### PR TITLE
[0.21] Additional backports

### LINKED ISSUE #22581: [0.21] test: assertion failed in feature_taproot.py
Seeing the same failure on a number of the 0.21 backport PRs. i.e https://cirrus-ci.com/task/5497683654737920:

```bash
168/194 - feature_taproot.py failed, Duration: 1248 s
stdout:
2021-07-29T09:23:04.366000Z TestFramework (INFO): Initializing test directory /tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_₿_🏃_20210729_091956/feature_taproot_172
2021-07-29T09:23:07.475000Z TestFramework (INFO): Post-activation tests...
2021-07-29T09:23:16.879000Z TestFramework (INFO): - Constructing addresses for returning coins
2021-07-29T09:23:17.297000Z TestFramework (INFO): - Creating test UTXOs...
2021-07-29T09:23:18.643000Z TestFramework (INFO): - Running 2740 spending tests
2021-07-29T09:23:44.188000Z TestFramework (INFO):   - 201 tests done
2021-07-29T09:24:12.165000Z TestFramework (INFO):   - 401 tests done
2021-07-29T09:25:01.751000Z TestFramework (INFO):   - 601 tests done
2021-07-29T09:25:39.542000Z TestFramework (INFO):   - 800 tests done
2021-07-29T09:26:23.207000Z TestFramework (INFO):   - 1001 tests done
2021-07-29T09:27:14.258000Z TestFramework (INFO):   - 1201 tests done
2021-07-29T09:28:12.163000Z TestFramework (INFO):   - 1402 tests done
2021-07-29T09:29:06.211000Z TestFramework (INFO):   - 1601 tests done
2021-07-29T09:29:49.906000Z TestFramework (INFO):   - 1800 tests done
2021-07-29T09:30:48.693000Z TestFramework (INFO):   - 2000 tests done
2021-07-29T09:32:02.797000Z TestFramework (INFO):   - 2201 tests done
2021-07-29T09:33:25.161000Z TestFramework (INFO):   - 2401 tests done
2021-07-29T09:34:37.826000Z TestFramework (INFO):   - 2601 tests done
2021-07-29T09:35:35.910000Z TestFramework (INFO):   - Done
2021-07-29T09:43:46.969000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 126, in main
    self.run_test()
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/feature_taproot.py", line 1466, in run_test
    self.sync_blocks()
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 615, in sync_blocks
    assert (all([len(x.getpeerinfo()) for x in rpc_connections]))
AssertionError
2021-07-29T09:43:46.975000Z TestFramework (INFO): Stopping nodes
2021-07-29T09:43:51.344000Z TestFramework (WARNING): Not cleaning up dir /tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_₿_🏃_20210729_091956/feature_taproot_172
2021-07-29T09:43:51.344000Z TestFramework (ERROR): Test failed. Test logging available at /tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_₿_🏃_20210729_091956/feature_taproot_172/test_framework.log
2021-07-29T09:43:51.344000Z TestFramework (ERROR): 
2021-07-29T09:43:51.344000Z TestFramework (ERROR): Hint: Call /tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/combine_logs.py '/tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_₿_🏃_20210729_091956/feature_taproot_172' to consolidate all logs
2021-07-29T09:43:51.344000Z TestFramework (ERROR): 
2021-07-29T09:43:51.345000Z TestFramework (ERROR): If this failure happened unexpectedly or intermittently, please file a bug and provide a link or upload of the combined log.
2021-07-29T09:43:51.345000Z TestFramework (ERROR): https://github.com/bitcoin/bitcoin/issues
2021-07-29T09:43:51.345000Z TestFramework (ERROR): 
```

### PR DESCRIPTION
**Pull request by fanquake**
This backports a few changes to fix CI failures we are seeing with the 0.21 branch.

Backports #21663, this might be the easiest way to fix the macOS CI failures we're seeing. i.e in #22569. The underlying issue is that the older CI images are using a version of brew that without running `brew update` first, is trying to download packages like Boost, from bintray (which no-longer works).

This also includes #20182, as by fixing macOS failure, via running `brew upgrade`, we end up using a newer version of miniupnpc, which emits a GNU extension related warning, and causes the build to fail, because we use `-Werror`.

Backporting #20535 should fix #22581.

### CODE REVIEW

**Comment by fanquake** [comment]
Changed this to just backport #21663. While this chance introduced a decent time hit to the CI,  it should be less of an issue in this branch, as the CI not only runs less frequently, but runs slower anyways due to Cirrus scheduling.

**Comment by fanquake** [comment]
Annoyingly, "fixing" the macOS brew means using a newer version of miniupnpc,  which emits a GNU extension related warning, and causes the build to fail, because we use `-Werror`. I think enabling `--suppress-external-warnings` is going to be the easiest fix, via backporting  #20182.

I've also added #20535 here to fix #22581.

**Comment by fanquake** [comment]
Looks like these fixes are working, and should be ok to merge. The [failure on the sanitizer job](https://github.com/bitcoin/bitcoin/pull/22578/checks?check_run_id=3191813816) is a timeout.

**Review by hebasto — APPROVED** [review]
ACK 55e941f5df18ce6d9b1ee8759f1419c5d1f03a8f, I verified changes by backporting locally.

**Pull request merged**
