### PR TITLE
update jonasschnellis gpg key

### PR DESCRIPTION
**Pull request by jonasschnelli**
Current key:
`dev@jonasschnelli.ch 0x29d4bcb6416f53ec / 416F53EC`

Old key (still in the pgp armored file):
`jonas.schnelli@include7.ch 0x2270e30c522739f6 / 522739F6`
(used for current gitian signatures)

Signed with my new key:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Adds my dev@jonasschnelli.ch GPG together with my old
jonas.schnelli@include7.ch (to verify gitian signatures) to the bitcoin
repository
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQIcBAEBAgAGBQJWRcmXAAoJECnUvLZBb1PsUTYP/jUmJll7TGXvZHd4oCiT/6Y/
16G7y/C0AqYcSZzeDPmASoWZyfbhY18k+8ekW/acH0NtV5bf3+uX3tDANf4c3jgD
37LlmtRS2LsFoEUCIbyO+pbgC11ZBucs4yOQNBak5MWY/3N/Kl3QNoRhjAV1vV5U
u5/uLDjgjbIZdetgHBiB55OEE7bcDh0+mCkg2hWHvUOIQS0IwLPlM07hIcIZH216
rluP4BlpH3JrHwU4IcyArFogDUS4+QU8G5RpBRrOgUJvL/uf5IUCG33pB/CVUeBM
ctRQjCms0ULUt5/l+kncWF2xC4CelgnkdykxVXoxJej1fLD/o/4WA/aScAZQuhkS
3gYuPh0M/QMqhEVtuifnrI+26+KyjtRc8hp0XEfp2HB3akqrGM6kDaHlZoVjkES1
+UXb7cRcM+k+ihIOqu2hh/dPFBTzsgaLMfouF20tnRMnPbJn7NQSKYBFX559JDb3
Ra+kfHlGKBKcT8ngFpreZXkZHpzKX90555Pi3maYuYcEZLVmf+xP3UWKjsXKPUCc
l+50P+DEIlVbg2sAhZEEWxtL4oTJOA+Rby0mwicj5tCyJGUcvectrC/PQF1guRrF
s1AUXANnfhLYeSBqbzucKNB7cI/NKXbGmYnlAt9RDY57IA254HLyfq3B/01USDCv
gF0bGXLNEjC9WjFfEdUo
=IVMl
-----END PGP SIGNATURE-----
```

Signed with my old key:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Adds my dev@jonasschnelli.ch GPG together with my old
jonas.schnelli@include7.ch (to verify gitian signatures) to the bitcoin
repository
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQIcBAEBAgAGBQJWRcnPAAoJECJw4wxSJzn2H1AP/jqs3I9ja1ALtYP8oSzSUrCG
JAP92lZUp2IABwVc1ZlBTh+9YU8WasRTGk7SZLljEaZYW2pZkPUAgWaJhki+7SlC
Xo9L2KnLzhkOoBUGRLHg/05V2WgbRLikXdjHyndMx7e+hWhB0hYTTdZUmu/Knq5k
bFB18cmsNGYOpTqvDhTsBG2Ha5av7KeKH8Nzg+gLKTG6MDQVUMjcCRqKKY/+vDmh
LTL8yP7WWnA8yOOHRTvG1xFcU1wfaU2n2PhnngWk6oS87JDiYuYQ/32zt1z5qfs0
baSSGh+VFtv3y4z5nApyizlvtjvmz7vcScQFNSqURvxcKnkqXN+2VcDgj9xVSihI
SxEFhGS8dUM6CyBWASqAxb2NVWfUik4QUWi86JJVjL1fEFWM9vxgj5Nu1uJTFaTX
g5iYcE6AlSuoFWYl1rG/uavhPsdqUPqt6S9qmm7JxrK5SbK8BM6cHhKPjKfU7vy0
wYaOg75XERdL7BMibtUj0UQ0b525DCJq3+2W/wr3nVKUyZ3zqVWaZMS/RfInP31P
YltlVCMWGfcy2a6gTMZnFEtyf1Am+UMpInCP5XvbmsDdBDxvhjeP64vPtMUdPxu4
A+wXHBXayAwJgPrkjXREDW/grwdxc5LResa1Vi+AjI6ixIp3x32Kkle2NHZInqiP
cL3pLs5OmxWoevVx2nuf
=or9p
-----END PGP SIGNATURE-----
```

### CODE REVIEW

**Comment by jonasschnelli** [comment]
you are welcome to sign my current key 0x29D4BCB6416F53EC (dev@jonasschnelli.ch) :)

**Comment by laanwj** [comment]
Also add your key id to `contrib/verify-commits/trusted-keys`, otherwise @TheBlueMatt 's tool will croak when you merge something.

**Comment by jonasschnelli** [comment]
Added my current key fingerprint to `contrib/verify-commits/trusted-keys`

**Comment by fanquake** [comment]
utACK

**Comment by laanwj** [comment]
ACK

**Pull request merged**
