### PR TITLE
Fixed some typoes in norwegian translation.

### PR DESCRIPTION
**Pull request by halvors**
Fixes some very minor but annoying typos in the Norwegian translation.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Awesome. Thanks for helping with translations!

Changes to translations as well as new translations can be submitted to
[Bitcoin Core's Transifex page](https://www.transifex.com/projects/p/bitcoin/).

Translations are periodically pulled from Transifex and merged into the git repository. See the
[translation process](https://github.com/bitcoin/bitcoin/blob/master/doc/translation_process.md) for details on how this works.

**Important**: We do not accept translation changes as GitHub pull requests because the next
pull from Transifex would automatically overwrite them again.

**Comment by halvors** [comment]
@MarcoFalke Ah i see. Did you update Transifex with the changes of this pull request or should i? :)

**Comment by MeshCollider** [comment]
@halvors it would be much appreciated if you could :)

**Comment by MarcoFalke** [comment]
@halvors No, I am not part of the norwegian translation team. Thus, can not change those translations.

**Pull request closed without merging**
