### PR TITLE
[refactor, move-only-ish] Refactor mempool accept/reject logic

### PR DESCRIPTION
**Pull request by skeees**
This commit is *almost* a move-only* and a fairly straightforward refactor which moves the p2p logic when a transaction received over the wire is accepted or rejected into their own functions instead of being embedded directly in ProcessMessages().

Motivation: as a follow-up to #12934, I'm working on putting mempool acceptance behind a similar type of asynchronous queue. In order to do that, ATMP response logic in p2p needs to be cleanly separated out into separate functions. 

*Note that this commit introduces one behavior change: Currently, if -promiscuousmempool is set (only allowed on regtest and testnet), it is possible for AcceptToMemoryPool() to return true, but for the CValidationState() to contain DoS points if the transaction failed validation with policy standard script flags but then passed with promiscuous flags. This will cause you to ban the peer who sent the transaction. This commit fixes this behavior by reseting the validation state in that one situation.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Concept ACK. I believe this makes dandelion easier to implement.

**Review by jamesob — COMMENTED** [review]
Looks good, though it would be nice to at least separate the behavior change and the refactoring into separate commits (if not separate PRs - though I can see how the process here motivates you to bundle the two).

**Comment by skeees** [comment]
Thanks @jamesob - addressed comments

**Review by jamesob — APPROVED** [review]
utACK https://github.com/bitcoin/bitcoin/pull/13407/commits/2567ef43f3efd99ed08a5eb841251ed9111732d3

In my last set of comments, I reviewed https://github.com/bitcoin/bitcoin/commit/4c9e9e7c7468b60172d4736455a0b5b11ca4f354.diff (which can be verified by checking the URL of the "View Changes" button associated with those comments). The [change since then](https://gist.github.com/jamesob/3f95070e03d9fce399778f60271001c1) only addresses my three comments.

The changes in this PR should be pretty well covered by `test/functional/mempool_*`. The only non-move difference I can see beyond the noted `-promiscuousmempool` change are two assertions introduced in `ProcessMessage` (https://github.com/bitcoin/bitcoin/pull/13407/files#diff-eff7adeaec73a769788bb78858815c91R2207, https://github.com/bitcoin/bitcoin/pull/13407/files#diff-eff7adeaec73a769788bb78858815c91R2210) which look sensible. 

Generally, I think this kind of refactoring is good - extracting functions makes important code like this easier to follow and more testable. Not to mention the motivating change (making mempool acceptance async) is very worthwhile.

**Comment by sipa** [comment]
Concept ACK

**Comment by Empact** [comment]
Could benefit from clang-format

**Comment by skeees** [comment]
rebased

**Comment by MarcoFalke** [comment]
>  Needs rebase 

due to "policy: Remove promiscuousmempoolflags #13527"

**Comment by skeees** [comment]
rebased (dropped cf36b6) as @MarcoFalke has addressed that in #13527

**Pull request closed without merging**
