### PR TITLE
trivial: correct parameter name in comments

### PR DESCRIPTION
**Pull request by andrewtoth**

### CODE REVIEW

**Comment by MeshCollider** [comment]
trivial ACK https://github.com/bitcoin/bitcoin/pull/15380/commits/1a0139cbaf5293914b07c6301225272bd5a836a7

**Review by kristapsk — APPROVED** [review]
utACK 1a0139cbaf5293914b07c6301225272bd5a836a7

**Comment by promag** [comment]
utACK 1a0139c.

**Comment by fanquake** [comment]
utACK 1a0139c

**Comment by practicalswift** [comment]
utACK 1a0139cbaf5293914b07c6301225272bd5a836a7

**Pull request merged**
