### PR TITLE
Enable mempool consistency checks in unit tests

### PR DESCRIPTION
**Pull request by sipa**
This helped me discovered #8220.

I can't measure any slowdown for running the unit tests.

### CODE REVIEW

**Comment by petertodd** [comment]
Concept ACK

**Comment by MarcoFalke** [comment]
utACK 3775ff9

**Comment by gmaxwell** [comment]
Tested ACK.   Just a very slight reservation that perhaps a consistency check being enabled someday hides a bug.

**Comment by laanwj** [comment]
Sounds like a good idea to me, concept ACK.

> Just a very slight reservation that perhaps a consistency check being enabled someday hides a bug.

This just adds checks I, hope? It doesn't ever *correct* consistency?

**Pull request merged**
