### PR TITLE
0.12 release notes: Sort by importance to usability

### PR DESCRIPTION
**Pull request by xor-freenet**
## Changes

Move stuff of the following categories to the to the top of the notes, in this descending order by how important I consider it:
1. CPU usage (= libsecp256k1)
2. Disk usage (= pruning)
3. Memory usage (= mempool limiting)
4. Network usage (= upload limit)
5. Security (= negative confirmations, Tor)

Reasons for this choice: CPU, disk, memory and network are what will cause the most visible annoyance to the user, so they're first. With money, security is important as well, so that's also bumped.

This PR only moves the stuff which I think is understandable to an average user.
In other words, I didn't touch the more technical stuff which will be difficult to grasp.
If you want me to sort that as well, feel free to suggest what to move where.
### Bonus change

There was an empty line which I think made no sense, I removed it in 302af5424156584d71d17aa6b211c55a9336.
## Open questions

I actually think the potential ~ 60 GB disk usage reduction by pruning is the most important change, not the 5x signature validation CPU usage reduction by libsecp256k1: CPU cycles are continuously "produced" by the users machine, but the available disk space is usually fixed. And 60 GB is _a lot_!
But as I'm biased by having a small SSD in my laptop, I would please like to first request reviewers to voice a vote on whether I should move pruning above libsecp256k1 or not?

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Hmm... importance is relative.
The wallet (so wallet & pruning) is probably not the most relevant topic. Mempool limitation and opt-in RBF are – IMO – far more relevant for the 0.12 release.
I tend to keep the current order.

**Comment by xor-freenet** [comment]
> The wallet (so wallet & pruning) is probably not the most relevant topic.

I totally appreciate the effort of people who run nodes solely for the purpose of running a node; or for mining. But both are expert usecases. 
The wallet on the other hand is a non-technical usecase. And we can assume that the average user is not an expert who does highly technical stuff. So by assuming that usability work should target the average user, can we agree that the wallet is important then?

**Comment by xor-freenet** [comment]
> [...] and opt-in RBF are – IMO – far more relevant for the 0.12 release.

I didn't push opt-in RBF because there is no UI for it yet, and thus it is not relevant to an average wallet user:
> Note that the wallet in Bitcoin Core 0.12 does not yet have support for creating transactions that would be replaceable under BIP 125.

**Comment by MarcoFalke** [comment]
I agree with @jonasschnelli: Importance is hard to evaluate so that everyone agrees. Some sections could be reordered but I think we don't want to create merge conflicts with other release note pull either.

I'd rather keep the current order, as the release notes are already referred to from other places and reordering could potentially destroy references.

**Comment by xor-freenet** [comment]
> Some sections could be reordered but I think we don't want to create merge conflicts with other release note pull either.

Git could be able to deal with that, I'm not sure.
Also notice: I've intentionally put each moved section in a commit of its own. So if you only agree with some of the moving, then the other commits could be left out.

> I'd rather keep the current order, as the release notes are already referred to from other places and reordering could potentially destroy references.

Links to sections in GitHub markdown reference the key of a section, not its line number. Example
> https://github.com/bitcoin/bitcoin/blob/v0.11.0/doc/release-notes.md#block-file-pruning

**Comment by laanwj** [comment]
Thanks for thinking about this.
But I'm not convinced either that this order is much better. I already sorted it, more or less, by importance in the beginning.
Also: Security is our priority #1, not the other way around.

**Comment by laanwj** [comment]
Closing - 0.12.0 final has been tagged, no longer possible to make changes here

**Pull request closed without merging**
