### PR TITLE
Move CBlockTreeDB to node/blockstorage

### PR DESCRIPTION
**Pull request by maflcko**
The block index (`CBlockTreeDB`) is required to write and read blocks, so move it to blockstorage

### CODE REVIEW

**Comment by practicalswift** [comment]
Concept ACK

**Comment by mostafarahimifard** [comment]
مرسی گلم

**Comment by theStack** [comment]
Concept ACK

**Comment by MarcoFalke** [comment]
Please review #22371 first

**Comment by fanquake** [comment]
Concept ACK - want to rebase/fixup this?

**Pull request closed without merging**
