### PR TITLE
Order CTxMemPool::queryHashes result by feerate including descendents.

### PR DESCRIPTION
**Pull request by pstratem**

### CODE REVIEW

**Comment by sdaftuar** [comment]
Motivation?  Curious whether whatever you're using this for should be using descendant fee rate or ancestor fee rate (see #7594)...

**Comment by pstratem** [comment]
@sdaftuar the motivation is two part

first to ensure mempool walks are in an order which avoids any orphans

second to make the feefilter command more efficient in combination with the mempool p2p command

**Comment by pstratem** [comment]
@sdaftuar is right this should be using ancestor indexing

**Comment by sipa** [comment]
@pstratem Can you elaborate? How does this guarantee the avoidance of orphans? Transaction descendants can have both higher or lower feerate than the parent.

**Comment by pstratem** [comment]
@sipa it doesn't i mis understood what was being indexed.

i'll fix this properly later

**Pull request closed without merging**
