### PR TITLE
Fix translations in en_US.ts

### PR DESCRIPTION
**Pull request by drodil**
Translate some Chinese characters back to English.

### CODE REVIEW

**Comment by Michagogo** [comment]
I don't know if this is how this’ll be fixed - not sure what the policy is, but translation updates are usually done via Transifex.

**Comment by Sjors** [comment]
Translations should indeed go through Transifex: https://github.com/bitcoin/bitcoin/blob/master/doc/translation_process.md#helping-to-translate-using-transifex

**Comment by drodil** [comment]
Did the fix to Transifex also.

**Comment by laanwj** [comment]
I'll remove the en_US translation from Transifex completely. It seems pointless.

**Comment by laanwj** [comment]
fixed through ea2e39fd2004e83375c1703543e32a10e3b9d981

**Pull request closed without merging**
