### PR TITLE
build: ignore common editor files

### PR DESCRIPTION
**Pull request by Bushstar**
Add IntelliJ and Visual Studio Code editor files to .gitignore. Small QOL change :)

### CODE REVIEW

**Comment by fanquake** [comment]
NACK. Feel free to add to your local (global) .gitignore.

**Comment by Bushstar** [comment]
If so should the Qt Creator entry be removed or leave it as this project uses Qt?

**Comment by willcl-ark** [comment]
@Bushstar I add project specific things to `.git/info/exclude` inside the project. But perhaps more helpful for you if you are using an IDE like that is if you add a global gitignore and reference it in your git config:

```
[core]
	excludesfile = /path/to/your/gitignore_global
```

Then you'll never be bothered by it again yourself.

**Comment by fanquake** [comment]
> If so should the Qt Creator entry be removed or leave it as this project uses Qt?

Can probably just leave things as-is. At some point we had instructions for using Qt Creator.

**Comment by Bushstar** [comment]
@willcl-ark top tips. I now have a global .gitignore file.

**Pull request closed without merging**
