### PR TITLE
[Doc] Update implemented BIPs list

### PR DESCRIPTION
**Pull request by fanquake**

### CODE REVIEW

**Comment by sipa** [comment]
ACK. We should not forget to include to update this again when the CSV softfork triggers, though.

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/8121/commits/e4f73c76b3a408037fdf32d9700d57f3d0e77a47

**Comment by laanwj** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/8121/commits/e4f73c76b3a408037fdf32d9700d57f3d0e77a47

> We should not forget to include to update this again when the CSV softfork triggers, though.

Yes, let's open an issue for post-CSV-softfork trigger TODOs.

**Comment by fanquake** [comment]
@laanwj done in #8131

**Pull request merged**
