### PR TITLE
[debian] Bump manpages and only mention -?

### PR DESCRIPTION
**Pull request by maflcko**
The manpages are outdated and are very rarely updated when changes to the code happen. (Especially the bitcoind commands, which are even outdated in our own source code)

As long as there is no maintainer for the manpages, it should be sufficient to mention `bitcoin[d|-cli|-qt] -?`.

Edit: Links to #1040

### CODE REVIEW

**Comment by luke-jr** [comment]
Weak NACK. Maybe add a comment to init.cpp to update them. Or better yet, write a script to automate updating them..

**Comment by MarcoFalke** [comment]
> add a comment to init.cpp

You'd also have to add the comment to rpc*.cpp but I guess this won't work if authors forget to read/update those files in the first place.

> write a script to automate updating

This should work but what is the point in duplicating all this information?

**Comment by luke-jr** [comment]
manpages are the go-to source for information on *nix.

**Comment by petertodd** [comment]
utACK https://github.com/MarcoFalke/bitcoin/commit/fa6ce44bf98fe1dd5be779fd77b844e7016d209e

Better empty than wrong!

**Comment by laanwj** [comment]
> Better empty than wrong!

ACK. Agreed. If someone wants to make a script to automatically update the manpages from --help I certainly encourage that, but up to then, this is very true.

**Pull request merged**
