### PR TITLE
net: Only use TorControl connection as proxy if proxy is not set yet

### PR DESCRIPTION
**Pull request by fjahr**
Should close #25265

The onion proxy can be set either via `-onion` or via `-proxy` (grep `init.cpp` for `onion_proxy`). Additionally, when TorControl is configured and successfully connected, there is a fallback that tries to setup the onion proxy via that connection. This fallback was only checking if `-onion` was set but if `-proxy` was set it was still running and overwriting the existing onion proxy configured in `-proxy`.

Instead of using `gArgs` I am checking if a valid proxy is set already. This should not make a difference in behavior since init error are thrown if `-onion` or `-proxy` are set but not valid. There is also another check if `-onion` or `-proxy` are explicitly disabled. I think this is the most reasonable behavior for such corner cases, though I am not sure if there are valid use cases for such a configuration.

This also adds some more explicit logging that should help users better understand what is happening.

### CODE REVIEW

**Comment by fjahr** [comment]
@kroese could you check if this solves your problem from #25688?

**Comment by 1440000bytes** [comment]
Concept ACK

**Comment by luke-jr** [comment]
Concept NACK. `-torcontrol` *should* override `-proxy`. (Plus, using GetProxy for the check will fail to update it when/if it changes during runtime.)

**Comment by fjahr** [comment]
> Concept NACK. `-torcontrol` _should_ override `-proxy`. (Plus, using GetProxy for the check will fail to update it when/if it changes during runtime.)

For anyone interested in following, I answered [here](https://github.com/bitcoin/bitcoin/issues/25265#issuecomment-1195891852). I would say let's keep the conceptual discussion about parameter interaction in the issue @luke-jr, so we don't have to argue the same things in two places.

**Comment by fjahr** [comment]
Closing this, see discussion in #25265.

**Pull request closed without merging**
