### PR TITLE
Descriptor Wallets BIP39 recovery

### PR DESCRIPTION
**Pull request by ghost**
./src/bitcoin-cli sethdseed true "ffffffffffffffffffffffffffffffff" hex
./src/bitcoin-cli sethdseed true "zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo wrong" mnemonic

works only for new type of wallet

### CODE REVIEW

**Comment by luke-jr** [comment]
>if you have seed words enter them in https://iancoleman.io/bip39/ and get the entropy (Show entropy details)

Please don't encourage people to enter private seed information into web browsers!

**Comment by achow101** [comment]
NACK

`sethdseed` should not be enabled for descriptor wallets. It completely destroys the purpose of using descriptor wallets because it will reintroduce the ambiguity about what kind of addresses are in the wallet. If you want to have BIP 39 in descriptors, then do BIP 39 in descriptors themselves. Users could then import a descriptor containing a BIP 39 seed via `importdescriptors`. Don't do this thing where we try to make descriptor wallets have an hd seed (they really don't) and then set that seed. That's a legacy wallet thing.

**Comment by fanquake** [comment]
> just a weekend hack, but maybe if will be usefull for somebody

PR's opened against this repo should contain code that is ready to be reviewed by other contributors. If you're looking for conceptual review or want to discuss a new feature/idea, you can open a draft PR (this will avoid some of the notifications generated by our bot), or an issue. We'd also prefer if you didn't do your development by continually force-pushing to the branch, as that just spams anyone subscribed to the repository with emails.

Please also read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md).

**Comment by mateusz-klatt** [comment]
closing review, leaving as a patch for personal use if i will need to get access to BIP39 protected wallet

**Pull request closed without merging**
