### PR TITLE
Simple mempool protect

### PR DESCRIPTION
**Pull request by morcos**
Built off of #6654, this implements an exponential rising effective min relay feerate.   This version implements 50 bands of 10% increase which is slightly over 100x at the top end.  Thus 100x the configured min relay rate must be more than enough to dissuade spam.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Seems to work (bitcoind master with -maxmempool=1):

Green line (dynamic mem usage) keeps under 1MB:
bildschirmfoto 2015-09-14 um 18 05 58
bildschirmfoto 2015-09-14 um 18 06 09

**Comment by dcousens** [comment]
concept ACK,  a lot of code though

**Comment by jonasschnelli** [comment]
Somehow I can't see the new log messages "insufficient fee for mempool size" or "mempool full hard cap" in my debug.log. Maybe its worth analyzing why.. it looks like that the transactions get always rejected because of `mapOrphan overflow, removed 1 tx`.

**Comment by morcos** [comment]
Closing in favor of #6722

**Pull request closed without merging**
