### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by practicalswift**
Fix typos.

### CODE REVIEW

**Comment by fanquake** [comment]
Can you try an combine this, cherry pick or not, with #12716. I don't think we need multiple (whole repo type) typo fixing PRs open at the same time.

**Comment by practicalswift** [comment]
@fanquake They are not overlapping from what I can see. Should I cherry-pick 4d9b4256d89d1f7c6b3e4938ab2e89cde296e8e8 into this PR?

**Comment by practicalswift** [comment]
@fanquake #12716 is now merged :-)

**Comment by hkjn** [comment]
utACK d27327c.

**Comment by sipa** [comment]
utACK d27327c79a651fab77e032fa1f00ce4458db959b

**Pull request merged**
