### PR TITLE
build: Skip i686 build by default in guix and gitian

### LINKED ISSUE #17504: Should we still ship 32-bit x86 Linux binaries?
I don't think there's any hurry to do this, just opening an issue as #17503 made me wonder.

In general, running bitcoind in 64 bit is unarguably better. 64-bit registers result in better validation performance and it allows leveldb to use mmap without worrying about virtual memory usage.

Back in the day, the rationale for removing 32-bit x86 builds for Windows but not Linux was that some cheapo VPS still used x86-32 bit.

Is this still the case in the year of (almost) 2020? Is anyone running x86-32 VMs for other purposes than testing software on that architecture? Even with that, how much testing are these binaries getting?

(to be clear, I'm not arguing to *remove support for 32-bit*, just to stop building and providing binaries for it. I also think ARM is a different matter.)

### PR DESCRIPTION
**Pull request by maflcko**
Closes #17504 

Now that we no longer provide downloads for i686 on our website (https://bitcoincore.org/en/download/), there is no need to build them by default.

i686 can still be built in depends (tested by ci/travis) and in guix/gitian by setting the appropriate `HOSTS`.

### CODE REVIEW

**Comment by laanwj** [comment]
Code review ACK fae9084ac5b10f94bdee54853d307838c4254e9c
Travis fail is the usual s390 fail.

**Review by hebasto — APPROVED** [review]
ACK fae9084ac5b10f94bdee54853d307838c4254e9c, I have reviewed the code and it looks OK, I agree it can be merged.

**Comment by practicalswift** [comment]
ACK fae9084ac5b10f94bdee54853d307838c4254e9c -- patch looks correct

**Comment by dongcarl** [comment]
Nice! Could probably also remove https://github.com/bitcoin/bitcoin/blob/4c2578706c70148fc001f42a0918a2fb10252b43/contrib/guix/manifest.scm#L150 but not a huge deal.

**Comment by dnprock** [comment]
@MarcoFalke I came across this PR. I notice there's still references to i686 in gitian-linux descriptor.

https://github.com/MarcoFalke/bitcoin-core/blob/fae9084ac5b10f94bdee54853d307838c4254e9c/contrib/gitian-descriptors/gitian-linux.yml#L103

Should they be removed as well?

**Comment by hebasto** [comment]
@dnprock 
> @MarcoFalke I came across this PR. I notice there's still references to i686 in gitian-linux descriptor.
> 
> https://github.com/bitcoin/bitcoin/blob/master/contrib/gitian-descriptors/gitian-linux.yml#L103
> 
> Should they be removed as well?

Mind submitting a pull request?

**Pull request merged**
