### PR TITLE
Blocksize: Some small preparations for a blocksize hardfork

### PR DESCRIPTION
**Pull request by jtimon**
Replaces #6625 (contains commits from #6526).

### CODE REVIEW

**Comment by maaku** [comment]
What's the reasoning for nMaxTransactions?

**Comment by jtimon** [comment]
More flexibility in the code for when MAX_BLOCK_SIZE is no longer a constant.

**Comment by maaku** [comment]
Perhaps my question wasn't clear -- why limit the number of transactions at all? We should probably do overflow checks (which would mean a real limit of 4 billion transactions), but I'm not sure why this would ever be a constrained parameter.

**Comment by jtimon** [comment]
I guess another option would be to just replace ```MAX_BLOCK_SIZE / 60``` with a static constant in merkleblock.cpp.
What you are saying is that changing that constant to a huge value wouldn't be a hardfork and it's therefore easier to just decouple merkleblock.cpp from MAX_BLOCK_SIZE, correct?

**Comment by maaku** [comment]
That check is really just a sanity check, and IMHO shouldn't be there as Merkle trees are used for other purposes. There is no reason to explicitly limit the number of transactions, and a generic merkle tree validator shouldn't have such a limitation built into it.

**Comment by jtimon** [comment]
Ok, so you suggest to just remove the check then?

**Pull request closed without merging**
