### PR TITLE
test: moved from percent format to proper format for consistency

### PR DESCRIPTION
**Pull request by sanjaykdragon**
Simple changes some of the python test related files. 
I converted from the old % format, ex:
"test %s" % "hello"
to the new str.format:
"test {}".format("hello")

This is more modern, as well as more consistent with the rest of the codebase (I have looked around and seen str.format used)

### CODE REVIEW

**Comment by practicalswift** [comment]
@sanjaykdragon How were these 15 instances chosen? :)  AFAICT we have 247 instances of the old printf-style string formatting in our codebase:

```
$ git grep "['\"] % " -- "*.py" | wc -l
247
```

_If_ we are to do something like this I suggest looking [`pyupgrade`](https://github.com/asottile/pyupgrade) which performs automatic conversion from the old printf-style string formatting to `.format(…)` :)

(Personally I don't have any strong opinion about this: just suggesting the proper tooling.)

**Comment by jonatack** [comment]
Welcome @sanjaykdragon and thank you for your contribution.

I could be wrong, but usually, style cleanups are done while touching the same code for other reasons. For more information about stylistic cleanup, see:

- [CONTRIBUTING.md#refactoring](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#refactoring)

If you're looking for ways to start contributing to the project, here is a great place to begin:

- [CONTRIBUTING.md#getting-started](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#getting-started)

**Comment by promag** [comment]
+1 what @practicalswift said, as long as this doesn't conflict with other changes.

**Comment by jonatack** [comment]
TBH, that contributing guide statement to not submit refactoring PRs stopped me from doing so for the first full year, and meanwhile I've seen a number of new contributors begin with refactoring critical code and seen it both appreciated and merged. So I'm not sure if that statement is valid and should be in the guide.

Here though, it's a pure style change. Once again maybe wrongly, I thought that they weren't accepted from new people. Maybe I should not have read the docs as much :smile:

**Comment by promag** [comment]
@jonatack I welcome style changes if then are in separate commit and simplify the PR while avoiding unnecessary style comments.

**Comment by sanjaykdragon** [comment]
> 
> 
> @sanjaykdragon How were these 15 instances chosen? :) AFAICT we have 247 instances of the old printf-style string formatting in our codebase:
> 
> ```
> $ git grep "['\"] % " -- "*.py" | wc -l
> 247
> ```
> 
> _If_ we are to do something like this I suggest looking at [`pyupgrade`](https://github.com/asottile/pyupgrade) which can perform automatic conversion from the old printf-style string formatting to `.format(…)` :)
> 
> [`pyupgrade`](https://github.com/asottile/pyupgrade) is a tool (and pre-commit hook) to automatically upgrade syntax for newer versions of the language. Try `pip3 install pyupgrade && pyupgrade $(git ls-files -- "*.py") && git diff` to see the suggested changes.
> 
> (Personally I don't have any strong opinion about this: just suggesting the proper tooling.)

I lowkey fear using automated tools on a big repo. I changed the files manually, although I probably should have automated it. pyugprade looks pretty interesting though

**Comment by sanjaykdragon** [comment]
> 
> 
> TBH, that contributing guide statement to not submit refactoring PRs stopped me from doing so for the first full year, and meanwhile I've seen a number of new contributors begin with refactoring critical code and seen it both appreciated and merged. So I'm not sure if that statement is valid and should be in the guide.
> 
> Here though, it's a pure style change. Once again maybe wrongly, I thought that they weren't accepted from new people. Maybe I should not have read the docs as much 😄

I have seen a pretty mixed bag on this, and I don't know if i would consider this file critical code. I expect refactoring the consensus area would be more scrutinized

**Comment by fanquake** [comment]
~0. This is what is stated in the [style guidelines for the functional tests](https://github.com/bitcoin/bitcoin/blob/master/test/functional/README.md#style-guidelines), but there's a chance these will all be changed again, to `f"something {arg}"` once we move to supporting 3.6+ (#13718), so I don't think theres' any rush to go through and chance all these now.

**Pull request closed without merging**
