### PR TITLE
[QT] Optimize spinner

### PR DESCRIPTION
**Pull request by GChuf**
Use 48px spinner as source
Optimize files with crushing and png indexing
File sizes reduces by ~85%

### CODE REVIEW

**Comment by MarcoFalke** [comment]
bitcoin-qt is already 34M, I don't think 35kB matter much

**Comment by promag** [comment]
Not worth it IMO.

**Comment by GChuf** [comment]
Of course, ~70kB less hardly matters but i don't see any reason why not to do it

**Comment by MarcoFalke** [comment]
The reason not to do it is that git can't compress binary files, and has to keep both versions. So reducing the size will *slow down* git clone

**Comment by MarcoFalke** [comment]
Another reason to not do it is that this needs a lot of testing (mac, wayland, x11, windows) x (low dpi, high dpi) x (before, after). This test matrix has 16 values

**Comment by GChuf** [comment]
I don't understand the part about compression. Can you elaborate?
If I understand, git compresses data before a user runs "git clone". If binary files can't be compressed, isn't it best for the binary files to be as small as possible?

**Comment by MarcoFalke** [comment]
>  isn't it best for the binary files to be as small as possible?

Yes, but git keeps the history of all files, so once it is in git there is no way to get it out or compress it.

**Comment by fanquake** [comment]
Thanks, however I agree with the @MarcoFalke, and this isn't mergeable as is, because you haven't used a proper commit message.

**Comment by GChuf** [comment]
Thanks for explanations @MarcoFalke

**Pull request closed without merging**
