### PR TITLE
[tests] Remove accounts from wallet_importprunedfunds.py

### PR DESCRIPTION
**Pull request by jnewbery**
This was split from #13075 to not block review/merge of that PR.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
@jnewbery Mind doing a rebase on master, since the last travis run (https://travis-ci.org/bitcoin/bitcoin/builds/373612454) was about two months ago.

**Comment by jnewbery** [comment]
Rebased on master. I can no longer repro the OOM locally (tried running the test 100 times), and Travis passes. @MarcoFalke - can you try running this locally?

I'm removing the **[Do not merge]** tag, since if this runs reliably it's ready for merge.

**Comment by MarcoFalke** [comment]
@jnewbery Good to hear your tested ack on  0882406 ;)

**Comment by MarcoFalke** [comment]
Concept ACK 38040c34e1e71ee4b6b56a018f742c8b03546b75

Going to take a closer look later

**Comment by MarcoFalke** [comment]
utACK 38040c34e1

**Pull request merged**
