### PR TITLE
[NO MERGE] Travis: Run nightly test suite

### PR DESCRIPTION
**Pull request by maflcko**
Ideally we want to detect fails in the extended suite early (i.e. in the PR which caused the fail). Though, this would double the runtime of the rpc tests in every PR from 5 to 10 minutes (with `pruning.py` disabled).

Also, we'd want to collect `--coverage` data until all rpcs are covered and then fail on uncovered (new) rpcs.

For now, every 24 hours a fresh nightly build is triggered _within this PR_.

**Current status:**
- Disable usual rpc tests and `make check`, otherwise travis will block the build exceeding the 2 hour max CPU time.
- Disable `pruning.py`
- Run extended coverage rpc tests once with `CPPFLAGS=-DDEBUG_LOCKORDER`
- Verify subtrees
- ~~Enable qt4 build~~

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Travis vanilla will not support nightly builds, but there are 3rd party apps available if this is a direction to take:
https://github.com/travis-ci/travis-ci/issues/582#issuecomment-10366023
https://github.com/travis-ci/travis-ci/issues/582#issuecomment-123484647

**Comment by jonasschnelli** [comment]
Am i right: every 24h this PR get's updated with the current master (over an external script) and makes this PR act as a nightly build?

**Comment by MarcoFalke** [comment]
Yes, pretty much like that right now.

**Comment by laanwj** [comment]
Seems like a good idea.

**Comment by MarcoFalke** [comment]
@sdaftuar `maxuploadtarget` failed again. Mind to look at this? (I couldn't reproduce locally)

```
Running 2nd level testscript maxuploadtarget.py ...
start_node: bitcoind started, calling bitcoin-cli -rpcwait getblockcount
start_node: calling bitcoin-cli -rpcwait getblockcount returned
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11593
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11593
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11593
Assertion failed: 2 != 3
  File "/home/travis/build/bitcoin/bitcoin/bitcoin-i686-pc-linux-gnu/qa/rpc-tests/test_framework/test_framework.py", line 135, in main
    self.run_test()
  File "/home/travis/build/bitcoin/bitcoin/bitcoin-i686-pc-linux-gnu/qa/rpc-tests/maxuploadtarget.py", line 203, in run_test
    assert_equal(test_nodes[0].block_receive_map[big_old_block], i+1)
  File "/home/travis/build/bitcoin/bitcoin/bitcoin-i686-pc-linux-gnu/qa/rpc-tests/test_framework/util.py", line 394, in assert_equal
    raise AssertionError("%s != %s"%(str(thing1),str(thing2)))
Stopping nodes
Cleaning up
Failed
Traceback (most recent call last):
  File "qa/pull-tester/rpc-tests.py", line 256, in <module>
    runtests()
  File "qa/pull-tester/rpc-tests.py", line 175, in runtests
    rpcTestDir + testScriptsExt[i] + flags, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/home/travis/build/bitcoin/bitcoin/bitcoin-i686-pc-linux-gnu/qa/rpc-tests/maxuploadtarget.py --srcdir /home/travis/build/bitcoin/bitcoin/bitcoin-i686-pc-linux-gnu/src --coveragedir /tmp/coveragesoVFH4 ' returned non-zero exit status 1

**Comment by sdaftuar** [comment]
@MarcoFalke Strange, I don't understand how that error can happen, but one thing I noticed is that there should be a `with mininode_lock:` guarding the `assert_equal(test_nodes[0].block_receive_map[big_old_block])` line.  Still, I can't come up with a logical scenario where there's actually a race condition there (but acquiring the lock is the right way to ensure there is no race, since both threads are updating that variable).

If we can't come up with other ideas, perhaps we can make that fix and see if the problem recurs...

**Comment by laanwj** [comment]
@MarcoFalke can you please include #7142 into this?

**Comment by MarcoFalke** [comment]
@laanwj Done!

**Comment by MarcoFalke** [comment]
Current status:
* Disable rpc tests and `make check`, otherwise travis will block the build exceeding the 2 hour max CPU time.
* Disable `pruning.py`
* Enable extended coverage rpc tests once
* Enable qt4 build

**Comment by arowser** [comment]
Can one of the admins verify this patch?

**Comment by sipa** [comment]
@arowser Have you even looked at this patch yourself? It is not intended to be merged, as it is automatically retriggered every 24h to detect bugs only caught by the extended tests. Please stop pinging every single pull request. Repository maintainers merge when there is sufficient agreement and review done, but they are not the only ones who do reviews. If you want to help merging things, please review yourself.

**Comment by sipa** [comment]
@arowser Furthermore, I consider the many comments you've left as spam, and I'll delete them when I encounter them. Please don't do that again, or I'll report it as abuse.

**Comment by MarcoFalke** [comment]
Noting failure in feefilter:


```
  File "/home/travis/build/bitcoin/bitcoin/build/../qa/rpc-tests/p2p-feefilter.py", line 101, in run_test

    assert(allInvsMatch(txids, test_node))

**Comment by sdaftuar** [comment]
@MarcoFalke I figured out the feefilter issue.  Looks like sometimes the second-to-last test generates transactions which don't relay within 10 seconds, and then get relayed after the feefilter is updated in the last test.

**Comment by MarcoFalke** [comment]
Failure in segwit.py: https://travis-ci.org/bitcoin/bitcoin/jobs/152860836#L2336

```
Verify sigops are counted in GBT with pre-BIP141 rules before the fork
Assertion failed: 599.98800000 != 999.980

   File "/home/travis/build/bitcoin/bitcoin/qa/rpc-tests/test_framework/test_framework.py", line 148, in main
    self.run_test()
  File "/home/travis/build/bitcoin/bitcoin/build/../qa/rpc-tests/segwit.py", line 167, in run_test
    assert_equal(self.nodes[2].getbalance(), 20*Decimal("49.999"))
  File "/home/travis/build/bitcoin/bitcoin/qa/rpc-tests/test_framework/util.py", line 504, in assert_equal
    raise AssertionError("%s != %s"%(str(thing1),str(thing2)))

**Comment by da2ce7** [comment]
@MarcoFalke, what is the status of this pull request?  Do you wish to rebase?

**Comment by laanwj** [comment]
This pull is not intended to be merged, it just re-pushes (and re-bases)
regularly to run Travis w/ full test suite, which is too slow for automatic use.

**Comment by TheBlueMatt** [comment]
Maybe the PR title should be updated to indicate this?

**Comment by jnewbery** [comment]
Now that Travis supports cron jobs, can this be replaced with something like #10052? I'm happy to help merging them if you think that's useful.

**Comment by TheBlueMatt** [comment]
I believe this can be closed now?

**Comment by jnewbery** [comment]
This seems to include tests that aren't covered by the travis cron job, namely valgrind, testing salvagewallet and a new compatibility functional test. @MarcoFalke - do you think those should be merged into master to be run by the cron job? If so, I'm happy to help with merging/reviewing.

**Comment by MarcoFalke** [comment]
@jnewbery Most of the code here is just a reminder for myself to look further into that topic. Not really ready to be merged or put into our travis yaml, as the diff needs to be adjusted every couple of weeks.

**Pull request closed without merging**
