### PR TITLE
Updating default max block size

### PR DESCRIPTION
**Pull request by Cannon-Ciota**
Removing artificial limit in max block size from 750KB to 1MB.

### CODE REVIEW

**Comment by paveljanik** [comment]
Duplicate, see #6231 and #7622.

**Comment by jonasschnelli** [comment]
It is good practice to always first check for possible duplicates.
Closing.

**Comment by Cannon-Ciota** [comment]
jonasschnelli I did not realize this was a duplicate. Thanks for the references to the former commits paveljanik

**Comment by paveljanik** [comment]
@Cannon-Ciota Please read both duplicates. There are enough arguments against this change at this time already. if you have new argument, please bring it.

**Pull request closed without merging**
