### PR TITLE
ci: Print iwyu patch in git diff format

### PR DESCRIPTION
**Pull request by maflcko**
Seems more dev friendly to also have a patch to copy-paste

### CODE REVIEW

**Review by stickies-v — COMMENTED** [review]
Concept ACK

**Comment by hebasto** [comment]
Concept ACK. Thank you for picking it up!

https://github.com/bitcoin/bitcoin/pull/26763#issuecomment-1405222378:

>> It is possible to leverage the fix_includes.py tool 
>
>Could probably make sense to add this to the CI, to allow easy copy-pasting from Cirrus or from a local run.

**Comment by hebasto** [comment]
> a patch to copy-paste

To be pedantic, replacement quotes `"..."` with angle brackets `<...>` is still required, unfortunately.

**Review by hebasto — APPROVED** [review]
ACK fa6986a66b451f532a1aa2bd72c956fcd8c0d042, tested on Ubuntu 22.04 locally.

**Comment by MarcoFalke** [comment]
Example output: https://cirrus-ci.com/task/5039323280572416?logs=ci#L5652

**Review by fanquake — APPROVED** [review]
ACK fa6986a66b451f532a1aa2bd72c956fcd8c0d042 - did not test but example CI output looks ok.

**Review by stickies-v — APPROVED** [review]
utACK fa6986a66b451f532a1aa2bd72c956fcd8c0d042

**Pull request merged**
