### PR TITLE
[Docs] Updated examples in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Willtech**
Updated examples in `CONTRIBUTING.md` to match currenty accepted convention e.g. [DOCS] {Verbose (50 char max) subject line}

Signed-off-by: Damian Williamson <willtech@live.com.au>

### CODE REVIEW

**Review by randolf — APPROVED** [review]

**Comment by Willtech** [comment]
Per this [event](https://github.com/bitcoin/bitcoin/pull/12384#event-1466043602).

**Comment by promag** [comment]
Actually on PR titles I prefer github labels instead of prefixes, because a PR can affect multitple areas.

**Comment by laanwj** [comment]
I still prefer `prefix:` to `[prefix]`. This is what linux, SDL, and many other projects use, I haven't ever seen the `[xxx]` convention for commits and I'm not sure why we need our own unique one.
So NACK on changing this.

> Actually on PR titles I prefer github labels instead of prefixes, because a PR can affect multitple areas.

Contributors can't set these themselves. Labeling is up to the repo owners (possibly based on those hints). Also labels are per-PR and not per-commit.

**Comment by laanwj** [comment]
> Per this event.

Not sure why @fanquake was changing that, but I disagree obviously :)

**Comment by promag** [comment]
I think prefixes are enough in commits (not against at all) and then someone with permissions (@fanquake for instance) set the correct labels on PR.

As for the prefix format, we should just use one.

**Comment by randolf** [comment]
@promag As long as it's easy to use and communicates clearly, I think it's better to have only one convention for this (whatever the consensus turns out to be).

**Pull request closed without merging**
