### PR TITLE
contrib: Update clang-format-diff

### PR DESCRIPTION
**Pull request by sedited**
This was taken from https://github.com/llvm/llvm-project/blob/900bb318b5b8c485e57cf810253a656b0fb683bc/clang/tools/clang-format/clang-format-diff.py and is useful for systems where clang tools are shipped with a version suffix.

### CODE REVIEW

**Comment by TheCharlatan** [comment]
There were a bunch of changes made to this file to make it "Bitcoin Core" style. Re-applying all of them seems a bit burdensome. Would it be ok to just overwrite these?

**Comment by TheCharlatan** [comment]
Updated c7cb63a12e1a90fe46471cca4001a472078b5ccf -> 008e81e025d64c33e1e71b5a2fe63dfdf6b31437 ([ClangFormatDiffBinaryOption_0](https://github.com/TheCharlatan/bitcoin/tree/ClangFormatDiffBinaryOption_0) -> [ClangFormatDiffBinaryOption_1](https://github.com/TheCharlatan/bitcoin/tree/ClangFormatDiffBinaryOption_1), [compare](https://github.com/TheCharlatan/bitcoin/compare/ClangFormatDiffBinaryOption_0..ClangFormatDiffBinaryOption_1))

* Addressed @maflcko's [comment](https://github.com/bitcoin/bitcoin/pull/29251#issuecomment-1893338875), updating to the latest clang-format-diff.py script: https://github.com/llvm/llvm-project/blob/900bb318b5b8c485e57cf810253a656b0fb683bc/clang/tools/clang-format/clang-format-diff.py

**Comment by TheCharlatan** [comment]
Updated 008e81e025d64c33e1e71b5a2fe63dfdf6b31437 -> 52149b7a2c2b48ed4a4c0900c74cda4bb52a1ea5 ([ClangFormatDiffBinaryOption_1](https://github.com/TheCharlatan/bitcoin/tree/ClangFormatDiffBinaryOption_1) -> [ClangFormatDiffBinaryOption_2](https://github.com/TheCharlatan/bitcoin/tree/ClangFormatDiffBinaryOption_2), [compare](https://github.com/TheCharlatan/bitcoin/compare/ClangFormatDiffBinaryOption_1..ClangFormatDiffBinaryOption_2))


* Added a commit fixing the lint errors by removing a python2 check and specifying "utf8" encoding when opening a file.

**Review by maflcko — APPROVED** [review]
lgtm ACK 52149b7a2c2b48ed4a4c0900c74cda4bb52a1ea5  🌱

<details><summary>Show signature</summary>

Signature:

```
untrusted comment: signature from minisign secret key on empty file; verify via: minisign -Vm "${path_to_any_empty_file}" -P RWTRmVTMeKV5noAMqVlsMugDDCyyTSbA3Re5AkUrhvLVln0tSaFWglOw -x "${path_to_this_whole_four_line_signature_blob}"
RUTRmVTMeKV5npGrKx1nqXCw5zeVHdtdYURB/KlyA/LMFgpNCs+SkW9a8N95d+U4AP1RJMi+krxU1A3Yux4bpwZNLvVBKy0wLgM=
trusted comment: lgtm ACK 52149b7a2c2b48ed4a4c0900c74cda4bb52a1ea5  🌱
OvfYlA4NC+vgQi+PK7fancIkRgGFUMoF0GnyeDigp2SjZhMD7QeiPlg8jfTtivZi0xWiOM2gSMUV1FNgPS2pCg==
```

</details>

**Pull request merged**
