### PR TITLE
build: remove double LIBBITCOIN_SERVER from bench-Makefile

### PR DESCRIPTION
**Pull request by brakmic**
This PR removes the redundant **LIBBITCOIN_SERVER** linking from bench's Makefile.
This PR is similar to https://github.com/bitcoin/bitcoin/pull/17910

Originally, this PR was part of https://github.com/bitcoin/bitcoin/pull/18377, which later got replaced by a better one https://github.com/bitcoin/bitcoin/pull/18397 written by **hebasto**.

### CODE REVIEW

**Comment by laanwj** [comment]
Concept ACK

**Comment by Empact** [comment]
Code Review ACK https://github.com/bitcoin/bitcoin/pull/18429/commits/1f97b69ba27deb645bf5dd229d0cb97d2baf8f49

**Comment by sipa** [comment]
ACK unless someone sees a reason why this would break in certain untested environments.

**Review by hebasto — APPROVED** [review]
ACK 1f97b69ba27deb645bf5dd229d0cb97d2baf8f49

**Review by theStack — APPROVED** [review]
ACK https://github.com/bitcoin/bitcoin/pull/18429/commits/1f97b69ba27deb645bf5dd229d0cb97d2baf8f49

**Pull request merged**
