### PR TITLE
Use new "macOS" naming where appropriate

### PR DESCRIPTION
**Pull request by MitchellCash**
Not quite a mass replacement as I've left OS X and Mac OS X where describing specific older versions.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
No strong opinion.
The shift from "Mac OSX" to "macOS" was done very recent and not sure if we should already do this in our docs.

**Comment by paveljanik** [comment]
Yes, they will change it soon again... Let's wait.

**Comment by MarcoFalke** [comment]
Closing, as this seems too controversial. Also, I don't like that files are moved for this reason as this breaks all hotlinks referring to the docs on `master`.

**Comment by mitchellcash** [comment]
@MarcoFalke no problem. I would say this change will need to happen at some point though, as the use of 'macOS' will start to become more common when referring to Apple's operating system and the term 'OS X' will fall out of favour and to some people maybe even unrecognisable.

**Comment by laanwj** [comment]
Agreed with closing this. We don't have to mirror every one of Apple's marketing moves immediately.

**Pull request closed without merging**
