### PR TITLE
build: Drop the leading 0 from the version number

### PR DESCRIPTION
**Pull request by achow101**
Removes the leading 0 from the version number. The minor version, which we had been using as the major version, is now the major version. The revision, which we had been using as the minor version, is now the minor version. The revision number is dropped. The build number is promoted to being part of the version number. This also avoids issues where it was accidentally not included in the version number.

The CLIENT_VERSION remains the same format as previous as previously, as the Major version was 0 so it never actually got included in it.

The user agent string formatter is updated to follow this new versioning.

***

Honestly I'm just tired of all of the people asking for "1.0" that maybe this'll shut them up. Skip the whole 1.0 thing and go straight to version 22.0!

Also, this means that the terminology we commonly use lines up with how the variables are named. So major versions are actually bumping the major version number, etc.

### CODE REVIEW

**Comment by laanwj** [comment]
Concept ACK

**Comment by practicalswift** [comment]
Concept ACK: a.) number go up is good, and b.) big number going up is obviously better than small number going up! :)

**Comment by hebasto** [comment]
Concept ACK for 0.22.0 -> 22.0

**Comment by Emzy** [comment]
Concept ACK for 0.22.0 -> 22.0

**Comment by michaelfolkson** [comment]
Concept ACK

Redundancy is generally worth considering but this 0.x redundancy seems unnecessary for all possible future scenarios. I'm assuming we don't need to look as far ahead as v99, v100... :)

**Comment by luke-jr** [comment]
Concept NACK, we should stick to a standard versioning system. Either semver (0.features.bugfixes or features.0.bugfixes) or calendar versioning (yy.mm.bugfixes). Whatever we do, CLIENT_VERSION and the UA should reflect it properly. If we go with calendar versioning, replacing 0.21 with 20.11 would make a smoother migration than a 21.N following 0.21.

**Comment by fjahr** [comment]
Following the discussion in the meeting today I am somewhat indifferent towards making a change. I guess I just have not been asked about a 1.0 enough ;) But if we do change anything I strongly prefer this to all the other approaches that were discussed because it's a simple change and simple to explain to outsiders.

**Comment by JeremyRubin** [comment]
I'd prefer if we track the calendar, e.g. 20.11 for a november 2020 release as luke suggests.

But if it's too late to make that happen I am happy to just drop the 0.

**Comment by MarcoFalke** [comment]
Concept ACK

Assigned 22.0 milestone

**Comment by jnewbery** [comment]
Concept ACK

This was discussed in yesterday's meeting: http://www.erisian.com.au/meetbot/bitcoin-core-dev/2020/bitcoin-core-dev.2020-10-22-18.59.log.html#l-122

Current status (please correct me if I'm wrong and I'll update):

Concept ACKs (10): @achow101, @laanwj, @practicalswift, @hebasto, @emzy, @michaelfolkson, @JeremyRubin, @MarcoFalke, @jnewbery, @sipa
Indifferent (2): @fjahr, @jonatack
Concept NACK (1): @luke-jr

**Comment by kristapsk** [comment]
I tend to agree with @luke-jr here.

**Comment by promag** [comment]
Concept ACK. No strong opinion if it should be this release.

It makes sense to me because versions like 0.19.0.1 wouldn't exist.

**Comment by practicalswift** [comment]
@kristapsk 

> I tend to agree with @luke-jr here.

Do you mean in the NACK sense ("don't drop the leading zero"), or in the use calendar version sense ("20.11" would be November 2020)? :)

**Comment by luke-jr** [comment]
>It makes sense to me because versions like 0.19.0.1 wouldn't exist.

0.19.0.1 is fundamentally different from typical bugfix releases, which are normally using the 3rd int.

**Comment by promag** [comment]
@luke-jr fundamentally different? At the time, if it was 19.0.0, we would just tag 19.0.1, or am I wrong?

**Comment by luke-jr** [comment]
@promag Anything is possible with such hypotheticals. If we had 19.0.0, we should never have 19.1.0 because we don't do minor feature releases...

**Comment by luke-jr** [comment]
(Hmm, unless we decide softforks count as minor features?)

**Comment by theStack** [comment]
Is there any strong fundamental long-term drawback on the calendar versioning, i.e. yy.mm.bugfixes (as suggested by JeremyRubin, luke-jr), other than "dropping the zero is simpler"? If not, I'd prefer the calendar versioning as well, it's just nice that you can immediately deduce when a client/node has been last updated by looking at the version, w/o having to look up the version history.

**Comment by luke-jr** [comment]
@theStack Calendar versions don't do that... 2020.11.5 may very well have been released in 2022 and up to date.

**Comment by theStack** [comment]
> @theStack Calendar versions don't do that... 2020.11.5 may very well have been released in 2022 and up to date.

True, that doesn't work with bugfix releases (obviously), but at least it gives a lower bound in the sense of "not older than". I'd still not consider a node "up to date" if it has the latest bugfixes but is based on a years old feature set...

**Comment by achow101** [comment]
> Is there any strong fundamental long-term drawback on the calendar versioning, i.e. yy.mm.bugfixes (as suggested by JeremyRubin, luke-jr), other than "dropping the zero is simpler"? If not, I'd prefer the calendar versioning as well, it's just nice that you can immediately deduce when a client/node has been last updated by looking at the version, w/o having to look up the version history.

I think the main drawback is user confusion. Changing the version number to a new scheme will cause confusion in the short term, but in the long term, when referring to older releases, there may also be confusion there. I think that with this change, there will be less confusion.

In terms of code changes, both switching to calendar versioning and this change are probably the same amount of changes in roughly the same places. It's just that conceptually it's easier to understand "drop the unused zero" than it is to understand switching to something entirely new.

**Comment by kristapsk** [comment]
> @kristapsk
> 
> > I tend to agree with @luke-jr here.
> 
> Do you mean in the NACK sense ("don't drop the leading zero"), or in the use calendar version sense ("20.11" would be November 2020)? :)

NACK. I don't see a problem with leading zero.

**Comment by sipa** [comment]
Concept ACK.

I see this more as making the versioning scheme reflect reality than anything else. We already call our 0.X releases "major" and 0.X.Y releases "minor", so the 0 doesn't seem to convey any information whatsoever.

I'm not opposed to a date-based YY.MM.minor scheme, though my personal preference is just dropping the zero.

**Comment by fanquake** [comment]
Concept ACK

> I'm not opposed to a date-based YY.MM.minor scheme, though my personal preference is just dropping the zero.

FWIW I am opposed to a date-based scheme. Let's just drop the 0 and get this over with.

**Comment by ajtowns** [comment]
Concept ACK. I'd also mildly prefer year based, but just dropping the zero is certainly simplest. Don't see a practical benefit to putting consensus changes (particularly versus standardness changes) into the version.

**Comment by jnewbery** [comment]
Code review ACK 8f7b930475

**Comment by MarcoFalke** [comment]
review ACK 8f7b93047581c67f2133cdb8c7845471de66c30f 🎻

<details><summary>Show signature and timestamp</summary>

Signature:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

review ACK 8f7b93047581c67f2133cdb8c7845471de66c30f 🎻
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEE+rVPoUahrI9sLGYTzit1aX5ppUgFAlwqrYAACgkQzit1aX5p
pUhEvQv/XEWpw+MGd8t2Z0NBKwh4VaA481Jue+XJxqO3xrrcMdBiVAhMRhE5UFUR
GlkvkYOGhCUswat5u0aSOWNF9NxT8MygTeEnKYkeXw1lgXamStT27xqfawuJe3Lt
QI0+kp1EV2J7A3Owf+Q0QHFELIeNY6QhhrPID7EzUx2Y1NAZTiSsoWQIgatqqaaz
/CqL2dRNQu170IR+z61spS21AyJ+GO/n4WpuNZPyqChuAKICmZcVQF+g0dIq5XU0
DZoyoGeLzvlkSywGQuU8a5bEeU5tyY6Y6D6Q5YvfY45OYFy+IobQ3QBg090l9RzP
i/mGR8SU27fOg1kwRjBeAEpaSE0lEaqp5vEJqgL71t/C+/dLhTucucE8rMk+zwEj
zTZBPidZotEhXFRuU0x49QkFqSxCUNQKXcaidJ8qHCycfpZkeFC471ES5PEVSqgd
cRUJ5+jgwqBdCHi0pfzEZ1GcndEPOC8Uyt1kzYSdelEojHem2Gj7UdXfD1Iq857c
PVFYN2wb
=TI+I
-----END PGP SIGNATURE-----
```

python: error while loading shared libraries: libpython3.8.so.1.0: cannot open shared object file: No such file or directory

</details>

**Comment by MarcoFalke** [comment]
(also tested that `CLIENT_VERSION` is unchanged)

**Comment by kallewoof** [comment]
Fixes the closed-since-April #9653. Not sure what changed, but I'm happy about the decision obviously.

**Comment by MarcoFalke** [comment]
I wouldn't say anything changed. When it comes to user experience, p2p features, bugfixes, hardening, testing improvements, and literally everything else, the leading 0 in the version is an insignificant stylistic choice. We have enough "real" issues so that tracking issues for stylistic questions are probably eating away resources from more important topics ( https://github.com/bitcoin/bitcoin/issues/9653#issuecomment-619648106 )

**Comment by whitslack** [comment]
I'm surprised nobody mentioned the obvious implication here: **Bitcoin Core is now officially out of beta!** 🚀

**Comment by sipa** [comment]
It hasn't had a "beta" label since 2014 (see #4221), and even then it was already hardly applicable.

**Comment by whitslack** [comment]
From #4221:

> This is not to say that the system is mature now, suddenly.

So are we **now** saying that the system is mature? 😄  Typically software projects use version numbers less than 1.0 to denote that their software is not yet production-ready. Advancing the version number to something greater than 1.0 sends the signal that the software is now ready for prime time.

**Comment by sipa** [comment]
And that's exactly what we wanted to avoid, by not going to 1.0, and instead just dropping the zero. We have for years been calling the X in 0.X.Y the major release number, so the 0 was just redundant. I don't know what mature means, but Bitcoin Core has had a release process with test procedures, multiple release candidates, goals of compatibility, ... for a better part of a decade now.

There is no dramatic change here, no big milestone, and no need for celebrations or whatever. It's just dropping a zero that was redundant.

**Comment by davidlj95** [comment]
Guess we'll need to update https://bitcoincore.org/en/lifecycle/ now that `22.0` is in place

**Pull request merged**
