### PR TITLE
Improve commit-check-script.sh

### PR DESCRIPTION
**Pull request by sipa**
This makes an improvement to commit-check-script.sh (which was introduced in #10189):
* Fail when a VERIFY SCRIPT is present in the commit body, but no `scripted-diff` exists in its title. This would have caught a bug in #10321 (which had `script-diff` instead of `scripted-diff`) by reducing the reviewer burden from noticing a correct `scripted-diff` to that or a correct VERIFY SCRIPT (using fairly fuzzy rules).

### CODE REVIEW

**Comment by jtimon** [comment]
Concept ACK!

**Comment by theuni** [comment]
utACK 5432fc3d59ce013d6c27f440ad86fc1f16d6e384. I don't believe the second commit is necessary, though. The diff is already shown regardless of success, this should make it print twice.

**Comment by sipa** [comment]
@theuni Removed the last commit. I somehow assumed that what it was printing out was the whole commit, not just the unscripted diff...

**Comment by jtimon** [comment]
Perhaps it would be interesting to rebase #10502 just to check this (and #10502 ) slightly more (although 1238f13 has 2 utACKs )

**Pull request merged**
