### PR TITLE
DEPENDENT: Globals: Avoid calling Params()

### PR DESCRIPTION
**Pull request by jtimon**
Passing CChainParams explicitly as parameter when possible facilitates testing and refactoring.

Dependencies:
- [X] Chainparams: Refactor: Decouple IsSuperMajority from Params() #5968
- [X] Chainparams: Remove redundant getter CChainParams::SubsidyHalvingInterval() #5996
- [X] Chainparams: Refactor: Remove redundant HashGenesisBlock() getter #5997
- [X] Chainparams: Refactor: Remove redundant AllowMinDifficultyBlocks() getter #5998
- [X] Cleanup: Delete CChainParams getters to attributes from Consensus::Params #5999
- [X] Chainparams: Explicit CMessageHeader::MessageStartChars to functions in main: #6173
- [X] Chainparams: Explicit Consensus::Params arg for almost all remaining functions #6163
- [X] Globals: Make AcceptBlockHeader static (Fix #6163) (AcceptBlockHeader) #6982
- [X] Globals: Don't call Params() from miner.cpp #6986 [global-chainparams-miner]
- [ ] Blocksize: Turn MAX_BLOCK_SIZE and MAX_BLOCK_SIGOPS into functions #6625 
- ~~[ ] Chainparams: Explicit Consensus::Params arg in consensus functions #6024~~
- [ ] Consensus: Adapt declarations of most obviously consensus functions [closed for now] #6591 [consensus-params-0.12.99]
- [ ] Globals: Explicit CChainParams in main.o (not touching the interface with net.o)
- [ ] Globals: Explicit CChainParams in net.o (voluntaries required, ideally someone heavily touching net.o for any other reason)
- [ ] Globals: Remove SelectParams()

EDIT Initial description:

After the struct Consensus::Params was created in #5812, there are some redundant getters in CChainParams. This depends on all the PRs that help remove them and continues passing CChainParams and Consensus::Params more explicitly, mainly in main.o, miner.o and init.cpp.
The rpc's, net.o, rest.o and base58.o are left with direct Params() calls. In the tests, Params(CBaseChainParams::MAIN) is preferred.

### CODE REVIEW

**Comment by jtimon** [comment]
Note that AcceptToMemoryPool is ignored because the calls to Params() there will be replaced with policy initialization in init.cpp.

**Comment by jtimon** [comment]
Closing for now, although I will keep updating the dependencies.

**Comment by jtimon** [comment]
Rebased and reopened. #6024 replaced with #6591.
voluntaries required for the step "Chainparams: Explicit CChainParams in net.o" which is not coded here.
Hopefully someone heavily touching net.o for any other reason (please tell anyone you know doing that about this PR) doesn't mind to take that part.
The final step "Chainparams: Remove SelectParams()" is not coded either, but I'm more than happy to do that myself once it's possible.

**Comment by dcousens** [comment]
Comparison URL to review this PR independently of its dependent: https://github.com/jtimon/bitcoin/compare/consensus-params-0.12.99...jtimon:chainparams_cleanup

**Comment by jtimon** [comment]
Rebased on top of #6591

**Comment by jtimon** [comment]
Rebased after #6163 and #6982 have been merged, opened #6986.

**Comment by jtimon** [comment]
Replaced by #7053. Since I think it was extremely
useful to group many related PRs under one big "DEPENDENT" one and
not coordinate how many of them are opened at the same time at some
point after 0.12 is forked I will open and analogous PR to continue
this one. But even if I believe that ```Params()``` is a great example of an
apparently-hard-to-remove global, the next PR will be more generic: there's more globals to pass
down explicitly not just ```Params()``` (mempool, mapBlockIndex,
chainActive, pindexBestHeader...). So ideally we would make this work
per-function rather than per-global. That's also more parallelizable
in terms of people. Explicitly passing all its variables to a
function is in principle a simple task, but I think it would be a
good opportunity for new developers to get familiarized with the
development process (rebases, nits, utACKs, re-utACKs, etc) while the
change they're doing is (while not a priority) something generally
desired in the long term, so they can see their PR eventually merged.
In any case, the main point of doing it with globals in general is
touching function declarations less total times to make the process
less disruptive for other unrelated PRs.

In addition, this was never complete but as new functions are created
in main it becomes more incomplete at time passes. Without going
function by function, one that I thought only needed
Consensus::Params, may need now the full CChainParams while I miss
the change in blind rebase. It is not an unsolvable problem, but it
would make the refactor more disruptive than needed.

I will post here to link to that new DEPENDENT PR. In the meantime,
if you were interested in this PR, you can review #7053, which is this the last part of this PR
that will be opened independently (apart from #6625 which is more part
of #6382).

**Pull request closed without merging**
