### PR TITLE
refactor, qt: Nuke some circular dependencies

### PR DESCRIPTION
**Pull request by hebasto**
This PR gets rid of the following circular dependencies:
- `qt/guiutil` -> `qt/walletmodel` -> `qt/optionsmodel` -> `qt/guiutil`
- `qt/walletmodel` -> `qt/walletmodeltransaction` -> `qt/walletmodel`
- `qt/paymentserver` -> `qt/walletmodel` -> `qt/paymentserver`

### CODE REVIEW

**Comment by practicalswift** [comment]
Concept ACK

Wow, three nuked circular dependencies in one go! Feels very good to see this suppression list shrink :)

**Comment by instagibbs** [comment]
literally did a subset of this for https://github.com/bitcoin/bitcoin/pull/17492

concept ACK

**Comment by hebasto** [comment]
@instagibbs 
> literally did a subset of this for #17492

Oh, I didn't noticed 450a2f7913bfbcfbc9c9dcc03c468043fe86fd76 before...

**Comment by instagibbs** [comment]
I was later pretty sure, just noting this would help my PR get smaller :)

**Comment by hebasto** [comment]
@instagibbs has been added as a co-author.

**Comment by Sjors** [comment]
ACK 5f50599ae7077ae9b9b56edb8892387b6ddc460a

**Comment by instagibbs** [comment]
code review ACK 5f50599ae7077ae9b9b56edb8892387b6ddc460a

**Comment by practicalswift** [comment]
ACK 567cb44eb95785c8df93a3844207d17f4c390372 -- diff looks correct

**Comment by hebasto** [comment]
@practicalswift 
> ACK [567cb44](https://github.com/bitcoin/bitcoin/commit/567cb44eb95785c8df93a3844207d17f4c390372) -- diff looks correct

You've ACKed non-top commit ;)

**Review by promag — APPROVED** [review]
ACK 5f50599ae7077ae9b9b56edb8892387b6ddc460a.

**Comment by practicalswift** [comment]
@hebasto Oh, thanks!

ACK 5f50599ae7077ae9b9b56edb8892387b6ddc460a -- diff looks correct

**Pull request merged**
