### PR TITLE
Update luke-jr's PGP key

### PR DESCRIPTION
**Pull request by luke-jr**
Same key, extended expiration date

### CODE REVIEW

**Comment by laanwj** [comment]
Can't find the discussion quickly but I remember we decided not to do this, to only update keys when they actually change, not for expiration dates. This is why the instructions for getting the gpg keys in [contrib/gitian-keys/README.md](https://github.com/bitcoin/bitcoin/blob/master/contrib/gitian-keys/README.md) include a `gpg --refresh-keys` step.

**Comment by luke-jr** [comment]
Hmm, I thought the discussion was about coordinating it so all of the keys were updated once a year together, but nothing ever materialised further...

**Comment by fanquake** [comment]
The discussion was in #8547/#8603.

**Comment by MarcoFalke** [comment]
I assume it comes with less review and maintenance overhead if there was a script that does this for all keys in one go.

**Pull request closed without merging**
