### PR TITLE
Update to my new key

### PR DESCRIPTION
**Pull request by sipa**

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
ACK

**Comment by gmaxwell** [comment]
ACK d3207abf6c2cad9ad09c71609be01e4bf6e8c827

**Comment by PRabahy** [comment]
Can you sign this key with your old key or something similar to prove its yours? I tried retrieving the key from the keysevers and I looked to see if the git commit was PGP signed. (Sorry if my neck beard is showing through)

**Comment by sipa** [comment]
@PRabahy GnuPG refuses to sign with a revoked key. I'll try.

**Comment by sipa** [comment]
Done.

**Comment by PRabahy** [comment]
ACK 4252cd09fd729b0d8a9d53c0308f54b3a798c372

**Comment by fanquake** [comment]
ACK

**Pull request merged**
