### PR TITLE
ci: use clang-16 in tidy task

### PR DESCRIPTION
**Pull request by fanquake**
Follow up to https://github.com/bitcoin/bitcoin/pull/27311#issuecomment-1481020371, as IWYU now has a [clang_16 branch](https://github.com/include-what-you-use/include-what-you-use/tree/clang_16).

This also removes some workarounds for (now fixed) clang-tidy issues, and simplifies the IWYU install steps.

### CODE REVIEW

**Comment by hebasto** [comment]
Concept ACK.

**Review by hebasto — COMMENTED** [review]
> ```shell
> /usr/include/wchar.h:35:10: fatal error: 'stddef.h' file not found
> #include <stddef.h>
>          ^~~~~~~~~~
> ```

This error can be fixed with the following diff:
```diff
--- a/ci/test/00_setup_env_native_tidy.sh
+++ b/ci/test/00_setup_env_native_tidy.sh
@@ -15,5 +15,5 @@ export RUN_FUNCTIONAL_TESTS=false
 export RUN_FUZZ_TESTS=false
 export RUN_TIDY=true
 export GOAL="install"
-export BITCOIN_CONFIG="CC=clang-16 CXX=clang++-16 --with-incompatible-bdb --disable-hardening CFLAGS='-O0 -g0' CXXFLAGS='-O0 -g0'"
+export BITCOIN_CONFIG="CC=clang-16 CXX=clang++-16 --with-incompatible-bdb --disable-hardening CFLAGS='-O0 -g0' CXXFLAGS='-O0 -g0 -I/usr/lib/llvm-16/lib/clang/16/include'"
 export CCACHE_SIZE=200M
```

See: https://cirrus-ci.com/task/5852229609979904

Some related discussion see in https://github.com/include-what-you-use/include-what-you-use/issues/679.

---

> Note that even though the CI here is "green", [the tidy task](https://cirrus-ci.com/task/6643322689683456?logs=ci#L5204) has failed

https://github.com/bitcoin/bitcoin/pull/26763 is somewhat related.

**Comment by fanquake** [comment]
>  -I/usr/lib/llvm-16/lib/clang/16/include

Included this. I think we could merge this as-is, but should also figure out why it's needed. It feels like there is another issue here.

> Also https://github.com/bitcoin/bitcoin/pull/25466#discussion_r930891939

Removed the related suppressions.

**Review by hebasto — APPROVED** [review]
ACK a56c96507a9e943bbcd7e126bc827de9495f0ebd

**Pull request merged**
