### PR TITLE
Banlist updates

### PR DESCRIPTION
**Pull request by luke-jr**
Recovering #6371 which was basically ready to merge when @Diapolo decided to leave

### CODE REVIEW

**Comment by dcousens** [comment]
@luke-jr why 5bc47b7?  Rebase?

**Comment by luke-jr** [comment]
@dcousens [Rebasing is bad.](http://www.mail-archive.com/dri-devel@lists.sourceforge.net/msg39091.html)

**Comment by MarcoFalke** [comment]
This looks like consistency cleanup/refactor. Any new feature to test here?

**Comment by jonasschnelli** [comment]
Thanks.
utACK.

**Comment by dcousens** [comment]
utACK 5bc4fb7

**Comment by MarcoFalke** [comment]
utACK 5bc4fb7

**Pull request merged**
