### PR TITLE
[Moveonly] Create ui_interface.cpp

### PR DESCRIPTION
**Pull request by maflcko**
Should be trivial to review, since it's move only besides a missing `return true;`.

### CODE REVIEW

**Comment by paveljanik** [comment]
Concept ACK.

I think that the `return true` is to have the same prototypes of both Warning and Error functions. Is it worth it?

**Comment by MarcoFalke** [comment]
> Is it worth it?

No, InitError should fail and trigger a shutdown. InitWarning, however, should not trigger a shutdown and continue execution. Thus the return value is not only unused but also misleading.

**Comment by paveljanik** [comment]
@MarcoFalke Of course I agree with you :-)

**Comment by jonasschnelli** [comment]
Concept ACK.
Not sure if the function names should contain the `Init*` part (like `InitError()` and `InitWarning()`). From the `ui_interface` perspective, the error/warning is unrelated to the init process.

**Comment by MarcoFalke** [comment]
> the error/warning is unrelated to the init process.

This is a valid point, but I think there is no actual use case for a *modal* pop up other than in the init process. I'd rather keep the old name, and change it when there is a valid use case for a blocking dialog.

**Comment by laanwj** [comment]
Concept ACK

**Comment by MarcoFalke** [comment]
Anything holding this back?

**Comment by laanwj** [comment]
Nit: the UI interface should be in bitcoin_server.a, not bitcoin_util.a. It should not be used by the other tools, just bitcoind and bitcoin-qt.

**Comment by MarcoFalke** [comment]
Addressed nit

**Pull request merged**
