### PR TITLE
test: Set regtest.BIP66Height = 102 to speed up tests

### PR DESCRIPTION
**Pull request by maflcko**
No need to waste time by forcing creation of more than 1000 blocks to get the benefits of being able to test BIP 66. Also, reducing the height makes it more likely that (third-party) tests are conforming to BIP 66, which is enforced on mainnet for all new blocks.

### CODE REVIEW

**Comment by theStack** [comment]
Strong Concept ACK

**Review by Zero-1729 — COMMENTED** [review]
Concept ACK fafe896a0b870d85250927bd5374caf73d379468

**Comment by GeneFerneau** [comment]
Concept + code review ACK [fafe896](https://github.com/bitcoin/bitcoin/pull/22632/commits/fafe896a0b870d85250927bd5374caf73d379468)

**Comment by brunoerg** [comment]
Concept ACK

**Review by kristapsk — APPROVED** [review]
ACK fafe896a0b870d85250927bd5374caf73d379468. Full functional test suite showed few second speed incrase on my laptop (although I didn't do proper benchmarking with multiple runs, just single `time ./test/functional/test_runner.py` on current master vs this PR).

**Comment by MarcoFalke** [comment]
This should only affect the speed of `test/functional/feature_dersig.py` and no other test

**Review by theStack — APPROVED** [review]
Tested ACK fafe896a0b870d85250927bd5374caf73d379468

master branch:
```
$ time ./test/functional/feature_dersig.py
...
    0m15.29s real     0m11.55s user    0m05.72s system
```

PR branch:
```
$ time ./test/functional/feature_dersig.py
...
    0m03.97s real     0m01.42s user    0m01.34s system
```

🎉

**Review by Zero-1729 — APPROVED** [review]
tACK fafe896

Tested on macOS v11.4

**Master**

```sh
$ time ./test/functional/feature_dersig.py
...
./test/functional/feature_dersig.py  1.65s user 0.42s system
```

**After Patch**

```sh
$ time ./test/functional/feature_dersig.py
...
./test/functional/feature_dersig.py  0.37s user 0.15s system
```

**Comment by 0xB10C** [comment]
crACK fafe896a0b870d85250927bd5374caf73d379468

**Review by hg333 — APPROVED** [review]
tACK https://github.com/bitcoin/bitcoin/commit/fafe896a0b870d85250927bd5374caf73d379468

Tested on Ubuntu 20.04

**Master branch:**
```
$ time ./test/functional/feature_dersig.py 
...
real	0m23.470s
user	0m6.761s
sys	0m1.232s
```
**PR branch:**
```
$ time ./test/functional/feature_dersig.py 
...
real	0m3.051s
user	0m0.646s
sys	0m0.131s
```

**Comment by laanwj** [comment]
ACK fafe896a0b870d85250927bd5374caf73d379468

**Pull request merged**
