### PR TITLE
scripted-diff: Bump copyright headers

### PR DESCRIPTION
**Pull request by maflcko**
Needs to be done because no one has removed the years yet

### CODE REVIEW

**Comment by practicalswift** [comment]
ACK fa0074e2d82928016a43ca408717154a1c70a4db

**Comment by MarcoFalke** [comment]
Link to lint: https://cirrus-ci.com/task/5664588576325632?command=lint#L860

**Comment by michaelfolkson** [comment]
You want years entirely removed from all currently used copyright headers so they don't need to updated next year @MarcoFalke? A good first issue?

**Comment by prusnak** [comment]
Shouldn't the year be `2021` in this PR?

**Comment by kallewoof** [comment]
Yes, should be 2021...

**Comment by sipa** [comment]
No, none of these files have been touched in the year 2021 yet.

**Comment by kallewoof** [comment]
Some of them haven't been touched in 2020 either. I assumed the bump was for all files, regardless of whether we touched them or not.

**Comment by MarcoFalke** [comment]
The script will update the number in each file to be the year in the author date.

I am checking that the script works correctly, so if any update happened without a corresponding edit in 2020, please let me know.

**Comment by kallewoof** [comment]
src/crypto/aes.h
```diff
commit aaaaad6ac95b402fe18d019d67897ced6b316ee0
Author: MarcoFalke <falke.marco@gmail.com>
Date:   Mon Dec 30 22:39:22 2019 +1300

    scripted-diff: Bump copyright of files changed in 2019

    -BEGIN VERIFY SCRIPT-
    ./contrib/devtools/copyright_header.py update ./
    -END VERIFY SCRIPT-

commit f6ee177f7d8d4a8220e6ba4f0d5f68830fe1c817
Author: practicalswift <practicalswift@users.noreply.github.com>
Date:   Mon Mar 25 14:46:30 2019 +0100

    Remove unused AES-128 code

```

**Pull request merged**
