### PR TITLE
doc: Moved -debuglogfile option to Debugging options

### PR DESCRIPTION
**Pull request by keystrike**
Moved -debuglogfile from the main options section to Debugging/Testing options

### CODE REVIEW

**Comment by hebasto** [comment]
> Moved -debuglogfile from the main options section to Debugging/Testing options

Rationale?

**Comment by keystrike** [comment]
All other debug options are in Debugging/Testing. It could make sense for -debug to be in the main options section, but not -debuglogfile.

**Comment by hebasto** [comment]
> All other debug options are in Debugging/Testing. It could make sense for -debug to be in the main options section, but not -debuglogfile.

Debugging/Testing options are for developers mostly. They are not designed to use in production/normal mode.
OTOH, a log file is used in normal node usage. Therefore, I think the current category is correct.

**Comment by keystrike** [comment]
> > All other debug options are in Debugging/Testing. It could make sense for -debug to be in the main options section, but not -debuglogfile.
> 
> Debugging/Testing options are for developers mostly. They are not designed to use in production/normal mode.
> OTOH, a log file is used in normal node usage. Therefore, I think the current category is correct.

Ok, that is reasonable.

**Pull request closed without merging**
