### PR TITLE
qt: Add better icon for Open URI

### PR DESCRIPTION
**Pull request by cvengler**
This PR adds a better icon for the Open URI button. This icon is more common for a URI.
<br>
In action it will look like this:

### CODE REVIEW

**Comment by MarcoFalke** [comment]
I'd rather stick with the https://www.s-ings.com/typicons we currently use.

**Comment by emilengler** [comment]
@MarcoFalke Good suggestion, I update it and the screenshot as well

**Comment by hebasto** [comment]
@emilengler 
> This icon is more common for a URI.

Some examples?

**Comment by emilengler** [comment]
Sure, take a look at qBittorrent for example. They have something similar for magnet URIs

**Comment by hebasto** [comment]
@emilengler 
Is the suggested icon [optimized](https://github.com/bitcoin/bitcoin/tree/master/contrib/devtools#optimize-pngspy)?

**Comment by emilengler** [comment]
@hebasto No not yet, will update it

**Comment by emilengler** [comment]
@hebasto Done

**Comment by laanwj** [comment]
New icon looks okay to me.

**Comment by jonasschnelli** [comment]
Fine by me

**Comment by promag** [comment]
Looks like it should have more padding? I think it should have the same line width.

Screenshot 2019-08-05 at 11 22 30

**Comment by MarcoFalke** [comment]
Is there a reason we can't use the svg directly?

**Comment by emilengler** [comment]
@promag Yes there is more padding, I had no idea if there was one already. But in action you won't see the difference

**Comment by jonasschnelli** [comment]
Looks in general acceptabel.
But the icon needs more padding to look not larger than the other ones.

Bildschirmfoto-2019-08-12-um-13 30 27

**Comment by emilengler** [comment]
@jonasschnelli Ok, I will append it.

**Comment by emilengler** [comment]
@jonasschnelli Done

**Comment by kristapsk** [comment]
I like this new icon better for "Open URI" context in menu, but dialog window itself actually has "from URI or file" and for generic "open" functionality that open folder icon is definitely more common (Transmission uses it for both file and magnet link menu items actually).

image

**Comment by emilengler** [comment]
Yeah I also had this in mind, the "..." can be replaced by the open icon

**Comment by laanwj** [comment]
Same comment as here: https://github.com/bitcoin/bitcoin/pull/16584#issuecomment-521195090

Instead of a flurry of menu icon changes and associated bikeshedding, maybe remove them completely.

**Comment by emilengler** [comment]
@laanwj See my comment in the issue you referenced to, Bitcoin should be accessible for anyone no matter of his education

**Comment by hebasto** [comment]
> Bitcoin should be accessible for anyone no matter of his education

This way leads to frustration only, IMO.

**Comment by fanquake** [comment]
Going to close this in favour of #16612, which already has a multitude of (Concept) ACKs.

**Pull request closed without merging**
