### PR TITLE
wallet: sqlite: don't include sqlite files from our headers

### PR DESCRIPTION
**Pull request by theuni**
Only `#include` upstream sqlite headers from our cpp files.

Like #28039 but simpler :)

### CODE REVIEW

**Comment by achow101** [comment]
ACK bea9fc2600635020fd28ec7a6613c92a6f349a86

**Review by maflcko — APPROVED** [review]
lgtm. I wonder why iwyu can't transform those two symbols into forward decls. Output on master:

```
The full include-list for wallet/sqlite.h:
...
#include <sqlite3.h>    // for sqlite3_stmt, sqlite3
...

**Review by sedited — APPROVED** [review]
Nice, ACK bea9fc2600635020fd28ec7a6613c92a6f349a86

**Review by kristapsk — APPROVED** [review]
utACK bea9fc2600635020fd28ec7a6613c92a6f349a86

**Review by hebasto — APPROVED** [review]
ACK bea9fc2600635020fd28ec7a6613c92a6f349a86, I have reviewed the code and it looks OK.

**Review by PRADACANDI18 — APPROVED** [review]
Looks good

**Pull request merged**
