### PR TITLE
Disconnect clients with intentionally broken consensus. 

### PR DESCRIPTION
**Pull request by bit-moon**

### CODE REVIEW

**Comment by luke-jr** [comment]
NACK, this is too broad. All current releases of Bitcoin XT are consensus-compatible. Furthermore, matching on UA is potentially problematic. Matching on behaviour has the problem of differentiating between real hardforks and broken nodes.

**Comment by paveljanik** [comment]
NACK

**Comment by laanwj** [comment]
LOL.

**Comment by jgarzik** [comment]
NAK, no troll patches

**Pull request closed without merging**
