### PR TITLE
Changing -txindex requires -reindex, not -reindex-chainstate

### PR DESCRIPTION
**Pull request by TheBlueMatt**
If there's an 0.15.0rc3, this should go in it.

### CODE REVIEW

**Comment by laanwj** [comment]
Agree, though bleh, changes a translation message.

**Comment by jonasschnelli** [comment]
ACK cd0ea487422028bec1f5df62ab4c57909c2bcc90.
I think it's better to have this in english (failed translation) then wrong. But no need to spun a rc3 if this is the only fix.

**Comment by achow101** [comment]
ACK cd0ea487422028bec1f5df62ab4c57909c2bcc90

**Comment by sdaftuar** [comment]
ACK

**Comment by MarcoFalke** [comment]
ACK

**Pull request merged**
