### PR TITLE
RPC doc fix-ups.

### PR DESCRIPTION
**Pull request by fanquake**
Small doc fixes following #9657.

### CODE REVIEW

**Comment by laanwj** [comment]
Thanks for making the documentation up to date. utACK https://github.com/bitcoin/bitcoin/pull/9807/commits/41e7219127d2895d2d223a75672cf312e476bfa5.

**Comment by paveljanik** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/9807/commits/851f6a39f10379bfdb27e18c87b322b942abe914

**Comment by jnewbery** [comment]
Thanks. utACK.

It would also be good to remove `qa/pull-tester/tests_config.py` from .gitignore, but that will cause it to appear as an untracked file in git status for anyone who builds on a previous commit and then git pulls.

**Comment by sdaftuar** [comment]
ACK

**Comment by fanquake** [comment]
@jnewbery, yea, that's why I just left it for now.

**Comment by MarcoFalke** [comment]
Makes sense, this could be done a week or so after the release of 0.14.0, when developers no longer jump back and forth so often between branches.

**Pull request merged**
