### PR TITLE
[0.12 backport] script_tests improvements from master and #7818

### PR DESCRIPTION
**Pull request by sipa**
Assuming #7818 gets merged, here is a backport to 0.12, to unify the framework across branches.

### CODE REVIEW

**Comment by laanwj** [comment]
I was about to ask how this integrates with "[0.12.2] qa Backports #7811" but this is different. In case anyone wonders: that pull backports functional tests, this pull backports unit tests, so there should be no overlap.

**Comment by MarcoFalke** [comment]
Nit: I'd prefer if you used `git cherry-pick -x $HASH` instead, so it is clear that those are backports.

**Comment by laanwj** [comment]
Right - the idea behind those "footers" in the commit message is to be able to instantly see what pull request / master commit(s) a commit came from. The scripting to create the list of pulls in the release notes makes use of this.

**Comment by laanwj** [comment]
Closing as #8001 was merged.

**Pull request closed without merging**
