### PR TITLE
Remove unused bits from the service flags enum

### PR DESCRIPTION
**Pull request by maflcko**
Remove all bits that have no BIP specification nor can be observed on the active network

### CODE REVIEW

**Comment by practicalswift** [comment]
utACK fa0d0ff6e1bee60fde63724ae28a51aac5a94d4a

**Comment by LarryRuane** [comment]
utACK fa0d0ff6e1bee60fde63724ae28a51aac5a94d4a

**Comment by promag** [comment]
ACK fa0d0ff6e1bee60fde63724ae28a51aac5a94d4a.

**Comment by laanwj** [comment]
ACK fa0d0ff6e1bee60fde63724ae28a51aac5a94d4a

**Comment by rebroad** [comment]
I'm still seeing plenty of nodes on the network advertising the THIN service bit, as of 10 minutes ago.

**Pull request merged**
