### PR TITLE
doc: add databases/py-sqlite3 to FreeBSD test suite deps

### PR DESCRIPTION
**Pull request by fanquake**
Adds missing documentation. See also https://cirrus-ci.com/task/5639240319500288.

### CODE REVIEW

**Comment by fanquake** [comment]
cc @murrayn

**Comment by murrayn** [comment]
There seems to be some other issue in that this test should not be getting run if any of its dependencies are not available.

**Comment by MarcoFalke** [comment]
Personally I am fine to just require the dependency

**Comment by fanquake** [comment]
Yea. I don't see the issue here. SQLite is available. Seems FreeBSD just needs another package to expose it to Python.

**Comment by murrayn** [comment]
I would rather not make another special documentation case for FreeBSD before we can rule out a code issue. On Linux, the test is skipped if the dependency is not there.

**Comment by MarcoFalke** [comment]
I think the test is only skipped if sqlite was not compiled into bitcoind? Which (in theory) is different from py-sqlite3 being installed, at least on FreeBSD.

**Comment by fanquake** [comment]
Yep. Adding this to the documentation is no different to having to `pip install pyzmq` or `apt install python3-zmq` to run the zeromq related functional tests.

**Comment by MarcoFalke** [comment]
In theory it would be possible to write a skip function if py-sqlite3 is not there, based on :


https://github.com/bitcoin/bitcoin/blob/edc3d1b296e34838d649dc21b8483a52e214932a/test/functional/test_framework/test_framework.py#L850-L855

**Comment by fanquake** [comment]
The tests have now been fixed in any case, so this is just adding the missing the documentation.

**Comment by fanquake** [comment]
@john-moffett want to review?

**Comment by john-moffett** [comment]
ACK 376e01b382679b49d5c8464c869d14eca23ab4b9

The `sqlite3` module is already included in most other python package distributions since it's part of the standard library, so FreeBSD seems like an outlier in that respect. It's a very small dependency and tests an important piece of wallet functionality, so it [makes sense](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) to specifically include it here.

**Pull request merged**
