### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by GoodDaisy**
fix typo in doc/Doxyfile.in
fix typo in test/functional/wallet_backup.py

### CODE REVIEW

**Comment by GoodDaisy** [comment]
@hebasto thank you very much for your suggestion, and I submit to here.

**Comment by RandyMcMillan** [comment]
ACK a1b1798b1652e93caf66e5e1c8353bcd7951f1c4

**Comment by alfonsoromanz** [comment]
ACK a1b1798b1652e93caf66e5e1c8353bcd7951f1c4

**Review by yahiheb — APPROVED** [review]
ACK [a1b1798](https://github.com/bitcoin/bitcoin/pull/29246/commits/a1b1798b1652e93caf66e5e1c8353bcd7951f1c4)

**Comment by glozow** [comment]
Thank you for your interest in contributing. Please see https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#pull-request-philosophy

**Pull request closed without merging**
