### PR TITLE
build: fix usage of `-Wloop-analysis`

### PR DESCRIPTION
**Pull request by fanquake**
Looks like I introduced this in
5ced92528362d8a9ea3c15a9752f3dc184108060.

### CODE REVIEW

**Comment by hebasto** [comment]
> Looks like I introduced this in [5ced925](https://github.com/bitcoin/bitcoin/commit/5ced92528362d8a9ea3c15a9752f3dc184108060).

... and I overlooked it during reviewing, and no complains from clang as both options are valid.

**Review by hebasto — APPROVED** [review]
ACK 166e0c057c91f7c8666fe8aa43f699956a2b4b8b, tested on Ubuntu 22.04:

- master branch (a62231bca629e945349255a1d331dd5c7a86ddd1):
```
$ ./autogen.sh
$ ./configure CC=clang CXX=clang++  2>&1 | grep loop-analysis
checking whether C++ compiler accepts -Wloop-analysis... yes
  CXXFLAGS        =   -fdebug-prefix-map=$(abs_top_srcdir)=.  -Wstack-protector -fstack-protector-all -fcf-protection=full -fstack-clash-protection  -Wall -Wextra -Wgnu -Wformat -Wformat-security -Wvla -Wshadow-field -Wthread-safety -Wrange-loop-analysis -Wredundant-decls -Wunused-member-function -Wdate-time -Wconditional-uninitialized -Woverloaded-virtual -Wsuggest-override -Wunreachable-code-loop-increment -Wimplicit-fallthrough  -Wno-unused-parameter -Wno-self-assign -Wno-deprecated-copy    -g -O2
```

- this PR:
```
$ ./autogen.sh
$ ./configure CC=clang CXX=clang++  2>&1 | grep loop-analysis
checking whether C++ compiler accepts -Wloop-analysis... yes
  CXXFLAGS        =   -fdebug-prefix-map=$(abs_top_srcdir)=.  -Wstack-protector -fstack-protector-all -fcf-protection=full -fstack-clash-protection  -Wall -Wextra -Wgnu -Wformat -Wformat-security -Wvla -Wshadow-field -Wthread-safety -Wloop-analysis -Wredundant-decls -Wunused-member-function -Wdate-time -Wconditional-uninitialized -Woverloaded-virtual -Wsuggest-override -Wunreachable-code-loop-increment -Wimplicit-fallthrough  -Wno-unused-parameter -Wno-self-assign -Wno-deprecated-copy    -g -O2
```

**Comment by ajtowns** [comment]
Original PR #23473 ; "boring" huh...

**Review by jarolrod — APPROVED** [review]
ACK 166e0c057c91f7c8666fe8aa43f699956a2b4b8b

Tested on macOS with the following commands

master 
```
$ ./configure CC=clang CXX=clang++  2>&1 | grep loop-analysis
checking whether C++ compiler accepts -Wloop-analysis... yes
  CXXFLAGS        =    -Wstack-protector -fstack-protector-all  -Wall -Wextra -Wgnu -Wformat -Wformat-security -Wvla -Wshadow-field -Wthread-safety -Wrange-loop-analysis -Wredundant-decls -Wunused-member-function -Wdate-time -Wconditional-uninitialized -Woverloaded-virtual -Wsuggest-override -Wunreachable-code-loop-increment -Wimplicit-fallthrough  -Wno-unused-parameter -Wno-self-assign -Wno-deprecated-copy    -g -O2
```


pr
```
$ ./configure CC=clang CXX=clang++  2>&1 | grep loop-analysis
checking whether C++ compiler accepts -Wloop-analysis... yes
  CXXFLAGS        =    -Wstack-protector -fstack-protector-all  -Wall -Wextra -Wgnu -Wformat -Wformat-security -Wvla -Wshadow-field -Wthread-safety -Wloop-analysis -Wredundant-decls -Wunused-member-function -Wdate-time -Wconditional-uninitialized -Woverloaded-virtual -Wsuggest-override -Wunreachable-code-loop-increment -Wimplicit-fallthrough  -Wno-unused-parameter -Wno-self-assign -Wno-deprecated-copy    -g -O2
```

**Pull request merged**
