### PR TITLE
doc: Collect release-notes snippets

### PR DESCRIPTION
**Pull request by maflcko**
Also add a note for #20101

### CODE REVIEW

**Comment by gwillen** [comment]
Complementing #20101 -- is it worth making the release notes be more explicit about the impact of the "no default wallet" change on RPC users? I.e., clearly spell out that the automatic prompting is only in the GUI, and that RPC users now MUST call `createwallet`, or `loadwallet`, or supply `-wallet` to `bitcoind`, in order to have a wallet available? (I advocated for putting this information in the error message, but that's somewhat abbreviated; the release notes would be one sensible place for a longer message about it.)

**Comment by MarcoFalke** [comment]
This is already mentioned in the GUI section and Default Wallet section of the release notes. Anything missing there?

**Comment by gwillen** [comment]
Well, the Default Wallet section says: 

"Bitcoin Core will no longer create an unnamed `""` wallet by default when no
wallet is specified on the command line or in the configuration files. For
backwards compatibility, if an unnamed `""` wallet already exists and would
have been loaded previously, then it will still be loaded. Users without an
unnamed `""` wallet and without any other wallets to be loaded on startup will
be prompted to either choose a wallet to load, or to create a new wallet."

So the message here is "GUI users, have no fear, you don't need to worry about this", and it does not mention RPC/CLI users at all. I am suggesting it should say something more explicitly helpful for those users, like: "RPC and CLI users will need to explicitly load a wallet, using either the `-wallet=` flag to `bitcoind`, or the `loadwallet` RPC. (Or create a new wallet using the `createwallet` RPC.)"

But it does say that in the error message now, after #20101, so one way or another they'll figure it out eventually.

**Comment by MarcoFalke** [comment]
I'll leave the notes as is for now. They can be changed easily as needed when they are moved to the wiki next week.

**Review by fanquake — APPROVED** [review]
ACK faa0847dec0f48f8c07c9a4c995bf5f688bb8c1c - no need to bike-shed here as these will all get massaged to death in the wiki anyways.

**Pull request merged**
