### PR TITLE
travis: make distdir before make

### PR DESCRIPTION
**Pull request by maflcko**
Fix my nit on my pull: https://github.com/bitcoin/bitcoin/pull/9390#discussion_r93356812

### CODE REVIEW

**Comment by MarcoFalke** [comment]
I have no idea why this fails, but the second commit fixes a blocker for 0.14.0

**Comment by MarcoFalke** [comment]
Thanks for looking at this. @theuni already has a fix prepared for the error. Let's give him some time to prepare a pull for this.

**Comment by fanquake** [comment]
@MarcoFalke Can you rebase this on #9513 so we can see the build results?

**Comment by fanquake** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/9416/commits/faaf3ca0af683bc6317ff4d1524eb506ab1b2ac8 tests look better here now as well.

**Pull request merged**
