### PR TITLE
build: Use newest `config.{guess,sub}` available

### PR DESCRIPTION
**Pull request by hebasto**
Fixes cross-compiling on old systems. See https://github.com/bitcoin/bitcoin/issues/26420#issuecomment-1295886891.

Guix builds:
```
ab58f8db4fb50c2af08be646e4a57491ff853bf41319fe3e962bb928ace2c1be  guix-build-ea7b8528490d/output/aarch64-linux-gnu/SHA256SUMS.part
c4a42a7dbfb15aa910ce269c3f3158df758eba01dd855cf6529c960d9b8bd76b  guix-build-ea7b8528490d/output/aarch64-linux-gnu/bitcoin-ea7b8528490d-aarch64-linux-gnu-debug.tar.gz
add5f80b0c8ee216c1d8db31e13656c45f11fe5c967324b8fcedd64d0d408938  guix-build-ea7b8528490d/output/aarch64-linux-gnu/bitcoin-ea7b8528490d-aarch64-linux-gnu.tar.gz
ba807ae5b29aca611a35700a968a4f9010528d6cdb6412f98c707aa0e9510e8b  guix-build-ea7b8528490d/output/arm-linux-gnueabihf/SHA256SUMS.part
fe127eff1fc8389ef00ae39d1446640512120d2f247a2ee64c06290116265729  guix-build-ea7b8528490d/output/arm-linux-gnueabihf/bitcoin-ea7b8528490d-arm-linux-gnueabihf-debug.tar.gz
ac75f0aba2e0801fc6b59405bff09884837e0ff8b6fa9fc1225e8325a4ec78a4  guix-build-ea7b8528490d/output/arm-linux-gnueabihf/bitcoin-ea7b8528490d-arm-linux-gnueabihf.tar.gz
dee402db94829bd5ce029ca02d75e008f8a18a44fd88e8ecd00b3ce586f223f4  guix-build-ea7b8528490d/output/arm64-apple-darwin/SHA256SUMS.part
bbf985dbd1ca875fbb0a03c21698d4b6797c27be45e3a31a3229daee0ecbcbf4  guix-build-ea7b8528490d/output/arm64-apple-darwin/bitcoin-ea7b8528490d-arm64-apple-darwin-unsigned.dmg
3cca89e532a2b637185ca316168b0f6fac2fce8795b486d530ee966a844716f1  guix-build-ea7b8528490d/output/arm64-apple-darwin/bitcoin-ea7b8528490d-arm64-apple-darwin-unsigned.tar.gz
487c68e1a71f6254d48f8d322a46c94e671e00b5930fbfe689804cd8e379c8e9  guix-build-ea7b8528490d/output/arm64-apple-darwin/bitcoin-ea7b8528490d-arm64-apple-darwin.tar.gz
db663cf3216871f4c87b687a839cb5cf18b5d9906b74d4c19e8ad422d904aa87  guix-build-ea7b8528490d/output/dist-archive/bitcoin-ea7b8528490d.tar.gz
09121bcd36d72ad26364182c678f2edaaf5b5e635ed43a6964ad7e4be1335075  guix-build-ea7b8528490d/output/powerpc64-linux-gnu/SHA256SUMS.part
e8638959b501c3d70421dcdc6579c5d77c5786abed7ad3d6051c628fd8f17c6b  guix-build-ea7b8528490d/output/powerpc64-linux-gnu/bitcoin-ea7b8528490d-powerpc64-linux-gnu-debug.tar.gz
b1aee39067d5010b4e63dc916232eb1582299d7acb56afacf5c9a5b75dcd8b82  guix-build-ea7b8528490d/output/powerpc64-linux-gnu/bitcoin-ea7b8528490d-powerpc64-linux-gnu.tar.gz
9ed3d0e710847068cb2064e51e3f4c14166ad86f5c297adcf0a4d24cd4e2a723  guix-build-ea7b8528490d/output/powerpc64le-linux-gnu/SHA256SUMS.part
19f99e41f41d9525a412872e61687452ab5ac23c5c964ef34b8c31a9d71adabc  guix-build-ea7b8528490d/output/powerpc64le-linux-gnu/bitcoin-ea7b8528490d-powerpc64le-linux-gnu-debug.tar.gz
bd669150ce6830ffbd8523acf75b6daf894c9449c6ce3073a9ce89156d9268f9  guix-build-ea7b8528490d/output/powerpc64le-linux-gnu/bitcoin-ea7b8528490d-powerpc64le-linux-gnu.tar.gz
5e42cb1fee7b5b046da37f62674a1662a6135f9644f5ea0288876334c3e8d34a  guix-build-ea7b8528490d/output/riscv64-linux-gnu/SHA256SUMS.part
8767a84e04e0cd27318305d31a5a897cdc5f56d8505416dd01753bb35c8980b0  guix-build-ea7b8528490d/output/riscv64-linux-gnu/bitcoin-ea7b8528490d-riscv64-linux-gnu-debug.tar.gz
00f1abcc64a7010f194dab847c04481e10991128b919b513aa9eb2911d03a243  guix-build-ea7b8528490d/output/riscv64-linux-gnu/bitcoin-ea7b8528490d-riscv64-linux-gnu.tar.gz
ae7add2e3ea0663fdd9d2c61c737e4bb4155d42932a0a5ce8cbbbcee627f01f3  guix-build-ea7b8528490d/output/x86_64-apple-darwin/SHA256SUMS.part
ba6b4a2f6a97e382a10ffec605f025d8724ac2dc0a441dbb42be79e915e98738  guix-build-ea7b8528490d/output/x86_64-apple-darwin/bitcoin-ea7b8528490d-x86_64-apple-darwin-unsigned.dmg
67914f29d9e81ee50b340c3ac05b336b98766b59b8cce153493786b04a51f18a  guix-build-ea7b8528490d/output/x86_64-apple-darwin/bitcoin-ea7b8528490d-x86_64-apple-darwin-unsigned.tar.gz
1d813d0e905a324f48beb2ce1da980e372c529b0eadb521662063f283fbc9bf6  guix-build-ea7b8528490d/output/x86_64-apple-darwin/bitcoin-ea7b8528490d-x86_64-apple-darwin.tar.gz
4e3d176ad9059e59e9b21919001ced2710c74229536b27ef65acef514287f7e5  guix-build-ea7b8528490d/output/x86_64-linux-gnu/SHA256SUMS.part
cbe31f4a60aac1a72bcdedccf39c18da21a5a4e257e77c0832ad93ce722923dd  guix-build-ea7b8528490d/output/x86_64-linux-gnu/bitcoin-ea7b8528490d-x86_64-linux-gnu-debug.tar.gz
d5f3cf53adf1d964cded3461b66199c4917715af0d84cac78c97acc92432b059  guix-build-ea7b8528490d/output/x86_64-linux-gnu/bitcoin-ea7b8528490d-x86_64-linux-gnu.tar.gz
9b1877d00fd447222839615cfeb089a8237f1d5d80cd2b819dd66621df8f2375  guix-build-ea7b8528490d/output/x86_64-w64-mingw32/SHA256SUMS.part
2fb88e40dd399a2dedb1a44c5bd1091899b00a6d3b8d99149f622a0069205560  guix-build-ea7b8528490d/output/x86_64-w64-mingw32/bitcoin-ea7b8528490d-win64-debug.zip
074ce203494dc15c916c151426438f09982a270f389cd139d3f28a75aea51af8  guix-build-ea7b8528490d/output/x86_64-w64-mingw32/bitcoin-ea7b8528490d-win64-setup-unsigned.exe
2aa8ff735ce96580fb915757ccce79dc2a19afb043a6c93d3749023ca647666d  guix-build-ea7b8528490d/output/x86_64-w64-mingw32/bitcoin-ea7b8528490d-win64-unsigned.tar.gz
0ac19e1901506c47d5b20297d468dbaa93e8572232671a16d08355988df8e7c3  guix-build-ea7b8528490d/output/x86_64-w64-mingw32/bitcoin-ea7b8528490d-win64.zip
```

### CODE REVIEW

**Comment by hebasto** [comment]
@fanquake 
> Does this work in a Guix build?

The PR description has been updated with Guix build hashes.

**Comment by jarolrod** [comment]
GUIX hashes

x86:
```
c6746ead892d3011b585bb1b8997ad1ca73d9a23c385e79670110b44b1be1534  guix-build-da95f2d55564/output/aarch64-linux-gnu/SHA256SUMS.part
a3b14bc4308f7ffdc34b1d190ec6c3fe3b1b1db7aae728aee855e3fb40dacff9  guix-build-da95f2d55564/output/aarch64-linux-gnu/bitcoin-da95f2d55564-aarch64-linux-gnu-debug.tar.gz
e5aad89817d1c4cd73f354093180755239ed32ff33b1d2aa9be39556da531f5c  guix-build-da95f2d55564/output/aarch64-linux-gnu/bitcoin-da95f2d55564-aarch64-linux-gnu.tar.gz
310232eb7aebc36dbaa77921e753d74a684bbc2e0ad4f7be24da75777ee160b0  guix-build-da95f2d55564/output/arm-linux-gnueabihf/SHA256SUMS.part
a74484af4af29cbd67960f6a9100abc492ccf7ffee540a7d4acf60c55963d016  guix-build-da95f2d55564/output/arm-linux-gnueabihf/bitcoin-da95f2d55564-arm-linux-gnueabihf-debug.tar.gz
b44faab4a698668e9180a09afd7b2d7f78e7edafc10e697f4f23afb22843e712  guix-build-da95f2d55564/output/arm-linux-gnueabihf/bitcoin-da95f2d55564-arm-linux-gnueabihf.tar.gz
1c702326d333dbe31516d221dce1cf924cefb7715770b354c9effc21dc752ade  guix-build-da95f2d55564/output/arm64-apple-darwin/SHA256SUMS.part
97ffd737d1c9de384c535f696f350d158a52942c8010bde4de4e4b4e6a648920  guix-build-da95f2d55564/output/arm64-apple-darwin/bitcoin-da95f2d55564-arm64-apple-darwin-unsigned.dmg
033e96ca238457375a2274aa266464d80e5bf7c2b0aae778adfc2a846030cb7c  guix-build-da95f2d55564/output/arm64-apple-darwin/bitcoin-da95f2d55564-arm64-apple-darwin-unsigned.tar.gz
8c945b3761c55617fa354b5439dbc9dbf6b9a9a1cd466c6a0d796b62c266cec6  guix-build-da95f2d55564/output/arm64-apple-darwin/bitcoin-da95f2d55564-arm64-apple-darwin.tar.gz
02c8be087b05316d8861886e1ce23f6d7fb241e8099fc9319de33e160e5b900b  guix-build-da95f2d55564/output/dist-archive/bitcoin-da95f2d55564.tar.gz
3e5e8266245020c68653084d22d41abc8fab70578c487fc35723353c68c3604d  guix-build-da95f2d55564/output/powerpc64-linux-gnu/SHA256SUMS.part
970f2c5a6e66bce51ed43a5abc3f7a337e17de72bd08e643e6074a4e11c41a65  guix-build-da95f2d55564/output/powerpc64-linux-gnu/bitcoin-da95f2d55564-powerpc64-linux-gnu-debug.tar.gz
c954ec664882c9dedc28285c9478323253487fdd0a79471e09c32049ee2777de  guix-build-da95f2d55564/output/powerpc64-linux-gnu/bitcoin-da95f2d55564-powerpc64-linux-gnu.tar.gz
f987ae3b640887af59e0bc15f678f8c85492d4908986e8e50c4e755303a01ef2  guix-build-da95f2d55564/output/powerpc64le-linux-gnu/SHA256SUMS.part
e9169169813e29ce4e8bfa92945395b3a8c93319a06ef83f44da6364fe8cdd7d  guix-build-da95f2d55564/output/powerpc64le-linux-gnu/bitcoin-da95f2d55564-powerpc64le-linux-gnu-debug.tar.gz
05d2b9017fa88a570932042486ff7248f0bf4845d60c6406e1c9da1044cf6ad6  guix-build-da95f2d55564/output/powerpc64le-linux-gnu/bitcoin-da95f2d55564-powerpc64le-linux-gnu.tar.gz
2aa8fda73878b63132df488b458b65bd203f1a81a1c9989ce072424aa013af33  guix-build-da95f2d55564/output/riscv64-linux-gnu/SHA256SUMS.part
a523f60e342e374583f638a50ec59e61a574c1a2609c86532feaed1cf478556a  guix-build-da95f2d55564/output/riscv64-linux-gnu/bitcoin-da95f2d55564-riscv64-linux-gnu-debug.tar.gz
afb3162eeadb1a73be8bce337de7f29f0008dbe2497649ed804daae154d7731f  guix-build-da95f2d55564/output/riscv64-linux-gnu/bitcoin-da95f2d55564-riscv64-linux-gnu.tar.gz
d8cb586faf2b09b0c2658416c8d91ab687d3369ce86c99531019455e103999fe  guix-build-da95f2d55564/output/x86_64-apple-darwin/SHA256SUMS.part
7c5c1c65399c7413bcb4edce444e7f683307878c94bca05ec95f168334f2f235  guix-build-da95f2d55564/output/x86_64-apple-darwin/bitcoin-da95f2d55564-x86_64-apple-darwin-unsigned.dmg
3a5bab918e7d15f56061db517ccd851708e4400460f2cb3635feb444613ff10a  guix-build-da95f2d55564/output/x86_64-apple-darwin/bitcoin-da95f2d55564-x86_64-apple-darwin-unsigned.tar.gz
7c104159d98a0a31a5f2e0d837931a504f4192368e446eaf97c44cb88a8d1325  guix-build-da95f2d55564/output/x86_64-apple-darwin/bitcoin-da95f2d55564-x86_64-apple-darwin.tar.gz
b6a0663ce2221ef7cf269104f836e78a4864850f162281adb64232bc2c747272  guix-build-da95f2d55564/output/x86_64-linux-gnu/SHA256SUMS.part
45fe4c15cbd7d52ea2c7078b6d3409c8e0332529911634d2ed9d141b5c7d2cc6  guix-build-da95f2d55564/output/x86_64-linux-gnu/bitcoin-da95f2d55564-x86_64-linux-gnu-debug.tar.gz
287c3c328276b6ac8016bf9c987b4dc5b4ecca9321fe4750176628beff8fffd8  guix-build-da95f2d55564/output/x86_64-linux-gnu/bitcoin-da95f2d55564-x86_64-linux-gnu.tar.gz
cb79ce0b1ea9718b7742e14dbd73dcb367074dd179c311ba080812923d4bf892  guix-build-da95f2d55564/output/x86_64-w64-mingw32/SHA256SUMS.part
82e45bbf29041781d14f4e0d11d47c1ea4dc8f2c60b10187604a3691ee75362a  guix-build-da95f2d55564/output/x86_64-w64-mingw32/bitcoin-da95f2d55564-win64-debug.zip
f0d3540dd04ea6ef764e3ac7febd4e0660d2e07496f538253d037874dcf010e5  guix-build-da95f2d55564/output/x86_64-w64-mingw32/bitcoin-da95f2d55564-win64-setup-unsigned.exe
95b7b2b58f32f51cffb15d027ed0503be8b7695a090177ad0a30e782b3b27118  guix-build-da95f2d55564/output/x86_64-w64-mingw32/bitcoin-da95f2d55564-win64-unsigned.tar.gz
39cf6fb127ff99a971c97ec2ca4ce955de860ff68b9d3ba342e481cc95feff1c  guix-build-da95f2d55564/output/x86_64-w64-mingw32/bitcoin-da95f2d55564-win64.zip
```

arm64:
```

```

**Comment by fanquake** [comment]
If we are going to do this, I think we might as well update the config.guess/sub shipped with depends at the same time.

**Comment by fanquake** [comment]
Want to rebase this?

**Comment by hebasto** [comment]
> Want to rebase this?

Done.

**Comment by hebasto** [comment]
The PR description has been updated with the recent Guix build hashes.

**Review by Adriana1960 — APPROVED** [review]

**Review by fanquake — APPROVED** [review]
ACK ea7b8528490d330f0f4e34e9b26ab00ba528f546

**Pull request merged**
