### PR TITLE
[0.18.2] Backports

### PR DESCRIPTION
**Pull request by fanquake**
Backports some commits to the `0.18` branch:

* #16596 - rpc: Fix getblocktemplate CLI example
* #16615 - doc: Fix typos in COPYRIGHT
* #16291 - gui: Stop translating PACKAGE_NAME (without the `make translate` commit)
* #16578 - Do not pass in command line arguments to QApplication
* #16051 - depends: add patch to common dependencies
* #16090 - Add vertical spacer
* #15651 - torcontrol: Use the default/standard network port for Tor hidden services, even if the internal port is set differently
* #15650 - Handle the result of posix_fallocate system call
* #16646 - Bugfix: QA: Run tests with UPnP disabled
* #16212 - addrdb: Remove temporary files created in SerializeFileDB. Fixes non-determinism in unit tests.
* #16512 - rpc: Shuffle inputs and outputs after joining psbts
* #16870 - build: update boost macros to latest upstream for improved error reporting
* #16982 - build: Factor out qt translations from build system
* #17095 - util: Filter control characters out of log messages

### CODE REVIEW

**Comment by luke-jr** [comment]
#16578 should be reverted, and certainly is not a bugfix, so shouldn't be backported in any case.

**Comment by luke-jr** [comment]
Suggest adding luke-jr/bitcoin 20190823-0.18-backports branch in. That adds:

* #16051 - depends: add patch to common dependencies
* Part of #15758 to make #16079 cleaner:
* * test: Check that wallet txs not in the mempool are untrusted
* * test: Add reorg test to wallet_balance
* #16079 - wallet_balance.py: Prevent edge cases
* #16090 - Add vertical spacer
* #16144 - wallet: do not encrypt wallets with disabled private keys
* #15651 - torcontrol: Use the default/standard network port for Tor hidden services, even if the internal port is set differently
* #15650 - Handle the result of posix_fallocate system call
* #16646 - Bugfix: QA: Run tests with UPnP disabled
* #16212 - addrdb: Remove temporary files created in SerializeFileDB. Fixes non-determinism in unit tests.

**Comment by fanquake** [comment]
Rebased on `0.18` and added a bunch of the suggested commits, will take a look at the remaining later.

**Comment by fanquake** [comment]
Added #16512. Note that in the [first commit](https://github.com/bitcoin/bitcoin/pull/16617/commits/1c1ad3c7b9c471768d574a6a934dacded3fff7e3#diff-01aa7d1d32f1b9e5a836c9c411978918L22) the header include has been changed from `#include <rpc/rawtransaction_util.h>` to `#include <rpc/rawtransaction.h>`.

**Comment by fanquake** [comment]
Added #16870. Note that the [commit](4e3f39434d26b06c924cf3f5154075f02b18d06c) differs in that the boost_base.m4 includes additional changes to update it to the latest upstream, which was updated in master as part of 2620e24b83d16bf0f2bfe360dee1e98b4be59ca5.

**Comment by MarcoFalke** [comment]
What is the status of this?

**Comment by fanquake** [comment]
@MarcoFalke There's a fair few commits in here. I'd like it to get some review and be merged rather than add any more changes.

**Comment by laanwj** [comment]
ACK 0b18ea6f570e24c9719c10eb6e125da743409c58

I repeated the cherry-picks here and resolved the conflicts in pretty much the same way.

**Pull request merged**
