### PR TITLE
Make sure LogPrint strings are line-terminated

### PR DESCRIPTION
**Pull request by rnicoll**
Seems to have been missed in #6497, but do let me know if there's a reason this shouldn't have a new line at the end.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
utACK.

**Comment by fanquake** [comment]
utACK

**Comment by paveljanik** [comment]
ACK

**Comment by laanwj** [comment]
utACK
Seems that I missed this, due to some other debug prints in net that do lack \n for a reason (as they're part of a set of multiple prints).

**Pull request merged**
