### PR TITLE
Use system univalue by default

### PR DESCRIPTION
**Pull request by luke-jr**
For future merging

### CODE REVIEW

**Comment by laanwj** [comment]
Previous discussion was in #7349, where it was decided *not* to automatically use an installed univalue in favor of the included one.

**Comment by luke-jr** [comment]
...for now.

**Comment by dcousens** [comment]
Why would you opt for system default?  Out of interest.

**Comment by luke-jr** [comment]
Standard best practices. Libraries shouldn't be bundled *at all*. We have a reasonable case for bundling consensus-critical ones like LevelDB and libsecp256k1, but Univalue is not consensus-critical at all.

**Comment by laanwj** [comment]
We're not going to do this (at least for the forseeable future), so closing for now.

**Pull request closed without merging**
