### PR TITLE
 [depends] Delete unused patches 

### PR DESCRIPTION
**Pull request by maflcko**

### CODE REVIEW

**Comment by jonasschnelli** [comment]
utACK fab4e7641c7e14634a7d8f13904054d6bd608ff4
ping @theuni

**Comment by laanwj** [comment]
Can you please be a bit more verbose in your commit message:
- Why were these patches there
- Why are they no longer needed

**Comment by MarcoFalke** [comment]
The patches are no longer used since https://github.com/bitcoin/bitcoin/commit/4bdad99f5000539dcf03ddc92c142fa6deb44c01#diff-348b8d945e85fb166a4cf611fa2e2f99L29. Also, I suspect they are bit rotten as we bumped to 1.59 already.

**Comment by theuni** [comment]
ut ACK. IIRC I back-ported these directly from boost master at the time, so dropping them in favor of a later fixed release makes sense.

**Comment by laanwj** [comment]
OH I was completely misreading the diff here, due to the surprising highlighting of a second-order diff.
You're just deleting the files not removing parts of it.
utACK fafe446

**Pull request merged**
