### PR TITLE
docs: improved grammar

### PR DESCRIPTION
**Pull request by xternet**

### CODE REVIEW

**Comment by MarcoFalke** [comment]
I think this is fine to just keep as is, since there is nothing wrong with it, so there is no need to change.

**Comment by xternet** [comment]
> I think this is fine to just keep as is, since there is nothing wrong with it, so there is no need to change.

@MarcoFalke There is a mistake:
_"...whereas block information and metadata independent of the current tip ~~**is**~~ kept in `BlockManager`."_

**is=>are**

**Comment by jarolrod** [comment]
fine to keep as is

**Comment by MarcoFalke** [comment]
Closing for now, as this seems controversial

**Pull request closed without merging**
