### PR TITLE
p2p: Remove dead code for nVersion=10300

### PR DESCRIPTION
**Pull request by maflcko**
This code is undocumented and confusing as well as dead, since peers with a version that old are disconnected immediately.

### CODE REVIEW

**Comment by laanwj** [comment]
utACK fa5099ceb757c9d56fa54a08d0441750df6c8869

**Review by scravy — APPROVED** [review]
<3

**Review by domob1812 — APPROVED** [review]
utACK fa5099ceb757c9d56fa54a08d0441750df6c8869.

**Comment by Empact** [comment]
utACK fa5099c `MIN_PEER_PROTO_VERSION` is `31800`

**Comment by practicalswift** [comment]
utACK fa5099ceb757c9d56fa54a08d0441750df6c8869

**Comment by jnewbery** [comment]
utACK fa5099ceb757c9d56fa54a08d0441750df6c8869

If you felt like it you could also remove a bunch of additional code from the `msg_version` class in `test_framework/messages.py` since the test framework won't work for anything older than a release or two ago. You could remove the `if self.nVersion >= 106` and `if self.nVersion >= 209:` conditionals.

**Comment by jnewbery** [comment]
utACK fa74d3d720f72c5f1184ca3e03b0c14a2bc06ed5.

We could also assert that the version is greater than MIN_PEER_PROTO_VERSION in the desererialize method of msg_version, but maybe that's overkill.

**Pull request merged**
