### PR TITLE
ci: Fix previous releases cache order

### PR DESCRIPTION
**Pull request by maflcko**

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Reported in https://github.com/bitcoin/bitcoin/pull/21619#issuecomment-817134054 by @hebasto . Thanks!

**Review by hebasto — COMMENTED** [review]
Concept ACK fa4f0b301ba5c07f1271fa7129d07683014d169b.

Does the populated cache prevent from downloading releases again: https://github.com/bitcoin/bitcoin/blob/f6c44e999b7d1d9a0de5d678ac8f1679aa271f65/ci/test/05_before_script.sh#L58-L60?

Maybe the [`populate_script`](https://cirrus-ci.org/guide/writing-tasks/#cache-instruction) field could be useful?

**Comment by MarcoFalke** [comment]
Not sure what you mean. The cache is populated and everything is green: https://cirrus-ci.com/task/6695630107049984?logs=previous_releases#L2

**Comment by MarcoFalke** [comment]
It is also greeen without cache: https://cirrus-ci.com/task/5560067312320512?logs=previous_releases#L1

**Comment by hebasto** [comment]
> Not sure what you mean.

Just trying to answer to myself "What is the role of the previous releases cache in the CI setup? Speedup what?"

**Comment by laanwj** [comment]
I think the idea of the cache is to avoid downloading the previous releases from bitcoincore.org every test run?

**Comment by hebasto** [comment]
> I think the idea of the cache is to avoid downloading the previous releases from bitcoincore.org every test run?

Agree. But currently it does not work like that.

**Comment by MarcoFalke** [comment]
It does:

```
Releases directory: /tmp/cirrus-build/releases/x86_64-pc-linux-gnu
Using cached v0.15.2
Using cached v0.16.3
Using cached v0.17.2
Using cached v0.18.1
Using cached v0.19.1
```

https://cirrus-ci.com/task/6695630107049984?logs=ci#L1993

**Comment by hebasto** [comment]
> It does:

Right. It is responsibility of [`test/get_previous_releases.py`](https://github.com/bitcoin/bitcoin/blob/master/test/get_previous_releases.py).

**Review by hebasto — APPROVED** [review]
ACK fa4f0b301ba5c07f1271fa7129d07683014d169b

**Pull request merged**
