### PR TITLE
Make Bitcoin Core compatible with NYA segwit2x

### PR DESCRIPTION
**Pull request by hovah**

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
https://bitcoincore.org/en/2017/08/18/btc1-misleading-statements/

**Comment by jonasschnelli** [comment]
Strong concept NACK.

**Comment by molxyz** [comment]
NACK

**Comment by alp-bitcoin** [comment]
Nack, consensus level changes require consensus from the ecosystem.  SegWit2X is clearly contentious.

**Comment by mattstrong** [comment]
This sucks

**Comment by jaredfranka** [comment]
NACK
OWND

**Comment by ReneFroger** [comment]
There is no consensus with all Core developers about unncessary blocksize increment. What's next? 8 MB? 16 MB? 32 MB? 1GB? 100GB? You need to think different about viable solutions.

With eternally blocksize, Bitcoin will process transactions on scale as Paypal and VISA, but it's not different anymore from them and could run only by big companies. Bitcoin is for the Joe the Average who want to control his own money. Not the money system as big enterprises wished to be. You need to think in the long term, thtat's what really counts eventually.

**Comment by Cocosoft** [comment]
Concept NACK.
SegWit2x, being a hardfork, needs strong consensus across the ecosystem, I don't see this being the case.

I also think we should evaluate how the network reacts to ~2MB+ blocks enabled by SegWit, before making any decisions on a further blocksize increase.

**Comment by errge** [comment]
NACK, LOL :)

**Comment by nomnombtc** [comment]
Sad to see that this PR was closed instantly on the same day... Why not let users opt-in to 2x.

What are bitcoin-core's plans if 90% of the hashrate will possibly mine btc1 blocks in november (https://coin.dance/blocks)?

**Comment by MarcoFalke** [comment]
I want to remind that the review comments on pull requests are not meant for extended off-topic discussions. Please switch to another channel and keep this discussion for review comments on the code.

Refer to the [guidelines](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#decision-making-process) on how to write a good peer review.

**Pull request closed without merging**
