### PR TITLE
0.15 release-notes nits: fix redundancy, remove accidental parenthesis & fix range style

### PR DESCRIPTION
**Pull request by practicalswift**
0.15 release-notes nits:
* Remove accidental parenthesis
* Fix redundancy ("remain" vs. previous "continue to remain")
* Fix range style ("from X to Y" vs. previous "from X-Y")

### CODE REVIEW

**Comment by practicalswift** [comment]
Travis failure for `p2p-leaktests.py` unrelated :-)  Is it just me or has the number of spurious Travis failures increased recently?

**Comment by jnewbery** [comment]
> Is it just me or has the number of spurious Travis failures increased recently?

@practicalswift - yes, that's my sense as well. This particular failure is a new test added by me in #11001, but I haven't seen it fail in this way before. It appears that the node doesn't receive a version message that the test framework sends to it, possibly because we're trying to connect too soon after changing the mocktime. I'll see if adding a sleep to the test fixes that.

I've restarted the job for you.

**Comment by sipa** [comment]
utACK dd0adb61fa31e37d02e57cd68baee543533bd4fb

**Comment by fanquake** [comment]
ACK after squashing. Please use a commit message that mentions updating the release notes.

**Comment by practicalswift** [comment]
@fanquake Squashed! :-)

**Comment by fanquake** [comment]
utACK 30c246b

**Comment by laanwj** [comment]
utACK/30c246b

**Pull request merged**
