### PR TITLE
[WIP] [RPC] Add call zaptransaction to delete transaction from wallet

### PR DESCRIPTION
**Pull request by instagibbs**
No tests yet, looking for concept ACKs, or to see what people would want for this. 

It's essentially mirror functionality of https://github.com/bitcoin/bitcoin/pull/7558. 

I am not sure how mempool interacts with this(I'm guessing I should check if it's in block/mempool like abandontransaction does) but the usage is intended for in-block transactions.

### CODE REVIEW

**Comment by laanwj** [comment]
I think the idea behind `abandontransaction` as introduced in 0.12 was to provide this functionality in a safer way. Deleting anything permanently from the db shouldn't be done lightly.
Ping @morcos

**Comment by instagibbs** [comment]
While similar, this functionality is more meant to pair with #7558, which isn't applicable to abandontransaction. If you have a transaction in your wallet that is confirmed, yet you do not want to "account for" as having the funds, there isn't a way to do this. Primarily I think this could happen for instance with an erroneous application of #7558 .

**Comment by laanwj** [comment]
I understand the application is different, but there's a risk in having vaguely similar functionality in different RPC calls.
Before adding abandontransaction we had a long discussion about what would be safe as well versus unsafe RPC call behavior for this purpose, so it already is a compromise.

Idea: If it is meant as antidote to #7558, why not call it `removeprunedfunds` and make it only work on funds thus added?

**Comment by instagibbs** [comment]
Understood and agreed. I might want to merge the two PRs then, and tag transactions in such a way to ensure that property.

**Comment by morcos** [comment]
I don't have a strong opinion about this functionality.
I do think it is quite different from abandontransaction though

**Comment by laanwj** [comment]
Well if really they're sufficiently different hat people won't get confused, I'm ok with adding this... But based on the names at least I would get confused as API user, I think. But that may be a documentation issue.

**Comment by instagibbs** [comment]
Closing in favor of merging the two PRs, with more aligned names and description.

**Pull request closed without merging**
