### PR TITLE
depends: Remove Qt build-time dependencies

### PR DESCRIPTION
**Pull request by laanwj**
In the spirit of the halving, let's (approximately) halve the number of packages in depends. Remove the following packages:
```diff
  bdb.mk
  boost.mk
  capnp.mk
- expat.mk
- fontconfig.mk
- freetype.mk
  libevent.mk
  libmultiprocess.mk
  libnatpmp.mk
- libXau.mk
- libxcb.mk
- libxcb_util.mk
- libxcb_util_image.mk
- libxcb_util_keysyms.mk
- libxcb_util_render.mk
- libxcb_util_wm.mk
- libxkbcommon.mk
  miniupnpc.mk
  native_capnp.mk
  native_cctools.mk
  native_libmultiprocess.mk
  native_libtapi.mk
  native_llvm.mk
  packages.mk
  qrencode.mk
  qt.mk
+ qtsowrap.mk
  sqlite.mk
  systemtap.mk
- xcb_proto.mk
- xproto.mk
  zeromq.mk
```
This is done by loading all of Qt's system dependencies at run-time, replacing them with an auto-generated wrapper library `qtsowrap`:

Basic diagram

See https://github.com/laanwj/qtsowrap for details.

After this, `bitcoin-qt` has the same direct linking dependencies as `bitcoind` and other binaries:
```
$ ldd build/src/qt/bitcoin-qt
        linux-vdso.so.1 (0x00007ffc01d83000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f76dbf1f000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f76dbc00000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f76de7a7000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f76dba1f000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f76de7d7000)
```
(libdl.so.X needed too depending on the libc version)

For comparison, `bitcoin-qt` from release 27.0 has the following:
```
$ ldd ~/workdir/x86_64-linux-gnu/bitcoin-27.0/bin/bitcoin-qt 
        linux-vdso.so.1 (0x00007ffde7f73000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa098e37000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa098e2f000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa098d4f000)
        libfontconfig.so.1 => /lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007fa098cff000)
        libfreetype.so.6 => /lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007fa09632f000)
        libxcb-icccm.so.4 => /lib/x86_64-linux-gnu/libxcb-icccm.so.4 (0x00007fa098cf7000)
        libxcb-image.so.0 => /lib/x86_64-linux-gnu/libxcb-image.so.0 (0x00007fa098cef000)
        libxcb-shm.so.0 => /lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007fa098ce7000)
        libxcb-keysyms.so.1 => /lib/x86_64-linux-gnu/libxcb-keysyms.so.1 (0x00007fa096000000)
        libxcb-randr.so.0 => /lib/x86_64-linux-gnu/libxcb-randr.so.0 (0x00007fa098ccf000)
        libxcb-render-util.so.0 => /lib/x86_64-linux-gnu/libxcb-render-util.so.0 (0x00007fa095c00000)
        libxcb-render.so.0 => /lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007fa098cbf000)
        libxcb-shape.so.0 => /lib/x86_64-linux-gnu/libxcb-shape.so.0 (0x00007fa098cb7000)
        libxcb-sync.so.1 => /lib/x86_64-linux-gnu/libxcb-sync.so.1 (0x00007fa098caf000)
        libxcb-xfixes.so.0 => /lib/x86_64-linux-gnu/libxcb-xfixes.so.0 (0x00007fa098c9f000)
        libxcb-xinerama.so.0 => /lib/x86_64-linux-gnu/libxcb-xinerama.so.0 (0x00007fa096327000)
        libxcb-xkb.so.1 => /lib/x86_64-linux-gnu/libxcb-xkb.so.1 (0x00007fa096307000)
        libxcb.so.1 => /lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fa0962d7000)
        libxkbcommon-x11.so.0 => /lib/x86_64-linux-gnu/libxkbcommon-x11.so.0 (0x00007fa0962c7000)
        libxkbcommon.so.0 => /lib/x86_64-linux-gnu/libxkbcommon.so.0 (0x00007fa09627f000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa09625f000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa095e1f000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fa098e4f000)
        libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fa09622f000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fa09620f000)
        libpng16.so.16 => /lib/x86_64-linux-gnu/libpng16.so.16 (0x00007fa095bc7000)
        libbrotlidec.so.1 => /lib/x86_64-linux-gnu/libbrotlidec.so.1 (0x00007fa095e0f000)
        libxcb-util.so.1 => /lib/x86_64-linux-gnu/libxcb-util.so.1 (0x00007fa095bbf000)
        libXau.so.6 => /lib/x86_64-linux-gnu/libXau.so.6 (0x00007fa096207000)
        libXdmcp.so.6 => /lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fa095800000)
        libbrotlicommon.so.1 => /lib/x86_64-linux-gnu/libbrotlicommon.so.1 (0x00007fa095b97000)
        libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007fa095b7f000)
        libmd.so.0 => /lib/x86_64-linux-gnu/libmd.so.0 (0x00007fa095b6f000)
```

This does not affect Windows or MacOS, which already do not have this problem of having to build half the OS in the dependency chain.

This will make it possible to add Wayland support to the release binaries without requiring the Wayland (or X) libraries to be installed on every system that runs them.

## Reviewing/Testing

- Three relatively small Python scripts that generate everything:
  - https://github.com/laanwj/qtsowrap/blob/main/scripts/collector.py
  - https://github.com/laanwj/qtsowrap/blob/main/scripts/gen.py
  - https://github.com/laanwj/qtsowrap/blob/main/scripts/generate-wrapper.py  
- One important thing to test is that the resulting `bitcoin-qt` binaries work on a range of different Linux distributions (also older ones that people still care about).
- i've added some review notes for the Qt patch here: https://github.com/laanwj/qtsowrap?tab=readme-ov-file#patching-qt . What is important to ensure is that `initialize_` happens before any calls to a library, as calling early will cause a crash. Forgetting to wrap a header will be found during linking, as the symbol will be wrong, so it's not a review concern.

## TODOs (all done)

(before merge, probably)
- laanwj/qtsowrap#3 
- laanwj/qtsowrap#4

### CODE REVIEW

**Comment by Gary19751957** [comment]
Why am I receiving these emails?This person is using my email to hack my
Bitcoin account,please help, Gary Rollins my phone number is 8593467976
please help!!

Gary Rollins

**Comment by luke-jr** [comment]
Instead of Qt's dependencies, maybe we should wrap Qt itself this way? Or do C++ templates break that too much?

**Comment by laanwj** [comment]
> Instead of Qt's dependencies, maybe we should wrap Qt itself this way? Or do C++ templates break that too much?

This is basically not possible with a C++ library. It is thanks to C's lack of name mangling and its straightforward linking model that makes this possible. Also Qt has a ton of symbols compared to these libraries.

Conceptually, a few low-level X (or in the future, Wayland) and font libraries are much likely to be on the user's system than a compatible version of Qt. That will only become worse with Qt 5 versus 6.

**Comment by laanwj** [comment]
One important thing to test here is that the resulting binaries work on a range of different Linux distributions (also older ones that people still care about). 

There's no inherent reason to assume this will make compatibility worse, but it currently loads *all* symbols from the headers for the respective libraries (https://github.com/laanwj/qtsowrap?tab=readme-ov-file#versions) which might enforce the lower bound on version stronger than used to be done.

Might consider downgrading the headers, if this turns out to be a problem. Or add a list in the descriptor per library of the functions actually used. But this is more work to maintain.

**Comment by laanwj** [comment]
Example: failure on Ubuntu 22.04:
```
$ ./bitcoin-qt
/lib/x86_64-linux-gnu/libxcb-xfixes.so.0: undefined symbol: xcb_xfixes_set_client_disconnect_mode_checked
qt.qpa.xcb: Unable to load required libraries, skipping initialization of XCB backend.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

Aborted (core dumped)
```
Ubuntu 22.04 has the following version of libxcb-xfixes:
```
$ apt-cache show libxcb-xfixes0
Package: libxcb-xfixes0
Architecture: amd64
Version: 1.14-3ubuntu3
```
1.14. That's kind of strange! That's the same one we have.
It may be due to a difference in `xcb_proto` (which supplies the protocols that the header files are generate from) instead.
Ours is 1.15.2, ubuntu 22.04 has `1.14`. So i'll downgrade to that.

**Comment by laanwj** [comment]
i've added some review notes for the Qt patch here: https://github.com/laanwj/qtsowrap?tab=readme-ov-file#patching-qt

**Comment by theuni** [comment]
Neat!

**Comment by laanwj** [comment]
Okay, i implemented a script to download the upstream tarballs and extract the headers from there\*.. 

So everything except what is in `scripts` is generated--this makes it traightforward to change the required interface versions in [collector.py](https://github.com/laanwj/qtsowrap/blob/main/scripts/collector.py) by pointing it to a different tarball and re-running the process, and committing the changes to git.

The entire process is deterministic so can also be used to verify that the headers in git are correct.

\* for `xcb_proto` this does require it to invoke a  generator script, to generate the headers from xml, however that's done in a minimalistic way, without invoking its entire build/install process

**Comment by laanwj** [comment]
Looks like we could drop 'bison' as a dependency here, it was used by the `xkbcommon` build which is dropped.

**Comment by laanwj** [comment]
Rebased for merge conflict and to apply fixup commits.

**Comment by laanwj** [comment]
Rebased for #29985 (add/add).

**Comment by laanwj** [comment]
All outstanding TODOs were done. Rebased to master, collected fixups.

**Review by jonatack — COMMENTED** [review]
Concept ACK. This looks like amazing work, great!

I'm not sure how to help test. Using arm64 macOS 14.4.1, this branch builds cleanly, the unit tests pass, and the GUI runs fine. Don't see any issues on first read of the code.

```
$ clang --version
Homebrew clang version 18.1.5
Target: arm64-apple-darwin23.4.0
Thread model: posix
InstalledDir: /opt/homebrew/opt/llvm/bin
```

**Comment by laanwj** [comment]
> I'm not sure how to help test. Using arm64 macOS 14.4.1, this branch builds cleanly, the unit tests pass, and the GUI runs fine. Don't see any issues on first read of the code.

Thanks for testing! To be clear, this shouldn't affect MacOS at all, Qt on MacOS (and Windows) doesn't have any of the huge bag of dependencies that Qt Linux/UNIX has.

**Comment by laanwj** [comment]
> I did test an earlier draft of this pull request and the only thing I noticed was that on a fresh desktop install of a Linux distro, sometimes a package would be missing, and the GUI would fail to start.

Do you have specific output or details? That isn't expected behavior. This PR doesn't change the libraries required to be installed on the user's system, all the dependencies that this removes were already built only to link against. The only difference is that they're loaded at runtime using `dlopen` instead of by the dynamic linker before the binary runs.

**Comment by laanwj** [comment]
@maflcko Thank you for testing!

**Comment by theuni** [comment]
Closed on purpose?

**Comment by laanwj** [comment]
i was a bit tired of seeing "you need to rebase" messages, will get around to this 😄

**Comment by laanwj** [comment]
Force-push: rebased to master for qt version bump. Trivial changes to depends, didn't need to change qt patch.

**Pull request closed without merging**
