### PR TITLE
Fix insanity of CWalletDB::WriteTx and CWalletTx::WriteToDisk

### PR DESCRIPTION
**Pull request by pstratem**

### CODE REVIEW

**Comment by MarcoFalke** [comment]
utACK 0fd5997

**Comment by jonasschnelli** [comment]
utACK 0fd599767d2dabf25ac8c3543cb586cfc4b9d816

**Comment by TheBlueMatt** [comment]
utACK 0fd599767d2dabf25ac8c3543cb586cfc4b9d816

**Comment by sipa** [comment]
utACK 0fd599767d2dabf25ac8c3543cb586cfc4b9d816

**Comment by paveljanik** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/8028/commits/0fd599767d2dabf25ac8c3543cb586cfc4b9d816

**Pull request merged**
