### PR TITLE
doc: Drop historical release-notes directory

### PR DESCRIPTION
**Pull request by luke-jr**
It's incomplete and just wastes a growing amount of space every release.

People who want to read them can still get them from their respective releases/tags.

### CODE REVIEW

**Comment by fanquake** [comment]
Any reason for the new PR? I was happy to modify the one I've got open if the consensus was to dump these.

**Comment by luke-jr** [comment]
Oh, thought you were suggesting making a PR for it. Oh well.

**Comment by achow101** [comment]
> People who want to read them can still get them from their respective releases/tags.

Usually we finish writing release notes after the tag has been made, so I don't think that will be the case. Unless we make a concerted effort to finish release notes before tagging.

**Comment by luke-jr** [comment]
>Usually we finish writing release notes after the tag has been made, so I don't think that will be the case.

AFAIK that's only happened once, by accident. It also means the software ships with the incomplete notes if so.

**Review by jarolrod — COMMENTED** [review]
I think we should keep the release notes for this release cycle, and open the question on the usefulness of these docs at a later point

**Review by kouloumos — COMMENTED** [review]
Although 23.0 release notes were missing the big PR list, I sometimes found that useful when doing codebase archeology as an additional tool to spot changes.

Also another point [previously mentioned from Murch on IRC](https://bitcoin-irc.chaincode.com/bitcoin-core-dev/2022-04-27#807906;).

**Comment by fanquake** [comment]
Given the comments here, and additional comments in IRC, there doesn't seem to be consensus on removing these. Going to close this for now.

**Pull request closed without merging**
