### PR TITLE
test: fix accurate multisig sigop count (BIP16), add unit test

### PR DESCRIPTION
**Pull request by theStack**
In the course of reviewing #29589 I noticed the following buggy call-site of `CScriptOp.decode_op_n` in the CScript's `GetSigOpCount` method:
https://github.com/bitcoin/bitcoin/blob/4cc99df44aec4d104590aee46cf18318e22a8568/test/functional/test_framework/script.py#L591-L593
This should be `lastOpcode` rather than `opcode`. The latter is either OP_CHECKMULTISIG or OP_CHECKMULTISIGVERIFY at this point, so `decode_op_n` would result in an error. Also, in `CScript.raw_iter`, we have to return the op as `CScriptOp` type instead of a bare integer, otherwise we can't call the decode method on it. To prevent this in the future, add some simple unit tests for `GetSigOpCount`.

Note that this was unnoticed, as the code part was never hit so far in the test framework.

### CODE REVIEW

**Review by Christewart — APPROVED** [review]
ACK 3e9c736a26724ffe3b70b387995fbf48c06300e2

Please review #29589 and (if you are feeling very generous) #29371 :-)

**Review by rkrux — APPROVED** [review]
tACK [3e9c736](https://github.com/bitcoin/bitcoin/pull/29615/commits/3e9c736a26724ffe3b70b387995fbf48c06300e2)

1. Make successful
2. Functional tests successful

Asked couple questions for my clarity.

**Review by hernanmarino — APPROVED** [review]
tACK 3e9c736a26724ffe3b70b387995fbf48c06300e2

**Comment by achow101** [comment]
ACK 3e9c736a26724ffe3b70b387995fbf48c06300e2

**Pull request merged**
