### PR TITLE
ci: Roll clang in test-each-commit task

### PR DESCRIPTION
**Pull request by maflcko**
Needed for https://github.com/bitcoin/bitcoin/pull/29077#issuecomment-2099704210

### CODE REVIEW

**Review by fanquake — APPROVED** [review]
ACK 2094da680fe580ba1bc62e9bab1e196f5e1c5341

**Comment by fanquake** [comment]
Yea, don't have to merge, but can do as soon as we have green CI. The image should be available very shortly?

**Review by mouhand999 — APPROVED** [review]

**Review by hebasto — APPROVED** [review]
ACK 2094da680fe580ba1bc62e9bab1e196f5e1c5341.

> This fails, because the image does not exist yet.

I've re-run the CI job.

**Review by hebasto — APPROVED** [review]
re-ACK fa90ad23c0cb99bde305af156c978c066f7bacb8.

**Pull request merged**
