### PR TITLE
doc: Added instructions in CONTRIBUTE.MD for adding an upstream to forked repo

### PR DESCRIPTION
**Pull request by dannmat**

### CODE REVIEW

**Comment by dannmat** [comment]
I have 7 commits in the pull request, so I feel like I've done something wrong. Can somebody please advise me if this is normal?

**Comment by MarcoFalke** [comment]
I think you can get rid of merge commits like so (untested):

```
git merge upstream/master
git reset --soft upstream/master
git commit -m "the commit message of all commits squashed..."

**Comment by dannmat** [comment]
I've added more commits here. I can't seem to get these down. Am I suppose to be rebasing to squash the commits into one?

**Comment by fanquake** [comment]
Yes, the only commit that should be here is your change.

**Pull request closed without merging**
