### PR TITLE
doc: Remove newlines from error message 

### PR DESCRIPTION
**Pull request by practicalswift**
Fix accidental use of the addition assignment operator (`+=`).

_Note to reviewers:_ Perhaps the `\n`:s should be removed too?

### CODE REVIEW

**Comment by Empact** [comment]
utACK 4df2fbc

**Comment by practicalswift** [comment]
@Empact Now removing newlines as well :-)

**Comment by Empact** [comment]
How about also remove the last of the 3, in init.cpp? (found via `/InitError\(.+\\n/`)

That would also be an easy case to test how these look without newlines, because you can set the blocksdir to a non-existent location.

**Comment by practicalswift** [comment]
@Empact Thanks! Now fixed. Please re-review :-)

**Comment by Empact** [comment]
Tested ACK ee34012

```
$ src/bitcoind -blocksdir=somenonsense
Error: Specified blocks directory "somenonsense" does not exist.
$ 
```

**Comment by MarcoFalke** [comment]
utACK ee34012c5bf590d17abc848b7ec2367816b63d14

**Comment by MarcoFalke** [comment]
Please squash your commits.

**Comment by practicalswift** [comment]
@MarcoFalke Squashed – please re-review :-)

**Comment by Empact** [comment]
utACK 620361f

**Comment by promag** [comment]
utACK 620361f.

Not all errors terminate with `.`, could be improved in a different PR?

**Pull request merged**
