### PR TITLE
[0.12] gitian: Set reference date to something more recent

### PR DESCRIPTION
**Pull request by maflcko**
This also helps in file views where binaries are sorted by time (be656283f98896df0bc8634d446b2873f9fed573)

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Test build: https://bitcoin.jonasschnelli.ch/pulls/7251/
Seems not to work.... maybe my gitian builder can't handle the new .yml files?

**Comment by MarcoFalke** [comment]
Sorry, mea culpa! You can't set `reference_datetime` to some future date.
```
checking whether build environment is sane... configure: error: newly created file is older than distributed files!
Check your system clock
```

**Comment by laanwj** [comment]
utACK

**Comment by laanwj** [comment]
Merged via eb2b745 (somehow github doesn't detect it?)

**Comment by MarcoFalke** [comment]
> @laanwj somehow github doesn't detect it

This was for 0.12 and master is already on 0.13, so GitHub did it right. It doesn't hurt to have it in master as well.

**Comment by MarcoFalke** [comment]
Thanks, merged as f6c8c1242b34eafdbee912544a071d2b58484ea8 into 0.12!

**Pull request closed without merging**
