### PR TITLE
net: Generate log entry when blocks messages are received unexpectedly

### PR DESCRIPTION
**Pull request by pstratem**
Currently these are incorrectly logged as an unknown command.

### CODE REVIEW

**Comment by gmaxwell** [comment]
utACK

**Comment by practicalswift** [comment]
Net effect of PR:

Logged before:

`Unknown command "{cmpctblock,blocktxn,headers,block}" from peer=N`

Logged after:

`Unexpected {cmpctblock,blocktxn,headers,block} message received from peer N`

No change in behaviour AFAICT.

utACK ef0019e054734a14214dfbce56611ce4db1688a5

**Comment by promag** [comment]
utACK ef0019e.

**Comment by MarcoFalke** [comment]
utACK ef0019e054734a14214dfbce56611ce4db1688a5

**Comment by naumenkogs** [comment]
utACK ef0019e

**Comment by laanwj** [comment]
Somehow we end up with code like this in the message handling every time. Let's try to pay attention to it in the future.
utACK otherwise

**Pull request merged**
