### PR TITLE
[Qt] simplify code for third party TX urls handling

### PR DESCRIPTION
**Pull request by Diapolo**
- prefer a foreach over a for loop and use a function from GUIUtil, to use
  code we already have

### CODE REVIEW

**Comment by Diapolo** [comment]
I wanted to add such a thing for the peers tab, perhaps usable for a whois service or something. I'd love to get a quick ACK so I can re-use the new code :).

**Comment by jonasschnelli** [comment]
I don't see a simplification of the code in this PR. It's just another way of doing this IMO.
This PR misses a benefit.

**Comment by Diapolo** [comment]
@jonasschnelli I think the foreach makes more sense, but also look at ``TransactionView::openThirdPartyTxUrl()``, which now uses a GUIUtil function.

**Comment by jgarzik** [comment]
Weak NAK - do not see much simplification (though I do have a preference for un-indenting code)

**Comment by Diapolo** [comment]
@jgarzik IMHO the code in ``TransactionView::openThirdPartyTxUrl`` is quite easier to read, yeah the rest is likely another version of how one could do it...

**Pull request closed without merging**
