### PR TITLE
contrib: Remove debian and rpm subfolder

### PR DESCRIPTION
**Pull request by maflcko**
The folders are now located here:

* https://github.com/bitcoin-core/packaging/tree/master/debian
* https://github.com/bitcoin-core/packaging/tree/master/rpm

Note that I kept the copyright file, so that it can be updated for our purposes in the commit that adds new files.

### CODE REVIEW

**Comment by practicalswift** [comment]
utACK fa0e1e2f630e6ca6cdfca64d8d92a7f0f85baa4d

1654 lines removed – very nice!

**Comment by kallewoof** [comment]
utACK fa0e1e2

Small diff for debian dir, but nothing significant.
Diff for rpm dir is clean.

**Comment by laanwj** [comment]
Thanks for picking this up, utACK fa0e1e2f630e6ca6cdfca64d8d92a7f0f85baa4d

**Comment by laanwj** [comment]
utACK fa0e1e2f630e6ca6cdfca64d8d92a7f0f85baa4d, thanks for picking this up

**Comment by fanquake** [comment]
utACK fa0e1e2

Only nit could be to drop:
```
Files: debian/*
Copyright: 2010-2011, Jonas Smedegaard <dr@jones.dk>
           2011, Matt Corallo <matt@bluematt.me>
License: GPL-2+
```

from [contrib/debian/copyright](https://github.com/bitcoin/bitcoin/blob/master/contrib/debian/copyright), as `copyright` is now the only file in `debian/*`.

**Comment by MarcoFalke** [comment]
@bugthebluematt

**Comment by TheBlueMatt** [comment]
Currently people tend to be pretty good about updating contrib/debian/copyright when things change, which is super nice cause I won't ever keep track of it. It may make sense to move it from contrib/debian/copyright to contrib/copyright or something like that.

**Comment by MarcoFalke** [comment]
It is still in the debian format, so I think it makes sense to keep in the debian folder. (Also I don't feel like updating all the internal and external links to the file)

**Comment by MarcoFalke** [comment]
If anyone feels strongly about that, it should be done in a separate commit to not invalidate the previous review.

**Pull request merged**
