### PR TITLE
Fix init README format to render correctly on github

### PR DESCRIPTION
**Pull request by jlopp**
Just need some preformatted tags to fix the github rendering.

### CODE REVIEW

**Comment by fanquake** [comment]
In future, please just force push changes to an existing PR rather than open a new one.

**Comment by jlopp** [comment]
Changes are the same as the other PR; I didn't know that you could change the base target via github UI.

**Comment by paveljanik** [comment]
Hmm, I do not understand why we have both `doc/init.md` and `contrib/init/README.md`. And why do they share the list of files in `contrib/init`? And why OS X's plist is not in the list in `doc/init.md`.

**Comment by laanwj** [comment]
Documentation in `doc/init.md` is for users.

The README.md in the directory is meant as a description of that directory, and why it exists. It could (but does not currently) point to the documentation.

**Comment by paveljanik** [comment]
But the change itself is OK ;-)

**Comment by fanquake** [comment]
trivial ACK b99fbad

**Pull request merged**
