### PR TITLE
net: Add -allowinbound config option

### PR DESCRIPTION
**Pull request by fjahr**
(This is just a very rough draft, I am only looking for conceptual feedback right now, so this is the bare minimum code to understand what it should do. I will add tests and fix docs when the conceptual review hurdle is cleared.)

This is an alternative approach to what was already attempted with #25690 and #24835. Please have a look there for more background information.

The `-allowinbound` option lets users explicitly mark networks as available for inbound connections, even if that network may be explicitly deactivated for outbound connections or if it is blocked for other reasons that are out of the user's control. The effect is that the `-externalip` addresses of that network may be announced and the `-getnetworkinfo` RPC will show these addresses. These several users seem to have run into these issues, see for example #25669.

### CODE REVIEW

**Comment by fjahr** [comment]
@mzumsande has suggested having separate `-onlynet` options for inbound and outbound. I think that's a valid option as well and if reviewers prefer that approach I can draft that one as well.

**Comment by vasild** [comment]
I think this can and should be resolved in a simpler way by removing `IsReachable()` from `AddLocal()` and `IsPeerAddrLocalGood()`.

The new option `-allowinbound` would be difficult to explain to users. By its name, I would guess that `-allowinbound=0` should do the same as `-listen=0`.

**Comment by Rspigler** [comment]
I like the `onlynet` inbound/outbound.  There is consistently confusion about the network settings and how they interact (and bugs found), and I think this would really clear things up.  Also, this would translate easily to GUI settings.

**Comment by vasild** [comment]
What would `-onlynet` inbound do? Is that not the same as omitting the network from `-bind=`?

**Comment by Rspigler** [comment]
Maybe I don't understand the purpose of the PR, but I thought it would make changes such as:
`-cjdnsreachable` -> `-allowinbound=cjdns`
`-onlynet=cjdns` -> `'-allowoutbound=cjdns`

**Comment by fjahr** [comment]
Closing this for now as I currently don't have time to continue with this. I hope I can revisit it in the future.

**Pull request closed without merging**
