### PR TITLE
0.18: rc3 backports

### PR DESCRIPTION
**Pull request by maflcko**
Remaining backports for rc3

### CODE REVIEW

**Comment by gmaxwell** [comment]
ACK

**Comment by MarcoFalke** [comment]
Would be nice if someone could double check the cherry-picks for correctly solving the conflicts

**Comment by promag** [comment]
ACK 95faffe, well done in ed0498af2827ccf033c9a7c4f46b82424e411083.

**Comment by laanwj** [comment]
utACK 95faffed264cf54a3b3041db2471c10f5011aabe

**Pull request merged**
