### PR TITLE
Update libsecp256k1 subtree to release 0.4.0

### PR DESCRIPTION
**Pull request by sipa**
We had previously pulled in a non-released commit along with #27479. The necessary changes have now been released in version 0.4.0, so update to that.

### CODE REVIEW

**Review by real-or-random — COMMENTED** [review]
Concept ACK

**Review by hebasto — APPROVED** [review]
ACK 0e0fc18c3cf8c0aa4cca85c4294416463f157870, having a zero diff with my local branch that updates the `secp256k1` subtree up to v0.4.0.

**Comment by fanquake** [comment]
cc @jonasnick

**Review by fanquake — APPROVED** [review]
ACK 0e0fc18c3cf8c0aa4cca85c4294416463f157870

**Pull request merged**
