### PR TITLE
Fix rounding bug in calculation of minimum change

### PR DESCRIPTION
**Pull request by morcos**
Thanks to @juscamarena for reporting this.

Please backport to 0.15. 

There was a potential rounding error where the fee for the change added to the fee for the original tx could be less than the fee for the tx including change.

This is fixed in the first commit.  The second commit adds one more snippet of information in the fee calculation report.  I actually realized that there is more information that would be nice to report, but we can add that post 0.15.

An open question is whether we should be returning failure if the test in line 2885 is hit or just resetting pick_new_inputs and continuing.  Originally I made it a failure to avoid any possible infinite loops.  But the case hit here is an example of where that logic possibly backfired.

### CODE REVIEW

**Review by gmaxwell — APPROVED** [review]
utACK  (reviewed this earlier based on the report; this is the fix I was expecting.)

**Review by instagibbs — APPROVED** [review]
utACK

**Review by ryanofsky — COMMENTED** [review]
utACK 6af49dddeaeec7f134e86d6f8cf839c55870b7ab.

Some code is shuffled around in the first commit, but only actual change in behavior seems to be computing minimum fee as `GetMinimumFee(nBytes + change_prototype_size + 2)` instead of `GetMinimumFee(nBytes) + GetMinimumFee(change_prototype_size)`.

Unclear whether it's the order of operations change or the +2 bytes which fixes the originally reported bug.

A test would be nice here but I think I say that every time I review CreateTransaction code (#9343, #10712)

**Comment by gmaxwell** [comment]
> Unclear whether it's the order of operations change or the +2 bytes which fixes the originally reported bug.

Both.  GetMinimumFee(nBytes) + GetMinimumFee(change_prototype_size)  has a rounding error compared to GetMinimumFee(nBytes + change_prototype_size)  and the +2 deals with the case that the output count becomes large enough to increase the compact size.

**Comment by juscamarena** [comment]
tACK, I no longer get the specific above issue. I ran into some other thing, that @morcos would probably better explain as he did as well.

**Comment by sdaftuar** [comment]
utACK

**Comment by kallewoof** [comment]
utACK 6af49dddeaeec7f134e86d6f8cf839c55870b7ab

**Review by gmaxwell — APPROVED** [review]
ACK.  (upgrading earlier utACK-- I left a node running for a few hours in regtest in a sending stress test and didn't manage to hit any issues.)

**Comment by MeshCollider** [comment]
utACK https://github.com/bitcoin/bitcoin/commit/a54c7b94f8825e9b52fec9066fe7c1d5b6f53482

**Comment by sipa** [comment]
utACK 6af49dddeaeec7f134e86d6f8cf839c55870b7ab

**Comment by MarcoFalke** [comment]
This was backported. Removing label

**Pull request merged**
