### PR TITLE
refactor: Move GetDifficulty out of `rpc/server.h`

### PR DESCRIPTION
**Pull request by laanwj**
`GetDifficulty` has no business in `rpcserver.h`. Define it in the interface header of the implementation unit `rpcblockchain` where it is defined.

Also modernize the signature to:

    double GetDifficulty(const CBlockIndex* blockindex = nullptr);

(remove `extern`, replace `NULL` with `nullptr`)

### CODE REVIEW

**Comment by jnewbery** [comment]
Tested ACK https://github.com/bitcoin/bitcoin/pull/10095/commits/e6dcfeec05d6527ab148550836937ff435e6449c

Can `RPCNotifyBlockChange()` (https://github.com/bitcoin/bitcoin/pull/10095/files#diff-a0fb7350bf105d107147e0d10f727f47L202) also be declared in rpc/blockchain.h ?

**Comment by jonasschnelli** [comment]
utACK e6dcfeec05d6527ab148550836937ff435e6449c

**Comment by laanwj** [comment]
@jnewbery Done

**Comment by laanwj** [comment]
I see rest.cpp also uses a few functions from this file:
```
extern void TxToJSON(const CTransaction& tx, const uint256 hashBlock, UniValue& entry);
extern UniValue blockToJSON(const CBlock& block, const CBlockIndex* blockindex, bool txDetails = false);
extern UniValue mempoolInfoToJSON();
extern UniValue mempoolToJSON(bool fVerbose = false);
extern void ScriptPubKeyToJSON(const CScript& scriptPubKey, UniValue& out, bool fIncludeHex);
extern UniValue blockheaderToJSON(const CBlockIndex* blockindex);
```
Going to add them to the header as well.

**Comment by jnewbery** [comment]
Looks good to me. Tested ACK c7e9aa7c1a92adba141958e5f86d267f34cc9508

**Review by dcousens — APPROVED** [review]

**Comment by jtimon** [comment]
ScriptPubKeyToJSON and TxToJSON are defined in https://github.com/bitcoin/bitcoin/blob/master/src/rpc/rawtransaction.cpp#L37 not rpc/blockchain.cpp. Either move the declaration or the definition for both to be in the same .h and .cpp

utACK c7e9aa7c1a92adba141958e5f86d267f34cc9508 modulo nit.

**Comment by laanwj** [comment]
@jtimon Good catch. I'll move them to their own header.

**Comment by jnewbery** [comment]
Or just refactor them out entirely since they're duplicate code: https://github.com/bitcoin/bitcoin/pull/8824

**Comment by laanwj** [comment]
Yes makes sense I'll just remove them from the header and ignore them for
this PR.

**Comment by laanwj** [comment]
Done, now those two lines remain in `rest.cpp`, will leave it to another pull to deal with them (I did remove the redundant `extern` though).

**Pull request merged**
