### PR TITLE
Upgrade depends/build system to use Qt 5.9.4

### LINKED ISSUE #10505: Upgrade depends/ build system to use Qt5.9
Qt5.9 has been [released](http://blog.qt.io/blog/2017/05/31/qt-5-9-released/).

Notable could be:

`
With Qt 5.9, we have had a strong focus on performance and stability. We’ve fixed a large number of bugs all across Qt[...]
`

`
Finally, we added support for compiling Qt in a size optimized mode (-Os on GCC), saving around 5-20% in binary size for the Qt libraries and your applications.
`

`
One major decision we have taken is to make Qt 5.9 another long-term supported (LTS) release. The previous LTS release, Qt 5.6, is starting to show it’s age, and many users have been asking for a more up to date version of Qt that they can use as a basis for long running projects.
`

### PR DESCRIPTION
**Pull request by thijstriemstra**
- update to Qt 5.9.4
- use https version of download.qt.io

fixes #10505

### CODE REVIEW

**Comment by thijstriemstra** [comment]
If osx build breaks here, see #11995.

**Comment by jonasschnelli** [comment]
I would be surprised if this works without changing the qt patches...

just started a depends (gtitian) build: https://bitcoin.jonasschnelli.ch/build/474

**Comment by thijstriemstra** [comment]
@jonasschnelli I see: https://github.com/thijstriemstra/bitcoin/tree/patch-1/depends/patches/qt

Any documentation/pointers why/how these were created? And when they can be dropped? Are there tests that fail without these? I guess we'll see..

**Comment by thijstriemstra** [comment]
> I would be surprised if this works without changing the qt patches...

Yeah, build failed with that, I'll take a look at updating the patches: https://travis-ci.org/bitcoin/bitcoin/jobs/335765496#L529

**Comment by fanquake** [comment]
Thanks for starting this, but the changes are likely to be more involved. Closing for now.

**Pull request closed without merging**
