### PR TITLE
[depends] Set OSX_MIN_VERSION to 10.8

### PR DESCRIPTION
**Pull request by fanquake**
0.13.0 is no longer compatible with OS X 10.7, see discussion in this [thread](https://github.com/bitcoin/bitcoin/issues/8577#issuecomment-255945996), and a plist change was made to prevent bitcoin-core running on 10.7 systems.

Earlier discussion mentioned that once we set the minimum target version to 10.8, we could remove some OS X related hacks, particularly in [macnotificationhandler.mm](https://github.com/bitcoin/bitcoin/pull/8184#issuecomment-224988684), so that could now be revisited.

### CODE REVIEW

**Comment by laanwj** [comment]
Concept ACK

**Comment by jonasschnelli** [comment]
ACK 617c96d5b3dd1b4665edff80913f473635ed0efb

**Comment by paveljanik** [comment]
Concept ACK

**Comment by theuni** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/9114/commits/617c96d5b3dd1b4665edff80913f473635ed0efb

**Comment by fanquake** [comment]
A bit more info about this. If you generate a depends prefix on OS X 10.12, and then plug that into configure, ./configure --prefix=/Users/michael/Github/bitcoin/depends/x86_64-apple-darwin16.1.0, when you compile it will fail with:

```
In file included from httpserver.cpp:22:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/future:1162:1: error: 'future<bool>' is unavailable: introduced in macOS 10.8
future<_Rp>::~future()

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/future:1896:1: error: '__packaged_task_function<bool (event_base *, evhttp *)>' is unavailable: introduced in macOS 10.8
__packaged_task_function<_Rp(_ArgTypes...)>::__packaged_task_function(_Fp&& __f)

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/future:632:1: error: '__assoc_state<bool>' is unavailable: introduced in macOS 10.8
__assoc_state<_Rp>::__on_zero_shared() _NOEXCEPT

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/future:1455:1: error: 'promise<bool>' is unavailable: introduced in macOS 10.8
promise<_Rp>::get_future()

18 errors generated.
```

After this change it compiles.

**Pull request merged**
