### PR TITLE
Make sure LC_ALL=C is set in all shell scripts

### PR DESCRIPTION
**Pull request by practicalswift**
~~Make sure `LC_ALL=C` is set when using `grep` range expressions.~~

Make sure `LC_ALL=C` is set in all shell scripts.

From the `grep(1)` documentation:

> Within a bracket expression, a range expression consists of two characters separated by a hyphen. It matches any single character that sorts between the two characters, inclusive, using the locale's collating sequence and character set. For example, in the default C locale, `[a-d]` is equivalent to `[abcd]`. Many  locales sort characters in dictionary order, and in these locales `[a-d]` is typically not equivalent to `[abcd]`; it might be equivalent to `[aBbCcDd]`, for example. To obtain the traditional interpretation of bracket expressions, you can use the C locale by setting the `LC_ALL` environment variable to the value C.

Context: [Locale issue found when reviewing #13450](https://github.com/bitcoin/bitcoin/pull/13450/files#r194877736)

### CODE REVIEW

**Comment by laanwj** [comment]
Maybe export LC_ALL=C at the beginning of these scripts, to rule out unexpected locale dependency in other commands too.

**Comment by practicalswift** [comment]
@laanwj Good idea. Now enforcing `export LC_ALL=C`. Please re-review :-)

**Comment by practicalswift** [comment]
@MarcoFalke Oh, that's weird! I'm unable to reproduce locally. Will try to find time to investigate soon!

**Comment by MarcoFalke** [comment]
Presumably caused by the non-ascii char in https://github.com/practicalswift/bitcoin/blob/0f556d2e6d19e5fd86712bb5f4b0506924740ae3/test/lint/lint-python.sh#L65

**Comment by laanwj** [comment]
Seems like an upstream bug then, with the version installed by Travis, if you can't reproduce it locally?

**Comment by ken2812221** [comment]
Looks like travis has already installed shellcheck v0.4.6, but we reinstall v0.3.3 from ubuntu repo.

**Comment by practicalswift** [comment]
Worked around the `shellcheck` issue by adding an "opt in to locale dependence" mechanism which is now in used for `test/lint/lint-shell.sh`.

Please re-review :-)

**Comment by laanwj** [comment]
Still segfaults?!?

**Comment by practicalswift** [comment]
@laanwj `LC_ALL=C` was exported by `test/lint/lint-all.sh` and thus inherited by `test/lint/lint-shell.sh`. Now "opting in to locale dependence" also in `lint-all.sh` to allow for the linting scripts to opt in/out of locale dependences themselves :-)

**Comment by laanwj** [comment]
Good. We should not forget to remove this workaround when we'll be able to use a newer shellcheck, it's a bit yucky, but checking all scripts but two is much better than nothing.
utACK 47776a958b08382d76d69b5df7beed807af168b3

**Comment by ken2812221** [comment]
utACK 47776a958b08382d76d69b5df7beed807af168b3

**Comment by practicalswift** [comment]
@MarcoFalke Oh, thanks! Fixed by #13494.

**Pull request merged**
