### PR TITLE
travis: Compile once on trusty

### PR DESCRIPTION
**Pull request by maflcko**
To avoid accidentally regressing again on #15172, we should compile at least once with gcc4.8 (the minimum required version)

Note that this uses the trusty image, which will be removed in a few months from the docker hub, so in the future it had to be switched to the centos7 (or similar) image, which should come with gcc4.8 as well.

### CODE REVIEW

**Comment by Empact** [comment]
See also #14998, which I haven't gotten green

**Comment by MarcoFalke** [comment]
Jup, thanks for working on this. Though, it seems your code-changes haven't seen much review, so I try to make a minimal test-only addition to get this in asap.

**Comment by Empact** [comment]
utACK 
https://github.com/bitcoin/bitcoin/pull/15276/commits/fa5ce3f10ea98e5cd6bdd829b5b7b8fd2736d286 could squash

**Comment by practicalswift** [comment]
utACK fa5ce3f10ea98e5cd6bdd829b5b7b8fd2736d286

**Pull request merged**
