### PR TITLE
0.19: Add txids with non-standard inputs to reject filter

### PR DESCRIPTION
**Pull request by sdaftuar**
Backport of #19620 to 0.19.

### CODE REVIEW

**Comment by laanwj** [comment]
As for the appveyor error I'm not sure I think you either need fae0e93836c0aa96b9274c69651b02cbf6352dc1 and/or faf5e256c50a3fe5f946daeab3fe68a894caad95.

**Comment by sdaftuar** [comment]
Just tried to backport #19444 but not sure I did it right...

**Comment by jnewbery** [comment]
We should merge #19025 rather than include appveyor changes in this PR.

**Comment by jnewbery** [comment]
utACK the last two commits in 568007cffe0c3998d5b4b20e16d4ae6fb779ed43

**Comment by instagibbs** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/19681/commits/52c3bec1bad4fc602a3911b44de48c6b0dbdfd25

**Comment by jnewbery** [comment]
utACK 52c3bec1ba

**Review by jonasschnelli — APPROVED** [review]
utACK 52c3bec1bad4fc602a3911b44de48c6b0dbdfd25
Compared with #19620

**Pull request merged**
