### PR TITLE
Backport bugfixes to 0.10 (2015-10-22 / f2c869a)

### PR DESCRIPTION
**Pull request by luke-jr**
Companion to #6825

### CODE REVIEW

**Comment by laanwj** [comment]
Has varous travis issues (missing chainParams, RPC failures)

**Comment by MarcoFalke** [comment]
Had a look yesterday, I think travis fails due to `Bugfix: Allow mining on top of old tip blocks for testnet (fixes testnet-in-a-box use case)`. Do we need this in `.10`?

**Comment by gmaxwell** [comment]
ACK.

**Comment by luke-jr** [comment]
@laanwj @MarcoFalke Travis is okay with this now. The testnet bugfix just needed chainParams (which had already been in the function for 0.11/master before the fix).

**Comment by laanwj** [comment]
@luke-jr Next time you do a backport pull like this, can you please add the original pull numbers of what you're backporting?

What I usually do is add a header to the commits, to mark where they came from:
```
Github-Pull: #1234
```
This allows my autogenerate-changelog scripting to work and provide useful pull links for the changes.

**Comment by luke-jr** [comment]
Is there an easy way to do that? I'll try to remember, but if it's a while, I may need reminding.

**Comment by laanwj** [comment]
Should probably document that somewhere.

I don't have scripting to automate adding the metadata. What I usually do is cherry-pick -x, then `git commit --amend` rewrite the "Cherry-picked from" text into `Rebased-From: `, and manually add in the pull #.

**Pull request merged**
