### PR TITLE
test: Add MaybeCompactWalletDB tsan suppression (take 2)

### PR DESCRIPTION
**Pull request by maflcko**
Previous attempt: #20218

### CODE REVIEW

**Comment by laanwj** [comment]
Do we have any idea why this is needed? Why does this particular function raise a false positive?

**Comment by MarcoFalke** [comment]
I have no clue. If someone knows why or even how to track this down (which is difficult because it happens intermittently), please let me know.

**Comment by MarcoFalke** [comment]
Though, having ci fail on known issues whose fix is unknown only increases frustration having to reset the builds.

**Comment by laanwj** [comment]
Yeah. What I'm a little bit worried about is that it might be an actual problem and not a false positive, in which case it would be a really bad idea to silence it.
But I don't know how to debug this either.

**Pull request closed without merging**
