### PR TITLE
p2p: rpc: add `tx_reconciliation` to `getpeerinfo`

### PR DESCRIPTION
**Pull request by brunoerg**
This PR adds a new field in `getpeerinfo` RPC to know whether a peer is registered for transaction reconciliation (we register it when receiving a `SENDTXRCNCL` msg).  

- The field `tx_reconciliation` is optional for in case you do not support tx reconciliation.
- With this field, we can improve `p2p_sendtxrcncl` tests by checking whether a peer is registered for transaction reconciliation instead of simply rely on logs message.
- d660df07d756ba5e06b74e4b51a7287620ae306b - Just remove unnecessary `disconnect_p2ps` (we're calling it right before restarting the node) calls in `p2p_sendtxrcncl`.

### CODE REVIEW

**Comment by brunoerg** [comment]
cc: @sr-gi per our convo.

**Comment by sr-gi** [comment]
Concept ACK

**Review by mzumsande — COMMENTED** [review]
This looks similar to #26602 / #27797 - I don't think any Erlay PR has been merged since then, so the reasoning from back then should still apply?

**Comment by sr-gi** [comment]
> This looks similar to #26602 / #27797 - I don't think any Erlay PR has been merged since then, so the reasoning from back then should still apply?

I was unaware of this. I'm happy to cherry-pick these two commits into one of the upcoming Erlay PRs, especially once the network messaging bits have been included.

**Comment by brunoerg** [comment]
> Sounds good to me. I still think that this (and anything else that is user-facing) should make it into master/releases as soon as Erlay is functional (not necessarily activated by default) but not before.

Sounds good to me as well. Closing this for now.

**Pull request closed without merging**
