### PR TITLE
[0.17] doc: merge upstream release-notes from bitcoin-core/bitcoin-devwiki

### PR DESCRIPTION
**Pull request by fanquake**
sipa [suggested in IRC](https://botbot.me/freenode/bitcoin-core-dev/2018-09-06/?msg=104094793&page=1) that now would be a good time to merge the release notes from the [bitcoin-devwiki](https://github.com/bitcoin-core/bitcoin-devwiki).

### CODE REVIEW

**Comment by laanwj** [comment]
I think it's best to do this just before the -final is tagged, not sooner.

**Comment by MarcoFalke** [comment]
Would be nice to add the list of authors and pull requests first. I'd like to review these before final

**Comment by fanquake** [comment]
This has been updated with the most recent changes from the wiki, which includes PRs and authors.

**Comment by MarcoFalke** [comment]
ACK

**Comment by fanquake** [comment]
Updated with the latest changes.

**Comment by MarcoFalke** [comment]
Needs one more update?

**Pull request merged**
