### PR TITLE
CBlockLocator: performance-move-const-arg Clang tidy fixup

### PR DESCRIPTION
**Pull request by jonatack**
Fix Clang-tidy CI errors on master.  See https://cirrus-ci.com/task/4806752200818688?logs=ci#L4696 for an example.

### CODE REVIEW

**Comment by jonatack** [comment]
The Clang tidy CI passed, so opening this up for review.

**Comment by jonatack** [comment]
> The change on line 52 makes sense, but the one on 316 seems like a step backwards?

Hm, RVO wouldn't be affected by the move of an argument (rather than of the object itself)?

Repushed without that change to see if the tidy job remains appeased.

**Comment by jonatack** [comment]
```
src/headerssync.cpp:316:26: error: passing result of std::move() as a const reference argument; no move will actually happen [performance-move-const-arg,-warnings-as-errors]
    return CBlockLocator{std::move(locator)};
                         ^~~~~~~~~~       ~
```

**Comment by jonatack** [comment]
> @jonatack Oh! The issue is just that `CBlockLocator` has no constructor that accepts an rvalue `uint256`. The `std::move` there has no effect, but the correct solution is adding an rvalue-accepting constructor, not getting rid of the `std::move`.

Ah interesting! Learning.

**Comment by vasild** [comment]
ACK af7a40c1830c16cb0005a4fb121f631e01be9f80
(the previous push with the two changes)

Both warnings are legit because no move will happen in either case.

But consider this, like @sipa suggested above, would avoid copying:

<details>
<summary>diff</summary>

```diff
diff --git i/src/chain.cpp w/src/chain.cpp
index 19c35b5012..66a0830394 100644
--- i/src/chain.cpp
+++ w/src/chain.cpp
@@ -46,13 +46,13 @@ std::vector<uint256> LocatorEntries(const CBlockIndex* index)
     }
     return have;
 }

 CBlockLocator GetLocator(const CBlockIndex* index)
 {
-    return CBlockLocator{std::move(LocatorEntries(index))};
+    return CBlockLocator{LocatorEntries(index)};
 }

 CBlockLocator CChain::GetLocator() const
 {
     return ::GetLocator(Tip());
 }
diff --git i/src/primitives/block.h w/src/primitives/block.h
index 76aba6c899..8c51d280b8 100644
--- i/src/primitives/block.h
+++ w/src/primitives/block.h
@@ -120,13 +120,13 @@ public:
 struct CBlockLocator
 {
     std::vector<uint256> vHave;

     CBlockLocator() {}

-    explicit CBlockLocator(const std::vector<uint256>& vHaveIn) : vHave(vHaveIn) {}
+    explicit CBlockLocator(std::vector<uint256>&& vHaveIn) : vHave(std::move(vHaveIn)) {}

     SERIALIZE_METHODS(CBlockLocator, obj)
     {
         int nVersion = s.GetVersion();
         if (!(s.GetType() & SER_GETHASH))
             READWRITE(nVersion);
```
</details>

**Comment by MarcoFalke** [comment]
Using `&&` would *force* all call sites to use `std::move`. Thus, it makes it impossible to use on `const&`.

You can simply change the constructor to allow anything:

```
explicit CBlockLocator(std::vector<uint256> have) : vHave{std::move(have)} {}

**Comment by MarcoFalke** [comment]
> an rvalue argument is still more efficient than a by-value one

Correct. Personally, I think it is fine to have an overhead equivalent to constructing an empty vector. When there is a new call-site with a const reference in the future, the constructor will need to be changed to that anyway, or a new `const&` constructor be added (alongside the `&&` one), which is what the stdlib is usually doing.

But anything should be fine here.

review ACK 6b24dfe24d2ed50ea0b06ce1919db3dc0e871a03

**Review by vasild — APPROVED** [review]
ACK 6b24dfe24d2ed50ea0b06ce1919db3dc0e871a03

**Comment by jonatack** [comment]
> With a by-value argument there is construct+move+move, with an rval argument, there is construct+move:
> rv.cc
> 
> ```
> output with `R5 r5` arg:
> 
> ```
> R5::R5() this=0x7fffffffe5e8 x=2, y=3.4
> R5::R5(R5&&) this=0x7fffffffe5d8 other=0x7fffffffe5e8 x=2, y=3.4
> R5::R5(R5&&) this=0x7fffffffe610 other=0x7fffffffe5d8 x=2, y=3.4
> R5::~R5() this=0x7fffffffe5d8 x=0, y=0
> R5::~R5() this=0x7fffffffe5e8 x=0, y=0
> R5::~R5() this=0x7fffffffe610 x=2, y=3.4
> ```
> 
> output with `R5&& r5` arg:
> 
> ```
> R5::R5() this=0x7fffffffe5e8 x=2, y=3.4
> R5::R5(R5&&) this=0x7fffffffe610 other=0x7fffffffe5e8 x=2, y=3.4
> R5::~R5() this=0x7fffffffe5e8 x=0, y=0
> R5::~R5() this=0x7fffffffe610 x=2, y=3.4
> ```

@vasild nice! Reproduced this locally for fun.

```bash
₿ g++ by-val-versus-rval.cpp && ./a.out 
R5::R5() this=0x7ffe5de81ea0 x=2, y=3.4
R5::R5(R5&&) this=0x7ffe5de81eb0 other=0x7ffe5de81ea0 x=2, y=3.4
R5::R5(R5&&) this=0x7ffe5de81ef0 other=0x7ffe5de81eb0 x=2, y=3.4
R5::~R5() this=0x7ffe5de81eb0 x=0, y=0
R5::~R5() this=0x7ffe5de81ea0 x=0, y=0
R5::~R5() this=0x7ffe5de81ef0 x=2, y=3.4

₿ g++ by-val-versus-rval.cpp && ./a.out 
R5::R5() this=0x7ffea6450b90 x=2, y=3.4
R5::R5(R5&&) this=0x7ffea6450bd0 other=0x7ffea6450b90 x=2, y=3.4
R5::~R5() this=0x7ffea6450b90 x=0, y=0
R5::~R5() this=0x7ffea6450bd0 x=2, y=3.4 
```

**Pull request merged**
