### PR TITLE
updated

### PR DESCRIPTION
**Pull request by tarunraheja84**
Steps to compile Bitcoin Core in Windows (most used OS) inserted.

### CODE REVIEW

**Comment by pinheadmz** [comment]
@tarunraheja84 see https://github.com/bitcoin/bitcoin/blob/master/doc/build-windows.md

**Comment by tarunraheja84** [comment]
@pinheadmz Can you please share links for Bitcoin Core IRC and StackExchange.  I will be grateful.

**Comment by pinheadmz** [comment]
https://bitcoin.stackexchange.com/questions

**Comment by tarunraheja84** [comment]
Thankyou very much

**Pull request closed without merging**
