### PR TITLE
Bugfix: Do not define HAVE_O_CLOEXEC for LevelDB when O_CLOEXEC is not available

### PR DESCRIPTION
**Pull request by luke-jr**
LevelDB uses `#ifdef` for HAVE_O_CLOEXEC, so if not available, it needs to be not-defined

### CODE REVIEW

**Comment by hebasto** [comment]
Why not https://github.com/google/leveldb/pull/1028?

**Comment by luke-jr** [comment]
That's ideal, but not merged yet, and even if it's done in time for 24.x, we should still fix it here now for backports.

**Comment by hebasto** [comment]
> That's ideal, but not merged yet...

Maybe pick that commit into our subtree?

**Comment by laanwj** [comment]
I'd also prefer cherry-picking the leveldb change instead.

**Comment by fanquake** [comment]
> I'd also prefer cherry-picking the leveldb change instead.

Agree with this as well.

**Comment by hebasto** [comment]
> > I'd also prefer cherry-picking the leveldb change instead.
> 
> Agree with this as well.

https://github.com/bitcoin-core/leveldb-subtree/pull/32

**Comment by fanquake** [comment]
> That's ideal, but not merged yet,

Given https://github.com/google/leveldb/commit/7b650f85de0b785596cc145a3dd28a54cb73bb50, I'd say the likelyhood of it being merged upstream is very low, so it being merged upstream shouldn't be a blocker for cherry-picking into our subtree and pulling it down here if we want.

**Comment by fanquake** [comment]
https://github.com/bitcoin-core/leveldb-subtree/pull/32 has been merged into our subtree.

**Comment by fanquake** [comment]
Opened a subtree update that pulls in https://github.com/bitcoin-core/leveldb-subtree/pull/32 in #25739.

**Comment by luke-jr** [comment]
Closing in favour of #25739

**Pull request closed without merging**
