### PR TITLE
[QT] cleanup icons

### PR DESCRIPTION
**Pull request by maflcko**
- Cleanup SVG code
- Unify design ("Typicons" seems to have round edges)
- Replace wifi icon with something new

### CODE REVIEW

**Comment by MarcoFalke** [comment]
@jonasschnelli Could you check if ```clock5.png``` displays correctly?

**Comment by jonasschnelli** [comment]
Nice! Thanks.
Will test and post some screenshots soon.

**Comment by luke-jr** [comment]
Where did the "something new" network icon come from? What is its license? This needs to be updated in assets-attribution.md, and must be MIT or similar licensing terms.

**Comment by jonasschnelli** [comment]
In general it looks very good.
The new net icons (instead of the "wifi" like icon) has a bit thin lines... 

Please update the `assets-attribution.md`.
At least add yourself to the list of designers (https://github.com/MarcoFalke/bitcoin/blob/MarcoFalke-2015-icon-cleanup/doc/assets-attribution.md#jonas-schnelli) so it would be clear that you are publishing under the MIT license.

OSX:
bildschirmfoto 2015-08-03 um 10 39 56
bildschirmfoto 2015-08-03 um 10 37 27
bildschirmfoto 2015-08-03 um 10 40 17
bildschirmfoto 2015-08-03 um 10 40 13

LINUX:
bildschirmfoto 2015-08-03 um 10 58 08
bildschirmfoto 2015-08-03 um 10 57 59
bildschirmfoto 2015-08-03 um 10 57 55
bildschirmfoto 2015-08-03 um 10 57 33

**Comment by Diapolo** [comment]
I'm not a friend of the new connection symbols, that is a NACK on changing it that way.

**Comment by jonasschnelli** [comment]
@Diapolo: could you give us any objective reasons for your dislike? The current icon is mostly used for WiFi connections and therefore i think changing it makes sense. The new icons would more reflect a p2p "signal strength".

**Comment by MarcoFalke** [comment]
I will try to make the wires thicker and make another commit of the new p2p-connection symbol, so it is easier not to merge it.

**Comment by Diapolo** [comment]
@jonasschnelli It reminds me of an USB-like symbol, a USB hub or something. Perhaps we should only use a color indicator red, orange, yellow and green (only if incoming connections are allowed).

**Comment by laanwj** [comment]
I like the new connection icon. Inventive.

**Comment by MarcoFalke** [comment]
I did the split into two commits, so we have:

* First commit:

screenshot from 2015-08-04 12-29-13

* Second commit (thicker wires):

screenshot from 2015-08-04 16-14-19

**Comment by jonasschnelli** [comment]
Tested ACK.
Bins: https://builds.jonasschnelli.ch/pulls/6505/

**Comment by laanwj** [comment]
Looks great. ACK.
schermafdruk van 2015-08-05 11 49 38

**Comment by fanquake** [comment]
Post merge ACK. I did have some screens to post but will leave it now.

**Pull request merged**
