### PR TITLE
Scripts and tools: Obsolete #!/bin/bash shebang

### PR DESCRIPTION
**Pull request by DesWurstes**
> `#!/bin/bash` assumes it is always installed to `/bin/` which can cause issues
> `#!/usr/bin/env bash` searches the user's `PATH` to find the `bash` binary

Details: https://github.com/dylanaraps/pure-bash-bible#obsolete-syntax

I'm open to comments: Should I also fix `#!/bin/sh`?

### CODE REVIEW

**Review by ken2812221 — APPROVED** [review]
utACK 000000035b20402dea3e8168165cd4eefdc97539

**Comment by luke-jr** [comment]
Did you bruteforce that hash? What did you use as the nonce?

**Comment by MarcoFalke** [comment]
@luke-jr 

```
git log --format=fuller 0000000 -1
commit 000000035b20402dea3e8168165cd4eefdc97539
Author:     DesWurstes <DesWurstes@users.noreply.github.com>
AuthorDate: Wed Jun 20 12:54:54 2018 +0300
Commit:     DesWurstes <DesWurstes@users.noreply.github.com>
CommitDate: Wed Jun 20 11:12:41 2018 +0300

    Obsolete #!/bin/bash shebang

**Comment by DesWurstes** [comment]
Timestamp, it is two hours earlier than the actual commit time.

**Comment by practicalswift** [comment]
utACK 000000035b20402dea3e8168165cd4eefdc97539

Nice hash!

**Comment by Empact** [comment]
utACK 0000000

**Comment by laanwj** [comment]
Agree that this is better. BSD ports tend to install `bash` to `/usr/local`, for example.

> I'm open to comments: Should I also fix #!/bin/sh?

I'd say, no. `/bin/sh` is by definition the system shell. Use of the system shell has its own issues (like the script having to be compatible with 80's shell dialect, the lowest common denominator of all shells), but the location is not one of them.

**Pull request merged**
