### PR TITLE
build: Drop macports support

### PR DESCRIPTION
**Pull request by Empact**
It's unmaintained, according to @theuni.
https://github.com/bitcoin/bitcoin/pull/14920/files#r246964938

Alternative is to put it under CI. I don't have a strong opinion on this, opened for separate consideration.

### CODE REVIEW

**Comment by laanwj** [comment]
Concept ACK.
If it's unmaintained it should be removed, simple as that.
Unless someone cares enough and promises to pick this up.

**Comment by fanquake** [comment]
Concept ACK. Doing this has been mentioned many times. Macports instructions were dropped from the macOS build readme in #4939 (>4 years ago, discussion in #4917), and I don't think anyone has complained/asked to have them re-added.

**Comment by practicalswift** [comment]
Concept ACK

**Comment by promag** [comment]
Concept ACK and change LGTM.

**Comment by laanwj** [comment]
"AppVeyor was unable to build non-mergeable pull request " huh

**Comment by Empact** [comment]
> "AppVeyor was unable to build non-mergeable pull request " huh

Rebasing cleared this up.

**Comment by jonasschnelli** [comment]
Tested ACK 4e81438f6556d059923f07409264c11c41cc4a0b

**Comment by Empact** [comment]
This also removes the last remaining references to qt4 :P

**Comment by IlyasRidhuan** [comment]
utAck

**Comment by fanquake** [comment]
utACK 4e81438

**Comment by theuni** [comment]
utACK 4e81438f6556d059923f07409264c11c41cc4a0b. Thanks!

**Comment by rex4539** [comment]
For the poor soul that may come here in the future, trying to compile using MacPorts.

Add the following to your Bash `.profile`:
```
export BDB_CFLAGS=/opt/local/include/db48/
export CPPFLAGS="$CPPFLAGS -isystem /opt/local/include"
export LIBS="$LIBS -L/opt/local/lib"
```

Restart your shell.

Bitcoin Core will now compile.

**Pull request merged**
