### PR TITLE
Bring historical release notes up to date

### PR DESCRIPTION
**Pull request by Michagogo**
[skip ci]

### CODE REVIEW

**Comment by fanquake** [comment]
Not sure it makes sense adding the 0.11 release notes to the 0.10 branch ?

**Comment by jonasschnelli** [comment]
Agree with @fanquake: 0.11x release notes make not much sense in the 0.10 branch.

**Comment by laanwj** [comment]
Agreed, let's not do this.

**Comment by Michagogo** [comment]
The 0.10.x should be included in 0.10. Releases should include the notes
for their direct ancestors.

**Pull request closed without merging**
