### PR TITLE
doc: Fix typos in endif header comments

### PR DESCRIPTION
**Pull request by maflcko**
Some of the endif header comments have typos in them (ZMRRPC_H), or are from a different file, or are inconsistently formatted.

Fix all and adjust the linter.

### CODE REVIEW

**Comment by katesalazar** [comment]
Concept ACK.

**Review by hebasto — APPROVED** [review]
ACK fa44237d76b66b6664870c3927b65a0ef89022e4

I've reviewed changes in `test/lint/lint-include-guards.sh`, and verified that all other changes are actually forced by the updated linter.

**Review by shaavan — APPROVED** [review]
ACK fa44237d76b66b6664870c3927b65a0ef89022e4

The updated lint-include-guard test makes sure that all three keywords: “ifndef”, “define”, “endif //”, must be present for each header file. This also ensures there are no redundant inundation or whitespaces on the lines in which they are present.

I have tested that the updated test is working correctly in following cases:

1. In case extra space is added anywhere on the line (beginning or in the middle)
2. Space is removed between “//” and includes guard name.
3. “//” is changed.

However, it cannot detect if an extra line is added above or below these keywords. 
```diff
+
 #endif // BITCOIN_LIBSECP256K1_CONFIG_H
```
Though that’s not the case, this test is designed to handle, so it is not an issue.

**Comment by MarcoFalke** [comment]
> Though that’s not the case, this test is designed to handle, so it is not an issue.

Correct

**Pull request merged**
