### PR TITLE
[qa] Switch to py3

### PR DESCRIPTION
**Pull request by maflcko**
Blockers:
- [x] #7893 (figure out fix for bctest.py on precise) **OR** #7920 (bump to trusty)

### CODE REVIEW

**Comment by MarcoFalke** [comment]
extended tests fail; I couldn't yet figure out why. Other than that, this seems ready.


```
$ ret=0; while [ $ret -eq 0 ]; do ./qa/pull-tester/rpc-tests.py smartfees; ret=$?;done
Running 2nd level testscript smartfees.py ...
Initializing test directory /tmp/test7p02nuxm
This test is time consuming, please be patient
Splitting inputs to small size so we can generate low priority tx's
JSONRPC error: 16: mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element)
  File "/home/marco/workspace/bitcoin/qa/rpc-tests/test_framework/test_framework.py", line 133, in main
    self.setup_network()
  File "/home/marco/workspace/bitcoin/qa/rpc-tests/smartfees.py", line 177, in setup_network
    split_inputs(self.nodes[0], self.txouts, self.txouts2)
  File "/home/marco/workspace/bitcoin/qa/rpc-tests/smartfees.py", line 94, in split_inputs
    txid = from_node.sendrawtransaction(completetx, True)

**Comment by laanwj** [comment]
Tested ACK https://github.com/bitcoin/bitcoin/pull/7814/commits/e5dac453d1343528760fc5a89c5c02f9368daa79

**Comment by MarcoFalke** [comment]
Rebased

**Comment by MarcoFalke** [comment]
I've been testing this on fedora linux. Would be good to know if this also works on osx and win. (If you want to test this, there is no need to compile anything. Just fetch the commit and run it through the test suite.)

**Comment by fanquake** [comment]
Run through the short test suite on OSX 10.11, all tests passed. Can we add a line for the zeromq osx dependancy?

`pip3 install pyzmq` was what I needed to get it working.

**Comment by laanwj** [comment]
I've tested both the extended and short test suite on Ubuntu 14.04. This passes.
Going to test on Debian 8.4 and Ubuntu 16.04 next.

**Comment by fanquake** [comment]
Running through the extended test suite.
```
Running testscript signmessages.py ...
Initializing test directory /var/folders/rb/jqqd25w926s5429rf58_zsv00000gn/T/testim6xak
JSONRPC error: Method not found
  File "/Users/michael/Github/bitcoin/qa/rpc-tests/test_framework/test_framework.py", line 135, in main
    self.run_test()
  File "/Users/michael/github/bitcoin/qa/rpc-tests/signmessages.py", line 27, in run_test
    signature = self.nodes[0].signmessagewithprivkey(privKey, message)
  File "/Users/michael/Github/bitcoin/qa/rpc-tests/test_framework/coverage.py", line 49, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "/Users/michael/Github/bitcoin/qa/rpc-tests/test_framework/authproxy.py", line 139, in __call__
    raise JSONRPCException(response['error'])
Stopping nodes
Cleaning up
Failed
Traceback (most recent call last):
  File "qa/pull-tester/rpc-tests.py", line 275, in <module>
    runtests()
  File "qa/pull-tester/rpc-tests.py", line 178, in runtests
    rpcTestDir + testScripts[i] + flags, shell=True)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/Users/michael/github/bitcoin/qa/rpc-tests/signmessages.py --srcdir /Users/michael/github/bitcoin/src  ' returned non-zero exit status 1
```

Looks like `signmessages.py` has been missed, as it also still has `env/ python2`

**Comment by laanwj** [comment]
Ah yes - merging a pull that adds a new test wasn't a very good idea. Now this probably needs to be updated to include the new test, otherwise it can't be merged without breaking travis.

**Comment by MarcoFalke** [comment]
>JSONRPC error: Method not found

Na, you just need to compile the new signmessage code.

Rebased nonetheless.

**Comment by MarcoFalke** [comment]
Interesting that this makes the test slower, though:

py3:
```
$ ./qa/pull-tester/rpc-tests.py signmessages
Running testscript signmessages.py ...
Initializing test directory /tmp/testgxs02bu5
Stopping nodes
Cleaning up
Tests successful
Duration: 2 s
```

py2:
```
$ ./qa/pull-tester/rpc-tests.py signmessages
Running testscript signmessages.py ...
Initializing test directory /tmp/testXaAvpQ
Stopping nodes
Cleaning up
Tests successful
Duration: 0 s
```

[wait_bitcoinds()](https://github.com/MarcoFalke/bitcoin/blob/fa389d4edc367073e2ccc6d1f0790c4b72ba17f2/qa/rpc-tests/test_framework/util.py#L326) takes 2 seconds now.

**Comment by laanwj** [comment]
Strange.

**Comment by MarcoFalke** [comment]
Indeed interesting; Other test still run fast with py3:

```
$ qa/pull-tester/rpc-tests.py disablewallet
Running testscript disablewallet.py ...
Initializing test directory /tmp/test_zgnh7e3
Stopping nodes
Cleaning up
Tests successful
Duration: 0 s

```

But let's not worry about it too much, this will be compensated by #7972, hopefully.

**Comment by laanwj** [comment]
Right, well if it is two seconds on one test I don't see why it would need to be a blocker.

**Pull request merged**
