### PR TITLE
rest: Return error when header count is not integral

### PR DESCRIPTION
**Pull request by maflcko**
Seems odd to interpret a hash (or any other string) as integer when it contains more than the digits 0 to 9.

### CODE REVIEW

**Review by jonatack — COMMENTED** [review]
ACK fa21fd44e24bb9e4e19e3e8bc4f0de8df34d9535

a couple ideas, feel free to ignore
```diff
diff --git a/src/rest.cpp b/src/rest.cpp
index d2fc35e818..0c2cb96622 100644
--- a/src/rest.cpp
+++ b/src/rest.cpp
@@ -194,7 +194,7 @@ static bool rest_headers(const std::any& context,
         return RESTERR(req, HTTP_BAD_REQUEST, "Header count out of range: " + path[0]);
     }
 
-    std::string hashStr = path[1];
+    const std::string& hashStr = path[1];
     uint256 hash;
     if (!ParseHashStr(hashStr, hash))
         return RESTERR(req, HTTP_BAD_REQUEST, "Invalid hash: " + hashStr);
diff --git a/src/test/util_tests.cpp b/src/test/util_tests.cpp
index b5088d3c33..bcff4b37a8 100644
--- a/src/test/util_tests.cpp
+++ b/src/test/util_tests.cpp
@@ -1527,6 +1527,7 @@ BOOST_AUTO_TEST_CASE(test_ToIntegral)
     BOOST_CHECK_EQUAL(ToIntegral<int32_t>("-1234").value(), -1'234);
     BOOST_CHECK_EQUAL(ToIntegral<int32_t>("-1").value(), -1);
 
+    RunToIntegralTests<size_t>();
     RunToIntegralTests<uint64_t>();
     RunToIntegralTests<int64_t>();
     RunToIntegralTests<uint32_t>();
```

**Review by shaavan — COMMENTED** [review]
Concept ACK

I agree with the concept of PR. It shouldn’t be possible for a non-integer header count to be valid, and this PR makes sure that it will always cause an error.
The tests are correct, too, and appropriately check the added code.

I have some suggestions and doubts regarding this PR, though. And I would kindly appreciate it if you would help me clear them out. Thank You.

**Comment by practicalswift** [comment]
cr ACK fa8d49289479b8eda7ba7530515c414d1cd566a3

**Review by promag — COMMENTED** [review]
Code review ACK fa8d49289479b8eda7ba7530515c414d1cd566a3.

Only suggestion is to have a different error.

**Review by shaavan — APPROVED** [review]
Code Review ACK fa8d49289479b8eda7ba7530515c414d1cd566a3

Changes since my last review:

- `!parsed_count` -> `!parsed_count.has_value()`
- Rebased on current master

**Pull request merged**
