### PR TITLE
Include pruned state in chaininfo.json

### PR DESCRIPTION
**Pull request by sime**

### CODE REVIEW

**Comment by paveljanik** [comment]
When you are at it, can you please document "softforks" (from #6353) in the doc/REST-interface.md file?

Please also add "pruned" and "pruneheight" into helptext here https://github.com/bitcoin/bitcoin/blob/master/src/rpcblockchain.cpp#L597 to make it complete.

**Comment by sime** [comment]
@paveljanik I've included the extra documentation. should `doc/REST-interface.md` go into the array contents of `softforks`? As I have only include the upper most level.

**Comment by jonasschnelli** [comment]
ACK

**Comment by laanwj** [comment]
LGTM, ACK

**Pull request merged**
