### PR TITLE
doc: Remove outdated minrelaytxfee comment

### PR DESCRIPTION
**Pull request by maflcko**
This is no longer true after #9380

### CODE REVIEW

**Comment by laanwj** [comment]
Ping @morcos

**Comment by morcos** [comment]
utACK

But we should probably replace it with a more accurate comment.

**Comment by MarcoFalke** [comment]
I doubt any user will download and read the source code to look for documentation of command line args. The documentation should be put in the manpages.

**Comment by laanwj** [comment]
Adding a more accurate comment could be done later - let's remove the inaccurate one at least.

**Pull request merged**
