### PR TITLE
RPC: Add feature to getblock by using the index

### PR DESCRIPTION
**Pull request by cvengler**
Hello, this PR adds a feature to `getblock` which allows to get the blockdata directly without the need for using `getblockhash` first.

First it checks if you have provided an input smaller than 64 characters.
After that it checks if the input is a valid number or if it contains letters.
If it is a valid number it will request the blockhash for this index.

The feature to use the hash directly works of course as well.

If the user provides an input which is smaller than 64 characters and is not a valid number it will return an error.

The changes were tested by myself and they work.

The reason for this improvement is that it is too exaggerated for me to first get the hash of an index and then get the block data with two separate commands.

### CODE REVIEW

**Comment by promag** [comment]
This was attempted before and rejected.

**Comment by laanwj** [comment]
Besides the conceptual discussion, I think this particular implementation has a few issues:

- Interpreting a string as a number breaks API consistency; sure, from `bitcoin-cli` you won't be able to see the difference, but from other languages using RPC it's unexpected to have to handle a number differently from other places
- Overloading based on how the value looks just feels wrong to me

*If* we really want this (it seems to be an often-requested thing) then my suggestion would be to define a new RPC call `getblockbyheight` instead of the usually brittle ways to re-define arguments.

**Comment by emilengler** [comment]
Good point, haven't had this in mind when I was doing it.
To your second point, I think it would become problematic only if the block height becomes 64-digits long. But I'm also convinced now that a separate RPC call is probably a better solution.

**Comment by promag** [comment]
What it the problem of 2 calls?

**Comment by emilengler** [comment]
Actually I don't see a problem with two calls as it is the best solution.
But I would prefer to do this in a new pull request rather than by this.

**Pull request closed without merging**
