### PR TITLE
ci: Cleanup macOS runs

### PR DESCRIPTION
**Pull request by maflcko**
* Remove a commented out cleanup task in `before_cache`
* Remove the linter run on macOS, and document that GNU tools are required to run the linters

### CODE REVIEW

**Review by ryanofsky — APPROVED** [review]
Code review ACK fadccb263baf6b8694f750623add42f966e423a3. But since this change reverts #13728, and I'm not sure what the specific goals of #13728 were, I guess I'd only give an uncertain +0.5 concept ACK.

For the specific scripted diff problem I ran into https://github.com/bitcoin/bitcoin/pull/13728#issuecomment-542973824, other solutions may make it possible to restore #13728 in the future like using homebrew to install modern versions of sed and bash, or just skipping the scripted-diff lint check on macos but running all the other lint checks.

**Comment by MarcoFalke** [comment]
Also, now that #16597 is merged, we should be more cautious with using too much travis resources. On weekdays a backlog of macOS builds up here: https://www.traviscistatus.com/

**Comment by Empact** [comment]
Believe you could directly revert this merge commit: https://github.com/bitcoin/bitcoin/commit/42d0eca725a83c999e2b67e33dfc7bcc96288dc3

And an alternative solution to issue noted in #13726 could be to disable the scripted-diff checks in that environment. It's still the case that people will run Mac OS environments.

**Comment by MarcoFalke** [comment]
There is a backlog of about 400 jobs on macOS travis right now (see the link in my previous comment). I don't think it is worth it to use those resources for linters, when mac users can simply not run the linters (they are run on travis as the fist step, real quick) or install GNU sed via brew or run them in a bionic docker container.

**Review by ryanofsky — APPROVED** [review]
Code review ACK fa677d1801fb9153a95a1fc9855fd5f21fc440c0 for new third commit replacing TRAVIS_OS_NAME check with NO_DEPENDS setting

**Comment by MarcoFalke** [comment]
Instead of the linter, I'd rather have a depends built on macOS. I'll leave that for a follow up pull request.

**Comment by MarcoFalke** [comment]
The linter isn't particularly stable, it seems: https://github.com/bitcoin/bitcoin/pull/17183#issuecomment-544128751

Any objections to getting this merged. @Sjors ?

**Comment by Empact** [comment]
Why not revert the merge commit to make it clearer what is reversion and what is clean-up / clarify authorship?

**Comment by MarcoFalke** [comment]
It is a revert of the merge commit (with conflicts solved) and the two commented out lines removed

**Comment by Empact** [comment]
Just suggesting that what you report would be more explicitly and succinctly communicated by the changelog if you separated those two operations. May be obviated by the conflicts though, I’m not sure about that.

**Comment by Sjors** [comment]
Code review ACK fa677d1801fb9153a95a1fc9855fd5f21fc440c0

Disabling the linter probably deserves its own commit / a more clear commit name.

**Comment by laanwj** [comment]
ACK fa677d1801fb9153a95a1fc9855fd5f21fc440c0

**Pull request merged**
