### PR TITLE
Minor update to qrencode package builder

### PR DESCRIPTION
**Pull request by MitchellCash**
Use package name variable inside qrencode $(package)_file_name variable

### CODE REVIEW

**Comment by fanquake** [comment]
Tested ACK 1bfe6b4

**Comment by MarcoFalke** [comment]
utACK 1bfe6b4

**Comment by laanwj** [comment]
What is the effect of this?

**Comment by MarcoFalke** [comment]
No effect. It just seems that this style is used in the other files.

**Comment by mitchellcash** [comment]
@laanwj sorry I should have been more specific in my description, but as @MarcoFalke mentions, it is more about being consistent with the other files.

**Pull request merged**
