### PR TITLE
SSL/TLS support for the HTTP(S) server

### PR DESCRIPTION
**Pull request by cvengler**
**Currently it only works on server side. bitcoin-cli needs probably a complete rewrite to work, see more below**

# Abstract
The goal of this PR is to add full functional SSL support to the Bitcoin Core HTTP Server.
# Motivation
At the moment it is not really secure to use Bitcoin Core RPC remotely. (#12763) made it much more secure with restricting access. However the connection level side is still insecure as it works through plain HTTP.
# The bitcoin-cli problem
The reason why I am opening this PR in this early state is because it seems like bitcoin-cli will need a rewrite powered by libcurl as libevent has not really good SSL support on the client side (other ideas and help is most welcome). As such a change is major I already wanna ask for `r"Concept (N)?ACK"` so that such a major change won't be worthless.
# OpenSSL again
This PR adds OpenSSL again. I would like if @fanquake could review the first two commits as they mostly consist of reverts from two of his PRs (#17265 and #17165) 
# Testing
It is already testable. Please be sure to have OpenSSL installed on your system! (Debian: `apt install openssl libssl-dev`)
You should also have `cURL` installed.
**The actual testing**
1. Generate an SSL cert with 
`openssl req -nodes -new -x509 -keyout server.key -out server.cert`.
If you have problems with the generation, you can download mine. (DO NOT USE THEM PRODUCTIVELY AS THE PRIVATE KEY IS PUBLICLY AVAILABLE). [Download here](https://www.emilengler.com/openssl.zip)
2. Compile my branch
3. Start bitcoind with
```
./bitcoind --server=1 --rpcuser=u --rpcpassword=p --regtest --ssl=1 --sslcert=/home/emil/openssl/server.cert --sslkey=/home/emil/openssl/server.key
```
 *(Please adjust the paths according to yours)*
4. Do the SSL request (Enter `p` as password)!
```
curl --user u -k --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getbestblockhash", "params": [] }' -H 'content-type: text/plain;' https://127.0.0.1:18443/
```
5. You should see that you just made a successful HTTPS request
# [Demo (Youtube Video)](https://www.youtube.com/watch?v=lBXl33XeDP4&feature=youtu.be)

### CODE REVIEW

**Comment by practicalswift** [comment]
@emilengler 

Do you see any advantage of handling SSL termination ourselves as opposed to delegating it to say a properly hardened `nginx` setup? It seems like this would broaden our attack surface and also bring in highly unwanted dependency :)

**Comment by sipa** [comment]
For context, Bitcoin Core used to have RPC SSL support. It was hard to use, hardly used, and probably shouldn't be used as the RPC interface is not hardened against untrusted users.

The release notes in 0.12 give a few alternatives: https://bitcoin.org/en/release/v0.12.0#rpc-ssl-support-dropped

**Comment by jonasschnelli** [comment]
#5677 removed SSL for the RPC interface and there are some discussions about the SSL drop in that particular PR.
I think adding SSL is a mistake in terms of modularity and security layers. We don't advocate to expose the RPC interface to the public internet and if someone needs a secure connection to the interface, using Wireguard or an Ngnix/Apache reverse proxy with proper certificate based authentication makes much more sense to me.
To me it makes little sense if each daemon application has its one httpd/SSL stack. IMO that should be handled by the applications/layers focusing on doing that properly.

The 0.12 release notes also had some examples how to accomplish SSL via a reverse proxy:
https://github.com/bitcoin/bitcoin/blob/47d981e8273804a040d71665a4cb16038d6717e1/doc/release-notes/release-notes-0.12.0.md#rpc-ssl-support-dropped

**Comment by laanwj** [comment]
NACK on re-adding OpenSSL dependency.

**Comment by emilengler** [comment]
Ok, didn’t knew about that SSL existed previously.

**Pull request closed without merging**
