### PR TITLE
qt: AddressBookPage - Hide non PKHash-Addresses and improve GUI messages for signing address book

### LINKED ISSUE #17969: Sign Message UI allows selection of keyless addresses
## What Happens
When you click File|Sign Message, the UI asks you to choose an address with which to sign.  You can enter one by hand, paste from clipboard, or "Choose a previously used address."  The third option provides a list of addresses that includes addresses for which there is no private key (P2SH addresses).  This is intimately related to #10542 but the fix _here_ is straightforward.

## Expected Behavior
I expect addresses for which no private key is known to be excluded from the list presented.  I realize that the same list is used to select an address to which to receive a payment, but that code could be adjusted to accept a filter, or the private-key-less addresses could be filtered out during display.

## To reproduce
Ensure that you have at least one P2SH address in your Bitcoin core wallet.
Select File | Sign Message
Click the address book.
Note that there are P2SH addresses offered for selection.

This is in Bitcoin Core 0.18.

### PR DESCRIPTION
**Pull request by 10xcryptodev**
fix #17969 and also add better messages to AddressBookPage when it's called from SignVerifyMessageDialog

### CODE REVIEW

**Comment by 10xcryptodev** [comment]
#17918 doesn't solve the GUI messages on AddressBookPage for sign and verify case, when the user open the dialog from sign and verify message. Also modify walletmodel that's not necessary. @jonasschnelli could you take a look on this solution?

**Comment by jonasschnelli** [comment]
Concept ACK. Will have a closer look soon.

**Comment by luke-jr** [comment]
PR title is confusing.

**Comment by 10xcryptodev** [comment]
@luke-jr hope it's better now, i'm not so good with PR titles :)

Giving more details here:
I implemented your suggestion: https://github.com/bitcoin/bitcoin/pull/17918/files#r371023931

Working on that solution i also found the AddressBookPage was using the GUI messages for `SendingTab` and `ReceivingTab` showing wrong messages and window title for the user, also fixed that

**Comment by fanquake** [comment]
@10xcryptodev Can you reopen this PR over in the new [GUI repo](https://github.com/bitcoin-core/gui)?

**Comment by 10xcryptodev** [comment]
@fanquake sure, i will open in the repo, thanks

**Pull request closed without merging**
