### PR TITLE
doc: Typos in test README

### PR DESCRIPTION
**Pull request by multisignature**
This patch fixes a few typos.

### CODE REVIEW

**Comment by multisignature** [comment]
Hopefully I did it right this time. Thanks to @michaelfolkson for the guidance!

**Comment by michaelfolkson** [comment]
You on IRC or is there some way to chat to help you with Git off of this PR? You opened the PR from master branch again and you will also need to [squash commits](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#squashing-commits).

**Comment by multisignature** [comment]
Ah, my bad. I have Discord, Telegram, Wickr, or email.

**Comment by michaelfolkson** [comment]
Can you send me an email michaelfolkson at gmail dot com? And close this PR. Thanks

**Comment by multisignature** [comment]
Sure thing.

**Pull request closed without merging**
