### PR TITLE
readme: Remove the word 'experimental' from description of Bitcoin

### PR DESCRIPTION
**Pull request by TomLisankie**
I don't believe the word 'experimental' applies to Bitcoin anymore.

There are hundreds of companies (and a few governments!) that use/hold or contribute to Bitcoin in some way or another, millions of people who hold Bitcoin as a store of value and/or use it as a medium of exchange, the Bitcoin network has been running continuously since its inception more than 13 years ago, and hundreds of projects exist that have gone on to develop other assets that take the methods first implemented in Bitcoin and attempt to copy them or alter them in some way.

Bitcoin is many things but it no longer seems experimental.

I saw [the conclusion](https://github.com/bitcoin/bitcoin/pull/24431#issuecomment-1063327063) of #24431 but I still decided to keep the issue open because it does not seem to me that just saying Bitcoin is a digital currency without the 'experimental' descriptor implies that the Bitcoin Core developers (or Bitcoin developers more generally) would be liable if there were to be some catastrophic bug (waiving any liability is already taken care of by the MIT License).

### CODE REVIEW

**Comment by russeree** [comment]
On a long enough time scale everything is experimental. Just my vote but the verbiage does accurately represent the project accurately. Reading the original PR. They are right to try to close this up. The time spent on this doesn't feel like it was valuable and there are many issues that need to get resolved. Just my 2 satoshis.

**Comment by TomLisankie** [comment]
I don’t disagree with you, but there’s a difference between talking
about the philosophy of what it means for something to be “experimental”
and the everyday usage of the term (e.g. “brand new and unproven”). The
latter of those two usages I think is appropriate for the context of a
first paragraph for a digital currency’s README.

On April 23, 2022, Onkar Suhas Samant ***@***.***> wrote:
> On a long enough time scale everything is experimental. Just my vote
> but the verbiage does accurately represent the project accurately.
> Reading the original PR. They are right to try to close this up. The
> time spent on this doesn't feel like it was valuable and there are
> many issues that need to get resolved. Just my 2 satoshis.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/bitcoin/bitcoin/pull/24951#issuecomment-1107390145>,
or unsubscribe <https://github.com/notifications/unsubscribe-
auth/AAAWT3TQEQ4HFP4ICAGX2D3VGOI2FANCNFSM5UD7PFVQ>.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by TomLisankie** [comment]
@fanquake what was the reason for closing this?

**Comment by laanwj** [comment]
There's a literal endless litany of issues and PRs exactly like this, starting from inception of this project, that have been closed every time (a selection: #24719 #24429 #21883 #20374 #16731 #16731). I'm not sure why you'd expect this one to be treated otherwise. 

The people working on the project disagree (I'd personally say bitcoin is still experimental both from a technical and legal perspective), so it's not going to be changed.

If you believe otherwise that's fine, but if you disagree with the developers and maintainers so much, then maybe you should consider why a word in the README.md file is still so important to you, you should be able to ignore that as well!

**Comment by russeree** [comment]
There are lots of ways to get started and successfully contribute to the community. 

 - Review issues
 - Create prs regarding issues 
 - Join IRC channels and contribute to the conversation 
 - Build and test new tags, branches, releases
 
If I can help in any way let me know. Though I myself am quite new.

**Comment by TomLisankie** [comment]
> (I'd personally say bitcoin is still experimental both from a technical and legal perspective)

@laanwj Okay, I accept that. However I am curious why you personally would say Bitcoin is still experimental from a technical perspective? And what would have to happen for you to no longer see it that way?

**Comment by laanwj** [comment]
@TomLisankie I don't have any specific requirements, but overall: when it's more integrated into society, seen as another means of storing  and transferring value (as well as other things it can do), and not regarded special anymore. This is kind of subjective, but take a few steps outside the enthusiasts bubble and you understand what I mean.

Note that I don't see experimental as a bad thing, experimenting with things and evaluating them is the only way society advances. And it goes really slow with financial/economic developments.

**Comment by TomLisankie** [comment]
@laanwj Thanks. I appreciate the thoughtful response.

**Pull request closed without merging**
