### PR TITLE
test: orphan parent is re-requested from 2nd peer

### PR DESCRIPTION
**Pull request by instagibbs**
Small test which I couldn't find coverage for.

### CODE REVIEW

**Review by glozow — COMMENTED** [review]
lgtm ACK 0f84cdd26614a229d9aee6cd74a1aa01b204a1f5

**Review by tdb3 — APPROVED** [review]
code review ACK 0f84cdd26614a229d9aee6cd74a1aa01b204a1f5

Looks good.

**Review by theStack — APPROVED** [review]
ACK 0f84cdd26614a229d9aee6cd74a1aa01b204a1f5

**Review by marcofleon — COMMENTED** [review]
tACK 0f84cdd26614a229d9aee6cd74a1aa01b204a1f5. Removing `node.bumpmocktime(GETDATA_TX_INTERVAL)` results in failure.

**Pull request merged**
