### PR TITLE
Reduce fingerprinting attacks

### PR DESCRIPTION
**Pull request by rebroad**
Unlikely to have happened but it is possible a fork with lower difficulty reaches a height comparable to our ActiveChain's height and that one (or more) of these blocks were spoon-fed to our node (as our node would not request them due to insufficient nChainWork). In this case, we could be fingerprinted. Closing this unlikely yet possible attack vector.

Another way to close this vector is to not accept blocks received that are are unrequested and have less nChainWork than our ActiveChain's Tip.

### CODE REVIEW

**Comment by gmaxwell** [comment]
You can't instantly stop responding to requests for thing you offered just because you had a reorg.  Doing so would be abusive to your peers.   This protection from fingerprinting is much more aggressive than what we do for getblocks (the original code was also more aggressive which is why we didn't consider fingerprinting an issue). No additional fingerprinting protection is provided by being more restrictive than getblocks.

**Comment by rebroad** [comment]
@gmaxwell I think you misunderstand this PR.

The current functionality is that getblocktxns requests are ignored for old blocks (old defined by superceeded by 10 or more blocks) UNLESS they are blocks on an alt chain, in which case the request is accepted as long as their height on the alt chain is within 10 of the height on the active chain.

Depending on when the alt chain forked, the block heights could have become out of sync with the active chain and not be representative of "10 blocks ago" based on the height check. i.e. on the alt chain, they could be blocks 20 blocks ago from that alt chain's tip.

This change therefore changes the check to go back only the equivalent of 10 blocks in terms of work, after-all it is the work which decides which is the winning fork, not the height. The deciding factor for the re-org should surely be used here, not an irrelevant factor (i.e. the height).

**Comment by gmaxwell** [comment]
Thanks for clarifying what you're trying to address, that wasn't clear to me before. I'll re-review with that understanding.

**Comment by rebroad** [comment]
@gmaxwell I realise that the maths isn't perfect if the block data requests is within 10 blocks of a difficulty change, the result might mean that it is effectively 9 or 11 blocks, but I felt this was close enough to 10 to not worry about. The way to make it exactly 10 would be to perhaps use -->pprev->pprev->pprev etc to get back to the block 10 ago (of course checking that nHeight is at least 11 also, or maybe the smallest height  that compact blocks became active), but I decided against this approach as the code was more complex for little extra gain.

**Comment by gmaxwell** [comment]
@rebroad Instead of using work, what are your thoughts on using chainActive.FindFork()?

**Comment by rebroad** [comment]
@gmaxwell ah.. I think the GetAncestor() part used by FindFork() will do the trick nicely, i.e. check that the work is at least as much as as chainActive.GetAncestor(chainActive.Tip()->nHeight-10)->nChainWork - this would then take into account the difficulty changes (and effectively follows pprev the 10 times needed).

I am not sure what the difference between chainActive.FindFork(pindex) and LastCommonAncestor(chainActive.Tip(), pindex) is...  they seem pretty similar if not the same - studying the code further to work out if there is a difference.

**Comment by rebroad** [comment]
@gmaxwell I'm not sure how FindFork() would help, but how about:-
`if (it->second->nChainWork < chainActive[std::max(0,chainActie.Height()-MAX_BLOC  KTXN_DEPTH)]->nChainWork)` ?

**Comment by rebroad** [comment]
Looking at #5918 (which fixed this issue for getdatas of blocks), it is using GetBlockProofEquivalendTime(), so for 10 blocks, this would be 10 * 10 * 60 seconds into the past permissable. I'm not sure if using this function would provide any advantage though.

**Comment by rebroad** [comment]
Renamed as some additional commits to be added shortly.

**Comment by fanquake** [comment]
No new commits have been pushed, and no more comments made. Feel free to re-open when you've pushed more code.

**Pull request closed without merging**
