### PR TITLE
Revert "Add patch to make codesign_allocate compatible with Apple's"

### PR DESCRIPTION
**Pull request by sipa**
This reverts #20644.

It appears that Apple has recently changed their `codesign_allocate` tool back to using 4k alignment on x86_64, at least in some cases, so this patch isn't causing our cctools-based version to be exactly compatible.

Furthermore, if codesigning were to change to use https://github.com/achow101/signapple instead, there is no need anymore to try to mimick Apple.

### CODE REVIEW

**Review by Bayrsaikhan12 — APPROVED** [review]

**Review by whiteslack — APPROVED** [review]

**Comment by laanwj** [comment]
ACK a0eb4c551ebf8adfacb8c38c4ce56641fe379667
Thanks for doing this anyway, this is so thankless and tiring, having to second-guess Apple's moves.

**Review by laanwj — APPROVED** [review]

**Comment by MarcoFalke** [comment]
Reference from IRC: `[06:46] <jonasschnelli> current state: 0.19.2rc1 and 0.20.2rc1 are signed (with achow101's tool), 0.21.0rc4 can't be signed deterministically (needs revert of sipas patch)`

**Review by jonasschnelli — APPROVED** [review]
ACK a0eb4c551ebf8adfacb8c38c4ce56641fe379667

**Comment by MarcoFalke** [comment]
checked-clean-revert ACK a0eb4c551ebf8adfacb8c38c4ce56641fe379667

**Comment by MarcoFalke** [comment]
Backported in #20850

**Pull request merged**
