### PR TITLE
Trivial: spelling fixes

### PR DESCRIPTION
**Pull request by ka7**
patch contains some spelling fixes ( just in comments ) as found by a bot ( http://www.misfix.org, https://github.com/ka7/misspell_fixer ).

### CODE REVIEW

**Comment by jonasschnelli** [comment]
ACK 248d9a2fb1fab3dca595aa988f1fcd895904cf48

**Comment by paveljanik** [comment]
ax_... upstream, sec256* upstream, leveldb upstream please.

**Comment by practicalswift** [comment]
Very good finds! Can't believe I haven't found these myself :-)

The policy is not to fix typos in release notes/change logs, so please skip the changes made in `contrib/debian/changelog`.

One of the secp256k1 typos has been reported upstream by me: https://github.com/bitcoin-core/secp256k1/pull/440 :-)

ACK 248d9a2fb1fab3dca595aa988f1fcd895904cf48 modulo the above + @paveljanik:s comments

**Comment by practicalswift** [comment]
@ka7 The updated version is better but please also remove the changes made to:

```
build-aux/m4/ax_boost_base.m4
src/leveldb/
src/secp256k1/
```

These should be reported upstream instead :-)

**Comment by practicalswift** [comment]
@ka7 Thanks for a nice first-time contribution! 

I used your tool to find 12 typos in the Swift project: https://github.com/apple/swift/pull/10710. That is quite impressive considering that the Swift project has had [218 merged typo fix PRs]( https://github.com/apple/swift/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Amerged%20typos%20) already. Prior to the run with your tool I believed the Swift code base to be at near zero typos (despite having 1.8 million lines of text in the repo) :-)

**Comment by jnewbery** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/10705/commits/5d4be45694126bf28f509dce27e98666621abc25. Please squash commits.

**Comment by practicalswift** [comment]
ACK 4e285175ff3a2fb1f78ad8216e1c88d3cd594b7b assuming that the current five commits are squashed into one commit :-)

**Comment by paveljanik** [comment]
ACK after squash

**Comment by practicalswift** [comment]
@ka7 Could you please include fixing of these typos in this PR as well? :-)

```
# a vs an ("an already", "an one-off")
src/qt/bitcoinstrings.cpp:"Error loading %s: You can't enable HD on a already existing non-HD wallet"),
src/qt/bitcoinstrings.cpp:QT_TRANSLATE_NOOP("bitcoin-core", "Error loading %s: You can't disable HD on a already existing HD wallet"),
src/test/netbase_tests.cpp:    // and that a one-off resolves correctly

# duplicate words ("command")
doc/Doxyfile.in:# popen()) the command command input-file, where command is the value of the
```

**Comment by jtimon** [comment]
ACK 248d9a2

**Comment by practicalswift** [comment]
@ka7 Please squash. Do this:

```shell
$ git checkout feature/spelling
$ git rebase -i HEAD~5
# replace "pick" with "fixup" for all but the first line (resulting in 1 pick and 4 fixup)
$ git push -f
```

**Comment by MarcoFalke** [comment]
Squashed and force pushed: 4e285175f...f42fc1d50

**Pull request merged**
