### PR TITLE
0.19: gui: Avoid Wallet::GetBalance in WalletModel::pollBalanceChanged

### PR DESCRIPTION
**Pull request by promag**
Backport #18160.

### CODE REVIEW

**Comment by fanquake** [comment]
Does this need backporting if it's being reverted in #18587?

**Comment by promag** [comment]
That was my suggestion, because the alternative would require backporting #17905 (which is not in 0.20).

**Comment by promag** [comment]
Note that in #15015 you see reports for older versions, but I think 0.19 is enough. Could check if this is clean backport in 0.18 but I'm not sure if there will be a new 0.18 patch release.

**Comment by fanquake** [comment]
Now part of #19025.

**Pull request closed without merging**
