### PR TITLE
test: Fix intermittent issue in p2p_segwit.py

### PR DESCRIPTION
**Pull request by maflcko**
Calling `start_node` might call `wait_for_rpc_connection`, which will fail.

https://cirrus-ci.com/task/5669555591708672?logs=ci#L3504

```
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/p2p_segwit.py", line 1974, in test_upgrade_after_activation
    self.start_node(2, extra_args=["-reindex", f"-segwitheight={SEGWIT_HEIGHT}"])
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 508, in start_node
    node.wait_for_rpc_connection()
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_node.py", line 224, in wait_for_rpc_connection
    raise FailedToStartError(self._node_msg(
test_framework.test_node.FailedToStartError: [node 2] bitcoind exited with status 1 during initialization

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Actually I have no idea how this test could even pass in the first place. All code paths here should eventually `raise FailedToStartError`, which shouldn't be caught and thus fail the test.

If someone wants to investigate this, that'd be great. Though the diff here should still be correct, as `assert_start_raises_init_error` is the proper way to check for init errors.

**Comment by Sjors** [comment]
Maybe rebase in light of #21804 merge.

**Comment by MarcoFalke** [comment]
Rebased, as requested by @Sjors

**Comment by jnewbery** [comment]
ACK fad6269916dbf8adc14d757a18f19c74e95cf659

**Comment by dhruv** [comment]
ACK fad6269

Thank for the fix, and showing me `assert_start_raises_init_error` @MarcoFalke. I am incorporating this into #21090 as well. It is indeed perplexing that the error was only intermittent.

**Comment by adamjonas** [comment]
Verifying the efficacy of this patch.

- The 4 days before this PR was merged there were 235 builds of master on cirrusCI resulting in 4 p2p_segwit.py failures.
- Since its merge, there have been 343 builds of master and 0 p2p_segwit.py failures.

**Pull request merged**
