### PR TITLE
build: Decouple clientversion.cpp from the git repo

### PR DESCRIPTION
**Pull request by hebasto**
This PR makes build process not using `git` to get the client version from the repository.
`clientversion.cpp` uses the client version data that are explicitly provided in `configure.ac`.

gitian/guix builds are not touched yet.

Alternative to #18902.

Seeking for concept acks.

### CODE REVIEW

**Comment by laanwj** [comment]
Concept ACK. As I noted on IRC, all the version information for releases including the RC level is self-contained in `configure.ac` now. There's no need to peek into git.

There is one time it's useful to look at git during the build process: if someone builds from git source, to be able to see the commit they built from in the program. This is somewhat useful for developers but if it causes too much difficulty and complexity I'm okay with foregoing it.

**Comment by tryphe** [comment]
Concept ACK. Since we're already using ac defines, one less script and one less header looks delicious!

**Comment by hebasto** [comment]
Rebased f04a6b4e3db133a29221ba4830daaa5a58992911 -> 9e8a1d002edee6d1d3529832be304e16b4c6e497 ([pr18980.01](https://github.com/hebasto/bitcoin/commits/pr18980.01) -> [pr18980.02](https://github.com/hebasto/bitcoin/commits/pr18980.02)) due to the conflict with #18677.

**Comment by luke-jr** [comment]
Doesn't this break including the current commit hash when doing actual git builds?

**Comment by fanquake** [comment]
Concept ACK

**Comment by fanquake** [comment]
Changing my concept ACK to ~0. It's not clear the tradeoff of losing git info from source builds is worth this change, and for some reason that tradeoff isn't mentioned in the PR description.

Otherwise, what is the status of this?

**Pull request closed without merging**
