### PR TITLE
build: Fix #include sys/poll.h to just poll.h (without sys/)

### PR DESCRIPTION
**Pull request by carnhofdaki**
http://pubs.opengroup.org/onlinepubs/009695399/functions/poll.html
http://man7.org/linux/man-pages/man2/poll.2.html

### CODE REVIEW

**Comment by laanwj** [comment]
ACK 0a996375c165293535ebf27c8103767963f1572e

**Comment by theStack** [comment]
ACK https://github.com/bitcoin/bitcoin/commit/0a996375c165293535ebf27c8103767963f1572e

**Comment by Empact** [comment]
ACK 4de0bde7bc546638cbbbb8bc4eb0d840d81cb953

**Comment by fanquake** [comment]
@carnhofdaki were you seeing a particular compile failure, or just making this align with the spec?

**Comment by carnhofdaki** [comment]
@fanquake no failure, just a warning.

**Review by fanquake — APPROVED** [review]
ACK 4de0bde7bc546638cbbbb8bc4eb0d840d81cb953 - Tested on macOS 10.14.6, Debian 10.1 and OpenBSD 6.5.

**Pull request merged**
