### PR TITLE
[qt] Windows: Make rpcconsole monospace font larger

### LINKED ISSUE #7017: Showing very tiny font in the Debug console tab
on Windows 7, 32bit

consoletab

### PR DESCRIPTION
**Pull request by maflcko**
Probably fixes #7017.

Merges fine into `master` and `0.12`.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
utACK for 0.12 (rc2) not sure if we want this for master/0.13 or if we should look for a better/alternative solution.

Build to test should be ready soon: https://bitcoin.jonasschnelli.ch/pulls/7364/

**Comment by MarcoFalke** [comment]
Thanks for the binaries.

Even though this is ugly, I'd say it should be merged into master as well. Lacking a better solution, it doesn't make things worse and backports easier.

**Comment by luke-jr** [comment]
Why are we not using QFontInfo(**fixedFontInfo**).pointSize() here?

**Comment by MarcoFalke** [comment]
@luke-jr dejavu #7364.

**Comment by luke-jr** [comment]
Seems like QFont() has the same problems? Makes more sense to scale fixedFontInfo than to scale some other font's default size. Besides, we got that Qt5 thing since then?

**Comment by MarcoFalke** [comment]
> Makes more sense to scale fixedFontInfo than to scale some other font's default size

Previously we had a "default font", so that's the reference. Though, you are welcome to change that.

> Besides, we got that Qt5 thing since then?

Doesn't change anything for Windows or Linux. Only a different font for OS X.

**Comment by laanwj** [comment]
Oh no, not more monospace related code changes. When are you guys going to give this up :-)

**Comment by jonasschnelli** [comment]
Tested ACK fa6a59dd397e62e850fc57df05cd6d117fbdcd82.
This is a quick and stable workaround and we should backport this to 0.12.
**For 0.13 we need a better solution.**

Current Master (to small on windows):
bildschirmfoto 2016-01-22 um 09 39 07

Current 0.11 version, non pretty, non mono (people are use to this font size):
bildschirmfoto 2016-01-22 um 09 41 02

This PR:
bildschirmfoto 2016-01-22 um 09 38 12

**Comment by laanwj** [comment]
I don't think this solution is acceptable in the longer term. We have to do one of these:
- Remove the #ifdef, just accept that the font is too big on some OSes
- Revert the console to proportional font as in 0.10.x

**Comment by luke-jr** [comment]
@laanwj http://permalink.gmane.org/gmane.mail.trojita.general/1315

**Pull request merged**
