### PR TITLE
MacOS Monterey(12.0 beta) support confirmed

### PR DESCRIPTION
**Pull request by mikkildlebl**
I checked that you can compile bitcoin in macOS Monterey!

I create this pull request to assure devs that bitcoin-core is compilable in macOS Monterey that was recently released.

### CODE REVIEW

**Comment by promag** [comment]
Thanks for the feedback.

**Comment by mikkildlebl** [comment]
There is no reason for these checks to fail it's a doc!

**Comment by MarcoFalke** [comment]
Jup, the test failure can simply be ignored. Reported as #22243

**Comment by fanquake** [comment]
Thanks for letting us know. However there's no need to change this documentation at this point.

**Pull request closed without merging**
