### PR TITLE
docs: Updated debug build instructions for cmake

### PR DESCRIPTION
**Pull request by itornaza**
In the [developer notes](https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md) the section on [compiling for debug](https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md#compiling-for-debugging) displays outdated instructions that were applicable before the move to cmake build system.

This PR just gives instructions on how to build for debugging in the context of cmake.

### CODE REVIEW

**Review by tdb3 — COMMENTED** [review]
Concept ACK

Looks like the Win64 CI error is unrelated.

**Comment by itornaza** [comment]
Rebased to address the CI lint test error that was due to documentation lines terminating with whitespace characters.

**Review by tdb3 — APPROVED** [review]
ACK 0b003e1ff7e09b56cd013b15f1998495994b7211

**Comment by kevkevinpal** [comment]
ACK [0b003e1](https://github.com/bitcoin/bitcoin/pull/30840/commits/0b003e1ff7e09b56cd013b15f1998495994b7211)

Also in this parity list `--enable-debug` is replaced with `-DCMAKE_BUILD_TYPE=Debug` and defaults to `RelWithDebInfo`
https://gist.github.com/hebasto/2ef97d3a726bfce08ded9df07f7dab5e

**Comment by itornaza** [comment]
> Also in this parity list `--enable-debug` is replaced with `-DCMAKE_BUILD_TYPE=Debug` and defaults to `RelWithDebInfo` https://gist.github.com/hebasto/2ef97d3a726bfce08ded9df07f7dab5e

Very helpful link, thanks for sharing!

**Comment by achow101** [comment]
ACK 0b003e1ff7e09b56cd013b15f1998495994b7211

TIL `ccmake`.

**Pull request merged**
