### PR TITLE
Refactor: Modernize disallowed copy constructors/assignment

### PR DESCRIPTION
**Pull request by danra**
Use C++11's better capability of expressing an interface of a non-copyable class by publicly deleting its copy ctor and assignment operator instead of just declaring them private.

### CODE REVIEW

**Review by dcousens — APPROVED** [review]

**Comment by practicalswift** [comment]
utACK 2a07f878a80003f2142d5052d015a9ac81a3a6bc. Nice C++11 cleanup!

**Comment by sipa** [comment]
utACK 2a07f878a80003f2142d5052d015a9ac81a3a6bc

**Comment by instagibbs** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/11351/commits/2a07f878a80003f2142d5052d015a9ac81a3a6bc

**Review by gmaxwell — APPROVED** [review]
utACK.  Is this all the cases of unused copy constructors in the codebase?  (no need for it to be now, but ifs not we should take a note to go do more of these).

**Comment by danra** [comment]
@gmaxwell Yes.

**Pull request merged**
