### PR TITLE
[tests] Speed up knapsack_solver_test by not recreating wallet 100 times.

### PR DESCRIPTION
**Pull request by lucash-dev**
Optimization of `knapsack_solver_test`by moving an expensive wallet creation to outside a 100x for loop.

On my (slow) machine:

```
before:        9.8s
after:         6.2s
--------------------
saved:         3.6s (36%)
```

This PR was split from #13050. Also see #10026.

### CODE REVIEW

**Comment by achow101** [comment]
I don't think this is entirely useful considering that this test will be removed (hopefully soon) altogether by #13307.

**Comment by laanwj** [comment]
> I don't think this is entirely useful considering that this test will be removed (hopefully soon) altogether by #13307. 

On the other hand this change is pretty straightforward, and might make sense until #13307 is merged.

**Comment by practicalswift** [comment]
Concept ACK

**Comment by lucash-dev** [comment]
Rebased.

**Comment by laanwj** [comment]
It's months later and #13307 is still in state of flux. I'm going ahead and merging this.

**Pull request merged**
