### PR TITLE
[26.x] archive 26.1 release notes + backports

### PR DESCRIPTION
**Pull request by glozow**
Archives 26.1 release notes and adds draft release notes for 26.2rc1

Also backports:
- #29691
- #29869
- #28554
- #29747
- #29853
- #29856
- #29764
- #29776
- #29985 
- #30094
- #29870
- #30149
- #30085

### CODE REVIEW

**Comment by Joudyadam** [comment]
how can i withdrawl my 3500 USDT  from okx wallet to binance please help me.
12 wallet phrase:

family nature fashion project scrub obscure bus crop coconut ship person winner

**Review by dasibcryptoidology — APPROVED** [review]

**Review by stickies-v — APPROVED** [review]
ACK a29e9e5fea98925cd19c4e9e8738de67d04da549 modulo [release notes touchup](https://github.com/bitcoin/bitcoin/pull/29899#discussion_r1611933793)

All backport commits are clean, except for:
- b1481467bdf6c1300341d1e2ca399ca5e30fdace: because of https://github.com/bitcoin/bitcoin/pull/28955
- 109b9d74f50651aa4765d6eec047f09e497215fd: because of LLVM version bump in #29659
- 7d13e6ab51a02db33fea4df61f70c3f919016a8b: because of removing -rpcserialversion (#28890, and #28438)

All of these look good to me.

nit: in b1481467bdf6c1300341d1e2ca399ca5e30fdace commit message, it should be `Github-Pull: #29776` instead of `Github-Pull: #29767`

**Comment by stickies-v** [comment]
re-ACK aa7e876953c460e8ff97a719fdb18f4f3ac4896f, only changes are fixing commit msg and transifex reference

**Review by willcl-ark — APPROVED** [review]
ACK aa7e876953c460e8ff97a719fdb18f4f3ac4896f

Checked that all backports were applied without modifcation where possible

**Pull request merged**
