### PR TITLE
[qa] smartfees: Properly use ordered dict

### PR DESCRIPTION
**Pull request by maflcko**
Dictionaries are not guaranteed to be sorted; Use an `OrderedDict` to avoid random failures of the smartfees test.

### CODE REVIEW

**Comment by paveljanik** [comment]
@MarcoFalke Marko, do you have a sample of how it fails without this change? I did 100 runs of master to compare and ACK this and it was always OK...

**Comment by MarcoFalke** [comment]
@paveljanik This depends on your environment. I will post exact steps to reproduce tonight, when I am home.

**Comment by laanwj** [comment]
+1 for using OrderedDict. Normal dicts's order is randomized (they use a random seed for security reasons) and it's clear that the order of those outputs here matters.

Aside: as of Python 3.5 [OrderedDict is implemented in C](https://bugs.python.org/issue16991) and hence almost as fast as normal dict. Not that it matters in this particular instance.

**Comment by laanwj** [comment]
To reproduce I'd suggest using an OrderedDict with the items reversed.

(can't do it myself right now, running the extended test suite using python 3)

**Comment by MarcoFalke** [comment]
@paveljanik To test this you can use `python -h` to see how you enable random hash seeds, if it is not yet enabled.

E.g. `python -R qa/rpc-tests/smartfees.py --srcdir=src` fails on master, passes with this patch.

**Comment by paveljanik** [comment]
Still not able to reproduce here on master, OS X.

On the other hand, this command now failed for me on OS X, with this PR:

```
$ python -R qa/rpc-tests/smartfees.py  --srcdir=src
Initializing test directory /var/folders/65/fn0h49r55k7779vg1b_h461r0000gn/T/test2CcA11
This test is time consuming, please be patient
Splitting inputs to small size so we can generate low priority tx's
Finished splitting
Will output estimates for 1/2/3/6/15/25 blocks
Creating transactions and mining them with a block size that can't keep up
JSONRPC error: 16: bad-txns-in-belowout
  File "/private/tmp/bitcoin-7980/qa/rpc-tests/test_framework/test_framework.py", line 135, in main
    self.run_test()
  File "qa/rpc-tests/smartfees.py", line 244, in run_test
    self.transact_and_mine(10, self.nodes[2])
  File "qa/rpc-tests/smartfees.py", line 220, in transact_and_mine
    self.memutxo, Decimal("0.005"), min_fee, min_fee)
  File "qa/rpc-tests/smartfees.py", line 67, in small_txpuzzle_randfee
    txid = from_node.sendrawtransaction(completetx, True)
  File "/private/tmp/bitcoin-7980/qa/rpc-tests/test_framework/coverage.py", line 50, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "/private/tmp/bitcoin-7980/qa/rpc-tests/test_framework/authproxy.py", line 139, in __call__
    raise JSONRPCException(response['error'])
Stopping nodes
Cleaning up
Failed
$ 
```

**Comment by paveljanik** [comment]
When I run the test as `./smartfee.py`, it is always OK here though (both master and this PR) - this is what I did before.

Using your method (with or without `-R`), I have various failures here, e.g.:

```
bitcoin-master$ python -R qa/rpc-tests/smartfees.py  --srcdir=src
Initializing test directory /var/folders/65/fn0h49r55k7779vg1b_h461r0000gn/T/test_u6yGY
This test is time consuming, please be patient
Splitting inputs to small size so we can generate low priority tx's
Unexpected exception caught during testing: IndexError('pop from empty list',)
  File "/private/tmp/bitcoin-master/qa/rpc-tests/test_framework/test_framework.py", line 133, in main
    self.setup_network()
  File "qa/rpc-tests/smartfees.py", line 165, in setup_network
    split_inputs(self.nodes[0], self.nodes[0].listunspent(0), self.txouts, True)
  File "qa/rpc-tests/smartfees.py", line 79, in split_inputs
    prevtxout = txins.pop()
Stopping nodes
Cleaning up
Failed
bitcoin-master$ 
```

**Comment by MarcoFalke** [comment]
@paveljanik Thanks for noticing! Of course I need to fix it in the other places as well...

**Comment by paveljanik** [comment]
Tests are running.

@MarcoFalke Feel free to cherrypick typos from https://github.com/bitcoin/bitcoin/commit/bcdd81cc8abf3505c827610190daa746be7e0d96

**Comment by MarcoFalke** [comment]
@paveljanik Done, thx.

**Comment by paveljanik** [comment]
20 runs of `rm -rf cache/; python -R qa/rpc-tests/smartfees.py  --srcdir=src` in both master and this PR: master 12x Failed, this PR: all OK.

ACK https://github.com/bitcoin/bitcoin/pull/7980/commits/43bbcd075355630544a530f3cc52014edb3787b2

**Pull request merged**
