### PR TITLE
[Qt] fix unused function warning in scicon.cpp

### PR DESCRIPTION
**Pull request by Diapolo**
- MakeSingleColorImage() is unused in non Mac, silence the compiler
  warning

### CODE REVIEW

**Comment by luke-jr** [comment]
This seems unnecessarily convoluted IMO...

**Comment by Diapolo** [comment]
C'mon... @laanwj tried it, I didn't test it correctly and NOW the warning is gone. Please don't make it controversial if it works or give a better/easier solution and post a pull, thanks.

**Comment by luke-jr** [comment]
If you're going to use #if, just remove the whole function...?

**Comment by prestotron** [comment]
I'd say to just go with it. If it removes warnings, then less confusion :)

I didn't really review the code very much, but from what is said it does, it sounds good to me.

(Again, I did not read the code. I glanced at it, nor have I tested it.)

**Comment by Diapolo** [comment]
@luke-jr Try to #if the function and see what happens then -_-.

**Comment by luke-jr** [comment]
@Diapolo Simple, see #6328

**Comment by jonasschnelli** [comment]
Prefere #6328 because it's based on preprocessor macros.

**Comment by laanwj** [comment]
NACK, neither this nor #6327 is the solution we should use here.

**Comment by Diapolo** [comment]
@laanwj This is weird, as your solution (current master) doesn't fix the warning, while my patch und also Lukes did fix it. My idea was to get this fixed without such a discussion...

**Comment by laanwj** [comment]
@diapolo My point in #6328 is that non-breaking platform specific style differences should be based on a runtime decision, not on #ifdefs (or maybe one set of #ifdef at the initialization of the program, which can be overridden using an option). See my post here: https://github.com/bitcoin/bitcoin/pull/6328#issuecomment-115122650

**Pull request closed without merging**
