### PR TITLE
[doc] build: warn against spaces in working directory

### LINKED ISSUE #12528: build: building depends and make install fails with space in path
On MacOS 10.13.3 with source files in `/Volumes/Glyph 1TB/src/bitcoin`

```
sudo make install
Password:
Making install in src
  CXX      crypto/libbitcoinconsensus_la-aes.lo
...
  CXXLD    libbitcoinconsensus.la
/usr/local/bin/gsed: can't read 1TB/src/bitcoin/src/secp256k1/libsecp256k1.la: No such file or directory
libtool:   error: '1TB/src/bitcoin/src/secp256k1/libsecp256k1.la' is not a valid libtool archive
make[2]: *** [libbitcoinconsensus.la] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1
```

Related to #9946?

Running make inside `/depends` also results in a cascade of errors if the source path has a space in it.

### LINKED ISSUE #12529: [depends] make fails with space in path
Running `make` inside `/depends` results in a cascade of errors if the source path has a space in it.

### PR DESCRIPTION
**Pull request by Sjors**
Fixes #12528 and fixes #12529.

### CODE REVIEW

**Comment by laanwj** [comment]
I think we should fix this instead of warn against it

**Comment by Sjors** [comment]
From my understanding that would involve fixing `protobuf` and `libtool`. We could of course leave those tickets open even after this warning.

**Comment by laanwj** [comment]
>  fixing `protobuf` and `libtool`

So is this only an issue when building `depends`? I agree that is out of scope, and should probably be documented with depends then, but I think our own project should probably be spaces-safe.

**Comment by MarcoFalke** [comment]
Are there upstream issues about the packages in depends that won't build with spaces in paths?

**Comment by practicalswift** [comment]
Could test for this when running the `configure` script and warn if the unfortunate conditions are met?

**Comment by Sjors** [comment]
I don't think it's just depends. The first issue I found was `make install` failing on macOS, I don't think that involved depends. The second issue is depends.

**Comment by MarcoFalke** [comment]
With a space in the working directory I can not even start to compile depends (it would fail in the download step)

Is it worth to fix that?

**Comment by BlockMechanic** [comment]
is there at least a temporay wok around ?

**Comment by Sjors** [comment]
Rebased. As much I prefer the underlying problem to be solved, it's still there... E.g. on macOS when calling `make` in `depends`:

```
Fetching biplist-1.0.3.tar.gz from https://bitcoincore.org/depends-sources
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file /Volumes/SSD/dev/bitcoin 
Warning: space/depends/work/download/native_biplist-1.0.3/biplist-1.0.3.tar.gz.
Warning: temp: No such file or directory
 75 21258   75 16055    0     0  29085      0 --:--:-- --:--:-- --:--:-- 29085
curl: (23) Failed writing body (0 != 16055)
make: *** [space/depends/sources/download-stamps/.stamp_fetched-native_biplist-biplist-1.0.3.tar.gz.hash] Error 23
```

**Comment by fanquake** [comment]
I'm not convinced this is something we need to have in our documentation, and the fact that it hasn't come up apart from the issues you've opened might also point to that.

We could use our docs to warn everyone about every issue they might run into when compiling an autotools based C++ project, as well provide troubleshooting for their package manager (i.e #18070), but I think our READMEs should only contain instructions that are actually related to building Bitcoin Core, and we should work on the assumption that anyone reading them has a working development environment.

**Comment by Sjors** [comment]
It's uncommon for people to have spaces in their development environment path; it happened to me because I moved everything to an external SSD drive that had a bad default name. But I wouldn't consider that a broken environment.

**Pull request closed without merging**
