### PR TITLE
BIP 350: Implement Bech32m and use it for v1+ segwit addresses (0.21 backport)

### PR DESCRIPTION
**Pull request by sipa**
Backport of #20861. Also includes #21471.

### CODE REVIEW

**Comment by jnewbery** [comment]
utACK 28b3a32060

I repeated the backport myself and got the same result.

You could also pick the `rpc_invalid_address_message.py` functional test, removing the precise error messages (which aren't returned in v0.21):

<details>
<summary>rpc_invalid_address_message.py</summary>

```python
#!/usr/bin/env python3
# Copyright (c) 2020 The Bitcoin Core developers
# Distributed under the MIT software license, see the accompanying
# file COPYING or http://www.opensource.org/licenses/mit-license.php.
"""Test error messages for 'getaddressinfo' and 'validateaddress' RPC commands."""

from test_framework.test_framework import BitcoinTestFramework

from test_framework.util import (
    assert_equal,
    assert_raises_rpc_error,
)

BECH32_VALID = 'bcrt1qtmp74ayg7p24uslctssvjm06q5phz4yrxucgnv'
BECH32_INVALID_BECH32 = 'bcrt1p0xlxvlhemja6c4dqv22uapctqupfhlxm9h8z3k2e72q4k9hcz7vqdmchcc'
BECH32_INVALID_BECH32M = 'bcrt1qw508d6qejxtdg4y5r3zarvary0c5xw7k35mrzd'
BECH32_INVALID_VERSION = 'bcrt130xlxvlhemja6c4dqv22uapctqupfhlxm9h8z3k2e72q4k9hcz7vqynjegk'
BECH32_INVALID_SIZE = 'bcrt1s0xlxvlhemja6c4dqv22uapctqupfhlxm9h8z3k2e72q4k9hcz7v8n0nx0muaewav25430mtr'
BECH32_INVALID_V0_SIZE = 'bcrt1qw508d6qejxtdg4y5r3zarvary0c5xw7kqqq5k3my'
BECH32_INVALID_PREFIX = 'bc1pw508d6qejxtdg4y5r3zarvary0c5xw7kw508d6qejxtdg4y5r3zarvary0c5xw7k7grplx'

BASE58_VALID = 'mipcBbFg9gMiCh81Kj8tqqdgoZub1ZJRfn'
BASE58_INVALID_PREFIX = '17VZNX1SN5NtKa8UQFxwQbFeFc3iqRYhem'

INVALID_ADDRESS = 'asfah14i8fajz0123f'

class InvalidAddressErrorMessageTest(BitcoinTestFramework):
    def set_test_params(self):
        self.setup_clean_chain = True
        self.num_nodes = 1

    def skip_test_if_missing_module(self):
        self.skip_if_no_wallet()

    def test_validateaddress(self):
        node = self.nodes[0]

        # Bech32
        info = node.validateaddress(BECH32_INVALID_SIZE)
        assert not info['isvalid']

        info = node.validateaddress(BECH32_INVALID_PREFIX)
        assert not info['isvalid']

        info = node.validateaddress(BECH32_INVALID_BECH32)
        assert not info['isvalid']

        info = node.validateaddress(BECH32_INVALID_BECH32M)
        assert not info['isvalid']

        info = node.validateaddress(BECH32_INVALID_V0_SIZE)
        assert not info['isvalid']

        info = node.validateaddress(BECH32_VALID)
        assert info['isvalid']
        assert 'error' not in info

        # Base58
        info = node.validateaddress(BASE58_INVALID_PREFIX)
        assert not info['isvalid']

        info = node.validateaddress(BASE58_VALID)
        assert info['isvalid']
        assert 'error' not in info

        # Invalid address format
        info = node.validateaddress(INVALID_ADDRESS)
        assert not info['isvalid']

    def test_getaddressinfo(self):
        node = self.nodes[0]

        assert_raises_rpc_error(-5, "Invalid address", node.getaddressinfo, BECH32_INVALID_SIZE)

        assert_raises_rpc_error(-5, "Invalid address", node.getaddressinfo, BECH32_INVALID_PREFIX)

        assert_raises_rpc_error(-5, "Invalid address", node.getaddressinfo, BASE58_INVALID_PREFIX)

        assert_raises_rpc_error(-5, "Invalid address", node.getaddressinfo, INVALID_ADDRESS)

    def run_test(self):
        self.test_validateaddress()
        self.test_getaddressinfo()


if __name__ == '__main__':
    InvalidAddressErrorMessageTest().main()
```

</details>

**Comment by gruve-p** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/21469/commits/28b3a3206097b89c7cf5f510e83f6027324b51c8

**Comment by MarcoFalke** [comment]
cherry-pick-only ACK 28b3a3206097b89c7cf5f510e83f6027324b51c8 did not review code nor test 👓

<details><summary>Show signature and timestamp</summary>

Signature:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

cherry-pick-only ACK 28b3a3206097b89c7cf5f510e83f6027324b51c8 did not review code nor test 👓
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEE+rVPoUahrI9sLGYTzit1aX5ppUgFAlwqrYAACgkQzit1aX5p
pUjqXwwAgZwS8RcAWCviu1/EEdYDtAtrYxN5lH74nOV564EM+1VVLdhd+vfoI1Yh
fDziALpjLgqDKAOV1ItgX974pfR9Tf8ZUfrAMJc9Gh4e9qfQwu2xxNOnQ7ULNs48
GMpYyebKhtl+1Srh5R/Edfb3wrOQ4DBUIuflq5sReYsqOlmNTPTm9nt5Fj174he5
wmNn0z2NER7ROsB5fVtUNuRVVjNmfPkukUpkUs0qJb42oYWUgG6UyMksB7I0MmkK
3mQO6eYa/Rmh2fZdwoN/agS5uKvPumv51mXg8AXBoOAEtndw+lpZlSbZIsiC4+yY
LZbbQdM3DzJSstQtqqrQPyTZ9NwXjYpJIlQpTUru4a0XkDHsm+fF6Yf4YWLbA3qz
L2JnGOLJmHwrhYMkykB5XyAAhbsBV9DYzsu0T7fK8aDuJpqKsYOvZu3zie+G/KcK
gqxK3T16pqfWqtgBslOZ/BZ6Lykk6/zcMkDI+fSC3Zv0XVyohMLuEiH3431PZsz+
OSp9T+Dy
=z0EU
-----END PGP SIGNATURE-----
```

[Timestamp of file with hash `f15d8f2dd34efe4f3f1fb17b1645f6fb3541a505d0c1a3d25a6c888cd487a5f9  -`](https://opentimestamps.org/info/?004f70656e54696d657374616d7073000050726f6f6600bf89e2e884e892940108f15d8f2dd34efe4f3f1fb17b1645f6fb3541a505d0c1a3d25a6c888cd487a5f9f010287e43b660475f1bf499aa24e4401ad808fff0103605c76a6483e98c7d4d37e2bb2b230608f104605845fcf0083a300bedeb66ef780083dfe30d2ef90c8e232268747470733a2f2f6274632e63616c656e6461722e636174616c6c6178792e636f6dfff01057617244b5eb40858475cd24ad2793ae08f104605845fbf0082fffe31b3e9122700083dfe30d2ef90c8e2e2d68747470733a2f2f616c6963652e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267fff0106b0df60dae34d84efda71827a5cfae9008f104605845fcf0083e8f890b9b293de00083dfe30d2ef90c8e2c2b68747470733a2f2f626f622e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267f010b2776a577b94925fbb1476a5ff4b2b0d08f0207be870cbd8e5593fefa3e704c7f68db06d2bf8c57882cfc8e0ab78674e886dcf08f020f0a044ec4aec461be30ce791c4ecb05e76166cdc534c60fbfa1754dcc2578f5e08f10460583825f008e179a8b798863f2d0083dfe30d2ef90c8e292868747470733a2f2f66696e6e65792e63616c656e6461722e657465726e69747977616c6c2e636f6d)

</details>

**Comment by sipa** [comment]
@jnewbery Added a commit that does that.

**Comment by jnewbery** [comment]
Oops. Sorry. I think the linter is failing because of an unused import:

```
diff --git a/test/functional/rpc_invalid_address_message.py b/test/functional/rpc_invalid_address_message.py
index 4626f62b0f..814f50c9e6 100755
--- a/test/functional/rpc_invalid_address_message.py
+++ b/test/functional/rpc_invalid_address_message.py
@@ -6,10 +6,7 @@
 
 from test_framework.test_framework import BitcoinTestFramework
 
-from test_framework.util import (
-    assert_equal,
-    assert_raises_rpc_error,
-)
+from test_framework.util import assert_raises_rpc_error
 
 BECH32_VALID = 'bcrt1qtmp74ayg7p24uslctssvjm06q5phz4yrxucgnv'
 BECH32_INVALID_BECH32 = 'bcrt1p0xlxvlhemja6c4dqv22uapctqupfhlxm9h8z3k2e72q4k9hcz7vqdmchcc'
```

**Comment by sipa** [comment]
@jnewbery Thanks, fixed!

**Comment by sipa** [comment]
Updated to mention v0.21.1 in `bips.md`.

**Comment by jnewbery** [comment]
utACK f2195d7c4aa45f5168ec55b14406aeaf970adcb1

Verified the range-diff. Only difference is the versions in bips.md and removing the unnecessary import in rpc_invalid_address_message.py.

**Review by fanquake — APPROVED** [review]
ACK f2195d7c4aa45f5168ec55b14406aeaf970adcb1 - performed the backport, changes look sane. Have not tested extensively.

**Comment by MarcoFalke** [comment]
cherry-pick re-ACK f2195d7c4aa45f5168ec55b14406aeaf970adcb1 , only change is version number in doc/bips and new test commit 🍝

<details><summary>Show signature and timestamp</summary>

Signature:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

cherry-pick re-ACK f2195d7c4aa45f5168ec55b14406aeaf970adcb1 , only change is version number in doc/bips and new test commit 🍝
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEE+rVPoUahrI9sLGYTzit1aX5ppUgFAlwqrYAACgkQzit1aX5p
pUgENwwAh5tTK73Rq9Xgvnt3A3rDkdON3qGFcLPxyZfyEniRgkIpA/bjFwTbRr73
sPw2fJLG3gZtvFLprSns0J+HxYWbBll+c1WWyBD/5Dct/qiDWDOi72E4O5HMD7L5
h+hJunE/jIo5LizuG468HQdiPrqbcM3lUXhwH32ovG8oePLIaEo1CV8gTZpZMdWg
mzW4JdjHVtf5q/zn3XKTOy6v7GoS9F/Z2/GbXAXkHuddU1c9sZtvkoEvGLjHsvPP
QwaWLs0G9XJ7n7SZZPOrX/7TXoMn1klKRMydpwE3ZBl4pKgKRi7Dw2Ccvu9VTiJn
+tVmKRJQS8KMgfZavoCMZ14R6EtloAuSAeOzWYOaKoPQ1KvfGUYumiXWFgWTQ3VC
OJmvifun9GQmY4R25El9S2PRpfCmBRIpRDU8dNXfdOKO+6jnTXFMiHDVoZShJYx7
u/iDzm3GsxdKbu7oQ/vFzF+4RcKdPhIUrxdWUZc3ZzHLxWSRxkjLG8YytmicaA+d
hp61NnXE
=y603
-----END PGP SIGNATURE-----
```

[Timestamp of file with hash `ba4c4b4eae9f449f1acbdb456b67bb75fc44f409fb63b3ab5b9c63aa98bb8190  -`](https://opentimestamps.org/info/?004f70656e54696d657374616d7073000050726f6f6600bf89e2e884e892940108ba4c4b4eae9f449f1acbdb456b67bb75fc44f409fb63b3ab5b9c63aa98bb8190f01002f4f7295336fe6b3df8bf474f2eca0a08fff01011e20e3dcbc4cea5ee490f65b556724408f1046065a134f00834f18389e37266280083dfe30d2ef90c8e2c2b68747470733a2f2f626f622e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267fff010210c16b03bfba759bfd547b5722781f708f120fd6614a9f42924b18a117a77c5015349edc7108f0d2e9b844a6869720e5dd47608f1046065a132f0082a11565bc8be1bf30083dfe30d2ef90c8e2e2d68747470733a2f2f616c6963652e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267fff0104ae44acb55f24de40bc4c1d74738144708f1046065a133f008616a88544597b84d0083dfe30d2ef90c8e232268747470733a2f2f6274632e63616c656e6461722e636174616c6c6178792e636f6df010993606f21c32b2fa1d45aafe8497ee2408f0208ef3f44c7635fadef08f0dd7a8de50b1b5f50827033b303d7419cbb80af1ec4508f1046065935af008fb62cce1d0d864a50083dfe30d2ef90c8e292868747470733a2f2f66696e6e65792e63616c656e6461722e657465726e69747977616c6c2e636f6d)

</details>

**Pull request merged**
