### PR TITLE
Remove not needed clang-format off comments

### PR DESCRIPTION
**Pull request by maflcko**
It seems odd to disable clang-format and force manual formatting when there is no need for it. So remove the clang-format comments and other unneeded comments.

Can be reviewed with `--word-diff-regex=. --ignore-all-space`

Looks like this was initially added in commit d9d79576f423cd9c5cef4547c7e3648dbb339460 to accommodate a linter that has since been removed and replaced by a functional test.

### CODE REVIEW

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/bitcoin/bitcoin/pull/24959/commits/faa9392e7ec5a1c9e26584063bd47a2b18721142

**Comment by MarcoFalke** [comment]
Force pushed to remove an empty line

**Review by fanquake — APPROVED** [review]
ACK fa870e3d4ccd6dfd0a9a8f2c608721a7251114e2

**Comment by laanwj** [comment]
Code review ACK fa870e3d4ccd6dfd0a9a8f2c608721a7251114e2

> Looks like this was initially added in commit https://github.com/bitcoin/bitcoin/commit/d9d79576f423cd9c5cef4547c7e3648dbb339460 to accommodate a linter

Yes, also the table used to have more columns, so the grid based formatting helped make it legible.

**Pull request merged**
