### PR TITLE
Introduce CBlockchain and move CheckBlockHeader

### PR DESCRIPTION
**Pull request by pstratem**
The ultimate goal here is to move all of the consensus functions defined in main.cpp to CBlockchain.

Initially they will all simply be static functions to ensure that the changes are obviously correct.

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
I think you forgot to include the files in git.

**Comment by pstratem** [comment]
Indeed I did

**Comment by jtimon** [comment]
This is a very different approach to libconsensus. I already see chainparams.h, checkpoints and other dependencies that shouldn't be in the consensus module (and libconsensus). This seems more disruptive to my work on libconsensus than segwit (for which I'm waiting to continue proposing more consensus related refactors).
Concept NACK.

**Comment by pstratem** [comment]
@jtimon I think there was a misunderstanding in the intention here.

My goal is simply to more clearly define the interface functions in an effort to separate networking and consensus logic.

The implementing functions should be pure while the interface used by bitcoind/bitcoin-qt would have some state, such as the block index and utxo states as well as which chain we're dealing with (ie ConsensusParams)

**Comment by arowser** [comment]
Can one of the admins verify this patch?

**Comment by sipa** [comment]
I think we need to first have a plan about refactorings in this space. There are too many people with conflicting goals pulling in different directions. Without coordination, I fear we'll end up with partially-completed refactors that are worse than what we've started off with.

**Comment by dcousens** [comment]
> Without coordination, I fear we'll end up with partially-completed refactors that are worse than what we've started off with.

Agreed,  perhaps an this is an article for in-depth technical discussion after the next meeting?

**Comment by dcousens** [comment]
utACK 942a847

**Comment by jtimon** [comment]
@pstratem Encapsulating consensus logic has been a long term goal of mine. I believe you are underestimating how disruptive this PR would be to my previous (but still not reviewed or merged) work in this subject. Let's please take little steps trying to find common ground. I never created the promised "libconsensus plan" document with pictures, but people really really interested have always have the chance to look at my longest branches (thus I assumed nobody was really as interested as they claimed...). Please, feel free to comment on any of my multiple "consensus" closed PRs.

**Comment by TheBlueMatt** [comment]
Needs rebase. Also see related work such as #8969 which attempts to move towards this in a different way - pull everything that isnt CBlockchain out of main.cpp first, then just put everything left in a class.

**Comment by sipa** [comment]
Closing. I think this needs significant rework after #8969 and #9260. Feel free to ask to reopen if you want to pick this up.

**Pull request closed without merging**
