### PR TITLE
Avoid "Unknown command" messages when receiving getaddr on outbound c…

### PR DESCRIPTION
**Pull request by rebroad**
…onnections.

This bug was introduced in #5442

### CODE REVIEW

**Comment by rebroad** [comment]
Yes, it will exit before displaying the "unknown command" message now.

**Comment by jonasschnelli** [comment]
Ah. Right. Wasn't aware of the `else` on L4736.

utACK.

**Comment by jgarzik** [comment]
If we are changing this code, please also log this exceptional event.

concept ACK

**Comment by laanwj** [comment]
Meh. 

a) the message will only appear when debug=net is set
b) at least with the old code it shows that *something* weird is happening, which is the point of verbose net logging (even though the message could be better) - after this patch it's ignored without any logging

**Comment by sipa** [comment]
Don't care.

**Comment by laanwj** [comment]
I don't think this is enough of an improvement to merge, so going to close this.

**Comment by rebroad** [comment]
@laanwj I'd consider this a bugfix rather than an improvement, since "getaddr" clearly is NOT an unknown command.

**Comment by MarcoFalke** [comment]
@rebroad The previous comments say that you are removing a line (interesting to at least some users) from the `debug.log`. Why not keep logging this with a proper message (as @jgarzik  suggests)?

**Comment by rebroad** [comment]
@laanwj @MarcoFalke Amended to address @jgarzik's comment.

**Pull request closed without merging**
