### PR TITLE
build: No need to check for leveldb atomics

### PR DESCRIPTION
**Pull request by theuni**
They're guaranteed with c++11

### CODE REVIEW

**Comment by paveljanik** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/7982/commits/de982901555b3f168a721a8911dc1ce8a51d3f59

**Comment by laanwj** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/7982/commits/de982901555b3f168a721a8911dc1ce8a51d3f59

This reminds me, we should make tinyformat use variadic template as well (TINYFORMAT_USE_VARIADIC_TEMPLATES) if that's not the case yet automatically.

**Comment by laanwj** [comment]
A quick test shows that it auto-detects and uses them automatically, at least on clang 3.9:
```c++
#ifdef TINYFORMAT_USE_VARIADIC_TEMPLATES
#error Using variadic templates
#endif
```
The detection method is a tad outdated though:
```
#   ifdef __GXX_EXPERIMENTAL_CXX0X__
#       define TINYFORMAT_USE_VARIADIC_TEMPLATES
#   endif
```

**Comment by theuni** [comment]
@laanwj Agreed, defining it explicitly couldn't hurt.

**Pull request merged**
