### PR TITLE
wallet, rpc: add BIP44 `account` in `createwallet`

### PR DESCRIPTION
**Pull request by brunoerg**
This PR adds an `account` parameter in `createwallet` RPC. It's the
BIP44 account that will be used in `SetupDescriptorScriptPubKeyMans`
to fetch the descriptors from the external signer.

### CODE REVIEW

**Review by BrandonOdiwuor — COMMENTED** [review]
Concept ACK

**Comment by luke-jr** [comment]
Feels like this could be confused with real/beancounter accounts like we used to support years ago. Maybe `hd_account` or something?

**Comment by achow101** [comment]
I think this might be a better candidate for a `createwalletdescriptor` (#29130) equivalent for external signers rather than continuing to jam more arguments into `createwallet`.

**Comment by brunoerg** [comment]
> Feels like this could be confused with real/beancounter accounts like we used to support years ago. Maybe hd_account or something?

I agree, had same thought. Just changed in latest push.

**Comment by brunoerg** [comment]
> I think this might be a better candidate for a createwalletdescriptor (https://github.com/bitcoin/bitcoin/pull/29130) equivalent for external signers rather than continuing to jam more arguments into createwallet.

You mean have a specific RPC for external signers or extending `createwalletdescriptor`?

**Review by luke-jr — CHANGES_REQUESTED** [review]
Beyond wallet_name, none of the positional parameters make sense as positional, and that goes for this new one too. Migrating this to an options object should probably be done sooner rather than after making the problem worse

**Comment by achow101** [comment]
> You mean have a specific RPC for external signers or extending `createwalletdescriptor`?

Unsure of the final design, but something like `createwalletdescriptor` for external signers seems like it would be useful, and having an account argument in that would probably also make sense. Actually, that might make sense for `createwalletdescriptor` itself.

**Comment by ryanofsky** [comment]
re: https://github.com/bitcoin/bitcoin/pull/29129#issuecomment-1869859432

> I think this might be a better candidate for a `createwalletdescriptor` (#29130) equivalent for external signers rather than continuing to jam more arguments into `createwallet`.

This makes sense, and I added this idea to my list of potential createwalletdescriptor extensions: https://github.com/bitcoin/bitcoin/pull/29130#discussion_r1435607572

But in general, as long as the createwallet `blank` option defaults to false and it creates descriptors by default, probably we should expect `createwallet` and `createwalletdescriptor` to accept some of the same options (and hopefully not duplicate the code implementing those options internally).

In this case, I'm not sure if it will be more common to have single bitcoin core wallets with multiple hd_accounts, or multiple bitcoin core wallets with single hd_accounts? In the latter case, it really does make sense to add the option to `createwallet`. And again as long as `blank` is not false, it seems like it would be useful to merge this PR to be able to control the descriptors that `createwallet` will add.

Also agree very much with luke-jr that it would be good not to allow this option to be passed by position, and instead to add an OBJ_NAMED_PARAMS options parameter instead. It probably makes sense to have a separate PR disallowing the other options from being passed by position as well, especially since 6 of the 7 options are bool values, so very easy to confuse if passed by position.

**Comment by brunoerg** [comment]
> Also agree very much with luke-jr that it would be good not to allow this option to be passed by position, and instead to add an OBJ_NAMED_PARAMS options parameter instead. It probably makes sense to have a separate PR disallowing the other options from being passed by position as well, especially since 6 of the 7 options are bool values, so very easy to confuse if passed by position.

I strongly agree with that. I could turn this draft until we've that.

**Comment by brunoerg** [comment]
Closing for now.

**Pull request closed without merging**
