### PR TITLE
refactor: Feebumper EstimateFeeRate follow-up

### PR DESCRIPTION
**Pull request by adamjonas**
Picking up some of the suggestions in the comments of #16727 including:
https://github.com/bitcoin/bitcoin/pull/16727#discussion_r330547321
https://github.com/bitcoin/bitcoin/pull/16727#discussion_r330549766
https://github.com/bitcoin/bitcoin/pull/16727#discussion_r333209674

### CODE REVIEW

**Comment by MarcoFalke** [comment]
ACK c4d8cc82608106a0518b86cdf855f0fa99164c0e

I don't really understand why we pass wallet pointers everywhere in this file, so you might also change the others if you feel like it. Though, I don't have a strong opinion.

**Comment by promag** [comment]
Code review ACK 66b29848c71c4b3b4dc36ca6d94de829bd533797.

**Comment by MarcoFalke** [comment]
ACK 66b29848c71c4b3b4dc36ca6d94de829bd533797 (looked at the diff on GitHub)

**Comment by laanwj** [comment]
Concept ACK.

N.B. please don't use the word 'refactor' and 'fixes' in one title, it's useful to know from the title whether something is a refactor or bug-fix. It can't be both because a refactor, by definition, is intended to keep behavior exactly the same.

**Comment by fjahr** [comment]
ACK 66b2984 reviewed code

**Pull request merged**
