### PR TITLE
remove the PAIRTYPE macro

### PR DESCRIPTION
**Pull request by benma**
Replace all BOOST_FOREACH and Q_FOREACH loops using it with range
based loops.

### CODE REVIEW

**Comment by practicalswift** [comment]
Concept ACK

**Review by dcousens — APPROVED** [review]

**Comment by fanquake** [comment]
This overlaps with #10193. However given it's a smaller change-set, and not solely about nuking Boost, maybe we can merge it first? Depends on how many other nearly/ready-to-merge PRs it's going to break.

**Comment by benma** [comment]
@fanquake thanks for pointing it out, I wasn't aware of the other PR. This PR removes the macro and some Q_FOREACH loops over the other one, so it's a small difference.

@jtimon can decide, I guess constantly rebasing such a big PR is a pain, so I don't mind for his to go first.

**Review by ryanofsky — COMMENTED** [review]
utACK 2ffa099308e2f3566531e30e5754f83800adbd7d. Nice change. I think it would be good to merge this before #10193 because this change is more targeted and will only make that PR easier to review. I would expect that rebasing #10193 should not be very difficult because most of the commits are scripted.

**Comment by benma** [comment]
@ryanofsky thanks, I addressed all of your feedback.

**Review by ryanofsky — COMMENTED** [review]
utACK 6b50bb066a55d073f870afb12ab57482da725735

**Comment by jtimon** [comment]
Rebasing #10193 isn't hard at all, once I wrote the sed scripts once it's just running them again. The problem with #10193 is that the reverse iterator to replace BOOST_REVERSE_FOREACH isn't working for some reason. So I separated #10502 with the first 3 commits that could be merged right away.
I would really prefer to do this using scripted-diff to make sure the removal is complete, on the other hand, it isn't adding const in the cases where it can like this one.

**Comment by MarcoFalke** [comment]
Needs rebase

**Comment by benma** [comment]
@MarcoFalke rebased.

**Comment by practicalswift** [comment]
utACK b3489576c28e8e38f1321c1090f7342b75f485c0

Very nice!

**Comment by sipa** [comment]
Can you write this as a scripted-diff?

**Comment by jtimon** [comment]
> Can you write this as a scripted-diff?

Can't we just merge https://github.com/bitcoin/bitcoin/pull/10502 instead?
Did anybody read https://github.com/bitcoin/bitcoin/pull/10497#issuecomment-305564105 ?

**Comment by sipa** [comment]
@jtimon Cool!

**Comment by benma** [comment]
As I said before, I don't mind at all to merge #10502 first. Then I don't have to repeat the effort of scripting the diff and after rebase this will simply be removing the macro.

**Comment by laanwj** [comment]
> Can't we just merge #10502 instead?

So: close this in favor of #10502, as it encompasses more and is scripted?

**Comment by MarcoFalke** [comment]
The only difference is that this one puts `auto` in place of
`std::pair<type1, type2>`.

**Comment by benma** [comment]
I think when this PR was started, the other one didn't deal with the Q_FOREACH and removing the pairtype macro (or I was blind ;)). Now that it does, I'll close this PR.

(I don't mind the explicit std::pair annotation).

**Comment by jtimon** [comment]
https://github.com/bitcoin/bitcoin/pull/10193 didn't remove PAIRTYPE until @tjps suggested it in https://github.com/bitcoin/bitcoin/pull/10193#discussion_r111326802

**Pull request closed without merging**
