### PR TITLE
bitcoin-wallet tool: Drop libbitcoin_server.a dependency

### PR DESCRIPTION
**Pull request by ryanofsky**
Dropping the `bitcoin-wallet` dependency on `libbitcoin_server.a` ensures wallet code can't access node global state, avoiding bugs like https://github.com/bitcoin/bitcoin/pull/15557#discussion_r267735431

### CODE REVIEW

**Comment by practicalswift** [comment]
Concept ACK

Decoupling is good.

Somewhat related: #15612 ("Reduce the number of globals used")

**Comment by 251Labs** [comment]
I just left feedback in #15638 pertaining to the newly introduced circular dependencies. I agree with @practicalswift that decoupling is good, but I hope we can do this without introducing new circular dependencies.

**Comment by ryanofsky** [comment]
> I just left feedback in #15638 pertaining to the newly introduced circular dependencies

Thanks, this was addressed some time ago in the other PR.

**Review by jgarzik — APPROVED** [review]
tested ACK.

Cosmetic question/comment:  is the proj moving back towards underscores in variables like old school Unix (`dust_relay_fee`), or sticking with C++ style lower-cased first letter, and no underscores?

**Comment by jnewbery** [comment]
utACK 78a2fb55c97fbc26f7b74c5b1fb999a2aff8ce88. Nice work, Russ.

**Comment by MarcoFalke** [comment]
utACK 78a2fb5

**Comment by MeshCollider** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/15639/commits/78a2fb55c97fbc26f7b74c5b1fb999a2aff8ce88

**Comment by ryanofsky** [comment]
re: https://github.com/bitcoin/bitcoin/pull/15639#pullrequestreview-225022833

> Cosmetic question/comment: is the proj moving back towards underscores in variables like old school Unix 

Pretty much yes. It's documented in the developer notes: https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md#coding-style-general

**Pull request merged**
