### PR TITLE
ci: Move s390x build to cirrus

### PR DESCRIPTION
**Pull request by maflcko**

### CODE REVIEW

**Comment by MarcoFalke** [comment]
It can detect a bug: https://cirrus-ci.com/task/5693953116733440?command=ci#L4686

**Comment by hebasto** [comment]
Concept ACK.

**Comment by hebasto** [comment]
https://cirrus-ci.com/task/5400693085306880?command=ci#L4756:
```
FAIL: qt/test/test_bitcoin-qt
=============================
Unknown host QEMU_IFLA type: 50
Unknown host QEMU_IFLA type: 51
Unknown host QEMU_IFLA type: 50
Unknown host QEMU_IFLA type: 51
Unknown host QEMU_IFLA type: 50
Unknown host QEMU_IFLA type: 51
Unknown QEMU_IFLA_BR type 46
Unknown QEMU_IFLA_BR type 45
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
./qt/test/test_bitcoin-qt: line 2: 116150 Aborted                 (core dumped) qemu-s390x "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-s390x-linux-gnu/src/qt/test/test_bitcoin-qt_orig" "$@"
FAIL qt/test/test_bitcoin-qt (exit status: 134)
```

**Comment by fanquake** [comment]
Concept ACK

**Comment by decryp2kanon** [comment]
Concept ACK

**Comment by decryp2kanon** [comment]
However it seems strange.
```
test_bitcoin-qt_orig: chainparams.cpp:113: CMainParams::CMainParams(): Assertion `consensus.hashGenesisBlock == uint256S("0x000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f")' failed.
```
https://cirrus-ci.com/task/5693953116733440?command=ci#L4748

**Comment by decryp2kanon** [comment]
> https://cirrus-ci.com/task/5400693085306880?command=ci#L4756:

same code
```
FAIL qt/test/test_sugarchain-qt (exit status: 134)
```

**Comment by MarcoFalke** [comment]
Not worth the effort. Let's just remove it

**Pull request closed without merging**
