### PR TITLE
Add erkmos OpenPGP key to gitian downloader keyset

### PR DESCRIPTION
**Pull request by erkmos**
Per request by @jonasschnelli I'm submitting my OpenPGP key.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
I did ask for this because i think it would be useful to have a central and secure place where all gitian build participants place their key. Because we use unrelated <usernames> as gitian sign identity, most keys can't be loaded over a keyserver unless you know at least first and last name or email of the signing identity.

**Comment by jonasschnelli** [comment]
I think we should make sure, that the filename in contrib/gitian-downloader/<key>.pgp matches the gitian sigs username. The background of this is that I'm working (low prio) on a gitian verify app.

**Comment by jonasschnelli** [comment]
`pub  4096R/167FBA47 2015-01-07  Erik Mossberg (erkmos) <erik@etyd.org>`
ACK.

**Comment by laanwj** [comment]
utACK

**Comment by fanquake** [comment]
ACK

**Pull request merged**
