### PR TITLE
mempool: Add the `bypass_feerate_accuracy` option to `testmempoolaccept`

### PR DESCRIPTION
**Pull request by w0xlt**
This PR adds the the `bypass_feerate_accuracy` option to `testmempoolaccept` RPC, which allows skipping the minimum mempool fee rate validation.

This enables testing of HTLC-timeout transactions signed with 0-feerate (with BOLT9 `option_anchors_zero_fee_htlc_tx`).

For more context, check https://github.com/bitcoin/bitcoin/pull/25434#pullrequestreview-1020896809.

Since this PR is built on top of https://github.com/bitcoin/bitcoin/pull/25577 and https://github.com/bitcoin/bitcoin/pull/25434, only the last 4 commits are new here.

### CODE REVIEW

**Comment by ariard** [comment]
Let's say your a LN node receiving a counterparty's signature for a HTLC-timeout (BOLT2's `commitment_signed`). In the optimistic case, this transaction is never going to be broadcast as LN channels don't have a bounded lifetime. This HTLC-timeout is signed with 0-feerate (with `option_anchors_zero_fee_htlc_tx`) and should be aggregated with a fee-bumping input thanks to SIGHASH_SINGLE | SIGHASH_ANYONECANPAY. As the LN node, you would like to know if this transaction respects all the non-final and non-fee checks to broadcast it at anytime in the future, thus avoiding to accept a non-sane input from your counterparty.

@luke-jr are you raising that #7533 should be opened again as a technical approach is more straighforward ? If so I invite you to do so and let contributors evaluate which approach is the better. Or could you qualify more your concerns e.g the maintenance cost or API misusage ?

If you're raising the concern that Lightning shouldn't make safety-critical assumptions on transaction-relay policy, I'll let the burden on you to propose the design of a second-layer to scale bitcoin payments as much decentralized and privacy-preserving (once we have fix all the issues).

**Comment by luke-jr** [comment]
> @luke-jr are you raising that https://github.com/bitcoin/bitcoin/pull/7533 should be opened again as a technical approach is more straighforward ? If so I invite you to do so and let contributors evaluate which approach is the better. Or could you qualify more your concerns e.g the maintenance cost or API misusage ?

@MarcoFalke has already reopened it as #20753.

>If you're raising the concern that Lightning shouldn't make safety-critical assumptions on transaction-relay policy, I'll let the burden on you to propose the design of a second-layer to scale bitcoin payments as much decentralized and privacy-preserving (once we have fix all the issues).

It shouldn't, but that's beside the point I am making here. There's nothing inherent in the original Lightning design that necessarily makes such assumptions...

**Comment by jonatack** [comment]
@w0xlt in the PR description, for reviewers I would suggest (a) mentioning that only the last 3 commits are new here, and (b)  adding a "why" motivation in the PR description, because if the why doesn't make sense then the what probably doesn't matter.

**Comment by w0xlt** [comment]
Rebased on top of https://github.com/bitcoin/bitcoin/pull/25434/commits/a006b8fd5a16c5283c25c4b8d93d96d485896816.

@jonatack I added the suggested information in the PR description.

**Comment by luke-jr** [comment]
>Further, I think an API where the check is explicit rather than relying on error strings is more robust.

Using a different JSON string for no reason is not an improvement.

**Comment by glozow** [comment]
> This HTLC-timeout is signed with 0-feerate (with option_anchors_zero_fee_htlc_tx) and should be aggregated with a fee-bumping input thanks to SIGHASH_SINGLE | SIGHASH_ANYONECANPAY. As the LN node, you would like to know if this transaction respects all the non-final and non-fee checks to broadcast it at anytime in the future

Seems like there isn't a reason to disable the feerate checks altogether. Rather, the better approach is to allow CPFP in the package submitted for testing, and the fee-bump should be included.

**Comment by glozow** [comment]
Closing for now as this builds on #25434 which still needs conceptual review. Can reopen when this is no longer blocked.

**Pull request closed without merging**
