### PR TITLE
[tests] increase timeouts in sendheaders test

### PR DESCRIPTION
**Pull request by jnewbery**
Increases short timeouts in the sendheaders.py test, which were causing intermittent failure when there was disk i/o contention.

We believe the root cause of this was that bitcoind log writes were excessively slow (up to several seconds) when another test was running in parallel and shutdown the node. The wallet flush on shutdown can block disk i/o for several seconds.

Longer term, it may be worth thinking about changing bitcoind LogPrints to write to a circular buffer and have a background thread write from there to disk. For now, let's just make this test less flakey.

@sdaftuar

### CODE REVIEW

**Comment by instagibbs** [comment]
nitting: could you set a constant to that value instead of hunting and pecking for the number in case it changes again?

**Comment by jnewbery** [comment]
@instagibbs good point. `wait_until()` currently defaults to having *no* timeout. I can't see how that's useful - we'd want any timed predicate to eventually time out and fail the test. I propose we change `wait_until()` to have a 60 second timeout by default, and then remove the timeout parameter from almost all calls to `wait_until()` Definition is here: https://github.com/bitcoin/bitcoin/blob/master/test/functional/test_framework/mininode.py#L1360

@sdaftuar @MarcoFalke - thoughts?

**Comment by sdaftuar** [comment]
@jnewbery Makes sense to me; I actually thought we already had a 60 second default and was going to suggest just using that when I saw @instagibbs' comment!

**Comment by jnewbery** [comment]
Updated `wait_until()` to have a default timeout of 60 seconds and removes the explicit timeouts from sendheaders.py

**Comment by instagibbs** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/10365/commits/56befa03ac559ddab95eac4c2167b586dc0d01b9

**Comment by MarcoFalke** [comment]
utACK 56befa0

**Comment by TheBlueMatt** [comment]
utACK 56befa03ac559ddab95eac4c2167b586dc0d01b9 though it might be nice to default the timeout in wait_for_* to float('inf') instead of 60 as well.

**Comment by jnewbery** [comment]
> it might be nice to default the timeout in wait_for_* to float('inf') instead of 60

Which wait_for_ functions are you referring to? The ones in sendheader.py or in mininode.py?
Why is changing the default to float('inf') better?

**Pull request merged**
