### PR TITLE
doc: Remove un-actionable TODO from chainparams.cpp

### PR DESCRIPTION
**Pull request by maflcko**
This can't be fixed by writing code, see discussion in https://github.com/bitcoin/bitcoin/pull/23021/files#r717426632

### CODE REVIEW

**Review by ghost — APPROVED** [review]
ACK https://github.com/bitcoin/bitcoin/pull/23122/commits/fa189621cc79fb72f7e27c76b75ebc00935a751e

Agree with the comment here https://github.com/bitcoin/bitcoin/pull/23021/files#r717426632

**Review by vincenzopalazzo — APPROVED** [review]
ack https://github.com/bitcoin/bitcoin/pull/23122/commits/fa189621cc79fb72f7e27c76b75ebc00935a751e

**Comment by jarolrod** [comment]
ACK fa189621cc79fb72f7e27c76b75ebc00935a751e

**Comment by Sjors** [comment]
Post merge fine with me :-)

**Pull request merged**
