### PR TITLE
[wallet] Remove segwit status check

### PR DESCRIPTION
**Pull request by ghost**
This is #11400 based on the current master.

### CODE REVIEW

**Comment by jnewbery** [comment]
ACK b233db7c0a60cec67252132b911f6a5d4e330128, but please retain the original authorship in the commit message.

#11400 seems abandoned, so I think it's fine to merge this once the commit message is fixed.

**Comment by jl2012** [comment]
@jnewbery @laudaa sorry that I forgot #11400. I don't think you need to revise the commit message just for authorship.

ACK b233db7

**Comment by laudaa** [comment]
@jnewbery I think I managed to do what you've requested. Mind checking again?

**Comment by jnewbery** [comment]
ACK b1a64bc4fff7405f20b8d4a4763427349daccb8f

Since @jl2012 is happy with the commit message, no need to change it.

For future reference, you can do the following to replace the most recent commit message with the commit message from a different commit:

```sh
git commit --amend --C <commit hash>
```

In this case, you'd do:

```sh
git commit --amend -C b8016405d62a3592648267ca97312bae40ae72af # b801640... is jl2012's commit
```

**Comment by promag** [comment]
utACK b1a64bc.

**Comment by MarcoFalke** [comment]
NACK the current commit.

I don't think this works, as it requires that segwit is *always* active on mainnet, as the transactions would otherwise be rejected by your own node based on policy. Note, that your node is not required to be fully synced to create sending transactions.

**Comment by promag** [comment]
@MarcoFalke so it reject everything when in IBD?

**Comment by promag** [comment]
@MarcoFalke essentially this removes `-walletprematurewitness` which is only used in `addwitnessaddress` RPC. Sorry but I don't understand your concern, can you elaborate?

**Comment by MarcoFalke** [comment]
See

https://github.com/bitcoin/bitcoin/blob/45173fa6fca9537abb0a0554f731d14b9f89c456/src/validation.cpp#L561-L564

which implies you can create segwit transactions with this pull request, but not send them.

**Comment by laudaa** [comment]
Rebased again.
Doesn't "-walletprematurewitness" function differently than "-prematurewitness"?

**Comment by laanwj** [comment]
> I don't think this works, as it requires that segwit is always active on mainnet

So this needs to go deeper to ensure that segwit is always enabled on mainnet? After all, it activated, so it makes no sense to reject creation of segwit transactions before being synced to the point where segwit activates.

**Comment by laanwj** [comment]
I'm not sure about the status of this PR. There are some unaddressed concerns. Closing for now, let me know if you start work on it again and I'll reopen.

**Pull request closed without merging**
