### PR TITLE
[RPC] clarify listunspent amount description

### PR DESCRIPTION
**Pull request by instagibbs**

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
ACK, not sure if trivial or not....

**Comment by instagibbs** [comment]
oh right, it changes compiled code, not just a comment.

**Comment by MarcoFalke** [comment]
utACK 3eba88d

**Comment by kallewoof** [comment]
utACK 3eba88d

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/9663/commits/3eba88d44cdfd9d4d2bfc19cd6049d90ee05fc1c

**Pull request merged**
