### PR TITLE
Broadcast address every day, not 9 hours

### PR DESCRIPTION
**Pull request by sipa**
Discovered by @gmaxwell.

### CODE REVIEW

**Review by dcousens — APPROVED** [review]

**Comment by gmaxwell** [comment]
Doesn't actually matter,  9 hours would also be a fine time-- but it wasn't what was intended there.  utACK.

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/10460/commits/010d68e8023a07ff85d58cd1aff80c6a63e8249d

**Comment by practicalswift** [comment]
ACK 010d68e

**Comment by laanwj** [comment]
utACK, though I agree that:

> Doesn't actually matter, 9 hours would also be a fine time

**Pull request merged**
