### PR TITLE
Fix insecure links

### PR DESCRIPTION
**Pull request by rex4539**

### CODE REVIEW

**Comment by fanquake** [comment]
NACK. These links are in upstream files.

**Comment by rex4539** [comment]
Oh, could you please point me to the upstream repo so I can submit the PR there?

**Comment by fanquake** [comment]
https://github.com/bitcoin-core/ctaes. However have already been "fixed" there. See: https://github.com/bitcoin-core/ctaes/pull/13.

**Comment by rex4539** [comment]
Not all, apparently.

https://github.com/bitcoin-core/ctaes/pull/20

**Pull request closed without merging**
