### PR TITLE
contrib/builder-keys/keys.txt: remove unavailable key

### PR DESCRIPTION
**Pull request by RandyMcMillan**

### CODE REVIEW

**Comment by RandyMcMillan** [comment]
synced all other keys with

hkp://keys.openpgp.org,
hkp://keyserver.ubuntu.com,
hkp://pgp.mit.edu

to ensure redundancy:

https://raw.githubusercontent.com/RandyMcMillan/bitcoin/2e7e4ec93b85c54e55fc0cf053bb57c8da079d08/builder-key-sync.log

**Comment by MarcoFalke** [comment]
I think we can remove all keys that were used for gitian builds only and never for a guix build

**Comment by RandyMcMillan** [comment]
additionally - we can setup a ci script that detects when this file changes (PR) and checks that the keys are on public key servers?

**Comment by MarcoFalke** [comment]
I think it only changes rarely, and if it changes, people will check that the key is available. See also https://github.com/bitcoin-core/guix.sigs/issues/133

**Comment by RandyMcMillan** [comment]
> I think we can remove all keys that were used for gitian builds only and never for a guix build

I will cross reference the https://github.com/bitcoin-core/guix.sigs repo - and list any unused keys from the contrib/builder-keys/keys.txt in this PR for discussion and/or removal.

**Review by fanquake — APPROVED** [review]
ACK dddfa028ffa6b6d70e4fae761ecb9477877d8ec2

> I think we can remove all keys that were used for gitian builds only and never for a guix build

I'll follow up with this.

**Pull request merged**
