### PR TITLE
Policy: Move CTxOut::IsDust() to policy.o

### PR DESCRIPTION
**Pull request by jtimon**
Built on top of #5100.
Decouples CTxOut from CFeeRate.
Related to #5071 , now IsDust can become a method of CNodePolicy.

### CODE REVIEW

**Comment by petertodd** [comment]
utACK

**Comment by jtimon** [comment]
Sorry for touching it again, moved to 2 commits instead of 3. Now it shares the first commit with #5180.

**Comment by sipa** [comment]
Untested ACK

**Comment by jtimon** [comment]
I am very sorry for delaying this again, but I'm closing until it's clear how the first step for policy should be. Something I invite reviewers to discuss at #5595 where I've placed some examples.

**Comment by jtimon** [comment]
Reopened. I was waiting for ~~#5595~~ #6068, but no real reason to keep waiting.
I'm also moving CFeeRate out of consensus to policy/fees (previously was necessary for primitives/transaction).

**Comment by jtimon** [comment]
Needs rebase and I'm thinking about moving the functions to the fee estimator (policy/fees) instead of policy/policy, so closing for now.

**Pull request closed without merging**
