### PR TITLE
[wallet] remove minimum total fee option

### PR DESCRIPTION
**Pull request by instagibbs**
It's of questionable use and complicates further wallet improvements.

### CODE REVIEW

**Comment by gmaxwell** [comment]
We had a minimum total fee? Thats useless.. Concept ACK getting rid of it.

**Comment by MarcoFalke** [comment]
Concept ACK. It might be useful in some edge cases, but I don't this this entitles for cluttering the gui and wallet code with this option.

**Comment by sipa** [comment]
utACK. Seems untested even.

**Comment by jonasschnelli** [comment]
Tested ACK 091a9ae21c47ea7c479e58465ff8aaee7a378fc5.
bildschirmfoto 2017-05-17 um 13 30 55

https://bitcoin.jonasschnelli.ch/build/136

**Comment by fanquake** [comment]
utACK 091a9ae
Couldn't seem to find any more related code that should have also been removed.

**Comment by laanwj** [comment]
utACK 091a9ae

**Comment by morcos** [comment]
woohoo!  
sorry i didn't ACK this

**Comment by markblundeberg** [comment]
(note: introduced bug later fixed in #11332)

**Pull request merged**
