### PR TITLE
Update secp256k1 subtree to v0.6.0

### PR DESCRIPTION
**Pull request by achow101**
v0.6.0 was just released, main change is that it has the musig module which #29675 needs.

### CODE REVIEW

**Comment by faisalazuredev** [comment]
merge it

**Comment by hebasto** [comment]
> v0.6.0 was just released, main change is that it has the musig module which #29675 needs.

Should we disable the musig module in this PR and enable it only when it is needed?

**Comment by hebasto** [comment]
> Another included benefit is that the default test iteration count for the secp256k1 `tests` binary has been reduced, which means Bitcoin Core's `ctest` run should speed up (the `tests` binary is the single longest running task currently); see [bitcoin-core/secp256k1#1581](https://github.com/bitcoin-core/secp256k1/pull/1581).

Additionally, the subtree tests can now match `ctest` regex options, such as `-E` or `-R`:
```
$ ctest --test-dir build -j 16 -R secp256k1
```

**Comment by achow101** [comment]
> Should we disable the musig module in this PR and enable it only when it is needed?

Done

**Review by hebasto — APPROVED** [review]
ACK 97235c446e9986ecca09c2a4b78d6c6239853fdb, verified by updating the secp256k1 subtree locally.

**Review by laanwj — APPROVED** [review]
ACK 97235c446e9986ecca09c2a4b78d6c6239853fdb
good to have the secp256k1_memclear commits

**Comment by fanquake** [comment]
Guix Build:
```bash
df8b274bbadabebfc2ec3d28591f6f66a983f2500779fb95016aaef8c728ad8d  guix-build-97235c446e99/output/aarch64-linux-gnu/SHA256SUMS.part
26aeeb60bf02b1d6e1c072a5c42a3ec14165f208efb5f17992f1716c2db7b826  guix-build-97235c446e99/output/aarch64-linux-gnu/bitcoin-97235c446e99-aarch64-linux-gnu-debug.tar.gz
043e16b13eed1ff5b3a1c4ce67309d595fffbdbbd0cd6800221a9eabb84a35eb  guix-build-97235c446e99/output/aarch64-linux-gnu/bitcoin-97235c446e99-aarch64-linux-gnu.tar.gz
3f2b606211c543d8e5639bfdb9cba817bc05aa7dcf5d1a2efe42736c54325a81  guix-build-97235c446e99/output/arm-linux-gnueabihf/SHA256SUMS.part
c869e44c1341e300e6c8f1f0b24ecb1a6961b15b7df18eeb063d216e64cccfde  guix-build-97235c446e99/output/arm-linux-gnueabihf/bitcoin-97235c446e99-arm-linux-gnueabihf-debug.tar.gz
12086906b844d777c0b41e6a1ebc13708bb88b4d624bdc7016d78b92a72c40fa  guix-build-97235c446e99/output/arm-linux-gnueabihf/bitcoin-97235c446e99-arm-linux-gnueabihf.tar.gz
028cdc0410919855767f3719f6765c1de3c3e070fca06031979e192e67608ef4  guix-build-97235c446e99/output/arm64-apple-darwin/SHA256SUMS.part
9b6794e45c8059b31031aed8a46ca5cb6b69bba7a8f52a061da5dac6f44e17c9  guix-build-97235c446e99/output/arm64-apple-darwin/bitcoin-97235c446e99-arm64-apple-darwin-unsigned.tar.gz
8f81e7782059c51bba90f2315042ebb11db47fc8593fc87a0a69891bad3117c9  guix-build-97235c446e99/output/arm64-apple-darwin/bitcoin-97235c446e99-arm64-apple-darwin-unsigned.zip
5b44e06b28f9b74a95af6c3f5b84611be71a89dfe96b13ba828c777950da01bc  guix-build-97235c446e99/output/arm64-apple-darwin/bitcoin-97235c446e99-arm64-apple-darwin.tar.gz
90a64bd370ab497dd7df62054f35df418a29b4f3da1eefee812371a32a93c8ca  guix-build-97235c446e99/output/dist-archive/bitcoin-97235c446e99.tar.gz
08c71713cdcbdc7a4f555ff2c9ac5ffc8d8502a94a91c1a2ace840032f16b238  guix-build-97235c446e99/output/powerpc64-linux-gnu/SHA256SUMS.part
6b60a37a7fe2374463d98ada79e5995e0b0b49f39c5674b33bdd54519aa85dab  guix-build-97235c446e99/output/powerpc64-linux-gnu/bitcoin-97235c446e99-powerpc64-linux-gnu-debug.tar.gz
ad07922d16815e795513c530c61c98a639252dc1a9fb167a24a5ea474a29c6c2  guix-build-97235c446e99/output/powerpc64-linux-gnu/bitcoin-97235c446e99-powerpc64-linux-gnu.tar.gz
a33458431a23769fb5a256700d4a7a8b28e250c9ee0b1084e911e2ffdfdc7c03  guix-build-97235c446e99/output/riscv64-linux-gnu/SHA256SUMS.part
c3eb0152e2e4ff672e18b218735c6108b6cf5534dccde7fc6f449d62ccd528e8  guix-build-97235c446e99/output/riscv64-linux-gnu/bitcoin-97235c446e99-riscv64-linux-gnu-debug.tar.gz
2f857cf68d0911a736634336d0b95a785effad143c9b13c2996fd45a42de9037  guix-build-97235c446e99/output/riscv64-linux-gnu/bitcoin-97235c446e99-riscv64-linux-gnu.tar.gz
92abee9de44018885f083f3c0160f31a1b243e7dc681a8012436107796f978b8  guix-build-97235c446e99/output/x86_64-apple-darwin/SHA256SUMS.part
b234bde1f0cbd12c150b5d6a0e8b8f4e20e10fd3df5ea7b1bd352182dd9bb1bb  guix-build-97235c446e99/output/x86_64-apple-darwin/bitcoin-97235c446e99-x86_64-apple-darwin-unsigned.tar.gz
135da97d62b6a3de0fea0487b7c636d3c893d3b4d7c79ef8fa0f9cfc345d9841  guix-build-97235c446e99/output/x86_64-apple-darwin/bitcoin-97235c446e99-x86_64-apple-darwin-unsigned.zip
d4edd28b01ce906428305dcb533c0df1176a8c39f4654003340a7d6635cedee1  guix-build-97235c446e99/output/x86_64-apple-darwin/bitcoin-97235c446e99-x86_64-apple-darwin.tar.gz
095fa14e84931c98682f0a87a13c554deff943d947b6eee411326a843dea9e3a  guix-build-97235c446e99/output/x86_64-linux-gnu/SHA256SUMS.part
6fe94b66164c88f6ade3295944ef51150dfe1c00d58499f5cd2a7c1112a57a09  guix-build-97235c446e99/output/x86_64-linux-gnu/bitcoin-97235c446e99-x86_64-linux-gnu-debug.tar.gz
e417cab3b7cc210137135ebbac66de859019db805f19d0f417b7c9f751967e3a  guix-build-97235c446e99/output/x86_64-linux-gnu/bitcoin-97235c446e99-x86_64-linux-gnu.tar.gz
5efc23bfc17c69bfddacf42fc08a4ce88e41f5cc7c53d83840d0b22b6c6e2249  guix-build-97235c446e99/output/x86_64-w64-mingw32/SHA256SUMS.part
1b9809ff08e1cfa42587a39299a0d57f39b4af4b5177c624ef079f32640d003f  guix-build-97235c446e99/output/x86_64-w64-mingw32/bitcoin-97235c446e99-win64-debug.zip
1b04b7c1548ea26531d79b1855d186d550c699702543dffe8ec9a2db8c62260c  guix-build-97235c446e99/output/x86_64-w64-mingw32/bitcoin-97235c446e99-win64-setup-unsigned.exe
769fa743cc56fa9966b6b01b069afb134e451b22ef24fd2c39101bb4b369d5a4  guix-build-97235c446e99/output/x86_64-w64-mingw32/bitcoin-97235c446e99-win64-unsigned.tar.gz
0267008bd2c22ed8bbfb52a889152e96136897c3b5c25827f2f95d96c04c44e1  guix-build-97235c446e99/output/x86_64-w64-mingw32/bitcoin-97235c446e99-win64.zip
```

**Pull request merged**
