### PR TITLE
doc: recommend brew install python@3.7 (minimum version)

### PR DESCRIPTION
**Pull request by RandyMcMillan**

### CODE REVIEW

**Comment by fanquake** [comment]
NACK. There's no need to install an old version of Python.

**Review by brunoerg — COMMENTED** [review]
NACK

For me it doesn't make sense to suggest to install the minimum version. I prefer to have users with the most recent one, not the minimum one.

**Comment by RandyMcMillan** [comment]
updated :

```brew install python@3```


https://github.com/bitcoin/bitcoin/blob/b2f2951e51b0be370041ec63527bad8fc0dab3ad/doc/build-osx.md#test-suite-dependencies

**Comment by fanquake** [comment]
NACK - `python` and `python@3` are the same thing (both aliases for python 3.11, which is the current latest version). We can leave these docs as-is, and/or worry about changing them when Python 4 is (never) released. Thanks.

**Comment by RandyMcMillan** [comment]
To maintain consistency across macOS x86 and Arm64 maybe the minimum python3 version should be python@3.8

Screen Shot 2023-02-20 at 1 00 41 PM


ref: https://github.com/bitcoin/bitcoin/pull/26226

**Comment by Sjors** [comment]
@RandyMcMillan maybe make a separate issue about M1 not supporting Python 3.8 (I don't have one, so can't confirm). It's just one of many operating systems we support, but a lot of devs use it so it seems worth looking into.

**Comment by fanquake** [comment]
Thanks, but there is no need to make an issue. There is nothing here that needs to be solved.

**Pull request closed without merging**
