### PR TITLE
Mark my dnsseed as supporting filtering

### PR DESCRIPTION
**Pull request by sipa**

### CODE REVIEW

**Comment by laanwj** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/8247/commits/133deb83dfedb09d1c5c477a01fb12665cbae16f

**Comment by jonasschnelli** [comment]
Tested ACK 133deb83dfedb09d1c5c477a01fb12665cbae16f

**Comment by fanquake** [comment]
utACK 133deb8
<https://github.com/bitcoin/bitcoin/commit/133deb83dfedb09d1c5c477a01fb12665cbae16f>

**Comment by rebroad** [comment]
@jonasschnelli How did you test this please? (I would like to find a way to test if a seed allows filtering)

**Comment by jonasschnelli** [comment]
@rebroad `dig x9.seed.bitcoin.sipa.be` or `dig x11.seed.bitcoin.sipa.be`, etc.

**Pull request merged**
