### PR TITLE
[cleanup] leveldbwrapper becomes more generic 'dbwrapper' module

### PR DESCRIPTION
**Pull request by jgarzik**
See individual commits for step-by-step transformation.

This originates from the conversion from leveldb to sqlite.  Some operations in the wrapper class were not needed, and the 'leveldb' moniker itself is not needed as this is really bitcoin's generic backend database glue layer.

The follow-on changes that build on top of this preparatory step can be seen at https://github.com/jgarzik/bitcoin/tree/2015_sqlite

### CODE REVIEW

**Comment by jmcorgan** [comment]
ACK

**Comment by dcousens** [comment]
ACK. 

As discussed on IRC, the `wrapper` name is misleading as this object maintains ownership over the underlying database object.  Not a blocker to this PR,  problem existed in the previous name.

@jgarzik any thoughts on whether the path argument is relevant to the API?  Its relevant to the current underlying implementation (leveldb), but if the idea is to allow expansion to other data models, its likely it won't always be relevant.

**Comment by btcdrak** [comment]
utACK

**Comment by jonasschnelli** [comment]
Nice!
UtACK

**Comment by MarcoFalke** [comment]
utACK

**Comment by pstratem** [comment]
utACK

**Comment by laanwj** [comment]
Great idea.
concept ACK (only quickly skimmed over it)

**Pull request merged**
