### PR TITLE
fixed typo in comment, iff -> if

### PR DESCRIPTION
**Pull request by bblarney**
Fixed typo in a comment, changed from 'iff' to 'if'

### CODE REVIEW

**Comment by jtimon** [comment]
ACK

**Comment by Empact** [comment]
`iff` has special meaning in computer science: "if and only if". Not sure whether that meaning applies here but I presume it does.

**Comment by laanwj** [comment]
I'm pretty sure this is not a typo.
FWIW: This particular comment was added by @morcos in 2fffaa97381f741786fff2e6ff25f4b9a74037fe.

**Comment by meshcollider** [comment]
As above, I don't think it's a typo

**Comment by kallewoof** [comment]
This is not a typo.

**Pull request closed without merging**
