### PR TITLE
[WIP] Backports for 0.10.5 (updated to 93ca5a3)

### PR DESCRIPTION
**Pull request by luke-jr**

### CODE REVIEW

**Comment by MarcoFalke** [comment]
#7259 could make sense for 0.10.5, imo.

**Comment by MarcoFalke** [comment]
utACK 0d43146. Note: This also includes OP_CHECKLOCKTIMEVERIFY, which is not in 0.12.0

**Comment by luke-jr** [comment]
> Note: This also includes OP_CHECKLOCKTIMEVERIFY, which is not in 0.12.0

??? How is it not in 0.12.0?

**Comment by MarcoFalke** [comment]
> [probably won't release this until v0.13](https://github.com/bitcoin/bitcoin/pull/7213#issuecomment-164573732)

**Comment by MarcoFalke** [comment]
Has a merge conflict.

**Comment by MarcoFalke** [comment]
Also https://bitcoincore.org/en/lifecycle/ says 0.10 Maintenance End was `2016-02-29`; so is this pull kept open for interested developers/users but not merged?

Related fun fact: `0.10.4` is not yet released: https://github.com/bitcoin/bitcoin/issues/7595#issuecomment-191228818

**Comment by luke-jr** [comment]
@MarcoFalke The website is wrong for Maint. End.

**Comment by arowser** [comment]
Can one of the admins verify this patch?

**Comment by laanwj** [comment]
Needs rebase.

**Pull request closed without merging**
