### PR TITLE
Avoid `interface` keyword to fix windows gitian build

### PR DESCRIPTION
**Pull request by ryanofsky**
Rename `interface` to `interfaces`

Build failure reported by ken2812221 in https://github.com/bitcoin/bitcoin/pull/10244#issuecomment-379434756

### CODE REVIEW

**Comment by laanwj** [comment]
utACK

**Comment by ryanofsky** [comment]
> Anyone have an idea why this didn't cause a problem in the Travis win build?

I don't know the specific answer, but I guess there are just different headers or versions of headers used in the two builds. There is some information about the headers that `#define interface struct` at https://stackoverflow.com/questions/25234203/what-is-the-interface-keyword-in-msvc and
https://social.msdn.microsoft.com/forums/vstudio/en-US/06bf1dea-1d20-4ec3-b9a1-3d673d7fcd8d/what-is-the-interface-keyword-in-native-c

**Comment by laanwj** [comment]
Ah yes for COM, of course.
We could also avoid this by not including the windows headers except in platform-specific utility compilation units. But meh.

**Comment by MarcoFalke** [comment]
Imo, a scripted diff should not (explicitly) modify the content of `.git`. Mind removing the `git` from the first command?

**Comment by ken2812221** [comment]
@laanwj  I think travis win build does not build qt part

**Comment by laanwj** [comment]
> @laanwj I think travis win build does not build qt part

Oh yes that could be true.

Does this fix your build problem?

**Comment by ryanofsky** [comment]
> Imo, a scripted diff should not (explicitly) modify the content of .git. Mind removing the git from the first command?

Currently, if you rename files in a scripted diff or add new files, you are required to update the git index, otherwise the `git diff` command which verifies the script will fail because it doesn't see the new paths. (To confirm this you can check out the PR, amend `git mv` to `mv` and run `contrib/devtools/commit-script-check.sh HEAD^..HEAD`, which will fail.)

I actually think this is a good thing. Scripts that keep the git index up to date are easier to edit and manually verify since you can paste them into your shell and run normal git commit/diff commands afterwards without having to first manually trawl the working directory to discover new paths.

If you really wanted to make the verifier automatically detect new paths, you could do it by adding a line like `git add -N $(git diff-tree --no-commit-id --diff-filter=A --name-only -r HEAD)`, but I think this would just be complicating it, and complicating manual verification and editing for no benefit.

**Comment by MarcoFalke** [comment]
utACK 17780d6f35a3951f649c3b7766b9283d9c18e39f

**Comment by MarcoFalke** [comment]
Thanks for the clarification @ryanofsky

**Comment by ken2812221** [comment]
Tested ACK 17780d6

**Comment by MarcoFalke** [comment]
Tested ACK 17780d6f35a3951f649c3b7766b9283d9c18e39f

**Pull request merged**
