### PR TITLE
doc: correct versions in dependencies.md

### PR DESCRIPTION
**Pull request by fanquake**

### CODE REVIEW

**Comment by MarcoFalke** [comment]
utACK ea384681a4c04ecf2904974a71b887b99c43bea7

**Comment by Sjors** [comment]
ACK ea38468

What's the reason `freetype`, `libevent`, `libICE`, `libSM`, `libX11`, `libXau`, etc. aren't listed? Are they sub-dependencies?

**Comment by laanwj** [comment]
> What's the reason freetype, libevent, libICE, libSM, libX11, libXau, etc. aren't listed? Are they sub-dependencies?

libevent is listed, and it should be, as we use the directly for RPC http.

The others are indeed indirect, anecdotally I've been able to run bitcoin-qt on Wayland on Linux without them, and you'll certainly be able to run without them on MacOS/Windows. They're possible dependencies of Qt, not of our code.

**Comment by laanwj** [comment]
On the other hand this lists libjpeg/libpng as well, which aren't directly used by our code either. Though they are required on every OS/WM at least because we ship jpg and png images...

**Comment by laanwj** [comment]
anyhow utACK 322d34ef65d5f1c6b58e7bd3fb3cd008d7983167

**Pull request merged**
