### PR TITLE
[trivial] Use log.info() instead of print() in remaining functional test cases.

### PR DESCRIPTION
**Pull request by jnewbery**
#9818 was opened before we had logging in the test framework and added a print() call to importmulti.py. log.info() is preferred now that we have logging in the test framework.

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
utACK 1f7065367c6e901f1f047f4bc0ce63633fd7602b
Looks like there are additional prints in nulldummy.py and proxy_test.

**Comment by jnewbery** [comment]
Thanks @TheBlueMatt . I originally didn't add logging to proxy_test.py because it was printing in __int__(), which is before logging has been set up. Looking a bit closer, it's very easy to move the logic from __init__() into setup_nodes(), which I think is where it belongs.

nulldummy.py was just an oversight.

I'll squash these commits once they've been reviewed.

**Comment by laanwj** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/10024/commits/e722777a4974272fe5d0bd06364aa887b599922b

**Comment by MarcoFalke** [comment]
utACK e722777

**Pull request merged**
