### PR TITLE
cmake: Revamp `FindLibevent` module

### PR DESCRIPTION
**Pull request by hebasto**
This PR generalizes the use of `find_package` / `pkg_check_modules`, prioritizing the former.

Addresses https://github.com/bitcoin/bitcoin/pull/30903#issuecomment-2444700876:
> We should also follow up with refactoring the libevent module, to more generically use CMake/pkg-config, rather than restricting the CMake usage to `vcpkg`. At that point, we'd likely be able to dump pkg-config for the depends path entirely.

Similar to https://github.com/bitcoin/bitcoin/pull/30903.

### CODE REVIEW

**Comment by fanquake** [comment]
Can you rebase this.

**Comment by hebasto** [comment]
> Can you rebase this.

Sure. Rebased.

**Comment by hebasto** [comment]
My Guix build:
```
aarch64
c448a9c8d6d436350846ccb998e6a5e2bb66ac519e3539188c4792c6a88f4a1c  guix-build-a6a3cab235cf/output/aarch64-linux-gnu/SHA256SUMS.part
613ef63f92fdf0422179fdedad230a7b8c5eb1530c892745bd2d5e76e8fb580c  guix-build-a6a3cab235cf/output/aarch64-linux-gnu/bitcoin-a6a3cab235cf-aarch64-linux-gnu-debug.tar.gz
2d77932ce9f8808f9673420320faaf9b20d910595f3d3d65687b5cbc55cb84dd  guix-build-a6a3cab235cf/output/aarch64-linux-gnu/bitcoin-a6a3cab235cf-aarch64-linux-gnu.tar.gz
73019d4fb0f4e54828f70383c769d578112e85c028892ae9bcffa64e0a744a98  guix-build-a6a3cab235cf/output/arm-linux-gnueabihf/SHA256SUMS.part
cb1d13753ef47508cfd8b06c95668580c6c17cc64c852f05379eb0523fbfbf5e  guix-build-a6a3cab235cf/output/arm-linux-gnueabihf/bitcoin-a6a3cab235cf-arm-linux-gnueabihf-debug.tar.gz
47d5a87c465dbfbf1ebc94ac45ad54b8ce12bced200ed8e9d1a3a0b9e10029d3  guix-build-a6a3cab235cf/output/arm-linux-gnueabihf/bitcoin-a6a3cab235cf-arm-linux-gnueabihf.tar.gz
2bcd4e7933c0a2492714b336d1a71abfef159663e0be24df62513841bdd1e8dc  guix-build-a6a3cab235cf/output/arm64-apple-darwin/SHA256SUMS.part
c2ea0008a1eec8d321d9fe1d3444a1c94168e26925b4f9aeb602e781d2f277c4  guix-build-a6a3cab235cf/output/arm64-apple-darwin/bitcoin-a6a3cab235cf-arm64-apple-darwin-unsigned.tar.gz
296f22f2abd6b87aebe37957073adf6527e92349ef76c973a0015455cb645738  guix-build-a6a3cab235cf/output/arm64-apple-darwin/bitcoin-a6a3cab235cf-arm64-apple-darwin-unsigned.zip
9c53fe999e9c8cb392273cec4052e6ba0e1a4d926058ffb1dfb2f79d96f9f61a  guix-build-a6a3cab235cf/output/arm64-apple-darwin/bitcoin-a6a3cab235cf-arm64-apple-darwin.tar.gz
7ac751b56e8820478c17c7701ed46a9291a642317d7dc5226712f14037442681  guix-build-a6a3cab235cf/output/dist-archive/bitcoin-a6a3cab235cf.tar.gz
5bc0ce74d6baaed0b9a71edd2142c12c51af50e49e4a3e561ca574630c15c1f7  guix-build-a6a3cab235cf/output/powerpc64-linux-gnu/SHA256SUMS.part
08bee7dc7a9b3afe0e8cd277b9647056b39bec94e868265f935b41b2c8bdad54  guix-build-a6a3cab235cf/output/powerpc64-linux-gnu/bitcoin-a6a3cab235cf-powerpc64-linux-gnu-debug.tar.gz
29595c9dfe155009ffaf6e5d4701e52c6e735f6bb8dbe7f1a939604ea1c0d72d  guix-build-a6a3cab235cf/output/powerpc64-linux-gnu/bitcoin-a6a3cab235cf-powerpc64-linux-gnu.tar.gz
9177685189978221038172865d0d7560ebee5f8a856908d7e955e2c4016fdffb  guix-build-a6a3cab235cf/output/riscv64-linux-gnu/SHA256SUMS.part
80ed63afed14e7183e11ae6d214288ded481853f1c25377986145a6aa9a8ea29  guix-build-a6a3cab235cf/output/riscv64-linux-gnu/bitcoin-a6a3cab235cf-riscv64-linux-gnu-debug.tar.gz
e3415ba90273004c8c0faf11cf96570b838d2b4aa04e5c3e2e74b85e1507bfc3  guix-build-a6a3cab235cf/output/riscv64-linux-gnu/bitcoin-a6a3cab235cf-riscv64-linux-gnu.tar.gz
07ae8d18a95806e8061aa9e29151c8c6f786a8c9e0ee2c8c3f91c88fafb54d65  guix-build-a6a3cab235cf/output/x86_64-apple-darwin/SHA256SUMS.part
f39dd6779d72b4054a6467c2c5cd88d7e9971604a851501c2a5d809b531a2f11  guix-build-a6a3cab235cf/output/x86_64-apple-darwin/bitcoin-a6a3cab235cf-x86_64-apple-darwin-unsigned.tar.gz
891e34c0d16b538d5817fc71e50746b0a09aa083f7edc5d3a744a668f582fb2a  guix-build-a6a3cab235cf/output/x86_64-apple-darwin/bitcoin-a6a3cab235cf-x86_64-apple-darwin-unsigned.zip
dab234ff1e2838a50a08b78d53a5542d535890603737cf41a7946709591aba74  guix-build-a6a3cab235cf/output/x86_64-apple-darwin/bitcoin-a6a3cab235cf-x86_64-apple-darwin.tar.gz
1786396653240ff3cf1125f8c50ddf606135717514bf1a8a612de04483df5854  guix-build-a6a3cab235cf/output/x86_64-linux-gnu/SHA256SUMS.part
945a49f969ad8da9efbf86c2c5f228c4872eebff3dd494f9712c074eba2003dd  guix-build-a6a3cab235cf/output/x86_64-linux-gnu/bitcoin-a6a3cab235cf-x86_64-linux-gnu-debug.tar.gz
461c91b543a1590a492249c3f72f9317ece3c31545c04b8b5f6f184c1155c5f9  guix-build-a6a3cab235cf/output/x86_64-linux-gnu/bitcoin-a6a3cab235cf-x86_64-linux-gnu.tar.gz
a0f23a0bd73f6a8a101613296b7a0d60151fe5333904658c13f70d8ce611d663  guix-build-a6a3cab235cf/output/x86_64-w64-mingw32/SHA256SUMS.part
22e92eb5929864f666940ac3342b3eef5ee11b9b96adc45397f8c2708903e0a5  guix-build-a6a3cab235cf/output/x86_64-w64-mingw32/bitcoin-a6a3cab235cf-win64-debug.zip
df3e31e1c644fc027cc884171b2f4454a895b09917df89b02357c9a6e1da99b3  guix-build-a6a3cab235cf/output/x86_64-w64-mingw32/bitcoin-a6a3cab235cf-win64-setup-unsigned.exe
77b454372ccec46833b7be52c240a21b3e694cf05e7f6d23a37d95d12369e05f  guix-build-a6a3cab235cf/output/x86_64-w64-mingw32/bitcoin-a6a3cab235cf-win64-unsigned.tar.gz
05b1385a21d2c1b48cb80e9c97c0c221fca5e341dd4838f03f8abe4fdb7b7b0b  guix-build-a6a3cab235cf/output/x86_64-w64-mingw32/bitcoin-a6a3cab235cf-win64.zip
```

**Comment by fanquake** [comment]
Guix build:
```bash
c448a9c8d6d436350846ccb998e6a5e2bb66ac519e3539188c4792c6a88f4a1c  guix-build-a6a3cab235cf/output/aarch64-linux-gnu/SHA256SUMS.part
613ef63f92fdf0422179fdedad230a7b8c5eb1530c892745bd2d5e76e8fb580c  guix-build-a6a3cab235cf/output/aarch64-linux-gnu/bitcoin-a6a3cab235cf-aarch64-linux-gnu-debug.tar.gz
2d77932ce9f8808f9673420320faaf9b20d910595f3d3d65687b5cbc55cb84dd  guix-build-a6a3cab235cf/output/aarch64-linux-gnu/bitcoin-a6a3cab235cf-aarch64-linux-gnu.tar.gz
73019d4fb0f4e54828f70383c769d578112e85c028892ae9bcffa64e0a744a98  guix-build-a6a3cab235cf/output/arm-linux-gnueabihf/SHA256SUMS.part
cb1d13753ef47508cfd8b06c95668580c6c17cc64c852f05379eb0523fbfbf5e  guix-build-a6a3cab235cf/output/arm-linux-gnueabihf/bitcoin-a6a3cab235cf-arm-linux-gnueabihf-debug.tar.gz
47d5a87c465dbfbf1ebc94ac45ad54b8ce12bced200ed8e9d1a3a0b9e10029d3  guix-build-a6a3cab235cf/output/arm-linux-gnueabihf/bitcoin-a6a3cab235cf-arm-linux-gnueabihf.tar.gz
2bcd4e7933c0a2492714b336d1a71abfef159663e0be24df62513841bdd1e8dc  guix-build-a6a3cab235cf/output/arm64-apple-darwin/SHA256SUMS.part
c2ea0008a1eec8d321d9fe1d3444a1c94168e26925b4f9aeb602e781d2f277c4  guix-build-a6a3cab235cf/output/arm64-apple-darwin/bitcoin-a6a3cab235cf-arm64-apple-darwin-unsigned.tar.gz
296f22f2abd6b87aebe37957073adf6527e92349ef76c973a0015455cb645738  guix-build-a6a3cab235cf/output/arm64-apple-darwin/bitcoin-a6a3cab235cf-arm64-apple-darwin-unsigned.zip
9c53fe999e9c8cb392273cec4052e6ba0e1a4d926058ffb1dfb2f79d96f9f61a  guix-build-a6a3cab235cf/output/arm64-apple-darwin/bitcoin-a6a3cab235cf-arm64-apple-darwin.tar.gz
7ac751b56e8820478c17c7701ed46a9291a642317d7dc5226712f14037442681  guix-build-a6a3cab235cf/output/dist-archive/bitcoin-a6a3cab235cf.tar.gz
5bc0ce74d6baaed0b9a71edd2142c12c51af50e49e4a3e561ca574630c15c1f7  guix-build-a6a3cab235cf/output/powerpc64-linux-gnu/SHA256SUMS.part
08bee7dc7a9b3afe0e8cd277b9647056b39bec94e868265f935b41b2c8bdad54  guix-build-a6a3cab235cf/output/powerpc64-linux-gnu/bitcoin-a6a3cab235cf-powerpc64-linux-gnu-debug.tar.gz
29595c9dfe155009ffaf6e5d4701e52c6e735f6bb8dbe7f1a939604ea1c0d72d  guix-build-a6a3cab235cf/output/powerpc64-linux-gnu/bitcoin-a6a3cab235cf-powerpc64-linux-gnu.tar.gz
9177685189978221038172865d0d7560ebee5f8a856908d7e955e2c4016fdffb  guix-build-a6a3cab235cf/output/riscv64-linux-gnu/SHA256SUMS.part
80ed63afed14e7183e11ae6d214288ded481853f1c25377986145a6aa9a8ea29  guix-build-a6a3cab235cf/output/riscv64-linux-gnu/bitcoin-a6a3cab235cf-riscv64-linux-gnu-debug.tar.gz
e3415ba90273004c8c0faf11cf96570b838d2b4aa04e5c3e2e74b85e1507bfc3  guix-build-a6a3cab235cf/output/riscv64-linux-gnu/bitcoin-a6a3cab235cf-riscv64-linux-gnu.tar.gz
07ae8d18a95806e8061aa9e29151c8c6f786a8c9e0ee2c8c3f91c88fafb54d65  guix-build-a6a3cab235cf/output/x86_64-apple-darwin/SHA256SUMS.part
f39dd6779d72b4054a6467c2c5cd88d7e9971604a851501c2a5d809b531a2f11  guix-build-a6a3cab235cf/output/x86_64-apple-darwin/bitcoin-a6a3cab235cf-x86_64-apple-darwin-unsigned.tar.gz
891e34c0d16b538d5817fc71e50746b0a09aa083f7edc5d3a744a668f582fb2a  guix-build-a6a3cab235cf/output/x86_64-apple-darwin/bitcoin-a6a3cab235cf-x86_64-apple-darwin-unsigned.zip
dab234ff1e2838a50a08b78d53a5542d535890603737cf41a7946709591aba74  guix-build-a6a3cab235cf/output/x86_64-apple-darwin/bitcoin-a6a3cab235cf-x86_64-apple-darwin.tar.gz
1786396653240ff3cf1125f8c50ddf606135717514bf1a8a612de04483df5854  guix-build-a6a3cab235cf/output/x86_64-linux-gnu/SHA256SUMS.part
945a49f969ad8da9efbf86c2c5f228c4872eebff3dd494f9712c074eba2003dd  guix-build-a6a3cab235cf/output/x86_64-linux-gnu/bitcoin-a6a3cab235cf-x86_64-linux-gnu-debug.tar.gz
461c91b543a1590a492249c3f72f9317ece3c31545c04b8b5f6f184c1155c5f9  guix-build-a6a3cab235cf/output/x86_64-linux-gnu/bitcoin-a6a3cab235cf-x86_64-linux-gnu.tar.gz
a0f23a0bd73f6a8a101613296b7a0d60151fe5333904658c13f70d8ce611d663  guix-build-a6a3cab235cf/output/x86_64-w64-mingw32/SHA256SUMS.part
22e92eb5929864f666940ac3342b3eef5ee11b9b96adc45397f8c2708903e0a5  guix-build-a6a3cab235cf/output/x86_64-w64-mingw32/bitcoin-a6a3cab235cf-win64-debug.zip
df3e31e1c644fc027cc884171b2f4454a895b09917df89b02357c9a6e1da99b3  guix-build-a6a3cab235cf/output/x86_64-w64-mingw32/bitcoin-a6a3cab235cf-win64-setup-unsigned.exe
77b454372ccec46833b7be52c240a21b3e694cf05e7f6d23a37d95d12369e05f  guix-build-a6a3cab235cf/output/x86_64-w64-mingw32/bitcoin-a6a3cab235cf-win64-unsigned.tar.gz
05b1385a21d2c1b48cb80e9c97c0c221fca5e341dd4838f03f8abe4fdb7b7b0b  guix-build-a6a3cab235cf/output/x86_64-w64-mingw32/bitcoin-a6a3cab235cf-win64.zip
```

**Comment by hebasto** [comment]
> Tested on Arch, which is one of the few distros that ship CMake config files for `libevent-dev`. You could add this diff:
> 
> ```diff
> diff --git a/doc/build-unix.md b/doc/build-unix.md
> index a5ad4df11d..4f04b4fd9f 100644
> --- a/doc/build-unix.md
> +++ b/doc/build-unix.md
> @@ -182,7 +182,7 @@ Setup and Build Example: Arch Linux
>  -----------------------------------
>  This example lists the steps necessary to setup and build a command line only distribution of the latest changes on Arch Linux:
>  
> -    pacman --sync --needed cmake boost gcc git libevent make pkgconf python sqlite
> +    pacman --sync --needed cmake boost gcc git libevent make python sqlite
>      git clone https://github.com/bitcoin/bitcoin.git
>      cd bitcoin/
>      cmake -B build
> ```

Thanks! Updated.

**Comment by hebasto** [comment]
My Guix build:
```
aarch64
b526b46943f39780cb2a204cd64159f7dd4f502e482256ba78371c82d717a591  guix-build-5a96767e3f53/output/aarch64-linux-gnu/SHA256SUMS.part
77714a2034b96c572598342da2147a638abd626b29e4ccecfe786f53dbf72a4e  guix-build-5a96767e3f53/output/aarch64-linux-gnu/bitcoin-5a96767e3f53-aarch64-linux-gnu-debug.tar.gz
a32ce8d85863ec00f75b37ab7b10bfc37e85efd3a1016ed66ce6cbd0024d018a  guix-build-5a96767e3f53/output/aarch64-linux-gnu/bitcoin-5a96767e3f53-aarch64-linux-gnu.tar.gz
751eba9ba4c9c2432018854a9064bcc24a7cde4236247da7ecf0c09d6ad4d998  guix-build-5a96767e3f53/output/arm-linux-gnueabihf/SHA256SUMS.part
e5c5d79fe4da7183009207e4c229a0da6d10da8b293c7309ff45b99b2d18dd78  guix-build-5a96767e3f53/output/arm-linux-gnueabihf/bitcoin-5a96767e3f53-arm-linux-gnueabihf-debug.tar.gz
258f63b89ef5cb5f425fd3c1e979e355608ab40272304fd04314acdf1f07397d  guix-build-5a96767e3f53/output/arm-linux-gnueabihf/bitcoin-5a96767e3f53-arm-linux-gnueabihf.tar.gz
6b79c89ce6e36cc46db4a50e1635e42751e2323227ae3b0b2f4012ce8fa40489  guix-build-5a96767e3f53/output/arm64-apple-darwin/SHA256SUMS.part
e8bd0927f1986eda76ff8da3ac966b8df5a847936fe15f6fe1ad2565ccf81de7  guix-build-5a96767e3f53/output/arm64-apple-darwin/bitcoin-5a96767e3f53-arm64-apple-darwin-unsigned.tar.gz
6705d70f0318d146aa4e264dd561eda53166d6ebacc60602f96a02549b0f8971  guix-build-5a96767e3f53/output/arm64-apple-darwin/bitcoin-5a96767e3f53-arm64-apple-darwin-unsigned.zip
a5feee710b316d2f2f6b43bfd55d4712d3513e5f56dd80d823b63fb90e74e52f  guix-build-5a96767e3f53/output/arm64-apple-darwin/bitcoin-5a96767e3f53-arm64-apple-darwin.tar.gz
e2d8c8b6f14bc44086cc6e152d80dd7fe9af4f501038dcffefded43f60c0c78b  guix-build-5a96767e3f53/output/dist-archive/bitcoin-5a96767e3f53.tar.gz
3e87fe8a89bd6ed809ca4ab77308999f84a3eb4cc4aa97a3de67925e93f193de  guix-build-5a96767e3f53/output/powerpc64-linux-gnu/SHA256SUMS.part
5de169c0431a5dd1efab9ea88dd5fc87c5f985adf1a87c796e6eaa154d241fdb  guix-build-5a96767e3f53/output/powerpc64-linux-gnu/bitcoin-5a96767e3f53-powerpc64-linux-gnu-debug.tar.gz
78333296ce7fc88882a71b1a2b03d8544ee9413516f322aa685e2e3c9c47abbe  guix-build-5a96767e3f53/output/powerpc64-linux-gnu/bitcoin-5a96767e3f53-powerpc64-linux-gnu.tar.gz
02e5ec367182a54814509f2c640cb8951341b63a7a510e2fe12f3c98f5829f8e  guix-build-5a96767e3f53/output/riscv64-linux-gnu/SHA256SUMS.part
239329403da2775bb5b3b8b73bd1fa9613a19852b30801e819cb39e5700ce495  guix-build-5a96767e3f53/output/riscv64-linux-gnu/bitcoin-5a96767e3f53-riscv64-linux-gnu-debug.tar.gz
7d9bf2f6c19455bfe8a94770ad10d71d73cabe3833e511b84e4da2b2bec9fa4d  guix-build-5a96767e3f53/output/riscv64-linux-gnu/bitcoin-5a96767e3f53-riscv64-linux-gnu.tar.gz
ba16d9bbbbafe29f39d8b733fe090725c24ae8a095a6454bfaaea8be2103025d  guix-build-5a96767e3f53/output/x86_64-apple-darwin/SHA256SUMS.part
a8907b52a882730062f2312e349c52e399215b76c6cff231ad550214ae52b807  guix-build-5a96767e3f53/output/x86_64-apple-darwin/bitcoin-5a96767e3f53-x86_64-apple-darwin-unsigned.tar.gz
e963cd3623bee1e79e7de260cc5347d203926a5a7da51dab97650ef8f3597f49  guix-build-5a96767e3f53/output/x86_64-apple-darwin/bitcoin-5a96767e3f53-x86_64-apple-darwin-unsigned.zip
6e6194b28563fb4bfa2840265ee783e282684df08b773919d4b78cd88e37ce78  guix-build-5a96767e3f53/output/x86_64-apple-darwin/bitcoin-5a96767e3f53-x86_64-apple-darwin.tar.gz
f84f236918aaae68c7a036bfcc4cd6e643b449ace6812f8fcb2ad3e6aa60fd89  guix-build-5a96767e3f53/output/x86_64-linux-gnu/SHA256SUMS.part
a35b69c56c97b8aa308a2893471712200646ec4b0d469828506059668044e05d  guix-build-5a96767e3f53/output/x86_64-linux-gnu/bitcoin-5a96767e3f53-x86_64-linux-gnu-debug.tar.gz
d8daf3cb7bf4e6a18e1312bedc0383b5a1676c16c723330f187c1cf2cccdf4e1  guix-build-5a96767e3f53/output/x86_64-linux-gnu/bitcoin-5a96767e3f53-x86_64-linux-gnu.tar.gz
4b7790e70a57d5d9c8dd167ebde956be0e8fd8819ff3374866869619fad5deea  guix-build-5a96767e3f53/output/x86_64-w64-mingw32/SHA256SUMS.part
1c051bbe9f6958f2cd91cb20e47fc0778a8e3877f034fd97b37b6a78f22b64ea  guix-build-5a96767e3f53/output/x86_64-w64-mingw32/bitcoin-5a96767e3f53-win64-debug.zip
b00ef4ad4fcad2da810b7900834256d8b56a575705f6a5ee5e124075ee9ce3ec  guix-build-5a96767e3f53/output/x86_64-w64-mingw32/bitcoin-5a96767e3f53-win64-setup-unsigned.exe
7f6bb43d931a8a62a5cfdd3d7a55b46bace525441e973563dacc71c34fc0aa10  guix-build-5a96767e3f53/output/x86_64-w64-mingw32/bitcoin-5a96767e3f53-win64-unsigned.tar.gz
122fb77cbc223ca67bfecdeef3709dbac291e1df0bbf082d87d94777292d9399  guix-build-5a96767e3f53/output/x86_64-w64-mingw32/bitcoin-5a96767e3f53-win64.zip
```

**Comment by fanquake** [comment]
Guix Build
```bash
b526b46943f39780cb2a204cd64159f7dd4f502e482256ba78371c82d717a591  guix-build-5a96767e3f53/output/aarch64-linux-gnu/SHA256SUMS.part
77714a2034b96c572598342da2147a638abd626b29e4ccecfe786f53dbf72a4e  guix-build-5a96767e3f53/output/aarch64-linux-gnu/bitcoin-5a96767e3f53-aarch64-linux-gnu-debug.tar.gz
a32ce8d85863ec00f75b37ab7b10bfc37e85efd3a1016ed66ce6cbd0024d018a  guix-build-5a96767e3f53/output/aarch64-linux-gnu/bitcoin-5a96767e3f53-aarch64-linux-gnu.tar.gz
751eba9ba4c9c2432018854a9064bcc24a7cde4236247da7ecf0c09d6ad4d998  guix-build-5a96767e3f53/output/arm-linux-gnueabihf/SHA256SUMS.part
e5c5d79fe4da7183009207e4c229a0da6d10da8b293c7309ff45b99b2d18dd78  guix-build-5a96767e3f53/output/arm-linux-gnueabihf/bitcoin-5a96767e3f53-arm-linux-gnueabihf-debug.tar.gz
258f63b89ef5cb5f425fd3c1e979e355608ab40272304fd04314acdf1f07397d  guix-build-5a96767e3f53/output/arm-linux-gnueabihf/bitcoin-5a96767e3f53-arm-linux-gnueabihf.tar.gz
6b79c89ce6e36cc46db4a50e1635e42751e2323227ae3b0b2f4012ce8fa40489  guix-build-5a96767e3f53/output/arm64-apple-darwin/SHA256SUMS.part
e8bd0927f1986eda76ff8da3ac966b8df5a847936fe15f6fe1ad2565ccf81de7  guix-build-5a96767e3f53/output/arm64-apple-darwin/bitcoin-5a96767e3f53-arm64-apple-darwin-unsigned.tar.gz
6705d70f0318d146aa4e264dd561eda53166d6ebacc60602f96a02549b0f8971  guix-build-5a96767e3f53/output/arm64-apple-darwin/bitcoin-5a96767e3f53-arm64-apple-darwin-unsigned.zip
a5feee710b316d2f2f6b43bfd55d4712d3513e5f56dd80d823b63fb90e74e52f  guix-build-5a96767e3f53/output/arm64-apple-darwin/bitcoin-5a96767e3f53-arm64-apple-darwin.tar.gz
e2d8c8b6f14bc44086cc6e152d80dd7fe9af4f501038dcffefded43f60c0c78b  guix-build-5a96767e3f53/output/dist-archive/bitcoin-5a96767e3f53.tar.gz
3e87fe8a89bd6ed809ca4ab77308999f84a3eb4cc4aa97a3de67925e93f193de  guix-build-5a96767e3f53/output/powerpc64-linux-gnu/SHA256SUMS.part
5de169c0431a5dd1efab9ea88dd5fc87c5f985adf1a87c796e6eaa154d241fdb  guix-build-5a96767e3f53/output/powerpc64-linux-gnu/bitcoin-5a96767e3f53-powerpc64-linux-gnu-debug.tar.gz
78333296ce7fc88882a71b1a2b03d8544ee9413516f322aa685e2e3c9c47abbe  guix-build-5a96767e3f53/output/powerpc64-linux-gnu/bitcoin-5a96767e3f53-powerpc64-linux-gnu.tar.gz
02e5ec367182a54814509f2c640cb8951341b63a7a510e2fe12f3c98f5829f8e  guix-build-5a96767e3f53/output/riscv64-linux-gnu/SHA256SUMS.part
239329403da2775bb5b3b8b73bd1fa9613a19852b30801e819cb39e5700ce495  guix-build-5a96767e3f53/output/riscv64-linux-gnu/bitcoin-5a96767e3f53-riscv64-linux-gnu-debug.tar.gz
7d9bf2f6c19455bfe8a94770ad10d71d73cabe3833e511b84e4da2b2bec9fa4d  guix-build-5a96767e3f53/output/riscv64-linux-gnu/bitcoin-5a96767e3f53-riscv64-linux-gnu.tar.gz
ba16d9bbbbafe29f39d8b733fe090725c24ae8a095a6454bfaaea8be2103025d  guix-build-5a96767e3f53/output/x86_64-apple-darwin/SHA256SUMS.part
a8907b52a882730062f2312e349c52e399215b76c6cff231ad550214ae52b807  guix-build-5a96767e3f53/output/x86_64-apple-darwin/bitcoin-5a96767e3f53-x86_64-apple-darwin-unsigned.tar.gz
e963cd3623bee1e79e7de260cc5347d203926a5a7da51dab97650ef8f3597f49  guix-build-5a96767e3f53/output/x86_64-apple-darwin/bitcoin-5a96767e3f53-x86_64-apple-darwin-unsigned.zip
6e6194b28563fb4bfa2840265ee783e282684df08b773919d4b78cd88e37ce78  guix-build-5a96767e3f53/output/x86_64-apple-darwin/bitcoin-5a96767e3f53-x86_64-apple-darwin.tar.gz
f84f236918aaae68c7a036bfcc4cd6e643b449ace6812f8fcb2ad3e6aa60fd89  guix-build-5a96767e3f53/output/x86_64-linux-gnu/SHA256SUMS.part
a35b69c56c97b8aa308a2893471712200646ec4b0d469828506059668044e05d  guix-build-5a96767e3f53/output/x86_64-linux-gnu/bitcoin-5a96767e3f53-x86_64-linux-gnu-debug.tar.gz
d8daf3cb7bf4e6a18e1312bedc0383b5a1676c16c723330f187c1cf2cccdf4e1  guix-build-5a96767e3f53/output/x86_64-linux-gnu/bitcoin-5a96767e3f53-x86_64-linux-gnu.tar.gz
4b7790e70a57d5d9c8dd167ebde956be0e8fd8819ff3374866869619fad5deea  guix-build-5a96767e3f53/output/x86_64-w64-mingw32/SHA256SUMS.part
1c051bbe9f6958f2cd91cb20e47fc0778a8e3877f034fd97b37b6a78f22b64ea  guix-build-5a96767e3f53/output/x86_64-w64-mingw32/bitcoin-5a96767e3f53-win64-debug.zip
b00ef4ad4fcad2da810b7900834256d8b56a575705f6a5ee5e124075ee9ce3ec  guix-build-5a96767e3f53/output/x86_64-w64-mingw32/bitcoin-5a96767e3f53-win64-setup-unsigned.exe
7f6bb43d931a8a62a5cfdd3d7a55b46bace525441e973563dacc71c34fc0aa10  guix-build-5a96767e3f53/output/x86_64-w64-mingw32/bitcoin-5a96767e3f53-win64-unsigned.tar.gz
122fb77cbc223ca67bfecdeef3709dbac291e1df0bbf082d87d94777292d9399  guix-build-5a96767e3f53/output/x86_64-w64-mingw32/bitcoin-5a96767e3f53-win64.zip
```

**Review by fanquake — APPROVED** [review]
ACK 5a96767e3f531ba9e8a676eec47727421f9f589f

**Pull request merged**
