### PR TITLE
Only log time to write coins cache to disk if bench debug enabled

### PR DESCRIPTION
**Pull request by rebroad**
Minor debugging change to only log this if bench debugging is enabled.

### CODE REVIEW

**Comment by fanquake** [comment]
~0. What is the motivation? This is generally useful information to have. You've also changed the file permissions.

**Comment by practicalswift** [comment]
Concept ACK on increasing signal-to-noise for our dear non-developer end-users by making debug style benckmarking output opt-in via `-debug`. The file permission change seems like a mistake though? :)

**Comment by rebroad** [comment]
@fanquake @practicalswift file permissions fixed - I'll keep an eye out for that in future, thanks.

**Comment by practicalswift** [comment]
cr ACK 95942529053554bcdc8c8937356c41a4b78c55d5: patch looks correct

**Comment by jamesob** [comment]
Why? This is useful information we use for bitcoinperf, and don't necessarily want to enable more severe debugging.

**Comment by fanquake** [comment]
You still haven't provided any motivation, this would likely just be a detriment to existing tools, and as mentioned above, this information is useful to have when not benchmarking/debugging.

**Comment by practicalswift** [comment]
At least make him make his case before closing.

Consider re-opening.

**Pull request closed without merging**
