### PR TITLE
wallet: Use PACKAGE_NAME to mention our software

### PR DESCRIPTION
**Pull request by hebasto**
This PR replaces "bitcoin" and "bitcoind" with `PACKAGE_NAME` in wallet log and error messages.

### CODE REVIEW

**Review by shaavan — COMMENTED** [review]
Concept ACK

This change helps in the generalization of strings and makes them robust in case of any possible future change.

I was just curious. What do you think about adding the word “instance” followed by the package name? 

**For example:**
```
throw std::runtime_error("SQLiteDatabase: Unable to obtain an exclusive lock on the database, is it being used by another " PACKAGE_NAME "?\n");
```
**Changed to** 
```
throw std::runtime_error("SQLiteDatabase: Unable to obtain an exclusive lock on the database, is it being used by another " PACKAGE_NAME " instance?\n");
```

This suggestion is valid for all the strings that have been updated except the one in the `src/wallet/bdb.cpp` file

**Comment by hebasto** [comment]
Updated 16fad5b415efc803eab53a5c8eddd129637a78aa -> da791c7f66243080177f92ce5f38c49305da63dc ([pr23311.01](https://github.com/hebasto/bitcoin/commits/pr23311.01) -> [pr23311.02](https://github.com/hebasto/bitcoin/commits/pr23311.02), [diff](https://github.com/hebasto/bitcoin/compare/pr23311.01..pr23311.02)).

Thanks to all reviewers, your comments are addressed :tiger2:

**Review by lsilva01 — APPROVED** [review]
Tested ACK da791c7 on Ubuntu 20.04.

**Review by brunoerg — APPROVED** [review]
tACK da791c7f66243080177f92ce5f38c49305da63dc

**Review by stratospher — COMMENTED** [review]
Tested ACK da791c7

The generic error messages introduced by this PR in src/wallet/bdb.cpp and src/wallet/sqlite.cpp, which reflect that there may be other instances(not necessarily a bitcoin instance or a bitcoind instance) using the lock is a nice change!

**Review by shaavan — APPROVED** [review]
ACK da791c7f66243080177f92ce5f38c49305da63dc

Changes since my last review:
1. Removed _“of bitcoin”_ in the string in the `src/wallet/bdb.cpp` file to increase the generality of this string message.
2. Added _“instance of”_ in all other (updated) strings to correct the sentences.

**Pull request merged**
