### PR TITLE
util, ci: Hard code previous release tarball checksums

### LINKED ISSUE #19812: ci: previous_release.py fails for C++17 Travis job on forked repo
https://travis-ci.org/github/hebasto/bitcoin/jobs/721269536

### PR DESCRIPTION
**Pull request by hebasto**
#19205 introduced signature verifying for the downloaded `SHA256SUMS.asc`.
This approach is brittle and does not work in CI environment for many reasons:
- https://github.com/bitcoin/bitcoin/issues/19812#issuecomment-680760663
- https://github.com/bitcoin/bitcoin/pull/19013#discussion_r459590779

This PR:
- implements **Sjors**' [idea](https://github.com/bitcoin/bitcoin/pull/19205#pullrequestreview-426080048):
> Alternatively we might as well hard code the checksum for each `tar.gz` release in the source code, here.

- is an alternative to 5a2c31e528e6bd60635096f233252f3c717f366d (#19013)

- fixes #19812

- updates v0.17.1 to v0.17.2

### CODE REVIEW

**Comment by hebasto** [comment]
cc @bliotti @Sjors @MarcoFalke

**Comment by practicalswift** [comment]
Concept ACK: this is better than than fetching the checksums from the same host as the binaries :)

**Comment by laanwj** [comment]
Does this need a mention in the release process?

**Comment by hebasto** [comment]
@laanwj 
> Does this need a mention in the release process?

Here https://github.com/bitcoin/bitcoin/blob/master/doc/release-process.md#after-3-or-more-people-have-gitian-built-and-their-results-match ?

**Comment by MarcoFalke** [comment]
This is only used by tests to download binaries, so no docs need to change. Maybe this should be moved to `./test/download_previous_releases.py` or so?

**Comment by hebasto** [comment]
> Maybe this should be moved to `./test/download_previous_releases.py` or so?

Out from `contrib/devtools/`?

**Comment by theStack** [comment]
Concept ACK

**Comment by Sjors** [comment]
Concept ACK. Maybe put the shasums in a text file so they're easier for other tools to use?

**Comment by laanwj** [comment]
> Here https://github.com/bitcoin/bitcoin/blob/master/doc/release-process.md#after-3-or-more-people-have-gitian-built-and-their-results-match ?

I'm aware of that. I meant to add the hashes to the Python script.

> Concept ACK. Maybe put the shasums in a text file so they're easier for other tools to use?

-0 on this. I mean, the preferred way to validate downloaded binaries is still using GPG, and while I think this is a good shortcut to optimize CI, I'm not sure we should encourage its use in other tools.

**Comment by hebasto** [comment]
@laanwj 
> > Here https://github.com/bitcoin/bitcoin/blob/master/doc/release-process.md#after-3-or-more-people-have-gitian-built-and-their-results-match ?
> 
> I'm aware of that. I meant to add the hashes to the Python script.

Sorry. It seems I did not understand correctly your initial suggestion:
> Does this need a mention in the release process?

Mind rewording?

**Comment by MarcoFalke** [comment]
The tests will need to be adjusted anyway to use the new binaries, so the hashes can be added then (if needed)

**Comment by laanwj** [comment]
No, it's okay, I agree with @MarcoFalke that that is not needed.

> This is only used by tests to download binaries, so no docs need to change.

**Comment by hebasto** [comment]
Updated c5affe70902ccf6ced959c8424cf7f35a3e5e6e1 -> 0374e821bd9e9498ce9c03aa8e5435870019978b ([pr19813.01](https://github.com/hebasto/bitcoin/commits/pr19813.01) -> [pr19813.02](https://github.com/hebasto/bitcoin/commits/pr19813.02), [diff](https://github.com/hebasto/bitcoin/compare/pr19813.01..pr19813.02)).

Addressed @MarcoFalke' [comment](https://github.com/bitcoin/bitcoin/pull/19813#issuecomment-681937956):
> This is only used by tests to download binaries, so no docs need to change. Maybe this should be moved to `./test/download_previous_releases.py` or so?

**Comment by MarcoFalke** [comment]
cr ACK 0374e821bd9e9498ce9c03aa8e5435870019978b

Hardcoding the hashes is equivalent from a trust perspective to hardcoding a gpg fingerprint and adding it to a keyring with ultimate trust.

The hashes will need to be updated whenever a new previous release is added to the tests, but that seems acceptable.

**Comment by luke-jr** [comment]
I noticed gitian building old releases doesn't match anymore, but since this only affects the downloader script (not the tests themselves), concept ACK.

**Comment by MarcoFalke** [comment]
> I noticed gitian building old releases doesn't match anymore

guix fixes this (maybe)

**Comment by Sjors** [comment]
tACK 0374e821bd9e9498ce9c03aa8e5435870019978b

**Pull request merged**
