### PR TITLE
doc: Remove mention of pulltester from README.md

### PR DESCRIPTION
**Pull request by laanwj**
We've switched to Travis CI a long time ago.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
ACK.

**Comment by fanquake** [comment]
ACK

**Comment by laanwj** [comment]
Another section from README.md we could consider removing, or adapting, is "Manual Quality Assurance (QA) Testing".
It refers to https://github.com/bitcoin/QA/, which hasn't been updated since 2013, and doesn't seem like it describes how things are actually going (maybe they should, I don't know, but it doesn't help pointing to procedure if no one follows it anyway, willl just confuse new users).

**Comment by MarcoFalke** [comment]
ACK

**Comment by MarcoFalke** [comment]
> It refers to https://github.com/bitcoin/QA/

It can just be removed because we have rpc test now to write exact test plans. Or, maybe condense this down into three sentences: Test plans may be posted to GitHub comments on each PR, etc. But it's not necessary to do a huge write up.

**Comment by sipa** [comment]
ACK

**Comment by BitcoinPullTester** [comment]
NOOOOOOOOOOOOOOOOOO YOU CANT KILL ME

**Comment by sipa** [comment]
You are terminated.

**Comment by laanwj** [comment]
The final goodbye!

**Pull request merged**
