### PR TITLE
test: check that `listdescriptors` descriptor strings are sorted

### PR DESCRIPTION
**Pull request by theStack**
This small PR adds a test for the change introduced in PR #25931 ("rpc: sort listdescriptors result", commit 50996241f2b0eefeaab4fcd11b9730fa2dc107ae). The correctness of the test can easily be verified by commenting out the `std::sort` call in the `listdescriptors` RPC implementation:
```diff
diff --git a/src/wallet/rpc/backup.cpp b/src/wallet/rpc/backup.cpp
index 09c74ea2da..3ed1a69b26 100644
--- a/src/wallet/rpc/backup.cpp
+++ b/src/wallet/rpc/backup.cpp
@@ -1829,9 +1829,11 @@ RPCHelpMan listdescriptors()
         });
     }

+    /*
     std::sort(wallet_descriptors.begin(), wallet_descriptors.end(), [](const auto& a, const auto& b) {
         return a.descriptor < b.descriptor;
     });
+    */

     UniValue descriptors(UniValue::VARR);
     for (const WalletDescInfo& info : wallet_descriptors) {

```
leading to a fail of the functional test `wallet_listdescriptors.py`.

### CODE REVIEW

**Review by jarolrod — COMMENTED** [review]
Should the help for this rpc and the entry for this rpc in [descriptors.md](https://github.com/bitcoin/bitcoin/blob/master/doc/descriptors.md) be updated to mention that it is sorted?

**Comment by theStack** [comment]
> Should the help for this rpc and the entry for this rpc in [descriptors.md](https://github.com/bitcoin/bitcoin/blob/master/doc/descriptors.md) be updated to mention that it is sorted?

Good point. I think for `descriptors.md` this is too much of a detail to be mentioned (the file only gives a rough one-line description of what each RPC does), but for the RPC help it would make sense. Will take a look.

**Comment by theStack** [comment]
Added a commit that extends the `listdescriptors` RPC help (https://github.com/bitcoin/bitcoin/pull/26156/commits/810c3dc7efbfa07e81f161848010e886e04929ea) by mentioning that the result is sorted by descriptor string representation, as suggested by @jarolrod.

**Review by jarolrod — APPROVED** [review]
ACK 810c3dc7efbfa07e81f161848010e886e04929ea

**Review by aureleoules — APPROVED** [review]
ACK 810c3dc7efbfa07e81f161848010e886e04929ea

**Pull request merged**
