### PR TITLE
Enforce LOW_S rules on all transactions with WITNESS BIP9 parameters

### PR DESCRIPTION
**Pull request by jl2012**
This will enforce SCRIPT_VERIFY_LOW_S on all transactions when segwit is activated with BIP9

### CODE REVIEW

**Comment by sipa** [comment]
This seems to break p2p-segwit.py.

**Comment by dcousens** [comment]
concept ACK

**Comment by NicolasDorier** [comment]
utACK 7ae9df7df2f603eee44db7ad8d0328d7e0e6670c, will try it.

**Comment by jl2012** [comment]
It is proposed to enforce NULLDUMMY at the same time: https://github.com/bitcoin/bips/pull/435

Codes will be updated.

**Comment by jl2012** [comment]
Replaced by https://github.com/bitcoin/bitcoin/pull/8533 with NULLDUMMY added

**Pull request closed without merging**
