### PR TITLE
[22.x] rc3 backports

### PR DESCRIPTION
**Pull request by hebasto**
Backported:

1) #22730
1) https://github.com/bitcoin-core/gui/pull/393
1) #22597
1) https://github.com/bitcoin-core/gui/pull/396
1) #22643
1) #22642
1) #22685 
1) #22686
1) #22654 
1) #22742 
1) https://github.com/bitcoin-core/gui/pull/406
1) #22713

### CODE REVIEW

**Comment by hebasto** [comment]
cc @achow101 @jarolrod @meshcollider @katesalazar

**Comment by MarcoFalke** [comment]
Maybe turn this into a backport pull and also add #22597 ?

**Comment by hebasto** [comment]
@MarcoFalke 
> Maybe turn this into a backport pull and also add #22597 ?

Done :tiger2:

**Comment by hebasto** [comment]
Should we backport #22584 as well to make CI tests green?

**Comment by MarcoFalke** [comment]
Sounds good

**Comment by hebasto** [comment]
Added #22584.

**Comment by jonatack** [comment]
> Should we backport #22584 as well to make CI tests green?

Note that #22584 is fixed by #22586.

**Comment by hebasto** [comment]
CI failure looks related to #22322.

**Comment by hebasto** [comment]
@MarcoFalke 

The current fuzz issue could be fixed by backporting #22517 and #22557.

Is it worth?

**Comment by MarcoFalke** [comment]
> backporting #22517 and #22557.

Seems ok to backport them. Though, apart from the CI I don't think that anyone is running the fuzz targets on release branches.

**Comment by hebasto** [comment]
Added #22517 and #22557.

**Comment by hebasto** [comment]
Added https://github.com/bitcoin-core/gui/pull/396.

**Comment by MarcoFalke** [comment]
The current failure is #22537

**Comment by hebasto** [comment]
> The current failure is #22537

Added #22232, and CI is green now.

Also, there were some [concerns](https://github.com/bitcoin/bitcoin/issues/22537#issuecomment-888787479) about backporting #22232 from @fanquake:
> > I can't imagine we are going to backport #22232.

So, if it seems controversial, ready to roll the last change back.

**Comment by fanquake** [comment]
> Added #22232, and CI is green now.

NACK. I don't know why you've added it. We don't backport refactors.

**Comment by hebasto** [comment]
@fanquake 
> > Added #22232, and CI is green now.
> 
> NACK. I don't know why you've added it. We don't backport refactors.

Reverted back.

But I cannot consider #22232 as a pure refactor, because it improves code quality.

**Comment by hebasto** [comment]
@fanquake 

How about #22597, #22584, #22517, #22557?

**Comment by hebasto** [comment]
Added #22643.

**Comment by hebasto** [comment]
Added #22642.

**Comment by fanquake** [comment]
> How about #22597, #22584, #22517, #22557?

I think we need to decide whether running the fuzzer CI in any branch other than master is something we want to be doing / maintaining. This seems pretty unsustainable unless we at least make changes in regards to the fuzz inputs being used by the different branches. I'm pretty sure Marco has mentioned this before.

Having to backport something like #22517, which is just meant to be a temporary measure to disable a fuzzer in master, and as a result also backporting #22557, which only silences a warning, is messy. Same with #22584. Ideally, in either case, we'd just be backporting an actual bug fix, if anything.

**Comment by hebasto** [comment]
> I think we need to decide whether running the fuzzer CI in any branch other than master is something we want to be doing / maintaining. This seems pretty unsustainable unless we at least make changes in regards to the fuzz inputs being used by the different branches. I'm pretty sure Marco has mentioned this before.

Right. Using the same `qa-assets` for any branch other than master one seems pointless. Considering this, my vote is to skip the fuzzer CI in such cases.

**Comment by hebasto** [comment]
> I think we need to decide whether running the fuzzer CI in any branch other than master is something we want to be doing / maintaining. This seems pretty unsustainable unless we at least make changes in regards to the fuzz inputs being used by the different branches. I'm pretty sure Marco has mentioned this before.

Addressed in #22730.

**Comment by achow101** [comment]
Can #22685 and #22686 be added to this?

**Comment by hebasto** [comment]
> Can #22685 and #22686 be added to this?

Done.

**Comment by jonatack** [comment]
I would submit #22651 and #22648 for consideration. 22.0 with the introduction of I2P support is where they will help the most.

**Comment by Rspigler** [comment]
I agree with @jonatack for 22651 and 22648, if they can get enough ACK's

**Comment by hebasto** [comment]
Added #22654.

**Comment by hebasto** [comment]
Added #22742.

**Comment by fanquake** [comment]
Lets addd #22730, and remove #22584, #22517 and #22557.

**Comment by hebasto** [comment]
> Lets add #22730, and remove #22584, #22517 and #22557.

Done.

**Comment by fanquake** [comment]
> Done.

PR description needs updating.

**Comment by hebasto** [comment]
> > Done.
> 
> PR description needs updating.

Updated.

**Comment by hebasto** [comment]
Added https://github.com/bitcoin-core/gui/pull/406.

**Pull request merged**
