### PR TITLE
release: Update the Windows Codesigning certificate

### PR DESCRIPTION
**Pull request by theuni**
This is a cherry-pick from 0.18/master.

0.17.2rc1 for win cannot currently be (successfully) signed because the 0.17 cert wasn't bumped along with the 0.18 one.

This should fix it.

### CODE REVIEW

**Review by fanquake — APPROVED** [review]
ACK 6737e1c0e16be8ff4cdbf03beb346c9e81b616ba

**Comment by laanwj** [comment]
oops, ACK 6737e1c0e16be8ff4cdbf03beb346c9e81b616ba

**Comment by laanwj** [comment]
time to tag 0.17.2rc2, i guess !

**Comment by GooseyGe59** [comment]
T

**Pull request merged**
