### PR TITLE
Renamed UniValue::__pushKV to UniValue::pushKVEnd.

### PR DESCRIPTION
**Pull request by Brotcrunsher**
Any identifier starting with 2 _ is reserved for the compiler and thus must not be used.

See: https://stackoverflow.com/a/228797/7130273

### CODE REVIEW

**Comment by hebasto** [comment]
See https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md#scripted-diffs for changes like this.

**Comment by hebasto** [comment]
Does it make sense to force such changes with the Clang's [`-Wreserved-identifier`](https://clang.llvm.org/docs/DiagnosticsReference.html#wreserved-identifier) diagnostic flag?

**Comment by fanquake** [comment]
@Brotcrunsher are you going to rebase this?

**Comment by hebasto** [comment]
> > Does it make sense to force such changes with the Clang's [`-Wreserved-identifier`](https://clang.llvm.org/docs/DiagnosticsReference.html#wreserved-identifier) diagnostic flag?
> 
> I get a warning about `_EraseTx` and this:

I got the same. Could be added to this PR, no?

**Comment by Brotcrunsher** [comment]
> Please follow the commit subject max len

Thanks for the feedback, done! One detail question regarding the max length (not important for this Commit, just want to learn for the future). Are CI triggers like "scripted-diff: " considered as part of the subject line and thus part of the 80 chars limitation?

**Comment by fanquake** [comment]
> Does it make sense to force such changes with the Clang's [-Wreserved-identifier](https://clang.llvm.org/docs/DiagnosticsReference.html#wreserved-identifier) diagnostic flag?

Doing so is going to require further suppressing, or changes in upstream code. i.e:
```bash
./minisketch/include/minisketch.h:2:9: warning: macro name is a reserved identifier [-Wreserved-macro-identifier]
#define _MINISKETCH_H_ 1
        ^
1 warning generated.
./crypto/ctaes/ctaes.h:8:9: warning: macro name is a reserved identifier [-Wreserved-macro-identifier]
#define _CTAES_H_ 1
        ^
1 warning generated.
./leveldb/port/thread_annotations.h:16:9: warning: macro name is a reserved identifier [-Wreserved-macro-identifier]
#define THREAD_ANNOTATION_ATTRIBUTE__(x) __attribute__((x))
        ^
1 warning generated.
minisketch/src/util.h:16:11: warning: macro name is a reserved identifier [-Wreserved-macro-identifier]
#  define __GNUC_PREREQ(_maj,_min) \
          ^
3 warnings generated.
```

**Pull request merged**
