### PR TITLE
[WIP] Backports for 0.11.3 (updated to 93ca5a3)

### PR DESCRIPTION
**Pull request by luke-jr**
@laanwj Did I get the commit format like you wanted here?

### CODE REVIEW

**Comment by MarcoFalke** [comment]
@luke-jr Mind to get this up to master?

**Comment by luke-jr** [comment]
@MarcoFalke Updated.

Note, the following are currently *excluded* from this branch, as they require non-trivial evaluation for backporting:

```
	a83f3c2 (origin-pull/6899/head) Add explicit shared_ptr constructor due to C++11 error
	Is 6a07eb6 a bugfix hiding inside #6424 ? O.o
	7085728 doc: there is no libboost-base-dev, add missing sudo
	513686d (origin-pull/6951/head) [qt] Use maxTxFee instead of 10000000
	a0953cd [qa] python-bitcoinrpc is no longer a subtree
	072e2f8 Alter assumptions in CCoinsViewCache::BatchWrite
	4ec3561 Replace scriptnum_test's normative ScriptNum implementation
	9b63758 util: Don't set strMiscWarning on every exception
	e482a7f (origin-pull/6942/head) Fix CCoins serialization documentation
	* 96b8025 Merge pull request #7112
		9af5f9c Move uiInterface.NotifyBlockTip signal above the core/wallet signal - This will keep getbestblockhash more in sync with blocknotify callbacks
		4082e46 [Qt] call GuessVerificationProgress synchronous during core signal, pass double over UI signal
		947d20b [Qt] reduce cs_main in getVerificationProgress()
		e6d50fc [Qt] update block tip (height and date) without locking cs_main, update always (each block)
		012fc91 NotifyBlockTip signal: switch from hash (uint256) to CBlockIndex* - also adds a boolean for indication if the tip update was happening during initial sync - emit notification also during initial sync
	1bb289f Assert now > 0 in GetTime GetTimeMillis GetTimeMicros
```

**Comment by MarcoFalke** [comment]
#7026 should go in as well.

**Comment by MarcoFalke** [comment]
utACK f711635

**Comment by laanwj** [comment]
@luke-jr Yep, commit format looks good to me.

**Comment by MarcoFalke** [comment]
utACK  3b21a5e. Note: This also includes OP_CHECKLOCKTIMEVERIFY, which is not in 0.12.0

**Comment by laanwj** [comment]
This branch has conflicts, BTW

**Comment by jonasschnelli** [comment]
Needs rebase on 0.11er branch.

**Comment by MarcoFalke** [comment]
Also, documentation changes like 79fba30 could be deferred to a later pull.

**Comment by luke-jr** [comment]
(Note: d658fe200e046063179607b9d1b38948b9af49bf and 848699de1f18a3a5c9f3e6c09ae4f6cc5b6da3bb have not been merged to 0.12 yet.)

**Pull request closed without merging**
