### PR TITLE
bench: Add a benchmark for wallet loading

### PR DESCRIPTION
**Pull request by achow101**
I've been working on some improvements to wallet loading performance and it's useful to have a benchmark to check whether these improvements are actually improvements.

### CODE REVIEW

**Review by w0xlt — APPROVED** [review]
ACK 464a162

**Review by maflcko — APPROVED** [review]

**Review by jarolrod — COMMENTED** [review]
Code Review ACK https://github.com/bitcoin/bitcoin/commit/464a16281791ee89be0072c230f07d4496021f15

**Comment by fanquake** [comment]
This has added minutes of runtime to `./src/bench/bench_bitcoin`, at least when run on macOS. I assume it needs to be modified use something like `-unsafesqlitesync`.

**Comment by achow101** [comment]
> I assume it needs to be modified use something like `-unsafesqlitesync`.

I considered that, but thought it would be preferable to benchmark the actual use rather than test-optimized use.

**Comment by achow101** [comment]
See #24924

**Pull request merged**
