### PR TITLE
refactor: Avoid copy of bilingual_str when formatting, Fix ADL violation

### PR DESCRIPTION
**Pull request by maflcko**
This refactor shouldn't change behavior, but may fix compile errors such as https://github.com/bitcoin/bitcoin/pull/27862#issuecomment-1592516184

### CODE REVIEW

**Review by stickies-v — COMMENTED** [review]
Approach ACK. Perhaps worth annotating both `arg` parameters with `LIFETIMEBOUND`?

**Comment by hebasto** [comment]
Concept ACK.

It [helps](https://github.com/bitcoin/bitcoin/pull/27862#issuecomment-1592843602) in https://github.com/bitcoin/bitcoin/pull/27862.

> Approach ACK. Perhaps worth annotating both `arg` parameters with `LIFETIMEBOUND`?

+1

**Review by stickies-v — APPROVED** [review]
ACK faa857686c3693077a09fc571f63829b48e5d5b5

Lambda approach is elegant. I would've been okay with a simple `LIFETIMEBOUND` attribute but this is probably better, thanks for reworking it.

> it would have already been unsafe in master because T& is already a lifetime-bound reference.

Yes, but I think that doesn't hold for what was the untemplated TranslateArg? It doesn't really matter here because `format` returns a copy anyway, but it would make new callsites of `std::string TranslateArg(const bilingual_str& arg, bool translated)` potentially unsafe?

**Review by ryanofsky — APPROVED** [review]
Code review ACK faa857686c3693077a09fc571f63829b48e5d5b5

Thanks for the fix. The code looks safe and should fix the namespace problem, but I had some questions about how it is working internally, see below. They aren't important, just asking to improve my understanding.

**Review by ryanofsky — APPROVED** [review]
Code review ACK fa8ef7d138913d2f10482b0f1693ad94ce497f11. Looks great! Thanks for updating

**Review by hebasto — APPROVED** [review]
ACK fa8ef7d138913d2f10482b0f1693ad94ce497f11, I have reviewed the code and it looks OK.

**Pull request merged**
