### PR TITLE
build: upgrade depends Boost to 1.77.0

### PR DESCRIPTION
**Pull request by fanquake**
This primarily improves support for external signing, as it includes
multiple bugfixes for Boost Process. As well as various improvements to
the multi-index library.

#23340 rebased.

Guix build:
```bash
bash-5.1# find guix-build-$(git rev-parse --short=12 HEAD)/output/ -type f -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum
b5186404303e2a6573a6df404f943f6d172d4965bd9a78d7f9d1f7cf7080b774  guix-build-4bba7ab2ffc3/output/aarch64-linux-gnu/SHA256SUMS.part
9d03756665fac8cb1e3af6623b8cede3032bad6cbc15739db5145c4813f0c2f9  guix-build-4bba7ab2ffc3/output/aarch64-linux-gnu/bitcoin-4bba7ab2ffc3-aarch64-linux-gnu-debug.tar.gz
32897b5fda018d4fe57f65234da9620202de0b774ae4fa454309460ee451ef98  guix-build-4bba7ab2ffc3/output/aarch64-linux-gnu/bitcoin-4bba7ab2ffc3-aarch64-linux-gnu.tar.gz
f64304b16fbfaf7a7330842bf8f535acacdcdd36ddf185f5dfcdbe184f05571f  guix-build-4bba7ab2ffc3/output/arm-linux-gnueabihf/SHA256SUMS.part
f5cb4c742edf42aec2f64f97c727a8e325050d465ea58ff9c22f8b5b31073879  guix-build-4bba7ab2ffc3/output/arm-linux-gnueabihf/bitcoin-4bba7ab2ffc3-arm-linux-gnueabihf-debug.tar.gz
0f834947a3eb2d802ba4d1d6dbd26fea9d3453bd8c2dedb06fcfbf1498b45433  guix-build-4bba7ab2ffc3/output/arm-linux-gnueabihf/bitcoin-4bba7ab2ffc3-arm-linux-gnueabihf.tar.gz
389feef0bf716dd7ea7d72d755f999dbd2d3160f895a606ad6f4a14e97083a47  guix-build-4bba7ab2ffc3/output/arm64-apple-darwin/SHA256SUMS.part
a9c791b6bcc2bbeff0c94f71dbd9967676559297e089079216253e303acd82cb  guix-build-4bba7ab2ffc3/output/arm64-apple-darwin/bitcoin-4bba7ab2ffc3-arm64-apple-darwin.tar.gz
55cdef30941f3fc4716bae5be1230b529b171c5e2cd0c18cc57a15206d742a13  guix-build-4bba7ab2ffc3/output/arm64-apple-darwin/bitcoin-4bba7ab2ffc3-osx-unsigned.dmg
5343499bd15ae59627d3b33259ac7ccec8c841c8bc27cd1a47b41389fae48ac3  guix-build-4bba7ab2ffc3/output/arm64-apple-darwin/bitcoin-4bba7ab2ffc3-osx-unsigned.tar.gz
fbb99e7f3d5249b92c90ba312ac769adfc9813fb70468decd09f722826f48119  guix-build-4bba7ab2ffc3/output/dist-archive/bitcoin-4bba7ab2ffc3.tar.gz
c5f466eb462dccea8daa10307ff140844f38097b198282600528acd486915e97  guix-build-4bba7ab2ffc3/output/powerpc64-linux-gnu/SHA256SUMS.part
174c75cbf16f3ca593d1c684b597eb8dac483dc10ae3cd46cbff61d3f70e70a5  guix-build-4bba7ab2ffc3/output/powerpc64-linux-gnu/bitcoin-4bba7ab2ffc3-powerpc64-linux-gnu-debug.tar.gz
1e6692f4876ba13847cd3722c6e2cd3ee886ebede6b12dffa01b1dbc55186358  guix-build-4bba7ab2ffc3/output/powerpc64-linux-gnu/bitcoin-4bba7ab2ffc3-powerpc64-linux-gnu.tar.gz
dac7f60b99dfb96daf8c3c9a0b98d4ecc3a7ecf7ad6a8dfb879cb61aa4f2e429  guix-build-4bba7ab2ffc3/output/powerpc64le-linux-gnu/SHA256SUMS.part
4cef32efcd9fa591a53ea5354d63e9d6c0d663ae7748599b34427f17ef462f1c  guix-build-4bba7ab2ffc3/output/powerpc64le-linux-gnu/bitcoin-4bba7ab2ffc3-powerpc64le-linux-gnu-debug.tar.gz
d5ac47db91eb0232075a1138cc0ae212516e4f7fa022b2de181533d411a0d507  guix-build-4bba7ab2ffc3/output/powerpc64le-linux-gnu/bitcoin-4bba7ab2ffc3-powerpc64le-linux-gnu.tar.gz
7eb67ea46c7ade1f51928648e664bc2295a96ae0e3f144cf6903f277334b228f  guix-build-4bba7ab2ffc3/output/riscv64-linux-gnu/SHA256SUMS.part
b97d248731573ef3911f4d2750409615a940f975d9c4de783c76beb897a4dd53  guix-build-4bba7ab2ffc3/output/riscv64-linux-gnu/bitcoin-4bba7ab2ffc3-riscv64-linux-gnu-debug.tar.gz
7d2b0cef4cc83dbf54cd1af18fe4cb7b7ea408747e30993c20e1012b1b628373  guix-build-4bba7ab2ffc3/output/riscv64-linux-gnu/bitcoin-4bba7ab2ffc3-riscv64-linux-gnu.tar.gz
a45eb59edc5a1e8742dd9fce1a9916b43ab2894ff8f3c62d5110a9afa35cf9e9  guix-build-4bba7ab2ffc3/output/x86_64-apple-darwin/SHA256SUMS.part
504efd5c1131407a3e3120e77a1abe1e183727d995e7cb944c9c8089518314a0  guix-build-4bba7ab2ffc3/output/x86_64-apple-darwin/bitcoin-4bba7ab2ffc3-osx-unsigned.dmg
0f14f26d2074de96d078ea31ef249a6f9ba2db1fec86856496fca5ab2f517cb7  guix-build-4bba7ab2ffc3/output/x86_64-apple-darwin/bitcoin-4bba7ab2ffc3-osx-unsigned.tar.gz
574aab5513038a80c6cac16eb927d7dcec27b880ffd313c6b56272ed577e2df3  guix-build-4bba7ab2ffc3/output/x86_64-apple-darwin/bitcoin-4bba7ab2ffc3-osx64.tar.gz
ec7861c9840c2888022a81d5fbb807284c07f603053ba9cc200c103e26379e7f  guix-build-4bba7ab2ffc3/output/x86_64-linux-gnu/SHA256SUMS.part
9d1d2fb313d15048ae6b10b9c50942a00ef8c65c367b25656810b3819fdc95ff  guix-build-4bba7ab2ffc3/output/x86_64-linux-gnu/bitcoin-4bba7ab2ffc3-x86_64-linux-gnu-debug.tar.gz
d668065e2de147d352914f0d2f5769051f0ec0a29ce208979758724fe556cc04  guix-build-4bba7ab2ffc3/output/x86_64-linux-gnu/bitcoin-4bba7ab2ffc3-x86_64-linux-gnu.tar.gz
aa1f2ce87f707d28c137775830da128bd2b49b20eb258ff46a78f1ada1516480  guix-build-4bba7ab2ffc3/output/x86_64-w64-mingw32/SHA256SUMS.part
bcf3f19575662dadf3f77ca0bd5d4a3268314fd97c46f88679af1977d83863c5  guix-build-4bba7ab2ffc3/output/x86_64-w64-mingw32/bitcoin-4bba7ab2ffc3-win-unsigned.tar.gz
c8d64700e03757a5f46ec04dc7e2cdf9435ebdee9e6cea5789475ca86461f912  guix-build-4bba7ab2ffc3/output/x86_64-w64-mingw32/bitcoin-4bba7ab2ffc3-win64-debug.zip
92bd0cb7a43551e89910e8fabfb2915da03835ac074331436e1f159760ed8d19  guix-build-4bba7ab2ffc3/output/x86_64-w64-mingw32/bitcoin-4bba7ab2ffc3-win64-setup-unsigned.exe
e414c9a500ebf49ef1f2625c6763b945a13d5f1d1c56463f642f325e054f87ed  guix-build-4bba7ab2ffc3/output/x86_64-w64-mingw32/bitcoin-4bba7ab2ffc3-win64.zip
```

### CODE REVIEW

**Comment by MarcoFalke** [comment]
> Drop fix_openbsd_test_lib.patch.

??

**Comment by fanquake** [comment]
> ??

Thanks, carryover from #23340. Already been done in #24301.

**Comment by MarcoFalke** [comment]
Since we only use the headers, review should be a lot easier.

Can you write up the most important changes or why this is needed?

**Comment by hebasto** [comment]
> Remove now unneeded suppression.

It can be removed without Boost upgrade -- #24390.

**Comment by hebasto** [comment]
#### Guix builds:
```
$ find guix-build-$(git rev-parse --short=12 HEAD)/output/ -type f -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum
3017c0b1d0252de5314ed1ad9086e64e2022cbba021d260be40b6efd7352998d  guix-build-d3ba57bf51e1/output/aarch64-linux-gnu/SHA256SUMS.part
c7bedad711508aa28eefce1d583726f93366b2d20ec20f4506ddbd72572e5b32  guix-build-d3ba57bf51e1/output/aarch64-linux-gnu/bitcoin-d3ba57bf51e1-aarch64-linux-gnu-debug.tar.gz
cd4580625462fd2aa6747cb1b5455a5237b66b9a174cc4237ad77106108a142d  guix-build-d3ba57bf51e1/output/aarch64-linux-gnu/bitcoin-d3ba57bf51e1-aarch64-linux-gnu.tar.gz
e479c62bcd07fe4eda9a0c55d1c72918de91760403fbe6cef8866a3fecd64c87  guix-build-d3ba57bf51e1/output/arm-linux-gnueabihf/SHA256SUMS.part
e7e66847972a86b36aa46d4d258fe87c9b692f8ed1cd5de869dd1c26ba181af5  guix-build-d3ba57bf51e1/output/arm-linux-gnueabihf/bitcoin-d3ba57bf51e1-arm-linux-gnueabihf-debug.tar.gz
b33a3c8701d74c65a0732cb842a1ae66fe199959382629ba2059910e37c90992  guix-build-d3ba57bf51e1/output/arm-linux-gnueabihf/bitcoin-d3ba57bf51e1-arm-linux-gnueabihf.tar.gz
588474e4a7e3b6ff7322ad06c0d370de71ffd8a8eb5c62142274e0616de03b79  guix-build-d3ba57bf51e1/output/arm64-apple-darwin/SHA256SUMS.part
abe16283861951ce20cc39866b5ec372f4eaa7a9d2125d67d48a589727033e4b  guix-build-d3ba57bf51e1/output/arm64-apple-darwin/bitcoin-d3ba57bf51e1-arm64-apple-darwin.tar.gz
5bb9f2cca220a8e7edaeb20a66241ac876d429f0e1246e1e8b11a3edc407e5fe  guix-build-d3ba57bf51e1/output/arm64-apple-darwin/bitcoin-d3ba57bf51e1-osx-unsigned.dmg
612b98a97b9c41920916a73d556a0946ebde9e8334f9658ff674f854af6f30d9  guix-build-d3ba57bf51e1/output/arm64-apple-darwin/bitcoin-d3ba57bf51e1-osx-unsigned.tar.gz
287834c3db19a7ca79f0ade594c5275e6907d24ed230b4107e1ccdfa576775f2  guix-build-d3ba57bf51e1/output/dist-archive/bitcoin-d3ba57bf51e1.tar.gz
e8fa2627adb0482d873a9d1259f06c06168bb42e3c4e7c1904f7e3f3d83949dc  guix-build-d3ba57bf51e1/output/powerpc64-linux-gnu/SHA256SUMS.part
423608d18420638d6c8f11ec33b93a2278bc2775aaa81e3fc63e59909b4e4bb3  guix-build-d3ba57bf51e1/output/powerpc64-linux-gnu/bitcoin-d3ba57bf51e1-powerpc64-linux-gnu-debug.tar.gz
c06c59e85658a10f8d40e121a7a96ec561314046fa3a0ccf31a3c376c6af4cba  guix-build-d3ba57bf51e1/output/powerpc64-linux-gnu/bitcoin-d3ba57bf51e1-powerpc64-linux-gnu.tar.gz
fa504a9ca0bd7213d213fc45f416979d27e1e3eabce56b216da3727f83825382  guix-build-d3ba57bf51e1/output/powerpc64le-linux-gnu/SHA256SUMS.part
a99cc66e52d99bd01a4d0e680c6e7654bcae88474bef45892bed069d2be6845c  guix-build-d3ba57bf51e1/output/powerpc64le-linux-gnu/bitcoin-d3ba57bf51e1-powerpc64le-linux-gnu-debug.tar.gz
91fb5f2ac9fb88b126cf7f40eba7445abedf7c5d4a248311ec51e983ee6dcd4a  guix-build-d3ba57bf51e1/output/powerpc64le-linux-gnu/bitcoin-d3ba57bf51e1-powerpc64le-linux-gnu.tar.gz
7f7b33f80da97281fd2d9cf425b4c200153dd29333d034e60084521f901cd047  guix-build-d3ba57bf51e1/output/riscv64-linux-gnu/SHA256SUMS.part
2686b07316f332e9fe2d1477b0bd69e0e52b61218c6d77dd9b0599d63629d3f5  guix-build-d3ba57bf51e1/output/riscv64-linux-gnu/bitcoin-d3ba57bf51e1-riscv64-linux-gnu-debug.tar.gz
2a7005edeb470110b1737418475d22d1ae91156f54bc7bc6a94c9b38c128fab2  guix-build-d3ba57bf51e1/output/riscv64-linux-gnu/bitcoin-d3ba57bf51e1-riscv64-linux-gnu.tar.gz
4c4ca4bb0868e1a5abda2d1a653338b9bd9d6e08aaba2a576a81ce960e73fa93  guix-build-d3ba57bf51e1/output/x86_64-apple-darwin/SHA256SUMS.part
0ad1bf194803e47dd8a51a3a6de5ea57627f674bb4b3a12258092aa9478ffd57  guix-build-d3ba57bf51e1/output/x86_64-apple-darwin/bitcoin-d3ba57bf51e1-osx-unsigned.dmg
cf17ed62223bdcef32d9fcf791041f77ca7dedc33ece10d17e6c8b67657743d0  guix-build-d3ba57bf51e1/output/x86_64-apple-darwin/bitcoin-d3ba57bf51e1-osx-unsigned.tar.gz
aa2609e0047dd548acb2d948135756833bc704efe902de644ffe778faca2b351  guix-build-d3ba57bf51e1/output/x86_64-apple-darwin/bitcoin-d3ba57bf51e1-osx64.tar.gz
eaccc12c2e0d896d395edf280ea582cb7cb45b328150096fc0221e3ce4b5bb7a  guix-build-d3ba57bf51e1/output/x86_64-linux-gnu/SHA256SUMS.part
154fe3c90b7a889eee1c75839e08b4d6d2edfb18fa3e12eba38d227f59451fbc  guix-build-d3ba57bf51e1/output/x86_64-linux-gnu/bitcoin-d3ba57bf51e1-x86_64-linux-gnu-debug.tar.gz
c500be2ae717800a97f19eb09b331005e7e9c7ec88bc77206480433a5e07af4d  guix-build-d3ba57bf51e1/output/x86_64-linux-gnu/bitcoin-d3ba57bf51e1-x86_64-linux-gnu.tar.gz
34cf68a8a74d1e4901071788bdbc4c11fd386aa2d9061ab5e5667d0cacd98442  guix-build-d3ba57bf51e1/output/x86_64-w64-mingw32/SHA256SUMS.part
b2ae0b4864a951a6a6f937594a3a7ae3c1fbff414e8345b2afc59183d1a14dcf  guix-build-d3ba57bf51e1/output/x86_64-w64-mingw32/bitcoin-d3ba57bf51e1-win-unsigned.tar.gz
447446d0d6d7a5684778df3d4efe0443169974cbf91ec6c4ecbcd77239d4d08f  guix-build-d3ba57bf51e1/output/x86_64-w64-mingw32/bitcoin-d3ba57bf51e1-win64-debug.zip
c3c24311b3a04f631fac5645f0054ac4951329a56e2a06f2886001eb15fd4415  guix-build-d3ba57bf51e1/output/x86_64-w64-mingw32/bitcoin-d3ba57bf51e1-win64-setup-unsigned.exe
b61f756bc1ec6b0efeac45d386785831689ec87b45ce6d7daef9aeaaf00b7ee9  guix-build-d3ba57bf51e1/output/x86_64-w64-mingw32/bitcoin-d3ba57bf51e1-win64.zip
```

**Comment by Sjors** [comment]
Bumping the depends version of Boost is fine by me. Maybe repeat the main motivation(s) from the original PR in the description.

I just updated non-depends Boost to 1.78 on my Mac, so I'll keep an eye on issues.

**Comment by Sjors** [comment]
For some reason 1.77 was never released on Homebrew. Not sure if there was a deeper reason for that. But #24415 seems like a good enough workaround for 1.78

**Comment by fanquake** [comment]
> Needs "version used" update in doc/dependencies.md?

Thanks. Fixed up. I'll add Guix hashes to the description shortly.

**Comment by hebasto** [comment]
#### Guix builds:
```
$ find guix-build-$(git rev-parse --short=12 HEAD)/output/ -type f -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum
b5186404303e2a6573a6df404f943f6d172d4965bd9a78d7f9d1f7cf7080b774  guix-build-4bba7ab2ffc3/output/aarch64-linux-gnu/SHA256SUMS.part
9d03756665fac8cb1e3af6623b8cede3032bad6cbc15739db5145c4813f0c2f9  guix-build-4bba7ab2ffc3/output/aarch64-linux-gnu/bitcoin-4bba7ab2ffc3-aarch64-linux-gnu-debug.tar.gz
32897b5fda018d4fe57f65234da9620202de0b774ae4fa454309460ee451ef98  guix-build-4bba7ab2ffc3/output/aarch64-linux-gnu/bitcoin-4bba7ab2ffc3-aarch64-linux-gnu.tar.gz
f64304b16fbfaf7a7330842bf8f535acacdcdd36ddf185f5dfcdbe184f05571f  guix-build-4bba7ab2ffc3/output/arm-linux-gnueabihf/SHA256SUMS.part
f5cb4c742edf42aec2f64f97c727a8e325050d465ea58ff9c22f8b5b31073879  guix-build-4bba7ab2ffc3/output/arm-linux-gnueabihf/bitcoin-4bba7ab2ffc3-arm-linux-gnueabihf-debug.tar.gz
0f834947a3eb2d802ba4d1d6dbd26fea9d3453bd8c2dedb06fcfbf1498b45433  guix-build-4bba7ab2ffc3/output/arm-linux-gnueabihf/bitcoin-4bba7ab2ffc3-arm-linux-gnueabihf.tar.gz
389feef0bf716dd7ea7d72d755f999dbd2d3160f895a606ad6f4a14e97083a47  guix-build-4bba7ab2ffc3/output/arm64-apple-darwin/SHA256SUMS.part
a9c791b6bcc2bbeff0c94f71dbd9967676559297e089079216253e303acd82cb  guix-build-4bba7ab2ffc3/output/arm64-apple-darwin/bitcoin-4bba7ab2ffc3-arm64-apple-darwin.tar.gz
55cdef30941f3fc4716bae5be1230b529b171c5e2cd0c18cc57a15206d742a13  guix-build-4bba7ab2ffc3/output/arm64-apple-darwin/bitcoin-4bba7ab2ffc3-osx-unsigned.dmg
5343499bd15ae59627d3b33259ac7ccec8c841c8bc27cd1a47b41389fae48ac3  guix-build-4bba7ab2ffc3/output/arm64-apple-darwin/bitcoin-4bba7ab2ffc3-osx-unsigned.tar.gz
fbb99e7f3d5249b92c90ba312ac769adfc9813fb70468decd09f722826f48119  guix-build-4bba7ab2ffc3/output/dist-archive/bitcoin-4bba7ab2ffc3.tar.gz
c5f466eb462dccea8daa10307ff140844f38097b198282600528acd486915e97  guix-build-4bba7ab2ffc3/output/powerpc64-linux-gnu/SHA256SUMS.part
174c75cbf16f3ca593d1c684b597eb8dac483dc10ae3cd46cbff61d3f70e70a5  guix-build-4bba7ab2ffc3/output/powerpc64-linux-gnu/bitcoin-4bba7ab2ffc3-powerpc64-linux-gnu-debug.tar.gz
1e6692f4876ba13847cd3722c6e2cd3ee886ebede6b12dffa01b1dbc55186358  guix-build-4bba7ab2ffc3/output/powerpc64-linux-gnu/bitcoin-4bba7ab2ffc3-powerpc64-linux-gnu.tar.gz
dac7f60b99dfb96daf8c3c9a0b98d4ecc3a7ecf7ad6a8dfb879cb61aa4f2e429  guix-build-4bba7ab2ffc3/output/powerpc64le-linux-gnu/SHA256SUMS.part
4cef32efcd9fa591a53ea5354d63e9d6c0d663ae7748599b34427f17ef462f1c  guix-build-4bba7ab2ffc3/output/powerpc64le-linux-gnu/bitcoin-4bba7ab2ffc3-powerpc64le-linux-gnu-debug.tar.gz
d5ac47db91eb0232075a1138cc0ae212516e4f7fa022b2de181533d411a0d507  guix-build-4bba7ab2ffc3/output/powerpc64le-linux-gnu/bitcoin-4bba7ab2ffc3-powerpc64le-linux-gnu.tar.gz
7eb67ea46c7ade1f51928648e664bc2295a96ae0e3f144cf6903f277334b228f  guix-build-4bba7ab2ffc3/output/riscv64-linux-gnu/SHA256SUMS.part
b97d248731573ef3911f4d2750409615a940f975d9c4de783c76beb897a4dd53  guix-build-4bba7ab2ffc3/output/riscv64-linux-gnu/bitcoin-4bba7ab2ffc3-riscv64-linux-gnu-debug.tar.gz
7d2b0cef4cc83dbf54cd1af18fe4cb7b7ea408747e30993c20e1012b1b628373  guix-build-4bba7ab2ffc3/output/riscv64-linux-gnu/bitcoin-4bba7ab2ffc3-riscv64-linux-gnu.tar.gz
a45eb59edc5a1e8742dd9fce1a9916b43ab2894ff8f3c62d5110a9afa35cf9e9  guix-build-4bba7ab2ffc3/output/x86_64-apple-darwin/SHA256SUMS.part
504efd5c1131407a3e3120e77a1abe1e183727d995e7cb944c9c8089518314a0  guix-build-4bba7ab2ffc3/output/x86_64-apple-darwin/bitcoin-4bba7ab2ffc3-osx-unsigned.dmg
0f14f26d2074de96d078ea31ef249a6f9ba2db1fec86856496fca5ab2f517cb7  guix-build-4bba7ab2ffc3/output/x86_64-apple-darwin/bitcoin-4bba7ab2ffc3-osx-unsigned.tar.gz
574aab5513038a80c6cac16eb927d7dcec27b880ffd313c6b56272ed577e2df3  guix-build-4bba7ab2ffc3/output/x86_64-apple-darwin/bitcoin-4bba7ab2ffc3-osx64.tar.gz
ec7861c9840c2888022a81d5fbb807284c07f603053ba9cc200c103e26379e7f  guix-build-4bba7ab2ffc3/output/x86_64-linux-gnu/SHA256SUMS.part
9d1d2fb313d15048ae6b10b9c50942a00ef8c65c367b25656810b3819fdc95ff  guix-build-4bba7ab2ffc3/output/x86_64-linux-gnu/bitcoin-4bba7ab2ffc3-x86_64-linux-gnu-debug.tar.gz
d668065e2de147d352914f0d2f5769051f0ec0a29ce208979758724fe556cc04  guix-build-4bba7ab2ffc3/output/x86_64-linux-gnu/bitcoin-4bba7ab2ffc3-x86_64-linux-gnu.tar.gz
aa1f2ce87f707d28c137775830da128bd2b49b20eb258ff46a78f1ada1516480  guix-build-4bba7ab2ffc3/output/x86_64-w64-mingw32/SHA256SUMS.part
bcf3f19575662dadf3f77ca0bd5d4a3268314fd97c46f88679af1977d83863c5  guix-build-4bba7ab2ffc3/output/x86_64-w64-mingw32/bitcoin-4bba7ab2ffc3-win-unsigned.tar.gz
c8d64700e03757a5f46ec04dc7e2cdf9435ebdee9e6cea5789475ca86461f912  guix-build-4bba7ab2ffc3/output/x86_64-w64-mingw32/bitcoin-4bba7ab2ffc3-win64-debug.zip
92bd0cb7a43551e89910e8fabfb2915da03835ac074331436e1f159760ed8d19  guix-build-4bba7ab2ffc3/output/x86_64-w64-mingw32/bitcoin-4bba7ab2ffc3-win64-setup-unsigned.exe
e414c9a500ebf49ef1f2625c6763b945a13d5f1d1c56463f642f325e054f87ed  guix-build-4bba7ab2ffc3/output/x86_64-w64-mingw32/bitcoin-4bba7ab2ffc3-win64.zip
```

**Review by hebasto — APPROVED** [review]
ACK 4bba7ab2ffc3a79acfec48727d3c8b35d8ee3f8f

Tested `bitcoin-4bba7ab2ffc3-x86_64-linux-gnu.tar.gz` for external signer support.

**Comment by laanwj** [comment]
My guix build output matches @hebasto 's.
I really hope this is the last boost bump for 23.0 :smile: 

ACK 4bba7ab2ffc3a79acfec48727d3c8b35d8ee3f8f

**Comment by Sjors** [comment]
Also tested that 4bba7ab2ffc3 signer support works on macOS.

Hashes match too (for macOS):

```
fbb99e7f3d5249b92c90ba312ac769adfc9813fb70468decd09f722826f48119  guix-build-4bba7ab2ffc3/output/dist-archive/bitcoin-4bba7ab2ffc3.tar.gz
504efd5c1131407a3e3120e77a1abe1e183727d995e7cb944c9c8089518314a0  guix-build-4bba7ab2ffc3/output/x86_64-apple-darwin/bitcoin-4bba7ab2ffc3-osx-unsigned.dmg
0f14f26d2074de96d078ea31ef249a6f9ba2db1fec86856496fca5ab2f517cb7  guix-build-4bba7ab2ffc3/output/x86_64-apple-darwin/bitcoin-4bba7ab2ffc3-osx-unsigned.tar.gz
574aab5513038a80c6cac16eb927d7dcec27b880ffd313c6b56272ed577e2df3  guix-build-4bba7ab2ffc3/output/x86_64-apple-darwin/bitcoin-4bba7ab2ffc3-osx64.tar.gz
```

**Pull request merged**
