### PR TITLE
test: Check that decoderawtransaction heuristic may fail

### PR DESCRIPTION
**Pull request by maflcko**
Adds an example where the heuristic fails

### CODE REVIEW

**Comment by robot-dreams** [comment]
Concept ACK

Would it make sense to be more explicit about what could go wrong (since it'll always be the case that the heuristic matches either `iswitness=False` or `iswitness=True`)?

For example:

        # The heuristic produces an absurd result with a negative output value
        heuristic = self.nodes[0].decoderawtransaction(hexstring=TX_HEURISTIC) 
        assert heuristic['vout'][0]['value'] < 0

        # The heuristic produces the same absurd result as iswitness=False
        non_witness = self.nodes[0].decoderawtransaction(hexstring=TX_HEURISTIC, iswitness=False)
        assert_equal(heuristic['txid'], non_witness['txid'])

        # Specifying iswitness=True produces a reasonable result
        witness = self.nodes[0].decoderawtransaction(hexstring=TX_HEURISTIC, iswitness=True)
        assert witness['vout'][0]['value'] > 0

**Comment by MarcoFalke** [comment]
>     `assert heuristic['vout'][0]['value'] < 0`

The amount doesn't have to be negative. I've modified the tx, so that the amount is positive.

**Comment by laanwj** [comment]
I'm a bit confused by this. Is this something that should be able to fail, or a bug that needs to be corrected in the heuristic?

**Comment by adamjonas** [comment]
@MarcoFalke mind addressing [laanwj's question](https://github.com/bitcoin/bitcoin/pull/19831#issuecomment-732235048)?

**Comment by MarcoFalke** [comment]
Fixed by #20595

**Pull request closed without merging**
