### PR TITLE
Update build-osx.md

### PR DESCRIPTION
**Pull request by Bhaney44**
I made the introduction more clear to help prevent confusion about installation and requirements.

ORIGINAL:
The commands in this guide should be executed in a Terminal application. macOS comes with a built-in Terminal located in:

`/Applications/Utilities/Terminal.app`

NEW:
The commands in this guide should be executed in a Terminal application.

-----------

The original text causes issues for developers by creating confusion regarding where code should be run, as described in #26778. Moreover, there are core problems relating to the technical convergence between the macOS GUI and Terminal App CLI. Specifically, the GUI and CLI are not in sync, which signifies problems deeper in the macOS architecture. 

I think it is important to focus on solving the real problem at hand, which is how to build bitcoin with a Mac. There is no reason to reference or direct developers to the Applications folder that I know of and please correct me if you believe I am mistaken. Here, the Principle of Parismony should apply and the simpler explanation is better.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
No opinion on the changes here, but please do not add merge commits and keep your commits squashed according to https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#squashing-commits

**Comment by fanquake** [comment]
~0 doesn't seem like an improvement. I don't see how this is related too, or solves your problems in #26778.

**Review by stickies-v — COMMENTED** [review]
NACK

Since macOS Catalina (10.15), utilities have been moved to `/System/Applications/Utilities` but in the GUI that location change was largely hidden, see e.g. [this article](https://derflounder.wordpress.com/2019/10/11/most-apple-apps-installed-with-the-os-have-a-new-filesystem-location/). In the GUI, the terminal effectively still appears to be in `/Applications/Utilities/Terminal.app`

These instructions, by definition, are only relevant to people that are using the GUI, because if they were using a terminal they already know where the terminal is. As such, I think they are fine to keep as is. I also wouldn't be terribly opposed to removing them, but frankly to me this just looks like a waste of time.

**Review by promag — COMMENTED** [review]
TBH, I think `## Preparation` section adds no value and could be removed - below there are already references to "your terminal". That is my suggestion if this is not closed.

**Comment by Bhaney44** [comment]
Thanks for all the thoughts and feedback. My intention here was to help, certainly if you don't think this helps, you do not have to merge the PR. I am still working through the pathing problem on installation defined in #26778. I ran into a massive sub-problem with the data requirements and now have to remove the installed software, but I'm struggling to find it on my machine because of the broader pathing issue.

Some questions I have generally on contributions to Bitcoin Core.

1. Does the core team want OSS developers to contribute?
2. Does the core team want to solve problems in Bitcoin Core?
3. What incentive is there for contributing to Bitcoin Core?

I am indifferent to the answer to these questions, I just don't have a good way to gauge the climate or need for the network. So, I only identify problems based on my own experience developing. Of course, one developers problems could also be another developers solution, especially if the intention is to keep developers out, as is the case with many L1s. It's ok if that is the intention here too, it would just be helpful to know ahead of time. I don't want to bother anyone here if the core team does not want help or new solutions.

**Comment by MarcoFalke** [comment]
## Getting started to contribute to Bitcoin Core

### Setting up your development environment

New developers are very welcome and needed. There are a lot of open issues of any difficulty waiting to be fixed. However, before you start contributing, familiarize yourself with the Bitcoin Core build system and tests. Refer to the documentation in the repository on how to build Bitcoin Core and how to run the unit and functional tests. Once that is done, you are all set.

If you need more help getting started, please refer to the following resources:

* https://medium.com/@amitiu/onboarding-to-bitcoin-core-7c1a83b20365
* https://jonatack.github.io/articles/how-to-review-pull-requests-in-bitcoin-core

### Pick something to work on

If you are looking for useful contributions to help out with, you can

* Search through the [good first issue](https://github.com/bitcoin/bitcoin/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)s or the ones that are [up for grabs](https://github.com/bitcoin/bitcoin/issues?utf8=%E2%9C%93&q=label%3A%22Up+for+grabs%22). Some of them might no longer be applicable. So if you are interested, but unsure, you might want to leave a comment on the issue first.
* Write tests to improve the coverage. Any kind of test is welcome and coverage information can be obtained from a relatively recent [coverage report](https://marcofalke.github.io/btc_cov). If you are unsure, don't hesitate to check back first.
* Help with review and testing. There are easy ones such as the [gui](https://github.com/bitcoin-core/gui/pulls) and [rpc](https://github.com/bitcoin/bitcoin/pulls?q=is%3Apr+is%3Aopen+label%3ARPC%2FREST%2FZMQ). However, review on any open pull request is welcome. Review will also help you understand the codebase better.
* Help on meta projects related to Bitcoin Core, such as a [high-level performance monitor](https://github.com/chaincodelabs/bitcoinperf).
* Join us on irc and let us know what you are interested in.

**Comment by Bhaney44** [comment]
> * https://jonatack.github.io/articles/how-to-review-pull-requests-in-bitcoin-core

Great, thank you!

**Comment by fanquake** [comment]
Closing for now (still unmergable in any case).

**Pull request closed without merging**
