### PR TITLE
build: split warnings out of CXXFLAGS

### PR DESCRIPTION
**Pull request by theuni**
CXXFLAGS should not be modified anyway. Also, this will enable us to selectively disable warnings.

As discussed with @sipa on IRC. Intention is to be able to filter out warnings from leveldb code so that we can be more aggressive with what we enable.

### CODE REVIEW

**Comment by Empact** [comment]
Concept ack. Could be done with a single var `WARN_CXXFLAGS`.

**Comment by theuni** [comment]
@Empact They were split so that we may filter out warnings, but still quash annoying ones.

**Comment by Empact** [comment]
To be clear, I just mean that you could store both the warn and nowarn options in the WARN_CXXFLAGS. No change in options communicated.

**Comment by practicalswift** [comment]
Very good idea! Will allow for enabling more warnings

Concept ACK

**Comment by laanwj** [comment]
utACK 9e305b56f5323cbf2b793d96e63e1a1c107155ab

**Comment by sipa** [comment]
Concept ACK. I don't understand autotools enough to understand the effect of these code changes.

**Comment by laanwj** [comment]
> Concept ACK. I don't understand autotools enough to see the effect of these code changes.

As I understand it, there isn't any effect as-is, this just isolates the warnings into a different variable.

**Comment by theuni** [comment]
@Empact That would not change the result here, but it would mean that we're unable to make a distinction between the two later.

@laanwj yes, exactly. @sipa mentioned that he would like to add more aggressive warnings for our code (-Wsuggest-override specifically was the prompt), but that would mean that we would have to fix up a bunch of warnings inside of leveldb. This PR separates the warnings so that they can be removed from leveldb as such:

```patch
diff --git a/src/Makefile.leveldb.include b/src/Makefile.leveldb.include
index 833f3d2..36edef9 100644
--- a/src/Makefile.leveldb.include
+++ b/src/Makefile.leveldb.include
@@ -30,7 +30,7 @@ LEVELDB_CPPFLAGS_INT += -DLEVELDB_PLATFORM_POSIX
 endif

 leveldb_libleveldb_a_CPPFLAGS = $(AM_CPPFLAGS) $(LEVELDB_CPPFLAGS_INT) $(LEVELDB_CPPFLAGS)
-leveldb_libleveldb_a_CXXFLAGS = $(AM_CXXFLAGS) $(PIE_FLAGS)
+leveldb_libleveldb_a_CXXFLAGS = $(filter-out $(WARN_CXXFLAGS),$(AM_CXXFLAGS)) $(PIE_FLAGS)

 leveldb_libleveldb_a_SOURCES=
 leveldb_libleveldb_a_SOURCES += leveldb/port/atomic_pointer.h
```

I didn't include that in this PR because I don't think we want to remove _all_ warnings, so that needs discussion, but this PR is an obvious and straightforward prerequisite IMO.

**Comment by fanquake** [comment]
utACK 9e305b5

**Pull request merged**
