### PR TITLE
contrib: Remove suspicious hosts list from makeseeds

### PR DESCRIPTION
**Pull request by laanwj**
I have some qualms about maintaining a suspicious hosts list as part as the repository\*. But also, it's stale and irrelevant. I've checked the entire list and none of them is connectable. Only one still appars in `nodes_main.txt` but with low uptime and an old subversion string so it wouldn't be picked in the first place. This change removes the list and the functionality to use it.

| IP               | 8333 connectable    | in `nodes_main.txt`   |
|------------------|---------------------|-----------------------|
| 130.211.129.106  |      no  | no    |
| 148.251.238.178  |      no  | no    |
| 176.9.46.6       |      no  | yes: /Satoshi:0.9.2.1/    |
| 178.63.107.226   |      no  | no    |
| 54.173.72.127    |      no  | no    |
| 54.174.10.182    |      no  | no    |
| 54.183.64.54     |      no  | no    |
| 54.194.231.211   |      no  | no    |
| 54.66.214.167    |      no  | no    |
| 54.66.220.137    |      no  | no    |
| 54.67.33.14      |      no  | no    |
| 54.77.251.214    |      no  | no    |
| 54.94.195.96     |      no  | no    |
| 54.94.200.247    |      no  | no    |
| 83.81.130.26     |      no  | no    |
| 88.198.17.7      |      no  | no    |

ref: https://github.com/bitcoin/bitcoin/issues/17020#issuecomment-1099973383

\* besides the commit noise, potential legal issues around accountability and liability that would come with maintaining such a blocklist actively, I don't think we should expose the project to

### CODE REVIEW

**Comment by mruddy** [comment]
Concept ACK this seems like not very effective cat and mouse stuff. I also looked through the code and the proposed change looks comprehensive / complete.

**Review by jonatack — APPROVED** [review]
ACK 2f629f80896697e458b47a8335744a11b4f3358

It looks like these haven't been updated since be22b3da1df15757ef15e4c4963507bcdff6a872 in December 2014/January 2015.

**Review by ghost — APPROVED** [review]
ACK https://github.com/bitcoin/bitcoin/pull/24862/commits/2f629f80896697e458b47a8335744a11b4f33587

**Comment by MarcoFalke** [comment]
ACK

**Comment by Empact** [comment]
ACK

**Comment by Empact** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/24862/commits/2f629f80896697e458b47a8335744a11b4f33587

/cc @sipa, who introduced this list in be22b3da1df15757ef15e4c4963507bcdff6a872

**Pull request merged**
