### PR TITLE
ci: Remove trusty

### PR DESCRIPTION
**Pull request by cvengler**
Remove trusty as it has reached is end of life since April
https://endoflife.software/operating-systems/linux/ubuntu

### CODE REVIEW

**Comment by MarcoFalke** [comment]
This is still used to ensure we can build with the minimum required qt and boost versions

**Comment by emilengler** [comment]
@MarcoFalke Why we don't use a newer minimal Qt version when the old one is only used by a distro which has reached its end of life

**Comment by sipa** [comment]
Ubuntu is not the only distribution that matters.

**Comment by Sjors** [comment]
I created an issue to track when it's OK to drop Trusty: #17628.

**Pull request closed without merging**
