### PR TITLE
AppInitMain: split initialization of Connman into a new function

### PR DESCRIPTION
**Pull request by benma**
An effort to reduce the size of AppInitMain().

### CODE REVIEW

**Comment by benma** [comment]
Rebased.

**Comment by dcousens** [comment]
concept ACK

**Comment by laanwj** [comment]
Ping @cfields (as he wrote the Connman code).

**Review by theuni — CHANGES_REQUESTED** [review]
Mm, I like the consolidation, but this kinda confuses the interface and gets in the way of the clean instantiation. The things currently done before starting connman are actually just config options that haven't been moved in yet.

What I'd much prefer (just hadn't gotten around yet) is to add:
CConnman::Options::vWhitelist
CConnman::Options::vBinds
CConnman::Options::vSeedNodes

I think we can combine the approaches by keeping the creation as-is, and having InitConnman() parse the config options and return a CConnman::Options.

**Comment by benma** [comment]
@theuni 

Thanks, that makes a whole lot of sense. I started the process with `vSeedNodes` in #10467, and will revisit this PR once the rest of the initialization is cleaned up.

**Comment by ryanofsky** [comment]
#10496 seems to be the next PR in this progression.

**Comment by laanwj** [comment]
Needs rebase after #10467 (I guess?)

**Comment by benma** [comment]
Might revisit with a new PR some day.

**Pull request closed without merging**
