### PR TITLE
script: utxo_snapshot.sh error handling

### PR DESCRIPTION
**Pull request by hazeycode**
There are 2 parts to this patchset, both concern the operation of `./contrib/devtools/utxo_snapshot.sh`:
1. Error handling is added so that the chainstate can be automatically recovered if an error occurs
2. Early exit if a file at OUTPUT_PATH already exists

The easiest way to test this is to take only the 1st part and follow these steps:
1. Create a dummy file for the purpose of the test e.g. `echo "some bytes so file is not empty" > ./utxo-788440.dat`
2. Run bitcoind and wait for it to sync
3. Run utxosnapshot.sh with some blockheight and a filepath __that already exists__ e.g. `./contrib/devtools/utxo_snapshot.sh 788440 ./utxo-788440.dat ./src/bitcoin-cli`
4. Wait for chain rewind to happen, snapshot to be generated and write to disk fail
5. Observe that the pivot block is now reconsidered and the chain is restored to the original height

Note that the 2nd part precludes error handling in the case that the file already exists.

For more info see https://github.com/bitcoin/bitcoin/issues/27841

__UPDATE__: Squashed into a single commit

### CODE REVIEW

**Comment by jamesob** [comment]
I see you've got some lint failures in CI; you can run linters (faithfully) locally using the container added here: https://github.com/bitcoin/bitcoin/pull/26906/files

**Comment by Sjors** [comment]
Lightly tested ACK 10d9bef0045398641fc723bd73b55ab9c512dac1

**Review by pablomartin4btc — COMMENTED** [review]
cr ACK.

I was working on this file this week and when I was about to create a PR I found this thankfully, and thanks for working on this, I had the described issues with this script and it's important to fix it.

If you want to link this PR to the issue that it resolves please consider to add some of these [keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) in the PR description following by the issue #, and you could remove the reference from the commit body.

I leave a couple of suggestions regarding the code.

**Comment by pablomartin4btc** [comment]
@hazeycode, are you still interested in continuing to work on this PR? Please let me know, otherwise I'll pick it up.

Btw, there's also another [suggestion](https://github.com/bitcoin/bitcoin/pull/28553#issuecomment-1804941396) from @Sjors to improve the script with another validation that might be needed.

**Comment by hazeycode** [comment]
Sorry for the delayed response @pablomartin4btc. Thanks for looking at this. Unfortunately, I don't have a time to work on this further at the moment, so feel free to take baton.

**Comment by pablomartin4btc** [comment]
> Sorry for the delayed response @pablomartin4btc. Thanks for looking at this. Unfortunately, I don't have a time to work on this further at the moment, so feel free to take baton.

Thanks @hazeycode, no worries, please close this PR, I'll create a new one and will add you as a co-author in the commit. Cheers!

**Pull request closed without merging**
