### PR TITLE
RPC/Wallet: Access wallets via interfaces::Wallet

### PR DESCRIPTION
**Pull request by luke-jr**
This is a minimal "step 1" to migrating wallet RPC methods to access via the abstract interfaces. Only trivial methods are ported at this stage.

Long term goal is to support different actual wallet classes (in particular, core-lighting wallets) which won't have remotely the same internals as Bitcoin Core wallets.

### CODE REVIEW

**Comment by w0xlt** [comment]
Approach ACK. This provides a better separation of concerns.

**Comment by S3RK** [comment]
Can you elaborate on "support different actual wallet classes (in particular, core-lighting wallets)"? I always though of lighting wallets operating on another abstraction layer on-top of bitcoin wallets, i.e. bitcoin wallets abstract the use of the blockchain while lighting wallets make use of that. Thus it seems like lighting wallets should have different interface from bitcoin wallets.

**Comment by luke-jr** [comment]
>Can you elaborate on "support different actual wallet classes (in particular, core-lighting wallets)"? I always though of lighting wallets operating on another abstraction layer on-top of bitcoin wallets, i.e. bitcoin wallets abstract the use of the blockchain while lighting wallets make use of that. Thus it seems like lighting wallets should have different interface from bitcoin wallets.

Wallets in general are at the same abstraction layer. Most interfaces are common whether you're sending/receiving on-chain or Lightning.

**Comment by ryanofsky** [comment]
I think this is a good change for a different reason than the one stated. Even if there won't be multiple wallet implementations, letting RPC methods interact with wallets through the `interfaces::Wallet` class instead of the `CWallet` class means new RPC methods can avoid accessing internal wallet state just like GUI code avoids it, and new RPC features should be easier to port to the GUI because they can be implemented behind the interface rather than on top of it.

One suggestion I would have is to drop commit "Wallet: Add missing const attribute to interfaces" (cc0a1d565e1aeb9f399a6b406528a80f4d0d0180) from this PR. The `interface::Wallet` class is an abstract class and the methods it declares are intentionally non-const, because making them const exposes internal implementation details of `interface::Wallet` subclasses that callers should not be aware of. In practice, it breaks multiprocess support (see https://github.com/bitcoin/bitcoin/pull/25337#discussion_r916367659, commit e81daff985867bfe88fdef325384dac344eb6aad from #10102). Dropping this would also make the PR more focused and smaller.

**Comment by S3RK** [comment]
> I think this is a good change for a different reason than the one stated. Even if there won't be multiple wallet implementations, letting RPC methods interact with wallets through the `interfaces::Wallet` class instead of the `CWallet` class means new RPC methods can avoid accessing internal wallet state just like GUI code avoids it, and new RPC features should be easier to port to the GUI because they can be implemented behind the interface rather than on top of it.

Agree that having RPC interacting through clear interface is great. Maybe we should discuss the long-term goal "to support different actual wallet classes (in particular, core-lighting wallets)" in some other place.

**Comment by PrimarchAzrael** [comment]
sheesh

**Comment by fanquake** [comment]
Moved to draft, as it looks like this needs further discussion, and has needed rebase for 3 months.

**Pull request closed without merging**
