### PR TITLE
docs: Specify preferred Python string formatting technique

### PR DESCRIPTION
**Pull request by masonicboom**
@practicalswift this documents the nit you suggested in my previous PR 
https://github.com/bitcoin/bitcoin/pull/13707#discussion_r203628395

### CODE REVIEW

**Comment by masonicboom** [comment]
Thanks. My philosophy is: if it's worth a nit, it's worth documenting (or even better, automating with lint rules) to eliminate review round-trips in the future.

> Trivia: When we move to Python 3.6 we can start using formatted string literals ("f-strings") as well :-)

Nice!

**Comment by practicalswift** [comment]
@masonicboom I share your love for automation/linting! 🏧😍

**Comment by laanwj** [comment]
Concept ACK, no strong feelings on what formatting to use, and please **do not** create PRs that change this all over the place, but for new code it is a good idea to use the new, recommended style consistently.

**Comment by MarcoFalke** [comment]
Agree with @practicalswift and @laanwj 

> it should be noted that a nit is just a suggested change for a trivial often non-blocking issue. Not all style nits end up in the developer notes (due to various reasons: no clear consensus, not worth documenting, etc.).

**Comment by promag** [comment]
ACK

**Pull request merged**
