### PR TITLE
Ensure wallet is unlocked before signing PSBT with walletprocesspsbt and GUI

### LINKED ISSUE #312: Unable to sign PSBT loaded from file/clipboard on the second time, getting "could not sign any more inputs" error
So I have bitcoin-core wallet.

1. I imported one of the receiving addresses from bitcoin-core to electrum as a watch only wallet.
2. I created a raw transaction using electrum
3. In electrum, I exported the raw transaction as a file (psbt file)
4. Load the PSBT file using bitcoin-core
5. Successfully signed the transaction on bitcoin-core

I repeated the process for the second time and I am getting this error, "could not sign any more inputs"

I searched the error message, it seems be here:
https://github.com/bitcoin/bitcoin/blob/7fcf53f7b4524572d1d0c9a5fdc388e87eb02416/src/qt/psbtoperationsdialog.cpp#L81

PS:
before I did the second try, I changed the passphrase.
bitcoin-core is on an offline computer.
bicoin core v0.21.0

I wonder if changing the passpharse on bitcoincore is related to this problem.
As far as I know the passphrase is only used to encrypt the wallet file? It has nothing to do with the private keys and address like mnemonic seeds?

### LINKED ISSUE #22874: bitcoin-cli walletprocesspsbt does not trigger passphrase warning
Bitcoin Core v0.21.1

`bitcoin-cli walletprocesspsbt` does not trigger a `wallet locked please enter passphrase` warning when using a wallet which holds private keys. To be clear I am experiencing this behavior when using the `default` wallet created by core.

The expected behavior would be to remind the user they are dealing with an encrypted wallet, since `walletprocesspsbt` attempts to access private keys to sign the psbt. It would be useful if a warning were present in the rpc response to remind the user they are dealing with an encrypted wallet.

### PR DESCRIPTION
**Pull request by meshcollider**
If signing a PSBT, we need to ensure the wallet is unlocked.

Fixes #22874, fixes bitcoin-core/gui#312

### CODE REVIEW

**Comment by prayank23** [comment]
Related GUI issue: https://github.com/bitcoin-core/gui/issues/312

**Review by promag — COMMENTED** [review]
Concept ACK. Could include a test.

**Comment by meshcollider** [comment]
Added another commit to address the GUI issue @prayank23 mentioned.

**Review by lsilva01 — APPROVED** [review]
Code Review ACK https://github.com/bitcoin/bitcoin/pull/23106/commits/7e3ee4cdd0f60a2f549ba030fe96b90d61c036c5

**Review by benthecarman — APPROVED** [review]
ACK 7e3ee4cdd0f60a2f549ba030fe96b90d61c036c5

**Comment by prayank23** [comment]
Post merge tACK https://github.com/bitcoin/bitcoin/commit/7e3ee4cdd0f60a2f549ba030fe96b90d61c036c5

<details>
  <summary>GUI</summary>
  
image

image

</details>


<details>
  <summary>CLI </summary>
  
```
$ bitcoin-cli walletprocesspsbt cHNidP8BAHECAAAAAc8rxxALBsWEEOQeiG8omNLS4etwfelczxCNkXq9ZkeDAQAAAAD9////AsPCAAAAAAAAFgAUk+E508Evzkjtp96eDMvj9acJsflQwwAAAAAAABYAFHRCFAkrwLrC4N8FwoQe83iHlPkZJP4fAAABAPUCAAAAAAEBn+1tNePIJterqM3FTCHyU5Pd7gDINjeWro57Og5DJmEAAAAAFxYAFMfPZFdLtGL2sDk+VtPq+FwO82Bv/v///wJYfwwBAAAAABYAFFKue/4Z1wdWSuWrItUf3XESDfiyoIYBAAAAAAAWABST4TnTwS/OSO2n3p4My+P1pwmx+QJHMEQCID4Hj3fkUhjkkGlJmmFqxkzjd7aN6Jc3RwSEc/kZ+ipFAiAq0iVNaVehtVFMIde58WjA0oyzMl1TNIAnWD7eqEh/gwEhA39z5OpBbgNSPWgXtFdiJiKMFrvE20Z9vHiXe5BERwWJ9P0fAAAAAA==

Error: Please enter the wallet passphrase with walletpassphrase first. (code -13)
```

</details>

**Review by promag — COMMENTED** [review]
Code review ACK 7e3ee4cdd0f60a2f549ba030fe96b90d61c036c5.

**Pull request merged**
