### PR TITLE
doc: use "std lib clock" over "C++11 clock"

### PR DESCRIPTION
**Pull request by fanquake**
These were new in C++11, and now they are just our standard library.

### CODE REVIEW

**Review by hebasto — APPROVED** [review]
ACK b8cfbcdc73f04f6bc2c0f3d7da885d651b62b86d.

There are a few more places where mentioning of C++11 in docs and comments seems outdated. For example:
- `.github/ISSUE_TEMPLATE/good_first_issue.md`
- `contrib/guix/INSTALL.md`
- `src/random.h`
- etc

**Review by jarolrod — APPROVED** [review]
ACK b8cfbcdc73f04f6bc2c0f3d7da885d651b62b86d

**Comment by fanquake** [comment]
> contrib/guix/INSTALL.md

This isn't outdated. Removed some others.

**Review by hebasto — APPROVED** [review]
re-ACK 672f7ad747ecc6e04472f96fa88332be1f39d39b

**Comment by jarolrod** [comment]
re-ACK 672f7ad747ecc6e04472f96fa88332be1f39d39b

**Pull request closed without merging**
