### PR TITLE
Remove bsdmainutils from doc/ci

### PR DESCRIPTION
**Pull request by fanquake**
This was previously used to install `hexdump` (for the tests). However that isn't used by CMake. I'm not aware of any other tools from this package being used.

### CODE REVIEW

**Review by hebasto — APPROVED** [review]
> This was previously used to install `hexdump` (for the tests).

(via the [`bsdextrautils`](https://packages.ubuntu.com/noble/amd64/bsdextrautils/filelist) package, at least on Ubuntu 24.04)

ACK c462276e6eea70efb0dd3a486f50fb32a7934500.

**Comment by fanquake** [comment]
Yea, see my comment here: https://github.com/bitcoin/bitcoin/pull/30740/files#r1735920877. I will just add the proper dependency.

**Review by hebasto — APPROVED** [review]
ACK 78358ce09d2a62a469a544249e02e02f9f7b94cd.

**Comment by fanquake** [comment]
Going to merge this now, to prevent any further unrelated CI failures in other PRs.

**Comment by Sjors** [comment]
Just ran into this as well, thanks for the fix.

**Pull request merged**
