### PR TITLE
qt: Replace deprecated QSignalMapper by lambda expressions

### PR DESCRIPTION
**Pull request by hebasto**
The [`QSignalMapper`](https://doc.qt.io/qt-5/qsignalmapper.html) class has been [deprecated](https://doc-snapshots.qt.io/qt5-5.10/obsoleteclasses.html) since Qt 5.10.

This PR replaces it by lambdas and does not change behavior.

### CODE REVIEW

**Comment by fanquake** [comment]
QSignalMapper has actually been un-deprecated, see [QSignalMapper deprecation](https://bugreports.qt.io/browse/QTBUG-73407) and [Un-deprecate QSignalMapper](https://codereview.qt-project.org/c/qt/qtbase/+/268701).

However Concept ACK assuming there's no change in behaviour and the new code is still compatible with Qt `5.5.1`.

**Comment by hebasto** [comment]
@fanquake 
> QSignalMapper has actually been un-deprecated, see [QSignalMapper deprecation](https://bugreports.qt.io/browse/QTBUG-73407) and [Un-deprecate QSignalMapper](https://codereview.qt-project.org/c/qt/qtbase/+/268701).

I didn't know about that. Thank you.

FWIW, this PR is a part of my work on warnings raised during compiling on Bionic against Qt 5.13.

**Comment by practicalswift** [comment]
Concept ACK -- more readable and less code

**Review by promag — COMMENTED** [review]
Concept ACK.

Are the style changes really necessary? I'd prefer just dropping `QSignalMapper`.

**Comment by hebasto** [comment]
@promag 
> Are the style changes really necessary? I'd prefer just dropping `QSignalMapper`.

Done.

**Comment by jonasschnelli** [comment]
Concept ACK

**Review by jonasschnelli — APPROVED** [review]
utACK 091213403922e970b38cc3a98c11074e02ddba14

**Comment by Sjors** [comment]
Post merge ACK. This totally gets rid of the flood of warnings on macOs with QT 5.13 from homebrew.  It's also shorter and more readable. Tested that external explorer links still work, as well as banning peers.

Building with depends (QT 5.9.7) also works, though this still throws trillions of (unrelated) warnings.

**Pull request merged**
