### PR TITLE
[Wallet] FundRawTransaction can accept pre-set inputs whose parent is not yet broadcasted

### PR DESCRIPTION
**Pull request by NicolasDorier**
This PR is based on https://github.com/bitcoin/bitcoin/pull/10202, it allows the user to pre fund a transaction with inputs which have not yet been broadcasted.
Please, review and ACK the first one independently from this PR.

This is useful for second layer payment protocol which regularly build transaction on top of unbroadcasted transaction.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Needs rebase.

**Comment by NicolasDorier** [comment]
I workedaround this need for this.

**Comment by JeremyRand** [comment]
> I workedaround this need for this.

@NicolasDorier may I ask what your workaround was?  I was very much hoping to see this PR merged, I'd love to see a workaround.

**Comment by NicolasDorier** [comment]
@JeremyRand I just gave up using the RPC for my projects, it was easier to create [NBXplorer](https://github.com/dgarage/NBXplorer/) which is a lightweight block explorer for bitcoin also working on pruned mode.

Feel free to rebase and take this PR if you feel the strength to get it merged, I would review.

**Pull request closed without merging**
