### PR TITLE
msvc: Cleanup after upgrading libsecp256k1 up to 0.3.0

### PR DESCRIPTION
**Pull request by hebasto**
libsecp256k1 [v0.3.0](https://github.com/bitcoin-core/secp256k1/blob/master/CHANGELOG.md#030---2023-03-08):
> Removed the configuration header `src/libsecp256k1-config.h`.

This PR removed the code that has been unused since https://github.com/bitcoin/bitcoin/pull/27230.

The `USE_ASM_X86_64` is now undefined explicitly (but actually it seems a bit redundant).

The `ECMULT_GEN_PREC_BITS` and `ECMULT_WINDOW_SIZE` macros are defined by the source code to their defaults.

---

Considering the upcoming CMake-based build system, these changes have a low-priority.

### CODE REVIEW

**Review by fanquake — APPROVED** [review]
ACK d9b54c46ccb28af20eb03e1409d1a34dc2adccdb

**Comment by fanquake** [comment]
Note that this conflicts with #27479, however it's a single-line change, and 27479 will have to be rebased again after the secp changes are pulled into our tree, so I think we can go ahead and merge this in the interim. cc @sipa.

**Comment by pinheadmz** [comment]
ACK
I noticed when switching locally between old and new branches that some untracked files got left over:

```

--> git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	src/secp256k1/src/libsecp256k1-config.h
	src/secp256k1/src/libsecp256k1-config.h.in
	src/secp256k1/src/stamp-h1

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by pinheadmz** [comment]
Actually I still get the untracked files warning after merge -- am i doing something wrong? Or would it make any sense to add these to gitignore?

**Comment by hebasto** [comment]
@pinheadmz 
> Actually I still get the untracked files warning after merge -- am i doing something wrong?

Try to clean your local repo first. For example, `git clean -xdff`.

**Pull request merged**
