### PR TITLE
Refactor g_wallet_init_interface to const reference

### PR DESCRIPTION
**Pull request by promag**

### CODE REVIEW

**Comment by promag** [comment]
Requesting review from @sipa @laanwj and @jnewbery.

**Comment by practicalswift** [comment]
Concept ACK

**Comment by laanwj** [comment]
I'm not convinced that this is worth changing at this point, at the least it may conflict with other wallet interface changes in process.

**Comment by MarcoFalke** [comment]
utACK 6ec78f146134be7ee067a25a412d3c927f9ac353

**Comment by promag** [comment]
> it may conflict with other wallet interface change

@laanwj I believe there are none? Anyway wallet interface is pretty new and if this is a good change then the sooner the better.

**Comment by laanwj** [comment]
Ok in that case concept ack...

**Pull request merged**
