### PR TITLE
[Wallet] Bare segwit scriptPubKey should not considered change by the wallet

### PR DESCRIPTION
**Pull request by NicolasDorier**
As the test describe, segwit scriptPubKey are considered as change. It means that if you import the scriptPubKey, then send money to it, and call `listtransactions`, you will not see it. (contrary to p2sh scriptPubKey)

This PR makes it possible to use watchonly on segwit scriptPubKey.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
Not working after restart.... working on it.

**Comment by NicolasDorier** [comment]
For this PR to work, I would need to save `CWitKeyID` and `CWitKScriptID` from the `mapAddressBook` into `CWalletDB`. Problem is, now `CBitcoinAddress` is used to serialized `TxDestination` into string. This mean that `CBitcoinAddress` would need to support Bech32 or completely removed into another system (a new visitor?).

I think this PR will become useful for later, so I am not closing it.

**Comment by ryanofsky** [comment]
It seems like the code changes here are superceded by #11167, but maybe the new python test is useful to keep. Is this correct?

**Comment by NicolasDorier** [comment]
@ryanofsky the test have been included by sipa in another PR (I don't remember when though).

**Comment by NicolasDorier** [comment]
Closing this sipa already fixed it and included the test.

**Comment by NicolasDorier** [comment]
Was merged on https://github.com/bitcoin/bitcoin/commit/06eaca63139ac02abf82b0245b42493c9b383905

**Pull request closed without merging**
