### PR TITLE
Add src/qt/android/.gitignore

### PR DESCRIPTION
**Pull request by hebasto**
This PR makes `git` ignore files created by `make apk`.

### CODE REVIEW

**Comment by hebasto** [comment]
cc @icota

**Comment by icota** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/22078/commits/7d07192ddeaad28a26e3c4a54757a4f27f2a08ff

**Comment by laanwj** [comment]
Concept ACK

**Comment by hebasto** [comment]
@laanwj 
> Concept ACK; have not tested this, or reasoned which entries are necessary here

Only `/build` entry is not necessary due to the fact it is mentioned here: https://github.com/bitcoin/bitcoin/blob/b789914f1723e34966ec4b73292b6345a38a7d46/.gitignore#L110-L113

But given the context, I think it's better to include it explicitly here.

**Pull request merged**
