### PR TITLE
build: add background.tiff and .pngs to "make clean"

### PR DESCRIPTION
**Pull request by RandyMcMillan**
After the initial build
 
/bitcoin/background.tiff
/bitcoin/background.tiff.png 
/bitcoin/background.tiff@2x.png

persist.

They should be removed by `make clean`

Pretested prior to PR: https://travis-ci.org/RandyMcMillan/bitcoin/builds/607770432

### CODE REVIEW

**Comment by jonasschnelli** [comment]
utACK 5badb5733412729e38cc9792bc604ef66bddfd1a

**Comment by practicalswift** [comment]
ACK 5badb5733412729e38cc9792bc604ef66bddfd1a -- diff looks correct

**Comment by laanwj** [comment]
Obligatory question: this remove is safe for non-MacOS platforms right?

**Comment by RandyMcMillan** [comment]
If the files don’t exist they will be recreated like an initial build.

**Comment by laanwj** [comment]
The important thing here is that `$(OSX_BACKGROUND_IMAGE)` has a valid value, even when doing a non-macos build. If it would be empty, `$(OSX_BACKGROUND_IMAGE)@2x.png` would try to delete `@2x.png`, which is not the intent.

Looking at the `Makefile.am`, it's set outside any conditionals, so *I think* it's okay.

**Comment by laanwj** [comment]
Why did you close this?

**Comment by RandyMcMillan** [comment]
@laanwj - I was using the Mac Github app to review my commits before pushing - and there must have been some kind of bug. I just installed the update (I hope that fixes it). Kinda embarrassing. It explains some noise that I was creating earlier in my PRs which I apologized about. As you can see the PR is now displaying a bunch of commits that I couldn't see.

**Comment by RandyMcMillan** [comment]
make clean isn't removing the Bitcoin-Qt.dmg either so I am going to take a look at that anyway.

**Pull request closed without merging**
