### PR TITLE
[Move Only] Move wallet related sources to src/wallet/

### PR DESCRIPTION
**Pull request by jonasschnelli**
This looks after a heavy changeset, but it's not. This will only move wallet related files to `/src/wallet/`.
The PR includes no code changes.

Could once be renamed from `/src/wallet` to `/src/legacywallet`.

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
You forgot to git add the new directory, it looks like.

**Comment by jonasschnelli** [comment]
@TheBlueMatt Bah. Now added. Thanks.

**Comment by laanwj** [comment]
ACK (but needs rebase)

**Comment by jonasschnelli** [comment]
Rebased.

**Comment by theuni** [comment]
Since there's a reasonably clean separation of the wallet files, I'd prefer to build the objects in the subdir, same as qt and tests:

```diff
diff --git a/src/Makefile.am b/src/Makefile.am
index 88e7af2..1ff3180 100644
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -23,7 +23,7 @@ BITCOIN_INCLUDES=-I$(builddir) -I$(builddir)/obj $(BOOST_CPPFLAGS) $(LEVELDB_CPP
 BITCOIN_INCLUDES += -I$(srcdir)/secp256k1/include
 
 LIBBITCOIN_SERVER=libbitcoin_server.a
-LIBBITCOIN_WALLET=libbitcoin_wallet.a
+LIBBITCOIN_WALLET=wallet/libbitcoin_wallet.a
 LIBBITCOIN_COMMON=libbitcoin_common.a
 LIBBITCOIN_CLI=libbitcoin_cli.a
 LIBBITCOIN_UTIL=libbitcoin_util.a
@@ -46,7 +46,7 @@ EXTRA_LIBRARIES = \
   libbitcoin_cli.a
 if ENABLE_WALLET
 BITCOIN_INCLUDES += $(BDB_CPPFLAGS)
-EXTRA_LIBRARIES += libbitcoin_wallet.a
+EXTRA_LIBRARIES += $(LIBBITCOIN_WALLET)
 endif
 
 if BUILD_BITCOIN_LIBS
@@ -191,8 +191,8 @@ libbitcoin_server_a_SOURCES = \
 
 # wallet: shared between bitcoind and bitcoin-qt, but only linked
 # when wallet enabled
-libbitcoin_wallet_a_CPPFLAGS = $(BITCOIN_INCLUDES)
-libbitcoin_wallet_a_SOURCES = \
+wallet_libbitcoin_wallet_a_CPPFLAGS = $(BITCOIN_INCLUDES)
+wallet_libbitcoin_wallet_a_SOURCES = \
   wallet/db.cpp \
   crypter.cpp \
   wallet/rpcdump.cpp \
@@ -310,7 +310,7 @@ bitcoind_LDADD = \
   $(LIBSECP256K1)
 
 if ENABLE_WALLET
-bitcoind_LDADD += libbitcoin_wallet.a
+bitcoind_LDADD += $(LIBBITCOIN_WALLET)
 endif
 
 bitcoind_LDADD += $(BOOST_LIBS) $(BDB_LIBS) $(SSL_LIBS) $(CRYPTO_LIBS) $(MINIUPNPC_LIBS)
diff --git a/src/Makefile.qt.include b/src/Makefile.qt.include
index 31fe3a9..7b48b41 100644
--- a/src/Makefile.qt.include
+++ b/src/Makefile.qt.include
@@ -370,7 +370,7 @@ QT_QM=$(QT_TS:.ts=.qm)
 
 SECONDARY: $(QT_QM)
 
-qt/bitcoinstrings.cpp: $(libbitcoin_server_a_SOURCES) $(libbitcoin_wallet_a_SOURCES)
+qt/bitcoinstrings.cpp: $(libbitcoin_server_a_SOURCES) $(wallet_libbitcoin_wallet_a_SOURCES)
 	@test -n $(XGETTEXT) || echo "xgettext is required for updating translations"
 	$(AM_V_GEN) cd $(srcdir); XGETTEXT=$(XGETTEXT) ../share/qt/extract_strings_qt.py $^
 

```
That'd be my preference since imo it's cleaner, but I'm not strongly opposed to leaving it as-is.

ACK either way.

**Comment by jonasschnelli** [comment]
@theuni Yes. I think this should be the long term goal. Let me play with it.
What about the wallet tests under `src/wallet/test`? I assume we keep these in the `src/Makefile.test.include` for now?
The problem is, that currently other tests relay on a wallet. I try to slowly also decouple things there.

**Comment by theuni** [comment]
@jonasschnelli sure, no problem if things slowly move that way, no need to try to do it all at once. Yes, tests are fine as you handled them imo. Eventually we can create a Makefile.wallet.include once it's more decoupled.

**Comment by jtimon** [comment]
ut ACK

**Comment by jonasschnelli** [comment]
Rebased.

What if we merge this (has ACK from @theuni  and @laanwj)? This requires rebase often when getting out of date.
The makefile changes (https://github.com/bitcoin/bitcoin/pull/5745#issuecomment-72989968) could be done in a upcoming PR.

**Comment by paveljanik** [comment]
utACK

**Comment by fanquake** [comment]
utACK

**Comment by jonasschnelli** [comment]
Rebased and ready for merge. :)

**Pull request merged**
