### PR TITLE
ci: Update apt cache

### PR DESCRIPTION
**Pull request by hebasto**
This PR aims to fix the recent errors in the "test each commit" CI job:
```
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

### CODE REVIEW

**Comment by hebasto** [comment]
cc @maflcko

**Comment by ismaelsadeeq** [comment]
utACK 710da28c72259e1054bb63d2d81a8f3aea4c9000

**Comment by fanquake** [comment]
Would have been good to link-to/explain the failures here. Nothing in the PR description or commit messages about what broke, or why this is the fix.

**Comment by hebasto** [comment]
> Would have been good to link-to/explain the failures here. Nothing in the PR description or commit messages about what broke, or why this is the fix.

A self-explaining excerpt from a build log has been added to the PR description.

**Comment by fanquake** [comment]
Will be backported in #28872.

**Pull request merged**
