### PR TITLE
test: Avoid overwriting the NodeContext member of the testing setup [-Wshadow-field]

### PR DESCRIPTION
**Pull request by maflcko**
Adding this warning will eliminate unexpected test failures and hard to review code. Moreover, there shouldn't be a use case in Bitcoin Core that relies on fields to be shadowed.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Requested by @ryanofsky in https://github.com/bitcoin/bitcoin/pull/18923/files#r436093574

**Comment by MarcoFalke** [comment]
Can be tested by reverting the fix and observing the warning:

```
In file included from wallet/test/init_test_fixture.cpp:8:
./wallet/test/init_test_fixture.h:21:17: warning: non-static data member 'm_node' of 'InitWalletDirTestingSetup' shadows member inherited from type 'BasicTestingSetup' [-Wshadow-field]
    NodeContext m_node;
                ^
./test/util/setup_common.h:76:17: note: declared here
    NodeContext m_node;
                ^
1 warning generated.

**Comment by hebasto** [comment]
Concept ACK.

**Review by hebasto — APPROVED** [review]
ACK fac6b9b938230d24c13fcb6e9be28515d674c6c8, tested on Linux Mint 19.3 (x86_64):
- Clang 9.0.0 accepts `-Wshadow-field` and works as expected
- GCC 7.5.0 does not accept `-Wshadow-field`

The wider `-Wshadow` was disabled in #10136.

**Comment by practicalswift** [comment]
ACK fac6b9b938230d24c13fcb6e9be28515d674c6c8 -- patch looks correct

**Review by fanquake — APPROVED** [review]
ACK fac6b9b938230d24c13fcb6e9be28515d674c6c8 - Warnings compiling fa16e7816b886b82d36457b0d8edc773cba76421 are below. No warnings with fac6b9b938230d24c13fcb6e9be28515d674c6c8. The `-Wshadow-field` diagnostic has been available in Clang since 5.0.0. It's not available for GCC.

```bash
In file included from wallet/test/wallet_test_fixture.cpp:5:
./wallet/test/wallet_test_fixture.h:22:17: warning: non-static data member 'm_node' of 'WalletTestingSetup' shadows member inherited from type 'BasicTestingSetup' [-Wshadow-field]
    NodeContext m_node;
                ^
./test/util/setup_common.h:76:17: note: declared here
    NodeContext m_node;
                ^
1 warning generated.
....
In file included from wallet/test/init_test_fixture.cpp:8:
./wallet/test/init_test_fixture.h:21:17: warning: non-static data member 'm_node' of 'InitWalletDirTestingSetup' shadows member inherited from type 'BasicTestingSetup' [-Wshadow-field]
    NodeContext m_node;
                ^
./test/util/setup_common.h:76:17: note: declared here
    NodeContext m_node;
                ^
1 warning generated.
...
In file included from wallet/test/wallet_test_fixture.cpp:5:
./wallet/test/wallet_test_fixture.h:22:17: warning: non-static data member 'm_node' of 'WalletTestingSetup' shadows member inherited from type 'BasicTestingSetup' [-Wshadow-field]
    NodeContext m_node;
                ^
./test/util/setup_common.h:76:17: note: declared here
    NodeContext m_node;
                ^
1 warning generated.
...
In file included from wallet/test/init_tests.cpp:11:
./wallet/test/init_test_fixture.h:21:17: warning: non-static data member 'm_node' of 'InitWalletDirTestingSetup' shadows member inherited from type 'BasicTestingSetup' [-Wshadow-field]
    NodeContext m_node;
                ^
./test/util/setup_common.h:76:17: note: declared here
    NodeContext m_node;
                ^
1 warning generated.
  CXX      test/util/libtest_util_a-mining.o
  CXX      test/util/libtest_util_a-net.o
In file included from wallet/test/psbt_wallet_tests.cpp:12:
./wallet/test/wallet_test_fixture.h:22:17: warning: non-static data member 'm_node' of 'WalletTestingSetup' shadows member inherited from type 'BasicTestingSetup' [-Wshadow-field]
    NodeContext m_node;
                ^
./test/util/setup_common.h:76:17: note: declared here
    NodeContext m_node;
                ^
1 warning generated.
  CXX      test/util/libtest_util_a-setup_common.o
  CXX      test/util/libtest_util_a-str.o
  CXX      test/util/libtest_util_a-transaction_utils.o
  CXX      test/util/libtest_util_a-wallet.o
  CXX      bench/bench_bitcoin-addrman.o
  CXX      bench/bench_bitcoin-bench_bitcoin.o
  CXX      bench/bench_bitcoin-bench.o
  CXX      bench/bench_bitcoin-block_assemble.o
  CXX      bench/bench_bitcoin-checkblock.o
In file included from wallet/test/coinselector_tests.cpp:12:
./wallet/test/wallet_test_fixture.h:22:17: warning: non-static data member 'm_node' of 'WalletTestingSetup' shadows member inherited from type 'BasicTestingSetup' [-Wshadow-field]
    NodeContext m_node;
                ^
./test/util/setup_common.h:76:17: note: declared here
    NodeContext m_node;
                ^
1 warning generated.
  CXX      bench/bench_bitcoin-checkqueue.o
In file included from wallet/test/wallet_tests.cpp:22:
./wallet/test/wallet_test_fixture.h:22:17: warning: non-static data member 'm_node' of 'WalletTestingSetup' shadows member inherited from type 'BasicTestingSetup' [-Wshadow-field]
    NodeContext m_node;
                ^
./test/util/setup_common.h:76:17: note: declared here
    NodeContext m_node;
                ^
wallet/test/wallet_tests.cpp:538:17: warning: non-static data member 'm_node' of 'ListCoinsTestingSetup' shadows member inherited from type 'BasicTestingSetup' [-Wshadow-field]
    NodeContext m_node;
                ^
./test/util/setup_common.h:76:17: note: declared here
    NodeContext m_node;
                ^
2 warnings generated.
```

**Pull request merged**
