### PR TITLE
doc: Mention good first issue list in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by fanquake**

### CODE REVIEW

**Comment by MeshCollider** [comment]
Concept ACK, couple of typos though, `your => you're`, `checkout => check out`

**Comment by MeshCollider** [comment]
LGTM, ACK https://github.com/bitcoin/bitcoin/pull/13165/commits/a508091c59584476e3673543e4729fae5d6f2483

**Review by promag — COMMENTED** [review]
ACK.

**Comment by laanwj** [comment]
utACK a508091c59584476e3673543e4729fae5d6f2483

**Comment by sdaftuar** [comment]
ACK

**Comment by jamesob** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/13165/commits/a508091c59584476e3673543e4729fae5d6f2483

**Pull request merged**
