### PR TITLE
build: set CXXFLAGS for libressl probe

### PR DESCRIPTION
**Pull request by laanwj**
AC_LANG_PROGRAM checks using g++, not gcc, so set the right flags.
Otherwise, SSL_CFLAGS and CRYPTO_CFLAGS are ignored for this check.

### CODE REVIEW

**Comment by theuni** [comment]
Ugh, whoops. From a quick glance, ACK.

**Comment by jonasschnelli** [comment]
Looks reasonable.
utACK.

**Comment by laanwj** [comment]
Would prefer #6732 to go on, so closing this for now.

**Comment by MarcoFalke** [comment]
Note: #6732 got merged.

**Comment by luke-jr** [comment]
Should this be reconsidered for 0.10/0.11?

**Pull request closed without merging**
