### PR TITLE
Fix OSX dmg issue (10.12 to 10.14)

### PR DESCRIPTION
**Pull request by jonasschnelli**
This seems to fix the macOS 10.12+ DMG issue in conjunction with Gitian on Bionic

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Figured out the issue. It seems to be the python binary string option for the WindowBounds.

Gitian Build:
https://bitcoin.jonasschnelli.ch/build/852

Please test via you own Gitian Build (@fanquake, @Sjors, @ken2812221).

Removed WIP tag.

**Comment by promag** [comment]
Tested ACK 898b7c3 on macOS 10.14 with @jonasschnelli build.

**Comment by MarcoFalke** [comment]
Could change the subject of the commit to something more meaningful?

**Comment by jonasschnelli** [comment]
@MarcoFalke: fixed.

**Comment by Sjors** [comment]
What "DMG issue in conjunction with Gitian on Bionic" are you referring to? Opening the first Gitian DMG above crashes, while the second works fine, so I guess that's the issue?

Needs backport to 0.17?

Still works as expected when I do `make deploy` on macOS (before and after look the same):
after

Trying to build it using my own Gitian on Bionic is giving me headaches. I'm confused by the `gitian-builder.py` syntax. I tried the following:

```
cd bitcoin
git remote add jonasschnelli https://github.com/jonasschnelli/bitcoin.git
git fetch jonasschnelli
cd ..
python3 gitian-build.py --detach-sign --no-commit --url https://github.com/jonasschnelli/bitcoin -o m -c -b sjors 2018/10/osx_dmg
2018/10/osx_dmg
```

If you don't add the remote first you get (despite the `--url` argument):
```
error: pathspec '2018/10/osx_dmg' did not match any file(s) known to git.
```

But now I get:
schermafbeelding 2018-10-23 om 12 21 51

**Comment by Sjors** [comment]
Fixes #14414

**Comment by ken2812221** [comment]
@Sjors 
Try
```
python3 gitian-build.py --detach-sign --no-commit --pull 14416 -o m -b ...

**Comment by Sjors** [comment]
@ken2812221 worked like a charm, thanks.

My Gitian build produces a dmg that behaves on macOS 10.14

```sh
920c0defbb516bbf34550f9551563124f986bdd375730985d0e2891f4016883d  bitcoin-0.17.99-osx-unsigned.dmg
```
(@DrahtBot rebases on master so its hash is different)

tACK 43719e0

**Comment by MarcoFalke** [comment]
Is this for backport?

**Comment by Sjors** [comment]
@MarcoFalke yes this should be backported to 0.17, as currently macOS users can't install that without a workaround. No need to backport to 0.16, because - I just tested - it doesn't have the issue (because Gitian Trusty builds?).

**Comment by laanwj** [comment]
thank you for figuring it out! so it was a silly python unicode versus bytes issue :(
utACK 43719e0a3411e6a08e04908332cb44adfa00c6a2

**Comment by jnewbery** [comment]
Thanks for fixing this @jonasschnelli! I see that the same commit (https://github.com/bitcoin/bitcoin/commit/18f05c765c800126b74a6d5b7f33cef7c9aae1b7) that changed the `WindowsBounds` value from a string to a bytes object also changed `backgroundImageAlias` to a bytes object. Does that also need to be changed back to a string for Python 3?

**Comment by fanquake** [comment]
Backported in https://github.com/bitcoin/bitcoin/commit/eb2cc84a31fb923b2b25b979682904cb81edec7e.

**Pull request merged**
