### PR TITLE
Bugfix: RPC/mining: Fail properly in estimatesmartfee if smart fee data is unavailable

### PR DESCRIPTION
**Pull request by luke-jr**
Fixes a regression introduced by #22722

(Not entirely sure on the solution)

### CODE REVIEW

**Review by ghost — APPROVED** [review]
crACK https://github.com/bitcoin/bitcoin/pull/23547/commits/cd8d156354ed32a215de5eab5c394a1d74d91ed4

**Comment by benthecarman** [comment]
maybe worth for 22.1

**Review by darosior — COMMENTED** [review]
Arf, good catch..

utACK cd8d156354ed32a215de5eab5c394a1d74d91ed4

**Review by kristapsk — APPROVED** [review]
utACK cd8d156354ed32a215de5eab5c394a1d74d91ed4

**Comment by MarcoFalke** [comment]
A regression test might be nice

**Pull request merged**
