### PR TITLE
ci: Use apt-fast 🚀

### PR DESCRIPTION
**Pull request by maflcko**
See #17546

### CODE REVIEW

**Comment by MarcoFalke** [comment]
The only thing faster than apt-fast is @fanquake applying the label

**Comment by promag** [comment]
From https://travis-ci.org/bitcoin/bitcoin/jobs/615606977?utm_medium=notification&utm_source=github_status
```
11/22 15:40:49 [ERROR] Failed to load trusted CA certificates from /etc/ssl/certs/ca-certificates.crt. Cause: Error while reading file.
```

**Comment by laanwj** [comment]
This script seems a bit on the large side to include in the repository.

But let's see if it makes the CI a lot faster.

**Comment by MarcoFalke** [comment]
I get mixed results. Here are the times for the whole install script (Though that also includes a clone of the qa-assets repo)

install time | https://travis-ci.org/bitcoin/bitcoin/builds/615573771 | https://travis-ci.org/bitcoin/bitcoin/jobs/615606972 |
|--|--|--|
|arm64|78|105(!)|
|win|141|308(!)|
|32bit| 109|66|
|qt5|193|107|
|trusty|212|246(!)|
|xenial|234|383(!)|
|asan|258|149|
|fuzz|121|71|
|no_wallet|95|58|
|mac|161|90|

**Comment by laanwj** [comment]
Yes those are mixed results. Some times are almost halved, others become significantly slower.

I wonder how much of that is due to the script itself or Travis' own pretty much extreme variance in runtime.

**Comment by elichai** [comment]
Back when I was using Debian/Ubuntu I used `apt-fast` for a while and then stopped because it wasn't really faster over time

**Comment by laanwj** [comment]
Selecting a better mirror can already make a big difference.

**Pull request closed without merging**
