### PR TITLE
guix: Add support for powerpc64{,le}

### PR DESCRIPTION
**Pull request by dongcarl**
```
The new time-machine commit contains a few small changes that make the
powerpc cross-toolchain work.
```

See this compare to review my custom patches to Guix: https://github.com/dongcarl/guix/compare/7d6bd44da57926e0d4af25eba723a61c82beef98...6c9d16db962a6f7155571b36eced681fd2889e23

### CODE REVIEW

**Comment by laanwj** [comment]
Changes look good to me, didn't test or review in detail yet. Concept ACK.

**Comment by laanwj** [comment]
Trying to run the guix build on a bare ubuntu server image i get the following errors:
```
user@guix:~/bitcoin$ ./contrib/guix/guix-build.sh     
/bin/sh: 1: gcc: not found     
/bin/sh: 1: gcc: not found                                                                                
/bin/sh: 1: g++: not found                                                                                
/bin/sh: 1: g++: not found                                                                                
env: '/home/user/bitcoin/depends/x86_64-apple-darwin18/native/bin/clang': No such file or directory
env: '/home/user/bitcoin/depends/x86_64-apple-darwin18/native/bin/clang': No such file or directory
env: '/home/user/bitcoin/depends/x86_64-apple-darwin18/native/bin/clang++': No such file or directory
env: '/home/user/bitcoin/depends/x86_64-apple-darwin18/native/bin/clang++': No such file or directory
```
Is it necessary to install `gcc` and g++`  outside of guix?

It does continue, no idea if it will complete.

**Comment by dongcarl** [comment]
> Is it necessary to install `gcc` and `g++` outside of guix?

No I don't think so.

I'm almost certain this is caused by the `depends` download triggering some "immediate" variables in our depends `Makefile` from evaluating... Shouldn't harm anything, but lemme dig and see where this is.

**Comment by laanwj** [comment]
Buld success (commit f4ae44c76feeb6a4400c374cb7641caf89f3b8ae):
```
0c3355d662c9828be853c774fac9e9ae38538dfae0e86193b9c427d4f6652940  output/bitcoin-f4ae44c76fee-powerpc64-linux-gnu-debug.tar.gz
d56c3b095f63bd00466c1765dd83c21a886ef9ce3695745fed55a176f7b2e3aa  output/bitcoin-f4ae44c76fee-powerpc64-linux-gnu.tar.gz
3209447188534bb2135030c2abaad9e2e5b4a69130720a5ad667bc746c7ae4de  output/bitcoin-f4ae44c76fee-powerpc64le-linux-gnu-debug.tar.gz
03424501de81bcc9126e55dd01a3f48d0607ed5b6c782af0fbada9d68b8b83ac  output/bitcoin-f4ae44c76fee-powerpc64le-linux-gnu.tar.gz
```

**Comment by fanquake** [comment]
Builds at 62cc2180afc1f2e2465eefb9b589a3b3a23d6376:
```bash
d29bb491a712da73a146ba7cf7935e1cf2ee491fbbc92ac8bd59e3a41126ed5d  output/bitcoin-62cc2180afc1-powerpc64-linux-gnu-debug.tar.gz
d5065882b91b004f68cedb48b6704081fdf7368a2c2854c240bba6533adb0e97  output/bitcoin-62cc2180afc1-powerpc64-linux-gnu.tar.gz
4ffa90656e515b9aa714eaa062f8172df467c3bc585210356c05d40f2341dd4f  output/bitcoin-62cc2180afc1-powerpc64le-linux-gnu-debug.tar.gz
4b23bfb20afcf2924dd8eb6d3fac9fad5109f1516a0fe0343e0e7f6fa87af784  output/bitcoin-62cc2180afc1-powerpc64le-linux-gnu.tar.gz
e4a05d6a09d824c10a3d6157a294b65e1053125a98c9a51f1f6d5b2d8c44e3ba  output/src/bitcoin-62cc2180afc1.tar.gz
```

**Comment by laanwj** [comment]
Can reproduce @fanquake's results :tada: 
```
d29bb491a712da73a146ba7cf7935e1cf2ee491fbbc92ac8bd59e3a41126ed5d  output/bitcoin-62cc2180afc1-powerpc64-linux-gnu-debug.tar.gz
d5065882b91b004f68cedb48b6704081fdf7368a2c2854c240bba6533adb0e97  output/bitcoin-62cc2180afc1-powerpc64-linux-gnu.tar.gz
4ffa90656e515b9aa714eaa062f8172df467c3bc585210356c05d40f2341dd4f  output/bitcoin-62cc2180afc1-powerpc64le-linux-gnu-debug.tar.gz
4b23bfb20afcf2924dd8eb6d3fac9fad5109f1516a0fe0343e0e7f6fa87af784  output/bitcoin-62cc2180afc1-powerpc64le-linux-gnu.tar.gz
e4a05d6a09d824c10a3d6157a294b65e1053125a98c9a51f1f6d5b2d8c44e3ba  output/src/bitcoin-62cc2180afc1.tar.gz
```

**Comment by MarcoFalke** [comment]
```
sha256sum output/{,src/}bitcoin*
e95c04f190722a5577b2a3f78463d01f13f87f748ec63d1df325db68a578e677  output/bitcoin-62cc2180afc1-powerpc64-linux-gnu-debug.tar.gz
cd6b14920197c0fcdae0609908359a1c2e3af8bb45590abc079f1d4bff5e9d0a  output/bitcoin-62cc2180afc1-powerpc64-linux-gnu.tar.gz
e4a05d6a09d824c10a3d6157a294b65e1053125a98c9a51f1f6d5b2d8c44e3ba  output/src/bitcoin-62cc2180afc1.tar.gz
```

Download: https://github.com/MarcoFalke/drahtbox/releases/download/none/bitcoin-62cc2180afc1-powerpc64-linux-gnu.tar.gz

I compiled on `aarch64`, which is not allowed, I presume?

**Comment by laanwj** [comment]
@MarcoFalke i'd say it is allowed i'll want to do my future builds on RV64.

Would be good to investigate what is different in your results (and whether they differ for other target architectures than POWER too).

That said, i don't think "determinism when building on other architectures" is a blocker for this PR, might want to open a new issue for that.

**Comment by laanwj** [comment]
I did another build for this on the GUIX distribution (x86_64) instead of installing it on top of another. After setting up a VM starting from the QEMU image, and setting up ssh access for `guest` (which wasn't that complicated but had to re-learn a bit of LISP in the process) it was completely straightforward:

```bash
# (copy in Xcode-11.3.1-11C505-extracted-SDK-with-libcxx-headers.tar.gz through scp or such …)
guix install git make curl
git clone https://github.com/bitcoin/bitcoin.git
cd bitcoin

mkdir -p depends/SDKs
cd depends/SDKs
tar -zxf ~/Xcode-11.3.1-11C505-extracted-SDK-with-libcxx-headers.tar.gz
cd ../..

contrib/guix/guix-build.sh
```

Output:

```
4ffa90656e515b9aa714eaa062f8172df467c3bc585210356c05d40f2341dd4f  output/bitcoin-62cc2180afc1-powerpc64le-linux-gnu-debug.tar.gz
4b23bfb20afcf2924dd8eb6d3fac9fad5109f1516a0fe0343e0e7f6fa87af784  output/bitcoin-62cc2180afc1-powerpc64le-linux-gnu.tar.gz
d29bb491a712da73a146ba7cf7935e1cf2ee491fbbc92ac8bd59e3a41126ed5d  output/bitcoin-62cc2180afc1-powerpc64-linux-gnu-debug.tar.gz
d5065882b91b004f68cedb48b6704081fdf7368a2c2854c240bba6533adb0e97  output/bitcoin-62cc2180afc1-powerpc64-linux-gnu.tar.gz
e4a05d6a09d824c10a3d6157a294b65e1053125a98c9a51f1f6d5b2d8c44e3ba  output/src/bitcoin-62cc2180afc1.tar.gz
```
Matches my results on Ubuntu and @fanquake's.

**Comment by laanwj** [comment]
Drahtbot build issue is:
```
/gnu/store/25s9l7cgwz01qq3crbh1dpfw69gvvna4-profile/bin/install: error writing '/distsrc-base/distsrc-a6b382150bcc-powerpc64le-linux-gnu/installed/bitcoin-a6b382150bcc//bin/test_bitcoin': No space left on device
make[3]: *** [Makefile:4521: install-binPROGRAMS] Error 1
```

**Comment by MarcoFalke** [comment]
Yeah, I am confused about that. I have ~30GB of free disk space, which seems like enough?

```
$ df -h ./
Filesystem      Size  Used Avail Use% Mounted on
/dev/root       146G  117G   29G  81% /

**Comment by laanwj** [comment]
i don't know ? gitiian deletes the intermediate build files between builds for each architecture, i don't know if the GUIX build currently does; fwiw my GUIX VM after the build:
```
/dev/vda1        79G   61G   15G  81% /
```

**Comment by MarcoFalke** [comment]
Maybe the docs should be updated here to clarify that 60 GB are now needed? https://github.com/bitcoin/bitcoin/blob/fa051c23860bcdcc871db5ad6b51b8d9ca88da35/contrib/guix/README.md#requirements

**Comment by MarcoFalke** [comment]
> might want to open a new issue for that.

Done in #21194

**Comment by dongcarl** [comment]
Pushed 62cc2180afc1f2e2465eefb9b589a3b3a23d6376 -> 4dd3c2ffe283ed6ff30d1ca1eaf2a50c1c643fff
- Rebase on master for merge of #20629
- Updated conservative size estimates following laanwj and MarcoFalke's conversations above

-----

Thanks MarcoFalke for opening #21194, would be great to get it reproducible across architectures as a stretch goal!

Usability notes:
1. Find a way to suppress the harmless yet alarming warnings: https://github.com/bitcoin/bitcoin/pull/21089#issuecomment-777562303
2. Perhaps add an `XCODE_SDK_TARBALL` env var to `contrib/guix/guix-build.sh` to avoid manual untarring

**Comment by dongcarl** [comment]
Pushed 4dd3c2ffe283ed6ff30d1ca1eaf2a50c1c643fff -> 857d98daa5dd778c6fdf7d58c65653c569e5a35d
- Rebase for merge of base PR #21087

**Comment by dongcarl** [comment]
Pushed 857d98daa5dd778c6fdf7d58c65653c569e5a35d -> 95990b9f3278360b63e79d6975af4ab5009c66ba
- Rebase for merge of base PR #21088

**Comment by fanquake** [comment]
I'm seeing a mismatch with `bitcoin-95990b9f3278-win64.zip` and `bitcoin-95990b9f3278-win64-debug.zip`:
```bash
bash-5.1# find output/ -type f -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum
89d8a12bba6c455b673bd6c8cc4ce7b4f9def7df7259ae514757344083293523  output/bitcoin-95990b9f3278-aarch64-linux-gnu-debug.tar.gz
4c885962e3c3b5b79c9ab04a93e717cebb67130b0e74bb3514cec1d40de8cc0b  output/bitcoin-95990b9f3278-aarch64-linux-gnu.tar.gz
a1bb294d91bf53e0e40df7b259503182a77c515fc8fbbbb7d5437e3560c8d1ce  output/bitcoin-95990b9f3278-arm-linux-gnueabihf-debug.tar.gz
8bfc10b51d6fd3c694f67da315065997fc4a599961dfd352cfdcc3a3e0bf53c9  output/bitcoin-95990b9f3278-arm-linux-gnueabihf.tar.gz
f8640d5d7880a3b9d9b65547e1ea85a1114d7ecc25729aa5e0e2a8141b564723  output/bitcoin-95990b9f3278-osx-unsigned.dmg
6d1b91124bd4386327c23a16e075aa4d9d93330dc53a4882c5f0f06c83509079  output/bitcoin-95990b9f3278-osx-unsigned.tar.gz
75796657f3d5c77d971abb4dc99114df6e964b3e4de6061756b01b0867aa8d27  output/bitcoin-95990b9f3278-osx64.tar.gz
060aaf3cc00a5470d5b68c021afc16f56afe6cace335c935d99e67ad695648d5  output/bitcoin-95990b9f3278-powerpc64-linux-gnu-debug.tar.gz
48ce7c67ea620ed84251923a7a29c050e57d52548df1ec21dd9c5b252b2de2c6  output/bitcoin-95990b9f3278-powerpc64-linux-gnu.tar.gz
f37029a01bd8cb6479ce6c1eba9cf442b9562c5557aa1ef6c2f31294ff993de6  output/bitcoin-95990b9f3278-powerpc64le-linux-gnu-debug.tar.gz
b4216539ba7b66009aec6d086fa1b6583ee856d7a4d7093da5a5ed8067231e6a  output/bitcoin-95990b9f3278-powerpc64le-linux-gnu.tar.gz
ec373358e29eb7039a7d8f1934fe8ac4167bec55e1799b345c7bc6f9459ab2c1  output/bitcoin-95990b9f3278-riscv64-linux-gnu-debug.tar.gz
7406f147a1fc24d599a0cf5bfd7a69d0f6146b3c4849daeb640c6a83987ceb79  output/bitcoin-95990b9f3278-riscv64-linux-gnu.tar.gz
258cf66fec82fee8c4ef41c33fe9afce23f80b63deba5b2e9b3f54d541da746f  output/bitcoin-95990b9f3278-win-unsigned.tar.gz
68b7d61e61bd6305343e9cb80a2244403b4ae30c586313126f0c0e4ef6935bb2  output/bitcoin-95990b9f3278-win64-debug.zip
a2f8c81815991971131fb7c7ec35e03fc9057984fcfe4ae86eeba4c20ac53858  output/bitcoin-95990b9f3278-win64-setup-unsigned.exe
e9a25fc9355fbaf8ddaaff7eea8ac3e18ef0fcb2dc12f4744c406189bd6389d6  output/bitcoin-95990b9f3278-win64.zip
f87f5583f7bd42d6ef3d22cc3379d462124b546d7eb8f8eed1240b6ee20ff8ab  output/bitcoin-95990b9f3278-x86_64-linux-gnu-debug.tar.gz
dbb746cb5128cea7c79ade844a8961636e362c9489dede4637e3b1111761fc77  output/bitcoin-95990b9f3278-x86_64-linux-gnu.tar.gz
e112d90e3527c2f2efcebe642c031e87ccba005b43c43a57edd7cea64349e531  output/src/bitcoin-95990b9f3278.tar.gz
```

My build artifacts are available here: https://github.com/fanquake/build_artifacts/releases/tag/guix_21089.

**Comment by MarcoFalke** [comment]
https://github.com/MarcoFalke/drahtbox/releases/tag/bitcoin-95990b9f3278

```
89d8a12bba6c455b673bd6c8cc4ce7b4f9def7df7259ae514757344083293523  output/bitcoin-95990b9f3278-aarch64-linux-gnu-debug.tar.gz
4c885962e3c3b5b79c9ab04a93e717cebb67130b0e74bb3514cec1d40de8cc0b  output/bitcoin-95990b9f3278-aarch64-linux-gnu.tar.gz
a1bb294d91bf53e0e40df7b259503182a77c515fc8fbbbb7d5437e3560c8d1ce  output/bitcoin-95990b9f3278-arm-linux-gnueabihf-debug.tar.gz
8bfc10b51d6fd3c694f67da315065997fc4a599961dfd352cfdcc3a3e0bf53c9  output/bitcoin-95990b9f3278-arm-linux-gnueabihf.tar.gz
060aaf3cc00a5470d5b68c021afc16f56afe6cace335c935d99e67ad695648d5  output/bitcoin-95990b9f3278-powerpc64-linux-gnu-debug.tar.gz
48ce7c67ea620ed84251923a7a29c050e57d52548df1ec21dd9c5b252b2de2c6  output/bitcoin-95990b9f3278-powerpc64-linux-gnu.tar.gz
f37029a01bd8cb6479ce6c1eba9cf442b9562c5557aa1ef6c2f31294ff993de6  output/bitcoin-95990b9f3278-powerpc64le-linux-gnu-debug.tar.gz
b4216539ba7b66009aec6d086fa1b6583ee856d7a4d7093da5a5ed8067231e6a  output/bitcoin-95990b9f3278-powerpc64le-linux-gnu.tar.gz
ec373358e29eb7039a7d8f1934fe8ac4167bec55e1799b345c7bc6f9459ab2c1  output/bitcoin-95990b9f3278-riscv64-linux-gnu-debug.tar.gz
7406f147a1fc24d599a0cf5bfd7a69d0f6146b3c4849daeb640c6a83987ceb79  output/bitcoin-95990b9f3278-riscv64-linux-gnu.tar.gz
258cf66fec82fee8c4ef41c33fe9afce23f80b63deba5b2e9b3f54d541da746f  output/bitcoin-95990b9f3278-win-unsigned.tar.gz
68b7d61e61bd6305343e9cb80a2244403b4ae30c586313126f0c0e4ef6935bb2  output/bitcoin-95990b9f3278-win64-debug.zip
a2f8c81815991971131fb7c7ec35e03fc9057984fcfe4ae86eeba4c20ac53858  output/bitcoin-95990b9f3278-win64-setup-unsigned.exe
e9a25fc9355fbaf8ddaaff7eea8ac3e18ef0fcb2dc12f4744c406189bd6389d6  output/bitcoin-95990b9f3278-win64.zip
f87f5583f7bd42d6ef3d22cc3379d462124b546d7eb8f8eed1240b6ee20ff8ab  output/bitcoin-95990b9f3278-x86_64-linux-gnu-debug.tar.gz
dbb746cb5128cea7c79ade844a8961636e362c9489dede4637e3b1111761fc77  output/bitcoin-95990b9f3278-x86_64-linux-gnu.tar.gz

**Comment by MarcoFalke** [comment]
(seems to be matching fanquake)

**Comment by laanwj** [comment]
My output matches @fanuake's and @MarcoFalke's exactly

**Comment by dongcarl** [comment]
Investigated a bit, seems like a difference in `umask`?

Here's my `umask` on the machine where I ran this build:
```sh
$ umask
0002
```

I see that on other machines `umask` is 0022.

Shall we set the `umask` to 0022 at the beginning of our `guix-build.sh` script?

```sh
$ diffoscope focal-virt/bitcoin-95990b9f3278-win64-debug.zip fanquake/bitcoin-95990b9f3278-win64-debug.zip
--- focal-virt/bitcoin-95990b9f3278-win64-debug.zip
+++ fanquake/bitcoin-95990b9f3278-win64-debug.zip
├── zipinfo {}
│ @@ -1,10 +1,10 @@
│  Zip file size: 441816619 bytes, number of entries: 8
│ --rwxrwxr-x  3.0 unx 37351236 b- defN 21-Feb-16 17:29 bitcoin-95990b9f3278/bin/bitcoin-cli.exe.dbg
│ --rwxrwxr-x  3.0 unx 612859596 b- defN 21-Feb-16 17:29 bitcoin-95990b9f3278/bin/bitcoin-qt.exe.dbg
│ --rwxrwxr-x  3.0 unx 56000510 b- defN 21-Feb-16 17:29 bitcoin-95990b9f3278/bin/bitcoin-tx.exe.dbg
│ --rwxrwxr-x  3.0 unx 37965401 b- defN 21-Feb-16 17:29 bitcoin-95990b9f3278/bin/bitcoin-util.exe.dbg
│ --rwxrwxr-x  3.0 unx 205062558 b- defN 21-Feb-16 17:29 bitcoin-95990b9f3278/bin/bitcoin-wallet.exe.dbg
│ --rwxrwxr-x  3.0 unx 449083928 b- defN 21-Feb-16 17:29 bitcoin-95990b9f3278/bin/bitcoind.exe.dbg
│ --rwxrwxr-x  3.0 unx 907142051 b- defN 21-Feb-16 17:29 bitcoin-95990b9f3278/bin/test_bitcoin.exe.dbg
│ --rwxrwxr-x  3.0 unx 12217326 b- defN 21-Feb-16 17:29 bitcoin-95990b9f3278/lib/libbitcoinconsensus-0.dll.dbg
│ +-rwxr-xr-x  3.0 unx 37351236 b- defN 21-Feb-16 17:29 bitcoin-95990b9f3278/bin/bitcoin-cli.exe.dbg
│ +-rwxr-xr-x  3.0 unx 612859596 b- defN 21-Feb-16 17:29 bitcoin-95990b9f3278/bin/bitcoin-qt.exe.dbg
│ +-rwxr-xr-x  3.0 unx 56000510 b- defN 21-Feb-16 17:29 bitcoin-95990b9f3278/bin/bitcoin-tx.exe.dbg
│ +-rwxr-xr-x  3.0 unx 37965401 b- defN 21-Feb-16 17:29 bitcoin-95990b9f3278/bin/bitcoin-util.exe.dbg
│ +-rwxr-xr-x  3.0 unx 205062558 b- defN 21-Feb-16 17:29 bitcoin-95990b9f3278/bin/bitcoin-wallet.exe.dbg
│ +-rwxr-xr-x  3.0 unx 449083928 b- defN 21-Feb-16 17:29 bitcoin-95990b9f3278/bin/bitcoind.exe.dbg
│ +-rwxr-xr-x  3.0 unx 907142051 b- defN 21-Feb-16 17:29 bitcoin-95990b9f3278/bin/test_bitcoin.exe.dbg
│ +-rwxr-xr-x  3.0 unx 12217326 b- defN 21-Feb-16 17:29 bitcoin-95990b9f3278/lib/libbitcoinconsensus-0.dll.dbg
│  8 files, 2317682606 bytes uncompressed, 441815265 bytes compressed:  80.9%
```

```sh
$ diffoscope focal-virt/bitcoin-95990b9f3278-win64.zip fanquake/bitcoin-95990b9f3278-win64.zip
--- focal-virt/bitcoin-95990b9f3278-win64.zip
+++ fanquake/bitcoin-95990b9f3278-win64.zip
├── zipinfo {}
│ @@ -1,25 +1,25 @@
│  Zip file size: 33782287 bytes, number of entries: 23
│ -drwxrwxr-x  3.0 unx        0 b- stor 21-Feb-16 17:29 bitcoin-95990b9f3278/
│ -drwxrwxr-x  3.0 unx        0 b- stor 21-Feb-16 17:29 bitcoin-95990b9f3278/bin/
│ +drwxr-xr-x  3.0 unx        0 b- stor 21-Feb-16 17:29 bitcoin-95990b9f3278/
│ +drwxr-xr-x  3.0 unx        0 b- stor 21-Feb-16 17:29 bitcoin-95990b9f3278/bin/
│  -rwxr-xr-x  3.0 unx  2069523 b- defN 21-Feb-16 17:29 bitcoin-95990b9f3278/bin/bitcoin-cli.exe
│  -rwxr-xr-x  3.0 unx 31886879 b- defN 21-Feb-16 17:29 bitcoin-95990b9f3278/bin/bitcoin-qt.exe
│  -rwxr-xr-x  3.0 unx  2385939 b- defN 21-Feb-16 17:29 bitcoin-95990b9f3278/bin/bitcoin-tx.exe
│  -rwxr-xr-x  3.0 unx  1894931 b- defN 21-Feb-16 17:29 bitcoin-95990b9f3278/bin/bitcoin-util.exe
│  -rwxr-xr-x  3.0 unx  7110675 b- defN 21-Feb-16 17:29 bitcoin-95990b9f3278/bin/bitcoin-wallet.exe
│  -rwxr-xr-x  3.0 unx 12144659 b- defN 21-Feb-16 17:29 bitcoin-95990b9f3278/bin/bitcoind.exe
│  -rwxr-xr-x  3.0 unx 20453907 b- defN 21-Feb-16 17:29 bitcoin-95990b9f3278/bin/test_bitcoin.exe
│ -drwxrwxr-x  3.0 unx        0 b- stor 21-Feb-16 17:29 bitcoin-95990b9f3278/include/
│ +drwxr-xr-x  3.0 unx        0 b- stor 21-Feb-16 17:29 bitcoin-95990b9f3278/include/
│  -rw-r--r--  3.0 unx     3660 t- defN 21-Feb-16 17:29 bitcoin-95990b9f3278/include/bitcoinconsensus.h
│ -drwxrwxr-x  3.0 unx        0 b- stor 21-Feb-16 17:29 bitcoin-95990b9f3278/lib/
│ +drwxr-xr-x  3.0 unx        0 b- stor 21-Feb-16 17:29 bitcoin-95990b9f3278/lib/
│  -rwxr-xr-x  3.0 unx  1442323 b- defN 21-Feb-16 17:29 bitcoin-95990b9f3278/lib/libbitcoinconsensus-0.dll
│ --rw-rw-r--  3.0 unx      846 t- defN 21-Feb-16 17:29 bitcoin-95990b9f3278/readme.txt
│ -drwxrwxr-x  3.0 unx        0 b- stor 21-Feb-16 17:29 bitcoin-95990b9f3278/share/
│ -drwxrwxr-x  3.0 unx        0 b- stor 21-Feb-16 17:29 bitcoin-95990b9f3278/share/man/
│ -drwxrwxr-x  3.0 unx        0 b- stor 21-Feb-16 17:29 bitcoin-95990b9f3278/share/man/man1/
│ +-rw-r--r--  3.0 unx      846 t- defN 21-Feb-16 17:29 bitcoin-95990b9f3278/readme.txt
│ +drwxr-xr-x  3.0 unx        0 b- stor 21-Feb-16 17:29 bitcoin-95990b9f3278/share/
│ +drwxr-xr-x  3.0 unx        0 b- stor 21-Feb-16 17:29 bitcoin-95990b9f3278/share/man/
│ +drwxr-xr-x  3.0 unx        0 b- stor 21-Feb-16 17:29 bitcoin-95990b9f3278/share/man/man1/
│  -rw-r--r--  3.0 unx      214 t- defN 21-Feb-16 17:29 bitcoin-95990b9f3278/share/man/man1/bitcoin-cli.1
│  -rw-r--r--  3.0 unx      211 t- defN 21-Feb-16 17:29 bitcoin-95990b9f3278/share/man/man1/bitcoin-qt.1
│  -rw-r--r--  3.0 unx      211 t- defN 21-Feb-16 17:29 bitcoin-95990b9f3278/share/man/man1/bitcoin-tx.1
│  -rw-r--r--  3.0 unx      217 t- defN 21-Feb-16 17:29 bitcoin-95990b9f3278/share/man/man1/bitcoin-util.1
│  -rw-r--r--  3.0 unx      223 t- defN 21-Feb-16 17:29 bitcoin-95990b9f3278/share/man/man1/bitcoin-wallet.1
│  -rw-r--r--  3.0 unx      205 t- defN 21-Feb-16 17:29 bitcoin-95990b9f3278/share/man/man1/bitcoind.1
│  23 files, 79394623 bytes uncompressed, 33778727 bytes compressed:  57.5%
```

**Comment by laanwj** [comment]
> Shall we set the umask to 0022 at the beginning of our guix-build.sh script?

Maybe. I'm a bit disappointed that Guix doesn't handle this itself! It seems like one of the first things you'd want to be robust against (apart from time, environment, username) when doing deterministic builds.

That said sure we can do it was a workaround.

**Comment by dongcarl** [comment]
> I'm a bit disappointed that Guix doesn't handle this itself! It seems like one of the first things you'd want to be robust against (apart from time, environment, username) when doing deterministic builds.

To be clear, when `guix-daemon` is building a package in its isolated container, `umask` _is_ set. I think `guix environment` doesn't set it because it's meant to be more of an "overlay" on top of your existing system (at least when `--container` is not supplied).

**Comment by dongcarl** [comment]
I opened #21271 to fix the non-reproducibility separately. I think this PR is ready for merge.

**Review by fanquake — APPROVED** [review]
ACK 95990b9f3278360b63e79d6975af4ab5009c66ba

**Pull request merged**
