### PR TITLE
util: warn about ignored recursive -includeconf calls

### PR DESCRIPTION
**Pull request by kallewoof**
This is a follow-up PR to #10267, and addresses https://github.com/bitcoin/bitcoin/pull/10267#issuecomment-387546144.

~~I am adding extra work for @jnewbery in #12755 here -- maybe I should just rebase on top of that, but not sure what the appropriate approach is here.~~

### CODE REVIEW

**Comment by laanwj** [comment]
> I am adding extra work for @jnewbery in #12755 here -- maybe I should just rebase on top of that, but not sure what the appropriate approach is here.

I (personally) prefer if PRs are more or less independent.
As having a web of dependencies between them makes it even harder to keep track of them.
On the other hand, #10267 is now in, and #12755 should probably be next.

**Comment by kallewoof** [comment]
@laanwj Makes sense. I will leave this as is and adjust it once #12755 is merged.

**Comment by promag** [comment]
utACK 6f10309.

BTW couldn't `cs_args` be locked the whole time?

**Comment by jnewbery** [comment]
concept ACK (and quick skim utACK). Will review & test after #12755 is merged.

**Comment by laanwj** [comment]
#12755 is merged, please rebase

**Comment by kallewoof** [comment]
Rebased.

**Comment by laanwj** [comment]
> @promag Is it better locking the whole time?

I don't know what the potential races here are, but If everything else is the same, keeping the lock closely around the section where it is needed is preferable. Also: calls such as `GetArgs` take their own lock, so already holding it is sloppy.

**Comment by promag** [comment]
@laanwj I mean, `ReadConfigFiles` should be an **atomic** operation right?

**Comment by laanwj** [comment]
> ReadConfigFiles should be an atomic operation right?

As far as I know we don't really make any assumptions in that regard right now, but in sane API design I think that makes sense.

**Comment by kallewoof** [comment]
I can try moving the lock to the top of the method and remove it elsewhere. I am concerned it may cause deadlocks though.

**Comment by kallewoof** [comment]
ba5b9fc

**Comment by promag** [comment]
@kallewoof I think it's great to change that but in a different PR. Commit 6f10309 is enough here. Sorry for asking here!

**Comment by laanwj** [comment]
utACK 2352aa9f3681fbcfb89a1910d9c5529dac9ca2e9

**Pull request merged**
