### PR TITLE
test: Remove python dead code linter

### PR DESCRIPTION
**Pull request by laanwj**
Primarily I'd like to remove this because it is very imprecise, due to Python's dynamic nature, giving it a large list of false positives that need to be listed as exceptions. See for example #16906.

It's also a frequent source of complaints. I'm doubtful of the usefulness of checking for dead code in a linter in the first place.
Having some dead code in the test framework for a while is not a
disaster.

### CODE REVIEW

**Comment by practicalswift** [comment]
ACK f4beb4996d27f2cdaf4f0a63e7dc044bf17decce - empirically the cost seems to exceed the benefit for this specific linter

**Comment by laanwj** [comment]
The thing is, I don't particularly want the list of exceptions to need to be maintained as part of the repository anymore.

**Comment by sdaftuar** [comment]
utACK f4beb4996d27f2cdaf4f0a63e7dc044bf17decce

**Comment by practicalswift** [comment]
ACK f4beb4996d27f2cdaf4f0a63e7dc044bf17decce -- diff looks correct

**Comment by jamesob** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/16961/commits/f4beb4996d27f2cdaf4f0a63e7dc044bf17decce

**Comment by luke-jr** [comment]
Concept ACK

**Comment by promag** [comment]
Bye ACK.

**Comment by MarcoFalke** [comment]
Going to merge this, as there is overwhelming support for it and it is probably not worth to spend more time discussion on it.

**Comment by laanwj** [comment]
> Going to merge this, as there is overwhelming support for it and it is probably not worth to spend more time discussion on it.

Thanks. Maybe in the future at some point this tool will be mature enough to use in a setting like this, and we can re-evaluate, but for now it's too much bother.

**Comment by flack** [comment]
I wonder if it would have been better to change `min-confidence` to `100` (or something) instead. At least that would have probably caught #21081. Having dead code in the test _framework_ may not be a disaster, but having it in the test themselves seems slightly more worrying

**Comment by MarcoFalke** [comment]
@flack Pull requests are welcome if it can be show that the previously observed issues, false positives, and annoyances are fixed

**Comment by flack** [comment]
@MarcoFalke thanks, I literally have no Python skills whatsoever, but who knows, maybe I'll give it a try. ofc, if someone more qualified wants to give it a try, have at it!

**Comment by laanwj** [comment]
The underlying problem here was that determining reachability statically an undecidable issue for python. This caused issue after issue. I don't think that changed.

**Comment by flack** [comment]
Sure, but even not knowing Python I cannot imagine there's a way for code after a return statement to ever be run. So I still think `--min-confidence 100` might be worth a try, i.e. tell the linter to skip the fancy guesswork and just report stuff it's 100% sure about.

**Pull request merged**
