### PR TITLE
doc: Correct PR Review Club frequency from weekly to monthly

### PR DESCRIPTION
**Pull request by GabrieleBocchi**
The PR Review Club is mentioned as weekly in the CONTRIBUTING.md file, but it is held monthly as per the official [Bitcoin Core PR Review Club website](https://bitcoincore.reviews/). This PR updates the documentation to just remove the frequency.

### CODE REVIEW

**Review by jonatack — COMMENTED** [review]
Perhaps drop the periodicity altogether, as it may evolve. 

(In which case, could also drop the word "meeting".)

**Review by tdb3 — COMMENTED** [review]
Concept ACK
I agree with the suggestion from @jonatack. It'd be good to drop "monthly" and "meeting".

**Comment by kevkevinpal** [comment]
Concept ACK

I agree with tbd3 and jonatack, drop the "monthly" and "meeting" and even if the frequency changes we won't need to touch this again. Unless the link is dead

**Comment by GabrieleBocchi** [comment]
Thank you for the suggestion! I completely agree. I've updated the PR accordingly.

**Comment by tdb3** [comment]
Let's [squash](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#squashing-commits) the two commits into one. It makes for a cleaner history when this is merged.

**Comment by GabrieleBocchi** [comment]
Thank you @tdb3, I did it. Should I also update the PR description?
This is actually my first contribution to this project, thank you for your guidance and support!

**Review by fanquake — APPROVED** [review]
ACK 637f437a1642ce845d7f750b45b71320a82d83b5

> Should I also update the PR description?

Yes. I've done it now in any case.

**Pull request merged**
