### PR TITLE
ci: tsan on clang-9

### PR DESCRIPTION
**Pull request by maflcko**
Bump the compiler runtime library that includes the sanitizers from clang-8 to clang-9 to get a more recent version. Also, bump the system packages from xenial to bionic to test packages closer to what is commonly used in production.

The second commit is needed to install the `tzdata` package, which is missing on some operating systems. See https://travis-ci.org/github/MarcoFalke/bitcoin-core/jobs/688455828#L1727

### CODE REVIEW

**Comment by practicalswift** [comment]
Concept ACK

**Comment by hebasto** [comment]
Concept ACK.

**Comment by MarcoFalke** [comment]
Shifted goalpost for now

**Comment by practicalswift** [comment]
ACK faf552117efdd456fb17b1d9490896de3b7d67a4 -- patch looks correct and Travis is happy

Thanks for doing this!

**Review by hebasto — APPROVED** [review]
ACK faf552117efdd456fb17b1d9490896de3b7d67a4

Maybe it is time to put `bionic` here:
https://github.com/bitcoin/bitcoin/blob/fa006caa136f05a18428c792802523637d2234ca/.travis.yml#L30
?

**Pull request merged**
