### PR TITLE
Better support for mainframes and EBCDIC users in general

### PR DESCRIPTION
**Pull request by scravy**
As can be seen in the photograph of a typical mainframe keyboard:

keyboard-029

These users do not have access to curly braces. To welcome contributors also from the realm of mainframe super computing, bitcoin should use some of the lesser known features of C++: Digraphs.

This pull request replaces non-comment and non-string curly braces with their [equivalent digraph representations](https://en.cppreference.com/w/cpp/language/operator_alternative) `<%` and `%>`. I had to adjust the `check-rpc-mappings.py` linter a bit as it was not robust enough to deal with the full spectrum of expressivity that C++ offers.

This change should help users using [EBCDIC](https://en.wikipedia.org/wiki/EBCDIC) or rather esoteric codepages like [DIN_66003](https://de.wikipedia.org/wiki/DIN_66003).

Unfortunately [Trigraphs were removed from C++17](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4210.pdf), which is why I restrained from replacing symbols in string literals and comments.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Concept ACK. Though reviewing a +31933-31933 diff is a bit daunting, so I'd prefer a scripted-diff.

**Comment by scravy** [comment]
Aww shoot, one of the travis build spuriously errored out: https://travis-ci.org/bitcoin/bitcoin/builds/514144261

I guess the validity if the change can be checked by building without this patch and with, the binary should not change a bit.

**Comment by laanwj** [comment]
:joy:

**Comment by scravy** [comment]
Happy April Fool's Day!

**Pull request closed without merging**
