### PR TITLE
ci: Run tests on arm

### LINKED ISSUE #16576: [help needed] Add notes on how to run unit and functional tests in QEMU
QEMU allows to emulate a processor (even of different architecture). We cross-compile to aarch64 and arm64, among others. Even though developers run tests on those architectures sporadically, it would be nice if there was documentation or a script in our repo on how to do that in QEMU.

### PR DESCRIPTION
**Pull request by maflcko**
Closes #16576

### CODE REVIEW

**Comment by practicalswift** [comment]
Concept ACK

Thanks for working on this -- diversity in testing is good!

**Comment by MarcoFalke** [comment]
Idk, giving up here. I can't make any sense of why travis fails here.

**Comment by MarcoFalke** [comment]
Squashed. Travis should pass now :pray:

**Comment by laanwj** [comment]
ACK fa852be6f5763ccb7c6f36ef7be61d0ac7ad5454

**Comment by laanwj** [comment]
But please change the name of the travis run, that unit tests are run now:
```yaml
    - stage: test
      name: 'ARM  [GOAL: install]  [no unit or functional tests]'
      env: >-
        FILE_ENV="./ci/test/00_setup_env_arm.sh"
```

**Comment by Empact** [comment]
ACK https://github.com/bitcoin/bitcoin/commit/fa852be6f5763ccb7c6f36ef7be61d0ac7ad5454 modulo https://github.com/bitcoin/bitcoin/pull/17041#issuecomment-539934566

**Comment by MarcoFalke** [comment]
> But please change the name of the travis run, that unit tests are run now:

Good catch. Fixed the travis.yml build names.

**Review by fanquake — APPROVED** [review]
ACK fa79dff624110992ca85c4abf6950e3ac0df72ef - assuming Travis is green again.

**Review by KaycoinsInc — APPROVED** [review]

**Review by KaycoinsInc — APPROVED** [review]

**Review by KaycoinsInc — APPROVED** [review]

**Review by KaycoinsInc — APPROVED** [review]

**Comment by sipa** [comment]
@KaycoinsInc Please stop spamming this repository.

**Review by KaycoinsInc — APPROVED** [review]

**Pull request merged**
