### PR TITLE
CalculateNextWorkRequired Cleanup

### PR DESCRIPTION
**Pull request by ghost**
Deprecating the remaining LogPrintf dependencies that were made obsolete in PR #7459 .

### CODE REVIEW

**Comment by paveljanik** [comment]
Travis failure unrelated (wallet.py -salvagewallet failure which I'm not able to reproduce locally anymore :-(().

ACK https://github.com/bitcoin/bitcoin/pull/7962/commits/c7aac2d557fe3d3aa5bcdd3301a9b87eb110d8ed

**Comment by jonasschnelli** [comment]
utACK c7aac2d557fe3d3aa5bcdd3301a9b87eb110d8ed
kicked travis.

**Comment by mruddy** [comment]
utACK c7aac2d

**Comment by btcdrak** [comment]
utACK c7aac2d

**Pull request merged**
