### PR TITLE
Remove redundant variables, statements and forward declarations

### PR DESCRIPTION
**Pull request by practicalswift**
Remove redundant …
* ~access modifiers,~
* forward declarations,
* unused variables,
* statements, and
* ~return types from lambdas.~

### CODE REVIEW

**Comment by Empact** [comment]
I'm unsure on 1d45dcd and dc0996f because they serve to help document the code.

**Comment by MarcoFalke** [comment]
Agree with @Empact

**Comment by practicalswift** [comment]
@Empact Thanks for the quick review!

I've now excluded dc0996f15ab99c8307bf63efd339cad20ddcb562 from this PR – I see your point.

Regarding 1d45dcd67dbb7319e9acd6dd36ce7106727cb18a, what does that add from a documentation viewpoint? `struct` has public access to its base classes by default.

**Comment by Empact** [comment]
@practicalswift the value is modest, but the declaration makes the default explicit, removing an otherwise-required unit of knowledge for the reader. Avoids the risk of an inappropriate expectation or assumption, particularly relevant since `struct` and `class` differ in their defaults.

**Comment by practicalswift** [comment]
@Empact I see your point. I've now excluded that commit.

@Empact @MarcoFalke Please re-review :-)

**Comment by promag** [comment]
utACK 3dee4cc.

**Comment by greenaddress** [comment]
utACK 3dee4cc5098c6e9bcc13df9d6277478c8273a6cd

**Comment by MarcoFalke** [comment]
utACK 3dee4cc

**Pull request merged**
