### PR TITLE
doc: macos replaces osx

### PR DESCRIPTION
**Pull request by suprraz**
Doc updates:

- rename `build-osx.md` to `build-macos.md`
- rename `README_osx.md` to `README_macos.md`
- update all file references in the project
- compatibility now includes `macOS 10.14 Mojave`

### CODE REVIEW

**Comment by suprraz** [comment]
2 commits squashed.

**Comment by Empact** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/14991/commits/850da37b197bb047ea9af8aee397154cda3c9826

**Comment by promag** [comment]
I agree with not rename files.

**Comment by suprraz** [comment]
Closed based to avoid breaking external links to the files.

**Pull request closed without merging**
