### PR TITLE
depends: Fetch miniupnpc sources from an alternative website

### PR DESCRIPTION
**Pull request by hebasto**
The https://miniupnp.tuxfamily.org website is unavailable now.

### CODE REVIEW

**Comment by fanquake** [comment]
> website is unavailable now.

Forever? Temporarily? Why not use the other official site?

Also no mention that this is now downloading a bunch of other stuff that we don't use?

**Comment by hebasto** [comment]
> > website is unavailable now.
> 
> Forever?

I don't know.

> Temporarily?

I don't know.

> Why not use the other official site?

Which one? http://miniupnp.free.fr without HTTPS?

> Also no mention that this is now downloading a bunch of other stuff that we don't use?

Mentioned in the PR description.

**Comment by laanwj** [comment]
> Which one? http://miniupnp.free.fr/ without HTTPS?

If that does keep the sha256 hash the same then maybe. Mind that github-generated tar.gzs aren't guaranteed to have a stable hash.

**Comment by hebasto** [comment]
> > Which one? http://miniupnp.free.fr/ without HTTPS?
> 
> If that does keep the sha256 hash the same then maybe.

It does. Switched to that website.

**Comment by laanwj** [comment]
> It does. Switched to that website.

Thanks. Agree it's really suboptimal to use http because of protocol-level mischief, though. i hope tuxfamily will be back.

**Comment by achow101** [comment]
ACK 21b8a14d37c19ce292d5529597e0d52338db48a9

The main page of tuxfamily.org has 2 posts stating that they've had weeks of downtime in the past 6 months, so I think it makes sense to switch to a different mirror as they seem to be having issues. It's unfortunate that miniupnp.free.fr is http only, but we check the hash so I think it's fine.

**Review by theuni — APPROVED** [review]
Agree with @laanwj and @achow101.

This is unfortunate, but seems like the best solution for now. The checksum should point out any hijinks. 

utACK 21b8a14d37c19ce292d5529597e0d52338db48a9

**Comment by edilmedeiros** [comment]
> > > Which one? http://miniupnp.free.fr/ without HTTPS?
> > 
> > 
> > If that does keep the sha256 hash the same then maybe.
> 
> It does. Switched to that website.

This is the same URL I used to update the MacOS package in the macports project a couple of months ago, so there will be more people watching it.

**Comment by fanquake** [comment]
Backported to 27.x in #30092.

**Comment by hebasto** [comment]
That's unfortunate.

As for today, https://miniupnp.free.fr/ is unavailable for me (

**Comment by edilmedeiros** [comment]
Isn't possible/desirable to try to get it from the Github repo instead?

https://github.com/miniupnp/miniupnp

**Comment by hebasto** [comment]
> Isn't possible/desirable to try to get it from the Github repo instead?

See https://github.com/bitcoin/bitcoin/pull/30151#issuecomment-2124512367:
> If that does keep the sha256 hash the same then maybe. Mind that github-generated tar.gzs aren't guaranteed to have a stable hash.

**Pull request merged**
