### PR TITLE
test: wallet_listtransactions improvements (speedup, cleanup, logging)

### PR DESCRIPTION
**Pull request by theStack**
This PR improves the test `wallet_listtransactions.py` in three ways:
* speeds up runtime by a factor of 2-3x by using the good ol' immediate tx relay trick (`-whitelist=noban@127.0.0.1`)
* removes unneeded/redundant code
* adds log messages, mostly by turning comments into `self.log.info(...)` calls

### CODE REVIEW

**Review by jonatack — COMMENTED** [review]
ACK c0abfa2d11a3ef847c68ef1a88bb3aa63d6fb7b2 modulo updating the positions of `wallet_listtransactions.py --legacy-wallet` and `wallet_listtransactions.py --descriptors` in the test runner from 2m to under 30s (per my testing, the run time drops from ~1m to ~10-15s).

<details><summary>Some quick suggestions for your consideration in the last commit</summary><p>

```diff
--- a/test/functional/wallet_listtransactions.py
+++ b/test/functional/wallet_listtransactions.py
@@ -105,19 +105,20 @@ class ListTransactionsTest(BitcoinTestFramework):
 
         self.run_rbf_opt_in_test()
 
-    # Check that the opt-in-rbf flag works properly, for sent and received
-    # transactions.
+
     def run_rbf_opt_in_test(self):
-        # Check whether a transaction signals opt-in RBF itself
+        """Test the opt-in-rbf flag for sent and received transactions."""
+
         def is_opt_in(node, txid):
+            """Check whether a transaction signals opt-in RBF itself."""
             rawtx = node.getrawtransaction(txid, 1)
             for x in rawtx["vin"]:
                 if x["sequence"] < 0xfffffffe:
                     return True
             return False
 
-        # Find an unconfirmed output matching a certain txid
         def get_unconfirmed_utxo_entry(node, txid_to_match):
+            """Find an unconfirmed output matching a certain txid."""
             utxo = node.listunspent(0, 0)
             for i in utxo:
                 if i["txid"] == txid_to_match:
@@ -125,7 +126,7 @@ class ListTransactionsTest(BitcoinTestFramework):
             return None
 
         self.log.info("Test txs w/o opt-in RBF (bip125-replaceable=no)")
-        # Chain a few transactions that don't opt-in.
+        # Chain a few transactions that don't opt in.
         txid_1 = self.nodes[0].sendtoaddress(self.nodes[1].getnewaddress(), 1)
         assert not is_opt_in(self.nodes[0], txid_1)

@@ -205,5 +205,6 @@ class ListTransactionsTest(BitcoinTestFramework):
         assert_equal(self.nodes[0].gettransaction(txid_3b)["bip125-replaceable"], "no")
         assert_equal(self.nodes[0].gettransaction(txid_4)["bip125-replaceable"], "unknown")
 
+
 if __name__ == '__main__':
     ListTransactionsTest().main()
```
</p></details>

**Comment by theStack** [comment]
@jonatack: Thanks for your review!

> [...] modulo updating the positions of `wallet_listtransactions.py --legacy-wallet` and `wallet_listtransactions.py --descriptors` in the test runner from 2m to under 30s (per my testing, the run time drops from ~1m to ~10-15s).

Good idea, done. Put that into the first commit, due to a conflict in test_runner.py I also had to rebase the PR branch.
> 
> Some quick suggestions for your consideration in the last commit

Nice, agree that this PR is also a good oportunity to change to docstrings. Took your suggestions and added you as co-author in the last commit.

**Comment by jonatack** [comment]
Thanks for updating!

ACK a006d7d73019b8cf4d68626c019c3d69729dda69

**Review by kristapsk — APPROVED** [review]
ACK a006d7d73019b8cf4d68626c019c3d69729dda69

**Comment by practicalswift** [comment]
Concept ACK

**Pull request merged**
