### PR TITLE
Push down RPC locks

### PR DESCRIPTION
**Pull request by laanwj**
Rebased version of #5107.
- update for RPC methods added since 84d13ee: setmocktime, invalidateblock, reconsiderblock. Only the first, setmocktime, required a change,      the other two are thread safe.
- remove no-longer-used threadSafe column from RPC table
- remove duplicate invalidateblock and reconsiderblock from RPC table

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Tested ACK.

**Comment by jonasschnelli** [comment]
I assume there is a minimal post PR overhaul of https://github.com/bitcoin/bitcoin/blob/master/src/rpcmining.cpp#L444 required. IMO not urgent.

**Comment by sdaftuar** [comment]
This commit appears to have broken the rpc-test getblocktemplate_longpoll.py.  Relevant failure:

```
  File "./getblocktemplate_longpoll.py", line 66, in run_test
    assert(thr.is_alive())
```

I'm not familiar enough with the test yet to understand what is going on, but I verified the test broke at this commit and succeeds in the previous one.

**Comment by jonasschnelli** [comment]
I can confirm that the test is broken.
`Assertion failed: (!pthread_mutex_unlock(&m)), function unlock...`

I think it has to do with the `LEAVE_CRITICAL_SECTION`.

**Comment by jonasschnelli** [comment]
I don't see a need for https://github.com/bitcoin/bitcoin/blob/master/src/rpcmining.cpp#L451 LEAVE and ENTER crictial section.
But maybe i'm wrong.

**Pull request merged**
