### PR TITLE
[22.x] guix: ignore additional failing certvalidator test

### LINKED ISSUE #24110: 22.x: darwin guix build currently failing
Guix building for Darwin, using the `22.x` branch currently fails due to a failing test in the python-certvalidator package. The test relies on a certificate, that expired 6 days ago..:
```bash
building /gnu/store/w8i5a3yfmayxhyjyr5ccnrh5pbx96pmq-python-oscryptotests-1.2.1.drv...
building /gnu/store/zpmm8r9i2sx75f9ix9xs962qc5a7s3i7-python-certvalidator-0.1-1.e5bdb4b.drv...
\ 'check' phasenote: keeping build directory `/tmp/guix-build-python-certvalidator-0.1-1.e5bdb4b.drv-1'
builder for `/gnu/store/zpmm8r9i2sx75f9ix9xs962qc5a7s3i7-python-certvalidator-0.1-1.e5bdb4b.drv' failed with exit code 1
build of /gnu/store/zpmm8r9i2sx75f9ix9xs962qc5a7s3i7-python-certvalidator-0.1-1.e5bdb4b.drv failed
View build log at '/var/log/guix/drvs/zp/mm8r9i2sx75f9ix9xs962qc5a7s3i7-python-certvalidator-0.1-1.e5bdb4b.drv.bz2'.
guix environment: error: build of `/gnu/store/zpmm8r9i2sx75f9ix9xs962qc5a7s3i7-python-certvalidator-0.1-1.e5bdb4b.drv' failed
....
======================================================================
ERROR: test_revocation_mode_soft (tests.test_validate.ValidateTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/guix-build-python-certvalidator-0.1-1.e5bdb4b.drv-0/source/tests/test_validate.py", line 85, in test_revocation_mode_soft
    validate_path(context, path)
  File "/tmp/guix-build-python-certvalidator-0.1-1.e5bdb4b.drv-0/source/tests/../certvalidator/validate.py", line 50, in validate_path
    return _validate_path(validation_context, path)
  File "/tmp/guix-build-python-certvalidator-0.1-1.e5bdb4b.drv-0/source/tests/../certvalidator/validate.py", line 358, in _validate_path
    raise PathValidationError(pretty_message(
certvalidator.errors.PathValidationError: The path could not be validated because the end-entity certificate expired 2022-01-14 12:00:00Z

----------------------------------------------------------------------
Ran 213 tests in 1.609s

FAILED (errors=1, skipped=10)
```

I have a fix for this in #24057, https://github.com/bitcoin/bitcoin/pull/24057/commits/85885919656a3f606f3d7f208378aabe95f3f62d, which can be backported to the 22.x branch.

### PR DESCRIPTION
**Pull request by fanquake**
Backports https://github.com/bitcoin/bitcoin/commit/85885919656a3f606f3d7f208378aabe95f3f62d from #24057 so that from-scratch Guix builds for the Darwin host aren't broken due to a (very recently) expired certificate causing one of the python-certvalidator tests to fail. Kept separate from #23276 because that hasn't gotten review attention, and I don't think we should leave `22.x` Darwin Guix builds broken for any longer than we have to.

Fixes #24110.

```bash
======================================================================
ERROR: test_revocation_mode_soft (tests.test_validate.ValidateTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/guix-build-python-certvalidator-0.1-1.e5bdb4b.drv-0/source/tests/test_validate.py", line 85, in test_revocation_mode_soft
    validate_path(context, path)
  File "/tmp/guix-build-python-certvalidator-0.1-1.e5bdb4b.drv-0/source/tests/../certvalidator/validate.py", line 50, in validate_path
    return _validate_path(validation_context, path)
  File "/tmp/guix-build-python-certvalidator-0.1-1.e5bdb4b.drv-0/source/tests/../certvalidator/validate.py", line 358, in _validate_path
    raise PathValidationError(pretty_message(
certvalidator.errors.PathValidationError: The path could not be validated because the end-entity certificate expired 2022-01-14 12:00:00Z
```

Guix Build:
```bash
bash-5.1# find guix-build-$(git rev-parse --short=12 HEAD)/output/ -type f -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum
359755bffecc64b4c005c5cdee3824190f6b1759dbc6c20034476dcc06413959  guix-build-b7ecef1ddf0c/output/dist-archive/bitcoin-b7ecef1ddf0c.tar.gz
0c6700270ec75991d70a97cad77e22cc00553f812edb56c1bac5ef6421f963e1  guix-build-b7ecef1ddf0c/output/x86_64-apple-darwin/SHA256SUMS.part
87d4637a87959a304422550edf87feda3953d7305894154a6a2d413cc0dd2034  guix-build-b7ecef1ddf0c/output/x86_64-apple-darwin/bitcoin-b7ecef1ddf0c-osx-unsigned.dmg
9cabae32689bd5f93e7faaaf341827f1c4069a63ab6f74276564e47819343b6c  guix-build-b7ecef1ddf0c/output/x86_64-apple-darwin/bitcoin-b7ecef1ddf0c-osx-unsigned.tar.gz
bb5fb113bc022a305e49783d0ba48be90aca61e4a942beeb45206dbc5b91ca6e  guix-build-b7ecef1ddf0c/output/x86_64-apple-darwin/bitcoin-b7ecef1ddf0c-x86_64-apple-darwin.tar.gz
```

### CODE REVIEW

**Comment by Sjors** [comment]
I did a a Guix clean followed by:

```sh
env HOSTS='x86_64-apple-darwin' ./contrib/guix/guix-build
```

This succeeds, but code-sign doesn't:

```sh
env HOSTS='x86_64-apple-darwin' ./contrib/guix/guix-codesign 
Checking that we can connect to the guix-daemon...

Hint: If this hangs, you may want to try turning your guix-daemon off and on
      again.

INFO: Codesigning b7ecef1ddf0c for platform triple x86_64-apple-darwin:
      ...using reference timestamp: 1642652187
      ...from worktree directory: '/home/guix/bitcoin'
          ...bind-mounted in container to: '/bitcoin'
      ...in build directory: '/home/guix/bitcoin/guix-build-b7ecef1ddf0c/distsrc-b7ecef1ddf0c-x86_64-apple-darwin-codesigned'
          ...bind-mounted in container to: '/distsrc-base/distsrc-b7ecef1ddf0c-x86_64-apple-darwin-codesigned'
      ...outputting in: '/home/guix/bitcoin/guix-build-b7ecef1ddf0c/output/x86_64-apple-darwin-codesigned'
          ...bind-mounted in container to: '/outdir-base/x86_64-apple-darwin-codesigned'
      ...using detached signatures in: '/home/guix/bitcoin-detached-sigs'
          ...bind-mounted in container to: '/detached-sigs'
Required environment variables as seen inside the container:
    UNSIGNED_TARBALL: /outdir-base/x86_64-apple-darwin/bitcoin-b7ecef1ddf0c-osx-unsigned.tar.gz
    DETACHED_SIGS_REPO: /detached-sigs
    DIST_ARCHIVE_BASE: /outdir-base/dist-archive
    DISTNAME: bitcoin-b7ecef1ddf0c
    HOST: x86_64-apple-darwin
    SOURCE_DATE_EPOCH: 1642652187
    DISTSRC: /distsrc-base/distsrc-b7ecef1ddf0c-x86_64-apple-darwin-codesigned
    OUTDIR: /outdir-base/x86_64-apple-darwin-codesigned
/gnu/store/q3y2bpd61bvb7d0g9ils1zi6pax5yvb1-python-elfesteem-0.1-1.87bbd79/lib/python3.8/site-packages/elfesteem/cstruct.py:412: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if name is not '' and not name in table: table[name] = {}
/gnu/store/q3y2bpd61bvb7d0g9ils1zi6pax5yvb1-python-elfesteem-0.1-1.87bbd79/lib/python3.8/site-packages/elfesteem/cstruct.py:415: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if name is not '':
Code signature applied
Traceback (most recent call last):
  File "/gnu/store/vsi3743mm41cfdv0zmap6p2qfsqylcmx-python-signapple-0.1-1.b084cbb/bin/.signapple-real", line 11, in <module>
    load_entry_point('signapple==0.1.0', 'console_scripts', 'signapple')()
  File "/gnu/store/vsi3743mm41cfdv0zmap6p2qfsqylcmx-python-signapple-0.1-1.b084cbb/lib/python3.8/site-packages/signapple/__init__.py", line 112, in main
    args.func(args)
  File "/gnu/store/vsi3743mm41cfdv0zmap6p2qfsqylcmx-python-signapple-0.1-1.b084cbb/lib/python3.8/site-packages/signapple/__init__.py", line 36, in apply
    verify(args)
  File "/gnu/store/vsi3743mm41cfdv0zmap6p2qfsqylcmx-python-signapple-0.1-1.b084cbb/lib/python3.8/site-packages/signapple/__init__.py", line 10, in verify
    verify_mach_o_signature(args.filename)
  File "/gnu/store/vsi3743mm41cfdv0zmap6p2qfsqylcmx-python-signapple-0.1-1.b084cbb/lib/python3.8/site-packages/signapple/verify.py", line 227, in verify_mach_o_signature
    _verify_single(filepath, header)
  File "/gnu/store/vsi3743mm41cfdv0zmap6p2qfsqylcmx-python-signapple-0.1-1.b084cbb/lib/python3.8/site-packages/signapple/verify.py", line 161, in _verify_single
    _validate_code_hashes(f, sig_superblob.code_dir_blob)
  File "/gnu/store/vsi3743mm41cfdv0zmap6p2qfsqylcmx-python-signapple-0.1-1.b084cbb/lib/python3.8/site-packages/signapple/verify.py", line 54, in _validate_code_hashes
    raise Exception(
Exception: Code slot hash mismatch. Expected 8cdb98ee7dbd9c1a5b021603c4b0ef933a31717f57884bc3a72536257e4d53dd, Calculated 95bcde7c12f864fcf3de59c87142b9fde1b728328a48cd923023381b730b4eab
```

Some hashes:
```
8f70852feb39078e02182563517d17bdfc4a12904cf1bdabbae95594d9a1e473  guix-build-b7ecef1ddf0c/output/dist-archive/bitcoin-b7ecef1ddf0c-codesignatures-22.0.tar.gz
359755bffecc64b4c005c5cdee3824190f6b1759dbc6c20034476dcc06413959  guix-build-b7ecef1ddf0c/output/dist-archive/bitcoin-b7ecef1ddf0c.tar.gz
0c6700270ec75991d70a97cad77e22cc00553f812edb56c1bac5ef6421f963e1  guix-build-b7ecef1ddf0c/output/x86_64-apple-darwin/SHA256SUMS.part
87d4637a87959a304422550edf87feda3953d7305894154a6a2d413cc0dd2034  guix-build-b7ecef1ddf0c/output/x86_64-apple-darwin/bitcoin-b7ecef1ddf0c-osx-unsigned.dmg
9cabae32689bd5f93e7faaaf341827f1c4069a63ab6f74276564e47819343b6c  guix-build-b7ecef1ddf0c/output/x86_64-apple-darwin/bitcoin-b7ecef1ddf0c-osx-unsigned.tar.gz
bb5fb113bc022a305e49783d0ba48be90aca61e4a942beeb45206dbc5b91ca6e  guix-build-b7ecef1ddf0c/output/x86_64-apple-darwin/bitcoin-b7ecef1ddf0c-x86_64-apple-darwin.tar.gz
```

**Comment by Sjors** [comment]
cc @dongcarl

**Comment by achow101** [comment]
I've also updated certvalidator to have passing tests.

**Comment by hebasto** [comment]
@Sjors 
> This succeeds, but code-sign doesn't:

Maybe https://github.com/bitcoin/bitcoin/pull/21851#issuecomment-1022115041 and #22546 ?

**Comment by Sjors** [comment]
@hebasto I'm running Guix on an Ubuntu machine. Are up saying I should copy it over to my Mac and code-sign it? That seems odd.

@achow101 certvalidator?

**Comment by dongcarl** [comment]
Wondering if we should just switch to achow's https://github.com/achow101/certvalidator/commit/e5bdb4bfcaa09fa0af355eb8867d00dfeecba08c instead?

**Comment by fanquake** [comment]
> Wondering if we should just switch to achow's achow101/certvalidator@e5bdb4b instead?

Isn't that the version we are already using?

**Comment by achow101** [comment]
> Wondering if we should just switch to achow's [achow101/certvalidator@e5bdb4b](https://github.com/achow101/certvalidator/commit/e5bdb4bfcaa09fa0af355eb8867d00dfeecba08c) instead?

I think you mean https://github.com/achow101/certvalidator/commit/a145bf25eb75a9f014b3e7678826132efbba6213

> @hebasto I'm running Guix on an Ubuntu machine. Are you saying I should copy it over to my Mac and code-sign it? That seems odd. Or is that a workaround because we don't have detached signatures for this commit?

The error you get there is because the detached sig it is using is for a different release. signapple does not know that the detached sig is not for the binary you have built.

> @achow101 certvalidator?

The tool that this patch is fixing.

**Comment by fanquake** [comment]
I think we could switch to the newer certvalidator branch in master, and then re-enable tests. However for `22.x` I'd rather fix the build by backporting this change. I'll add some Guix hashes to the PR description shortly.

**Comment by Sjors** [comment]
My hashes match those in the PR description, but those don't include the signed DMG. I guess I'm confused about what certificate related problem this PR is solving.

**Comment by fanquake** [comment]
> I guess I'm confused about what certificate related problem this PR is solving.

If you Guix build the current 22.x branch, from scratch (so that `python-certvalidator` is built instead of a cached version being used), it will fail. This PR is making it not fail. The python-certvalidator package has a test that has recently started failing, due to a certificate used in it's test suite expiring. All this change does is ignore the failing test, similar to how we already ignore some of its tests, so that the Guix build will work.

> but those don't include the signed DMG.

They don't need to. You don't need to run the code-sign step at all to verify this fixing what it's supposed to be fixing.

**Comment by Sjors** [comment]
What is `python-certvalidator` used for roughly?

**Comment by fanquake** [comment]
> What is python-certvalidator used for roughly?

https://github.com/wbond/certvalidator: "A Python library for validating X.509 certificates or paths. ". We use a fork maintained by achow. It's a dependency of sign-apple.

**Comment by Sjors** [comment]
> from scratch

I did a `guix clean` and then built the commit before PR. Which works fine. I'll try a more thorough nuke of Guix files...

**Comment by MarcoFalke** [comment]
Concept ACK b7ecef1ddf0c9f1f53ab220bee2e19a6b8978e34

Seems good to make it possible to compile the branch again

**Comment by fanquake** [comment]
> I did a guix clean and then built the commit before PR. Which works fine. 

You need to Guix build such that the python-certvalidator package is actually built, and the tests run.

I am going to merge this now to un-break from-scratch builds.

**Pull request merged**
