### PR TITLE
[UI Styling] Left-Align Tab Bar - debugwindow.ui

### PR DESCRIPTION
**Pull request by SCDeveloper**
Aesthetics.

### CODE REVIEW

**Comment by SCDeveloper** [comment]
screen shot 2017-03-05 at 20 40 25

**Comment by SCDeveloper** [comment]
Merge alongside https://github.com/bitcoin/bitcoin/pull/9924

**Comment by SCDeveloper** [comment]
Merge alongside https://github.com/bitcoin/bitcoin/pull/9925

**Comment by SCDeveloper** [comment]
This is a bug on OSX and this is the cure.

**Comment by laanwj** [comment]
Closing these, we disagree on the direction the GUI should take so it's not going to go anywhere.

**Pull request closed without merging**
