### PR TITLE
Update src/secp256k1 subtree to upstream release v0.3.0

### PR DESCRIPTION
**Pull request by sipa**
This updates the libsecp256k1 subtree to [v0.3.0](https://github.com/bitcoin-core/secp256k1/releases/tag/v0.3.0). I don't believe there are code changes that are particularly important to Bitcoin Core, apart from the added CMake build system support.

### CODE REVIEW

**Review by real-or-random — COMMENTED** [review]
Concept ACK

**Comment by fanquake** [comment]
Concept ACK

cc @jonasnick too

**Review by jonasnick — COMMENTED** [review]
ACK e5c7fcb361d3379c254a52104b4ba25907cd07bb

**Review by fanquake — APPROVED** [review]
ACK e5c7fcb361d3379c254a52104b4ba25907cd07bb

**Pull request merged**
