### PR TITLE
Avoid VLA in hash.h

### PR DESCRIPTION
**Pull request by sipa**

### CODE REVIEW

**Review by gmaxwell — APPROVED** [review]
utACK.

**Comment by paveljanik** [comment]
Compiles and works together with #9789.

ACK https://github.com/bitcoin/bitcoin/pull/9791/commits/5c8fd508112016c3821b71112270afe83e6949ac

**Comment by laanwj** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/9791/commits/5c8fd508112016c3821b71112270afe83e6949ac

**Comment by sipa** [comment]
To clarify: my GCC does not consider this to be a VLA, but at least some Clang versions do.

**Comment by laanwj** [comment]
Well I think this makes the code clearer too, so it's a win in any case.

**Comment by MarcoFalke** [comment]
5c8fd508112016c3821b71112270afe83e6949ac gives same binaries with recent gcc on my arch.

utACK 5c8fd508112016c3821b71112270afe83e6949ac

**Pull request merged**
