### PR TITLE
contrib: Move optimize-pngs.py script to the maintainer repo

### PR DESCRIPTION
**Pull request by maflcko**
Moved to https://github.com/bitcoin-core/bitcoin-maintainer-tools/blob/master/optimize-pngs.py

Bitcoin Core should focus on the full node implementation, not on scripts to compress png images. 

This script is only used when new PNG files are added to the repo. This happens about once every two years. So fetching the script from the other repo should not be a burden, but removing it from this repo is going to cut down on the meta files we need to maintain in the main repo.

### CODE REVIEW

**Comment by practicalswift** [comment]
Concept ACK

**Comment by kristapsk** [comment]
Concept ACK

I see the script differs little bit, that's some changes added on top?

Btw, [here's script](https://github.com/kristapsk/random-stuff/blob/master/git-copy.sh) that copies file between two git repos preserving history. Doesn't work every time, but mostly do.

**Review by hebasto — APPROVED** [review]
ACK fa13090d2048c9a1e475eb25de756763f8adddb8, verified that script is already [moved](https://github.com/bitcoin-core/bitcoin-maintainer-tools/pull/56).

**Comment by practicalswift** [comment]
ACK fa13090d2048c9a1e475eb25de756763f8adddb8 -- `+0 lines, -82 lines` :)

**Comment by promag** [comment]
ACK fa13090d2048c9a1e475eb25de756763f8adddb8.

**Pull request merged**
