### PR TITLE
Remove unnecessary G_TRANSLATION_FUN nullptr assignment

### PR DESCRIPTION
**Pull request by promag**
Cleans https://github.com/bitcoin/bitcoin/pull/13961/files#r213135952.

### CODE REVIEW

**Comment by practicalswift** [comment]
utACK 508b65c74b9515a62e8ee55bc4c28cb3684b0263

**Comment by ken2812221** [comment]
Does this improve something?

**Comment by promag** [comment]
No.

**Comment by Empact** [comment]
utACK 508b65c less code is bettter code

**Comment by laanwj** [comment]
TBH I like the explicit construction more, this change seems completely unnecessary

**Comment by promag** [comment]
@laanwj this was initially a pointer.

**Comment by laanwj** [comment]
oh I see, it's not a pointer, ok fine, yes then it's not sensible to assign nullptr

was just getting a bit annoyed with getting a "clean up" PR after every PR, sorry

**Comment by MarcoFalke** [comment]
Tend to agree with @laanwj. According to https://en.cppreference.com/w/cpp/utility/functional/function/function both variations "1-2) Creates an empty function."
If one variant is preferable, it should be mentioned in the developer notes.

**Comment by promag** [comment]
I prefer 1) but I don't care that much.

**Pull request closed without merging**
