### PR TITLE
test: Move linters to test/lint, add readme

### PR DESCRIPTION
**Pull request by maflcko**
This moves the checks and linters from `devtools` to a subfolder in `test`. (Motivated by my opinion that the dev tools are mostly for generating code and updating the repo whereas the linters are read-only checks.)

Also, adds a readme to clarify that checks and linters are only meant to prevent bugs and user facing issues, not merely stylistic preference or inconsistencies. (This is motivated by the diversity in developers and work flows as well as existing code styles. It would be too disruptive to change all existing code to a single style or too burdensome to force all developers to adhere to a single style. Also note that our style guide is changing, so locking in at the wrong style "too early" would only waste resources.)

### CODE REVIEW

**Comment by practicalswift** [comment]
The `test/lint/` move is an obvious utACK, but the "add readme" part is troublesome:

The following addition … 

```
This folder contains lint scripts that aim to prevent direct or indirect user facing bugs.
Patches that do not pass the linter checks are usually not accepted.

Note that the [recommended style](/doc/developer-notes.md) and other stylistic
inconsistencies should not be enforced unless they could result in user facing bugs.
```

… formalizes a new "automation skeptical" (for lack of a better word!) policy which in the light of recent discussions on linting (see for example #12879) does not seem to be backed by consensus.

Personally I subscribe to the linting philosophy outlined by @sipa in #12879: 

> If there is a widespread opinion among contributors and maintainers that a particul guideline is worth the burden, then I think it should be put in the style guide - and if it is, it sounds great to enforce it.

I suggest the following text instead:

```
This folder contains lint scripts that automate the review process in some form.

If there is a widespread opinion among contributors and maintainers that a particular
guideline is worth the burden, then it should be put in the style guide - and if it is, it
is probably a good candidate for linting. However, the enforcement should be limited
to issues that can reliably identified without false positives or false negatives.

Patches that do not pass the linter checks are usually not accepted.
```

**Comment by MarcoFalke** [comment]
@practicalswift That was my first draft, but I realized that the style guide includes not only enforceable guidelines, but also a bunch of recommendations, that are fine to violate. For example the "Miscellaneous" [coding style](https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md#coding-style) or the reference to the clang-format rules. While most of them can be reliably identified without false positives or false negatives, I think we should avoid enforcing them.

**Comment by MarcoFalke** [comment]
Also note that the wording is not strict "[...] other stylistic inconsistencies *should* not be enforced [...]"

We can always add a linter for stuff that is uncontroversial but not preventing any user facing bugs. See for example the linter that checks for trailing white space.

**Comment by promag** [comment]
`test/liny/lint-python.sh` also catches python scripts in contrib/ and share/ - fine I guess?

**Comment by MarcoFalke** [comment]
@promag I guess that is fine or maybe even desired.

**Comment by sipa** [comment]
utACK fa3c910bfeab00703c947c5200a64c21225b50ef

**Comment by kallewoof** [comment]
utACK fa3c910

**Comment by Empact** [comment]
`contrib/devtools/README.md` still documents `check-doc`, which has moved.

**Comment by jnewbery** [comment]
utACK https://github.com/bitcoin/bitcoin/commit/fa3c910bfeab00703c947c5200a64c21225b50ef

**Comment by ken2812221** [comment]
utACK fa3c910

**Comment by laanwj** [comment]
I'm just going to merge this, so many utACKs for the current state.

**Pull request merged**
