### PR TITLE
[tests] remove redundant univalue_tests.cpp

### PR DESCRIPTION
**Pull request by jnewbery**
univalue unit tests were added in #4730 , and exist at `/src/test/univalue_tests.cpp` (outside the univalue tree). That test was brought into the univalue repository in https://github.com/bitcoin-core/univalue/pull/4 , which was pulled into the github repository in https://github.com/bitcoin/bitcoin/pull/11420.

That means that the univalue test exists in two places:
1. `/src/test/univalue_tests.cpp`
2. `/src/univalue/test/object.cpp`

(2) is a strict superset of (1). It adds some macros to work around boost not being a univalue dependency, and adds a few extra lines of test.

Therefore remove `/src/test/univalue_tests.cpp`

### CODE REVIEW

**Comment by practicalswift** [comment]
Oh, nice catch! -334 lines!

utACK 2862b562cc17f9d4507dab3b9281bf066b093e16

**Comment by MarcoFalke** [comment]
Concept ACK. Going to review after a subtree pull

**Comment by laanwj** [comment]
> **Going to review after a subtree pull**

What needs to be pulled in first?

**Comment by MarcoFalke** [comment]
The tests would break by merging it right now. See https://github.com/bitcoin-core/univalue/pull/9

**Comment by jnewbery** [comment]
> The tests would break...

More accurately, the tests wouldn't be fully testing what we expect them to. They'd continue to pass.

univalue doesn't change frequently, and as long as we don't pull in unrelated changes from univalue without pulling in https://github.com/bitcoin-core/univalue/pull/9, there's no risk or downside to merging this PR.

**Comment by MarcoFalke** [comment]
> no risk or downside to merging this PR

I disagree. There might be no risk, but there is a downside. One tool for testing changes is to break the software (or test) on purpose and see if the test (or software), i.e. the "counterpart", fails. Merging the pull request now would make it infeasible to use this approach for testing on univalue objects.

**Review by ryanofsky — COMMENTED** [review]
utACK 2862b562cc17f9d4507dab3b9281bf066b093e16. Confirmed test/univalue_tests.cpp is a subset of univalue/test/object.cpp, though it seems #11952 should be merged before this PR.

**Comment by MarcoFalke** [comment]
Tested that the tests work on current master, now.

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Tested ACK 2862b562cc17f9d4507dab3b9281bf066b093e16
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJaOthVAAoJENLqSFDnUoslQRwP/0Vx+fszR58LBm5xAeQwITHI
ZSxnSAuO3n069DLSeBKKHxDLwkBLyAtlgbJew5L3pG/XD7bCOWBz46mJmZFIC+yf
g/UswPICh5tU/hl+UBcAQWMtxHWAWOpyl+MRJuNAfi3bWLzzJukT4zgSq39WeGEi
rV23M+zNhTvLAMlkvstQeL18zVetxNgQl+q1WnV5odykIZuXaoeJOppWTu4ev8Os
C+T2xpNFtRazi1Zao5ouR2siqFydCoMUhFJT6A6kM4tPWZg9QdQKzMtC4LDJkVBC
VUZKlSAmaZUGoucHJbFoe+dqRu1Jctc2uBlKwC9VmDWj71JqSu8PoQ0U70Kk81iV
Vu7CgxVBLdErAzSeG+VGBHHF7jiM/yVBIQrkmU5pu0KDOxUi1XQaAu9Qv2852Q81
1Zcyw36RCzfKe6gSvCO3NU2o26PdZCLt/GYDWtx4CO0CoDP4rTEde2PACj9j2LCC
T1OT6jIN72Is+krlY7Y/gPb9neKeLCSnp8NDzfotJGTeC8BRmIejoWXYcxG1OJvR
sAi5JhVOvD2GClVZuAuYiTfY427w5zNnSf6UIVEaJ8saojOslR0uA36NBbiMr4Qk
dFN9e+z3RgrGdIfg4ykPX4qO2/M+xecq5RPcL1tbwqcXiNIWV4I8ydC65PIMlU9u
uBuruRLsWGGpyNZqPKpM
=3ItC
-----END PGP SIGNATURE-----

**Pull request merged**
