### PR TITLE
Remove unreachable or otherwise redundant code

### PR DESCRIPTION
**Pull request by practicalswift**
Remove unreachable or otherwise redundant code.

### CODE REVIEW

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/10536/commits/758bcc466c2ab33648398d53210183587e371b80

**Review by dcousens — APPROVED** [review]

**Comment by jonasschnelli** [comment]
ACK 758bcc466c2ab33648398d53210183587e371b80

**Comment by practicalswift** [comment]
Merge conflicts resolved!

**Comment by sipa** [comment]
utACK 4265bf351a5c7b89ec33deff9f3800f28ff6f3e3

**Comment by MarcoFalke** [comment]
utACK 4265bf351a5c7b89ec33deff9f3800f28ff6f3e3

**Pull request merged**
