### PR TITLE
qa: Revert "Make qt wallet test compatible with qt4"

### PR DESCRIPTION
**Pull request by maflcko**
This removes the file added in #10098

### CODE REVIEW

**Comment by fanquake** [comment]
Concept ACK

Needs to be rebased for #14011.

**Comment by promag** [comment]
utACK fadffae.

**Comment by promag** [comment]
Is Qt 5.4 the minimum supported version?

**Comment by hebasto** [comment]
utACK fadffae

**Comment by MarcoFalke** [comment]
@promag Looks like it right now. See https://github.com/bitcoin/bitcoin/issues/13478#issuecomment-431566265

**Comment by ken2812221** [comment]
utACK fadffae17f31507a3d79a7b7f1cef71660767e0d

**Comment by laanwj** [comment]
utACK fadffae17f31507a3d79a7b7f1cef71660767e0d
good catch—somehow expected we'd have removed the qt4 workarounds by now, but this one was hiding

**Pull request merged**
