### PR TITLE
ci: Set MSVC toolset version explicitly

### PR DESCRIPTION
**Pull request by hebasto**
This PR is an alternative to https://github.com/bitcoin/bitcoin/pull/28905 and reverts it.

To avoid toolset version incompatibilities, which result in errors like this:
```
LINK : fatal error C1900: Il mismatch between 'P1' version '20230904' and 'P2' version '20221215' [D:\a\bitcoin\bitcoin\build_msvc\test_bitcoin\test_bitcoin.vcxproj]
LINK : fatal error LNK1257: code generation failed [D:\a\bitcoin\bitcoin\build_msvc\test_bitcoin\test_bitcoin.vcxproj]
LINK : fatal error LNK1327: failure during running link.exe [D:\a\bitcoin\bitcoin\build_msvc\test_bitcoin\test_bitcoin.vcxproj]
```

it is enough to set it explicitly in the vcpkg triplet file (see the second commit). The `VCToolsVersion` environment variable is set by the `ilammy/msvc-dev-cmd` action.

Please note that the https://github.com/bitcoin/bitcoin/pull/28905 is not [optimal](https://github.com/bitcoin/bitcoin/pull/28905#issuecomment-1822571419):
> I guess this is something we'll just have to maintain forever? That's a shame, because it also adds ~30% runtime to this CI job.

### CODE REVIEW

**Review by pablomartin4btc — APPROVED** [review]
ACK 70100f8584c762cbc6cbc09d05cc4e9d22a3ec75 since I've reviewed to be reverted #28905.

**Comment by sipsorcery** [comment]
Does the CI job still cache the vcpkg dependencies? Will this PR still work if there a minor version update on the build image?

**Comment by hebasto** [comment]
> Does the CI job still cache the vcpkg dependencies?

It does.

> Will this PR still work if there a minor version update on the build image?

I've added the toolset version to the cache key: https://github.com/bitcoin/bitcoin/blob/70100f8584c762cbc6cbc09d05cc4e9d22a3ec75/.github/workflows/ci.yml#L250

so the cache will be invalidated if it is changed.

**Comment by sipsorcery** [comment]
utACK 4335e553596a0ad5b136d3aa9fc898c906d226b4.

**Comment by hebasto** [comment]
@sipsorcery 

> utACK [4335e55](https://github.com/bitcoin/bitcoin/commit/4335e553596a0ad5b136d3aa9fc898c906d226b4).

Wrong hash?

:)

**Comment by hebasto** [comment]
cc @maflcko @fanquake

**Pull request merged**
