### PR TITLE
RPC: Consistently use UniValue.pushKV instead of push_back(Pair()) (karel-3d)

### PR DESCRIPTION
**Pull request by maflcko**
Rebased version of  #11386 by karel-3d.

Closes:  #11386

### CODE REVIEW

**Comment by jnewbery** [comment]
Tested ACK cf931d85d3089b5e42c2256ed335ff00fcbcc057

**Comment by MarcoFalke** [comment]
Rebased

**Review by dcousens — APPROVED** [review]

**Comment by jnewbery** [comment]
tested ACK b7de633eb2105758d8d92089a0dbcaba23eea5d0

**Comment by MarcoFalke** [comment]
Rebased.

This is a subtree bump and simple scripted diff. Should be trivial to review.

**Pull request merged**
