### PR TITLE
Fix debug log message for block files

### PR DESCRIPTION
**Pull request by morcos**
This will cause the log messages to have the right information again.

### CODE REVIEW

**Comment by tulip0** [comment]
Confirmed this fixes the broken log prints in master.

    2015-11-18 03:04:29 Leaving block file 376: CBlockFileInfo(blocks=0, size=0, heights=0...0, time=1970-01-01...1970-01-01)

to

    2015-11-18 06:02:41 Leaving block file 19: CBlockFileInfo(blocks=9469, size=134217001, heights=575072...584179, time=2015-09-29...2015-11-08)

**Comment by fanquake** [comment]
utACK

**Comment by MarcoFalke** [comment]
utACK

**Comment by gmaxwell** [comment]
ACK.

**Pull request merged**
