### PR TITLE
Fix spelling mistakes in code documentation

### PR DESCRIPTION
**Pull request by maaku**
See commits for details. Does change the test binary due to JSON strings.

### CODE REVIEW

**Comment by Diapolo** [comment]
Should go to https://github.com/theuni/bitcoin/tree/trivial-next

**Comment by dcousens** [comment]
@Diapolo what is that repository by comparison?  Why can't it be merged here? 
I don't see any notes RE the above in https://github.com/bitcoin/bitcoin#development-process,  so please forgive me if I've missed something.

**Comment by fanquake** [comment]
@dcousens Please don't comment on three different issues asking the same question; it just results in email spam.. The trivial next repository was set up to handle trivial code changes and to try keep some of the "noise" out of the main repository.

**Comment by dcousens** [comment]
@fanquake sure.  I removed the superfluous comment in #6543.
There is no mention of that process in the `README`,  is it listed somewhere officially?

**Comment by fanquake** [comment]
@dcousens The repo is still somewhat experimental. It's had some traffic, and been merged back into the main repository at least three time now, see #6135, #6004 and the original merge in #5731. Given that we're pointing people to it we probably should mention it in the documentation. Feel free to submit a pull request (to the main repo) to add some notes. 

Using a separate branch in this repository doesn't solve the "noise" problem. Anyone following this repository would still get emailed for every trivial pull request, and every comment each trivial pull.

**Comment by jonasschnelli** [comment]
ACK.
But should go over @theuni s trivial branch.

**Comment by dcousens** [comment]
@fanquake the joys of a monolithic code base. 
Shall we put it in the README?

**Comment by laanwj** [comment]
Just going to merge this now. But yes we should get the trivial branch running again @theuni, please submit there next time.

**Pull request merged**
