### PR TITLE
guix: point to latest upstream master

### PR DESCRIPTION
**Pull request by fanquake**
Now that Carls fix for binutils and compressed debug sections has been
merged into Guix, point our time-machine to the latest commit on Guix
master. The Windows builds don't yet work with this change, but we are
now at the point of compiling our own code..

There must be a difference in the Guix environment, compared to, for
example, compiling using GCC 10.3 on Ubuntu Hirsute, which currently works.

Opening this PR for testing / discussion:
```bash
Making all in src
make[1]: Entering directory '/distsrc-base/distsrc-f6ff8d8604f6-x86_64-w64-mingw32/src'
make[2]: Entering directory '/distsrc-base/distsrc-f6ff8d8604f6-x86_64-w64-mingw32/src'
  CXX      bitcoind-bitcoind.o
  CXX      libbitcoin_node_a-addrdb.o
  CXX      libbitcoin_node_a-addrman.o
  CXX      libbitcoin_node_a-banman.o
  GEN      bitcoind-res.o
  CXX      libbitcoin_node_a-blockencodings.o
  CXX      libbitcoin_node_a-blockfilter.o
  CXX      libbitcoin_node_a-chain.o
  CXX      libbitcoin_node_a-dbwrapper.o
  CXX      libbitcoin_node_a-deploymentstatus.o
  CXX      libbitcoin_node_a-flatfile.o
  CXX      libbitcoin_node_a-httprpc.o
  CXX      libbitcoin_node_a-httpserver.o
  CXX      libbitcoin_node_a-i2p.o
  CXX      libbitcoin_node_a-init.o
  CXX      libbitcoin_node_a-mapport.o
  CXX      libbitcoin_node_a-net.o
  CXX      libbitcoin_node_a-net_processing.o
  CXX      libbitcoin_node_a-noui.o
  CXX      libbitcoin_node_a-pow.o
  CXX      libbitcoin_node_a-rest.o
  CXX      libbitcoin_node_a-shutdown.o
In file included from init.cpp:78:
/gnu/store/k3bs5211ca8hy7hzkj83caiakmj3sh36-gcc-cross-x86_64-w64-mingw32-10.3.0/include/c++/fstream: In instantiation of 'std::basic_ofstream<_CharT, _Traits>::basic_ofstream(const _Path&, std::ios_base::openmode) [with _Path = fs::path; _Require = fs::path; _CharT = char; _Traits = std::char_traits<char>; std::ios_base::openmode = std::ios_base::openmode]':
init.cpp:143:40:   required from here
/gnu/store/k3bs5211ca8hy7hzkj83caiakmj3sh36-gcc-cross-x86_64-w64-mingw32-10.3.0/include/c++/fstream:844:38: error: no matching function for call to 'std::basic_ofstream<char>::basic_ofstream(const value_type*, std::ios_base::openmode&)'
  844 |  : basic_ofstream(__s.c_str(), __mode)
      |                                      ^
/gnu/store/k3bs5211ca8hy7hzkj83caiakmj3sh36-gcc-cross-x86_64-w64-mingw32-10.3.0/include/c++/fstream:850:7: note: candidate: 'std::basic_ofstream<_CharT, _Traits>::basic_ofstream(std::basic_ofstream<_CharT, _Traits>&&) [with _CharT = char; _Traits = std::char_traits<char>]'
  850 |       basic_ofstream(basic_ofstream&& __rhs)
      |       ^~~~~~~~~~~~~~
/gnu/store/k3bs5211ca8hy7hzkj83caiakmj3sh36-gcc-cross-x86_64-w64-mingw32-10.3.0/include/c++/fstream:850:7: note:   candidate expects 1 argument, 2 provided
/gnu/store/k3bs5211ca8hy7hzkj83caiakmj3sh36-gcc-cross-x86_64-w64-mingw32-10.3.0/include/c++/fstream:842:2: note: candidate: 'template<class _Path, class _Require> std::basic_ofstream<_CharT, _Traits>::basic_ofstream(const _Path&, std::ios_base::openmode) [with _Path = _Path; _Require = _Require; _CharT = char; _Traits = std::char_traits<char>]'
  842 |  basic_ofstream(const _Path& __s,
      |  ^~~~~~~~~~~~~~
/gnu/store/k3bs5211ca8hy7hzkj83caiakmj3sh36-gcc-cross-x86_64-w64-mingw32-10.3.0/include/c++/fstream:842:2: note:   template argument deduction/substitution failed:
/gnu/store/k3bs5211ca8hy7hzkj83caiakmj3sh36-gcc-cross-x86_64-w64-mingw32-10.3.0/include/c++/fstream:841:32: error: request for member 'make_preferred' in 'std::declval<const wchar_t*&>()', which is of non-class type 'const wchar_t*'
  841 |       template<typename _Path, typename _Require = _If_fs_path<_Path>>
      |                                ^~~~~~~~
/gnu/store/k3bs5211ca8hy7hzkj83caiakmj3sh36-gcc-cross-x86_64-w64-mingw32-10.3.0/include/c++/fstream:825:7: note: candidate: 'std::basic_ofstream<_CharT, _Traits>::basic_ofstream(const string&, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::string = std::__cxx11::basic_string<char>; std::ios_base::openmode = std::ios_base::openmode]'
  825 |       basic_ofstream(const std::string& __s,
      |       ^~~~~~~~~~~~~~
/gnu/store/k3bs5211ca8hy7hzkj83caiakmj3sh36-gcc-cross-x86_64-w64-mingw32-10.3.0/include/c++/fstream:825:41: note:   no known conversion for argument 1 from 'const value_type*' {aka 'const wchar_t*'} to 'const string&' {aka 'const std::__cxx11::basic_string<char>&'}
  825 |       basic_ofstream(const std::string& __s,
      |                      ~~~~~~~~~~~~~~~~~~~^~~
/gnu/store/k3bs5211ca8hy7hzkj83caiakmj3sh36-gcc-cross-x86_64-w64-mingw32-10.3.0/include/c++/fstream:790:7: note: candidate: 'std::basic_ofstream<_CharT, _Traits>::basic_ofstream(const char*, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::ios_base::openmode = std::ios_base::openmode]'
  790 |       basic_ofstream(const char* __s,
      |       ^~~~~~~~~~~~~~
/gnu/store/k3bs5211ca8hy7hzkj83caiakmj3sh36-gcc-cross-x86_64-w64-mingw32-10.3.0/include/c++/fstream:790:34: note:   no known conversion for argument 1 from 'const value_type*' {aka 'const wchar_t*'} to 'const char*'
  790 |       basic_ofstream(const char* __s,
      |                      ~~~~~~~~~~~~^~~
/gnu/store/k3bs5211ca8hy7hzkj83caiakmj3sh36-gcc-cross-x86_64-w64-mingw32-10.3.0/include/c++/fstream:779:7: note: candidate: 'std::basic_ofstream<_CharT, _Traits>::basic_ofstream() [with _CharT = char; _Traits = std::char_traits<char>]'
  779 |       basic_ofstream(): __ostream_type(), _M_filebuf()
      |       ^~~~~~~~~~~~~~
/gnu/store/k3bs5211ca8hy7hzkj83caiakmj3sh36-gcc-cross-x86_64-w64-mingw32-10.3.0/include/c++/fstream:779:7: note:   candidate expects 0 arguments, 2 provided
/gnu/store/k3bs5211ca8hy7hzkj83caiakmj3sh36-gcc-cross-x86_64-w64-mingw32-10.3.0/include/c++/fstream:844:38: error: no matching function for call to 'std::basic_ofstream<char>::basic_ofstream(const value_type*, std::ios_base::openmode&)'
  844 |  : basic_ofstream(__s.c_str(), __mode)
      |                                      ^
/gnu/store/k3bs5211ca8hy7hzkj83caiakmj3sh36-gcc-cross-x86_64-w64-mingw32-10.3.0/include/c++/fstream:850:7: note: candidate: 'std::basic_ofstream<_CharT, _Traits>::basic_ofstream(std::basic_ofstream<_CharT, _Traits>&&) [with _CharT = char; _Traits = std::char_traits<char>]'
  850 |       basic_ofstream(basic_ofstream&& __rhs)
      |       ^~~~~~~~~~~~~~
/gnu/store/k3bs5211ca8hy7hzkj83caiakmj3sh36-gcc-cross-x86_64-w64-mingw32-10.3.0/include/c++/fstream:850:7: note:   candidate expects 1 argument, 2 provided
/gnu/store/k3bs5211ca8hy7hzkj83caiakmj3sh36-gcc-cross-x86_64-w64-mingw32-10.3.0/include/c++/fstream:842:2: note: candidate: 'template<class _Path, class _Require> std::basic_ofstream<_CharT, _Traits>::basic_ofstream(const _Path&, std::ios_base::openmode) [with _Path = _Path; _Require = _Require; _CharT = char; _Traits = std::char_traits<char>]'
  842 |  basic_ofstream(const _Path& __s,
      |  ^~~~~~~~~~~~~~
/gnu/store/k3bs5211ca8hy7hzkj83caiakmj3sh36-gcc-cross-x86_64-w64-mingw32-10.3.0/include/c++/fstream:842:2: note:   template argument deduction/substitution failed:
/gnu/store/k3bs5211ca8hy7hzkj83caiakmj3sh36-gcc-cross-x86_64-w64-mingw32-10.3.0/include/c++/fstream:841:32: error: request for member 'make_preferred' in 'std::declval<const wchar_t*&>()', which is of non-class type 'const wchar_t*'
  841 |       template<typename _Path, typename _Require = _If_fs_path<_Path>>
      |                                ^~~~~~~~
/gnu/store/k3bs5211ca8hy7hzkj83caiakmj3sh36-gcc-cross-x86_64-w64-mingw32-10.3.0/include/c++/fstream:825:7: note: candidate: 'std::basic_ofstream<_CharT, _Traits>::basic_ofstream(const string&, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::string = std::__cxx11::basic_string<char>; std::ios_base::openmode = std::ios_base::openmode]'
  825 |       basic_ofstream(const std::string& __s,
      |       ^~~~~~~~~~~~~~
/gnu/store/k3bs5211ca8hy7hzkj83caiakmj3sh36-gcc-cross-x86_64-w64-mingw32-10.3.0/include/c++/fstream:825:41: note:   no known conversion for argument 1 from 'const value_type*' {aka 'const wchar_t*'} to 'const string&' {aka 'const std::__cxx11::basic_string<char>&'}
  825 |       basic_ofstream(const std::string& __s,
      |                      ~~~~~~~~~~~~~~~~~~~^~~
/gnu/store/k3bs5211ca8hy7hzkj83caiakmj3sh36-gcc-cross-x86_64-w64-mingw32-10.3.0/include/c++/fstream:790:7: note: candidate: 'std::basic_ofstream<_CharT, _Traits>::basic_ofstream(const char*, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::ios_base::openmode = std::ios_base::openmode]'
  790 |       basic_ofstream(const char* __s,
      |       ^~~~~~~~~~~~~~
/gnu/store/k3bs5211ca8hy7hzkj83caiakmj3sh36-gcc-cross-x86_64-w64-mingw32-10.3.0/include/c++/fstream:790:34: note:   no known conversion for argument 1 from 'const value_type*' {aka 'const wchar_t*'} to 'const char*'
  790 |       basic_ofstream(const char* __s,
      |                      ~~~~~~~~~~~~^~~
/gnu/store/k3bs5211ca8hy7hzkj83caiakmj3sh36-gcc-cross-x86_64-w64-mingw32-10.3.0/include/c++/fstream:779:7: note: candidate: 'std::basic_ofstream<_CharT, _Traits>::basic_ofstream() [with _CharT = char; _Traits = std::char_traits<char>]'
  779 |       basic_ofstream(): __ostream_type(), _M_filebuf()
      |       ^~~~~~~~~~~~~~
/gnu/store/k3bs5211ca8hy7hzkj83caiakmj3sh36-gcc-cross-x86_64-w64-mingw32-10.3.0/include/c++/fstream:779:7: note:   candidate expects 0 arguments, 2 provided
  CXX      libbitcoin_node_a-signet.o
  CXX      libbitcoin_node_a-timedata.o
  CXX      libbitcoin_node_a-torcontrol.o
  CXX      libbitcoin_node_a-txdb.o
make[2]: *** [Makefile:9653: libbitcoin_node_a-init.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/distsrc-base/distsrc-f6ff8d8604f6-x86_64-w64-mingw32/src'
make[1]: *** [Makefile:17461: all-recursive] Error 1
make[1]: Leaving directory '/distsrc-base/distsrc-f6ff8d8604f6-x86_64-w64-mingw32/src'
make: *** [Makefile:816: all-recursive] Error 1
```

Related to #24055.

### CODE REVIEW

**Comment by hebasto** [comment]
Yesterday I was building against [4be896d6e0d322b3f5b514c8a2811efcd6a31606](https://git.savannah.gnu.org/cgit/guix.git/commit/?id=4be896d6e0d322b3f5b514c8a2811efcd6a31606) Guix commit, and have got the same error.

The weirdest part of the error message is
```
... error: request for member 'make_preferred' in 'std::declval<const wchar_t*&>()', which is of non-class type 'const wchar_t*'
```

Friendly ping @dongcarl @ryanofsky

**Comment by ryanofsky** [comment]
Fanquake's error seems to come from this line (based on `init.cpp:143:40:   required from here`)

https://github.com/bitcoin/bitcoin/blob/f6ff8d8604f65c4cb5392e2259d77439665867e7/src/init.cpp#L143

Which happens for the reason we are familiar with that std::fstream does not like `fs::path` objects

I'm not sure about the other `make_preferred` error. The place I see us calling that is

https://github.com/bitcoin/bitcoin/blob/f6ff8d8604f65c4cb5392e2259d77439665867e7/src/test/util/chainstate.h#L40 

which looks ok to me

**Comment by MarcoFalke** [comment]
So I guess the solution will be to partially revert `fs`? That is: `std::ofstream` -> `fs::ofstream`.

**Comment by hebasto** [comment]
> So I guess the solution will be to partially revert `fs`? That is: `std::ofstream` -> `fs::ofstream`.

FWIW, I've tried such approaches in some variants without success..

**Comment by MarcoFalke** [comment]
Is there any way to reproduce this outside of guix?

**Comment by dongcarl** [comment]
Might it be because of: https://salsa.debian.org/mingw-w64-team/gcc-mingw-w64/-/blob/2ee26ff4f275384aa6173ada884929db4d2f1bbf/debian/rules#L228

**Comment by hebasto** [comment]
I've made some investigations. The error does not caused by our `fs::path` class. A similar error happens when using pure `std::filesystem::path`.

> I'm not sure about the other `make_preferred` error.

It happens during template argument substitution in `typename _Require = _If_fs_path<_Path>`.

**Comment by hebasto** [comment]
FWIW, in Guix environment the `_GLIBCXX_HAVE__WFOPEN` macro is undefined.

**Comment by hebasto** [comment]
@dongcarl 
> Might it be because of: https://salsa.debian.org/mingw-w64-team/gcc-mingw-w64/-/blob/2ee26ff4f275384aa6173ada884929db4d2f1bbf/debian/rules#L228

I've verified this assumption.

Indeed, in Guix environment the macro `_GLIBCXX_FULLY_DYNAMIC_STRING` is defined to `0` which differs from non-Guix environment where it is defined to `1`.

The following patch:
```diff
--- a/contrib/guix/manifest.scm
+++ b/contrib/guix/manifest.scm
@@ -160,7 +160,7 @@ desirable for building Bitcoin Core release binaries."
                         base-gcc))
 
 (define (make-gcc-with-pthreads gcc)
-  (package-with-extra-configure-variable gcc "--enable-threads" "posix"))
+  (package-with-extra-configure-variable (package-with-extra-configure-variable gcc "--enable-fully-dynamic-string" "yes") "--enable-threads" "posix"))
 
 (define (make-mingw-pthreads-cross-toolchain target)
   "Create a cross-compilation toolchain package for TARGET"
```
makes `_GLIBCXX_FULLY_DYNAMIC_STRING` defined to `1`, but the error still exists, unfortunately.

**Comment by dongcarl** [comment]
Okay leaving a comment here for myself and anyone else who wants to dive in: it seems that `_GLIBCXX_FULLY_DYNAMIC_STRING` doesn't really affect this much.

What does affect it is `_GLIBCXX_HAVE__WFOPEN`, which is undefined in the Guix environment and defined in the Ubuntu Impish environment. Despite its name it actually affects `open` and the `*fstream` constructors, so would match the errors we're seeing. No `--enable-wchar_t=yes` does not solve this.

Additional info:

Reproducer:
```
#include <filesystem>
#include <fstream>

namespace fs = std::filesystem;

int main() {
    fs::path p = "./what";
    std::ofstream file{p};
    return 0;
}
```

Alt reproducer:

```
#include <filesystem>
#include <fstream>

namespace fs = std::filesystem;

int main() {
    wchar_t p[] {L"./what"};
    std::ofstream file{p};
    return 0;
}
```

Compile with:
```
$ x86_64-w64-mingw32-g++ -std=c++17 test.cpp
```

In impish docker:
```sh
# x86_64-w64-mingw32-nm -C a.exe | grep stream
00000000004015d8 T std::basic_ofstream<char, std::char_traits<char> >::basic_ofstream(wchar_t const*, std::_Ios_Openmode)
00000000004015d0 T std::basic_ofstream<char, std::char_traits<char> >::~basic_ofstream()
00000000004082d8 I __imp__ZNSt14basic_ofstreamIcSt11char_traitsIcEEC1EPKwSt13_Ios_Openmode
00000000004082e0 I __imp__ZNSt14basic_ofstreamIcSt11char_traitsIcEED1Ev
```

**Comment by Meru852** [comment]
I think most users about the roaming of the files running disk. cause most users asked me how to change the AppData\Roaming\Bitcoin runnings disk? they don't have enough space in their storage. some one please help me get this solution.

**Comment by hebasto** [comment]
> FWIW, in Guix environment the `_GLIBCXX_HAVE__WFOPEN` macro is undefined.

> What does affect it is `_GLIBCXX_HAVE__WFOPEN`, which is undefined in the Guix environment and defined in the Ubuntu Impish environment. Despite its name it actually affects `open` and the `*fstream` constructors, so would match the errors we're seeing.

Are mingw headers available at this point https://gcc.gnu.org/git/?p=gcc.git;a=blob;f=libstdc%2B%2B-v3/crossconfig.m4;h=fe1828835368dd5c2c16a20cf4abc52739e52f30;hb=f00b5710a30f22efc3171c393e56aeb335c3cd39#l200:
```
    AC_CHECK_FUNCS(_wfopen)
```
?

**Comment by hebasto** [comment]
After further investigation, I suspect the [following option](https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/cross-base.scm#n183):
```
                             '("--with-newlib")
```

I was trying:
```diff
--- a/contrib/guix/manifest.scm
+++ b/contrib/guix/manifest.scm
@@ -160,7 +160,7 @@ desirable for building Bitcoin Core release binaries."
                         base-gcc))
 
 (define (make-gcc-with-pthreads gcc)
-  (package-with-extra-configure-variable gcc "--enable-threads" "posix"))
+  (package-with-extra-configure-variable (package-with-extra-configure-variable gcc "--with-newlib" "no") "--enable-threads" "posix"))
 
 (define (make-mingw-pthreads-cross-toolchain target)
   "Create a cross-compilation toolchain package for TARGET"
```
but it fails because `--with-newlib` actually overrides my custom option:
```
configure flags: ("CONFIG_SHELL=/gnu/store/4y5m9lb8k3qkb1y9m02sw9w9a6hacd16-bash-minimal-5.1.8/bin/bash" "SHELL=/gnu/store/4y5m9lb8k3qkb1y9m02sw9w9a6hacd16-bash-minimal-5.1.8/bin/bash" "--prefix=/gnu/store/byrh6d5ldyx0i80a39l2q9mns0cd4vp2-gcc-cross-x86_64-w64-mingw32-10.3.0" "--enable-fast-install" "--libdir=/gnu/store/wxjzjz3pajgknmfvj3mg9fvx3l99wmla-gcc-cross-x86_64-w64-mingw32-10.3.0-lib/lib" "--includedir=/gnu/store/wxjzjz3pajgknmfvj3mg9fvx3l99wmla-gcc-cross-x86_64-w64-mingw32-10.3.0-lib/include" "--build=x86_64-unknown-linux-gnu" "--enable-threads=posix" "--with-newlib=no" "--target=x86_64-w64-mingw32" "--disable-libcilkrts" "--with-sysroot=/" "--with-toolexeclibdir=/gnu/store/wxjzjz3pajgknmfvj3mg9fvx3l99wmla-gcc-cross-x86_64-w64-mingw32-10.3.0-lib/x86_64-w64-mingw32/lib" "--with-newlib" "--enable-plugin" "--enable-languages=c,c++" "--disable-multilib" "--with-system-zlib" "--disable-libstdcxx-pch" "--with-local-prefix=/no-gcc-local-prefix" "--with-gxx-include-dir=/gnu/store/byrh6d5ldyx0i80a39l2q9mns0cd4vp2-gcc-cross-x86_64-w64-mingw32-10.3.0/include/c++" "--with-native-system-header-dir=/gnu/store/39m4gjy9dn18r6vcka1iyvl0979zwnv8-mingw-w64-x86_64-winpthreads-8.0.0/include" "CC_FOR_TARGET=x86_64-w64-mingw32-gcc" "CXX_FOR_TARGET=x86_64-w64-mingw32-g++" "LD_FOR_TARGET=x86_64-w64-mingw32-ld" "AR_FOR_TARGET=x86_64-w64-mingw32-ar" "NM_FOR_TARGET=x86_64-w64-mingw32-nm" "OBJDUMP_FOR_TARGET=x86_64-w64-mingw32-objdump" "RANLIB_FOR_TARGET=x86_64-w64-mingw32-ranlib" "STRIP_FOR_TARGET=x86_64-w64-mingw32-strip")
```

@dongcarl What is the correct way to build with `--without-newlib` option?

**Comment by hebasto** [comment]
> After further investigation, I suspect the [following option](https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/cross-base.scm#n183):
> 
> ```
>                              '("--with-newlib")
> ```

A solution suggested in #24348.

**Comment by fanquake** [comment]
Let's continue discussion in #24348 for now.

**Pull request closed without merging**
