### PR TITLE
Drop JSONRPCRequest constructors after #21366

### PR DESCRIPTION
**Pull request by ryanofsky**
This just makes an additional simplification after #21366 replaced
util::Ref with std::any. It was originally suggested
https://github.com/bitcoin/bitcoin/pull/21366#issuecomment-792044351 but
delayed for a followup. It would have prevented usage bug
https://github.com/bitcoin/bitcoin/pull/21572.

### CODE REVIEW

**Comment by theStack** [comment]
Concept ACK

Considering the bug fixed in #21572, I think it would also make sense to deduplicate the two loops in `WalletClientImpl::registerRpcs()`, as their bodies contain exactly the same code. (Doesn't necessarily have to be in this PR though; if not, I'm happy to do a follow-up).

**Comment by ryanofsky** [comment]
> I think it would also make sense to deduplicate the two loops in `WalletClientImpl::registerRpcs()`, as their bodies contain exactly the same code. (Doesn't necessarily have to be in this PR though; if not, I'm happy to do a follow-up).

Thanks for reviewing and suggesting the improvement. #21467 is removing the second loop though, so best not to consolidate these.

**Review by meshcollider — COMMENTED** [review]
Code review ACK 2b9871142607159bb102ac58edd51d62b413a050

**Review by theStack — APPROVED** [review]
Code-review ACK 2b9871142607159bb102ac58edd51d62b413a050
Nice simplification!

**Review by promag — COMMENTED** [review]
Code review ACK 2b9871142607159bb102ac58edd51d62b413a050

**Comment by MarcoFalke** [comment]
I think you forgot to rebase this on 937fd4a66f048780bffc5e714d0c800de987ce93 when opening the pr. Git can't figure out that this doesn't conflict, otherwise.

**Comment by ryanofsky** [comment]
> I think you forgot to rebase this on [937fd4a](https://github.com/bitcoin/bitcoin/commit/937fd4a66f048780bffc5e714d0c800de987ce93) when opening the pr. Git can't figure out that this doesn't conflict, otherwise.

Thanks! Rebased now.

---

Rebased 2b9871142607159bb102ac58edd51d62b413a050 -> 9044522ef76f880760165d98fab024802ccfc062 ([`pr/simpreq.1`](https://github.com/ryanofsky/bitcoin/commits/pr/simpreq.1) -> [`pr/simpreq.2`](https://github.com/ryanofsky/bitcoin/commits/pr/simpreq.2), [compare](https://github.com/ryanofsky/bitcoin/compare/pr/simpreq.1-rebase..pr/simpreq.2)) due to conflict with #21572

**Comment by promag** [comment]
ACK 9044522ef76f880760165d98fab024802ccfc062, fixed conflict in src/wallet/interfaces.cpp.

**Pull request merged**
