### PR TITLE
scripts: move update-translations.py to maintainer-tools repo

### PR DESCRIPTION
**Pull request by fanquake**
As mentioned in [#16644](https://github.com/bitcoin/bitcoin/pull/16644#issuecomment-522481111), move the `update-translations.py` script out of the `bitcoin/bitcoin` repo. This script is run infrequently by maintainers, and aside from #16644, doesn't see many changes. If it is going to be changed, it probably shouldn't consume review bandwidth in bitcoin/bitcoin anyways.

PR adding the script to the maintainer-tools repo: https://github.com/bitcoin-core/bitcoin-maintainer-tools/pull/31

Could also move some other scripts, such as [`gen-manpages.sh`](https://github.com/bitcoin/bitcoin/blob/master/contrib/devtools/gen-manpages.sh).

### CODE REVIEW

**Comment by GChuf** [comment]
Why not include the other scripts in devtools as well then? They might get updated in the future as well.

**Comment by emilengler** [comment]
Could you update the link to the script in the maintainers repo once the PR is being merged?

**Comment by fanquake** [comment]
> Why not include the other scripts in devtools as well then? They might get updated in the future as well.

I might update this to include `gen-manpags.sh`. I don't think everything in `devtools/` needs to be moved into the maintainer repo, because they aren't all maintainer tools.

**Comment by laanwj** [comment]
ACK 3d50fe2c1fb566501257fc16d4606e06f518a0bb 
this was merged to maintainer-tools n bitcoin-core/bitcoin-maintainer-tools#31

>Why not include the other scripts in devtools as well then? They might get updated in the future as well.

Maybe. Let's discuss these on a case by case basis.

**Pull request merged**
