### PR TITLE
[Qt] remove size grip to get rid of the right margin

### PR DESCRIPTION
**Pull request by jonasschnelli**
IMO nobody needs a size grip and it looks bad

### CODE REVIEW

**Comment by Diapolo** [comment]
Just to mention it, Thunderbird on Windows has it, Firefox or IE don't... not sure about this one. I tend to don't care ;).

**Comment by luke-jr** [comment]
Prefer to keep it (it's not hurting anything), but don't care.

**Comment by jonasschnelli** [comment]
@luke-jr: I know. It's minimal.
But have a look at the screenshot/mockup below.
I really care about margins and paddings.
The right unused margin in the status bar always poked me.

github

**Comment by fanquake** [comment]
Tested ACK

**Comment by jonasschnelli** [comment]
prebuilt binaries for testing: https://builds.jonasschnelli.ch/pulls/5628/

**Comment by laanwj** [comment]
Seems a bit like the UI equivalent of premature optimization. Isn't the point of a size grip to communicate that the window can be resized?

**Comment by jonasschnelli** [comment]
@laanwj: Right. But the grip is only visible on windows. On Linux and Mac there is a unused space to the right.

On window there are many apps where the grip is not visible but the window is also resizable.

**Comment by jonasschnelli** [comment]
See also:
Internet Explorer, Filer-Explorer, Terminal: nowadays most apps/windows don't have a resize handle.

bildschirmfoto 2015-01-20 um 16 18 29

**Pull request merged**
