### PR TITLE
Remove mapRequest tracking that just effects Qt display.

### PR DESCRIPTION
**Pull request by TheBlueMatt**
I thought we had removed this a long time ago, TBH, its really
confusing feedback to users that we display whether a tx was
broadcast to immediate neighbor nodes, given that has little
indication of whether the tx propagated very far.

### CODE REVIEW

**Comment by gmaxwell** [comment]
ACK. I also thought so too. LGTM.

**Comment by laanwj** [comment]
Concept ACK.
I tried to remove it in the deep past: #3380.
@sipa disagreed at the time, so let's ask again.

**Comment by sipa** [comment]
@laanwj Heh, I don't even remember anymore.

Concept ACK, the current approach isn't a good way to measure network propagation anyway.

**Comment by gmaxwell** [comment]
We'd want to do something different (which would also be much more effective and less confusing) after dandelion and/mempool sync is implemented, anyways.

**Comment by MarcoFalke** [comment]
utACK beef7ec4be725beea870a2da510d2817487601ec

**Comment by laanwj** [comment]
> Concept ACK, the current approach isn't a good way to measure network propagation anyway.

Right, in one direction it is: if a transaction has not been requested by any other node, you can be sure it hasn't propagated. But not the other way around.

**Comment by theuni** [comment]
utACK beef7ec4be725beea870a2da510d2817487601ec

**Comment by jtimon** [comment]
utACK beef7ec4be725beea870a2da510d2817487601ec

**Pull request merged**
