### PR TITLE
test: get and decode tx with a single `gettransaction` RPC call

### PR DESCRIPTION
**Pull request by theStack**
Rather than subsequently calling `gettransaction` and `decoderawtransaction` to get the decoded information  for a specific tx-id, we can simply use the verbose version of `gettransaction`, which returns this in a 'decoded' key. I.e.

```
node.decoderawtransaction(node.gettransaction(txid)['hex'])
```

can simply be replaced by:

```
node.gettransaction(txid=txid, verbose=True)['decoded']
```

Rationale: shorter code, shorter test logs, less RPC calls.

### CODE REVIEW

**Review by promag — COMMENTED** [review]
Code review ACK c045207fb4a96f3cbdf7841ecab5c36323ea01a3. Didn't check if same approach could be applied in other places.

**Review by shaavan — COMMENTED** [review]
Concept ACK

This PR simplifies the code and RPC calls around getting a transaction and decoding it. I was able to successfully compile the PR on Ubuntu 20.04 without any errors. Nice catch, @theStack!

> I think mempool_packages.py (line 68 and 69) could be also included here, couldn't it?

I think this is a valid suggestion. I tried to implement this myself while testing, and I was able to successfully do so in the following way:

```diff
# We need the wtxids to check P2P announcements
-            fulltx = self.nodes[0].getrawtransaction(txid)
-            witnesstx = self.nodes[0].decoderawtransaction(fulltx, True)
+            witnesstx = self.nodes[0].gettransaction(txid=txid, verbose=True)['decoded']
             witness_chain.append(witnesstx['hash'])
```

**Review by brunoerg — APPROVED** [review]
tACK c045207fb4a96f3cbdf7841ecab5c36323ea01a3

**Comment by brunoerg** [comment]
> > I think mempool_packages.py (line 68 and 69) could be also included here, couldn't it?
> 
> I think this is a valid suggestion. I tried to implement this myself while testing, and I was able to successfully do so in the following way:
> 
> ```diff
> # We need the wtxids to check P2P announcements
> -            fulltx = self.nodes[0].getrawtransaction(txid)
> -            witnesstx = self.nodes[0].decoderawtransaction(fulltx, True)
> +            witnesstx = self.nodes[0].gettransaction(txid=txid, verbose=True)['decoded']
>              witness_chain.append(witnesstx['hash'])
> ```

Great! I am gonna check if there are other places it could be applied

**Review by stratospher — COMMENTED** [review]
Tested ACK c045207

Verified that the output dictionary produced for a specific tx-id in both the master and PR are the same. There’s 1 more instance where this change can be applied:

In test/functional/rpc_rawtransaction.py:

- [L464-465](https://github.com/bitcoin/bitcoin/blob/feedb9c84e72e4fff489810a2bbeec09bcda5763/test/functional/rpc_rawtransaction.py#L464-L465)
- [L474-475](https://github.com/bitcoin/bitcoin/blob/feedb9c84e72e4fff489810a2bbeec09bcda5763/test/functional/rpc_rawtransaction.py#L474-L475)
- [L507-508](https://github.com/bitcoin/bitcoin/blob/feedb9c84e72e4fff489810a2bbeec09bcda5763/test/functional/rpc_rawtransaction.py#L507-L508)
- [L515-516](https://github.com/bitcoin/bitcoin/blob/feedb9c84e72e4fff489810a2bbeec09bcda5763/test/functional/rpc_rawtransaction.py#L515-L516)

**Review by amadeuszpawlik — APPROVED** [review]

**Review by lsilva01 — APPROVED** [review]
Tested ACK 130ee48 on Ubuntu 20.04.

**Review by shaavan — APPROVED** [review]
ACK 130ee481082d2612d452d7d69131ade935b225b5

**Pull request merged**
