### PR TITLE
refactor: move interfaces/* to common/interfaces/*

### PR DESCRIPTION
**Pull request by fanquake**
This came up in #26196: https://github.com/bitcoin/bitcoin/pull/26196#issuecomment-1268533492. Opening this as a draft for the minute, to point to from another PR.

Ultimately the goal here (aside from common quite possibly being a better home for this code) is to move the Boost Signals2 using code out of libbitcoin_util, which is/will be used by the kernel.

When this is done, we can drop `$(BOOST_CPPFLAGS)` from libbitcoin_util (last commit).

### CODE REVIEW

**Comment by ryanofsky** [comment]
I think something should be done about the inconsistency of having `libbitcoin_core.a` source files outside of the `src/common/` and this is one possible option. Other possible options are:

1. Move `src/interface/` files to a `libbitcoin_interfaces.a` library
2. Delete `src/interface/*.cpp` files and make `src/interfaces/` directory only contain headers

I think I like these options a little better, because they would keep source structure flat and avoid too much nesting. They would also avoid namespace inconsistencies or the need to have a nested `common::interfaces::` namespace that would make function declarations in headers more verbose.

I want look into option 2 a little more since it seems like the 3 .cpp files in the interfaces directory are very minimal and don't contain much real code.

**Comment by shaavan** [comment]
@ryanofsky 

As you mentioned, I agree that we should go for a less nested option when possible.

Now considering the alternatives you mentioned, Option 2 seems like a pretty interesting idea. I thought it to be a preferable option because it seemed a cleaner way to achieve our goal.
However, on second thought, what if we need to expand `src/interfaces` in the future for some reason, and going with a header-only route for the expansion might be unreasonable? So we might have to move to an option similar to your first suggestion.

This might be an infeasible scenario, and there might exist other options than the two you mentioned to achieve this goal, which I haven't considered. But I just wanted to explain why I think the second option, though cleaner, might not be feasible in the long run.

**Comment by ryanofsky** [comment]
I implemented option 2 above in #26293.

> However, on second thought, what if we need to expand `src/interfaces` in the future for some reason, and going with a header-only route for the expansion might be unreasonable?

I don't see this happening, just because the point of `src/interfaces/` directory is just to define abstract classes with virtual methods. Implementation of the interfaces belongs in the _node_, _wallet_, or _common_ libraries, or in the GUI. If implementation code sneaks into the interfaces directory it's probably a mistake. Or if it is really intentional, it could logically go into a `libbitcoin_interfaces.a` library that without requiring all the interfaces to move somewhere.

**Comment by fanquake** [comment]
> because they would keep source structure flat and avoid too much nesting. 

Is this something we are actively trying to avoid? i.e in https://github.com/bitcoin/bitcoin/pull/26250#discussion_r986997358 we seem to be going the other direction.

In any case, closing this in favour of #26298.

**Pull request closed without merging**
