### PR TITLE
Restore compatibility with old CSubNet serialization

### PR DESCRIPTION
**Pull request by sipa**
#19628 changed CSubNet for IPv4 netmasks, using the first 4 bytes of `netmask` rather than the last 4 to store the actual mask. Unfortunately, CSubNet objects are serialized on disk in banlist.dat, breaking compatibility with existing banlists (and bringing them into an inconsistent state where entries reported in `listbanned` cannot be removed).

Fix this by reverting to the old format (just for serialization). Also add a sanity check to the deserializer so that nonsensical banlist.dat entries are ignored (which would otherwise be possible if someone added IPv4 entries after #19628 but without this PR).

Reported by Greg Maxwell.

### CODE REVIEW

**Review by kallewoof — COMMENTED** [review]
Code review ACK

Slightly prefer if this was handled with versioning instead (i.e. bump banlist version, if there is one, have a grace period for a few versions where both are supported).

I think it's okay to eventually drop backwards compatibility for banlists, but maybe I don't take them seriously enough.

**Comment by sipa** [comment]
@kallewoof I agree that that would be the way to go if there was actually a feature change. There isn't. The serialization format was just gratuitously broken, and this reverts it.

**Comment by practicalswift** [comment]
Concept ACK

**Review by vasild — APPROVED** [review]
ACK 886be97af

Maybe we don't need to ignore the entries that have the IPv4 mask in the first 4 bytes (second commit) because this code was not released?

I am planning to [change](https://github.com/bitcoin/bitcoin/pull/19628#issuecomment-679958713) `CSubNet::netmask` from `uint8_t [16]` to just `uint8_t` (CIDR netmask number) and this is tightly related. I guess I will keep the (un)serialize to use this old format of 16 bytes with IPv4 netmask at the end because introducing a version of `banlist.dat` does not look justified (it will save 15 bytes per entry on disk).

**Comment by sipa** [comment]
@vasild Agree that there is no strong requirement to deal with files created/modified using unreleased code. But as it's perhaps a generally useful change (it guarantees that regardless of the file's contents, you'll never end up in a situation where there are entries in `listbanned` that cannot be remvoed using `setban`), perhaps it's useful to keep it in?

**Comment by laanwj** [comment]
Thanks for the quick fix!
Code review ACK 886be97af5d4aba338b23a7b20b8560be8156231

**Comment by gmaxwell** [comment]
I would suggest that it assert on any wonky-mask, except then you'd create a crash for anyone that had bans from current git master.  You really don't want those in memory, esp if later the ban lookup is changed to a patricia trie they'll turn into memory corruption bugs (unless the author of that code remembers this possibility and inserts the sanitization there).

Perhaps an alternative is to have the sanitization and the plan for removing it is to stop storing masks and instead store prefix lengths, so that the insane values are just not representable.

**Comment by sipa** [comment]
@gmaxwell This deletes the wonky-mask ones immediately after loading, FWIW.

**Comment by gmaxwell** [comment]
sorry, I was intending to respond to @wumpus who seemed to not like the deleting that much!

**Comment by sipa** [comment]
Oh, I missed that.

@laanwj I'm thinking that this sanity check should probably stay in the code. It isn't specific to the incompatbility here - any other damage to your banlist.dat file could also mean you end up with unremovable entries, so it seems like a generic improvement to protect against that.

**Comment by vasild** [comment]
> stop storing masks and instead store prefix lengths, so that the insane values are just not representable

Just to note that even if we store prefix lengths (CIDR), that would be stored in 1 byte and it is still possible to have insane values, e.g. 150.

**Comment by laanwj** [comment]
It's good to ward against corrupted data files, especially relatively unimportant ones like the ban list, but at some point, disk is a trusted interface. There are tons of ways disk corruption can crash the daemon. And sometimes it should, so that users are aware of what is happening, making things easier to diagnose.

That said I'm okay with this fix as it is, and don't think this particular change is worth bikeshedding too much.

**Pull request merged**
