### PR TITLE
Fix typos in `subprocess.hpp`

### PR DESCRIPTION
**Pull request by hebasto**
Resolves one item in the https://github.com/bitcoin/bitcoin/pull/28981#pullrequestreview-1991272752:
>    - Remove linter exclusions and fix all issues.

Based on upstream https://github.com/arun11299/cpp-subprocess/pull/101.

### CODE REVIEW

**Comment by hebasto** [comment]
cc @theStack

**Review by fanquake — APPROVED** [review]
ACK 13f5391bbb45cd8aebc6ae70cad08aff632ebd55

**Comment by Jgoedhart1988** [comment]
Hello World

**Review by Jgoedhart1988 — COMMENTED** [review]
Ok

**Pull request merged**
