### PR TITLE
contrib: refactor: simplify linearize scripts

### PR DESCRIPTION
**Pull request by theStack**
This PR simplifies the linearization scripts `linearize-data.py` and `linearize-hashes.py` by replacing overly complicated cruft (block header hash string calculation, hex string reverse) with means of the Python3 standard library.

### CODE REVIEW

**Comment by laanwj** [comment]
Concept ACK
NIce cleanup!

**Comment by laanwj** [comment]
It reminds me that we don't have any kind of test for these scripts. It might be good to have a standardized test, even if it involves manual steps. If anyone is still using these scripts at all? At the time linearize was introduced it was used to create a blockchain file for distribution through torrent. I don't think anyone has done that for a long time. But maybe it has other users.

**Comment by theStack** [comment]
> It reminds me that we don't have any kind of test for these scripts. It might be good to have a standardized test, even if it involves manual steps. If anyone is still using these scripts at all? At the time linearize was introduced it was used to create a blockchain file for distribution through torrent. I don't think anyone has done that for a long time. But maybe it has other users.

Currently, the functional test feature_loadblock.py uses it to generate a serialized blockchain (bootstrap.dat), which is then loaded via `-loadblock`:
https://github.com/bitcoin/bitcoin/blob/5a8d56680b615a3eaa4496ae636db8f65e719284/test/functional/feature_loadblock.py#L63-L72

I agree though that having more detailled tests would probably be nice.

**Comment by laanwj** [comment]
Code review ACK 254a63e097def1bf7e157c72ea9e4fff1eeb7a28

**Pull request merged**
