### PR TITLE
improve security

### PR DESCRIPTION
**Pull request by fingera**
some critical data does not clean in memory

### CODE REVIEW

**Comment by fingera** [comment]
Does this commit make sense? 
Also found that there are several similar.

**Comment by fingera** [comment]
All *ssl libraries does cleanse. some data is in stack does't cleanup. maybe bitcoin code used in wallet app now. The most important thing is, can I do something?  
happy weekend

**Comment by promag** [comment]
@fingera FYI #10102.

**Comment by fingera** [comment]
@promag thks,
Is this commit should close?
CHMAC_SHA512 is leak critical data in stack.
'special secret allocator' hook malloc and free is not useful.
Page out is only threat?

**Pull request closed without merging**
