### PR TITLE
convert C-style (void) parameter lists to C++ style ()

### PR DESCRIPTION
**Pull request by arvidn**
In C, an empty parameter list, `()`, means the function takes any arguments, and `(void)` means the function does not take any parameters.
In C++, an empty parameter list means the function does not take any parameters.

So, C++ still supports `(void)` parameter lists with the same semantics, why change to `()`?

1. removing the redundant `void` improves signal-to-noise ratio of the code
2. using `(void)` exposes a rare inconsistency in that a template taking a template `(T)` parameter list, cannot be instantiated with `T=void`

### CODE REVIEW

**Comment by donaloconnor** [comment]
utACK https://github.com/bitcoin/bitcoin/commit/3ccfa34b32b7ed9d7bef05baa36827b4b262197e

**Comment by promag** [comment]
Interesting. utACK 3ccfa34.

**Comment by practicalswift** [comment]
utACK 3ccfa34b32b7ed9d7bef05baa36827b4b262197e

Nice cleanup!

**Comment by MarcoFalke** [comment]
I compiled with clang and the code change doesn't change a single bit of the `bitcoind` binary. (Didn't check `test_bitcoin` and `bitcoin-qt`)

**Comment by ken2812221** [comment]
utACK 3ccfa34

**Pull request merged**
