### PR TITLE
build: update retry to current version

### PR DESCRIPTION
**Pull request by RandyMcMillan**
This commit eliminates spelling and white space
errors that are flagged in the linting process

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Please specify the commit hash of the "current version", see e.g. fa0aac0f43a108a88b03a346464ecda4ae2cf630

**Comment by MarcoFalke** [comment]
Also, travis doesn't pass because you introduced trailing whitespace

**Comment by RandyMcMillan** [comment]
Please bare with while I get this synced up.
https://github.com/kadwanev/retry/pull/16#issuecomment-547178293

Eventually a member should consider adding this as a sub tree.

REF: https://github.com/bitcoin/bitcoin/pull/17214

**Comment by RandyMcMillan** [comment]
Passes lining:
https://travis-ci.org/RandyMcMillan/bitcoin/jobs/605244976
https://travis-ci.org/RandyMcMillan/bitcoin/jobs/605244990

**Comment by practicalswift** [comment]
ACK 58d0393bec7680933702b76cd3f1d1e33030ed16

**Pull request merged**
