### PR TITLE
Remove unused import. Remove accidental trailing semicolons.

### PR DESCRIPTION
**Pull request by practicalswift**

### CODE REVIEW

**Comment by jnewbery** [comment]
Again? Wasn't this already done here: #10107 

and here: #9607

Can we limit this kind of PR to one at the beginning of each release cycle?

**Comment by practicalswift** [comment]
@jnewbery Seems like the same issues are being re-introduced again and again:-)

**Comment by jnewbery** [comment]
Seems like it! Can I suggest the following:

- keep one PR open with a title like "WIP: post 0.14.1 python code style nits"
- update it with all the style nits you find during the release cycle
- rebase it as soon as 0.14.1 is branched from master.
- only then ask for review/merge.

Thank you for your efforts to clean up the code. It's appreciated, but let's do it in a way that doesn't create undue work for reviewers and maintainers.

**Comment by MarcoFalke** [comment]
Agree with @jnewbery. This is basically the same as with Wshadow: As long as we can not enforce a specific style, such pull requests tend to harm development on the master branch. I'd suggest to do a "Fix Wshadow" and "Remove trailing semicolons" pull request after each branch off of master. It is totally fine to have style nits sit around in master and clear them up prior to a release.

**Comment by jonasschnelli** [comment]
Sorry, my fault.
Though I don't think its worth to do an extra cleanup PR. Maybe someone can fix it when he touched that file for a better reason.

**Comment by practicalswift** [comment]
A few additional unused imports were introduced during the last few days - removed those, rebased and pushed :-)

**Pull request merged**
