### PR TITLE
Uninstall icon changed from default nsis to bitcoin

### PR DESCRIPTION
**Pull request by RottenCoin**
trivial

### CODE REVIEW

**Comment by hebasto** [comment]
I think icons were distinguished on purpose.

**Comment by MarcoFalke** [comment]
Please include a motivation for this change and screenshots to illustrate it

**Comment by laanwj** [comment]
NACK from me, I think having a distinct icon for uninstalling makes sense.

**Comment by MarcoFalke** [comment]
Closing for now. Can be reopened once the feedback has been addressed

**Pull request closed without merging**
