### PR TITLE
addrman: delete addresses that don't belong to the supported networks

### PR DESCRIPTION
**Pull request by brunoerg**
This PR adds a new flag `-cleanupaddrman`. When initializing a node with this flag, it will delete addresses from addrman (both new and tried tables) that do not belong to the supported networks (e.g. `-onlynet`). Deleting addresses that do not belong to the supported networks can avoid a lot of unnecessary addrman `Select` calls (especially when turning from clearnet + Tor/I2P/CJDNS to Tor/I2P/CJDNS).

1. This flag is not enabled by default, if user intends to go back to the previous network, just do not set it.
2. Addresses from non-supported networks will naturely be replaced in addrman since we only store addresses from networks we support (cleaning up them on init is a way to avoid spending resources on it).
3. Avoiding these addresses in addrman can avoid exceeding the maximum number of tries in `ThreadOpenConnections`.
```cpp
// If we didn't find an appropriate destination after trying 100 addresses fetched from addrman,
// stop this loop, and let the outer loop run again (which sleeps, adds seed nodes, recalculates
// already-connected network ranges, ...) before trying new addrman addresses.
nTries++;
if (nTries > 100)
    break;
```  
4. Specially turning from clearnet + Tor/I2P/CJDNS to Tor/I2P/CJDNS, this feature it will ensure we will relay more addresses from these networks to other peers.

### CODE REVIEW

**Comment by brunoerg** [comment]
cc: @mzumsande

**Comment by naumenkogs** [comment]
Having these records around might be useful too, if you go back to those networks.

Do we have any practical problems with these Select calls? Too much CPU time, orz disk reads, or memory use?

Not only this would motivate this code change and review use better, but also it would help us understand under which circumstances a node operator might actually want to do this....And then maybe the right thing would be to trigger this cleaning automatically rather than thinking a user will trigger it.

Or, what i think is even more likely, we may rather change Addrman architecture to facilitate this better in the first place.

**Comment by 1440000bytes** [comment]
> This PR adds a new flag -cleanupaddrman. When initializing a node with this flag, it will delete addresses from addrman (both new and tried tables) that do not belong to the supported networks (e.g. -onlynet). 

I don't think this is a good idea

> This flag is not enabled by default.

Concept ACK because it's not enabled by default and could be useful for testing.

**Comment by brunoerg** [comment]
@naumenkogs and @amitiuttarwar I just updated the description with more infos. Thanks!

--------

> Or, what i think is even more likely, we may rather change Addrman architecture to facilitate this better in the first place.

@naumenkogs: What do you mean by changing addrman architecture?

**Comment by mzumsande** [comment]
> Deleting addresses that do not belong to the supported networks can avoid a lot of unnecessary addrman `Select` calls

It would be good to have some intution for how big this effect is. For example, if you have an addrman with mostly IPv4/IPv6 addresses and a few onion ones then restart with `-onlynet=onion`, will it take noticeably longer to find peers? The worst case scenario would be if you had just a single onion address, but that doesn't seem realistic, so I'd be more interested about the case where you have between 5% and 10% onion addresses.

**Comment by vasild** [comment]
What about setting `preferred_net`

https://github.com/bitcoin/bitcoin/blob/7143d4388407ab3d12005e55a02d5e8f334e4dc9/src/net.cpp#L2682

if `-onlynet` is used? Surely it is a waste to select an unreachable address:

https://github.com/bitcoin/bitcoin/blob/7143d4388407ab3d12005e55a02d5e8f334e4dc9/src/net.cpp#L2695-L2697

That would skew the outcome though. If addrman has 60% IPv4, 25% Tor and 15% I2P addresses right now it is more likely to select Tor over I2P. If we run with `-onlynet=tor -onlynet=i2p` and set `preferred_net` to Tor or I2P randomly (50% chance) to avoid the IPv4 addresses, then it will not be more likely to pick Tor. It would be relatively easy to extend that parameter to `preferred_nets` -- meaning to return an address from one of the given networks.

> 4. Specially turning from clearnet + Tor/I2P/CJDNS to Tor/I2P/CJDNS, this feature it will ensure we will relay more addresses from these networks to other peers.

clearnet addresses might be useful to Tor peers if they are multi-homed. I think it is good that we send any address type to any peer. Instead of e.g. only Tor addresses to Tor peers.

**Comment by brunoerg** [comment]
> What about setting preferred_net

Yes, I previously discussed this options with @mzumsande. It might be an alternative, sure.

> That would skew the outcome though. If addrman has 60% IPv4, 25% Tor and 15% I2P addresses right now it is more likely to select Tor over I2P. If we run with -onlynet=tor -onlynet=i2p and set preferred_net to Tor or I2P randomly (50% chance) to avoid the IPv4 addresses, then it will not be more likely to pick Tor. It would be relatively easy to extend that parameter to preferred_nets -- meaning to return an address from one of the given networks.

Sure, we can extend addrman's `Select` to deal with more than one network and return an address from one of the given networks. 

> clearnet addresses might be useful to Tor peers if they are multi-homed. I think it is good that we send any address type to any peer. Instead of e.g. only Tor addresses to Tor peers.

Sure, this is something we can dicuss because not ensuring we're sending Tor addresses to Tor peers is also not positive. But I agree on relaying clearnet addresses for those nodes. I do not have this data, but I suppose that most Tor peers also run on clearnet?

**Comment by vasild** [comment]
> not ensuring we're sending Tor addresses to Tor peers is also not positive

Right, if we sent solely IPv4 addresses to a Tor peer while we have Tor addresses, that seems like something that can be improved.

**Comment by brunoerg** [comment]
I'll close this PR to work on a "less aggressive" approach (extending `Select` to support multiple networks). I will provide my benchmarks on that new PR.

Thanks, @vasild @mzumsande @naumenkogs @amitiuttarwar.

**Pull request closed without merging**
