### PR TITLE
test: Add RegTestingSetup to setup_common

### PR DESCRIPTION
**Pull request by maflcko**
The default chain for `TestingSetup` is the main chain. However, any test that wants to mine blocks on demand needs to switch to regtest. This is done manually and in-line right now.

Fix that by creating an explicit `RegTestingSetup` and use it where appropriate.

Also, add a move-only commit to move `ComputeFilter` into the newly created unit test library.

Both commits are part of #15845, but split up because they are useful on their own.

### CODE REVIEW

**Comment by practicalswift** [comment]
Concept ACK

**Comment by MarcoFalke** [comment]
Rebased

**Comment by MarcoFalke** [comment]
Anything left to do here?

**Comment by practicalswift** [comment]
ACK fa0a731d007a8e76d2740a2e6ead2289de77e475 -- diff looks correct

**Pull request merged**
