### PR TITLE
bugfix: rest: avoid segfault for invalid URI

### PR DESCRIPTION
**Pull request by pablomartin4btc**
Minimal fix to get it promptly into 25.0 release (suggested by  [stickies-v](https://github.com/bitcoin/bitcoin/pull/27253#pullrequestreview-1385130381) and supported by [vasild](https://github.com/bitcoin/bitcoin/pull/27253#pullrequestreview-1385842606)  )

Please check #27253 for reviewers comments and acks regarding this PR and read the commit comment message body for more details about the fix.

### CODE REVIEW

**Review by stickies-v — APPROVED** [review]
ACK 827b14c33f39131ede35ddecde75cc052d977ec5

**Review by theStack — CHANGES_REQUESTED** [review]
It's still possible to provoke a segfault via the `/rest/mempool` endpoint, which also uses `GetQueryParameter()` (tested on a `bitcoind -signet -rest` instance):

```
$ curl localhost:38332/rest/mempool/contents.json?%
curl: (52) Empty reply from server

bitcoind output:
libc++abi: terminating with uncaught exception of type std::runtime_error: URI parsing failed, it likely contained RFC 3986 invalid characters
Abort trap (core dumped)
```

Should be easy to fix by catching ` std::runtime_error` also at the proper places within `rest_mempool`.

**Comment by pablomartin4btc** [comment]
> It's still possible to provoke a segfault via the `/rest/mempool` endpoint, which also uses `GetQueryParameter()` (tested on a `bitcoind -signet -rest` instance):
> 

Thanks @theStack. I'll fix it asap.

**Review by vasild — APPROVED** [review]
ACK 827b14c33f39131ede35ddecde75cc052d977ec5

**Comment by pablomartin4btc** [comment]
Updated changes:
- Fixed issue detected by @theStack on the `rest/mempool` endpoint that was also calling `GetQueryParameter()`.

**Review by stickies-v — APPROVED** [review]
re-ACK 11422cc

**Review by theStack — COMMENTED** [review]
post-merge ACK 11422cc5720c8d73a87600de8fe8abb156db80dc

**Pull request merged**
