### PR TITLE
Fix masking of irrelevant bits in address groups.

### PR DESCRIPTION
**Pull request by morcos**
If I'm reading this right, I believe the intent is to keep the high order nBits and mask away the others with 1's.  But before this fix it was keeping the high order (8 - nBits).   I don't think there was any effect, because the only time this was used was in the case of he.net /36 IPv6 groups so nBits was 4.

### CODE REVIEW

**Comment by sipa** [comment]
Nice catch. Changing the | into an & seems simpler, though.

**Comment by dcousens** [comment]
Agreed,  the `&` would be much clearer here and is more typical for a masking operation any way.

**Comment by morcos** [comment]
I thought about `&` but I wasn't confident it was ok to change the previous behavior.
I also couldn't see how to make it as short?
`vchRet.push_back(GetByte(15 - nStartByte) & (((1 << nBits) - 1) << (8 - nBits)));`
or 
`vchRet.push_back(GetByte(15 - nStartByte) & ~((1 << (8-nBits)) - 1));`

**Comment by sipa** [comment]
Good point, we shouldn't change the existing behaviour.

ACK

**Comment by jonasschnelli** [comment]
utACK.
Would be nice if there would be test coverage in `netbase_tests.cpp` for this.

**Comment by laanwj** [comment]
utACK.
There was a similar error in the netmask parsing.
Agree @jonasschnelli that unit tests for this function would be nice.

**Comment by morcos** [comment]
Ok writing unit test.  I have a question about `IsLocal()`, since those addresses are also `!IsRoutable()` they will be lumped in the `NET_UNROUTABLE` group instead of having their own group.  The check for `IsLocal()` on line 932 is meaningless.  Is that expected?  Changing that would obviously change existing behavior.

**Comment by laanwj** [comment]
Yes, that check seems to be redundant. But let's leave removing it for another pull.

**Pull request merged**
