### PR TITLE
Update Makefile backup URL

### PR DESCRIPTION
**Pull request by btcdrak**
Please tag with [backport] for `0.12`, `0.11` & `0.10`

### CODE REVIEW

**Comment by MarcoFalke** [comment]
@btcdrak Could you close the other 2 pulls and ask this one to get tagged with [backport]?

Also, travis issue with https?

```
Fetching qrencode...

ERROR: no certificate subject alternative name matches

	requested host name `fukuchi.org'.

To connect to fukuchi.org insecurely, use `--no-check-certificate'.

ERROR: no certificate subject alternative name matches

	requested host name `dev.bitcoincore.org'.

To connect to dev.bitcoincore.org insecurely, use `--no-check-certificate'.

make: *** [/home/travis/build/bitcoin/bitcoin/depends/sources/download-stamps/.stamp_fetched-qrencode-qrencode-3.4.4.tar.bz2.hash] Error 5

make: Leaving directory `/home/travis/build/bitcoin/bitcoin/depends'

The command "make $MAKEJOBS -C depends HOST=$HOST $DEP_OPTS" failed and exited with 2 during .

**Comment by luke-jr** [comment]
Can we also get a redirect setup so this doesn't break? :/

**Comment by btcdrak** [comment]
Redirect setup @luke-jr

**Comment by laanwj** [comment]
Can confirm the redirect is working. Thanks @btcdrak.

(we still need a change like this, but we can think about it some time longer where we want the fallback files to be hosted)

**Comment by laanwj** [comment]
Keeping this as-is. The level of indirection afforded by the redirect is useful, even if we move the files somewhere else.

**Pull request closed without merging**
