### PR TITLE
Remove my key from trusted-keys

### PR DESCRIPTION
**Pull request by sipa**

### CODE REVIEW

**Comment by laanwj** [comment]
> Should the contrib/verify-commits/trusted-git-root be updated as well?

Let's see if the checks still pass.

**Review by kristapsk — APPROVED** [review]
ACK 8cbeab4d90437765d1e63b95ede81e4d5e7c975f

**Review by ghost — APPROVED** [review]
ACK https://github.com/bitcoin/bitcoin/pull/25568/commits/8cbeab4d90437765d1e63b95ede81e4d5e7c975f

Verified the fingerprint from https://bitcoincore.org/en/contact/

Thank you for being a bitcoin core maintainer since May 2011. I have learn a lot of things reading your posts and will keep learning as you will still be active as a contributor.

An OP_RETURN tx for memories: https://mempool.space/tx/830e6cb9ae8a35efa23c1053db942db8abe7d3f362f6173638860ee7849507ae

**Comment by b3h3rkz** [comment]
Thank you @sipa!

Beautiful OP_RETURN @1440000bytes 💯

**Comment by junderw** [comment]
ACK 8cbeab4d90437765d1e63b95ede81e4d5e7c975f

Thanks for everything @sipa and good luck on your future endeavors.

**Review by Zero-1729 — APPROVED** [review]
ACK 8cbeab4d90437765d1e63b95ede81e4d5e7c975f

Verified fingerprint matches the key in my keyring.

Thank you @sipa for all your work on core, and invaluable responses on bitcoin.stackexchange. 

Best of wishes on your next chapter!

**Pull request merged**
