### PR TITLE
GUI: Replace send-to-self with dual send+receive entries

### PR DESCRIPTION
**Pull request by luke-jr**
Makes the GUI transaction list more like the RPC, and IMO clearer in general.

As a side effect, this also fixes the GUI entries when a transaction is a net profit to us, but some inputs were also from us.

### CODE REVIEW

**Comment by luke-jr** [comment]
Apparently tests need updating. Concept ACK/NACK?

**Comment by promag** [comment]
Before:
screenshot 2019-01-06 at 18 06 22

After:
screenshot 2019-01-06 at 18 06 41

In #12578 the "Sent to" row would only have 0.1 and the fee would be in a separate row.

**Comment by Empact** [comment]
Concept ACK - seems like a nice simplification, and IMO the table is more clear

**Comment by hebasto** [comment]
Does this approach work for special transactions (e.g., CoinJoin, Pay-to-Endpoint etc)?

**Comment by luke-jr** [comment]
> Does this approach work for special transactions (e.g., CoinJoin, Pay-to-Endpoint etc)?

It can't. If you have a tx from A & B to C & D, there's no logical way to know the correct logical transaction(s) that comprise it, without some kind of metadata.

**Comment by luke-jr** [comment]
(It might display it nicer, though, as a single "net change" entry)

**Comment by kristapsk** [comment]
Haven't tested, but in the screenshot above "Received with" is before "Sent to". Shouldn't it be other way around?

**Comment by promag** [comment]
@kristapsk yap, it makes more sense if you consider the order important.

**Comment by luke-jr** [comment]
Tests and sorting fixed. Ready for review.

**Comment by jonasschnelli** [comment]
Concept ACK
I guess this is much more understandable.

**Comment by luke-jr** [comment]
Rebased

**Comment by jonasschnelli** [comment]
Re-concept ACK.
Can we have more eyes/reviews on that PR?
@promag, @hebasto?

**Comment by jonasschnelli** [comment]
Maybe also a QT test that produces a variate of transaction types including CoinJoins with an optional to manually verify the transaction table (or a produced screenshot) would be great.

**Review by hebasto — COMMENTED** [review]
Tested 14bb8db698d406e59c173f428abbc8d1ea449fed on Linux Mint 19.3 (x86_64):

- one "recipient"
  - master
Screenshot from 2020-06-04 15-27-37
  - this PR
Screenshot from 2020-06-04 15-28-08
- two "recipients"
  - master
Screenshot from 2020-06-04 15-34-50
  - this PR
Screenshot from 2020-06-04 15-32-51

---

1. I'd prefer to keep the "Payment to yourself" type as descriptive enough.

2. Could a send-to-self tx has only two records: combined debit and combined credit?

**Comment by luke-jr** [comment]
> I'd prefer to keep the "Payment to yourself" type as descriptive enough.

How would that even work? Why?

> Could a send-to-self tx has only two records: combined debit and combined credit?

That breaks labels and defeats the point of having multiple recipients. If you want that as a user, you can just use one recipient?

**Comment by hebasto** [comment]
@luke-jr 
> > I'd prefer to keep the "Payment to yourself" type as descriptive enough.
> 
> How would that even work? Why?

On master, one could easily spot send-to-self txs in the tx list, and use sorting in "Type" column. I believe it is convenient. Without "Payment to yourself" type such UX is lost.

---

> > Could a send-to-self tx has only two records: combined debit and combined credit?
> 
> That breaks labels...

Agree.

> ... and defeats the point of having multiple recipients. If you want that as a user, you can just use one recipient?

It is up to a user how many txouts one wants to create in a send-to-self tx, no?

**Comment by luke-jr** [comment]
>On master, one could easily spot send-to-self txs in the tx list, and use sorting in "Type" column. I believe it is convenient. Without "Payment to yourself" type such UX is lost.

What is the use case?

>It is up to a user how many txouts one wants to create in a send-to-self tx, no?

But you want to make anything other than 1 (in effect) require multiple transactions...

**Comment by hebasto** [comment]
> > On master, one could easily spot send-to-self txs in the tx list, and use sorting in "Type" column. I believe it is convenient. Without "Payment to yourself" type such UX is lost.
> 
> What is the use case?

For example, a user want to review send-to-self txs made some time ago...

**Comment by luke-jr** [comment]
What is the use case for "send-to-self txs"?

The only time I've ever seen actual sends-to-self occur, are also cases in which deviations of behaviour are bad...

**Comment by hebasto** [comment]
> The only time I've ever seen actual sends-to-self occur, are also cases in which deviations of behaviour are bad...

... tend to agree with you.

> What is the use case for "send-to-self txs"?

The scope of this PR is to how to present the _existing_ "send-to-self" txs to a user in the GUI, as I understand it.

The discussions about "should send-to-self txs exist" or "what is the use case for send-to-self txs" deserve their own issues/pulls :)

**Comment by luke-jr** [comment]
This replaces send-to-self. As in, they cease to exist conceptually.

(And they never had any existence beyond conceptually.)

**Comment by luke-jr** [comment]
Rebased. This has quite a few Concept ACKs - how about some code review? :/

**Comment by fanquake** [comment]
> Rebased. This has quite a few Concept ACKs - how about some code review? :/

Lets try and make that happen over in the [GUI repo](https://github.com/bitcoin-core/gui).

**Pull request closed without merging**
