### PR TITLE
Implement BIP 14 : separate protocol version from client version

### PR DESCRIPTION
**Pull request by gavinandresen**
This replaces VERSION with PROTOCOL_VERSION (defined in serialize.h) and CLIENT_VERSION (defined in main.h).

I also define CLIENT_NAME as either "bitcoind" or "bitcoin-qt" in main.h.

The getinfo() RPC command returns CLIENT_VERSION as "version" (same as before) and PROTOCOL_VERSION as "protocolversion" (new).

CLIENT_VERSION is recorded in the wallet.dat as "version".

And PROTOCOL_VERSION is used for all the network serialization stuff.

There is a TODO here related to the CAlert feature, but doing it will require more thought/work. And I've got another change to CAlert (give testnet its own alert keypair) that'll be a good time to change it.

I decided against new command-line arguments / bitcoin.conf options to make it really easy to override the CLIENT_NAME or CLIENT_VERSION reported to peers; those would be easy-to-add-later features.

### CODE REVIEW

**Comment by rebroad** [comment]
NACK  :) It's a great idea when there is only one development team for bitcoin, but in the future I expect to see multiple development teams as part of bitcoin's decentralization, and then there will need to be a more non-linear to nodes communicating their capabilities.

**Comment by luke-jr** [comment]
@rebroad Uh, what are you talking about/doing? This is a change that was made and merged in 2011, and does the opposite of what you seem to be thinking it does...

**Comment by rebroad** [comment]
@luke-jr Yes, I realise this is a very old one hence the smiley, but it seems that with various other bitcoin nodes out there, for example, Unlimited are using Protocol Version >80000, which means that Core will assume it provides services such as compact blocks, SegWit, etc when it does not. I am thinking that the PROTOCOL_VERSION ought not to be relied upon as developers are moving away from it for reasons that need to be better understood. I suspect those reasons are that it doesn't suit multiple development teams as it enforces a level of linearity but not on a "level playing field".

**Comment by luke-jr** [comment]
1. This isn't used for CB nor XThin.
2. SegWit is a consensus layer upgrade, and is therefore not optional for full nodes.
3. There is already (since 2011) a Bitcoin-wide standards process (Bitcoin Improvement Proposals; BIP) for changes to common infrastructure to be coordinated between different development teams.
4. That said, this incrementing p2p protocol version number is probably growing increasingly useless, and it might make sense to redefine it as a pair of 16-bit version number (with the current usage) and make the remaining into additional service bits. (Someone wishing to work on this should start a discussion on the implementation-independent bitcoin-dev mailing list, and write a BIP.)

**Pull request merged**
