### PR TITLE
ci: Bump macOS VM image to the latest version

### PR DESCRIPTION
**Pull request by hebasto**
On Cirrus CI bump macOS VM from Catalina to Big Sur.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
No objection. I guess this is good to merge if green?

**Comment by fanquake** [comment]
> On Cirrus CI bump macOS VM from Catalina to Big Sur.

Why?

**Comment by hebasto** [comment]
> > On Cirrus CI bump macOS VM from Catalina to Big Sur.
> 
> Why?

https://github.com/bitcoin/bitcoin/blob/b8e76479cea448d4e00f698fe39ab3e0228ab22d/.cirrus.yml#L176

**Review by fanquake — APPROVED** [review]
ACK b8e76479cea448d4e00f698fe39ab3e0228ab22d - I'm always going to question bumping things for the sake of it/when there's no reasoning given. In this case, moving from building on macOS 10.x to 11.x shouldn't really lose us any coverage, and may turn up potential macOS quirks a bit earlier.

**Pull request merged**
