### PR TITLE
Fix calculation of number of bound sockets to use

### PR DESCRIPTION
**Pull request by TheBlueMatt**
Pulled this out of #9243 because it is a logically separate change.

### CODE REVIEW

**Comment by sipa** [comment]
utACK 9e1f46821d5bb69e2cbf25738eefa7c6cb99c838

**Comment by laanwj** [comment]
utACK https://github.com/bitcoin/bitcoin/commit/9e1f46821d5bb69e2cbf25738eefa7c6cb99c838

**Comment by paveljanik** [comment]
What is returned by `mapMultiArgs.at("-bind").size()` if `!mapMultiArgs.count("-bind")`? Do we need the condition at all?

**Comment by sipa** [comment]
@paveljanik It would raise an exception. Using `[]` instead would result in adding "-bind" as a key to the map.

**Comment by paveljanik** [comment]
ACK 9e1f468

**Comment by jonasschnelli** [comment]
utACK 9e1f46821d5bb69e2cbf25738eefa7c6cb99c838

**Comment by gmaxwell** [comment]
utACK

**Comment by instagibbs** [comment]
utACK 9e1f46821d5bb69e2cbf25738eefa7c6cb99c838

**Comment by morcos** [comment]
utACK

@laanwj ready for merge

**Pull request merged**
