### PR TITLE
test: Avoid F541 (f-string without any placeholders)

### PR DESCRIPTION
**Pull request by maflcko**
An extra `f` string-prefix is mostly harmless, but could be confusing or hint to a mistake where a format argument was forgotten.

Try to avoid the confusion and mistakes by applying the `F541` linter rule.

### CODE REVIEW

**Review by lucasbalieiro — APPROVED** [review]
Hi @maflcko,
~~**Tested ACK** [531621d5](https://github.com/bitcoin/bitcoin/pull/31417/commits/bd8312fc31af8a7a1c7175b0a48646cf531621d5)~~

**Tested ACK** [bd8312f](https://github.com/bitcoin/bitcoin/pull/31417/commits/bd8312fc31af8a7a1c7175b0a48646cf531621d5)

Thank you for addressing this. I understand the rationale behind the change: preventing potential confusion caused by f-strings without placeholders and mitigating mistakes where format arguments may have been inadvertently omitted.

While this is indeed a minor and harmless modification, I tested the changes by rebuilding the source and running the modified test suite. Everything functioned as expected.

<details> <summary>For reference, here is my testing environment and test results:</summary>

```bash
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.5 LTS
Release:	22.04
Codename:	jammy

python3 --version
Python 3.10.12
```

Below is a screenshot of the test output for verification:
image

</details>
To further justify this change and provide reference material for future contributors, I'd like to cite the following:

1. [Ruff rule F541 documentation](https://docs.astral.sh/ruff/rules/f-string-missing-placeholders/):  
   > An f-string without placeholders can be confusing for readers, who may expect such a placeholder to be present. An f-string without any placeholders could also indicate that the author forgot to add a placeholder expression.

2. [PEP 498](https://peps.python.org/pep-0498/#specification):  
   > The parts of the f-string outside of braces are literal strings.

This change aligns well with best practices and coding standards, ensuring improved readability and reducing potential errors in the future.

Thanks again for your contribution!

**Comment by lucasbalieiro** [comment]
**Tested ACK** [fae7639](https://github.com/bitcoin/bitcoin/pull/31417/commits/fae76393bdbf867176e65447799d6ee3d3567b18)] 

Hi @maflcko,  

Apologies for the confusion in my earlier [[comment](https://github.com/bitcoin/bitcoin/pull/31417#pullrequestreview-2480383560)](https://github.com/bitcoin/bitcoin/pull/31417#pullrequestreview-2480383560). I mistakenly referenced only the last eight characters of the commit hash instead of the first seven, which may have caused some misunderstanding.  

To clarify, I have re-run all the tests, thoroughly verified the correct commit hash, and can confirm that everything works as expected:  
image  

Thank you for your understanding, and I apologize for any inconvenience caused.

**Review by danielabrozzoni — APPROVED** [review]
ACK fae76393bdbf867176e65447799d6ee3d3567b18

**Review by tdb3 — APPROVED** [review]
Code review ACK fae76393bdbf867176e65447799d6ee3d3567b18

The style guidelines prefer `f`-string over `.format()`, but it's a preference and the minimal change in the PR seems reasonable when compared to something decomposed like the following:

```diff
diff --git a/contrib/tracing/log_raw_p2p_msgs.py b/contrib/tracing/log_raw_p2p_msgs.py
index 9cda7fd08d4..864847983a9 100755
--- a/contrib/tracing/log_raw_p2p_msgs.py
+++ b/contrib/tracing/log_raw_p2p_msgs.py
@@ -117,19 +117,13 @@ int trace_outbound_message(struct pt_regs *ctx) {
 
 
 def print_message(event, inbound):
-    print("{} {} msg '{}' from peer {} ({}, {}) with {} bytes: {}".format(
-
-              "Warning: incomplete message (only {} out of {} bytes)!".format(
-                  len(event.msg), event.msg_size) if len(event.msg) < event.msg_size else "",
-              "inbound" if inbound else "outbound",
-              event.msg_type.decode("utf-8"),
-              event.peer_id,
-              event.peer_conn_type.decode("utf-8"),
-              event.peer_addr.decode("utf-8"),
-              event.msg_size,
-              bytes(event.msg[:event.msg_size]).hex(),
-          )
-          )
+    warning = "Warning: incomplete message (only {len(event.msg)} out of {event.msg_size} bytes)!" if len(event.msg) < event.msg_size else ""
+    direction = "inbound" if inbound else "outbound"
+    msg_type = event.msg_type.decode("utf-8")
+    conn_type = event.peer_conn_type.decode("utf-8")
+    peer_addr = event.peer_addr.decode("utf-8")
+    num_bytes = bytes(event.msg[:event.msg_size]).hex()
+    print(f"{warning} {direction} msg '{msg_type}' from peer {event.peer_id} ({conn_type}, {peer_addr}) with {event.msg_size} bytes: {num_bytes}")
 
 
 def main(pid):
```

> Use f'{x}' for string formatting in preference to '{}'.format(x) or '%s' % x.
https://github.com/bitcoin/bitcoin/blob/master/test/functional/README.md#style-guidelines

**Pull request merged**
