### PR TITLE
[wallet] Clarify getbalance help string to explain interaction with bumpfee

### PR DESCRIPTION
**Pull request by ryanofsky**

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
Do we need to describe the implementation details in the docs? I'd prefer something shorter that just nodes "if there are conflicting spends of wallet outputs, these may be counted twice, resulting in an incorrect balance".

Related issue: #8183.

**Comment by ryanofsky** [comment]
I don't see these as implementation details, I just think this just a basic description of what the two balances represent. I could remove the extra help text and text turn it into a code comment, if there is a reason to thing that more vague documentation would be better here, but I'd be curious to know advantages you think this could have.

**Comment by jonasschnelli** [comment]
I had the same impressions like @TheBlueMatt. Is very technical and deeper connects the implementation with the documentation, means, if we change the implementation, we may need to update the docs (or remove which would be a step backwards then).

**Comment by ryanofsky** [comment]
Ok, I moved details from the RPC help string to a code comment in 5a00659b58800ce52b652a31d551a984926c46de. I also added a broader warning about the account parameter since Matt and Alex pointed out that only describing one potential problem might imply that there are no other problems we know about (which apparently there are in #8183, #3816, #7597, #6042).

**Comment by TheBlueMatt** [comment]
ACK

**Comment by MarcoFalke** [comment]
ACK 5a00659b58800ce52b652a31d551a984926c46de.

Also assigning 0.14, as this fixes documentation.

**Pull request merged**
