### PR TITLE
Bugfix: GUI: Remove broken ability to edit the address field in the sending address book

### PR DESCRIPTION
**Pull request by luke-jr**
Apparently in the sending address book, it is possible to edit the address field of an address/label row.

Doing so, however, has 2 pretty big bugs:

**Bug 1** (since 0.17, #10244): Instead of moving the label, the new address's label was set to the new address itself, and the actual label was lost completely.

**Bug 2** (effectively since 0.19, #13756): All metadata associated with the old address (prior to edit) is deleted, except for label and purpose. Probably some should remain with the old address (eg, whether the associated key was used to spend already), and others should be moved to the new address (no existing cases, just hypothetically). I doubt we should ever just outright delete it.

Edit: **Bug 3** (unconfirmed, debatable): Editing both the label and address in the label-editing dialog would still delete the label for the old address.

**Proposed resolution**: Remove the ability to edit the address field. It doesn't really make sense.

### CODE REVIEW

**Comment by instagibbs** [comment]
can you give a "tutorial" on how to change address on master? I can't seem to figure this out.

**Comment by MarcoFalke** [comment]
@instagibbs : Click "sending addresses" and then right click on an address and then "edit".


Screenshot from 2020-02-26 00-28-43

**Comment by jonasschnelli** [comment]
The edit function is already somehow hidden. IMO Having a "address books" without an edit function seems quite limiting. @luke-jr: what would it mean to fix bug1/2?

Would deprecating the address book (then removing it at some point) make sense?

**Comment by luke-jr** [comment]
How would you edit labels then?

**Comment by luke-jr** [comment]
@MarcoFalke Actually, this was only addressing inline editing, so the dialog is another place to disable the editing... Fixed

**Comment by luke-jr** [comment]
@instagibbs I suspect "how to inline edit" is platform-dependent, but on my KDE-based system, double-clicking on the field I intend to edit does it.

**Comment by emilengler** [comment]
NACK sorry.
I agree with @jonasschnelli, instead of removing it I would improve it

**Comment by luke-jr** [comment]
@emilengler What is the use case? Clearly nobody uses it since it doesn't work. @jonasschnelli seems confused about the PR, and isn't NACKing it...

**Comment by emilengler** [comment]
@luke-jr Do you really know that nobody is using it?
Also I was agreeing on the reason not on his choice though

**Comment by luke-jr** [comment]
It _doesn't work at all_... And hasn't for a long time now. How could anyone be using it?

**Comment by emilengler** [comment]
> It doesn't work at all... 

That's why I said improve it instead of remove it

> How could anyone be using it?

You're right on that point though but maybe some users are frustrated because it didn't worked

**Comment by laanwj** [comment]
FWIW I tend to edit labels by right clicking on a transaction then doing 'edit label'. Haven't used the address book for ages.

**Comment by luke-jr** [comment]
This has no impact whatsoever on the ability to edit labels anywhere.

This is about when the user attempts to edit the *address*.

**Review by hebasto — CHANGES_REQUESTED** [review]
Approach ACK 2667478697b044e57d9cb619bbf32cadd86fd295, tested on Linux Mint 19.3.

Some notes:
1) could the last commit "GUI: Disallow editing the address in EditAddressDialog with mode=EditSendingAddress" be squashed into the first one "Bugfix: GUI: Disable inline editing of sending addresses"

2) the tooltip content is misleading now: "Right click to edit _address_ or label".

**Comment by luke-jr** [comment]
Squashed & fixed

**Review by hebasto — APPROVED** [review]
ACK 0a44e08992f5c2f4a5077071c13599da99559905

**Comment by fanquake** [comment]
If this is still relevant, it should be rebased and then re-opened in the [gui repo](https://github.com/bitcoin-core/gui/pulls).

**Comment by fanquake** [comment]
Closing per https://github.com/bitcoin/bitcoin/pull/18194#issuecomment-807994862.

**Pull request closed without merging**
