### PR TITLE
fs: consistently use fsbridge:: for ifstream / ofstream

### PR DESCRIPTION
**Pull request by fanquake**
Two of these changes are part of #20744, but are ok to do now, and reduce the diff that will eventually need to be reviewed in that PR. See commit messages for details.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Please clarify if this changes behavior in any way or if this is a refactor.

**Comment by hebasto** [comment]
https://cirrus-ci.com/task/6421734977961984:
```
bench/bench.cpp: In function ‘void {anonymous}::GenerateTemplateResults(const std::vector<ankerl::nanobench::Result>&, const string&, const char*)’:
bench/bench.cpp:30:37: error: use of deleted function ‘fs::path::path(std::string)’
   30 |     fsbridge::ofstream fout{filename};
      |                                     ^
In file included from ./test/util/setup_common.h:9,
                 from bench/bench.cpp:7:
./fs.h:50:5: note: declared here
   50 |     path(std::string) = delete;
      |     ^~~~
make[2]: *** [Makefile:13538: bench/bench_bitcoin-bench.o] Error 1
```

**Comment by fanquake** [comment]
Closing as this is going in as part of #20744.

**Comment by MarcoFalke** [comment]
Not sure why this was closed?

It looks like the CI failure hinted at a bug that needs fixup? In all other places where strings from the command line are converted to paths, `PathFromString` is used, but not here in bench.

**Comment by fanquake** [comment]
> Not sure why this was closed?

It's part of #20744.

**Comment by MarcoFalke** [comment]
I think it might be worthwhile to fix the presumed bug in bench before 20744, in which case this should compile and can also be done before 20744?

**Comment by fanquake** [comment]
Ok. I had deleted the branch, but can open a new PR.

**Pull request closed without merging**
