### PR TITLE
Fix for listsinceblock not filtering conflicted transactions

### PR DESCRIPTION
**Pull request by mchrostowski**
Fix for issue #8752 which, if merged, replaces PR #8757 

I prepped functional/listsinceblock.py for additional tests.
Wrote a test for the above issue.
Made a fix to rpcwallet.cpp:listsinceblock(...).

The fix takes advantage of CMerkleTx::GetDepthInMainChain() returning a negative value for conflicted transactions. The negative value represents the depth of the transaction with which it is conflicted. Taking abs(...) of this lets us use the same logic for filtering un-conflicted transactions to filter the conflicted ones.

### CODE REVIEW

**Comment by RHavar** [comment]
ACK

**Comment by jonasschnelli** [comment]
utACK df09c3aaca3d261a0679a2fcc04da9ee01fb824a

**Comment by jonasschnelli** [comment]
Needs rebase though now.

**Comment by TheBlueMatt** [comment]
@mchrostowski any plans to rebase this?

**Pull request closed without merging**
