### PR TITLE
[Trivial] Update license year range to 2019

### PR DESCRIPTION
**Pull request by cvengler**
Bitcoin Core is going to become 10 so the license year range also needs an update.
2019 is coming very soon so it is the time to update the year range like every year.

Same as #12063

### CODE REVIEW

**Comment by promag** [comment]
See #12063.

BTW, maybe there could be a script to generate a scripted diff?

**Comment by Empact** [comment]
Check out https://github.com/bitcoin/bitcoin/blob/master/contrib/devtools/copyright_header.py

**Comment by emilengler** [comment]
@Empact Should I also update the copyright headers with 2019 and squash the commits then ?

**Comment by fanquake** [comment]
@emilengler just update this to include the same files as #12063. i.e add `configure.ac` & `contrib/debian/copyright`, then squash into a single commit.

**Comment by fanquake** [comment]
utACK ae5594d

**Comment by laanwj** [comment]
utACK ae5594d51b489826f2f2315c92e8df5ee0267efc

**Pull request merged**
