### PR TITLE
[Trivial] Grammar and typo correction (laudaa)

### PR DESCRIPTION
**Pull request by maflcko**
Minor corrections in src\test\* .

This is a squashed version of #9543, which I accidentally closed while trying to squash and force push.

### CODE REVIEW

**Comment by laudaa** [comment]
Sounds good!

**Comment by morcos** [comment]
@MarcoFalke for the record I'm opposed to these kind of PR's 
They just cause unnecessary merge and rebase conflicts for no added value.

**Comment by MarcoFalke** [comment]
@morcos Agree, but note that this pull was already reviewed in #9543.
I'd prefer not to close pull request once they have been reviewed and
ACKed.

I think one solution would be to mention in our contribution
guidelines that minor grammar and spelling mistakes (e.g. AE vs BE or
mostly irrelevant typographic errors in non user facing messages)
should not be fixed.

**Comment by morcos** [comment]
@MarcoFalke ok thanks..  yeah or fixed only when modifying the area already...

**Pull request merged**
