### PR TITLE
Remove `Warning:` from warning message printed for unknown new rules

### PR DESCRIPTION
**Pull request by ghost**
Reason: I noticed that `Warning` is printed 2 times in `-getinfo` while reviewing https://github.com/bitcoin/bitcoin/pull/21832#issuecomment-851004943

Same string is used for GUI, log and stderr. If we need to add `Warning:` in GUI or other place we can always prepend to this string.

CLI: 

```
Warnings: Unknown new rules activated (versionbit 28)

```

GUI: 

image

### CODE REVIEW

**Review by klementtan — APPROVED** [review]
ACK [`db99bab`](https://github.com/bitcoin/bitcoin/pull/22102/commits/db99bab2d8400e269e5c52cb69c88a7de02470aa)

Good catch!

**Comment by laanwj** [comment]
Yes, it is unnecessary to prepend "warning" to a warning.
Code review ACK

Can you please change your git author and committer name in the commits though? It shows as "unknown". Also, please squash the two commits, changing the test and tested code is one atomic change.
```
commit db99bab2d8400e269e5c52cb69c88a7de02470aa (pull/22102/head)
Author: unknown <prayank…>
Date:   Sun May 30 21:39:36 2021 +0530

    change warning message in test
```

**Comment by prayank23** [comment]
> Can you please change your git author and committer name in the commits though? It shows as "unknown". Also, please squash the two commits, changing the test and tested code is one atomic change.

@laanwj Done ✔️

**Comment by MarcoFalke** [comment]
review ACK 6d7e46ce23217da53ff52f535879c393c02fa2b2

**Pull request merged**
