### PR TITLE
util: Fix GUIX build with syscall sandbox

### PR DESCRIPTION
**Pull request by laanwj**
Looks like we've broke the GUIX build in #20487. This attempts to fix it:

- Define `__NR_statx` `__NR_getrandom` `__NR_membarrier` as some kernel headers lack them, and it's important to have the same profile independent on what kernel is used for building.
- Define `SECCOMP_RET_KILL_PROCESS` as it isn't defined in the headers.

### CODE REVIEW

**Comment by laanwj** [comment]
Thinking of it, I'm not sure this is the right solution. `statx` is not directly used by us, but by libc. What if the resulting binary is run against a more recent version of libc, it will use the system call but not be allowed to, so fail?

Might be better to do
```
#ifndef __NR_statx
#define __NR_statx 332
#endif
```
…instead

**Review by practicalswift — APPROVED** [review]
cr ACK 1685d1221e7e605ff073df94e223420691afa079

This might be helpful for fellow reviewers:

```
$ grep -E '(statx|getrandom|membarrier)$' linux/arch/x86/entry/syscalls/syscall_64.tbl
318     common  getrandom               sys_getrandom
324     common  membarrier              sys_membarrier
332     common  statx                   sys_statx
$ grep SECCOMP_RET_KILL_PROCESS linux/include/uapi/linux/seccomp.h
#define SECCOMP_RET_KILL_PROCESS 0x80000000U /* kill the process */

```

**Comment by MarcoFalke** [comment]
Can remove this line now?

https://github.com/bitcoin/bitcoin/blob/1685d1221e7e605ff073df94e223420691afa079/src/util/syscall_sandbox.cpp#L179

**Comment by practicalswift** [comment]
@MarcoFalke Yes, I think these two no longer need to be conditional:

```c++
#if defined(__NR_getrandom)
    {__NR_getrandom, "getrandom"},
#endif // defined(__NR_getrandom)
…
#if defined(__NR_membarrier)
    {__NR_membarrier, "membarrier"},
#endif // defined(__NR_membarrier)
```

**Comment by laanwj** [comment]
> Can remove this line now?

I'm still not decided what I want to do with that table, but i i's supposed to be more or less platform-independent. I left it like this for platforms that *really* don't have the getrandom call.

**Comment by laanwj** [comment]
Anyhow, removed them and force-pushed. I agree it's also somewhat confusing and they can always be added again.

**Comment by practicalswift** [comment]
cr ACK 2d0279987ef04edda5f61c171768b9527cc936cc

Thanks for quickly resolving this!

**Comment by practicalswift** [comment]
FWIW this is how [`minijail`](https://google.github.io/minijail/) (a sandboxing and containment tool used in Chrome OS and Android) handles this:

```
/* Ideally minijail is compiled against a modern libc, which has modern copies
 * of Linux uapi for ioctls, and unistd.h for syscalls. However, sometimes this
 * isn't possible - such as when building with the Android host toolchain - so
 * locally define the system calls in use in active seccomp policy files.
 * This UAPI is taken from sanitized bionic headers.
 */

#ifndef __NR_copy_file_range
#ifdef __x86_64__
#define __NR_copy_file_range 326
#elif __i386__
#define __NR_copy_file_range 377
#elif __arm64__
#define __NR_copy_file_range 285
#endif
#endif /* __NR_copy_file_range */
…
```

https://github.com/google/minijail/blob/6aa0392f3a948c09eb8305650f5d3067e94b25af/gen_syscalls-inl.h#L8-L23

**Comment by laanwj** [comment]
Thanks—we could do the same when we support multiple platforms.

**Pull request merged**
