### PR TITLE
qa: Pin shellcheck version

### PR DESCRIPTION
**Pull request by practicalswift**
Pin `shellcheck` version.

### CODE REVIEW

**Comment by promag** [comment]
Can't we lock the installed version instead?

**Comment by practicalswift** [comment]
@promag The `shellcheck` on Travis is pre-installed AFAIK - we don't install it explicitly in our Travis conf. Also since we don't control the version the user has installed pinning wouldn't have prevented the version problem described in https://github.com/bitcoin/bitcoin/pull/14115/commits/908a559f33cf9d774953ce46e159e66fc9bc758d.

**Comment by promag** [comment]
@practicalswift IMO what the use has it not a problem, instead it helps if the user has a newer version so he can update the travis one if necessary.

We could run in a docker container?

**Comment by practicalswift** [comment]
@promag Yes, pinning the version by going the Docker route would be an alternative way to solve. I'll let @laanwj chime in here.

**Comment by laanwj** [comment]
I think it makes sense to allow for some variability in `shellcheck` versions for people that want to run this locally.

**Comment by promag** [comment]
Just to be clear, in travis run the linter in a container with a specific version of shellcheck, locally use the one available in the path?

**Comment by promag** [comment]
@MarcoFalke why? The official supported would be the travis IMO. If the linter fails for the user then he either upgrades/downgrades his version or submit a pull to fix the (most likely) new version.

**Comment by practicalswift** [comment]
@promag The proposed solution allows for some variability in `shellcheck` versions. Could you describe what problems foresee with allowing for such variability?

**Comment by practicalswift** [comment]
@koalaman Thanks for the input! What is the best way to achieve version pinning of `shellcheck` in Travis? Travis pre-installs `shellcheck`.

**Review by klineswing — APPROVED** [review]

**Comment by koalaman** [comment]
@practicalswift  Unfortunately I'm not very familiar with Travis myself. 

Someone contributed a recipe which just downloads a specific release version (which could obviously be improved by verifying the checksum):

```
export scversion="stable" # or "v0.4.7", or "latest"
wget "https://storage.googleapis.com/shellcheck/shellcheck-${scversion}.linux.x86_64.tar.xz"
tar --xz -xvf shellcheck-"${scversion}".linux.x86_64.tar.xz
cp shellcheck-"${scversion}"/shellcheck /usr/bin/
shellcheck --version
```

Specific ShellCheck releases can also be run via Docker, if that helps.

**Comment by promag** [comment]
We already use docker so I guess we could use the one available in bionic?

**Comment by practicalswift** [comment]
Now pinning the `shellcheck` version. Please re-review :-)

**Comment by MarcoFalke** [comment]
ACK, we do the same for the pip packages

**Comment by promag** [comment]
I guess checksum verification is not necessary. Still curious why not docker. utACK a517541 though.

**Comment by practicalswift** [comment]
@promag We don't use Docker for any of the linters. The non-Docker setup is simpler.

**Pull request merged**
