### PR TITLE
Replace RecursiveMutex `cs_addrLocal` with Mutex, and rename it

### PR DESCRIPTION
**Pull request by w0xlt**
This PR is related to #19303 and gets rid of the `RecursiveMutex cs_addrLocal`.

### CODE REVIEW

**Review by shaavan — APPROVED** [review]
ACK 63ca568f484a6b36b9485165c4932938f0602b36

- The new name of cs_addrLocal -> m_addr_local_mutex is an improvement.
- I checked that `m_addr_local_mutex` is being used at two places in the codebase. These instances have been addressed by _Asserting Lock not held_ before locking the mutex. So I think it's safe to convert `m_addr_local_mutex` from **RecursiveMutex** to **Mutex**.

**Review by hebasto — COMMENTED** [review]
Concept ACK.

Adding `AssertLockNotHeld(m_addr_local_mutex)` macros should be combined with adding thread safety annotations `LOCKS_EXCLUDED(m_addr_local_mutex)` in the `src/net.h`. See https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md#threads-and-synchronization

Also, for the safe commit history, "refactor: replace RecursiveMutex m_addr_local_mutex with Mutex" commit should follow "p2p: add assertions for m_addr_local_mutex" one.

**Review by hebasto — APPROVED** [review]
ACK dec787d8ac2e8fb42db87431dd622bf44897bc4e, I have reviewed the code and it looks OK, I agree it can be merged.

**Review by shaavan — APPROVED** [review]
reACK dec787d8ac2e8fb42db87431dd622bf44897bc4e

Changes since my last review:
- Added Thread Safety annotation, `LOCKS_EXCLUDED(m_addr_local_mutex)`, to the `Get/Set AddrLocal()` functions' declaration.
- Rearranged commits so that `m_addr_local_mutex` is converted to **Mutex**, _after_, other conditions are made right for it.

**Pull request merged**
