### PR TITLE
[refactor] Fix the chainparamsbase -> util circular dependency

### PR DESCRIPTION
**Pull request by Empact**
By moving gArgs references out of chainparamsbase.cpp.

Note both chainparams.cpp, bitcoin-cli.cpp, and all callers of
SetupChainParamsBaseOptions include util.h

### CODE REVIEW

**Comment by 251Labs** [comment]
+1 for going after another dependency cycle :) 

Extracting `MakeUnique` seems like a good thing to do.

Does it make sense to refactor the dependency of `util` on `chainparamsbase`? 
https://github.com/bitcoin/bitcoin/blob/9b638c7ce1b93c996b49f02c0bcefb25b6200d8e/src/util.cpp#L8
This relationship seems the crux to the circular dependency to  me. Imo`util` should have as little dependencies as possible.

**Comment by Empact** [comment]
Agree on minimizing `util`, but seems removing `chainparamsbase` would be a bigger job, since `ArgsManager` uses `CBaseChainParams`, and `ArgsManager` is the bulk of `util`.

**Comment by Empact** [comment]
Dropped the third commit and extracted #13690 for easier review. Maybe start with that?

**Comment by Empact** [comment]
Rebased for #13690

**Comment by Empact** [comment]
Ran clang-format

**Comment by Empact** [comment]
Rebased for  #13695

**Comment by sipa** [comment]
I don't think moving the arguments for chain selection to util is the right solution here.

Why does util depend on knowing something about chain parameters anyway? It's supposed to be a bunch of utility functions.

**Comment by MarcoFalke** [comment]
What about moving argsmanager to a separate module?

**Comment by Empact** [comment]
I'll look into that, thanks!

**Comment by Empact** [comment]
A possible follow-up - replacing the string-based handling with an enum class: https://github.com/Empact/bitcoin/tree/chain-enum-class

**Comment by Empact** [comment]
@sipa you're right, that's much cleaner. Closing in favor of #14045

**Pull request closed without merging**
