### PR TITLE
Change Time in debug.log from UTC to local time.

### PR DESCRIPTION
**Pull request by mhchia**

### CODE REVIEW

**Comment by gmaxwell** [comment]
What is the motivation for this? I consider it pretty undesirable, as it makes it much harder to correlate logs from multiple hosts when helping people with problems (e.g. requires asking users for their timezone and them getting it right).

**Comment by j84255801912** [comment]
ok, sorry. I agree with your opinion, I thought that is more

**Comment by j84255801912** [comment]
sorry for the stupidness, I'm not familiar with the github interface.

**Comment by paveljanik** [comment]
@gmaxwell This argument is based on the situation where user has several Bitcoin Core nodes running around the world. There are other situations where user has to "re-count" the time in the bitcoind's `debug.log` file to compare it to the other logs from other deamons/messages/logs from his (only) system.
My personal preference would be to log in local time (as other services on my machines are doing) and have an option (turned off by default) to log in UTC.

**Comment by TheBlueMatt** [comment]
If anything this should be optional, indeed, though I have little preference for the default.

**Comment by gmaxwell** [comment]
Or print both.

**Comment by j84255801912** [comment]
Excuse me, should I reopen this pull request or create another one to print
both or set one of them as default and the other as optional?

2015-02-03 3:10 GMT+08:00 Gregory Maxwell <notifications@github.com>:

**Comment by laanwj** [comment]
I really don't like adding an option for something trivial, debug related as this. We should just pick something that makes sense.

**Comment by j84255801912** [comment]
Then I reopen this pull request to let you guys choose, sorry for the disturbance.

**Comment by paveljanik** [comment]
In this case, both use cases are valid and the user has to decide, so I think the extra added option makes sense.
... or we can add -syslog option, change the default to local time and then users with several bitcoind's around the world can syslog to one place to make it easier to correlate. This is the way how other daemons solve this (but there are exceptions).

**Comment by ianks** [comment]
Using anything but UTC for things like this can cause many, many headaches. If the user _really_ wants non-UTC, it's rather trivial to convert everything in the log to it manually.

**Comment by laanwj** [comment]
@panveljanik people are already using bitcoind with other logging backends. As I learned the hard way when I tried to fiddle with it, that's what `-printtoconsole` is used for. It prints the log messages to stdout, so it is trivial to make the output - per line - end up in a system log. Some init service management systems will even do that by default.

This is another example of something that has been done and forgotten 1000's of times, since the 80's, no need to spend time building, reviewing or testing any additional log-fu in bitcoind. You can do logging, externally, any way you want, bitcoind just has to provide the messages. Which it does.

BTW: I'd think it is  much easier to correlate multiple instances in different locales if times are in UTC, not local time. If you then want to find out what happened at a certain time of the day you'd convert that time into UTC once and look up that timestamp in all the other logs. If all logs are in their local times, that's a lot more involved.

@ianks Agreed.

**Comment by paveljanik** [comment]
I use `-printtoconsole` myself, yes. No need for additional option, right.
To paraphrase your last paragraph:
BTW: I'd think it is much easier to correlate multiple system apps in different log files if times are in local time (as other system apps; logs already do), not UTC. If you then want to find out what happened at a certain time of the day you do not have to convert from UTC at all and look up that timestamp in all the other logs. If the bitcoind log is in UTC, that's a lot more involved.

Two use cases. We make it hard for the other one right now. And we are the only app that is doing so... At least I'm not aware of any other app doing this.

**Comment by laanwj** [comment]
@paveljanik Yes, in the end everything is a compromise. The are valid reasons for logging in local time just as well, no argument there. But for the built-in logging I'd say we stick with UTC. For anything else, use external tools.
(could take the hardline stance that `-logtimestamps` was a bad idea in the first place and we should have left that to external tools, but meh, let's just stop the argument here and work on more productive things)

**Comment by MineForeman** [comment]
Just to add another point of view, I do run multiple servers in different timezones and the 'common practice' when you do that is to set all of your timezones to UTC so you can easily merge you logs if wanted.

As such, this change would have no effect.

**Pull request closed without merging**
