### PR TITLE
[Test Suite] Fix test for null tx input

### PR DESCRIPTION
**Pull request by domob1812**
Update the unittest that is meant to catch a transaction that is invalid because it has a null input.  The old test failed not because of that but because it was considered a coinbase with too large script.  This is already checked with a different test, though.

The new test is _not_ a coinbase since it has two inputs, but one of them is null.  This really checks the corresponding code path in `CheckTransaction`.  If this check is disabled there in `main.cpp`, the old unittest still succeeded.  It does no longer succeed with this patch.

### CODE REVIEW

**Comment by laanwj** [comment]
utACK

**Comment by laanwj** [comment]
From @gmaxwell on IRC: Personally I would have put the 0100 input in the first position, for fear that some coinbase checking code only checks the nullness of the first input.

**Comment by petertodd** [comment]
utACK

I'd test both first and second being the null. :)

**Comment by domob1812** [comment]
Sounds like a reasonable plan! ;)  I'll update the patch accordingly later today.

**Comment by domob1812** [comment]
Pushed the extended patch.

**Comment by petertodd** [comment]
utACK

**Comment by jgarzik** [comment]
ut ACK

**Comment by sipa** [comment]
The new test contains a much more structured transaction only. Is there a reason to delete the previous one?

**Comment by domob1812** [comment]
The previous test didn't do what it was advertised to do - it failed not because of the null txin but because of the coinbase length restriction.  This is already tested by the preceding test, so I don't see much of a point in having two tests for that.  But if you think it should stay, I can leave it in (but "fix" the comment for what it really tests).

**Pull request merged**
