### PR TITLE
Qt/ModalOverlay: Use theme tooltip colours

### PR DESCRIPTION
**Pull request by luke-jr**
This seems to look nice in virtually all colour themes (except Zion Reversed, but frankly my dislike of how it looked with that extended to more than just the overlay...)

### CODE REVIEW

**Comment by fanquake** [comment]
OS X before & after, the background is now a yellowish colour vs the original grey.
modal-grey
modal-yellow

**Comment by laanwj** [comment]
> OS X before & after, the background is now a yellowish colour vs the original grey.

Tooltip-yellow! Like sticking a tooltip over the interface.

Going to test this, as I have a somewhat unconventional theme.

Before:
untitled1

After:
untitled2

Big white blob or not, the original is better-readable.
Also what's up with the corners?

**Comment by luke-jr** [comment]
Uh, the colours used are tooltip-text on tooltip-bg. You have white-on-white tooltips?? :/

I don't know anything about corners... saw something in the stylesheet, but it didn't seem to do anything?

**Comment by MarcoFalke** [comment]
Same problem on default fedora skin. Also, we should make sure gitian builds work fine with it.

**Comment by rebroad** [comment]
I saw the PR for this overlay yet I have yet to see it on my running bitcoin-qt . How do I make this appear please?

**Comment by luke-jr** [comment]
Leave your node (presumably testnet) offline for a few days, then when you start it, prevent it from syncing entirely by stopping it after it fetches headers, then start it again with -connect=0 to prevent it from getting connections.

**Comment by laanwj** [comment]
> Uh, the colours used are tooltip-text on tooltip-bg. You have white-on-white tooltips?? :/

Tooltips are white on grey, just like everything else.
untitled
There's no canary-yellow in my theme at all.

> I don't know anything about corners... saw something in the stylesheet, but it didn't seem to do anything?

Looking at the screenshots they used to be nice and rounded, with the patch they're just square.

**Comment by luke-jr** [comment]
@laanwj @MarcoFalke Please test

**Comment by fanquake** [comment]
OS X 10.12, QT 5.7.0
ui-overlay

**Comment by MarcoFalke** [comment]
Still the same:

**Comment by luke-jr** [comment]
@MarcoFalke Do your tooltips work? Can you investigate why you seem to have white-on-white palette here?

**Comment by fanquake** [comment]
Going to close this for now. Seems there are still issues to solve with the yellow-tooltip colouring. Can revisit when some more research has been done.

**Comment by katesalazar** [comment]
This look sweet in my Plasma Breeze and Plasma Breeze Dark themes. No matter if wallet is opened or not, all 4 combinations are as good with this as in the master tip d67330d112.

It doesn't build on my system right away because of some Qt dependency mismatch I was lazy to investigate, but merge/rebase conflicts to master tip d67330d112 are easy<sup>\[1\]</sup>.

<sub>\[1\]: I actually used master fd9c22ca69 of three days ago which should be similar.</sub>

**Pull request closed without merging**
