### PR TITLE
wallet: fund transaction external input cleanups

### PR DESCRIPTION
**Pull request by instagibbs**
Minor cleanups to https://github.com/bitcoin/bitcoin/pull/17211

### CODE REVIEW

**Comment by achow101** [comment]
ACK 7d56d5a77fc7ee9095deb36b8e05f8969461c533

**Comment by instagibbs** [comment]
@meshcollider thanks, I couldn't figure out how many test issues there were in total. Please tag me in the PR for review

squashed

**Comment by achow101** [comment]
ACK 43568782c23185a0599a6e60d61db4716da1cda1

**Review by meshcollider — COMMENTED** [review]
utACK 43568782c23185a0599a6e60d61db4716da1cda1

**Comment by MarcoFalke** [comment]
Is this "cleanup" a refactoring or a behaviour change?

**Comment by instagibbs** [comment]
Should be non behavior changing.

**Review by benthecarman — APPROVED** [review]
ACK 43568782c23185a0599a6e60d61db4716da1cda1

**Pull request merged**
