### PR TITLE
improve dust spamming prevention algorithm

### PR DESCRIPTION
**Pull request by coblee**
This code helps with reducing dust spam. The original code will make the transaction fee become the minimum fee if any output is less than a cent. This makes it costly to send dust spam, but there's an edge case. The attacker can send a transaction with 1000 outputs of one satoshi each. The transaction size is huge but the fee is only the base fee. This fix will increase the fee by the base fee amount for each output that's less than a cent.

### CODE REVIEW

**Comment by felipelalli** [comment]
It sounds good merging this specific fix at this time, after some attacks.

**Comment by willsteel** [comment]
One only learns from mistakes

**Comment by adv0r** [comment]
@felipelalli +1

**Comment by mb300sd** [comment]
Whatever my opinion is worth... +1.

**Comment by bitcreditscc** [comment]
Consensus has changed. It's back on the table. This could potentially resolve the backlog we have in transactions

**Comment by pentarh** [comment]
Txout should be compared not to CENT, which is very hardcoded value, but to nBaseFee imho. Like this

if (txout.nValue < nBaseFee)

**Comment by ABISprotocol** [comment]
This is certainly not back on the table at all, imho.  There were very good reasons this pull request was closed out in 2012.  I would encourage people to re-read the remarks (including those of @gavinandresen as shown [here](https://github.com/bitcoin/bitcoin/pull/1536#issuecomment-6716066)) and @gmaxwell's.

It's a bad idea to take a nuclear option with respect to fees and reject the opportunity that can be presented from analyzing microgiving potential.  Odd also that people keep referring to this as "dust spam" when they could be reframing the language and the issue... the current "dust problem" (which I would argue should actually be called a "giving opportunity") is an opportunity to re-examine transactions, transforming them into bursts of microgiving.  Do not foreclose on the an opportunity to re-examine and re-envision transactions and thus change the system you are using.

In closing, I would also recommend you see issue #6402 as an example and also some of the more recent comments on #6201 (including one that I've entered).

**Pull request closed without merging**
