### PR TITLE
rpc: Output a descriptor in createmultisig and addmultisigaddress

### PR DESCRIPTION
**Pull request by achow101**
Give a descriptor from `createmultisig` and `addmultisigaddress`.

Extracted from #16528 with `addmultisgaddress` and tests added.

### CODE REVIEW

**Comment by sipa** [comment]
Code review ACK, briefly tested.

Why didn't we think of this earlier?

**Comment by sipa** [comment]
Also add a mention to doc/descriptors.md?

**Comment by achow101** [comment]
Added a mention in descriptors.md

**Comment by Sjors** [comment]
tACK 19a354b11f85a3c6c81ff83bf702bf7a40cf5046

**Review by promag — COMMENTED** [review]
Code review ACK 19a354b11f85a3c6c81ff83bf702bf7a40cf5046.

**Review by meshcollider — COMMENTED** [review]
utACK 19a354b11f85a3c6c81ff83bf702bf7a40cf5046

**Comment by MarcoFalke** [comment]
ACK 19a354b11f85a3c6c81ff83bf702bf7a40cf5046

**Pull request merged**
