### PR TITLE
Rename OP_NOP3 to OP_CHECKSEQUENCEVERIFY

### PR DESCRIPTION
**Pull request by btcdrak**

### CODE REVIEW

**Comment by dcousens** [comment]
utACK 0cbfd0b

**Comment by luke-jr** [comment]
Premature until the softfork is accepted, no?

**Comment by luke-jr** [comment]
(Also, much prefer CHECKMATURITYVERIFY for a name...)

**Comment by laanwj** [comment]
I also think this is too early. Until the softfork goes through this is still effectively a NOP.

**Comment by arowser** [comment]
Can one of the admins verify this patch?

**Comment by laanwj** [comment]
Needs rebase.

**Comment by jl2012** [comment]
are we going to do this in 0.13.0?

**Comment by laanwj** [comment]
I think we should

**Comment by MarcoFalke** [comment]
@btcdrak Needs rebase

**Comment by btcdrak** [comment]
@laanwj This will not cleanly cherry-pick to 0.12, would you like be to create the backport for 0.12 as a separate PR?

**Comment by petertodd** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/7540/commits/18c975c831a3a71b26df43a2617a06840f3aa377

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/7540/commits/18c975c831a3a71b26df43a2617a06840f3aa377

**Comment by MarcoFalke** [comment]
utACK 18c975c

**Comment by laanwj** [comment]
@btcdrak Yes, I think a separate backport PR would make sense in this case, as it's probably easier to  do the replacement another time than try to coax git into cherry-picking this.

**Comment by MarcoFalke** [comment]
Backported via 5c84382. Removing label.

**Pull request merged**
