### PR TITLE
Make GetFetchFlags always request witness objects from witness peers

### PR DESCRIPTION
**Pull request by TheBlueMatt**
This fixes a bug where we might (in exceedingly rare circumstances)
accidentally ban a node for sending us the first (potentially few)
segwit blocks in non-segwit mode.

See https://github.com/bitcoin/bitcoin/pull/8393#discussion_r81563418 for the compact-block-related issue, though there is a similar(ly rare) version in ::INV processing as well.

### CODE REVIEW

**Review by dcousens — APPROVED** [review]
concept ACK,  utACK

**Comment by sdaftuar** [comment]
ACK

**Comment by btcdrak** [comment]
utACK 84a32a8

**Comment by NicolasDorier** [comment]
might be worth droppied the pprev parameter completely?

**Comment by TheBlueMatt** [comment]
This late in 13.1, I wanted to touch as little code as possible. I'd call that a candidate for cleanup in 14.

**Comment by btcdrak** [comment]
@TheBlueMatt is this for backport?

**Comment by TheBlueMatt** [comment]
@btcdrak Yes, #8393 is now rebased on top of this.

**Comment by MarcoFalke** [comment]
I guess this will be backported through #8393 .

**Pull request closed without merging**
