### PR TITLE
build: Fix LTO functionality

### PR DESCRIPTION
**Pull request by hebasto**
The current LTO functionality implementation has multiple issues:
1. Duplicated `-flto` flags when linking.
2. The `secp256k1` subtree code is built without LTO.
3. In `AX_CHECK_LINK_FLAG` macro the wrong `CXXFLAG_WERROR` flag is used instead of the correct `LDFLAG_WERROR` one.

This PR fixes all of them.

Might be verified as follows:
```
$ readelf -S src/secp256k1/src/libsecp256k1_la-secp256k1.o | grep .gnu.lto_ | wc -l
274
```

---

The depends build system has similar issues that will be addressed in a separated PR.

Noticed while porting this functionality to a new CMake-based build system.

### CODE REVIEW

**Comment by fanquake** [comment]
In case anyone is unsure, the --enable-lto option, as-is, does work, no broken binaries etc (and we use (thin) LTO in oss-fuzz).

Changes 1 & 3 here don't affect the compiled binary. The compiler will eat any duplicate -flto flags; the change to the -Werror flag is correct, but also does not affect the compiled binary.

Passing the flags through to libsecp is an improvement, and I'm pretty sure that wasn't done originally, because when the --enable-lto option was implemented, we didn't have a clean way to do it. SECP_CFLAGS didn't exist.

That being said, I'm not sure if this option is something we should actually maintain going forward. It's been a useful convenience for testing, but as LTO has matured, and more configurations/options have become available (thin,auto etc), I'm not sure it makes sense for us to have a usage like this. We could probably revert back to c(xx)flags and friends, for passing options through. 

Extending the current build option to account for all new/different LTO functionality probably doesn't make sense (that isn't being done here, but before we change things further I think this is worth considering).

**Comment by hebasto** [comment]
The other point of this PR is to make the current build system comparable to a new CMake-based one, as there is no reason to pessimize the latter, for example, by not applying LTO for libsecp code, for the sake of compatibility with the master branch.

See: https://github.com/hebasto/bitcoin/pull/52.

**Comment by fanquake** [comment]
> See: https://github.com/hebasto/bitcoin/pull/52.

I think the example usage there:
> cmake -B build -DLTO=ON -DLTO_FLAGS="-flto"

is somewhat helping make my point. Seems odd to have a `LTO=ON` option, but then still have to explicitly pass `-flto` into a non-standard `LTO_FLAGS` variable. Shouldn't that be what `LTO=ON` would do for you? I'm not sure how that is better/clearer than just `cmake -B build CXXFLAGS="-flto"`?

It's also not clear if `LTO_FLAGS` is a catch-all for compile and link flags, i.e if I'm using a link cache, do I pass the link options (i.e `-Wl,-cache_path_lto`) through there too, and then the build system figures out what's a compile flag, and what's a link flag? Is that better than `LDFLAGS="-Wl,-cache_path_lto=/some/cache"`? Will followup in the PR in any case.

**Comment by hebasto** [comment]
FWIW, the https://github.com/bitcoin/bitcoin/pull/29185 makes this PR outdated.

**Comment by fanquake** [comment]
> FWIW, the https://github.com/bitcoin/bitcoin/pull/29185 makes this PR outdated.

Closing this for now, given it looks like we are going ahead with #29185.

**Pull request closed without merging**
