### PR TITLE
Android depends

### PR DESCRIPTION
**Pull request by BlockMechanic**
Includes necessary changes to the depends and patches to enable android Qt builds. based on previous work here :- https://github.com/bitcoin/bitcoin/pull/16916 rebased to master.

### CODE REVIEW

**Comment by fanquake** [comment]
@BlockMechanic can you address my [comments](https://github.com/bitcoin/bitcoin/pull/16916#issuecomment-533937371) from the previous PR. Mainly basing this off the work that is already being done in #16110, rather than duplicating the changes.

**Comment by BlockMechanic** [comment]
These depends deal specifically with building QT for android as is. For the necessary changes to build the QML version, i'll push those later

**Comment by BlockMechanic** [comment]
@fanquake  sorry, i am still getting used to using git and performing actions like fethcing someone else's branch , and pushing changes here is still new to me , hence the mess up i mentioned. I managed to get @icota's branch for https://github.com/bitcoin/bitcoin/pull/16110 but could not get it to cooperate properly on my end so i could push here.

**Comment by laanwj** [comment]
> Mainly basing this off the work that is already being done in #16110, rather than duplicating the changes.

Good point. I think it would be good if the people working on bitcoin core on Android (@greenaddress, @BlockMechanic, @icota), would start working together instead of besides each other. It's not clear to me how the different changes relate to each other. Maybe we need an Android maintainer at some point.

**Comment by icota** [comment]
@laanwj I think the difference is that @BlockMechanic is trying to support 32-bit ARM and x86 as well. Like I commented in https://github.com/bitcoin/bitcoin/pull/16916 I don't personally see much value and don't have the devices to test this. But changes on top of https://github.com/bitcoin/bitcoin/pull/16110 are very welcome.

I'm working on a "packaging" PR (to produce an APK) to complement this. It is all very conceptual at this stage but if everything goes to plan and the PRs come together nicely (UI + reproducible build/package) I'd like to volunteer as the Android maintainer. But let's give it some time.

**Comment by fanquake** [comment]
Yes my point is mainly that, for example, both PRs are bringing in a `arc4random_addrandom` patch for `libevent`, so it'd make sense for this PR be based #16110 (opened first, I prefer the patch naming their as well), rather than them being worked on in parallel.

**Comment by BlockMechanic** [comment]
This is now completed in #16110

**Pull request closed without merging**
