### PR TITLE
RPCWallet: Notate all account stuff as deprecated

### PR DESCRIPTION
**Pull request by luke-jr**

### CODE REVIEW

**Comment by petertodd** [comment]
utACK

**Comment by laanwj** [comment]
ut ACK

**Comment by fanquake** [comment]
utACK

**Comment by jtimon** [comment]
ACK

**Comment by sipa** [comment]
I have an alternative suggestion here, namely to 'degrade' accounts back into labels. That means marking all RPC methods that operate on the concept of an "account balance" as deprecated, but not the ability to list transactions received with a particular label etc.

Pro: address labels already exist in the GUI and we probably want to keep them there, so making the RPC functionality analogous should be easy, and it doesn't have the potential confusion risk that accounts have.
Cons: If we're going to break functionality, maybe it should be broken entirely.

**Comment by jgarzik** [comment]
@sipa That was my suggestion months ago in IRC:  Adding one or more "tags" to each address is still useful.

**Comment by luke-jr** [comment]
@sipa That may not be as simple as you think - GUI labels and accounts overlap *only* for receive transactions. Send transaction labels and send account are entirely unrelated right now. :/

**Comment by laanwj** [comment]
I like sipa's idea. The labels feature is useful, and aiming to expose it *eventually* in both RPC and the GUI would make things symmetrical, which is what many users expect.

On the other hand doing that without confusing current users of accounts even more will be difficult. Hence I like first communicating a complete deprecation of the account system as in this pull.

This at some point introduce a *new* API for labels.

**Comment by laanwj** [comment]
> That means marking all RPC methods that operate on the concept of an "account balance" as deprecated, but not the ability to list transactions received with a particular label etc.

As there would no longer be a concept of 'account address' or 'account balance' the label API could be very minimal, e.g.:

- `getaddressesforlabel` [like getaddressesforaccount]
- `listlabels` [like listaccounts, but would just return a list of labels, without balances]
- `setlabel` (address, label) [like setaccount]

These would stay the same, and accept a label instead of an account:

- `getnewaddress` (label)
- `listtransactions` (label,...)

Others, like `sendfrom` would no longer make sense at all, eg. there is no point in sending from a label.

**Comment by luke-jr** [comment]
Note: BFGMiner needs some equivalent of getaccountaddress.

It would make sense to let sendfrom (or at least sendmany) set a label for a send, to avoid having to make 2 RPC calls for each send.

**Comment by laanwj** [comment]
What would be the point of getaccountaddress without accounts? Why not use `getnewaddress (label)`?

**Comment by luke-jr** [comment]
getnewaddress always creates a new address. In the case of mining, you want to continue to use the same one you were using last time until you find a block. I believe this goes for P2Pool as well.

sendmany-only sounds fine to me.

**Comment by laanwj** [comment]
Couldn't you use `getaddressesforlabel` then, and if no results, get a new address? Alternatively, remember the last-used address internally.

**Comment by luke-jr** [comment]
getaddressesforlabel doesn't tell you if addresses are used or not, does it? At this time, there is no internal storage of any sort... hate to add it for this.

**Comment by laanwj** [comment]
Well, the concept of a 'label address' just doesn't make sense, and also has no GUI equivalent.

Also there is some weird interaction that prevents the last address from being moved from an account, and that interaction has to do with the 'account address'. To make it work like GUI labels (so you can get rid of them), that would have to be changed as well. Easiest would be to just get rid of the confusing feature.

**Comment by luke-jr** [comment]
"Get unused address with label" makes sense - albeit only for mining (since bitcoind won't know if it's used-but-not-broadcast-yet). Maybe "getminingaddress" would be appropriate?

**Pull request merged**
