### PR TITLE
Ignore getheaders prior to passing all checkpoints.

### LINKED ISSUE #6971: Is the InitialBlockDownload() check in 'getheaders' too strict?
I was trying to sync a new node from an almost-synced node, and somehow it was ignoring the other node.

Some debugging traced the problem to: https://github.com/bitcoin/bitcoin/blob/master/src/main.cpp#L4307

I understand the rationale, of course, it makes no sense to share blocks if we're at the beginning of the chain. But we define 'initial block download' as 'hasn't received a block in the last 24 hours'. So it is also on while catching up.

Nodes which are almost-synced could in very well partake in serving old blocks, or am I missing something?

### PR DESCRIPTION
**Pull request by rebroad**
An improvement over #6172. Fixes #6971 rather than bypasses it as #6974 did, and reduces overloading of whitelisting.

### CODE REVIEW

**Comment by dcousens** [comment]
Would it be better to use chain work here too? (ref https://github.com/bitcoin/bitcoin/pull/9053)

**Comment by rebroad** [comment]
@dcousens A nice idea, but this change is to fix the concerns raised here: https://github.com/bitcoin/bitcoin/pull/5927#issuecomment-104665085 which requires it to be linked to the last checkpoint. For some reason additional criteria got added too that made it too strict.

**Comment by laanwj** [comment]
Instead of adding more reliance on checkpoints, we should be getting rid of them. @gmaxwell has work in progress to do this.

**Comment by gmaxwell** [comment]
NAK. No more reliance on checkpoints.  Also-- IsInitialBlockDownload does a fine job here AFAIK-- this is literally its job (esp with my changes that are less likely to let it get tripped up on testnet with headers forked).

**Comment by MarcoFalke** [comment]
Needs rebase, if still relevant.

**Comment by rebroad** [comment]
@laanwj This PR does not add more reliance on checkpoints, as the previous code also used checkpoints.

**Comment by MarcoFalke** [comment]
@rebroad Please, this is not an argument.

Because something was done in the past does not mean it is correct and encouraged forever. Often we keep code that works (but relies on bad pratices) because no one found time to fix it... I don't see a way where we restore the checkpoint functionality you are referencing in this pull.

**Comment by rebroad** [comment]
@MarcoFalke A step in the right direction while waiting for a better solution is surely better than standing still while waiting for a better solution.

**Comment by rebroad** [comment]
And in response to @gmaxwell https://botbot.me/freenode/bitcoin-core-dev/msg/75840350/ - this PR reduces the DoS effect you refer to - i.e. it ignores FEWER getheaders than previously.

**Comment by rebroad** [comment]
I think there is some serious reality distortion going on here. I honestly have zero idea why this PR is not a quick and easy improvement and introduces zero debt.

**Pull request closed without merging**
