### PR TITLE
ci: Stop and remove CI container

### PR DESCRIPTION
**Pull request by maflcko**
This should not affect CI runs that have `DANGER_RUN_CI_ON_HOST=1` set, for example `.cirrus.yml`.

However, when running CI locally with podman or docker, the container is stopped and thus deleted when all tests have passed. This feature was requested in https://github.com/bitcoin/bitcoin/pull/26843#issuecomment-1374445512 and can help to reduce used disk space when running several CI tasks subsequently.

### CODE REVIEW

**Comment by fanquake** [comment]
Concept ACK

**Comment by hebasto** [comment]
Concept ACK.

**Review by fanquake — APPROVED** [review]
ACK fa0584eb829f2cb52675e17b5b09b4c648378d38

**Review by hebasto — APPROVED** [review]
ACK fa0584eb829f2cb52675e17b5b09b4c648378d38, tested on Ubuntu 22.04.

My only concerns are about `CI_` "namespace" for variables, which has being actively used by CI providers. No conflicts with [Cirrus CI](https://cirrus-ci.org/guide/writing-tasks/#environment-variables) although.

**Comment by MarcoFalke** [comment]
Happy to pick another name, if there are suggestions.

**Comment by hebasto** [comment]
> Happy to pick another name, if there are suggestions.

Maybe `BITCOIN_...`?

**Comment by MarcoFalke** [comment]
Will leave as-is for now. Can be changed in a follow-up, because merge conflicts in this area are rare.

**Pull request merged**
