### PR TITLE
Add chainwork to getchaintxstats

### PR DESCRIPTION
**Pull request by sipa**
This makes it easier to create and verify the `nMinimumChainWork` data in chain parameters.

### CODE REVIEW

**Comment by gmaxwell** [comment]
Hm? getblockchaininfo gives it to you, and this is what the readme tells you to use.

**Comment by sipa** [comment]
It only gives it you for the tip. `getchaintxstats` works for any block.

**Review by promag — COMMENTED** [review]
Can you add the new field in the functional test in `test/functional/blockchain.py`?

**Comment by jnewbery** [comment]
What's the reason for wanting chainwork for any arbitrary block? Are you expecting to use nMinimumChainWork and defaultAssumeValid from the same block? Or is it so you can verify you have the exact same value as someone else who's run the release process?

**Comment by sipa** [comment]
@jnewbery Yes, ability to repeatably come up with the same numbers, even if the exact value doesn't matter.

This probably belongs more in `getblockheader` than in `getchaintxstats`, as it's not really a statistic about transactions. Closing.

**Comment by achow101** [comment]
`getblockheader` already includes the chainwork for a block.

**Comment by sipa** [comment]
Oops, totally unnecessary in that case.

**Pull request closed without merging**
