### PR TITLE
Move AdvertiseLocal debug output to net category

### PR DESCRIPTION
**Pull request by Mirobit**
Not sure why this information is needed in the gernal debug log.

### CODE REVIEW

**Comment by fanquake** [comment]
Please squash your commits.

**Comment by laanwj** [comment]
Yes, why not, Concept ACK
See here for commit squashing instructions: https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#squashing-commits

**Comment by paveljanik** [comment]
Concept ACK

**Comment by laanwj** [comment]
That didn't work, now you have added two commits including a merge commit.

**Comment by MarcoFalke** [comment]
You can try

```shell
git reset f4a59ab~
git commit -m "Move AdvertiseLocal debug output to net category" src/

**Comment by laanwj** [comment]
Still needs squashing.
If you really don't manage to do so (try to follow @MarcoFalke's steps), you could re-do the changes as one commit.

**Pull request closed without merging**
