### PR TITLE
Update libsecp256k1 subtree to current master

### PR DESCRIPTION
**Pull request by fanquake**
This includes changes from the 0.4.1 release: https://github.com/bitcoin-core/secp256k1/releases/tag/v0.4.1.

> The point multiplication algorithm used for ECDH operations (module ecdh) was replaced with a slightly faster one.

> Optional handwritten x86_64 assembly for field operations was removed because modern C compilers are able to output more efficient assembly. This change results in a significant speedup of some library functions when handwritten x86_64 assembly is enabled (--with-asm=x86_64 in GNU Autotools, -DSECP256K1_ASM=x86_64 in CMake), which is the default on x86_64. Benchmarks with GCC 10.5.0 show a 10% speedup for secp256k1_ecdsa_verify and secp256k1_schnorrsig_verify.

### CODE REVIEW

**Comment by fanquake** [comment]
cc @real-or-random @jonasnick

**Comment by hebasto** [comment]
Shouldn't the subtree be synced to the `v0.4.1` tag instead of the current master branch?

**Comment by fanquake** [comment]
> Shouldn't the subtree be synced to the v0.4.1 tag instead of the current master branch?

Why? It makes 0 difference.

**Comment by fanquake** [comment]
I would also prefer not to introduce some policy about only using tags, or similar, because we want to retain the ability to update the subtree to any commit we'd like, at any point.

**Review by hebasto — APPROVED** [review]
ACK c13a17c6996442f04635bdf70ee8f06bf6854ff6, I've updated the `secp256k1` to its current master branch ([efe85c70a2e357e3605a8901a9662295bae1001f](https://github.com/bitcoin-core/secp256k1/commit/efe85c70a2e357e3605a8901a9662295bae1001f)) locally and got zero diff with this PR.

However, the PR title and description are a bit misleading as they mention "0.4.1 release", which implies (at least for me) syncing to the `v0.4.1` tag.

**Review by jonasnick — APPROVED** [review]
ACK c13a17c6996442f04635bdf70ee8f06bf6854ff6 no difference to my locally checked out version.

**Review by real-or-random — APPROVED** [review]
Concept ACK c13a17c6996442f04635bdf70ee8f06bf6854ff6 I haven't checked that the subtree is correct but no objections to update to this commit

> However, the PR title and description are a bit misleading as they mention "0.4.1 release", which implies (at least for me) syncing to the `v0.4.1` tag.

True, this updates to the merge commit of the "cleanup" PR after the release.  But yeah, it really doesn't matter in the end, and I think there's no need to invalidate the ACKs here.

**Comment by luke-jr** [comment]
It makes a minor difference of reporting the correct version number. I agree with @hebasto on using the tag, but also agree with @fanquake on not having a policy that we must use tags.

**Comment by fanquake** [comment]
> It makes a minor difference of reporting the correct version number. 

What do you mean by/where are we reporting the version number?

**Comment by fanquake** [comment]
I've updated to commit message to make it clear that this isn't exactly the 0.4.1 tag. 

> Plus, ./configure --help in the subtree mentions 

I was thinking more like output from bitcoind or similar.

**Review by hebasto — APPROVED** [review]
re-ACK e2cdeb592596432039d21f4c819d45f1e46d65ef

**Review by real-or-random — APPROVED** [review]
Concept ACK https://github.com/bitcoin/bitcoin/commit/c13a17c6996442f04635bdf70ee8f06bf6854ff6 I haven't checked that the subtree is correct but no objections to update to this commit

**Review by jonasnick — COMMENTED** [review]
reACK e2cdeb592596432039d21f4c819d45f1e46d65ef

**Comment by jamesob** [comment]
Probably neither here nor there, but didn't see much of a performance impact from this. 

ibd local range dbcache=4000 667200 697200

**Comment by jamesob** [comment]
Oddly enough, this change benched out as being slightly slower (~4.8%) than the commit before it in master. 

Not a huge regression, but not what I expected. Compiled with `gcc 10.2.1`.

ibd local range dbcache=4000 667200 697200

### #29169 vs. f8ca1357 (absolute)
|                         bench name                         |  x  |           #29169           |          f8ca1357          |
| ---------------------------------------------------------- | --: | -------------------------- | -------------------------- |
| ibd.local.range.dbcache=4000.667200.697200.total_secs      |   2 | 13522.9734 (± 42.0521)     | 12901.7487 (± 6.9377)      |
| ibd.local.range.dbcache=4000.667200.697200.peak_rss_KiB    |   2 | 4431630.0000 (± 5274.0000) | 4431262.0000 (± 1938.0000) |
| ibd.local.range.dbcache=4000.667200.697200.cpu_kernel_secs |   2 | 462.5950 (± 1.8850)        | 459.9700 (± 0.5700)        |
| ibd.local.range.dbcache=4000.667200.697200.cpu_user_secs   |   2 | 47645.5000 (± 175.3900)    | 45210.2300 (± 37.1900)     |


### #29169 vs. f8ca1357 (relative)
|                         bench name                         |  x  |       #29169       | f8ca1357 |
| ---------------------------------------------------------- | --: | -----------------: | -------: |
| ibd.local.range.dbcache=4000.667200.697200.total_secs      |   2 | 1.0481504324562638 |        1 |
| ibd.local.range.dbcache=4000.667200.697200.peak_rss_KiB    |   2 | 1.0000830463195360 |        1 |
| ibd.local.range.dbcache=4000.667200.697200.cpu_kernel_secs |   2 | 1.0057068939278648 |        1 |
| ibd.local.range.dbcache=4000.667200.697200.cpu_user_secs   |   2 | 1.0538654636351110 |        1 |

**Comment by real-or-random** [comment]
Hm, this is really not expected.

> Compiled with `gcc 10.2.1`.

You could see if gcc 10.5.0 makes a difference. AFAIU this is used in the official builds currently (until https://github.com/bitcoin/bitcoin/pull/27897 lands), and this was one of our considerations.

If that doesn't help, please benchmark libsecp256k1 with (https://github.com/bitcoin-core/secp256k1/commit/10e6d29b60c3931e327bc18e6c50cea78296b1ba) and without https://github.com/bitcoin-core/secp256k1/pull/1446 (https://github.com/bitcoin-core/secp256k1/commit/07687e811d1c9700e6fe9d658aef080e3568c0f1), see the PR for instructions and also consider setting `SECP256K1_BENCH_ITERS=200000` or another large value.

**Comment by jamesob** [comment]
Quick update:

I did confirm (on another machine) that more contemporary versions of gcc (`12.2.0` in this case) do show a speed _up_ of about 4%, with slightly more time spent in kernel:

### #29169 vs. f8ca1357 (relative)
|                         bench name                         |  x  |       #29169       |      f8ca1357      |
| ---------------------------------------------------------- | --: | -----------------: | -----------------: |
| ibd.local.range.dbcache=4000.667200.697200.total_secs      |   2 | 1.0000000000000000 | 1.0400910327330894 |
| ibd.local.range.dbcache=4000.667200.697200.peak_rss_KiB    |   2 | 1.0000000000000000 | 1.0018178271964506 |
| ibd.local.range.dbcache=4000.667200.697200.cpu_kernel_secs |   2 | 1.0225739275301957 | 1.0000000000000000 |
| ibd.local.range.dbcache=4000.667200.697200.cpu_user_secs   |   2 | 1.0000000000000000 | 1.0711547761286089 |

I also confirmed that the gcc 10 result was not a fluke; a rerun again showed 5% regression. I'm rerunning with gcc 12 on that same machine and will post the results when they're up. I guess this is all expected since the libsecp change was advertised to be contingent on improvements in gcc.

**Comment by jamesob** [comment]
Oddly enough, even with `gcc 12.2.0`, the regression on the first machine holds. Artifacts here: https://gist.github.com/jamesob/1f4456f1f9bafcabb392210bbfe9f240

Will run the secp benches in isolation.

**Comment by jamesob** [comment]
> If that doesn't help, please benchmark libsecp256k1 with ([bitcoin-core/secp256k1@10e6d29](https://github.com/bitcoin-core/secp256k1/commit/10e6d29b60c3931e327bc18e6c50cea78296b1ba)) and without [bitcoin-core/secp256k1#1446](https://github.com/bitcoin-core/secp256k1/pull/1446) ([bitcoin-core/secp256k1@07687e8](https://github.com/bitcoin-core/secp256k1/commit/07687e811d1c9700e6fe9d658aef080e3568c0f1)), see the PR for instructions and also consider setting `SECP256K1_BENCH_ITERS=200000` or another large value.

These benchmarks are indeed slower on the first host when compiling with `debian gcc 12.2.0-14`. Data here: https://gist.github.com/jamesob/52133933b9728ab0f677563ef6bc554e

**Pull request merged**
