### PR TITLE
guix: remove GCC 10 workaround from NSIS

### PR DESCRIPTION
**Pull request by fanquake**
Fixed upstream in 3.06.
See https://github.com/kichik/nsis/commit/229b6136c41ba5caba25936f4927476d20aa283f and https://sourceforge.net/p/nsis/bugs/1248/.

Split from #27897, as that is still WIP, and GCC 12 isn't required to make this change.
This commit could have gone in with #28328.

Guix Build (same for x86_64 & aarch64):
```bash
81a565bc5c719d04cb6640cf7593d7fdd6e37935dc2ac9280f638e625c1c5f87  guix-build-588068d5a12b/output/aarch64-linux-gnu/SHA256SUMS.part
6f1ed3a2a053c3e90f1511fe33239378fc2631f46d795a955807ab39e2b93dfc  guix-build-588068d5a12b/output/aarch64-linux-gnu/bitcoin-588068d5a12b-aarch64-linux-gnu-debug.tar.gz
c8a2904c651b862d9dce3f4094b59b66be5e745111b75c420452bd04ab9cdbe3  guix-build-588068d5a12b/output/aarch64-linux-gnu/bitcoin-588068d5a12b-aarch64-linux-gnu.tar.gz
654bb5d89e12f936e63e2c910c78842c43db7048a895052295f613a50b639857  guix-build-588068d5a12b/output/arm-linux-gnueabihf/SHA256SUMS.part
8a1b67f3c12b579b374c559f59d709bd83bcd3cff3ec5a4274119c0e5f6c388f  guix-build-588068d5a12b/output/arm-linux-gnueabihf/bitcoin-588068d5a12b-arm-linux-gnueabihf-debug.tar.gz
7d8a3327599702a94be4b8d49eda7857f732c290773a775c6de507da656e271b  guix-build-588068d5a12b/output/arm-linux-gnueabihf/bitcoin-588068d5a12b-arm-linux-gnueabihf.tar.gz
215786257409612206db7ff4008dbcb6a60dcf6cc92a1a437124a1483612f699  guix-build-588068d5a12b/output/arm64-apple-darwin/SHA256SUMS.part
e36b41c531d34ca843028b778163bed4ce4c52310ed8056eff8a1a1b47b61fb7  guix-build-588068d5a12b/output/arm64-apple-darwin/bitcoin-588068d5a12b-arm64-apple-darwin-unsigned.dmg
ecb488625bdf566e7c63781795f296ec4f630ef90edf7e6073591ed1d9b90bda  guix-build-588068d5a12b/output/arm64-apple-darwin/bitcoin-588068d5a12b-arm64-apple-darwin-unsigned.tar.gz
d8f9759a903cd052ea3e562d1ef186c9dad38089205650d1bcb218e7506c378f  guix-build-588068d5a12b/output/arm64-apple-darwin/bitcoin-588068d5a12b-arm64-apple-darwin.tar.gz
385084fe6d80d0b563b1b20d558b29681fd5bf624bc70c403e831cd8aae45dc0  guix-build-588068d5a12b/output/dist-archive/bitcoin-588068d5a12b.tar.gz
89504c8be28482d4f70740d6865aa26db0e1854d0b35598c43462cd35f0b49c4  guix-build-588068d5a12b/output/powerpc64-linux-gnu/SHA256SUMS.part
5836bfb4c9a11318362a89db25e4cd9363688ae6be18a6abfd1974a52c0b2759  guix-build-588068d5a12b/output/powerpc64-linux-gnu/bitcoin-588068d5a12b-powerpc64-linux-gnu-debug.tar.gz
3e6f4481a594316ab08ea946c5fac6055ca8a81a91ce0a20c44976b3bc4f8d0d  guix-build-588068d5a12b/output/powerpc64-linux-gnu/bitcoin-588068d5a12b-powerpc64-linux-gnu.tar.gz
4e753efe5a20cf6f1e83e604d9f8ba0d79b3c96fc5d5487ec7ed0f33c819b99a  guix-build-588068d5a12b/output/powerpc64le-linux-gnu/SHA256SUMS.part
9d29e49b519ce1d683531699dd15e72495052151b21404affc50e7b228155eb1  guix-build-588068d5a12b/output/powerpc64le-linux-gnu/bitcoin-588068d5a12b-powerpc64le-linux-gnu-debug.tar.gz
511179d90bbf6beb45b6168575a78600d38a060891dc1aa8f11f0adc5ba51f87  guix-build-588068d5a12b/output/powerpc64le-linux-gnu/bitcoin-588068d5a12b-powerpc64le-linux-gnu.tar.gz
d46184105524d59a75066b067b63df6bfd2203d8003c343a5898ee7d4e4f78e5  guix-build-588068d5a12b/output/riscv64-linux-gnu/SHA256SUMS.part
b6434ec5a4a046b9448f36f5596f6db0f8cd71a3e4383827869fcbaa25e005e4  guix-build-588068d5a12b/output/riscv64-linux-gnu/bitcoin-588068d5a12b-riscv64-linux-gnu-debug.tar.gz
237e37ccae4095a1d8aa34d6b967655561ba0a524dfb79e3dcd4c18ad8f8a222  guix-build-588068d5a12b/output/riscv64-linux-gnu/bitcoin-588068d5a12b-riscv64-linux-gnu.tar.gz
db28897936262e344da8011d37afde97ed53ba4f5ce1a3f935d258284b22e649  guix-build-588068d5a12b/output/x86_64-apple-darwin/SHA256SUMS.part
8d71763fc748cde1f68785eef4b1a498c1ec4c13cf94f02ad8727debe0d94a1d  guix-build-588068d5a12b/output/x86_64-apple-darwin/bitcoin-588068d5a12b-x86_64-apple-darwin-unsigned.dmg
1e0bf2ef0f65f2e7fe5439fe0a15a4803e06d7c42dae06133be5d1b67fa30657  guix-build-588068d5a12b/output/x86_64-apple-darwin/bitcoin-588068d5a12b-x86_64-apple-darwin-unsigned.tar.gz
2d71083593583f3a3ed2e83d4a05f67338e9cb51cb730d238827eef7d3e9007e  guix-build-588068d5a12b/output/x86_64-apple-darwin/bitcoin-588068d5a12b-x86_64-apple-darwin.tar.gz
cc3cc2c1077a04d5643ca21a43b8b7f233b8c743eb73f066643ddfd4a1e1ce27  guix-build-588068d5a12b/output/x86_64-linux-gnu/SHA256SUMS.part
e18c1c0c1cf836c9e540edd969d2657afd3847345b1e0a6e5a9bebfd35782c47  guix-build-588068d5a12b/output/x86_64-linux-gnu/bitcoin-588068d5a12b-x86_64-linux-gnu-debug.tar.gz
4c88aa50227ccd7bb9069369cfc2196de42212f5d0553902155346ae39ef2401  guix-build-588068d5a12b/output/x86_64-linux-gnu/bitcoin-588068d5a12b-x86_64-linux-gnu.tar.gz
51f9f0d9c21598d9d37132e21c786378468c50c393b46e084d81c504186238cd  guix-build-588068d5a12b/output/x86_64-w64-mingw32/SHA256SUMS.part
a4a0b55a40ba17b70c93eaba132e31c94cb2380cad0fe4e2ebe199c68a49c293  guix-build-588068d5a12b/output/x86_64-w64-mingw32/bitcoin-588068d5a12b-win64-debug.zip
75495c9a00ee7401b96afa51c93fe56d8b10a531ce0526f5b4713b9e8aaab9a5  guix-build-588068d5a12b/output/x86_64-w64-mingw32/bitcoin-588068d5a12b-win64-setup-unsigned.exe
a6e8416846ebea253d2b3c5c40f60a227bd5cfb2272a477cf364a085fea140e4  guix-build-588068d5a12b/output/x86_64-w64-mingw32/bitcoin-588068d5a12b-win64-unsigned.tar.gz
2bbd6cd49ad0297a5b3279a5cfbcbb35586cfdd72388e5e1ef2d87e1c8a9cf97  guix-build-588068d5a12b/output/x86_64-w64-mingw32/bitcoin-588068d5a12b-win64.zip
```

### CODE REVIEW

**Comment by hebasto** [comment]
```
x86_64
385084fe6d80d0b563b1b20d558b29681fd5bf624bc70c403e831cd8aae45dc0  guix-build-588068d5a12b/output/dist-archive/bitcoin-588068d5a12b.tar.gz
51f9f0d9c21598d9d37132e21c786378468c50c393b46e084d81c504186238cd  guix-build-588068d5a12b/output/x86_64-w64-mingw32/SHA256SUMS.part
a4a0b55a40ba17b70c93eaba132e31c94cb2380cad0fe4e2ebe199c68a49c293  guix-build-588068d5a12b/output/x86_64-w64-mingw32/bitcoin-588068d5a12b-win64-debug.zip
75495c9a00ee7401b96afa51c93fe56d8b10a531ce0526f5b4713b9e8aaab9a5  guix-build-588068d5a12b/output/x86_64-w64-mingw32/bitcoin-588068d5a12b-win64-setup-unsigned.exe
a6e8416846ebea253d2b3c5c40f60a227bd5cfb2272a477cf364a085fea140e4  guix-build-588068d5a12b/output/x86_64-w64-mingw32/bitcoin-588068d5a12b-win64-unsigned.tar.gz
2bbd6cd49ad0297a5b3279a5cfbcbb35586cfdd72388e5e1ef2d87e1c8a9cf97  guix-build-588068d5a12b/output/x86_64-w64-mingw32/bitcoin-588068d5a12b-win64.zip
```

**Comment by hebasto** [comment]
`bitcoin-588068d5a12b-win64-setup-unsigned.exe` tested on Windows 11 Pro 22H2.

**Review by hebasto — APPROVED** [review]
ACK 588068d5a12b752b70bb7e4f3f8decb1ce2fe4e8.

```
aarch64
385084fe6d80d0b563b1b20d558b29681fd5bf624bc70c403e831cd8aae45dc0  guix-build-588068d5a12b/output/dist-archive/bitcoin-588068d5a12b.tar.gz
51f9f0d9c21598d9d37132e21c786378468c50c393b46e084d81c504186238cd  guix-build-588068d5a12b/output/x86_64-w64-mingw32/SHA256SUMS.part
a4a0b55a40ba17b70c93eaba132e31c94cb2380cad0fe4e2ebe199c68a49c293  guix-build-588068d5a12b/output/x86_64-w64-mingw32/bitcoin-588068d5a12b-win64-debug.zip
75495c9a00ee7401b96afa51c93fe56d8b10a531ce0526f5b4713b9e8aaab9a5  guix-build-588068d5a12b/output/x86_64-w64-mingw32/bitcoin-588068d5a12b-win64-setup-unsigned.exe
a6e8416846ebea253d2b3c5c40f60a227bd5cfb2272a477cf364a085fea140e4  guix-build-588068d5a12b/output/x86_64-w64-mingw32/bitcoin-588068d5a12b-win64-unsigned.tar.gz
2bbd6cd49ad0297a5b3279a5cfbcbb35586cfdd72388e5e1ef2d87e1c8a9cf97  guix-build-588068d5a12b/output/x86_64-w64-mingw32/bitcoin-588068d5a12b-win64.zip
```

**Review by sedited — COMMENTED** [review]
Post-merge ACK 588068d5a12b752b70bb7e4f3f8decb1ce2fe4e8

Reproduced the build hashes on both x86_64 and aarch64.

**Pull request merged**
