### PR TITLE
Add Gitian PGP key: Sjors

### PR DESCRIPTION
**Pull request by Sjors**
First Gitian PR: bitcoin/gitian.sigs#603

### CODE REVIEW

**Comment by promag** [comment]
LGTM.

**Comment by fanquake** [comment]
utACK 41b15cf

**Comment by laanwj** [comment]
```
pub  rsa4096/0x57FF9BDBCC301009 2015-06-30 [expires: 2019-06-30]
uid                             Sjors Provoost <sjors@sprovoost.nl>
uid                             Sjors Provoost <sjors@freedom.nl>
sub  rsa4096/0x498A18F9F6BB9174 2015-06-30 [expires: 2019-06-30]
```
Verified that this is the key used to sign Sjors' gitian builds.
utACK 41b15cf

**Comment by jonasschnelli** [comment]
ACK 41b15cfc9e6e25c63696c002bfdfec78882419cf

```
pub   rsa4096 2015-06-30 [SC] [verfällt: 2019-06-30]
      ED9BDF7AD6A55E232E84524257FF9BDBCC301009
uid        [  marginal ] Sjors Provoost <sjors@sprovoost.nl>
uid        [  marginal ] Sjors Provoost <sjors@freedom.nl>
sub   rsa4096 2015-06-30 [E] [verfällt: 2019-06-30]
```

Successfully verified key with signatures from https://github.com/bitcoin-core/gitian.sigs/pull/603.

**Pull request merged**
