### PR TITLE
Relative time

### PR DESCRIPTION
**Pull request by rebroad**
Improves the debug for AskFor() - removes the rather useless decimal display of time and the date format, and replaces with time from now, which is much easier to read (and speed read). Also now logs the sizes mapAskFor, mapAlreadyAskedFor and setAskFor.

Also creates a strAge() function which I think could be useful for various things (e.g. lastseen time, etc).

### CODE REVIEW

**Comment by gmaxwell** [comment]
Fields with variable units are a real pain to parse from scripts.

**Comment by laanwj** [comment]
> Fields with variable units are a real pain to parse from scripts.

I know it's being done because of lack of a better interface to get various information in machine readable format, but arguably debug logs should not be considered an interface to other software, but are for troubleshooting by operators.

**Comment by rebroad** [comment]
@gmaxwell I'd be surprised if anyone is parsing nRequestTime from the askfor lines of a debug.log

**Comment by gmaxwell** [comment]
@rebroad I absolutely have.  Let me put it another way:  What possibly useful thing is anyone going to do with that data _except_ parse it out and chart it to observe the behavior?

If it's your belief that people are actually not using it, then it should be removed, not pretty printed to a variable unit that is a real pain to create summary information from.

**Comment by rebroad** [comment]
@gmaxwell If you've used it to parse from then that is reason enough to leave it in, IMHO. Although given that there will be some who want human readable data and some who want machine readable data, then perhaps a command line option is called for....

**Comment by laanwj** [comment]
No way we're going to introduce a command line option for an obscure bit of
logging information.

What I would like is a more general framework for machine-readable
statistics logging (like statoshi) that will log more and more useful
information for producing timing summaries etc using external scripts.

Information such as this could then either be human-formatted or removed in
the debug log depending on whether it is appropriate.

Until then I'd suggest closing this.

**Pull request closed without merging**
