### PR TITLE
[doc] explain what .python-version does

### PR DESCRIPTION
**Pull request by Sjors**
Documentation followup to https://github.com/bitcoin/bitcoin/pull/14884#discussion_r241444376.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
What happens if 3.4.9 isn't installed, but 3.4.8 and 3.5.1?

**Comment by Sjors** [comment]
Then pyenv complains as soon as you run a test:
```
pyenv: version `3.4.9' is not installed (set by .python-version)
```

 It's trivial to add as many Python versions as you want with `pyenv install VERSION`.

**Comment by jnewbery** [comment]
utACK 04215eb328de23151ef1e3572b7a16a9f4efa1a2

**Comment by practicalswift** [comment]
utACK 04215eb328de23151ef1e3572b7a16a9f4efa1a2

**Pull request merged**
