### PR TITLE
net: Hardcoded seed update

### PR DESCRIPTION
**Pull request by laanwj**
Update the hardcoded node addresses, after changing the pattern to include 0.15.x.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Tested ACK 1e9054415336d68d4ea6c2f49e83c2dc5743dd69
Randomly tested some of the new IPs.

**Comment by jnewbery** [comment]
ACK 1e9054415336d68d4ea6c2f49e83c2dc5743dd69.

Tested that:
- makeseeds.py generates a similar list to the new nodes_main.txt in this PR
- generate-seeds.py converts the nodes_main.txt in this PR to the src/chainparamsseeds.h in this PR
- I'm able to connect to a random selection of 5 of the IPv4 seed nodes in this PR.

**Comment by promag** [comment]
Typo in first commit.

**Comment by laanwj** [comment]
> Typo in first commit.

True, nah, not going to invalidate my reviews over that.

**Comment by gmaxwell** [comment]
ACK.

**Pull request merged**
