### PR TITLE
developer notes: updates for C++11

### PR DESCRIPTION
**Pull request by kazcw**

### CODE REVIEW

**Comment by dcousens** [comment]
concept ACK

**Comment by sipa** [comment]
I'm personally fine with C-style casts for integer types, because for the
semantics are simple, unambiguous, and much shorter than using the C++
style.

However, if people feel strongly about this, I'm fine with strictly
avoiding them.

**Comment by laanwj** [comment]
I'm fine with C-style casts too for primitive types. No need to change anything there, they're not more magical than anything else.

For object types and such it makes sense to require c++ cases.

ACK on the scoped_ptr to unique_ptr change.

**Comment by dcousens** [comment]
@laanwj it does make searching for casts and points of concern much easier if you use `static_cast` and the rest of the C++ family of casts.
The C-syntax, while more concise in context, often bears a higher intellectual load as to the broader implications of the action in the long run,  IMHO.

The extra safety guarantees are also a boon and pretty excellent for what I would consider safety conscious software.

It also makes casts even uglier,  as they should be.

**Comment by laanwj** [comment]
>  it does make searching for casts and points of concern much easier if you use static_cast and the rest of the C++ family of casts.

How often do you actually want to search for all casts?

> The extra safety guarantees are also a boon and pretty excellent for what I would consider safety conscious software.

Can you be more specific here? How are casts of primitive types safer using C++ syntax?

I know that pointer casts are safer using C++ syntax and as they are the dangerous kind of casting. I agree with using C++ syntax when casting from const to non const pointers, or one kind of pointer to another, but I don't agree doing so for all cases where primitive types are converted.

**Comment by laanwj** [comment]
I'm also not looking forward to 20 PRs full of 'convert one type of cast to another'. In the time we run this project we've (as far as I know) never had a bug caused by casting. There's no immediate need here. I wrote those developer suggestions all after having found an issue caused by that particular thing. They're not meant for style preferences.

**Comment by laanwj** [comment]
We should mention this one: avoid shadowing vars, and enable -Wshadow #8105
Very sneaky bug introduced by this: https://github.com/bitcoin/bitcoin/pull/8102#issuecomment-221934374

**Comment by dcousens** [comment]
> Can you be more specific here? How are casts of primitive types safer using C++ syntax?

> I know that pointer casts are safer using C++ syntax and as they are the dangerous kind of casting.

Perhaps I mis-indicated that I was referring to int style casts,  the above was a blanket opinion.

In respect to: 
> I agree with using C++ syntax when casting from const to non const pointers, or one kind of pointer to another, but I don't agree doing so for all cases where primitive types are converted.

I think this is a good compromise.
That said, IMHO, primitive conversions can often [but certainly not always] be an indication that the underlying type is over-constrained or just plain wrong.

In light of:
> I'm also not looking forward to 20 PRs full of 'convert one type of cast to another'

I too think this may be just another nit-pick enabling PR,  but,  it is certainly a desirable goal... at some point.

**Comment by kazcw** [comment]
Removed the statement on C-style casts.

**Pull request merged**
