### PR TITLE
build: Disallow shadowing variables via -isystem, -Wshadow

### PR DESCRIPTION
**Pull request by Empact**
Shadowed variables are implicated in logic errors, duplicative code, and
unnecessary operation. Catching them automatically is best.

As with -Wdocumentation, warns when configured with --enable-isystem,
errors if configured with --enable-werror as well.

This is built on / depends on: #14920

### CODE REVIEW

**Comment by practicalswift** [comment]
Concept ACK

**Comment by laanwj** [comment]
Sorry, but NACK. Please not this again. I still remember what a clusterfck enabling shadowing warnings was last time. It created such a torrend of PRs:

 #9911
 #10009 
  #10010
 ...

It also wasn't consistent between compilers so just that you have no shadowing warnings doesn't mean that no one else has, triggering a 'shadowing fixup' PR after every other normal PR, until it was finally disabled in #10136.

**Comment by practicalswift** [comment]
@laanwj What about only enabling in Travis for `clang`? That way there will be no need for manual reviewers pointing out accidental shadowing: that will already have been fixed before manual review starts. I see quite a few of these when doing review work.

**Comment by Empact** [comment]
Yeah, to distinguish this from those other PRs, with this Travis will fail on the introduction of a violation, so dealing with them will be off-loaded from the reviewer to the pull requester, based on that this should reduce review burden.

**Comment by gmaxwell** [comment]
NAK.  Forcing contributors to do battle with the random failures of a remote compiler is not attractive.

I wish shadow warnings were useful in C++ like they are in C, but they aren't. They're continually spurious.  We tried shadow warnings before and it was a nuisance.  I don't expect this to change unless compiler authors add an additional kind of narrower scope shadow warning.

Furthermore, I'm not aware of any bugs in this project being introduced or hidden by shadowing so far.  I am, however, aware of PRs that created bugs trying to silence warnings.

**Comment by Empact** [comment]
Closing due to controversy

**Pull request closed without merging**
