### PR TITLE
build: Make lint-locale-dependence.sh work with BSD grep (avoid empty subexpressions)

### PR DESCRIPTION
**Pull request by practicalswift**
Make `lint-locale-dependence.sh` work with BSD `grep` by avoiding empty subexpressions.

macOS High Sierra:

```
$ grep --version
grep (BSD grep) 2.5.1-FreeBSD
$ echo foo | grep -E '^foo(_r|_s)?$'
foo
$ echo foo | grep -E '^foo(|_r|_s)$'
grep: empty (sub)expression
```

Ubuntu 18.04 LTS:

```
$ grep --version
grep (GNU grep) 3.1
$ echo foo | grep -E '^foo(_r|_s)?$'
foo
$ echo foo | grep -E '^foo(|_r|_s)$'
foo
```

Reported by @masonicboom in https://github.com/bitcoin/bitcoin/pull/13708#discussion_r203791916. Thanks!

### CODE REVIEW

**Comment by Empact** [comment]
utACK 5a3eefc4 how much work would it be to make the scripts fully compatible with BSD grep? Would be nice to remove the gnu grep requirement.

**Comment by Empact** [comment]
There's another empty subexpression in `lint-shell-locale.sh`, line 18

**Comment by practicalswift** [comment]
@Empact Fixed the GNU:Ism in `lint-shell-locale.sh`. Do you know of any other incompatibility with BSD grep? I've now added a linter that will help us avoid introducing GNU:isms in our shell scripts :-)

Please re-review!

**Comment by laanwj** [comment]
Thanks for doing this but...
*sigh* more shell-lowest-common-denominator-porting
I wish we just bit the bullet ported this stuff to Python so that it's, by definition, not dependent on external tools.

**Comment by Empact** [comment]
As an alternative to the linter here, I set up running the linter check on Mac via Travis, #13728.

**Comment by practicalswift** [comment]
I prefer @Empact:s solution in #13728 which runs the linter chers on Mac via Travis

 Closing this PR since it won't be relevant when #13728 have been merged.

**Pull request closed without merging**
