### PR TITLE
Move GetTempPath() to testutil

### PR DESCRIPTION
**Pull request by musalbas**
Addresses https://github.com/bitcoin/bitcoin/issues/6702 and https://github.com/bitcoin/bitcoin/issues/6701.

This pull request creates a new source file for test utils, and moves GetTempPath() from util to testutil.

This is because per the above issues, GetTempPath() is insecure and has unchecked error conditions, making it unsuitable for use in production code. GetTempPath() is only used in the unit tests and not used anywhere in the main code, so it would be a good idea to move this to the test suite so that no one tries to use this in the future and it's not mixed with production code.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Nice!
utACK.

**Comment by musalbas** [comment]
Fixed Windows build error. The build passes now.

**Comment by paveljanik** [comment]
ACK

**Comment by MarcoFalke** [comment]
utACK  2fdaa25

**Comment by laanwj** [comment]
Yes, makes sense, utACK 2fdaa25

**Pull request merged**
