### PR TITLE
build: fix qt distdir builds

### PR DESCRIPTION
**Pull request by theuni**
Just build the same way as the file above it.

Fixes the issue presented by #9416.

### CODE REVIEW

**Comment by theuni** [comment]
@MarcoFalke I believe this should fix your issue.

**Comment by MarcoFalke** [comment]
Thanks for the fix.

utACK 945008d

**Comment by fanquake** [comment]
OS X failed with:
```
Undefined symbols for architecture x86_64:
  "qInitResources_bitcoin()", referenced from:
      _main in qt_bitcoin_qt-bitcoin.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [qt/bitcoin-qt] Error 1
make[1]: Leaving directory `/home/travis/build/bitcoin/bitcoin/build/src'
make: *** [src/qt/bitcoin-qt] Error 2
```

Linux failed with:
```
qt/qt_bitcoin_qt-bitcoin.o: In function `main':
bitcoin.cpp:(.text.startup+0x13d): undefined reference to `qInitResources_bitcoin()'
collect2: error: ld returned 1 exit status
make[2]: *** [qt/bitcoin-qt] Error 1
make[2]: Leaving directory `/home/travis/build/bitcoin/bitcoin/build/src'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/home/travis/build/bitcoin/bitcoin/build/src'
make: *** [install-recursive] Error 1
```

**Comment by theuni** [comment]
Whoops, I remember what this is doing now. This is wrong.

We need to make the distinction between generated files and unchanging files. Since these aren't changed by the build, they need to come from srcdir rather than builddir. So it's correct as-is.

**Pull request closed without merging**
