### PR TITLE
[Net] Refactor: exit when no direct fetch

### PR DESCRIPTION
**Pull request by rebroad**
Adds a return as no need to stay in this function any longer once it has been decided that direct-fetch will not occur, and improves code readability (IMHO).

### CODE REVIEW

**Comment by fanquake** [comment]
Please squash these changes into a single commit.

**Comment by fanquake** [comment]
Needs a rebase.

**Review by kallewoof — COMMENTED** [review]
utACK + verified code with indentation changes was the same.

**Comment by fanquake** [comment]
Closing, nit needs addressing and still needs a rebase. Feel free to reopen when it's ready for re-review.

**Pull request closed without merging**
