### PR TITLE
 gui: update text to eliminate safety hazards

### PR DESCRIPTION
**Pull request by SpicaLab**
This text is a private email address and is misleading.
I have reverted to the original text.

### CODE REVIEW

**Comment by SpicaLab** [comment]
The text error here exists in branch 0.20 and 0.21
Branch 0.20 also needs to be fixed.

https://github.com/bitcoin/bitcoin/blob/0.20/src/qt/locale/bitcoin_zh_CN.ts

**Comment by MarcoFalke** [comment]
Thanks for helping with translations! However, changes to translations as well as new translations are submitted to [Bitcoin Core's Transifex page](https://www.transifex.com/projects/p/bitcoin/).

Translations are periodically pulled from Transifex and merged into the git repository. See the [translation process](https://github.com/bitcoin/bitcoin/blob/master/doc/translation_process.md) for details on how this works. So we do not accept translation changes as GitHub pull requests because the next pull from Transifex would automatically overwrite them again.

**Comment by MarcoFalke** [comment]
I'll leave this open until the fixed translations have been pulled

**Comment by SpicaLab** [comment]
> Thanks for helping with translations! However, changes to translations as well as new translations are submitted to [Bitcoin Core's Transifex page](https://www.transifex.com/projects/p/bitcoin/).
> 
> Translations are periodically pulled from Transifex and merged into the git repository. See the [translation process](https://github.com/bitcoin/bitcoin/blob/master/doc/translation_process.md) for details on how this works. So we do not accept translation changes as GitHub pull requests because the next pull from Transifex would automatically overwrite them again.

I know Bitcoin Core Transifex, but this is not only a translation problem, it may bring other risks.
So I mean is that the proofreading of the translated text may need to be strengthened.

**Comment by laanwj** [comment]
> So I mean is that the proofreading of the translated text may need to be strengthened.

Clearly we need a reviewer for Chinese. Mind getting involved?

**Comment by SpicaLab** [comment]
> Clearly we need a reviewer (and language coordinator) for Chinese. Mind getting involved?

I am very happy to contribute to bitcoin.
How to join a translation reviewer.
Or create an issue before the release of each version, and each native speaker will review the text changes.

**Comment by fanquake** [comment]
This has been fixed in master, so isn't an issue for 22.0, but still exists in the 0.21 and later branches. Added the 0.21.2 milestone.

**Pull request closed without merging**
