### PR TITLE
[qt] Return useful error message on ATMP failure

### PR DESCRIPTION
**Pull request by maflcko**
Follow up of  #9016

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Concept ACK. Will test soon.

**Comment by jonasschnelli** [comment]
Any recommendation how to test this?

**Comment by MarcoFalke** [comment]
You could try to create a transaction which violates policy (e.g. a "free" transaction with full mempool or one which violates the ancestor/descendant limit)

```sh
src/qt/bitcoin-qt -testnet -limitancestorcount=1

**Comment by jonasschnelli** [comment]
Tested ACK 3333e5a1e582225907b201cca64322d7620fbeec
bildschirmfoto 2016-11-01 um 08 31 52

**Comment by MarcoFalke** [comment]
(Strictly speaking, it should be impossible to test. Right now it can only be tested due to bugs such as #9019.)

**Comment by jonasschnelli** [comment]
@MarcoFalke: you can test it (=run into such situation) in conjunction with CoinControl.

**Pull request merged**
