### PR TITLE
Update RPC generate help for numblocks to include required

### PR DESCRIPTION
**Pull request by ChainQuery**
The `generate` RPC has no default `numblocks` and a numeric value is required.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Can you remove the merge-commit from the branch, please?

**Comment by jonasschnelli** [comment]
ACK after squashing (remove merge commit).

**Comment by laanwj** [comment]
Better to be explicit, IMO (defaults are annoying with positional arguments). Apart from that, this call is only used for testing (regtest), adding a default doesn't make much sense.

ACK after removing the spurious commit.

**Comment by ChainQuery** [comment]
Sorry folks, still figuring out git, going to close this request.

**Pull request closed without merging**
