### PR TITLE
msvc: Define the same `QT_...` macros as in Autotools builds

### PR DESCRIPTION
**Pull request by hebasto**
There are no reasons to have such a diversion.

Also it fixes https://github.com/bitcoin/bitcoin/pull/28960#issuecomment-1847971114.

### CODE REVIEW

**Comment by sipsorcery** [comment]
@hebasto what version of QT are you using for Windows builds? 

It's been a while since I did a QT build and I'm having lots of challenges with `5.15.11` on `master`.

**Comment by hebasto** [comment]
> @hebasto what version of QT are you using for Windows builds?

Qt 5.15.11

> It's been a while since I did a QT build and I'm having lots of challenges with `5.15.11` on `master`.

I've made another Qt 5.15.11 build just today with no issues.

**Comment by sipsorcery** [comment]
tACK 1a5dae630df1eef9eac51557b2f1c5dba0924953.

**Review by sedited — APPROVED** [review]
ACK 1a5dae630df1eef9eac51557b2f1c5dba0924953

Thank you @hebasto, this fixes the build failure of #28960.

**Pull request merged**
