### PR TITLE
Use proper lowercase "k" for kB measurements

### PR DESCRIPTION
**Pull request by luke-jr**
Note: Did not update the Qt debug window's Network Traffic tab because it really is using 1024-base units (which is uppercase-K).

### CODE REVIEW

**Comment by paveljanik** [comment]
ACK

**Comment by Diapolo** [comment]
kB is 1000 as base, right?

**Comment by luke-jr** [comment]
Right

**Comment by Diapolo** [comment]
utACK

**Comment by laanwj** [comment]
ACK for @theuni's trivial-next tree, better to file these at his github directly https://github.com/theuni/bitcoin

**Comment by faizkhan00** [comment]
utACK

**Comment by sandakersmann** [comment]
ACK

**Comment by fanquake** [comment]
ACK

**Pull request closed without merging**
