### PR TITLE
Use list initialization (C++11) for maps/vectors instead of boost::assign::map_list_of/list_of

### PR DESCRIPTION
**Pull request by practicalswift**
Use list initialization (C++11) for maps/vectors instead of `boost::assign::map_list_of`/`list_of`.

### CODE REVIEW

**Comment by sipa** [comment]
Concept ACK ACK ACK

**Comment by MarcoFalke** [comment]
Seems closely related to #10477

**Comment by practicalswift** [comment]
@MarcoFalke Ah, that one seems to tackle a subset of the issues found in one specific file (`src/chainparams.cpp`). This PR fixes the entire code base.

**Review by dcousens — APPROVED** [review]

**Comment by laanwj** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/10545/commits/3fb81a8480582d96e8c87ef1b963a11c55064d57, looks a lot better like this.

**Comment by jonasschnelli** [comment]
Finally.
utACK 3fb81a8480582d96e8c87ef1b963a11c55064d57

**Comment by paveljanik** [comment]
compilesACK 3fb81a8

Looks good!

**Pull request merged**
