### PR TITLE
msvc: scripted-diff: Remove NDEBUG pre-define in project file

### PR DESCRIPTION
**Pull request by ken2812221**
Follow #15391

### CODE REVIEW

**Comment by fanquake** [comment]
cc @sipsorcery

**Comment by sipsorcery** [comment]
@ken2812221 isn't `NDEBUG` desirable for msvc release builds?  Without it `assert` statements will terminate the programs.

**Comment by ken2812221** [comment]
You can't build it after #15391 merged. The CI pass because I disabled them by the appveyor.yml

**Comment by sipa** [comment]
@sipsorcery If an assertion is false, aborting is often far better than the alternative (with assumptions violated, we may accept an invalid chain for example...).

**Comment by trebliw5** [comment]
http://www.trebliw5@gmail.comtrebliw5@gmail.com

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by MarcoFalke** [comment]
How could this compile locally, but then suddenly stop to compile with #15391, given that we have the same compile time check in validation.cpp?

**Comment by ken2812221** [comment]
Maybe @sipsorcery just delete them in libbitcoin_server.vcxproj in his first PR?

**Comment by sipsorcery** [comment]
tACK 8a1f0a38d4a7cef544001e86c569bde747db2ecb 3ec56bea0d7b36bef2b6c7095ecd7d9fb43a3631.

@MarcoFalke if your comment was for me then I didn't have any problems compiling with msvc before or after this PR. Instead I was just having a little moan about the unfriendly way asserts terminate bitcoin-qt. But that decision was made by a wiser person(s) than me so I'll track down the root cause instead.

**Pull request merged**
