### PR TITLE
refactor: make some BlockManager members const

### PR DESCRIPTION
**Pull request by promag**
These methods can be const so make them const 🤷

### CODE REVIEW

**Comment by fanquake** [comment]
See also #25673, which came with the CI check.

**Comment by promag** [comment]
@fanquake d0efa0c4537b65c0f8ec12d4d9df56df3f9e1283 is the motivation for this change, making `blockman` usage const.

**Comment by TheCharlatan** [comment]
Concept ACK

It won't make a difference to any callers of the `BlockManager`, but I think you could mark `FlushUndoFile` as `const` as well.

**Comment by achow101** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.

**Pull request closed without merging**
