### PR TITLE
test: Assert on correct variable

### PR DESCRIPTION
**Pull request by kallewoof**

### CODE REVIEW

**Comment by laanwj** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/12918/commits/bf08fc5b6bcfdb5d0f6b049c802a768284916d6b

**Comment by practicalswift** [comment]
utACK bf08fc5b6bcfdb5d0f6b049c802a768284916d6b

**Comment by Empact** [comment]
utACK bf08fc5

**Comment by promag** [comment]
utACK bf08fc5.

**Pull request merged**
