### PR TITLE
remove unneded include from rpcserver.cpp and rpcclient.cpp

### PR DESCRIPTION
**Pull request by Diapolo**

### CODE REVIEW

**Comment by MarcoFalke** [comment]
utACK

**Comment by laanwj** [comment]
Not sure about this. `rpcserver` and `rpcclient` clearly depend on univalue, so this will just make the dependencies more fuzzy.

**Comment by paveljanik** [comment]
You can ping-pong this include between in `.cpp` and `.h` or have them in both. But who cares? Do we have a recommendation for developers?

This and all similar issues are a form of DoS on Bitcoin Core development IMO.

**Comment by dcousens** [comment]
NACK

**Comment by laanwj** [comment]
> This and all similar issues are a form of DoS on Bitcoin Core development IMO.

Agree. NACK, closing.

**Comment by Diapolo** [comment]
Guys let another one take care of small stuff like this, my passion is currently over, thanks.

**Comment by sipa** [comment]
@paveljanik The intention is that every file #includes all headers which it
uses things from, even if that dependency was already indirectly #included
through one of its other dependencies.

A .c file's corresponding .h file is an exception, as they are considered
to be one unit. #includes in the .h file do not need to be repeated in the
.c file in that case.

**Comment by laanwj** [comment]
> A .c file's corresponding .h file is an exception, as they are considered to be one unit. #includes in the .h file do not need to be repeated in the .c file in that case.

Absolutely - it's not necessary, the compilation unit inherits from its own header. But there's nothing wrong with including a dependency headet in both the .h and .c. Compilers will remember which files were already included (and which have the proper `#ifdef` guard) and won't read them again. So changes like this are a no-op. And I don't think it makes things more readable. It's just not a change worth making IMO.

**Pull request closed without merging**
