### PR TITLE
[REST] JSON support for /rest/headers

### PR DESCRIPTION
**Pull request by jonasschnelli**
also includes REST documentation update for /rest/headers

### CODE REVIEW

**Comment by fanquake** [comment]
Needs rebase

**Comment by jonasschnelli** [comment]
Rebased.
I still think it would make sense to merge this. At least it would add documentation for rest/getheaders (which currently is missing). I could also try to split of the documentation change for separate pull-in.
The JSON support for getheaders would round off/complete the json/bin/hex output support.

**Comment by jgarzik** [comment]
Code appears correct...  I just wonder who would use JSON header queries.

**Comment by jonasschnelli** [comment]
@jgarzik couldn't we ask the same for json blocks? I just think we should have consistent output support over all rest calls.

**Comment by laanwj** [comment]
Well at least blocks contain transactions. None of the information in headers is that useful in itself, and don't you get a similar view with `/rest/block/notxdetails/`?

**Comment by jonasschnelli** [comment]
IMO JSON output support is for users who don't like to deserialize data. `/rest/block/notxdetails/` does not allow one to retrieve multiple blocks/headers at one time. Thats why there is a `/rest/getheaders` call. It looks somehow bad if we have only one rest call without JSON support and users there need to deserialize data (which mean the need a library or have to lear more about the protocol).

**Comment by laanwj** [comment]
Yes, I understand the purpose but I'm with @jgarzik in wondering why anyone would use this, as the header has very little informational value outside its (hashable, unmalleable) binary representation. But I'm not strongly against it either it's not a lot of code.

**Comment by laanwj** [comment]
utACK

**Comment by paveljanik** [comment]
ACK (I was about to add the missing /rest/headers documentation ;-)

**Comment by jonasschnelli** [comment]
Yes. This PR also includes the missing docs for already merged rest headers call (it's a separate commit).

**Comment by laanwj** [comment]
After #6247 this can use the existing BlockHeaderToJSON (see my comment about overlap there)

**Comment by jonasschnelli** [comment]
Rebased and make use of the `UniValue blockheaderToJSON(const CBlockIndex* blockindex)` from #6247.

**Comment by laanwj** [comment]
ACK

**Pull request merged**
