### PR TITLE
Stratum v2 Template Provider (take 2)

### PR DESCRIPTION
**Pull request by Sjors**
Based on on @Fi3's https://github.com/bitcoin/bitcoin/compare/master...Fi3:bitcoin:PatchTemplates which is based on @ccdle12's #27854. I rebased it and re-wrote the commit history. See the original branch for the evolution of the spec.

See [docs/stratum-v2.md](https://github.com/Sjors/bitcoin/blob/2023/11/sv2-poll/doc/stratum-v2.md) for a brief description of Stratum v2 and the role of Bitcoin Core in that system..

## What to test and review? 

- [ ] #29295 
- [ ] Custom signet mining improvement: #29032
- [ ] Make nested pull-requests easier: #29274

See the [testing guide](https://github.com/Sjors/bitcoin/blob/2023/11/sv2-poll/doc/stratum-v2.md#testing-guide) for various ways to test this PR. This branch is actively used by (testnet) pools, so it should be ready for high level review.

I'll make separate pull requests for parts that are ready for detailed review. Probably starting with ECDH and the Noise Protocol.

## Implementation notes

Silent Payments also needs the ECDH module, so I cherry-picked the commit from #28122. It uses ECDH is a slightly different way, but perhaps there's more overlap to be had.

## Contributing

If you want to help out with any of the issues below, please open a PR to my fork. I will then squash your commits into my own where needed. 

### Spec

- [ ] modify spec to use `ProvideMissingTransactions`? (followup?)
- [ ] pick a good default for `default_coinbase_tx_additional_output_size` (see `getblocktemplate` RPC)

### Noise

- [ ] use EllSwift https://github.com/stratum-mining/sv2-spec/pull/66, implemented in https://github.com/Sjors/bitcoin/pull/28
- [ ] certificate signing issue: https://github.com/stratum-mining/stratum/issues/717, fix in https://github.com/Sjors/bitcoin/pull/29

### Networking

- [ ] add `-sv2bind` and `-sv2allowip`
- [x] persist static key (needs #29229)
- [ ] optional `-sv2cert`
- [x] create `Sv2Transport` subclass similar to `V2Transport`: https://github.com/Sjors/bitcoin/pull/27
- [ ] drop `Sv2TemplateProvider::SendBuf`, reuse p2p socket handling if possible
- [ ] limit number of connected clients
- [ ] maybe limit (number of) `coinbase_output_max_additional_size`
- [ ] TMP / TODO comments at the top of `sv2_messages.h`
- [ ] adjust base58 encoding of authority public key https://github.com/stratum-mining/stratum/issues/721

### Testing

- [ ] expand sv2_template_provider_tests
- [ ] add transport fuzzer
- [ ] add template provider fuzzer

### Template generation and updating

- [x] hold on to templates a bit after a block is found https://github.com/stratum-mining/stratum/issues/709 (in case of race to prevent downstream crashes, though we still wouldn't relay it without additional changes)
- [ ] hold on to template transactions even if the mempool drops them (for some time)
- [ ] group templates with the same `coinbase_tx_additional_output_size`
- [ ] don't generate templates when no client is connected

### Misc

- [ ] move / refactor `GetMerklePathForCoinbase` helper (see Future Work in original PR, and https://github.com/stratum-mining/stratum/issues/567)
- [ ] truncate long trace messages

## Potential followups

- [ ] implement Noise protocol and mock client in Python, add functional tests (based on `test/sv2_template_provider_tests.cpp`)
- [ ] use process separation, e.g. a `bitcoin-tp` binary, see [multiprocess.md](https://github.com/bitcoin/bitcoin/blob/master/doc/design/multiprocess.md?plain=1)
- [ ] make template updates push based, on top of Cluster Mempool, see [docs/stratum-v2.md](https://github.com/Sjors/bitcoin/blob/2023/11/sv2-poll/doc/stratum-v2.md) (for new blocks it's already push based)
- [ ] push empty template for the next block (downstream can ignore or use, https://github.com/stratum-mining/sv2-apps/issues/8)
  - send prevhash for this template as soon as any new block arrives
- [ ] push optimistic template for the next block
  - send prevhash if and only if our template won (i.e. we got a `SubmitSolution` message)

### CODE REVIEW

**Comment by Sjors** [comment]
Rebased and fixed encoding mistake I made during rebase:

```diff
diff --git a/src/node/sv2_messages.h b/src/node/sv2_messages.h
index fd6974b998..d3b257c31c 100644
--- a/src/node/sv2_messages.h
+++ b/src/node/sv2_messages.h
@@ -533,11 +533,11 @@ struct Sv2SubmitSolutionMsg
         s >> m_template_id >> m_version >> m_header_timestamp >> m_header_nonce;
 
         // Ignore the 2 byte length as the rest of the stream is assumed to be
         // the m_coinbase_tx.
         s.ignore(2);
-        s >> TX_NO_WITNESS(m_coinbase_tx);
+        s >> TX_WITH_WITNESS(m_coinbase_tx);
     }
 };
```

Yes, the coinbase transaction has a witness.

**Comment by Sjors** [comment]
I moved `sv2_noise.h` and `sv2_messages.h` to `common` and `template_provider.h` to `node`.

**Comment by Sjors** [comment]
Ran clang-tidy locally to (hopefully) fix its remaining complaints. Included @Fi3's https://github.com/Sjors/bitcoin/pull/25 (plus additional header and test change) which drops the `CIPHER_CONFIRMATION` state, as per https://github.com/stratum-mining/sv2-spec/issues/60.

**Comment by Sjors** [comment]
I guess I didn't catch them all locally. Pushed a change to the last (linter commit). Also fixed the broken noise handshake test. Replaced `usleep` with `UninterruptibleSleep` to keep Windows happy.

@hebasto any idea how to handle `D:\a\bitcoin\bitcoin\src\common\sv2_noise.h(92,13): error C3646: 'WriteMsg': unknown override specifier `?

```cpp
class Sv2CipherState
{
public:
    Sv2CipherState() = default;
    ...
    ssize_t WriteMsg(Span<std::byte> msg);
```

**Comment by Sjors** [comment]
It's not easy being green, but including `compat.h` should fix the issue:

```cpp
// ssize_t is POSIX, and not present when using MSVC.
```

The CI fuzzer caught an overflow, so I added a guard against absurd `coinbase_output_max_additional_size` values. I have not tried the fuzzer myself yet, nor does it have complete coverage, so there may still be other issues.

**Comment by hebasto** [comment]
> @hebasto any idea how to handle `D:\a\bitcoin\bitcoin\src\common\sv2_noise.h(92,13): error C3646: 'WriteMsg': unknown override specifier `?

> It's not easy being green

Happy to see CI is green :)

**Comment by Sjors** [comment]
I renamed `-stratumv2` to `-sv2` and `stratumv2port` to `-sv2port`. Added `-sv2interval` (default 30 seconds) and `-sv2feedelta` (default 1000 sat) to control how often templates are updated.

**Comment by Sjors** [comment]
Integrated changes from https://github.com/Sjors/bitcoin/pull/26: further noise simplification, and chunking large messages. This requires https://github.com/Fi3/stratum-1/tree/UpdateNoise until it's merged into the dev branch. I also renamed `SendMsg` in `noise.h` to `WriteMsg`. And rebased.

**Comment by Sjors** [comment]
I moved chunking into `noise.h`, since the maximum message length of 65 KB is part of the protocol. I also dropped `ProcessMsg` handler in favor of handling handshake vs. regular transport more directly. Finally `SendBuf` is now called by `EncryptAndSendMessage` rather than by each message call site.

Main changes: 
* 945838fca264c8469e24d629a4552741dbbd4dda -> f08a10a892fc467dbf6037e0c73227822e9f698a
* fc0aa335dd3f3beba383a42f19f73822b4ad2d34 -> 028c286d9a38343d8240c62a67207681d024a326 
* f706dffba9cf7552b179607d8674ba40cdeecd62 -> 8424d9270c27dd0d453895d36de6e070f3f6cd65

**Comment by Sjors** [comment]
@Fi3 found the issue, fixed in a7f08e74428c4e5da62365d686e5c51c5afc959d

```patch
--- a/src/common/sv2_noise.cpp
+++ b/src/common/sv2_noise.cpp
@@ -56,11 +56,11 @@ void Sv2CipherState::EncryptMessage(Span<std::byte> input, Span<std::byte> outpu
     for (size_t i = 0; i < num_chunks; ++i) {
         size_t chunk_start = i * max_chunk_size;
         size_t chunk_end = std::min(chunk_start + max_chunk_size, input.size());
         size_t chunk_size = chunk_end - chunk_start;
         const auto encrypted_chunk_start = output.begin() + i * NOISE_MAX_CHUNK_SIZE;
-        std::copy(input.begin(), input.begin() + chunk_size, encrypted_chunk_start);
+        std::copy(input.begin() + chunk_start, input.begin() + chunk_start + chunk_size, encrypted_chunk_start);
```

**Comment by Sjors** [comment]
Hopefully fixed the "test each commit" CI. Added documentation, moved testing instructions from the PR descriptor to it. The doc now also explains how to test this PR with a custom signet - which so far seems the most practical approach, despite its many moving parts.

**Comment by Sjors** [comment]
Rebased and big refactor.

Introducing `Sv2Transport`, a subclass of `Transport` very similar to `V2Transport`. For the most part this abstraction works quite well, and should make it easy to review for people familiar with the v2 transport (BIP324) implementation.

There'a few pain points though, perhaps @sipa has thoughts on this?

1. `CNetMessage` and `Sv2NetMsg` can perhaps be united to a single base class, but there are differences: `Sv2NetMsg` does not need `std::string m_type`. This is why I ended up not implementing the override for `GetReceivedMessage()`

2. Similar to (1), `SetMessageToSend` expects `CSerializedNetMsg`, but we need to keep track of the the header separately (because it contains the message length). So I implemented `SetMessageToSend(Sv2NetMsg& msg)` instead.

3. (very minor): the `m_type` part of `GetBytesToSend` is not needed

4. `Sv2TemplateProvider::ThreadSv2Handler()` contains some copy-pasted stuff from `CConnman::SocketSendData`. Ideally I'd like to extract some common functionality from `CConnman` that deals with sockets (and maybe also memory use checking, though I think that's less of an issue for sv2).

Another implementation thing to consider, though I think that can wait until I start splitting this into separate PR's, is that I'm trying to organise the code in such a way that putting the sv2 Template Provider in a separate process will be relatively straightforward to do as a followup. One of the goals of the sv2 project is for template providers to run as a public service. Multiple changes to this PR are needed to do that safely, but one thing that should help is (eventually) moving it out of the node process, so that worst case only the TP crashes.

In particular I've been moving stuff so that `Sv2Transport` has no dependency on `Node`, by moving `Transport`, `CSerializedNetMsg` and `CNetMessage` out of `net.cpp`. `Sv2TemplateProvider` does, but very little (mostly `miner.h`). 

Biggest changes:
* ceef59cbb029a36bbb9cb3414e8a4c2d4dcf0652 -> 77987c6292171151e574017079b1644dca0d2efd
* 0764c5531a1d1b4020b97a22bf4449cf32365f37 -> 61cfd61e1472e9bc7019f6c637259ac6ad5821ef
* 2f7e02d45473e69d5dd8634d9f30e2d5875f7f2f

**Comment by Sjors** [comment]
I pulled #29032 into this branch to remove the need for branch-switching while testing on a custom signet.

**Comment by Sjors** [comment]
Added a (ephemeral) client id to the log so it's easier to figure out what's going on when there's multiple connections.

**Comment by Sjors** [comment]
(I plan to rebase this after some other stuff is merged)

**Comment by Sjors** [comment]
I opened a (draft) pull request for the Noise part of this: #29346

**Comment by Sjors** [comment]
Added two commits to stay in sync with SRI: https://github.com/stratum-mining/stratum/pull/742

Next week I'll try to rebase this on the latest #29346, which has diverged a bit.

**Comment by Sjors** [comment]
I rebased on top of #29346 and pushed the result to: https://github.com/Sjors/bitcoin/tree/2024/02/sv2-poll-ellswift

Once EllSwift lands on the SRI side (or if I make a revert commit for it) I'll update this PR.

**Comment by Sjors** [comment]
Added to `2024/02/sv2-poll-ellswift`: we now hold on to templates for 10 seconds after a new block arrives, in a case a miner was still working on it. The resulting block still wouldn't get broadcast.

**Comment by Sjors** [comment]
I added tests for `RequestTransactionData` to `2024/02/sv2-poll-ellswift`, including an RBF test. It seems that the node _does_ hold on to transaction data after an RBF. I don't know if that's because the block template has a p pointer, or if there's some other mechanism at play.

We'll need some way to limit the amount of memory that this can take up.

**Comment by Sjors** [comment]
This PR is superseeded by #29432.

**Pull request closed without merging**
