### PR TITLE
Tests: Create functional tests for coin selection

### PR DESCRIPTION
**Pull request by akankshakashyap**
Added functional test for coin selection which compare waste metric

### CODE REVIEW

**Comment by brunoerg** [comment]
You should change the file permission to 755 instead of 644.

**Comment by akankshakashyap** [comment]
> You should change the file permission to 755 instead of 644.

done.

**Comment by ishaanam** [comment]
Thanks for working on increasing test coverage, I would find it a bit easier to review this PR if you explained why a functional test is needed for this as opposed to extending the existing coin selection unit tests?

**Comment by Xekyo** [comment]
Concept NACK

In functional tests, we test whether outside calls to Bitcoin Core will receive sensible responses, treating all of Bitcoin Core as one black box. Functional tests are expensive to run in comparison to unit tests, because we spin up whole instances of the node for each test suite. Because functional tests are expensive, we want to use them when we are verifying that the whole system works correctly integrally. However overall, we would like to reduce the count of functional tests by converting them to unit tests to reduce the runtime of the functional tests when possible.

The coin selection functionality is a small, well-delineated part of the transaction building within the wallet code, with the waste metric itself being an even smaller subset thereof. The proposed tests are testing the current internal implementation logic of this small part of the wallet code by executing the whole stack of calls, but functionally, we could have a different internal implementation that would still produce valid, functionally equivalent transactions. I would second @ishaanam's question from above that the tests would be better situated in a unit test that specifically focuses on the waste metric and coin selection.

**Comment by fanquake** [comment]
Thanks for contributing changes, however there's no agreement that this is a good approach. Going to close this PR for now.

**Pull request closed without merging**
