### PR TITLE
build: Bump version to 0.16.2

### PR DESCRIPTION
**Pull request by theuni**
Missed for rc1. Might make sense to just jump to a quick rc2.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
utACK 4244dbddc4a92d869542a0b5c9f60b34ce905398

**Comment by ken2812221** [comment]
utACK 4244dbd

**Comment by MarcoFalke** [comment]
@laanwj , when you merge this locally, please reset your `0.16` branch to `20461fc`, then create a merge of (`20461fc` and `4244dbd`). This way the Tree-SHA512 will get added properly for all "leftmost" branch commits and merge commits without having to force push to the `0.16` branch.

**Comment by achow101** [comment]
utACK 4244dbddc4a92d869542a0b5c9f60b34ce905398

**Comment by sipa** [comment]
duhACK 4244dbddc4a92d869542a0b5c9f60b34ce905398

**Comment by laanwj** [comment]
> @laanwj , when you merge this locally, please reset your

Done. Thank you. I'm sorry for messing this up so badly.

**Pull request merged**
