### PR TITLE
refactor: Add params to node context

### PR DESCRIPTION
**Pull request by maflcko**
`EnsureParams(node)` and `Params()` are completely identical, but slowly removing the global `Params()` makes the code easier to reason about and easier to test.
Some places do not rely on the global, but pass around the params through deep call stacks. If the params are passed along with a node context, those could be removed, as just passing a node context should be sufficient.

I suggest that existing code stays as is, but whenever code is touched for other reasons, it could be updated to use `EnsureParams()`.

### CODE REVIEW

**Comment by practicalswift** [comment]
Concept ACK: less is more when it comes to globals

**Comment by MarcoFalke** [comment]
Going to reopen later

**Comment by MarcoFalke** [comment]
rebased

**Comment by MarcoFalke** [comment]
Going to reopen later

**Pull request closed without merging**
