### PR TITLE
test: Work around libFuzzer deadlock

### PR DESCRIPTION
**Pull request by maflcko**
Only required part is `symbolize=0`, but the other changes shouldn't hurt

### CODE REVIEW

**Comment by practicalswift** [comment]
Concept ACK

**Comment by MarcoFalke** [comment]
Force pushed from 8ef72437fb to fa39c8a3e8 to remove unrelated changes

**Comment by practicalswift** [comment]
cr ACK fa39c8a3e8f1090103468780d122a4cf4191bc13: patch looks correct

**Comment by Crypt-iQ** [comment]
Could also add UBSAN_OPTIONS to suppress complaints if running `--with-sanitizers=undefined`?

**Comment by MarcoFalke** [comment]
@Crypt-iQ I did that in 8ef7243 but decided to tackle it in a follow-up pull

**Comment by Crypt-iQ** [comment]
@MarcoFalke My bad, for some reason I didn't see that.

**Pull request merged**
