### PR TITLE
[Wallet] Bugfix: Fundrawtransaction: don't terminate when keypool is empty

### PR DESCRIPTION
**Pull request by jonasschnelli**
Right now, `CWallet::CreateTransaction()` has an assertion that ensures that a key could be retrieved from the keypool.

`fundrawtransaction` can run on an encrypted unlocked wallet (it actually doesn't sign). But, it can still fail because the keypool could be drained on a locked wallet.

Current master crashes in that case.

### CODE REVIEW

**Comment by gmaxwell** [comment]
utACK.

**Comment by MarcoFalke** [comment]
Tagged for 0.12 backport because I am able to reproduce on that branch:

```cpp
bin/bitcoin-0.12.1/bin/bitcoin-qt -regtest -datadir=/tmp 
bitcoin-qt: wallet/wallet.cpp:2107: bool CWallet::CreateTransaction(const std::vector<CRecipient>&, CWalletTx&, CReserveKey&, CAmount&, int&, std::string&, const CCoinControl*, bool): Assertion `ret' failed.
Aborted (core dumped)

**Comment by MarcoFalke** [comment]
utACK c24a4f5

**Review by doublek420 — APPROVED** [review]

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/commit/c24a4f5981d47d55aa9e4eb40294832a4d38fb80

What about new test case (failing in the master, OK here)?

**Comment by MarcoFalke** [comment]
Yes, agree with paveljanik, please add the trivial test case somewhere.

**Comment by jonasschnelli** [comment]
Added a commit with a test that ensures the new behaviour. Test will fail on master.

**Comment by MarcoFalke** [comment]
utACK 1a6eacbf3b7e3d5941fec1154079bbc4678ce861

**Comment by paveljanik** [comment]
Thank you @jonasschnelli.

Tested ACK 1a6eacb

Fails on master with
```
Initializing test directory /var/folders/65/fn0h49r55k7779vg1b_h461r0000gn/T/testyal7ogu7/50231
Mining blocks...
Assertion failed: (ret), function CreateTransaction, file wallet/wallet.cpp, line 2392.
Unexpected exception caught during testing: ConnectionRefusedError(61, 'Connection refused')
```

OK here.

**Comment by gmaxwell** [comment]
ACK.

**Comment by sipa** [comment]
utACK 1a6eacbf3b7e3d5941fec1154079bbc4678ce861

**Comment by MarcoFalke** [comment]
Backports:

* for 0.13 in #9347
* for 0.12 in #9211

**Pull request merged**
