### PR TITLE
Make fuzzer actually test CTxOutCompressor

### PR DESCRIPTION
**Pull request by sipa**
Fixes a small oversight in #9172.

### CODE REVIEW

**Comment by laanwj** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/9354/commits/5dd626a6d34331d1712f49ed164b7aa47a2d7ea7

**Comment by paveljanik** [comment]
Huh, sorry, I do not understand it 8)

What is the diff supposed to do? If it catches exception, 0 is returned. If it is OK, 0 is returned at the end. So what are we testing at all? Isn't this optimised out completely anyway?

**Comment by gmaxwell** [comment]
@paveljanik  It catches crashes and asserts and has, in the past, found actual bugs;  our deseralizers are already (hopefully!) all used in contexts where the surrounding code is catching their exceptions.

It isn't optimized out either because the compiler doesn't know about side effects of the functions (or their ability to hit asserts!) but it might be prudent to harden a little more against that.

**Comment by laanwj** [comment]
> What is the diff supposed to do? If it catches exception, 0 is returned. If it is OK, 0 is returned at the end. So what are we testing at all? 

It may make sense to return 1 in case of fail and 0 in case of success. That would make it possible for tools to distinguish between successful and failed parses, which is useful to find examples of "accepted" data to compare against another parser.

Not relevant to this pull, though.

> Isn't this optimised out completely anyway?

No, it's not.

**Pull request merged**
