### PR TITLE
msvc: Compile `test\fuzz\miniscript.cpp`

### PR DESCRIPTION
**Pull request by hebasto**
This PR resolves the remained point from the https://github.com/bitcoin/bitcoin/pull/29774#issuecomment-2028808614:
> What is the issue with the ... miniscript fuzz tests?

From the CI [log](https://github.com/bitcoin/bitcoin/actions/runs/8941546183/job/24562123707?pr=30031#step:29:234):
```
miniscript_script: succeeded against 721 files in 1s.
Run miniscript_script with args ['D:\\a\\bitcoin\\bitcoin\\src\\fuzz.exe', WindowsPath('D:/a/_temp/qa-assets/fuzz_seed_corpus/miniscript_script')]
miniscript_smart: succeeded against 1429 files in 2s.
Run miniscript_smart with args ['D:\\a\\bitcoin\\bitcoin\\src\\fuzz.exe', WindowsPath('D:/a/_temp/qa-assets/fuzz_seed_corpus/miniscript_smart')]
miniscript_stable: succeeded against 1871 files in 2s.
Run miniscript_stable with args ['D:\\a\\bitcoin\\bitcoin\\src\\fuzz.exe', WindowsPath('D:/a/_temp/qa-assets/fuzz_seed_corpus/miniscript_stable')]
miniscript_string: succeeded against 918 files in 3s.
Run miniscript_string with args ['D:\\a\\bitcoin\\bitcoin\\src\\fuzz.exe', WindowsPath('D:/a/_temp/qa-assets/fuzz_seed_corpus/miniscript_string')]
```

### CODE REVIEW

**Comment by hebasto** [comment]
Closing in favour of #28657.

**Comment by fanquake** [comment]
> Based on https://github.com/bitcoin/bitcoin/pull/28657.

**Comment by hebasto** [comment]
> > Based on #28657.
> 
> Can be rebased now.

Rebased and undrafted.

**Review by sedited — APPROVED** [review]
ACK 9155b733e153e799f09cc7f7e9199ad776b2cbb1

**Comment by emc99** [comment]
There is no file at test/fuzz/miniscript

**Comment by hebasto** [comment]
> There is no file at test/fuzz/miniscript

```
$ file src/test/fuzz/miniscript.cpp
src/test/fuzz/miniscript.cpp: C++ source, ASCII text
```

**Comment by hebasto** [comment]
Ported to the CMake-based build system in https://github.com/hebasto/bitcoin/pull/187.

**Comment by emc99** [comment]
Are you looking for someone to compile this file on msvc?

**Pull request merged**
