### PR TITLE
rpc: Properly deserialize txs with witness before signing

### LINKED ISSUE #18803: intermittent test failure "non-mandatory-script-verify-flag (Signature must be zero for failed CHECK(MULTI)SIG operation) (-26)"
https://travis-ci.org/github/bitcoin/bitcoin/jobs/680452476#L6107

### PR DESCRIPTION
**Pull request by maflcko**
Signing a transaction can only happen when the transaction has inputs. A transaction with inputs can always be deserialized as witness-transaction. If `try_no_witness` decoding is attempted, this will lead to rare intermittent failures.

Fixes #18803

### CODE REVIEW

**Comment by MarcoFalke** [comment]
This may have been introduced in commit 6b4f231f5f0f88690488c4da20ea1c180dbc4b19, in which case it needs backport to all currently supported, released versions of Bitcoin Core.

**Comment by MarcoFalke** [comment]
See also #15899

**Comment by laanwj** [comment]
Looks like this removes all the remaining `DecodeHexTx(…, …, true)` in non-test code, besides `fundrawtransaction`.

**Comment by achow101** [comment]
What happens if someone does try a 0 input tx with these? Ideally we would give a meaningful error, but I don't think we do.

**Comment by fanquake** [comment]
@MarcoFalke could you follow up with achows query:

> What happens if someone does try a 0 input tx with these? Ideally we would give a meaningful error, but I don't think we do.

**Comment by MarcoFalke** [comment]
@achow101 @fanquake thanks, adjusted error message

**Review by achow101 — COMMENTED** [review]
ACK 33330778230961cfbf2a24de36b5877e395cc596

**Comment by MarcoFalke** [comment]
@instagibbs / @ajtowns  as the author/reviewer of #17775 you might be qualified and interested in reviewing this

**Comment by ajtowns** [comment]
ACK 33330778230961cfbf2a24de36b5877e395cc596

Confirmed the RPCs changed are only worth calling if you have inputs, and the error message changes look okay.

**Comment by fanquake** [comment]
Being backported to 0.20 in #20166.

**Pull request merged**
