### PR TITLE
Change SIG_NULLFAIL => NULLFAIL.

### PR DESCRIPTION
**Pull request by richardkiss**
In ```src/test/script_tests.cpp``` the ```ScriptErrorDesc``` entries all take the form ```{SCRIPT_ERR_XXX, "XXX"}``` except for ```{ SCRIPT_ERR_SIG_NULLFAIL, "NULLFAIL" }```. This patch corrects this oversight.

### CODE REVIEW

**Comment by paveljanik** [comment]
NACK

What about "NULLFAIL" -> "SIG_NULLFAIL" to unify SCRIPT_ERR_SIG*?

**Comment by richardkiss** [comment]
I can submit a patch that goes the other way (NULLFAIL => SIG_NULLFAIL) if the consensus is that way is preferable. I'm agnostic.

**Comment by richardkiss** [comment]
See https://github.com/richardkiss/bitcoin/tree/feature/unify_sig_nullfail for a look at the other direction. This requires quite a few more changes.

**Comment by kallewoof** [comment]
`SIG_NULLFAIL` refers to the signature (not) being null, so shortening to `NULLFAIL` is NACK from me. Concept ACK on `NULLFAIL` -> `SIG_NULLFAIL`. There's also `SCRIPT_VERIFY_NULLFAIL` which I think should probably ideally be `SCRIPT_VERIFY_SIG_NULLFAIL`.

**Comment by richardkiss** [comment]
Submitted alternative pull request https://github.com/bitcoin/bitcoin/pull/9754

**Comment by fanquake** [comment]
Going to close this due to a few NACKs and not much other feedback. Will leave #9754 open.

**Pull request closed without merging**
