### PR TITLE
doc/release-notes: Various cleanups

### PR DESCRIPTION
**Pull request by luke-jr**
- Remove minor/obvious changes
- Clarify and document new options in "Minimum Fee Rate Policies"
- Attribution fixes
- Remove deprecation of miner priority sorting

### CODE REVIEW

**Comment by jnewbery** [comment]
NACK. You seem to have accidentally removed the part about priority transaction sorting for mining being deprecated in Core and being removed in the next major version.

**Comment by luke-jr** [comment]
Not accidentally, it's documented in the summary. There is no consensus to remove priority mining.

**Comment by sipa** [comment]
Please stop this, @luke-jr. I'm aware you dislike the removal of priority mining, but it seems the vast majority of contributors to the project agree it is pointless to maintain at this point.

**Comment by luke-jr** [comment]
@sipa I tried to find a compromise where nobody had to maintain it besides me, but certain people were stubborn and refused. So the status quo of "no consensus to remove" remains for now.

**Comment by sipa** [comment]
@luke-jr This is not a consensus change, and it's not up to you to block this. I absolutely respect that you want priority mining to remain available, but you'll have to do it in your own fork, or develop an external tool that implements it through `prioritizetransaction` RPC calls (which seems very useful in any case as an example).

**Comment by luke-jr** [comment]
@sipa I think [this comment](https://github.com/bitcoin/bitcoin/issues/9601#issuecomment-279600986) deserves proper consideration before any final decision is made. But in the case that priority is to be removed, how about simply adding to the current text, "Miners who wish to retain this feature should switch to Bitcoin Knots, where it will continue to be maintained and supported for the time being."?

**Comment by sipa** [comment]
@luke-jr Ok, I've commented.

> how about simply adding to the current text, "Miners who wish to retain this feature should switch to Bitcoin Knots, where it will continue to be maintained and supported for the time being."?

I disagree with recommending the use of software based on a feature we don't consider relevant ourselves.

**Comment by luke-jr** [comment]
I do consider it relevant, and even aside from that, it is up to miners to decide on their own if they consider it relevant, not to have information about its availability suppressed so they are forced out of using it.

**Comment by sipa** [comment]
> I do consider it relevant

That's fine, you can recommend whatever you like. But you can't decide alone what goes into Bitcoin Core's release notes.

**Comment by MarcoFalke** [comment]
Closing. This missed the deadline.

**Pull request closed without merging**
