### PR TITLE
Serialization improvements (minimal initial commits)

### PR DESCRIPTION
**Pull request by sipa**
This is a minimal subset of #10785 that still does *something*.

It adds a new saner serialization macro, which can be used in parallel with the old one. Then the addrdb code is converted to use this new macro.

I'll add follow-up PRs that add more functionality + converting of other modules as things get merged.

### CODE REVIEW

**Comment by fanquake** [comment]
Concept ACK - thanks for splitting this up. I've swapped out #10785 for this PR in the high-prio project.

**Comment by jamesob** [comment]
ACK 9250a087d2f450f37342010aea0a5d583eea508b ([`jamesob/ackr/17850.1.sipa.serialization_improvemen`](https://github.com/jamesob/bitcoin/tree/ackr/17850.1.sipa.serialization_improvemen))

Code looks good. I pulled locally, built, ran `make -j 4 check`.

<details><summary>Show signature data</summary>
<p>

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK 9250a087d2f450f37342010aea0a5d583eea508b ([`jamesob/ackr/17850.1.sipa.serialization_improvemen`](https://github.com/jamesob/bitcoin/tree/ackr/17850.1.sipa.serialization_improvemen))

Code looks good. I pulled locally, built, ran `make -j 4 check`.
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEEpm2+LMqPsWj2rAwWyrywS1A+5mgFAl4Pj6MACgkQyrywS1A+
5mjoVQ/8CY+CSMIvURlNx614LFfcBlsh5/pM9hyohAraovCiKXbhfJ53X0nuJmKn
AVYmXr72ArKlbtgvYfBD3x5+MpamQ1/WfDGpEHFaKwmjiowFi6B7On8eC3yHGwFf
jE0QjAvqekudhb4UOAJuKapKezW83jK+wwp86yWIm5b0vPEH1wgOg+Mlym/LICms
BAwV14OHrgMvzfJeXUg7w9QsjrMUWCmc/mdrYqehNbu9JDCXRPdplxH+H4Dr4kLm
Wem7Ts/buwns6rsM2JG1Sh5QmipNkXPLGW7klwqvJ1IojD1ruQ/DJgV4FeUyjRc5
4hSEJLn7HEyY+u7e2Sx/zEQOAHcmso+lpUxKT5toSq+YTml1WgHeUMtFi+r8fPMp
MpbscgzgNMB7v/D6X7pu1hZo1MlO/wAf/E/x57nLB7gidMLD4wsayrzYmkMf0Fg7
JM4zZRcWiA3kJV0EQSm0SwvvQbsuTKOasSNse3wspQwafpGjKoa0eCa0aZ1md5AJ
0cZiwQoSibM893e+b1hpXYC0/aF7oG+Nt1Dda2tX99SeMImtx8F09gu0NK2dQcM0
bguCw1XiMCpHLfTjpozuVdoWOVU9r9JhBTjLR5D/jhh5/MOeA73lLCIPG22/GVsg
rf3kikt9Q0TSWiVicuhGav+E/4/lWsE0DRwNiQCmgSGcaQ82Qlw=
=m98m
-----END PGP SIGNATURE-----

```

</p></details>

**Comment by jamesob** [comment]
BTW, #10785 is an anagram of this, its replacement, #17850. Threw me for a loop there for a second.

**Comment by promag** [comment]
@jamesob and you think it's a coincidence? 

Concept ACK.

**Comment by sipa** [comment]
> BTW, #10785 is an anagram of this, its replacement, #17850.

Same digits, but serialized differently.

**Comment by kallewoof** [comment]
ACK 9250a087d2f450f37342010aea0a5d583eea508b

**Comment by practicalswift** [comment]
Concept ACK

**Comment by laanwj** [comment]
code review ACK 9250a087d2f450f37342010aea0a5d583eea508b

**Pull request merged**
