### PR TITLE
[RPC] getmempoolinfo mempoolminfee is a BTC/KB feerate

### PR DESCRIPTION
**Pull request by instagibbs**

### CODE REVIEW

**Comment by ryanofsky** [comment]
ACK f128f78ddbb2be70ddf8542e47ede83b9f57046a

**Comment by paveljanik** [comment]
ACK f128f78

**Comment by fanquake** [comment]
utACK f128f78

**Comment by kallewoof** [comment]
utACK f128f78ddbb2be70ddf8542e47ede83b9f57046a

**Pull request merged**
