### PR TITLE
TRIVIAL: Fix typo

### PR DESCRIPTION
**Pull request by paveljanik**
exectuable -> executable

### CODE REVIEW

**Comment by Diapolo** [comment]
ACK

**Comment by fanquake** [comment]
Could you combine this with #5602 ? Rather than opening multiple pull requests just to fix typos.

**Comment by Michagogo** [comment]
BTW, for things like this if you add [skip ci] or [ci skip] in the commit message, it'll save Travis the trouble of going and building and testing the software again for something like this.

**Comment by laanwj** [comment]
@michagogo good idea

**Comment by laanwj** [comment]
This is part of @theuni's trivial tree (https://github.com/theuni/bitcoin-trivial/commits/trivial-rebase) and will be merged via that route, so closing this pull.

**Pull request closed without merging**
