### PR TITLE
build: Require python 3.5

### PR DESCRIPTION
**Pull request by maflcko**
Python 3.4 is EOL after March 2019, so switch to 3.5. See https://devguide.python.org/#status-of-python-branches

This pull does the following in a bunch of commits:
* scripted diff to use the `bytes::hex()` method in place of previous wrappers (`b2x`, `bytes_to_hex_str`, `hexlify`, ...)
* Update the build system (gitian and travis) to remove python2.7 and replace it with python3.5
* Another scripted-diff to remove brackets after `assert`. This is unrelated to the python3.5 switch, but a stylistic commit, so probably not worth to split up. The motivation behind it is to avoid asserting on data structures (such as tuples of length one), which never fails:
```py
>>> assert(False,)   # with brackets
>>> assert False,    # without brackets
SyntaxError: invalid syntax
>>> assert False     # proper assertion
AssertionError
```
* And then a final scripted diff to update the copyright headers in the `test` subfolder, since I touched most of the files anyway and it wouldn't make sense to split this commit out into a separate pull.

For reference (contributed by luke-jr):

Ubuntu LTS (bionic): 3.6.5
Debian stable (stretch): 3.5.3
RHEL 8 (expected before v0.19): 3.6.x
Gentoo stable: 3.6.5
Arch: 3.7.1

### CODE REVIEW

**Comment by luke-jr** [comment]
For reference:

Ubuntu LTS (bionic): 3.6.5
Debian stable (stretch): 3.5.3
RHEL 8 (expected before v0.19): 3.6.x
Gentoo stable: 3.6.5
Arch: 3.7.1

**Comment by jnewbery** [comment]
Concept ACK. Release notes for 3.5 are here: https://docs.python.org/3/whatsnew/3.5.html . I think for this project, the most interesting new features could be:

- [Type hints](https://docs.python.org/3/whatsnew/3.5.html#whatsnew-pep-484)
- [Coroutines with async and await syntax](https://docs.python.org/3/whatsnew/3.5.html#whatsnew-pep-492)

**Comment by practicalswift** [comment]
Concept ACK

**Comment by fanquake** [comment]
Concept ACK. 
+1 on being able to start using [Type Hints](https://docs.python.org/3/whatsnew/3.5.html#pep-484-type-hints).

**Comment by Sjors** [comment]
Concept ACK

**Comment by MarcoFalke** [comment]
@jnewbery You might be interested in reviewing this, since it removes some python2.7 leftovers from  "Remove Python2 support" in #11881

**Comment by jnewbery** [comment]
Looks good. I especially like _scripted-diff: test: Remove brackets after assert_  :100: Is there a flake warning we can add to enforce in that in future?

This is for inclusion in v0.19, so I'll review after v0.18 is forked.

**Comment by MarcoFalke** [comment]
Rebased

**Comment by practicalswift** [comment]
utACK faa7cdf764a651975fa3c780df7df206a08254c2

**Comment by Sjors** [comment]
tACK faa7cdf except PyEnv needs a full version number, i.e. `3.5.6`. With that, I was able to run `make check` and the functional test suite on macOS 10.14.3, but I didn't try the various linters and other tools.

**Comment by Sjors** [comment]
utACK dddd1d0. Travis failure on `p2p_invalid_messages.py` seems spurious.

**Comment by jnewbery** [comment]
> Travis failure on p2p_invalid_messages.py seems spurious.

I restarted the job.

**Comment by practicalswift** [comment]
utACK dddd1d05d3df06865f5e0b1442d7425c0955de4e

**Comment by Sjors** [comment]
tACK fa27978. It's a new commit on top of dddd1d0, not a rebase; the force push only replaced an earlier version of that new commit.

**Pull request merged**
