### PR TITLE
Replaced current function names with __func__ in LogPrintf() calls.

### PR DESCRIPTION
**Pull request by ghost**
This patch replaces the name of the current function with '**func**' in LogPrintf() calls.

### CODE REVIEW

**Comment by paveljanik** [comment]
minor NIT: please remove `()` where used without contents inside. It is clear that it is the function name, thus `()` are not needed - three instances of it (search for the string `():`).

**Comment by laanwj** [comment]
Looks good to me, should probably go into the trivial branch @cfields

**Comment by jgarzik** [comment]
ut ACK -- should go in trivial tree

**Comment by nbenoit** [comment]
Thanks for looking at it, I added a second patch to address @paveljanik remark.

**Comment by theuni** [comment]
This has been merged into the trivial tree and can be closed. It will be merged into master with the next trivial sync.

**Pull request closed without merging**
