### PR TITLE
Backport: [rpc] Remove the addresses field from the getaddressinfo return object

### PR DESCRIPTION
**Pull request by jnewbery**
Backport #15750

### CODE REVIEW

**Comment by MarcoFalke** [comment]
The backport should include the metadata. You may use a script to do it for you: https://github.com/bitcoin-core/bitcoin-maintainer-tools#backport

**Comment by jnewbery** [comment]
Which metadata am I missing? I'd rather not do another merge resolve for this.

**Comment by MarcoFalke** [comment]
The backport should include the metadata:

```
Github-Pull: #num
Rebased-From: commit_id
```

Of course, you can also add it manually

**Comment by jnewbery** [comment]
Added metadata manually

**Comment by MarcoFalke** [comment]
ACK b3a04c963d4e761b66a1a8c1aae1c835534e47eb (checked cherry-pick)

**Comment by MarcoFalke** [comment]
Merged. Please adjust the release notes (if necessary) https://github.com/bitcoin-core/bitcoin-devwiki/wiki/0.18.0-Release-Notes-Draft

**Comment by jnewbery** [comment]
> Please adjust the release notes

Done: https://github.com/bitcoin-core/bitcoin-devwiki/wiki/0.18.0-Release-Notes-Draft/_compare/8469ba7665054b8066725dc41ceb0206d9a0bad5...74a36c9a0f5a45a7950f7e40d4de5cb3fcee42b3

**Pull request merged**
