### PR TITLE
add (max)uploadtarget infos to getnettotals RPC help

### PR DESCRIPTION
**Pull request by jonasschnelli**

### CODE REVIEW

**Comment by sipa** [comment]
utACK

**Comment by jonasschnelli** [comment]
Same sample output to judge the formatting:
bildschirmfoto 2015-11-12 um 14 43 01

**Comment by paveljanik** [comment]
There are two `{` on uploadtarget` line.

**Comment by paveljanik** [comment]
Boolean entries are described differently in the other help texts.

**Comment by jonasschnelli** [comment]
Thanks for the review.
Fixed the double "{" and the description for the booleans.

**Comment by paveljanik** [comment]
The output here looks like this:
```
{
  "totalbytesrecv": 7718519,
  "totalbytessent": 56670,
  "timemillis": 1447337892394,
  "uploadtarget": {
    "timeframe": 86400,
    "target": 0,
    "target_reached": false,
    "serve_historical_blocks": true,
    "bytes_left_in_cycle": 0,
    "time_left_in_cycle": 0
  }
}
```
Please note the position of `{` in `uploadtarget` - it is on the same line. Can you move it there also in the helptext?

And this was the last nit.

ACK

**Comment by instagibbs** [comment]
Meta-comment: if #6984 gets merged I'd want to know that whitelisted peers existed and I was serving historical blocks to them.

**Comment by laanwj** [comment]
> Would it hurt just to add "bytes" to "target"? aka "targetbytes"
> Everything else has bytes in the field name.

Hah, yes, we could comment many things on consistency in the RPC interface. Some things have _ separators some have words written together, there are even a few camelCases here and there.

@jonasschnelli Thanks for documenting it though - as it is.

**Comment by gmaxwell** [comment]
utACK

**Comment by gmaxwell** [comment]
ACK.

**Comment by dcousens** [comment]
ACK

**Pull request merged**
