### PR TITLE
'internal' loop's variable hides a function's parameter of the same name

### PR DESCRIPTION
**Pull request by n0feer**
Pretty clear. Just semantic change so the code in the following section would be open to changes, and less confusing.

### CODE REVIEW

**Review by luke-jr — COMMENTED** [review]
Would prefer a new name that indicates what it actually is for

**Comment by n0feer** [comment]
Yeah I agree that it’s not a good name. I think it’s better to just call it boolean_value or i. Do you have a better idea @luke-jr?

**Comment by luke-jr** [comment]
I suggest `active_internal`, and while you're at it, make the inner loop `active_type`

**Comment by n0feer** [comment]
@luke-jr Good idea. I renamed it. Regarding the `active_type` variable, should I just change `bool` to `active_type` and consider it in the if statement (line 3213)?

**Comment by luke-jr** [comment]
Not sure what you're asking. I was just suggesting renaming the `t` variable to `active_type`

**Review by luke-jr — APPROVED** [review]
utACK

**Comment by n0feer** [comment]
Ok, I renamed it as you suggested. It would be cool if you can review the code once again. thnx

**Review by luke-jr — APPROVED** [review]
re-utACK

**Comment by fanquake** [comment]
Needs commits squashed, proper commit message, PR title updated etc.

**Comment by S3RK** [comment]
JFYI #19651 will drop this cycle

**Comment by fanquake** [comment]
@n0feer thanks for the contribution here, but I'm going to close this PR in favour of #19651, as that is pretty much mergable. If you'd like to make another contribution, a good place to start is the [good first issue list](https://github.com/bitcoin/bitcoin/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).

**Pull request closed without merging**
