### PR TITLE
Remove min reasonable fee

### PR DESCRIPTION
**Pull request by morcos**
This builds off of #9380...  It's just a cleanup PR and should be no change in functionality.

Previously the minReasonableRelayFee which was passed through CTxMempool to CBlockPolicyEstimator was just getting its statically initialized value of DEFAULT_MIN_RELAY_TX_FEE so this PR shortcuts passing it through for no reason.

It's perfectly fine to have a smaller min bucket feerate in fee estimation, it is just slightly less space efficient.  However changing this number invalidates old fee estimate files..  So we change the hardcoded minimum rate to be the same rate that was being passed in previously (1000 from DEFAULT_MIN_RELAY_TX_FEE) and we can worry about changing it in the future if that ever becomes not small enough.

@theuni

### CODE REVIEW

**Comment by morcos** [comment]
rebased

**Comment by theuni** [comment]
utACK ad82cb06cecf84c4f9e5647b404b7eb19f1e9bf3.

To help other reviewers: The mempool previously accepted an argument that appeared to be coming from the "-minrelaytxfee" option, but in reality (as @morcos said above) the CTxMempool had already been statically created with DEFAULT_MIN_RELAY_TX_FEE before the option was parsed: https://github.com/bitcoin/bitcoin/blob/master/src/validation.cpp#L86

**Comment by MarcoFalke** [comment]
ACK ad82cb0

**Comment by TheBlueMatt** [comment]
utACK ad82cb06cecf84c4f9e5647b404b7eb19f1e9bf3.

**Comment by ryanofsky** [comment]
utACK ad82cb06cecf84c4f9e5647b404b7eb19f1e9bf3

**Review by gmaxwell — APPROVED** [review]
utACK.

**Pull request merged**
