### PR TITLE
libevent http fixes

### LINKED ISSUE #6660: bitcoind exits with SIGPIPE after Ctrl+C in bitcoin-cli
Current master, OS X self built.

`bitcoind` exits after I press Ctrl+C in the other terminal after running the command

```
bitcoin-cli getrawmempool true
```

The output of the command is quite large right now... When I press Ctrl+C, the `bitcoind` running in the other terminal window will exit. The exit code is 141 (141-128 = 13, SIGPIPE).

When the mempool gets large enough, ie. cca 30000 txs, I can reproduce with cca 30% probability.

Looks like new `libevent` based webserver doesn't handle SIGPIPE correctly.

### PR DESCRIPTION
**Pull request by laanwj**
Fix a few rough edges discovered in use of the new libevent http server:;
### init: Ignore SIGPIPE

Ignore SIGPIPE on all non-win32 OSes, otherwise an unexpectedly disconnecting
RPC client will terminate the application. This problem was introduced
with the libhttp-based RPC server.

Fixes #6660.
### http: Disable libevent debug logging, if not explicitly enabled

Add a option "-debug=libevent" to enable libevent debugging for troubleshooting.
Libevent logging is redirected to our own log.

Addresses stdout spew in #6655.
### rpc: Split option -rpctimeout into -rpcservertimeout and -rpcclienttimeout

The two timeouts for the server and client, are essentially different:
- In the case of the server it should be a lower value to avoid clients
  clogging up connection slots
- In the case of the client it should be a high value to accomedate slow
  responses from the server, for example for slow queries or when the
  lock is contended

Split the options into `-rpcservertimeout` and `-rpcclienttimeout` with
respective defaults of 30 and 900.

Should fix, or make it possible to fix timeout issues in #6655.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
utACK (plans to test this soon).
Not sure about the insides of `getblocktemplate`, but hows does the rpctimeout affect the long poll?

**Comment by laanwj** [comment]
> Not sure about the insides of getblocktemplate, but hows does the rpctimeout affect the long poll?

On the server side it doesn't affect that - it doesn't spend time waiting for input from the client. 
On the client side, the request will time out if the reply takes longer than `rpcclienttimeout`.

**Comment by morcos** [comment]
Unfortnately I'm 0/2 on testing these.  I couldn't recreate the SIGPIPE issue, in master or here, so thats's a start.  But I still get what looks like a timeout from getblocktemplate_longpoll.py  and I still get errors spewed to stdout when I don't have an IPv6 address.

**Comment by laanwj** [comment]
From IRC:
```
<morcos> regarding the rpc timeouts..  before 6695, you could fix the problem by starting the bitcoind's in the python tests with -rpctimeout=1500 (or whatever)
<morcos> doesn't that imply that somehow it was the timeout on the server end that was the problem?
```
Looks like the issue is not in bitcoin-cli but in the python http functionality that cannot cope with disconnects between requests (as said by @sdaftuar ). Which would be strange, but I'll take a look at it.

**Comment by laanwj** [comment]
The `rpcbind.py` test hang in #6655 is caused by bitcoin-cli being unable to connect to IPv6 IPs. Not sure why. Also not sure whether this affects all libevent versions. But I can reproduce it with libevent 0x02001500 on Ubuntu 14.04 (which is relatively ancient).

**Comment by jonasschnelli** [comment]
> SIGPIPE appears to be an OS X issue, which is why I couldn't recreate.

I could reproduce it on debian as well. Use a bitcoin-cli command like `getblocktemplate` or `getrawmempool` and enter `ctrl-C` short after sending-off the command. Very hard to reproduce (requires a few tries).
With a script it would probably easy.

The SIGPIPE gets emitted when bitcoind starts to write to a closed socket (ctrl-c will terminate bitcoin-cli which ends up in writing to a closed socket on the server side).

**Comment by morcos** [comment]
@laanwj I know I said I didn't care, but I tracked down the silly warning messages.  We need to call event_set_log_callback.  I tried it and it works.

screen shot 2015-09-18 at 6 11 17 pm

**Comment by dcousens** [comment]
concept ACK

**Comment by laanwj** [comment]
@morcos Ah, that'd allow redirecting the messages to our own log. That makes sense in addition to what is done here.

**Comment by laanwj** [comment]
The Python BadStatusLine on disconnect issue sounds like https://bugs.python.org/issue3566 "httplib persistent connections violate MUST in RFC2616 sec 8.1.4."

This was fixed in Python 3.5.

I've pushed a commit that should work around it.

**Comment by morcos** [comment]
ACK (modulo missing newlines)

**Comment by laanwj** [comment]
Fixed the newline issue (thanks @morcos), removed a spurious change in util.py

**Pull request merged**
