### PR TITLE
add ryanofsky to trusted-keys

### PR DESCRIPTION
**Pull request by ryanofsky**
For maintaining interfaces and other areas of the codebase. Some previous discussion in IRC meeting https://gnusha.org/bitcoin-core-dev/2023-05-04.log

### CODE REVIEW

**Comment by darosior** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK 59ebee3fb4181baf20fab263cf1b587ece1bd5e2 for adding ryanofsky as a maintainer.

I have not checked the key `4D1B3D5ECBA1A7E05371EEBE46800E30FC748A66`.
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEEWQtykmla/6W2csuy4T/BRc0/QwQFAmRZ+qsACgkQ4T/BRc0/
QwT3lQv/Qud7HqLisikdjcg7jrqa9YBS5j8CwFFIJW5TpY5zqLsm/7nI8RlkakRg
gvj1Ok92RTnhEGaleN/80Bco9uH5PEW+6V0tda5ZS/VqD4P0l3Jra9U0kvnTeWAR
aFRWCK14nelsU2+ccG0cf0yHnqrX3/jJGzINJzx2nJt1xDNVKxrkqahYSZfeNa3q
9CZdmxbVTswCyH9kkLdN8iSs80xcHufO+S11W14PtHd71vxzivAM/5MKb2FT0L3p
vQxQpw4mzPoM5QPr5zbtWsuGEAOT9OjbnrGVINsHXDJZEscJdLaNhNtJBsV7WM8U
25GYDMM4wW8V1KFlpaZpAyS6/J0kWh2ekgl7ZUjOTnQNqxKJMKDLwxLtb0Bm2OvA
2g2SES1kJ9h4fMYGc666zzicEem3ytnqADB/gR1pbFcYZINi1rB3xyqBw+lFeV/5
LinoM/DODXQSz6VIdeDOQvZCXN/6qwiroCx2QwqHndOFMNqPmRQI2LlwYdhtaE0m
dv9e3fmt
=KLkd
-----END PGP SIGNATURE-----

**Review by hebasto — APPROVED** [review]
ACK 59ebee3fb4181baf20fab263cf1b587ece1bd5e2

My local gpg output:
```
$ gpg --list-keys 4D1B3D5ECBA1A7E05371EEBE46800E30FC748A66
pub   rsa4096 2022-01-07 [SC] [expires: 2024-01-07]
      4D1B3D5ECBA1A7E05371EEBE46800E30FC748A66
uid           [ unknown] Ryan Ofsky <ryan@ofsky.org>
sub   rsa4096 2022-01-07 [E] [expires: 2024-01-07]

```

**Review by glozow — COMMENTED** [review]
ACK 59ebee3fb4181baf20fab263cf1b587ece1bd5e2

I feel that we need an "interfaces" maintainer with a deep understanding of our codebase's architecture (how it is and how it should be), particularly as we are working on several large projects spanning multiple subsystems and figuring out how to separate them. I believe @ryanofksy is this person, and generally a natural fit for having merge access because he is one of the most consistent and thorough reviewers on the project.

This key fingerprint matches what is in my keychain.

**Review by pinheadmz — APPROVED** [review]
ACK 59ebee3fb4181baf20fab263cf1b587ece1bd5e2

I verified the key fingerprint in meatspace with the human that I believe is, in fact, @ryanofsky. Confirmed fingerprint matches key that signed this commit.

ryanofsky will be a great maintainer, his reviews are excellent even on PRs that he doesn't agree with.

<details><summary>Show Signature</summary>

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

ACK 59ebee3fb4181baf20fab263cf1b587ece1bd5e2
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEE5hdzzW4BBA4vG9eM5+KYS2KJyToFAmRaT50ACgkQ5+KYS2KJ
yTpn0Q//edwpQ6qT/St2CsR3WBPJcUBb4PT5eNnVpaPTd1Y6J+dxtZ8G0kp4lLZY
t8tkzR1E7/idcX+QUVeRVhubfJEB0fgJWeK91Gx7c6v7fHLAoSLH3Zmcw5YE0fWK
gcbl3cjs3S6Yz1VZ3/b898Ol8hLNlQ1jDY3c4yEmDzbjddZIf9GHrqsgwh5//YwT
KLgXPboXKo86t3ON/2HROcS1eHoB9Q2hXe1tflEfQ2mXsYp1r3mW1wr0v9ovSyWD
Q+sbV7a7Q91yBXCmZOTVwLDhHIghDGhY2wtYbS1k5RTL7puDnosQJEax2/tSs3BZ
eFKxc0hmqjx9oJlzGmVoGi7wMVldxMRO2ZVfFCXq0tK7r9WH9tB4B7wVFStlujYW
QZho2DHE881Foho6vyduO1C3N+D0ZUV8YPIxGoxidSbxPNaO/62CQKJarw+sXmEY
qKNB5VHQgjoxO33MsqxWaECQHjt6/PCcF5lXUFe2vqulAc5wdSEXCKD72W7fqbQ5
rKpza4HNorynf+XRo0wO61FIOQTiKjKgeTdyLbmL9UGzwMJsiaDddlgTU1+XASCs
HKlRZne2a0HD90pDZ6AZelxynXtNCtyuexcvHTwmEZgmR2oVxdKBYonobkIHaAvR
ckvjnmX19HctxoaS8xTtIgqygH/3S6SGT7X5HBjySyRp88xUPag=
=3V8S
-----END PGP SIGNATURE-----
```

pinheadmz's public key is [on keybase](https://keybase.io/pinheadmz/pgp_keys.asc?fingerprint=e61773cd6e01040e2f1bd78ce7e2984b6289c93a)
</details>

**Review by stickies-v — APPROVED** [review]
utACK https://github.com/bitcoin/bitcoin/commit/59ebee3fb4181baf20fab263cf1b587ece1bd5e2

ryanofsky has consistently proven to be extremely skilled, thorough and helpful. Even though he's comfortable being opinionated, I always find his discourse respectful and well balanced. His PRs and reviews often serve as a benchmark for how things should be done, for me. I think he has the right attributes for being successful as a maintainer.

I cannot verify his key as I do not have it in my keyring. 

Thank you for taking this on, ryanofsky!

**Review by brunoerg — APPROVED** [review]
ACK 59ebee3fb4181baf20fab263cf1b587ece1bd5e2

Strongly agree on adding @ryanofsky on it.

**Review by theStack — APPROVED** [review]
ACK 59ebee3fb4181baf20fab263cf1b587ece1bd5e2

**Review by mzumsande — COMMENTED** [review]
ACK 59ebee3fb4181baf20fab263cf1b587ece1bd5e2

**Review by theuni — APPROVED** [review]
ACK 59ebee3fb4181baf20fab263cf1b587ece1bd5e2.

**Review by jarolrod — APPROVED** [review]
ACK https://github.com/bitcoin/bitcoin/commit/59ebee3fb4181baf20fab263cf1b587ece1bd5e2

**Comment by josibake** [comment]
post-merge ACK https://github.com/bitcoin/bitcoin/commit/59ebee3fb4181baf20fab263cf1b587ece1bd5e2

Solid track record of review and work on the project. Aside from the obvious fit for an interfaces maintainer, ryanofsky has a track record of thorough review and being able to clearly articulate his reasoning

**Comment by Sjors** [comment]
Concept ACK. I can't verify the PGP key.

**Comment by 0xB10C** [comment]
post-merge ACK

**Comment by Zero-1729** [comment]
Post merge ACK 59ebee3fb4181baf20fab263cf1b587ece1bd5e2

Verified key fingerprint checks out in my local keychain.

**Comment by jamesob** [comment]
ACK russ

**Comment by jamesob** [comment]
PO27970686-front-cu

I'm also unable to verify the GPG key.

**Comment by michaelfolkson** [comment]
For posterity: https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2023-May/021618.html

**Comment by michaelfolkson** [comment]
Also for posterity: https://gist.github.com/michaelfolkson/81df14508ed3ad3232da133e154d6873

The maintainer role was always supposed to be janitorial one and was not elevated above the many long term contributors on the project. A hundred(s) billion dollar ecosystem shouldn't depend on the whims of a small group of maintainers who refuse to engage on decisions that not only impact the project but potentially the entire ecosystem (currently valued in the hundreds of billions of dollars). The fact that I'm the only one here stating the obvious (as I was for the CTV activation chaos) is really scary to me. I'm hoping many of those long term contributors are involved in private discussions with the maintainers I'm not privy to. If they aren't they really should be as concerned as I am.

**Comment by stickies-v** [comment]
> The fact that I'm the only one here stating the obvious (...) is really scary to me.

Not to speak for anyone else, but perhaps the lack of engagement on your messages is because most regular contributors are just generally happy with the maintainer decisions and don't agree with your assessment but do not wish to keep discussing the same thing time and again?

**Comment by michaelfolkson** [comment]
> Not to speak for anyone else, but perhaps the lack of engagement on your messages is because most regular contributors are just generally happy with the maintainer decisions and don't agree with your assessment but do not wish to keep discussing the same thing time and again?

It is a failure of communication and process around both CTV (which could have resulted in a chain split disrupting a hundred(s) billion dollar ecosystem) and now the addition, rejection and removal of maintainers. If you and others don't think that stuff is important I don't know what to tell you. You are unfortunately completely missing the bigger picture. To assume Vasil and other long term contributors are happy with the situation is also a rather significant assumption.

**Pull request merged**
