### PR TITLE
doc: Merge release notes for 0.20.0 release

### PR DESCRIPTION
**Pull request by maflcko**
mostly move-only. Can be reviewed with the `--color-moved=dimmed-zebra` option.

### CODE REVIEW

**Comment by laanwj** [comment]
ACK fa8b6020ec9350c5ddf05018eb390ff565cefca3
I suppose after this we can move the draft 0.20.0 release notes to the wiki.

**Comment by MarcoFalke** [comment]
Yes, after feature freeze next week no more things should be merged into the release notes and we can put them on the wiki.

**Review by fanquake — APPROVED** [review]
ACK fa8b6020ec9350c5ddf05018eb390ff565cefca3 - any changes are basically headers and newlines.

**Comment by promag** [comment]
ACK fa8b6020ec9350c5ddf05018eb390ff565cefca3.

**Pull request merged**
