### PR TITLE
Enforce BIP 68 from genesis

### PR DESCRIPTION
**Pull request by maflcko**
Now that BIP 68 is active, it makes sense to enforce its rules on all blocks, even historic ones, regardless of the deployment status.

### Benefits:

* BIP 68 rules are applied for all blocks (even blocks not yet created). This may benefit static analysis, code review, and development of new script features that build on BIP 68.
* Any future bugs introduced in the deployment code won't have any effect on the BIP 68 rules, as they are independent of deployment.
* Enforcing the BIP 68 rules regardless of the deployment status makes testing easier because invalid blocks after activation are also invalid before activation. So there is no need to differentiate the two cases.
* It gives belt-and-suspenders protection against a practically expensive and theoretically impossible IBD reorg attack where the node is eclipsed. `nMinimumChainWork` makes this attack practically expensive. Also, this attack is currently theoretically impossible because no vector is known to inject a consensus-invalid transaction into the mempool (or even have it mined).

For reference, previously something similar was done for the script verification flags P2SH and WITNESS in commit 0a8b7b4b33c9d78574627fc606267e2d8955cd1c. (And is being done for TAPROOT in #23536).

### Considerations

Obviously this change can lead to consensus splits on the network in light of massive reorgs. Currently the last block before BIP 68 activation, that is the last block without the BIP 68 rules applied, is buried by a few months of POW. BIP90 considerations apply when looking at reorgs this large.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Please review #24565 first, while this stays in draft.

**Comment by ajtowns** [comment]
Doesn't seem to save much code, and requires revalidating years worth of blocks to ensure it doesn't break consensus. Not really seeing the point of this? Concept -1 from me.

**Comment by ajtowns** [comment]
Unlike #23536 I don't think this has much (any?) possible effect on wallet behaviour; bip68 only allows time locks up to ~15 months, and bip68 was ~68 months ago (slightly more than "a few months of POW"...), and unlike with taproot/segwit/p2sh any  transaction that is invalid right now due to bip68, will eventually become valid.

Also, any static analysis tool that can't cope with conditional consensus logic just doesn't seem suitable for use on the bitcoin codebase in the first place to me.

So still -1 from me; these sorts of unnecessary changes around consensus code seem far more likely to introduce bugs (as #24421 has) than prevent them.

**Comment by MarcoFalke** [comment]
If a BIP 68 violating tx makes it into the mempool in current `master` (or a previous release), `getblocktemplate` will refuse to create a block on the current main chain tip. This pull doesn't change that. It enforces BIP 68 rules on all blocks (past and future ones) and block templates. I think this is a motivation for the changes here, since a block template that includes a BIP 68 violation on current `master` will happily go through for blocks that will never end up in the main chain (built on a stale tip, see the unit test) and it will fail for blocks that are built on the current tip.

**Comment by ajtowns** [comment]
If you're relying on someone giving you a bip68-invalid tx to avoid building blocks with a tip that's over 5 years out of date, I think you've already lost...

**Comment by jnewbery** [comment]
> So still -1 from me; these sorts of unnecessary changes around consensus code seem far more likely to introduce bugs (as https://github.com/bitcoin/bitcoin/pull/24421 has) than prevent them.

24421 doesn't change consensus code, so I don't think it's a relevant comparison here. The bug introduced in that PR was a functional test simulating an impossible scenario.

**Comment by MarcoFalke** [comment]
I'll pick this up later

**Pull request closed without merging**
