### PR TITLE
contrib: macdeploy: make gen-sdk deterministic

### PR DESCRIPTION
**Pull request by prusnak**
This PR attempts to make `contrib/macdeploy/gen-sdk` deterministic

Can anyone with the `Xcode_12.2.xip` confirm that `gen-sdk` produces the same hash? => `e7ca56bc8804d16624fad68be2e71647747d6629cacaaa3de5fbfa7f444e9eae `

### CODE REVIEW

**Comment by fanquake** [comment]
Testing your branch @ 13a4a092dbeb3ec9a99398450941f4066dc92fcf:
```bash
shasum -a 256 Xcode_12.2.xip
28d352f8c14a43d9b8a082ac6338dc173cb153f964c6e8fb6ba389e5be528bd0  Xcode_12.2.xip
....
contrib/macdeploy/gen-sdk Xcode.app
Found Xcode (version: 12.2, build id: 12B45b)
Found MacOSX SDK (version: 11.0, build id: 20A2408)
Creating output .tar.gz file...
Adding MacOSX SDK 11.0 files...
Adding libc++ headers...
Done! Find the resulting gzipped tarball at:
Xcode-12.2-12B45b-extracted-SDK-with-libcxx-headers.tar.gz
...
shasum -a 256 Xcode-12.2-12B45b-extracted-SDK-with-libcxx-headers.tar.gz 
a396dd24f61fb55a6d3ec98b8b58fc0b04cdb6b2695039869d04105f885e0867  Xcode-12.2-12B45b-extracted-SDK-with-libcxx-headers.tar.gz
```

**Comment by prusnak** [comment]
> Testing your branch @ [13a4a09](https://github.com/bitcoin/bitcoin/commit/13a4a092dbeb3ec9a99398450941f4066dc92fcf):

How did you extract the xip file? Via `xip -x` or `apple-sdk-tools/extract_xcode.py` ?

**Comment by prusnak** [comment]
It seems the default TAR format has changed [from GNU to PAX in Python 3.8](https://docs.python.org/3/library/tarfile.html#tarfile.DEFAULT_FORMAT).

This is addressed by the change in 140f8e7831fc191f4981c4e681f501ef744a6129 which sets GNU format explicitly. The hash changed to `3829cc15df84680ea41ab470f572603408c285c3b72390660b7a37a43e890197`

**Comment by prusnak** [comment]
> This might be fixed by monkey-patching the `tarfile.TarInfo._create_header` function, but the change would not be very nice.

I monkey-patched the Python bug in ba30a5407e065e9d6dd037351e83f56a43f38f19.

The new deterministic hash should be `e7ca56bc8804d16624fad68be2e71647747d6629cacaaa3de5fbfa7f444e9eae` (confirmed on Linux with Python 3.9 and macOS with Python 3.8).

**Comment by hebasto** [comment]
Concept ACK.

**Comment by fanquake** [comment]
> The new deterministic hash should be e7ca56bc8804d16624fad68be2e71647747d6629cacaaa3de5fbfa7f444e9eae,

Nice. I'm now getting a matching hash.
```bash
➜  SDK ./contrib/macdeploy/gen-sdk Xcode.app                                     
Found Xcode (version: 12.2, build id: 12B45b)
Found MacOSX SDK (version: 11.0, build id: 20A2408)
Creating output .tar.gz file...
Adding MacOSX SDK 11.0 files...
Adding libc++ headers...
Done! Find the resulting gzipped tarball at:
Xcode-12.2-12B45b-extracted-SDK-with-libcxx-headers.tar.gz
➜  SDK shasum -a 256 Xcode-12.2-12B45b-extracted-SDK-with-libcxx-headers.tar.gz
e7ca56bc8804d16624fad68be2e71647747d6629cacaaa3de5fbfa7f444e9eae  Xcode-12.2-12B45b-extracted-SDK-with-libcxx-headers.tar.gz
```

**Comment by prusnak** [comment]
> Nice. I'm now getting a matching hash.

Thanks. Switching from Draft to Ready for review.

**Comment by laanwj** [comment]
Concept ACK. I think having a deterministic MacOS SDK input is very useful.

**Comment by jarolrod** [comment]
Concept ACK, would love to see this be deterministic but I have a hash mismatch with the resulting archive file.

I get the same hash for the downloaded xip file:
```
$ sha256sum ./Xcode_12.2.xip 

28d352f8c14a43d9b8a082ac6338dc173cb153f964c6e8fb6ba389e5be528bd0
```

But, I get a different hash for the resulting archive file:

```
$ ./contrib/macdeploy/gen-sdk ./Xcode.app

Found Xcode (version: 12.2, build id: 12B45b)
Found MacOSX SDK (version: 11.0, build id: 20A2408)
Creating output .tar.gz file...
Adding MacOSX SDK 11.0 files...
Adding libc++ headers...
Done! Find the resulting gzipped tarball at:
/home/xyz/Code/Bitcoin/review/bitcoin-24534/bitcoin/Xcode-12.2-12B45b-extracted-SDK-with-libcxx-headers.tar.gz
```

```
$ sha256sum ./Xcode-12.2-12B45b-extracted-SDK-with-libcxx-headers.tar.gz 

501625bd401d7f228b3bae18f264fd3739da5788464f0897e5c455451d2128c2  ./Xcode-12.2-12B45b-extracted-SDK-with-libcxx-headers.tar.gz
```

**Comment by laanwj** [comment]
Tested ACK ba30a5407e065e9d6dd037351e83f56a43f38f19

Output matches the hash in the OP (tried on Ubuntu 22.04, x86_64, Python 3.10.4):
```sh
$ sha256sum ~/Downloads/Xcode_12.2.xip
28d352f8c14a43d9b8a082ac6338dc173cb153f964c6e8fb6ba389e5be528bd0  /home/orion/Downloads/Xcode_12.2.xip
$ …/apple-sdk-tools/extract_xcode.py -f ~/Downloads/Xcode_12.2.xip | cpio -d -i
$ …/bitcoin/contrib/macdeploy/gen-sdk $PWD/Xcode.app/
Found Xcode (version: 12.2, build id: 12B45b)
Found MacOSX SDK (version: 11.0, build id: 20A2408)
Creating output .tar.gz file...
Adding MacOSX SDK 11.0 files...
Adding libc++ headers...
Done! Find the resulting gzipped tarball at:
…/apple-sdk-tools/Xcode-12.2-12B45b-extracted-SDK-with-libcxx-headers.tar.gz
$ sha256sum Xcode-12.2-12B45b-extracted-SDK-with-libcxx-headers.tar.gz
e7ca56bc8804d16624fad68be2e71647747d6629cacaaa3de5fbfa7f444e9eae  Xcode-12.2-12B45b-extracted-SDK-with-libcxx-headers.tar.gz
```

**Comment by jarolrod** [comment]
@prusnak That run was Ubuntu 22.04, python 3.10, on arm64 cpu. Will rerun on x86 ubuntu

`reserved for run on x86 ubuntu`

**Comment by prusnak** [comment]
@jarolrod Hm, weird. can you please share the tarball with the `501625bd401d7f228b3bae18f264fd3739da5788464f0897e5c455451d2128c2` hash? I could compare locally and try to figure out what went wrong.

**Review by jarolrod — APPROVED** [review]
Tested ACK https://github.com/bitcoin/bitcoin/commit/ba30a5407e065e9d6dd037351e83f56a43f38f19

I don't know what had happened in my original run, its possible that on accident I hadn't successfully changed to the PR branch. I re-ran everything on my setup and now I get a matching hash :)

```
sha256sum ./Xcode-12.2-12B45b-extracted-SDK-with-libcxx-headers.tar.gz 
e7ca56bc8804d16624fad68be2e71647747d6629cacaaa3de5fbfa7f444e9eae  ./Xcode-12.2-12B45b-extracted-SDK-with-libcxx-headers.tar.gz
```

**Comment by laanwj** [comment]
I think this causes an error while building from the SDK: #24947

**Pull request merged**
