### PR TITLE
Bring secp256k1 subtree up to date with master

### PR DESCRIPTION
**Pull request by laanwj**
The last update of secp256k1 has been ~9 months ago (6c527ec), probably it is time to update the subtree again.
At least the (experimental) ARM assembly has been merged since.

According to @sipa on IRC "there are certainly no regressions known that would make the current master less appropriate than the subtree in bitcoin currently"

### CODE REVIEW

**Comment by MarcoFalke** [comment]
utACK 103f1e8

```
$ ./contrib/devtools/git-subtree-check.sh src/secp256k1
src/secp256k1 in HEAD was last updated to upstream commit c5b32e16c4d2560ce829caf88a413fc06fd83d09 (tree cabf1a0476632c9ac99946c39e663a681cc019ae)
src/secp256k1 in HEAD currently refers to tree cabf1a0476632c9ac99946c39e663a681cc019ae
GOOD

**Comment by paveljanik** [comment]
Removal of <string.h> include is probably the source of this warning:

```
+In file included from src/secp256k1.c:14:
+./src/ecmult_impl.h:186:9: warning: implicitly declaring library function 'memcpy' with type 'void *(void *, const void *, unsigned long)'
+        memcpy(dst->pre_g, src->pre_g, size);
+        ^
+./src/ecmult_impl.h:186:9: note: include the header <string.h> or explicitly provide a declaration for 'memcpy'
+./src/ecmult_impl.h:230:5: warning: implicitly declaring library function 'memset' with type 'void *(void *, int, unsigned long)'
+    memset(wnaf, 0, len * sizeof(wnaf[0]));
+    ^
+./src/ecmult_impl.h:230:5: note: include the header <string.h> or explicitly provide a declaration for 'memset'
+2 warnings generated.
```

Will report upstream...

**Comment by laanwj** [comment]
@paveljanik That's a very nasty warning (being able to use functions without declarations is an ancient C mis-feature), but indeed that needs to be solved upsteram.

**Comment by paveljanik** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/8453/commits/103f1e897dfcc3fa8f2089fe961bb83a11d01057

**Comment by laanwj** [comment]
Will re-do this now that https://github.com/bitcoin-core/secp256k1/issues/410 is merged

**Comment by laanwj** [comment]
Updated.

**Comment by MarcoFalke** [comment]
```
$ ./contrib/devtools/git-subtree-check.sh src/secp256k1
src/secp256k1 in HEAD was last updated to upstream commit 7a49cacd3937311fcb1cb36b6ba3336fca811991 (tree cfd05e78e0a117016efa89cd75e4ac5a938219cb)
src/secp256k1 in HEAD currently refers to tree cfd05e78e0a117016efa89cd75e4ac5a938219cb
GOOD

**Comment by paveljanik** [comment]
utACK

Travis failure in `segwit.py` (https://travis-ci.org/bitcoin/bitcoin/jobs/152624836#L7727) interesting, but probably unrelated.

**Comment by sipa** [comment]
```
$ contrib/devtools/git-subtree-check.sh src/secp256k1
src/secp256k1 in HEAD was last updated to upstream commit 7a49cacd3937311fcb1cb36b6ba3336fca811991 (tree cfd05e78e0a117016efa89cd75e4ac5a938219cb)
src/secp256k1 in HEAD currently refers to tree cfd05e78e0a117016efa89cd75e4ac5a938219cb
GOOD
```

**Pull request merged**
