### PR TITLE
Avoid divide-by-zero in header sync logs when NodeClock is behind

### PR DESCRIPTION
**Pull request by maflcko**
The log may be confusing, when the NodeClock is behind the current header tip.

Fix it, by assuming the NodeClock is never behind the current header tip.

### CODE REVIEW

**Comment by sr-gi** [comment]
Concept ACK, will review it soon

**Review by tdb3 — COMMENTED** [review]
ACK fa4d98b3c8e63f20c6f366fc9382039ba52614a4
crACK.
Ran some basic sanity checks:  built, and ran all unit and functional tests (all passed).

Started IBD on signet without stale clock.
"Pre-synchronizing" and "Synchronizing" messages looked ok (no negatives or inf observed).

Started IBD on signet with stale clock (about 19 hours behind tip).
"Pre-synchronizing" and "Synchronizing" messages looked ok (no negatives or inf observed).

**Comment by tdb3** [comment]
> > Started IBD on signet with stale clock (about 19 hours behind tip).
> > "Pre-synchronizing" and "Synchronizing" messages looked ok (no negatives or inf observed).
> 
> Yes, this is expected, because the signet chain has a total age of over 19 hours. You could try again, but set the time to be before the first header in the signet chain, and then submit the first header? Or you could try my modified functional test: [#29640 (comment)](https://github.com/bitcoin/bitcoin/pull/29640#discussion_r1523264375)?

v26.0:
```
2019-12-31T06:00:36Z New outbound-full-relay v1 peer connected: version: 70013, blocks=187585, peer=0
2019-12-31T06:00:36Z Pre-synchronizing blockheaders, height: 2000 (~-5.89%)
2019-12-31T06:00:37Z Pre-synchronizing blockheaders, height: 4000 (~-11.76%)
...
2019-12-31T06:01:01Z Pre-synchronizing blockheaders, height: 142000 (~-414.61%)
2019-12-31T06:01:02Z Pre-synchronizing blockheaders, height: 146000 (~-424.84%)
2019-12-31T06:01:05Z Warning: Please check that your computer's date and time are correct! If your clock is wrong, Bitcoin Core will not work properly.
Warning: Please check that your computer's date and time are correct! If your clock is wrong, Bitcoin Core will not work properly.
2019-12-31T06:01:05Z New outbound-full-relay v1 peer connected: version: 70016, blocks=187585, peer=3

```

PR 29647:
```
2019-12-31T06:02:36Z Pre-synchronizing blockheaders, height: 6000 (~100.00%)
2019-12-31T06:02:36Z Pre-synchronizing blockheaders, height: 10000 (~100.00%)
...
2019-12-31T06:02:52Z Pre-synchronizing blockheaders, height: 174000 (~100.00%)
2019-12-31T06:02:52Z Pre-synchronizing blockheaders, height: 178000 (~100.00%)
2019-12-31T06:02:52Z Cannot connect to socket for 119.123.205.192:38333
2019-12-31T06:02:53Z Cannot connect to socket for 100.26.155.44:38333
2019-12-31T06:02:54Z Warning: Please check that your computer's date and time are correct! If your clock is wrong, Bitcoin Core will not work properly.
Warning: Please check that your computer's date and time are correct! If your clock is wrong, Bitcoin Core will not work properly.

```

**Comment by sr-gi** [comment]
tACK [fa4d98b](https://github.com/bitcoin/bitcoin/pull/29647/commits/fa4d98b3c8e63f20c6f366fc9382039ba52614a4)

I tested this against #29640 by dropping 813961f057255835285266b90fcd6351ff4a3d1e and cherry-picking both commits included in the PR.

Output after dropping 813961f057255835285266b90fcd6351ff4a3d1e:

```
[msghand] [validation.cpp:4193] [ProcessNewBlockHeaders] Synchronizing blockheaders, height: 1 (~inf%)
```

Output after cherry-picking:

```
[validation.cpp:4194] [ProcessNewBlockHeaders] Synchronizing blockheaders, height: 1 (~100.00%)
```

**Comment by achow101** [comment]
ACK fa4d98b3c8e63f20c6f366fc9382039ba52614a4

**Pull request merged**
