### PR TITLE
bitcoin-cli.cpp: Use symbolic constant for exit code

### PR DESCRIPTION
**Pull request by tuladhar**

### CODE REVIEW

**Comment by paveljanik** [comment]
Looks much better, ACK https://github.com/bitcoin/bitcoin/pull/7989/commits/9a8a7d011564c43231d16e6e3a25c73f0c76fde1

No need to open new PR next time :-)

**Comment by laanwj** [comment]
Trivially correct ACK https://github.com/bitcoin/bitcoin/pull/7989/commits/9a8a7d011564c43231d16e6e3a25c73f0c76fde1

**Comment by MarcoFalke** [comment]
I think the motivation for this change was https://stackoverflow.com/questions/461449/return-statement-vs-exit-in-main , so the commit message would be still "wrong".

But the code looks good. utACK 9a8a7d0

**Comment by laanwj** [comment]
It's no less wrong or right, IMO, but it harmonizes the function a bit - all of the other exits from main() use return EXIT_FAILURE.

**Comment by tuladhar** [comment]
@laanwj Thanks for the merge!

**Pull request merged**
