### PR TITLE
[doc] Increase recommended memory in gitian build guide

### PR DESCRIPTION
**Pull request by fanquake**
Fixes some nits from #8358.

Probably worth back-porting to the 0.13 branch, so the guide is correct for any new builders.

### CODE REVIEW

**Comment by laanwj** [comment]
utACK, should have been part of #8358

**Comment by MarcoFalke** [comment]
This was brought to my attention after the pull was merged. Also, I don't use virtual box (nor this guide) on my machine.

Concept ACK 7fdbce9

**Comment by sipa** [comment]
ACK

**Comment by rebroad** [comment]
Does anyone know why this has increased?

**Comment by jonasschnelli** [comment]
@rebroad: see https://github.com/bitcoin/bitcoin/pull/8358

**Pull request merged**
