### PR TITLE
doc: Add 19501 release notes

### PR DESCRIPTION
**Pull request by maflcko**
Adds release notes and fixes up some whitespace nits for the touched RPCs

### CODE REVIEW

**Comment by fanquake** [comment]
Want to fix up [this issue](https://github.com/bitcoin/bitcoin/pull/19969#discussion_r491663311) here as well?

**Comment by MarcoFalke** [comment]
Thx, done. The rendered diff for the first commit is now:

```diff
diff --git a/send b/send
index 58337d5..2a403d7 100644
--- a/send
+++ b/send
@@ -5,7 +5,7 @@ EXPERIMENTAL warning: this call may be changed in future releases.
 Send a transaction.
 
 Arguments:
-1. outputs                               (json array, required) A JSON array with outputs (key-value pairs), where none of the keys are duplicated.
+1. outputs                               (json array, required) The outputs (key-value pairs), where none of the keys are duplicated.
                                          That is, each address can only appear once and there can only be one 'data' object.
                                          For convenience, a dictionary, which holds the key-value pairs directly, is also accepted.
      [
diff --git a/sendmany b/sendmany
index ee770c0..d5c56a3 100644
--- a/sendmany
+++ b/sendmany
@@ -30,7 +30,7 @@ Arguments:
 9. verbose                   (boolean, optional, default=false) If true, return extra infomration about the transaction.
 
 Result (if verbose is not set or set to false):
-"hex"    (string) The transaction id for the send. Only  1 transaction is created regardless of
+"hex"    (string) The transaction id for the send. Only 1 transaction is created regardless of
          the number of addresses.
 
 Result (if verbose is set to true):

**Comment by laanwj** [comment]
Code review ACK fa710a6d67b2de64bde90def77c70d0a052f9030

**Review by fanquake — APPROVED** [review]
ACK fa710a6d67b2de64bde90def77c70d0a052f9030

**Pull request merged**
