### PR TITLE
build: make configure --enable-debug override CXXFLAGS from depends

### PR DESCRIPTION
**Pull request by mruddy**
Before this change, to compile with depends, and have your `--enable-debug` `-O0` be effective, you'd still need to do:

`CONFIG_SITE="$PWD/depends/x86_64-pc-linux-gnu/share/config.site" ./configure --enable-debug CXXFLAGS="-O0"`

This is because the depends config.site is setting `-O1` via CXXFLAGS. For more info, see here https://github.com/bitcoin/bitcoin/blob/69b10212ea5370606c7a5aa500a70c36b4cbb58f/depends/hosts/linux.mk#L17-L18

This PR makes it so that you just have to run:
`CONFIG_SITE="$PWD/depends/x86_64-pc-linux-gnu/share/config.site" ./configure --enable-debug`

### CODE REVIEW

**Comment by hebasto** [comment]
It is supposed to build depends with `DEBUG=1`. In that case no `--enable-debug` required as it is set in `config.site`.

**Comment by mruddy** [comment]
By doing that, you end up with `-O1` instead of `-O0 -g3 -ftrapv`.
Building depends with `make DEBUG=1` is not enough.

**Comment by Davidcalculus** [comment]
bc1qdrc8fup30ctv7ppjyr2txcg6wgcrejj2nk53we

**Comment by fanquake** [comment]
@mruddy you might want to take a look at #25972, which is related to this change, and contains fixes for some of the issues you're seeing in the CI here.

**Comment by fanquake** [comment]
Going to close this in favour of #25972, which solves the same issue. The CI failures here are the same as-in that PR, where solutions to most have been found. I think the next steps are to start splitting changes off the PR.

**Comment by mruddy** [comment]
@fanquake I think that this PR should follow (that is, build off of the changes that you guys are doing in) #25972, but I don't think they solve the same issue. Fundamentally, this PR deals with getting the CXXFLAGS that are set by the depends build to not clobber the debug flags set by the subsequent configure.

**Pull request closed without merging**
