### PR TITLE
Include full version number in released file names

### PR DESCRIPTION
**Pull request by achow101**
As noted on IRC, the filenames of the gitian build results do not contain the 4th digit of the version number if it has one, e.g. 0.17.0.1 produces files with the number 0.17.0. Furthermore, when RC's are built, the resulting filenames are of the release version and do not include `rc` in them. This occurs because `configure.ac` is written to create version numbers of the form `major.minor.rev` instead of `major.minor.rev.build` and without any rc version as it does not handle rc numbers.

This PR changes `configure.ac` to include the build number if it is greater than 0. It will also include the rc number if it is greater than 0. So the filenames of the gitian builds will now contain the full version number.

This behavior can be tested by setting `_CLIENT_VERSION_BUILD` and `_CLIENT_VERSION_RC` to non-zero values and then doing `make dist`. A tar file should be created with the correct versioning.

### CODE REVIEW

**Comment by luke-jr** [comment]
So it would show `0.17.0.1rc1` if that was the version?

Might be nice to actually use the full version number generated from the tag, so non-tag builds get the commit hash in there...

**Comment by achow101** [comment]
> So it would show `0.17.0.1rc1` if that was the version?

It would only show in the gitian produced files. This shouldn't effect what users would see from `-version` or in the About window.

**Comment by harding** [comment]
For BitcoinCore.org, as @laanwj mentions, the regular content part of the website doesn't currently have any pages that link directly to RCs, so no changes are necessary as long as the final release files continue to use the same naming scheme.

**Comment by wbnns** [comment]
Should be okay for bitcoin.org as well, thanks.

**Comment by achow101** [comment]
I've updated release-process.md to say that `CLIENT_VERSION_RC` needs to be updated before each RC.

> Normal releases will not change name, correct?

Correct.

**Comment by laanwj** [comment]
@harding @wbnns thanks for weighing in

utACK 75a4bf699fa6bdefa1b3d8cd405ea822d6ee01c0

**Comment by laanwj** [comment]
@theuni I suppose you're ok with this?

**Pull request merged**
