### PR TITLE
wallet: refactor: dedup sqlite blob binding

### PR DESCRIPTION
**Pull request by theStack**
This refactoring PR deduplicates repeated SQLite blob binding to a statement with a newly introduced helper function `BindBlobToStatement`, abstracting away the calls to `sqlite3_bind_blob(...)`. 
This should be more readable and less error-prone, e.g. in case that the error handling has to be adapted. As a slight drawback, the function where the binding happens is not printed anymore (`__func__`), i.e. one could argue this is not strictly a refactoring, but IMHO the advantages of deduplication outweigh this; binding errors are purely internal logic errors (wrong use of the sqlite API) rather than something that is dependend on external data like DB content.

### CODE REVIEW

**Comment by fanquake** [comment]
[CI failure](https://cirrus-ci.com/task/6303111479296000?logs=ci#L3036):
```bash
 test  2022-03-06T20:03:09.040000Z TestFramework (ERROR): Assertion failed 
                                   Traceback (most recent call last):
                                     File "/tmp/cirrus-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 132, in main
                                       self.run_test()
                                     File "/tmp/cirrus-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/wallet_taproot.py", line 435, in run_test
                                       lambda k1, k2: (key(H_POINT), [multi_a(1, [k1, k2])])
                                     File "/tmp/cirrus-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/wallet_taproot.py", line 336, in do_test
                                       self.do_test_addr(comment, pattern, privmap, treefn, keys[0:nkeys])
                                     File "/tmp/cirrus-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/wallet_taproot.py", line 251, in do_test_addr
                                       assert_equal(addr_g, addr_r)
                                     File "/tmp/cirrus-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/util.py", line 51, in assert_equal
                                       raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
                                   AssertionError: not(bcrt1px3pnh5n8npeqr3cv0aq6dvqpcsujrgksfd6hup8dpa62z3m9jf9s3sk3ve == bcrt1pn2xq83tt55vfsxtwhkx96sanchkjzwg6yqxuewvn6emkfyqnyp0qe5cteg)
```

**Comment by achow101** [comment]
CI failure is unrelated

**Comment by theStack** [comment]
Restarted the CI for the failing target (the cause of the failure is fixed in #24490).

**Comment by laanwj** [comment]
Code review ACK 8ea6167099ddfe9a42464c3c8ae2acd895329d4f

Nice cleanup.

**Comment by achow101** [comment]
ACK 8ea6167099ddfe9a42464c3c8ae2acd895329d4f

**Comment by klementtan** [comment]
ACK 8ea6167099ddfe9a42464c3c8ae2acd895329d4f

**Review by klementtan — APPROVED** [review]

**Pull request merged**
