### PR TITLE
[Qt] Fix display of package name on 'open config file' tooltip

### PR DESCRIPTION
**Pull request by esotericnonsense**
This patch addresses https://github.com/bitcoin/bitcoin/issues/11197.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
utACK 6c26e8907ce1047a4206cab7510455f155e5d1f1

**Comment by achow101** [comment]
utACK 6c26e89

**Comment by MarcoFalke** [comment]
Marked for backport in case it can make it through. Imo, does not need a fresh rc.

**Comment by esotericnonsense** [comment]
I have tested this patch off the v0.15.0rc3 tag with --disablewallet (as I don't have bdb4.8 on the machine atm).

**Comment by esotericnonsense** [comment]
Also working on a PR against master as it doesn't merge cleanly

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/11198/commits/14ccd4d8d1847d64903224562ad3c7eb795b3781

**Comment by jonasschnelli** [comment]
Post merge ACK 14ccd4d8d1847d64903224562ad3c7eb795b3781

**Pull request merged**
