### PR TITLE
qt: Prefix makefile variables with QT_

### PR DESCRIPTION
**Pull request by promag**
Improves consistency and readability if future QML variables are added.

### CODE REVIEW

**Review by shaavan — COMMENTED** [review]
Concept ACK

This PR focuses on improving the consistency and readability of **Makefile.qt.include** by renaming the variable per their proper function and usage. Since there is a high probability of introducing new **QML** variables in the future, this is a small but necessary change.

As we are on the matter of variable naming consistency, I want to add something, though. In the **Makefile.qt.include** on lines **292** and **324.** Shouldn’t the variable `BITCOIN_RS` also be renamed to `BITCOIN_QT_RS`?

**Comment by promag** [comment]
I’ll take a look @shaavan, thanks.

**Review by hebasto — APPROVED** [review]
ACK e8b6e7ccb45c0189ccc953589b8083a7fe0c56a8

**Review by hebasto — APPROVED** [review]
re-ACK eb04badcd6108e17c8ec78e9c316775c334030cb, only suggested changes, and script-diff used.

**Review by shaavan — APPROVED** [review]
Code Review ACK eb04badcd6108e17c8ec78e9c316775c334030cb

Changes since my last review:
- Renamed `BITCOIN_RC` -> `BITCOIN_QT_RC`
- Used **scripted-diff** in commit message

**Pull request merged**
