### PR TITLE
test: Mention commit id in scripted diff error

### PR DESCRIPTION
**Pull request by laanwj**
Add commit id to make spotting the issue easier.

### CODE REVIEW

**Review by hebasto — APPROVED** [review]
~ACK~ Concept ACK 3491bf358a81d41a386cd14581d15396354a6e6c, should help in situations like https://travis-ci.org/github/bitcoin/bitcoin/jobs/732481553

**Comment by hebasto** [comment]
Is this new check break all future CI builds due to the ill-formed title of the f471a3be00c2b6433b8c258b716982c0539da13f commit?

**Comment by jonatack** [comment]
Good idea.

**Comment by laanwj** [comment]
> Will all future Travis CI builds fail due to the ill-formed title of the f471a3b commit?

It's pretty strange, I assumed this script will only check the PR in question, not the whole project history.

**Comment by fjahr** [comment]
I think this is the same issue as #19654 fixed and I would suggest to use the same fix: #20071.

**Comment by robot-dreams** [comment]
ACK 3491bf358a81d41a386cd14581d15396354a6e6c

Without this change, at 54fc96ffa70ad3a53d32709101b7a2ce064d822e:

```
$ test/lint/commit-script-check.sh HEAD~..
Error: script block marker but no scripted-diff in title
Failed
```

With this change (rebased onto 54fc96ffa70ad3a53d32709101b7a2ce064d822e):

```
$ test/lint/commit-script-check.sh HEAD~2..
Error: script block marker but no scripted-diff in title of commit f471a3be00c2b6433b8c258b716982c0539da13f
Failed
```

**Comment by sipa** [comment]
utACK 3491bf358a81d41a386cd14581d15396354a6e6c

**Pull request merged**
