### PR TITLE
script: de-dupe and update valgrind suppressions

### PR DESCRIPTION
**Pull request by jonatack**
This PR de-dupes the current suppressions, then reduces the additional ones currently generated down to the minimal entries needed to run valgrind 3.16.0 with `--exit-on-first-error=yes`. Tested on Debian 4.19 x86/64. Feedback welcome.

These suppressions allow running valgrind without errors on current master for...

test_bitcoin:
```
  valgrind --leak-check=full --show-leak-kinds=all --show-reachable=yes \
           --gen-suppressions=all --error-limit=no -s \
           --suppressions=contrib/valgrind.supp \
           src/test/test_bitcoin --log_level=test_suite
```
bench_bitcoin:
```
  valgrind --leak-check=full --show-leak-kinds=all --show-reachable=yes \
           --gen-suppressions=all --error-limit=no -s \
           --suppressions=contrib/valgrind.supp \
           src/bench/bench_bitcoin -evals=1
```
test_bitcoin-qt:
```
  valgrind --leak-check=full --show-leak-kinds=all --show-reachable=yes \
           --gen-suppressions=all --error-limit=no -s \
           --suppressions=contrib/valgrind.supp \
           src/qt/test/test_bitcoin-qt --log_level=test_suite
```
and with `make check-valgrind` in PR #17639 which runs them all.

### CODE REVIEW

**Comment by practicalswift** [comment]
@jonatack 

Are you able to reproduce this one reliably?

```
{
   Suppress rest_blockhash_by_height Conditional jump or move depends on uninitialised value(s)
   Memcheck:Cond
   fun:_ZL24rest_blockhash_by_heightP11HTTPRequestRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
}
```

If so, can you try minimising the test case to find the root cause?

It looks like the use of an uninitialised value, which would be a very valuable find!

**Comment by jonatack** [comment]
Lone travis failure in "scheduler_tests/mockforward" is unrelated.

**Comment by practicalswift** [comment]
@jonatack I haven't seen that failure - I quoted the diff :)

**Comment by jonatack** [comment]
Oh ok, that appears to be worth looking into but is unrelated to this PR; that suppression was introduced in 2d23082cbe4. Once this PR is merged it will be easier for me to look into individual errors without seeing a hundred other warnings or maintaining a custom suppressions file.

**Comment by jonatack** [comment]
> @jonatack I haven't seen that failure - I quoted the diff :)

Oh ok, that appears to be worth looking into but is unrelated to this PR; that suppression was introduced in 2d23082 by @michiboo. Once this PR is merged it will be easier for me to look into individual errors without seeing a hundred other warnings or maintaining a custom suppressions file.

**Comment by jonatack** [comment]
No reviews or interest in this, closing.

**Pull request closed without merging**
