### PR TITLE
CI: Add label to scripted-diffs

### PR DESCRIPTION
**Pull request by l0rinc**
Add a `scripted-diff` label for pull requests that contain `scripted-diff:` commits, to make sure that CI is running them properly.
Inspired by https://github.com/bitcoin/bitcoin/issues/29692

Note that I've used https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/using-github-cli-in-workflows instead of e.g. `actions-ecosystem/action-add-labels` since it's a lot simpler, can be tried locally and documents a lot better what we're doing (it's also what their example uses in https://docs.github.com/en/actions/use-cases-and-examples/project-management/adding-labels-to-issues).

### CODE REVIEW

**Comment by l0rinc** [comment]
As an attack vector, people could prefix with `scripted–diff` (using an en dash or other unicode char which wouldn't be obvious to a human, but the CI wouldn't run the provided scripts). Adding a label would provide an extra level of safety to make sure the CI did its job.

Note that this is still a draft and doesn't seem to be working yet, comments like these are welcome.

**Comment by l0rinc** [comment]
> If there is a BEGIN, without a matching scripted-diff

Which can be replaced with `BEGlN` (i.e. a lowercase L instead of an I or any other unicode trickery) and reviewers would be fooled into thinking that the scripts were validated by the CI.

**Comment by theuni** [comment]
Agree with @maflcko that this isn't adding much as-is. My suggestion was for @DrahtBot to add the label only once it had actually run the scripted-diff successfully.

**Comment by l0rinc** [comment]
> My suggestion was for @DrahtBot to add the label only once it had actually run the scripted-diff successfully.

If you think that's better than doing it in a separate job, I'll investigate.
@maflcko, would that work with you as well?

**Comment by fanquake** [comment]
Agree with the other comments. Concept -0

**Pull request closed without merging**
