### PR TITLE
doc: fix command typo in guix README

### PR DESCRIPTION
**Pull request by hg333**

### CODE REVIEW

**Comment by jonatack** [comment]
Feel free to pull in any of these fixups as well: https://github.com/jonatack/bitcoin/commit/e279f6a09a38dabc6b80d537d3212abddba5ed8b

**Review by jonatack — COMMENTED** [review]
ACK 198ceb82f91bfdeac6e143ca7433f4a524f6f36f

**Comment by jamesob** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/22538/commits/198ceb82f91bfdeac6e143ca7433f4a524f6f36f

**Comment by fanquake** [comment]
In future, please remove the default comment from the PR template, even if you're not writing a PR description. Also, you can use a prefix in your commit message. See how I've edited the title.

**Comment by fanquake** [comment]
Backported in #22534.

**Comment by laanwj** [comment]
@hg333 Your git name is "h". You might want to change this so that it's easier to credit you in the release notes next time. For 23.0 I'm going to use "hg333".

**Pull request merged**
