### PR TITLE
MOVEONLY: Policy: Move some policy code

### PR DESCRIPTION
**Pull request by jtimon**
Move policy code out of main (and policy/standard).
Nobody seemed to disagree with this part in any of the multiple versions of #6068 and related PRs.
This is trivially non-risky, but this PR will be closed when a bitcoin/0.12 branch is created (unless it has been merged first).

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Code Review ACK.

**Comment by petertodd** [comment]
utACK (mostly concept ACK, w/ some code review)

**Comment by paveljanik** [comment]
utACK

**Comment by theuni** [comment]
Confirmed move-only other than the std namespace changes. utACK other than the nit above.

**Comment by jtimon** [comment]
@theuni re additional declaration. It was to not leave the comment alone until it is replaced with the CStandardPolicy method that will replace it in https://github.com/jtimon/bitcoin/commit/3fdcfedadafebb11f5ee01f10ef2c0f0f98c74d5#diff-d22bc3e058f8982972e2eb381a1df668L35 but I'm happy to remove that line if it doesn't make sense to anyone else. For me having the comment ready there is enough.

**Comment by btcdrak** [comment]
utACK

**Comment by morcos** [comment]
ACK (before the merge conflict)

**Comment by jtimon** [comment]
Rebased

**Comment by luke-jr** [comment]
Concept ACK (did not confirm MOVEONLY).

**Comment by jtimon** [comment]
@laanwj @sipa ping

**Pull request merged**
