### PR TITLE
[Wallet][Trivial] Rename usehd option to createhdwallet

### PR DESCRIPTION
**Pull request by pstratem**

### CODE REVIEW

**Comment by laanwj** [comment]
This was discussed in #8035: https://github.com/bitcoin/bitcoin/pull/8035#issuecomment-225366630 and there was no clear preference for renaming it.

**Comment by MarcoFalke** [comment]
@pstratem The goal was to have this a permanent option and not an option only for the first start of the client. I.e. you set whether you prefer to usehd or not in your conf file. Thus, the client can warn you if the underlying wallet does not comply your preference.

**Comment by pstratem** [comment]
@MarcoFalke OK is there an upgrade strategy?

**Comment by MarcoFalke** [comment]
Not for 0.13. But I think there are  plans to use `-upgradewallet` or similar to create a HD seed in 0.14.

**Comment by jonasschnelli** [comment]
I think we should keep `-usehd=1` for now.
We need to think about ... 

1. if and how we are going to allow HD for already existing wallets
2. How a user could input a seed (xpriv) during hd wallet creation (I guess a config argument `-hdmasterkey=<xpriv>` would not be the best way to do this, adding an RPC call would allow to pass in a master key at the stage where the wallet has already been created).

**Comment by laanwj** [comment]
The rationale for keeping the option named as-is has been explained, no need to rename, closing this.

**Pull request closed without merging**
