### PR TITLE
[24.x] p2p: Handle IsContinuationOfLowWorkHeadersSync return value correctly when new headers sync is started

### PR DESCRIPTION
**Pull request by glozow**
Backport of #26355.

### CODE REVIEW

**Comment by dergoegge** [comment]
ACK e23def8fcc4558b1a49ee8f2dd608fe91ced1d6d

**Review by stickies-v — APPROVED** [review]
ACK e23def8fcc4558b1a49ee8f2dd608fe91ced1d6d

Changes are identical to #26355, and they're based on the same `PeerManagerImpl::TryLowWorkHeadersSync()` function - no changes there either.

**Comment by luke-jr** [comment]
@glozow In the future, if you're not merging the exact same commit, please add the usual "Github-Pull" and "Rebased-From" fields to the commit messages.

**Comment by glozow** [comment]
@luke-jr will do, thanks

**Pull request merged**
