### PR TITLE
test: Inline scriptnum10 header

### PR DESCRIPTION
**Pull request by maflcko**
The header file was moved to test in #4160.

Currently `make clean` fails because da32bd80bf3cab07e12f574dafcf11345a961444 assumed that the `BITCOIN_TESTS` only contains cpp files.

The `make clean` failure can be solved by inlining the header file.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Instead of inlining, I could move it to `BITCOIN_TEST_SUITE`, if people prefer.

**Comment by murrayn** [comment]
I was going to change https://github.com/bitcoin/bitcoin/commit/da32bd80bf3cab07e12f574dafcf11345a961444 but I think your `BITCOIN_TEST_SUITE` suggestion seems better.

Maybe `BITCOIN_TESTS ` should be renamed `BITCOIN_TESTS_CPP` for clarity?

**Comment by practicalswift** [comment]
Concept ACK

Let's get this merged quickly – `make clean` is crucial :-)

**Comment by Empact** [comment]
I like the idea of moving to `BITCOIN_TEST_SUITE`.

**Comment by jamesob** [comment]
IMO we should do the simplest thing possible to make `make clean` work again (https://github.com/bitcoin/bitcoin/pull/14455) and only after that think about shuffling stuff around.

**Pull request closed without merging**
