### PR TITLE
[net] Minor cleanups to asmap

### PR DESCRIPTION
**Pull request by jnewbery**
These small cleanups to the asmap code are the first 4 commits from #22910. They're minor improvements that are independently useful whether or not 22910 is merged.

### CODE REVIEW

**Comment by fanquake** [comment]
Concept ACK

**Comment by naumenkogs** [comment]
ACK 853c4edb70f897a6a7165abaea4a303d7d448721

**Comment by practicalswift** [comment]
Concept ACK

**Review by theStack — APPROVED** [review]
Concept and code-review ACK 853c4edb70f897a6a7165abaea4a303d7d448721 🗺️ 

An alternative solution in bfdf4ef334a16ef6108a658bf4f8514754128c18 would be to simply set `bits = 128` as default argument for the global `SanityCheckASMap` function (no need to update callers, deduplicates the magic number).

**Review by fanquake — APPROVED** [review]
ACK 853c4edb70f897a6a7165abaea4a303d7d448721

**Pull request merged**
