### PR TITLE
(WIP) Add -logtimemillis command line option

### PR DESCRIPTION
**Pull request by rebroad**
I find micros are too granular, with no line ever being less than 1 millisecond apart from its neighbouring lines, therefore this option will save 3 bytes per line of debug.log :)

### CODE REVIEW

**Comment by laanwj** [comment]
Seems overkill to have three time formats

**Comment by jonasschnelli** [comment]
Agree with @laanwj

**Comment by rebroad** [comment]
@laanwj you have a point - shall I add to this the removal of logtimemicros? I just didn't want to inconvenience people who already had it in their bitcoin.conf, though.

**Comment by laanwj** [comment]
IMO we should just keep things as is. Either use microsecond precision, or second precision, or keep this as a custom patch. You could even postprocess the log to chop off three positions. For the rest of the world this just isn't so important.

**Comment by rebroad** [comment]
@laanwj You are probably right, but if you close the PR now the rest of the world probably won't even see this PR to give their opinion on it...

**Comment by laanwj** [comment]
I'd fathom the rest of the world, too, has more urgent things to discuss too than even more flavors of logging format. This shouldn't compete for attention with attention with bugfixes and new features.

**Comment by rebroad** [comment]
@laanwj You are probably right, however, many other projects default to logging only milliseconds. I do still question the logic in logging 3 additional insignificant decimal places, given that lines (in my experience) are never less than 1ms apart.

I like the idea of postprocessing, although ideally rather than post-processing this could be done by piping so that the unprocessed debug log isn't created. Is there currently an option to debug to stdout or stderr?, as this would then be possible.

**Comment by laanwj** [comment]
```
src/init.cpp:    strUsage += HelpMessageOpt("-printtoconsole", _("Send trace/debug info to console instead of debug.log file"));
```

**Pull request closed without merging**
