### PR TITLE
build, qt: Drop unneeded direct dependency on freetype

### PR DESCRIPTION
**Pull request by hebasto**
Only `fontconfig` directly depends on `freetype`.

#### Guix builds on `x86_64`:
```
$ find guix-build-$(git rev-parse --short=12 HEAD)/output/ -type f -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum
02a5522a0e58ff9b330e84922419ea99516fcb1e74ba0e1deb94babe7f5dbf2b  guix-build-cc7542cc9552/output/aarch64-linux-gnu/SHA256SUMS.part
9c6e0f38f37556da2a8e77f920253b81faccd680211e9c5f1c11f6f66c9ea786  guix-build-cc7542cc9552/output/aarch64-linux-gnu/bitcoin-cc7542cc9552-aarch64-linux-gnu-debug.tar.gz
2267be7ef95cde2c6229f6b64952fd46e79df173041bebb86d2cd32149c0f1d3  guix-build-cc7542cc9552/output/aarch64-linux-gnu/bitcoin-cc7542cc9552-aarch64-linux-gnu.tar.gz
c6aeb65c25318fd6d8490dd73783c1eb6ad9774de235051b8750781cfd7639fa  guix-build-cc7542cc9552/output/arm-linux-gnueabihf/SHA256SUMS.part
abe9b9ed8202242815d1efcfc7e345ff79b34ed880abf091a87b179bc312a4ff  guix-build-cc7542cc9552/output/arm-linux-gnueabihf/bitcoin-cc7542cc9552-arm-linux-gnueabihf-debug.tar.gz
b34ed8fc29b9ac03b96f30d69d10bedbccbacbbfc6fe5a3214d74da457950074  guix-build-cc7542cc9552/output/arm-linux-gnueabihf/bitcoin-cc7542cc9552-arm-linux-gnueabihf.tar.gz
02d95ef4c118304250acce282ab17a6d68b00fffc1e28446bd77755019295959  guix-build-cc7542cc9552/output/arm64-apple-darwin/SHA256SUMS.part
99c6e1c87e679131f1badb3a30b65569500d5f1378c3b0ea4d0bfa1550f682ad  guix-build-cc7542cc9552/output/arm64-apple-darwin/bitcoin-cc7542cc9552-arm64-apple-darwin-unsigned.dmg
5c2ae0147c9675c8a6dc956a0449372d76eb30739e3390d740bcb64af804351e  guix-build-cc7542cc9552/output/arm64-apple-darwin/bitcoin-cc7542cc9552-arm64-apple-darwin-unsigned.tar.gz
f530c398a6620de3f5a0bb7ec5000e449810f809ea70bdbb09b7d8d6039f4dc0  guix-build-cc7542cc9552/output/arm64-apple-darwin/bitcoin-cc7542cc9552-arm64-apple-darwin.tar.gz
d697c2dca125e0af51945034185eb1868df70aab21812ec922d24a933224b5cf  guix-build-cc7542cc9552/output/dist-archive/bitcoin-cc7542cc9552.tar.gz
cb807947b6d729141eda185bf138d3a28aedf936159e70c22dbe6b6cd759db50  guix-build-cc7542cc9552/output/powerpc64-linux-gnu/SHA256SUMS.part
368221a179f97e415dbef1a2d95917ee8ba24bd68a826ae4cc7edb1aa3364c9f  guix-build-cc7542cc9552/output/powerpc64-linux-gnu/bitcoin-cc7542cc9552-powerpc64-linux-gnu-debug.tar.gz
c8c3822c2f16e43a87999c31f7f9821f28344cf745da0009561b823543a0d8e5  guix-build-cc7542cc9552/output/powerpc64-linux-gnu/bitcoin-cc7542cc9552-powerpc64-linux-gnu.tar.gz
ab3ac5f3144cebef532151732045b53d96912ba6e15f88efe3dfc84f939c9ee2  guix-build-cc7542cc9552/output/powerpc64le-linux-gnu/SHA256SUMS.part
1218a9e3dbf5eaa2a23c086d623be03ec9deffd24f3ba58e1765f5bf0cc3d793  guix-build-cc7542cc9552/output/powerpc64le-linux-gnu/bitcoin-cc7542cc9552-powerpc64le-linux-gnu-debug.tar.gz
6f4ad0507d40cd194d9790c4d68795890bcecb32d77f9142e2c1edd06a89c75c  guix-build-cc7542cc9552/output/powerpc64le-linux-gnu/bitcoin-cc7542cc9552-powerpc64le-linux-gnu.tar.gz
7f16d8781b604b4d13c09f2060c2222d17659b1c93a02ca27f9c7285dbcf2c87  guix-build-cc7542cc9552/output/riscv64-linux-gnu/SHA256SUMS.part
f0b2dcca08c6c068c858b715849d3bf33fe10954939383df523f87cbeb17ddaf  guix-build-cc7542cc9552/output/riscv64-linux-gnu/bitcoin-cc7542cc9552-riscv64-linux-gnu-debug.tar.gz
b392a1755d98ca0a58036d04b7291971c05f58964537cc0731d17949fbdfd4bc  guix-build-cc7542cc9552/output/riscv64-linux-gnu/bitcoin-cc7542cc9552-riscv64-linux-gnu.tar.gz
f044eb2a465bd889d7621416b9d5a20edd061e77eb4ab141bc15f13f8640b3d9  guix-build-cc7542cc9552/output/x86_64-apple-darwin/SHA256SUMS.part
af4867fe1d4453e0c257e9b47e58511b39ab84ab8726a8e807f1486e3918cdad  guix-build-cc7542cc9552/output/x86_64-apple-darwin/bitcoin-cc7542cc9552-x86_64-apple-darwin-unsigned.dmg
77ce9fcb94432c5d5b7a66a00620bad0b17ea7790615c2a22cfabd94c73dc0fb  guix-build-cc7542cc9552/output/x86_64-apple-darwin/bitcoin-cc7542cc9552-x86_64-apple-darwin-unsigned.tar.gz
73d41ef67086db682d9655db79704de027334748295cc3983ecae1319a4beab6  guix-build-cc7542cc9552/output/x86_64-apple-darwin/bitcoin-cc7542cc9552-x86_64-apple-darwin.tar.gz
ff396f8749be86ad71d26203b7daffaeec02e882766f7e047738a5324c40f273  guix-build-cc7542cc9552/output/x86_64-linux-gnu/SHA256SUMS.part
2d88d2bbc9219ac7dab2dff9418901e2a3daf7cb71662dfb4be6e845c263bc08  guix-build-cc7542cc9552/output/x86_64-linux-gnu/bitcoin-cc7542cc9552-x86_64-linux-gnu-debug.tar.gz
e9c75bdd41c1cf81a531b578f0d6188939e6c5b023a04e34d838ce11da5e171a  guix-build-cc7542cc9552/output/x86_64-linux-gnu/bitcoin-cc7542cc9552-x86_64-linux-gnu.tar.gz
1540b3997c28e2584900fcf9d8f287be79d36e5135108bf7b41a257153886dc5  guix-build-cc7542cc9552/output/x86_64-w64-mingw32/SHA256SUMS.part
69f77d496676646ee94fe3239c897a0631476dea4d5bea80396aa051a3384d1f  guix-build-cc7542cc9552/output/x86_64-w64-mingw32/bitcoin-cc7542cc9552-win64-debug.zip
87b02e9781a5a5544207cd71f51f78e17d5e496106dac71392d8ac9c125e08a6  guix-build-cc7542cc9552/output/x86_64-w64-mingw32/bitcoin-cc7542cc9552-win64-setup-unsigned.exe
5cc8e5d0d50e10744f8fd628cddf4aed0c1a25635e6d978db697e5d0b14e0cc2  guix-build-cc7542cc9552/output/x86_64-w64-mingw32/bitcoin-cc7542cc9552-win64-unsigned.tar.gz
fa3b4d2d3ed1b8e4e7cd6bb0ca8af4f882ff0238cfbe7d42844aba3f2cd551d0  guix-build-cc7542cc9552/output/x86_64-w64-mingw32/bitcoin-cc7542cc9552-win64.zip
```

### CODE REVIEW

**Comment by fanquake** [comment]
We pass `-system-freetype` when building for Linux, which I would say implies a direct dependency? 
It's also listed here: https://doc.qt.io/qt-5.15/linux-requirements.html, and in our symbol-check.py as an allowed lib.

**Comment by laanwj** [comment]
Right. It would be kind of a waste of binary space if Qt started linking some internal version of freetype. Also there may be conflicts with the one fontconfig links against. I'm not sure this change makes sense.

**Comment by hebasto** [comment]
> We pass `-system-freetype` when building for Linux, which I would say implies a direct dependency?

Actually, `-fontconfig` [implies](https://github.com/qt/qtbase/commit/d179931ada9c9055eb7c86ee264fa5f2e1ec3453) `-system-freetype`.

> It's also listed here: https://doc.qt.io/qt-5.15/linux-requirements.html, and in our symbol-check.py as an allowed lib.

Correct. But this dependency is indirect via Fontconfig.

**Comment by hebasto** [comment]
FWIW, in Qt 6 even `libxkbcommon` is not required as a _build_ dependency.

**Comment by Ferrydh** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by laanwj** [comment]
> Actually, -fontconfig [implies](https://github.com/qt/qtbase/commit/d179931ada9c9055eb7c86ee264fa5f2e1ec3453) -system-freetype.

Right. That makes sense. One wouldn't want two different versions of freetype involved. 

That said, breaking this dependency only makes sense if Qt doesn't directly use freetype at all, not even its headers (it's not only about link dependencies). Pretty sure it does. If it doesn't find it installed, does it use the headers from `./src/3rdparty/freetype`?

**Comment by jarolrod** [comment]
GUIX hashes, mine match @hebasto 

```
02a5522a0e58ff9b330e84922419ea99516fcb1e74ba0e1deb94babe7f5dbf2b  guix-build-cc7542cc9552/output/aarch64-linux-gnu/SHA256SUMS.part
9c6e0f38f37556da2a8e77f920253b81faccd680211e9c5f1c11f6f66c9ea786  guix-build-cc7542cc9552/output/aarch64-linux-gnu/bitcoin-cc7542cc9552-aarch64-linux-gnu-debug.tar.gz
2267be7ef95cde2c6229f6b64952fd46e79df173041bebb86d2cd32149c0f1d3  guix-build-cc7542cc9552/output/aarch64-linux-gnu/bitcoin-cc7542cc9552-aarch64-linux-gnu.tar.gz
c6aeb65c25318fd6d8490dd73783c1eb6ad9774de235051b8750781cfd7639fa  guix-build-cc7542cc9552/output/arm-linux-gnueabihf/SHA256SUMS.part
abe9b9ed8202242815d1efcfc7e345ff79b34ed880abf091a87b179bc312a4ff  guix-build-cc7542cc9552/output/arm-linux-gnueabihf/bitcoin-cc7542cc9552-arm-linux-gnueabihf-debug.tar.gz
b34ed8fc29b9ac03b96f30d69d10bedbccbacbbfc6fe5a3214d74da457950074  guix-build-cc7542cc9552/output/arm-linux-gnueabihf/bitcoin-cc7542cc9552-arm-linux-gnueabihf.tar.gz
02d95ef4c118304250acce282ab17a6d68b00fffc1e28446bd77755019295959  guix-build-cc7542cc9552/output/arm64-apple-darwin/SHA256SUMS.part
99c6e1c87e679131f1badb3a30b65569500d5f1378c3b0ea4d0bfa1550f682ad  guix-build-cc7542cc9552/output/arm64-apple-darwin/bitcoin-cc7542cc9552-arm64-apple-darwin-unsigned.dmg
5c2ae0147c9675c8a6dc956a0449372d76eb30739e3390d740bcb64af804351e  guix-build-cc7542cc9552/output/arm64-apple-darwin/bitcoin-cc7542cc9552-arm64-apple-darwin-unsigned.tar.gz
f530c398a6620de3f5a0bb7ec5000e449810f809ea70bdbb09b7d8d6039f4dc0  guix-build-cc7542cc9552/output/arm64-apple-darwin/bitcoin-cc7542cc9552-arm64-apple-darwin.tar.gz
d697c2dca125e0af51945034185eb1868df70aab21812ec922d24a933224b5cf  guix-build-cc7542cc9552/output/dist-archive/bitcoin-cc7542cc9552.tar.gz
cb807947b6d729141eda185bf138d3a28aedf936159e70c22dbe6b6cd759db50  guix-build-cc7542cc9552/output/powerpc64-linux-gnu/SHA256SUMS.part
368221a179f97e415dbef1a2d95917ee8ba24bd68a826ae4cc7edb1aa3364c9f  guix-build-cc7542cc9552/output/powerpc64-linux-gnu/bitcoin-cc7542cc9552-powerpc64-linux-gnu-debug.tar.gz
c8c3822c2f16e43a87999c31f7f9821f28344cf745da0009561b823543a0d8e5  guix-build-cc7542cc9552/output/powerpc64-linux-gnu/bitcoin-cc7542cc9552-powerpc64-linux-gnu.tar.gz
ab3ac5f3144cebef532151732045b53d96912ba6e15f88efe3dfc84f939c9ee2  guix-build-cc7542cc9552/output/powerpc64le-linux-gnu/SHA256SUMS.part
1218a9e3dbf5eaa2a23c086d623be03ec9deffd24f3ba58e1765f5bf0cc3d793  guix-build-cc7542cc9552/output/powerpc64le-linux-gnu/bitcoin-cc7542cc9552-powerpc64le-linux-gnu-debug.tar.gz
6f4ad0507d40cd194d9790c4d68795890bcecb32d77f9142e2c1edd06a89c75c  guix-build-cc7542cc9552/output/powerpc64le-linux-gnu/bitcoin-cc7542cc9552-powerpc64le-linux-gnu.tar.gz
7f16d8781b604b4d13c09f2060c2222d17659b1c93a02ca27f9c7285dbcf2c87  guix-build-cc7542cc9552/output/riscv64-linux-gnu/SHA256SUMS.part
f0b2dcca08c6c068c858b715849d3bf33fe10954939383df523f87cbeb17ddaf  guix-build-cc7542cc9552/output/riscv64-linux-gnu/bitcoin-cc7542cc9552-riscv64-linux-gnu-debug.tar.gz
b392a1755d98ca0a58036d04b7291971c05f58964537cc0731d17949fbdfd4bc  guix-build-cc7542cc9552/output/riscv64-linux-gnu/bitcoin-cc7542cc9552-riscv64-linux-gnu.tar.gz
f044eb2a465bd889d7621416b9d5a20edd061e77eb4ab141bc15f13f8640b3d9  guix-build-cc7542cc9552/output/x86_64-apple-darwin/SHA256SUMS.part
af4867fe1d4453e0c257e9b47e58511b39ab84ab8726a8e807f1486e3918cdad  guix-build-cc7542cc9552/output/x86_64-apple-darwin/bitcoin-cc7542cc9552-x86_64-apple-darwin-unsigned.dmg
77ce9fcb94432c5d5b7a66a00620bad0b17ea7790615c2a22cfabd94c73dc0fb  guix-build-cc7542cc9552/output/x86_64-apple-darwin/bitcoin-cc7542cc9552-x86_64-apple-darwin-unsigned.tar.gz
73d41ef67086db682d9655db79704de027334748295cc3983ecae1319a4beab6  guix-build-cc7542cc9552/output/x86_64-apple-darwin/bitcoin-cc7542cc9552-x86_64-apple-darwin.tar.gz
ff396f8749be86ad71d26203b7daffaeec02e882766f7e047738a5324c40f273  guix-build-cc7542cc9552/output/x86_64-linux-gnu/SHA256SUMS.part
2d88d2bbc9219ac7dab2dff9418901e2a3daf7cb71662dfb4be6e845c263bc08  guix-build-cc7542cc9552/output/x86_64-linux-gnu/bitcoin-cc7542cc9552-x86_64-linux-gnu-debug.tar.gz
e9c75bdd41c1cf81a531b578f0d6188939e6c5b023a04e34d838ce11da5e171a  guix-build-cc7542cc9552/output/x86_64-linux-gnu/bitcoin-cc7542cc9552-x86_64-linux-gnu.tar.gz
1540b3997c28e2584900fcf9d8f287be79d36e5135108bf7b41a257153886dc5  guix-build-cc7542cc9552/output/x86_64-w64-mingw32/SHA256SUMS.part
69f77d496676646ee94fe3239c897a0631476dea4d5bea80396aa051a3384d1f  guix-build-cc7542cc9552/output/x86_64-w64-mingw32/bitcoin-cc7542cc9552-win64-debug.zip
87b02e9781a5a5544207cd71f51f78e17d5e496106dac71392d8ac9c125e08a6  guix-build-cc7542cc9552/output/x86_64-w64-mingw32/bitcoin-cc7542cc9552-win64-setup-unsigned.exe
5cc8e5d0d50e10744f8fd628cddf4aed0c1a25635e6d978db697e5d0b14e0cc2  guix-build-cc7542cc9552/output/x86_64-w64-mingw32/bitcoin-cc7542cc9552-win64-unsigned.tar.gz
fa3b4d2d3ed1b8e4e7cd6bb0ca8af4f882ff0238cfbe7d42844aba3f2cd551d0  guix-build-cc7542cc9552/output/x86_64-w64-mingw32/bitcoin-cc7542cc9552-win64.zip
```

**Pull request closed without merging**
