### PR TITLE
travis: Run property based testing

### PR DESCRIPTION
**Pull request by maflcko**

### CODE REVIEW

**Comment by practicalswift** [comment]
This is so great to see in actions! Thanks a lot @Christewart for making this happen. Hope to see more contributions from you! :-)

Strong concept ACK

**Comment by practicalswift** [comment]
Why the close? :-)

**Comment by MarcoFalke** [comment]
@practicalswift This is up for grabs. Figuring out what caused this probably needs someone to reproduce locally in a docker container that is set up the same way as the one on travis. Or run with valgrind/asan on travis (remote debugging)

**Comment by Christewart** [comment]
@fanquake I know you expressed interest in picking this up too ^.

**Comment by fanquake** [comment]
Removed "Up for grabs" as this is being re-tried in #14853.

**Pull request closed without merging**
