### PR TITLE
guix: remove cURL from build env

### PR DESCRIPTION
**Pull request by fanquake**
Remove cURL & osslsigncode option.

### CODE REVIEW

**Comment by hebasto** [comment]
Concept ACK.

**Comment by hebasto** [comment]
It is not clear why this is a fix. `CMAKE_DISABLE_FIND_PACKAGE_CURL` is a valid [variable](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html) that:
> can be used to build a project without an optional package

**Comment by hebasto** [comment]
Btw, do we still need this line https://github.com/bitcoin/bitcoin/blob/f467b28ac35add304442f30c2a05ef5d9df496e2/contrib/guix/manifest.scm#L14 at all?

**Comment by hebasto** [comment]
> It is not clear why this is a fix. `CMAKE_DISABLE_FIND_PACKAGE_CURL` is a valid [variable](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html) that:
> 
> > can be used to build a project without an optional package

Considering the `FindCURL` module [source code](https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/FindCURL.cmake), I believe that the current using of the `CMAKE_DISABLE_FIND_PACKAGE_CURL` variable is optimal.

FWIW, the build log contains `-- Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR)` for either variants. It is even possible to drop `(arguments '(#:configure-flags ...))` altogether. But again, the current code in the master branch is the optimal shortcut.

**Comment by fanquake** [comment]
> is the optimal shortcut.

I think I'd rather remove all the dead code. The option confusion comes from the fact that these flags seem to just fail silently if the relevant libraries haven't been compiled/installed with CMake, which I was look at for 2.6.

**Review by hebasto — APPROVED** [review]
ACK 641897a83dc9d40b618efbae67c3beb90a1f34f8

Guix build:
```
7e9b3758aadd87db9c89fec5c05ca7a5020aaebf185daee4f7570dd1eeb23355  guix-build-641897a83dc9/output/aarch64-linux-gnu/SHA256SUMS.part
494f06d1f21ad20aa8cc8f61c4dfeda053215f41bb2aa0bfd47343909edf4dad  guix-build-641897a83dc9/output/aarch64-linux-gnu/bitcoin-641897a83dc9-aarch64-linux-gnu-debug.tar.gz
8a3912a0ff0cb41b87494291ca13bc9caa47ff08d57f37b6d99a9c8e3667390a  guix-build-641897a83dc9/output/aarch64-linux-gnu/bitcoin-641897a83dc9-aarch64-linux-gnu.tar.gz
f19438426160165aaf2b38f0dfb6ee1157789222094c263e8dbee16597a6e54a  guix-build-641897a83dc9/output/arm-linux-gnueabihf/SHA256SUMS.part
92dcc15477eb04a5a16f71eee084cb0d55ded62b9fa8b452a85b2aa44901d4a5  guix-build-641897a83dc9/output/arm-linux-gnueabihf/bitcoin-641897a83dc9-arm-linux-gnueabihf-debug.tar.gz
70a01778667dc0d6b364ab3013c6e0971fd12a1cc8222053390cae660ef463d4  guix-build-641897a83dc9/output/arm-linux-gnueabihf/bitcoin-641897a83dc9-arm-linux-gnueabihf.tar.gz
aa1f695501b520d39ba7c9dffc9d11ef1f28e3e8c1a73ca460148edef4937745  guix-build-641897a83dc9/output/arm64-apple-darwin/SHA256SUMS.part
7ca4c8dce214443fce181fdd1d299e7fdb084623c4f40abe273bf0a915bd3413  guix-build-641897a83dc9/output/arm64-apple-darwin/bitcoin-641897a83dc9-arm64-apple-darwin-unsigned.dmg
decd8b6a3e25faba192d5b305dbb55bdb1a263a7a034acfce209e96188df35df  guix-build-641897a83dc9/output/arm64-apple-darwin/bitcoin-641897a83dc9-arm64-apple-darwin-unsigned.tar.gz
a807d6597324b00753b8e69666ba0caf0cc42ef42125b88979f32a676024a356  guix-build-641897a83dc9/output/arm64-apple-darwin/bitcoin-641897a83dc9-arm64-apple-darwin.tar.gz
c262ce97ddba6599c27849b7a6d0d911ca43a84e36cb16d66537115b23f0f6ab  guix-build-641897a83dc9/output/dist-archive/bitcoin-641897a83dc9.tar.gz
0dceb5a7fef96a796066cfcb4a1ed6c42eec6e49c27fa58da3e4001347951e4d  guix-build-641897a83dc9/output/powerpc64-linux-gnu/SHA256SUMS.part
ffd89d8148e2fd7b7e9c5eeb9b5aa3c6ef516c993d863ae31cfd081d279cace9  guix-build-641897a83dc9/output/powerpc64-linux-gnu/bitcoin-641897a83dc9-powerpc64-linux-gnu-debug.tar.gz
ed4476ecf3d2bf3e97528466439c36b53c29ff6c536801802014c36d54b3df2f  guix-build-641897a83dc9/output/powerpc64-linux-gnu/bitcoin-641897a83dc9-powerpc64-linux-gnu.tar.gz
61dc2842797a67314f9993be99751a8d11fd54dcedeca26fa749bb4239f4b6cf  guix-build-641897a83dc9/output/powerpc64le-linux-gnu/SHA256SUMS.part
c08afb422c14c2efadc9dc677ff96cec415046205d36240b04928a5e37d66085  guix-build-641897a83dc9/output/powerpc64le-linux-gnu/bitcoin-641897a83dc9-powerpc64le-linux-gnu-debug.tar.gz
03c006460944d79a33db17771f250dc0d3a2f6ad776e6e828d470bbbd3e486fb  guix-build-641897a83dc9/output/powerpc64le-linux-gnu/bitcoin-641897a83dc9-powerpc64le-linux-gnu.tar.gz
9eacf7b79dacce548e0cfc488e24395e58f2f6ac720daf240720a5ff7f4022f0  guix-build-641897a83dc9/output/riscv64-linux-gnu/SHA256SUMS.part
c8b2512129717d97fd3f3a8e318e4fbd16b8f30a648499810ef78c1f4921c0dc  guix-build-641897a83dc9/output/riscv64-linux-gnu/bitcoin-641897a83dc9-riscv64-linux-gnu-debug.tar.gz
00f6924fd605e9cc570e558718d81276def828fa18cc5f7b91d2a1a5b9892e9b  guix-build-641897a83dc9/output/riscv64-linux-gnu/bitcoin-641897a83dc9-riscv64-linux-gnu.tar.gz
26a4ddc43073deab4262e97d80fc62d5d4ad631ab9a30a26348868d270815c5a  guix-build-641897a83dc9/output/x86_64-apple-darwin/SHA256SUMS.part
5e8da34fa268bf02aabb96429617666696bafa0b94b409492f8f25d5032e7523  guix-build-641897a83dc9/output/x86_64-apple-darwin/bitcoin-641897a83dc9-x86_64-apple-darwin-unsigned.dmg
976b79c3090defa1e8ae1c2f8e41093ecc6a73a31fa125abcae74cef8e0708c6  guix-build-641897a83dc9/output/x86_64-apple-darwin/bitcoin-641897a83dc9-x86_64-apple-darwin-unsigned.tar.gz
b94d9f00cd31637fd8dfe668716f086efeb63ec49d7b74927bdd9730fa1d3c5a  guix-build-641897a83dc9/output/x86_64-apple-darwin/bitcoin-641897a83dc9-x86_64-apple-darwin.tar.gz
dc0e65ec526c414b8ccebcbfa8ded492e3f27bbab8fb57108adf9c7663aa4d22  guix-build-641897a83dc9/output/x86_64-linux-gnu/SHA256SUMS.part
ba4f435ca40dc5e7c362e2a97261a859539b77163240a77c4287083a17b061d7  guix-build-641897a83dc9/output/x86_64-linux-gnu/bitcoin-641897a83dc9-x86_64-linux-gnu-debug.tar.gz
2bec39933491b20fc19629162a7023b6dc2cd8af764a9c0662727d7ec850eb60  guix-build-641897a83dc9/output/x86_64-linux-gnu/bitcoin-641897a83dc9-x86_64-linux-gnu.tar.gz
2081c799fa94f6780784d4211684a627de36b222841fe14383c87b1fa9df57e2  guix-build-641897a83dc9/output/x86_64-w64-mingw32/SHA256SUMS.part
dcebd386a4d58cfe88918c004c80874a3e4336fd86e7a02842ead8bd7351205d  guix-build-641897a83dc9/output/x86_64-w64-mingw32/bitcoin-641897a83dc9-win64-debug.zip
41bc2827c9cd9ef9a12c448497d0f1891ad4fa4c930651ecc9222ce959aeec1e  guix-build-641897a83dc9/output/x86_64-w64-mingw32/bitcoin-641897a83dc9-win64-setup-unsigned.exe
6ae282bb727627fbe4c56b21abdb3f1f8b223b3af01b1dbba234e1a7f3c440c7  guix-build-641897a83dc9/output/x86_64-w64-mingw32/bitcoin-641897a83dc9-win64-unsigned.tar.gz
d1a283fcec7faa8474fb3ea8b9102ce9b1bd41f0280a2813ea07ff2175153058  guix-build-641897a83dc9/output/x86_64-w64-mingw32/bitcoin-641897a83dc9-win64.zip
```

**Review by sedited — APPROVED** [review]
ACK 641897a83dc9d40b618efbae67c3beb90a1f34f8

Guix build:
```
find guix-build-$(git rev-parse --short=12 HEAD)/output/ -type f -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum
7e9b3758aadd87db9c89fec5c05ca7a5020aaebf185daee4f7570dd1eeb23355  guix-build-641897a83dc9/output/aarch64-linux-gnu/SHA256SUMS.part
494f06d1f21ad20aa8cc8f61c4dfeda053215f41bb2aa0bfd47343909edf4dad  guix-build-641897a83dc9/output/aarch64-linux-gnu/bitcoin-641897a83dc9-aarch64-linux-gnu-debug.tar.gz
8a3912a0ff0cb41b87494291ca13bc9caa47ff08d57f37b6d99a9c8e3667390a  guix-build-641897a83dc9/output/aarch64-linux-gnu/bitcoin-641897a83dc9-aarch64-linux-gnu.tar.gz
f19438426160165aaf2b38f0dfb6ee1157789222094c263e8dbee16597a6e54a  guix-build-641897a83dc9/output/arm-linux-gnueabihf/SHA256SUMS.part
92dcc15477eb04a5a16f71eee084cb0d55ded62b9fa8b452a85b2aa44901d4a5  guix-build-641897a83dc9/output/arm-linux-gnueabihf/bitcoin-641897a83dc9-arm-linux-gnueabihf-debug.tar.gz
70a01778667dc0d6b364ab3013c6e0971fd12a1cc8222053390cae660ef463d4  guix-build-641897a83dc9/output/arm-linux-gnueabihf/bitcoin-641897a83dc9-arm-linux-gnueabihf.tar.gz
aa1f695501b520d39ba7c9dffc9d11ef1f28e3e8c1a73ca460148edef4937745  guix-build-641897a83dc9/output/arm64-apple-darwin/SHA256SUMS.part
7ca4c8dce214443fce181fdd1d299e7fdb084623c4f40abe273bf0a915bd3413  guix-build-641897a83dc9/output/arm64-apple-darwin/bitcoin-641897a83dc9-arm64-apple-darwin-unsigned.dmg
decd8b6a3e25faba192d5b305dbb55bdb1a263a7a034acfce209e96188df35df  guix-build-641897a83dc9/output/arm64-apple-darwin/bitcoin-641897a83dc9-arm64-apple-darwin-unsigned.tar.gz
a807d6597324b00753b8e69666ba0caf0cc42ef42125b88979f32a676024a356  guix-build-641897a83dc9/output/arm64-apple-darwin/bitcoin-641897a83dc9-arm64-apple-darwin.tar.gz
c262ce97ddba6599c27849b7a6d0d911ca43a84e36cb16d66537115b23f0f6ab  guix-build-641897a83dc9/output/dist-archive/bitcoin-641897a83dc9.tar.gz
0dceb5a7fef96a796066cfcb4a1ed6c42eec6e49c27fa58da3e4001347951e4d  guix-build-641897a83dc9/output/powerpc64-linux-gnu/SHA256SUMS.part
ffd89d8148e2fd7b7e9c5eeb9b5aa3c6ef516c993d863ae31cfd081d279cace9  guix-build-641897a83dc9/output/powerpc64-linux-gnu/bitcoin-641897a83dc9-powerpc64-linux-gnu-debug.tar.gz
ed4476ecf3d2bf3e97528466439c36b53c29ff6c536801802014c36d54b3df2f  guix-build-641897a83dc9/output/powerpc64-linux-gnu/bitcoin-641897a83dc9-powerpc64-linux-gnu.tar.gz
61dc2842797a67314f9993be99751a8d11fd54dcedeca26fa749bb4239f4b6cf  guix-build-641897a83dc9/output/powerpc64le-linux-gnu/SHA256SUMS.part
c08afb422c14c2efadc9dc677ff96cec415046205d36240b04928a5e37d66085  guix-build-641897a83dc9/output/powerpc64le-linux-gnu/bitcoin-641897a83dc9-powerpc64le-linux-gnu-debug.tar.gz
03c006460944d79a33db17771f250dc0d3a2f6ad776e6e828d470bbbd3e486fb  guix-build-641897a83dc9/output/powerpc64le-linux-gnu/bitcoin-641897a83dc9-powerpc64le-linux-gnu.tar.gz
9eacf7b79dacce548e0cfc488e24395e58f2f6ac720daf240720a5ff7f4022f0  guix-build-641897a83dc9/output/riscv64-linux-gnu/SHA256SUMS.part
c8b2512129717d97fd3f3a8e318e4fbd16b8f30a648499810ef78c1f4921c0dc  guix-build-641897a83dc9/output/riscv64-linux-gnu/bitcoin-641897a83dc9-riscv64-linux-gnu-debug.tar.gz
00f6924fd605e9cc570e558718d81276def828fa18cc5f7b91d2a1a5b9892e9b  guix-build-641897a83dc9/output/riscv64-linux-gnu/bitcoin-641897a83dc9-riscv64-linux-gnu.tar.gz
26a4ddc43073deab4262e97d80fc62d5d4ad631ab9a30a26348868d270815c5a  guix-build-641897a83dc9/output/x86_64-apple-darwin/SHA256SUMS.part
5e8da34fa268bf02aabb96429617666696bafa0b94b409492f8f25d5032e7523  guix-build-641897a83dc9/output/x86_64-apple-darwin/bitcoin-641897a83dc9-x86_64-apple-darwin-unsigned.dmg
976b79c3090defa1e8ae1c2f8e41093ecc6a73a31fa125abcae74cef8e0708c6  guix-build-641897a83dc9/output/x86_64-apple-darwin/bitcoin-641897a83dc9-x86_64-apple-darwin-unsigned.tar.gz
b94d9f00cd31637fd8dfe668716f086efeb63ec49d7b74927bdd9730fa1d3c5a  guix-build-641897a83dc9/output/x86_64-apple-darwin/bitcoin-641897a83dc9-x86_64-apple-darwin.tar.gz
dc0e65ec526c414b8ccebcbfa8ded492e3f27bbab8fb57108adf9c7663aa4d22  guix-build-641897a83dc9/output/x86_64-linux-gnu/SHA256SUMS.part
ba4f435ca40dc5e7c362e2a97261a859539b77163240a77c4287083a17b061d7  guix-build-641897a83dc9/output/x86_64-linux-gnu/bitcoin-641897a83dc9-x86_64-linux-gnu-debug.tar.gz
2bec39933491b20fc19629162a7023b6dc2cd8af764a9c0662727d7ec850eb60  guix-build-641897a83dc9/output/x86_64-linux-gnu/bitcoin-641897a83dc9-x86_64-linux-gnu.tar.gz
2081c799fa94f6780784d4211684a627de36b222841fe14383c87b1fa9df57e2  guix-build-641897a83dc9/output/x86_64-w64-mingw32/SHA256SUMS.part
dcebd386a4d58cfe88918c004c80874a3e4336fd86e7a02842ead8bd7351205d  guix-build-641897a83dc9/output/x86_64-w64-mingw32/bitcoin-641897a83dc9-win64-debug.zip
41bc2827c9cd9ef9a12c448497d0f1891ad4fa4c930651ecc9222ce959aeec1e  guix-build-641897a83dc9/output/x86_64-w64-mingw32/bitcoin-641897a83dc9-win64-setup-unsigned.exe
6ae282bb727627fbe4c56b21abdb3f1f8b223b3af01b1dbba234e1a7f3c440c7  guix-build-641897a83dc9/output/x86_64-w64-mingw32/bitcoin-641897a83dc9-win64-unsigned.tar.gz
d1a283fcec7faa8474fb3ea8b9102ce9b1bd41f0280a2813ea07ff2175153058  guix-build-641897a83dc9/output/x86_64-w64-mingw32/bitcoin-641897a83dc9-win64.zip
```

**Pull request merged**
