### PR TITLE
Fix CNetAddr::IsRFC2544 comment + tests

### PR DESCRIPTION
**Pull request by tynes**
The comment describing the functionality of `CNetAddr::IsRFC2544` is incorrect.

https://github.com/bitcoin/bitcoin/blob/46d6930f8c7ba7cbcd7d86dd5d0117642fcbc819/src/netaddress.h#L57

It should actually read `198.18.0.0/15` based on [RFC 3330](https://tools.ietf.org/html/rfc3330):

```
   198.18.0.0/15 - This block has been allocated for use in benchmark
   tests of network interconnect devices.  Its use is documented in
   [RFC2544].
```

See [RFC 2544](https://tools.ietf.org/html/rfc2544) here.

See the implementation here:

https://github.com/bitcoin/bitcoin/blob/47d981e8273804a040d71665a4cb16038d6717e1/src/netaddress.cpp#L142-L145

This PR also adds tests for the minimum and maximum values that are valid RFC 2544 addresses.

### CODE REVIEW

**Comment by practicalswift** [comment]
Good catch and nice first-time contribution! Hope to see more contributions from you in the future :)

ACK 529d332fbfe633d60845a97e1a06f552bd63d0d4

```
$ ipcalc 198.18.0.0/15
Address:   198.18.0.0           11000110.0001001 0.00000000.00000000
Netmask:   255.254.0.0 = 15     11111111.1111111 0.00000000.00000000
Wildcard:  0.1.255.255          00000000.0000000 1.11111111.11111111
=>
Network:   198.18.0.0/15        11000110.0001001 0.00000000.00000000
HostMin:   198.18.0.1           11000110.0001001 0.00000000.00000001
HostMax:   198.19.255.254       11000110.0001001 1.11111111.11111110
Broadcast: 198.19.255.255       11000110.0001001 1.11111111.11111111
Hosts/Net: 131070                Class C
```

**Review by promag — COMMENTED** [review]
ACK 529d332fbfe633d60845a97e1a06f552bd63d0d4, nit could squash.

**Review by jonatack — COMMENTED** [review]
ACK 529d332fbfe633d60845a97e1a06f552bd63d0d4

**Comment by laanwj** [comment]
ACK 529d332fbfe633d60845a97e1a06f552bd63d0d4

**Comment by tynes** [comment]
@practicalswift Thank you for the encouragement! :)

**Pull request merged**
