### PR TITLE
minor changes in db/walletdb (e.g. constify some std::string references)

### PR DESCRIPTION
**Pull request by Diapolo**

### CODE REVIEW

**Comment by laanwj** [comment]
ACK on d9727fb 4000726 4fbfbf9
NACK on 0134b6b, the change in CDBEnv::CloseDb is unnecessary, and the rest of the changes are just some idle whitespace changes and move-declarations-around.

**Comment by Diapolo** [comment]
@laanwj Removed number 4.

**Comment by laanwj** [comment]
Now that the newwallet work is starting (#5686). I want to discourage any changes to the old wallet code not strictly necessary. So I'm closing this, sorry.

**Comment by Diapolo** [comment]
Yeah nothing new...

**Pull request closed without merging**
