### PR TITLE
index: make indices robust against init aborts

### PR DESCRIPTION
**Pull request by mzumsande**
When an index thread receives an interrupt during init before it got to index anything (so `m_best_block_index == nullptr` still), it will still try to commit previous "work" before stopping the thread. That means that `BaseIndex::CommitInternal()` calls `GetLocator(nullptr)`, which returns an locator to the tip ([code](https://github.com/bitcoin/bitcoin/blob/06b6369766137756648b3cb62c8f385cca234e69/src/chain.cpp#L31-L32)), and saves it to the index DB.
On the next startup, this locator will be read and it will be assumed that we have successfully synced the index to the tip, when in reality we have indexed nothing.
In the case of coinstatsindex, this would lead to a shutdown of bitcoind without any indication what went wrong. For the other indexes, there would be no immediate shutdown, but the index would be corrupt.

This PR fixes this by not committing when `m_best_block_index==nullptr`, and it also adds an error log message to the silent coinstatsindex shutdown path.

This is another small bug found by `feature_init.py` - the second commit enables blockfilterindex and coinstatsindex for this test, enabling coinstatsindex without the first commit would have led to frequent failures.

### CODE REVIEW

**Comment by mzumsande** [comment]
fyi @fjahr @jamesob

**Comment by jamesob** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/24117/commits/e87ee7569b08c6ad2e859ae568d85ae2b213b33c pending CI

Nice find! Code looks good.

**Review by Successahead — APPROVED** [review]

**Comment by fjahr** [comment]
Concept ACK

> enabling coinstatsindex without the first commit would have led to frequent failures.

Can you expand on this? I did not get any failures when I removed the changes from the first commit.

**Review by shaavan — APPROVED** [review]
Code Review ACK e87ee7569b08c6ad2e859ae568d85ae2b213b33c

It makes sense not to commit when nothing is indexed, and I agree with it. The updates done to the test file are logical and make sense. The `feature_init.py` test ran successfully on the PR branch.

However, I was not able to verify this claim:
> enabling coinstatsindex without the first commit would have led to frequent failures.

I ran the updated test multiple times on master, and it was successful each time.

**Comment by mzumsande** [comment]
> Can you expand on this? I did not get any failures when I removed the changes from the first commit.

> I ran the updated test multiple times on master, and it was successful each time.

That's interesting! For me, it fails in the first part, between the runs for the expected lines `init message: Verifying blocks` (where the index gets corruptedafter the interrupt) and `init message: Starting network threads` (where the nodes fails to start because coinstatsindex terminates bitcoind). 
I just ran the updated test on current master 50 times and got 26 failures, so it fails ~50% of the time for me.

But I think it is possible that the timing can be different on different systems - the interrupt must come at a specific point in time during init for the failure to occur, so having a faster or slower system might change things a lot.

**Comment by fjahr** [comment]
Ok, I still think the changes are valuable even though I can not reproduce the failure.

Code review ACK e87ee75

**Comment by mzumsande** [comment]
Rebased

**Comment by fjahr** [comment]
reACK bfcd60f5d505334230013de4115483b22a7898ee

**Review by shaavan — APPROVED** [review]
reACK bfcd60f5d505334230013de4115483b22a7898ee

Changes since my last review:
- The PR is rebased which leading to removal of line: `node.start(extra_args=['-txindex=1', '-blockfilterindex=1', '-coinstatsindex=1'])` where it was no more needed.

I agree with @fjahr. Though I could not reproduce the intended failure, I think that these changes are valuable in their own right and can be merged.

**Comment by Sjors** [comment]
I still managed to corrupt this index during a spontaneous machine reboot, on the latest master. Unfortunately I forgot to keep a copy for more debugging.

```
2022-06-14T18:07:41Z coinstatsindex thread start
2022-06-14T18:07:41Z Syncing coinstatsindex with block chain from height 0
2022-06-14T18:07:41Z ERROR: Commit: Failed to commit latest coinstatsindex state
```

**Comment by Sjors** [comment]
Unfortunately I didn't track this very well, because I only found out some days ofter the reboot. My `uptime` says 20 days, so I guess it wasn't even a full reboot, just enough for macOS to kill every application that was running. In other words, I don't know when it happened relative to the log entries.

**Pull request merged**
