### PR TITLE
wallet: Remove unnecessary mempool lock in ReacceptWalletTransactions

### PR DESCRIPTION
**Pull request by promag**

### CODE REVIEW

**Comment by promag** [comment]
@TheBlueMatt FYI.

**Comment by sipa** [comment]
utACK 5b252934362c2971e521df56c26ced56f07deb72. ATMPWorker grabs this lock itself.

**Comment by jonasschnelli** [comment]
utACK 5b252934362c2971e521df56c26ced56f07deb72

**Comment by TheBlueMatt** [comment]
This is incorrect since #11839, but would be fixed by #11866. utACK if rebased on #11866.

**Comment by TheBlueMatt** [comment]
utACK 5b252934362c2971e521df56c26ced56f07deb72

**Pull request merged**
