### PR TITLE
[TRIVIAL] Drop C headers in favour of C++-compatibility headers.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Thanks for contributing.
Please also read https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#refactoring

**Comment by MarcoFalke** [comment]
Related pull: #11261

**Comment by kekimusmaximus** [comment]
There is though some utility to using the c++ headers. For example most math functions in C have arguments as double while in C++ the arguments are both floats and double and long double.

I actually ended up doing this while I've seen a warning in some log10 usage saying that float was used and extended to double or something along the lines. Not a big deal though.

Another benefit of using C++ headers is that names in the standard library are quite common and when you don't use namespaces you might shot yourself in the foot.

And contrary to comments in the pull #11261 you don't need to specify the namespace for the integer types, that would be just overkill.

Of course it's not a priority but as I was looking at the code I just picked some low hanging fruits.

**Review by bolekC — COMMENTED** [review]
Any good reason why you have chosen only these 63 files for update?

**Comment by kekimusmaximus** [comment]
I should have also included header files, I now realize, this shouldn't be a problem to add.

I skipped over univalue as when compiling it is not compiled using the -std=c++11 CXXFLAG.

Unlike #11261 I did not replace <limits.h> with <climits> as they do not provide similar information (see http://pubs.opengroup.org/onlinepubs/009695399/basedefs/limits.h.html)

**Comment by practicalswift** [comment]
Concept ACK (see my PR #11261). But it should be done as a `scripted-diff`.

**Comment by laanwj** [comment]
This is not worth doing, IMO. It generates a ton of code churn and just really doesn't matter.

**Pull request closed without merging**
