### PR TITLE
ci: Use qemu-user through container engine

### PR DESCRIPTION
**Pull request by maflcko**
Currently the CI containers always run on the host architecture, and only wrap `bitcoind` into `qemu-user` when needed. This has many issues:

* The `i386` tasks can not be run on non-x86 hosts.
* `config.guess` isn't present when building the CI image, which is fine. But it prints a warning, see https://github.com/bitcoin/bitcoin/pull/27739#pullrequestreview-1446580353
* The python tests are run on the host architecture, making it harder to find architecture specific bugs. See for example https://github.com/bitcoin/bitcoin/pull/27529#issuecomment-1521387810
* All modern container engines support automatic dispatch to qemu-user, so it seems redundant to re-invent the wheel.

Fix all issues by:
* removing `HOST` from `ci/test/00_setup_env.sh`.
* removing `QEMU_USER_CMD` and `ci/test/wrap-qemu.sh`.
* removing `DPKG_ADD_ARCH` where possible, and pruning `PACKAGES` where possible.
* specifying the architecture in `CI_IMAGE_NAME_TAG` to be used by the container engine.

### CODE REVIEW

**Comment by willcl-ark** [comment]
I don't think I can give this much competent review I'm afraid. Partly because I can't get it working locally, and partly because I don't feel like I understand the changes fully yet.

I did try to run `MAKEJOBS="-j$(nproc)" FILE_ENV="./ci/test/00_setup_env_s390x.sh" ./ci/test_run_all.sh`, but it takes more than 2 hours to run (amd64 local arch), and I keep getting (possibly) unrelated errors like this: [390x_build_error.txt](https://github.com/bitcoin/bitcoin/files/12180726/390x_build_error.txt)

I do have some questions for my own understanding though...

Am I right in understanding that in the new setup, docker is using qemu and binfmt-misc from the container engines' kernel to run (emulate) e.g. the `"docker.io/s390x/debian:bookworm"` image, and that this is _roughly_ the same (but simpler to configure from our side) than running an x86 image, manually installing qemu, and then wrapping our various binaries in it. But it also achieves "The python tests are run on the host architecture, making it harder to find architecture specific bugs"?

**Comment by willcl-ark** [comment]
Thanks Marco, thats a very helpful explanation (and I nice changes for us!).

I will give it another go this afternoon after trying to update qemu.

**Comment by willcl-ark** [comment]
@MarcoFalke 

> Yes, this is expected. Instead of just running `bitcoind` through qemu, now the whole container is run through qemu.

Ok running this again... to setup and build Depends still takes more than an hour for me (with it taking 56 mins to progress past  `building qt`) which seems relatively annoying. Am I correct that this build will use a depends cache on actual CI though, which should speed it up there significantly?

**Comment by willcl-ark** [comment]
Unfortunately that build broke again for me for another seemingly unrealted reason. I have the correct version of qemu this time for sure:

```log
will@ubuntu in ~
$ qemu-s390x --version
qemu-s390x version 7.2.0 (Debian 1:7.2+dfsg-5ubuntu2.2)
Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developers
```

I don't think I can test this on my side, but I am a concept ACK on these changes, and they _look_ correct to me.

**Review by fanquake — APPROVED** [review]
ACK fad0b67c212dcb8a16fcbda5a74acc959ed4e284 - this seems ok to me, and removes complexity from our CI system.

I've locally tested the ENVs changed here, and seen the associated slowdown / resource consumption. Had GCC segfault more than once when cross-compiling s390x.

**Pull request merged**
