### PR TITLE
[0.20] final rc2 backports

### PR DESCRIPTION
**Pull request by maflcko**

### CODE REVIEW

**Comment by fanquake** [comment]
The backport of https://github.com/bitcoin/bitcoin/commit/a4118c6e200e02e7560f8bc213697aa2909d95b1 here needs to be slightly different also. I've got a version you can pull in here: https://github.com/fanquake/bitcoin/commit/5d5cf12738d04f9212d3108f5afc5686fd361bad.

**Comment by MarcoFalke** [comment]
Thanks, ci macos cross build is green now

**Comment by MarcoFalke** [comment]
Dropped the build system change. This only contains some minor doc fixups. Can be merged or closed before rc2, no strong opinion.

**Review by fanquake — APPROVED** [review]
ACK 19bcf178485c7d2c353581e514582bd569c66c00

**Comment by benthecarman** [comment]
ACK 19bcf17

**Comment by MarcoFalke** [comment]
@laanwj Friendly ping

**Pull request merged**
