### PR TITLE
tests: simplify next_block() function in feature_block

### PR DESCRIPTION
**Pull request by jnewbery**
The solve parameter is unnecessary. Remove it and add comments.

### CODE REVIEW

**Comment by jnewbery** [comment]
follow-up from #18355 

@MarcoFalke @TheQuantumPhysicist

**Comment by MarcoFalke** [comment]
ACK 612a931d1a3ac1678d02aed30c48fd25ccd113db

Fine with me

**Comment by TheQuantumPhysicist** [comment]
ACK 612a931

Looks good. Thanks for improving it :smile:

**Comment by practicalswift** [comment]
ACK 612a931d1a3ac1678d02aed30c48fd25ccd113db -- simpler is better and patch looks correct :)

**Pull request merged**
