### PR TITLE
[trivial] fix white space in rpc help messages

### PR DESCRIPTION
**Pull request by maflcko**
This should format all rpc help messages correctly

---

To verify this is mostly white space fixing, you may use ?w= https://github.com/bitcoin/bitcoin/pull/6866/files?w=

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Did you test the help output? I think because of \" some of the off-track spaces where correct.

**Comment by paveljanik** [comment]
bResult -> Result ACK
NACK the rest, please test the output first.

**Comment by MarcoFalke** [comment]
NACK myself. I think an internal output formatter is the way to go.

**Comment by paveljanik** [comment]
But do not forget to submit `bResult` typo within some later PR please.

**Pull request closed without merging**
