### PR TITLE
Update gitian signing key of jl2012

### PR DESCRIPTION
**Pull request by jl2012**

### CODE REVIEW

**Comment by fanquake** [comment]
utACK 9b0d8ef, the test failure is unrelated.
```
..........
p2p-compactblocks.py:
...snip...
Failed
stderr:
  File "/home/travis/build/bitcoin/bitcoin/qa/rpc-tests/test_framework/test_framework.py", line 148, in main
    self.run_test()
  File "/home/travis/build/bitcoin/bitcoin/build/../qa/rpc-tests/p2p-compactblocks.py", line 809, in run_test
    sync_blocks(self.nodes)
  File "/home/travis/build/bitcoin/bitcoin/qa/rpc-tests/test_framework/util.py", line 138, in sync_blocks
    raise AssertionError("Block sync failed")
Pass: False, Duration: 100 s
```

**Comment by jonasschnelli** [comment]
utACK
@jl2012 maybe post a signature done with your old key here for consistency?

**Comment by MarcoFalke** [comment]
So what happened to the old key?

```
$ gpg --fingerprint jl2012
pub   4096R/B3936517 2015-10-16
      Key fingerprint = D3CC 1772 8600 5BB8 FF67  3294 C524 2A1A B393 6517

**Comment by MarcoFalke** [comment]
Concept NACK from me. This is the same key, it seems.

**Comment by jl2012** [comment]
@MarcoFalke The self-signature of the key was expired in August. This one has the new signature

**Comment by laanwj** [comment]
At some point it was decided not to update keys in this repository unless the actual key changed, to minimize diff noise (see e.g. discussion in #8547).

People are however advised to run `gpg --refresh-keys` after importing: https://github.com/bitcoin/bitcoin/pull/8603

**Comment by jl2012** [comment]
OK, closing

**Pull request closed without merging**
