### PR TITLE
doc: fix typo in interface_usdt_utxocache.py

### PR DESCRIPTION
**Pull request by mxaddict**

### CODE REVIEW

**Comment by 0xB10C** [comment]
ACK

**Comment by fanquake** [comment]
Can you update the commit message to the same as what I've changed the PR title too: `doc: fix typo in interface_usdt_utxocache.py`.

**Comment by mxaddict** [comment]
Sure

**Comment by paulkania** [comment]
I was under the impression PRs like this were pointless time-sinks on the maintainers' time.

**Comment by mxaddict** [comment]
> I was under the impression PRs like this were pointless time-sinks on the maintainers' time.

Makes sense

**Pull request closed without merging**
