### PR TITLE
depends: build expat with CMake

### PR DESCRIPTION
**Pull request by fanquake**
Switch to building Expat with CMake, instead of Autotools.

### CODE REVIEW

**Comment by fanquake** [comment]
Looks like there could be issues with expat, CMake and 32-bit builds:
* https://cirrus-ci.com/task/6695396838211584
* https://cirrus-ci.com/task/5850971908079616

**Comment by tobtoht** [comment]
(Testing a script I'm developing on this PR)

- [x] This package was signed with a GPG key that was used to sign a previous release: `3176EF7DB2367F1FCA4F306B1F9B0E909AF37285`
- [x] All files in common with the git repository have matching hashes. 
- [ ] 26 files present in the tarball are not present in the git repository for a total of 57709 lines: https://paste.debian.net/plainh/ba0edfca
- [ ] After removal of the files above, this package contains no binaries, no archives and 4 generated scripts: https://paste.debian.net/plainh/ed6bbbc7

**Comment by fanquake** [comment]
> 26 files present in the tarball are not present in the git repository for a total of 57709 lines: https://paste.debian.net/plainh/ba0edfca
> After removal of the files above, this package contains no binaries, no archives and 4 generated scripts: https://paste.debian.net/plainh/ed6bbbc7

I've pushed a change that switches to downloading the unbootstraped source tarball. Want to re-run your script?

**Comment by tobtoht** [comment]
>Want to re-run your script?

- [x] No signature file found, however git tag `R_2_6_2` is signed with a GPG key that was used to sign a previous release: `3176EF7DB2367F1FCA4F306B1F9B0E909AF37285`
- [x] All files in common with the git repository have matching hashes.
- [x] Tarball does not contain any files that are not present in the git repository.
- [ ] This package contains no binaries, no archives and 4 generated scripts: https://paste.debian.net/plainh/beafa9aa

Those generated scripts are short and look harmless, btw.

>I've pushed a change that switches to downloading the unbootstraped source tarball.

GitHub generated source archives may not have stable hashes: https://github.blog/2023-02-21-update-on-the-future-stability-of-source-code-archives-and-hashes/

I'm not sure if `depends` currently supports this, but falling back to the mirror on a hash mismatch may be sensible.

**Comment by fanquake** [comment]
Rebased on master. 32-bit builds should also be fixed. No longer a version bump, just a Autotools -> CMake switch.

**Comment by fanquake** [comment]
Guix Build (x86_64, aarch64):
```bash
cd661a8196c71db10430898b78555489f2fb5a1b1e35bb633c18a5d21692bc3d  guix-build-6ccf95586047/output/aarch64-linux-gnu/SHA256SUMS.part
8c340c73ed52b60db257032f18cc39db2ffee35f78c67f8fe4dc67557f33ebb7  guix-build-6ccf95586047/output/aarch64-linux-gnu/bitcoin-6ccf95586047-aarch64-linux-gnu-debug.tar.gz
f77bf0c350d58b9a8755e1fab3c560e5aa1e5202181ddab0c098d3f9da96863f  guix-build-6ccf95586047/output/aarch64-linux-gnu/bitcoin-6ccf95586047-aarch64-linux-gnu.tar.gz
16980ad25d964d83ef728a44f47fdc85a863da611ad0b7c8429fdd1ff3a9cbce  guix-build-6ccf95586047/output/arm-linux-gnueabihf/SHA256SUMS.part
d34eb0c7a905165586bf094066e6514088c8fdec3570296cdaf156028dbe2434  guix-build-6ccf95586047/output/arm-linux-gnueabihf/bitcoin-6ccf95586047-arm-linux-gnueabihf-debug.tar.gz
458c337e086b99753a55b56f9cb14c022c7a883fdf9ebe98fcfd53e472e621ea  guix-build-6ccf95586047/output/arm-linux-gnueabihf/bitcoin-6ccf95586047-arm-linux-gnueabihf.tar.gz
59aca12ddb9265622abf6e1a63d011ea056b7e84a45d2824afa8b494df0e1c34  guix-build-6ccf95586047/output/arm64-apple-darwin/SHA256SUMS.part
bc9f6f664f3f57993890b21a7ace8631dda2b4d8cd59a171a6f42a76c65b0baa  guix-build-6ccf95586047/output/arm64-apple-darwin/bitcoin-6ccf95586047-arm64-apple-darwin-unsigned.tar.gz
23e9e94e6c472552175a124ce24bcb587d109abe1fa634567e257d99f97b4450  guix-build-6ccf95586047/output/arm64-apple-darwin/bitcoin-6ccf95586047-arm64-apple-darwin-unsigned.zip
3680fb7a35d0c96b4f57c834c2ec64c7509b052c9c5870caf10b88514cc8fa9a  guix-build-6ccf95586047/output/arm64-apple-darwin/bitcoin-6ccf95586047-arm64-apple-darwin.tar.gz
59bd07c2d44da31c84eb212ffe222e8231af2fe4cf27442c2eeaeedba619b7eb  guix-build-6ccf95586047/output/dist-archive/bitcoin-6ccf95586047.tar.gz
2c191c87284ca97102bd2ef75ae603d47139fcd7232d2f00dad0cda4895e25f2  guix-build-6ccf95586047/output/powerpc64-linux-gnu/SHA256SUMS.part
ccc61296748f43b77ced8cbeaed535ca4c1cac03877e7bcb59fef0e965b78bb3  guix-build-6ccf95586047/output/powerpc64-linux-gnu/bitcoin-6ccf95586047-powerpc64-linux-gnu-debug.tar.gz
74c9840fb229751a0492dc40891671d675028460d9270058c346bbdafd8088f0  guix-build-6ccf95586047/output/powerpc64-linux-gnu/bitcoin-6ccf95586047-powerpc64-linux-gnu.tar.gz
48744eecfea3f69ed37bcb2bd61c78a1cb5f1604cfcafc6008542198202f904e  guix-build-6ccf95586047/output/riscv64-linux-gnu/SHA256SUMS.part
154d3b870030f2f3ab131eaeb480301680c8605e2ed9bcfa21f7ab538d201144  guix-build-6ccf95586047/output/riscv64-linux-gnu/bitcoin-6ccf95586047-riscv64-linux-gnu-debug.tar.gz
82230a2fbcc70fd19b4e81b520edb0f9b17e985a8b0bb12ce9811cb6f0fd4cbf  guix-build-6ccf95586047/output/riscv64-linux-gnu/bitcoin-6ccf95586047-riscv64-linux-gnu.tar.gz
08b058fbaac04b15eb86b9fa85385de28f3edf5dd4cbeb5b2bc759e0c08fae1f  guix-build-6ccf95586047/output/x86_64-apple-darwin/SHA256SUMS.part
323b852b1f2070ad361aa4bcca331874d722e3c36ca8fb4918c7eac56143c3e7  guix-build-6ccf95586047/output/x86_64-apple-darwin/bitcoin-6ccf95586047-x86_64-apple-darwin-unsigned.tar.gz
c6bcd22144bd1214523463d034decd9e3bf719d6e98a7fb8d297be3873c0292c  guix-build-6ccf95586047/output/x86_64-apple-darwin/bitcoin-6ccf95586047-x86_64-apple-darwin-unsigned.zip
0a9a15d42e846eca13633d2dbeff083a497cde0457cf99922eeddb71d6d04e32  guix-build-6ccf95586047/output/x86_64-apple-darwin/bitcoin-6ccf95586047-x86_64-apple-darwin.tar.gz
9317f7c1c93674997ef1a7b80913a8820a42c611984eb923dd940793fb91f52c  guix-build-6ccf95586047/output/x86_64-linux-gnu/SHA256SUMS.part
6d8ce4f5a669c73f9d0a4205debd6154fe55b69297ca5cd6d84cc5b03298b910  guix-build-6ccf95586047/output/x86_64-linux-gnu/bitcoin-6ccf95586047-x86_64-linux-gnu-debug.tar.gz
9a5937b0afe3cf08af74e7933916b0bfb7c19ba01c84a4bb4bf7b93f9d1c298c  guix-build-6ccf95586047/output/x86_64-linux-gnu/bitcoin-6ccf95586047-x86_64-linux-gnu.tar.gz
eae638dd409caf81ad286a20ce6a07bcebed3fd97fa0116f4f5ca62e51289c1c  guix-build-6ccf95586047/output/x86_64-w64-mingw32/SHA256SUMS.part
452911441ef112df74a37e2c4d6802a723a8b456398fe02b556b4beb576a04e9  guix-build-6ccf95586047/output/x86_64-w64-mingw32/bitcoin-6ccf95586047-win64-debug.zip
67bebf7fd0695829e381fc5ca144248b517c656ee1ef9a2ea0b4a463d3de94bf  guix-build-6ccf95586047/output/x86_64-w64-mingw32/bitcoin-6ccf95586047-win64-setup-unsigned.exe
a24800d5c2ae63b5c25ce07f9a1974bc863526b39e292717335d4c27576b9064  guix-build-6ccf95586047/output/x86_64-w64-mingw32/bitcoin-6ccf95586047-win64-unsigned.tar.gz
78db9fd78a188cbb85fc82862976ed177625a5ad3388a33ab5cebebcc57be311  guix-build-6ccf95586047/output/x86_64-w64-mingw32/bitcoin-6ccf95586047-win64.zip
```

**Review by hebasto — COMMENTED** [review]
Tested 6ccf95586047ad520af15a8451154ae519e272f9.

1. Autotools compiles with `-fexceptions`, but CMake doesn't. Considering that this option is disabled for C by default, should we mirror this behaviour?

2. Should we bump the [CMake minimum required version](https://github.com/libexpat/libexpat/blob/3bab6c09bbe8bf42d84b81563ddbcf4cca4be838/expat/CMakeLists.txt#L36):
```cmake
cmake_minimum_required(VERSION 3.1.3)
```
 ?

**Comment by fanquake** [comment]
> should we mirror this behaviour?

Which behaviour? If this is missing from one build system, that could be a bug that should be reported upstream. Given that these are stubs compiled just so Qt can compile, I don't think it matters too much.

> Should we bump the CMake minimum required version

Sure. Added a patch.

**Comment by fanquake** [comment]
Guix Build (aarch64):
```bash
4ed36603100265640e4e9e73fa8f04c2b10a581c0a68f37cb636f1cbff71469c  guix-build-cf46c6b8f2ff/output/aarch64-linux-gnu/SHA256SUMS.part
70b0f40dec0646cc7378c17bb569c8aa292ceba93e9b7233e7a0067fde04a24c  guix-build-cf46c6b8f2ff/output/aarch64-linux-gnu/bitcoin-cf46c6b8f2ff-aarch64-linux-gnu-debug.tar.gz
e778fdbf6dcf74a8cfeac8d3b353f877809f96a6f4759e497d939b001874a357  guix-build-cf46c6b8f2ff/output/aarch64-linux-gnu/bitcoin-cf46c6b8f2ff-aarch64-linux-gnu.tar.gz
c99a80fbee8f43dff0519d7dd76e41145dc9f4f1a593138fc19c147956092e7d  guix-build-cf46c6b8f2ff/output/arm-linux-gnueabihf/SHA256SUMS.part
eb6a3972d15e0f027cf2664c860e2b15228983db5d5b33f61b78f6602570f72e  guix-build-cf46c6b8f2ff/output/arm-linux-gnueabihf/bitcoin-cf46c6b8f2ff-arm-linux-gnueabihf-debug.tar.gz
d66b3386d3996a446fa54214f4e21f6aa2797808b16430f46af6a26d07ff661b  guix-build-cf46c6b8f2ff/output/arm-linux-gnueabihf/bitcoin-cf46c6b8f2ff-arm-linux-gnueabihf.tar.gz
01d22496ecd504b6b9759b033c93d46719db7f3de90a2ccab014b80683186b2f  guix-build-cf46c6b8f2ff/output/arm64-apple-darwin/SHA256SUMS.part
3715a0f1b6fe1c0e557061adfffdf56fd54b9068cee463b2d22df22932d3a7e9  guix-build-cf46c6b8f2ff/output/arm64-apple-darwin/bitcoin-cf46c6b8f2ff-arm64-apple-darwin-unsigned.tar.gz
e6e5e2f8daba83c5c3145a043f42670997a81ea93b65642ec89ff4935e0c8a54  guix-build-cf46c6b8f2ff/output/arm64-apple-darwin/bitcoin-cf46c6b8f2ff-arm64-apple-darwin-unsigned.zip
d904963e5a27c3f7afda205dbe73a2a903c104a76bc20ba275fe9d96c48d37cf  guix-build-cf46c6b8f2ff/output/arm64-apple-darwin/bitcoin-cf46c6b8f2ff-arm64-apple-darwin.tar.gz
1276ee1ed31845f7656c2e120635f8dbe90b7d8e564eacd2c9065d162b3b4f07  guix-build-cf46c6b8f2ff/output/dist-archive/bitcoin-cf46c6b8f2ff.tar.gz
55a7f4a459d65d2bf2ec605f5c0e00ddae50a33eacb68525a2d08e3fbfcf87ff  guix-build-cf46c6b8f2ff/output/powerpc64-linux-gnu/SHA256SUMS.part
04e4f6c6574070b30d4405b04f3d13c57356b127d06fa93eab6ade93c182fedc  guix-build-cf46c6b8f2ff/output/powerpc64-linux-gnu/bitcoin-cf46c6b8f2ff-powerpc64-linux-gnu-debug.tar.gz
019f386d8debd534034fbc2ee448079ec742ccac2bff4487cd14fbfa3d99542d  guix-build-cf46c6b8f2ff/output/powerpc64-linux-gnu/bitcoin-cf46c6b8f2ff-powerpc64-linux-gnu.tar.gz
497cda9eadb42f1612816efee54750d955593b598ca4543a80fa2ee429619f0e  guix-build-cf46c6b8f2ff/output/riscv64-linux-gnu/SHA256SUMS.part
59fd779017a33673f3ee102d7fe33d59857a765ec42a768a622b3b8f5fbb573a  guix-build-cf46c6b8f2ff/output/riscv64-linux-gnu/bitcoin-cf46c6b8f2ff-riscv64-linux-gnu-debug.tar.gz
99be98072747cd2b6decb9df417b02def8c9f0008ac75420c4d58220acd3fdfb  guix-build-cf46c6b8f2ff/output/riscv64-linux-gnu/bitcoin-cf46c6b8f2ff-riscv64-linux-gnu.tar.gz
480972d8f878b720e044f5b0fd8d62df60bd3bbc4916801c175fb24a68165caa  guix-build-cf46c6b8f2ff/output/x86_64-apple-darwin/SHA256SUMS.part
9441f7a2f1536349fa3dcab2807baa155fab720c388e46589fbbcb3082521626  guix-build-cf46c6b8f2ff/output/x86_64-apple-darwin/bitcoin-cf46c6b8f2ff-x86_64-apple-darwin-unsigned.tar.gz
d249b182dfe0383d6a54d498d23e79b996ca66b88e5af66430da63dfe09e2e23  guix-build-cf46c6b8f2ff/output/x86_64-apple-darwin/bitcoin-cf46c6b8f2ff-x86_64-apple-darwin-unsigned.zip
ddcc614b2f8a412426d0463401f0a265a99a09b69bb6b2831577669607ad4fe1  guix-build-cf46c6b8f2ff/output/x86_64-apple-darwin/bitcoin-cf46c6b8f2ff-x86_64-apple-darwin.tar.gz
ab9b987f9e8c19e614ffc7e774b5e5eceb014a6420c07e19108fe5c815e1c321  guix-build-cf46c6b8f2ff/output/x86_64-linux-gnu/SHA256SUMS.part
f6c2e2972a773aec557d88af8cfd97642b467b0d6b767d9be634d614d9ff8660  guix-build-cf46c6b8f2ff/output/x86_64-linux-gnu/bitcoin-cf46c6b8f2ff-x86_64-linux-gnu-debug.tar.gz
bbd1be6ef572ee8e294b2f39c5196e821716a3dfd2fd19ba0fde93b49d5af495  guix-build-cf46c6b8f2ff/output/x86_64-linux-gnu/bitcoin-cf46c6b8f2ff-x86_64-linux-gnu.tar.gz
e5e1bad1398f92e72e4f9a3160f8e364913c920abb55a894d287cd1c98ec7995  guix-build-cf46c6b8f2ff/output/x86_64-w64-mingw32/SHA256SUMS.part
e1a9a0af02ca80ace6362268346e5b77f7583443e64b2e08bd4d2bca5300b6da  guix-build-cf46c6b8f2ff/output/x86_64-w64-mingw32/bitcoin-cf46c6b8f2ff-win64-debug.zip
ab1e958ae83e458f4cf7baac4a757f5f89a27f1a2f3b6c7d8259f0e2398b64ec  guix-build-cf46c6b8f2ff/output/x86_64-w64-mingw32/bitcoin-cf46c6b8f2ff-win64-setup-unsigned.exe
4337edce1e0c99d788d9522aae2224db161035181a13f294cba07b9407dcaa87  guix-build-cf46c6b8f2ff/output/x86_64-w64-mingw32/bitcoin-cf46c6b8f2ff-win64-unsigned.tar.gz
5eefec2926a4d81c59d011e6cfdc3a460299ab524310cc3f546aeb977a904961  guix-build-cf46c6b8f2ff/output/x86_64-w64-mingw32/bitcoin-cf46c6b8f2ff-win64.zip
```

**Review by hebasto — APPROVED** [review]
ACK cf46c6b8f2ffc88e4d7299e952fae55d3ae56ef5.

`*.la` files are no longer created. Hence, there is no need to remove them:
```diff
--- a/depends/packages/expat.mk
+++ b/depends/packages/expat.mk
@@ -33,5 +33,5 @@ define $(package)_stage_cmds
 endef
 
 define $(package)_postprocess_cmds
-  rm -rf share lib/cmake lib/*.la
+  rm -rf share lib/cmake
 endef
```

(similar to https://github.com/bitcoin/bitcoin/pull/30506)

**Comment by hebasto** [comment]
My Guix build:
```
x86_64
4ed36603100265640e4e9e73fa8f04c2b10a581c0a68f37cb636f1cbff71469c  guix-build-cf46c6b8f2ff/output/aarch64-linux-gnu/SHA256SUMS.part
70b0f40dec0646cc7378c17bb569c8aa292ceba93e9b7233e7a0067fde04a24c  guix-build-cf46c6b8f2ff/output/aarch64-linux-gnu/bitcoin-cf46c6b8f2ff-aarch64-linux-gnu-debug.tar.gz
e778fdbf6dcf74a8cfeac8d3b353f877809f96a6f4759e497d939b001874a357  guix-build-cf46c6b8f2ff/output/aarch64-linux-gnu/bitcoin-cf46c6b8f2ff-aarch64-linux-gnu.tar.gz
c99a80fbee8f43dff0519d7dd76e41145dc9f4f1a593138fc19c147956092e7d  guix-build-cf46c6b8f2ff/output/arm-linux-gnueabihf/SHA256SUMS.part
eb6a3972d15e0f027cf2664c860e2b15228983db5d5b33f61b78f6602570f72e  guix-build-cf46c6b8f2ff/output/arm-linux-gnueabihf/bitcoin-cf46c6b8f2ff-arm-linux-gnueabihf-debug.tar.gz
d66b3386d3996a446fa54214f4e21f6aa2797808b16430f46af6a26d07ff661b  guix-build-cf46c6b8f2ff/output/arm-linux-gnueabihf/bitcoin-cf46c6b8f2ff-arm-linux-gnueabihf.tar.gz
01d22496ecd504b6b9759b033c93d46719db7f3de90a2ccab014b80683186b2f  guix-build-cf46c6b8f2ff/output/arm64-apple-darwin/SHA256SUMS.part
3715a0f1b6fe1c0e557061adfffdf56fd54b9068cee463b2d22df22932d3a7e9  guix-build-cf46c6b8f2ff/output/arm64-apple-darwin/bitcoin-cf46c6b8f2ff-arm64-apple-darwin-unsigned.tar.gz
e6e5e2f8daba83c5c3145a043f42670997a81ea93b65642ec89ff4935e0c8a54  guix-build-cf46c6b8f2ff/output/arm64-apple-darwin/bitcoin-cf46c6b8f2ff-arm64-apple-darwin-unsigned.zip
d904963e5a27c3f7afda205dbe73a2a903c104a76bc20ba275fe9d96c48d37cf  guix-build-cf46c6b8f2ff/output/arm64-apple-darwin/bitcoin-cf46c6b8f2ff-arm64-apple-darwin.tar.gz
1276ee1ed31845f7656c2e120635f8dbe90b7d8e564eacd2c9065d162b3b4f07  guix-build-cf46c6b8f2ff/output/dist-archive/bitcoin-cf46c6b8f2ff.tar.gz
55a7f4a459d65d2bf2ec605f5c0e00ddae50a33eacb68525a2d08e3fbfcf87ff  guix-build-cf46c6b8f2ff/output/powerpc64-linux-gnu/SHA256SUMS.part
04e4f6c6574070b30d4405b04f3d13c57356b127d06fa93eab6ade93c182fedc  guix-build-cf46c6b8f2ff/output/powerpc64-linux-gnu/bitcoin-cf46c6b8f2ff-powerpc64-linux-gnu-debug.tar.gz
019f386d8debd534034fbc2ee448079ec742ccac2bff4487cd14fbfa3d99542d  guix-build-cf46c6b8f2ff/output/powerpc64-linux-gnu/bitcoin-cf46c6b8f2ff-powerpc64-linux-gnu.tar.gz
497cda9eadb42f1612816efee54750d955593b598ca4543a80fa2ee429619f0e  guix-build-cf46c6b8f2ff/output/riscv64-linux-gnu/SHA256SUMS.part
59fd779017a33673f3ee102d7fe33d59857a765ec42a768a622b3b8f5fbb573a  guix-build-cf46c6b8f2ff/output/riscv64-linux-gnu/bitcoin-cf46c6b8f2ff-riscv64-linux-gnu-debug.tar.gz
99be98072747cd2b6decb9df417b02def8c9f0008ac75420c4d58220acd3fdfb  guix-build-cf46c6b8f2ff/output/riscv64-linux-gnu/bitcoin-cf46c6b8f2ff-riscv64-linux-gnu.tar.gz
480972d8f878b720e044f5b0fd8d62df60bd3bbc4916801c175fb24a68165caa  guix-build-cf46c6b8f2ff/output/x86_64-apple-darwin/SHA256SUMS.part
9441f7a2f1536349fa3dcab2807baa155fab720c388e46589fbbcb3082521626  guix-build-cf46c6b8f2ff/output/x86_64-apple-darwin/bitcoin-cf46c6b8f2ff-x86_64-apple-darwin-unsigned.tar.gz
d249b182dfe0383d6a54d498d23e79b996ca66b88e5af66430da63dfe09e2e23  guix-build-cf46c6b8f2ff/output/x86_64-apple-darwin/bitcoin-cf46c6b8f2ff-x86_64-apple-darwin-unsigned.zip
ddcc614b2f8a412426d0463401f0a265a99a09b69bb6b2831577669607ad4fe1  guix-build-cf46c6b8f2ff/output/x86_64-apple-darwin/bitcoin-cf46c6b8f2ff-x86_64-apple-darwin.tar.gz
ab9b987f9e8c19e614ffc7e774b5e5eceb014a6420c07e19108fe5c815e1c321  guix-build-cf46c6b8f2ff/output/x86_64-linux-gnu/SHA256SUMS.part
f6c2e2972a773aec557d88af8cfd97642b467b0d6b767d9be634d614d9ff8660  guix-build-cf46c6b8f2ff/output/x86_64-linux-gnu/bitcoin-cf46c6b8f2ff-x86_64-linux-gnu-debug.tar.gz
bbd1be6ef572ee8e294b2f39c5196e821716a3dfd2fd19ba0fde93b49d5af495  guix-build-cf46c6b8f2ff/output/x86_64-linux-gnu/bitcoin-cf46c6b8f2ff-x86_64-linux-gnu.tar.gz
e5e1bad1398f92e72e4f9a3160f8e364913c920abb55a894d287cd1c98ec7995  guix-build-cf46c6b8f2ff/output/x86_64-w64-mingw32/SHA256SUMS.part
e1a9a0af02ca80ace6362268346e5b77f7583443e64b2e08bd4d2bca5300b6da  guix-build-cf46c6b8f2ff/output/x86_64-w64-mingw32/bitcoin-cf46c6b8f2ff-win64-debug.zip
ab1e958ae83e458f4cf7baac4a757f5f89a27f1a2f3b6c7d8259f0e2398b64ec  guix-build-cf46c6b8f2ff/output/x86_64-w64-mingw32/bitcoin-cf46c6b8f2ff-win64-setup-unsigned.exe
4337edce1e0c99d788d9522aae2224db161035181a13f294cba07b9407dcaa87  guix-build-cf46c6b8f2ff/output/x86_64-w64-mingw32/bitcoin-cf46c6b8f2ff-win64-unsigned.tar.gz
5eefec2926a4d81c59d011e6cfdc3a460299ab524310cc3f546aeb977a904961  guix-build-cf46c6b8f2ff/output/x86_64-w64-mingw32/bitcoin-cf46c6b8f2ff-win64.zip
```

**Review by hebasto — APPROVED** [review]
re-ACK a517029646ac86f9d72fcea204ff45db41702e37.

**Pull request merged**
