### PR TITLE
Changed the year and little bit of formatting.

### PR DESCRIPTION
**Pull request by Villacaleb**

### CODE REVIEW

**Comment by fanquake** [comment]
NACK - we only change copyright dates when files are actually changed. Formatting will be taken care of when we sort out clang-formatting.

**Comment by Villacaleb** [comment]
I see, also, what does "NACK" mean?

**Comment by fanquake** [comment]
It means I disagree with the changes. See https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md#pull-request-terminology

**Comment by paveljanik** [comment]
NACK
Not useful change. Please close this issue.

**Comment by laanwj** [comment]
Thanks for trying to contribute, but we don't update the years randomly, there's a script for it (see contrib/devtools/fix-copyright-headers.py). But the consensus was, last time, to remove the copyright years completely from source files.

**Pull request closed without merging**
