### PR TITLE
Cleanup: Delete CChainParams getters to attributes from Consensus::Params

### PR DESCRIPTION
**Pull request by jtimon**
Delete 4 redundat getters in CChainParams.
A small part of #5970.

### CODE REVIEW

**Comment by theuni** [comment]
ut ACK

**Comment by sipa** [comment]
ut ACK

**Comment by jgarzik** [comment]
ACK

**Comment by jtimon** [comment]
Needed rebase.

**Comment by laanwj** [comment]
utACK

**Pull request merged**
