### PR TITLE
Trivial: move several relay options into the relay help group

### PR DESCRIPTION
**Pull request by jlopp**
It seems to me that these three config options are better suited to be grouped with the rest of the relay options.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Makes sense.
utACK 0fb288725b68d533aa2591ca1bd83db416f4a12c

**Comment by laanwj** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/10088/commits/0fb288725b68d533aa2591ca1bd83db416f4a12c

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/10088/commits/0fb288725b68d533aa2591ca1bd83db416f4a12c

**Comment by fanquake** [comment]
utACK 0fb2887

**Pull request merged**
