### PR TITLE
Fix quoting of copyright holders in configure.ac.

### PR DESCRIPTION
**Pull request by domob1812**
The old configure.ac did not work for a copyright holders string containing commas due to insufficient quoting.  The new one allows this.  While this is, of course, not of direct consequence to the current code (where the string is "Bitcoin Core"), it should still be fixed now that the string is actually factored out.

### CODE REVIEW

**Comment by domob1812** [comment]
Note that I'm not an expert in m4, so I cannot really tell whether the fix is "correct".  It just works in my trials.

**Comment by laanwj** [comment]
utACK, although this pretty much "fixes" a problem that we don't have. Derived projects with commas in their copyright string could also add the extra `[]`.

**Comment by sipa** [comment]
Seems this also makes an unrelatef change (copyright year instead of version is release)?

**Comment by laanwj** [comment]
@sipa Correct. Though I think that change makes sense
```patch
-AC_DEFINE(COPYRIGHT_YEAR, _COPYRIGHT_YEAR, [Version is release])
+AC_DEFINE(COPYRIGHT_YEAR, _COPYRIGHT_YEAR, [Copyright year])
```
Currently we get this in `src/config/bitcoin-config.h`:
```
/* Version is release */
#define COPYRIGHT_YEAR 2016
```

**Comment by domob1812** [comment]
Yes, I agree - this is not high priority for Bitcoin.  However, since we actually factored the copyright holders out, I think it makes sense to do it "correctly".

True, the copyright-year change is unrelated - but I stumbled upon it while editing, and think it also makes sense and is trivial enough.  But I can also remove it from the PR if you prefer.

**Comment by luke-jr** [comment]
Hmm, I didn't expect multiple things in the substitution part, and the CopyrightHolders function probably won't react correctly to that. But utACK I suppose, this change shouldn't hurt.

**Comment by laanwj** [comment]
> Hmm, I didn't expect multiple things in the substitution part, and the CopyrightHolders function probably won't react correctly to that.

Right. Would make sense to have a Tested ACK here before merge.

**Pull request merged**
