### PR TITLE
Remove unused SERIALIZE_METHODS for CBanEntry

### PR DESCRIPTION
**Pull request by maflcko**
It would be confusing to keep unused and dead code.

### CODE REVIEW

**Review by ryanofsky — APPROVED** [review]
Code review ACK fa3bd9de99ee2bdfce2010e9367391a146e41878. 

PR #22848 is related to this one. Without the binary serialization this PR removes, the JSON serialization which #22848 exposes is even more necessary for gui/node process separation. Either binary or json serialization for banmap_t will work for that, as long as there is some publicly exposed banmap<->string serialization function.

**Comment by theStack** [comment]
Concept ACK

**Comment by Zero-1729** [comment]
Approach ACK

**Review by theStack — APPROVED** [review]
Code-review ACK fa3bd9de99ee2bdfce2010e9367391a146e41878

**Pull request merged**
