### PR TITLE
test: convert documentation into type annotations

### PR DESCRIPTION
**Pull request by fanquake**
Rather than having function types exist as documentation, make them type annotations, which enables more `mypy` checking.

### CODE REVIEW

**Comment by practicalswift** [comment]
Concept ACK

Automatic checking is better than human checking. Empirical evidence suggests that humans are slow, inaccurate, and bore easily.

**Comment by MarcoFalke** [comment]
ci fails

**Comment by fanquake** [comment]
> ci fails

Trying to determine what the failure is here. Looking at https://cirrus-ci.com/task/6475309332561920 it seems the failure happens after [printing the uncovered commands](https://github.com/bitcoin/bitcoin/blob/684e687d42f8d20ac349004ec48a3d0924eb0137/test/functional/test_runner.py#L536), but before it gets to ["Cleaning up coverage data"](https://github.com/bitcoin/bitcoin/blob/684e687d42f8d20ac349004ec48a3d0924eb0137/test/functional/test_runner.py#L538).

I can't seem to reproduce when running this branch & `test/functional/test_runner.py --coverage` locally on a Linux or macOS machine; or when running with what should be the equivalent options from `00_setup_env_native_qt5.sh`.

**Comment by MarcoFalke** [comment]
I can reproduce locally with the ci system

```
ALL                                                | ✓ Passed  | 4979 s (accumulated) 
Runtime: 719 s

Uncovered RPC commands:
  - addnode
  - analyzepsbt
  - clearbanned
  - combinepsbt
  - combinerawtransaction
  - converttopsbt
  - createmultisig
  - createpsbt
  - createrawtransaction
  - decodepsbt
  - decoderawtransaction
  - decodescript
  - deriveaddresses
  - disconnectnode
  - enumeratesigners
  - estimatesmartfee
  - finalizepsbt
  - generateblock
  - generatetoaddress
  - generatetodescriptor
  - getaddednodeinfo
  - getbestblockhash
  - getblock
  - getblockchaininfo
  - getblockcount
  - getblockfilter
  - getblockhash
  - getblockheader
  - getblockstats
  - getblocktemplate
  - getchaintips
  - getchaintxstats
  - getconnectioncount
  - getdescriptorinfo
  - getdifficulty
  - getindexinfo
  - getmemoryinfo
  - getmempoolancestors
  - getmempooldescendants
  - getmempoolentry
  - getmempoolinfo
  - getmininginfo
  - getnettotals
  - getnetworkhashps
  - getnetworkinfo
  - getnodeaddresses
  - getpeerinfo
  - getrawmempool
  - getrawtransaction
  - getrpcinfo
  - gettxout
  - gettxoutproof
  - gettxoutsetinfo
  - getzmqnotifications
  - help
  - joinpsbts
  - listbanned
  - logging
  - ping
  - preciousblock
  - prioritisetransaction
  - pruneblockchain
  - savemempool
  - scantxoutset
  - sendrawtransaction
  - setban
  - setnetworkactive
  - signmessagewithprivkey
  - signrawtransactionwithkey
  - stop
  - submitblock
  - submitheader
  - testmempoolaccept
  - uptime
  - utxoupdatepsbt
  - validateaddress
  - verifychain
  - verifymessage
  - verifytxoutproof

# echo $?
1

**Comment by laanwj** [comment]
Concept ACK, I like the mypy-style for documentation better anyhow.

**Comment by MarcoFalke** [comment]
Maybe you can split up the failing commit into a separate pull?

**Comment by fanquake** [comment]
> Maybe you can split up the failing commit into a separate pull?

Ok. Split into #22139.

**Comment by kiminuo** [comment]
Concept ACK

**Comment by theStack** [comment]
Concept ACK

**Comment by instagibbs** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/22092/commits/68ace23fa3bc01baa734ddf2c0963acae1c75ed1

annotations match prior comments

**Pull request merged**
