### PR TITLE
Wrap boost::replace_all

### PR DESCRIPTION
**Pull request by maflcko**
The included header is thousand lines of template code (not counting the recursive includes) for basically one function.

### CODE REVIEW

**Comment by laanwj** [comment]
Concept ACK, good idea to pimpl as much of boost as possible.

**Comment by theStack** [comment]
Concept ACK

**Comment by pk-b2** [comment]
Concept ACK

There is one more instance of boost:replace_all in https://github.com/bitcoin/bitcoin/blob/fa7734d7e7e52ec9557c9508d6be164025ff90d7/src/util/system.cpp#L1255

**Comment by pk-b2** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/25068/commits/fa2deae2a86417d7e0d4cd33fb933b1000d20313

**Comment by w0xlt** [comment]
Approach ACK

**Comment by seejee** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/25068/commits/fa2deae2a86417d7e0d4cd33fb933b1000d20313

**Comment by martinus** [comment]
ACK fa2deae2a86417d7e0d4cd33fb933b1000d20313. Next step, replace with custom implementation to get rid of another boost header?

nit: string.cpp shows `Copyright (c) 2019 The Bitcoin Core developers`

**Pull request merged**
