### PR TITLE
test: Set regtest.BIP65Height = 111 to speed up tests

### PR DESCRIPTION
**Pull request by maflcko**
No need to waste time by forcing creation of more than 1000 blocks to get the benefits of being able to test BIP 65. Also, reducing the height makes it more likely that (third-party) tests are conforming to BIP 65, which is enforced on mainnet for all new blocks.

### CODE REVIEW

**Comment by practicalswift** [comment]
Concept ACK

**Comment by theStack** [comment]
Concept ACK

**Comment by Zero-1729** [comment]
Concept ACK

**Comment by MarcoFalke** [comment]
Rebased and ready for review

**Review by theStack — APPROVED** [review]
Tested ACK faa5228f7427ed467bb0a6806fc891d61f23c76b 🚀 

Good to see that the burden of generating large numbers of blocks is more and more relieved. This enables nice speed-ups for the affected tests (>3x for feature_cltv.py, 2x for rpc_signrawtransaction.py on my machine).

**Review by Zero-1729 — APPROVED** [review]
tACK faa5228 🧪

Tested on macOS v11.5.2

Clean changes, affected tests aren't broken. More importantly, saw the following times on master and this patch respectively:

#### Master

| File | User | System |
|---|---|---|
| test/functional/feature_cltv.py | 1.35s | 0.36s |
| test/functional/rpc_blockchain.py | 1.00s | 0.31s | 
| test/functional/rpc_signrawtransaction.py |  3.44s | 0.68s |

#### After Patch

| File | User | System |
|---|---|---|
| test/functional/feature_cltv.py | 0.33s | 0.11s | 
| test/functional/rpc_blockchain.py | 1.00s | 0.31s | 
| test/functional/rpc_signrawtransaction.py  | 1.52s | 0.41s |

**Review by theStack — APPROVED** [review]
re-ACK faf7e485e901d6c72db5d969b526fa148060a003 📍 

Checked via `git range-diff faa5228f...faf7e485` that changes since my last ACK are only rebase-related.

**Review by Zero-1729 — APPROVED** [review]
re-ACK faf7e485e901d6c72db5d969b526fa148060a003 🧋

LGTM, clean rebase since last review 🧼

**Review by kristapsk — APPROVED** [review]
ACK faf7e485e901d6c72db5d969b526fa148060a003

**Pull request merged**
