### PR TITLE
[UI Styling] Left-Align Tab Bar - optionsdialog.ui

### PR DESCRIPTION
**Pull request by SCDeveloper**
Aesthetics.

### CODE REVIEW

**Comment by SCDeveloper** [comment]
screen shot 2017-03-05 at 20 40 07

**Comment by SCDeveloper** [comment]
Merge alongside #9925

**Comment by luke-jr** [comment]
It's already left-aligned on platforms that use left-aligned tab bars... Your screenshot looks like macOS. Does macOS not match what our tab bar looks like?

**Comment by SCDeveloper** [comment]
No this is a bug on OSX, and I have fixed it :D

**Comment by jonasschnelli** [comment]
I don't think we should do this.
OSX uses a center-aligned tab-bar.

Example form the settings:
bildschirmfoto 2017-03-06 um 09 27 44

**Comment by jonasschnelli** [comment]
I don't think we should do this.
OSX uses a center-aligned tab-bar.

Example form the settings:
bildschirmfoto 2017-03-06 um 09 27 44

**Comment by SCDeveloper** [comment]
Well I think you should considering that it appears left-aligned on all other operating systems.

It also looks a damn site better.

**Comment by laanwj** [comment]
I agree with @jonasschnelli, we should simply use the OS-provided layout. On MacOSX it's what users expect.

**Comment by SCDeveloper** [comment]
I am an OSX user and it isn't what I expected.

**Comment by luke-jr** [comment]
> OK, then let the OS simply control how the application is styled and relinquish control over it. 

That's exactly what we (and any reasonable software) do...

**Comment by SCDeveloper** [comment]
Even if it looks bad?

**Comment by laanwj** [comment]
> Even if it looks bad and differs from how it looks on all the other operating systems?

Yes. Why would someone using some platform care how it looks in other platforms at all?

**Comment by laanwj** [comment]
Closing these, we disagree on the direction the GUI should take so it's not going to go anywhere.

**Comment by SCDeveloper** [comment]
Because people don't just use one operating system. I have Windows, Linux and OSX.

**Comment by luke-jr** [comment]
If you dislike how it looks, reconfigure your OS or use one that lets you.

**Pull request closed without merging**
