### PR TITLE
A: Chainparams: Rename RequireStandard() to DefaultAcceptNonstd()

### PR DESCRIPTION
**Pull request by jtimon**
Alternative to #16527 

Just a rename, shouldn't change functionality.
Can be considered bik-shedding, but I believe the resulting code is more clear, less negations.

Rename related to #16770

### CODE REVIEW

**Comment by jtimon** [comment]
Rebased

**Comment by jtimon** [comment]
Decoupled from #16524

**Comment by luke-jr** [comment]
Don't think this is worth it.

**Comment by jtimon** [comment]
Since I seem to be alone in considering:

```
    fRequireStandard = !gArgs.GetBoolArg("-acceptnonstdtxn", chainparams.DefaultAcceptNonstd());
```

much more readable than 

```
    fRequireStandard = !gArgs.GetBoolArg("-acceptnonstdtxn", !chainparams.RequireStandard());
```
just by having one less negation...closing

**Comment by MarcoFalke** [comment]
I like it, but yeah *shrug*

**Pull request closed without merging**
