### PR TITLE
test: reject float at satoshi_round

### PR DESCRIPTION
**Pull request by katesalazar**
Using strings and integers will be more predictable than using float,
which is less repeatable.

satoshi_round was used with almost no floats already, I suppose
that because it rounds in a single direction and when floating
point rounding occurs it can go either up or downwards so it
is a risky thing to do. Forbid it explicitly.

### CODE REVIEW

**Review by maflcko — COMMENTED** [review]
I wonder if `satoshi_round` can be removed if the call sites denote everything in integral satoshi values.

**Comment by katesalazar** [comment]
> I wonder if `satoshi_round` can be removed if the call sites denote everything in integral satoshi values.

If Bitcoin Core won't hard fork increased currency divisibility,
removing it is cleaner.

If Bitcoin Core or other group is going to hard fork increased
currency divisibility, you might prefer to keep this and maybe
use it more than it is used currently.

**Comment by meshcollider** [comment]
> If Bitcoin Core won't hard fork increased currency divisibility,
removing it is cleaner.

It is very safe to modify the test code assuming Bitcoin Core will *not* hard fork.

**Comment by katesalazar** [comment]
> > > I wonder if `satoshi_round` can be removed if the call sites denote everything in integral satoshi values.
> > 
> > If Bitcoin Core won't hard fork increased currency divisibility,
> > removing it is cleaner.
> 
> It is very safe to modify the test code assuming Bitcoin Core will _not_ hard fork.

If I had to do this, I'd take all the necessary time to make sure
every rational is a `decimal.Decimal` instead of a float,
then remove satoshi_round, and then close this PR unmerged.

If possible, I would prefer configuring a "safe mode" at the Python interpreter
to completely forbid floating point at code overseeing and asserting testing,
but I don't know if Python has such feature.

Cheers!

**Comment by MarcoFalke** [comment]
Are you still working on this?

**Pull request closed without merging**
