### PR TITLE
Add missing include for atomic in db.h

### PR DESCRIPTION
**Pull request by morcos**
I was getting compile errors without this.

### CODE REVIEW

**Comment by jnewbery** [comment]
Tested ACK 8e69adc6651ed533a014d883f06be33c468cf2db

**Comment by paveljanik** [comment]
trivial ACK https://github.com/bitcoin/bitcoin/pull/10578/commits/8e69adc6651ed533a014d883f06be33c468cf2db

**Review by ryanofsky — COMMENTED** [review]
utACK 8e69adc6651ed533a014d883f06be33c468cf2db

Compile error doesn't happen for me, but include should be added because an atomic was introduced here in #8694

**Comment by sipa** [comment]
utACK 8e69adc6651ed533a014d883f06be33c468cf2db

**Pull request merged**
