### PR TITLE
Test: Cover "change_type" option of "walletcreatefundedpsbt" RPC

### PR DESCRIPTION
**Pull request by guggero**
Increases test coverage of the `walletcreatefundedpsbt` RPC.

Tests the following combinations:
 - Make sure the global option `-changetype` is used as the default value for the `change_type` option if not specified.
 - Make sure the global option `-changetype` can be overwritten by explicitly setting the `change_type` option of the `walletcreatefundedpsbt` RPC call.
 - Make sure the options `change_type` and `changeAddress` are mutually exclusive.

### CODE REVIEW

**Comment by practicalswift** [comment]
Concept ACK

Very nice first-time contribution @guggero! Hope to see more contributions from you in the future. Warm welcome! :)

**Review by kristapsk — APPROVED** [review]
ACK b371aa3bbd9a0b2633cc46c3925181da17bdc403

**Comment by michaelfolkson** [comment]
Concept ACK

Are you happy for this to have a "good first review" [label](https://github.com/bitcoin/bitcoin/issues/19941) @guggero? It would mean the PR is noisier than normal and you might have to answer more basic questions than you otherwise would :)

**Comment by guggero** [comment]
Thank you all for the (concept) ACKs and the warm welcome :)

I think the label "good first review" is a great idea, @michaelfolkson. I'm happy to answer any and all questions around this PR (that I know the answer to). You're welcome to add the label.

**Comment by MarcoFalke** [comment]
Needs rebase

```
                                   AssertionError: Expected substring not found in error message:

                                   substring: 'both changeAddress and address_type'

                                   error message: 'Cannot specify both change address and address type options'.

**Comment by guggero** [comment]
Rebased and fixed the error message check.

**Comment by achow101** [comment]
ACK a56e9f5670136b29e48aabfc7f38569222fe4635

**Pull request merged**
