### PR TITLE
Adjust Gradle properties to fix `apk` build

### PR DESCRIPTION
**Pull request by hebasto**
On the master branch @ d2b8c5e1234cdaff84bd1f60aea598d219cdac5e, building the `apk` target fails:
```
$ make -C src/qt apk
...
> Task :compileDebugJavaWithJavac FAILED
/home/hebasto/git/gui/src/qt/android/src/org/qtproject/qt5/android/QtActivityDelegate.java:690: error: cannot find symbol
                Display display = (Build.VERSION.SDK_INT < Build.VERSION_CODES.R)
                                                                              ^
  symbol:   variable R
  location: class VERSION_CODES
/home/hebasto/git/gui/src/qt/android/src/org/qtproject/qt5/android/QtActivityDelegate.java:692: error: cannot find symbol
                        : m_activity.getDisplay();
                                    ^
  symbol:   method getDisplay()
  location: variable m_activity of type Activity
/home/hebasto/git/gui/src/qt/android/src/org/qtproject/qt5/android/QtActivityDelegate.java:833: error: cannot find symbol
        float refreshRate = (Build.VERSION.SDK_INT < Build.VERSION_CODES.R)
                                                                        ^
  symbol:   variable R
  location: class VERSION_CODES
/home/hebasto/git/gui/src/qt/android/src/org/qtproject/qt5/android/QtActivityDelegate.java:835: error: cannot find symbol
                : m_activity.getDisplay().getRefreshRate();
                            ^
  symbol:   method getDisplay()
  location: variable m_activity of type Activity
/home/hebasto/git/gui/src/qt/android/src/org/qtproject/qt5/android/QtLayout.java:95: error: cannot find symbol
        Display display = (Build.VERSION.SDK_INT < Build.VERSION_CODES.R)
                                                                      ^
  symbol:   variable R
  location: class VERSION_CODES
/home/hebasto/git/gui/src/qt/android/src/org/qtproject/qt5/android/QtLayout.java:97: error: cannot find symbol
                : ((Activity)getContext()).getDisplay();
                                          ^
  symbol:   method getDisplay()
  location: class Activity
/home/hebasto/git/gui/src/qt/android/src/org/qtproject/qt5/android/ExtractStyle.java:418: error: cannot find symbol
            if (Build.VERSION.SDK_INT < Build.VERSION_CODES.Q)
                                                           ^
  symbol:   variable Q
  location: class VERSION_CODES
/home/hebasto/git/gui/src/qt/android/src/org/qtproject/qt5/android/ExtractStyle.java:421: error: cannot find symbol
                numStates = stateList.getStateCount();
                                     ^
  symbol:   method getStateCount()
  location: variable stateList of type StateListDrawable
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
8 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 827ms
...
```

Fixing it by updating the Gradle tool's properties.

### CODE REVIEW

**Comment by hebasto** [comment]
Friendly ping @icota :)

**Comment by hebasto** [comment]
Reworked. The PR description has been updated.

**Review by fanquake — APPROVED** [review]
ACK 5f504065544133a47da5a7a240675c23eceb0799 - seems fine.

**Comment by hebasto** [comment]
> It still fails for me with the same reason in CI:
> 
> [cirrus-ci.com/task/6379161720193024?logs=ci#L4214](https://cirrus-ci.com/task/6379161720193024?logs=ci#L4214)

Does CI task fail locally for you?

**Comment by hebasto** [comment]
> Yes.
> 
> Does `MAKEJOBS="-j$(nproc)" FILE_ENV="./ci/test/00_setup_env_android.sh" ./ci/test_run_all.sh` pass?

For me, the following
```
env -i HOME="$HOME" PATH="$PATH" USER="$USER" bash -c 'MAKEJOBS="-j16" FILE_ENV="./ci/test/00_setup_env_android.sh" ./ci/test_run_all.sh'
```
passes for 66f8ee2969dcfd5df13f5e33afa80cbc6ffef774, but fails for f4674444b21184ee267675eba4886009b4ec619c.

**Comment by hebasto** [comment]
@maflcko 

Does the following patch:
```diff
--- a/ci/test/01_base_install.sh
+++ b/ci/test/01_base_install.sh
@@ -98,7 +98,7 @@ if [ -n "$ANDROID_HOME" ] && [ ! -d "$ANDROID_HOME" ]; then
   fi
   mkdir -p "$ANDROID_HOME"
   unzip -o "$ANDROID_TOOLS_PATH" -d "$ANDROID_HOME"
-  yes | "${ANDROID_HOME}"/cmdline-tools/bin/sdkmanager --sdk_root="${ANDROID_HOME}" --install "build-tools;${ANDROID_BUILD_TOOLS_VERSION}" "platform-tools" "platforms;android-${ANDROID_API_LEVEL}" "ndk;${ANDROID_NDK_VERSION}"
+  yes | "${ANDROID_HOME}"/cmdline-tools/bin/sdkmanager --sdk_root="${ANDROID_HOME}" --install "build-tools;${ANDROID_BUILD_TOOLS_VERSION}" "platform-tools" "platforms;android-31" "platforms;android-${ANDROID_API_LEVEL}" "ndk;${ANDROID_NDK_VERSION}"
 fi
 
```

work for you?

(clear cache may be needed)

**Pull request merged**
