### PR TITLE
p2p, refactor: add `CInv` transaction message helpers; use in net processing

### PR DESCRIPTION
**Pull request by jonatack**
Following the merge of wtxid relay in #18044, this is the first of three refactoring PRs (this one, #19610, and #19611) with no change in behavior, tightly scoped to ease review, to simplify the net processing code and improve encapsulation:

- add `CInv` transaction message helper methods, defined in the class

- use the new helpers in `net_processing.cpp` to simplify the code and improve encapsulation

Test coverage is provided by the functional p2p tests, notably (from seeing which tests failed when breaking things to test coverage) `p2p_segwit`, `p2p_tx_download`, `p2p_feefilter`, and `p2p_permissions`.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Code Review ACK 3faeaab673ad3fd0f9c80407b0e625a1fa5ff4ae - would it be an wrong to make the new calls inline?

**Comment by jonatack** [comment]
Thanks @jonasschnelli, good idea, done. Made the new member functions implicitly [inline](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rf-inline) by defining them in the class definition. Change from last push: `git diff 3faeaab c251d710`

**Review by vasild — APPROVED** [review]
ACK c251d71

* Would it be possible to also handle the rest of `MSG_*` values and make `CInv::type` private?
* Would it make sense to change `CInv::type` from `int` to `enum GetDataMsg`? Or maybe to `uint32_t` (ac88e2eb6 has changed `enum GetDataMsg` from `int` to `uint32_t`)?

**Comment by jonatack** [comment]
Thanks for reviewing, @vasild. Done in https://github.com/jonatack/bitcoin/commits/CInv-type-refactoring. Will propose separately to keep the changes small and not invalidate review.

**Review by theStack — APPROVED** [review]
Code-Review ACK c251d710a4c2981c6d52362a9a89db84da3d4a67

**Review by hebasto — APPROVED** [review]
ACK c251d710a4c2981c6d52362a9a89db84da3d4a67, I have reviewed the code and it looks OK, I agree it can be merged.

**Comment by fjahr** [comment]
Code review ACK c251d710a4c2981c6d52362a9a89db84da3d4a67

**Comment by jonatack** [comment]
Thank you for the review :heart: hopefully with 4-5 ACKs this is RFM.

**Comment by laanwj** [comment]
Code review ACK c251d710a4c2981c6d52362a9a89db84da3d4a67

**Comment by jonatack** [comment]
Thanks to everyone for reviewing. The follow-up #19610 which makes the same change for INV block messages, is rebased and ready with tests green, if you're inclined to have a look.

**Pull request merged**
