### PR TITLE
Improve CMedianFilter algorithm

### PR DESCRIPTION
**Pull request by antoinedesbois**
1. Add benchmarks for median computation.
2. Improve median computation algorithm
  2.1. Write unit tests to ensure new median computation has the same behavior as the previous implementation
  2.2. Ensure benchmarks are improved

The new median algorithm takes its |max_size| as a template parameter and relies on a ring buffer to keep track of the current values the median needs to be computed on. Instead of sorting the values from scratch on every new insertion, the new algorithm finds where the new value needs to be inserted and where the now outdated value needs to be removed. It then rotates the elements of the vector to perform the sorted insertion.

The test |util_MedianFilter_rand| proves that the new behavior is the same as doing the sorting on every iteration.

### CODE REVIEW

**Comment by laanwj** [comment]
Thanks for your contribution. However, `CMedianFilter` is only used for timedata, for a very limited number of values. Also, timedata is part of P2P time adjustment which is in the process of being removed on the longer term. Adding tests is nice but i'm not sure about changing the algorithm at this point.

**Review by Raulnori77 — APPROVED** [review]

**Comment by fanquake** [comment]
> Your call, I do not know what the timeline looks like for the removal of the time adjustment.

One of the related PRs is #24662, and some semi-related refactoring is in #24697. I agree with @laanwj that refactoring timedata-only related code at this point is likely not worthwhile.

**Comment by laanwj** [comment]
> Your call, I do not know what the timeline looks like for the removal of the time adjustmen

To be honest, I don't know either, and this isn't a NACK, i just think review time can be spend more productively. So will leave it up to other people.

>  We can merge the benchmarks and/or tests since those have no effect on production software, let me know if you think that'd be useful.

Let's give it some time.

**Comment by fanquake** [comment]
Thanks for the contribution @antoinedesbois, however I'm going to close this PR for now. Given it's likely the refactors in #24662 will go ahead. If that doesn't happen, this PR could be re-opened later on.

**Pull request closed without merging**
