### PR TITLE
build: Make the help string for --with-gui configure option unambiguous 

### LINKED ISSUE #17813: build: Ambiguous help string for --with-gui configure option
This help message
```
$ ./configure --help | grep -A 1 'with-gui'
  --with-gui[=no|qt5|auto]
                          build bitcoin-qt GUI (default=auto)
```
states that `--with-gui` and `--with-gui=auto` are equivalent.

But this is _not_ correct.

Consider a system without available Qt:

```
$ ./configure --with-gui | grep 'with gui'
configure: error: Qt dependencies not found
```

```
$ ./configure --with-gui=auto | grep 'with gui'
configure: WARNING: Qt dependencies not found; bitcoin-qt frontend will not be built
  with gui / qt = no
```

What should be fixed: the help message or `configure` behavior?

### PR DESCRIPTION
**Pull request by hebasto**
This PR changes the help string for `--with-gui` option of the `configure` script in the following way:
- explicitly adds "yes" value
- explicitly states that `--with-gui` is equivalent  to `--with-gui=qt5`
- adds check for `--with-gui` values: the `configure` script raises an error if a value in `--with-gui=value` is not expected
- refactors to make ongoing changes (#18298) clear and easy to review

On master (3d28c886f077ce22fb7755fe9ec1f4e08d3d4a62):
```
$ ./configure --help | grep -A 1 'with-gui\['
  --with-gui[=no|qt5|auto]
                          build bitcoin-qt GUI (default=auto)
```

With this PR:
```
$ ./configure --help | grep -A 2 'with-gui\['
  --with-gui[=yes|no|auto|qt5]
                          build bitcoin-qt GUI (default is auto; --with-gui
                          and --with-gui=qt5 are equivalent to --with-gui=yes)
```

Also the `QT_LIB_PREFIX` variable is removed for code simplicity and readability.

This PR does _not_ change behavior of the `configure` script for known values of the `--with-gui` option, and raises an error otherwise.

Fix #17813
Based on #18297 (492971de35bab26346545f68365872211f458b00..8a26848c460160e1279f26bc413f693a34e33b9d)

### CODE REVIEW

**Comment by hebasto** [comment]
The PR description has been updated on @ryanofsky's [request](https://github.com/bitcoin/bitcoin/issues/17813#issuecomment-600023429).

**Comment by ryanofsky** [comment]
Thanks for updating, new description makes this much more understandable. Two things I don't understand:

- Unclear what "adds check for --with-gui values" is means. Is there a new warning or error?
- Paragraph "This PR does not change behavior. The configure script warns..." is confusing because it's unclear whether the warning is new or old. If this isn't changing warnings and errors, then I don't think there is a reason to mention them. If this is changing warnings and errors, the differences should be listed in the list of changes at the top of the PR, not in a bottom paragraph beginning with "This PR does not change behavior."

**Comment by hebasto** [comment]
>    - Unclear what "adds check for --with-gui values" is means. Is there a new warning or error?

There is a new error if value is not expected. PR description has been updated.

>    - Paragraph "This PR does not change behavior. The configure script warns..." is confusing because it's unclear whether the warning is new or old. If this isn't changing warnings and errors, then I don't think there is a reason to mention them. If this is changing warnings and errors, the differences should be listed in the list of changes at the top of the PR, not in a bottom paragraph beginning with "This PR does not change behavior."

PR description has been updated.

**Comment by luke-jr** [comment]
Rather not. Isn't Qt 6 around the corner?

**Comment by hebasto** [comment]
Closing until Qt 6.

**Pull request closed without merging**
