### PR TITLE
[WIP] p2p: send not_found msgs for unknown, pruned or unwilling to share blocks

### PR DESCRIPTION
**Pull request by furszy**
The 'not_found' message, introduced in protocol version 70001 (Bitcoin Core 0.8.0 - Feb 2013), serves as a response to a 'getdata' message when the receiving node does not have the requested data available for relay. Thus far, this has only been applied to transactions. This PR proposes extending its use to blocks as well.

Currently, when the remote peer does not have the requested block data, it ignores the 'getdata' inventory block request. This lack of response causes the requesting node to wait (and stall if the request was for an IBD block) for 10 minutes until the request timeout is triggered. As a result, the local node abruptly disconnects the peer due to perceived unresponsiveness in order to download the block from another source, even though the peer handled the message accordantly and may still be relaying other headers, blocks, and transactions properly.

This behavior is suboptimal for well-behaving nodes. Therefore, this PR proposes sending 'not_found' messages for blocks the remote peer does not know about or no longer stores, allowing the local node to promptly request them from another peer. Doing so will help prevent network synchronization stalling scenarios, allow us to shorten idle wait times (by reducing the block request timeout for peers supporting this feature), and ensure well-behaving peers remain connected.

Pending tasks:
1. Write detailed commits description.
2. Expand PR description
    1. Describe feature negotiation message. Annotate all considered options.
    2. Describe 'not_found' handler behavior for blocks closer to the tip vs historical ones.
3. Create BIP for the new feature negotiation message.
4. Think about increasing the peer's block download priority when it signals support for the feature.
5. Think about disconnecting the peer when a known feature negotiation message is received prior to the version message.
6. Complete TODOs in the code.

### CODE REVIEW

**Comment by dergoegge** [comment]
> Currently, when the remote peer does not have the requested block data, it ignores the 'getdata' inventory block request. This lack of response causes the requesting node to wait (and stall if the request was for an IBD block) for 10 minutes until the request timeout is triggered.

Nodes advertise which blocks they have and what their current tip is, so the timeouts should only happen if the peer is misbehaving or if you disrespect the protocol by asking for things they don't have. Disconnection seems appropriate in both cases?

What is the problem this is trying to solve?

**Comment by furszy** [comment]
> Nodes advertise which blocks they have and what their current tip is, so the timeouts should only happen if the peer is misbehaving or if you disrespect the protocol by asking for things they don't have.

We don't ask all peers about all the blocks they know about. If the node is it in the main-chain, most of the time we only know their last advertised header only.
Once we are headers-wise sync, the block downloading procedure download blocks from different peers. It has a window of 16 in-flight blocks per peer. The peer who advertised the header might not be the one who ends up providing the final block.

This open a window for other scenarios such peers not responding when you ask for an old block that isn't in the main chain (fingerprinting protection), not responding when you ask for a block deeper than the pruning threshold (to avoid leaking the prune-height) or for a block that was just pruned (erased in-between the inv roundtrip). Which doesn't necessarily represent a bad behaving peer.

When this situations arises, well-behaving peers responding with a not_found will allow us to promptly request the block from another source instead of staying idle for 10 minutes and disconnect the well-behaving peer that is still in full compliance with the protocol specs. Preferring peers signaling this feature over others over time seems the correct path to follow to me.

**Comment by furszy** [comment]
> > The peer who advertised the header might not be the one who ends up providing the final block.
> 
> I don't think we ever ask for a block from a peer without that specific peer having announced the block or a descendant to us?

Yeah. I actually spent some time checking that specifically because it would allow an easy way to partition the network by sending only the new header tip, disconnecting and expect the peer requests it to someone else who does not have it etc..

What I meant with the "The peer who advertised the header might not be the one who ends up providing the final block" is that providing a descendant of a block doesn't mean the peer has the block data in all circumstances. Thus why wrote those examples.

>  I think it's good to have numbers about whether this actually happens in production between honest nodes.

Ideally, yeah. But.. how would you get numbers when the disconnecting peer does not tell you the idle reason?

Protocol wise, and generally speaking here, I don't see why a connection should stay idle for 10 minutes when two honest peers are connected. There should always be a response, even more when the other peer continue sending all other messages accordantly.

**Review by furszy — COMMENTED** [review]
Thanks for the comment gmaxwell.

> I think if you find yourself thinking sending a not found is a solution to a problem, you've got a mistake somewhere else.

Yeah, thats actually how this working path started #28120.

> I believed the current behavior was this: If a node is non-pruned it will have all blocks, no issue. If a node is pruned it will respond to requests for the last 288 which are protocol required and will disconnect any peer that asks for a block outside of the window. Again, no issue.

Those scenarios are ok, but what about the following ones:

- For AssumeUTXO:
AssumeUTXO nodes prioritize tip synchronization first, meaning they advertise knowledge of all blocks posterior to the snapshot base block hash. This causes honest peers trying to synchronize historical block from them to forcibly disconnect due to the lack of response while the AssumeUTXO node is synchronizing the tip chain or the background one. This scenario can be replicated just by running an AssumeUTXO node and connecting a new node -> test case exercising the disconnection can be found [here](https://github.com/furszy/bitcoin-core/commit/d1fd7ec4269a35afcc841d123b5c75e986e25457).

  So, based on your comment, instead of implementing something like this, would your suggestion be to signal the AssumeUTXO sync state at the network level in some way? Because that sounds like signaling when (1) the node does not have the background chain and (2) when the node finishes syncing the background chain. Which sounds odd at first.
Probably not a fingerprinting concern because AssumeUTXO nodes should already be distinguishable enough just by observing their block requests. But.. I'm not so sure about it.

- High-Bandwidth Peers:
BIP152 mentions the possibility of relaying PoW-valid headers before fully validating the block data. So, what if the block turns out to be invalid? the relayer will ignore any following-up request and lead to disconnection.

**Review by furszy — COMMENTED** [review]
> The assumeutxo node would just be a limited node, it'll offer the most recent blocks and none of the history. (it might have more history then it offers, as is the case of any other limited node.)

Yeah, this was the piece I was missing. Thanks!
Funny, I thought about a dynamically adjustable network signal but didn't consider reusing the limited service flag by enabling/disabling full-node service support based on the assumeUTXO background chain-sync status..

Created #30807 implementing it. It fixes the last honest peer disconnection scenario I had in mind.

> > High-Bandwidth Peers:
> > BIP152 mentions the possibility of relaying PoW-valid headers before fully validating the block data. So, what if the block > turns out to be invalid? the relayer will ignore any following-up request and lead to disconnection.
> 
> They don't relay just headers, they relay the block, which is why the BIP directs peers to not ban each other for sending an invalid block this way so long as it was POW valid.

Yeah ok, great.

**Pull request closed without merging**
