### PR TITLE
devtools: show pull and commit information in github-merge

### PR DESCRIPTION
**Pull request by laanwj**
Print the number and title of the pull, as well as the commits to be merged.

Example:
pullinfo

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Oh. Nice!

Tested ACK:
bildschirmfoto 2016-01-22 um 16 55 30
https://github.com/libbtc/libbtc/commit/a56ea7304004453fd841f03606df75cfa5522970

**Comment by fanquake** [comment]
utACK

**Comment by achow101** [comment]
Tested ACK 17b5d38

Although it still has the bug that I fixed in #7402 which was in the original.

**Comment by laanwj** [comment]
@achow101 Yes, the python version is a direct conversion of the bash script, I don't expect it to solve any bugs, just make it easier to add features. I'll have a look at #7402 and include that.

**Pull request merged**
