### PR TITLE
ci: Add vcpkg tools cache

### LINKED ISSUE #23107: ci: Windows build fails intermittently when downloading (Failed to download from mirror set)
It seems that sometimes a download will fail, but succeeds on the retry, however the full build will still be marked as failed:

https://cirrus-ci.com/task/4800755426131968?logs=build#L31

```
  A suitable version of powershell-core was not found (required v7.1.0). Downloading portable powershell-core v7.1.0...
  Downloading powershell-core...
    https://github.com/PowerShell/PowerShell/releases/download/v7.1.0/PowerShell-7.1.0-win-x86.zip -> C:\Users\ContainerAdministrator\AppData\Local\Temp\vcpkg\downloads\PowerShell-7.1.0-win-x86.zip
  Failed to download from mirror set:
  https://github.com/PowerShell/PowerShell/releases/download/v7.1.0/PowerShell-7.1.0-win-x86.zip: WinHttpReceiveResponse() failed: 12030
  
C:\Users\ContainerAdministrator\AppData\Local\Temp\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(94,5): error MSB3073: The command ""C:\Users\ContainerAdministrator\AppData\Local\Temp\vcpkg\scripts\buildsystems\msbuild\..\..\..\vcpkg.exe" install  --x-wait-for-lock --triplet "x64-windows-static" --vcpkg-root "C:\Users\ContainerAdministrator\AppData\Local\Temp\vcpkg\scripts\buildsystems\msbuild\..\..\..\\" "--x-manifest-root=C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\build_msvc\\" "--x-install-root=C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\build_msvc\vcpkg_installed\\" " exited with code 1. [C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\build_msvc\libbitcoinconsensus\libbitcoinconsensus.vcxproj]
  Waiting to take filesystem lock on C:\Users\ContainerAdministrator\AppData\Local\Temp\vcpkg\.vcpkg-root...
  C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\build_msvc
  Installing vcpkg dependencies to C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\build_msvc\vcpkg_installed\
  "C:\Users\ContainerAdministrator\AppData\Local\Temp\vcpkg\scripts\buildsystems\msbuild\..\..\..\vcpkg.exe" install  --x-wait-for-lock --triplet "x64-windows-static" --vcpkg-root "C:\Users\ContainerAdministrator\AppData\Local\Temp\vcpkg\scripts\buildsystems\msbuild\..\..\..\\" "--x-manifest-root=C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\build_msvc\\" "--x-install-root=C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\build_msvc\vcpkg_installed\\" 
  Detecting compiler hash for triplet x64-windows-static...
  A suitable version of powershell-core was not found (required v7.1.0). Downloading portable powershell-core v7.1.0...
  Downloading powershell-core...
    https://github.com/PowerShell/PowerShell/releases/download/v7.1.0/PowerShell-7.1.0-win-x86.zip -> C:\Users\ContainerAdministrator\AppData\Local\Temp\vcpkg\downloads\PowerShell-7.1.0-win-x86.zip
  Extracting powershell-core...

### PR DESCRIPTION
**Pull request by hebasto**
On master (02feae54a53ff654f7cecf17ed467edcd612cd0c) vcpkg downloads some tools that are used internally:
```
...
  A suitable version of cmake was not found (required v3.20.0). Downloading portable cmake v3.20.0...
  Downloading cmake...
    https://github.com/Kitware/CMake/releases/download/v3.20.2/cmake-3.20.2-windows-i386.zip -> C:\Users\ContainerAdministrator\AppData\Local\Temp\vcpkg\downloads\cmake-3.20.2-windows-i386.zip
  Extracting cmake...
  A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
  Downloading 7zip...
    https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 -> C:\Users\ContainerAdministrator\AppData\Local\Temp\vcpkg\downloads\7-zip.commandline.18.1.0.nupkg
  Extracting 7zip...
  A suitable version of nuget was not found (required v5.5.0). Downloading portable nuget v5.5.0...
  Downloading nuget...
    https://dist.nuget.org/win-x86-commandline/v5.5.1/nuget.exe -> C:\Users\ContainerAdministrator\AppData\Local\Temp\vcpkg\downloads\22ea847d-nuget.exe
  Detecting compiler hash for triplet x64-windows-static...
  A suitable version of powershell-core was not found (required v7.1.0). Downloading portable powershell-core v7.1.0...
  Downloading powershell-core...
    https://github.com/PowerShell/PowerShell/releases/download/v7.1.3/PowerShell-7.1.3-win-x86.zip -> C:\Users\ContainerAdministrator\AppData\Local\Temp\vcpkg\downloads\PowerShell-7.1.3-win-x86.zip
  Extracting powershell-core...
...
```

If any of downloads above fails the whole CI task fails (see #23107). The most recent failure examples in the master branch:
- https://github.com/bitcoin/bitcoin/commit/c001da306b29c46ef1e7421002c3aba3ff5ed514, [log](https://api.cirrus-ci.com/v1/task/5182966176415744/logs/build.log)
- https://github.com/bitcoin/bitcoin/commit/12ff8993bcc7315f4a9b69bf16def980bb0e5197, [log](https://api.cirrus-ci.com/v1/task/5367684129882112/logs/build.log)

This PR adds vcpkg tools cache.

Closes #23107.

---

Note for reviewers. Some patches from the initial PR were split into separated PRs: #23310 and #23329. Therefore, a discussion here could be outdated or irrelevant until the recent [push](https://github.com/bitcoin/bitcoin/pull/23215#issuecomment-949556531).

### CODE REVIEW

**Comment by hebasto** [comment]
cc @sipsorcery

**Comment by sipsorcery** [comment]
I think I mentioned it on the original PR that moved the Windows build to Cirrus but we did have a period of instability that was caused by caching vcpkg dependencies #19431 and #19444. Just thought I'd mention it in case the same issue crops up again and is traced back to this PR.
 
Other than that vcpkg has a new'ish [binary caching](https://github.com/microsoft/vcpkg/blob/master/docs/users/binarycaching.md) feature which is recommended for CI use. If vcpkg dependencies are going to be cached again it would seem to make sense to enable it. By only caching the `C:\Users\ContainerAdministrator\AppData\Local\vcpkg\archives` directory, without the feature, it could cause the ABI mismatch between the dependencies and the compiler version we encountered in the past. In theory all that should be required is to set the environment variable to:

`VCPKG_FEATURE_FLAGS: 'manifests,binarycaching'

**Comment by sipsorcery** [comment]
> We already use binary caching. 

I don't think so, at least the old appveyor job wasn't. I had it enabled on my personal appveyor job to save 10 minutes on the Bitcoin Core build but I'm pretty sure it was never turned on for the main Bitcoin Core CI job.

> Maybe also it's reasonable to invalidate the cache when msbuild -version is changed?

I think that's very desireable due to the aforementioned ABI incompatabilites that crop up. It's been my experience that vcpkg, with binary caching enabled, rebuilds dependencies if it detects an updated compiler.

> Btw, the "Binary Caching" feature is enabled by default

That's good news, I hadn't spotted that. The CI config in this PR is still pegging vcpkg to commit ID `75522bb1f2e7d863078bcd06322348f053a9e33f` so won't be taking advantage of the new defaults. 

An alternative to my suggestion of explicitly setting binary caching on, would be to update the vcpkg commit ID to `5568f110b509a9fd90711978a7cb76bae75bb092` which is the latest `2021.05.12 release` and looks like it would have manifests and binary caching enabled by default.

**Comment by sipsorcery** [comment]
> On Cirrus CI Windows job it is enabled

I'm not sure just caching the vcpkg download directories is enough.... It's the libraries that are built from the downloaded source archives that are used in the Bitcoin Core build. How those libraries are detected as out of date is the question.

Is there any reason not to bump the vcpkg commit to `75522bb1f2e7d863078bcd06322348f053a9e33f`? 

Now that you've pointed out manifests and binary caching are enabled by default it seems like a good idea to take advantage of them. And it would make our discussion academic :).

**Pull request merged**
