### PR TITLE
Properly forbid -salvagewallet and -zapwallettxes for multi wallet.

### PR DESCRIPTION
**Pull request by morcos**
Please tag 0.15

`SoftSetBoolArg` returns false if the argument was set either way.

### CODE REVIEW

**Comment by luke-jr** [comment]
Good catch, utACK.

**Comment by MarcoFalke** [comment]
utACK dd97a529ad23169f346aa042a808adf702ce8450

**Comment by jnewbery** [comment]
utACK dd97a529ad23169f346aa042a808adf702ce8450. Needs to go in for 0.15

**Comment by achow101** [comment]
utACK dd97a529ad23169f346aa042a808adf702ce8450

**Comment by TheBlueMatt** [comment]
utACK dd97a529ad23169f346aa042a808adf702ce8450

**Comment by sipa** [comment]
utACK dd97a529ad23169f346aa042a808adf702ce8450

**Pull request merged**
