### PR TITLE
[contrib] Delete spendfrom

### PR DESCRIPTION
**Pull request by maflcko**
This seems a developer-only tool, which appears unmaintained and unused.

### CODE REVIEW

**Comment by instagibbs** [comment]
Can you give a short explanation why to delete? :+1:

**Comment by MarcoFalke** [comment]
@instagibbs I could not find any reason to keep it.

To me this looks:

* unmaintained (uses deprecated features)
* unused (better alternatives exist)
* untested (has bugs)
* promotes address reuse

**Comment by gmaxwell** [comment]
ACK.

**Comment by laanwj** [comment]
I wasn't even aware it existed. Thanks for cleaning up.

**Pull request merged**
