### PR TITLE
doc: add distcc to productivity notes

### PR DESCRIPTION
**Pull request by Sjors**
If you have more than one computer at your disposal, you can use [distcc](https://www.distcc.org) to speed up compilation.

### CODE REVIEW

**Comment by laanwj** [comment]
Interesting suggestion. Although general build speed-up tips are somewhat out of scope, I don't think it hurts to mention the fact that it exists. No need to add any more details though.

**Comment by laanwj** [comment]
ACK 14093d5d243f6eb9cfef721c80f92848d95032ee

**Review by brunoerg — APPROVED** [review]
Nice!

ACK 14093d5d243f6eb9cfef721c80f92848d95032ee

**Review by w0xlt — APPROVED** [review]
ACK https://github.com/bitcoin/bitcoin/pull/25359/commits/14093d5d243f6eb9cfef721c80f92848d95032ee

**Pull request merged**
