### PR TITLE
doc: Remove misleading hint in getrawtransaction

### PR DESCRIPTION
**Pull request by maflcko**
For 0.18.0

I asked this line to be added in #15159, which was wrong because getmempoolentry does not return the raw transaction hex.

### CODE REVIEW

**Comment by Sjors** [comment]
I can't get rid of this error on macOS 10.14.3:

```
  AR       libbitcoin_wallet.a
rpc/rawtransaction.cpp:150:32: error: no member named 'IsValidNumArgs' in 'RPCHelpMan'
    if (request.fHelp || !help.IsValidNumArgs(request.params.size())) {
                          ~~~~ ^
1 error generated.
make[1]: *** [rpc/libbitcoin_server_a-rawtransaction.o] Error 1
make: *** [src/bitcoind] Error 2
```

I tried `make distclean`.

**Comment by Sjors** [comment]
(nvm my previous comment, my working tree wasn't clean)

tACK 9999879

**Comment by laanwj** [comment]
> I asked this line to be added in #15159, which was wrong because getmempoolentry does not return the raw transaction hex.

So should it?

**Comment by promag** [comment]
ACK 9999879.



> > I asked this line to be added in #15159, which was wrong because getmempoolentry does not return the raw transaction hex.
> 
> So should it?

By adding a option? Anyway, that is the goal of:
```
getrawtransaction "txid" ( verbose "blockhash" )

Return the raw transaction data.

By default this function only works for mempool transactions...
```

**Comment by laanwj** [comment]
> By adding a option? Anyway, that is the goal of:

If there's another documented way to do it that's good enough.

utACK 9999879f56c88ca2837f5d18e6688917ba96e9e2

**Pull request merged**
