### PR TITLE
Split up rpcwallet

### PR DESCRIPTION
**Pull request by meshcollider**
This is the rest of #23622, to split up rpcwallet into smaller, more logical parts.

This will have a lot of conflicts but let's just get it over and done with.

### CODE REVIEW

**Review by shaavan — APPROVED** [review]
crACK 889d32f7f2b6577d6ef367efecfc2f55916c3070

I have reviewed each commit on this PR, and I agree with the changes. 
Though I have not thoroughly tested, I was able to run bitcoind and bitcoin-cli on this PR successfully.

However, merging this PR now would not be effective as there are still too many [conflicts](https://github.com/bitcoin/bitcoin/pull/23667#issuecomment-985968995) with this PR. Though I understand that this would be an ineffective way, I would suggest you further split this PR.

**Review by ryanofsky — APPROVED** [review]
Code review ACK 889d32f7f2b6577d6ef367efecfc2f55916c3070. Easy review. Just function moves then file move.

> This will have a lot of conflicts but let's just get it over and done with.

Thank you! It's less annoying to deal with conflicts in one PR than multiple PRs, IMO.

> However, merging this PR now would not be effective as there are still too many [conflicts](https://github.com/bitcoin/bitcoin/pull/23667#issuecomment-985968995) with this PR. Though I understand that this would be an ineffective way, I would suggest you further split this PR.

I do think fact that these are clean moves with no changes should makes conflicts easier to resolve. And overall conflicts should be less of a burden if they only have to resolved once, instead of multiple times after different PRs.

**Comment by achow101** [comment]
ACK 889d32f7f2b6577d6ef367efecfc2f55916c3070

Nice straightforward moveonly commits. Although this has a lot of conflicts, rebasing shouldn't be that difficult. Git should be able to identify the moves and apply the changes accordingly, so it won't be that bad.

One thought on the RPC grouping: `abortrescan` should be in `rpc/transactions.cpp` to be with `rescanblockchain`.

**Comment by meshcollider** [comment]
Thanks for the review!

Rebased and moved `abortrescan` as suggested by @achow101

**Comment by achow101** [comment]
ACK b36e738285b111a184c67fd845404850c34333a3

**Review by ryanofsky — APPROVED** [review]
Code review ACK b36e738285b111a184c67fd845404850c34333a3, verified move-only again

**Comment by fanquake** [comment]
> However, merging this PR now would not be effective as there are still too many conflicts with this PR. Though I understand that this would be an ineffective way, I would suggest you further split this PR.

I agree with the other comments in regards to just "doing this now". A PR like this is always going to have a large number of conflicts, and splitting it up into many more PRs is just going draw out the rebasing, and create a lot more (repo) noise. 

Note that nearly half of the conflicting PRs actually belong to the PR author and the two reviewers who have already ACK'd this change. If you include Marco ([who was also planning on making these changes](https://github.com/bitcoin/bitcoin/issues/23622#issuecomment-981384971)) then it's more than half, so the "rebasing burden" isn't actually as bad as it may look.

I'm going to merge this now.

**Comment by Sjors** [comment]
Oh hi... (but yeah, it's worth it)

**Pull request merged**
