### PR TITLE
Use SipHash for node eviction (cont'd)

### PR DESCRIPTION
**Pull request by laanwj**
Add full test vectors from spec, test per byte and per 8 bytes.

Builds on #8086 (as it adds per-byte hashing).

### CODE REVIEW

**Comment by sipa** [comment]
utACK eebc23218758d89bce0b7cb0eced9fd654cd3d15

**Comment by instagibbs** [comment]
May want to re-title this PR

**Comment by sipa** [comment]
The original had grown in scope anyway, it now does:
* Extend the SipHash implementation
* Improved comments
* Added tests
* Switched to thread-safe random seed initializers
* Switch node eviction to use siphash

**Comment by NicolasDorier** [comment]
tACK (reimplemented this PR tests included into NBitcoin successfully on https://github.com/MetacoSA/NBitcoin/commit/c915829c0e4595d49c357525c9c51b4cb52f4b7f)

**Comment by TheBlueMatt** [comment]
So #8086 had some level of debate, and instead of continuing it there, you open a new pull under a bullshit title, get ONE untested ACK on the shit from #8086 and merge it?
Your hubris is showing.

**Comment by sipa** [comment]
#8086 had plenty of ACKs and this did only add tests, which also got ACKs.

You complained in #8086 about it being insecure. If you can explain how,
I'll gladly revert the siphash-for-eviction part.

**Comment by laanwj** [comment]
@sipa it's not clear who or what you're replying to

In any case, it was time to merge this, there were no concrete concerns left.

**Comment by rebroad** [comment]
What is a SipHash?

**Comment by sipa** [comment]
https://131002.net/siphash/

**Pull request merged**
