### PR TITLE
qt: Display minimum ping in debug window.

### PR DESCRIPTION
**Pull request by rebroad**
Adds minimum ping to the debug information, and replaces the last ping with the minimum ping in the node list.

### CODE REVIEW

**Comment by paveljanik** [comment]
Why replacing? Isn't the last ping time more valuable? Why renaming the member variable?

**Comment by rebroad** [comment]
@paveljanik Good questions, which perhaps I ought to have proactively explained.

Minimum ping is used in disconnection logic for evicting incoming connections, so a way it is the more relevant value.

Renaming the variable so that it is consistent with the RPC variable.

**Comment by MarcoFalke** [comment]
utACK 1724a40

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/8925/commits/1724a405c9065f2c939e936aca9b5d37fca5e954

**Comment by jonasschnelli** [comment]
Yes. Why not.
utACK 1724a405c9065f2c939e936aca9b5d37fca5e954

**Pull request merged**
