### PR TITLE
[Qt] optimize PNG files

### PR DESCRIPTION
**Pull request by jonasschnelli**
According to report on #5488 there can be libpng warnings while starting bitcoin-qt.
This PR will strip out unnecessary data (especially color profiles) from all PNG files.

### CODE REVIEW

**Comment by fanquake** [comment]
Needs Rebase

**Comment by jonasschnelli** [comment]
Rebased.

**Comment by jonasschnelli** [comment]
Updated the script as well as the images so it will use `pngcrush` to crush the `convert`-stripped images.

**Comment by zander** [comment]
Would a tool like optipng or pngcrush or trimage be more appropriate ?

**Comment by jonasschnelli** [comment]
@zander: pngcrush is included. See my last comment.

**Comment by laanwj** [comment]
Your script needs `set -e` at the top to make it fail when one of the tools fails.
(e.g. I didn't have pngcrush installed and it happily continued)

Also let's move it to `contrib/devtools`, leaving them in the contrib toplevel is a bit untidy.

**Comment by jonasschnelli** [comment]
Rewrote script, placed it under `contrib/devtools`.
Output of processing is here: https://gist.github.com/jonasschnelli/dad302d9b9b8a3163259

**Comment by jonasschnelli** [comment]
A second run of the script won't change the PNG sha256 (at least in my environment).

**Comment by laanwj** [comment]
Looks good to me now. When I re-run this script I get the same output as well.
In https://github.com/laanwj/bitcoin/commit/41dc934ffc111a900d9262cd1bb1ad84492a4e6e I've improved the script a little bit:
- Add pre/post check of image contents
- remove use of external tool to compute sha256 in favor of hashlib

**Comment by laanwj** [comment]
Added another commit https://github.com/laanwj/bitcoin/commit/2c77c150703952764aaeb43ab5f836d5b7fb0f7a that replaces uses of shell=True with the Python equivalent (as shell=True is less portable, and can be a security hazard).

**Comment by jonasschnelli** [comment]
Nice. Thanks for the additions.
I also added a rename commit because `strip_png.py` is no longer a adequate name.

**Comment by laanwj** [comment]
Merged via d1aa3c6 (squashed into two commits, one with your changes one with mine)

**Comment by jonasschnelli** [comment]
Was merged. Closing.

**Pull request closed without merging**
