### PR TITLE
Add bitcoin-tx JSON tests

### PR DESCRIPTION
**Pull request by jnewbery**
This PR adds new test cases to test bitcoin-tx JSON output, as suggested by @sipa in https://github.com/bitcoin/bitcoin/pull/8817 .

### CODE REVIEW

**Comment by laanwj** [comment]
Awesome, thanks!
utACK https://github.com/bitcoin/bitcoin/pull/8829/commits/54e5d7c1b81e1b76f5789abfa2cb1f5963cd9d72

**Comment by MarcoFalke** [comment]
utACK 54e5d7c1b81e1b76f5789abfa2cb1f5963cd9d72

**Comment by paveljanik** [comment]
ups, merged in the middle of my testing :-)

postmerge ACK https://github.com/bitcoin/bitcoin/commit/54e5d7c1b81e1b76f5789abfa2cb1f5963cd9d72

**Comment by droark** [comment]
Question: Was txcreate2.json supposed to be empty? I'm assuming some test data was supposed to be in it. :)

**Comment by jnewbery** [comment]
Interesting. The txcreate2 test is attempting to create a transaction with a single pay-to-script output for zero satoshi. When outputting as json, bitcoin-tx returns the empty string. When outputting as hex, it returns 01000000000100000000000000000000000000, ie:

```
version |number in|number out|out1 amount     |out1 script length|nlocktime
01000000 00        01         0000000000000000 00                 00000000
```

I think that's garbage and bitcoin-tx should reject any attempt to add an output with zero satoshi. I'll open a PR to fix that.

Interestingly, bitcoin-tx does output a json object if I try to create a zero-value transaction to a non-empty script:

```
$ bitcoin-tx -json -create outscript=0:"OP_DROP"
{
    "txid": "f0851b68202f736b792649cfc960259c2374badcb644ab20cac726b5f72f61c9",
    "version": 1,
    "locktime": 0,
    "vin": [
    ],
    "vout": [
        {
            "value": 0.00,
            "n": 0,
            "scriptPubKey": {
                "asm": "OP_DROP",
                "hex": "75",
                "type": "nonstandard"
            }
        }
    ],
    "hex": "0100000000010000000000000000017500000000"
}
```

txcreate2 is also the only test case that tests creating a pay-to-script, so we should add a new test case that tests adding a valid pay-to-script output.

**Comment by sipa** [comment]
Zero-value outputs are perfectly valid according to consensus rules.

**Comment by jnewbery** [comment]
ah, ok. Thanks. Then the fix is in bitcoin-tx to properly output zero-value, empty-script outputs.

**Comment by laanwj** [comment]
Good to see that we're finding bugs in bitcoin-tx by adding tests :)

**Comment by jnewbery** [comment]
I've mischaracterised the problem here. bitcoin-tx *is* outputting the transaction correctly in hex and json. However, when I try to pipe that same hex transaction back into bitcoin-tx, it fails with `error: invalid transaction encoding`.

**Comment by sipa** [comment]
Ah, that seems to be due to the segwit ambiguity for 0-input transactions.
IIRC, DecodeTransaction in core_io.h has a boolean parameter for attempting
to decode partial transactions. It should be set to true in calls from
bitcoin-tx.

**Comment by jnewbery** [comment]
Thanks @sipa . New PR here: https://github.com/bitcoin/bitcoin/pull/8837 to make bitcoin-tx set the flag correctly and parse partial transactions.

@droark - I've added https://github.com/bitcoin/bitcoin/pull/8836 to fix the fact that `bitcoin-util-test.py` would always succeed if the output comparison file was empty. That PR also fixes `txcreate2.json` so it's no longer empty.

**Comment by laanwj** [comment]
This was backported in #8832, removing tag

**Pull request merged**
