### PR TITLE
[TRIVIAL] Remove continue statement at the end of loop.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Tend to NACK here. This serves as documentation, indicating that the (large) scope is indeed the scope of a loop.

**Comment by bolekC** [comment]
Tend to agree with NACK. This code is anyway a bit too long so `continue` can help to read.

**Comment by kekimusmaximus** [comment]
I think a comment at the end of the scope might serve as better documentation ( // End while loop ). A continue does not provide this information IMHO.

**Comment by MarcoFalke** [comment]
> A continue does not provide this information IMHO.

It does. It is even compile-time enforced documentation, in contrast to a comment, which easily gets outdated.

**Comment by kekimusmaximus** [comment]
I'm indifferent to the outcome but it's not a compile-time enforced documentation.
It's bikeshedding at this point.

**Comment by MarcoFalke** [comment]
heh, right. Better close it :)

**Comment by bolekC** [comment]
>>A continue does not provide this information IMHO.

>It does. It is even compile-time enforced documentation, in contrast to a comment, which easily gets outdated.
Can you check if compiler generates the same code in both cases ?

**Comment by MarcoFalke** [comment]
I meant that the compiler will error out, if you place a `continue` at the end of a random non-loop scope.

**Pull request closed without merging**
