### PR TITLE
Backport bugfixes to 0.11 (2015-10-22 / f2c869a)

### PR DESCRIPTION
**Pull request by luke-jr**
Probably should leave this open until we're ready for the next 0.11.x release so I can keep adding to it.

### CODE REVIEW

**Comment by luke-jr** [comment]
Is 6a07eb676a020b0035173facb25f92f1ff6380f7 a bugfix hiding inside #6424 ? O.o

**Comment by MarcoFalke** [comment]
Skimmed-diff ACK.

**Comment by sipa** [comment]
Skimmed-diff ACK.

**Comment by fanquake** [comment]
utACK

**Comment by laanwj** [comment]
utACK

**Pull request merged**
