### PR TITLE
Rename rpcuser.py to rpcauth.py

### PR DESCRIPTION
**Pull request by hkjn**
This script creates `rpcauth` entries for bitcoin.conf, not the deprecated `rpcuser` entry, so this changes the name of the script to match.

As discussed in #11830.

### CODE REVIEW

**Comment by hkjn** [comment]
The test that failed on Travis produced the following stacktrace:
```
Traceback (most recent call last):
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/test/functional/segwit.py", line 673, in <module>
    SegWitTest().main()
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 142, in main
    self.stop_nodes()
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 263, in stop_nodes
    node.wait_until_stopped()
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_node.py", line 150, in wait_until_stopped
    wait_until(self.is_node_stopped, timeout=timeout)
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/util.py", line 215, in wait_until
    if predicate():
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_node.py", line 141, in is_node_stopped
    assert_equal(return_code, 0)
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/util.py", line 38, in assert_equal
    raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
AssertionError: not(1 == 0)
```

I could be missing something, but it doesn't seem to indicate the line number of the failed assertion; just that the failure was in `segwit.py`'s `SegWitTest.main()`, making it hard to dig into the cause of the failure..

(The failure message that `1` is not equal to `0` is also not very illuminating..)

Running what via Travis logs looks like the relevant test command locally produces no failures for `segwit.py`:
```
$ test/functional/test_runner.py --combinedlogslen=4000 --coverage --quiet --extended --exclude pruning,dbcrash
[ ... ]
TEST                           | STATUS    | DURATION

abandonconflict.py             | P Passed  | 19 s
assumevalid.py                 | P Passed  | 132 s
bip65-cltv-p2p.py              | P Passed  | 46 s
bip68-112-113-p2p.py           | P Passed  | 95 s
bip68-sequence.py              | P Passed  | 228 s
bip9-softforks.py              | P Passed  | 1621 s
bipdersig-p2p.py               | P Passed  | 38 s
bitcoin_cli.py                 | P Passed  | 5 s
blockchain.py                  | P Passed  | 17 s
bumpfee.py                     | P Passed  | 34 s
decodescript.py                | P Passed  | 5 s
deprecated_rpc.py              | P Passed  | 5 s
disablewallet.py               | P Passed  | 4 s
disconnect_ban.py              | P Passed  | 11 s
example_test.py                | P Passed  | 7 s
feature_logging.py             | x Failed  | 7 s
fundrawtransaction.py          | P Passed  | 68 s
getblocktemplate_longpoll.py   | P Passed  | 73 s
getchaintips.py                | P Passed  | 13 s
httpbasics.py                  | P Passed  | 8 s
import-rescan.py               | x Failed  | 13 s
importmulti.py                 | P Passed  | 22 s
importprunedfunds.py           | P Passed  | 10 s
invalidateblock.py             | P Passed  | 12 s
invalidblockrequest.py         | P Passed  | 12 s
invalidtxrequest.py            | P Passed  | 12 s
keypool-topup.py               | P Passed  | 45 s
keypool.py                     | P Passed  | 23 s
listsinceblock.py              | x Failed  | 6 s
listtransactions.py            | P Passed  | 33 s
maxuploadtarget.py             | P Passed  | 947 s
mempool_limit.py               | P Passed  | 30 s
mempool_packages.py            | P Passed  | 68 s
mempool_persist.py             | x Failed  | 20 s
mempool_reorg.py               | P Passed  | 11 s
mempool_resurrect_test.py      | P Passed  | 6 s
mempool_spendcoinbase.py       | P Passed  | 5 s
merkle_blocks.py               | P Passed  | 15 s
minchainwork.py                | x Failed  | 5 s
mining.py                      | x Failed  | 8 s
multi_rpc.py                   | P Passed  | 9 s
multiwallet.py                 | P Passed  | 17 s 
net.py                         | P Passed  | 6 s
notifications.py               | P Passed  | 10 s  
nulldummy.py                   | P Passed  | 18 s  
p2p-acceptblock.py             | P Passed  | 28 s
p2p-compactblocks.py           | P Passed  | 129 s 
p2p-feefilter.py               | P Passed  | 66 s  
p2p-fingerprint.py             | P Passed  | 13 s
p2p-fullblocktest.py           | x Failed  | 1962 s
p2p-leaktests.py               | P Passed  | 12 s 
p2p-mempool.py                 | P Passed  | 4 s
p2p-segwit.py                  | P Passed  | 984 s 
p2p-timeouts.py                | P Passed  | 66 s  
p2p-versionbits-warning.py     | P Passed  | 20 s  
preciousblock.py               | P Passed  | 11 s  
prioritise_transaction.py      | P Passed  | 40 s  
proxy_test.py                  | P Passed  | 11 s  
rawtransactions.py             | P Passed  | 30 s  
receivedby.py                  | P Passed  | 13 s  
reindex.py                     | P Passed  | 19 s  
replace-by-fee.py              | P Passed  | 41 s 
resendwallettransactions.py    | P Passed  | 7 s
rest.py                        | P Passed  | 14 s  
rpcbind_test.py                | P Passed  | 15 s 
rpcnamedargs.py                | P Passed  | 5 s
segwit.py                      | P Passed  | 99 s  
sendheaders.py                 | P Passed  | 30 s 
signmessages.py                | P Passed  | 4 s  
signrawtransactions.py         | P Passed  | 4 s
smartfees.py                   | P Passed  | 487 s 
txn_clone.py                   | P Passed  | 13 s  
txn_clone.py --mineblock       | P Passed  | 14 s  
txn_doublespend.py             | P Passed  | 13 s  
txn_doublespend.py --mineblock | P Passed  | 13 s 
uacomment.py                   | x Failed  | 9 s  
uptime.py                      | P Passed  | 4 s
wallet-accounts.py             | P Passed  | 32 s  
wallet-dump.py                 | P Passed  | 30 s  
wallet-encryption.py           | P Passed  | 26 s
wallet-hd.py                   | P Passed  | 267 s 
wallet.py                      | P Passed  | 87 s
walletbackup.py                | P Passed  | 184 s 
zapwallettxes.py               | P Passed  | 12 s 
zmq_test.py                    | o Skipped | 5 s

ALL                            | x Failed  | 8622 s (accumulated) 
```

However several other tests *do* fail locally.. this leads me to believe that issues seen in Travis as well as locally are issues with the test or test framework rather than the proposed change in this PR. I'd be happy to try to track down those test issues, but I'm still getting acquinted with the test framework, so it might take some time.

**Comment by ryanofsky** [comment]
I restarted your travis test. Segwit.py failure is probably due to the return code bug fixed in #11831

**Review by ryanofsky — COMMENTED** [review]
utACK 3fdb29778a0b598d4ddf05ec5ed4593641d0da6e. Might be worth a mention in [doc/release-notes.md](https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes.md) too

**Comment by hkjn** [comment]
Thanks @ryanofsky. For future reference, is there a way I can restart the test on Travis myself? (Short of pushing a change, I mean.)

I've taken a stab at updating doc/release-notes.md as well in this PR. Let me know how that looks.

**Comment by ryanofsky** [comment]
I think if you're a github project member you can restart travis jobs.

**Review by ryanofsky — COMMENTED** [review]
utACK 3121d76ba11043ea5c4e957ac0c3edbf21d1e84d. Updated release notes look good to me.

**Comment by hkjn** [comment]
Ah, you mean if you authorize travis-ci.org to access your Github repos / orgs some button shows up on the build results page? I've been avoiding that due to the wide-ranging permissions they ask for, but maybe there's a need to be pragmatic..

**Comment by ryanofsky** [comment]
> Ah, you mean if you authorize travis-ci.org to access your Github repos / orgs some button shows up on the build results page? I've been avoiding that due to the wide-ranging permissions they ask for, but maybe there's a need to be pragmatic..

If you become a member of the bitcoin/bitcoin github project, a "restart job" shows up letting you restart travis runs associated with bitcoin/bitcoin PR's. Someone administering the project has to add you. You could ask about it on IRC.

Authorizing travis-ci.org to your github project would just let travis interact with your forked bitcoin repo, not have any effect on the main one.

**Comment by sipa** [comment]
Concept ACK

**Comment by hkjn** [comment]
Thanks for explaining Travis stuff, @ryanofsky, makes sense. I'm not going to bother poking anyone around joining the bitcoin project on GH at this time, I think, but will wait until I've made some more sizeable contributions.

Since tests passed on CI I think this can be merged at any time you want. (I'm still trying to debug the test failures I mentioned above, some of which seem persistent, but those tests fail on clean `master` as well locally, so clearly something different in my environment.)

**Comment by hkjn** [comment]
cc @TheBlueMatt @achow101, this PR is the follow-up we discussed in #11830, in case you would like to review and/or merge.

**Comment by achow101** [comment]
utACK 3121d76ba11043ea5c4e957ac0c3edbf21d1e84d

**Pull request merged**
