### PR TITLE
guix: scope pkg-config to Linux only

### PR DESCRIPTION
**Pull request by fanquake**
After #31181, `pkg-config` is no-longer needed for macOS or Windows Guix builds. It's still needed for Linux, as it's used by a Qt subdependency (fontconfig to find freetype). However we should also no-longer need it for Qt itself, when building using depends.

### CODE REVIEW

**Comment by fanquake** [comment]
Guix build (aarch64):
```bash
02cdb4ec345e0e4b2f3876dded48a468c864fe58515ae7e4d7f9a8c1c4911337  guix-build-7edc54b086ac/output/aarch64-linux-gnu/SHA256SUMS.part
83d376375b1d5309108acc9e02711138c826d38fca0a73e7cc6048b21f3c4ab1  guix-build-7edc54b086ac/output/aarch64-linux-gnu/bitcoin-7edc54b086ac-aarch64-linux-gnu-debug.tar.gz
25677323242badfd9be8c5fdbc71ecf9b663239842deb244bbca4bc90a311d4d  guix-build-7edc54b086ac/output/aarch64-linux-gnu/bitcoin-7edc54b086ac-aarch64-linux-gnu.tar.gz
de94c7597fe9075ccc8a19afdb3a7ccb6fbaa5e29bcfc9eab5cf3567cc9ce4e7  guix-build-7edc54b086ac/output/arm-linux-gnueabihf/SHA256SUMS.part
131e83e1039a0ae79db57596d42f796eb7004fc42f268e6e8f369f69b3f2363f  guix-build-7edc54b086ac/output/arm-linux-gnueabihf/bitcoin-7edc54b086ac-arm-linux-gnueabihf-debug.tar.gz
f0dbd6aa84e1d32811b1a9ac72b499cecc3c11fd98b8a4436a300d4f62a279d2  guix-build-7edc54b086ac/output/arm-linux-gnueabihf/bitcoin-7edc54b086ac-arm-linux-gnueabihf.tar.gz
d8b5b00a1e623f345e023af9c77936cb02b846685c840ff7b2039ab33d9a3bb7  guix-build-7edc54b086ac/output/arm64-apple-darwin/SHA256SUMS.part
fc991f442e79d58e85fb4b5b514eac6c17f65adb21af4f5877c4f212d5e7bf17  guix-build-7edc54b086ac/output/arm64-apple-darwin/bitcoin-7edc54b086ac-arm64-apple-darwin-unsigned.tar.gz
a005896805b302b9c0708c9379332be7adba63248e70d0d798ab91143d538cd1  guix-build-7edc54b086ac/output/arm64-apple-darwin/bitcoin-7edc54b086ac-arm64-apple-darwin-unsigned.zip
2c9f9659a2cf0eb6485351c3e562a4137aef5e4665e921cfa223fa332649b64b  guix-build-7edc54b086ac/output/arm64-apple-darwin/bitcoin-7edc54b086ac-arm64-apple-darwin.tar.gz
a5049ef8d82516209801fc31410042ad4dbb117a86276b089f695c4589778171  guix-build-7edc54b086ac/output/dist-archive/bitcoin-7edc54b086ac.tar.gz
4495f122b28665fa29ac442e677f062bfb7f7254fb624d5e79aa34b61029e7c3  guix-build-7edc54b086ac/output/powerpc64-linux-gnu/SHA256SUMS.part
90edfb3e508d0cfcdeaf604dbffefda98f6d17780970b3b93532cc281ab732f7  guix-build-7edc54b086ac/output/powerpc64-linux-gnu/bitcoin-7edc54b086ac-powerpc64-linux-gnu-debug.tar.gz
9922ff902a7c4538fed939184b99ff06aff0eb30da148c04ac194d0f11dc3354  guix-build-7edc54b086ac/output/powerpc64-linux-gnu/bitcoin-7edc54b086ac-powerpc64-linux-gnu.tar.gz
7365f5becf37ee2370c8c72e9cefde890d78147dae7a557ea24c3c2410429e77  guix-build-7edc54b086ac/output/riscv64-linux-gnu/SHA256SUMS.part
28c87bf4f083a550ac5a7d9475e8d2fd39c29562afd23fc0a03c6cac4280c7a8  guix-build-7edc54b086ac/output/riscv64-linux-gnu/bitcoin-7edc54b086ac-riscv64-linux-gnu-debug.tar.gz
e5e63871d27acdd84f94887288c3ca150f9ce1a52d4271a625146a187da7330f  guix-build-7edc54b086ac/output/riscv64-linux-gnu/bitcoin-7edc54b086ac-riscv64-linux-gnu.tar.gz
039a05b2f1523dfdee7334680762808e97120735ea5d633b493adafdacd5e2bb  guix-build-7edc54b086ac/output/x86_64-apple-darwin/SHA256SUMS.part
de4a98f6872c64c40548b60c611275deb5a42d932f69c4ca839eaae88024dfc3  guix-build-7edc54b086ac/output/x86_64-apple-darwin/bitcoin-7edc54b086ac-x86_64-apple-darwin-unsigned.tar.gz
530051855c39e626f857273fafae527e96975165bd1cbcffbdcd1d49e8ef4653  guix-build-7edc54b086ac/output/x86_64-apple-darwin/bitcoin-7edc54b086ac-x86_64-apple-darwin-unsigned.zip
ab15f8b665ec2a68919b3090459418213b4925c40d9d9abfdc18a22aec9d8985  guix-build-7edc54b086ac/output/x86_64-apple-darwin/bitcoin-7edc54b086ac-x86_64-apple-darwin.tar.gz
0ab1ba84141256e2edaa15ddd587c52e534c64590ee542d2c1711b16b174fead  guix-build-7edc54b086ac/output/x86_64-linux-gnu/SHA256SUMS.part
b8888c042d6219c698535b9c515f2c329587aba9954482dd9df835f7e6b09e8a  guix-build-7edc54b086ac/output/x86_64-linux-gnu/bitcoin-7edc54b086ac-x86_64-linux-gnu-debug.tar.gz
e3c0133a8738f99fff4884bc7aa678f201e9821599db497d7c11a63ecf386b63  guix-build-7edc54b086ac/output/x86_64-linux-gnu/bitcoin-7edc54b086ac-x86_64-linux-gnu.tar.gz
ff36b9a06ceded52acfc86b0396043d74d0d69f9eb193a8b49e03a5da9573309  guix-build-7edc54b086ac/output/x86_64-w64-mingw32/SHA256SUMS.part
a0100fd6dd1d6826c6d34fc8356904746272e834c419cbdcfbda9cba2245a2a3  guix-build-7edc54b086ac/output/x86_64-w64-mingw32/bitcoin-7edc54b086ac-win64-debug.zip
5c7e9987e17bae9b666f1d952dec03676f402b40bc4edcdb08e52d42ce999f83  guix-build-7edc54b086ac/output/x86_64-w64-mingw32/bitcoin-7edc54b086ac-win64-setup-unsigned.exe
b1e467751c1061bdba2e1e79a520c9d7085e9ebbb562171b444d7ab0c279ed4f  guix-build-7edc54b086ac/output/x86_64-w64-mingw32/bitcoin-7edc54b086ac-win64-unsigned.tar.gz
af6aa6489ab59b65bd250b5c909f56a5e64259acd2856de103dae15590e78763  guix-build-7edc54b086ac/output/x86_64-w64-mingw32/bitcoin-7edc54b086ac-win64.zip
```

**Comment by fanquake** [comment]
Dropped another patch and pruned a Qt libtool archive.

**Comment by fanquake** [comment]
Guix build (aarch64)
```bash
a9e1f628dd64913209e6f55f183453b046c91e44fb959ea61e0c40c0a8457e98  guix-build-2833befb7822/output/aarch64-linux-gnu/SHA256SUMS.part
d082fbc96abb72a4bb0495833b6361d1ab61f8eefc3423571589920ed6c89678  guix-build-2833befb7822/output/aarch64-linux-gnu/bitcoin-2833befb7822-aarch64-linux-gnu-debug.tar.gz
6d94622d87e86ceef908e2b05435ac7f0e4b7f3d224454f619155e44c36128b9  guix-build-2833befb7822/output/aarch64-linux-gnu/bitcoin-2833befb7822-aarch64-linux-gnu.tar.gz
ca288057fc618c4094493e8e56e8d52f9bfcbabcd3b57dc69d2820749d7c6a7e  guix-build-2833befb7822/output/arm-linux-gnueabihf/SHA256SUMS.part
3bdf82ddd59025bb4cdd193490a8ae5c23aca8e08ccc45a187e8c990a2991dca  guix-build-2833befb7822/output/arm-linux-gnueabihf/bitcoin-2833befb7822-arm-linux-gnueabihf-debug.tar.gz
478b436828a048baeeac55b96d82d4ed00f718f4466e57a3471a36796ae87daf  guix-build-2833befb7822/output/arm-linux-gnueabihf/bitcoin-2833befb7822-arm-linux-gnueabihf.tar.gz
3a6b711c56f860e77b58ca34c815ce52fb41021babd72ce7cba0451e75b604fe  guix-build-2833befb7822/output/arm64-apple-darwin/SHA256SUMS.part
dc7bfc859a829e02b87d2a105848bfb8644c9504aa8f95c1f9670a557347475a  guix-build-2833befb7822/output/arm64-apple-darwin/bitcoin-2833befb7822-arm64-apple-darwin-unsigned.tar.gz
39c4187c0ea3049aa91c61a225aabd27a261e0d50dddedde35f21b435437114b  guix-build-2833befb7822/output/arm64-apple-darwin/bitcoin-2833befb7822-arm64-apple-darwin-unsigned.zip
653de08be3b8c3cd4f041c5043685ed5d8f5eeba9b66e1b7dc87b40a54cb056e  guix-build-2833befb7822/output/arm64-apple-darwin/bitcoin-2833befb7822-arm64-apple-darwin.tar.gz
aeca6acbec6d6f430397c14368eab11080497b2b213d860388d54572691e8ef0  guix-build-2833befb7822/output/dist-archive/bitcoin-2833befb7822.tar.gz
ee5106db79f3e68a131effd77e79bf8aac4324af556b7df487de26d6c293e60f  guix-build-2833befb7822/output/powerpc64-linux-gnu/SHA256SUMS.part
e455419936ad9872d9510feddaacf8861e04f08c2c962121389f7efe217b1ddb  guix-build-2833befb7822/output/powerpc64-linux-gnu/bitcoin-2833befb7822-powerpc64-linux-gnu-debug.tar.gz
214b5f8dc179e92495ff553e07e7d806ab15626a8c6b1ec920106edd9d4c83d6  guix-build-2833befb7822/output/powerpc64-linux-gnu/bitcoin-2833befb7822-powerpc64-linux-gnu.tar.gz
6ef57b6e6b1da33d2d797f6938f8e9b83b161afc377e53803ab4611c9f474aa0  guix-build-2833befb7822/output/riscv64-linux-gnu/SHA256SUMS.part
8de54b80b91115d2b81a890c2fc8775d5b5e6bb728f7b58d0377a589c3cd20d0  guix-build-2833befb7822/output/riscv64-linux-gnu/bitcoin-2833befb7822-riscv64-linux-gnu-debug.tar.gz
b704b1b775e8ad24de0dff0c9807b801d6ac327e5d47612eafc2054635f5595a  guix-build-2833befb7822/output/riscv64-linux-gnu/bitcoin-2833befb7822-riscv64-linux-gnu.tar.gz
f8eb0fd05e90ee466695912b2917090d0256d1ac434fb866d92b4e35c561f241  guix-build-2833befb7822/output/x86_64-apple-darwin/SHA256SUMS.part
7eefa9abe6356f7082cdea6afb41382be73f5f6dc7cb3dcbb42e71a50d740fa6  guix-build-2833befb7822/output/x86_64-apple-darwin/bitcoin-2833befb7822-x86_64-apple-darwin-unsigned.tar.gz
21c8389e1d182481a94f2c2169e6d7d25ef7fd70a2d9013f305b0012db1fc848  guix-build-2833befb7822/output/x86_64-apple-darwin/bitcoin-2833befb7822-x86_64-apple-darwin-unsigned.zip
defe96ae51fb6f5d823969296e9332e755ae44ea1c852700e4e2687a0cba9ff3  guix-build-2833befb7822/output/x86_64-apple-darwin/bitcoin-2833befb7822-x86_64-apple-darwin.tar.gz
75c6dc47934112a266d258697e6536160e6553f70cf28c877c13ec574da1e27e  guix-build-2833befb7822/output/x86_64-linux-gnu/SHA256SUMS.part
10456e68bcce78f6202355fa529d20436e04f5cb69a1ea51a67a0f59405fb710  guix-build-2833befb7822/output/x86_64-linux-gnu/bitcoin-2833befb7822-x86_64-linux-gnu-debug.tar.gz
53f4becad0d0269810336539c4da70de554057d02f0426ae50681ba3b82805a1  guix-build-2833befb7822/output/x86_64-linux-gnu/bitcoin-2833befb7822-x86_64-linux-gnu.tar.gz
ffd34528ae99efab12f7d1c3b0f795316e5a644e7e044368fb96b330727e42cd  guix-build-2833befb7822/output/x86_64-w64-mingw32/SHA256SUMS.part
955a1b4163a32871f9577ca1bafc8b695a1ccc190d3041e7c236febe8f7f7116  guix-build-2833befb7822/output/x86_64-w64-mingw32/bitcoin-2833befb7822-win64-debug.zip
d6524abb909c22d6df390a157cd64384d73554b2843a795cf037f73510853978  guix-build-2833befb7822/output/x86_64-w64-mingw32/bitcoin-2833befb7822-win64-setup-unsigned.exe
b622c49758e00b01f19da57b808cb562f68431adc64f7a7437e1db856ab03f7c  guix-build-2833befb7822/output/x86_64-w64-mingw32/bitcoin-2833befb7822-win64-unsigned.tar.gz
77de2c8c86e36b394e96323d83d90f9b9d6dde7a1f119a066234daa3f405de49  guix-build-2833befb7822/output/x86_64-w64-mingw32/bitcoin-2833befb7822-win64.zip
```

**Comment by TheCharlatan** [comment]
Guix build (aarch64):
```
a9e1f628dd64913209e6f55f183453b046c91e44fb959ea61e0c40c0a8457e98  guix-build-2833befb7822/output/aarch64-linux-gnu/SHA256SUMS.part
d082fbc96abb72a4bb0495833b6361d1ab61f8eefc3423571589920ed6c89678  guix-build-2833befb7822/output/aarch64-linux-gnu/bitcoin-2833befb7822-aarch64-linux-gnu-debug.tar.gz
6d94622d87e86ceef908e2b05435ac7f0e4b7f3d224454f619155e44c36128b9  guix-build-2833befb7822/output/aarch64-linux-gnu/bitcoin-2833befb7822-aarch64-linux-gnu.tar.gz
ca288057fc618c4094493e8e56e8d52f9bfcbabcd3b57dc69d2820749d7c6a7e  guix-build-2833befb7822/output/arm-linux-gnueabihf/SHA256SUMS.part
3bdf82ddd59025bb4cdd193490a8ae5c23aca8e08ccc45a187e8c990a2991dca  guix-build-2833befb7822/output/arm-linux-gnueabihf/bitcoin-2833befb7822-arm-linux-gnueabihf-debug.tar.gz
478b436828a048baeeac55b96d82d4ed00f718f4466e57a3471a36796ae87daf  guix-build-2833befb7822/output/arm-linux-gnueabihf/bitcoin-2833befb7822-arm-linux-gnueabihf.tar.gz
3a6b711c56f860e77b58ca34c815ce52fb41021babd72ce7cba0451e75b604fe  guix-build-2833befb7822/output/arm64-apple-darwin/SHA256SUMS.part
dc7bfc859a829e02b87d2a105848bfb8644c9504aa8f95c1f9670a557347475a  guix-build-2833befb7822/output/arm64-apple-darwin/bitcoin-2833befb7822-arm64-apple-darwin-unsigned.tar.gz
39c4187c0ea3049aa91c61a225aabd27a261e0d50dddedde35f21b435437114b  guix-build-2833befb7822/output/arm64-apple-darwin/bitcoin-2833befb7822-arm64-apple-darwin-unsigned.zip
653de08be3b8c3cd4f041c5043685ed5d8f5eeba9b66e1b7dc87b40a54cb056e  guix-build-2833befb7822/output/arm64-apple-darwin/bitcoin-2833befb7822-arm64-apple-darwin.tar.gz
aeca6acbec6d6f430397c14368eab11080497b2b213d860388d54572691e8ef0  guix-build-2833befb7822/output/dist-archive/bitcoin-2833befb7822.tar.gz
ee5106db79f3e68a131effd77e79bf8aac4324af556b7df487de26d6c293e60f  guix-build-2833befb7822/output/powerpc64-linux-gnu/SHA256SUMS.part
e455419936ad9872d9510feddaacf8861e04f08c2c962121389f7efe217b1ddb  guix-build-2833befb7822/output/powerpc64-linux-gnu/bitcoin-2833befb7822-powerpc64-linux-gnu-debug.tar.gz
214b5f8dc179e92495ff553e07e7d806ab15626a8c6b1ec920106edd9d4c83d6  guix-build-2833befb7822/output/powerpc64-linux-gnu/bitcoin-2833befb7822-powerpc64-linux-gnu.tar.gz
6ef57b6e6b1da33d2d797f6938f8e9b83b161afc377e53803ab4611c9f474aa0  guix-build-2833befb7822/output/riscv64-linux-gnu/SHA256SUMS.part
8de54b80b91115d2b81a890c2fc8775d5b5e6bb728f7b58d0377a589c3cd20d0  guix-build-2833befb7822/output/riscv64-linux-gnu/bitcoin-2833befb7822-riscv64-linux-gnu-debug.tar.gz
b704b1b775e8ad24de0dff0c9807b801d6ac327e5d47612eafc2054635f5595a  guix-build-2833befb7822/output/riscv64-linux-gnu/bitcoin-2833befb7822-riscv64-linux-gnu.tar.gz
f8eb0fd05e90ee466695912b2917090d0256d1ac434fb866d92b4e35c561f241  guix-build-2833befb7822/output/x86_64-apple-darwin/SHA256SUMS.part
7eefa9abe6356f7082cdea6afb41382be73f5f6dc7cb3dcbb42e71a50d740fa6  guix-build-2833befb7822/output/x86_64-apple-darwin/bitcoin-2833befb7822-x86_64-apple-darwin-unsigned.tar.gz
21c8389e1d182481a94f2c2169e6d7d25ef7fd70a2d9013f305b0012db1fc848  guix-build-2833befb7822/output/x86_64-apple-darwin/bitcoin-2833befb7822-x86_64-apple-darwin-unsigned.zip
defe96ae51fb6f5d823969296e9332e755ae44ea1c852700e4e2687a0cba9ff3  guix-build-2833befb7822/output/x86_64-apple-darwin/bitcoin-2833befb7822-x86_64-apple-darwin.tar.gz
75c6dc47934112a266d258697e6536160e6553f70cf28c877c13ec574da1e27e  guix-build-2833befb7822/output/x86_64-linux-gnu/SHA256SUMS.part
10456e68bcce78f6202355fa529d20436e04f5cb69a1ea51a67a0f59405fb710  guix-build-2833befb7822/output/x86_64-linux-gnu/bitcoin-2833befb7822-x86_64-linux-gnu-debug.tar.gz
53f4becad0d0269810336539c4da70de554057d02f0426ae50681ba3b82805a1  guix-build-2833befb7822/output/x86_64-linux-gnu/bitcoin-2833befb7822-x86_64-linux-gnu.tar.gz
ffd34528ae99efab12f7d1c3b0f795316e5a644e7e044368fb96b330727e42cd  guix-build-2833befb7822/output/x86_64-w64-mingw32/SHA256SUMS.part
955a1b4163a32871f9577ca1bafc8b695a1ccc190d3041e7c236febe8f7f7116  guix-build-2833befb7822/output/x86_64-w64-mingw32/bitcoin-2833befb7822-win64-debug.zip
d6524abb909c22d6df390a157cd64384d73554b2843a795cf037f73510853978  guix-build-2833befb7822/output/x86_64-w64-mingw32/bitcoin-2833befb7822-win64-setup-unsigned.exe
b622c49758e00b01f19da57b808cb562f68431adc64f7a7437e1db856ab03f7c  guix-build-2833befb7822/output/x86_64-w64-mingw32/bitcoin-2833befb7822-win64-unsigned.tar.gz
77de2c8c86e36b394e96323d83d90f9b9d6dde7a1f119a066234daa3f405de49  guix-build-2833befb7822/output/x86_64-w64-mingw32/bitcoin-2833befb7822-win64.zip
```

**Comment by TheCharlatan** [comment]
Looks like we could could also get rid of the pkgconfig hints in the toolchain file: https://github.com/TheCharlatan/bitcoin/commit/1a6724af305122973efcc8a329e98f41077314a2 (did a guix build with this patch too).

**Comment by fanquake** [comment]
> https://github.com/TheCharlatan/bitcoin/commit/1a6724af305122973efcc8a329e98f41077314a2

Pulled that in. Added another commit for sqlite.

**Comment by fanquake** [comment]
Guix Build (x86_64):
```bash
780670d401a6f110231c6a941c3e044065624f4c60fe1ce4340992c8bf8513a7  guix-build-bcd82b13f464/output/aarch64-linux-gnu/SHA256SUMS.part
2ecebfbbf8f557d371d7eecb312bc6a17d8ce1d38db94acf84f7571202f8a688  guix-build-bcd82b13f464/output/aarch64-linux-gnu/bitcoin-bcd82b13f464-aarch64-linux-gnu-debug.tar.gz
2dd1837f044308c53ec5a2cb76b5f93497e08561c1b7c1c7efeb3af5e0a3afdf  guix-build-bcd82b13f464/output/aarch64-linux-gnu/bitcoin-bcd82b13f464-aarch64-linux-gnu.tar.gz
b2b6a2de895dcb68ea5eec45f5bfe6d5f681ba20000b4c7b7697dd2f5f135e21  guix-build-bcd82b13f464/output/arm-linux-gnueabihf/SHA256SUMS.part
5b85084622405ab91f44e033722ec514a1d1d5906a336f20426ed2318133e2fa  guix-build-bcd82b13f464/output/arm-linux-gnueabihf/bitcoin-bcd82b13f464-arm-linux-gnueabihf-debug.tar.gz
e8b1aec4cbb47b279c954cbe0693ade69c05f71a0ea039f3ee2bebe6f154c6b4  guix-build-bcd82b13f464/output/arm-linux-gnueabihf/bitcoin-bcd82b13f464-arm-linux-gnueabihf.tar.gz
c50ee8b560c5d89c6486956db100972c1d3bf280a854241e76d96cc142c55afe  guix-build-bcd82b13f464/output/arm64-apple-darwin/SHA256SUMS.part
5d4840e2de0a1f641be9c09fbf1df5db9e43f9b07d554fa22dd8a7b5429dcbb4  guix-build-bcd82b13f464/output/arm64-apple-darwin/bitcoin-bcd82b13f464-arm64-apple-darwin-unsigned.tar.gz
80525c4d2f46d0b0c2b5d8422adc44c9c601659a9a94dddb23414735c6c8da3c  guix-build-bcd82b13f464/output/arm64-apple-darwin/bitcoin-bcd82b13f464-arm64-apple-darwin-unsigned.zip
ceb25a8e6370c51084b4661b36ba03c4b4c2de0d6c674e7a07bd712f89b432f9  guix-build-bcd82b13f464/output/arm64-apple-darwin/bitcoin-bcd82b13f464-arm64-apple-darwin.tar.gz
c62f5a1e3f700e8b4237bd44a8563c076b8281f84bdc40b25a9281a2db995755  guix-build-bcd82b13f464/output/dist-archive/bitcoin-bcd82b13f464.tar.gz
3336d721d7664626b91a429a89af03d2cc71b6e3ebbc7452d98d78d4b7d87c92  guix-build-bcd82b13f464/output/powerpc64-linux-gnu/SHA256SUMS.part
08c5c06ea79266fe00b63e70c6176c355aadd3ea34c635c956968e1be2ebf598  guix-build-bcd82b13f464/output/powerpc64-linux-gnu/bitcoin-bcd82b13f464-powerpc64-linux-gnu-debug.tar.gz
612bb29bc1268e2765e5e0632daff9c556941ae020dd2344f32460972b1a3dd7  guix-build-bcd82b13f464/output/powerpc64-linux-gnu/bitcoin-bcd82b13f464-powerpc64-linux-gnu.tar.gz
61d879bf43da184a94847bdb1e0e1cd42a34d40ef625906db3c9d8afbf2a8944  guix-build-bcd82b13f464/output/riscv64-linux-gnu/SHA256SUMS.part
f36895d3ae9e77e281fe924db0803719d182c1caca8201d6fb23d4d3136a94c3  guix-build-bcd82b13f464/output/riscv64-linux-gnu/bitcoin-bcd82b13f464-riscv64-linux-gnu-debug.tar.gz
62a4b166f68fdfd5cca1c1b129cfbad15176757828a3bae6919e386762546bbe  guix-build-bcd82b13f464/output/riscv64-linux-gnu/bitcoin-bcd82b13f464-riscv64-linux-gnu.tar.gz
13a4d57e12699803eefcebd3bb3e182b06c15796e3f06c4c90bad8916692e223  guix-build-bcd82b13f464/output/x86_64-apple-darwin/SHA256SUMS.part
3c1195b51a96087cb79fc2f9a88401521c84d28de2a14cc62668603e11dd6234  guix-build-bcd82b13f464/output/x86_64-apple-darwin/bitcoin-bcd82b13f464-x86_64-apple-darwin-unsigned.tar.gz
681b31f58d457532eb7513693ef8f0fa9f4265a44a382a6a150a297f968454fd  guix-build-bcd82b13f464/output/x86_64-apple-darwin/bitcoin-bcd82b13f464-x86_64-apple-darwin-unsigned.zip
b1d76f128e10a719faae23a4d69105094e92a50c9411a817bcb89fd4371ecd4e  guix-build-bcd82b13f464/output/x86_64-apple-darwin/bitcoin-bcd82b13f464-x86_64-apple-darwin.tar.gz
17dec23ca245d799b9cd1dec86e28c7e155eefdcaa9e6bcda3421788c7eeabf9  guix-build-bcd82b13f464/output/x86_64-linux-gnu/SHA256SUMS.part
9bb6b3d707d5d93b232aaa5237a727a272373bac74302bb5aa140ac6e6efd710  guix-build-bcd82b13f464/output/x86_64-linux-gnu/bitcoin-bcd82b13f464-x86_64-linux-gnu-debug.tar.gz
ae9ef8e7a0789a3c25bf93f20e1ed70505e836a0fba3aeb90d0ecc4db1a401e1  guix-build-bcd82b13f464/output/x86_64-linux-gnu/bitcoin-bcd82b13f464-x86_64-linux-gnu.tar.gz
fa1d413e0c8c69786a6ee9334d31b6b46c3a353658b32261add9e2b241ca1768  guix-build-bcd82b13f464/output/x86_64-w64-mingw32/SHA256SUMS.part
4cf55ea904f7ebd3e813b32ca32f59d4f590845ff4db287820f4e0507e210ac4  guix-build-bcd82b13f464/output/x86_64-w64-mingw32/bitcoin-bcd82b13f464-win64-debug.zip
efb5f44bda8eddb2794864020ca649ef1078cd65a46405f707be01d79c3a72a5  guix-build-bcd82b13f464/output/x86_64-w64-mingw32/bitcoin-bcd82b13f464-win64-setup-unsigned.exe
4056eecf1542d1204b35b28ac4f7aea8e2194e3cd7629bf2c33e9831ab560bf6  guix-build-bcd82b13f464/output/x86_64-w64-mingw32/bitcoin-bcd82b13f464-win64-unsigned.tar.gz
16ee769d6b099f4c3fdf8fa48d90a935502465cc9a151a563e7c2acbb392e2ad  guix-build-bcd82b13f464/output/x86_64-w64-mingw32/bitcoin-bcd82b13f464-win64.zip
```

**Review by sedited — APPROVED** [review]
ACK bcd82b13f4649e57d7d106856aab7b2a6296d728

**Comment by hebasto** [comment]
Concept ACK.

**Pull request merged**
