### PR TITLE
zmq: use std::string in zmqError()

### PR DESCRIPTION
**Pull request by fanquake**
This is two minor changes. The first is to change `zmqError` to take a `const std::string&` instead of a `const char*`. The second is to change the second portion of `zmqError` to print `msg: message` rather than `errno=message`, given that `zmq_strerror` returns a message. To me, this seems more readable / useful than output like: `Error: Unable to initialize context errno=No such file or directory`.

### CODE REVIEW

**Comment by theStack** [comment]
Concept ACK

nit: Not sure if we have it in the coding guidelines, but I think we almost always pass `std::string`s by reference rather than by value
(see e.g. `git grep "(.*const std::string.*)"`)

**Comment by fanquake** [comment]
> always pass std::strings by reference

Thanks, addressed.

**Review by theStack — APPROVED** [review]
Code-Review ACK 3f05a9e681c4b72d99ddda8ccb6911d6ffad44ec

**Comment by practicalswift** [comment]
cr ACK 3f05a9e681c4b72d99ddda8ccb6911d6ffad44ec

**Comment by instagibbs** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/22200/commits/3f05a9e681c4b72d99ddda8ccb6911d6ffad44ec

**Pull request merged**
