### PR TITLE
Add Whitepaper Link

### PR DESCRIPTION
**Pull request by wawesomeNOGUI**

### CODE REVIEW

**Comment by hebasto** [comment]
@wawesomeNOGUI 

Please see https://github.com/bitcoin-core/gui/pull/302

**Comment by jonatack** [comment]
Search on "whitepaper" in the closed pull requests. 😉

**Comment by wawesomeNOGUI** [comment]
Ohhh is there no truly official whitepaper link?

**Comment by hebasto** [comment]
> Ohhh is there no truly official whitepaper link?

True Bitcoin resources has nothing "official" :)

**Comment by wawesomeNOGUI** [comment]
Decentralised stuff is pretty interesting! Is that link I found a good copy of the whitepaper though?

**Comment by RandyMcMillan** [comment]
@hebasto @jonatack,

Why not just add a getwhitepaper command to the bitcoin-cli?

or instructions on extracting it from the command line?


```
seq 0 947 | (while read -r n; do bitcoin-cli gettxout 54e48e5f5c656b26c3bca14a8c95aa583d07ebe84dde3b7dd4a78f4e4186e713 $n | jq -r '.scriptPubKey.asm' | awk '{ print $2 $3 $4 }'; done) | tr -d '\n' | cut -c 17-368600 | xxd -r -p > bitcoin.pdf

```

That would be better than including an external link to the docs.

**Comment by hebasto** [comment]
> Is that link I found a good copy of the whitepaper though?

Yeap :)
You always could compare it with other sources, e.g., https://bitcoin.stackexchange.com/questions/35959/how-is-the-whitepaper-decoded-from-the-blockchain-tx-with-1000x-m-of-n-multisi

**Comment by hebasto** [comment]
> @hebasto @jonatack,
> 
> Why not just add a getwhitepaper command to the bitcoin-cli?

Why should it be a part of this repo?

**Comment by jonatack** [comment]
> > Is that link I found a good copy of the whitepaper though?
> 
> 
> 
> Yeap :)
> 
> You always could compare it with other sources, e.g., https://bitcoin.stackexchange.com/questions/35959/how-is-the-whitepaper-decoded-from-the-blockchain-tx-with-1000x-m-of-n-multisi

(and https://gist.github.com/harding/dabea3d83c695e6b937bf090eddf2bb3  is a complementary read)

**Comment by michaelfolkson** [comment]
I'd quite like to nip in the bud all these white paper PRs.

I'm thinking delete "For more information read the original Bitcoin whitepaper" entirely from the README.

Or alternatively add an additional sentence "This is not hosted in the Bitcoin Core repo but is available at various other external sites. Please do not open a PR to add a link to this repo."

Thoughts?

**Comment by wawesomeNOGUI** [comment]
Isn’t the whitepaper is a pretty important historical document for bitcoin though?

**Comment by michaelfolkson** [comment]
wawesomeNOGUI:

> Isn’t the whitepaper a pretty important historical document for bitcoin though?

Lots of excellent sites covering Bitcoin's history e.g. https://nakamotoinstitute.org/, https://diyhpl.us/wiki/transcripts/, https://btctranscripts.com/, https://www.lopp.net/bitcoin-information/history.html

This repo covers Git history, issues, PRs for the Bitcoin Core implementation. It doesn't need to store general documents of Bitcoin's history like the above sites.

**Comment by prayank23** [comment]
> Isn’t the whitepaper a pretty important historical document for bitcoin though?

Yes. However, maintainers and few contributors in this project (Bitcoin Core: One of the implementation for Bitcoin) don't think its needed in this repository.

You can read the original whitepaper here: https://web.archive.org/web/20091128185352/http://voxel.dl.sourceforge.net/project/bitcoin/Research%20Paper/bitcoin.pdf/bitcoin.pdf

Links are available in README for other implementations as well: https://github.com/bitcoinknots/bitcoin

In case you prefer reading the white paper with a URL that starts with [github.com/bitcoin/bitcoin](https://github.com/bitcoin/bitcoin/blob/d0fe3ec88c427b50aacb9ef895046ab949820749/doc/whitepaper/whitepaper.md)

**Pull request closed without merging**
