### PR TITLE
28950 followups

### PR DESCRIPTION
**Pull request by instagibbs**
Follow-ups to https://github.com/bitcoin/bitcoin/pull/28950

### CODE REVIEW

**Comment by glozow** [comment]
Did you want to take https://github.com/bitcoin/bitcoin/pull/28950#discussion_r1522819044?

**Comment by instagibbs** [comment]
@glozow punting on that one, thanks

**Comment by fanquake** [comment]
```bash
test/txpackage_tests.cpp:821:103: error: argument name 'client_maxfeerate' in comment does not match parameter name 'client_max_feerate' [bugprone-argument-comment,-warnings-as-errors]
  821 |                                                           package_rich_parent, /*test_accept=*/false, /*client_maxfeerate=*/{});
      |                                                                                                       ^~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                       /*client_max_feerate=*/
```

**Review by stickies-v — COMMENTED** [review]
Approach ACK cc2a4a6b8ec2c01ef4eed464c5173255d2ff7497. First commit should probably be a scripted-diff though, and I think the last 2 commits make more sense when squashed?

> LGTM. Did you want to take https://github.com/bitcoin/bitcoin/pull/28950#discussion_r1522819044?

I think that's fine to leave as is, as per https://github.com/bitcoin/bitcoin/pull/28950#discussion_r1537736698

**Comment by instagibbs** [comment]
> First commit should probably be a scripted-diff though, and I think the last 2 commits make more sense when squashed?

both done, thanks

**Review by glozow — COMMENTED** [review]
utACK 7b29119d79efbc8c4148f350cc86531fde8b7251

**Review by stickies-v — APPROVED** [review]
ACK 7b29119d79efbc8c4148f350cc86531fde8b7251

**Pull request merged**
