### PR TITLE
Rework same-chain from abusing DoS banning, to explicit checks

### PR DESCRIPTION
**Pull request by luke-jr**
This fixes bugs where we end up banning peers running different consensus rules (including old nodes following a softfork). Since we rely on having peers enforcing the same rules as us, it also enforces that outbound non-feeler connections must have and maintain the same tip block; if they diverge from us, we disconnect them (and find a replacement).

### CODE REVIEW

**Comment by gmaxwell** [comment]
bleh please don't use reject for this.

**Comment by luke-jr** [comment]
@gmaxwell Do you have a better solution? It doesn't seem like we have any other way to determine that case?

**Comment by luke-jr** [comment]
```
p2p-compactblocks.py failed, Duration: 83 s
```

But it passes locally... :/

**Comment by luke-jr** [comment]
This breaks because compact blocks allows relaying invalid blocks without penalty, but there is no indication at all even later, whether the peer sending you the compact block has accepted it himself or not... so basically we can almost never know if a compact-block peer is on a different tip than us.

Ideas for how to solve this?

**Comment by luke-jr** [comment]
Closed due to impracticality, and superceded by #10593

**Pull request closed without merging**
