### PR TITLE
[RPC] Remove waitforblock and waitfornewblock

### PR DESCRIPTION
**Pull request by achow101**
Removed because these RPCs are for tests only and are now unused

### CODE REVIEW

**Comment by sipa** [comment]
@theuni These RPCs were added in #8680, and never used (only `waitforblockatheight` was ever used). Is there a plan or expectation that they'll ever be needed?

**Comment by NicolasDorier** [comment]
I did not know it existed, but I think it is very useful, I would use it if I am sure it stays.

Easier to use than configuring blocknotify or ZMQ.

**Comment by laanwj** [comment]
Would be nice to have a test for them, if we keep them.

**Comment by theuni** [comment]
@sipa If ever used, I figured it'd only be to make some python tests less cumbersome.

@jnewbery Do you have any use for these? Otherwise, I'd be fine with removing.

**Comment by jnewbery** [comment]
> @jnewbery Do you have any use for these? Otherwise, I'd be fine with removing.

Not currently, although they may be useful for some tests. On the other hand, it's just as easy to call `getbestblockhash` or `getblock` in a loop until the desired block has been accepted.

I have no issue with these being removed or staying (as long as they remain hidden and not part of the public API).

**Comment by MarcoFalke** [comment]
I am ok with removing or keeping and adding tests. Though, it seems the functionality is redundant:

* waitfornewblock() ---> waitforblockheight(current_height + 1)
* waitforblock(hash) ---> waitforblockheight(hash_height) && getblockhash(hash_height) == hash

**Comment by MarcoFalke** [comment]
utACK 5fc1253bb8b95d34880e565cb2aa193caab06d71

**Comment by theuni** [comment]
@MarcoFalke They're intended to be atomic operations as we were dealing with some test race issues a while back. They're indeed redundant if atomicity isn't needed.

**Comment by NicolasDorier** [comment]
well, I think they are useful. Instead of polling for new block I would definitively use that.

**Comment by sipa** [comment]
utACK b69194916c5fc8ebdaebb04e3cc6c4aab37e1c49

**Comment by achow101** [comment]
rebased

**Comment by promag** [comment]
utACK b691949.

IMO blocking or long pool RPC/REST calls should be avoided.

**Comment by NicolasDorier** [comment]
I think this should not be removed, but documented. Right now the only way to get block notification is to connect to to the P2P layer or use ZeroMQ. Both requires additional configuration. (also, I have never managed to make ZeroMQ notifications works with a .NET Client)
I end up connecting to my node by P2P to get new blocks.

I would have known that such RPC method existed, I would have definitively used it in place of my current solution.

I think a `WaitWalletTransaction` would also be higly helpful.

**Comment by luke-jr** [comment]
@NicolasDorier FYI there is also `blocknotify`

**Comment by NicolasDorier** [comment]
Same problem as ZeroMQ. It requires additional configuration on the bitcoin node, and need additional code, the program called by `blocknotify` need a way to notify the program interested into this event by another mechanism.... This is a pain.

**Comment by jnewbery** [comment]
@NicolasDorier - Be careful about using these RPCs in product code. They were introduced as test tools only and there is no guarantee that they will work as you expect. For example, I just managed to break bitcoind's RPC server by running 4 `waitfornewblock` requests in parallel. Any request after that fails, and I don't think there's any way to cancel the `waitfornewblock` requests.

There are also no tests for them and they are hidden debug RPCs, so it's likely you'd be the only one using them, which increases the risk of regressions.

I'm slightly averse to long-polling RPCs in general, but I'm also not too concerned if these stay (with the provisos above).

**Comment by promag** [comment]
Agree with @jnewbery. You can have a small utility to listen zmq messages and forward the most suitable transport for your .NET app.

And I think doing that to some kind of queue would benefit both parts, specially if the queue has means to easily notify you app.

**Comment by NicolasDorier** [comment]
@jnewbery I know there is a maximum number of concurrent requests, this can be notified to the user when it happens.

@promag I enumerated the problems of using ZMQ above. This just make it harder to build stuff on top of Core by making it require more configuration and dependency.
It is easier to connect to the P2P layer and listen for new block than it is to setup ZMQ, and listening through it with a cross plateform library.

**Comment by promag** [comment]
> making it require more configuration

@NicolasDorier IMO that´s fine. Even if there was websocket support, it should have/require configuration before it could be used. You also configure RPC right?

**Comment by NicolasDorier** [comment]
@promag no I do not configure RPC. If bitcoin is running with default parameters, I can connect to it through the wellknown port and wellknown cookiefile.

**Comment by achow101** [comment]
Rebased

**Comment by NicolasDorier** [comment]
If https://github.com/bitcoin/bitcoin/pull/10519 would be merged, I would see no problem removing this rpc method.

**Comment by laanwj** [comment]
Needs rebase, if still relevant.

**Comment by NicolasDorier** [comment]
Seems like nobody is using it, and on my side I am not at ease using something that might disappear tomorrow, so feel free to delete it.

But I still think it is a shame, this is the most useful RPC call ever! :(

**Comment by achow101** [comment]
Rebased

**Comment by nopara73** [comment]
NACK.

`waitfor...` RPC calls are very useful. They should be documented rather than removed. If they ruin some coding best practices, then remove it.

Imagine a wallet daemon that gives you p2pkh only through RPC, it gives you p2wpkh only through ZMQ and it gives you p2wpkh over p2sh only through websockets. Sure that works, but you must have 3 different communication channels properly implemented and configured in order to get all three of them. **The more communication protocols a software uses the less reliable it is.** Networking may be the trickiest coding challenge, where so many little things can go wrong.

https://github.com/MetacoSA/NBitcoin/pull/363
https://github.com/nopara73/MagicalCryptoWallet/issues/32

**Comment by laanwj** [comment]
As both @NicolasDorier and @nopara73 are apparently using these calls (or would if they aren't goin to be removed) and think they are useful, I don't think they should be removed, then.
Closing.

**Comment by nopara73** [comment]
Personally we were using but removed them, due to this change, so it's fine by me.

**Comment by jnewbery** [comment]
> Although I'd still not be happy if the user space breaks (like ever.)

These RPC methods were introduced as hidden calls for testing only. They shouldn't be used in production systems. They should either be removed (since they're unused in testing now), or made unhidden and fully supported. I'd vote for removing them.

**Comment by MarcoFalke** [comment]
Marked up for grabs for someone to address my feedback: https://github.com/bitcoin/bitcoin/pull/10519#discussion_r173045365

**Pull request closed without merging**
