### PR TITLE
Inscriptions option

### PR DESCRIPTION
**Pull request by Retropex**
There has been a lot of spam on bitcoin for several months now, it is urgent to do something to stop the spam of Inscriptions  on the chain. A whole bunch of shitcoins arrived because of brc-20 and strips the least informed bitcoiners on these topics. a lot of bitcoiners praise the assets of bitcoin such as the fact that it is a hard currency unlike shitcoins so why let this thing proliferate on the chain?

I hope that the developers will not just refuse this request and especially that they will take a little of their time to make this code optional for example with an `Inscription=0` in the file `bitcoin.conf`

### CODE REVIEW

**Comment by Retropex** [comment]
Thank you for considering the question @fanquake

**Comment by michaelfolkson** [comment]
@Retropex: Ask on [Bitcoin StackExchange](https://bitcoin.stackexchange.com/) whether what you are suggesting is a good idea (short answer is any default policy change or custom policy option doesn't necessarily stop inscriptions as you can still submit consensus compatible transactions directly to a miner). There is already an [ordinals tag](https://bitcoin.stackexchange.com/questions/tagged/ordinals) with previous Q&A on this topic.

**Comment by pavel-vasin** [comment]
>you can still submit consensus compatible transactions directly to a miner

Is it time to remove the standard transaction policy?

**Comment by michaelfolkson** [comment]
@pavel-vasin: Discussed [here](https://github.com/bitcoin/bitcoin/pull/27578). Bitcoin StackExchange next time please.

**Comment by Fiach-Dubh** [comment]
> @Retropex: Ask on [Bitcoin StackExchange](https://bitcoin.stackexchange.com/) whether what you are suggesting is a good idea (short answer is any default policy change or custom policy option doesn't necessarily stop inscriptions as you can still submit consensus compatible transactions directly to a miner). There is already an [ordinals tag](https://bitcoin.stackexchange.com/questions/tagged/ordinals) with previous Q&A on this topic.

what if the intent of such a filter is not to stop them, but to simply not have ones mempool (whether pool or individual) participate in their dissemination. 

ie personal choice. 

This choice, even though irrelevant to an effect network wide, may still be popular enough for people to be running mystery meat clients. 

Would bringing this within Bitcoin Core peer review, as was with datacarrier=0 be a consideration?

**Comment by dzyphr** [comment]
It  will be left up to personal choice no matter what, however I think we should take the approach of mitigating anything that really looks like spam which again will be personal choice.

**Comment by RicYashiroLee** [comment]
> @Retropex: Ask on [Bitcoin StackExchange](https://bitcoin.stackexchange.com/) whether what you are suggesting is a good idea (short answer is any default policy change or custom policy option doesn't necessarily stop inscriptions as you can still submit consensus compatible transactions directly to a miner). There is already an [ordinals tag](https://bitcoin.stackexchange.com/questions/tagged/ordinals) with previous Q&A on this topic.

The key word is 'cumbersome', to make  hash-anchoring(stamps, inscriptions, etc) as cumbersome as possible. The argument of 'because it is possible to to it in some other way, let us then loosen up all doors to garbage data' is a bad answer, not one of a true bitcoiner, IMV.

**Comment by Retropex** [comment]
@MarcoFalke @fanquake @jonatack Still no consideration for implementing countermeasures?

The number of [nodes](https://bitnodes.io) seems to be decreasing lately, the [blocks](https://orangepill.ovh/fr/block/0000000000000000000476c0391f69f310e980ec1498493414a8b46f518dc8d4) are full of inscriptions and the [UTXO set](https://statoshi.info/d/000000009/unspent-transaction-output-set?orgId=1&refresh=10m&from=now-1y&to=now&viewPanel=8) continues to grow at a very worrying speed.

You can see in blue the inscriptions in each block on this [site](https://orangepill.ovh/fr/).



image

image

image

**Comment by Retropex** [comment]
Still no reaction to give the tools to the node runners to defend themselves?

image

[link](https://mempool.space/fr/graphs/mempool#1m)

**Pull request closed without merging**
