### PR TITLE
test: refactor: save MiniWallet mode explicitly

### PR DESCRIPTION
**Pull request by theStack**
Rather than abusing the member variables `self._priv_key` and `self._address` to determine the MiniWallet mode, save it explicitly (`self._mode`) in the constructor and use that instead to increase the readability and maintainability of the code.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Maybe add a default case of `assert 0` for the switch-case statements?

**Comment by theStack** [comment]
> Maybe add a default case of `assert 0` for the switch-case statements?

Thanks, done.

**Review by maflcko — APPROVED** [review]
review ACK be8d0dba15528ac75a2c73d9f696b1db567d4ca4 🔳

<details><summary>Show signature</summary>

Signature:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

review ACK be8d0dba15528ac75a2c73d9f696b1db567d4ca4 🔳
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEE+rVPoUahrI9sLGYTzit1aX5ppUgFAlwqrYAACgkQzit1aX5p
pUht5Qv7B7+t6K4PznSgERmfJZ82ePam0205AlBDgnrv0EOtUsLXWLm1+lGiwLTH
900qrc0mOP6V0c6q9MtwhS8UO0hNNOCPGNdmmzjBOZmg+f7grtCfq/LItKUm/YUN
qVpafM/rHNrqvnVqTYIdPSUpPFBPhAlM74b7BPwI8JdX9tqpWVIYJILz7b5lbNet
DEgAbIvAmP+cByOYoGP8F6LWOAj7Li1B/DyolnV41Z9So1sbvZeSCbllBq10FiQ9
QCUo6TyC2isMd8m7sOT6FIegzSVernThYyQ47wHDv2RyNGx1q4v/fOgynuJHHNo7
oD01nNinam4w6DyeR/Ll2sC40JqH7s6NASK/EmdLafZL+NB4dMaDdXLkxvSvXb0/
XnlWP5oK3WDL3CqjkKHlXoApbksKuzO4qwFyi4IrXdgdNAzbvfEXKFfpcIususme
HaDQKFCPP5jfNIEFLkUAXUDB+Tfvwe7/CzeHcLMnpXNuriAHVE5D3PI4Uui7wYLe
yrrsSwQX
=mUkX
-----END PGP SIGNATURE-----
```


</details>

**Review by kouloumos — COMMENTED** [review]
ACK be8d0dba15528ac75a2c73d9f696b1db567d4ca4, definitely helps with readability and maintainability! Even with the comments I often had to remind myself what mode each condition implied.

All tests pass with `test/functional/test_runner.py` on macOS 10.15

**Pull request merged**
