### PR TITLE
tests: Handle ImportError explicitly, improve comparisons against None

### PR DESCRIPTION
**Pull request by daniel-s-ingram**

### CODE REVIEW

**Comment by jonasschnelli** [comment]
meh ACK

**Comment by daniel-s-ingram** [comment]
Will do - thanks, @practicalswift!

**Comment by practicalswift** [comment]
@daniel-s-ingram Great! When doing that don't forget to enable `flake8` check `E711` in `test/lint/lint-python.sh` to make sure your fix becomes permanent until the end of time :-)

**Comment by laanwj** [comment]
> I think we should use is None/is not None instead of == None/!= None throughout the code base. The former is safer and faster. Feel free to open such a PR :-)

Agree. This is overall an improvement, IMO. I did change the PR title to be more comprehensible and in line with the actual changes.

utACK c9ba253f4f5d675d7736d24c1167229d0898ef1a

**Pull request merged**
