### PR TITLE
test: Properly raise FailedToStartError when rpc shutdown before warmup finished

### PR DESCRIPTION
**Pull request by maflcko**
Should fix issues such as https://travis-ci.org/github/bitcoin/bitcoin/jobs/671910152#L7034

### CODE REVIEW

**Comment by promag** [comment]
I think connection reset indicates that the server is not properly closing the connection - I suspect the header `Connection: close` doesn't reach the client (?) - so this might be some race/corner-case with libevent where the socket is closed too soon?

This doesn't invalidate this change since the retry attempts is limited.

**Comment by MarcoFalke** [comment]
>  I suspect the header Connection: close doesn't reach the client (?)

Why not? Wouldn't it throw the same exception if it reached the client?

**Comment by promag** [comment]
No, if the header reached the client then it would gracefully close, ECONNRESET means the server closed unexpectedly.

**Comment by MarcoFalke** [comment]
It has to throw some kind of exception if the connection is closed without returning a result (json or jsonexception), no?

**Comment by promag** [comment]
Yes, but why (or in what case) would it close without returning a result?

**Comment by MarcoFalke** [comment]
> Yes, but why (or in what case) would it close without returning a result? I mean, once the server accepts the connection, it should send the reply.

Right. This should probably be fixed in libevent or Bitcoin Core. The patch in this pull is to get the tests work around this issue in the meantime.

**Comment by promag** [comment]
> The patch in this pull is to get the tests work around this issue in the meantime.

Yeah I agree with this. I can't reproduce but looking at travis error this looks enough.

ACK for that reason.

**Comment by MarcoFalke** [comment]
It happens only in valgrind, so a race seems most likely

**Pull request merged**
