### PR TITLE
Move util files to directory

### PR DESCRIPTION
**Pull request by jimpo**
As discussed [here](https://github.com/bitcoin/bitcoin/pull/14074#issuecomment-429090584), this establishes a `util/` directory to introduce more organizational structure and have a clear place for new util files. It's really not scary to review, it's just one big scripted diff.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
The scripted diff will also run on non-git files that happen to be in the folder. Imo, this should be avoided by using a `git ls-files` with a filter or something.

**Comment by promag** [comment]
IMO scripted diff commit could have the mv commands to avoid having a bad commit.

**Comment by ken2812221** [comment]
Could you please apply this as the second commit? Thanks
```diff
diff --git a/build_msvc/libbitcoinconsensus/libbitcoinconsensus.vcxproj b/build_msvc/libbitcoinconsensus/libbitcoinconsensus.vcxproj
index 0be7e7e43..2c6c0a8b7 100644
--- a/build_msvc/libbitcoinconsensus/libbitcoinconsensus.vcxproj
+++ b/build_msvc/libbitcoinconsensus/libbitcoinconsensus.vcxproj
@@ -40,7 +40,7 @@
     <ClCompile Include="..\..\src\script\script.cpp" />
     <ClCompile Include="..\..\src\script\script_error.cpp" />
     <ClCompile Include="..\..\src\uint256.cpp" />
-    <ClCompile Include="..\..\src\utilstrencodings.cpp" />
+    <ClCompile Include="..\..\src\util\strencodings.cpp" />
   </ItemGroup>
   <ItemGroup>
     <None Include="packages.config" />
```

**Comment by ken2812221** [comment]
utACK d0f883e9c5c7dd1ac9efcd69eb0065e47376afef

**Comment by MarcoFalke** [comment]
utACK d0f883e9c5c7dd1ac9efcd69eb0065e47376afef

**Comment by scravy** [comment]
utACK d0f883e

**Comment by MeshCollider** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/14555/commits/d0f883e9c5c7dd1ac9efcd69eb0065e47376afef

**Comment by promag** [comment]
After rebase:
```diff
diff --git a/src/base58.cpp b/src/base58.cpp
index eac763394..e3d285339 100644
--- a/src/base58.cpp
+++ b/src/base58.cpp
@@ -6,7 +6,7 @@
 
 #include <hash.h>
 #include <uint256.h>
-#include <utilstrencodings.h>
+#include <util/strencodings.h>
 
 #include <assert.h>
 #include <string.h>
```

**Comment by ken2812221** [comment]
utACK 2068f089c8b7b90eb4557d3f67ea0f0ed2059a23

**Comment by fanquake** [comment]
tACK 2068f08
`make check` and ran the functional tests.

Might be a good to merge this now, to save the constant rebasing.  Doesn't look like this will break any ready to merge/PRs with ACKs etc.

**Comment by promag** [comment]
Agree with @fanquake, ACK 2068f08.

**Comment by laanwj** [comment]
utACK 2068f089c8b7b90eb4557d3f67ea0f0ed2059a23

- `util/system.h` is great naming, yes, the file is for os/system utilities
- We need to come up with guidelines (in the developer notes) what to put in `src/compat` versus `src/support` versus `src/util`, all three are more or less utilities. But that can be done later.

**Pull request merged**
