### PR TITLE
[Tests] Fix BIP65 p2p test

### PR DESCRIPTION
**Pull request by sdaftuar**
create_coinbase() was being called with the wrong argument

### CODE REVIEW

**Comment by sipa** [comment]
Why did Travis not detect this problem?

**Comment by sdaftuar** [comment]
It's one of the extended tests, not run by Travis.

**Comment by jgarzik** [comment]
it-works ACK

**Comment by petertodd** [comment]
Tested ACK

Gah, I should have caught that. :(

**Pull request merged**
