### PR TITLE
[Depends] Bump miniupnpc and config.guess+sub

### PR DESCRIPTION
**Pull request by fanquake**
Also includes latest config.guess & config.sub

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Is there a changelog for miniupnp? I can't find relevant commits here: https://github.com/miniupnp/miniupnp/commits/miniupnpd_1_9

**Comment by fanquake** [comment]
@jonasschnelli the changelog for miniupnpc is [here](http://miniupnp.tuxfamily.org/files/changelog.php?file=miniupnpc-1.9.20160209.tar.gz).
The changelogs for all other mini binaries can be found on this page http://miniupnp.tuxfamily.org/files/

**Comment by laanwj** [comment]
This would be the approximate diff (approximately, as it's based on dates - miniupnpc doesn't tag releases):
https://github.com/miniupnp/miniupnp/compare/3c18a3ef029ff9acf3b2fb15774ebc7b24e2d1f6...81e0ca10df401e7d188da36f20e118f68ddbd590

**Comment by theuni** [comment]
ACK on the config.guess/sub. Those miniupnpc parsing changes are scary as always.

**Pull request merged**
