### PR TITLE
refactor: Convert comments to thread safety annotations

### PR DESCRIPTION
**Pull request by maflcko**
Convert human-only-readable annotations to human-and-machine-readable annotations.

### CODE REVIEW

**Comment by practicalswift** [comment]
ACK regarding the changes, but this PR is a subset of the PR #13123 submitted back in April (with the exception of the change to `src/validation.cpp`)? :-)

Close this PR in favour of #13123?

**Comment by promag** [comment]
utACK fa71eb5.

@practicalswift like Marco said, these are the obvious annotations and your pull will be simplified after this.

**Comment by practicalswift** [comment]
utACK fa71eb5196fc157213d7b6364071530ab19df724

@promag Makes sense, but where did Marco say that? I missed it :-)

**Comment by promag** [comment]
@practicalswift updated my comment 😛

**Pull request merged**
