### PR TITLE
Doc: do update before fetching packages in WSL build guide

### PR DESCRIPTION
**Pull request by nvercamm**
Add update and upgrade commands to enable the installation of the first dependencies on ubuntu xenial. If those are not executed some packages can not be found.

### CODE REVIEW

**Comment by laanwj** [comment]
Indeed the `apt-get` can fail on a system with an old package catalog. Note that you don't strictly need the `apt-get upgrade`, just the update. But it's ok...

**Comment by randolf** [comment]
The concern I have with running the upgrade/update is that it might have an effect on other packages not related to Bitcoin.  Might it be better to instead add a note that "apt-get update" might help in the event that some dependencies are missing?

**Comment by nvercamm** [comment]
I ran into this problem when using the WSL and after doing a fresh install of Ubuntu from the Microsoft store. So I would think that everybody using this workflow will run into this problem.

I also ran into some other problems for which I haven't created a pull request yet: mainly missing packages and the installation of berkleydb 4.8. So maybe a seperate section for a freshly installed Ubuntu Xenial on WSL would be appropriate.

**Comment by laanwj** [comment]
> The concern I have with running the upgrade/update is that it might have an effect on other packages not related to Bitcoin.

I understand the concern but also note that this is always the case. When you `apt-get install` a package you get its most recent version, as well as the most recent of its dependencies, and the dependencies in turn, all the way up to base system libraries.

**Comment by laanwj** [comment]
> So maybe a seperate section for a freshly installed Ubuntu Xenial on WSL would be appropriate.

FWIW there's nothing specific to Xenial in this PR. Running `apt-get update` before installing packages makes as much sense for every Debian variant in existence.

**Comment by fanquake** [comment]
utACK e29c6c8
The Windows build instructions seem fragile at the best of times, if running apt update/upgrade is going to cause more issues that's worrying.

**Pull request merged**
