### PR TITLE
[QT] New filesave icon

### PR DESCRIPTION
**Pull request by GChuf**
The old icon is the same as "receive.png"

### CODE REVIEW

**Comment by hebasto** [comment]
@gapeman Welcome!
Screenshots "before" and "after" are appreciated in the PR description.

**Comment by emilengler** [comment]
Concept NACK because I think that the current icon does this job. Also we are using icons from [here](https://www.s-ings.com/typicons/) and I think its better to keep using these icons

**Comment by jonasschnelli** [comment]
Looks not to bad. Either we use an icon from https://www.s-ings.com/typicons/ or you would need to put an entry into `doc/assets-attribution.md` (creator, license, etc.).

However, I think your new icon would require padding to not appear overly large.

**Comment by gapeman** [comment]
I have padded the icon, and updated the copyright file. I've also noticed some mistakes in the copyright file (It's Stephen, not Stephan).
Current licence file is under /contrib/debian/copyright and I'm not sure why - surely it would be better for it to stay in doc/assets-attribution.md?

p.s. Updated copyright 2 times because I accidentally removed "< >" symbols

**Comment by Sjors** [comment]
c95ad1d looks good, but please squash the commits

Would also be good to add a screenshot of the icon in context.

**Comment by gapeman** [comment]
Closing this pull request, opening new one

**Comment by emilengler** [comment]
Ok...
Why?

**Comment by emilengler** [comment]
See #16584

**Comment by fanquake** [comment]
In future please just squash and force push to the branch, rather than opening a new PR.

**Pull request closed without merging**
