### PR TITLE
ci: Revert tsan task changes

### PR DESCRIPTION
**Pull request by maflcko**
Looks like there are still bugs in clang-15, so we need to roll back all the way to the previously used version (clang-13).

### CODE REVIEW

**Review by hebasto — APPROVED** [review]
ACK fabb6af8508a9c0d05d2e9f0006b0b1d3f38119a, I have reviewed the code and it looks OK, I agree it can be merged.

**Comment by fanquake** [comment]
Can we revert just #26759? Is there an issue with using Clang-15 with the suppression back in place?

Going forward, we should probably have better rationale for removing (already marked intermittent) suppresions, than "it works on my machine" and/or assuming it was magically fixed by some toolchain backport ([which couldn't have been the case here anyway](https://github.com/bitcoin/bitcoin/pull/26759#issuecomment-1367217851)).

We should also figure out what is different about the Cirrus env; as the suppressed issue re-appeared immediately after the merge of #26759.

**Comment by MarcoFalke** [comment]
There are two unrelated issues:

* The issue with clang-14/15 is an *internal* crash in tsan.
* The tsan false positive.

It doesn't help that both are intermittent and the false positive is not reproducible so far. (I tried with a `4.15.0-173-generic` kernel and another on `6.0.15`)

**Comment by MarcoFalke** [comment]
> We should also figure out what is different about the Cirrus env

As the issues are intermittent, my best guess would be they are easier to reproduce on cloud providers with 3rd-party load on neighbouring CPUs or neighbouring threads on the same CPU.

**Comment by MarcoFalke** [comment]
There is also a third (unrelated?) issue:


```
Remaining jobs: [interface_bitcoin_cli.py --legacy-wallet]
............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Timed out!
```

**Comment by MarcoFalke** [comment]
I made some progress reproducing on a fresh install of Ubuntu Jammy:


* Install packages and clone repos

```
apt update && apt install -y git vim htop ccache build-essential libtool autotools-dev automake pkg-config bsdmainutils python3 libevent-dev libboost-dev clang llvm libsqlite3-dev cmake ninja-build lld ( git clone https://github.com/bitcoin/bitcoin  ./bitcoin-core && cd bitcoin-core/ && ./autogen.sh ) && git clone https://github.com/llvm/llvm-project && cd ./llvm-project/
```

* Start bisect

```
git bisect start e0efedd2c33 88e66f
```

* Run tests

```
( rm -rf build/ && ccache --zero-stats && mkdir build && cd build/ && cmake -G Ninja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DLLVM_USE_LINKER=lld -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++  -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_BENCHMARKS=OFF -DLLVM_INCLUDE_TESTS=OFF -DLLVM_PARALLEL_LINK_JOBS=1 -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS='clang;compiler-rt' ../llvm/ && ninja && ccache --show-stats && git log -1 && ./bin/clang --version ) && ( cd ../bitcoin-core/ && ./configure --disable-tests --disable-bench --disable-fuzz-binary --without-bdb --with-gui=no  --with-sanitizers=thread CC=/root/llvm-project/build/bin/clang CXX=/root/llvm-project/build/bin/clang++ && rm -f /tmp/runs && make clean && make -j $(nproc)  && ( strings /root/bitcoin-core/src/bitcoind |grep llvm/llvm-proje ) && while ( TSAN_OPTIONS="suppressions=$(pwd)/test/sanitizer_suppressions/tsan:halt_on_error=1" ./test/functional/test_runner.py -j30   $(for i in $(seq 1 81); do echo 'interface_bitcoin_cli.py' ; done)    --failfast --timeout-factor=30 ) ; do echo 1 >> /tmp/runs ; done )
```

(Then figure out whether to `git bisect good` or `bad`, based on the number of successful runs or a timeout/crash of bitcoind)

**Comment by MarcoFalke** [comment]
```
llvm-project# git bisect bad
9fb8058a8079b3a9a8af0aff0f4b6898960d331f is the first bad commit
commit 9fb8058a8079b3a9a8af0aff0f4b6898960d331f
Author: Dmitry Vyukov <dvyukov@google.com>
Date:   Mon Dec 13 12:45:53 2021 +0100

    tsan: enable the new runtime
    
    This enables the new runtime (D112603) by default.
    
    Depends on D112603.
    
    Differential Revision: https://reviews.llvm.org/D115624

 compiler-rt/lib/tsan/CMakeLists.txt | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```

See https://github.com/llvm/llvm-project/commit/9fb8058a8079b3a9a8af0aff0f4b6898960d331f and the previous commit https://github.com/llvm/llvm-project/commit/b332134921b42796c6b46453eaf2affdc09e3154

**Comment by MarcoFalke** [comment]
Fix in https://github.com/llvm/llvm-project-release-prs/commit/56839a4c4292bbb4ce53b0452409d8c2ac514025

**Pull request merged**
