### PR TITLE
doc: Add link to ccache docs for more description

### PR DESCRIPTION
**Pull request by spicyzboss**
Add description link to `base_dir` option in `ccache`.

Before
image

After
image

### CODE REVIEW

**Comment by tdb3** [comment]
Concept ACK.
Seems beneficial to add clarification.

nit: In case the link to the ccache doc goes stale, perhaps also include the rationale from it directly in productivity.md:

```
You _must not_ set base_dir to "/", or anywhere that contains system headers (according to the [ccache docs](https://ccache.dev/manual/latest.html#_configuration_options)), since doing this will make ccache also rewrite paths to system header files, which typically is counterproductive.
```

**Comment by tdb3** [comment]
Rather than change the same line in two commits, it would be better to squash those commits. (See https://github.com/tdb3/toolbox/blob/main/git/commitSquashExample.md for an example). This way the commit log is cleaner.

**Comment by spicyzboss** [comment]
I guess the explanation with link seems to make docs more complete

**Review by hernanmarino — APPROVED** [review]

**Comment by fanquake** [comment]
Thanks, however I think we'll leave this as-is.

**Pull request closed without merging**
