### PR TITLE
qt: Bump BLOCK_CHAIN_SIZE to 200GB

### PR DESCRIPTION
**Pull request by laanwj**
Part of the release process for 0.16.

Value is open for discussion, my blocks/ directory is 163GB but this leaves some slack.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
ACK ba490d2460592720627621f6f25a1526bb0d045c. The value should not be outdated by the time of the next major release, so giving some air is good.

**Comment by jonasschnelli** [comment]
ACK ba490d2460592720627621f6f25a1526bb0d045c

**Comment by jnewbery** [comment]
ACK ba490d2460592720627621f6f25a1526bb0d045c. Currently ~164GB for me.

**Comment by achow101** [comment]
post-merge ACK  ba490d2

**Pull request merged**
