### PR TITLE
ci: Skip broken Wine64 tests by default

### PR DESCRIPTION
**Pull request by maflcko**
I don't think the unit tests run in Wine after the Windows cross-compilation have ever shown a true positive since the MSVC task was added. However, they are a source of frequent false-positives.

Thus, disable them by default for now. Anyone can still enable them by setting `RUN_UNIT_TESTS=true`.

A follow-up could run them on real Windows, see https://github.com/bitcoin/bitcoin/pull/31176.

Conceptually there are many other nightly tasks, which rarely find issues and are not run by default, like the valgrind or s390x tasks. So putting the Wine unit tests in the same bucket should be fine.

### CODE REVIEW

**Comment by hebasto** [comment]
I'm a bit hesitant about this change.

> Conceptually there are many other nightly tasks, which rarely find issues and are not run by default, like the valgrind or s390x tasks. So putting the Wine unit tests in the same bucket should be fine.

I disagree. Conceptually, this is a different case because the cross-compiled `test_bitcoin.exe` is part of release bundle for Windows. And leaving the repo without a CI job to run it seems like a drawback.

> A follow-up could run them on real Windows, but this comes with its own downsides, see #31176.

What downsides?

**Review by hebasto — APPROVED** [review]
ACK fa5e7064597fc51366f082e3d07a4591e576db38, to avoid false-positives.

**Review by willcl-ark — APPROVED** [review]
ACK fa5e7064597fc51366f082e3d07a4591e576db38

I agree with disabling these tests, and then pursuing a followup e.g. #31176 to run them natively on windows. There's no point in debugging false positives (and no? real positives).

**Comment by hebasto** [comment]
> Is this test-only change with two reviews rfm?
> 
> This is the most common false positive right now.

And the [replacement](https://github.com/bitcoin/bitcoin/pull/31176) is ready.

> Fixes #31071

Maybe drop it from the PR description?

**Comment by hebasto** [comment]
> ... so I think it still makes sense to merge this one in the meantime.

I did not mean to delay the merge of this PR.

**Comment by willcl-ark** [comment]
https://cirrus-ci.com/task/6357677415071744?logs=ci#L2640

**Comment by ryanofsky** [comment]
> @ryanofsky Do you think this is rfm?

Merged this now.

Am a little curious about the underlying issue though because in theory there doesn't have to be binary distinction between false positives and true positives. Test failures on a platform could indicate that be a sign that tests are fragile or poorly written even if they aren't technically buggy or reveal bugs in the code. Just clicking the cirrus links here it's hard to tell what the nature of these failures is, what may be causing them, and whether they happen reliably or randomly.

**Pull request merged**
