### PR TITLE
rpc: Reword SighashFromStr error message

### PR DESCRIPTION
**Pull request by maflcko**
Put quotes around the parameter. In theory, `std::quoted` should be used, but that seems overkill.

This should avoid error messages such as `A valid sighash parameter is not a valid sighash parameter. (code -8)`.

Also, it should fix fuzz false positives when searching for internal bugs in the `rpc` fuzz target. For example, `ZGVzY3JpcHRvcnByb2Nlc3Nwc2J0XP9ce1tdXOVJbnRlcm5hbCBidWcgZGV0ZWN0ZWQAXQ0AHfcAXQ1p7TJv`.

### CODE REVIEW

**Review by dergoegge — APPROVED** [review]
ACK fa6ab0d020d0b1492203f7eb2ccb8051812de086

**Review by brunoerg — APPROVED** [review]
utACK fa6ab0d020d0b1492203f7eb2ccb8051812de086

**Comment by fanquake** [comment]
Backported in #29888.

**Review by dasibcryptoidology — APPROVED** [review]

**Review by DCMTOKEN — COMMENTED** [review]
Please approve my request for changes

**Review by DCMTOKEN — COMMENTED** [review]
Please approve changes so I can run a test and see if there's any issues

**Comment by Amarrufo-1** [comment]
I dunno wat this means

**Pull request merged**
