### PR TITLE
doc: Correct a small typo in help / manpage

### PR DESCRIPTION
**Pull request by darosior**
Just a little typo I noticed while reading the manpage.

### CODE REVIEW

**Comment by emilengler** [comment]
ACK 2fa8dc5

**Review by kristapsk — APPROVED** [review]
utACK 2fa8dc545417ab8ff54676ff22a93674d1a54797

**Comment by practicalswift** [comment]
ACK 2fa8dc545417ab8ff54676ff22a93674d1a54797 -- also small defects should be fixed

Nice find!

**Comment by laanwj** [comment]
ACK 2fa8dc545417ab8ff54676ff22a93674d1a54797

**Pull request merged**
