### PR TITLE
Make all script validation flags backward compatible

### PR DESCRIPTION
**Pull request by sipa**
This change makes `SCRIPT_VERIFY_UPGRADABLE_NOPS` not apply to `OP_CHECKLOCKTIMEVERIFY` and `OP_CHECKSEQUENCEVERIFY`. This is a no-op as `UPGRADABLE_NOPS` is only set for mempool transactions, and those always have `SCRIPT_VERIFY_CHECKLOCKTIMEVERIFY` and `SCRIPT_VERIFY_CHECKSEQUENCEVERIFY` set as well. The advantage is that setting more flags now always results in a reduction in acceptable scripts (=softfork).

This results in a nice and testable property for validation, for which a new test is added.

This also means that the introduction of a new definition for a NOP or witness version will likely need the following procedure (example OP_NOP8 here)
* Remove OP_NOP8 from being affected by `SCRIPT_VERIFY_DISCOURAGE_UPGRADABLE_NOPS`.
* Add a `SCRIPT_VERIFY_DISCOURAGE_NOP8`, which only applies to `OP_NOP8`.
* Add a `SCRIPT_VERIFY_NOP8` which implements the new consensus logic.
* Before activation, add `SCRIPT_VERIFY_DISCOURAGE_NOP8` to the mempool flags.
* After activation, add `SCRIPT_VERIFY_NOP8` to both the mempool and consensus flags.

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
Can you rebase this on top of the now-merged #10192 to remove the extra checks in its test? Concept ACK.

**Comment by sipa** [comment]
Done.

**Comment by TheBlueMatt** [comment]
utACK 01013f5d2fbe3fa86565c927bf7bb8ec0f525073 I did check some of the test changes failed appropriately, but wouldnt really call it a tested ACK per se.

**Review by jl2012 — APPROVED** [review]
utACK 01013f5

**Comment by laanwj** [comment]
utACK 2851b77312b55c8868acd4cd2c118e5a034606b7, reviewed both test and interpreter changes, they seem clear and contained and could discover no issues with the changed logic.

**Pull request merged**
