### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by antonio-fr**
fix typo in comment

### CODE REVIEW

**Comment by Diapolo** [comment]
Should go to https://github.com/theuni/bitcoin/tree/trivial-next

**Comment by dcousens** [comment]
@Diapolo same question as in https://github.com/bitcoin/bitcoin/pull/6544

**Comment by laanwj** [comment]
Yes, thanks for the fix, but please file his to the trivial branch, it doesn't get more trivial than this :)

**Comment by antonio-fr** [comment]
OK, done.
Pull request #50, in theuni/bitcoin branch trivial-next.

**Comment by dcousens** [comment]
@laanwj I understand the reason to use @theuni's trivial repository is to decrease noise here.  But,  how much noise will it reduce really versus just a merge here?
Or is it purely *merge* noise that we looking to resolve with trivial?

**Comment by laanwj** [comment]
@dcousens it's about pull request noise, about delegation. Reducing merge noise (by grouping related commits) is a nice side effect.

**Comment by laanwj** [comment]
Closing the pull here, thanks for moving it.

**Pull request closed without merging**
