### PR TITLE
ci: Fuzz with integer sanitizer

### PR DESCRIPTION
**Pull request by maflcko**
Otherwise the suppressions file will go out of sync

### CODE REVIEW

**Comment by practicalswift** [comment]
Super Strong Concept ACK :)

In cases where we want to rely on implicit sign changes, implicit truncations, etc we can explicitly opt-in to them on a per file or per function basis via suppressions.

**Comment by MarcoFalke** [comment]
Times out

**Comment by practicalswift** [comment]
@MarcoFalke In order to process the `qa-assets` inputs with `-fsanitize=integer` without timeouts I usually prune all excessively large inputs we have by using `find qa-assets/fuzz_seed_corpus/ -type f -size +4k -delete` (where `4k` can be tuned). See https://github.com/bitcoin-core/qa-assets/issues/25#issuecomment-767731480.

**Comment by MarcoFalke** [comment]
ci passed in 1h30min

**Comment by practicalswift** [comment]
cr ACK faff3991a9be0ea7be31685fb46d94c212c5da34: patch looks correct

**Pull request merged**
