### PR TITLE
Bugfix: gitian: Add curl to packages (now needed for depends)

### PR DESCRIPTION
**Pull request by luke-jr**

### CODE REVIEW

**Comment by MarcoFalke** [comment]
utACK

**Comment by jonasschnelli** [comment]
Maybe squash?
utACK.

**Comment by laanwj** [comment]
utACK e5daa2e

**Comment by jonasschnelli** [comment]
Tested ACK https://github.com/bitcoin/bitcoin/commit/e5daa2e2aef61f0b9441d19f0b67015f426c6056 (https://bitcoin.jonasschnelli.ch/pulls/7614/).

**Comment by theuni** [comment]
ut ACK.

**Comment by MarcoFalke** [comment]
This was backported in 7815cb6 (0.11) and ca8f160 (0.12) and 4e1134b (0.10). Removing label "needs backport"

**Pull request merged**
