### PR TITLE
contrib: Remove duplicate packages from gitian-linux.yml

### PR DESCRIPTION
**Pull request by maflcko**
https://packages.ubuntu.com/bionic/g++-aarch64-linux-gnu already depends on `g++-7-aarch64-linux-gnu` and `gcc-7-aarch64-linux-gnu`, so I don't see a reason to list them explicitly again.

Same for `g++-arm-linux-gnueabihf` and `g++-multilib`

### CODE REVIEW

**Comment by MarcoFalke** [comment]
This should clear some confusing about why a version is explicitly mentioned (see #13702  by @Sjors)

**Comment by laanwj** [comment]
Concept ACK

**Comment by ken2812221** [comment]
DrahtBot does not show linux build result, so the gitian build for linux fail?

**Comment by MarcoFalke** [comment]
Closing due to https://bugs.launchpad.net/ubuntu/+source/gcc-defaults-arm64-cross/+bug/1347820

**Pull request closed without merging**
