### PR TITLE
Add DERSIG transaction test cases

### PR DESCRIPTION
**Pull request by rnicoll**
Add test cases for DERSIG flag enforcement against transactions. Builds on existing script tests, by adding corresponding transaction coverage.

### CODE REVIEW

**Comment by laanwj** [comment]
ACK

**Comment by TheBlueMatt** [comment]
utACK

**Comment by MarcoFalke** [comment]
concept ACK

**Comment by btcdrak** [comment]
ACK

**Comment by dcousens** [comment]
ACK

**Comment by afk11** [comment]
ACK.

**Pull request merged**
