### PR TITLE
Scripts and tools: increased timeout downloading

### PR DESCRIPTION
**Pull request by cisba**
DOWNLOAD_CONNECT_TIMEOUT changed from 10 to 30 because some file start only after 15 sec (see below).
```
Fetching boost_1_64_0.tar.bz2 from https://dl.bintray.com/boostorg/release/1.64.0/source/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:15 --:--:--     0
100 76.7M  100 76.7M    0     0  1863k      0  0:00:42  0:00:42 --:--:-- 8136k
/home/gitianuser/bitcoin/depends/work/download/boost-1_64_0/boost_1_64_0.tar.bz2.temp: OK
```

### CODE REVIEW

**Comment by ken2812221** [comment]
If it failed to download the file, you could retry it again. That's just a temporary connection issue.

**Comment by cisba** [comment]
@ken2812221, I have this issue systematically with that source (dl.bintray.com). 
No problems with others. I think is network related, but could affect also other people.
We cannot assume that everybody in the world has the best network connection...
For this reason I suggest to increase the timeout value.

**Comment by practicalswift** [comment]
utACK e7a72455fa4d5c5b1a37ceae1ec557354b3009c2

No harm in bumping the timeout a bit :-)

**Comment by jamesob** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/14184/commits/e7a72455fa4d5c5b1a37ceae1ec557354b3009c2

**Pull request merged**
