### PR TITLE
util: Add Join helper to join a list of strings

### PR DESCRIPTION
**Pull request by maflcko**
We have a lot of enumerations in the code and sometimes those enumerations need to be mentioned in the RPC or command line documentation. Previously, each caller would have a couple of lines inline to join the strings or the joined string is hardcoded in the documentation. A helper to join strings would make code such as https://github.com/bitcoin/bitcoin/pull/16629#discussion_r315852446 less verbose and easier to read.

Also, warnings commonly accumulate in complex RPCs, since a warning doesn't lead to an early return. A helper to join those warnings would make code such as https://github.com/bitcoin/bitcoin/pull/16394/files#r309324997 less verbose and easier to read.

### CODE REVIEW

**Comment by practicalswift** [comment]
ACK fa09713060ced21905108161d53e6de79f104649

Perhaps put this handy function in real-world use outside of the tests as part of this PR?

Could these be candidates?

https://github.com/bitcoin/bitcoin/blob/70b12af87eb036623f5dd1f3a519efe6c156570d/src/rpc/util.cpp#L648-L652

https://github.com/bitcoin/bitcoin/blob/70b12af87eb036623f5dd1f3a519efe6c156570d/src/script/script.cpp#L256-L261

**Comment by MarcoFalke** [comment]
> Perhaps put this handy function in real-world use outside of the tests as part of this PR?

Done. (Now used in `rpc/util`. I checked that all generated rpc helps are identical before and after this change)

**Comment by practicalswift** [comment]
Very nice!

ACK faebf6271467048dc8a9a0c526a0f8565023a966

**Comment by sipa** [comment]
I think you can also use `std::accumulate(list.begin(), list.end(), "")`; it's also a lot more generic.

**Comment by MarcoFalke** [comment]
> I think you can also use std::accumulate(list.begin(), list.end(), ""); it's also a lot more generic.

It seems less generic, since it does not accept a separator, nor a unary operator.

**Comment by emilengler** [comment]
Concept ACK

**Comment by NicolasDorier** [comment]
@sipa accumulate is not recommended https://stackoverflow.com/questions/15347123/how-to-construct-a-stdstring-from-a-stdvectorstring/18703743

```
Don't use std::accumulate for string concatenation, it is a classic Schlemiel the Painter's algorithm, even worse than the usual example using strcat in C. Without C++11 move semantics, it incurs two unnecessary copies of the accumulator for each element of the vector. Even with move semantics, it still incurs one unnecessary copy of the accumulator for each element.

The three examples above are O(n).

std::accumulate is O(n²) for strings.
```

**Comment by hebasto** [comment]
@MarcoFalke 
On Linux I can compile, link, and pass unit tests without `util/string.cpp`.
Has this source file any special mission?

**Comment by MarcoFalke** [comment]
No, it has no meaning. Just a placeholder when someone wants to add stuff. For example the things in `strencodings` that have nothing to do with encoding/decoding strings can be moved here. Not saying that should be done now, but it can be done in the future.

**Pull request merged**
