### PR TITLE
chainparams: Remove seed.bitcoinstats.com

### LINKED ISSUE #29911: DNS seed "seed.bitcoinstats.com" doesn't support filtering while the comments says it does
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

It's stated in `chainparams.cpp` that "seed.bitcoinstats.com" supports filtering. However, this isn't true.

https://github.com/bitcoin/bitcoin/blob/c05c214f2e9cfd6070a3c7680bfa09358fd9d97a/src/kernel/chainparams.cpp#L137

### Expected behaviour

Since "seed.bitcoinstats.com" supports filtering for `NODE_NETWORK`, when asked for `NODE_NETWORK`, it should return archival nodes. It doesn't.

### Steps to reproduce

`dig x1.seed.bitcoinstats.com`.

```
[I] calvin@bitcoin ~> dig x1.seed.bitcoinstats.com

; <<>> DiG 9.18.21 <<>> x1.seed.bitcoinstats.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 60119
;; flags: qr rd ra; QUERY: 1, ANSWER: 25, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;x1.seed.bitcoinstats.com.      IN      A

;; ANSWER SECTION:
x1.seed.bitcoinstats.com. 60    IN      A       13.112.109.34
x1.seed.bitcoinstats.com. 60    IN      A       3.211.51.136
x1.seed.bitcoinstats.com. 60    IN      A       3.8.38.104
x1.seed.bitcoinstats.com. 60    IN      A       64.227.26.97
x1.seed.bitcoinstats.com. 60    IN      A       69.55.55.188
x1.seed.bitcoinstats.com. 60    IN      A       34.241.94.237
x1.seed.bitcoinstats.com. 60    IN      A       3.124.65.19
x1.seed.bitcoinstats.com. 60    IN      A       3.81.243.143
x1.seed.bitcoinstats.com. 60    IN      A       51.195.28.51
x1.seed.bitcoinstats.com. 60    IN      A       46.137.123.109
x1.seed.bitcoinstats.com. 60    IN      A       138.68.173.152
x1.seed.bitcoinstats.com. 60    IN      A       69.4.94.226
x1.seed.bitcoinstats.com. 60    IN      A       142.93.200.9
x1.seed.bitcoinstats.com. 60    IN      A       54.68.82.186
x1.seed.bitcoinstats.com. 60    IN      A       18.202.91.9
x1.seed.bitcoinstats.com. 60    IN      A       52.30.154.84
x1.seed.bitcoinstats.com. 60    IN      A       116.203.99.217
x1.seed.bitcoinstats.com. 60    IN      A       13.112.109.34
x1.seed.bitcoinstats.com. 60    IN      A       3.211.51.136
x1.seed.bitcoinstats.com. 60    IN      A       3.8.38.104
x1.seed.bitcoinstats.com. 60    IN      A       64.227.26.97
x1.seed.bitcoinstats.com. 60    IN      A       69.55.55.188
x1.seed.bitcoinstats.com. 60    IN      A       34.241.94.237
x1.seed.bitcoinstats.com. 60    IN      A       3.124.65.19
x1.seed.bitcoinstats.com. 60    IN      A       3.81.243.143

;; Query time: 312 msec
;; SERVER: 1.1.1.1#53(1.1.1.1) (UDP)
;; WHEN: Fri Apr 19 19:35:56 KST 2024
;; MSG SIZE  rcvd: 453
```

Of the returned addresses, these address do not support `NODE_NETWORK`
```
13.112.109.34
3.8.38.104
64.227.26.97
69.55.55.188
34.241.94.237
142.93.200.9
18.202.91.9
52.30.154.84
116.203.99.217
13.112.109.34
64.227.26.97
69.55.55.188
34.241.94.237
```

One can easily check bitnodes data: https://bitnodes.io/nodes/3.8.38.104-8333/

A handful of the nodes here were also unreachable at the time of this writing.

### Relevant log output

_No response_

### How did you obtain Bitcoin Core

Pre-built binaries

### What version of Bitcoin Core are you using?

v23.0.0 but this doesn't matter here

### Operating system and version

Also doesn't matter

### Machine specifications

I don't think this matters for this issue

### PR DESCRIPTION
**Pull request by achow101**
This seeder no longer appears to be serving sufficient addresses.

Fixes #29911

### CODE REVIEW

**Review by 1440000bytes — APPROVED** [review]
ACK https://github.com/bitcoin/bitcoin/pull/30720/commits/c88a7dc53e3be7489605c3326cf768df5437393a

Not sure if this should be added in release notes.

**Review by virtu — APPROVED** [review]

**Review by virtu — COMMENTED** [review]
ACK https://github.com/bitcoin/bitcoin/commit/c88a7dc53e3be7489605c3326cf768df5437393a

**Review by mzumsande — COMMENTED** [review]
ACK c88a7dc53e3be7489605c3326cf768df5437393a

It can be re-added when it's fixed.

**Comment by glozow** [comment]
lgtm looking at discussion on #29911

cc @cdecker

**Comment by cdecker** [comment]
I'm in the process of fixing the seeder. It should be back online by the end of the week, if that's acceptable

**Review by BrandonOdiwuor — APPROVED** [review]
ACK c88a7dc53e3be7489605c3326cf768df5437393a

**Comment by fanquake** [comment]
> I'm in the process of fixing the seeder. It should be back online by the end of the week, if that's acceptable

No worries. We can revert this once it's back up, and we can see it working correctly.

**Comment by cdecker** [comment]
Great, I'm just testing it as we speak, and I'll open a new PR adding it, once its shown to work, if that's ok.

**Comment by vasild** [comment]
> Great, I'm just testing it as we speak, and I'll open a new PR adding it, once its shown to work, if that's ok.

wen pr?

**Pull request merged**
