### PR TITLE
[Qt] add bitcoin logo to about screen

### PR DESCRIPTION
**Pull request by jonasschnelli**

### CODE REVIEW

**Comment by fanquake** [comment]
Screenshot
screen shot

**Comment by jonasschnelli** [comment]
Now it should be Qt4 compatible.

Screen before and after:
bildschirmfoto 2015-02-04 um 20 32 31

bildschirmfoto 2015-02-04 um 20 34 19

**Comment by jonasschnelli** [comment]
Linux:

Before
bildschirmfoto 2015-02-04 um 20 46 24

After:
bildschirmfoto 2015-02-04 um 21 00 28

**Comment by paveljanik** [comment]
ACK
minor NIT: on testnet/regtest, the color is not as we are used to :-)

**Comment by jonasschnelli** [comment]
@paveljanik Yes. This is a feature ... *cough slightly*.
Having a blue/green icon in testnet/regtest mode is fine IMO.

**Comment by paveljanik** [comment]
BTW - I was talking about the color of the new added icon on the About window... I like the color of the intro image (both green and blue one!). Would like to see the same color in the About window as well :-)
But you can safely ignore this :-)

**Comment by jonasschnelli** [comment]
@paveljanik Yes. I know what you meant with that. I was just *cough slightly* because i was aware of this inconsistence. It would certainly be fixable somehow. But the color of the icon gets rewritten and cached at the very beginning of the qt app cycle.
I think it's not worth the effort because the green/blue icon will probably only popups on devs screens.

**Comment by paveljanik** [comment]
Agreed, sure.

**Comment by fanquake** [comment]
Tested ACK

**Comment by L-Cranston-Shadow** [comment]
First time commenting on a project so I hope I'm doing this correctly and I apologize if this is a stupid question, but is there any effect vis a vis resizing the window with the new image?

**Comment by jonasschnelli** [comment]
@L-Cranston-Shadow First github comment. Nice. Thanks for your participation.
The resize behavior is still the same.
You can still resize the window to a very small size (see below).
In the current (0.9.3) and upcoming version 0.10 there is also a image on the about screen which follows the same resize constraints.

Feel free to test it by building bitcoin master yourself of use a prebuilt binary (https://builds.jonasschnelli.ch/pulls/5753/).

bildschirmfoto 2015-02-07 um 13 07 26

**Pull request merged**
