### PR TITLE
Hardcoded seeds update pre-0.17 branch

### PR DESCRIPTION
**Pull request by laanwj**
As per release process and https://github.com/bitcoin/bitcoin/blob/master/contrib/seeds/README.md

### CODE REVIEW

**Comment by MarcoFalke** [comment]
utACK 825fb02ef1c716f930bc7c40a6acda5eaff2c40f (Did the same steps and confirmed that my result has a smaller diff against 825fb02ef1c716f930bc7c40a6acda5eaff2c40f, than against current master)

**Comment by MarcoFalke** [comment]
nit: Could add a commit to fix `GetDesireableServiceFlags` -> `GetDesirableServiceFlags`, since that is used in the code. Proposed diff:

```diff
diff --git a/contrib/seeds/README.md b/contrib/seeds/README.md
index 6dc277f298..502c20d0d6 100644
--- a/contrib/seeds/README.md
+++ b/contrib/seeds/README.md
@@ -4,7 +4,7 @@ Utility to generate the seeds.txt list that is compiled into the client
 (see [src/chainparamsseeds.h](/src/chainparamsseeds.h) and other utilities in [contrib/seeds](/contrib/seeds)).
 
 Be sure to update `PATTERN_AGENT` in `makeseeds.py` to include the current version,
-and remove old versions as necessary (at a minimum when GetDesireableServiceFlags
+and remove old versions as necessary (at a minimum when GetDesirableServiceFlags
 changes its default return value, as those are the services which seeds are added
 to addrman with).

**Comment by laanwj** [comment]
Thanks, added

**Comment by MarcoFalke** [comment]
re-ACK 176aa5aa1d944113161b99cf6c09b7dd3a5c684e

**Pull request merged**
