### PR TITLE
Remove unused code from wallet and validation interface

### LINKED ISSUE #6109: Remove unused CWallet::EraseFromWallet
`CWallet::EraseFromWallet` and `CValidationInterface::EraseFromWallet` are not used. Moreover, CValidationInterface is not supposed to "know" what a wallet is.

### PR DESCRIPTION
**Pull request by fanquake**
Fixes #6109

### CODE REVIEW

**Comment by jonasschnelli** [comment]
code-review ACK.
I think we don't need that code part (`EraseTransaction`) in near future. Removing makes sense.

**Comment by laanwj** [comment]
Not convinced about this. I do think we want to be able to remove unconfirmed, or conflicting transactions at some point (e.g. when implementing replace-by-fee, or other cases where the transaction is to time out after a while if it doesn't make it into a block).

**Comment by luke-jr** [comment]
@laanwj I don't see a case where deleting or hiding a still-valid transaction is a good idea. And the only way it can become invalid is if a conflicting one is confirmed; even in that case, I don't think we want erase semantics. IMO the signal should go. The wallet may conceivably want to erase a transaction it is respending itself, especially once the respend has confirmed, so I agree the CWallet method should stay for now.

**Comment by laanwj** [comment]
@luke-jr True, in the case I mentioned it will be the wallet itself deciding to remove the transaction, not the node logic.

**Pull request merged**
