### PR TITLE
test: Return dict in MiniWallet::send_to

### PR DESCRIPTION
**Pull request by maflcko**
Returning a tuple has many issues:

* If only one value is needed, it can not be indexed by name
* If another value is added to the return value, all call sites need to be updated

Bite the bullet now and update all call sites to fix the above issues.

### CODE REVIEW

**Comment by theStack** [comment]
Concept ACK

**Review by brunoerg — APPROVED** [review]
crACK faf4315c88d8c81c2ff84870bc81aef3cf719816

**Review by stickies-v — COMMENTED** [review]
Concept ACK for moving away from a tuple return value. I think I'd prefer something more struct-like though, for example a `typing.NamedTuple`? Also, I don't see the point in returning `tx`, `wtxid`, and `hex` if no one is accessing them yet - can easily be added later on when needed?

**Review by theStack — APPROVED** [review]
Code-review ACK faf4315c88d8c81c2ff84870bc81aef3cf719816

**Comment by fanquake** [comment]
@stickies-v want to take a final look?

**Review by stickies-v — APPROVED** [review]
Code review ACK faf4315c88d8c81c2ff84870bc81aef3cf719816

I'd have preferred doing things a bit differently but I think as per the PRs rationale, it's better to move away from the tuple return type quickly to avoid larger refactorings in the future. My comments can easily be implemented in follow-ups, if people want them.

---

> The idea is to use the same return type as the other MiniWallet methods.

Fair enough, I hadn't considered that.

> If you want compile-time type checks <...>

My main concern is readability and usability, being explicit about the structure of the dict is helpful to users imo and integrates well with IDEs. I still prefer using e.g. a namedtuple but that can be a follow-up (I don't think I feel strongly enough about it to open that PR myself, at least for now) that updates all relevant functions at the same time instead of doing it just for this one.

> The idea was to use the same return values as the other MiniWallet methods, but I am happy to drop this.

If it were up to me I'd just have it return ["tx", "sent_vout"] since all 3 other fields can easily be accessed through "tx", but I see your rationale your rationale and I think it's reasonable.

**Pull request merged**
