### PR TITLE
contrib: Fix check-doc script regexes

### PR DESCRIPTION
**Pull request by maflcko**
Fixup the regexes to properly find all used args. The regex should now match all of the getter and setter methods of the `ArgsManager`. See https://dev.visucore.com/bitcoin/doxygen/class_args_manager.html#pub-methods

Before:
```
Args used        : 159
Args documented  : 188
Args undocumented: 0
Args unknown     : 29
```

After:
```
Args used        : 183
Args documented  : 188
Args undocumented: 0
Args unknown     : 5
```

### CODE REVIEW

**Comment by MarcoFalke** [comment]
You can disable the whitespace changes for review (e.g. on GitHub web view with https://github.com/bitcoin/bitcoin/pull/12820/commits/74f8902e816cdf6d380a775d0b320ef9bd7f557b?w=1)

**Comment by jnewbery** [comment]
Tested ACK 136084470cd7920b94e016621ebf682996247162

Looks like it works. We can remove the help text for the non-existent `-fuzzmessagestest` (removed in ea3326891d8c3dcbcff178b618108d657c5586a3)

**Comment by jnewbery** [comment]
Oh, I wasn't suggesting we needed to do it here, but sure why not. Tested ACK 0c17e27630ada2d9284e357cc0e92ffff8775423

**Comment by ajtowns** [comment]
Seems pretty reasonable. utACK 0c17e27630ada2d9284e357cc0e92ffff8775423

**Pull request merged**
