### PR TITLE
Optimize memory usage of CNode::setAddrKnown

### PR DESCRIPTION
**Pull request by gavinandresen**
The first pull implements a "rolling bloom filter" class that keeps track of at least the last N elements added (but has a false positive rate when queried whether an element has been added).

The second uses that class to optimize the memory usage of CNode::setAddrKnown, to a fixed 37K of memory per CNode (from about 650K before any changes, or ~300K after @sipa 's #6064 ).

### CODE REVIEW

**Comment by sipa** [comment]
Concept ACK.

**Comment by gavinandresen** [comment]
Changed the first commit to pick @sipa 's nit  (replace array of 2 pointers to bloom filters with plain-old private members that are initialized in the constructor; less code is better).

**Comment by sipa** [comment]
Tested ACK

**Comment by laanwj** [comment]
Concept ACK

**Comment by laanwj** [comment]
Closing as #6064 includes this

**Pull request closed without merging**
