### PR TITLE
0.19: Backports

### PR DESCRIPTION
**Pull request by promag**
Backports
 - #16963
 - #17445
 - #17258
 - #17621
 - #17924
 - #17634

### CODE REVIEW

**Comment by promag** [comment]
I can also include #17621 once it gets more reviews or gets merged.

**Comment by fanquake** [comment]
In general I'd prefer if backport PRs weren't opened until the changes they contain are actually all merged into master (I realise there are other similar backport PRs open now, and might close them). 

Just because a PR has had some review or has an ACK, doesn't mean it wont need additional changes before merge; and having backport PRs open before then just guarantees more changes/noise etc.

**Comment by fanquake** [comment]
Going to reopen this when the PRs it's backporting have been merged.

**Comment by fanquake** [comment]
> I can also include #17621 once it gets more reviews or gets merged.

Can you include #17621 and #17258 here.

**Comment by promag** [comment]
@fanquake done.

**Comment by fanquake** [comment]
@instagibbs @adamjonas Can you check the relevant backports here.

**Comment by promag** [comment]
@instagibbs note that I had to change a bit because #17300 is not in 0.19 branch.

**Comment by adamjonas** [comment]
88729d804e39fbb42aa92c039afe3641edf9190c looks good

**Comment by instagibbs** [comment]
https://github.com/bitcoin/bitcoin/pull/17792/commits/a5489c9892fc12cb70c6c7b017881a9218d0b041 looks right

**Comment by promag** [comment]
@instagibbs any idea why wallet_avoidreuse.py fails?

**Comment by instagibbs** [comment]
investigating

**Comment by instagibbs** [comment]
@promag unfortunately the original PR introduced a regression that makes it worse for this branch: https://github.com/bitcoin/bitcoin/pull/17924

**Comment by promag** [comment]
@instagibbs included #17924.

**Comment by promag** [comment]
@hebasto included #17634, please take a look.

**Comment by fanquake** [comment]
@promag #17924 has been merged. Can you re-check your backport here.

**Comment by promag** [comment]
@fanquake updated OP, backport is still up to date.

**Comment by laanwj** [comment]
ACK cd67b1dcb8f1eca8c0c7cecc6f4de27c7efe41d5, checked that I got more or less the same result backporting these commits

**Pull request merged**
