### PR TITLE
Acquire lock to check for genesis block.

### PR DESCRIPTION
**Pull request by pstratem**
Fix issue identified in #7917 around failure to acquire cs_main for chainActive access.

### CODE REVIEW

**Comment by sipa** [comment]
utACK

I think it can be written slightly shorter with a reverse lock around the sleep.

**Comment by pstratem** [comment]
@sipa as in acquire the lock and then release it while sleeping and re-aquire after?

**Comment by gmaxwell** [comment]
utACK 46b0c3b688dccf6ba9ac08cbd6d6981249a73b1a

This loses a log entry, but the log entry appears useless...

**Comment by dcousens** [comment]
utACK 46b0c3b,  but it'd probably be nicer to use `std::condition_variable` signals/semaphores for things like this instead of loops and `MilliSleep(10);`.

**Comment by kazcw** [comment]
The loop is emulating a condvar here (specifically `csBestBlock`), but I don't see a good way to deal with `fDisconnect` in a cond-wait that isn't quite a bit more involved than fixing this little data race. If init ran in a boost thread it'd be interruptible, but nothing in `AppInit2` expects to be exitable via interruption exceptions... utACK 46b0c3b; I'll open a separate bug relating to `fDisconnect`

**Comment by pstratem** [comment]
@kazcw agreed this is not ideal... nothing about init.cpp is ideal

**Comment by TheBlueMatt** [comment]
utACK 46b0c3b688dccf6ba9ac08cbd6d6981249a73b1a

**Comment by arowser** [comment]
Can one of the admins verify this patch?

**Pull request merged**
