### PR TITLE
Include bitcoin-tx binary on Debian/Ubuntu

### PR DESCRIPTION
**Pull request by zw**
Currently left out of Matt's PPA.  Debian's package for unstable already has it.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
utACK

**Comment by luke-jr** [comment]
This should be a separate package.

**Comment by zw** [comment]
@luke-jr I've no strong feelings; I'm sure I've come across both single-binary packages and lump-it-in-with-the-oft-unused-daemon packages in Debian.  Seems like a distro decision to me, but consistency over where to find what binary seems a good idea, however it's achieved.

This does highlight the slightly silly situation of Debian's debianisation living with them (neither clearly following git nor pushing stuff like this to git), and the PPA's debianisation living here.  Would be nice to change things in just one place.

**Comment by laanwj** [comment]
No strong feelings on this, although @luke-jr does have a point. `bitcoin-tx` is an utility that depends on neither the server nor the RPC client.

**Comment by jgarzik** [comment]
ACK

**Comment by zw** [comment]
Filed a [bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=797683) with Debian's maintainers, making a case for splitting it out like Gentoo does.  Let's see what they say.

**Comment by jgarzik** [comment]
For the moment, the pull request is obviously better than not shipping the tool at all.

It is better to merge this, and then update if the new pkg route is chosen.

**Comment by dcousens** [comment]
ACK, merge unless a new package is created.

**Comment by zw** [comment]
No reply on the bug but I can't really see Debian folks disagreeing, so the updated version puts bitcoin-tx in its own single-binary package.  @TheBlueMatt might want to comment and/or add a changelog entry, if only so that the resulting package version is bumped to 0.11 - there are Ubuntu-specific suffixes in there so I'm not sure I should touch it.

**Comment by TheBlueMatt** [comment]
utACK as it is now. I would prefer you not touch the changelog (I need to push an update that syncs it with the latest version used against the Ubuntu repo first, so unless you want to do that, just leave it).

**Pull request merged**
