### PR TITLE
depends: remove Qt networking features

### PR DESCRIPTION
**Pull request by fanquake**
Somewhat of a followup to removing BIP70 support in #17165. This removes networking features from our Qt build. This also removes the need to link against the `CFNetwork` and `SystemConfiguration` libraries on macOS.

```diff
src/qt/bitcoin-qt:
 /usr/lib/libSystem.B.dylib 
 /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit 
 /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation 
 /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices 
 /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit 
 /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices 
 /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation 
-/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration 
 /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics 
 /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon 
 /usr/lib/libc++.1.dylib 
-/System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork 
 /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText 
 /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO 
 /usr/lib/libobjc.A.dylib 
```

> Introduced the -optimized-tools option; supersedes -optimized-qmake.

`optimized-qmake` became `optimized-tools` in Qt 5.6.0. While the former still works, we can use the newer flag.

A diff of the removed symbols is available [here](https://gist.github.com/fanquake/9c8d5961c91f90a2966191367adfb391).

We still need to actually build the network module, because we are using `QLocalServer` & `QLocalSocket` in the payment server.

### CODE REVIEW

**Comment by laanwj** [comment]
Concept ACK

> We still need to actually build the network module, because we are using QLocalServer & QLocalSocket in the payment server.

Yes,, this is the only cross-platform IPC mechanism that Qt has, afaik.

**Comment by Sjors** [comment]
Concept ACK

Tested 58f9f23 on macOS 10.15.2, was able to create a DMG and BIP20 URLs can still be opened.

**Comment by fanquake** [comment]
Annoyingly, the Windows build blows up without `networkinterface`. Looking for a workaround.

**Comment by fanquake** [comment]
This is now ready for review. I've fixed the Windows build by reinstating the `networkinterface` feature.

**Comment by Sjors** [comment]
Tested ACK 3569e0e4bc549672aa3d4eeb5d309619355574d1 on macOS 10.15.2. I would like to see this tested on Windows and work on a repaired AppVeyor though.

**Comment by fanquake** [comment]
> work on a repaired AppVeyor though.

Rebased on master for Appveyor.

**Comment by MarcoFalke** [comment]
Gitian:

```
socket/qnativesocketengine_win.cpp: At global scope:
socket/qnativesocketengine_win.cpp:928:45: error: ‘QNetworkInterface’ does not name a type; did you mean ‘QMetaTypeInterface’?
                                       const QNetworkInterface &iface)
                                             ^~~~~~~~~~~~~~~~~
                                             QMetaTypeInterface
socket/qnativesocketengine_win.cpp: In function ‘bool multicastMembershipHelper(QNativeSocketEnginePrivate*, int, int, const QHostAddress&, const int&)’:
socket/qnativesocketengine_win.cpp:946:40: error: request for member ‘index’ in ‘iface’, which is of non-class type ‘const int’
         mreq6.ipv6mr_interface = iface.index();
                                        ^~~~~
socket/qnativesocketengine_win.cpp:957:19: error: request for member ‘isValid’ in ‘iface’, which is of non-class type ‘const int’
         if (iface.isValid()) {
                   ^~~~~~~
socket/qnativesocketengine_win.cpp:958:25: error: ‘QNetworkAddressEntry’ was not declared in this scope
             const QList<QNetworkAddressEntry> addressEntries = iface.addressEntries();
                         ^~~~~~~~~~~~~~~~~~~~
socket/qnativesocketengine_win.cpp:958:25: note: suggested alternative: ‘InitNetworkAddressControl’
             const QList<QNetworkAddressEntry> addressEntries = iface.addressEntries();
                         ^~~~~~~~~~~~~~~~~~~~
                         InitNetworkAddressControl
socket/qnativesocketengine_win.cpp:958:45: error: template argument 1 is invalid
             const QList<QNetworkAddressEntry> addressEntries = iface.addressEntries();
                                             ^
socket/qnativesocketengine_win.cpp:958:70: error: request for member ‘addressEntries’ in ‘iface’, which is of non-class type ‘const int’
             const QList<QNetworkAddressEntry> addressEntries = iface.addressEntries();
                                                                      ^~~~~~~~~~~~~~
socket/qnativesocketengine_win.cpp:960:24: error: ‘QNetworkAddressEntry’ does not name a type; did you mean ‘InitNetworkAddressControl’?
             for (const QNetworkAddressEntry &entry : addressEntries) {
                        ^~~~~~~~~~~~~~~~~~~~
                        InitNetworkAddressControl
socket/qnativesocketengine_win.cpp:968:13: error: expected ‘;’ before ‘if’
             if (!found) {
             ^~
socket/qnativesocketengine_win.cpp:968:13: error: expected primary-expression before ‘if’
socket/qnativesocketengine_win.cpp:968:13: error: expected ‘;’ before ‘if’
socket/qnativesocketengine_win.cpp:968:13: error: expected primary-expression before ‘if’
socket/qnativesocketengine_win.cpp:968:13: error: expected ‘)’ before ‘if’
socket/qnativesocketengine_win.cpp:958:47: warning: unused variable ‘addressEntries’ [-Wunused-variable]
             const QList<QNetworkAddressEntry> addressEntries = iface.addressEntries();
                                               ^~~~~~~~~~~~~~
socket/qnativesocketengine_win.cpp: At global scope:
socket/qnativesocketengine_win.cpp:993:65: error: ‘QNetworkInterface’ does not name a type; did you mean ‘QMetaTypeInterface’?
                                                           const QNetworkInterface &iface)
                                                                 ^~~~~~~~~~~~~~~~~
                                                                 QMetaTypeInterface
socket/qnativesocketengine_win.cpp:993:89: error: no ‘bool QNativeSocketEnginePrivate::nativeJoinMulticastGroup(const QHostAddress&, const int&)’ member function declared in class ‘QNativeSocketEnginePrivate’
                                                           const QNetworkInterface &iface)
                                                                                         ^
socket/qnativesocketengine_win.cpp:1003:66: error: ‘QNetworkInterface’ does not name a type; did you mean ‘QMetaTypeInterface’?
                                                            const QNetworkInterface &iface)
                                                                  ^~~~~~~~~~~~~~~~~
                                                                  QMetaTypeInterface
socket/qnativesocketengine_win.cpp:1003:90: error: no ‘bool QNativeSocketEnginePrivate::nativeLeaveMulticastGroup(const QHostAddress&, const int&)’ member function declared in class ‘QNativeSocketEnginePrivate’
                                                            const QNetworkInterface &iface)
                                                                                          ^
socket/qnativesocketengine_win.cpp:1012:1: error: ‘QNetworkInterface’ does not name a type; did you mean ‘QMetaTypeInterface’?
 QNetworkInterface QNativeSocketEnginePrivate::nativeMulticastInterface() const
 ^~~~~~~~~~~~~~~~~
 QMetaTypeInterface
socket/qnativesocketengine_win.cpp:1045:68: error: ‘QNetworkInterface’ does not name a type; did you mean ‘QMetaTypeInterface’?
 bool QNativeSocketEnginePrivate::nativeSetMulticastInterface(const QNetworkInterface &iface)
                                                                    ^~~~~~~~~~~~~~~~~
                                                                    QMetaTypeInterface
socket/qnativesocketengine_win.cpp:1045:92: error: no ‘bool QNativeSocketEnginePrivate::nativeSetMulticastInterface(const int&)’ member function declared in class ‘QNativeSocketEnginePrivate’
 bool QNativeSocketEnginePrivate::nativeSetMulticastInterface(const QNetworkInterface &iface)
                                                                                            ^
socket/qnativesocketengine_win.cpp:924:13: warning: ‘bool multicastMembershipHelper(QNativeSocketEnginePrivate*, int, int, const QHostAddress&, const int&)’ defined but not used [-Wunused-function]
 static bool multicastMembershipHelper(QNativeSocketEnginePrivate *d,
             ^~~~~~~~~~~~~~~~~~~~~~~~~
Makefile.Release:13580: recipe for target '.obj/release/qnativesocketengine_win.o' failed
make[3]: *** [.obj/release/qnativesocketengine_win.o] Error 1
make[3]: Leaving directory '/home/ubuntu/build/bitcoin/depends/work/build/x86_64-w64-mingw32/qt/5.9.8-c25ce276640/qtbase/src/network'
Makefile:36: recipe for target 'release' failed
make[2]: *** [release] Error 2
make[2]: Leaving directory '/home/ubuntu/build/bitcoin/depends/work/build/x86_64-w64-mingw32/qt/5.9.8-c25ce276640/qtbase/src/network'
Makefile:257: recipe for target 'sub-network' failed
make[1]: *** [sub-network] Error 2
make[1]: Leaving directory '/home/ubuntu/build/bitcoin/depends/work/build/x86_64-w64-mingw32/qt/5.9.8-c25ce276640/qtbase/src'
funcs.mk:251: recipe for target '/home/ubuntu/build/bitcoin/depends/work/build/x86_64-w64-mingw32/qt/5.9.8-c25ce276640/qtbase/.stamp_built' failed
make: *** [/home/ubuntu/build/bitcoin/depends/work/build/x86_64-w64-mingw32/qt/5.9.8-c25ce276640/qtbase/.stamp_built] Error 2
make: Leaving directory '/home/ubuntu/build/bitcoin/depends'

**Comment by fanquake** [comment]
@MarcoFalke the bot built the old branch. That error is no longer relevant.

**Comment by Sjors** [comment]
Code review ACK 3569e0e4bc549672aa3d4eeb5d309619355574d1: just a rebase

**Comment by practicalswift** [comment]
ACK 244501fc85a1319857efb227093c0e71c1d5a01e -- diff looks correct

Thanks for doing these cleanups

**Comment by promag** [comment]
Code review ACK 244501fc85a1319857efb227093c0e71c1d5a01e.

**Pull request merged**
