### PR TITLE
[0.21] final rc4 backports

### PR DESCRIPTION
**Pull request by maflcko**
The remaining backports to get rc4 out. Currently only waiting on the macOS build fix.

### CODE REVIEW

**Comment by Sjors** [comment]
ACK up to 8273ea3

**Comment by jonatack** [comment]
Consider adding #19961 if merged in time.

**Comment by MarcoFalke** [comment]
The commits are all mostly documentation or test related clean cherry-picks IIRC, so shouldn't be too hard to review

**Comment by benthecarman** [comment]
ACK b1c0f97483f01f8836e5d83e98c881e44018cde5

**Comment by Sjors** [comment]
ACK b1c0f97

**Pull request merged**
