### PR TITLE
[FOR LATER USE][WIP][Wallet] add support for a flexible "set of features"

### PR DESCRIPTION
**Pull request by jonasschnelli**
Started with this PR before we merged https://github.com/bitcoin/bitcoin/pull/8367.
This solution would be more elegant.

This PR is more or less an announcement if someone wants to pick this up later.
Its complete but requires testing maybe bug/nit fixing.

Should be considered once we add the next new feature to the wallet.

### CODE REVIEW

**Comment by pstratem** [comment]
We already have this.

Wallets are key value, the key is effectively a feature flag.

**Comment by jonasschnelli** [comment]
> We already have this.
> 
> Wallets are key value, the key is effectively a feature flag.

I think this would not be sufficient.
What if one of the values object format changes? Sure, it could be detected by the deserializing logic. But I think explicit required "features" would be much more flexible.

**Comment by jtimon** [comment]
Needs rebase

**Comment by TheBlueMatt** [comment]
Should this just be closed?

**Comment by jonasschnelli** [comment]
> Should this just be closed?

Jup. Closing.

**Pull request closed without merging**
