### PR TITLE
multiprocess compatibility updates

### PR DESCRIPTION
**Pull request by ryanofsky**
This is a collection of small changes to interfaces and code which were needed as part of multiprocess PR #10102, but have been moved here to make that PR smaller.

All of these changes are refactoring changes which do not affect behavior of current code

---

This PR is part of the [process separation project](https://github.com/bitcoin/bitcoin/issues/28722).

### CODE REVIEW

**Review by maflcko — COMMENTED** [review]
I didn't review the Span commit yet.


ACK 28bddf90ccbb3a58d30210b6102220fa6253229f 🍍

<details><summary>Show signature</summary>

Signature:

```
untrusted comment: signature from minisign secret key on empty file; verify via: minisign -Vm "${path_to_any_empty_file}" -P RWTRmVTMeKV5noAMqVlsMugDDCyyTSbA3Re5AkUrhvLVln0tSaFWglOw -x "${path_to_this_whole_four_line_signature_blob}"
RUTRmVTMeKV5npGrKx1nqXCw5zeVHdtdYURB/KlyA/LMFgpNCs+SkW9a8N95d+U4AP1RJMi+krxU1A3Yux4bpwZNLvVBKy0wLgM=
trusted comment: ACK 28bddf90ccbb3a58d30210b6102220fa6253229f 🍍
5sCvwzO8Gj/WV/7QAif56fxTc3QT8+G/qXnBh/ZHH/rKxUb25SXW7I3/m26dnr0KfVVDVQGfar78kL1Yc4E5Dg==
```

</details>

**Review by ryanofsky — COMMENTED** [review]
Appreciate the review

Updated 28bddf90ccbb3a58d30210b6102220fa6253229f -> 3b70f7b6156cb110c47a6e482791cf337bb6ad6d ([`pr/ipcfix.2`](https://github.com/ryanofsky/bitcoin/commits/pr/ipcfix.2) -> [`pr/ipcfix.3`](https://github.com/ryanofsky/bitcoin/commits/pr/ipcfix.3), [compare](https://github.com/ryanofsky/bitcoin/compare/pr/ipcfix.2..pr/ipcfix.3)) with review suggestions.

**Comment by achow101** [comment]
ACK 3b70f7b6156cb110c47a6e482791cf337bb6ad6d

**Comment by naumenkogs** [comment]
ACK 3b70f7b6156cb110c47a6e482791cf337bb6ad6d

**Pull request merged**
