### PR TITLE
we do check for duplicate inputs in CheckBlock

### PR DESCRIPTION
**Pull request by instagibbs**
Since https://github.com/bitcoin/bitcoin/pull/14247

### CODE REVIEW

**Comment by jimpo** [comment]
As noted [here](https://github.com/bitcoin/bitcoin/pull/14247#discussion_r218252492), we might as well remove the function param entirely.

**Comment by instagibbs** [comment]
@MarcoFalke subsumed by https://github.com/bitcoin/bitcoin/pull/14258 or?

**Comment by MarcoFalke** [comment]
Indeed, looks like #14258 is doing a similar thing.

**Comment by jeffrade** [comment]
This is a popular bug fix. I was curious and was about to submit the same PR :laughing:

**Pull request closed without merging**
