### PR TITLE
add support for miniupnpc api version 14

### PR DESCRIPTION
**Pull request by ghost**
The value of new arg ttl is set to 2 as it's recommended default.

### CODE REVIEW

**Comment by fanquake** [comment]
Relevant commit from the MiniUPnP repo 
[add ttl argument to upnpDiscover() functions - increments API_VERSION to 14](https://github.com/miniupnp/miniupnp/commit/1da63faa4fff5cb30e5d4b848ceef80a292382b9)

**Comment by laanwj** [comment]
utACK

**Comment by theuni** [comment]
ut ACK. Any reason not to bump to 1.9.20150730 in depends as well?

**Comment by laanwj** [comment]
@theuni sounds good to me

**Comment by sipa** [comment]
ut ACK

**Pull request merged**
