### PR TITLE
Add bilingual_str type

### PR DESCRIPTION
**Pull request by hebasto**
This PR adds the `bilingual_str` struct and a `strprintf` overload:
https://github.com/bitcoin/bitcoin/blob/0626b8cbdf0aa971500eb5613c7ab4096c496966/src/tinyformat.h#L1066-L1067

Both new features allow bitcoin code to easily send dual translated and non-translated messages to the GUI and the logging framework.

This PR is only a refactoring (has been split off the #16224 (see: https://github.com/bitcoin/bitcoin/pull/16224/#issuecomment-509718579)) and does not change behavior.

### CODE REVIEW

**Comment by hebasto** [comment]
GH does not render comment address correctly:
` https://github.com/bitcoin/bitcoin/pull/16224/#issuecomment-509701396`

**Comment by MarcoFalke** [comment]
ACK 4e1eda717e, the diff seems verbose but I think it makes sense
to be more explicit where translated strings are passed in.
Currently we have issues where translated strings end up in the debug log.

Also, this is a requirement for future fixes such as #16224

<details><summary>Show signature and timestamp</summary>

Signature:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK 4e1eda717e, the diff seems verbose but I think it makes sense
to be more explicit where translated strings are passed in.
Currently we have issues where translated strings end up in the debug log.

Also, this is a requirement for future fixes such as #16224
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEE+rVPoUahrI9sLGYTzit1aX5ppUgFAlwqrYAACgkQzit1aX5p
pUgAxgv7B8gVJW+NBhgvYFjV7GzTcEDz0+R5pW0pW+8JXt5bYm4l9YkmBZVq/kk+
Pf/Wr2Vv91OoFIAiAu8iObedp35PzybgeZ4Dc9HlidhOHZvqxOrjNf+lINNyh+ZZ
ibv0VVcNQTeffMf6+zQoHazuyJPtNarJHmfPQQPBuYPbniW8DpDcRtamMIBxg0sd
2FMLWtgt214boyf0aNUTmQUjxqwtafuqSpOri1VVMc458lIAKma8tdQUo9U/ryfP
+F8ev8SuK+ZJF3DRqah5mCO6+5Cd5vv0e/wsVemL6DBW11IuTOdW8WCFQoTIQINL
ayT1m4fbe9wdKh1r/j4Hla8qGjrtPSfgoEj+wfghACLP2MVZxZwqraLz2tH4NFQ4
8zVtjR7Ms1PVSSNFGEoEWU7ouYdX/Jgz/KDp/MxpeFMwzTNZkBWrP5An1AwuJyyt
5VR16+80UJfF5qnOXpO3tt7t7CQzB194ZBJVLneTVUye0Q/87xW8Y5MjCDn5QBVD
TtPRZurp
=g2TS
-----END PGP SIGNATURE-----
```

[Timestamp of file with hash `a12ab7776476c20805e88823e532aa26d34082ee0510d1f17344e7869974c62a  -`](https://opentimestamps.org/info/?004f70656e54696d657374616d7073000050726f6f6600bf89e2e884e892940108a12ab7776476c20805e88823e532aa26d34082ee0510d1f17344e7869974c62af0105355d2597b2a24c2e1c5d6524e2d5c3508fff0106f8d308545c356d7934586c899ab4ba108f1045d24e17af0080a878baeafcc05260083dfe30d2ef90c8e292868747470733a2f2f66696e6e65792e63616c656e6461722e657465726e69747977616c6c2e636f6dfff010aad1f0d8952d4d73dda997adad4790af08f1045d24e17af008114125dd60e2fb040083dfe30d2ef90c8e2e2d68747470733a2f2f616c6963652e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267fff010c2558d1b0a4b0255c81ea6125173731208f1045d24e17af0082eb34d07d086166c0083dfe30d2ef90c8e232268747470733a2f2f6274632e63616c656e6461722e636174616c6c6178792e636f6df010efb9346616047e699c1ad295f8c6748908f1045d24e17af008cdd329f453217dfe0083dfe30d2ef90c8e2c2b68747470733a2f2f626f622e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267)

</details>

**Comment by hebasto** [comment]
Rebased.

**Comment by hebasto** [comment]
Rebased.

**Comment by hebasto** [comment]
Rebased.

**Review by ryanofsky — APPROVED** [review]
Thank for a making new PR to separate refactoring and behavior changes!

Conditional utACK 3b7348ff8a4633679a387dcbfe266348dcba6c2a if this PR is fixed to have a descriptive title and OP. For title I'd suggest, "Add bilingual_str class". In the description, I'd say something like, "This PR adds a bilingual_str class and a strprintf overload that allows bitcoin code to easily send dual translated and non-translated messages to the GUI and the logging framework. This PR is only a refactoring, and does not change behavior."

As I commented on the other PR, I think this PR and its followup would be simpler if the `_` function signature was changed to return bilingual_str in the same commit that changed ThreadSafeMessageBox, InitError, InitWarning, and similar functions to accept bilingual_str arguments. This would avoid the churn of having to add `.translated` suffixes and then remove them later. It would mean replacing the scripted diff commit with a manual commit, but I think the manual commit should be smaller, and honestly I'd consider it an advantage not to have to decipher the sed / bash code anyway. But this is just my suggested approach, I'm also fine with the current approach.

**Comment by hebasto** [comment]
@ryanofsky Thank you for your review.

> For title I'd suggest, "Add bilingual_str class". In the description, I'd say something like, "This PR adds a bilingual_str class and a strprintf overload that allows bitcoin code to easily send dual translated and non-translated messages to the GUI and the logging framework. This PR is only a refactoring, and does not change behavior."

Done.

> ... I'm also fine with the current approach.

Let it be ;)

**Review by ryanofsky — APPROVED** [review]
utACK 375d90974a9ba3569bb6710c8f26cdda53d01389. Only changes since last review are rebase and updating the PR title & description (thanks!). There currently a lint error making travis fail, but this looks good otherwise.

One thing is I would probably remove "gui:" prefix from PR title because that even though this is refactoring that doesn't change behavior and is meant to help the gui, the prefix could mislead reviewers to thinking the PR doesn't touch non-gui code.

**Comment by hebasto** [comment]
> There currently a lint error making travis fail, but this looks good otherwise.

Fixed.

> One thing is I would probably remove "gui:" prefix from PR title because that even though this is refactoring that doesn't change behavior and is meant to help the gui, the prefix could mislead reviewers to thinking the PR doesn't touch non-gui code.

Fair point. Done.

**Review by ryanofsky — APPROVED** [review]
utACK 753f7cccce83084f4b18cf4bdf3225183179508c. Only change since last review is fixing lint error (double includes)

**Comment by MarcoFalke** [comment]
ACK 753f7cccce

<details><summary>Show signature and timestamp</summary>

Signature:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK 753f7cccce
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEE+rVPoUahrI9sLGYTzit1aX5ppUgFAlwqrYAACgkQzit1aX5p
pUiBwgv+OJt8U0HjITstlQNagRqZacUEQZyME/hdiZRw7caFb5FGuDAulw8igqrl
PyfXIFF++rOnK/SztA/KklP6vTaTQ5VhVJpMYLsklwE0Bq4WLfhrKOybpnI+WZbo
Iv/jbKwTpjw2XR/LtVIZ6F1Dos3CTBFfJwDXgru6JEi86ByOMf9X7yCJdEi1v546
Bpg9brypH3hwcmv40mTlqazxYGvbX8PKRxH8TpEStgmyujpsKsnLHsAAQAFqAO+R
mlSC8IhT35IXAxUlr8LTvyIK1sVmShfOm9j2xUZh9DLBPR8aVt19eHgcYUNh/z1Z
ybNOe+MyYnfAnfHFmWAFaBd9lFiZWfbANsqI+htv1z5WDoEbq2j2urB7xnHbTiX+
fUmsCzUgMlIu88B02CyUuCqmeRYkPoPRIX0PEgqOVD83+TyseMjUzBPKHGgQhL71
GUV3yqgxAyme+cqFm8gHg3K/bBeY2vm5HRfK1RplJSssQrWJtzLpeT4uMSj5VSnV
qcBkK4py
=g2sy
-----END PGP SIGNATURE-----
```

[Timestamp of file with hash `ca358d398db24f0840fdb656fc63a356463d01b9f675517cbd06d4b4e20071c3  -`](https://opentimestamps.org/info/?004f70656e54696d657374616d7073000050726f6f6600bf89e2e884e892940108ca358d398db24f0840fdb656fc63a356463d01b9f675517cbd06d4b4e20071c3f0107c6452c5dc918c20a301a7115358b2fc08fff01028e0e4641074fdb3a72574f31309578608f1045d389e2cf00835ae14a1243565ae0083dfe30d2ef90c8e292868747470733a2f2f66696e6e65792e63616c656e6461722e657465726e69747977616c6c2e636f6dfff010a53effb4695885c45b4851707928805c08f1045d389e2df00811044661d906301a0083dfe30d2ef90c8e232268747470733a2f2f6274632e63616c656e6461722e636174616c6c6178792e636f6dfff010d5c1845a4d8650889d1f93359433067e08f1045d389e2cf008a471a9d138651fbe0083dfe30d2ef90c8e2c2b68747470733a2f2f626f622e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267f010dd0254b9226d8a9541fc5b6da751dfc608f1045d389e2cf0083c5d75711086b6450083dfe30d2ef90c8e2e2d68747470733a2f2f616c6963652e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267)

</details>

**Pull request merged**
