### PR TITLE
RFC: Assert on probable deadlocks if the second lock isnt try_lock

### PR DESCRIPTION
**Pull request by TheBlueMatt**
Just for travis

### CODE REVIEW

**Comment by laanwj** [comment]
Concept ACK, but this makes the deadlock detection code kind of complex. I can't immediately see whether it's correct or wrong.

**Comment by gavinandresen** [comment]
Hmmm....

Would this work instead? Modify sync.h CMutexLock::TryEnter to only call EnterCritical() if the lock is successfully acquired?
```
    bool TryEnter(const char* pszName, const char* pszFile, int nLine)
    {
        lock.try_lock();
        if (lock.owns_lock()
              EnterCritical(pszName, pszFile, nLine, (void*)(lock.mutex()), true);
        return lock.owns_lock();
    }
```

**Comment by TheBlueMatt** [comment]
@gavinandresen No, because often you see warnings because you have a lock(B) followed by a try_lock(A) and a lock(A) followed by a lock(B) at different times, you'll get a warning, but your suggestion would ignore it because you didnt actually see a deadlock.

Also, you cant just ignore try_locks entirely because it is very easy to create a deadlock with a try_lock.

**Comment by gavinandresen** [comment]
@TheBlueMatt : maybe I'm being dense... but:

If we get:  lock(B) then a successful (lock-acquired) try_lock(A), then the lockorders map will contain "B then A".
If at any point in the future lock(A) is followed by lock(B), a warning will be triggered -- my suggestion doesn't require that there be an actual deadlock.

I'm not suggesting that try_lock be ignored entirely....

**Comment by TheBlueMatt** [comment]
@gavinandresen Yes, and if a warning were triggered in that (beningn) case, then you'd see things crash on the new assert?

**Comment by sipa** [comment]
Haven't spent too much time thinking about this, but having (A, B) in one place and (B, try A) in another place can never cause a deadlock. I believe that the correct checking behaviour is to add any acquired lock to the table, but never do a deadlock check when entering a try_lock.

**Comment by TheBlueMatt** [comment]
@sipa: Consider the case A, tryB, C and C, tryB, A. This is actually not a deadlock, but if you simply skip the deadlock check for B, you'll get an error.

**Comment by TheBlueMatt** [comment]
IIRC, there was a similar case that I saw that prompted this pull.

**Comment by gavinandresen** [comment]
@TheBlueMatt : sorry, I WAS just being dense.

I'm with @laanwj -- ACK on the concept, but I'm having trouble convincing myself the code is correct (I may just need more caffeine before thinking about it some more). It feels like there should be a simpler solution.

**Comment by sipa** [comment]
Interesting. I agree (a,try b,c),(c,try b,a)) is not a deadlock, but it is
not something any code should be doing - it looks extremely fragile
(*remove* a lock, and turn it into a deadlock). So I'd rather trigger
deadlock warnings for it too.

**Comment by TheBlueMatt** [comment]
IIRC we (used to) do something like that. We may not anymore, but some of the network processing stuff is a mess.

**Comment by TheBlueMatt** [comment]
@sipa checked, turns out the deadlock detection code never called potential_deadlock_detected for TRY_LOCKs so we definitely still do require the code in this pull before we can assert on deadlocks. Also rebased and added a comment so that this is more readable.

**Pull request merged**
