### PR TITLE
Remove redundant semicolons

### PR DESCRIPTION
**Pull request by practicalswift**

### CODE REVIEW

**Review by dcousens — APPROVED** [review]

**Comment by practicalswift** [comment]
@dcousens Thanks for the quick review! Appreciated! :-)

**Comment by fanquake** [comment]
ACK 8fc6989

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/commit/8fc698935f01a9f0675e509761fb69be8d43e80a

**Comment by MarcoFalke** [comment]
ACK 8fc698935f01a9f0675e509761fb69be8d43e80a

**Comment by practicalswift** [comment]
Ready for merge? :-)

**Pull request merged**
