### PR TITLE
[Qt] change debug window tab ordering, move "console" at front

### PR DESCRIPTION
**Pull request by jonasschnelli**
I'm not sure what other think about this. But IMO it makes more sense to have the console at first pos.
Maybe it would even be better to have the console separated from the debug window.
Adding a separate menu entry "Help" -> "Console" could also make sense.

### CODE REVIEW

**Comment by luke-jr** [comment]
I think not. The debug information is far more useful to people than the console, which should only be touched by experts. I think it'd be okay to make the console a main window tab, though, provided it be conditional on some "Advanced expert functionality" setting in Options.

**Comment by jonasschnelli** [comment]
Okay. I see.
I try to change this PR to allow users to open the console from a separate menu item and remove the console from the debug window.

But i disagree with having a "expert setting" for this.
Especially when compiling/running in -NOWALLET mode the RPC console can/is fundamental to the GUI.
I would even say the RPC Console is not much more of a expert-function as the rest of the UI.
This could change once we add SPV and some other features which could make Bitcoin-Qt basic-user-compatible.

**Comment by luke-jr** [comment]
The entire UI as it is right now (excepting Coin Control, which is an advanced setting disabled by default) is perfectly fine for the most novice users. SPV is a nice optimisation for *impatient* users, but has nothing to do with skill level.

**Comment by laanwj** [comment]
I prefer to keep this as-is too. The debug window is useful to get some quick information about the running node. It's easy enough to switch to the console if you do need it.

**Comment by jonasschnelli** [comment]
Okay. Agreed.

**Pull request closed without merging**
