### PR TITLE
[qa] Adjust poll interval for micro-optimization of run time

### PR DESCRIPTION
**Pull request by maflcko**
This will save up to half a minute depending on the system.

Depends on https://github.com/bitcoin/bitcoin/issues/8532#issuecomment-240601644

### CODE REVIEW

**Comment by luke-jr** [comment]
utACK, seems reasonably safe. (The actual timeouts are unchanged, just the poll interval.)

**Comment by MarcoFalke** [comment]
Correct. Actually, increasing the polling frequency increases the timeouts because you have to add the round trip time in each loop to get the "real" timeout.

**Comment by laanwj** [comment]
Doesn't seem to result in any noticable speedup for me. With this patch:
```
ALL                            | True   | 832 s (accumulated)

Runtime: 243 s
```
Without this patch:
```
ALL                            | True   | 838 s (accumulated)

Runtime: 237 s
```

**Comment by MarcoFalke** [comment]
Closing, I think there are better ways to improve runtime.

**Pull request closed without merging**
