### PR TITLE
test: Avoid connecting to real network when running tests

### PR DESCRIPTION
**Pull request by maflcko**
Introduced in #19884

### CODE REVIEW

**Comment by Sjors** [comment]
ACK fa730e915766b012ff145e3c2af782668defb21f

Can you add a note _which_ test was connecting to the outside world? I assume it's one of the few tests that uses mainnet?

**Comment by MarcoFalke** [comment]
I haven't checked if any of the current tests reach out right now, but any non-regtest test might be affected.

**Comment by practicalswift** [comment]
Concept ACK

Good catch! Accidental telemetry is still telemetry and should be removed.

**Comment by practicalswift** [comment]
To detect accidental introduction of telemetry in the future: could we perhaps guard against external connections in tests via say a seccomp restricted job in Travis? Perhaps `nsjail` or `firejail` could be used.

**Comment by MarcoFalke** [comment]
Sure, pull request welcome

**Pull request merged**
