### PR TITLE
Bump univalue subtree and fix json formatting in tests

### PR DESCRIPTION
**Pull request by maflcko**
The subtree-merge commit also fixes the whitespace for failing tests, such that bisect doesn't break.

Finally, the bump also includes the changes that accidentally modified our subtree, such that the subtree check should work fine now:

```sh
./contrib/devtools/git-subtree-check.sh src/univalue

### CODE REVIEW

**Comment by laanwj** [comment]
utACK faaeeb0

The whitespace fix is a nice little improvement.

**Comment by fanquake** [comment]
I haven't been able to verify this like the secp256k1 subtree. Is this waiting for https://github.com/bitcoin-core/univalue/pull/7 to be merged?

**Comment by MarcoFalke** [comment]
Jup, the commit should be merged first.

**Comment by laanwj** [comment]
https://github.com/bitcoin-core/univalue/pull/7 is merged

**Comment by fanquake** [comment]
tested ACK faaeeb0
```
[pull/11420/local-merge f94cd2237] Merge #11420: Bump univalue subtree and fix json formatting in tests
 Date: Wed Oct 11 19:13:16 2017 +0800
#11420 Bump univalue subtree and fix json formatting in tests into master
* faaeeb0d3 Bump univalue and fix json formatting in tests (MarcoFalke) (pull/11420/head)
* 619bb0503 Squashed 'src/univalue/' changes from 16a1f7f6e..fe805ea74 (MarcoFalke)

Dropping you on a shell so you can try building/testing the merged source.
Run 'git diff HEAD~' to show the changes being merged.
Type 'exit' when done.
bash-3.2$ git fetch https://github.com/bitcoin-core/univalue.git
warning: no common commits
remote: Counting objects: 565, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 565 (delta 0), reused 4 (delta 0), pack-reused 558
Receiving objects: 100% (565/565), 111.21 KiB | 77.00 KiB/s, done.
Resolving deltas: 100% (304/304), done.
From https://github.com/bitcoin-core/univalue
 * branch                HEAD       -> FETCH_HEAD
bash-3.2$ ./contrib/devtools/git-subtree-check.sh src/univalue
src/univalue in HEAD was last updated to upstream commit fe805ea74f8919382720b09a905a14e81311b3ad (tree 5d48005ff778ddf521705b5d08d19189966fc36b)
src/univalue in HEAD currently refers to tree 5d48005ff778ddf521705b5d08d19189966fc36b
GOOD
```
```
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS check-local
Running test/util/bitcoin-util-test.py...
/usr/local/bin/python3.6 ../test/util/bitcoin-util-test.py
  CC       src/tests-tests.o
  CC       src/exhaustive_tests-tests_exhaustive.o
make[5]: `libsecp256k1.la' is up to date.
  CCLD     exhaustive_tests
PASS: qt/test/test_bitcoin-qt
  CCLD     tests
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS
PASS: exhaustive_tests
PASS: tests
============================================================================
Testsuite summary for libsecp256k1 0.1
============================================================================
# TOTAL: 2
# PASS:  2
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
  CXX      test/test_object-object.o
  CXX      test/test_test_json-test_json.o
  CXX      test/test_unitester-unitester.o
  CXX      test/test_no_nul-no_nul.o
  CXXLD    test/no_nul
  CXXLD    test/test_json
  CXXLD    test/unitester
  CXXLD    test/object
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS
PASS: test/no_nul
PASS: test/object
PASS: test/unitester
============================================================================
Testsuite summary for univalue 1.0.3
============================================================================
# TOTAL: 3
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
PASS: test/test_bitcoin
============================================================================
Testsuite summary for Bitcoin Core 0.15.99
============================================================================
# TOTAL: 2
# PASS:  2
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Making check in doc/man
make[1]: Nothing to be done for `check'.
make[1]: Nothing to be done for `check-am'.

```

**Comment by laanwj** [comment]
Thanks for testing @fanquake , looks good to me now.

**Pull request merged**
