### PR TITLE
depends: Support for S390X and POWER targets

### PR DESCRIPTION
**Pull request by maflcko**
Failure before:

```
$ make -C depends HOST=powerpc64-linux-gnu
...
ERROR: Feature 'system-zlib' was enabled, but the pre-condition 'libs.zlib' failed.

ERROR: Feature 'xcb' was enabled, but the pre-condition 'libs.xcb' failed.

ERROR: Feature 'system-freetype' was enabled, but the pre-condition 'features.freetype && libs.freetype' failed.

ERROR: Feature 'fontconfig' was enabled, but the pre-condition '!config.win32 && !config.darwin && features.system-freetype && libs.fontconfig' failed.
make: *** [funcs.mk:254: /bitcoin/depends/work/build/powerpc64-linux-gnu/qt/5.9.8-95548079095/qtbase/.stamp_configured] Error 3


$ make -C depends HOST=s390x-linux-gnu
...
ERROR: Feature 'system-zlib' was enabled, but the pre-condition 'libs.zlib' failed.

ERROR: Feature 'xcb' was enabled, but the pre-condition 'libs.xcb' failed.

ERROR: Feature 'system-freetype' was enabled, but the pre-condition 'features.freetype && libs.freetype' failed.

ERROR: Feature 'fontconfig' was enabled, but the pre-condition '!config.win32 && !config.darwin && features.system-freetype && libs.fontconfig' failed.
make: *** [funcs.mk:254: /bitcoin/depends/work/build/s390x-linux-gnu/qt/5.9.8-79c6d6ca6ec/qtbase/.stamp_configured] Error 3
```

### CODE REVIEW

**Comment by elichai** [comment]
Is this needed for cross compilation?

**Comment by MarcoFalke** [comment]
> Is this needed for cross compilation?

Yes. I couldn't get cross compilation to work (see OP)

**Comment by laanwj** [comment]
Code review ACK 11113247c323c5b98debcb512fb9db9fe5a8e7cf
Haven't tested cross-compile for these targets but this is definitely the kind of change that is needed for depends to support them.

**Comment by dongcarl** [comment]
tested ACK 11113247c323c5b98debcb512fb9db9fe5a8e7cf

-----

Tested on Ubuntu Bionic docker containers after installing dependencies per https://github.com/bitcoin/bitcoin/blob/11113247c323c5b98debcb512fb9db9fe5a8e7cf/depends/README.md#for-linux-including-i386-arm-cross-compilation

**Comment by practicalswift** [comment]
ACK 11113247c323c5b98debcb512fb9db9fe5a8e7cf -- diff looks correct

**Pull request merged**
