### PR TITLE
test: Change background_cs from pointer to reference in validation_chainstate_tests

### LINKED ISSUE #23101: compiler warning on building src/test/test_bitcoin-validation_chainstate_tests.o
**Is your feature request related to a problem? Please describe.**

Warning on building using g++ 8.3.

```
 1 In file included from ./txdb.h:11,
 2                  from ./validation.h:26,
 3                  from ./test/util/chainstate.h:13,
 4                  from test/validation_chainstate_tests.cpp:11:
 5 ./chain.h: In member function ‘void validation_chainstate_tests::chainstate_update_tip::test_method()’:
 6 ./chain.h:422:27: warning: ‘background_cs’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 7          return vChain.size() > 0 ? vChain[vChain.size() - 1] : nullptr;
 8                 ~~~~~~~~~~~^~
 9 test/validation_chainstate_tests.cpp:109:18: note: ‘background_cs’ was declared here
10      CChainState* background_cs;
11                   ^~~~~~~~~~~~~
12
```

**Describe the solution you'd like**

Able to build without warnings.

**Describe alternatives you've considered**

N/A.

**Additional context**

`cd src/ && make test/test_bitcoin-validation_chainstate_tests.o`

Bisecting this warning, I ended up in revision 673a5bd3377929a0
by @jamesob.

Thank you very much and please excuse the noise.

### PR DESCRIPTION
**Pull request by maflcko**
This changes background_cs from being a pointer to a reference to work
around a gcc false warning. Also, this makes the test easier to read.

Fixes bitcoin#23101

Can be reviewed with --ignore-all-space.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
This is fixed in gcc8.4, I believe, but debian:buster still ships 8.3, in case anyone wants to test this: https://packages.debian.org/buster/gcc

**Comment by practicalswift** [comment]
Concept ACK

**Comment by mzumsande** [comment]
A description with a link to the issue it fixes would be nice.

**Comment by MarcoFalke** [comment]
The description is in the body of the commit message.

**Comment by jnewbery** [comment]
>> A description with a link to the issue it fixes would be nice.

> The description is in the body of the commit message.

I agree that the description/link to issue should appear in the PR description, to make it easier for other contributors to quickly understand what the PR is doing.

**Comment by MarcoFalke** [comment]
Ok, copy-pasted the description

**Comment by practicalswift** [comment]
cr ACK fa4d0aacf2bbddaf1709660ffd8d520570533aa8

**Comment by laanwj** [comment]
Concept ACK

I've tried to make the PR title clearer, but I don't know: does this only affect gcc 8.3 or a wider version range?

**Comment by MarcoFalke** [comment]
No idea which gcc version are affected. I only tested debian-gcc-8.3

**Comment by katesalazar** [comment]
Nobody needs to sweat it, who cares, simply keep GCC 8.3 for now.

Ideally, you would find out the answer by reading CI workers' logs,
not by asking peers.

**Comment by MarcoFalke** [comment]
We don't have the resources to maintain CI scripts for every operating system and every compiler version, so I think asking which version is affected seems reasonable.

**Review by hebasto — APPROVED** [review]
ACK fa4d0aacf2bbddaf1709660ffd8d520570533aa8, tested on Linux Mint 20.2 (x86_64) by merging this PR on top of the current master.

Compiler:
```
$ gcc --version
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

- master (1790a8ddacae0d52135f5020894ef1ceef625cf9):
```
$ make > /dev/null 
test/fuzz/float.cpp: In function ‘void float_fuzz_target(FuzzBufferType)’:
test/fuzz/float.cpp:60:30: warning: ‘tmp’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   60 |         assert(std::isnan(d) || d == d_deserialized);
      |                              ^~
In file included from ./validation.h:15,
                 from ./test/util/chainstate.h:13,
                 from test/validation_chainstate_tests.cpp:11:
./chain.h: In member function ‘void validation_chainstate_tests::chainstate_update_tip::test_method()’:
./chain.h:422:27: warning: ‘background_cs’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  422 |         return vChain.size() > 0 ? vChain[vChain.size() - 1] : nullptr;
      |                ~~~~~~~~~~~^~
test/validation_chainstate_tests.cpp:110:18: note: ‘background_cs’ was declared here
  110 |     CChainState* background_cs;
      |                  ^~~~~~~~~~~~~
```

- master (1790a8ddacae0d52135f5020894ef1ceef625cf9) + this PR:
```
$ make > /dev/null 
test/fuzz/float.cpp: In function ‘void float_fuzz_target(FuzzBufferType)’:
test/fuzz/float.cpp:60:30: warning: ‘tmp’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   60 |         assert(std::isnan(d) || d == d_deserialized);
      |                              ^~
```

**Pull request merged**
