### PR TITLE
init: abort if i2p/cjdns are chosen via -onlynet but are unreachable

### PR DESCRIPTION
**Pull request by mzumsande**
If the networks i2p / cjdns are chosen via `-onlynet` but the user forgot to provide `-i2psam` / `-cjdnsreachable`, no outbound connections will be made - it would be nice to inform the user about that.
The solution proposed here mimics existing behavior for `-onlynet=onion` and non-specified `-onion`/`-proxy` where we already abort with an InitError - if reviewers would prefer to just print a warning, please say so.

The second commit adds CJDNS support to the debug-only `addpeeraddress` RPC allowing to add CJDNS addresses to addrman for testing and debug purposes. (if `-cjdnsreachable=1`)

This is the result of an [IRC discussion](https://bitcoin-irc.chaincode.com/bitcoin-core-dev/2022-09-01#848066;) with vasild.

### CODE REVIEW

**Comment by brunoerg** [comment]
Concept ACK

**Comment by 1440000bytes** [comment]
> If the networks i2p / cjdns are chosen via -onlynet but the user forgot to provide -i2psam / -cjdnsreachable, no outbound connections will be made - it would be nice to inform the user about that.

It's mentioned in the i2p doc that `i2psam` is required.

> The second commit adds CJDNS support to the debug-only addpeeraddress RPC allowing to add CJDNS addresses to addrman for testing and debug purposes. (if -cjdnsreachable=1)

Is his commit related to first change in any way?

**Review by vasild — APPROVED** [review]
ACK b3576b7e594dc75a8100e231089f3f5985207bb7

**Comment by brunoerg** [comment]
> The solution proposed here mimics existing behavior for -onlynet=onion and non-specified -onion/-proxy where we already abort with an InitError - if reviewers would prefer to just print a warning, please say so.

This approach is ok for me. But I slightly prefer a warning and it could set up `-i2psam` / `-cjdnsreachable` for me (like a "`SoftSetBoolArg`") if I chose one of them in `-onlynet`. Are there any malefits in doing so?

**Comment by mzumsande** [comment]
> Is this commit related to first change in any way?

Not directly, it's a small and imo uncontroversial improvement to addpeeraddrress, which also deals with cjdns (and which might help to manually add manually cjdns peers to addrman if we can't find any, even if it's currently debug-only), so I thought might make sense to include here. If preferred, I could drop it.

> This approach is ok for me. But I slightly prefer a warning 

I chose an error because of the existing behavior with `-onlynet=onion` and missing `-proxy`, and I don't really see a reason why a different approach for different privacy networks would make sense. That being said, I'd be fine with a warning too, but in that case we probably should also just warn in the `-onlynet=onion` case.
I think it would be best to wait for the discussion in #24991 (which is more important than this PR and hopefully gets into 24.0, because it fixes a bug) and adapt this to PR to imitate whatever approach was chosen there.

> (...) and it could set up `-i2psam` / `-cjdnsreachable` for me (like a "`SoftSetBoolArg`") if I chose one of them in `-onlynet`. Are there any malefits in doing so?

I think that soft-setting `-i2psam` would entail guessing the i2p proxy (default "127.0.0.1:7656" but configurable), which seems not ideal to me.

**Comment by brunoerg** [comment]
> I think that soft-setting -i2psam would entail guessing the i2p proxy (default "127.0.0.1:7656" but configurable), which seems not ideal to me.

You're right. Thanks.

**Review by luke-jr — CHANGES_REQUESTED** [review]
If you set `-onlynet=cjdns -onlynet=ipv6`, it shouldn't fail IMO. Maybe a warning.

**Comment by vasild** [comment]
@luke-jr,

Requesting `-onlynet` to an unreachable network is a sign the user does not know what they are doing / misconfigured `bitcoind` / the provided configuration will not have the expected effects. In such a case I think it is best to stop at startup.

In particular, that means:
* for `-onlynet=onion` to work, a tor proxy must be provided either via `-proxy`, `-onion` or `-torcontrol`+`-listenonion=1`
* for `-onlynet=i2p` to work, I2P proxy must be provided via `-i2psam`
* for `-onlynet=cjdns` to work, the CJDNS network must be reachable in the environment where `bitcoind` is running and signaled to `bitcoind` by `-cjdnsreachable`

regardless of whether additional `-onlynet` options are used.

**Comment by fanquake** [comment]
> I think it would be best to wait for the discussion in https://github.com/bitcoin/bitcoin/pull/24991 (which is more important than this PR and hopefully gets into 24.0, because it fixes a bug) and adapt this to PR to imitate whatever approach was chosen there.

#24991 has now been merged, and will be part of 24.0.

**Comment by mzumsande** [comment]
[b3576b7 ](https://github.com/bitcoin/bitcoin/commit/b3576b7e594dc75a8100e231089f3f5985207bb7)to [68209a7](https://github.com/bitcoin/bitcoin/commit/68209a7b5c0326e14508d9cf749771605bd6ffe7): Rebased

I kept it at `InitErrors`, not warnings, see @vasild's [rationale](https://github.com/bitcoin/bitcoin/pull/25989#issuecomment-1243391928), plus I can't see a good reason why we should just have warnings for certain networks, but errors for others in a comparable situation.

**Comment by mzumsande** [comment]
@fanquake: I don't see a strong need to push this last-minute in 24.0, at least it shouldn't delay anything. In contrast to #24991 which fixed a bug (users with a reasonable configuration would get an InitError at startup) this is just a nice-to-have (users who don't read the docs and choose an unreasonable configuration will get an InitError now instead of getting no peers from that network).

**Comment by fanquake** [comment]
> I don't see a strong need to push this last-minute in 24.0, at least it shouldn't delay anything.

@mzumsande I've added the milestone as a nice-to-fix for 24.x, and this should be simple to backport. This wont be blocking branch-off.

**Review by vasild — APPROVED** [review]
ACK 68209a7b5c0326e14508d9cf749771605bd6ffe7

**Review by dergoegge — APPROVED** [review]
ACK 68209a7b5c0326e14508d9cf749771605bd6ffe7 

fun fact: passing `-onlynet=i2p` takes a lot longer to error than passing `-onlynet=cjdns` because we load the chainstate (and other chain related data structures) before the i2p checks but after the cjdns checks. Not sure if that is worth a refactor (in a follow up) but in my opinion there is really no reason to have the chainstate loaded before doing all networking checks.

**Comment by fanquake** [comment]
Added to #26133 for backporting to 24.x.

**Pull request merged**
