### PR TITLE
Allow peers to determine how much they are seen to be misbehaving.

### PR DESCRIPTION
**Pull request by rebroad**
This can allow peers in future to modify their behaviour to avoid netsplits.

### CODE REVIEW

**Comment by rebroad** [comment]
@laanwj Just re-read your message https://github.com/bitcoin/bitcoin/pull/4389#issuecomment-47865956 above, and I realise the assumption you were making, i.e. that behaviour learned about misbehaviour would apply to more nodes than the node giving the feedback.

I don't think a node should assume all nodes classify the same behaviour as misbehaviour, this would certainly open up to the "bad feedback" sybil atack you mention. Instead, nodes should regard any feedback as being applicable only to the node giving it.

**Comment by sipa** [comment]
I think we should just get rid of misbehaviour scores entirely - all they do is making it harder to debug problems. Things that result in a ban score should just immediately trigger a ban, and others should have no effect at all. The only thing they help with is reduce the chance of accidentally have a relayed network message not immediately partition the network, but if this can happen with a 100-score misbehaviour, it can probably happen ten times with a 10-score misbehaviour.

**Comment by venzen** [comment]
that would be more efficient, wrt connection management, and eliminate the need for node behavior accounting/tracking.

it seems that notions of "misbehavior" belong in consensus code. Blatant breaches of protocol should just result in a ban, straight-away

**Comment by venzen** [comment]
if a ban disconnect is accompanied by a ```bye``` message as suggested by @laanwj then that could be useful to other clients and their developers, It will also mean that protocol breach is explicitly stated as the reason for disconnect both for specifically challenging unacceptable protocol behavior and to assist all client software and developers.

Yes, client development should still be done via connection to a Satoshi client running with ```-debug``` but the cases for punishing peers are quite specific and it would be useful to address such behavior directly and specifically via ```bye``` with a varchar string payload.

**Comment by rebroad** [comment]
@sipa Is there some sort of roadmap document for Bitcoin Core? If so, I think your idea to abolish the current misbehaviour model should be added and I am in agreement. I like the "bye" message idea also, although technically, it's not needed as all unknown commands are currently logged so any messages could be sent that way :) 

I'd be happy to write a commit now that sends bye messages prior to disconnects and ban 100s. For the ban <100s, what could be used? A reject message? e.g. a reject message is currently sent in response to multiple version messages.

**Comment by sipa** [comment]
This was just a personal opinion, certainly not something that has been
addressed project-wide, and people may very well disagree.

Also, sorry for furthering this. We should hijact a old issue for this
discussion.

**Comment by rebroad** [comment]
@sipa Given the varying timezones we occupy, this is a better place to discuss this (for me at least) than the IRC channel.. We really need a better medium to discuss these things. Both IRC and the mailing list seem less than ideal compared to here. Perhaps wiki.bitcoin.com ?

**Pull request closed without merging**
