### PR TITLE
Reduce unnecessary default logging

### PR DESCRIPTION
**Pull request by ajtowns**
Moves the following log messages into debug log categories:

 * "AcceptBlockHeader: ..." to validation
 * "Prune: deleted blk/rev" to new blockstorage log category
 * "Leaving block file" moves from validation to blockstorage
 * "write coins cache to disk" to bench

Also adds the hash of the block to the log message when AcceptBlockHeader is rejecting because of problems with the prev block.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
```
                                     File "/tmp/cirrus-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/rpc_misc.py", line 60, in run_test
                                       assert_equal(len(node.logging()), 26)
                                     File "/tmp/cirrus-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/util.py", line 50, in assert_equal
                                       raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
                                   AssertionError: not(27 == 26)

**Review by ghost — APPROVED** [review]

**Review by promag — COMMENTED** [review]
Code review ACK b5950dd59ca3e144721a5f15568a65be43bd2f20.

**Comment by practicalswift** [comment]
cr ACK b5950dd59ca3e144721a5f15568a65be43bd2f20

**Review by meshcollider — COMMENTED** [review]
Code review ACK b5950dd59ca3e144721a5f15568a65be43bd2f20

**Pull request merged**
