### PR TITLE
contrib: macdeploy: fix typo in permissions

### LINKED ISSUE #24947: Permissions corrupted in gen-sdk macosx headers
I think #24534 broke the MacOS SDK:
```
guest@gnu /tmp/Xcode-12.2-12B45b-extracted-SDK-with-libcxx-headers$ ls -al
total 32
drwxr-xr-x 4 guest users 4096 Apr 22 18:58 ./
drwxrwxrwt 4 root  root  4096 Apr 22 18:58 ../
---x---r-- 1 guest users  127 Jan  1  1970 Entitlements.plist
---x---r-- 1 guest users 4307 Jan  1  1970 SDKSettings.json
---x---r-- 1 guest users 3597 Jan  1  1970 SDKSettings.plist
drwxr-xr-x 4 guest users 4096 Jan  1  1970 System/
drwxr-xr-x 7 guest users 4096 Jan  1  1970 usr/
```
Causing the guix build to fail with:
```
checking for x86_64-apple-darwin-gcc... env -u C_INCLUDE_PATH -u CPLUS_INCLUDE_PATH -u OBJC_INCLUDE_PATH -u OBJCPLUS_INCLUDE_PATH -u CPATH -u LIBRARY_PATH /home/kvaciral/.guix-profile/bin/clang --target=x86_64-apple-darwin -mmacosx-version-min=10.15 -B/bitcoin/depends/x86_64-apple-darwin/native/bin -mlinker-version=609 -isysroot/bitcoin/depends/SDKs/Xcode-12.2-12B45b-extracted-SDK-with-libcxx-headers -Xclang -internal-externc-isystem/gnu/store/v770rvqs8q21mbzwb3gkihr2glgn80am-clang-10.0.1/lib/clang/10.0.1/include -Xclang -internal-externc-isystem/bitcoin/depends/SDKs/Xcode-12.2-12B45b-extracted-SDK-with-libcxx-headers/usr/include
checking whether the C compiler works... no
configure: error: in `/bitcoin/depends/work/build/x86_64-apple-darwin/libevent/2.1.12-stable-6395cab7fb6':
configure: error: C compiler cannot create executables
See `config.log' for more details
make: *** [[funcs.mk:283](http://funcs.mk:283/): /bitcoin/depends/work/build/x86_64-apple-darwin/libevent/2.1.12-stable-6395cab7fb6/./.stamp_configured] Error 77
make: Leaving directory '/bitcoin/depends'
kvaciral@penumbra:~/projects/bitcoin$
```

Reported by @kvaciral.

### PR DESCRIPTION
**Pull request by prusnak**
Fixes https://github.com/bitcoin/bitcoin/issues/24947

### CODE REVIEW

**Comment by laanwj** [comment]
Code review ACK, looks like it fixes the problem on first glance!
(but let's learn from our last mistake and actually test it in a guix build before ACKing :blush:  )

**Comment by Beckyscrypto** [comment]
1ED637BB-724F-44BC-A7DF-6361101C58F6
83187AA0-1358-40B7-92DC-7154FB39A6FA
[Uploading ContractWolf_Audit_CerberusProtocol.pdf…]()

**Comment by hebasto** [comment]
```
$ ./contrib/macdeploy/gen-sdk ../XIP/Xcode.app
Found Xcode (version: 12.2, build id: 12B45b)
Found MacOSX SDK (version: 11.0, build id: 20A2408)
Creating output .tar.gz file...
Adding MacOSX SDK 11.0 files...
Adding libc++ headers...
Done! Find the resulting gzipped tarball at:
/home/hebasto/GitHub/bitcoin/Xcode-12.2-12B45b-extracted-SDK-with-libcxx-headers.tar.gz
hebasto@latitude-5490:~/GitHub/bitcoin$ sha256sum Xcode-12.2-12B45b-extracted-SDK-with-libcxx-headers.tar.gz 
df75d30ecafc429e905134333aeae56ac65fac67cb4182622398fd717df77619  Xcode-12.2-12B45b-extracted-SDK-with-libcxx-headers.tar.gz
```

**Review by hebasto — APPROVED** [review]
ACK 51d06df8746828ffac39ac94f9efa3332b3f0556

**Review by fanquake — APPROVED** [review]
ACK 51d06df8746828ffac39ac94f9efa3332b3f0556 - recreated the tarball, but didn't run a Guix build. 

```bash
shasum -a 256 Xcode-12.2-12B45b-extracted-SDK-with-libcxx-headers.tar.gz
df75d30ecafc429e905134333aeae56ac65fac67cb4182622398fd717df77619  Xcode-12.2-12B45b-extracted-SDK-with-libcxx-headers.tar.gz
```

**Comment by jarolrod** [comment]
post merge ack, was able to recreate the tarball and then ran a guix build

**Pull request merged**
