### PR TITLE
test: bip125-replaceable in listsinceblock

### PR DESCRIPTION
**Pull request by brunoerg**
This PR adds test coverage for bip125-replaceable in listsinceblock. I added this test into wallet_listtransactions.py instead of putting it into wallet_listsinceblock.py to utilize the scenario already created in wallet_listtransactions.py and avoid repetition.

### CODE REVIEW

**Review by theStack — APPROVED** [review]
ACK b7884dd1b68814c59ff4fb5f7a199e306b015e85

**Review by promag — COMMENTED** [review]
ACK b7884dd1b68814c59ff4fb5f7a199e306b015e85.

**Review by stratospher — COMMENTED** [review]
tested ACK b7884dd. Verified the bip125-replaceable status of some transactions with listsinceblock.

<details>
<summary>Test results:</summary>
<br>


```
$ test/functional/wallet_listtransactions.py
2021-10-16T05:53:33.218000Z TestFramework (INFO): Initializing test directory /var/folders/bh/7x61zw991x15d01dlnx_cgrh0000gn/T/bitcoin_func_test_birab8hp
2021-10-16T05:53:35.521000Z TestFramework (INFO): Test simple send from node0 to node1
2021-10-16T05:53:35.826000Z TestFramework (INFO): Test confirmations change after mining a block
2021-10-16T05:53:35.841000Z TestFramework (INFO): Test send-to-self on node0
2021-10-16T05:53:36.133000Z TestFramework (INFO): Test sendmany from node1: twice to self, twice to node0
2021-10-16T05:53:45.867000Z TestFramework (INFO): Test 'include_watchonly' feature (legacy wallet)
2021-10-16T05:53:47.363000Z TestFramework (INFO): Test txs w/o opt-in RBF (bip125-replaceable=no)
2021-10-16T05:53:49.817000Z TestFramework (INFO): Test txs with opt-in RBF (bip125-replaceable=yes)
2021-10-16T05:53:52.112000Z TestFramework (INFO): Test tx with unknown RBF state (bip125-replaceable=unknown)
2021-10-16T05:53:53.147000Z TestFramework (INFO): Test bip125-replaceable status with gettransaction RPC
2021-10-16T05:53:53.166000Z TestFramework (INFO): Test bip125-replaceable status with listsinceblock
2021-10-16T05:53:53.182000Z TestFramework (INFO): Test mined transactions are no longer bip125-replaceable
2021-10-16T05:53:53.240000Z TestFramework (INFO): Stopping nodes
2021-10-16T05:53:53.769000Z TestFramework (INFO): Cleaning up /var/folders/bh/7x61zw991x15d01dlnx_cgrh0000gn/T/bitcoin_func_test_birab8hp on exit
2021-10-16T05:53:53.769000Z TestFramework (INFO): Tests successful
```

</details>

**Review by lsilva01 — APPROVED** [review]
tACK b7884dd  on Ubuntu 20.04

**Pull request merged**
