### PR TITLE
refactor: Simply include CTxMemPool::Options in CTxMemPool directly rather than duplicating definition

### PR DESCRIPTION
**Pull request by luke-jr**
Instead of duplicating mempool options two places, just include the Options struct directly on the CTxMemPool

### CODE REVIEW

**Comment by glozow** [comment]
Looking at the conflicts with kernel, v3, cluster mempool, etc., is this the kind of mempool refactor we should defer for now?

**Comment by luke-jr** [comment]
reopen please

**Comment by luke-jr** [comment]
Rebased

**Review by kristapsk — APPROVED** [review]
cr utACK cc67d33fdac45357b593b1faff3d1735e5fe91ba

**Review by jonatack — COMMENTED** [review]
Nice cleanup.

ACK cc67d33fdac45357b593b1faff3d1735e5fe91ba

**Comment by achow101** [comment]
ACK cc67d33fdac45357b593b1faff3d1735e5fe91ba

**Pull request merged**
