### PR TITLE
rpc: Allow importmulti watchonly imports with locked wallet

### LINKED ISSUE #17867: importmulti does not allow watchonly imports while wallet is locked
This differs from behaviour of `importaddress` where it works.
```
$ bitcoin-cli importaddress "<address>" "<label>" false
```
vs
```
$ bitcoin-cli importmulti '[{ "scriptPubKey": { "address": "<address>" }, "timestamp":0, "label": "<label>", "watchonly": true }]' '{ "rescan": false }'
error code: -13
error message:
Error: Please enter the wallet passphrase with walletpassphrase first.
```

### PR DESCRIPTION
**Pull request by aureleoules**
Allows watch-only imports on locked wallets with `importmulti`.
Also adds a test.

Fixes #17867.

### CODE REVIEW

**Review by kristapsk — APPROVED** [review]
ACK fea634603f0424d82370f6118602da081740e676

**Comment by theStack** [comment]
Concept ACK

**Review by theStack — APPROVED** [review]
Code-review ACK fea634603f0424d82370f6118602da081740e676

Could also add a test checking that the RPC still throws on a locked wallet if there are any non-watchonly imports:

```diff
diff --git a/test/functional/wallet_importmulti.py b/test/functional/wallet_importmulti.py
index 0a6cdc290..62a1a3341 100755
--- a/test/functional/wallet_importmulti.py
+++ b/test/functional/wallet_importmulti.py
@@ -878,6 +878,12 @@ class ImportMultiTest(BitcoinTestFramework):
         self.log.info('Test watchonly imports on a wallet with a passphrase, without unlocking')
         self.nodes[1].createwallet(wallet_name='w1', blank=True, passphrase='pass')
         wrpc = self.nodes[1].get_wallet_rpc('w1')
+        assert_raises_rpc_error(-13, "Please enter the wallet passphrase with walletpassphrase first.",
+                                wrpc.importmulti, [{
+                                    'desc': descsum_create('wpkh(' + pub1 + ')'),
+                                    "timestamp": "now",
+                                }])
+
         result = wrpc.importmulti(
             [{
                 'desc': descsum_create('wpkh(' + pub1 + ')'),
```

**Comment by aureleoules** [comment]
@theStack thanks, I applied the diff.

**Review by kristapsk — APPROVED** [review]
re-ACK 2c03465dfa18ee615f76b6e507a65ef451ce1b7c

**Review by theStack — APPROVED** [review]
re-ACK 2c03465dfa18ee615f76b6e507a65ef451ce1b7c

**Comment by achow101** [comment]
ACK 2c03465dfa18ee615f76b6e507a65ef451ce1b7c

**Pull request merged**
