### PR TITLE
lint: Check that all wallet args are hidden

### PR DESCRIPTION
**Pull request by maflcko**
Can be tested by calling `git revert 765d5890be` and then running the script

### CODE REVIEW

**Comment by fanquake** [comment]
utACK fac174e

```shell
$ merge 15920
[pull/15920/local-merge d4663cc6a] Merge #15920: lint: Check that all wallet args are hidden
 Date: Mon Apr 29 20:50:41 2019 +0800
#15920 lint: Check that all wallet args are hidden into master
* fac174e2d lint: Check that all wallet args are hidden (MarcoFalke) (pull/15920/head)

Dropping you on a shell so you can try building/testing the merged source.
Run 'git diff HEAD~' to show the changes being merged.
Type 'exit' when done.

bash-3.2$ git revert 765d5890be
[pull/15920/local-merge c8412b746] Revert "Bugfix: dummywallet: Add -ignorepartialspends to list of ignored wallet options"
 1 file changed, 1 deletion(-)

bash-3.2$ test/lint/check-doc.py
Args used        : 175
Args documented  : 183
Args undocumented: 0
set()
Args unknown     : 8
{'-zmqpubhashtxhwm', '-zmqpubrawtxhwm', '-zmqpubhashtx', '-zmqpubrawblock', '-zmqpubrawblockhwm', '-zmqpubrawtx', '-zmqpubhashblockhwm', '-zmqpubhashblock'}
Traceback (most recent call last):
  File "test/lint/check-doc.py", line 66, in <module>
    main()
  File "test/lint/check-doc.py", line 62, in main
    lint_missing_hidden_wallet_args()
  File "test/lint/check-doc.py", line 57, in lint_missing_hidden_wallet_args
    assert 0, "Please add {} to the hidden args in DummyWalletInit::AddWalletOptions".format(hidden_missing)
AssertionError: Please add {'-avoidpartialspends'} to the hidden args in DummyWalletInit::AddWalletOptions

bash-3.2$ git revert c8412b746
[pull/15920/local-merge c40e287ad] Revert "Revert "Bugfix: dummywallet: Add -ignorepartialspends to list of ignored wallet options""
 1 file changed, 1 insertion(+)

bash-3.2$ test/lint/check-doc.py
Args used        : 175
Args documented  : 183
Args undocumented: 0
set()
Args unknown     : 8
{'-zmqpubhashblockhwm', '-zmqpubrawtxhwm', '-zmqpubhashblock', '-zmqpubhashtx', '-zmqpubrawblockhwm', '-zmqpubrawblock', '-zmqpubrawtx', '-zmqpubhashtxhwm'}
```

**Comment by practicalswift** [comment]
tACK fac174e2d17e06b63aa5eb20b404af00d38db26e

Very nice to have a linter making sure that reviewers never have to think about this ever again :-)

@fanquake Out of curiosity: what `merge` alias/script (`merge 15920` in your the shell session you posted) do you use to check the PR locally? I've written such an alias/script myself for my needs but I'd rather use a less hacky packaged tool if available :-)

**Comment by fanquake** [comment]
@practicalswift It's the [github-merge.py](https://github.com/bitcoin/bitcoin/blob/master/contrib/devtools/github-merge.py) script in `contrib/devtools`.

**Comment by luke-jr** [comment]
@practicalswift Linters are NOT a substitute for proper review!

**Comment by practicalswift** [comment]
@luke-jr No, obviously not. Linters complement proper human review. Ideally they catch errors before any human review takes place.

**Pull request merged**
