### PR TITLE
doc: Change #bitcoin-dev IRC channel to #bitcoin-core-dev

### PR DESCRIPTION
**Pull request by laanwj**
Mention new channel - split off Bitcoin Core project specific development discussion from the general Bitcoin development channel.

### CODE REVIEW

**Comment by paveljanik** [comment]
ACK

**Comment by fanquake** [comment]
ACK

**Comment by kanzure** [comment]
Would be nice to mention #bitcoin-dev for general bitcoin development?

**Comment by laanwj** [comment]
> Would be nice to mention #bitcoin-dev for general bitcoin development?

Maybe, although that's really the domain for other resources (like the wiki, bitcoin.org, etc that refer to the entire network), not our project documentation.

**Comment by jgarzik** [comment]
Avoid prior mistakes:  Write one sentence to describe what is on-topic for the channel.

**Comment by jonasschnelli** [comment]
ACK.
Not sure if it needs a textline of what it on-/off topic (Bitcoin-core-dev sounds after a good topic).

**Comment by dcousens** [comment]
ACK

**Comment by laanwj** [comment]
OK, in `doc/README.md` under resources I've split out 'project-specific development' and 'general bitcoin development'. I'm not sure what is the place to go into more detail about what is on- and off topic, maybe a link in the topic of the channel itself.

**Comment by luke-jr** [comment]
Eh, when did this change? #bitcoin-dev has always been open to discussion of Bitcoin development, including Core, Electrum, etc...

**Pull request merged**
