### PR TITLE
Issue #10542 Signmessage doesn't work with segwit addresses

### PR DESCRIPTION
**Pull request by jakubtrnka**
bitcoin-cli verifymessage was extended to verify signatures against both
bech32 and segwit-p2sh. Class PubkeyConsistencyVisitor has been added
which takes extracted public key as constructor argument and verifies
signatures against all meaningful CTxDestinations.

Signmessage will be implemented in a next step.

### CODE REVIEW

**Comment by luke-jr** [comment]
NACK, it is by design that the deprecated message signature format is not supported for Segwit stuff.

If you want signed messages, please work on coming up with a signature system that addresses the many shortcomings of the old style.

**Comment by sipa** [comment]
@luke-jr I'm torn here.

One the one hand you're right that we should aim to work on an improved standard that can deal with arbitrary scripts rather than just specific single-key addresses.

On the other hand, it does seem like nobody is really working on a standard like that, and the continued lack of standard is doing users a disservice. At the same time it seems other software has already adopted extensions to the old signmessage format.

**Comment by luke-jr** [comment]
There's been quite a bit of discussion on the bitcoin-dev mailing list. I don't think it's fair to say nobody is working on it. And even if that were true, the solution would be for someone who wants signmessage, to begin working on it.

I'm not sure how much of a disservice it is. I can't remember the last time I saw signmessage used for what it actually does - everyone who wants it, seems to be assuming things the signatures *don't* prove.

**Comment by jakubtrnka** [comment]
@luke-jr Ok. I'm not very experienced in development. I wanted to try sth. easy for the first time.

**Comment by kallewoof** [comment]
> On the other hand, it does seem like nobody is really working on a standard like that, and the continued lack of standard is doing users a disservice. At the same time it seems other software has already adopted extensions to the old signmessage format.

Discussion here: https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2018-March/015818.html

**Pull request closed without merging**
