### PR TITLE
Assert cs_main is held when retrieving node state

### PR DESCRIPTION
**Pull request by promag**
Replaces a comment with the actual assertion.

### CODE REVIEW

**Comment by practicalswift** [comment]
@promag This change is already in https://github.com/bitcoin/bitcoin/pull/11226/commits/4c8604e6607114fd06b9be210a25b208e9d64821 which is part of #11226 :-)

**Comment by promag** [comment]
@practicalswift removed `GUARDED_BY`, but I'm keeping the `AssertLockHeld`.

**Comment by TheBlueMatt** [comment]
Fails travis as DoS_Tests calls State() without cs_main.

**Comment by MarcoFalke** [comment]
@promag ping

**Comment by practicalswift** [comment]
Locking added to tests in #11623 :-)

**Comment by MarcoFalke** [comment]
utACK afd5cd588a994ad067862652beaebe78a8d35381

**Comment by TheBlueMatt** [comment]
I dont know if we want to be adding new AssertLockHelds, actually. We should be adding GUARDED_BY annotations as we go, and I think just doing that here may be nice (cause merging them all in one huge #11226 probably isn't gonna happen), but AssertLockHelds dont add much of anything if we're already checking it at compile/travis-time.

**Comment by laanwj** [comment]
@promag Can you add the annotation please?

**Comment by promag** [comment]
Rebased and updated.

**Comment by practicalswift** [comment]
utACK 8f2616cf99d1e0b573f647cd45ee87fba1c969e9

Yay for annotations!

**Comment by promag** [comment]
Adding the annotations breaks the build, which #11226 already takes care of. Rebasing on top of that results only in the assert, which is what was initially.

@laanwj wdyt?

**Comment by TheBlueMatt** [comment]
@promag the annotations are required to be applied recursively. Any function that calls State() must either LOCK(cs_main) prior to the call, or be marked with EXCLUSIVE_LOCKS_REQUIRED(cs_main) itself (and then its callers must LOCK(cs_main)). That's the magic of the new annotations - you get notified by travis for (the simple cases of) missing locks!

**Pull request closed without merging**
