### PR TITLE
build: Bump guix time-machine to unlock riscv64 metal

### LINKED ISSUE #29020: ./contrib/guix/guix-build does not work on riscv64
Steps to reproduce:

```
# dpkg --print-architecture && HOSTS="arm64-apple-darwin" V=1 VERBOSE=1 MAX_JOBS=$(nproc) ./contrib/guix/guix-build 
riscv64
Found macOS SDK at '/bitcoin-core/depends/SDKs/Xcode-12.2-12B45b-extracted-SDK-with-libcxx-headers', using...
Checking that we can connect to the guix-daemon...

Hint: If this hangs, you may want to try turning your guix-daemon off and on
      again.

accepted connection from pid 2870003, user root
make: Entering directory '/bitcoin-core/depends'
make[1]: Entering directory '/bitcoin-core/depends'
make[1]: Leaving directory '/bitcoin-core/depends'
make: Leaving directory '/bitcoin-core/depends'
INFO: Building 92d12f1c8903 for platform triple arm64-apple-darwin:
      ...using reference timestamp: 1696409041
      ...running at most 4 jobs
      ...from worktree directory: '/bitcoin-core'
          ...bind-mounted in container to: '/bitcoin'
      ...in build directory: '/bitcoin-core/guix-build-92d12f1c8903/distsrc-92d12f1c8903-arm64-apple-darwin'
          ...bind-mounted in container to: '/distsrc-base/distsrc-92d12f1c8903-arm64-apple-darwin'
      ...outputting in: '/bitcoin-core/guix-build-92d12f1c8903/output/arm64-apple-darwin'
          ...bind-mounted in container to: '/outdir-base/arm64-apple-darwin'
accepted connection from pid 2872281, user root
accepted connection from pid 2872281, user root
Backtrace:
          18 (primitive-load "/root/.cache/guix/inferiors/4wrulds2lx?")
In guix/ui.scm:
   2324:7 17 (run-guix . _)
  2287:10 16 (run-guix-command _ . _)
In ice-9/boot-9.scm:
  1752:10 15 (with-exception-handler _ _ #:unwind? _ # _)
In guix/store.scm:
    672:3 14 (guix-environment* _)
In ice-9/boot-9.scm:
  1752:10 13 (with-exception-handler _ _ #:unwind? _ # _)
In guix/store.scm:
   659:37 12 (thunk)
   1298:8 11 (call-with-build-handler _ _)
   1298:8 10 (call-with-build-handler #<procedure 3f812c0ea0 at gui?> ?)
In guix/status.scm:
    839:4  9 (call-with-status-report _ _)
In guix/scripts/environment.scm:
  1158:11  8 (_)
In guix/store.scm:
  2168:25  7 (run-with-store #<store-connection 256.99 3f851f2af0> _ ?)
In guix/scripts/environment.scm:
    869:8  6 (_ _)
In gnu/build/linux-container.scm:
   397:16  5 (call-with-container (#<<file-system> device: "none?> ?) ?)
   239:15  4 (run-container "/tmp/guix-directory.GcTuOV" (#<<fil?> ?) ?)
In guix/build/syscalls.scm:
  1114:21  3 (_ 2114060305)
In unknown file:
Exception thrown while printing backtrace:
In procedure primitive-call-ip: Wrong type argument in position 1 (expecting PRIMITIVE_P): #<procedure 3f82490420 (_ _ _ _ _ _)>

ice-9/boot-9.scm:1685:16: In procedure raise-exception:
Wrong type (expecting exact integer): #f
```

### PR DESCRIPTION
**Pull request by maflcko**
Closes https://github.com/bitcoin/bitcoin/issues/29020

### CODE REVIEW

**Comment by fanquake** [comment]
> Is there an easy way to print all affected/changed/bumped dependencies in the Bitcoin Core build graph?

A quick check is to compare the manifests of master vs the change, i.e:
```bash
diff guix-build-3695ecbf680a/var/profiles/x86_64-linux-gnu/manifest guix-build-fa87a2072b91/var/profiles/x86_64-linux-gnu/manifest 
60c60
<       "0.67"
---
>       "0.68"
62c62
<       "/gnu/store/4ck57lp0wdcslrc106c649yfm3fclmsl-moreutils-0.67")
---
>       "/gnu/store/09jzmmg2h8cxf75imk0r1c3j0cx20zkn-moreutils-0.68")
171c171
<       "/gnu/store/zjsygsszp9v5i5gz8kqxxfrl50xwzl44-git-minimal-2.41.0"
---
>       "/gnu/store/w6bbaal18axhsyy3r418isll33qzz2jb-git-minimal-2.41.0"
186c186
<       "/gnu/store/ch86qkh3qz2701wy7p1r4s7r7i2jyqjl-python-lief-0.13.2")
---
>       "/gnu/store/lkq1x15862rgch435k6cici1yi8anwas-python-lief-0.13.2")
190c190
<       "/gnu/store/6a7rbkaisfwfz54k8b90ns54kra314cp-x86_64-linux-gnu-toolchain-10.5.0"
---
>       "/gnu/store/my917igzlinspc0fp6zl827nzmyl4wgb-x86_64-linux-gnu-toolchain-10.5.0"
199c199
<           "/gnu/store/6308la3gb2r344sp8prvk058qvzq14lq-glibc-cross-x86_64-linux-gnu-2.27"
---
>           "/gnu/store/glkb9x9h6s0zxia3ywd1y55jg80w1ai5-glibc-cross-x86_64-linux-gnu-2.27"
202c202
<               "6.1.61"
---
>               "6.1.67"
204c204
<               "/gnu/store/av2i6y23kmrnhgfqwhgmh24f12l2qvvv-linux-libre-headers-cross-x86_64-linux-gnu-6.1.61")))
---
>               "/gnu/store/v80d0b41laxz2i6mhik0nz8ikya0b6hi-linux-libre-headers-cross-x86_64-linux-gnu-6.1.67")))
210c210
<           "/gnu/store/g5g7j5xlw132s1rbabx7h1yvgn321985-gcc-cross-x86_64-linux-gnu-10.5.0")
---
>           "/gnu/store/bjrf468hxqnzymddr6xxs3vairk46ypr-gcc-cross-x86_64-linux-gnu-10.5.0")
214c214
<           "/gnu/store/jn08byk4gwcd1k8xilcm2x7z660l3lfd-glibc-cross-x86_64-linux-gnu-2.27-static"
---
>           "/gnu/store/fncrsxpss8l8aj4qvmymkkksm6bb4ar4-glibc-cross-x86_64-linux-gnu-2.27-static"
218,219c218,219
<                "6.1.61"
<                "/gnu/store/av2i6y23kmrnhgfqwhgmh24f12l2qvvv-linux-libre-headers-cross-x86_64-linux-gnu-6.1.61")))
---
>                "6.1.67"
>                "/gnu/store/v80d0b41laxz2i6mhik0nz8ikya0b6hi-linux-libre-headers-cross-x86_64-linux-gnu-6.1.67")))
225c225
<           "/gnu/store/xsl44lhvxircf1ffqh3iyrrzgprf57cx-gcc-cross-x86_64-linux-gnu-10.5.0-lib")))
---
>           "/gnu/store/yjqqr10hl10aqjmkdsr3dzvqsw0h6nkw-gcc-cross-x86_64-linux-gnu-10.5.0-lib")))
```

Depending on how much you want to see, you could also do something with `guix graph`: https://guix.gnu.org/manual/en/html_node/Invoking-guix-graph.html.

**Review by fanquake — APPROVED** [review]
ACK fa87a2072b91c591d2714bc70488b395c22df95d

Guix build (aarch64):
```bash
d137d8dc94b3d734965b7e50fac273f704e122f969430e1b43bfe21c9af31bbe  guix-build-fa87a2072b91/output/aarch64-linux-gnu/SHA256SUMS.part
42d66d0daf6067a74c3ba4e55c012712ae5cca02c9123ed3ef7fd9a8f09c16d4  guix-build-fa87a2072b91/output/aarch64-linux-gnu/bitcoin-fa87a2072b91-aarch64-linux-gnu-debug.tar.gz
3ccda6af99c1dd4b54533d073dca82d5f252759cede55a335220065dfe24ee7c  guix-build-fa87a2072b91/output/aarch64-linux-gnu/bitcoin-fa87a2072b91-aarch64-linux-gnu.tar.gz
ea3a9d6ef4ee4a83ad2aa95b667a38473c971e74c8ec599a353a16678642c211  guix-build-fa87a2072b91/output/arm-linux-gnueabihf/SHA256SUMS.part
a4d41469855a143a16b591b78ce04842ed597fdb50f26b5c4ee97aca137275ee  guix-build-fa87a2072b91/output/arm-linux-gnueabihf/bitcoin-fa87a2072b91-arm-linux-gnueabihf-debug.tar.gz
97f91c7c3776d218e0e4b9c3b0d7fcb9e47aef9414c12874f390ecd42538baf7  guix-build-fa87a2072b91/output/arm-linux-gnueabihf/bitcoin-fa87a2072b91-arm-linux-gnueabihf.tar.gz
0b06e5eb3c0c67f075406cd568e6afb45914fff4c5135b597639d869acb4b93c  guix-build-fa87a2072b91/output/arm64-apple-darwin/SHA256SUMS.part
4ee72078a82351ea81cb9ad7cbccc0c30a0420f16da5efd9121ffa7f69744ea3  guix-build-fa87a2072b91/output/arm64-apple-darwin/bitcoin-fa87a2072b91-arm64-apple-darwin-unsigned.tar.gz
c3204e997966993bed355072ef4ea6e8b4708d80f67d53ce1d01a0398e4a6fee  guix-build-fa87a2072b91/output/arm64-apple-darwin/bitcoin-fa87a2072b91-arm64-apple-darwin-unsigned.zip
764c7de0291c3caa15584bc730ad7166cc87d44526a460da35f43831cf342743  guix-build-fa87a2072b91/output/arm64-apple-darwin/bitcoin-fa87a2072b91-arm64-apple-darwin.tar.gz
b5325393a05c4452c6695103a33bcfa221df48c65df0cccbf8d5eadba58b181f  guix-build-fa87a2072b91/output/dist-archive/bitcoin-fa87a2072b91.tar.gz
d8ba9241a6058116eabe017a2fa9c7aa62430de33aa875022a79dadc3dc8478b  guix-build-fa87a2072b91/output/powerpc64-linux-gnu/SHA256SUMS.part
bcd1aeac764f5fe9485f6a84d1e417bb066bcc7c3973bcb83802a999964b8de2  guix-build-fa87a2072b91/output/powerpc64-linux-gnu/bitcoin-fa87a2072b91-powerpc64-linux-gnu-debug.tar.gz
ad345dddbea6285cc31ac4a295ae115cf41b2cc2e2315914aef32206cad10b4e  guix-build-fa87a2072b91/output/powerpc64-linux-gnu/bitcoin-fa87a2072b91-powerpc64-linux-gnu.tar.gz
5ee29851afae46e124cbf1bc11027e876d789509a73da7e553e89bdbb2ecd4d0  guix-build-fa87a2072b91/output/powerpc64le-linux-gnu/SHA256SUMS.part
30d944c57922d75e5d530c98daa5d472d8ae9e4d281270d23f5e8389d9ac6353  guix-build-fa87a2072b91/output/powerpc64le-linux-gnu/bitcoin-fa87a2072b91-powerpc64le-linux-gnu-debug.tar.gz
276f0db360cecad6dc9f58c738f82f3499bd7f360c99711165efcaf2ef26c30a  guix-build-fa87a2072b91/output/powerpc64le-linux-gnu/bitcoin-fa87a2072b91-powerpc64le-linux-gnu.tar.gz
62c84dbca74e6f3f0a8434437e885eef96c8faf1df7cd966f380323ea87d0bd3  guix-build-fa87a2072b91/output/riscv64-linux-gnu/SHA256SUMS.part
86cb0971a5151fc922c2b627e8860d550fd453cc909b017b2f293dd388b16717  guix-build-fa87a2072b91/output/riscv64-linux-gnu/bitcoin-fa87a2072b91-riscv64-linux-gnu-debug.tar.gz
8e227432a0d3542855293592c0a448f3af3bd6215da00d63586f082e4ea26dba  guix-build-fa87a2072b91/output/riscv64-linux-gnu/bitcoin-fa87a2072b91-riscv64-linux-gnu.tar.gz
b276c06a5b3e04dc39726147fda30919af97ca6c843809aeeeb3e0d760e24917  guix-build-fa87a2072b91/output/x86_64-apple-darwin/SHA256SUMS.part
e41219c0cd0fedeb8646ba866a779112594e5c608542bb5530cd0e94184bcba9  guix-build-fa87a2072b91/output/x86_64-apple-darwin/bitcoin-fa87a2072b91-x86_64-apple-darwin-unsigned.tar.gz
af186305d4b09094f19976701071861d7fcaf0b187bb957825ecb7e2bcffb30f  guix-build-fa87a2072b91/output/x86_64-apple-darwin/bitcoin-fa87a2072b91-x86_64-apple-darwin-unsigned.zip
fabf02c5fc54013acb2dacfff63b252a402e78991e4f8784de5ccbb9ed5e4fc0  guix-build-fa87a2072b91/output/x86_64-apple-darwin/bitcoin-fa87a2072b91-x86_64-apple-darwin.tar.gz
a722a013353047f4046dc5ddf0856dfd1785a976e625b33d574bd9a84b1358ba  guix-build-fa87a2072b91/output/x86_64-linux-gnu/SHA256SUMS.part
516f926f87caa2f1b5069d96c46756a7bcbdb81a05b1886c3a32fd7b679179a3  guix-build-fa87a2072b91/output/x86_64-linux-gnu/bitcoin-fa87a2072b91-x86_64-linux-gnu-debug.tar.gz
f2dd02a2511dcb5747a101c3aeecd58142d3f109c1ac9e89da90ef0703496055  guix-build-fa87a2072b91/output/x86_64-linux-gnu/bitcoin-fa87a2072b91-x86_64-linux-gnu.tar.gz
150cc09da44026c02a3b52b6fb92d7a5f684653c924d6166003787d609afbea4  guix-build-fa87a2072b91/output/x86_64-w64-mingw32/SHA256SUMS.part
9b369e281123a99568f52f2e82c995a84bbddf3632514c6141c0ee583ff91926  guix-build-fa87a2072b91/output/x86_64-w64-mingw32/bitcoin-fa87a2072b91-win64-debug.zip
03fb87437fae6146c561512ea9c15c938bed2aa90445c7823c1813bd36683203  guix-build-fa87a2072b91/output/x86_64-w64-mingw32/bitcoin-fa87a2072b91-win64-setup-unsigned.exe
fe24419fd384b3c9d5729041e9ea685d9d7c672db92587016a8b44631ed5254c  guix-build-fa87a2072b91/output/x86_64-w64-mingw32/bitcoin-fa87a2072b91-win64-unsigned.tar.gz
e651b8f174253cb8dc49aefff3f3d5c3d99a63c0b8f38b9874e2e0b5a8e58810  guix-build-fa87a2072b91/output/x86_64-w64-mingw32/bitcoin-fa87a2072b91-win64.zip
```

**Comment by fanquake** [comment]
> Looks like this fails with:

Given that the problem here is compiling cctools on RISC-V, I think this will ultimately be solved by switching to LLVM/LLD (#21778).

**Review by sedited — COMMENTED** [review]
Post-merge ACK, reproduced @fanquake's hashes and ran into the same macOS build issue.

**Pull request merged**
