### PR TITLE
mining: Optimise for typical mining use with blockmaxsize

### PR DESCRIPTION
**Pull request by luke-jr**

### CODE REVIEW

**Comment by morcos** [comment]
Can you quantify the benefit of doing this?  I don't think we should be keeping around extra fields without being sure its really worth it.  Will any significant number of miners use this instead of blockmaxweight?  In any case this is redundant with blockmaxweight until segwit is activated, so we should defer discussion of adding it until then.

**Comment by luke-jr** [comment]
All miners should be using blockmaxsize, not blockmaxweight, right now and until some future change makes blocks larger than 1 MB sane. It's not redundant on testnet, and if it were redundant, we should remove the weight stuff, not size...

**Comment by morcos** [comment]
@luke-jr I don't think we're concerned about block size on test net.

By quantifying the benefit what I meant was miners can already use blockmaxsize if they want to (although I would recommend they not), all this pull does is cache the necessary calculations.  Can you quantify the benefit of doing that instead of the status quo?

**Comment by luke-jr** [comment]
Miners should not be recommended to disable blockmaxsize, since size is currently the critical constraining resource on the network. It's true that switching to blockmaxweight in 0.13.0 won't have any practical difference on mainnet, but when segwit gets activated, it will, and it is TBD whether producing blocks larger than 1 MB will be responsible at that time.

**Comment by f139975** [comment]
@luke-jr: please provide a description, when opening a pull request.

To quote [CONTRIBUTING.md#contributor-workflow](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#contributor-workflow):

> The body of the pull request should contain enough description about what the patch does together with any justification/reasoning.

**Comment by luke-jr** [comment]
#8559 says 576MiB per day = ~17GB per Month is too high; if this is correct, it will be important for miners to set a maxblocksize of at most 2 MB.

**Comment by luke-jr** [comment]
This should probably be tagged for 0.13.1...

**Comment by morcos** [comment]
I recently looked into this because I was worried about the default (passing no options) still using size accounting and this being potentially slow after segwit activates.  I tried to estimate how slow this might be by setting a blockmaxsize=950000 and blockmaxweight=4000000 which should cause the mining algorithm to have to trace each package adding up size all the way through the mempool.  I found that this was only slightly slower than just setting blockmaxweight.  12ms average vs 10.5ms.

I believe we should not do any extra work to support size accounting at this point, but that it is fine to leave it in the code and not a significant performance concern until we can all agree that there is no reason to keep the extra complication around.

**Comment by sipa** [comment]
@morcos Thanks for benchmarking this - always better to have actual numbers.

**Pull request closed without merging**
