### PR TITLE
doc: Fix datadir path in 0.18.0 release notes

### PR DESCRIPTION
**Pull request by ch4ot1c**

### CODE REVIEW

**Comment by MarcoFalke** [comment]
unsigned ACK 0507cbc9376fc7c2effc29284d8a4df1f68f09dd

**Comment by ryanofsky** [comment]
`~bitcoin` refers to the home directory of the bitcoin user, so I think the documentation is correct as is, and this change just makes it more ambiguous. But if people are less familiar with multi-user systems than they used to be and `~bitcoin` is confusing, maybe this change is an improvement. I just don't think it's a "fix"

**Comment by MarcoFalke** [comment]
Thanks for the input. Makes sense, so closing this for now.

**Comment by laanwj** [comment]
I also think there's limited added value to updating historical release notes, save for serious things such as missing credits or dangerous suggestions. In which case you'd also want to update them on the bitcoincore.org site. But for something that very slighly improves readability I think it's not worth it.

**Comment by ch4ot1c** [comment]
Gotcha - this was the only place I found this usage (`grep -nr "\~bitcoin" .`), so it was just a smell. Learned something today!

Noted your advice on nitting release notes.

**Pull request closed without merging**
