### PR TITLE
Bugfix: test/functional/rpc_psbt: Remove check for specific error message that depends on uncertain assumptions

### PR DESCRIPTION
**Pull request by luke-jr**
When converttopsbt is called with a signed transaction, it either fails with "TX decode failed" if one or more inputs were segwit, or "Inputs must not have scriptSigs and scriptWitnesses" otherwise.
Since no effort is made by the test to ensure the inputs are segwit or not, avoid checking the exact message used.
The error code is still checked to ensure it is of the correct kind of failure.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Fixes: #13738

**Comment by instagibbs** [comment]
didn't know you could give an empty string

utACK  https://github.com/bitcoin/bitcoin/pull/14818/commits/c87fc71f7e9316bcc0653cd86c50177424b5b1f9

**Comment by luke-jr** [comment]
I'm not sure it fixes #13738. Isn't that a "no exception thrown" issue? The bug fixed here is that it's throwing a *different* exception...

**Comment by MarcoFalke** [comment]
@luke-jr Right

**Comment by achow101** [comment]
utACK c87fc71f7e9316bcc0653cd86c50177424b5b1f9

**Pull request merged**
