### PR TITLE
[travis] add zmq python module, re-enable zmq rpc tests

### PR DESCRIPTION
**Pull request by jonasschnelli**
Travis can't run the zmq tests because its missing the python zmq module.
https://travis-ci.org/bitcoin/bitcoin/jobs/80832394#L3588

**This would install the python zmq module and re-enable the rpc tests**.
Disabling zmq tests on travis would be another solution, but IMO we should maximize the CI test coverage.

Not sure if this is a good solution (@theuni?).

Let's discuss this before merging.

### CODE REVIEW

**Comment by sipa** [comment]
ACK

**Comment by jgarzik** [comment]
concept ACK

**Comment by btcdrak** [comment]
Looks like Travis timed out on a couple of jobs.

**Comment by dcousens** [comment]
ACK

**Comment by jonasschnelli** [comment]
Somehow even if travis successfully installs `libzmq3` and `python-zmq`, the rpc test can't connect over zmq with bitcoind.
Still try to figure out why...

**Comment by theuni** [comment]
Does this work locally? It's not clear to me what needs to be native and what needs to be per-arch.

**Comment by jonasschnelli** [comment]
@theuni 
The zmq_test.py (RPC test) works prefect locally. Tested on OSX/Debian and Ubuntu.
The `zmq_test.py` changes within this PR are for debugging purposes. 
I can only encounter the problem in Travis builds.
It looks like that zmq tcp:// connection does not work in travis. Even after installing python-zmq. Also my solution (`sudo rm -f /etc/apt/sources.list.d/travis_ci_zeromq3-source.list;`) looks after a workaround hack.
Maybe you have a different approach to get the zmq_test.py running on travis.

**Comment by jonasschnelli** [comment]
@theuni: Any idea how we could fix this? Having CI tests for the ZMQ would be important IMO otherwise the risks are high that things break without noticing.

**Comment by theuni** [comment]
@jonasschnelli I need to spend a bit of time learning about the intricacies of zmq/python here. But I'll try to track down the issue.

**Comment by theuni** [comment]
@jonasschnelli This fixes: https://github.com/theuni/bitcoin/commit/05a7243678e97b3944c5ceb23c4b05c57fb9c42f . Problem was the old libzmq that the pyzmq was using. Installing the newer pyzmq from a ppa pulls in newer versions of both.

**Comment by jonasschnelli** [comment]
Added @theuni commit.
Travis is happy now.
This would add CI coverage of the ZMQ feature.

**Comment by laanwj** [comment]
ACK when travis is green

**Pull request merged**
