### PR TITLE
[23.2] Backports for rc1

### PR DESCRIPTION
**Pull request by fanquake**
Final backports for `rc1`. Currently:
* https://github.com/bitcoin/bitcoin/pull/27608 (not a clean cherry-pick)
* https://github.com/bitcoin/bitcoin/pull/27610 (second commit is not clean)

### CODE REVIEW

**Comment by Sjors** [comment]
utACK ce8f812b0ac0905c26edd826c57886a08079b4a7

**Comment by fanquake** [comment]
Added #27610, as well as all other changes required to cut an rc1.

> Are you going to add https://github.com/bitcoin/bitcoin/pull/27610 to this?

Yes. Note that the second commit from that PR is not a clean cherry-pick.

**Comment by achow101** [comment]
ACK a26ff204f0f0355749a1b61136437623b325f8fb

Diffs match as expected

**Comment by dergoegge** [comment]
ACK a26ff204f0f0355749a1b61136437623b325f8fb

**Comment by ajtowns** [comment]
utACK a26ff204f0f0355749a1b61136437623b325f8fb

**Comment by Sjors** [comment]
I didn't check the #27608 backport (nor the original). I did check #27608, the other commits in this PR and the release notes, which look good to me.

**Pull request merged**
