### PR TITLE
[test] Avoid potential NULL pointer dereference in addrman_tests.cpp

### PR DESCRIPTION
**Pull request by practicalswift**

### CODE REVIEW

**Comment by luke-jr** [comment]
utACK

**Comment by MarcoFalke** [comment]
This is already checked 5 lines above, no?

**Comment by practicalswift** [comment]
@MarcoFalke `BOOST_CHECK(info1, …)` (as opposed to `BOOST_REQUIRE(info1, …)`) won't stop the execution and ...

    if (info2)
          BOOST_CHECK(info2->ToString() == info1->ToString());		

... will be run regardless of the code path taken here ...

    if (info1)
        BOOST_CHECK(info1->ToString() == "250.1.2.1:8333");

... right? :-)

**Comment by MarcoFalke** [comment]
ACK afab9f47f619120f22e5d586d417c71551f8d000

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/commit/afab9f47f619120f22e5d586d417c71551f8d000

**Pull request merged**
