### PR TITLE
Update chain transaction statistics

### PR DESCRIPTION
**Pull request by sipa**

### CODE REVIEW

**Comment by sipa** [comment]
Alternatively, we can set this to the assumevalid height's stats, and exaggerate the expected tx rate afterwards. That can somewhat account for the higher validation time past assumevalid.

**Comment by laanwj** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/10986/commits/b1973d6181eacfaaf45effb67e0c449ea3a436b8

**Comment by jonasschnelli** [comment]
utACK b1973d6181eacfaaf45effb67e0c449ea3a436b8 (haven't verified the number of transaction up to the new block).

**Comment by promag** [comment]
utACK b1973d6.

**Comment by fanquake** [comment]
utACK b1973d6

**Pull request merged**
