### PR TITLE
[tests] Remove unused imports (script.OP_0 and script.sha256)

### PR DESCRIPTION
**Pull request by practicalswift**
Remove unused imports (`script.OP_0` and `script.sha256`).

### CODE REVIEW

**Comment by MeshCollider** [comment]
The typo fix is wrong unfortunately, should be 'a' (because 'one' effectively starts with a 'w')

**Comment by fanquake** [comment]
Agree with @MeshCollider that typo fix isn't correct.

**Comment by practicalswift** [comment]
@MeshCollider @fanquake Thanks for reviewing! Typo fix removed :-)

**Comment by practicalswift** [comment]
The build error seems unrelated.

**Comment by MeshCollider** [comment]
Yeah Concept ACK for removing the unused import

**Comment by jnewbery** [comment]
There are many instances in the test/functional/test_framework directory of unused imports, wildcard imports, names being imported indirectly through wildcard imports, imports on the same line, imports not in PEP8 ordering, imports not being sorted, etc.

I'd rather have a single PR that fixes all of those nits, rather than tackle it file-by-file.

That said, utACK c7e0abe1904bac179771985c5223a323a17f97f5 if people disagree with my preferred approach.

**Comment by MarcoFalke** [comment]
Agree with @jnewbery if a fix is reasonable to do for the whole project in a single commit, that should be preferred. However, if that is not feasible for whatever reason or not worth it, nothing should be touched. (Unless you need to change the line anyway.)

**Pull request closed without merging**
