### PR TITLE
test: Reliably don't start itself (lint-all.py runs all tests twice)

### PR DESCRIPTION
**Pull request by martinus**
When running `./test/lint/lint-all.py`, the script runs all tests but
also calls itself because the comparison with `__file__` doesn't work.

Comparing resolved paths gives reliable comparison, and lint-all.py doesn't call itself any more

### CODE REVIEW

**Comment by MarcoFalke** [comment]
It doesn't run twice in CI, right? For example, looking at https://cirrus-ci.com/task/4523243527733248?logs=lint#L849 I can only find the error once.

**Comment by martinus** [comment]
Ah, in `06_script.sh` lint-all.py is started with `test/lint/lint-all.py`, but I am starting it locally with `./test/lint/lint-all.py`. I think the leading `./` is the difference

**Comment by laanwj** [comment]
May I propose a different solution: to rename the launcher so that it doesn't match the glob. This is 100% reliable and imo more elegant.

**Comment by MarcoFalke** [comment]
Yeah, could rename to `all-lint.py` and then also address https://github.com/bitcoin/bitcoin/pull/24982#discussion_r859456117 while touching this file?

**Comment by laanwj** [comment]
Code review ACK f26a496dfd0a7ce3833a10075027d7d5b0345e32

**Review by DaniloRoque501 — COMMENTED** [review]
martinus:2022-06-fix-lint-all-starting-itself

**Review by jonatack — COMMENTED** [review]
Post-merge ACK

**Pull request merged**
