### PR TITLE
[0.12.2] qa Backports

### PR DESCRIPTION
**Pull request by maflcko**
@btcdrak

### CODE REVIEW

**Comment by MarcoFalke** [comment]
I left out fa8cd46  because I didn't feel like solving conflicts. Extended  tests seem to test pass locally.

**Comment by laanwj** [comment]
Probably we want to do this  when the Python 3 transition is complete?

**Comment by MarcoFalke** [comment]
@laanwj I am not sure if it makes sense to do the py3 switch as part of this pull because I am waiting for travis to switch to trusty first. Then the question arises if we switch the 0.12 branch to trusty as well. Regardless of how we decide, I think the py3 switch for 0.12 should be a separate pull.

**Comment by MarcoFalke** [comment]
Extended tests pass.

**Pull request merged**
