### PR TITLE
[qt] sync-overlay: Don't block during reindex

### PR DESCRIPTION
**Pull request by maflcko**
As I understand this, the "`fHeader`-shortcut" in clientmodel will fire too much during reindex, thus making the gui freeze. The reason for this shurtcut is to make sure the gui always knows the height of the best header. Though, I think it is not required for the gui to have this knowledge (after all it is just a warning dialog) and an approximate display is just fine.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
I think the constant upcounting "Number of blocks left" is confusing (even with the `~`). I prefer to keep it "unknown" until we have synced the headers chain.

**Comment by MarcoFalke** [comment]
Done

**Comment by laanwj** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/8821/commits/faa4de2a2ac2eb9bb6a419940da83fa898d16a3c

**Comment by jonasschnelli** [comment]
Tested ACK fa85e860a9261e6c585ec40e67845fa93a20c6e7

**Comment by fanquake** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/8821/commits/faa4de2a2ac2eb9bb6a419940da83fa898d16a3c

**Pull request merged**
