### PR TITLE
Python3 fixup

### PR DESCRIPTION
**Pull request by jnewbery**
security-check.py and symbol-check.py were broken by #11881. Fix them.

### CODE REVIEW

**Comment by jnewbery** [comment]
cc @ken2812221

**Review by ken2812221 — APPROVED** [review]
Tested ACK f50975b

**Comment by practicalswift** [comment]
utACK f50975b13667c002ebad871b140bcea4f09d0742

**Comment by jamesob** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/12829/commits/f50975b13667c002ebad871b140bcea4f09d0742

**Comment by hkjn** [comment]
utACK f50975b.

LGTM!

**Pull request merged**
