### PR TITLE
Document RPC method aliasing

### PR DESCRIPTION
**Pull request by ryanofsky**
Suggested by @Sjors in https://github.com/bitcoin/bitcoin/pull/11536#issuecomment-372820660

### CODE REVIEW

**Comment by Sjors** [comment]
Concept ACK. Ideally there would also be some comment next to each alias in places like `CRPCCommand commands[]`, but apparently that's non trivial.

**Comment by ryanofsky** [comment]
> Ideally there would also be some comment next to each alias in places like CRPCCommand commands[]

What would the comment say, and why would it be helpful? The only non-obvious behavior I can think of regarding aliases is that they are omitted from the command listing in help text, and this doesn't seem like a relevant fact to mention in the middle of command registration.

**Review by randolf — APPROVED** [review]

**Comment by PierreRochard** [comment]
ACK 4c317d89e9d980328028ff01cd9a0465cc22bb7e

**Comment by laanwj** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/12700/commits/4c317d89e9d980328028ff01cd9a0465cc22bb7e. This is exactly the behavior that is desirable for deprecating/renaming RPCs, but needs to be documented.

**Pull request merged**
