### PR TITLE
tests: Drop variadic macro

### LINKED ISSUE #13456: Variadic macro in mempool_tests.cpp breaking MSVC build
The use of three macros with variadic arguments was added to src/test/mempool_test.cpp in https://github.com/bitcoin/bitcoin/commit/f77e1d34fd5f17304ce319b5f962b8005592501a. 

The three macros below generate a compiler error with MSVC.

`#define MK_OUTPUTS(amounts...) std::vector<CAmount>{amounts}`
`#define MK_INPUTS(txs...) std::vector<CTransactionRef>{txs}`
`#define MK_INPUT_IDX(idxes...) std::vector<uint32_t>{idxes}`

The easy fix is to add a ',' after the named argument as per:

`#define MK_OUTPUTS(amounts,...) std::vector<CAmount>{amounts}`
`#define MK_INPUTS(txs,...) std::vector<CTransactionRef>{txs}`
`#define MK_INPUT_IDX(idxes,...) std::vector<uint32_t>{idxes}`

I don't know if that will break any other compilers.

If I had a spare 198 Swiss Francs I'd buy the C standard and check which is the correct approach, https://www.iso.org/standard/57853.html, but I don't.

### PR DESCRIPTION
**Pull request by maflcko**
The C++11 constructor of `std::vector` that takes an initializer list, is not `explicit`. Thus, the macro is not required and can be dropped.

Hopefully fixes #13456

### CODE REVIEW

**Comment by MarcoFalke** [comment]
@sipsorcery Would you mind testing, since I don't have a MSVC?

**Comment by practicalswift** [comment]
Concept ACK

**Comment by MarcoFalke** [comment]
> utACK (msvc).

untested (ut) or tested? A tested ack is always preferred ;)

**Comment by sipsorcery** [comment]
@MarcoFalke sorry should have been a tested ACK. Compiled the PR with msvc and successfully ran the test_bitcoin.exe.

**Comment by laanwj** [comment]
utACK faf52f953b47aac6a39892b037eaa3f08d46b655

**Pull request merged**
