### PR TITLE
gui: Make Bitcoin Core logo pure black

### PR DESCRIPTION
**Pull request by maflcko**
This normalized the Bitcoin Core icon branding for consistency.
* Our website has a black theme
* Our GitHub, Twitter, Snap Store and other media channels have the black logo (https://twitter.com/bitcoincoreorg , https://snapcraft.io/bitcoin-core , ... )

Todo:

* [ ] Restore the vibrant colors for each test chain
* [ ] Generate the mac icon (help needed)

### CODE REVIEW

**Comment by molxyz** [comment]
I'm not sure if this is a good idea. It's my fav color but I have come across someone's comment that it makes Bitcoin Core look like "Nazi", whatever that means. If we could give users a choice of a few colors for the gui, I think it would be better.

**Comment by jamesob** [comment]
Concept ACK

**Comment by michaelfolkson** [comment]
Concept ACK

**Comment by jonasschnelli** [comment]
General concept ACK though we need to visually compare and eventually optimize.

**Comment by laanwj** [comment]
~0, I'm fine with the orange color tbh, I don't see a strong reason to change this, will cause more drama and complaining and bikeshedding for no good reason, and seems it even has been Godwin'd already …

**Comment by jnewbery** [comment]
concept ACK

**Comment by practicalswift** [comment]
Concept ACK

**Comment by promag** [comment]
Maybe also list other pages that needs to be updated if this goes forward, like https://github.com/bitcoin-core.

I like both, maybe fuse both in a tiger pattern..

**Comment by hebasto** [comment]
I like the current orange color branding. There is another way to achieve consistency: change icons on the website, GitHub, Twitter etc.

**Comment by Sjors** [comment]
I'm not a fan of changing orange. You could even argue in favor of using a different color, to distinguish software from the coin. The Bitcoin Core software (black) works on the coin Bitcoin (orange) and the coin Bitcoin testnet (green).

As a first step though, you could introduce a single SVG from which we derive the other images.

**Comment by emilengler** [comment]
I agree with Sjors.
The current colors which indicate the chain are perfect and I have no problems with the orange one.
Concept NACK because of the reasons above

**Comment by instagibbs** [comment]
concept NACK for the same "it's showing what chain is running" reasons

**Comment by luke-jr** [comment]
The orange logo is for Bitcoin itself, not specific to Bitcoin Core.

I do like the idea of Bitcoin Core getting its own logo, but I'm not sure just making it black is a good one.

Note that simply replacing the Bitcoin icon isn't sufficient either - systems expect the generic Bitcoin icon installed as-is, even if we have an application-specific icon to add. (I probably have code in Knots to address this discrepancy should a Core logo move forward.)

> The current colors which indicate the chain are perfect

A black logo doesn't mean we can't use other colours for non-mainnet.

**Comment by emilengler** [comment]
@luke-jr Bitcoin Core already has it's own logo iirc.
You should see a small gradient different than other logos.
See [here](https://raw.githubusercontent.com/bitcoin/bitcoin/master/src/qt/res/icons/bitcoin.png) and [here](https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Bitcoin.svg/1024px-Bitcoin.svg.png)

The first one is the Bitcoin Core one

**Comment by Sjors** [comment]
Renewed proposal in https://github.com/bitcoin-core/gui/issues/89

**Pull request closed without merging**
