### PR TITLE
p2p: Remove dead service bits code

### LINKED ISSUE #10993: Return service bits 6 and 8 on Aug 1, 2018
#10982 started disconnecting service bits 6 and 8 until aug 1, 2018, the code to do so should be removed on or after that date.

### PR DESCRIPTION
**Pull request by maflcko**
Seems fine to remove for the upcoming 0.17 release

Fixes #10993

### CODE REVIEW

**Comment by theuni** [comment]
I think this is premature. Since it was shipped in 15.0, we need to consider this behavior locked-in until August.  We can't practically re-use the bits until then anyway, and we still don't want to remain connected to any peer with them enabled for whatever reason.

Also, I assume the ```1 << 5``` is still relevant.

**Comment by MarcoFalke** [comment]
Good point about keeping it in the code for now to make clear that they are taken. Guess there is no rush in merging this.

**Comment by Sjors** [comment]
Isn't one needed for Bitcoin Cash nodes?

If it can be done without side-effects, it would be a nice gesture to at least deprecate it.

**Comment by MarcoFalke** [comment]
Needs rebase. No need to keep open; Closing for now.

**Comment by laanwj** [comment]
utACK fa4bf92be9420919c74cdde9a973f7327d01ac88

**Comment by sipa** [comment]
utACK fa4bf92be9420919c74cdde9a973f7327d01ac88

**Comment by laanwj** [comment]
utACK fa4bf92be9420919c74cdde9a973f7327d01ac88

**Pull request merged**
