### PR TITLE
doc: Add note on deleting past-EOL release branches

### PR DESCRIPTION
**Pull request by maflcko**
This is being done for years now, but wasn't documented.

Some reasons to do it:
* Backports to those branches are unlikely to be tested both on CI (since it is often fragile and broken for stale branches) and by users (since those users likely don't exist). If a user exists, they are better off backporting any fixes they need from the last still-supported branch and test them on their own infrastructure.
* Community support of those branches is still possible, though this will need to be done in another project to relieve the burden on this project.
* All release tags will remain, so no historic code is lost.

### CODE REVIEW

**Comment by laanwj** [comment]
Concept ACK

**Review by jonatack — COMMENTED** [review]
ACK fa68489ab16a2618d906beff5ecaa598d6faface

**Review by hebasto — COMMENTED** [review]
ACK fa38d98aa98bcf34b5b59ff894bbb5da67355b29

**Comment by fanquake** [comment]
Concept ACK

**Review by fanquake — APPROVED** [review]
ACK fa38d98aa98bcf34b5b59ff894bbb5da67355b29 - I think this is fine as-is.

**Pull request merged**
