### PR TITLE
Minor changes to dbwrapper to simplify support for other databases

### PR DESCRIPTION
**Pull request by laanwj**
During my [experiment with using LMDB as database](https://github.com/laanwj/bitcoin/tree/2016_04_mdb) I came across these database-agnostic changes to dbwrapper which make it easier to support other databases, or are small common-sense (I think) cleanups at most:
- Pass parent CDBWrapper into CDBBatch and CDBIterator instead of obfuscation key (in the case of lmdb the batch needs to know about the database, to create a write transaction). This also looks cleaner.
- Incrase privacy of methods that are implementation specific by moving them to a namespace: HandleError, GetObfuscateKey.
- Make constructor of CDBIterator private - they rely on implementation details, others have no business instantiating these.
- Remove `GetObfuscateKeyHex` - It is an unnecessary method as it is used only two times and only internally, and the whole implementation is  `HexStr(obfuscate_key)`.
- Remove `throw` keywords in function signatures - Using throw() specifications   in function signatures is not only not required in C++, it is considered   deprecated for [various reasons](https://stackoverflow.com/questions/1055387/throw-keyword-in-functions-signature).   It is not implemented by any of the common C++ compilers. Their usage is also   inconsistent with the rest of the source code.

### CODE REVIEW

**Comment by sipa** [comment]
utACK 869cf1234a915808fda6fd663dead5580fbd046e

**Comment by MarcoFalke** [comment]
utACK 869cf12

**Comment by btcdrak** [comment]
Tested ACK 869cf12

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/commit/869cf1234a915808fda6fd663dead5580fbd046e

`throw()` is still used in two other files on master:

```
src/support/allocators/secure.h
src/support/allocators/zeroafterfree.h
```

but it is not for this PR.

**Comment by jonasschnelli** [comment]
utACK 869cf1234a915808fda6fd663dead5580fbd046e

**Comment by jamesob** [comment]
utACK

**Comment by laanwj** [comment]
> throw() is still used in two other files on master:
>
>    src/support/allocators/secure.h
>    src/support/allocators/zeroafterfree.h

Thanks for mentioning, although I think these are of a different class. They use `throw()` in the more conventional way to signify that a method or function *doesn't ever* throw. These could be replaced by the `noexcept` keyword in c++11.

**Pull request merged**
