### PR TITLE
doc: More precise -debug and -debugexclude doc

### PR DESCRIPTION
**Pull request by ghost**
I wondered how one could enable debug logging with `-debug=<category>` for multiple categories. Found out solution is to specify that option multiple times for each wanted category.

This PR documents this behavior and uses the same wording for the same behavior of `-debugexclude=<category>` to make that also clear and stringent.

### CODE REVIEW

**Comment by practicalswift** [comment]
Concept ACK on clarifying this

**Comment by laanwj** [comment]
ACK 572fd0f7382bd0e6c7acc27dc354fae8489ab0a0

**Comment by MarcoFalke** [comment]
ACK 572fd0f7382bd0e6c7acc27dc354fae8489ab0a0

Would be nice if the cardinality was auto-printed by the argsman, similar to how the python argsman does it

**Review by theStack — APPROVED** [review]
ACK 572fd0f7382bd0e6c7acc27dc354fae8489ab0a0
Thanks for clarifying!

**Pull request merged**
