### PR TITLE
Revert "doc: note that brew installed qt is not supported"

### LINKED ISSUE #25947: MacOS Build Error: Qt 5 and 6 Simultaneously Installed.
This error seems to appear when `brew install qt@5` is installed at the same time as: `brew install qt`. (ie, qt version 6):

``` bash
% brew list --version | grep qt

qt 6.3.1_1
qt@5 5.15.5_1
```

```
Making all in src
  CXX      qt/libbitcoinqt_a-bantablemodel.o
In file included from qt/bantablemodel.cpp:14:
In file included from /usr/local/Cellar/qt@5/5.15.5_1/lib/QtCore.framework/Headers/QLocale:1:
/usr/local/Cellar/qt@5/5.15.5_1/lib/QtCore.framework/Headers/qlocale.h:1028:25: error: unknown type name 'QStringRef'; did you mean 'CFStringRef'?
    short toShort(const QStringRef &s, bool *ok = nullptr) const;
                        ^~~~~~~~~~
                        CFStringRef
/usr/local/include/QtCore/qdebug.h:531:1: note: 'CFStringRef' declared here
Q_FORWARD_DECLARE_CF_TYPE(CFString);
^
/usr/local/include/QtCore/qglobal.h:802:77: note: expanded from macro 'Q_FORWARD_DECLARE_CF_TYPE'
#  define Q_FORWARD_DECLARE_CF_TYPE(type) typedef const struct __ ## type * type ## Ref
                                                                            ^
<scratch space>:112:1: note: expanded from here
CFStringRef
^
```

```bash
% git clean -ffxd
% git rev-parse HEAD
e191fac4f3c37820f0618f72f0a8e8b524531ab8
% ./autogen.sh
% ./configure
% make
```
output: https://gist.github.com/da2ce7/c697259e204c961876ad7f7057e95b34

config.log: https://gist.github.com/da2ce7/ec7276de7d0284681cd73b0cdcb90f3b

brew list --version --formulae: https://gist.github.com/da2ce7/25d6473224a1d69a28cf24e44abb55b7

_Originally posted by @da2ce7 in https://github.com/bitcoin/bitcoin/issues/21901#issuecomment-1229561087_

### PR DESCRIPTION
**Pull request by hebasto**
As bitcoin/bitcoin#26056 fixes bitcoin/bitcoin#25947 it looks reasonable to revert bitcoin/bitcoin#21988.

### CODE REVIEW

**Comment by jarolrod** [comment]
concept ack

**Comment by fanquake** [comment]
ACK - post rebase

**Comment by hebasto** [comment]
Rebased b7f1d2fb971fb5a98016de51759aaae464df9564 -> 34a2f91055ea467b4c20c419646849da5bd7fb94 ([pr26079.01](https://github.com/hebasto/bitcoin/commits/pr26079.01) -> [pr26079.02](https://github.com/hebasto/bitcoin/commits/pr26079.02)) on top of the merged #26056.

**Review by fanquake — APPROVED** [review]
ACK 34a2f91055ea467b4c20c419646849da5bd7fb94 - haven't tested at all.

**Review by jarolrod — APPROVED** [review]
ACK https://github.com/bitcoin/bitcoin/commit/34a2f91055ea467b4c20c419646849da5bd7fb94

Confirming that this is no longer an issue. Tested on both an M1 and intel mac

**Pull request merged**
