### PR TITLE
refactor: Pass reference to LookUpStats

### PR DESCRIPTION
**Pull request by maflcko**
I find it confusing to have an interface that accepts nullptr, but immediately crashes the program when someone does pass nullptr.

Fix that.

Also some include fixups.

### CODE REVIEW

**Comment by jonatack** [comment]
Concept ACK

**Comment by jonatack** [comment]
Concept ACK
```
CHECK_NONFATAL(condition) or NONFATAL_UNREACHABLE should be used instead of assert for RPC code.
src/rpc/blockchain.cpp:827:            CBlockIndex& block_index = *Assert(WITH_LOCK(::cs_main, return blockman.LookupBlockIndex(view->GetBestBlock())));

^---- failure generated from lint-assertions.py
```

**Comment by MarcoFalke** [comment]
Thx, fixed

**Comment by jonatack** [comment]
Approach ACK, changes LGTM on first read over GitHub, checked that a lifetimebound annotation isn't needed.

**Review by aureleoules — COMMENTED** [review]
ACK faa3d38ec6f2999740486c6c66cd062e74c769fb

**Pull request merged**
