### PR TITLE
doc: add release note for -getinfo displaying multiwallet balances

### PR DESCRIPTION
**Pull request by jonatack**
Release note for #18594. This is one of the commits from #19089, which had one concept ACK and approach ACK since late May. It seems better to submit the changes atomically.

### CODE REVIEW

**Comment by jonatack** [comment]
The next PR will be 865d2c32d5a99c49a3fcea86c881ac6cdc980b3e to update the `-getinfo` help.

**Comment by promag** [comment]
ACK.

This PR adds release notes for #18594 - might be a good idea to add this to OP.

**Comment by jonatack** [comment]
Thanks @promag, added.

**Comment by luke-jr** [comment]
ACK

**Pull request merged**
