### PR TITLE
Updated funcs.mk to work with Windows Subsystem for Linux

### PR DESCRIPTION
**Pull request by mxaddict**
This PR allows for buildings the depends packages on WSL

Tested on Windows 11 WSL 2.x

### CODE REVIEW

**Comment by mxaddict** [comment]
> 

Current issue is that Windows Subsystem for Linux adds some PATH values that have () and spaces, which cause these 3 lines of code to get a syntax error, simply adding the quotes fixes the issue.

**Comment by mxaddict** [comment]
Actually to be clear the issue also happens on any linux distro that has PATH values with those characters.

**Comment by hebasto** [comment]
> Current issue is that Windows Subsystem for Linux adds some PATH values that have () and spaces, which cause these 3 lines of code to get a syntax error, simply adding the quotes fixes the issue.

See #23895, #12528.

**Comment by mxaddict** [comment]
I think this change fixes those issue mentioned, I'm able to build depends correctly with path values with spaces with this fix.

**Comment by mxaddict** [comment]
With fix:
image


Without:
image

**Comment by laanwj** [comment]
Concept ACK, I'm kind of happy to see building in paths with spaces is almost supported. It's almost like it's 2022 not 1984. Once that works it'd make sense to do it in one of the CI runs.

**Comment by laanwj** [comment]
> I usually avoid path values with spaces, but sometimes it just can't be helped smile

Sure, if that's your preference. But there should be no technical reason to :smile: Space has been a valid character in paths since, i dunno, moving away from FAT16? To be sure, some of the UNIX tooling is just very clumsy in that regard, it's not specific to this project. But things are improving slowly.

**Comment by fanquake** [comment]
@mxaddict can you confirm that *everything* works with this change. Not just building depends, but also building bitcoind, running `make install`, even performing a cross-compile etc.

You'll also need to get rid of the merge commit out of the PR, and, while you're at it, can you update the commit message for the change to be more descriptive than `Updated funcs.mk to work..`.

**Comment by mxaddict** [comment]
> 

I can confirm that I can cross compile for mingw and osx as well, have not tried any other builds though

I assume it also does not break any builds as the CI runs have passed.

Sure, I can update the commit message and remove the merge commit

**Comment by mxaddict** [comment]
Closing, no one seems to be interested in this PR

**Pull request closed without merging**
