### PR TITLE
fuzz: Run in parallel

### PR DESCRIPTION
**Pull request by maflcko**
Can be reviewed with `--ignore-all-space`

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Locally:

```
$ time ./test/fuzz/test_runner.py ../btc_qa_assets/fuzz_seed_corpus --par=9 -l DEBUG
...
real	1m44.747s
user	9m17.108s
sys	0m32.433s


$ time ./test/fuzz/test_runner.py ../btc_qa_assets/fuzz_seed_corpus --par=1 -l DEBUG
...
real	5m53.437s
user	5m25.461s
sys	0m19.031s

$ # current master
$ time ./test/fuzz/test_runner.py ../btc_qa_assets/fuzz_seed_corpus -l DEBUG
...
real	6m1.995s
user	5m35.519s
sys	0m18.982s

**Comment by practicalswift** [comment]
ACK fa66280396890bf616cc75432603111e1046d496 -- patch looks correct and the live demo in https://github.com/bitcoin-core/qa-assets/pull/11#issuecomment-615439226 convinced me: this is good!

**Comment by MarcoFalke** [comment]
It doesn't seem to speed up the run on travis, but it doesn't slow it down either. I guess I don't care about that as long as locally everything runs fast.

**Review by fanquake — APPROVED** [review]
ACK fa66280396890bf616cc75432603111e1046d496 - this seems sane, and clearly provides some speedup. I'd post benchmarks but can't seem to get through a full run of `./test/fuzz/test_runner.py` without hitting at least a few crashes; see #18763, 18762.

**Pull request merged**
