### PR TITLE
doc: Mention required workload when building with MSVC

### PR DESCRIPTION
**Pull request by hebasto**

### CODE REVIEW

**Comment by hebasto** [comment]
Friendly ping @Sjors @sipsorcery

**Comment by sipsorcery** [comment]
ACK f97892d21af9fa1d5c3b07b37e233b0bea0807e7.

**Review by shaavan — COMMENTED** [review]
Do we need all the individual components from the "Desktop development with C++" workload when building with MSVC?

**Comment by hebasto** [comment]
> Do we need all the individual components from the "Desktop development with C++" workload when building with MSVC?

No, we don't. The default ones are just enough.

**Review by jarolrod — COMMENTED** [review]
Correct me if i'm mistaken, but the `Visual Studio Build Tools component`, when following the provided link, is only available at the bottom of the page and hidden behind a drop down menu titled `Tools for Visual Studio`. Perhaps mention this here so that someone doesn't give up and end up downloading Visual Studio 2022 in frustration of not finding the target download.

**Comment by hebasto** [comment]
@jarolrod 
> Correct me if i'm mistaken, but the `Visual Studio Build Tools component`, when following the provided link, is only available at the bottom of the page and hidden behind a drop down menu titled `Tools for Visual Studio`. Perhaps mention this here so that someone doesn't give up and end up downloading Visual Studio 2022 in frustration of not finding the target download.

That's correct. Mind suggesting a better wording aligned with this repo's approach to documenting the use of third-party tools?

**Pull request merged**
