### PR TITLE
refactor: Move more stuff to blockstorage

### PR DESCRIPTION
**Pull request by maflcko**
See #21575

### CODE REVIEW

**Review by promag — COMMENTED** [review]
Code review ACK fa8cf6fae74f5738c2cb7a72400cd9af76d016e3. Always nice to see a nice chunk of code moved from validation.cpp. I agree this block storage related code doesn't belong there.

Verified commit by commit, with the given instructions, easy to review and to reason about. Only detail is that `AbortNode` is moved early since it is needed in an upcoming commit.

**Comment by MarcoFalke** [comment]
Rebased.

```
git range-diff bitcoin-core/master fa8cf6fae7 fab20c8f73 --word-diff-regex=.

**Comment by practicalswift** [comment]
Concept ACK

I don't know if that would belong in this PR or in a follow-up PR, but perhaps we want to introduce `namespace blockstorage` similar to how `namespace init` is introduced in https://github.com/bitcoin/bitcoin/pull/21732?

**Comment by MarcoFalke** [comment]
I think a namespace is not the right solution here. Blockstorage is inherently stateful, so a class makes more sense. I expect that `BlockManager` can be recycled to be this class (after it is moved here), but this will happen in later pull requests. The changes here are focussed on move-only to simply collect the code that is blockstorage related.

**Comment by Sjors** [comment]
ACK fa09a9eac8d8ab65ce4064c35a9f21349a644982

**Comment by kiminuo** [comment]
ACK fa09a9e

* Checked diff via dimmed-zebra.
* Compiled each individual commit - success. 
* (Noticed only that `IsBlockPruned` is no longer an inline function.)

**Comment by promag** [comment]
Code review ACK fa09a9eac8d8ab65ce4064c35a9f21349a644982. Since last review `git range-diff c6d6bc8abb721be68a3d2cdba11ceb5e9814c9b1 fa8cf6fae74f5738c2cb7a72400cd9af76d016e3 fa09a9eac8d8ab65ce4064c35a9f21349a644982 --word-diff-regex=.`.

**Review by promag — COMMENTED** [review]
Code review ACK fa09a9eac8d8ab65ce4064c35a9f21349a644982. Since last review

git range-diff c6d6bc8abb721be68a3d2cdba11ceb5e9814c9b1 fa8cf6fae74f5738c2cb7a72400cd9af76d016e3 fa09a9eac8d8ab65ce4064c35a9f21349a644982 --word-diff-regex=.`

**Comment by laanwj** [comment]
Code review ACK fa09a9eac8d8ab65ce4064c35a9f21349a644982

**Pull request merged**
