### PR TITLE
guix: pass `--enable-initfini-array` to release GCC

### PR DESCRIPTION
**Pull request by fanquake**
This returns us to pre-Guix behaviour, where the compilers we were using to build releases, were configured with this option.

> [--enable-initfini-array](https://gcc.gnu.org/install/configure.html)
> Force the use of sections .init_array and .fini_array (instead of .init and .fini) for constructors and destructors. Option --disable-initfini-array has the opposite effect. If neither option is specified, the configure script will try to guess whether the .init_array and .fini_array sections are supported and, if they are, use them.

### CODE REVIEW

**Comment by TheCharlatan** [comment]
I can confirm that this adds relevant `.fini_array`sections and gets rid of the `.ctors` and `.dtors` sections in the bitcoin x86 _64 linux binaries by comparing the binaries of this PR's `HEAD` and its `HEAD~1`.

`objdump -h bitcoind` on fc733e9 (HEAD) :
```
bitcoind:     file format elf64-x86-64
Sections:
Idx Name          Size      VMA               LMA               File off  Algn
  0 .interp       0000001c  0000000000000350  0000000000000350  00000350  2**0
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
...
 22 .init_array   00000598  0000000000e5dfa0  0000000000e5dfa0  00e5cfa0  2**3
                  CONTENTS, ALLOC, LOAD, DATA
 23 .fini_array   00000008  0000000000e5e538  0000000000e5e538  00e5d538  2**3
                  CONTENTS, ALLOC, LOAD, DATA
 24 .data.rel.ro  0001c6f8  0000000000e5e540  0000000000e5e540  00e5d540  2**5
                  CONTENTS, ALLOC, LOAD, DATA
 25 .dynamic      00000250  0000000000e7ac38  0000000000e7ac38  00e79c38  2**3
                  CONTENTS, ALLOC, LOAD, DATA
 26 .got          00001168  0000000000e7ae88  0000000000e7ae88  00e79e88  2**3
                  CONTENTS, ALLOC, LOAD, DATA
 27 .data         00003830  0000000000e7c000  0000000000e7c000  00e7b000  2**5
                  CONTENTS, ALLOC, LOAD, DATA
 28 .bss          000103d8  0000000000e7f840  0000000000e7f840  00e7e830  2**5
                  ALLOC
 29 .comment      00000012  0000000000000000  0000000000000000  00e7e830  2**0
                  CONTENTS, READONLY
 30 .note.stapsdt 000004fc  0000000000000000  0000000000000000  00e7e844  2**2
                  CONTENTS, READONLY
 31 .gnu_debuglink 00000014  0000000000000000  0000000000000000  00e7ed40  2**2
                  CONTENTS, READONLY
```

`objdump -h bitcoind` on 4398cfb2 (HEAD~1):
```
bitcoind:     file format elf64-x86-64
Sections:
Idx Name          Size      VMA               LMA               File off  Algn
  0 .interp       0000001c  0000000000000350  0000000000000350  00000350  2**0
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
...
 22 .init_array   00000590  0000000000e5dfb0  0000000000e5dfb0  00e5cfb0  2**3
                  CONTENTS, ALLOC, LOAD, DATA
 23 .ctors        00000010  0000000000e5e540  0000000000e5e540  00e5d540  2**3
                  CONTENTS, ALLOC, LOAD, DATA
 24 .dtors        00000010  0000000000e5e550  0000000000e5e550  00e5d550  2**3
                  CONTENTS, ALLOC, LOAD, DATA
 25 .data.rel.ro  0001c6f8  0000000000e5e560  0000000000e5e560  00e5d560  2**5
                  CONTENTS, ALLOC, LOAD, DATA
 26 .dynamic      00000230  0000000000e7ac58  0000000000e7ac58  00e79c58  2**3
                  CONTENTS, ALLOC, LOAD, DATA
 27 .got          00001168  0000000000e7ae88  0000000000e7ae88  00e79e88  2**3
                  CONTENTS, ALLOC, LOAD, DATA
 28 .data         00003830  0000000000e7c000  0000000000e7c000  00e7b000  2**5
                  CONTENTS, ALLOC, LOAD, DATA
 29 .bss          000103d8  0000000000e7f840  0000000000e7f840  00e7e830  2**5
                  ALLOC
 30 .comment      00000012  0000000000000000  0000000000000000  00e7e830  2**0
                  CONTENTS, READONLY
 31 .note.stapsdt 000004fc  0000000000000000  0000000000000000  00e7e844  2**2
                  CONTENTS, READONLY
 32 .gnu_debuglink 00000014  0000000000000000  0000000000000000  00e7ed40  2**2
                  CONTENTS, READONLY
```

**Comment by TheCharlatan** [comment]
Guix builds [127c637](https://github.com/bitcoin/bitcoin/pull/27153/commits/127c637cf0a80e0ea68a7c5aaa088e5ccc9d3d13)

```
ae145877193079ceb71b86582b86294efba941d8898480e16920f8588bb25fca  guix-build-127c637cf0a8/output/aarch64-linux-gnu/SHA256SUMS.part
b50822b488f79eba521dca2538b98ced15da3f175deeccce4030a6690bd4b077  guix-build-127c637cf0a8/output/aarch64-linux-gnu/bitcoin-127c637cf0a8-aarch64-linux-gnu-debug.tar.gz
a04d495f8338dc30afdc258df91708c20197f74fe7c84070d8e9ebc9d3924780  guix-build-127c637cf0a8/output/aarch64-linux-gnu/bitcoin-127c637cf0a8-aarch64-linux-gnu.tar.gz
827e3e980631e17a813a6bc1a74e9b2c323492e4b71114d788f61df551c388c0  guix-build-127c637cf0a8/output/arm-linux-gnueabihf/SHA256SUMS.part
0d665407a1c2017f3896edaeabffe4682859bf519ad0b4a7b35c3103879be954  guix-build-127c637cf0a8/output/arm-linux-gnueabihf/bitcoin-127c637cf0a8-arm-linux-gnueabihf-debug.tar.gz
7454a77358c9c2fd6da16c740cc0470aff757f6bba20f0cc65942cdda9090986  guix-build-127c637cf0a8/output/arm-linux-gnueabihf/bitcoin-127c637cf0a8-arm-linux-gnueabihf.tar.gz
4f358fa4812897081e4348dd0d2c4fad7d3cc7ee4ca36d038969b429e1b74514  guix-build-127c637cf0a8/output/arm64-apple-darwin/SHA256SUMS.part
5ae3602d2867678b6d9ab95d8313c07971bdfd5bbe7266710f218ff2c0238789  guix-build-127c637cf0a8/output/arm64-apple-darwin/bitcoin-127c637cf0a8-arm64-apple-darwin-unsigned.dmg
2f39b61b328e3e52bb514d2a428139ffffa04545d93daf282c10ff590a43a6ed  guix-build-127c637cf0a8/output/arm64-apple-darwin/bitcoin-127c637cf0a8-arm64-apple-darwin-unsigned.tar.gz
55d54c87a7026190ed50650b741a5936faf762ab069cd9862b364eabf55355a6  guix-build-127c637cf0a8/output/arm64-apple-darwin/bitcoin-127c637cf0a8-arm64-apple-darwin.tar.gz
0888a44f58955f82a1c9e4b4805f5368f421123983a158c0e41e54a6c2604908  guix-build-127c637cf0a8/output/dist-archive/bitcoin-127c637cf0a8.tar.gz
d9047095a70f409c6105960c2bd695e8e4004bd5143c3aabbbb7759501d5223d  guix-build-127c637cf0a8/output/powerpc64-linux-gnu/SHA256SUMS.part
58f2f2c84f10a8401d552c0b697d9135e3696e6a45b30b0ee66b4bcda666810e  guix-build-127c637cf0a8/output/powerpc64-linux-gnu/bitcoin-127c637cf0a8-powerpc64-linux-gnu-debug.tar.gz
3beed3c123cdef21444541ab7232145d3270ff7ecbf6c8f4e4090ac618c5c295  guix-build-127c637cf0a8/output/powerpc64-linux-gnu/bitcoin-127c637cf0a8-powerpc64-linux-gnu.tar.gz
c350eaaa84fc7d158cf21f2a90cb4ec9d9ab91395e19e54e6761b723cf46ad28  guix-build-127c637cf0a8/output/powerpc64le-linux-gnu/SHA256SUMS.part
ee2139dde970b19f51b607252d4e80f524ff752110c3478d16fdf9b9e0c4adf3  guix-build-127c637cf0a8/output/powerpc64le-linux-gnu/bitcoin-127c637cf0a8-powerpc64le-linux-gnu-debug.tar.gz
42fd146f9f595e5aa6c24384e37e47a2ba4ecd75192d44d437e658f92aea18ff  guix-build-127c637cf0a8/output/powerpc64le-linux-gnu/bitcoin-127c637cf0a8-powerpc64le-linux-gnu.tar.gz
33d2490ee2ea2835b0f8fa8ce7fb107c1ae76756c05574087fb73e2222166ece  guix-build-127c637cf0a8/output/riscv64-linux-gnu/SHA256SUMS.part
ebeea43e60e2897f6adc7cbc9d469ca26da9f5b4935ba6385d88729f6289198c  guix-build-127c637cf0a8/output/riscv64-linux-gnu/bitcoin-127c637cf0a8-riscv64-linux-gnu-debug.tar.gz
48e543236f01689084c4c65e1394796d1943dd5c9cdd0c594812227368775b72  guix-build-127c637cf0a8/output/riscv64-linux-gnu/bitcoin-127c637cf0a8-riscv64-linux-gnu.tar.gz
011ffddefd89e5449f88d9f3291a49a46e37fc5e9eb42a24ebd8a1004fbfa0f9  guix-build-127c637cf0a8/output/x86_64-apple-darwin/SHA256SUMS.part
c7474fe1e546781c9bdca78dd30903d850a98b7195bf76140e0383850f7d96b4  guix-build-127c637cf0a8/output/x86_64-apple-darwin/bitcoin-127c637cf0a8-x86_64-apple-darwin-unsigned.dmg
be3ca6d0243b10dd81656f085854121e00bdfff6831f578129692938ff657727  guix-build-127c637cf0a8/output/x86_64-apple-darwin/bitcoin-127c637cf0a8-x86_64-apple-darwin-unsigned.tar.gz
d1fc59507cba1bfb3e9b1b3e909fc24bf388259b2d2ed4eeb86d4da159d3447f  guix-build-127c637cf0a8/output/x86_64-apple-darwin/bitcoin-127c637cf0a8-x86_64-apple-darwin.tar.gz
891014347c78d114882f081f6cc074a8ce28755c78f6ac55718a36a2a7e7e5d4  guix-build-127c637cf0a8/output/x86_64-linux-gnu/SHA256SUMS.part
316534b436f654068ad31d689364010e71d887c80d01e760cafa1ce607da665b  guix-build-127c637cf0a8/output/x86_64-linux-gnu/bitcoin-127c637cf0a8-x86_64-linux-gnu-debug.tar.gz
b6d24756ecd1dc98bd6d1f2483ddea8511e35cc5ea028dfbf1acf63fcd8c62fd  guix-build-127c637cf0a8/output/x86_64-linux-gnu/bitcoin-127c637cf0a8-x86_64-linux-gnu.tar.gz
e319baafacce5985db98e18666ff17d7633d7d866cbe6add93d674ec7ac5575e  guix-build-127c637cf0a8/output/x86_64-w64-mingw32/SHA256SUMS.part
9beb8b1492d25e6681d4c73127a0a82d41dbbc96afe5ab1c66d1d095a20d8cbe  guix-build-127c637cf0a8/output/x86_64-w64-mingw32/bitcoin-127c637cf0a8-win64-debug.zip
b9b1c9a8f59ee05c360572f0a0a15419ea66058ee9f860f1d9444f5371a65840  guix-build-127c637cf0a8/output/x86_64-w64-mingw32/bitcoin-127c637cf0a8-win64-setup-unsigned.exe
e76d9d34ea8ccdb977d65f60ffdcea0dc9e68b650603339afa6d10cc25987986  guix-build-127c637cf0a8/output/x86_64-w64-mingw32/bitcoin-127c637cf0a8-win64-unsigned.tar.gz
a17420f664deb1866f856be5181a27ee8442e4c40ebf205cbb74fe530460bc83  guix-build-127c637cf0a8/output/x86_64-w64-mingw32/bitcoin-127c637cf0a8-win64.zip
```

**Review by vincenzopalazzo — APPROVED** [review]
utACK https://github.com/bitcoin/bitcoin/pull/27153/commits/127c637cf0a80e0ea68a7c5aaa088e5ccc9d3d13

**Comment by TheCharlatan** [comment]
ACK 127c637cf0a80e0ea68a7c5aaa088e5ccc9d3d13

**Pull request merged**
