### PR TITLE
mempool: Run coin.IsSpent only once in a row

### PR DESCRIPTION
**Pull request by maflcko**
Follow-up to commit 64e4963c635ec3a73a5fa3f32f6ec08e70609f60 and https://github.com/bitcoin/bitcoin/pull/23976#discussion_r787758193

### CODE REVIEW

**Review by theStack — APPROVED** [review]
Code-review ACK fa2bcc4e42e7fed61727b3de4019e9702d4090ce

The condition `false || expression` is logically equivalent to just `expression`.

**Review by w0xlt — APPROVED** [review]
crACK https://github.com/bitcoin/bitcoin/pull/24102/commits/fa2bcc4e42e7fed61727b3de4019e9702d4090ce

There is no need for `coin.IsSpent()`, given the previous assertion.

**Review by shaavan — APPROVED** [review]
Code Review ACK fa2bcc4e42e7fed61727b3de4019e9702d4090ce

The reason is nicely explained by @theStack.

> The condition `false || expression` is logically equivalent to just `expression`.

**Review by brunoerg — APPROVED** [review]
crACK fa2bcc4e42e7fed61727b3de4019e9702d4090ce

**Comment by glozow** [comment]
utACK fa2bcc4e42e7fed61727b3de4019e9702d4090ce, agree the assertion is sufficient

**Pull request merged**
