### PR TITLE
Improvement of documentation of command line parameter 'whitelist'

### PR DESCRIPTION
**Pull request by ghost**
See https://github.com/bitcoin/bitcoin/pull/9249

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Thanks! Some feedback:

Please keep the existing translation of the last sentence, when you
are not changing a word in it. Things to translate are put in `_()`.

Also you want to refrain from splitting a sentence in two translation strings.

Finally, you can use the existing pull and add commits to it/squash.

**Comment by wodry** [comment]
OK here ya go :)

**Comment by sipa** [comment]
utACK

**Comment by MarcoFalke** [comment]
utACK (and squashed: 40b85ed ... 8a70a9d)

**Comment by fanquake** [comment]
utACK 8a70a9d

**Comment by jonasschnelli** [comment]
ACK 8a70a9da3da0df5c376042b18b87f0a63e88d2e3

**Comment by gmaxwell** [comment]
utACK

**Pull request merged**
