### PR TITLE
[gitian] Default reference_datetime to commit author date

### PR DESCRIPTION
**Pull request by maflcko**

### CODE REVIEW

**Comment by MarcoFalke** [comment]
@jonasschnelli I don't want to break your debian box, so would you mind testing this after updating your gitian-builder to the latest version?

**Comment by laanwj** [comment]
Ping @theuni

Concept ACK however:

There's a potential determinism problem with making the datetime depend on the bitcoin repository: the dependencies are built with datetime set to a single commit date, then cached, then next time they'll be reused. If the dependencies embed the datetime anywhere, different builders can get different result depending on when they built the dependencies.

**Comment by MarcoFalke** [comment]
Appears to be working on https://bitcoin.jonasschnelli.ch/pulls/7283/:

screenshot from 2016-01-04 12-57-51

**Comment by jonasschnelli** [comment]
Agree with @laanwj: would it be possible to build and cache the dependencies still with a fixed time?
Maybe first someone needs to check if the datetime results/gets included somehow in the dependencies.

**Comment by laanwj** [comment]
BTW: Ugh. I think it was a mistake to add the build date there. It's worthless at most, and deceptive at the least.
If we want the date of last commit in there, would make sense to add it after the "Client version".

**Comment by theuni** [comment]
@laanwj I'm all for removing the build date from tagged releases. That would also mean that we could merge the signing steps, since the only reason they're staggered is the changed commit hash in the binary.

@jonasschnelli I believe we've already removed all time sources from the depends.

@laanwj I believe that would already be the case?

**Comment by laanwj** [comment]
> @laanwj I believe that would already be the case?

Faketime prevents that at the moment by setting the date/time stamp to a fixed value

**Comment by MarcoFalke** [comment]
Then, wouldn't stuff like be656283f98896df0bc8634d446b2873f9fed573 break this as well?

**Comment by laanwj** [comment]
You're right, but be65628 is a one-time change. So dependencies built before and after that may differ. The problem with this is that the time/date will change *every* time.

Not sure it is an issue, but as this is a non-critical detail I'd like to be sure it doesn't cause problems down the line before merging it.

**Comment by laanwj** [comment]
Needs rebase

**Comment by MarcoFalke** [comment]
Rebased

**Comment by MarcoFalke** [comment]
@laanwj I've been running gitian builder to see if the results match:

| yml source         | target commit      | cache populated by | result |
|--------------------|--------------------|--------------------|--------|
| e7ea5db            | e7ea5db            | e7ea5db            | 041a0f82a0c4...  bitcoin-0.12.99-linux32.tar.gz  |
| this pull's commit | this pull's commit | e7ea5db            | 49fd8bbb3fcc...  bitcoin-0.12.99-linux32.tar.gz |
| this pull's commit | this pull's commit | this pull's commit | 49fd8bbb3fcc...  bitcoin-0.12.99-linux32.tar.gz  |
| e7ea5db            | e7ea5db            | this pull's commit | 041a0f82a0c4...  bitcoin-0.12.99-linux32.tar.gz    |


So this appears to indicate that the result is independent from the cache.

**Comment by MarcoFalke** [comment]
@theuni Do you think this is ready to merge into 0.13?

**Comment by theuni** [comment]
Sorry for the delay, testing this.

**Comment by theuni** [comment]
Yes, after taking a closer look, unfortunately this will not play nice with depends. Mostly because of the timestamps inside of tarballs, but also .a's and other problematic formats. Note that the end-results may or may not be the same, but the intermediates would differ.

We can revisit this later though, as options for tar/binutils/ld/etc have been added recently that reliably purge this data.

The only realistic thing I see that we can do here for now without a major overhaul would be to set the faketime once to a hard-coded date for depends, so that it remains the same regardless of the commit used, then reset for the bitcoin build itself.

**Comment by MarcoFalke** [comment]
> set the faketime once to a hard-coded date for depends


@theuni Something like the last commit  I pushed (untested)?

**Comment by theuni** [comment]
@MarcoFalke Yep, I think that approach should be fine.

**Comment by MarcoFalke** [comment]
Not sure why gitian fails on the windows build...

```
[gitian-builder]$ tail -8 var/build.log
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... yes
checking whether make supports nested variables... (cached) yes
checking whether the C++ compiler works... no
configure: error: in `/home/ubuntu/build/bitcoin':
configure: error: C++ compiler cannot create executables
See `config.log' for more details

[gitian-builder]$ ./libexec/on-target tail -5 ./build/bitcoin/config.log
#define PACKAGE_STRING "Bitcoin Core 0.12.99"
#define PACKAGE_BUGREPORT "https://github.com/bitcoin/bitcoin/issues"
#define PACKAGE_URL "https://bitcoincore.org/"

configure: exit 77

**Comment by arowser** [comment]
Can one of the admins verify this patch?

**Comment by laanwj** [comment]
I think it would be better to remove use of the build date in our binary completely, making the use of faketime unnecessary. We don't have control over that for the dependencies but we do for our own code.

**Comment by MarcoFalke** [comment]
The motivation for this pull was to avoid regular "bump date" pulls such as https://github.com/bitcoin/bitcoin/pull/7251#issue-123874815.

The build date was removed in #7732 and I don't think we should add the commit date to the gui.

**Comment by MarcoFalke** [comment]
If this pull gets closes, it might be worth to update https://github.com/bitcoin/bitcoin/blob/950be19727a581970591d8f8138dfe4725750382/doc/release-process.md#bitcoin-maintainersrelease-engineers-update-version-in-sources and mention to bump the date in the same go.

**Comment by mrCertified** [comment]
utACK え7えあ5db

**Comment by laanwj** [comment]
There's another place where this matters: the times/dates in the .zip files and .tar.gz archives of the binary distribution. I guess that makes it worth doing this. 

> The build date was removed in #7732 and I don't think we should add the commit date to the gui. 

Only from the GUI though.

**Comment by laanwj** [comment]
> If this pull gets closes, it might be worth to update

Well my point was more 'why would we care about this'. If there is no reason to care about this date at all, there's no point in bumping it either. E.g. after making sure it doesn't get shown in the GUI or log anymore.
But I suppose the dates in archives are a reason to care.

**Pull request merged**
