### PR TITLE
test: Remove unsafe BOOST_TEST_MESSAGE

### LINKED ISSUE #17987: Unit test validation_block_tests intermittently writes garbage to stdout
Current master, Ubuntu:

Repeatedly running `validation_block_tests/processnewblock_signals_ordering`, a test that creates multiple threads to test the validation interface, sporadically writes weird messages to stdout (with the test passing).
Running 
`for i in {1..30}; do ./src/test/test_bitcoin --run_test=validation_block_tests/processnewblock_signals_ordering; done` 
usually gives me multiple occurrences of this.

It  sometimes writes code fragments such as "pindexNew->GetBlockHash()", "m_expected_tip", "==", in other runs single log entries.

Can someone reproduce this? 
Obviously this is just a small nuisance in itself, still reporting this in case the root cause might be interesting.

### PR DESCRIPTION
**Pull request by maflcko**
Fixes #17987

Can be tested with

```
./src/test/test_bitcoin -l test_suite  -- DEBUG_LOG_OUT

### CODE REVIEW

**Comment by MarcoFalke** [comment]
cc @mzumsande

**Comment by fjahr** [comment]
tested ACK fa3cc0bfc4c4fc13a384fc291403c9fd41082f18

Thank you!

**Comment by mzumsande** [comment]
Tested ACK fa3cc0bfc4c4fc13a384fc291403c9fd41082f18

Maybe test/README.md could mention the DEBUG_LOG_OUT option which I find really helpful, and possibly also a warning that BOOST_TEST_MESSAGE, which is mentioned there, is not threadsafe.

**Comment by MarcoFalke** [comment]
Thanks, I am going to go ahead and merge this bug fix. Will update the docs in a new commit.

**Comment by MarcoFalke** [comment]
Done here: #18486

**Pull request merged**
