### PR TITLE
Implement watchonly support in fundrawtransaction

### PR DESCRIPTION
**Pull request by TheBlueMatt**

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
Realized I forgot to submit this after #6088....

**Comment by jonasschnelli** [comment]
Needs rebase

**Comment by jgarzik** [comment]
ut ACK

**Comment by sipa** [comment]
Untested ACK.

**Comment by sipa** [comment]
Hmm, do you actually need to have the full CPubKey object available? Just
marking a particular key id as "trust me, i can sign this" should be
enough, or am i missing something?

**Comment by sipa** [comment]
Ignore me, the dummy signer needs it. Nice.

**Comment by laanwj** [comment]
utACK

**Pull request merged**
