### PR TITLE
Update libsecp256k1 (endomorphism, test improvements)

### PR DESCRIPTION
**Pull request by sipa**
This updates the libsecp256k1 subtree to the latest master, which includes:

* Enabling the GLV endomorphism optimization by default (and removing support for the non-GLV EC multiplication)
* Added a proof for the correctness of the lambda split algorithm by roconnor-blockstream (other code was relying on the fact that it always outputs 128 bit results, which isn't at all obvious).
* Improved exhaustive tests, in particular for the Schnorr signature module
* Various other testing and CI improvements

### CODE REVIEW

**Comment by jonatack** [comment]
Concept ACK.

**Comment by benthecarman** [comment]
ACK 9e5626d 

```
$  ./test/lint/git-subtree-check.sh src/secp256k1
src/secp256k1 in HEAD currently refers to tree c79797189781d6656eba6cb155c249c57b4f5c9a
src/secp256k1 in HEAD was last updated in commit 52380bf304b1c02dda23f1e2fad0159e29b2f7a2 (tree c79797189781d6656eba6cb155c249c57b4f5c9a)
src/secp256k1 in HEAD was last updated to upstream commit c6b6b8f1bb044d7d1aa065ebb674adde98a36a8e (tree c79797189781d6656eba6cb155c249c57b4f5c9a)
GOOD

```

**Review by fanquake — APPROVED** [review]
ACK 9e5626d2a8ddbbd7640ff53f89f3a7021d747633 - performed a squash and checked that the changes were the same. The non-endomorphism code has now been ripped out.

how-to-verify-subtree notes here: https://github.com/fanquake/core-review/blob/master/subtree-merge.md

**Comment by fanquake** [comment]
@jamesob this would be a good PR for you to throw into bitcoinperf.

**Comment by jamesob** [comment]
Ran a local IBD comparison on this for 8000 blocks (height 500_000 - 508_000) and to my surprise didn't see any performance difference. Compared the HEAD of this PR to the commit in master preceding it (https://github.com/bitcoin/bitcoin/commit/c2c4dbaebd955ad2829364f7fa5b8169ca1ba6b9). Could be that this platform is bottlenecked by IO and not CPU?

ibd local range 500000 508000

### commands index
|          bench name           |                                                                                                    command                                                                                                     |
|-------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| ibd.local.range.500000.508000 | `bitcoind -dbcache=300 -debug=coindb -debug=bench -listen=0 -connect=0 -addnode=127.0.0.1:8888 -prune=9999999 -printtoconsole=0 -assumevalid=000000000000000000176c192f42ad13ab159fdb20198b87e7ba3c001e47b876` |


### #20147 vs. c2c4dbaebd955ad2829364f7fa5b8169ca1ba6b9 (absolute)
|                 bench name                 |  x  |           #20147           | c2c4dbaebd955ad2829364f7fa5b8169ca1ba6b9 |
|--------------------------------------------|----:|----------------------------|------------------------------------------|
| ibd.local.range.500000.508000.total_secs   |   2 | 737.8656 (± 3.1841)        | 738.3541 (± 7.6443)                      |
| ibd.local.range.500000.508000.peak_rss_KiB |   2 | 1746294.0000 (± 2362.0000) | 1756260.0000 (± 3168.0000)               |


### #20147 vs. c2c4dbaebd955ad2829364f7fa5b8169ca1ba6b9 (relative)
|                 bench name                 |  x  | #20147 | c2c4dbaebd955ad2829364f7fa5b8169ca1ba6b9 |
|--------------------------------------------|----:|-------:|-----------------------------------------:|
| ibd.local.range.500000.508000.total_secs   |   2 |      1 |                                    1.001 |
| ibd.local.range.500000.508000.peak_rss_KiB |   2 |      1 |                                    1.006 |

**Comment by sipa** [comment]
@jamesob That's certainly possible. With such a low dbcache, it's also possible it's just spending a lot of time in in preparing leveldb updates to flush.

**Comment by Sjors** [comment]
Your `assumevalid` block is at height 522,000 so you're not checking signatures, I think.

**Comment by jamesob** [comment]
Great call @Sjors, that should've occurred to me (d'oh). In any case, here are some much less surprising results showing improvement after disabled assumevalid.

ibd local range 500000 508000

### commands index
|          bench name           |                                                                     command                                                                      |
|-------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------|
| ibd.local.range.500000.508000 | `bitcoind -dbcache=300 -debug=coindb -debug=bench -listen=0 -connect=0 -addnode=127.0.0.1:8888 -prune=9999999 -printtoconsole=0 \-assumevalid=0` |


### #20147 vs. c2c4dbae (absolute)
|                 bench name                 |  x  |           #20147            |          c2c4dbae          |
|--------------------------------------------|----:|-----------------------------|----------------------------|
| ibd.local.range.500000.508000.total_secs   |   2 | 1529.8273 (± 5.1097)        | 1780.5817 (± 5.7187)       |
| ibd.local.range.500000.508000.peak_rss_KiB |   2 | 1718228.0000 (± 17852.0000) | 1686864.0000 (± 6596.0000) |


### #20147 vs. c2c4dbae (relative)
|                 bench name                 |  x  | #20147 | c2c4dbae |
|--------------------------------------------|----:|-------:|---------:|
| ibd.local.range.500000.508000.total_secs   |   2 |  1.000 |    1.164 |
| ibd.local.range.500000.508000.peak_rss_KiB |   2 |  1.019 |    1.000 |


For kicks, here's the utxo cache flush history (I need to normalize the times in this graph...).

ibd local range 500000 508000-flush-history

**Comment by fanquake** [comment]
Thanks @jamesob 👍

**Pull request merged**
