### PR TITLE
test: merge banning test from p2p_disconnect_ban to rpc_setban

### PR DESCRIPTION
**Pull request by brunoerg**
There are tests related to banning in both `p2p_disconnect_ban` and `rpc_setban`, some of them are testing same scenarios. So, this PR moves all banning test stuff to `rpc_setban` and leaves `p2p_disconnect_ban` only for disconnecting stuff. Since `p2p_disconnect_ban` doesn't have any banning stuff, this PR also renames that to `p2p_disconnect`.

### CODE REVIEW

**Comment by brunoerg** [comment]
cc: @andrewtoth (https://github.com/bitcoin/bitcoin/pull/26822#pullrequestreview-1238269263)

**Comment by brunoerg** [comment]
Rebased

**Comment by brunoerg** [comment]
Rebased

**Comment by glozow** [comment]
Since there doesn't seem to be very much review interest... is there any benefit in moving these tests to a different file?

**Comment by brunoerg** [comment]
> Since there doesn't seem to be very much review interest... is there any benefit in moving these tests to a different file?

Currently, there are stuff that are being test in both `p2p_disconnect_ban` and `rpc_setban` (e.g. "Test the ban list is preserved through restart" in `setban` and "setban: test persistence across node restart" in `p2p_disconnect_ban`). Since we have a specific test for `setban` RPC, the idea is concentrate everything about it there.

**Comment by brunoerg** [comment]
I'll close for now and work in a simpler alternative.

**Pull request closed without merging**
