### PR TITLE
Include tinyformat as a subtree

### PR DESCRIPTION
**Pull request by Empact**
This adds the existing c42f/tinyformat@689695c  of tinyformat as a subtree, and extracts the modifications that had been made to a `utilstrprintf.h` wrapper file which is included instead of `tinyformat.h` directly.

The benefits being that this should be easier to verifiably update and clearer what changes are being introduced, while making it easier to identify `tinyformat.h` as a dependency rather than a project file, and apply special treatment relative to that fact.

### CODE REVIEW

**Comment by Empact** [comment]
See https://github.com/bitcoin/bitcoin/commits/master/src/tinyformat.h for the changes relative to 7d312cb

**Comment by Empact** [comment]
wip: I have some build issues to sort out

**Comment by MarcoFalke** [comment]
Seems like a lot of files to pull in just to make it a subtree, no? Imo tinyformat is really meant to be a single file just to be copied into the project.

You can get the local modifications with `diff $upstream_file $local_file` using the upstream version mentioned in the last bump: 60b98f8e145617e9e50a2eb7f3181953e1e8c424

**Comment by Empact** [comment]
I'd be down with other approaches. My main desire is to separate the bitcoin code from the dependency code, and just a sub-folder is sufficient for that.

**Comment by Empact** [comment]
Reopening as the build seems to be sorted. I have pending follow-ups which relate to this that will help to explain the motivation.

**Comment by Empact** [comment]
Huh seems I'm unable to re-open due to the force pushes I made in the interim. Opening a new PR instead.

**Pull request closed without merging**
