### PR TITLE
zmq: Add jsonblock, jsontx

### LINKED ISSUE #14873: feature: Add JSON as a ZMQ output format
When the ZMQ interface publishes to, for example: `rawblock`, the default and only output format is as a binary / hex raw block. An option for `jsonblock` or similar could offer the deserialized version of this, as JSON, for clients that do not want to require dependency methods for interpreting raw blocks.

### PR DESCRIPTION
**Pull request by ch4ot1c**
These changes allow ZMQ to publish its updates for txs and blocks as human-readable JSON, as opposed to in the raw Bitcoin format. Output data corresponds to `verbosity` level 1.

Closes #14873

### CODE REVIEW

**Comment by promag** [comment]
Have you seen #11614?

**Comment by ch4ot1c** [comment]
@promag Thanks for showing me that - I hadn't seen it.

I think the prior discussion is great; I value these changes for the same reasons as @astanway:

- Swift / Objective-C doesn't have a transaction or block parsing library available; I would like to avoid custom code involving `varint`, etc. 
- I am using @fanquake's CoreRPC for an iOS project. ZMQ is a nice complement, and I can use it to determine the chaintip update event, but would much prefer it in a deserialized format. Assuming I don't want to "roll my own" parser:
- No unnecessary roundtrip from an additional RPC call (`getblock`)

Perhaps there is a bit of bias in the prior discussion, since experts @luke-jr and @dcousens dismissed it as "easy to implement". I think there is an important question raised:

> However, if ease of application development is not a priority for the project, then sure - happy to close.

The tradeoffs seem to favor having an option for JSON, since we already serve JSON over RPC.

**Comment by gmaxwell** [comment]
@laanwj That was also my thought on seeing the PR title.

**Comment by ch4ot1c** [comment]
I hear the response - fair enough. What could be done next / instead?

**Comment by laanwj** [comment]
> I hear the response - fair enough. What could be done next /  instead? 

If performance isn't important, otherwise you'd be using a client-side decoding library, but you're using zmq as a notification mechanism, why is the extra roundtrip to call `getblock` or `decoderawtransaction` such a problem?

**Comment by ch4ot1c** [comment]
A small performance hit in-transit would cost less and be more reliable than two (1 zmq 1 rpc) networking events, I guess was my reasoning. The duplicate call would mean more transferred data in total than the original with JSON formatting. I'm only interested in the latest block's stats.

Implementing parsing on clients makes the most sense, agreed.

`hashblock` is all I really needed. `hashtx`, `rawtx`, and `decoderawtransaction` got me mixed up in unneeded possibilities.

This might sound useless or even confusing, but for symmetry, we could consider `decoderawblock` as an RPC. There is already `submitblock` whose interface seemingly makes more sense for `bitcoind`, as it validates unavoidably.

**Comment by jonasschnelli** [comment]
I agree with @laanwj about JSON probably not being something we should have in conjunction with ZMQ.

I think a path for having JSON push notification would be the RPC long polling feature.
A first step could be: https://github.com/bitcoin/bitcoin/pull/13262 (outdated)

**Comment by promag** [comment]
I agree with @jonasschnelli.

@ch4ot1c don't forget that at the moment zmq notifications happen on the "main" thread. RPC is handled on a thread pool.

**Comment by laanwj** [comment]
As there is no agreement to do this I'm closing this PR

**Pull request closed without merging**
