### PR TITLE
docs: create sybil.md

### PR DESCRIPTION
**Pull request by Rspigler**
https://github.com/bitcoin/bitcoin/pull/25884

Sybil Attack info for CJDNS, I2P, and Tor

### CODE REVIEW

**Comment by 1440000bytes** [comment]
I am not sure if this needs 3 or more commits and last commit has incorrect author which could also be squashed with correction.

**Comment by 1440000bytes** [comment]
No opinion on pull request conceptually because we could have several doc files for different attacks.

Alternative would be to either create a doc file only for security recommendations or mention these points in individual files (tor, i2p, cjdns)

**Comment by michaelfolkson** [comment]
This seems like overkill to me (to introduce a new doc). Just a single line in the individual files (tor, i2p, cjdns) saying that while there are fewer nodes to connect to than IPv4, IPv6 the risk of a sybil attack may be higher? Even that I'm unsure about because that seems to be introducing judgment which there may be differing opinions on.

**Comment by michaelfolkson** [comment]
This may be better as a Bitcoin StackExchange question. "Am I at greater risk of being subject to sybil attack if I use one or a combination of Tor, I2P, CJDNS?" or such like. Perhaps there would be answer(s) from those who have enabled those networks in Core and spent more time interacting with peers on those networks than I/we have.

**Comment by Rspigler** [comment]
@michaelfolkson That's how I originally wrote the PR, but @vasild didn't like it

**Comment by ZenulAbidin** [comment]
> This may be better as a Bitcoin StackExchange question. "Am I at greater risk of being subject to sybil attack if I use one or a combination of Tor, I2P, CJDNS?" or such like. Perhaps there would be answer(s) from those who have enabled those networks in Core and spent more time interacting with peers on those networks than I/we have.

IMO it will be more visible on Google if it was placed in Bitcoin Wiki rather than BSE. I can make such an edit if @Rspigler is happy with it like that.

**Comment by Rspigler** [comment]
@ZenulAbidin Yes, it seems this is too controversial for official github docs. Bitcoin wiki would be great!

**Pull request closed without merging**
