### PR TITLE
[24.1] Backports for rc3

### PR DESCRIPTION
**Pull request by fanquake**
Backports for rc3. Currently:
* https://github.com/bitcoin/bitcoin/pull/27608
* https://github.com/bitcoin/bitcoin/pull/27610

### CODE REVIEW

**Comment by josibake** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/27614/commits/97f5e28830dfa5786cdc5df62e245e03fa393e19

Verified that the commits added are the correct ones from the PRs linked, compiled and ran the tests. Document changes look good. Looks like the CI failures are just github being crappy

**Review by glozow — COMMENTED** [review]
ACK 97f5e28830dfa5786cdc5df62e245e03fa393e19

**Comment by dergoegge** [comment]
ACK 97f5e28830dfa5786cdc5df62e245e03fa393e19

**Review by brunoerg — APPROVED** [review]
ACK 97f5e28830dfa5786cdc5df62e245e03fa393e19

Just ran the tests locally, no problem. Release notes ok.

**Review by hebasto — APPROVED** [review]
ACK 97f5e28830dfa5786cdc5df62e245e03fa393e19, commits were backported locally, got zero diff.

**Comment by achow101** [comment]
ACK 97f5e28830dfa5786cdc5df62e245e03fa393e19

**Pull request merged**
