### PR TITLE
C++20 std::views::reverse

### PR DESCRIPTION
**Pull request by stickies-v**
C++20 introduces [`std::ranges::views::reverse`](https://en.cppreference.com/w/cpp/ranges/reverse_view), which allows us to drop our own `reverse_iterator.h` implementation and also makes it easier to chain views (even though I think we currently don't use this).

### CODE REVIEW

**Comment by fanquake** [comment]
cc @sipa you might have some insight here in regards to prevector.

**Comment by stickies-v** [comment]
> Needs rebase

Thx, rebased to include #28349 & updated PR description

**Comment by fanquake** [comment]
https://github.com/bitcoin/bitcoin/pull/28687/checks?check_run_id=19528202548
```bash
/usr/bin/ccache clang++-13 -stdlib=libc++ -std=c++20 -DHAVE_CONFIG_H -I. -I../src/config  -fmacro-prefix-map=/ci_container_base/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu=. -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -DHAVE_BUILD_INFO -DPROVIDE_FUZZ_MAIN_FUNCTION -I. -I./minisketch/include -I./secp256k1/include -I./univalue/include -I./leveldb/include -isystem /ci_container_base/depends/x86_64-pc-linux-gnu/include -DBOOST_MULTI_INDEX_DISABLE_SERIALIZATION -DBOOST_NO_CXX98_FUNCTION_BASE   -isystem /ci_container_base/depends/x86_64-pc-linux-gnu/include -pthread -I/ci_container_base/depends/x86_64-pc-linux-gnu/include  -I/ci_container_base/depends/x86_64-pc-linux-gnu/include/  -fdebug-prefix-map=/ci_container_base/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu=. -Wstack-protector -fstack-protector-all -fcf-protection=full -fstack-clash-protection   -Werror    -fvisibility=hidden -fPIE -pipe -std=c++20 -O2  -c -o libbitcoin_node_a-net_processing.o `test -f 'net_processing.cpp' || echo './'`net_processing.cpp
net_processing.cpp:2074:62: error: no member named 'reverse' in namespace 'std::views'
            for (const uint256& hash : vHashes | std::views::reverse) {
                                                 ~~~~~~~~~~~~^
net_processing.cpp:2760:69: error: no member named 'reverse' in namespace 'std::views'
            for (const CBlockIndex *pindex : vToFetch | std::views::reverse) {
                                                        ~~~~~~~~~~~~^
2 errors generated.
```

Looks like ranges didn't become complete / non-experimental in LLVM until version 16: https://releases.llvm.org/16.0.0/projects/libcxx/docs/ReleaseNotes.html
> The C++20 ranges library has been completed and is no longer experimental (with the exception of ranges::join_view which is still marked as experimental because it is about to undergo an ABI-breaking change in the Standard due to [D2770](https://isocpp.org/files/papers/D2770R0.html)). Work on C++23 ranges has started.

**Comment by fanquake** [comment]
> Interesting that the guix macOS build passed, given that it is on clang-15, no?

I'd guess this is because our macOS SDK (libc++) is from Xcode 15, which is based on LLVM ~16, and [includes support for ranges](https://developer.apple.com/xcode/cpp/#c++20). So as long as clang-15 can compile it, which it should given vanilla LLVM supports the use of ranges (experimentally) in 15, it probably works.

**Comment by fanquake** [comment]
> Though, on GHA it says XCode 14.3

According to https://developer.apple.com/xcode/cpp/#c++20, "Ranges" have been available on macOS since Xcode 14.3.

**Comment by fanquake** [comment]
> (Possibly?) fixed in https://github.com/bitcoin/bitcoin/pull/29275

Looks like it does, this compiles for me locally atleast: https://github.com/fanquake/bitcoin/tree/28687_29275.

@stickies-v can you rebase this branch on top of #29275.

**Comment by fanquake** [comment]
Could rebase, and update the PR description? Ideally this is now just blocked on our supported compiler versions.

**Comment by stickies-v** [comment]
Force pushed to:
- rebase after #29091 got merged, which now makes the `previous releases, depends DEBUG` task pass
- rebase on top of #29165 (e95d88b197cd49040b693f33367e055dbf90b276), which will make `multiprocess, i686, DEBUG` pass when merged

`no wallet, libbitcoinkernel` is now the only remaining failing CI task, afaict requiring a bump to clang-16 too

**Comment by stickies-v** [comment]
Rebased on top of https://github.com/bitcoin/bitcoin/pull/29765. One more task to go 🤞

**Comment by stickies-v** [comment]
Force pushed to address merge conflict from #28830 and rebase on top of #30263

**Comment by stickies-v** [comment]
With https://github.com/bitcoin/bitcoin/pull/30263 merged, this PR is now ready for review 🥳

**Comment by stickies-v** [comment]
Force pushed to address merge conflict from https://github.com/bitcoin/bitcoin/pull/28052/

**Comment by achow101** [comment]
ACK 2925bd537cbd8c70594e23f6c4298b7101f7f73d

**Comment by TheCharlatan** [comment]
Post-merge ACK 2925bd537cbd8c70594e23f6c4298b7101f7f73d

**Pull request merged**
