### PR TITLE
build: Allow to configure --with-sanitizers=fuzzer

### PR DESCRIPTION
**Pull request by maflcko**

### CODE REVIEW

**Comment by practicalswift** [comment]
Concept ACK

**Comment by laanwj** [comment]
Might be useful to document this somewhere.

**Comment by MarcoFalke** [comment]
Added documentation

**Comment by fanquake** [comment]
Concept/utACK fad058a

Annoyingly, this doesn't work out of the box on macOS:
```
checking whether C++ compiler accepts -Werror... yes
checking whether C++ compiler accepts -fsanitize=fuzzer,address... yes
checking whether the linker accepts -fsanitize=fuzzer,address... no
configure: error: linker did not accept requested flags, you are missing required libraries
```

Seemingly because `Xcode 10` doesn't include a copy of `libclang_rt.fuzzer_osx.a`. i.e:
```
clang++ -fsanitize=fuzzer -o fuzzme fuzzme.cpp
ld: file not found: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/lib/darwin/libclang_rt.fuzzer_osx.a
clang: error: linker command failed with exit code 1 (use -v to see invocation)
``` 

Configuring Core with all other sanitizers, `address`, `thread`, `undefined` etc, works correctly. 

Will test in a Linux env shortly.

**Pull request merged**
