### PR TITLE
[23.x] GUI backports

### PR DESCRIPTION
**Pull request by hebasto**
Backports from the GUI repo:
- bitcoin-core/gui#555
- bitcoin-core/gui#568

### CODE REVIEW

**Comment by Sjors** [comment]
ACK 642f2726deaa1dad21912d4319fac0deb6dbb564

**Comment by gruve-p** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/24596/commits/642f2726deaa1dad21912d4319fac0deb6dbb564

**Comment by luke-jr** [comment]
Approach NACK. This should just be a merge of the exact same commits/PR; it doesn't need a separate cherry-pick.

**Comment by hebasto** [comment]
> Approach NACK. This should just be a merge of the exact same commits/PR; it doesn't need a separate cherry-pick.

As usual, the [`backport.py`](https://github.com/bitcoin-core/bitcoin-maintainer-tools/blob/main/backport.py) script was used to prepare this PR.

**Comment by Sjors** [comment]
I guess a new merge commit, rather than cherry-picking, has the benefit of preserving my commit signatures.

I don't know how easy it is to implement that in the backport script. I could also make a cherry-pick PR myself :-)

**Comment by luke-jr** [comment]
>As usual, the backport.py script was used to prepare this PR.

Point is, that's not needed (and therefore shouldn't be used) for this PR.

**Comment by fanquake** [comment]
@Sjors @gruve-p @vasild @mzumsande want to (re)-review so we can get these couple of backports in.

**Comment by gruve-p** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/24596/commits/70f2c579b9de41f987e170f15c0ce767d9ad7931

**Comment by MarcoFalke** [comment]
I can see why it is minimally cleaner (from a `git` perspective) to not cherry-pick unless required, but I don't think this is reason enough to NACK this pull, since there won't be any difference for end-users (except for the git hash that is embedded in the binary).

**Comment by vasild** [comment]
ACK 70f2c579b9de41f987e170f15c0ce767d9ad7931

@luke-jr, how could this be a merge instead of cherry-picks? I do not think this is possible, but maybe I am missing something. What exact `git` commands would create such a merge? There are intermediate, undesired, commits in `master`, a merge would drag them into `23.x` too.

**Comment by MarcoFalke** [comment]
I think this would only be possible for pull requests which happen to be (or are intentionally) based on any commit pre-branch-off.

**Pull request merged**
