### PR TITLE
doc: rename wallet-tool references to bitcoin-wallet

### PR DESCRIPTION
**Pull request by hel-o**
Fix. text reference to executable bitcoin-wallet instead of wallet-tool, there is not a wallet-tool at bin/ folder.

### CODE REVIEW

**Comment by laanwj** [comment]
there's two other mentions of the old name, maybe adopt those too
```
src/wallet/wallet.cpp:    // If wallet doesn't have a chain (e.g wallet-tool), lock can't be taken.
src/wallet/wallet.cpp:    // tx status. If lock can't be taken (e.g wallet-tool), tx confirmation
```

**Comment by hel-o** [comment]
Commit done.

**Comment by fanquake** [comment]
Please [squash your commits](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#squashing-commits) and update to use a commit message like `doc: rename wallet-tool references to bitcoin-wallet`.

**Review by fanquake — APPROVED** [review]
ACK e7ad4a2f8c07a82d6424b473f0d51dbd8f897b10 - thanks for following up.

**Pull request merged**
