### PR TITLE
doc: provide context for CNetAddr::UnserializeV1Array() and span.h with lifetimebound

### PR DESCRIPTION
**Pull request by jonatack**
Add contextual documentation for developers and future readers of the code regarding
- CNetAddr::UnserializeV1Array (see #22140)
- Span and why it defines Clang lifetimebound locally rather than using the one in attributes.h

### CODE REVIEW

**Comment by jonatack** [comment]
I just saw this explanatory comment at the time: https://github.com/bitcoin/bitcoin/pull/19387/files#r451060526. Not sure if the context is still the same, as the `attributes` header file previously contained other code.

**Comment by sipa** [comment]
Yeah, this was done intentionally to keep span.h reusable without depending on other project files. I don't think anything changed about that.

I don't personally feel strongly either way; just pointing out the reason.

**Comment by practicalswift** [comment]
cr ACK 419d4767d07f0d9affddca6bb8c469ae79a47d63

**Comment by fanquake** [comment]
cc @theuni

**Comment by jonatack** [comment]
(If it is preferred to keep span.h self-contained, I'd be tempted to convert this patch to documenting the intention and reason here and wrt #22140 to help future readers of the code.)

**Comment by laanwj** [comment]
No strong opinion here, remember that in principle the entire file can be considered temporary compatibility code until c++20, it's fine with me to treat it as a self-contained drop-in instead of really a part of our project.

**Comment by jonatack** [comment]
Updated this patch to provide contextual documentation for developers regarding
- CNetAddr::UnserializeV1Array, e.g. #22140
- Span and why it defines Clang lifetimebound locally rather than using the one in attributes.h

**Comment by laanwj** [comment]
Thanks for the clarifications.
Documentation review ACK 33c6a208a9e2512a174c99c224a933a59f091bc2

**Pull request merged**
