### PR TITLE
jumpstart headers sync

### PR DESCRIPTION
**Pull request by pstratem**
triggers headers download on connection with another network node

### CODE REVIEW

**Comment by sdaftuar** [comment]
Not sure I entirely understand the goal here -- after #5662, we are now going to be sending getheaders to all network nodes, just not immediately.  Instead, we wait until our headers chain is almost current (```pindexBestHeader->GetBlockTime() > GetAdjustedTime() - 24 * 60 * 60```), and then we send getheaders to all our network peers.

My understanding is that we do this so that we're not downloading the full headers chain from multiple peers unnecessarily.  There is a tradeoff there, but I think even if we are to consider a different tradeoff and be more willing to download duplicate data, then the right way to do it would involve changing the code in SendMessages (around line 4955).

**Comment by pstratem** [comment]
The intent is to download headers from all peers which claim to be able to.

The selection of the first peer can get you stuck until the next block is found.

You're right about the placement of the code though.

**Comment by pstratem** [comment]
and im using the wrong flag!

**Comment by pstratem** [comment]
i'll get back to this later...

**Pull request closed without merging**
