### PR TITLE
util: Show descriptive error messages when FileCommit fails

### PR DESCRIPTION
**Pull request by john-moffett**
Only raw [`errno`](https://en.cppreference.com/w/cpp/error/errno) int values are logged if `FileCommit` fails. These values are implementation-specific, so it makes it harder to debug based on user reports. For instance, https://github.com/bitcoin/bitcoin/issues/26455#issue-1436654238 and [another](https://bitcointalk.org/index.php?topic=5182526.0#:~:text=FileCommit%3A%20FlushFileBuffers%20failed%3A%205).

Instead, use `SysErrorString` (or the refactored Windows equivalent `Win32ErrorString`) to display both the raw int value and the descriptive message. All other instances in the code I could find where `errno` or (Windows-only) `GetLastError()`/`WSAGetLastError()` are logged use the full descriptive string. For example:

https://github.com/bitcoin/bitcoin/blob/1b680948d43b1d39645b9d839a6fa7c6c1786b51/src/util/sock.cpp#L390

https://github.com/bitcoin/bitcoin/blob/1b680948d43b1d39645b9d839a6fa7c6c1786b51/src/util/sock.cpp#L272

https://github.com/bitcoin/bitcoin/blob/7e1007a3c6c9a921c2b60919b84a60eaabfe1c5d/src/netbase.cpp#L515-L516

https://github.com/bitcoin/bitcoin/blob/8ccab65f289e3cce392cbe01d5fc0e7437f51f1e/src/init.cpp#L164 

I refactored the Windows formatting code to put it in `syserror.cpp`, as it's applicable to all Win32 API system errors, not just networking errors. To be clear, the Windows API functions `WSAGetLastError()` and `GetLastError()` are currently [equivalent](https://stackoverflow.com/questions/15586224/is-wsagetlasterror-just-an-alias-for-getlasterror).

### CODE REVIEW

**Review by fanquake — COMMENTED** [review]
Somewhat unrelated, but after this change, how often are we using the
```cpp
#ifdef WIN32
    if (strerror_s(...
```

case in `SysErrorString`? Wondering if we can (in general) further consolidate this error logging.

**Comment by john-moffett** [comment]
@fanquake Great suggestions, thanks. Will incorporate them all shortly. 



> Somewhat unrelated, but after this change, how often are we using the
> 
> ```c++
> #ifdef WIN32
>     if (strerror_s(...
> ```
> 
> case in `SysErrorString`? Wondering if we can (in general) further consolidate this error logging.

I don't think in many places. In addition to the potential use of it for `fflush` in this PR, there's this:

https://github.com/bitcoin/bitcoin/blob/3eaf7be6ade22c99f3c0000122e49b94de868d74/src/init.cpp#L164

If I artificially trigger that using the current code (by giving it an impossible path), it shows:

image

If I substitute it with `Win32ErrorString(GetLastError())`, I get:

image

Since the error codes are [unrelated](https://stackoverflow.com/questions/20056851/getlasterror-errno-formatmessagea-and-strerror-s#comment29875130_20056851) (`errno` and `GetLastError()` return different actual values), I think it'd be difficult to consolidate effectively.

Potentially, we could have a `std::string GetSystemErrorReason()` function that called `SysErrorString(errno)` on non-Win32 and `Win32ErrorString(GetLastError())` on Win32, but I'm not certain that (on Win32) _every time_ `errno` is set that `GetLastError()` is also set.

**Comment by hebasto** [comment]
Concept ACK.

**Comment by glozow** [comment]
@john-moffett please rebase?

**Comment by john-moffett** [comment]
Thanks for reminding me! Will rebase tomorrow.

**Review by maflcko — APPROVED** [review]
nice. lgtm, but I didn't look at the windows stuff

**Pull request merged**
