### PR TITLE
guix: Use $HOST instead of generic osx{64} for macOS artifacts

### PR DESCRIPTION
**Pull request by hebasto**
On master (f94784f5bcfd0adf5d20f9631cde454348b4ff71) and 23.x branches some GUIX artifacts for `x86_64` and `arm64` macOS have indistinguishable names:
```
d34646cbaf05e03195eb1e426f72fb471fe2d87ab18c9a656600089597703a38  bitcoin-23.0rc2-arm64-apple-darwin.tar.gz
968767b39442e179e5976b948112a0904374eb4cfb9cba22863408a70a1d99f9  bitcoin-23.0rc2-osx-unsigned.dmg
d8a7037d5bb845a214e45a52abcf9119bfbe72a76d6370e9560c18fda74a70db  bitcoin-23.0rc2-osx-unsigned.tar.gz
71092f37985d556bdd25d33fb8571e13664eacadda90efcf21eaa1ba8a32eabd  bitcoin-23.0rc2-osx-unsigned.dmg
cb10c49b486085b89393955a7a168c32e2f2a4911f2b8d44494bd8f2bd0acf2f  bitcoin-23.0rc2-osx-unsigned.tar.gz
6d4c44726cd45711c4cb7257c6b46731be1446fc85e79ac86f2def19be45ced3  bitcoin-23.0rc2-osx64.tar.gz
```

With this PR:
```
$ find guix-build-$(git rev-parse --short=12 HEAD)/output/ -type f -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum
054c3765381b6d59c6ad8e5e3cbbdd23e330bd579f88b399f78f296d1a4536d0  guix-build-53dd6165b899/output/arm64-apple-darwin/SHA256SUMS.part
18750c1ff71d014fe5f976da738bfa04a4cd02af6b0d575def8d83160552de2d  guix-build-53dd6165b899/output/arm64-apple-darwin/bitcoin-53dd6165b899-arm64-apple-darwin-unsigned.dmg
fa2b16684060202d1918c658b446909ee10999a8b9a85018ca2f6a09eaa11c8e  guix-build-53dd6165b899/output/arm64-apple-darwin/bitcoin-53dd6165b899-arm64-apple-darwin-unsigned.tar.gz
b865000eb4b291a51d1920eec63dcbc9b47dedb1cc7fda0af3ab9b321db36b82  guix-build-53dd6165b899/output/arm64-apple-darwin/bitcoin-53dd6165b899-arm64-apple-darwin.tar.gz
dd88ce6660754987abf95fc2c4d09f6d2248f12ecee4ef2c03f4fa74bbd8e3ae  guix-build-53dd6165b899/output/dist-archive/bitcoin-53dd6165b899.tar.gz
fb1871c134e079aa970c5317cad258540e2642cc7ff60a794c85651c85fc6fc4  guix-build-53dd6165b899/output/x86_64-apple-darwin/SHA256SUMS.part
b1f4c04f7dbd85798ed7cd76fd7948299dfb5653c6c68df0b0839be1c1b295dd  guix-build-53dd6165b899/output/x86_64-apple-darwin/bitcoin-53dd6165b899-x86_64-apple-darwin-unsigned.dmg
f1f8b2774ba3028d6cdde509076614067a6affc0fa176fdbb03829109ae47022  guix-build-53dd6165b899/output/x86_64-apple-darwin/bitcoin-53dd6165b899-x86_64-apple-darwin-unsigned.tar.gz
20b9386a81e70f848db7c4f14bcb6cf2fbc1dc17aad1b9a2e6f04ac6fa86a4c9  guix-build-53dd6165b899/output/x86_64-apple-darwin/bitcoin-53dd6165b899-x86_64-apple-darwin.tar.gz
6f764a8fe876359d3c377fd934eb6595cc06d746980e07320565566abe9409f9  guix-build-53dd6165b899/output/x86_64-w64-mingw32/SHA256SUMS.part
446b24b2e01608d3dc09db29545db2cdb716c161b19356f4fae930d3ebb299f8  guix-build-53dd6165b899/output/x86_64-w64-mingw32/bitcoin-53dd6165b899-win64-debug.zip
d1660e6839a1358ae2d164958b551b81338cca9b740b3dc314397a35b17ba2a6  guix-build-53dd6165b899/output/x86_64-w64-mingw32/bitcoin-53dd6165b899-win64-setup-unsigned.exe
4ab0d948f3864f0d5d220c570b57a02e040f936a8f6b9dba3b4688c80667def9  guix-build-53dd6165b899/output/x86_64-w64-mingw32/bitcoin-53dd6165b899-win64-unsigned.tar.gz
481177329998fcbb71ab1fc9542a6ffcea623cebddf567981cfa76a7320ec115  guix-build-53dd6165b899/output/x86_64-w64-mingw32/bitcoin-53dd6165b899-win64.zip
```

Also naming of Windows artifacts has been improved.

### CODE REVIEW

**Comment by hebasto** [comment]
cc @achow101 @dongcarl 

Backport to 23.x for rc3?

**Comment by achow101** [comment]
Concept ACK, will test when I get to my guix building machine.

I think we will need to backport this as otherwise the filenames will collide and we will accidentally lose one of the archs when uploading to the download server (all output files are in the same directory rather than split by host as guix outputs).

**Comment by fanquake** [comment]
Concept ACK

**Comment by gruve-p** [comment]
Concept ACK

**Comment by laanwj** [comment]
Code review ACK 933a43018f0f1c0b72acbfa9de5e0f84bf49d0a2

Just ran into this problem while trying to upload the binaries for rc2.

>I think we will need to backport this as otherwise the filenames will collide and we will accidentally lose one of the archs when uploading to the download server

Yes. Luckily my move script checks for this eventuality so I noticed.

**Comment by laanwj** [comment]
Looking at the list of files this leaves Windows as the "odd one out" with regard to naming:
```
bitcoin-23.0rc2-win64-setup.exe
bitcoin-23.0rc2-win64.zip
```
I'm not sure how important consistency is. If not,  I don't think we need to rename them until another processor architecture becomes popular for windows.

Another inconsistency is that windows has `-unsigned` and (no suffix), while osx has `-unsigned` and `-signed`. We might want to while we're at it. For the [rc2 upload](https://bitcoincore.org/bin/bitcoin-core-23.0/test.rc2/) I left out the `-signed` in the `dmg` name.

**Comment by hebasto** [comment]
> Another inconsistency is that windows has `-unsigned` and (no suffix), while osx has `-unsigned` and `-signed`. We might want to reconcile these while we're at it. For the [rc2 upload](https://bitcoincore.org/bin/bitcoin-core-23.0/test.rc2/) I left out the `-signed` in the signed `dmg` name. Fixing it the other way around would be possible too.

A dedicated commit has been added.

**Comment by fanquake** [comment]
Guix Build:
```bash
bash-5.1# find guix-build-$(git rev-parse --short=12 HEAD)/output/ -type f -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum
c7e2e15aa352da10b269173a224b453adb2871db2327582959f4dd3d6e91b371  guix-build-4b4b04a66d8f/output/arm64-apple-darwin/SHA256SUMS.part
5f673a4cf06036b8eb33ab676e4237204ad2e889d9d977e1866741d61962574c  guix-build-4b4b04a66d8f/output/arm64-apple-darwin/bitcoin-4b4b04a66d8f-arm64-apple-darwin-unsigned.dmg
abbbf4f069b1f53088c11d4fa73919268b3cec1f34e77cb88516cb525ed9c8ef  guix-build-4b4b04a66d8f/output/arm64-apple-darwin/bitcoin-4b4b04a66d8f-arm64-apple-darwin-unsigned.tar.gz
428cd0bf8a3d8c82e2e36cc266100701f22ea73d9313d97c49ed52139e79805b  guix-build-4b4b04a66d8f/output/arm64-apple-darwin/bitcoin-4b4b04a66d8f-arm64-apple-darwin.tar.gz
3cb6adf4c6fb626cd7c15b681bba7bebbfb99844124101b97e77ff07fd3ea667  guix-build-4b4b04a66d8f/output/dist-archive/bitcoin-4b4b04a66d8f.tar.gz
69f6d39783efde46e1a4ec908a4fc368b90c7f2d85fa87f40b054454a77fa84e  guix-build-4b4b04a66d8f/output/x86_64-apple-darwin/SHA256SUMS.part
19e6a4b8625ddce402fc18cc65293b66c362666b1a9355b91699f880a504f612  guix-build-4b4b04a66d8f/output/x86_64-apple-darwin/bitcoin-4b4b04a66d8f-x86_64-apple-darwin-unsigned.dmg
e515163e9b7fbd3554971a4b0601e018e7424f073a5d496a04917ab814d9dfea  guix-build-4b4b04a66d8f/output/x86_64-apple-darwin/bitcoin-4b4b04a66d8f-x86_64-apple-darwin-unsigned.tar.gz
0a803a2624ec8d47b68da3bde2e85f6fa903119a1aebbc1fac583b48de37428e  guix-build-4b4b04a66d8f/output/x86_64-apple-darwin/bitcoin-4b4b04a66d8f-x86_64-apple-darwin.tar.gz
e59f65ce90e082c4bb472d7542cdec6ce8b2c4692934a9fc678bbd6e171ef0a7  guix-build-4b4b04a66d8f/output/x86_64-w64-mingw32/SHA256SUMS.part
0a14e12232b73a0727912b76778e1b4e60ebb10c9bb479c8000ae8d0d6421efc  guix-build-4b4b04a66d8f/output/x86_64-w64-mingw32/bitcoin-4b4b04a66d8f-win-unsigned.tar.gz
bd564d3603df41c09c447e3789b1afce3803f66244e73597f389f90d14a85a78  guix-build-4b4b04a66d8f/output/x86_64-w64-mingw32/bitcoin-4b4b04a66d8f-win64-debug.zip
c2474785fd47d2937df30fe5bd9a07cb78504e6257cc97da2b5eac0359118f0c  guix-build-4b4b04a66d8f/output/x86_64-w64-mingw32/bitcoin-4b4b04a66d8f-win64-setup-unsigned.exe
29880c988297efd35bb51160bdd8afc658cc1b86386f6cd7d101057c2192c167  guix-build-4b4b04a66d8f/output/x86_64-w64-mingw32/bitcoin-4b4b04a66d8f-win64.zip
```

If we are making changes to make the outputs consistent, we should probably make the unsigned windows tarball `win64-unsigned.tar.gz`:

> bitcoin-4b4b04a66d8f-win-unsigned.tar.gz
bitcoin-4b4b04a66d8f-win64-debug.zip
bitcoin-4b4b04a66d8f-win64-setup-unsigned.exe
bitcoin-4b4b04a66d8f-win64.zip

**Comment by hebasto** [comment]
> If we are making changes to make the outputs consistent, we should probably make the unsigned windows tarball `win64-unsigned.tar.gz`:
> 
> > bitcoin-4b4b04a66d8f-win-unsigned.tar.gz
> > bitcoin-4b4b04a66d8f-win64-debug.zip
> > bitcoin-4b4b04a66d8f-win64-setup-unsigned.exe
> > bitcoin-4b4b04a66d8f-win64.zip

Fixed.

**Comment by fanquake** [comment]
Guix Build:
```bash
bash-5.1# find guix-build-$(git rev-parse --short=12 HEAD)/output/ -type f -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum
054c3765381b6d59c6ad8e5e3cbbdd23e330bd579f88b399f78f296d1a4536d0  guix-build-53dd6165b899/output/arm64-apple-darwin/SHA256SUMS.part
18750c1ff71d014fe5f976da738bfa04a4cd02af6b0d575def8d83160552de2d  guix-build-53dd6165b899/output/arm64-apple-darwin/bitcoin-53dd6165b899-arm64-apple-darwin-unsigned.dmg
fa2b16684060202d1918c658b446909ee10999a8b9a85018ca2f6a09eaa11c8e  guix-build-53dd6165b899/output/arm64-apple-darwin/bitcoin-53dd6165b899-arm64-apple-darwin-unsigned.tar.gz
b865000eb4b291a51d1920eec63dcbc9b47dedb1cc7fda0af3ab9b321db36b82  guix-build-53dd6165b899/output/arm64-apple-darwin/bitcoin-53dd6165b899-arm64-apple-darwin.tar.gz
dd88ce6660754987abf95fc2c4d09f6d2248f12ecee4ef2c03f4fa74bbd8e3ae  guix-build-53dd6165b899/output/dist-archive/bitcoin-53dd6165b899.tar.gz
fb1871c134e079aa970c5317cad258540e2642cc7ff60a794c85651c85fc6fc4  guix-build-53dd6165b899/output/x86_64-apple-darwin/SHA256SUMS.part
b1f4c04f7dbd85798ed7cd76fd7948299dfb5653c6c68df0b0839be1c1b295dd  guix-build-53dd6165b899/output/x86_64-apple-darwin/bitcoin-53dd6165b899-x86_64-apple-darwin-unsigned.dmg
f1f8b2774ba3028d6cdde509076614067a6affc0fa176fdbb03829109ae47022  guix-build-53dd6165b899/output/x86_64-apple-darwin/bitcoin-53dd6165b899-x86_64-apple-darwin-unsigned.tar.gz
20b9386a81e70f848db7c4f14bcb6cf2fbc1dc17aad1b9a2e6f04ac6fa86a4c9  guix-build-53dd6165b899/output/x86_64-apple-darwin/bitcoin-53dd6165b899-x86_64-apple-darwin.tar.gz
6f764a8fe876359d3c377fd934eb6595cc06d746980e07320565566abe9409f9  guix-build-53dd6165b899/output/x86_64-w64-mingw32/SHA256SUMS.part
446b24b2e01608d3dc09db29545db2cdb716c161b19356f4fae930d3ebb299f8  guix-build-53dd6165b899/output/x86_64-w64-mingw32/bitcoin-53dd6165b899-win64-debug.zip
d1660e6839a1358ae2d164958b551b81338cca9b740b3dc314397a35b17ba2a6  guix-build-53dd6165b899/output/x86_64-w64-mingw32/bitcoin-53dd6165b899-win64-setup-unsigned.exe
4ab0d948f3864f0d5d220c570b57a02e040f936a8f6b9dba3b4688c80667def9  guix-build-53dd6165b899/output/x86_64-w64-mingw32/bitcoin-53dd6165b899-win64-unsigned.tar.gz
481177329998fcbb71ab1fc9542a6ffcea623cebddf567981cfa76a7320ec115  guix-build-53dd6165b899/output/x86_64-w64-mingw32/bitcoin-53dd6165b899-win64.zip
```

**Comment by gruve-p** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/24549/commits/53dd6165b8994301d638298906b006032e0bbe48

**Comment by achow101** [comment]
```
054c3765381b6d59c6ad8e5e3cbbdd23e330bd579f88b399f78f296d1a4536d0  guix-build-53dd6165b899/output/arm64-apple-darwin/SHA256SUMS.part
18750c1ff71d014fe5f976da738bfa04a4cd02af6b0d575def8d83160552de2d  guix-build-53dd6165b899/output/arm64-apple-darwin/bitcoin-53dd6165b899-arm64-apple-darwin-unsigned.dmg
fa2b16684060202d1918c658b446909ee10999a8b9a85018ca2f6a09eaa11c8e  guix-build-53dd6165b899/output/arm64-apple-darwin/bitcoin-53dd6165b899-arm64-apple-darwin-unsigned.tar.gz
b865000eb4b291a51d1920eec63dcbc9b47dedb1cc7fda0af3ab9b321db36b82  guix-build-53dd6165b899/output/arm64-apple-darwin/bitcoin-53dd6165b899-arm64-apple-darwin.tar.gz
dd88ce6660754987abf95fc2c4d09f6d2248f12ecee4ef2c03f4fa74bbd8e3ae  guix-build-53dd6165b899/output/dist-archive/bitcoin-53dd6165b899.tar.gz
fb1871c134e079aa970c5317cad258540e2642cc7ff60a794c85651c85fc6fc4  guix-build-53dd6165b899/output/x86_64-apple-darwin/SHA256SUMS.part
b1f4c04f7dbd85798ed7cd76fd7948299dfb5653c6c68df0b0839be1c1b295dd  guix-build-53dd6165b899/output/x86_64-apple-darwin/bitcoin-53dd6165b899-x86_64-apple-darwin-unsigned.dmg
f1f8b2774ba3028d6cdde509076614067a6affc0fa176fdbb03829109ae47022  guix-build-53dd6165b899/output/x86_64-apple-darwin/bitcoin-53dd6165b899-x86_64-apple-darwin-unsigned.tar.gz
20b9386a81e70f848db7c4f14bcb6cf2fbc1dc17aad1b9a2e6f04ac6fa86a4c9  guix-build-53dd6165b899/output/x86_64-apple-darwin/bitcoin-53dd6165b899-x86_64-apple-darwin.tar.gz
6f764a8fe876359d3c377fd934eb6595cc06d746980e07320565566abe9409f9  guix-build-53dd6165b899/output/x86_64-w64-mingw32/SHA256SUMS.part
446b24b2e01608d3dc09db29545db2cdb716c161b19356f4fae930d3ebb299f8  guix-build-53dd6165b899/output/x86_64-w64-mingw32/bitcoin-53dd6165b899-win64-debug.zip
d1660e6839a1358ae2d164958b551b81338cca9b740b3dc314397a35b17ba2a6  guix-build-53dd6165b899/output/x86_64-w64-mingw32/bitcoin-53dd6165b899-win64-setup-unsigned.exe
4ab0d948f3864f0d5d220c570b57a02e040f936a8f6b9dba3b4688c80667def9  guix-build-53dd6165b899/output/x86_64-w64-mingw32/bitcoin-53dd6165b899-win64-unsigned.tar.gz
481177329998fcbb71ab1fc9542a6ffcea623cebddf567981cfa76a7320ec115  guix-build-53dd6165b899/output/x86_64-w64-mingw32/bitcoin-53dd6165b899-win64.zip
```

**Comment by achow101** [comment]
ACK 53dd6165b8994301d638298906b006032e0bbe48

**Comment by fanquake** [comment]
Backported in #24593.

**Pull request merged**
