### PR TITLE
net: split resolve out of connect

### PR DESCRIPTION
**Pull request by theuni**
This is a greatly simplified version of #10285, which only aims to address async resolving.

It essentially breaks up two wrapper functions for things only used in one place (ConnectSocketDirectly/ConnectThroughProxy) in favor of calling them directly. This allows us to fully handle resolves before attempting a connection, as is necessary for async connections.

As a bonus, I believe the logic is now much easier to follow than before.

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
utACK 13015a6bea5bc9e82c8fa207f2c9d6489aff6589. Still want to see something happen on the RAII-ifying SOCKET wrapper, but this shouldnt have any effect.

**Comment by laanwj** [comment]
Need rebase.

**Comment by theuni** [comment]
Rebased.

Unfortunately, this as well as a follow-up will be needed before #11227, in order to avoid an unlikely race at shutdown (events must be added from the event-handler thread, otherwise they may be added at the same time that the handler is being torn down). That's a step in the right direction anyway though, as it's needed for async connections themselves.

I'm working on the follow-up now.

**Comment by laanwj** [comment]
utACK b887676

**Pull request merged**
