### PR TITLE
[24.x] Backports

### PR DESCRIPTION
**Pull request by fanquake**
Backports:
* https://github.com/bitcoin/bitcoin/pull/26595
* https://github.com/bitcoin/bitcoin/pull/26675
* https://github.com/bitcoin/bitcoin/pull/26679
* https://github.com/bitcoin/bitcoin/pull/26761
* https://github.com/bitcoin/bitcoin/pull/26837
* https://github.com/bitcoin/bitcoin/pull/26909
* https://github.com/bitcoin/bitcoin/pull/26924
* https://github.com/bitcoin/bitcoin/pull/26944
* https://github.com/bitcoin-core/gui/pull/704
* https://github.com/bitcoin/bitcoin/pull/27053
* https://github.com/bitcoin/bitcoin/pull/27080

### CODE REVIEW

**Comment by fanquake** [comment]
Added #26234 & #26388 to fix the no-longer available Intel macOS box in the CI.

**Review by hebasto — APPROVED** [review]
ACK 784a754aa47ce10c6fd99c09cdfc76ee9bc91652, I've made backporting locally and got a diff between my branch and this PR as follows:
```diff
--- a/test/functional/wallet_importdescriptors.py
+++ b/test/functional/wallet_importdescriptors.py
@@ -484,8 +484,8 @@ class ImportDescriptorsTest(BitcoinTestFramework):
         assert_equal(addr, 'bcrt1qp8s25ckjl7gr6x2q3dx3tn2pytwp05upkjztk6ey857tt50r5aeqn6mvr9') # Derived at m/84'/0'/0'/1
         change_addr = wmulti_pub.getrawchangeaddress('bech32') # uses change 2
         assert_equal(change_addr, 'bcrt1qp6j3jw8yetefte7kw6v5pc89rkgakzy98p6gf7ayslaveaxqyjusnw580c') # Derived at m/84'/1'/0'/2
-        assert(send_txid in self.nodes[0].getrawmempool(True))
-        assert(send_txid in (x['txid'] for x in wmulti_pub.listunspent(0)))
+        assert send_txid in self.nodes[0].getrawmempool(True)
+        assert send_txid in (x['txid'] for x in wmulti_pub.listunspent(0))
         assert_equal(wmulti_pub.getwalletinfo()['keypoolsize'], 999)
 
         # generate some utxos for next tests
```
which tracks down to 459cb637aca80f744a8399e84bc78fab60de0b5c from #26257 which, in turn, is not backported here.

---

> trivial backports as far as I can see

https://github.com/bitcoin-core/gui/pull/704 and https://github.com/bitcoin/bitcoin/pull/27053 are not trivial to backport.

**Comment by hebasto** [comment]
> ACK [784a754](https://github.com/bitcoin/bitcoin/commit/784a754aa47ce10c6fd99c09cdfc76ee9bc91652)
> 
> trivial backports as far as I can see

**Comment by achow101** [comment]
ACK 784a754aa47ce10c6fd99c09cdfc76ee9bc91652

**Pull request merged**
