### PR TITLE
Implement 64 bit arithmetic op codes in the Script interpreter

### PR DESCRIPTION
**Pull request by Christewart**
This PR adds 64 bit arithmetic op codes to the Script interpreter.

This PR corresponds with this BIP proposal: https://github.com/bitcoin/bips/pull/1538

This work is heavily borrowed from the elements implementation of 64 bit op codes: https://github.com/ElementsProject/elements/pull/1020

### CODE REVIEW

**Comment by moonsettler** [comment]
Concept ACK. i see no reason for this not to be bundled with any future amount introspection soft fork.

**Comment by tiero** [comment]
Concept ACK

**Comment by hsjoberg** [comment]
Concept ACK. This is great!

**Comment by Christewart** [comment]
Too speculative for now https://delvingbitcoin.org/t/64-bit-arithmetic-soft-fork/397/53

**Pull request closed without merging**
