### PR TITLE
Copyright headers for build scripts

### PR DESCRIPTION
**Pull request by luke-jr**
This needs sign-off from: ~~@morcos @anddam~~ @brandondahler ~~@btcdrak @casey~~ @theuni @cozz ~~@dcousens @ers35 @EthanHeilman @gavinandresen~~ @gmaxwell ~~@jamesob~~ ~~@jgarzik @jonasschnelli~~ @jtimon ~~@joshtriplett~~ @kazcw ~~@maraoz~~ @MarcoFalke ~~@maaku~~ @TheBlueMatt @fanquake ~~@musalbas~~ @pstratem ~~@paveljanik~~ @Diapolo ~~@sipa @rnicoll @SergioDemianLerner @sdaftuar @laanwj @yurizhykin @dexX7 @nomnombtc @ntrgn @ptschip @randy-waterhouse @sinetek~~

~~@knocte~~ @joshtriplett 

~~@ajtowns @dooglus @onlyjob @wtogami~~ @imwuzhh

Permission from Tim Kosse has already been obtained:

```
[22:45:45] <codesquid> yes, shouldn't be an issue to put this one under MIT license
```

### CODE REVIEW

**Comment by ers35** [comment]
I sign-off on changing the license of these build scripts as indicated.

**Comment by maaku** [comment]
I approve.

**Comment by dooglus** [comment]
I approve of adding license information.

I don't think it's a great idea to include the typo fixing commit here given the subject of this PR, but you probably don't care what I think about that.

**Comment by randy-waterhouse** [comment]
I approve of placing the build scripts under MIT license.

**Comment by laanwj** [comment]
Can't we have a general policy that everything committed to the repository must be put under MIT license?  (e.g. github shows this repository as MIT) no matter what is at the top of the file.

This just keeps going on and on and on (this pull, #8702, #8701, #8700, #8676, are just the **last few days**), Micromanaging every file in this way results in a lot of overhead for everyone involved, which could be spent on solving one of the many actual problems.

So I really never want to repeat this again.

**Comment by EthanHeilman** [comment]
I approve.

**Comment by joshtriplett** [comment]
:+1: from me.

@laanwj Agreed; I already assumed from the top-level COPYING file containing the MIT license that any contributions were under the MIT license unless otherwise specified.

**Review by dcousens — APPROVED** [review]
:+1:

**Comment by knocte** [comment]
I approve

**Comment by sipa** [comment]
I approve.

**Comment by maraoz** [comment]
Approved

**Comment by ajtowns** [comment]
Approved

**Comment by paveljanik** [comment]
Approved

**Comment by jonasschnelli** [comment]
I approve.

**Comment by rnicoll** [comment]
Approved

**Comment by onlyjob** [comment]
Approved.

**Comment by yurizhykin** [comment]
I approve and agree with @laanwj.

**Comment by MarcoFalke** [comment]
@luke-jr Many of those that were pinged already gave a permanent ACK on all of their past contributions to this repo to be explicitly MIT licensed.

**Comment by luke-jr** [comment]
@MarcoFalke Is there a record of who has done so?

**Comment by dexX7** [comment]
Approved.

**Comment by MarcoFalke** [comment]
@luke-jr e.g. https://github.com/bitcoin/bitcoin/pull/7300#issuecomment-172033561

**Comment by luke-jr** [comment]
Yes, my point is there's no easy way to find these.

**Comment by musalbas** [comment]
Fine with me.

**Comment by nomnombtc** [comment]
Approved.

But also like someone said:
>I already assumed from the top-level COPYING file containing the MIT license that any contributions were under the MIT license unless otherwise specified.

**Comment by anddam** [comment]
My contribution was trivial, but I definitely approve the PR.

**Comment by btcdrak** [comment]
Approved.

**Comment by wtogami** [comment]
Approved.

**Comment by ptschip** [comment]
I approve

**Comment by casey** [comment]
Approved

**Comment by sinetek** [comment]
Approve. sinetek Sep 27 2016

**Comment by jgarzik** [comment]
1) ACK for all my contributions, @luke-jr 

2) The project should consider something like the Linux kernel's developer sign-off, to augment the MIT license: http://developercertificate.org

**Comment by MarcoFalke** [comment]
> 2) The project should consider something like the Linux kernel's developer sign-off, to augment the MIT license: http://developercertificate.org

Agree, but I think right now we are missing the infrastructure to do so.

**Comment by ntrgn** [comment]
I approve.

**Comment by SergioDemianLerner** [comment]
Approved

**Pull request merged**
