### PR TITLE
Enable spectre mitigations when supported by compiler.

### PR DESCRIPTION
**Pull request by jameshilliard**
Potential option for resolving #12091 using compiler flags recently added in OpenSSH. Audit of assembly code in libsecp256k1 may still be required.

### CODE REVIEW

**Comment by fanquake** [comment]
@jameshilliard What's the best way to test this? I assume it will only work with very recent Clang/GCC?

Did ./configure with master + https://github.com/bitcoin/bitcoin/pull/12412/commits/20879d31ef9dc7f54cd7f4ea52a417d3b337fba5 on OS X:
```
checking whether C++ compiler accepts -Wstack-protector... yes
checking whether C++ compiler accepts -fstack-protector-all... yes
checking whether C++ compiler accepts -mfunction-return=thunk... no
checking whether C++ compiler accepts -mindirect-branch=thunk... no
checking whether C++ compiler accepts -mretpoline... no
checking whether C++ preprocessor accepts -D_FORTIFY_SOURCE=2... yes
```

**Comment by jameshilliard** [comment]
@fanquake This is pretty much untested other than checking that the flags don't get set when not available on OS X. Yeah I think you just need a really new Clang/GCC.

**Comment by theuni** [comment]
I'm not convinced that this is the right thing to do.

Not only does Bitcoin core need to be compiled this way in order to be safe, the libc and c++ stdlib need to be rebuilt as well. I'd hate to take a performance it, and only be providing a false sense of security. For example, this would not be enough to protect our current gitian builds.

Seems like this should really be done at the distro level. Are any distros forcing these on by default?

**Comment by jameshilliard** [comment]
> Seems like this should really be done at the distro level.

Tricky part is mitigations are needed at both levels and we intentionally avoid letting bitcoin core get included in distro package managers.

> Are any distros forcing these on by default?

Sounds like some plan to. Maybe we should just detect if the distro has libs with mitigations and then enable only when they do at compile time.

**Comment by eklitzke** [comment]
AIUI Spectre style attacks let an attacker read memory already mapped in their own address space (contrast to meltdown, which is much more severe). That's why the focus w/ spectre has been on JS engines: it allows "sandboxed" javascript code to read in-process browser data outside of the sandbox.

That's a serious, but very particular (and unusual) use case. What kind of attack specifically do you think this would insulate Bitcoin from?

**Pull request closed without merging**
