### PR TITLE
net processing: Only send a getheaders for one block in an INV

### PR DESCRIPTION
**Pull request by jnewbery**
Headers-first is the primary method of announcement on the network. If a node fell back sending blocks by inv, it's probably for a re-org. The final block hash provided should be the highest, so send a getheaders and then fetch the blocks we need to catch up.

Sending many GETHEADERS messages to the peer would cause them to send a large number of potentially large HEADERS messages with redundant data, which is a waste of bandwidth.

### CODE REVIEW

**Comment by jonatack** [comment]
The code changes look good. I need to verify the concept more when it's not late, e.g. that the final block hash will be the highest and the variation/savings in bandwidth.

**Comment by mzumsande** [comment]
Can the "waste of bandwidth scenario" you describe ever occur? 
My understanding was that it is currently taken care of by the send side by only including the tip in the INV in `SendMessages()`, so that there wouldn't be multiple block hashes within an INV.

**Comment by jnewbery** [comment]
> My understanding was that it is currently taken care of by the send side by only including the tip in the INV in SendMessages()

You're right that current Bitcoin Core software should only send a single block in the INV message. The point about wasting bandwidth is more for other software that may send us many blocks in a single INV, which would cause us to reply with multiple getheaders.

**Comment by sipa** [comment]
utACK 746736639e6d05acdb85c866d4c605c947d4c500

**Comment by naumenkogs** [comment]
utACK 7467366

**Review by naumenkogs — APPROVED** [review]
utACK 7467366

**Review by ajtowns — COMMENTED** [review]
ACK 746736639e6d05acdb85c866d4c605c947d4c500

I think this patch doesn't change behaviour when the peer is a bitcoind (because it will only potentially send a single block in an inv message), and is not normally relevant because most peers will do headers first download and compact blocks so will find out about blocks that way. As such, which block in the inv is the best one to query doesn't really seem decidable, so picking the last one seems as good a choice as any.

**Comment by mzumsande** [comment]
utACK 746736639e6d05acdb85c866d4c605c947d4c500 as per @ajtowns' reasoning.

**Review by jonatack — COMMENTED** [review]
ACK 746736639e6d05acdb85c866d4c605c947d4c500

Code review and light sanity check running bitcoind with added debug logging in this change for a bit more than a day. Perhaps update the code comments with @ajtowns' feedback.

**Comment by amitiuttarwar** [comment]
post merge ack 7467366

**Pull request merged**
