### PR TITLE
assumeutxo, rpc: Add 'start' parameter to loadtxoutset

### LINKED ISSUE #28620: rpc: make loadtxoutset async
### Please describe the feature you'd like to see added.

`loadtxoutset` should return more quickly, perhaps just checking that the file exists. There should be another RPC to monitor the status.

### Is your feature related to a problem, if so please describe it.

1. `loadtxoutset` takes too long, even requiring `-rpctimeout=0`. This makes it hard for potential integrations like Umbrel, BTCPay server or Specter desktop to show progress.

2. Progress can only be followed via the debug log, which is too noisy during IBD.

### Describe the solution you'd like

It could follow the same pattern as `scanblocks`, with `start`, `status` and `abort`. The latter two won't need an argument. This would not be backwards compatible, but imo that's fine as long as it lands before mainnet support.

### Describe any alternatives you've considered

_No response_

### Please leave any additional context

_No response_

### PR DESCRIPTION
**Pull request by hernanmarino**
Might fix https://github.com/bitcoin/bitcoin/issues/28620 

This PR only modifies the behavior of loadtxoutset to require a mandatory "start" string as a first parameter.

This change will allow to implement "status", "abort" or similar future parameters in follow-ups, without breaking the current RPC protocol with incompatible changes (if this were to be merged in the current release cycle)

Also, it is implemented in a minimalist way, to make it easy to review.

### CODE REVIEW

**Review by pablomartin4btc — COMMENTED** [review]
Concept ACK

**Comment by ryanofsky** [comment]
Is there another RPC method that supports subcommands ("start" "status" "abort") like this? It seems our RPC dispatching and documentation framework might have to be changed a lot to support a RPC methods with multiple subcommands if the subcommands don't all take the same parameters. Also the JSON-RPC protocol doesn't provide a way to represent subcommands, so it might be awkward for example in python to write the command as a string argument instead of a method name.

Maybe a simpler alternative would be to add loadtxoutsetstatus and loadtxoutsetabort RPC methods.

**Comment by hernanmarino** [comment]
> Is there another RPC method that supports subcommands ("start" "status" "abort") like this? 

Yes, the issue mentions `scanblocks` which folllows the exact same protocol.

**Comment by ryanofsky** [comment]
Thanks for the examples. This confirms my doubts about the approach, since documentation produced by "bitcoin-cli help scanblocks" is pretty messy, and it seems like this approach can only work if none of the other subcommands take any positional RPC arguments, since they would conflict with arguments for the "start" subcommand.

So having separate RPC methods still seems a little cleaner to me, but maybe it's worth accepting some limitations if it makes the 3 RPCs more consistent with each other. Either way seems reasonable.

**Comment by hernanmarino** [comment]
> Thanks for the examples. This confirms my doubts about the approach, since documentation produced by "bitcoin-cli help scanblocks" is pretty messy, and it seems like this approach can only work if none of the other subcommands take any positional RPC arguments, since they would conflict with arguments for the "start" subcommand.
> 
> So having separate RPC methods still seems a little cleaner to me, but maybe it's worth accepting some limitations if it makes the 3 RPCs more consistent with each other. Either way seems reasonable.

Yes , although I like a little bit more this approach I understand your point of view. I also agree that something can be done in the future to improve this situation. It might be a refactoring of `RPCHelpMan` logic, or some local handling in each RPC function implementation.

If there is consensus to go ahead with this approach, I volunteer myself to also implement the `abort` and `status` subcommands in follow-ups, and perhaps try a solution for what you described as well.

**Comment by Sjors** [comment]
I think @ryanofsky's suggestion makes sense. We could even keep `loadtxoutset` the same (it implies `start`), and just have `loadtxoutsetstatus and `loadtxoutsetabort`.

**Comment by hernanmarino** [comment]
> Are you still working on this?

Yes ! I was witing for more reviews, but I'll go ahead with @Sjors suggestion asap.

**Comment by hernanmarino** [comment]
> Ok, maybe turn it into draft, until you are done and the CI is passing?

Actually, I 'd like to ask you and @pablomartin4btc (who also reviewed) a question .  I am convinced now to follow @ryanofsky ( and @Sjors ) suggestion of implementing this with 3 commands instead of the current approach of subcommands.

If you agree with this new approach , I think I'll close this PR and implement the functionality in one (or two) followup PRs implementing the new commands, since there is no point in keeping this PR if `loadtxoutset` remains unchanged.

**Review by pablomartin4btc — COMMENTED** [review]
I think it's up to you really, you could either use this PR, updating title & description (mentioning previous approach) or create a new one referring this one, but you would need to make `loadtxoutset` async now (no? :thinking:) so the other [2 new RPC commands](https://github.com/bitcoin/bitcoin/pull/28659#issuecomment-1774662703) (to be created) work/ interact well.

**Comment by hernanmarino** [comment]
> Closing for now. This has been a placeholder for months now, with no code to review or merge, and the CI failing anyway. Feel free to open a new pull request once and if there is something to review. If you have questions, you can leave them in the existing thread: #28620

I agree with closing, consensus was leaning towards to a different approach, in  wich I am already working. I 'll open a new PR when ready, thanks.

**Pull request closed without merging**
