### PR TITLE
[28.x] 28.1rc2 backports

### PR DESCRIPTION
**Pull request by achow101**
Backports:

* #31223
* #31448
* #31431
* #31419

### CODE REVIEW

**Comment by fanquake** [comment]
https://cirrus-ci.com/task/5580834063777792?logs=ci#L1854:
```bash
 test  2024-12-11T17:44:45.280000Z TestFramework (ERROR): Unexpected exception caught during testing 
                                   Traceback (most recent call last):
                                     File "/ci_container_base/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 132, in main
                                       self.run_test()
                                     File "/ci_container_base/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/wallet_migration.py", line 1095, in run_test
                                       self.test_migrate_simple_watch_only()
                                     File "/ci_container_base/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/wallet_migration.py", line 1024, in test_migrate_simple_watch_only
                                       res, _ = self.migrate_and_get_rpc("bare_p2pk")
                                   AttributeError: 'WalletMigrationTest' object has no attribute 'migrate_and_get_rpc'
```

**Review by hodlinator — APPROVED** [review]
ACK 227642d5afeb9918269192500d1a41bcb64b51c5

Only contains changes from 3 mentioned PRs. No longer includes #31374 which depended on additional changes.

**Comment by achow101** [comment]
Added #31223 and also the rest of the rc2 things.

**Review by hodlinator — APPROVED** [review]
re-ACK 5576618152aff0358aeb1c5189422882b419de2d

Used `git range-diff 0e2b12b^..1dd3af8  227642d..bdc6b3e` to confirm only commit messages and diff *context* changed marginally vs #31223.

Last few added commits correspond well to *release-process.md*.

**Review by PlatinumWrist5055 — COMMENTED** [review]
https://github.com/bitcoin/bitcoin/issues/31418

**Pull request merged**
