### PR TITLE
Check for compatibility with download in FindNextBlocksToDownload

### LINKED ISSUE #8518: testnet: 0.13 peers are disconnected due to "stalling"
As segwit is active on testnet, blocks will only be downloaded from NODE_WITNESS peers. Though, exactly those peers are disconnected after `BLOCK_STALLING_TIMEOUT = 2` seconds. I am running master (6e6ab2c)

This behavior is consistent across restarts. Sample [debug.log](http://pastebin.ubuntu.com/23058327/) and [getchaintips](http://pastebin.ubuntu.com/23058325/).

It is possible that I shot my own foot at some point, but it seemed smelly enough to create an issue.

### PR DESCRIPTION
**Pull request by sipa**
Fixes #8518 (untested).

Move the witness-compatibility of a peer with downloading to FindNextBlocksToDownload. This should be more efficient than doing it afterwards in SendMessages, and avoids accidentally marking peers as stalling.

cc @MarcoFalke @sdaftuar

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Tested ACK 887919c

**Comment by gmaxwell** [comment]
utACK, will test.

**Comment by gmaxwell** [comment]
ACK.

**Comment by sdaftuar** [comment]
post-merge utACK

**Pull request merged**
