### PR TITLE
depends: fix unusable memory_resource in macos qt build

### LINKED ISSUE #28566: build: depends qt failure with macos 13 & Xcode (tools) 15
When building qt in depends, on a macOS 13 system, with version 15 of the command line tools, it currently fails to build:
```bash
compiling .moc/moc_qfbscreen_p.cpp
compiling .moc/moc_qfbvthandler_p.cpp
gmake[4]: Entering directory '/bitcoin/depends/work/build/aarch64-apple-darwin22.6.0/qt/5.15.5-8525c199952/qtbase/src/widgets'
uic dialogs/qfiledialog.ui
dyld[55501]: Symbol not found: __ZTVNSt3__13pmr25monotonic_buffer_resourceE
  Referenced from: <577DB68A-5C1A-38A3-8285-AC3E88B934FE> /bitcoin/depends/work/build/aarch64-apple-darwin22.6.0/qt/5.15.5-8525c199952/qtbase/bin/uic
  Expected in:     <3EE92404-8FC3-374B-A598-D5C9A8CD64B5> /usr/lib/libc++.1.dylib
/bin/sh: line 1: 55501 Abort trap: 6           /bitcoin/depends/work/build/aarch64-apple-darwin22.6.0/qt/5.15.5-8525c199952/qtbase/bin/uic dialogs/qfiledialog.ui -o .uic/ui_qfiledialog.h
compiling kernel/qt_widgets_pch.h
gmake[4]: *** [Makefile:72588: .uic/ui_qfiledialog.h] Error 134
```

See discussion in https://github.com/bitcoin/bitcoin/pull/28543#issuecomment-1742666479. May require another patch to Qt.

### PR DESCRIPTION
**Pull request by fanquake**
See https://codereview.qt-project.org/c/qt/qtbase/+/482392.

Fixes #28566.

### CODE REVIEW

**Comment by hebasto** [comment]
Concept ACK.

**Review by hebasto — APPROVED** [review]
ACK 848eec09363d1ba8198376eb9654b1a69e3541aa.

I've backported an upstream fix locally and got the same patch.

Tested on:
- macOS Ventura 13.6 (22G120, M1) + Xcode 15.0
- macOS Sonoma 14.0 (23A344, M1) + Xcode 15.0

**Comment by fanquake** [comment]
Guix Build (aarch64):
```bash
6b4e0258f56f6af3ddcfaa9da568c3b003823ac2699365bb9817ed02e01ed69d  guix-build-848eec09363d/output/aarch64-linux-gnu/SHA256SUMS.part
a209b3cd5c9ddd6856d6d3010bc3660c87fb4e503908acca45dec46e865cd1ba  guix-build-848eec09363d/output/aarch64-linux-gnu/bitcoin-848eec09363d-aarch64-linux-gnu-debug.tar.gz
3e96c8239a69b693fadcb4a4f142cd9a63603de9b040613d799e3c491a5a08b6  guix-build-848eec09363d/output/aarch64-linux-gnu/bitcoin-848eec09363d-aarch64-linux-gnu.tar.gz
95a5ea3d5b51103d4ba4d991f7df76500a9105a40d0d7f9e8eae2634765d3967  guix-build-848eec09363d/output/arm-linux-gnueabihf/SHA256SUMS.part
53a664ecb615c4e41d43566620fee66f248fa657f94d89d23e9efda079878aab  guix-build-848eec09363d/output/arm-linux-gnueabihf/bitcoin-848eec09363d-arm-linux-gnueabihf-debug.tar.gz
7facff37c0cfcbef359e8878b7c5b19ab9bdab6450ab06258cf8aec3ce168f0e  guix-build-848eec09363d/output/arm-linux-gnueabihf/bitcoin-848eec09363d-arm-linux-gnueabihf.tar.gz
b782d5bbd76535aad00b2d78ebb92bdf785861b05c5462aa04c02975d0d0c88b  guix-build-848eec09363d/output/arm64-apple-darwin/SHA256SUMS.part
0da6d0c75cc6b4fcb4d8245bad3add0af02fac00af0356b2466be5ba9ca260bc  guix-build-848eec09363d/output/arm64-apple-darwin/bitcoin-848eec09363d-arm64-apple-darwin-unsigned.tar.gz
714a079b6c33fa8b3d5ca8c11d9e9bbafa7753f19b5fbda4657c0bb7f30faa3f  guix-build-848eec09363d/output/arm64-apple-darwin/bitcoin-848eec09363d-arm64-apple-darwin-unsigned.zip
ee0f97581a072b91b3b6c781bbce0081777817ff538d41c6be6a630ebdbc79c3  guix-build-848eec09363d/output/arm64-apple-darwin/bitcoin-848eec09363d-arm64-apple-darwin.tar.gz
76dd60077ff2d91496476c4afa1fae204a19f5c8283cacf9da1cf3cb2d479462  guix-build-848eec09363d/output/dist-archive/bitcoin-848eec09363d.tar.gz
5342b8de37eb4cb5d0ec7374bf05efa4ec679ad467950439715e1673120f4c8d  guix-build-848eec09363d/output/powerpc64-linux-gnu/SHA256SUMS.part
4b0bc5c3068f4135a533e5ac0b5bbf0e8eb32bbde1e7e0c2e2ca1168a7617eaa  guix-build-848eec09363d/output/powerpc64-linux-gnu/bitcoin-848eec09363d-powerpc64-linux-gnu-debug.tar.gz
3b1342afaa479286e367df0440c014900299edf43cf9a9ea354a23f9edec5286  guix-build-848eec09363d/output/powerpc64-linux-gnu/bitcoin-848eec09363d-powerpc64-linux-gnu.tar.gz
8eab040e61a0f04b7c887bab3f81b307936c50f3c2e32688177196b5ff1be9eb  guix-build-848eec09363d/output/powerpc64le-linux-gnu/SHA256SUMS.part
0c4217e1dc834c3a1fb4964e9ec203055475af693aaa856d47cbb7743be0c118  guix-build-848eec09363d/output/powerpc64le-linux-gnu/bitcoin-848eec09363d-powerpc64le-linux-gnu-debug.tar.gz
682900a1788e52c4c2642ea33a01b4482cb13cea83e4dfc46fb1a1210d969ff0  guix-build-848eec09363d/output/powerpc64le-linux-gnu/bitcoin-848eec09363d-powerpc64le-linux-gnu.tar.gz
0ebf6a23c0d2d5b394192060f4c2ca1dec241d31fa688d88f444df972a8f8165  guix-build-848eec09363d/output/riscv64-linux-gnu/SHA256SUMS.part
54928974faf547c0cc00ac49be730636c57bd5503a1a6c71c140db691c2a0314  guix-build-848eec09363d/output/riscv64-linux-gnu/bitcoin-848eec09363d-riscv64-linux-gnu-debug.tar.gz
5c27969284a48f60194b9469ee0f5f160cdd288ecc90e69c3da20519e5ff2a04  guix-build-848eec09363d/output/riscv64-linux-gnu/bitcoin-848eec09363d-riscv64-linux-gnu.tar.gz
6e4d2ef7f423de63815006110c85fefc008a4ed79e79db5347260d8784dfb998  guix-build-848eec09363d/output/x86_64-apple-darwin/SHA256SUMS.part
2c7f2b8fc72bb20d6a27dbdde7c614b2f1b4d46376fb2a00e9710e3c72a3f78f  guix-build-848eec09363d/output/x86_64-apple-darwin/bitcoin-848eec09363d-x86_64-apple-darwin-unsigned.tar.gz
31753b800aa77fa54d3b5446c1e10f34c35b1089d0f3b0fecf45d56e482f6a97  guix-build-848eec09363d/output/x86_64-apple-darwin/bitcoin-848eec09363d-x86_64-apple-darwin-unsigned.zip
4eab6dffc5206476acaec5ed5c33dff20347309a759ecc8ce7733565358800d9  guix-build-848eec09363d/output/x86_64-apple-darwin/bitcoin-848eec09363d-x86_64-apple-darwin.tar.gz
9fbefacafabcc900d77720ea71eebc9589122dfa24af2f32dc594171e578a280  guix-build-848eec09363d/output/x86_64-linux-gnu/SHA256SUMS.part
2dfe9bf8ad9a32c3be5c0e8a3159f2dc156a6dbff92411d62c616569bbcc1946  guix-build-848eec09363d/output/x86_64-linux-gnu/bitcoin-848eec09363d-x86_64-linux-gnu-debug.tar.gz
82b41f3768dc7454589e71e479ae76d840279a0cc94adc1047f3b48c7ce12d33  guix-build-848eec09363d/output/x86_64-linux-gnu/bitcoin-848eec09363d-x86_64-linux-gnu.tar.gz
a253e829aa1f482ade4fa721b0b2261611ee1b976448fc49c6324e900e157cf8  guix-build-848eec09363d/output/x86_64-w64-mingw32/SHA256SUMS.part
8969c0319a25f2458ea20ce6909ab88de8348cddf5136e1b5f563af580b651cc  guix-build-848eec09363d/output/x86_64-w64-mingw32/bitcoin-848eec09363d-win64-debug.zip
d389da0e91c0db76e597ce3bbdc48573a3467feec5e5fada752c382b47db66e9  guix-build-848eec09363d/output/x86_64-w64-mingw32/bitcoin-848eec09363d-win64-setup-unsigned.exe
ee76bbdb8a0e2d850e655010e415371108b4ef291311cdf32284182b32520298  guix-build-848eec09363d/output/x86_64-w64-mingw32/bitcoin-848eec09363d-win64-unsigned.tar.gz
977cf4b649deb73a8a0f0b157cf417c4e316037afda169f082071fdfa256c1b2  guix-build-848eec09363d/output/x86_64-w64-mingw32/bitcoin-848eec09363d-win64.zip
```

**Comment by fanquake** [comment]
Added to #28487 for backporting to 25.x.

**Comment by fanquake** [comment]
Added to #28535 for backporting to 24.x.

**Comment by hebasto** [comment]
Guix builds:
```
x86_64
6b4e0258f56f6af3ddcfaa9da568c3b003823ac2699365bb9817ed02e01ed69d  guix-build-848eec09363d/output/aarch64-linux-gnu/SHA256SUMS.part
a209b3cd5c9ddd6856d6d3010bc3660c87fb4e503908acca45dec46e865cd1ba  guix-build-848eec09363d/output/aarch64-linux-gnu/bitcoin-848eec09363d-aarch64-linux-gnu-debug.tar.gz
3e96c8239a69b693fadcb4a4f142cd9a63603de9b040613d799e3c491a5a08b6  guix-build-848eec09363d/output/aarch64-linux-gnu/bitcoin-848eec09363d-aarch64-linux-gnu.tar.gz
95a5ea3d5b51103d4ba4d991f7df76500a9105a40d0d7f9e8eae2634765d3967  guix-build-848eec09363d/output/arm-linux-gnueabihf/SHA256SUMS.part
53a664ecb615c4e41d43566620fee66f248fa657f94d89d23e9efda079878aab  guix-build-848eec09363d/output/arm-linux-gnueabihf/bitcoin-848eec09363d-arm-linux-gnueabihf-debug.tar.gz
7facff37c0cfcbef359e8878b7c5b19ab9bdab6450ab06258cf8aec3ce168f0e  guix-build-848eec09363d/output/arm-linux-gnueabihf/bitcoin-848eec09363d-arm-linux-gnueabihf.tar.gz
b782d5bbd76535aad00b2d78ebb92bdf785861b05c5462aa04c02975d0d0c88b  guix-build-848eec09363d/output/arm64-apple-darwin/SHA256SUMS.part
0da6d0c75cc6b4fcb4d8245bad3add0af02fac00af0356b2466be5ba9ca260bc  guix-build-848eec09363d/output/arm64-apple-darwin/bitcoin-848eec09363d-arm64-apple-darwin-unsigned.tar.gz
714a079b6c33fa8b3d5ca8c11d9e9bbafa7753f19b5fbda4657c0bb7f30faa3f  guix-build-848eec09363d/output/arm64-apple-darwin/bitcoin-848eec09363d-arm64-apple-darwin-unsigned.zip
ee0f97581a072b91b3b6c781bbce0081777817ff538d41c6be6a630ebdbc79c3  guix-build-848eec09363d/output/arm64-apple-darwin/bitcoin-848eec09363d-arm64-apple-darwin.tar.gz
76dd60077ff2d91496476c4afa1fae204a19f5c8283cacf9da1cf3cb2d479462  guix-build-848eec09363d/output/dist-archive/bitcoin-848eec09363d.tar.gz
5342b8de37eb4cb5d0ec7374bf05efa4ec679ad467950439715e1673120f4c8d  guix-build-848eec09363d/output/powerpc64-linux-gnu/SHA256SUMS.part
4b0bc5c3068f4135a533e5ac0b5bbf0e8eb32bbde1e7e0c2e2ca1168a7617eaa  guix-build-848eec09363d/output/powerpc64-linux-gnu/bitcoin-848eec09363d-powerpc64-linux-gnu-debug.tar.gz
3b1342afaa479286e367df0440c014900299edf43cf9a9ea354a23f9edec5286  guix-build-848eec09363d/output/powerpc64-linux-gnu/bitcoin-848eec09363d-powerpc64-linux-gnu.tar.gz
8eab040e61a0f04b7c887bab3f81b307936c50f3c2e32688177196b5ff1be9eb  guix-build-848eec09363d/output/powerpc64le-linux-gnu/SHA256SUMS.part
0c4217e1dc834c3a1fb4964e9ec203055475af693aaa856d47cbb7743be0c118  guix-build-848eec09363d/output/powerpc64le-linux-gnu/bitcoin-848eec09363d-powerpc64le-linux-gnu-debug.tar.gz
682900a1788e52c4c2642ea33a01b4482cb13cea83e4dfc46fb1a1210d969ff0  guix-build-848eec09363d/output/powerpc64le-linux-gnu/bitcoin-848eec09363d-powerpc64le-linux-gnu.tar.gz
0ebf6a23c0d2d5b394192060f4c2ca1dec241d31fa688d88f444df972a8f8165  guix-build-848eec09363d/output/riscv64-linux-gnu/SHA256SUMS.part
54928974faf547c0cc00ac49be730636c57bd5503a1a6c71c140db691c2a0314  guix-build-848eec09363d/output/riscv64-linux-gnu/bitcoin-848eec09363d-riscv64-linux-gnu-debug.tar.gz
5c27969284a48f60194b9469ee0f5f160cdd288ecc90e69c3da20519e5ff2a04  guix-build-848eec09363d/output/riscv64-linux-gnu/bitcoin-848eec09363d-riscv64-linux-gnu.tar.gz
6e4d2ef7f423de63815006110c85fefc008a4ed79e79db5347260d8784dfb998  guix-build-848eec09363d/output/x86_64-apple-darwin/SHA256SUMS.part
2c7f2b8fc72bb20d6a27dbdde7c614b2f1b4d46376fb2a00e9710e3c72a3f78f  guix-build-848eec09363d/output/x86_64-apple-darwin/bitcoin-848eec09363d-x86_64-apple-darwin-unsigned.tar.gz
31753b800aa77fa54d3b5446c1e10f34c35b1089d0f3b0fecf45d56e482f6a97  guix-build-848eec09363d/output/x86_64-apple-darwin/bitcoin-848eec09363d-x86_64-apple-darwin-unsigned.zip
4eab6dffc5206476acaec5ed5c33dff20347309a759ecc8ce7733565358800d9  guix-build-848eec09363d/output/x86_64-apple-darwin/bitcoin-848eec09363d-x86_64-apple-darwin.tar.gz
9fbefacafabcc900d77720ea71eebc9589122dfa24af2f32dc594171e578a280  guix-build-848eec09363d/output/x86_64-linux-gnu/SHA256SUMS.part
2dfe9bf8ad9a32c3be5c0e8a3159f2dc156a6dbff92411d62c616569bbcc1946  guix-build-848eec09363d/output/x86_64-linux-gnu/bitcoin-848eec09363d-x86_64-linux-gnu-debug.tar.gz
82b41f3768dc7454589e71e479ae76d840279a0cc94adc1047f3b48c7ce12d33  guix-build-848eec09363d/output/x86_64-linux-gnu/bitcoin-848eec09363d-x86_64-linux-gnu.tar.gz
a253e829aa1f482ade4fa721b0b2261611ee1b976448fc49c6324e900e157cf8  guix-build-848eec09363d/output/x86_64-w64-mingw32/SHA256SUMS.part
8969c0319a25f2458ea20ce6909ab88de8348cddf5136e1b5f563af580b651cc  guix-build-848eec09363d/output/x86_64-w64-mingw32/bitcoin-848eec09363d-win64-debug.zip
d389da0e91c0db76e597ce3bbdc48573a3467feec5e5fada752c382b47db66e9  guix-build-848eec09363d/output/x86_64-w64-mingw32/bitcoin-848eec09363d-win64-setup-unsigned.exe
ee76bbdb8a0e2d850e655010e415371108b4ef291311cdf32284182b32520298  guix-build-848eec09363d/output/x86_64-w64-mingw32/bitcoin-848eec09363d-win64-unsigned.tar.gz
977cf4b649deb73a8a0f0b157cf417c4e316037afda169f082071fdfa256c1b2  guix-build-848eec09363d/output/x86_64-w64-mingw32/bitcoin-848eec09363d-win64.zip
```

**Pull request merged**
