### PR TITLE
random: remove call to RAND_screen() (Windows only)

### PR DESCRIPTION
**Pull request by fanquake**
Follow up to https://github.com/bitcoin/bitcoin/pull/17151 where there were multiple calls to also remove our call to RAND_screen().

### CODE REVIEW

**Comment by MarcoFalke** [comment]
unsigned ACK e892f9648ae5f72b2020bdaa1e28901e8378e9fc

**Comment by emilengler** [comment]
ACK

**Comment by laanwj** [comment]
ACK e892f9648ae5f72b2020bdaa1e28901e8378e9fc

Though after this I'd prefer to wait for #17165 and rip OpenSSL out all at once, instead of statement for statement :smile:

**Comment by MarcoFalke** [comment]
ACK e892f9648ae5f72b2020bdaa1e28901e8378e9fc

**Pull request merged**
