### PR TITLE
qt/scicon: Avoid warnings about unused MakeSingleColorImage

### PR DESCRIPTION
**Pull request by luke-jr**
A cleaner alternative to #6327

### CODE REVIEW

**Comment by Diapolo** [comment]
+9 / -3 yours
+7 / -7 mine :-P

Well I like mine better, as I removed an #ifdef ;).

**Comment by jonasschnelli** [comment]
ACK

**Comment by laanwj** [comment]
We had this discussion before, shortly ago: #6143

For the sake of making sure as much code gets compiled for every platform, thus logic that does not use specific platform-dependent APIs (and thus potentially compiles on other platforms) should not be in platform-specific #ifdefs.

E.g. use MACOSX/WINDOWS to determine a UIPlatformStyle enum once, then pass that on. This could be overridden for testing.

**Comment by laanwj** [comment]
Closing in favor of #6487, which implements the approach outlined in my above post.

**Pull request closed without merging**
