### PR TITLE
Make extra super sure RAND_bytes failing == exit

### PR DESCRIPTION
**Pull request by gavinandresen**
Inspired by a worried email from somebody reviewing the code.

### CODE REVIEW

**Comment by gmaxwell** [comment]
There are a number of other assert(falses) that should get exit()s by that metric; that is part of why the code still refuses to compile with NDEBUG.   I'd rather replace the assert.h macro with our own that is guaranteed to quit; and end the constant repetition of issues around assert().

**Comment by gavinandresen** [comment]
@gmaxwell : okey dokey, "perfect enemy of the better"... I don't care enough to write a proper assert() replacement, but if you do, then please write a patch.

Until then, I think this should be pulled.

**Comment by gmaxwell** [comment]
Already working on it. Independently, I don't think this should be pulled: All it's going to result in is more panicked email which is confused about how assert works in the codebase. I am tired of it. We had another round of that a week ago.

**Comment by laanwj** [comment]
> All it's going to result in is more panicked email which is confused about how assert works in the codebase

I agree.. This solves nothing and may 'confirm' irrational panic. A) as it is, openssl rand will never fail, so this case isn't important B) building with NDEBUG is explicitly forbidden, and until we replace assert (which is worthwhile) it will result in problems in other places.

**Pull request closed without merging**
