### PR TITLE
Switch to weight units for all feerates computation

### LINKED ISSUE #13283: minRelayTxFee should be calculated on weight, not vbytes.  aka "vbytes must die"
By default, bitcoin core has minRelayTxFee of '0.00001000' or 1000 satoshi per 1000 bytes.

This should be the same as 250 satoshi per kiloweight, but it's *not* since it internally uses vbytes (which *rounds up*).  As a result, modern (segwit-only) software must perform hacks to ensure that it generates transactions which propagate, and authors write angsty, whiny commit messages:

https://github.com/ElementsProject/lightning/commit/2e687b9b352c9092b5e8bd4a688916ac50b44af0

## What behavior did you expect?

Transactions with exactly 250 satoshi per kilosipa should propagate.

## What was the actual behavior?

Only one in four transactions like this will propagate, the rest will be rejected.

### PR DESCRIPTION
**Pull request by darosior**
This changes the current feerate computation from using virtual bytes to weight units for transaction size.

The transaction size being stored and used as virtual bytes introduced some non-negligible rounding and approximations *(See https://github.com/bitcoin/bitcoin/issues/13283 for an example.)*. This patch set is an attempt to switch to using weight units in place of virtual bytes internally for a more accurate feerate computation, while leaving intact the vbyte interface.

There is, I think, a big cleanup needed (for example renaming feerate constants as `xx_FEERATE` would really improve readability) but I wanted to keep changes as minimal as possible.

 Fixes #13283.

### CODE REVIEW

**Comment by darosior** [comment]
Rebased now that appveyor seems to be fixed.

**Comment by darosior** [comment]
This might be "too late" but the fee estimation can be floored to 253 sat/kWU, so that the wallet doesn't create transaction below old feerate until most of the network relay 250 sat/kWU txs..

**Comment by darosior** [comment]
Rebased.

**Comment by jb55** [comment]
I can't help but wonder if there's a better abstraction here instead of random conversions happening everywhere...

**Comment by darosior** [comment]
> I can't help but wonder if there's a better abstraction here instead of random conversions happening everywhere...

Conversion is needed anyway for every user input (and even for JSONRPC outputs) to not break the API..

**Comment by jb55** [comment]
>> I can't help but wonder if there's a better abstraction here instead of random conversions happening everywhere...
>
> Conversion is needed anyway for every user input (and even for JSONRPC outputs) to not break the API..

yes I understand that conversions are needed... I'm just referring to
the fact these are two different fee types, but that fact is not
captured in the type system. If we had a better abstraction that
captures both of these types, it would be less error prone and we
wouldn't have to opencode conversions everywhere.

**Comment by darosior** [comment]
Rebased.

Will rework the approach and include remarks from jb55 if there are some acks on the general concept of using / exposing weight units..

**Comment by ariard** [comment]
Concept ACK.

Correctness of fee computation is safety-critical for any time-sensitive protocol like LN. Overpaying by default  isn't the solution as you may have to save value for period of congestion. With this regards easing implementation of segwit fee-estimators should be highly considered. 

As Rusty points out in related issue, this should be part of a wider discussion on a stable API for protocol applications on top of Bitcoin Core.

**Comment by darosior** [comment]
Thank you for the feedback, I'll rebase this and change the approach as per jb55's comments soon.
I wanted to go for the minimal changes, but something cleaner is definitely better. This makes me wonder
if I should break this into smaller PRs, too.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by adamjonas** [comment]
I gathered some opinions on this from a long time contributor about the concept, he replied:
"seems like a fine thing to do. also seems like not a high priority"

After looking at the code, however, his reaction was that the patch was too big for the benefit. Putting more data in the CTxMemPoolEntry especially stood out as an issue. 

@darosior I think it's worth getting more conceptual review before you put in more effort. I believe it's clear that more discussions need to happen around ways to improve the linkages between Bitcoin Core and LN, but based on the opinions I gathered, the approach on this PR could use some more feedback.

**Comment by darosior** [comment]
@adamjonas this PR is a **bad** approach. It's been known and discusses above, so I don't think it's worth discussing this but for the sake of the argument: I locally have a version which is an about 3x smaller diff, and regarding adding a field to the CTxMempoolEntry it's necessary anyway as to use weight-mesured feerates we need to track, well, the weight of the tx.

I agree it needs more conceptual feedback, but i don't want to ask for it before this patchset is reworked (will push soon :tm: ) as i think the boutique approach here could degrade the conceptual review.

Nonetheless, thank you for your interest.

**Comment by jnewbery** [comment]
This has required rebase since February, and there are still conceptual questions outstanding. I'm going to close it for now.

@darosior - feel free to reopen (or open another PR) if you have something that's ready for review/discussion.

**Pull request closed without merging**
