### PR TITLE
[contrib] verify-commits: Add MarcoFalke fingerprint

### PR DESCRIPTION
**Pull request by maflcko**

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Hmm... seems not to match with your gitian key.
```
pub   4096R/F4316B9B 2015-12-14
      Key fingerprint = B8B3 F1C0 E58C 15DB 6A81  D30C 3648 A882 F431 6B9B
uid                  Marco Falke <falke.marco@gmail.com>
sub   2048R/E50FE137 2015-12-14 [expires: 2016-06-11]
sub   2048R/F6B61B9A 2015-12-14 [expires: 2016-06-11]
```

**Comment by laanwj** [comment]
Matches with first subkey though:
```
pub   4096R/F4316B9B 2015-12-14
      Key fingerprint = B8B3 F1C0 E58C 15DB 6A81  D30C 3648 A882 F431 6B9B
uid                  Marco Falke <falke.marco@gmail.com>
sub   2048R/E50FE137 2015-12-14 [expires: 2016-06-11]
      Key fingerprint = FE09 B823 E6D8 3A3B C798  3EAA 2D7F 2372 E50F E137
sub   2048R/F6B61B9A 2015-12-14 [expires: 2016-06-11]
      Key fingerprint = B6C7 2B4A 758C C29B 483E  82C7 6DF9 EDF1 F6B6 1B9A
```

**Comment by jonasschnelli** [comment]
Right. It matches with the first subkey. My fault!

**Comment by MarcoFalke** [comment]
You need to pass `--fingerprint` twice.

**Comment by sipa** [comment]
> You need to pass `--fingerprint` twice.

Today I learned!

**Comment by MarcoFalke** [comment]
> The important thing is that it matches the key used for signing merges, so if you use the subkey, that one should be in here.

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

I will use the subkeys for everyday signing (gitian results, emails, merge
commits, or this very message I am typing right now, etc) and decryption. The
root key is used to sign other keys or extend the lifetime of the subkeys.
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQEcBAEBAgAGBQJXGNssAAoJEC1/I3LlD+E3BHEH/jIBfm5XiLFH8JZX4RN4j/uS
IsZnJnPlZVZsqrmTFQWR4OYjSfeyGtH3ICxVdbEgkg+T8f709KGi+sJKG3H823W7
0eGPdqYZFmb7m/A5odJ7ovTSuvTWsU/1MTIvWOhD3+faLEnuNngInaF2H6bpqe7Y
EdykKpgJwvttbV4cRLPY/sT4ZWvXKSrOn+67dtGB9KwNcc8hnNFGVX9h7Vc8MWL1
zWcGwpKfU4oPLr4UfIAMQx9NGboaDw0rWyM5dki3hJCvy17CGzk3+Ae/I8J7jRGk
1taZwIhtROtMFcDicr629KCA5oGUqjtbXIfmu5cu+Zy5uoL3aC/Q/XukGyC3Gso=
=1Mrt
-----END PGP SIGNATURE-----

**Comment by laanwj** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/7921/commits/fa243293343eb964bfee5b91cc52b91f16232ab6

**Comment by jonasschnelli** [comment]
ACK fa243293343eb964bfee5b91cc52b91f16232ab6

**Comment by laanwj** [comment]
Travis failure is unrelated (another timeout...)

**Pull request merged**
