### PR TITLE
Add option to avoid warning on certain network upgrades

### PR DESCRIPTION
**Pull request by ajtowns**
The "-vbignore=bit:start:end" option can be used to prevent bitcoin
from alerting the user of known but uninteresting proposed upgrades
that are being signalled via the version field.

This hopefully provides the feature requested in issue #8266, allow version bits to have an "ignore button". It requires specifying start and end times rather than a final block height, which should map better to BIP 9 implementations. It also allows multiple deployments on a single bit to be ignored independently -- if the bit is used in between any deployments, it will still generate warnings.

This setting will also avoid the bit from triggering the "Unknown block versions being mined" warning during the set period.

### CODE REVIEW

**Review by promag — COMMENTED** [review]
Missing update to help message.

**Comment by laanwj** [comment]
Concept ACK

Ping @gmaxwell which requested this.

**Comment by ajtowns** [comment]
Rebased against master; updated help text; moved structure definition to versionbits.h; use emplace_back instead of push_back.

Added additional commit that removes the BIP109/bit 28 warning on testnet by default, without the user needing to specify the parameter.

**Comment by laanwj** [comment]
It looks like interest in this got lost a bit due to recent drama, because it is not sure how feasible BIP9 still is in the first place.

But anyhow ping @gmaxwell (again, sorry).

**Comment by ajtowns** [comment]
Rebased; use an enum class instead of a bool for use_ignorebits argument to ComputeBlockVersion.

FWIW, I think version bits would still be useful for BIP8 or BIP148/BIP91-style UASF's; full node users can require miners to signal support (or to not signal support if they want to opt-out of a change) so as to allow two potential chains to be easily distinguished by SPV clients.

**Comment by ajtowns** [comment]
Going to close this until there's some clarity on what method might get used for soft-forks in future (bip 9, bip 8, something else)...

**Pull request closed without merging**
