### PR TITLE
Remove unused, non-working RPC PostCommand signal

### PR DESCRIPTION
**Pull request by practicalswift**

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
I'd vote we just remove the dead code.

**Comment by fanquake** [comment]
```
I'd vote we just remove the dead code.
```
Agree.

**Comment by JeremyRubin** [comment]
NACK. Code seems to be reachable?

 JSONRPCError doesn't inherit from std::exception. transformNamedArguments could throw a JSONRPCError.

**Comment by TheBlueMatt** [comment]
Either way, code is clearly a NOP.

**Comment by laanwj** [comment]
This clearly seems a bug. There's two options here: 
- repair the PostCommand functionality so that the PostCommand handler actually runs (by having a RAII cleanup that triggers it)
- remove the PostCommand functionality

It looks like this currently influences nothing as no PostCommand handlers are being registered.

**Comment by practicalswift** [comment]
@laanwj Updated and pushed. I simply remoevd the PostCommand functionality. Let me know if you have any further suggestions! :-)

**Comment by laanwj** [comment]
@practicalswift You should more thoroughly remove it then. Also remove the signal. Otherwise people will register it in the expectation it will be called.

**Comment by practicalswift** [comment]
@laanwj Another try - looks good? :-)

**Comment by laanwj** [comment]
Yes, all the traces of it should be gone. Looks good to me now.

**Pull request merged**
