### PR TITLE
doc: Added regtest config for linearize script

### PR DESCRIPTION
**Pull request by gr0kchain**
Updated the example-linearize.cfg file to include support for the regtest chain network config which is used by the ./linearize-data.py

Problem:
Without the regtest magic, genesis hash and path config, the `linearize-data.py` script cannot generate a bootstrap.dat file.

Example:

./linearize-data.py ./linearize.cfg
Read 102 hashes
Genesis block not found in hashlist

Solution: 

Added netmagic, genesis and input example parameters to file. 

Resolution

1. Starting bitcoind in regtest mode 
2. bitcoin-cli generatetoaddress 101 $(bitcoin-cli getnewaddress)
3. ./linearize-hashes.py ./linearize.cfg > ./hashlist.txt
4. ./linearize-data.py ./linearize.cfg

```
$ ./linearize-data.py ./linearize.cfg
Read 102 hashes
Input file /Users/gr0kchain/.bitcoin/regtest/blocks/blk00000.dat
Output file /Users/gr0kchain/Downloads/bootstrap.dat
Done (102 blocks written)
```

### CODE REVIEW

**Comment by laanwj** [comment]
Concept ACK, but please improve your commit message from just "Updated config file".

**Comment by gr0kchain** [comment]
Updated commit message as requested

**Comment by laanwj** [comment]
Thanks, but now it's too long long, please stick to the "consisting of a short subject line (50 chars max), a blank line and explanatory text as separate paragraph(s)" format.
Please read https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md especially "Contributor Workflow" and "Squashing Commits".

**Comment by gr0kchain** [comment]
Thanks for the guidance, and apologies for the multi commit message updates, had some local config issues. Seems fine now with the updated log messages as per the documentation guidelines provided.

**Comment by MarcoFalke** [comment]
Also this: https://chris.beams.io/posts/git-commit/

**Comment by promag** [comment]
ACK after  squash.

**Comment by gr0kchain** [comment]
Squashed the unnecessary noise and consolidated into a single commit with updated comment as per the guidelines

**Review by fanquake — APPROVED** [review]
ACK 582e66b6e75d58033987a7b0474226cfdd724ce0

**Pull request merged**
