### PR TITLE
Update init doc to mention cookie authentication

### PR DESCRIPTION
**Pull request by fanquake**
Noticed by sipa in #6512

### CODE REVIEW

**Comment by laanwj** [comment]
ACK

**Comment by paveljanik** [comment]
The cookie file will be used even without the `-daemon` option on the `bitcoind` command line.

**Comment by laanwj** [comment]
Good catch @paveljanik . It depends on `-server`, not `-daemon`. And `-server` is always set by default for `bitcoind`.

**Comment by fanquake** [comment]
Updated

**Comment by paveljanik** [comment]
ACK, thanks.

**Comment by jonasschnelli** [comment]
ACK. Thanks!

**Comment by laanwj** [comment]
Neds rebase due to #6512

**Comment by fanquake** [comment]
@laanwj Rebased.

**Pull request merged**
