### PR TITLE
Implementation of BIP8

### PR DESCRIPTION
**Pull request by shaolinfry**
Implementation of [BIP8](https://github.com/bitcoin/bips/blob/master/bip-0008.mediawiki) workflow for soft fork deployment. 

states

### CODE REVIEW

**Comment by luke-jr** [comment]
NACK.

**Comment by instagibbs** [comment]
@luke-jr from https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md "NACKs without accompanying reasoning may be disregarded;"

**Comment by luke-jr** [comment]
BIP8 is not currently used, nor may ever be used at least in its current form, since it fails to address some outstanding issues with BIP9. As such, it doesn't make sense to merge code for it.

**Comment by laanwj** [comment]
Closing for now. Doesn't get much attention at the moment. This will be relevant when a softfork is to be done again.

**Pull request closed without merging**
