### PR TITLE
Remove TransactionTableModel::TxIDRole

### PR DESCRIPTION
**Pull request by promag**
The role `TxIDRole` is a duplicate of `TxHashRole`. This change favours `TxHashRole`.

### CODE REVIEW

**Comment by laanwj** [comment]
utACK - I think it was duplicated because TxID used to contain the vout id at some point, too.

**Comment by practicalswift** [comment]
Concept ACK

**Comment by jonasschnelli** [comment]
utACK b73cd923c451d926e475482ed7dcdac47444cdb2

**Comment by MarcoFalke** [comment]
utACK b73cd923c451d926e475482ed7dcdac47444cdb2

**Comment by jonasschnelli** [comment]
See travis report:
```
qt/transactionfilterproxy.cpp: In member function ‘virtual bool TransactionFilterProxy::filterAcceptsRow(int, const QModelIndex&) const’:
qt/transactionfilterproxy.cpp:39:31: error: ‘TxIDRole’ is not a member of ‘TransactionTableModel’
     QString txid = index.data(TransactionTableModel::TxIDRole).toString();
```

**Comment by promag** [comment]
Somehow missed that. Fixed.

**Comment by MarcoFalke** [comment]
re-utACK 3b26b6af728d5ac538d333a1275073c7c5a012e1

**Pull request merged**
