### PR TITLE
Prevector Quick Destruct

### PR DESCRIPTION
**Pull request by JeremyRubin**
This is a minor performance optimization of prevector. If the stored type is trivially destructible (such as unsigned char which is the main use of prevector), there is no need to call clear on the entries before freeing.

The call to clear seems to not get optimized out completely (likely because of the `--_size;` side-effect) with `-O3`.

`std::is_trivially_copyable` seems to enjoy full cross platform support.

On the included benchmark, I see about a 3% performance improvement.

### CODE REVIEW

**Comment by theuni** [comment]
any chance you get the same gain by specializing erase() with std::enable_if and std::is_trivially_destructible, simply reducing it down to a memset in the specialized case? That way we'd still get the zero'd mem, and it'd get sped up in several other places as well.

**Comment by JeremyRubin** [comment]
@theuni  I think that works -- may as well wrap both locations.

**Comment by kallewoof** [comment]
utACK 45a5aaf

**Comment by dcousens** [comment]
light utACK 45a5aa5

**Comment by laanwj** [comment]
utACK 45a5aaf

**Pull request merged**
