### PR TITLE
build: remove `--enable-lto`

### PR DESCRIPTION
**Pull request by fanquake**
This has outlived its usefulness, doesn't gel well with newer compilers & `-flto` related options, i.e thin vs full, or `=auto`, and having `-flto` as the only option means that sometimes this just needs to be worked around, i.e in oss-fuzz:
https://github.com/google/oss-fuzz/blob/master/projects/bitcoin-core/build.sh.

While it was convenient when `-flto` was newer, support for `-flto` is now in all compilers we use, and there's also no-longer any real need for us to treat `-flto` different to any other optimization option.

Remove it, to remove build complexity, and so there's no need to port a similar option to CMake.

Note that the LTO option remains in depends, because we still need a way to build packages that have LTO specific patches/options.

### CODE REVIEW

**Comment by hebasto** [comment]
Concept ACK.

**Comment by fanquake** [comment]
> Can you explain what that means? Is the recommended way to manually override CXXFLAGS and LDFLAGS now?

Yea. `-flto` is really no different to `-O2` or any other compile option, so using it will require adding `-flto=*`, and any other related options you might want, i.e using a link cache via `-Wl,-cache_path_lto`, to the respective *FLAGS vars. Note that this is already required by anyone wanting to do anything other, or in addion to just using `-flto` with the current options (or they'd have to workaround by modifying the source etc).

**Review by sedited — APPROVED** [review]
ACK 2d1b1c7daeeada3f737e62ceb2db7484cde5ff4e

Tested just passing in the required flags, seems to work as advertised.

**Comment by hebasto** [comment]
Tested 2d1b1c7daeeada3f737e62ceb2db7484cde5ff4e on Ubuntu 22.04:

```
$ ./configure CXXFLAGS="-g -O2 -flto=auto" SECP_CFLAGS="-flto=auto"
$ make -C src bitcoind
```

```
$ make -C depends CXXFLAGS="-O2 -flto=auto" LTO=1
$ ./configure CONFIG_SITE=$PWD/depends/x86_64-pc-linux-gnu/share/config.site SECP_CFLAGS="-flto=auto"
$ make
```

> Ah, I guess this would disable O2, see https://github.com/bitcoin/bitcoin/pull/28071/files. So I guess it would have to be appended to `CXX` and possibly `LDFLAGS`.

Appending to `CXXFLAGS` works fine.

FWIW, there are three `if test "$CXXFLAGS_overridden" = "no"` cases in the `configure.ac`, which also includes processing of the warning options (see https://github.com/bitcoin/bitcoin/pull/25972).

**Comment by m3dwards** [comment]
Tested 2d1b1c7daeeada3f737e62ceb2db7484cde5ff4e on MacOS

```shell
$ ./configure CC=clang CXX=clang++ CXXFLAGS="-g -v -flto=thin" SECP_CFLAGS="-g -flto=thin" LDFLAGS="-flto-jobs=3"
$ make check
```

With `-v` flag on CXXFLAGS I could see that `-flto=thin` was present.

**Review by hebasto — APPROVED** [review]
ACK 2d1b1c7daeeada3f737e62ceb2db7484cde5ff4e.

**Comment by fanquake** [comment]
This is waiting on https://github.com/google/oss-fuzz/pull/11498 downstream.

**Pull request merged**
