### PR TITLE
[Qt] fix icon sizes and column width

### PR DESCRIPTION
**Pull request by jonasschnelli**

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Will look like:

win:
bildschirmfoto 2015-01-09 um 11 55 27

osx:
bildschirmfoto 2015-01-09 um 11 58 56

**Comment by jonasschnelli** [comment]
@paveljanik as mentioned on IRC: please don't use Qt4 anymore for OSX builds. It doesn't support retina.

We even should drop Qt4 compatibility for OS X because it will end up with large icons as shown above.

**Comment by luke-jr** [comment]
A warning at the end of configure would be appropriate, but breaking it for no reason would just be annoying IMO. Some users probably don't have Retina, and wouldn't benefit from updating Qt.

**Comment by jonasschnelli** [comment]
@luke-jr even non retina mac and older mac could run Qt5 binaries. With Qt5 the oversized icon would also render nice on non-retina.
Deprecated-unsupported warning is fine for me.

**Comment by jonasschnelli** [comment]
@paveljanik could you retest this with Qt5 already?

**Comment by jonasschnelli** [comment]
Regarding sizes: please see #5489

**Comment by jonasschnelli** [comment]
@zander Transparent space in icons make icons look more uniform when displayed together without clustering the code with some magic padding numbers. And potential replacement would also be more complicated with static padding in the code.

**Comment by zander** [comment]
> Transparent space in icons make icons look more uniform when displayed together 

Definitely! 

> without clustering the code with some magic padding numbers.
> And potential replacement would also be more complicated with static padding in the code.

Don't use static padding, just Qt::AlignmentCenter

Regarding sizing; you should really run optimize on the images *before* you merge, so you don't end up changing it twice. Git will keep all versions on everyones harddrive forever. Best to avoid unneeded changes. 15Kb vs 700 bytes is two orders of magnitude...

**Comment by jonasschnelli** [comment]
> Don't use static padding, just Qt::AlignmentCenter

But this would not solve uniforming sized between icons.

> Regarding sizing; you should really run optimize on the images before you merge, so you don't end up changing it twice. Git will keep all versions on everyones harddrive forever. Best to avoid unneeded changes. 15Kb vs 700 bytes is two orders of magnitude...

Yes. But this time we encountered the size issue after the merging of some new icons. That's why we have now #5489 with a included script so we might run it next time before creating a PR or merge.

**Comment by zander** [comment]
> Yes. But this time we encountered the size issue after the merging of some new icons. That's why we have now #5489 with a included script so we might run it next time before creating a PR or merge.

You say "yes", but I don't see a new push, so you really meant "no", didn't you?

Why don't you update *this* merge with the fixed icons?

**Comment by jonasschnelli** [comment]
@zander Because #5489 is already open and has discussion and is not finished yet.

**Comment by jonasschnelli** [comment]
optimized the two pngs in this pull according to #5489.

**Comment by fanquake** [comment]
Needs rebase

**Comment by jonasschnelli** [comment]
Rebased.

**Comment by fanquake** [comment]
Tested ACK OSX 10.9 with Qt5

**Comment by laanwj** [comment]
This makes the status column too wide here (Ubuntu Qt5). This is not really a problem, but looks asymmetric, because the column is not centered.

untitled

**Comment by jonasschnelli** [comment]
@laanwj My ubuntu 14.04 gives out a more or less centered column.
bildschirmfoto 2015-01-16 um 14 00 51

will try now to center the content in the column.

**Comment by jonasschnelli** [comment]
Centering the QIcon within the QTableWidgetCell would need a custom class with a QPainter (see http://qt-project.org/forums/viewthread/31839). Just setting the alignment did not work.

I don't think it's worth doing this.

**Comment by laanwj** [comment]
Blegh.
Can we make the width adaptive somehow? I don't understand why it shows narrower here.

**Comment by jonasschnelli** [comment]
@laanwj:
Currently i'm not investigating the width issue.
This pull make sense because the current master looks like this on windows:
bildschirmfoto 2015-01-20 um 14 37 11

**Comment by laanwj** [comment]
But it's weird isn't it? The image has a fixed width in pixels. We set a fixed width in pixels. How can this differ so much per OS or seemingly even per theme :/

**Pull request merged**
