### PR TITLE
doc: Various validation doc fixups

### PR DESCRIPTION
**Pull request by maflcko**

### CODE REVIEW

**Comment by MarcoFalke** [comment]
This includes the changes from #21816

**Comment by michaelfolkson** [comment]
This appears to be typos, rephrasing and a renaming of `RewindBlockIndex` to `NeedsRedownload`. It would be nice for reviewers to have a PR description explaining the context for this renaming rather than needing to explore a chain of PRs to figure it out.

**Comment by MarcoFalke** [comment]
> It seems to be introduced in #15606 but that isn't merged yet.

I don't think this pull introduces it either. It is just another outdated comment (or typo) in the pull description.

**Comment by michaelfolkson** [comment]
ACK fac7e42a148897931a9d53ee6e97ec400cfa00b6

**Comment by MarcoFalke** [comment]
> needing to explore a chain of PRs to figure it out

Force pushed to mention the commit id in the commit body

**Comment by michaelfolkson** [comment]
Re-ACK fa4245d88409091a3a6115a96a200b70be663725

**Comment by jnewbery** [comment]
ACK fa4245d884

**Comment by jamesob** [comment]
ACK, thanks!

**Pull request merged**
