### PR TITLE
build: Fix `make apk` for Android w/ non-default SOURCES_PATH in depends

### LINKED ISSUE #22522: build, android: `make apk` fails if depends source cache is in a non-default location
When building the Android dependencies and `SOURCES_PATH` is set to a non-default location (i.e. not in the depends directory), doing `make apk` results in the following error:

```
find: ‘../depends/sources/’: No such file or directory
find: ‘../depends/sources/’: No such file or directory
tar: --exclude=*/*: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
find: ‘../depends/sources/’: No such file or directory
find: ‘../depends/sources/’: No such file or directory
tar: --exclude=*/*: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
find: ‘../depends/sources/’: No such file or directory
find: ‘../depends/sources/’: No such file or directory
tar: --exclude=*/*: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
```

It seems like the culprit is https://github.com/bitcoin/bitcoin/blob/a3791da0e80ab35e862989373f033e5be4dff26b/src/Makefile.qt.include#L385-L387 which is looking for files in the default depends sources path.

### PR DESCRIPTION
**Pull request by hebasto**
On master (1488f55fa57a1400a57be837b574183f019c7855) if depends are built with the customized `SOURCES_PATH` variable, the following `make apk` fails for Android host (see bitcoin/bitcoin#22522).

Fixes bitcoin/bitcoin#22522.

### CODE REVIEW

**Comment by achow101** [comment]
Seems to work.

**Comment by hebasto** [comment]
> This PR is based on #22552, and only the last two commits belong to this one.

The dependency on #22552 could be eliminated by replacing `$(qt_file_name)` with a hardcoded value, but it will definitely bad for maintainability.

**Comment by icota** [comment]
I can confirm this fixes my Android build issues. I haven't yet looked at the code.

**Comment by hebasto** [comment]
Rebased 5005c8e912b561b3a572b19bdd9e35ad98b928f2 -> 57aeb32d888542fba261138ae378ae9e0062c12c ([pr22555.03](https://github.com/hebasto/bitcoin/commits/pr22555.03) -> [pr22555.04](https://github.com/hebasto/bitcoin/commits/pr22555.04)) due to the conflicts with #23473 and #23494.

**Comment by hebasto** [comment]
Rebased 57aeb32d888542fba261138ae378ae9e0062c12c -> a5b568ec74528d0ea94b1ee0392d37e338c97155 ([pr22555.04](https://github.com/hebasto/bitcoin/commits/pr22555.04) -> [pr22555.05](https://github.com/hebasto/bitcoin/commits/pr22555.05)) due to the conflict with #23535.

**Comment by hebasto** [comment]
Rebased a5b568ec74528d0ea94b1ee0392d37e338c97155 -> 03037862fc749685ba2e60c3194d634e16513a54 ([pr22555.05](https://github.com/hebasto/bitcoin/commits/pr22555.05) -> [pr22555.06](https://github.com/hebasto/bitcoin/commits/pr22555.06)) due to the conflict with #23580.

**Comment by hebasto** [comment]
Rebased 03037862fc749685ba2e60c3194d634e16513a54 -> df63d6a5f95da9b70992dcea0baa60f18b852667 ([pr22555.06](https://github.com/hebasto/bitcoin/commits/pr22555.06) -> [pr22555.07](https://github.com/hebasto/bitcoin/commits/pr22555.07)) due to the conflict with #23618.

**Comment by hebasto** [comment]
Rebased df63d6a5f95da9b70992dcea0baa60f18b852667 -> 5b36a11e7ce731bed8d510ef1428687a0b7a0551 ([pr22555.07](https://github.com/hebasto/bitcoin/commits/pr22555.07) -> [pr22555.08](https://github.com/hebasto/bitcoin/commits/pr22555.08)) due to the conflict with #23489.

**Comment by hebasto** [comment]
Rebased 5b36a11e7ce731bed8d510ef1428687a0b7a0551 -> 72005867a4ae6e80c361c8c4f3f800b9854c3791 ([pr22555.08](https://github.com/hebasto/bitcoin/commits/pr22555.08) -> [pr22555.09](https://github.com/hebasto/bitcoin/commits/pr22555.09)) due to the conflicts with #23495 and #23673.

**Comment by hebasto** [comment]
Rebased 72005867a4ae6e80c361c8c4f3f800b9854c3791 -> 4a8fec4fde2c57e7be210ccc71a8c185ef035d56 ([pr22555.09](https://github.com/hebasto/bitcoin/commits/pr22555.09) -> [pr22555.10](https://github.com/hebasto/bitcoin/commits/pr22555.10)) due to the conflict with #23744.

**Comment by hebasto** [comment]
Rebased 4a8fec4fde2c57e7be210ccc71a8c185ef035d56 -> 580efc56ae17dc8523af2ae18a593ed5cb708c05 ([pr22555.10](https://github.com/hebasto/bitcoin/commits/pr22555.10) -> [pr22555.11](https://github.com/hebasto/bitcoin/commits/pr22555.11)) due to the conflict with #23724.

**Comment by hebasto** [comment]
Rebased 580efc56ae17dc8523af2ae18a593ed5cb708c05 -> 5f099742f2737c2e44665469a3768cab7b6e74dd ([pr22555.11](https://github.com/hebasto/bitcoin/commits/pr22555.11) -> [pr22555.12](https://github.com/hebasto/bitcoin/commits/pr22555.12)).

**Comment by hebasto** [comment]
Ok, I reworked this PR:
- dropped dependency on scary #22552
- dropped indentation refactoring commit

Should be a bit easier to review now :)

Friendly ping @achow101 @icota @fanquake

**Comment by achow101** [comment]
ACK 7d310694fc7acc6611890e3eaff36631edb86fef

**Comment by hebasto** [comment]
Rebased 7d310694fc7acc6611890e3eaff36631edb86fef -> 5d166dfc25520906457227b4702621754414e2a3 ([pr22555.13](https://github.com/hebasto/bitcoin/commits/pr22555.13) -> [pr22555.14](https://github.com/hebasto/bitcoin/commits/pr22555.14)) due to the conflict with #24866.

**Comment by hebasto** [comment]
@fanquake 

> Adding more code to our depends and build systems...

Also some lines have been [removed](https://github.com/bitcoin/bitcoin/pull/22555/files#diff-f054095eca878328c57407b87b16556c57551480c6a04c998c93ec0ba7c4bd2f) from `src/Makefile.qt.include` :)

> ... just to accommodate building for android in a "non-default" way is a bit meh. The people using this target with a custom `SOURCES_PATH`, which I'd assume is not many at all...

This PR is not about adding a new feature for a few developers, but about fixing a bug in the existing feature. If consider to accept the point mentioned above, probably #22522 should be closed and the `SOURCES_PATH` variable should be removed from our depends and build system, no?

> ... could also just set `QT_BASE_PATH`.

`QT_BASE_PATH=<some-path> make apk` won't fix #22522.

**Comment by 1440000bytes** [comment]
I followed these steps from [doc/build-android.md](https://github.com/bitcoin/bitcoin/blob/master/doc/build-android.md):

1. Download Android Studio
2. SDK Manager -> SDK Tools -> NDK
3. Use `ANDROID_SDK=/home/test/Android/Sdk ANDROID_NDK=/home/test/Android/Sdk/ndk-bundle make HOST=aarch64-linux-android ANDROID_API_LEVEL=28 ANDROID_TOOLCHAIN_BIN=/home/test/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin`
4. Run `make && make apk` in `src/qt` which gives same error as shared in https://github.com/bitcoin/bitcoin/issues/22522

image

**Comment by hebasto** [comment]
@1440000bytes 
> 3\. Use `ANDROID_SDK=/home/test/Android/Sdk ANDROID_NDK=/home/test/Android/Sdk/ndk-bundle make HOST=aarch64-linux-android ANDROID_API_LEVEL=28 ANDROID_TOOLCHAIN_BIN=/home/test/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin`

I didn't check everything for now, but seeing "NDK (Side be side)" in your screenshot make me believe that `ANDROID_NDK=/home/test/Android/Sdk/ndk-bundle` is wrong. It should be something like `/home/test/Android/Sdk/ndk/23.1.7779620`.

**Comment by 1440000bytes** [comment]
I changed it to `ANDROID_NDK=/home/test/Android/Sdk/ndk/24.0.8215888/` but still same error

**Comment by hebasto** [comment]
@1440000bytes 
> 4\. Run `make && make apk` in `src/qt` which gives same error as shared in https://github.com/bitcoin/bitcoin/issues/22522

It seems really strange for me, as in @achow101's issue _"`SOURCES_PATH` is set to a non-default location"_, but you do not use the `SOURCES_PATH`  variable at all.

Could you provide your commands and error messages exactly from your terminal please?

**Comment by 1440000bytes** [comment]
> Could you provide your commands and error messages exactly from your terminal please?

https://pastebin.com/raw/kkduRKvs

**Comment by hebasto** [comment]
@1440000bytes 
> > Could you provide your commands and error messages exactly from your terminal please?
> 
> https://pastebin.com/raw/kkduRKvs

Thank you!

I think you did not build depends, and missed configuration step. It should be like that:
```
$ make -C depends HOST=aarch64-linux-android ANDROID_SDK=/home/hebasto/Android/Sdk ANDROID_NDK=/home/hebasto/Android/Sdk/ndk/23.1.7779620 ANDROID_API_LEVEL=28 ANDROID_TOOLCHAIN_BIN=/home/hebasto/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/bin
$ ./autogen.sh
$ ./configure --quiet CONFIG_SITE=$PWD/depends/aarch64-linux-android/share/config.site --enable-suppress-external-warnings
$ make clean
$ cd src/qt
$ make
$ make apk
```

**Pull request closed without merging**
