### PR TITLE
Remove unused variable int64_t nEnd. Fix typo: "conditon" → "condition".

### PR DESCRIPTION
**Pull request by practicalswift**
* Remove unused variable `int64_t nEnd`. Last use of `nEnd` removed in commit 1fc8c3d.
* Fix typo: "conditon" → "condition". Typo introduced in commit 439c4e8.

### CODE REVIEW

**Comment by practicalswift** [comment]
Friendly ping @TheBlueMatt and @marcos :-)

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/10862/commits/5a6671c4ca85947b59d03a4f9f0f24412a8f9cf7

**Comment by greenaddress** [comment]
utACK 5a6671c4ca85947b59d03a4f9f0f24412a8f9cf7

**Comment by achow101** [comment]
utACK 5a6671c4ca85947b59d03a4f9f0f24412a8f9cf7

**Comment by MarcoFalke** [comment]
utACK 5a6671c4ca85947b59d03a4f9f0f24412a8f9cf7

**Comment by jonasschnelli** [comment]
utACK 5a6671c4ca85947b59d03a4f9f0f24412a8f9cf7

**Comment by jonasschnelli** [comment]
ACK 323

**Review by dcousens — APPROVED** [review]

**Pull request merged**
