### PR TITLE
Document sizeof(size_t) assumptions and compiler assumptions in assumptions.h

### PR DESCRIPTION
**Pull request by practicalswift**
Document `sizeof(size_t)` assumptions and compiler assumptions by adding compile-time checks in `assumptions.h`.

### CODE REVIEW

**Comment by scravy** [comment]
utACK c7ea8d3236e7c1b0c198345cc78a6754338d3724

**Comment by laanwj** [comment]
utACK c7ea8d3236e7c1b0c198345cc78a6754338d3724
(I don't think these are necessary assumptions, you're supposed to use `uintptr_t` if you want an integer type the same size as a pointer, but ok we do make it in practice)

**Comment by practicalswift** [comment]
@scravy @laanwj Added compiler assumptions for completeness. Please re-review :-)

**Comment by scravy** [comment]
I am not sure that the C++11 assumption is needed. The assumptions in here are about the _platform_, i.e. hardware, system configuration, etc.

Whether bitcoin is built using C++11 or not is pretty much up to the build system, not so much to the underlying platform (whereas I might just be able to configure/make on some alien system violating assumptions about certain types).

I'm not fundamentally opposed it, but I also do not see any necessity for it.

**Comment by practicalswift** [comment]
@scravy When adding `assumptions.h` the goal was to document all tacit assumptions we make that don't follow directly from the standard used. Not specifying the standard was just an oversight from my part -- it should have been there from the beginning :-)

A thought experiment that can be made when considering what assumptions that should be specified explicitly:
* Could it help sound static analysis or other types of formal analysis if an assumption we make was specified explicitly in `assumptions.h`?

If the answer is yes the assumption probably be explicitly stated in `assumptions.h` :-)

**Comment by laanwj** [comment]
> I am not sure that the C++11 assumption is needed. The assumptions in here are about the platform, i.e. hardware, system configuration, etc.

I tend to agree. I like documenting specific, concrete assumptions here about platforms and environments. 
Asserting the C++11 macros seems too sweeping and general. Is there any specific reason bitcoind cannot be built with C++14 or 19 mode if so desired? Will this result in expected bugs besides "we haven't tested it"? If not, let's not include it.

**Comment by practicalswift** [comment]
@laanwj I've now changed to `__cplusplus >= 201103L` to make sure the compiler supports at least the final version of C++11. This will allow for building in say C++14 or 19 mode. Please re-review :-)

**Comment by practicalswift** [comment]
@laanwj An alternative would be to simply issue a warning if a non-C++11 (ISO/IEC 14882:2011) compiler is used:

```
#if __cplusplus != 201104L
#warning ...
#endif
```

WDYT? :-)

**Comment by practicalswift** [comment]
@laanwj Ping - what is your preference? :-)

**Comment by practicalswift** [comment]
FWIW: I've verified that a disassembly of the `bitcoind` binary built with this patch applied is identical to a disassembly of the `bitcoind` binary built against `master` (as expected).

**Comment by laanwj** [comment]
This is fine, let's not have an endless discussion over a pretty insignificant change like this.

**Pull request merged**
