### PR TITLE
build: No longer need to hack the `PATH` variable in `config.site`

### PR DESCRIPTION
**Pull request by hebasto**
This PR adds lacking definitions of absolute paths to some tools in the depends build system.

This improvement makes possible to keep the `PATH` variable untouched during configuration.

Also see https://github.com/bitcoin/bitcoin/pull/24566#discussion_r851125442.

#### Guix builds on `x86_64`:
```
$ find guix-build-$(git rev-parse --short=12 HEAD)/output/ -type f -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum
93fa58bf2a1f5c15c5a547c014036ac79761e5c9622bd5099408ce570b39f02f  guix-build-efa3a807a677/output/aarch64-linux-gnu/SHA256SUMS.part
ef5f53348404ba973dceaf088a4d47dfd0f1fa3d3bf75bdd723b043431de005d  guix-build-efa3a807a677/output/aarch64-linux-gnu/bitcoin-efa3a807a677-aarch64-linux-gnu-debug.tar.gz
6688b2295d564b32ea676c0540c43cdc5211322eddc87e0967b764284e847368  guix-build-efa3a807a677/output/aarch64-linux-gnu/bitcoin-efa3a807a677-aarch64-linux-gnu.tar.gz
4abb3428be477aa7360611689fd28950f30dbbac6a95c454095367d8df11ad72  guix-build-efa3a807a677/output/arm-linux-gnueabihf/SHA256SUMS.part
8dd33389170e83812821d5dd68741db96af1376035ba40af0215a7ae95dcf7fc  guix-build-efa3a807a677/output/arm-linux-gnueabihf/bitcoin-efa3a807a677-arm-linux-gnueabihf-debug.tar.gz
544e97eb88b2a44c8ceb9660399eb5d49d75e07ff59fc03a701a595bacea0491  guix-build-efa3a807a677/output/arm-linux-gnueabihf/bitcoin-efa3a807a677-arm-linux-gnueabihf.tar.gz
219faf1131bdcffffd5979eafd2beabc4a300081f8b1df184852b7183dfbc0e8  guix-build-efa3a807a677/output/arm64-apple-darwin/SHA256SUMS.part
602a417bfa7971fb26d0fe9921d2348fd0d01a5bcf0af93f8a9d50112076e0eb  guix-build-efa3a807a677/output/arm64-apple-darwin/bitcoin-efa3a807a677-arm64-apple-darwin-unsigned.dmg
0dcb197420844da8da3f528a1d986628f7b63adb1e83353d63e8a84da59abc42  guix-build-efa3a807a677/output/arm64-apple-darwin/bitcoin-efa3a807a677-arm64-apple-darwin-unsigned.tar.gz
10efdd33418234a8288c27a614f50e9ff45efbd681fa1c0e173142b6d267cdb8  guix-build-efa3a807a677/output/arm64-apple-darwin/bitcoin-efa3a807a677-arm64-apple-darwin.tar.gz
e5ef02adeb9bcb4675972b0dc233a904006b0940d721049eeb94b14cda34872e  guix-build-efa3a807a677/output/dist-archive/bitcoin-efa3a807a677.tar.gz
a75d2a49b7a8ab1c849e1badff5049a417519f0154b65335a8717d01b8b6ed62  guix-build-efa3a807a677/output/powerpc64-linux-gnu/SHA256SUMS.part
aef63d196487dd0bc597fd53633ac889149f1a126c651ea55f3bec11a092c460  guix-build-efa3a807a677/output/powerpc64-linux-gnu/bitcoin-efa3a807a677-powerpc64-linux-gnu-debug.tar.gz
ddc7913eed26270be271a8712bf351d562d57c746810ea3b7b4101aea8cb6d89  guix-build-efa3a807a677/output/powerpc64-linux-gnu/bitcoin-efa3a807a677-powerpc64-linux-gnu.tar.gz
83bbf4b1af07a2cf7d6014de7c885f0998dd38afacdb5242f5f56505ee704f17  guix-build-efa3a807a677/output/powerpc64le-linux-gnu/SHA256SUMS.part
c9d5d95de98ed987b63a78d4f6e082cb36d5ec3ba71d130601e03d3ebfbd208d  guix-build-efa3a807a677/output/powerpc64le-linux-gnu/bitcoin-efa3a807a677-powerpc64le-linux-gnu-debug.tar.gz
88ed6ec82dd4c1c656fe80b4c49f91a4c15c2ab798dbbe16a3d57393f17d6f3a  guix-build-efa3a807a677/output/powerpc64le-linux-gnu/bitcoin-efa3a807a677-powerpc64le-linux-gnu.tar.gz
7b8e7b3b1e68a2ea0e37c058b284da11e9721ef4d1bc2761ed003b2061358d5f  guix-build-efa3a807a677/output/riscv64-linux-gnu/SHA256SUMS.part
a5de4bedf2b4bc5ab25db21b942076897cabe8a40ce9b0637488af6b4d90693a  guix-build-efa3a807a677/output/riscv64-linux-gnu/bitcoin-efa3a807a677-riscv64-linux-gnu-debug.tar.gz
53023994202887778a001ce00daf7cdc135b9e6c3be034f31645ab4ba5f078c6  guix-build-efa3a807a677/output/riscv64-linux-gnu/bitcoin-efa3a807a677-riscv64-linux-gnu.tar.gz
c6664a61b81dfa080c466d2252a6db70165acbea6cfad51ada16970e9c08bb6f  guix-build-efa3a807a677/output/x86_64-apple-darwin/SHA256SUMS.part
a528569ae4bf5e19401311649086a2d8e3fa5251b44550e623722968dfb111ea  guix-build-efa3a807a677/output/x86_64-apple-darwin/bitcoin-efa3a807a677-x86_64-apple-darwin-unsigned.dmg
9b0384cce7605b546ed581074955f2b9c33cf0817453842036e6224b423b814b  guix-build-efa3a807a677/output/x86_64-apple-darwin/bitcoin-efa3a807a677-x86_64-apple-darwin-unsigned.tar.gz
ebdbd2f3a6406233f27ee48be0ab014991fedba3c0831f79f4a4873f7abf3d7a  guix-build-efa3a807a677/output/x86_64-apple-darwin/bitcoin-efa3a807a677-x86_64-apple-darwin.tar.gz
05a8f71fe67f7193e71ea8bbe6f8df2e651b8ac7da3075ba25aacdd3515f7757  guix-build-efa3a807a677/output/x86_64-linux-gnu/SHA256SUMS.part
30a17a1e3d795ea390cd1e0f3ef74c989b5768ae7415740fcca46befe4cb7206  guix-build-efa3a807a677/output/x86_64-linux-gnu/bitcoin-efa3a807a677-x86_64-linux-gnu-debug.tar.gz
66db846f3fd739089afa5c339659dbf5efb50572f2d29f8288bf24be9e8f1dd0  guix-build-efa3a807a677/output/x86_64-linux-gnu/bitcoin-efa3a807a677-x86_64-linux-gnu.tar.gz
bd3c44890823badcf6d296fa674de14275684be7593f4ab21c0316873ddd8652  guix-build-efa3a807a677/output/x86_64-w64-mingw32/SHA256SUMS.part
6ce3ee21212ff2a95e085073a48194476ade2d5ff94cc1c8ec58a8ae7db8f1fa  guix-build-efa3a807a677/output/x86_64-w64-mingw32/bitcoin-efa3a807a677-win64-debug.zip
5e697c05537cfb2ce2ed95fef25e261e2cfa83a31fd548a98118580c4bbff2e4  guix-build-efa3a807a677/output/x86_64-w64-mingw32/bitcoin-efa3a807a677-win64-setup-unsigned.exe
4cc2bcff98845c792c0ed12a2ea407b25fb85b2d4250d88dca94ed68f42e714d  guix-build-efa3a807a677/output/x86_64-w64-mingw32/bitcoin-efa3a807a677-win64-unsigned.tar.gz
9d5d72271dc6b820e63b30c5c3f9015309777793100b4e2b6ab0c8ea0f7b4aed  guix-build-efa3a807a677/output/x86_64-w64-mingw32/bitcoin-efa3a807a677-win64.zip
```

### CODE REVIEW

**Comment by laanwj** [comment]
Nice. Concept ACK!

**Comment by Empact** [comment]
Concept ACK https://github.com/bitcoin/bitcoin/pull/24866/commits/32995a8d70b9530a9e512aee0cda7673f6ac3c1c + builds cleanly on my system.

**Review by vincenzopalazzo — APPROVED** [review]
Good Job.

ACK https://github.com/bitcoin/bitcoin/pull/24866/commits/32995a8d70b9530a9e512aee0cda7673f6ac3c1c

**Comment by jarolrod** [comment]
Concept ACK

Guix hashes (x86), mine match @hebasto:
```
241bca9422ca6dc83af24ace276d484c1aae093e42d1c541967f1d4811311fb0  guix-build-32995a8d70b9/output/aarch64-linux-gnu/SHA256SUMS.part
1e6e99b768cdb6e5522ef70249709f5576b81747a75e59e733d640855fd49ca9  guix-build-32995a8d70b9/output/aarch64-linux-gnu/bitcoin-32995a8d70b9-aarch64-linux-gnu-debug.tar.gz
829893636e887220b03567dcf823ab1c3e3b7edfa7065eed45420ebe30baff87  guix-build-32995a8d70b9/output/aarch64-linux-gnu/bitcoin-32995a8d70b9-aarch64-linux-gnu.tar.gz
2aca05ef9d20abd78224129412a5df78b850bdc73a3995509d7dddfaf7e76fa8  guix-build-32995a8d70b9/output/arm-linux-gnueabihf/SHA256SUMS.part
7a0918535045e2cb38a06e45c829505e296e818c1dd799e3153d2ce85912c6cc  guix-build-32995a8d70b9/output/arm-linux-gnueabihf/bitcoin-32995a8d70b9-arm-linux-gnueabihf-debug.tar.gz
23c3e55d1cd6b4924fd3f76c2c020b10b2c181a4297d8bdbba28f2a273627c90  guix-build-32995a8d70b9/output/arm-linux-gnueabihf/bitcoin-32995a8d70b9-arm-linux-gnueabihf.tar.gz
a41db7d34d7dead130944b0f579611d10964f1f211906da6efbd6daf39bded67  guix-build-32995a8d70b9/output/arm64-apple-darwin/SHA256SUMS.part
6e22528e290f6c1a37ac4f39bbc57674a5477f61ee093969d8cfea7c45968786  guix-build-32995a8d70b9/output/arm64-apple-darwin/bitcoin-32995a8d70b9-arm64-apple-darwin-unsigned.dmg
253b43592ac0eca29e8671cbef5be4a73c9c3922f26e0868a4bde8531bb40e05  guix-build-32995a8d70b9/output/arm64-apple-darwin/bitcoin-32995a8d70b9-arm64-apple-darwin-unsigned.tar.gz
5e2a3fe6e2aba736ee2c0ca6d734977c785d5f2478d6e84c302be36f3dcb92a5  guix-build-32995a8d70b9/output/arm64-apple-darwin/bitcoin-32995a8d70b9-arm64-apple-darwin.tar.gz
3001f4864b68a1fe205ad6fd959fe6bec954ae19e31ee81c8a80ddddd2ccfd4e  guix-build-32995a8d70b9/output/dist-archive/bitcoin-32995a8d70b9.tar.gz
153d51fd5b849b05fb71d355dcc18c31ef9b53219d874a224fa2cd9b39f0ed1b  guix-build-32995a8d70b9/output/powerpc64-linux-gnu/SHA256SUMS.part
e19c4c6db1ee6f694bc83ec564c6adc13d32890456746a9fdf92f47aac235c20  guix-build-32995a8d70b9/output/powerpc64-linux-gnu/bitcoin-32995a8d70b9-powerpc64-linux-gnu-debug.tar.gz
6b800da00a7ca7b976d4137ce06f430311c291894c3021cd9cedf6ac71b6fef2  guix-build-32995a8d70b9/output/powerpc64-linux-gnu/bitcoin-32995a8d70b9-powerpc64-linux-gnu.tar.gz
89fb1842936211b753f451aee7b14c675aeeb16e6ccbc8bf08946b5a12bb10c6  guix-build-32995a8d70b9/output/powerpc64le-linux-gnu/SHA256SUMS.part
baa01f99d61f65d7084e7266e38dd10395778478eb85e87bac38dd617d01b191  guix-build-32995a8d70b9/output/powerpc64le-linux-gnu/bitcoin-32995a8d70b9-powerpc64le-linux-gnu-debug.tar.gz
4453e25dad25f611a4e20a615cc986a11de861b6adf550daa46dc1a146b538f4  guix-build-32995a8d70b9/output/powerpc64le-linux-gnu/bitcoin-32995a8d70b9-powerpc64le-linux-gnu.tar.gz
49cb54488966408a6f6a5976ed14ddc14236597c9310882a7e584127794e5b62  guix-build-32995a8d70b9/output/riscv64-linux-gnu/SHA256SUMS.part
5af4e11a19f2975db8aba877d661286f64dacc3538ce33e1e93a0fbf2568e4d1  guix-build-32995a8d70b9/output/riscv64-linux-gnu/bitcoin-32995a8d70b9-riscv64-linux-gnu-debug.tar.gz
de81ab7da3fb3154992f27d266d7022d453d5d29238db0c86da0e0cba3416cbd  guix-build-32995a8d70b9/output/riscv64-linux-gnu/bitcoin-32995a8d70b9-riscv64-linux-gnu.tar.gz
ca630a2834bb91638533d6e963686d6aab17ab032c4bae387b6f7f2aa103e5cc  guix-build-32995a8d70b9/output/x86_64-apple-darwin/SHA256SUMS.part
9391e66b291afbecfb6462afde483f9de69f7c700f71cf4eb161e67f6deddd48  guix-build-32995a8d70b9/output/x86_64-apple-darwin/bitcoin-32995a8d70b9-x86_64-apple-darwin-unsigned.dmg
0c2ae56bb2b2d3d5f4e637f000621d06181a44f511a58fef1f9546a044f6b2c7  guix-build-32995a8d70b9/output/x86_64-apple-darwin/bitcoin-32995a8d70b9-x86_64-apple-darwin-unsigned.tar.gz
2938389444782058e21a3332f2d0eea957d6ded50fd5bad308bffbe88f195219  guix-build-32995a8d70b9/output/x86_64-apple-darwin/bitcoin-32995a8d70b9-x86_64-apple-darwin.tar.gz
44144abd1e384a19147b128570b808e5abbc97a6ca0e8a987b98864c3cc3f909  guix-build-32995a8d70b9/output/x86_64-linux-gnu/SHA256SUMS.part
2650f4294072149cb3d84f59ce9e5f22da158663c5e884b049effd8331517c9b  guix-build-32995a8d70b9/output/x86_64-linux-gnu/bitcoin-32995a8d70b9-x86_64-linux-gnu-debug.tar.gz
e236b430186bac08297934e51d789eb49fcad1e7a495c704d42d2cdd94349c62  guix-build-32995a8d70b9/output/x86_64-linux-gnu/bitcoin-32995a8d70b9-x86_64-linux-gnu.tar.gz
ad096d8247911c9eac36734b59c05093bd8b01594ab6ea4041859c82ab6e4e24  guix-build-32995a8d70b9/output/x86_64-w64-mingw32/SHA256SUMS.part
c74444c1dafdf6e5da61c8057128d601e4b2adf2affbb86612a4a17c8ec600f8  guix-build-32995a8d70b9/output/x86_64-w64-mingw32/bitcoin-32995a8d70b9-win64-debug.zip
526c5b418eb9e1ba763bde91ed197d3565fe670fe6aac50bc501ad916ac715df  guix-build-32995a8d70b9/output/x86_64-w64-mingw32/bitcoin-32995a8d70b9-win64-setup-unsigned.exe
ba76eeffeeeefd1999fe0794aa025f729f8a97d041875b59a4c94e8b6bd98cb7  guix-build-32995a8d70b9/output/x86_64-w64-mingw32/bitcoin-32995a8d70b9-win64-unsigned.tar.gz
28949a81ccb6e2ce0fcdb88e61e341cdac5232a31d4bfefc04d6aa224fd632bd  guix-build-32995a8d70b9/output/x86_64-w64-mingw32/bitcoin-32995a8d70b9-win64.zip
```

**Comment by fanquake** [comment]
Concept ACK. It would be good to get the DMG removal in first.

**Comment by hebasto** [comment]
> Concept ACK. It would be good to get the DMG removal in first.

Converting to draft until #24031 goes first.

**Comment by fanquake** [comment]
> Converting to draft until https://github.com/bitcoin/bitcoin/pull/24031 goes first.

#24031 is merged. Let's move forward here.

**Comment by hebasto** [comment]
> > Converting to draft until #24031 goes first.
> 
> #24031 is merged. Let's move forward here.

Done.

**Review by vincenzopalazzo — APPROVED** [review]
Re ACK https://github.com/bitcoin/bitcoin/commit/efa3a807a677659b0b74cdeda944e7c8ce0157fb

**Comment by hebasto** [comment]
Guix builds hashes have been updated in the PR description.

**Pull request merged**
