### PR TITLE
refactor: Use Txid in CMerkleBlock

### PR DESCRIPTION
**Pull request by maflcko**
This should also fix a gcc-13 compiler warning, see https://github.com/bitcoin/bitcoin/pull/28922#discussion_r1407856376

```
rpc/txoutproof.cpp: In lambda function:
rpc/txoutproof.cpp:72:33: error: possibly dangling reference to a temporary [-Werror=dangling-reference]
   72 |                     const Coin& coin = AccessByTxid(active_chainstate.CoinsTip(), Txid::FromUint256(tx));
      |                                 ^~~~
rpc/txoutproof.cpp:72:52: note: the temporary was destroyed at the end of the full expression ‘AccessByTxid((*(const CCoinsViewCache*)(&(& active_chainstate)->Chainstate::CoinsTip())), transaction_identifier<false>::FromUint256((* & tx)))’
   72 |                     const Coin& coin = AccessByTxid(active_chainstate.CoinsTip(), Txid::FromUint256(tx));
      |                                        ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors

### CODE REVIEW

**Review by dergoegge — APPROVED** [review]
Code review ACK fa665711a00b2e39954848160b3e70c60730b276

**Review by sedited — APPROVED** [review]
ACK fa665711a00b2e39954848160b3e70c60730b276

**Comment by TheCharlatan** [comment]
Re-ACK fa02c08c93e5867b7ea07d79ca1c0917dcde88e0

**Review by dergoegge — APPROVED** [review]
reACK fa02c08c93e5867b7ea07d79ca1c0917dcde88e0

**Comment by fanquake** [comment]
cc @achow101

**Comment by achow101** [comment]
Post merge ACK fa02c08c93e5867b7ea07d79ca1c0917dcde88e0

**Pull request merged**
