### PR TITLE
tests: Add FindEarliestAtLeast test for edge cases

### PR DESCRIPTION
**Pull request by ryanofsky**
E.g. repeated max timestamps, extreme int64_t & unsigned int search values.

### CODE REVIEW

**Comment by laanwj** [comment]
Thanks for adding a test. utACK https://github.com/bitcoin/bitcoin/pull/9909/commits/cf66f043687f124f84dc8e471865d7462537e3e7.

**Comment by laanwj** [comment]
Adding @sipa as reviewer, as IIRC he wrote this code.

**Comment by sipa** [comment]
@gmaxwell wrote `FindEarlierAtLeast` (https://github.com/bitcoin/bitcoin/pull/9490).

**Comment by laanwj** [comment]
@gmaxwell can you take a quick look at this test then?

**Comment by ryanofsky** [comment]
@gmaxwell, in case you didn't see this PR, it adds a test for FindEarliestAtLeast, so it's somewhat related to https://github.com/bitcoin/bitcoin/pull/10410 which you recently commented on.

**Pull request merged**
