### PR TITLE
build: remove qt libjpeg check from bitcoin_qt.m4

### PR DESCRIPTION
**Pull request by fanquake**
When gitian building on Windows I'm seeing:
```bash
checking for Qt 5... yes
checking for > Qt 5.7... yes
checking for main in -limm32... yes
checking for main in -lz ... yes
checking for library containing jpeg_create_decompress ... configure: WARNING: libjpeg not found. Assuming qt has it built-in
no
checking for library containing png_error ... -lqtlibpng
checking for library containing pcre2_match_16... -lqtpcre2
checking for library containing hb_ot_tags_from_script ... -lqtharfbuzz
```

We are passing `-qt-libjpeg` to Qt:
https://github.com/bitcoin/bitcoin/blob/e6e99d4f757f2e5052f0cc68951c75e91e4753e3/depends/packages/qt.mk#L66
but I dont think we are doing anything with `jpeg` related regardless?

### CODE REVIEW

**Review by theuni — DISMISSED** [review]
Concept ACK. IIRC we used some jpegs ages ago, but since removal this is overdue.

Could you switch to the qt config to -no-jpeg as well? It shouldn't affect the end-result in any meaningful way because all of the unused jpeg stuff should be stripped out by the linker anyway, but we can at least avoid compiling libjpeg as part of the qt build.

**Comment by dongcarl** [comment]
Concept ACK, agree that we should remove `-no-jpeg`, and also `libjpeg` from `doc/dependencies.md`

**Comment by fanquake** [comment]
Added `-no-libjpeg` to Qts configure flags, and removed jpeg from `doc/dependencies.md`. 
Also added a commit that removes the line numbers from the qt packages that we reference in there, as at the moment they are constantly incorrect.

**Comment by laanwj** [comment]
Good catch, I struggle to remember what we ever needed `jpeg` for, so I searched history:
```
 delete mode 100644 src/qt/res/images/splash2.jpg
```
it was removed in 2013 in f9124587ccea723dbd743e3877a7071fbb6c5732

ACK f509e3b8ce0c5652e85ce26545f7ed94689f46ab

**Review by laanwj — APPROVED** [review]

**Comment by promag** [comment]
ACK f509e3b8ce0c5652e85ce26545f7ed94689f46ab.

**Pull request merged**
