### PR TITLE
Master: Change the -keypool info text 

### PR DESCRIPTION
**Pull request by bom64**
Current: 
Set key pool size to <n> (default: %u), 

New maybe something like: 
Set key pool size to <n> (default: %u, does not refill keypool if wallet already exists).

### CODE REVIEW

**Comment by jonasschnelli** [comment]
I think you need to rebase against master or clean up your git history.

**Comment by laanwj** [comment]
I'd prefer not putting the extra text in the parenthesis. It has nothing to do with the default and looks circuitous. Maybe:

    Set key pool size. Passing this option does not trigger a keypool refill. (default: %u),

Also: pull requests should be against master, not 0.12

**Comment by bom64** [comment]
The trigger for this issue was that I was use -keypool when the wallet.dat exist but there was no message at all that the wallet.dat was unchanged. It was only because I was monitor the size og wallet.dat that I was realise that notting happen. I error message will be nice a la:
-keypool can not be use on a already existed wallet.dat. You can type keypoolrefill into the console (Help->Debug window->Console).

**Comment by laanwj** [comment]
> The trigger for this issue was that I was use -keypool when the wallet.dat exist but there was no message at all that the wallet.dat was unchanged. It was only because I was monitor the size og wallet.dat that I was realise that notting happen. I error message will be nice a la:
-keypool can not be use on a already existed wallet.dat. You can type keypoolrefill into the console (Help->Debug window->Console).

I understand, makes sense to add this statement.

I have to close this PR though, please create a new pull that starts from master instead of the 0.12 branch.

**Comment by MarcoFalke** [comment]
@bom64 https://www.google.com/#q=git+101 Might come in handy. ;)

**Comment by bom64** [comment]
Yes! :-)

**Pull request closed without merging**
