### PR TITLE
validation: Add compile-time checking for negative locking requirement in LimitValidationInterfaceQueue

### PR DESCRIPTION
**Pull request by practicalswift**
This PR adds compile-time checking for negative locking requirements that follow from the run-time locking requirement `AssertLockNotHeld(cs_main)` in `LimitValidationInterfaceQueue(...)`.

Changes:
* Add `LOCKS_EXCLUDED(cs_main)` to `LimitValidationInterfaceQueue(...)` which does `AssertLockNotHeld(cs_main)`
* Add `LOCKS_EXCLUDED(cs_main)` to `CChainState::ActivateBestChain(…)`, `CChainState:: InvalidateBlock(…)` and `CChainState::RewindBlockIndex(…)` which all call `LimitValidationInterfaceQueue(...)` which does `AssertLockNotHeld(cs_main)`
* Add `LOCKS_EXCLUDED(cs_main)` to `InvalidateBlock(…)` which calls `CChainState::InvalidateBlock(...)` which in turn calls `LimitValidationInterfaceQueue(...)` which  does `AssertLockNotHeld(cs_main)`
* Add `LOCKS_EXCLUDED(cs_main)` to `RewindBlockIndex(…)` which calls `CChainState::RewindBlockIndex(...)` which in turn calls `LimitValidationInterfaceQueue(...)` which does `AssertLockNotHeld(cs_main)`

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Could squash the 6-line patch into one commit?

**Comment by practicalswift** [comment]
@MarcoFalke Good idea! Now squashed. Please re-review :-)

**Comment by jamesob** [comment]
This causes a warning during compilation because we call ABC here with cs_main held: https://github.com/bitcoin/bitcoin/blob/master/src/validation.cpp#L3953-L3962

**Comment by MarcoFalke** [comment]
@jamesob This issue is reported in

* Inconsistent locking behavior in LoadChainTip #15967

**Pull request merged**
