### PR TITLE
[0.13] Various backports

### PR DESCRIPTION
**Pull request by sipa**
This includes backports of #8520 #8540 #8282 #7579 #8624 #8604 #8291 #8524 #8612 #8651 #8606 #8594.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Thanks for going through all the tagged pulls. Could you also include #8646 and close it afterward?

**Comment by gmaxwell** [comment]
ACK.

**Comment by btcdrak** [comment]
ACK ab295bb

**Comment by fanquake** [comment]
ACK ab295bb

**Comment by laanwj** [comment]
utACK ab295bb - removed need backport tags from all referred pull requests

**Comment by MarcoFalke** [comment]
> removed need backport tags from all referred pull requests

I think you missed some, but they are now removed.

**Pull request merged**
