### PR TITLE
depends: bump miniupnpc and ccache

### PR DESCRIPTION
**Pull request by fanquake**
@theuni mentioned we can bump miniupnpc to 1.9.20150730 in #6583.
[release notes](http://miniupnp.tuxfamily.org/files/changelog.php?file=miniupnpc-1.9.20150730.tar.gz)

```
$Id: Changelog.txt,v 1.212 2015/07/23 20:41:50 nanard Exp $
miniUPnP client Changelog.
2015/07/23:
  split getDevicesFromMiniSSDPD
  add ttl argument to upnpDiscover() functions
  increments API_VERSION to 14

2015/07/22:
  Read USN from SSDP messages.

2015/07/15:
  Check malloc/calloc

2015/06/16:
  update getDevicesFromMiniSSDPD() to process longer minissdpd
    responses
```

We could also bump ccache to 3.2.3 (currently 3.2.2) [release notes](https://ccache.samba.org/releasenotes.html#_ccache_3_2_3)

```
ccache 3.2.3
Release date: 2015-08-16

New features and improvements
Added support for compiler option -gsplit-dwarf.

Bug fixes
Support external zlib in nonstandard directory.

Avoid calling exit() inside an exit handler.

Let exit handler terminate properly.

Bail out on compiler option --save-temps in addition to -save-temps.

Only log "Disabling direct mode" once when failing to read potential include files.
```

qrencode (3.44) and protobuf (2.6.1) are still both the most recent releases.

Boost 1.59.0 is out, release notes [here](http://www.boost.org/users/history/version_1_59_0.html)

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Tried a gitian build... seems to be a hash/checksum issue somewhere:
https://builds.jonasschnelli.ch/pulls/6619/
https://builds.jonasschnelli.ch/pulls/6619/build-linux.log

**Comment by fanquake** [comment]
Can you manually download http://miniupnp.free.fr/files/miniupnpc-1.9.20150730.tar.gz, and see if you get different SHA256?
```
7730c60cdddb6c7788f5c068a52cf55db8cee126304f86becd9a52c825b8cdc2
```

**Comment by jonasschnelli** [comment]
Jup. Is different.
```
jonasschnelli$ openssl dgst -sha256 miniupnpc-1.9.20150730.tar.gz 
SHA256(miniupnpc-1.9.20150730.tar.gz)= 1d64fab1fd3b4c8545139341ba197f19329a863f4f21b578fc2a228ab586a604
```

**Comment by fanquake** [comment]
Interesting, can someone else download and confirm I'm generating the wrong hash?
```
fanquake$ openssl dgst -sha256 miniupnpc-1.9.20150730.tar.gz 
SHA256(miniupnpc-1.9.20150730.tar.gz)= 7730c60cdddb6c7788f5c068a52cf55db8cee126304f86becd9a52c825b8cdc2

fanquake$ shasum -a 256 miniupnpc-1.9.20150730.tar.gz 
7730c60cdddb6c7788f5c068a52cf55db8cee126304f86becd9a52c825b8cdc2  miniupnpc-1.9.20150730.tar.gz
```

**Comment by theuni** [comment]
```bash
cory@cory-i7:/tmp$ sha256sum miniupnpc-1.9.20150730.tar.gz 
1d64fab1fd3b4c8545139341ba197f19329a863f4f21b578fc2a228ab586a604  miniupnpc-1.9.20150730.tar.gz
```

**Comment by laanwj** [comment]
Just downloaded:
```
Sha256: 1d64fab1fd3b4c8545139341ba197f19329a863f4f21b578fc2a228ab586a604  miniupnpc-1.9.20150730.tar.gz
Size: 81431 
```
Would be very interested in @fanquake's variant.

**Comment by fanquake** [comment]
I've amended the miniupnpc commit

@laanwj If I download using the depends system, or wget, directly I'm getting the correct file and hash. However if I download using the exact same link in Chrome, I'm getting a different 400kb file..

**Comment by theuni** [comment]
@fanquake same! firefox is the good hash, chromium is different (7730c60cdddb6c7788f5c068a52cf55db8cee126304f86becd9a52c825b8cdc2, same as yours). Investigating now.

**Comment by theuni** [comment]
ok, mystery solved, though it only raises further questions:
```bash
cory$ sha256sum miniupnpc-1.9.20150730.tar.gz 
1d64fab1fd3b4c8545139341ba197f19329a863f4f21b578fc2a228ab586a604  miniupnpc-1.9.20150730.tar.gz
cory$ gzip -d miniupnpc-1.9.20150730.tar.gz 
cory$ sha256sum miniupnpc-1.9.20150730.tar 
7730c60cdddb6c7788f5c068a52cf55db8cee126304f86becd9a52c825b8cdc2  miniupnpc-1.9.20150730.tar
```

**Comment by laanwj** [comment]
ACK

**Comment by laanwj** [comment]
This is the complete diff between the two miniupnp versions: https://gist.github.com/laanwj/18e5da2b68f3a7127e27

**Comment by theuni** [comment]
post-merge ACK

**Pull request merged**
