### PR TITLE
gui: New filesave icon, updated copyright

### PR DESCRIPTION
**Pull request by GChuf**
Updated the filesave icon (the original was the same as the receive.png)
Updated and fixed some typos in the copyright file

### CODE REVIEW

**Comment by gapeman** [comment]
Sorry for the initial mess everyone. I created a cleaner pull request with only 1 commit.
I still don't have any screenshots, else I would upload them.

**Comment by emilengler** [comment]
See #16583

**Comment by fanquake** [comment]
Concept ACK on an icon that is more obviously a "save" action, and different from receive. However I don't see these icons on macOS, so will leave it up to others to comment. In any case, the new icon file can be compressed by about ~50%.

Old filesave icon:
filesave_old

New filesave icon:
filesave_new

**Comment by jonasschnelli** [comment]
I'm not a license guy... but is the Creative Commons BY 3.0 compatible with out MIT license?
@luke-jr @wtogami maybe?

**Comment by gapeman** [comment]
@fanquake what do you mean by compression - reducing image size in pixels, indexing png, something else? I thought Qt takes care of compression when compiling.

As for licences compatibility, I found [this](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software) and [this](https://opensource.stackexchange.com/questions/324/are-permissive-licenses-mit-bsd-zlib-compatible-with-cc-by). I think for this case it should be fine.

**Comment by emilengler** [comment]
@jonasschnelli Yes but I think only when we add the name of the author to our COPYING file like
```
Copyright (c) 2009-2019 The Bitcoin Core developers
Copyright (c) 2009-2019 Bitcoin Developers
Copyright (c) 2019 (or whatever date he made the icon) THE_GUY_WHO_CREATED_THIS_ICON
```
Also I'm not a lawyer but CC-BY means in general that we only need to mention the author, probably in the copying file. Although it might be possible if we create a THANKS file which includes names like the guy who made the icon. Many other projects have this

**Comment by MarcoFalke** [comment]
Yeah, I think we'd have to update the GUI About dialog to include the authors of the icons.

**Comment by jonasschnelli** [comment]
> Yeah, I think we'd have to update the GUI About dialog to include the authors of the icons.

I think it's not worth the effort for a single icon.
Maybe @gapeman can take or modify an existing icon from the typicons family?

Also, we should not forget that the floppy-disk icon may appeal to "older guys" (like us?)... but those disks are out of use since years and have no longer anything to do with "persistence store".
It's like showing a phone-hook-modem when meaning "the internet".

**Comment by MarcoFalke** [comment]
@jonasschnelli We don't mention Stephen Hutching in the about dialog right now. Even if that is not required by the license, it feels like a nice gesture to do.

Agree that we shouldn't use a floppy disk as the "save icon". Apart from ms word no one is using that anymore these days.

**Comment by jonasschnelli** [comment]
> @jonasschnelli We don't mention Stephen Hutching in the about dialog right now:

See https://github.com/bitcoin/bitcoin/issues/6367#issuecomment-118250990. Stephen agreed to distribute it under MIT.
I think either we mention all gfx designers in the about dialog or none. I guess people accept and agree that this project is not about persona.

**Comment by gapeman** [comment]
I agree that it's not worth the effort for a single icon. None of the typicons seem to really represent _saving_, so I was thinking about creating an icon myself.
I also came across these icons, all licensed under MIT, which might come in handy in the future: [[1]](https://ionicons.com/) [[2]](https://iconify.design/icon-sets/raphael/)

And even though floppy disks aren't used anymore, we all know what the icon means and I think it's still being used extensively. Notepad++ comes to mind and my search results across various search engines all output floppy disk icons when searching for a "save icon".
I'm not aware of any other "standard" save icons and personally would like to see this trend survive.

**Comment by MarcoFalke** [comment]
The only icon I found was the one in libreoffice, which looks similar to our old save icon.

Screenshot from 2019-08-12 13-26-06

**Comment by gapeman** [comment]
I'm not sure what the point was, @MarcoFalke. Version 5.1.6.2 of libreoffice that I have installed uses floppy disk icons, but I don't want to get into a conversation which programs use what.

Here's libreoffice floppy disk icon screenshot (which I like) and should probably be hidden somewhere in the official github libreoffice repo ...
Screenshot_52

I think we should all just vote for **either** _floppy disk_ or _something else_.

**Comment by emilengler** [comment]
I still think everyone knows what is meant by a floppy disk :)

**Comment by gapeman** [comment]
I've made an icon myself from scratch:
filesave crushed

I've also found the [optimize-pngs.py](https://github.com/bitcoin/bitcoin/blob/master/contrib/devtools/optimize-pngs.py) script fanquake was probably referring to.

The result in bitcoin-qt (I spent a while optimizing the icon so it looks great in qt):
Screenshot_59

I'd like to put the file under public domain. What do you think?

**Comment by kristapsk** [comment]
I agree that most people know what floppy disk icon means, but it will become less and less intuitive in the future and I'm also not sure is the right way to go. There are more and more computer users nowadays that haven't seen any floppy disk in their entire life.

**Comment by emilengler** [comment]
I personally think this icon doesn't fit in that good. I prefer the older one as it looks more like the others, but this is my opinion so **NACK** sorry :(

**Comment by laanwj** [comment]
If this requires any special license exemptions it's not worth it, IMO. We simplified the licensing a lot, one time, by switching from gathered icons to icons from one icon set. From a practical perspective that's great and also ensures consistency.

No opinion on floppy disk versus box-with-arrow.

> However I don't see these icons on macOS, so will leave it up to others to comment.

BTW: are menu icons even still a thing in modern GUI? At least GNOME hasn't displayed them anymore for a long time. Same for MacOSX apparently. Might consider removing them completely.

**Comment by MarcoFalke** [comment]
Just tested on Fedora 30, and it looks like they aren't even shown. So I tend to agree with @laanwj 


Screenshot from 2019-08-14 07-45-26

**Comment by jonasschnelli** [comment]
Closing this due not worth the effort
Thanks anyways @gapeman for the intention to improve.
Maybe this leads to a PR removing all the menu icons...

**Comment by promag** [comment]
Also agree with removing the icons.

**Comment by luke-jr** [comment]
Menu icons are still used in KDE at least.

**Pull request closed without merging**
