### PR TITLE
WIP: Reduce MinRelayFee slower when Mempool utilised and faster when needed.

### PR DESCRIPTION
**Pull request by rebroad**
I'm not sure whether to label this WIP or not. It's a little experimental, and perhaps only needed on nodes with a small maxmempool (tested on 50MB).

It's attempting to address the issue #21558 

Example in action:-
image

### CODE REVIEW

**Comment by JeremyRubin** [comment]
interesting!

Can you comment the code a bit better I found it a bit confusing how it's working.

**Comment by rebroad** [comment]
@JeremyRubin 
image
Perhaps this image helps - it basically drops the minrelayfee if the mempool utilization goes below 90% quite quickly, but also quickly restores it to what the current algorithm sets it to, if utilization picks up again.
The other change I made is that if utilization is 90% or above it doesn't reduce the minrelayfee at all - only if it goes below 90%.

I suspect that the rapid changing of the minrelayfee might look too much for some, but with the way feefilter messages are delayed then it doesn't change how often messages are sent so much, and minrelayfee changes less often when memory utilization stays around 90% or above.

**Comment by rebroad** [comment]
What I think would be more ideal than this solution, is two rolling numbers... The existing one perhaps ought to decrease slower than it currently does, and then a 2nd number that adjusts to the first number, but much more quickly (but not as quickly as with this pull request in its current form). The 2nd number ought to have a "half-life" of around 5 or 10 minutes, I suspect.

**Comment by rebroad** [comment]
Upon further testing, this algo is broken as the minfee should never go up unless it's during the process of deleting TXs from the mempool - if it goes up in any other event, then this creates a band of missing TXs due to my addition of not reducing the minfee until mempool utilization goes below 90% (or 80%) - it just pads the mempool with low Sat/B TXs which never get used.

So, the algo needs to change to either remove the condition (of utilization) before reducing the minfee, or not raising the minfee unless the mempool is actually full. And a better determination for lowering minfee quickly perhaps would be when we receive a block, and setting it based on the lowest Sat/B TX (that was taken from our mempool) in that block.

**Comment by rebroad** [comment]
image
I've fixed the issues with the algo, and I'm quite happy with the way it works now. Continuing to test it, but it seems to work well, with no issues so far.

**Comment by rebroad** [comment]
Showing some comparisons between existing behaviour and new behaviour:-
image
image

**Comment by rebroad** [comment]
ok, this (https://github.com/bitcoin/bitcoin/pull/21618/commits/fde749e23401c1115b69e2612479755ac095c56f) broke the fuzzer - might be best to remove it for now.

**Pull request closed without merging**
