### PR TITLE
cli: Ignore libevent warnings

### PR DESCRIPTION
**Pull request by theuni**
Should fix rpc tests that fail due to an unclean stderr.

Untested as I'm not seeing these warnings. @promag mind seeing if this fixes your problem?

### CODE REVIEW

**Comment by laanwj** [comment]
utACK

**Comment by laanwj** [comment]
utACK 0231ef6c6d4f45edffda4ac3bce2048f9c8a8c00

**Comment by Empact** [comment]
According to the below the default is to log message to stderr, do we want to keep logging the lower-level messages?
http://www.wangafu.net/~nickm/libevent-book/Ref1_libsetup.html

**Comment by laanwj** [comment]
Yes, the messages go to stderr. Which is normally fine, at least they don't mess up the application output!
But iwas causing problems in the test for @promag.

**Comment by Empact** [comment]
Maybe send them to the `debuglogfile`?

**Comment by laanwj** [comment]
No, bitcoin-cli should definitely not write to any debug log file.

**Comment by laanwj** [comment]
@promag Can you test this? It's kind of blocked on that.

**Comment by promag** [comment]
Tested ACK 0231ef6 - it fixes my problem. @theuni how could I test the `throw` added?

Before:
```
./src/bitcoin-cli -regtest help
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
== Blockchain ==
getbestblockhash
...
```
After
```
./src/bitcoin-cli -regtest help
== Blockchain ==
getbestblockhash
...
```

**Comment by MarcoFalke** [comment]
> @theuni how could I test the throw added?

@promag You can test the `throw` by replacing `severity >= EVENT_LOG_ERR` with `true`. Would you mind doing that post-merge, please?

**Pull request merged**
