### PR TITLE
doc: fix typos

### PR DESCRIPTION
**Pull request by rex4539**

### CODE REVIEW

**Comment by hebasto** [comment]
@DrahtBot seems insisting :)

**Comment by hebasto** [comment]
```
$ git fetch origin pull/23500/merge
$ git checkout FETCH_HEAD 
$ test/lint/lint-spelling.sh 
src/util/syscall_sandbox.cpp:128: creat ==> create
test/functional/wallet_multisig_descriptor_psbt.py:88: justs ==> just
^ Warning: codespell identified likely spelling errors. Any false positives? Add them to the list of ignored words in test/lint/lint-spelling.ignore-words.txt
```

and https://github.com/bitcoin/bitcoin/pull/22067#discussion_r744258501

**Comment by rex4539** [comment]
@hebasto added, thanks!

**Comment by katesalazar** [comment]
Concept ACK.

**Comment by hebasto** [comment]
`src/util/syscall_sandbox.cpp:128: creat ==> create` -- could this warning be silenced by adjusting an ignored words list?

**Review by hebasto — APPROVED** [review]
ACK 2de1ceb2e9180d40611a6d32b3a9470c242952e0

**Comment by rex4539** [comment]
> `src/util/syscall_sandbox.cpp:128: creat ==> create` -- could this warning be silenced by adjusting an ignored words list?

`codespell --ignore-words-list creat`

**Pull request merged**
