### PR TITLE
doc: Extract CreateTxDoc in rawtransaction

### PR DESCRIPTION
**Pull request by fanquake**
For the fields: inputs, outputs, locktime, replaceable. Similar to #23172.

Can be reviewed with `--color-moved=dimmed-zebra --color-moved-ws=ignore-all-space`.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
review ACK 5bb1f42f492a4e33faebf19e505f67b8581b3001 🙂

<details><summary>Show signature</summary>

Signature:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

review ACK 5bb1f42f492a4e33faebf19e505f67b8581b3001 🙂
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEE+rVPoUahrI9sLGYTzit1aX5ppUgFAlwqrYAACgkQzit1aX5p
pUiEXAwAqDv3q5tres7kUZ6Gt8laQrVjhLA2/9PS8G8OafKVcwbsL8lhFBpBo4WM
ZeGBKASDrP5Ow4ZiRzQpuIP58ghoKwKblzn1XeLy/HsPLB0ewmapnnUGnzRTIp1K
3SBE/NrqkE/o45Zj1yKXLdmPqf8TpbiAImX75hWc/LoA6sT2I6EfeWW4+lY7mEye
p+bKdEvhR0rGFC1yBZM1bbHmVokVPERGXaLAkKGqcDqgW/Vxsr5H4n5R2NTcYLx9
D0OVQ5lnx/N0YQyu0Ubl02KsJ1bVb5H80oBhItZnDr7SVu7QiswIacMq5HKmGRBc
qSR1XXkChqxbBmzgwZY6Z/IaMvyGJvy9O+XNbci1zPFP4A9GMlhNnp5AEIw0erHk
eIcSNDGv+oHQ2YVKTfVUvpjqtGzLB9ODjvZam2UOEg33rKNxaya2SRwI14a8aqMv
dTAMrOxcqAbMpnaukKj4UuSENBj0NU0GuJYcgS5gYt9Pa1aGhchxUmXnjuhUy43q
rFUjPGAx
=v2Sk
-----END PGP SIGNATURE-----
```


</details>

**Comment by MarcoFalke** [comment]
rendered diff:

```diff
diff --git a/createpsbt b/createpsbt
index a8eac97..4253601 100644
--- a/createpsbt
+++ b/createpsbt
@@ -4,7 +4,7 @@ Creates a transaction in the Partially Signed Transaction format.
 Implements the Creator role.
 
 Arguments:
-1. inputs                      (json array, required) The json objects
+1. inputs                      (json array, required) The inputs
      [
        {                       (json object)
          "txid": "hex",        (string, required) The transaction id
diff --git a/createrawtransaction b/createrawtransaction
index cd68d55..787eb2e 100644
--- a/createrawtransaction
+++ b/createrawtransaction
@@ -31,7 +31,7 @@ Arguments:
        ...
      ]
 3. locktime                    (numeric, optional, default=0) Raw locktime. Non-0 value also locktime-activates inputs
-4. replaceable                 (boolean, optional, default=false) Marks this transaction as BIP125-replaceable.
+4. replaceable                 (boolean, optional, default=false) Marks this transaction as BIP125 replaceable.
                                Allows this transaction to be replaced by a transaction with higher fees. If provided, it is an error if explicit sequence numbers are incompatible.
 
 Result:

**Comment by MarcoFalke** [comment]
Maybe keep the `-` for BIP125-replacable?

**Comment by fanquake** [comment]
> Maybe add the - for BIP125-replacable?

Done. Added to `FundTxDoc` as well.

**Comment by MarcoFalke** [comment]
ACK c771ee8571dc63d27747ef565671eb1dcdc0ff4b 😸

<details><summary>Show signature</summary>

Signature:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK c771ee8571dc63d27747ef565671eb1dcdc0ff4b 😸
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEE+rVPoUahrI9sLGYTzit1aX5ppUgFAlwqrYAACgkQzit1aX5p
pUhd/AwAuWCNiLEVqg20NYsBxrZC+fbL3sCJfpT9hDUIogN49LmpvQIZuY4qliHz
AnF4ttfGmMupUSHVSIaOyCSHLwecDdYbotOicOCZAa/AQA3YTfcj2HqEwwZZ59ul
2doL/eJ5z+umklkAAkXhoA1RGdsrflwIxpIYVORmFuuajjvmHBKNZf+nGg8c708S
9txBI6OxpXh3q+XHmnw2b64SQ62saqbtOCnqXzV/PRoip6DIjezO2F5yp0xG3rJr
fDYsf/CXQIpOl9pgrHWyzxTV4l7xxlhrCL5ULO6i6pYY4wTzgtuprqRpYxxd6ljp
y2qWjHd3MOa1F1brFjX5zBjU8tSaN20pXQHkpYdABlv2O2U1MglCJdNeFl8/OvbL
UlP+NClCW30c7YqzLsuS6ptMD61Qiyeb1SaaPs1Fr7LkkjaY9TTmCvP53F+RP2JL
bet6q9jcynq7VxSo7X0eRjs/O7GWsKYKoVS3NzO6y8jxrib0djRz3SL9d/rqx8f+
+fnoVx7M
=/3Cu
-----END PGP SIGNATURE-----
```


</details>

**Comment by MarcoFalke** [comment]
rendered diff:

```diff
diff --git a/createpsbt b/createpsbt
index a8eac97..a1018ca 100644
--- a/createpsbt
+++ b/createpsbt
@@ -4,7 +4,7 @@ Creates a transaction in the Partially Signed Transaction format.
 Implements the Creator role.
 
 Arguments:
-1. inputs                      (json array, required) The json objects
+1. inputs                      (json array, required) The inputs
      [
        {                       (json object)
          "txid": "hex",        (string, required) The transaction id
@@ -28,7 +28,7 @@ Arguments:
        ...
      ]
 3. locktime                    (numeric, optional, default=0) Raw locktime. Non-0 value also locktime-activates inputs
-4. replaceable                 (boolean, optional, default=false) Marks this transaction as BIP125 replaceable.
+4. replaceable                 (boolean, optional, default=false) Marks this transaction as BIP125-replaceable.
                                Allows this transaction to be replaced by a transaction with higher fees. If provided, it is an error if explicit sequence numbers are incompatible.
 
 Result:
diff --git a/fundrawtransaction b/fundrawtransaction
index 4490741..a93652c 100644
--- a/fundrawtransaction
+++ b/fundrawtransaction
@@ -42,7 +42,7 @@ Arguments:
                                       "unset"
                                       "economical"
                                       "conservative"
-       "replaceable": bool,           (boolean, optional, default=wallet default) Marks this transaction as BIP125 replaceable.
+       "replaceable": bool,           (boolean, optional, default=wallet default) Marks this transaction as BIP125-replaceable.
                                       Allows this transaction to be replaced by a transaction with higher fees
        "solving_data": {              (json object, optional) Keys and scripts needed for producing a final transaction with a dummy signature.
                                       Used for fee estimation during coin selection.
diff --git a/send b/send
index 28c0ea6..2a59110 100644
--- a/send
+++ b/send
@@ -59,7 +59,7 @@ Arguments:
                                          "unset"
                                          "economical"
                                          "conservative"
-       "replaceable": bool,              (boolean, optional, default=wallet default) Marks this transaction as BIP125 replaceable.
+       "replaceable": bool,              (boolean, optional, default=wallet default) Marks this transaction as BIP125-replaceable.
                                          Allows this transaction to be replaced by a transaction with higher fees
        "solving_data": {                 (json object, optional) Keys and scripts needed for producing a final transaction with a dummy signature.
                                          Used for fee estimation during coin selection.
diff --git a/walletcreatefundedpsbt b/walletcreatefundedpsbt
index 1f3f357..d2a172f 100644
--- a/walletcreatefundedpsbt
+++ b/walletcreatefundedpsbt
@@ -55,7 +55,7 @@ Arguments:
                                       "unset"
                                       "economical"
                                       "conservative"
-       "replaceable": bool,           (boolean, optional, default=wallet default) Marks this transaction as BIP125 replaceable.
+       "replaceable": bool,           (boolean, optional, default=wallet default) Marks this transaction as BIP125-replaceable.
                                       Allows this transaction to be replaced by a transaction with higher fees
        "solving_data": {              (json object, optional) Keys and scripts needed for producing a final transaction with a dummy signature.
                                       Used for fee estimation during coin selection.

**Pull request merged**
