### PR TITLE
[23.x] Backports

### PR DESCRIPTION
**Pull request by fanquake**
Backports:
* https://github.com/bitcoin/bitcoin/pull/26909
* https://github.com/bitcoin/bitcoin/pull/26924
* https://github.com/bitcoin/bitcoin/pull/26944

### CODE REVIEW

**Comment by MarcoFalke** [comment]
ACK 412cd1a34e035c1a2f35f4b4ac14eb192835950c 👬

<details><summary>Show signature</summary>

Signature:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK 412cd1a34e035c1a2f35f4b4ac14eb192835950c 👬
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEE+rVPoUahrI9sLGYTzit1aX5ppUgFAlwqrYAACgkQzit1aX5p
pUiz6gwAoNzijbCNloDVVJ7Ds33zFamQZr8PrN05T+q08mATepW9Hxr3vbd8vXbD
F6WDQFaXcnF5q/ULgDQBGFibXmxIkRiL+O/QN/4y0lDNxy/0xu/oSRyaWwhUPtHs
FAdpqrHOlqRhwfF1CBDrd/4V8feo5NfP1ehCBx5jwbasCjZ6J/lOStIPuxq7pU5k
xkoQZrb8OaKRQW4VsVRBJ72SQqrVC3dQu6zVGKxmFtaiOfzMUq1w95ZnWFF8bt32
wPZpsIvJRiNP1lwKx6tzi+9FfKWDgSZxgyGFxKfajEY9lkGgo5Q65JIrmWeZi8MO
Tzdx8x2fhcSJISqFFKL+Aoy6buGJjuuVxgMnmNUdALnNrmq9vmdJxZuOZoNTjfQB
587z6wqz/RSrulMahOnNP09kqXoZx273zV66pUiVwMt6cltjcNJh8cpywEKAYfEr
echfqkYbe/FvjoQm12i98vG9WqUrcYcbv9wtbPBFSGsWH61+Lf0JMXwAN/VToF3i
oHNy55Vn
=E5XQ
-----END PGP SIGNATURE-----
```


</details>

**Comment by fanquake** [comment]
Compiling 23.x (398768769f85cc1b6ff212ed931646b59fa1acd6) with GCC 13 requires additional include fixes to what is already backported, so I've added a commit with them.

**Comment by instagibbs** [comment]
Only extra commit/change is af862661654966d5de614755ab9bd1b5913e0959 

ACK https://github.com/bitcoin/bitcoin/pull/26921/commits/52376d9217060ce84e992e374d5dc2beae40bb06

**Comment by fanquake** [comment]
Also merging this to unbreak the GCC 13 build.

**Pull request merged**
