### PR TITLE
Refactor CBlockHeaderAndShortTxIDs::GetShortID into CTransaction

### PR DESCRIPTION
**Pull request by pstratem**
I'd like to use the short id scheme for mempool syncing.

### CODE REVIEW

**Comment by petertodd** [comment]
I'm a bit dubious about mixing in this non-consensus-critical code into the consensus-critical CTransaction, though I don't know what's the right alternative for you.

**Comment by dcousens** [comment]
weak NACK,  but only from the point of view that I feel the context specific ID algorithms should remain, context specific.
You've shown here how easy it would be to outline that new mempool syncing scheme just using `SipHashUint256` directly.   The two being the same is just consequential.

**Comment by laanwj** [comment]
Tend to agree to keep this a separate function. In the long term we'd like the consensus critical data structures to be just data structures, with the bare minimum necessary for their interaction with consensus.

Network-code-specific functionality does not belong in there.

**Comment by pstratem** [comment]
Alight

**Pull request closed without merging**
