### PR TITLE
contrib: drop GCC MAX_VERSION to 4.3.0 in symbol-check

### PR DESCRIPTION
**Pull request by fanquake**
Reflect the actual symbols used, i.e:

```bash
bitcoind: symbol __bswapsi2 from unsupported version GCC_4.3.0(7)
```

### CODE REVIEW

**Comment by hebasto** [comment]
> Reflect the actual symbols used, i.e:
> 
> ```shell
> bitcoind: symbol __bswapsi2 from unsupported version GCC_4.3.0(7)
> ```

Is it happening for Guix builds?

**Comment by fanquake** [comment]
> Is it happening for Guix builds?

Yes.

**Review by sedited — APPROVED** [review]
ACK ff896d25819da1c1e80591595c922fb093942645

Ran a guix build and:

```
nm -D riscv64-linux-gnu/bitcoin-ff896d25819d/bin/bitcoind | grep -i gcc                                                                                                        
...
U __bswapdi2@GCC_4.3.0
...
```
~Where is the 4.3.0 versioned symbol coming from?~
EDIT: Nvm, found it.

**Comment by fanquake** [comment]
Guix Build (aarch64):
```bash
018360e32742367f372f48529ac321758dad7f64f42538807f06b2129e0d97fd  guix-build-ff896d25819d/output/aarch64-linux-gnu/SHA256SUMS.part
8958317b7f79cb2839bed4f089c5c580be8dd3434563d2a797bb8f05905fbec5  guix-build-ff896d25819d/output/aarch64-linux-gnu/bitcoin-ff896d25819d-aarch64-linux-gnu-debug.tar.gz
71f0fd9abd4e354b87c4f670bdb17560f186f251d992f040c50239e3fbc783af  guix-build-ff896d25819d/output/aarch64-linux-gnu/bitcoin-ff896d25819d-aarch64-linux-gnu.tar.gz
f82cf4b711e3545d9a9fda3162a1df360b095a7d8d77129ce2cca65053ae01c4  guix-build-ff896d25819d/output/arm-linux-gnueabihf/SHA256SUMS.part
d2491ac2641a4b79997e0518f930ee9e149af6db0a2b4d85d481fcfc0c90b883  guix-build-ff896d25819d/output/arm-linux-gnueabihf/bitcoin-ff896d25819d-arm-linux-gnueabihf-debug.tar.gz
acd112e672a97026a1f027aeabdb9d7e4582786374002e7478df5daf01c58ae0  guix-build-ff896d25819d/output/arm-linux-gnueabihf/bitcoin-ff896d25819d-arm-linux-gnueabihf.tar.gz
71a0ab84bade2df1a3279265149ff35aef277f85e8369bfef410a97382b3492a  guix-build-ff896d25819d/output/arm64-apple-darwin/SHA256SUMS.part
271b82e04774d8269c71a02fa52211d934789482c96dd4d93cbf6baa8ef13030  guix-build-ff896d25819d/output/arm64-apple-darwin/bitcoin-ff896d25819d-arm64-apple-darwin-unsigned.tar.gz
d8b3e078071707d16a0153217115bc68d88c2a61674ed533bc234e17f83bf5a6  guix-build-ff896d25819d/output/arm64-apple-darwin/bitcoin-ff896d25819d-arm64-apple-darwin-unsigned.zip
b509cb3ae7b24d2f512b0c72469667c57492c2dd95fe55b653e8db264758720b  guix-build-ff896d25819d/output/arm64-apple-darwin/bitcoin-ff896d25819d-arm64-apple-darwin.tar.gz
fda6618bcec12eab38ff05c28f82c52b9c0a23f09d54de369da0a7363344e9b6  guix-build-ff896d25819d/output/dist-archive/bitcoin-ff896d25819d.tar.gz
37ec9906c74d2b0fb1299e7402f3d3a632ef9b106f7b81e84fef758f9a78cd30  guix-build-ff896d25819d/output/powerpc64-linux-gnu/SHA256SUMS.part
e84814ed12f3d70783bf20545152c445f3ad37a64b4ea132553dc28c38b81bf3  guix-build-ff896d25819d/output/powerpc64-linux-gnu/bitcoin-ff896d25819d-powerpc64-linux-gnu-debug.tar.gz
90fdfed8a2d2105f9aeee3985021274ffbea15065d328b81e41738910e2eae83  guix-build-ff896d25819d/output/powerpc64-linux-gnu/bitcoin-ff896d25819d-powerpc64-linux-gnu.tar.gz
b818fa901f39743cf9f497d104d40e1da618a04a1924f872d4978390d48d04b2  guix-build-ff896d25819d/output/powerpc64le-linux-gnu/SHA256SUMS.part
79af8b23080e5a3f4428ef5fd6fb93d1446b4d98f657600cc137fc076dfff465  guix-build-ff896d25819d/output/powerpc64le-linux-gnu/bitcoin-ff896d25819d-powerpc64le-linux-gnu-debug.tar.gz
61764b2fc9899741e4c9459beb442f2496c528b59c1f4fd74d90c3158a33ddbb  guix-build-ff896d25819d/output/powerpc64le-linux-gnu/bitcoin-ff896d25819d-powerpc64le-linux-gnu.tar.gz
06312ac9e5e40806459b1041521155bf922ea1d3d44885dbbf9201d60158e997  guix-build-ff896d25819d/output/riscv64-linux-gnu/SHA256SUMS.part
c755e7c21435388d4d7a6451fc5d7d17af3aaa01f2244f1a61ed207072c7fedf  guix-build-ff896d25819d/output/riscv64-linux-gnu/bitcoin-ff896d25819d-riscv64-linux-gnu-debug.tar.gz
d02f39e30313c2cd21510acc8f3ec0f96c5bfcdddaeacdba330c378eb0325e2d  guix-build-ff896d25819d/output/riscv64-linux-gnu/bitcoin-ff896d25819d-riscv64-linux-gnu.tar.gz
36e587990f45683d2a1a20635bb22dc5528c9d32a97876b4cc6d0241f56e7ce3  guix-build-ff896d25819d/output/x86_64-apple-darwin/SHA256SUMS.part
3be326ada72f671ec6f7197fd0d781fc1de7b5ed58063dccde181fe0174a1a53  guix-build-ff896d25819d/output/x86_64-apple-darwin/bitcoin-ff896d25819d-x86_64-apple-darwin-unsigned.tar.gz
ff47e7ac30ec6ec6694ef6ade243ce49bcefe7bc4b07d35919a34009487fc832  guix-build-ff896d25819d/output/x86_64-apple-darwin/bitcoin-ff896d25819d-x86_64-apple-darwin-unsigned.zip
d7ac8c9fdfce2e4fc81c30bdfe805e6f986a55544492450f39f719ef25a622b9  guix-build-ff896d25819d/output/x86_64-apple-darwin/bitcoin-ff896d25819d-x86_64-apple-darwin.tar.gz
74d434d7ec38ac67c69efebc28fa7e6360a757c6d99785206df2012c68234c2a  guix-build-ff896d25819d/output/x86_64-linux-gnu/SHA256SUMS.part
cb2536c31d2fc7f256a6ca53d8f8599002cb8ce3459197999c47f0338b71e3b1  guix-build-ff896d25819d/output/x86_64-linux-gnu/bitcoin-ff896d25819d-x86_64-linux-gnu-debug.tar.gz
11689fad4ff54ed3378ea84b9c758f65ba01ecfa0d777471396efc4ae37d7fd6  guix-build-ff896d25819d/output/x86_64-linux-gnu/bitcoin-ff896d25819d-x86_64-linux-gnu.tar.gz
fb0fff24c30d6ccce7ce73508926e608e2df9cbd002472aecc47a3ca23910f2b  guix-build-ff896d25819d/output/x86_64-w64-mingw32/SHA256SUMS.part
46aa880653d3725399653ef1a5add1a4f76c8e1b441a61af4e6e20c4a35ad77e  guix-build-ff896d25819d/output/x86_64-w64-mingw32/bitcoin-ff896d25819d-win64-debug.zip
ebd857b52ed2c9f0369a6d3adb9aa8cef80f2ddfe2c789f74d6d36fba9b846c4  guix-build-ff896d25819d/output/x86_64-w64-mingw32/bitcoin-ff896d25819d-win64-setup-unsigned.exe
062cea9250bbea14c2251e0fc696b7b1825edd239487932a24c4f802b30f4a05  guix-build-ff896d25819d/output/x86_64-w64-mingw32/bitcoin-ff896d25819d-win64-unsigned.tar.gz
a64ed417497fe5636783a115d314025a0580f96022248957271ef99c6f3bac9e  guix-build-ff896d25819d/output/x86_64-w64-mingw32/bitcoin-ff896d25819d-win64.zip
```

**Pull request merged**
