### PR TITLE
build: Update `qt` package up to 5.15.10

### PR DESCRIPTION
**Pull request by hebasto**
The Qt 5.15.10 contains at least three important for us fixes:
- https://github.com/qt/qtbase/commit/8bb90ab760310c9bc82b6ecbe068532fcb4e7822, which allows us to drop the [`dont_hardcode_x86_64.patch`](https://github.com/bitcoin/bitcoin/blob/fd8ab08558ccfb62f2d0a64d2d0d4dcefba977bc/depends/patches/qt/dont_hardcode_x86_64.patch)
- https://github.com/qt/qtbase/commit/8467beddb7239cc213ae13900fa30e3d26df5e78, which allows us to drop the [`fix_montery_include.patch`](https://github.com/bitcoin/bitcoin/blob/fd8ab08558ccfb62f2d0a64d2d0d4dcefba977bc/depends/patches/qt/fix_montery_include.patch)
- https://github.com/qt/qtbase/commit/df08a21fa4e7139d46ec68bcf264c922789c4f3a, which addresses https://github.com/bitcoin/bitcoin/pull/28349#issuecomment-1743519614

### CODE REVIEW

**Comment by fanquake** [comment]
Can you rebase this now that #28543 is merged.

**Comment by hebasto** [comment]
> Can you rebase this now that #28543 is merged.

Done.

**Comment by fanquake** [comment]
Concept ACK. Need to update doc/dependencies as well.

**Comment by hebasto** [comment]
> Need to update doc/dependencies as well.

Docs and CI have been updated.

**Comment by hebasto** [comment]
I've refreshed Guix build hashes in the PR description.

**Comment by fanquake** [comment]
Can be rebased on top of #28571.

**Comment by hebasto** [comment]
> Can be rebased on top of #28571.

Done.

**Comment by hebasto** [comment]
Guix builds:
```
x86_64
6cdacd3aa6ae6ae09645be0ad74e0788dd52836df1ba874e8dae2ddc35e6ae5c  guix-build-a05d79a48d9e/output/aarch64-linux-gnu/SHA256SUMS.part
a3da57e03d34c3733a155a7d4372e21739ca83edb3d47855370e3ac4ec34c15f  guix-build-a05d79a48d9e/output/aarch64-linux-gnu/bitcoin-a05d79a48d9e-aarch64-linux-gnu-debug.tar.gz
2db9694aa717f73d8c7aa768ac07d435672ce518509a108fa811db5c897b8481  guix-build-a05d79a48d9e/output/aarch64-linux-gnu/bitcoin-a05d79a48d9e-aarch64-linux-gnu.tar.gz
a1dfb9632354dbae82f8548f3c2996f61216e1d0e808d563b40b9774ae343c08  guix-build-a05d79a48d9e/output/arm-linux-gnueabihf/SHA256SUMS.part
359ee1f050d0022ae2c7efce2fa55f70399211e730651caf7982d7a8bd2a04c6  guix-build-a05d79a48d9e/output/arm-linux-gnueabihf/bitcoin-a05d79a48d9e-arm-linux-gnueabihf-debug.tar.gz
9c919732135f485dd502292168e4193fb2c145d8d352e3a47bfc8db07632e28a  guix-build-a05d79a48d9e/output/arm-linux-gnueabihf/bitcoin-a05d79a48d9e-arm-linux-gnueabihf.tar.gz
bd9a074d0f8a1da0a88aaca241d2a233e0b9361d845af12fc77b87e92a793770  guix-build-a05d79a48d9e/output/arm64-apple-darwin/SHA256SUMS.part
ed8d417b8ac249ace203a3f71d6cdee7e64255e0b508122eda16325a67df12c6  guix-build-a05d79a48d9e/output/arm64-apple-darwin/bitcoin-a05d79a48d9e-arm64-apple-darwin-unsigned.tar.gz
93af1969c25229fde6d7a476274a1b74abb8baf88bd3b3af084b55255aa774ea  guix-build-a05d79a48d9e/output/arm64-apple-darwin/bitcoin-a05d79a48d9e-arm64-apple-darwin-unsigned.zip
6186b637959e1440c006443bccfc348d7d2f0e52a0ef4828d5743064b4e73bfe  guix-build-a05d79a48d9e/output/arm64-apple-darwin/bitcoin-a05d79a48d9e-arm64-apple-darwin.tar.gz
2c48daee437c1f6172502505bcf3bd61a66d958f7e16c5570d4c222174a19578  guix-build-a05d79a48d9e/output/dist-archive/bitcoin-a05d79a48d9e.tar.gz
1702fadacb442cc088fbdbd7e449b37e4ad148657a23142aa94b9141f1e3d1d9  guix-build-a05d79a48d9e/output/powerpc64-linux-gnu/SHA256SUMS.part
9fab771dcf122fc5ae465b491aea3b852a20e1a067dfa7df31f35a9010bb3f83  guix-build-a05d79a48d9e/output/powerpc64-linux-gnu/bitcoin-a05d79a48d9e-powerpc64-linux-gnu-debug.tar.gz
2bef17740c8fcb4de11b83f091417236736b8aba8496bc990b19f3cf135da5d2  guix-build-a05d79a48d9e/output/powerpc64-linux-gnu/bitcoin-a05d79a48d9e-powerpc64-linux-gnu.tar.gz
00b8f0fb018c230cc1ac86039b2e9fd953aedb1308c26dd12ced8c43a5bf3268  guix-build-a05d79a48d9e/output/powerpc64le-linux-gnu/SHA256SUMS.part
177e36eda849ca7733c9a240c9521d73e40132571643303c8b4a149b8721ede6  guix-build-a05d79a48d9e/output/powerpc64le-linux-gnu/bitcoin-a05d79a48d9e-powerpc64le-linux-gnu-debug.tar.gz
923ffb15b8f56a83011ca143be59b6aaadcede74277380e4bedb3ad2558c0d28  guix-build-a05d79a48d9e/output/powerpc64le-linux-gnu/bitcoin-a05d79a48d9e-powerpc64le-linux-gnu.tar.gz
e7bc2c7d1674d264f241ee745d1ac757b7bc193a997635c27cefb2a89c6605bd  guix-build-a05d79a48d9e/output/riscv64-linux-gnu/SHA256SUMS.part
8fe39268eae9c9a336050cdc77642d777786a938f33af9ec2b0a1d83c1defa68  guix-build-a05d79a48d9e/output/riscv64-linux-gnu/bitcoin-a05d79a48d9e-riscv64-linux-gnu-debug.tar.gz
aafd7da17b6e61050d206b5847052ce31ced4d663e5df6f4dcf3421458d47677  guix-build-a05d79a48d9e/output/riscv64-linux-gnu/bitcoin-a05d79a48d9e-riscv64-linux-gnu.tar.gz
8379ab622b81f17c5566c657af81c617ee04f8b7387e19a72b7105d4eaef47c4  guix-build-a05d79a48d9e/output/x86_64-apple-darwin/SHA256SUMS.part
eceaa617fb88683262e1ddde82773c5e0fe25055d1794e3dbc2049c6566fd42e  guix-build-a05d79a48d9e/output/x86_64-apple-darwin/bitcoin-a05d79a48d9e-x86_64-apple-darwin-unsigned.tar.gz
0f5fbffe81830682b00e9e97a9ee49cb0718c11585c37e25bc5027f078a421da  guix-build-a05d79a48d9e/output/x86_64-apple-darwin/bitcoin-a05d79a48d9e-x86_64-apple-darwin-unsigned.zip
482191a7695a51d6f57c5316706661d6e78cb67bf7deb6ba3eb8635f49e575c7  guix-build-a05d79a48d9e/output/x86_64-apple-darwin/bitcoin-a05d79a48d9e-x86_64-apple-darwin.tar.gz
9c3cc6ca9590fe1bf5e93d6ba099b789de8b79c17e676df99bb32fd42828da37  guix-build-a05d79a48d9e/output/x86_64-linux-gnu/SHA256SUMS.part
b069884bca495a73d1e8c7cd547162d6cdeb88eb68849667f5eb8409388cddf6  guix-build-a05d79a48d9e/output/x86_64-linux-gnu/bitcoin-a05d79a48d9e-x86_64-linux-gnu-debug.tar.gz
87979a835da546b3b1692a32e48b52fc96f6998b7d7a12cc663b007017497a65  guix-build-a05d79a48d9e/output/x86_64-linux-gnu/bitcoin-a05d79a48d9e-x86_64-linux-gnu.tar.gz
11f9614c554aa30284fdb6beb8235c6517438450e6e832e148debbb5b33d4e48  guix-build-a05d79a48d9e/output/x86_64-w64-mingw32/SHA256SUMS.part
3df2be245b0455cac6f6e576eaac24028d5671fe5312efdd1c9441a1e2a65647  guix-build-a05d79a48d9e/output/x86_64-w64-mingw32/bitcoin-a05d79a48d9e-win64-debug.zip
6d4ce4f77ed29dcc6020cb8ac6c888624b4e39618d56f6960f9de3838f1e470f  guix-build-a05d79a48d9e/output/x86_64-w64-mingw32/bitcoin-a05d79a48d9e-win64-setup-unsigned.exe
976d86092eb122d7f468179276c396b78a5789c9cd443c1fa56390bd0d7b6e64  guix-build-a05d79a48d9e/output/x86_64-w64-mingw32/bitcoin-a05d79a48d9e-win64-unsigned.tar.gz
775b82be223af29e3b289cbf2d7bf0d74b099cb397455a1f5e1c04941d1c1ede  guix-build-a05d79a48d9e/output/x86_64-w64-mingw32/bitcoin-a05d79a48d9e-win64.zip
```

**Comment by hebasto** [comment]
@MarcoFalke 

Mind taking a look at https://cirrus-ci.com/task/5416743623983104?

Another cache issue?

**Comment by fanquake** [comment]
Guix Build (aarch64):
```bash
6cdacd3aa6ae6ae09645be0ad74e0788dd52836df1ba874e8dae2ddc35e6ae5c  guix-build-a05d79a48d9e/output/aarch64-linux-gnu/SHA256SUMS.part
a3da57e03d34c3733a155a7d4372e21739ca83edb3d47855370e3ac4ec34c15f  guix-build-a05d79a48d9e/output/aarch64-linux-gnu/bitcoin-a05d79a48d9e-aarch64-linux-gnu-debug.tar.gz
2db9694aa717f73d8c7aa768ac07d435672ce518509a108fa811db5c897b8481  guix-build-a05d79a48d9e/output/aarch64-linux-gnu/bitcoin-a05d79a48d9e-aarch64-linux-gnu.tar.gz
a1dfb9632354dbae82f8548f3c2996f61216e1d0e808d563b40b9774ae343c08  guix-build-a05d79a48d9e/output/arm-linux-gnueabihf/SHA256SUMS.part
359ee1f050d0022ae2c7efce2fa55f70399211e730651caf7982d7a8bd2a04c6  guix-build-a05d79a48d9e/output/arm-linux-gnueabihf/bitcoin-a05d79a48d9e-arm-linux-gnueabihf-debug.tar.gz
9c919732135f485dd502292168e4193fb2c145d8d352e3a47bfc8db07632e28a  guix-build-a05d79a48d9e/output/arm-linux-gnueabihf/bitcoin-a05d79a48d9e-arm-linux-gnueabihf.tar.gz
bd9a074d0f8a1da0a88aaca241d2a233e0b9361d845af12fc77b87e92a793770  guix-build-a05d79a48d9e/output/arm64-apple-darwin/SHA256SUMS.part
ed8d417b8ac249ace203a3f71d6cdee7e64255e0b508122eda16325a67df12c6  guix-build-a05d79a48d9e/output/arm64-apple-darwin/bitcoin-a05d79a48d9e-arm64-apple-darwin-unsigned.tar.gz
93af1969c25229fde6d7a476274a1b74abb8baf88bd3b3af084b55255aa774ea  guix-build-a05d79a48d9e/output/arm64-apple-darwin/bitcoin-a05d79a48d9e-arm64-apple-darwin-unsigned.zip
6186b637959e1440c006443bccfc348d7d2f0e52a0ef4828d5743064b4e73bfe  guix-build-a05d79a48d9e/output/arm64-apple-darwin/bitcoin-a05d79a48d9e-arm64-apple-darwin.tar.gz
2c48daee437c1f6172502505bcf3bd61a66d958f7e16c5570d4c222174a19578  guix-build-a05d79a48d9e/output/dist-archive/bitcoin-a05d79a48d9e.tar.gz
1702fadacb442cc088fbdbd7e449b37e4ad148657a23142aa94b9141f1e3d1d9  guix-build-a05d79a48d9e/output/powerpc64-linux-gnu/SHA256SUMS.part
9fab771dcf122fc5ae465b491aea3b852a20e1a067dfa7df31f35a9010bb3f83  guix-build-a05d79a48d9e/output/powerpc64-linux-gnu/bitcoin-a05d79a48d9e-powerpc64-linux-gnu-debug.tar.gz
2bef17740c8fcb4de11b83f091417236736b8aba8496bc990b19f3cf135da5d2  guix-build-a05d79a48d9e/output/powerpc64-linux-gnu/bitcoin-a05d79a48d9e-powerpc64-linux-gnu.tar.gz
00b8f0fb018c230cc1ac86039b2e9fd953aedb1308c26dd12ced8c43a5bf3268  guix-build-a05d79a48d9e/output/powerpc64le-linux-gnu/SHA256SUMS.part
177e36eda849ca7733c9a240c9521d73e40132571643303c8b4a149b8721ede6  guix-build-a05d79a48d9e/output/powerpc64le-linux-gnu/bitcoin-a05d79a48d9e-powerpc64le-linux-gnu-debug.tar.gz
923ffb15b8f56a83011ca143be59b6aaadcede74277380e4bedb3ad2558c0d28  guix-build-a05d79a48d9e/output/powerpc64le-linux-gnu/bitcoin-a05d79a48d9e-powerpc64le-linux-gnu.tar.gz
e7bc2c7d1674d264f241ee745d1ac757b7bc193a997635c27cefb2a89c6605bd  guix-build-a05d79a48d9e/output/riscv64-linux-gnu/SHA256SUMS.part
8fe39268eae9c9a336050cdc77642d777786a938f33af9ec2b0a1d83c1defa68  guix-build-a05d79a48d9e/output/riscv64-linux-gnu/bitcoin-a05d79a48d9e-riscv64-linux-gnu-debug.tar.gz
aafd7da17b6e61050d206b5847052ce31ced4d663e5df6f4dcf3421458d47677  guix-build-a05d79a48d9e/output/riscv64-linux-gnu/bitcoin-a05d79a48d9e-riscv64-linux-gnu.tar.gz
8379ab622b81f17c5566c657af81c617ee04f8b7387e19a72b7105d4eaef47c4  guix-build-a05d79a48d9e/output/x86_64-apple-darwin/SHA256SUMS.part
eceaa617fb88683262e1ddde82773c5e0fe25055d1794e3dbc2049c6566fd42e  guix-build-a05d79a48d9e/output/x86_64-apple-darwin/bitcoin-a05d79a48d9e-x86_64-apple-darwin-unsigned.tar.gz
0f5fbffe81830682b00e9e97a9ee49cb0718c11585c37e25bc5027f078a421da  guix-build-a05d79a48d9e/output/x86_64-apple-darwin/bitcoin-a05d79a48d9e-x86_64-apple-darwin-unsigned.zip
482191a7695a51d6f57c5316706661d6e78cb67bf7deb6ba3eb8635f49e575c7  guix-build-a05d79a48d9e/output/x86_64-apple-darwin/bitcoin-a05d79a48d9e-x86_64-apple-darwin.tar.gz
9c3cc6ca9590fe1bf5e93d6ba099b789de8b79c17e676df99bb32fd42828da37  guix-build-a05d79a48d9e/output/x86_64-linux-gnu/SHA256SUMS.part
b069884bca495a73d1e8c7cd547162d6cdeb88eb68849667f5eb8409388cddf6  guix-build-a05d79a48d9e/output/x86_64-linux-gnu/bitcoin-a05d79a48d9e-x86_64-linux-gnu-debug.tar.gz
87979a835da546b3b1692a32e48b52fc96f6998b7d7a12cc663b007017497a65  guix-build-a05d79a48d9e/output/x86_64-linux-gnu/bitcoin-a05d79a48d9e-x86_64-linux-gnu.tar.gz
11f9614c554aa30284fdb6beb8235c6517438450e6e832e148debbb5b33d4e48  guix-build-a05d79a48d9e/output/x86_64-w64-mingw32/SHA256SUMS.part
3df2be245b0455cac6f6e576eaac24028d5671fe5312efdd1c9441a1e2a65647  guix-build-a05d79a48d9e/output/x86_64-w64-mingw32/bitcoin-a05d79a48d9e-win64-debug.zip
6d4ce4f77ed29dcc6020cb8ac6c888624b4e39618d56f6960f9de3838f1e470f  guix-build-a05d79a48d9e/output/x86_64-w64-mingw32/bitcoin-a05d79a48d9e-win64-setup-unsigned.exe
976d86092eb122d7f468179276c396b78a5789c9cd443c1fa56390bd0d7b6e64  guix-build-a05d79a48d9e/output/x86_64-w64-mingw32/bitcoin-a05d79a48d9e-win64-unsigned.tar.gz
775b82be223af29e3b289cbf2d7bf0d74b099cb397455a1f5e1c04941d1c1ede  guix-build-a05d79a48d9e/output/x86_64-w64-mingw32/bitcoin-a05d79a48d9e-win64.zip
```

**Comment by fanquake** [comment]
`fix_montery_include.patch` can also be dropped: https://github.com/qt/qtbase/blob/29400a683f96867133b28299c0d0bd6bcf40df35/src/plugins/platforms/cocoa/qiosurfacegraphicsbuffer.h#L46.

**Comment by hebasto** [comment]
> `fix_montery_include.patch` can also be dropped: [qt/qtbase@`29400a6`/src/plugins/platforms/cocoa/qiosurfacegraphicsbuffer.h#L46](https://github.com/qt/qtbase/blob/29400a683f96867133b28299c0d0bd6bcf40df35/src/plugins/platforms/cocoa/qiosurfacegraphicsbuffer.h#L46).

Thanks! Updated.

**Comment by hebasto** [comment]
My Guix builds:
```
x86_64
b98b77a0f75757c862aa6f3358676bc7d97f105705d0c3ca85189c39f932b6f1  guix-build-6988a2f097e9/output/aarch64-linux-gnu/SHA256SUMS.part
4419c39a47174d4881b613d9fee9223ef63e0bf8f7fd9dd64a16479dae4dcd8f  guix-build-6988a2f097e9/output/aarch64-linux-gnu/bitcoin-6988a2f097e9-aarch64-linux-gnu-debug.tar.gz
0053525e69b81803cb0a280eb6a3e2dceec905088f25c579359f81d5b36ca48f  guix-build-6988a2f097e9/output/aarch64-linux-gnu/bitcoin-6988a2f097e9-aarch64-linux-gnu.tar.gz
92265d376cdd716478d5ef19fb62105b46d7146a20c75dd5c62cf76117058320  guix-build-6988a2f097e9/output/arm-linux-gnueabihf/SHA256SUMS.part
cceb832356d632cb2aa4978b4c74f815f760ffdda79f393a6667ba05e930e10e  guix-build-6988a2f097e9/output/arm-linux-gnueabihf/bitcoin-6988a2f097e9-arm-linux-gnueabihf-debug.tar.gz
620b31921f83c4323ae5a8565802ed66e161592adb3d9bc3bcd876500786881c  guix-build-6988a2f097e9/output/arm-linux-gnueabihf/bitcoin-6988a2f097e9-arm-linux-gnueabihf.tar.gz
1f14d9278330de48d0479558bee94fe8e8a3632f2a0a5510aeeebf35487beb81  guix-build-6988a2f097e9/output/arm64-apple-darwin/SHA256SUMS.part
1689454626745c7031ae44aee26f1f27c45e9b6de13ff52149e72a9e8ad098f8  guix-build-6988a2f097e9/output/arm64-apple-darwin/bitcoin-6988a2f097e9-arm64-apple-darwin-unsigned.tar.gz
0b023ccb3cbe6b3ef0b9dc53720e28c0b48aa98df308e420b32bc68ccc2d43a6  guix-build-6988a2f097e9/output/arm64-apple-darwin/bitcoin-6988a2f097e9-arm64-apple-darwin-unsigned.zip
ee73c9f2eee4bfd4e950a1ce5f8cede6f6ad846659efc23fa087756b49f7dea9  guix-build-6988a2f097e9/output/arm64-apple-darwin/bitcoin-6988a2f097e9-arm64-apple-darwin.tar.gz
0350c9e1cca12b6b1e0d68279d5c6edb4ad3ac3ac7a8b3f61deec556f37f5abe  guix-build-6988a2f097e9/output/dist-archive/bitcoin-6988a2f097e9.tar.gz
c5142a099e642610cbd810da69d688a5a68a890b6eb001d4fbdcf800c29eebe1  guix-build-6988a2f097e9/output/powerpc64-linux-gnu/SHA256SUMS.part
034ee84f431eae21af928701e417787afcec6b2567ec83ee331d4de8855f57d1  guix-build-6988a2f097e9/output/powerpc64-linux-gnu/bitcoin-6988a2f097e9-powerpc64-linux-gnu-debug.tar.gz
f0758d7e9f6f1cbc8c23fbfe1b04f14e48a4913e3906389a1c8910415e24cb34  guix-build-6988a2f097e9/output/powerpc64-linux-gnu/bitcoin-6988a2f097e9-powerpc64-linux-gnu.tar.gz
647e544a7a17efb8e24d2a361476c96e00792a3bdd1451c66869890ac3193348  guix-build-6988a2f097e9/output/powerpc64le-linux-gnu/SHA256SUMS.part
b740f575473c573218f480125bc5a9992f6d7c7c7e17d67d2584fe985e0f5759  guix-build-6988a2f097e9/output/powerpc64le-linux-gnu/bitcoin-6988a2f097e9-powerpc64le-linux-gnu-debug.tar.gz
1b1f440c335239f7a4d5e9d9899b43cc20be5aa21a0d537d72f289a28c722c50  guix-build-6988a2f097e9/output/powerpc64le-linux-gnu/bitcoin-6988a2f097e9-powerpc64le-linux-gnu.tar.gz
0e07119b072d4fabde799e9bc51bf493f082199baf22fc3b2924a8f0c394dc1a  guix-build-6988a2f097e9/output/riscv64-linux-gnu/SHA256SUMS.part
bdaef9aeccf41ff72edee576cec372fa84ac15fb95d25292626e00f361961997  guix-build-6988a2f097e9/output/riscv64-linux-gnu/bitcoin-6988a2f097e9-riscv64-linux-gnu-debug.tar.gz
0bc1a12344b998c2cc2c10b2d1c4adebbfc3491b1478c9b05e3845eafda8ffac  guix-build-6988a2f097e9/output/riscv64-linux-gnu/bitcoin-6988a2f097e9-riscv64-linux-gnu.tar.gz
1fb067cb40a734ca7facf6a3ac046f181863632de3fe08d5292d1df43d470d91  guix-build-6988a2f097e9/output/x86_64-apple-darwin/SHA256SUMS.part
83303ca9163cd7302a6b4bff5fdcd1046f623cb63102db6754b6631fb03c43c6  guix-build-6988a2f097e9/output/x86_64-apple-darwin/bitcoin-6988a2f097e9-x86_64-apple-darwin-unsigned.tar.gz
47740dc4b0712c17baffcdff993d615348571e95367b37406271124af46bc973  guix-build-6988a2f097e9/output/x86_64-apple-darwin/bitcoin-6988a2f097e9-x86_64-apple-darwin-unsigned.zip
eb5b9b8ba9cf13d9c34f4caf6f5a9ff13b94712d94cbeebacc2215711cc86d34  guix-build-6988a2f097e9/output/x86_64-apple-darwin/bitcoin-6988a2f097e9-x86_64-apple-darwin.tar.gz
0398f0db30df7a5efa9d515fdec73b5c88bec6de5a3c77bcfbfacbd15e874fed  guix-build-6988a2f097e9/output/x86_64-linux-gnu/SHA256SUMS.part
41707880d4999cfb94116315bea99a79253024f461f551e51c6e2681e209b472  guix-build-6988a2f097e9/output/x86_64-linux-gnu/bitcoin-6988a2f097e9-x86_64-linux-gnu-debug.tar.gz
141306d192d6c6790ade09f90961e191ec55785a5081f02a3b7d48a2e06a5859  guix-build-6988a2f097e9/output/x86_64-linux-gnu/bitcoin-6988a2f097e9-x86_64-linux-gnu.tar.gz
42b9ea7b9ce2eb4c0f9ef3793d3768ca0c512aea05cf0524a530ed55ac2493ac  guix-build-6988a2f097e9/output/x86_64-w64-mingw32/SHA256SUMS.part
c7a564e35fb1bc2beafaa5734af7e45f91824c89badc6a32fec147e50d2d2378  guix-build-6988a2f097e9/output/x86_64-w64-mingw32/bitcoin-6988a2f097e9-win64-debug.zip
8b6d12a64905f0157c75160b655ac035f85d0561555bd7c0c77854783cf55e7b  guix-build-6988a2f097e9/output/x86_64-w64-mingw32/bitcoin-6988a2f097e9-win64-setup-unsigned.exe
dd1cebaf3d48347c09ec0dfd7a830a6146cb7714a61f8206ca228d4241b0295c  guix-build-6988a2f097e9/output/x86_64-w64-mingw32/bitcoin-6988a2f097e9-win64-unsigned.tar.gz
f43f28479bc6d5d3597d5d6e1952de1bd7430cd6f8919aa4f222d0398cdf7ce9  guix-build-6988a2f097e9/output/x86_64-w64-mingw32/bitcoin-6988a2f097e9-win64.zip
```

**Comment by fanquake** [comment]
Guix Build (x86_64):
```bash
b98b77a0f75757c862aa6f3358676bc7d97f105705d0c3ca85189c39f932b6f1  guix-build-6988a2f097e9/output/aarch64-linux-gnu/SHA256SUMS.part
4419c39a47174d4881b613d9fee9223ef63e0bf8f7fd9dd64a16479dae4dcd8f  guix-build-6988a2f097e9/output/aarch64-linux-gnu/bitcoin-6988a2f097e9-aarch64-linux-gnu-debug.tar.gz
0053525e69b81803cb0a280eb6a3e2dceec905088f25c579359f81d5b36ca48f  guix-build-6988a2f097e9/output/aarch64-linux-gnu/bitcoin-6988a2f097e9-aarch64-linux-gnu.tar.gz
92265d376cdd716478d5ef19fb62105b46d7146a20c75dd5c62cf76117058320  guix-build-6988a2f097e9/output/arm-linux-gnueabihf/SHA256SUMS.part
cceb832356d632cb2aa4978b4c74f815f760ffdda79f393a6667ba05e930e10e  guix-build-6988a2f097e9/output/arm-linux-gnueabihf/bitcoin-6988a2f097e9-arm-linux-gnueabihf-debug.tar.gz
620b31921f83c4323ae5a8565802ed66e161592adb3d9bc3bcd876500786881c  guix-build-6988a2f097e9/output/arm-linux-gnueabihf/bitcoin-6988a2f097e9-arm-linux-gnueabihf.tar.gz
1f14d9278330de48d0479558bee94fe8e8a3632f2a0a5510aeeebf35487beb81  guix-build-6988a2f097e9/output/arm64-apple-darwin/SHA256SUMS.part
1689454626745c7031ae44aee26f1f27c45e9b6de13ff52149e72a9e8ad098f8  guix-build-6988a2f097e9/output/arm64-apple-darwin/bitcoin-6988a2f097e9-arm64-apple-darwin-unsigned.tar.gz
0b023ccb3cbe6b3ef0b9dc53720e28c0b48aa98df308e420b32bc68ccc2d43a6  guix-build-6988a2f097e9/output/arm64-apple-darwin/bitcoin-6988a2f097e9-arm64-apple-darwin-unsigned.zip
ee73c9f2eee4bfd4e950a1ce5f8cede6f6ad846659efc23fa087756b49f7dea9  guix-build-6988a2f097e9/output/arm64-apple-darwin/bitcoin-6988a2f097e9-arm64-apple-darwin.tar.gz
0350c9e1cca12b6b1e0d68279d5c6edb4ad3ac3ac7a8b3f61deec556f37f5abe  guix-build-6988a2f097e9/output/dist-archive/bitcoin-6988a2f097e9.tar.gz
c5142a099e642610cbd810da69d688a5a68a890b6eb001d4fbdcf800c29eebe1  guix-build-6988a2f097e9/output/powerpc64-linux-gnu/SHA256SUMS.part
034ee84f431eae21af928701e417787afcec6b2567ec83ee331d4de8855f57d1  guix-build-6988a2f097e9/output/powerpc64-linux-gnu/bitcoin-6988a2f097e9-powerpc64-linux-gnu-debug.tar.gz
f0758d7e9f6f1cbc8c23fbfe1b04f14e48a4913e3906389a1c8910415e24cb34  guix-build-6988a2f097e9/output/powerpc64-linux-gnu/bitcoin-6988a2f097e9-powerpc64-linux-gnu.tar.gz
647e544a7a17efb8e24d2a361476c96e00792a3bdd1451c66869890ac3193348  guix-build-6988a2f097e9/output/powerpc64le-linux-gnu/SHA256SUMS.part
b740f575473c573218f480125bc5a9992f6d7c7c7e17d67d2584fe985e0f5759  guix-build-6988a2f097e9/output/powerpc64le-linux-gnu/bitcoin-6988a2f097e9-powerpc64le-linux-gnu-debug.tar.gz
1b1f440c335239f7a4d5e9d9899b43cc20be5aa21a0d537d72f289a28c722c50  guix-build-6988a2f097e9/output/powerpc64le-linux-gnu/bitcoin-6988a2f097e9-powerpc64le-linux-gnu.tar.gz
0e07119b072d4fabde799e9bc51bf493f082199baf22fc3b2924a8f0c394dc1a  guix-build-6988a2f097e9/output/riscv64-linux-gnu/SHA256SUMS.part
bdaef9aeccf41ff72edee576cec372fa84ac15fb95d25292626e00f361961997  guix-build-6988a2f097e9/output/riscv64-linux-gnu/bitcoin-6988a2f097e9-riscv64-linux-gnu-debug.tar.gz
0bc1a12344b998c2cc2c10b2d1c4adebbfc3491b1478c9b05e3845eafda8ffac  guix-build-6988a2f097e9/output/riscv64-linux-gnu/bitcoin-6988a2f097e9-riscv64-linux-gnu.tar.gz
1fb067cb40a734ca7facf6a3ac046f181863632de3fe08d5292d1df43d470d91  guix-build-6988a2f097e9/output/x86_64-apple-darwin/SHA256SUMS.part
83303ca9163cd7302a6b4bff5fdcd1046f623cb63102db6754b6631fb03c43c6  guix-build-6988a2f097e9/output/x86_64-apple-darwin/bitcoin-6988a2f097e9-x86_64-apple-darwin-unsigned.tar.gz
47740dc4b0712c17baffcdff993d615348571e95367b37406271124af46bc973  guix-build-6988a2f097e9/output/x86_64-apple-darwin/bitcoin-6988a2f097e9-x86_64-apple-darwin-unsigned.zip
eb5b9b8ba9cf13d9c34f4caf6f5a9ff13b94712d94cbeebacc2215711cc86d34  guix-build-6988a2f097e9/output/x86_64-apple-darwin/bitcoin-6988a2f097e9-x86_64-apple-darwin.tar.gz
0398f0db30df7a5efa9d515fdec73b5c88bec6de5a3c77bcfbfacbd15e874fed  guix-build-6988a2f097e9/output/x86_64-linux-gnu/SHA256SUMS.part
41707880d4999cfb94116315bea99a79253024f461f551e51c6e2681e209b472  guix-build-6988a2f097e9/output/x86_64-linux-gnu/bitcoin-6988a2f097e9-x86_64-linux-gnu-debug.tar.gz
141306d192d6c6790ade09f90961e191ec55785a5081f02a3b7d48a2e06a5859  guix-build-6988a2f097e9/output/x86_64-linux-gnu/bitcoin-6988a2f097e9-x86_64-linux-gnu.tar.gz
42b9ea7b9ce2eb4c0f9ef3793d3768ca0c512aea05cf0524a530ed55ac2493ac  guix-build-6988a2f097e9/output/x86_64-w64-mingw32/SHA256SUMS.part
c7a564e35fb1bc2beafaa5734af7e45f91824c89badc6a32fec147e50d2d2378  guix-build-6988a2f097e9/output/x86_64-w64-mingw32/bitcoin-6988a2f097e9-win64-debug.zip
8b6d12a64905f0157c75160b655ac035f85d0561555bd7c0c77854783cf55e7b  guix-build-6988a2f097e9/output/x86_64-w64-mingw32/bitcoin-6988a2f097e9-win64-setup-unsigned.exe
dd1cebaf3d48347c09ec0dfd7a830a6146cb7714a61f8206ca228d4241b0295c  guix-build-6988a2f097e9/output/x86_64-w64-mingw32/bitcoin-6988a2f097e9-win64-unsigned.tar.gz
f43f28479bc6d5d3597d5d6e1952de1bd7430cd6f8919aa4f222d0398cdf7ce9  guix-build-6988a2f097e9/output/x86_64-w64-mingw32/bitcoin-6988a2f097e9-win64.zip
```

**Review by fanquake — APPROVED** [review]
ACK 6988a2f097e9af50e1b4222550b2593bfc5685ea.

**Comment by fanquake** [comment]
Looks like the error is:

> Project ERROR: No suitable Android SDK platform found. Minimum version is android-31.
make[4]: *** [Makefile:49: sub-jar-make_first-ordered] Error 3

**Comment by hebasto** [comment]
> Looks like the error is:
> 
> > Project ERROR: No suitable Android SDK platform found. Minimum version is android-31.
> > make[4]: *** [Makefile:49: sub-jar-make_first-ordered] Error 3

The diff as follows:
```diff
--- a/ci/test/00_setup_env_android.sh
+++ b/ci/test/00_setup_env_android.sh
@@ -14,8 +14,8 @@ export CI_IMAGE_NAME_TAG="docker.io/amd64/ubuntu:22.04"
 export RUN_UNIT_TESTS=false
 export RUN_FUNCTIONAL_TESTS=false
 
-export ANDROID_API_LEVEL=28
-export ANDROID_BUILD_TOOLS_VERSION=28.0.3
+export ANDROID_API_LEVEL=31
+export ANDROID_BUILD_TOOLS_VERSION=31.0.0
 export ANDROID_NDK_VERSION=23.2.8568313
 export ANDROID_TOOLS_URL=https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
 export ANDROID_HOME="${DEPENDS_DIR}/SDKs/android"
```
helps to build the `qt` package.

However, a linker error happens for the `bitcoin-qt` binary.

**Comment by hebasto** [comment]
> This breaks android?

I cannot reproduce any issue locally:
```
$ env | grep ANDROID
ANDROID_HOME=/home/hebasto/Android/Sdk
ANDROID_NDK_ROOT=/home/hebasto/Android/Sdk/ndk/23.2.8568313
$ make -j 16 -C depends HOST=aarch64-linux-android ANDROID_SDK=${ANDROID_HOME} ANDROID_NDK=${ANDROID_NDK_ROOT} ANDROID_API_LEVEL=28 ANDROID_TOOLCHAIN_BIN=${ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/linux-x86_64/bin
...
copying packages: boost libevent qt qrencode bdb sqlite miniupnpc libnatpmp zeromq
to: /home/hebasto/git/bitcoin/depends/aarch64-linux-android
make: Leaving directory '/home/hebasto/git/bitcoin/depends'
```

**Comment by hebasto** [comment]
> Did you also try with `MAKEJOBS="-j$(nproc)" FILE_ENV="./ci/test/00_setup_env_android.sh" ./ci/test_run_all.sh` ?

That is another issue. Please see #28611.

**Comment by fanquake** [comment]
Qt 5.15.11 is now out: https://github.com/qt/qtbase/commit/da6e958319e95fe564d3b30c931492dd666bfaff
https://download.qt.io/official_releases/qt/5.15/5.15.11/.

**Pull request merged**
