### PR TITLE
Trivial: little typos

### PR DESCRIPTION
**Pull request by ghost**
I wish I could merge it with #8505

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Trivial ACK b6190a7a9e36101b0e1a41c4e969db4cdb3ec1a5.
It's good to have only a few of these typo fix PRs and combine them as much as possible to not disturb other PRs.

**Comment by sipa** [comment]
Please don't change code inside the leveldb subtree directly. You could do
so through the https://github.com/bitcoin/leveldb repository (which is
sometimes synced with the src/leveldb directory), however.

**Comment by jonasschnelli** [comment]
Oh. Right. Change is on a subtree.
un-Trivial-ACK.

**Comment by mcccs** [comment]
> It's good to have only a few of these typo fix PRs and combine them as much as possible to not disturb other PRs.

Yes, 2 typos for a Pull Request isn't enough.

I'll close this Pull Request because...

> Please don't change code inside the leveldb subtree directly. You could do
so through the https://github.com/bitcoin/leveldb repository (which is
sometimes synced with the src/leveldb directory), however.

...because I'll open A Pull Request in leveldb repo.

**Pull request closed without merging**
