### PR TITLE
gui: Fix open wallet menu initialization order

### LINKED ISSUE #16230: gui: Open Wallet does not list available wallets
Using master (98958c81f5065a5de13699d46995d278ecb6709e) with Qt `5.12.3` (also tested with depends) with multiple wallets available. None are shown in the `Open Wallet ->` menu in the gui. The wallets can be loaded from the console, bitcoin-cli etc.

### PR DESCRIPTION
**Pull request by promag**
Fixes #16230, the menu must be created before connecting to aboutToShow signal.

### CODE REVIEW

**Review by ryanofsky — APPROVED** [review]
utACK 5224be5a3354e1a22ea4d7f0e40aadfccdf67064. Looks good, fix is simple and makes perfect sense after seeing explanation in https://github.com/bitcoin/bitcoin/pull/16118#issuecomment-503166407. Without this change (and since #16118), the menu pointer passed to `connect(m_open_wallet_action->menu(), ...)` is null and connecting has no effect. With this change, the menu is constructed earlier so the connect call can work.

**Comment by hebasto** [comment]
ACK 5224be5a3354e1a22ea4d7f0e40aadfccdf67064, I have tested the code on Bionic with Qt 5.12.4.

**Comment by fanquake** [comment]
@promag apologies, will review this tomorrow.

**Comment by fanquake** [comment]
@promag Thanks for following up here, and sorry for the slow review..

I've tested that this change fixes the `File -> Open Wallet -> ` behaviour (https://github.com/bitcoin/bitcoin/issues/16230):

file_open

I've also checked that with this change on top of `master` (2cbcc55ba6aea26d64eae3981b83dac04f70240f), the `File` menu is still disabled during load (#16118):

no_use_before_load

You've mentioned in some other PRs that going forward, when we are testing GUI changes we should be using `QT_FATAL_WARNINGS=1`. When I use that env variable with this PR, `bitcoin-qt` segfaults when it finishes loading:
```bash
lldb Bitcoin-Qt.app
(lldb) target create "Bitcoin-Qt.app"
Current executable set to 'Bitcoin-Qt.app' (x86_64).
(lldb) env QT_FATAL_WARNINGS=1
(lldb) run
Process 23386 launched: '/Users/michael/github/bitcoin/Bitcoin-Qt.app/Contents/MacOS/Bitcoin-Qt' (x86_64)
2019-06-23 18:21:14.578614+0800 Bitcoin-Qt[23386:57844] MessageTracer: Falling back to default whitelist
Process 23386 stopped
* thread #1, name = 'bitcoin-main', queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00007fff7e3be2c6 libsystem_kernel.dylib`__pthread_kill + 10
libsystem_kernel.dylib`__pthread_kill:
->  0x7fff7e3be2c6 <+10>: jae    0x7fff7e3be2d0            ; <+20>
    0x7fff7e3be2c8 <+12>: movq   %rax, %rdi
    0x7fff7e3be2cb <+15>: jmp    0x7fff7e3b8457            ; cerror_nocancel
    0x7fff7e3be2d0 <+20>: retq   
Target 0: (Bitcoin-Qt) stopped.
```

**Comment by hebasto** [comment]
@fanquake 
> You've mentioned in some other PRs that going forward, when we are testing GUI changes we should be using QT_FATAL_WARNINGS=1. When I use that env variable with this PR, bitcoin-qt segfaults when it finishes loading...

It seems unrelated to this PR as warnings could be produced by the internal Qt code. To verify you could launch:
```
QT_FATAL_WARNINGS=7 bitcoin-qt -debug
```

and check out warnings in the `debug.log`.

**Comment by fanquake** [comment]
@hebasto Thanks. I had just about figured that out myself, as the debug.log was always cutting off at:
```
2019-06-23T10:21:21Z UpdateTip: new best=000000000000000000b6a9e3c4aa5619a48023818df48f757f8fff650b51de85 height=494994 version=0x20000002 log2_work=87.490425 tx=272517027 date='2017-11-18T23:38:38Z' progress=0.642811 cache=4.2MiB(31387txo)
2019-06-23T10:21:21Z UpdateTip: new best=000000000000000000aa16a81a9b3b74f47f07bd6184705a3525e8325dffa54f height=494995 version=0x20000000 log2_work=87.490464 tx=272519017 date='2017-11-19T00:03:10Z' progress=0.642816 cache=5.2MiB(39744txo)
2019-06-23T10:21:21Z UpdateTip: new best=00000000000000000076be6678a2efa7793f98900ac0490863514f291e0f90f8 height=494996 version=0x20000000 log2_work=87.490502 tx=272519980 date='2017-11-19T00:03:48Z' progress=0.642818 cache=6.1MiB(47055txo)
2019-06-23T10:21:21Z GUI: Platform customization: "macosx"
```

So yes, that seems unrelated to this PR, and the changes in #16263 look good.

**Review by fanquake — APPROVED** [review]
ACK 5224be5a3354e1a22ea4d7f0e40aadfccdf67064 Testing included in a comment above. The segfaulting with QT_FATAL_WARNINGS is unrelated to this change.

**Comment by hebasto** [comment]
@fanquake 
>  I had just about figured that out myself, as the debug.log was always cutting off at:
> 
> ```
> 2019-06-23T10:21:21Z UpdateTip: new best=000000000000000000b6a9e3c4aa5619a48023818df48f757f8fff650b51de85 height=494994 version=0x20000002 log2_work=87.490425 tx=272517027 date='2017-11-18T23:38:38Z' progress=0.642811 cache=4.2MiB(31387txo)
> 2019-06-23T10:21:21Z UpdateTip: new best=000000000000000000aa16a81a9b3b74f47f07bd6184705a3525e8325dffa54f height=494995 version=0x20000000 log2_work=87.490464 tx=272519017 date='2017-11-19T00:03:10Z' progress=0.642816 cache=5.2MiB(39744txo)
> 2019-06-23T10:21:21Z UpdateTip: new best=00000000000000000076be6678a2efa7793f98900ac0490863514f291e0f90f8 height=494996 version=0x20000000 log2_work=87.490502 tx=272519980 date='2017-11-19T00:03:48Z' progress=0.642818 cache=6.1MiB(47055txo)
> 2019-06-23T10:21:21Z GUI: Platform customization: "macosx"
> ```

This case has been fixed in #16263 ;)

**Pull request merged**
