### PR TITLE
doc: Rewrite some validation docs as lock annotations

### PR DESCRIPTION
**Pull request by maflcko**
#13402 added some lock annotations in comments. This pull removes them and adds clang-readable locking annotations instead.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Currently based on #13412 to avoid having to solve a merge conflict later on.

**Comment by practicalswift** [comment]
utACK 712108e9ec2ce20a5759106a13cadf506a5f9367

Very nice!

**Comment by qmma70** [comment]
utAck

**Comment by MarcoFalke** [comment]
I tagged this with "doc", since the objdump doesn't show any difference for me. (Though, the binaries don't yield the same hash.)

**Comment by promag** [comment]
utACK fa324a8.

**Comment by sipa** [comment]
utACK fa324a8b15a4ef4138685b3427c895ec14faf3af

**Comment by laanwj** [comment]
utACK fa324a8b15a4ef4138685b3427c895ec14faf3af

**Pull request merged**
