### PR TITLE
[Qt] Simple opt-in-RBF checkbox

### PR DESCRIPTION
**Pull request by jonasschnelli**
Adds a checkbox to the Send-Coins-Pannel (next to "Add Recipient") that allows to set the according nSequence to signal BIP125 RBF.

This PR does not include a way to actually replace a transaction with the GUI. So not sure if we want this without a GUI based replacement workflow (which I'm working on but it is a bigger chunk).
But I don't want to hold back review of this PR.

Includes two refactoring commits from https://github.com/bitcoin/bitcoin/pull/7159

bildschirmfoto 2016-04-05 um 16 49 20

bildschirmfoto 2016-04-05 um 17 14 09

### CODE REVIEW

**Comment by luke-jr** [comment]
Not sure it makes sense to expose this until the wallet actually *can* do replacement...

**Comment by gmaxwell** [comment]
I don't think the confirmation window deserves red text and the bang for it. Also "replaceable" there may have the user thinking that it's more replaceable than it is... arguably it should be the non-replacable case that should get red text (because you can't update fees later).

I'm wondering if we should even have a "replaceable switch" and not, instead, have an "adaptive fee switch" (that does the compute N replacements, with locktimes in the future, and multiplicatively higher fees-- and the fee line changes to [x btc, or y,z,q,r after 3,4,5,6 blocks])

**Comment by jonasschnelli** [comment]
> Not sure it makes sense to expose this until the wallet actually can do replacement...

Right. I totally agree.
I'm working on the replacement GUI process but this can be reviewed already. The timeline to get this into 0.13 is tough.

**Comment by jonasschnelli** [comment]
> I'm wondering if we should even have a "replaceable switch" and not, instead, have an "adaptive fee switch" (that does the compute N replacements, with locktimes in the future, and multiplicatively higher fees-- and the fee line changes to [x btc, or y,z,q,r after 3,4,5,6 blocks])

Yes. This might be a solution.
I somehow was also trying to allow adding additional outputs (edit the transaction back in the sendcoins dialog).
But maybe we should just focus on increasing the fees?

**Comment by gmaxwell** [comment]
Ah. workflow for additional outputs is more complex because you need to handle also making a child transaction of the original transaction for use in case the original confirms... and if you do this multiple times there is a bit of exponential blowup in the number of versions you must compute.

**Comment by gmaxwell** [comment]
Instead of the word "replacable" perhaps the word "updatable" or "amendable" would better express what the it'll do?   doing the add output thing would be pretty interesting... though it would be nice to have a [send immediately] option which delays sending it, thus avoids having to do the extra just in case transactions if you amend with in the timeout. (and could also let you abort before it was initially set).

**Comment by kirkalx** [comment]
Hate to be that guy Jonas, but I believe "replaceab"... is the more accepted spelling, if you don't go with Greg's suggestion.

**Comment by laanwj** [comment]
Needs rebase.

**Comment by jonasschnelli** [comment]
Closing in favor of #8182 (included there).

**Pull request closed without merging**
