### PR TITLE
test: Fuzz on macOS

### PR DESCRIPTION
**Pull request by maflcko**
Any reason not to?

### CODE REVIEW

**Comment by dergoegge** [comment]
Concept ACK

Would there be any value in making this a separate task?

**Comment by brunoerg** [comment]
Concept ACK

**Comment by kevkevinpal** [comment]
Concept ACK

**Review by jamesob — APPROVED** [review]
Github ACK https://github.com/bitcoin/bitcoin/pull/27932/commits/fae7c50d201726f605938c3511dd9119efeea5ec

Adds fuzzing to a new architecture, right? Seems like an easy win?

**Review by dergoegge — APPROVED** [review]
utACK fae7c50d201726f605938c3511dd9119efeea5ec

**Pull request merged**
