### PR TITLE
[doc] release-process: Mention GitHub release and archived release notes

### PR DESCRIPTION
**Pull request by maflcko**

### CODE REVIEW

**Comment by laanwj** [comment]
utACK

**Comment by fanquake** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/9093/commits/faead5e1a92cd6b46b04f4e973336ef73c4e3a4e

**Comment by MarcoFalke** [comment]
Right now the releases (https://github.com/bitcoin/bitcoin/releases) contain the full release notes. Would anyone object if I changed them to be links only?

@sipa

**Comment by sipa** [comment]
Seems you changed them to just links already. Good.

**Pull request merged**
