### PR TITLE
wallet: Replace -zapwallettxes with zapwallettxes RPC

### PR DESCRIPTION
**Pull request by achow101**
`-zapwallettxes` is known to not work with multiwallet and is currently disabled if multiple wallets are being loaded.

This PR removes the `-zapwallettxes` startup option and replaces its functionality with a `zapwallettxes` RPC command. This RPC does almost the same thing that the startup command did in that it removes all of the transactions from the target wallet. A blockchain rescan can optionally be triggered, as well as a mempool rescan. The default is to rescan the blockchain but not the mempool.

However a large difference is that `-zapwallettxes` would prevent the mempool from being loaded (#10330) but the RPC does not clear the mempool. However this does mean that the usefulness of this is questionable as the unconfirmed transactions that are being removed from the wallet would still appear in the mempool. The original behavior can be replicated by doing `zapwallettxes` and restarting with `-persistmempool=0`.

Also tests are updated to use the new RPC.

### CODE REVIEW

**Review by maflcko — COMMENTED** [review]
Concept ACK (feel free to ignore style nit)

**Comment by instagibbs** [comment]
@laanwj brings up a point on irc that I think is good enough to bring up here: Why not just make this a wallet tool function? Might save some OP text space not worrying about mempool at all for this.

**Comment by MarcoFalke** [comment]
If you forget to start with `-persistmempool=0`, then even the wallet tool can't save you

**Comment by achow101** [comment]
From today's IRC meeting, it seemed like the consensus was to make this part of the wallet tool. This seemed fine at first, but I started looking into that a bit more deeply and I think if we want to retain all of the same behavior, it doesn't quite work. The issue is the option to keep transaction metadata. This works by keeping the removed txs in a temp variable and restoring the metadata for the txs found during the rescan. However moving this to the wallet tool means that we will lose this behavior as that metadata will be lost and the wallet tool cannot do the rescan.

**Comment by ryanofsky** [comment]
> However moving this to the wallet tool means that we will lose this behavior as that metadata will be lost and the wallet tool cannot do the rescan.

No need for metadata to be lost I think. Wallet tool could do the equivalent of current zap command line option but instead of stashing metadata in a temporary variable, stash it in temporary rows. So the offline part of zap would clear [`BESTBLOCK`](https://github.com/bitcoin/bitcoin/blob/4b705b1c98f60ab736df98d62a8d4988f61678d5/src/wallet/walletdb.cpp#L26) and rename [`TX`](https://github.com/bitcoin/bitcoin/blob/4b705b1c98f60ab736df98d62a8d4988f61678d5/src/wallet/walletdb.cpp#L43) rows to `ZAPTX` rows. Then the rescan would scavenge and clear the `ZAPTX` rows.

**Comment by achow101** [comment]
Closing in favor of #19700

**Pull request closed without merging**
