### PR TITLE
added org.bitcoin.bitcoind.plist for launchd (OS X)

### PR DESCRIPTION
**Pull request by kevcooper**
This is a launch agent for OS X to start bitcoind on user login.

### CODE REVIEW

**Comment by casey** [comment]
Tested and works on Yosemite.

**Comment by fanquake** [comment]
utACK

**Comment by paveljanik** [comment]
ACK

**Comment by paveljanik** [comment]
minor nit: please add a description where to put it (~/Library/LaunchAgents) somewhere around this file.

**Comment by jonasschnelli** [comment]
Would be nice to see some markup compatible informations/documentations in `contrib/init/README.md`.

Also for this PR we should probably mention that one can/needs to adjust the bitcoind path.
IMO the path `/usr/local/bin/bitcoind` is not recommended on OSX (brew and macports) probably use a different path.

**Comment by kevcooper** [comment]
I agree with adding more documentation and I'll work on that. I chose /usr/local/bin because it is included in the standard OS X PATH. The other default locations are /usr/bin , /bin , /usr/sbin , and /sbin which are all populated with system tools where as /usr/local/bin doesn't actually exist until you create it and add some tools to it, implying that it's purpose is for local tools added by the user. It is also where homebrew symlinks most tools to.

**Comment by kevcooper** [comment]
@jonasschnelli would adding documentation in doc/init.md be okay? It's referenced at the end of contrib/init/README.md as the location for more info.

**Comment by jonasschnelli** [comment]
Adding documentation to `docs/init.md` would make sense. Yes.

**Comment by laanwj** [comment]
Will merge this after documentation added to init.md

**Comment by paveljanik** [comment]
@kevcooper Can you please add the docs to `init.md`?

**Comment by kevcooper** [comment]
Yeah I'll get it done in the next couple days

**Comment by fanquake** [comment]
ping @kevcooper

**Comment by kevcooper** [comment]
Argh sorry school has been dominating my time but I don't have any assignments this weekend so I'll finish my commits tomorrow!!

**Comment by kevcooper** [comment]
let me know if anything needs to be added or changed.

**Comment by laanwj** [comment]
Thanks for seeing this through @kevcooper

**Pull request merged**
