### PR TITLE
Add undocumented -forcecompactdb to force LevelDB compactions

### PR DESCRIPTION
**Pull request by sipa**

### CODE REVIEW

**Comment by MarcoFalke** [comment]
The option names don't match. Pick one ;)

**Comment by sipa** [comment]
I tested it, it instantly ran a 20-minute compaction operation (spinning disk, encrypted/compressed ZFS volume). It slightly reduced the size (though it was only 2.something GB already). During the operation, the usage increased to 3.something GB and went down again.

**Comment by achow101** [comment]
ACK 8842d1a5d48bb6015030b12407ebd2060160c40f

Compaction of block index time with txindex: 1 hour 3 min
Block index had no size change, 12 GB before and after

Compaction of chainstate time: 10 min
Chainstate reduced from 5.9 GB to 2.7 GB

**Comment by TheBlueMatt** [comment]
utACK

**Review by gmaxwell — APPROVED** [review]
ACK.

2017-08-04 23:41:19 Starting database compaction of /home/gmaxwell/.bitcoin/blocks/index
2017-08-04 23:41:23 Finished database compaction of /home/gmaxwell/.bitcoin/blocks/index
2017-08-04 23:41:29 Starting database compaction of /home/gmaxwell/.bitcoin/chainstate
2017-08-04 23:45:54 Finished database compaction of /home/gmaxwell/.bitcoin/chainstate

on my slow laptop, which only had about 1GB free, now it has 4.3GB free!

Running it again when already compacted (and no new blocks processed) gave:

2017-08-04 23:55:20 Starting database compaction of /home/gmaxwell/.bitcoin/blocks/index
2017-08-04 23:55:20 Finished database compaction of /home/gmaxwell/.bitcoin/blocks/index
2017-08-04 23:55:25 Starting database compaction of /home/gmaxwell/.bitcoin/chainstate
2017-08-04 23:55:25 Finished database compaction of /home/gmaxwell/.bitcoin/chainstate


Then after syncing 174 blocks:

2017-08-05 00:04:41 Starting database compaction of /home/gmaxwell/.bitcoin/blocks/index
2017-08-05 00:04:44 Finished database compaction of /home/gmaxwell/.bitcoin/blocks/index
2017-08-05 00:04:49 Starting database compaction of /home/gmaxwell/.bitcoin/chainstate
2017-08-05 00:13:49 Finished database compaction of /home/gmaxwell/.bitcoin/chainstate

**Comment by laanwj** [comment]
utACK 8842d1a

**Pull request merged**
