### PR TITLE
wallet/refactor: refer to CWallet immutably when possible

### PR DESCRIPTION
**Pull request by kallewoof**
A lot of places refer to `CWallet*`'s as `CWallet * const`, which translates to *"an immutable pointer to a mutable `CWallet` instance"*; this is

1. often not what the author meant, especially as a lot of these places do not at all modify the wallet object, and
2. confusing, as it tends to suggest that this is a proper way to refer to a constant `CWallet` instance.

This PR changes references to wallets to `const CWallet* const` whenever immutability is expected. This should result in no behavioral changes at all, and improved compile-time error checking.

Note from irc:

> &lt;sipa&gt; sounds good to me; this is the sort of change that as long as it compiles, the behavior shouldn't change
> &lt;sipa&gt; though in general it may lead to introducing automatic copying of objects sometimes (e.g. trying to std::move a const object will work, but generally result in a copy rather than an efficient move)
> &lt;sipa&gt; CWallet objects aren't copied or moved though

### CODE REVIEW

**Comment by promag** [comment]
Concept ACK.

**Comment by MarcoFalke** [comment]
As you are changing this, my preference would be to just use `const CWallet& wallet`, which has all the same benefits as `const CWallet* const`, but also can't be `nullptr`.

**Comment by promag** [comment]
@MarcoFalke that would be a larger change. I don't mind this PR as it is and do that in other PR.

**Comment by kallewoof** [comment]
I love the idea, and started working on it, but as @promag points out, the diff becomes significantly larger. I can make a competing PR if people would like to compare the two, otherwise I think a follow-up PR to go from const CWallet* to const CWallet& might be worthwhile.

**Comment by promag** [comment]
Unless some script-fu master sorts some scripted diff.

**Comment by practicalswift** [comment]
Concept ACK

`const CWallet&` would be even better :)

**Comment by kallewoof** [comment]
I made a new branch and switched to `const CWallet&`. It builds on top of this one. I can switch to it if people find it worthwhile, but it pushes the diff from 68 to ~330 lines: https://github.com/kallewoof/bitcoin/compare/2002-const-fixes...kallewoof:2002-const-fixes-depointered (diff vs this PR)

**Comment by Empact** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/18241/commits/79facb11e92f8b61063f301027dee7c7344eb1be

Could squash into one or a few commits. I also like moving to references but I don't mind them arriving over time.

**Comment by kallewoof** [comment]
@Empact I tried to justify/analyze each change in each commit, so would prefer not to squash but if people find it hard to review, I can do so.

**Comment by promag** [comment]
d9b0ebc1da8758645f6de24a4a557511ef9b5e36 has a typo in commit message.

**Comment by kallewoof** [comment]
@promag What typo? "ivar" is a common way to refer to instance variables where I'm from.

**Comment by promag** [comment]
@kallewoof TIL!

ACK 79facb11e92f8b61063f301027dee7c7344eb1be.

**Comment by fjahr** [comment]
ACK 79facb11e92f8b61063f301027dee7c7344eb1be

**Comment by laanwj** [comment]
ACK 79facb11e92f8b61063f301027dee7c7344eb1be

**Pull request merged**
