### PR TITLE
refactor: Remove unused includes from dbwrapper.h

### PR DESCRIPTION
**Pull request by maflcko**
Unused includes are confusing, but also cause unrelated compile errors when the unused includes were to be removed.

Fix that by adding the missing includes where they are needed and then remove them where they are not needed. This is also checked by iwyu.

### CODE REVIEW

**Comment by hebasto** [comment]
Concept ACK.

**Comment by fanquake** [comment]
ACK if green tidy. Could also include
```bash
rpc/fees.cpp should remove these lines:
- #include <policy/policy.h>  // lines 9-9
- #include <util/system.h>  // lines 19-19
```

**Review by hebasto — APPROVED** [review]
ACK faf98aecf876fae0ec6d4d16b7e66f3a35253180, I have reviewed the code and it looks OK, I agree it can be merged.

**Comment by Sjors** [comment]
It indeed does look a bit confusing. But I can still build from scratch on macOS 12.4

**Review by jarolrod — APPROVED** [review]
Code Review ACK https://github.com/bitcoin/bitcoin/commit/faf98aecf876fae0ec6d4d16b7e66f3a35253180

CI is green, compiled on ubuntu 22.04 and macOS 12.4 without issue, also ran tests.

**Pull request merged**
