### PR TITLE
Includes: Cleanup includes

### PR DESCRIPTION
**Pull request by jtimon**
Separated from #5681 (as explained there) to also include #5696 and to become a single commit cleanup (after those two and maybe other preparations have been merged).

### CODE REVIEW

**Comment by jtimon** [comment]
closing for now

**Comment by jtimon** [comment]
I know this will be more interesting after #6051 and #6335 but why keep waiting?
This is good already.

**Comment by Diapolo** [comment]
@jtimon But it fails Traivs :-/.

**Comment by jtimon** [comment]
Fixed --disable-wallet build.

**Comment by jtimon** [comment]
Updated. Now also cleaning up net.h and wallet/ a little bit. Of course, adding the missing includes that are discovered as a result.

**Comment by jtimon** [comment]
Sorry, updated again.

**Comment by jtimon** [comment]
Rebased

**Comment by jgarzik** [comment]
concept ACK - however this sort of PR needs constant rebasing.  Usually better to break it up into even smaller chunks than modifying 40+ files in one go.

**Comment by jtimon** [comment]
Yes, that's why I try to avoid making these cleanups after the code moves that make them possible and not at the same time (so that the moves are less painful). But they keep accumulating...
The need for constant rebases and lack of review is why I closed it last time, and When I get bored of I will likely close it once again. 
But, yes, smaller pieces (maybe small enough to get into the trivial branch while keeping the trivial branch itself maintainable) is a good suggestion, although I would really prefer that one day it just got merged once and for all (innocent me).

**Comment by Diapolo** [comment]
I always think this is a valuable work, but doesn't get much review time or seems to trivial for getting reviewed. Perhaps the trivial branch is the better place, but IMHO the trivial cycles should be shorter also.

**Comment by jgarzik** [comment]
ACK.  Merge or close.

**Comment by jtimon** [comment]
Sorry, I didn't realized this needed a trivial rebase (a ```using namespace std``` near a newly added ```#include <boost/foreach.hpp>``` in walletmodel.cpp).

**Comment by laanwj** [comment]
ACK - but let's do this only once per major release

**Comment by jtimon** [comment]
Limiting to at most one big include cleanup per major release sounds reasonable.
I'm not sure I will ever do another one as big as this one though (and smaller ones can be made part of the relevant PR or via the trivial branch).

**Pull request merged**
