### PR TITLE
test: enhance p2p_orphan_handling

### PR DESCRIPTION
**Pull request by tdb3**
Previously, `p2p_orphan_handling` relied on checking the debug log for orphanage changes.  This updates the tests to reduce debug log checking and add checks using `tx_in_orphanage()` and `getorphantxs` introduced in #30793.

### CODE REVIEW

**Review by glozow — COMMENTED** [review]
light code review ACK 9de9c858d5aa412e1c6086e564fbe85984a4f2d5

**Review by rkrux — APPROVED** [review]
tACK 9de9c858d5aa412e1c6086e564fbe85984a4f2d5

Successful make and all functional tests. This is my preference as well to use the `getorphantxs` RPC for asserting over searching in the debug logs.

**Review by danielabrozzoni — APPROVED** [review]
ACK 9de9c858d5aa412e1c6086e564fbe85984a4f2d5

**Comment by instagibbs** [comment]
nice cleanup :+1:

**Pull request merged**
