### PR TITLE
doc: add -addrinfo to tor docs

### PR DESCRIPTION
**Pull request by jonatack**
Follow-up to #21595.

### CODE REVIEW

**Review by jarolrod — COMMENTED** [review]
Concept ACK

Add `addrinfo` to the list of options
https://github.com/bitcoin/bitcoin/blob/65f30e4c21e94b775853392b7e0de5c7fd3de488/doc/tor.md#L13
``` diff
  - in the output of the CLI `-netinfo` peer connections dashboard
+ - in the output of the CLI `-addrinfo` command
```

Then your paragraph is an explanation of this option much like lines 15&16 are for the debug log option.

**Comment by jonatack** [comment]
> Concept ACK
> 
> Add `addrinfo` to the list of options

Thanks for having a look! That list is of ways to see your local onion address, so it seems to me that this is a different topic and use context and doesn't belong in that list.

**Comment by jarolrod** [comment]
ACK 65f30e4c21e94b775853392b7e0de5c7fd3de488


> That list is of ways to see your local onion address, so it seems to me that this is a different topic and use context and doesn't belong in that list.

Right, whoops! 🥃

**Review by RiccardoMasutti — APPROVED** [review]
ACK

**Comment by practicalswift** [comment]
ACK 65f30e4c21e94b775853392b7e0de5c7fd3de488

Thanks for improving documentation!

**Review by theStack — APPROVED** [review]
LGTM 👍 
ACK 65f30e4c21e94b775853392b7e0de5c7fd3de488

**Comment by 0xB10C** [comment]
ACK 65f30e4c21e94b775853392b7e0de5c7fd3de488

**Pull request merged**
