### PR TITLE
Move message processing to new 'procmsg' module.

### PR DESCRIPTION
**Pull request by jgarzik**
Compiles and passes tests.  Could use some refinement.

### CODE REVIEW

**Comment by jtimon** [comment]
Needs rebase...
Would this be easier to merge if it only contained one commit equivalent to https://github.com/jgarzik/bitcoin/commit/78edf5cb8cf65caf38080ac57040469cc9c6957f but doing the separation directly in main and using regular functions instead of method of a new class?
They can even be static inline functions in which case the commit should produce an identical build unless I'm missing something.

**Comment by jgarzik** [comment]
Closing.  I still think this is worth merging and @jtimon seems to agree.  However it has not gained sufficient momentum to get merged for whatever reason.

As usual, it is easy to re-open a PR if this turns out to be in error, ACKs suddenly appear, etc.  Applying the "close old PRs, easy to reopen" pattern.

This code movement change is too large to continue rebasing if it is not getting merged.

**Comment by jtimon** [comment]
I really think this kind of PR opens the door to many modularity improvements. And I understand that code movements are a burden to reviewers because they need to keep up to date with them after they're merged. This is a very big move on main.cpp that everybody is touching.
But I seriously don't understand why breaking breaking an overly-nested switch into new functions of a too-large function like ProcessMessage is so difficult when (as you have proven) it can be done with minimal and review-friendly patch. I believe this can be done in a way that results in an identical gitian just prefixing all the new functions with ```static inline```, but I've never tested it. When I tried to do something similar in #5153 for EvalScript but @gmaxwell tested it and the build hash wasn't identical. I didn't add that prefix because, I thought, theoretically, the compiler should be smart enough to tell by itself, but as @sipa  explained me later, non-static (or in an anonymous namespace) things are effectively "public" to the compiler, because it doesn't have a per-file way to tell whether you're using ```extern``` somewhere else.
 
I really think we should break both EvalScript and ProcessMessage with an identical-build single commit. With an identical build you don't even need any tested ack, concept acks should be enough.
If I remember correctly @petertodd started a bounty on a python script to check whether the last commit produces an identical build hash or not. I proposed it and I didn't needed the bounty as motivation, but I never did it.This is the tutorial by @laanwj that I was going to use: https://github.com/bitcoin/bitcoin/pull/4180#issuecomment-52148271

**Comment by jgarzik** [comment]
@jtimon I agree.  It is however difficult to produce identical hashes due to minor compiler build differences such as the ones that sipa mentions.

You could probably perform some #include tricks to accomplish the first file movement step with equivalent hashes, if you keep ProcessMessage() intact.  Once the individual code blocks move to their own functions/methods, the hashes will unavoidably differ.

A line-by-line source code comparison tool would be better than a hash check.

**Comment by sipa** [comment]
I have nothing against changes like this, except I think that:
1) The resulting temporary state is worse than the start due to circular
dependencies (you don't claim it is, but:)
2) It does not help anything towards achieving the IMHO correct solution,
which is separate handler modules, like @laanwj's inv/ask transaction
handling. In fact, it interferes with it.

I would like to see moving bits of processing out to well-encapsulated
handler modules, and would have expected such changes to have happened by
now.

**Comment by jtimon** [comment]
> You could probably perform some #include tricks to accomplish the first file movement step with equivalent hashes, if you keep ProcessMessage() intact. 

I was talking about breaking the doing an equivalent to that commit without moving anything at first.

> Once the individual code blocks move to their own functions/methods, the hashes will unavoidably differ.

Shouldn't ```static inline``` be enough to in practice keep the code where it was (in ProcessMessage)? 

> A line-by-line source code comparison tool would be better than a hash check.

We already have that with git. And by not correcting the indentation at first, the commit can be very readable (specially if the new class is not introduced). But the identical hash eliminates the need of further testing, which is nice.

@sipa would you oppose to just doing the function separation in main.cpp ? That wouldn't create any circular dependencies and I believe it would help with the later modularization that you want (apart from making ProcessMessage much, much, much more readable [I don't use eclipse anymore but I believe some checkstyle plugins can segfault just by trying to analyze this function {if you first disable the typical "too long function" check, obviously}</bad joke>]).

**Comment by jtimon** [comment]
I'm talking about something along this lines: https://github.com/bitcoin/bitcoin/compare/bitcoin:master...jtimon:process-message-0.12.99 
But I now realize that for the build to be identical the return true; at the end of every new function should be introduced before that commit. That little preparation would also be trivial to review, but I'm not sure having an identical build commit would be a great benefit anymore...

**Comment by sipa** [comment]
No problem with splitting up processing.

**Comment by jtimon** [comment]
@sipa Great, I will eventually open what I started there then, although I believe it would be good to make more things like #6163 first, so that we don't have to work more later (having to add more parameters to the new functions).

Thoughts on the identical build? Could https://github.com/bitcoin/bitcoin/commit/d8e5ff46d31680c1b90abb1d04a7580a2ba48888 theoretically produce an identical build? Is it worth it (given that you need a previous commit at least for the return trues)?

**Comment by sipa** [comment]
I think that for refactors like this, you shouldn't aim for identical builds.

**Comment by jtimon** [comment]
Thanks, @sipa that's useful. But I don't see why inlining all those new static functions is a bad idea. First, is no worse than what you had, and second, the inline can be removed in a fixup! commit (to be squashed together after "testing", just like the preparation commit).

In any case, maybe is still not worth it, but what about doing something similar in consensus code, more concretely in EvalScript? To remind you, #5153 was considered too risky.

**Comment by sipa** [comment]
@jtimon I mean *forcing* the compiler to inline things - just putting the 'inline' keyword may not be enough for that (it may need compiler flags, for example), and even then, the order in the binary may end up being different.

Just saying that IMHO that's not a good use of your time, but if you think you can make the build identical, so much the better.

I'm much less concerned about changes here than in script evaluation, as getting some state/variables/processing wrong in message handling should result in immediate failure (some messages not being processed), in script evaluation it could lead to very subtle differences.

**Comment by jgarzik** [comment]
Basically the inlining doesn't produce any value.  It doesn't generate identical hashes.  Might as well make them separate functions.

**Comment by jtimon** [comment]
Thank you very much both of you: this is very helpful.
When (if nobody does it before me) I reopen the discussed subset of this PR, I will forget about the identical build. I guess I was too much worried about reusing the IsIdenticalBuild tool for  https://github.com/bitcoin/bitcoin/pull/5153#issuecomment-60885271 , but this seems definitely less risky and more of a priority. 

But, as said, I would like to see more of those ```Params()``` disappear, and some of those ```const CChainParams&``` and ```const CPolicy&``` moving up first.
The most current and finished thing I have on this will be in https://github.com/jtimon/bitcoin/commits/process-message-0.12.99 until I open it as a PR in case you want to take a look or cherry pick for finishing.

**Pull request closed without merging**
