### PR TITLE
Remove script to clean up datadirs

### PR DESCRIPTION
**Pull request by maflcko**
This reverts commit 33c055c4f1eca07bd914a5b40a21f92ad82dde9f. (#2295)

### CODE REVIEW

**Comment by Empact** [comment]
utACK fa85de9 - defunct (re 0.7/0.8) and there are no other references to this file.

Fun fact: no public full node is running 0.7. https://bitnodes.earn.com/nodes/

**Comment by practicalswift** [comment]
utACK fa85de9ff5cfa85a76026b1b6138ba1d7b54864a

**Comment by laanwj** [comment]
I also think that this script outlived its usefulness.
utACK fa85de9ff5cfa85a76026b1b6138ba1d7b54864a

**Comment by fanquake** [comment]
utACK fa85de9

**Comment by jonasschnelli** [comment]
utACK fa85de9ff5cfa85a76026b1b6138ba1d7b54864a

**Pull request merged**
