### PR TITLE
[trivial] remove no-longer-used InitError logic

### PR DESCRIPTION
**Pull request by instagibbs**
Made irrelevant in https://github.com/bitcoin/bitcoin/commit/7d80d2e3d7ecceb5a99fef357b118949f6dd8a79

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Nice, good catch.
utACK https://github.com/bitcoin/bitcoin/pull/8516/commits/edb6cf1432568bc54cd3d6a6cc260f3f265403f6

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/8516/commits/edb6cf1432568bc54cd3d6a6cc260f3f265403f6

**Comment by MarcoFalke** [comment]
utACK edb6cf1

**Comment by MarcoFalke** [comment]
Travis failure unrelated:

```
   File "/home/travis/build/bitcoin/bitcoin/qa/rpc-tests/test_framework/test_framework.py", line 148, in main
    self.run_test()
   File "/home/travis/build/bitcoin/bitcoin/build/../qa/rpc-tests/abandonconflict.py", line 146, in run_test
    assert(newbalance == balance + Decimal("20"))

**Comment by dcousens** [comment]
utACK edb6cf1

**Pull request merged**
