### PR TITLE
[22.x] Backports for 22.x

### PR DESCRIPTION
**Pull request by fanquake**
Collecting backports for the 22.1 release. Currently:
* https://github.com/bitcoin/bitcoin/pull/23045
* https://github.com/bitcoin/bitcoin/pull/23061
* https://github.com/bitcoin/bitcoin/pull/23148
* https://github.com/bitcoin/bitcoin/pull/22390
* https://github.com/bitcoin/bitcoin/pull/22820
* https://github.com/bitcoin/bitcoin/pull/22781
* https://github.com/bitcoin/bitcoin/pull/22895
* https://github.com/bitcoin/bitcoin/pull/23335
* https://github.com/bitcoin/bitcoin/pull/23333
* https://github.com/bitcoin/bitcoin/pull/22949
* https://github.com/bitcoin/bitcoin/pull/23580
* https://github.com/bitcoin/bitcoin/pull/23504
* https://github.com/bitcoin/bitcoin/pull/24239

### CODE REVIEW

**Comment by laanwj** [comment]
@katesalazar The policy is that we backport bugfixes to previous releases. The referenced issue seems a small cosmetic change that doesn't affect use of the software. So I'd say it's unnecessary. On the other hand it's also zero-risk so if other people think it's nice to have I'm also not strongly against it.

**Comment by luke-jr** [comment]
Suggest #21882 #22390 #22781 #22820 #22895

Maybe #23182 (+followup fix) #22359 #22722 #22879

**Comment by lukaszsamson** [comment]
What about [#22949?](https://github.com/bitcoin/bitcoin/pull/22949)? https://github.com/bitcoin/bitcoin/issues/23353 is assigned to 22.1 milestone

**Comment by fanquake** [comment]
> What about #22949?? #23353 is assigned to 22.1 milestone

I've added #22949, and updated the PR description to include all the changes.

**Comment by gruve-p** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/23276/commits/e02e8dcf583fff679560c914f3089ec368d78ea2

**Comment by laanwj** [comment]
List-of-commits ACK 406e3134e2e322a4791f720ff665d0692e97be9a

**Comment by prayank23** [comment]
I am not sure but this can be added: https://github.com/bitcoin/bitcoin/pull/23268

**Comment by achow101** [comment]
ACK 269553fe73b17f8acda3071a48836c66092d31d0

**Pull request merged**
