### PR TITLE
Cleanup: reduce to one GetMinimumFee call signature

### PR DESCRIPTION
**Pull request by morcos**

### CODE REVIEW

**Comment by MarcoFalke** [comment]
utACK 3edbd79a65334bbb99e11ac68532421ee2930a8a

**Comment by TheBlueMatt** [comment]
utACK 3edbd79a65334bbb99e11ac68532421ee2930a8a

**Comment by jonasschnelli** [comment]
utACK 3edbd79a65334bbb99e11ac68532421ee2930a8a

**Comment by paveljanik** [comment]
utACK 3edbd79

**Comment by sipa** [comment]
utACK 3edbd79a65334bbb99e11ac68532421ee2930a8a

**Pull request merged**
