### PR TITLE
Bugfix: Only run bitcoin-tx tests when bitcoin-tx is enabled

### PR DESCRIPTION
**Pull request by luke-jr**
Includes #5618 (which the reasons for rejecting no longer hold true)

### CODE REVIEW

**Comment by laanwj** [comment]
This change is build-system heavy, @theuni can you take a look?

**Comment by MarcoFalke** [comment]
utACK the bugfix. Didn't look at the first commit.

**Comment by theuni** [comment]
Seems a bit unnecessary, but I can't come up with a justifiable reason not to.
-0 on the concept.

The changes themselves look sane, though. utACK a2a04a5abb347d52b3ef473f7c80c3c0ffc67a2f.

**Review by ryanofsky — COMMENTED** [review]
utACK a2a04a5abb347d52b3ef473f7c80c3c0ffc67a2f both commits. I think configuration options like this are useful so you can choose the components you need in a set-and-forget config step, and then use normal `make`, `make install`, and `make check` commands.

A previous comment (https://github.com/bitcoin/bitcoin/pull/5618#issuecomment-88454412) seemed to suggest that these autoconf options are useless because you could alternately run commands like `make -C src bitcoin-tx` to selectively build components. But that's cumbersome and unreliable and also doesn't work with build actions like "make check" and "make install".

Only minor suggestion I'd make is to rephrase "Make it possible to build only one of bitcoin-cli or bitcoin-tx" commit description so it doesn't sound like these are exclusive options. When I first saw this this PR I thought it was going to disallow building both tools at the same time.

**Pull request merged**
