### PR TITLE
gui: Refactor wallet controller activities

### PR DESCRIPTION
**Pull request by promag**
Based on #15450.

This is similar to #15478 but with a better implementation. Both wallet loading and wallet creation are now asynchronous. The implementation also avoids inner event loops. It should be safe to quit the application or run `stop` RPC while the dialogs are visible.

### CODE REVIEW

**Comment by promag** [comment]
Only review last 2 commits.

**Comment by achow101** [comment]
@promag I think you should just have this PR refactor OpenWalletActivity from current master and then I will pull in the rest of the changes into #15450

**Comment by fanquake** [comment]
@promag Given that @achow101 has pulled these changes into #15450, did you want to close this?

**Comment by promag** [comment]
@fanquake yap.

**Pull request closed without merging**
