### PR TITLE
release: Update translations for v27.0 soft translation string freeze

### PR DESCRIPTION
**Pull request by hebasto**
This PR follows our [Release Process](https://github.com/bitcoin/bitcoin/blob/master/doc/release-process.md).

Required to open Transifex translations for v27.0 as it's scheduled in https://github.com/bitcoin/bitcoin/issues/29028.

The previous similar PR: https://github.com/bitcoin/bitcoin/pull/28383.

### CODE REVIEW

**Comment by hebasto** [comment]
cc @jarolrod

**Review by jarolrod — APPROVED** [review]
ACK 71927b24e5aceecd8a07cdaeb916898d45486bea

Pulled in update with the update-translations.py script and and updated the source files with `make -C src translate`, with a zero-diff

**Review by johnny9 — APPROVED** [review]
ACK 71927b24e5aceecd8a07cdaeb916898d45486bea

Reproduced by running update-translations.py and then `./configure && make -C src translate`. No diff when comparing my branch and this one.

https://github.com/hebasto/bitcoin/compare/230207-translation...johnny9:bitcoin:translation-check-27?expand=1

**Comment by hebasto** [comment]
cc @fanquake

**Review by pablomartin4btc — COMMENTED** [review]
post-merge tACK 71927b24e5aceecd8a07cdaeb916898d45486bea

I've tested it following the [translate process guide](https://github.com/bitcoin/bitcoin/blob/master/doc/translation_process.md) (which `Transifex` setup is outdated and needs to be corrected) on master and compared the resulted changes against this PR verifying there was no differences.

**Pull request merged**
