### PR TITLE
[0.13] Document reindexing changes

### PR DESCRIPTION
**Pull request by sipa**

### CODE REVIEW

**Comment by jonasschnelli** [comment]
ACK.

**Comment by paveljanik** [comment]
Nice explanation, thank you!

ACK https://github.com/bitcoin/bitcoin/pull/8465/commits/b49d963cf7c5feeb90666749171b752731f70061

**Comment by btcdrak** [comment]
ACK

**Comment by fanquake** [comment]
ACK b49d963

**Comment by laanwj** [comment]
Thanks! ACK

**Pull request merged**
