### PR TITLE
build: Only use `@` prefix for `echo` command in Makefiles

### LINKED ISSUE #18891: builds: Review use of `@`-prefixed lines in our Makefiles
From https://www.gnu.org/software/make/manual/make.html#Echoing:

> Normally `make` prints each line of the recipe before it is executed. We call this _echoing_ because it gives the appearance that you are typing the lines yourself.
> 
> When a line starts with ‘`@`’, the echoing of that line is suppressed. The ‘`@`’ is discarded before the line is passed to the shell. Typically you would use this for a command whose only effect is to print something, such as an `echo` command to indicate progress through the makefile:
> 
> ```Makefile
> @echo About to make distribution files
> ```

Since there is no way to turn off the `@`-prefix behaviour other than giving the `--just-print` flag (which puts `make` in dry-run mode and thus does not always work properly), we should make sure that we only put `@` where we mean to for debuggability's sake. **In practice, this probably means using `@`-prefix only when we're `@echo`-ing.**

-----

For example:
https://github.com/bitcoin/bitcoin/blob/fbd522721cb89ef0efea0c1bc912c00b268d1c2a/Makefile.am#L83-L85

Will silence the printing of `$(MAKENSIS) -V2 $(top_builddir)/share/setup.nsi`, which might be useful information. In fact, this whole snippet could just be:

```Makefile
	$(MAKENSIS) -V2 $(top_builddir)/share/setup.nsi
```

-----

Let me know what you think!

### PR DESCRIPTION
**Pull request by freenancial**
According to #18891:
> ... using @-prefix only when we're @echo-ing.

I searched all `\t@` in all `Makefile.am`, and replaced the `@` sign with `$(AM_V_at)` when it isn't used on an `echo` command.

---

This is my first Bitcoin PR, please let me know if I missed anything.
Thanks a lot!

### CODE REVIEW

**Comment by theuni** [comment]
@ is used to avoid printing build steps, most of which are pretty spammy. I'm not a fan of this wholesale replacement.

The makefile guidance in #18891 doesn't apply to us IMO, as automake has its own ```$(AM_V_at)``` that is preferred over ```@```. That keeps ```make``` quiet, but ```make V=1``` print steps.

So I think we should replace ```@``` with ```$(AM_V_at)``` instead.

**Comment by freenancial** [comment]
@theuni , I have updated the PR to use `$(AM_V_at)` instead, and looks like all checks have been passed.
PTAL at your convenience, thx!

**Review by hebasto — COMMENTED** [review]
[automake manual](https://www.gnu.org/software/automake/manual/automake.html#index-AM_005fV_005fat):
>  - You can use the predefined variable ... `AM_V_at` as a prefix to commands that should not output anything in silent mode. When output is to be verbose, [this variable] will expand to the empty string.
>  - You can silence a recipe unconditionally with `@`...

Since the silent rules are enabled: https://github.com/bitcoin/bitcoin/blob/65a54d684fcfa5b2cb15b09fd9be9acb56bb5f79/configure.ac#L51-L52

the using of the `AM_V_at` variable won't have any effect.

If more output is _really_ needed in the verbose mode `@` could be just removed (in justified cases).

**Comment by freenancial** [comment]
I find I don't have enough understanding to continue with this PR, so I'm closing it.
Anyone who is interested is welcome to commandeer it :)

**Comment by fanquake** [comment]
Removed "Up for grabs" given the switch to CMake.

**Pull request closed without merging**
