### PR TITLE
[tests] Fix feature_block flakiness

### PR DESCRIPTION
**Pull request by jnewbery**
feature_block.py occasionally fails on Travis. I believe this is due to
a a race condition when reconnecting to bitcoind after a subtest that
expects disconnection. If the test runs ahead and sends the INV for the
subsequent test before we've received the initial sync getheaders, then
we may end up sending two headers messages - one as a response to the
initial sync getheaders and one in response to the INV getheaders. If
both of those headers fail validation with a DoS score of 50 or higher,
then we'll unexpectedly be disconnected.

There is only one validation failure that has a DoS score bewteen 50 and
100, which is high-hash. That's why the test is failing immediately
after the "Reject a block with invalid work" subtest.

Fix is to wait for the initial getheaders from the peer before we
start populating our blockstore. That way we won't have any invalid
headers to respond to it with.

### CODE REVIEW

**Comment by jnewbery** [comment]
This test bug would disappear with #11639, since that changes the DoS disconnect/ban behaviour. However, this change is probably still useful to ensure that there's no cross-contamination between subtests.

**Comment by jnewbery** [comment]
Longer term, can we just have proper unit tests for validation please :grin:

**Review by ryanofsky — COMMENTED** [review]
utACK c1d742025caec62cf38cea1166fa6c4d0f7e207b. I'm not very familiar with this test but the explanation and fix make sense. Is a similar fix needed for the new invalid_tx test in #13003 that is now getting disconnected?

**Comment by jnewbery** [comment]
> Is a similar fix needed for the new invalid_tx test in #13003 that is now getting disconnected?

No - this is specific to invalid block headers (and more specifically - only to block headers that fail PoW validation).

**Comment by PierreRochard** [comment]
utACK c1d7420

**Pull request merged**
