### PR TITLE
Fix compilation when compiler do not support __builtin_clz*

### PR DESCRIPTION
**Pull request by 532479301**
#ifdef is not correct since defination is defined to 0 or 1. Should change to #if

### CODE REVIEW

**Comment by laanwj** [comment]
This change seems to be correct. These macros are defined like this in `src/config/bitcoin-config.h`:
```c++
/* Define to 1 if you have the declaration of `__builtin_clzl', and to 0 if
   you don't. */
#define HAVE_DECL___BUILTIN_CLZL 0
```
I'm curious why some defines in that file use `#undef/#define` and others #define XXX 0` versus `#define XXX 1`, but this is certainly the latter.
Adding @theuni as reviewer.

**Review by theuni — APPROVED** [review]
@laanwj Huh, yep, that's really annoying. The docs even point out that the behavior is wonky: https://www.gnu.org/software/autoconf/manual/autoconf-2.62/html_node/Generic-Declarations.html

I confirmed that we manage to get the others right, though to be 100% safe in the non-autoconf case (msvc builds that don't use a config.h, for example) we would need to use a construct like ```#if defined(foo) && foo```.

utACK 18307849b405f9e2067eaa8091b105838f413707

**Comment by fanquake** [comment]
utACK 1830784

**Comment by laanwj** [comment]
> we would need to use a construct like #if defined(foo) && foo.

I think using `#if X` is better in that case. At least it will fail when X is not defined, which aids in discoverability of the option.

**Pull request merged**
