### PR TITLE
fees: Remove fallbackfee default

### PR DESCRIPTION
**Pull request by maflcko**
fallbackfee is impossible to keep up-to-date by hardcoding a default value. This removes the default value and hands the responsibility to the user to determine an appropriate fallbackfee in case fee estimates are not available.

Todo:

- [ ] Properly rework the GUI when no fee estimates are available and no fallbackfee is set. (TBD: Upcoming in a later pull request)

### CODE REVIEW

**Comment by aikq35** [comment]
#11882

**Comment by laanwj** [comment]
Concept ACK. I think this is is an obviously good idea. If no fee estimate can be made, users should set a manual fee. Hardcoding a fallback fee is not realistic.

**Comment by promag** [comment]
+1

**Comment by jonasschnelli** [comment]
Concept ACK... the only bothering thing is, that regtest mode gets quite useless without passing in a -fallbackfee... and for that reason #11882 (removes default fallbackfee on mainnet only) may make more sense.

**Comment by MarcoFalke** [comment]
My understanding is that regtest mode becomes more and more useless as the number of differences to mainnet increase. If we special case that on mainnet, there'd be no way to test other than running a mainnet node.

Especially since we plan to rework the gui based on the fallback settings, it is important to be able to test in a non-mainnet setting.

**Comment by MarcoFalke** [comment]
They could specify it in their bitcoin.conf, assuming that it exists. If no bitcoin.conf exists, the only way I see is by passing it in on the command line.

**Comment by MarcoFalke** [comment]
Closing, since #11882 is now similar and there is little value in keeping both open.

**Pull request closed without merging**
