### PR TITLE
[RPC] Add transaction size to JSON output

### PR DESCRIPTION
**Pull request by Har01d**
This may be useful for blockchain explorers.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Not sure if this is really useful, because in both cases you know the size already by hexlen/2.
`decoderawtrandaction` -> you pass a hexstring so you know the size already.
`gettransaction` size = result['hex']/2.

But no strong opinion.

**Comment by Har01d** [comment]
@jonasschnelli, it's helpful when one uses REST API (`/rest/block/{blockhash}.json` or `/rest/tx/{txid}.json`), since there's no hex strings for transactions. Yes, you can use `/rest/tx/{txid}.hex` or `/rest/tx/{txid}.bin` for calculating the size, but that would be an additional query per transaction.

**Comment by jonasschnelli** [comment]
Agreed. Over RPC/JSON it can be useful.

utACK.

**Comment by dcousens** [comment]
ACK

**Comment by tulip0** [comment]
>>> import requests
    >>> requests.get("http://127.1:8332/rest/tx/6421d0b4dd71b0a823eb597cc5412b0af9f33bc456fb85c23b9ffe2eb18a7067.json").json()['size']
    120

Output is fine and the field seems to be useful.

**Comment by pstratem** [comment]
concept ACK

**Comment by laanwj** [comment]
Needs to be tested in one of the RPC tests

**Comment by sipa** [comment]
utACK, but needs an RPC test indeed.

**Comment by paveljanik** [comment]
ACK

For a test, you can use this change:
```
diff --git a/src/test/rpc_tests.cpp b/src/test/rpc_tests.cpp
index 2a486f0..79d7fec 100644
--- a/src/test/rpc_tests.cpp
+++ b/src/test/rpc_tests.cpp
@@ -74,6 +74,7 @@ BOOST_AUTO_TEST_CASE(rpc_rawparams)
     BOOST_CHECK_NO_THROW(r = CallRPC(string("decoderawtransaction ")+rawtx));
     BOOST_CHECK_EQUAL(find_value(r.get_obj(), "version").get_int(), 1);
     BOOST_CHECK_EQUAL(find_value(r.get_obj(), "locktime").get_int(), 0);
+    BOOST_CHECK_EQUAL(find_value(r.get_obj(), "size").get_int(), 193);
     BOOST_CHECK_THROW(r = CallRPC(string("decoderawtransaction ")+rawtx+" extra"), runtime_error);
 
     BOOST_CHECK_THROW(CallRPC("signrawtransaction"), runtime_error);
```

**Comment by Har01d** [comment]
Thanks @paveljanik, I've added the test.

**Comment by paveljanik** [comment]
And now, squash everything in one commit.

**Comment by Har01d** [comment]
@paveljanik, done.

**Comment by paveljanik** [comment]
perfect now, reACK

```
$ curl localhost:18332/rest/tx/00b308619c0cfae71a1375ac75353aab8fda9564be2fb29d146ce5ba7e75c687.json 2>/dev/null | json_pp
{
   "vout" : [
      {
         "n" : 0,
         "scriptPubKey" : {
            "addresses" : [
               "mhTohtQAoCemEZrMj6gYxwyRMQ5AH7DrmB"
            ],
            "type" : "pubkeyhash",
            "hex" : "76a9141557d578c41e5e5954b6ccf792eef781fce1a41188ac",
            "reqSigs" : 1,
            "asm" : "OP_DUP OP_HASH160 1557d578c41e5e5954b6ccf792eef781fce1a411 OP_EQUALVERIFY OP_CHECKSIG"
         },
         "value" : 0.88936742
      },
      {
         "n" : 1,
         "scriptPubKey" : {
            "addresses" : [
               "mn1cNcrQuHoRjGgDzQJWynca75VaVZjVXB"
            ],
            "type" : "pubkeyhash",
            "hex" : "76a914473c3029a6cd2fea28653fe0e2cfe0df44ad995a88ac",
            "reqSigs" : 1,
            "asm" : "OP_DUP OP_HASH160 473c3029a6cd2fea28653fe0e2cfe0df44ad995a OP_EQUALVERIFY OP_CHECKSIG"
         },
         "value" : 0.12
      }
   ],
   "txid" : "00b308619c0cfae71a1375ac75353aab8fda9564be2fb29d146ce5ba7e75c687",
   "version" : 1,
   "vin" : [
      {
         "vout" : 1,
         "sequence" : 4294967294,
         "txid" : "8cb542fb7930f93bcd83df0825f66e8334009fd411abed7ce4ab420d049ea6c0",
         "scriptSig" : {
            "hex" : "483045022100caa46f920976fbed34bc0b5dbeddeb3dca66360ed10dfd9898a09dbce0cd7627022019f999fa2388f5bbc48858446eb6fb281ea92f3815c5e940f3ead9396a8f442c012103c9ac0648e7f79ef5ccae4a09da0d8ea4ba17a60e5359e46de3c226e1abafa168",
            "asm" : "3045022100caa46f920976fbed34bc0b5dbeddeb3dca66360ed10dfd9898a09dbce0cd7627022019f999fa2388f5bbc48858446eb6fb281ea92f3815c5e940f3ead9396a8f442c[ALL] 03c9ac0648e7f79ef5ccae4a09da0d8ea4ba17a60e5359e46de3c226e1abafa168"
         }
      }
   ],
   "locktime" : 607711,
   "size" : 226
}
$ btctest decoderawtransaction 0100000001c0a69e040d42abe47cedab11d49f0034836ef62508df83cd3bf93079fb42b58c010000006b483045022100caa46f920976fbed34bc0b5dbeddeb3dca66360ed10dfd9898a09dbce0cd7627022019f999fa2388f5bbc48858446eb6fb281ea92f3815c5e940f3ead9396a8f442c012103c9ac0648e7f79ef5ccae4a09da0d8ea4ba17a60e5359e46de3c226e1abafa168feffffff0226114d05000000001976a9141557d578c41e5e5954b6ccf792eef781fce1a41188ac001bb700000000001976a914473c3029a6cd2fea28653fe0e2cfe0df44ad995a88acdf450900
{
  "txid": "00b308619c0cfae71a1375ac75353aab8fda9564be2fb29d146ce5ba7e75c687",
  "size": 226,
  "version": 1,
  "locktime": 607711,
  "vin": [
    {
      "txid": "8cb542fb7930f93bcd83df0825f66e8334009fd411abed7ce4ab420d049ea6c0",
      "vout": 1,
      "scriptSig": {
        "asm": "3045022100caa46f920976fbed34bc0b5dbeddeb3dca66360ed10dfd9898a09dbce0cd7627022019f999fa2388f5bbc48858446eb6fb281ea92f3815c5e940f3ead9396a8f442c[ALL] 03c9ac0648e7f79ef5ccae4a09da0d8ea4ba17a60e5359e46de3c226e1abafa168",
        "hex": "483045022100caa46f920976fbed34bc0b5dbeddeb3dca66360ed10dfd9898a09dbce0cd7627022019f999fa2388f5bbc48858446eb6fb281ea92f3815c5e940f3ead9396a8f442c012103c9ac0648e7f79ef5ccae4a09da0d8ea4ba17a60e5359e46de3c226e1abafa168"
      },
      "sequence": 4294967294
    }
  ],
  "vout": [
    {
      "value": 0.88936742,
      "n": 0,
      "scriptPubKey": {
        "asm": "OP_DUP OP_HASH160 1557d578c41e5e5954b6ccf792eef781fce1a411 OP_EQUALVERIFY OP_CHECKSIG",
        "hex": "76a9141557d578c41e5e5954b6ccf792eef781fce1a41188ac",
        "reqSigs": 1,
        "type": "pubkeyhash",
        "addresses": [
          "mhTohtQAoCemEZrMj6gYxwyRMQ5AH7DrmB"
        ]
      }
    }, 
    {
      "value": 0.12000000,
      "n": 1,
      "scriptPubKey": {
        "asm": "OP_DUP OP_HASH160 473c3029a6cd2fea28653fe0e2cfe0df44ad995a OP_EQUALVERIFY OP_CHECKSIG",
        "hex": "76a914473c3029a6cd2fea28653fe0e2cfe0df44ad995a88ac",
        "reqSigs": 1,
        "type": "pubkeyhash",
        "addresses": [
          "mn1cNcrQuHoRjGgDzQJWynca75VaVZjVXB"
        ]
      }
    }
  ]
}
$ 
```

**Comment by sipa** [comment]
ACK

**Comment by MarcoFalke** [comment]
utACK 996d311

**Comment by gmaxwell** [comment]
ACK.

**Pull request merged**
