### PR TITLE
[wallet] rpc: Drop misleading option in importprunedfunds

### PR DESCRIPTION
**Pull request by maflcko**

### CODE REVIEW

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/8581/commits/fab5ecb7719063aa72751df1258dfa4cf4a9a4a9

Good catch.

**Comment by btcdrak** [comment]
utACK fab5ecb

**Comment by jonasschnelli** [comment]
Nice!
utACK https://github.com/bitcoin/bitcoin/pull/8581/commits/fab5ecb7719063aa72751df1258dfa4cf4a9a4a9

**Comment by laanwj** [comment]
Eh yes. utACK https://github.com/bitcoin/bitcoin/pull/8581/commits/fab5ecb7719063aa72751df1258dfa4cf4a9a4a9

**Comment by sipa** [comment]
Ping @instagibbs

**Comment by instagibbs** [comment]
utACK

**Comment by MarcoFalke** [comment]
#8600 is the non breaking backport.

**Pull request merged**
