### PR TITLE
Allow the default key to be unavailable

### PR DESCRIPTION
**Pull request by sipa**
This solves the issue where no default key can be added after -salvagewallet.

### CODE REVIEW

**Comment by webwakko** [comment]
Hi, Can someone tell me how to apply this fix for the ecrypted wallet and the use of -salvagewallet? 
It seems the links a broken and I'm kinda new to this, but I have a wallet that has an urgent need to be fixed .. talking about a lot of $'s :s

**Comment by achow101** [comment]
@webwakko Please see #10952 which actually allows for the default key to not be in the wallet. That PR is currently merged into master. If you want to be able to use that behavior, just build master.

**Comment by webwakko** [comment]
Hi mate,

Thanks for getting back to me on this one, but to be honest.. this is still
a bit chinese for me...
here's the problem :

I have an alt coin wallet, that's is actualy using the core qt-wallet which
has basicly the same code behind it.. just don't know which fork it is.
Maybe you heard about the DeepOnion coin ?
I have almost 3k of onions on it, but it cannot dump a private key for the
address where these onions are located.
I'm looking to find a solution since several weeks now but without luck...
So... It would be great if you could assist me in trying to recover that
private key so i can move them to a wallet that actualy has a private key
(which I already created and own)
I'm willing to reward you for this... current value for 1 onion is about $3
or even a bit more...
If you can help me fix this problem by some simple guidance.. I'll send you
a very nice reward for this. You can count on it.

Let me know if you can assist me in this one.


With friendly regards,


Webwakko

2017-12-07 17:45 GMT+01:00 Andrew Chow <notifications@github.com>:

**Comment by sipa** [comment]
Hi @webwakko.

Sorry to hear about your issues, but this is a place to discuss development issues, and not the right place to get support. You can try bitcoin.stackexchange.com for help.

Otherwise, you'll just have to wait until the next release which is expected to have this issue fixed.

**Pull request merged**
