### PR TITLE
[WIP] p2p: Add random txn's from mempool to GETBLOCKTXN

### PR DESCRIPTION
**Pull request by davidgumberg**
As compact block completion works currently, nodes reveal precisely the subset of transactions from published blocks that they already have in their mempool when they make a `GETBLOCKTXN` request for the transactions that they are missing during compact block relay. The greatest danger here is that nodes will never request their own transactions. Given a "sufficient number" of `GETBLOCKTXN`'s from a single peer, it will become possible to identify their wallet addresses with some degree of confidence. 

Assuming that all transactions except for a node's own, have a nonzero probability of not being in the node's mempool when a block is discovered, an attacker with an infinite set of `GETBLOCKTXN`'s from a single peer that reuses a finite number of pubkeys will have 100% confidence about what addresses belong to that peer.

I am not a statistician, but I am actively trying to see if I can work out how large, and whether the "sufficient number" that gives a reasonable degree of confidence about a peer-pubkey correlation is a realistic scenario or not.

This PR prevents mempool fingerprinting by randomly adding  ~ 1 in 200 (0.5%) transactions from our mempool to our `GETBLOCKTXN`. Nodes that have less complete mempools (worse connections) will have fewer excess txn's to relay. (Nodes with 50% of block missing from mempool will tend to have about 5 excess transactions requested if there are 2000 txn's in a block) 0.5% is a number I mostly pulled out of thin air but  a maximum impact of 0.5% seems like a reasonable price to pay if the fingerprinting attack described is realistic.

### CODE REVIEW

**Comment by naumenkogs** [comment]
I agree with @sipa, with a stronger emphasis that I would probably NACK this change because the cost of this fix is too high, and the privacy gain is too low.

You may be interested in contributing to some SPV client implementation instead :) I'm curious how well they preserve privacy when they request transactions/blocks (that subset which is of interest to them specifically). E.g. whether they ask the same node to provide everything — then the node can correlate.

**Comment by MarcoFalke** [comment]
Wouldn't it be better to not add wallet transactions to the mempool if we don't want peers to query our mempool for wallet transactions?

See also https://github.com/bitcoin/bitcoin/issues/11887#issuecomment-1061946262 (and all in- and out- links in this issue)

**Comment by petertodd** [comment]
> * Just empirically, compact block relay works very well

Note that it's very easy for an adversary to change that by simply broadcasting simultaneous double-spends with the same fee. Indeed, n-way double spends broadcast to n different nodes is easy to do. So I don't think the observation that it works well right now is relevant to the adversarial case.

**Comment by MarcoFalke** [comment]
> If we don't add wallet transactions to the mempool but still relay them

Yeah, I didn't mention this, but obviously we wouldn't relay them with the mempool. Doing a one-shot (tor-only) outbound connection to fan-out the tx (one-hop dandelion) without adding it to the mempool shouldn't leave a fingerprint, other than the one left by the tor-only connection, no?

**Comment by achow101** [comment]
This PR does not seem to have conceptual support. Please leave a comment if you would like this to be reopened.

**Pull request closed without merging**
