### PR TITLE
refactor: Remove excess reserve() call for SecureString

### PR DESCRIPTION
**Pull request by knst**
This PR removes excess `reserve()` call for `SecureString`

Call `reverse` was introduced when `std::string` was used. For `std::string`, this makes sense as it prevents re-allocation when the string's size increases to prevent a situation that memory will be re-allocated and "zeroing" will clean only the latest region, but not all of them.
However, with the use of a custom allocator, this call is no longer necessary; `secure_allocator` from `support/allocators/secure.h` ensures that all re-allocation would be safely re-written and secret passphrase won't stay in memory.

### CODE REVIEW

**Comment by epiccurious** [comment]
Tested ACK. Passed the functional test runner.

**Comment by Empact** [comment]
@knst can you explain or cite a reference as to why this is no longer required? I would expect the implementation of `reserve` to be relative to the supplied allocator. Is it because size change is inexpensive with a reserved page via `LockedPoolManager`?

**Comment by knst** [comment]
@Empact 

In the original 2011 implementation, a regular std::string was used for the passphrase:
```
commit b7bcaf940d27fa8cfe89422943fbeaab7a350930
Author: Wladimir J. van der Laan <laanwj@gmail.com>
Date:   Wed Aug 24 22:07:26 2011 +0200

    Wallet encryption part 2: ask passphrase when needed, add menu options
diff --git a/src/qt/askpassphrasedialog.cpp b/src/qt/askpassphrasedialog.cpp
new file mode 100644
index 0000000000..a297513a62
--- /dev/null
+++ b/src/qt/askpassphrasedialog.cpp
....
    std::string oldpass, newpass1, newpass2;
    // TODO: mlock memory / munlock on return so they will not be swapped out, really need "mlockedstring" wrapper class to do this safely
    oldpass.reserve(MAX_PASSPHRASE_SIZE);
    newpass1.reserve(MAX_PASSPHRASE_SIZE);
    newpass2.reserve(MAX_PASSPHRASE_SIZE);
....
```

Reserving memory ensured that the memory would not be reallocated inside `std::string` when the content changed. This helped implement a crucial feature: we could zero out the memory before freeing it, ensuring that if the memory were reallocated to another object, the application would crash in a dump or something similar would happen—instead of the passphrase, there would be zeroes. To ensure that `std::string` always worked with the same memory region (allowing it to be zeroed), reserve was called.

Later on, `std::string` was replaced with `SecureString` (which is still a `std::string` but uses a special allocator). We no longer need to worry about reallocation inside `SecureString`, because all memory is allocated by a special allocator that handles all cleaning, ensuring that the secret bytes of the passphrase would never leak out of this object.
Here's safety memory cleaning in deallocation (whatever how many times std::string allocated/deallocated memory -- all memory would be "cleansed"): https://github.com/bitcoin/bitcoin/blob/master/src/support/allocators/secure.h#L39
https://github.com/bitcoin/bitcoin/blob/master/src/support/cleanse.h#L11-L13

**Summarizing: the use of reserve has been introduced years ago not for optimization purposes, but to ensure the safety of the user's passphrase. This concern is no longer necessary with the introduction of `SecureString`.**

**Comment by Empact** [comment]
Is it not worthwhile to prevent reallocation if we can, even if there is not a data disclosure risk with this allocator?

**Comment by knst** [comment]
> Is it not worthwhile to prevent reallocation if we can

@Empact I added one more commit which adds `const` and changes way of initialization of SecureString - there were not any re-allocations, but not that's enforced by const.

Except `wallet/rpc/wallet.cpp` - there's also no reallocations, objects are not changed, but code readability would be worsened if I add there `const`.

**Comment by epiccurious** [comment]
> code readability would be worsened if I add there const

Seems like adding a const here would be worthwhile. Can you elaborate on the worsened code readability?

**Comment by knst** [comment]
> Seems like adding a const here would be worthwhile. Can you elaborate on the worsened code readability?

here's it: https://github.com/bitcoin/bitcoin/pull/29364/commits/f99d92bde055efaf20c89198eb22dc3e35778d1e
not too bad actually, I added a commit.

**Pull request closed without merging**
