### PR TITLE
Switch CCoinsMap from boost to std unordered_map

### PR DESCRIPTION
**Pull request by sipa**
Rely less on Boost. There is no pressing reason for this now, but it'd be nice to have it for #10195.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
utACK e6756ad33579766cd73973b7489ef2be9427a4c4

**Comment by theuni** [comment]
utACK e6756ad33579766cd73973b7489ef2be9427a4c4

**Comment by instagibbs** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/10249/commits/e6756ad33579766cd73973b7489ef2be9427a4c4

**Review by gmaxwell — APPROVED** [review]
not very useful utACK.

**Comment by TheBlueMatt** [comment]
utACK e6756ad33579766cd73973b7489ef2be9427a4c4 die boost.

**Review by dcousens — APPROVED** [review]
utACK

**Comment by jtimon** [comment]
utACK e6756ad
Will the first commit pass individually? If not, maybe better squash.

**Comment by sipa** [comment]
@jtimon I haven't tried but I don't see why not. It just adds some things to memusage...

**Comment by sipa** [comment]
> die boost.

I always interpret such statements as German.

**Pull request merged**
