### PR TITLE
[Qt] show client user agent in debug window

### PR DESCRIPTION
**Pull request by Diapolo**
subver

I added the same indentation to the subversion as we have for the lib versions, this is just an obsolete screenshot.

### CODE REVIEW

**Comment by laanwj** [comment]
ACK

**Comment by fanquake** [comment]
Tested ACK 
screen shot 4

**Comment by laanwj** [comment]
Small nit: let's call it "User agent" instead of "Client subversion". I can see "subversion" resulting in quite funny translations, and more people will understand it by comparing it to HTTP user agent (that's also why we use option `-uacomment`)

**Comment by paveljanik** [comment]
Do we need starting and trailing `/` in Client version and User agent/Client subversion at all?

**Comment by laanwj** [comment]
IMO, yes. Don't try to be smart and just report as it is sent to the P2P network.

**Comment by paveljanik** [comment]
ACK

**Comment by MarcoFalke** [comment]
+1 for ```User Agent``` (The Peers-tab in the debug window already calls it that way)

**Comment by Diapolo** [comment]
Updated to ``User Agent``.

**Comment by jonasschnelli** [comment]
Tested ACK.
+1 for user agent.
bildschirmfoto 2015-08-07 um 14 31 29

**Pull request merged**
