### PR TITLE
test: prefer sqlite for wallet tests

### LINKED ISSUE #26511: Use descriptor wallets by default in functional tests
Since 23.0 descriptor wallet is the default wallet type.
As part of the transition it also make sense to make it default wallet type for functional tests

### PR DESCRIPTION
**Pull request by S3RK**
Fixes #26511

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Looks like you'll need to add a missing --legacy-wallet to the failing test?

**Comment by S3RK** [comment]
> Looks like you'll need to add a missing --legacy-wallet to the failing test?

Addressed this in a different (hopefully better way) by making `wallet_migration.py` pass with both wallet flags

**Comment by achow101** [comment]
ACK 17554efb6095f6ec273e52568efe1678253cb7c0

**Comment by achow101** [comment]
Github isn't detecting this as merged for some reason.

**Pull request closed without merging**
