### PR TITLE
[verify-commits] Fix gpg.sh's echoing for commits with '\n'

### PR DESCRIPTION
**Pull request by TheBlueMatt**
Should fix master travis failures

### CODE REVIEW

**Comment by practicalswift** [comment]
The `p2p-versionbits-warning.py` failure seems unrelated.

**Comment by practicalswift** [comment]
Travis now passing.

utACK a38686cea035e0d480e4ee953b8e40c7f0fa2118

**Comment by TheBlueMatt** [comment]
@practicalswift in dash, echo "\n" is equivalent to echo -e "\n" in bash. printf '%s\n' "\n" always prints \n.

**Comment by practicalswift** [comment]
@TheBlueMatt Thanks for the clarification.

utACK a38686cea035e0d480e4ee953b8e40c7f0fa2118

**Comment by sipa** [comment]
Lightly tested ACK a38686cea035e0d480e4ee953b8e40c7f0fa2118

**Pull request merged**
