### PR TITLE
[0.11] Backport BIP9 and softfork for BIP's 68,112,113

### PR DESCRIPTION
**Pull request by morcos**
(I updated this with the new deployment dates)

### CODE REVIEW

**Comment by morcos** [comment]
This was tested by running `bip68-1112-113-p2p.py` from #7648 against the binary built in this PR.

**Comment by btcdrak** [comment]
@morcos shouldnt this backport include the `bip68-1112-113-p2p.py` tests?

**Comment by morcos** [comment]
@btcdrak I thought I commented about that, but now I'm not sure where I wrote that.
Some of those python tests are quite annoying to backport as I discovered when backporting the `bip68-sequence.py`.  I didn't want to mess with whatever was going to have to be done to backport the changes to the comparison test framework itself.  But because of the way the comparison test works, its easy to start up the current version of the comparison test and run it against the backported binary, which is really what you want anyway.

**Comment by btcdrak** [comment]
OK. I tested the backport by compiling then switching to `master` and running the `bip68-1112-113-p2p.py` and `bip9-softforks.py` tests. All checks out.

ACK afb99c6

**Comment by NicolasDorier** [comment]
Not sure if big deal but no Lockpoint ? (982670c333aff6d5660c18ed00931df764733529)

**Comment by NicolasDorier** [comment]
ACK afb99c68c538cb045071f6ebe0dd2b69ad82656f

**Comment by btcdrak** [comment]
@NicolasDorier not for `0.11`. iirc, lockpoints were introduced to restore the speed improvements to CNB() that were introduced in 0.12.

**Comment by sdaftuar** [comment]
ACK.  Reviewed each backported commit.

Also, if anyone else is trying to verify that `bip68-112-113-p2p.py` from master passes when run against this 0.11 binary, note that after #7751 the RPC tests will encode decimal values as strings, which can fail when run against an 0.11 node (it wasn't until 0.12 that `AmountFromValue()` will accept strings).  However, after reverting d7b80b54fbb73acc92ddee84697ac4cc10d4d336, the test from master passes.

**Comment by afk11** [comment]
ACK afb99c6 - verified using sdaftuars method

**Comment by morcos** [comment]
Closing due to lack of interest in another 0.11 release.
Seems ok not to backport CSV to 0.11.
I can reopen if that changes for some reason.

**Comment by luke-jr** [comment]
It would be a serious problem if CSV were to activate without a 0.11 release. This should just wait for the fixes in #7935

**Comment by jtimon** [comment]
If it gets the review, I don't see any reason not to release another 0.11. I mean, if people want to code it back to 0.8 (I think that's highly unlikely), I don't see the problem. Maybe just clearly warn users that they shouldn't expect further maintenance for 0.11 (I believe we already say "only expect the last 2 versions to be maintained" somewhere anyway).

**Pull request closed without merging**
