### PR TITLE
[Qt] Add option to increase/decrease font size in the console window

### PR DESCRIPTION
**Pull request by jonasschnelli**
Allows to increase/decrease the console font size.
Font size will be persisted over `QSettings` (survives a restart).
Default size is unified over all platform.
Rearranged the "clear icon" and the ">" (shell prompt).

Possible future extension: allow switching between system default- and monospace-font.

bildschirmfoto 2016-01-22 um 18 00 26

### CODE REVIEW

**Comment by paveljanik** [comment]
Doesn't link here:
```
Undefined symbols for architecture x86_64:
  "qInitResources_bitcoin()", referenced from:
      _main in qt_bitcoin_qt-bitcoin.o
```

**Comment by paveljanik** [comment]
While compiling:
```
qt/forms/debugwindow.ui: Warning: The name 'horizontalLayout' (QHBoxLayout) is already in use, defaulting to 'horizontalLayout1'.
```

**Comment by jonasschnelli** [comment]
@paveljanik: Thanks!
Fixed the "already in use" warning and added the missing icon (travis should be happy now).

**Comment by paveljanik** [comment]
Works OK here.

Nits: the warning above. The tooltips contain Caps Text (Decrease *F*ont *S*ize) - compare with Clear *c*onsole.

**Comment by paveljanik** [comment]
@jonasschnelli IIRC icons were OK on your side - this was my local issue :-)

**Comment by laanwj** [comment]
Concept ACK, nice, this should end the complaints about the font size.

**Comment by paveljanik** [comment]
Concept ACK.

**Comment by achow101** [comment]
Tested ACK 3a3a927

Although can it be done so that it doesn't jump back to the top of the window? It requires that you have to scroll all the way down if the size is changed when there is a lot of text there.

**Comment by jonasschnelli** [comment]
Added another commit.
Now the scroll-list keeps the vertical position (percentage) after changing the font size.

Would be nice if someone could re-test.

**Comment by achow101** [comment]
Tested re-ACK 56c9e66

**Comment by paveljanik** [comment]
Fontsizes are OK, vertical scrollbar OK. But I do not like the cursor change (but maybe this is because I'm too old to remember real cursors ;-).

**Comment by jonasschnelli** [comment]
agree with @paveljanik: (re)added a Icon that indicates the promot line. Removed the placeholder text in the input field itself.
Also added copyright attributions.

**Comment by paveljanik** [comment]
The new icon is good :-))

**Comment by paveljanik** [comment]
There is "Decrease font size" tooltip over the new prompt icon (probably cut&paste issue):

screen shot 2016-01-24 at 10 27 05

**Comment by jonasschnelli** [comment]
Fixed the wrong tooltip on the prompt icon.
@paveljanik: mind doing a final re-test?

**Comment by paveljanik** [comment]
ACK https://github.com/jonasschnelli/bitcoin/commit/43abb02aa20bd32795478236b20b45d3b4087138

Perfect now :-)

**Comment by MarcoFalke** [comment]
Awesome!
Post merge Tested ACK

**Pull request merged**
