### PR TITLE
msvc: Compile `test\fuzz\bitdeque.cpp`

### PR DESCRIPTION
**Pull request by hebasto**
This PR resolves one point from the https://github.com/bitcoin/bitcoin/pull/29774#issuecomment-2028808614:
> What is the issue with the bitdeque... ?

### CODE REVIEW

**Comment by hebasto** [comment]
cc @sipa

**Review by dergoegge — APPROVED** [review]
utACK 774359b4a96d2724dc70f900cb71e084a77164da

**Comment by achow101** [comment]
ACK 774359b4a96d2724dc70f900cb71e084a77164da

Tested on windows, the bitdeque fuzz target is indeed now available.

**Comment by hebasto** [comment]
Ported to the CMake-based build system in https://github.com/hebasto/bitcoin/pull/182.

**Pull request merged**
