### PR TITLE
doc: update SECURITY.md inline with recent changes to bitcoincore.org

### PR DESCRIPTION
**Pull request by fanquake**
See https://github.com/bitcoin-core/bitcoincore.org/pull/809 and https://github.com/bitcoin-core/bitcoincore.org/pull/819 and https://bitcoincore.org/en/contact/.

### CODE REVIEW

**Comment by katesalazar** [comment]
Concept ACK, seems to match https://github.com/bitcoin-core/bitcoincore.org/pull/809/commits/fcb9e23a99723e395b8bb5c11c60ad62e8e63c82.

**Review by kristapsk — APPROVED** [review]
ACK e7c0d506d50d359c47b2d2b2d19c9c0b3350dea5, checked that fingerprint matches.

**Comment by laanwj** [comment]
ACK e7c0d506d50d359c47b2d2b2d19c9c0b3350dea5, checked that fingerprint matches

**Review by Zero-1729 — COMMENTED** [review]
ACK e7c0d506d50d359c47b2d2b2d19c9c0b3350dea5, fingerprint matches.

**Pull request merged**
