### PR TITLE
doc: Fix spelling errors identified by codespell in comments

### PR DESCRIPTION
**Pull request by Empact**
From the output [here](https://cirrus-ci.com/task/5275612980969472?logs=lint#L849):
```
src/qt/test/addressbooktests.cpp:185: wilcard ==> wildcard
src/qt/test/addressbooktests.cpp:191: wilcard ==> wildcard
src/test/miniscript_tests.cpp:227: nd ==> and, 2nd
src/test/versionbits_tests.cpp:260: everytime ==> every time
src/util/time.h:89: precicion ==> precision
src/util/time.h:90: precicion ==> precision
^ Warning: codespell identified likely spelling errors. Any false positives? Add them to the list of ignored words in test/lint/spelling.ignore-words.txt
```

~~I left the 'nd' in miniscript_tests as-is, as it's valid miniscript,
and I'm wary of whitelisting it.~~

### CODE REVIEW

**Review by jonatack — COMMENTED** [review]
A couple more minor fixups that can be squashed in here, for your consideration:

```diff
diff --git a/doc/fuzzing.md b/doc/fuzzing.md
index 9abfbc9213..7a2191f859 100644
--- a/doc/fuzzing.md
+++ b/doc/fuzzing.md
@@ -105,7 +105,7 @@ Fuzzing on a harness compiled with `--with-sanitizers=address,fuzzer,undefined` 
 ## Reproduce a fuzzer crash reported by the CI
 
-- `cd` into the `qa-assets` directory and update it with `git pull qa-assets`
+- `cd` into the `qa-assets` directory and update it with `git pull`
diff --git a/src/bench/bench.cpp b/src/bench/bench.cpp
index d26b52410c..26975bb59d 100644
--- a/src/bench/bench.cpp
+++ b/src/bench/bench.cpp
@@ -58,7 +58,7 @@ void benchmark::BenchRunner::RunAll(const Args& args)
     if (args.sanity_check) {
-        std::cout << "Running with --sanity check option, benchmark results will be useless." << std::endl;
+        std::cout << "Running with --sanity-check option, benchmark results will be useless." << std::endl;
 ```

Seems ok to add "nd" to `test/lint/spelling.ignore-words.txt`.

**Comment by Empact** [comment]
@jonatack picked up the latter fixup, added nd to the ignore list.

**Review by dunxen — APPROVED** [review]
ACK f565b28

Meta nit: Spelling in commit message/PR title :smile: :
s/coments/comments

**Comment by jonatack** [comment]
> ~I left the 'nd' in miniscript_tests as-is, as it's valid miniscript, and I'm wary of whitelisting it.~

Note to contributors, strikethrough formatting in the PR description doesn't seem to translate very well in the merge commit. Probably best to just remove it.

```
      ~~I left the 'nd' in miniscript_tests as-is, as it's valid miniscript,
      and I'm wary of whitelisting it.~~
```

**Review by onyea — COMMENTED** [review]
Send to my wallet

**Pull request merged**
