### PR TITLE
doc/release-process: Restore and update PPA note

### PR DESCRIPTION
**Pull request by luke-jr**
For some reason #18125 removed the note instead of updating it...

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Instead of adding more compile paths and configurations, whose resulting binaries need to be tested, I'd prefer if the ppa was updated to just download the already-built and tested release binary.

See also https://github.com/bitcoin-core/packaging/tree/master/debian

**Comment by MarcoFalke** [comment]
And it probably makes sense to keep the current name tag of `bitcoin/bitcoin`, if we decide they are maintained again.

**Comment by luke-jr** [comment]
The gitian binaries are static-built with stock libraries, not ideal for actual real-world usage.

The PPAs build natively for their target OS.

This PPA was never not-maintained. If we want to move it back to `bitcoin/bitcoin`, @TheBlueMatt will need to set someone up with access to it...

**Comment by fanquake** [comment]
NACK. 

I didn't link to anything else, because we wouldn't link to anything other than `~bitcoin/+archive/ubuntu/bitcoin`. If you want to get access from Matt, that's up to you, however I don't think we need to link to your PPA in the interim.

In any case, I think a note to remind you to build anything is a bit redundant. I'm sure you are aware when new versions are tagged.

**Comment by luke-jr** [comment]
> I didn't link to anything else, because we wouldn't link to anything other than ~bitcoin/+archive/ubuntu/bitcoin. If you want to get access from Matt, that's up to you, however I don't think we need to link to your PPA in the interim.

That's absurd. What reason could you possibly justify this with?

**Comment by MarcoFalke** [comment]
Existing links use bitcoin/bitcoin, and if we decide that the ppa is supported again, we should not break those links unless necessary

**Comment by MarcoFalke** [comment]
> The gitian binaries are static-built with stock libraries, not ideal for actual real-world usage.

If someone really needs to depend on the OS libs, they might be better off typing `make` locally instead of asking us to do it. I don't think we need to support every single little-used edge case in our releases

**Comment by luke-jr** [comment]
Support: The PPA remains supported. It's not a matter of "again".

Naming: I thought we were generally trying to move away from using the name "bitcoin"...

> If someone really needs to depend on the OS libs, they might be better off typing make locally instead of asking us to do it. I don't think we need to support every single little-used edge case in our releases

We don't build the PPA. Their OS vendor, Canonical, is doing that.

PPAs aren't a "little-used edge case", they are a common, standard way of distributing native packages for Ubuntu.

**Comment by sipa** [comment]
I think there is a good argument to be had that the PPA should be supported - better integration with native libraries is one of them. Some others were brought up in #17912. 

However, it takes a pretty crazy stretch of imagination to claim they're still supported right now, when https://launchpad.net/~bitcoin/+archive/ubuntu/bitcoin literally says "NOT MAINTAINED (for new versions of Ubuntu), PLEASE USE THE SNAP INSTEAD". There is a difference between someone maintaining a PPA personally, and the project deciding to support one.

**Comment by luke-jr** [comment]
I am maintaining the PPA now in the exact same way that Matt used to...

**Comment by MarcoFalke** [comment]
Regardless of my previous points, I'd also prefer if the PPA source code (debian dir) is publicly maintained in a git repo. We set up https://github.com/bitcoin-core/packaging/tree/master/debian for exactly this purpose, but it has seen no commits for more than two years. At a minimum, it is required to bump the version. So clearly that is unmaintained.

The canonical servers should then be set up to pull from https://github.com/bitcoin-core/packaging/tree/master/debian.

**Comment by luke-jr** [comment]
Actually, I use the very debian dir from that repo. Bumping the version is automated at deploy-time. I should probably commit the gitian YML that does it all...

PPAs don't pull; they are push-based.

**Comment by luke-jr** [comment]
See also: https://github.com/bitcoin-core/packaging/pull/35

**Comment by TheBlueMatt** [comment]
I dont think it makes sense to use a PPA for future builds unless its a never-updated package that just checks gitian sigs/the release PGP key's signature and updates as needed. The whole point of retiring the PPA is it had problems all the time and didn't make sense to use when we have better downloads.

**Comment by luke-jr** [comment]
Gitian binaries are not better.

**Comment by laanwj** [comment]
I agree it's better to have a single, deterministic, auditable source of binaries, and gitian has this role at the moment.

But FWIW I'm fine with adding you to the CC list for new releases/RCs in the release process.

**Comment by sipa** [comment]
When updating my Ubuntu install (to 20.4 Focal Fossa), I got a notice that chromium-browser was only going to be distributed as snap anymore, and that updating the package would automatically install the snap instead. If possible we may want to do something similar for our PPA (at least until there is another PPA that we're comfortable with).

**Comment by fanquake** [comment]
Going to close this. There certainly isn't any agreement that the project is re-supporting a PPA, particularly one other than `~bitcoin/+archive/ubuntu/bitcoin`. In any case, I'm certain Luke is well aware when new releases of Bitcoin Core are published, so I don't think we need a note to ping him in this document.

**Pull request closed without merging**
