### PR TITLE
Consensus: Remove unused dependencies

### PR DESCRIPTION
**Pull request by shmulim**

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Is this a complete fix for all files in the repository? Also, steps to reproduce would be nice. Did you use `iwyu`?

**Comment by shmulim** [comment]
This pertains only to `params.h`, and does not represent a comprehensive check ​for the possibility of other unused dependencies. No, I did not run `iwyu`, only code-review.

**Comment by MarcoFalke** [comment]
Tend to NACK in that case. Otherwise this will generate a flood of pull requests for each affected file. This probably would also need a travis check.

**Comment by fanquake** [comment]
I agree with @MarcoFalke . Refactoring like this can't be done one file at a time, as it's noisy, and will result in hundreds of PRs. It's also hard to do one large (hundreds of files at once) PR, as it will mean rebasing everything else. 
Also, as long as duplicate/un-needed includes checks aren't enforced before anything is merged, these will continually creep into the code.

**Pull request closed without merging**
