### PR TITLE
Blockchain is one word

### PR DESCRIPTION
**Pull request by sandakersmann**
Blockchain was added to Oxford Dictionaries Online in August 2015.

http://www.coindesk.com/oxford-dictionaries-definitions-blockchain-miner/

### CODE REVIEW

**Comment by fanquake** [comment]
Previous pulls for the same change are #5242 & #5248.

**Comment by maaku** [comment]
NACK. Please there's no reason to cause rebase hell over a spelling issue. Would be more accepting if it wasn't changing 97 lines across 48 files.

**Comment by MarcoFalke** [comment]
NACK. I don't like the idea to be the first ones to impose Oxford Dictionary's view onto developers [et al. (relevant xkcd)](https://xkcd.com/978/). Unless there is a consistent trend observed across publications and online resources, we should just leave it as is and fix it when it's more clear what to use.

**Comment by rebroad** [comment]
NACK. "block" and "chain" are also in the dictionary.

**Comment by laanwj** [comment]
Consensus is clear, closing

**Pull request closed without merging**
