### PR TITLE
[0.20] Backports

### PR DESCRIPTION
**Pull request by fanquake**
Currently backports the following to the 0.20 branch:
* #18700 - Fix locking on WSL using flock instead of fcntl
* #18982 - wallet: Minimal fix to restore conflicted transaction notifications
* #19059 - gui: update Qt base translations for macOS release
* #19152 - build: improve build OS configure output
* #19194 -  util: Don't reference errno when pthread fails.
* #19215 - psbt: Include and allow both non_witness_utxo and witness_utxo for segwit inputs
* #19219 - Replace automatic bans with discouragement filter
* #19300 - wallet: Handle concurrent wallet loading

### CODE REVIEW

**Comment by promag** [comment]
#19300 was merged.

**Comment by fanquake** [comment]
I've added #19215 and #19300 cc @achow101 & @promag if you want to check those. I've also added a commit to remove the FreeBSD job from the Cirrus config, as that seemed to be continually failing in the "installing packages" phase (it has also been removed from master).

**Comment by fanquake** [comment]
https://github.com/bitcoin/bitcoin/pull/19219 has been added. The second commit (https://github.com/bitcoin/bitcoin/pull/19224/commits/2b79ac740622218a52e2cf3ae1755dd3a8d4847a) isn't a  necessity, so might end up being dropped. 

The test failure is in AppVeyor; looks like a Boost include issue. Maybe a cache needs clearing / packages need re-installing.

**Comment by laanwj** [comment]
ACK 2b79ac740622218a52e2cf3ae1755dd3a8d4847a
Reviewed the code changes and metadata and checked here and there whether they match the original changes.

**Comment by MarcoFalke** [comment]
See #19440 for the appveyor fix

**Comment by laanwj** [comment]
Thanks, so we might want to backport  #19444 as well, if we care about AppVeyor passing on the branch (I guess so).

**Comment by amitiuttarwar** [comment]
ACK 04773480575ac79f238ac5764247dddd0cae5051 2b79ac740622218a52e2cf3ae1755dd3a8d4847a by comparing to original changes, double checking the diff

**Comment by sipa** [comment]
utACK 2b79ac740622218a52e2cf3ae1755dd3a8d4847a

I've verified 04773480575ac79f238ac5764247dddd0cae5051 by rebasing myself. I've done cursory code re-review of the other commits.

**Pull request merged**
