### PR TITLE
test: script_error checking in script_invalid tests

### LINKED ISSUE #7513: Verify script errors as part of tx_invalid tests
Check the returned script_error.

This is low priority as the specific error is not part of consensus, but it could avoid unclear reporting issues such as #6862.

### PR DESCRIPTION
**Pull request by laanwj**
Check the returned script_error. Add expected script_error for generated as well as custom tests.

The specific error is not part of consensus, however it could avoid unclear reporting issues such as #6862 in the future. It also makes it easier to verify that all potential error conditions are checked.

It also reveals that overflow conditions return `UNKNOWN_ERROR`, there appears to be no specific error code for that.

Fixes #7513.

Changes are best reviewed using `git --word-diff`.

### CODE REVIEW

**Comment by laanwj** [comment]
These are never returned in any of the script tests:
- `SCRIPT_ERR_CHECKMULTISIGVERIFY`
- `SCRIPT_ERR_CHECKSIGVERIFY`
- `SCRIPT_ERR_NUMEQUALVERIFY`
- `ERR_NEGATIVE_LOCKTIME

**Comment by laanwj** [comment]
Ping @cfields @sipa @gmaxwell

**Comment by theuni** [comment]
@laanwj Closed on purpose? I didn't see this before, but sounds like a good idea for sure.

**Comment by laanwj** [comment]
@theuni Closed because I've been asking for review a few times for this, but never received any answer (neither positive nor negative) so I was assuming it was too much review work relative to some extra testing coverage.

Happy to reopen though!

**Pull request merged**
