### PR TITLE
Bump univalue subtree

### PR DESCRIPTION
**Pull request by maflcko**
This bumps the univalue subtree and changes two lines of our code. Apart from the get_int -> getInt change, this is mostly a rebase of https://github.com/bitcoin/bitcoin/pull/15975, which was closed back then.

However, given the numerous UniValue copy bugs and performance regressions in the past years, I think it makes sense to finally go through with the changes and disable potentially expensive implicit UniValue copies, which may cause OOM.

The changes here are not strictly required for that, but make future changes less verbose and easier to review.

### CODE REVIEW

**Comment by fanquake** [comment]
Concept ACK

**Review by fanquake — APPROVED** [review]
ACK fa0cc61b7f79b1844ac0fb3831e606a1ba861c15
```bash
src/univalue in HEAD currently refers to tree 6ba346f1e5bda33c46e6d242eb1440da46a502bf
src/univalue in HEAD was last updated in commit 025c6ca509f9e3975505d9fd786a4ca73a3a3a2d (tree 6ba346f1e5bda33c46e6d242eb1440da46a502bf)
GOOD
```

Guix Build (arm64):
```bash
8cfab617fa2b511fdc82b55d49f830e69ae76eaf630c0cdf664d1949c88d361c  guix-build-fa0cc61b7f79/output/arm-linux-gnueabihf/SHA256SUMS.part
81347fdcab2e8509ffc2ce31a8c38b7111c645c83293511739ca95c8614b3c59  guix-build-fa0cc61b7f79/output/arm-linux-gnueabihf/bitcoin-fa0cc61b7f79-arm-linux-gnueabihf-debug.tar.gz
12bb761c54463f282a7511c32a4136bb193398b2d29971ca10f8ca6a56fd5cdf  guix-build-fa0cc61b7f79/output/arm-linux-gnueabihf/bitcoin-fa0cc61b7f79-arm-linux-gnueabihf.tar.gz
26c96378fa32c04ee5b9fc980c35dde4b8bd7d3695153e906539ee0caf8860ad  guix-build-fa0cc61b7f79/output/arm64-apple-darwin/SHA256SUMS.part
ed3cb7f798e88b1377051666473ee50dd02ff57a01c7aa006e7436c00520d532  guix-build-fa0cc61b7f79/output/arm64-apple-darwin/bitcoin-fa0cc61b7f79-arm64-apple-darwin-unsigned.dmg
d0319be8537b6c56a698bfa0d82063e2cc98f30a55c26ad7ccd0e246b98f4895  guix-build-fa0cc61b7f79/output/arm64-apple-darwin/bitcoin-fa0cc61b7f79-arm64-apple-darwin-unsigned.tar.gz
03e23c9d377ab08c39f1f383d518eefec2a6cdb7fda6b8bec7b4f15b51fd557f  guix-build-fa0cc61b7f79/output/arm64-apple-darwin/bitcoin-fa0cc61b7f79-arm64-apple-darwin.tar.gz
25c0aadb971599d74f657227f73544732a69a61156fd3b2be532d62c12f98d14  guix-build-fa0cc61b7f79/output/dist-archive/bitcoin-fa0cc61b7f79.tar.gz
f02ee628008c641dd85de08014be830635221f1d717fde201176716cf18d1949  guix-build-fa0cc61b7f79/output/powerpc64-linux-gnu/SHA256SUMS.part
048885a7ee118901621c91cc0fca2e44d943fd712e55e95a3b5796d65778aad7  guix-build-fa0cc61b7f79/output/powerpc64-linux-gnu/bitcoin-fa0cc61b7f79-powerpc64-linux-gnu-debug.tar.gz
547111fc50a2bcd3d5f9bd6c58f97787ca8e4373726194ce6a9cfc108bfe24a7  guix-build-fa0cc61b7f79/output/powerpc64-linux-gnu/bitcoin-fa0cc61b7f79-powerpc64-linux-gnu.tar.gz
a9c753f88ca4b4c4a1e2038ce68b88bc56461dbbed81b647b89e30abcda3b285  guix-build-fa0cc61b7f79/output/powerpc64le-linux-gnu/SHA256SUMS.part
61abbeaabec40fec0e17a06cb417ca69f473aee6583039cdb09539288d20f216  guix-build-fa0cc61b7f79/output/powerpc64le-linux-gnu/bitcoin-fa0cc61b7f79-powerpc64le-linux-gnu-debug.tar.gz
395fdb9c764829492d43f88cd50385e3569aae9565822833b999028afd124365  guix-build-fa0cc61b7f79/output/powerpc64le-linux-gnu/bitcoin-fa0cc61b7f79-powerpc64le-linux-gnu.tar.gz
d3b48140ae359396e62115dae09caaa94730ae1608a7ebfcfd0951f99b7f567a  guix-build-fa0cc61b7f79/output/riscv64-linux-gnu/SHA256SUMS.part
51e6fe65ec438584729a8f3631c2f2b7fa21e2621c3933cf19fabf0059e47d0f  guix-build-fa0cc61b7f79/output/riscv64-linux-gnu/bitcoin-fa0cc61b7f79-riscv64-linux-gnu-debug.tar.gz
89b558c5cc25687fc6479253ab56061c62dba0c15b233b37d1f0e6bcacb1d2bb  guix-build-fa0cc61b7f79/output/riscv64-linux-gnu/bitcoin-fa0cc61b7f79-riscv64-linux-gnu.tar.gz
1e216a1f8d131ddb6225f335902a97a4c1fc9159b57150584a947de1115f0139  guix-build-fa0cc61b7f79/output/x86_64-apple-darwin/SHA256SUMS.part
a7ebea7fcf2db3a631f5a48e13ce85a295cf0f6ad89abebee3df0e37ea6ec351  guix-build-fa0cc61b7f79/output/x86_64-apple-darwin/bitcoin-fa0cc61b7f79-x86_64-apple-darwin-unsigned.dmg
3a5e34c1777c0346e0a84ec7b3eb67ed6db53434d176f1c259bfc7cd05f11176  guix-build-fa0cc61b7f79/output/x86_64-apple-darwin/bitcoin-fa0cc61b7f79-x86_64-apple-darwin-unsigned.tar.gz
20a868f1be92103a8ef1c6b42faea4af2fcf4537ab4bcf8b6ce54aa4c8d799ec  guix-build-fa0cc61b7f79/output/x86_64-apple-darwin/bitcoin-fa0cc61b7f79-x86_64-apple-darwin.tar.gz
9d5f011f5612d6cbcc24f4f9511ebd39b4da53a61d5aacab13e46a8d7408434a  guix-build-fa0cc61b7f79/output/x86_64-linux-gnu/SHA256SUMS.part
977f2dc8554bf46a50103724597c94153abedaba8089efc37407a424934fa031  guix-build-fa0cc61b7f79/output/x86_64-linux-gnu/bitcoin-fa0cc61b7f79-x86_64-linux-gnu-debug.tar.gz
c54f5bf857bae26e0fe1743f42e4d4c38fb516de4712895f2977955ec7778638  guix-build-fa0cc61b7f79/output/x86_64-linux-gnu/bitcoin-fa0cc61b7f79-x86_64-linux-gnu.tar.gz
064d38ef0281898ce62e4099e7348effc6f88db129d699a085257f60f0f0d5d9  guix-build-fa0cc61b7f79/output/x86_64-w64-mingw32/SHA256SUMS.part
1e302fcf58b1323b96cc62dfcc9e3ad3fa2731998a01c329aabc60f19a1ec265  guix-build-fa0cc61b7f79/output/x86_64-w64-mingw32/bitcoin-fa0cc61b7f79-win64-debug.zip
fbfaa8a4ed26364316d235d834bc8943db39d8c4c9aa28503e969151e82582ce  guix-build-fa0cc61b7f79/output/x86_64-w64-mingw32/bitcoin-fa0cc61b7f79-win64-setup-unsigned.exe
3730d9a4378cfabea19cde375de2af0da19baec457bb8680199f42d9c7cc15c9  guix-build-fa0cc61b7f79/output/x86_64-w64-mingw32/bitcoin-fa0cc61b7f79-win64-unsigned.tar.gz
5bcc6326f683600348aa75d4a09e420fa8c337bf56502a55bb5eabe6a16b7a68  guix-build-fa0cc61b7f79/output/x86_64-w64-mingw32/bitcoin-fa0cc61b7f79-win64.zip
```

**Comment by MarcoFalke** [comment]
cc @promag (I stole the diff from you)

**Comment by laanwj** [comment]
Code review ACK fa0cc61b7f79b1844ac0fb3831e606a1ba861c15

**Pull request merged**
