### PR TITLE
Re-wrote a passage of text that was difficult to understand.

### PR DESCRIPTION
**Pull request by jasonlewicki**
A simple document update.

### CODE REVIEW

**Comment by jasonlewicki** [comment]
My first commit to the bitcoin repo. I've never done this before, so I wanted to start off with something small.

**Comment by luke-jr** [comment]
ACK; it still seems unclear, but it's at least an improvement.

**Comment by fanquake** [comment]
ACK, definitely an improvement

**Comment by laanwj** [comment]
ACK for @theuni's trivial branch

**Comment by laanwj** [comment]
Was merged into trivial-next.

**Pull request closed without merging**
