### PR TITLE
[depends] ZeroMQ 4.2.2

### PR DESCRIPTION
**Pull request by fanquake**
Update depends ZeroMQ to 4.2.2, the release notes are available [here](https://github.com/zeromq/libzmq/releases).

We can drop both patches, as they have both been merged upstream (they actually had been for some time but just hadn't yet made it into a release).

`--without-documentation` is deprecated and has been replaced with `--without-docs`.
`--disable-perf` disables building performance measuring tools, which are enabled by default, see the libzmq [configure.ac](https://github.com/zeromq/libzmq/blob/master/configure.ac#L367).
Updated dependencies.md.
`--disable-curve-keygen` disable building the curve key generation tool. See [here](https://github.com/zeromq/libzmq/blob/master/configure.ac#L405).

Can someone on windows test that this is still working correctly. Maybe @achow101 ?

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Travis Windows (depends build) is failing.
I think you need to adopt the MinGW static patches instead of removing.

**Comment by fanquake** [comment]
The patches were only turning this line: `AC_MSG_ERROR([Building static libraries is not supported under MinGW32])` into `CPPFLAGS="-DZMQ_STATIC $CPPFLAGS"` (in two steps, as we wanted to use the commits from upstream). The new configure.ac now contains both patches, see [here](https://github.com/zeromq/libzmq/blob/master/configure.ac#L271), so I think this might be a different issue. Will investigate shortly.
```
/usr/share/mingw-w64/include/netioapi.h:458:3: error: ‘SOCKADDR_INET’ has not been declared
   SOCKADDR_INET *BestSourceAddress
   ^
In file included from /usr/share/mingw-w64/include/iphlpapi.h:16:0,
                 from src/windows.hpp:58,
                 from src/precompiled.hpp:37,
                 from src/address.cpp:30:
/usr/share/mingw-w64/include/netioapi.h:585:9: error: ‘SOCKADDR_INET’ does not name a type
   const SOCKADDR_INET *SourceAddress
         ^
In file included from src/windows.hpp:58:0,
                 from src/precompiled.hpp:37,
                 from src/address.cpp:30:
/usr/share/mingw-w64/include/iphlpapi.h:147:5: error: ‘SOCKADDR_IN6’ does not name a type
     SOCKADDR_IN6 Ipv6Address;
     ^
```

**Comment by fanquake** [comment]
Rebased and force pushed, pretty sure I've fixed the compilation issue here.

**Comment by fanquake** [comment]
Pushed a commit to update to the latest point release (4.2.1), may also help with these issues.

**Comment by laanwj** [comment]
Still the SOCKADDR_INET issue

**Comment by laanwj** [comment]
Seems this is blocked by an upstream issue?

**Comment by TheBlueMatt** [comment]
Has the issue been reported upstream? Any closer to resolving this one?

**Comment by fanquake** [comment]
@theuni Can you take a look here you have a chance? We discussed setting `WINNT` a while back, but I can't quite seem to get it right.

**Comment by MarcoFalke** [comment]
@fanquake Moved this to 0.17.0, since it seems stuck.

**Comment by theuni** [comment]
Sorry for overlooking this.

I believe I've managed to track down the issue. @fanquake Could you try replacing your second commit with this one instead: https://github.com/theuni/bitcoin/commit/ef3ced4e0d0519c903bf115760aa3307f60a09ad ?

That should work around the missing includes.

**Comment by fanquake** [comment]
@theuni Thanks. Just had to trim the patch whitespace to keep the linter happy. Tests looks good now. Re-assigning to the 0.16.0 milestone.

**Review by theuni — APPROVED** [review]
utACK 4fd7af8ec3eaebbebd1b431a6de668eeabdd8d54

**Comment by fanquake** [comment]
Added `--disable-curve-keygen` to our configure options. This option disables building the curve key generation tool, see the zeromq [configure.ac](https://github.com/zeromq/libzmq/blob/master/configure.ac#L405).

**Comment by theuni** [comment]
Sure, utACK 126999d1cc1b2513cb2ca62a70db0cd6a912a7ba.

**Pull request merged**
