### PR TITLE
build,doc: Update for 0.13.0+ and OpenBSD 5.9

### PR DESCRIPTION
**Pull request by laanwj**
Build:
- LevelDB platform was not guessed correctly (it ended up defining `-DOS_OPENBSD59` instead of `-DOS_OPENBSD`). This has been fixed by adding explicit checks for OpenBSD and FreeBSD.
- On OpenBSD there is no convenience link from `python3.5` to `python3`: add detection for other python interpreter names.
- If it has to guess the LevelDB OS, print a autoconf warning so that the user can check.

Changes to `build-openbsd.md`:
- Python 3 now supported.
- Bump boost version to 1.61 - one boost patch no longer needed.
- All checked with OpenBSD 5.9, except for the clang part, I left this as-is for someone adventurous.
- Mention overriding resource limits, OpenBSD's default ulimit does not  suffice for building Bitcoin Core with gcc 4.9.3.

### CODE REVIEW

**Comment by laanwj** [comment]
@theuni can you take a look at the build system changes

**Comment by paveljanik** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/8604/commits/b96fd9b5a009355cd0bd97ac921e62cd397bbc9a

**Comment by fanquake** [comment]
Tested ACK compiled 0.13.0 + 6275123 on OpenBSD5.9

Built with VirtualBox 5.1.4 on OS X 10.11 . Didn't check the Clang part.

Needed the autogen.sh changes otherwise I saw the same issues as #8127, so that should be closed when this is merged.

**Comment by theuni** [comment]
utACK 6275123ce960172aeecfe087c8c0e303a216736a. Looks good to me.

**Pull request merged**
