### PR TITLE
RPC: Chainparams: Simplify -rpcport and CBaseMainParams 

### PR DESCRIPTION
**Pull request by jtimon**
(the latter is just a very encapsulated global string var now [but it still
decides what dir to read fikes from]).

 Command line argument -rpcport no longer has a complex default to
 think about. The default for bitcoin is 8332 and remains that.
 For testnet3 and regtest; explicitly specifying -rpcport=18332 and -rpcport=18443
 respectively is still possible as always.

### CODE REVIEW

**Review by dcousens — APPROVED** [review]

**Comment by sipa** [comment]
I don't understand why?

**Comment by gmaxwell** [comment]
NAK. This seems to be a straightforward reduction in functionality for no obvious reason.

**Comment by esotericnonsense** [comment]
nACK echoing comments above

**Comment by jtimon** [comment]
The reason is to simplify the code and configuration. Chainparams is abused for many things that have nothing to do with the chain itself, like defaults for other options (like in this case).
I don't consider this a reduction in functionality but a simplification in the configuration. The functionality is selecting the rpc port, which can still be done.

I would also remove GetDefaultPort, DefaultConsistencyChecks and RequireStandard from CChainParams, but I assume that would be nacked as well for being considered "a reduction of functionality"...

**Comment by sipa** [comment]
@jtimon Simplification is a good thing, but maybe you're missing the functionality this brings. The P2P network heavily favors nodes that run on the default port (there is a bias for them when making outgoing connections - preventing DoS attacks on third party services, and DNS seeds can only give results that run on the default port). Further you're ccomplicating running both testnet and mainnet on the same machine.

**Comment by jtimon** [comment]
Running mainnet and testnet in the same machine would just -rpcport=18332 (for example) for testnet.
I assume the default port thing applies to CChainParams::GetDefaultPort not BaseParams().RPCPort().

But yeah, I didn't know about that.

**Pull request closed without merging**
