### PR TITLE
Trivial: Fix two VarInt examples in serialize.h

### PR DESCRIPTION
**Pull request by cbarcenas**
Two of the VarInt examples given in the comments of `serialize.h` are wrong. This is a minor change to correct them.

To verify, you can compute the VarInt encodings of 16511 and 65535 by hand or use the following test program (requires C++11):

```
#include <iomanip>
#include <iostream>
#include <sstream>
#include <vector>

#include "serialize.h"

int main()
{
  std::vector<unsigned long long> inputs = {
    0, 1, 127, 128, 255, 256, 16383, 16384, 16511, 65535, (1LL << 32)
  };

  for (auto& input : inputs) {
    std::stringstream output;

    WriteVarInt(output, input);

    std::cout << std::dec << input << ':';
    int c;
    while ((c = output.get()) != EOF) {
      std::cout << " 0x" << std::hex << std::setw(2) << std::setfill('0') << c;
    }
    std::cout << std::endl;
  }
}
```

### CODE REVIEW

**Comment by laanwj** [comment]
```
bitcoin/src$ g++ -std=c++11 test_serialize.cpp -o test_serialize -I. -DHAVE_CONFIG_H -I../build/src
bitcoin/src$ ./test_serialize 
0: 0x00
1: 0x01
127: 0x7f
128: 0x80 0x00
255: 0x80 0x7f
256: 0x81 0x00
16383: 0xfe 0x7f
16384: 0xff 0x00
16511: 0xff 0x7f
65535: 0x82 0xfe 0x7f
4294967296: 0x8e 0xfe 0xfe 0xff 0x00
```
I may be misreading your comment, but `128` becomes `0x80 0x00`, not `0xFF 0x7F`?

**Comment by dcousens** [comment]
utACK 7bd5ff4

**Comment by sipa** [comment]
ACK 7bd5ff46237b06b3cf223176c1c71ef66383fa92, verified by hand

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/8560/commits/7bd5ff46237b06b3cf223176c1c71ef66383fa92

Brilliant eye - never ever trust old comments 👍 Thank you!

**Comment by fanquake** [comment]
utACK 7bd5ff4

**Pull request merged**
