### PR TITLE
[0.18] Backport 15749: importmulti only imports origin info for PKH outputs

### PR DESCRIPTION
**Pull request by meshcollider**
Clean backport of #15749 by sipa to 0.18

### CODE REVIEW

**Comment by fanquake** [comment]
@meshcollider These commits are missing the `Github-Pull:` and `Rebased-From:` info.

**Comment by MarcoFalke** [comment]
The backport should include the metadata. You may use a script to do it for you: https://github.com/bitcoin-core/bitcoin-maintainer-tools#backport

**Comment by meshcollider** [comment]
Sorry, fixed, forgot about the metadata

**Comment by fanquake** [comment]
utACK 235550d

**Comment by MarcoFalke** [comment]
ACK 235550d019 (Checked that they are clean cherry-picks)

**Pull request merged**
