### PR TITLE
[trivial] credit values are CAmount

### PR DESCRIPTION
**Pull request by instagibbs**

### CODE REVIEW

**Comment by achow101** [comment]
utACK 20c3215a9031b3dbbde641b933246b3e222e4eca

**Comment by MarcoFalke** [comment]
ACK 20c3215a9031b3dbbde641b933246b3e222e4eca

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/commit/20c3215a9031b3dbbde641b933246b3e222e4eca

**Comment by sipa** [comment]
utACK

**Pull request merged**
