### PR TITLE
refactor: Remove stray cs_main redundant declaration

### PR DESCRIPTION
**Pull request by maflcko**
Looks like this was forgotten when introducing kernel/cs_main ?

Also, there is a commit to export threadsafety.h from sync.h.

### CODE REVIEW

**Comment by hebasto** [comment]
Concept ACK.

**Review by hebasto — APPROVED** [review]
ACK faba08b5b4dd5dedb457db18696de6e15839c696

> Also, there is a commit to export threadsafety.h from sync.h.

I'm not sure about that because thread safety annotations are mostly used in headers, and `sync.h` can be needed to be included in source files only. For example, without that commit, `node/utxo_snapshot.h` needs a replacement s/`#include <sync.h>`/`#include <threadsafety.h>`/.

**Comment by MarcoFalke** [comment]
> sync.h can be needed to be included in source files only

No? If the header uses a `Mutex`, it will need to include sync.h. Is there any place in the codebase that doesn't use `Mutex`?

**Comment by hebasto** [comment]
> Is there any place in the codebase that doesn't use `Mutex`?

For example, `node/utxo_snapshot.h` from this PR?

**Comment by MarcoFalke** [comment]
Well, I meant `Mutex` or `RecursiveMutex`, or whatever else is in `sync.h`.

The point is that you can't compile `utxo_snapshot.h` without `sync.h`, and any other place that uses symbols with theadsafety annotations from `sync.h`, in which case including theadsafety.h again serves no purpose other than noise.

**Comment by hebasto** [comment]
> Well, I meant `Mutex` or `RecursiveMutex`, or whatever else is in `sync.h`.
> 
> The point is that you can't compile `utxo_snapshot.h` without `sync.h`

It is job of `<kernel/cs_main.h>` now, no?

> and any other place that uses symbols with theadsafety annotations from `sync.h`, in which case including theadsafety.h again serves no purpose other than noise.

Agree. Probably the use case of `<kernel/cs_main.h>` is the only counter example.

**Comment by MarcoFalke** [comment]
I think the only counter example (something that doesn't need `sync.h` directly or indirectly) is `logging.h`, because it only needs threadsafety, see https://github.com/bitcoin/bitcoin/blob/d4c180ecc9aec5baa6c074f78e4d2c5e28b124ac/src/logging.h#L10

Though, I am not changing that in this pull.

**Comment by MarcoFalke** [comment]
cc @fanquake

**Pull request merged**
