### PR TITLE
wallet: Fix bug when just created encrypted wallet cannot get address

### LINKED ISSUE #105: Newley created encrypted wallets can't use "Create new receiving address"
Freshly created **encrypted** wallets do have the "Create new receiving address" Button disabled. Closing and reopening fixes the issue.

Bildschirmfoto 2020-10-23 um 12 52 48

Added 0.21.0 milestone.

### PR DESCRIPTION
**Pull request by hebasto**
Fix https://github.com/bitcoin-core/gui/issues/105

### CODE REVIEW

**Comment by hebasto** [comment]
cc @jonasschnelli @achow101

**Comment by achow101** [comment]
Tested ACK bf6855a9096b25aa75bba61b57ee1b2433d49707

**Review by kristapsk — APPROVED** [review]
ACK bf6855a9096b25aa75bba61b57ee1b2433d49707

**Review by meshcollider — COMMENTED** [review]
Tested ACK bf6855a9096b25aa75bba61b57ee1b2433d49707

**Pull request merged**
