### PR TITLE
RPC: Use integer satoshis instead BTC with decimals

### PR DESCRIPTION
**Pull request by jtimon**
There's been talks about using satoshis in RPC instead of BTC, which requires decimals and don't work well with json.

On the other hand, such a change would break the RPC API as well as many tests.
This is a draft on how we could move there (doing it only for 2 of the 8 RPC calls that would need to be changed). An useDecimalAmounts optional param is added. If true, the user can introduce BTC amounts as before. If false, the user needs to introduce the amounts in satoshis.

Interestingly enough, for signrawtransaction, useDecimalAmounts can default to false without breaking any tests (which means the amounts in useDecimalAmounts are not being currently tested).
In contrast, createrawtransaction would break many tests.

We could slowly adapt the tests to use satoshis and once that's done, at some point in the future we could break the API, remove all useDecimalAmounts params and not allow to BTC amounts anymore.

I didn't want go further before getting some feedback.

### CODE REVIEW

**Comment by da2ce7** [comment]
Concept ACK.  I think that it is important to have an API Break at some point. Moving away from Decimal Amounts is very desirable.

**Comment by jgarzik** [comment]
General agreement, with a notable caveat:

Older but widely deployed versions of the jansson library will truncate JSON numbers that are integers larger than unsigned 32-bit.

**Comment by luke-jr** [comment]
Dislike making another numbered argument.

If we care about jansson bugs, I suspect throwing a ".0" on the end would workaround them.

**Comment by jgarzik** [comment]
On the floating point side, you're limited by the 'double' C data type.

Some people just throw up their hands and store numbers inside of strings :)

**Comment by JeremyRubin** [comment]
One idea:

pass a "multiplier" argument to the RPCs such that users can select arbitrary number systems. Default it to Bitcoin or Satoshis. This future proofs the API design in the event of any popular system (or even prepping for fractional satoshis...)


This could also be useful for people wishing to pay at an exchange rate :)

**Comment by TheBlueMatt** [comment]
This is the kind of thing I think should be an option in the named
arguments list, but probably not added to every single RPC command's
positional parameters.

**Comment by luke-jr** [comment]
`double` is large enough for any satoshi amounts on most systems (and any exceptions are likely to not support Core at all right now).

**Comment by laanwj** [comment]
NACK doing it in this way.

- I'd prefer "return amounts as strings". It would be more consistent.  "Integers" don't exist in JSON. A JSON parser could still convert large numbers to float silently. Returning the values as strings means the program can use whatever internal format they want - it moves parsing away from the JSON parser, which is usually hard to override.

We already added handling of these for input in `AmountFromValue` in #6380, with the idea of making that an option later.

- If you really want to go ahead with this please see my implementation in #3759. It was much less invasive, effectively only two functions were touched `AmountFromValue`  and `ValueFromAmount`, and it allowed the user to select between four variants. 

There is no need to change every single call site of those functions for this!

**Comment by jtimon** [comment]
Replaced by #9882

**Pull request closed without merging**
