### PR TITLE
Compressed Bitcoin Transactions

### PR DESCRIPTION
**Pull request by TomBriar**
This is a draft PR and reference implementation for a Compressed Bitcoin Transaction, As stated in the doc the main application for this is steganography, satellite/radio broadcast, and other low bandwidth channels with a high CPU availability on decompression.

doc: Added Compressed Transaction Schema Documentation
util: Added a variable length bitstream encoder
script: Added the rest of the IsPayTo Script functions, And Split ExtractDestination into two functions for ease of use
node: Added a vector based coin lookup
primitives: Added Compressed Transaction
validation: Added OutPoint Compression methods to the chainstate class
rpc: Added RPC endpoints for compression and decompression of Transactions
test: Added Tests for the RPC and new Primitive
fuzz: Added a fuzz test for Compressed Transactions

Link to first post on the bitcoin mailing list:
https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2023-August/021924.html

### CODE REVIEW

**Comment by 1440000bytes** [comment]
Concept ACK

25-50% savings look good and compressed raw transactions can help in some cases as mentioned in the PR description. 

Related Q&A: https://bitcoin.stackexchange.com/questions/98886/compress-transaction-hex-string (still wont fit in one text message but will need less text messages)

**Comment by achow101** [comment]
Is this intended to be used for storage, p2p relay, or something else? If for our storage, I would be interested in seeing benchmarks as this would have an effect on how quickly things can be pulled from disk to be relayed. If for relay, then I think there should first be a BIP that describes the protocol for using compression and how that is negotiated. And if neither of those, then I don't think it's within the scope of Bitcoin Core. It seems to be a pretty significant maintenance burden for something that, as implemented, is only used by specific new RPCs.

**Review by furszy — COMMENTED** [review]
You could run the lint whitespace task locally. It is inside test/lint folder.

**Comment by TomBriar** [comment]
Hi,

This is a reference implementation for the compression scheme described in this WIP BIP:
https://github.com/bitcoin/bips/pull/1556

It may be a bit heavy to be PR'd into bitcoin core at this time, although it has a great application for both the P2P and Storage in bitcoin core. Another project that implements the same schema is underway as an external tool and the RPC commands were found to be sufficient.

Thanks-
Tom.

**Pull request closed without merging**
