### PR TITLE
qt: Make bitcoin.ico non-executable

### PR DESCRIPTION
**Pull request by practicalswift**
Make `bitcoin.ico` non-executable.

No need to execute icons and having +x bits laying around breaks `find … -executable` :)

Before this patch:

```sh
$ find $(git ls-files -- ":(exclude)*.sh" ":(exclude)*.py") -executable
ci/retry/retry
contrib/macdeploy/macdeployqtplus
depends/config.guess
depends/config.sub
src/qt/res/icons/bitcoin.ico
src/secp256k1/src/modules/recovery/main_impl.h
```

After this patch:

```sh
$ find $(git ls-files -- ":(exclude)*.sh" ":(exclude)*.py") -executable
ci/retry/retry
contrib/macdeploy/macdeployqtplus
depends/config.guess
depends/config.sub
src/secp256k1/src/modules/recovery/main_impl.h
```

FWIW:

```
$ file $(find $(git ls-files -- ":(exclude)*.sh" ":(exclude)*.py") -executable)
ci/retry/retry:                                 Bourne-Again shell script, UTF-8 Unicode text executable
contrib/macdeploy/macdeployqtplus:              Python script, ASCII text executable
depends/config.guess:                           POSIX shell script, ASCII text executable
depends/config.sub:                             POSIX shell script, ASCII text executable
src/qt/res/icons/bitcoin.ico:                   MS Windows icon resource - 10 icons, 48x48, 16 colors, 4 bits/pixel, 32x32, 16 colors, 4 bits/pixel
src/secp256k1/src/modules/recovery/main_impl.h: C source, ASCII text
```

### CODE REVIEW

**Comment by practicalswift** [comment]
The `src/secp256k1/src/modules/recovery/main_impl.h` case has now been fixed upstreams thanks to @elichai -- see https://github.com/bitcoin-core/secp256k1/pull/740 :)

**Comment by MarcoFalke** [comment]
ACK a95af77eb264646b4160836e4e9a2c4b45f87bb8 gitian build finished, so it doesn't look like the icon used in Windows resource files needs to be executable. Though, I didn't read the documentation.

**Review by jonatack — COMMENTED** [review]
Nice find.

ACK a95af77eb264646

**Comment by MarcoFalke** [comment]
The testnet icon doesn't have +x either, so I think this is good to merge.

```
$ ll ./src/qt/res/icons/bitcoin*.ico
-rwxrwxr-x. 1 marco marco 57964 Apr 14 15:18 ./src/qt/res/icons/bitcoin.ico
-rw-rw-r--. 1 marco marco 57251 Apr 14 15:18 ./src/qt/res/icons/bitcoin_testnet.ico

**Pull request merged**
