### PR TITLE
[0.12.2] backport: [qa] Switch to py3

### PR DESCRIPTION
**Pull request by maflcko**
Github-Pull: #7814 
This also includes the other .12 backports but I expect travis to fail on this one.

@laanwj can you try to look into backporting #7723 and a6666b2 if we want to switch to py3 in .12 as well?

### CODE REVIEW

**Comment by laanwj** [comment]
Whoa, at some point it seems easier to copy over the tests from master and disable the parts that are not appropriate.

**Comment by luke-jr** [comment]
Not sure it's appropriate to add dependencies to stable versions. But otoh, it's just tests... (or does this still work with Py2 as well?)

**Comment by MarcoFalke** [comment]
No, the qa/ subfolder is not compatible. It is either python2 or python3.

**Comment by laanwj** [comment]
> Not sure it's appropriate to add dependencies to stable versions. But otoh, it's just tests...

It's a bit of a grey area, but yes it's "just tests", and in addition to that I think the fact that the RPC tests are never invoked by the build system makes this acceptable.

**Comment by MarcoFalke** [comment]
Removed WIP tag

**Comment by laanwj** [comment]
tACK 2826565

**Pull request merged**
