### PR TITLE
ci: Add tsan suppression for race in DatabaseBatch

### PR DESCRIPTION
**Pull request by hebasto**
Since #19325 was merged, the corresponding change in TSan suppression file gets required.

This PR is:
- an analogous to #19226 and #19450, and
- a temporary workaround for CI fail like https://cirrus-ci.com/task/5741795508224000?command=ci#L4993

### CODE REVIEW

**Comment by hebasto** [comment]
cc @MarcoFalke

**Comment by MarcoFalke** [comment]
Mind to cherry-pick 0d41ed87fc0afbbe0916d363fd71b12c5fe981eb in here as well?

**Comment by hebasto** [comment]
@MarcoFalke 
> Mind to cherry-pick [0d41ed8](https://github.com/bitcoin/bitcoin/commit/0d41ed87fc0afbbe0916d363fd71b12c5fe981eb) in here as well?

Done.

**Comment by MarcoFalke** [comment]
ACK 0cdf2a77ddfa1d53c6fbd830d557a3f20d7fc365

**Pull request merged**
