### PR TITLE
Update sendfrom RPC help to correct coin selection misconception

### PR DESCRIPTION
**Pull request by ryanofsky**
Common misunderstanding according to https://github.com/bitcoin/bitcoin/issues/9826#issuecomment-281934722

### CODE REVIEW

**Comment by laanwj** [comment]
utACK.

Can you put this PR in a time machine and file it five years ago? :-)

**Comment by TheBlueMatt** [comment]
Heh, ACK.

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/9840/commits/f81f0d003079b96b8c33d3dfe76f90e50344bcd8

**Comment by jnewbery** [comment]
Yay! Help text that's helpful :tada:

utACK

**Comment by MarcoFalke** [comment]
utACK f81f0d0

**Comment by kallewoof** [comment]
utACK f81f0d0

**Comment by MarcoFalke** [comment]
@laanwj Any reason this is assigned to 0.14.1?

**Comment by laanwj** [comment]
It should be backported to the 0.14 branch at some point, but not necessarily 0.14.0.

**Comment by laanwj** [comment]
However, now that it's clear that there's going to another rc I'm just going to include it.

**Pull request merged**
