### PR TITLE
Travis test (not to merge): Introduce silent bug in CFeeRate

### PR DESCRIPTION
**Pull request by jtimon**
This passes unittests and `python ./qa/pull-tester/rpc-tests.py -extended`.
I just want to make sure this passes travis before proposing a test that would make this change fail.
I know it may not be very important or a priority right now, but since I have it done already, one more check in the unittests won't harm.
Please, don't merge.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
I don't think this constructor is used right now, so the compiler will probably wipe it and it should not make a difference for travis.

**Comment by jtimon** [comment]
If it wasn't used, my new test shouldn't fail with this change either, but it does.

**Comment by laanwj** [comment]
Good catch, this definitely needs a test

**Comment by MarcoFalke** [comment]
Indeed, it is used. Happy to review if you submit the patch for the tests.

**Comment by jtimon** [comment]
I'm glad that this is helpful, the fix test is in #7728 (sorry, I opened the PR without paying attention to github, which was telling me I needed to rebase on top of #7705 ).

I actually "wasted" much more time than expected on a draft branch to make a point that shouldn't have taken me much time because this test didn't exist. But what I did is kind of a long story with some embarrassing parts that I'm still not sure I want to publish. More details in a follow up discussion PR though (separated from #7728 ).

**Pull request closed without merging**
