### PR TITLE
Bugfix: Allow building libbitcoinconsensus without any univalue

### PR DESCRIPTION
**Pull request by luke-jr**

### CODE REVIEW

**Comment by theuni** [comment]
Concept ACK. A few nits:
- Please store the test as build_no_programs or build_libs_only or so, so that we only need the ugly xnononono stuff in one place.
- I'd rather not abuse system_univalue that way, as it's not obvious what it's doing. Please change that to configure_embedded_univalue or so, and rework the test as necessary.

**Comment by luke-jr** [comment]
It's conceivable that at some point bitcoin-tx could be freed of the univalue dependency as well, so I'm not sure it makes sense to do the dedicated var?

**Comment by laanwj** [comment]
I don't think that's realistic. bitcoin-tx uses JSON objects in various places in the interface

**Comment by theuni** [comment]
@luke-jr My only concern is that "system_univalue" should not be equated to "don't use any univalue". renaming to need_univalue would suffice.

**Comment by laanwj** [comment]
Ok, let's rename it then.

**Comment by luke-jr** [comment]
Renamed.

**Comment by theuni** [comment]
Thanks. utACK.

**Comment by jgarzik** [comment]
ut ACK

**Comment by luke-jr** [comment]
Needs backport to 0.13.

**Pull request merged**
