### PR TITLE
Allow per network configuration file

### LINKED ISSUE #9374: Per-network bitcoin.conf files
When running with the -testnet option, I would expect the bitcoin.conf file in the testnet3 directory to be used, yet it uses the mainnet config file instead, yet the debug.log indicates the datadir is the testnet3 dir:-

```
2016-12-19 03:08:58.629380 Using data directory /home/rebroad/.bitcoin/testnet3
2016-12-19 03:08:58.629453 Using config file /home/rebroad/.bitcoin/bitcoin.conf
```

### PR DESCRIPTION
**Pull request by rebroad**
Fixes #9374

### CODE REVIEW

**Comment by kallewoof** [comment]
Since `netconf` values should override main config settings, you want to load `netconf` before `conf`, I think. See https://github.com/bitcoin/bitcoin/blame/master/src/util.cpp#L546

**Comment by laanwj** [comment]
> Since netconf values should override main config settings, you want to load netconf before conf, I think

That's not possible, as conf can specify the network.

**Comment by kallewoof** [comment]
It can, sure, but if it does, you have no use for per-network configuration files at all. You could just put the specified stuff into conf directly.

**Comment by rebroad** [comment]
needs more testing

**Comment by fanquake** [comment]
Needs a rebase.

**Comment by fanquake** [comment]
Lack of feedback, and still needs a rebase. Feel free to reopen when it has been.

**Pull request closed without merging**
