### PR TITLE
docs: Fix typos

### PR DESCRIPTION
**Pull request by practicalswift**
Fix typos.

### CODE REVIEW

**Comment by practicalswift** [comment]
@MarcoFalke I submit typos as I find them. If I have an already existing typo PR then I add the newly found typo to that one. Is that not the recommended procedure? :-)

**Comment by MarcoFalke** [comment]
Fine, I will leave this one open until next month.

**Comment by paveljanik** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/13069/commits/fdbe55337fc609ba48ce5fc11222b78b2256c7be

**Comment by laanwj** [comment]
> Fine, I will leave this one open until next month.

Agree.

**Comment by practicalswift** [comment]
Added three new typos.

**Comment by practicalswift** [comment]
Anyone willing to review? :-)

**Review by jb55 — APPROVED** [review]
ACK d8c4998f3198e8d7e37a8414b9891f6b74b9173b

**Pull request merged**
