### PR TITLE
test: Fix intermittent sync issue in wallet_pruning

### LINKED ISSUE #27065: Intermittent issue in wallet_pruning.py
```
wget https://drahtbot.space/temp_scratch/wallet_pruning_258.tar.xz
tar -xvf ./wallet_pruning_258.tar.xz
test/functional/combine_logs.py -c ./wallet_pruning_258
```

```
 test  2023-02-08T07:00:29.787000Z TestFramework (ERROR): Assertion failed 
                                   Traceback (most recent call last):
                                     File "/root/bitcoin-core/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 134, in main
                                       self.run_test()
                                     File "/root/bitcoin-core/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/wallet_pruning.py", line 127, in run_test
                                       self.mine_large_blocks(self.nodes[0], 50)
                                     File "/root/bitcoin-core/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/wallet_pruning.py", line 63, in mine_large_blocks
                                       self.sync_all()
                                     File "/root/bitcoin-core/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 728, in sync_all
                                       self.sync_blocks(nodes)
                                     File "/root/bitcoin-core/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 697, in sync_blocks
                                       assert (all([len(x.getpeerinfo()) for x in rpc_connections]))
                                   AssertionError

### PR DESCRIPTION
**Pull request by maflcko**
Setting the mocktime on each loop iteration will make net processing racy and cause a disconnect due to timeout.

Fix that by setting the mocktime only once.

Fixes https://github.com/bitcoin/bitcoin/issues/27065

### CODE REVIEW

**Review by brunoerg — APPROVED** [review]
crACK fa6f67837b08a808cdd72856ac24cc932863daf4

**Comment by mzumsande** [comment]
https://cirrus-ci.com/task/5441089956478976 :cry:

**Comment by MarcoFalke** [comment]
> https://cirrus-ci.com/task/5441089956478976 cry

Ah, good catch. This is the still exactly the  same error as in https://github.com/bitcoin/bitcoin/issues/27065. While the fix here is unrelated to fixing that bug, I think it is still needed to fix the same bug happening in a different line.

**Comment by MarcoFalke** [comment]
See https://github.com/bitcoin/bitcoin/pull/27093

**Pull request merged**
