### PR TITLE
build: no-longer fail default configure if BDB isn't available

### PR DESCRIPTION
**Pull request by fanquake**
Inline with moving to descriptor (sqlite) wallets by default for 0.23,
this adapts the build system so that a default `./configure` invocation
no-longer fails if BDB isn't present. Currently, if configure is run
with no options, and no BDB is present, we'll fail with:
```bash
checking for Berkeley DB C++ headers... no
configure: error: libdb_cxx headers missing, Bitcoin Core requires this library for BDB wallet support (--without-bdb to disable BDB wallet support)
```

If descriptor wallets are to be the default, this behaviour no longer
makes sense, as a builder should be able to configure and build, to use
a wallet, without BDB installed, and without passing additional
arguments, i.e `--without-bdb` or `--with-incompatible-bdb`, to
configure.

With this change, running configure will no-longer fail, but will
instead print:
```bash
checking for Berkeley DB C++ headers... no
configure: WARNING: libdb_cxx headers missing
configure: WARNING: Bitcoin Core requires this library for BDB (legacy) wallet support
configure: WARNING: Passing --without-bdb will suppress this warning
checking for sqlite3 >= 3.7.17... yes
checking whether to build wallet with support for sqlite... yes
```

### CODE REVIEW

**Comment by jarolrod** [comment]
strong concept ack

**Comment by practicalswift** [comment]
Strong Strong Concept ACK

This will greatly improve the first time Bitcoin Core developer experience by allowing the expected and familiar `./configure && make` routine :)

**Review by darosior — COMMENTED** [review]
Concept ACK

**Comment by laanwj** [comment]
What about `--with-incompatible-bdb` this is hardwired into my fingers now—
> without passing additional arguments, i.e --without-bdb or --with-incompatible-bdb, to configure.

Thanks :smile:

**Comment by amadeuszpawlik** [comment]
Very nice!

**Comment by hebasto** [comment]
Concept ACK.

**Comment by hebasto** [comment]
Maybe also replace an error with a warning and disabling BDB support for the following case:
```
$ ./autogen.sh 
$ ./configure --quiet
configure: error: Found Berkeley DB other than 4.8, required for portable BDB wallets (--with-incompatible-bdb to ignore or --without-bdb to disable BDB wallet support)
```
?

**Comment by fanquake** [comment]
> and disabling BDB support for the following case:

What do you mean by disabling BDB support? I think this should remain as an error for now.

**Comment by fanquake** [comment]
> Maybe also replace an error with a warning and disabling BDB support for the following case:

I've done this now.

**Review by hebasto — APPROVED** [review]
ACK 747cd17404832604c50d03d58e11ba816bb229f7, tested on Linux Mint 20.2 (x86_64) with the (un)installed system packages `libdb-dev` and `libdb++-dev`.

**Comment by katesalazar** [comment]
Once decided BDB is going out,
the earliest people gets the shock about removing it,
the better. This is a good idea. 👍

**Pull request merged**
