### PR TITLE
fuzz: add guide to fuzzing with Eclipser v1.x

### PR DESCRIPTION
**Pull request by agroce**
MarcoFalke and practicalswift here's an Eclipser guide, reconstructed from their documentation and my docker history getting it up and running.  It might be good if someone confirmed it actually works for them in a fresh ubuntu 20.04.

### CODE REVIEW

**Review by practicalswift — CHANGES_REQUESTED** [review]
Tested ACK d899d36a146822c0d6e90755f343ddc45904f84f modulo missing `./autogen.sh` :)

Thanks for doing this: Eclipser is a very nice and interesting fuzzer, and the addition of a symbolic execution inspired fuzzer to the Bitcoin Core "fuzzing ensemble" is awesome :)

Recommended reading for other reviewers: ["What Makes Eclipser Special?"](https://blog.trailofbits.com/2019/05/31/fuzzing-unit-tests-with-deepstate-and-eclipser/) (Trail of Bits) and the [Eclipser paper](https://softsec.kaist.ac.kr/~jschoi/data/icse2019.pdf).

This quote from the blog post referenced above describes why "the more the merrier" typically holds when it comes to choosing fuzzers:

> The research literature and practical wisdom of fuzzer use repeatedly show that, even when a fuzzer is good enough to “beat” other fuzzers (and thus get a paper published at ICSE), it will always have instances where it performs worse than an “old,” “outdated” fuzzer. In fuzzing, diversity is not just helpful, it’s essential, if you really want the best chance to find every last bug. No fuzzer will be best for all programs under test, or for all bugs in a given real-world program.

**Comment by MarcoFalke** [comment]
Concept ACK will test after https://github.com/bitcoin/bitcoin/pull/22585#discussion_r679758113

**Comment by agroce** [comment]
What I'd really like is to get tool-based ensemble fuzzing up and running, but my experiments right now are showing the tools may be not-ready-for-prime-time.  The DeepState ensembler (sort of) works right now, but porting doesn't seem like a good approach.

**Comment by jonatack** [comment]
Concept ACK. I might test with Debian.

**Comment by practicalswift** [comment]
Tested ACK 4f9784fc2d51843ebc05e81c31a508bee5b7e370

**Comment by MarcoFalke** [comment]
Please squash your commits according to https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#squashing-commits

**Comment by agroce** [comment]
Will squash in the AM

**Comment by agroce** [comment]
squashed & ready to go

**Comment by practicalswift** [comment]
ACK 6e1150ea3b82d1ab557d4b74aa652b8d974876aa

**Pull request merged**
