### PR TITLE
gitian: Ship debug tarballs/zips with debug symbols

### PR DESCRIPTION
**Pull request by theuni**
Addresses #7770, though only Linux and Windows for now. OSX will need a little more attention, since dsymutil isn't yet built as part of our toolchain.

To test, simply untar/unzip the new -debug files in the same path as the binaries, and gdb should find them automatically.

To make my life easier while I was in there, I fixed up depends to play nice with CONFIG_SITE, which can be used now instead of abusing --prefix, though the --prefix hack still works fine.

Now, configure can also be run like:

```
CONFIG_SITE=$PWD/depends/x86_64-pc-linux-gnu/share/config.site --prefix=/whatever/you/want
```

### CODE REVIEW

**Comment by laanwj** [comment]
Very cool!
utACK 7e7eb27

**Comment by jonasschnelli** [comment]
Nice utACK 7e7eb2724e1d66b9d6675433798f312a71789a8f

**Comment by sipa** [comment]
Concept ACK

**Comment by laanwj** [comment]
Tested ACK for Linux:
- Generating a backtrace works when loading the symbols in gdb, but not when not having loaded the symbols
- `addr2line` works
```bash
$ addr2line -aife bitcoind.dbg 0xb258c                                                                
0x00000000000b258c
_Z17ReadBlockFromDiskR6CBlockPK11CBlockIndexRKN9Consensus6ParamsE
/home/ubuntu/build/bitcoin/distsrc-x86_64-unknown-linux-gnu/src/main.cpp:1562
```
Haven't tested windows yet.

**Comment by laanwj** [comment]
Hm, only tangentially related to this pull, but this is strange, looks like windows .zip still has bench_bitcoin.exe:
```
-rwxr-xr-x 1 orion orion   2886675 Jan  1 00:00 bench_bitcoin.exe
-rwxrwxr-x 1 orion orion  15123409 Jan  1 00:00 bench_bitcoin.exe.dbg
```
Seems I overlooked that one in #7776.

**Comment by laanwj** [comment]
Tested ACK Windows:
```
$ /usr/bin/x86_64-w64-mingw32-addr2line -Caife bitcoind.exe.dbg 504000                                   
0x0000000000504000
CBlockIndex::GetMedianTimePast() const
/home/ubuntu/build/bitcoin/distsrc-x86_64-w64-mingw32/src/chain.h:291
UpdateTime(CBlockHeader*, Consensus::Params const&, CBlockIndex const*)
/home/ubuntu/build/bitcoin/distsrc-x86_64-w64-mingw32/src/miner.cpp:62
```

**Comment by theuni** [comment]
I tried it insomuch as gdb finds the symbols, but I had other local issues preventing gdb from working with wine. I'm not sure that I've ever actually used gdb for win debugging.

I'm assuming most windows crash investigations will happen via add2rline, but if you've used gdb that way in the past and would like to verify that it works, I'll see if I can work out my issue and test.

**Comment by laanwj** [comment]
> I'm assuming most windows crash investigations will happen via add2rline, but if you've used gdb that way in the past and would like to verify that it works, I'll see if I can work out my issue and test.

Yes, I've done so once, it was not a very pleasant experience.
No need to spend more work there, that's so rare that we can fix it up if it happens to not work then.

**Pull request merged**
