### PR TITLE
qt: Use parent-child relation to manage lifetime of OptionsModel object

### PR DESCRIPTION
**Pull request by hebasto**
Both `BitcoinApplication` and `OptionsModel` classes are derived from the `QObject` class, therefore a parent-child relation could be established to manage the lifetime of an `OptionsModel` object:
https://github.com/bitcoin/bitcoin/blob/5236b2e267a58870239673c7ec85e5df0cb8fc8e/src/qt/optionsmodel.cpp#L29-L30

This PR does not change behavior.

### CODE REVIEW

**Comment by Empact** [comment]
Perhaps also `BitcoinApplication#window`?

**Comment by hebasto** [comment]
@Empact 
> Perhaps also `BitcoinApplication#window`?

Unfortunately, this is impossible due to [`QMainWindow`](https://doc.qt.io/qt-5/qmainwindow.html#QMainWindow) expects a parent of the `QWidget` type. And the `BitcoinApplication` class is not derived from the `QWidget`.

**Comment by jonasschnelli** [comment]
Yeah. Why not. I just find it confusing to find a `new` but not a `delete` on the same layer of code when using raw pointers.

**Comment by hebasto** [comment]
> Yeah. Why not. I just find it confusing to find a `new` but not a `delete` on the same layer of code when using raw pointers.

That is how [Qt Object Trees](https://doc.qt.io/qt-5/objecttrees.html#construction-destruction-order-of-qobjects) work.

**Review by promag — COMMENTED** [review]
ACK 8e08d005989c6b5f7f05e0a1e0ba84f544a76d01.

**Comment by jonasschnelli** [comment]
utACK 8e08d005989c6b5f7f05e0a1e0ba84f544a76d01

**Pull request merged**
