### PR TITLE
Fix assertion in CKey::SignCompact

### LINKED ISSUE #15286: Incorrect or duplicate assertion in key.cpp signing code
The following assertion seems redundant. Is it a mistake? Two lines prior the same assertion is made, and the value being asserted doesn't appear to change in-between. However the next line asserts a condition on a different variable which differs by only one letter. Is the referenced line a duplicate assertion of `ret` and therefore redundant, or is it supposed to be `assert(rec)`?

https://github.com/bitcoin/bitcoin/blob/7275365c9bc7e7ebd6bbf7dcb251946aac44b5de/src/key.cpp#L247-L251

### PR DESCRIPTION
**Pull request by promag**
Fixes #15286.

### CODE REVIEW

**Comment by laanwj** [comment]
utACK 3617f117394285c87c395a0ccc92941977f97019

**Comment by practicalswift** [comment]
utACK 3617f117394285c87c395a0ccc92941977f97019

This is why I love `[[nodiscard]]` :-)

**Comment by Empact** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/15299/commits/3617f117394285c87c395a0ccc92941977f97019

**Comment by maaku** [comment]
Already merged, but FWIW this is just as redundant. `secp256k1_ecdsa_recoverable_signature_serialize_compact` always returns 1; the serialization function semantics are that they never fail. No check is required.

**Pull request merged**
