### PR TITLE
doc: update maintainer list in REVIEWERS

### PR DESCRIPTION
**Pull request by fanquake**

### CODE REVIEW

**Comment by glozow** [comment]
LGTM

**Comment by michaelfolkson** [comment]
ACK 3fadafd0db0adb995cf3a462caca1e336ebdc1ee

**Comment by hebasto** [comment]
Should @jonasschnelli's key `32EE5C4C3FA15CCADB46ABE529D4BCB6416F53EC` and @meshcollider's key `CA03882CB1FC067B5D3ACFE4D300116E1C875A3D` be also removed from [contrib/verify-commits/trusted-keys](https://github.com/bitcoin/bitcoin/blob/master/contrib/verify-commits/trusted-keys)?

**Comment by MarcoFalke** [comment]
See https://github.com/bitcoin-core/bitcoincore.org/pull/876 on the process

**Comment by hebasto** [comment]
> See [bitcoin-core/bitcoincore.org#876](https://github.com/bitcoin-core/bitcoincore.org/pull/876) on the process

Thanks! But https://github.com/bitcoin-core/bitcoincore.org/pull/876 does not touch [contrib/verify-commits/trusted-keys](https://github.com/bitcoin/bitcoin/blob/master/contrib/verify-commits/trusted-keys) in _this_ repo.

**Comment by MarcoFalke** [comment]
Right, someone would need to open a pull request.

**Comment by hebasto** [comment]
> Right, someone would need to open a pull request.

Done in #25197.

**Pull request merged**
