### PR TITLE
Speedy trial activation parameters for Taproot

### PR DESCRIPTION
**Pull request by achow101**
Adds the activation parameters for taproot as specified in https://github.com/bitcoin/bips/pull/1104

### CODE REVIEW

**Review by luke-jr — CHANGES_REQUESTED** [review]
Concept NACK. Devs have no authority to make consensus changes against community consensus.

**Comment by JeremyRubin** [comment]
ACK these match the BIP

**Comment by ajtowns** [comment]
Maybe include the (expected) dates as comments? That's been done in the past, see #8937. ACK otherwise.

**Comment by achow101** [comment]
> Maybe include the (expected) dates as comments? That's been done in the past, see #8937. ACK otherwise.

Done.

**Comment by JeremyRubin** [comment]
re-ack 96608b1

**Comment by JeremyRubin** [comment]
reack f979b3237f1cfc28f9c4ccb07beab558d5357a55

**Comment by gmaxwell** [comment]
utACK f979b3237f1cfc28f9c4ccb07beab558d5357a55

As per: https://github.com/bitcoin/bitcoin/pull/21377#issuecomment-819792337

**Comment by ajtowns** [comment]
ACK f979b3237f1cfc28f9c4ccb07beab558d5357a55

**Comment by ajtowns** [comment]
> Concept NACK. Devs have no authority to make consensus changes against community consensus.

Note that luke-jr is [on the record](http://gnusha.org/uasf/2021-03-02.log) as committing to NACK lot=false proposals in general, in accordance with his [list post on the topic](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2021-February/018498.html):

> 11:08 < luke-jr> personally I plan to NACK any LOT=False; but I doubt I would need to at this point (devs pushing against LOT=True seem to be off shed-painting other bad ideas now)
> 12:42 < hashcash> make a PR for core with LOT=false
> 12:42 < luke-jr> hashcash: I will NACK it

**Comment by instagibbs** [comment]
"needs backport" (obviously)

**Comment by instagibbs** [comment]
ACK f979b32
in it matches the BIP draft

**Comment by clarkmoody** [comment]
ACK f979b32

**Comment by Sjors** [comment]
ACK f979b3237f1cfc28f9c4ccb07beab558d5357a55

<details><summary>Fancy PGP signature</summary>
<p>
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

ACK f979b3237f1cfc28f9c4ccb07beab558d5357a55
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEE7ZvfetalXiMuhFJCV/+b28wwEAkFAmB37eMACgkQV/+b28ww
EAn+cw/+KXnEpGiRXlWJlUSGxyASQn9mF5iJR46E50yqOJdRaEfGDOnViRfXluZY
xzgehN5rd9/HcXABD3lvRPQUEnI0NLtVdue8EcWLeRfyaNV5Tu/hYXHSw1DtO1tw
ne9WR62+t71fVsVU1jHWL8fEr4wcwBnvfVBAw8hN8WrF6MICuTdIYTge5F3DLtAj
L5Bj8fDbwLxmEtuJBFTXMq2yHzObzvOh47cI9pKO+ylQYZjVF03iybPFl2woBxV3
+cWZQ4SkBzMW0hCWAeHLbWpkrnrwuO+Bb8hWcVeD2MdMvUDpJtn9cOiRajb+LviW
mrcxzOZU4/asEXgUa6XZZrrFeRfWq4XisEm7w+PgUNJC0z6xCBu+PLJyqNcC4xIR
2BGr/VYxidrMDNMbh/YNX6HfRecXfaOxzgVpnb0hwZDr6bQrNgYU4wLBnTYcUTiE
iMtnvd6uBu/KjGsDBkRPKvxBvKQmHSxoleEQmmPX3bYfy7e++YKMApe++u4dWirk
aadHx2Us9PVpIdCH/TKDhxKuYFcgI0EmaVUkALRa/ClHp9WBpdlCzqivB8TSR14F
kKKd88xMhhNnynJSW4NYhflDQ7FV5ljMQR9xEnQ5UWN2mxFYPu3bw56IHTgGcT8c
6kRYQSo/FVceGI4Sg1mukZZMVaMlkvo+MFejDjuAxn2+Ig07C0Q=
=pEwh
-----END PGP SIGNATURE-----
</p>
</details>

**Review by jonatack — APPROVED** [review]
utACK f979b3237f1cfc28f9c4ccb07beab558d5357a55 verified with the BIP draft

```ruby
>> Time.at(1619222400).to_time.utc
=> 2021-04-24 00:00:00 UTC
>> Time.at(1628640000).to_time.utc
=> 2021-08-11 00:00:00 UTC
```

**Comment by jnewbery** [comment]
ACK f979b3237f1cfc28f9c4ccb07beab558d5357a55

**Comment by hsjoberg** [comment]
Concept ACK
Code review ACK f979b3237f1cfc28f9c4ccb07beab558d5357a55

**Comment by benthecarman** [comment]
ACK f979b3237f1cfc28f9c4ccb07beab558d5357a55

**Comment by leishman** [comment]
ACK f979b3237f1cfc28f9c4ccb07beab558d5357a55

**Comment by fanquake** [comment]
Being backported in #21701.

**Comment by Kisha56** [comment]
Hello world I'm Kisha147

**Pull request merged**
