### PR TITLE
doc: Correction for VerifyTaprootCommitment comments

### PR DESCRIPTION
**Pull request by roconnor-blockstream**
According to BIP-341, 'p' is called the taproot *internal* key, not inner key.

### CODE REVIEW

**Comment by michaelfolkson** [comment]
ACK 56325c9be7a6ea3717efdf2ec5f244a659f26452

Only three comments in interpreter.cpp that refer to "inner key", all of them replaced in this PR. No reference to "inner key" in BIP 341

**Review by theStack — COMMENTED** [review]
Note that there are also some occurences of "inner pubkey" in the functional taproot test and a test framework script helper module that could be tackled in this PR:
```
$ git grep "inner pubkey"
src/script/interpreter.cpp:    //! The inner pubkey (x-only, so no Y coordinate parity).
src/script/interpreter.cpp:    // Compute the tweak from the Merkle root and the inner pubkey.
src/script/interpreter.cpp:    // Verify that the output pubkey matches the tweaked inner pubkey, after correcting for parity.
test/functional/feature_taproot.py:    # The inner pubkey for a taproot script path spend (32 bytes).
test/functional/feature_taproot.py:    # The negation flag of the inner pubkey for a taproot script path spend.
test/functional/feature_taproot.py:    # Test that bitflips in the inner pubkey invalidate it.
test/functional/test_framework/script.py:# - inner_pubkey: the inner pubkey (32 bytes)
```

**Review by benthecarman — APPROVED** [review]
ACK 6a0a6e7d0509e48a6cc08c6604a25671d5f8cab4

**Review by theStack — APPROVED** [review]
ACK 6a0a6e7d0509e48a6cc08c6604a25671d5f8cab4

**Comment by sipa** [comment]
ACK 6a0a6e7d0509e48a6cc08c6604a25671d5f8cab4

I guess I'll need to make this change in #21365 as well.

**Pull request merged**
