### PR TITLE
Remove unused variable. Remove accidental trailing semicolons in Python code

### PR DESCRIPTION
**Pull request by practicalswift**

### CODE REVIEW

**Review by dcousens — APPROVED** [review]

**Comment by sipa** [comment]
utACK

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/10107/commits/85de9d474b13a0e6ad681848e5497d02e00dd644

**Comment by fanquake** [comment]
ACK 85de9d4

**Comment by jnewbery** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/10107/commits/85de9d474b13a0e6ad681848e5497d02e00dd644

**Pull request merged**
