### PR TITLE
Remove base58 hard-coding

### PR DESCRIPTION
**Pull request by penguin1333**
Not a big change, just more efficient. It was hard coded, and though it works either way, it's better than it being hard coded.

### CODE REVIEW

**Comment by luke-jr** [comment]
More efficient how? If anything, this would be *less* efficient.

**Comment by prestotron** [comment]
@luke-jr

This isn't less efficient. We're never going to change it, so why keep it hard coded? It's bad practice.

But either way, it works the same. So I'd just say to merge it if you want more "pretty" code.

**Comment by prestotron** [comment]
Here's an example:

You have 1 apple.

You want to count it 3 times.

You could say "1 apple + 1 apple + 1 apple"

or you could store it in say, a variable called "a" and do "a*3"

**Comment by paveljanik** [comment]
NACK
If you want to have prettier code, why not rewrite the whole last phase of the function? Why skip zeroes and prefill with 1s at all?

**Comment by prestotron** [comment]
I guess that's true, but it wouldn't hurt to merge would it? It's been requested and it makes things neater imo. 

But of course, that's arguable. I don't feel like arguing because it's a waste of time and I already probably agree with you. I just thought "why not?". Haha

**Comment by laanwj** [comment]
I have no opinion on whether this is better or not. Something can be said for both sides.

But I feel this discussion is a waste of time, please don't make changes if they don't solve a problem, we're barged with pull requests as it is.

**Pull request closed without merging**
