### PR TITLE
build: enable unused member function diagnostic

### LINKED ISSUE #19702: Enable unused member function diagnostic by default
Enable unused member function diagnostic by default.

Clang has a nice compiler diagnostic `-Wunused-member-function` which is good at catching accidentally dead/unreachable code.

While dead/unreachable code is most often harmless from a security/robustness perspective there are instances where dead/unreachable code may be an indication of more serious issues. Enabling this diagnostic allows us to find such cases and reason about which is which.

See concept ACKs for enabling this diagnostic in #19015.

Current warnings in `master` that would need to be addressed when enabling this diagnostic:

```
index/blockfilterindex.cpp:54:5: warning: unused member function 'DBHeightKey' [-Wunused-member-function]
script/bitcoinconsensus.cpp:50:9: warning: unused member function 'GetType' [-Wunused-member-function]
```

#### Useful skills:

Basic understanding of C++. See #19015 for an example on how to enable a compiler diagnostic by editing `configure.ac`.

#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

### PR DESCRIPTION
**Pull request by Zero-1729**
This PR enables the `-Wunused-member-function` compiler diagnostic, as discussed in #19702.

> **Notice**: The `unused-member-function` diagnostic is only available on clang. Therefore, clang should be used to test this PR.

- [x] Include the `-Wunused-member-function`diagnostic in `./configure.ac`. (ed69213c2b2a99023bdee5168614cb8b71990f5f)
- [x] Resolve the reported warnings. (819d03b932134ee91df3b0fe98a481a331ce57bf)

Currently, enabling this flag no longer reports the following warnings:

> **Note**: output from `make 2>&1 | grep "warning: unused member function" | sort | uniq -c`

```
1 index/blockfilterindex.cpp:54:5: warning: unused member function 'DBHeightKey' [-Wunused-member-function]
2 script/bitcoinconsensus.cpp:50:9: warning: unused member function 'GetType' [-Wunused-member-function]
1 test/util_tests.cpp:1975:14: warning: unused member function 'operator=' [-Wunused-member-function]
```

All tests have passed locally (from `make check` & `src/test/test_bitcoin`).

This PR closes #19702.

### CODE REVIEW

**Comment by practicalswift** [comment]
Concept ACK

Thanks for doing this @Zero-1729! :)

**Comment by pox** [comment]
Tested ACK 0791ffd

Tested by building commit ed69213 (where warning is enabled) with clang 10 and seeing the following warnings:

```
  CXX      index/libbitcoin_server_a-blockfilterindex.o
index/blockfilterindex.cpp:54:5: warning: unused member function 'DBHeightKey' [-Wunused-member-function]
    DBHeightKey() : height(0) {}
    ^
1 warning generated.
...
script/bitcoinconsensus.cpp:50:9: warning: unused member function 'GetType' [-Wunused-member-function]
    int GetType() const { return m_type; }
        ^
1 warning generated.
...
test/util_tests.cpp:1975:14: warning: member function 'operator=' is not needed and will not be emitted [-Wunneeded-member-function]
    Tracker& operator=(Tracker&& t) noexcept
             ^

```

Then rebuilt commit 0791ffd to see warnings are gone.
Also searched manually for the removed functions in the codebase to make sure they're not referenced by any uncompiled code.

Thanks for not squashing the commits and making it easier to recreate the warnings.

**Comment by practicalswift** [comment]
ACK 0791ffda1772930cf3db440333b5bbc559699172 -- patch looks correct

Thanks for yet another nice contribution @Zero-1729 :)

**Comment by tryphe** [comment]
ACK 0791ffda1772930cf3db440333b5bbc559699172. Neutral on the idea of refactoring and changing the build in one PR, but the changes look good and are simple enough.

**Comment by Zero-1729** [comment]
Not sure why the CI Build for  0791ffda1772930cf3db440333b5bbc559699172 failed, so I squashed the last three commits (0791ffda1772930cf3db440333b5bbc559699172, 819df4ca714a1fc18426a69cd0352857c78a5201, and 9885ced065da082c10f49927d6c4416de3fd359a) into 819d03b932134ee91df3b0fe98a481a331ce57bf and everything now checks out.

Thanks @practicalswift and @tryphe for reviewing, and @pox for testing :+1:.

**Comment by practicalswift** [comment]
ACK 819d03b932134ee91df3b0fe98a481a331ce57bf - patch still looks correct :)

**Comment by MarcoFalke** [comment]
ACK 819d03b932134ee91df3b0fe98a481a331ce57bf

**Review by theStack — APPROVED** [review]
tested ACK 819d03b932134ee91df3b0fe98a481a331ce57bf
Verified that re-running autogen.sh after the first commit adds `-Wunused-member-function` to the `CXXFLAGS` and building detects all unused member functions that are removed in the second commit (using clang 3.8.0 here).

**Comment by practicalswift** [comment]
@pox @tryphe Would you mind re-reviewing @Zero-1729's updated version of this PR? :)

**Comment by pox** [comment]
Tested ACK 819d03b932134ee91df3b0fe98a481a331ce57bf with clang after `make clean`. No unused member function warnings.

**Comment by Zero-1729** [comment]
@tryphe have you had time to re-review?

**Comment by kristapsk** [comment]
Checked out commit ed69213c2b2a99023bdee5168614cb8b71990f5f, can't reproduce warnings, GCC 8.4.0.

**Comment by theStack** [comment]
> Checked out commit [ed69213](https://github.com/bitcoin/bitcoin/commit/ed69213c2b2a99023bdee5168614cb8b71990f5f), can't reproduce warnings, GCC 8.4.0.

I remember I also tried to reproduce this with GCC first, but then I found out that this diagnostic is only available on clang, not on GCC. (Couldn't find out though which exact clang version introduced it.) Maybe a fact that's worth mentioning in the PR description.

**Comment by Zero-1729** [comment]
@theStack thanks for pointing that out. I just updated the PR description with a notice to let others know about this.

**Comment by Zero-1729** [comment]
@kristapsk have you tried testing ed69213 with clang?

**Comment by Zero-1729** [comment]
@kristapsk did you eventually get round to testing ed69213?

**Pull request merged**
