### PR TITLE
clarify obscure uses of EvalScript()

### PR DESCRIPTION
**Pull request by ghost**
The 3rd argument of EvalScript() is the unsigned int flags, not a bool.

### CODE REVIEW

**Comment by petertodd** [comment]
utACK

**Comment by fanquake** [comment]
Tested ACK

**Comment by sipa** [comment]
untested ACK

**Comment by laanwj** [comment]
```
03ef452e39dc6bfdd48d3631d1e9c561c34f48fcc63133c3e7b3b3cb747c05b3  bitcoind.a99ef7d.stripped
03ef452e39dc6bfdd48d3631d1e9c561c34f48fcc63133c3e7b3b3cb747c05b3  bitcoind.de236f5.stripped
```
ACK

**Pull request merged**
