### PR TITLE
test: Unify testing setups for fuzz, bench, and unit tests

### PR DESCRIPTION
**Pull request by maflcko**
Now that the fuzz tests can use the BasicTestingSetup [1], do the same for bench.

Also move some duplicate code to a common "test/util" module.

[1]:  fuzz: Link BasicTestingSetup (shared with unit tests) #15504

### CODE REVIEW

**Comment by practicalswift** [comment]
Concept ACK

Nice!

**Comment by jonatack** [comment]
Partial ACK https://github.com/bitcoin/bitcoin/pull/15788/commits/faf400077d0144363c2dd24187431d958fb149a9

Reviewed changes, recompiled, ran unit tests, ran benchmarks. Todo: Run fuzzing.

**Review by jonatack — COMMENTED** [review]
ACK https://github.com/bitcoin/bitcoin/pull/15788/commits/faf400077d0144363c2dd24187431d958fb149a9

Reviewed changes, recompiled, ran unit tests and [benchmarks](https://github.com/jonatack/bitcoin-development/blob/master/bitcoin-benchmarks/2019-04-12-bitcoin-master-benchmarks.txt). Todo: Run fuzzing.

**Comment by jonatack** [comment]
FWIW I haven't managed to get the fuzzing to run -- so cannot confirm or infirm that aspect wrt this PR. [Gist here](https://gist.github.com/jonatack/5179fd1842414147c2e691ba0e871310). Pointers welcome.

**Comment by MarcoFalke** [comment]
Fuzzing shouldn't be changed by this pr, but it would help if you posted your configure line (and config log) as well as the output of make. See also doc/fuzzing

**Pull request merged**
