### PR TITLE
tests: add a BasicTestingSetup and apply to all tests

### PR DESCRIPTION
**Pull request by laanwj**
Make sure that chainparams and logging is properly initialized. Doing this for every test may be overkill, but this initialization is so simple that that does not matter.

This should fix the travis issues.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Tested locally. Worked fine.
Let's see what travis means. Also started a gitian build to more test env. diversity.

**Comment by Diapolo** [comment]
This doesn't apply to Qt tests?

**Comment by laanwj** [comment]
@diapolo I don't think so, nothing changed there recently did it?

**Comment by Diapolo** [comment]
I was just asking, because it seems you updated all core testfiles, but not the Qt ones.

**Comment by laanwj** [comment]
@diapolo Just checked. Last change to qt tests is 5 weeks ago and had to do with payment requests. There were no test reordering or initialization changes for qt.

**Comment by Diapolo** [comment]
Alright, thanks for verifying :)!

**Comment by jonasschnelli** [comment]
For the records. Gitian was also happy with this:
* https://builds.jonasschnelli.ch/pulls/5883/build-linux.log
* https://builds.jonasschnelli.ch/pulls/5883/build-osx.log
* https://builds.jonasschnelli.ch/pulls/5883/build-win.log

**Pull request merged**
