### PR TITLE
test: Add txindex migration test

### PR DESCRIPTION
**Pull request by maflcko**
Test for #22626

### CODE REVIEW

**Comment by theStack** [comment]
Concept ACK

**Comment by duncandean** [comment]
Concept ACK

**Comment by practicalswift** [comment]
Concept ACK (obviously :))

**Comment by MarcoFalke** [comment]
Removed now-redundant `sync_all`.

**Review by theStack — APPROVED** [review]
Tested ACK fadc4c72723d67a59d80d843c85b090ae22b463b 🌁 
(code-reviewed test, ran it under Debian bookworm/sid, with downloaded binary previous releases v0.16.3 and v0.20.1)

**Comment by hebasto** [comment]
See #23514.

**Pull request merged**
