### PR TITLE
[26.x] backports and final changes for v26.1rc2

### PR DESCRIPTION
**Pull request by glozow**
Includes:
- #29357
- #29412 
- #29524 
- #29510
- #29529 

Also does:
- update to release notes
- bump to rc2
- manpages
- (no changes to bitcoin.conf)

### CODE REVIEW

**Comment by achow101** [comment]
I think #29510 should be backported too, once it's merged.

**Review by hebasto — APPROVED** [review]
ACK 4ac0eb543d028379bb2b86ab08bbbb2f9f48d5b1.

**Comment by glozow** [comment]
Noting changes for #29412:
- `LogDebug` to `LogPrint`
- `GetSerializeSize(TX_NO_WITNESS(tx))` to `GetSerializeSize(tx, PROTOCOL_VERSION | SERIALIZE_TRANSACTION_NO_WITNESS)`
- Didn't add 1ed2c9829700054526156297552bb47230406098, modified validation_tests to convert transaction hash data as needed. (26.x doesn't have transaction_identifier.h)

**Comment by fanquake** [comment]
Can you also add #29529.

**Comment by glozow** [comment]
Added #29529. Also updated release notes and added final changes for rc2.

**Comment by achow101** [comment]
ACK c68d4d0ac5b8537ba5e1c0c512b807768e1c5c1f

**Pull request merged**
