### PR TITLE
guix: use same commit for codesigning time-machine

### PR DESCRIPTION
**Pull request by fanquake**
The time machines should be updated in lockstep.

### CODE REVIEW

**Review by hebasto — APPROVED** [review]
ACK 29862bdd402112a98d5da08cb9909bd427b955ad, I have reviewed the code and it looks OK, I agree it can be merged.

**Comment by gruve-p** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/24484/commits/29862bdd402112a98d5da08cb9909bd427b955ad

**Comment by achow101** [comment]
ACK 29862bdd402112a98d5da08cb9909bd427b955ad

**Comment by fanquake** [comment]
Backported in #24485.

**Pull request merged**
