### PR TITLE
Remove useless string initializations

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by bolekC — COMMENTED** [review]
ntACK 4893f5c
Not sure but probably compiler will not optimize this so small improvement in performance is possible with this improvement.

**Comment by fanquake** [comment]
Needs a rebase.

**Comment by practicalswift** [comment]
Concept ACK, but should ideally be done as a `scripted-diff`. Also please squash and add a PR body :-)

**Comment by laanwj** [comment]
Needs rebase/squash to get rid of the merge commit. If you're unsure how to do this, see https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#squashing-commits .

**Review by dcousens — APPROVED** [review]

**Comment by practicalswift** [comment]
This scripted-diff will fix these:

```
for F in $(git grep -lE 'std::string [a-zA-Z]*( |)=( |)"";'); do
    sed -i -E 's/(std::string [a-zA-Z]*)( |)=( |)"";/\1;/g' $F
done
```

**Comment by jonasschnelli** [comment]
utACK 19ac86e2063432fca1f21fd3ef9770e7bde5d0ff

**Pull request merged**
