### PR TITLE
Globals: Pass Consensus::Params through CBlockTreeDB::LoadBlockIndexGuts()

### PR DESCRIPTION
**Pull request by jtimon**
Part of #7829

### CODE REVIEW

**Comment by mrbandrews** [comment]
Code review ACK

**Comment by jtimon** [comment]
Updated fixing @mrbandrews 's nit.

**Comment by jtimon** [comment]
Needed rebase after renaming main.o, see #9260 (although needed, the rebase was clean in this case)

**Comment by jtimon** [comment]
Needed rebase

**Comment by laanwj** [comment]
utACK b324b28

**Pull request merged**
