### PR TITLE
[tests] Add libFuzzer support

### PR DESCRIPTION
**Pull request by practicalswift**
Add `libFuzzer` support.

As discussed in [issue #10364](https://github.com/bitcoin/bitcoin/issues/10364#issuecomment-300000902).

See http://llvm.org/docs/LibFuzzer.html#fuzzer-usage for usage instructions.

### CODE REVIEW

**Comment by practicalswift** [comment]
Related pull request: #10440 ("Speed up fuzzing by ~200x when using afl-fuzz").

**Comment by laanwj** [comment]
Concept ACK

**Comment by practicalswift** [comment]
Friendly ping @laanwj or @jonasschnelli - is this one getting ready for merge? Would help a lot to have `libFuzzer` support out-of-the-box :-)

**Comment by laanwj** [comment]
Looks good to me, only touches bitcoin_fuzzy anyhow.
utACK f3ba869

**Pull request merged**
