### PR TITLE
refactor: replace RecursiveMutex `m_cs_banned` with Mutex (and rename)

### PR DESCRIPTION
**Pull request by w0xlt**
This PR is related to #19303 and gets rid of the RecursiveMutex `m_cs_banned`.

The last commit prevents double lock for `m_banned_mutex` by changing `BanMan::GetBanned()` to lock it only after `BanMan::SweepBanned()` releases it.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
The second commit is UB. Can you explain why the third commit is safe to do?

**Comment by w0xlt** [comment]
What does UB mean?
The second commit follows the same format adopted in cac8366 .

> Can you explain why the third commit is safe to do?

The third commit is necessary to avoid double lock error for 'm_banned_mutex'.
`BanMan::SweepBanned()` is only called internally in `src/banman.cpp`.

1) It is called in `BanMan::BanMan` but this function does not acquire lock, so there is no need to change it.
2) It is called in `BanMan::DumpBanlist` and this is the same case as above.
3) `BanMan::GetBanned` acquired lock for mutex before calling `BanMan::SweepBanned` so a double lock occurred. With `RecursiveMutex`, it wasn´t a problem. But using `mutex`, the lock acquisiton needs to be moved after `BanMan::SweepBanned` is completed and its lock released.

**Comment by jonatack** [comment]
> What does UB mean?

Undefined behavior. See https://en.cppreference.com/w/cpp/language/ub and https://bitcoincore.reviews/17639 for more.

**Comment by MarcoFalke** [comment]
> The third commit is necessary

I understand that it is necessary to avoid the UB. I was asking why it is safe to release the lock in between.

**Comment by shaavan** [comment]
> I was asking why it is safe to release the lock in between.

The way I understand the risk behind releasing a lock in between functions is, say:
1. **SweepBanned** is called.
2. **LOCK** is set up, `m_banned` is updated, **LOCK** is released.
3. GetBanned sets up **LOCK**; the value of `m_banned` is copied to banmap.

However, say another function acquires lock between steps 2 and 3 and updates the value of m_banned somehow, then we will get a false value return for banmap in step 3.

I shall take another look at the codebase and see if this scenario is possible.

**Comment by hebasto** [comment]
I'd suggest to apply [Clang Thread Safety Analysis annotations](https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md#threads-and-synchronization).
In particular, `void SweepBanned() EXCLUSIVE_LOCKS_REQUIRED(m_banned_mutex);`.

**Comment by hebasto** [comment]
Please consider an alternative #24097.

@w0xlt I've taken your commits into #24097.

**Comment by w0xlt** [comment]
Closed in favor of #24097.

**Pull request closed without merging**
