### PR TITLE
script: Add trusted key for hebasto

### PR DESCRIPTION
**Pull request by hebasto**
It is assumed that my responsibility will be limited to the [GUI repo](https://github.com/bitcoin-core/gui).

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Thanks and Concept ACK, happy to welcome you as a maintainer. It is good to see your contributions in the areas where we previously had a lack of contributors and reviewers!

**Comment by MarcoFalke** [comment]
Once (and if) this is merged, you can refer to the doc on how to setup the merge script: https://github.com/bitcoin-core/bitcoin-maintainer-tools/pull/89

**Review by jarolrod — COMMENTED** [review]
ACK 55d85834ccd73aa2f93cf9a81523cb747973346e 🥃

See you around the GUI  ♪┏(・o･)┛♪┗ ( ･o･) ┓♪

**Comment by S3RK** [comment]
There is also a list of maintainers in [REVIEWERS](https://github.com/bitcoin/bitcoin/blob/2e9031f95d2bf8d0134103a10a8a2162975f1259/REVIEWERS)

**Comment by promag** [comment]
Concept ACK 🥳

**Comment by laanwj** [comment]
Welcome !

> It is assumed that my responsibility will be limited to the GUI repo.

Yes, for now !
I mean don't forget I started as GUI maintainer as well :sweat_smile: 

ACK 55d85834ccd73aa2f93cf9a81523cb747973346e
This matches the key I have locally available from you.

**Comment by MarcoFalke** [comment]
matches the key I have locally ACK 55d85834ccd73aa2f93cf9a81523cb747973346e 🍪

<details><summary>Show signature and timestamp</summary>

Signature:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

matches the key I have locally ACK 55d85834ccd73aa2f93cf9a81523cb747973346e 🍪
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEE+rVPoUahrI9sLGYTzit1aX5ppUgFAlwqrYAACgkQzit1aX5p
pUhiPwv+KbcF/m8130t+dCWFuXSh7qzRGuIOF6Nti0FtwGCSKHmd9HjNYHDkMCWi
zjsH1rhlbMjIQ2ZpGDza7N9PjQNgNX+jqA7U4YDrJxH/DeH3gRz2LiUVxHgZbvBm
0gQsX1QWCaQrlR/0whkurXW8/tSo8WCFq6X1wsYV0MhzDR+XYgVJDFPCiJosGoFe
xF4xMfi9QE0eOAdUj8IH6M7fPlEszmh/FvTNweQkKI8Hdpcsi5MwwvCD0pZ2HJ8H
WttJpuG3+9TIC598Q2Vjr1LMUcCu5OnQ19DJ9kTiPzwM8EBxn0YroaPbMsySk074
Uo9vCPgLmLg3zhvgFzfs38nuKe8+jLx3mjGpOODTmvL08sQ5r8mkdLUIfxjxI7GC
cMZJ6GC+ODrroQBTWr90iSN44fONRtp/gJnJbSsCWRtaitO3LKkUHwEWjp9/dDoj
g7uSd/aRcDxVyjh4Yya2XVL2iuJO3UHmxFIA68hVlyP957NxcQ7mDuv8u+Ab1ZMT
FQ9IIiEi
=y0h2
-----END PGP SIGNATURE-----
```

[Timestamp of file with hash `7125c3f69e613d7bb1aa040f5312b8f8686cb6e34a80f8a78515f8a42f42e0a8  -`](https://opentimestamps.org/info/?004f70656e54696d657374616d7073000050726f6f6600bf89e2e884e8929401087125c3f69e613d7bb1aa040f5312b8f8686cb6e34a80f8a78515f8a42f42e0a8f0103aac31479c2d758c731fb6b79fbd431208fff010673e595c3ef9ee4515821f41d5fd670908f1046074630bf0083023b1a6002dfe730083dfe30d2ef90c8e292868747470733a2f2f66696e6e65792e63616c656e6461722e657465726e69747977616c6c2e636f6dfff010693e87cb231cc12dc8c57e413ae7c60b08f104607470e5f008cb883b58ecd2d2af0083dfe30d2ef90c8e2c2b68747470733a2f2f626f622e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267fff0107008034e66cd968f4a9131ed95317e1308f104607470e4f0088504d913f732d2a10083dfe30d2ef90c8e2e2d68747470733a2f2f616c6963652e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267f010fcdfaee9f46ffaa05cafb270e508d9ec08f104607470e5f00865702c1d5949ec5b0083dfe30d2ef90c8e232268747470733a2f2f6274632e63616c656e6461722e636174616c6c6178792e636f6d)

</details>

**Pull request merged**
