### PR TITLE
Add seed.btc.petertodd.org to mainnet DNS seeds

### PR DESCRIPTION
**Pull request by petertodd**
Identical setup to my testnet DNS seed, but for mainnet.

### CODE REVIEW

**Comment by cdecker** [comment]
ACK 3b4dd2a6768536be3a7db21353f43ba614c17377

Nice to see this added. I've been monitoring the seed for a while so let me add some additional data about the seed: it returns about 50% reachable nodes and (from my vantage point) has ~100ms latency. The stale rate is a bit high-ish, but that might be easy to fix.

**Comment by petertodd** [comment]
Thanks! Didn't know anyone else was monitoring it.

I reset the database on it a week ago or so when I upgrading the seeder to @sipa's latest bitcoin-seeder code, so possibly that's why the stale rate is a bit high; maybe needs time to collect more data? Specifically it's running commit https://github.com/sipa/bitcoin-seeder/commit/d54f39a1eeb7ddb0638396755d3a76abbd4c41ef, with one small patch to also return full-RBF flagging nodes (as does my testnet seed).

**Comment by cdecker** [comment]
Yeah, I added it some time ago to http://bitcoinstats.com/network/dns-servers/ :wink:

**Comment by laanwj** [comment]
Concept ACK.

I suppose you sign off on the [dnsseed policy](https://github.com/bitcoin/bitcoin/blob/master/doc/dnsseed-policy.md)?

**Comment by petertodd** [comment]
@laanwj Yup, ACK https://github.com/bitcoin/bitcoin/blob/99963b938ffb4ad37f4a9d275998bf1a9dc11e64/doc/dnsseed-policy.md

**Review by gmaxwell — APPROVED** [review]
utACK

**Comment by jonasschnelli** [comment]
Tested ACK.
IPv4 and IPv6 works. Tried a couple of IPs retrived over the seeder. Crawler seems to be up to date.

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/9805/commits/3b4dd2a6768536be3a7db21353f43ba614c17377

**Pull request merged**
