### PR TITLE
Change "insane" to "excessive" (referring to high fees) in text strings and identifiers

### PR DESCRIPTION
**Pull request by daira**
This is clearer and more meaningful, as well as avoiding ableist langage (see http://www.autistichoya.com/p/ableist-words-and-terms-to-avoid.html ).

Note that this will also require translation changes in Transifex for the key
"A fee higher than %1 is considered an insanely high fee." which is now
"A fee higher than %1 is considered an excessive fee."

Signed-off-by: Daira Hopwood daira@jacaranda.org

### CODE REVIEW

**Comment by daira** [comment]
There are 10 languages on Transifex that have a translation for the changed key; I'm happy to change those translations if this pull request is accepted.

**Comment by gmaxwell** [comment]
Excessive is misleading.  I would be glad if we changed to avoid any language that was derogatory towards anyone, but I think a different word would be better.  Paying $10 for a soft drink would be excessive especially if one was available down the street for $2,  paying $10,000 would be completely nonsensical. It's the latter the software is trying to prevent. (It doesn't prevent merely excessive)

Would nonsensical be acceptable?

**Comment by daira** [comment]
Note also that there's a source-level backward incompatibility for anything compiled against Bitcoin Core that relies on ``WalletModel::InsaneFee``. (There's no binary incompatibility since ``WalletModel::ExcessiveFee`` will take the same integer value.) If necessary I can add an ``InsaneFee = ExcessiveFee`` alias to avoid this.

**Comment by daira** [comment]
Nonsensical or absurd would be fine. I vote for "absurd", in that case.

**Comment by gmaxwell** [comment]
Absurd sounds great to me, but you might want to wait a bit to see if anyone else comments (I don't want to make you iterate on this if other people have opinions that differ greatly from mine).

I don't think we mind the incompatibility, though we are library structured, it's not a supported thing for external applications yet. (Oh, and I seemed to fail to say in the first time: thanks for taking a look and commenting. I'm always glad to have more perspectives; as soon as you pointed out the implication I realized I'd been careless in my word choice when I introduced the original language).

**Comment by luke-jr** [comment]
Another option is "inordinate"

**Comment by laanwj** [comment]
I didn't know of the word inordinate, so I suppose other non-native English speaking people can have problems with it.

So +1 for absurd.

**Comment by MineForeman** [comment]
How about "excessive"?

Absurd sounds a bit excessive a warning to me.

**Comment by daira** [comment]
@MineForeman : @gmaxwell said that "excessive" was not the intended meaning, since the check doesn't prevent fees that are merely excessive. The consensus seems to be for "absurdly high" so I'll go with that.

**Comment by daira** [comment]
I also checked the other languages on Transifex (there are more than 10 with a translation for this string; I had missed some):

French:
Des frais supérieurs à %1 sont considérés comme follement élevés.
Fees higher than 1% are considered {wildly, foolishly} high.
Seems fine.

German:
https://www.transifex.com/projects/p/bitcoin/viewstrings/#de/qt-translation-010x/37434907?q=insanely
Eine höhere Gebühr als %1 wird als unsinnig hohe Gebühr angesehen.
A fee higher than 1% is considered an {absurdly, nonsensically} high fee.
This is fine.

Danish:
Et gebyr højere end %1 anses som et vanvittigt højt gebyr.
A fee higher than 1% is considered as a {crazily, insanely} high fee.
Eek, this may need retranslation by a Danish speaker.
http://ordnet.dk/ddo/ordbog?query=vanvittig makes it clear that this word has undesired mental health connotations.

Dutch:
Transactiekosten hoger dan %1 worden gezien als waanzinnig hoog.
Transaction costs are higher than 1% are considered {outrageously, insanely, delusionally} high.
This probably also needs retranslation.
(see http://www.etymologiebank.nl/trefwoord/waanzinnig )

Spanish:
https://www.transifex.com/projects/p/bitcoin/viewstrings/#es/qt-translation-010x/37434907?q=insanely
Una comisión mayor de 1% se considera increíblemente alta.
A fee higher than 1% is considered incredibly high.
Completely fine.

Catalan:
https://www.transifex.com/projects/p/bitcoin/viewstrings/#ca/qt-translation-010x/37434907?q=insanely
https://www.transifex.com/projects/p/bitcoin/viewstrings/#ca_ES/qt-translation-010x/37434907?q=insanely
Una comissió superior a %1 es considera una comissió excessiva.
A fee higher than 1% is considered an excessive fee.
Might not have the intended meaning.

Italian:
Una commissione più alta dell'1% è considerata insensatamente alta.
A fee higher than 1% is considered {senselessly, irrationally, foolishly, unreasonably} high.
I think this is okay but it might be useful to ask a native speaker, since "insensato" can
also mean "stupid" when applied to people.

Norwegian Bokmål:
https://www.transifex.com/projects/p/bitcoin/viewstrings/#nb/qt-translation-010x/37434907?q=insanely
Et gebyr høyere enn %1 er ansett som et sinnsykt høyt gebyr.
A fee higher than 1% is considered an insanely high fee.
Needs retranslation. The literal meaning of sinnsykt is "mentally sick".

Swedish:
https://www.transifex.com/projects/p/bitcoin/viewstrings/#sv/qt-translation-010x/37434907?q=insanely
En avgift högre än %1 anses som en onormalt hög avgift.
A fee higher than 1% is considered as an abnormally high fee.
Seems fine.

Russian:
Комиссия больше, чем %1, считается невероятно большой.
A fee more than 1% is considered {extremely, unbelieveably, incredibly} high.
Seems fine.

Ukrainian:
https://www.transifex.com/projects/p/bitcoin/viewstrings/#uk/qt-translation-010x/37434907?q=insanely
Плата вища, ніж %1 вважається шалено високою.
A fee more than 1% is considered {wildly, incredibly} high.
Seems fine.

Turkish:
https://www.transifex.com/projects/p/bitcoin/viewstrings/#tr/qt-translation-010x/37434907?q=insanely
%1 tutarından yüksek ücret delicesine aşırı yüksek bir ücret olarak kabul edilir.
A fee higher than 1% is considered an insanely excessive cost.

Chinese (China/simplified):
高于 %1的交易费 将视为 过高的交易费。
Greater than 1% transaction fee will be deemed {excessive, exorbitant, too high} transaction fees.
过高 seems not to be ableist, but it might not have the intended meaning for the same reason "excessive" doesn't.

Chinese (Taiwan/traditional):
高於 %1 的手續費會被認為是不正常。
Greater than 1% transaction fee will be considered {abnormal, fraudulent, iniquitous}.
Hmm. Not sure that 不正常 (translated by Google as "abnormal", but 不正 is translated as "fraud")
has the intended meaning either.

Needs retranslation for ableist language: Danish, Dutch, Norwegian Bokmål, possibly Italian
Needs retranslation for meaning: Chinese (China and Taiwan), Catalan

**Comment by daira** [comment]
Closing in favour of #5732.

**Comment by daira** [comment]
Danish has been fixed ( https://www.transifex.com/projects/p/bitcoin/viewstrings/#da/qt-translation-011x/37434907?q=absurd ). I submitted the old, unproblematic translations for German, Russian, and Ukrainian.

**Pull request closed without merging**
