### PR TITLE
[util] Remove redundant call to get() on smart pointer (thread_specific_ptr)

### PR DESCRIPTION
**Pull request by practicalswift**

### CODE REVIEW

**Comment by practicalswift** [comment]
Replaced `[trivial]` with `[util]` in commit title.

**Comment by practicalswift** [comment]
Any changes needed before merge? :-)

**Comment by sipa** [comment]
@practicalswift Reviewers are volunteers and have a lot to look at around this time... please don't a dozen pull requests.

**Comment by practicalswift** [comment]
@sipa Sorry about that - was mean to be more like a friendly ping than a nag. Sorry, won't happen again :-)

**Comment by practicalswift** [comment]
Merge conflicts resolved and pushed! :-)

**Pull request merged**
