### PR TITLE
Set link from http:// to https://

### PR DESCRIPTION
**Pull request by suriyaa**
Hi guys, :smile:

I **set the** **_`opensource.org/licenses/MIT`**_ **link from** **_http://**_ **to** **_https://**_ in **`README.md`**. :pencil2:

_Yours,_
[**Suriyaa Kudo**](https://github.com/SuriyaaKudoIsc) :octocat:

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Trivial ACK.

**Comment by paveljanik** [comment]
ACK

**Comment by dcousens** [comment]
Trivial ACK

**Comment by fanquake** [comment]
ACK

**Comment by petertodd** [comment]
Ah cool! Good to keep in mind for other projects.

Trival ACK

**Comment by SuriyaaKudoIsc** [comment]
@jonasschnelli @paveljanik @dcousens @fanquake @petertodd: What do you mean with **"`Trivial ACK`"**?

**Comment by MarcoFalke** [comment]
@SuriyaaKudoIsc Please read the `README.md` and https://github.com/bitcoin/bitcoin/blob/05b5831aa0038cc2ae24e17ea438428eb2b6e44c/CONTRIBUTING.md

**Comment by SuriyaaKudoIsc** [comment]
@MarcoFalke: Thanks! :+1:

> ACK means "I have tested the code and I agree it should be merged"

**Pull request merged**
