### PR TITLE
doc: empty REVIEWERS file

### PR DESCRIPTION
**Pull request by fanquake**
It seems that it's time for our experiment with this file to come to an
end.

See discussion here:
https://github.com/bitcoin/bitcoin/pull/25560/files#r915491743.

### CODE REVIEW

**Review by kristapsk — APPROVED** [review]
ACK cdbc68c1cd9b8228f8cdee9f61c20639325fb67d. It's kinda [CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners), don't think Bitcoin Core should have such thing.

**Comment by MarcoFalke** [comment]
Yes, `git blame` is best if you want to manually find reviewers.

However, this list was made for people to *opt-in* to *bot* notifications (as it is explained in the first line of the file), but then some people on the list complained about being notified by a bot. :man_shrugging: 

If there is anyone in this list who prefers those bot notifications, I think we should keep them in this list and remove everyone else.

**Comment by MarcoFalke** [comment]
Currently, the format of the comment looks like this: https://github.com/bitcoin/bitcoin/pull/25614#issuecomment-1184513896

This may be interesting to people that are not subscribed to the repo, but want to subscribe to changes to a specific file or folder.

My suggestion would be to keep the file and remove all contents for now, then leave the pull open for two weeks before merge. In those two weeks, people can explicitly opt-in by leaving a comment to be (re-)added to the file with the understanding that they will receive some kind of bot notifications. Also, anyone can open a pull request in the future to opt-in.

**Comment by fanquake** [comment]
> My suggestion would be to keep the file and remove all contents for now, then leave the pull open for two weeks before merge. In those two weeks, people can explicitly opt-in by leaving a comment to be (re-)added to the file with the understanding that they will receive some kind of bot notifications. 

Should we wait any longer?

**Comment by MarcoFalke** [comment]
I'd also say to keep the empty file in the repo for another two months to give people a chance to add themselves (opt-in to notifications) if they want.

**Comment by fanquake** [comment]
> I'd also say to keep the empty file in the repo

Pushed to just empty the file.

**Comment by MarcoFalke** [comment]
ACK 4d06fc4bed12ca119208ee53369719f52b0f7098 seems best to have devs opt-in to this explicitly by themselves

**Pull request merged**
