### PR TITLE
Tests: Refactor to create witness script creation function

### PR DESCRIPTION
**Pull request by jimmysong**
* Refactor blocktools.py so that witness script creation is its own function
* Changed p2p-segwit to use new function

### CODE REVIEW

**Review by sdaftuar — APPROVED** [review]
utACK d6388fc6c7289409e60b0076e53823cb861eda5e

**Comment by jnewbery** [comment]
Tested ACK https://github.com/bitcoin/bitcoin/pull/10223/commits/e3b78aa4978a21c270f7bd2ed6e88b8a3397fe4b. Looks good Jimmy.

**Comment by jimmysong** [comment]
@MarcoFalke Glad to squash when you give me the go-ahead for merge.

**Comment by jimmysong** [comment]
squashed and rebased to master

**Pull request merged**
