### PR TITLE
doc: Update obsolete links to online reference #19582

### PR DESCRIPTION
**Pull request by ecurrencyhodler**
Updated all the obsolete links to valid ones.

Found this issue from https://github.com/bitcoin/bitcoin/issues/19582.

### CODE REVIEW

**Comment by hebasto** [comment]
@ecurrencyhodler 
Thank you! And welcome as a contributor!

It is expected that your commit will use a [scripted diff](https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md#scripted-diffs) :)

**Comment by ecurrencyhodler** [comment]
Thanks. Will take a look. I'll see if I can figure out how to do that. :)

**Comment by MarcoFalke** [comment]
There'd also be the https://btcinformation.org/en/developer-reference#reject website , not sure which one to prefer, though. Another alternative would be to remove the links completely.

**Comment by hebasto** [comment]
> There'd also be the https://btcinformation.org/en/developer-reference#reject website , not sure which one to prefer, though. Another alternative would be to remove the links completely.

+1 to remove them.

This script could be used:
```
-BEGIN VERIFY SCRIPT-
sed -i '/https:\/\/bitcoin.org\/en\/developer-reference/d' ./src/protocol.h
-END VERIFY SCRIPT-
```

**Comment by MarcoFalke** [comment]
Fixed in commit a787428

**Pull request closed without merging**
