### PR TITLE
Compress PNG images with `zopflipng`.

### PR DESCRIPTION
**Pull request by mikispag**
Compress every PNG image with [`zopflipng`](https://github.com/google/zopfli), an open source program for losslessly compressing PNGs using DEFLATE better.

This commit can be reproduced with the following command:

```shell
for i in `find -type f -name '*.png'`; do zopflipng -m -y "$i" "$i" & done;
```

and the latest version of `zopflipng`.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
How much are the savings? For git the file size is going to effectively double, since it has to keep track of both versions.

If the savings are worthwhile, I'd suggest to adjust our script to use zopfli: https://github.com/bitcoin/bitcoin/blob/master/contrib/devtools/optimize-pngs.py

**Comment by mikispag** [comment]
Good point. For some files, they become 25+% smaller.

**Comment by jonasschnelli** [comment]
Does this PR produce deterministic files? See discussion in https://github.com/bitcoin/bitcoin/pull/5489.

**Comment by mikispag** [comment]
I tried re-running several times and with the same version of `zopflipng` - yes. Not sure this is exactly what you are asking, though.

**Comment by promag** [comment]
No strong opinion, but I think savings aren't worth it.

**Comment by laanwj** [comment]
Tend toward NACK. Sorry to say, but reducing the size of our images to the absolute minimum is not an important concern of this project. There isn't much media in bitcoin core at all.

If you want to do serious work in reducing the size of the distributed binaries, you might want to look at testing #18605.

**Comment by kiminuo** [comment]
I agree with laanwj.

**Comment by fanquake** [comment]
Thanks. This kind of thing has come up many times before, #16636, #11069, #17122, #14615, and it'd seem that if we were to merge a compression, 6 months later someone will likely  be able to optimize the images slightly more (and we'd just end up with even more copies of the same files in git).

If you are keen to start contributing, I'd suggest taking a look at the [good first issues list](https://github.com/bitcoin/bitcoin/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22).

**Comment by MarcoFalke** [comment]
I was patching our script for fun to see if zopfli can improve on top of pngcrush, and it seems so. Not enough to change anything in our repo, but enough to entertain me for 12 minutes running a script.

```
Total reduction: 43655 bytes
```

Also, the checksum was stable after two runs.

Diff I used: (Could potentially be enhanced by keeping pngcrush as a preprocessing step)

```diff
diff --git a/contrib/devtools/optimize-pngs.py b/contrib/devtools/optimize-pngs.py
index e9481dbbcf..e665541a8c 100755
--- a/contrib/devtools/optimize-pngs.py
+++ b/contrib/devtools/optimize-pngs.py
@@ -24,7 +24,7 @@ def content_hash(filename):
     data = i.tobytes()
     return hashlib.sha256(data).hexdigest()
 
-pngcrush = 'pngcrush'
+pngcrush = 'zopflipng'
 git = 'git'
 folders = ["src/qt/res/movies", "src/qt/res/icons", "share/pixmaps"]
 basePath = subprocess.check_output([git, 'rev-parse', '--show-toplevel'], universal_newlines=True, encoding='utf8').rstrip('\n')
@@ -43,17 +43,12 @@ for folder in folders:
             fileMetaMap['contentHashPre'] = content_hash(file_path)
 
             try:
-                subprocess.call([pngcrush, "-brute", "-ow", "-rem", "gAMA", "-rem", "cHRM", "-rem", "iCCP", "-rem", "sRGB", "-rem", "alla", "-rem", "text", file_path],
+                subprocess.call([pngcrush, '-m', '-y', file_path, file_path],
                                 stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
             except:
                 print("pngcrush is not installed, aborting...")
                 sys.exit(0)
 
-            #verify
-            if "Not a PNG file" in subprocess.check_output([pngcrush, "-n", "-v", file_path], stderr=subprocess.STDOUT, universal_newlines=True, encoding='utf8'):
-                print("PNG file "+file+" is corrupted after crushing, check out pngcursh version")
-                sys.exit(1)
-
             fileMetaMap['sha256New'] = file_hash(file_path)
             fileMetaMap['contentHashPost'] = content_hash(file_path)

**Comment by MarcoFalke** [comment]
So Concept ACK the next time we change the icons in the GUI, but Concept NACK for now.

**Pull request closed without merging**
