### PR TITLE
Bump minimum libc to 2.19 for release binaries

### LINKED ISSUE #17525: build: Linux gitian builds fail on master
```
  GEN      qt/locale/bitcoin_zh_TW.qm
  GEN      qt/qrc_bitcoin_locale.cpp
  CXX      qt/qt_libbitcoinqt_a-qrc_bitcoin_locale.o
  AR       qt/libbitcoinqt.a
  CXXLD    qt/bitcoin-qt
make[2]: Leaving directory '/home/ubuntu/build/bitcoin/distsrc-i686-pc-linux-gnu/src'
make[1]: Leaving directory '/home/ubuntu/build/bitcoin/distsrc-i686-pc-linux-gnu/src'
Making all in doc/man
make[1]: Entering directory '/home/ubuntu/build/bitcoin/distsrc-i686-pc-linux-gnu/doc/man'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/ubuntu/build/bitcoin/distsrc-i686-pc-linux-gnu/doc/man'
make[1]: Entering directory '/home/ubuntu/build/bitcoin/distsrc-i686-pc-linux-gnu'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/home/ubuntu/build/bitcoin/distsrc-i686-pc-linux-gnu'
+ make -j1 -C src check-security
make: Entering directory '/home/ubuntu/build/bitcoin/distsrc-i686-pc-linux-gnu/src'
Checking binary security...
make: Leaving directory '/home/ubuntu/build/bitcoin/distsrc-i686-pc-linux-gnu/src'
+ make -j1 -C src check-symbols
make: Entering directory '/home/ubuntu/build/bitcoin/distsrc-i686-pc-linux-gnu/src'
Checking glibc back compat...
bitcoin-cli: symbol getauxval from unsupported version GLIBC_2.16
bitcoin-tx: symbol getauxval from unsupported version GLIBC_2.16
bitcoin-wallet: symbol getauxval from unsupported version GLIBC_2.16
test/test_bitcoin: symbol getauxval from unsupported version GLIBC_2.16
qt/bitcoin-qt: symbol getauxval from unsupported version GLIBC_2.16
Makefile:15062: recipe for target 'check-symbols' failed
make: *** [check-symbols] Error 1
make: Leaving directory '/home/ubuntu/build/bitcoin/distsrc-i686-pc-linux-gnu/src'

### PR DESCRIPTION
**Pull request by laanwj**
Fixes #17525.

Debian 8 (Jessie, oldoldstable) has:

- g++ version 4.9.2 (https://packages.debian.org/search?suite=jessie&arch=any&searchon=names&keywords=g%2B%2B)
- libc version 2.19 (https://packages.debian.org/search?suite=jessie&arch=any&searchon=names&keywords=libc6)

Debian 9 (Stretch, Oldstable) has:

- g++ version 6.3.0 (https://packages.debian.org/search?suite=stretch&arch=any&searchon=names&keywords=g%2B%2B)
- libc version 2.24 (https://packages.debian.org/search?suite=stretch&arch=any&searchon=names&keywords=libc6)

Ubuntu 16.04.4 (Xenial, oldest supported Ubuntu) has:

- g++ version 5.3.1 (https://packages.ubuntu.com/search?keywords=g%2B%2B&searchon=names&suite=xenial&section=all)
- libc version 2.23.0 (https://packages.ubuntu.com/search?keywords=libc6&searchon=names&suite=xenial&section=all)

Taking the minimum of these as our target.

According to GNU ABI document (http://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html) this corresponds to:

- GCC 4.9.2: GCC_4.8.0
- (glibc)    GLIBC_2_19

This also contains a (long needed) commit to disallow dynamic linking to stdc++, as our releases statically link against that.

It might be possible to remove some fallbacks from `src/compat/glibc_compat.cpp`, too. But I'll wait for the version decision first.

### CODE REVIEW

**Comment by laanwj** [comment]
Could also do Jessie (oldoldstable):
- g++ version 4.9.2 (https://packages.debian.org/search?suite=jessie&arch=any&searchon=names&keywords=g%2B%2B)
- libc version 2.19 (https://packages.debian.org/search?suite=jessie&arch=any&searchon=names&keywords=libc6)

This would still fix #17525, which requires at least 2.16.

**Comment by fanquake** [comment]
Concept ACK

**Comment by laanwj** [comment]
I have backed this down to 2.19 (Debian Stretch/Oldoldstable). I see no reason to push for anything higher.

**Comment by MarcoFalke** [comment]
http://mirror.centos.org/centos/7/os/x86_64/Packages/glibc-2.17-292.el7.x86_64.rpm

**Comment by laanwj** [comment]
Bah, I'm giving up on this.

**Comment by MarcoFalke** [comment]
Could also add the EOL in comments, so:

* Cent OS 7: June 30, 2024
* Debian 8: 2020 (https://wiki.debian.org/DebianReleases#Production_Releases)

**Comment by laanwj** [comment]
Feel free to pick this up, I don't feel like bothering with the eternal pit of misery that is distributing binaries for Linux anymore.

**Comment by fanquake** [comment]
I'll grab this.

**Pull request closed without merging**
