### PR TITLE
Docs: Improve doc of options addnode, connect, seednode

### PR DESCRIPTION
**Pull request by ghost**
Just clarify that options `addnode`, `connect` and `seednode` can be specified multiple times.

### CODE REVIEW

**Comment by sipa** [comment]
ACK

**Comment by wodry** [comment]
There was a Travis error only on one build. I added two empty new lines to the commit message and pushed again to trigger a new build to see if it now passes.

```
feature_includeconf.py                | x Failed  | 1 s
ALL                                   | x Failed  | 941 s (accumulated) 
Runtime: 243 s
Uncovered RPC commands:
  - abortrescan
  - estimatesmartfee
  - getaddressbyaccount
  - getmempoolancestors
  - getmempooldescendants
  - logging
  - pruneblockchain
The command "if [ "$RUN_TESTS" = "true" ]; then DOCKER_EXEC test/functional/test_runner.py --combinedlogslen=4000 --coverage --quiet --failfast ${extended}; fi" exited with 1.
```

**Comment by fanquake** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/13588/commits/b330c3001cf8b68362ccb7e818cd0c457f535e6f

**Comment by laanwj** [comment]
utACK b330c3001

**Pull request merged**
