### PR TITLE
refactor: VectorWriter and SpanReader without nVersion

### PR DESCRIPTION
**Pull request by maflcko**
The serialize version is unused, so remove it. This also allows to remove `GCS_SER_VERSION` and allows a scripted-diff to remove most of `CDataStream`.

### CODE REVIEW

**Comment by ajtowns** [comment]
Shares its first commit with #28892

**Review by ryanofsky — APPROVED** [review]
Code review ACK fae76a1f2ac0b352cdd708e6d57f8605bf40112e

**Comment by ryanofsky** [comment]
What are the places where CDataStream is still needed after this and what will happen to these?

**Comment by ajtowns** [comment]
ACK fae76a1f2ac0b352cdd708e6d57f8605bf40112e

**Pull request merged**
