### PR TITLE
Drop dead code CScript::Find

### PR DESCRIPTION
**Pull request by Empact**
Last use removed in 922e8e2 (2012!)

### CODE REVIEW

**Comment by Empact** [comment]
Do we have a mechanism for dead code detection?

**Comment by MarcoFalke** [comment]
Please include in what commit it was last used.

**Comment by Empact** [comment]
@MarcoFalke 922e8e2 (2012!)

**Comment by jimpo** [comment]
utACK c6d4a81.

grepped codebase for `Find(`. Other instances found are `CAddrMan::Find` and `FindFileTest::Find` in leveldb.

**Comment by Empact** [comment]
The test failure is known issue #12863

**Comment by Empact** [comment]
Rebased for CI

**Comment by ajtowns** [comment]
NACK 8cbc5c4be4be22aca228074f087a374a7ec38be8 -- code is fine, but it introduces a merge conflict with #12885 due to being adjacent in the file being patched, so this should be rebased after that is merged IMO.

**Comment by practicalswift** [comment]
utACK 8cbc5c4be4be22aca228074f087a374a7ec38be8

I don't see any usage being removed in 922e8e2.

My reading is that `Find(…)` has been unused since being introduced in e679ec969c8b22c676ebb10bea1038f6c8f13b33.

Anyways – nice find!

**Comment by laanwj** [comment]
drop dead code :mouse:
utACK 8cbc5c4be4be22aca228074f087a374a7ec38be8

**Comment by sipa** [comment]
Drop dead, code! utACK 8cbc5c4be4be22aca228074f087a374a7ec38be8

**Comment by Empact** [comment]
@sipa likewise on this side :)

**Comment by promag** [comment]
@ajtowns sorry you mean @practicalswift?

**Comment by promag** [comment]
utACK 8cbc5c4.

**Pull request merged**
