### PR TITLE
Changed Czech translation of the word "blockchain"

### PR DESCRIPTION
**Pull request by pajasevi**
Changed translation of the word "blockchain" and "block chain" from "bločenka" to its english version.
Motivation:
- "Bločenka" is not technically correct term and does not have the same meaning as the original term
- Nobody actually ever uses it because it is silly and confusing
- Term "blockchain" is regularly used in both mainstream and technical media in Czech language as well as in software, services, forums etc.

### CODE REVIEW

**Comment by laanwj** [comment]
Those are good points!
However, please edit translations on transifex: https://www.transifex.com/bitcoin/bitcoin/qt-translation-018x/  
We don't take changes to translation files here because they would be overwritten next time the is synced from there.

Also documented here: https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#contributor-workflow

> Note that translations should not be submitted as pull requests, please see Translation Process for more information on helping with translations.

**Comment by pajasevi** [comment]
@laanwj I'm sorry for unnecessary PR and thank you for the information. I will submit my translation ASAP.

**Comment by laanwj** [comment]
No need to be sorry, let me know when you've made your change then I'll pull your change into 0.18 (so we can try to get this into rc2)

**Comment by pajasevi** [comment]
I've made the changes on transifex few minutes ago (and also added a few new translations). Does it need to be approved over there to get into the repo?

**Comment by laanwj** [comment]
> I've made the changes on transifex few minutes ago (and also added a few new translations). Does it need to be approved over there to get into the repo?

No, unless your language has a review team, but that's quite rare.

I've tried running the `contrib/devtools/update-translations.py` script and it makes these changes (among others), so it's okay.

**Comment by generalbytes** [comment]
That was fast.

**Comment by slush0** [comment]
I agree with the change, "bločenka" is silly in Czech.

**Pull request closed without merging**
