### PR TITLE
Bugfix: Include <memory> for std::unique_ptr

### PR DESCRIPTION
**Pull request by luke-jr**
Not sure why all these includes were missing, but it's breaking builds for some users:

https://bugs.gentoo.org/show_bug.cgi?id=652142

(Added to all files with a reference to `std::unique_ptr`)

### CODE REVIEW

**Comment by randolf** [comment]
This doesn't compile on NetBSD 7.0 (64-bit), but the unmodified branch builds as expected.  It seems that these updates prevent the check for "-ldb_cxx" from succeeding, even though Berkeley DB4 is already installed.

**STEPS**
```
git clone https://www.github.com/luke-jr/bitcoin
cd bitcoin
git checkout incl_memory
./autogen.sh
./configure CPPFLAGS="-I/usr/pkg/include" LDFLAGS="-L/usr/pkg/lib" BOOST_CPPFLAGS="-I/usr/pkg/include" BOOST_LDFLAGS="-L/usr/pkg/lib"
```

**OUTCOME**
```
checking for Berkeley DB C++ headers... /usr/pkg/include/db4/
checking for main in -ldb_cxx-4.8... no
checking for main in -ldb_cxx... no
configure: error: libdb_cxx missing, Bitcoin Core requires this library for wallet functionality (--disable-wallet to disable wallet functionality)
```

If a change is needed for the ``./configure`` command, I'd be happy to add it to the documentation for the NetBSD installation instructions to accommodate this Pull Request.

Thanks.

**Comment by luke-jr** [comment]
Don't use PR branches directly (this one is based on the last common commit between 0.15 and master, for maximum merge-compatibility). Merge it into master to test.

(This shouldn't change anything during configure.)

**Comment by randolf** [comment]
@luke-jr I'm still learning how to use git, et al., so I welcome any suggestions on how to test this properly.

**Comment by luke-jr** [comment]
```
git clone https://www.github.com/bitcoin/bitcoin
cd bitcoin
git fetch https://www.github.com/luke-jr/bitcoin incl_memory
git merge FETCH_HEAD
./autogen.sh
./configure CPPFLAGS="-I/usr/pkg/include" LDFLAGS="-L/usr/pkg/lib" BOOST_CPPFLAGS="-I/usr/pkg/include" BOOST_LDFLAGS="-L/usr/pkg/lib"
```

**Comment by randolf** [comment]
ACK.

@luke-jr Thanks, that worked, and it compiled successfully on NetBSD.

**Review by randolf — APPROVED** [review]

**Comment by luke-jr** [comment]
@fanquake This should be "Bug", not "Refactoring"...

**Comment by promag** [comment]
utACK a5bca13.

**Comment by sipa** [comment]
utACK a5bca13095aa835d61f872081fc0cc2fa53552f3

**Comment by fanquake** [comment]
Added to #13455 for backport.

**Pull request merged**
