### PR TITLE
build: Re-add command to install vcpkg

### PR DESCRIPTION
**Pull request by dplusplus1024**
`vcpkg integrate install` must be executed so that msbuild will automatically install external dependencies.

It was removed in https://github.com/bitcoin/bitcoin/commit/712f95d3324d02310dd468e7bfd1e1b0df432e77

It was originally added in https://github.com/bitcoin/bitcoin/commit/76445677586a4c2fa72606b662269a4390c2e71f

### CODE REVIEW

**Comment by ddustin** [comment]
ACK

**Comment by sipsorcery** [comment]
ACK de17d245b7462784f9d36591b0f346aa6b2e9b8c.

I did shorten the `vcpkg` instructions when [manifests](https://vcpkg.readthedocs.io/en/latest/specifications/manifests/) were introduced. The idea being that `msbuild` would take care of calling `vcpkg` to install the dependencies automatically and it would be one less step.

Given that:

 - It seems to be recommended to still call [vcpkg integrate install](https://devblogs.microsoft.com/cppblog/vcpkg-accelerate-your-team-development-environment-with-binary-caching-and-manifests/#using-manifests-with-msbuild-projects) even with manifests enabled.
 - At least one issue, #17864, has been raised with the Bitcoin Core `vcpkg` instructions.
 - Executing `vcpkg integrate install` should not cause any problems for manifests (although it's not clear what happens if different versions of a dependency are installed in the main `vcpkg` directory and the `manifest` directory).

It's an ACK from me.

**Review by hebasto — APPROVED** [review]
ACK de17d245b7462784f9d36591b0f346aa6b2e9b8c, I use the same in #21551.

**Comment by MarcoFalke** [comment]
Sorry, I missed the "Merge message contains an html comment!" warning when merging this. So the merge commit now contains an html comment.

**Pull request merged**
