### PR TITLE
Revert "Fixes Bug in Transaction generation in ComplexMempool benchmark"

### PR DESCRIPTION
**Pull request by maflcko**
Developers are reporting crashes (potentially OOM) on IRC, but I can't reproduce. Still, revert this for now, since one developer reported the bare metal this was running on crashed.

### CODE REVIEW

**Comment by hebasto** [comment]
Is it ok that this PR is not based on the master branch?

**Comment by MarcoFalke** [comment]
> Is it ok that this PR is not based on the master branch?

Huh, I think it is impossible to create a pull request for a branch that isn't based on a commit in the target branch?

**Comment by MarcoFalke** [comment]
> I mean, a commit parent is not a merge commit.

I don't think we do or should require that. Would there be a reason?

**Comment by laanwj** [comment]
Thanks, tested ACK faa185bb3abe5fdaeeae14706bad9437acac6a69
Can run the `bench_bitcoin` again without crashing my whole computer.

**Pull request merged**
