### PR TITLE
use constant references for strings in functions in wallet/*.*

### PR DESCRIPTION
**Pull request by Diapolo**

### CODE REVIEW

**Comment by jonasschnelli** [comment]
utACK @theuni over trivial

**Comment by fanquake** [comment]
utACK

**Comment by Diapolo** [comment]
As this is a code change this doesn't belong into trivial IMHO.

**Comment by laanwj** [comment]
Agree, this should not be in trivial.

ACK

**Comment by sipa** [comment]
ACK

**Pull request merged**
