### PR TITLE
verify-commits: Bump trusted git root to after most recent laanwj merge

### PR DESCRIPTION
**Pull request by achow101**
To prepare for the removal of laanwj's key from trusted key (#27054), the trusted git root needs to be newer than the most recent merge commit signed by his key.

This can be tested by removing the laanwj's key from trusted keys (e.g. by merging with #27054) and running `verify-commits.py` with `--clean-merge 0`: `./contrib/verify-commits/verify-commits.py --clean-merge 0 HEAD~`. (`--clean-merge 0` disables the clean merge check which will checkout some commits, which results in the `trusted-keys` used in checking of subsequent commits to be different than expected).

### CODE REVIEW

**Comment by Sjors** [comment]
I would prefer a solution that allows checking commits by retired maintainers, at least up to a few years back (e.g. the branch-off point for the last backport supported version).

**Comment by MarcoFalke** [comment]
You can do `git checkout "$(cat contrib/verify-commits/trusted-git-root)~1"` and then verify the previous commits, as often as you want, to go as far back as you want.

**Comment by Sjors** [comment]
That's a good hint to add to the `README`. But having the root key not too recent still seems better, all things equal. I think we should only bump it if a former maintainer revokes their key or it expires, plus maybe every couple of years to preempt such issues. So far #27058 seems compatible with that approach.

**Comment by MarcoFalke** [comment]
> I think we should only bump

Is there any reason for this? See also https://github.com/bitcoin/bitcoin/pull/27058#discussion_r1099900493 
What would the alternative be? Listing hundreds or thousands of "revsig" commits in a file, to ensure it is impossible to review manually, only with special git commands, potentially making it trivial to sneak in malicious commits that are not actually revsig commits?

**Comment by Sjors** [comment]
@MarcoFalke answered in https://github.com/bitcoin/bitcoin/pull/27058#issuecomment-1426770715. Depending on what we do there this PR can either be closed or merged.

**Comment by MarcoFalke** [comment]
lgtm, Approach ACK

I haven't tested this, because I use a trusted git root set by myself anyway, but I can't see a reason not to do this. This was also done last time in commit d4b3dc5b0a726cc4cc7a8467be43126e78f841cf, so it makes sense to do the same approach again.

**Review by fanquake — APPROVED** [review]
ACK 6ada37d44cce7fa3a729de72cede4c1f3bc675ce

```bash
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

ACK 6ada37d44cce7fa3a729de72cede4c1f3bc675ce
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEEz7FuIclQ9n+pXlWPLuufXMCVJsEFAmPrwdkACgkQLuufXMCV
JsHyExAApfaVBqnmRs6raV8ky90kLLiesvYjgebHyJAq059OZvlROziNC43FAlls
xnhDxMYqUB8rFRGpPccqI4oi+tpSFUrS44MP+UgMzkq1mrt7Tfx7cjTQPkB21YFD
FYrTZT5hE7FLQvkf7yDD8OobkZOZQl5wIKE+VNW3TW0oBWnfjXY5tw1vh51Qta1x
9B7UrSRJJ3SFD/xmLYDtCtzRDraKg44fRxKf9A5rvXaWdfR3s8pBZuVXJePveCTv
YQjKQtFxRIjiWaFNW+ERD0xxq0B6z3/LvocqXJwo2Mryc4tUMsqZuopze6V8oIUB
GWxSRxDV6bumWxxBqQbvfZJhwJY+Jstm2JD7TxDtwvgJe0Wnb0sTsGBpkFFNXORy
9QPCcYPlW3+YIT2Z/fDhg1DQd4+2JhWtaGyguB/yHly7j2A+jRGBqtFATNFUtz/r
cfTdDPXR3fvXFh3hjcKKCvcwKrPbfU4SXqAU0qlXX7DprbWkpQpt01Jg5rNBINlC
j/tsKNxeMj1kNeCYy4muDqC5HRA2gsqlb+bEeyndg3PlPyypi0d8Aj2S7/BgXUU/
FKSgXWMEagBXHklmYJnMRtt85RDsOfDKW7znecGDqDBlX2qA8pZ1SNaVWYhFvU2Y
iePmdIgEuhpn19xQwjSu+M4ITVNb0C9jSqY0IUF5gK3OZh70WGw=
=Bln+
-----END PGP SIGNATURE-----
```

**Review by hebasto — APPROVED** [review]
ACK 6ada37d44cce7fa3a729de72cede4c1f3bc675ce, I've verified the history of laanwj's merge commits.

**Comment by glozow** [comment]
post merge ACK 6ada37d44cce7fa3a729de72cede4c1f3bc675ce

**Pull request merged**
