### PR TITLE
semi trivial: clarify witness branches in transaction.h serialization

### PR DESCRIPTION
**Pull request by dcousens**
In reading through this,  I found it much easier to read/reason about the branches without having to double check the double negation and relevant syntax by just having this more readable variable.

`hasWitness` might be misleading,  since the witness flag could still be missing.
Perhaps `supportsWitness` or `witnessCompatible`?

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Trivial utACK 744526fec097821a78529386ada81ae844f7183a

**Comment by NicolasDorier** [comment]
Trivial utACK 744526f, I think supportsWitness may be better though, if you are not too lazy to change it. :p

**Comment by sipa** [comment]
utACK after squash. allowWitness is fine by me.

**Comment by paveljanik** [comment]
`fAllowWitness`?

**Comment by dcousens** [comment]
Rebased and squashed as dc82f77

**Comment by paveljanik** [comment]
trivial ACK https://github.com/bitcoin/bitcoin/pull/8332/commits/e37b16a75c1ff86d515ef3050d2c76432ea71225

**Comment by jtimon** [comment]
ACK e37b16a (didn't tested but it's obviously correct).

**Comment by MarcoFalke** [comment]
utACK e37b16a75c1ff86d515ef3050d2c76432ea71225

**Pull request merged**
