### PR TITLE
refactor: Use chainman() helper consistently in ChainImpl

### PR DESCRIPTION
**Pull request by maflcko**
Doing anything else will just lead to more verbose and inconsistent code.

### CODE REVIEW

**Review by jamesob — COMMENTED** [review]
Concept ACK, will review shortly

**Review by fanquake — APPROVED** [review]
ACK fa32b1bbfd418410c47b2a33c6fa106371288138 - all instances of `Assert(m_node.chainman)` in node/interfaces replaced with `chainman()`, which is the same thing.

**Review by shaavan — APPROVED** [review]
Code Review ACK fa32b1bbfd418410c47b2a33c6fa106371288138

- I agree with making the code less verbose while maintaining the same logic behind it.
- Verified that using `chainman()` is equivalent to `Assert(m_node.chainman)`

```
ChainstateManager& chainman() { return *Assert(m_context->chainman); }
```
- Verified that all instances of `Assert(m_node.chainman)` are replaced with `chainman()`.

**Comment by jonatack** [comment]
Post-merge ACK

**Pull request merged**
