### PR TITLE
Refactor: Stop using namespace std (bitcoin-cli/-tx).

### PR DESCRIPTION
**Pull request by kallewoof**
According to the "Source code organization" section in [Developer notes](https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md), `using namespace` should be avoided. This commit removes `using namespace std` from bitcoin-cli/-tx and adds the `std::` prefix in appropriate places.

### CODE REVIEW

**Comment by laanwj** [comment]
Yes, this has to be done at some point.

**Comment by sipa** [comment]
Concept ACK

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/9220/commits/2f2625a0bb94db220a6f5560fa942159b66ac61e

Good candidate for same-binary check.

**Comment by MarcoFalke** [comment]
same-binaries ACK 2f2625a0bb94db220a6f5560fa942159b66ac61e

**Comment by jonasschnelli** [comment]
utACK 2f2625a0bb94db220a6f5560fa942159b66ac61e

**Comment by kallewoof** [comment]
@MarcoFalke I can't find any resources on same-binaries checking. I would like to make a more encompassing commit that deals with all these, but the diff is rather big so I'd like to do the same-binaries check beforehand myself.

**Comment by fanquake** [comment]
@kallewoof Have a look at this repo https://github.com/laanwj/bitcoin-maintainer-tools

**Comment by kallewoof** [comment]
Ahh, thanks a lot!

**Pull request merged**
