### PR TITLE
Move-only: bloom to src/common

### PR DESCRIPTION
**Pull request by maflcko**
To avoid having all files at the top level `./src` directory, start moving them to their respective sub directory according to https://github.com/bitcoin/bitcoin/issues/15732.

`bloom` currently depends on libconsensus (`CTransaction`, `CScript`, ...) and it is currently located in the libcommon. Thus, move it to `src/common/`. (libutil in `src/util/` is for stuff that doesn't depend on libconsensus).

### CODE REVIEW

**Comment by MarcoFalke** [comment]
See also #22951 (which has a minor conflict in one adjacent line).

**Review by vincenzopalazzo — APPROVED** [review]
Concept ACK https://github.com/bitcoin/bitcoin/pull/23137/commits/fa762d0cb13a12cb8e569816d1b4516405942925

**Comment by practicalswift** [comment]
Concept ACK

**Comment by naumenkogs** [comment]
Concept ACK

**Comment by MarcoFalke** [comment]
Rebased

**Review by theStack — APPROVED** [review]
Code-review ACK fa2d611bedc2a755dcf84a82699c70b57b903cf6

TIL how to move files via scripted-diff (IIRC I tried once and failed, probably used "mv" rather than "git mv"...)

**Review by hebasto — COMMENTED** [review]
Concept ACK.

**Review by ryanofsky — APPROVED** [review]
Code review ACK fa2d611bedc2a755dcf84a82699c70b57b903cf6

**Review by fanquake — APPROVED** [review]
ACK fa2d611bedc2a755dcf84a82699c70b57b903cf6 - source shuffle starts now.

**Pull request merged**
