### PR TITLE
build, qt: Drop fix_no_printer.patch

### PR DESCRIPTION
**Pull request by hebasto**
The removed patch is not required since [switching](https://github.com/bitcoin/bitcoin/pull/23489) Qt version from 5.12.11 to 5.15.2.

Upstream bug reports and fixes:
- [QTBUG-62675](https://bugreports.qt.io/browse/QTBUG-62675) fixed in https://github.com/qt/qtbase/commit/b1db1dd655788fb685949959c99c901515bfd8ab since Qt 5.12.5
- [QTBUG-76941](https://bugreports.qt.io/browse/QTBUG-76941) fixed in https://github.com/qt/qtbase/commit/de8bd9ec6b21e3b43b08c4c2588b5116a7ca8ece since Qt 5.12.5

Although the bugs have been fixed since Qt 5.12.5, we did need the patch due to the https://github.com/qt/qtbase/commit/1e5566c2e98098b0f7d7628f62425eec569f3a34 reversal commit which has been introduced in Qt 5.12.7.

### CODE REVIEW

**Comment by hebasto** [comment]
Due to adjacent modified lines of code, this PR conflicts with #24668. Would it better to combine the former into the latter?

cc @fanquake @prusnak

**Comment by prusnak** [comment]
> Would it better to combine the former into the latter?

I think it's better to rebase this PR on top of https://github.com/bitcoin/bitcoin/pull/24668 and keep the PRs separate. No strong preference, though.

**Comment by prusnak** [comment]
I created a new PR https://github.com/bitcoin/bitcoin/pull/24688 which contains the commit from this PR + adds CVE fixes mentioned in https://github.com/bitcoin/bitcoin/pull/24668#issuecomment-1079031717

If you agree we can close this PR and focus on reviewing https://github.com/bitcoin/bitcoin/pull/24688 once https://github.com/bitcoin/bitcoin/pull/24668 is merged in.

**Comment by fanquake** [comment]
> Due to adjacent modified lines of code, this PR conflicts with https://github.com/bitcoin/bitcoin/pull/24668. Would it better to combine the former into the latter?

Yes. There's no need for this to be a separate PR. If we're going to bump Qt again, then all these changes should be combined.

**Comment by prusnak** [comment]
> Yes. There's no need for this to be a separate PR. If we're going to bump Qt again, then all these changes should be combined.

Cherry-picked the commit from this PR into https://github.com/bitcoin/bitcoin/pull/24668

This PR can be closed now.

**Pull request closed without merging**
