### PR TITLE
build: Increase MS Visual Studio minimum version

### PR DESCRIPTION
**Pull request by hebasto**
Visual Studio 2022 with `/std:c++20` supports [designated initializers](https://github.com/bitcoin/bitcoin/pull/24531).

### CODE REVIEW

**Comment by hebasto** [comment]
Still [observing](https://cirrus-ci.com/task/5188905141010432) a memory usage [spike](https://github.com/bitcoin/bitcoin/pull/24531#issuecomment-1072210898) up to 25.38 GB.

**Comment by ajtowns** [comment]
> Still [observing](https://cirrus-ci.com/task/5188905141010432) a memory usage [spike](https://github.com/bitcoin/bitcoin/pull/24531#issuecomment-1072210898) up to 25.38 GB.

Is that unique to cirrus, or something people can observe when compiling with vs2022 themselves?

**Review by sipsorcery — APPROVED** [review]
Builds and passes tests for me.

**Comment by MarcoFalke** [comment]
> Is that unique to cirrus, or something people can observe when compiling with vs2022 themselves?

I guess it would be nice to have a minimum working (breaking) example

**Comment by hebasto** [comment]
> > Is that unique to cirrus, or something people can observe when compiling with vs2022 themselves?
> 
> I guess it would be nice to have a minimum working (breaking) example

FWIW, disabling of Qt code removes memory usage spikes.

**Comment by hebasto** [comment]
> So it has nothing to do with designated initializers, but with compiling qt code with the c++20 option?

Yes. See https://cirrus-ci.com/task/4621320997568512

**Comment by laanwj** [comment]
Concept ACK

**Comment by MarcoFalke** [comment]
If you want to use this pull request for debugging faster, you can also delete all other tasks and assign the credits template to the windows build for immediate scheduling.

**Comment by hebasto** [comment]
@MarcoFalke 

> you can also delete all other tasks 

Of course, I did it in my private Cirrus account :)

> and assign the credits template to the windows build for immediate scheduling.

Thank you!

**Comment by hebasto** [comment]
_"Curiouser and curiouser!"_

Just removing other CI tasks make "Win64 native [vs2022]" pass:

- https://cirrus-ci.com/task/5080247971348480 -- failed
- https://cirrus-ci.com/task/5782767731474432 -- passed

**Comment by MarcoFalke** [comment]
Maybe it incorrectly uses  a previous ccache?

**Comment by hebasto** [comment]
> Still [observing](https://cirrus-ci.com/task/5188905141010432) a memory usage [spike](https://github.com/bitcoin/bitcoin/pull/24531#issuecomment-1072210898) up to 25.38 GB.

It appears, that those spikes are caused by recursive usage of `RPCResult`. Applied refactoring removed them.

@sipsorcery Is this bug familiar to you?

**Comment by sipsorcery** [comment]
> > Still [observing](https://cirrus-ci.com/task/5188905141010432) a memory usage [spike](https://github.com/bitcoin/bitcoin/pull/24531#issuecomment-1072210898) up to 25.38 GB.
> 
> It appears, that those spikes are caused by recursive usage of `RPCResult`. The applied refactoring has removed them.
> 
> @sipsorcery Is this bug familiar to you?

Nope, I've never come across it. I only have 16GB though, so I'd guess even if I did somehow manage to replicate it my machine would crash or freeze first.

**Comment by sipsorcery** [comment]
tACK 1240e827770dfe2c10badd9e42730430abb44ee5.

**Comment by MarcoFalke** [comment]
Concept ACK 1240e827770dfe2c10badd9e42730430abb44ee5

**Comment by hebasto** [comment]
Rebased 1240e827770dfe2c10badd9e42730430abb44ee5 -> 630c1711b47ce50805f4dd2883777a100f7e5339 ([pr25472.06](https://github.com/hebasto/bitcoin/commits/pr25472.06) -> [pr25472.07](https://github.com/hebasto/bitcoin/commits/pr25472.07)) due to the conflict with #25500.

**Comment by theuni** [comment]
I'm confused about this PR. If I'm reading correctly, MSVC now gets built as c++20 while other platforms are c++17. Seemingly so that we could drop our designated initializer code because it's non-standard for c++17.

That seems like a huge hammer for a small problem. I suspect I'm missing something?

**Comment by hebasto** [comment]
> I'm confused about this PR. If I'm reading correctly, MSVC now gets built as c++20 while other platforms are c++17. Seemingly so that we could drop our designated initializer code because it's non-standard for c++17.
> 
> That seems like a huge hammer for a small problem. I suspect I'm missing something?

I took a liberty to cross [reference](https://github.com/bitcoin/bitcoin/pull/24531#issue-1166402005):
> Designated initializers are supported since gcc 4.7 (Our minimum required is 8) and clang 3 (Our minimum required is 7). They work out of the box with C++17, and only msvc requires the C++20 flag to be set. I don't expect any of our msvc users will run into issues due to this. See also https://bitcoin.jonasschnelli.ch/ircmeetings/logs/bitcoin-core-dev/2022/bitcoin-core-dev.2022-03-10-19.00.log.html#l-114

**Pull request merged**
