### PR TITLE
Log warning when deprecated network name 'tor' is used

### PR DESCRIPTION
**Pull request by ghost**
As @laanwj mentioned [here](https://github.com/bitcoin/bitcoin/pull/13418#discussion_r197645385), using option `onlynet=tor` is deprecated.

I think it would be good to give the user a depcreaction warning feedback, so users can switch to `onlynet=onion` so there is a perspective for removing the deprecated `tor` in the future to decrease confusion.

Currently, users maybe just wonder that they can use a undocumented option, or they are not aware that they use a deprecated option.

Alternatively for the log warning message, I think at least this deprecetaion should be documented in the source code in a comment for readers of the source code.

### CODE REVIEW

**Comment by laanwj** [comment]
utACK 9f8c54b1b5ddedddf47fc51c1fcb533321f6f89f

**Comment by sipa** [comment]
utACK 9f8c54b1b5ddedddf47fc51c1fcb533321f6f89f

**Comment by promag** [comment]
utACK 9f8c54b.

Makes sense to s/NET_TOR/NET_ONION/?

**Review by jb55 — APPROVED** [review]
ACK 9f8c54b1b5ddedddf47fc51c1fcb533321f6f89f

**Comment by sipa** [comment]
utACK 9f8c54b1b5ddedddf47fc51c1fcb533321f6f89f

**Pull request merged**
