### PR TITLE
[tests] Don't import asyncio to test magic bytes

### PR DESCRIPTION
**Pull request by jnewbery**
Simplify the test for invalid start bytes. No need to import asyncio and the Network thread.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Concept ACK. Nice simplification, but it looks like the tests no longer pass after this change.

**Comment by jnewbery** [comment]
oops. Fixed.

**Comment by MarcoFalke** [comment]
review ACK 49236be099c5e8b3cadbc98d5216313e7e1a5a45

**Comment by fanquake** [comment]
cc @troygiorshev.

**Review by jonatack — COMMENTED** [review]
ACK 49236be099c5e8b3cadbc98d5216313e7e1a5a45

**Comment by troygiorshev** [comment]
ACK 49236be.  +0.1 on the additional `cut_len` reformat.

**Pull request merged**
