### PR TITLE
ci: Switch to Previous Visual Studio 2019 image to avoid failure

### PR DESCRIPTION
**Pull request by hebasto**

### CODE REVIEW

**Comment by jonatack** [comment]
Concept ACK if this fixes the appveyor CI that appears to have gone down today.￼

**Comment by hebasto** [comment]
Hmm, on my personal AppVeyor account it passes: https://ci.appveyor.com/project/hebasto/bitcoin/builds/40571807

**Comment by hebasto** [comment]
@sipsorcery Could you look in the current Appveyor failure?

**Comment by hebasto** [comment]
The current master branch passes on my personal AppVeyor account.

Therefore, this PR does not make any sense.

**Comment by sipsorcery** [comment]
@hebasto looks fine? I'll double check `master` on my appveyor set up.

**Comment by hebasto** [comment]
@sipsorcery 
> @hebasto looks fine? I'll double check `master` on my appveyor set up.

It looks like a hiccup on their side :)

**Pull request closed without merging**
