### PR TITLE
Prevent multiple calls to ExtractDestination

### PR DESCRIPTION
**Pull request by pedrobranco**
Trivial performance improvement.

It consists in preventing multiple calls to `ExtractDestination` in rpc call `listunspent`. For an **large UTXO set** the improvement are more notable.  

This PR moves the computation of multiple `ExtractDestination` to a single call, and also reorganizes the code of building the JSON result of each UTXO.

### CODE REVIEW

**Comment by dcousens** [comment]
utACK 4a7c2f4

**Comment by laanwj** [comment]
Concept ACK

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/7825/commits/4a7c2f4c5a3c9c68bf7f50670f825fcbf1769dbb

To get more people looking at this, please provide some interesting numbers ;-))

**Comment by pedrobranco** [comment]
The performance improvement isn't much significant on typical wallets. The main advantage is the reuse of the function `ExtractDestination(` and the organization of `listunspent` call.

**Comment by NicolasDorier** [comment]
I would add this condition:

```
if(!fValidAddress && setAddress.size() > 0)
    continue;
```

**Comment by pedrobranco** [comment]
@NicolasDorier You are right. Will fix.

**Comment by NicolasDorier** [comment]
utACK 83153e6

**Comment by sipa** [comment]
utACK 0bf6f302626497184a26b88c61fe6af1741e2a44

**Comment by jonasschnelli** [comment]
Core-Review utACK 0bf6f302626497184a26b88c61fe6af1741e2a44

**Pull request merged**
