### PR TITLE
testing pr (please ignore)

### PR DESCRIPTION
**Pull request by ryanofsky**

### CODE REVIEW

**Comment by sipa** [comment]
What is this?

**Comment by sipa** [comment]
Please stop spamming.

**Comment by TheBlueMatt** [comment]
Thats my bad, I told him if he wants to test travis he can just open a pr and keep updating till the tests pass...I forgot that github started sending emails for each push.

**Comment by jnewbery** [comment]
@TheBlueMatt - if @ryanofsky's Bitcoin fork is public, he should be able to enable Travis builds on the branches in his own fork.

**Pull request closed without merging**
