### PR TITLE
test: Add diamond-shape prioritisetransaction test

### PR DESCRIPTION
**Pull request by maflcko**
Looks like there is no test for diamonds, only for chains (in `mempool_packages.py`)

### CODE REVIEW

**Review by jessebarton — COMMENTED** [review]
Concept ACK [fa58577](https://github.com/bitcoin/bitcoin/pull/24623/commits/fa5857724d871dfd312514fcc5afd1d718e19243)

Test passed, no issues

I'm still learning quite a bit, so not sure what else to check for. Looking at the prioritisetransaction function and trying to understand the logic.

If reviews like this aren't helpful let me know.

**Comment by MarcoFalke** [comment]
Rebased for minor rework

**Comment by jamesob** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/24623/commits/fa0758e1457552e9243bc9663408e88a8cccc8f6

Nice test! Ran locally. Was this motivated by the oversight in #24364?

**Comment by MarcoFalke** [comment]
This probably can't catch #24364 in the current form. I'd suspect there will need to be at least one call to `getblocktemplate`

**Pull request merged**
