### PR TITLE
test: listsinceblock block height checks

### PR DESCRIPTION
**Pull request by jonatack**
This is the second commit of #17535. 

This PR extends a listsinceblock test to check the new transaction 'blockheight' field recently added in #17437. It also cleans up code in the test function without changing or removing existing checks.

### CODE REVIEW

**Comment by fjahr** [comment]
tested ACK 83e1d92413e262e6a876336ec433a6fbc335223a

**Comment by promag** [comment]
Code review 83e1d92413e262e6a876336ec433a6fbc335223a.

**Review by ryanofsky — APPROVED** [review]
Code review ACK 83e1d92413e262e6a876336ec433a6fbc335223a. Nice test improvements!

re: description https://github.com/bitcoin/bitcoin/pull/18420#issue-393078803

> This is the second commit of #17535, which adds coverage for #17437.

It's great to link to other issues, but would recommend writing PR description and that doesn't require reading other pages to understand. Would suggest starting off with something like, "This PR extends listsinceblock test to check new transaction 'blockheight' field recently added in #17437. It also cleans up code in the test function without changing or removing existing checks."

**Comment by jonatack** [comment]
Thanks @ryanofsky for the suggestion; added it to the PR description.

**Pull request merged**
