### PR TITLE
Bugfix: Qt/Options: Restore persistent "restart required" notice

### PR DESCRIPTION
**Pull request by luke-jr**
This got broken when updateProxyValidationState was added.

### CODE REVIEW

**Comment by laanwj** [comment]
What exactly is broken here?

**Comment by luke-jr** [comment]
updateProxyValidationState clears it, so the persistent message is never shown in practice

**Comment by laanwj** [comment]
That seems pretty serious, tagging for 0.14

**Comment by jonasschnelli** [comment]
Started testing...

**Comment by jonasschnelli** [comment]
Thanks @luke-jr!
Tested ACK 0b4f273e9cf7166dbd103e116b5d991e359e673d. Indeed, this is an important fix for 0.14.

**Comment by jonasschnelli** [comment]
Issue was introduced in #7025.

**Comment by MarcoFalke** [comment]
utACK 0b4f273e9cf7166dbd103e116b5d991e359e673d

**Pull request merged**
