### PR TITLE
Fix typos and cleanup

### PR DESCRIPTION
**Pull request by rex4539**

### CODE REVIEW

**Comment by STALININST** [comment]
I am not authorized to merge it, what is appveyor and travis-ci? I am getting emaill spam because shit like this

**Comment by practicalswift** [comment]
ACK 4a9f064ea10e58220dce114e0fafa90ff8f1fcdf

Nice cleanups!

**Comment by donaloconnor** [comment]
ACK https://github.com/bitcoin/bitcoin/commit/4a9f064ea10e58220dce114e0fafa90ff8f1fcdf

**Comment by promag** [comment]
Restarted appveyor.

ACK 4a9f064.

**Pull request merged**
