### PR TITLE
[tests] Remove rpc_zmq.py

### PR DESCRIPTION
**Pull request by jnewbery**
rpc_zmq.py is racy and fails intermittently. Remove that test file and
move the getzmqnotifications RPC test into interface_zmq.py.

### CODE REVIEW

**Comment by promag** [comment]
utACK 42a995a.

**Comment by achow101** [comment]
utACK 42a995ae4819ea472b211eb5088727a422fcbeb8

**Comment by MarcoFalke** [comment]
Why is the race not a bug that should be fixed?

**Comment by practicalswift** [comment]
utACK 42a995ae4819ea472b211eb5088727a422fcbeb8

Let's get rid of the racy test now and have it re-added as soon as a raciness has been fixed

**Comment by gmaxwell** [comment]
> Let's get rid of the racy test now and have it re-added as soon as a raciness has been fixed

I can't follow this logic.

**Comment by practicalswift** [comment]
@gmaxwell Sorry, my logic was incorrect :-)  I incorrectly assumed that some racy subset of the test was removed. I now understand that's not the case. A brainfart on my part :-)

**Comment by jnewbery** [comment]
> I'm not clear on why this test is racy.

Here's a possibility, although can't demonstrate without the log files:

- bitcoind is started in rpc_zmq.py L30
- the rpc server starts in init.cpp L1232 (`AppInitServers()`)
- there's then a race between:
    a) the test framework calling `getzmqnotifications` (rpc_zmq.py L31)
    b) the ZMQNotificationInterface being initialized in ` CZMQNotificationInterface::Create()` (init.cpp L1339)

If (a) wins, then `getzmqnotifications` will return an empty object. See zmqrpc.cpp L36:

```
    if (g_zmq_notification_interface != nullptr) {
    ...
    }
```

> Why is the race not a bug that should be fixed?

Not a bug. Just the test trying calling `getzmqnotifications` before the interface has been initialized.

**Comment by MarcoFalke** [comment]
> Not a bug. Just the test trying calling getzmqnotifications before the interface has been initialized.

How is this not a bug. The call should block and wait until the interface has been initialized? Similarly on how we block the wallet on calls until it has caught up with the chainstate, this call should block until all notifications have been activated/deactivated immediately prior to this call.

**Comment by jnewbery** [comment]
> How is this not a bug.

The help text for `getzmqnotifications` says "Returns information about the active ZeroMQ notifications." If you call the RPC before the interface is active, then it (correctly) returns an empty object since no notifications are active.

This is a little bit pedantic though. This is a tiny window condition which as far as I'm aware can only be hit in Travis which has weird scheduling and delays. I don't think this can cause any problems for end-users actually using the zmq interface.

I opened this PR to unblock #14336, which I think is a far more important goal than making sure that the zmq interface gets initialized before `getzmqnotifications` returns. If you want to fix that, by all means go ahead, but I don't think doing so should block #14336.

**Pull request merged**
