### PR TITLE
C++11 build/runtime fixes

### PR DESCRIPTION
**Pull request by theuni**
In preparation for switching to the c++11 requirement, I've done depends builds on all supported OSs and fixed up any snags along the way.

Note that this does not enable c++11 anywhere, it simply enables c++11 builds to pass.

Once merged, we can begin moving forward with enabling.

### CODE REVIEW

**Comment by dcousens** [comment]
utACK

**Comment by fanquake** [comment]
conceptACK, will start testing shortly.

**Comment by jonasschnelli** [comment]
code review ACK.

**Comment by dcousens** [comment]
utACK 3968922

**Comment by MarcoFalke** [comment]
utACK  3968922

**Comment by jgarzik** [comment]
utACK

**Comment by sipa** [comment]
utACK

**Comment by paveljanik** [comment]
minor nits: new `configure` line output is:
```
checking for mismatched boost c++11 scoped enums... ok
```
Will we use C++11 like we use C++? Ie. capital C? Or is small c ok?

Can you please add a comment to `configure.ac` (e.g. reuse the commit message) above the new part?

Otherwise ACK
Thanks!

**Comment by laanwj** [comment]
utACK

**Pull request merged**
