### PR TITLE
Remove unused module from rpc-tests

### PR DESCRIPTION
**Pull request by 34ro**
remove unused python modules.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
utACK a432aa0aa83310f0eb053329fb4b2670ce92b1c6

**Comment by kallewoof** [comment]
utACK a432aa0

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/commit/a432aa0aa83310f0eb053329fb4b2670ce92b1c6

**Comment by JeremyRubin** [comment]
utACK, good finds!

**Comment by fanquake** [comment]
utACK a432aa0

**Comment by jnewbery** [comment]
tested ACK

**Comment by MarcoFalke** [comment]
utACK a432aa0aa83310f0eb053329fb4b2670ce92b1c6

**Pull request merged**
