### PR TITLE
refactor: Allow CScript construction from any std::input_iterator

### PR DESCRIPTION
**Pull request by maflcko**
Currently only (pre)vector iterators and raw pointers are accepted. However, this makes it harder to construct from input iterators provided by other classes, such as `std::span`.

Fix that.

### CODE REVIEW

**Comment by delta1** [comment]
Concept ACK dddd56c6eecfb0e0f53874355ee821f5bd6af556

Looks like a nice code change to me. "previous releases" CI is turning up an issue in script/interpreter 

```
script/interpreter.cpp: In function ‘bool EvalChecksigPreTapscript(const valtype&, const valtype&, prevector<28, unsigned char>::const_iterator, prevector<28, unsigned char>::const_iterator, unsigned int, const BaseSignatureChecker&, SigVersion, ScriptError*, bool&)’:
script/interpreter.cpp:325:44: error: no matching function for call to ‘CScript::CScript(prevector<28, unsigned char>::const_iterator&, prevector<28, unsigned char>::const_iterator&)’
  325 |     CScript scriptCode(pbegincodehash, pend);
  ```

**Comment by delta1** [comment]
> CI is turning up an issue in script/interpreter

looks like  a few issues in that file

**Comment by delta1** [comment]
@maflcko interesting, thanks for the context. does that mean that the previous releases CI job needs to be changed to user a newer gcc?

**Comment by delta1** [comment]
ACK [fa9ef95](https://github.com/bitcoin/bitcoin/pull/29369/commits/fa9ef95b4c1114e2d8f7c3307fdf01446efee6fd)

**Review by ajtowns — COMMENTED** [review]
utACK fa9ef95b4c1114e2d8f7c3307fdf01446efee6fd

LGTM. Could change `template<typename InputIterator>prevector(...)` to also expect `std::input_iterator`.

The prevector functions that take two iterators first increase the capacity by `last - first` then run `fill(ptr, first, last)` -- that's buggy if the passed in iterators specify a greater range than a `size_type` (or `difference_type` for `insert()`) can hold. Could perhaps be worth changing:

```diff
-    template<typename InputIterator>
-    void fill(T* dst, InputIterator first, InputIterator last) {
-        while (first != last) {
+    template<std::input_iterator InputIterator>
+    void fill(T* dst, InputIterator first, size_type n) {
+        while (n-- > 0) {
```

**Review by hernanmarino — COMMENTED** [review]
utACK fa40ae2dbd181b27371b91636652c9b408585384

**Comment by delta1** [comment]
reACK fa7b9b9

**Review by hodlinator — APPROVED** [review]
ACK fa7b9b99a2ed466d1765d748f4a59c2f581b974f

Verified that it resolved the issue I was having on other PR (https://github.com/bitcoin/bitcoin/pull/30377#discussion_r1719107583) through cherry-picking the commits in this PR, undoing the local workaround, and pushing to a personal GitHub branch 239709e194203e06bd1f0610059e00998f645d4c to see if Windows CI compiled it successfully, which it did (https://github.com/hodlinator/bitcoin/actions/runs/10419824929/job/28858657327).

nit: I'd prefer the removal of `value_type` from `prevector` was its own commit and the remaining changes were squashed into a second commit as they appear to belong closer together.

**Review by ryanofsky — APPROVED** [review]
Code review ACK fa7b9b99a2ed466d1765d748f4a59c2f581b974f

**Comment by ryanofsky** [comment]
> rfm with 5 acks on the first commit (2 stale and 3 current), and 3 acks on the second commit?

I haven't been merging anything just because I think we are in feature freeze https://github.com/bitcoin/bitcoin/issues/29891

**Comment by achow101** [comment]
ACK fa7b9b99a2ed466d1765d748f4a59c2f581b974f

**Review by theuni — COMMENTED** [review]
Post-merge utACK fa7b9b99a2ed466d1765d748f4a59c2f581b974f. I had a similar commit while hacking on allocators a while back: https://github.com/theuni/bitcoin/commit/3d34f21931226e7c39fb0cfcfe3581c3dfa3cc0f . This is even more elegant :)

**Pull request merged**
