### PR TITLE
Better error handling for submitblock

### PR DESCRIPTION
**Pull request by gmaxwell**
Check transaction count early in submitblock.

There is no point in even hashing a submitted block which doesn't have a coinbase transaction.

This also results in more useful error reporting on corrupted input.

Thanks to rawodb for the bug report.

### CODE REVIEW

**Comment by laanwj** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/10146/commits/30f30c0f99d21d6c8476c759104de5bb3218a188

**Comment by jonasschnelli** [comment]
utACK 30f30c0f99d21d6c8476c759104de5bb3218a188

**Comment by paveljanik** [comment]
utACK 30f30c0

**Comment by laanwj** [comment]
Reminder: this needs a functional test to prevent regression, but not necessary in this PR.

**Comment by jnewbery** [comment]
Regression test here: #10190

**Pull request merged**
