### PR TITLE
Addrman offline attempts

### PR DESCRIPTION
**Pull request by gmaxwell**
If a node is offline failed outbound connection attempts will crank up
the addrman counter and effectively blow away our state.

This change reduces the problem by only counting attempts made while
the node believes it has outbound connections to at least two
netgroups.

Connect and addnode connections are also not counted, as there is no
reason to unequally penalize them for their more frequent
connections -- though there should be no real effect from this
unless their addnode configureation is later removed.

Wasteful repeated connection attempts while only a few connections are
up are avoided via nLastTry.

This is still somewhat incomplete protection because our outbound
peers could be down but not timed out or might all be on 'local'
networks (although the requirement for multiple netgroups helps).

( reopen of #6030 )

### CODE REVIEW

**Comment by pstratem** [comment]
This should probably be checking for connections to at least two netgroups outside of RFC1918 IP space, but this is certainly an improvement.

**Comment by gmaxwell** [comment]
@pstratem checking connections is better than no check at all.  This PR is from April 2015, so I'm not inclined to expand the scope any further right now. If this is accepted I'll happily open a follow on PR to make it stronger.

**Comment by arowser** [comment]
Can one of the admins verify this patch?

**Comment by sipa** [comment]
Needs rebase.

**Comment by sipa** [comment]
Did you accidentally include #7992?

**Comment by sipa** [comment]
utACK 66cefd47194a8aa7478dbea9a1b96640febeeda7

**Comment by sipa** [comment]
Running a public node with #7960 #8007 #8065 #8080 #8082 #8084 #8086 for testing.

**Comment by sipa** [comment]
This should be easy to test manually: add a debug log entry above the info.nAttempts increment in CAddrMan::Attempt_(), and see how often it triggers with network connected and disconnected.

**Pull request merged**
