### PR TITLE
build: Drop ancient hack in gitian-linux descriptor

### PR DESCRIPTION
**Pull request by hebasto**
The hack was aimed to fix an issue in Ubuntu Trusty 14.04 (see #8188).
The current hack implementation was added in #8315.

On master (8db23349fe9b512e6801d59d17052c5a7a1c64df) this hack is effectively noop, and it is no longer needed.

I see this PR as a step to removing `libfaketime` from gitian builds.

### CODE REVIEW

**Comment by hebasto** [comment]
@theuni Mind reviewing this PR as it removes the code added by you?

**Comment by dongcarl** [comment]
My 2c: When I was writing the Guix scripts, I didn't include these hacks and the reproducibility worked out fine. I tried to build the Guix environment to be somewhat similar to the Ubuntu one, so I suspect this should work fine.

**Comment by dongcarl** [comment]
NACKish on the 1ba14962434c4ec78757e46a0e3f8cc0a2fa114c commit
- Dropping "ca-certificates" broke Gitian builds for me
- I prefer being explicit about everything we need instead of relying on the dependencies between packages

**Comment by hebasto** [comment]
Updated d3fe00d90d1aa630b508550ae1f172f41f454114 -> f9da9691631732eb621bfef3b159aeaa3c8a2ee1 ([pr19622.01](https://github.com/hebasto/bitcoin/commits/pr19622.01) -> [pr19622.02](https://github.com/hebasto/bitcoin/commits/pr19622.02), [diff](https://github.com/hebasto/bitcoin/compare/pr19622.01..pr19622.02)).

Addressed @dongcarl's [comment](https://github.com/bitcoin/bitcoin/pull/19622#issuecomment-666648155):
>  - Dropping "ca-certificates" broke Gitian builds for me
> 
>  - I prefer being explicit about everything we need instead of relying on the dependencies between packages

- all dependencies packages are installed explicitly, including the [`patch`](https://packages.ubuntu.com/bionic/patch) package
- all `gcc-8-{arch}` packages are dependencies of respective `g++-8-{arch}` packages, and their listing seems overkill
- missed `g++-{arch}` packages affect on `gcov` binary only, that is not used in gitian builds.

**Comment by fanquake** [comment]
> Dropped unused 'python3' package.

We need Python3 to run the security and symbol check scripts post build. I'd assume it's still being installed as a side-effect of another package.

**Comment by hebasto** [comment]
@fanquake 
> > Dropped unused 'python3' package.
> 
> We need Python3 to run the security and symbol check scripts post build. I'd assume it's still being installed as a side-effect of another package.

Indeed. I forgot about `symbol-check.py` and `security-check.py`.

**Comment by hebasto** [comment]
Updated f9da9691631732eb621bfef3b159aeaa3c8a2ee1 -> 33a84e8f405ed6dd8885419cef305b4e6c7a428a ([pr19622.02](https://github.com/hebasto/bitcoin/commits/pr19622.02) -> [pr19622.03](https://github.com/hebasto/bitcoin/commits/pr19622.03), [diff](https://github.com/hebasto/bitcoin/compare/pr19622.02..pr19622.03)).

Addressed @fanquake's [comment](https://github.com/bitcoin/bitcoin/pull/19622#issuecomment-669249503):
> We need Python3 to run the security and symbol check scripts post build. I'd assume it's still being installed as a side-effect of another package.

**Comment by laanwj** [comment]
Code review ACK 33a84e8f405ed6dd8885419cef305b4e6c7a428a
I would like to see at least one test that this is still deterministic, though.

**Comment by hebasto** [comment]
> I would like to see at least one tested ACK that this is still deterministic, though.

My hashes for comparison:
```
ae538b6274b08cf8c7a969ca26ec3e2980ddacb46a7bf4f76c47dd9f1eed63e9  bitcoin-33a84e8f405e-aarch64-linux-gnu-debug.tar.gz
48d19b6a5f7e98e5274b6fcb2fe7df3b3a93610bcf5c8d3db68fff6bff21e382  bitcoin-33a84e8f405e-aarch64-linux-gnu.tar.gz
2fd77cbc8c2f322c5c075547a3a2338f731ca055c2ac7f8a283a2a145e0bb54f  bitcoin-33a84e8f405e-arm-linux-gnueabihf-debug.tar.gz
3fc9ef07934ada253a724d50f13eb0aa520ea05e6318e39b1d01e0959f1fec40  bitcoin-33a84e8f405e-arm-linux-gnueabihf.tar.gz
ceb2aaa73b100f96a8059c0807676f863e05c43160160a1fa66e4251a5129174  bitcoin-33a84e8f405e-riscv64-linux-gnu-debug.tar.gz
3d5228b95768ded5f23d5d5e74589f79ada1d8cb1551c75db48c57a51f3fd5c6  bitcoin-33a84e8f405e-riscv64-linux-gnu.tar.gz
6e56328ff4aed63fbdf4708b41e0003b8db07bf807a9331e426f3bebac02f547  bitcoin-33a84e8f405e-x86_64-linux-gnu-debug.tar.gz
60f36255cd3d6209195cee3656a1af9100777b1311f2b274f0c162e10e4c8488  bitcoin-33a84e8f405e-x86_64-linux-gnu.tar.gz
e05a8d8acb85fa7b8639510ed7a098157311cd1535a4fa6b950cdf28342d1529  src/bitcoin-33a84e8f405e.tar.gz
97a045ae326e5f0d19a11845f7ab9de2a15a68898b3cafed5edee3b637397cea  bitcoin-core-linux-0.21-res.yml
```

**Comment by dongcarl** [comment]
tACK 33a84e8f405e
```
- out_manifest: |
    ae538b6274b08cf8c7a969ca26ec3e2980ddacb46a7bf4f76c47dd9f1eed63e9  bitcoin-33a84e8f405e-aarch64-linux-gnu-debug.tar.gz
    48d19b6a5f7e98e5274b6fcb2fe7df3b3a93610bcf5c8d3db68fff6bff21e382  bitcoin-33a84e8f405e-aarch64-linux-gnu.tar.gz
    2fd77cbc8c2f322c5c075547a3a2338f731ca055c2ac7f8a283a2a145e0bb54f  bitcoin-33a84e8f405e-arm-linux-gnueabihf-debug.tar.gz
    3fc9ef07934ada253a724d50f13eb0aa520ea05e6318e39b1d01e0959f1fec40  bitcoin-33a84e8f405e-arm-linux-gnueabihf.tar.gz
    ceb2aaa73b100f96a8059c0807676f863e05c43160160a1fa66e4251a5129174  bitcoin-33a84e8f405e-riscv64-linux-gnu-debug.tar.gz
    3d5228b95768ded5f23d5d5e74589f79ada1d8cb1551c75db48c57a51f3fd5c6  bitcoin-33a84e8f405e-riscv64-linux-gnu.tar.gz
    6e56328ff4aed63fbdf4708b41e0003b8db07bf807a9331e426f3bebac02f547  bitcoin-33a84e8f405e-x86_64-linux-gnu-debug.tar.gz
    60f36255cd3d6209195cee3656a1af9100777b1311f2b274f0c162e10e4c8488  bitcoin-33a84e8f405e-x86_64-linux-gnu.tar.gz
    e05a8d8acb85fa7b8639510ed7a098157311cd1535a4fa6b950cdf28342d1529  src/bitcoin-33a84e8f405e.tar.gz
```

**Pull request merged**
