### PR TITLE
rpc: Avoid "duplicate" return value for invalid submitblock

### PR DESCRIPTION
**Pull request by maflcko**
When `submitblock` of an invalid block, the return value should not be `"duplicate"`.

This is only seen when the header was previously found (denoted by the incorrectly named boolean `fBlockPresent`). Fix this bug by removing `fBlockPresent`.

### CODE REVIEW

**Comment by practicalswift** [comment]
Is @DrahtBot a new addition to the project? Who is the bot owner? :-)

**Comment by promag** [comment]
utACK. Nit, `Result: ` help could be improved.

**Comment by TheBlueMatt** [comment]
This breaks having two submitblocks in paralell. Now instead of one returning true and the other duplicate, you might have one return true and one simply return "inconclusive". I think the correct fix is to just set fBlockPresent to pindex->nStatus & HAVE_DATA.

**Comment by MarcoFalke** [comment]
@TheBlueMatt I don't see how this fixes the race. The only other option I see is to partially revert the commit that introduced the bug (eb63bf86cf6dc99f150574463df6ffb013a34493), i.e. read from mapBlockIndex *after* `ProcessNewBlock`.

**Comment by TheBlueMatt** [comment]
Ah, indeed, must have been introduced on master when ProcessNewBlock lost its cs_main at call-time. Obvious fix would be to duplicate the fBlockPresent check after PNB by re-acquiring cs_main.

**Comment by skeees** [comment]
utACK

Maybe DrahtBot can rebase my PR for me once this is merged ;-)

**Comment by MarcoFalke** [comment]
I force pushed the commit with one change:

* `return "duplicate" when `fNewBlock` is given as false from PNB

Should be easy to re-ACK

**Comment by MarcoFalke** [comment]
Added a TODO to properly set fNewBlock when a new invalid block is sent, that fails ABH. (I am not going to touch that ABH code in this pull request, since my main goal is to fix invalid return for the rpc)

**Comment by jnewbery** [comment]
utACK fa08ebd7f24fc911b1af14644e4e235b6f3f9316

**Comment by promag** [comment]
re-utACK fa08ebd.

**Comment by jnewbery** [comment]
Why close?

**Comment by MarcoFalke** [comment]
> Why close?

To indicate that it was up for grabs.

**Comment by jnewbery** [comment]
> To indicate that it was up for grabs.

I don't get it. If this is up for grabs you think it should be merged, but you don't want to maintain it? It's currently mergeable and has ACKs. Why not just leave it open?

**Comment by TheBlueMatt** [comment]
Please see #13439. The changes here weren't sufficient, needed one more commit to actually fix the issue mentioned.

**Comment by jnewbery** [comment]
Got it. Good to know. Thanks Matt!

**Pull request closed without merging**
