### PR TITLE
qa: Remove polling loop from test_runner

### PR DESCRIPTION
**Pull request by maflcko**
My initial design for parallel tests was a busy loop (busy waiting) that polls the running processes every half a second.

Using pythons own `ThreadPoolExecutor` makes the code smaller and hopefully easier to read/understand. By removing the half-a-second overhead, I believe the tests run now slightly faster (Verified on my workstation, but should also be verified by one of the reviewers, ideally)

This is refactoring beside the following changes:
* Dropped the dot-printing (....) while waiting for the next result
* `--failfast` will now wait for unfinished jobs (similar to a failure in `make`)
* The `portseed_offset` is no longer applied. This is no longer required since we already kill leftover processes (see #12904). This "fixes" #10869 because we deterministically pick ports starting at 11000

### CODE REVIEW

**Comment by laanwj** [comment]
I don't see difference with regard to run time:
```
with
real    3m54.986s
real    3m56.017s
real    4m0.519s
real    3m45.475s
real    3m57.155s

without
real    3m51.195s
real    3m54.101s
real    3m53.719s
real    4m1.334s
real    3m53.727s
```
However I like the code cleanup and it doesn't make it worse so utACK fa35a022e929948ee13b76093ab5c9907f3c4209

**Comment by laanwj** [comment]
Seems that with this change, Ctrl-C does no longer quit the test runner immediately when the tests have started, looks like it has to be pressed twice.

> Dropped the dot-printing (....) while waiting for the next result

I suddenly remember that this was added to prevent Travis from timing out due to no output. Is that no longer a concern?

**Comment by MarcoFalke** [comment]
> I suddenly remember that this was added to prevent Travis from timing out due to no output. Is that no longer a concern?

The run time is between 2 and 3 minutes. And travis would only time out after 10 minutes of no dots received. The extended tests are not run on travis for a couple of weeks now, so I can't answer that...

**Comment by MarcoFalke** [comment]
Closing for now. Not really worth the effort

**Pull request closed without merging**
