### PR TITLE
wallet: Simplify logic in CCryptoKeyStore::AddKeyPubKey(...)

### PR DESCRIPTION
**Pull request by practicalswift**
Simplify logic in `CCryptoKeyStore::AddKeyPubKey(...)`.

### CODE REVIEW

**Review by eklitzke — COMMENTED** [review]
drive by review but, lgtm

**Comment by promag** [comment]
ACK d4761db.

**Comment by MarcoFalke** [comment]
This pattern is used throughout the code base. Also, not everyone might agree that this "simplifies the logic".

Closing the refactoring pull according to the developer notes.

**Review by ryanofsky — COMMENTED** [review]
ACK d4761db2dd77f5924e6b83b6206164892f98465b

**Pull request closed without merging**
