### PR TITLE
doc: Update the used Qt version

### PR DESCRIPTION
**Pull request by hebasto**
Missed in bitcoin/bitcoin#23489.

### CODE REVIEW

**Review by w0xlt — APPROVED** [review]
ACK d67fc78

**Review by shaavan — APPROVED** [review]
ACK d67fc786d9978927e317fd313d6666fbc2d6a31e

A minor but crucial change.
- Verified that the version by our codebase has been bumped up from `5.12.11` -> `5.15.2` in #23489.
- This change was not reflected in depend docs until now, which this PR fixes.

**Review by prusnak — APPROVED** [review]
ACK d67fc78

**Review by promag — COMMENTED** [review]
ACK d67fc786d9978927e317fd313d6666fbc2d6a31e.

**Pull request merged**
