### PR TITLE
Updated text on send confirmation dialog

### PR DESCRIPTION
**Pull request by dannmat**
I have changed the text on the send confirmation dialog, as it still referenced BIP 125 (which was first proposed back in 2015).
I don't think users need to see which BIP proposed the change 4 years later.

I also changed the title text to be more user friendly.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
The issue with changing translated strings is that all translations in all languages get discarded. This has to be weight against the benefit of the new string.

**Comment by laanwj** [comment]
It's too late for 0.20.0, the strings and translations freeze are past. Could consider after the branch-off though.

**Comment by jonasschnelli** [comment]
I prefer the new (in this PR) text. Seems more clear and user focused. Comparing screenshots would be nice.
utACK 7237f928118f3ab2df4a905304ef9141f150e2d4 (for 0.21).

**Comment by dannmat** [comment]
> I prefer the new (in this PR) text. Seems more clear and user focused. Comparing screenshots would be nice.
> utACK [7237f92](https://github.com/bitcoin/bitcoin/commit/7237f928118f3ab2df4a905304ef9141f150e2d4) (for 0.21).

Here is the modal pre-change:
Bitcoin Core Send Modal (pre-change)

Here is the modal post-change:
Bitcoin Core Send Modal (post-change)

The changes aren't too noticeable on Mac, it's more for Windows/Linux, which make use of the `windowTitle` property.

**Comment by luke-jr** [comment]
"signaling" at least should be lowercase

I'm not sure the BIP 125 reference is obsolete, though - it's the specification itself for a policy, not a one-off change.

**Comment by jonasschnelli** [comment]
Needs rebase.

**Comment by adamjonas** [comment]
I'm getting post-rebase build errors consistent with the CI. @dannmat mind taking a look?

```
qt/sendcoinsdialog.cpp:337:13: error: use of undeclared identifier 'questionString'; did you mean 'question_string'?
            questionString.append(tr("You can increase the fee later (Signaling Replace-By-Fee)."));
            ^~~~~~~~~~~~~~
            question_string
qt/sendcoinsdialog.cpp:223:48: note: 'question_string' declared here
bool SendCoinsDialog::PrepareSendText(QString& question_string, QString& informative_text, QString& detailed_text)
                                               ^
qt/sendcoinsdialog.cpp:339:13: error: use of undeclared identifier 'questionString'; did you mean 'question_string'?
            questionString.append(tr("You cannot increase the fee later (Not signalling Replace-By-Fee)"));
            ^~~~~~~~~~~~~~
            question_string
qt/sendcoinsdialog.cpp:223:48: note: 'question_string' declared here
bool SendCoinsDialog::PrepareSendText(QString& question_string, QString& informative_text, QString& detailed_text)
```

**Comment by dannmat** [comment]
Yep I can take a look at this 👍

**Comment by fanquake** [comment]
Hi @dannmat. This is a fairly simple wording change, but as-is, it doesn't compile, and the commits needs cleaning up. If you do still want to follow up with this change, I'm going to suggest re-opening your PR in the gui repo: https://github.com/bitcoin-core/gui. There are currently a few other tooltip/text related PRs open there as well.

**Comment by dannmat** [comment]
Hi @fanquake. Sorry I didn't get chance to clean this commit up. I'll re-open this in the new gui repo.

Thanks,
Matt

**Pull request closed without merging**
