### PR TITLE
[doc] Fix broken Markdown table in dependencies.md

### PR DESCRIPTION
**Pull request by practicalswift**
Changes made to `dependencies.md`:
* Fix broken table Markdown.
* Use correct capitalization.
* Sort dependencies.
* Minor cleanups.

### CODE REVIEW

**Comment by MeshCollider** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/11264/commits/bab6604f8bfc5fc4344280d28bdca88cc3b47a2f

Nice catch so quickly, pretty big formatting fail :+1: Must have happened when the "latest available" column was removed and no one checked the formatting after that

**Comment by practicalswift** [comment]
Triggering a new Travis build to get rid of the spurious build error :-)

**Comment by flack** [comment]
Strange, I was sure I looked at it in github's preview renderer after I removed the column. But good that you caught it!

**Comment by fanquake** [comment]
utACK after squashing your commits, and adding [Doc] etc
Here is how it appears now:
markdown

**Pull request merged**
