### PR TITLE
Scripts and tools: Add sudoers.d, rc.local from docs to gitian script

### PR DESCRIPTION
**Pull request by JeremyRand**
The docs at https://github.com/bitcoin-core/docs/blob/master/gitian-building/gitian-building-setup-gitian-debian.md instruct to create a `sudoers.d` entry and an `rc.local` script.  This PR brings `gitian-build.py` in line with those instructions.  Without this PR, running `gitian-build.py` from a stock Debian Buster VM fails due to the missing `br0`, and also prompts for sudo permissions frequently due to the missing `sudoers.d` entry.

Note that this PR (and the existing instructions on which it is based) are suboptimal, as they will clobber an existing `rc.local` if one exists.  I'm open to suggestions on improving this (maybe putting it in `/etc/init.d/` instead?), though I think that if an improvement is made, it should be applied both to the English instructions and the automated script in order to keep them consistent.

### CODE REVIEW

**Comment by hebasto** [comment]
This PR makes `gitian-build.py` more Debian/Ubuntu specific. I'd rather move in the opposite direction -- to a distro-agnostic script.

**Comment by JeremyRand** [comment]
> This PR makes gitian-build.py more Debian/Ubuntu specific. I'd rather move in the opposite direction -- to a distro-agnostic script.

@hebasto I'd have no objection to this in principle, although the existing script is definitely specific to Debian/Ubuntu-style distros as-is (e.g. it uses `apt-get`).  Even if the script is modified to support other distros, I don't think it should be made less useful for Debian/Ubuntu (i.e. I'd have no objection to only doing Debian/Ubuntu-specific stuff on those distros, but I think automating as much as possible on Debian/Ubuntu is a feature, not a bug).

**Comment by laanwj** [comment]
I'd prefer for a script like this to not make system-wide permanent changes. I guess it could tell the user to do so if it is needed, but adding something to suders automatically feels almost like adding a backdoor :laughing:

**Comment by MarcoFalke** [comment]
Agree on that. On the same note we should remove the `apt-get install` calls and instead tell the user that those are a requirement

**Comment by fanquake** [comment]
Going to close this, as the consensus seems to be that we don't want to add these calls.

An alternative PR could remove the `apt-get` calls and add requirements to the docs.

**Pull request closed without merging**
