### PR TITLE
[Qt][RPC] Autocomplete commands for 'help' command in debug console

### PR DESCRIPTION
**Pull request by achow101**
Puts the commands in the autocompletion box when doing a `help <command>` command in the debug console.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Nice. Concept ACK. Will test soon.

**Review by jonasschnelli — APPROVED** [review]
tested ACK 6d8fe35b94c660654020c876d6c1862b2d4f0397

bildschirmfoto 2017-01-10 um 17 09 26

**Comment by sipa** [comment]
Neat. Concept ACk

**Comment by MarcoFalke** [comment]
utACK 6d8fe35b94c660654020c876d6c1862b2d4f0397

So the only thing left is autocompletion for nested calls :)

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/commit/6d8fe35b94c660654020c876d6c1862b2d4f0397

**Comment by kallewoof** [comment]
ACK 6d8fe35

**Comment by fanquake** [comment]
Tested 6d8fe35 on OS X. Appears as below:
screen shot 1
screen shot 2

**Pull request merged**
