### PR TITLE
Extend support for nested commands to bitcoin-cli

### PR DESCRIPTION
**Pull request by jonasschnelli**
Currently, only the GUI supports nested commands like `getblock(getblock(getbestblockhash())[previousblockhash])[size]` (just an example) (see #7783).

This PR extends the support for nested commands to bitcoin-cli (entirely client side).

See https://github.com/bitcoin/bitcoin/blob/0.20/src/qt/rpcconsole.cpp#L397 for more information.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
The first commit might help to avoid reviewing moved code.

**Comment by kristapsk** [comment]
Tests are failing for me.
```
rpc_deriveaddresses.py --usecli       | ✖ Failed  | 2 s
wallet_createwallet.py --usecli       | ✖ Failed  | 2 s
wallet_multiwallet.py --usecli        | ✖ Failed  | 2 s
wallet_watchonly.py --usecli          | ✖ Failed  | 1 s
```
Failing with `test_framework.authproxy.JSONRPCException: Requested wallet does not exist or is not loaded (-18)`.

**Comment by jonasschnelli** [comment]
@kristapsk: should be fixed now.
What currently won't work is nested commands in conjunction with descriptors. I'll work on a fix soon.

**Comment by ajtowns** [comment]
The command line already lets you do nested calls natively, eg:

```sh
$ bitcoin-cli getblock $(bitcoin-cli getblockheader $(bitcoin-cli getbestblockhash) | jq -r .previousblockhash) | jq -r .size
```

You could use shell aliases to reduce typing:

```sh
$ bc () { bitcoin-cli "$@"; }
$ bcfield () { local F="$1"; shift; bitcoin-cli "$@" | jq -r "$F"; }
$ bcfield size getblock $(bcfield previousblockhash getblockheader $(bc getbestblockhash))
```

Personally, the only time it makes a difference to me is when I want to quickly query blocks around a particular height (eg `for a in {100..200}; do bitcoin-cli getblockheader @$a; done | grep versionHex`), so the approach in #16439 is quicker and easier (less typing and don't have to deal with brackets). Otherwise I'm pretty much writing a script, and the extra typing/aliases is no big deal.

**Comment by jonasschnelli** [comment]
@ajtowns: Good point. Yes. You can also do it with shell magic. Though you could also argue that writing a shell alias (or short script) could replace bitcoin-cli entirely (use cURL instead). Also for #16439, a shell alias/script would be trivial.

I guess bitcoin-cli is a utility. Something that should allow one to perform a task quick and fast (to not make you use cURl or other low level http/RPC clients).

This PR is not a replacement for #16439. It goes in a similar direction and may allow solve the same issues.

IMO this PR extends the `power-commands` (nested options plus subelement access) we have in the GUI to the CLI which I think is desirable (also for further extensions).

**Comment by ajtowns** [comment]
> @ajtowns: Good point. Yes. You can also do it with shell magic. Though you could also argue that writing a shell alias (or short script) could replace bitcoin-cli entirely (use cURL instead). Also for #16439, a shell alias/script would be trivial.

More or less: the disadvantage of a shell alias (eg `bitcoin-cli getblockheader $(bcbest)`) is that the alias can't inherit `-conf`, `-datadir`, `-testnet`, `-signet`, or `-regtest` from the "parent" bitcoin-cli command, while `getblockheader(getbestblockhash)` or `@best` will automatically adapt to the right context.

For me, that matters when I'm doing a quick oneliner, but not when I'm doing anything more complicated. YMMV obviously.

**Comment by jonasschnelli** [comment]
> More or less: the disadvantage of a shell alias (eg bitcoin-cli getblockheader $(bcbest)) is that the alias can't inherit -conf, -datadir, -testnet, -signet, or -regtest from the "parent" bitcoin-cli command, while getblockheader(getbestblockhash) or @best will automatically adapt to the right context.

Indeed. That would also speak for this PR over shell aliases.

I think #16439 could be integrated into this PR. There could be special commands like `@best` or `@H(400000)` that just translates into `getbestblockhash()` or `getblockhash(400000)`.

**Comment by jonatack** [comment]
Concept ACK

**Comment by theStack** [comment]
Concept ACK

**Comment by jonasschnelli** [comment]
Rebased

**Comment by prayank23** [comment]
Concept ACK

Compiled successfully on Ubuntu 20.04.2 LTS. Tests passed.

I am not sure about the correct syntax for nesting so got error without quotes. 

Error:

```
satoshi@ubuntu:~$ bitcoin-cli getblock(getblock(getbestblockhash())[previousblockhash])[tx][0]

bash: syntax error near unexpected token `('
```
With quotes:

```
satoshi@ubuntu:~$ bitcoin-cli "getblock(getblock(getbestblockhash())[previousblockhash])[tx][0]"

c06f7c267bae5c5994cd4584f930f4c4800170c4ecb96ebf6290b6956dc23303
```

**Comment by prayank23** [comment]
> including a mini programming langauge seems to me to be asking for trouble

Security? Interesting point. Although GUI console has limited access and usage, can we try few things in it? Or enable this only for testnet, regtest etc. and experiment for few weeks/months?

**Comment by kristapsk** [comment]
> I am not sure about the correct syntax for nesting so got error without quotes.

@prayank23, that's issue of shell, nothing we can do about here, just `echo (` in bash will fail too.

**Comment by prayank23** [comment]
> that's issue of shell, nothing we can do about here, just echo ( in bash will fail too.

Okay. I was interested in this PR because nesting helps in creating scripts for specific tasks. I have used `cmdlets` in PowerShell, the pipe symbol is used when one cmdlet pipes a result to another cmdlet. For example, 

`Get-MsolUser | Set-MsolUser -PasswordNeverExpires $true)`
Will perform a task (Set one parameter `true`) on all the results returned in the first cmdlet.

A similar thing in Bitcoin Core can be:

`listunspent 100 9999999 | setlabel "100 Conf UTXO"`

**Pull request closed without merging**
