### PR TITLE
wallet: Reset BerkeleyDB handle after connection fails

### PR DESCRIPTION
**Pull request by real-or-random**
According to the BerkeleyDB docs, the DbEnv handle may not be accessed
after close() has been called. This change ensures that we create a new
handle after close() is called. This avoids a segfault when the first
connection attempt fails and then a second connection attempt tries to
call open() on the already closed DbEnv handle.

Without the patch, bitcoindd reliably crashes in the second call to `set_lg_dir()` after `close()` if 
there is an issue with the database:
```
2018-05-03T13:27:21Z Bitcoin Core version v0.16.99.0-a024a1841-dirty (debug build)
[...]
2018-05-03T13:27:21Z Using wallet directory /home/tim/.bitcoin
2018-05-03T13:27:21Z init message: Verifying wallet(s)...
2018-05-03T13:27:21Z Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)
2018-05-03T13:27:21Z Using wallet wallet.dat
2018-05-03T13:27:21Z BerkeleyEnvironment::Open: LogDir=/home/tim/.bitcoin/database 
2018-05-03T13:27:21Z BerkeleyEnvironment::Open: Error -30974 opening database environment: DB_RUNRECOVERY: Fatal error, run database recovery
2018-05-03T13:27:21Z Moved old /home/tim/.bitcoin/database to /home/tim/.bitcoin/database.1525354041.bak. Retrying.
2018-05-03T13:27:21Z BerkeleyEnvironment::Open: LogDir=/home/tim/.bitcoin/database ErrorFile=/home/tim/.bitcoin/db.log
[1]    14533 segmentation fault (core dumped)  ./src/bitcoind
```

After the fix: 
```
2018-05-03T17:19:32Z Bitcoin Core version v0.16.99.0-cc09e3bd0-dirty (release build)
[...]
2018-05-03T17:19:32Z Using wallet directory /home/tim/.bitcoin
2018-05-03T17:19:32Z init message: Verifying wallet(s)...
2018-05-03T17:19:32Z Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)
2018-05-03T17:19:32Z Using wallet wallet.dat
2018-05-03T17:19:32Z BerkeleyEnvironment::Open: LogDir=/home/tim/.bitcoin/database ErrorFile=/home/tim/.bitcoin/db.log
2018-05-03T17:19:32Z scheduler thread start
2018-05-03T17:19:32Z BerkeleyEnvironment::Open: Error -30974 opening database environment: DB_RUNRECOVERY: Fatal error, run database recovery
2018-05-03T17:19:32Z Moved old /home/tim/.bitcoin/database to /home/tim/.bitcoin/database.1525367972.bak. Retrying.
2018-05-03T17:19:32Z BerkeleyEnvironment::Open: LogDir=/home/tim/.bitcoin/database ErrorFile=/home/tim/.bitcoin/db.log
2018-05-03T17:19:32Z Cache configuration:
2018-05-03T17:19:32Z * Using 2.0MiB for block index database
2018-05-03T17:19:32Z * Using 8.0MiB for chain state database
2018-05-03T17:19:32Z * Using 440.0MiB for in-memory UTXO set (plus up to 286.1MiB of unused mempool space)
2018-05-03T17:19:32Z init message: Loading block index..
[...]
```

### CODE REVIEW

**Comment by jamesob** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/13161/commits/264c64380978d7b0bd3ecb56a861eb004cc58b01

Nice first contribution.

**Comment by fanquake** [comment]
Concept ACK. 
@real-or-random  What are you doing to simulate an issue with the database?

**Comment by real-or-random** [comment]
Oh it was not simulated, the error was real. The log file says
```
Unacceptable log file /home/tim/.bitcoin/database/log.0000000001: unsupported log version 19
Invalid log file: log.0000000001: Invalid argument
PANIC: Invalid argument
process-private: unable to find environment
```
(I guess the last line appeared only later after bitcoind moved away the database directory.)
Any idea what could be the reason for this?

For testing, I can reliable reproduce the database issue by moving the old database directory back in place.

**Comment by real-or-random** [comment]
Not really related but I think I know what caused the database error: The wallet was initially created with the official Arch Linux version, which is configured `--with-incompatible-bdb` (I didn't know that), and then I tried to open the wallet with a version built against bdb 4.8.

**Comment by ryanofsky** [comment]
Would a simpler fix just be to drop the `dbenv->close(0);` line? Adding more initialization steps and  resetting fDbEnvInit and fMockDb members would seem to make the retry code a little more convoluted than it needs to be. It also doesn't seem good that the `close` return value isn't checked and nothing is logged if it failed (also true before this PR).

I also wonder if we could add a unit test or functional test to exercise this code. One way could be to create a dummy `pathIn / "database"` file and checking to make sure it gets renamed to `database.{time}.bak` and the wallet still gets loaded successfully.

**Comment by real-or-random** [comment]
The documentation says we need the close():
 > If DbEnv::open() fails, the DbEnv::close() method must be called to discard the DbEnv handle.
(see https://docs.oracle.com/cd/E17275_01/html/api_reference/CXX/envopen.html)

I've added proper logging if the close() fails.

I'm not sure if a test is that helpful but I can certainly add one if people think it's a good idea.

**Review by ryanofsky — COMMENTED** [review]
utACK b6f0b4d8595df0241a6499cd57e7ddac56558bf1. Thanks for the fix!

**Comment by sipa** [comment]
Concept ACK

**Comment by laanwj** [comment]
utACK b6f0b4d8595df0241a6499cd57e7ddac56558bf1

**Comment by hbxia** [comment]
Hi Tim, I still meet the similar issue with the latest code (already has your fix):

2018-05-25T02:14:01Z HTTP: creating work queue of depth 16
2018-05-25T02:14:01Z No rpcpassword set - using random cookie authentication
2018-05-25T02:14:01Z Generated RPC authentication cookie /root/.bitcoin/.cookie
2018-05-25T02:14:01Z HTTP: starting 4 worker threads
2018-05-25T02:14:01Z Using wallet directory /root/.bitcoin/wallets
2018-05-25T02:14:01Z init message: Verifying wallet(s)...
2018-05-25T02:14:01Z Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)
2018-05-25T02:14:01Z Using wallet wallet.dat
2018-05-25T02:14:01Z BerkeleyEnvironment::Open: LogDir=/root/.bitcoin/wallets/database ErrorFile=/root/.bitcoin/wallets/db.log
Segmentation fault

My server info:
Linux iZbp18y166co7d3pw5qf79Z 4.4.0-98-generic #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

BTW, official downloaded BIN bitcoind has no issue on my server, but manually build bitcoind.

Thanks

**Comment by real-or-random** [comment]
Hm, your problem should not be related to this pull request.

These are the build instructions:
https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md#linux-distribution-specific-instructions
If you still encounter the problem, I'd recommend you to open a new issue and paste the contents of the ErrorFile as mentioned in the log.

**Comment by hbxia** [comment]
Tim, thanks for your info. My current work around is to disable wallet "./configure --disable-wallet", because I do not need it so far.

**Pull request merged**
