### PR TITLE
[WIP] Fix: OSX QT compile fix: defer to bswap_XX when defined.

### PR DESCRIPTION
**Pull request by kallewoof**
Defer to (protobuf) defined `bswap_XX` macros when defined. This resolves compile errors for the QT client on OSX.

### CODE REVIEW

**Review by jonasschnelli — APPROVED** [review]
Makes sense.
Code Review utACK e62650b5d5fa643daf337031cb4cb914704dd346

**Comment by laanwj** [comment]
Yes, seems sensible. It's unfortunate that protobuf exports such common names as macros in their public interface.
The other way around would be to put `#undef bswap_XX` at the top. Don't have a clear preference though.

**Comment by kallewoof** [comment]
Protobuf detects and uses the OS defined OSSwapIntXX macros which might be a nice thing. Other than that yes I'm surprised they are as clumsy as they are considering it's Google.

**Comment by laanwj** [comment]
> Protobuf detects and uses the OS defined OSSwapIntXX macros which might be a nice thing

That would be a nice thing if you addded the same detection to our autoconf. The byteswap functions are mainly used in places that don't include (and can't depend on) protobuf.

Now this creates an inconsistency between compilation units that include protobuf and don't include protobuf, in unrelated code.

**Comment by kallewoof** [comment]
That makes a lot of sense. I will dig Monday.

**Comment by kallewoof** [comment]
I somehow messed the rebase up. Reopening. Sorry about that.

**Pull request closed without merging**
