### PR TITLE
Inline CTxInWitness inside CTxIn

### PR DESCRIPTION
**Pull request by sipa**
This is a rebase of #8452 on top of #8580.

### CODE REVIEW

**Comment by fanquake** [comment]
This needs a rebase.

**Comment by sipa** [comment]
@fanquake Planning to rebase this after #8580, which I'll rebase after #9039.

**Comment by sipa** [comment]
Rebased on top of the new #8580.

**Comment by sipa** [comment]
Rebased now #8580 is merged. Removes 80 lines of code!

**Comment by laanwj** [comment]
Testing #8589 #9283 #9288 #9589 on a reasonably busy public node.

**Comment by sipa** [comment]
I am curious what this myhtical #9589 is!

**Comment by gmaxwell** [comment]
ACK

**Comment by paveljanik** [comment]
Compiles cleanly utACK https://github.com/bitcoin/bitcoin/pull/8589/commits/f6fb7acda4aefd01b8ef6cd77063bfc0c4f4ab36

**Comment by laanwj** [comment]
> I am curious what this myhtical #9589 is!

#9289, sorry :)

**Comment by laanwj** [comment]
Slightly-tested ACK f6fb7ac

**Comment by morcos** [comment]
so much better
thanks!

**Pull request merged**
