### PR TITLE
Contrib scripts: Filter IPv6 by ASN

### PR DESCRIPTION
**Pull request by abitfan**
Improves IP diversity for hardcoded seednodes.

### CODE REVIEW

**Comment by laanwj** [comment]
Concept ACK

**Comment by practicalswift** [comment]
Concept ACK

**Comment by laanwj** [comment]
Tested ACK on the query part

one question though before I merge: are the IPv4 and IPv6 ASNs in a single namespace? if not, asn_count logic should take this into account

**Comment by abitfan** [comment]
Yes, they are in the same namespace (notice ip**v46**) only max_per_asn will be chosen, weather they're all v4 or v6 or a combination of v4+v6

**Pull request merged**
