### PR TITLE
[0.20] Fix GBT: Restore "!segwit" and "csv" to "rules" key

### PR DESCRIPTION
**Pull request by luke-jr**
Original branch merges cleanly (no rebase needed)

See also #17946

### CODE REVIEW

**Comment by jnewbery** [comment]
utACK 412d5fe8791c417bf46fc55a5bb8d59be98a33db

**Comment by fanquake** [comment]
These commits are missing the `Github-Pull` and `Rebased-From` metadata that we normally add  to backports.

**Comment by MarcoFalke** [comment]
The commit were written before the branch (and are located on top of a common ancestor of master+0.20) , so I think the script doesn't need the metadata.

**Comment by luke-jr** [comment]
@fanquake This isn't a backport per se; it's the original branch, exactly the same commits just merged into master.

**Comment by kcalvinalvin** [comment]
Appveyor is failing a test because the [commit](https://github.com/bitcoin/bitcoin/pull/17931) that fixed the error isn't included in this branch.

This commit is included in the ```0.20``` branch.

**Comment by MarcoFalke** [comment]
This is a two-line code fix with a two-line test. The risk of breaking something is low, so I think this can go into final without another rc. Thoughts?

**Comment by laanwj** [comment]
I would strongly prefer not to include any code change (no matter how minor) to the binaries in -final that is not in any rc.
As this is not a regression in 0.20, I think this can wait until 0.20.1.

**Review by Shaynefrost — APPROVED** [review]

**Pull request merged**
