### PR TITLE
util: Don't throw in GetTime{Millis,Micros}(). Mark as noexcept.

### PR DESCRIPTION
**Pull request by practicalswift**
* `boost::posix_time::ptime(boost::gregorian::date(1970,1,1)` throws `bad_year`, `bad_day_of_month`, or `bad_day_month` (derivatives of `std::out_of_range`) if the year, month or day are out of range. It is obvious to us that it won't throw at run-time for `1970-01-01`, but that is not obvious for the compiler or static analyzers. From a static analyzer perspective it will look like these exceptions can reach all the way up to `NodeImpl::appInitMain()` where they are unhandled.
* `boost::posix_time::from_time_t(0)` is simpler and doesn't throw. 
* Re-use the result of `boost::posix_time::from_time_t(0)` like we're doing in `DecodeDumpTime(…)`.
* Mark `GetTimeMillis()` and `GetTimeMicros()` as `noexcept`.

### CODE REVIEW

**Review by qmma70 — COMMENTED** [review]
Why not use `std::chrono::high_resolution_clock`?

**Comment by practicalswift** [comment]
@qmma70 I'm all for removing Boost, but that is something for another PR :-)

**Comment by sipa** [comment]
utACK bcdf285db285932365fe6cae17ba5a585cd1a17e

**Comment by Empact** [comment]
`noexcept` doesn't sit right with me her.
https://google.github.io/styleguide/cppguide.html#noexcept
https://akrzemi1.wordpress.com/2014/04/24/noexcept-what-for/

**Comment by sipa** [comment]
@Empact What in particular is an argument against noexcept here?

**Comment by Empact** [comment]
I guess I'm more wondering: what is the justification for it? If it doesn't help with significant performance optimizations (ala `move`) and we don't expect it to affect the error performance of the method (because we don't expect it to throw) then why should we apply the treatment? If we should apply it here, should we apply it to most methods? Just a notion.

**Comment by practicalswift** [comment]
@Empact Scott Meyers has this to say about `noexcept`: http://aristeia.com/EC++11-14/noexcept%202014-03-31.pdf – "Declare `noexcept` whenever possible" :-)

**Comment by ken2812221** [comment]
utACK afc97c731e407f87fae0385aa5c3a729981ca1aa

**Comment by MarcoFalke** [comment]
Looks like this is made obsolete by something like #9566?

**Comment by practicalswift** [comment]
@MarcoFalke Yes, guess so.

Perhaps I should close this PR? The interest in making `GetTime{Millis,Micros}()` `noexcept` seems to be quite low :-)

**Pull request closed without merging**
