### PR TITLE
init: Replace URL_WEBSITE with PACKAGE_URL

### PR DESCRIPTION
**Pull request by maflcko**
This is needed for rebranding efforts such as #18489

### CODE REVIEW

**Review by hebasto — COMMENTED** [review]
Tested facace8780e5d73b0fbdb71f1b2a7905dae4592c on Linux Mint 19.3:

```diff
$ diff -u ~/version-master ~/version-18503 
--- /home/hebasto/version-master	2020-04-02 15:27:50.139783797 +0300
+++ /home/hebasto/version-18503	2020-04-02 15:29:25.639331357 +0300
@@ -1,8 +1,8 @@
-Bitcoin Core version v0.19.99.0-41fa2926d
+Bitcoin Core version v0.19.99.0-facace878
 Copyright (C) 2009-2020 The Bitcoin Core developers
 
 Please contribute if you find Bitcoin Core useful. Visit
-<https://bitcoincore.org> for further information about the software.
+https://bitcoincore.org/ for further information about the software.
 The source code is available from <https://github.com/bitcoin/bitcoin>.
 
 This is experimental software.
```

It seems better to use the unified style for both links: with `<` and `>` or without them at all.

**Comment by MarcoFalke** [comment]
Whoopsie. Those chevrons are needed in the GUI to make the link clickable.

**Review by hebasto — APPROVED** [review]
ACK fad2f68353944c83cad7b77415645215ae3f1093, tested on Linux Mint 19.3:
Screenshot from 2020-04-02 16-04-04

All of the links are clickable.

**Review by fanquake — APPROVED** [review]
ACK fad2f68353944c83cad7b77415645215ae3f1093 - clicked a link.

**Pull request merged**
