### PR TITLE
ci: Use Ubuntu 24.04 Noble for asan,tsan,tidy,fuzz

### PR DESCRIPTION
**Pull request by maflcko**
23.10 will be EOL mid next year, so a bump is needed before then for the `master` branch (and possibly the `26.x` branch).

Doing the bump now is fine, because the clang version is pinned to 17 inside the CI tasks. So a default clang version change in the system image should not affect the tasks. Once clang-18 is available and the default in April next year (https://discourse.ubuntu.com/t/noble-numbat-release-schedule/35649#planned-and-potentially-disruptive-archive-wide-activities-2), the pinned version could be bumped (for CI tasks that require a pin, like tidy), or the pin can be removed (for CI tasks that usually do not require a pin, like fuzz or the sanitizers).

### CODE REVIEW

**Review by fanquake — APPROVED** [review]
ACK fad2392c5861a88a87cb8a03d2fc9773e178feb8

**Comment by fanquake** [comment]
Will be backported in #29011.

**Comment by TheCharlatan** [comment]
When I apply this patch and run `FILE_ENV="./ci/test/00_setup_env_native_tidy.sh" ./ci/test_run_all.sh`, I get
```
131.2 CMake Error at /usr/lib/llvm-17/lib/cmake/clang/ClangTargets.cmake:833 (message):
131.2   The imported target "libclang" references the file
131.2 
131.2      "/usr/lib/llvm-17/lib/libclang-17.so.1"
131.2 
131.2   but this file does not exist.  Possible reasons include:
131.2 
131.2   * The file was deleted, renamed, or moved to another location.
131.2 
131.2   * An install or uninstall procedure did not complete successfully.
131.2 
131.2   * The installation package was faulty and contained
131.2 
131.2      "/usr/lib/llvm-17/lib/cmake/clang/ClangTargets.cmake"
131.2 
131.2   but not all the files it references.
131.2 
131.2 Call Stack (most recent call first):
131.2   /usr/lib/llvm-17/lib/cmake/clang/ClangConfig.cmake:20 (include)
131.2   CMakeLists.txt:20 (find_package)
131.2 
131.2 
131.2 -- Configuring incomplete, errors occurred!
------
test_imagefile:16
--------------------
  14 |     COPY ./ci/test/00_setup_env.sh ./${FILE_ENV} ./ci/test/01_base_install.sh /ci_container_base/ci/test/
  15 |     
  16 | >>> RUN ["bash", "-c", "cd /ci_container_base/ && set -o errexit && source ./ci/test/00_setup_env.sh && ./ci/test/01_base_install.sh"]
  17 |     
--------------------
ERROR: failed to solve: process "bash -c cd /ci_container_base/ && set -o errexit && source ./ci/test/00_setup_env.sh && ./ci/test/01_base_install.sh" did not complete successfully: exit code: 1
```

**Comment by fanquake** [comment]
Looks like something similar (for LLVM 18) is being worked around upstream, by just creating the missing file: https://github.com/include-what-you-use/include-what-you-use/pull/1350.

**Comment by fanquake** [comment]
> Will be fixed in 17.0.6-2 once noble-proposed is released,

This has shipped, and `17.0.6-2` is available.

**Pull request merged**
