### PR TITLE
Remove excess logic.

### PR DESCRIPTION
**Pull request by practicalswift**
Replace …

```c++
if (foo)
  return true;
return false;
```

… with …

```c++
return foo;
```

Inspired by @kewde:s finding in #10164.

### CODE REVIEW

**Review by bulldozer00 — APPROVED** [review]

**Comment by JeremyRubin** [comment]
utack 9a763d4

**Comment by paveljanik** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/10175/commits/9a763d4f86fb2428bfcae6cad5326600ada10c11

**Comment by TheBlueMatt** [comment]
utACK 9a763d4f86fb2428bfcae6cad5326600ada10c11

**Comment by MarcoFalke** [comment]
utACK 9a763d4f86fb2428bfcae6cad5326600ada10c11

**Pull request merged**
