### PR TITLE
[release-notes.md] Remove alias

### PR DESCRIPTION
**Pull request by kallewoof**
They're the same person.

### CODE REVIEW

**Comment by sipa** [comment]
> They're the same person.

Citation needed.

**Comment by dougstrong77** [comment]
Who is the same person and what is a citation im new this ive tried games im thinking ive gotten paid for but i guess there not please help me under stand the way i can know whats mine .

**Comment by sipa** [comment]
@dougstrong77 I was making a joke. It's @kallewoof who was removing his own duplicated name.

**Comment by kallewoof** [comment]
Haha, I didn't notice it until now for some reason. As for citation, "this is me" by me. Should be valid enough, right? ;)

**Pull request merged**
