### PR TITLE
Fix typos in description.md and wallet_util.py

### PR DESCRIPTION
**Pull request by hanmz**
Fix typos in description.md.
`digestable` => `digestible`
`lenghts` => `lengths`

### CODE REVIEW

**Comment by hanmz** [comment]
> Please squash your commits according to https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#squashing-commits

OK DONE

**Review by kristapsk — APPROVED** [review]
ACK 03e36b3da093e2c23cf51b46f6901cb84ddbf867

**Review by brunoerg — APPROVED** [review]
utACK 03e36b3da093e2c23cf51b46f6901cb84ddbf867

**Review by alfonsoromanz — APPROVED** [review]
ACK 03e36b3da093e2c23cf51b46f6901cb84ddbf867

**Pull request merged**
