### PR TITLE
[Qt] fix rpc console font size to flexible metrics

### LINKED ISSUE #5897: font size too small in debug console.
I build with Qt5.

UI is fine with Qt5. normal UI works out-of-box for HIDPI monitor, except debug console.
the font is very small, and can not by adjusted by Ctr+mousewheel or Ctr+Key_Plus

because Mac uses pixel scale, so the UI might be usable on retina mac, but on Linux, there is no PixelRatio ( aka , always = 1.0) so the font should not be specified in fixed pixel size. but use QFontMetrics, or, just just use "points" .

### PR DESCRIPTION
**Pull request by jonasschnelli**
should fix #5897

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Font is no slightly bigger on my mac. But totally okay.

After:
bildschirmfoto 2015-03-14 um 12 39 03

Before:
bildschirmfoto 2015-03-14 um 12 41 55

**Comment by microcai** [comment]
works for me.

**Comment by microcai** [comment]
Linux/X11 KDE environment:  DPI = 192

screenshot before this patch applied

screenshot_bitcoin

screenshot with this patch applied
screenshot_bitcoin2

**Comment by jonasschnelli** [comment]
@microcai hmm... looks good but i don't have a idea why your font size of the time-cell has also changed.

**Comment by microcai** [comment]
@jonasschnelli I tried to use standard zoom method Ctrl+Key_PLUS

**Comment by luke-jr** [comment]
What does font-size:1em do differently than omitting the attribute?

**Comment by Diapolo** [comment]
Can you check if we use hard-coded px sizes in other places? Perhaps it's time to replace them?

**Comment by jonasschnelli** [comment]
@luke-jr: Good question. 1em as font-size should be the default if there is no style-changing elsewhere. Will check this soon.

@Diapolo: The question is how Qt deals with HiDPI. On OSX 12px font size will result in 24px on screen in HiDPI (as expected). On linux we just saw that it will stay on 12px. There (fonts) em metrics makes sense. For other hard-coded px values (widgets size, offsets) it could end up value-doubles on HiDPI depending of Qt's handling.
So yes for changing all font-sizes to em, no for px widget sizes and offsets.

**Comment by microcai** [comment]
to make things clear, zoom in pixel level is only supported in osx platform. both Linux and windows version of Qt just uses DPI. so 12px font stay in 12px font even under windows.

**Comment by luke-jr** [comment]
I would expect Qt to default to the user font size preference.

**Comment by jonasschnelli** [comment]
as @luke-jr proposed i just removed the `font-size: 1em` setting. This should result in the same behavior maybe it also detects some way of using the standard os font-sizes.
@microcai could you test again?

**Comment by microcai** [comment]
@jonasschnelli I alread did.

**Comment by jonasschnelli** [comment]
@microcai hows the result? without `1em` same as with? thanks.

**Comment by microcai** [comment]
@jonasschnelli just see the screenshot. there is barely visible difference with "1em" or without "1em"

**Comment by microcai** [comment]
@jonasschnelli  1em seems to be the default font size. so I can't really tell the difference either 1em or omit it altogether.

**Comment by laanwj** [comment]
Looks good to me, although I wonder why we ever added a fixed font size (in pixels!), that must have been a workaround for something.

**Comment by fanquake** [comment]
@laanwj Looks like it was introduced here c6aa86afc2fe8995bcb1036c9879f85ef335e295, nearly 3 years ago.

**Comment by laanwj** [comment]
OK, so I added it myself when I introduced this code. I don't remember why.

**Comment by laanwj** [comment]
Trying it out jogged my memory. Without font-size, and with font-size:1em it looks like:
untitled

The default monospace font size on Ubuntu is huge.

**Comment by luke-jr** [comment]
Meh, that's not too huge. If the terminal looks the same, I'd say it's expected. Surely Ubuntu lets users configure their defaults?

**Comment by jonasschnelli** [comment]
@laanwj It seems like that `font-size: <n>em;` does not have any effect. Or at least with values <1em. I tried 0.8 and 0.1em. Looks exact the same as with 1em. I also tried `10pt`. Looks also good but generate font-size difference between ubuntu/linux and osx. 

I created a HiDPI ubuntu VM and did take a closer look at bitcoin-qt HiDPI unter linux. There are many issues (icon sizes, splash-screen, overview screen, etc., etc,)

This PR goes into the right direction (removing fix `px` values) but will not solve the whole HiDPI issue.

**Comment by microcai** [comment]
@jonasschnelli what about using 12pt ?

**Comment by jonasschnelli** [comment]
@microcai using 12pt would enlarge the font-size on linux as well as on osx. 10pt would make sense but even there the font-size is about ~10-20% larger.
IMO we should just remove the font-size as it is in this PR.

**Comment by laanwj** [comment]
I really don't like the default font size on Linux. @luke-jr If you compare it with the normal, non-monospace font as used for the time and the tab titles it IS huge.

Thinking of that, maybe we should remove the monospace? Looks good here.

**Comment by luke-jr** [comment]
I want to compare it with the terminal program. Whenever possible, we should use an OS/user-defined look and feel, not try to second-guess it.

**Comment by laanwj** [comment]
The terminal, at least on Ubuntu, uses a less ugly font and also more
reasonably sized than whatever Qt chooses with 'monospace'. It's not
realistic to expect it to pick the same font as the OS's terminal. 

We *have* to make our own font decision here. There, picking using the
default (non-monospace) font seems safest.

**Comment by jonasschnelli** [comment]
non-monospace would look like this (see below).
I don't have a strong position here. There is not much of a difference between monospace and standard font in terms of usability of the rpc console.

bildschirmfoto 2015-03-19 um 21 40 09

**Comment by laanwj** [comment]
Looks good to me. We don't (as far as I see) use the fixed width property anywhere for formatting, so a proportional font does just as well and may even be more readable.

**Comment by jonasschnelli** [comment]
Removed the "monospace" font style. IMO safest solution.

**Pull request merged**
