### PR TITLE
test: Remove TODO comments to remove -txindex option

### PR DESCRIPTION
**Pull request by maflcko**

### CODE REVIEW

**Comment by jnewbery** [comment]
I think @amitiuttarwar is already working on removing these as a follow-up to #15159.

**Comment by MarcoFalke** [comment]
I wanted to get this in to 0.18.0 without a backport and I haven't seen a follow-up in the last two weeks. Though, happy to close my pull if someone want to take this over.

**Comment by amitiuttarwar** [comment]
I've been working on it & was close to putting up a PR, but its ok :) My changes are pretty similar. I can contribute an additional change to the `interface_rest` test to remove -txindex by updating to search for a mempool transaction.

**Comment by MarcoFalke** [comment]
Please open you pull request with the changes. I am happy to provide feedback on those.

**Pull request closed without merging**
