### PR TITLE
net: Use proxy server 127.0.0.1 if -proxy is specified without arguments (instead of continuing without proxy server)

### PR DESCRIPTION
**Pull request by practicalswift**
Use proxy server `127.0.0.1` if `-proxy` is specified without arguments (instead of continuing without proxy server).

Continuing without a proxy server when the end-user has specified `-proxy` may result in accidental loss of privacy. (The end-user might think he/she is using a proxy when he/she is not.)

Before this patch:

```
$ src/bitcoind -proxy
…
2020-09-23T00:24:33Z InitParameterInteraction: parameter interaction: -proxy set -> setting -listen=0
2020-09-23T00:24:33Z InitParameterInteraction: parameter interaction: -proxy set -> setting -upnp=0
2020-09-23T00:24:33Z InitParameterInteraction: parameter interaction: -proxy set -> setting -discover=0
2020-09-23T00:24:33Z InitParameterInteraction: parameter interaction: -listen=0 -> setting -listenonion=0
…
2020-09-23T00:24:33Z init message: Starting network threads...
```

`bitcoind` is now running *without* a proxy server (`GetProxy(…, …) == false`, `HaveNameProxy() == false`, etc.).

Note that the "-proxy set" log messages above which the end-user might interpret as "good, my traffic is now routed via the proxy".

After this patch:

```
$ src/bitcoind -proxy
…
2020-09-23T00:24:33Z InitParameterInteraction: parameter interaction: -proxy set -> setting -listen=0
2020-09-23T00:24:33Z InitParameterInteraction: parameter interaction: -proxy set -> setting -upnp=0
2020-09-23T00:24:33Z InitParameterInteraction: parameter interaction: -proxy set -> setting -discover=0
2020-09-23T00:24:33Z InitParameterInteraction: parameter interaction: -proxy set without argument -> setting -proxy=127.0.0.1
2020-09-23T00:24:33Z InitParameterInteraction: parameter interaction: -listen=0 -> setting -listenonion=0
…
2020-09-23T00:24:33Z init message: Starting network threads...
```

`bitcoind` is now running *with* a proxy server (`GetProxy(…, …) == true`, `HaveNameProxy() == true`, etc.).

### CODE REVIEW

**Comment by jonatack** [comment]
Interesting, TIL! Will look into this.

**Comment by laanwj** [comment]
Concept Meh. Good catch, but I think this should be an error. There is no such thing as a "default proxy server".

**Comment by practicalswift** [comment]
> Concept Meh. Good catch, but I think this should be an error.

Yes, I thought about that too. Perhaps that is the way to go. I don't have any strong opinion.

> There is no such thing as a "default proxy server".

Technically you're right of course, but I'd assume that >95% of our users use `-proxy=127.0.0.1` (which is equivalent to `-proxy=127.0.0.1:9050`).

FWIW, we already have a default proxy port (9050).

**Comment by laanwj** [comment]
> Yes, I thought about making it an error as an alternative. Perhaps that is the way to go. I don't have any strong opinion.

I personally like being really explicit about errors, and avoid ambiguity, especially where privacy is potentially concerned.

**Comment by practicalswift** [comment]
@laanwj I think you have a good point. Explicit is better than implicit. Closing this PR. Will fix it by printing an error message instead :)

**Pull request closed without merging**
