### PR TITLE
build/doc: update bitcoin_config.h packages, release process

### PR DESCRIPTION
**Pull request by jonatack**
- Bump PACKAGE_VERSION and PACKAGE_STRING in `build_msvc/bitcoin_config.h` from 0.17 to 0.18 (follow-up to 48ed65b).

- Update `doc/release_process.md` (follow-up to e47dc4f), new version visible [here](https://github.com/jonatack/bitcoin/blob/bitcoin_config-and-release_process-updates/doc/release-process.md).

- Perhaps worth backporting the version updates to 0.18.0.

### CODE REVIEW

**Comment by jonatack** [comment]
For info `PACKAGE_VERSION` seems to be used in a variety of places...

$ git grep PACKAGE_VERSION
```bash
Makefile.am:24:BITCOIN_WIN_INSTALLER=$(PACKAGE)-$(PACKAGE_VERSION)-win$(WINDOWS_BITS)-setup$(EXEEXT)
build_msvc/bitcoin_config.h:358:#define PACKAGE_VERSION "0.18.99"
doc/Doxyfile.in:41:PROJECT_NUMBER         = @PACKAGE_VERSION@
libbitcoinconsensus.pc.in:8:Version: @PACKAGE_VERSION@
share/setup.nsi.in:51:OutFile @abs_top_srcdir@/@PACKAGE_TARNAME@-@PACKAGE_VERSION@-win@WINDOWS_BITS@-setup.exe
share/setup.nsi.in:63:VIAddVersionKey ProductVersion "@PACKAGE_VERSION@"
share/setup.nsi.in:66:VIAddVersionKey FileVersion "@PACKAGE_VERSION@"
share/setup.nsi.in:101:    WriteRegStr HKCU "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$(^Name)" DisplayVersion "@PACKAGE_VERSION@"
src/secp256k1/libsecp256k1.pc.in:9:Version: @PACKAGE_VERSION@
```
...and PACKAGE_STRING appears to be unused, at least inside the codebase

$ git grep `PACKAGE_STRING`
```
build_msvc/bitcoin_config.h:349:#define PACKAGE_STRING "Bitcoin Core 0.18.99"
```

**Comment by laanwj** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/16080/commits/8afca323e371a7a191d874928046d6bf2fbbe072

Looks like the descriptors were bumped in #15528.
I don't think it's necessary to backport release process changes.

**Comment by MarcoFalke** [comment]
Agree that this doesn't need backport

**Comment by jonatack** [comment]
Thanks!

I mentioned backporting because in the tagged v0.18.0 release, PACKAGE_VERSION and PACKAGE_STRING in build_msvc/bitcoin_config.h are still set to 0.17 which may (or may not) cause issues for Visual Studio builds (see https://github.com/bitcoin/bitcoin/pull/11526).

**Comment by jonatack** [comment]
Appears @sipsorcery agreed to maintain it.

**Comment by sipsorcery** [comment]
utACK https://github.com/bitcoin/bitcoin/commit/8afca323e371a7a191d874928046d6bf2fbbe072.

Changing the PACKAGE* settings won't cause any problems for the msvc build. 

It's not strictly needed to update the build_msvc/bitcoin_config.h as part of the release process since the msvc build is for development/testing purposes only and neither it nor any artifacts produced from it are ever included in any bitcoin core downloads. But it also doesn't hurt and seems reasonable to keep them in sync.

**Comment by jonatack** [comment]
Thanks @sipsorcery. TIL.

**Pull request merged**
