### PR TITLE
Ephemeral Anchors

### PR DESCRIPTION
**Pull request by instagibbs**
Depends on https://github.com/bitcoin/bitcoin/pull/28948 and https://github.com/bitcoin/bitcoin/pull/28984

Replaces https://github.com/bitcoin/bitcoin/pull/26403 to refresh the conversation.

BIP text here: https://github.com/instagibbs/bips/blob/ephemeral_anchor/bip-ephemeralanchors.mediawiki

Example usage:
https://github.com/instagibbs/bolts/commits/zero_fee_commitment
https://github.com/instagibbs/lightning/commits/commit_zero_fees

TODO:
1) figure out what precisely to do in a reorg when ephemeral transactions are trying to enter the mempool(and write a test)
2) restrict ephemeral anchor value to 0 (future relaxation possible with more work/motivation)
3) rebased on top of master, add in trim ephemeral anchor tx functionality when they are at 0-fee package feerate

### CODE REVIEW

**Comment by ariard** [comment]
> BIP text here: https://github.com/instagibbs/bips/blob/ephemeral_anchor/bip-ephemeralanchors.mediawiki

"Be 0-fee”

This is uncertain to me how this rule works with trimmed HTLCs on LN commitment transactions making their fees non-zero, even assuming anchor outputs where second-stage txn are signed with 0-feerate.

Beyond, I think it should add an information section at destination of use-cases developers discouraging the usage of anyone-can-spend ephemeral anchor. Otherwise a time-sensitive package can be tampered by third-parties entering into replacement cycling games, without being a direct off-chain counterparty to the target transaction traffic.

**Comment by instagibbs** [comment]
@ariard I'd rather talk downstream details over here https://github.com/bitcoin/bips/pull/1524

**Comment by luke-jr** [comment]
>BIP text here: https://github.com/instagibbs/bips/blob/ephemeral_anchor/bip-ephemeralanchors.mediawiki

Node policy is not a subject matter for standardization in itself. It's the transaction format that the BIP (if there is one) should focus on, not speculative behaviour of individual nodes.

**Comment by ariard** [comment]
> @ariard I'd rather talk downstream details over here https://github.com/bitcoin/bips/pull/1524

Thanks good to me - Answered strong conceptual issues there.

**Comment by da2ce7** [comment]
@luke-jr 

> > BIP text here: https://github.com/instagibbs/bips/blob/ephemeral_anchor/bip-ephemeralanchors.mediawiki
> 
> Node policy is not a subject matter for standardization in itself. It's the transaction format that the BIP (if there is one) should focus on, not speculative behaviour of individual nodes.

This Proposed BIP brings a set of concepts that allows the community to communicate using a coherent language regarding what "Ephemeral Anchors" are. By defining this term in context of it would work, the community can reason about them in a clear and coherent manner, (no matter if they individuality choose to use them in their not policy or not).

It is my opinion that such a BIP proposal is perfectly applicable and beneficial toward the community communication goals:

>  An Informational BIP describes a Bitcoin design issue, or provides general guidelines or information to the Bitcoin community, but does not propose a new feature. [...]

**Comment by instagibbs** [comment]
I have another branch I'm going to likely pursue once 1p1c relay is further along: https://github.com/instagibbs/bitcoin/commit/fe67ffda0f74c1f9ef95b8b75f030828adec8da3

With v3 + sibling eviction, it makes sense to me to first open up the feature with current supported scriptpubkeys for when the output is considered dust.

This allows people to pick anyone can spend or shared keyed anchors. It also means any outputs can be dust, as long as they get spent.

Future updates can include:
1) `OP_1 <0xfees>` style scripts as in the current PR.
2) relaxation from V3: I suspect the cluster mempool interface will make the logic much simpler to extending it to be arbitrary tx topologies. This could allow batched CPFP and more.

**Comment by instagibbs** [comment]
closing this in favor of https://github.com/bitcoin/bitcoin/pull/30239

**Comment by parsaei889** [comment]
ندارم

**Comment by parsaei889** [comment]
عالی

**Comment by parsaei889** [comment]
خوب بود ممنون

**Pull request closed without merging**
