### PR TITLE
util: move MapIntoRange() for reuse in fuzz tests

### PR DESCRIPTION
**Pull request by fanquake**

### CODE REVIEW

**Comment by sipa** [comment]
This technique is actually used in a few other places in the codebase, though this is the only one that does it for 64-bit inputs and ranges; at least in `cache::compute_hashes` in `cuckoocache.h` and `FastMod` in `common/bloom.cpp`. It's also used in `bench/nanobench.h`, but I think that file is intended to stay dependencyless.

Perhaps it would make sense to have specific functions for both (e.g. FastReduce32, FastReduce64) and put them in an integer util file or so?

**Comment by jamesob** [comment]
Code review ACK https://github.com/bitcoin/bitcoin/pull/23760/commits/a8dc99f21cafaa8d37ea16bf9441872d5d653e09

Mergeable as it stands IMO, but what @sipa's saying probably makes sense too.

**Review by shaavan — COMMENTED** [review]
Concept ACK

Moving the MapIntoRange allows both `src/blockfilter.cpp` and `src/test/fuzz/golomb_rice.cpp` to access the function while removing unnecessary duplicated code.

The one small thing that bugs me is using static keywords with the utility function. To be honest, I could not clearly understand the reasoning behind using (or not using) the static keyword with a utility function. Still, I had not seen many `src/util` functions with a static keyword in its definition.

P.s.: I tried to comprehend the reasoning of static keyword, but I could not find a good reference for it. And I considered it is better to ask rather than to give an uninformed ACK.

**Comment by MarcoFalke** [comment]
I think using `static` in a header file is a way to embed the compiled function into every object file that uses it (as opposed to putting it into one object only and then linking that)?

**Comment by shaavan** [comment]
> embed the compiled function into every object file that uses it

So wouldn't it increase the memory used at runtime by the application? Is the speed boost provided by using `static` worth increasing memory usage?

**Comment by sipa** [comment]
Using `static` here means that indeed, every compilation unit gets its own copy of the function. But, on the other hand, it means it doesn't need to be emitted either if all call-sites can be inlined, which is almost certainly the case. So the practical effect is really that it appears 0 times in the overall compilation output rather than 1 time.

**Comment by MarcoFalke** [comment]
I guess changing `static` to `inline` here wouldn't change the binary, but clarify the intent a bit more?

**Comment by sipa** [comment]
It could change the binary. Marking it `inline` but not `static` means the compiler still has to emit it. `-ffunction-sections` and `-Wl,--gc-sections` will let the linker remove it, though.

I think it should be both `inline` and `static`.

**Comment by shaavan** [comment]
> I think it should be both `inline` and `static`.

As far as I understand the usage of **static** and **inline**, I think it's best to go with this solution.

**Comment by fanquake** [comment]
> I think it should be both inline and static.

Updated to be `static inline`.

**Comment by MarcoFalke** [comment]
See also the feedback here: https://github.com/bitcoin/bitcoin/pull/23760#issuecomment-992631996

**Comment by fanquake** [comment]
> See also the feedback here: #23760 (comment)

Going to leave that for now. Happy for someone else to follow up.

**Review by shaavan — APPROVED** [review]
ACK df2307cdc3d08233d17beb9a50c144baaef1f44e

Changes since my last review:
- `static` -> `static inline`

The rationale for the change is discussed [above](https://github.com/bitcoin/bitcoin/pull/23760#issuecomment-994825450), with which I agree.

> Going to leave that for now. Happy for someone else to follow up.

[#23760 (comment)](https://github.com/bitcoin/bitcoin/pull/23760#issuecomment-992631996) seems interesting. Let me try working upon it, and give an update as soon as possible.

**Comment by sipa** [comment]
> Going to leave that for now. Happy for someone else to follow up.

See #23994.

**Pull request merged**
