### PR TITLE
refactor: policy: Pass kernel::MemPoolOptions to IsStandard[Tx] rather than long list of individual options

### PR DESCRIPTION
**Pull request by luke-jr**

### CODE REVIEW

**Comment by luke-jr** [comment]
@kristapsk @jonatack @achow101

**Comment by fanquake** [comment]
https://github.com/bitcoin/bitcoin/pull/30232/checks?check_run_id=25845075037:
```bash
A new circular dependency in the form of "kernel/mempool_options -> policy/policy -> kernel/mempool_options" appears to have been introduced.
```

**Comment by luke-jr** [comment]
>A new circular dependency in the form of "kernel/mempool_options -> policy/policy -> kernel/mempool_options" appears to have been introduced.

How do you propose resolving this? It's not really a circular dependency, just equivocated as such due to the CI test stripping file extensions, but maybe there's a better approach that just fixing CI?

**Comment by glozow** [comment]
Mind providing some motivation for the refactor? PR description is empty

**Comment by luke-jr** [comment]
Besides making the code cleaner, I'm hoping to get to a point where it's practical to fix the remaining vsize bugs.

**Comment by luke-jr** [comment]
Seems more like kernel shouldn't have policy stuff at all, but that's out of scope for this PR. Added your commit

**Comment by achow101** [comment]
This PR does not seem to have attracted much attention from reviewers. As such, it does not seem important enough right now to keep it sitting idle in the list of open PRs. The motivation is vague/missing.

Closing due to lack of interest.

**Pull request closed without merging**
