### PR TITLE
qt: Make it possible to show details for multiple transactions

### PR DESCRIPTION
**Pull request by laanwj**
A small GUI annoyance for me has always been that it's impossible to have multiple transaction detail windows open, for example to compare transactions.

This patch makes the window non-modal so that it is possible to open transaction details at will.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Nice! Also though about this. Thanks.

utACK 1f3b3fd48bb6c5787893529862430bd77b2c7fb3

**Comment by laanwj** [comment]
Another thing to consider here now may be to add some information to the window title. After all if there are multiple open it may be useful to distinguish them in taskbars etc.

I'm not sure on what to add though; transaction id seems to be of limited usefulness.

**Comment by paveljanik** [comment]
Numbering the windows?

**Comment by laanwj** [comment]
Numbering doesn't seem more useful to me than just keeping them with the same window title. It needs to actually identify the transaction.

**Comment by jonasschnelli** [comment]
What about the shortened transaction id (middle truncated). Something like `4d8fad...8dd9f9` for `4d8fad408da55d4b54e3be97960db06d78489f5984e0a6e8ada082295e8dd9f9`?

**Comment by paveljanik** [comment]
Full tx ID. window manager/... will shorten it if needed (ie. Transaction details: tx_id).

**Comment by jonasschnelli** [comment]
To make this work on OSX (not sure about Windows) you need to make the dialog non-modal.
```diff
diff --git a/src/qt/transactionview.cpp b/src/qt/transactionview.cpp
index eb6111e..bfdd7a4 100644
--- a/src/qt/transactionview.cpp
+++ b/src/qt/transactionview.cpp
@@ -480,6 +480,7 @@ void TransactionView::showDetails()
     {
         TransactionDescDialog *dlg = new TransactionDescDialog(selection.at(0));
         dlg->setAttribute(Qt::WA_DeleteOnClose);
+        dlg->setModal(false);
         dlg->show();
     }
 }
```

**Comment by jonasschnelli** [comment]
I tested with the full transaction-ID as window title. LGTM.
bildschirmfoto 2016-04-25 um 21 27 50


```diff
diff --git a/src/qt/transactiondescdialog.cpp b/src/qt/transactiondescdialog.cpp
index f7b6995..0e1d0e1 100644
--- a/src/qt/transactiondescdialog.cpp
+++ b/src/qt/transactiondescdialog.cpp
@@ -15,6 +15,7 @@ TransactionDescDialog::TransactionDescDialog(const QModelIndex &idx, QWidget *pa
 {
     ui->setupUi(this);
     QString desc = idx.data(TransactionTableModel::LongDescriptionRole).toString();
+    setWindowTitle(idx.data(TransactionTableModel::TxHashRole).toString());
     ui->detailText->setHtml(desc);
 }
 
diff --git a/src/qt/transactionview.cpp b/src/qt/transactionview.cpp
index eb6111e..bfdd7a4 100644
--- a/src/qt/transactionview.cpp
+++ b/src/qt/transactionview.cpp
@@ -480,6 +480,7 @@ void TransactionView::showDetails()
     {
         TransactionDescDialog *dlg = new TransactionDescDialog(selection.at(0));
         dlg->setAttribute(Qt::WA_DeleteOnClose);
+        dlg->setModal(false);
         dlg->show();
     }
 }
```

**Comment by laanwj** [comment]
@jonasschnelli: Interesting, do you know why is this necessary specifically here, how about the other places where we use `setAttribute(Qt::WA_DeleteOnClose)`?
- src/qt/receivecoinsdialog.cpp: on_receiveButton_clicked, on_recentRequestsView_doubleClicked
- src/qt/walletview.cpp: WalletView::gotoSignMessageTab, WalletView::gotoVerifyMessageTab

**Comment by laanwj** [comment]
From the QDialog documentation:
http://doc.qt.io/qt-5/qdialog.html#modal-prop  "By default, this property is false"

It's only exec() which sets it to true, which we don't use anymore. I don't think we need to set it.

**Comment by paveljanik** [comment]
Works OK here, even without `setModal(false)`.

**Comment by jonasschnelli** [comment]
Right. `setModal()` is not required. Was a local issue here.

**Comment by jonasschnelli** [comment]
Using "Details for" instead of "Transaction Details" would not truncate the window title (at least on OSX).

bildschirmfoto 2016-04-26 um 08 13 21


Tested ACK 17a6a217867603f349de676739f072c789c3918f.

**Comment by laanwj** [comment]
Yes, Abbreviating to "Details for %s" makes sense, will do that, it was just that having the whole title hex was a bit too cypherpunk even for me :)

**Comment by laanwj** [comment]
Added a new commit that puts the tx id in the window title.

**Pull request merged**
