### PR TITLE
doc: add documentation for shared library libbitcoinconsensus

### PR DESCRIPTION
**Pull request by braydonf**
Related Issue: #5311

### CODE REVIEW

**Comment by laanwj** [comment]
Looks good to me, thanks!

**Comment by jonasschnelli** [comment]
Nice. Thanks.
ACK.
I also like name `shared-libraries.md` which implies that more things should be available as library.

**Comment by theuni** [comment]
Looks great, thanks. One nit though: Please specify that bitcoinconsensus_ERR_OK only means that the inputs were sane and that verification was attempted, it does not mean that verification succeeded.

**Comment by fanquake** [comment]
ACK

**Comment by lontivero** [comment]
Could you add another *Example Implementations* for NBitcoin? It is a library for .NET that implements the consensus library too.

https://github.com/lontivero/NBitcoin/blob/master/NBitcoin/Script.cs#L814

**Comment by paveljanik** [comment]
ACK

**Pull request merged**
