### PR TITLE
Remove unused function arguments

### PR DESCRIPTION
**Pull request by practicalswift**
Remove unused function arguments.

### CODE REVIEW

**Comment by Empact** [comment]
utACK 796c9e3

**Comment by ken2812221** [comment]
utACK 796c9e371c30bb5cada70decaa027edbb4ad078f

**Comment by promag** [comment]
utACK 796c9e3.

@practicalswift have you checked if these arguments were used in the past?

**Comment by practicalswift** [comment]
@promag Yes absolutely, these were the results:

* `ThreadHTTP`: argument never used.
* `DefaultOptions`: argument never used.
* `ProcessGetBlockData`: last use of `interruptMsgProc` removed in 66aa1d58a158991a8014a91335b5bc9c00062f56 (ping @thebluematt :-))
* `WitnessSigOps`: argument never used.

**Review by conscott — COMMENTED** [review]
Tested ACK 796c9e371c30bb5cada70decaa027edbb4ad078f

**Comment by fanquake** [comment]
Concept ACK

@practicalswift What are you doing to find the unused arguments? I'm curious because (from a quick glance) there are more functions in those same files that also have unused arguments. Any reason not to include them here?

**Comment by practicalswift** [comment]
@fanquake What additional examples of unused arguments did you find? Let me know and I’ll investigate why the commercial static analyzer I used for this specific analysis missed them.

**Comment by fanquake** [comment]
@practicalswift See #13615 for one example.

**Comment by MarcoFalke** [comment]
Needs rebase?

**Comment by practicalswift** [comment]
Rebased! :-)

**Comment by fanquake** [comment]
utACK bd9d069

**Pull request merged**
