### PR TITLE
[Qt] prevent amount overflow problem with payment requests

### LINKED ISSUE #5624: Possible MINOR vulnerability in BIP70 implementation
**(as reported by Sergio Damien Lerner)**

Bitcoin amounts are stored as uint64 in the protobuf messages. Amounts over 0x7FFFFFFFFFFFFFFF will be considered negative when this line is executed:

    QList<std::pair<CScript, CAmount> > sendingTos = request.getPayTo();   

(in  PaymentServer::processPaymentRequest() in qt\paymentserver.cpp)

This does not pose a problem, since negative values should be discardedby the dust check : if (txOut.IsDust(::minRelayTxFee))

Nevertheless recipient.amount will still accumulate all positive values and may overflow, since the payment protocol allows the merchant to specify many output addresses and each one has a separate amount. So it is still possible to create a negative total amount by overflowing the
int64 range with several positive amounts. For example, (uint64) -1 + (uint64) -1 + 3 == 1. The user will be presented with a dialog asking to pay a total of 1 BTC, but internally the operation will fail, because the independent constituent payment amounts will not be able to be fulfilled.

This has the nasty effect that the user may think he may have been robbed, because even if the user has 100 BTC, the software will tell the user "The amount exceeds your balance.".

Correction:
```
bool PaymentServer::processPaymentRequest(PaymentRequestPlus& request,
SendCoinsRecipient& recipient) {
    ....
   CTxOut txOut(sendingTo.second, sendingTo.first);
    // BEGIN ADD
     if (!MoneyRange(sendingTo.second)) {
        emit message(tr("Payment request rejected"),
                tr("Invalid money range."),
                CClientUIInterface::MSG_ERROR);
            return false;
    }
   // END ADD
  ....
    recipient.amount += sendingTo.second;
  ...
    // BEGIN ADD
     if (!MoneyRange(recipient.amount)) {
        emit message(tr("Payment request rejected"),
                tr("Invalid  accumulated money range."),
                CClientUIInterface::MSG_ERROR);
            return false;
    }
   // END ADD
```

The payment request unit test should be extended to test negative and very large amounts in requests....

### PR DESCRIPTION
**Pull request by Diapolo**
Bitcoin amounts are stored as uint64 in the protobuf messages (see
paymentrequest.proto), but CAmount is defined as int64_t. Because
of that we need to verify that single and accumulated amounts are
in a valid range and no variable overflow has happened.
- fixes #5624 (#5622)

Thanks @SergioDemianLerner for reporting that issue and also supplying us
with a possible solution.
- add static verifyAmount() function to PaymentServer and move the logging
  on error into the function
- also add a unit test to paymentservertests.cpp

Please merge after #5665!

### CODE REVIEW

**Comment by Diapolo** [comment]
This is missing additional test-cases currently!

**Comment by jonasschnelli** [comment]
I tried to test this but my payment request with a overflow amount was blocked earlier by `if(!BitcoinUnits::parse(BitcoinUnits::BTC, i->second, &rv.amount))` in `guiutil.cpp`.

Any ideas how to test this?

Misses unit test.

**Comment by Diapolo** [comment]
You are aware, that I'm currently in the way of adding a better test-coverage, as also written above :)?
I'm not at the point where I thought about how to test this special case here...

**Comment by jonasschnelli** [comment]
Yes. I saw that you started writing more tests.
I just added it into a comment so that we not forget about it.

**Comment by Diapolo** [comment]
Yeah that's good, also if you find an idea on how to test this case fell free to comment again :).

**Comment by Diapolo** [comment]
I guess I can create a payment request which contains an amount, which (when added together) will trigger the new code in here, because if overflows. But for this I need my other related pulls getting merged, as there are currently too many open ones related to payment requests ^^.

**Comment by jonasschnelli** [comment]
@Diapolo yes. Understand the step-by-step thing. I tried with a manipulates php script (from gavin). But overflown amounts was already detected in the bitcoin url parsing.

**Comment by Diapolo** [comment]
@jonasschnelli Mind taking a look :)?

**Comment by jonasschnelli** [comment]
tested, reviewed, lldb stepped, ACK.

bildschirmfoto 2015-01-30 um 09 35 50

**Comment by laanwj** [comment]
ACK on the checking code.

I'd say we can simplify the reported messages to the user. A user that gets a "invalid money range" message has no clue what to do (and neither do translatorws). Let's show a general "invalid payment request" message. More details (for developers) will be in the debug log.

**Comment by Diapolo** [comment]
@laanwj Message changed to what you suggested.

**Pull request merged**
