### PR TITLE
test: various USDT functional test cleanups (27831 follow-ups)

### PR DESCRIPTION
**Pull request by stickies-v**
Various cleanups to the USDT functional tests, largely (but not exclusively) follow-ups to https://github.com/bitcoin/bitcoin/pull/27831#pullrequestreview-1491438045. Except for slightly different logging behaviour in "test: store utxocache events" and "test: log sanity check assertion failures", this is a refactor PR, removing unnecessary code and (imo) making it more readable and maintainable.

The rationale for each change is in the corresponding commit message.

Note: except for "test: store utxocache events" (which relies on its parent, and I separated into two commits because we may want the parent but not the child), all commits are stand-alone and I'm okay with dropping one/multiple commits if they turn out to be controversial or undesired.

### CODE REVIEW

**Comment by 0xB10C** [comment]
Thanks for picking this up! Concept ACK. I'll have a closer look.

**Comment by fanquake** [comment]
cc @virtu

**Comment by virtu** [comment]
Concept ACK. Will take a closer look and test next week.

**Comment by russeree** [comment]
Tested, still need to review code further.

image

**Comment by 0xB10C** [comment]
ACK 9f55773a370a0d039e727445ccee6b84e05f562a. Reviewed the code and ran the USDT interface tests. I stepped through the commits and think all changes are reasonable.

**Pull request merged**
