### PR TITLE
travis: Run unit tests --with-sanitizers=undefined

### LINKED ISSUE #12691: Enable -fsanitize flags in Travis
This idea is from discussion in #12686 . GCC 4.8 supports two -fsanitize flags, `-fsanitize=address` and `-fsanitize=thread` (and newer versions support even more of these flags). It would be a good idea to enable these options in Travis. @sipa points out that the build still isn't completely clean when using these flags, so to add this we'd either have to fix all of the existing errors or some up with a whilelisting mechanism to grandfather the old violations.

### PR DESCRIPTION
**Pull request by maflcko**
See issue #12691

### CODE REVIEW

**Comment by practicalswift** [comment]
This is excellent!

Strongest possible concept ACK

**Comment by ken2812221** [comment]
Concept ACK

**Comment by scravy** [comment]
Concept ACK

**Comment by scravy** [comment]
From the build log:

```
checking whether we are using Intel C compiler... no
checking whether we are using Sun Studio C compiler... no
checking whether we are using clang C compiler... no
checking whether we are using gcc >= 4 C compiler... yes
checking whether the C++ compiler works... yes
checking whether we are using Intel C++ compiler... no
checking whether we are using Sun Studio C++ compiler... no
checking whether we are using clang C++ compiler... no
checking whether we are using gcc >= 4 C++ compiler... yes
```

In https://travis-ci.org/bitcoin/bitcoin/jobs/420091638:

> Pull Request #14036 travis: Compile with sanitizers and clang in one of the linux jobs

doesn't seem to be using clang at all.

**Comment by MarcoFalke** [comment]
Yes, it is not possible to set the compiler when building from depends. I will add this back, when it is possible.

**Comment by laanwj** [comment]
utACK fad8afa3883675880dfa7fa6664fe658f10b11b5

**Pull request merged**
