### PR TITLE
Docs: Add extra step to clean $PATH var to strip out windows %PATH% paths.

### PR DESCRIPTION
**Pull request by donaloconnor**
I experienced the same ( error mentioned in #10269) . The suggested extra step in this PR removes the problematic Windows paths from the $PATH var.

### CODE REVIEW

**Comment by donaloconnor** [comment]
I am not sure if version Ubuntu Trusty 14.04 pulls in the Windows %PATH% variable? I am using the latest  Ubuntu Xenial 16.04 which has more issues cross compiling as mentioned in #10269 . If 14.04 does not pull in %PATH% thus not causing the issue this doc addition tries to fix then please reject this PR.

Thanks.

**Comment by laanwj** [comment]
Overlaps with  #10889

**Comment by laanwj** [comment]
> I am not sure if version Ubuntu Trusty 14.04 pulls in the Windows %PATH% variable?

Not sure either, it doesn't hurt to add the step in any case, it will likely still be needed for 18.04.

**Comment by fanquake** [comment]
Started testing this.
Built master at https://github.com/bitcoin/bitcoin/commit/c22a53cd6351b3f0e96de971b001ad712b83fc47 on a Windows 10 VM (Version 1607, OS Build 14393.1593) using WSL with Ubuntu 14.04.
windows

Going to upgrade to Ubuntu 16.04 and test.

**Comment by fanquake** [comment]
Upgraded WSL to 16.04.3, and tried building https://github.com/bitcoin/bitcoin/commit/c22a53cd6351b3f0e96de971b001ad712b83fc47 using these instructions. The result is as expected.
ubuntu 16 04 3


Upgraded WSL to 17.04 and tried building https://github.com/bitcoin/bitcoin/commit/3255d6347b1f9eccbec3d6d93d4a424087a3b35b using these instructions + @laanwj's info from #8732. That works successfully. 
ubuntu 17 04


I think it'd be worthwhile adding the posix alternative info to the readme, or at least mentioning that 17.04 will work with a simple workaround.

**Comment by neobitz** [comment]
thanks @fanquake but last question, Windows store doesn't have the latest Ubuntu Zesty yet. Bash can't find the new Ubuntu release with $ sudo do-release-upgrade command, so how to uprade xenial to zesty?

**Comment by fanquake** [comment]
@donaloconnor I'd like to cherry-pick this commit, but I can't seem to as the author info is missing. 
```
bitcoin xxx$ git cherry-pick 6e6ee9e83c35189fc98da5461633ef8aa5aa5879
fatal: empty ident name (for <user@xxx.localdomain>) not allowed
```

Could you either push up a commit with author information, or do you mind if I take the changes as they are, and credit you in my new commit?

**Comment by donaloconnor** [comment]
@fanquake  - I think it should be okay now? I'm still getting my head around git so apologies if this doesn't work. If it doesn't then I'm good with credit in your commit.

Cheers.
Donal

**Comment by fanquake** [comment]
@donaloconnor Thanks. Closing this PR in favour of #11437.

**Pull request closed without merging**
