### PR TITLE
Improve askfor logging (show time it will be requested by)

### PR DESCRIPTION
**Pull request by rebroad**
This improves logging of askfors. Firstly it now shows the time the request will be sent (rather than the incorrect time 2 minutes earlier). Also, the number of the time is now omitted since this now isn't useful since time went from seconds to microseconds.

### CODE REVIEW

**Comment by rebroad** [comment]
@laanwj Since #4831 didn't get merged, can this perhaps be reopened?

**Comment by laanwj** [comment]
Reopen button is greyed out here.
(the AskForDebug branch has been deleted)

**Comment by MarcoFalke** [comment]
There is no discussion in this pull, so it's save to reopen a rebased version, I guess.

**Comment by rebroad** [comment]
I've restored the branch. Github isn't saying it needs rebasing but that might be because it needs re-opening before it will determine that...

**Pull request closed without merging**
