### PR TITLE
[tests] Add node methods to test framework

### PR DESCRIPTION
**Pull request by jnewbery**
First step towards #10082:

- moves `initialize_chain()` and `initialize_chain_clean()` in their entireties to be methods of BitcoinTestFramework. At the moment, these are only ever called by BitcoinTestFramework, so it makes sense to move them to be class methods.
- add wrapper methods for start / stop nodes functions to BitcoinTestFramework class
- [trivial] restructures ordering of members of BitcoinTestFramework for clarity.

### CODE REVIEW

**Comment by JeremyRubin** [comment]
looks reasonable. Have you been able to figure out why Travis is timing out?

**Comment by jnewbery** [comment]
> Have you been able to figure out why Travis is timing out?

Because I messed up the merge :( Should be fixed now.

**Review by jimmysong — COMMENTED** [review]
ACK 2558b9a25047768b955863baa858f13e1f631ef1

Makes groking test_framework simpler.

Edit: tested locally.

**Review by jimmysong — APPROVED** [review]

**Comment by jnewbery** [comment]
rebased

**Comment by sdaftuar** [comment]
ACK 6291f47

Perhaps the commit message in the last commit should be fixed, though? "Reorganize BitcoinTestFramework class"

**Comment by jnewbery** [comment]
Thanks @sdaftuar . Commit message fixed. https://github.com/bitcoin/bitcoin/pull/10171/commits/4550049903608a98176d8a3f8b13ec0e00281ac5 is exactly the same as https://github.com/bitcoin/bitcoin/commit/6291f47545bfd89e73f16e8c796dd0bb51161f5a but with a new commit message.

**Comment by sdaftuar** [comment]
re-ACK 4550049

**Pull request merged**
