### PR TITLE
0.10

### PR DESCRIPTION
**Pull request by SegfredB**

### CODE REVIEW

**Comment by dexX7** [comment]
It would actually be useful, if there were a conflict free version of this ...

**Comment by gmaxwell** [comment]
@dexX7 It is unclear what you are talking about.

**Comment by dexX7** [comment]
Sorry, my bad. What I was actually thinking: it's unfortunate that the different release branches don't merge cleanly into another, such as: master into 0.11, 0.11 into 0.10, etc.

This makes it more difficult to upgrade a codebase from 0.10 to 0.11 for example.

**Comment by sipa** [comment]
@dexX7: the person creating this pull request almost certainly just wanted
to do a git checkout.

**Pull request closed without merging**
