### PR TITLE
[22.x] build: explicitly disable libsecp256k1 openssl based tests

### PR DESCRIPTION
**Pull request by fanquake**
Backport of #23314

These tests are failing when run against OpenSSL 3, and have been
removed upstream, bitcoin-core/secp256k1#983, so
disabled them for now to avoid `make check` failures.

Note that this will also remove warning output from our build, due to
the use of deprecated OpenSSL API functions. See #23048.

### CODE REVIEW

**Comment by fanquake** [comment]
cc @real-or-random @jonasnick

**Comment by fanquake** [comment]
Updated to be a proper backport of #23314.

**Comment by MarcoFalke** [comment]
Can be moved to #23276?

**Comment by MarcoFalke** [comment]
ack

**Pull request merged**
