### PR TITLE
Remove CWalletTx::fFromMe member.

### PR DESCRIPTION
**Pull request by ryanofsky**
Prior to this commit, the fFromMe member was written to and serialized but not
actually used in any meaningful way.

The one place where the fFromMe was used in a nontrivial way was
CWallet::AddToWallet, but the only actual effect it had there was to trigger
additional CWalletDB::WriteTx calls that would change serialized fFromMe fields
in previously existing database rows from false to true (without changing other
fields).

### CODE REVIEW

**Comment by jonasschnelli** [comment]
I agree that this is dead code and should probably be removed.
The only reason I could think of why to keep this is to have a flag to later determine which transactions in the wallet where created by the own wallet over `CreateTransaction()`.
Although not sure how useful this would be.

**Comment by laanwj** [comment]
Yes, is there any value in keeping/generating this information? I guess we can do a more thorough job by just looking at the inputs/outputs of a transaction. This will also catch transactions generated and broadcasted through the raw transactions API.

**Comment by ryanofsky** [comment]
@jonasschnelli's comment helped me understand the purpose of the fFromMe field, and now I kind of think it's worth keeping, especially since getting rid of it doesn't simplify things much.

I changed my commit for now to just document the `fFromMe` field instead of getting rid of it. For reference, previous commit was https://github.com/ryanofsky/bitcoin/commit/6b9a284c640b87e4179f7a2469696d2d26c31319

**Comment by pstratem** [comment]
@ryanofsky This was made dead by changes to the trickle logic

originally the use was for this one line 

>                            if (wtx.fFromMe)
>                                fTrickleWait = true;

I dont see any reason not to remove it.

**Comment by ryanofsky** [comment]
Ok @pstratem, removed fFromMe again. I don't have any opinion on whether it should be kept or removed. I just think it should be documented as in commit https://github.com/bitcoin/bitcoin/pull/9351/commits/39c77b00e3d61dfea1f45be5d3b77e5adea7b91a if it is not removed.

Reasons I could imagine why someone might not want to remove it is that it provides a nice little clue about the origin of a transaction that could be useful for debugging, or to show as information in the UI. Also, removing the variable doesn't simplify the code very much. Another reason to keep it might be that having it could make it easier to remove the `fTimeReceivedIsTxTime` variable which I think is actually a stranger thing to serialize. It has similar meaning to `fFromMe`, but unlike fFromMe is not merged properly in `AddToWallet`.

**Comment by laanwj** [comment]
I tend to agree there's no reason to make a quick decision on this one. No need to remove this for 0.14.
Adding the brainstorming label.

**Comment by ryanofsky** [comment]
I think I will close this PR, but feel free to reopen if it you want to keep it around. I created a separate PR https://github.com/bitcoin/bitcoin/pull/9378 with just the documentation commit.

**Pull request closed without merging**
