### PR TITLE
Bugfix: RPC/Mining: GBT should return 1 MB sizelimit before segwit activates

### PR DESCRIPTION
**Pull request by luke-jr**
Not sure how I missed this when fixing the sigoplimit... Better late than never - maybe.

### CODE REVIEW

**Review by jonasschnelli — APPROVED** [review]
utACK 8b19cc83bb05c80c391cb1968c5ae5300f193267

**Comment by jtimon** [comment]
utACK 8b19cc8

**Comment by TheBlueMatt** [comment]
Can you add this to the existing test-cases? Looks like it should be easy.

**Comment by laanwj** [comment]
utACK https://github.com/bitcoin/bitcoin/commit/8b19cc83bb05c80c391cb1968c5ae5300f193267, agree that a testcase would be superb.

**Comment by sipa** [comment]
utACK

**Comment by luke-jr** [comment]
Rebased and added tests.

**Comment by MarcoFalke** [comment]
```py
	Testing detection of non-standard P2WSH witness
Assertion failed: not(b'bad-txns-vout-negative' == b'bad-witness-nonstandard')

  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-unknown-linux-gnu/qa/rpc-tests/test_framework/test_framework.py", line 145, in main
    self.run_test()
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-unknown-linux-gnu/qa/rpc-tests/p2p-segwit.py", line 2028, in run_test
    self.test_non_standard_witness()
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-unknown-linux-gnu/qa/rpc-tests/p2p-segwit.py", line 1905, in test_non_standard_witness
    self.std_node.test_transaction_acceptance(p2wsh_txs[0], True, False, b'bad-witness-nonstandard')
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-unknown-linux-gnu/qa/rpc-tests/p2p-segwit.py", line 160, in test_transaction_acceptance
    assert_equal(self.last_reject.reason, reason)
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-unknown-linux-gnu/qa/rpc-tests/test_framework/util.py", line 529, in assert_equal
    raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))

**Comment by luke-jr** [comment]
I don't see how that's possible...

**Comment by jtimon** [comment]
utACK 279f944

**Comment by sipa** [comment]
utACK for 0.14

**Comment by luke-jr** [comment]
( @MarcoFalke  Re-run of Travis didn't have the same issue, so I guess p2p-segwit was/is flakey, and that failure was unrelated to this PR.)

**Pull request merged**
