### PR TITLE
Allow whitelisting outgoing connections

### PR DESCRIPTION
**Pull request by luke-jr**
Rethinking/rewrite of #10594 in light of whitelist flags: new flags are added for "in" and "out" to specify the connection direction matched. Both can be specified to match either direction.

### CODE REVIEW

**Comment by laanwj** [comment]
Concept ACK.

As for implementation, I'm not sure about having `In` and `Out` as permissions.

This doesn't allow having different flags for a IP for incoming and outgoing. Not sure that's ever necessary, but this seems a bit muddles to me. Might also consider e.g. `whiteconnect` (for outgoing connections) could have a completely different flag list structure from the normal `whitelist` (for incoming connections).

**Comment by luke-jr** [comment]
As you noticed, the implementation already doesn't treat in/out as permissions.

Using `-whitelist` for both allows for easily specifying the same flags for both in,out. I can't think of any benefit to having separate options. (I'm not sure why we'd want to support different sets of flags...)

**Comment by luke-jr** [comment]
Rebased

**Comment by MarcoFalke** [comment]
Previously whitelisting outgoing connections wasn't possible, so no guards have been added to protect those from disconnection. Would be good to revisit those places and evaluate if guards are needed.

For example commit c60fd71a65e841efe187992f46c583a704cc37f5 by @sdaftuar checks for `pfrom->fWhitelisted`, but the commit immediately after it (5a6d00c6defc587e22c93e63029fdd538ce8858d) removes the check.

**Comment by luke-jr** [comment]
@MarcoFalke Even on inbound peers, `noban` isn't absolute. There are many places that can be made more noban-friendly, but due to the complexity of at least a few of them, I think they would be better as followup PRs.

**Comment by rebroad** [comment]
More reasons to merge than to not merge, based on my understanding of the use of whitelist (which is essentially peers you trust/own), so untested ACK.

**Comment by jonatack** [comment]
I've looking at the net permissions lately, will review.

**Comment by luke-jr** [comment]
Rebased

**Comment by MarcoFalke** [comment]
Concept ACK

**Comment by 1440000bytes** [comment]
Concept ACK

**Comment by vasild** [comment]
This would allow us to use [transient (aka one-time / random / disposable) I2P addresses](https://github.com/bitcoin/bitcoin/pull/25355) when making outgoing connections to all nodes, except to whitelisted ones for which we would use our persistent I2P address.

**Comment by achow101** [comment]
Closing this as it has not had any activity in a while. If you are interested in continuing work on this, please leave a comment so that it can be reopened.

**Comment by brunoerg** [comment]
@luke-jr Are you intending to work on this?

**Comment by 1440000bytes** [comment]
Seems a little weird because I tried to filter bitcoin core pull requests with `is:pr is:open sort:updated-asc` and first PR in the result has 1 Concept ACK from dev who longer contributes to this repo in reviews and second was only active for a few days/weeks. Those comments were posted in May 2022 and PR is in draft mode.

Whereas, this PR got last 2 Concept ACK or comments agreeing from active contributors in May 2022. And a Concept ACK from present maintainer. 

 > @luke-jr Are you intending to work on this?
 
 Anyway, PR author has not commented since Jul 7, 2021 so we cannot blame others for this PR to get more review and eventually merged. 
 
 ---
 
 Whitelist could be a taboo in bitcoin, however this is already possible manually. This PR makes it easier to manage your outgoing connections. I haven't reviewed each commit but I conceptually agree with the idea.

**Comment by Smithbull001** [comment]
Allow whitelisr

**Comment by luke-jr** [comment]
@brunoerg I have never stopped maintaining it.

**Comment by brunoerg** [comment]
@luke-jr Cool, just to know, because it's been closed and I am interesting on it.

**Comment by brunoerg** [comment]
Concept ACK

**Pull request closed without merging**
