### PR TITLE
Remove redundant `-datacarrier` option

### PR DESCRIPTION
**Pull request by vostrnad**
The `-datacarrier` option is redundant, as disabling the relay and mining of transactions creating OP_RETURN outputs can be accomplished by setting `-datacarriersize=0`. Its removal was supported by several people in the discussion of [#27261](https://github.com/bitcoin/bitcoin/pull/27261) (e.g. https://github.com/bitcoin/bitcoin/pull/27261#issuecomment-1472404739, https://github.com/bitcoin/bitcoin/pull/27261#issuecomment-1581058082) and implemented in [#28130](https://github.com/bitcoin/bitcoin/pull/28130), but that PR was rejected due to making other, more controversial changes.

Being a breaking change, this will of course need a release note. I'd recommend anyone concerned that they might accidentally start relaying and mining OP_RETURN transactions to proactively set `-datacarriersize=0` now.

### CODE REVIEW

**Comment by vostrnad** [comment]
The main benefit really is not having two options with similar names that can do the same thing. As you yourself said in the linked comment:

> Having two ways to achieve the same is just confusing and can lead to issues.

Seems to me a one-time breaking change (with very little impact) is preferred to keeping the confusing set of options forever.

**Comment by vostrnad** [comment]
Another difference from `-chain` is that it is possible to set both `-datacarrier=0` and a positive `-datacarriersize` without so much as a warning (`-chain` immediately crashes when in conflict with another option).

Here are also a few examples of users confused about the two options:

https://twitter.com/FieldNas/status/1782498776671768807
https://twitter.com/betoche1984/status/1782452190063337681

**Comment by laanwj** [comment]
This particular option was introduced 10 years ago (in e44fea55ea73f46bc9460597c7001e77acb58db7). FWIW i think we would need a stronger reason to remove it than a bit of redundancy.

**Comment by vostrnad** [comment]
What is there to work on? CI passes and there are no merge conflicts. I know you suggested alternative approaches, but those can be implemented in different PRs if this one gets closed.

**Comment by luke-jr** [comment]
It seems there is a benefit to redundant options, in that we had to do the whole `prune-prev` thing to preserve the disabled size in the GUI (which is actually kindof weird, since disabling pruning is a pretty big change).

But the confusion isn't nothing either.

Inclined to leave it alone since it's been this way for years. = Weak Concept NACK.

**Pull request closed without merging**
