### PR TITLE
ci: Use clang-8 for fuzzing to run on aarch64 ci systems

### PR DESCRIPTION
**Pull request by maflcko**
Ubuntu bionic clang is clang version 6, which does not come with libfuzzer. So the ci system breaks down when run on aarch64.

Fix that by using clang-8

For reference, the previous error on my ci system was:

```
/usr/bin/ld: cannot find /usr/lib/llvm-6.0/lib/clang/6.0.0/lib/linux/libclang_rt.fuzzer-aarch64.a: No such file or directory

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Excerpt from my ci system:

```
Options used to compile and link:
  with wallet   = no
  with gui / qt = no
  with zmq      = no
  with test     = yes
    with prop   = no
    with fuzz   = yes
  with bench    = no
  with upnp     = no
  use asm       = yes
  sanitizers    = fuzzer,address,undefined
  debug enabled = no
  gprof enabled = no
  werror        = no

  target os     = linux
  build os      = 

  CC            = /usr/bin/ccache clang-8
  CFLAGS        = -g -O2
  CPPFLAGS      =   -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -Qunused-arguments  -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS
  CXX           = /usr/bin/ccache clang++-8 -std=c++11
  CXXFLAGS      =   -Wstack-protector -fstack-protector-all  -Wall -Wextra -Wformat -Wvla -Wswitch -Wformat-security -Wthread-safety-analysis -Wrange-loop-analysis -Wredundant-decls  -Wno-unused-parameter -Wno-self-assign -Wno-unused-local-typedef -Wno-deprecated-register -Wno-implicit-fallthrough   -g -O2
  LDFLAGS       = -pthread  -Wl,-z,relro -Wl,-z,now -pie  
  ARFLAGS       = cr

travis_fold:end:configure

travis_fold:start:build
Making install in src
make[1]: Entering directory '/root/workspace/bitcoin-core/build/bitcoin-aarch64-unknown-linux-gnu/src'
make[2]: Entering directory '/root/workspace/bitcoin-core/build/bitcoin-aarch64-unknown-linux-gnu/src'
  CXX      test/fuzz/test_fuzz_address_deserialize-fuzz.o
  CXX      test/util/test_fuzz_address_deserialize-setup_common.o

**Comment by practicalswift** [comment]
ACK fa6e01b2f3cd8523a95bd1906ac5e62ee3cbf319 -- diff looks correct

**Review by fanquake — APPROVED** [review]
ACK fa6e01b2f3cd8523a95bd1906ac5e62ee3cbf319

**Comment by MarcoFalke** [comment]
Bumped the timeout in a new commit, because it turns out that just running over the existing seeds takes 5 minutes for me:

```
root@odroid:~/workspace/bitcoin-core/build/bitcoin-aarch64-unknown-linux-gnu# time ./test/fuzz/test_runner.py ../../qa-assets/fuzz_seed_corpus/
Fuzz targets found: ['address_deserialize', 'addrman_deserialize', 'banentry_deserialize', 'bech32', 'block_deserialize', 'blockheader_deserialize', 'blocklocator_deserialize', 'blockmerkleroot', 'blocktransactions_deserialize', 'blocktransactionsrequest_deserialize', 'blockundo_deserialize', 'bloomfilter_deserialize', 'coins_deserialize', 'descriptor_parse', 'diskblockindex_deserialize', 'eval_script', 'inv_deserialize', 'messageheader_deserialize', 'netaddr_deserialize', 'parse_iso8601', 'script', 'script_flags', 'service_deserialize', 'spanparsing', 'transaction', 'txoutcompressor_deserialize', 'txundo_deserialize']
Fuzz targets selected: ['blocktransactions_deserialize', 'bloomfilter_deserialize', 'parse_iso8601', 'txoutcompressor_deserialize', 'blocklocator_deserialize', 'diskblockindex_deserialize', 'service_deserialize', 'banentry_deserialize', 'address_deserialize', 'inv_deserialize', 'script_flags', 'coins_deserialize', 'descriptor_parse', 'blockheader_deserialize', 'block_deserialize', 'addrman_deserialize', 'messageheader_deserialize', 'blocktransactionsrequest_deserialize', 'txundo_deserialize', 'blockmerkleroot', 'eval_script', 'bech32', 'blockundo_deserialize', 'script', 'netaddr_deserialize', 'spanparsing', 'transaction']

real	5m5.762s
user	4m9.200s
sys	0m8.390s

**Comment by laanwj** [comment]
ACK fa2ec9f4518c1da3ab3592537c6cd204693a6069

**Pull request merged**
