### PR TITLE
wallet: move crypter to wallet

### PR DESCRIPTION
**Pull request by theuni**
I'm not aware of any plans to use this outside of the wallet.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
ACK.

**Comment by fanquake** [comment]
ACK

**Comment by Diapolo** [comment]
You should take care of the header-comment because of the move to ``support``.

**Comment by sipa** [comment]
ACK

**Comment by jgarzik** [comment]
ut ACK

**Comment by theuni** [comment]
@Diapolo most of the other headers in wallet/ haven't been updated, and I'd rather not change it here and break the 100% code move. Let's just do that as a next step.

**Comment by laanwj** [comment]
Appears to have been an oversight, crypter clearly belongs with the wallet.

ACK

**Pull request merged**
