### PR TITLE
[REST] remove json input for getutxos, limit to query max. 15 outpoints

### PR DESCRIPTION
**Pull request by jonasschnelli**
Remove possibility to send json encoded parameters to `/rest/getutxos/` to avoid possible DoS scenarios (issue #6192).

The JSON output option is untouched.

### CODE REVIEW

**Comment by laanwj** [comment]
utACK, I like the new interface

**Comment by jgarzik** [comment]
ut ACK - though I don't understand why we care about operators DoS'ing themselves...   Nobody should be sending any data, json or binary, straight from remote to the REST interface without sanitizing.

**Comment by jonasschnelli** [comment]
I agree with @jgarzik. The nice side effect of this PR is that it harmonize the input scheme (avoid raw http post data and use `/rest/<command>/<parameter:1>/<parameter:n>.json` everywhere).
And JSON as input format was a bad decision anyways (as output format it's totally fine IMO).

**Comment by jonasschnelli** [comment]
Travis issue (as well as in #6197 and #6198) is because of the failing native comparison tool (java). Hope someone can fix this soon.

**Comment by laanwj** [comment]
> avoid raw http post data and use /rest/<command>/<parameter:1>/<parameter:n>.json everywhere

Exactly. Providing parameters in the URI is what makes this interface more elegant.

**Pull request merged**
