### PR TITLE
Make connect=0 disable automatic outbound connections.

### PR DESCRIPTION
**Pull request by gmaxwell**
Otherwise it just responds to this obvious bit of configuration by
 trying to connect to "0" in a loop.

### CODE REVIEW

**Comment by luke-jr** [comment]
Concept ACK. I've always used it in this way, might as well make it official.

**Comment by jonasschnelli** [comment]
utACK ec4d35cb501b79173c4fc55a8b4f6c3f97659fe6

**Comment by laanwj** [comment]
utACK ,needs documentation in HelpMessage though

**Comment by theuni** [comment]
Concept ACK. Don't we want this to disable dns seed queries too though? As-is, I believe this would actually force them.

**Comment by laanwj** [comment]
> Concept ACK. Don't we want this to disable dns seed queries too though? 

I think @gmaxwell checked that

**Comment by sipa** [comment]
Code review ACK. Agree with documentation update.

**Comment by MarcoFalke** [comment]
utACK ec4d35c

Not sure if we need to document this. "Normal people" might be fine with just `-maxconnections=0` and might not need to know about this?

**Comment by laanwj** [comment]
> Not sure if we need to document this. "Normal people" might be fine with just

I think we should aim to document everything, whether it exists for "normal people" or not. Developers need documentation too. Testers, too.

**Comment by laanwj** [comment]
Travis failure is unrelated (p2p-compactblocks is having transient issues again), re-spinning

**Pull request merged**
