### PR TITLE
[WIP] [tool] Add salvage and zaptxs commands to bitcoin-wallet

### PR DESCRIPTION
**Pull request by jnewbery**
Adds `salvage` and `zaptxs` commands to bitcoin-wallet

### CODE REVIEW

**Comment by jnewbery** [comment]
As suggested here: https://github.com/bitcoin/bitcoin/pull/13926#issuecomment-455183742, the initial bitcoin-wallet PR stripped down the wallet tool to minimum functionality. This PR adds the `salvage` and `zaptxs` commands back in.

I haven't made any changes from the original PR, so @Sjors comment here: https://github.com/bitcoin/bitcoin/pull/13926#issuecomment-455174640 still isn't addressed. I plan to do that in future, but wanted to have a PR open in case others wanted to provide early concept feedback.

**Comment by Sjors** [comment]
Concept ACK. I suggest marking them deprecated in `bitcoind` at the same time.

**Comment by jonasschnelli** [comment]
Concept ACK.
Is there a reason why this duplicates the functionality rather than directly move it?

**Comment by ryanofsky** [comment]
Curious why this is marked WIP. Would be good to clarify if you are still working on changes or are presently seeking review.

> Is there a reason why this duplicates the functionality rather than directly move it?

I don't think it should hold up this PR, but I do have the same question, and personally would love to see a PR getting rid of current the duplication between [`CreateWallet`](https://github.com/bitcoin/bitcoin/blob/d83d6079432cf592ff6c740d1d3fbdb5e596facb/src/wallet/wallettool.cpp#L24) and [`createwallet`](https://github.com/bitcoin/bitcoin/blob/d83d6079432cf592ff6c740d1d3fbdb5e596facb/src/wallet/rpcwallet.cpp#L2579), [`LoadWallet`](https://github.com/bitcoin/bitcoin/blob/d83d6079432cf592ff6c740d1d3fbdb5e596facb/src/wallet/wallettool.cpp#L51) and [`loadwallet`](https://github.com/bitcoin/bitcoin/blob/d83d6079432cf592ff6c740d1d3fbdb5e596facb/src/wallet/rpcwallet.cpp#L2523).

I think it would be good to have a plan or at least a basic idea going forward of how to avoid duplicating functionality between the wallet and wallet tool. Making the wallet tool into a limited frontend for a subset RPC methods that work offline (suggested in https://github.com/bitcoin/bitcoin/pull/13926#issuecomment-455187379) would be a good approach that would enable code sharing, and also decrease the likelihood of a garbagey command line parsing code getting added to wallet tool in the future. But other approaches are certainly possible.

**Comment by MarcoFalke** [comment]
This is critical functionality and I think unless there is at least a basic test, this is not ready for review.

**Comment by jnewbery** [comment]
> Curious why this is marked WIP.

Sorry, a better tag would be work-not-in-progress. I'm not actively working on this and plan to pick it up later. I wanted to open the PR so people could give concept feedback. I'll also mark as 'Up For Grabs' if someone else wants to grab it with higher priority.

This isn't ready for merge for a couple of reasons:
- needs updating to address feedback here https://github.com/bitcoin/bitcoin/pull/13926#issuecomment-455174640
- needs tests

I definitely agree with your concerns about code duplication and like your idea https://github.com/bitcoin/bitcoin/pull/13926#issuecomment-455187379.

**Pull request closed without merging**
