### PR TITLE
[28.x] backports and finalize

### PR DESCRIPTION
**Pull request by achow101**
* #30952
* #30962 
* Finalize 28.0 (or rc3 if additional backports are needed)

### CODE REVIEW

**Review by hebasto — APPROVED** [review]
ACK 1f6c3caf30849a6e53957aa15c6ac27b97004dc5.

A new backport only affects the test code, so I agree to skip the rc3 phase.

**Comment by achow101** [comment]
Added #30962

I think it's trivial enough to not require rc3 as well.

**Review by stickies-v — COMMENTED** [review]
code LGTM 98745e03ffc9f69f901b827e19e4d8d645a27112

Verified all backport commits are clean and make sense, and that I'm getting the same manpages. I think `doc/release-notes.md` still needs to be updated though?

**Comment by achow101** [comment]
> I think `doc/release-notes.md` still needs to be updated though?

I think that's usually done when after the release is published on the website.

**Comment by stickies-v** [comment]
It seems to have been the process for 26.0 and 27.0 at least:

- https://github.com/bitcoin/bitcoin/pull/29780/files#diff-e04cb1e9f29f76897c6b84334238f621ff45ba13cf180ad1d0d442d50ebe51f7
- https://github.com/bitcoin/bitcoin/pull/28959/files#diff-e04cb1e9f29f76897c6b84334238f621ff45ba13cf180ad1d0d442d50ebe51f7

**Comment by achow101** [comment]
Hmm ok, will add those soon. Still some changes to be made on the release notes.

**Comment by instagibbs** [comment]
LGTM https://github.com/bitcoin/bitcoin/pull/30959/commits/5de225f5c145368f70cb5f870933bcf9df6b92c8

**Comment by glozow** [comment]
post merge ACK

**Comment by stickies-v** [comment]
Thanks! I've added https://github.com/bitcoin-core/bitcoin-devwiki/wiki/28.0-Release-Notes-Draft/6677e1b3aa3ecadd142786f1393d2a7affe9e03e which adds missing PR numbers.

Release notes otherwise LGTM, I verified the author list and read through the descriptions. I think these 3 might benefit from being added to the list too, I'll give them a go later:
- bitcoin/bitcoin#29648
- bitcoin/bitcoin#28981
- bitcoin/bitcoin#28280

**Review by Imebeez — COMMENTED** [review]
N-2

**Pull request merged**
