### PR TITLE
DEPENDENT: Chainparams: Introduce N testnet chains to test different block sizes

### PR DESCRIPTION
**Pull request by jtimon**
This creates `std::numeric_limits<uint64_t>::max()` new testchains, each one with a different maximum block size and genesis block.
It would be generally good to have more people collecting data and
conduction simulations related to different consensus maximum block sizes.
This PR attempts to simplify that work.
Even if it may take long until it is merged (because it requires many
little steps to be taken first), this branch (or a fork of it) can be used right now for
testing purposes.

One can use it, for example, like this: `./src/qt/bitcoin-qt -chain=sizetest -debug -printtoconsole -gen=1 -genproclimit=20 -blocksize=2000000`

I will rebase and update the list of dependencies accordingly as
things get merged.

Dependencies:
- [X] CTestNetParams and CRegTestParams extend directly from CChainParams #6381
- [X] Chainparams: Translations: DRY: options and error strings #6235
- [X] Qt: BIP70: Chainparams: DRY: Make qt/guiutil.cpp fit BIP70 chain name strings #6908 (trivial review)
- [ ] Chainparams: Use a regular factory for creating chainparams #6907 (medium review)
- [ ] Don't check the genesis block #6597 (medium review)
- [ ] Blocksize: Turn MAX_BLOCK_SIZE and MAX_BLOCK_SIGOPS into functions #6625
- [ ] Generic selection with -chain=<chainString> in addition of -testnet and -regtest [closed] #5229
- [ ] Qt: Simplify network/chain styles and add a default purple one (trivial review)
- [ ] Checkpoints: The hash of the genesis block is the genesis checkpoint and chain id [closed] #6230
- [ ] Chainparams: Adapt qt/paymentserver to support more than 2 chains
- [X] Chainparams: Introduce AssignBase58PrefixStyle() static function NACK
- [X] Blocksize: Introduce sizetest mode with infinite chains NACK

Similar branches on top of older versions:

https://github.com/jtimon/bitcoin/tree/chainparams-sizetest-0.11

### CODE REVIEW

**Comment by jtimon** [comment]
Rebased after #6381. Also rebased back in time to 0.11: https://github.com/jtimon/bitcoin/tree/chainparams-sizetest-0.11

**Comment by JornC** [comment]
Spun up a node and block explorer on top of this PR:

http://srv1.yogh.io/#json:getinfo
http://srv1.yogh.io/#json:getblockchaininfo

Availability subject to change, will jump back to the main chain when no longer needed - if needed at all.

**Comment by jtimon** [comment]
Rebased and fixed (see https://github.com/bitcoin/bitcoin/pull/6077#issuecomment-133584041 ).

**Comment by jtimon** [comment]
This wasn't passing travis because of a small bug in https://github.com/jtimon/bitcoin/commit/989e37459b7c2f6505f7c98d7fe40e7eec5aba99 (#6625). I will wait for travis to approve this to force push #6625.

**Comment by TheBlueMatt** [comment]
NACK. I think the code should exist for people to use for testing, but I dont think Bitcoin Core is the place to support a ton of test/benchmark chains. This is different from the regtest/testnet chains, which exist to create a bitcoin-in-a-box for testing, but which try to mimic Bitcoin where convinient for testing, not to test changes to Bitcoin itself.

**Comment by priestc** [comment]
I think it might be a better idea to just make one testnet with unlimited blocksize, rather than multiple networks with all different size limits. What is the 20MB test chain going to teach us that the 50MB chain will? When testing scalability, it makes the most sense to have as many people working together than to have multiple people working on multiple chains. Take a look at the bip that I recently wrote that deals with the same subject: https://github.com/bitcoin/bips/pull/222

**Comment by jtimon** [comment]
> I think it might be a better idea to just make one testnet with unlimited blocksize.

You can effectively do that as well (just set -blocksize to ```std::numeric_limits<uint64_t>::max()```). But this also allows you to simulate networks with smaller sizes and to test schism forks scenarios.

@TheBlueMatt what about the individual steps (to make things like this more maintainable on top of master)? What about #6235 and #6597, for example?

**Comment by jtimon** [comment]
Rebased

**Comment by laanwj** [comment]
> NACK. I think the code should exist for people to use for testing, but I dont think Bitcoin Core is the place to support a ton of test/benchmark chain

I tend to agree with @bluematt here. Let's not overcomplicate bitcoind with all kinds of specific purpose test code.

**Comment by jtimon** [comment]
Precisely this PR makes creating a new testchain easier by removing specific purpose code for different chains that is not always properly encapsulated. Then it prepares code for a future change in block size and then it adds a new testchain to test different block sizes. The last part only makes sense if it is a single extremely simple commit like  https://github.com/jtimon/bitcoin/commit/b7bce5c5571200361e3b74406d0f9bc986960491 . But even if that change is never accepted, I will maintain it here because that's the way I test "is it easy to create a new testchain?" every time I rebase. I have marked that step as nacked and solved in the first post. I have also properly marked the PRs that are currently closed and opened #6907 and #6908 which are now much more clear after #6235.
People interested in changes to make it easier to create new testchains can follow this PR and I can rebase just one long branch plus only a few little opened PRs at a time.
When there's only nacked commits remaining we can revisit the nacks and merge or close. This was never intended to be merged all at once, that's why it has the bullet points (which I'm finding very useful).

**Comment by jtimon** [comment]
Rebased after #6908 has being merged.

**Comment by jtimon** [comment]
Closing. It will be eventually replaced with a similar one that doesn't use block size as an example.

**Pull request closed without merging**
