### PR TITLE
SanitizeString: Allow hypen char

### PR DESCRIPTION
**Pull request by maflcko**
Maybe someone wants to put `their-domain.org` in the UA?

Ref: #4983.

### CODE REVIEW

**Comment by laanwj** [comment]
Maybe we could reverse the approach, and allow everything allowed by the [BIP14](https://github.com/bitcoin/bips/blob/master/bip-0014.mediawiki). Otherwise we can keep creating 'also allow XX' pulls (yes, I'm guilty of this one) .

I think the conceptual issue is that `SanitizeString` is used for two purposes: 
- to avoid formatting strings that are dangerous to pass to the shell, terminal or debug log, and
- to filter characters for user agent

Splitting of these two use-cases with a parameter was a great idea. Now we can make SanitizeString(SAFE_CHARS_UA_COMMENT) pass through all characters allowed per BIP14.

**Unfortunately**  that BIP isn't clear on that. It says that `/` `:` `(` and `)` are reserved, but it doesn't make any statement about e.g. which character set is used, or even about control characters...

**Comment by MarcoFalke** [comment]
Assuming ASCII and forgetting about all non printable ASCII chars, leaves us with 33 chars (alphanum is fine) to make a decision about:

` .,;_/:?@()` is already in, so what is left:

     !"#$%&'*+-<=>[]\^`{|}~

IIrc, UAs get dumped to debug.log as well, so is it save to allow any char?

**Comment by jgarzik** [comment]
ut ACK

**Comment by laanwj** [comment]
> IIrc, UAs get dumped to debug.log as well, so is it save to allow any char?

Yes, but only processed through SanitizeString(SAFE_CHARS_DEFAULT) - in principle, just the fact that we don't log some characters doesn't mean that they shouldn't be allowed in uacomments.

**Comment by laanwj** [comment]
Meh, I don't think it's worth it to take this to BIP level - although the BIP should have mentioned valid/invalid characters!
utACK

**Pull request merged**
