### PR TITLE
Renamed deprecated apt-get to apt in doc/build-unix.md

### PR DESCRIPTION
**Pull request by SsNiPeR1**
Renamed deprecated apt-get to apt in doc/build-unix.md

### CODE REVIEW

**Comment by jonatack** [comment]
Duplicate of #17256?

**Comment by SsNiPeR1** [comment]
> Duplicate of #17256?

maybe, but why not after three years? i hate apt-get

**Comment by MarcoFalke** [comment]
> i hate apt-get

This is not about your personal preference. Please include a clear motivation, explaining why it is deprecated with a source. Also, please explain how users that copy-paste the commands into scripts should deal with the warnings that this will cause.

**Comment by SsNiPeR1** [comment]
> > i hate apt-get
> 
> Please include a clear and objective motivation, explaining why it is deprecated with a source. Also, please explain how users that copy-paste the commands into scripts should deal with the warnings that this will cause.

idk but please merge, cus everybody uses apt. i've seen NOBODY who uses apt-get, but many use apt or aptitude.

**Comment by MarcoFalke** [comment]
> idk but please merge

This is not how open source works. Our project uses a review process and it is the responsibility of the pull request author to make it as easy as possible for reviewers to evaluate the change. Stating a goal, a motivation and supplementary information to underline why the change makes sense and is safe to do do help.

Going to close this for now, but this can be reopened when the above has been addressed.

**Comment by MarcoFalke** [comment]
## Getting started to contribute to Bitcoin Core

### Setting up your development environment

New developers are very welcome and needed. There are a lot of open issues of any difficulty waiting to be fixed. However, before you start contributing, familiarize yourself with the Bitcoin Core build system and tests. Refer to the documentation in the repository on how to build Bitcoin Core and how to run the unit and functional tests. Once that is done, you are all set.

If you need more help getting started, please refer to the following resources:

* https://medium.com/@amitiu/onboarding-to-bitcoin-core-7c1a83b20365
* https://jonatack.github.io/articles/how-to-review-pull-requests-in-bitcoin-core

### Pick something to work on

If you are looking for useful contributions to help out with, you can

* Search through the [good first issue](https://github.com/bitcoin/bitcoin/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)s or the ones that are [up for grabs](https://github.com/bitcoin/bitcoin/issues?utf8=%E2%9C%93&q=label%3A%22Up+for+grabs%22). Some of them might no longer be applicable. So if you are interested, but unsure, you might want to leave a comment on the issue first.
* Write tests to improve the coverage. Any kind of test is welcome and coverage information can be obtained from a relatively recent [coverage report](https://marcofalke.github.io/btc_cov). If you are unsure, don't hesitate to check back first.
* Help with review and testing. There are easy ones such as the [gui](https://github.com/bitcoin/bitcoin/pulls?q=is%3Apr+is%3Aopen+label%3AGUI) and [rpc](https://github.com/bitcoin/bitcoin/pulls?q=is%3Apr+is%3Aopen+label%3ARPC%2FREST%2FZMQ). However, review on any open pull request is welcome. Review will also help you understand the codebase better.
* Help on meta projects related to Bitcoin Core, such as a [high-level performance monitor](https://github.com/chaincodelabs/bitcoinperf).
* Join us on irc and let us know what you are interested in.

**Comment by SsNiPeR1** [comment]
:(

**Comment by hebasto** [comment]
`apt-get` is not deprecated.

`apt` is more user-friendly.

Besides `doc/build-unix.md`, `apt-get` is also suggested in:
- `depends/README.md`
- `doc/fuzzing.md`
- `doc/translation_process.md`
- `src/qt/README.md`
- `test/README.md`

**Pull request closed without merging**
