### PR TITLE
External signer multisig support

### PR DESCRIPTION
**Pull request by Sjors**
This adds 7 commits on top of #16546 (External signer support) to enable multisig functionality.

It introduces a new `createmultisigwallet` RPC which can also be used without external signer support (although it's only marginally easier than importing descriptors).

It automatically fetches xpubs from connected hardware devices (using HWI), constructs BIP67 multisig descriptors (native and wrapped SegWit) and imports them into a new wallet. For not connected external signers it's also possible to manually provide an xpub.

Use `enumeratesigners` to get a list of device fingerprints, and then call the new `createmultisigwallet `:

```
createmultisigwallet "wallet_name" threshold ["fingerprint","xpub1","xpub2",...] ( avoid_reuse )

Creates and loads a new multisig wallet.
Only native segwit bech32 addresses are supported.
Arguments:
1. wallet_name           (string, required) The name for the new wallet. If this is a path, the wallet will be created at the path location.
2. threshold             (numeric, required) Number of required signatures
3. signers               (json array, required) A json array of signers identified by their BIP32 fingerprint
     [
       "fingerprint",    (string, required) master key fingerprint. Can be obtained using emumeratesigners.
       "xpub1",          (string) the xpub at deriviation path m/48h/0h/0h/1h used for P2SH_SEGWIT, obtained automatically if -signer if configured
       "xpub2",          (string) the xpub at deriviation path m/48h/0h/0h/2h used for native SegWit, obtained automatically if -signer if configured
       ...
     ]
4. avoid_reuse           (boolean, optional, default=false) Keep track of coin reuse, and treat dirty and clean coins differently with privacy considerations in mind.

Result:
{
  "name" :    <wallet_name>,        (string) The wallet name if created successfully. If the wallet was created using a full path, the wallet_name will be the full path.
  "warning" : <warning>,            (string) Warning message if wallet was not loaded cleanly.
}

Examples:
> bitcoin-cli createmultisigwallet "ManualMultisigWallet" 2 '[{"fingerprint": "d34db33f", "xpub2": "xpub6DJ2dNUysrn5Vt36jH2KLBT2i1auw1tTSSomg8PhqNiUtx8QX2SvC9nrHu81fT41fvDUnhMjEzQgXnQjKEu3oaqMSzhSrHMxyyoEAmUHQbY"}, {"fingerprint": "3442193e", "xpub1": "xpub661MyMwAqRbcFtXgS5sYJABqqG9YLmC4Q1Rdap9gSE8NqtwybGhePY2gZ29ESFjqJoCu1Rupje8YtGqsefD265TMg7usUDFdp6W1EGMcet8"}]'
> bitcoin-cli createmultisigwallet "AutomaticMultisigWallet" 2 '[{"fingerprint": "d34db33f"}, {"fingerprint": "3442193e"}]'
> curl --user myusername --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "createmultisigwallet", "params": ["ManualMultisigWallet", 2, '[{"fingerprint": "d34db33f", "xpub2": "xpub6DJ2dNUysrn5Vt36jH2KLBT2i1auw1tTSSomg8PhqNiUtx8QX2SvC9nrHu81fT41fvDUnhMjEzQgXnQjKEu3oaqMSzhSrHMxyyoEAmUHQbY"}, {"fingerprint": "3442193e", "xpub1": "xpub661MyMwAqRbcFtXgS5sYJABqqG9YLmC4Q1Rdap9gSE8NqtwybGhePY2gZ29ESFjqJoCu1Rupje8YtGqsefD265TMg7usUDFdp6W1EGMcet8"}]'] }' -H 'content-type: text/plain;' http://127.0.0.1:8332/
> curl --user myusername --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "createmultisigwallet", "params": ["AutomaticMultisigWallet", 2, '[{"fingerprint": "d34db33f"}, {"fingerprint": "3442193e"}]'] }' -H 'content-type: text/plain;' http://127.0.0.1:8332/
```

It uses the `getxpub` HWI method instead of `getdescriptors`, and constructs the descriptor locally.

TODO:
- [ ] displayaddress support for all connected devices (only ColdCard can handle this afaik, but requires producing a Multisig.txt file)
- [ ] wait for improved change address detection support, or add strong warning

See also: [Junction](https://github.com/justinmoon/junction) or [Specter Desktop](https://github.com/cryptoadvance/specter-desktop) for similar workflows.

## Change detection

Note that due to limitations in HWI, hardware wallet firmware and the PSBT format, the current multisig flow is pretty unsafe. This is because change detection generally doesn't work.

On ColdCard you can put a `multisig.txt` file to enable change detection:
```
Name: My-2-of-2
Policy: 2 of 2
Derivation: m/48h/0h/0h/2h

A1A1A1A1: xpub...
B1B1B1B1: xpub...
```

### CODE REVIEW

**Comment by Sjors** [comment]
cc @justinmoon @stepansnigirev thoughts on derivation paths?

**Comment by stepansnigirev** [comment]
Using `m/48h/0h/0h/1h` derivation path by default is ok, but I would like to be able to change the derivation path in options. Also it would be nice to provide xpub without fingerprint, then fingerprint of the xpub and `m/` as derivation path could be used, but not sure if it makes sense.
```
[
       "fingerprint",   (string, required) master key fingerprint. Can be obtained using emumeratesigners.
       "derivation",    (string) deriviation path for the key, m/48h/0h/0h/1h by default
       "xpub",          (string) the xpub, obtained automatically if -signer if configured
]
```

**Comment by Sjors** [comment]
It now uses `sortedmulti()` from #17056 and creates both native segwit and P2SH wrapped SegWit descriptors. This should match the derivation paths used by Electrum and ColdCard: https://github.com/spesmilo/electrum/pull/4465

You can test this with HWI, a ColdCard simulator plus one other wallet, e.g. Trezor (Simulator) or Ledger. After you import descriptors, you'll need to create a multisig text file for the ColdCard simulator in `work/MicroSD/multisig.txt`, using fingerprints and keys from the descriptor:

```
Name: My-2-of-2
Policy: 2 of 2
Derivation: m/48h/0h/0h/2h

A1A1A1A1: tpub...
B1B1B1B1: tpub...
```

Now you can send and receive, even with the GUI. The ColdCard simulator seems to just auto-sign if everything is OK.

**Comment by Sjors** [comment]
I'll look into this again when there's more progress on a standard for multisig wallet coordination, see #18142.

**Comment by Rspigler** [comment]
Hi @Sjors - see [BSMS](https://github.com/bitcoin/bips/pull/1097) for a standard for multisig wallet coordination

**Comment by Rspigler** [comment]
Should this be reopened?

**Comment by gremen1918** [comment]
can you help me hope to earn bitcoin, i have fully downloaded.
trying unlist nothing shows

**Comment by Sjors** [comment]
I have some ideas on how to tackle this, but not need to reopen this PR. First step is #22341

**Pull request closed without merging**
