### PR TITLE
Adding test case for SINGLE|ANYONECANPAY hash type in tx_valid.json

### PR DESCRIPTION
**Pull request by Christewart**
We are missing a test vector for SINGLE|ANYONECANPAY inside of tx_valid.json. This addresses the issue #12060

### CODE REVIEW

**Comment by jnewbery** [comment]
> Seems like the travis failure is unrelated?

Yes, looks like another instance of #11777. I've restarted the job.

**Comment by practicalswift** [comment]
Concept ACK! 👍

**Review by TheBlueMatt — COMMENTED** [review]
utACK. At least the signatures decode as [SINGLE|ANYONECANPAY] so no reason not to have more tests.

**Comment by MarcoFalke** [comment]
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

utACK 18be3ab13964ebdc0bbaf739b2b29aa34de53dc5
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJaV6JTAAoJENLqSFDnUoslIRoP/3NB6Vq1FnCksrUlEoO1ZEVm
+9Ju7o/v7Sz73qeJ6ynOZgrNSQMCsq7V6e2mnWGJj6hG3rhBUdRguqmR06iabt5b
pbsHGghX3g7+E7pI4bbpF4yLf6Bd0FpOWo9YDvCOkLe4QV7XLRBkLY2d2LTYSc57
JV2WQvdfx6UPPpzLJK3gztSLjBy/m18Ij1Edij1THVbpjinObhO5t/1Rs/2QPe8v
9c3CTnF+TaWuWe44U9Ej75mUQWCDm1g2WG+tkKbnUx1C48KC2unx7PdxatDdEs0N
CErqdszTnwF/6XkKDseL5F9bB91As8iJ4c5HDR7ThVxko+ew4M3/mxepkRBOaQZx
1lzx8c070VuBhQghTIUEqFkTVaQFdvtBjcCW2DYOkvrlaPf4nOfIjC11HDUhEZo6
OkJ2Nm+HiFktDW9nG9WnYjr9Wv44k+jLPcjyObpLmIbAPTZ2gzXrqP0XZoBlp0K7
0eWWxX2aPQg+y7oL8GBSiMmRKnVTF/T5pSMB+H/2d3kZurLw5/QyY5GcVUWwrqXx
/Ud106jSIpl/W6qCPKe5WNGeX+Ez0mjC510GbfVyfO2ZnYuoEpRgz5qh+PL0ZCir
WW/YQgrOs47MFm01EJhH68NbLLF2dyehiFudC7s6raIsJzVTdV90+JOJVcYAVvkF
GLCOf83Bx+0MbZ01tINp
=1EnU
-----END PGP SIGNATURE-----

**Pull request merged**
