### PR TITLE
refactor: remove extra CBlockIndex declaration

### PR DESCRIPTION
**Pull request by rrybarczyk**
Remove duplicate `class CBlockIndex;` declaration.

### CODE REVIEW

**Comment by promag** [comment]
ACK 9824a0d. Is this a random finding or you have searched for more similar cases?

**Comment by rrybarczyk** [comment]
Just a random find

**Review by fanquake — APPROVED** [review]
ACK 9824a0d6e91f75477b8417a2acb3301a8e8d8aa1

Initial usage was introduced in d76a8acb9b7bcabf43e3e05168a36911f187818d (#6680). The duplicate was introduced in 7d0bf0bb4652fad052d5bf3ca3bf883754b46ead (#6480), which was actually merged after #6680.

**Comment by practicalswift** [comment]
utACK 9824a0d6e91f75477b8417a2acb3301a8e8d8aa1

Welcome as a contributor!

@promag This seems to be the only instance:

```
$ git grep -E '^(class|struct|extern) .*;' -- "*.h" "*.cpp" | sort | uniq -c | grep -vE ' 1 '
      2 src/validationinterface.h:class CBlockIndex;
```

**Comment by promag** [comment]
@practicalswift nice ;)

**Pull request merged**
