### PR TITLE
[26.x] Backports for rc2

### PR DESCRIPTION
**Pull request by fanquake**
Backports for v26.0rc2:
* #28695
* #28698
* #28728
* #28757
* #28759
* https://github.com/bitcoin-core/gui/pull/774

### CODE REVIEW

**Comment by josibake** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/28754/commits/6772a6272129629659e66d245d1911420a3a72ac

Pulls in the correct commit for the bugfix, compiled without any issues so seems fine to leave off the IWYU commit from the original PR.

**Comment by fanquake** [comment]
Added final backports, and bumped version + manpages. We also just merged a translation update, which I rebased this branch on top of.

**Review by hebasto — APPROVED** [review]
ACK 9c29048dac5dfa5a06323b350156b1212b87d56d, I've applied backport locally and got a zero diff. Also I've reviewed the last two commits.

**Review by sedited — APPROVED** [review]
lgtm ACK 9c29048dac5dfa5a06323b350156b1212b87d56d

**Review by hebasto — APPROVED** [review]
re-ACK e4e84790f62990f31a519f1ec0e8cc16e93a3c3b, only a backport of https://github.com/bitcoin-core/gui/pull/774 added since my [recent](https://github.com/bitcoin/bitcoin/pull/28754#pullrequestreview-1707143194) review.

**Review by sedited — APPROVED** [review]
Re-ACK e4e84790f62990f31a519f1ec0e8cc16e93a3c3b

**Comment by josibake** [comment]
ACK https://github.com/bitcoin/bitcoin/commit/e4e84790f62990f31a519f1ec0e8cc16e93a3c3b

**Pull request merged**
