### PR TITLE
-acceptnonstdtxn option to skip "non-standard transaction" checks

### PR DESCRIPTION
**Pull request by luke-jr**
Adds a -acceptnonstdtxn option to allow miners to easily accept "non-standard" transactions

We probably want to amend this with a block for OP_NOP*?

### CODE REVIEW

**Comment by luke-jr** [comment]
Considering that merging this would have avoided [the recent sigop-flooding problem](https://www.reddit.com/r/Bitcoin/comments/3pouij/new_cheap_way_to_flood_attack_bitcoin_network/), can I get this reopened and reconsidered?

**Comment by dcousens** [comment]
@luke-jr how would it have avoided that?

**Comment by luke-jr** [comment]
[The top commit since early 2014](https://github.com/luke-jr/bitcoin/commit/a524f5449ecffebfeae7df3da36c109357fc2e1e) limits sigops to a reasonable rate per bytes. This not only causes the fee logic to reflect the cost as expected, but also requires any attempt to spam sigops to also spam data meeting the block size before the block sigop limit.

**Comment by dcousens** [comment]
Fair enough,  but,  that isn't part of this PR?

**Comment by luke-jr** [comment]
It is as soon as it gets reopened. (GitHub ignores updates when the PR is closed.)

**Comment by eragmus** [comment]
Any update on this? Identical attack resurfaced 3 days ago:
> https://www.reddit.com/r/Bitcoin/comments/3ur5ma/stuck_transactions/

**Comment by luke-jr** [comment]
That part was split into #7081

**Comment by eragmus** [comment]
Okay, thanks!

**Pull request closed without merging**
