### PR TITLE
wallet: use vector instead of list for transactions

### LINKED ISSUE #25229: Memory leak via API listtransactions
Hello. I use a bitcoind with a large wallet containing about 150K transactions.
Each time the method listtransactions is used the memory consumed by the process grows. As a result it can take up all possible memory and ends with a kill signal.

System information:
CentOS 8.4
CPU Cores: 12
RAM: 64GB
SSD: 1TB

### PR DESCRIPTION
**Pull request by ghost**
This fixes https://github.com/bitcoin/bitcoin/issues/25229

I tested on Fedora with below steps and could list transactions several times on PR branch while Master branch bitcoind crashed in running `listtransactions`:

1. Add thousands of transactions in a wallet on regtest with `bitcoin-cli generatetoaddress 100000 ADDRESS`
2. Run `listtransactions` command multiple times in Master and PR branch: `bitcoin-cli listtransactions "*" 100000 1000`
3. Keep an eye on CPU and memory usage with `top`

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Can you explain *why* this fixes the bug? This may change the memory usage, but I fail to see a memory leak or how this fixes it.

**Comment by pakizefar** [comment]
+989333054600

**Comment by 1440000bytes** [comment]
> Can you explain _why_ this fixes the bug? This may change the memory usage, but I fail to see a memory leak or how this fixes it.

I was testing based on the things shared in https://github.com/bitcoin/bitcoin/issues/25229 and trying to improve performance. I am assuming the issue is accidentally fixed with this pull request but need confirmation from reviewers.

First thing that I wanted to change in the code was `std::list` with something that has less performance issues in C++. After reading a few articles found that `std::vector` can be an easy replacement to improve performance in this case.

> In C++ there is only one God, and its name is vector.

https://blog.quasar.ai/using-c-containers-efficiently

> std::vector is insanely faster than std::list to find an element
std::vector always performs faster than std::list with very small data
std::vector is always faster to push elements at the back than std::list
std::list handles large elements very well, especially for sorting or inserting in the front

https://dzone.com/articles/c-benchmark-%E2%80%93-stdvector-vs

Cleared vector elements in `ListTransactions()` because I think its not going out of scope to free memory and is required before running `listtransactions` again. It was also done in `CachedTxGetAmounts()` in [src/wallet/receive.cpp](https://github.com/bitcoin/bitcoin/blob/ba48fcf4a40c5b9888459511fb4233a1b89184cc/src/wallet/receive.cpp#L230)

**Comment by 1440000bytes** [comment]
It improved performance but did not fix the issue. In the video `bitcoind` still crashes after running 4 times in a wallet with 100k transactions trying to list them all every minute. Closing this pull request as it does not fix the real issue.

https://user-images.githubusercontent.com/94559964/170909843-cf056e9e-f3a1-419c-83be-a241b4fc9ba6.mp4

**Comment by luke-jr** [comment]
It's not clear to me that this should be closed. Even if it doesn't fix the referenced issue, is it still a noticeable performance improvement?

**Comment by 1440000bytes** [comment]
> It's not clear to me that this should be closed. Even if it doesn't fix the referenced issue, is it still a noticeable performance improvement?

I will reopen after doing a few more tests and see if there is any significant improvement in performance.

**Pull request closed without merging**
