### PR TITLE
Remove vfReachable and modify IsReachable to only use vfLimited.

### PR DESCRIPTION
**Pull request by pstratem**
We do not know that a class of Network is reachable, only that it is not.

### CODE REVIEW

**Comment by laanwj** [comment]
Possibly related issue, there's some discussion there:
- Addrman only contains seed nodes when there's no externally bound address #7098 @theuni

Concept ACK, I don't think we need both vfLimited and vfReachable, though this will have to be carefully checked to make sure it still respects onlynet, and proxies etc. No automatic tests for any of this.

**Comment by pstratem** [comment]
@laanwj Yes this will fix that issue.

onlynet and proxy settings are unaffected

**Comment by laanwj** [comment]
@theuni can you please take a look here, as you performed investigation in #7098. Do you see problems with this solution?

**Comment by theuni** [comment]
Concept ack, trying to balance the two was confusing.
Quick code review ack as well.

**Comment by sipa** [comment]
Concept ACK

**Comment by MarcoFalke** [comment]
Backported as part of #7938. Removing label 'Needs backport'.

**Pull request merged**
