### PR TITLE
Trivial: fix fee estimate write error log message

### PR DESCRIPTION
**Pull request by CryptAxe**

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
utACK

**Comment by CryptAxe** [comment]
Well I guess you can't delete remote branches with a pull request open anymore, sorry for closing / reopening

**Comment by instagibbs** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/10263/commits/94807be8c6e196c01e9bfc0e44fb1604a6714d8e

**Comment by paveljanik** [comment]
utACK 94807be

**Comment by fanquake** [comment]
utACK 94807be

**Pull request merged**
