### PR TITLE
net: Fix sent reject messages for blocks and transactions

### PR DESCRIPTION
**Pull request by laanwj**
Ever since we #5913 have been sending invalid reject messages for transactions and blocks.

### CODE REVIEW

**Comment by dcousens** [comment]
Worth adding a regression test?

**Comment by laanwj** [comment]
Would make sense.

**Comment by laanwj** [comment]
To be clear, this solves the following issue:

Normal reject message

    2015-12-07 20:16:52 peer=1096 Reject tx code 64: non-final: hash 54fae12b1dc553ec56137138ad28304569c9b3a69791fca5a02664b379a7d6ba

Reject message from 0.11.99+

    2015-12-04 16:07:00 peer=322 Reject tx code 66: : hash 6e6f69746361736e617274206565726620646574696d696c20657461721d0000

Reason seems empty, and part of the reason message ends up in the "hash". This is due to the reject code being sent as multiple bytes instead of one, misaligning the message.

**Comment by MarcoFalke** [comment]
utACK 9fc6ed6

**Comment by laanwj** [comment]
Added basic tests for rejection of blocks and transactions.

**Comment by laanwj** [comment]
@sdaftuar Ming taking a look at the test changes?

**Comment by sdaftuar** [comment]
Sure, will take a look.

**Comment by sdaftuar** [comment]
post-merge ACK.  The extension to the test framework seems like a good idea!

**Comment by laanwj** [comment]
This is cherry-picked to 0.12 as 44fef99e666e85caa7616765412d7becf97ab673, removing needs backport label

**Pull request merged**
