### PR TITLE
Make AbortNode function static

### PR DESCRIPTION
**Pull request by Empact**
Has been src/validation.cpp-only since 27afcd89db302d87168e0f504ee141dbf0e1ea22

### CODE REVIEW

**Comment by MarcoFalke** [comment]
I fail to see how this makes a difference? I suggest closing the pull request according to the guidelines https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#refactoring

**Comment by Empact** [comment]
Fair enough, since it isn't declared elsewhere, it's already limited to this file. Static would just make that explicit / enforced.

**Comment by MarcoFalke** [comment]
You'd had to add a section to the developer note style guide and get that accepted first, otherwise people will refactor the code back and forth to their own liking.

**Comment by Empact** [comment]
A happy ending: #13163 :)

**Pull request closed without merging**
