### PR TITLE
script: Add commits signed with sipas expired key to allow-revsig-commits

### LINKED ISSUE #22737: verify commits failed
**Expected behavior**
PASS Verified

**Actual behavior**
Failed.
Some console printed as followed:
No parent of 803ef70fd9f65ef800567ff9456fac525bc3e3c2 was signed with a trusted key!
Parents are: (NOTHING)

**To reproduce**
step 1: cd path/to/bitcoin

step 2: gpg --keyserver hkps://keys.openpgp.org --recv-keys $(<contrib/verify-commits/trusted-keys)
console log is :
gpg: key 410108112E7EA81F: no user ID
gpg: key 944D35F9AC3DB76A: "Michael Ford (bitcoin-otc) <fanquake@gmail.com>" not changed
gpg: key D300116E1C875A3D: "MeshCollider <dobsonsa68@gmail.com>" not changed
gpg: key 3648A882F4316B9B: "Marco Falke <marco.falke@tum.de>" not changed
gpg: key 29D4BCB6416F53EC: "Jonas Schnelli <dev@jonasschnelli.ch>" not changed
gpg: key 860FEB804E669320: "Pieter Wuille <pieter@wuille.net>" not changed
gpg: key 74810B012346C9A6: "Wladimir J. van der Laan <laanwj@visucore.com>" not changed
gpg: Total number processed: 7
gpg:              unchanged: 6

step 3: git fetch origin && ./contrib/verify-commits/verify-commits.py origin/master && git checkout origin/master

**System information**

HEAD commit id:  bb9f76a71
OS: MacOS Big Sur
Python:
Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 26 2018, 19:50:54)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin

### PR DESCRIPTION
**Pull request by n-thumann**
Fixes https://github.com/bitcoin/bitcoin/issues/22737.
While investigating the issue above, I noticed that there are 141 commits that are signed with sipas expired key.
To allow `./contrib/verify-commits/verify-commits.py` to succeed, this PR adds them to `allow-revsig-commits`.
Feel free to confirm that they're indeed signed with an expired key using e.g. `git show --show-signature d8cd7b137fb075616f31d2b43b85fa2e27ea7477` :)

### CODE REVIEW

**Comment by n-thumann** [comment]
Ping @Yihen-Liu. Would you mind testing this as you reported the bug that this PR fixes? :)

**Comment by Yihen-Liu** [comment]
@n-thumann Dear man, what I did as follow:  
step one, copy the patch you push and paste them into the allowo-revsig-commits;
step two, ./contrib/verify-commits/verify-commits.py origin/master

It takes long time to verify, more than one hour;  I type CTRL-C when it does not finished automatically;

I want to confirm whether my op steps is right? if not, will you please give me right suggestion about how to checkout the patch and  verify step by step?

**Comment by n-thumann** [comment]
> It takes long time to verify, more than one hour; I type CTRL-C when it does not finished automatically;

This is perfectly fine and not unusual. Please don't quit it, but wait until it's done :) On my machine it took 3:15 hours to check all commits.

**Comment by Yihen-Liu** [comment]
Hi @n-thumann,
Yes, all commits verify validly and successfully which took about 3 hours on my macbook :)

**Comment by luke-jr** [comment]
It seems like there ought to be a way to tell GPG to verify against the commit date (but I couldn't find a way)

**Comment by laanwj** [comment]
Concept ACK, have not verified the commit ids.

> It seems like there ought to be a way to tell GPG to verify against the commit date (but I couldn't find a way)

This sounds like it would be good to have, though it'd need some additional assurance that the timestamps are not faked.

**Comment by sipa** [comment]
Perhaps a possibility is:
* Add a check that merge commits must have a timestamp in the past (or not more than X minutes in the future or so).
* Use libfaketime around gnupg, with time set to the commit timestamp.

**Comment by MarcoFalke** [comment]
It might be tricky to derive OTS proofs for the commits, as they are not timestamped themselves. Though there are timestamps for other commits around that time.

**Comment by laanwj** [comment]
- I created a (hacky) script to list the commits that are signed with a certain key
```python3
#!/usr/bin/env python3
from git import Repo
import subprocess
import sys

repo = Repo(".")
GIT = 'git'
keyid = sys.argv[1]
keyid = keyid.replace(' ', '').lower()

for c in repo.iter_commits():
    r = subprocess.run([GIT, 'verify-commit', c.hexsha], capture_output=True, universal_newlines=True)
    for line in r.stderr.split('\n'):
        if line.startswith(('Primary key fingerprint: ', '     Subkey fingerprint: ')):
            ckeyid = line[25:].replace(' ', '').lower()
            if ckeyid == keyid:
                print(c.hexsha)
```
- I did
```bash
git checkout master
../list-commits-with-key.py "AC66 2617 2E00 A82C FFAE  8972 A636 E976 31F7 67E0" >> contrib/verify-commits/allow-revsig-commits
git diff FETCH_HEAD contrib/verify-commits/allow-revsig-commits
```

This gives me the following output:
```patch
 d9fdac130a5ed1d96fcac6bb87c10bec9d596b17
-a07e8caa5d5000286604458e6887f57fec7fdcbb
-8b262eb2d80bfa27ae8501078ce47bc1407e9c55
-5df84de583c900e00fef63bedaef32786f205a33
-4ba6da55743a55189164e29e45ac9e73a074d808
 5bea05bc1d17aa43cbdf3a3413241f8132790d93
```
These four commits are signed with the key but not included in this commit:
```
a07e8caa5d5000286604458e6887f57fec7fdcbb Merge #13033: Build txindex in parallel with validation
8b262eb2d80bfa27ae8501078ce47bc1407e9c55 Merge #13021: MOVEONLY: Move logging code from util.{h,cpp} to new files.
5df84de583c900e00fef63bedaef32786f205a33 Merge #12970: logging: bypass timestamp formatting when not logging
4ba6da55743a55189164e29e45ac9e73a074d808 Merge #12743: Fix csBestBlock/cvBlockChange waiting in rpc/mining
```
Is this intentional?

**Comment by laanwj** [comment]
Oh, I see, they're already in the file, so would be duplicate. Ok, fair enough.

Code review ACK 365f35481d5c04109d64e88e548d6985705c2f75

**Pull request merged**
