### PR TITLE
net: Hardcoded seeds update January 2016

### LINKED ISSUE #7399: Need update of hardcoded seeds for 0.12
Just a reminder.

### PR DESCRIPTION
**Pull request by laanwj**
Update hardcoded seed list for mainnet.
(not sure where to get one for testnet3, but it's less important...)

Also update documentation in contrib/seeds/README.md.

Fixes #7399

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Tested ACK 4818dba90074f213efa0fa7faf577ce5fb02eaee (I get roughly the same seeds)

**Comment by paveljanik** [comment]
ACK https://github.com/laanwj/bitcoin/commit/4818dba90074f213efa0fa7faf577ce5fb02eaee

**Comment by PRabahy** [comment]
I'm still not on the list. :( I have been running a node consistently at 68.34.102.231 for quite a while. I did a little investigation back in https://github.com/bitcoin/bitcoin/pull/6333 and found that it was probably something to do with IPv6, so I have been running onlynet=ipv4. http://bitcoin.sipa.be/seeds.txt shows my node at almost 100% up-time.

**Comment by luke-jr** [comment]
Prefer to avoid listing nodes that have a specific interest in being on the list anyway.

**Comment by PRabahy** [comment]
My motivation is to make sure that the list of hardcoded seeds is accurate. For the 1 data point that I have direct knowledge of (my own node), it does not appear that the list is accurate. If I was interested in attacking the bitcoin network, there would be much more effective ways that getting my node on this list.

Either way, I manually verified about a dozen of the nodes on the new list and most of them showed up as online. Looks good enough to me.

**Comment by jonasschnelli** [comment]
If somebody wants to compare the output, my dns seeders data would be here:
https://bitcoin.jonasschnelli.ch/dnsseed.dump

**Comment by laanwj** [comment]
@PRabahy I have no idea why you're not listed, but if it appears in seeds.txt it should be straightforward to trace it through the `makeseeds.py` script and see which filter pass "eats" it.

**Comment by MarcoFalke** [comment]
@PRabahy your weekly uptime is 87% (sipa) or 86% ([21](https://bitnodes.21.co/nodes/leaderboard/?q=68.34.102.231#leaderboard)). I don't think this is enough to get into the list.

**Comment by gmaxwell** [comment]
ACK

**Comment by laanwj** [comment]
Backported to 0.12 as cb83beb3759b9bd19cc13b1e3dd589349787ac3e

**Pull request merged**
