### PR TITLE
Remove confusing CAddrDB

### PR DESCRIPTION
**Pull request by maflcko**
Split out from #22762 to avoid having to carry it around in (an)other rebase(s)

### CODE REVIEW

**Comment by practicalswift** [comment]
Concept ACK

**Review by ryanofsky — APPROVED** [review]
Code review ACK fade9a1a4db71241ccad03fdacfb626453952963

**Review by lsilva01 — APPROVED** [review]
Code Review ACK https://github.com/bitcoin/bitcoin/pull/22915/commits/fade9a1a4db71241ccad03fdacfb626453952963

This change makes the code clearer.

**Comment by MarcoFalke** [comment]
Going to merge this because the commit has another three (indirect) ACKs from the parent pull.

**Pull request merged**
