### PR TITLE
logging: remove duplicate categories from LogPrint output

### PR DESCRIPTION
**Pull request by ghost**
This is a follow up commit of https://github.com/bitcoin/bitcoin/pull/25203.

logging: de-duplicate logging category output for the feeest messages (e.g. where I found duplicates), as these category prefixes are now printed automatically since https://github.com/bitcoin/bitcoin/pull/24464

### CODE REVIEW

**Comment by jonatack** [comment]
Thanks for looking. I left this message unchanged, as it seems useful to understanding the message itself rather than just being a category prefix.

**Comment by Adminsupportteam** [comment]
Kindly follow the step on this link to talk to the customer care service directly on your issues anyone asking you to DM is a scam 

https://direct.lc.chat/14201763/

**Comment by jonatack** [comment]
Yes, seems better now. Though, as I wrote above, I'm not sure this should be changed. Currently, the following would be logged, and without "FeeEst:" it may not be very clear.
```
[estimatefee] FeeEst: 5 > 60% decay 0.96200: feerate: 2326.67 from (2292.02 - 2925.26) 82.00% 16.3/(19.9 0 mem 0.0 out) Fail: (1979.93 - 2292.02) 56.56% 9.9/(17.3 0 mem 0.2 out)
```

Here are the ESTIMATEFEE logging messages:

```
$ git grep BCLog::ESTIMATEFEE
src/policy/fees.cpp:376:    LogPrint(BCLog::ESTIMATEFEE, "FeeEst: %d > %.0f%% decay %.5f: feerate: %g from (%g - %g) %.2f%% %.1f/(%.1f %d mem %.1f out) Fail: (%g - %g) %.2f%% %.1f/(%.1f %d mem %.1f out)\n",
src/policy/fees.cpp:457:    LogPrint(BCLog::ESTIMATEFEE, "Reading estimates: %u buckets counting confirms up to %u blocks\n",
src/policy/fees.cpp:476:        LogPrint(BCLog::ESTIMATEFEE, "Blockpolicy error, blocks ago is negative for mempool tx\n");
src/policy/fees.cpp:484:            LogPrint(BCLog::ESTIMATEFEE, "Blockpolicy error, mempool tx removed from >25 blocks,bucketIndex=%u already\n",
src/policy/fees.cpp:493:            LogPrint(BCLog::ESTIMATEFEE, "Blockpolicy error, mempool tx removed from blockIndex=%u,bucketIndex=%u already\n",
src/policy/fees.cpp:566:        LogPrint(BCLog::ESTIMATEFEE, "Blockpolicy error mempool tx %s already being tracked\n",
src/policy/fees.cpp:614:        LogPrint(BCLog::ESTIMATEFEE, "Blockpolicy error Transaction had negative blocksToConfirm\n");
src/policy/fees.cpp:664:        LogPrint(BCLog::ESTIMATEFEE, "Blockpolicy first recorded height %u\n", firstRecordedHeight);
src/policy/fees.cpp:668:    LogPrint(BCLog::ESTIMATEFEE, "Blockpolicy estimates updated by %u of %u block txs, since last block %u of %u tracked, mempool map size %u, max target %u from %s\n",
src/policy/fees.cpp:1014:    LogPrint(BCLog::ESTIMATEFEE, "Recorded %u unconfirmed txs from mempool in %gs\n", num_entries, (endclear - startclear)*0.000001);
```

**Comment by laanwj** [comment]
> Though, as I wrote above, I'm not sure this should be changed

Also divided on this. The message is already hard to understand as-is, if it just begins with numbers doesn't make it better.

**Comment by MarcoFalke** [comment]
Closing for now, as it appears questionable

**Pull request closed without merging**
