### PR TITLE
Docs: correction to test readme compile instructions

### PR DESCRIPTION
**Pull request by JBaczuk**
I'm pretty sure this wording is just switched, but correct me if I'm wrong. If you have only changed a test file, you can just build the files in the test folder, no need to build the entire source.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Our compile tooling will notice that only test files have been modified and thus `make` will only compile the test files if they have been modified, so the wording as in master sounds correct to me.

**Comment by JBaczuk** [comment]
I'm just confused because it says, "If you modify a **non-test** file, use `make -C src/test` to recompile only what's needed to run the bitcoind tests."

Wouldn't that only compile **test** files?

**Comment by sipa** [comment]
@JBaczuk And all core files needed to run those tests. Make reasons about dependencies.

**Comment by JBaczuk** [comment]
@sipa Ah, ok, sounds like I'm mistaken, then, thanks.

**Pull request closed without merging**
