### PR TITLE
build: upgrade to boost 1.77 to fix c++20 compilation

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
I've been investigating compiling bitcoin core using C++20. It appears that our usage of boost requires boost 1.73 or above in order to compile using C++20 (compilation fails with any version lower than that). After initial review, it was recommended to bump boost to 1.77.

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
Any thoughts on this? If there are no objections, I think it makes sense to move forward with this change

**Comment by fanquake** [comment]
>  If there are no objections, I think it makes sense to move forward with this change

I think this is an awkward bump, and if we are going to update Boost again, it might as well be to the current latest version, which is 1.77.0. As mentioned, that would mean we can drop a suppression, and we'd avoid some build warnings related to unused variables in the process module. We are also early enough in the release cycle that if there are any serious issues the update could be reverted. Just make sure you update our Boost package to account for the fact that we don't need the CMake files that will be generated with the newer version.

Also, please write a better commit message. i.e `build: update depends Boost to 1.77.0`.

**Comment by PastaPastaPasta** [comment]
Bumped to 1.77 and removed suppression as suggested above, will sqash once we have ACKs / Concept ACKs

**Comment by hebasto** [comment]
> ... will sqash once we have ACKs / Concept ACKs

The opposite is preferable though...

**Comment by PastaPastaPasta** [comment]
> > ... will sqash once we have ACKs / Concept ACKs
> 
> The opposite is preferable though...

Okay, squashed, I generally prefer having a clean history, but that's okay :)

**Comment by MarcoFalke** [comment]
> �[0;32m node1 stderr ERROR: The syscall "fstatfs" (syscall number 138) is not allowed by the syscall sandbox in thread "httpworker.0". Please report.

**Comment by PastaPastaPasta** [comment]
> > �[0;32m node1 stderr ERROR: The syscall "fstatfs" (syscall number 138) is not allowed by the syscall sandbox in thread "httpworker.0". Please report.

Any suggestions? I'd be happy to revert to 1.76 and work it down until ci is happy?

**Comment by MarcoFalke** [comment]
Either you add it in the right place, like commit fab360aa0027a274681eff3f00ac1972bcfa126c or you wait for #20744 or you pick a different version. Not opinion on what to do.

**Comment by PastaPastaPasta** [comment]
> Either you add it in the right place, like commit [fab360a](https://github.com/bitcoin/bitcoin/commit/fab360aa0027a274681eff3f00ac1972bcfa126c) or you wait for #20744 or you pick a different version. Not opinion on what to do.

If someone would like to provide a diff similar to what Marco mentions, I'll be happy to apply it, but I'm not too familiar with syscall sandboxing

At this point, I'm going to move forward with trying version working back from 1.77 to 1.76 etc until I find one that CI is happy with.

**Comment by fanquake** [comment]
> Bumped to 1.77 and removed suppression as suggested above, 

You didn't update to account for the Cmake files as [mentioned](https://github.com/bitcoin/bitcoin/pull/23340#issuecomment-962763343).

> Okay, squashed, I generally prefer having a clean history, but that's okay :)

Pull requests are expected to contain changes that are reviewable / ACKable. Don't push random changes / fixups with the intent to "squash later"; make whatever changes/fixups you need to locally, then squash, fixup commit messages etc, before pushing to GitHub. Separately, rather than crossing out stuff in your PR description, either update it if it's relevant, or remove it entirely, otherwise it's just polluting the merge message with garbage. Given the point of this PR is to fix the C++20 build, it would be worthwhile including what is actually failing with Boost 1.71.0, or why 1.73.0 or later is required.

> At this point, I'm going to move forward with trying version working back from 1.77 to 1.76 etc until I find one that CI is happy with.

I'd still rather we move to 1.77.0, adding any syscall exceptions as needed. Also, please don't do development via CI. It's noisy, and is really just abusing CI resources. You can run the [CI locally](https://github.com/bitcoin/bitcoin/tree/master/ci) to test you changes, and ensure they are working before pushing them up.

**Comment by MarcoFalke** [comment]
```
�[0;39;49m�[1;34;49mtest/bip32_tests.cpp(159): Entering test suite "bip32_tests"
�[0;39;49m�[1;34;49mtest/bip32_tests.cpp(177): Entering test case "bip32_test5"
==78132==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x562ff2d626fb in boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*) /tmp/cirrus-ci-build/depends/work/build/x86_64-pc-linux-gnu/boost/1_75_0-25950737f88/libs/filesystem/src/operations.cpp:2603:7
    #1 0x562ff2d6f3c0 in boost::filesystem::detail::temp_directory_path(boost::system::error_code*) /tmp/cirrus-ci-build/depends/work/build/x86_64-pc-linux-gnu/boost/1_75_0-25950737f88/libs/filesystem/src/operations.cpp:2799:24
    #2 0x562ff15276b0 in boost::filesystem::temp_directory_path() /tmp/cirrus-ci-build/depends/x86_64-pc-linux-gnu/include/boost/filesystem/operations.hpp:517:46
    #3 0x562ff151ae48 in BasicTestingSetup::BasicTestingSetup(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<char const*, std::__1::allocator<char const*> > const&) src/test/util/setup_common.cpp:76:19
    #4 0x562ff0697d82 in bip32_tests::bip32_test5::bip32_test5() src/test/bip32_tests.cpp:177:1
    #5 0x562ff068abc6 in bip32_tests::bip32_test5_invoker() src/test/bip32_tests.cpp:177:1
    #6 0x562ff0592e98 in boost::detail::function::void_function_invoker0<void (*)(), void>::invoke(boost::detail::function::function_buffer&) /tmp/cirrus-ci-build/depends/x86_64-pc-linux-gnu/include/boost/function/function_template.hpp:117:11
    #7 0x562ff2f4dbac in boost::function0<void>::operator()() const /tmp/cirrus-ci-build/depends/work/build/x86_64-pc-linux-gnu/boost/1_75_0-25950737f88/./boost/function/function_template.hpp:763:14
    #8 0x562ff2f4dbac in boost::detail::forward::operator()() /tmp/cirrus-ci-build/depends/work/build/x86_64-pc-linux-gnu/boost/1_75_0-25950737f88/./boost/test/impl/execution_monitor.ipp:1388:32
    #9 0x562ff2f4dbac in boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke(boost::detail::function::function_buffer&) /tmp/cirrus-ci-build/depends/work/build/x86_64-pc-linux-gnu/boost/1_75_0-25950737f88/./boost/function/function_template.hpp:137:18
    #10 0x562ff2f40aba in boost::function0<int>::operator()() const /tmp/cirrus-ci-build/depends/work/build/x86_64-pc-linux-gnu/boost/1_75_0-25950737f88/./boost/function/function_template.hpp:763:14
    #11 0x562ff2f40aba in int boost::detail::do_invoke<boost::shared_ptr<boost::detail::translator_holder_base>, boost::function<int ()> >(boost::shared_ptr<boost::detail::translator_holder_base> const&, boost::function<int ()> const&) /tmp/cirrus-ci-build/depends/work/build/x86_64-pc-linux-gnu/boost/1_75_0-25950737f88/./boost/test/impl/execution_monitor.ipp:301:30
    #12 0x562ff2f40aba in boost::execution_monitor::catch_signals(boost::function<int ()> const&) /tmp/cirrus-ci-build/depends/work/build/x86_64-pc-linux-gnu/boost/1_75_0-25950737f88/./boost/test/impl/execution_monitor.ipp:903:16
    #13 0x562ff2f4119b in boost::execution_monitor::execute(boost::function<int ()> const&) /tmp/cirrus-ci-build/depends/work/build/x86_64-pc-linux-gnu/boost/1_75_0-25950737f88/./boost/test/impl/execution_monitor.ipp:1301:16
    #14 0x562ff2f45559 in boost::execution_monitor::vexecute(boost::function<void ()> const&) /tmp/cirrus-ci-build/depends/work/build/x86_64-pc-linux-gnu/boost/1_75_0-25950737f88/./boost/test/impl/execution_monitor.ipp:1397:5
    #15 0x562ff2e58393 in boost::unit_test::unit_test_monitor_t::execute_and_translate(boost::function<void ()> const&, unsigned long) /tmp/cirrus-ci-build/depends/work/build/x86_64-pc-linux-gnu/boost/1_75_0-25950737f88/./boost/test/impl/unit_test_monitor.ipp:49:9
    #16 0x562ff2dcc644 in boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned long, boost::unit_test::framework::state::random_generator_helper const*) /tmp/cirrus-ci-build/depends/work/build/x86_64-pc-linux-gnu/boost/1_75_0-25950737f88/./boost/test/impl/framework.ipp:815:44
    #17 0x562ff2dcd898 in boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned long, boost::unit_test::framework::state::random_generator_helper const*) /tmp/cirrus-ci-build/depends/work/build/x86_64-pc-linux-gnu/boost/1_75_0-25950737f88/./boost/test/impl/framework.ipp:784:58
    #18 0x562ff2dcd898 in boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned long, boost::unit_test::framework::state::random_generator_helper const*) /tmp/cirrus-ci-build/depends/work/build/x86_64-pc-linux-gnu/boost/1_75_0-25950737f88/./boost/test/impl/framework.ipp:784:58
    #19 0x562ff2db5595 in boost::unit_test::framework::run(unsigned long, bool) /tmp/cirrus-ci-build/depends/work/build/x86_64-pc-linux-gnu/boost/1_75_0-25950737f88/./boost/test/impl/framework.ipp:1721:29
    #20 0x562ff2e53b36 in boost::unit_test::unit_test_main(boost::unit_test::test_suite* (*)(int, char**), int, char**) /tmp/cirrus-ci-build/depends/work/build/x86_64-pc-linux-gnu/boost/1_75_0-25950737f88/./boost/test/impl/unit_test_main.ipp:250:9
    #21 0x562ff2e55500 in main /tmp/cirrus-ci-build/depends/work/build/x86_64-pc-linux-gnu/boost/1_75_0-25950737f88/./boost/test/impl/unit_test_main.ipp:306:12
    #22 0x7f39b873b0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #23 0x562ff03e9c4d in _start (/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/src/test/test_bitcoin+0x10fc4d)

  Uninitialized value was created by an allocation of 'path_stat' in the stack frame of function '_ZN5boost10filesystem6detail6statusERKNS0_4pathEPNS_6system10error_codeE'
    #0 0x562ff2d620f0 in boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*) /tmp/cirrus-ci-build/depends/work/build/x86_64-pc-linux-gnu/boost/1_75_0-25950737f88/libs/filesystem/src/operations.cpp:2572

SUMMARY: MemorySanitizer: use-of-uninitialized-value /tmp/cirrus-ci-build/depends/work/build/x86_64-pc-linux-gnu/boost/1_75_0-25950737f88/libs/filesystem/src/operations.cpp:2603:7 in boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)
Exiting
make[3]: *** [Makefile:18537: test/bip32_tests.cpp.test] Error 1

**Comment by MarcoFalke** [comment]
You can rebase on #23555

**Comment by PastaPastaPasta** [comment]
> You can rebase on #23555

I presume you want me to revert back to 1.77 and rebase, correct?

**Comment by MarcoFalke** [comment]
Looks like the msan issue is still there. Maybe a miscompilation? (Can't reproduce in valgrind so far)

Also, we should watch out for this change in boost 1.76: https://github.com/bitcoin/bitcoin/pull/23551#issuecomment-974292532

**Comment by dougEfresh** [comment]
In case this helps, 
Even if you upgrade to clang13 with llvm13 libc++ and use **std::filesystem** instead of boost you get a similar error:

```
SUMMARY: MemorySanitizer: use-of-uninitialized-value /tmp/cirrus-ci-build/ci/scratch/msan/llvm-project/libcxx/src/filesystem/operations.cpp:553:7 in std::__1::__fs::filesystem::detail::(anonymous namespace)::create_file_status(std::__1::error_code&, std::__1::__fs::filesystem::path const&, stat const&, std::__1::error_code*)
  ORIGIN: invalid (0). Might be a bug in MemorySanitizer origin tracking.
    This could still be a bug in your code, too!
Exiting

==75987==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7fb7ba7c0851 in std::__1::__fs::filesystem::detail::(anonymous namespace)::create_file_status(std::__1::error_code&, std::__1::__fs::filesystem::path const&, stat const&, std::__1::error_code*) /tmp/cirrus-ci-build/ci/scratch/msan/llvm-project/libcxx/src/filesystem/operations.cpp:553:7
    #1 0x7fb7ba7b7071 in posix_stat /tmp/cirrus-ci-build/ci/scratch/msan/llvm-project/libcxx/src/filesystem/operations.cpp:578:10
    #2 0x7fb7ba7b7071 in posix_stat /tmp/cirrus-ci-build/ci/scratch/msan/llvm-project/libcxx/src/filesystem/operations.cpp:583:10
    #3 0x7fb7ba7b7071 in std::__1::__fs::filesystem::__temp_directory_path(std::__1::error_code*) /tmp/cirrus-ci-build/ci/scratch/msan/llvm-project/libcxx/src/filesystem/operations.cpp:1449:20
    #4 0x557d728af752 in std::__1::__fs::filesystem::temp_directory_path() /tmp/cirrus-ci-build/ci/scratch/msan/build/include/c++/v1/filesystem:2295:10
    #5 0x557d728af752 in BasicTestingSetup::BasicTestingSetup(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<char const*, std::__1::allocator<char const*> > const&) src/test/util/setup_common.cpp:76:19
    #6 0x557d728b1cc1 in ChainTestingSetup::ChainTestingSetup(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<char const*, std::__1::allocator<char const*> > const&) src/test/util/setup_common.cpp:135:7
    #7 0x557d728b3023 in TestingSetup::TestingSetup(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<char const*, std::__1::allocator<char const*> > const&) src/test/util/setup_common.cpp:173:7
    #8 0x557d715c9c35 in RegTestingSetup::RegTestingSetup() src/./test/util/setup_common.h:107:11
    #9 0x557d715c9c35 in blockencodings_tests::SimpleRoundTripTest::SimpleRoundTripTest() src/test/blockencodings_tests.cpp:55:1
    #10 0x557d715c9c35 in blockencodings_tests::SimpleRoundTripTest_invoker() src/test/blockencodings_tests.cpp:55:1
    #11 0x557d714a7e68 in boost::detail::function::void_function_invoker0<void (*)(), void>::invoke(boost::detail::function::function_buffer&) /tmp/cirrus-ci-build/depends/x86_64-pc-linux-gnu/include/boost/function/function_template.hpp:117:11
    #12 0x557d7412da09 in boost::function0<void>::operator()() const /tmp/cirrus-ci-build/depends/work/build/x86_64-pc-linux-gnu/boost/1_77_0-7494ab49d6b/./boost/function/function_template.hpp:763:14
    #13 0x557d7412da09 in boost::detail::forward::operator()() /tmp/cirrus-ci-build/depends/work/build/x86_64-pc-linux-gnu/boost/1_77_0-7494ab49d6b/./boost/test/impl/execution_monitor.ipp:1388:32
    #14 0x557d7412da09 in boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke(boost::detail::function::function_buffer&) /tmp/cirrus-ci-build/depends/work/build/x86_64-pc-linux-gnu/boost/1_77_0-7494ab49d6b/./boost/function/function_template.hpp:137:18
    #15 0x557d74121952 in boost::function0<int>::operator()() const /tmp/cirrus-ci-build/depends/work/build/x86_64-pc-linux-gnu/boost/1_77_0-7494ab49d6b/./boost/function/function_template.hpp:763:14
    #16 0x557d74121952 in int boost::detail::do_invoke<boost::shared_ptr<boost::detail::translator_holder_base>, boost::function<int ()> >(boost::shared_ptr<boost::detail::translator_holder_base> const&, boost::function<int ()> const&) /tmp/cirrus-ci-build/depends/work/build/x86_64-pc-linux-gnu/boost/1_77_0-7494ab49d6b/./boost/test/impl/execution_monitor.ipp:301:30
    #17 0x557d74121952 in boost::execution_monitor::catch_signals(boost::function<int ()> const&) /tmp/cirrus-ci-build/depends/work/build/x86_64-pc-linux-gnu/boost/1_77_0-7494ab49d6b/./boost/test/impl/execution_monitor.ipp:903:16
    #18 0x557d74121d1f in boost::execution_monitor::execute(boost::function<int ()> const&) /tmp/cirrus-ci-build/depends/work/build/x86_64-pc-linux-gnu/boost/1_77_0-7494ab49d6b/./boost/test/impl/execution_monitor.ipp:1301:16
    #19 0x557d741257b9 in boost::execution_monitor::vexecute(boost::function<void ()> const&) /tmp/cirrus-ci-build/depends/work/build/x86_64-pc-linux-gnu/boost/1_77_0-7494ab49d6b/./boost/test/impl/execution_monitor.ipp:1397:5
    #20 0x557d7404de12 in boost::unit_test::unit_test_monitor_t::execute_and_translate(boost::function<void ()> const&, unsigned long) /tmp/cirrus-ci-build/depends/work/build/x86_64-pc-linux-gnu/boost/1_77_0-7494ab49d6b/./boost/test/impl/unit_test_monitor.ipp:49:9
    #21 0x557d73fc9bec in boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned long, boost::unit_test::framework::state::random_generator_helper const*) /tmp/cirrus-ci-build/depends/work/build/x86_64-pc-linux-gnu/boost/1_77_0-7494ab49d6b/./boost/test/impl/framework.ipp:815:44
    #22 0x557d73fcae83 in boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned long, boost::unit_test::framework::state::random_generator_helper const*) /tmp/cirrus-ci-build/depends/work/build/x86_64-pc-linux-gnu/boost/1_77_0-7494ab49d6b/./boost/test/impl/framework.ipp:784:58
    #23 0x557d73fcae83 in boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned long, boost::unit_test::framework::state::random_generator_helper const*) /tmp/cirrus-ci-build/depends/work/build/x86_64-pc-linux-gnu/boost/1_77_0-7494ab49d6b/./boost/test/impl/framework.ipp:784:58
    #24 0x557d73fa8649 in boost::unit_test::framework::run(unsigned long, bool) /tmp/cirrus-ci-build/depends/work/build/x86_64-pc-linux-gnu/boost/1_77_0-7494ab49d6b/./boost/test/impl/framework.ipp:1721:29
    #25 0x557d74049d33 in boost::unit_test::unit_test_main(boost::unit_test::test_suite* (*)(int, char**), int, char**) /tmp/cirrus-ci-build/depends/work/build/x86_64-pc-linux-gnu/boost/1_77_0-7494ab49d6b/./boost/test/impl/unit_test_main.ipp:250:9
    #26 0x557d7404ab60 in main /tmp/cirrus-ci-build/depends/work/build/x86_64-pc-linux-gnu/boost/1_77_0-7494ab49d6b/./boost/test/impl/unit_test_main.ipp:306:12
    #27 0x7fb7ba33efcf  (/lib/x86_64-linux-gnu/libc.so.6+0x2dfcf)
    #28 0x7fb7ba33f07c in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2e07c)
    #29 0x557d712f2914 in _start (/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/src/test/test_bitcoin+0x15d914)
```

https://cirrus-ci.com/task/6714264523112448

**Comment by MarcoFalke** [comment]
Could rebase and remove this file: https://github.com/bitcoin/bitcoin/pull/23998/files#diff-f0d944793d9fcd5e0429c26efabf465b903cedfd17e0d744916f0ba3d3beb2e5

**Comment by PastaPastaPasta** [comment]
Done, rebased, and applied suggestion. (am out and about atm, so am not able to build depends locally)

**Comment by fanquake** [comment]
The second commit needs to be squashed, otherwise depends wont build in ce77c4baed0d0da1f21670a443da6037af4fa7f1. You need to fixup the PR description, remove all the struck-through text etc. You can also remove the portion about a `--enable-c++20` flag, as that PR already exists. You should also add why 1.77.0 is actually required to use c++20.

**Comment by fanquake** [comment]
This needs rebasing past #24276 and #24301. Unless there's a reason not too, this could now also be Boost 1.78.0.

**Comment by fanquake** [comment]
I've rebased this in #24383.

**Pull request closed without merging**
