### PR TITLE
Make segwit failure due to CLEANSTACK violation return a SCRIPT_ERR_CLEANSTACK error code

### PR DESCRIPTION
**Pull request by maaku**
If a segwit script terminates with a stack size not equal to one, the current error code is EVAL_FALSE. This is semantically wrong, and prevents explicitly checking CLEANSTACK violations in the unit tests. This PR changes the error code (and affected unit tests) to use SCRIPT_ERROR_CLEANSTACK instead of SCRIPT_ERROR_EVAL_FALSE.

### CODE REVIEW

**Comment by Christewart** [comment]
utack 1e747e3

**Review by instagibbs — APPROVED** [review]
utACK

sidenote: I do wonder what "implicit" here means in the commend above. Implicit since no flag is passed, I suppose?

**Comment by sipa** [comment]
utACK

**Comment by theuni** [comment]
utACK 1e747e3c1e04a38c5ed6e8f8cd14077b8b7377c9.

@instagibbs Yes, I read that as "if we're into witness validation, SCRIPT_VERIFY_CLEANSTACK is assumed"

**Comment by sipa** [comment]
it's more "if we're into witness validation, cleanstack is implied (regardless of SCRIPT_VERIFY_CLEANSTACK)"

**Comment by jtimon** [comment]
utACK

**Comment by randolf** [comment]
Concept ACK.

**Comment by jnewbery** [comment]
5 utACKs. Is this ready for merge?

**Pull request merged**
