### PR TITLE
scripted-diff: change kB to kvB, kilobyte to kilovbyte for transaction fee rate things

### PR DESCRIPTION
**Pull request by achow101**
Renames kB and kilobyte to kvB and kilovbyte respectively in order to make clear the fee rates are in virtual bytes rather than actual bytes.

### CODE REVIEW

**Comment by Sjors** [comment]
This disabimguation is useful, but for the UI "virtual kilobyte", "v-kilobyte", "virtual kB" or "v-kB" would be more readable than "kilovbyte" and "kvB".

schermafbeelding 2018-01-17 om 18 24 05

It will matter less if and when we switch to satoshi per byte (sat/vB or sat/vByte).

**Comment by Sjors** [comment]
Some [IRC discussion](https://botbot.me/freenode/bitcoin-core-dev/2018-01-18/?msg=95905148&page=5).

Another approach would be to just stick to "byte" in the UI and use tooltips where necessary to point out it's technically "virtual bytes".

**Comment by Sjors** [comment]
Some [IRC discussion](https://botbot.me/freenode/bitcoin-core-dev/2018-01-18/?msg=95905148&page=5).

Another approach would be to just stick to "byte" in the UI and use tooltips where necessary to point out it's technically "virtual bytes".

For RPC more precise technical terminology makes sense.

**Comment by MarcoFalke** [comment]
Tend to NACK. 

We shouldn't need to specify that the size is virtual. Either the user knows what virtual means, so they know that all sizes that involve transaction fees are virtual. Or they don't, in which case it just adds confusion.

**Comment by Sjors** [comment]
I tend to agree with @MarcoFalke, though I'm in favor of explaining this in at least some RPC calls and tooltips.

**Pull request closed without merging**
