### PR TITLE
build: Bump minimum supported GCC to g++-9

### PR DESCRIPTION
**Pull request by maflcko**
It is a bit frustrating to write valid C++ code only to realize that g++-8 fails to parse it later on.

The only non-EOL operating system still shipping with g++-8 is CentOS Stream 8. I think it is reasonable for users of affected Linux distributions to:

* Upgrade their operating system, or compiler to a supported version.
* Alternatively, stay with a previous release of Bitcoin Core as long as it is supported.

Fixes https://github.com/bitcoin/bitcoin/issues/27537

### CODE REVIEW

**Comment by fanquake** [comment]
Concept ACK - seems fine for 26.0.

**Comment by hebasto** [comment]
> The only non-EOL operating system still shipping with g++-8 is CentOS 8.

> seems fine for 26.0.

Considering https://www.centos.org/centos-linux-eol/:
> CentOS Linux 8 will reach End Of Life (EOL) on December 31st, 2021. 

I agree.

Concept ACK.

**Comment by codexnakamoto** [comment]
Concept ACK - this is logical and seems uncontentious.

**Comment by fanquake** [comment]
Could adjust the comment here: https://github.com/bitcoin/bitcoin/blob/edd2a8644531e6fb8f64ad6acce86f8fdec9ab26/src/txrequest.cpp#L72 to remove mention of GCC 8.x.

Could pull in this commit, to remove the GCC 8 `-lstdc++fs` check: https://github.com/fanquake/bitcoin/commit/b2632e7c7b7dfc5487629d80e11a8cdeaa649ed9.

**Comment by fanquake** [comment]
Are you going to pull a Clang bump into this PR? I don't see the point of leaving redundant code, especially when the diff is trivial to review.

**Comment by fanquake** [comment]
Ok. Lets kill `l_filesystem.m4`.

**Review by hebasto — APPROVED** [review]
ACK fa953f15bfcf95df9aa9c91e1c4b56a205f4d1ae

**Review by fanquake — APPROVED** [review]
ACK fa953f15bfcf95df9aa9c91e1c4b56a205f4d1ae

**Comment by fanquake** [comment]
Guix Build:
```bash
eebee5018a0bfa5e6de1ebb58522457f0f35f5636e71990af35d5b10c9ebb296  guix-build-fa953f15bfcf/output/aarch64-linux-gnu/SHA256SUMS.part
7c7a69bb6cce74a31cd747f4234332de83d201d0b6426aac3095a16b9eb09e33  guix-build-fa953f15bfcf/output/aarch64-linux-gnu/bitcoin-fa953f15bfcf-aarch64-linux-gnu-debug.tar.gz
869ae0cd106fc82ed075f1efa50993dbe588aad9316579397de594e46f18155e  guix-build-fa953f15bfcf/output/aarch64-linux-gnu/bitcoin-fa953f15bfcf-aarch64-linux-gnu.tar.gz
61764214a68b0602fc34faa3fa2077b3bc729fcf1a3131544f74f7604ecd4076  guix-build-fa953f15bfcf/output/arm-linux-gnueabihf/SHA256SUMS.part
54c823fa4b11570c40aabc8b66a16604fbd40847378f6dd4678f5357730da5f0  guix-build-fa953f15bfcf/output/arm-linux-gnueabihf/bitcoin-fa953f15bfcf-arm-linux-gnueabihf-debug.tar.gz
2c5b4a0dca818d845f9e84bd1d8e7684da20f3e22cf941ff3ee2116730a2836d  guix-build-fa953f15bfcf/output/arm-linux-gnueabihf/bitcoin-fa953f15bfcf-arm-linux-gnueabihf.tar.gz
147a3a3c900451a6637253ba1bce0e87ad98ab3add2df5e39a07a82ebb5cadf0  guix-build-fa953f15bfcf/output/arm64-apple-darwin/SHA256SUMS.part
d3e1d7f040aa025ea941a4bae91adf179f7943308c4ba3ada44b8813b5ab469c  guix-build-fa953f15bfcf/output/arm64-apple-darwin/bitcoin-fa953f15bfcf-arm64-apple-darwin-unsigned.dmg
71a4f7c2b0bcf017e872e0222f8ae6bd077381195df5284442dcce50c8b0dbf7  guix-build-fa953f15bfcf/output/arm64-apple-darwin/bitcoin-fa953f15bfcf-arm64-apple-darwin-unsigned.tar.gz
a530e0e081c770273dea777766295b05b93b89eb1ee0a5117e87f332333c82c6  guix-build-fa953f15bfcf/output/arm64-apple-darwin/bitcoin-fa953f15bfcf-arm64-apple-darwin.tar.gz
80ac0b91bc39f9027724f09fa4ff4f14a0f856a6ce049248f1ad3bcc8c33c483  guix-build-fa953f15bfcf/output/dist-archive/bitcoin-fa953f15bfcf.tar.gz
ef11be4df52aff3cf68293349b1d227af2536c3ad23d89edfd07f0cec72a2b1f  guix-build-fa953f15bfcf/output/powerpc64-linux-gnu/SHA256SUMS.part
ec69bcbd145293f473a8f17efb7da8977b12d501646e0f68fc16bed9d7a2cb44  guix-build-fa953f15bfcf/output/powerpc64-linux-gnu/bitcoin-fa953f15bfcf-powerpc64-linux-gnu-debug.tar.gz
f45677953a3f93bb61b78cde18c1245de11787e88c2cb6f62496492c1c322ea3  guix-build-fa953f15bfcf/output/powerpc64-linux-gnu/bitcoin-fa953f15bfcf-powerpc64-linux-gnu.tar.gz
786351b24d3d99500a854eaecfac24fbead87b936a2ccdaf360ea502430bbd84  guix-build-fa953f15bfcf/output/powerpc64le-linux-gnu/SHA256SUMS.part
25a1ac349dd5a27b3b2fd99a5f164fecf9644652c917c71f4bd6b0370a76f52a  guix-build-fa953f15bfcf/output/powerpc64le-linux-gnu/bitcoin-fa953f15bfcf-powerpc64le-linux-gnu-debug.tar.gz
84704403eca5d43e5de52e22c140d4889a27c757ecbe365a7ab8dc64ef4719df  guix-build-fa953f15bfcf/output/powerpc64le-linux-gnu/bitcoin-fa953f15bfcf-powerpc64le-linux-gnu.tar.gz
72395ffba3c6f63a740592998240f6aac3808d12ad35d62ac54be6ead25a2f05  guix-build-fa953f15bfcf/output/riscv64-linux-gnu/SHA256SUMS.part
ecb2eddea01f80d7b80be94071905de3a35bfe31af40ae99b3155b11bf374efd  guix-build-fa953f15bfcf/output/riscv64-linux-gnu/bitcoin-fa953f15bfcf-riscv64-linux-gnu-debug.tar.gz
31343c259dcb288bf08afb4bbef7a5751236762f0a75eebb23ed8d76c1537d43  guix-build-fa953f15bfcf/output/riscv64-linux-gnu/bitcoin-fa953f15bfcf-riscv64-linux-gnu.tar.gz
edca2d028f8e0e0070a440a37cba2e0f6db23079f895f11830caa100d8d68b4a  guix-build-fa953f15bfcf/output/x86_64-apple-darwin/SHA256SUMS.part
61b5475ba66770df37d9a3410402789c8145bc12d318def3541b7be8918c9bcb  guix-build-fa953f15bfcf/output/x86_64-apple-darwin/bitcoin-fa953f15bfcf-x86_64-apple-darwin-unsigned.dmg
d7e68fb94ee32839bbfa0e44804bebe8e200ac678c5c13abf90b96d4318dbd43  guix-build-fa953f15bfcf/output/x86_64-apple-darwin/bitcoin-fa953f15bfcf-x86_64-apple-darwin-unsigned.tar.gz
226b28549e888357ced590e132082ba23a8df6bbd70fb3f31a31ed42c29567ac  guix-build-fa953f15bfcf/output/x86_64-apple-darwin/bitcoin-fa953f15bfcf-x86_64-apple-darwin.tar.gz
c0d19bd032ca58d8b95384d4bfb6a8d5743ed6fc83e6742487c00ec34e289446  guix-build-fa953f15bfcf/output/x86_64-linux-gnu/SHA256SUMS.part
618f56abff2793f0164f4a7933b6d321a5a6beae2623bb8f771c0d76fa72a998  guix-build-fa953f15bfcf/output/x86_64-linux-gnu/bitcoin-fa953f15bfcf-x86_64-linux-gnu-debug.tar.gz
a44c967aa389f115189e02cf4395f0b1d7250cb8951a5a3ada82ed81273fad5a  guix-build-fa953f15bfcf/output/x86_64-linux-gnu/bitcoin-fa953f15bfcf-x86_64-linux-gnu.tar.gz
a93a79c849c8486e2f7b10d8e2bf6f6a12d689f1160a1fa44cce8f4875895fdd  guix-build-fa953f15bfcf/output/x86_64-w64-mingw32/SHA256SUMS.part
526f20b0603eb2a02d6bed21bcf27626bc3c4de91ab72dabc7451cb62932c6fb  guix-build-fa953f15bfcf/output/x86_64-w64-mingw32/bitcoin-fa953f15bfcf-win64-debug.zip
4b2ac3b3e6215703ccecb352ca8937644507fc13ef1da3397c96d55c56d16b09  guix-build-fa953f15bfcf/output/x86_64-w64-mingw32/bitcoin-fa953f15bfcf-win64-setup-unsigned.exe
bc63b49d35a012de63ba42a3de8f644ab4ed1a41026b1b09e885ec5363ff3579  guix-build-fa953f15bfcf/output/x86_64-w64-mingw32/bitcoin-fa953f15bfcf-win64-unsigned.tar.gz
6868d20c330862e60035734deff4da77260cccd11915a6b68beb994d38fdcad0  guix-build-fa953f15bfcf/output/x86_64-w64-mingw32/bitcoin-fa953f15bfcf-win64.zip
```

**Pull request merged**
