### PR TITLE
Fix typo in release notes.

### PR DESCRIPTION
**Pull request by dooglus**

### CODE REVIEW

**Review by jonasschnelli — APPROVED** [review]
ACK after squash

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/9803/commits/cee86b7c41c0711d4a435fc7fc3fa94f5a3f4b6d after squash

**Comment by MarcoFalke** [comment]
instagibbs is duplicated as well.

**Review by gmaxwell — APPROVED** [review]
ACK. It could remove the redundant instagibbs too, if its revised with that-- ack still applies.

**Comment by fanquake** [comment]
ACK

**Comment by laanwj** [comment]
Merged via ae1c4e2. Changes: squashed, removed redundent instagibbs, added @zw who maintains https://github.com/zw/bitcoin-gh-meta/ which is very useful while creating the changelog

**Pull request closed without merging**
