### PR TITLE
Use std::move() instead of copying/removing in TxMemPool

### PR DESCRIPTION
**Pull request by rodentrabies**
Fix for #8099 . Don't know if the solution is clean enough, but still. Tried to make changes as small as possible, thus the raw pointer and the optional parameter.

### CODE REVIEW

**Comment by sipa** [comment]
Concept ACK

**Comment by theuni** [comment]
Moving from a de-referenced shared_ptr is kinda wonky. How about passing a pointer to a list of shared_ptr instead, which you would grab using GetSharedTx rather than GetTx. Then as a bonus, you can use splice() rather than moving.

**Comment by yurizhykin** [comment]
@theuni, you mean replace `list<CTransaction>` with `list<shared_ptr<CTransaction>>` at the very top in removeForReorg(), or just in RemoveStaged()

**Comment by theuni** [comment]
@yurizhykin I mean everywhere this PR adds a ```std::list<CTransaction>* removed``` param, use ```std::list<std::shared_ptr<CTransaction> >* removed``` instead.

**Comment by sipa** [comment]
Concept ACK on passing shared_ptr instead.

**Comment by yurizhykin** [comment]
Okay, I'm not 100% sure I did exactly as I was told to, but list for storing deleted transactions is passed down the stack from some top level point (in `main.cpp` and some tests), so I had to replace `list<CTransaction>` declarations with `list<shared_ptr<const CTransaction>>` ones everywhere at those points. Also removed redundant `list<CTransaction> result` local variable declaration in `CTxMemPool::removeConflicts()`.

**Comment by sipa** [comment]
I completely forgot about this PR when writing #8515.

**Comment by yurizhykin** [comment]
Well, as long as it is done way better in #8515, I should probably just close this one.

**Pull request closed without merging**
