### PR TITLE
build: Bump clang version to fix non-determinism

### PR DESCRIPTION
**Pull request by hebasto**
Bumping clang from 6.0.1 to 8.0.0 in 5c2c835433a80c204da1335daa51a014670c7324 (#19240) came with inherent [non-determinism](https://github.com/bitcoin-core/gitian.sigs/tree/master/0.21.0rc1-osx-unsigned), that was fixed in LLVM 9.

This PR suggests the first option [from](https://github.com/bitcoin/bitcoin/pull/20436#issue-524922509):
>  - Bump to clang9 where this is fixed
>  - As **dongcarl** suggested: rewrite the some of the qt function (`qt_intersect_spans` in qpaintengine_raster.cpp) to avoid hitting the non-determinism
>  - Disable the buggy behavior via cmdline option

This is an alternative to #20436, #20440 and #20447.
No patches :)

### CODE REVIEW

**Comment by hebasto** [comment]
cc @achow101 @dongcarl @fanquake @theuni

**Comment by fanquake** [comment]
While we will likely end up doing this for 22.0,  concept NACK on switching compilers in the RC stage of a release. I'm somewhat surprised this works as is. Normally there are other minor changes required, like adjusting a path, or fixing up a `.so` name etc, however that's good to know.

**Comment by hebasto** [comment]
> While we will likely end up doing this for 22.0, concept NACK on switching compilers in the RC stage of a release.

Correct. My intention is to get this merged into the master branch, not into the 0.21. For the 0.21 branch I've already ACKed #20447.

**Comment by laanwj** [comment]
This has been my preferred way to resolve this from the beginning.

**Comment by hebasto** [comment]
My gitian macOS build:
```
Generating report
a723c3ce3816387f6f4df75b31a7cd8afe41115c37d75eb3f37ec8b19bad9e06  bitcoin-5ebb747d2a14-osx-unsigned.dmg
3ba163f8979ee9d68e19861f44d4c9757b1bd9a2af82ba902d9bc6c234ad0c47  bitcoin-5ebb747d2a14-osx-unsigned.tar.gz
e122c0511048ff7066d244277a3c83d91429b4c237a2835d17dbe96328700ebb  bitcoin-5ebb747d2a14-osx64.tar.gz
ea036d6b0e29a48a4f4776f1cee9e65e766cb74ba87130d03af2c299ff080b82  src/bitcoin-5ebb747d2a14.tar.gz
ac7c1d432f4db182cf5765bae2511881cc4a8615eccbe1c5ac6d53870789020c  bitcoin-core-osx-22-res.yml
Done.
```

**Comment by laanwj** [comment]
I think we still need to do this?
@dongcarl @fanquake

**Comment by hebasto** [comment]
Rebased on top of the #21376.

**Comment by hebasto** [comment]
Gitian builds:
```
Generating report
df3ab808f69e38bf263981e202247c253191ebba6f1e5a2d847cf1f493a73cdd  bitcoin-8df117089569-osx-unsigned.dmg
e9f3ef47f067a0145b013ce502175ccdd8465f2a1f00277e2abb2eb8e90f860d  bitcoin-8df117089569-osx-unsigned.tar.gz
0b1b52aa8c1b20bcd1e9bc75053acfdcc436de8ce382f26068ac7f7c9483d1b9  bitcoin-8df117089569-osx64.tar.gz
3196530732e8ff0388a59a30c7bad17ecb7496f844af29a3813404d6523c6284  src/bitcoin-8df117089569.tar.gz
d7f9d053360ba8ad6ba8853059b22519b4d593bbcda91071ff0eae8e5bb7d346  bitcoin-core-osx-22-res.yml
Done.

# cache was not cleared
Generating report
df3ab808f69e38bf263981e202247c253191ebba6f1e5a2d847cf1f493a73cdd  bitcoin-8df117089569-osx-unsigned.dmg
e9f3ef47f067a0145b013ce502175ccdd8465f2a1f00277e2abb2eb8e90f860d  bitcoin-8df117089569-osx-unsigned.tar.gz
0b1b52aa8c1b20bcd1e9bc75053acfdcc436de8ce382f26068ac7f7c9483d1b9  bitcoin-8df117089569-osx64.tar.gz
3196530732e8ff0388a59a30c7bad17ecb7496f844af29a3813404d6523c6284  src/bitcoin-8df117089569.tar.gz
d7f9d053360ba8ad6ba8853059b22519b4d593bbcda91071ff0eae8e5bb7d346  bitcoin-core-osx-22-res.yml
Done.

# cache was cleared
Generating report
df3ab808f69e38bf263981e202247c253191ebba6f1e5a2d847cf1f493a73cdd  bitcoin-8df117089569-osx-unsigned.dmg
e9f3ef47f067a0145b013ce502175ccdd8465f2a1f00277e2abb2eb8e90f860d  bitcoin-8df117089569-osx-unsigned.tar.gz
0b1b52aa8c1b20bcd1e9bc75053acfdcc436de8ce382f26068ac7f7c9483d1b9  bitcoin-8df117089569-osx64.tar.gz
3196530732e8ff0388a59a30c7bad17ecb7496f844af29a3813404d6523c6284  src/bitcoin-8df117089569.tar.gz
55c5c0a8f8863508f7544568d5a0c8214529f9aa57200a2babcd92486c9ec334  bitcoin-core-osx-22-res.yml
Done.
```

Guix build:
```
$ find output -type f -name *$(git rev-parse --short HEAD)*.* -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum
71fb6c229b472a34a80c8efa62c8926078ca66c47ec4eceac4dcb1689879228a  output/bitcoin-8df117089569-osx-unsigned.dmg
d86bb1f041ae104eeb524f346349a3568f3549919618f36a1c0d72186fa763e7  output/bitcoin-8df117089569-osx-unsigned.tar.gz
7b5a0f09c8c21df67aca61fcf5cb9a18c2944a71e769f50d87beb1ce1861cfaa  output/bitcoin-8df117089569-osx64.tar.gz
3196530732e8ff0388a59a30c7bad17ecb7496f844af29a3813404d6523c6284  output/src/bitcoin-8df117089569.tar.gz
```
```

**Review by jarolrod — COMMENTED** [review]
Contributing GUIX hashes, mine line up with hebasto's

```
find output -type f -name *$(git rev-parse --short HEAD)*.* -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum

71fb6c229b472a34a80c8efa62c8926078ca66c47ec4eceac4dcb1689879228a  output/bitcoin-8df117089569-osx-unsigned.dmg
d86bb1f041ae104eeb524f346349a3568f3549919618f36a1c0d72186fa763e7  output/bitcoin-8df117089569-osx-unsigned.tar.gz
7b5a0f09c8c21df67aca61fcf5cb9a18c2944a71e769f50d87beb1ce1861cfaa  output/bitcoin-8df117089569-osx64.tar.gz
3196530732e8ff0388a59a30c7bad17ecb7496f844af29a3813404d6523c6284  output/src/bitcoin-8df117089569.tar.gz
```

**Comment by fanquake** [comment]
I've now included this in #19817, as part of a toolchain bump, which also means we'd move to Clang 10.

**Pull request closed without merging**
