### PR TITLE
lint, refactor: Update cppcheck linter to c++17 and improve explicit usage

### PR DESCRIPTION
**Pull request by fjahr**
I found the `extended-lint-cppcheck` linter still uses `std=c++11` when reviewing #20471. The only difference in the output after this change is one line is missing:

```
src/script/descriptor.cpp:159:5: warning: Struct 'PubkeyProvider' has a constructor with 1 argument that is not explicit. [noExplicitConstructor]
```

After some digging, I am still not sure why this one is ignored with c++17 when 40 other`noExplicitConstructor` warnings were still appearing.

In the second commit, I fix these warnings, adding `explicit` where appropriate and adding fixes to ignore otherwise.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
🕵️ @sipa @practicalswift @achow101 have been requested to review this pull request as specified in the {FILENAME_REVIEWERS} file.

**Comment by practicalswift** [comment]
Concept ACK: explicit is better than implicit generally, and to be explicit: especially when it comes to `explicit` ctors

@fjahr Looks like the fuzzing harnesses needs some massage to compile properly after your fix :)

**Comment by fjahr** [comment]
> @fjahr Looks like the fuzzing harnesses needs some massage to compile properly after your fix :)

Thanks, forgot to do that before pushing. Should be ok now.

**Comment by practicalswift** [comment]
cr ACK 1e62350ca20898189904a88dfef9ea11ddcd8626: patch looks correct!

Rationale behind Concept ACK from C++ Core Guidelines: [By default, declare single-argument constructors `explicit`](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c46-by-default-declare-single-argument-constructors-explicit)

**Comment by MarcoFalke** [comment]
review ACK 1e62350ca20898189904a88dfef9ea11ddcd8626

**Pull request merged**
