### PR TITLE
[0.21] Update version and release notes for 0.21.2rc2

### PR DESCRIPTION
**Pull request by fanquake**
Bump version to `0.21.2rc2` and add the new backports to the release notes.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
ACK b8f5fb7c6bc2aac3b6313ba796f3ed11101caf65

**Comment by meshcollider** [comment]
LGTM

**Comment by hebasto** [comment]
Update `build_msvc/bitcoin_config.h` as well?

**Comment by fanquake** [comment]
> Update build_msvc/bitcoin_config.h as well?

Update what?

**Review by hebasto — APPROVED** [review]
ACK b8f5fb7c6bc2aac3b6313ba796f3ed11101caf65

**Pull request merged**
