### PR TITLE
GUI: Remove old translation files, reorganize translations

### PR DESCRIPTION
**Pull request by GChuf**
I have only noticed that all the "old" translation files are being used for v19 after being mentioned in https://github.com/bitcoin/bitcoin/issues/17027.
Due to some reorganizing on transifex, some language files should never have ended in v19. The correct way to update would be to delete all existing translation files and run the script afterwards.
This is the result.

FWIW: Why are there less files than before? It's because there was a lot of duplication on transifex. For example, Korean would be translated into _(ko)_ as well as _(ko_KR)_. I've deleted ko_KR in such cases, and merged such translations together to get one, more completed translation file.

I wasn't sure how to deal with 019 appropriately, so I made this PR to master.

### CODE REVIEW

**Comment by GChuf** [comment]
@laanwj please take a look.
note: this includes the zh_TW "fix" as well from the aforementioned issue.

**Comment by laanwj** [comment]
- Please change this on Transifex, never manually on the branch. The script will automatically add and remove translations to synchronize with transifex.
- We do not do translation updates on master (see https://github.com/bitcoin/bitcoin/pull/17049#issuecomment-538399860).

**Comment by laanwj** [comment]
> The correct way to update would be to delete all existing translation files and run the script afterwards. This is the result.

Wait, I'm pretty sure the script already does this? If not, we need to fix the script so this keeps happening automatically.

**Comment by laanwj** [comment]
ref https://github.com/bitcoin-core/bitcoin-maintainer-tools/pull/39

**Pull request closed without merging**
