### PR TITLE
cmake, qt: Use absolute paths for includes in MOC-generated files

### LINKED ISSUE #31145: Cmake build system breaks with symbolic links
If the `build` directory is a symbolic link, or when the entire source directory is symlinked (and we build from there), the current cmake build runs into trouble finding its own generated files.

To reproduce:
```
git clone --depth=1 https://github.com/bitcoin/bitcoin.git
mkdir build
cd bitcoin/
ln -s ../build .
cmake -Bbuild -DBUILD_GUI=ON
cd build
make
```

```
[ 37%] Building CXX object src/CMakeFiles/bitcoin_node.dir/validation.cpp.o
In file included from /data/src/tmp/bitcoin/build/src/qt/bitcoinqt_autogen/mocs_compilation.cpp:2:
/data/src/tmp/bitcoin/build/src/qt/bitcoinqt_autogen/EWIEGA46WW/moc_addressbookpage.cpp:10:10: fatal error: ../../../../../src/qt/addressbookpage.h: No such file or directory
   10 | #include "../../../../../src/qt/addressbookpage.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/qt/CMakeFiles/bitcoinqt.dir/build.make:784: src/qt/CMakeFiles/bitcoinqt.dir/bitcoinqt_autogen/mocs_compilation.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs...
```

This affects the build with Qt as well as the build with multiprocess, both which have generated files.

With autotools this wasn't an issue, so i think it can be considered a regression. But not a high-priority one as it can be worked around by specifying the full paths instead.

### PR DESCRIPTION
**Pull request by hebasto**
Fixes https://github.com/bitcoin/bitcoin/issues/31145.

From the `moc --help` output:
```
  -p <path>                         Path prefix for included file.
```

### CODE REVIEW

**Comment by hebasto** [comment]
cc @laanwj

**Comment by laanwj** [comment]
Concept ACK, will test!

**Comment by laanwj** [comment]
Tested `-DBUILD_GUI=ON` builds:
- make + whole sourcedir in symlink → works
- ninja + whole sourcedir in symlink → works
- make + build directory is symlink → works
- ninja + build directory is symlink → works

Tested ACK 6f4128e3a838d03f46d397c15bc5333287e14863

**Review by willcl-ark — APPROVED** [review]
tACK 6f4128e3a838d03f46d397c15bc5333287e14863

Tested building using a symlinked build dir using Ninja. Failures I experienced in #31145 build successfully with this patch.

**Review by sedited — APPROVED** [review]
ACK 6f4128e3a838d03f46d397c15bc5333287e14863

**Review by BrandonOdiwuor — APPROVED** [review]
ACK 6f4128e3a838d03f46d397c15bc5333287e14863

**Pull request merged**
