### PR TITLE
[DONTMERGE] Test ranked_index

### PR DESCRIPTION
**Pull request by sipa**
This is a simple test to see if boost multi_index's ranked_index works in Travis.

Do not merge.

### CODE REVIEW

**Comment by sipa** [comment]
It seems Ubuntu 16.04 (xenial) only has boost 1.58.

**Comment by MarcoFalke** [comment]
See #16381 #18943

**Comment by laanwj** [comment]
Xenial's C++ compiler doesn't support C++17 (#16684) so we're going to get rid of build-time support for that anyhow. I wouldn't mind dropping it sooner if you really need this.

**Comment by MarcoFalke** [comment]
xenial ships also with clang-8, so that should compile C++17 . But I agree that at this point we should be comfortable to tell people to use depends on xenial.

**Comment by MarcoFalke** [comment]
For reference, the OS version breakdown of the snap package is:

* 45% bionic
* 15% 19.10
* 10% focal
* 5% xenial
* 5% linux mint
* x% some other non-Ubuntu OSes

**Comment by sipa** [comment]
Thanks for the information everyone. This may end up being useful, but it seems there is a better solution that doesn't need this.

**Pull request closed without merging**
