### PR TITLE
[Doc] Fix link to installation script

### PR DESCRIPTION
**Pull request by ghost**
Missed in #11960 .

### CODE REVIEW

**Comment by MeshCollider** [comment]
Oh no, recursive issue number! I think you mean #11960 :P
LGTM, utACK https://github.com/bitcoin/bitcoin/commit/91ee7bfe080e6773c8b7e2de2acebd1d1dda79b9

**Comment by laudaa** [comment]
Oops, @MeshCollider. Fixed endless recursion. :P

**Comment by fanquake** [comment]
trivial ack 91ee7bf

**Comment by laanwj** [comment]
Included in #11984 (which does a larger update of this doc).

**Pull request closed without merging**
