### PR TITLE
[0.19] psbt: check that various indexes and amounts are within bounds

### PR DESCRIPTION
**Pull request by luke-jr**
Backport of #17156, non-trivial due to crossing the refactor in #17371

### CODE REVIEW

**Comment by fanquake** [comment]
Looks like this needs some [changes](https://travis-ci.org/bitcoin/bitcoin/builds/646637032):
```bash
wallet/test/psbt_wallet_tests.cpp: In member function ‘void psbt_wallet_tests::psbt_updater_test::test_method()’:
wallet/test/psbt_wallet_tests.cpp:77:48: error: ‘class CWallet’ has no member named ‘GetSigningProvider’
     const SigningProvider* provider = m_wallet.GetSigningProvider(ws1, sigdata);
                                                ^
make[2]: *** [wallet/test/test_test_bitcoin-psbt_wallet_tests.o] Error 1
```

**Comment by luke-jr** [comment]
Fixed (`SignPSBTInput`'s first argument is simply the wallet in 0.19)

**Comment by laanwj** [comment]
Backport looks good to me, backported test looks good  to me (and passes).
ACK f5fb7fca969cd43318384bec46bb7687b1a529fd

**Review by laanwj — APPROVED** [review]

**Comment by dgpv** [comment]
The checks correctly detect the case when the sum of amounts of inputs or outputs exceed MoneyRange, but as AFAICT the tests did not test for these conditions.

Here's two test PSBT that exhibit the conditions, please use them to add to the tests if you'd like:

sum of input amounts is out of valid range:
`cHNidP8BAJoCAAAAAvA00BFgAm6tp86RowwH6BMImQNL5zXUcTT97XoLGz0BAAAAAAD/////8DTQEWACbq2nzpGjDAfoEwiZA0vnNdRxNP3tegsbPQEBAAAAAP////8CAPkClQAAAAAWABQo3DTHwdFy0CCa+h6+bi7VJs3tcvztApUAAAAAFgAU9yTiAXuIvg0vjC19EAqBBuCGJNQAAAAAAAEBHwAAu8VkQwQAFgAU1EyyBQKdNymMjX5teAIUYQ+kIc0AAQEfAAC7xWRDBAAWABSSuJ3ylxfvTwYlM3tgxCBvDoOVXgAAAA==`

sum of output amounts is out of valid range:
`cHNidP8BAHECAAAAAfA00BFgAm6tp86RowwH6BMImQNL5zXUcTT97XoLGz0BAAAAAAD/////AgAAu8VkQwQAFgAUKNw0x8HRctAgmvoevm4u1SbN7XIAALvFZEMEABYAFPck4gF7iL4NL4wtfRAKgQbghiTUAAAAAAABAR+AsU8BAAAAABYAFJUDtxf2PHo641HEOBOAIvFMNTr2AAAA`

**Pull request merged**
