### PR TITLE
[test] Test abortrescan command

### PR DESCRIPTION
**Pull request by mess110**
This is an attempt of continuing the #10367 PR started by @kallewoof.

Got here through #11314

I really hope, I am not overstepping by submitting this PR, I tried to contact @kallewoof, but the user is not on slack. Since the PR was opened in May, I decided to try to help to improve it.

I addressed the nits mentioned and added the test for `False`

### CODE REVIEW

**Comment by instagibbs** [comment]
@mess110 Typically try to contact the user on IRC(or just ask on freenode #bitcoin-core-dev), people will help you find out.

**Comment by laanwj** [comment]
> I really hope, I am not overstepping by submitting this PR, I tried to contact @kallewoof, but the user is not on slack. Since the PR was opened in May, I decided to try to help to improve it.

No problem! you're always free to continue an issue if it has been abandoned for a while and you want to help it forward. Thanks! If @kallewoof wants he can cherry-pick this into  #10367, if not we can continue development here.

**Comment by kallewoof** [comment]
I've definitely not abandoned it, and not sure why you would get that impression. I'll review your commits and cherry pick if they look good later today.

**Comment by mess110** [comment]
Work continuing on the prev PR, closing this one

**Pull request closed without merging**
