### PR TITLE
[Tests] Fix a typo at assert_start_raises_init_error() and use specific exception for initialization error

### PR DESCRIPTION
**Pull request by romanz**
`self.wait_util_stopped()` should be `self.wait_until_stopped()`.

Also, use a specific Exception subclass for indicating node failure to start (instead of using `AssetionError` and an `except Exception` clause).

Following https://travis-ci.org/bitcoin/bitcoin/jobs/359066226#L2726 and depending on #12806 (which fixes the root cause of the Travis test failure).

### CODE REVIEW

**Review by randolf — CHANGES_REQUESTED** [review]
It appears that you're changing a lot more than just typing errors here.  Please update the description of this Pull Request to explain the changes.  Thanks.

**Comment by romanz** [comment]
> Please update the description of this Pull Request to explain the changes.

Done.

**Comment by jnewbery** [comment]
Nice change! Please rebase on master now that #12806 is merged, and update the PR title.

**Comment by MarcoFalke** [comment]
utACK 8394300859e69141fc62a5c120448f3311e5cc6a

**Comment by jnewbery** [comment]
Tested ACK 8394300859e69141fc62a5c120448f3311e5cc6a

**Review by randolf — APPROVED** [review]

**Pull request merged**
