### PR TITLE
tests: Test serialisation as part of deserialisation fuzzing. Test round-trip equality where possible.

### PR DESCRIPTION
**Pull request by practicalswift**
Test serialisation as part of deserialisation fuzzing. Test round-trip equality where possible.

### CODE REVIEW

**Comment by practicalswift** [comment]
@MarcoFalke If possible it would be nice to get the serialization fuzzing PR:s #17225 and #17051 in so that the currently under review PR #10785 ("Serialization improvements") can be easily fuzz tested :)

**Comment by practicalswift** [comment]
Rebased!

**Comment by practicalswift** [comment]
Rebased! :)

**Comment by practicalswift** [comment]
@MarcoFalke Can we move forward with this one? The current deserialization/serialization fuzzing is really lacking so this PR should be a clear improvement. I'm afraid bugs might sneak in unnecessarily if we don't improve our fuzz testing :)

**Comment by practicalswift** [comment]
Rebased! :)

**Comment by MarcoFalke** [comment]
ACK 709afb2a7de283a9188e7df51476830012e0a4e5 🍲

<details><summary>Show signature and timestamp</summary>

Signature:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK 709afb2a7de283a9188e7df51476830012e0a4e5 🍲
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEE+rVPoUahrI9sLGYTzit1aX5ppUgFAlwqrYAACgkQzit1aX5p
pUiRVAv9H5qQWzA2afXR5AbtSkKESM0ou1s8zx75A1qmnTCjkbR2c1zs9uuzqfil
oP5XQeUTdr7PjM4Y5P3X5dzdxPuUH0UZlGKRgnPHBWaUpUhGvUb6cD1QeZmE005V
Pc1iQoh7gE9e/4iMVm7zLb+dtJdvVKqCo7+SyOKIw5CUeu7sZWA2OrCzUNBxSUnY
l1/ZlX1EEvUM2rWxeCGRfbwCc6bCp+Yxww5GasYwWmMsUM9wPX3jOxRtzXUcfTTc
P4gSG0nJcIw5UhEWrIy4tf9gSjP8GMuclQDlr145zSLG3DMSey/tbM4IJSPX0/y6
LhS63+wCjqTi5ADAmAimyMnDmWU7032J6xHwRMrD8CF4dxlV52iIMWjBy1aXE96y
9NziQDsvFcpSExLW1uOeQPrTzKGjcT/GCwSxY2ubpgI2jPC8EseCp6nTNLN83fB9
/rot9gRkyu1Zj5ZYpLSdoJAzJIvTuZtM7vvhwhMJfA7KiGULxQw0x+Scxxg3UIOg
P6BI7HPL
=5M6D
-----END PGP SIGNATURE-----
```

[Timestamp of file with hash `0deb42754ef31a2d35b98c6ac2df5a98f164c3d19f4bd40e6255e095b85c4aec  -`](https://opentimestamps.org/info/?004f70656e54696d657374616d7073000050726f6f6600bf89e2e884e8929401080deb42754ef31a2d35b98c6ac2df5a98f164c3d19f4bd40e6255e095b85c4aecf010a14096dd44875bf6a1347f5d7c5ba42b08fff0108945b9a6c89f2136468ec74ad754601508f1045deea96cf008576fcb9329bcb2a90083dfe30d2ef90c8e2c2b68747470733a2f2f626f622e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267fff010f105deda3926dadaaec195e07d752dfb08f1045deea96cf008de4daef80f9663330083dfe30d2ef90c8e2e2d68747470733a2f2f616c6963652e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267fff010f70b6032c67c04ac6b688e98e35d3c8108f1045deea96cf0089612d81c884ad44a0083dfe30d2ef90c8e232268747470733a2f2f6274632e63616c656e6461722e636174616c6c6178792e636f6df010f739566097ebeebc4dc62a91ca8831fa08f1045deea96cf008345752ca46e5d7a80083dfe30d2ef90c8e292868747470733a2f2f66696e6e65792e63616c656e6461722e657465726e69747977616c6c2e636f6d)

</details>

**Pull request merged**
