### PR TITLE
Fix some benign races in timestamp logging

### PR DESCRIPTION
**Pull request by TheBlueMatt**

### CODE REVIEW

**Review by dcousens — APPROVED** [review]

**Comment by sipa** [comment]
utACK 8b22efb6f7c406951f33a04e84377fd16f02121c

**Comment by jonasschnelli** [comment]
utACK 8b22efb6f7c406951f33a04e84377fd16f02121c

**Comment by gmaxwell** [comment]
utACK.

**Comment by paveljanik** [comment]
utACK 8b22efb

**Pull request merged**
