### PR TITLE
test: Remove unused txmempool include from tests

### PR DESCRIPTION
**Pull request by maflcko**
Seems odd to include this heavy header in all tests despite it only being used in a few tests.

Can be reviewed with `--color-moved=dimmed-zebra --ignore-all-space`

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Follow-up to #26250

**Comment by hebasto** [comment]
Concept ACK.

**Comment by MarcoFalke** [comment]
I can reduce the fuzz compile time (user+kernel time) by 20% with a dirty `txmempool.h`. To reproduce:


```
( echo >> ./src/txmempool.h ) && /usr/bin/time --format '%U+%S (%e)' make -j $(nproc)

**Comment by brunoerg** [comment]
Concept ACK

**Comment by MarcoFalke** [comment]
Does anyone know why msvc is unable to link this?

**Comment by fanquake** [comment]
> Does anyone know why msvc is unable to link this?

@sipsorcery @hebasto any thoughts?

**Comment by hebasto** [comment]
> Does anyone know why msvc is unable to link this?

```diff
--- a/build_msvc/test_bitcoin-qt/test_bitcoin-qt.vcxproj
+++ b/build_msvc/test_bitcoin-qt/test_bitcoin-qt.vcxproj
@@ -54,6 +54,9 @@
     <ProjectReference Include="..\libbitcoin_zmq\libbitcoin_zmq.vcxproj">
       <Project>{792d487f-f14c-49fc-a9de-3fc150f31c3f}</Project>
     </ProjectReference>
+    <ProjectReference Include="..\libtest_util\libtest_util.vcxproj">
+      <Project>{1e065f03-3566-47d0-8fa9-daa72b084e7d}</Project>
+    </ProjectReference>
     <ProjectReference Include="..\libleveldb\libleveldb.vcxproj">
       <Project>{18430fef-6b61-4c53-b396-718e02850f1b}</Project>
     </ProjectReference>
```

**Review by aureleoules — COMMENTED** [review]
ACK fad7f2239c74a4db31b3023f2bcaf1f0852453f8

**Review by aureleoules — APPROVED** [review]
reACK 1c48dae76fc808bf7154aca976e7303364c56509
Thanks for the co-author.

**Review by hebasto — APPROVED** [review]
ACK 1c48dae76fc808bf7154aca976e7303364c56509, I have reviewed the code and it looks OK, I agree it can be merged.

**Review by w0xlt — APPROVED** [review]
ACK https://github.com/bitcoin/bitcoin/pull/26286/commits/1c48dae76fc808bf7154aca976e7303364c56509

**Pull request merged**
