### PR TITLE
[Trivial] Remove incorrect help message from gettxoutproof()

### PR DESCRIPTION
**Pull request by jnewbery**

### CODE REVIEW

**Comment by instagibbs** [comment]
no idea what that was supposed to mean. ACK.

**Comment by jnewbery** [comment]
I suspect the function was copy-pasted from `getrawtransaction()` above and this line wasn't removed.

**Comment by instagibbs** [comment]
If anything I think it should stress it doesn't include it. IIRC that tripped me up long ago.

**Comment by TheBlueMatt** [comment]
ACK. wut....

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/9711/commits/9949ebfa6a548260858df429f4d0e716e0a26065

**Comment by MarcoFalke** [comment]
ACK 9949ebf

**Pull request merged**
