### PR TITLE
Crystal clean make clean

### LINKED ISSUE #7501: 'make clean' doesn't clean all build results
After `make clean`, at least these files stay behind:
```
./src/libbitcoin_consensus.a
./src/libbitcoin_wallet.a
./src/libbitcoin_common.a
./src/libbitcoin_cli.a
./src/crypto/libbitcoin_crypto.a
./src/libbitcoin_util.a
./src/libbitcoin_server.a
./src/qt/libbitcoinqt.a
```
(there may be more, but I happened to notice these ones - leaving libraries behind would easily result in conflicts)

### PR DESCRIPTION
**Pull request by paveljanik**
Fixes #7501.

### CODE REVIEW

**Comment by paveljanik** [comment]
@theuni Please have a look please.

**Comment by laanwj** [comment]
utACK

**Comment by theuni** [comment]
@paveljanik Please don't use wildcards unless absolutely necessary, especially when deleting.

You should be able to simply:
```
CLEANFILES += $(EXTRA_LIBRARIES)
```
There's no need to clean qt manually, as it's not third-party.

**Comment by paveljanik** [comment]
@theuni But `make clean` doesn't clean in `qt` dir as @laanwj reported...
Will test $(EXTRA_LIBRARIES)...

**Comment by paveljanik** [comment]
Works much better! Thanks.

**Comment by theuni** [comment]
@paveljanik In Makefile.qt.in:
```
EXTRA_LIBRARIES += qt/libbitcoinqt.a
```
So that should take care of it.

**Comment by theuni** [comment]
Thanks, ut ack.

**Comment by laanwj** [comment]
BTW (no need to be in this PR) it would be nice to add a 'crystal clear' check to the test suite, could be interleaved with the current build process, just taking a snapshot of files here and there, then cleaning afterwards and checking:
```bash
./autogen.sh
git ls-files -o > $TMPDIR/after_autogen.txt
./configure
git ls-files -o > $TMPDIR/after_configure.txt
make 
...
make clean
git ls-files -o > $TMPDIR/after_clean.txt
make distclean
git ls-files -o > $TMPDIR/after_distclean.txt
# Check
diff $TMPDIR/after_configure.txt $TMPDIR/after_clean.txt
diff  $TMPDIR/after_distclean.txt $TMPDIR/after_autogen.txt
```

**Comment by laanwj** [comment]
Tested using this patch, and with the above steps. Only one snag:

- `make clean` leaves behind one file that is not present after configure: `src/obj/build.h`, but this is cleaned up by `make distclean`, so may be a false positive

ACK, it solves the issue I raise in #7501

**Comment by theuni** [comment]
@laanwj 'make distcheck' should do what you're after, i think? Been a while since I've tried it, I wouldn't be surprised if it's currently broken.

**Comment by laanwj** [comment]
@theuni Yes, that's probably what I've been emulating. I had no idea there was a built-in command for that.

**Pull request merged**
