### PR TITLE
[24.1] Bump version to 24.1rc2

### PR DESCRIPTION
**Pull request by fanquake**
rc1 (tagged > a month ago) was mostly a no-op, due to lack of binaries. While some are up now, [albeit at the wrong URL](https://bitcoincore.org/bin/bitcoin-24.1rc1/), there seems no point continuing the rc1 cycle, when we already have additional changes backported (#27474), and we've also received no bug reports/feedback from anyone who did test.

So bump the version, and cut an rc2.

### CODE REVIEW

**Review by hebasto — APPROVED** [review]
ACK 03a16a1da09f45721c799c719e48350dfe12ae88, I have reviewed the code and it looks OK.

> there seems no point continuing the rc1 cycle, when we already have additional changes backported

Agree.

**Comment by achow101** [comment]
ACK 03a16a1da09f45721c799c719e48350dfe12ae88

**Comment by gruve-p** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/27486/commits/03a16a1da09f45721c799c719e48350dfe12ae88

**Comment by Raen111** [comment]
Even

**Pull request merged**
