### PR TITLE
gitian, ci: Drop unneeded python3-dev package for macOS builds

### PR DESCRIPTION
**Pull request by hebasto**

### CODE REVIEW

**Comment by hebasto** [comment]
Gitian build:
```
Generating report
d35d3e43e4ff237aee47728a9ef38316fa14e7df75126ccc72a4e0e9a0817926  bitcoin-e4c0cada7911-osx-unsigned.dmg
8b99e4dd747280073bb8a8cc810ba7e2d254805b922444ae15a6e8e8bc767362  bitcoin-e4c0cada7911-osx-unsigned.tar.gz
c9a4e4be1c26c8d360f71a9f190ec962a0b39d75f7117ef117215682df0613cd  bitcoin-e4c0cada7911-osx64.tar.gz
f5121c9239fadf62501379443b5466763765426eaeb6f6181aff9ab3f0bf092f  src/bitcoin-e4c0cada7911.tar.gz
413eaa73853c982ac2e9e892783ba35af22507512994be7c4441c25da873199e  bitcoin-core-osx-22-res.yml
Done.
```

**Comment by MarcoFalke** [comment]
(removed test label because it is only secondary. the primary change is the build system)

**Review by fanquake — APPROVED** [review]
ACK e4c0cada791135e2d0a36638541c03feff0bd6bc - gitian builds match and I checked that this doesn't end up installed as a side-effect of another package.
```bash
Generating report
d35d3e43e4ff237aee47728a9ef38316fa14e7df75126ccc72a4e0e9a0817926  bitcoin-e4c0cada7911-osx-unsigned.dmg
8b99e4dd747280073bb8a8cc810ba7e2d254805b922444ae15a6e8e8bc767362  bitcoin-e4c0cada7911-osx-unsigned.tar.gz
c9a4e4be1c26c8d360f71a9f190ec962a0b39d75f7117ef117215682df0613cd  bitcoin-e4c0cada7911-osx64.tar.gz
f5121c9239fadf62501379443b5466763765426eaeb6f6181aff9ab3f0bf092f  src/bitcoin-e4c0cada7911.tar.gz
a83f378c3c42d9dcac8a3754d25ac4d0b01d196c65c5d812094d7a443a8fffda  bitcoin-core-osx-22-res.yml
Done.
```

```bash
publicsuffix/focal,now 20200303.0012-1 all [installed,automatic]
python3-distutils/focal-updates,focal-security,now 3.8.5-1~20.04.1 all [installed,automatic]
python3-lib2to3/focal-updates,focal-security,now 3.8.5-1~20.04.1 all [installed,automatic]
python3-minimal/focal,now 3.8.2-0ubuntu2 amd64 [installed,automatic]
python3-pkg-resources/focal,now 45.2.0-1 all [installed,automatic]
python3-setuptools/focal,now 45.2.0-1 all [installed]
python3.8-minimal/focal-updates,focal-security,now 3.8.5-1~20.04.2 amd64 [installed,automatic]
python3.8/focal-updates,focal-security,now 3.8.5-1~20.04.2 amd64 [installed,automatic]
python3/focal,now 3.8.2-0ubuntu2 amd64 [installed]
readline-common/focal,now 8.0-4 all [installed,automatic]
```

**Comment by laanwj** [comment]
Good catch.

**Pull request merged**
