### PR TITLE
scripted-diff: Bump copyright of files changed in 2019

### PR DESCRIPTION
**Pull request by maflcko**

### CODE REVIEW

**Comment by promag** [comment]
ACK aaaaad6ac95b402fe18d019d67897ced6b316ee0 🎉

**Comment by sanjaykdragon** [comment]
Nit: Will soon be changed to 2020?

**Comment by hebasto** [comment]
Related: #17691

**Comment by practicalswift** [comment]
ACK aaaaad6ac95b402fe18d019d67897ced6b316ee0

**Comment by fanquake** [comment]
ACK aaaaad6ac95b402fe18d019d67897ced6b316ee0 - going to merge this now because the year is over and conflicts are minimal. 

> Nit: Will soon be changed to 2020?

@sanjaykdragon No. This script is run once at the end of each year, and only modifies the headers in files that have been changed. Nothing needs to be changed to 2020 until the end of 2020.

**Pull request merged**
