### PR TITLE
refactor: convert string formatting to F-strings

### PR DESCRIPTION
**Pull request by iw4p**
All instances of string formatting have been converted to F-strings for increased readability and performance. Before that some of strings use `.format` and others use f-strings.

### CODE REVIEW

**Comment by brunoerg** [comment]
If this is just a refactor, why the `fix:` on commit message?

**Comment by iw4p** [comment]
> If this is just a refactor, why the `fix:` on the commit message ([8c600f7](https://github.com/bitcoin/bitcoin/commit/8c600f7f78d5aaf3577f6257b648727d72e32a06))?

Usually the most prefixes are `fix` and `feat`, but sometimes some repos and projects use other keywords like chore, ref, etc.
[reference](https://www.conventionalcommits.org/en/v1.0.0-beta.2/).
By the way I modified the commit message prefix.

**Comment by fanquake** [comment]
You should read our developer notes for an overview of what is relevant to our project. ref doesn't mean anything here. You could probably use refactor:.

**Comment by iw4p** [comment]
Sorry, I'm a newbie. I read [this](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#creating-the-pull-request) and only saw this tagging for PR title. Now I changed it to `refactor`.

**Review by stickies-v — COMMENTED** [review]
Concept NACK. Thank you for looking into this, and I support increased f-string usage, but imo this should be done organically whenever these lines are touched for other reasons (or with a scripted-diff across the code base, and enforcing it with linter, should there be support to do that). In its current form, this is not worth the review time imo.

**Comment by iw4p** [comment]
Hi,
Thank you. 
I touched this file to optimize it like using built-in python request library instead of curl and decreasing the request numbers, and one more PR. That's why I decided to go for converting strings to f-string.

**Comment by glozow** [comment]
Thanks for your interest in contributing! CONTRIBUTING.md and developer-notes.md contain good resources for beginners. As we have 300+ pulls open right now, closing this test refactor to focus review attention on the others (see https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#refactoring)

**Pull request closed without merging**
