### PR TITLE
Add CJDNS network to -addrinfo and -netinfo

### PR DESCRIPTION
**Pull request by jonatack**
Follow-up to #23077 and #23324.
```
$ ./src/bitcoin-cli -addrinfo
{
  "addresses_known": {
    "ipv4": 47782,
    "ipv6": 10307,
    "onion": 8030,
    "i2p": 41,
    "cjdns": 1,
    "total": 66161
  }
}
$ ./src/bitcoin-cli -netinfo 
Bitcoin Core client v22.99.0-deb6223d4c55 - server 70016/Satoshi:22.99.0(jon)/

        ipv4    ipv6   onion     i2p   cjdns   total   block  manual
in         0       5      12       5       1      23
out        2       2       9       5       2      20       2      10
total      2       7      21      10       3      43
```
```
$ ./src/bitcoin-cli -netinfo 1
```

Screenshot from 2021-10-10 12-01-58

### CODE REVIEW

**Comment by laanwj** [comment]
Concept ACK

**Comment by dunxen** [comment]
Concept ACK

**Comment by practicalswift** [comment]
Concept ACK

Thanks for improving `-addrinfo` and `-netinfo`.

**Comment by prayank23** [comment]
I am still [not sure](https://github.com/bitcoin/bitcoin/pull/23077#issuecomment-926349000) about CJDNS and have no opinions on https://github.com/bitcoin/bitcoin/pull/23077

However, looking at the support from others it will most likely get merged so this PR makes sense.

Concept ACK

**Comment by laanwj** [comment]
Needs rebase (and can go out of draft) after #23175.

**Comment by prusnak** [comment]
> Needs rebase (and can go out of draft) now that #23175 is merged.

laanwj meant https://github.com/bitcoin/bitcoin/pull/23077 (#23175 is this PR)

**Comment by jonatack** [comment]
Thanks! Rebased and updated (simplified) following the merge of #23324, and bringing out of draft now that #23077 has been merged.

**Review by prusnak — APPROVED** [review]
utACK

**Comment by laanwj** [comment]
Code review ACK 7b6528746acf9c915d7157bb860ec899b58dded7

**Comment by prusnak** [comment]
This PR has been merged into master via https://github.com/bitcoin/bitcoin/commit/caf8b26b52bf38289899dfa1ca15aa9c9d140971

**Comment by sipa** [comment]
Closing as merged.

**Pull request closed without merging**
