### PR TITLE
test: Extend stale_tip_peer_management test

### PR DESCRIPTION
**Pull request by maflcko**
Add coverage for the case where a peer is protected when it pretends to have a block.

Also, add some `ASSERT_DEBUG_LOG` to document the tests for the reader.

### CODE REVIEW

**Comment by jonatack** [comment]
Concept ACK

**Comment by MarcoFalke** [comment]
Rebased

**Comment by jonatack** [comment]
Concept ACK

**Comment by achow101** [comment]
Are you still working on this?

**Comment by achow101** [comment]
Closing this as it has not had any activity in a while. If you are interested in continuing work on this, please leave a comment so that it can be reopened.

**Comment by MarcoFalke** [comment]
Ok, I'll rebase

**Review by mzumsande — COMMENTED** [review]
Concept ACK.

I wonder if it's possible (and worth it) to tweak the test such that it would have caught #26172.
Sending the block via p2p  like this test does also updates `m_last_block_announcement`, however I think we'd need to add a getter to check this directly.
Or maybe it could work to have 5 nodes send new block headers via p2p instead of 1, such that only `MAX_OUTBOUND_PEERS_TO_PROTECT_FROM_DISCONNECT=4` of them get protected, and the fifth also gets saved from disconnect via `m_last_block_announcement`.

**Comment by LarryRuane** [comment]
> I wonder if it's possible (and worth it) to tweak the test such that it would have caught #26172. 

I have a [test](https://github.com/LarryRuane/bitcoin/commit/3f847e4c4e5f89f812407eef39d421f45b0eea02) for that but haven't made the PR yet (I'll do that this week). I'll compare what I have to this PR since there's likely some overlap.

**Comment by theuni** [comment]
Ping @MarcoFalke, apparently :)

**Pull request closed without merging**
