### PR TITLE
docs: fix typo

### PR DESCRIPTION
**Pull request by vuittont60**

### CODE REVIEW

**Comment by hebasto** [comment]
Why this typo is not caught by the linter?

See: https://github.com/bitcoin/bitcoin/pull/28605.

**Comment by vuittont60** [comment]
Yes, linter is the requirement for branch-off.
And we can see, not all typos can be caught by the linter.
And I caught the fish that escaped the net.

**Review by hebasto — APPROVED** [review]
ACK 57131bfa3cfd9e5826b5c557aba8aa03bf41f833, the `codespell` is powerless to catch this typo.

**Review by jarolrod — COMMENTED** [review]
ACK 57131bfa3cfd9e5826b5c557aba8aa03bf41f833

**Pull request merged**
