### PR TITLE
LegacyScriptPubKeyMan code cleanups

### PR DESCRIPTION
**Pull request by ryanofsky**
This PR implements suggested code cleanups from https://github.com/bitcoin/bitcoin/pull/17260 review comments

### CODE REVIEW

**Comment by MarcoFalke** [comment]
In commit aa0e6d8ab1761d6bbc729614663da7ad7fb67dac:

My comment was just an example. It is generally not clear to me when this nullptr check should be done. Most of the other methods don't do it either. E.g. `CWallet::LoadWallet`, `CWallet::GetNewChangeDestination`, `CWallet::CreateWalletFromFile`, ...

**Comment by ryanofsky** [comment]
> It is generally not clear to me when this nullptr check should be done.

Checking for null key managers *should* always be done, and various commits in #17261 add more null checks. But I don't think it makes a big difference if we add null checks now (there should only be a small handful) or wait for changes from #17261. Just let me know what you prefer: dropping this commit, keeping it, or expanding it to cover `LoadWallet`, etc.

Note `m_spk_man` will never actually _be_ null until commit "Refactor: Allow LegacyScriptPubKeyMan to be null" 66d2e2206267695f2fc722481252f63f7c74636a from #17261 

Later after that, `m_spk_man` is replaced with lists of key managers in commit "Box the wallet: Add multiple keyman maps and loops" 00b7802570970d6328bc566b9978f93be0f18f66 from #17261 and all the `if (auto spk_man = m_spk_man.get())` blocks turn into `for` loops.

**Comment by Sjors** [comment]
> It is generally not clear to me when this nullptr check should be done.

I like how `GetLegacyScriptPubKeyMan helper` returns a reference instead of a pointer.

> Just let me know what you prefer: dropping this commit, keeping it, or expanding it to cover LoadWallet, etc.

I prefer expanding it.

**Comment by MarcoFalke** [comment]
Either drop it or expand it. It shouldn't matter

**Comment by ryanofsky** [comment]
re: https://github.com/bitcoin/bitcoin/pull/17300#issuecomment-547535074 from Sjors

> I prefer expanding it.

re: https://github.com/bitcoin/bitcoin/pull/17300#issuecomment-547541329 from MarcoFalke 

> Either drop it or expand it. It shouldn't matter

I looked into expanding this but some of the changes in places like `CreateWallet` and `AddToWalletIfInvolvingMe` are awkward and less-obvious than I'd want to make in a bulk commit. I think the existing individual commits in #17261 which are broken down by functionality add the null checking in a more understandable way than could be done here. So I just dropped commit aa0e6d8ab1761d6bbc729614663da7ad7fb67dac. Another advantage of not expanding this is it will keep #17300 from conflicting with #17261 too much.

**Comment by MarcoFalke** [comment]
Approach ACK, haven't looked at the diff

**Comment by Sjors** [comment]
ACK 53fe0b70adeffe4cb94e6fa18a9abbdf674a2cd0

**Comment by achow101** [comment]
ACK 53fe0b70adeffe4cb94e6fa18a9abbdf674a2cd0

**Comment by MarcoFalke** [comment]
ACK 53fe0b70adeffe4cb94e6fa18a9abbdf674a2cd0

<details><summary>Show signature and timestamp</summary>

Signature:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK 53fe0b70adeffe4cb94e6fa18a9abbdf674a2cd0
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEE+rVPoUahrI9sLGYTzit1aX5ppUgFAlwqrYAACgkQzit1aX5p
pUg83wwAgwAEPoOoUUuaq/slVcJkmBK2g/zAdTLvLCsBV0PNQiI5v9QN1DcAbFgW
vTWN0+u2VaehZGhJoqw5riAOdXrY+MQrcn01Ljx4b49550F1w0Dbf4BLu41yQ/qj
56sZzYxSyZ0x5E6sogazCOhwKWZ6KEyht3aZR2YPx7y8Gp1BNF53Whmb0LVSsm9C
xIKg3Z+/aP3FzBLL3VD39lhxSZjjw0yxTqlZPNgEcHK7xQvn7uf+VkhIVoXdNcSf
kPgljx5KscWrsMAP/i8NViZ8k86n5QRlcO/iQIZbIyWk2wywzQpq/SBf8uxF+V9Y
SNiEnTwSnvLl4IyLwLcHio58S7+PXgQtV3L1wgGDhsXD/ZNRuiwAnshrnlECPMe+
3ZgE82cPznKEj/b22lo/Jyt/XMlLkrcEiuFDw9Z+eqMO1c/+6UxGoPX/E/YFPv0M
GPK3fen95qdbmwknlSoALUUbnJQvS5QkAwWug0Bm6C+zMy5eBwp2l84bOT69CMa7
IYipWyK3
=8EPP
-----END PGP SIGNATURE-----
```

[Timestamp of file with hash `f41dcbac528b83e896b46a19b8757a3b59f8e6f343c9e7f4830f5b6cb65d028e  -`](https://opentimestamps.org/info/?004f70656e54696d657374616d7073000050726f6f6600bf89e2e884e892940108f41dcbac528b83e896b46a19b8757a3b59f8e6f343c9e7f4830f5b6cb65d028ef010bdc7353e0909247c57f2d951566d34e708fff01053a38ec0efb5763623fefc9311ce871708f1045dbb2a8ff008ad25617f968959590083dfe30d2ef90c8e232268747470733a2f2f6274632e63616c656e6461722e636174616c6c6178792e636f6dfff0105b70b73be6344a9140365be47a739f2408f1045dbb2a8ff0088aae2227d3d30f400083dfe30d2ef90c8e2e2d68747470733a2f2f616c6963652e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267fff0109de057fc9dab42a322f73512889ef74d08f1045dbb2a8ff00870487c740594a4b80083dfe30d2ef90c8e2c2b68747470733a2f2f626f622e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267f010a500e39b7af1e58039626537d5d55aef08f1045dbb2a8ff0082d02c69bacfb00fb0083dfe30d2ef90c8e292868747470733a2f2f66696e6e65792e63616c656e6461722e657465726e69747977616c6c2e636f6d)

</details>

**Comment by laanwj** [comment]
This introduces 5 "warning: unused variable 'spk_man' [-Wunused-variable]"  warnings in rpcdump.

Probably harmless: though if the function should be called if the return value is not used (so it's purely side effect) it might be good to document that so people don't do the obvious thing.

**Comment by ryanofsky** [comment]
> This introduces 5 "warning: unused variable 'spk_man' [-Wunused-variable]" warnings in rpcdump.
> 
> Probably harmless: though if the function should be called if the return value is not used (so it's purely side effect) it might be good to document that so people don't do the obvious thing.

Good catch. I'm planning to make another cleanup PR after #17304 (which could be close to ready for merge) for more unaddressed review comments. I could fix the warning in that PR, or open a more limited PR sooner if the warnings are too annoying. Some of the unused `spk_man` variables in the warnings are used later in 07e0c2369353623a289b5b92da1f13f6d2be1ace from #17261, but it's unclear if these locks are actually necessary, and in any case it's confusing to have these unused variables. It might also help to rename `GetLegacyScriptPubKeyMan` to `EnsureLegacyScriptPubKeyMan` to be clear about what the function is doing when the return value is unused.

**Pull request merged**
