### PR TITLE
trivial: Fix typo – "Ubutntu" → "Ubuntu"

### PR DESCRIPTION
**Pull request by practicalswift**
Fix typo – "Ubutntu" → "Ubuntu".

### CODE REVIEW

**Comment by promag** [comment]
ACK.

**Comment by laanwj** [comment]
Eh yes ACK

**Comment by TheBlueMatt** [comment]
In the future, can we avoid unicode in commit messages/PR titles? Would be nice to not get unicode replacement charachters all over my terminal in git log.

**Comment by practicalswift** [comment]
@TheBlueMatt Sure! :-)

**Pull request merged**
