### PR TITLE
Silence false positive GCC warning in wallet/rpcwallet.cpp

### LINKED ISSUE #20381: "may be used uninitialized" warning in wallet/rpcwallet.cpp
Have this warning while building current master (0bd4929cd00e91bf4137f43b097cd62f72f503e4) on one test machine.
```
wallet/rpcwallet.cpp: In function 'rescanblockchain()::<lambda(const RPCHelpMan&, const JSONRPCRequest&)>':
wallet/rpcwallet.cpp:3596:19: warning: '*((void*)& stop_height +4)' may be used uninitialized in this function [-Wmaybe-uninitialized]
 3596 |     Optional<int> stop_height;
      |                   ^~~~~~~~~~~
```
```
$ gcc --version
gcc (Gentoo 9.2.0-r2 p3) 9.2.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ uname -a
Linux red-box 4.19.72-gentoo #2 SMP Sun Sep 22 03:00:01 EEST 2019 x86_64 Intel(R) Pentium(R) CPU N3710 @ 1.60GHz GenuineIntel GNU/Linux
```

### PR DESCRIPTION
**Pull request by kristapsk**
Resolves #20381.

### CODE REVIEW

**Comment by jonatack** [comment]
While here, it looks like the "#include <optional.h>" header should be added.

**Comment by jnewbery** [comment]
utACK 049feabf289ace817a3da62fe84942d0200b8f0b

No harm in doing this now, although I expect we'll swap our usage of boost::optional for std::optional very soon after moving to c++17.

**Review by promag — COMMENTED** [review]
ACK 29c66ace5c777b56cd9e19756a1ab0801d15a5ae.

nit, could squash.

**Comment by kristapsk** [comment]
@promag , could, but, OTOH, they are two different (although related) changes.

**Comment by practicalswift** [comment]
ACK 049feabf289ace817a3da62fe84942d0200b8f0b: diagnostics signal to noise is increased by getting rid of false positives

**Comment by jnewbery** [comment]
@promag did you mean to ACK the head commit 049feabf289ace817a3da62fe84942d0200b8f0b?

**Comment by hebasto** [comment]
Similar issues have a long history in the repo:
- #15292
- #18052
- #18198

Particularly, this warning was [discussed](https://github.com/bitcoin/bitcoin/pull/17954#discussion_r395695797) in #17954.

Considering that switching to C++17 is around the corner, and `std::make_optional` has no known drawbacks, I'd suggest to postpone addressing compiler warnings until using `std::make_optional`.

**Comment by elichai** [comment]
I'm with @hebasto 
Concept NACK, my reasoning are: https://github.com/bitcoin/bitcoin/issues/18198#issuecomment-602050441
I'd prefer silencing those warnings until we can switch to `std::optional`

**Comment by MarcoFalke** [comment]
Going to merge this, otherwise we'll have to close a flood of issues complaining about the warning. I'll make sure to remove the workarounds after branch-off, as neither the workarounds nor MakeOptional is needed with C++17

**Review by hebasto — APPROVED** [review]
ACK 049feabf289ace817a3da62fe84942d0200b8f0b, I have reviewed the code and it looks OK, I agree it can be merged.

**Pull request merged**
