### PR TITLE
travis: Run unit and functional tests on native arm

### PR DESCRIPTION
**Pull request by maflcko**
This keeps the cross-compilation to make it easy to run the ci on non-arm hardware. To run this locally in qemu-user as it used to be, just `export QEMU_USER_CMD="qemu-arm -L /usr/arm-linux-gnueabihf/"`.

### CODE REVIEW

**Comment by practicalswift** [comment]
Concept ACK

Diversity in testing is good

**Comment by MarcoFalke** [comment]
Even though it shouldn't fail, this fails with

```
/bin/bash: /home/travis/build/bitcoin/bitcoin/depends/arm-linux-gnueabihf/share/../native/bin/uic: cannot execute binary file: Exec format error
```

I might try to debug this locally some day...

**Comment by laanwj** [comment]
Concept ACK

I think the error has to do with using the output of cross-compilation; the "native" uic will be x86-64, the expected build platform.

**Comment by MarcoFalke** [comment]
Oh, so we can't cross compile on arm64 to other arches?

**Comment by laanwj** [comment]
> Oh, so we can't cross compile on arm64 to other arches?

There is no conceptual reason why not, but maybe not with how depends are set up right now. Not sure.

But I think I misunderstand what is happening. I thought the cross compile was from x86 to armhf. Is it cross-compiling from arm64 to armhf?

What is the "native" platform here, and what is the target platform?

**Comment by MarcoFalke** [comment]
travis offers arm64 (== aarch64 ) machines, so the cross compilation is on a arm64 host to an arm32 guest

**Comment by laanwj** [comment]
So we're sure it's not using cached `arm-linux-gnueabihf` depends that have been built on x86-64? I can't think of any explanation why the native tools like `uic` (which are by definition not cross-compiled, but built with the native C++ compiler, so that they can be part of the build processs) would be the wrong architecture.

**Comment by MarcoFalke** [comment]
Good point. The depends cache is not invalidated when the compiler changes

**Comment by laanwj** [comment]
Looks like it finishes the build now, but the testing stage cannot find the binaries… strange

**Comment by laanwj** [comment]
I think I get the reason for this: you are executing ARM32 executables on ARM64 without symbolic linker and glibc installed. Missing the ELF interpreter will give the same "not found" error as missing the executable itself.

I think this is package `libc6:armhf`.

**Comment by MarcoFalke** [comment]
Added `libc6-armhf-armel-cross` to the install packages

**Comment by laanwj** [comment]
I think that's the old package naming. It should work though.

> bionic (18.04LTS) (devel): Dummy package to get libc6:armhf installed [universe]
> 2.27-3ubuntu1cross1: all

**Comment by MarcoFalke** [comment]
It fails locally and on travis:

```
$ sudo apt install libc6-dev-armhf-armel-cross && make check -j 2
Reading package lists... Done
Building dependency tree
Reading state information... Done
libc6-dev-armhf-armel-cross is already the newest version (2.27-3ubuntu1cross1.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Making check in src
make[1]: Entering directory '/home/ubuntu/bitcoin-core/src'
make[2]: Entering directory '/home/ubuntu/bitcoin-core/src'
make[3]: Entering directory '/home/ubuntu/bitcoin-core'
make[3]: Leaving directory '/home/ubuntu/bitcoin-core'
make  check-TESTS check-local
make[3]: Entering directory '/home/ubuntu/bitcoin-core/src'
Running tests: arith_uint256_tests from test/arith_uint256_tests.cpp
/bin/bash: test/test_bitcoin: No such file or directory

**Comment by laanwj** [comment]
What is the output of `readelf -a test/test_bitcoin | grep interpreter`? does that file exist?

**Comment by MarcoFalke** [comment]
```
$ readelf -a src/test/test_bitcoin | grep interpreter
      [Requesting program interpreter: /lib/ld-linux-armhf.so.3]
0x59004c <_ZNK5boost7runtime17value_interpreterIbLb0EE9interpretENS_9unit_test13basic_cstringIKcEES6_>: @0x9c7a78
0x5957bc <_ZNK5boost7runtime17value_interpreterIjLb0EE9interpretENS_9unit_test13basic_cstringIKcEES6_>: @0x9c807c
0x595dc0 <_ZNK5boost7runtime17value_interpreterImLb0EE9interpretENS_9unit_test13basic_cstringIKcEES6_>: @0x9c8188
 29187: 00000000     0 FILE    LOCAL  DEFAULT  ABS interpreter.cpp


$ ll /lib/ld-linux-armhf.so.3
ls: cannot access '/lib/ld-linux-armhf.so.3': No such file or directory

```

```
$ ll /usr/arm-linux-gnueabihf/lib/ld-linux-armhf.so.3 
lrwxrwxrwx 1 root root 10 Sep 17  2018 /usr/arm-linux-gnueabihf/lib/ld-linux-armhf.so.3 -> ld-2.27.so*
```

**Comment by laanwj** [comment]
It really needs to be in `/lib` for multi-arch to work.

Can you try:
```
dpkg --add-architecture armhf
apt get update
apt-get install libc6:armhf
```

**Comment by MarcoFalke** [comment]
I feel dumb for not trying that, but then I remember that it didn't work locally:


```
# dpkg --add-architecture armhf
root@729a87425702:/# apt update
Hit:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Ign:4 http://security.ubuntu.com/ubuntu bionic-security/main armhf Packages    
Hit:5 http://archive.ubuntu.com/ubuntu bionic-backports InRelease              
Ign:6 http://security.ubuntu.com/ubuntu bionic-security/restricted armhf Packages
Ign:7 http://archive.ubuntu.com/ubuntu bionic/multiverse armhf Packages                                                            
Ign:8 http://security.ubuntu.com/ubuntu bionic-security/multiverse armhf Packages                                                  
Ign:9 http://archive.ubuntu.com/ubuntu bionic/main armhf Packages                                                                  
Ign:10 http://security.ubuntu.com/ubuntu bionic-security/universe armhf Packages                                                   
Ign:11 http://archive.ubuntu.com/ubuntu bionic/universe armhf Packages                                   
Ign:4 http://security.ubuntu.com/ubuntu bionic-security/main armhf Packages                              
Ign:12 http://archive.ubuntu.com/ubuntu bionic/restricted armhf Packages    
Ign:6 http://security.ubuntu.com/ubuntu bionic-security/restricted armhf Packages
Ign:7 http://archive.ubuntu.com/ubuntu bionic/multiverse armhf Packages
Ign:8 http://security.ubuntu.com/ubuntu bionic-security/multiverse armhf Packages
Ign:13 http://archive.ubuntu.com/ubuntu bionic-updates/universe armhf Packages
Ign:10 http://security.ubuntu.com/ubuntu bionic-security/universe armhf Packages
Ign:14 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse armhf Packages
Ign:4 http://security.ubuntu.com/ubuntu bionic-security/main armhf Packages
Ign:15 http://archive.ubuntu.com/ubuntu bionic-updates/main armhf Packages
Ign:6 http://security.ubuntu.com/ubuntu bionic-security/restricted armhf Packages
Ign:16 http://archive.ubuntu.com/ubuntu bionic-updates/restricted armhf Packages
Ign:8 http://security.ubuntu.com/ubuntu bionic-security/multiverse armhf Packages
Ign:9 http://archive.ubuntu.com/ubuntu bionic/main armhf Packages
Ign:10 http://security.ubuntu.com/ubuntu bionic-security/universe armhf Packages
Ign:17 http://archive.ubuntu.com/ubuntu bionic-backports/main armhf Packages
Err:4 http://security.ubuntu.com/ubuntu bionic-security/main armhf Packages
  404  Not Found [IP: 91.189.88.24 80]
Ign:18 http://archive.ubuntu.com/ubuntu bionic-backports/universe armhf Packages
Ign:6 http://security.ubuntu.com/ubuntu bionic-security/restricted armhf Packages
Ign:11 http://archive.ubuntu.com/ubuntu bionic/universe armhf Packages      
Ign:8 http://security.ubuntu.com/ubuntu bionic-security/multiverse armhf Packages
Ign:12 http://archive.ubuntu.com/ubuntu bionic/restricted armhf Packages    
Ign:10 http://security.ubuntu.com/ubuntu bionic-security/universe armhf Packages
Ign:7 http://archive.ubuntu.com/ubuntu bionic/multiverse armhf Packages     
Ign:13 http://archive.ubuntu.com/ubuntu bionic-updates/universe armhf Packages
Ign:14 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse armhf Packages
Ign:15 http://archive.ubuntu.com/ubuntu bionic-updates/main armhf Packages
Ign:16 http://archive.ubuntu.com/ubuntu bionic-updates/restricted armhf Packages
Ign:9 http://archive.ubuntu.com/ubuntu bionic/main armhf Packages
Ign:17 http://archive.ubuntu.com/ubuntu bionic-backports/main armhf Packages
Ign:18 http://archive.ubuntu.com/ubuntu bionic-backports/universe armhf Packages
Ign:11 http://archive.ubuntu.com/ubuntu bionic/universe armhf Packages
Ign:12 http://archive.ubuntu.com/ubuntu bionic/restricted armhf Packages
Err:7 http://archive.ubuntu.com/ubuntu bionic/multiverse armhf Packages
  404  Not Found [IP: 91.189.88.149 80]
Ign:13 http://archive.ubuntu.com/ubuntu bionic-updates/universe armhf Packages
Ign:14 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse armhf Packages
Ign:15 http://archive.ubuntu.com/ubuntu bionic-updates/main armhf Packages
Ign:16 http://archive.ubuntu.com/ubuntu bionic-updates/restricted armhf Packages
Ign:9 http://archive.ubuntu.com/ubuntu bionic/main armhf Packages
Ign:17 http://archive.ubuntu.com/ubuntu bionic-backports/main armhf Packages
Ign:18 http://archive.ubuntu.com/ubuntu bionic-backports/universe armhf Packages
Ign:11 http://archive.ubuntu.com/ubuntu bionic/universe armhf Packages
Ign:12 http://archive.ubuntu.com/ubuntu bionic/restricted armhf Packages
Err:13 http://archive.ubuntu.com/ubuntu bionic-updates/universe armhf Packages
  404  Not Found [IP: 91.189.88.149 80]
Ign:14 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse armhf Packages
Ign:15 http://archive.ubuntu.com/ubuntu bionic-updates/main armhf Packages
Ign:16 http://archive.ubuntu.com/ubuntu bionic-updates/restricted armhf Packages
Err:17 http://archive.ubuntu.com/ubuntu bionic-backports/main armhf Packages
  404  Not Found [IP: 91.189.88.149 80]
Ign:18 http://archive.ubuntu.com/ubuntu bionic-backports/universe armhf Packages
Reading package lists... Done
E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/bionic-security/main/binary-armhf/Packages  404  Not Found [IP: 91.189.88.24 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic/multiverse/binary-armhf/Packages  404  Not Found [IP: 91.189.88.149 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-updates/universe/binary-armhf/Packages  404  Not Found [IP: 91.189.88.149 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-backports/main/binary-armhf/Packages  404  Not Found [IP: 91.189.88.149 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
root@729a87425702:/# apt-get install libc6:armhf
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libc6:armhf

**Comment by MarcoFalke** [comment]
Oh, I was running the `dpkg --add-architecture armhf` on x86_64 locally. Does that make it not work?

Either way. Looks like on travis and the odroid c2 it worked. Let's hope it runs the tests now :pray:

**Comment by laanwj** [comment]
> Oh, I was running the dpkg --add-architecture armhf on x86_64 locally. Does that make it not work?

I'm not sure. I think it *in principle* it should be possible to install armhf as additional architecture on x86, using qemu, but it's a much less-traveled path than armhf on aarch64. You might have to mess around with apt configuration.

**Comment by MarcoFalke** [comment]
@laanwj Thanks for the help. Passes locally and on travis. This is ready for review now!

**Comment by laanwj** [comment]
Thanks for seeing this through!

LGTM ACK facc0da63a8fa4bd6fc2782cbe92eb9f920f2256

**Comment by practicalswift** [comment]
ACK facc0da63a8fa4bd6fc2782cbe92eb9f920f2256 -- diff looks correct and Travis seems happy

Thanks for working on this!

**Pull request merged**
