### PR TITLE
[22.x] rc2 backports

### PR DESCRIPTION
**Pull request by fanquake**
Currently backports #22511. We can collect up further backports and merge prior to rc2.

### CODE REVIEW

**Comment by achow101** [comment]
ACK cd57bb1a6626e0820ae2456cd3b71c140cf83403

Verified that the diffs match.

**Comment by dongcarl** [comment]
Building cd57bb1a66 right now and checking the codesigning workflow with self-signed certs.

**Comment by fanquake** [comment]
Guix builds:
```bash
bash-5.1# find guix-build-$(git rev-parse --short=12 HEAD)/output/ -type f -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum
d0f9039e14c2c61912fa961fb4d8a048c5ccc23e5673880df344ecc23910325f  guix-build-cd57bb1a6626/output/aarch64-linux-gnu/SHA256SUMS.part
adbd1af831ce5dd319de5859c5df36dcd3899a83e76f4be0d71d674ca4f086a6  guix-build-cd57bb1a6626/output/aarch64-linux-gnu/bitcoin-cd57bb1a6626-aarch64-linux-gnu-debug.tar.gz
83aac881d256ceae2dc4771f4cff800c75592c0610ebce2ad1e3a0b7a98cb17f  guix-build-cd57bb1a6626/output/aarch64-linux-gnu/bitcoin-cd57bb1a6626-aarch64-linux-gnu.tar.gz
8c4b1313f6d4b62590e33eb79581a0a0694c59b067e11e5375d952cf88749906  guix-build-cd57bb1a6626/output/arm-linux-gnueabihf/SHA256SUMS.part
7ceb281370f61df3078b09cf80674c12f24815aeba0c1bc148ade9d63ec8263b  guix-build-cd57bb1a6626/output/arm-linux-gnueabihf/bitcoin-cd57bb1a6626-arm-linux-gnueabihf-debug.tar.gz
941f268fcd0882bffdb9fa8f02b7c2dfbb2b60695336ce8a2980befe5a2dbaad  guix-build-cd57bb1a6626/output/arm-linux-gnueabihf/bitcoin-cd57bb1a6626-arm-linux-gnueabihf.tar.gz
58ec80628160a50663f4481953baac812793f0df0b505040fd4d0af01672173a  guix-build-cd57bb1a6626/output/dist-archive/bitcoin-cd57bb1a6626.tar.gz
fc1336666f725eec0c2f1221c54f7b8900004f351937b920b1cb4f53dfb97d7e  guix-build-cd57bb1a6626/output/powerpc64-linux-gnu/SHA256SUMS.part
d5444007c3a3c85304f9176bd47f74bd2c0d75fc7ae6c577429f5c25cdd79e80  guix-build-cd57bb1a6626/output/powerpc64-linux-gnu/bitcoin-cd57bb1a6626-powerpc64-linux-gnu-debug.tar.gz
27ac3784de27e6db98f46cf6200f4fccdb1161229bfa6d9cbcbcb75662da9a9b  guix-build-cd57bb1a6626/output/powerpc64-linux-gnu/bitcoin-cd57bb1a6626-powerpc64-linux-gnu.tar.gz
9856f57fe35ce727ce125cd8faefcd4710652599c88b87eb118a601685157059  guix-build-cd57bb1a6626/output/powerpc64le-linux-gnu/SHA256SUMS.part
d00163bf2ad874d5d76a53b470857181493bb54c11cf64c6e79a7ef97e72b24c  guix-build-cd57bb1a6626/output/powerpc64le-linux-gnu/bitcoin-cd57bb1a6626-powerpc64le-linux-gnu-debug.tar.gz
8ee09b7bb1482640dc91bff595fc8cbcdedcf6eea746b98e7002e92d3669cc76  guix-build-cd57bb1a6626/output/powerpc64le-linux-gnu/bitcoin-cd57bb1a6626-powerpc64le-linux-gnu.tar.gz
bb06ed9128bce843326cce59b7dc243be7d798c5b0434ee506332277c74997a6  guix-build-cd57bb1a6626/output/riscv64-linux-gnu/SHA256SUMS.part
369aba2fcc6523724faf216e711b6d2dea737515475bac3c757c8dfbde5ad4c0  guix-build-cd57bb1a6626/output/riscv64-linux-gnu/bitcoin-cd57bb1a6626-riscv64-linux-gnu-debug.tar.gz
730d411cd605caecad1581660783e6f5046f9423ec7d30bbe4f99e061e049342  guix-build-cd57bb1a6626/output/riscv64-linux-gnu/bitcoin-cd57bb1a6626-riscv64-linux-gnu.tar.gz
25e0f763eef908ee3ef01cf32badba940961cc8e7b9ef987ed2ee909e2d2d3e4  guix-build-cd57bb1a6626/output/x86_64-apple-darwin18/SHA256SUMS.part
360030cce3ded4c74bffd9fd3744b88d7238f71d2f59b4ec4aaa61d798aaa927  guix-build-cd57bb1a6626/output/x86_64-apple-darwin18/bitcoin-cd57bb1a6626-osx-unsigned.dmg
8ca84dc139801158a07de11409870fde942385b39586194edfbaefa5adb837c9  guix-build-cd57bb1a6626/output/x86_64-apple-darwin18/bitcoin-cd57bb1a6626-osx-unsigned.tar.gz
764333eb47ccc1758fe81aace15c9ae0d59f7491c0a333146c9c2651754766d7  guix-build-cd57bb1a6626/output/x86_64-apple-darwin18/bitcoin-cd57bb1a6626-osx64.tar.gz
dea7484c8f1659e2f4fe3c0f1a6ae63191d25b3892c41d5f88f0c7145e19bf20  guix-build-cd57bb1a6626/output/x86_64-linux-gnu/SHA256SUMS.part
638ecdac8aa7da8b1cea51d0c6df5732b59e934ccf415e010529e9cc6c5db181  guix-build-cd57bb1a6626/output/x86_64-linux-gnu/bitcoin-cd57bb1a6626-x86_64-linux-gnu-debug.tar.gz
91cc5a77ef30691a2793a2f5f10f426a5aa620ec55d7fac7a945fa4cdbc431ef  guix-build-cd57bb1a6626/output/x86_64-linux-gnu/bitcoin-cd57bb1a6626-x86_64-linux-gnu.tar.gz
2bbc50eee80a63dd3b3c3f60a38bc0951add0f1db4bfcaddbf52da519aac56dd  guix-build-cd57bb1a6626/output/x86_64-w64-mingw32/SHA256SUMS.part
85dbf24017d34950c810b427ba965874cae865475e08e378d5b766c19c79082d  guix-build-cd57bb1a6626/output/x86_64-w64-mingw32/bitcoin-cd57bb1a6626-win-unsigned.tar.gz
9146603ef76f2defd1f768b874ed11dd5838008c0346f85982b103010cbb1055  guix-build-cd57bb1a6626/output/x86_64-w64-mingw32/bitcoin-cd57bb1a6626-win64-debug.zip
6cadd6813c4cd723657f4eb3a59cf4a517bc1bfc3797cc3dead8f0d7155c4a58  guix-build-cd57bb1a6626/output/x86_64-w64-mingw32/bitcoin-cd57bb1a6626-win64-setup-unsigned.exe
30271711dd689096e05b381df8f916b082e5b2308b6a2655cf672f632b53d69e  guix-build-cd57bb1a6626/output/x86_64-w64-mingw32/bitcoin-cd57bb1a6626-win64.zip
```

**Comment by laanwj** [comment]
Let's add #22589

**Comment by fanquake** [comment]
> Let's add #22589

Added.

**Comment by laanwj** [comment]
ACK 739d19053b152c8f6a5d70461a9a1b93549f135c

**Pull request merged**
