### PR TITLE
gui: Drop PeerTableModel dependency to ClientModel

### PR DESCRIPTION
**Pull request by promag**
Class `PeerTableModel` doesn't actually depend on `ClientModel`.

### CODE REVIEW

**Comment by promag** [comment]
@jonasschnelli don't know how I've missed this simple change in #18036.

**Comment by hebasto** [comment]
Concept ACK.

**Review by hebasto — APPROVED** [review]
ACK ff59bcd3213ef61f2167c0aa60fcaf5afbc20c61, tested on Linux Mint 19.3. No changes in behavior are observed.

**Comment by Empact** [comment]
Code Review ACK https://github.com/bitcoin/bitcoin/pull/18060/commits/ff59bcd3213ef61f2167c0aa60fcaf5afbc20c61

**Pull request merged**
