### PR TITLE
 doc: Switch release-notes.md to union merge 

### LINKED ISSUE #12819: Avoid release-notes.md conflicts
From #bitcoin-core-dev:

```
12:05 < jnewbery> release-notes.md conflicts are really irritating. Any thoughts on how to make them stop? Perhaps have a separate release-notes file for each PR that requires them, eg release-notes-pr1234.md, and then concatenate/edit them before the release? Release notes need a lot of editing anyway, so might not add too much overhead
12:11 < sipa> jnewbery: that doesn't seem like more overhead than the to-wiki-and-back dance we do already at the end
...
13:23 < instagibbs> jnewbery, ive had to rebase a couple PRs a couple times each due to that :/
13:27 < sipa> instagibbs: easy rebases, thankfully :)
13:28 < instagibbs> muh acks!
```

I'm interested to hear any other suggestions for avoiding release-notes conflicts.

### PR DESCRIPTION
**Pull request by maflcko**
Fix #12819

### CODE REVIEW

**Comment by jnewbery** [comment]
Concept ACK. Why not just place the new rule in the base directory .gitattributes file?

**Comment by MarcoFalke** [comment]
Thanks, I missed that there was one

**Comment by instagibbs** [comment]
huh TIL.

concept ACK

**Comment by jnewbery** [comment]
Tested ACK 5be024a0ed891fff202106cfc046d6e90f265a99

**Comment by MeshCollider** [comment]
Nice, utACK https://github.com/bitcoin/bitcoin/pull/12823/commits/5be024a0ed891fff202106cfc046d6e90f265a99

**Review by randolf — APPROVED** [review]

**Comment by ajtowns** [comment]
This works fine locally but github will still report a merge conflict. See https://github.com/isaacs/github/issues/487 for background and https://github.com/ajtowns/test-repo/pull/8 for an example.

**Comment by MarcoFalke** [comment]
We don't use GitHub for merges, so I guess that is fine.

**Comment by laanwj** [comment]
Can you elaborate on what the result of this will be? The git documentation says this on union merges:

>  Instead of leaving conflicts in the file, resolve conflicts favouring our (or their or both) side of the lines.

Does this mean it prefers losing information (by taking from either side) to adding conflicts?

**Comment by MarcoFalke** [comment]
The documentation is for all three options, which explains the weird structure of the sentence.

The explanation for `--union` is "Instead of leaving conflicts in the file, resolve conflicts favouring <strike>our (or their or</strike> both) side of the lines."


https://git-scm.com/docs/git-merge-file#git-merge-file---union

**Comment by MarcoFalke** [comment]
Which means that for *any* conflict it will include both sides. That is fine if both sides add stuff, but does not work too well if both sides remove the same line. That would mean someone had to solve the "union merge conflict" after merge.

**Comment by jnewbery** [comment]
> We don't use GitHub for merges, so I guess that is fine.

I think the benefit of this PR would be if it didn't cause GitHub to say that a PR has conflicts (and therefore needs rebase). If github still thinks there's a conflict then the PRs will still require a rebase (and therefore invalidate ACKs).

**Comment by laanwj** [comment]
Thanks for the explanation.

Any idea how this will interact with #12708? Will git still see the union-result as a "clean merge"?

**Comment by MarcoFalke** [comment]
It should, since it uses `git merge` internally and that should respect the attributes file.

**Comment by practicalswift** [comment]
Concept ACK

Good idea

**Pull request closed without merging**
