### PR TITLE
util: Do not use gArgs global in ArgsManager member functions

### PR DESCRIPTION
**Pull request by hebasto**

### CODE REVIEW

**Review by promag — COMMENTED** [review]
Could also drop gArgs from `ReadConfigFiles`?

**Comment by hebasto** [comment]
Updated 7d3c3fec7a9fdd08438f6382f2bf705eaefe21e7 -> d103484fe81a8a5bf1d692f3f7d1c0ef1be5f63c ([pr20092.01](https://github.com/hebasto/bitcoin/commits/pr20092.01) -> [pr20092.02](https://github.com/hebasto/bitcoin/commits/pr20092.02), [diff](https://github.com/hebasto/bitcoin/compare/pr20092.01..pr20092.02)):

- addressed @promag's [comment](https://github.com/bitcoin/bitcoin/pull/20092#pullrequestreview-502851521):
> Could also drop gArgs from `ReadConfigFiles`?

**Comment by practicalswift** [comment]
ACK d103484fe81a8a5bf1d692f3f7d1c0ef1be5f63c: patch looks correct

**Comment by promag** [comment]
ACK d103484fe81a8a5bf1d692f3f7d1c0ef1be5f63c.

**Pull request merged**
