### PR TITLE
RPC SendMany Help: remove subtractfeefromamount

### PR DESCRIPTION
**Pull request by ChainQuery**
Argument 5, subtractfeefromamount, listed in help for sendmany is ignored and not a valid argument.

Remove it from help.

### CODE REVIEW

**Comment by casey** [comment]
I'm not sure if I'm reading the code correctly, but it looks like the argument is not ignored. The array is stored in `subtractFeeFromAmount` on line 969, and then used to create the `CRecipient` on line 999, which is eventually passed into `pwalletMain->CreateTransaction`.

**Comment by ChainQuery** [comment]
I'm not sure if I'm reading it correctly either, but this was inspired by /contrib/bitrpc/bitrpc.py sendmany inputs starting on line 251. The 5th, subtractfeefromamount, is ignored.

**Comment by casey** [comment]
It looks like `bitrpc.py` is just missing the subtractfeefromamount argument. This is an omission in `bitrpc.py`, not a bug in the help dialog.

**Comment by ChainQuery** [comment]
Your right. Closing this request.

**Pull request closed without merging**
