### PR TITLE
Reorder travis builds for faster response

### PR DESCRIPTION
**Pull request by sipa**
Ordered the travis builds approximately from slower to faster ones, to bring their end times closes together (hopefully resulting in a faster result overall).

### CODE REVIEW

**Comment by fanquake** [comment]
Needs rebase

**Comment by laanwj** [comment]
Yes, needs rebase

**Comment by sipa** [comment]
Redone.

The first one is the fastest now (ARM), the following ones are ordered from slow to fast.

**Comment by jonasschnelli** [comment]
ACK.


Before PR:
bildschirmfoto 2015-03-13 um 15 29 23


After PR:
bildschirmfoto 2015-03-13 um 15 29 59

**Pull request merged**
