### PR TITLE
refactor: Replace HexStr(o.begin(), o.end()) with HexStr(o)

### PR DESCRIPTION
**Pull request by laanwj**
HexStr can be called with anything that bas `begin()` and `end()` functions, so clean up the redundant calls.

(context: I tried to convert `HexStr` to use span, but this turns out to be somewhat more involved than I thought, because of the limitation to pre-c++17 Span lacking iterator-based constructor) . This commit is a first step which stands on its own though)

### CODE REVIEW

**Review by jonatack — COMMENTED** [review]
Nice cleanup.

almost-ACK 282df9029ff138ec1d263e57fcf3373d51929598 modulo when building the fuzzers

```
test/fuzz/decode_tx.cpp:17:39: error: no matching constructor for initialization of 'std::string' (aka 'basic_string<char>')
    const std::string tx_hex = HexStr(std::string{buffer});
                                      ^          ~~~~~~~~
```

**Comment by laanwj** [comment]
Thanks!
Re-pushed, hopefully fixing the fuzzer issue.

**Comment by jonatack** [comment]
ACK bd93e32292c96b671e71223032ff8f660ce27c5d

`git diff 282df90 bd93e32`
```diff
diff --git a/src/test/fuzz/decode_tx.cpp b/src/test/fuzz/decode_tx.cpp
@@ -14,7 +14,7 @@
 
 void test_one_input(const std::vector<uint8_t>& buffer)
 {
-    const std::string tx_hex = HexStr(std::string{buffer});
+    const std::string tx_hex = HexStr(buffer);
```

recalcitrant fuzzer is back in action
```
((HEAD detached at origin/pr/19373))$ ./src/test/fuzz/decode_tx ../qa-assets/fuzz_seed_corpus/
INFO: Seed: 4054234011
INFO: Loaded 1 modules   (20258 inline 8-bit counters): 20258 [0x5645f8a56df0, 0x5645f8a5bd12), 
INFO: Loaded 1 PC tables (20258 PCs): 20258 [0x5645f8a5bd18,0x5645f8aaaf38), 
INFO:    53252 files found in ../qa-assets/fuzz_seed_corpus/
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
INFO: seed corpus: files: 53252 min: 1b max: 3984182b total: 495231715b rss: 100Mb
#2	pulse  ft: 693 exec/s: 0 rss: 102Mb
#4	pulse  cov: 692 ft: 693 corp: 1/1b exec/s: 0 rss: 102Mb
.../...
#16384	pulse  cov: 2638 ft: 7052 corp: 158/4355b exec/s: 399 rss: 257Mb
#32768	pulse  cov: 2646 ft: 10391 corp: 268/18Kb exec/s: 315 rss: 269Mb
```

**Comment by troygiorshev** [comment]
ACK bd93e32292c96b671e71223032ff8f660ce27c5d

When running all of the fuzz tests `descriptor_parse` and `parse_univalue` break for me.  However, those aren't touched by this PR so I'm assuming it's a problem with my machine.  When those are excluded, everything works fine.

Looking forward to eventually being able to build the fuzz tests at the same time as everything else [:)](https://github.com/theuni/bitcoin/commits/build-fuzz)

**Comment by jonatack** [comment]
@troygiorshev maybe `make clean` or `make distclean` might help: `./autogen.sh ; ./configure --enable-c++17 --enable-fuzz --with-sanitizers=address,fuzzer,undefined CC=clang CXX=clang++ && make clean && make -j <nproc>`

**Comment by MarcoFalke** [comment]
I ran `sed -i --regexp-extended -e 's/HexStr\(([^(]+)\.begin\(\), *([^(]+)\.end\(\)\)/HexStr(\1)/g' $(git grep -l HexStr)` and arrived at the same result.

review ACK bd93e32292c96b671e71223032ff8f660ce27c5d 🔌

<details><summary>Show signature and timestamp</summary>

Signature:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

review ACK bd93e32292c96b671e71223032ff8f660ce27c5d 🔌
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEE+rVPoUahrI9sLGYTzit1aX5ppUgFAlwqrYAACgkQzit1aX5p
pUgRIAv/Uk2ihLCqBuVZ0KblTbUu+g5OGfsCXD9KS2QFTVWWMoa7uNFfJW1AQfVq
xwu1u7fHAxE51Pd8pshRLD7PjNRT1vab5wW5NXp0UuBJMjUb8uoQ1x3CYLHN24wV
c434W65R92ZLMkYUM+gBixh3DkiRXd89mnihcxqp15Ls7yhZJIW08e5DZKIKNbiH
HfM+PFkdq4DJV473hhASjSKgdVBngZuuOdzk6Vi53jOQFh7IE38YeT71xBJ0IRBh
qiCfcXsS/mzRrFe7PHMG9GPlWzMP/ede5ICOrauncjgA/3UBR6i1o9RfzX6b885o
M9c5dHdkhd3WjuwEBYrCj9gtbMRyqC7kZbLEYhWcfR/Psp/0SKyF4FAP8O8AItiC
rc4BQYJn/3GG7b7SUReu2PyyDFPwJW3r68x6WQEbSclHq+3iRfNKTiOBe1vc0zI+
r2FnahlKrw3/hqz4jDUJfgooeiKHrev2SJOKZJOhzGqyL4ujnTdKp+NRpoRRXy+t
hxQ3BPag
=NgtJ
-----END PGP SIGNATURE-----
```

[Timestamp of file with hash `c29a816f655c66172f117b610389a5a791097d2c042b69406155146f2572f5c9  -`](https://opentimestamps.org/info/?004f70656e54696d657374616d7073000050726f6f6600bf89e2e884e892940108c29a816f655c66172f117b610389a5a791097d2c042b69406155146f2572f5c9f010c2a103b6675b71d458e451e0cdc13c8c08fff0104459592e033a74854f86c4af5ca1329d08f1045ef399c2f00857b4a56270ab6dbb0083dfe30d2ef90c8e2c2b68747470733a2f2f626f622e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267fff0104eebec5bba4ad1abca2a67aed08e3d5108f020ba58191bd2a160a946f2c007a7dae5f8adce66360b9cd5e83fd8d6644422fb0b08f1045ef399c2f008d0e4820a1b4a6db70083dfe30d2ef90c8e292868747470733a2f2f66696e6e65792e63616c656e6461722e657465726e69747977616c6c2e636f6dfff010a0efaeb21c66dd7926a5cd5db13b2f6608f1045ef399c2f00819044ea813165be60083dfe30d2ef90c8e232268747470733a2f2f6274632e63616c656e6461722e636174616c6c6178792e636f6df010a8bfbac3b2e730edc1fb37aac979b88908f020499078c142e3b94f2d0e8fd8a11765b2fb633f1e3fe941dc1d2f7ca0429230d708f1045ef399c3f008115276f7213c3bb20083dfe30d2ef90c8e2e2d68747470733a2f2f616c6963652e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267)

</details>

**Pull request merged**
