### PR TITLE
scripted-diff: Small locking rename

### PR DESCRIPTION
**Pull request by ryanofsky**
Call sync.h primitives "locks" and "mutexes" instead of "blocks" and "waitable critical sections" to match current coding conventions and c++11 standard names.

This PR does not rename the "CCriticalSection" class (though this could be done as a followup) because it's used everywhere and would swamp the other changes in this PR. Plain mutexes should mostly be preferred instead of recursive mutexes in new code anyway.

### CODE REVIEW

**Comment by promag** [comment]
Concept ACK.

Drop `C` prefix too?

**Comment by ryanofsky** [comment]
>Concept ACK.
>
>Drop C prefix too?

Thanks, will wait for more feedback. I didn't rename CCriticalSection because it's used everywhere and changing it would make the diff 3 times as big (22 lines -> 73 lines). Also I think we will probably lean toward using non-recursive rather than recursive locks in new code, so CCriticalSection name should not matter as much going forward. I kept the C in CCriticalLock to be consistent with CCriticalSection. CCriticalLock is only used internally in sync.h so again it shouldn't have an impact on new code, and I didn't see a reason to break consistency within sync.h.

**Comment by practicalswift** [comment]
utACK eec3e2261eb895b704c5153203e6b1b946213667

**Comment by TheBlueMatt** [comment]
To me, calling it just "Mutex"/"Lock" implies this is what people should use for new mutexs/locks, but that isn't what we want because it doesn't support DEBUG_LOCKORDER. Indeed, we maybe could make it support DEBUG_LOCKORDER and then start migrating to it over our current recursive stuff, but for now I'd prefer to make it more clear that the new typedefs should be discouraged.

**Comment by ryanofsky** [comment]
Is DEBUG_LOCKORDER the only reason you want to discourage these?

**Comment by TheBlueMatt** [comment]
I suppose, I mean as long as its clear that its non-recursive and someone doesn't introduce a bug on accident cause they're not paying attention, DEBUG_LOCKORDER would be my only complaint.

**Comment by ryanofsky** [comment]
I'll just implement DEBUG_LOCKORDER for these. It should be pretty easy.

**Comment by MarcoFalke** [comment]
Needs rebase

**Comment by laanwj** [comment]
If we're renaming them anyway, why not call them what they are? RecursiveMutex. RecursiveLock, Mutex, Lock?

I'm all for using non-recursive locks in new code, using recursive locks is usually discouraged nowadays.

**Comment by TheBlueMatt** [comment]
Indeed, after #11640, and because this is scripted, I'd be more than happy to see us drop the "CriticalSection" naming - no one uses that anymore...

**Comment by practicalswift** [comment]
Agree with @laanwj – let's use the standard C++11 naming instead of project-local names for locking constructs.

Are there any good arguments for using project-local names for the locking constructs?

**Comment by laanwj** [comment]
Please get rid of the "Merge remote-tracking branch 'origin/pull/11640/head'" merge commit

utACK otherwise

**Comment by ryanofsky** [comment]
> Please get rid of the "Merge remote-tracking branch 'origin/pull/11640/head'" merge commit
>
>utACK otherwise

@laanwj, could you add your utACK to #11640? The merge just indicates #11599 is based on #11640, and distinguishes the #11599 commits from the #11640 one.

**Comment by MarcoFalke** [comment]
Needs rebase

**Pull request merged**
