### PR TITLE
util: Use std::chrono for time getters

### PR DESCRIPTION
**Pull request by maflcko**

### CODE REVIEW

**Comment by MarcoFalke** [comment]
We may have to wait for C++20 to be able to use this and be absolutely sure this returns UTC

So closing for now unless there is reason to push this.

**Comment by sanjaykdragon** [comment]
> We may have to wait for C++20 to be able to use this and be absolutely sure this returns UTC
> 
> So closing for now unless there is reason to push this.

Why do we need to wait until C++20 to use this? From what I have seen, the commit you made uses features from C++11 to C++17 (although we don't support C++17 yet, afaik)

**Comment by MarcoFalke** [comment]
https://en.cppreference.com/w/cpp/chrono/system_clock

**Comment by MarcoFalke** [comment]
Or use the sanity check thingy from #9566

**Pull request closed without merging**
