### PR TITLE
misc: Autotools -> CMake changes

### PR DESCRIPTION
**Pull request by fanquake**
These don't seem to be included in, i.e #30664.

### CODE REVIEW

**Comment by fanquake** [comment]
Given the lint change actually changes behaviour, I don't think squashing that into "doc" changes is correct. But will squash the other two.

**Review by theuni — COMMENTED** [review]
LGTM ACK after squash

**Review by hebasto — APPROVED** [review]
ACK 4188c2a11241ece8774e62b0f585adb91aa44cb9.

**Review by hebasto — APPROVED** [review]
re-ACK a865494deeff7dedcad7140299aee00ab3cdd62c.

**Pull request merged**
