### PR TITLE
[0.16.1] gui: Backport bech32 checkbox

### PR DESCRIPTION
**Pull request by maflcko**

### CODE REVIEW

**Comment by jonasschnelli** [comment]
utACK dcb13a0ab687b23465a046e35ca75a432427b833

**Comment by promag** [comment]
Tested ACK 0eda98d. utACK dcb13a0.

**Comment by fanquake** [comment]
utACK dcb13a0

**Comment by achow101** [comment]
utACK dcb13a0ab687b23465a046e35ca75a432427b833

**Comment by laanwj** [comment]
utACK dcb13a0ab687b23465a046e35ca75a432427b833

**Pull request merged**
