### PR TITLE
[0.20] Fix release tarball

### PR DESCRIPTION
**Pull request by luke-jr**
Includes parts of #18556, #18741, #18818, and #18902 needed to fix the release tarball for 0.20

### CODE REVIEW

**Comment by hebasto** [comment]
c474e46ae7604f9b6cf8801207300b81c97e0499:
Mind adding the `.sh` extension to the `make_release_tarball` script name to make it available for `lint-shell.sh`?

**Comment by hebasto** [comment]
e46e063562a433d8a3718036985e9008f6278bc0
Could consider an alternative approach https://github.com/bitcoin/bitcoin/pull/18349/commits/80190e7aeb7e730934271b03918640ec18a56dc5 that seems less hacky?

**Comment by hebasto** [comment]
Concept ACK.

**Comment by fanquake** [comment]
I'm going to close this. At this point we're not going to be backporting any tarball related changes to the 0.20 branch. I'll also echo the comments made in #18818; I haven't seen a single complaint/issue related to changes in the `0.20` tarball over the ~10 months since it's been released.

**Pull request closed without merging**
