### PR TITLE
[trivial] pull secp256k1 subtree

### LINKED ISSUE #7018: Master will not compile on Windows7
Failing to compile.  I can get it to compile by doing:

-#include "include/secp256k1.h"
+#include "../include/secp256k1.h"

It's obviously not finding the header, but not sure if that's really where it should be fixed 

make[3]: Leaving directory `/c/bitcoin-a/src/leveldb'
make[3]: Entering directory `/c/bitcoin-a/src/secp256k1'
gcc -I./ -g -O2 -Wall -Wextra -Wno-unused-function -c src/gen_context.c -o gen_c
ontext.o
src/gen_context.c:10:31: fatal error: include/secp256k1.h: No such file or direc
tory
 #include "include/secp256k1.h"
                               ^
compilation terminated.
make[3]: *** [gen_context.o] Error 1
make[3]: Leaving directory `/c/bitcoin-a/src/secp256k1'
make[2]: *** [secp256k1/libsecp256k1.la] Error 2
make[2]: Leaving directory `/c/bitcoin-a/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/c/bitcoin-a/src'
make: *** [all-recursive] Error 1

### PR DESCRIPTION
**Pull request by maflcko**
This fixes #7018.

Reviewers may call `$ contrib/devtools/git-subtree-check.sh src/secp256k1 fa63e49`

### CODE REVIEW

**Comment by laanwj** [comment]
utACK
I don't like the subtree commit noise just to update a single line in a single file, but that's a less pretty side of subtrees that we have to accept, I guess.

**Comment by jonasschnelli** [comment]
utACK.

Maybe we should wait and combine changes in the libsecp256k. IIRC @sipa and @gmaxwell had in mind to do a libsecp256k1 release which would be a good tag for a subtree update.

**Comment by MarcoFalke** [comment]
> subtree commit noise

Only one commit overhead at most, so negligible compared to what was already saved. ;)

> combine changes

Sure. Is there an eta of the release?

**Comment by sipa** [comment]
utACK

This is more urgent to fix, I think.

**Comment by gmaxwell** [comment]
utACK. Build system fix, should go in sooner rather than later. "Pardon our dust."

**Comment by dcousens** [comment]
utACK

**Pull request merged**
