### PR TITLE
Trivial: Fix #include sys/fcntl.h to just fcntl.h (without sys/)

### PR DESCRIPTION
**Pull request by jsarenik**
http://pubs.opengroup.org/onlinepubs/009695399/functions/fcntl.html
http://man7.org/linux/man-pages/man2/fcntl.2.html

### CODE REVIEW

**Comment by jsarenik** [comment]
Rationale: compiling on musl-based system (Alpine Linux for example) produces warnings. It just should be without `sys/`.

**Comment by MarcoFalke** [comment]
utACK 648bdc8cc09c85748967b86347bbc7825e339d5f

**Review by theuni — APPROVED** [review]
Heh, I have the same commit queued up locally from testing with musl this week.

I believe there are some ancient OSs that may only have the sys/fcntl.h version, but I'm ok with not adding detection until someone complains about an actual failed build.

utACK 648bdc8cc09c85748967b86347bbc7825e339d5f

**Comment by fanquake** [comment]
utACK 648bdc8

**Pull request merged**
