### PR TITLE
remove unused variable - consensus.nMinerConfirmationWindow

### PR DESCRIPTION
**Pull request by ghost**
consensus.nMinerConfirmationWindow is initialized to 0 via the c++11 standard and never assigned a value. Code is not rearranged like the earlier pull request and is 100% equivalent. Leaving the code as is makes it appear as if there is a bug.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Ok, now I see what you did in #17433. Please restore the fix from #17433 and cherry-pick it on master. (We merge bug fixes to master and then backport them to old branches after they have been merged to master)

**Comment by MarcoFalke** [comment]
>consensus.nMinerConfirmationWindow is initialized to 0 via the c++11 standard

This is not true. It is uninitialized memory.

**Comment by bitcoinVBR** [comment]
Created new pull request on master for this:

fix uninitialized variable nMinerConfirmationWindow #17449

**Comment by bitcoinVBR** [comment]
> > consensus.nMinerConfirmationWindow is initialized to 0 via the c++11 standard
> 
> This is not true. It is uninitialized memory.

Yes you are right, there isn't a     = {}; to initializes all members to zero

**Comment by laanwj** [comment]
Closing in favor of #17449

**Pull request closed without merging**
