### PR TITLE
Update developer notes with RPC response guidelines

### PR DESCRIPTION
**Pull request by promag**

### CODE REVIEW

**Comment by jnewbery** [comment]
ACK - seems like a reasonable suggestion. Agree that this should be a SHOULD rather than a MUST.

**Comment by mess110** [comment]
The main reason I can think of not to return a JSON object is if it returns something raw like a key or a number. Maybe there are also backward compatibility reasons why non JSON output is returned. Are there any other reasons?

Wouldn't it make it easier for clients to always expect a JSON object in the response? It would be future proof as well.

**Comment by laanwj** [comment]
Backward compatibility is a strong reason. We don't change existing interfaces unless there is a a good reason, and just conforming to a developer-notes item is not one.

Also, it's slightly easier to use from the command-line with `bitcoin-cli` if something returns a bare value.

**Comment by promag** [comment]
@laanwj the guideline is `Try to make the RPC response a JSON object`, it's not agains bare values. Beside that, I would bet RPC is mostly used with foreign client libraries than with `bitcoin-cli`.

**Comment by laanwj** [comment]
> I would bet RPC is mostly used with foreign client libraries than with bitcoin-cli

That's not the point, isn't it? despite a bet what use form is more common, many people are using `bitcoin-cli` as a command line client.

**Comment by promag** [comment]
No it isn't for sure, but I think we shouldn't have `bitcoin-cli` in mind when deciding API interface.

As for `bitcoin-cli`, I've previously suggested to have something like `-rpcoutput=...` to ease in those cases, but that's another topic.

Do you think I should improve the guideline?

**Review by luke-jr — APPROVED** [review]
ACK

**Comment by MarcoFalke** [comment]
ACK 62ecce7

**Pull request merged**
