### PR TITLE
[WIP] [Wallet] Target effective value during transaction creation

### PR DESCRIPTION
**Pull request by instagibbs**
Previous fee-targeting behavior lead to needless looping, excessive fees, and surprising behavior. 

This PR changes the "fee targeting" algorithm by considering "effective value" of considered inputs instead of simply trying to hit an absolute fee, seeing if it failed, then trying again with the estimated total fee at the end of the loop.

The algorithm also doesn't select any coin with non-positive effective value.

In short:
`effectiveValue = nValue - feeRate*num_bytes_for_signed_input`

See https://github.com/bitcoin/bitcoin/issues/10247 , https://github.com/bitcoin/bitcoin/issues/7664 

To do:
1) Previously the wallet just kept stuffing fees until it succeeded. In this PR there is no strict sanity checks on the loop, so if there is some error where we are just shy and cannot re-balance change output to pay for it, it will look forever(I have no idea if this is possible since we should be over-estimating at worst). We should probably have something like https://github.com/bitcoin/bitcoin/pull/10333 for re-balancing, and then a sanity check to error out if a specified feerate cannot be hit for some reason post-coin selection, perhaps after a fixed number of tries. 
2) This breaks the `coinControl->nMinimumTotalFee` option. I can't conceive a use for it, so I want to remove this anyways.  https://github.com/bitcoin/bitcoin/pull/10390

### CODE REVIEW

**Comment by instagibbs** [comment]
Getting travis `RPC_WALLET_INSUFFICIENT_FUNDS` errors all over the place for one configuration. Can't reproduce locally...

**Comment by morcos** [comment]
sort of concept ACK

I think there are a lot of issues to think about in order to make sure we don't accidentally introduce poor behavior.
One simple improvement would be to cache the number of bytes each input would require to spend to create a much simpler calculation of effective value each time through instead of dummy signing an ever growing virtual transaction.

But I'm more concerned with the interaction between the knapsack solver and the effective value inputs.  Since the knapsack solver aims for exact matches (either with or without change), I believe there will be a tendency to often include many very small effective inputs to try to get as close as possible to an arbitrary change number.

**Comment by instagibbs** [comment]
>One simple improvement would be to cache the number of bytes each input would require to spend to create a much simpler calculation of effective value each time through instead of dummy signing an ever growing virtual transaction.

Yes, some additional refactoring would make sense especially for this. This was probably the most janky part of my implementation.

>I believe there will be a tendency to often include many very small effective inputs to try to get as close as possible to an arbitrary change number.

As we discussed on IRC, Core already does this, but you mean that previously slightly larger inputs would now fall under this bucket so it may pack even more. It's hard to say the net effect especially since we disallow negative effective value inputs, but something to think about. OTOH If we wait until everything is an unambiguous win, I am not sure any changes will get merged.

> some chatter about general refactoring on IRC

I really don't mind attempting to tackle more refactoring within this PR. I admittedly did just over minimal refactoring to make it work.

**Comment by instagibbs** [comment]
@gmaxwell notes on IRC that we may want to consider unconfirmed change as smaller effective value by having it also need to pay for the ancestor(s) feerate delta to current confirmation target feerate.

**Comment by instagibbs** [comment]
closing until BnB PR has been merged, then will revisit our transaction creation strategy as a whole.

**Pull request closed without merging**
