### PR TITLE
Globals: Explicitly pass const CChainParams& to UpdateTip()

### PR DESCRIPTION
**Pull request by jtimon**
Part of #7829.

### CODE REVIEW

**Comment by laanwj** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/7876/commits/145ae6e714f9f212c39ec7684b4de813e0abc921

If there are other functions where you can easily pass in CChainParams& with low impact to the rest of the code, I'd prefer if you combine them into this instead of open separate pulls.

**Comment by instagibbs** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/7876/commits/145ae6e714f9f212c39ec7684b4de813e0abc921

**Comment by jtimon** [comment]
@laanwj well, the idea of #7829 is helping new people doing them. I did #7828 as a "canonical example" (in fact, I wanted to pass CPolicy at the same time, but ProcessMessage() had waited enough for CPolicy to exist...) and this one because it seems slightly more confusing (or could confuse someone trying to do it for DisconnectTip()). I wouldn't mind doing DisconnectTip() in this PR for that reason.

Probably the less disruptive remaining ones are ConnectBlock(), CheckBlockHeader() and ContextualCheckBlockHeader() [I didn't put ContextualCheckBlock() because @morcos and I want to just destroy the function]. But these seem good exercises for #7829.

Besides that, I must have tried to do CheckBlockHeader() like in 10 different PRs already (probably 5 of them did it before and 5 of them after the cursed consensus moveonly), but I've never tried to get someone else to do it. Perhaps this breaks the curse or something.

**Comment by laanwj** [comment]
@jtimon Well sure it helps reviewing to have small pull requests, but if it's just adding an argument to a function and passing it on that's hardly a risky refactor, nor controversial in any way.

> I wouldn't mind doing DisconnectTip() in this PR for that reason

ok Let's do that.

**Comment by jtimon** [comment]
Closing in favor of #7916 , which contains this same commit plus another one doing it for DisconnectTip() and InvalidateBlock() too.

**Pull request closed without merging**
