### PR TITLE
[qa] Avoid printing to console during cache creation

### PR DESCRIPTION
**Pull request by sdaftuar**

### CODE REVIEW

**Comment by promag** [comment]
ACK, sounds reasonable.

**Comment by MarcoFalke** [comment]
I'd prefer if that was done during `initialize_datadir`, so you could remove it here as well: https://github.com/bitcoin/bitcoin/blame/1807dd13633ff9c7fe00f8727b9c628cbc144595/test/functional/test_framework/test_node.py#L85

**Comment by sdaftuar** [comment]
@MarcoFalke done

**Comment by laanwj** [comment]
Needs rebase (for #12755, I think.)

**Comment by sdaftuar** [comment]
Rebased

**Comment by laanwj** [comment]
utACK 08ebdba82a5a75155234cbe3c6cdf08a2e087c2f

**Comment by MarcoFalke** [comment]
utACK 08ebdba

**Pull request merged**
