### PR TITLE
tests: Don't depend on value of DEFAULT_PERMIT_BAREMULTISIG

### PR DESCRIPTION
**Pull request by ajtowns**
Update unit and functional tests so that they continue to work if the default for `-permitbaremultisig` is changed.

### CODE REVIEW

**Comment by instagibbs** [comment]
crACK https://github.com/bitcoin/bitcoin/pull/29088/commits/7b45744df33c6a4759eae1a3984f389cbac837c2

(someone should probably switch it default false and check)

**Comment by ajtowns** [comment]
> crACK [7b45744](https://github.com/bitcoin/bitcoin/commit/7b45744df33c6a4759eae1a3984f389cbac837c2)
> 
> (someone should probably switch it default false and check)

see also CI on #29093

**Review by glozow — COMMENTED** [review]
ACK 7b45744df33c6a4759eae1a3984f389cbac837c2, changed default locally and all tests passed

**Comment by achow101** [comment]
ACK 7b45744df33c6a4759eae1a3984f389cbac837c2

**Pull request merged**
