### PR TITLE
build, ci: add `DEBUG_LOCKCONTENTION` to --enable-debug and CI

### PR DESCRIPTION
**Pull request by jonatack**
- Add `DEBUG_LOCKCONTENTION` flag to the `--enable-debug` configuration
- Add `DEBUG_LOCKCONTENTION` to the native tsan CI task that contains `DEBUG_LOCKORDER` (verified that the CI has all logging categories enabled by default, except libevent and leveldb)
- Update the developer notes that `--enable-debug` configures `DEBUG_LOCKCONTENTION`

Related to https://github.com/bitcoin/bitcoin/issues/24709.

### CODE REVIEW

**Comment by jonatack** [comment]
Moving this out of draft.

**Comment by jonatack** [comment]
Dropped the first two commits that were remaining from #24734 to simplify and hopefully see review.

**Comment by jonatack** [comment]
Rebased.

**Review by maflcko — APPROVED** [review]
lgtm

**Pull request merged**
