### PR TITLE
test: non-positive integer value to `-peertimeout` should throw an error

### PR DESCRIPTION
**Pull request by brunoerg**
This PR adds test coverage for #25506, since #25505 gets closed.

### CODE REVIEW

**Comment by brunoerg** [comment]
cc: @kristapsk @1440000bytes

**Review by kristapsk — APPROVED** [review]
ACK d22bd543cc666e7fdb6fdd0eca5f7514f516b393

**Review by w0xlt — APPROVED** [review]
ACK https://github.com/bitcoin/bitcoin/pull/25511/commits/d22bd543cc666e7fdb6fdd0eca5f7514f516b393

**Review by ghost — APPROVED** [review]
ACK https://github.com/bitcoin/bitcoin/pull/25511/commits/d22bd543cc666e7fdb6fdd0eca5f7514f516b393

**Pull request merged**
