### PR TITLE
wallet: Use MTP for locktime checks, not adjusted time

### PR DESCRIPTION
**Pull request by maflcko**
The "flags" parameter is used to decide whether to use MTP or network adjusted time. Make the wallet use MTP instead of adjusted time.

Otherwise this might calculate the wrong wallet balance or list the wrong coins.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Added description and took out of draft

**Comment by luke-jr** [comment]
Concept ACK, but maybe while you're renaming, we should make it do `CheckSequenceLocks` as well?

**Comment by MarcoFalke** [comment]
> Concept ACK, but maybe while you're renaming, we should make it do CheckSequenceLocks as well?

Thanks, I've edited the scripted diff, but I am including this in a follow-up refactor to keep the bugfix patch minimal.

**Comment by MarcoFalke** [comment]
The included regression test can be tested by observing a failure when running against current master

**Comment by luke-jr** [comment]
But without CheckSequenceLocks, this is only a partial fix, and the bug remains...?

**Comment by MarcoFalke** [comment]
Done in https://github.com/bitcoin/bitcoin/pull/24067

**Pull request closed without merging**
