### PR TITLE
Remove unused variables

### PR DESCRIPTION
**Pull request by maflcko**
This removes the remaining unused variables outside of `src/test`.

### CODE REVIEW

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/8590/commits/fa6dc9f0e5eac8ec473b63adfd43635005778f46

**Comment by btcdrak** [comment]
ACK fa6dc9f

**Comment by laanwj** [comment]
Thanks, utACK

Just out of curiosity: what did you use to find these?

**Comment by MarcoFalke** [comment]
@laanwj I was looking into cppcheck and cpplint the last days. It was trivial to set up. According to the tools, those are the last unused variables.

Also, they found a ton of unused functions, but I couldn't find anything that deserves attention. E.g. [DeleteAuthCookie](https://dev.visucore.com/bitcoin/doxygen/rpc_2protocol_8cpp.html#a9807259ee7b7c4f5445cf54fd23589cb) is unused, but there is no point in removing the code. Almost all unused functions potentially turn out to be useful in the future.

Finally, cppcheck returned some errors and warnings but my knowledge of cpp is too low. So they could very well be false positives.

**Comment by MarcoFalke** [comment]
<sub>It would probably be fun to set up a GitHub bot account which scans each pull request and then spams all the code nits in the appropriate lines in the code...

**Comment by laanwj** [comment]
> @laanwj I was looking into cppcheck and cpplint the last days. It was trivial to set up. According to the tools, those are the last unused variables.

Thanks, I'll check them out. I think I've had cppcheck installed at some point, but kind of forgot about it.

>  E.g. DeleteAuthCookie is unused, but there is no point in removing the code. 

Yes sometimes a half of a [create,remove] pair that really belongs together is unused, this is one example. More an indication of 'this needs tests' than 'this code needs to be removed'.

**Comment by fanquake** [comment]
utACK fa6dc9f

**Pull request merged**
