### PR TITLE
docs: align items in contrib init

### PR DESCRIPTION
**Pull request by morenoh149**
minor

### CODE REVIEW

**Comment by fanquake** [comment]
trivial ACK 053b6f4

**Comment by hebasto** [comment]
trivial ACK 053b6f42d21fbbeb83d48b1a7b873b640976eab7

**Comment by promag** [comment]
Bad alignment due to latest rename to macOS.

ACK 053b6f4, although I think this file could be improved instead:
 - maybe add a title and improved better description
 - use table for the sample files
 - use link to doc/init.md

**Comment by laanwj** [comment]
do we really want PRs that add a single-space?

**Pull request merged**
