### PR TITLE
[net] add dnsseed.emzy.de to DNS seeds

### PR DESCRIPTION
**Pull request by Emzy**
ACK https://github.com/bitcoin/bitcoin/blob/master/doc/dnsseed-policy.md

I'm willing to keep it up and running, unless something bad happens.
I have 15+ years experience running dns servers.

About my setup:

- the server may change over time, but the service will be up all the time
- running [sipa/bitcoin-seeder](https://github.com/sipa/bitcoin-seeder) with default settings (and the non-root port redirect)

### CODE REVIEW

**Comment by jonasschnelli** [comment]
I can't see any prior contribution to this project by @Emzy. I suggest only adding DNS seeds from long term contributors.

**Comment by luke-jr** [comment]
I don't think code contributors should necessarily overlap with service contributors. In fact, it may be a positive thing to have at least one or two seeds run by non-developers. Regardless, we've had such in the past, and adding this new requirement seems like a topic for a PR to the policy document.

**Comment by laanwj** [comment]
The DNS seed seems to be working. Tried querying it and the addresses I got back were connectable.

**Comment by TheBlueMatt** [comment]
I've at least met @Emzy in person a few times, for whatever small amount that's worth.

**Comment by laanwj** [comment]
Ok I think we should probably do this then.

**Comment by laanwj** [comment]
utACK de7266fc3c9962cc3571c6ff72d616d2e8327fbb

**Pull request merged**
