### PR TITLE
Avoid -Wshadow warnings in wallet_tests

### PR DESCRIPTION
**Pull request by ryanofsky**
Warnings introduced by #9773 and reported by @paveljanik in #9773 and #9827.

### CODE REVIEW

**Comment by paveljanik** [comment]
Isn't the other way shorter (ie. changing only inside blocks)?

But anyway, this fixes the issue, yes. ACK https://github.com/bitcoin/bitcoin/pull/9828/commits/09fe346a4fb9c2b6c4f1bc1318494885708226cd

**Comment by ryanofsky** [comment]
The other way is shorter but would conflict with other pending prs. Also I think it is better for global variables to use longer names than locals.

**Comment by paveljanik** [comment]
@ryanofsky Yes, I agree.

**Review by dcousens — APPROVED** [review]

**Comment by MarcoFalke** [comment]
utACK 09fe346, I think we should give #8808 a try.

**Pull request merged**
