### PR TITLE
build: Upgrade default msvc platform

### PR DESCRIPTION
**Pull request by rojarsmith**
Support Visual Studio 2022.

Pass the full compile at Windows 11 and vcpkg 2021.12.01.

### CODE REVIEW

**Comment by hebasto** [comment]
What are other VS versions that are compatible with the `v143` toolset?

**Comment by rojarsmith** [comment]
> What are other VS versions that are compatible with the `v143` toolset?

VS2022 community is also free for non-profit organization, optimized for the latest hardware and similarity product architecture with VS2019. I recommend defalut toolset upgrade to the latest version.

Based on past experience it can also use the VS2019 IDE with the new v143 toolset with installing "Build Tools for Visual Studio 2022". (Sorry for I haven't tried)

I using the pre-build Qt5.12.11_x64_static_vs2019_16101 with VS2022 include v143 toolset is no problem.

**Comment by sipsorcery** [comment]
This PR isn't updating the toolset version in the msbuild project files. To update the default toolset version it will have to be set in `common.init.vcxproj`.

That also explains why this PR passes the cirrus build job even though it only has msbuild verison `16.11.2.50704` installed (vs 2022 and the corresponding C++ v143 toolset have an msbuild major version of 17).

Conceptually, updating the toolset to the latest version makes sense to me as long as cirrus supports it?

**Comment by rojarsmith** [comment]
> 
I did not update common.init.vcxproj because of the MSVC building must running the command at least once:
`
py -3 msvc-autogen.py
`
or
`
py -3 msvc-autogen.py -toolset v143
`

**Comment by sipsorcery** [comment]
For `py -3 msvc-autogen.py` this PR doesn't change anyting.

For `py -3 msvc-autogen.py -toolset v143` this PR isn't needed.

The only thing the `msvc-autogen.py` script does is write some of the `vcxproj` files, including the common ones. If the `PlatformToolset` version in `common.init.vcxproj` doesn't change, which it doesn't, then this PR has no effect.

**Comment by fanquake** [comment]
Thanks, however I'm going to close this for now, as it's not clear this is a (standalone) improvement.

**Comment by MarcoFalke** [comment]
See also https://github.com/cirruslabs/cirrus-ci-docs/issues/985

**Pull request closed without merging**
