### PR TITLE
refactor: Deleted unreachable code in httpserver.cpp

### PR DESCRIPTION
**Pull request by joaoajmatos**
Some of the code in httpserver.cpp was unreachable, and didn't follow the developer notes.

### CODE REVIEW

**Review by stickies-v — COMMENTED** [review]
Concept ACK - would clean up [`HTTPRequest::GetRequestMethod()`](https://github.com/bitcoin/bitcoin/blob/38d06e1561013f4ca845fd5ba6ffcc64de67f9c0/src/httpserver.cpp#L624-L643) at the same time though. Can't find any other such instances in the codebase (grepped with `"return.*\;\n\s*break\;"`)

**Review by w0xlt — COMMENTED** [review]
Approach ACK

**Review by hebasto — APPROVED** [review]
ACK 50439383a24fb7096e100ee6383da76db99426d5.

Agree with the [suggestion](https://github.com/bitcoin/bitcoin/pull/26570#pullrequestreview-1194569163) above.

Also, while touching this `switch` statement, maybe it makes sense to follow our [Developer Notes](https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md#c-data-structures) and replace `default:` with `case HTTPRequest::UNKNOWN:`?

**Comment by JoaoAJMatos** [comment]
I think this might be it

**Comment by hebasto** [comment]
@JoaoAJMatos 

Thank you for your contribution!

Usually, pull requests are required to be merge commit free.

Also the content of your commits could be more focused and self-contained. For example, the first commit removes all `break` statements from both `RequestMethodString` and `GetRequestMethod` functions. The second one refactors the `RequestMethodString` function to follow the Developer Notes.

And please include `// no default case, so the compiler can warn about missing cases` comment as it is being suggested by the Developer Notes.

**Comment by fanquake** [comment]
@JoaoAJMatos are you planning on following up here? Please also write a pull request description.

**Comment by fanquake** [comment]
@JoaoAJMatos you need to fixup your changes according to https://github.com/bitcoin/bitcoin/pull/26570#issuecomment-1328263377. You also cannot have merge commits.

**Pull request closed without merging**
