### PR TITLE
[backport] wallet: allow zero-fee fundrawtransaction/walletcreatefundedpsbt and other fixes

### PR DESCRIPTION
**Pull request by jonatack**
Github-Pull: #20426
Rebased-From: 1b3d7009280595108eb22ac1188bc4367804fc5d

Github-Pull: #20426
Rebased-From: 3f1e10b2b1cd11f7112fbad6355464bd4adbbc5c

Github-Pull: #20426
Rebased-From: 9f08780dd7946b63476e9736745131db8e7f4e93

### CODE REVIEW

**Comment by fanquake** [comment]
The GitHub-Pull & Rebased-From metadata should be included with each commit.

**Comment by jonatack** [comment]
> The GitHub-Pull & Rebased-From metadata should be included with each commit.

Thanks, I based this on #20490 and the commit messages were the same as the original. Just realized there's `bitcoin-maintainer-tools/backport.py`, will give it try.

**Comment by jonatack** [comment]
Thanks @fanquake, done.

**Comment by MarcoFalke** [comment]
#20490 didn't need cherry-picks, so I opted to merge without rebase. Though when cherry-picks are needed, it is better to include where they were cherry-picked from.

**Comment by jonatack** [comment]
Thanks @MarcoFalke.

**Pull request merged**
