### PR TITLE
ci: Run ci configs on cirrus

### PR DESCRIPTION
**Pull request by maflcko**
Travis CI Org is shutting down, so move the configs to cirrus ci

### CODE REVIEW

**Comment by hebasto** [comment]
Concept ACK.

**Comment by practicalswift** [comment]
Concept ACK: anything that allows us to get back CI detection of uses of uninitialized memory (UUM) is worth doing. The current unfortunate situation with no Valgrind and no MemorySanitzer in our main CI feels a bit scary TBH :\

**Comment by decryp2kanon** [comment]
Concept ACK

**Review by hebasto — APPROVED** [review]
ACK 969fcfc38f3f8c51fb26d735e9b9d477d1677c0f, I have reviewed the code and it looks OK, I agree it can be merged.

**Comment by MarcoFalke** [comment]
Rebased

**Comment by MarcoFalke** [comment]
Rebased. Should be ready for merge

**Comment by practicalswift** [comment]
ACK fa7a4385d08797876de9a05ae8a6fde18e36bd67: patch looks correct

**Pull request merged**
