### PR TITLE
Stop translating command line options

### PR DESCRIPTION
**Pull request by laanwj**
Many options are extremely technical, and refer internals, making it difficult to translate usefully. This came up in discussion of e.g.  #10949. If a message is not understood by translators (which are typically end-users, not developers) they'll either translate it literally, making it harder to understand instead of easier, with the added drawback of the user no longer being able to google it.

Also the translation was only working for bitcoin-qt as with the console programs, there is no translation backend. So it was injecting never-used translation messages for bitcoin-cli, -tx.

For these reasons, stop translating options help completely. This should not affect the output **in any way** \* except for bitcoin-qt when a non-English language is configured in the locale.

This implements #10962.

\*) I checked this, but please do verify this.

### CODE REVIEW

**Comment by promag** [comment]
Concept ACK. Needs release notes?

**Comment by laanwj** [comment]
> How about also get rid of translations of HelpMessageGroup in util.cpp?

Done, good catch.

> Concept ACK. Needs release notes?

I don't think that's necessary to mention explicitly. This is hardly even noticeable to the user.

**Comment by achow101** [comment]
utACK 2047cde5fe3aaa9cd8318a8d47e8080880a2757b

**Comment by practicalswift** [comment]
Concept ACK

**Comment by jonasschnelli** [comment]
Thanks. Finally!
utACK 2047cde5fe3aaa9cd8318a8d47e8080880a2757b (please squash).

**Comment by promag** [comment]
Will test.

**Comment by MarcoFalke** [comment]
re-ACK 3d4fa83587759095b7f0ccfe4075808098d4ae7f (No changes, so didn't re-test)

**Comment by ken2812221** [comment]
Tested ACK 3d4fa83587759095b7f0ccfe4075808098d4ae7f

**Comment by promag** [comment]
Tested ACK 3d4fa83. Help -> Command line options window also show not translated.

**Pull request merged**
