### PR TITLE
tests: Reduce memory usage by 0.5 GB when compiling script_tests.cpp

### PR DESCRIPTION
**Pull request by practicalswift**
Reduce compile-time memory usage (max RSS) by 0.5 GB when compiling script_tests.cpp (from 1.4 GB to 0.9 GB).

Context:
* See compile-time memory consumption [wall of shame in this month's State of the Repo Report](https://github.com/bitcoin/bitcoin/issues/16298).
* TheBlueMatt's issue #6658: "Building requires >1GB memory"

Compile-time memory consumption wall of shame before this PR:

| #  | File | Max memory usage (RSS) |
| -: | :--- | ---------------------: |
| 1 | `test/test_test_bitcoin-script_tests.o` | 1416 MB |
| 2 | `wallet/libbitcoin_wallet_a-wallet.o` | 1102 MB |
| 3 | `wallet/libbitcoin_wallet_a-rpcwallet.o` | 1059 MB |
| 4 | `libbitcoin_server_a-validation.o` | 953 MB |
| 5 | `test/test_test_bitcoin-util_tests.o` | 905 MB |

Compile-time memory consumption wall of shame after this PR:

| #  | File | Max memory usage (RSS) |
| -: | :--- | ---------------------: |
| 1 | `wallet/libbitcoin_wallet_a-wallet.o` | 1102 MB |
| 2 | `wallet/libbitcoin_wallet_a-rpcwallet.o` | 1059 MB |
| 3 | `libbitcoin_server_a-validation.o` | 953 MB |
| 4 | `test/test_test_bitcoin-script_tests.o` | 948 MB |
| 5 | `test/test_test_bitcoin-util_tests.o` | 905 MB |

Before:

```
$ /usr/bin/time g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I. -DBOOST_SP_USE_STD_ATOMIC -DBOOST_AC_USE_STD_ATOMIC -pthread -I/usr/include -I./leveldb/include -I./leveldb/helpers/memenv -I./secp256k1/include -I./univalue/include -DBOOST_TEST_DYN_LINK -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -fstack-reuse=none -Wstack-protector -fstack-protector-all -Wall -Wextra -Wformat -Wvla -Wformat-security -Wredundant-decls -Wno-unused-parameter -Wno-implicit-fallthrough -fPIE -g -O2 -MT test/test_test_bitcoin-script_tests.o -MD -MP -MF test/.deps/test_test_bitcoin-script_tests.Tpo -c -o test/test_test_bitcoin-script_tests.o test/script_tests.cpp
32.63user 0.99system 0:33.63elapsed 99%CPU (0avgtext+0avgdata 1443460maxresident)k
0inputs+114672outputs (0major+439941minor)pagefaults 0swaps
```

After:

```
$ /usr/bin/time g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I. -DBOOST_SP_USE_STD_ATOMIC -DBOOST_AC_USE_STD_ATOMIC -pthread -I/usr/include -I./leveldb/include -I./leveldb/helpers/memenv -I./secp256k1/include -I./univalue/include -DBOOST_TEST_DYN_LINK -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -fstack-reuse=none -Wstack-protector -fstack-protector-all -Wall -Wextra -Wformat -Wvla -Wformat-security -Wredundant-decls -Wno-unused-parameter -Wno-implicit-fallthrough -fPIE -g -O2 -MT test/test_test_bitcoin-script_tests.o -MD -MP -MF test/.deps/test_test_bitcoin-script_tests.Tpo -c -o test/test_test_bitcoin-script_tests.o test/script_tests.cpp
28.86user 0.95system 0:36.14elapsed 82%CPU (0avgtext+0avgdata 947984maxresident)k
0inputs+66112outputs (0major+285149minor)pagefaults 0swaps
```

### CODE REVIEW

**Comment by Sjors** [comment]
Concept ACK, but I get three warnings on macOS:

```
test/script_tests.cpp:489:13: warning: unknown pragma ignored [-Wunknown-pragmas]
#pragma GCC push_options
            ^
test/script_tests.cpp:490:13: warning: unknown pragma ignored [-Wunknown-pragmas]
#pragma GCC optimize ("O0")
            ^
test/script_tests.cpp:969:13: warning: unknown pragma ignored [-Wunknown-pragmas]
#pragma GCC pop_options
            ^
3 warnings generated.
  CXXLD    test/test_bitcoin
```

We should get rid of those warnings. However I assume this change won't do anything on macOS: that's probably fine, since most  low memory devices don't run macOS.

**Comment by practicalswift** [comment]
@Sjors Are you sure you are testing against the latest version (e87b991b5de7f98d3b260c44b97f154bd40a386b) which has the `ifdef`? If so, what compiler are you using?

@fanquake The 0.5 GB part is relevant and should be in the title?

**Review by promag — COMMENTED** [review]
Tests should be compiled the same way - same optimizations? Because of inlined code and templates?

**Comment by practicalswift** [comment]
@practicalswift Ideally yes, but at the cost of a +0.5 GB memory requirement? :-)

**Comment by promag** [comment]
IMHO yes.

**Comment by practicalswift** [comment]
@promag Oh, that is surprising. Care to elaborate? What potentials problems do you see? I'm not sure I follow your reasoning here TBH :-)

**Comment by promag** [comment]
I'm not saying there are problems, just that it should use the same compiler flags.

Would breaking the file help?

BTW, is the test slower?

**Comment by practicalswift** [comment]
@promag I still don't follow. What did you mean with "because of inlined code and templates"?

**Comment by promag** [comment]
Generically speaking inlined code and templates will be compiled and tested differently correct?

**Comment by practicalswift** [comment]
> Would breaking the file help?

Unfortunately not: max RSS when compiling only `script_build` is 1.2 GB.

> BTW, is the test slower?

There is no measurable difference: `script_tests/script_build` takes ~380 ms regardless of optimisation level.

**Comment by laanwj** [comment]
Concept ACK

**Comment by Sjors** [comment]
@promag afaik the compiler flags used for the test have no impact on the binary code produced for the file that's being tested. If that's the case, then there's no reason to believe that these new tests would miss any problems.

@practicalswift the warnings have gone away

 ACK d522fdd, but that only covers not breaking macOS.

**Comment by MarcoFalke** [comment]
I am not too happy about pushing and popping compiler arguments on a per-file basis.

Also, I'd first like to understand why it is using so much memory. Clang 9.0 hast `-ftime-trace`, maybe gcc has something similar.

**Comment by promag** [comment]
@Sjors I know that, see https://stackoverflow.com/questions/6364365/can-different-optimization-levels-lead-to-functionally-different-code, and considering the test file in question why risk some weird case?

Agree with @MarcoFalke regarding other approaches to reduce mem usage.

**Comment by practicalswift** [comment]
@MarcoFalke The reason for the absurd memory use is `-fvar-tracking` (in combination with `-g`). See #16331 for alternative way to handle this.

**Pull request closed without merging**
