### PR TITLE
Update libsecp256k1 subtree to latest master

### PR DESCRIPTION
**Pull request by sipa**
This updates our src/secp256k1 subtree to the latest upstream master. The changes include:

* The introduction of safegcd-based modular inverses, reducing ECDSA signing time by 25%-30% and ECDSA verification time by 15%-17%.
  * [Original paper](https://gcd.cr.yp.to/papers.html) by Daniel J. Bernstein and Bo-Yin Yang
  * [Implementation](https://github.com/bitcoin-core/secp256k1/pull/767) by Peter Dettman; [final](https://github.com/bitcoin-core/secp256k1/pull/831) version
  * [Explanation](https://github.com/bitcoin-core/secp256k1/blob/master/doc/safegcd_implementation.md) of the algorithm using Python snippets
  * [Analysis](https://github.com/sipa/safegcd-bounds) of the maximum number of iterations the algorithm needs
  * [Formal proof in Coq](https://medium.com/blockstream/a-formal-proof-of-safegcd-bounds-695e1735a348) by Russell O'Connor, for a high-level equivalent algorithm
* Removal of libgmp as an (optional) dependency (which wasn't used in the Bitcoin Core build)
* CI changes (Travis -> Cirrus)
* Build system improvements

### CODE REVIEW

**Comment by sipa** [comment]
@sipsorcery Is there a way of disabling C4146 (at least inside src/secp256k1, and at least it being treated as an error)? All these instances of negating a positive number are well-defined and intentional...

**Comment by sipsorcery** [comment]
@sipa yes the warning should be disabled by adding `<DisableSpecificWarnings>4146</DisableSpecificWarnings>` to `build_msvc\libsecp256k1\libsecp256k1.vcxproj`.

Probably clearer putting it this way: replace the `ClCompile` XML node with the below:

````
<ClCompile>   
<PreprocessorDefinitions>ENABLE_MODULE_ECDH;ENABLE_MODULE_RECOVERY;ENABLE_MODULE_EXTRAKEYS;ENABLE_MODULE_SCHNORRSIG;%(PreprocessorDefinitions)</PreprocessorDefinitions>
  <AdditionalIncludeDirectories>..\..\src\secp256k1;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
  <DisableSpecificWarnings>4146</DisableSpecificWarnings>
</ClCompile>
````

**Comment by sipa** [comment]
@sipsorcery Thanks!

**Comment by mariosanchezgarcia** [comment]
Hola soy sathosi nakamoto

**Comment by fanquake** [comment]
Concept ACK. I've completed one (pruned) sync using this branch. @jamesob want to do some benchmarking?

**Comment by sipa** [comment]
Updated to also include the now-merged https://github.com/bitcoin-core/secp256k1/pull/966.

**Comment by jamesob** [comment]
> @jamesob want to do some benchmarking?

Apologies, missed this notification. Will get some going in the next day or so.

**Comment by Sjors** [comment]
I'm running a full IBD with 5c7ee1b2da6b on mainnet with `-assumevalid=0` on macOS 11.3.1 (Intel)

**Comment by laanwj** [comment]
Added this to my FreeBSD node for testing. Configure phase and compilation goes without hitch at least.

**Comment by jamesob** [comment]
> Apologies, missed this notification. Will get some going in the next day or so.

Still planned, but debugging some build weirdness on the bench machines (bad interaction between ancient Debian and c++17 requirements).

**Comment by jamesob** [comment]
Happy to report that I'm seeing 1.07x speedup here.

ibd local range 500000 510000

### commands index
|          bench name           |                                                                     command                                                                     |
|-------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------|
| ibd.local.range.500000.510000 | `bitcoind -dbcache=300 -debug=coindb -debug=bench -listen=0 -connect=0 -addnode=127.0.0.1:8888 -prune=9999999 -printtoconsole=0 -assumevalid=0` |


### #21573 vs. $mergebase (absolute)
|                 bench name                 |  x  |           #21573            |         $mergebase          |
|--------------------------------------------|----:|-----------------------------|-----------------------------|
| ibd.local.range.500000.510000.total_secs   |   2 | 1805.3634 (± 3.2389)        | 1938.7935 (± 2.3256)        |
| ibd.local.range.500000.510000.peak_rss_KiB |   2 | 1701526.0000 (± 19670.0000) | 1720014.0000 (± 10298.0000) |


### #21573 vs. $mergebase (relative)
|                 bench name                 |  x  | #21573 | $mergebase |
|--------------------------------------------|----:|-------:|-----------:|
| ibd.local.range.500000.510000.total_secs   |   2 |      1 |      1.074 |
| ibd.local.range.500000.510000.peak_rss_KiB |   2 |      1 |      1.011 |

**Comment by sipa** [comment]
@jamesob Any possibility of measuring CPU time (as opposed to wall clock time)?

**Comment by jamesob** [comment]
Here's the second benchmark run, reporting CPU seconds:

ibd local range 500000 510000

**Comment by jamesob** [comment]
Here's the second benchmark run, reporting CPU seconds:

### #21573 vs. $mergebase (absolute)
|                  bench name                   |  x  |           #21573           |         $mergebase          |
|-----------------------------------------------|----:|----------------------------|-----------------------------|
| ibd.local.range.500000.510000.total_secs      |   2 | 1809.3671 (± 3.3923)       | 1958.0218 (± 10.2106)       |
| ibd.local.range.500000.510000.peak_rss_KiB    |   2 | 1690334.0000 (± 6038.0000) | 1703732.0000 (± 16204.0000) |
| ibd.local.range.500000.510000.cpu_kernel_secs |   2 | 315.8800 (± 0.5400)        | 328.8000 (± 5.0200)         |
| ibd.local.range.500000.510000.cpu_user_secs   |   2 | 10365.2350 (± 3.6150)      | 11663.7200 (± 12.4200)      |


### #21573 vs. $mergebase (relative)
|                  bench name                   |  x  | #21573 | $mergebase |
|-----------------------------------------------|----:|-------:|-----------:|
| ibd.local.range.500000.510000.total_secs      |   2 |      1 |      1.082 |
| ibd.local.range.500000.510000.peak_rss_KiB    |   2 |      1 |      1.008 |
| ibd.local.range.500000.510000.cpu_kernel_secs |   2 |      1 |      1.041 |
| ibd.local.range.500000.510000.cpu_user_secs   |   2 |      1 |      1.125 |

**Comment by sipa** [comment]
Anything left to do here?

**Comment by laanwj** [comment]
I don't think so.
Tested ACK 5c7ee1b2da6bf783d27034fca9dfd3a64ed525cb

**Pull request merged**
