### PR TITLE
Remove nBlockMaxSize from miner opt struct as it is no longer used.

### PR DESCRIPTION
**Pull request by gmaxwell**

### CODE REVIEW

**Comment by achow101** [comment]
utACK 22fd04beb9e7ee4c8576a2f43796200faa780938

**Review by dcousens — APPROVED** [review]

**Comment by practicalswift** [comment]
utACK 22fd04beb9e7ee4c8576a2f43796200faa780938. Nice find. Can't believe I missed this one :-)

**Comment by promag** [comment]
utACK 22fd04b.

**Comment by sdaftuar** [comment]
utACK

**Pull request merged**
