### PR TITLE
[0.16] Make signrawtransaction give an error when amount is needed but missing

### PR DESCRIPTION
**Pull request by luke-jr**
Backport of #13547 to 0.16

### CODE REVIEW

**Comment by Empact** [comment]
utACK 212ef1f

**Comment by fanquake** [comment]
utACK 212ef1f

**Comment by Sjors** [comment]
utACK 212ef1f, and functional test passes on macOS.

**Comment by laanwj** [comment]
utACK 212ef1f9547e27295a94eaa9d5ae552d858e2d9f

**Pull request merged**
