### PR TITLE
Reduce systematic error of time offset measurements

### PR DESCRIPTION
**Pull request by maflcko**
Assuming all nodes perfectly synced their clocks, `nTimeOffset` ≤ 0. This PR's commits bring it closer to zero.

### CODE REVIEW

**Comment by gmaxwell** [comment]
Our time system has a resolution of one second and huge inherent systemic errors vs UTC (e.g. we do not handle leap seconds). In blocks, latencies in the mining process usually make their times tens of seconds off (and misconfigurations make them minutes off).

The network also has infinite gain, e.g. there is no inherent bias to drive it back in sync with UTC except for corner case limitations in the correction procedure.

Fortunately, we do not use the time in any ways in which precision is important. (which is also fortunate because making it precise and consistent without centralization is an unsolved problem!)

Given that, I am not sure that an offset of even as much as 20000 microseconds is at all interesting.

Are you aware of a case where this matters?

**Comment by gmaxwell** [comment]
I did a cursory check for step 6 side effects having any effect before the end. Before accepting that change a more careful examination should be done in review.   I think deferring binding until later in setup is likely reasonable regardless of the timing handling.

**Comment by MarcoFalke** [comment]
Indeed, e12d0ad is relevant only in less than 0.5%, correcting the insignificant one second offset on my machine.

To check if 0ac42c4 works, you could pick a server with a public IP address which some other nodes actively try to connect to. Then just restart the server (or even do something costly like reindex). In the meantime you can see the other nodes `PushVersion()` to your server. So `nTimeOffset = ` whatever it took you to reindex, etc.

**Comment by laanwj** [comment]
As it is not clear to me what practical issue this solves - the time sync logic is a bit dodgy in the first place, and as @gmaxwell already says absolute precision is not important for our use caes - I'm not willing to take the risk of breaking the initialization sequence, sorry.

**Pull request closed without merging**
