### PR TITLE
Trivial: s/SetBestChain/ChainStateFlushed in comments after #13106

### PR DESCRIPTION
**Pull request by ryanofsky**

### CODE REVIEW

**Comment by fanquake** [comment]
utACK 21f5680

**Comment by promag** [comment]
utACK 21f5680.

**Comment by laanwj** [comment]
Gah, apparently the script in 50b6533aa2a9ccbc758aaf5a9f6dfa1c9433bff1 didn't cover these.
```
    -BEGIN VERIFY SCRIPT-
    sed -i 's/SetBestChain/ChainStateFlushed/g' src/validationinterface.h src/validationinterface.cpp src/wallet/wallet.h src/wallet/wallet.cpp src/validation.cpp src/index/txindex.h src/index/txindex.cpp
    -END VERIFY SCRIPT-
```

**Comment by practicalswift** [comment]
utACK 21f56805531c4b2954d0aaffa34c83f37ed8f9c0

**Comment by laanwj** [comment]
> Yeah, imo git grep -l foo ./src/ is less fragile than hardcoding all the file names.

Yes, though, please use `git ls-files` in that case otherwise it'll search/replace in executables and IDE metadata files unrelated to git too...

**Comment by practicalswift** [comment]
@laanwj `git grep` will only search in the repo, right? :-)

**Comment by laanwj** [comment]
@practicalswift You're right, that's what it does by default, forgot about that.

**Pull request merged**
