### PR TITLE
0.16: Remaining backports for 0.16.2

### PR DESCRIPTION
**Pull request by maflcko**
Some gui/doc/rpc/qa backports

### CODE REVIEW

**Comment by fanquake** [comment]
Looks like this is missing #13452 and #13437 ?

**Comment by MarcoFalke** [comment]
@fanquake thanks. I will go through all master changes again and then include those two as well (and any other I find on the way)

**Comment by gmaxwell** [comment]
ACK

**Comment by luke-jr** [comment]
Missing:

* **#12859 (somewhat important): Bugfix: Include <memory> for std::unique_ptr**
* #12432: [qt] send: Clear All also resets coin control options
* #12573: Fix compilation when compiler do not support __builtin_clz*
* #12617: gui: Show messages as text not html
* #12743: Fix csBestBlock/cvBlockChange waiting in rpc/mining
* #12793: qt: Avoid reseting on resetguisettigs=0
* #13149: Handle unsuccessful fseek(...):s

**Comment by MarcoFalke** [comment]
> #12859 (somewhat important): Bugfix: Include for std::unique_ptr
> #12793: qt: Avoid reseting on resetguisettigs=0

Both are included. Thanks, will look at the remaining ones...

**Comment by MarcoFalke** [comment]
Done

**Comment by gmaxwell** [comment]
ACK

**Comment by fanquake** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/13644/commits/21dd5127a423f38712dcdcef4002e714e8276bd2

**Comment by sipa** [comment]
utACK d9c563095d71055ff054d3a27e11a12d3d1ec92f

**Comment by gmaxwell** [comment]
re-ACK

**Comment by fanquake** [comment]
re-utACK d9c5630

**Comment by laanwj** [comment]
utACK d9c563095d71055ff054d3a27e11a12d3d1ec92f

**Pull request merged**
