### PR TITLE
[build] rename movies to animation

### PR DESCRIPTION
**Pull request by Bushstar**
Rename the movies directory and RES_MOVIES make variable to animation and RES_ANIMATION respectively. Movies is a bit of an unexpected term to be found.

### CODE REVIEW

**Comment by hebasto** [comment]
Mind place it to https://github.com/bitcoin-core/gui ?

**Comment by Bushstar** [comment]
@hebasto Will do. Not seen that repo before.

**Comment by laanwj** [comment]
~0 on this, but if you really want to change this all over the repository in a shitton of files, I think this should be a scripted diff.
See https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md#scripted-diffs

**Comment by hebasto** [comment]
@Bushstar 
> Not seen that repo before.

#19071

**Comment by Bushstar** [comment]
@hebasto thanks. I'll close this PR and create one on gui using a scripted diff.

**Pull request closed without merging**
