### PR TITLE
ci: Bump CentOS 8 image

### PR DESCRIPTION
**Pull request by maflcko**
CentOS 8 was just shut down:

```
$ pob centos:8 
[root_e606059da4d9 /]# dnf update
Failed to set locale, defaulting to C.UTF-8
CentOS Linux 8 - AppStream
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
```

Fix that by bumping the image.

### CODE REVIEW

**Comment by hebasto** [comment]
Concept ACK, [considering](https://www.centos.org/cl-vs-cs/):
> - CentOS Linux 8 EOL: 2021-12-31
> - CentOS Stream 8 EOL: 2024-05-31

**Comment by fanquake** [comment]
```bash
  zeromq-4.3.4-2.el8.x86_64                                                     
Removed:
  coreutils-single-8.30-12.el8.x86_64                                           

Complete!
bash: free: command not found

Exit status: 127
```

**Comment by MarcoFalke** [comment]
Trying with procps-ng ...

**Comment by MarcoFalke** [comment]
```
Building libevent...
make[1]: Entering directory '/tmp/cirrus-ci-build/depends/work/build/i686-pc-linux-gnu/libevent/2.1.12-stable-dbc4e9c2bf0'
make[1]: -c: Command not found
make[1]: *** [Makefile:1425: config.h] Error 127
make[1]: Leaving directory '/tmp/cirrus-ci-build/depends/work/build/i686-pc-linux-gnu/libevent/2.1.12-stable-dbc4e9c2bf0'
make: *** [funcs.mk:282: /tmp/cirrus-ci-build/depends/work/build/i686-pc-linux-gnu/libevent/2.1.12-stable-dbc4e9c2bf0/./.stamp_built] Error 2
make: Leaving directory '/tmp/cirrus-ci-build/depends'
Exit status: 2

**Comment by hebasto** [comment]
@MarcoFalke 

`libevent` build can be fixed with the following patch:
```diff
--- a/ci/test/05_before_script.sh
+++ b/ci/test/05_before_script.sh
@@ -47,7 +47,7 @@ if [[ $HOST = *-mingw32 ]]; then
   DOCKER_EXEC update-alternatives --set "${HOST}-g++" \$\(which "${HOST}-g++-posix"\)
 fi
 if [ -z "$NO_DEPENDS" ]; then
-  if [[ $DOCKER_NAME_TAG == centos* ]]; then
+  if [[ $DOCKER_NAME_TAG == *centos* ]]; then
     # CentOS has problems building the depends if the config shell is not explicitly set
     # (i.e. for libevent a Makefile with an empty SHELL variable is generated, leading to
     #  an error as the first command is executed)
```

**Comment by Sjors** [comment]
utACK fafc55a with the caveat that I've never used CentOS.

**Comment by MarcoFalke** [comment]
Just to give some more context:

* Only the first commit is needed as a bug fix
* The second commit is an unrelated rename. docker->ci, since it is possible to run the ci without docker
* The third commit makes sense because we use the centos build to test with `dash`

**Comment by fanquake** [comment]
Being backported in #24256.

**Pull request merged**
