### PR TITLE
docs: correctly identify script type

### PR DESCRIPTION
**Pull request by niftynei**
Fix a typo.

### CODE REVIEW

**Comment by sipa** [comment]
ACK 4ed064dbd90b5f254c4637e8f820c75225958f1f

**Review by darosior — APPROVED** [review]
ACK 4ed064dbd90b5f254c4637e8f820c75225958f1f

**Review by theStack — APPROVED** [review]
ACK 4ed064dbd90b5f254c4637e8f820c75225958f1f

**Review by sanket1729 — APPROVED** [review]
utack 4ed064dbd90b5f254c4637e8f820c75225958f1f

**Pull request merged**
