### PR TITLE
Aligning tests with the supply algorithm.

### PR DESCRIPTION
**Pull request by ghost**
This is a refactoring of #5925, the least we can do to follow best practices on the testing side (à la TDD, tests shouldn't be enforcing improper, consensus-conflicting, behavior).

Hence, this PR is limited to test corrections only, setting up the stage for MAX_MONEY refactoring at some future point in time as per sipa's suggestion.

### CODE REVIEW

**Comment by paveljanik** [comment]
NACK, sorry. I do not think it is worth to touch this (the reasoning is all written in #5925).

**Comment by sipa** [comment]
How about we rename MAX_MONEY to AMOUNT_OVERFLOW_PROTECTION_THRESHOLD? Can
we do then stop discussing the precise semantics of the maximum money
constant?

**Comment by laanwj** [comment]
Fully agree with @sipa, couldn't have worded it better.

**Comment by 21E14** [comment]
@sipa Sounds great. Please refer to #6197 for implementation.

**Pull request closed without merging**
