### PR TITLE
Updated more NULL -> nullptr

### PR DESCRIPTION
**Pull request by mxaddict**
I noticed most CPP code already use nullptr

### CODE REVIEW

**Comment by mxaddict** [comment]
@fanquake I've checked the travis error, but I'm confused what the error means:

```
FAIL: subtree directory was touched without subtree merge
```

**Comment by MarcoFalke** [comment]
Subtrees need to be updated upstream. Please refer to the markdown docs in this repo

**Comment by mxaddict** [comment]
@MarcoFalke I see, is there a reason why these are not loaded as submodules?

**Comment by MarcoFalke** [comment]
I think they are the same (c.f. https://stackoverflow.com/a/35549033/2084795)

**Pull request closed without merging**
