### PR TITLE
[trivial] update comments for tx weight

### PR DESCRIPTION
**Pull request by carryforward**
https://github.com/bitcoin/bitcoin/commit/2c06bae39edfaa9c0855d83377ad8fda09e4fa08 missed a couple comments.  This corrects/clarifies the stragglers.

### CODE REVIEW

**Comment by instagibbs** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/9155/commits/07ede5d711e7fd601770c1f57110830bf540f0bc

Can confirm it's the last 2 instances of the constant.

**Comment by MarcoFalke** [comment]
utACK 07ede5d711e7fd601770c1f57110830bf540f0bc

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/commit/07ede5d711e7fd601770c1f57110830bf540f0bc

**Comment by sipa** [comment]
utACK 07ede5d711e7fd601770c1f57110830bf540f0bc

**Comment by fanquake** [comment]
utACK 07ede5d

**Pull request merged**
