### PR TITLE
Add Cirrus CI build status

### PR DESCRIPTION
**Pull request by willianpaixao**
It's a simple addition of the badge with build status.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Hmmm, I am not sure what the point is of adding this to the Readme. Locally you can't or wouldn't want to render this. On GitHub there is already a status attached to every commit.

**Comment by willianpaixao** [comment]
Hi @MarcoFalke, thanks for the fast feedback.

The README.md is not for locally rendering, but for someone entering this repository. There, devs can have a summary of what's the project's current status. Having a build badge in the README is a best-practice widely adopted here in Github.

The per-commit status you mentioned is useful for a core developer interested in checking whether their latest push is successful, which is also very important, but not the same as the badge in the README. In essence, no non-core developer will navigate to the latest commit or to the Cirrus website (which I just had to do, hence this PR) to check if the project is correctly building.

**Comment by MarcoFalke** [comment]
All our branches should always compile/build. There might be some exceptions on the development master branch in case of silent merge conflicts, but they are rare and discovered quickly. Build failures never happened (to my knowledge) on release branches or tagged releases. So I think adding the badge is not needed.

Moreover, the CI has "natural" false positives and the badge will turn red on some days due to issues not related to the build status or even unrelated to our source code at all. So adding the badge will just send false signals.

Finally, I think non-developers shouldn't be building from master. Generally it is recommended to build the release tags/branches.

**Comment by willianpaixao** [comment]
> All our branches should always compile/build

I wish life was that easy. 😅 

> Build failures never happened (to my knowledge) on release branches or tagged releases.

That's great! But if you note in the PR I specify builds in the master branch, since it's what we want to track when contributing to the project.

> Moreover, the CI has "natural" false positives

Then it's a case of fixing those corner cases rather than hiding the badge.

> Finally, I think non-developers shouldn't be building from master

You misread me. I said non-core developers. It's someone that is very likely a developer and wants to contribute with code but is not part of the Bitcoin Core organization.

**Comment by jarolrod** [comment]
Concept 0 on this. 

This badge being on the `README.md` doesn't really provide any meaningful information to core developers or periphery developers. Also we'd have instances where it may turn `Failing` because of false positives/test timeouts.

**Comment by MarcoFalke** [comment]
All branches build fine right now, but all CI failed on this. This is an upstream bug and there is nothing we can do about that in our repo.

**Comment by MarcoFalke** [comment]
@willianpaixao Thank you for your interest in contributing to Bitcoin Core. If you want to make meaningful contributions, I've collected some pointers for you.

## Getting started to contribute to Bitcoin Core

### Setting up your development environment

New developers are very welcome and needed. There are a lot of open issues of any difficulty waiting to be fixed. However, before you start contributing, familiarize yourself with the Bitcoin Core build system and tests. Refer to the documentation in the repository on how to build Bitcoin Core and how to run the unit and functional tests. Once that is done, you are all set.

If you need more help getting started, please refer to the following resources:

* https://medium.com/@amitiu/onboarding-to-bitcoin-core-7c1a83b20365
* https://jonatack.github.io/articles/how-to-review-pull-requests-in-bitcoin-core

### Pick something to work on

If you are looking for useful contributions to help out with, you can

* Search through the [good first issue](https://github.com/bitcoin/bitcoin/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)s or the ones that are [up for grabs](https://github.com/bitcoin/bitcoin/issues?utf8=%E2%9C%93&q=label%3A%22Up+for+grabs%22). Some of them might no longer be applicable. So if you are interested, but unsure, you might want to leave a comment on the issue first.
* Write tests to improve the coverage. Any kind of test is welcome and coverage information can be obtained from a relatively recent [coverage report](https://marcofalke.github.io/btc_cov). If you are unsure, don't hesitate to check back first.
* Help with review and testing. There are easy ones such as the [gui](https://github.com/bitcoin/bitcoin/pulls?q=is%3Apr+is%3Aopen+label%3AGUI) and [rpc](https://github.com/bitcoin/bitcoin/pulls?q=is%3Apr+is%3Aopen+label%3ARPC%2FREST%2FZMQ). However, review on any open pull request is welcome. Review will also help you understand the codebase better.
* Help on meta projects related to Bitcoin Core, such as a [high-level performance monitor](https://github.com/chaincodelabs/bitcoinperf).
* Join us on irc and let us know what you are interested in.

**Pull request closed without merging**
