### PR TITLE
cli: replace testnet with chain and return network name as per BIP70.

### PR DESCRIPTION
**Pull request by fanquake**
Related IRC discussion [here (line 151)](http://www.erisian.com.au/bitcoin-core-dev/log-2019-03-09.html).

### CODE REVIEW

**Comment by luke-jr** [comment]
Shouldn't we retain "testnet" for compatibility, for now?

**Comment by laanwj** [comment]
> Shouldn't we retain "testnet" for compatibility, for now?

Now that it's client-side, IMO there's no strict need for keeping compatibility at all (you could always use a different `bitcoin-cli` executable). We've already let this linger for way too long.

**Comment by laanwj** [comment]
ACK 890396cbd504b4670597d39ecb037e69ffb8bd3e

**Comment by MarcoFalke** [comment]
ACK 890396c

**Comment by Empact** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/15566/commits/890396cbd504b4670597d39ecb037e69ffb8bd3e

nit: I also like the idea of explicit deprecation

**Comment by IlyasRidhuan** [comment]
ACK 890396c

**Pull request merged**
