### PR TITLE
depends: update `LD64_VERSION` to 711

### PR DESCRIPTION
**Pull request by fanquake**
I forgot to do this in https://github.com/bitcoin/bitcoin/commit/7d5815293ed8a3dea68b61a78944e410f02b147f.
Add a test so it's impossible to forget.

### CODE REVIEW

**Comment by TheCharlatan** [comment]
Damn, should have caught this :(
utACK 092daa2f9524e371ee6b505519d9b722a2c6361a

**Comment by hebasto** [comment]
> Add a test so it's impossible to forget.

Why not derive the `LD64_VERSION` value directly from the linker:
```
$ ./depends/x86_64-apple-darwin/native/bin/x86_64-apple-darwin-ld -v
@(#)PROGRAM:ld  PROJECT:ld64-711
BUILD 09:08:42 Oct 11 2023
configured to support archs: armv6 armv7 armv7s arm64 arm64e arm64_32 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em (tvOS)
LTO support using: LLVM version 15.0.7 (static support for 29, runtime is 29)
TAPI support using: TAPI version 1300.6.5 (1300.6.5)
```

**Review by jarolrod — COMMENTED** [review]
ACK 092daa2f9524e371ee6b505519d9b722a2c6361a

**Comment by fanquake** [comment]
> Why not derive the LD64_VERSION value directly from the linker:

That would prevent us from being able to set it to anything other than the exact value output by -v.

Also unsure if whatever parsing code you write would also be compatible with lld.

**Comment by hebasto** [comment]
> Add a test so it's impossible to forget.

The test passes with the [first](https://github.com/bitcoin/bitcoin/commit/cefbf0bc20dfe932240877b3096300c8c241ad61) commit been reverted.

**Comment by fanquake** [comment]
> The test passes with the [first](https://github.com/bitcoin/bitcoin/commit/cefbf0bc20dfe932240877b3096300c8c241ad61) commit been reverted.

The because if unset, the value is the default linker version, iirc.

**Comment by hebasto** [comment]
> > The test passes with the [first](https://github.com/bitcoin/bitcoin/commit/cefbf0bc20dfe932240877b3096300c8c241ad61) commit been reverted.
> 
> The because if unset, the value is the default linker version, iirc.

How is it unset?

**Comment by fanquake** [comment]
> How is it unset?

If the test is still passing, clearly it's not being set to 609. Otherwise it would fail.

**Comment by hebasto** [comment]
> > How is it unset?
> 
> If the test is still passing, clearly it's not being set to 609. Otherwise it would fail.

Please consider https://github.com/hebasto/bitcoin/tree/pr28630/1011.

the `LD64_VERSION` is [still set](https://github.com/hebasto/bitcoin/blob/pr28630/1011/depends/hosts/darwin.mk#L5) to the wrong value::
```
LD64_VERSION=609
```

but the Guix build succeeds:
```
8fdacd899e61f2314c1645c787b409197a9783a33994fc2707cd654ae10760fc  guix-build-4e68bd5325ea/output/dist-archive/bitcoin-4e68bd5325ea.tar.gz
830188b61fa795e496ccf38c80900b5ee778ba2bea30f27552db046d738a5ca2  guix-build-4e68bd5325ea/output/x86_64-apple-darwin/SHA256SUMS.part
ca3cf7f40f4ea85c7cf72abba47f25a509243977a587c2c1d9e6d2c6135099f7  guix-build-4e68bd5325ea/output/x86_64-apple-darwin/bitcoin-4e68bd5325ea-x86_64-apple-darwin-unsigned.tar.gz
0517f0faf2abc3b07d3909f5f4e4e588159105f5d481065b36902d27b043f59c  guix-build-4e68bd5325ea/output/x86_64-apple-darwin/bitcoin-4e68bd5325ea-x86_64-apple-darwin-unsigned.zip
51ada364ee1f37ad792d3b8d03230ac3896f5b2dbff469c1c2b411ad9f94fe1f  guix-build-4e68bd5325ea/output/x86_64-apple-darwin/bitcoin-4e68bd5325ea-x86_64-apple-darwin.tar.gz
```

**Comment by fanquake** [comment]
We don't need another branch. I'm saying the same thing. If the test is passing, clearly the value in the binary is not being set to 609 (in which case, it's being set to the default linker value (711)).

**Comment by hebasto** [comment]
> We don't need another branch. I'm saying the same thing. If the test is passing, clearly the value in the binary is not being set to 609 (in which case, it's being set to the default linker value (711)).

If code has `LD64_VERSION=609` and the test passes, what is the purpose of the test then?

**Comment by fanquake** [comment]
> what is the purpose of the test then?

To check for the version being used/embedded? Clearly it's exposed a bug here, potentially in our understanding of `-mlinker-version`.

**Review by hebasto — APPROVED** [review]
ACK 092daa2f9524e371ee6b505519d9b722a2c6361a.

Suggesting to drop "Add a test so it's impossible to forget." from the PR description before merging.

> Clearly it's exposed a bug here, potentially in our understanding of `-mlinker-version`.

Agree.

**Review by laanwj — APPROVED** [review]
ACK 092daa2f9524e371ee6b505519d9b722a2c6361a
i dont know about mac linker specifics but reviewed symbol-check.py change and lgtm

**Comment by jarolrod** [comment]
GUIX hashes

```
1451e9cdec787f51604257ce8810be020a3abc8e307474643f79fbb55e403584  guix-build-092daa2f9524/output/arm64-apple-darwin/SHA256SUMS.part
4ffd62b263db859059840dbb2c8602c187d39ba98b8241135a09f54dba0ec4ea  guix-build-092daa2f9524/output/arm64-apple-darwin/bitcoin-092daa2f9524-arm64-apple-darwin-unsigned.tar.gz
b479787d21ac0defabaccc804e4400d13ea51d73557c1fe9483aa2fd3b536b96  guix-build-092daa2f9524/output/arm64-apple-darwin/bitcoin-092daa2f9524-arm64-apple-darwin-unsigned.zip
fe4e5d623e8ddee89414f5d6c5b370280769f8aadc495af4ed3c464499ec9cb0  guix-build-092daa2f9524/output/arm64-apple-darwin/bitcoin-092daa2f9524-arm64-apple-darwin.tar.gz
714f9980e48a01f6ef8655d7f89a208201d2fb96038905de0e997c0c1f12fe68  guix-build-092daa2f9524/output/dist-archive/bitcoin-092daa2f9524.tar.gz
23588af64e1b7019b237810c68df6750517b41df8c48b061147cafdb40408f5a  guix-build-092daa2f9524/output/x86_64-apple-darwin/SHA256SUMS.part
1634732934ee01803adc84e5ba9f5e56579bff237b8aac8ac1882b02e2f64920  guix-build-092daa2f9524/output/x86_64-apple-darwin/bitcoin-092daa2f9524-x86_64-apple-darwin-unsigned.tar.gz
c4dddc491901fe8ea112eb146a4bb9351797c5d8dfc0b8e84e2b548d01ae938e  guix-build-092daa2f9524/output/x86_64-apple-darwin/bitcoin-092daa2f9524-x86_64-apple-darwin-unsigned.zip
2d5876eb31f2cfa32228029fb20851c1ad43c2c36c3870254db94b1da86e9d58  guix-build-092daa2f9524/output/x86_64-apple-darwin/bitcoin-092daa2f9524-x86_64-apple-darwin.tar.gz
```

**Comment by achow101** [comment]
ACK 092daa2f9524e371ee6b505519d9b722a2c6361a

**Pull request merged**
