### PR TITLE
refactor: deduplicate AmountFromValue() functions

### PR DESCRIPTION
**Pull request by jonatack**
It makes sense to deduplicate this logic and merge it to a single point of truth.

Reviewers mentioned this in the thread at https://github.com/bitcoin/bitcoin/pull/19092#discussion_r436443371, where I wanted to use `AmountFromValue()` in `bitcoin-cli.cpp`, making yet another (third) copy of that same function.

### CODE REVIEW

**Review by bitcoinfinancier — APPROVED** [review]

**Comment by fanquake** [comment]
Also not sure. This might remove the duplicate `AmountFromValue` from bitcoin-tx, but instead we end up with an extra wrapper function in rpc/util.h?

Generally, I think that anytime you're putting the return type of a function into it's name, something is going a bit wrong. Given in this case it's because we've already got a function called `AmountFromValue`, someone might ask why not just refactor that to return `util::Result`, instead of adding a new layer of indirection.

**Review by stickies-v — COMMENTED** [review]
I think I'm approach NACK. A lot of change, and a more cluttered `rpc/util` interface just for the sake of removing this function from `bitcoin-tx`.

Isn't something like this a lot less overhead, if this is something we want to improve? https://github.com/stickies-v/bitcoin/commit/d5130411219e1f7f2791663eb22f3f4213a325ed . I'm not sure introducing the `rpc/util.h` dependency is even worth it, but that's happening in this implementation too so at least that's not worse.

**Comment by stickies-v** [comment]
Also nit: I don't understand why 709acdc359edbdc7afed15d12278cfc24220376b and 072af572b41d840a2ca53ffb3c8a1613dd4610c4 are 2 commits, that's just making review more difficult?

**Comment by fanquake** [comment]
What's the status of this? Seems to have 2 `~0` and an approach NACK.

**Comment by fanquake** [comment]
> I'll re-look at the implementation here and see if it can be improved, or extracted to its own file.

Ok. Marked as a draft for now then.

**Pull request closed without merging**
