### PR TITLE
tracing: utxocache tracepoints follow up for #22902

### PR DESCRIPTION
**Pull request by arnabsen1729**
This PR is a follow-up to the [#22902](https://github.com/bitcoin/bitcoin/pull/22902). 

Previously, the tracepoint `utxocache:flush` was called, even when it was not flushing. So, the tracepoint is now scoped to write only when coins cache to disk.

### CODE REVIEW

**Comment by fanquake** [comment]
cc @0xB10C @jb55 @laanwj

**Comment by 0xB10C** [comment]
Concept ACK. These are important fixups and followups to #22902. Will review and test this.

The `utxocache` tracepoints still require manual testing before this PR is merged as #22902 didn't receive throughout testing.

**Comment by jb55** [comment]
Concept ACK

**Comment by 0xB10C** [comment]
Added a bitcoind.observer dashboard based on the flush and add/spent/uncache tracepoints to observe their behavior a bit: https://bitcoind.observer/d/beTN4K27z/utxo-cache (this is currently running a pruned IBD and the UTXO cache is flushed for pruning before it reaches it's maximum capacity -- see #20827)

**Comment by 0xB10C** [comment]
My site currently is currently only picking up flushes related to a prune event. I'll investigate.

**Comment by 0xB10C** [comment]
Could add a note in the `utxoscache:uncache`, `utxoscache:add`, and `utxocache:spent` tracepoint documentation that we don't have only one 'the utxo cache'. We sometimes work with temporary UTXO caches. For example, in `TestBlockValidity()` after mining or during mempool consistency checks (frequent on regtest).

**Comment by arnabsen1729** [comment]
> Could add a note in the `utxoscache:uncache`, `utxoscache:add`, and `utxocache:spent` tracepoint documentation that we don't have only one 'the utxo cache'. We sometimes work with temporary UTXO caches. For example, in `TestBlockValidity()` after mining or during mempool consistency checks (frequent on regtest). Tracepoints are triggered for temporary caches too. Noticed this while writing functional tests for the tracepoints.

Okay, will update the docs :+1:

**Comment by 0xB10C** [comment]
Feel free to squash this commit https://github.com/0xB10C/bitcoin/commit/287351a80193a24c84a245989ffa2403c15c78fe documenting this https://github.com/bitcoin/bitcoin/pull/23907#issuecomment-1033967515 into the `tracing: misc follow-ups to 22902` too (while copying the commit subject and description into the squash commit description).

---

I've cherry picked the commits from #24358 (tracepoint tests) onto this PR (currently `git cherry-pick 1e8aa02ec5cc2819c67ef40a7573c4b23a4c11cc..db3a05f50ee5d3cafa226882eade531a7ebff6b1`; [0xB10C/bitcoin:2022-02-23907+tracepoint-tests](https://github.com/0xB10C/bitcoin/tree/2022-02-23907%2Btracepoint-tests)) to run the tracepoint tests against this PR. Tests pass!

**Review by 0xB10C — APPROVED** [review]
ACK 799968e8b38833dc7fd7b6d488a66a14580ef674

Code and doc changes reviewed. Tested with #24358.

**Pull request merged**
