### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by practicalswift**
Fix typos:
* "poicy" → "policy" (introduced in 1fafd704dac73594f69de5f9c15f697217653d7a)
* "serializeable" → "serializable" (introduced in 3babbcb48786372d4b22171674c4cc5a6220c294)

### CODE REVIEW

**Comment by practicalswift** [comment]
Friendly ping @morcos and @gmaxwell :-)

**Comment by morcos** [comment]
utACK

**Comment by paveljanik** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/10833/commits/0189d8ed19eb435f7b355bb482ec748195a2c0b3

**Comment by sipa** [comment]
utACK 0189d8ed19eb435f7b355bb482ec748195a2c0b3

**Pull request merged**
