### PR TITLE
wallet: Use fsbridge::ifstream to fix Windows path issue

### LINKED ISSUE #15460: Some functional tests fail on native windows when tempdir has unicode chars in the path
The following tests are not emoji-safe:

```
TEST                     | STATUS    | DURATION

feature_config_args.py   | ✖ Failed  | 17 s
feature_includeconf.py   | ✖ Failed  | 11 s
interface_bitcoin_cli.py | ✖ Failed  | 8 s
wallet_multiwallet.py    | ✖ Failed  | 6 s

ALL                      | ✖ Failed  | 42 s (accumulated) 
Runtime: 17 s
```

### PR DESCRIPTION
**Pull request by ken2812221**
Fix #15460

### CODE REVIEW

**Comment by ken2812221** [comment]
image

**Comment by laanwj** [comment]
utACK 6ad79cbd562d04ebbcb61c774fb3389e70fedb7c

**Review by ryanofsky — APPROVED** [review]
utACK 6ad79cbd562d04ebbcb61c774fb3389e70fedb7c. I was going to suggest that maybe there should be a linter only allowing use of `fsbridge::ifstream`, and not other `ifstream` classes. But this might be too strict because in a lot of cases we can know that filename being opened is ascii.

**Comment by fanquake** [comment]
utACK 6ad79cb

**Comment by laanwj** [comment]
> I was going to suggest that maybe there should be a linter only allowing use of `fsbridge::ifstream`, and not other `ifstream` classes.

File system access should always go through the fsbridge when possible, this is better for sandboxing. So I think this would be appropriate, as well as mentioning this in the developer notes of course.
(but not in this PR)

**Pull request merged**
