### PR TITLE
Remove outdated share/certs/ directory

### PR DESCRIPTION
**Pull request by meshcollider**
The directory hasn't been touched for 5 years (other than a couple of typo fixes/renaming). The certificates are expired, the build process notes are out of date, especially with the gitian building and everything, Gavin no longer has anything to do with it, etc.

The signing process is all documented (and scripted) elsewhere (e.g. doc/release-process.md and gitian-building.md, contrib/macdeploy and windeploy), this can just be removed

@theuni can confirm if this is okay, we discussed it on IRC for a bit :)

### CODE REVIEW

**Comment by fanquake** [comment]
utACK 6951a1c

**Comment by practicalswift** [comment]
utACK 6951a1c6758ab642ef99f93c8d6a43f1b72214cb

**Comment by theuni** [comment]
utACK. The current process is described in the release process doc.

**Comment by laanwj** [comment]
Eh yes, good catch.

**Comment by jonasschnelli** [comment]
ACK 6951a1c6758ab642ef99f93c8d6a43f1b72214cb

**Comment by achow101** [comment]
I think that BitcoinFoundation_Apple_Cert.pem should be moved to `contrib/macdeploy` since it is the cert used for signing MacOS releases although it is not the full chain in a format like the certs in `contrib/windeploy`

**Comment by laanwj** [comment]
@achow101 I'll leave it to @theuni to add it anywhere else, if necessary, but I doubt that old cert is still the one used anywhere.

**Comment by achow101** [comment]
@laanwj It is the same cert: https://botbot.me/freenode/bitcoin-core-dev/2017-09-21/?msg=91373405&page=1 (IRC discussion about this)

**Comment by MarcoFalke** [comment]
Given that the certificate expires before the next release, I don't see the need to move it around.

Anyway, what are the plans for signing upcoming releases?

**Pull request merged**
