### PR TITLE
QA: Expect PACKAGE_NAME rather than constant "Bitcoin Core"

### PR DESCRIPTION
**Pull request by luke-jr**
Followup to #29144

### CODE REVIEW

**Comment by kevkevinpal** [comment]
ACK [197b540](https://github.com/bitcoin/bitcoin/pull/30308/commits/197b5404b0f4a1d6e989000845b45c8bd24e0bc6)

we're doing this in these files aswell so seems fine to me
```
test/functional/wallet_multiwallet.py 
test/functional/tool_wallet.py 
test/functional/interface_bitcoin_cli.py 
test/functional/feature_filelock.py
```

**Comment by kevkevinpal** [comment]
I see we're doing something similar in `./test/functional/wallet_backwards_compatibility.py` 

```
node_v17.assert_start_raises_init_error(["-wallet=w3"], "Error: Error loading w3: Wallet requires newer version of Bitcoin Core")

and

node_v16.assert_start_raises_init_error([f"-wallet={wallet_name}"], f"Error: Error loading {wallet_name}: Wallet requires newer version of Bitcoin Core")
```

not sure if you want to update here aswell in this PR

**Review by tdb3 — APPROVED** [review]
ACK 197b5404b0f4a1d6e989000845b45c8bd24e0bc6
grepped for other instances of `Bitcoin Core` in test/functional/ and didn't see any beyond what @kevkevinpal identified.

**Comment by fanquake** [comment]
> not sure if you want to update here aswell in this PR

@luke-jr can you update this PR to include the additional changes.

**Comment by luke-jr** [comment]
>It can be changed just for consistency, and to prevent similar issues in future when devs copy-paste code.

Changing it would *break* that test.

I don't think there's anything more to do here at the moment. (CI is a good idea, but seems suited to a different PR)

**Review by nehtech9 — APPROVED** [review]

**Pull request merged**
