### PR TITLE
qt: use CHashWriter also in SignVerifyMessageDialog

### PR DESCRIPTION
**Pull request by ghost**
This eliminates unnecessary copying of data being hashed.

### CODE REVIEW

**Comment by laanwj** [comment]
It doesn't shave off much code, but looks like a better fit, yes. utACK

**Comment by laanwj** [comment]
Having some more explanation in the commit message would be nice though!

**Comment by sipa** [comment]
utACK

**Comment by rat4** [comment]
Added an explanation.

**Comment by jonasschnelli** [comment]
utACK.

**Pull request merged**
