### PR TITLE
cli: remove duplicate wallet fields from -getinfo

### PR DESCRIPTION
**Pull request by fanquake**
`walletversion` and `balance` are both included below.

### CODE REVIEW

**Comment by laanwj** [comment]
ACK 3f6568d66b42bd151b26df3bd84c64959bbe3fc9

**Comment by MarcoFalke** [comment]
ACK 3f6568d66b42bd151b26df3bd84c64959bbe3fc9

**Comment by IlyasRidhuan** [comment]
ACK 3f6568d

**Comment by promag** [comment]
ACK 3f6568d.

**Comment by Empact** [comment]
utACK 
https://github.com/bitcoin/bitcoin/pull/15564/commits/3f6568d66b42bd151b26df3bd84c64959bbe3fc9

**Pull request merged**
