### PR TITLE
Mention Linux ARM executables in release process and notes

### PR DESCRIPTION
**Pull request by laanwj**
Did I forget any place?

One of #7678.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
utACK 877ad71. Will test on rc1

**Comment by laanwj** [comment]
Also probably requires a change to the download page on bitcoin.org: https://github.com/bitcoin-dot-org/bitcoin.org/issues/1315

**Comment by fanquake** [comment]
Maybe add `aarch64-linux-gnu` to the `host-platform-triplets` list in depends/README.md? Otherwise ACK

**Comment by laanwj** [comment]
> Maybe add aarch64-linux-gnu to the host-platform-triplets list in depends/README.md? 

Good idea.

**Pull request merged**
