### PR TITLE
 bitcoin-tx: Reject non-integral and out of range int strings

### PR DESCRIPTION
**Pull request by maflcko**
Seems odd to silently accept arbitrary strings that don't even represent integral values.

Fix that.

### CODE REVIEW

**Review by promag — COMMENTED** [review]
Code review ACK fa334a8765a88f18e7a63d908b672b27343d8219.

My only suggestion is to create a helper to avoid duplicate code, like:
```cpp
template <typename T>
T ParseIntegral(const std::string& str, const std::string& error_msg)
{
    const auto parsed{ToIntegral<T>(TrimString(str))};
    if (!parsed.has_value()) {
        throw std::runtime_error(error_msg + " '" + str + "'");
    }
    return parsed.value();
}
```

**Comment by MarcoFalke** [comment]
Thanks, done

**Review by promag — COMMENTED** [review]
Code review ACK fa6f29de516c7af5206b91b59ada466032329250.

**Comment by practicalswift** [comment]
cr ACK fa6f29de516c7af5206b91b59ada466032329250

**Comment by laanwj** [comment]
Code review fa6f29de516c7af5206b91b59ada466032329250

**Pull request merged**
