### PR TITLE
test: Add missing call to skip_if_no_cli()

### PR DESCRIPTION
**Pull request by practicalswift**
Add missing call to `skip_if_no_cli()` as suggested by @MarcoFalke in #14365.

### CODE REVIEW

**Comment by ken2812221** [comment]
utACK db01839361ae01201c27d3a96f6346d76a8314e0. 
Could you also change `.appveyor.yml` from `@BUILD_BITCOIN_UTILS_TRUE@` to `@BUILD_BITCOIN_CLI_TRUE@`?
https://github.com/bitcoin/bitcoin/blob/1e8f88e071019907785b260477bd359bef6f9a8f/.appveyor.yml#L49

**Comment by practicalswift** [comment]
@ken2812221 Sure, like this?

```diff
diff --git a/.appveyor.yml b/.appveyor.yml
index d7ce2224e..57319d24f 100644
--- a/.appveyor.yml
+++ b/.appveyor.yml
@@ -46,7 +46,7 @@ after_build:
 before_test:
 - ps:  ${conf_ini} = (Get-Content([IO.Path]::Combine(${env:APPVEYOR_BUILD_FOLDER}, "test", "config.ini.in")))
 - ps:  ${conf_ini} = $conf_ini.Replace("@abs_top_srcdir@", ${env:APPVEYOR_BUILD_FOLDER}).Replace("@abs_top_builddir@", ${env:APPVEYOR_BUILD_FOLDER}).Replace("@EXEEXT@", ".exe")
-- ps:  ${conf_ini} = $conf_ini.Replace("@ENABLE_WALLET_TRUE@", "").Replace("@BUILD_BITCOIN_UTILS_TRUE@", "").Replace("@BUILD_BITCOIND_TRUE@", "").Replace("@ENABLE_ZMQ_TRUE@", "")
+- ps:  ${conf_ini} = $conf_ini.Replace("@ENABLE_WALLET_TRUE@", "").Replace("@BUILD_BITCOIN_CLI_TRUE@", "").Replace("@BUILD_BITCOIND_TRUE@", "").Replace("@ENABLE_ZMQ_TRUE@", "")
 - ps:  ${utf8} = New-Object System.Text.UTF8Encoding ${false}
 - ps:  '[IO.File]::WriteAllLines([IO.Path]::Combine(${env:APPVEYOR_BUILD_FOLDER}, "test", "config.ini"), $conf_ini, ${utf8})'
 - ps:  move "build_msvc\${env:PLATFORM}\${env:CONFIGURATION}\*.exe" src
```

**Comment by ken2812221** [comment]
@practicalswift yes, thanks

**Comment by practicalswift** [comment]
@ken2812221 Fixed. Please re-review :-)

**Comment by ken2812221** [comment]
re-utACK ff94da78874550e3ae472686fdb6dd78a457eafd

**Pull request merged**
