### PR TITLE
test: Use clang-12 for ASAN, Add missing suppression

### PR DESCRIPTION
**Pull request by maflcko**

### CODE REVIEW

**Comment by MarcoFalke** [comment]
@martinus I haven't looked at the source code, but the `bench/nanobench.h:1107:15: runtime error: left shift of 4982565676696827473 by 27 places cannot be represented in type 'uint64_t' (aka 'unsigned long')` is probably expected and the suppression is the correct fix? As in: Not only a temporary fix to work around the sanitizer crash but also long term.

**Comment by martinus** [comment]
yes an overflow here is expected, this is in a random number generator. In the code I have already disabled "integer" sanitizer for that code, but not undefined behavior

**Comment by practicalswift** [comment]
Concept ACK

**Review by KenG-pro — APPROVED** [review]

**Review by fanquake — APPROVED** [review]
ACK fa00bb2c5ca64c7eb9e1846ffedc7829859812ca

**Pull request merged**
