### PR TITLE
appveyor: image: Previous Visual Studio 2019

### PR DESCRIPTION
**Pull request by maflcko**

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Appveyor started failing: https://ci.appveyor.com/project/DrahtBot/bitcoin/builds/37488791
Then started passing again (same commit): https://ci.appveyor.com/project/DrahtBot/bitcoin/builds/37491951
Then started failing again on all builds. Thus, the issue must be upstream.

**Comment by sipsorcery** [comment]
Hmm not so sure, I've been building on the latest Appveyor image successfully. Will have a look.

**Comment by MarcoFalke** [comment]
Thanks

**Comment by sipsorcery** [comment]
Seems like something is broken between appveyor and vcpkg. I haven't been able to re-produce yet. I will keep trying.

If you want a temporary fix you can use my cached versions of the vcpkg dependencies by setting the two environment variables below in the Appveyor settings. It results in the packages being downloaded as binaries from one of my previous appveyor builds instead of building from source.

VCPKG_FEATURE_FLAGS manifests,binarycaching
VCPKG_BINARY_SOURCES nuget,https://aaronrc.pkgs.visualstudio.com/bitcoin/_packaging/vcpkg-deps/nuget/v3/index.json,read

**Comment by sipsorcery** [comment]
Seems to have fixed itself. Glitch in the matrix.

**Pull request closed without merging**
