### PR TITLE
Fix and improve txn_doublespend.py test

### PR DESCRIPTION
**Pull request by dgenr8**
The first commit illustrates a problem with the current txn_doublespend.py test.  The test relies on unsupportable behavior in the wallet's SyncMetaData method.  The test is made to produce inconsistent results by making a small change to specific test "amount" parameters.

The second commit introduces a primitive method CTransaction::IsEquivalentTo and uses it in the wallet to ensure that SyncMetaData is only called for malleability clones, not general conflict (doublespend) transactions.  This makes the output of the illustrative version of txn_doublespend.py consistent and predictable.

The third commit is a revised txn_doublespend.py test that does not rely on broken SyncMetaData.  Instead, it expects the fixed version of SyncMetaData.   It also removes a dependency on the soon-to-be-deprecated accounting "move" method.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
utACK.
Travis fails `test_bitcoin: chainparams.cpp:286: const CChainParams& Params(): Assertion `pCurrentParams' failed.`.
You probably need to rebase because there was a travis error after a certain commit on master.

**Comment by dgenr8** [comment]
@gavinandresen ping

**Comment by gavinandresen** [comment]
I don't like the new unit test-- you are testing the new "" account gets debited on a non-malleated doublespend.

But our wallet code will never produce a non-malleated double-spend (at least not without the user jumping through some hoops to copy the wallet to two machines, etc etc etc).

I'd be happier if the new unit test tested the new code, and created a malleated version of the spend-to-foo and made sure The Right Thing happened.

I'm also uncertain about changing the SyncMetaData behavior to only work for malleated transactions, but I think I can live with that (mostly because what you get depends on the order your node sees transactions, accounts are being deprecated, and non-malleated double-spends of a "spendfrom" should never happen unless you jump through hoops).

**Comment by dgenr8** [comment]
@gavinandresen Thanks for the review  ... <gets to work>

**Comment by dgenr8** [comment]
Per @gavinandresen review:
 - Improved implementation of IsEquivalentTo
 - Added txn_clone.py, which tests malleability clone accounting
 - Updated rpc-tests.sh to call the new test with and without the --mineblock option

The new test relies on setting nlocktime via createrawtransaction.  There is also a stand-alone #5936 for this change.

**Comment by dgenr8** [comment]
- Problem illustration squashed, archived [here](https://github.com/dgenr8/bitcoin/commit/062d4ddf9d50f9abf86b13c58163018581c603a9).
 - txn_clone.py updated to use rpc generate(...)

**Comment by laanwj** [comment]
ACK on new test, for discussion with regard to adding a field to `createrawtransaction` RPC see #5936

**Comment by dgenr8** [comment]
Removed the change to `createrawtransaction`.

**Pull request merged**
