### PR TITLE
Docs: Update WSL installation notes for Fall Creators update

### PR DESCRIPTION
**Pull request by Thoragh**
Fall Creators update (RS3) was released 17 October and it has made some changes to the installation of WSL (no longer requires Developer Mode, out of beta and Ubuntu has to be installed from the Store).

### CODE REVIEW

**Comment by laanwj** [comment]
Concept ACK

**Comment by laanwj** [comment]
I'd like to see confirmation that at least one other person tested this before merging.

**Comment by MarcoFalke** [comment]
Concept ACK a4f171de5a44253394cb739586b04e2429f7f84d. Agree with @laanwj

**Comment by mikedennis** [comment]
I just went through this and did my own pull when I was pointed to the fact this one already exists. I'm not sure you need much additional doc around this at all. It's basically just install WSL and then follow linux instructions for whatever distro you install in the WSL. Worked great for me whereas I was unable to get it to work with the previous beta WSL.

**Comment by laanwj** [comment]
> It's basically just install WSL and then follow linux instructions for whatever distro you install in the WSL.

With the exception that you're *cross compiling* for Windows. If you miss that part, you get issues like #11633. That's why separate instructions exist.

**Comment by laanwj** [comment]
@mikedennis So can you ACK the changes here, then this can be merged.

**Comment by laanwj** [comment]
This is conflicting after #11438, needs rebase if there are still relevant changes after that.

**Comment by mikedennis** [comment]
I'm having problems with cross compilation. To start with if you follow these procedures you end up with Ubuntu Xenial 16.04 which this doc states is not a good choice for cross compilation.

I proceeded and ran into a problem with this step building in depends:
```make HOST=x86_64-w64-mingw32```

I get an error warning about automake-1.14 is missing on my system. I checked and I have 1.15-4ubuntu1 installed. I suspect  I need to follow the workarounds in #8732 

I recommend putting a note in the docs that this procedure installs Ubuntu Xenial 16.04 and to see #8732 if you want to cross compile.

You can also install openSUSE Leap 42 in WSL. I may give that a try and see if I have more success with that and the cross compilation.

**Comment by laanwj** [comment]
> I get an error warning about automake-1.14 is missing on my system. I checked and I have 1.15-4ubuntu1 installed. I suspect I need to follow the workarounds in #8732

If you get that error, you need to build from the linux drive. Building from a mounted windows drive e.g. /mnt/c/ will not work, as the file system interaction changes the timestamps such as protobuf thinks it needs to re-generate its configuration files, which doesn't work.

**Comment by mikedennis** [comment]
I was able to build with cross compilation using the instructions. I would, however, recommend the following modifications to the documentation:
* In depends build mention you cannot build via mnt or else will get an error with automake
* I needed to change to posix compilers even though I'm running Ubuntu 16.04. The docs say you only need to run posix on 17.04 and higher so probably need to change the docs to say 16.04 and higher.

**Comment by Thoragh** [comment]
I have updated the pull request.

**Comment by laanwj** [comment]
Going to merge this, @mikedennis feel free to improve it further in a future PR, these changes make sense but are outside the claimed scope of this PR.

**Pull request merged**
