### PR TITLE
test: remove unused variables in `p2p_invalid_block`

### PR DESCRIPTION
**Pull request by brunoerg**

### CODE REVIEW

**Comment by fanquake** [comment]
> IIRC dropping the confidence would lead to false positives

Yea, most of the output produced at 60 is that (or code we wouldn't want to remove). I guess having Vulture at 100 when it doesn't seem to work, means we could just remove it?

**Comment by brunoerg** [comment]
> Shouldn't vulture be able to detect those with our setting of 100%?

It should, but it doesn't work as expected. It doesn't detect scenarios like:
```py
abc = 1
abc = 2
call(abc)
```

Even dropping confidence, it catches only some stuff from our test framework (false flag). E.g.:
```sh
test/functional/p2p_invalid_block.py:32: unused method 'set_test_params' (60% confidence)
test/functional/p2p_invalid_block.py:33: unused attribute 'num_nodes' (60% confidence)
test/functional/p2p_invalid_block.py:34: unused attribute 'setup_clean_chain' (60% confidence)
test/functional/p2p_invalid_block.py:35: unused attribute 'extra_args' (60% confidence)
test/functional/p2p_invalid_block.py:37: unused method 'run_test' (60% confidence)
```

**Comment by brunoerg** [comment]
> Maybe report it upstream?

Seems good. https://github.com/jendrikseipp/vulture/issues/315 is useful for us as well.

**Review by stickies-v — APPROVED** [review]
ACK 3eb03803c4111d09c63550a6a6c09afbe3430bf6

I was confused by the PR and commit title though as we're not removing any variables, and they are used. I'd just call it "unused code".

**Pull request merged**
