### PR TITLE
Clean up chainparams some more.

### PR DESCRIPTION
**Pull request by domob1812**
Clean up the code in chainparams a bit more after the recent refactorings.  In particular, make sure the structure of the "RegTest" params matches the structure of the other classes.  This makes the code clearer to read.

Also remove redundant values of the genesis block in always-specified optional arguments and mark variable/argument as "const".

### CODE REVIEW

**Comment by sipa** [comment]
No strong opinion, but looks good to me.

**Comment by jonasschnelli** [comment]
ACK (makes sense to remove duplicated parameter default values and the const pass by ref).

**Comment by laanwj** [comment]
I'd prefer to take this one step further: remove the default arguments from the outer `CreateGenesisBlock` as well. And specify all the parameters where they belong, together, in the appropriate constructor.

**Comment by domob1812** [comment]
I agree - I've updated the patch.  When it is finally reviewed and ready, I will squash the commits.

**Comment by laanwj** [comment]
utACK

**Comment by theuni** [comment]
ut ACK. Agreed that the defaults there are strange.

**Comment by laanwj** [comment]
@domob1812 can you squash please?

**Comment by domob1812** [comment]
Done.

**Comment by domob1812** [comment]
Done.

**Pull request merged**
