### PR TITLE
test: Explain that a bug should be filed when the tests fail

### PR DESCRIPTION
**Pull request by maflcko**
Without a bug report it is harder to fix the issue

### CODE REVIEW

**Review by hebasto — APPROVED** [review]
ACK fad21a1a7aa8804f4699e5821f074f5d3845c78b, I have not tested the code, but I have reviewed it and it looks OK, I agree it can be merged.

**Review by fanquake — APPROVED** [review]
ACK fad21a1a7aa8804f4699e5821f074f5d3845c78b
```bash
    assert_equal(self.nodes[0].getbestblockhash(), block.blahblah)
AttributeError: 'CBlock' object has no attribute 'blahblah'
2020-05-30T07:58:41.461000Z TestFramework (INFO): Stopping nodes
2020-05-30T07:58:41.724000Z TestFramework (WARNING): Not cleaning up dir /var/folders/z2/cn877pxd3czdfh47mfkmbwgm0000gn/T/test_runner_₿_🏃_20200530_155836/feature_cltv_0
2020-05-30T07:58:41.724000Z TestFramework (ERROR): Test failed. Test logging available at /var/folders/z2/cn877pxd3czdfh47mfkmbwgm0000gn/T/test_runner_₿_🏃_20200530_155836/feature_cltv_0/test_framework.log
2020-05-30T07:58:41.725000Z TestFramework (ERROR): 
2020-05-30T07:58:41.725000Z TestFramework (ERROR): Hint: Call /bitcoin/test/functional/combine_logs.py '/var/folders/z2/cn877pxd3czdfh47mfkmbwgm0000gn/T/test_runner_₿_🏃_20200530_155836/feature_cltv_0' to consolidate all logs
2020-05-30T07:58:41.725000Z TestFramework (ERROR): 
2020-05-30T07:58:41.725000Z TestFramework (ERROR): If this failure happened unexpectedly or intermittently, please file a bug and provide a link or upload of the combined log.
2020-05-30T07:58:41.725000Z TestFramework (ERROR): https://github.com/bitcoin/bitcoin/issues
2020-05-30T07:58:41.725000Z TestFramework (ERROR): 
```

**Comment by hebasto** [comment]
@MarcoFalke 
How to preserve the travis log with an intermittent error for issue submitting?
e.g., https://travis-ci.org/github/bitcoin/bitcoin/jobs/692067912#L5040

If I re-run build the log pointed by url will be re-written. Re-submit the latest commit?

**Comment by MarcoFalke** [comment]
Yes, only way is to (force) push or re-open or download manually :(  See https://github.com/bitcoin/bitcoin/issues/15847#issuecomment-487591130

**Pull request merged**
