### PR TITLE
build: extract $(BOOST_CPPFLAGS) from $(BITCOIN_INCLUDES) 

### LINKED ISSUE #25947: MacOS Build Error: Qt 5 and 6 Simultaneously Installed.
This error seems to appear when `brew install qt@5` is installed at the same time as: `brew install qt`. (ie, qt version 6):

``` bash
% brew list --version | grep qt

qt 6.3.1_1
qt@5 5.15.5_1
```

```
Making all in src
  CXX      qt/libbitcoinqt_a-bantablemodel.o
In file included from qt/bantablemodel.cpp:14:
In file included from /usr/local/Cellar/qt@5/5.15.5_1/lib/QtCore.framework/Headers/QLocale:1:
/usr/local/Cellar/qt@5/5.15.5_1/lib/QtCore.framework/Headers/qlocale.h:1028:25: error: unknown type name 'QStringRef'; did you mean 'CFStringRef'?
    short toShort(const QStringRef &s, bool *ok = nullptr) const;
                        ^~~~~~~~~~
                        CFStringRef
/usr/local/include/QtCore/qdebug.h:531:1: note: 'CFStringRef' declared here
Q_FORWARD_DECLARE_CF_TYPE(CFString);
^
/usr/local/include/QtCore/qglobal.h:802:77: note: expanded from macro 'Q_FORWARD_DECLARE_CF_TYPE'
#  define Q_FORWARD_DECLARE_CF_TYPE(type) typedef const struct __ ## type * type ## Ref
                                                                            ^
<scratch space>:112:1: note: expanded from here
CFStringRef
^
```

```bash
% git clean -ffxd
% git rev-parse HEAD
e191fac4f3c37820f0618f72f0a8e8b524531ab8
% ./autogen.sh
% ./configure
% make
```
output: https://gist.github.com/da2ce7/c697259e204c961876ad7f7057e95b34

config.log: https://gist.github.com/da2ce7/ec7276de7d0284681cd73b0cdcb90f3b

brew list --version --formulae: https://gist.github.com/da2ce7/25d6473224a1d69a28cf24e44abb55b7

_Originally posted by @da2ce7 in https://github.com/bitcoin/bitcoin/issues/21901#issuecomment-1229561087_

### PR DESCRIPTION
**Pull request by fanquake**
This leaves `$(BITCOIN_INCLUDES)` as internal dependencies, and gives finer control over Boost includes.

Fixes #25947.

### CODE REVIEW

**Comment by hebasto** [comment]
Concept ACK.

**Comment by theuni** [comment]
Concept ACK.

Hah, I was working on this at the same time (on top of master, though).
To compare, here's what I came up with: https://github.com/theuni/bitcoin/commit/400eede3e56b15db86a83d7785a57f179f6cba85

Rather than adding it where it looked like it would be needed, I added a depends commit to move it out of the common prefix path, that way we'll actually detect missing headers: https://github.com/theuni/bitcoin/commit/e131d8f1e33baa9a9499d2e1a4a99b171566c5a5 . Then I rebuilt everything and added `BOOST_CPPFLAGS` one-by-one as needed to fix compilation.

**Comment by theuni** [comment]
Looks like the only difference between ours (other than test_util) is missing `BOOST_CPPFLAGS` for `bitcoin_chainstate`

ACK after adding that.

**Comment by hebasto** [comment]
@theuni 
> here's what I came up with: [theuni@400eede](https://github.com/theuni/bitcoin/commit/400eede3e56b15db86a83d7785a57f179f6cba85)

With flag reordering as follows:
```diff
diff --git a/src/Makefile.qt.include b/src/Makefile.qt.include
index 4fe79652e..602a11825 100644
--- a/src/Makefile.qt.include
+++ b/src/Makefile.qt.include
@@ -295,7 +295,7 @@ BITCOIN_QT_RC = qt/res/bitcoin-qt-res.rc
 BITCOIN_QT_INCLUDES = -DQT_NO_KEYWORDS -DQT_USE_QSTRINGBUILDER
 
 qt_libbitcoinqt_a_CPPFLAGS = $(AM_CPPFLAGS) $(BITCOIN_INCLUDES) $(BITCOIN_QT_INCLUDES) \
-  $(BOOST_CPPFLAGS) $(QT_INCLUDES) $(QT_DBUS_INCLUDES) $(QR_CFLAGS)
+  $(QT_INCLUDES) $(QT_DBUS_INCLUDES) $(QR_CFLAGS) $(BOOST_CPPFLAGS)
 qt_libbitcoinqt_a_CXXFLAGS = $(AM_CXXFLAGS) $(QT_PIE_FLAGS)
 qt_libbitcoinqt_a_OBJCXXFLAGS = $(AM_OBJCXXFLAGS) $(QT_PIE_FLAGS)
 
diff --git a/src/Makefile.qttest.include b/src/Makefile.qttest.include
index afcd4106b..89c659d4b 100644
--- a/src/Makefile.qttest.include
+++ b/src/Makefile.qttest.include
@@ -27,7 +27,7 @@ TEST_QT_H = \
   qt/test/wallettests.h
 
 qt_test_test_bitcoin_qt_CPPFLAGS = $(AM_CPPFLAGS) $(BITCOIN_INCLUDES) $(BITCOIN_QT_INCLUDES) \
-  $(BOOST_CPPFLAGS) $(QT_INCLUDES) $(QT_TEST_INCLUDES)
+  $(QT_INCLUDES) $(QT_TEST_INCLUDES) $(BOOST_CPPFLAGS)
 
 qt_test_test_bitcoin_qt_SOURCES = \
   init/bitcoin-qt.cpp \
```

your commit fixes #25947 as well.

**Comment by fanquake** [comment]
> Looks like the only difference between ours (other than test_util) is missing BOOST_CPPFLAGS for bitcoin_chainstate

The bin I didn't test compiling 😅. Rebased on master and fixed this up.

**Comment by hebasto** [comment]
This diff:
```diff
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -753,7 +753,7 @@ bitcoin_node_LDADD = $(LIBBITCOIN_NODE) $(bitcoin_bin_ldadd) $(LIBBITCOIN_IPC) $
 
 # bitcoin-cli binary #
 bitcoin_cli_SOURCES = bitcoin-cli.cpp
-bitcoin_cli_CPPFLAGS = $(AM_CPPFLAGS) $(BITCOIN_INCLUDES) $(EVENT_CFLAGS)
+bitcoin_cli_CPPFLAGS = $(AM_CPPFLAGS) $(BITCOIN_INCLUDES) $(BOOST_CPPFLAGS) $(EVENT_CFLAGS)
 bitcoin_cli_CXXFLAGS = $(AM_CXXFLAGS) $(PIE_FLAGS)
 bitcoin_cli_LDFLAGS = $(RELDFLAGS) $(AM_LDFLAGS) $(LIBTOOL_APP_LDFLAGS) $(PTHREAD_FLAGS)
 
```

fixes macOS native build.

**Comment by Sjors** [comment]
Concept ACK

**Comment by fanquake** [comment]
> fixes macOS native build.

I don't think that's the right solution, and would actually just hide the underlying problem. Re-adding `$(BOOST_CPPFLAGS)` where it isn't needed, also defeats the point of this change.

Given that the CI runs with `--enable-suppress-external-warnings`, and the failure is due to warnings coming from libevent, there is some other problem here; `-Wdocumentation` warnings for an external dependency shouldn't be appearing at all. 

Looking at the [log](https://cirrus-ci.com/task/5756119120347136?logs=ci#L1672), we've got `-isystem /usr/local/Cellar/libevent/2.1.12/include`, but then:
```bash
In file included from bitcoin-cli.cpp:40:
/usr/local/include/event2/buffer.h:210:11: error: parameter 'buffer' not found in the function declaration [-Werror,-Wdocumentation]
 * @param buffer the evbuffer that the callback is watching.
          ^~~~~~
```

so I assume the reason these are currently being suppressed is actually due to the Boost cppflags always being present, which adds `-isystem /usr/local/include -DBOOST_MULTI_INDEX_DISABLE_SERIALIZATION -DBOOST_NO_CXX98_FUNCTION_BASE` to the compile, and suppresses all warnings coming from `/usr/local/include`.

**Comment by theuni** [comment]
From ./ci/test/00_setup_env_native_asan.sh :

> export PACKAGES="systemtap-sdt-dev bpfcc-tools clang llvm python3-zmq qtbase5-dev qttools5-dev-tools libevent-dev bsdmainutils libboost-dev libdb5.3++-dev libminiupnpc-dev libnatpmp-dev libzmq3-dev libqrencode-dev libsqlite3-dev"


From .cirrus.yml:
>  brew_install_script:
>    \- brew install boost libevent qt@5 miniupnpc libnatpmp ccache zeromq qrencode libtool automake gnu-getopt

Seems we're pulling libevent (and a few others) from 2 places for MacOS. Why?

**Comment by MarcoFalke** [comment]
It is a bit messy, but the brew macos build doesn't use the Ubuntu apt, so there should only be one place where this is installed: https://github.com/bitcoin/bitcoin/blob/5558d2f5496d8fe1c16f9edd1ef395fcd842e6fb/.cirrus.yml#L332

You can also check the logs produced at runtime to double check.

**Comment by theuni** [comment]
I played around a little bit with this locally and was able to reproduce with a minimal test-case.

I believe this commit should fix the root issue here: https://github.com/theuni/bitcoin/commit/6f19a01473759f2cc787f2246add1b1d63603bef (see the comment for a description of the issue).

@hebasto do you have an easy way of testing? If not, I can just open a PR with these two commits and see if c-I is happy.

**Comment by theuni** [comment]
> @theuni
> 
> > here's what I came up with: [theuni@400eede](https://github.com/theuni/bitcoin/commit/400eede3e56b15db86a83d7785a57f179f6cba85)
> 
> With flag reordering as follows:
> 
> ```diff
> diff --git a/src/Makefile.qt.include b/src/Makefile.qt.include
> index 4fe79652e..602a11825 100644
> --- a/src/Makefile.qt.include
> +++ b/src/Makefile.qt.include
> @@ -295,7 +295,7 @@ BITCOIN_QT_RC = qt/res/bitcoin-qt-res.rc
>  BITCOIN_QT_INCLUDES = -DQT_NO_KEYWORDS -DQT_USE_QSTRINGBUILDER
>  
>  qt_libbitcoinqt_a_CPPFLAGS = $(AM_CPPFLAGS) $(BITCOIN_INCLUDES) $(BITCOIN_QT_INCLUDES) \
> -  $(BOOST_CPPFLAGS) $(QT_INCLUDES) $(QT_DBUS_INCLUDES) $(QR_CFLAGS)
> +  $(QT_INCLUDES) $(QT_DBUS_INCLUDES) $(QR_CFLAGS) $(BOOST_CPPFLAGS)
>  qt_libbitcoinqt_a_CXXFLAGS = $(AM_CXXFLAGS) $(QT_PIE_FLAGS)
>  qt_libbitcoinqt_a_OBJCXXFLAGS = $(AM_OBJCXXFLAGS) $(QT_PIE_FLAGS)
>  
> diff --git a/src/Makefile.qttest.include b/src/Makefile.qttest.include
> index afcd4106b..89c659d4b 100644
> --- a/src/Makefile.qttest.include
> +++ b/src/Makefile.qttest.include
> @@ -27,7 +27,7 @@ TEST_QT_H = \
>    qt/test/wallettests.h
>  
>  qt_test_test_bitcoin_qt_CPPFLAGS = $(AM_CPPFLAGS) $(BITCOIN_INCLUDES) $(BITCOIN_QT_INCLUDES) \
> -  $(BOOST_CPPFLAGS) $(QT_INCLUDES) $(QT_TEST_INCLUDES)
> +  $(QT_INCLUDES) $(QT_TEST_INCLUDES) $(BOOST_CPPFLAGS)
>  
>  qt_test_test_bitcoin_qt_SOURCES = \
>    init/bitcoin-qt.cpp \
> ```
> 
> your commit fixes #25947 as well.

I do think specifying explicitly probed include paths (bdb/sqlite/qt5/miniupnpc/natpmp) before the others for brew whenever we can makes sense as a policy. And in this case, I agree that it would fix the problem. That said, I'm not sure we can always do this (include order may matter for other reasons), and homebrew isn't exactly our top priority.

So, since I don't see any reason not to in this case... ACK reversing the order as you suggested.

**Comment by fanquake** [comment]
Updated the description to note that this should also fix #25947 (I haven't tested myself). Also going to tag this (and implicitly #26070) for 24.0, as they are fixing annoying bugs in `--suppress-external-warnings`, and now building on macOS when multiple versions of qt installed.

**Comment by fanquake** [comment]
Rebased for #26070.

**Comment by theuni** [comment]
ACK 12de8f6262e9e74eb3c1a1c46070f7bc6a4cdac6

It's nice that we're now forced to make all external dependencies explicit. I suspect this will eventually lead to a few more boost removals.

**Comment by kouloumos** [comment]
Verified that it fixes #25947.

Tested on macOS 10.15.7 with
```shell
$ brew list --version | grep qt
qt 6.3.1_3
qt@5 5.15.5_2 5.15.3
```

**Review by hebasto — APPROVED** [review]
ACK 12de8f6262e9e74eb3c1a1c46070f7bc6a4cdac6, tested on macOS Monterey 12.6 (21G115, Intel).

**Review by jarolrod — APPROVED** [review]
ACK 12de8f6262e9e74eb3c1a1c46070f7bc6a4cdac6

**Comment by Zero-1729** [comment]
Posthumous ACK 12de8f6262e9e74eb3c1a1c46070f7bc6a4cdac6 

P.S. Tested on macOS 12.6 (21G115), M1

Thanks @fanquake!

**Pull request merged**
