### PR TITLE
RPC: why not give more details when "generate" fails?

### PR DESCRIPTION
**Pull request by jtimon**
It should be unlikely to get this error anyway, but when you get it, the more you know about it better, no?

### CODE REVIEW

**Comment by instagibbs** [comment]
Commit message is a bit cheeky for my tastes, but content utACK. It's better to give something to user than nothing.

**Comment by jtimon** [comment]
Reworded commit message.

**Comment by jonasschnelli** [comment]
Yes. Why not.
utACK e71cc7c482c80af4a3963d11702631e79d7d3a25

**Comment by sipa** [comment]
utACK e71cc7c482c80af4a3963d11702631e79d7d3a25

**Comment by paveljanik** [comment]
Needs rebase.

**Comment by jtimon** [comment]
Rebased

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/9087/commits/1adf82ac394ca16308e1004495b76529d54018ba

**Pull request merged**
