### PR TITLE
gui: Close console with CTRL+D ala terminal

### PR DESCRIPTION
**Pull request by promag**
Originally suggested by @emilengler.

### CODE REVIEW

**Comment by emilengler** [comment]
Tested it, works great.
ACK

**Comment by hebasto** [comment]
Concept ACK and code looks neat.
The `CTRL+D` shortcut is not common for Windows users. And the GUI should somehow inform a user about it.

**Comment by jonasschnelli** [comment]
I guess this is OS specific.
On macOS, `cmd-W` does close windows within an app (works almost with all apps including strange java cross platform apps like "Arduino-IDE",... but not with Bitcoin-Qt).

However, concept ACK on working on shortcuts to close windows.

**Comment by laanwj** [comment]
ACK

(though I share with @jonasschnelli  a slight preference for Ctrl-W as well for closing *any* subwindow, due to FF browser tabs, but have no problem with Ctrl-D doing the same here, there's already a PR for that anyhow #15768)

**Comment by laanwj** [comment]
Tested ACK 5813b37ff687eb792d17b9efed729ee555bdb00a

**Comment by emilengler** [comment]
@jonasschnelli does ctrl+w closes any window?
The idea behind it was only to close a terminal window and the bitcoin-qt terminal window is one. I think the Ctrl+D shortcut is common for unix terminals

**Comment by promag** [comment]
Correction, it sends EOF to the shell prompt, which then terminates, which can result in the window close.

**Comment by emilengler** [comment]
Sure but this effectively closes a terminal (at least on unix(-like) systems)

**Comment by promag** [comment]
No quite:
```sh
cat
CTRL+D    # cat quits
```

**Comment by emilengler** [comment]
IIRC someone said that this does not send a EOF to the terminal, it "only" closes the terminal.
I meant that your implementation is fine for this.
Sorry I sometimes have problems to justify myself :(

**Comment by jonasschnelli** [comment]
> @jonasschnelli does ctrl+w closes any window?

on macOS: yes. (Almost) every window (at least all well behaving apps close a window).

--- 
#15768 is related and I think we should have one PR adding the "close window shortcut functionality".

Since this is OS dependent, the shortcut should probably be defined in `platformstyles.cpp/.h`.

However, I think each window should be closeable with a default shortcut (including console, help, preferences, etc.).
Probably: `ctrl-D` on  linux, `cmd-W` on macOS and `alt F4` on windows.

I could not find, but it could be that Qt provide a such functionality already.

**Comment by jonatack** [comment]
> Probably: `ctrl-D` on linux, `cmd-W` on macOS and `alt F4` on windows.

Here on Linux Debian, `C-w` closes desktop windows (with Gnome), and `C-d` closes terminal windows.

**Review by jonatack — COMMENTED** [review]
ACK 5813b37ff687eb792d17b9efed729ee555bdb00a, built and tested manually, all tests pass.

The added `C-d` functionality works only with the GUI console window, and not with the info, network traffic, or peers windows.

On Linux Debian for me `C-w` closes desktop windows (Gnome) and browser tabs (Firefox), and `C-d` closes terminal windows.

> (though I share with @jonasschnelli a slight preference for Ctrl-W as well for closing _any_ subwindow, due to FF browser tabs, but have no problem with Ctrl-D doing the same here, there's already a PR for that anyhow #15768)

Agree.

**Comment by emilengler** [comment]
On my Debian Linux MATE Ctrl-W also closes nearly every window except console windows.
Does Ctrl-W also closes the default Terminal.app on macOS?

**Comment by hebasto** [comment]
I'd prefer to use Ctrl+W for closing any subwindow (like #15768). And using a special shortcut for closing the "Console" window [seems an overkill](https://developer.apple.com/design/human-interface-guidelines/macos/user-interaction/keyboard/):
> **Define new keyboard shortcuts only for things people do regularly.** It’s hard for people to remember shortcuts they seldom use. Minimizing app-specific keyboard shortcuts also helps avoid potential conflicts with other system-wide shortcuts that may be in place.

Anyway, if reviewers will decide that the "Console" window needs its own shortcut to be closed, it seems the next patch could be an [improvement of usability](https://github.com/bitcoin/bitcoin/pull/16515#issuecomment-517183727):
```diff
--- a/src/qt/rpcconsole.cpp
+++ b/src/qt/rpcconsole.cpp
@@ -802,19 +802,21 @@ void RPCConsole::clear(bool clearHistory)
                 ".secwarning { color: red; }"
                 "b { color: #006060; } "
             ).arg(fixedFontInfo.family(), QString("%1pt").arg(consoleFontSize))
         );
 
 #ifdef Q_OS_MAC
-    QString clsKey = "(⌘)-L";
+    QString clear_key = "⌘L";
+    QString close_key = "⌘D";
 #else
-    QString clsKey = "Ctrl-L";
+    QString clear_key = "Ctrl+L";
+    QString close_key = "Ctrl+D";
 #endif
 
     message(CMD_REPLY, (tr("Welcome to the %1 RPC console.").arg(PACKAGE_NAME) + "<br>" +
-                        tr("Use up and down arrows to navigate history, and %1 to clear screen.").arg("<b>"+clsKey+"</b>") + "<br>" +
+                        tr("Use up and down arrows to navigate history, %1 to clear screen and %2 to close this window.").arg("<b>" + clear_key + "</b>").arg("<b>" + close_key + "</b>") + "<br>" +
                         tr("Type %1 for an overview of available commands.").arg("<b>help</b>") + "<br>" +
                         tr("For more information on using this console type %1.").arg("<b>help-console</b>") +
                         "<br><span class=\"secwarning\"><br>" +
                         tr("WARNING: Scammers have been active, telling users to type commands here, stealing their wallet contents. Do not use this console without fully understanding the ramifications of a command.") +
                         "</span>"),
                         true);
```

**Comment by promag** [comment]
meh

**Pull request closed without merging**
