### PR TITLE
qt: English (source) translations update

### PR DESCRIPTION
**Pull request by laanwj**
Last-minute update for bitcoin/bitcoin#24434 and bitcoin/bitcoin#24401.

### CODE REVIEW

**Review by jonatack — COMMENTED** [review]
Light review ACK 38020c4f2eb6aae05a4745695f718034fb769c1b

at least, as far as I can tell. Unrelated, saw the following with `make translate` (clang 15 and gcc 11)

```
make translate
  GEN      qt/bitcoinstrings.cpp
protocol.h:379: warning: unterminated character constant
util/strencodings.h:44: warning: unterminated character constant
  GEN      translate
/home/jon/projects/bitcoin/bitcoin/src/util/strencodings.h:44: Unterminated C++ character
/home/jon/projects/bitcoin/bitcoin/src/protocol.h:379: Unterminated C++ character
/home/jon/projects/bitcoin/bitcoin/src/protocol.h:359: Unbalanced opening brace in C++ code (or abuse of the C++ preprocessor)
/home/jon/projects/bitcoin/bitcoin/src/qt/guiutil.cpp:800: Unterminated C++ character
/home/jon/projects/bitcoin/bitcoin/src/qt/guiutil.cpp:803: Unterminated C++ character
/home/jon/projects/bitcoin/bitcoin/src/qt/guiutil.cpp:804: Unterminated C++ character
/home/jon/projects/bitcoin/bitcoin/src/qt/guiutil.cpp:807: Unterminated C++ character
/home/jon/projects/bitcoin/bitcoin/src/qt/guiutil.cpp:800: Unbalanced opening parenthesis in C++ code (or abuse of the C++ preprocessor)
Updating 'qt/locale/bitcoin_en.ts'...
    Found 1100 source text(s) (0 new and 1100 already existing)
  GEN      translate
```

**Comment by laanwj** [comment]
I think the warnings are harmless. They're thrown by `qtranslate` when encountering constructions like `1'000`. I guess it hasn't been updated yet for new C++ syntax. As long as they don't happen on the same line as `tr()` (making it possible to miss a message?) I think it doesn't matter.

**Review by fanquake — APPROVED** [review]
ACK 38020c4f2eb6aae05a4745695f718034fb769c1b

**Comment by Pragmatic2021** [comment]
Thank you, as usual. When you need me, let me know..

**Pull request merged**
