### PR TITLE
qt: Show the Window when double clicking the taskbar icon

### LINKED ISSUE #12838: QT: double click bitcoin icon on the task bar with setting 'minimize to the tray' cause a blank window
double click bitcoin icon on the task bar with setting 'minimize to the tray' cause a blank window

ezgif com-video-to-gif

### PR DESCRIPTION
**Pull request by ken2812221**
fix #12838

### CODE REVIEW

**Comment by fanquake** [comment]
@jonasschnelli Could you also do a gitian build here?

**Comment by jonasschnelli** [comment]
gitian build: https://bitcoin.jonasschnelli.ch/build/575

**Comment by fanquake** [comment]
I've tested the Win64 gitian build, and can confirm that the double click -> white-screen behaviour reported in #12838 is fixed by 67bf2aa68eaa4502c8c11541e3f39b0372e95bf8. Have not tested on any other OS, or checked if any other minimising behaviours etc are affected yet.

**Comment by laanwj** [comment]
utACK 67bf2aa68eaa4502c8c11541e3f39b0372e95bf8

**Pull request merged**
