### PR TITLE
qt: Assert QMetaObject::invokeMethod result

### PR DESCRIPTION
**Pull request by promag**
Invalid/wrong dynamic calls aren't verified by the compiler. This PR asserts those dynamic calls. Once we bump Qt to at least 5.10 these can be refactored to use the `invokeMethod` overload that allows connecting to lambdas or member pointers, which are compile checked.

For reference, one of the overloaded versions is https://doc.qt.io/qt-5/qmetaobject.html#invokeMethod-5.

### CODE REVIEW

**Comment by hebasto** [comment]
@promag 
> Once we bump Qt to at least 5.10 these can be refactored to use the `invokeMethod` overload that allows connecting to lambdas or member pointers, which are compile checked.

IMO, in the long run it will be better to get rid of `QMetaObject::invokeMethod` completely, because [`QMetaObject` class](https://doc.qt.io/qt-5/qmetaobject.html#details)
> ... is not normally required for application programming...

**Comment by promag** [comment]
@hebasto since Qt 5.10 invokeMethod is very useful to run code asynchronous in other threads.

**Comment by hebasto** [comment]
@promag 
> since Qt 5.10 invokeMethod is very useful to run code (a)synchronous in other thread.

I believe it is possible and convenient to handle all inter-thread communications via signal-slot connections. That is the main Qt feature ;)

**Comment by promag** [comment]
Yes, but there's nothing wrong with convenience, that's why those were added.

**Comment by hebasto** [comment]
Concept ACK

**Comment by laanwj** [comment]
So to be clear, before concept ACK: these can *only* fail when the name / method signature is wrong, not for run-time reasons such as a full queue ?

**Comment by promag** [comment]
@laanwj yes, from the docs:
> Invokes the member (a signal or a slot name) on the object obj. Returns true if the member could be invoked. Returns false if there is no such member or the parameters did not match.

> such as a full queue 

Is this even possible?

**Comment by laanwj** [comment]
> Is this even possible?

I don't think so, not sure, my experience (with accidentally not rate-limiting notifications) is that the queue is very deep at least
but thanks for quoting the doc that's good enough for me.

concept and code review ACK 2fd7d0b9081c9add34277e94e8ad21ce22ee2d61

**Comment by hebasto** [comment]
This approach was used in a720a983015c9ef8cc814c16a5b9ef6379695817 already.

**Comment by hebasto** [comment]
Tested on Debian 9.9 (system Qt 5.7.1):
```
$ ./src/qt/bitcoin-qt -regtest -nowallet -debug=qt
```
Open a wallet from menu...
```
bitcoin-qt: qt/walletcontroller.cpp:125: WalletModel* WalletController::getOrCreateWallet(std::unique_ptr<interfaces::Wallet>): Assertion `invoked' failed.
Aborted
```
```
$ tail -5 ~/.bitcoin/regtest/debug.log 
2019-07-08T16:14:33Z [rpc one] nFileVersion = 189900
2019-07-08T16:14:33Z [rpc one] Keys: 2001 plaintext, 0 encrypted, 2001 w/ metadata, 2001 total. Unknown wallet records: 0
2019-07-08T16:14:33Z [rpc one] Wallet completed loading in              97ms
2019-07-08T16:14:33Z GUI: TransactionTablePriv::refreshWallet
2019-07-08T16:14:33Z GUI: QMetaMethod::invoke: Unable to handle unregistered datatype 'WalletModel*'
```

Ref: #15453, #16349

**Comment by promag** [comment]
@hebasto please add `WalletModel*` here:
https://github.com/bitcoin/bitcoin/blob/2679bb8919b5089f8067ccfd94f766747b8df671/src/qt/bitcoin.cpp#L64-L68
and test again.

**Comment by hebasto** [comment]
@promag 
> please add WalletModel* ... and test again.

Done. No luck ((
Result is the same.

**Comment by promag** [comment]
Also here https://github.com/bitcoin/bitcoin/blob/05623c021681a5a9c4d35f70f3dbd7e1e49fd81c/src/qt/bitcoin.cpp#L453

**Comment by hebasto** [comment]
@promag the latter is enough:
```diff
diff --git a/src/qt/bitcoin.cpp b/src/qt/bitcoin.cpp
index 2fdbcca04..b7740d540 100644
--- a/src/qt/bitcoin.cpp
+++ b/src/qt/bitcoin.cpp
@@ -454,6 +454,7 @@ int GuiMain(int argc, char* argv[])
     qRegisterMetaType< CAmount >("CAmount");
     qRegisterMetaType< std::function<void()> >("std::function<void()>");
     qRegisterMetaType<QMessageBox::Icon>("QMessageBox::Icon");
+    qRegisterMetaType< WalletModel* >();
     /// 2. Parse command-line options. We do this after qt in order to show an error if there are problems parsing these
     // Command-line options take precedence:
     node->setupServerArgs();
```

It works.

**Comment by promag** [comment]
Cool, I'll add it here and you can close your PR.

**Comment by hebasto** [comment]
@promag 
> Cool, I'll add it here and you can close your PR.

I will leave it as refactoring, if you don't mind.

**Comment by laanwj** [comment]
Nice that this helped find an actual bug!

**Comment by promag** [comment]
IMO all done here, thanks @hebasto.

**Comment by hebasto** [comment]
ACK f27bd96b5fdc2921d93c44bbf422bff0e979c4de, I have tested the code.

**Comment by laanwj** [comment]
@hebasto looks like you didn't ACK the top commit but the one below it

ACK 64fee489448c62319e77941c30152084695b5a5d

**Comment by hebasto** [comment]
> @hebasto looks like you didn't ACK the top commit but the one below it

post-merge ACK 64fee489448c62319e77941c30152084695b5a5d

**Comment by promag** [comment]
Backport in #16359.

**Pull request merged**
