### PR TITLE
Update to latest libsecp256k1 master

### PR DESCRIPTION
**Pull request by sipa**
There have been a few small performance improvements, and improved tests.

### CODE REVIEW

**Comment by gmaxwell** [comment]
ACK (haven't verified the subtree merge, those always mangle for me)

**Comment by laanwj** [comment]
Subtree checks out for me, haven't reviewed the secp256k1-changes-ACK
```bash
$ git fetch https://github.com/bitcoin-core/secp256k1.git
remote: Counting objects: 209, done.
remote: Total 209 (delta 126), reused 126 (delta 126), pack-reused 83
Receiving objects: 100% (209/209), 97.14 KiB | 0 bytes/s, done.
Resolving deltas: 100% (143/143), completed with 47 local objects.
From https://github.com/bitcoin-core/secp256k1
 * branch            HEAD       -> FETCH_HEAD
$ contrib/devtools/git-subtree-check.sh src/secp256k1
src/secp256k1 in HEAD was last updated to upstream commit cbc20b8c34d44c2ef175420f3cdfe054f82e8e2c (tree 7f745a9ba06199f3d072634b9082f94d47b3ef35)
src/secp256k1 in HEAD currently refers to tree 7f745a9ba06199f3d072634b9082f94d47b3ef35
GOOD
```

**Comment by sipa** [comment]
Updated to also include https://github.com/bitcoin-core/secp256k1/pull/454.

**Review by gmaxwell — APPROVED** [review]
re-ACK

**Comment by fanquake** [comment]
Tested the subtree-merge ACK
```
[pull/10323/local-merge 53b64555f] Merge #10323: Update to latest libsecp256k1 master
 Date: Wed May 17 16:58:22 2017 +0800
#10323 Update to latest libsecp256k1 master into master
* 525282769 Update to latest libsecp256k1 (Pieter Wuille) (pull/10323/head)
* e7c1b4490 Squashed 'src/secp256k1/' changes from 8225239..84973d3 (Pieter Wuille)

Dropping you on a shell so you can try building/testing the merged source.
Run 'git diff HEAD~' to show the changes being merged.
Type 'exit' when done.
bash-3.2$ git fetch https://github.com/bitcoin-core/secp256k1.git
remote: Counting objects: 3934, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 3934 (delta 0), reused 0 (delta 0), pack-reused 3928
Receiving objects: 100% (3934/3934), 1.61 MiB | 110.00 KiB/s, done.
Resolving deltas: 100% (2762/2762), done.
From https://github.com/bitcoin-core/secp256k1
 * branch                HEAD       -> FETCH_HEAD
bash-3.2$ contrib/devtools/git-subtree-check.sh src/secp256k1
src/secp256k1 in HEAD was last updated to upstream commit 84973d393ac240a90b2e1a6538c5368202bc2224 (tree 0cedbba829a5b38b750b2952af49b45880c32117)
src/secp256k1 in HEAD currently refers to tree 0cedbba829a5b38b750b2952af49b45880c32117
GOOD
```

**Pull request merged**
