### PR TITLE
[0.21] gitian: Use custom MacOS code signing tool 

### PR DESCRIPTION
**Pull request by achow101**
Backport of #20880 and #22190

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Is this to be merged before `0.21.2rc1`?

**Comment by achow101** [comment]
> Is this to be merged before `0.21.2rc1`?

Ideally before rc2, as rc1 is already tagged.

**Comment by MarcoFalke** [comment]
`0.21.2rc1` isn't tagged yet, but I guess we can, right after merge of this

**Review by maflcko — COMMENTED** [review]
cherry-pick-only ACK 0fe60a84ae 🍀

<details><summary>Show signature and timestamp</summary>

Signature:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

cherry-pick-only ACK 0fe60a84ae 🍀
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEE+rVPoUahrI9sLGYTzit1aX5ppUgFAlwqrYAACgkQzit1aX5p
pUjTsgv+OWnF0qiPGkQ6gXIMFyU4/JYUiEM77mmcT4L3McDRU5gX+KSg1DFjE2PN
CF+UWqCQnpEP9nze6AzWmvseYw2t6MFZcAveF2VAcmYWo53+gkDpRbThFC9BYvy/
8NwBhE6jty81Fu84lizftPmspORSMJ1NAU3ZZw19ZimFSHikIaRv11GE+OOntVJW
etkWFU3pmJWpP+BX57w7rNX3oB0wQGCiBAszs4jvbsHE0mOlyKsz5FlhVWWSTaVR
T9nhAiE5rkvYrveMeTuCmpRPrHnAESeQrIKJJ/HTuo8+jQPM/wHQCjnXkOVfZu6v
ZFZ+ooYpPmDgH/8K02fLZwBeOagSwHNut0TN7JQ83vncAWqTdvsD3nm0HlWckrks
HXHtN7mJ7U930rLUiiFTNtmpXTxd9wN52YYJYfGMHH8jlCJuMe/hMXKEWtXKcMHW
uNABTjNoN5adJ++o1Zx5IwjQ/4qX+L7nBbG9JhfFi2+qdQSQuq7jkjGoMEh1iHSw
mHX4jemz
=FhzS
-----END PGP SIGNATURE-----
```

[Timestamp of file with hash `bac76ff36b468b8567f590452420bcb503b8ea743179cf2946e9430c6655fd4e  -`](https://opentimestamps.org/info/?004f70656e54696d657374616d7073000050726f6f6600bf89e2e884e892940108bac76ff36b468b8567f590452420bcb503b8ea743179cf2946e9430c6655fd4ef0109d8193f5dfad2e31b58b44bd5f43ef0708fff01063f465fb7778e28878e515246af7fd2608f10460cda199f008ecd3a81b960d6c6d0083dfe30d2ef90c8e2c2b68747470733a2f2f626f622e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267fff0109b6c7e642b1679a54595f30c303e1ae408f10460cda199f0085f904d50fdf209b70083dfe30d2ef90c8e232268747470733a2f2f6274632e63616c656e6461722e636174616c6c6178792e636f6dfff0109c14b8d7ac7fdfd297bfc948bd97feaa08f120b521cdff09c7aad508950bd10cd5be7e83de8427514f9db8655975303538d74c08f10460cda199f00891b4878ebe5eccfb0083dfe30d2ef90c8e2e2d68747470733a2f2f616c6963652e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267f010d3cacc13d64b837bad5661626a50193708f120d0c491f72261680700f5d1d4e06a14b5ab3df56b67a2f34a03ddbcc0e12ede2208f10460cda19af0086a032b9cf91e04980083dfe30d2ef90c8e292868747470733a2f2f66696e6e65792e63616c656e6461722e657465726e69747977616c6c2e636f6d)

</details>

**Pull request merged**
