### PR TITLE
tests: Don't assume presence of __builtin_mul_overflow(…) in MultiplicationOverflow(…) fuzzing harness

### LINKED ISSUE #18389: fuzzing: compilation error ‘__builtin_mul_overflow’ does not have pointer to integer type
I'm using Debian, compiling current master (5bf45fe2a9642f8ae8f8a12bcbf8f8b4770421ad) after configure with `./configure --disable-shared --enable-tests --enable-fuzz CC=${AFLPATH}/afl-clang CXX=${AFLPATH}/afl-clang++`.

Getting this error:
```[+] Instrumented 442 locations (64-bit, hardened mode, ratio 100%).
  CXX      test/fuzz/test_fuzz_key-fuzz.o
afl-cc 2.52b by <lcamtuf@google.com>
test/fuzz/integer.cpp:152:27: error: default initialization of an object of const type 'const SigningProvider' without a
      user-provided default constructor
    const SigningProvider store;
                          ^
                               {}
1 error generated.
Makefile:14931: recipe for target 'test/fuzz/test_fuzz_integer-integer.o' failed
```

If I configure for gcc, I get this error:
```
test/fuzz/multiplication_overflow.cpp: In instantiation of ‘void {anonymous}::TestMultiplicationOverflow(FuzzedDataProvider&) [with T = bool]’:
test/fuzz/multiplication_overflow.cpp:41:58:   required from here
test/fuzz/multiplication_overflow.cpp:21:75: error: argument 3 in call to function ‘__builtin_mul_overflow’ does not have pointer to integer type
     const bool is_multiplication_overflow_builtin = __builtin_mul_overflow(i, j, &result_builtin);
                                                                           ^
Makefile:15155: recipe for target 'test/fuzz/test_fuzz_multiplication_overflow-multiplication_overflow.o' failed
```

Funny enough, it works on my macbook locally :)
cc @practicalswift

### PR DESCRIPTION
**Pull request by practicalswift**
Don't assume presence of `__builtin_mul_overflow(…)` in `MultiplicationOverflow(…)` fuzzing harness.

Fixes #18389.

### CODE REVIEW

**Comment by naumenkogs** [comment]
`afl-cc 2.52b by <lcamtuf@google.com>
test/fuzz/multiplication_overflow.cpp:20:44: error: missing binary operator before token "("
 #if defined(__has_builtin) && __has_builtin(__builtin_mul_overflow)
                                            ^`
This is with gcc.
FYI i'm compiling with make -j4, if that makes any difference.

**Comment by naumenkogs** [comment]
Using 3748e1daec3f3b597e642d5eb86adb21fade6e36, got this with gcc:

`test/fuzz/multiplication_overflow.cpp:20:44: error: missing binary operator before token "("
 #if defined(__has_builtin) && __has_builtin(__builtin_mul_overflow)
                                            ^
In file included from ./util/system.h:22:0,
                 from ./addrman.h:15,
                 from test/fuzz/deserialize.cpp:6:`

**Comment by practicalswift** [comment]
@naumenkogs Oh, thanks! Clang-isms now removed :)  Please re-review!

**Comment by naumenkogs** [comment]
```
test/fuzz/multiplication_overflow.cpp: In instantiation of ‘void {anonymous}::TestMultiplicationOverflow(FuzzedDataProvider&) [with T = bool]’:
test/fuzz/multiplication_overflow.cpp:55:58:   required from here
test/fuzz/multiplication_overflow.cpp:30:75: error: argument 3 in call to function ‘__builtin_mul_overflow’ does not have pointer to integer type
     const bool is_multiplication_overflow_builtin = __builtin_mul_overflow(i, j, &result_builtin);
                                                                           ^
afl-as 2.52b by <lcamtuf@google.com>```

I also noticed that I have gcc 5.4.0. Perhaps I should just update my compilers? I dunno what are the expectations.

**Comment by naumenkogs** [comment]
Updated both compilers, didn't help with this particular issue I mention above.

**Comment by practicalswift** [comment]
@naumenkogs Thanks for testing! Hopefully fixed now. Would you mind testing the latest version? :)

**Comment by naumenkogs** [comment]
ACK 7c1ac70

**Pull request merged**
