### PR TITLE
Fix macOS failing to flush blockfiles to disk for certain external drives

### LINKED ISSUE #26455: Flushing block file to disk failed when using external drive on macOS Ventura
I kept getting an error regarding Flushing Block to disk. I've tried to use bitcoin core V0.23 and it doesn't help; although V0.22 was better at loading the backup file, but I couldn't send any of my bitcoin out. I can't seem to load the wallet or the backup file properly. Not a coder and hoping someone can help. I don't think it's an issue with the hard drive. Any suggestion? I'm on MacOSx Ventura 13.0. 

Debug.log file:

2022-11-04T20:34:28Z Using wallet /Volumes/Extreme SSD/bruceltd wallet.dat
2022-11-04T20:34:28Z BerkeleyEnvironment::Open: LogDir=/Volumes/Extreme SSD/database ErrorFile=/Volumes/Extreme SSD/db.log
.
.
.
2022-11-04T20:58:16Z FileCommit: fcntl F_FULLFSYNC failed: 25
2022-11-04T20:58:16Z ERROR: SerializeFileDB: Failed to flush file /Volumes/Extreme SSD/peers.176f

db.log file:
fsync: Inappropriate ioctl for device
PANIC: Inappropriate ioctl for device
txn_checkpoint: failed to flush the buffer cache: DB_RUNRECOVERY: Fatal error, run database recovery

### PR DESCRIPTION
**Pull request by john-moffett**
This PR attempts to close (or at least help) #26455 (and closed duplicates #26400 #26530).

### Context

macOS's `fsync` only flushes writes to the drive, but doesn't ask the drive to *immediately* commit the data to permanent storage (ie - physically write it) ([manpage](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/fsync.2.html)). The data will eventually be physically written, but there are no guarantees when it will happen -- it could be several seconds or more. For a stronger 'immediate-write' guarantee, they offer an `F_FULLFSYNC` option to `fcntl` ([manpage](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/fcntl.2.html#//apple_ref/doc/man/2/fcntl:~:text=current%20file%20offset.-,F_FULLFSYNC,-Does%20the%20same)) to accomplish that. This `fsync`-on-macOS behavior has caused [historical problems](https://github.com/bitcoin/bitcoin/issues/2770#issuecomment-22686426) in this project for macOS builds, so, since then, the `F_FULLSYNC` approach has been used for writing (see #3000).

However, certain external drives or filesystems do not support `fcntl` with `F_FULLFSYNC` option. (And some that *do* supposedly support the option do not actually do it.) These drives/filesystems will typically report `errno` `ENOTSUP` or `ENOTTY`, which is what was reported in the referenced issues. [However, there is no reliable way to determine lack of support](https://github.com/google/leveldb/commit/296de8d5b8e4e57bd1e46c981114dfbe58a8c4fa), so **relying on specific error codes is insufficient**.

This bug seems to only be affecting macOS 13 (Ventura) systems, but in theory, any macOS version could be affected.

### What other projects have done

Other projects, including [LevelDB](https://github.com/google/leveldb/commit/296de8d5b8e4e57bd1e46c981114dfbe58a8c4fa), [SQLite](https://sqlite.org/src/file?name=src/os_unix.c&ci=5c669f5f399fe899#:~:text=If%20the%20FULLFSYNC%20failed%2C%20fall%20back%20to%20attempting%20an%20fsync()), and [MariaDB](https://github.com/MariaDB/server/commit/746fd9fdacc52ccc297db7703ea9288b67138167) have experienced similar issues, and have taken the strategy of falling back on the (less reliable) `fsync` when `F_FULLFSYNC` isn't supported. (See helpful [Twitter thread](https://twitter.com/TigerBeetleDB/status/1422855270716293123).) Some (SQLite, MariaDB, LevelDB) fall back to `fsync` on *any* error, and others only fall back on specific errors (BerkeleyDB 4.8 [falls back only on `ENOTSUP`](https://github.com/observerdev/db-4.8.30/blob/3c75267f11336acb1be06bed419e8056cc689d09/os/os_fsync.c#L81-L88), which is why this PR may not fully fix #26455, as the wallet is getting the error `ENOTTY`.)

### This PR

I propose to follow that general strategy and fall back on `fsync` if `F_FULLFSYNC` fails for any reason, while preserving both error codes for debugging. 

(I think we should also print the error strings using `SysErrorString` rather than print the raw platform-dependent error codes, but I wanted to keep this PR as atomic as possible and save those changes (4 or 5 lines in addition to these) for another PR (which I'd be happy to submit -- or modify this PR to include).)

### CODE REVIEW

**Review by luke-jr — CHANGES_REQUESTED** [review]
Since fsync doesn't do the whole job, it shouldn't silence the error/return-false when F_FULLFSYNC fails.

And if, as you say, some drives claim to have done it while they actually haven't, should we perhaps consider falling back to fsync even if F_FULLFSYNC succeeds? (Or maybe F_FULLFSYNC always at least does the equivalent of fsync? In which case I ask: does it do so even if F_FULLFSYNC returns an error?)

**Comment by john-moffett** [comment]
> Since fsync doesn't do the whole job, it shouldn't silence the error/return-false when F_FULLFSYNC fails.

Sorry, I was unclear. (I'll edit my comment.) `fsync` does eventually physically write to disk on macOS, but it just does it on its own time. It's more vulnerable to corruption / data loss if, for example, the machine or drive loses power. The `F_FULLFSYNC` option is better just because it actually physically writes *immediately* after it flushes to disk. Prior to #3000, the macOS version just used `fsync`. This PR goes back to using `fsync` if the (better) `F_FULLFSYNC` isn't available. 

> And if, as you say, some drives claim to have done it while they actually haven't, should we perhaps consider falling back to fsync even if F_FULLFSYNC succeeds?

Some drives claim to write immediately with the `fcntl F_FULLFSYNC` call, but in reality only do the equivalent of macOS's version of `fsync` -- that is, they just flush to disk, return ASAP, and let the disk actually physically write whenever it wants, rather than blocking until the physical write is complete.

> Or maybe F_FULLFSYNC always at least does the equivalent of fsync?

I think that's what happens for the drives that 'lie', which is what I just talked about. However, I don't think any actual flushes or physical writes happen if `F_FULLFYNC` returns an error.

**Review by jamesob — APPROVED** [review]
ACK e663ee9b448c2aad7449666b07d7fb87ea492d31 ([`jamesob/ackr/26534.1.john-moffett.fix_macos_failing_to_flu`](https://github.com/jamesob/bitcoin/tree/ackr/26534.1.john-moffett.fix_macos_failing_to_flu))

Thanks for the great PR and welcome to the project! 

The patch is compact and well-described. Conceptually it's pretty simple: in a
nutshell this just calls `fsync()` should we fail the more specific `fcntl()`
call. There is good precedent for this approach; bitcoin [already relies on this
strategy](https://github.com/jamesob/bitcoin/blob/e663ee9b448c2aad7449666b07d7fb87ea492d31/src/leveldb/util/env_posix.cc#L381-L394) in our vendored leveldb code.

I've built and reveiewed the change locally.

<details><summary>Show signature data</summary>
<p>

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK e663ee9b448c2aad7449666b07d7fb87ea492d31 ([`jamesob/ackr/26534.1.john-moffett.fix_macos_failing_to_flu`](https://github.com/jamesob/bitcoin/tree/ackr/26534.1.john-moffett.fix_macos_failing_to_flu))

Thanks for the great PR and welcome to the project! 

The patch is compact and well-described. Conceptually it's pretty simple: in a
nutshell this just calls `fsync()` should we fail the more specific `fcntl()`
call. There is good precedent for this approach; bitcoin [already relies on this
strategy](https://github.com/jamesob/bitcoin/blob/e663ee9b448c2aad7449666b07d7fb87ea492d31/src/leveldb/util/env_posix.cc#L381-L394)
in our vendored leveldb code.

I've built and reveiewed the change locally.
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEEGNRVI1NPYuZCSIrGepNdrbLETwUFAmOEw90ACgkQepNdrbLE
TwUNBQ//QTTTV7TKsRbXSjXw1efU7jP/srJHtJoDNfTj8ZV4vbqfkrERGITi+Aud
DAi5RhdU9PyO5hX5Z19bDuGoGxg3CHFNE6gKH2NXwdxsO7E1yJ44N+QQlvId9cJB
+52xm+rXQeP4/aHHwmo6JuFmQCJC6Hsri7SYNbtJJWSU+qg+HSjAemtj4HKemZk3
vupd4uPThcsrtHjen6ksW5EofXOikATl86BCYA/X0HC4mG7vQSbR5co1S0bVc2y7
2RxVOeAe0TI8HvBKiOzCT2fBRVmF/OL1vE3Uks4X8ObZLv3D3eLF7Lz2Kmu57n18
sRKgE/o0PtlxwaTW4Sz19WtN3D3lOVE3lx1W/+vRi3RNHTSf4PqtvxZO02S1Kq9I
IhhhekQIvrDsOrgaydyyTjTgxT3CRYiZI7uDTEu8xPqSo6GTNG9WpFC2olOWGLna
1vlOA/edBeZ0WCagEHGtouxnicvKUYzVK56uIpbJA2pnbnbnyempaEBs592LBxh+
O/WJPsTqPGVZa0YhaMYk2TCVBA+XBAQsdkRYlkHLZw8OJsa5E+6k1TVZ1aXAFGOm
BJ1AI6LOgMeeR9qZrdjHoroR9xFyC4kS4h+/BmKUSM6mhLaYoOoNaenCOlXK7RGV
TcVocuW1tJrC4bgiC0ParDeFas5s0SsaUMrJJV5I+788QLcco4A=
=JarI
-----END PGP SIGNATURE-----

```

</p></details>

<details><summary>Show platform data</summary>
<p>

```
Tested on Linux-6.0.2-arch1-1-x86_64-with-glibc2.36

Configured with ./configure --without-bdb 'CXXFLAGS=-fPIE -pipe -O2 -g -Wthread-safety-analysis -Wall -Werror=sign-compare ' --disable-gui-tests --disable-fuzz-binary --enable-wallet --enable-debug --with-daemon --enable-natpmp-default CXX=/usr/bin/clang++ CC=/usr/bin/clang PYTHONPATH= --disable-shared --with-pic --enable-benchmark=no --enable-module-recovery --enable-module-schnorrsig --disable-shared --with-pic --enable-benchmark=no --enable-module-recovery --enable-module-schnorrsig --no-create --no-recursion

Compiled with /usr/bin/ccache /usr/bin/clang++ -std=c++17 -mavx -mavx2 -mpclmul -fPIE -pipe -O2 -g -Wthread-safety-analysis -Wall -Werror=sign-compare  -O0 -g3 -ftrapv -fdebug-prefix-map=$(abs_top_srcdir)=.  -Wstack-protector -fstack-protector-all -fcf-protection=full -fstack-clash-protection -msse4.1 -msse4.2 -msse4 -msha  i

Compiler version: clang version 14.0.6
```

</p></details>

**Comment by jamesob** [comment]
Also, the single failing CI job just needs a kick but apparently I don't have perms to rerun it from the Cirrus CI page.

**Comment by hebasto** [comment]
> Also, the single failing CI job just needs a kick but apparently I don't have perms to rerun it from the Cirrus CI page.

Kicked.

**Comment by luke-jr** [comment]
>fsync does eventually physically write to disk on macOS, but it just does it on its own time. It's more vulnerable to corruption / data loss if, for example, the machine or drive loses power.

All writes are by default "on their own time". The _entire purpose_ of fsync is to force it to be immediate and block on that, so that after the call returns, there is no risk of corruption / data loss from something as simple as a power failure.

So if that isn't happening, this function has failed, and should return an error. (If we don't care, it should be ignored or otherwise handled the same for all failure cases, not just some.)

**Comment by john-moffett** [comment]
@jamesob , thank you for your kind words and the time you took to review.

@luke-jr Thanks for the comment, Luke. I believe I understand your point -- that`FileCommit` exists to assure that the data is actually physically written by the time the function returns, so we shouldn't let macOS get away with breaking that contract just because the hardware doesn't support it. It's better to simply fail (or, alternatively, allow other systems to get away with the same behavior). 

My thinking was that doing macOS's poor `fsync` was better than leaving the hardware unsupported. To be fair, it does do *something* in this case -- it flushes the buffer to the drive. However, it doesn't provide the [full guarantee implied by the comments](https://github.com/bitcoin/bitcoin/blob/d415b7261c05dafbc3e65eea72d270b2bed0958b/src/util/system.h#L57-L58). My assumption was that it was more of a 'best-effort' situation.

I'll obviously defer to your judgment in situations like these, so I'm happy to close this if my understanding of your comment was correct.

**Comment by luke-jr** [comment]
I agree we should do _something_. If FULLFSYNC fails, calling fsync is reasonable.

If we are unable to flush, ideally we should inform the user (perhaps make it a GUI-visible warning?), and let them choose another storage device.

OTOH, for block files, we can always reprocess the block again if needed, so that might actually be a better solution if we can't flush properly.

**Comment by luke-jr** [comment]
Looking at this again, it seems fflush failure indicates the write actually failed, and in that case we should terminate the program entirely.

If any of the others fail, I think we should post a warning to the user (maybe just before/during IBD?) and continue.

And in the meantime (out of scope here IMO), we shouldn't be flushing block files at all. It's an expensive operation, and usually unnecessary. Instead, we should just ensure we can recover cleanly from missing or corrupt recent block data.

**Comment by luke-jr** [comment]
With regard to my last (out of scope) comment, I am thinking more for performance reasons. There's no reason we can't detect the missing block data when we verify blocks at startup, and handle it gracefully.

**Review by fanquake — COMMENTED** [review]
> This bug seems to only be affecting macOS 13 (Ventura) systems, but in theory, any macOS version could be affected.

Do we know what has changed in macOS Ventura to make this start occuring? You say this could affect other versions, but given things only started breaking again with the release of Ventura (and users claim things worked perfectly with previous major versions, i.e: https://github.com/bitcoin/bitcoin/issues/26400#issuecomment-1294887460), clearly something has changed. It would be good to understand what that is.

I've had a look through the XNU sources for Ventura (https://github.com/apple-oss-distributions/xnu/tree/xnu-8792.41.9) and the previous version (Monterey): https://github.com/apple-oss-distributions/xnu/tree/xnu-8020.140.41, and the functions pointed too by https://github.com/google/leveldb/commit/296de8d5b8e4e57bd1e46c981114dfbe58a8c4fa, and didn't see anything obvious.

**Comment by gawlk** [comment]
Hi y'all,

I've been having this issue on 2 m1 Macs with MacOS 13 but it seem to work on the latest MacOS 13.1 Beta !

On both previous Macs, it crashed after a couple minutes but on the latest on it's been running for a while now and still going.

Here's a screenshot:

image

**Comment by john-moffett** [comment]
Thanks, @gawlk !

I suppose this is, indeed, a transient OS bug. I'm also running 13.1 and have tried seven different non-Apple external drives with various filesystems and have yet to trigger the issue.

@fanquake , I had a look at the XNU sources, too, and likewise couldn't find anything, though some code around an [`ENOTTY` emission](https://github.com/apple-oss-distributions/xnu/blob/5c2921b07a2480ab43ec66f5b9e41cb872bc554f/bsd/vfs/kpi_vfs.c#L3934) changed recently:

image

I can't fathom why that would affect us in this case, though, so it may remain a mystery.

Regardless, I think it's best to shelve this. Thanks for the comments!

**Pull request closed without merging**
