### PR TITLE
TRIVIAL: Refactor: inline CTxIn::IsFinal() [ only used in main::IsFinalTx() ]

### PR DESCRIPTION
**Pull request by jtimon**
Less lines.

### CODE REVIEW

**Comment by laanwj** [comment]
NACK. It's less lines, but less self-documenting. Semantic information as well as encapsulation is lost

**Comment by jtimon** [comment]
Another argument is moving more logic out of the primitives, the same reason why @sipa didn't wanted primitives/block to depend on pow.o

**Comment by sipa** [comment]
@laanwj Would making a IsTxOutFinal function in main be acceptable?

**Comment by jtimon** [comment]
I think at that point actual documentation would be better than self-documentation.
Anyway, I'm closing. We can come back to this after isfinaltx has been moved to consensus.o

**Pull request closed without merging**
