### PR TITLE
Net: Do not re-enable Onion network when it was disabled via onlynet

### LINKED ISSUE #13378: P2P: Node with onlynet=ipv6 connects outgoing to Onion
Running bitcoind 0.16.1rc1 64-Bit binary release on Linux

### What I did
I have now setup IPv6 connection for my node (but only outgoing, since my providers router does not allow incoming IPv6 traffic...)
I have running also Tor on localhost with bitcoin (not really) "hidden" service, in parallel to IPv4.

So I was curious and set 
onlynet=ipv6
in bitcoin.conf (before, "onlynet" was not set)

### Expected behavior
Only IPv6 connections, both incoming and outgoing, no Tor traffic, no traffic to local Tor hidden service.

### Actual behavior
Node connects to IPv6, IPv4 and Tor, see screenshot of GUI debug window connection tab.

Also, there are error messages in the debug log that I had not before:
("Keine Berechtigung" means "No permission" in English)

2018-06-03 12:41:46 Loaded 71277 addresses from peers.dat  324ms
2018-06-03 12:41:46 init message: Lade Sperrliste...
2018-06-03 12:41:46 init message: Starte Netzwerk-Threads...
2018-06-03 12:41:46 init message: Laden abgeschlossen
2018-06-03 12:41:46 opencon thread start
2018-06-03 12:41:46 net thread start
2018-06-03 12:41:46 dnsseed thread start
2018-06-03 12:41:46 addcon thread start
2018-06-03 12:41:46 msghand thread start
2018-06-03 12:41:46 GUI: Platform customization: "other"
2018-06-03 12:41:46 GUI: PaymentServer::LoadRootCAs: Loaded  159  root certificates
2018-06-03 12:41:55 Imported mempool transactions from disk: 2019 succeeded, 0 failed, 0 expired, 0 already there
2018-06-03 12:41:57 Loading addresses from DNS seeds (could take a while)
2018-06-03 12:41:57 219 addresses found from DNS seeds
2018-06-03 12:41:57 dnsseed thread exit
2018-06-03 12:42:07 New outbound peer connected: version: 70015, blocks=525773, peer=0
**2018-06-03 12:44:06 GUI: QAccessibleTable::child: Invalid index at:  3 0
2018-06-03 12:44:06 GUI: Cannot creat accessible child interface for object:  QTableView(0x55960b4b1040, name = "peerWidget")  index:  29
2018-06-03 12:44:06 GUI: QAccessibleTable::child: Invalid index at:  3 0
2018-06-03 12:44:06 GUI: Cannot creat accessible child interface for object:  QTableView(0x55960b4b1040, name = "peerWidget")  index:  29
2018-06-03 12:44:06 GUI: QAccessibleTable::child: Invalid index at:  3 0
2018-06-03 12:44:06 GUI: Cannot creat accessible child interface for object:  QTableView(0x55960b4b1040, name = "peerWidget")  index:  29
2018-06-03 12:44:11 GUI: QAccessibleTable::child: Invalid index at:  2 0
2018-06-03 12:44:11 GUI: Cannot creat accessible child interface for object:  QTableView(0x55960b4b1040, name = "peerWidget")  index:  22
2018-06-03 12:44:11 GUI: QAccessibleTable::child: Invalid index at:  2 0
2018-06-03 12:44:11 GUI: Cannot creat accessible child interface for object:  QTableView(0x55960b4b1040, name = "peerWidget")  index:  22
2018-06-03 12:44:11 GUI: QAccessibleTable::child: Invalid index at:  2 0
2018-06-03 12:44:11 GUI: Cannot creat accessible child interface for object:  QTableView(0x55960b4b1040, name = "peerWidget")  index:  22
2018-06-03 12:44:51 connect() to [2601:98a:4203:6e9d:68b9:19cf:e683:6932]:8333 failed after select(): Keine Berechtigung (13)
2018-06-03 12:45:33 connect() to [2a00:c1a0:4888:a500:cc5b:3e64:8aba:d6b4]:8333 failed after select(): Keine Berechtigung (13)
2018-06-03 12:45:38 connect() to [2001:981:9cae:1:7c4b:8f56:ab7c:78f]:8333 failed after select(): Keine Berechtigung (13)**

bildschirmfoto

### PR DESCRIPTION
**Pull request by ghost**
Fixes #13378

If set `onlynet=ipv4` or `onlynet=ipv6` (implicating the attempt to disable onion network) without this patch, Bitcoin Core would re-enable onion network (setting onion network to status "reachable", when it was initially set to "unreachable" (aka "limited" in the code). This happened when `proxy` or `onion` parameters where set, or when `listenonion` was set to 1 (which is the default).

I think, the users initial choice of disabling onion network should be honored instead of quietly being overwritten.

I have testet with
`onlynet=ipv4`
`onlynet=ipv6`
`onlynet=onion`
(each for itself, no multiple `onlynet` settings)
and without specifying `onlynet`
With this patch, the node only connects to the specified network (or to all networks in the last test case)

### CODE REVIEW

**Comment by wodry** [comment]
I tested also the following case:
When Tor is running on `127.0.0.1:9050`, and the following two options are set together:
`proxy=127.0.0.1:9050`
`onlynet=ipv4`
then a Onion Hidden Service will be started and announced automatically via Tor ControlPort as usual, but the node will not connect outgoing to Onion addresses, but outgoing connections to IPv4 addresses will go through Tor.

**Comment by laanwj** [comment]
Needs rebase, but also I don't think simply removing `SetLimited` on `NET_ONION` everywhere is the right solution.

**Comment by practicalswift** [comment]
Could be closed?

**Comment by wodry** [comment]
> Could be closed?

Thanks for reaction. What's Your objective for closing? Is the issue solved, or do You think there is no issue, or do You think the PR is not so good, in that case any other idea?

**Comment by practicalswift** [comment]
@wodry I noticed that this PR hasn't been rebased in a long time so I simply assumed it was abandoned :-)

Please rebase and respond to @laanwj:s feedback and this PR won't be closed due to staleness :-)

**Comment by wodry** [comment]
Rebased (I hope I made it right, was my first stale PR rebase).
@laanwj Maybe You could give more details about why You think the PR wouldn't be the right solution.

**Comment by Saibato** [comment]
> Rebased (I hope I made it right, was my first stale PR rebase).
> @laanwj Maybe You could give more details about why You think the PR wouldn't be the right solution.

Hi @wodry  You are almost correct, those settings are total meaningless since they are true
by default, and in #7553 the mess was introduced that will prevent, onlynet selections to work
correctly with onion proxys. since then it was and is possible that an onion proxy will be created later in torcontrol, that does not care about the onlynet flags, according to doku a bug since then not much noticed.

How do you like the diff, this will fix both your issue and the problem with torcontrol and different proxy settings other than 127.0.0.1:9050?
Please feel free to take and copy paste what you like, i will then review ...

``` Diff
diff --git a/src/init.cpp b/src/init.cpp
index 8d9566edc..00354c90f 100644
--- a/src/init.cpp
+++ b/src/init.cpp
@@ -1397,6 +1397,9 @@ bool AppInitMain(const util::Ref& context, NodeContext& node)
             strSubVersion.size(), MAX_SUBVERSION_LENGTH));
     }
 
+    // Future devs please note: the underlying structure is default all nets are reachable
+    // So here if onlynet defined we set all routeable false and then mask in all desired nets to *true*.
+    // Use IsReachable(netname) to determine later this user settings.
     if (gArgs.IsArgSet("-onlynet")) {
         std::set<enum Network> nets;
         for (const std::string& snet : gArgs.GetArgs("-onlynet")) {
@@ -1419,7 +1422,6 @@ bool AppInitMain(const util::Ref& context, NodeContext& node)
     // -proxy sets a proxy for all outgoing network traffic
     // -noproxy (or -proxy=0) as well as the empty string can be used to not set a proxy, this is the default
     std::string proxyArg = gArgs.GetArg("-proxy", "");
-    SetReachable(NET_ONION, false);
     if (proxyArg != "" && proxyArg != "0") {
         CService proxyAddr;
         if (!Lookup(proxyArg, proxyAddr, 9050, fNameLookup)) {
@@ -1430,16 +1432,18 @@ bool AppInitMain(const util::Ref& context, NodeContext& node)
         if (!addrProxy.IsValid())
             return InitError(strprintf(_("Invalid -proxy address or hostname: '%s'"), proxyArg));
 
-        SetProxy(NET_IPV4, addrProxy);
-        SetProxy(NET_IPV6, addrProxy);
-        SetProxy(NET_ONION, addrProxy);
+        if (IsReachable(NET_IPV4)) SetProxy(NET_IPV4, addrProxy);
+        if (IsReachable(NET_IPV6)) SetProxy(NET_IPV6, addrProxy);
+        if (IsReachable(NET_ONION)) SetProxy(NET_ONION, addrProxy);
+        // -onlynet will at least leave one allowed, so we now set the name proxy
         SetNameProxy(addrProxy);
-        SetReachable(NET_ONION, true); // by default, -proxy sets onion as reachable, unless -noonion later
+        // by default, -proxy sets also an onion proxy, if allowed by -netonly flags, unless -noonion later
     }
 
     // -onion can be used to set only a proxy for .onion, or override normal proxy for .onion addresses
     // -noonion (or -onion=0) disables connecting to .onion entirely
     // An empty string is used to not override the onion proxy (in which case it defaults to -proxy set above, or none)
+
     std::string onionArg = gArgs.GetArg("-onion", "");
     if (onionArg != "") {
         if (onionArg == "0") { // Handle -noonion/-onion=0
@@ -1452,10 +1456,15 @@ bool AppInitMain(const util::Ref& context, NodeContext& node)
             proxyType addrOnion = proxyType(onionProxy, proxyRandomize);
             if (!addrOnion.IsValid())
                 return InitError(strprintf(_("Invalid -onion address or hostname: '%s'"), onionArg));
-            SetProxy(NET_ONION, addrOnion);
-            SetReachable(NET_ONION, true);
+            if (IsReachable(NET_ONION)) {
+                SetProxy(NET_ONION, addrOnion);
+            } else return InitError(strprintf(_("Invalid request network not allowed:  '%s'"), onionArg));
         }
     }
+    for (int n = 0; n < NET_MAX; n++) {
+       Network net = (enum Network)n;
+       if (net != NET_UNROUTABLE) LogPrintf("Net [%s] outbound allowed %d\n", GetNetworkName(net), IsReachable(net));
+    }
 
     // see Step 2: parameter interactions for more information about these
     fListen = gArgs.GetBoolArg("-listen", DEFAULT_LISTEN);
diff --git a/src/torcontrol.cpp b/src/torcontrol.cpp
index 84118b36e..7bcb96d67 100644
--- a/src/torcontrol.cpp
+++ b/src/torcontrol.cpp
@@ -522,15 +522,21 @@ void TorController::auth_cb(TorControlConnection& _conn, const TorControlReply&
     if (reply.code == 250) {
         LogPrint(BCLog::TOR, "tor: Authentication successful\n");
 
-        // Now that we know Tor is running setup the proxy for onion addresses
+         // Now that we know Tor is running setup the proxy for onion addresses
         // if -onion isn't set to something else.
-        if (gArgs.GetArg("-onion", "") == "") {
-            CService resolved(LookupNumeric("127.0.0.1", 9050));
-            proxyType addrOnion = proxyType(resolved, true);
-            SetProxy(NET_ONION, addrOnion);
-            SetReachable(NET_ONION, true);
+        // Or if we have already an outbound proxy defined. we skip this footgun gracefully.
+        proxyType addrOnion;
+        if (IsReachable(NET_ONION)) {
+            if (gArgs.GetArg("-onion", "") == "" && !GetProxy(NET_ONION, addrOnion)) {
+                CService resolved(LookupNumeric("127.0.0.1", 9050));
+                addrOnion = proxyType(resolved, gArgs.GetBoolArg("-proxyrandomize", true));
+                if (SetProxy(NET_ONION, addrOnion)) {
+                    // Here the 'do not default dox the service' line?
+                    SetNameProxy(addrOnion);
+                    LogPrintf("tor: Default outbound tor .onion address proxy is set to 127.0.0.1:9050\n");
+                }
+            }
         }
-
         // Finally - now create the service
         if (private_key.empty()) // No private key, generate one
             private_key = "NEW:RSA1024"; // Explicitly request RSA1024 - see issue #9214

**Comment by wodry** [comment]
> Please feel free to take and copy paste what you like, i will then review ...

@Saibato I had created this PR quite long ago and have forgotten what this is all about in detail, and it looks according to You that things changed also. So, please feel free to create a new PR, You could mention this PR there, and this PR could be closed then.

**Comment by Saibato** [comment]
> > Please feel free to take and copy paste what you like, i will then review ...
> 
> @Saibato I had created this PR quite long ago and have forgotten what this is all about in detail, and it looks according to You that things changed also. So, please feel free to create a new PR, You could mention this PR there, and this PR could be closed then.

Yup, will mention this. you clearly found and fixed a missbehave of the node that is not fixed since  #7553 and your fix would have worked then. Things change a bit and I will add a fix to the PR #19358. Thx. :+1:

**Comment by fanquake** [comment]
[See above](https://github.com/bitcoin/bitcoin/pull/14425#issuecomment-650034083):

> Saibato I had created this PR quite long ago and have forgotten what this is all about in detail, and it looks according to You that things changed also. So, please feel free to create a new PR, You could mention this PR there, and this PR could be closed then.

**Pull request closed without merging**
