### PR TITLE
qt: Remove menu icons

### PR DESCRIPTION
**Pull request by laanwj**
Remove the icons from the application menu. Why remove?

- They are inconsistently applied, some actions had icons, some newer ones don't. Good luck coming up with a sensible icon for everything
- Menu icons don't seem to have a place in modern UI: for example, GNOME, MacOS have stopped showing these a long time ago (see https://github.com/bitcoin/bitcoin/pull/16584#issuecomment-521195090)
- Less bikeshedding opportunity about "what should the icon for this be"

Removed icons:

```
/icons/quit            res/icons/quit.png
/icons/about           res/icons/about.png
/icons/about_qt        res/icons/about_qt.png
/icons/options         res/icons/configure.png
/icons/key             res/icons/key.png
/icons/verify          res/icons/verify.png (also .svg)
/icons/debugwindow     res/icons/debugwindow.png
/icons/open            res/icons/open.png
/icons/info            res/icons/info.png
/icons/filesave        res/icons/filesave.png
```
I checked that these icons are used nowhere else.

Removed from the menu not removed from the repository, because still referenced by other parts of the code:
```
/icons/lock_closed
/icons/edit
/icons/address-book
/icons/send
```

### CODE REVIEW

**Comment by practicalswift** [comment]
Concept ACK

**Comment by hebasto** [comment]
Concept ACK

**Comment by MarcoFalke** [comment]
Before (x11 Gnome / wayland):
Screenshot from 2019-08-14 13-45-14 Screenshot from 2019-08-14 13-45-32

After (x11 Gnome / wayland):
Screenshot from 2019-08-14 13-43-35 Screenshot from 2019-08-14 13-44-12

**Comment by MarcoFalke** [comment]
ACK e181eb2b19c5bdccd36e7fd84d928b561ef98011

<details><summary>Show signature and timestamp</summary>

Signature:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK e181eb2b19c5bdccd36e7fd84d928b561ef98011
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEE+rVPoUahrI9sLGYTzit1aX5ppUgFAlwqrYAACgkQzit1aX5p
pUjijQv/WDprJlrAN4OhF4JNEnYn9CJqzuzCYgv1Vwvl/IkEa70NiJzcXO0r9pS2
+rWz/ysMadkiSnqYyTGBAAX9NXU7R/wiY0z2YtwgE0+gyo0yFqd4EwQB7g1pvZfB
G103EG8mOiDrZ6ZgZn9aFlRwAevUx2QXkad4V9JT4ssXgI6SYwsuQh4H7/c+iOj0
zQf87oyi1SVTJgFOUAP72q45D83fm09tGwhZTGnaMaAmFr9pMVpCwVeR0hMxVveD
CA3+VNS2CbPq5l4++pjK7FO6lWM9tW74Gkv1slv9iGb4sPdKihsOv35/OSEZOtwP
SO5vp1RfieLCXSVUaohm0uP4bS3QnT8VL8SDTdXscE1md9NU9ycyVXjxlsYC8SiF
qoxyL1fHI4SJVrJr5t+tP2YMZCvbl7AFrd2Qg6dX7J8E07/ZzQLY/AJ0Ul1JPR4A
eaIp5S+juXvBLY9ZReYwJCIHf0BF8B3mNKphot48CE9/wJsvdlqsubiQOC7Eho04
WU6bV19x
=ld0Q
-----END PGP SIGNATURE-----
```

[Timestamp of file with hash `1104ade14aa4e0052c1230cc7604a8017dc830605d57010203b11cabe43e401a  -`](https://opentimestamps.org/info/?004f70656e54696d657374616d7073000050726f6f6600bf89e2e884e8929401081104ade14aa4e0052c1230cc7604a8017dc830605d57010203b11cabe43e401af0101f42539ea2121d607169cb76dde3183008fff0103f521955aacb8c3b994c156e532acd1608f1045d544ba8f0081d7c3025ed04bbf00083dfe30d2ef90c8e232268747470733a2f2f6274632e63616c656e6461722e636174616c6c6178792e636f6dfff0104981eb7af14b4a06447c0f1dfe03f38108f1045d544ba8f008d0e8673ac0cda9320083dfe30d2ef90c8e2e2d68747470733a2f2f616c6963652e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267fff010776fe64dc0342cc74c1a3a35d9fa375108f1045d544ba8f008fb5432f367bd45370083dfe30d2ef90c8e2c2b68747470733a2f2f626f622e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267f0108ee204503f0b117c820d81f6e54c4bda08f1045d544ba8f0085d48d381d48510940083dfe30d2ef90c8e292868747470733a2f2f66696e6e65792e63616c656e6461722e657465726e69747977616c6c2e636f6d)

</details>

**Comment by emilengler** [comment]
Concept NACK what is with people who can't read? When I was in kindergarten and primary school these were essential for me (especially in english software). Also in countries like Venezuela where Bitcoin is used a lot, 5% of the population cannot read and Bitcoin should be accessible for anyone

**Comment by hebasto** [comment]
ACK e181eb2b19c5bdccd36e7fd84d928b561ef98011, tested on Linux Mint 19.2 + Cinnamon 4.2.3:

before:
Screenshot from 2019-08-14 21-10-59-0

with e181eb2b19c5bdccd36e7fd84d928b561ef98011: 
Screenshot from 2019-08-14 21-20-16-0

**Comment by MarcoFalke** [comment]
@hebasto It changes the background color as well?

**Comment by hebasto** [comment]
> It changes the background color as well?

No, it does not. The former build is gitian and the latter is compiled against system Qt. And my DE has dark theme activated.

**Comment by promag** [comment]
Concept ACK!

**Comment by gapeman** [comment]
Agree with @emilengler about people who have problems with English language or don't have the option to use bitcoin-qt in their own language.
On the other hand I agree with @laanwj about inconsistency and so called bikeshedding. 

I think it's worth keeping them, and if we do, I'd be glad to help with creating/searching for the missing icons.

**Comment by laanwj** [comment]
> Concept NACK what is with people who can't read?

QtAccessibility and text-to-speech would probably be the best in that case, as it also helps people who are blind. I think this is far outside the scope of this issue though.

(No, the little icons besides menu items don't actually help people that can't read in any significant way, do you think they could navigate the Send interface, or the transaction list right now ?)

**Comment by promag** [comment]
Concept ACK!

**Comment by fanquake** [comment]
Concept ACK. Agree with all of @laanwj's points. I think this repository has far higher priority things to do than be worrying about / arguing over dropdown menu icons.

As I mentioned in the other PR. I don't think I've seen these icons on macOS for quite some time, if ever?

master (f418c3379cbad8caaf3e988caf727fe62b218f8c):
master

this PR (e181eb2b19c5bdccd36e7fd84d928b561ef98011):
no-icons

**Comment by jonasschnelli** [comment]
ACK e181eb2b19c5bdccd36e7fd84d928b561ef98011 (needs rebase though)

**Comment by gapeman** [comment]
NACK.
Recognizing icons is much faster than reading the menus, there's studies about that. I don't read the menu, I look at the icons - maybe some of you do too.
The send interface I can also imagine navigating without being able to read (english) with the help of icons that are there, though of course I get laanwj's point. We aren't here to solve the problem of illiteracy.
But if your point is "there's too much problems with icons so we'll remove them", then I very much regret making that filesave PR which (in?)directly led to this. I think people's opinion differs from the developers' perspective and a lot of people will miss the icons if they're gone.

**Comment by laanwj** [comment]
> The send interface I can also imagine navigating without being able to read (english)

I think equating not being able to read *English* with illiteracy (and dyslexia etc) is wrong. There's a whole, active project at transifex (https://www.transifex.com/bitcoin/bitcoin/) to provide translations and localizations of the GUI in tons of different languages. If there isn't a reasonable translation in your language, please help update it.

I'm all for accessibility for disadvantaged people, and if you want to work on that, that'd be wonderful. But I've never seen PRs from you to improve accessibility otherwise, so please, don't use them as a pretense to make this specific point about style.

**Comment by promag** [comment]
Could someone try `QApplication::instance()->setAttribute(Qt::AA_DontShowIconsInMenus)`? If it works we could avoid deleting icons for now.

**Comment by gapeman** [comment]
Just to make sure: I mean and I meant no disrespect whatsoever to anyone here.

I didn't want to equate illiteracy with anything else. Perhaps I phrased it wrong.
I am active at transifex and I am helping with translating into my native language. I've also made an issue https://github.com/bitcoin/bitcoin/issues/16591 regarding some translations.

Regarding my contributions, I've only just started contributing a few days ago.
My point is, I think this PR would hurt accessibility in some ways, and is not about style. We obviously disagree.

**Comment by laanwj** [comment]
> Could someone try QApplication::instance()->setAttribute(Qt::AA_DontShowIconsInMenus)? If it works we could avoid deleting icons for now.

I think deleting the icons would be a feature, not a problem, when they're unused. They'd still be in git history.

I think this is too controversial, closing. remind me not to get involved in UI issues.

**Comment by Sjors** [comment]
There might be a way to avoid bike-shedding over icons and yet keep them, which is to use [QIcon fromTheme](https://doc.qt.io/qt-5/qicon.html#fromTheme). That would still involve removing the existing icon set.

Apple's [Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/macos/menus/menu-anatomy/) recommend mostly avoiding menu icons, or at least using highly standardized ones:
Schermafbeelding 2019-08-15 om 13 20 18

They generally know what they're doing, although unfortunately they don't really explain the motive here. Interestingly Apple uses icons extensively inside application windows, just not in the menu. I guess the moral is that important stuff shouldn't be exclusively in the menu.

Since we do still use icons in the application windows, removing them from the menu doesn't fully stop bike shedding.

**Comment by MarcoFalke** [comment]
ACK on either removing them or replacing them with familiar icons, as per https://github.com/bitcoin/bitcoin/pull/16612#issuecomment-521611093

Working against common design guidelines doesn't make Bitcoin Core more accessible

**Comment by practicalswift** [comment]
ACK 390874c722c5af0b37cb94151ffb49986eab5f7d -- diff looks correct

> Working against common design guidelines doesn't make Bitcoin Core more accessible

Agree fully.

**Comment by l2a5b1** [comment]
Please reopen this pull request.

ACK 390874c722c5af0b37cb94151ffb49986eab5f7d - Bitcoin Core has a very simple application menu. As long as the menu items describe their actions clearly and unambiguously then the icons alongside the label are redundant and offer very little value, if anything at all.

A good application menu just needs menu labels that unambiguously and clearly describe each action. 

Using icons alongside a menu label to describe an action may make sense when

- it is not possible to unambiguously and succinctly describe menu actions. The icon alongside the menu label can then provide hints to the user.

- an application has a (configurable) toolbar and application menu so that the items on each one are analogous to each other (usually the case when there are a lot of actions that the user can perform).

- When menu actions in a menu section represent a collection to a single resource type, for example bookmarks to web pages in a web browser.

UX decisions:

It would be great if we could validate UX decisions, including this one, via usability tests not subjective ACKS or NACKS. 

@moneyball Is Square Crypto already conducting usability tests of the Bitcoin Core software and Bitcoin UX in general?

As far as bikeshedding is concerned:

Every person here contributes to Bitcoin Core for its own reasons. Some care deeply about strong conformance to best C++ practices; others about code style; or UX design; or cryptography and what have you. I think pull requests and constructive or passionate input regarding whatever Bitcoin Core development related topic should be welcomed.

**Comment by moneyball** [comment]
@l2a5b1 Square Crypto is still in the process of hiring a designer. I expect this to take awhile. We will then need to determine prioritization of projects, and I am not sure if the Core wallet will be at the top of the list. However, one of our goals is to help catalyze and grow a design community for Bitcoin, so that there is more design talent available and interested in helping many projects including the Core wallet.

**Comment by gapeman** [comment]
+1 on usability testing. Users' perspective should be important.

It might be that programmers and developers see software in another light than end users. For me, icons are a faster way of recognizing things - as mentioned before, humans recognize pictures much faster than words.
I also don't know what the "common design guidelines" would be. Are any people here actual designers?

An option would be to keep the icons and give the user a chance to toggle them back on if they want.
But I think we should ask users what they think.

**Comment by Sjors** [comment]
>  toggle them back on

That's a net increase in code complexity; we'd still need to bike shed over icons, but now also maintain and test an additional setting.


Good UI is very hard to do by group consensus. This is why #10102 (multiprocess bitcoin) is an important development. It would ultimately allow alternative GUI implementations to be first class citizens of the Bitcoin Core wallet. Right now any alternative GUI would have to use the RPC, which is not powerful enough (although projects like BTCPay do use it).
 
It's important to conserve review time & energy for important-but-hard stuff like multi-process bitcoin. It's one thing to have many small pull requests, but it's a whole other thing for those pull requests to draw lots of energy from bike-shedding, which is inevitable when touching the UI (been there, see https://github.com/bitcoin/bitcoin/pull/11605).

**Comment by promag** [comment]
> > Could someone try QApplication::instance()->setAttribute(Qt::AA_DontShowIconsInMenus)? If it works we could avoid deleting icons for now.
> 
> I think deleting the icons would be a feature, not a problem, when they're unused. They'd still be in git history.

@laanwj that's not my point. `QAction` can be associated to multiple widgets and displayed differently - I don't know if we have these. My point is that we could first hide menu icons only and keep the actions with icons in the case those are associated to other widgets. Note that this is a Qt feature.

That said I don't think icons in menu items improve accessibility - well structured menus, unambiguous labels and shortcuts do improve accessibility.

My personal opinion is that menus without icons look more clean and professional.

**Comment by kallewoof** [comment]
ACK 390874c722c5af0b37cb94151ffb49986eab5f7d

I don't buy that it's faster to look at icons vs reading text, and as mentioned, accessibility support is the way to go for people with special needs. Translations is the way to go for people who don't speak English. (Come on, having people use a tool in a language they don't understand to transfer money around? Let's not encourage that at all.)

**Comment by jonasschnelli** [comment]
utACK 390874c722c5af0b37cb94151ffb49986eab5f7d

**Comment by luke-jr** [comment]
Post-humourous concept NACK: Apple doesn't dictate design guidelines for anything other than macOS. On other systems, removing the icons contradicts application expectations.

(But if nobody is willing to do the work to fix them, maybe it's for the best...)

**Comment by GChuf** [comment]
I'm still willing to help with the icons.

To address the initial reasons for removal, I'm sure there are sensible icons out there for every menu option and inconsistency could be solved. Of course the new proposed icons might spark up a debate again, which leads us to bikeshedding - however, the problem might not lie in the icons themselves, but in people willing to argue over something below their skill level and of low priority, even though they consider the icons useless (we did remove them).

Whether or not you believe images to be faster or slower than text ("believe" being the operative word), I think it would be sensible to agree that images are (or can be) complementary to text.
And regarding accessibility: although icons don't solve every problem, they could help people with dyslexia, poor vision, learning english, and so on.

**Comment by luke-jr** [comment]
Well, if you're willing to do the work, please open a PR adding the new icons back in. :)

Note that one unfortunately-common "gotcha" is that icons should be licensed under MIT or MIT-like terms.

**Pull request merged**
