### PR TITLE
tests: Add initialization order fiasco detection in Travis

### PR DESCRIPTION
**Pull request by practicalswift**
Add initialization order fiasco detection in Travis :)

Context: https://github.com/bitcoin/bitcoin/pull/17670#issuecomment-562035813

This would have caught the `events_hasher` initialization order issue introduced in #17573  and fixed in #17670.

Output in case of an initialization order fiasco:

```
==7934==ERROR: AddressSanitizer: initialization-order-fiasco on address 0x557098d79200 at pc 0x55709796b9a3 bp 0x7ffde524dc30 sp 0x7ffde524dc28
READ of size 8 at 0x557098d79200 thread T0
    #0 0x55709796b9a2 in CSHA256::Finalize(unsigned char*) src/crypto/sha256.cpp:667:25
    #1 0x5570978150e9 in SeedEvents(CSHA512&) src/random.cpp:462:19
    #2 0x5570978145e1 in SeedSlow(CSHA512&) src/random.cpp:482:5
    #3 0x5570978149a3 in SeedStartup(CSHA512&, (anonymous namespace)::RNGState&) src/random.cpp:527:5
    #4 0x55709781102d in ProcRand(unsigned char*, int, RNGLevel) src/random.cpp:571:9
    #5 0x557097810d19 in GetRandBytes(unsigned char*, int) src/random.cpp:576:59
    #6 0x557096c2f9d5 in (anonymous namespace)::CSignatureCache::CSignatureCache() src/script/sigcache.cpp:34:9
    #7 0x557096511977 in __cxx_global_var_init.7 src/script/sigcache.cpp:67:24
    #8 0x5570965119f8 in _GLOBAL__sub_I_sigcache.cpp src/script/sigcache.cpp
    #9 0x557097bba4ac in __libc_csu_init (src/bitcoind+0x18554ac)
    #10 0x7f214b1c2b27 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:266
    #11 0x5570965347d9 in _start (src/bitcoind+0x1cf7d9)

0x557098d79200 is located 96 bytes inside of global variable 'events_hasher' defined in 'random.cpp:456:16' (0x557098d791a0) of size 104
  registered at:
    #0 0x557096545dfd in __asan_register_globals compiler-rt/lib/asan/asan_globals.cpp:360:3
    #1 0x557097817f8b in asan.module_ctor (src/bitcoind+0x14b2f8b)

SUMMARY: AddressSanitizer: initialization-order-fiasco src/crypto/sha256.cpp:667:25 in CSHA256::Finalize(unsigned char*)
```

### CODE REVIEW

**Comment by practicalswift** [comment]
Fails as expected for the two ASAN jobs in Travis:

```
make[3]: *** [test/amount_tests.cpp.test] Error 1
Makefile:14006: recipe for target 'test/amount_tests.cpp.test' failed
=================================================================
==25881==ERROR: AddressSanitizer: initialization-order-fiasco on address 0x55e6e8811540 at pc 0x55e6e3f3e333 bp 0x7fff60848af0 sp 0x7fff60848ae8
READ of size 8 at 0x55e6e8811540 thread T0
    #0 0x55e6e3f3e332 in CSHA256::Finalize(unsigned char*) /home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-pc-linux-gnu/src/crypto/sha256.cpp:667:25
    #1 0x55e6e3e63905 in SeedEvents(CSHA512&) /home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-pc-linux-gnu/src/random.cpp:462:19
    #2 0x55e6e3e62dd3 in SeedSlow(CSHA512&) /home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-pc-linux-gnu/src/random.cpp:482:5
    #3 0x55e6e3e634cf in SeedStartup(CSHA512&, (anonymous namespace)::RNGState&) /home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-pc-linux-gnu/src/random.cpp:527:5
    #4 0x55e6e3e5fddc in ProcRand(unsigned char*, int, RNGLevel) /home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-pc-linux-gnu/src/random.cpp:571:9
    #5 0x55e6e3e5fba1 in GetRandBytes(unsigned char*, int) /home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-pc-linux-gnu/src/random.cpp:576:59
    #6 0x55e6e2682563 in (anonymous namespace)::CSignatureCache::CSignatureCache() /home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-pc-linux-gnu/src/script/sigcache.cpp:34:9
    #7 0x55e6e2682563 in __cxx_global_var_init.11 /home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-pc-linux-gnu/src/script/sigcache.cpp:67
    #8 0x55e6e2682563 in _GLOBAL__sub_I_sigcache.cpp /home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-pc-linux-gnu/src/script/sigcache.cpp
    #9 0x55e6e44a2e1c in __libc_csu_init (/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-pc-linux-gnu/src/test/test_bitcoin+0x4911e1c)
    #10 0x7fe2b094eb27 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b27)
    #11 0x55e6e2698bd9 in _start (/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-pc-linux-gnu/src/test/test_bitcoin+0x2b07bd9)
0x55e6e8811540 is located 96 bytes inside of global variable 'events_hasher' defined in 'random.cpp:456:16' (0x55e6e88114e0) of size 104
  registered at:
    #0 0x55e6e26aa5de in __asan_register_globals (/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-pc-linux-gnu/src/test/test_bitcoin+0x2b195de)
    #1 0x55e6e3e652bb in asan.module_ctor (/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-pc-linux-gnu/src/test/test_bitcoin+0x42d42bb)
```

**Comment by laanwj** [comment]
Concept ACK!

Does this pass with  #17670 or are there other initialization order fiasco in the code?

**Comment by practicalswift** [comment]
@laanwj This is the only fiasco in our code AFAIK :)

**Comment by promag** [comment]
Tested ACK 1f9d5af4f197e7cc0469a0bb25dcbc51dfa537f4, got
```
==3770==ERROR: AddressSanitizer: initialization-order-fiasco on address 0x0001058f70a0 at pc 0x000105542404 bp 0x7ffeeb534ef0 sp 0x7ffeeb534ee8
READ of size 8 at 0x0001058f70a0 thread T0
    #0 0x105542403 in CSHA256::Finalize(unsigned char*) sha256.cpp:667
    #1 0x105433ca0 in SeedEvents(CSHA512&) random.cpp:462
    #2 0x1054300f6 in ProcRand(unsigned char*, int, RNGLevel) random.cpp:482
    #3 0x10542f99a in GetRandBytes(unsigned char*, int) random.cpp:576
    #4 0x104bfcce5 in _GLOBAL__sub_I_sigcache.cpp sigcache.cpp:34
```

Probably rebase with #17670 to have CI green.

**Comment by MarcoFalke** [comment]
ACK 1f9d5af4f197e7cc0469a0bb25dcbc51dfa537f4 👔

<details><summary>Show signature and timestamp</summary>

Signature:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK 1f9d5af4f197e7cc0469a0bb25dcbc51dfa537f4 👔
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEE+rVPoUahrI9sLGYTzit1aX5ppUgFAlwqrYAACgkQzit1aX5p
pUggBgv/WX2CjAhXVFCzZxEXZNk/ypMrUPN0Jg6iclVN5cpR2G7AVGTdiJUCYxCR
TDky/yYSl/soc+Zd8odXNOPIJAP6azPWmD2a7J8ttMB4iCmgQvPQxXarIEKQrC7b
cOU+yNTOe2tNkooir9ZoP6ay8z0GFxa1tsflRipGWeJEZqiLMM1nJo6e9qvfF7lN
MldOOAHo07B4+nmi/7w0Pj6GYfxF9OT17HHkhMiFjaYc+ezBaAbyNRTT/iH7L9dv
7s3d+2Qp2DLE0YvBuofAkNUkeVtg/AU6iKYnUzkNWCxsrhmpmfYG/YLb+wcxYwRI
FwvMNqPQMB+e6E55njqpIkWwsnvhK68ewgAmFTVFJ2mDDmg0mGQV8KEX9Lorjjm3
ZdJD+3DxAn8VfhTQQFS5iS1LTkXPFkZ8y/GHUwX0GBuYNKClpFSGyZe+mKHZK3fU
YkRY7+eVhw6Eg7QkFud9xZ7/IEp8SZWtvfNvBWHAuJGVK/zyzLI+j3bgRUQiXqM+
z2r0XTcX
=3Nui
-----END PGP SIGNATURE-----
```

[Timestamp of file with hash `97c46147814b07ad0e4976949b09e8d622a974ee6005483703d819bc30b4ccb4  -`](https://opentimestamps.org/info/?004f70656e54696d657374616d7073000050726f6f6600bf89e2e884e89294010897c46147814b07ad0e4976949b09e8d622a974ee6005483703d819bc30b4ccb4f010411bf64bb8341d854ef50bae1f9bb58b08fff010094154a1ca8be091a2b2a4e8817b3c8808f1045de948c0f008dcfd16f3706ae7f40083dfe30d2ef90c8e2c2b68747470733a2f2f626f622e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267fff010ccd5dea3ccbc5ef94ea309b86f2b733608f12066b159b59597a818798adb384423a3e8fd305198dfff34c3ee747165d820780408f1045de948c0f00816c0cdb1c0e8c4720083dfe30d2ef90c8e292868747470733a2f2f66696e6e65792e63616c656e6461722e657465726e69747977616c6c2e636f6df010fcc14a2e060f9edaa83965320bcf229e08f1045de948bff00813e4ab508779636f0083dfe30d2ef90c8e232268747470733a2f2f6274632e63616c656e6461722e636174616c6c6178792e636f6d)

</details>

**Pull request merged**
