### PR TITLE
refactor: Split ArgsManager out of util/system

### PR DESCRIPTION
**Pull request by Empact**
By splitting `ArgsManager` and related functions out of the grab-bag `util/system` file, this enables more specific includes, ~referencing `ArgsManager` without pulling in `gArgs`~, and eliminate a circular dependency between `chainparamsbase` and `utils/system`.

The proposed new modules are:
* util/args_manager - ArgsManager and related functions
* util/args - gArgs only - separate to support the goal of limiting the scope of `gArgs`
* util/system - a variety of file system and sytem-related functions

Other notable points:
* I find it a bit concerning that `ArgsManager::ReadConfigFiles` calls `ClearPathCache` and `CheckDataDirOption` on `gArgs` rather than the current `ArgsManager` instance in the status quo.

The new files are nearly unchanged from their sources, so `git diff master --color-moved=dimmed-zebra` could be helpful.

### CODE REVIEW

**Review by dongcarl — COMMENTED** [review]
Concept ACK!

In fact I did almost the exact same thing here 😆: https://github.com/dongcarl/bitcoin/commit/81d1857599b51e82cc63ae734b7834085661cf99

Happy to use your changes though if you're planning on proactively rebasing over master when merge conflicts arise!

One thing: the only difference I can spot between your changes and mine is that you didn't move `BITCOIN_CONF_FILENAME` and `BITCOIN_SETTINGS_FILENAME` out of `util/system.h`, I think doing that makes the split even better? Lmk!

**Comment by Empact** [comment]
@ryanofsky thanks, I consolidated `args_manager` into `args` - I agree the cost in complexity weighs against the minor benefit of limiting `gArgs` access.

**Comment by Empact** [comment]
> In fact I did almost the exact same thing here 😆: https://github.com/dongcarl/bitcoin/commit/81d1857599b51e82cc63ae734b7834085661cf99

@dongcarl Nice! I'm open to rebasing this, and I think it'd be positive to evaluate it independently. I could go either way on the filenames - with this `args` is the larger file, and `system` includes a variety of filesystem-related functionality. 🤷

**Comment by kiminuo** [comment]
Concept ACK, nice work

In commit 066ba007bed96552cfdc6a6ed91199ddc1cace8c (*refactor: Split ArgsManager out of util/system*), I wonder whether it would be good to introduce a constant for `-avoidpartialspends` to reduce a risk of a typo.

Also this PR feels big, would it be reasonable to split it into multiple PRs? I mean having a PR for 066ba007bed96552cfdc6a6ed91199ddc1cace8c is quite easy to review and it can get code review ACKs almost immediately imho. Plus one would avoid the need for many rebases which this big PR risks. I can probably give a hand with it if you need/want.

**Comment by Empact** [comment]
@kiminuo thanks, re "this PR feels big" I think you make a good point, I'll split out a prep work PR. As for the risk of typos, that hasn't been a practice elsewhere in the codebase, but I have an idea or two of an alternative that could apply across the board.

**Comment by Empact** [comment]
See https://github.com/bitcoin/bitcoin/pull/24811 for the setup commits of this PR.

**Comment by Empact** [comment]
This PR impacting the need for `util/system` includes led me to audit those, and the necessity of them. I could perhaps reorder the commits or do a follow up to shrink it down further.

**Comment by dongcarl** [comment]
@Empact I'm wondering if you'd be open to splitting off the last two commits off to their own PR (or just this PR) not based on #24811?

I think "removing references to gArgs and header tree cleanup" (which is what #24811 is doing) probably stands on its own merit and can be done either before or after the "split util/args and util/system" work here.

**Comment by Empact** [comment]
> @Empact I'm wondering if you'd be open to splitting off the last two commits off to their own PR (or just this PR) not based on #24811?

Sure, I'll be happy to try that, but I think some of the prior work is necessary to enable the separation. I'll let you know what I find.

**Comment by Empact** [comment]
Closing in favor of my next attempt: https://github.com/bitcoin/bitcoin/pull/25152

**Pull request closed without merging**
