### PR TITLE
Update libsecp256k1 subtree to current master

### PR DESCRIPTION
**Pull request by fanquake**
This includes changes from the 0.5.0 release: https://github.com/bitcoin-core/secp256k1/releases/tag/v0.5.0

> New function secp256k1_ec_pubkey_sort that sorts public keys using lexicographic (of compressed serialization) order.

> The implementation of the point multiplication algorithm used for signing and public key generation was changed, resulting in improved performance for those operations.
>    The related configure option --ecmult-gen-precision was replaced with --ecmult-gen-kb (ECMULT_GEN_KB for CMake).
>    This changes the supported precomputed table sizes for these operations. The new supported sizes are 2 KiB, 22 KiB, or 86 KiB (while the old supported sizes were 32 KiB, 64 KiB, or 512 KiB).

### CODE REVIEW

**Comment by fanquake** [comment]
cc @real-or-random @jonasnick

**Review by real-or-random — COMMENTED** [review]
Concept ACK

@hebasto Or would you prefer waiting for https://github.com/bitcoin-core/secp256k1/pull/1529?

**Comment by hebasto** [comment]
> Or would you prefer waiting for [bitcoin-core/secp256k1#1529](https://github.com/bitcoin-core/secp256k1/pull/1529)?

Not at all.  [bitcoin-core/secp256k1#1529](https://github.com/bitcoin-core/secp256k1/pull/1529) is not critical because the Bitcoin Core's CMake staging branch does not use the `PROJECT_IS_TOP_LEVEL` variable.

**Comment by hebasto** [comment]
> @real-or-random @jonasnick

Can you confirm that the default value of the new `--with-ecmult-gen-kb` option is optimal for Bitcoin Core?

**Review by hebasto — APPROVED** [review]
ACK a057869aa3c42457570765966cb66accb2375b13, I've got a zero diff with my local branch, which reproduces the subtree update, and `ecmult gen table size   = 86 KiB` in the configure summary.

**Review by jonasnick — APPROVED** [review]
utACK a057869aa3c42457570765966cb66accb2375b13

**Comment by fanquake** [comment]
Guix build (aarch64):
```bash
e7f19ceb7286ff81d1464575418d494dc2143d43cdc8b0e9a1bff7e47cffc773  guix-build-a057869aa3c4/output/aarch64-linux-gnu/SHA256SUMS.part
f7e9fa7ada1cc470342e7851862b25a026add7dbd2a441f22327f516268eabb3  guix-build-a057869aa3c4/output/aarch64-linux-gnu/bitcoin-a057869aa3c4-aarch64-linux-gnu-debug.tar.gz
30e3001bf9e9ea03defd21f094887e7c9a5f5b4c95162fbf5ea7d9cbe7458458  guix-build-a057869aa3c4/output/aarch64-linux-gnu/bitcoin-a057869aa3c4-aarch64-linux-gnu.tar.gz
3c520e52f0d0882b2e14d591a8d17cae25501a038bb5a8140654ba406178c72f  guix-build-a057869aa3c4/output/arm-linux-gnueabihf/SHA256SUMS.part
92319dc4f32bc295ae366847f9e74e14605d1ec37179e3771b1e9ec4ef6c220e  guix-build-a057869aa3c4/output/arm-linux-gnueabihf/bitcoin-a057869aa3c4-arm-linux-gnueabihf-debug.tar.gz
f4ebdef64df27da5bfcf63e03e899701ce2b2164a891b5063775fbee2e7a8def  guix-build-a057869aa3c4/output/arm-linux-gnueabihf/bitcoin-a057869aa3c4-arm-linux-gnueabihf.tar.gz
644b160459f38549d50447366cdfa20a5ad5fb5a810a513fa0742b8e080f7be2  guix-build-a057869aa3c4/output/arm64-apple-darwin/SHA256SUMS.part
e92a26a0cb219d77ba6acecff9df907af9aeb3717833c14632948da1cefbf295  guix-build-a057869aa3c4/output/arm64-apple-darwin/bitcoin-a057869aa3c4-arm64-apple-darwin-unsigned.tar.gz
75ea0be162a822d7ec7fbee6c547107f690d919fbc82679179eb25cd2a8eebc3  guix-build-a057869aa3c4/output/arm64-apple-darwin/bitcoin-a057869aa3c4-arm64-apple-darwin-unsigned.zip
0656688b18b2e167f96699ccf2ad09468c68f34c376ed1dc02dac80420c2f30c  guix-build-a057869aa3c4/output/arm64-apple-darwin/bitcoin-a057869aa3c4-arm64-apple-darwin.tar.gz
24a3a1c5a80bd821df79f5958e34d4a8a177b335c98c63b63e73a2ace8e04211  guix-build-a057869aa3c4/output/dist-archive/bitcoin-a057869aa3c4.tar.gz
55abf3736504ac8d273a85fcac304916e0a39bf24c4d9f6af028cf5216e6dfc1  guix-build-a057869aa3c4/output/powerpc64-linux-gnu/SHA256SUMS.part
cd9b9a74162b9ac9899b0b0b59cb6cd4482ae9dde1e6d375dea347e1dbbddfdb  guix-build-a057869aa3c4/output/powerpc64-linux-gnu/bitcoin-a057869aa3c4-powerpc64-linux-gnu-debug.tar.gz
6a8c59084824f7e58c94682b673e9d8cf2acc1486bcaa95dbb5d93d4c2686256  guix-build-a057869aa3c4/output/powerpc64-linux-gnu/bitcoin-a057869aa3c4-powerpc64-linux-gnu.tar.gz
9612c284eb42670134b19c2bd916acfa7de595225b938bb0c7389c72845240f7  guix-build-a057869aa3c4/output/riscv64-linux-gnu/SHA256SUMS.part
bff5c34f69b28d8210a9317ef04d20072a37f63c71936d8b192a5f3a8cdb7e51  guix-build-a057869aa3c4/output/riscv64-linux-gnu/bitcoin-a057869aa3c4-riscv64-linux-gnu-debug.tar.gz
5a0769eeb557b9f55d7fc0d4617b94a8f960b373359450978d96cdb6842f3cae  guix-build-a057869aa3c4/output/riscv64-linux-gnu/bitcoin-a057869aa3c4-riscv64-linux-gnu.tar.gz
e479e9a59ba872a930706c7dceb1760030ac426076a0f1b6cdf8dd71e3f7db3f  guix-build-a057869aa3c4/output/x86_64-apple-darwin/SHA256SUMS.part
79eeabc68b67c9297917faa327fee224ba3e47ffe9d88a95f488bcf317142e61  guix-build-a057869aa3c4/output/x86_64-apple-darwin/bitcoin-a057869aa3c4-x86_64-apple-darwin-unsigned.tar.gz
4b5fa4492b1f9cfa33bec5dda7f6db625e15fc54e0cfb7040bff60ef49b9cc4d  guix-build-a057869aa3c4/output/x86_64-apple-darwin/bitcoin-a057869aa3c4-x86_64-apple-darwin-unsigned.zip
236efa5401e4c7d22d24362fad1a54bae77b23eb2c66c2392b082ab0c93a6eab  guix-build-a057869aa3c4/output/x86_64-apple-darwin/bitcoin-a057869aa3c4-x86_64-apple-darwin.tar.gz
38805e9576f55aaf2084ca6893f6e0827a22385017433409bc293edf72a8103b  guix-build-a057869aa3c4/output/x86_64-linux-gnu/SHA256SUMS.part
95e6244b99737861d86acb7c73e475d3f4ea7249e63fca1fc2e6f64b5ae5575d  guix-build-a057869aa3c4/output/x86_64-linux-gnu/bitcoin-a057869aa3c4-x86_64-linux-gnu-debug.tar.gz
f7a7baaebb23ee79d3fce16add1085583f7341863402943b4fd4fa2d49e341a0  guix-build-a057869aa3c4/output/x86_64-linux-gnu/bitcoin-a057869aa3c4-x86_64-linux-gnu.tar.gz
2ea1d7e047c3656c1c2018087de694f6c92343296d4489b1c2118048108b17cf  guix-build-a057869aa3c4/output/x86_64-w64-mingw32/SHA256SUMS.part
e5e694259146e79384a78d648295d1bc4b98538813d0c63711d9f22a7d7eae1b  guix-build-a057869aa3c4/output/x86_64-w64-mingw32/bitcoin-a057869aa3c4-win64-debug.zip
85594dbb2bd9e9cf95ff5fb17e0c729c66b03d3c785d556ced10fdfb4e933d1b  guix-build-a057869aa3c4/output/x86_64-w64-mingw32/bitcoin-a057869aa3c4-win64-setup-unsigned.exe
c6d1519cab9e7ed4377bb7c89381e5811566eb7c3a31ce42ec956ec64ef2ceed  guix-build-a057869aa3c4/output/x86_64-w64-mingw32/bitcoin-a057869aa3c4-win64-unsigned.tar.gz
210f594370f3872bee4034765938935ea0f462f3620a6e06f5d521ffc9464eb4  guix-build-a057869aa3c4/output/x86_64-w64-mingw32/bitcoin-a057869aa3c4-win64.zip
```

**Comment by hebasto** [comment]
Ported to the CMake-based build system in https://github.com/hebasto/bitcoin/pull/220.

**Pull request merged**
