### PR TITLE
Add correct bool combiner for net signals

### PR DESCRIPTION
**Pull request by sipa**
Extracted from #5843.

### CODE REVIEW

**Comment by sipa** [comment]
@gavinandresen No clue how to use that boost::bind inside a type descriptor. Feel free to suggest code.

**Comment by laanwj** [comment]
ACK

**Comment by gavinandresen** [comment]
Tested ACK.

My c++ kung fu fails me trying to use boost::bind instead of a CombinerAll class.
But you could save a couple of lines of code like this:

```
diff --git a/src/net.h b/src/net.h
index e500536..81783ab 100644
--- a/src/net.h
+++ b/src/net.h
@@ -26,6 +26,7 @@
 #include <arpa/inet.h>
 #endif

+#include <boost/algorithm/cxx11/all_of.hpp>
 #include <boost/filesystem/path.hpp>
 #include <boost/foreach.hpp>
 #include <boost/signals2/signal.hpp>
@@ -83,11 +84,7 @@ struct CombinerAll
     template<typename I>
     bool operator()(I first, I last) const
     {
-        while (first != last) {
-            if (!(*first)) return false;
-            ++first;
-        }
-        return true;
+        return boost::algorithm::all_of_equal<I, bool>(first, last, true);
     }
 };
```

Take it or leave it, your original code is arguably more readable (doesn't require knowledge of what all_of_equal does).

**Comment by laanwj** [comment]
> #include <boost/algorithm/cxx11/all_of.hpp>

I like the shorter, declarative code. But (looking at the include file name) does that require c++11?

**Comment by gavinandresen** [comment]
This is a boost implementation of functionality already part of C++11 for older C++ compilers. 

--
Gavin Andresen

**Comment by laanwj** [comment]
Ah, right, a boost-ism that can be changed to a c++11-ism, that's great

**Comment by jgarzik** [comment]
ut ACK

**Pull request merged**
