### PR TITLE
Fix typos across bitcoin repository

### PR DESCRIPTION
**Pull request by kittenking**
Fix typos across **bitcoin** repository

**Fixed Files**

```
bitcoin/build-aux/m4/ax_boost_base.m4:13:65: "searchs" is a misspelling of "searches"
bitcoin/src/qt/bitcoin.cpp:314:66: "complate" is a misspelling of "complete"
bitcoin/src/secp256k1/src/tests.c:2123:43: "infinitiy" is a misspelling of "infinity"
```

### CODE REVIEW

**Comment by fanquake** [comment]
Please remove any modifications to historical release notes, as well as any subtrees, i.e leveldb.

**Comment by fanquake** [comment]
Please make changes in a local branch rather than editing in the GitHun UI. As every change will send a new email to those watching the repository.

**Comment by kittenking** [comment]
> Please make changes in a local branch rather than editing in the GitHub UI. As every change will send a new email to those watching the repository.

Oops! Sorry I Completed

**Comment by fanquake** [comment]
Thanks, however I'm going to close this. Please read our [contributing docs](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md), particularly the sections on contributor workflow and squashing commits.

You might also be interested in checking out the [good first issue](https://github.com/bitcoin/bitcoin/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) tag. Generally we dont accept PRs that just fix typos.

**Pull request closed without merging**
