### PR TITLE
[depends] Don't build libevent sample code

### PR DESCRIPTION
**Pull request by fanquake**
Before and after libevent build on OS X.

```
Building libevent...
  GEN      include/event2/event-config.h
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
  CC       buffer.lo
  CC       bufferevent.lo
  CC       bufferevent_filter.lo
  CC       bufferevent_ratelim.lo
  CC       bufferevent_sock.lo
  CC       bufferevent_pair.lo
  CC       event.lo
  CC       evmap.lo
  CC       evthread.lo
  CC       evutil.lo
  CC       evutil_rand.lo
  CC       evutil_time.lo
  CC       listener.lo
  CC       log.lo
  CC       select.lo
  CC       poll.lo
  CC       kqueue.lo
  CC       signal.lo
  CC       evdns.lo
  CC       event_tagging.lo
  CC       evrpc.lo
  CC       http.lo
  CC       evthread_pthread.lo
  CC       sample/dns-example.o
  CC       sample/event-read-fifo.o
  CC       sample/hello-world.o
  CC       sample/http-server.o
  CC       sample/http-connect.o
  CC       sample/signal-test.o
  CC       sample/time-test.o
  CCLD     libevent_core.la
  CCLD     libevent_pthreads.la
  CCLD     libevent.la
  CCLD     libevent_extra.la
  CCLD     sample/event-read-fifo
  CCLD     sample/dns-example
  CCLD     sample/hello-world
  CCLD     sample/http-server
  CCLD     sample/http-connect
  CCLD     sample/signal-test
  CCLD     sample/time-test
Staging libevent...
```

```
Building libevent...
  GEN      include/event2/event-config.h
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
  CC       buffer.lo
  CC       bufferevent.lo
  CC       bufferevent_filter.lo
  CC       bufferevent_pair.lo
  CC       bufferevent_ratelim.lo
  CC       bufferevent_sock.lo
  CC       event.lo
  CC       evmap.lo
  CC       evthread.lo
  CC       evutil.lo
  CC       evutil_rand.lo
  CC       evutil_time.lo
  CC       listener.lo
  CC       log.lo
  CC       select.lo
  CC       poll.lo
  CC       kqueue.lo
  CC       signal.lo
  CC       evdns.lo
  CC       event_tagging.lo
  CC       evrpc.lo
  CC       http.lo
  CC       evthread_pthread.lo
  CCLD     libevent_core.la
  CCLD     libevent_pthreads.la
  CCLD     libevent.la
  CCLD     libevent_extra.la
Staging libevent...
```

### CODE REVIEW

**Comment by promag** [comment]
Trivial ACK f38c051.

**Comment by MeshCollider** [comment]
Trivial ACK https://github.com/bitcoin/bitcoin/pull/11286/commits/f38c05104848db63ad0df85c24eea466dbff8536
Heh, everyone has been building hello-world all this time.

**Comment by achow101** [comment]
utACK f38c05104848db63ad0df85c24eea466dbff8536

**Comment by practicalswift** [comment]
utACK f38c05104848db63ad0df85c24eea466dbff8536 - nice find!

**Pull request merged**
