### PR TITLE
Report minimum ping time in getpeerinfo

### PR DESCRIPTION
**Pull request by TheBlueMatt**

### CODE REVIEW

**Comment by jonasschnelli** [comment]
utACK

**Comment by paveljanik** [comment]
ACK

**Comment by fanquake** [comment]
utACK

**Comment by MarcoFalke** [comment]
minping seems to be zero in most cases. Being connected to 3 "incoming peers" on localhost and 8 "outgoing peers" on testnet I get
```
$ getpeerinfo|grep minping
    "minping": 0,
    "minping": 0,
    "minping": 0,
    "minping": 0.107754,
    "minping": 0,
    "minping": 0,
    "minping": 0,
    "minping": 0,
    "minping": 0.219713,
    "minping": 9.6e-05,
    "minping": 0,
```

**Comment by laanwj** [comment]
@MarcoFalke Good catch: nMinPingUsecTime is left uninitialized on CNode creation. As it is a moving minimum, it should probably default to `std::numeric_limits<int64_t>::max()` initially, not zero.

**Comment by laanwj** [comment]
ACK on this pull.

**Pull request merged**
