### PR TITLE
Remove redundant pre-TopUpKeypool check

### PR DESCRIPTION
**Pull request by instagibbs**
TopUpKeypool already has a quick check for `IsLocked()`

### CODE REVIEW

**Comment by MarcoFalke** [comment]
ACK d40a642c14e4533d74ccd41daae6bcc0734501e0, but could fix the coding style in the wallet method, so that the commit can be reviewed by only looking at the diff: 

```diff
diff --git a/src/wallet/wallet.cpp b/src/wallet/wallet.cpp
index 097b92a262..084ec4599d 100644
--- a/src/wallet/wallet.cpp
+++ b/src/wallet/wallet.cpp
@@ -3423,8 +3423,7 @@ bool CWallet::TopUpKeyPool(unsigned int kpSize)
     {
         LOCK(cs_wallet);
 
-        if (IsLocked())
-            return false;
+        if (IsLocked()) return false;
 
         // Top up key pool
         unsigned int nTargetSize;

**Comment by instagibbs** [comment]
good call @MarcoFalke , done

**Comment by MarcoFalke** [comment]
ACK d75d64b747c1cfca1e203755bdef50c017536bec, only looked at the diff

<details><summary>Show signature and timestamp</summary>

Signature:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK d75d64b747c1cfca1e203755bdef50c017536bec, only looked at the diff
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEE+rVPoUahrI9sLGYTzit1aX5ppUgFAlwqrYAACgkQzit1aX5p
pUhNcwv9GUeiQtaJceUbojPSDPITC/bWmmpQsHHM/smh7Cfg2DvzwDChsilo9aU5
nTWcak7EB/veBx3jy0V1uBcVSJiaF9SMgNX2AnjauA4Y8ShEAEex6HhykB1UsViu
3nHJRfDSfOyQw67H7dW0pnKosAmI1RIQVEsY+o51RQKIaDUQdFveefgZXo9i3VoH
h29eNUwxXqxbC8KK8wyOIeWu+Ej25Kvjqv+TRM9qQpCwj4I0JTREideGksxfAA0s
34BTZBluxOPWvjlbPgOmFaEa7zbfeL/VuEMXdGtPkLc1pXHv7P5KJ+ES1lMiBtVw
tVSF8Ob5AOA203y8WC/EfVC70UGDO64OI2SnxgkZ/LB2C+1bh9kG+AWHtk69p2Wj
CGmqCATo1fOEdg+BOIl8IagPdDh0Ws5YLVgs+wr1QyJiklzsgSzQAugBnn8dDKIf
KzP8e5+OkK8jYUnBGtCkAVdAcjqUFvexWge6QQgjXFa4LJ2nMrOLihNzyL0iYNET
RGMrkdbG
=kvZO
-----END PGP SIGNATURE-----
```

[Timestamp of file with hash `dfcc5bf7dc7fdef37456ef6b7a38e94248b574e921682dbc041268e79e939ed4  -`](https://opentimestamps.org/info/?004f70656e54696d657374616d7073000050726f6f6600bf89e2e884e892940108dfcc5bf7dc7fdef37456ef6b7a38e94248b574e921682dbc041268e79e939ed4f010ac2de67f3adbe7baff394ccdda1d9eaf08fff01046ca3e967472089b1f59516c3a223fbe08f1045d24aeeff008c59315552993bc2f0083dfe30d2ef90c8e232268747470733a2f2f6274632e63616c656e6461722e636174616c6c6178792e636f6dfff01051946867d69094a3acd97ef24201bb6b08f1045d24aef0f00818a6159842454c4c0083dfe30d2ef90c8e292868747470733a2f2f66696e6e65792e63616c656e6461722e657465726e69747977616c6c2e636f6dfff0106cffaa047d04a481dd616832a767ca6508f1045d24aeeff00864fa7088264e35240083dfe30d2ef90c8e2c2b68747470733a2f2f626f622e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267f010945c4fe7f8010192ca5101549743cead08f1045d24aeeff008eccf1e9aa18eaaf10083dfe30d2ef90c8e2e2d68747470733a2f2f616c6963652e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267)

</details>

**Comment by instagibbs** [comment]
Down to one check change due to s/key/destination/ refactoring merged in master.

**Comment by MarcoFalke** [comment]
> Down to one check change due to s/key/destination/ refactoring merged in master.

Are you sure? I think they just have been moved elsewhere.

**Comment by instagibbs** [comment]
@MarcoFalke you'd think since I reviewed the responsible PR I would have known, but no I was wrong :) updated.

**Comment by achow101** [comment]
ACK 96b6dd468a4cb6077d1a2267d620d99d39aac7d0 Reviewed the diff and checked that the `if (!IsLocked()) TopUpKeypool()` pattern is changed everywhere.

**Pull request merged**
