### PR TITLE
release: Windows signing script

### PR DESCRIPTION
**Pull request by theuni**
A dev came around IRC today asking for help with some of these manual steps, so I figured it would be helpful to go ahead and script it up. This is an ancient todo of mine.

To match the osx signing procedure, pack the needed ingredients into the unsigned tarball. This makes the signing procedure very straightforward.

Additionally, the cert chain has been added so that the signer doesn't provide it, only the private key for the codesigning cert.. Note that the gitian recipe for re-attaching the signature does not actually verify this yet, though.

Also added some quick docs for the procedure.

### CODE REVIEW

**Comment by losh11** [comment]
+1

**Comment by losh11** [comment]
👍

**Comment by MarcoFalke** [comment]
Concept ACK 09fe2d9

**Comment by laanwj** [comment]
Concept ACK. Good to automate this!

**Comment by fanquake** [comment]
Concept ACK. Planning on testing this shortly.

**Comment by laanwj** [comment]
Assigning 0.15.0 milestone.

**Comment by theuni** [comment]
Ah, thanks for the reminder. I used the script/certs to sign all of the 0.14.0 binaries and never heard any complaints. So I'm assuming this is good to go :)

**Comment by laanwj** [comment]
Awesome!

**Pull request merged**
