### PR TITLE
clear typo "skipepd" changed to "skipped"

### PR DESCRIPTION
**Pull request by smatthewenglish**
just so. clear typo "skipepd" changed to "skipped".

### CODE REVIEW

**Comment by gmaxwell** [comment]
This is a cosmetic change in leveldb, it should go upstream. https://github.com/google/leveldb/releases

**Comment by MarcoFalke** [comment]
ACK, but we can not merge the pull here as this is a git subtree.

**Comment by s-matthew-english** [comment]
are you sure? If you look here: 
https://github.com/google/leveldb/blob/master/db/log_test.cc

they don't have the typo

**Comment by MarcoFalke** [comment]
@s-matthew-english whoops, it is already fixed and we have a pull open for syncing with upstream: #8613

**Pull request closed without merging**
