### PR TITLE
wallet: Fix ZapSelectTx to sync wallet spends

### PR DESCRIPTION
**Pull request by bvbfan**
Signed-off-by: Anthony Fieroni <bvbfan@abv.bg>

### CODE REVIEW

**Review by ryanofsky — APPROVED** [review]
Code review ACK a04387448f0bf4eddd27b905f554608b6ba3ed00. Code change is simple, and thank you for writing a test!

Logically the change makes sense, but I'd be curious to know what motivation is for the PR (it would be good to expand PR description). It doesn't seem like this going to effect behavior in most cases because map is just keeping track of wallet transactions spending wallet coins, which shouldn't matter if the transactions and coins aren't in the wallet. If there were a python functional test showing where this made a difference, that might motivate and explain the change a little better.

Either way, the change does seem like it is reasonable.

Travis failure sync_mempools timeout in mempool_unbroadcast.py https://travis-ci.org/github/bitcoin/bitcoin/jobs/682269091#L3122 seems spurious and is probably unrelated

**Review by ryanofsky — APPROVED** [review]
Code review ACK 9c59f9c285303659ee1beed7555bbb322e6e6981. Only change since last review tweaking the for loop as suggested

**Comment by adamjonas** [comment]
Compiled and ran tests. @bvbfan, it'd be great if you could expand the PR description to include the motivation and/or include a functional test to better explain this change as [requested above](https://github.com/bitcoin/bitcoin/pull/18850#pullrequestreview-407039712).

**Review by jonatack — COMMENTED** [review]
ACK 9c59f9c285303659ee1beed7555bbb322e6e6981 tested rebased on current master b33136b6ba9887f7d and the new unit test does indeed fail without the change.
```
wallet/test/wallet_tests.cpp(793): Entering test case "ZapSelectTx"
wallet/test/wallet_tests.cpp(819): error: in "wallet_tests/ZapSelectTx": check !wallet->HasWalletSpend(prev_hash) has failed
```
> Logically the change makes sense, but I'd be curious to know what motivation is for the PR (it would be good to expand PR description). It doesn't seem like this going to effect behavior in most cases because map is just keeping track of wallet transactions spending wallet coins, which shouldn't matter if the transactions and coins aren't in the wallet. If there were a python functional test showing where this made a difference, that might motivate and explain the change a little better.

Agree with @ryanofsky and @adamjonas here.

**Comment by jonatack** [comment]
> Logically the change makes sense, but I'd be curious to know what motivation is for the PR (it would be good to expand PR description). It doesn't seem like this going to effect behavior in most cases because map is just keeping track of wallet transactions spending wallet coins, which shouldn't matter if the transactions and coins aren't in the wallet. If there were a python functional test showing where this made a difference, that might motivate and explain the change a little better.

Agree with @ryanofsky and @adamjonas here.

The new unit test does indeed fail without the change.
```
wallet/test/wallet_tests.cpp(793): Entering test case "ZapSelectTx"
wallet/test/wallet_tests.cpp(819): error: in "wallet_tests/ZapSelectTx": check !wallet->HasWalletSpend(prev_hash) has failed
```

**Comment by bvbfan** [comment]
> Compiled and ran tests. @bvbfan, it'd be great if you could expand the PR description to include the motivation and/or include a functional test to better explain this change as [requested above](https://github.com/bitcoin/bitcoin/pull/18850#pullrequestreview-407039712).

The motivation is `mapWallet` is used, in many place, without check (method `at` pretend that hash presents) but that's not exactly true when `mapTxSpends` and `mapWallet` are out of sync. That can lead to crash/data loss in wallet.

**Comment by ryanofsky** [comment]
> The motivation is `mapWallet` is used, in many places, without check (method `at` expects that hash presents) but that's not exactly true when `mapTxSpends` and `mapWallet` are out of sync. That can lead to crash/data loss in wallet.

Thanks, makes sense. It looks like something like this could happen in MarkConflicted: stray entry in mapTxSpends here:

https://github.com/bitcoin/bitcoin/blob/d77170d52687c3d708daffb7976c3e0d345ff7dc/src/wallet/wallet.cpp#L947

could lead to a crash here:

https://github.com/bitcoin/bitcoin/blob/d77170d52687c3d708daffb7976c3e0d345ff7dc/src/wallet/wallet.cpp#L1075

So I think it would be good to merge this PR

**Comment by achow101** [comment]
ACK 9c59f9c285303659ee1beed7555bbb322e6e6981

**Review by meshcollider — COMMENTED** [review]
utACK 9c59f9c285303659ee1beed7555bbb322e6e6981

**Pull request merged**
