### PR TITLE
depends: build FreeType with CMake

### PR DESCRIPTION
**Pull request by fanquake**
Switches Freetype to be built with CMake.

### CODE REVIEW

**Comment by fanquake** [comment]
No-longer a version bump. Just a switch from Autotools -> CMake.

**Comment by fanquake** [comment]
Guix Build (x86_64, aarch64):
```bash
bd6c916cc5fdd322bf9e7e3cecbe45a68551c0135d63b35709b32fccde289834  guix-build-ff4f3deb7b8a/output/aarch64-linux-gnu/SHA256SUMS.part
12c161c6b94ccb15d420fe27f7a812c95247a2614db5f8c6e666e04b5ef0a7d3  guix-build-ff4f3deb7b8a/output/aarch64-linux-gnu/bitcoin-ff4f3deb7b8a-aarch64-linux-gnu-debug.tar.gz
99c6d258715f38c7b56eefd0b08e80552012e8903f26d28225b690f432839545  guix-build-ff4f3deb7b8a/output/aarch64-linux-gnu/bitcoin-ff4f3deb7b8a-aarch64-linux-gnu.tar.gz
53439d3dbbafd509d1ebe875e7b575f85799ebf9afd42a1cbd6f045e348eae69  guix-build-ff4f3deb7b8a/output/arm-linux-gnueabihf/SHA256SUMS.part
2883d8b5f4eff0431bb5a2716a63b6faed5ef956b8c8bcf258b8ef4ab483e7ba  guix-build-ff4f3deb7b8a/output/arm-linux-gnueabihf/bitcoin-ff4f3deb7b8a-arm-linux-gnueabihf-debug.tar.gz
abb4315c5542d42e69d6b8884ea1cc1c10f819113ce5e5c7265ecdf4eaa21ad7  guix-build-ff4f3deb7b8a/output/arm-linux-gnueabihf/bitcoin-ff4f3deb7b8a-arm-linux-gnueabihf.tar.gz
95e77b3dc481dc0c0b1da863a79032cb2fb1530d65c7b35296afe179d3c7ad14  guix-build-ff4f3deb7b8a/output/arm64-apple-darwin/SHA256SUMS.part
b5153fcc9aa10a97b36784329def7f353da00a2f67c4318cb0299d10bf8a564a  guix-build-ff4f3deb7b8a/output/arm64-apple-darwin/bitcoin-ff4f3deb7b8a-arm64-apple-darwin-unsigned.tar.gz
0109129b943a387cad85d66a85c93a5fac2fa16f20b6cf0914d497a4af87cc1c  guix-build-ff4f3deb7b8a/output/arm64-apple-darwin/bitcoin-ff4f3deb7b8a-arm64-apple-darwin-unsigned.zip
18d7fb6f45b585a4313d115ac95f049dfc27b66857571933a3f5851f8ae6d7b0  guix-build-ff4f3deb7b8a/output/arm64-apple-darwin/bitcoin-ff4f3deb7b8a-arm64-apple-darwin.tar.gz
d06400de6864382db4e3b08f3004d4a2b74d1d24531463356c03e1c8b7978de3  guix-build-ff4f3deb7b8a/output/dist-archive/bitcoin-ff4f3deb7b8a.tar.gz
85798edc4eeb382114d296397fd27e3dc70c604a28004dcc26fbec2508266da0  guix-build-ff4f3deb7b8a/output/powerpc64-linux-gnu/SHA256SUMS.part
8a936135175ccd1d2dc55025223de506f7df5d3d2848b454bca90ce4264c80b5  guix-build-ff4f3deb7b8a/output/powerpc64-linux-gnu/bitcoin-ff4f3deb7b8a-powerpc64-linux-gnu-debug.tar.gz
6a9f8afc11918f5b0d9002b33bbad9809027cdc98a08652c53bc2a462f856934  guix-build-ff4f3deb7b8a/output/powerpc64-linux-gnu/bitcoin-ff4f3deb7b8a-powerpc64-linux-gnu.tar.gz
1eb79428eb7bede4d4cfc3aea27c86c28cc8d98c1225e7248ec998d27a0ed7b6  guix-build-ff4f3deb7b8a/output/riscv64-linux-gnu/SHA256SUMS.part
6286b6d74232e10e89906d5f65c6fcf882bd784b808390bd4c2bbdd58676e5ae  guix-build-ff4f3deb7b8a/output/riscv64-linux-gnu/bitcoin-ff4f3deb7b8a-riscv64-linux-gnu-debug.tar.gz
e6ab676aa1429d05d20be9624c26ce1b50bf10b6efe8f96915c317356fd0f59b  guix-build-ff4f3deb7b8a/output/riscv64-linux-gnu/bitcoin-ff4f3deb7b8a-riscv64-linux-gnu.tar.gz
7bcb9f5662f781879e0e10778fcc419b79851e3c6471654d0bac8db299bd6a86  guix-build-ff4f3deb7b8a/output/x86_64-apple-darwin/SHA256SUMS.part
083e4cdd8701011f46371d066a945814b6b34287bcd67c21651fd2ac616f93cf  guix-build-ff4f3deb7b8a/output/x86_64-apple-darwin/bitcoin-ff4f3deb7b8a-x86_64-apple-darwin-unsigned.tar.gz
1f02a9e010bcc6a55cccab5c2312593d79c860ebf3fd3f827afaaec25e698630  guix-build-ff4f3deb7b8a/output/x86_64-apple-darwin/bitcoin-ff4f3deb7b8a-x86_64-apple-darwin-unsigned.zip
1870d6e62bd93960ef859fb78643b00d2ad9188790847b1b009d2f27e80200dc  guix-build-ff4f3deb7b8a/output/x86_64-apple-darwin/bitcoin-ff4f3deb7b8a-x86_64-apple-darwin.tar.gz
b481475a2124d92dc676cc95ef2d9c890050a5ac58780615bf0eaa022ae0f8e2  guix-build-ff4f3deb7b8a/output/x86_64-linux-gnu/SHA256SUMS.part
472b8b03355e2dea86fd77c16c027da2e934f9dc28e1608d517c8bf15dd763cf  guix-build-ff4f3deb7b8a/output/x86_64-linux-gnu/bitcoin-ff4f3deb7b8a-x86_64-linux-gnu-debug.tar.gz
d106b8c4f9ddd5e74eaddd7455a8cce440671b7427f4e67e42e5b2ea29c848bd  guix-build-ff4f3deb7b8a/output/x86_64-linux-gnu/bitcoin-ff4f3deb7b8a-x86_64-linux-gnu.tar.gz
a31709916abd7280ca347eb1a23511a642c400a768de692a644ab3a138e45cba  guix-build-ff4f3deb7b8a/output/x86_64-w64-mingw32/SHA256SUMS.part
b069d45d5b95cb65f32a8aefe2f7ecf5ad97302d9a1169472ad09ebb29ee06c4  guix-build-ff4f3deb7b8a/output/x86_64-w64-mingw32/bitcoin-ff4f3deb7b8a-win64-debug.zip
807b7041b33daa530d5feffd107b23f7ca97b77589450a21a2cc05d3afdc2647  guix-build-ff4f3deb7b8a/output/x86_64-w64-mingw32/bitcoin-ff4f3deb7b8a-win64-setup-unsigned.exe
24c43da78605efdae686411e02aa7da8d28afbc166175ce2b2b8450bacaa92e2  guix-build-ff4f3deb7b8a/output/x86_64-w64-mingw32/bitcoin-ff4f3deb7b8a-win64-unsigned.tar.gz
bace22b2b356dc9875e2c8f462310650470d3c7723d4afccaca0a4dcfb11b6d4  guix-build-ff4f3deb7b8a/output/x86_64-w64-mingw32/bitcoin-ff4f3deb7b8a-win64.zip
```

**Review by theuni — APPROVED** [review]
ACK ff4f3deb7b8adfcc90fb745440ce4be1176552ca

Guix build (x86_64):
```
12c161c6b94ccb15d420fe27f7a812c95247a2614db5f8c6e666e04b5ef0a7d3  aarch64-linux-gnu/bitcoin-ff4f3deb7b8a-aarch64-linux-gnu-debug.tar.gz
99c6d258715f38c7b56eefd0b08e80552012e8903f26d28225b690f432839545  aarch64-linux-gnu/bitcoin-ff4f3deb7b8a-aarch64-linux-gnu.tar.gz
bd6c916cc5fdd322bf9e7e3cecbe45a68551c0135d63b35709b32fccde289834  aarch64-linux-gnu/SHA256SUMS.part
18d7fb6f45b585a4313d115ac95f049dfc27b66857571933a3f5851f8ae6d7b0  arm64-apple-darwin/bitcoin-ff4f3deb7b8a-arm64-apple-darwin.tar.gz
b5153fcc9aa10a97b36784329def7f353da00a2f67c4318cb0299d10bf8a564a  arm64-apple-darwin/bitcoin-ff4f3deb7b8a-arm64-apple-darwin-unsigned.tar.gz
0109129b943a387cad85d66a85c93a5fac2fa16f20b6cf0914d497a4af87cc1c  arm64-apple-darwin/bitcoin-ff4f3deb7b8a-arm64-apple-darwin-unsigned.zip
95e77b3dc481dc0c0b1da863a79032cb2fb1530d65c7b35296afe179d3c7ad14  arm64-apple-darwin/SHA256SUMS.part
2883d8b5f4eff0431bb5a2716a63b6faed5ef956b8c8bcf258b8ef4ab483e7ba  arm-linux-gnueabihf/bitcoin-ff4f3deb7b8a-arm-linux-gnueabihf-debug.tar.gz
abb4315c5542d42e69d6b8884ea1cc1c10f819113ce5e5c7265ecdf4eaa21ad7  arm-linux-gnueabihf/bitcoin-ff4f3deb7b8a-arm-linux-gnueabihf.tar.gz
53439d3dbbafd509d1ebe875e7b575f85799ebf9afd42a1cbd6f045e348eae69  arm-linux-gnueabihf/SHA256SUMS.part
d06400de6864382db4e3b08f3004d4a2b74d1d24531463356c03e1c8b7978de3  dist-archive/bitcoin-ff4f3deb7b8a.tar.gz
8a936135175ccd1d2dc55025223de506f7df5d3d2848b454bca90ce4264c80b5  powerpc64-linux-gnu/bitcoin-ff4f3deb7b8a-powerpc64-linux-gnu-debug.tar.gz
6a9f8afc11918f5b0d9002b33bbad9809027cdc98a08652c53bc2a462f856934  powerpc64-linux-gnu/bitcoin-ff4f3deb7b8a-powerpc64-linux-gnu.tar.gz
85798edc4eeb382114d296397fd27e3dc70c604a28004dcc26fbec2508266da0  powerpc64-linux-gnu/SHA256SUMS.part
6286b6d74232e10e89906d5f65c6fcf882bd784b808390bd4c2bbdd58676e5ae  riscv64-linux-gnu/bitcoin-ff4f3deb7b8a-riscv64-linux-gnu-debug.tar.gz
e6ab676aa1429d05d20be9624c26ce1b50bf10b6efe8f96915c317356fd0f59b  riscv64-linux-gnu/bitcoin-ff4f3deb7b8a-riscv64-linux-gnu.tar.gz
1eb79428eb7bede4d4cfc3aea27c86c28cc8d98c1225e7248ec998d27a0ed7b6  riscv64-linux-gnu/SHA256SUMS.part
1870d6e62bd93960ef859fb78643b00d2ad9188790847b1b009d2f27e80200dc  x86_64-apple-darwin/bitcoin-ff4f3deb7b8a-x86_64-apple-darwin.tar.gz
083e4cdd8701011f46371d066a945814b6b34287bcd67c21651fd2ac616f93cf  x86_64-apple-darwin/bitcoin-ff4f3deb7b8a-x86_64-apple-darwin-unsigned.tar.gz
1f02a9e010bcc6a55cccab5c2312593d79c860ebf3fd3f827afaaec25e698630  x86_64-apple-darwin/bitcoin-ff4f3deb7b8a-x86_64-apple-darwin-unsigned.zip
7bcb9f5662f781879e0e10778fcc419b79851e3c6471654d0bac8db299bd6a86  x86_64-apple-darwin/SHA256SUMS.part
472b8b03355e2dea86fd77c16c027da2e934f9dc28e1608d517c8bf15dd763cf  x86_64-linux-gnu/bitcoin-ff4f3deb7b8a-x86_64-linux-gnu-debug.tar.gz
d106b8c4f9ddd5e74eaddd7455a8cce440671b7427f4e67e42e5b2ea29c848bd  x86_64-linux-gnu/bitcoin-ff4f3deb7b8a-x86_64-linux-gnu.tar.gz
b481475a2124d92dc676cc95ef2d9c890050a5ac58780615bf0eaa022ae0f8e2  x86_64-linux-gnu/SHA256SUMS.part
b069d45d5b95cb65f32a8aefe2f7ecf5ad97302d9a1169472ad09ebb29ee06c4  x86_64-w64-mingw32/bitcoin-ff4f3deb7b8a-win64-debug.zip
807b7041b33daa530d5feffd107b23f7ca97b77589450a21a2cc05d3afdc2647  x86_64-w64-mingw32/bitcoin-ff4f3deb7b8a-win64-setup-unsigned.exe
24c43da78605efdae686411e02aa7da8d28afbc166175ce2b2b8450bacaa92e2  x86_64-w64-mingw32/bitcoin-ff4f3deb7b8a-win64-unsigned.tar.gz
bace22b2b356dc9875e2c8f462310650470d3c7723d4afccaca0a4dcfb11b6d4  x86_64-w64-mingw32/bitcoin-ff4f3deb7b8a-win64.zip
a31709916abd7280ca347eb1a23511a642c400a768de692a644ab3a138e45cba  x86_64-w64-mingw32/SHA256SUMS.part
```

**Review by hebasto — APPROVED** [review]
ACK ff4f3deb7b8adfcc90fb745440ce4be1176552ca, I've verified the actual compile options, they look sane.

**Pull request merged**
