### PR TITLE
test: Fix test_random includes

### PR DESCRIPTION
**Pull request by maflcko**
Follow up of  #8914 to fix gitian builds.

@jonasschnelli Can you try this and see what https://bitcoin.jonasschnelli.ch/pulls/9095 says?

### CODE REVIEW

**Comment by MarcoFalke** [comment]
https://bitcoin.jonasschnelli.ch/pulls/9095/build-linux.log


```
test/coins_tests.cpp:10:30: fatal error: test/test_random.h: No such file or directory
 #include "test/test_random.h"
                              ^
compilation terminated.
```

:confused:

**Comment by jonasschnelli** [comment]
Yes. This fixes my gitian issues present since oct 19th (nightly builds).
Tested ACK fa8278e845b6a80164e13a39f917a101fe14b10d

**Comment by fanquake** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/9095/commits/fa8278e845b6a80164e13a39f917a101fe14b10d

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/9095/commits/fa8278e845b6a80164e13a39f917a101fe14b10d

**Pull request merged**
