### PR TITLE
gui: add prune to intro screen with smart default

### PR DESCRIPTION
**Pull request by Sjors**
This adds a checkbox to the intro screen to enable pruning from the get go.

If the user has plenty of space, it's unchecked by default:

big

If the user has insufficient space it's checked by default:
low

When the user has barely enough space and is likely to need pruning in the near future, this is shown in yellow and we also check the prune box:

medium

The cut-off for this 10 GB above `m_assumed_blockchain_size` (`=240` in `chainparams.cpp`). 

If the user launches the first time with `-prune=...` then we disable the check box and display the correct size (rounded to GB):
Schermafbeelding 2019-08-24 om 20 23 14
 
The 2 GB default matches the settings default. The user can't change it in the intro screen, but can change it later. I'm tempted to increase that default to 10 GB, and then have the intro screen reduce it if space is really tight.

Tips for testing:
* move your existing data dir elsewhere
* wipe data dir at every restart (behavior is different if it exists)
* launch with `bitcoin-qt -resetguisettings -lang=en` (there's some space issues in different languages)
* fake your free space by changing `intro.cpp` line 90: `freeBytesAvailable = 5000000000; // 5 GB`
* try both testnet and mainnet, because settings are seperate. In particular note how step 7 in `GuiMain` switches where `QTSettings settings` points to; this had me thoroughly confused on testnet, because I was setting them too early.

### CODE REVIEW

**Comment by hebasto** [comment]
Concept ACK

**Comment by jb55** [comment]
Awesome! Concept ACK!

**Comment by Sjors** [comment]
It turns out that applying the prune setting on first load was more involved than I thought. As part of the first launch sequence (or if you use `-resetguisettings`) it resets the `QTSettings` object. So you can't just do `settings.setValue("bPrune", true)` before the `OptionsModel` is instantiated. You can't change `QTSettings` later either, because although the settings dialog will look correct and pruning is enabled at next launch, it didn't actually tell the node to prune.

I ended up adding an explicit setter for prune to `OptionsModel` which uses `node->forceSetArg()` internally.

In addition it's necessary to know if the dialog was actually shown to the user, because otherwise the prune settings gets overridden with the default (false) at the next launch. So now there's 5 commits :-)

**Comment by practicalswift** [comment]
Concept ACK

**Comment by instagibbs** [comment]
concept ACK! It's the biggest hurdle to users today if social media is any indicator.

**Comment by achow101** [comment]
> It turns out that applying the prune setting on first load was more involved than I thought. As part of the first launch sequence (or if you use `-resetguisettings`) it resets the `QTSettings` object. So you can't just do `settings.setValue("bPrune", true)` before the `OptionsModel` is instantiated. You can't change `QTSettings` later either, because although the settings dialog will look correct and pruning is enabled at next launch, it didn't actually tell the node to prune.
> ...
> 
> In addition it's necessary to know if the dialog was actually shown to the user, because otherwise the prune settings gets overridden with the default (false) at the next launch. So now there's 5 commits :-)

A long time ago, there was a similar (or same) issue with `strDataDir` in QSettings. Couldn't you just do something similar to how the datadir is handled instead of having all this extra prune specific things?

> I ended up adding an explicit setter for prune to `OptionsModel` which uses `node->forceSetArg()` internally.

Why does `forceSetArg` need to be exposed too? Could you use `SoftSetArg`?

**Comment by promag** [comment]
Concept ACK.

I wonder if this should be the trigger to refactor the intro into a wizard? Maybe like this it's a bit overwhelming?

Had a quick look commit by commit and I think the approach could also be improved, still nice work!

**Comment by Sjors** [comment]
I'm open to rebasing onto a bigger refactor of the intro wizard, but that might reduce the chance of making it into 0.19. 

> Why does forceSetArg need to be exposed too? Could you use SoftSetArg?

`SoftSetArg` is called twice; once during the reset where prune is set to its default 0, and then again when we set it to 1. It fails the second time and instead the settings dialog will show `-prune=0` as an override.

> A long time ago, there was a similar (or same) issue with `strDataDir` in QSettings. 

The reset code contains a workaround for `strDataDir`. It stores it in a temp variable, resets the settings and then sets it again. I could do the same thing for `prune`, but keep in mind that the Intro dialog isn't always shown. So if the default data dir exists and you reset your settings, then prune would still be enabled. I'd rather turn it around and add an explicit setter for the datadir.

**Comment by emilengler** [comment]
Concept ACK
Could you add an option to change the pruning size?
IIRC Bitcoin Knots has such a feature @luke-jr, you might want to take a look at this implementation.

**Comment by promag** [comment]
> I'm open to rebasing onto a bigger refactor of the intro wizard

Let me see if it's that big.

**Comment by luke-jr** [comment]
Yes, this is part of https://github.com/luke-jr/bitcoin/commits/rwconf_gui-0.18%2Bknots

Next step to get there is PR #11082

**Comment by jonasschnelli** [comment]
Nice!
Concept ACK.

**Comment by Sjors** [comment]
@emilengler I'd like to keep the intro screen as simple as possible, not overwhelm users with choices. It's easy to adjust the prune size in settings and the user has plenty of time for that during IBD.

Also note the diminishing returns for a larger prune setting. 10 GB protects you against a 1 month reorg if blocks are 4 MB. Pruned nodes only share the most recent 288 blocks ([BIP-159](https://github.com/bitcoin/bips/blob/master/bip-0159.mediawiki)). Maybe after #15606 we can add another network flag to indicate down to which UTXO snapshot we have blocks. At that point it makes sense to suggest prune sizes worth N years of blocks. Again, rather than explain all those trade-offs on the intro screen, we can just pick a good default and leave the rest to the settings screen.

@luke-jr I think promag is talking about refactoring the intro screen so that it's better suited to handle more settings. In addition to that we could revamp the entire settings system, e.g. with your rw_config PR. I don't think this PR makes those efforts more difficult, or vice versa, so we can merge in any order.

**Comment by luke-jr** [comment]
@Sjors rwconf_gui DOES refactor the intro screen: it has options for pruning, tells you how old your backups can be, etc.

**Review by ryanofsky — APPROVED** [review]
utACK 9924bce317b96ab0c57efb99330abd11b6f16b9a. The changes are very logical, and implement the feature in a clean that way that doesn't add a lot of complication and shouldn't interfere with future improvements. I looked at Luke's branch too, and I think there's also a lot of great stuff there that seems fully compatible with this change.

Not a big concern, but this is also compatible with some changes I'm working on:

- 0ab41dd770c1f13983df528b111cfc8a51fe016a from #15936 stops using `QSettings` for pruning and other settings shared between `bitcoind` and `bitcoin-qt` and instead stores them in the datadir.
- [`79d6760`](https://github.com/bitcoin/bitcoin/commit/79d6760748a646a61ff69517fb33f4b105b42872#diff-55d472da4902ed903a3b3d94f05fec42) from my [ipc branch](https://github.com/ryanofsky/bitcoin/commits/conn-export), gets rid of minute `parseParameters`, `readConfigFiles`,  `softSetArg`, etc interfactions between node and gui code and just updates settings in batches.

**Comment by laanwj** [comment]
Concept ACK

**Comment by GChuf** [comment]
Concept ACK, should make running a node much easier for users.

While looking around I also noticed this - would it be smart to decrease the block download window to 128 for prune mode? 

```
bitcoin/src/validation.h

/** Size of the "block download window": how far ahead of our current height do we fetch?
 *  Larger windows tolerate larger download speed differences between peer, but increase the potential
 *  degree of disordering of blocks on disk (which make reindexing and pruning harder). We'll probably
 *  want to make this a per-peer adaptive value at some point. */
static const unsigned int BLOCK_DOWNLOAD_WINDOW = 1024;
```

**Comment by laanwj** [comment]
Would be nice to get this in before the feature freeze.

@GChuf maybe, though it would negatively affect performance for initial sync on pruned nodes, please open a separate issue for this discussion, it's out of scope here

**Pull request merged**
