### PR TITLE
doc: guix: add lzma python tip

### PR DESCRIPTION
**Pull request by jamesob**
I tripped on this error when attempting to do Guix builds for macOS
from a debian host.

### CODE REVIEW

**Comment by luke-jr** [comment]
Why would you have to reinstall Python? Debian doesn't compile it, so shouldn't the package be the same regardless?

**Comment by jamesob** [comment]
When building the shared libs (`--enable-shared`), if the lzma header is missing Python apparently just skips it. I build my Python from source so I'm not sure how this might work with Debian packaging.

**Comment by laanwj** [comment]
I'm kind of confused here. How does installing headers make a Python package appear? Only if you build Python afterward?

I think it would be better to handle this as a required build check/dependency, e.g. through the conventional `requirements.txt` system.

Specific instructions related to building Python from source is out of scope for this document, i think, as it's definitely not a specific need here. You only need *a* Python with the `lzma` package.

**Comment by jamesob** [comment]
haha okay, well this comment would've probably saved me fifteen minutes but I guess it's out of scope. Will close.

**Comment by jamesob** [comment]
Just for posterity...

All Python installations ship with the `lzma.py` file below, but (I guess) if you compile Python without having the lzma headers installed, you don't get the `.so` file alongside it:
```sh
% ls /usr/local/lib/python3.10/*lzma*
/usr/local/lib/python3.10/_lzma.cpython-39-x86_64-linux-gnu.so  /usr/local/lib/python3.10/lzma.py
```

which then causes the following import to fail:
```py
% grep _lzma /usr/local/lib/python3.10/lzma.py
from _lzma import *
from _lzma import _encode_filter_properties, _decode_filter_properties
```

I don't know why Python builds don't require the lzma headers if this is part of the standard library, but apparently you can have a "valid" Python installation built from source (as I did) that lacks this shared object file.

**Pull request closed without merging**
