### PR TITLE
mining: Rename `-blockmaxcost` to `-blockmaxweight`

### PR DESCRIPTION
**Pull request by laanwj**
As discussed in the 2016-07-14 meeting,
http://www.erisian.com.au/meetbot/bitcoin-core-dev/2016/bitcoin-core-dev.2016-07-14-19.00.html

Needs an analogous change to BIP141: https://github.com/bitcoin/bips/pull/420

### CODE REVIEW

**Comment by MarcoFalke** [comment]
ACK bf70224 (Haven't checked for proper replacement in all places but I imagine check-doc would catch that.)

**Comment by paveljanik** [comment]
src/rpc/blockchain.cpp:            "  \"cost\" : n             (numeric) The block cost\n"
src/rpc/mining.cpp:            "  \"currentblockcost\": nnn,   (numeric) The last block cost\n"

**Comment by paveljanik** [comment]
Hmm, what about using the term "blockcost" instead?

**Comment by laanwj** [comment]
@paveljanik yes if you want to change all occurrences, also in variable names, then there is much more code impact.

**Comment by laanwj** [comment]
Bah, changing all occurences of 'cost' to 'weight' is a huge change.
I'm also having second thoughts about it.
Changing it just in user-facing messages is doable, but yes it also appears in the RPC API, in variable names, in tons of comments. And I suppose those all have to be changed for consistency.

**Pull request closed without merging**
