### PR TITLE
Pull leveldb subtree

### PR DESCRIPTION
**Pull request by maflcko**
Some windows-related fixes.

Sanity check with:

```
git fetch https://github.com/bitcoin-core/leveldb
./test/lint/git-subtree-check.sh src/leveldb

### CODE REVIEW

**Comment by fanquake** [comment]
utACK fa61801 

Pulls in [Use utf-8 to decode filename](https://github.com/bitcoin-core/leveldb/pull/18) and [Fixes to allow building with msvc](https://github.com/bitcoin-core/leveldb/pull/14).

```
michael$ merge 15270
[pull/15270/local-merge ccaccc177] Merge #15270: Pull leveldb subtree
 Date: Sun Jan 27 10:25:17 2019 +0800
#15270 Pull leveldb subtree into master
* fa6180188 Pull leveldb subtree (MarcoFalke) (pull/15270/head)
* 4f2e6c8b8 Squashed 'src/leveldb/' changes from 524b7e36a8..f545dfabff (MarcoFalke)

Dropping you on a shell so you can try building/testing the merged source.
Run 'git diff HEAD~' to show the changes being merged.
Type 'exit' when done.
bash-3.2$ git fetch https://github.com/bitcoin-core/leveldb
remote: Enumerating objects: 547, done.
remote: Counting objects: 100% (547/547), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 1284 (delta 544), reused 545 (delta 544), pack-reused 737
Receiving objects: 100% (1284/1284), 423.61 KiB | 930.00 KiB/s, done.
Resolving deltas: 100% (978/978), completed with 165 local objects.
From https://github.com/bitcoin-core/leveldb
 * branch                HEAD       -> FETCH_HEAD
bash-3.2$ ./test/lint/git-subtree-check.sh src/leveldb
src/leveldb in HEAD currently refers to tree 9a76136301c252c4b6a0ca628381af761f0fba4a
src/leveldb in HEAD was last updated in commit 4f2e6c8b881b7ccda36233332dfd1bd231389a8e (tree 9a76136301c252c4b6a0ca628381af761f0fba4a)
src/leveldb in HEAD was last updated to upstream commit f545dfabff4c2e9836efed094dba99a34fbc6b88 (tree 9a76136301c252c4b6a0ca628381af761f0fba4a)
GOOD
```

**Comment by ken2812221** [comment]
Tested the gitian build binaries. ACK fa6180188b8ab89af97860e6497716405a48bab6

@MarcoFalke just notice that @DrahtBot website is down.

**Comment by MarcoFalke** [comment]
Ah, thx. I forgot to update the cloudflare settings. Should work now.

**Comment by MarcoFalke** [comment]
Tested ACK (didn't look at the code changes)

Current master:

screenshot from 2019-01-29 13-07-34

This pull:
screenshot from 2019-01-29 13-06-50

**Comment by laanwj** [comment]
utACK fa6180188b8ab89af97860e6497716405a48bab6

**Pull request merged**
