### PR TITLE
test: Add test for BIP30 duplicate tx

### PR DESCRIPTION
**Pull request by maflcko**
This adds a test for BIP30 to check that duplicate txs can exist in the blockchain given the first one was completely spent when the second one is added. (Requested by ajtowns in https://github.com/bitcoin/bitcoin/pull/16333#issuecomment-508604071)

We can not add a test that a later duplicate tx overwrites a previous one, because BIP30 is always enforced on regtest. If someone feels strongly about such a test, some Bitcoin Core code would have to be modified, which can be done in a follow up pull request.

Also, add a commit to fix the BIP34 test failures reported in https://github.com/bitcoin/bitcoin/pull/14633#issue-227712540

### CODE REVIEW

**Comment by laanwj** [comment]
Concept ACK

**Comment by sdaftuar** [comment]
> We can not add a test that a later duplicate tx overwrites a previous one, because BIP30 is always enforced on regtest. 

I think we cannot add such a test because it would violate consensus rules, except for the two hardcoded exceptions on mainnet!

Also I think it's worth pointing out that the optimizations we have in place for mainnet, where we don't actually enforce BIP30 explicitly if we're on the BIP34-activating chain we expect to be on, makes regtest-testing less meaningful here.  However, we do rely on BIP 30 being explicitly enforced for alternate chains, which is critical to allowing a node to reorg to the main chain if being fed an alternate early history, so this is probably a good test to add overall.

**Comment by MarcoFalke** [comment]
> I think we cannot add such a test because it would violate consensus rules, except for the two hardcoded exceptions on mainnet!

Yes, we'd have to add a regtest exception as well, and I'd prefer not to modify source code in a pull that only adds tests.

**Comment by ajtowns** [comment]
We check that the hardcoded exceptions work correctly everytime someone does an IBD and we check the non-exceptional case every other block, so doesn't seem like there's much value in adding regtest-only exceptions to me...

**Comment by laanwj** [comment]
Code review ACK fa8489a15511f61a372473927e73c34692bbec23

**Pull request merged**
