### PR TITLE
tests: Skip P2PConnection's is_closing() check when not available

### LINKED ISSUE #13745: mininode tests broken with Python 3.4.2 (Debian Jessie)
The recent change in #13715 broke mininode tests on systems with Python 3.4.2 (as included in Debian Jessie aka oldstable).  This is because the method [`is_closing`](https://docs.python.org/3.4/library/asyncio-protocol.html#asyncio.BaseTransport.is_closing) is only introduced in Python 3.4.4.

A workaround would be to add a `hasattr` condition that only checks `is_closing` if it is actually available - keeping the benefits of #13715 for newer systems while not breaking old systems (basically falling back to the behaviour before #13715 for them).  If that's a desired fix, I'm happy to create a PR for it.

### PR DESCRIPTION
**Pull request by domob1812**
#13715 introduced a new check for `_transport.is_closing()` in mininode's `P2PConnection`'s.  This function is [only available from Python 3.4.4](https://docs.python.org/3.4/library/asyncio-protocol.html#asyncio.BaseTransport.is_closing), though, while Bitcoin Core is supposed to support all Python 3.4 versions.

In this change, we make the check conditional on `is_closing` being available.  If it is not, then we revert to the behaviour before the check was introduced; this means that #13579 is not fixed for old systems, but at least the tests work as they used to do before.

This includes a small refactoring from a one-line lambda to an inline function, because this makes the code easier to read with more and more conditions being added.

Fixes #13745.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
utACK 4728553290aebd9fc22f08c8bc73b05a45fb388a

**Comment by marcoagner** [comment]
utACK 4728553290aebd9fc22f08c8bc73b05a45fb388a

**Comment by flack** [comment]
maybe add a note that this is to support python < 3.4.4, so that it's easier to find and remove this workaround when support for these versions is dropped

**Comment by domob1812** [comment]
Added a comment as suggested by @flack.

**Pull request merged**
