### PR TITLE
wallet: Add TxStateString function for debugging and logging

### PR DESCRIPTION
**Pull request by ryanofsky**
I found this useful while debugging silent conflict between #10102 and #27469 recently

### CODE REVIEW

**Review by furszy — COMMENTED** [review]
ACK dc1520b1

I'm slightly more inclined to encapsulate the string representation into a `toString()` per struct so we don't have to touch different functions when adding a new tx state. But.. that could be just me. Not blocking at all.


<details>

``` diff
diff --git a/src/wallet/transaction.h b/src/wallet/transaction.h
--- a/src/wallet/transaction.h	(revision 42056e6a2944b3f61aed376b3317551ca1241971)
+++ b/src/wallet/transaction.h	(date 1695826678557)
@@ -29,10 +29,13 @@
     int position_in_block;
 
     explicit TxStateConfirmed(const uint256& block_hash, int height, int index) : confirmed_block_hash(block_hash), confirmed_block_height(height), position_in_block(index) {}
+
+    std::string toString() const { return strprintf("Confirmed (block=%s, index=%i)", confirmed_block_hash.ToString(), position_in_block); }
 };
 
 //! State of transaction added to mempool.
 struct TxStateInMempool {
+    std::string toString() const { return strprintf("InMempool"); }
 };
 
 //! State of rejected transaction that conflicts with a confirmed block.
@@ -41,6 +44,8 @@
     int conflicting_block_height;
 
     explicit TxStateConflicted(const uint256& block_hash, int height) : conflicting_block_hash(block_hash), conflicting_block_height(height) {}
+
+    std::string toString() const { return strprintf("Conflicted (block=%s)", conflicting_block_hash.ToString()); }
 };
 
 //! State of transaction not confirmed or conflicting with a known block and
@@ -51,6 +56,8 @@
     bool abandoned;
 
     explicit TxStateInactive(bool abandoned = false) : abandoned(abandoned) {}
+
+    std::string toString() const { return strprintf("Inactive (abandoned=%i)", abandoned); }
 };
 
 //! State of transaction loaded in an unrecognized state with unexpected hash or
@@ -62,6 +69,8 @@
     int index;
 
     TxStateUnrecognized(const uint256& block_hash, int index) : block_hash(block_hash), index(index) {}
+
+    std::string toString() const { return strprintf("Unrecognized (block=%s, index=%i)", block_hash.ToString(), index); }
 };
 
 //! All possible CWalletTx states
@@ -109,6 +118,11 @@
     }, state);
 }
 
+//! Return TxState as a string for logging or debugging.
+static inline std::string TxStateString(const TxState& state)
+{
+    return std::visit([](const auto& s) { return s.toString(); }, state);
+}
 
 /**
  * Cachable amount subdivided into watchonly and spendable parts.
```

</details>

**Comment by ryanofsky** [comment]
re: https://github.com/bitcoin/bitcoin/pull/28544#pullrequestreview-1646937471

> I'm slightly more inclined to encapsulate the string representation into a `toString()` per struct so we don't have to touch different functions when adding a new tx state. But.. that could be just me. Not blocking at all.

Agree this is nicer. It also lets the function work with `SyncTxState` variants, not just `TxState`.

Updated dc1520b14ea38f80ed7d4c4598beb54d86667f24 -> 8a553c94098c96cb3679468c2b460be145a0eabf ([`pr/statestr.1`](https://github.com/ryanofsky/bitcoin/commits/pr/statestr.1) -> [`pr/statestr.2`](https://github.com/ryanofsky/bitcoin/commits/pr/statestr.2), [compare](https://github.com/ryanofsky/bitcoin/compare/pr/statestr.1..pr/statestr.2)) with suggestion

**Review by furszy — COMMENTED** [review]
Code ACK 8a553c9

**Comment by ishaanam** [comment]
utACK 8a553c94098c96cb3679468c2b460be145a0eabf

**Comment by achow101** [comment]
ACK 8a553c94098c96cb3679468c2b460be145a0eabf

**Pull request merged**
