### PR TITLE
Remove unused Python imports

### PR DESCRIPTION
**Pull request by practicalswift**
The commit in this PR removes unused Python imports.

### CODE REVIEW

**Comment by laanwj** [comment]
Makes sense. Is there an automated tool you used to find these?

**Comment by practicalswift** [comment]
Yes, [`pycodestyle`](https://pypi.python.org/pypi/pycodestyle) (formerly `pep8`) is probably the most common tool for checking Python code against the Python Software Foundation's [Style Guide for Python Code (PEP-8)](https://www.python.org/dev/peps/pep-0008/). Unused imports is one class of violations covered by `pycodestyle`.

I've done some cleanup work for the `apple/swift` project - [see here](https://github.com/apple/swift/pulls?utf8=%E2%9C%93&q=is%3Apr%20author%3Apracticalswift%20is%3Amerged) - which included things such as bringing the Python code base in line with PEP-8. Please let me know if that kind of contributions would be welcome in the Bitcoin project and I'll dig in! :-)

**Comment by jtimon** [comment]
Concept ACK

**Comment by practicalswift** [comment]
Removed `[trivial]` from the commit title.

**Comment by jnewbery** [comment]
ACK

Feel free to open PRs for tidying up python coding style. I'm happy to review anything in the qa directory.

**Comment by practicalswift** [comment]
@jnewbery OK, great! Will do! :-)

**Comment by practicalswift** [comment]
@jnewbery Do you know who to ask for a review of PR #9529? :-)

**Comment by practicalswift** [comment]
@jnewbery What is the proper protocol to follow w.r.t. to submitting Python cleanups? Should I wait for this initial Python cleanup PR to get merged before proceeding with further cleanups, or what is the preferred way to proceed? :-)

**Comment by MarcoFalke** [comment]
utACK 95bab821b3af268d23e9cf5f9da3dd7f1e396949

**Comment by jnewbery** [comment]
@practicalswift - probably best to ask @MarcoFalke since he maintains the qa and test code. In general I'd recommend not making parallel PRs which touch a lot of files, since you'll probably end up having to rebase.

**Comment by practicalswift** [comment]
@jnewbery Makes sense! My second Python cleanup PR is #9532 which removes 8 unused Python variables (+ one unused variable in the C++ code :-)).

**Comment by MarcoFalke** [comment]
I think it makes sense to clean up the python code base in qa/ but
please make sure you are not "exceeding the goal". We already had
cleanup pulls which changed to a max line length to 80 chars among
other things. It turned out the patch was impossible to review,
actually changed behavior and would have introduced bugs. I'd rather
have "ugly" code that works than some PEP8 code that crashes.

Just ask yourself if a specific cleanup task is worth it and easy to
review, then it should be fine.

**Pull request merged**
