### PR TITLE
validation: fix ActivateSnapshot to use hardcoded nChainTx

### PR DESCRIPTION
**Pull request by jamesob**
This fixes an oversight from the move of nChainTx from the user-supplied
snapshot metadata into the hardcoded assumeutxo chainparams.

Since the nChainTx is now unused in the metadata, it should be removed
in a future commit.

See: https://github.com/bitcoin/bitcoin/pull/19806#discussion_r612165410

### CODE REVIEW

**Review by ryanofsky — APPROVED** [review]
Code review ACK 931684b24a89aba884cb18c13fa67ccca339ee8c

It seems reasonable to just ignore the SnapshotMetadata::m_nchaintx value instead of checking it as long as it's going away. Will there be a followup PR to remove it?

**Comment by Sjors** [comment]
utACK 931684b modulo AppVeyor test issue:
```
src\test\validation_chainstatemanager_tests.cpp(278,1): error C3493: 'bad_nchaintx' cannot be implicitly captured because no default capture mode has been specified 
```

**Comment by jamesob** [comment]
Thanks for the reviews @ryanofsky @Sjors. I've pushed a commit removing the nchaintx value from the snapshot metadata. This will of course render previously-generated snapshots unusable, but given that there's currently no way of actually making use of the snapshots I don't think that's an issue.

**Comment by Sjors** [comment]
Other than breaking half the CI's: sounds good :-)

**Comment by jamesob** [comment]
> Other than breaking half the CI's: sounds good :-)

Oops! Fixed.

**Review by ryanofsky — APPROVED** [review]
Code review ACK 91d93aac4e3fe6fff5ef492ed152c4d8fa6f2672. No change to previous commit, just new commit removing now unused utxo snapshot field and updating tests.

**Comment by Sjors** [comment]
utACK 91d93aac4e3fe6fff5ef492ed152c4d8fa6f2672

**Review by maflcko — COMMENTED** [review]
I haven't reviewed this because I am still reviewing #19806, but the changes are likely ok to merge in the meantime.

**Pull request merged**
