### PR TITLE
Add const modifier to HTTPRequest methods

### PR DESCRIPTION
**Pull request by promag**

### CODE REVIEW

**Comment by domob1812** [comment]
utACK 18c49eb8877d8b11f763083a79a7b8250e060106 - thanks for the cleanup!

**Comment by 251Labs** [comment]
thanks @promag - utACK 18c49eb

**Comment by Empact** [comment]
utACK 18c49eb

**Comment by laanwj** [comment]
utACK 18c49eb8877d8b11f763083a79a7b8250e060106

**Pull request merged**
