### PR TITLE
[init] Clarify help message

### PR DESCRIPTION
**Pull request by maflcko**
Also, I think this should be branched by `showDebug`.

### CODE REVIEW

**Comment by paveljanik** [comment]
Why debug? Message is better with the explicit "memory pool".

**Comment by jonasschnelli** [comment]
Tend to NACK for the `showDebug` wall, though ACK the text change. Explicitly mention "memory pool" might be good and could solve cure some wild thought.

**Comment by laanwj** [comment]
Yes, new text is better, don't know about `showDebug`. It's a miner policy option, not so much a debugging one.

**Comment by MarcoFalke** [comment]
Addressed nits. (Let's leave the `showDebug` for later to clean up, if wanted)

**Comment by achow101** [comment]
ACK

**Pull request merged**
