### PR TITLE
Fix walletbackup.py after directory restructuring

### PR DESCRIPTION
**Pull request by sdaftuar**
Also add walletbackup.py to the pull-tester script

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Oh. I missed that. Thanks.

ACK (if travis succeed).

**Comment by laanwj** [comment]
Does anyone know why walletbackup.py was not included before? Is it a test that takes a long time?

**Comment by sdaftuar** [comment]
Seems to take about 30 seconds on my machine -- would it be better to move it to the set of scripts that don't run automatically?

**Comment by laanwj** [comment]
30 seconds doesn't sound too bad to me...

**Comment by jonasschnelli** [comment]
IMO it would be nice to have this test also within pull-tester/CI standard tests (even if it wasn't there before).

@sdaftuar: https://github.com/bitcoin/bitcoin/blob/master/qa/rpc-tests/README.md is also a bit outdated. Maybe you find time to write something about the new classes, comparison test cases, etc.... ?

**Comment by sdaftuar** [comment]
@jonasschnelli  Totally agree and sorry it's been taking a while, I've started work on implementing the first few of the java comparison tool's tests in the python framework.  As part of that I'm reworking some of the interfaces a little bit to accommodate the test; my plan was to update the documentation and submit as part of that pull (hopefully sooner rather than later).

**Pull request merged**
