### PR TITLE
[WIP] p2p: asmap, avoid inbound connections from a specific AS

### LINKED ISSUE #26353: Asmap: avoid connecting to certain AS
While studying asmap, I could understand that Core tries to connect to at most one peer per AS, like:
image

Supposing I don't want to have my node connected to Amazon or Digital Ocean, doesn't it make sense to make possible to set up my node to avoid connecting to certain AS (something like `-asmapavoid=abc,bca,cba...`?

### PR DESCRIPTION
**Pull request by brunoerg**
Fixes #26353 

For privacy/security reasons (discussed in #26353 - e.g. malicious nodes on a particular AS), we could avoid connections from particular AS (discussed in #26353). This PR adds a flag `-avoidas`, which can be specified multiple times, where you pass an ASN you want to avoid inbound connections from.

e.g.
```sh
./src/bitcoind --asmap=path/to/file --avoidas=399991
```

### CODE REVIEW

**Comment by brunoerg** [comment]
> Would it make sense to instead offer this feature as an extension of the banning functionality (through setban / listbanned RPCs). That way it'd be runtime-configurable, get expiration, and the ability to export/import banlist.json files.

I'm testing different approaches and I think makes sense to expand `banlist`, gonna change it.

**Comment by brunoerg** [comment]
@sipa, adding it to the `ban` stuff would not work for only `inbound` connections I guess. If I set a ban based on AS, maybe all my connections with them would be affected, wouldn't it? This approach is more like to avoid any inbound, but not affecting me to connect to any of them.

**Comment by brunoerg** [comment]
> Why would you only want to avoid inbound? 

An example: an attacker is using AWS to create multiple nodes and connect with me, I want to avoid it. However, it doesn't mean all the nodes from there are malicious, even I can have another node hosted there.

**Comment by petertodd** [comment]
I think this feature should be called something like `-ban-as` rather than `-avoidas`, as the functionality is similar to IP banning. The word "avoid" doesn't give that connotation and needlessly introduces a new term for users to understand.

**Review by luke-jr — CHANGES_REQUESTED** [review]
Also think it would make more sense to broaden this to a ban type. If you want to connect to peers in the AS but not accept inbound connections (which IMO is weird), why wouldn't that possibly also be the case for (eg) a subnet ban?

**Comment by brunoerg** [comment]
Closing it for now. I agree on moving it to `ban`, will work on it.

**Pull request closed without merging**
