### PR TITLE
Image File Compression

### PR DESCRIPTION
**Pull request by Peppernrino**
Ran a series of lossless compression algorithms on the images to make them smaller. Total reduction of 279,816 bytes.

As per the _PULL_REQUEST_TEMPLATE.md_, I am to state why I feel this pull request is important. Bitcoin is a popular cryptocurrency, and every time someone downloads or uploads the source, it costs bandwidth. It is a measure to save disk space and time. :)

Over 1,000,000 users, it's a savings of ~279GB each way.

### CODE REVIEW

**Comment by dongcarl** [comment]
What compression pipeline did you use? Perhaps this could be contributed as a script for future PRs containing images?

**Comment by Peppernrino** [comment]
It varies from image type to image type, but here is an example of what was run on _spinner.png_:

* PngOptimizer.exe -file:"spinner.png"
Original Size: 16636. Optimized Size: 1774

* truepng.exe -o4 -tz -md remove all -g0 /i0 /tz /quiet /y /out "spinner.png" "spinner.png"
Original Size: 1774. Optimized Size: 1497

* pngout.exe /q /y /r /d0 /mincodes0 /kacTL,fcTL,fdAT /s0 "spinner.png" "spinner.png"
Original Size: 1497. Optimized Size: 1497

* optipng.exe -zw32k -quiet -o6 -strip all "spinner.png"
Original Size: 1497. Optimized Size: 1497

* leanify.exe -q -i 30 "spinner.png"
Original Size: 1497. Optimized Size: 1480

* pngwolf.exe --out-deflate=zopfli,iter=30 --in="spinner.png" --out="spinner.png"
Original Size: 1480. Optimized Size: 1473

* pngrewrite.exe "spinner.png" "spinner.png"
Original Size: 1473. Optimized Size: 1473

* advpng.exe -z -q -4 -i 30 "spinner.png"
Original Size: 1473. Optimized Size: 1473

* ECT.exe -quiet --allfilters -strip -9 "spinner.png"
Original Size: 1473. Optimized Size: 1344

* pingo.exe -s8 "spinner.png"
Original Size: 1344. Optimized Size: 1344

* deflopt.exe /a /b /s "spinner.png"
Original Size: 1344. Optimized Size: 1344

* defluff.bat "spinner.png" "spinner.png"
Original Size: 1344. Optimized Size: 1344

* deflopt.exe /a /b /s "spinner.png"
Original Size: 1344. Optimized Size: 1344

**Comment by luke-jr** [comment]
Note that every user needs to download ~200 GB anyway. Saving a few kB isn't a big deal.

That being said, no objection to using better PNGs. (Personally I would prefer if we can move to SVGs...)

**Comment by Peppernrino** [comment]
Make sure to visually confirm the integrity of the files if you do choose to do this. I noticed some images I did earlier with magick.exe (for another program) had some degradation, so I discarded them.

I'll go through my logs and gather what I ran on all of the file types that were modified. Just wanted to get a sample done quick for you guys. :)

**Comment by MarcoFalke** [comment]
Please adjust https://github.com/bitcoin/bitcoin/blob/master/contrib/devtools/optimize-pngs.py so that this can be reproduced by reviewers.

**Comment by laanwj** [comment]
NACK, IMO

Thanks for trying to contribute but this doesn't really help

- it doesn't make the repository smaller (just includes another copy)
- yes it might make the distribution a bit smaller, buut the blockchain download and storage size being what it is, what gives?

**Comment by Peppernrino** [comment]
Well that's upsetting. I figured anything that helped would be accepted.

Sorry for confusing the repository with the distribution... I'm a self-trained developer, and sometimes the jargon is the only problem with our communication. Kind of like how I have to Google "NACK" now... :D 

I'll go to that bit @MarcoFalke is talking about, and have some discussion there. I'm sure I can be helpful in this area. Ideally, I want people to include the changes themselves... it's not about glory. Good compression appears to be some kind of secret. lol. I actually started doing this after being inspired by an article entitled, "The Website Obesity Crisis".

**Comment by Peppernrino** [comment]
Must be nice to have such crazy veto power. 3 people liked it. You didn't.

**Comment by MeshCollider** [comment]
@Peppernrino sorry your PR was closed, and thanks for trying to contribute, but this isn't about "crazy veto power". Note that Luke only said he had no objection, not that he liked it, and we have hundreds of open pull requests to review, so a change which affects 102 different files without clear benefits is quite a burden on reviewers. So a NACK with good reasoning in this case is enough to warrant closure. Perhaps you could take a look at some of the open issues in the repository and find a different way to contribute :)

**Comment by Peppernrino** [comment]
The change makes the files smaller. That is the benefit. And no thank you. I'm turned off from contributing now.

**Comment by Peppernrino** [comment]
For the record, @dongcarl indicated that he would like the changes included in upcoming releases as part of how things are done here.

Reiterating that @luke-jr only had no objection is quite seriously some meaningless semantics. The point was that he felt it would be fine to include. Nuff said.

**Comment by sipa** [comment]
@Peppernrino I'm very happy that you were interested in contributing, and sad to see you're turned away by the response. But I agree with @laanwj here; there is a possibly endless stream of incremental improvements like this, and we're very starved on reviewer time.

**Comment by Peppernrino** [comment]
Seems like everybody has time to comment on this thread. :D

**Comment by Peppernrino** [comment]
Jokes aside, I checked out the thingy @MarcoFalke was talking about, and it seems the images might have a sha256 in there after all! :o 

This pull might actually make things weird because of how convoluted the compression process already is.

**Comment by MarcoFalke** [comment]
I am happy to review this if this runs on linux (see the script above I linked to) and produces a deterministic as well as stable output.

But a one-off compression that cannot be run on newly added files because it depends on a random collection of tools that only run on Windows is not particularly useful for the general developer.

**Comment by promag** [comment]
> Ran a series of lossless compression algorithms on the images to make them smaller. Total reduction of 279,816 bytes.

Is the total reduction the sum of each image reduction or the reduction of the final distribution archive?

**Comment by Peppernrino** [comment]
Total reduction overall.

**Pull request closed without merging**
