### PR TITLE
Make AddrMan support multiple ports per IP

### PR DESCRIPTION
**Pull request by sipa**
For a long part of Bitcoin's history, this codebase has aggressively avoided making automatic connections to anything but nodes running on port 8333. I'd like to propose changing that, and this is a first PR necessary for that.

The folklore justification (eventually actually added as a comment to the codebase in #20668) is that this is to prevent the Bitcoin P2P network from being leveraged to perform a DoS attack on other services, if their IP/port would get rumoured. It appears, at least the current network scale - and probably significantly larger - that the impact is very low at best (see calculations by vasild in https://github.com/bitcoin/bitcoin/issues/5150#issuecomment-853888909 e.g.). Another possible justification would be a risk that treating different IP:port combinations separately would help perform Eclipse attacks (by an attacker rumouring their own IP with many ports). This concern is (a) no different than what is possible with IPv6 (where large ranges of IP addresses are very cheaply available), and (b) already hopefully sufficiently addressed by addrman's design (which limits access through based selected based on network groups).

And this policy has downsides too; in particular, a fixed port is easy to detect, and a very obvious sign a Bitcoin node is running there.

One obstacle in moving away from a default port that is the fact that addrman is currently restricted to a single entry per IP address. If ports are no longer expected to be generally always the default one, we need to deal with the case where conflicting information is relayed. It turns out there is a very natural solution to this: treat (IP,port) combination exactly as we're treating IPs now; this automatically means that the same IP may appear with multiple ports, simply because those would be distinct entries. Given that indexing into addrman's bucket _already_ uses the port number, the only change required is making all addrman lookup be (IP,port) (aka `CService`) based, rather than IP (aka `CNetAddr`) based.

This PR doesn't include any change to the actual outbound connection preference logic, as perhaps that's something that we want to phase in more gradually.

### CODE REVIEW

**Review by lsilva01 — APPROVED** [review]
Tested ACK 5697d60 on Ubuntu 20.04.

`CNetAddr` has been replaced by `CService` in `mapAddr` in this change.
`CService` is a subclass of `CNetAddr` that has the port attribute.
Started node with an existing `peers.dat` file and with no file. It had no impact on serialization / unserialization as this is done using `AddrInfo`.

**Review by vasild — APPROVED** [review]
ACK 5697d6054a1aaec0f89a8c8ce792d5e9f5c02314

TODO: once this PR and https://github.com/bitcoin/bitcoin/pull/22839 are merged, ensure that all logging of addresses from within addrman include the port (i.e. avoid `ToStringIP()`).

**Review by mzumsande — COMMENTED** [review]
Concept ACK

In four different places in Addrman, there is the pattern
```
    AddrInfo* pinfo = Find(addr);

    // if not found, bail out
    if (!pinfo)
        return;

    AddrInfo& info = *pinfo;

    // check whether we are talking about the exact same CService (including same port)
    if (info != addr)
        return;
```
I think the final check for `info != addr` could be removed now, since with this PR, `Find()`  only returns an entry if there is a match including the port (and the first return would be hit if not).

**Comment by sipa** [comment]
@practicalswift That's a reasonable concern. I think as a first step, the policy could e.g. still maintain the deprioritization of connections to ports numbered < 1024.

**Review by jnewbery — COMMENTED** [review]
Concept ACK. Couple of minor comments inline.

I agree with @mzumsande about removing the `// check whether we are talking about the exact same CService (including same port)` logic from `_Good()`, `_Attempt()`, `_Connected()` and `_SetServices()`.

**Review by vasild — APPROVED** [review]
ACK 92617b7a758c0425330fba4b886296730567927c

**Comment by vasild** [comment]
A followup to this, that removes the strong preference for 8333 is in https://github.com/bitcoin/bitcoin/pull/23542.

**Pull request merged**
