### PR TITLE
[Fuzz] Poly1305 differential fuzzing against Floodyberry's implementation

### PR DESCRIPTION
**Pull request by prakash1512**
This PR compares Bitcoin Core's implementation of Poly1305 with Floodyberry's public domain implementation in order to find implementation discrepancies if any.

Instructions to test this PR:
Step1: Fetch the pull request
Step2: Switch to the pull request branch and run the following commands:
```
$ ./autogen.sh
$ CC=clang CXX=clang++ ./configure --enable-fuzz --with-sanitizers=address,fuzzer,undefined
$ make
$ FUZZ=crypto_diff_fuzz_poly1305 src/test/fuzz/fuzz
```

### CODE REVIEW

**Comment by achow101** [comment]
Are you still working on this?

**Comment by stratospher** [comment]
Yes, I'm still working on this. I'm looking for concept ACKs for this approach. Also wondering whether differential fuzzing between c++ and python implementations would be more valuable? (See https://github.com/bitcoin/bitcoin/pull/23441#issuecomment-1276633895 also.)

I'll update soon regarding the ci fuzz crash.

**Comment by stratospher** [comment]
> I don't think differential fuzzing with a Python implementation is worth it (much slower, and much harder due to cross-language comparing). There is also nothing particularly authoritative about any given Python implementation; in the end it's comparison with actually-deployed poly1305 code we want.

I was thinking of the python implementation in the functional testing framework but this makes sense.
Closing this PR until we find a better way to test.

**Comment by stratospher** [comment]
thanks for clarifying! I find the reference and current implementation to be similar for a good differential fuzz test now. I'd like to understand more about how differential fuzzing is done in other projects before continuing with this PR.

**Pull request closed without merging**
