### PR TITLE
Remove unused dummy_tx variable from FillPSBT

### PR DESCRIPTION
**Pull request by dongcarl**

### CODE REVIEW

**Comment by achow101** [comment]
ACK 16bcc1b8237698c96b8ced2fa7eb76388c7ba85e

grep'd for `dummy_tx` and it was only used here.

**Comment by domob1812** [comment]
utACK 16bcc1b8237698c96b8ced2fa7eb76388c7ba85e - nice find!

**Comment by Empact** [comment]
utACK 16bcc1b introduced in https://github.com/bitcoin/bitcoin/commit/a4b06fb42eb0ad94e562ca839391b57e69285136#diff-df7d84ff2f53fcb2a0dc15a3a51e55ce and never used

**Comment by laanwj** [comment]
utACK 16bcc1b8237698c96b8ced2fa7eb76388c7ba85e

**Pull request merged**
