### PR TITLE
Drop final alert announcement

### PR DESCRIPTION
**Pull request by Empact**
As discussed in #14033

### CODE REVIEW

**Comment by laanwj** [comment]
let's keep the discussion in #14033, spiltting it over two PRs would not be constructive

**Comment by Empact** [comment]
@laanwj shall I leave the PR separate or move the code over as well?

**Comment by laanwj** [comment]
code-wise it's okay to have this as a separate PR, just trying to pre-empt a "sharded" discussion

**Comment by Empact** [comment]
Closing as per lack of consensus in #14033

**Pull request closed without merging**
