### PR TITLE
Add testnet DNS seed:  seed.testnet.bitcoin.sprovoost.nl

### PR DESCRIPTION
**Pull request by Sjors**
I tested it myself by:
* `dig seed.testnet.bitcoin.sprovoost.nl`  (should have propagated by now, but if you only see two records with `A 66.111... ` try again later)
* deleting the other seeds and all data in `.../testnet3`, recompiling and then starting the node. Log shows `21 addresses found from DNS seeds`.

ACK https://github.com/bitcoin/bitcoin/blob/master/doc/dnsseed-policy.md

I'm willing to keep it up and running at least throughout 2018, unless something bad happens.

About my setup:
* Amazon EC2 instance in Europe, running Ubuntu 16.04; I use this instance for some other chores, but only port 53 is world reachable (for mainnet I'd probably run a dedicated instance, and perhaps a location I have physical control over)
* running [sipa/bitcoin-seeder](https://github.com/sipa/bitcoin-seeder) with default settings (and the non-root port redirect)
* feedback about my domain / DNS setup is welcome, I can provide more details via private email

I can use guidance on _Any hosting services contracted by the operator are equally expected to uphold these expectations_. Although I assume the requirements for testnet are less strict than for mainnet, in case I want to pursue the latter in the future: what unpleasant things can Amazon, my domain registrar and other intermediaries do? How would I mitigate that?

Also note that The Netherlands passed some pretty onerous legislation creating uncertainty over what the secret service can compel people like myself to do. However these laws won't take effect before mid 2018, there's probably more interesting targets than myself to go after, and it's easier for them to just monitor all unencrypted P2P traffic everywhere, or monitor some intermediary I depend on.

Any good tools for monitoring uptime?

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Can you add IPv6 support?

**Comment by Sjors** [comment]
Done, I think.

I followed the instructions for adding IPv6 support to an existing EC2 instance [here](http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-migrate-ipv6.html), but ended up not being able to even `ping6 ipv6.google.com`. I'm sure it was solvable, but creating a new instance was easier. May take a while for DNS to propagate.

I don't have IPv6 support on my own connection, but this looks promising:

```sh
$ dig -t AAAA seed.testnet.bitcoin.sprovoost.nl

; <<>> DiG 9.9.7-P3 <<>> -t AAAA seed.testnet.bitcoin.sprovoost.nl
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 40644
;; flags: qr rd ra; QUERY: 1, ANSWER: 12, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;seed.testnet.bitcoin.sprovoost.nl. IN	AAAA

;; ANSWER SECTION:
seed.testnet.bitcoin.sprovoost.nl. 3503	IN AAAA	2600:3c00::f03c:91ff:fe89:305f
seed.testnet.bitcoin.sprovoost.nl. 3503	IN AAAA	2600:3c01::f03c:91ff:fe91:6a51
seed.testnet.bitcoin.sprovoost.nl. 3503	IN AAAA	2a01:4f8:211:14cf::2
seed.testnet.bitcoin.sprovoost.nl. 3503	IN AAAA	2001:67c:16dc:1201:5054:ff:fe17:4dac
seed.testnet.bitcoin.sprovoost.nl. 3503	IN AAAA	2607:5300:60:ac0::1
seed.testnet.bitcoin.sprovoost.nl. 3503	IN AAAA	2a01:4f8:140:9186::2
seed.testnet.bitcoin.sprovoost.nl. 3503	IN AAAA	2001:e42:102:1818:160:16:232:144
seed.testnet.bitcoin.sprovoost.nl. 3503	IN AAAA	2a02:c207:3001:9320::1
seed.testnet.bitcoin.sprovoost.nl. 3503	IN AAAA	2001:41d0:2:203c::1
seed.testnet.bitcoin.sprovoost.nl. 3503	IN AAAA	2001:4800:7818:103:be76:4eff:fe05:f119
seed.testnet.bitcoin.sprovoost.nl. 3503	IN AAAA	2a01:4f8:191:840b::2
seed.testnet.bitcoin.sprovoost.nl. 3503	IN AAAA	2a00:16d8:c::5b6a:c261
```

`ping6 seed.testnet.bitcoin.sprovoost.nl` seems to work as well (using some online tools).

**Comment by Sjors** [comment]
@jonasschnelli by the way I can't reach yours from my EC2 instance, and from my current location it's not returning any records: ` dig -t AAAA testnet-seed.bitcoin.jonasschnelli.ch` (same with `-t A`).

**Comment by jonasschnelli** [comment]
@Sjors: My testnet seed had an issue,... fixed since a couple of hours and currently figuring out why it happened and why the monitoring failed.

**Comment by Sjors** [comment]
I deployed a mainnet seed as well, on a dedicated instance. I'll make a PR for that someday after my testnet seed is merged. Feel free to monitor it in the meantime: `seed.bitcoin.sprovoost.nl`

**Comment by laanwj** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/11917/commits/f455a24da7b098d390b6405ae19826d0c5684c3e

**Comment by jonasschnelli** [comment]
utACK f455a24da7b098d390b6405ae19826d0c5684c3e

**Comment by MeshCollider** [comment]
utACK https://github.com/bitcoin/bitcoin/commit/f455a24da7b098d390b6405ae19826d0c5684c3e

**Pull request merged**
