### PR TITLE
Update btcdrak signing key

### PR DESCRIPTION
**Pull request by btcdrak**

### CODE REVIEW

**Comment by fanquake** [comment]
Is this the same as #8547 ? Wasn't the conclusion to get people to use --refresh-keys .

**Comment by MarcoFalke** [comment]
I think the old key is revoked

**Comment by laanwj** [comment]
Yes, the old key is revoked. So --refresh-keys is a good idea to get the revocation certificate, but not a replacement for updating the key this time.

ACK 46606af, verified that the key in this pull, 0xD5566241A0295FA9 is the same new key as I have on file for @btcdrak.

**Comment by fanquake** [comment]
utACK 46606af

**Pull request merged**
