### PR TITLE
WIP test: Check that wait_until returns if time point is in the past

### PR DESCRIPTION
**Pull request by maflcko**
Regression test for https://github.com/boostorg/thread/issues/308

### CODE REVIEW

**Comment by MarcoFalke** [comment]
The unit test currently fails fails when using boost from depends on Linux

**Comment by luke-jr** [comment]
??? Why is this downgrading boost, and documenting it as upgraded?

**Comment by luke-jr** [comment]
If this bug affects us with all recent boost versions (at least <=1.66 are not available in Gentoo anymore), maybe we should implement a workaround instead?

**Comment by MarcoFalke** [comment]
I think there is nothing we can do here except to remove boost

**Comment by luke-jr** [comment]
Utility function to check for the exception and see if the time passed explicitly?

**Pull request closed without merging**
