### PR TITLE
ci: Workaround Microsoft mirror issue for GitHub Action

### PR DESCRIPTION
**Pull request by hebasto**
Upstream:
 - issue -- https://github.com/actions/runner-images/issues/9733
 - code snippet -- https://github.com/actions/runner-images/issues/9733#issuecomment-2074590278

### CODE REVIEW

**Comment by hebasto** [comment]
Going to add a second commit just to trigger the affected "test-each-commit" CI job.

**Comment by paplorinc** [comment]
Could you please validate that this is the failure reason for https://github.com/bitcoin/bitcoin/pull/29862?

**Comment by hebasto** [comment]
> Could you please validate that this is the failure reason for #29862?

Correct.

**Comment by hebasto** [comment]
> Going to add a second commit just to trigger the affected "test-each-commit" CI job.

It works -- https://github.com/bitcoin/bitcoin/actions/runs/8815890196/job/24198769685.

**Comment by hebasto** [comment]
> > Going to add a second commit just to trigger the affected "test-each-commit" CI job.
> 
> It works -- https://github.com/bitcoin/bitcoin/actions/runs/8815890196/job/24198769685.

Reverted back to the mergeable state.

**Comment by fanquake** [comment]
Given the impact, I assume this will be fixed shortly. So not sure we need to commit something just to semi-immediately revert it. GitHub is also having issues (https://www.githubstatus.com/), so maybe it's the same/related infra.

**Comment by hebasto** [comment]
https://github.com/microsoft/linux-package-repositories/issues/130

Closing.

**Pull request closed without merging**
