### PR TITLE
build: minor boost tidyups

### PR DESCRIPTION
**Pull request by fanquake**
Don't install CMake config files we don't use.
Remove duplicated `-fvisibility=hidden` flag.

Guix build:
```bash
bash-5.1# find guix-build-$(git rev-parse --short=12 HEAD)/output/ -type f -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum
e7eeffd0df31f8e319e7f099d7c3ba8429b47c8d9f888517b146b0cf079470bc  guix-build-e734847c1f50/output/aarch64-linux-gnu/SHA256SUMS.part
516c4703e84d74b80b22a2c8ef7f971ab269332d1394841f27cdca76013689f1  guix-build-e734847c1f50/output/aarch64-linux-gnu/bitcoin-e734847c1f50-aarch64-linux-gnu-debug.tar.gz
4f2e279584d2f46ca3bdd9e67375bfd0a8637dfd183ccdf827248729ea69e858  guix-build-e734847c1f50/output/aarch64-linux-gnu/bitcoin-e734847c1f50-aarch64-linux-gnu.tar.gz
28298c04b7810489a3be5471435ec63955d33cf57d4dc234e539ab95ba4dfe40  guix-build-e734847c1f50/output/arm-linux-gnueabihf/SHA256SUMS.part
1a5d3245d982797d98ecfa2325da224b0814823c858ebaf56a6f310fe099b046  guix-build-e734847c1f50/output/arm-linux-gnueabihf/bitcoin-e734847c1f50-arm-linux-gnueabihf-debug.tar.gz
ef79e545661f8e76811df5a9d1d9299c8cb35485b729377f07e789d559d2298d  guix-build-e734847c1f50/output/arm-linux-gnueabihf/bitcoin-e734847c1f50-arm-linux-gnueabihf.tar.gz
f92bd538bd10dd7c09644e322d8c53536fde236ac16a0f5405becb3165685e68  guix-build-e734847c1f50/output/dist-archive/bitcoin-e734847c1f50.tar.gz
56e7934800c630e91fee389ea9c8e95469deafafd58a8fb18616db13675dc51b  guix-build-e734847c1f50/output/powerpc64-linux-gnu/SHA256SUMS.part
f15a2e7ad3d7be3ab9ee65f7a77df902c303d561b465fb22242bcfa47344be9c  guix-build-e734847c1f50/output/powerpc64-linux-gnu/bitcoin-e734847c1f50-powerpc64-linux-gnu-debug.tar.gz
776ee33875d9934d9d472e9e735088bb9e9cf58bc9e29102a7a019a52deb28e3  guix-build-e734847c1f50/output/powerpc64-linux-gnu/bitcoin-e734847c1f50-powerpc64-linux-gnu.tar.gz
19758310e0e19e17d57c59ba9fc4cbb350b64de0ddc050f85136043666b63c44  guix-build-e734847c1f50/output/powerpc64le-linux-gnu/SHA256SUMS.part
90ad4e0b948e8bf58538f40f648420230e2357c3e2ae9aa331bac44fe98b1d71  guix-build-e734847c1f50/output/powerpc64le-linux-gnu/bitcoin-e734847c1f50-powerpc64le-linux-gnu-debug.tar.gz
809a9a95dfa84fab4f365b687e68b58195a00810d6c9f3442c5b1155630d9515  guix-build-e734847c1f50/output/powerpc64le-linux-gnu/bitcoin-e734847c1f50-powerpc64le-linux-gnu.tar.gz
3ea0563f95f3d6a2ecbdeb4ddf06187db1fbbf1dbabe77db38218f0c13a6dd2b  guix-build-e734847c1f50/output/riscv64-linux-gnu/SHA256SUMS.part
1730fe70782024ae1558c9065361d4dc754683c6b5fecc420cf990c8b37a5f08  guix-build-e734847c1f50/output/riscv64-linux-gnu/bitcoin-e734847c1f50-riscv64-linux-gnu-debug.tar.gz
720b6d6625c009e54d6a8b50e0dacdf7723374d52ace6a23874db6d3e540665d  guix-build-e734847c1f50/output/riscv64-linux-gnu/bitcoin-e734847c1f50-riscv64-linux-gnu.tar.gz
bbf89e748b089ba68c50c9c03b81cb7f4b0517939dacd2e6a72d2480713c02c4  guix-build-e734847c1f50/output/x86_64-apple-darwin19/SHA256SUMS.part
7a47bea38f3d8c19bb411bf4ab28bc4a237865184ddcb0677b3f240f4c5a2462  guix-build-e734847c1f50/output/x86_64-apple-darwin19/bitcoin-e734847c1f50-osx-unsigned.dmg
6e10739840f56dedf0d1dfb9a788d539b87f5e79bf5a3eaacca97126cbf1c04e  guix-build-e734847c1f50/output/x86_64-apple-darwin19/bitcoin-e734847c1f50-osx-unsigned.tar.gz
66c31edaa776e2a07225cc202a70fa3a3a745939b8c0ad2893cb86730869f118  guix-build-e734847c1f50/output/x86_64-apple-darwin19/bitcoin-e734847c1f50-osx64.tar.gz
41aefbeacc4a09f89fbee35446b887c7fadfd17f833b1765fc2de3bec5fe4ce3  guix-build-e734847c1f50/output/x86_64-linux-gnu/SHA256SUMS.part
30a7bfff7be3145e24637c9ab0b605cae0d2942aa6df2a1e7ac0afb22ec18792  guix-build-e734847c1f50/output/x86_64-linux-gnu/bitcoin-e734847c1f50-x86_64-linux-gnu-debug.tar.gz
c7d91fbf09858bc5a573f169715bb1cddb046b2a7d62de73b26a952a92f918e7  guix-build-e734847c1f50/output/x86_64-linux-gnu/bitcoin-e734847c1f50-x86_64-linux-gnu.tar.gz
e8ac5cf5360ceb8ee4550f43a5233c27a1265050d29c3a9b3b2ad136a77c80d4  guix-build-e734847c1f50/output/x86_64-w64-mingw32/SHA256SUMS.part
079df526644fb001fc4500222f9775d3f7c2a39960bd81274bcb941748e8fbde  guix-build-e734847c1f50/output/x86_64-w64-mingw32/bitcoin-e734847c1f50-win-unsigned.tar.gz
3d5a9855b4c5f330006c4a4213549f4bb40323778590b3300c827616004ad6de  guix-build-e734847c1f50/output/x86_64-w64-mingw32/bitcoin-e734847c1f50-win64-debug.zip
182e1c668784e16ce73be3175c7bf59012eeae5673b507ab58b164ef670590ab  guix-build-e734847c1f50/output/x86_64-w64-mingw32/bitcoin-e734847c1f50-win64-setup-unsigned.exe
34dc88b5898f4dcba8215a44b6ea545f05e9d7fa623fbb966ed27aeba35d0fdf  guix-build-e734847c1f50/output/x86_64-w64-mingw32/bitcoin-e734847c1f50-win64.zip
```

### CODE REVIEW

**Comment by hebasto** [comment]
> Remove duplicated `-fvisibility=hidden` flag.

Do you mean a flag which is set by `configure` script? If so, it is set only when `--enable-reduce-exports` is provided, no?

**Comment by fanquake** [comment]
> Do you mean a flag which is set by configure script?

No.
> Boost already sets this by default.

**Comment by hebasto** [comment]
Concept ACK.

**Comment by hebasto** [comment]
> > Do you mean a flag which is set by configure script?
> 
> No.
> 
> > Boost already sets this by default.

How could I verify it? Is it documented?

**Comment by fanquake** [comment]
> How could I verify it?

You could compare the compilation of a boost file before and after this PR. i.e:

master:
```bash
    "g++" "-m64"   -fvisibility-inlines-hidden -pipe -O2 -std=c++17 -fvisibility=hidden   -fPIC   -m64 -pthread -O3 -finline-functions -Wno-inline -Wall -fvisibility=hidden   -I/home/ubuntu/bitcoin/depends/x86_64-pc-linux-gnu/include      -DBOOST_ALL_NO_LIB=1 -DBOOST_FILESYSTEM_STATIC_LINK=1 -DNDEBUG  -I"." -c -o "bin.v2/libs/filesystem/build/gcc-10/release/link-static/threading-multi/visibility-hidden/codecvt_error_category.o" "libs/filesystem/src/codecvt_error_category.cpp"
```

This PR:
```bash
    "g++" "-m64"   -fvisibility-inlines-hidden -pipe -O2 -std=c++17   -fPIC   -m64 -pthread -O3 -finline-functions -Wno-inline -Wall -fvisibility=hidden   -I/home/ubuntu/bitcoin/depends/x86_64-pc-linux-gnu/include      -DBOOST_ALL_NO_LIB=1 -DBOOST_FILESYSTEM_STATIC_LINK=1 -DNDEBUG  -I"." -c -o "bin.v2/libs/filesystem/build/gcc-10/release/link-static/threading-multi/visibility-hidden/codecvt_error_category.o" "libs/filesystem/src/codecvt_error_category.cpp"
```

>  Is it documented?

Probably somewhere inside `b2`. https://github.com/boostorg/build/blob/3dd9a8fc7f382342c672297de2d0ef72733a9509/src/tools/features/visibility-feature.jam#L33-L36.

**Review by hebasto — APPROVED** [review]
ACK e734847c1f5095d5aac8784d6e57804c99d61db6, tested on Linux Mint 20.2 (x86_64) and on macOS Big Sur 11.6.1 (Intel, 20G224): `-fvisibility=hidden` is no longer duplicated in compiler invocations, and the resulted package has no the `lib/cmake/` directory.

**Comment by hebasto** [comment]
#### Guix builds:
```
$ find guix-build-$(git rev-parse --short=12 HEAD)/output/ -type f -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum
e7eeffd0df31f8e319e7f099d7c3ba8429b47c8d9f888517b146b0cf079470bc  guix-build-e734847c1f50/output/aarch64-linux-gnu/SHA256SUMS.part
516c4703e84d74b80b22a2c8ef7f971ab269332d1394841f27cdca76013689f1  guix-build-e734847c1f50/output/aarch64-linux-gnu/bitcoin-e734847c1f50-aarch64-linux-gnu-debug.tar.gz
4f2e279584d2f46ca3bdd9e67375bfd0a8637dfd183ccdf827248729ea69e858  guix-build-e734847c1f50/output/aarch64-linux-gnu/bitcoin-e734847c1f50-aarch64-linux-gnu.tar.gz
28298c04b7810489a3be5471435ec63955d33cf57d4dc234e539ab95ba4dfe40  guix-build-e734847c1f50/output/arm-linux-gnueabihf/SHA256SUMS.part
1a5d3245d982797d98ecfa2325da224b0814823c858ebaf56a6f310fe099b046  guix-build-e734847c1f50/output/arm-linux-gnueabihf/bitcoin-e734847c1f50-arm-linux-gnueabihf-debug.tar.gz
ef79e545661f8e76811df5a9d1d9299c8cb35485b729377f07e789d559d2298d  guix-build-e734847c1f50/output/arm-linux-gnueabihf/bitcoin-e734847c1f50-arm-linux-gnueabihf.tar.gz
f92bd538bd10dd7c09644e322d8c53536fde236ac16a0f5405becb3165685e68  guix-build-e734847c1f50/output/dist-archive/bitcoin-e734847c1f50.tar.gz
56e7934800c630e91fee389ea9c8e95469deafafd58a8fb18616db13675dc51b  guix-build-e734847c1f50/output/powerpc64-linux-gnu/SHA256SUMS.part
f15a2e7ad3d7be3ab9ee65f7a77df902c303d561b465fb22242bcfa47344be9c  guix-build-e734847c1f50/output/powerpc64-linux-gnu/bitcoin-e734847c1f50-powerpc64-linux-gnu-debug.tar.gz
776ee33875d9934d9d472e9e735088bb9e9cf58bc9e29102a7a019a52deb28e3  guix-build-e734847c1f50/output/powerpc64-linux-gnu/bitcoin-e734847c1f50-powerpc64-linux-gnu.tar.gz
19758310e0e19e17d57c59ba9fc4cbb350b64de0ddc050f85136043666b63c44  guix-build-e734847c1f50/output/powerpc64le-linux-gnu/SHA256SUMS.part
90ad4e0b948e8bf58538f40f648420230e2357c3e2ae9aa331bac44fe98b1d71  guix-build-e734847c1f50/output/powerpc64le-linux-gnu/bitcoin-e734847c1f50-powerpc64le-linux-gnu-debug.tar.gz
809a9a95dfa84fab4f365b687e68b58195a00810d6c9f3442c5b1155630d9515  guix-build-e734847c1f50/output/powerpc64le-linux-gnu/bitcoin-e734847c1f50-powerpc64le-linux-gnu.tar.gz
3ea0563f95f3d6a2ecbdeb4ddf06187db1fbbf1dbabe77db38218f0c13a6dd2b  guix-build-e734847c1f50/output/riscv64-linux-gnu/SHA256SUMS.part
1730fe70782024ae1558c9065361d4dc754683c6b5fecc420cf990c8b37a5f08  guix-build-e734847c1f50/output/riscv64-linux-gnu/bitcoin-e734847c1f50-riscv64-linux-gnu-debug.tar.gz
720b6d6625c009e54d6a8b50e0dacdf7723374d52ace6a23874db6d3e540665d  guix-build-e734847c1f50/output/riscv64-linux-gnu/bitcoin-e734847c1f50-riscv64-linux-gnu.tar.gz
bbf89e748b089ba68c50c9c03b81cb7f4b0517939dacd2e6a72d2480713c02c4  guix-build-e734847c1f50/output/x86_64-apple-darwin19/SHA256SUMS.part
7a47bea38f3d8c19bb411bf4ab28bc4a237865184ddcb0677b3f240f4c5a2462  guix-build-e734847c1f50/output/x86_64-apple-darwin19/bitcoin-e734847c1f50-osx-unsigned.dmg
6e10739840f56dedf0d1dfb9a788d539b87f5e79bf5a3eaacca97126cbf1c04e  guix-build-e734847c1f50/output/x86_64-apple-darwin19/bitcoin-e734847c1f50-osx-unsigned.tar.gz
66c31edaa776e2a07225cc202a70fa3a3a745939b8c0ad2893cb86730869f118  guix-build-e734847c1f50/output/x86_64-apple-darwin19/bitcoin-e734847c1f50-osx64.tar.gz
41aefbeacc4a09f89fbee35446b887c7fadfd17f833b1765fc2de3bec5fe4ce3  guix-build-e734847c1f50/output/x86_64-linux-gnu/SHA256SUMS.part
30a7bfff7be3145e24637c9ab0b605cae0d2942aa6df2a1e7ac0afb22ec18792  guix-build-e734847c1f50/output/x86_64-linux-gnu/bitcoin-e734847c1f50-x86_64-linux-gnu-debug.tar.gz
c7d91fbf09858bc5a573f169715bb1cddb046b2a7d62de73b26a952a92f918e7  guix-build-e734847c1f50/output/x86_64-linux-gnu/bitcoin-e734847c1f50-x86_64-linux-gnu.tar.gz
e8ac5cf5360ceb8ee4550f43a5233c27a1265050d29c3a9b3b2ad136a77c80d4  guix-build-e734847c1f50/output/x86_64-w64-mingw32/SHA256SUMS.part
079df526644fb001fc4500222f9775d3f7c2a39960bd81274bcb941748e8fbde  guix-build-e734847c1f50/output/x86_64-w64-mingw32/bitcoin-e734847c1f50-win-unsigned.tar.gz
3d5a9855b4c5f330006c4a4213549f4bb40323778590b3300c827616004ad6de  guix-build-e734847c1f50/output/x86_64-w64-mingw32/bitcoin-e734847c1f50-win64-debug.zip
182e1c668784e16ce73be3175c7bf59012eeae5673b507ab58b164ef670590ab  guix-build-e734847c1f50/output/x86_64-w64-mingw32/bitcoin-e734847c1f50-win64-setup-unsigned.exe
34dc88b5898f4dcba8215a44b6ea545f05e9d7fa623fbb966ed27aeba35d0fdf  guix-build-e734847c1f50/output/x86_64-w64-mingw32/bitcoin-e734847c1f50-win64.zip
```

**Pull request merged**
