### PR TITLE
rpc: Add level 3 verbosity to getblock RPC call (#21245 modified)

### PR DESCRIPTION
**Pull request by kiminuo**
Author of #21245 expressed [time issues](https://github.com/bitcoin/bitcoin/pull/21245#issuecomment-902332088) in the original PR. Given that #21245 has received a lot of review*, I have decided to open this new pull request with [modifications required to get ACK from luke-jr ](https://github.com/bitcoin/bitcoin/pull/21245#issuecomment-905150806) and a few nits of mine.

### Original PR description

> Display the prevout in transaction inputs when calling getblock level 3 verbosity. This PR affects the existing `/rest/block` API by adding a `prevout` fields to tx inputs. This is mentioned in the change to the release notes.
> 
> I added some functional tests that
> 
>     * checks that the RPC call still works when TxUndo can't be found
> 
>     * Doesn't display the "value" or "scriptPubKey" of the previous output when at a lower verbosity level
> 
> 
> This "completes" the issue #18771

### Possible improvements

* https://github.com/kiminuo/bitcoin/commit/b0bf4f255f86aeaddce68889087c22f9068f4d97 - I can include even this commit to this PR if deemed useful or I can leave it for a follow-up PR. See https://github.com/bitcoin/bitcoin/pull/21245#issuecomment-894853784 for more context.

### Examples

Examples of the `getblock` output with various verbose levels. Note that `000000000000001f682b188971cc1a121546be4e9d5baf22934fdc7f538288d5` contains only 2 transactions.

(See: https://github.com/bitcoin/bitcoin/pull/21245#issuecomment-893313612)

#### Verbose level 0

```bash
./bitcoin-cli -testnet getblock 000000000000001f682b188971cc1a121546be4e9d5baf22934fdc7f538288d5 0
```

##### Verbose level 1

```bash
./bitcoin-cli -testnet getblock 000000000000001f682b188971cc1a121546be4e9d5baf22934fdc7f538288d5 1
```

##### Verbose level 2

```bash
./bitcoin-cli -testnet getblock 000000000000001f682b188971cc1a121546be4e9d5baf22934fdc7f538288d5 2
```

##### Verbose level 3

```bash
./bitcoin-cli -testnet getblock 000000000000001f682b188971cc1a121546be4e9d5baf22934fdc7f538288d5 3
```

#### REST

```bash
curl -H "content-type:text/plain;" http://127.0.0.1:18332/rest/block/000000000000001f682b188971cc1a121546be4e9d5baf22934fdc7f538288d5.json
```

<sub>* ... and my everyday obsessive checking of my email inbox whether the PR moves forward.</sub>

Edit laanwj: Removed at symbol from message, and large example output to prevent it from all ending up in the commit message.

### CODE REVIEW

**Comment by 0xB10C** [comment]
Concept ACK. Thanks for picking this up. Will review now that the requested changes are in.

**Comment by laanwj** [comment]
Concept ACK, this is a useful feature to have, an interesting approach to use the undo data.

**Review by luke-jr — APPROVED** [review]
utACK 305a59a7b55e2507f66729c9a42d5e8fd1cf23a7

**Review by luke-jr — APPROVED** [review]
re-utACK b0f7af35481c1ed6db4f20cec41443f9c0159f2b

**Review by meshcollider — COMMENTED** [review]
utACK 5c34507ecbbdc29c086276d1c62835b461823507

I am leaning towards including the helptext for the new verbosity level. Obviously that will make the help output pretty long, but I think it should be documented.

**Comment by kiminuo** [comment]
> re-utACK [b0f7af3](https://github.com/bitcoin/bitcoin/commit/b0f7af35481c1ed6db4f20cec41443f9c0159f2b)

@luke-jr Ah, you acked previous version, not the current one.

**Comment by kiminuo** [comment]
@theStack Would you please re-ACK if you feel like it?

**Comment by 0xB10C** [comment]
ACK 5c34507ecbbdc29c086276d1c62835b461823507

**Review by theStack — APPROVED** [review]
ACK 5c34507ecbbdc29c086276d1c62835b461823507 👘 

Verified via `git range-diff 72dbe981...5c34507e` that since my last ACK (review done in PR #21245, see https://github.com/bitcoin/bitcoin/pull/21245#pullrequestreview-724950830) all changes are rebase-related or minor improvements (related to comments, variable renames etc.).

**Review by promag — COMMENTED** [review]
Concept ACK 5c34507ecbbdc29c086276d1c62835b461823507

**Comment by laanwj** [comment]
Merged this as there were no critical comments, many ACKs, and to not drag this on forever. I do think in general it's better to just incorporate comments and not move small nits 'to follow-up PRs' because of fear of invalidating ACKs.

**Comment by fanquake** [comment]
> I do think in general it's better to just incorporate comments and not move small nits 'to follow-up PRs' because of fear of invalidating ACKs.

I agree. The point of PR review (among other things) is to get code to a mergable state. There are trade-offs depending on the size/complexity of a change, and whether or not everything _must_ be addressed, but I think we have started to drift too far to the wrong side of pushing changes to followups / not actually taking review suggestions onboard for fear of *invalidating ACKs* (not saying that is the case here).

**Pull request merged**
