### PR TITLE
The (line 49) command line didn't takes you into brew's interactive mode

### PR DESCRIPTION
**Pull request by chulini**
you have to add --interactive flag to enter brew's interactive mode

### CODE REVIEW

**Comment by fanquake** [comment]
I can't find any difference with or without --interactive. What actually happens when you run the install command?

**Comment by chulini** [comment]
The first time I installed berkeley-db4 the installation sent me to the regular console. Googling I've figured out that --interactive forces the interactive mode at the end of installation. Tried again with --interactive and that worked fine.

Now I've uninstalled berkeley-db4 an installed again *without* --interactive flag and sent me to the interactive mode just like with --interactive flag.

Maybe is was a issue in just my computer.

**Comment by Michagogo** [comment]
Um, how does a doc-only change fail CI? o_O

**Comment by theuni** [comment]
@Michagogo  See #5611 for the fix. The windows test was using random values, and just happened to blow up here.

**Pull request closed without merging**
