### PR TITLE
Docs: Properly alphabetize output of CLI --help option.

### PR DESCRIPTION
**Pull request by murrayn**
The --help output of bitcoind, bitcoin-cli, bitcoin-tx, qt/bitcoin-qt, et al. is only about 90% alphabetized by option, which is kind of sloppy and occasionally misleading. This change (mostly) organizes the output alphabetically.

### CODE REVIEW

**Comment by promag** [comment]
Lightly tested ACK d3e4675.

**Comment by sipa** [comment]
I had no idea it was so bad. Concept ACK

**Comment by laanwj** [comment]
utACK

**Review by randolf — APPROVED** [review]

**Comment by MarcoFalke** [comment]
utACK d3e467520fef3d9da1f3f2e8e79dcde34bec444f

**Pull request merged**
