### PR TITLE
MOVEONLY: Move logging code from util.{h,cpp} to new files.

### PR DESCRIPTION
**Pull request by jimpo**
Split out first commit from #12954 to reduce amount of rebasing necessary.

This introduces a cyclic dependency between `logging` and `util` that should be cleaned up in a future PR.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
utACK b77b6e23457dcbf160a3d586eca9df7a8d0bb351 (Lines are kept in the same order, which makes it easier to verify moveonly-ness)

**Comment by Empact** [comment]
utACK b77b6e2 also confirmed that the lines are repeated faithfully

**Comment by ajtowns** [comment]
utACK b77b6e23457dcbf160a3d586eca9df7a8d0bb351

Comparison with `git diff HEAD^ --color-moved=zebra` looks good. The cyclic dependency is logging.cpp to util.h to logging.h and there's a plan for breaking that cycle in #12954. Agree that this would be good to merge soon, since it's essentially a blocker for anything touching logging code.

**Comment by sipa** [comment]
utACK b77b6e23457dcbf160a3d586eca9df7a8d0bb351. Verified move-only.

**Pull request merged**
