### PR TITLE
test: Remove java comparison tool

### PR DESCRIPTION
**Pull request by laanwj**
There is a growing number of issues with it, and no one is really maintaining it anymore. From https://github.com/bitcoin/bitcoin/issues/4545#issuecomment-209938408:

> Seems I'll just have to set a deadline: I'm going to remove use of the unmaintained java-based comparison framework after the 0.13 branch-off (projected  2016-07-06, see #7679). I hope the Python framework will be a full replacement by then, but as this is holding up progress in other areas, that will not affect the decision.

@MarcoFalke worded it quite well too:

> If they don't and no one knows how to fix, we can remove them right now. Because the only thing they'd be doing then, is slowing down travis.
- The effort of porting the java comparison tool to Python is going very well, see e.g. #8141. If there is something left to do, I'm sure it can be resolved before the 0.14 release.
- The test is blocking changes such as #7093 (Address mempool information leak and resource wasting attacks).
- This test takes quite a while and is holding up enabling the tests for win32: #8227.
-  [comparison tool support seems to have been dropped from the v0.14](https://github.com/bitcoinj/bitcoinj/commit/1eaf05cacf35ebdf8e716eb84f0d5d0c051b3398) release of bitcoinj (discovered @droark)

This removes all the support for the tool, and removes it from depends (and hopefully all other references to it).

Not to be backported to 0.13.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Thank you!

ACK 3c5251d

**Comment by sipa** [comment]
Concept ACK

**Comment by laanwj** [comment]
@theuni can you have a look at the depends/build system changes here?

**Comment by droark** [comment]
ACK

Definitely not the person to sign off on the depends/build system changes but what I see strikes me as pretty thorough. I did a bit of a deep dive awhile back and seem to recall what's here as being everything that's related to the tool.

**Comment by theuni** [comment]
Woohoo, great to see this! Thanks to everyone involved.

Build-side looks good. The .travis.yaml can drop the hostname hack since we no longer require java, but that can be done as a follow-up.

utACK.

**Comment by laanwj** [comment]
@theuni Did I remove the right hack?

**Comment by MarcoFalke** [comment]
Yes, eb0c52e looks right. (c.f. #8253)

**Comment by theuni** [comment]
@laanwj yup, thanks.

**Pull request merged**
