### PR TITLE
refactor: Make CCoinsCacheEntry::Flags enum private

### PR DESCRIPTION
**Pull request by hodlinator**
Follow-up to #30906 which made it possible by removing external usage of the enum.

Move-only change, reviewable using:
`--color-moved=dimmed-zebra --color-moved-ws=ignore-all-space`

### CODE REVIEW

**Comment by l0rinc** [comment]
We want to completely remove the flags in the future since we're storing it redundantly (cc @andrewtoth), so this move is a nack from me.

**Comment by andrewtoth** [comment]
As @l0rinc alluded, we don't really need flags at all anymore. A dirty entry is one that is spent or is FRESH. So, we only really need a binary state now, not a bitfield, so we can replace flags with an `m_flags` boolean. `IsDirty()` can return `coin.IsSpent() || m_fresh`.

**Comment by hodlinator** [comment]
Ookay.. closing suggested follow-up PR due to unexpected welcome. :upside_down_face:

**Comment by andrewtoth** [comment]
Well, what about a PR with that approach to remove the flags bitfield and replace with a boolean for fresh only?

**Comment by hodlinator** [comment]
> Well, what about a PR with that approach to remove the flags bitfield and replace with a boolean for fresh only?

I'd prefer someone else more knowledgeable/active in this area take the initiative on such a transform.

**Comment by l0rinc** [comment]
> I'd prefer someone else more knowledgeable/active in this area take the initiative on such a transform.

We can help with the reviews - or even with describing the problem in more detail, but removing the flags (as described by @andrewtoth above) would be a lot more meaningful than just moving the flags.

**Pull request closed without merging**
