### PR TITLE
qt: Remove custom fee radio group and remove nCustomFeeRadio setting

### PR DESCRIPTION
**Pull request by achow101**
Removes the extraneous custom fee radio group and its single radio button. The radio button is replaced with a label that has the radio button's text.

Continuation of #11332

### CODE REVIEW

**Comment by promag** [comment]
Please rebase.

**Comment by achow101** [comment]
Rebased

**Comment by TheBlueMatt** [comment]
Concept ACK. Looks like travis failure was unrelated (some failure in p2p-versionbits-warning.py).

**Comment by jonasschnelli** [comment]
Concept ACK

**Comment by sipa** [comment]
Concept ACK

**Comment by laanwj** [comment]
utACK e53fa4a

**Pull request merged**
