### PR TITLE
contrib: run test-symbol-check for RISC-V

### PR DESCRIPTION
**Pull request by fanquake**
Now that we are using Focal for gitian building (glibc 2.31), we can use a newer introduced symbol, and include RISC-V in this test.

### CODE REVIEW

**Comment by laanwj** [comment]
Code review ACK 1211a90132eff1e796f248fff79d9e3d386f85e9
If this passes on RISC-V and all other platforms, it can be merged.

**Comment by fanquake** [comment]
I had to add a change to move the security check tests from a CI using Bionic, to one using Focal. This is also being done as a part of #21135.

**Comment by fanquake** [comment]
Linux gitian builds at ccb7b6a97652b45f60e0ac680a239bc6058b9773:
```bash
Generating report
414b7b6bd1abf7fda227aeb8e65382c0bba5ec4e0ddda064677d7b86ecbc96cc  bitcoin-ccb7b6a97652-aarch64-linux-gnu-debug.tar.gz
e2a229f6b973fa6691e967330330b4e6a43560dfd69bbf23c2b8793bc8454033  bitcoin-ccb7b6a97652-aarch64-linux-gnu.tar.gz
21db0c98fbe262ae0233a4ac79f87f02c4ea271db24f381cdfccd4f3c101e56b  bitcoin-ccb7b6a97652-arm-linux-gnueabihf-debug.tar.gz
5e3949af1fd7c853d65dc22d7473b5abd12c1c10261c454f56bb9a1972b1ff7a  bitcoin-ccb7b6a97652-arm-linux-gnueabihf.tar.gz
eb8c318cd57ae1ad8cbd509101799cb32fa6ad49b10c66d461fd8265a7ed2b8b  bitcoin-ccb7b6a97652-powerpc64-linux-gnu-debug.tar.gz
2ec50b2c7188e3009f11c2c78ab77d33bac03735eebe8ac87e4af060e77f7c8a  bitcoin-ccb7b6a97652-powerpc64-linux-gnu.tar.gz
cc998e88efdbf94c489e2ef8ef6c7c118005a8f1b7cf28db2e17824361b6fcaf  bitcoin-ccb7b6a97652-powerpc64le-linux-gnu-debug.tar.gz
25ed164efdcfc4f81954ba39264f71cc62b9a44e628f05458d6e3c8ec246288b  bitcoin-ccb7b6a97652-powerpc64le-linux-gnu.tar.gz
e2bb2aee23ee1a5d4f9ae6f8ede8ace915a583a45a2b21fc9aa6a176b590cabb  bitcoin-ccb7b6a97652-riscv64-linux-gnu-debug.tar.gz
1efe0fb31af22850dccecb70597ce46c16cbe5e740b39c72c015a3a5f17283b8  bitcoin-ccb7b6a97652-riscv64-linux-gnu.tar.gz
da1473854096bb61696362bf2d8f1f8f1db96286624cbed724f9ee46a9a45f15  bitcoin-ccb7b6a97652-x86_64-linux-gnu-debug.tar.gz
485f0351307418242cee4d3299d0b0bc245f591bcd10008c7098d3a06d7c814b  bitcoin-ccb7b6a97652-x86_64-linux-gnu.tar.gz
ef9a38853dee9017a9fd0dc83c67f180250f9c9c39f69ea325e5ffbd5f561d93  src/bitcoin-ccb7b6a97652.tar.gz
c4fb9d7512f40995ea39a9e35c66292c2603f162b69f51e6918d6895027a1001  bitcoin-core-linux-22-res.yml
Done.
```

**Comment by fanquake** [comment]
Linux Guix builds at ccb7b6a97652b45f60e0ac680a239bc6058b9773:
```bash
bash-5.1# find output/ -type f -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum
efe8c167f5a153dcefb1aab2a4edae8a56187fa588318d96c4958876ec157935  output/bitcoin-ccb7b6a97652-aarch64-linux-gnu-debug.tar.gz
1dc1c3a174d4e027d597cdac64c0de64ded472280b7524b8ae5417660ee0038a  output/bitcoin-ccb7b6a97652-aarch64-linux-gnu.tar.gz
114335ee7daa54e7b4192b4fe54a698ec2fb53dfb76471ae49a43bac85b3d2b7  output/bitcoin-ccb7b6a97652-arm-linux-gnueabihf-debug.tar.gz
e103199663d2b0c0ff0b1307e36ed682d15039008ab001c241650eec98652e6a  output/bitcoin-ccb7b6a97652-arm-linux-gnueabihf.tar.gz
67d814c48a555fd4972221ef94bf53c3e955bfa28361c569a9bf79c9542b51eb  output/bitcoin-ccb7b6a97652-riscv64-linux-gnu-debug.tar.gz
fd9a4b150a4b397ce4940c715acc6b0a2d265e2c475de744f1ad905f904164b6  output/bitcoin-ccb7b6a97652-riscv64-linux-gnu.tar.gz
461f0b8f4a20b6423e64805aac61e89a4ae906433f3c43a8223a442b521d4989  output/bitcoin-ccb7b6a97652-x86_64-linux-gnu-debug.tar.gz
b01c9f5dc3fcfd489d595d81d64e0b200321bfa4314b140674808acb54ee48b7  output/bitcoin-ccb7b6a97652-x86_64-linux-gnu.tar.gz
ef9a38853dee9017a9fd0dc83c67f180250f9c9c39f69ea325e5ffbd5f561d93  output/src/bitcoin-ccb7b6a97652.tar.gz
```

**Comment by laanwj** [comment]
Gititan build succesful:
```
414b7b6bd1abf7fda227aeb8e65382c0bba5ec4e0ddda064677d7b86ecbc96cc  bitcoin-ccb7b6a97652-aarch64-linux-gnu-debug.tar.gz
e2a229f6b973fa6691e967330330b4e6a43560dfd69bbf23c2b8793bc8454033  bitcoin-ccb7b6a97652-aarch64-linux-gnu.tar.gz
21db0c98fbe262ae0233a4ac79f87f02c4ea271db24f381cdfccd4f3c101e56b  bitcoin-ccb7b6a97652-arm-linux-gnueabihf-debug.tar.gz
5e3949af1fd7c853d65dc22d7473b5abd12c1c10261c454f56bb9a1972b1ff7a  bitcoin-ccb7b6a97652-arm-linux-gnueabihf.tar.gz
eb8c318cd57ae1ad8cbd509101799cb32fa6ad49b10c66d461fd8265a7ed2b8b  bitcoin-ccb7b6a97652-powerpc64-linux-gnu-debug.tar.gz
2ec50b2c7188e3009f11c2c78ab77d33bac03735eebe8ac87e4af060e77f7c8a  bitcoin-ccb7b6a97652-powerpc64-linux-gnu.tar.gz
cc998e88efdbf94c489e2ef8ef6c7c118005a8f1b7cf28db2e17824361b6fcaf  bitcoin-ccb7b6a97652-powerpc64le-linux-gnu-debug.tar.gz
25ed164efdcfc4f81954ba39264f71cc62b9a44e628f05458d6e3c8ec246288b  bitcoin-ccb7b6a97652-powerpc64le-linux-gnu.tar.gz
e2bb2aee23ee1a5d4f9ae6f8ede8ace915a583a45a2b21fc9aa6a176b590cabb  bitcoin-ccb7b6a97652-riscv64-linux-gnu-debug.tar.gz
1efe0fb31af22850dccecb70597ce46c16cbe5e740b39c72c015a3a5f17283b8  bitcoin-ccb7b6a97652-riscv64-linux-gnu.tar.gz
da1473854096bb61696362bf2d8f1f8f1db96286624cbed724f9ee46a9a45f15  bitcoin-ccb7b6a97652-x86_64-linux-gnu-debug.tar.gz
485f0351307418242cee4d3299d0b0bc245f591bcd10008c7098d3a06d7c814b  bitcoin-ccb7b6a97652-x86_64-linux-gnu.tar.gz
ef9a38853dee9017a9fd0dc83c67f180250f9c9c39f69ea325e5ffbd5f561d93  src/bitcoin-ccb7b6a97652.tar.gz
594fc8c760b27c868f51630c2f8b689f4cf54ed831a7c033ce70a4af595ef844  bitcoin-core-linux-22-res.yml
```

**Pull request merged**
