### PR TITLE
RPC method 'encodescript'

### PR DESCRIPTION
**Pull request by rodentrabies**
Implements proposal in #12948.

Progress:
- [ ] method implementation;
- [ ] functional test.

### CODE REVIEW

**Comment by MeshCollider** [comment]
Concept ACK

**Comment by sipa** [comment]
I don't think it's very useful to open a PR before you have an implementation.

If you have design questions that need to be solved first, you can open an issue, or comment on the existing one.

**Comment by fanquake** [comment]
I agree with @sipa. Pull requests are meant for code that's ready for review, they are not meant to be placeholders/a way to indicate you are working on something.

If you want to discuss technical approach/design, please do so in #12948. Then, once you have some code ready for review, please open a PR.

**Comment by mrwhythat** [comment]
@sipa, @fanquake, that was exactly my intent, to use it as a placeholder and keep track of tasks for today:) Sorry and thanks for a guideline. Will push an implementation in a couple of hours and reopen.

**Comment by mrwhythat** [comment]
Can this be reopened for review now. Tests are still missing but a straightforward implementation is ready.

**Pull request closed without merging**
