### PR TITLE
WIP: Touch appveyor vcpkg file to force refresh

### PR DESCRIPTION
**Pull request by sipsorcery**
Non merge/review. PR will be deleted once appveyor job has run.

### CODE REVIEW

**Comment by Sjors** [comment]
Do you think the current issue was triggered by my rebase of #15382, which adds `boost-process`?

**Comment by sipsorcery** [comment]
> Do you think the current issue was triggered by my rebase of #15382, which adds `boost-process`?

Yes I suspect building your PR may have thrown a spanner in the works. Perhaps because the Bitcoin Core appveyor account allows two simultaneous jobs the dependency cache got corrupted somehow. It's normally just a matter of re-building the vcpkg package dependencies to fix which is what this PR should do.

**Comment by Sjors** [comment]
Should we make the cache machine specific (assuming there's an environment param to indicate which machine we're on)?

**Comment by sipsorcery** [comment]
My understanding is the cache is not stored on a per virtual machine basis. You specify a cache key (a directory path) and all instances of the job download the cache entry when they start. 

I think the approach here is that we accept we'll have occasional issues with appveyor dependencies and deal with them on a case by case basis. They should be relatively rare particularly since we've pegged the vcpkg ports files to a specific commit ID.

**Comment by sipsorcery** [comment]
Appveyor working again,

**Pull request closed without merging**
