### PR TITLE
Trivial: Add common failure cases for rpc server connection failure

### PR DESCRIPTION
**Pull request by instagibbs**
As of now if you're not familiar with the other error responses, you might not know why connection failed. Give common reasons for this particular error message.

### CODE REVIEW

**Comment by laanwj** [comment]
Concept ACK, but I think this message is becoming too long to be crammed into one line. I think it'd make sense to write it out over multiple lines, e.g. leave the last line for the detailed error message (if any).

**Comment by instagibbs** [comment]
added newline to break it up some of the text

**Comment by MarcoFalke** [comment]
utACK 8f329f991bc81ddcfb4f51574e2003edde14e996

**Comment by laanwj** [comment]
Tested ACK 8f329f9

**Comment by laanwj** [comment]
This is a bit confusing now:
```
$ cli getinfo
error: couldn't connect to server
(make sure server is running and you are connecting to the correct RPC port: -1 unknown)
```
If you don't know better it seems like the *port* is unknown. I think this would be better:
```
$ cli getinfo
error: couldn't connect to server:  unknown (-1)
(make sure server is running and you are connecting to the correct RPC port)
```

**Comment by kameroni** [comment]
Bonjour

**Pull request merged**
