### PR TITLE
crypto: Fix K1/K2 use in the comments in ChaCha20-Poly1305 AEAD

### PR DESCRIPTION
**Pull request by stratospher**
As per [#22331](https://github.com/bitcoin/bitcoin/pull/22331) and the [Detailed Construction of the ChaCha20Forward4064-Poly1305@Bitcoin cipher suite](https://gist.github.com/jonasschnelli/c530ea8421b8d0e80c51486325587c52#detailed-construction) mentioned in BIP 324, K1 is used for encrypting the associated data(message length) and instantiating the Poly1305 MAC while K2 is used for encrypting the payload. This PR fixes the comments which need to be updated in:

1. The test vector in `src/test/crypto_tests.cpp`
2. In `src/crypto/chacha_poly_aead.h`,  `m_chacha_main` is a K2 ChaCha20 cipher instance and should be used for encrypting the payload. Also,  `m_chacha_header` is a K1 ChaCha20 cipher instance and is used for encrypting the length and instantiating the Poly1305 MAC.

### CODE REVIEW

**Comment by dhruv** [comment]
Thanks for catching that, @stratospher 

ACK dc904064ffc9aa9cf4215d910bc496b1ced16d2c

**Review by shaavan — COMMENTED** [review]
Concept ACK

This PR fixes the comments surrounding k1 and k2 keys to indicate their usages properly. As per BIP 324, I agree with the changes.

**Review by shaavan — APPROVED** [review]
ACK e3c15d555138bf9900268c05c39182b8fa98a673

**Review by siv2r — COMMENTED** [review]
Concept ACK

nit: It might be better to [squash your commits](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#squashing-commits).

**Review by Zero-1729 — COMMENTED** [review]
ACK be7f413

LGTM, this patch accurately updates the comments in accordance with BIP 324.

**Review by shaavan — APPROVED** [review]
reACK be7f4130f996b2564041719177f0a907e5c2011b

**Review by jonatack — COMMENTED** [review]
Concept ACK, nice find.

**Comment by laanwj** [comment]
@stratospher Your git name is "=", you might want to change this so that crediting you in the release notes is easier next time. For 23.0 I'm going to use "stratospher".

**Pull request merged**
