### PR TITLE
fuzz: Disable debug log file

### PR DESCRIPTION
**Pull request by maflcko**
There are several issues with writing to a debug log file when fuzzing:

* Disk access is slow, but fuzzing should be fast (Note: I could not verify this claim with data)
* Disks have a limited size and will eventually run out of space, but fuzzing should run continuous

Fix both issues by disabling the debug log file for fuzz tests

### CODE REVIEW

**Comment by practicalswift** [comment]
Concept ACK

Thanks for doing this: faster fuzzing is better fuzzing.

**Comment by MarcoFalke** [comment]
Rebased now that #18615 is merged

**Comment by practicalswift** [comment]
ACK fa69f88486e900aacf3fc768671f947927173226 -- patch looks correct

**Comment by MarcoFalke** [comment]
I couldn't verify my claim that this speeds up fuzzing, but at least I am no longer running out of disk space, so I think it is still required.

**Pull request merged**
