### PR TITLE
Package Mempool Submission with Package Fee-Bumping

### PR DESCRIPTION
**Pull request by glozow**
This implements mempool validation logic for fee-bumping transactions using CPFP and RBFing mempool transactions within a package, and the combination of both (i.e. a child in a package can pay to RBF its parents' conflicts). This does not implement package relay; there are no P2P changes.

For more info, see full proposal [gist](https://gist.github.com/glozow/dc4e9d5c5b14ade7cdfac40f43adb18a).

**Package Mempool Accept Progress**:
- [x] #21062
- [x] #20833
- [x] #21800
- [x] #22675 
- [x] #23381
- [x] #22674
- [x] #23804
- [x] #24152
- [x] #24836 
- [ ] #25038

Note that, until package relay exists, fee-bumped package transactions that are otherwise too-low-fee won't go any further than the user's mempool. This PR doesn't expose the package validation codepath to users because it would be misleading.

### CODE REVIEW

**Comment by sdaftuar** [comment]
I have some concerns around what semantics are desired for bypassing the fee rate checks for a single transaction and using a notion of package fee rate instead.

I think the logic here — of using the descendant fee rate as an alternate to the transaction’s fee rate — is insufficient for preventing free relay.  Consider a 3 transaction package where one child transaction C has two parents, A and B, all of equal size.  Suppose A and B are zero-fee transactions and C has a fee rate of 2.  Then each of A and B would evaluate to having a fee rate of 1 (with C), but as a package the fee rate would be just 2/3.  If the mempool min fee or min relay fee is 1, then this package would make it in despite being below the required fee rate.

I think this type of issue may be somewhat difficult to avoid if we don’t tailor our semantics to the use case(s) we are trying to support.  Right now, if I understand correctly, we don’t enforce any particular topology on the packages we accept — in fact I think the package acceptance logic would even accept unrelated transactions as well?  One idea I had was to require the whole package’s fee rate to be above the min relay and mempool min fee as well, but that doesn’t work very well if we allow someone to bundle in an unrelated high fee transaction to “pay” for some low fee rate package.

We could check that a package is connected (from a graph theory perspective) as a condition for acceptance, but that is also not quite sufficient for achieving the semantics that I think we want.  For instance, if we are processing some package that has a sub graph of transactions which would not make it in on its own, we probably wouldn’t want to admit that whole graph?  I’m not quite sure.  It seems like if there is a detachable sub graph that would get evicted shortly after acceptance because it’s below the mempool min fee, that might still admit some kind of free relay problem, similar to the issue with unrelated transactions.

My previous approach to the package relay problem was to define packages in a future p2p protocol extension as being the set of unconfirmed ancestors of a single target transaction.  If that is sufficient for the use cases we are currently trying to support, then I think that simplifies the concerns a great deal — in this simple case I believe we could just look at two things: (a) check the target transaction’s own fee rate is sufficient to get in, and (b) check that the entire ancestor package for that target transaction also has a total fee rate sufficient to get in.  (Of course we’d have to add a check that validates a package only contains ancestor transactions of the target, too.)

The other benefit of using a target transaction’s ancestors as how we define a package is that it lines up better with how the mining algorithm currently works.

If multiple children paying for multiple parents is some desired use case, I’m not sure the mempool and mining code are set up well enough to support that, so it would be helpful to analyze those use cases better to make sure our implementation will work okay.

**Comment by Rspigler** [comment]
> in this simple case I believe we could just look at two things: (a) check the target transaction’s own fee rate is sufficient to get in, and (b) check that the entire ancestor package for that target transaction also has a total fee rate sufficient to get in.

This seems reasonable.

**Comment by glozow** [comment]
Thank you for the thoughtful review @sdaftuar!

> I think the logic here — of using the descendant fee rate as an alternate to the transaction’s fee rate — is insufficient for preventing free relay. Consider a 3 transaction package where one child transaction C has two parents, A and B, all of equal size. Suppose A and B are zero-fee transactions and C has a fee rate of 2. Then each of A and B would evaluate to having a fee rate of 1 (with C), but as a package the fee rate would be just 2/3. If the mempool min fee or min relay fee is 1, then this package would make it in despite being below the required fee rate.

Great point. I had been thinking of descendant feerate as a good marker since that's how we evict from mempool, but it is imperfect: I think we already have the case where a transaction's ancestor score is too low to be mined, but descendant score too high to be evicted. And it's additionally problematic with package relay.

A proposal: if the mempool is intended to store the best candidates for mining, then we should evict in the opposite order we include in blocks, which is ancestor score.
So a transaction's `minerscore = max([ancestorfeerate(tx) for tx in {itself, all its descendants}])`. (This is with the current mining code - I suppose the definition of `minerscore` would be updated if/when block template creation changes).

If we replaced descendant feerate with `minerscore`, would that solve this problem? We go through the package, calculate everyone's ancestor feerate (including in-package and in-mempool ancestors), then we calculate everyone's `minerscore` based on that? Everyone's `minerscore` must surpass the min mempool/relay feerate. I think, then, it might not be necessary to specify/figure out which transactions are sponsees and which ones are sponsors?

(Very far down the line, but just throwing a thought out there: considering feefilters with package relay, I think we would also want to use [unmodified] `minerscore` for feefiltering as well).

**Comment by sdaftuar** [comment]
> A proposal: if the mempool is intended to store the best candidates for mining, then we should evict in the opposite order we include in blocks, which is ancestor score.
So a transaction's minerscore = max([ancestorfeerate(tx) for tx in {itself, all its descendants}]). (This is with the current mining code - I suppose the definition of minerscore would be updated if/when block template creation changes).

> If we replaced descendant feerate with minerscore, would that solve this problem? 

I think we should consider these two things separately: (1) whether to change the eviction algorithm used by the mempool, and (2) whether to change the fee rate heuristic used to evaluate transaction / package acceptance.

---
Regarding the use of the miner score based on maximum-ancestor-feerate-of-descendants, I think that heuristic doesn't work very well for eviction.  Imagine this scenario: the mempool has a very large, very low fee rate transaction A, with children B and C.  C also is a child of another low feerate parent D.

It is possible then that B has such a high feerate that A and B would be selected for the next block, and then that C and D would be selected as well (once A is paid for by B, C's ancestor feerate score would go up).  However, if A is in fact very large, then C's own ancestor fee rate could be quite low, so that D's `minerscore` could be very small.  This might mean that D and C could be evicted if the mempool were full, even if they would be selected for the next block!

(As an aside I think the worst-case computation required to maintain this score would be worse than the status quo, too -- going from O(n) to O(n^2) to update statistics in the mempool when transactions are added/removed, where n = ancestor/descendant count.)

---
However regarding the heuristic we use for admitting a package to the mempool, I think using this max-ancestor-feerate-of-descendants as an additional check that we compare to the min-relay-fee and mempool-min-fee probably does work.  It might mean that packages which include a transaction that would be relying on some in-mempool-sibling to pay for a low fee parent might not make it in, but if that's not a use case we're worried about then probably this is fine (if conservative)?

That seems to be a generalization of what I had proposed; I had suggested requiring a single ancestor-package that passes the fee rate check in total, while you're saying we can just require that every transaction in the package be part of some ancestor package that would pass the fee rate check.  I'll give that more thought but it seems like a plausible solution.

**Comment by glozow** [comment]
Right, I agree with the separation between mempool eviction policy and evaluation of package transactions. Won't pursue the former much further here... 

My plan of attack after the IRC [discussion](https://gist.github.com/glozow/d362100715e9a3e2e61cb4b600663377) last night is going to be 1 parent + 1 child packages (perhaps these can also be thought of as 1 sponsee + 1 sponsor) and I think checking everyone's max-ancestor-feerate-of-descendants or descendant feerate of sponsee & ancestor feerate of sponsor would all work.

> One additional thought, assuming this idea works at all I think it ought to be sufficient to restrict the calculation of the score to the package transactions alone. That is, for each transaction, calculate its fee rate for mempool acceptance as max([in-package-ancestor-fee-rate(tx) for tx in {itself, descendants}], where the in-package-ancestor-fee-rate(tx) is defined to be the min(tx fee rate, tx's fee rate including in-package ancestors). And then for each transaction in the package, evaluate that fee rate against the mempool min fee and the min relay fee. The idea is that we only need to ensure that we're paying enough to justify relay of the transactions -- when the network gets busier, the mempool min fee goes up so as long as the new transaction packages being relayed are continuing to have their fee rates go up too, that should be good enough to prevent free relay. There shouldn't be any need to look at the fee rates of the transactions that are already in the mempool.

Good point!!!

**Comment by glozow** [comment]
Next PR ready for review is #24152.

**Comment by glozow** [comment]
Actually that's a good point @DrahtBot - this PR was made to track progress on package relay / package mempool stuff but it's not great at it since there are now multiple branches, v3 is separated, and there are things in multiple repos.
Possibly more helpful, here's a board to track everything package relay-related: https://github.com/orgs/bitcoin/projects/4/views/1?layout=board

**Comment by flack** [comment]
@glozow that link gives a 404 for me. Also the board you mention isn't listed in https://github.com/orgs/bitcoin/projects?query=is%3Aopen. Or is it only accessible to members?

**Comment by glozow** [comment]
@flack apologies I didn't realize! It should be public now.

**Pull request closed without merging**
