### PR TITLE
depends: Improve id string robustness 

### PR DESCRIPTION
**Pull request by dongcarl**
```
Environment variables and search paths can drastically effect the
operation of build tools.

Include these in our id string to mitigate against false cache hits.
```

Note to builders: This will invalidate all depends output caches in `BASE_CACHE`

### CODE REVIEW

**Comment by laanwj** [comment]
Concept ACK. If I understand it correctly, this includes only specific targeted environment variables and not the entire env?

**Comment by luke-jr** [comment]
`gcc -v -E -` seems to lose `COLLECT_LTO_WRAPPER`...

**Comment by dongcarl** [comment]
> Concept ACK. If I understand it correctly, this includes only specific targeted environment variables and not the entire env?

Yes! It automatically includes any env var that starts with the name of the tool (e.g. `STRIP_*` for `strip`), and if there are particular ones we know about (e.g. `ZERO_AR_DATE`) we can just append it like so: [`6ee5ee4` (#20629)](https://github.com/bitcoin/bitcoin/pull/20629/commits/6ee5ee405a94ae006f55924e3219134c752ab0d8#diff-eedaa015e7a0c44dda909e3ccd2b890f5f75aaf0d350bda143fad18f0070b8a0R118)

**Comment by dongcarl** [comment]
> `gcc -v -E -` seems to lose `COLLECT_LTO_WRAPPER`...

Right, perhaps someone knows a better invocation here? I'm guessing `COLLECT_LTO_WRAPPER` is omitted because the linker is not going to run?

**Comment by dongcarl** [comment]
Pushed 4b9aaca598aea561d44215eecd3c4a01d08ddd5a -> f792069bc117f11dff0db11f9386ec216581d2a2
1. Added an invocation of CC/CXX with just "-v" to pick up COLLECT_LTO_WRAPPER
1. Added comment about COLLECT_LTO_WRAPPER and the weird fd indirection trick

**Comment by laanwj** [comment]
Code review ACK f792069bc117f11dff0db11f9386ec216581d2a2

**Comment by laanwj** [comment]
re-ACK 5200929bfe26c549d7da92c0adf8adf61e143416

**Pull request merged**
