### PR TITLE
Docs: Fix minor error in doc/psbt.md

### PR DESCRIPTION
**Pull request by bitcoinhodler**
It's pretty clear that the author meant "rather than" here.

### CODE REVIEW

**Comment by Empact** [comment]
trivial ACK

**Comment by MeshCollider** [comment]
Trivial ACK https://github.com/bitcoin/bitcoin/commit/72b63bc9054f7742a9b12ea29b21770b5e437092

**Comment by fanquake** [comment]
utACK 72b63bc, will add to #14945 as well.

**Comment by practicalswift** [comment]
ACK 72b63bc9054f7742a9b12ea29b21770b5e437092

Welcome as a contributor @bitcoinhodler!

**Comment by promag** [comment]
ACK.

**Comment by fanquake** [comment]
Backported in #14945.

**Pull request merged**
