### PR TITLE
[backups] Automatic backups basics

### PR DESCRIPTION
**Pull request by jonasschnelli**
- allow to do automatic backups when keypool gets refilled
- by default backups are turned off
- by default only encrypted wallets are allowed for backup (configurable)

This could be the basic for later adding backup possibilities for Bitcoin-Qt including visual elements for latest and amount of backups as also validity-check-display of backup files.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
rebased

**Comment by jonasschnelli** [comment]
rebased.

**Comment by jonasschnelli** [comment]
I'm no longer convinced that this PRs solution if this is going into the right direction. As example: what means a encrypted wallet? Why are metadata like labels and comments (which could harm privacy) not encrypted in a encrypted wallet?
How this would perform after there is support for Bip32?

**Comment by gmaxwell** [comment]
@jonasschnelli   Things other than private keys are not encrypted because otherwise the user is forced to enter their key at every startup or use, which is inconvenient and would punish users for using encryption and would leave their key more vulnerable to observation by malware or people around them. The entry of the key also becomes an important consent point: a user of an encrypted wallet can never accidentally send money no matter how stupidly they click or how far they explore.

Encryption of a wallet is not usually adequate for privacy on your local computer in any case:  your logs, browser cache, etc all leak much of the same data...  When we talk about backups the situation is somewhat different, and I can agree it may make sense to have all the data encrypted there.  If I were to do it again I would have an master key encrypted with the hardened user passphrase used to derive separate keys for encrypting the whole wallet and the private keys. At the first use, I'd cache the whole wallet subkey (but not the private key one) in a separate file.  This way backups would preserve privacy, so long as they didn't backup the cache.

BIP32 is not at all a replacement for backups; at most it protects key material. It does nothing to preserve metadata which can be absolutely critical (keeping in mind that in much of the developed world if your taxes are audited its up to you to prove you were paying what you owed). I somewhat regret inventing the public derivation thats most commonly used now-- it's overused, and in ways that harm security (often by people who do not understand the implications).

**Comment by jgarzik** [comment]
Closing for this older PR.  It sounds like there is general agreement that something like this is a good direction, but it's doesn't seem to be coalescing into a specific solution that is liked.

My own criticism:   I don't think this low level functionality is needed at all for non-GUI daemon.  It can be implemented with a simple, external cron script that applies well to the local site.

Suggestions:
* Add such a script to contrib/
* Directly implement a GUI-specific, user-friendly backup method in the GUI.  Don't try to match bitcoind and GUI backup behaviors, as the two sets of users can be quite different.  Do what makes sense for the GUI.

**Comment by jonasschnelli** [comment]
Agree with @jgarzik in general.
What made me stop woking on this: as long as an "encrypted wallet" contains unencrypted sensitive data  (like transactions [unencrypted], labels [unencrypted] and wtx comments [unencrypted]) it is to risky to auto-backup a wallet.
Users might start to think they can store the backup in a insecure space (like dropbox, etc.) because they are assuming the backup is encrypted (which is a false assumption, only the private keys are encrypted).

**Pull request closed without merging**
