### PR TITLE
[qa] univalue: Bump subtree

### PR DESCRIPTION
**Pull request by maflcko**
Pulls in the test changes to the univalue subtree.

Beside looking at the code, reviewers should refer to https://github.com/bitcoin/bitcoin/blob/master/contrib/devtools/README.md#git-subtree-checksh on how to verify the subtree pull.

### CODE REVIEW

**Comment by jnewbery** [comment]
Tested ACK fa58ff9c40632b00961abf9b09acee1bda1c5d3c. I've manually checked the commits, run the tests, and verified git-subtree-check:

```
./contrib/devtools/git-subtree-check.sh src/univalue
src/univalue in HEAD currently refers to tree 46076c3c05f8fb95a7bdad3f5c93d01f14ecbf9d
src/univalue in HEAD was last updated in commit 351fadd68a49e8955b1b0185da1eb90fa53a4cc6 (tree 46076c3c05f8fb95a7bdad3f5c93d01f14ecbf9d)
src/univalue in HEAD was last updated to upstream commit ec849d9a2889e89ba484dacbc7d2ce258f090545 (tree 46076c3c05f8fb95a7bdad3f5c93d01f14ecbf9d)
GOOD
```

**Review by ryanofsky — COMMENTED** [review]
NACK (I think) to fa58ff9c40632b00961abf9b09acee1bda1c5d3c, unless I am misunderstanding something. This seems to be using https://github.com/bitcoin-core/univalue/commits/ec849d9a2889e89ba484dacbc7d2ce258f090545 as the upstream commit, but that commit isn't a master commit on either https://github.com/bitcoin-core/univalue/commits/master or https://github.com/jgarzik/univalue/commits/master. I think if you switch to https://github.com/bitcoin-core/univalue/commit/07947ff2da9ef02a9dfa13346bc5545708e3ebe7 instead this should be good.

**Comment by MarcoFalke** [comment]
@ryanofsky It is a commit on the master branch for me. C.f.

```
$ git log univalue/master -3 --oneline && git log ec849d9a2889e89ba484dacbc7d2ce258f090545~ --oneline -1
07947ff2da (univalue/master) Merge #9: [tests] Fix BOOST_CHECK_THROW macro
ec849d9a28 [tests] Fix BOOST_CHECK_THROW macro
31bc9f5a49 Merge #8: Remove unused Homebrew workaround
31bc9f5a49 Merge #8: Remove unused Homebrew workaround
```

So the 07947ff commit is an "empty" merge commit (artefact of the merge script to create commits even when fast-forward could have been used for the purpose of putting meta-information in there.) As we strip the meta information of commits for the purpose of subtree pulls, I fail to see the need to include it and redo the subtree pull.

**Comment by ryanofsky** [comment]
That only shows ec849d9a28 is _contained in_ the master branch. I wouldn't call it being on the _on_ the master branch because the master branch has never pointed to that commit and never will. Would it be difficult to update this PR so it merges in the right commit (07947ff2da instead of ec849d9a28)?

It is true that there that there is diff between 07947ff2da and ec849d9a28, but there are a few reasons why I think it is appropriate to update to 07947ff2da instead of ec849d9a28:

- 07947ff2da unlike ec849d9a28 references the PR number containing the BOOST_CHECK_THROW change. If you look at ec849d9a28 by itself you have no clue where that change is coming from, where to find the code review comments etc. If you wanted to run a changelog script that would include PR numbers, the PR would never be mentioned.
- 07947ff2da unlike ec849d9a28 is GPG signed.
- 07947ff2da unlike ec849d9a28 includes Tree-SHA512 hash
- 07947ff2da unlike ec849d9a28 has travis runs associated with it
- 07947ff2da unlike ec849d9a28 doesn't require manually diffing in order to verify that it matches the current master branch of the https://github.com/bitcoin-core/univalue repository.

**Comment by MarcoFalke** [comment]
Changed commit. Tree shouldn't change, obviously.

**Review by ryanofsky — COMMENTED** [review]
Thanks! utACK fad349c507a3179fa117ddf3ad6e651609c366cc, saw "GOOD" from git-subtree-check.sh

**Comment by MeshCollider** [comment]
utACK https://github.com/bitcoin/bitcoin/commit/fad349c507a3179fa117ddf3ad6e651609c366cc

**Comment by laanwj** [comment]
utACK fad349c
```
src/univalue in HEAD currently refers to tree 46076c3c05f8fb95a7bdad3f5c93d01f14ecbf9d
src/univalue in HEAD was last updated in commit 88411e98e50c92f8990733eee0bc353ac8f21a35 (tree 46076c3c05f8fb95a7bdad3f5c93d01f14ecbf9d)
src/univalue in HEAD was last updated to upstream commit 07947ff2da9ef02a9dfa13346bc5545708e3ebe7 (tree 46076c3c05f8fb95a7bdad3f5c93d01f14ecbf9d)
GOOD
```

**Pull request merged**
