### PR TITLE
test: Move test_chain_listunspent wallet check from mempool_packages to wallet_basic

### PR DESCRIPTION
**Pull request by maflcko**
This fixes a bug.

On master:

```
$ ./test/functional/mempool_packages.py  --legacy-wallet 
  File "./test/functional/mempool_packages.py", line 52, in run_test
    self.nodes[0].importaddress(self.wallet.get_address())
test_framework.authproxy.JSONRPCException: Bech32m addresses cannot be imported into legacy wallets (-5)
```

On this pull, all tests pass.

### CODE REVIEW

**Comment by Godonzrepublic** [comment]
WOW WOW GOOD NEW I HAVE BEEN GETTING LOT OF PROFITS WITH THE HELP OF THIS MOG VIA INSTA👉 @TECK_SPY

**Review by Godonzrepublic — COMMENTED** [review]
.

**Comment by achow101** [comment]
Is there a reason that this test needs the wallet in the first place?

**Comment by fanquake** [comment]
cc @glozow

**Comment by glozow** [comment]
> Yeah, the test doesn't need the wallet, but it is providing mempool-package coverage for the listunspent wallet RPC. So maybe an alternative would be to move it out into a new test, idk?

Would be in favor of moving the listunspent coverage to a new/existing `wallet_` functional test instead.

**Review by glozow — COMMENTED** [review]
ACK ffffe622e9cbf926326135bb23958380dcf09df1, thanks for changing! Nice to remove wallet from another non-wallet test.

**Pull request merged**
