### PR TITLE
tx_valid: re-order inputs to how they are encoded

### PR DESCRIPTION
**Pull request by dcousens**
Just something I noted when using these externally.
The new ordering matches how they are encoded in the serialised transaction.

If there was a reason for these to be ordered this way, then I've probably misinterpreted the test data.

### CODE REVIEW

**Comment by laanwj** [comment]
> If there was a reason for these to be ordered this way, then I've probably misinterpreted the test data.

That depends: is the re-ordering part of the test or not?

**Comment by dcousens** [comment]
> That depends: is the re-ordering part of the test or not?

They don't fail with this new ordering,  and the resultant transaction is encoded the same.
There does not appear to be any hints in the associated comments that the ordering was important either.

**Comment by dcousens** [comment]
> if (mapprevOutValues.count(tx.vin[i].prevout)) {

In the tests,  they are just using a map-lookup to see if the resultant inputs exist.
Ultimately it is the encoded transaction that was dictating the order (as can be seen in the "fixed" data).

**Comment by MarcoFalke** [comment]
No strong opinion about changing the order, but I think it makes sense to be consistent, if there was no particular reason for the current order.

**Comment by MarcoFalke** [comment]
@NicolasDorier Was there a particular reason you chose that order?

**Comment by NicolasDorier** [comment]
None, no strong opinion either.

**Comment by dcousens** [comment]
The motivation for this change was that it was intuitive at first why my tests were failing in an external open-source library that was testing against these inputs 1:1 (that is, I had an underlying assumption of the inputs being in-order).

**Comment by dcousens** [comment]
Anything further needed here?

**Pull request merged**
