### PR TITLE
Final backports for 0.21.2rc1

### PR DESCRIPTION
**Pull request by maflcko**

### CODE REVIEW

**Comment by hebasto** [comment]
Why only one commit is backported from #21644?

**Comment by MarcoFalke** [comment]
The other commits are unrelated test improvements. I am happy to ACK a pull that backports test improvements, but I probably won't backport it myself.

**Comment by hebasto** [comment]
Not sure if https://github.com/bitcoin-core/gui/pull/280 is backported correctly: diffs on 0.21 branch and on master are different.

**Comment by MarcoFalke** [comment]
```
qt/paymentserver.cpp: In member function ‘void PaymentServer::handleURIOrFile(const QString&)’:

qt/paymentserver.cpp:237:105: error: too many arguments to function ‘CTxDestination DecodeDestination(const string&)’

                 const CTxDestination dest = DecodeDestination(recipient.address.toStdString(), error_msg);

                                                                                                         ^

In file included from qt/paymentserver.cpp:17:0:

./key_io.h:25:16: note: declared here

 CTxDestination DecodeDestination(const std::string& str);

                ^

**Comment by hebasto** [comment]
> ```
> qt/paymentserver.cpp: In member function ‘void PaymentServer::handleURIOrFile(const QString&)’:
> 
> qt/paymentserver.cpp:237:105: error: too many arguments to function ‘CTxDestination DecodeDestination(const string&)’
> 
>                  const CTxDestination dest = DecodeDestination(recipient.address.toStdString(), error_msg);
> 
>                                                                                                          ^
> 
> In file included from qt/paymentserver.cpp:17:0:
> 
> ./key_io.h:25:16: note: declared here
> 
>  CTxDestination DecodeDestination(const std::string& str);
> 
>                 ^
> ```

Ah, right!

**Review by hebasto — APPROVED** [review]
ACK 09620b89f5f78434080196162c75e3e65cc8d47f, tested https://github.com/bitcoin-core/gui/pull/280 behavior.

**Comment by achow101** [comment]
ACK 09620b89f5f78434080196162c75e3e65cc8d47f Diffs match.

**Review by fanquake — APPROVED** [review]
ACK 09620b89f5f78434080196162c75e3e65cc8d47f

**Pull request merged**
