### PR TITLE
[Qt] fix a issue where "command line options"-action overwrite "Preference"-action (on OSX)

### LINKED ISSUE #5800: "Preferences" menu opens "command line options" when using French language (OSX)
When clicking on the "Preferences" menu when using French language, the "command line options" window opens instead of the usual preferences pane. I note that this works correctly when using English and a few other languages that I tested.

Bitcoin core version 10.99.0
OS: OSX 10.9.5

### PR DESCRIPTION
**Pull request by jonasschnelli**
fixes #5800

### CODE REVIEW

**Comment by jonasschnelli** [comment]
The QT behavior on mac will place menu action with string matching to "config, options, setup, settings or preferences" to the general application menu (at very left) and remove them from other menu positions (which is somehow weak IMO).

Currently i only added the `QAction::NoRole` role to the `showHelpMessageAction` action. It is might be discussable to add the "NoRole" to every "standard menu action".

**Comment by laanwj** [comment]
utACK

**Comment by fanquake** [comment]
utACK

**Comment by theuni** [comment]
Nice find. It's very weird that QT uses string matching here on purpose.

utAck.

**Comment by laanwj** [comment]
> It's very weird that QT uses string matching here on purpose

Yes. Qt's autodetection of html/plaintext for labels can be annoying, but this is a few magnitudes worse. The moral of the story is to leave as little a possible to defaults. Explicitly setting the role for all actions makes sense (if I remember correctly it also helps accessibility as screen readers and such use the info).

**Pull request merged**
