### PR TITLE
[26.x] Backports

### PR DESCRIPTION
**Pull request by fanquake**
Backports for `26.x`. Currently:
* https://github.com/bitcoin/bitcoin/pull/28920
* https://github.com/bitcoin/bitcoin/pull/28992
* https://github.com/bitcoin/bitcoin/pull/28994
* https://github.com/bitcoin/bitcoin/pull/29003
* https://github.com/bitcoin/bitcoin/pull/29023
* https://github.com/bitcoin/bitcoin/pull/29080
* https://github.com/bitcoin/bitcoin/pull/29176

### CODE REVIEW

**Comment by willcl-ark** [comment]
ACK 188e023d2fdab30b4a779a862b2c8b567bb15803

Checked diffs between Rebased-from commit hash and these commits themselves.

**Comment by fanquake** [comment]
Note that any tidy job failure here is currently related to https://github.com/bitcoin/bitcoin/pull/28992#issuecomment-1852101216 (and should be fixed in future).

**Comment by luke-jr** [comment]
7e90b5938f4dbdba58355f55f785c9054055a912 has a typo in the commit message

**Review by sedited — APPROVED** [review]
ACK 7b79e54474b86864c81148c74824bfe4b732412d

**Review by glozow — COMMENTED** [review]
ACK 7b79e54474b86864c81148c74824bfe4b732412d, matches mine

**Pull request merged**
