### PR TITLE
[Qt] make warnings label selectable (jonasschnelli)

### LINKED ISSUE #8970: Qt: Warning messages are not selectable
When a warning message is displayed in Bitcoin-QT, it is not possible to select it with the cursor (for copying or cutting).

### PR DESCRIPTION
**Pull request by maflcko**
Should fix #8970

### CODE REVIEW

**Comment by rebroad** [comment]
This has got to be the fastest fix I've witnessed so far!

**Comment by MarcoFalke** [comment]
The fix is from Dec, but never got merged.

**Comment by laanwj** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/8972/commits/ef0c9ee2960fda58b2fe5b0c3b4c672231b30322

**Comment by paveljanik** [comment]
tested ACK https://github.com/bitcoin/bitcoin/pull/8972/commits/ef0c9ee2960fda58b2fe5b0c3b4c672231b30322

**Comment by jonasschnelli** [comment]
Thanks.
Post merge utACK.

**Pull request merged**
