### PR TITLE
RPC Docs: gettxout*: clarify bestblock and unspent counts

### PR DESCRIPTION
**Pull request by harding**
Expounds on two things I've seen confuse inexperienced users:

- transactions/outputs in `gettxoutsetinfo`: a user thought this was the total number of transactions or outputs ever seen on the chain, whereas it's only the number in the UTXO.

- bestblock in `gettxout`: a user thought this was the block that included the output, not realizing it was the tip of the current best block chain.  I also copied this text to `gettxoutsetinfo` for congruency.  I skimmed other uses of "bestblock" in the RPC docs and they seemed clear to me.

### CODE REVIEW

**Comment by practicalswift** [comment]
Concept ACK

**Comment by harding** [comment]
Travis failure seems unrelated.

**Comment by MarcoFalke** [comment]
utACK f30e9be4c194e33c25c20989b3e74dcf9dee7d9a

**Comment by sipa** [comment]
utACK f30e9be4c194e33c25c20989b3e74dcf9dee7d9a

**Pull request merged**
