### PR TITLE
Remove folder and images for bootstrap.md

### PR DESCRIPTION
**Pull request by sandakersmann**
Remove folder and images for bootstrap.md due to removal of bootstrap.md

### CODE REVIEW

**Comment by fanquake** [comment]
Nice catch. Can you send this to https://github.com/theuni/bitcoin @ the trivial-next branch.

**Comment by paveljanik** [comment]
Travis build issue is a weird one - the build took 50 minutes...

**Comment by jonasschnelli** [comment]
ACK

**Comment by laanwj** [comment]
ACK @theuni this is something for the trivial branch

**Comment by theuni** [comment]
merged into trivial-next

**Comment by laanwj** [comment]
Thanks @theuni, closing

**Pull request closed without merging**
