### PR TITLE
include QPainterPath to fix compile error with Qt 5.15

### PR DESCRIPTION
**Pull request by puchu**
include QPainterPath to fix compile error with Qt 5.15

### CODE REVIEW

**Comment by puchu** [comment]
compile error is:

`qt/trafficgraphwidget.cpp: In member function ‘void TrafficGraphWidget::paintPath(QPainterPath&, QQueue<float>&)’:
qt/trafficgraphwidget.cpp:55:9: error: invalid use of incomplete type ‘class QPainterPath’
   55 |         path.moveTo(x, YMARGIN + h);
      |         ^~~~
In file included from /usr/include/qt5/QtGui/qbrush.h:49,
                 from /usr/include/qt5/QtGui/qpalette.h:46,
                 from /usr/include/qt5/QtWidgets/qwidget.h:48,
                 from /usr/include/qt5/QtWidgets/QWidget:1,
                 from ./qt/trafficgraphwidget.h:8,
                 from qt/trafficgraphwidget.cpp:6:
/usr/include/qt5/QtGui/qmatrix.h:54:7: note: forward declaration of ‘class QPainterPath’
   54 | class QPainterPath;
      |       ^~~~~~~~~~~~
qt/trafficgraphwidget.cpp:59:13: error: invalid use of incomplete type ‘class QPainterPath’
   59 |             path.lineTo(x, y);
      |             ^~~~
In file included from /usr/include/qt5/QtGui/qbrush.h:49,
                 from /usr/include/qt5/QtGui/qpalette.h:46,
                 from /usr/include/qt5/QtWidgets/qwidget.h:48,
                 from /usr/include/qt5/QtWidgets/QWidget:1,
                 from ./qt/trafficgraphwidget.h:8,
                 from qt/trafficgraphwidget.cpp:6:
/usr/include/qt5/QtGui/qmatrix.h:54:7: note: forward declaration of ‘class QPainterPath’
   54 | class QPainterPath;
      |       ^~~~~~~~~~~~
qt/trafficgraphwidget.cpp:61:9: error: invalid use of incomplete type ‘class QPainterPath’
   61 |         path.lineTo(x, YMARGIN + h);
      |         ^~~~
In file included from /usr/include/qt5/QtGui/qbrush.h:49,
                 from /usr/include/qt5/QtGui/qpalette.h:46,
                 from /usr/include/qt5/QtWidgets/qwidget.h:48,
                 from /usr/include/qt5/QtWidgets/QWidget:1,
                 from ./qt/trafficgraphwidget.h:8,
                 from qt/trafficgraphwidget.cpp:6:
/usr/include/qt5/QtGui/qmatrix.h:54:7: note: forward declaration of ‘class QPainterPath’
   54 | class QPainterPath;
      |       ^~~~~~~~~~~~
qt/trafficgraphwidget.cpp: In member function ‘virtual void TrafficGraphWidget::paintEvent(QPaintEvent*)’:
qt/trafficgraphwidget.cpp:109:22: error: aggregate ‘QPainterPath p’ has incomplete type and cannot be defined
  109 |         QPainterPath p;
      |                      ^
qt/trafficgraphwidget.cpp:116:22: error: aggregate ‘QPainterPath p’ has incomplete type and cannot be defined
  116 |         QPainterPath p;
      |                      ^
`

**Comment by puchu** [comment]
compile error is:

qt/trafficgraphwidget.cpp: In member function ‘void TrafficGraphWidget::paintPath(QPainterPath&, QQueue<float>&)’:
qt/trafficgraphwidget.cpp:55:9: error: invalid use of incomplete type ‘class QPainterPath’
   55 |         path.moveTo(x, YMARGIN + h);
      |         ^~~~
In file included from /usr/include/qt5/QtGui/qbrush.h:49,
                 from /usr/include/qt5/QtGui/qpalette.h:46,
                 from /usr/include/qt5/QtWidgets/qwidget.h:48,
                 from /usr/include/qt5/QtWidgets/QWidget:1,
                 from ./qt/trafficgraphwidget.h:8,
                 from qt/trafficgraphwidget.cpp:6:
/usr/include/qt5/QtGui/qmatrix.h:54:7: note: forward declaration of ‘class QPainterPath’
   54 | class QPainterPath;
      |       ^~~~~~~~~~~~
qt/trafficgraphwidget.cpp:59:13: error: invalid use of incomplete type ‘class QPainterPath’
   59 |             path.lineTo(x, y);
      |             ^~~~
In file included from /usr/include/qt5/QtGui/qbrush.h:49,
                 from /usr/include/qt5/QtGui/qpalette.h:46,
                 from /usr/include/qt5/QtWidgets/qwidget.h:48,
                 from /usr/include/qt5/QtWidgets/QWidget:1,
                 from ./qt/trafficgraphwidget.h:8,
                 from qt/trafficgraphwidget.cpp:6:
/usr/include/qt5/QtGui/qmatrix.h:54:7: note: forward declaration of ‘class QPainterPath’
   54 | class QPainterPath;
      |       ^~~~~~~~~~~~
qt/trafficgraphwidget.cpp:61:9: error: invalid use of incomplete type ‘class QPainterPath’
   61 |         path.lineTo(x, YMARGIN + h);
      |         ^~~~
In file included from /usr/include/qt5/QtGui/qbrush.h:49,
                 from /usr/include/qt5/QtGui/qpalette.h:46,
                 from /usr/include/qt5/QtWidgets/qwidget.h:48,
                 from /usr/include/qt5/QtWidgets/QWidget:1,
                 from ./qt/trafficgraphwidget.h:8,
                 from qt/trafficgraphwidget.cpp:6:
/usr/include/qt5/QtGui/qmatrix.h:54:7: note: forward declaration of ‘class QPainterPath’
   54 | class QPainterPath;
      |       ^~~~~~~~~~~~
qt/trafficgraphwidget.cpp: In member function ‘virtual void TrafficGraphWidget::paintEvent(QPaintEvent*)’:
qt/trafficgraphwidget.cpp:109:22: error: aggregate ‘QPainterPath p’ has incomplete type and cannot be defined
  109 |         QPainterPath p;
      |                      ^
qt/trafficgraphwidget.cpp:116:22: error: aggregate ‘QPainterPath p’ has incomplete type and cannot be defined
  116 |         QPainterPath p;
      |                      ^

**Comment by promag** [comment]
You should backport #19097 instead.

**Comment by puchu** [comment]
why wasn't this included in the 0.20 tag?

**Comment by promag** [comment]
Was set to 0.20.1 milestone.

**Comment by MarcoFalke** [comment]
This is part of the group that is tagged for backport: https://github.com/bitcoin/bitcoin/issues?q=label%3A%22Needs+backport+%280.20%29%22+

**Comment by laanwj** [comment]
If you add the appropriate backporting metadata (see https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#backporting) and copy the author/commit message then you could turn this into a backport of #19097.

**Comment by promag** [comment]
@puchu backport done in #19170.

**Pull request closed without merging**
