### PR TITLE
refactor: only use explicit reinterpret/const casts, not implicit

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
This PR converts 149 silent reinterpret_cast's into explicit reinterpret_cast's
This PR converts  33 silent const_cast's into explicit const_cast's

This PR is broken out from https://github.com/bitcoin/bitcoin/pull/23810, as it appears there is little appetite for the scope of change as outlined in that PR.

```
A C-style cast is equivalent to try casting in the following order:

    const_cast(...)
    static_cast(...)
    const_cast(static_cast(...))
    reinterpret_cast(...)
    const_cast(reinterpret_cast(...))

For a more thorough discussion, see "ES.49: If you must use a cast, use a named cast"
in the C++ Core Guidelines (Stroustrup & Sutter).
```

The PR resolves the most critical step of removing implicit c-style casts that act as reinterpret_casts or const_casts, additionally, this PR should be considerably less conflicting than it's predecessor. I at least hope that it is deemed the value will exceed the cost of conflicts.  

If there are any specific areas of the codebase that are heavily conflicting compared to others, I'd be happy to drop those sections of the PR for now.

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
@MarcoFalke, do you have any opinions about this more stripped down PR?

**Comment by MarcoFalke** [comment]
Yeah, it might be better to use spans where possible instead of changing one bloaty code to another slightly better, but still bloaty code

**Comment by PastaPastaPasta** [comment]
> Yeah, it might be better to use spans where possible instead of changing one bloaty code to another slightly better, but still bloaty code

@MarcoFalke 
I agree, seems like there are a number of potential spanifications that would make sense, and maybe I can work on in the future. Do you think that is a good reason to not move forward with this PR? It seems to me that this PR doesn't have the costs we discussed in https://github.com/bitcoin/bitcoin/pull/23810, but does have the benefits

> +0 for using verbose casts for pointers, since we usually get those wrong (#23438 (comment), https://github.com/bitcoin/bitcoin/pull/23810/files#r771801088).



> will yet again need everyone with an existing patch, who does more significant work, to rebase.

Since this PR only conflicts with two others, (one of which seems quite dead) I think this cost has been minimized.

**Comment by MarcoFalke** [comment]
I don't think it makes sense to change the same LOC twice. See also https://github.com/bitcoin/bitcoin/pull/22167#issuecomment-960936147 where I suggested to do char->std::byte, but then decided to go char->Span.

There is more cost to a pull request than conflicts. Another cost is review and the general burden that it places on the project. A burden could be any of the following:

* Time spent on review
* Accidental introduction of bugs
* (Silent) merge conflicts, either in the branch or a backport branch. Those conflicts demand further developer and reviewer time or introduce bugs.

**Comment by jonatack** [comment]
I like that these named casts make smelly conversions easier to see and more ugly, to eventually encourage refactoring them away.  Given how many there are in the codebase though, it's easier to do it when the code is being touched for other things, either as a PR author or a reviewer making suggestions, and I've seen a few reinterpret casts added this way.

**Comment by jonatack** [comment]
I like that these named casts make smelly conversions easier to see, grep for, and more verbose/ugly, to eventually encourage refactoring them away.  Given how many there are in the codebase though, it's easier to do it when the code is being touched for other things, either as a PR author or a reviewer making suggestions, and I've seen a few reinterpret casts added this way. Doing it wholesale across the codebase is a hard sell, however, for the reasons mentioned above.

**Comment by martinus** [comment]
I had a look through a few of the casts, and I think quite a bit of them can simply be removed. E.g. all casts to `void*`, and many others as well. 
Also, I think it might be beneficial to change the hash API to accept `const void*`. Then a lot more reinterpret_casts could be removed.

**Comment by martinus** [comment]
> I think the hash api might be better off taking a span of `std::byte`

I just saw there are also helpers like `MakeByteSpan` and `AsBytes` which would make this convenient, I agree

**Comment by achow101** [comment]
Closing this as it has not had any activity in a while. If you are interested in continuing work on this, please leave a comment so that it can be reopened.

**Comment by PastaPastaPasta** [comment]
I've just rebased this PR. I'd love for this to move forward, but it seems that most maintainers here are against it due to the conflicts it'll cause with other open PRs (even though imo the conflicts will be quite easy for authors to resolve)

**Comment by martinus** [comment]
@PastaPastaPasta you could remove all the `reinterpret_cast<void*>` casts

**Pull request closed without merging**
