### PR TITLE
build: Clean remnants of QTBUG-34748 fix

### PR DESCRIPTION
**Pull request by hebasto**
Hope, this PR will make [transit](https://github.com/bitcoin/bitcoin/pull/21376) to Qt 5.12.10 neater.

A fix for [QTBUG-34748](https://bugreports.qt.io/browse/QTBUG-34748) was introduced in #5915 (v0.11.0, Qt 5.2.1).

[QTBUG-34748](https://bugreports.qt.io/browse/QTBUG-34748) was [fixed](https://github.com/qt/qtbase/commit/b19b0808940c8c54b102012be134a370b26e348e) in Qt 5.3.0.

The separated [`fix-xcb-include-order.patch`](https://github.com/theuni/bitcoin/blob/bb44d9e7546e6118cd91db5bbe471a3ce2ee7fcd/depends/patches/qt/fix-xcb-include-order.patch), provided by #5915, was dropped in #12971 while bumping Qt to 5.9.4 (5.9.6). But `libxcb.mk` remained unchanged.

This PR reverts #5915 for `libxcb.mk` as well.

### CODE REVIEW

**Comment by hebasto** [comment]
cc @fanquake

**Comment by fanquake** [comment]
This is already included in #21376?

**Comment by hebasto** [comment]
> This is already included in #21376?

Yes. In #21376 the change in `libxcb.mk` looks like it is motivated by Qt version bumping  to 5.12. But, actually, it is not related to Qt 5.12.

If this justification seems wrong, feel free to close this PR.

**Comment by practicalswift** [comment]
cr ACK 173ef8980d921c9c0e46257747ab1165965e3ced: patch looks correct

**Comment by fanquake** [comment]
ACK 173ef8980d921c9c0e46257747ab1165965e3ced

> Yes. In #21376 the change in libxcb.mk looks like it is motivated by Qt version bumping to 5.12. But, actually, it is not related to Qt 5.12.

I'm not sure that matters too much. However given you've split this out, and some additional background  information is useful, I'm just going to merge this, and then we can finish up in #21376.

**Pull request merged**
