### PR TITLE
LevelDB Fixes and Enhancements

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by mcelrath** [comment]
@jgarzik please advise since you didn't originate this request.

**Comment by jonasschnelli** [comment]
Would be nice to have a bench utility to compare this PR agains the leveldb version.

**Comment by jgarzik** [comment]
I intentionally avoided creating a pull request because we don't yet know if sqlite has adequate performance for our needs.

Based on preliminary @jmcorgan input, it sounds like sqlite is too slow.

Recommendation:  Close pull request, but request @jmcorgan paste his test results here for issue tracking purposes.

**Comment by jmcorgan** [comment]
My tests were entirely informal and subjective.  We'd actually have to define a benchmark that could be part of an A/B test in order for the results to be interpreted.

**Comment by jgarzik** [comment]
@jmcorgan Informal is still informative :)  "It took Y hours to reindex with sqlite"

**Comment by dcousens** [comment]
@LordOfTheCoin was this PR in working order such that the above could easily be tested?

**Comment by cryptomarc** [comment]
Why not use http://www.aerospike.com ? Its insanely fast and opens up options for the future, ie. multi-threads in multiple processes.

**Comment by LordOfTheCoin** [comment]
Tried on Win 10, Compiled and Ran, Didn't Thoroughly Test Though

**Comment by dcousens** [comment]
@jgarzik I'll see if I can provide that information soon.
Is there any specific metrics you'd prefer?

**Comment by jgarzik** [comment]
@dcousens The first metric is initial sync time, which is sometimes "approximated" with a reindex.  A/B testing for current master leveldb versus sqlite.

**Comment by sipa** [comment]
Also, running with -debug=bench will give a breakdown of time per activity.

**Comment by LordOfTheCoin** [comment]
BTW, AeroSpike doesn't have a c++ implementation

**Comment by cryptomarc** [comment]
I think the client library doesnt exist in C++, but should easily support it. 

Question is what our aim here is? Speed? Future in-ram processing ideas?

**Comment by jgarzik** [comment]
@LordOfTheCoin C++ works just fine with C libraries.

@cryptomarc speed

**Comment by cryptomarc** [comment]
To my understanding Aerospike pretty much kills in all the benchmark tests done vs other No-SQL db's. I will try to run a couple of tests myself and post them here.

**Comment by sipa** [comment]
Aerospike is AGPL...

**Comment by LordOfTheCoin** [comment]
Its' AGPL, compatable with GPL, but with MIT?

**Comment by sipa** [comment]
Using an AGPL library in Bitcoin Core would require Bitcoin Core itself to
be licensed under AGPL or compatible terms.

Even if we would want to do that, it would be nearly impossible to
accomplish. Every contributor in the past would need to give consent about
this, as they hold copyright over the code they wrote.

**Comment by LordOfTheCoin** [comment]
There are about ~ 6000 Contributors, so I get it....

**Comment by cryptomarc** [comment]
Its a shame, and something I missed out when looking at Aerospike. Shame because it seems to be much on par with some interesting functionality that we could utilize in the future for Bitcoin.

**Comment by mcelrath** [comment]
I really don't think this database should be or needs to be distributed with the core source (as leveldb currently is).  There are no licensing issues when linking against an external library.  This should be an external dependency, whose correctness can be verified using UTXO commitment hashes as I describe here: http://lists.linuxfoundation.org/pipermail/bitcoin-dev/2015-October/011638.html

**Comment by sipa** [comment]
Linking against a library is usually considered a derivative work, in
particular when the library's .h file are under the same license.

Including the source code of our database engine inside the source tree or
not is an artifact of using git subtrees. Even if we didn't, we would still
need to specify an exact version to prevent bugfixes that break consensus
by users who link against different versions. Using subtree or not is not
relevant in this discussion.

UTXO commitments do not fix this, as they need a different trust model
(miners not committing to incorrect data).

**Comment by mcelrath** [comment]
That's just not true regarding derivative works. Bitcoin links against e.g. boost and is not a derivative of boost.  Its header files are distributed separately.  It's easy to specify specific versions of external dependencies.

Verifying correctness of database operation is not a trust model change.  I'm thinking of it mostly in an advisory capacity...to notify node operators that something has gone horribly wrong.  Note that the UTXO commitment scheme I describe doesn't actually require those hashes to be committed to in a block.  Nodes can locally compute them simply to verify their own correctness of operation (and not communicate them at all). So one has potentially 3 sources of these hashes: computed during block ingest, computed by database query, and committed in the block.  Nodes that detect such an error could e.g. refuse to mine blocks (at the discretion of the operator -- obviously blindly trusting the hash in the block IS a trust model change).

**Comment by sipa** [comment]
@mcelrath In my understanding, Bitcoin binaries are a derivative work of the Boost headers, and if linked statically, a derivative work of the Boost C++ code too. If we were to make Bitcoin Core depend on an AGPL library, we could not distribute binaries without also providing the Bitcoin Core source code under AGPL-compatible licensing. If the AGPL library would be an optional dependency, things are potentially different - we could ship Bitcoin Core binaries that do not need the library for correct operation, but load them at runtime if available.

**Pull request closed without merging**
