### PR TITLE
configure: Make it possible to build only one of bitcoin-cli or bitcoin-tx

### PR DESCRIPTION
**Pull request by luke-jr**

### CODE REVIEW

**Comment by laanwj** [comment]
IMO this is too granular. No need to micromanage every tool. We had this discussion before, and decided on a rough 'utils' split for anything not GUI or bitcoind.

**Comment by luke-jr** [comment]
This keeps --with[out]-utils, but allows overriding it on a per-utility basis. At the very least, I will need this (either merged or patched in) for Gentoo, which builds each component from source individually.

**Comment by laanwj** [comment]
What will `--with[out]-utils` do after this change? I don't see any code to handle it, but my autotools-fu isn't that great.

This pull has a merge commit in it, you need to get rid of that before it can be merged.

**Comment by jgarzik** [comment]
Seems like NAK territory?  We already covered this on IRC.  You can do this at the make command line level for just about any project, with no need to complicate configure.

**Comment by luke-jr** [comment]
@laanwj --with[out]-utils continues to function as it did previously, basically controlling the default for the new options.

@jgarzik Is there a way to do `make install` in that scenario?

**Comment by laanwj** [comment]
@luke-jr Ah yes, I missed that default so I wondered how it worked.

@theuni mind taking a look here?

**Comment by laanwj** [comment]
There seems to be no interest in this, and earlier consensus on IRC was not to split out the flags this far, so I'm closing this.

I think it can make sense to do this when different utilities have different outside dependency libraries, in which case people may be forced to install dependencies for an utility they're not interested in. But not now.

**Comment by luke-jr** [comment]
> I think it can make sense to do this when different utilities have different outside dependency libraries, in which case people may be forced to install dependencies for an utility they're not interested in. But not now.

This is now true FWIW.

**Comment by laanwj** [comment]
Yes, you mean bitcoin-tx doesn't need libevent.

**Pull request closed without merging**
