### PR TITLE
build: Add bitcoin-tx.exe into Windows installer

### PR DESCRIPTION
**Pull request by ken2812221**
I think bitcoin-tx.exe should be packed into the Windows installer.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
utACK 5c5902acc515c8f46ad73222cd57a29c4c13b92c. Also, we are running the util tests in appveyor (on windows), so bitcoin-tx should have basic test coverage.

**Comment by laanwj** [comment]
I'm surprised that this has been the case for so long and we only notice now.

**Comment by hebasto** [comment]
utACK 5c5902acc515c8f46ad73222cd57a29c4c13b92c

**Comment by fanquake** [comment]
utACK 5c5902a

**Comment by jonasschnelli** [comment]
utACK 5c5902ac

**Comment by murrayn** [comment]
utACK https://github.com/bitcoin/bitcoin/commit/5c5902acc515c8f46ad73222cd57a29c4c13b92c

**Comment by MeshCollider** [comment]
Tested the 64 bit installer from the gitian build above

ACK https://github.com/bitcoin/bitcoin/pull/14698/commits/5c5902acc515c8f46ad73222cd57a29c4c13b92c

**Comment by gmaxwell** [comment]
Should this be tagged for backport?

**Comment by sipa** [comment]
@gmaxwell This seems more a new feature than a bugfix, though I think it's trivial enough we may want to backport it. Other opinions?

**Pull request merged**
