### PR TITLE
refactor: Add and use EnsureConnman in rpc code

### PR DESCRIPTION
**Pull request by maflcko**
This removes the 10 occurrences of `throw JSONRPCError(RPC_CLIENT_P2P_DISABLED, "Error: Peer-to-peer functionality missing or disabled");` and replaces them with `EnsureConnman`.

### CODE REVIEW

**Comment by practicalswift** [comment]
Concept ACK: neat cleanups!

**Review by jarolrod — COMMENTED** [review]
ACK fad37e6c380bf96fa430217d5e2f43322d4718f9

This is a nice simplification. Tested the error message with the patch below. Used a similar patch with `EnsurePeerman`. Tested that, with this refactor, functionality remains the same by applying a similar patch to the occurrences of `if(!node.connman)`.

``` diff
--- a/src/rpc/net.cpp
+++ b/src/rpc/net.cpp
@@ -41,7 +41,7 @@ const std::vector<std::string> CONNECTION_TYPE_DOC{
 
 CConnman& EnsureConnman(const NodeContext& node)
 {
-    if (!node.connman) {
+    if (true) {
         throw JSONRPCError(RPC_CLIENT_P2P_DISABLED, "Error: Peer-to-peer functionality missing or disabled");
     }
     return *node.connman;

```

**Review by theStack — COMMENTED** [review]
Concept ACK

There is one other instance in the `ping` RPC that can be tackled with `EnsurePeerman`:

```diff
diff --git a/src/rpc/net.cpp b/src/rpc/net.cpp
index 4d192ad95..fff7d3b60 100644
--- a/src/rpc/net.cpp
+++ b/src/rpc/net.cpp
@@ -92,12 +92,10 @@ static RPCHelpMan ping()
         [&](const RPCHelpMan& self, const JSONRPCRequest& request) -> UniValue
 {
     NodeContext& node = EnsureAnyNodeContext(request.context);
-    if (!node.peerman) {
-        throw JSONRPCError(RPC_CLIENT_P2P_DISABLED, "Error: Peer-to-peer functionality missing or disabled");
-    }
+    PeerManager& peerman = EnsurePeerman(node);

     // Request that each node send a ping during next message processing pass
-    node.peerman->SendPings();
+    peerman.SendPings();
     return NullUniValue;
 },
     };
```

Also, including `<any>` isn't needed in the new header `src/rpc/net.h`.

**Comment by MarcoFalke** [comment]
Thanks, done

**Review by theStack — APPROVED** [review]
ACK fafb68add5e16e8bd5b9428bcffcaee2639747cf

**Comment by jarolrod** [comment]
re-ACK fafb68add5e16e8bd5b9428bcffcaee2639747cf

**Review by ryanofsky — APPROVED** [review]
Code review ACK fafb68add5e16e8bd5b9428bcffcaee2639747cf

**Pull request merged**
