### PR TITLE
Double semicolon cleanup

### PR DESCRIPTION
**Pull request by ghost**
Assuming, and clarifying, the empty statements weren't intentional.

### CODE REVIEW

**Comment by paveljanik** [comment]
Can you please remove also the rest?

```
qt/bantablemodel.cpp:    return columns.length();;
qt/guiutil.cpp:        QString msg(QUrl::toPercentEncoding(info.message));;
qt/peertablemodel.cpp:    return columns.length();;
test/rpc_tests.cpp:    BOOST_CHECK_NO_THROW(CallRPC(string("setban 127.0.0.0 remove")));;
test/rpc_tests.cpp:    BOOST_CHECK_NO_THROW(CallRPC(string("setban 127.0.0.0/24 remove")));;
```

**Comment by 21E14** [comment]
PR updated accordingly. Why don't we spin off Qt!?

**Comment by MarcoFalke** [comment]
utACK a5a0831458d8290c1e7591cf32a529669b613d86

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/commit/a5a0831458d8290c1e7591cf32a529669b613d86

**Comment by fanquake** [comment]
ACK https://github.com/21E14/bitcoin/commit/a5a0831458d8290c1e7591cf32a529669b613d86

**Comment by jonasschnelli** [comment]
ACK a5a0831458d8290c1e7591cf32a529669b613d86

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/commit/a5a0831458d8290c1e7591cf32a529669b613d86

**Pull request merged**
