### PR TITLE
clientversion: Define only macros we’ll use

### PR DESCRIPTION
**Pull request by practicalswift**
Define only macros we'll use.

### CODE REVIEW

**Comment by kallewoof** [comment]
Is there even a point in having the define, rather than just putting it in the `#define BUILD_DESC` directly?

**Comment by practicalswift** [comment]
@kallewoof Good point! Now defining `BUILD_DESC` directly. Please re-review :-)

**Comment by ken2812221** [comment]
This seems not work.
Use `git archive` and `bitcoin-cli --version` to test
This PR:
`Bitcoin Core RPC client version vCLIENT_VERSION_MAJOR.CLIENT_VERSION_MINOR.CLIENT_VERSION_REVISION.CLIENT_VERSION_BUILD-g87af43b1f9f55877b0ec57ef0e0a3e0cdf809d8e`
master:
`Bitcoin Core RPC client version v0.16.99.0-g9d86aad287f07e20066138b9f909758ad7a2e098`

**Comment by Empact** [comment]
How about building the three off a common define?:

```C++
#define BUILD_DESC_WITHOUT_SUFFIX(maj, min, rev, build) \
    "v" DO_STRINGIZE(maj) "." DO_STRINGIZE(min) "." DO_STRINGIZE(rev) "." DO_STRINGIZE(build)
```

This would reduce duplication and make the suffix more visible in the code.

**Comment by practicalswift** [comment]
@Empact Now using a common define. Please review :-)

@ken2812221 Please re-review :-)

**Comment by Empact** [comment]
Just realized you can inline the arguments to BUILD_DESC_VERSION, so that the implementations are like `BUILD_DESC_VERSION "-" BUILD_SUFFIX` - would be much clearer IMO.

**Comment by practicalswift** [comment]
@Empact Updated. Please re-review :-)

**Comment by MarcoFalke** [comment]
Not sure if this is worth it. I doubt we have enough reviewers that are fluent enough in macros that can review this.

**Pull request closed without merging**
