### PR TITLE
Add Gitian key for droark

### PR DESCRIPTION
**Pull request by droark**
I've signed 0.18.0rc1 and 0.18.0rc2, and I intend to sign every release moving forward.

### CODE REVIEW

**Comment by fanquake** [comment]
[0.18.0rc1 sigs](https://github.com/bitcoin-core/gitian.sigs/pull/954), [0.18.0rc2 sigs](https://github.com/bitcoin-core/gitian.sigs/pull/974).

**Comment by laanwj** [comment]
confirming that this is the key used to sign

rc1:
```
gpg:                using RSA key 6D3170C1DC2C6FD0AEEBCA6743811D1A26623924
gpg: Can't check signature: No public key
droark: BAD SIGNATURE
```
rc2:
```
gpg:                using RSA key 6D3170C1DC2C6FD0AEEBCA6743811D1A26623924
gpg: Can't check signature: No public key
droark: BAD SIGNATURE
```

**Comment by laanwj** [comment]
@droark Is your key on the keyservers?
```
gpg --recv-key 6D3170C1DC2C6FD0AEEBCA6743811D1A26623924
gpg: keyserver receive failed: No data
```

**Comment by fanquake** [comment]
@laanwj weird, I have it here:
```
gpg --recv-key 6D3170C1DC2C6FD0AEEBCA6743811D1A26623924
gpg: key 43811D1A26623924: "Douglas Roark <joroark@vt.edu>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
```

**Comment by laanwj** [comment]
looks like a local problem, could reproduce @fanquake's step on another host

utACK 204c729457aa21e5fc6325a5af57f69b55a67c6a

**Pull request merged**
