### PR TITLE
Release notes for Miniscript support in P2WSH descriptors

### PR DESCRIPTION
**Pull request by darosior**
Changelog for #24148.

### CODE REVIEW

**Comment by darosior** [comment]
@Sjors @achow101 @w0xlt, can you think of something else worth mentioning or missing?

**Comment by Sjors** [comment]
ACK d751beb7ac1c26d9d892ef3d3f244090d46b1e00

**Review by w0xlt — APPROVED** [review]
ACK https://github.com/bitcoin/bitcoin/pull/25618/commits/d751beb7ac1c26d9d892ef3d3f244090d46b1e00

**Comment by achow101** [comment]
ACK d751beb7ac1c26d9d892ef3d3f244090d46b1e00

**Pull request merged**
