### PR TITLE
Update libsecp256k1

### PR DESCRIPTION
**Pull request by sipa**
This just updates the libsecp256k1 subtree to the latest master. It does not switch validation to it.

### CODE REVIEW

**Comment by fanquake** [comment]
utACK
```
bash-3.2$ contrib/devtools/git-subtree-check.sh src/secp256k1
src/secp256k1 in HEAD was last updated to upstream commit 2bfb82b10edf0f0b0e366a12f94c8b21a914159d (tree 7a74d5de4d518bc5165feeeb75edb0ac4e8c5bea)
src/secp256k1 in HEAD currently refers to tree 7a74d5de4d518bc5165feeeb75edb0ac4e8c5bea
GOOD
```

**Comment by gmaxwell** [comment]
ACK

**Comment by jtimon** [comment]
Concept ACK

**Comment by laanwj** [comment]
Concept ACK.

Should we keep this open until the 0.12 feature freeze, so that new changes to secp256k1 can be included up to then, or better to merge as soon as possible?

**Comment by jtimon** [comment]
I would say merge asap, that will make #6954 easier to review.

**Comment by jgarzik** [comment]
ACK - merge ASAP

**Comment by laanwj** [comment]
if you get "/home/user/bitcoin/src/key.cpp:204: undefined reference to `secp256k1_ecdsa_sign_recoverable'"  errors after updating to master including this pull you need to clean your git tree.

**Pull request merged**
