### PR TITLE
build: Fix `-Xclang -internal-isystem` option

### LINKED ISSUE #29174: Broken `--enable-suppress-external-warning` for Apple Clang 15 on `x86_64`
Apple Clang 15 does not support `-Xclang -internal-isystem` anymore. On both `x86_64` and `arm64` platforms, the following check: https://github.com/bitcoin/bitcoin/blob/65c05db660b2ca1d0076b0d8573a6760b3228068/configure.ac#L742-L744
 fails with `error: unknown argument: '-internal-isystem/usr/local/include'`.

It makes the `--enable-suppress-external-warnings` option not working for dependency packages installed by Homebrew and linked to `/usr/local`, which happens for all non-keg packages on `x86_64`. There is no such an effect on `arm64`.

For a related discussion refer to https://github.com/bitcoin/bitcoin/pull/29165#discussion_r1440273658.

### PR DESCRIPTION
**Pull request by hebasto**
This PR:
- addresses https://github.com/bitcoin/bitcoin/pull/29165#discussion_r1439433156
- fixes https://github.com/bitcoin/bitcoin/issues/29174

### CODE REVIEW

**Comment by hebasto** [comment]
https://github.com/bitcoin/bitcoin/actions/runs/7437962301/job/20236177232:
```
checking whether C++ preprocessor accepts -Xclang -internal-isystem -Xclang /usr/local/include/... yes
```

**Comment by hebasto** [comment]
> pull title should be "build: Fix -Xclang -internal-isystem option"? Otherwise lgtm

Done.

**Comment by fanquake** [comment]
> The same Xcode version is used for the release binaries.

Can probably drop this, or be more specific, because we don't use Xcode to build release binaries (only the SDK, which is versioned differently).

**Comment by hebasto** [comment]
> > The same Xcode version is used for the release binaries.
> 
> Can probably drop this, or be more specific, because we don't use Xcode to build release binaries (only the SDK, which is versioned differently).

Dropped.

**Review by fanquake — APPROVED** [review]
ACK d742be3d3f5d5063d7160f72422bce2fec953f38. The same as what was done in #27328.

> For example, see: https://github.com/llvm/llvm-project/commit/cbbe1d44546db52c71c9a2b18f85b87ae82df9e7

I guess this is meant to be an example of someone else using `-Xclang`? However this commit is from > 10 years ago, and isn't related to, or an explanation for the recent change in Clang behaviour.

**Comment by hebasto** [comment]
> I guess this is meant to be an example of someone else using `-Xclang`?

Right, just an example. I forgot about #27328.

**Pull request merged**
