### PR TITLE
[Doc] Fix typo

### PR DESCRIPTION
**Pull request by azuchi**
Fix typo `IDB` to `IBD`.

### CODE REVIEW

**Comment by randolf** [comment]
This is a good catch.  For better clarity, I suggest changing the line to include the acronym in parenthesis earlier on because this will make it clearer to users (assuming that IBD really is an acronym for Initial Block Download):

`An `initialblockdownload` (IBD) boolean has been added to the `getblockchaininfo` RPC to indicate whether the node is currently in IBD or not.`

**Review by randolf — CHANGES_REQUESTED** [review]
This is a good correction.  For better clarity, I suggest also changing the line to include the acronym in parenthesis earlier on because this will make it clearer to users (assuming that IBD really is an acronym for Initial Block Download):

`An `initialblockdownload` (IBD) boolean has been added to the `getblockchaininfo` RPC to indicate whether the node is currently in IBD or not.`

**Review by randolf — APPROVED** [review]

**Review by jonasschnelli — APPROVED** [review]
ACK ce3b313a452e1731099fa41ee10d20fad6ae8dff (please squash)

**Comment by MarcoFalke** [comment]
Please fix this upstream for now: https://github.com/bitcoin-core/bitcoin-devwiki/wiki/0.16.0-Release-notes/_history

**Pull request closed without merging**
