### PR TITLE
[qa]: remove root test directory for RPC tests

### PR DESCRIPTION
**Pull request by rodentrabies**
Fix for #8647. Back up each test's root directory and at the end if it is empty (or contains only *.bak) files, remove it too.

### CODE REVIEW

**Comment by fanquake** [comment]
Travis Output
```
wallet-hd.py:
...
Stopping nodes
Cleaning up
stderr:
 Traceback (most recent call last):
  File "/home/travis/build/bitcoin/bitcoin/build/../qa/rpc-tests/wallet-hd.py", line 87, in <module>
    WalletHDTest().main ()
  File "/home/travis/build/bitcoin/bitcoin/qa/rpc-tests/test_framework/test_framework.py", line 185, in main
    os.rmdir(self.options.root)
OSError: [Errno 39] Directory not empty: '/tmp/test02xnhitc'
Pass: False, Duration: 34 s

```

**Comment by yurizhykin** [comment]
Sorry, accidentally used non-recursive directory.

**Comment by MarcoFalke** [comment]
Please don't delete the dir when there are files left. (The bak file
should be properly removed in the corresponding test, which may be
wallet-dump.py)

**Comment by yurizhykin** [comment]
@MarcoFalke I didn't quite understand the problem with bak file, so decided it is that way for some purpose. It appears that the bak file name was appended to test root without '/' separator. Fixed in c62cc4ec759a8487373f158b3cbb888efcdd753a.

**Comment by MarcoFalke** [comment]
utACK c62cc4ec759a8487373f158b3cbb888efcdd753a

**Comment by MarcoFalke** [comment]
This will delete the dir when the user passed it in and it was empty in the beginning.

Though, overall I think this is better than the previous situation.

**Pull request merged**
