### PR TITLE
Removal of "free transaction" logic from codebase

### PR DESCRIPTION
**Pull request by Leviathn**
This is the first of a series of pull requests to remove all "free transaction" logic from the codebase

### CODE REVIEW

**Comment by paveljanik** [comment]
@Leviathn ? Do you think that `estimatepriority` was not called/referenced at all?

**Comment by Leviathn** [comment]
Thanks for the guidance - just getting into the swing of things..

**Comment by morcos** [comment]
@Leviathn I removed the functionality of estimate*priority in #7730.  I didn't think it was necessarily a good idea to remove the RPC call itself until it had been marked deprecated for a release.  I didn't know if there were external applications relying on those API calls at least returning something.

What do others think?

**Comment by sipa** [comment]
When did we mark it as deprecated?

**Comment by morcos** [comment]
@sipa last week.

(for 0.14)

**Comment by Leviathn** [comment]
Not trying to step on your toes @morcos - I know fees are where you've been focusing on lately : I just saw an opportunity to contribute by removing what I see (i think obviously so) as useless functionality in a fee-saturated Bitcoin.

**Comment by sipa** [comment]
I think most people agree it's useless at this point, but we normally don't
break RPC compatibility without deprecating it first.

**Comment by morcos** [comment]
@Leviathn I'm 100% in agreement that we should remove all the priority code.  I was going to suggest that as a topic for discussion in this weeks IRC development meeting.  Please join us.  I'm not sure if its a change that we'll get in for 0.14, but would be nice to agree we can move forward with it.

The RPC calls in particular though I thought we might leave around for backwards compatibility until we'd given users enough notice.

I just looked and there are a couple of cleanups that could be done now though if you are interested.  In tests, qt and wallet code there are calls to estimate*priority that are now useless.  They could be removed.  I'd be happy to review that PR.

**Comment by Leviathn** [comment]
Ok - After reviewing #7730 it appears your clean-up there is comprehensive, so i'll close this and reopen another PR for the Tests, QT, and Wallet Code removals. I'll be happy to join you this week re - the Dev meet. 

I appreciate the quality feedback

**Pull request closed without merging**
