### PR TITLE
appveyor: Write @PACKAGE_NAME@ to config

### PR DESCRIPTION
**Pull request by maflcko**
fix tests which are currently failing on appveyor after #15896

### CODE REVIEW

**Comment by hebasto** [comment]
Should be the next patch applied aswell?
```
diff --git a/build_msvc/bitcoin_config.h b/build_msvc/bitcoin_config.h
index 4ac27dae3..817bb57ce 100644
--- a/build_msvc/bitcoin_config.h
+++ b/build_msvc/bitcoin_config.h
@@ -14,7 +14,7 @@
 #define CLIENT_VERSION_MAJOR 1
 
 /* Minor version */
-#define CLIENT_VERSION_MINOR 17
+#define CLIENT_VERSION_MINOR 18
 
 /* Build revision */
 #define CLIENT_VERSION_REVISION 99
```

**Review by ryanofsky — APPROVED** [review]
utACK faebd8ca118f6fbf08c783faba796b5ee957ff00. Not following your own "Please provide clear motivation for your patch" advice maybe, but I gather the motivation is to fix tests which are currently failing on appveyor after #15896?

**Comment by Sjors** [comment]
utACK faebd8c if AppVeyor blesses it.

**Comment by MarcoFalke** [comment]
@hebasto That should be mentioned in the branch-off todo list. See for example #15607

**Comment by MarcoFalke** [comment]
Took @ryanofsky 's motivation and copy-pasted it into the first comment

**Comment by luke-jr** [comment]
Why isn't AppVeyor using standard build stuff? :/

**Pull request merged**
