### PR TITLE
rpc: Document an RPCResult for all calls; Enforce at compile time

### PR DESCRIPTION
**Pull request by maflcko**
This documents the RPC Result (type and description, if applicable) everywhere it was missing. The patch can be reviewed with the `git diff` option `-W`/`--function-context`.

Also, code won't compile without having an RPCResult documented.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Added a commit to fix the nit from https://github.com/bitcoin/bitcoin/pull/17809#discussion_r386299875

**Comment by practicalswift** [comment]
Concept ACK: compile-time enforcement is the best type of enforcement! :)

**Review by promag — COMMENTED** [review]
Tested ACK fac52253f81a4f0d04b25eb4b6c28d04b85ef10b, built and verified listunspent help output.

BTW, had to `#include <string>` in sync.h , on osx 10.14.6:
```
$ clang -v
Apple LLVM version 9.0.0 (clang-900.0.31)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
```

**Comment by MarcoFalke** [comment]
> BTW, had to #include <string> in sync.h , on osx 10.14.6:

I didn't modify `sync` at all?!

**Comment by promag** [comment]
I know, just saying that you could add a commit to fix that since this is ready for merge instead of a new PR. Unless you prefer a new PR? (clearly string.h is missing there)

**Comment by laanwj** [comment]
Lightly tested ACK fac52253f81a4f0d04b25eb4b6c28d04b85ef10b

**Pull request merged**
