### PR TITLE
Trivial: Fix typo

### PR DESCRIPTION
**Pull request by murtyjones**

### CODE REVIEW

**Review by dcousens — APPROVED** [review]

**Comment by gmaxwell** [comment]
ACK.

**Review by jonasschnelli — APPROVED** [review]
Trivial ACK

**Comment by fanquake** [comment]
ACK

**Comment by MarcoFalke** [comment]
ACK 12a721b

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/8762/commits/12a721b45e16124f48ea85f96079feec18e948ca

**Pull request merged**
