### PR TITLE
Slightly overhaul NSI pixmaps

### PR DESCRIPTION
**Pull request by jonasschnelli**
Slightly overhaul the NSI pixmaps.
As far as I can see the `share/pixmaps/bitcoin*.png|.xmp` files are unused (removed in this PR).

Gitian build will follow.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Gitian build:
https://bitcoin.jonasschnelli.ch/build/188

How it looks after this PR:
bildschirmfoto 2017-06-22 um 09 02 35
bildschirmfoto 2017-06-22 um 09 02 45

**Comment by MarcoFalke** [comment]
Looks like they are used in contrib.

utACK on the other change.

```sh
git grep xpm ./contrib/
contrib/debian/bitcoin-qt.install:share/pixmaps/bitcoin32.xpm usr/share/pixmaps
contrib/debian/bitcoin-qt.install:share/pixmaps/bitcoin16.xpm usr/share/pixmaps
contrib/rpm/bitcoin.spec:%{_bindir}/convert -resize 16x16 %{buildroot}%{_datadir}/pixmaps/bitcoin256.png %{buildroot}%{_datadir}/pixmaps/bitcoin16.xpm
contrib/rpm/bitcoin.spec:%{_bindir}/convert -resize 32x32 %{buildroot}%{_datadir}/pixmaps/bitcoin256.png %{buildroot}%{_datadir}/pixmaps/bitcoin32.xpm
contrib/rpm/bitcoin.spec:%{_bindir}/convert -resize 64x64 %{buildroot}%{_datadir}/pixmaps/bitcoin256.png %{buildroot}%{_datadir}/pixmaps/bitcoin64.xpm
contrib/rpm/bitcoin.spec:%{_bindir}/convert -resize 128x128 %{buildroot}%{_datadir}/pixmaps/bitcoin256.png %{buildroot}%{_datadir}/pixmaps/bitcoin128.xpm
contrib/rpm/bitcoin.spec:%{_bindir}/convert %{buildroot}%{_datadir}/pixmaps/bitcoin256.png %{buildroot}%{_datadir}/pixmaps/bitcoin256.xpm
contrib/rpm/bitcoin.spec:touch %{buildroot}%{_datadir}/pixmaps/*.xpm -r %{SOURCE100}
contrib/rpm/bitcoin.spec:%attr(0644,root,root) %{_datadir}/pixmaps/*.xpm

**Comment by jonasschnelli** [comment]
@MarcoFalke: yes, your right.

Restored the files (force push amend commit).

**Comment by MarcoFalke** [comment]
ACK 92fb8bd81fb5e71116f648e6cc149ad27357f2a7

**Comment by laanwj** [comment]
LGTM, utACK

**Pull request merged**
