### PR TITLE
Add explicit cast to base58 and bech32 string constants in order to silence GCC warning

### PR DESCRIPTION
**Pull request by DesWurstes**
May I also constexprize them in this Pull Request?

### CODE REVIEW

**Comment by ken2812221** [comment]
Could you elaborate more details? I don't understand what your purpose is.

**Comment by DesWurstes** [comment]
In standard C++, `const char*a="abc";` is illegal. `(const char *)` is required, and `const_cast<char*>` is the C++ way to do that.

**Comment by practicalswift** [comment]
@DesWurstes I'm not sure I follow. Can you post the GCC warning you're trying to get rid of?

**Comment by sipa** [comment]
Why is that illegal?

**Comment by DesWurstes** [comment]
Erroneous observation due to blind constexpr replacements. It was `char * k="d";` that was illegal.<sub><sub><sup><sup>forgive me.</sup></sup></sub></sub>

**Pull request closed without merging**
