### PR TITLE
Expand functional zmq transaction tests

### PR DESCRIPTION
**Pull request by instagibbs**
Tests written to better define what messages are sent when. Also did a bit of refactoring to make sure the exact notification channel ordering doesn't matter.

Confusions below aside, I believe having these more descriptive tests helps describe what behavior we expect from ZMQ notificaitons.

Remaining confusion:
1) Notification patterns seem to vary wildly with the inclusion of mempool transactions being reorg'ed. See difference between "Add zmq test for transaction pub during reorg" and "Have zmq reorg test cover mempool txns" commits for specifics.
2) Why does a reorg'ed transaction get announced 3 times? From what I understand it can get announced once for disconnected block, once for mempool entry. What's the third? It occurs a 4th time when included in a block(not added in test)

### CODE REVIEW

**Review by promag — COMMENTED** [review]
Concept ACK, notifier order still exists but from the client side we don't have to worry about order involving different messages.

With this change we no longer test receiving different messages in the same socket. This could be done in a small test.

**Comment by laanwj** [comment]
code review ACK 7356292e1d7a44da8a2bd31c02c58d550bf38009

**Comment by promag** [comment]
Code review ACK 7356292e1d7a44da8a2bd31c02c58d550bf38009.

> It occurs a 4th time when included in a block(not added in test yet)

@instagibbs will you update this branch?

**Comment by instagibbs** [comment]
@promag not really no, heh. Removed the "yet" in OP.

**Pull request merged**
