### PR TITLE
wallet: Refactor: Update NULL -> nullptr

### PR DESCRIPTION
**Pull request by mxaddict**
I noticed most CPP code already use nullptr

#16146 replacement PR

### CODE REVIEW

**Comment by Empact** [comment]
See also #13802 and #15112, which automatically enforces against such cases.

**Comment by laanwj** [comment]
ACK after this can be automatically avoided (e.g. by a linter) from here on, I dont' like an infinite stream of these PRs.

**Comment by mxaddict** [comment]
Also moved some changes from #16146 over to https://github.com/bitcoin-core/univalue/pull/18

**Comment by practicalswift** [comment]
utACK 89bd27259bb898066a2e1616f94d3df0fe0d0b8f

+1 for guarding against introduction of `NULL` via linting or a compiler warning (#15112 ready for merge?)

**Review by PastaPastaPasta — APPROVED** [review]
ACK

**Review by fanquake — APPROVED** [review]
utACK https://github.com/bitcoin/bitcoin/pull/16147/commits/89bd27259bb898066a2e1616f94d3df0fe0d0b8f

>  after this can be automatically avoided (e.g. by a linter) from here on, I dont' like an infinite stream of these PRs.

👍

**Comment by promag** [comment]
This is already done in #15112, IMO should be closed - either way ACK 89bd272.

**Comment by MarcoFalke** [comment]
Thank you for your contribution. While this stylistic change makes sense on its own, it comes at a cost and risk for the project as a whole. The weak motivation for the change does not justify the burden that it places on the project. A burden could be any of the following:

* Time spent on review
* Accidental introduction of bugs
* (Silent) merge conflicts, either in the branch or a backport branch. Those conflicts demand further developer and reviewer time or introduce bugs.

For more information about refactoring changes and stylistic cleanup, see
* https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#refactoring
* https://github.com/bitcoin/bitcoin/blob/master/.github/PULL_REQUEST_TEMPLATE.md
* https://github.com/bitcoin/bitcoin/issues/15465

Generally, if the style is not mentioned nor enforced by the developer notes, we leave it up to the original author to pick whatever fits them best personally and then leave it that way until the line is touched for other reasons.

Let me know if you have any questions.

**Pull request closed without merging**
