### PR TITLE
script, doc: guix tidy-ups

### PR DESCRIPTION
**Pull request by jonatack**

### CODE REVIEW

**Comment by fanquake** [comment]
A bunch of these are being done in #22511.

**Comment by jonatack** [comment]
Some aren't.

**Comment by fanquake** [comment]
Probably easiest to point out the few additional typos in that PR. Then we can just backport 2 commits.

**Review by hebasto — APPROVED** [review]
ACK dced8b5266d013da2ddc0a2d907dcf864e914bc1

**Comment by hebasto** [comment]
> Probably easiest to point out the few additional typos in that PR. Then we can just backport 2 commits.

Agree. Also https://github.com/bitcoin/bitcoin/pull/22511#issuecomment-884803754

**Comment by jonatack** [comment]
Most of these suggestions aren't in the current version of #22511 and that PR is about something else.  But ok :man_shrugging:

**Comment by fanquake** [comment]
There's enough overlap to combine them into one, and some of the changes here were already pointed out in a comment in that PR. Some of the changes here are also not correct. i.e the sig files are called `noncodesigned.SHA256SUMS`, so updating the error messages to call them `non-codesigned.SHA256SUMS` is not right.

**Pull request closed without merging**
