### PR TITLE
Fix some locks

### LINKED ISSUE #8599: Possible Deadlock
Just updated a node to current master (+https://github.com/bitcoin/bitcoin/pull/7685), the node ran successfully for a couple of weeks, shortly after updating to current master, I ran in a deadlock assertion:
I think the possible deadlock is not related to the PR which I'm running on top.

```
2016-08-26 07:50:29 POTENTIAL DEADLOCK DETECTED
2016-08-26 07:50:29 Previous lock order was:
2016-08-26 07:50:29  pnode->cs_vRecvMsg  net.cpp:1885 (TRY)
2016-08-26 07:50:29  cs_main  main.cpp:4726
2016-08-26 07:50:29  (1) pfrom->cs_filter  main.cpp:4784
2016-08-26 07:50:29  (2) cs_vSend  net.cpp:2683
2016-08-26 07:50:29 Current lock order is:
2016-08-26 07:50:29  (2) pnode->cs_vSend  net.cpp:1904 (TRY)
2016-08-26 07:50:29  cs_main  main.cpp:6343 (TRY)
2016-08-26 07:50:29  pto->cs_inventory  main.cpp:6563
2016-08-26 07:50:29  (1) pto->cs_filter  main.cpp:6586
```

### PR DESCRIPTION
**Pull request by sipa**
This makes sure that cs_filter is never held while taking cs_main or CNode::cs_vSend.

This should fix #8599.

### CODE REVIEW

**Comment by luke-jr** [comment]
utACK

**Comment by sipa** [comment]
I believe this bug exists in 0.13.0.

**Comment by MarcoFalke** [comment]
utACK 144ed76ea0b38b7c21b224501964f8a2c65c4bb6

**Comment by sipa** [comment]
Feel like testing whether this fixes your issue #8599, @jonasschnelli ?

**Comment by jonasschnelli** [comment]
I just ran again into #8599...
Added this PR on top of current master and re-started the node... will report.

**Comment by jonasschnelli** [comment]
My node having the issue #8599 did run without deadlock assertion-exit the last 7 days.
Testes ACK https://github.com/bitcoin/bitcoin/pull/8606/commits/144ed76ea0b38b7c21b224501964f8a2c65c4bb6

**Pull request merged**
