### PR TITLE
Fix spelling of Qt

### PR DESCRIPTION
**Pull request by diegoviola**
QT is considered a typo, Qt is the proper term.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
IIrc you'd need to update the translations via Transifex, not going to work if you commit here.

**Comment by jonasschnelli** [comment]
@MarcoFalke is right. The `*.ts` changes are useless. They need to be made at https://www.transifex.com/bitcoin.

Also please use https://github.com/theuni/bitcoin for trivial non-code changes to avoid trivial PR overflow in the main repository.

**Comment by diegoviola** [comment]
Sorry, restored the `*.ts` files to the previous state.

**Comment by jonasschnelli** [comment]
@diegoviola: mind closing the PR and reopening on https://github.com/theuni/bitcoin?
We should really try to reduce such non-benefit PRs

**Comment by diegoviola** [comment]
@jonasschnelli OK.

**Pull request merged**
