### PR TITLE
Update hmac_sha256.cpp

### PR DESCRIPTION
**Pull request by smatthewenglish**
eminently reasonable temporal update

### CODE REVIEW

**Comment by sipa** [comment]
Did anything substantially change to that file this year?

**Comment by MarcoFalke** [comment]
No need to update every single file on it's own: #7205

**Comment by smenglish** [comment]
hmm, sorry about that. I don't have much experience contributing to open source projects, so I was just trying it out.

**Comment by MarcoFalke** [comment]
No worries, you can read through https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md to see how things work.

**Comment by MarcoFalke** [comment]
Also, I think you can close this PR.

**Comment by smenglish** [comment]
thank you.

**Pull request closed without merging**
