### PR TITLE
Trivial: Remove double semicolon from wallet.cpp and misc.cpp

### PR DESCRIPTION
**Pull request by Gnappuraz**

### CODE REVIEW

**Comment by fanquake** [comment]
utACK 3946a79

**Review by ken2812221 — APPROVED** [review]
utACK 3946a79c38b73a1e29af7c00b6f1fc56c382a7fb

**Comment by Empact** [comment]
utACK 3946a79

**Comment by promag** [comment]
utACK 3946a79.

**Comment by ken2812221** [comment]
Mind also remove the double semicolon here?
https://github.com/bitcoin/bitcoin/blob/master/src/rpc/misc.cpp#L81

**Comment by fanquake** [comment]
ACK removing the `;;` mentioned above. It seems to be the only other erroneous use of `;;` I can find in the codebase (other uses are in for loops).

**Comment by Gnappuraz** [comment]
Removed also the other semicolon as asked by @ken2812221

**Comment by Empact** [comment]
re-utACK 8560b94 please squash

**Comment by promag** [comment]
And update PR title.

**Comment by ken2812221** [comment]
utACK 1336d9cb3b5441904bb214dc7259035aacdcd108

**Comment by fanquake** [comment]
utACK 1336d9c

**Comment by sipa** [comment]
utACK 1336d9cb3b5441904bb214dc7259035aacdcd108

**Comment by Empact** [comment]
re-utACK 1336d9c

**Pull request merged**
