### PR TITLE
Wallet: reduce excess logic InMempool()

### PR DESCRIPTION
**Pull request by kewde**
removed the excess logic, return directly instead of using if-statement.

### CODE REVIEW

**Comment by paveljanik** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/10164/commits/3491476b6f486a85bef09f1a0bd4d39e1af9d0b1

**Comment by NicolasDorier** [comment]
utACK 3491476

**Comment by jnewbery** [comment]
utACK 3491476b6f486a85bef09f1a0bd4d39e1af9d0b1

**Review by gmaxwell — APPROVED** [review]
utACK

**Comment by MarcoFalke** [comment]
utACK 3491476b6f486a85bef09f1a0bd4d39e1af9d0b1

**Comment by practicalswift** [comment]
utACK 3491476b6f486a85bef09f1a0bd4d39e1af9d0b1

Nice find @kewde! Keep 'em coming!

**Pull request merged**
