### PR TITLE
mempool: Fix unintended unsigned integer wraparound in CTxMemPool::UpdateAncestorsOf(bool add, …) when add is false

### PR DESCRIPTION
**Pull request by practicalswift**
Fix unintended unsigned integer wraparound in `CTxMemPool::UpdateAncestorsOf(bool add, …)` when `add` is `false`.

```
txmempool.cpp:219:44: runtime error: unsigned integer overflow: 18446744073709551615 * 155 cannot be represented in type 'unsigned long' !=
```

### CODE REVIEW

**Comment by sdaftuar** [comment]
Why did you decide to close this PR?  After some digging I believe this change correctly fixes a bug, though I think the problem is not in the unsigned integer overflow (which is well-defined), but in casting the resulting unsigned integer to a signed type (which I have recently learned is not defined behavior, when the unsigned value would be negative).

So I think this change, which casts to int64_t first before multiplying by -1, is exactly correct.

**Comment by MarcoFalke** [comment]
I haven't reviewed the claim that @sdaftuar makes, but I checked that on my machine the bitcoind compiled with clang doesn't change at all, and for gcc the objdump is the same.

**Comment by sdaftuar** [comment]
utACK

@ryanofsky pointed me to this:  http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3690.pdf, from section 4.7.3 

> If the destination type is signed, the value is unchanged if it can be represented in the destination type (and bit-field width); otherwise, the value is implementation-defined.

**Comment by practicalswift** [comment]
@sdaftuar @ryanofsky You might want to take a look at #11551 (`Fix unsigned integer wrap-around in GetBlockProofEquivalentTime`) and #11535 :-)

**Pull request closed without merging**
