### PR TITLE
Suggested wallet code cleanups from #14711

### PR DESCRIPTION
**Pull request by ryanofsky**
This implements suggested changes from #14711 review comments that didn't make make it in before merging.

There are no changes in behavior in this PR, just documentation updates, simplifications, and variable renames.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
ACK aebafd0edf81b546d4b7db9e7f53e9eef2c0073e. Thanks for the responses to my questions in the other pull!

**Comment by promag** [comment]
ACK aebafd0, agreed on renames and updated comments.

**Comment by fanquake** [comment]
utACK aebafd0

**Comment by jnewbery** [comment]
utACK aebafd0edf81b546d4b7db9e7f53e9eef2c0073e. Hooray for quick merges :tada:

**Pull request merged**
