### PR TITLE
test: Bump timeouts to accomodate really slow disks

### PR DESCRIPTION
**Pull request by maflcko**
Needed these patches locally for some arm machines with slow storage

### CODE REVIEW

**Comment by Empact** [comment]
Random alternative notion: what would you think of adding a command-line option that increases the `wait_until` timeouts by a factor? That would allow the longer timeouts to be opt-in.

**Comment by MarcoFalke** [comment]
I wouldn't mind that, but I'd prefer to do this as a follow-up

**Comment by practicalswift** [comment]
ACK fa6df0de538c15a6d393830af373ac9af6f48125

**Review by fanquake — APPROVED** [review]
ACK fa6df0de538c15a6d393830af373ac9af6f48125

**Comment by fanquake** [comment]
> Random alternative notion: what would you think of adding a command-line option that increases the wait_until timeouts by a factor? That would allow the longer timeouts to be opt-in.

Opened #18266 for this.

**Pull request merged**
