### PR TITLE
[21.x] Qt: Handle exceptions instead of crash

### PR DESCRIPTION
**Pull request by luke-jr**
This is a backport of https://github.com/bitcoin-core/gui/pull/260 to 21.x / C++11.

Since 21.x is now Maintenance End for Core, and the fix herein is mostly UX-related in practice, it's unclear if it makes sense to merge this PR, but even if not, I would appreciate any review since I intend to include it in Knots LTS.

For the sake of easier review, the C++11 backport is an additional unsquashed commit.

### CODE REVIEW

**Comment by fanquake** [comment]
@hebasto any thoughts here?

**Review by hebasto — COMMENTED** [review]
ACK 6a794f4737eef9a13a3963f87bd2f37916d11f32, I've verified that code has been backported correctly.

Do we really need to introduce `#include <QStringBuilder>` into the `21.x` branch? Maybe combine these changes with a02c970eb001b456d74ddc30750fe8b55348ddac?

**Comment by luke-jr** [comment]
>Do we really need to introduce #include <QStringBuilder> into the 21.x branch? Maybe combine these changes with a02c970?

An optimisation isn't a bugfix, but I guess there's no harm in using trivially slower code for normally-unused string building.

Backported just that commit from https://github.com/bitcoin-core/gui/pull/313

**Review by hebasto — APPROVED** [review]
re-ACK 87028acd2f785b0f172b7a934acce0a2082ebca0

**Comment by luke-jr** [comment]
Had to replace `[[maybe_unused]]`s with `(void)var;` for C++11 compatibility

**Review by hebasto — APPROVED** [review]
re-ACK 3609f2d1b0d6eb64da974f3e1ce3b8f26cd747dc

FWIW, while the `maybe_unused` attribute indeed is a C++17 feature, I was able to successfully compile f735ab016b96a273b364edb6c7940c54275c36ae with both gcc 8.4.0 and clang 8.0.0 on Ubuntu 18.04.6 LTS.

**Comment by fanquake** [comment]
> Since 21.x is now Maintenance End for Core, and the fix herein is mostly UX-related in practice, it's unclear if it makes sense to merge this PR

21.x is now also [EOL](https://bitcoincore.org/en/lifecycle/). I think we can close this rather than merging a gui backport into an EOL branch.

**Pull request closed without merging**
