### PR TITLE
Merge from trivial

### PR DESCRIPTION
**Pull request by theuni**
Nothing controversial, I think. A few unneeded class/struct re-arrangements slipped in, but no reason to grab the pitchforks.

### CODE REVIEW

**Comment by laanwj** [comment]
ACK

**Comment by paveljanik** [comment]
ACK (The change like https://github.com/theuni/bitcoin/commit/3b00e7c231648cfe0c36c5f9f0c44953146c1a5b can be replicated across the whole tree)

**Comment by fanquake** [comment]
ACK

**Comment by sipa** [comment]
ACK

**Comment by gavinandresen** [comment]
ACK

**Comment by Diapolo** [comment]
ACK

**Pull request merged**
