### PR TITLE
 GUI: Move QRImageWidget to its own file-pair

### PR DESCRIPTION
**Pull request by luke-jr**
For at least QR-code based pairing of mobile wallets with nodes, it will be desirable to render QR codes even without wallet support.

Therefore, this prepares by moving the QRImageWidget out of a wallet-specific file into its own `qrencoder` file-pair.

### CODE REVIEW

**Comment by laanwj** [comment]
concept ACK, though I'd prefer naming the pair `qrimagewidget.(cpp|h)` so that the files are named the same as the class

**Comment by jonasschnelli** [comment]
Concept ACK
@luke-jr can you elaborate a bit on the possible non-BIP21 QRCode usages?

**Comment by luke-jr** [comment]
The end goal is something like #15428

**Comment by laanwj** [comment]
utACK fc929842c20ac81869a33edce765e389a46e6c0c

**Comment by jonasschnelli** [comment]
Thanks @luke-jr. I wasn't aware of #15428.
utACK fc929842c20ac81869a33edce765e389a46e6c0c

**Pull request merged**
