### PR TITLE
Keccak hf: Fix mining centralization

### PR DESCRIPTION
**Pull request by stale2000**
As per Luke-jr's helpful suggestions, Bitcoin Core needs a way to defends itself against the chance of a hostile hardfork.

This PR would solves mining centralization by allowing GPU miners to be the leading-edge again, by changing the proof of work algorithm.

### CODE REVIEW

**Comment by wachub** [comment]
Well any change of this seriousness would require a hard fork in itself.

**Comment by MarcoFalke** [comment]
I guess you'd need a BIP and universal support to do so.

Quoting @sipa 

>  In my opinion, the correct way to do a hard fork is to first see if there is universal support for it, and when so, schedule it for 1 year in the future or so. No vote needed; everyone knows they have to upgrade by that time. There can still be a miner vote after that 1 year to be sure miners _also_ agree to the change, and know we'll end up with a secure chain after the fork, but that's just belt and suspenders.

**Comment by laanwj** [comment]
I'm not sure how much sense it makes to do an emergency hard-fork to protect against a hard-fork. A change of PoW is something that would make most sense for the side of the hard-fork that forks off - as they're changing consensus behavior already.

No matter what, definitely needs a BIP and discussion on the mailing list. This would need a change to many other software: at least every miner and pool implementation, and thus is not an issue that can be handled here.

**Comment by jl2012** [comment]
This one should be closed. No BIP, no discussion, no consensus

**Comment by laanwj** [comment]
@jl2012 Agreed. Changing the PoW is a nuclear option when miners misbehave. There's no point in keeping this open, it gives people the wrong idea that this is being considered for integration at the moment.

**Comment by keo** [comment]
"when miners misbehave" - really?

Bitcoin's protocol IS consensus. The chain with the most work done IS the valid chain, as per Satoshi's whitepaper.


There's no such thing as majority of miners misbehaving, only in the context of centralized planning -- which Bitcoin, by definition, is poised to disrupt.

**Comment by gmaxwell** [comment]
@keo The Bitcoin whitepaper says no such thing; nor has _any_ version of Bitcoin, including the pre-release alpha, nor- as far as I am aware- any other cryptocurrency _ever_ worked in the way you describe. Rather, the first _valid_ chain, conforming to the rules of the Bitcoin system with the most work is the preferred one.

Bitcoin nodes absolutely ignore chains which violate the rules of the system. A miner producing an invalid block is, from the perspective of the Bitcoin network, simply not mining at all. This operation is an essential component of the incentive balance which keeps the system working, limiting the potential abuse of high hashpower attacks to reorganization or exclusion of transactions and not arbitrary rule violation, creation of inflation, etc.

**Comment by seweso** [comment]
@gmaxwell You are technically correct, and raise important & valid points, as you always do. 

But in practice the longest chain **is** Bitcoin. By virtue of Bitcoin being the most popular and valuable cryptocurrency on this planet, and because everyone will always regard it as such. 

Could miners create a longer chain which is not "Bitcoin": Yes. Will they? No, not for any significant amount of time. 

Can Bitcoin split exactly through the middle and create two Bitcoin's? Well that is so unlikely that it is not really worth exploring. One will always be called Bitcoin, and the other Bitcoin Something. 

Like the great Eminem once said:  I am whatever you say I am. 

The big (on topic) question is: Can a less valuable cryptocurrency still be more secure? And if it is more secure, wouldn't it become more valuable anyway? 

Some realities might simply be unescapable. Like the need for politics.

**Comment by laanwj** [comment]
> "when miners misbehave" - really?

Yes, let's (for the sake of discussion, worst case) say an organiation steals or otherwise acquires 99% of all double-sha256 mining power, and decides to censor all transactions, or otherwise wreak havoc on the chain.
People running node software could then decide that that is not the bitcoin they want, and switch to software with a different mining algorithm whose distribution of computation hardware is more balanced.
As said it is a nuclear option, and obviously everyone would prefer that that is not necessary, but it is not impossible. You can't force people to partake in a bitcoin that was 'ruined' for them.

**Comment by seweso** [comment]
@laanwj Seems Andreas M Antonopoulos answered that exact question: https://youtu.be/mTOqvWfB0Dw?t=41m47s

**Pull request closed without merging**
