### PR TITLE
p2p: TryLowWorkHeadersSync follow-ups

### PR DESCRIPTION
**Pull request by dergoegge**
See https://github.com/bitcoin/bitcoin/pull/26355#discussion_r1003561481 and https://github.com/bitcoin/bitcoin/pull/26355#discussion_r1004554187

### CODE REVIEW

**Review by mzumsande — COMMENTED** [review]
utACK e891aabf5a4992a65b9c5ae8606f8dd08515b310

**Comment by dergoegge** [comment]
> Maybe also address https://github.com/bitcoin/bitcoin/pull/26355#discussion_r1004554187 ?

Added a commit for that comment.

**Review by hernanmarino — APPROVED** [review]
ACK 784b02319128988038d4bd82f05736be22f14ee9

**Review by brunoerg — APPROVED** [review]
crACK 784b02319128988038d4bd82f05736be22f14ee9

**Review by mzumsande — COMMENTED** [review]
ACK 784b02319128988038d4bd82f05736be22f14ee9

I checked that `IsContinuationOfLowWorkHeadersSync` calls `ProcessNextHeaders`, which sets the state to `FINAL` if unsuccessful, resulting in `IsContinuationOfLowWorkHeadersSync` doing the cleanup of `m_headers_sync` and `m_headers_presync_stats`, so it is correct to remove the same cleanup in `TryLowWorkHeadersSync`.

**Comment by fanquake** [comment]
This has been merged.

**Pull request closed without merging**
