### PR TITLE
Update libsecp256k1 subtree to latest master

### PR DESCRIPTION
**Pull request by fanquake**
Updates the libsecp256k1 subtree to https://github.com/bitcoin-core/secp256k1/commit/f473c959f08edcb73669142f872d2189950bc54a. This includes a number of CMake related changes, including one that prevents CMake from segfaulting when we were configuring the subtree. A number of these changes have come from the review/discussion in https://github.com/hebasto/bitcoin/pull/192:

* https://github.com/bitcoin-core/secp256k1/pull/1529
* https://github.com/bitcoin-core/secp256k1/pull/1532
* https://github.com/bitcoin-core/secp256k1/pull/1535
* https://github.com/bitcoin-core/secp256k1/pull/1543
* https://github.com/bitcoin-core/secp256k1/pull/1545
* https://github.com/bitcoin-core/secp256k1/pull/1546

Also includes:

* https://github.com/bitcoin-core/secp256k1/pull/1488
* https://github.com/bitcoin-core/secp256k1/pull/1517
* https://github.com/bitcoin-core/secp256k1/pull/1533
* https://github.com/bitcoin-core/secp256k1/pull/1548
* https://github.com/bitcoin-core/secp256k1/pull/1550

### CODE REVIEW

**Comment by fanquake** [comment]
cc @real-or-random. Depending on whether https://github.com/bitcoin-core/secp256k1/pull/1535 goes in, we could also pull that, but just a cleanup.

**Review by hebasto — APPROVED** [review]
ACK 4c67e14cacef1903800b4cf4e32a12922d36025f, I've got a zero diff with my local branch, which reproduces the subtree update.

**Comment by fanquake** [comment]
> Depending on whether https://github.com/bitcoin-core/secp256k1/pull/1535 goes in, we could also pull that, but just a cleanup.

Incorporated.

**Review by sedited — APPROVED** [review]
ACK cc58e958f341d2759fbabe5c9d8cc557e17d587f

**Review by real-or-random — COMMENTED** [review]
Concept ACK -- this is a particularly harmless update as all changes are in the tests or in the build system or in comments

**Review by hebasto — APPROVED** [review]
re-ACK cc58e958f341d2759fbabe5c9d8cc557e17d587f.

**Review by real-or-random — APPROVED** [review]
utACK cc58e958f341d2759fbabe5c9d8cc557e17d587f

**Comment by achow101** [comment]
ACK cc58e958f341d2759fbabe5c9d8cc557e17d587f

Verified that there is no diff between the subtree and secp master.

**Comment by hebasto** [comment]
There is nothing to port to the CMake staging branch. Deleting the "Needs CMake port" label.

**Pull request merged**
