### PR TITLE
Some minor testing cleanups

### PR DESCRIPTION
**Pull request by morcos**
- first commit just roughly orders all of the RPC tests for running time and puts in comments so new tests can be added at approximately the right place.  i'm not sure its worth doing this very often.

- second commit removes setting of `relaypriority=0` from the rpc tests.  it obviously wasn't necessary if they were passing after the `-limitfreerelay` change to default to 0.

- third commit removes the obsolete file run-bitcoind-for-test.sh, but someone should check if I did this correctly, since now that I've removed it from .gitignore, everyones repos will complain that they have an extra file sitting around.  i wasn't sure how to clean that up?

let me know if only some of these commits are wanted and i get rid of the unwanted ones.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
utACK. I think you can also remove `.bitcoin` from the gitignore file.

**Comment by laanwj** [comment]
Another minor idea would be to remove explicit `-server` from the `bitcoind` command lines. That will catch a problem with the option (e.g. as in #9010) next time.

**Comment by MarcoFalke** [comment]
My guess would be that the gui binary can no longer be used for running the tests after removal of `-server`?

**Comment by MarcoFalke** [comment]
> third commit removes the obsolete file run-bitcoind-for-test.sh, but someone should check if I did this correctly, since now that I've removed it from .gitignore, everyones repos will complain that they have an extra file sitting around. i wasn't sure how to clean that up?

Everyone who cares about a "clean" work dir can delete the file by themself. It will still be generated every time you switch back to a old enough commit, so one could argue to leave the `.gitignore` patch out of this pull and submit it some time later, but I don't think this is worth it.

**Comment by laanwj** [comment]
> My guess would be that the gui binary can no longer be used for running the tests after removal of -server?

Hm good point. So that's why it's being passed? okay

**Comment by laanwj** [comment]
> since now that I've removed it from .gitignore, everyones repos will complain that they have an extra file sitting around. i wasn't sure how to clean that up?

I don't think see that as a problem. At least it will make it obvious that there's a redundant file around and that they can delete it. Unlike when you keep it in gitignore.

utACK 30b620c

**Comment by laanwj** [comment]
If you end get a `config.status: error: cannot find input file: `qa/pull-tester/run-bitcoind-for-test.sh.in` message in configure after pulling this, re-run autogen.sh

**Pull request merged**
