### PR TITLE
[trivial] sync univalue subtree

### LINKED ISSUE #6778: Build: circular dependency for libunivalue
To get this fixed, we first need a change in upstream univalue. See https://github.com/jgarzik/univalue/pull/13

Assuming that's accepted, next time we sync up with univalue, we'll need this change:
https://github.com/theuni/bitcoin/commit/c2bfdddf6ccdecd78fc09c262bab247cf9b29165

That should take care of the problem.

### PR DESCRIPTION
**Pull request by maflcko**
This syncs  jgarzik/univalue@5839ac3
- fixes gitignore issue https://github.com/bitcoin/bitcoin/pull/6770#issuecomment-146073263
- fixes #6778 

Reviewers should call `./contrib/devtools/git-subtree-check.sh src/univalue`

### CODE REVIEW

**Comment by theuni** [comment]
utACK

**Comment by fanquake** [comment]
utACK

**Comment by paveljanik** [comment]
ACK

**Comment by jamesob** [comment]
Tested ACK

**Pull request merged**
