### PR TITLE
Don't use zero as null pointer constant. Use nullptr (C++11).

### PR DESCRIPTION
**Pull request by practicalswift**
Don't use zero as null pointer constant.

From the developer notes:

> `nullptr` is preferred over `NULL` or `(void*)0`.

From the C++ Core Guidelines:

> **ES.47: Use `nullptr` rather than `0` or `NULL`**
> Reason Readability. Minimize surprises: `nullptr` cannot be confused with an `int`. `nullptr` also has a well-specified (very restrictive) type, and thus works in more scenarios where type deduction might do the wrong thing on `NULL` or `0`.

Found by compiling the project with `-Wzero-as-null-pointer-constant` and fixing where appropriate (skipping false positives).

### CODE REVIEW

**Comment by promag** [comment]
Concept ACK.

**Comment by fanquake** [comment]
If this is going to be done, shouldn't `-Wzero-as-null-pointer-constant` or a similar sort of lint script be added to the build system to try and stop it's usage re-occurring? Otherwise this seems like it could end up similar to `-Wshadow`.

**Comment by practicalswift** [comment]
@fanquake Yes that would be the best way to make sure we don't regress! Unfortunately `-Wzero-as-null-pointer-constant` generates some false positives in our code and some true positives in our dependencies.

**Comment by MarcoFalke** [comment]
> Unfortunately -Wzero-as-null-pointer-constant generates some false positives in our code and some true positives in our dependencies.

In which case I suggest to do the same as with `-Wshadow`: Don't enforce it and don't change existing code. So I tend to Concept NACK here.

**Comment by practicalswift** [comment]
@MarcoFalke Oh, but in contrast to shadowing I think the probably of regressions is much lower – hopefully making this a one time "switch to C++11" change. New code is unlikely to use `0` instead of the proper pointer literal `nullptr`, no?

I'd assume the instances changed here are from the pre-C++11 era.

**Comment by MarcoFalke** [comment]
Fine, `nullptr` is type safe, so at least it is an improvement and also doesn't hurt. There shouldn't be any issues given that this compiles, right?

**Comment by practicalswift** [comment]
@MarcoFalke Correct! Type safety is our friend.

This change is safe:
* Changing from `0` (or `NULL`) to `nullptr` where the zero is used as a null pointer constant is always safe.
* Changing from `0` (or `NULL`) to `nullptr` where the zero is **NOT** used as a null pointer constant will result in a compiler error.

So yes, if it compiles it is safe :-)

**Comment by kallewoof** [comment]
Weak concept NAK, but I'm okay with it if others are (I understand it's safe if it compiles).

Too many files changed (100 lines over 58 files) for a change that isn't really a fix (the reason stated in C++ guidelines is 'readability', which is rather weak for a 58 file change IMO). I feel this is one of those things that can be fixed gradually over time as people update the transgressing code.

**Comment by practicalswift** [comment]
Closing this PR due to lack of consensus ACK :-)

**Pull request closed without merging**
