### PR TITLE
[Doc] Update Doxygen configuration file

### PR DESCRIPTION
**Pull request by fanquake**
Now that @laanwj's [documentation server](https://dev.visucore.com/bitcoin/doxygen/) seems to be running Doxygen 1.8.11, I've updated the Doxyfile from a newer version.

This was done using 'doxygen -u /doc/Doxyfile'

All previous configuration options should have remained as is.

Any new options are set to defaults. However I've set two accordingly:

```
DOCSET_BUNDLE_ID       = org.bitcoin.Bitcoin-Core
DOCSET_PUBLISHER_ID    = org.bitcoin.Bitcoin-Core
```

### CODE REVIEW

**Comment by laanwj** [comment]
You're leaving out the most interesting part: how does this change the output? :)

**Comment by fanquake** [comment]
Screenshots comparing the current doc-server with what I generated.
Before:
before
After:
after
Before:
before-2
After:
after-2
Before:
before-3
After:
after-3
Before:
before-4
After:
after-4

**Comment by laanwj** [comment]
Thanks. I don't think I'm seeing it though. What are the main differences/improvements? Or is the point that it stays the same?

**Comment by laanwj** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/8890/commits/f2e939bdbceef1ee90d59fab9ab99b944b44bce1

**Comment by paveljanik** [comment]
preprocessed (comment changes ignored, whitespace changes removed) diff:
```
--- orig	2016-10-08 21:46:20.000000000 +0200
+++ new	2016-10-08 21:46:27.000000000 +0200
+ALLOW_UNICODE_NAMES    = NO
+TCL_SUBST              =
+MARKDOWN_SUPPORT       = YES
+TOC_INCLUDE_HEADINGS   = 0
+AUTOLINK_SUPPORT       = YES
+GROUP_NESTED_COMPOUNDS = NO
+INLINE_SIMPLE_STRUCTS  = NO
-SYMBOL_CACHE_SIZE      = 0
+LOOKUP_CACHE_SIZE      = 0
+EXTRACT_PACKAGE        = NO
+HIDE_COMPOUND_REFERENCE= NO
+SHOW_GROUPED_MEMB_INC  = NO
-SHOW_DIRECTORIES       = NO
+CITE_BIB_FILES         =
+WARN_AS_ERROR          = NO
-EXCLUDE                = src/leveldb src/json src/test /src/qt/test
+EXCLUDE                = src/leveldb \
+                         src/json \
+                         src/test \
+                         src/qt/test
-EXCLUDE_SYMBOLS        = boost google
+EXCLUDE_SYMBOLS        = boost \
+                         google
+USE_MDFILE_AS_MAINPAGE =
+SOURCE_TOOLTIPS        = YES
+HTML_EXTRA_STYLESHEET  =
-HTML_ALIGN_MEMBERS     = YES
+HTML_INDEX_NUM_ENTRIES = 100
-DOCSET_BUNDLE_ID       = org.doxygen.Project
-DOCSET_PUBLISHER_ID    = org.doxygen.Publisher
+DOCSET_BUNDLE_ID       = org.bitcoin.Bitcoin-Core
+DOCSET_PUBLISHER_ID    = org.bitcoin.Bitcoin-Core
-ENUM_VALUES_PER_LINE   = 4
-USE_INLINE_TREES       = NO
+ENUM_VALUES_PER_LINE   = 4
+MATHJAX_FORMAT         = HTML-CSS
+MATHJAX_EXTENSIONS     =
+MATHJAX_CODEFILE       =
+EXTERNAL_SEARCH        = NO
+SEARCHENGINE_URL       =
+SEARCHDATA_FILE        = searchdata.xml
+EXTERNAL_SEARCH_ID     =
+EXTRA_SEARCH_MAPPINGS  =
+LATEX_EXTRA_STYLESHEET =
+LATEX_EXTRA_FILES      =
+LATEX_BIB_STYLE        = plain
+LATEX_TIMESTAMP        = NO
+RTF_SOURCE_CODE        = NO
+MAN_SUBDIR             =
-XML_SCHEMA             = 
-XML_DTD                = 
+GENERATE_DOCBOOK       = NO
+DOCBOOK_OUTPUT         = docbook
+DOCBOOK_PROGRAMLISTING = NO
+EXTERNAL_PAGES         = YES
+DIA_PATH               =
+UML_LIMIT_NUM_FIELDS   = 10
+INTERACTIVE_SVG        = NO
+DIAFILE_DIRS           =
+PLANTUML_JAR_PATH      =
+PLANTUML_INCLUDE_PATH  =
```

What effect does this change has and is it worth it at all?

**Comment by laanwj** [comment]
Well the advantage would be that it is easier to use new features of doxygen as the options are mentioned in the config already just in cast.

**Pull request merged**
