### PR TITLE
Declare single-argument (non-converting) constructors "explicit"

### PR DESCRIPTION
**Pull request by practicalswift**
Declare single-argument (non-converting) constructors `explicit`.

In order to avoid unintended implicit conversions.

For a more thorough discussion, see ["C.46: By default, declare single-argument constructors explicit"](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c46-by-default-declare-single-argument-constructors-explicit) in the C++ Core Guidelines (Stroustrup & Sutter).

### CODE REVIEW

**Comment by practicalswift** [comment]
Rebased! Feel free to review :-)

**Comment by fanquake** [comment]
Rebooted the failing test.

**Comment by practicalswift** [comment]
Thanks!

**Comment by MarcoFalke** [comment]
utACK 3bdbbce

**Comment by practicalswift** [comment]
Rebased!

**Comment by laanwj** [comment]
utACK  https://github.com/bitcoin/bitcoin/pull/10969/commits/64fb0ac016c7fd01c60c39af60f6431bac57f9ee, this is a good precaution to avoid accidental "automatic conversions".

**Pull request merged**
