### PR TITLE
wallet: Set DatabaseStatus::SUCCESS in MakeSQLiteDatabase

### PR DESCRIPTION
**Pull request by maflcko**
This is a refactor to set the status to `SUCCESS` (like it is done in `MakeBerkeleyDatabase`, too). It also happens to fix a false positive valgrind warning (tested with bionic-gcc and focal-clang):

```
 node1 stderr ==28149== Conditional jump or move depends on uninitialised value(s)
==28149==    at 0x464471: LoadWallets(interfaces::Chain&) (load.cpp:105)
==28149==    by 0x44BFBA: interfaces::(anonymous namespace)::WalletClientImpl::load() (wallet.cpp:510)
==28149==    by 0x1640F9: AppInitMain(util::Ref const&, NodeContext&, interfaces::BlockAndHeaderTipInfo*) (init.cpp:1815)
==28149==    by 0x144F3F: AppInit (bitcoind.cpp:142)
==28149==    by 0x144F3F: main (bitcoind.cpp:172)
==28149== 
{
   <insert_a_suppression_name_here>
   Memcheck:Cond
   fun:_Z11LoadWalletsRN10interfaces5ChainE
   fun:_ZN10interfaces12_GLOBAL__N_116WalletClientImpl4loadEv
   fun:_Z11AppInitMainRKN4util3RefER11NodeContextPN10interfaces21BlockAndHeaderTipInfoE
   fun:AppInit
   fun:main
} 

TEST                                             | STATUS    | DURATION

wallet_hd.py --descriptors                       | ✖ Failed  | 69 s
```

### CODE REVIEW

**Comment by achow101** [comment]
ACK faf5fa74136b0117f02c5aa525bfff86654786ea

**Comment by practicalswift** [comment]
Concept ACK

@MarcoFalke I'm trying to correlate the line numbers in the `valgrind` output with the code: do you know which revision you were running? `valgrind` false positives are quite rare so it would be interesting to analyze this case :)

**Review by mjdietzx — APPROVED** [review]
ack faf5fa74136b0117f02c5aa525bfff86654786ea

**Comment by MarcoFalke** [comment]
@practicalswift It is normal master, line 105 is:

```cpp
            if (!database && status == DatabaseStatus::FAILED_NOT_FOUND) {
```

status should only be read when the db doesn't exists, in which case status is also set.

**Pull request merged**
