### PR TITLE
netaddress: Update CNetAddr for ORCHIDv2

### PR DESCRIPTION
**Pull request by dongcarl**
```
The original ORCHID prefix was deprecated as of 2014-03, the new
ORCHIDv2 prefix was allocated by RFC7343 as of 2014-07. We did not
consider the original ORCHID prefix routable, and I don't see any reason
to consider the new one to be either.
```

Would like to know if people think this kind of thing is even worth keeping the codebase updated for. Perhaps it'd be nice to write a devtool to pull the csv from [here](https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml) and generate the code.

### CODE REVIEW

**Comment by laanwj** [comment]
utACK

**Comment by sipa** [comment]
Maybe we should instead just have a single IsUnroutable function that tests for all these cases simultaneously. Perhaps it just has a const vector of prefixes to check against.

**Review by ryanofsky — APPROVED** [review]
utACK 00a50a09eaf9149e44c207290ec093fc86f4b096

**Comment by Empact** [comment]
> Maybe we should instead just have a single IsUnroutable function that tests for all these cases simultaneously. Perhaps it just has a const vector of prefixes to check against.

Here's a take on: https://github.com/bitcoin/bitcoin/compare/master...Empact:is-routable?expand=1

**Comment by dongcarl** [comment]
Rebased, I think I'm going to limit this change to just ORCHIDv2 for now.

**Comment by ryanofsky** [comment]
utACK 8be3f306338e27b3fa3ad3bfb75f822d038909a5. Only change since last review is rebasing after #15718 merge.

re: https://github.com/bitcoin/bitcoin/pull/15689#issuecomment-492767893

> I think I'm going to limit this change to just ORCHIDv2 for now.

I was initially confused by this comment because this PR was always limited to ORCHIDv2. But this is just a response to an earlier comment about potentially expanding the PR: https://github.com/bitcoin/bitcoin/pull/15689#issuecomment-481787809

**Comment by laanwj** [comment]
> Maybe we should instead just have a single IsUnroutable  function that tests for all these cases simultaneously. Perhaps it just  has a const vector of prefixes to check against.

Good idea but can be done separately.

**Pull request merged**
