### PR TITLE
Rename -usewallet to -rpcwallet

### PR DESCRIPTION
**Pull request by morcos**

### CODE REVIEW

**Comment by jonasschnelli** [comment]
ACK 2264236da05fadd9d7d3c103882df8ebecc01b6b.
Tagged for 0.15.

**Comment by sipa** [comment]
utACK 2264236da05fadd9d7d3c103882df8ebecc01b6b.

**Comment by laanwj** [comment]
Makes sense, utACK

**Comment by promag** [comment]
utACK 2264236.

**Comment by theuni** [comment]
utACK 2264236da05fadd9d7d3c103882df8ebecc01b6b

**Pull request merged**
