### PR TITLE
net: remove more CConnman globals

### PR DESCRIPTION
**Pull request by theuni**
This continues some of the great work that @benma has been doing.

More work towards a CConnman with no globals, so that we can test instances against themselves.

### CODE REVIEW

**Comment by theuni** [comment]
Grr, serves me right for building without Qt. Will fix.

**Comment by theuni** [comment]
@jonasschnelli Any suggestion where to stick this? The qt build fails because the global accessor has been removed. I'd hate to add the global back just for qt.

Is it possible to add a QSettings value from gArgs without it ending up stored in the config file?

**Comment by jonasschnelli** [comment]
@theuni: I don't know whats the simples change. You could pass it into a GUI constant holder singleton (or pseudo global). Could be held in `guiutil.cpp/h`. Or just pass it around (to `bitcoingui.cpp`, etc., but I guess that will lead to a lot of code)

**Comment by benma** [comment]
This seems to be the only option that changes operations on the fly. We could just not do that (`setRestartRequired(true)`).

Otherwise, a clean option might be to register a callback in qt, called when non-restart settings are changed. Could hook up the `dataChanged` signal to a slot somewhere closer in qt to where the callback can be passed.

**Comment by jonasschnelli** [comment]
Concept ACK

**Comment by MarcoFalke** [comment]
Picked up in "net: remove more CConnman globals (theuni) #14856"

**Pull request closed without merging**
