### PR TITLE
[Trivial,Doc] Add missing "blocktime" description to listtransactions help, fix formatting.

### PR DESCRIPTION
**Pull request by paveljanik**
blocktime field described, two small formatting fixes (spaces moved).

### CODE REVIEW

**Comment by MarcoFalke** [comment]
utACK but still, we should finally get rid of this hard coded formatting.

**Comment by paveljanik** [comment]
Yes. There are more problems I left there - types are not aligned etc.

**Comment by MarcoFalke** [comment]
Yes, but let's do this after Dec 1 to prevent conflicting with features waiting to get in.

**Comment by paveljanik** [comment]
I do not plan to do it at all 8)

**Comment by laanwj** [comment]
Let's cut down on the number of space-massaging commits. I understand it's well-meant, but there are plenty of real issues to solve, at some point this is just commit noise.

**Comment by laanwj** [comment]
Oh I missed that this actually adds help for a field. Sorry.

**Pull request merged**
