### PR TITLE
Remove undefined FetchCoins method declaration

### PR DESCRIPTION
**Pull request by ryanofsky**

### CODE REVIEW

**Comment by morcos** [comment]
utACK . but shouldn't be marked trivial.  "trivial" is only for PR's that do not make code changes, not for simple code changes.

**Comment by ryanofsky** [comment]
Thanks. And I thought trivial just meant trivial!

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/9307/commits/fe41f5836552517da3d5cff2a970d6d0a6a8f06c

**Comment by MarcoFalke** [comment]
Concept ACK fe41f58

**Review by dcousens — APPROVED** [review]

**Comment by sipa** [comment]
Obvious ACK fe41f5836552517da3d5cff2a970d6d0a6a8f06c

**Pull request merged**
