### PR TITLE
Avoid "Unknown command" messages when receiving getaddr on outbound c…

### PR DESCRIPTION
**Pull request by rebroad**
…onnections.

Replaces #6344 and addresses concerns raised (i.e. now logs this exceptional event).

### CODE REVIEW

**Comment by sipa** [comment]
utACK

Tiny nit: can you use a less wide commit title? See http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html for example.

**Comment by laanwj** [comment]
utACK

**Comment by MarcoFalke** [comment]
utACK  d84ea1a

**Comment by kirkalx** [comment]
utACK.
Was looking at this code recently @rebroad and as I recall there were a few other similar situations there if you are looking for some more cleanups. Otherwise I'll put it on my TODO list :)

e.g.
````C++
    else if (strCommand == NetMsgType::HEADERS && !fImporting && !fReindex) // Ignore headers received while importing
````

**Comment by rebroad** [comment]
@sipa commit reworded

**Comment by MarcoFalke** [comment]
Could be tagged with "Needs backport"

**Comment by MarcoFalke** [comment]
Backported as part of #7938. Removing label 'Needs backport'.

**Pull request merged**
