### PR TITLE
Addition of ImmatureCreditCached to MarkDirty()

### PR DESCRIPTION
**Pull request by SCDeveloper**

### CODE REVIEW

**Comment by SCDeveloper** [comment]
Why is this not added here? Yet ImmatureWatchCreditCached is? Mistake or is there a reason for it not to be missing?

**Comment by jonasschnelli** [comment]
@SCDeveloper: can you elaborate what this change is trying to fix?

**Comment by SCDeveloper** [comment]
I am asking if it is missing in the first place.

**Comment by SCDeveloper** [comment]
Can anyone elaborate why it isn't in MakeDirty()????

**Comment by laanwj** [comment]
Looks like fImmatureCreditCached is never cleared except when the transaction is initialized. I don't think that is correct, unless it can never change.

**Comment by SCDeveloper** [comment]
I would of thought it would be best to have it in MarkDirty(), I have it currently within my code I am due to release shortly (Silk(SLK) & DarkSilk(DSLK)) and have no issues. I just don't understand why Bitcoin doesn't have it there?

**Comment by morcos** [comment]
utACK.

I certainly don't think it hurts to put it in MarkDirty and it makes more logical sense.
I don't think it'll actually change behavior though since GetImmatureCredit returns 0 instead of accessing the cache if this test fails:
`if (IsCoinBase() && GetBlocksToMaturity() > 0 && IsInMainChain())` 
and I can't see as how the amount of the immature credit could change otherwise.

**Comment by SCDeveloper** [comment]
I think it is just safer and more logical to have to covered than to not.

**Comment by sipa** [comment]
The only reason why an immature balance cached value can get invalidated is when the longest chain length decreases, which is an exceedingly rare and hard thing in Bitcoin mainnet (it requires a massive reorg crossing a retarget, with large time difference).

However, agree, for consistency and obviousness of correctness, utACK.

**Comment by SCDeveloper** [comment]
If people wouldnt mind I would like to recommit this under my public identity.

**Comment by spencerlievens** [comment]
Im forking the code now to recommit @sipa

**Comment by spencerlievens** [comment]
@sipa https://github.com/bitcoin/bitcoin/pull/8717

**Comment by SCDeveloper** [comment]
Please see link above

**Pull request closed without merging**
