### PR TITLE
test: Remove fragile assert_memory_usage_stable

### PR DESCRIPTION
**Pull request by maflcko**
This test fails on arm64 and a fuzz tests seems inappropriate for the functional test suite anyway, so remove it.

Example failures:

* https://travis-ci.org/bitcoin/bitcoin/jobs/611497963#L14517
* https://travis-ci.org/MarcoFalke/bitcoin-core/jobs/611029104#L3876

### CODE REVIEW

**Comment by practicalswift** [comment]
ACK fadeb41fcce084c95fe29a9cb85a5df3c7df3cf1 -- diff looks good and Travis is happy

Thanks for working on this

**Comment by laanwj** [comment]
ACK, maybe remove the definition of `assert_memory_usage_stable` in `test_node.py` as well as this is the only use.

**Comment by jamesob** [comment]
Concept ACK. RIP.

**Comment by MarcoFalke** [comment]
I wasn't sure if @jamesob was using it for some projects, but I interpret the reply as "no", so going to remove the `assert_memory_usage_stable` as well.

**Comment by jamesob** [comment]
FWIW I think this is a totally appropriate assertion for a functional test, since it's the highest-level suite of tests we have, and ensuring sane memory use is a feature of the system, but if we can't do it reliably across platform then we should either not do it on unreliable platforms or remove it entirely. My preference would be for the former, but if other people don't want to maintain this then I won't complain.

**Comment by laanwj** [comment]
In theory I agree, in practice a modern OS is so complex with so much going on in the background, that deterministically testing memory use seems to be impossible. It's the same as for timing tests. Sure, this can be done in a controlled environment, but not Travis and definitely not with parallelism of many.

**Comment by MarcoFalke** [comment]
I think the check itself is useful, but the limitations of the functional test framework make it almost useless in practice. The current status of this tests is: Running for twelve months, not a single reproducible failure.

I think this can be implemented as a fuzz test, making it more powerful, useful and easier to debug in case of failure.

**Review by jamesob — APPROVED** [review]
ACK https://github.com/bitcoin/bitcoin/pull/17469/commits/fac942ca57dce6cfa5655a3ac8664d6a051bc01f

**Pull request merged**
