### PR TITLE
Update build-osx.md

### PR DESCRIPTION
**Pull request by atErik**
Adding instructions to use MacPorts pkg-mngr in macOS. Adding instructions to turn-off anti-privacy data-collection activities of Homebrew pkg-mngr.

### CODE REVIEW

**Comment by hebasto** [comment]
@atErik 

Thank you for your contribution.

> Adding instructions to turn-off anti-privacy data-collection activities of Homebrew pkg-mngr.

Concept ~0 about that as it looks out of this repo scope. Our docs should not duplicate 3rd-party software docs.

**Review by jarolrod — COMMENTED** [review]
Thank you for your contribution!

I am NACK on this, our build docs are meant to provide guidance on building. They aren't meant to list every piece of information or iterate on all the possible ways that packages can be installed. The current instructions are easily adaptable to someone using macports as a package manager; so we don't have to duplicate information for that here.

**Comment by MarcoFalke** [comment]
Closing for now due to controversy

**Comment by atErik** [comment]
sorry to respond in late.

MacPorts pkg's name, and homebrew pkg's name are not same,
it takes time to find it.
So i'm requesting to add macports pkg name lines, etc.

@hebasto , then we need to add the link to the Homebrew project that instructs to do this data-collection activities.

**Comment by hebasto** [comment]
@atErik 
> @hebasto , then we need to add the link to the Homebrew project that instructs on how to turn-off this data-collection activities : https://docs.brew.sh/Analytics

Disagree. Ultimately, it could end with data-collection activities notes for OSes which are used to run Bitcoin Core.

> By not-including MacPorts info, devs in this prj have decided to discourage more use/adoption of MacPorts, and supporting homebrew only.

We care about maintaining our build system with very restricted resources. Even supporting the only package manager for macOS is a decent maintenance burden. Also Homebrew is preinstalled on [macOS images](https://github.com/cirruslabs/macos-image-templates) being used in our. CI workflow.

**Pull request closed without merging**
