### PR TITLE
[doc] build: Mention curl

### PR DESCRIPTION
**Pull request by maflcko**
closes #8478

### CODE REVIEW

**Comment by btcdrak** [comment]
utACK fae6bb8

**Comment by fanquake** [comment]
utACK fae6bb8

**Comment by jonasschnelli** [comment]
ACK https://github.com/bitcoin/bitcoin/commit/fae6bb85cf71056aa2541d9bc5cce26946a56945

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/8624/commits/fae6bb85cf71056aa2541d9bc5cce26946a56945

**Pull request merged**
