### PR TITLE
refactor: Replace m_params with chainman.GetParams()

### PR DESCRIPTION
**Pull request by aureleoules**
Fixes a TODO introduced in #24595.
Removes `m_params` from `CChainState` class and replaces it with `m_chainman.GetParams()`.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Why the close?

**Comment by aureleoules** [comment]
@MarcoFalke I was asked by @adamjonas to close this during coredev.

**Comment by MarcoFalke** [comment]
It is fixing a TODO, so if that is no longer applicable, the TODO should be removed

**Comment by adamjonas** [comment]
@MarcoFalke the request to close was based on lack of review and, therefore, the implied lack of support. If you'd be willing to review, @aureleoules can reopen.

**Comment by MarcoFalke** [comment]
sure

**Comment by aureleoules** [comment]
Note that I could have reduced the code diff by renaming `params` to `m_params` but since `params` is not a class member anymore I think its more confusing.

**Review by maflcko — COMMENTED** [review]
review ACK 5d3f98d27879cd6d84b8590e947336e8d09613ed 🌎

<details><summary>Show signature</summary>

Signature:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

review ACK 5d3f98d27879cd6d84b8590e947336e8d09613ed 🌎
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEE+rVPoUahrI9sLGYTzit1aX5ppUgFAlwqrYAACgkQzit1aX5p
pUjJ8Qv/ct7XpfKidLyXHj8qvtiMkjeM7lH4rtiwWVOi23PmFTl3UXN+CJZwuXlt
P7onWWziczOZIJzJVVwFKgbOegIfG2QNWlVpSWsgQRYXYdCi8wRyqmsChxKUNdQ/
+Yl2ny0CMpoEORl1rD8/wFdvBhpKbkVDl/dbCKLmz1KUxLfFDWPfcZ2VdyCrtoKr
+jXmBUtYVGciQaD/MK638lK/AgBEy1GzbBnnBZKg8oKi729FsEzFY9C7mGFT7OMc
RMn2hRKMdl9Vjz5ffBVp7DXC5tHTG6RJMZAIilI6xdw77BX5qFK5+HqGsOh/27sx
sn6mA0kP+tqPxV4/lD6PgtoYpbmQN9afxVJ8zFLCOM/TU4gIbQzlApQ1iM4/x+jp
m5E3lE0OAmWgns8YQ1ui2VkbcQhPU+0OfzoZC/3VPH5fGF5L2fW0aFsdgy2jT4Ph
pIFZjGbXvI8m/WEok1Rps4ZEKcIqkFjK0q3l29gJILPHZNtagEf4s4zqWc7czmtd
DiVFo5K1
=Udt+
-----END PGP SIGNATURE-----
```


</details>

**Comment by MarcoFalke** [comment]
In the future it might be best not to add refactoring TODOs?

**Pull request merged**
