### PR TITLE
Build System: Prevent warning about "maybe uninitialized variable" nStart in init.cpp

### PR DESCRIPTION
**Pull request by ReneNyffenegger**
The compiler apparently is unable to detect that `nStart` is initialized and issues a warning because `-Wmaybe-uniniatiialized` is enalbed.

The `#pragma` ... and `#pragma ... pop` prevent the warning for the line in question.

### CODE REVIEW

**Comment by fanquake** [comment]
Duplicate of #10714.

**Comment by TheBlueMatt** [comment]
Prefer #10714 - GCC is technically correct here, its a race to hit fShutdown before the print, no reason to silence it, we should fix our bug.

**Comment by ReneNyffenegger** [comment]
This PR can be closed as [#10714](https://github.com/bitcoin/bitcoin/pull/10714) has solved the problem this PR tried to address.

**Comment by jtimon** [comment]
It doesn't look like #10714 solved the warning? don't we just need to initialize nStart to 0 or something?

Also, @ReneNyffenegger you can close your own PRs yourself if you want.

**Comment by ReneNyffenegger** [comment]
I didn't know I could close my pull requests. Doing it now.

**Pull request closed without merging**
