### PR TITLE
[refactor] Remove using namespace <xxx> from rpc/ & script/ sources

### PR DESCRIPTION
**Pull request by kallewoof**
This is a sub-set of #9235, including only the `rpc` and `script` dirs.

Same-binaries check (2017-03-08):
```
$ ../bitcoin-maintainer-tools/build-for-compare.py 6996e066b538f03b8aa1f617dbb959b57ff6e727 8cbfc4e47216cbf9e3e758604e23951f40d76cf9 --executables "src/bitcoind,src/bitcoin-cli,src/bitcoin-tx"
[...]
make[1]: Leaving directory '/tmp/repo/src'
>>> [do_build] Copying object files...
>>> [do_build] Performing basic analysis pass...
>>> [do_build] Use these commands to compare results:
>>> [do_build] $ sha256sum /tmp/compare/*.stripped
>>> [do_build] $ git diff -W --word-diff /tmp/compare/6996e066b538f03b8aa1f617dbb959b57ff6e727 /tmp/compare/8cbfc4e47216cbf9e3e758604e23951f40d76cf9
$ sha256sum /tmp/compare/*.stripped
1bfe4311525db52b9c5d5c2b0b9ff6f8e3f3cfda0dcb1e5cd83b08b767a4a902  /tmp/compare/bitcoin-cli.6996e066b538f03b8aa1f617dbb959b57ff6e727.stripped
1bfe4311525db52b9c5d5c2b0b9ff6f8e3f3cfda0dcb1e5cd83b08b767a4a902  /tmp/compare/bitcoin-cli.8cbfc4e47216cbf9e3e758604e23951f40d76cf9.stripped
fb0f6796776dc39e422910572a216cbad87f607cbb4920bd12d2c483cc51e231  /tmp/compare/bitcoind.6996e066b538f03b8aa1f617dbb959b57ff6e727.stripped
fb0f6796776dc39e422910572a216cbad87f607cbb4920bd12d2c483cc51e231  /tmp/compare/bitcoind.8cbfc4e47216cbf9e3e758604e23951f40d76cf9.stripped
fe4107fcc49ba17cdfbb0edc357373ea37d833d5691af7b2367758e8b3e1d45c  /tmp/compare/bitcoin-tx.6996e066b538f03b8aa1f617dbb959b57ff6e727.stripped
fe4107fcc49ba17cdfbb0edc357373ea37d833d5691af7b2367758e8b3e1d45c  /tmp/compare/bitcoin-tx.8cbfc4e47216cbf9e3e758604e23951f40d76cf9.stripped
$ git diff -W --word-diff /tmp/compare/6996e066b538f03b8aa1f617dbb959b57ff6e727 /tmp/compare/8cbfc4e47216cbf9e3e758604e23951f40d76cf9
$ 
```

The affected files and namespaces:
```
rpc/blockchain.cpp:       std
rpc/client.cpp:           std
rpc/mining.cpp:           std
rpc/misc.cpp:             std
rpc/net.cpp:              std
rpc/protocol.cpp:         std
rpc/rawtransaction.cpp:   std
rpc/server.cpp:           RPCServer [unused], std
script/interpreter.cpp:   std
script/ismine.cpp:        std
script/script.cpp:        std
script/sign.cpp:          std
script/standard.cpp:      std
```

### CODE REVIEW

**Comment by kallewoof** [comment]
@MarcoFalke OK.

**Comment by fanquake** [comment]
Feature freeze is here. Please rebase this.

**Comment by kallewoof** [comment]
@fanquake Rebased & redid binary comparison (ff58b1c vs 1eb9d53).

**Comment by jtimon** [comment]
utACK 1eb9d53

**Review by dcousens — APPROVED** [review]

**Comment by MarcoFalke** [comment]
utACK 1eb9d53

**Comment by sipa** [comment]
utACK

**Comment by laanwj** [comment]
Needs another rebase, sorry.

**Comment by kallewoof** [comment]
@laanwj Rebased & redid binary comparison (6996e066b538f03b8aa1f617dbb959b57ff6e727 vs 8cbfc4e47216cbf9e3e758604e23951f40d76cf9).

**Comment by kallewoof** [comment]
I'm not sure why Travis is failing.

**Pull request merged**
