### PR TITLE
doc: Update GitHub documentation links

### PR DESCRIPTION
**Pull request by suriyaa**
Removing URL redirecting for GitHub documentation links.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
You will have to submit upstream if you want to modify any of the subtrees in `./src/`

**Comment by suriyaa** [comment]
@MarcoFalke How can I submit the changes upstream? With `git push upstream github-docs` in my local repo?

**Comment by MarcoFalke** [comment]
See https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md#subtrees

**Comment by suriyaa** [comment]
Thanks @MarcoFalke! I updated this pull request by **rebasing the commit**. (I removed the changes in the subtrees and kept the changes in the `./CONTRIBUTING.md` file.)

**Review by fanquake — APPROVED** [review]
ACK 470c6aa280f42558499db95b3ebca06a179d3514 - updates look correct.

**Pull request merged**
