### PR TITLE
0.18 backport: backport github-merge.py improvements

### PR DESCRIPTION
**Pull request by fanquake**
Recent improvements to the `github-merge.py` script in master, such as including review comments and displaying `ACK`s at sign-off time would be nice to have in the 0.18 branch. It also keeps the merge process the same for both branches.

### CODE REVIEW

**Comment by laanwj** [comment]
We haven't historically done this, generally I use the tools and process of master no matter what is on the specific branch. But if it helps you, I don't mind.

**Comment by MarcoFalke** [comment]
github-merge should be part of a separate repository, since it is not tied to the release process. I think we keep it here to expose it to more review.

Also, you might want to consider using an out-of-tree github-merge script, as you might have accidentally checked out a branch or pull request that shipped you a modified (potentially malicious) github-merge script.

**Comment by MarcoFalke** [comment]
So tend to NACK, it should either be left untouched or removed

**Comment by fanquake** [comment]
I'll just move to using an out-of-tree script.

**Pull request closed without merging**
