### PR TITLE
doc: Use bitcoind in Tor documentation

### PR DESCRIPTION
**Pull request by knoxcard**

### CODE REVIEW

**Comment by sipa** [comment]
What does `-daemon` have to do with Tor?

**Comment by knoxcard** [comment]
When you execute the following command, the bitcoin server will start, but it is not a background process.  Once you exit the terminal, the process dies as well.
`bitcoind -proxy=127.0.0.1:9050 -externalip=57qr3yd1nyntf5k.onion -listen`

By executing the command below, the Bitcoin server starts and forks as a background process, then exits and returns to the console.
`./bitcoind -daemon -proxy=127.0.0.1:9050 -externalip=57qr3yd1nyntf5k.onion -listen`

**Comment by sipa** [comment]
Sure, but there are many other options people may want to combine with the Tor specific ones (for example `-logtimestamps` or `-dbcache` or `-txindex` or `-maxconnections`). Some of these may be necessary in your particular setup; others may be personal preference.

But this document isn't trying to give a comprehensive overview of all options; just the Tor specific ones. There are probably dozens of others that could be listed.

**Comment by knoxcard** [comment]
Hmmm, can't imagine someone not using -daemon.  In my Debian environment, I would never had a persistent process without it.  Okay, but how about the first correction I made, where it states

bitcoin instead of bitcoind

**Comment by knoxcard** [comment]
My apologies, daemon=1 can be configured in bitcoin.conf...gotchya

**Comment by sipa** [comment]
All options can be configured in bitcoin.conf or on the command line.

Yes, the first fix (bitcoind instead of bitcoin) is great. There is another instance of that at the bottom of the file, btw.

If you think nobody would want to run without daemon (I personally always do as well), perhaps that would be a good reason to discuss changing the default (but do so in a separate PR).

**Comment by knoxcard** [comment]
Gonna resubmit pull request

**Comment by knoxcard** [comment]
Nice catch, fixed both instances, pull request ready.

**Comment by fanquake** [comment]
@knoxcard Can you please [squash your commits](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#squashing-commits)

**Comment by practicalswift** [comment]
utACK on the `bitcoin` to `bitcoind` changes assuming squash into one commit

**Comment by laanwj** [comment]
ACK after squash

**Comment by knoxcard** [comment]
My apologies for not responding sooner.
I've never squashed a commit, but I am committed to trying it. lol, lil Github humor for you there.
I'll try to get around to this first thing tomorrow.

***Would be wonderful it GitHub could automate these kind of tasks or just create a "squash commit" button

**Comment by practicalswift** [comment]
@knoxcard 

```
$ git rebase -i HEAD~3 # mark the two last commits as fixups.
$ git push -f
```

**Comment by laanwj** [comment]
Looks like you have enabled maintainers pushing to your branch - pushed a squashed version.
(though if you can, read up on git so you can do this yourself next time)

**Comment by knoxcard** [comment]
Thank You
I am a super technical guy and use git all time.
Where would I have executed those commands?
New console window in Windows, then create a new folder then git fetch?

Am I missing something?
I submitted these changes using the Github web interface.
See where I am coming from?

**Comment by knoxcard** [comment]
Nice work gentlemen, may your Bitcoin be plentiful as the years pass.

**Pull request merged**
