### PR TITLE
Add fee option to fundrawtransaction

### PR DESCRIPTION
**Pull request by promag**
Depends on #7518.

Currently there is a dynamic/minimum fee determination when the transaction is constructed. 
This PR adds the fee option to `fundrawtransaction` for when the caller wants to specify an already determined fee by other means.

Note that this is rebased with #7518 so only consider the last commit.

### CODE REVIEW

**Comment by promag** [comment]
Will add tests when this is considered acceptable.

**Comment by jonasschnelli** [comment]
Concept ACK.
The RBF feebump command requires a similar change.

**Comment by sdaftuar** [comment]
Wouldn't feerate make more sense to specify, since presumably you don't know how big the transaction will be?

**Comment by sipa** [comment]
I agree that feerate makes more sense. When you're calling
fundrawtransaction, you don't know what the final inputs (and sometimes
outputs) will be, or you wouldn't be calling it.

**Comment by promag** [comment]
Suppose the use case where the fee was estimated, rounded, displayed and accepted by the user. I just want to honour that value. If it is not enough then if fails, but if it succeeds then its added to the block reward.

I'm aware of transaction size and all, but at the end I just need to **fund** the requested fee.

**Comment by jonasschnelli** [comment]
@promag: how about using CoinControls `nMinimumTotalFee` for that purpose?

**Comment by promag** [comment]
As I said, I have to honour that value and still use the unspent selection algorithm. There is no `nMaximumTotalFee` otherwise I would be happy.

**Comment by promag** [comment]
Unless you (all) agree on adding `nMaximumTotalFee` and fail if it's not enough.

**Comment by promag** [comment]
Since #7518 was merged, can I get some closure here?

**Comment by laanwj** [comment]
We try to avoid absolute fees on the API, because they make it easy to accidentally post a transaction with too little (or too much) fee. Especially for a call like `fundrawtransaction`, where, as said by @sdaftuar and @sipa, the final size of the transaction is not yet known. A fee rate would be better IMO.

**Comment by promag** [comment]
@laanwj even `nMaximumTotalFee`?

**Comment by laanwj** [comment]
> If it is not enough then if fails, but if it succeeds then its added to the block reward.** If it is not enough then if fails, but if it succeeds then its added to the block reward.**

But when would it fail? You mean when it would be rejected by local mempool policy?

**Comment by promag** [comment]
@laanwj nMaximumTotalFee would be added to `CCoinControl` and only used in `CWallet::CreateTransaction`. This is useful for services depending on bitcoind wishing to create transactions and have control of the final fee.

**Comment by laanwj** [comment]
I  still don't see the point. Why would you specify a maximum fee instead of a fee-rate? Before calling fundrawtransaction you **don't know** how large the transaction is going to be, and miners  judge fee-rate, not total fee, so it's easy to get a transaction stuck this way.

**Comment by MarcoFalke** [comment]
Agree with @laanwj. Even though we have a `-maxtxfee` as some upper bound which ideally should never trigger, adding something like this as an option to fundraw does not make sense. You can look at the transaction later to find out the total fee and discard it/do other things if you don't like the fee amount.

**Comment by laanwj** [comment]
> You can look at the transaction later to find out the total fee and discard it/do other things if you don't like the fee amount

Right, that's one of the things you get for free with using a multi-step process instead of a single `sendtoaddress`.

**Comment by promag** [comment]
Imagine there are lots of small unspents that if used causes the total fee to increase. If lockUnspent option is true and fee exceeds the max fee then no locking would occur.

Regardless of maxFee, I believe exposing the minFee (of `CCoinControl`) and allowing to override `nTxConfirmTarget` is acceptable?

**Comment by paveljanik** [comment]
Needs rebase.

**Comment by sipa** [comment]
Concept ACK for a maxfee. I don't think fundrawtransaction should have an exact fee option though.

Also needs a rebase after #7518.

**Comment by promag** [comment]
I'm going forward with maxfee.

**Comment by sipa** [comment]
@promag Still working on this?

**Comment by laanwj** [comment]
Closing this due to inactivity, no reply from author in a month. Feel free to ping me if you're starting work on this again then I'll reopen.

**Comment by jonasschnelli** [comment]
Related: https://github.com/bitcoin/bitcoin/pull/7967 ([merged] [RPC] add feerate option to fundrawtransaction)

**Pull request closed without merging**
