### PR TITLE
[25.x] qt: 25.1rc1 translations update

### PR DESCRIPTION
**Pull request by hebasto**
This PR pulls the recent translations from the [Transifex.com](https://www.transifex.com/bitcoin/bitcoin) using the [`bitcoin-maintainer-tools/update-translations.py`](https://github.com/bitcoin-core/bitcoin-maintainer-tools/blob/main/update-translations.py) tool.

According to our [Release Process docs](https://github.com/bitcoin/bitcoin/blob/master/doc/release-process.md#before-every-release-candidate), it is supposed to be merged before `v25.1rc1` tagging.

Changes in "Chinese (China) (zh_CN)" translation were manually discarded as they have too many removals (it looks like a vandalism).

### CODE REVIEW

**Comment by hebasto** [comment]
Friendly ping @stickies-v @jarolrod :)

**Comment by hebasto** [comment]
I have manually discarded changes in "German (de)" and  "Chinese (China) (zh_CN)" translations as they have too many removals and look like a vandalism.

**Review by stickies-v — APPROVED** [review]
ACK 40188072db24807a0f2721e0d4b63045601bffd9

Following the translation process and manually discarding the changes to `bitcoin_de.ts` and `bitcoin_ch_ZN.ts` (didn't inspect the translations in detail but those indeed look like vandalism), I have arrived at a zero diff with 40188072db24807a0f2721e0d4b63045601bffd9 (based on ecc74cd4f3ba26b4ae1fe1c08289971bed399597)

> Removed "Portuguese (QT FILETYPE)" translation, which has no point:

Was this removed on tx already? I didn't have to do any manual changes for this.

**Comment by Emzy** [comment]
I will fix the German translation. It will take a day.

**Comment by hebasto** [comment]
@Emzy 
> I will fix the German translation. It will take a day.

If this PR will be merged earlier (to not delaying 25.1rc1 tagging), the updated translation will be fetched for the next tag.

**Comment by hebasto** [comment]
> I will fix the German translation. It will take a day.

Picked up :)

Friendly ping @stickies-v @jarolrod. Once more :)

**Review by stickies-v — APPROVED** [review]
re-ACK 88b525f93adc713dc69a6af94f3b9fd4474595d4

**Review by jarolrod — APPROVED** [review]
ACK 88b525f93adc713dc69a6af94f3b9fd4474595d4

**Pull request merged**
