### PR TITLE
ci: Build and run tests once on freebsd

### PR DESCRIPTION
**Pull request by maflcko**
Could be activated through https://github.com/marketplace/cirrus-ci

### CODE REVIEW

**Comment by fanquake** [comment]
Concept ACK running tests on a BSD. Is this on Cirrus CI because we've run out of capacity with Travis?

**Comment by MarcoFalke** [comment]
I believe cirrus ci is the only solution that offers freebsd.

**Comment by laanwj** [comment]
While I like the idea of adding BSDs, I'm not sure I'd like to add yet another different, incompatible CI besides AppVeyor and Travis. They all work slightly different for restarting the build, checking the logs, etc.

**Comment by MarcoFalke** [comment]
I tend to agree that our ci turns into a jungle of traffic lights that no one really knows how to handle. Also, I am not aware of the last time something broke on freebsd, so adding this has little value. Though, I remember someone asked for adding some bsd to the ci, which is why I took a stab here to see if it would work.

**Comment by practicalswift** [comment]
Concept ACK

I think the benefit of testing in diverse environments outweighs the maintenance cost.

**Comment by MarcoFalke** [comment]
@practicalswift Please remind me of the last failure we had that was seen on freebsd but not on any other platform. If there was none, it seems this test adds little value in its current form.

**Comment by practicalswift** [comment]
@MarcoFalke During the last year we've had at least #13503 and #13314 :-)

**Comment by laanwj** [comment]
> I think the benefit of testing in diverse environments outweighs the maintenance cost.

This is not a matter of "maintenance cost". I agree the CI script itself needs very little maintenance.

The problem is that every PR kind of becomes a slot machine of different CIs. I think it will fail much more often randomly than due to an actual problem.

I'd have no problem with this if it could be added as another Travis run.

**Comment by MarcoFalke** [comment]
It could be merged and it would only be run by people that opt-in (by activating the cirrus ci app)

**Comment by MarcoFalke** [comment]
In the same regard we could disable the appveyor on this repo again.

**Comment by laanwj** [comment]
> In the same regard we could disable the appveyor on this repo again.

Yea, though I'd say appveyor windows is pretty useful. It's sufficiently different from Linux, .e.g. breaking on windows but not linux is pretty common!

**Comment by kev009** [comment]
I am the ports net-p2p/bitcoin{, -daemon, -utils} maintainer and would appreciate this CI feedback in the repo.

**Comment by MarcoFalke** [comment]
Going to merge this, without enabling any hooks on this repo, so it doesn't turn into a slot machine

**Comment by fkorotkov** [comment]
Hey @MarcoFalke, what do you mean by "it doesn't turn into a slot machine"? 😅

**Comment by MarcoFalke** [comment]
Right now we use several ci solutions:

* Travis for cross builds to windows + mac, as well as to run the functional tests in different config settings on ubuntu
* Appveyor to check the msvc compilation and run the functional tests on windows

We have had some intermittent issues with those two in the past that were hard to debug, as they'd often only happen in the ci system. So the solution to that would be to rerun the build, i.e. pull the arm of the slot machine :slot_machine: and hope it turns green. https://github.com/bitcoin/bitcoin/pull/15338#issuecomment-460717158

I will keep an eye on the results in my private repo, and if all looks fine, we can enable it for this repo as well.

**Comment by MarcoFalke** [comment]
https://cirrus-ci.com/github/MarcoFalke/bitcoin

**Comment by scravy** [comment]
What’s the deal with enabling them? It does not ban anyone from merging, doesn’t it? It just gets automatically triggered and may give reviewers some additional input.

**Comment by fkorotkov** [comment]
@MarcoFalke got it! Thanks for explaining the allegory. 🙌

**Pull request merged**
