### PR TITLE
net: compat.h related cleanup

### PR DESCRIPTION
**Pull request by hebasto**
It is the `compat.h` header's job to provide platform-agnostic interfaces for internet operations.
No need in `#include <arpa/inet.h>` scattered around.

### CODE REVIEW

**Comment by hebasto** [comment]
cc @jamesob

**Comment by practicalswift** [comment]
ACK 3da5a27ca3290b05b50453295304d35f5ac729f7: patch looks correct

**Comment by hebasto** [comment]
Removed trailing space.

**Comment by practicalswift** [comment]
re-ACK cadb77a6ab8a3e6f56062cfaec4dd8168c71b39d: patch looks even better

**Comment by laanwj** [comment]
Code review ACK cadb77a6ab8a3e6f56062cfaec4dd8168c71b39d

**Pull request merged**
