### PR TITLE
doc: Document that wallet salvage is experimental

### PR DESCRIPTION
**Pull request by maflcko**
See #20151

### CODE REVIEW

**Comment by practicalswift** [comment]
ACK fab94534b64593be1620c989bf69eb02e1be9b1b: user safety first

**Review by hebasto — APPROVED** [review]
ACK fab94534b64593be1620c989bf69eb02e1be9b1b, maybe capitalize into "WARNING"?

**Review by mjdietzx — APPROVED** [review]
ack fab94534b64593be1620c989bf69eb02e1be9b1b

**Review by meshcollider — COMMENTED** [review]
Trivial ACK fab94534b64593be1620c989bf69eb02e1be9b1b

**Comment by satoshi-n** [comment]
Yeah about time...

**Pull request merged**
