### PR TITLE
Remove contrib/debian/patches subdirectory

### PR DESCRIPTION
**Pull request by droark**
The directory hasn’t been touched in five years and seems like something that could be added again later if needed. Remove the subdirectory.

### CODE REVIEW

**Comment by practicalswift** [comment]
ACK ca04070

**Comment by TheBlueMatt** [comment]
Have you tested if the Debian build still succeeds if these files are missing? I'd bet they don't.

**Comment by laanwj** [comment]
What I sometimes wonder: is anyone using the stuff in `contrib/debian` to do debian builds at all?
Is it used for the PPAs?

**Comment by TheBlueMatt** [comment]
It is (roughly) used for the PPAs, AFAIK that is the only user.

**Comment by laanwj** [comment]
Okay, thanks. Yes that's enough reason to keep it around.

**Comment by TheBlueMatt** [comment]
Yea, I would say trash it, but we've gotten contributors to update the PPA through it, which helps me be super lazy :).

**Comment by fanquake** [comment]
Closing, seems we want to keep this.

**Comment by laanwj** [comment]
Well, yes, this directory (and the accompanying README file) is a standard fixture in `contrib/debian` directories, it doesn't hurt to keep it around, though it's unlikely any patches will be added there as we could just as well patch the project itself as it's part of the same tree.

**Comment by droark** [comment]
Thanks, everyone. I'll add a PR a little later that updates the README. Might as well ensure that people know to leave the directory alone. :)

**Pull request closed without merging**
