### PR TITLE
[23.x] macOS / build backports

### PR DESCRIPTION
**Pull request by fanquake**
Backports:
* #24549
* #24573
* #24588
* #24597

### CODE REVIEW

**Comment by gruve-p** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/24593/commits/f541a252f676dcdab15654e8b2b83b2dbcee46b3

**Comment by achow101** [comment]
Guix build

```
b2e644c68aabe198b0ad8e632f70fd86c3ae15c012fdf45fcabb257bfddfdd69  guix-build-f541a252f676/output/aarch64-linux-gnu/SHA256SUMS.part
3368e4d06b787221c3d3b3dbd09a4c1477fb8908ed1812e6e3c29c4590129e53  guix-build-f541a252f676/output/aarch64-linux-gnu/bitcoin-f541a252f676-aarch64-linux-gnu-debug.tar.gz
a6927b1ae118f547e1268dcc6966d4cb9f6aa5e6014924eafe371e9f48eb6311  guix-build-f541a252f676/output/aarch64-linux-gnu/bitcoin-f541a252f676-aarch64-linux-gnu.tar.gz
d1e8e6b05e553f733bc55d7a0d6b144169c2e2182484ebaa9c84bb1a4234b3a8  guix-build-f541a252f676/output/arm-linux-gnueabihf/SHA256SUMS.part
65028d30702a0fe072074a16b82633e7b3a3b7b9e9bfc7561e15edad6862b092  guix-build-f541a252f676/output/arm-linux-gnueabihf/bitcoin-f541a252f676-arm-linux-gnueabihf-debug.tar.gz
02e257d7e7b9b0a0b9a668f8933bb2b3cc7443dbd7b000a39ce96d043613c12f  guix-build-f541a252f676/output/arm-linux-gnueabihf/bitcoin-f541a252f676-arm-linux-gnueabihf.tar.gz
45e41f8457bdfd3bfc501f065e7e717ba10ada68044fe16248adf843ddb2afe4  guix-build-f541a252f676/output/arm64-apple-darwin/SHA256SUMS.part
6c1f9b4047a52d79874228c7eccc8a2dcad30b5ed74469066037e6d9f7ccdae9  guix-build-f541a252f676/output/arm64-apple-darwin/bitcoin-f541a252f676-arm64-apple-darwin-unsigned.dmg
516dd9cec4847012201e5e3793250329722465f187f14fb433e58cdda90645c8  guix-build-f541a252f676/output/arm64-apple-darwin/bitcoin-f541a252f676-arm64-apple-darwin-unsigned.tar.gz
d19bfe00e66aac8fa2c988d51825ba437871895769b2ddca9858104ac86e953a  guix-build-f541a252f676/output/arm64-apple-darwin/bitcoin-f541a252f676-arm64-apple-darwin.tar.gz
49032d00a20cfe303c6329a36566c7150c03541c42e9f5b3be6692c0e41cf5d4  guix-build-f541a252f676/output/dist-archive/bitcoin-f541a252f676.tar.gz
6d5f58462ec368f18b897b5c67fecd815be0cd29a6e93ee31d3eeeeddd32f26c  guix-build-f541a252f676/output/powerpc64-linux-gnu/SHA256SUMS.part
f89a390f0effc82ed47d31be167002e0a02ef23e7d467bc2b70603a56d9f6f4f  guix-build-f541a252f676/output/powerpc64-linux-gnu/bitcoin-f541a252f676-powerpc64-linux-gnu-debug.tar.gz
c7d165beda21c240527e9c21ca7eafd7a32f7077ed47cef5f47b6dc1c72c286b  guix-build-f541a252f676/output/powerpc64-linux-gnu/bitcoin-f541a252f676-powerpc64-linux-gnu.tar.gz
46a200ddb05a2ef50a59a2c3f6f0cd256d325a5839f11bb4f80d98464ce5a749  guix-build-f541a252f676/output/powerpc64le-linux-gnu/SHA256SUMS.part
204ee29c955cfa54368bbfe1be74921f44773d0e2d069db4333b92ca1b5ed825  guix-build-f541a252f676/output/powerpc64le-linux-gnu/bitcoin-f541a252f676-powerpc64le-linux-gnu-debug.tar.gz
e70a46f8b2e962b7fad8ffb4eed95e1e979bef60ebdce755e66dfd0ad81e2777  guix-build-f541a252f676/output/powerpc64le-linux-gnu/bitcoin-f541a252f676-powerpc64le-linux-gnu.tar.gz
0916b01d98a3afff4d1786f0f1f5b918bcf581eaea13dbaa99e1ecd228ac9c54  guix-build-f541a252f676/output/riscv64-linux-gnu/SHA256SUMS.part
c40ad5c3d322aa730c99a5c838e1495f53fd83aa5d218c7d93cfe19c9a23d605  guix-build-f541a252f676/output/riscv64-linux-gnu/bitcoin-f541a252f676-riscv64-linux-gnu-debug.tar.gz
befa3aaad5d425a7fe6c3610251609a82b8a92e54dadf66cc04e75af0189e0da  guix-build-f541a252f676/output/riscv64-linux-gnu/bitcoin-f541a252f676-riscv64-linux-gnu.tar.gz
477b7b7680f14e878a39b56be02ea81e197a2f9fc08d0e55fb7677f5cbe3a4b0  guix-build-f541a252f676/output/x86_64-apple-darwin/SHA256SUMS.part
6fe1afd688c35dfcdd6504d3c7d455bbcd12335b35efdb5412d0d0914e8803e3  guix-build-f541a252f676/output/x86_64-apple-darwin/bitcoin-f541a252f676-x86_64-apple-darwin-unsigned.dmg
67c0b6824888f6d114bc0eb1e280a8d9b766bde3092c908e582e29e44f10bc25  guix-build-f541a252f676/output/x86_64-apple-darwin/bitcoin-f541a252f676-x86_64-apple-darwin-unsigned.tar.gz
cfaae76b797d2f9f80ac0469957b12252a080564bdb72ff0071022e3a6d81cd2  guix-build-f541a252f676/output/x86_64-apple-darwin/bitcoin-f541a252f676-x86_64-apple-darwin.tar.gz
1c384e19b33e5b24de528f51b56c1589657e082f847603760cecfb6f76982442  guix-build-f541a252f676/output/x86_64-linux-gnu/SHA256SUMS.part
f547cde3a4679ea856c129eccde23dc111e671cbc1d896b5ea9da14e3429b389  guix-build-f541a252f676/output/x86_64-linux-gnu/bitcoin-f541a252f676-x86_64-linux-gnu-debug.tar.gz
06de04d5791619c2765e8b3894d3ab7d07e9738cd02c568a5b108f8a46bf6b8f  guix-build-f541a252f676/output/x86_64-linux-gnu/bitcoin-f541a252f676-x86_64-linux-gnu.tar.gz
5b80a7b25190cddf959f6cba1a6c7310396d6e4dfc4f27324a419d776fa16cbf  guix-build-f541a252f676/output/x86_64-w64-mingw32/SHA256SUMS.part
559d3b9e74c9614cb6581cc9d98614d82f0b9a34f7ea149469a5066aead160e8  guix-build-f541a252f676/output/x86_64-w64-mingw32/bitcoin-f541a252f676-win64-debug.zip
4f738965fd12f154811c3bbb37b93e251044741d9bf353e13d29f68796329695  guix-build-f541a252f676/output/x86_64-w64-mingw32/bitcoin-f541a252f676-win64-setup-unsigned.exe
358ed3056ecf0b4dd3684645e1a04c84a97f67d27a144b63fda8ac90535256cb  guix-build-f541a252f676/output/x86_64-w64-mingw32/bitcoin-f541a252f676-win64-unsigned.tar.gz
0719e5ebfd4070cbdb30cfa58d03b5491edd6f4fac0b9b15d4b7ff29e9f3617b  guix-build-f541a252f676/output/x86_64-w64-mingw32/bitcoin-f541a252f676-win64.zip
```

**Comment by achow101** [comment]
ACK f541a252f676dcdab15654e8b2b83b2dbcee46b3

**Comment by fanquake** [comment]
Guix Build:
```bash
bash-5.1# find guix-build-$(git rev-parse --short=12 HEAD)/output/ -type f -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum
b2e644c68aabe198b0ad8e632f70fd86c3ae15c012fdf45fcabb257bfddfdd69  guix-build-f541a252f676/output/aarch64-linux-gnu/SHA256SUMS.part
3368e4d06b787221c3d3b3dbd09a4c1477fb8908ed1812e6e3c29c4590129e53  guix-build-f541a252f676/output/aarch64-linux-gnu/bitcoin-f541a252f676-aarch64-linux-gnu-debug.tar.gz
a6927b1ae118f547e1268dcc6966d4cb9f6aa5e6014924eafe371e9f48eb6311  guix-build-f541a252f676/output/aarch64-linux-gnu/bitcoin-f541a252f676-aarch64-linux-gnu.tar.gz
d1e8e6b05e553f733bc55d7a0d6b144169c2e2182484ebaa9c84bb1a4234b3a8  guix-build-f541a252f676/output/arm-linux-gnueabihf/SHA256SUMS.part
65028d30702a0fe072074a16b82633e7b3a3b7b9e9bfc7561e15edad6862b092  guix-build-f541a252f676/output/arm-linux-gnueabihf/bitcoin-f541a252f676-arm-linux-gnueabihf-debug.tar.gz
02e257d7e7b9b0a0b9a668f8933bb2b3cc7443dbd7b000a39ce96d043613c12f  guix-build-f541a252f676/output/arm-linux-gnueabihf/bitcoin-f541a252f676-arm-linux-gnueabihf.tar.gz
45e41f8457bdfd3bfc501f065e7e717ba10ada68044fe16248adf843ddb2afe4  guix-build-f541a252f676/output/arm64-apple-darwin/SHA256SUMS.part
6c1f9b4047a52d79874228c7eccc8a2dcad30b5ed74469066037e6d9f7ccdae9  guix-build-f541a252f676/output/arm64-apple-darwin/bitcoin-f541a252f676-arm64-apple-darwin-unsigned.dmg
516dd9cec4847012201e5e3793250329722465f187f14fb433e58cdda90645c8  guix-build-f541a252f676/output/arm64-apple-darwin/bitcoin-f541a252f676-arm64-apple-darwin-unsigned.tar.gz
d19bfe00e66aac8fa2c988d51825ba437871895769b2ddca9858104ac86e953a  guix-build-f541a252f676/output/arm64-apple-darwin/bitcoin-f541a252f676-arm64-apple-darwin.tar.gz
49032d00a20cfe303c6329a36566c7150c03541c42e9f5b3be6692c0e41cf5d4  guix-build-f541a252f676/output/dist-archive/bitcoin-f541a252f676.tar.gz
6d5f58462ec368f18b897b5c67fecd815be0cd29a6e93ee31d3eeeeddd32f26c  guix-build-f541a252f676/output/powerpc64-linux-gnu/SHA256SUMS.part
f89a390f0effc82ed47d31be167002e0a02ef23e7d467bc2b70603a56d9f6f4f  guix-build-f541a252f676/output/powerpc64-linux-gnu/bitcoin-f541a252f676-powerpc64-linux-gnu-debug.tar.gz
c7d165beda21c240527e9c21ca7eafd7a32f7077ed47cef5f47b6dc1c72c286b  guix-build-f541a252f676/output/powerpc64-linux-gnu/bitcoin-f541a252f676-powerpc64-linux-gnu.tar.gz
46a200ddb05a2ef50a59a2c3f6f0cd256d325a5839f11bb4f80d98464ce5a749  guix-build-f541a252f676/output/powerpc64le-linux-gnu/SHA256SUMS.part
204ee29c955cfa54368bbfe1be74921f44773d0e2d069db4333b92ca1b5ed825  guix-build-f541a252f676/output/powerpc64le-linux-gnu/bitcoin-f541a252f676-powerpc64le-linux-gnu-debug.tar.gz
e70a46f8b2e962b7fad8ffb4eed95e1e979bef60ebdce755e66dfd0ad81e2777  guix-build-f541a252f676/output/powerpc64le-linux-gnu/bitcoin-f541a252f676-powerpc64le-linux-gnu.tar.gz
0916b01d98a3afff4d1786f0f1f5b918bcf581eaea13dbaa99e1ecd228ac9c54  guix-build-f541a252f676/output/riscv64-linux-gnu/SHA256SUMS.part
c40ad5c3d322aa730c99a5c838e1495f53fd83aa5d218c7d93cfe19c9a23d605  guix-build-f541a252f676/output/riscv64-linux-gnu/bitcoin-f541a252f676-riscv64-linux-gnu-debug.tar.gz
befa3aaad5d425a7fe6c3610251609a82b8a92e54dadf66cc04e75af0189e0da  guix-build-f541a252f676/output/riscv64-linux-gnu/bitcoin-f541a252f676-riscv64-linux-gnu.tar.gz
477b7b7680f14e878a39b56be02ea81e197a2f9fc08d0e55fb7677f5cbe3a4b0  guix-build-f541a252f676/output/x86_64-apple-darwin/SHA256SUMS.part
6fe1afd688c35dfcdd6504d3c7d455bbcd12335b35efdb5412d0d0914e8803e3  guix-build-f541a252f676/output/x86_64-apple-darwin/bitcoin-f541a252f676-x86_64-apple-darwin-unsigned.dmg
67c0b6824888f6d114bc0eb1e280a8d9b766bde3092c908e582e29e44f10bc25  guix-build-f541a252f676/output/x86_64-apple-darwin/bitcoin-f541a252f676-x86_64-apple-darwin-unsigned.tar.gz
cfaae76b797d2f9f80ac0469957b12252a080564bdb72ff0071022e3a6d81cd2  guix-build-f541a252f676/output/x86_64-apple-darwin/bitcoin-f541a252f676-x86_64-apple-darwin.tar.gz
1c384e19b33e5b24de528f51b56c1589657e082f847603760cecfb6f76982442  guix-build-f541a252f676/output/x86_64-linux-gnu/SHA256SUMS.part
f547cde3a4679ea856c129eccde23dc111e671cbc1d896b5ea9da14e3429b389  guix-build-f541a252f676/output/x86_64-linux-gnu/bitcoin-f541a252f676-x86_64-linux-gnu-debug.tar.gz
06de04d5791619c2765e8b3894d3ab7d07e9738cd02c568a5b108f8a46bf6b8f  guix-build-f541a252f676/output/x86_64-linux-gnu/bitcoin-f541a252f676-x86_64-linux-gnu.tar.gz
5b80a7b25190cddf959f6cba1a6c7310396d6e4dfc4f27324a419d776fa16cbf  guix-build-f541a252f676/output/x86_64-w64-mingw32/SHA256SUMS.part
559d3b9e74c9614cb6581cc9d98614d82f0b9a34f7ea149469a5066aead160e8  guix-build-f541a252f676/output/x86_64-w64-mingw32/bitcoin-f541a252f676-win64-debug.zip
4f738965fd12f154811c3bbb37b93e251044741d9bf353e13d29f68796329695  guix-build-f541a252f676/output/x86_64-w64-mingw32/bitcoin-f541a252f676-win64-setup-unsigned.exe
358ed3056ecf0b4dd3684645e1a04c84a97f67d27a144b63fda8ac90535256cb  guix-build-f541a252f676/output/x86_64-w64-mingw32/bitcoin-f541a252f676-win64-unsigned.tar.gz
0719e5ebfd4070cbdb30cfa58d03b5491edd6f4fac0b9b15d4b7ff29e9f3617b  guix-build-f541a252f676/output/x86_64-w64-mingw32/bitcoin-f541a252f676-win64.zip
```

**Comment by fanquake** [comment]
Added 1 additional commit. Should be straightforward to re-ACK.

**Comment by laanwj** [comment]
Code review ACK 61c021605f8733891cb8d92509c84ac814d3712a

**Pull request merged**
