### PR TITLE
[wallet] Remove redundant initialization

### PR DESCRIPTION
**Pull request by practicalswift**

### CODE REVIEW

**Comment by JeremyRubin** [comment]
utACK eb8d6cc.

nit: I'd like it if you added an assert(pindexRescan != nullptr) after the end of the if/else block, which is the invariant the previous version enforced.

**Comment by paveljanik** [comment]
Hmm, what about initializing it with

```C++
pindexRescan = chainActive.Genesis();
```

and shorten the code?

**Comment by JeremyRubin** [comment]
That seems nice.

**Comment by practicalswift** [comment]
Now initializing to `chainActive.Genesis()` as requested :-)

**Comment by paveljanik** [comment]
You can now remove the else branch (this was the "nice" of the change)!

**Comment by practicalswift** [comment]
Ah, fixed and pushed! :-)

**Comment by paveljanik** [comment]
6-,2+ nice. The only missing thing is a comment above the changed code explaining it.

ACK https://github.com/bitcoin/bitcoin/pull/9576/commits/80fb8e7944a68573336fddb554ac332104336247

**Comment by practicalswift** [comment]
@paveljanik Any suggestions on how to explain it succinctly without repeating the code? :-)

**Comment by MarcoFalke** [comment]
I don't think we need a comment here. This part is rather self explanatory when comparing to other parts of the code base.

**Comment by laanwj** [comment]
I'm not missing a comment in the code itself, but an explanation in the commit message as to why this is redundant would be nice.

**Comment by practicalswift** [comment]
@laanwj I've now added an explanation in the commit message. Looks good? :-)

**Comment by laanwj** [comment]
@practicalswift yes, awesome.

**Pull request merged**
