### PR TITLE
test: Add signet witness commitment section parse tests

### PR DESCRIPTION
**Pull request by maflcko**

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Before: https://drahtbot.github.io/reports/coverage/bitcoin/bitcoin/master/total.coverage/src/signet.cpp.gcov.html
After: https://drahtbot.github.io/reports/coverage/bitcoin/bitcoin/20004/total.coverage/src/signet.cpp.gcov.html

**Comment by MarcoFalke** [comment]
cc @kallewoof / @ajtowns :sweat_smile:

**Review by kallewoof — COMMENTED** [review]
Nice!

utACK faee74f6c841eea391c08ebbadb045746c3ef77f

**Comment by ajtowns** [comment]
Not really convinced always explicitly passing in an ArgsManager to CreateChainParams is an improvement. Could make it

```c++
std::unique_ptr<const CChainParams> CreateChainParams(const std::string& chain, ArgsManager* pargs)
{
   ArgsManager& args = (pargs != nullptr ? *pargs : gArgs);
    ...
}
```

or similar and avoid touching all the other code?

Seems kind of a shame not to add a dummy tx a well to get to 100% line coverage?

**Comment by MarcoFalke** [comment]
> avoid touching all the other code

Long term goal is to get rid of the gArgs global in Core (though, not the gui), so I think this patch will be done anyway. Left as is for now.

> Seems kind of a shame not to add a dummy tx a well to get to 100% line coverage?

Done :100:

**Comment by laanwj** [comment]
ACK fa29b5ae666bbb4c19188f0dcf8a1ba738aac624

**Pull request merged**
