### PR TITLE
ci: apply cache size limit and  print ccache statistics in "ARM64 Android APK" task

### LINKED ISSUE #25475: ci: Handle `ccache` in the proper way in "ARM64 Android APK" task
On the master branch, there are some flaws when using `ccache` in the "ARM64 Android APK" CI task:
- no `ccache` statistics printed
- no our custom cache size [limit](https://github.com/bitcoin/bitcoin/blob/0dd34773334c7f4db7b05df30ee61b011795b46d/.cirrus.yml#L6) applied (it has grown up to `ccache cache size is 4243Mb.` for [now](https://api.cirrus-ci.com/v1/task/5827307548966912/logs/Upload%20'ccache'%20cache.log))

#### Useful skills:

- basic Bash skills
- basic understanding of [Cirrus CI](https://cirrus-ci.org/guide/quick-start/)

#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

Probably, only a few modifications in [`ci/test/06_script_a.sh`](https://github.com/bitcoin/bitcoin/blob/master/ci/test/06_script_a.sh) are required.

### PR DESCRIPTION
**Pull request by sogoagain**
Fixes https://github.com/bitcoin/bitcoin/issues/25475

Modified `ci/test/06_script_a.sh` file to apply cache size limit and print ccahce statistics in "ARM64 Android APK" task.

Please feel free to give me any feedback. Thanks.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Please squash your commits according to https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#squashing-commits

**Review by hebasto — APPROVED** [review]
Approach ACK 7899294d2ec9053f61fb89f015c676be91007bf2, https://api.cirrus-ci.com/v1/task/6391990253256704/logs/ci.log looks good.

Of course, https://github.com/bitcoin/bitcoin/pull/25530#issuecomment-1173483561 should be addressed before merging.

**Comment by hebasto** [comment]
Looking at the very low cache hit rate, I'm wondering whether we should use the `NDK_CCACHE` environment variable as documented [here](https://developer.android.com/ndk/downloads/revision_history)?

**Review by hebasto — APPROVED** [review]
ACK 31346a31962ab06d49cb45aee8acd92d8806538b, my previous [comment](https://github.com/bitcoin/bitcoin/pull/25530#issuecomment-1173822177) can be considered as a suggestion for a follow up.

**Comment by sogoagain** [comment]
@hebasto Yes. The cache hit ratio is definitely low. I will look into problem the issue including `NDK_CCACHE` environment variable.

**Pull request merged**
