### PR TITLE
 Merge leveldb subtree 

### PR DESCRIPTION
**Pull request by maflcko**
For review:

```sh
git fetch https://github.com/bitcoin-core/leveldb
./test/lint/git-subtree-check.sh src/leveldb
```

Closes #13860

### CODE REVIEW

**Comment by achow101** [comment]
utACK fa14fa742d3347c5b627f3375770536c648192fe

**Comment by ken2812221** [comment]
utACK fa14fa7

**Comment by fanquake** [comment]
tested the subtree merge ACK fa14fa7
```
merge 13925
[pull/13925/local-merge 4fc2596df] Merge #13925: Merge leveldb subtree
 Date: Fri Aug 10 16:50:47 2018 +0800
#13925 Merge leveldb subtree into master
* fa14fa742 Merge leveldb subtree (MarcoFalke) (pull/13925/head)
* ec749b1bc Squashed 'src/leveldb/' changes from 64052c76c5..524b7e36a8 (MarcoFalke)

Dropping you on a shell so you can try building/testing the merged source.
Run 'git diff HEAD~' to show the changes being merged.
Type 'exit' when done.

bash-3.2$ git fetch https://github.com/bitcoin-core/leveldb
remote: Counting objects: 1266, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 1266 (delta 540), reused 541 (delta 540), pack-reused 722
Receiving objects: 100% (1266/1266), 415.15 KiB | 273.00 KiB/s, done.
Resolving deltas: 100% (963/963), completed with 160 local objects.
From https://github.com/bitcoin-core/leveldb
 * branch                HEAD       -> FETCH_HEAD

bash-3.2$ ./test/lint/git-subtree-check.sh src/leveldb
src/leveldb in HEAD currently refers to tree f8cdc77167be86194f98d0412baf4b89d3d5abe6
src/leveldb in HEAD was last updated in commit ec749b1bcdf2483b642fb51d635800e272c68ba6 (tree f8cdc77167be86194f98d0412baf4b89d3d5abe6)
src/leveldb in HEAD was last updated to upstream commit 524b7e36a8e3bce6fcbcd1b5df09024283f325ba (tree f8cdc77167be86194f98d0412baf4b89d3d5abe6)
GOOD
bash-3.2$ 
```

**Comment by laanwj** [comment]
utACK fa14fa742d3347c5b627f3375770536c648192fe

**Pull request merged**
