### PR TITLE
instance of 'mem pool' to 'mempool'

### PR DESCRIPTION
**Pull request by smatthewenglish**
there was only one instance of  'mem pool' and not 'mempool', so I changed it to conform to the others

### CODE REVIEW

**Comment by laanwj** [comment]
Makes sense, utACK

**Comment by paveljanik** [comment]
Not the only one, please fix also the second one in `src/rpc/mining.cpp`.

**Comment by MarcoFalke** [comment]
I was once wondering it this should be changed to *transaction pool*, but I don't think it is feasible to change at this point.

**Comment by laanwj** [comment]
Yes, in retrospect that would have been a much better name. But everyone knows what a mempool is by now, changing it will just seed more confusion. Better to go with the least invasive change.

**Comment by s-matthew-english** [comment]
ok- I changed that one in `src/rpc/mining.cpp`, but now I guess I should squash the commits. is it possible to do that using the GitHub web app? If not I can do it from my console but not until later this evening.

**Comment by laanwj** [comment]
Squashed the commits

**Comment by fanquake** [comment]
utACK

**Pull request merged**
