### PR TITLE
Release notes about mining code changes

### PR DESCRIPTION
**Pull request by morcos**
@laanwj I made this a new PR since it seemed you were about to merge the other one

@MarcoFalke hopefully this won't conflict with yours

### CODE REVIEW

**Comment by petertodd** [comment]
ACK https://github.com/morcos/bitcoin/commit/b3926a2e0d5a8340f4ddeac11d7f56a55586adae

**Comment by MarcoFalke** [comment]
ACK b3926a2. Does not conflict with mine.

**Comment by morcos** [comment]
@laanwj I rebased this since you merged the prior PR, but then it occurred to me that maybe I shouldn't have b/c the ACK's don't line up.  Please let me know what you prefer for the future.
Anyway, its the same text that was ACK'ed

**Comment by MarcoFalke** [comment]
@morcos If this was only a rebase, you can just do `git reset --hard b3926a2;git push <> -f` and GitHub will show it lined up.

**Comment by laanwj** [comment]
ACK

**Pull request merged**
