### PR TITLE
[WIP] Implement pruning to location

### PR DESCRIPTION
**Pull request by rodentrabies**
Implements #10929 
- [x] Add `-pruneto` option.
- [x] Implement optional moving of blocks instead of deleting while pruning.
- [ ] Implement linking moved blocks back when prune location is accessible.

### CODE REVIEW

**Comment by jnewbery** [comment]
@mrwhythat thanks for your contribution. I've taken a look at the code and it looks like a good start to #10929 but I have some doubts about the overall concept. My comments are here: https://github.com/bitcoin/bitcoin/issues/10929#issuecomment-329607560

**Comment by mrwhythat** [comment]
From discussion in #10929, it's unclear whether this PR should be continued or not. Any suggestions?

**Comment by jnewbery** [comment]
Hi @mrwhythat - sorry. I really didn't want to discourage you on your first PR. Your first commits look good, but my view of #10929 is that there are a lot of edge cases to think about before this will be in a useful state. I don't see huge benefit from the feature, but there may be others who do.

For me there are much more interesting features to be worked on, but I certainly wouldn't concept NACK this if you feel strongly that it would be useful to lots of users. Feel free to contact me on irc or slack.

**Comment by mrwhythat** [comment]
Ok, then I'm closing this PR, but I'll leave the branch in case it's needed some time in the future.

**Pull request closed without merging**
