### PR TITLE
p2p: Use absolute FQDN for DNS seed domains

### PR DESCRIPTION
**Pull request by ghost**
Fixes https://github.com/bitcoin/bitcoin/issues/23193 by using absolute FQDN for domains used by DNS seeds.

It improves security and should not break anything based on my research and testing. Few things about absolute FQDN are shared in https://superuser.com/questions/1467958/why-does-putting-a-dot-after-the-url-remove-login-information

Master branch:

```
DNS seed x9.dnsseed.bitcoin.dashjr.org. responded with IP 127.0.0.1
```

PR branch:

```
DNS seed x9.dnsseed.bitcoin.dashjr.org. responded with IP 159.89.108.149
```

Reviewers can follow the steps mentioned in Issue to test: https://github.com/bitcoin/bitcoin/issues/23193#issuecomment-937717145

### CODE REVIEW

**Review by luke-jr — APPROVED** [review]
utACK

**Comment by luke-jr** [comment]
You might consider rewriting this by appending the final period in `ThreadDNSAddressSeed`, rather than expecting the chainparams to have it for each entry. That seems safe and more mistake-resistant (eg, you forgot the testnet DNS seeds).

**Review by kristapsk — APPROVED** [review]
utACK 04ef501ae030df490d419e3cf97b2dd34f2ec655

**Comment by prayank23** [comment]
- Made changes in 4 domains used by testnet DNS seeds (L233-L236)
- Added @practicalswift as co-author

**Comment by practicalswift** [comment]
@prayank23 

Still not complete I'm afraid: the signet DNS seed node is not changed :)

This is the command I used locally to check the changes:

```
$ sed -i 's/vSeeds.emplace_back("\(.*[a-z]\)");/vSeeds.emplace_back("\1.");/g' src/chainparams.cpp
```

When doing the touch up you may drop me as co-author: I'm just an enthusiastic reviewer, and to don't introduce confusion I think "co-author" tagging should be reserved to situations where the actual commit is written by multiple parties (such as when editing a cherry-picked commit from another author) :)

**Comment by prayank23** [comment]
@practicalswift I did something wrong with squashing. Will fix it. Signet domain wasn't there because PR branch wasn't synced with master when I created pull request.


I had added you as co-author because its a small change and was suggested by you. Will remove it if you aren't okay with it.

**Comment by laanwj** [comment]
code review ACK ca2c313aa291ae44adc1b7148ed49125bdc77bf4

**Review by promag — COMMENTED** [review]
Code review ACK ca2c313aa291ae44adc1b7148ed49125bdc77bf4.

**Pull request merged**
