### PR TITLE
Change "oldstable" to "oldoldstable" for lidb4.8*

### PR DESCRIPTION
**Pull request by tailsjoin**
https://packages.debian.org/search?searchon=names&exact=1&suite=all&section=all&keywords=libdb4.8
Berkeley DB 4.8 is part of squeeze, which is now "oldoldstable."

### CODE REVIEW

**Comment by luke-jr** [comment]
utACK, but... I'm not sure it's actually safe to add repos for old Debian distros?

**Comment by laanwj** [comment]
> utACK, but... I'm not sure it's actually safe to add repos for old Debian distros?

I'm not sure either. I wasn't aware that we were recommending that. It's probably better to follow the build-from-source instructions under "Berkeley DB".

**Comment by theuni** [comment]
Agreed with the hesitance above. Adding a repo for building bitcoin is a pretty nasty recommendation. I'd rather recommend just building from source.

Alternatively: has anyone tried pinging the debian maintainers? They may be willing to carry db48 in oldstable/stable. IIRC homebrew just did that for us.

**Comment by laanwj** [comment]
@tailsjoin Ok, so let's remove that recommendation completely.

**Comment by tailsjoin** [comment]
I've removed the recommendation of adding sources for Debian, and fixed a punctuation mistake on the next line. Reading through the doc now it seems to flow well. If one were to have a problem installing libdb4.8 dependencies, the build instructions come soon after.

**Comment by tailsjoin** [comment]
Found one more capitalization error.

**Comment by tailsjoin** [comment]
Punctuation fixes in REST doc, too.

**Comment by laanwj** [comment]
Merged via 9fbca20
Backported to 0.11 as d7101a6

**Pull request closed without merging**
