### PR TITLE
build: Remove --enable-gprof

### PR DESCRIPTION
**Pull request by maflcko**
It is unclear what benefit this option has, given that:

* `gprof` requires re-compilation (`perf` and other tools can instead be used on existing executables)
* `gprof` requires hardening to be disabled
* `gprof` doesn't work with `clang`
* `perf` is documented in the dev-notes, and test notes, and embedded into the functional test framework; `gprof` isn't
* Anyone really wanting to use it could pass the required flags to `./configure`
* I couldn't find any mention of the use of `gprof` in the discussions in this repo, apart from the initial pull request adding it (cfaac2a60f3ac63ae8deccb03d88bd559449b78c)
* Keeping it means that it needs to be maintained and ported to CMake

Fix all issues by removing it.

### CODE REVIEW

**Review by sedited — APPROVED** [review]
ACK fa780e1c25e8e98253e32d93db65f78a0092433f

**Review by hebasto — APPROVED** [review]
ACK fa780e1c25e8e98253e32d93db65f78a0092433f, I have reviewed the code and it looks OK.

**Review by willcl-ark — APPROVED** [review]
crACK fa780e1c25e8e98253e32d93db65f78a0092433f

Agree on the rationale given here for removal.

I've previously tried to use `gprof` in place of `perf` (when `addr2line` was broken/unusably slow on my Ubuntu kernel) and hit against many of the pain points ("requirements") @maflcko mentions in OP, which also had me wondering how often this is really used...

I did find a reference to `gprof` remaining in depends: https://github.com/bitcoin/bitcoin/blob/7fd4905c403ccb233f489e2f6a6aa3cd53b033ed/depends/packages/qrencode.mk#L9

I think this is also unneeded, as libqrencode seems to default to `off` in the configure script:

```log
  --enable-gprof          generate extra code to write profile information
                          suitable for gprof [default=no]
```

**Comment by fanquake** [comment]
Nothing should be required here in regards to qrencode. I agree that this can just be removed.

**Comment by fanquake** [comment]
Removed the label because nothing was ever ported.

**Comment by hebasto** [comment]
> It needs to be ported to the table in https://gist.github.com/hebasto/2ef97d3a726bfce08ded9df07f7dab5e

Done.

**Pull request merged**
