### PR TITLE
util: remove WSL 1 workaround in fs

### PR DESCRIPTION
**Pull request by philmb3487**
Following discussion, the WSL1 patch will be removed, as WSL1 is no longer being developed by Microsoft. Instead, please upgrade to a mainstream WSL2 version. More information can be found on [the official website](https://docs.microsoft.com/en-us/windows/wsl/).

### CODE REVIEW

**Comment by NorrinRadd** [comment]
LGTM

**Comment by hebasto** [comment]
Are there any limitations why a Windows user cannot upgrade their WSL1 to WSL2?

**Comment by sinetek** [comment]
> Are there any limitations why a Windows user cannot upgrade their WSL1 to WSL2?

hi  @hebasto. As far as I know WSL1 is no longer being developed. [Documentation ](https://docs.microsoft.com/en-us/windows/wsl/compare-versions) indicates that WSL1 is slightly advantageous in some cases where access to the native filesystem is required, and WSL2 might interact with other virtualization solutions.
I'm not particularly attached to this hack.

**Comment by hebasto** [comment]
Why not just drop support for WSL1 then?

**Comment by 1440000bytes** [comment]
> I think this is reasonable to specify, as I myself spent a few minutes looking why the call IsWSL() was failing on my WSL environment.

@sinetek how can I test this?

> Why not just drop support for WSL1 then?

@hebasto 

Everyone would not have upgraded to WSL2 yet and there are some trade-offs according to the docs: https://docs.microsoft.com/en-us/windows/wsl/compare-versions#exceptions-for-using-wsl-1-rather-than-wsl-2

**Comment by sinetek** [comment]
> > I think this is reasonable to specify, as I myself spent a few minutes looking why the call IsWSL() was failing on my WSL environment.
> 
> @sinetek how can I test this?

Run the app under GDB and set a breakpoint on this function.
Alternatively you can see the result of `utsname.version` with the command `uname -v`.
The result on my box is `#1 SMP Wed Mar 2 00:30:59 UTC 2022`.


> > Why not just drop support for WSL1 then?
> 
> @hebasto
> 
> Everyone would not have upgraded to WSL2 yet and there are some trade-offs according to the docs: https://docs.microsoft.com/en-us/windows/wsl/compare-versions#exceptions-for-using-wsl-1-rather-than-wsl-2

I tend to agree. On the other hand I can understand why the removal is warranted, there might be some other unseen bugs in WSL1 and building a complete syscall emulation of Linux is beyond the scope of this project.

**Comment by fanquake** [comment]
I agree that we could probably just remove support for WSL1 here.

**Review by ghost — APPROVED** [review]
ACK https://github.com/bitcoin/bitcoin/pull/25898/commits/7566cd63c8ec6e1009f18697c8076d5c9380f239

nit: can fix lint error (whitespace)

**Comment by fanquake** [comment]
> nit: can fix lint error (whitespace)

That isn't a nit. It needs fixing before merge.

The PR title and description need to be updated to reflect the new changes.

**Comment by sinetek** [comment]
> > nit: can fix lint error (whitespace)
> 
> That isn't a nit. It needs fixing before merge.
> 
> The PR title and description need to be updated to reflect the new changes.

That's a cute way to enforce spaces. Updated.

**Comment by luke-jr** [comment]
Considering IBD bottleneck is often I/O, and Microsoft's documentation says WSL1 is better for that, I think someone should do some benchmarks before we drop WSL1 support.

**Review by ghost — APPROVED** [review]
reACK https://github.com/bitcoin/bitcoin/pull/25898/commits/2e803455e796e15d99648f8e280c3decc1cf13fb

**Comment by MarcoFalke** [comment]
Please revert to the previous commit, we usually do not allow merge commits in the commit history unless there is a reason to use them.

**Comment by sinetek** [comment]
> Please revert to the previous commit, we usually do not allow merge commits in the commit history unless there is a reason to use them.

Thanks for alerting me. That was not intentional and fixed.

**Review by ghost — APPROVED** [review]
ACK https://github.com/bitcoin/bitcoin/pull/25898/commits/5669afb80e350027705dc378d2ab16232567511a

**Comment by hebasto** [comment]
Is reverting of the original e8fa0a3d2025509fcddc59fc618e91371542cf87 commit cleaner?

Maybe it's worth updating `doc/build-windows.md`: https://github.com/bitcoin/bitcoin/blob/e2bfd41f832dc7c7be6f17e928352f0eb2865f66/doc/build-windows.md#L9 as well, I mean, s/WSL/WSL 2/?

**Review by fanquake — APPROVED** [review]
ACK 5669afb80e350027705dc378d2ab16232567511a - seems ok as-is.

**Pull request merged**
