### PR TITLE
Fix compiler warnings

### PR DESCRIPTION
**Pull request by rebroad**

### CODE REVIEW

**Comment by fanquake** [comment]
These should be submitted to the [bitcoin-core leveldb repo](https://github.com/bitcoin-core/leveldb).

**Comment by MarcoFalke** [comment]
Right, we can not merge this, as it would "overwrite" the subtree. Please submit upstream: https://github.com/google/leveldb

**Comment by rebroad** [comment]
ah, ok, thanks. have raised https://github.com/bitcoin-core/leveldb/pull/15 - should it go to bitcoin-fork or upstream in that project?

**Comment by rebroad** [comment]
I'm a little confused though as it does seem that these files are in bitcoin also.. should they be in both projects? how are they kept in sync?

**Comment by sipa** [comment]
git subtree.

**Comment by rebroad** [comment]
@sipa I'm still seeing these errors when compiling bitcoin, even though I've PRed the leveldb... how do I stop the old versions of these files from being put in the directory structure please?

**Comment by sipa** [comment]
It's just a copy of the tree. If you want the same changes to show up to
test with, just make the sake changes in the subtree.

**Pull request closed without merging**
