### PR TITLE
wallet: fix segfault by avoiding invalid default-ctored `external_spk_managers` entry

### PR DESCRIPTION
**Pull request by theStack**
Fixes #23321 (bug reported by Josef Vondrlik (josef-v)).

In the method `CWallet::LoadActiveScriptPubKeyMan`, the map `external_spk_managers` (or `internal_spk_managers`, if parameter `internal` is false) is accessed via std::map::operator[], which means that a default-ctored entry is created with a null-pointer as value, if the key doesn't exist.  As soon as this value is dereferenced, a segmentation fault occurs, e.g. in `CWallet::KeypoolCountExternalKeys`.

The bevaviour can be reproduced by the following steps (starting with empty regtest datadir):

```
$ ./src/bitcoind -regtest -daemon
$ ./src/bitcoin-cli -regtest -named createwallet_name=wallet descriptors=true blank=true
$ cat regtest-descriptors.txt
[
  {
    "desc": "tr([e4445899/49'/1'/0']tprv8ZgxMBicQKsPd8jCeBWsYLEoWxbVgzJDatJ7XkwQ6G3uF4FsHuaziHQ5JZAW4K515nj6kVVwPaNWZSMEcR7aFCwL4tQqTcaoprMKTTtm6Zg/1/*)#mr3llm7f",
    "timestamp": 1634652324,
    "active": true,
    "internal": true,
    "range": [
      0,
      999
    ],
    "next": 0
  }
]
$ ./src/bitcoin-cli -regtest importdescriptors "$(cat regtest-descriptors.txt)"
[
  {
    "success": true
  }
]
$ ./src/bitcoin-cli -regtest getwalletinfo
error: timeout on transient error: Could not connect to the server 127.0.0.1:18443 (error code 1 - "EOF reached")
```

### CODE REVIEW

**Comment by achow101** [comment]
Code Review ACK 6911ab95f19d2b1f60f2d0b2f3961fa6639d4f31

**Comment by achow101** [comment]
> Does this need backport to earlier than 22.x?

No, this is new in 22.x

**Review by lsilva01 — APPROVED** [review]
Tested ACK 6911ab9  on Ubuntu 20.04.
I was able to reproduce the error on the master branch and this PR fixes this.

**Review by instagibbs — APPROVED** [review]
ACK 6911ab95f19d2b1f60f2d0b2f3961fa6639d4f31

**Pull request merged**
