### PR TITLE
[0.17] Backports

### PR DESCRIPTION
**Pull request by maflcko**

### CODE REVIEW

**Comment by fanquake** [comment]
Could include #14298

**Comment by fanquake** [comment]
Would suggest also adding #14011 cc @ryanofsky

**Comment by fanquake** [comment]
Travis output:
```
script/sign.cpp: In function ‘bool CreateSig(const BaseSignatureCreator&, SignatureData&, const SigningProvider&, std::vector<unsigned char>&, const CPubKey&, const CScript&, SigVersion)’:
script/sign.cpp:80:5: error: ‘KeyOriginInfo’ was not declared in this scope
     KeyOriginInfo info;
     ^~~~~~~~~~~~~
script/sign.cpp:81:18: error: ‘const class SigningProvider’ has no member named ‘GetKeyOrigin’; did you mean ‘GetKey’?
     if (provider.GetKeyOrigin(keyid, info)) {
                  ^~~~~~~~~~~~
                  GetKey
script/sign.cpp:81:38: error: ‘info’ was not declared in this scope
     if (provider.GetKeyOrigin(keyid, info)) {
                                      ^~~~
script/sign.cpp:81:38: note: suggested alternative: ‘int’
     if (provider.GetKeyOrigin(keyid, info)) {
                                      ^~~~
                                      int
```

**Comment by luke-jr** [comment]
#14298 is not a bug fix...

**Comment by MarcoFalke** [comment]
Added commits that fix issues with `valgrind` running `bench_bitcoin` and `test_bitcoin`.

**Comment by MarcoFalke** [comment]
Rebased on current 0.17 branch. Note that GitHub shows the commits in a different order.

**Review by ryanofsky — APPROVED** [review]
utACK 542651cfb408d10e6eaaa24ad985c95e51f88f75. Verified using the script in https://github.com/bitcoin/bitcoin/pull/11592#pullrequestreview-73922693 that commits in this PR were cherry-picked correctly, and tagged with the right PR numbers, and merged previously to master.

(Two commits bb9069555120474a53caf55027c2bdc1d4cf383c and fb9ad043f8b82c7d507ee729121658073eb894f8 had minor conflicts that appeared to be resolved correctly, and one commit 542651cfb408d10e6eaaa24ad985c95e51f88f75 was not a cherry-pick.)

**Pull request merged**
