### PR TITLE
Use `libc++` headers from macOS SDK instead of from clang

### PR DESCRIPTION
**Pull request by dongcarl**
~~Based on #16392~~ **Update:** Base PR has been merged.

Why this is useful: Previously, we were using [the `libc++` headers copied from the clang package we downloaded from llvm.org](https://github.com/bitcoin/bitcoin/pull/18072/commits/8e888983b7ced7a53d21272085a74558b20d7821). This is suboptimal as our goal is to have a toolchain that can target macOS, which (in Xcode.app) has its own set of `libc++` headers that can [differ from those of the clang package](https://gist.github.com/fanquake/9315a02416f56d1545dfef7f9c75bc45). It seems to me that given our goal, it is better to use what Apple intends, and not rely on upstream `clang` <-> Apple `clang` compatibility.

-----

This requires a regeneration of the macOS SDK, I apologize that this didn't make it into #16392, please follow the updated instructions here: https://github.com/bitcoin/bitcoin/pull/18072/commits/8e8fadff59c48b33ffbdac14acd52f469954307d?short_path=9de36be#diff-9de36befe13356841c2699ee0eff4a0a (I'm linking to the Markdown diff so that people who need to regenerate the macOS SDK can see the difference in procedure from before)

### CODE REVIEW

**Comment by sipa** [comment]
Can you explain why this is useful?

**Comment by dongcarl** [comment]
@sipa I apologize for not including that, it is now included in the PR description!

**Comment by Sjors** [comment]
Travis linter is annoyed by a few things: https://travis-ci.org/github/bitcoin/bitcoin/jobs/646483250#L370

It wasn't super clear you have to point it to `Xcode.app`, not the directory. Otherwise I get this error:

```
found Xcode: /Users/sjors/dev/sdk-apple
Xcode (or this script) is out of date
```

The script produces a 97M file:
```
8d06240bce91b55cc5d278a90f4208aa4958d86bc14c3f2b70de2fdaa6b13c03  MacOSX10.14.sdk.tar.gz
````

**Comment by dongcarl** [comment]
@Sjors You have my gratitude for the testing! After thinking on this some more, I think something like #18674 might be a cleaner, less error-prone way forward. Will close this once I have a PR up!

**Pull request closed without merging**
