### PR TITLE
Trivial: Fix typos in various files

### PR DESCRIPTION
**Pull request by leijurv**
Changed "replacable" to "replaceable" for consistency. "replacable" only appears in this one place, while "replaceable" appears elsewhere in various files (and is also the correct spelling).

The standard spelling seems to be "serialize" and "optimize", not "serialise" and "optimise"

```
grep -r "optimization" src/ | wc -l
     16
grep -r "optimisation" src/ | wc -l
       1

grep -r "serialize" src/ | wc -l
     310
grep -r "serialise" src/ | wc -l
       1
```

### CODE REVIEW

**Comment by paveljanik** [comment]
Please close #8506 and #8507, integrate them here. Thanks.

**Comment by leijurv** [comment]
All right, one minute

**Comment by leijurv** [comment]
Done

**Comment by leijurv** [comment]
Note that "don't" is also misspelled in `/src/leveldb/util/env_win.cc` but I was unsure about editing leveldb

**Comment by leijurv** [comment]
The standard spelling seems to be "reorganiz-", not "reorganis-"

```
grep -r "reorganiz" src/ | wc -l
       11
grep -r "reorganis" src/ | wc -l
      2
```

**Comment by leijurv** [comment]
Not interested in an extremely long title listing every single file, that's what the "Files changed" tab is for

**Comment by leijurv** [comment]
Done with finding typos with aspell for now

**Comment by MarcoFalke** [comment]
Please squash your commits according to https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#squashing-commits

**Comment by leijurv** [comment]
All right

**Comment by jonasschnelli** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/8505/commits/1aacfc2da521a8e0d718e9ac561d9b2d7916eb0b

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/8505/commits/1aacfc2da521a8e0d718e9ac561d9b2d7916eb0b

**Comment by MarcoFalke** [comment]
utACK 1aacfc2da521a8e0d718e9ac561d9b2d7916eb0b

**Comment by mcccs** [comment]
ACK

**Comment by rebroad** [comment]
Is it specified anywhere whether the project should establish a standard/style of US or International English?

**Comment by MarcoFalke** [comment]
No, and I think this is not something we can enforce. Most developers are non-native English speakers, so telling everyone that they use the wrong English would be distracting.

**Comment by MarcoFalke** [comment]
Though, having a non-enforced guideline, such as "Use this style of English" wouldn't hurt.

**Pull request merged**
