### PR TITLE
kernel: remove `script/solver.{h,cpp}` from kernel headers

### PR DESCRIPTION
**Pull request by darosior**
This removes the non consensus-critical `solver.h` header from the kernel headers by stripping out the `TxoutType` enum (needed by `policy.h`) into its own header.

It's only a small gain but it's also pretty straightforward. Figured i'd PR it directly to gather whether people think that's worth it.

### CODE REVIEW

**Comment by fanquake** [comment]
cc @theuni @TheCharlatan

**Review by sedited — APPROVED** [review]
ACK 84024b44e25507f5ef10e03057510383c47af332

Thank for your contribution!

I don't think we have to hunt down all the non-consensus code in the kernel headers at this time though. As long as it is still unclear what the API is supposed to be in the end, the focus should be on removing platform-specific or external dependency headers. For easy wins such as here, the benefit is clear though: Less unrelated code in the kernel lib means one fewer thing to handle in the future of the kernel library.

**Comment by darosior** [comment]
Yeah, something else i considered is how they may be re-introduced in the future. It may be reasonable to expect reintroduction of external headers back into kernel to be caught during review, but these small things may slip through more easily.

**Review by maflcko — CHANGES_REQUESTED** [review]
I don't understand this change. `solver.o` is still linked into `libbitcoinkernel_la`

**Comment by TheCharlatan** [comment]
> As for removing solver.h from the public headers: I think that's a bit too early with no linter in place to check it, no?

We don't have a linter in place for the other headers that were recently removed either though. @cfields has a commit for manually defining the list of includes for `bitcoin-chainstate`. But like I said, I don't think we should be looking for more of these right now, but it doesn't hurt to split this up either.

**Comment by TheCharlatan** [comment]
> What if a user wants to use the solver and it has to be re-added to libbitcoinkernel later? Seems odd to rule that out now, no?

There is nothing here that precludes the solver not becoming part of the API later on.

**Comment by darosior** [comment]
My bad for the PR description, it was from an earlier (attempted) version of this branch.

**Comment by darosior** [comment]
I'm going to close this. I was not sure about opening it in the first place, looks like review time is better spent elsewhere.

**Pull request closed without merging**
