### PR TITLE
[0.17] depends: fix qt determinism

### PR DESCRIPTION
**Pull request by maflcko**
Backport for rc2

### CODE REVIEW

**Comment by fanquake** [comment]
How do you see why appveyor is failing here, and how do you restart a build?

**Comment by MarcoFalke** [comment]
@fanquake I am not aware of a way to restart the build, but the appveyor is only meant for master anyway. Also, it doesn't build from depends.

**Comment by fanquake** [comment]
utACK 48c8459

**Comment by ken2812221** [comment]
Tested ACK 48c8459

**Pull request merged**
