### PR TITLE
0.15: Backports

### PR DESCRIPTION
**Pull request by maflcko**

### CODE REVIEW

**Review by ryanofsky — COMMENTED** [review]
utACK 6666d9524148931d261aed1be6700562876e8116

**Comment by laanwj** [comment]
utACK, though wouldn't we in the long run be better off backporting the function name change to the 0.15 branch wholesale?

**Comment by TheBlueMatt** [comment]
Given we want to use the 0.15 branch for segwit-wallet, that seems like a wise decision to me.

**Comment by MarcoFalke** [comment]
Right, #11376 (0.15.1) needs it as well.

**Comment by ryanofsky** [comment]
Seems fine, but if you wanted a more minimal change you could just add:

```python
assert_raises_rpc_error = assert_raises_jsonrpc
```

to the bottom of util.py to add an alias for the new function.

**Comment by morcos** [comment]
PR's backported here:
#10853
#11376 
#11492 
#11476 
#11472 
#10357 (missing at the moment)
#11458 
57edc0b0 from #11456 
#10756 
#11490 
#11568 
#11578
#11531 
#11560 (TBD)
#11593 (TBD)
#11100 (TBD)

**Comment by MarcoFalke** [comment]
@morcos missing #11326 😛

**Review by morcos — APPROVED** [review]
utACK 8195cb0
Did not thoroughly vet each change, but backported changes myself and verified conflict resolution.

**Review by ryanofsky — COMMENTED** [review]
utACK 8195cb0d7fc4f8699b35aff7a43ed2fb3013608c. I verified that the cherry-pick commits were tagged with the right PR numbers and were previously merged to master, and I confirmed that all the merge conflict resolutions and diffs after cherry-picking looked good.

Used a little bash script to help with this

```sh
BRANCH=remotes/origin/0.15
BACKPORT=11592

git reset --hard
git checkout $BRANCH
for commit in $(git rev-list --reverse --topo-order $BRANCH..remotes/origin/pull/$BACKPORT/head); do
    pr=$(git log -n1 --pretty=format:%B "$commit" | sed -n 's/Github-Pull: #//p')
    orig=$(git log -n1 --pretty=format:%B "$commit" | sed -n 's/Rebased-From: //p')
    echo "- Commit $commit orig $orig pr $pr"
    if [ -z "$pr" ]; then
        # Commit is not from a pr, just cherry pick and add REVIEWME tag
        git cherry-pick "$commit" || exit 1
        GIT_EDITOR="sed -i '1 s/.*/REVIEWME\n\n&/'" git commit --amend
        continue
    fi
    if ! git -c rerere.enabled=false cherry-pick $orig > /dev/null; then
        EDITOR=true git commit -a
    fi
    if ! git diff --quiet "HEAD..$commit"; then
        git read-tree "$commit"
        git commit -m "REVIEWME from $commit orig $orig pr $pr"
        while ! git reset --hard; do sleep 1; done
    fi
    if ! grep -q "$orig" <(git rev-list $BRANCH..remotes/origin/pull/$pr/head); then
        echo "Error: Commit $orig not found in pr $pr" >&2
        exit 1
    fi
    if [ "$(git merge-base $orig origin/master)" != $orig ]; then
        echo "Error: Commit $orig from pr $pr not found in master" >&2
        exit 1
    fi
done

git log --grep REVIEWME -p $BRANCH..HEAD
```

**Comment by theuni** [comment]
utACK 8195cb0d7fc4f8699b35aff7a43ed2fb3013608c, assuming Travis is happy with it.

**Comment by luke-jr** [comment]
NACK #11100. Removing functionality has no place being snuck into a backport, and benefits nobody. It is only ever a reason for NOT upgrading.

**Comment by gmaxwell** [comment]
@luke-jr your opposition to #11100 was noted on the PR itself.

**Comment by sdaftuar** [comment]
I manually verified the backports here; conflict resolution looks correct to me as well.

ACK 8195cb0d7fc4f8699b35aff7a43ed2fb3013608c

**Comment by MeshCollider** [comment]
utACK https://github.com/bitcoin/bitcoin/commit/8195cb0d7fc4f8699b35aff7a43ed2fb3013608c
Thanks for the script @ryanofsky :)

**Comment by sipa** [comment]
utACK 8195cb0d7fc4f8699b35aff7a43ed2fb3013608c, looked over the list of backported PRs, and verified using @ryanofsky's script.

**Pull request merged**
