### PR TITLE
Remove declaration of unused method: void UpdatedTransaction(const uint256 &)

### PR DESCRIPTION
**Pull request by practicalswift**
Remove declaration of unused method: `void UpdatedTransaction(const uint256 &)`

Removed in 9fececb2cbabc52cc375b84bf840fac018cc8121.

### CODE REVIEW

**Comment by practicalswift** [comment]
Friendly ping @TheBlueMatt :-)

**Comment by TheBlueMatt** [comment]
utACK e061d8d7abb66c234786ea1c855d4cbb1b9b22ef

**Comment by sipa** [comment]
Obvious utACK e061d8d7abb66c234786ea1c855d4cbb1b9b22ef

**Comment by fanquake** [comment]
utACK e061d8d

**Comment by paveljanik** [comment]
ACK e061d8d

**Comment by MarcoFalke** [comment]
utACK e061d8d

**Pull request merged**
