### PR TITLE
docs: update /rest/chaininfo doc referring to RPC help

### PR DESCRIPTION
**Pull request by brunoerg**
Internally, `/rest/chaininfo` gets the infos from `getblockchaininfo` and I just realized the documentation of it in `REST-interface.md` is outdated compared to the `getblockchaininfo` RPC one. This PR removes the documentation of the fields and adds a reference to the RPC help.

### CODE REVIEW

**Comment by laanwj** [comment]
Concept ACK. Though, if it's the same, at some point we might as well say 'see getblockchaininfo RPC' to avoid duplicating information that may out of date soon again.

**Comment by brunoerg** [comment]
> at some point we might as well say 'see bitcoin-cli help getblockchaininfo' to avoid duplicating information that may out of date soon again.

I agree


Btw, @laanwj do you think we should say in developer-notes to check REST doc (and other ones) when changing a RPC command?

**Comment by jonatack** [comment]
Concept ACK.

> we might as well say 'see bitcoin-cli help getblockchaininfo' to avoid duplicating information that may out of date soon again.

Agree, and it looks like getblockchaininfo will be updated soon for a deprecation. Maybe something like the following diff:

<details><summary>diff</summary><p>

```diff
diff --git a/doc/REST-interface.md b/doc/REST-interface.md
index c359725faf..f11624fd28 100644
--- a/doc/REST-interface.md
+++ b/doc/REST-interface.md
@@ -82,17 +82,7 @@ Given a height: returns hash of block in best-block-chain at height provided.
 
 Returns various state info regarding block chain processing.
 Only supports JSON as output format.
-* chain : (string) current network name (main, test, signet, regtest)
-* blocks : (numeric) the current number of blocks processed in the server
-* headers : (numeric) the current number of headers we have validated
-* bestblockhash : (string) the hash of the currently best block
-* difficulty : (numeric) the current difficulty
-* mediantime : (numeric) the median time of the 11 blocks before the most recent block on the blockchain
-* verificationprogress : (numeric) estimate of verification progress [0..1]
-* chainwork : (string) total amount of work in active chain, in hexadecimal
-* pruned : (boolean) if the blocks are subject to pruning
-* pruneheight : (numeric) highest block available
-* softforks : (array) status of softforks in progress
+Refer to the `getblockchaininfo` RPC help for details.
 
 #### Query UTXO set
 `GET /rest/getutxos/<checkmempool>/<txid>-<n>/<txid>-<n>/.../<txid>-<n>.<bin|hex|json>`
@@ -127,13 +117,13 @@ $ curl localhost:18332/rest/getutxos/checkmempool/b2cdfd7b89def827ff8af7cd9bff76
 #### Memory pool
 `GET /rest/mempool/info.json`
 
-Returns various information about the TX mempool.
+Returns various information about the transaction mempool.
 Only supports JSON as output format.
-Refer to the `getmempoolinfo` RPC for documentation of the fields.
+Refer to the `getmempoolinfo` RPC help for details.
 
 `GET /rest/mempool/contents.json`
 
-Returns transactions in the TX mempool.
+Returns the transactions in the mempool.
 Only supports JSON as output format.
```
</p></details>

**Comment by brunoerg** [comment]
Thanks, @laanwj and @jonatack. Just updated this PR (and its description) to remove the documentation of the fields and add a reference to the RPC help.

**Review by jonatack — APPROVED** [review]
ACK 1d95b5c78368575c8885a5bf659cdb4d6261f124

**Pull request merged**
