### PR TITLE
[Wallet] Improve Wallet encapsulation

### PR DESCRIPTION
**Pull request by pstratem**
Improvements to the CWallet API which can be made without a negative performance impact.

### CODE REVIEW

**Comment by dcousens** [comment]
utACK 380498a

**Comment by jonasschnelli** [comment]
utACK 380498aba4f6aebe53a8241f163e3c7fe424b7e0

**Comment by MarcoFalke** [comment]
utACK 380498a

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/commit/380498aba4f6aebe53a8241f163e3c7fe424b7e0

**Comment by arowser** [comment]
Can one of the admins verify this patch?

**Comment by sipa** [comment]
ACK, Confirmed move-only ecb9741ec3067f67f595126869d0200c62064bbd and 380498aba4f6aebe53a8241f163e3c7fe424b7e0.

**Pull request merged**
