### PR TITLE
qt, refactor: Remove never used default parameter

### PR DESCRIPTION
**Pull request by hebasto**
In `BitcoinGUI::message()` slot the `bool* ret = nullptr` parameter is never used.

This PR removes it and simplifies connections syntax by replacing lambdas with the `&BitcoinGUI::message` slot.

### CODE REVIEW

**Comment by promag** [comment]
Concept ACK, when was the last usage dropped?

**Comment by Empact** [comment]
I believe the use was removed in: 35ecf854c084c248ad640c6af030a9d1ed726c47 but haven't built the old code to confirm.

**Comment by Empact** [comment]
Code review ACK https://github.com/bitcoin/bitcoin/pull/17943/commits/1a53b0da60097cd7fd423c519f01ceca0fd0aa14

**Comment by Sjors** [comment]
Tested ACK 1a53b0da60097cd7fd423c519f01ceca0fd0aa14

You see messages in action by e.g. feeding a malformed BIP20 URI: `src/qt/bitcoin-qt -regtest bitcoin://bcrt1q`

**Comment by hebasto** [comment]
Sorry, It seems I broke `ThreadSafeMessageBox()` ((

`bool* ret` actually is used here:
https://github.com/bitcoin/bitcoin/blob/a654626f076a72416a3d354218d7107571d6caaf/src/qt/bitcoingui.cpp#L1368

How it could be reverted?

**Comment by promag** [comment]
Please don't revert, I think the code you referenced is broken.

**Comment by hebasto** [comment]
@fanquake (from IRC):

> It's unclear from your comments what is supposedly broken or not.

```
$ ./src/qt/bitcoin-qt 
: You need to rebuild the database using -reindex to go back to unpruned mode.  This will redownload the entire blockchain.
Please restart with -reindex or -reindex-chainstate to recover.
bitcoin-qt: qt/bitcoingui.cpp:1369: bool ThreadSafeMessageBox(BitcoinGUI*, const string&, const string&, unsigned int): Assertion `invoked' failed.
Aborted (core dumped)
```

**Pull request merged**
