### PR TITLE
Suppress some annoying deprecation warnings (OSX)

### PR DESCRIPTION
**Pull request by jonasschnelli**

### CODE REVIEW

**Comment by paveljanik** [comment]
On my building VM based on 10.10.x, it removes two warnings: `daemon` and `LSGetApplicationForInfo`. Maybe there are more warnings removed on newer systems. I always took it as a gentle reminder :-)

ACK https://github.com/bitcoin/bitcoin/pull/9284/commits/2ab8fbbd5b0075b9e6316aaf2405e6b9d97f2311

**Comment by theuni** [comment]
Hmm, I don't think we really want to hide these?

**Comment by jonasschnelli** [comment]
I get at least 100 of those while compiling:
```
In file included from /usr/local/Cellar/protobuf260/2.6.0/include/google/protobuf/stubs/atomicops.h:179:
/usr/local/Cellar/protobuf260/2.6.0/include/google/protobuf/stubs/atomicops_internals_macosx.h:173:9: warning: 
      'OSAtomicCompareAndSwap64Barrier' is deprecated: first deprecated in macOS 10.12 - Use
      std::atomic_compare_exchange_strong() from <atomic> instead [-Wdeprecated-declarations]
    if (OSAtomicCompareAndSwap64Barrier(
        ^
```

**Comment by morcos** [comment]
Hmm..   They are pretty annoying, and I guess we can't just fix them ourselves...

**Comment by jonasschnelli** [comment]
@theuni: We could wrap it in a " if host = darwin"?

**Comment by gmaxwell** [comment]
I don't think we want to blanket disable them even on a single host. If protobuf is doing this can we just wrap the headers it generates with a pragma to disable the warning just there?

**Comment by theuni** [comment]
@gmaxwell Yes, Looks like it still exists in master upstream :\

I think we could probably hack together something like
```c++
#ifdef SOME_MAC_VERSION_MACRO
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
#include "protobuf/foo.h"
#pragma clang diagnostic pop
#endif
```
I'm not sure how possible that is with the generated file, though. I can have a look tomorrow while I'm bored on a plane.

**Comment by laanwj** [comment]
+1 for using #pragma to do this on a case-by-case basis. Don't forget the daemon one if you do.

**Comment by jonasschnelli** [comment]
Thanks for having a look at this @theuni. Hundreds of warnings on OSX 10.12+ defeats the purpose of warning the user. Everyone on OSX will just ignore them because finding the non-OSX-hell-depracation warnings is like finding the needle in a haystack.

**Comment by paveljanik** [comment]
I like the `#pragma` solution!

**Comment by theuni** [comment]
I think there may be a better option here. The includes have a GOOGLE_PROTOBUF_NO_THREAD_SAFETY macro that we can set, assuming we don't need thread-safety in the structures themselves. I assume that's the case?

I didn't have access to the protobuf options while I was looking, but I'd assume there's something that we can add to the .proto to get that defined. I'll take a closer look when I can find some stable internet.

**Comment by laanwj** [comment]
> assuming we don't need thread-safety in the structures themselves

We don't. I didn't even realize there was an option for that.

**Comment by CodeShark** [comment]
utACK

**Comment by theuni** [comment]
I checked the protobuf docs and don't see any easy way to disable this.

@jonasschnelli Could you try the hammer approach of ```./configure CPPFLAGS=-DGOOGLE_PROTOBUF_NO_THREAD_SAFETY``` ? If that works, we can stick it in the appropriate place.

**Comment by jonasschnelli** [comment]
@theuni:
Defining `GOOGLE_PROTOBUF_NO_THREAD_SAFETY` solves the deprecation warnings. But do we want to disable the thread safety on OSX?

There are other deprecation warnings though (leveldb):
```
In file included from ./leveldb/port/port_posix.h:47:
./leveldb/port/atomic_pointer.h:59:3: warning: 'OSMemoryBarrier' is deprecated: first deprecated in macOS 10.12 - Use std::atomic_thread_fence() from <atomic>
      instead [-Wdeprecated-declarations]
  OSMemoryBarrier();
  ^
/usr/include/libkern/OSAtomicDeprecated.h:749:9: note: 'OSMemoryBarrier' has been explicitly marked deprecated here
void    OSMemoryBarrier( void );
        ^
```

**Comment by fanquake** [comment]
The other warnings have been fixed upstream IIRC

**Comment by jonasschnelli** [comment]
Closing for now.

**Pull request closed without merging**
