### PR TITLE
Trivial: Globals: Explicitly pass const CChainParams& to ProcessMessage()

### PR DESCRIPTION
**Pull request by jtimon**
Who wouldn't ACK a trivial +2-3 ?

### CODE REVIEW

**Comment by laanwj** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/7828/commits/bf477bcc794360c145156c9e8f155e0215f70dd3

**Comment by sipa** [comment]
utACK bf477bc

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/7828/commits/bf477bcc794360c145156c9e8f155e0215f70dd3

**Comment by theuni** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/7828/commits/bf477bcc794360c145156c9e8f155e0215f70dd3

**Pull request merged**
