### PR TITLE
Update year to 2018

### PR DESCRIPTION
**Pull request by filips123**
Update year to 2018.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
We have a script to do this for all files: https://github.com/bitcoin/bitcoin/tree/d32528e733f2711b34dbc41fbb2bb0f153bf7e9a/contrib/devtools#copyright_headerpy

**Comment by MeshCollider** [comment]
This gets done at the end of the year doesn't it?

**Comment by randolf** [comment]
NACK.  I noticed that at least 3 source files have a copyright year of 2017 replaced with a new year of 2018, when they should really be extending the year 2017 to a range of "2017-2018."  (Hopefully the devtool script referenced by @MarcoFalke takes this into consideration.)

test/functional/rpc_uptime.py
test/functional/rpc_deprecated.py
test/functional/wallet_resendwallettransactions.py

**Review by randolf — CHANGES_REQUESTED** [review]
I noticed that at least 3 source files have a copyright year of 2017 replaced with a new year of 2018, when they should really be extending the year 2017 to a range of "2017-2018."  (Can you correct this?)

test/functional/rpc_uptime.py
test/functional/rpc_deprecated.py
test/functional/wallet_resendwallettransactions.py

**Comment by filips123** [comment]
I started this script and now all the years are correct.
Should I create a new Pull Request with repaired files?

**Comment by filips123** [comment]
I created new Pull Request #12359 with this script.

**Pull request closed without merging**
