### PR TITLE
depends: bump miniupnpc to 2.2.8

### PR DESCRIPTION
**Pull request by theuni**
Drops two of our patches that have been merged upstream and adjusts the other to deal with recent changes.

Follow-up from #30283. I can't vouch for the upstream changes here.

### CODE REVIEW

**Comment by edilmedeiros** [comment]
Concept ACK.

From the CI output, this has to wait for #30283 to be merged first, right?

**Comment by Sjors** [comment]
cc @laanwj

**Comment by theuni** [comment]
Marked as draft #30283 is merged.

**Comment by fanquake** [comment]
> Marked as draft until https://github.com/bitcoin/bitcoin/pull/30283 is merged.

Can rebase / undraft this now.

**Comment by TheCharlatan** [comment]
Guix builds (aarch64):
```
7f69ccde68d336bee6141d2cbcec8046332dedc908ba428ac08299daeb6a5d41  guix-build-545bb6c96080/output/aarch64-linux-gnu/SHA256SUMS.part
e843d7b6003da9f6259da41019f328af337858a45e4197ee9c5050984dc9e255  guix-build-545bb6c96080/output/aarch64-linux-gnu/bitcoin-545bb6c96080-aarch64-linux-gnu-debug.tar.gz
1fdc9afbf83b2e8ce19d8a2c5cd080d87172ad02c4ce41036962f1bf675a415a  guix-build-545bb6c96080/output/aarch64-linux-gnu/bitcoin-545bb6c96080-aarch64-linux-gnu.tar.gz
400f2e70a689b6495af97def189cdf8b9d8dd740f5c45e8b851a4ff0469fc984  guix-build-545bb6c96080/output/arm-linux-gnueabihf/SHA256SUMS.part
e4d13ae0f2125606fdf456f7d62af25c9bec797f00c00e74c1236336d1174a67  guix-build-545bb6c96080/output/arm-linux-gnueabihf/bitcoin-545bb6c96080-arm-linux-gnueabihf-debug.tar.gz
c2370ff07929393f6ae735a12a3e2134e18b20acc7a534410be3da1461fda51a  guix-build-545bb6c96080/output/arm-linux-gnueabihf/bitcoin-545bb6c96080-arm-linux-gnueabihf.tar.gz
82128f74a03ccd39ba027c7f608acbfbc327373d91a770eb58c883c1caf88c07  guix-build-545bb6c96080/output/arm64-apple-darwin/SHA256SUMS.part
34a8894873b22acd65c2fdef4b80f8bbf9a930c651ed6d6307b8a43a2a0878c3  guix-build-545bb6c96080/output/arm64-apple-darwin/bitcoin-545bb6c96080-arm64-apple-darwin-unsigned.tar.gz
04bc2a9d4ec1a2272687b0dee704ad0bc54944a3448b14e2a20af223a9050dc5  guix-build-545bb6c96080/output/arm64-apple-darwin/bitcoin-545bb6c96080-arm64-apple-darwin-unsigned.zip
6db77ac9bf538d73038c8268af95fbb73d63c2045d174d4af54462fa61c42ec6  guix-build-545bb6c96080/output/arm64-apple-darwin/bitcoin-545bb6c96080-arm64-apple-darwin.tar.gz
ada87843bc15e3e8ebba7ab3018bd2ea75d884f310acbd3dc9b6a01d5175be4c  guix-build-545bb6c96080/output/dist-archive/bitcoin-545bb6c96080.tar.gz
9affe451fbff49501cdc1fa1c076e110f8817654ce74edf36acbee401b2be840  guix-build-545bb6c96080/output/powerpc64-linux-gnu/SHA256SUMS.part
0dd5ff185fc27cf160a83b9e8bda93c9a975425d97312127161bec14011149b4  guix-build-545bb6c96080/output/powerpc64-linux-gnu/bitcoin-545bb6c96080-powerpc64-linux-gnu-debug.tar.gz
68e380f13ca9a00a38b8a8046b3a1064f0c7d18801ece1bde26864c7f50de94c  guix-build-545bb6c96080/output/powerpc64-linux-gnu/bitcoin-545bb6c96080-powerpc64-linux-gnu.tar.gz
8480b2713395a42fa898ce9293c2b1d2cfd7196e18010be7ed30753e095c1c3e  guix-build-545bb6c96080/output/riscv64-linux-gnu/SHA256SUMS.part
62446cea05d22dcad8f62475d3bb7220fa6c3423b294d8c9071f64fb11d107d1  guix-build-545bb6c96080/output/riscv64-linux-gnu/bitcoin-545bb6c96080-riscv64-linux-gnu-debug.tar.gz
9c23c77c50b1acacf90c4303e7b1fae4f6fe406bc00cea808248f2403def0219  guix-build-545bb6c96080/output/riscv64-linux-gnu/bitcoin-545bb6c96080-riscv64-linux-gnu.tar.gz
685051ef7ba4793f90a66c5858266a309d937913171a3da0afc7335880d0dacc  guix-build-545bb6c96080/output/x86_64-apple-darwin/SHA256SUMS.part
9746a003bbcebb41d3a7cb365850f23b9364d5b3b25fda149a76437a5eb7e1e4  guix-build-545bb6c96080/output/x86_64-apple-darwin/bitcoin-545bb6c96080-x86_64-apple-darwin-unsigned.tar.gz
ba77822a7b9f6082a5b5b41bfed51fe84e771b8e9869cb9a32421c263120796c  guix-build-545bb6c96080/output/x86_64-apple-darwin/bitcoin-545bb6c96080-x86_64-apple-darwin-unsigned.zip
37fceeab62ead081699374400bf37442ff7f5f5a0712c67153dd436775cecab9  guix-build-545bb6c96080/output/x86_64-apple-darwin/bitcoin-545bb6c96080-x86_64-apple-darwin.tar.gz
6ee480721d582179a44487135160e0ce43cdfcbcddfd390d1fdb1cc6798628f5  guix-build-545bb6c96080/output/x86_64-linux-gnu/SHA256SUMS.part
f30c17ffdaea58fb13180b53a676f7bc459f8ee473aa23af4e39b8fa1907e22e  guix-build-545bb6c96080/output/x86_64-linux-gnu/bitcoin-545bb6c96080-x86_64-linux-gnu-debug.tar.gz
0f0993cb2ad2eae0f2e843b47678969c290752f4bf082d2444e35dda87c4e86b  guix-build-545bb6c96080/output/x86_64-linux-gnu/bitcoin-545bb6c96080-x86_64-linux-gnu.tar.gz
c45f789cb5400738afb0760e36bb02f75e048bb4e680d073661d56f5597194d8  guix-build-545bb6c96080/output/x86_64-w64-mingw32/SHA256SUMS.part
765b5e54a254fbf22e8e54753cfa46029940596daec291394d055232382005b4  guix-build-545bb6c96080/output/x86_64-w64-mingw32/bitcoin-545bb6c96080-win64-debug.zip
551285d885d75e4d263bc12517a941fca4601f7fd9dd034adc7eea6c0ae33268  guix-build-545bb6c96080/output/x86_64-w64-mingw32/bitcoin-545bb6c96080-win64-setup-unsigned.exe
d59df500857d2ee8a1d08a9780162192f19dff2d4585dc827575c6a9fba274ae  guix-build-545bb6c96080/output/x86_64-w64-mingw32/bitcoin-545bb6c96080-win64-unsigned.tar.gz
49ad4a2568e699ac4a00e472926e77fc1e23cf66c4ce511ce70d4149a1204ac4  guix-build-545bb6c96080/output/x86_64-w64-mingw32/bitcoin-545bb6c96080-win64.zip
```

**Comment by Sjors** [comment]
tACK 545bb6c96080

I looked at the diff between the packaged 2.2.7 and 2.2.8. There's a `MINIUPNPC_API_VERSION` bump from 17 to 18, which was addressed in #30283. I also see our dropped patches reflected in the diff. Didn't study the rest of the changes.

Tested on macOS 14.5 with `-upnp=1 -natpmp=0`.

When I turn UPnP support off in the router:

```
[mapport] No valid UPnP IGDs found
```

When I turn it on:

```
2024-06-21T12:55:33Z [mapport] UPnP: ExternalIPAddress = x.x.x.x
2024-06-21T12:55:33Z [mapport] AddLocal(x.x.x.x:x,3)
2024-06-21T12:55:33Z [mapport] UPnP Port Mapping successful.
```

My OPNSense router identifies this as `Bitcoin Core v27.99.0-g545bb6c960800760512634a7227337fa779ea944`. Same behavior as with the v27.0 release binary. 

So I'm not sure what `depends/patches/miniupnpc/dont_leak_info.patch` is supposed to achieve.

Guix hashes:

```
7f69ccde68d336bee6141d2cbcec8046332dedc908ba428ac08299daeb6a5d41  guix-build-545bb6c96080/output/aarch64-linux-gnu/SHA256SUMS.part
e843d7b6003da9f6259da41019f328af337858a45e4197ee9c5050984dc9e255  guix-build-545bb6c96080/output/aarch64-linux-gnu/bitcoin-545bb6c96080-aarch64-linux-gnu-debug.tar.gz
1fdc9afbf83b2e8ce19d8a2c5cd080d87172ad02c4ce41036962f1bf675a415a  guix-build-545bb6c96080/output/aarch64-linux-gnu/bitcoin-545bb6c96080-aarch64-linux-gnu.tar.gz
400f2e70a689b6495af97def189cdf8b9d8dd740f5c45e8b851a4ff0469fc984  guix-build-545bb6c96080/output/arm-linux-gnueabihf/SHA256SUMS.part
e4d13ae0f2125606fdf456f7d62af25c9bec797f00c00e74c1236336d1174a67  guix-build-545bb6c96080/output/arm-linux-gnueabihf/bitcoin-545bb6c96080-arm-linux-gnueabihf-debug.tar.gz
c2370ff07929393f6ae735a12a3e2134e18b20acc7a534410be3da1461fda51a  guix-build-545bb6c96080/output/arm-linux-gnueabihf/bitcoin-545bb6c96080-arm-linux-gnueabihf.tar.gz
82128f74a03ccd39ba027c7f608acbfbc327373d91a770eb58c883c1caf88c07  guix-build-545bb6c96080/output/arm64-apple-darwin/SHA256SUMS.part
34a8894873b22acd65c2fdef4b80f8bbf9a930c651ed6d6307b8a43a2a0878c3  guix-build-545bb6c96080/output/arm64-apple-darwin/bitcoin-545bb6c96080-arm64-apple-darwin-unsigned.tar.gz
04bc2a9d4ec1a2272687b0dee704ad0bc54944a3448b14e2a20af223a9050dc5  guix-build-545bb6c96080/output/arm64-apple-darwin/bitcoin-545bb6c96080-arm64-apple-darwin-unsigned.zip
6db77ac9bf538d73038c8268af95fbb73d63c2045d174d4af54462fa61c42ec6  guix-build-545bb6c96080/output/arm64-apple-darwin/bitcoin-545bb6c96080-arm64-apple-darwin.tar.gz
ada87843bc15e3e8ebba7ab3018bd2ea75d884f310acbd3dc9b6a01d5175be4c  guix-build-545bb6c96080/output/dist-archive/bitcoin-545bb6c96080.tar.gz
9affe451fbff49501cdc1fa1c076e110f8817654ce74edf36acbee401b2be840  guix-build-545bb6c96080/output/powerpc64-linux-gnu/SHA256SUMS.part
0dd5ff185fc27cf160a83b9e8bda93c9a975425d97312127161bec14011149b4  guix-build-545bb6c96080/output/powerpc64-linux-gnu/bitcoin-545bb6c96080-powerpc64-linux-gnu-debug.tar.gz
68e380f13ca9a00a38b8a8046b3a1064f0c7d18801ece1bde26864c7f50de94c  guix-build-545bb6c96080/output/powerpc64-linux-gnu/bitcoin-545bb6c96080-powerpc64-linux-gnu.tar.gz
8480b2713395a42fa898ce9293c2b1d2cfd7196e18010be7ed30753e095c1c3e  guix-build-545bb6c96080/output/riscv64-linux-gnu/SHA256SUMS.part
62446cea05d22dcad8f62475d3bb7220fa6c3423b294d8c9071f64fb11d107d1  guix-build-545bb6c96080/output/riscv64-linux-gnu/bitcoin-545bb6c96080-riscv64-linux-gnu-debug.tar.gz
9c23c77c50b1acacf90c4303e7b1fae4f6fe406bc00cea808248f2403def0219  guix-build-545bb6c96080/output/riscv64-linux-gnu/bitcoin-545bb6c96080-riscv64-linux-gnu.tar.gz
685051ef7ba4793f90a66c5858266a309d937913171a3da0afc7335880d0dacc  guix-build-545bb6c96080/output/x86_64-apple-darwin/SHA256SUMS.part
9746a003bbcebb41d3a7cb365850f23b9364d5b3b25fda149a76437a5eb7e1e4  guix-build-545bb6c96080/output/x86_64-apple-darwin/bitcoin-545bb6c96080-x86_64-apple-darwin-unsigned.tar.gz
ba77822a7b9f6082a5b5b41bfed51fe84e771b8e9869cb9a32421c263120796c  guix-build-545bb6c96080/output/x86_64-apple-darwin/bitcoin-545bb6c96080-x86_64-apple-darwin-unsigned.zip
37fceeab62ead081699374400bf37442ff7f5f5a0712c67153dd436775cecab9  guix-build-545bb6c96080/output/x86_64-apple-darwin/bitcoin-545bb6c96080-x86_64-apple-darwin.tar.gz
6ee480721d582179a44487135160e0ce43cdfcbcddfd390d1fdb1cc6798628f5  guix-build-545bb6c96080/output/x86_64-linux-gnu/SHA256SUMS.part
f30c17ffdaea58fb13180b53a676f7bc459f8ee473aa23af4e39b8fa1907e22e  guix-build-545bb6c96080/output/x86_64-linux-gnu/bitcoin-545bb6c96080-x86_64-linux-gnu-debug.tar.gz
0f0993cb2ad2eae0f2e843b47678969c290752f4bf082d2444e35dda87c4e86b  guix-build-545bb6c96080/output/x86_64-linux-gnu/bitcoin-545bb6c96080-x86_64-linux-gnu.tar.gz
c45f789cb5400738afb0760e36bb02f75e048bb4e680d073661d56f5597194d8  guix-build-545bb6c96080/output/x86_64-w64-mingw32/SHA256SUMS.part
765b5e54a254fbf22e8e54753cfa46029940596daec291394d055232382005b4  guix-build-545bb6c96080/output/x86_64-w64-mingw32/bitcoin-545bb6c96080-win64-debug.zip
551285d885d75e4d263bc12517a941fca4601f7fd9dd034adc7eea6c0ae33268  guix-build-545bb6c96080/output/x86_64-w64-mingw32/bitcoin-545bb6c96080-win64-setup-unsigned.exe
d59df500857d2ee8a1d08a9780162192f19dff2d4585dc827575c6a9fba274ae  guix-build-545bb6c96080/output/x86_64-w64-mingw32/bitcoin-545bb6c96080-win64-unsigned.tar.gz
49ad4a2568e699ac4a00e472926e77fc1e23cf66c4ce511ce70d4149a1204ac4  guix-build-545bb6c96080/output/x86_64-w64-mingw32/bitcoin-545bb6c96080-win64.zip
```

**Comment by edilmedeiros** [comment]
Just curious if this is still relevant after #30043?

**Comment by fanquake** [comment]
> Or probably https://github.com/bitcoin/bitcoin/pull/31130?

If #31130 is merged, then yes, this is no-longer relevant. Drafted for now, given this also needs rebase.

**Comment by fanquake** [comment]
I think #31130 is going to go in for `v29.0`. If that doesn't happen, we can reopen here.

**Comment by laanwj** [comment]
> I think https://github.com/bitcoin/bitcoin/pull/31130 is going to go in for v29.0. If that doesn't happen, we can reopen here.

yes... i dont think i've seen any PR that popular in my time here 😄

**Comment by theuni** [comment]
Woohoo! I like that much better than a bump :)

**Pull request closed without merging**
