### PR TITLE
[Trivial] Update license year range to 2018

### PR DESCRIPTION
**Pull request by ghost**
The same as #9617.

Happy new year! :smiley:

### CODE REVIEW

**Review by dcousens — APPROVED** [review]

**Comment by MarcoFalke** [comment]
utACK c9439e735a6659b59bdcb8cc70342a8fe8c9a9b7

**Comment by MeshCollider** [comment]
Why not squash into #12062?

**Comment by MarcoFalke** [comment]
Probably easier to review, since this was presumably done manual and the other one was done by a script?

**Comment by akx20000a** [comment]
@MarcoFalke That's correct.

**Comment by jonasschnelli** [comment]
utACK c9439e735a6659b59bdcb8cc70342a8fe8c9a9b7

**Pull request merged**
