### PR TITLE
msvc: Fix silent merge conflict between #13926 and #14372

### PR DESCRIPTION
**Pull request by ken2812221**
The bitcoin-wallet.exe would have to link with libsecp256k1 after we build libsecp256k1 in project.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
cc @sipsorcery

**Comment by MarcoFalke** [comment]
tool_wallet seems to pass already: https://ci.appveyor.com/project/DrahtBot/bitcoin/builds/22082489#L129

**Comment by NicolasDorier** [comment]
tACK

**Comment by ken2812221** [comment]
@MarcoFalke I think that MSVC is trying to link with vcpkg's secp256k1 library that is in the cache.

error if we clear the cache: https://ci.appveyor.com/project/ken2812221/bitcoin/builds/22067759

**Comment by sipsorcery** [comment]
tACK bef8fdd6e2293efdaf05f804a8cff69380c8665e.

**Pull request merged**
