### PR TITLE
rpcwallet: Replace boost::optional<T>::emplace with simple assignment of T{}

### LINKED ISSUE #18943: What is the minimum supported version of boost for 0.21.0?
The wallet code uses `Optional::emplace()`, which was only added in boost 1.56, see https://github.com/boostorg/optional/commit/2e583aaf30964afd66c1284aa71d0d8b42fa440d

So for 0.21.0 there are two options:
* Work around `emplace` and keep the minimum boost version below 1.56
* Require boost 1.56

```
wallet/rpcwallet.cpp: In function ‘UniValue listsinceblock(const JSONRPCRequest&)’:
wallet/rpcwallet.cpp:1560:16: error: ‘Optional<int>’ has no member named ‘emplace’
         height.emplace();
                ^
wallet/rpcwallet.cpp:1561:19: error: ‘Optional<int>’ has no member named ‘emplace’
         altheight.emplace();
                   ^

### PR DESCRIPTION
**Pull request by maflcko**
Closes #18943

### CODE REVIEW

**Review by ryanofsky — APPROVED** [review]
Code review ACK fa1f840596554ed264d11ee3b3643bf99eb57eb5 and thanks for using a standalone commit for the fix

**Review by promag — COMMENTED** [review]
Code review ACK fa1f840596554ed264d11ee3b3643bf99eb57eb5.

**Review by hebasto — APPROVED** [review]
ACK fa1f840596554ed264d11ee3b3643bf99eb57eb5, tested on Linux Mint 19.3.

**Comment by laanwj** [comment]
ACK fa1f840596554ed264d11ee3b3643bf99eb57eb5

**Pull request merged**
