### PR TITLE
[qt] Add .clang-format

### PR DESCRIPTION
**Pull request by maflcko**
@jonasschnelli @laanwj Do you think this is useful?

It is pretty much a copy of the existing file with the only diff:

``` diff
--- src/.clang-format
+++ src/qt/.clang-format
@@ -15 +15 @@
-BreakBeforeBraces: Linux
+BreakBeforeBraces: Allman

```

### CODE REVIEW

**Comment by jonasschnelli** [comment]
No real opinion on that. I just think one clang-format file should be enough.

**Comment by paveljanik** [comment]
@jonasschnelli At first, I had the same opinion as you. At the second look, we should start somewhere. Qt/GUI part is more conservative as the rest of the code, so it will be a good start to put and test the clang-format there.

**Comment by MarcoFalke** [comment]
> I just think one clang-format file should be enough.

So we are not going to keep the current formatting in `/qt` and `/qt` is going to accept the formatting of core?

**Comment by laanwj** [comment]
Due to the undesirability of breaking patches I'm not going to go along with any clang-reformat of the code at large. It's not worth spending too much time on this, there are much larger concerns.

It may make sense to add this for new code though. No strong opinion for or against adding this particular file.

**Comment by MarcoFalke** [comment]
> No strong opinion for or against adding this particular file.

I think everyone is ok with either option. I'd just prefer to know what style is targeted for new code or what I should advise others to do in case they ask for feedback. No need to have a lengthy discussion about this, just express your decision by merging/closing this pull.

**Comment by laanwj** [comment]
I think the best option is to target one style only for new code. Anything else is too much unnecessary complication for contributors.

However when adding code to current files it makes sense to use the style used there.

**Comment by MarcoFalke** [comment]
Ok, great. Then this pull can be closed, I guess.

**Pull request closed without merging**
