### PR TITLE
net: 0.19 seeds update

### PR DESCRIPTION
**Pull request by laanwj**
- contrib: Improve makeseeds script  
- net: 0.19 hardcoded seeds update

Sources: 
- http://bitcoin.sipa.be/seeds.txt.gz (Sipa)
- https://github.com/bitcoin/bitcoin/files/3671913/dnsseed.dump.tar.gz (Sjors)

Output:
```
Initial: IPv4 418690, IPv6 55861, Onion 2747
Skip entries with invalid address: IPv4 418690, IPv6 55861, Onion 2747
After removing duplicates: IPv4 409220, IPv6 54028, Onion 2717
Skip entries from suspicious hosts: IPv4 409219, IPv6 54028, Onion 2717
Enforce minimal number of blocks: IPv4 106719, IPv6 46342, Onion 2621
Require service bit 1: IPv4 106384, IPv6 46241, Onion 2542
Require minimum uptime: IPv4 5300, IPv6 1153, Onion 201
Require a known and recent user agent: IPv4 4642, IPv6 1060, Onion 141
Filter out hosts with multiple bitcoin ports: IPv4 4642, IPv6 1060, Onion 141
Look up ASNs and limit results, both per ASN and globally: IPv4 464, IPv6 48, Onion 141
```

### CODE REVIEW

**Comment by laanwj** [comment]
Only 48 IPv6 seeds might be slightly concerning, dunno.

**Comment by Sjors** [comment]
A lot of IPv6 hosts disappear in the "multiple bitcoin ports" step too. That script output table might be easier to read if you put the numbers first (ideally padded).

**Comment by laanwj** [comment]
> The suspicious hosts check removes suspiciously few entries :-)

Yea, only 16 "suspicious hosts" are defined in the script, which were added a long time ago. TBH I don't really think it makes much sense to maintain such a list in the repository.

**Comment by laanwj** [comment]
It looks like the problem is not the ASN sifting itself, but the way the limiting works. There used to be a limit of 512 IPv4 peers, and no limit on IPv6 or Tor peers (because there are only so few of the latter). However the PR to include the IPv6 addresses in the ASN sifting also included them in the 512 limit. It's split more or less according to how many IPv4/IPv6 there are.

Will make add per-network limits instead.

**Comment by Sjors** [comment]
A max of 2 seeds per ASN seems a bit strict. E.g. AS33915 contains all Dutch Vodafone mobile (not reachable) and Ziggo cable users (long living IP). It's fine for IPv4 because we still get the max of 512 for that net.

Maybe make it 10 for IPv6? The odds of randomly connecting to two nodes on the same ASN still seems negligible.

Should we bump `MIN_BLOCKS` as well?

**Comment by laanwj** [comment]
> Maybe make it 10 for IPv6? The odds of randomly connecting to two nodes on the same ASN still seems negligible
> Should we bump MIN_BLOCKS as well?

All good suggestions, but I'd say, post-0.19.

**Comment by Sjors** [comment]
ACK 3b09f2b

Something to consider when we do improve the script, is that it's not very deterministic. E.g. I ran the script on sipa's data from a few days later plus my data (uploaded above), and 400 of the [resulting nodes](https://github.com/Sjors/bitcoin/commit/7c08e20d321928a2654605ac8fe1c0ed26db209b) are different. Even though our numbers are similar at each step:

```
  IPv4   IPv6  Onion Pass                                               
418727  55869   2746 Initial
418727  55869   2746 Skip entries with invalid address
410413  54115   2718 After removing duplicates
410412  54115   2718 Skip entries from suspicious hosts
107223  46411   2622 Enforce minimal number of blocks
106885  46308   2543 Require service bit 1
  5376   1164    202 Require minimum uptime
  4685   1066    141 Require a known and recent user agent
  4648   1060    141 Filter out hosts with multiple bitcoin ports
   512    116    141 Look up ASNs and limit results per ASN and per net
```

I tried moving the deduplication step after the uptime and sort steps ([commit](https://github.com/Sjors/bitcoin/commit/3b97aed57284ba4179608ee36f29c4efce282ca6)). I ran it, committed, fetched a slightly newer version of sipa's seed, and ran it again. Now only 140 nodes are different, which is still not great.

**Comment by jonasschnelli** [comment]
Looks good.
ACK 801d341f3a4b00633aa135407752d21ba868e37b - I just did some random manual checks against my data source (https://bitcointools.jonasschnelli.ch/dnsseed.dump.tar.gz) and it seems like that a lot of the new IPs are not listed in my seeder dump. Though I guess that is okay.
Did some manual checks with telnet.

**Comment by TheBlueMatt** [comment]
Only looked at the address txt file, and found the following groups with ore than two IPs per ASN.
212.33.204.190:8333 should likely be removed as it is RPKI-Invalid (max-length 20, but announced as a 22), so it isn't gonna be accessible from a number of networks. The 2002:: IPs are 6to4 and likely also shouldn't be included (except maybe as the corresponding IPv4 addresses).

```
174 38.143.66.107:8333
174 [2001:550:3d05:156::100]:8333
174 [2602:ffb6:4:739e:f816:3eff:fe00:c2b3]:8333
4134 14.18.140.45:5559
4134 180.97.80.213:8333
4134 182.150.55.96:8333
4134 222.186.43.66:8333
6939 [2001:470:1f1d:61f:cd1a::109]:42434
6939 [2001:470:5:41e::3001]:8333
6939 [2002:2f5a:562a::2f5a:562a]:8333
6939 [2002:b6ff:3dca::b6ff:3dca]:28364
```

**Review by jkczyz — COMMENTED** [review]
Reviewed Python changes. Some minor typos and nits but otherwise looks like reasonable improvements.

**Comment by laanwj** [comment]
I'm not going to fix up comment typos here, feel free to do that later.

> Something to consider when we do improve the script, is that it's not very deterministic. 

The deduplication step randomizes the input order (by putting it into a dict, which uses hashing with a random seed in python).

This is intentional, because the input consists of concatenated nodes files from different sources. If it only picks the first valid nodes it'd effectively ignore your input.

Sure, a deterministic shuffling could be done. But determinism was never required in this script, and this is not the time to make up requirements.

> and found the following groups with ore than two IPs per ASN.

Wait, you're saying that the two IPs per ASN filtering isn't only non-deterministic, it doesn't even work?

**Comment by laanwj** [comment]
Removed these in a new commit:
```
174 38.143.66.107:8333
174 [2001:550:3d05:156::100]:8333
174 [2602:ffb6:4:739e:f816:3eff:fe00:c2b3]:8333
4134 14.18.140.45:5559
4134 180.97.80.213:8333
4134 182.150.55.96:8333
4134 222.186.43.66:8333
6939 [2001:470:1f1d:61f:cd1a::109]:42434
6939 [2001:470:5:41e::3001]:8333
6939 [2002:2f5a:562a::2f5a:562a]:8333
6939 [2002:b6ff:3dca::b6ff:3dca]:28364
```

**Comment by Sjors** [comment]
ACK 0218171. I also checked that `chainparamsseeds.h` is generated from `nodes_main.txt`. Sounds like we should look at this script a bit more outside release moments :-)

**Pull request merged**
