### PR TITLE
devtools: Correctly extract symbol versions in symbol-check

### PR DESCRIPTION
**Pull request by laanwj**
I misunderstood the ELF specification for version symbols (verneed): The `vn_aux` pointer is relative to the main verneed record, not the start of the section.

This caused many symbols to not be versioned properly in the return value of `elf.dyn_symbols`. This was discovered in #21454.

Fix it by correcting the offset computation.

- xkb versions symbols (using the prefix `V`), as this library is used by bitcoin-qt, add it to the valid versions in `symbol-check.py`

This unfortunately brings to light some symbols that have been introduced since and weren't caught (from a gitian compile of master):

```
bitcoin-cli: symbol getrandom from unsupported version GLIBC_2.25
bitcoin-cli: failed IMPORTED_SYMBOLS
bitcoind: symbol getrandom from unsupported version GLIBC_2.25
bitcoind: symbol log from unsupported version GLIBC_2.29
bitcoind: symbol fcntl64 from unsupported version GLIBC_2.28
bitcoind: symbol pow from unsupported version GLIBC_2.29
bitcoind: symbol exp from unsupported version GLIBC_2.29
bitcoind: failed IMPORTED_SYMBOLS
bitcoin-qt: symbol exp from unsupported version GLIBC_2.29
bitcoin-qt: symbol fcntl64 from unsupported version GLIBC_2.28
bitcoin-qt: symbol log from unsupported version GLIBC_2.29
bitcoin-qt: symbol pow from unsupported version GLIBC_2.29
bitcoin-qt: symbol statx from unsupported version GLIBC_2.28
bitcoin-qt: symbol getrandom from unsupported version GLIBC_2.25
bitcoin-qt: symbol renameat2 from unsupported version GLIBC_2.28
bitcoin-qt: symbol getentropy from unsupported version GLIBC_2.25
bitcoin-qt: failed IMPORTED_SYMBOLS
bitcoin-wallet: symbol exp from unsupported version GLIBC_2.29
bitcoin-wallet: symbol log from unsupported version GLIBC_2.29
bitcoin-wallet: symbol fcntl64 from unsupported version GLIBC_2.28
bitcoin-wallet: failed IMPORTED_SYMBOLS
test_bitcoin: symbol getrandom from unsupported version GLIBC_2.25
test_bitcoin: symbol log from unsupported version GLIBC_2.29
test_bitcoin: symbol fcntl64 from unsupported version GLIBC_2.28
test_bitcoin: symbol pow from unsupported version GLIBC_2.29
test_bitcoin: symbol exp from unsupported version GLIBC_2.29
test_bitcoin: failed IMPORTED_SYMBOLS
```

### CODE REVIEW

**Comment by laanwj** [comment]
* `exp` is used in `CRollingBloomFilter::CRollingBloomFilter` (in our code)
* `fcntl64` has a data reference, it's not ever called in the code (`objdump -d bitcoin-qt|grep fcntl64@plt` shows nothing)
* `getentropy` is used in `QRandomGenerator::SystemGenerator::generate` (inside qt)
* `getrandom` is used in one place: `arc4_stir at evutil_rand.c:?`  (libevent dependency)
* `log` is used in various places throughout the code (mainly for log2_work computation for debug)
* `pow` is used in *many* places in our code, also in qt
* `renameat` is used in `QFileSystemEngine::renameFile` (inside qt)
* `statx` is used in three places (`QFileSystemMetaData` inside qt)

**Comment by achow101** [comment]
Is there a reference document that explains what the offset is? I found a doc that mentioned it, but my reading of that also came to the original conclusion that you made.

**Comment by laanwj** [comment]
> Is there a reference document that explains what the offset is? 

I couldn't find anything. But this matches the `objdump` output, and what the linker itself seems to do, which seems kind of important for a symbol check.

All the other offsets (`vn_next`, `vna_next`) are relative to the referring record, so it is at least consistent.

**Comment by laanwj** [comment]
Found it:

> vn_aux
>
>    The byte offset, from the start of this Elf32_Verneed entry, to the Elf32_Vernaux array of version definitions that are required from the associated file dependency. At least one version dependency must exist. Additional version dependencies can be present, the number being indicated by the vn_cnt value.

Source: [Oracle](https://docs.oracle.com/cd/E19120-01/open.solaris/819-0690/chapter6-61174/index.html), of all places…

**Review by hebasto — COMMENTED** [review]
Approach ACK c9b19edf9990d5ebf34945ce8e9a3220459d70f3, tested including comparison with master + reverted 634f6ec4eb9997d7bd0f8209fad49a4171d42384 from #20434 (non-pixie).

>     * xkb versions symbols (using the prefix `V`), as this library is used by bitcoin-qt...

The `libxkbcommon` package was added in #21376.

This PR works flawlessly. Need more time to reason about the last commit to final ACK.

**Comment by laanwj** [comment]
> Need more time to reason about the last commit to final ACK.

FWW, the last commit is a continuation of #17538 from 2019, which bumped the minimum glibc to 2.17.

**Comment by laanwj** [comment]
> Maybe it would be better to rewrite the code so that the minimum GLIBC version isn't split over two places?

Okay, pushed a new last commit that does this. Instead of hardcoding a separate table for GLIBC, it optionally allows entries in `MAX_VERSIONS` to be a per-architecture dictionary. I hope this is clearer.

**Review by hebasto — APPROVED** [review]
ACK e8cd3700eeb27437f5ea435869c9d61214285fdd

> Okay, pushed a new last commit that does this. Instead of hardcoding a separate table for GLIBC, it optionally allows entries in `MAX_VERSIONS` to be a per-architecture dictionary. I hope this is clearer.

Many thanks for that!

**Comment by hebasto** [comment]
> This unfortunately brings to light some symbols that have been introduced since and weren't caught (from a gitian compile of master):

On master, with applied #22281, #22287 and this PR:
```
Checking glibc back compat...
bitcoind: symbol getrandom from unsupported version GLIBC_2.25
bitcoind: failed IMPORTED_SYMBOLS
bitcoin-cli: symbol getrandom from unsupported version GLIBC_2.25
bitcoin-cli: failed IMPORTED_SYMBOLS
test/test_bitcoin: symbol getrandom from unsupported version GLIBC_2.25
test/test_bitcoin: failed IMPORTED_SYMBOLS
qt/bitcoin-qt: symbol statx from unsupported version GLIBC_2.28
qt/bitcoin-qt: symbol getrandom from unsupported version GLIBC_2.25
qt/bitcoin-qt: symbol renameat2 from unsupported version GLIBC_2.28
qt/bitcoin-qt: symbol getentropy from unsupported version GLIBC_2.25
qt/bitcoin-qt: failed IMPORTED_SYMBO
```

For `statx` and `renameat2` I opened a dedicated #22280.

Are `getrandom` and `getentropy` safe to be allowed?

**Comment by hebasto** [comment]
@laanwj 
>     * `getentropy` is used in `QRandomGenerator::SystemGenerator::generate` (inside qt)
> 
>     * `getrandom` is used in one place: `arc4_stir at evutil_rand.c:?`  (libevent dependency)

Removed in #22318.

**Comment by hebasto** [comment]
@laanwj 
> * `renameat` is used in `QFileSystemEngine::renameFile` (inside qt)
> 
> * `statx` is used in three places (`QFileSystemMetaData` inside qt)

Removed in #22321.

**Comment by hebasto** [comment]
With #22281, #22287/#22305, #22318 and #22321 [combined](https://github.com/hebasto/bitcoin/commits/210623-glibc) the `symbol-check.py` passes successfully.

**Pull request merged**
