### PR TITLE
script, doc: contrib/seeds updates

### PR DESCRIPTION
**Pull request by jonatack**
Seen while reviewing #20237.

1. Fix a deprecation warning in `contrib/seeds/makeseeds.py`
```
    makeseeds.py:139: DeprecationWarning: please use dns.resolver.resolve() instead
      asn = int([x.to_text() for x in dns.resolver.query('.'.join(
```
  - Per https://dnspython.readthedocs.io/en/latest/whatsnew.html, `dns.resolver.query()` was deprecated in `dnspython` version 2.0.0.

  - See https://dnspython.readthedocs.io/en/latest/resolver-class.html for more info on the resolver class.

2. Update the `dnspython` dependency installation instructions in `contrib/seeds/README`

  - The markdown rendering can be seen here: https://github.com/jonatack/bitcoin/tree/contrib-seeds-fixups/contrib/seeds

### CODE REVIEW

**Comment by practicalswift** [comment]
Concept ACK

Thanks for cleaning up!

**Comment by fanquake** [comment]
~0. This has to wait until after branch off otherwise it will break our Python 3.5 requirement.

**Comment by jonatack** [comment]
Sure, can re-open after we bump the minimum to 3.6.

**Comment by jonatack** [comment]
Re-opening now that the minimum Python version has been bumped to 3.6.

**Comment by laanwj** [comment]
code review ACK 961f148cb1b4caab86b4354357999e03433b04b1

**Pull request merged**
