### PR TITLE
fuzz: Misc refactor

### PR DESCRIPTION
**Pull request by maflcko**
Some small refactors to remove unused and redundant fuzz code

### CODE REVIEW

**Comment by practicalswift** [comment]
cr ACK faa8b2de6b9749d33b4f11155a29d7094f23a144: patch looks correct and touches only `src/test/fuzz/` (+ one addition to `src/test/util/`)

Thanks for cleaning up!

**Comment by practicalswift** [comment]
cr re-ACK faaf133e4ada4a12783e7395a17f207f7d700e09

**Comment by MarcoFalke** [comment]
Sorry for the force push. Should be done now:

* This: https://drahtbot.space/host_reports/DrahtBot/reports/coverage_fuzz/monotree/fa4926cca68db243/fuzz.coverage/index.html
* master: https://marcofalke.github.io/btc_cov/fuzz.coverage/index.html

**Comment by practicalswift** [comment]
cr re-ACK fa4926cca68db2433e579d9b4a642248a9314673

**Pull request merged**
