### PR TITLE
Remove the phrase "Experimental" from section what is bitcoin?

### PR DESCRIPTION
**Pull request by ucallmerk**
Bitcoin is no longer considered an experimental digital currency. With world wide adoption by crypto investors and institutions like Governments, Banks and Stock Exchanges it has already established as the world's leading crypto currency and is here to stay.
Hence removing the term "Experimental"

### CODE REVIEW

**Comment by fanquake** [comment]
Thanks, but we're happy leaving this as-is for now. See #21883, #21326 etc.

**Comment by ucallmerk** [comment]
Hmm.. I think that's an eye catcher for every new enthusiastic programmer who believes in Bitcoin.
I know you feel it's still experimental but the world says otherwise :)
Find a good day to change that text :)

**Comment by prayank23** [comment]
> Hmm.. I think that's an eye catcher for every new enthusiastic programmer who believes in Bitcoin.

They might also not see whitepaper in this repository. Although it's available in a few other repositories, websites etc. Bitcoin Core is one of the implementation of Bitcoin and most of the maintainers still consider Bitcoin an experiment.

You can either ignore it or fork it and change it for your usage.

**Comment by MarcoFalke** [comment]
For reference, an earlier discussion: https://github.com/bitcoin/bitcoin/issues/7173

I think that it is inherently subjective whether Bitcoin is experimental or not, so removing the word here or adding it there won't change anything about its perception. If you read the sentence that follows the sentence that mentions "experimental", you will notice that there is no authority in Bitcoin. Thus there is no one to decide whether it is experimental or not anyway.

I can see an argument to remove the whole section, as it is not the primary goal of the Bitcoin Core software to educate users about Bitcoin. I'd expect users to already know about Bitcoin once they discover Bitcoin Core. Maybe it can be replaced by something along the lines of the first section of https://bitcoincore.org/en/about/

**Comment by michaelfolkson** [comment]
I wonder if we can nip all these PRs on "experimental" wording and linking to the white paper in the bud once and for all.

Thoughts on adding "(arguably)" in front of experimental? And to remove any reference to the white paper? Happy to open the PR if it would help stop these PRs.

**Pull request closed without merging**
