### PR TITLE
rpc: trigger error before dealing strSecret / strLabel

### PR DESCRIPTION
**Pull request by bdescamps**
Improvement on importprivkey method.
Errors can be triggered early.

### CODE REVIEW

**Review by ccr781804 — APPROVED** [review]
For me. It's very difficult to understand clearly.

**Comment by bdescamps** [comment]
I think it's better to deal directly exit function. Here we can trigger two JSONRPCError, without instantiate string for strLabel & strSecret

**Comment by laanwj** [comment]
What does this change from a user perspective?

**Comment by bdescamps** [comment]
At this time nothing, but it can prevent future bug.

**Comment by laanwj** [comment]
What kind of bug?

**Comment by bdescamps** [comment]
A bug create by a bad interpretation of code
Here we create 2 variables strSecret StrLabel.
 - strSecret which is instanciate by a request params
 - strLabel which is instanciate by an empty string and set after by a request params (if it is present)

There is no reason to dealing them now because we don't use them.  Moreover if the wallet rescan is disabled or if the wallet is currently rescanning we have creating all that for nothing

**Comment by tryphe** [comment]
This code doesn't get called very much (people only use it to manually type in their legacy private keys) and the performance doesn't really matter. It would save us from copying a string _each time an error happens_...

The initializations could also be moved up before `LOCK(pwallet->cs_wallet);` to save on lock time.
The initialization of `strLabel` could be moved down further also, to line 168.

:bike: :bike: :bike:

**Comment by MarcoFalke** [comment]
With argument parsing moving to RPCHelpMan, this will become obsolete. So tend to NACK on this diff.

Maybe it could make sense to use the zeroing-on-destruction string here.

**Comment by laanwj** [comment]
As it stands, this doesn't seem worth the hassle, so closing this.

**Pull request closed without merging**
