### PR TITLE
wallet: Replace `GetBalance()` logic with `AvailableCoins()`

### PR DESCRIPTION
**Pull request by w0xlt**
This PR proposes a solution for https://github.com/bitcoin/bitcoin/issues/26500 by changing the `AvailableCoins()` function to calculate values by status (`TRUSTED`, `UNTRUSTED_PENDING` and `IMMATURE`) and ownership (`MINE`, `WATCH_ONLY`), eliminating the `GetBalance()` logic.

The downside is that the cache is no longer used. Not sure about the performance implication, but if the approach is OK, caching can also be used with this solution.

This approach also fixes the bug mentioned at the end of the `wallet_abandonconflict.py` file.

### CODE REVIEW

**Comment by w0xlt** [comment]
Rebased.

**Comment by achow101** [comment]
I think this will end up making `GetBalance` really slow. We should really be tracking our UTXOs and computing the balance (and available coins) from that instead of iterating the entire wallet to figure out the UTXOs. #27286 implements the first steps to doing that, and I think we should prefer moving in that direction.

**Comment by josibake** [comment]
I'd also prefer we stopped using `AvailableCoins` as a general wallet traversal tool in favor of something like https://github.com/bitcoin/bitcoin/pull/27286

A lot of bugs/strangeness in the wallet seems to come from the fact that we always need to iterate over a bunch of transactions to learn the state of our wallet. If we did track wallet state in one place, we could have well-scoped individual functions for specific tasks.

**Comment by achow101** [comment]
Closing due to lack of interest in this approach.

**Pull request closed without merging**
