### PR TITLE
[Makefile] Alphabetically Reorder addrdb.cpp

### PR DESCRIPTION
**Pull request by spencerlievens**
To keep conformity.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
*sigh*
utACK 56f09df9d81ce635323f5eefc28f328284004203

**Comment by TheBlueMatt** [comment]
> *sigh*
ACK

**Comment by kallewoof** [comment]
utACK 56f09df9d81ce635323f5eefc28f328284004203

**Comment by laanwj** [comment]
Meh.

**Comment by kallewoof** [comment]
Local conformity? (All the other files in the list are in alphabetic order.)

**Comment by spencerlievens** [comment]
@laanwj Conformity in the sense that the rest of the makefile is alphabetically sorted and that everyone seems to be conforming to that standard.

**Comment by jonasschnelli** [comment]
> @laanwj Conformity in the sense that the rest of the makefile is alphabetically sorted and that everyone seems to be conforming to that standard(well nearly everyone :P).

Such pull requests improve almost nothing while they distract the development process of other important features and stealing times from reviewers and maintainers.

If you want to help, improve something that has a positive net-outcome.

**Comment by laanwj** [comment]
> @laanwj Conformity in the sense that the rest of the makefile is alphabetically sorted and that everyone seems to be conforming to that standard(well nearly everyone :P).

Ok, fair enough, going to merge this one, but - as @jonasschnelli already says - please don't make a habit of it. Usually it's best to do these kind of changes when you're already adding/removing files in the first place.

**Pull request merged**
