### PR TITLE
Add list of implemented BIPs

### PR DESCRIPTION
**Pull request by sipa**

### CODE REVIEW

**Comment by Michagogo** [comment]
A few nits:
* There's some inconsistency between "implemented since" and "in". I feel like the latter sounds more natural, but either way it should be consistent.
* Not sure I completely understand the logic behind the use of bold and italics, but maybe that's just me
* I don't think it's necessary to mention rc versions -- they're a technicality of the release process, I think they can just be listed as v0.10.0.
* Was 0.9 still called Bitcoin-Qt? I thought we were calling it Bitcoin Core GUI (or just "the GUI") now.

Other than that, as far as I can tell, looks good. ACK.

**Comment by laanwj** [comment]
Nice idea!

- May make sense to add commit IDs, if we know them
- Maybe format as a table

Not meant as blockers or necessarily have to be done in this pull, ACK anyhow.

**Comment by fanquake** [comment]
ACK

**Comment by fanquake** [comment]
@laanwj Just to follow up:
Implemented
BIPS 11,12,13 #669
BIP 14 #707
BIP 16 #748
BIP 22 #936
BIP 23 #1816
BIP 31 #1081
BIP 34 #1526
BIP 35 #1641
BIP 37 #1795
BIP 42 #3842
BIP 61 #3185
BIP 70 #2539
BIP 71 #5216

Currently Open
BIP 66 #5713

**Comment by laanwj** [comment]
@fanquake Whoa, thanks, nice work of archeology tracking those down.

**Comment by sipa** [comment]
Updated, added BIP66, included @Michagogo's list, and added PR numbers for BIP21 and BIP30.

**Comment by Michagogo** [comment]
@sipa Do you mean @fanquake?

**Comment by Michagogo** [comment]
And ICYMI, https://github.com/bitcoin/bitcoin/pull/5708#issuecomment-71395575

**Comment by sipa** [comment]
Updated.

**Comment by gmaxwell** [comment]
ACK.

**Comment by sean1000444** [comment]
Would it be possible to update this with changes that happened after such as https://github.com/bitcoin/bitcoin/commit/2e17ac83c65b65fe2037b8c8941c25e288905903#diff-dedcc88d0e66b86a19981e7c175658c2 that changed the BIP 11 implementation here: https://github.com/bitcoin/bitcoin/commit/7e55c1ab650163011a690daf74cb1cc89bdd563b#diff-dedcc88d0e66b86a19981e7c175658c2 . I am currently porting BIPs into a project and this would make it much easier to avoid including a deprecated addition.

**Pull request merged**
