### PR TITLE
miner: Remove uncompiled MTP code

### PR DESCRIPTION
**Pull request by maflcko**
This removes uncompiled code.

Can be checked by inserting `static_assert(STANDARD_LOCKTIME_VERIFY_FLAGS & LOCKTIME_MEDIAN_TIME_PAST)` and compiling or by reading the source code.

Even if the code was compiled, it would be unsafe to execute, since it is not allowed to include transactions that are locked until some time after the current MTP.

Also, rename the member to cause explicit merge conflicts in case there is a patch out there referencing the variable.

### CODE REVIEW

**Review by luke-jr — APPROVED** [review]
utACK. Might have been nicer to review as 2 commits (splitting the formatting/rename changes out of the code removal)

**Comment by MarcoFalke** [comment]
> Might have been nicer to review as 2 commits

Thanks. Reworked into two commits.

**Review by shaavan — APPROVED** [review]
ACK fa46ac4d9d6dc99572c44c42adc9bc3f41d701d4

Complied and ran bitcoind successfully with the following patch:
```
static_assert(STANDARD_LOCKTIME_VERIFY_FLAGS & LOCKTIME_MEDIAN_TIME_PAST)
```

This goes to show that the above statement is always true. Hence I agree with removing the conditional part of the code that shall never be reached. The renaming of the variable makes sense and follows our global variable naming convention.
Finally, the formatting changes introduced in the first commit of this PR look good. I checked for possible formatting issues, and I found none.

**Review by theStack — APPROVED** [review]
Code-review ACK fa46ac4d9d6dc99572c44c42adc9bc3f41d701d4

**Pull request merged**
