### PR TITLE
doc: asmap release note

### PR DESCRIPTION
**Pull request by jonatack**
Unsure how much detail to provide. Feedback welcome.

### CODE REVIEW

**Comment by jonatack** [comment]
Markdown version visible here: https://github.com/jonatack/bitcoin/blob/asmap-release-note/doc/release-notes.md

**Comment by jonatack** [comment]
Markdown version visible here: https://github.com/jonatack/bitcoin/blob/asmap-release-note/doc/release-notes.md#new-settings

**Comment by flack** [comment]
fyi, you can also see the markdown rendering in the PR if you click the "rich diff" button:

richdiff


https://github.com/bitcoin/bitcoin/pull/18310/files?short_path=ef76fd6#diff-ef76fd6674f07db88c3422fdbf0bcf9f

**Comment by laanwj** [comment]
> fyi, you can also see the markdown rendering in the PR if you click the "rich diff" button:

TIL!

**Comment by laanwj** [comment]
ACK ac73afbcbf7751cf2b8d52de6f2a341e8bac5cf6

> Unsure how much detail to provide.

I think this is exactly the right level of detail for a release notes entry.

**Comment by MarcoFalke** [comment]
cc @naumenkogs

**Comment by naumenkogs** [comment]
ACK ac73afb

**Pull request merged**
