### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by ayeowch**

### CODE REVIEW

**Comment by fanquake** [comment]
ACK for the trivial tree. Ping @theuni

**Comment by fsb4000** [comment]
ACK

**Comment by jonasschnelli** [comment]
ACK @ trivial

**Comment by Diapolo** [comment]
ACK @theuni for Trivial.

**Comment by laanwj** [comment]
Was merged into trivial-next.

**Comment by theuni** [comment]
Grr, just looked at this closer while preparing a PR from trivial-next. This wasn't a typo.

Reverted from trivial, NACK.

**Comment by ayeowch** [comment]
@theuni Shouldn't it be 'to send' instead of 'to end'?

**Comment by theuni** [comment]
No, it means more like "to infinity".

**Comment by ayeowch** [comment]
and beyond..

**Pull request closed without merging**
