### PR TITLE
0.13.2 release process

### PR DESCRIPTION
**Pull request by maflcko**

### CODE REVIEW

**Review by dcousens — APPROVED** [review]

**Comment by MarcoFalke** [comment]
The manpages are missing the zmq options, @laanwj feel free to recreate them if you feel like it.

**Comment by gmaxwell** [comment]
ACK.

**Comment by laanwj** [comment]
Gah, did I forget the bump the version again. 

> The manpages are missing the zmq options, @laanwj feel free to recreate them if you feel like it.

Strange - how did it end up that way? In any case the old manpages in `contrib/debian/manpages/bitcoin-cli.1` should go if you put new ones in `doc/man`.

**Comment by MarcoFalke** [comment]
Fine, moved them to the old location

**Pull request merged**
