### PR TITLE
test: fix intermittent failure in wallet_resendwallettransactions.py

### LINKED ISSUE #28094: failure in wallet_resendwallettransactions.py --legacy-wallet
https://cirrus-ci.com/task/5656433702731776?logs=ci#L7912 from #26288:
```bash
................................................................
                                                                
194/268 - wallet_resendwallettransactions.py --legacy-wallet failed, Duration: 111 s
stdout:
2023-07-17T21:30:03.351000Z TestFramework (INFO): PRNG seed is: 4625691275301666838
2023-07-17T21:30:03.352000Z TestFramework (INFO): Initializing test directory /tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_₿_🏃_20230717_204920/wallet_resendwallettransactions_69
2023-07-17T21:30:18.443000Z TestFramework (INFO): Create a new transaction and wait until it's broadcast
2023-07-17T21:30:22.728000Z TestFramework (INFO): Create a block
2023-07-17T21:30:22.733000Z TestFramework (INFO): Bump time & check that transaction is rebroadcast
2023-07-17T21:30:23.639000Z TestFramework (INFO): Chain of unconfirmed not-in-mempool txs are rebroadcast
2023-07-17T21:31:23.811000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 131, in main
    self.run_test()
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/wallet_resendwallettransactions.py", line 116, in run_test
    assert_raises_rpc_error(-5, "Transaction not in mempool", node.getmempoolentry, txid)
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/util.py", line 131, in assert_raises_rpc_error
    assert try_rpc(code, message, fun, *args, **kwds), "No exception raised"
AssertionError: No exception raised
2023-07-17T21:31:23.862000Z TestFramework (INFO): Stopping nodes
2023-07-17T21:31:54.182000Z TestFramework (WARNING): Not cleaning up dir /tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_₿_🏃_20230717_204920/wallet_resendwallettransactions_69
2023-07-17T21:31:54.182000Z TestFramework (ERROR): Test failed. Test logging available at /tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_₿_🏃_20230717_204920/wallet_resendwallettransactions_69/test_framework.log
2023-07-17T21:31:54.182000Z TestFramework (ERROR): 
2023-07-17T21:31:54.183000Z TestFramework (ERROR): Hint: Call /tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/combine_logs.py '/tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_₿_🏃_20230717_204920/wallet_resendwallettransactions_69' to consolidate all logs
2023-07-17T21:31:54.183000Z TestFramework (ERROR): 
2023-07-17T21:31:54.183000Z TestFramework (ERROR): If this failure happened unexpectedly or intermittently, please file a bug and provide a link or upload of the combined log.
2023-07-17T21:31:54.183000Z TestFramework (ERROR): https://github.com/bitcoin/bitcoin/issues
2023-07-17T21:31:54.183000Z TestFramework (ERROR): 
```

Full log: https://gist.github.com/fanquake/cb8e0dd478c6a63d448b4db4d29142c4.

### PR DESCRIPTION
**Pull request by mzumsande**
Fixes #28094

The test bumps the mocktime for ~2 weeks and then triggers eviction from the mempool. But this bump will also cause a new resubmit, and if the timing is such that this resubmit happens right after the eviction and before the check that the tx was evicted, the test can fail as in #28094:

```
node0 2023-07-17T21:31:23.809483Z (mocktime: 2023-08-02T09:46:27Z) [httpworker.1] [validation.cpp:267] [LimitMempoolSize] [mempool] Expired 2 transactions from the memory pool
node0 2023-07-17T21:31:23.810079Z (mocktime: 2023-08-02T09:46:27Z) [scheduler] [wallet/wallet.h:895] [WalletLogPrintf] [default wallet] ResubmitWalletTransactions: resubmit 2 unconfirmed transactions
node0 2023-07-17T21:31:23.810474Z (mocktime: 2023-08-02T09:46:27Z) [httpworker.2] [rpc/request.cpp:181] [parse] [rpc] ThreadRPCServer method=getmempoolentry user=__cookie__ 
2023-07-17T21:31:23.811000Z TestFramework (ERROR): Assertion failed (...) AssertionError: No exception raised
```
Fix this by flushing out the current resubmit call before triggering mempool eviction.

### CODE REVIEW

**Review by jonatack — COMMENTED** [review]
Light "this looks like the other tests in this file" ACK e667bd68a10512ddc784df44bdcb63ee441e5551

**Review by maflcko — COMMENTED** [review]
left a follow-up idea

**Comment by achow101** [comment]
ACK e667bd68a10512ddc784df44bdcb63ee441e5551

**Comment by mzumsande** [comment]
I didn't get to address the suggestions by @jonatack  and @MarcoFalke in time - they make sense to me and could be done in a separate PR that reworks the test a bit deeper than just fixing the timeout - just noting that I'm probably not going to get to this, at least for the next couple of weeks.

**Pull request merged**
