### PR TITLE
assets-attribution: Update typicons to MIT license

### PR DESCRIPTION
**Pull request by luke-jr**
Per #6367 ...

stephenhutchings commented 3 Jul 2015, 6:35 GMT:

> Hi Luke, happy for these to be distributed under the terms of the MIT licence.
> Let me know if you need anything further from me.

Note, this can be cleanly merged to both master and 0.11 branches.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
ACK

**Comment by fanquake** [comment]
Great. ACK

**Comment by laanwj** [comment]
Nice! ACK

**Comment by laanwj** [comment]
Also merged to 0.11 as 7bf37e1

**Pull request merged**
