### PR TITLE
 [wallet] Add regression test for vValue sort order 

### PR DESCRIPTION
**Pull request by maflcko**
vValue is sorted from high to low. This adds a regression test such that pulls like #7183 would fail travis.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Note: #7183 was changed in the meantime, the original diff might come in handy to test this pull:

```diff
diff --git a/src/wallet/wallet.cpp b/src/wallet/wallet.cpp
index d23d54e..3d1f58c 100644
--- a/src/wallet/wallet.cpp
+++ b/src/wallet/wallet.cpp
@@ -1605,7 +1605,7 @@ static void ApproximateBestSubset(vector<pair<CAmount, pair<const CWalletTx*,uns
         bool fReachedTarget = false;
         for (int nPass = 0; nPass < 2 && !fReachedTarget; nPass++)
         {
-            for (unsigned int i = 0; i < vValue.size(); i++)
+            for (unsigned int i = 0; i < vValue.size() && !fReachedTarget; i++)
             {
                 //The solver here uses a randomized algorithm,
                 //the randomness serves no real security purpose but is just
@@ -1625,8 +1625,6 @@ static void ApproximateBestSubset(vector<pair<CAmount, pair<const CWalletTx*,uns
                             nBest = nTotal;
                             vfBest = vfIncluded;
                         }
-                        nTotal -= vValue[i].first;
-                        vfIncluded[i] = false;
                     }
                 }
             }

**Comment by laanwj** [comment]
utACK

**Comment by Xekyo** [comment]
ACK: Fails for the referenced original PR #7183.

**Comment by laanwj** [comment]
Cherry-picked to 0.12 as ff9b610

**Pull request merged**
