### PR TITLE
Report progress in ReplayBlocks while rolling forward

### LINKED ISSUE #13303: GUI: ShowProgress is missing during ReplayBlocks()
During rolling forward in `ReplayBlocks()` the UI progress starts with 0 then, once sync up again, jumps to 100%. This process can take pretty long and it would be good to show some progress steps within the RollingForwardBlock loop (`for (int nHeight = nForkHeight + 1; nHeight <= pindexNew->nHeight; ++nHeight) {`)

### PR DESCRIPTION
**Pull request by promag**
Fixes #13303.

### CODE REVIEW

**Comment by promag** [comment]
Should only report each 5% for instance?

**Comment by Empact** [comment]
`CWallet::ScanForWalletTransactions` has a pretty good implementation that only reports every 1%.

**Comment by promag** [comment]
@Empact IMO the receiver is the one that should throttle, because he is the one that knows the resolution. Anyway, looks like `ScanForWalletTransactions` reports progress each 100 blocks, or am I wrong?

**Comment by GreatSock** [comment]
I think it should report every 1% change. But since changes less than 1% won't be visible, maybe check if the percentage have actually changed before updating. Calling `ShowProgress` 100 times should be fine right?

**Comment by promag** [comment]
I don't mind doing something like that...

> But since changes less than 1% won't be visible

But how do you know? What if you have a progress bar with, for instance, 200px width? It should report 0.5%.

**Comment by GreatSock** [comment]
Right now `ShowProgress` seems to take an integer which means 1% changes won't be visible.

But I agree: `ShowProgress` should instead take a float(maybe even between 0 and 1) and then check if it should update by itself. This would probably be better since it can then choose to display the progress however it wants.

**Comment by promag** [comment]
Actually I thinking in something like `ShowProgress(int min, int value, int max)`.

**Comment by GreatSock** [comment]
I would personally prefer giving it a float since I feel like it would be more flexible. But then again, why not do both? We could just overload the function.

**Comment by jonasschnelli** [comment]
What is the best test plan to test this?

**Comment by jb55** [comment]
Anything left to do here?

**Comment by laanwj** [comment]
utACK b16ab9af07f802cc769c2443df1c637e8e12ab80

**Comment by laanwj** [comment]
> Anything left to do here?

Not really—I think the most important thing to review here is that divide by zero never happens.

**Pull request merged**
