### PR TITLE
test: Fix intermittent wallet_multiwallet issue with got_loading_error

### PR DESCRIPTION
**Pull request by maflcko**
Failing the test after 10 iterations without a loading error is problematic because it may take 11 iterations to get a loading error.

Fix that by running until a loading error occurs, which should happen in almost all runs within the first 10 iterations.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
https://cirrus-ci.com/task/5005908700823552?command=ci#L5178

**Review by ryanofsky — APPROVED** [review]
Code review ACK fab48da908f3f81135b9163edf5011d1e5f6ef6e. This seems like a good workaround. I think more ideally think load and unload RPCs would not have racy status reporting (suggested previously https://github.com/bitcoin/bitcoin/pull/19300#pullrequestreview-435362710 and
https://github.com/bitcoin/bitcoin/issues/19232#issuecomment-645114976) so the race condition that this test tries to trigger just wouldn't exist.

Also for reference there was discussion about fragility of this test when it was added https://github.com/bitcoin/bitcoin/pull/19300#discussion_r441536261

**Comment by PiRK** [comment]
Doesn't that introduce a risk that one of the 3 threads never detects a race and keeps running forever?

**Comment by PiRK** [comment]
nvm, I missed the fact that `got_loading_error` is a global.

**Pull request merged**
