### PR TITLE
net: Hardcoded seeds update for 0.20

### PR DESCRIPTION
**Pull request by laanwj**
Update hardcoded seeds from http://bitcoin.sipa.be/seeds.txt.gz,
according to release process.

Output from makeseeds.py:
```
  IPv4   IPv6  Onion Pass                                               
1364173 244127   2454 Initial
1364173 244127   2454 Skip entries with invalid address
1129552 213117   2345 After removing duplicates
1129548 213117   2345 Skip entries from suspicious hosts
338216 191944   2249 Enforce minimal number of blocks
336851 188993   2189 Require service bit 1
  6998   1520    150 Require minimum uptime
  5682   1290     89 Require a known and recent user agent
  5622   1279     89 Filter out hosts with multiple bitcoin ports
   512    146     89 Look up ASNs and limit results per ASN and per net
```

### CODE REVIEW

**Comment by laanwj** [comment]
Oops, need to update the user agent strings.

**Comment by hebasto** [comment]
Are non-standard port ok?

**Comment by laanwj** [comment]
> Are non-standard port ok?

Yes, that's ok. Might help if ISPs block the standard port.

**Comment by jonasschnelli** [comment]
utACK 5dc165fe5be12b7a43d89137dbfe64b806aaf310 - manually verified some added, removed and kept IPv4 and IPv6 against my [seed dump](https://bitcoin.jonasschnelli.ch/dnsseed.dump).

**Comment by sipa** [comment]
It is suspicious that the change in thd set of onion hosts is almost entirely red.

**Comment by laanwj** [comment]
Last time there was also a problem with onions and the DNS seed (#16999).
I guess we can skip the seeds update if this is strictly worse.

**Comment by laanwj** [comment]
@sipa Now that you say, I was surprised that adding `0.19.x` to the user agents didn't result in any more onion addresses in the final result (still only 70). As if the list is stale?

Maybe if other people with DNS seeds post their list, I can combine them again and see if that gives more active onion addresses.

**Comment by sipa** [comment]
@laanwj Ugh. It seems my crawler wasn't running with Tor enabled. Fixed.

This probably means we'll want to use someone else's data (or even better, combine the results).

**Comment by laanwj** [comment]
@TheBlueMatt @luke-jr @cdecker @Sjors @petertodd @Emzy @jonasschnelli  if possible please upload your DNS seed dump and post it here,especially if your crawler is running with Tor

**Comment by RandyMcMillan** [comment]
> Are non-standard ports ok?

I believe non-standard ports should be encouraged as a fail over. Port blocking on the backbone should be anticipated.

**Comment by Emzy** [comment]
> @TheBlueMatt @luke-jr @cdecker @Sjors @petertodd @Emzy @jonasschnelli if possible please upload your DNS seed dump and post it here,especially if your crawler is running with Tor

[seeds.txt.gz](https://github.com/bitcoin/bitcoin/files/4422725/seeds.txt.gz)
 
Tor is enabled.

**Comment by sipa** [comment]
Our outgoing connection selection is very strongly avoiding non-standard ports (something that's been in the codebase for ages BTW; the original intent was to avoid turning the Bitcoin network into a DDoS service for non-Bitcoin ports).

**Comment by luke-jr** [comment]
http://luke.dashjr.org/programs/bitcoin/files/charts/seeds.txt (162 MB, no Tor)

**Comment by Emzy** [comment]
> @TheBlueMatt @luke-jr @cdecker @Sjors @petertodd @Emzy @jonasschnelli if possible please upload your DNS seed dump and post it here,especially if your crawler is running with Tor

[seeds-emzy.txt.gz](https://github.com/bitcoin/bitcoin/files/4423239/seeds-emzy.txt.gz)

I have deleted the dnsseed.dump an hour ago. So there are only 23 onion addresses in the dump. I will upload the file again later if I got more.

**Comment by Emzy** [comment]
[seeds-emzy.txt.gz](https://github.com/bitcoin/bitcoin/files/4423970/seeds-emzy.txt.gz)
with 67 .onion

**Comment by Emzy** [comment]
[seeds-emzy.txt.gz](https://github.com/bitcoin/bitcoin/files/4426874/seeds-emzy.txt.gz)
now with 369 .onion

**Comment by Sjors** [comment]
[dnsseed.dump.tar.gz](https://github.com/bitcoin/bitcoin/files/4427250/dnsseed.dump.tar.gz) with 1394 onions

**Comment by laanwj** [comment]
Ok, re-did the process with the concatenated files and updated the statistics. Hopefully it's better now (there's a few more onions).

**Comment by Sjors** [comment]
I'm only seeing two green onions in a see of red onions. Maybe loosen the criteria for onion nodes a bit? They don't have amazing up time as seen from my seed, but Tor itself (or my connection to it) might be flaky too.

**Comment by laanwj** [comment]
The uptime requirements for onions are already much more lenient than for IPv4 peers (10% instead of 50%). I could bring them down even more, but, do we need that many hardcoded onion seeds? Seems 89 is pretty ok to me.

(Also, can we do changes to the seeds scripts *between* release please? the issue for that is #17020. Everyone seems to forget about it every time until just before the hurry before a release branch-off)

**Comment by Sjors** [comment]
5% uptime instead of 10% would 3x the number of nodes from my list, but I agree 89 sounds good enough, and 10% is quite bad already.

**Pull request merged**
