### PR TITLE
p2p: add MAX_FEELER_CONNECTIONS constant

### PR DESCRIPTION
**Pull request by fanquake**
Extracted from #16003.

### CODE REVIEW

**Review by hebasto — APPROVED** [review]
ACK 37eb3116bf6d97c4787ba3b7ee29dc96fa742d99

nit: it seems GH does not recognize https://github.com/tryphe as an author. Maybe because of different emails:
```
$ git log --no-merges | grep -A 3 tryphe
Author: tryphe <tryphe@noreply.github.com>
Date:   Wed May 8 04:34:01 2019 -0400

    p2p: add MAX_FEELER_CONNECTIONS constant
--
Author: tryphe <tryphe@users.noreply.github.com>
Date:   Sat May 4 22:01:51 2019 -0400

    remove old bootstrap relevant code
```

**Comment by naumenkogs** [comment]
utACK 37eb311.
Went through the code to check that we do support >1 feelers.

**Comment by practicalswift** [comment]
ACK 37eb3116bf6d97c4787ba3b7ee29dc96fa742d99

**Comment by instagibbs** [comment]
Might be worth including the constant here since I think this is the only other place using the now-unnamed constant:
`src/test/denialofservice_tests.cpp:158:    options.nMaxFeeler = 1;`

ACK https://github.com/bitcoin/bitcoin/pull/18910/commits/37eb3116bf6d97c4787ba3b7ee29dc96fa742d99

**Comment by fanquake** [comment]
> Might be worth including the constant here since I think this is the only other place using the now-unnamed constant:

Added an additional commit to replace that and a couple other constants.

**Comment by naumenkogs** [comment]
utACK e3047ed

**Pull request merged**
