### PR TITLE
ci: Rename Cirrus CI osx_instance to macos_instance

### PR DESCRIPTION
**Pull request by hebasto**
See https://github.com/cirruslabs/cirrus-ci-docs/pull/763.

### CODE REVIEW

**Comment by katesalazar** [comment]
ACK c49e7db8ae771ab97f24e0bf74359ee474a17ddc

**Comment by katesalazar** [comment]
you can use more poignant commit messages

**Comment by MarcoFalke** [comment]
Done

**Comment by katesalazar** [comment]
the ticket name was good enough :D

**Pull request merged**
