### PR TITLE
Make .gitignore ignore src/test/fuzz/fuzz.exe

### PR DESCRIPTION
**Pull request by hebasto**

### CODE REVIEW

**Comment by fanquake** [comment]
Shouldn't this be included by `*.exe` ?

**Comment by hebasto** [comment]
> Shouldn't this be included by `*.exe` ?

Did not dig into the depth, but it does not work.

**Comment by laanwj** [comment]
Strange, as we don't mention any of the other `.exe` explicitly. What's different about the fuzz one?

**Comment by hebasto** [comment]
> Strange, as we don't mention any of the other `.exe` explicitly. What's different about the fuzz one?
> 
> Edit: it's this rule:
> 
> ```
> !src/test/fuzz/*.*
> ```

Right.

**Comment by laanwj** [comment]
Would it work to move that rule above the `*..exe` one?

**Comment by hebasto** [comment]
> Edit: it's this rule:
> 
> ```
> !src/test/fuzz/*.*
> ```
> 
> Why do we need that?

Appears that we do not need it :)

Also s/`src/test/fuzz/*`/`src/test/fuzz/fuzz`/ for explicitly.

**Comment by practicalswift** [comment]
Concept ACK

**Comment by MarcoFalke** [comment]
cr ACK 35da623574ccae99a4bf1ecc215311a0936a417a

**Comment by practicalswift** [comment]
cr ACK 35da623574ccae99a4bf1ecc215311a0936a417a

**Comment by laanwj** [comment]
Posthumous ACK, this is a much better solution

**Pull request merged**
