### PR TITLE
Allow bitcoin-tx to create v2 transactions

### PR DESCRIPTION
**Pull request by btcdrak**
Sync bitcoin-tx with tx version policy

### CODE REVIEW

**Comment by jonasschnelli** [comment]
utACK b0aea8057921f0ed2288cf07048f652c7d6d9cf3

**Comment by instagibbs** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/8932/commits/b0aea8057921f0ed2288cf07048f652c7d6d9cf3

**Comment by petertodd** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/8932/commits/b0aea8057921f0ed2288cf07048f652c7d6d9cf3

**Comment by laanwj** [comment]
utACK b0aea80

**Pull request merged**
