### PR TITLE
SendMoney: use already-calculated balance

### PR DESCRIPTION
**Pull request by instagibbs**

### CODE REVIEW

**Comment by sipa** [comment]
utACK ea83d0098a2eb29a3b1398f3ecf907f7eece1eee

(I wouldn't classify this as trivial though, it actually changes the executed code).

**Comment by instagibbs** [comment]
True, which is why I made sure to run the tests. Changed.

**Review by dcousens — APPROVED** [review]

**Comment by mrbandrews** [comment]
If you were inclined, you could add the following test at line 87 of wallet.py:
assert_raises_message(JSONRPCException, "requires a transaction fee", self.nodes[2].sendtoaddress, self.nodes[2].getnewaddress(), 20.99999999)
Otherwise, ACK

**Review by Jamielee11 — APPROVED** [review]

**Comment by morcos** [comment]
utACK

**Comment by gmaxwell** [comment]
utACK

**Comment by jonasschnelli** [comment]
`CWalletTx` uses a cache for the `GetAvailableCredit()`, but right, `GetBalance` should only be called if really necessary because of the loop under the lock through mapWallet and the `isTrusted()` calls.

utACK ea83d0098a2eb29a3b1398f3ecf907f7eece1eee

**Pull request merged**
