### PR TITLE
Header include guideline

### PR DESCRIPTION
**Pull request by sipa**

### CODE REVIEW

**Review by gmaxwell — APPROVED** [review]
ACK

**Comment by practicalswift** [comment]
ACK!

**Comment by fanquake** [comment]
ACK a090d1c

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/10575/commits/a090d1c1c9c379bce7345ba5b78aa9491e350d0b

**Comment by jonasschnelli** [comment]
Good!
ACK a090d1c1c9c379bce7345ba5b78aa9491e350d0b

**Comment by laanwj** [comment]
Makes sense.

Is there a good way to check/review this, though? Would be useful to add suggestion for reviewing.

I'm also afraid this will generate lots of 'mess around with headers' PRs, so we probably want to add that this holds for new code.

**Comment by practicalswift** [comment]
@laanwj I wrote the following script ...

```bash
#!/bin/bash

for H in $(git grep "" -- "*.h" | cut -f1 -d: | uniq); do
    CPP=${H/%\.h/.cpp}
    if [[ ! -e $CPP ]]; then
        continue
    fi
    cat "$H" "$CPP" | grep -E "^#include " | sort | uniq -c | \
      grep " 2 #include" && echo "$CPP" && echo
done
```

... to identify `.cpp` files that re-include the includes already included in its corresponding `.h` file. See PR #10575.

**Comment by laanwj** [comment]
Well yes but I'm more interested in the first point:

> Every `.cpp` and `.h` file should `#include` every header file it directly uses classes, functions or other
 definitions from, even if those headers are already included indirectly through other headers.

So how to check that a .cpp or .h is using functionality that is only indirectly included? Seems like *a lot* of work to do manually, at least.

**Comment by practicalswift** [comment]
@laanwj Ah, [`iwyu`](https://github.com/include-what-you-use/include-what-you-use) is best-in-class there!

**Comment by ryanofsky** [comment]
Iwyu is great and it would be really nice if it works on bitcoin source. It manages forward declarations as well as includes and will automatically add/remove/convert between them as appropriate.

**Comment by sipa** [comment]
Perhaps we should have iwyu included in our build system, and then refer to it in developer-notes.md?

**Comment by laanwj** [comment]
> Iwyu is great and it would be really nice if it works on bitcoin source

Has anyone tried?

**Pull request merged**
