### PR TITLE
test: add coverage for non-hex value to -minimumchainwork

### PR DESCRIPTION
**Pull request by brunoerg**
This PR adds test coverage for the following init error:
https://github.com/bitcoin/bitcoin/blob/b9ef5a10e2fa4609d048db57b99463305455ebe4/src/init.cpp#L917-L919

Passing a non-hex value to -minimumchainwork should throw an initial error.

### CODE REVIEW

**Review by w0xlt — COMMENTED** [review]
Approach ACK

**Review by kristapsk — APPROVED** [review]
ACK 49fe179f00f2ffa1eb96b7737b6b07c92dc5e865

**Comment by brunoerg** [comment]
Rebased

**Review by kristapsk — APPROVED** [review]
re-ACK ebfc308ea4b8851118e8194d837556bf443c329c

**Comment by laanwj** [comment]
Code review ACK ebfc308ea4b8851118e8194d837556bf443c329c

**Pull request merged**
