### PR TITLE
qt: Fix QCompleter popup regression

### PR DESCRIPTION
**Pull request by hebasto**
The PR #8129 has introduced a regression with the `QCompleter` popup in the Debug window.

How to reproduce:

1.  open the Debug window;
2.  go to the 'Console' tab;
3.  start writing some RPC command and try to pick it from the list using arrow keys, press Enter.

Note that the popup used to display completions is not being closed. To close it they should mouse click somewhere outside of the popup.

The wrong behaviour of the `QCompleter` popup is observed on Linux Mint 19 and Windows 10.
This PR fixes this regression.

Refs:

- #7613
- #7772
- #8129

### CODE REVIEW

**Comment by promag** [comment]
Tested ACK b7df768 on Windows 10.

**Comment by hebasto** [comment]
@Sjors Would you mind to review this PR?

**Comment by Sjors** [comment]
Tested b7df768 on macOS 10.14. It fixes the bug, but introduces a new one: commands get duplicated.
schermafbeelding 2018-10-13 om 15 36 06

**Comment by Sjors** [comment]
tACK 081cc02 for macOS 10.14 / QT 5.11.2. Needs retesting on Windows.

**Comment by hebasto** [comment]
@promag Would you mind re-reviewing this PR?

**Pull request merged**
