### PR TITLE
Return txid even if ATMP fails for new transaction

### PR DESCRIPTION
**Pull request by sipa**

### CODE REVIEW

**Comment by jonasschnelli** [comment]
utACK a0728ccebb155b09cc537c88275662e33c1ab675
Would be nice if someone could write a test for this.

**Comment by morcos** [comment]
utACK b3a7410

I think this needs release notes documenting the change in behavior.

For 0.14.0 (not backport) we should also consider how to pass on the information on whether the tx was accepted to the mempool and if not why not?

**Comment by gmaxwell** [comment]
utACK. Will test.

@morcos  the listtransaction output tells you if the transaction is currently in the mempool, and we log the rejection. Is that covering a lot of your thinking?

**Comment by luke-jr** [comment]
utACK. It may make sense to move broadcasting outside of CommitTransaction entirely, but this is good enough for now (and backport).

**Comment by sdaftuar** [comment]
ACK b3a74100b86423c553ac327f3ea6fdbc2c50890a, wrote up a quick test to exercise the logic:

```
diff --git a/qa/rpc-tests/wallet.py b/qa/rpc-tests/wallet.py
index 3c0dc0f..6435f00 100755
--- a/qa/rpc-tests/wallet.py
+++ b/qa/rpc-tests/wallet.py
@@ -346,5 +346,18 @@ class WalletTest (BitcoinTestFramework):
         assert_equal(coinbase_tx_1["transactions"][0]["blockhash"], blocks[1])
         assert_equal(len(self.nodes[0].listsinceblock(blocks[1])["transactions"]), 0)
 
+        # Test that spending coins doesn't fail as long as balance is high enough.
+        to_send = 0.05
+        txids = []
+        while self.nodes[0].getbalance() > to_send:
+            txids.append(self.nodes[0].sendtoaddress(self.nodes[0].getnewaddress(), to_send))
+
+        mempool = self.nodes[0].getrawmempool()
+        sent_tx_not_in_mempool = False
+        for txid in txids:
+            if (txid not in mempool):
+                sent_tx_not_in_mempool = True
+        assert(sent_tx_not_in_mempool) # otherwise test needs to be updated to cover this case
+
 if __name__ == '__main__':
     WalletTest().main()
```

**Comment by morcos** [comment]
@gmaxwell No, I mean more than that. I think it would be good to inform the user that for some reason his transaction has not be accepted to the mempool.  Perhaps there is no good way to do this without breaking the RPC API, but at the very least we could do it from the GUI.

But to be clear, I do not think that should be a blocker for this.  I'll agree that this is an improvement, I just think we should continue to improve afterwards...

**Comment by gmaxwell** [comment]
ACK

**Comment by CodeShark** [comment]
ACK

**Comment by MarcoFalke** [comment]
utACK b3a74100b86423c553ac327f3ea6fdbc2c50890a

**Comment by MarcoFalke** [comment]
I'd prefer not to merge any test case for this, as a passing test would assert that there is a bug in the code base. Tests are usually written to assert that there are no bugs...

**Comment by morcos** [comment]
@marcofalke what do you mean by that?  There are certainly ways for transactions to not be accepted into the memory pool which aren't bugs and I think it could make sense to verify that a txid is still returned.

**Comment by MarcoFalke** [comment]
@morcos What I mean is that the wallet logic should take care that a transaction is accepted to the mempool. When it is not possible, return early in the wallet logic and don't commit the transaction to the wallet, otherwise it is a bug.

I see the return-txid patch as a temporary workaround and not a solution to the problem. So sure, you could create a unit test to check that a transaction fails ATMP but still returns true when commited, but I don't think it makes sense to create a functional test for this. Note that the test above by sdaftuar relies on bug #9019. Another (maybe minimal) test case could rely on bug #9316. Similarly you could come up with a test that pumps the mempoolminfee above the default wallet fee rate, I assume. Of course one could argue that some of these are features and not bugs, but as long as they appear in conjunction with `-walletbroadcast` enabled, I consider them bugs.

**Comment by morcos** [comment]
@MarcoFalke ah ok, yes I mostly agree.  However I think that too long chains may end up being an exception to that where we want the wallet to generate and save the transaction even if its not accepted to the mempool.  That's obviously after a best efforts try to create the transaction without a too long chain.
  
In any case, I think we both agree nothing more needed on this PR (but release notes still needed)

**Comment by instagibbs** [comment]
@sdaftuar fwiw https://github.com/bitcoin/bitcoin/pull/9262 will no longer change any behavior by default aside from attempt to make shorter chains so that test may be fine

**Comment by instagibbs** [comment]
utACK b3a74100b86423c553ac327f3ea6fdbc2c50890a

**Comment by paveljanik** [comment]
utACK https://github.com/bitcoin/bitcoin/commit/b3a74100b86423c553ac327f3ea6fdbc2c50890a

**Comment by MarcoFalke** [comment]
Backport in #9347 (release notes already merged)

**Pull request merged**
