### PR TITLE
[depends] Latest config.guess and config.sub

### PR DESCRIPTION
**Pull request by fanquake**

### CODE REVIEW

**Comment by laanwj** [comment]
utACK

**Comment by paveljanik** [comment]
ACK

**Comment by laanwj** [comment]
Can you take a look @theuni?

**Comment by theuni** [comment]
Looks good to me. utACK

**Comment by paveljanik** [comment]
Typo `configury` reported to authors.

**Comment by paveljanik** [comment]
... and they fixed it immediately (http://git.savannah.gnu.org/cgit/config.git/commit/?id=1e80063123b47b97d25dfeded8dd92a19dafab66).

**Pull request merged**
