### PR TITLE
build: Make `--with-gui=qt6` configure option available on macOS

### PR DESCRIPTION
**Pull request by hebasto**
This is another (however, not alternative; rather OS-specific) approach to bring Qt 6 to Bitcoin Core GUI users.

In Qt 6 most of the libraries are built as frameworks (by default), therefore, this PR is much less invasive and (I hope) less controversial then bitcoin/bitcoin#24798.

To test this PR on macOS (both Intel-based and Apple Silicon) just
```
# brew remove qt@5
# brew install qt
# ./autogen.sh
# ./configure --with-gui=qt6
# make clean 
# make
# make check
```

The other benefit of this PR is keeping our Qt code base compatible with Qt 6 due to the CI task which runs `--with-gui=qt6`.

Documentation update and guarding calls which are deprecated in Qt 6 are left for follow ups to keep this PR focused on build stuff. 

Based on multiple PRs in the GUI repo which get code base compatible with Qt 6, and only the last two commits belong to this PR.

### CODE REVIEW

**Comment by laanwj** [comment]
I'm not sure, ACK on `--with-gui=qt6` in general but I really don't like the idea of having qt6 support for MacOS only.

**Comment by hebasto** [comment]
> I'm not sure, ACK on `--with-gui=qt6` in general but I really don't like the idea of having qt6 support for MacOS only. For one, I can't test it.

The other part, having Qt 6 in depends, is in #24798.

Building with dynamical linking against system Qt 6 on Linux does not look like a task worth taking on without CMake.

**Comment by fanquake** [comment]
Concept ~0. It feels like support for Qt6 is trying to be pushed into our codebase before it's ready / generally usable. I'm not sure why we need to add support, right now, for only a specific package manager, on a single OS.

**Comment by fanquake** [comment]
> So it looks like macOS installs QT 6 by default if you do brew install qt.

This has already been the case for more than a year: #21346.

> So we need to either tell users to install qt@5 

We already do. https://github.com/bitcoin/bitcoin/blob/master/doc/build-osx.md#qt

**Comment by hebasto** [comment]
> So we need to ... tell users to install qt@5

We [do](https://github.com/bitcoin/bitcoin/blob/master/doc/build-osx.md#qt) :)

**Comment by Sjors** [comment]
Oh wait, brew keeps 5 around.

**Comment by hebasto** [comment]
CMake is going to make it much [more elegant](https://github.com/hebasto/bitcoin/pull/3#issuecomment-1153287048).

**Pull request closed without merging**
