### PR TITLE
[REST] getutxos REST command (based on Bip64)

### PR DESCRIPTION
**Pull request by jonasschnelli**
has parts of @mikehearn #4351
- allows querying the utxos over REST
- same binary input and outputs as mentioned in Bip64
- input format = output format
- various rpc/rest regtests

### CODE REVIEW

**Comment by laanwj** [comment]
utACK

**Comment by jonasschnelli** [comment]
rebased

**Comment by paveljanik** [comment]
@jonasschnelli can you please add some description of this API to https://github.com/bitcoin/bitcoin/blob/master/doc/REST-interface.md

**Comment by jonasschnelli** [comment]
@paveljanik i just added a basic documentation. Will extend the documentation if there are enough ACKs.

**Comment by paveljanik** [comment]
ACK

Sample calls:

```sh
# main
$ curl --data '{}' localhost:8332/rest/getutxos/.json 2>/dev/null | json_pp 
{
   "chaintipHash" : "000000000000000008596bd7ca15fb534a119cd5d219508df39d95e2272c6b4e",
   "chainHeight" : 346243,
   "utxos" : [],
   "bitmap" : ""
}

# test
$ curl --data '{"checkmempool":false,"outpoints":[{"txid":"b2cdfd7b89def827ff8af7cd9bff7627ff72e5e8b0f71210f92ea7a4000c5d75","n":0}]}' localhost:18332/rest/getutxos/.json 2>/dev/null | json_pp
{
   "chaintipHash" : "00000000fb01a7f3745a717f8caebee056c484e6e0bfe4a9591c235bb70506fb",
   "chainHeight" : 325347,
   "utxos" : [],
   "bitmap" : "0"
}
$ curl --data '{"checkmempool":true,"outpoints":[{"txid":"b2cdfd7b89def827ff8af7cd9bff7627ff72e5e8b0f71210f92ea7a4000c5d75","n":0}]}' localhost:18332/rest/getutxos/.json 2>/dev/null | json_pp
{
   "chaintipHash" : "00000000fb01a7f3745a717f8caebee056c484e6e0bfe4a9591c235bb70506fb",
   "chainHeight" : 325347,
   "utxos" : [
      {
         "scriptPubKey" : {
            "addresses" : [
               "mi7as51dvLJsizWnTMurtRmrP8hG2m1XvD"
            ],
            "type" : "pubkeyhash",
            "hex" : "76a9141c7cebb529b86a04c683dfa87be49de35bcf589e88ac",
            "reqSigs" : 1,
            "asm" : "OP_DUP OP_HASH160 1c7cebb529b86a04c683dfa87be49de35bcf589e OP_EQUALVERIFY OP_CHECKSIG"
         },
         "value" : 8.8687,
         "height" : 2147483647,
         "txvers" : 1
      }
   ],
   "bitmap" : "1"
}
$ 
```

**Comment by jonasschnelli** [comment]
Updated. Fixed setgenerate/generate issues after #5957

**Pull request merged**
