### PR TITLE
Common argument defaults for NODE_BLOOM stuff and -wallet

### PR DESCRIPTION
**Pull request by luke-jr**
Can we stop adding more of these to fix? :p

### CODE REVIEW

**Comment by paveljanik** [comment]
When you are at this...

These:
```
init.cpp:    strUsage += HelpMessageOpt("-salvagewallet", _("Attempt to recover private keys from a corrupt wallet.dat on startup"));
init.cpp:                uiInterface.InitMessage(_("Error loading wallet.dat: Wallet corrupted"));
init.cpp:                strErrors << _("Error loading wallet.dat: Wallet corrupted") << "\n";
init.cpp:                InitWarning(_("Error reading wallet.dat! All keys read correctly, but transaction data"
init.cpp:                strErrors << strprintf(_("Error loading wallet.dat: Wallet requires newer version of %s"), _(PACKAGE_NAME)) << "\n";
init.cpp:                strErrors << _("Error loading wallet.dat") << "\n";
```
should probably use the selected `wallet.dat` file name (`strWalletFile`) instead of the hardcoded name. And there are other such cases.

**Comment by laanwj** [comment]
Concept ACK
`-enforcenodebloom` is going away soon (#6641), so I don't think it needs any fixes/improvements

**Comment by pstratem** [comment]
utACK 1fb91b3496f2f07bbace1f9f8e716f7f62d889e6

**Comment by dcousens** [comment]
utACK 1fb91b3

**Comment by laanwj** [comment]
@paveljanik I think the `-salvagewallet` help message should simply say 'wallet', not 'wallet.dat'.
For the warnings and errors you're right and it'd be better to use the actual wallet file name.

**Pull request merged**
