### PR TITLE
Block Wallet RPCs until wallet is synced to our current chain

### LINKED ISSUE #9148: Wallet RPCs can return stale info due to ProcessNewBlock Race
I know this issue has been pointed out a few times, but didnt see an issue for it here.

After #7946, if you connect a block, then immediately make some RPC request to get the current block information (eg if you're polling to see when a new block comes in) and then immediately request wallet balance/utxos/etc, the information returned can be up-to-date as of the previous block, not the newly-connected one. This is easy to see in some simple test-cases, and I assume would effect some various use-cases that people might be using in the wild. This is a regression in master, so we should fix it for 0.14.

I think we need to be moving more towards these kinds of callback happening in a background thread anyway, so we have two options - change the API significantly and add some kind of "getwalletchainstate" so that people can wait for wallet to be caught up or add a "sleep until wallet is caught up with chainstate as of entry to RPC function" wrapper to wallet calls.

I generally prefer the second option becuase I think the first will create a somewhat confusing API that people are likely to fuck up, and the sleep should generally never be too long unless your wallet is super slow/too many keys.

### PR DESCRIPTION
**Pull request by TheBlueMatt**
This fixes #9148, though with a bit more code than I intended.

There were two issues: a) wallet could return data based on partial block processing, because there were no locks between SyncTransaction calls, which is fixed relatively easily. and b) you could be busy-waiting on getbestblockheight , and call getbalance immediately after that changed, getting your balance as of the previous block instead of the new one, which is a regression in master from 0.13.

To resolve the second, we introduce a primitive to block until the wallet has caught up either with the current chain, or the best chain (to resolve a simple race condition).

This should probably get a test case, because I know you can see a in simple tests, but I'm not 100% sure about b.

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
@morcos points out that the cs_main holding at for the block's transaction's processing loop might interfere with all the fancy new fast block-response networking stuff we have going in 0.14. Sadly, because cs_main must come before cs_wallet, this isnt trivial to fix.

One easy fix is to add another cs_wallet - cs_wallet_before_main which is locked here to emulate the behavior prior to the lock split in #7946.

**Comment by TheBlueMatt** [comment]
Thinking about it more, most of those things will not be running at that time anyway, because we only have one message processing thread. This may have adverse effects on miners who run with a wallet, but aside from that I dont think there is really all that much cs_main contention here (and certainly wouldn't be a regression from 0.13). We can add a cs_wallet_before_main when we split message processing thread.

**Comment by morcos** [comment]
utACK?

I think the code is right, but I wish there were a bit more straightforward way of doing this.

**Comment by TheBlueMatt** [comment]
Closing in favor of #9583 for 0.14. Will open a new PR with a bigger set of changes that also addresses the concerns in #9584.

**Pull request closed without merging**
