### PR TITLE
test: remove flags verification since it has a fixed value

### PR DESCRIPTION
**Pull request by brunoerg**
This PR removes unnecessary flags verification since its value has been fixed (3).

### CODE REVIEW

**Comment by MarcoFalke** [comment]
It might be better to add a comment that the function body is copied 1-1 from somewhere else

**Comment by brunoerg** [comment]
@MarcoFalke why? is this a pattern?

**Comment by MarcoFalke** [comment]
Yes, I believe this is the witness serialize pattern that Bitcoin Core uses in the source code and tests.

**Comment by laanwj** [comment]
It looks like there is no agreement to make this change. So closing.

**Pull request closed without merging**
