### PR TITLE
[do not merge] travis gdb parachute for #9825

### PR DESCRIPTION
**Pull request by laanwj**
Hopefully this can give us a useful traceback.

### CODE REVIEW

**Comment by paveljanik** [comment]
Looks like gdb is missing

**Comment by laanwj** [comment]
yep, added that now

**Comment by laanwj** [comment]
Hm, to make this iterate faster, could change the builds to only build test_bitcoin. Let's just wait for this to finish first to see if anything else needs changing.

**Comment by laanwj** [comment]
Ugh the no-wallet build was rebuilding all dependencies (including Qt). Cancelled that. Hopefully it won't do that every time.

**Comment by laanwj** [comment]
Looks like I caught it in the act now:
```
test_bitcoin: /home/travis/build/bitcoin/bitcoin/depends/i686-pc-linux-gnu/share/../include/boost/thread/pthread/recursive_mutex.hpp:113: void boost::recursive_mutex::lock(): Assertion `!pthread_mutex_lock(&m)' failed.
Program received signal SIGABRT, Aborted.
Thread 41 (Thread 0xec3a7b40 (LWP 21516)):
Python Exception <class 'gdb.MemoryError'> Cannot access memory at address 0x24: 
#0  0xf7fdacd9 in ?? ()
Error while running hook_stop:
Cannot access memory at address 0x24
0xf7fdacd9 in ?? ()
```
Unfortunately, the traceback is everything but useful.

**Comment by laanwj** [comment]
I'm slightly optimistic that this has been solved by #9875. If the bug rears its head again I'll reopen.

**Comment by ryanofsky** [comment]
Maybe another thing to add would be --loglevel=all to test_bitcoin
http://www.boost.org/doc/libs/1_63_0/libs/test/doc/html/boost_test/utf_reference/rt_param_reference/log_level.html

**Pull request closed without merging**
