### PR TITLE
[26.x] backports and final changes for 26.2rc1

### PR DESCRIPTION
**Pull request by glozow**
Backports + release notes for:
- #30151 

And final changes for 26.2rc1:
- build changes
- manpages
- non-removal translations updates

### CODE REVIEW

**Comment by hebasto** [comment]
@glozow 

Feel free to pick up the https://github.com/hebasto/bitcoin/commit/a586d703dce4c6fba95696ae978d9711a355d7d6 commit from the https://github.com/hebasto/bitcoin/commits/pr30260/0610 branch to pull the recent translations from the Transifex website.

Unfortunately, more translations have been vandalized (

**Comment by glozow** [comment]
> Feel free to pick up the [hebasto@a586d70](https://github.com/hebasto/bitcoin/commit/a586d703dce4c6fba95696ae978d9711a355d7d6) commit from the https://github.com/hebasto/bitcoin/commits/pr30260/0610 branch to pull the recent translations from the Transifex website.

Thanks @hebasto! I've cherry-picked that with a minor change to the commit message

**Comment by hebasto** [comment]
The native Windows CI fails due to a [broken Windows image](https://github.com/actions/runner-images/issues/10004).

**Review by stickies-v — APPROVED** [review]
ACK 7ca424f8e651707effe1380aaf72d9ad0e97aa18

I checked that:
- backport is clean
- manpages are identical to mine
- translations are identical to mine, except for the removal of the languages mentioned in the commit message, which appears to be vandalism
- release notes are correct

**Review by fanquake — APPROVED** [review]
ACK 7ca424f8e651707effe1380aaf72d9ad0e97aa18

**Pull request merged**
