### PR TITLE
Backports for 0.14.3

### PR DESCRIPTION
**Pull request by luke-jr**
Sorry this is late. It should have backports of everything from PRs 10234..10495, except for #10318, 965a12442746e99247e5ce0f43fba8e3e149cae4, and 513da90cdd8463964e8c430b25f4326defc0bc96 which seem too complex for a trivial backport.

### CODE REVIEW

**Comment by luke-jr** [comment]
Had to back out 965a12442746e99247e5ce0f43fba8e3e149cae4 and 513da90cdd8463964e8c430b25f4326defc0bc96 due to incompatibilities.

**Comment by laanwj** [comment]
Maybe leave this for 0.14.3? We're already in the 0.14.2 rc cycle, which I think is too late to add so much.

**Comment by luke-jr** [comment]
I don't see anything too critical here, so fine with me if it waits for 0.14.3.

**Comment by fanquake** [comment]
Moved to 0.14.3 milestone.

**Comment by fanquake** [comment]
Does anything new need to be added here?

**Comment by luke-jr** [comment]
I haven't reviewed anything since nearly a month ago. Newer stuff can get another PR?

**Comment by laanwj** [comment]
Yes, if people agree with the list of PRs backported here (didn't find anything objectionable in a quick scan, at least) and they're backported properly this should be merged.

**Comment by fanquake** [comment]
utACK 	76f9cf9

**Comment by laanwj** [comment]
utACK ff274d3

**Pull request merged**
