### PR TITLE
refactor: Use [[maybe_unused]] attribute

### PR DESCRIPTION
**Pull request by hebasto**
This change is required for bitcoin/bitcoin#24773 as it prevents MSVC yelling about "warning C4551: function call missing argument list".

But it is useful by itself as it makes code more concise and readable.

### CODE REVIEW

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/bitcoin/bitcoin/pull/24772/commits/07ddecb84e6097684fa56cfc79c8c2aad76f6604

**Comment by Empact** [comment]
Code review ACK 07ddecb84e6097684fa56cfc79c8c2aad76f6604

**Review by w0xlt — APPROVED** [review]
ACK 07ddecb

**Comment by laanwj** [comment]
Code review ACK 07ddecb84e6097684fa56cfc79c8c2aad76f6604

**Pull request merged**
