### PR TITLE
CChainState -> Chainstate

### PR DESCRIPTION
**Pull request by jamesob**
Alright alright alright, I know: we hate refactors. We especially hate cosmetic refactors. 

Nobody knows better than I that changing broad swaths of code out from under our already-abused collaborators, only to send a cascade of rebase bankruptcies, is annoying at best and sadistic at worst. And for a rename! The indignation!

But just for a second, imagine yourself. Programming `bitcoin/bitcoin`, on a sandy beach beneath a lapis lazuli sky. You go to type the name of what is probably the most commonly used data structure in the codebase, and you *only hit shift once*. 

What could you do in such a world? You could do anything. [The only limit is yourself.](https://zombo.com/)

---

So maybe you like the idea of this patch but really don't want to deal with rebasing. You're in luck! 

Here're the commands that will bail you out of rebase bankruptcy:

```sh
git rebase -i $(git merge-base HEAD master) \
  -x 'sed -i "s/CChainState/Chainstate/g" $(git ls-files | grep -E ".*\.(py|cpp|h)$") && git commit --amend --no-edit'
# <commit changed?>
git add -u && git rebase --continue
```

---

~~Anyway I'm not sure how serious I am about this, but I figured it was worth proposing.~~ I have decided I am very serious about this.

Maybe we can have nice things every once in a while?

### CODE REVIEW

**Comment by jonatack** [comment]
Ok, where is @jamesob and what have you done to him.

**Comment by glozow** [comment]
Concept ACK, but need song-and-dance interpretation of the PR description

**Comment by jonatack** [comment]
I'm sort of tepid on whether this is worth doing, but supposing it were, I think I'd prefer ChainState over Chainstate. The reason/question is, are words like "chain state", "fee rate", and "block hash" each one word or two? For me, and maybe for people not closely familiar since years with Bitcoin development, they are two words--at least originally, which I guess is why there are classes in the codebase like CChainState and CFeeRate. I usually grep case-indifferently anyway. Just one weakly held light opinion.

**Comment by jb55** [comment]
ACK 5977234384da1f52475fc8165c52830750bf7d2a

**Comment by michaelfolkson** [comment]
I was reading through some of @jonatack's [notes](https://github.com/jonatack/bitcoin-development/blob/master/notes.txt#L582) and found this old quote from Greg Maxwell:

> I reiterate: the background level of refactors, style changes, cleanups, and other related activity is actively repelling multiple long term contributors, myself included. I beg: give it a bit of a rest, we have so many other things that are crying for our attention and our resolve. We should try to find some initiatives that we all feel more excited about, success with them would make it easier to work on other things... but right now a big style change is just not a unifying effort.

I don't have a strong enough opinion to NACK this PR but the above seems to add some historical context behind previous attempts to do renames like this which may be helpful for other reviewers.

**Comment by ajtowns** [comment]
Introducing "Stockholm syndrome: the PR" ? We have `ChainstateManager` already, so while I agree with @jonatack that it's weird treating "chainstate" as one word, at least this is slightly reducing an inconsistency. Don't really see the benefits outweighing the costs here.

**Review by ryanofsky — APPROVED** [review]
Code review ACK 5977234384da1f52475fc8165c52830750bf7d2a

https://www.youtube.com/watch?v=j7OHG7tHrNM

**Comment by ryanofsky** [comment]
Also "ChainState" looks better than "Chainstate", establishes it as a noun, and is confusing to no one.

**Comment by jb55** [comment]
On Tue, Mar 15, 2022 at 07:12:29AM -0700, Michael Folkson wrote:
>I was reading through some of @jonatack's
>[notes](https://github.com/jonatack/bitcoin-development/blob/master/notes.txt#L582)
>and found this old quote from Greg Maxwell:
>
>> I reiterate: the background level of refactors, style changes,
>> cleanups, and other related activity is actively repelling multiple
>> long term contributors, myself included. I beg: give it a bit of a
>> rest, we have so many other things that are crying for our attention
>> and our resolve. We should try to find some initiatives that we all
>> feel more excited about, success with them would make it easier to
>> work on other things... but right now a big style change is just not
>> a unifying effort.
>
>I don't have a strong enough opinion to NACK this PR but the above
>seems to add some historical context behind previous attempts to do
>renames like this which may be helpful for other reviewers.

I ACK'd because I think this irrational fear of refactors is holding
bitcoin's code quality back. Not saying this PR is the best example, I
agree that style changes aren't as productive, but trivial refactors and
improvements that improve code quality in non-consensus critical code
shouldn't take years to merge.

I get that we are being conservative, but I think the bigger factor to
the brain drain is the fact that people put in effort to do small code
quality improvements just to wait years to even see it merged.

Now people don't even bother to improve code quality because of this
weird meme that refactors don't matter, and only new features matter.
Perhaps I'm off base here since I'm not a fulltime core dev but that's
just been my perspective watching core dev over the past decade.

**Comment by MarcoFalke** [comment]
(Not a comment on the changes here, just my approach to renames)

Personally I try to bundle such rename refactors with other changes that make sense on their own. When there is a large or otherwise breaking code change, scripted-diff renames can be appended at minimal extra cost. Sometimes they are even the better choice, to create compile failures for silent merge conflicts that may otherwise sneak in unnoticed. They wouldn't increase the number of conflicts (as the code is touched anyway for other reasons) and the review spent on the scripted-diff is negligible compared to the review spent on the other changes.

**Review by promag — COMMENTED** [review]
Code review ACK 5977234384da1f52475fc8165c52830750bf7d2a.

Feel free to rename all remaining C-prefixed classes  💣

**Comment by jamesob** [comment]
> found this old quote from Greg Maxwell

There's a major difference in review requirements/risk/annoyance between "I shuffled a bunch of code around and changed some software engineeringy design patterns/C++ features because it just *feels* cleaner" vs. "here's a scripted-diff that is trivial to review." The former is unadvisable, and I wouldn't propose something in that vein unless it was a part of significant feature work which had been motivated with a decent prototype of the end-state. 

I well remember the sentiment that Greg is talking about in the quote; there was good reason for what he said, both at the time and now. But the effort required to review this struck me as negligible, and I can't help but indulge some contrarianism now and again.

I won't be heartbroken if we close this thing but man do I hate typing `CChainState`.

**Review by ryanofsky — APPROVED** [review]
Code review ACK e2c9115af2db4b5aa1f1d2333946fb22912e500d. Just rebased since last review

**Comment by jamesob** [comment]
image

**Comment by MarcoFalke** [comment]
I sometimes see myself running into compile errors when typing `ChainStateManager`, or `CChainstate`, so I think it makes sense to somehow improve the consistency here. Also, the merge conflicts right now are currently as minimal as they can get.

Any reason why there are two commits and not a single one? A `sed ... $(git grep -l CChainState ':(exclude)doc/release-notes*')` should be sufficient.

**Comment by jamesob** [comment]
@MarcoFalke thanks! Pushed.

**Comment by MarcoFalke** [comment]
cr ACK 00eeb31c7660e2c28f189f77a6905dee946ef408

**Comment by hebasto** [comment]
Concept ACK.

**Review by hebasto — APPROVED** [review]
ACK 00eeb31c7660e2c28f189f77a6905dee946ef408

**Review by glozow — COMMENTED** [review]
ACK 00eeb31c7660e2c28f189f77a6905dee946ef408, thanks for being the one to propose this

**Review by w0xlt — APPROVED** [review]
ACK https://github.com/bitcoin/bitcoin/pull/24513/commits/00eeb31c7660e2c28f189f77a6905dee946ef408

**Comment by jamesob** [comment]
RFM?

**Pull request merged**
