### PR TITLE
[0.21.1]: rc1 Backports

### PR DESCRIPTION
**Pull request by maflcko**
Current backports for *0.21.1*.

One conflict was in the test case.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Some gui changes that might be good to include: https://github.com/bitcoin-core/gui/milestone/3

**Comment by laanwj** [comment]
Commit list ACK 6dc58e99457fe4609fa3c401e89f98c92dbd9878

**Comment by gruve-p** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/20901/commits/08dada84565ea5f49127123e356c82a150626f3c

**Comment by jonatack** [comment]
If docs fixes are backportable, maybe #21384.

**Comment by MarcoFalke** [comment]
Fixed fuzz build failure and appveyor ci bug. This is now ready for review/merge.

Should be relatively easy to review, because most commits are clean cherry-picks beside one or two trivial conflicts.


<!--

16209b1b19

fa4e088cbac035b8029a10b492849540150d0622

bec7f2caf76901a33dcdd2c3bf976f3954131666


0b294c0ba84f2993db71f4b8c3cb23ba3c45a66b

**Comment by ajtowns** [comment]
ACK 5a2d98c640cf308d3c7e85ba51fbb7e84f99322a -- checked 'rebased-from' patches are in master, and rebased patches are clean rebases (except for the first one which changes `""s` to `std::string("")` to avoid c++17 dependency). commits seem fine, but haven't reviewed in detail.

**Review by fanquake — APPROVED** [review]
ACK 5a2d98c640cf308d3c7e85ba51fbb7e84f99322a - branched off `0.21` and redid the backports. Minor conflict in c33fbab25c82b6a18773b80e8b355c987066ae5a. The diff between my branch and #20901 was just in release notes, `_CLIENT_VERSION_RC` (#20901 branched before 95ea54ba089610019a74c1176a2c7c0dba144b1c) and #21490 which has already been merged into `0.21`.

**Pull request merged**
