### PR TITLE
Add LIFETIMEBOUND to CScript where needed

### PR DESCRIPTION
**Pull request by maflcko**
Without this, stack-use-after-scope can only be detected at runtime with ASan or code review, both of which are expensive.

Use `LIFETIMEBOUND` to turn this error into a compile warning.

See https://releases.llvm.org/12.0.0/tools/clang/docs/AttributeReference.html#lifetimebound

Example:

```cpp
const CScript a{WITH_LOCK(::cs_main, return CScript{} << OP_0 << OP_1)};
```

Before: (no warning)
After:

```
warning: returning reference to local temporary object [-Wreturn-stack-address]
    const CScript a{WITH_LOCK(::cs_main, return CScript{} << OP_0 << OP_1)};
                                                ^~~~~~~~~
./sync.h:276:65: note: expanded from macro 'WITH_LOCK'
#define WITH_LOCK(cs, code) [&]() -> decltype(auto) { LOCK(cs); code; }()
                                                                ^~~~

### CODE REVIEW

**Comment by sipa** [comment]
Interesting, I wouldn't have considered using `lifetimebound` for those, but it makes sense.

utACK fabcaf39cd1516923c818b382ee3478b340f3db7.

My understanding is that this cannot introduce bugs if it compiles with issues, as the attribute only adds warning/errors.

**Comment by picopa88** [comment]
Sometimes the merge is not fully synchronized, sometimes I have had a few problems with this merge. It gives unconsolidated results and omits the backup of one of the data, which only happens occasionally but it will bring unnecessary [slitherio](https://slitherio.online) inconvenience.

**Comment by fanquake** [comment]
@theuni want to take a look here?

**Comment by sipa** [comment]
utACK

**Comment by theuni** [comment]
Concept ACK/utACK. I guess ideally we'd annotate anywhere we return references to `*this` or `*this.foo`?

I tried switching the return type from `decltype(auto)` to `auto`, which works around this problem by allowing copies to be made as a typical `return` would, but that disables the ability to bind to a legit returned reference. However, it does have the nice side-effect of showing where these annotations would be useful :)

The one it turned up is `ChainstateManager::InitializeChainstate`, maybe add an annotation there as well?

**Comment by MarcoFalke** [comment]
> Concept ACK/utACK. I guess ideally we'd annotate anywhere we return references to *this or *this.foo?

Correct. I think where `foo` is a (trivial?) built-in type, the annotation isn't needed because at least clang will figure it out by itself. Though, it shouldn't hurt, so maybe someone writes a clang-tidy script to do the refactor in a follow-up?

> The one it turned up is ChainstateManager::InitializeChainstate, maybe add an annotation there as well?

Thanks, added a commit. Can be tested with this snippet:

```
warning: returning reference to local temporary object [-Wreturn-stack-address]
    CChainState& c1 = WITH_LOCK(::cs_main, return ChainstateManager{}.InitializeChainstate(&mempool));
                                                  ^~~~~~~~~~~~~~~~~~~
./sync.h:276:65: note: expanded from macro 'WITH_LOCK'
#define WITH_LOCK(cs, code) [&]() -> decltype(auto) { LOCK(cs); code; }()
                                                                ^~~~
1 warning generated.

**Comment by theuni** [comment]
utACK fa7e6c56f58678b310898a158053ee9ff8b27fe7.

**Review by jonatack — COMMENTED** [review]
Light ACK fa7e6c56f58678b310898a158053ee9ff8b27fe7 debug build with clang 13, reproduced the example compiler warning in the pull description, and briefly looked at `clang::lifetimebound` support in earlier versions of clang; it is in clang 7 (https://releases.llvm.org/7.0.0/tools/clang/docs/AttributeReference.html#lifetimebound-clang-lifetimebound), did not see references to it in earlier docs

**Pull request merged**
