### PR TITLE
[gitian] Alphabetize signing keys & add kallewoof key

### PR DESCRIPTION
**Pull request by kallewoof**
The docs require 2 sigs before merging, but I'm making the PR now so I don't forget about it.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Please sort by second column

**Comment by MeshCollider** [comment]
Should be sorted by name rather than appended at the bottom :)

**Comment by MeshCollider** [comment]
@MarcoFalke it appears the current list sorting is somewhat inconsistent, why are some users sorted by first name and others by second?

**Comment by fanquake** [comment]
@kallewoof Can you link the PR for your sigs you've submitted to the gitian sigs repo here as well.

**Comment by kallewoof** [comment]
@fanquake https://github.com/bitcoin-core/gitian.sigs/pull/706

**Comment by MarcoFalke** [comment]
Thanks for sorting ;)

**Comment by fanquake** [comment]
utACK e690cf4

**Comment by MarcoFalke** [comment]
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

utACK e690cf4b860a19810de8f6ac645fc86d2f7c56b4
-----BEGIN PGP SIGNATURE-----

iQGcBAEBCgAGBQJaoAQwAAoJEM4rdWl+aaVIL5AMAI07mu2PlzRuz+1eD5Q6Ut3b
fioNPcoswrnuHGHTsGZjg5sFwHCwC3UMQH4ulLDRee6aRb7nAOnjPK3tm6fZw78M
noWk1VCjV1GLqmRxFiClpQoS/hM6F7jLgYVeuPbsIjwV0BPKXS0JKBMbp+saFJQe
EshlSB4L2teSq8Up8FzRjudzBYvuaC/Jxxlpnfu+dMQdzAK2SJY40DaY6tELyOOO
kUUpAvY35lDsZw3V7JUjqrGEIhspoMvrkk5wEC1f2Zvy+7RaFKOnZTwWDnrOuzRw
IICfmNFVo5npd5hWOwSTH4iYQvuo7AE6yks9E9/AzaG9848hyEABWdGb3fe0KwHM
g4jn7Fkw4evxiTT7VdDOLBHzRiYOAIsHk/O2iIr+E4MB8kcvorUOqIvVmDIBv9RT
cYTTrHei5L0FdVpuTSaLLY9i2BGUXj+4uvmKw4RcpnKxOTKa7qcXD2+wfVHxMULu
r4vloeb0G+Kmi1weLUQeWV+Zgc2Kk4FXNWgVO5391g==
=MVe3
-----END PGP SIGNATURE-----

**Pull request merged**
