### PR TITLE
[Doc] importmulti: add missing description of keypool option

### PR DESCRIPTION
**Pull request by harding**
Option was added in #14075 but not documented there.

CC: @achow101

### CODE REVIEW

**Comment by MeshCollider** [comment]
utACK https://github.com/bitcoin/bitcoin/commit/a607c9ae4c2730fca5ce340c400c95c87e498a7c

**Comment by achow101** [comment]
Whoops.

utACK a607c9ae4c2730fca5ce340c400c95c87e498a7c

**Comment by max00x** [comment]
ในวันที่ อา. 17 ก.พ. 2019 07:18 น. Andrew Chow <notifications@github.com
เขียนว่า:

**Comment by fanquake** [comment]
utACK a607c9a

**Pull request merged**
