### PR TITLE
Names: BIP9 vs versionbits

### PR DESCRIPTION
**Pull request by jtimon**
Whether bip8 it's adopted or not it seems clear bip9 was flawed in its assumptions, the version bit part was right and will be continued by proposed extensions.

This should be orthogonal to #10462, but maybe it helps in review before or after and it's better documentation long term.

### CODE REVIEW

**Comment by shaolinfry** [comment]
Can someone restart the two failed jobs, they look like random Travis related fails.

**Comment by fanquake** [comment]
Restarted both jobs, for reference the errors were:
```
stdout:
2017-05-27 01:32:40.308000 TestFramework (INFO): Initializing test directory /tmp/bitcoin_test_runner_20170527_013135/p2p-compactblocks_160
2017-05-27 01:32:40.564000 TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/util.py", line 281, in start_nodes
    rpcs.append(start_node(i, dirname, extra_args[i], rpchost, timewait=timewait, binary=binary[i]))
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/util.py", line 242, in start_node
    wait_for_bitcoind_start(bitcoind_processes[i], url, i)
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/util.py", line 216, in wait_for_bitcoind_start
    raise Exception('bitcoind exited with status %i during initialization' % process.returncode)
Exception: bitcoind exited with status 1 during initialization
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 146, in main
    self.setup_network()
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 81, in setup_network
    self.setup_nodes()
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 94, in setup_nodes
    self.nodes = start_nodes(self.num_nodes, self.options.tmpdir, extra_args)
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/util.py", line 283, in start_nodes
    stop_nodes(rpcs)
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/util.py", line 303, in stop_nodes
    assert not bitcoind_processes.values() # All connections must be gone now
AssertionError
2017-05-27 01:32:40.565000 TestFramework (INFO): Stopping nodes
stderr:
************************
EXCEPTION: St12out_of_range       
map::at       
bitcoin in AppInit()       
Traceback (most recent call last):
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/test/functional/p2p-compactblocks.py", line 945, in <module>
    CompactBlocksTest().main()
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 162, in main
    self.stop_nodes()
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 206, in stop_nodes
    stop_nodes(self.nodes)
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/util.py", line 301, in stop_nodes
    for i, node in enumerate(nodes):
TypeError: 'NoneType' object is not iterable
.......................................................
p2p-segwit.py failed, Duration: 5 s
stdout:
2017-05-27 01:33:04.891000 TestFramework (INFO): Initializing test directory /tmp/bitcoin_test_runner_20170527_013135/p2p-segwit_156
2017-05-27 01:33:10.047000 TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/util.py", line 281, in start_nodes
    rpcs.append(start_node(i, dirname, extra_args[i], rpchost, timewait=timewait, binary=binary[i]))
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/util.py", line 242, in start_node
    wait_for_bitcoind_start(bitcoind_processes[i], url, i)
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/util.py", line 216, in wait_for_bitcoind_start
    raise Exception('bitcoind exited with status %i during initialization' % process.returncode)
Exception: bitcoind exited with status 1 during initialization
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 146, in main
    self.setup_network()
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/test/functional/p2p-segwit.py", line 120, in setup_network
    self.setup_nodes()
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 94, in setup_nodes
    self.nodes = start_nodes(self.num_nodes, self.options.tmpdir, extra_args)
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/util.py", line 283, in start_nodes
    stop_nodes(rpcs)
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/util.py", line 303, in stop_nodes
    assert not bitcoind_processes.values() # All connections must be gone now
AssertionError
2017-05-27 01:33:10.048000 TestFramework (INFO): Stopping nodes
stderr:
************************
EXCEPTION: St12out_of_range       
map::at       
bitcoin in AppInit()       
Traceback (most recent call last):
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/test/functional/p2p-segwit.py", line 1952, in <module>
    SegWitTest().main()
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 162, in main
    self.stop_nodes()
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 206, in stop_nodes
    stop_nodes(self.nodes)
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/util.py", line 301, in stop_nodes
    for i, node in enumerate(nodes):
TypeError: 'NoneType' object is not iterable
```

**Comment by jtimon** [comment]
Sorry, the error was just one s/-bip9params/-vbparams/ lost in rebase, not a problem with travis. Updated.

**Comment by shaolinfry** [comment]
@fanquake can you rerun Travis - looks like the VM errored and stopped the build process prematurely.

utACK assuming they pass.

**Comment by fanquake** [comment]
@shaolinfry Restarted, looks like they are all passing now.

**Comment by shaolinfry** [comment]
utACK b463bc9

**Comment by laanwj** [comment]
Concept ACK, I think this naming is better because it is more general.

**Comment by benma** [comment]
utACK b463bc9

**Comment by instagibbs** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/10463/commits/b463bc9215192e6fd93336fdca51778e9aa23d64

**Pull request merged**
