### PR TITLE
[28.x] Backports & 28.1rc1

### PR DESCRIPTION
**Pull request by fanquake**
Backports:
* #30568
* #31007
* #31013
* #31016
* #31035
* #31166

Contains:
* A commit to do the same as #31307.

### CODE REVIEW

**Review by willcl-ark — COMMENTED** [review]
These backports look clean to me.

Due to how my helper script parses the diffs between originals and backports I noticed that in: "addrman: change nid_type from int to int64_t"  4c1d74b60c8aee9702e2fe53ea9e680cc74c38dc, the commit message in this backport references the corrent PR, but wrong commit, it should be:

```diff
- Rebased-From: 051ba3290e30e210bfc50dea974063053313ad3e
+ Rebased-From: 51f7668d31e2624e41c7ce77fe33162802808f3f
```

**Comment by fanquake** [comment]
Thanks, fixed up the message.

**Review by willcl-ark — APPROVED** [review]
ACK 8fef83a0a03f884e0c5399b318eb55064b84b718

Agree that it's reasonable to apply the MSVC exclusion to all MSVC versions in this fixup.

<details>
  <summary>system info</summary>
  
| k           | v |
|-------------|-------|
| OS          | Ubuntu 23.10 (mantic) |
| Arch        | x86_64 |
| Kernel      | 6.5.0-44-generic |
| System      | Linux |
| CPU Model   | 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz |
| CPU Cores   | 16 |
| Memory      | 62Gi |
| CC          | Homebrew clang version 19.1.1 |
| CXX         | Homebrew clang version 19.1.1 |
| Python      | Python 3.9.18 |
| Make        | GNU Make 4.3 |
| CMake       | cmake version 3.30.5 |
| Boost       | 1_74 |
| sqlite3     | 3.46.1 2024-08-13 09:16:08 |
| Git Branch  | 28_some_backports |
  
</details>

**Comment by fanquake** [comment]
One thing that didn't happen here was re-genning the example bitcoin.conf, can be done in either rc2 or before final.

**Pull request merged**
