### PR TITLE
Add const to methods that do not modify the object for which it is called

### PR DESCRIPTION
**Pull request by practicalswift**

### CODE REVIEW

**Comment by benma** [comment]
`isRestartRequired()` in optionsmodel.(h|cpp) can also be made const, I think.

**Comment by practicalswift** [comment]
@benma Thanks! Added and pushed.

**Comment by benma** [comment]
utACK 17d6213f1ed08ce9907b90d22cc9596267eeeb73

**Review by dcousens — APPROVED** [review]

**Review by dcousens — APPROVED** [review]
utACK

**Comment by MarcoFalke** [comment]
utACK 17d6213f1ed08ce9907b90d22cc9596267eeeb

**Comment by paveljanik** [comment]
utACK 17d6213

**Comment by jtimon** [comment]
ACK 17d6213f1ed08ce9907b90d22cc9596267eeeb73

**Comment by practicalswift** [comment]
Adding link to ["By default, make member functions `const`" (Con.2)](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rconst-fct) in the C++ Core Guidelines.

**Comment by practicalswift** [comment]
Added a few additional methods.

**Comment by MarcoFalke** [comment]
utACK 6e8c48dc593d8b6e5cebd15a980074715223b572

**Comment by TheBlueMatt** [comment]
utACK 6e8c48dc593d8b6e5cebd15a980074715223b572

**Comment by paveljanik** [comment]
re-utACK 6e8c48d

**Pull request merged**
