### PR TITLE
msvc: add rapidcheck property tests

### PR DESCRIPTION
**Pull request by ken2812221**
This PR add the property tests into the binaries built by MSVC.

And another trivial change is that I reordered the appveyor package list.

### CODE REVIEW

**Comment by practicalswift** [comment]
@ken2812221 The tests run as expected under Windows?

**Comment by sipsorcery** [comment]
tACK d067e81dcf574b6504813bbf742cd5af057e8e9b.

Appveyor build now runs these two additional tests:

> rpc_deriveaddresses.py                | ✓ Passed  | 2 s
rpc_deriveaddresses.py --usecli       | ✓ Passed  | 2 s

**Comment by practicalswift** [comment]
utACK d067e81dcf574b6504813bbf742cd5af057e8e9b

**Comment by fanquake** [comment]
utACK d067e81

**Pull request merged**
