### PR TITLE
[tests] log thread names by default in functional tests

### PR DESCRIPTION
**Pull request by jnewbery**
More detailed logs are better

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Should add a comment to `initialize_datadir` to explain why logging related configs should not go into the conf file?

**Comment by jnewbery** [comment]
@MarcoFalke - is there a good reason? Is it just so these options get picked up before the conf file is read?

**Comment by MarcoFalke** [comment]
I think it was something like "I don't want logging to be verbose and spam the debug.log when I start a regtest node in the temp dir for debugging"

**Comment by practicalswift** [comment]
Concept ACK

**Comment by laanwj** [comment]
> I think it was something like "I don't want logging to be  verbose and spam the debug.log when I start a regtest node in the temp  dir for debugging after a test failure"

Would definitely make sense to add a comment then.

**Comment by jnewbery** [comment]
> Should add a comment to initialize_datadir to explain why logging related configs should not go into the conf file?

Added comment as requested.

**Comment by jamesob** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/15927/commits/7b29ec277b2f99a526c2a70f0dec7b28f1e874a4

**Comment by practicalswift** [comment]
utACK 7b29ec277b2f99a526c2a70f0dec7b28f1e874a4

**Comment by jonatack** [comment]
Hi John, I tried to test this (recompiled, ran various functional tests, added changes to make them fail), and was unable to find a change in logging. Could you give an example I can run of where this makes a difference?

**Comment by MarcoFalke** [comment]
@jonatack Good catch. I suggest to extend some `assert_debug_log` with a string that also matches the thread name. Maybe in script checking or net?

**Comment by jnewbery** [comment]
Note that `logthreadnames` does not work on mingw32 and darwin.

I've verified that this works for me. Before:

```
head /tmp/user/1000/bitcoin_func_test_4apf_c6t/node0/regtest/debug.log
2019-05-06T16:44:58Z 




2019-05-06T16:44:58.838174Z Bitcoin Core version v0.18.99.0-unk (release build)
2019-05-06T16:44:58.838180Z InitParameterInteraction: parameter interaction: -bind set -> setting -listen=1
2019-05-06T16:44:58.838216Z Validating signatures for all blocks.
2019-05-06T16:44:58.838220Z Setting nMinimumChainWork=0000000000000000000000000000000000000000000000000000000000000000
2019-05-06T16:44:58.838283Z Using the 'sse4(1way),sse41(4way),avx2(8way)' SHA256 implementation
```

After:

```
head -10 /tmp/user/1000/bitcoin_func_test_aihi949j/node0/regtest/debug.log 
2019-05-06T16:28:51Z 




2019-05-06T16:28:51.180256Z [init] Bitcoin Core version v0.18.99.0-unk (release build)
2019-05-06T16:28:51.180272Z [init] InitParameterInteraction: parameter interaction: -bind set -> setting -listen=1
2019-05-06T16:28:51.180392Z [init] Validating signatures for all blocks.
2019-05-06T16:28:51.180404Z [init] Setting nMinimumChainWork=0000000000000000000000000000000000000000000000000000000000000000
2019-05-06T16:28:51.180553Z [init] Using the 'sse4(1way),sse41(4way),avx2(8way)' SHA256 implementation
```

(note the [init] prefix on the log lines).

> I suggest to extend some assert_debug_log with a string that also matches the thread name.

This would break the functional tests on platforms that don't support `-logthreadnames`

**Comment by MarcoFalke** [comment]
Oh, yeah. Would have to add to `test/.config.ini` ...

Not asking you to do it here, though.

**Pull request merged**
