### PR TITLE
build, qt: Fix static builds on macOS Big Sur

### LINKED ISSUE #249: GUI hangs (no windows) when bitcoin-qt runs on macOS Big Sur, and it was compiled with depends (Qt 5.12)
On macOS Big Sur 11.2.3 (20D91):
```
% xcrun --show-sdk-version
11.1
```

When `bitcoin-qt` is compiled with depends, no window is shown.

That was not the case before [bumping](https://github.com/bitcoin/bitcoin/pull/21376) Qt version to 5.12.10. See https://github.com/bitcoin/bitcoin/pull/21376#issuecomment-795379418

I scratched it a bit. Looks like a problem with the Cocoa integration plugin as dereferencing of the `QGuiApplicationPrivate::platformIntegration()` pointer causes the `EXC_BAD_ACCESS` error.

Probably, it's an upstream bug.

---

UPDATE:

### Case A (SDK 11.1)

- system: Big Sur 11.2.3 (20D91)
```
% xcode-select --print-path    
/Library/Developer/CommandLineTools
% xcrun --show-sdk-path
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
% xcrun --show-sdk-version         
11.1
% make C depends
% CONFIG_SITE=$PWD/depends/x86_64-apple-darwin20.3.0/share/config.site ./configure
% make
% src/qt/bitcoin-qt -regtest -printtoconsole
```
The client runs but the GUI hangs -- no window is created.

### Case B (SDK 11.1 compiled on Catalina, tested on Big Sur)

- build system: Catalina 10.15.7 (19H524) + Xcode 12.4 (12D4e)
```
% xcodebuild -version
Xcode 12.4
Build version 12D4e
% xcode-select --print-path
/Applications/Xcode.app/Contents/Developer
% xcrun --sdk macosx --show-sdk-path
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk
% xcrun --sdk macosx --show-sdk-version
11.1
% make C depends
% CONFIG_SITE=$PWD/depends/x86_64-apple-darwin19.6.0/share/config.site ./configure
% make
% src/qt/bitcoin-qt -regtest -printtoconsole
````
Everything works just fine.

- test system: Big Sur 11.2.3 (20D91)

The binary compiled on Catalina has been moved to Big Sur.
```
% ~/Downloads/bitcoin-qt -regtest -printtoconsole
```
The client runs but the GUI hangs -- no window is created (the same behavior as in the case A).

### Case C (SDK 10.15.6 from downloaded Xcode 11.7)

- system: Big Sur 11.2.3 (20D91)
```
% sudo xcode-select --switch ~/Downloads/Xcode_11.7/Xcode.app
% xcode-select --print-path
/Users/hebasto1/Downloads/Xcode_11.7/Xcode.app/Contents/Developer
% xcrun --show-sdk-path
/Users/hebasto1/Downloads/Xcode_11.7/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
% xcrun --show-sdk-version         
10.15.6
% make C depends
% CONFIG_SITE=$PWD/depends/x86_64-apple-darwin20.3.0/share/config.site ./configure
% make
% src/qt/bitcoin-qt -regtest -printtoconsole
```
The client runs but the GUI hangs -- no window is created (the same behavior as in the case A).

--- 

Xcode 10.3 and older (SDK 10.14.6) does ~not~ work on Big Sur at all. (see https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-release-notes)

But building depends fail:

### Case D (SDK 10.14.6 from downloaded Xcode 10.3)

- build system: Big Sur 11.2.3 (20D91) + Xcode 10.3 (10G8)
```
% xcodebuild -version
Xcode 10.3
Build version 10G8
% xcode-select --print-path
/Applications/Xcode.app/Contents/Developer
% xcrun --show-sdk-path
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk
% xcrun --show-sdk-version
10.14
% make -C depends native_ds_store
````

The last command fails (looks like an infinite loop).

### PR DESCRIPTION
**Pull request by hebasto**
See details and the patch in https://bugreports.qt.io/browse/QTBUG-87014

Fixes https://github.com/bitcoin-core/gui/issues/249

### CODE REVIEW

**Comment by hebasto** [comment]
### Gitian builds:
```
Generating report
d0015548f1094879097805d8e359bd082f3c272040059b9569f54eb637494f21  bitcoin-41b6db36ac2c-aarch64-linux-gnu-debug.tar.gz
e8b42c6a0a236818ae49892b7703bffd102b010fdbe49f6f4b5be42049332046  bitcoin-41b6db36ac2c-aarch64-linux-gnu.tar.gz
d7776ec8bfb304cf98f8794ac33991fbcdc37fd4e94426f0521ef2ce14b8f1dd  bitcoin-41b6db36ac2c-arm-linux-gnueabihf-debug.tar.gz
884b67e8573ea4c4fbec547985e0dbf7c440b97718b73e2dc525cd8ae09bf545  bitcoin-41b6db36ac2c-arm-linux-gnueabihf.tar.gz
c5b80aaf72bc223012d0c673c9cae379e495cf09818fde542bdc8798c88ffa88  bitcoin-41b6db36ac2c-powerpc64-linux-gnu-debug.tar.gz
07fd06867d65faf4505d56fa143954f2dc08e3c3fc87477572b337957b45855b  bitcoin-41b6db36ac2c-powerpc64-linux-gnu.tar.gz
1206251e09f94750df67effb412cd242f91ad30c943b9811f28d01043c4f2cc7  bitcoin-41b6db36ac2c-powerpc64le-linux-gnu-debug.tar.gz
462461e82a7954313cdd1e1f7d45aa0811ff41401cb9cc8b5e3f4355f84d2fdc  bitcoin-41b6db36ac2c-powerpc64le-linux-gnu.tar.gz
d67a7b0cade78617c27f4747ae2e98902bf3b94c83a822b8e87649e690e1e1bc  bitcoin-41b6db36ac2c-riscv64-linux-gnu-debug.tar.gz
c74fc950ca10250948b478d1ac1d3a6988ca1d4bd7546b2092b68e53cf107e9b  bitcoin-41b6db36ac2c-riscv64-linux-gnu.tar.gz
d4c991da5967aa1759921a93b3ee8c73729b9f0feb466ba762beb48295269b41  bitcoin-41b6db36ac2c-x86_64-linux-gnu-debug.tar.gz
684c78b607be11e7256ab14b538557b49c968badedb75f0e5a711da90f741731  bitcoin-41b6db36ac2c-x86_64-linux-gnu.tar.gz
ff7ee794cc562bd9eb66118cf7dd23668971419ac6b62174d8e05b6da9831460  src/bitcoin-41b6db36ac2c.tar.gz
5c29c91dc887f5fdffe742f3321fa39b58a695c30998d7f41de445ecf2c76df9  bitcoin-core-linux-22-res.yml
Done.
```

```
Generating report
f5a96e85260da77a220367df3ea48025fe57b10123353ba527a6f07882330c15  bitcoin-41b6db36ac2c-win-unsigned.tar.gz
dd657b5a9f97d442bbd280c94d1a7cb8947b6396cf4d7c7a01c82698d07618a9  bitcoin-41b6db36ac2c-win64-debug.zip
ab7276f3c1d03c75f3faf4d09579fb2f715e5c089a07a8a7b34ddc77f69955b4  bitcoin-41b6db36ac2c-win64-setup-unsigned.exe
b61b868cf2dae4e155e778610e10de5e85863c2c554277e35f155d49b77d09ac  bitcoin-41b6db36ac2c-win64.zip
ff7ee794cc562bd9eb66118cf7dd23668971419ac6b62174d8e05b6da9831460  src/bitcoin-41b6db36ac2c.tar.gz
d2b9a2bfe896cbe1530d2cf51781f5162471c83105ab4e96a59dcd1d2fe18508  bitcoin-core-win-22-res.yml
Done.
```

```
Generating report
a510113ac7520c429bd26aa3b0376f736ac6b95cc1b11d3ace1c5e0259038192  bitcoin-41b6db36ac2c-osx-unsigned.dmg
f83fc9957c3bb298a666c183a0485c41aff133bf1e94d47613939bd774d50b51  bitcoin-41b6db36ac2c-osx-unsigned.tar.gz
a64cc80c684a9307bf714ea1c56fd5dd82e7ebb2ab4f947f903c60258e530d42  bitcoin-41b6db36ac2c-osx64.tar.gz
ff7ee794cc562bd9eb66118cf7dd23668971419ac6b62174d8e05b6da9831460  src/bitcoin-41b6db36ac2c.tar.gz
3f3a51fb088b34e14e6d433646fb64b65fe9d905ca91854912b92404a8fadc4f  bitcoin-core-osx-22-res.yml
Done.
```

**Comment by MarcoFalke** [comment]
qt5.12 is only used in master, so assigned 22.0 milestone

**Comment by fanquake** [comment]
Concept ACK. This matches the change that was [backported to the 5.12 branch](https://codereview.qt-project.org/c/qt%2Fqtbase/+/322507) (`git branch --contains c5d904639dbd690a36306e2b455610029704d821`. We don't have it, because a 5.12.11 release has not been tagged (yet); it should happen  in the first half of this year, according to https://wiki.qt.io/Qt_5.12_Release.

Similar to other Qt patches we have, can you add a note at the top of the patch file, mentioning that this can be dropped when using Qt 5.12.11 or later.

@jarolrod or @Sjors could either of you test a depends build and confirm that `bitcoin-qt` run on macOS 11.

**Review by jarolrod — COMMENTED** [review]
Confirming that this fixes the depends build issue on macOS Big Sur. Thanks for the fix!
A ton of the following warnings do pop-up, but they are non-fatal. I also get them on Catalina with SDK 10.15.

```
ld: warning: direct access in function 'QMetaTypeIdQObject<QWindow*, 8>::qt_metatype_id()' from file '/Users/xyz/Code/Bitcoin/fix-bigsur-static/bitcoin/depends/x86_64-apple-darwin20.3.0/plugins/platforms/libqcocoa.a(qcocoaintegration.o)' to global weak symbol 'QMetaTypeIdQObject<QWindow*, 8>::qt_metatype_id()::metatype_id' from file 'qt/libbitcoinqt.a(libbitcoinqt_a-walletcontroller.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
```

(reserved space for GUIX hashes)

**Comment by hebasto** [comment]
Updated 41b6db36ac2c40dc6374d5f056f1ad6cc6420872 -> d347fc07a54d2bc887adfef3b5ee84a636a9b64b ([pr21495.01](https://github.com/hebasto/bitcoin/commits/pr21495.01) -> [pr21495.02](https://github.com/hebasto/bitcoin/commits/pr21495.02), [diff](https://github.com/hebasto/bitcoin/compare/pr21495.01..pr21495.02)):

- addressed @fanquake's [comment](https://github.com/bitcoin/bitcoin/pull/21495#issuecomment-803792011):
> Similar to other Qt patches we have, can you add a note at the top of the patch file, mentioning that this can be dropped when using Qt 5.12.11 or later.

**Comment by hebasto** [comment]
Guix builds:
```
$ find output -type f -name *$(git rev-parse --short HEAD)*.* -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum
b2c03db57874a7e52fd11c57f0088711f544671ac52e15cfc68077494b95b113  output/bitcoin-d347fc07a54d-aarch64-linux-gnu-debug.tar.gz
b1d85a5be34f2d65d258f496b191c869d72a221248ca904a6ec3e744131f78f5  output/bitcoin-d347fc07a54d-aarch64-linux-gnu.tar.gz
b2cdadf1ddca6dd91cd1ffd5ef7759689726065a482264a2d99bfc0de8b4390c  output/bitcoin-d347fc07a54d-arm-linux-gnueabihf-debug.tar.gz
ca9743cc611a96a027549ecc93fde6ae3f2e54ff461019df11751d8c09f10cfa  output/bitcoin-d347fc07a54d-arm-linux-gnueabihf.tar.gz
cda2e1255204ab53f2b63ef04fade646dfc34484617a98a9e2fd0adeb7272699  output/bitcoin-d347fc07a54d-osx-unsigned.dmg
1f45d8ab16658edec3dd35a5656ddefa18d22092b6d2bab4316f48e3540ad571  output/bitcoin-d347fc07a54d-osx-unsigned.tar.gz
07c2a75c5b8f961c6e90e2dcd9d485c66d128285240726b2b7379e7b371631ef  output/bitcoin-d347fc07a54d-osx64.tar.gz
f65d24424a922b93c89f7acbcdf916f87d52d65617774a6ba36bbdff4f0a4827  output/bitcoin-d347fc07a54d-powerpc64-linux-gnu-debug.tar.gz
a099d7b4eb75de23acb63fc058b0f4a76a67c6ae0687354836f0346155128792  output/bitcoin-d347fc07a54d-powerpc64-linux-gnu.tar.gz
8aaabbc187a31a08fb9a2808b75b3922937d55c7254f0661933857377365a803  output/bitcoin-d347fc07a54d-powerpc64le-linux-gnu-debug.tar.gz
1df297a669d3f3cfdeb60e296c4e30e3a7b091a6b88b309004fa36970267a01e  output/bitcoin-d347fc07a54d-powerpc64le-linux-gnu.tar.gz
b0381ccbe9ac66cad846082a1506284e22a101b9c1c03e461db0ed8c8e45815c  output/bitcoin-d347fc07a54d-riscv64-linux-gnu-debug.tar.gz
9d94f534ce7e4b883046072706f5d514e02b9c6c5dfd2e0b66539253fe2f8738  output/bitcoin-d347fc07a54d-riscv64-linux-gnu.tar.gz
6b42298e092d87cd4f77e7eefb234ebeff9d837164b95c8e8c7746ddf8c32e84  output/bitcoin-d347fc07a54d-win-unsigned.tar.gz
40830e316af13eb2885cf9fc258c50ea19f37ec74d5b1b47fe1c709087e47bcc  output/bitcoin-d347fc07a54d-win64-debug.zip
08814e7dd420650f18e303ba403d755e0a8384a64eb41cfcc534da00bd81784b  output/bitcoin-d347fc07a54d-win64-setup-unsigned.exe
1cb962c79f339236f2f288a2dfa6e7ad99ad1b5964eb7c3248f1c08f379d3657  output/bitcoin-d347fc07a54d-win64.zip
49ae6b04cccd12f6d3cb955380d08503a548f41d7274eab88e0cdfc95609ef51  output/bitcoin-d347fc07a54d-x86_64-linux-gnu-debug.tar.gz
f3ccb66459e8bed50bcfc8e437e7990fad59b05b966de0785cca41b1ceda1b5d  output/bitcoin-d347fc07a54d-x86_64-linux-gnu.tar.gz
82da4f18b70e5a6546fae2fb6e3a49af90b5d4f0a786f28dc0ab97c895d2d79c  output/src/bitcoin-d347fc07a54d.tar.gz
```

**Comment by hebasto** [comment]
Gitian builds:
- Linux:
```
Generating report
9312bb39f32c5f4cf9172977fbf94f669acff03623b2647d6138a1322557f1fc  bitcoin-d347fc07a54d-aarch64-linux-gnu-debug.tar.gz
ad1080f3b4928ff3d127a9f32029c010e19516ea9495f08e8b217fba6300e919  bitcoin-d347fc07a54d-aarch64-linux-gnu.tar.gz
871194fcafc052c5dc173b81aefaf66840edcc51cc499730ee48c0c96dd390f9  bitcoin-d347fc07a54d-arm-linux-gnueabihf-debug.tar.gz
452e3d2ec8f196afaf8303118cb035b9bd7ee4ee2388187e8f813f4da5943276  bitcoin-d347fc07a54d-arm-linux-gnueabihf.tar.gz
086cb887bc5c554837af39c04c7ea3d50c72e30df1b490d7c798b902bc7a2ba3  bitcoin-d347fc07a54d-powerpc64-linux-gnu-debug.tar.gz
acb165a69e6ee6d3b4ed65793426368a3417a77589fc2cd31834b0b83a81b571  bitcoin-d347fc07a54d-powerpc64-linux-gnu.tar.gz
cc28e87a8c347f68bd76ad3f5b74f151220d1f24690ca389732c6d71a147afea  bitcoin-d347fc07a54d-powerpc64le-linux-gnu-debug.tar.gz
533190a2627f9568c87847cbcf5eab136fb329bccdbca3a64a34af1e9e00774b  bitcoin-d347fc07a54d-powerpc64le-linux-gnu.tar.gz
a9758cbaec6710135df4b63e84ae374b77b1d72dc1e9b55ed730a00fc1d163b9  bitcoin-d347fc07a54d-riscv64-linux-gnu-debug.tar.gz
5072bcfeda87fe8ccad69694474c9a5fb35ea431cbff75633c8378ecfe4775fa  bitcoin-d347fc07a54d-riscv64-linux-gnu.tar.gz
a6fc05be40ce3fa6c0dc76724e9483f5e8386f5bad88b81e60bea2efc1cd7d56  bitcoin-d347fc07a54d-x86_64-linux-gnu-debug.tar.gz
17129aee3cd4bc89de691c2a53df4b6fa20cec14c9c90dec5e0a216e3edfb639  bitcoin-d347fc07a54d-x86_64-linux-gnu.tar.gz
82da4f18b70e5a6546fae2fb6e3a49af90b5d4f0a786f28dc0ab97c895d2d79c  src/bitcoin-d347fc07a54d.tar.gz
5661c2248709a1bbc3c23da566fa6bfbf72aaf2ec046fe85d8a1421af4451c62  bitcoin-core-linux-22-res.yml
Done.
```
- Windows:
```
Generating report
4efb257aa171e08fe580e340f3053756aabc1a63c3c1531c14f241f65c7450f6  bitcoin-d347fc07a54d-win-unsigned.tar.gz
946091f99d5d3b3971f6446803ab98f0a51c97d9b9e695846e020276169b5c4e  bitcoin-d347fc07a54d-win64-debug.zip
e212000f44df187238bbe6cfae337a30303fb3830bbf41cd4cc3c054716d239a  bitcoin-d347fc07a54d-win64-setup-unsigned.exe
72116f9a355183410ebe890bef24094feef51baad40574f48dc59b342790b80c  bitcoin-d347fc07a54d-win64.zip
82da4f18b70e5a6546fae2fb6e3a49af90b5d4f0a786f28dc0ab97c895d2d79c  src/bitcoin-d347fc07a54d.tar.gz
682c4b249edad42c1fc26a001c40b84bb61c3f07b050a5a4173829535a7b1f8b  bitcoin-core-win-22-res.yml
Done.
```
- macOS:
```
Generating report
063f0e23eb3612d3f25992cfcef984eb3225ce687309178c589ccc9ff3f307f7  bitcoin-d347fc07a54d-osx-unsigned.dmg
32192f4b935bc74fe620a647b9ebfe815927848ac5cacb8a74ea8be85140a378  bitcoin-d347fc07a54d-osx-unsigned.tar.gz
fa600a2c664255620a9c1480562b20472c7e022b2cc18422b8a076ecc95ccb37  bitcoin-d347fc07a54d-osx64.tar.gz
82da4f18b70e5a6546fae2fb6e3a49af90b5d4f0a786f28dc0ab97c895d2d79c  src/bitcoin-d347fc07a54d.tar.gz
5790c07bee20ab3437335800ad1d044106beff477e80554086aae3b513d99d73  bitcoin-core-osx-22-res.yml
Done.
```

**Comment by fanquake** [comment]
Guix is matching, however I'm currently seeing a mismatch for the macOS gitian build.

Gitian:
macOS
```bash
76aef92275ac0ab1b6dac2132c099b7e1a7ab2638baa7fab705e9c53c92b093e  bitcoin-d347fc07a54d-osx-unsigned.dmg
ee7242894466d89f8f0161998f759eba47c2f0dd3ecd6c6c34b9c3f86555d293  bitcoin-d347fc07a54d-osx-unsigned.tar.gz
5a3f569c4bcfa91a9494d8a657d0cc3964b4b06e9ec08ecd0cbe2dfeebe1b9b5  bitcoin-d347fc07a54d-osx64.tar.gz
82da4f18b70e5a6546fae2fb6e3a49af90b5d4f0a786f28dc0ab97c895d2d79c  src/bitcoin-d347fc07a54d.tar.gz
26feb335e7724f75d655796ddf85513da4fbd66fcb95fa2a99a3936947755802  bitcoin-core-osx-22-res.yml
```

Windows:
```bash
4efb257aa171e08fe580e340f3053756aabc1a63c3c1531c14f241f65c7450f6  bitcoin-d347fc07a54d-win-unsigned.tar.gz
946091f99d5d3b3971f6446803ab98f0a51c97d9b9e695846e020276169b5c4e  bitcoin-d347fc07a54d-win64-debug.zip
e212000f44df187238bbe6cfae337a30303fb3830bbf41cd4cc3c054716d239a  bitcoin-d347fc07a54d-win64-setup-unsigned.exe
72116f9a355183410ebe890bef24094feef51baad40574f48dc59b342790b80c  bitcoin-d347fc07a54d-win64.zip
82da4f18b70e5a6546fae2fb6e3a49af90b5d4f0a786f28dc0ab97c895d2d79c  src/bitcoin-d347fc07a54d.tar.gz
37f13f87c4d8b556272f611796f7883932d8474d52f74fe6c4376479d658ee02  bitcoin-core-win-22-res.yml
```

Linux:
```bash
9312bb39f32c5f4cf9172977fbf94f669acff03623b2647d6138a1322557f1fc  bitcoin-d347fc07a54d-aarch64-linux-gnu-debug.tar.gz
ad1080f3b4928ff3d127a9f32029c010e19516ea9495f08e8b217fba6300e919  bitcoin-d347fc07a54d-aarch64-linux-gnu.tar.gz
871194fcafc052c5dc173b81aefaf66840edcc51cc499730ee48c0c96dd390f9  bitcoin-d347fc07a54d-arm-linux-gnueabihf-debug.tar.gz
452e3d2ec8f196afaf8303118cb035b9bd7ee4ee2388187e8f813f4da5943276  bitcoin-d347fc07a54d-arm-linux-gnueabihf.tar.gz
086cb887bc5c554837af39c04c7ea3d50c72e30df1b490d7c798b902bc7a2ba3  bitcoin-d347fc07a54d-powerpc64-linux-gnu-debug.tar.gz
acb165a69e6ee6d3b4ed65793426368a3417a77589fc2cd31834b0b83a81b571  bitcoin-d347fc07a54d-powerpc64-linux-gnu.tar.gz
cc28e87a8c347f68bd76ad3f5b74f151220d1f24690ca389732c6d71a147afea  bitcoin-d347fc07a54d-powerpc64le-linux-gnu-debug.tar.gz
533190a2627f9568c87847cbcf5eab136fb329bccdbca3a64a34af1e9e00774b  bitcoin-d347fc07a54d-powerpc64le-linux-gnu.tar.gz
a9758cbaec6710135df4b63e84ae374b77b1d72dc1e9b55ed730a00fc1d163b9  bitcoin-d347fc07a54d-riscv64-linux-gnu-debug.tar.gz
5072bcfeda87fe8ccad69694474c9a5fb35ea431cbff75633c8378ecfe4775fa  bitcoin-d347fc07a54d-riscv64-linux-gnu.tar.gz
a6fc05be40ce3fa6c0dc76724e9483f5e8386f5bad88b81e60bea2efc1cd7d56  bitcoin-d347fc07a54d-x86_64-linux-gnu-debug.tar.gz
17129aee3cd4bc89de691c2a53df4b6fa20cec14c9c90dec5e0a216e3edfb639  bitcoin-d347fc07a54d-x86_64-linux-gnu.tar.gz
82da4f18b70e5a6546fae2fb6e3a49af90b5d4f0a786f28dc0ab97c895d2d79c  src/bitcoin-d347fc07a54d.tar.gz
76fc04d1d9db010d1000c0456126b7a7c7e18be990a45b3ddc19bb9ad08792a1  bitcoin-core-linux-22-res.yml
```

Guix:
```bash
b2c03db57874a7e52fd11c57f0088711f544671ac52e15cfc68077494b95b113  output/bitcoin-d347fc07a54d-aarch64-linux-gnu-debug.tar.gz
b1d85a5be34f2d65d258f496b191c869d72a221248ca904a6ec3e744131f78f5  output/bitcoin-d347fc07a54d-aarch64-linux-gnu.tar.gz
b2cdadf1ddca6dd91cd1ffd5ef7759689726065a482264a2d99bfc0de8b4390c  output/bitcoin-d347fc07a54d-arm-linux-gnueabihf-debug.tar.gz
ca9743cc611a96a027549ecc93fde6ae3f2e54ff461019df11751d8c09f10cfa  output/bitcoin-d347fc07a54d-arm-linux-gnueabihf.tar.gz
cda2e1255204ab53f2b63ef04fade646dfc34484617a98a9e2fd0adeb7272699  output/bitcoin-d347fc07a54d-osx-unsigned.dmg
1f45d8ab16658edec3dd35a5656ddefa18d22092b6d2bab4316f48e3540ad571  output/bitcoin-d347fc07a54d-osx-unsigned.tar.gz
07c2a75c5b8f961c6e90e2dcd9d485c66d128285240726b2b7379e7b371631ef  output/bitcoin-d347fc07a54d-osx64.tar.gz
f65d24424a922b93c89f7acbcdf916f87d52d65617774a6ba36bbdff4f0a4827  output/bitcoin-d347fc07a54d-powerpc64-linux-gnu-debug.tar.gz
a099d7b4eb75de23acb63fc058b0f4a76a67c6ae0687354836f0346155128792  output/bitcoin-d347fc07a54d-powerpc64-linux-gnu.tar.gz
8aaabbc187a31a08fb9a2808b75b3922937d55c7254f0661933857377365a803  output/bitcoin-d347fc07a54d-powerpc64le-linux-gnu-debug.tar.gz
1df297a669d3f3cfdeb60e296c4e30e3a7b091a6b88b309004fa36970267a01e  output/bitcoin-d347fc07a54d-powerpc64le-linux-gnu.tar.gz
b0381ccbe9ac66cad846082a1506284e22a101b9c1c03e461db0ed8c8e45815c  output/bitcoin-d347fc07a54d-riscv64-linux-gnu-debug.tar.gz
9d94f534ce7e4b883046072706f5d514e02b9c6c5dfd2e0b66539253fe2f8738  output/bitcoin-d347fc07a54d-riscv64-linux-gnu.tar.gz
6b42298e092d87cd4f77e7eefb234ebeff9d837164b95c8e8c7746ddf8c32e84  output/bitcoin-d347fc07a54d-win-unsigned.tar.gz
40830e316af13eb2885cf9fc258c50ea19f37ec74d5b1b47fe1c709087e47bcc  output/bitcoin-d347fc07a54d-win64-debug.zip
08814e7dd420650f18e303ba403d755e0a8384a64eb41cfcc534da00bd81784b  output/bitcoin-d347fc07a54d-win64-setup-unsigned.exe
1cb962c79f339236f2f288a2dfa6e7ad99ad1b5964eb7c3248f1c08f379d3657  output/bitcoin-d347fc07a54d-win64.zip
49ae6b04cccd12f6d3cb955380d08503a548f41d7274eab88e0cdfc95609ef51  output/bitcoin-d347fc07a54d-x86_64-linux-gnu-debug.tar.gz
f3ccb66459e8bed50bcfc8e437e7990fad59b05b966de0785cca41b1ceda1b5d  output/bitcoin-d347fc07a54d-x86_64-linux-gnu.tar.gz
82da4f18b70e5a6546fae2fb6e3a49af90b5d4f0a786f28dc0ab97c895d2d79c  output/src/bitcoin-d347fc07a54d.tar.gz
```

**Comment by hebasto** [comment]
Did another gitian build with a clear cache:
```
Generating report
76aef92275ac0ab1b6dac2132c099b7e1a7ab2638baa7fab705e9c53c92b093e  bitcoin-d347fc07a54d-osx-unsigned.dmg
ee7242894466d89f8f0161998f759eba47c2f0dd3ecd6c6c34b9c3f86555d293  bitcoin-d347fc07a54d-osx-unsigned.tar.gz
5a3f569c4bcfa91a9494d8a657d0cc3964b4b06e9ec08ecd0cbe2dfeebe1b9b5  bitcoin-d347fc07a54d-osx64.tar.gz
82da4f18b70e5a6546fae2fb6e3a49af90b5d4f0a786f28dc0ab97c895d2d79c  src/bitcoin-d347fc07a54d.tar.gz
809b0caef323adafd125e69ed9e2df610e3e24bab740ce5b86ddcde593da1aed  bitcoin-core-osx-22-res.yml
Done.
```

It was before when dirty cache causes different hashes, right?

**Comment by hebasto** [comment]
Rebased d347fc07a54d2bc887adfef3b5ee84a636a9b64b -> ec76bad655b105916693c7a415b7c7cf0a924f16 ([pr21495.02](https://github.com/hebasto/bitcoin/commits/pr21495.02) -> [pr21495.03](https://github.com/hebasto/bitcoin/commits/pr21495.03)) due to the conflict with #17227.

**Comment by fanquake** [comment]
Builds @ ec76bad655b105916693c7a415b7c7cf0a924f16
Guix:
```bash
4c487f9c270d42804f8b27822882d884adf7cb30125b523c2781429bae512972  output/bitcoin-ec76bad655b1-osx-unsigned.dmg
dafbf43e498026c282f7530dc09dd00587b3b39825a2947eb85501df3546dcfb  output/bitcoin-ec76bad655b1-osx-unsigned.tar.gz
5e04760ac262263af7cc19a6e7faf7eddd610fb7357bec019f7bf74e03114e4e  output/bitcoin-ec76bad655b1-osx64.tar.gz
37c144d78dbaef941209769e5bf5197ee96e1fb20b220144bf75b6137d74184a  output/src/bitcoin-ec76bad655b1.tar.gz
```

Gitian:
```bash
283900007fa528753a23bc01ab04dd2d9c8a14e36697321f6a0501261db66d1b  bitcoin-ec76bad655b1-osx-unsigned.dmg
62158f3d6f1bbe1da36d06a32d5b109af18ed17a1acaddb00a1699536d3bb79a  bitcoin-ec76bad655b1-osx-unsigned.tar.gz
9b16a47b89283da880cf790d8ae19f9878513f8b3c6dfd9f7bf2094aa1234041  bitcoin-ec76bad655b1-osx64.tar.gz
37c144d78dbaef941209769e5bf5197ee96e1fb20b220144bf75b6137d74184a  src/bitcoin-ec76bad655b1.tar.gz
2f6d059f5fb4bacd4d455a2c0bd53289c7e2e6e5e6221487fcb6720d5d8d2967  bitcoin-core-osx-22-res.yml
```

**Comment by hebasto** [comment]
Guix build:
```
$ find output -type f -name *$(git rev-parse --short HEAD)*.* -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum
4c487f9c270d42804f8b27822882d884adf7cb30125b523c2781429bae512972  output/bitcoin-ec76bad655b1-osx-unsigned.dmg
dafbf43e498026c282f7530dc09dd00587b3b39825a2947eb85501df3546dcfb  output/bitcoin-ec76bad655b1-osx-unsigned.tar.gz
5e04760ac262263af7cc19a6e7faf7eddd610fb7357bec019f7bf74e03114e4e  output/bitcoin-ec76bad655b1-osx64.tar.gz
37c144d78dbaef941209769e5bf5197ee96e1fb20b220144bf75b6137d74184a  output/src/bitcoin-ec76bad655b1.tar.gz
```
Gitian build:
```
Generating report
283900007fa528753a23bc01ab04dd2d9c8a14e36697321f6a0501261db66d1b  bitcoin-ec76bad655b1-osx-unsigned.dmg
62158f3d6f1bbe1da36d06a32d5b109af18ed17a1acaddb00a1699536d3bb79a  bitcoin-ec76bad655b1-osx-unsigned.tar.gz
9b16a47b89283da880cf790d8ae19f9878513f8b3c6dfd9f7bf2094aa1234041  bitcoin-ec76bad655b1-osx64.tar.gz
37c144d78dbaef941209769e5bf5197ee96e1fb20b220144bf75b6137d74184a  src/bitcoin-ec76bad655b1.tar.gz
0cb727768959c82663bfb115a76116e4d7de4747e3a94c09eb092a466ade0d7e  bitcoin-core-osx-22-res.yml
Done.
```

**Review by fanquake — APPROVED** [review]
ACK ec76bad655b105916693c7a415b7c7cf0a924f16

**Comment by Sjors** [comment]
Post merge: I tested on master on macOS 11.2.3. I'm able to run it run `src/qt/bitcoin-qt` as well as from the DMG.

**Comment by hebasto** [comment]
@jarolrod 
> A ton of the following warnings do pop-up, but they are non-fatal. I also get them on Catalina with SDK 10.15.

Unrelated to this PR, but you could silent those warnings by passing the `--enable-reduce-exports` option to the `configure` script.

**Comment by hebasto** [comment]
@jarolrod 
> A ton of the following warnings do pop-up, but they are non-fatal. I also get them on Catalina with SDK 10.15.

FWIW, [QTBUG-81297](https://bugreports.qt.io/browse/QTBUG-81297) is fixed in Qt 5.15.

**Pull request merged**
