### PR TITLE
trivial: capitalize BIP32 in option help

### PR DESCRIPTION
**Pull request by laanwj**
For consistency, BIP32 should be in uppercase in translation message.

Reported by @pryds on Transifex.

### CODE REVIEW

**Comment by fanquake** [comment]
trivial ACK

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/8246/commits/a1c92c29fd1c242831867ede4c67e544377ae473

I didn't want to be super nit-picky when merging this (there were also bip32s in comments etc.).

**Comment by laanwj** [comment]
> I didn't want to be super nit-picky when merging this (there were also bip32s in comments etc.).

Right, this is a user-facing issue, so somewhat more serious.

**Comment by jonasschnelli** [comment]
Post merge ACK.

**Pull request merged**
