### PR TITLE
Fix memleak in TorController

### PR DESCRIPTION
**Pull request by jonasschnelli**
It looks like, `TorController::disconnected_cb(TorControlConnection& conn)` gets called multiple times which results in multiple `event_new()`.

Needs testing!

```
2016-02-26 19:29:42 setKeyPool.size() = 101
2016-02-26 19:29:42 mapWallet.size() = 2202
2016-02-26 19:29:42 mapAddressBook.size() = 4
2016-02-26 19:29:42 init message: Loading addresses...
2016-02-26 19:29:42 torcontrol thread start
2016-02-26 19:29:42 tor: Error connecting to Tor control socket
2016-02-26 19:29:42 tor: Not connected to Tor control port 127.0.0.1:9051, trying to reconnect
2016-02-26 19:29:43 Loaded 0 addresses from peers.dat  1732ms
2016-02-26 19:29:43 tor: Error connecting to Tor control socket
2016-02-26 19:29:43 tor: Not connected to Tor control port 127.0.0.1:9051, trying to reconnect
2016-02-26 19:29:43 init message: Loading banlist...
2016-02-26 19:29:45 tor: Error connecting to Tor control socket
2016-02-26 19:29:45 tor: Not connected to Tor control port 127.0.0.1:9051, trying to reconnect
2016-02-26 19:29:46 dnsseed thread start
2016-02-26 19:29:46 net thread start
```

### CODE REVIEW

**Comment by laanwj** [comment]
utACK
nit: event_free implies event_del, doing both is unnecessary

**Comment by laanwj** [comment]
Good point @theuni!

**Comment by laanwj** [comment]
Closing in favor of #7637

**Comment by MarcoFalke** [comment]
Removing label 'needs backport'

**Pull request closed without merging**
