### PR TITLE
trivial: Fix typo – alreardy → already

### PR DESCRIPTION
**Pull request by practicalswift**
Fix typo: alreardy → already.

### CODE REVIEW

**Comment by paveljanik** [comment]
trivial ACK https://github.com/bitcoin/bitcoin/pull/11635/commits/7536b08c1090f9ac1081d7e27379e9152989b52b

**Comment by jackpot1136** [comment]
Thank you

**Comment by fanquake** [comment]
trivial ack 7536b08

**Comment by promag** [comment]
ACK 7536b08.

**Pull request merged**
