### PR TITLE
doc: Corrected Typos in Documentation

### PR DESCRIPTION
**Pull request by ppyordanov**
Scanned the whole source code for typing errors and corrected. Added a translation correction.

> If you're going to fix typos, can you please fix all of them as seen in the spelling linter script `test/lint/lint-spelling.sh`, e.g. I believe:
> 
> src/core_read.cpp:131: presense ==> presence
> src/net_processing.h:68: anounce ==> announce
> src/netaddress.h:486: compatiblity ==> compatibility
> src/wallet/walletdb.cpp:429: Crypted ==> Encrypted
> src/test/validation_tests.cpp:78: excercise ==> exercise
> test/functional/feature_nulldummy.py:63: unnecssary ==> unnecessary
> 
> and update `test/lint/lint-spelling.ignore-words.txt` to ignore all of the current false positives.

### CODE REVIEW

**Comment by fanquake** [comment]
Don't modify upstream files, generated files, historical release notes, subtrees or any translations. Remove any @ mentions from the PR body.

**Comment by michaelfolkson** [comment]
Note also there is already this PR in progress of review. https://github.com/bitcoin/bitcoin/pull/20762

There may well be some to-dos for a follow up PR though.

**Comment by jonatack** [comment]
Concept ACK for any remaining ones after doing https://github.com/bitcoin/bitcoin/pull/20836#issuecomment-753581717 and #20762 -- looks like you found some.

**Comment by michaelfolkson** [comment]
Noisy labels too. A maintainer needs to reduce the Labels to just Docs

**Comment by hebasto** [comment]
Linter job failed: https://cirrus-ci.com/task/6073276860465152

**Comment by ppyordanov** [comment]
Addressing review comments, excluded:

generated files
historical release notes
subtrees
translations.

**Comment by fanquake** [comment]
Thanks for your contribution. However to move things along I'm going to fix this up and consolidate it with some other changes. Your changes will still be attributed to you.

**Pull request closed without merging**
