### PR TITLE
Add gitian PGP key: wjcloud

### PR DESCRIPTION
**Pull request by ghost**
Gitian PR: https://github.com/bitcoin-core/gitian.sigs/pull/620

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Related https://github.com/bitcoin/bitcoin/pull/11700

**Comment by laanwj** [comment]
Verified that the key matches the signature used in https://github.com/bitcoin-core/gitian.sigs/pull/620

**Review by laanwj — APPROVED** [review]

**Comment by jonasschnelli** [comment]
Hmm... unsure.
Key refers to btcplt.org (Bitcoin Platinum).
I just want to make sure if the key merged into the Core repository will not be used to leverage other things (indirect advertising).

**Comment by laanwj** [comment]
Ok, yea, that is unacceptable.

**Comment by MarcoFalke** [comment]
Unrelated note: Since most keys are outdated and keeping them up to date is somewhat of a pain, what about removing all keys and only adding a list of full key fingerprints, to be fed into `gpg` for later download. Right now we need to connect to some pgp key server anyway, as some keys are timed out.

**Comment by laanwj** [comment]
>  Since most keys are outdated and keeping them up to date is somewhat of a pain, what about removing all keys and only adding a list of full key fingerprints, 

Yes, that would be a good idea. Have only the key-fingerprints in the main repo.

With I'd prefer to put up a separate repository with the keys somewhere that it will import from, checking the key fingerprints. Pulling from the keyserver every time, for every build, is fairly slow and takes up unnecessarily resources for them (and it also fails some of the time).

**Comment by MarcoFalke** [comment]
@laanwj You are referring to the maintainers' keys, right?

**Comment by laanwj** [comment]
> @laanwj You are referring to the maintainers' keys, right?

Yes, all keys. Though travis doesn't have to import/check the gitian ones obviously.

**Comment by MarcoFalke** [comment]
Can be closed in case #11909 is merged.

**Comment by wjcloud** [comment]
I'm closing this as my ID has changed :D

**Pull request closed without merging**
