### PR TITLE
test: Speed up wallet_resendwallettransactions with mockscheduler RPC

### LINKED ISSUE #20143: qa: Intermittent error in wallet_resendwallettransactions.py
https://travis-ci.org/github/hebasto/bitcoin/jobs/735078189#L5109:

```
AssertionError: Predicate ''''
        def test_function():
            if check_connected:
                assert self.is_connected
            return test_function_in()
''' not true after 240.0 seconds
```

### PR DESCRIPTION
**Pull request by maflcko**
Also fixes #20143

### CODE REVIEW

**Review by jonatack — COMMENTED** [review]
ACK, am seeing a lot of variation in the test run times but it seems to be faster and I like the idea of using this rpc instead of `time.sleep()` if it's robust.

**Comment by MarcoFalke** [comment]
The variation comes from the trickle delay for sending invs

**Review by guggero — COMMENTED** [review]
ACK fa299ac2

Great speedup! The test runs 3 to 5 seconds faster on my machine compared to master.

**Comment by lehuuhieu7777** [comment]
Good

**Pull request merged**
