### PR TITLE
Use python not 'python2'

### PR DESCRIPTION
**Pull request by cjavad**
addition to Merge #11830. I looked through the source files looking for other files with 
    
    #!/usr/bin/env python2
and found that contrib/devtools/test-security-check.py had the same error that @hkjn pointed out.

### CODE REVIEW

**Comment by laanwj** [comment]
It might simply mean that the tool needs python 2.

Did you verify and test that this code is compatible with python 3?

**Comment by JavadSM** [comment]
I did, and it produced the same results with python, python2 and python3.

**Comment by kev009** [comment]
Note that some packages don't install any bin/python' symlink (i.e. freebsd ports) to make the 2-3 transition less ambiguous.

**Comment by JavadSM** [comment]
Yes but most unix based operating systems uses the bin/python symlink that is included with fx. macos and linux. And because the ```#!bin/env python``` is targeted for unix users and other POSIX based OSs where some of them dont have the ```#!bin/env python2``` symlink like MacOS. So i would argue that using  ```#!bin/env python``` is preferred over ```#!bin/env python2```.

**Comment by laanwj** [comment]
It looks like we use `#!/usr/bin/env python3` in most places:
```bash
git ls-files \*.py | xargs head -n 1|less
```

**Comment by hkjn** [comment]
FWIW I also agree that setting `python3` explicitly is the best path, assuming `python2` support no longer is necessary. I went the other way in #11830 to try to be gentle to the long tail of `python2`-only folks that are still out there.

Any such users on `python2` only could still call scripts with `python2 somescript.py` if they for some reason don't want to upgrade, assuming we keep the scripts compatible with both major versions.

**Comment by MarcoFalke** [comment]
Even though it is not mentioned in `doc/dependencies.md`, we still target py2 support for user facing scripts. Functional tests are the only exception.

**Comment by JavadSM** [comment]
Agreeing with @laanwj and @hkjn here, python3 would be a better choice for future compatibility.

**Comment by laanwj** [comment]
ACK after squash

**Comment by jnewbery** [comment]
> Yes, agree it's somewhat weird now. I think it's about time to move away from that, and just settle on Python 3. But not be a discussion that we need to do here.

I completely agree with @laanwj. Here are the hashbangs for python files not in the test directory:

```
share/qt/extract_strings_qt.py|1 col 12| #!/usr/bin/env python
share/rpcauth/rpcauth.py|1 col 12| #!/usr/bin/env python
contrib/testgen/gen_base58_test_vectors.py|1 col 12| #!/usr/bin/env python
contrib/linearize/linearize-hashes.py|1 col 12| #!/usr/bin/env python3
contrib/linearize/linearize-data.py|1 col 12| #!/usr/bin/env python3
contrib/zmq/zmq_sub3.4.py|1 col 12| #!/usr/bin/env python3
contrib/zmq/zmq_sub.py|1 col 12| #!/usr/bin/env python3
contrib/macdeploy/custom_dsstore.py|1 col 12| #!/usr/bin/env python
contrib/macdeploy/macdeployqtplus|1 col 12| #!/usr/bin/env python
contrib/seeds/generate-seeds.py|1 col 12| #!/usr/bin/env python3
contrib/seeds/makeseeds.py|1 col 12| #!/usr/bin/env python3
contrib/filter-lcov.py|1 col 12| #!/usr/bin/env python3
contrib/devtools/check-doc.py|1 col 12| #!/usr/bin/env python
contrib/devtools/copyright_header.py|1 col 12| #!/usr/bin/env python3
contrib/devtools/check-rpc-mappings.py|1 col 12| #!/usr/bin/env python3
contrib/devtools/security-check.py|1 col 12| #!/usr/bin/env python
contrib/devtools/optimize-pngs.py|1 col 12| #!/usr/bin/env python
contrib/devtools/test-security-check.py|1 col 12| #!/usr/bin/env python2
contrib/devtools/update-translations.py|1 col 12| #!/usr/bin/env python
contrib/devtools/github-merge.py|1 col 12| #!/usr/bin/env python3
contrib/devtools/symbol-check.py|1 col 12| #!/usr/bin/env python
contrib/devtools/clang-format-diff.py|1 col 12| #!/usr/bin/env python
```

Almost all specify python3. Having some which nominally support python2 is a bad idea, since I'd imagine no-one is even testing that they maintain compatibility with python2.

> But not be a discussion that we need to do here.

I'll open a PR to completely remove support for python2. We can move the discussion there.

**Comment by jnewbery** [comment]
I think you need a couple more changes:

- remove the no longer needed ` from __future__ import division,print_function` line
- add a `universal_newlines=True` argument to the `subprocess.Popen()` call

**Comment by laanwj** [comment]
> I'll open a PR to completely remove support for python2. We can move the discussion there.

I think the only exception would be some of the python scripts for macdeploy that still require Python 2 (@cfields probably knows).

**Comment by jnewbery** [comment]
Please squash commits together (you can do this by running `git rebase -i HEAD~3` and then selecting `f` for the second and third commits), and remove the @ jnewbery tag from the commit message (credit is not generally required for reviewers, and having @ tags in commit messages makes github spam the user).

**Comment by MarcoFalke** [comment]
If you want to do this, you should  bump `security-check.py` to py3-only as well. As I read the current code, it will run the test in py3 and the actual script in py2. Imo, this should be avoided.

**Comment by MarcoFalke** [comment]
Then, squash everything into a single commit, fix the commit message, force push and fix the pull request title.

**Comment by JavadSM** [comment]
So git does not seem to work here?

**Comment by JavadSM** [comment]
Moved to #11895

**Pull request closed without merging**
