### PR TITLE
util: Filter out macOS process serial number

### LINKED ISSUE #17179: macos: shutdown on first run due to -psn_ parameter
When downloading and running Bitcoin core for the first time, after clicking through the "Are you sure you want to open. it?" screen, there's a possibility that macOS will pass an argument like `-psn_0_SOME_ID` to the application, which results in a shutdown as it's an invalid argument:

v0 19 0rc1 args shutdown

This only happens on the first run, subsequent opens will work fine, but we should filter these out, otherwise it's a poor and confusing first experience.

### PR DESCRIPTION
**Pull request by hebasto**
Fix #17179

### CODE REVIEW

**Comment by hebasto** [comment]
@fanquake  Could "Needs gitian build" label be assigned to this PR?

**Comment by jonasschnelli** [comment]
Concept ACK.
It fairly is a bit of a hack.
Could we also add a link to the macOS documentation where this magical parameter is described?

**Comment by promag** [comment]
Concept ACK, code LGTM.

**Comment by hebasto** [comment]
> Could we also add a link to the macOS documentation where this magical parameter is described?

All the links to the macOS docs I found are dead, unfortunately ((

**Comment by laanwj** [comment]
ACK b5f0be38790ecc87a1e537edeca5923f608bc68c

I agree it's a hack, but it's also harmless, and apparently the same Qt used to do, when we still passed the command line arguments to it.

**Comment by fanquake** [comment]
@jonasschnelli the Qt filtering was happening [here](https://code.qt.io/cgit/qt/qtbase.git/tree/src/gui/kernel/qguiapplication.cpp?h=5.9.8#n1377).

```cpp
#ifdef Q_OS_MAC
        } else if (strncmp(arg, "-psn_", 5) == 0) {
            // eat "-psn_xxxx" on Mac, which is passed when starting an app from Finder.
```

Documentation on the `-psn_` params seems to be pretty light.

**Comment by MarcoFalke** [comment]
unsigned ACK b5f0be38790ecc87a1e537edeca5923f608bc68c

**Comment by promag** [comment]
ACK b5f0be38790ecc87a1e537edeca5923f608bc68c.

**Review by fanquake — APPROVED** [review]
ACK b5f0be38790ecc87a1e537edeca5923f608bc68c - Tested that this fixes #17179.

**Pull request merged**
