### PR TITLE
-bip148 option

### PR DESCRIPTION
**Pull request by earonesty**
This is based on luke-jr's "non-dos(100)" version of the code, it is mutually exclusive with  #10442.   More discussion is in  #10428.

### CODE REVIEW

**Comment by luke-jr** [comment]
For reference, just the DoS rework/fixes are in #10512

**Comment by laanwj** [comment]
Travis failure is due to
```WARNING! The following scripts are not being run: ['bip148-segwit-uasf.py']. Check the test lists in test_runner.py.
```
I think....

**Comment by jnewbery** [comment]
> Travis failure is due to *WARNING! The following scripts are not being run: ['bip148-segwit-uasf.py']. Check the test lists in test_runner.py.* I think....

Correct - on Travis it's a failure condition to have a functional test that isn't included in either `BASE_SCRIPTS` or `EXTENDED_SCRIPTS` in test_runner.py

**Comment by luke-jr** [comment]
Rebased on top of #10593 and #10594, and fixed test issues.

**Comment by ABISprotocol** [comment]
Concurrence on something that would allow user to opt-in would be grand.  Cheers

**Comment by runn1ng** [comment]
Is this branch actively maintained / usable / recommended?

Is there a reason why it's not in the upstream? (I don't follow bitcoin-dev mailing list)

**Comment by luke-jr** [comment]
@runn1ng For now, I would recommend users upgrade to https://github.com/UASF/bitcoin/

**Comment by laanwj** [comment]
Yes, the UASF branch is there, this one doesn't seem to be maintained actively.

**Comment by NainKult** [comment]
@runn1ng Politics

**Comment by runn1ng** [comment]
@luke-jr Thanks! Would you recommend to use `0.14-BIP148` branch directly, or the `v0.14.2-uasfsegwit0.3` tag (which is a little behind)?

**Comment by luke-jr** [comment]
Either should be fine.

**Comment by btcdrak** [comment]
This can be closed now.

**Pull request closed without merging**
