### PR TITLE
[trivial] Fix typos in comments

### PR DESCRIPTION
**Pull request by practicalswift**
Sorry for taking up review time with this, but I will submit *at most* once per month going forward :-)  On the bright side, I don't think there are many typos left in the repo after the merge of this PR!

Hopefully this PR should be trivial to review since all changes pertain to comments.

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by jnewbery** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/10045/commits/dbf30ff10f76d2ab9114b345e8712cba30a8d282

**Comment by paveljanik** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/10045/commits/dbf30ff10f76d2ab9114b345e8712cba30a8d282

**Comment by fanquake** [comment]
utACK dbf30ff

**Comment by jonasschnelli** [comment]
Trivial ACK https://github.com/bitcoin/bitcoin/commit/dbf30ff10f76d2ab9114b345e8712cba30a8d282

**Pull request merged**
