### PR TITLE
Doc: update release notes for changes since 0.17.0 branch

### PR DESCRIPTION
**Pull request by harding**
This documents changes listed by `git log v0.17.0...11e1ac3 --merges` and integrates the existing detached release notes into the main file.

My goal is to update the release notes each month in order to reduce the amount of writing and review that needs to be done all at once near the start of the RC cycle.

Note: I've chosen to use fully-qualified URLs for linking to documentation, rather than shorter relative URLs that would otherwise be preferred, as the release notes are commonly copied into emails, reddit threads, and blog posts where relative URLs would be incomplete or would point to the wrong page.

### CODE REVIEW

**Comment by WorkShop-Office** [comment]
On Nov 8, 2018 9:25 PM, "David A. Harding" <notifications@github.com<mailto:notifications@github.com>> wrote:


This documents changes listed by git log v0.17.0...11e1ac3 --merges and integrates the existing detached release notes into the main file.
My goal is to update the release notes each month in order to reduce the amount of writing and review that needs to be done all at once near the start of the RC cycle.
Note: I've chosen to use fully-qualified URLs for linking to documentation, rather than shorter relative URLs that would otherwise be preferred, as the release notes are commonly copied into emails, reddit threads, and blog posts where relative URLs would be incomplete or would point to the wrong page.

You can view, comment on, or merge this pull request online at:

  https://github.com/bitcoin/bitcoin/pull/14688

Commit Summary


  *   Release notes: update notes through to 11e1ac3ae08
  *   Release notes: integrate detached release notes

File Changes


  *   D doc/release-notes-13152.md<http://release-notes-13152.md> (5)
  *   D doc/release-notes-14023.md<http://release-notes-14023.md> (8)
  *   D doc/release-notes-14282.md<http://release-notes-14282.md> (9)
  *   D doc/release-notes-14296.md<http://release-notes-14296.md> (5)
  *   D doc/release-notes-14454.md<http://release-notes-14454.md> (6)
  *   D doc/release-notes-14468.md<http://release-notes-14468.md> (15)
  *   M doc/release-notes.md<http://release-notes.md> (139)

Patch Links:


  *   https://github.com/bitcoin/bitcoin/pull/14688.patch
  *   https://github.com/bitcoin/bitcoin/pull/14688.diff

**Review by maflcko — APPROVED** [review]
ACK b69f537596902c68aa4863ff98ed175dea3ff7df

**Comment by mruddy** [comment]
@harding https://github.com/bitcoin/bitcoin/pull/14060 added the config options:
-zmqpubhashblockhwm
-zmqpubhashtxhwm
-zmqpubrawblockhwm
-zmqpubrawtxhwm
I wasn't aware of the detached release note convention so I didn't make one. Should I add one now, or is this note enough for you to make mention of the new options in the release notes?

**Comment by sipa** [comment]
I'm confused; these changes look like things that were in 0.17 already; they shouldn't go into master's release-notes (which will be for 0.18).

**Comment by laanwj** [comment]
Thanks for doing this!

> I'm confused; these changes look like things that were in  0.17 already; they shouldn't go into master's release-notes (which will  be for 0.18).

Are you sure?
The command `git log v0.17.0...11e1ac3 --merges` does go down the master branch *since* the 0.17 fork. So apart from things that have been backported it should list PRs that are only on the master branch.

**Comment by laanwj** [comment]
> I wasn't aware of the detached release note convention so I didn't make one. Should I add one now, or is this note enough for you to make mention of the new options in the release notes?

If you want your feature to be documented in the release notes, preferably add one yourself, yes!

**Comment by harding** [comment]
@sipa it looks like you're correct, sorry about that. There was a large number of "backports" to 0.17 after the branch point but before the release so I didn't realize that they'd been backported.  For example, 0f681cecadb9472b3d3ae2c1dd23d8173dc2e316 was the backport that put the descriptors.md file into 0.17, meaning it isn't actually new as this PR indicates.

I'll check everything, make the edits, and comment here when I'm sure this PR only includes actual new changes.

**Comment by MarcoFalke** [comment]
The document has been backported, but it hasn't been mentioned in the release notes back then. Since it is not possible to change release notes after the release, we could not mention it at all, mention it on the 0.17.1 release, or on the master branch...?

**Comment by harding** [comment]
@MarcoFalke the document has been extended in recent commits that I think are unique to master, so I was thinking about just slightly revising my current description to say the document has been updated rather than saying it's new.  I think that accomplishes the goal of informing users about it while also only describing new changes for 0.18.

**Comment by MarcoFalke** [comment]
Good point, but the descriptor fixups have also been backported to 0.17.1 in #14566

**Comment by harding** [comment]
@MarcoFalke I was thinking about the stuff in #14150 that I think is a new feature, and not particularly useful in 0.17, and so is IMO unlikely to be backported.

**Comment by harding** [comment]
This is ready for review again.  I've reviewed each line added in this PR to determine whether the relevant code change was backported to the 0.17 branch (as of its current tip, 5150accdd2a7c7f0edf964d56bd7d34b5f740cdc) and made the necessary changes---which only affected one item: I've relabeled the output script descriptors documentation as updated (not new) and moved its position in the list down below the notices about new documentation files.

Note: this still only covers merges up to the commit mentioned in the OP; any subsequent notable merges will be documented in next month's update.

**Comment by fanquake** [comment]
utACK ba8f0c6

**Pull request merged**
