### PR TITLE
Several corrections to Greek translation

### PR DESCRIPTION
**Pull request by rex4539**

### CODE REVIEW

**Comment by achow101** [comment]
Translations should be done on [transifex](https://www.transifex.com/bitcoin/bitcoin/). Changes to translations in pull requests will end up being overwritten by the next pull from transifex.

**Comment by fanquake** [comment]
Indeed, please send translation changes upstream.

**Comment by randolf** [comment]
@achow101 @fanquake FYI:  I asked @rex4539 in PR #12593 to move these changes into a separate Pull Request.  It's good to know about https://www.transifex.com/bitcoin/bitcoin/ -- thanks.

**Comment by rex4539** [comment]
I have already started entering the changes in transifex.

**Pull request closed without merging**
