### PR TITLE
build: Drop all of the ZeroMQ patches

### PR DESCRIPTION
**Pull request by hebasto**
This PR gets rid of the all patches for ZeroMQ:
- the [Mingw-w64 5.0 (Ubuntu 18.04 bionic)](https://packages.ubuntu.com/bionic/mingw-w64) is used to build the [Windows](https://github.com/bitcoin/bitcoin/blob/master/doc/build-windows.md) binaries
- it is safe to use `pthread_setname_np` since #17538 when the minimal `glibc` version is set to 2.17; see: https://github.com/bitcoin/bitcoin/pull/11986#issuecomment-366105050

### CODE REVIEW

**Review by promag — COMMENTED** [review]
Concept ACK.

**Comment by practicalswift** [comment]
Concept ACK: less is more

**Review by theStack — COMMENTED** [review]
Concept ACK

**Comment by MarcoFalke** [comment]
```
+ make -j1 -C /home/ubuntu/build/bitcoin/depends HOST=x86_64-linux-gnu
make: Entering directory '/home/ubuntu/build/bitcoin/depends'
sha256sum: /home/ubuntu/build/bitcoin/depends/patches/zeromq/0001-fix-build-with-older-mingw64.patch: No such file or directory
sha256sum: /home/ubuntu/build/bitcoin/depends/patches/zeromq/0002-disable-pthread_set_name_np.patch: No such file or directory
Extracting zeromq...
/home/ubuntu/cache/common/zeromq-4.3.1.tar.gz: OK
Preprocessing zeromq...
/bin/sh: 1: cd: can't cd to /home/ubuntu/build/bitcoin/depends/patches/zeromq
cp: cannot stat '0001-fix-build-with-older-mingw64.patch': No such file or directory
/bin/sh: 1: cd: can't cd to /home/ubuntu/build/bitcoin/depends/patches/zeromq
cp: cannot stat '0002-disable-pthread_set_name_np.patch': No such file or directory
funcs.mk:251: recipe for target '/home/ubuntu/build/bitcoin/depends/work/build/x86_64-linux-gnu/zeromq/4.3.1-726059c460b/.stamp_preprocessed' failed
make: *** [/home/ubuntu/build/bitcoin/depends/work/build/x86_64-linux-gnu/zeromq/4.3.1-726059c460b/.stamp_preprocessed] Error 1
make: Leaving directory '/home/ubuntu/build/bitcoin/depends'

**Comment by hebasto** [comment]
@MarcoFalke 
gitian builds were maid against 763b839fad1125320f32d69621995277aa59dd0a
The current top commit is f642b49af73fedc6dc9af4ac299e4cfa80755583
Sorry.

Mind re-assigning "Needs gitian build"?

**Comment by dongcarl** [comment]
Looks like most "stable" releases of distributions have `mingw-w64` > 4 as well: https://repology.org/project/mingw-w64/versions

**Comment by laanwj** [comment]
Concept ACK, though I don't think there's any hurry to do this. I'd like to avoid going back and forth debate over this as happened with #18427.

**Review by fanquake — APPROVED** [review]
ACK f642b49af73fedc6dc9af4ac299e4cfa80755583.

079df9609e6ed2a09949ebe5e98a179f61709801 - This is ok. [As noted](https://github.com/bitcoin/bitcoin/pull/18405#issuecomment-602720833) most distros have a much more recent version of mingw-w64 available. Also if someone is using mingw-w64 < 4 (i.e Ubuntu 14.04), at least the failure will be obvious, as zmq in depends will fail to build:
```bash
In file included from src/windows.hpp:61:0,
                 from src/precompiled.hpp:49,
                 from src/address.cpp:30:
/usr/share/mingw-w64/include/iphlpapi.h:147:5: error: 'SOCKADDR_IN6' does not name a type
     SOCKADDR_IN6 Ipv6Address;
     ^
cc1plus: warning: unrecognized command line option "-Wno-tautological-constant-compare" [enabled by default]
cc1plus: warning: unrecognized command line option "-Wno-atomic-alignment" [enabled by default]
make[1]: *** [src/src_libzmq_la-address.lo] Error 1
```

However, if they are cross-compiling for Windows using 14.04, they've already got other issues to deal with. Qt doesn't build:
```bash
compiling qwindowsnativeinterface.cpp
compiling qwindowsopengltester.cpp
compiling qwin10helpers.cpp
qwin10helpers.cpp:60:37: fatal error: uiviewsettingsinterop.h: No such file or directory
 #  include <uiviewsettingsinterop.h>
                                     ^
compilation terminated.
compiling qwindowsclipboard.cpp
compiling qwindowsdrag.cpp
compiling qwindowstabletsupport.cpp
make[5]: *** [.obj/release/qwin10helpers.o] Error 1
```

and even if you build depends, skipping QT and zeromq, bitcoind doesn't compile, due to the inclusion of the `<codecvt>` header:
```bash
  CXX      libbitcoin_common_a-netbase.o
  CXX      libbitcoin_common_a-net_permissions.o
netbase.cpp:19:19: fatal error: codecvt: No such file or directory
 #include <codecvt>
                   ^
compilation terminated.
  CXX      libbitcoin_common_a-outputtype.o
  CXX      policy/libbitcoin_common_a-feerate.o
make[2]: *** [libbitcoin_common_a-netbase.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/bitcoin/src'
```

f642b49af73fedc6dc9af4ac299e4cfa80755583 - as mentioned, `pthread_setname_np` has been available since [glibc 2.12](https://sourceware.org/legacy-ml/libc-alpha/2010-05/msg00000.html). We now require 2.17+.

-------

> the Mingw-w64 5.0 (Ubuntu 18.04 bionic) is used to build the Windows binaries

I do want to mention that this by itself isn't sufficient justification for dropping patches, as the version of Ubuntu we use to build releases (which can be quite recent) isn't the only OS we have to worry about supporting.

**Pull request merged**
