### PR TITLE
script: update REVIEWERS

### PR DESCRIPTION
**Pull request by jonatack**
Meta: `git show a06eb03` indicates the commit was first made one year ago and the PR was merged in September 2020. 

It might be time for an update, if automated review requests via DrahtBot are operational.

"Regular contributors are free to add their names to specific directories or files provided that they are willing to provide a review." 

Perhaps we can compile and squash suggested updates here, per that guideline.

### CODE REVIEW

**Comment by jonatack** [comment]
Tagging @adamjonas added as author.

**Comment by laanwj** [comment]
ACK 5f4449bba1526d6630173a507b51766d7d7d382f
Also adds @hebasto which is good.
(but might be good to hold off immediate merging, as said, to aggregate more desired changes)

**Comment by Sjors** [comment]
Feel free to add below Descriptors:

```
# External signer
*external_signer*                           @sjors
docs/external-signer.md                     @sjors
*signer.py                                  @sjors
```

And somewhere else:
```
# Backwards compatibility tests
test/functional/feature_backwards_compatibility.py @sjors
test/functional/mempool_compatibility.py           @sjors
test/get_previous_releases.py                      @sjors
test/functional/wallet_upgradewallet.py            @sjors @achow101
```
(maybe use *_compatibility.py for the first two lines)

**Comment by MarcoFalke** [comment]
It wasn't clear to me whether people liked what DrahtBot does, so I am not running it 24/7. Since people are still happily adding themselves to the list, I presume I should run it more often?

**Comment by Sjors** [comment]
I don't mind getting a notification, though it might be annoying for copyright year changes and stuff like that.

**Comment by jonatack** [comment]
@Sjors nice; updated.

**Comment by MarcoFalke** [comment]
> annoying for copyright year changes

Sure, but this change should only happen once a year per file.  Though, it is currently unclear if the listed reviewers want to be notified about refactoring changes of the listed files.

**Comment by jonatack** [comment]
Just received a few dozen email notifications for everyone. Maybe a couple of times a week would be a good frequency, as a suggestion.

**Comment by jonatack** [comment]
Another PR has been opened to make updates to this file. I don't think we need two at the same time, so closing this.

**Comment by jonatack** [comment]
Re-opening, sorry, crossed signals.

**Comment by practicalswift** [comment]
ACK 48bd9ebc5db92af5162598d9a6d32a765252c701: patch looks correct :)

**Review by hebasto — APPROVED** [review]
ACK 48bd9ebc5db92af5162598d9a6d32a765252c701, I have reviewed the code and it looks OK, I agree it can be merged.

**Comment by adamjonas** [comment]
Glad to hear people still want this.

ACK 48bd9eb. I ran through the new files added with `*`s using `git ls-files`.

**Pull request merged**
