### PR TITLE
[RFC] bitcoin-asmap utility

### PR DESCRIPTION
**Pull request by sipa**
This adds a new binary, `bitcoin-asmap` that can be used to construct, inspect, and query asmap files. It replaces the Python scripts I had at https://github.com/sipa/asmap with something more performant, efficient, and auditable.

There are some rough edges still (in particular documenting the code and a number of edge cases), but I'd like to offer it for comments here. I'm not sure we want this code to be part of the Bitcoin Core codebase, but it certainly has advantages (in terms of code reuse and having consistent encoder/decoder). I think it may also be beneficial that users have a way to audit these files using code that's subject to our review and testing process.

This PR includes a fuzz test that verifies (for small, reduced inputs) that encoding produces asmap files consistent with their input, that invoking the interpreter on them works as expected, and that decoding and re-encoding does not change their behavior.

Given a text file `asmap.txt` with lines like these:

```
193.189.95.0/24 AS34906
193.189.96.0/24 AS20850
193.189.98.0/23 AS33925
193.190.0.0/15 AS2611
193.19.102.0/23 AS20485
193.19.103.0/24 AS8342
193.19.106.0/23 AS3257
```

You can run `bitcoin-asmap encode asmap.dat <asmap.txt` to construct an asmap file in a few seconds. `bitcoin-asmap decode asmap.dat` will decode it back to the original format (note however that the result may look very different, as unassigned IP ranges get remapped for efficiency). `bitcoin-asmap lookup asmap.dat 193.190.253.208` will look up one entry in it.

There is code at https://github.com/rrybarczyk/asmap-rs (by @rrybarczyk and @naumenkogs) to build input for this tool using RIPE's dumps of Internet routing tables.

### CODE REVIEW

**Comment by jonatack** [comment]
Concept ACK (leaving aside for now the question of inclusion in the codebase). This appears to be based on #18512 which should be reviewed first?

**Comment by naumenkogs** [comment]
Concept ACK. I think it makes sense for us to have this tool inside the repo, if we want to encourage using asmap, and improve the auditability/maintenance.

Did some slight code review, will do more if/when we get enough Concept ACKs.

Also, I will probably post this separately, but anyone who speaks rust is welcome to review our tool (https://github.com/rrybarczyk/asmap-rs) for aggregating routing info from various sources :)

**Comment by sipa** [comment]
Added lots of comments, and improved the encoder algorithm. I believe it will now always find the smallest encoding (in a few seconds, for realistic inputs).

**Comment by practicalswift** [comment]
Concept ACK

**Comment by jb55** [comment]
+0 for having it in the repo, Concept ACK

**Comment by luke-jr** [comment]
Ideally it should be in another repo, but maybe we're not ready for that yet if it shares a lot of code.

**Comment by Sjors** [comment]
It might be worth building this on top of #19937 as part of `bitcoin-util`.

Concept ACK on including something this into the codebase, ideally along with some instructions which are a bit sparse now.

**Comment by lestephane** [comment]
@Sjors I had the same problem with the lack of clear instructions so I created a Vagrantfile that performs all the steps in one go.

It's located at https://github.com/lestephane/vagrant-asmap

You run `vagrant up`, and after a while, if your machine has the minimum specs to run the bottleneck analysis (12GB RAM seems to be needed for me), you end up with an `ip_asn.map` file.

**Comment by dunxen** [comment]
Concept ACK

I'm working on some tooling to help with map comparisons between releases and some user experience improvements to `asmap-rs`.

Although certainly we'll have an encoded map included with every release when asmap is enabled by default, I think it still makes sense to include `bitcoin-asmap` in this repo for easier maintenance and discoverability. It's just less hassle for node operators who may be interested generating and encoding their own mappings too.

**Comment by sipa** [comment]
Closing. I'm working on external tooling for working with asmap files in https://github.com/sipa/asmap/tree/nextgen (encode, decode, diff, bottleneck, ...).

**Pull request closed without merging**
