### PR TITLE
Lint: improve subtree exclusion

### PR DESCRIPTION
**Pull request by davidgumberg**
This PR improves subtree exclusion by rewriting lint checks to reuse common exclusion logic. Most lint checks previously did not exclude `crypto/ctaes`, the locale linter did not exclude `src/crc32`

Makes the include guards lint check print all missing include guards before exiting.

Supercedes https://github.com/bitcoin/bitcoin/pull/29744

### CODE REVIEW

**Comment by davidgumberg** [comment]
I think I will leave it in here since the motivation for https://github.com/bitcoin/bitcoin/commit/54b2115bb848e1aad8a86aae858de63a851235ce is mostly the increased number of lint checks only accessible through the lint test runner. But I will split it out if anyone has an objection, or if this PR stalls.

**Comment by davidgumberg** [comment]
Windows CI appears to have timed out, Rebased to get a fresh CI run.

**Comment by fanquake** [comment]
> Looks like the conflicting https://github.com/bitcoin/bitcoin/pull/30034 is close(r) to merge, if you want to review it

This is now merged. Can you rebase here?

**Comment by davidgumberg** [comment]
Rebased to address merge conflict

**Comment by davidgumberg** [comment]
> Any thoughts on splitting the first commit out into a separate pull? Seems to be a requested feature by three people so far, but I am not sure about bundling it for review with the other changes here.

You are right, split out the first commit into: #30219

**Comment by davidgumberg** [comment]
Rebased over master since #30219 was merged.

**Comment by davidgumberg** [comment]
Closing this for now, it's up for grabs, if I have a chance to work on this again soon I'll split into smaller PR's

**Pull request closed without merging**
