### PR TITLE
getbalance example covers at least 6 confirms

### PR DESCRIPTION
**Pull request by instagibbs**

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
utACK

**Comment by jonasschnelli** [comment]
utACK 228987d84c352de691315474649475f3fbc5de28

**Comment by MeshCollider** [comment]
This is also changed in #10789

**Comment by TheBlueMatt** [comment]
Lets mark this for 15, as it is a bugfix, 10789 can come separately.

**Comment by sipa** [comment]
utACK 228987d84c352de691315474649475f3fbc5de28

**Pull request merged**
