### PR TITLE
Remove the build_msvc/testconsensus project

### PR DESCRIPTION
**Pull request by sipsorcery**
The testconsensus project is not integral to the Bitcoin Core code. It was originally added as a quick and dirty demo of how to do a consensus check with the msvc build. There are better examples.

PR #23438 made a change that caused a compiler error with the buildmsvc/testconsensus code. Rather than leave it hanging around to incur potential bitrot, or further PR build failures, it should be removed.

### CODE REVIEW

**Comment by hebasto** [comment]
Concept ACK.

https://github.com/bitcoin/bitcoin/pull/23438#issuecomment-962507565:
> I suspect no one ever uses it.

I was around the same idea recently.

**Comment by fanquake** [comment]
Concept ACK

**Review by hebasto — APPROVED** [review]
ACK bb1c84082c8a8709fec201f5768deab22c938241, tested on Windows 10 Pro (20H2).

**Comment by MarcoFalke** [comment]
I think another issue was that there was no error message in the CI log. Obviously unrelated to removing this file, but having error messages makes debugging this easier in the future.

**Pull request merged**
