### PR TITLE
ci: Build depends only once for Android build

### PR DESCRIPTION
**Pull request by maflcko**
Currently the Android task has several issues:

* It is missing a cache instruction, thus failing the build on Cirrus CI
* It is running the depends build twice

Fix those issues

### CODE REVIEW

**Comment by icota** [comment]
tACK 04254c746eb162726fde5bcf38c92a23a7a432d6

Thanks again @MarcoFalke

**Comment by MarcoFalke** [comment]
Reference that depends is built twice:

* https://cirrus-ci.com/task/6673185279049728?logs=ci#L3418
* https://cirrus-ci.com/task/6673185279049728?logs=ci#L3422 (4 lines later)

Reference that `depends/sources` is needed:

* https://github.com/bitcoin/bitcoin/pull/17227/files#diff-f054095eca878328c57407b87b16556c57551480c6a04c998c93ec0ba7c4bd2fR382

**Comment by ryanofsky** [comment]
Code review ACK faf847fa749df2fb7eabf0cb3418ff3fdc02074f. Thanks for fixing this! It was affecting some of my prs (https://github.com/bitcoin/bitcoin/pull/17227#issuecomment-806248409).

In the future since the build system is pretty obscure it would be really helpful if commit messages didn't just say what was changing but also gave some hint why changes were being made.

- faaee1a36f7dc94c5a567c26c1643f17ccf67856 ci: Set DEPENDS_DIR when setting BASE_ROOT_DIR (1/6)
  - Change seems great, but is it changing behavior or is it just cleanup? Is there something motivating it or a reason it was written the opposite way previously?
- fa7d6ea93d413d5e3e005d2cbbe815b73016a299 ci: Build depends only once for Android build (2/6)
  - Again change seems good, but what is it? It seems like it should make things faster, but is just an optimization or also a bug fix?
- fae8916f44f9f37bf7a8b3a478f779bceb0f7dc9 ci: Bump Android cross-build to Ubuntu Focal (3/6)
  - Is this a bugfix? Just cleanup? 
- fa768ac9730c7f10274afacb592cd6ce67e4fd06 cirrus: Only cache releases when needed (4/6)
  - Bugfix? Cleanup? Optimization?
- faf847fa749df2fb7eabf0cb3418ff3fdc02074f cirrus: Add missing depends_sources_cache to Android task (5/6)
  - This seems to create a new cache as described https://cirrus-ci.org/guide/writing-tasks/#cache-instruction. Is it just an optimization?

**Comment by hebasto** [comment]
@MarcoFalke 

Are you going to keep the latest "cirrus: temp" commit (04254c746eb162726fde5bcf38c92a23a7a432d6)?

**Comment by MarcoFalke** [comment]
no

**Review by hebasto — COMMENTED** [review]
Approach ACK 04254c746eb162726fde5bcf38c92a23a7a432d6

**Comment by MarcoFalke** [comment]
Added text to commit bodies

**Comment by ryanofsky** [comment]
Code review ACK fa52d7d3adc99c0e716628058b4fd083034d27e0. Only change since last review is adding descriptions and changing new RUN_UNIT_TESTS line from true to false. (I assume that change doesn't do anything because even though prior default was true, it's a cross compiled build and enabling unit tests would have no effect.)

I'm still not clear if building depends twice before commit 2/5 "ci: Build depends only once for Android build" (fac577d42330e57c17540cabdb8be43c90b715d9) was actually causing problems or just a messy and unnecessary thing to do. But maybe it's not known. In any case the new descriptions are clear and very helpful!

**Review by hebasto — APPROVED** [review]
ACK fa52d7d3adc99c0e716628058b4fd083034d27e0, I have reviewed the code and it looks OK, I agree it can be merged after passing CI.

**Comment by hebasto** [comment]
Maybe also optimize SDK cache:
```diff
--- a/.cirrus.yml
+++ b/.cirrus.yml
@@ -33,8 +33,6 @@ global_task_template: &GLOBAL_TASK_TEMPLATE
     folder: "/tmp/ccache_dir"
   depends_built_cache:
     folder: "/tmp/cirrus-ci-build/depends/built"
-  depends_sdk_cache:
-    folder: "/tmp/cirrus-ci-build/depends/sdk-sources"
   ci_script:
     - ./ci/test_run_all.sh
 
@@ -161,6 +159,8 @@ task:
 
 task:
   name: 'macOS 10.14 [gui, no tests] [focal]'
+  depends_sdk_cache:
+    folder: "/tmp/cirrus-ci-build/depends/sdk-sources"
   << : *GLOBAL_TASK_TEMPLATE
   container:
     image: ubuntu:focal
@@ -185,6 +185,8 @@ task:
   name: 'ARM64 Android APK [focal]'
   depends_sources_cache:
     folder: "/tmp/cirrus-ci-build/depends/sources"
+  depends_sdk_cache:
+    folder: "/tmp/cirrus-ci-build/depends/sdk-sources"
   << : *GLOBAL_TASK_TEMPLATE
   container:
     image: ubuntu:focal
```
?

**Pull request merged**
