### PR TITLE
gui: Make send and receive widgets extend QWidget

### PR DESCRIPTION
**Pull request by promag**
These aren't dialogs.

### CODE REVIEW

**Comment by promag** [comment]
Let me know if I should include script-diff to rename classes and files.

**Comment by hebasto** [comment]
Concept ACK.

> Let me know if I should include script-diff to rename classes and files.

I [think](https://github.com/bitcoin/bitcoin/issues/17607#issuecomment-559018437) so.

**Comment by hebasto** [comment]
This PR also requires:
- corresponding changes in `forms/*.ui` files
- dropping `QDialog` slots and signals.

**Comment by fanquake** [comment]
This has a concept ACK, but looks like it may need additional (qt only) changes, conversion to a scripted diff where  appropriate and in any case needs a rebase. I'm going to suggest re-opening this in https://github.com/bitcoin-core/gui.

**Pull request closed without merging**
