### PR TITLE
build: Update univalue subtree

### PR DESCRIPTION
**Pull request by maflcko**
Just a minor bugfix: Currently we don't push booleans into arrays, but if we did they'd be pushed as integers.

Can be tested by reverting the diff in `include/` and observing a test failure.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
See also https://github.com/bitcoin/bitcoin/tree/master/test/lint#git-subtree-checksh

**Comment by laanwj** [comment]
ACK fa17eef6274811be5348149443e563bca95d54a3

Unfortunately these kind of errors (combined with C++'s automatic type promotion) is one of the pitfalls of using C++ method overloading

**Comment by practicalswift** [comment]
cr ACK fa17eef6274811be5348149443e563bca95d54a3

Implicit conversions are the worst! 😢

**Comment by luke-jr** [comment]
Why isn't this upstreamed?

**Pull request merged**
