### PR TITLE
qa: Make TestNodeCLI command optional in send_cli

### PR DESCRIPTION
**Pull request by maflcko**
Makes the `command` optional, since there are valid bitcoin-cli calls that have no `command`:

* `bitcoin-cli -?`
* `bitcoin-cli -getinfo`
* ...

Also, rename self.args to self.options, since that is the name in the `bitcoin-cli -help` documentation.

### CODE REVIEW

**Comment by jnewbery** [comment]
Tested ACK fab04c3f55715f8d63ae88d087e9ea83f525a670

**Review by ryanofsky — COMMENTED** [review]
utACK fab04c3f55715f8d63ae88d087e9ea83f525a670, but could be cleaned up slightly.

**Review by ryanofsky — COMMENTED** [review]
utACK fae7b14a0468fba43ca8ce87249be69e13cea608. Thanks for update! Only changes since last review were what was suggested.

**Comment by jnewbery** [comment]
Tested ACK fae7b14a0468fba43ca8ce87249be69e13cea608

**Pull request merged**
