### PR TITLE
Remove connect_nodes global and Replace connect_nodes(self.nodes[a], b) with self.connect_nodes(a, b)

### PR DESCRIPTION
**Pull request by ghost**
Made changes in 37 files based on the issue and solution suggested by MarcoFalke in https://github.com/bitcoin/bitcoin/issues/19821

### CODE REVIEW

**Comment by michaelfolkson** [comment]
A few things to note from the contributing [guidelines](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md).

- The contributor [workflow](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#contributor-workflow) is to fork the project and create a separate topic branch (i.e. not open a PR from master)
- You should [use](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#committing-patches) the fixes or closes keywords when referencing the issue it fixes/closes as this will cause the corresponding issue to be closed when the pull request is merged.
- For find and replace like exercises we use [scripted diffs](https://github.com/bitcoin/bitcoin/blob/bab4cce1b0eedc1a51692aaf83ba54dd0a9d17e6/doc/developer-notes.md#scripted-diffs). 

If anything isn't clear or you need further help let us know.

**Comment by prayank23** [comment]
1. I had created a separate branch for [bitcoin-core/gui](https://github.com/bitcoin-core/gui) but I thought master branch can be used for https://github.com/bitcoin/bitcoin

I can use a different branch in future or delete this if it's not acceptable.

2. Agree I could have used a better description. In this case there wasn't much to describe and I thought it's better to link the issue which has all the details instead of writing the same thing.

3. While making the changes I realized it requires manually doing it carefully. So not sure if it could have been done with script.

4. There were some conflicts during CI checks and trying to resolve them I created few others so completely deleted old PR and created new one.

5. I will keep the things in mind while submitting a PR in future, let me know if this needs changes/closure or can be merged.

**Comment by michaelfolkson** [comment]
> I had created a separate branch for bitcoin-core/gui but I thought master branch can be used for bitcoin/bitcoin

I would recommend you fork both repositories (bitcoin/bitcoin and bitcoin-core/gui) individually and treat them as separate repos. 

In reality bitcoin/bitcoin pulls in changes made to bitcoin-core/gui but if you continue contributing you will be opening PRs and reviewing PRs on both repositories depending on whether it is GUI or not. Then you can have your master branch follow the master of each repo and set up topic branches off master.

> While making the changes I realized it requires manually doing it carefully. So not sure if it could have been done with script.

Unless I am missing something this is a find and replace which can be done using a scripted-diff. I don't think this will be merged without a scripted-diff but someone more experienced can correct me if I am wrong.

> I will keep the things in mind while submitting a PR in future, let me know if this needs changes/closure or can be merged.

As I said I don't think this will be merged as is. You'd need to close this PR to open a new PR from a topic branch and provide a scripted-diff. If you need help with the latter please say.

**Comment by khendri** [comment]
Mantap

**Comment by robot-dreams** [comment]
Thanks so much for working on this, @prayank23 !

I've built on your work over in #19967  to use a scripted-diff as suggested, and I kept you as the PR author for the relevant commit: 1d21af136e67ba25f4734ed077020ffcc761c07b

**Comment by michaelfolkson** [comment]
Yeah nice work @prayank23. Hopefully [this](https://bitcoin.stackexchange.com/questions/98989/why-do-some-bitcoin-core-good-first-issues-require-scripted-diffs) will be useful for future new contributors.

Feel free to look at the scripted-diff commit in @robot-dreams PR and if it works, makes sense to you, you can [review](https://jonatack.github.io/articles/how-to-review-pull-requests-in-bitcoin-core) his PR by Approach ACKing or ACKing the commit.

**Pull request closed without merging**
