### PR TITLE
Test some transaction creation with non-empty fee estimator

### PR DESCRIPTION
**Pull request by instagibbs**
These tests give additional coverage to RPCs that use `conf_target` in a meaningful way that doesn't just return min rates.

Inspired by https://github.com/bitcoin/bitcoin/issues/18240

### CODE REVIEW

**Comment by instagibbs** [comment]
Probably a good idea to stick this test somewhere else, but that would require either replication of this test(filling out the estimator?) or refactoring it to use it as a library.

**Comment by instagibbs** [comment]
one build failing:
```
    assert_fee_amount(tx2_info["fee"], tx2_info["vsize"], med_fee)
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/util.py", line 39, in assert_fee_amount
    raise AssertionError("Fee of %s BTC too low! (Should be %s BTC)" % (str(fee), str(target_fee)))
AssertionError: Fee of 0.00008981 BTC too low! (Should be 0.00012702 BTC)
```
Will investigate

**Comment by instagibbs** [comment]
not taking this further, someone else can pick it up

**Comment by jonatack** [comment]
@instagibbs I wrote/am writing `conf_target` tests as part of follow-ups to #11413 and will look at pulling these commits in.

**Pull request closed without merging**
