### PR TITLE
[24.x] Backports for rc2

### PR DESCRIPTION
**Pull request by fanquake**
Will collect backports for rc2 as they become available. Currently:
* https://github.com/bitcoin/bitcoin/pull/25858
* https://github.com/bitcoin/bitcoin/pull/26124
* https://github.com/bitcoin/bitcoin/pull/26149
* https://github.com/bitcoin/bitcoin/pull/26172
* https://github.com/bitcoin/bitcoin/pull/26205
* https://github.com/bitcoin/bitcoin/pull/26212
* https://github.com/bitcoin/bitcoin/pull/26215

### CODE REVIEW

**Comment by instagibbs** [comment]
anymore backports expected for rc2?

**Comment by MarcoFalke** [comment]
Yes, see https://github.com/bitcoin/bitcoin/milestone/54

**Comment by dergoegge** [comment]
ACK  5ad82a09b409d416236092062a4201e238dfd68b

**Comment by achow101** [comment]
ACK e2e4c2969ba753a94587985582123a596f57067b

**Comment by LarryRuane** [comment]
post-merge ACK e2e4c2969ba753a94587985582123a596f57067b

**Pull request merged**
