### PR TITLE
[22.x] qt: Pre-rc2 translations update

### PR DESCRIPTION
**Pull request by hebasto**
Since 6312b8370c5d3d9fb12eab992e3a32176d68f006 translations are still updating everyday.

I'm going to keep this PR updated until the moment just before tagging rc2, when it is expected to be merged.

Hope this will make life of both translators and release maintainers a bit easier :)

### CODE REVIEW

**Comment by hebasto** [comment]
cc @laanwj

**Comment by hebasto** [comment]
> I'm going to keep this PR updated...

Updated.

---

Is "Backport" label required here?

**Comment by hebasto** [comment]
Updated.

**Comment by laanwj** [comment]
> Is "Backport" label required here?

Not really, because it's not; we don't tend to do translations updates on master after split-off, only on the branch.

**Comment by laanwj** [comment]
CI failure seems unrelated (but looks fairly scary, something fuzzing-related).

**Comment by hebasto** [comment]
> CI failure seems unrelated (but looks fairly scary, something fuzzing-related).

#22537

**Comment by hebasto** [comment]
Updated.

This update does _not_ remove German (de) translation that was removed from Transifex.com by [Daoudia](https://www.transifex.com/user/profile/Daoudia/) 21 hours ago:

Screenshot from 2021-07-28 01-44-10

**Comment by hebasto** [comment]
Updated.

**Comment by hebasto** [comment]
Updated.

I've restored the German (de) translation in Transifex.com from [bitcoin_de.ts](https://github.com/bitcoin/bitcoin/blob/22.x/src/qt/locale/bitcoin_de.ts).

**Comment by hebasto** [comment]
Updated.

**Pull request closed without merging**
