### PR TITLE
Extract consts for WITNESS_V0 hash sizes

### PR DESCRIPTION
**Pull request by Empact**

### CODE REVIEW

**Comment by MarcoFalke** [comment]
utACK 3450a9b25cd6dbc69daf946bd3a610681ee61317

**Comment by sipa** [comment]
utACK 3450a9b25cd6dbc69daf946bd3a610681ee61317

**Comment by jnewbery** [comment]
utACK 3450a9b25cd6dbc69daf946bd3a610681ee61317

**Comment by laanwj** [comment]
```bash
$ git ls-files | xargs sed -i 's/WITNESS_V0_SCRIPTHASH_SIZE/32/g'
$ git ls-files | xargs sed -i 's/WITNESS_V0_KEYHASH_SIZE/20/g'
$ git diff HEAD~1
```
```patch
diff --git a/src/script/interpreter.h b/src/script/interpreter.h
index bb7750d..6ad84a7 100644
--- a/src/script/interpreter.h
+++ b/src/script/interpreter.h
@@ -129,6 +129,10 @@ enum class SigVersion
     WITNESS_V0 = 1,
 };
 
+/** Signature hash sizes */
+static constexpr size_t 32 = 32;
+static constexpr size_t 20 = 20;
+
 uint256 SignatureHash(const CScript &scriptCode, const CTransaction& txTo, unsigned int nIn, int nHashType, const CAmount& amount, SigVersion sigversion, const PrecomputedTransactionData* cache = nullptr);
 
 class BaseSignatureChecker
```
ACK 3450a9b25cd6dbc69daf946bd3a610681ee61317

**Pull request merged**
