### PR TITLE
wallet: Add size check on meta.key_origin.path

### LINKED ISSUE #21605: wallet: Segmentation fault during sync
Trying to sync my several years old wallet using bitcoin-qt on Linux WITH PRUNING ON. After 44% (around Dec. 3 2017, 16:xx), it quits with a segmentation fault. Guessing from the date, I could have made a transaction from that wallet around that time. Tried different computers with different flavors of Linux (Ubuntu 20.04, q4os 20.04) to no avail. If I am syncing without a wallet, it works.
Here, logs from a run with GDB and a subsequent backtrace (not sure if that helps, please contact me for debug info):

Reading symbols from ./bitcoin/bitcoin-0.21.0/bin/bitcoin-qt...
(No debugging symbols found in ./bitcoin/bitcoin-0.21.0/bin/bitcoin-qt)
(gdb) start
Function "main" not defined.
Make breakpoint pending on future shared library load? (y or [n]) n
Starting program: /home/chrischan/bitcoin/bitcoin-0.21.0/bin/bitcoin-qt 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff742f700 (LWP 32345)]
[New Thread 0x7ffff63dc700 (LWP 32346)]
[New Thread 0x7ffff5a9a700 (LWP 32347)]
[New Thread 0x7fffe6ffe700 (LWP 32348)]
[New Thread 0x7fffe67fd700 (LWP 32349)]
[New Thread 0x7fffc5881700 (LWP 32350)]
[New Thread 0x7fff4a870700 (LWP 32353)]
[New Thread 0x7fff42ee6700 (LWP 32354)]
[Thread 0x7fff4a870700 (LWP 32353) exited]
[New Thread 0x7fff426e5700 (LWP 32355)]
[New Thread 0x7fff41ee4700 (LWP 32356)]
[New Thread 0x7fff416e3700 (LWP 32357)]
[New Thread 0x7fff40ee2700 (LWP 32358)]
[New Thread 0x7fff2bfff700 (LWP 32359)]
[New Thread 0x7fff2b7fe700 (LWP 32360)]
[New Thread 0x7fff2affd700 (LWP 32361)]
[New Thread 0x7fff2a7fc700 (LWP 32362)]
[Thread 0x7fff41ee4700 (LWP 32356) exited]

Thread 6 "b-scheduler" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe67fd700 (LWP 32349)]
0x0000555555c2ba7b in ?? ()
(gdb) bt
#0  0x0000555555c2ba7b in ?? ()
#1  0x0000555555c4d72d in ?? ()
#2  0x0000555555c4e03d in ?? ()
#3  0x0000555555c4e454 in ?? ()
#4  0x0000555555ac964b in ?? ()
#5  0x0000555555da43b0 in ?? ()
#6  0x0000555555da31ca in ?? ()
#7  0x00005555558a097b in ?? ()
#8  0x0000555555e6e58a in ?? ()
#9  0x00007ffff7f9c609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#10 0x00007ffff7c16293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) 

**System information**

V21.0, from website, verified signature

(1) Old asus EeePc, 2MB RAM, 250GB SSD
(2) Acer Laptop, 4MB RAM, 250GB SSD 

Ubuntu 20.04
Q4OS (latest)

### PR DESCRIPTION
**Pull request by rooprob**
Resolves https://github.com/bitcoin/bitcoin/issues/21605 segfault on legacy wallet

I also encountered same [*] when resyncing a 2017 era blockchain.
* https://gist.github.com/rooprob/91d78358b920b8f8b7df78af8b2ce99c

### CODE REVIEW

**Comment by laanwj** [comment]
Concept ACK, I agree this shouldn't cause a crash.

**Comment by achow101** [comment]
The root cause of the problem this is fixing is that the wallet does not contain the upgraded key metadata because it is encrypted and has not been unlocked yet, and a transaction was found that involved inactive HD chains. So this segfault can be triggered with a non-corrupted wallet. I don't think it is necessarily correct to log an error and move on as doing so could result in missing funds.

To avoid the crash, I think access to `meta.key_origin.path` should be guarded by both the length check and `meta.has_key_origin`. Then if `has_key_origin == false`, `meta.hdKeypath can be used` to figure out what to derive. This would avoid the segfault while not losing any functionality.

**Comment by achow101** [comment]
> when I encountered this, this was the state of meta,

This matches what I expect. The meta is not upgraded (nVersion is 10, not 12, and has_key_origin is false).

**Comment by achow101** [comment]
@rooprob Are you planning on continuing to work on this PR? If not, I can take it over in #23304

**Comment by rooprob** [comment]
> @rooprob Are you planning on continuing to work on this PR? If not, I can take it over in #23304

I think it's better to follow up in your PR.  I shall withdraw this PR.

Thanks for picking this up in #23304

**Pull request closed without merging**
