### PR TITLE
fuzz: Add UBSan suppressions needed for fuzz tests to not warn under -fsanitize=integer

### PR DESCRIPTION
**Pull request by practicalswift**
Add UBSan suppressions needed for fuzz tests to not warn under `-fsanitize=integer`.

Avoid `-fsanitize=integer` warnings in fuzzing harnesses.

Suppressed warnings (excluding warnings from `src/crypto/` and `src/test/`):

```
addrman.cpp:306:24: runtime error: implicit conversion from type 'long' of value 5190149478 (64-bit, signed) to type 'uint32_t' (aka 'unsigned int') changed the value to 895182182 (32-bit, unsigned)
addrman.h:446:43: runtime error: implicit conversion from type 'int' of value -22 (32-bit, signed) to type 'const uint8_t' (aka 'const unsigned char') changed the value to 234 (8-bit, unsigned)
arith_uint256.cpp:32:35: runtime error: left shift of 1712128 by 24 places cannot be represented in type 'uint32_t' (aka 'unsigned int')
arith_uint256.cpp:47:39: runtime error: left shift of 4294966784 by 31 places cannot be represented in type 'uint32_t' (aka 'unsigned int')
chain.cpp:151:12: runtime error: implicit conversion from type 'int' of value -1 (32-bit, signed) to type 'unsigned long' changed the value to 18446744073709551615 (64-bit, unsigned)
coins.cpp:114:22: runtime error: unsigned integer overflow: 0 - 96 cannot be represented in type 'unsigned long'
compressor.cpp:162:33: runtime error: unsigned integer overflow: 15617702637291228364 * 10 cannot be represented in type 'unsigned long'
compressor.cpp:188:11: runtime error: unsigned integer overflow: 2265760372865400000 * 10 cannot be represented in type 'unsigned long'
hash.cpp:13:15: runtime error: left shift of 1692305888 by 15 places cannot be represented in type 'uint32_t' (aka 'unsigned int')
pubkey.h:152:23: runtime error: unsigned integer overflow: 0 - 1 cannot be represented in type 'unsigned int'
streams.h:570:31: runtime error: left shift of 350879 by 52 places cannot be represented in type 'uint64_t' (aka 'unsigned long')
util/bip32.cpp:57:36: runtime error: left shift of 3241096244 by 1 places cannot be represented in type 'unsigned int'
util/strencodings.cpp:562:38: runtime error: implicit conversion from type 'unsigned char' of value 255 (8-bit, unsigned) to type 'char' changed the value to -1 (8-bit, signed)
util/strencodings.h:164:24: runtime error: implicit conversion from type 'int' of value -74 (32-bit, signed) to type 'unsigned long' changed the value to 18446744073709551542 (64-bit, unsigned)
```

The warnings above happen here:

https://github.com/bitcoin/bitcoin/blob/32b191fb66e644c690c94cbfdae6ddbc754769d7/src/addrman.cpp#L306
https://github.com/bitcoin/bitcoin/blob/32b191fb66e644c690c94cbfdae6ddbc754769d7/src/addrman.h#L446
https://github.com/bitcoin/bitcoin/blob/32b191fb66e644c690c94cbfdae6ddbc754769d7/src/arith_uint256.cpp#L32
https://github.com/bitcoin/bitcoin/blob/32b191fb66e644c690c94cbfdae6ddbc754769d7/src/arith_uint256.cpp#L47
https://github.com/bitcoin/bitcoin/blob/32b191fb66e644c690c94cbfdae6ddbc754769d7/src/chain.cpp#L151
https://github.com/bitcoin/bitcoin/blob/32b191fb66e644c690c94cbfdae6ddbc754769d7/src/coins.cpp#L114
https://github.com/bitcoin/bitcoin/blob/32b191fb66e644c690c94cbfdae6ddbc754769d7/src/compressor.cpp#L162
https://github.com/bitcoin/bitcoin/blob/32b191fb66e644c690c94cbfdae6ddbc754769d7/src/compressor.cpp#L188
https://github.com/bitcoin/bitcoin/blob/32b191fb66e644c690c94cbfdae6ddbc754769d7/src/hash.cpp#L13
https://github.com/bitcoin/bitcoin/blob/32b191fb66e644c690c94cbfdae6ddbc754769d7/src/pubkey.h#L152
https://github.com/bitcoin/bitcoin/blob/32b191fb66e644c690c94cbfdae6ddbc754769d7/src/streams.h#L570
https://github.com/bitcoin/bitcoin/blob/32b191fb66e644c690c94cbfdae6ddbc754769d7/src/util/bip32.cpp#L57
https://github.com/bitcoin/bitcoin/blob/32b191fb66e644c690c94cbfdae6ddbc754769d7/src/util/strencodings.cpp#L562
https://github.com/bitcoin/bitcoin/blob/32b191fb66e644c690c94cbfdae6ddbc754769d7/src/util/strencodings.h#L164

### CODE REVIEW

**Comment by practicalswift** [comment]
See #21001 for the `src/coins.cpp` case. It should probably be addressed rather than suppressed.

**Comment by practicalswift** [comment]
@MarcoFalke It is currently complete only with regards to the fuzz tests.

More specifically it survives the following under `-fsanitize=integer`:

```
$ ./fuzz_survival_test.sh 2
Running fuzzer "addition_overflow" for 2 second(s): ✅
Running fuzzer "addrdb" for 2 second(s): ✅
Running fuzzer "address_deserialize" for 2 second(s): ✅
Running fuzzer "addr_info_deserialize" for 2 second(s): ✅
Running fuzzer "addrman" for 2 second(s): ✅
…
```

`fuzz_survival_test.sh` can be found here: https://gist.github.com/practicalswift/e3de0d96af31f42d3a2f5bcb6f631432

I haven't gotten around to covering also the unit tests and functional tests, but it makes sense to cover them as well. I'll look in to expanding the scope of this PR to cover them too :)

**Comment by MarcoFalke** [comment]
I was running the `process_messages` harness, compiled with `clang version 11.0.0` sanitizers: `fuzzer,integer`. Which version are you using for testing?

**Comment by practicalswift** [comment]
@MarcoFalke Oh, I was starting from an empty seed corpus.

I've now added all `-fsanitize=integer` suppressions needed for the following commands to pass:

1. Unit tests
1. Functional tests
1. Fuzz tests starting with an empty corpus and running for a minute or so
1. Fuzz tests running over the `qa-assets` corpus

To reproduce:

```
# Unit tests
$ UBSAN_OPTIONS="print_stacktrace=1:halt_on_error=1:report_error_type=1:suppressions=$(pwd)/test/sanitizer_suppressions/ubsan" \
      src/test/test_bitcoin

# Functional tests
$ UBSAN_OPTIONS="print_stacktrace=1:halt_on_error=1:report_error_type=1:suppressions=$(pwd)/test/sanitizer_suppressions/ubsan" \
      test/functional/test_runner.py --timeout-factor=0 --failfast --combinedlogslen=100

# Fuzz tests starting with an empty corpus
$ ./fuzz_survival_test.sh # From https://gist.github.com/practicalswift/e3de0d96af31f42d3a2f5bcb6f631432

# Fuzz tests running over the qa-assets corpus
# Run ./fuzz_survival_test.sh after adjusting it to use the qa-seeds corpus.
$ ./fuzz_survival_test_qa.sh
```

**Comment by MarcoFalke** [comment]
review ACK f0f8b1a076c362c6e26570a2129809f4d6a0abad 🤚

<details><summary>Show signature and timestamp</summary>

Signature:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

review ACK f0f8b1a076c362c6e26570a2129809f4d6a0abad 🤚
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEE+rVPoUahrI9sLGYTzit1aX5ppUgFAlwqrYAACgkQzit1aX5p
pUgaOwv/Yl+4miTBnNJtB6jjBfibJcMOStYIEzi0t/LWFwEPNOViBnz4+FBYszgy
a2Zusppxw/Mt7hKB1cHmJgs9WAgS3kTXyH/c1vg043d7/qQrOBxSXu7EL/xO3sx8
NCDmXoIyMT0+wWdLFg/TGP/TeGnmmoK+UJ/i/seEl5quVaBPTauP3sdZv6tGqRaP
zY1Qq8btdAGohbp8o6Sxwp7gjfQBjoy8ggH4TheiGSpvuyvbomDcEmNu/j0E3b4d
t8g1Ef3Vcve88BN8SvRB5UN+DtpNjbsKjMjxTh8k1GOGEKgv3QdKABkNjQjsKABx
I3FbSZz0wElfIBHDZL6W7jopwhMFPf24v1dWKJyCNI1IwNE0T23EOndZxFpKqFKW
ZG5EhSY19vAkykW6NUo9KRUfHzuPvKPRBC64cvtX2AShHvltPynesIJkM2d+LTyn
2sW6Je34/oOKnWoyA2JrxlyMgJXzIqZkSFbfQAqztY8BU87sMcILEdxlV7leLdch
CZsN3rMe
=5LC+
-----END PGP SIGNATURE-----
```

[Timestamp of file with hash `6949a3e88bd4ef7a52797e84db8a5eea62639166a78d8c2eed13eccb4dcfd32d  -`](https://opentimestamps.org/info/?004f70656e54696d657374616d7073000050726f6f6600bf89e2e884e8929401086949a3e88bd4ef7a52797e84db8a5eea62639166a78d8c2eed13eccb4dcfd32df01063b4cbe045c75c6165f79a53a25b26a708fff0106086892e614c5654099d0e50e9f7833e08f104600fcf93f0088e51747a8d0ba8af0083dfe30d2ef90c8e2e2d68747470733a2f2f616c6963652e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267fff0108ba9b4ce50a0adba84049b31b0ae4bdf08f104600fcf93f008004437824d6029050083dfe30d2ef90c8e2c2b68747470733a2f2f626f622e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267fff010b72430a877b8c3180b855ee11327d79408f02052db99f7ec2b115603acf23074ba6095550f18d1a5a7a340c56ed26279d97f2408f104600fcf94f00843936ab385a9ca560083dfe30d2ef90c8e292868747470733a2f2f66696e6e65792e63616c656e6461722e657465726e69747977616c6c2e636f6df010ca0cd2b4611d5a7ff003b1808ad34c1a08f12097a3319b250b2ee099206796a0176c943676463266ff82a8029b31ce28a100ec08f104600fcf95f0084f725155779053400083dfe30d2ef90c8e232268747470733a2f2f6274632e63616c656e6461722e636174616c6c6178792e636f6d)

</details>

**Comment by MarcoFalke** [comment]
review ACK 0d9899789e5d8f834eeb1bc67017a79bbc77530a 🎅

<details><summary>Show signature and timestamp</summary>

Signature:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

review ACK 0d9899789e5d8f834eeb1bc67017a79bbc77530a 🎅
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEE+rVPoUahrI9sLGYTzit1aX5ppUgFAlwqrYAACgkQzit1aX5p
pUhBggwAhZaV0ehCdKDwIh/BP4PCpM/dybM7tXzkTO+Q31MgI3deJ31J0BXs+zSi
fBv16UbSLLXMAO7BmSOjt7WO4Q8f+B138ERrR+1W6DlmR8HJ/6hZTaiQAlikQIG5
ixgzzH1PX6FdMsAbTGbIrWOv4hflIoIs2MkKjXnKRKighD62viF8KFrzZSUOwls8
EYCxo/mcLE9uPWsccnUWM6ElpBwLwXdloEIDz9+k1X26VHVQk5Hb44dLOjFSIJld
vSZhRVgt8o9ZDaWV2F2Qi64A7pQAkvZ/fXjommAbeBZtzrh95r+WRECzXWjVnjrA
KtwcI9rYfbzePawFtxN4RHQab5VDxqUU1Og7ZG7c0ro6sqL8sM3eianvZaRnCJb1
EkR9k/yicw//S9XKXyNX/xVjBe/ead9IQdzUCLYbLqfbhj95nZxSzF47iAtJsnV0
m26U/s8d6zBtSsGFqk1q3Qa/58U4EFqrs05OTItaFsJ65lO3nFEDp0nroetojw+M
dWk7V6vD
=8Lkf
-----END PGP SIGNATURE-----
```

[Timestamp of file with hash `a8d5520f601c503b2ecc40e4169f8355ed84571b1827d52455af1e4256107a2b  -`](https://opentimestamps.org/info/?004f70656e54696d657374616d7073000050726f6f6600bf89e2e884e892940108a8d5520f601c503b2ecc40e4169f8355ed84571b1827d52455af1e4256107a2bf010f23caaa856d5e89f54c1918e53fed01b08fff01031a58128b0aa50cb869368eef5ae6f2608f1207b0d78c669dbc92e85173115924c844ffca475751f0144e87da460b28d3a433e08f020bff39e62b8151c966273ce51f6050eb6c0501a63c7f0765abfb54d771d5b48f908f0203f69854ee9df3fe1cad4c2c4378ab6039f3ac14dc9674e1345a59d423c45ca5108f104600fcfb4f0083dd8995ee25035530083dfe30d2ef90c8e292868747470733a2f2f66696e6e65792e63616c656e6461722e657465726e69747977616c6c2e636f6dfff0109a23cf32ee5eac59806370daf5eab9b908f104600fcfb5f008a68042f654d9414c0083dfe30d2ef90c8e232268747470733a2f2f6274632e63616c656e6461722e636174616c6c6178792e636f6dfff010bb963bc5ccbd1cb094a3c0e802a124e508f120432f44f8b9ae5c1b93b0d0f1553a22b80238502b860b23b98c7513c45c7fca2508f020231091c071cd76eb9ffa071d23955a16cfb075008193d1e0b13e325eec023ae308f104600fcfb4f008a5c1dc83c2eff46b0083dfe30d2ef90c8e2c2b68747470733a2f2f626f622e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267f010f89d0abd163e93d4a9dcf70badab292608f020076864119ddf8d2abe52b5d8642b595473ea4fc340dc5c320d56be2572f633ba08f020af10c4858ae556799ea602984d57a9c5ec2565db61c0ad794a8947fea517d83208f020be26a3df9c61d52b11b4da1d4688f3af8ee068f6e632d3538e214e9f4a34ef4108f104600fcfb4f008cb625e5abc6646820083dfe30d2ef90c8e2e2d68747470733a2f2f616c6963652e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267)

</details>

**Comment by MarcoFalke** [comment]
Force pushed to remove unrelated commit. Hope you don't mind @practicalswift

**Comment by MarcoFalke** [comment]
Only change was in the linter, which passed. So we don't need to wait for the other ci checks before merge.

**Pull request merged**
