### PR TITLE
Slightly improve gitian building guide

### PR DESCRIPTION
**Pull request by Michagogo**
Change the gitian building guide such that it modifies the VirtualBox NAT
setting (to 192.168.11/24, to make @gavinandresen happy) rather than
overriding Gitian's default IP address in ways that may or may not have
broken/break in the future, considering how fickle/fragile/volatile Gitian
is. Once we're using vboxmanage anyway, replace the multi-step process of
adding the port forwarding rule (and 2 images) with the one-line command
to do the same thing.

Note that this guide may not work in other ways, for other reasons -- for
example, with the new depends system, stuff may need to change. I haven't
gotten around to looking at the changes to gitian building in depth, so I
don't know how much needs to be fixed/rewritten.

### CODE REVIEW

**Comment by laanwj** [comment]
@jgarzik Why did you remove the "Docs and output" label here? This concerns documentation so that would be the appropriate label.

**Comment by jgarzik** [comment]
@laanwj Odd.  It is most likely a mis-click.

**Comment by theuni** [comment]
@Michagogo on OSX, this is "VBoxManage" rather than "vboxmanage". I'd really rather not mix gui/cli commands though, let's try to use one or the other.

To change the ip range, I instead created a new Nat Network, set it to 10.0.11.0/24, and bound gitianbuilder to that. All via the GUI, and it seems to work with no issues. Any reason not to use that approach?

**Comment by laanwj** [comment]
@theuni If you can do it through the GUI, that's way preferable. The only reason for the command-line workaround was that it didn't seem to be possible through the GUI.

**Comment by Michagogo** [comment]
Ah! That keyword is very helpful. Did some Googling... Looks like it can be done with the GUI, but the trick is that you need to go to the global Virtualbox preferences, and create a new "NAT Network", where you can (among other things) set the address range. Once you've done that, you can attach the individuals VMs to that network. A very counterintuitive way to do that, if you ask me. @laanwj want to try it and update the guide? I'd do it, but I'm on my phone and don't know when I'll be able to get around to it, and also I'm on Windows, so the GUI looks different. Better to keep it consistent. @theuni Good catch!

**Comment by Michagogo** [comment]
@theuni Also, it's VBoxManage on Windows too, but that's case insensitive. I changed it to lowercase after someone said that on Linux (iirc) it's lowercase, and I tested on a Mac and found that there was a symlink from the lowercase to the capitalized one.

**Comment by theuni** [comment]
@Michagogo I can update it, since it seems like that's cross-platform friendly. Will do.

**Pull request closed without merging**
