### PR TITLE
ci: Place datadirs for tests under tmpfs

### PR DESCRIPTION
**Pull request by maflcko**
This should speed up the tests a bit (see comment below for results).

### CODE REVIEW

**Comment by laanwj** [comment]
Using tmpfs for temporary test directories can potentially speed up tests a lot, something to be wary for is that it significantly increases memory usage as well (no idea if this is a problem for the current CI).

**Comment by laanwj** [comment]
> I'd say the memory increase shouldn't matter, because on modern distros the default temp dir is already a tmpfs. So if memory was an issue, then running the tests normally (outside the CI) would already lead to issue reports. (I haven't seen any, but I may be missing some).

i don't think anyone runs the tests in low-memory/dis conditions 😄 i've had some issues on custom RISC-V hardware in the past, but nothing significant enough to create an issue about. At least the CI with start with a clean slate every time so no cruft accumulates in tmpfs.

**Comment by TheCharlatan** [comment]
> (see comment below for results).

What is this referring to?

**Comment by willcl-ark** [comment]
That is odd, and a little disappointing. The code appears correct to me.

I was wondering whether `tmpfs` according to docker might just mean "ephemeral" (but still disk-based), but it appears that it it **is** both ephemeral and ramdisk based as per the underlying filesystem `tmpfs`.

I will run the CI on my own self-hosted runner, and see what sort of numbers I  get from it...

**Pull request closed without merging**
