### PR TITLE
Torv2 removal followups

### PR DESCRIPTION
**Pull request by vasild**
* Simplify some code, now that we know `CNetAddr::IsRFC4193()` and `CNetAddr::IsTor()` cannot be `true` at the same time.
* Drop Tor v2 addresses when loading addrman from `peers.dat` - they would have been loaded as dummy-all-zeros IPv6 addresses and linger in addrman, wasting space.

### CODE REVIEW

**Comment by vasild** [comment]
cc @jonatack

**Comment by jonatack** [comment]
Thanks! Will have a look after tomorrow (Chaincode seminar, Optech writing and work interviews today and tomorrow).

**Comment by jonatack** [comment]
Concept ACK

**Comment by vasild** [comment]
`26227ae770...00b875ba94`: fix test mishap

**Comment by laanwj** [comment]
Concept ACK

> they would have been loaded as dummy-all-zeros IPv6 addresses and linger in addrman, wasting space.

Good catch.

**Comment by sipa** [comment]
ACK 00b875ba9414463d0041da6924fd9b54d6a06dee. Reviewed the code, and tested with -DDEBUG_ADDRMAN (unit tests + mainnet run with peers.dat that contained v2 onions).

**Review by jonatack — COMMENTED** [review]
ACK 00b875ba9414463d0041da6924fd9b54d6a06dee reviewed, debug-built with -DEBUG_ADDRMAN rebased to current master, restarted node on mainnet/signet/testnet and verified that on each chain -addrinfo shows no change in address counts (as expected). Added some sanity check asserts, rebuilt/re-ran test. Checked that the new test fails on master with "test/addrman_tests.cpp(824): error: in "addrman_tests/remove_invalid": check addrman.size() == 2 has failed [4 != 2]"

**Comment by naumenkogs** [comment]
Concept ACK.

**Comment by 0xB10C** [comment]
Concept ACK

**Review by jarolrod — COMMENTED** [review]
ACK 00b875ba9414463d0041da6924fd9b54d6a06dee

Cherry-picked each commit on top of master, and test compile + run unit tests. Tested on Linux and macOS connected through tor.

### Notes on commits

- [x] a164cd3ba694ffeba03b2887a411b7f82f6c087e
  - checking for `!isTor()` is in fact redundant as `IsRFC4193` calls `IsIPV6`. Since we've already determined that `m_net` is `NET_IPV6`, it is redundant to then check that it is not `NET_ONION`
- [x] bdb62096f0109b2ec76849d33d6cf7187dea299f
  - makes sense to remove this here 🥃 
  - code review ack only, did not fuzz
- [x] 00b875ba9414463d0041da6924fd9b54d6a06dee
  - Code Review ACK
  - copied and pasted the test added here in `addrman_tests.cpp` onto master and confirm that the test would fail
    - ```
       test/addrman_tests.cpp(824): error: in "addrman_tests/remove_invalid": check addrman.size() == 2 has failed [4 != 2]
      ```

**Comment by laanwj** [comment]
Code review and lightly tested ACK 00b875ba9414463d0041da6924fd9b54d6a06dee

**Pull request merged**
