### PR TITLE
Implement memory locks on passphrase input

### PR DESCRIPTION
**Pull request by micrictor**
As requested in comments, lock the memory used to store the encryption passphrases.

### CODE REVIEW

**Comment by sipa** [comment]
This won't work. It locks the string object itself, not the (separately
allocated) memory area where the string's contents is stored.

You need a string with a custom allocator to solve this.

**Comment by laanwj** [comment]
The problem is, I don't think Qt supports strings with custom allocators. And if want to use your own string type, at the very least you'd need to implement a custom text field to make use of it. There's no saying what QLineEdit, or at a lower level, X, does internally. It may scatter buffers with (part of) the passphrase everywhere in the heap.

A possible suggestion (I think by @gmaxwell) was for a "secure entry" sandbox, e.g. launching a new process that runs fully memory-locked that captures the passphrase and does the private key handling and signing so that nothing sensitive has to leave the process. This would also allow utilizing special OS support for process isolation.

**Comment by jonasschnelli** [comment]
Just checked and found out that QT does not support custom or secure allocators. It would required to dig down the whole path to the OS implementation (for the three supported platforms) which would be hard to implement and very hard to maintain (not only that it runs also that it is secure).

The separated secure entry process would make more sense but even there its not trivial to implement.

Maybe wallet encryption should go more into a direction of easy-multisig-usage or other concepts of store partial data in a "cold-space".

**Comment by laanwj** [comment]
Closing this, as-is it won't noticeably improve security and thus doesn't warrant removing the comments.

**Comment by micrictor** [comment]
Looking deeper, it seems that if you lock the return of the data accessor(
ui->passEdit1->text().data() ) it properly locks the area of memory being
used to store the actual data. I verified this in GDB.

I also changed the locking done for RPC calls so it locks the proper
memory, again verified in GDB.

Just checked and found out that QT does not support custom or secure
allocators. It would required to dig down the whole path to the OS
implementation (for the three supported platforms) which would be hard to
implement and very hard to maintain (not only that it runs also that it is
secure).

The separated secure entry process would make more sense but even there its
not trivial to implement.

Maybe wallet encryption should go more into a direction of
easy-multisig-usage or other concepts of store partial data in a
"cold-space".

—
Reply to this email directly or view it on GitHub
<https://github.com/bitcoin/bitcoin/pull/6019#issuecomment-93672794>.

**Pull request closed without merging**
