### PR TITLE
release: Update translations for v28.0 soft translation string freeze

### PR DESCRIPTION
**Pull request by hebasto**
This PR follows our [Release Process](https://github.com/bitcoin/bitcoin/blob/4c62f4b53561bce5b2eb8639cdc24d284be537eb/doc/release-process.md).

Note: (possible) vandalism/damage has been prevented by reverting the deletion of `bitcoin_af`, `bitcoin_es_MX`, and `bitcoin_ru` translations.

Required to open Transifex translations for v28.0 as it's scheduled in https://github.com/bitcoin/bitcoin/issues/29891.

The previous similar PR: https://github.com/bitcoin/bitcoin/pull/29397.

### CODE REVIEW

**Comment by hebasto** [comment]
cc @stickies-v @pablomartin4btc @johnny9

**Review by stickies-v — APPROVED** [review]
ACK be419674da66e9c349c9c35246c20a7b9fda2dd0

It seems you've made some manual adjustments that might be worth documenting in the PR description? Specifically, I've noticed:
1. you've prevented (what appears to be) vandalism by reverting the deletion of `bitcoin_af`, `bitcoin_es_MX`, and `bitcoin_ru` translations
2. you've rolled back some clearly not Swedish translations in `bitcoin_sv`:

<details>

```diff
diff --git a/src/qt/locale/bitcoin_sv.ts b/src/qt/locale/bitcoin_sv.ts
index 618a3acbb0..e80f0b6380 100644
--- a/src/qt/locale/bitcoin_sv.ts
+++ b/src/qt/locale/bitcoin_sv.ts
@@ -341,36 +341,36 @@ Försök igen.</translation>
     <message numerus="yes">
         <source>%n second(s)</source>
         <translation type="unfinished">
-            <numerusform />
-            <numerusform />
+            <numerusform>%n second(s)</numerusform>
+            <numerusform>%n second(s)</numerusform>
         </translation>
     </message>
     <message numerus="yes">
         <source>%n minute(s)</source>
         <translation type="unfinished">
-            <numerusform />
-            <numerusform />
+            <numerusform>%n minute(s)</numerusform>
+            <numerusform>%n minute(s)</numerusform>
         </translation>
     </message>
     <message numerus="yes">
         <source>%n hour(s)</source>
         <translation type="unfinished">
-            <numerusform />
-            <numerusform />
+            <numerusform>%n hour(s)</numerusform>
+            <numerusform>%n hour(s)</numerusform>
         </translation>
     </message>
     <message numerus="yes">
         <source>%n day(s)</source>
         <translation type="unfinished">
-            <numerusform />
-            <numerusform />
+            <numerusform>%n day(s)</numerusform>
+            <numerusform>%n day(s)</numerusform>
         </translation>
     </message>
     <message numerus="yes">
         <source>%n week(s)</source>
         <translation type="unfinished">
-            <numerusform />
-            <numerusform />
+            <numerusform>%n week(s)</numerusform>
+            <numerusform>%n week(s)</numerusform>
         </translation>
     </message>
     <message>
@@ -380,8 +380,8 @@ Försök igen.</translation>
     <message numerus="yes">
         <source>%n year(s)</source>
         <translation type="unfinished">
-            <numerusform />
-            <numerusform />
+            <numerusform>%n year(s)</numerusform>
+            <numerusform>%n year(s)</numerusform>
         </translation>
     </message>
     </context>
@@ -2840,8 +2840,8 @@ Om den här plånboken innehåller lösbara</translation>
     <message numerus="yes">
         <source>Estimated to begin confirmation within %n block(s).</source>
         <translation type="unfinished">
-            <numerusform />
-            <numerusform />
+            <numerusform>Estimated to begin confirmation within %n block(s).</numerusform>
+            <numerusform>Estimated to begin confirmation within %n block(s).</numerusform>
         </translation>
     </message>
     <message>
@@ -3150,8 +3150,8 @@ Om den här plånboken innehåller lösbara</translation>
     <message numerus="yes">
         <source>matures in %n more block(s)</source>
         <translation type="unfinished">
-            <numerusform />
-            <numerusform />
+            <numerusform>matures in %n more block(s)</numerusform>
+            <numerusform>matures in %n more block(s)</numerusform>
         </translation>
     </message>
     <message>

```
</details>

Besides the diff outlined above, I'm getting the same output:

```
../bitcoin-maintainer-tools/update-translations.py
./configure && make -C src translate
```

Note:
- `bitcoin_az`, `bitcoin_az@latin`, `bitcoin_la` seems to have a bunch of new English translations in it too

**Comment by hebasto** [comment]
>    1. you've prevented (what appears to be) vandalism by reverting the deletion of `bitcoin_af`, `bitcoin_es_MX`, and `bitcoin_ru` translations

It is mentioned in the commit message as "Removals of translation files have been discarded.".

I'll put your wording in the PR description.

**Comment by hebasto** [comment]
>    2. you've rolled back some clearly not Swedish translations in `bitcoin_sv`:

I haven't. Those translations were updated by translators after I pulled the translations from the Transifex:
image

It's a moving a target, and we did our best in this PR.

**Review by pablomartin4btc — COMMENTED** [review]
post-merge ACK be419674da66e9c349c9c35246c20a7b9fda2dd0

no diff

**Review by SamyDgz — APPROVED** [review]

**Pull request merged**
