### PR TITLE
export der always compressed

### PR DESCRIPTION
**Pull request by fingera**

### CODE REVIEW

**Comment by laanwj** [comment]
Please add rationale to your OP, why is this change?
Also please add a least a test for the new behavior

**Review by randolf — CHANGES_REQUESTED** [review]
Please update the description of what this PR does (at present there is no description).  Thank you.

**Comment by fingera** [comment]
CKey key
key1.MakeNewKey(false)
CPrivKey priv = key.GetPrivate()
priv is compressed,
i will adding test case

**Comment by laanwj** [comment]
Closing, as the goal here has not been explained

**Comment by fingera** [comment]
it is a bug for  ec_privkey_export_der

**Comment by fingera** [comment]
Is it changing ec_privkey_export_der? Delete another branch that will never be reached

**Comment by fingera** [comment]
#14195

**Pull request closed without merging**
