### PR TITLE
contrib: Remove keys that are no longer used for merging

### PR DESCRIPTION
**Pull request by hebasto**
See:
- https://bitcoin-irc.chaincode.com/bitcoin-core-dev/2021-10-21#726591
- https://bitcoin-irc.chaincode.com/bitcoin-core-dev/2021-12-09#750000

Also updated `trusted-git-root` to be right after **meshcollider**'s last merge.

The latest similar change was bitcoin/bitcoin#7713.

A related discussion on [IRC](https://bitcoin-irc.chaincode.com/bitcoin-core-dev/2021-10-22#727090):
> [12:28](https://bitcoin-irc.chaincode.com/bitcoin-core-dev/2021-10-22#727090) \<MarcoFalke> jonasschnelli: I was about to ask you whether you planned to remove your fingerprint from the "trusted-keys" for merging, but it looks like this will break verify-commits ...
> [12:31](https://bitcoin-irc.chaincode.com/bitcoin-core-dev/2021-10-22#727091) \<laanwj> you would also have a add all his merge commits to exceptions, i guess
> [12:32](https://bitcoin-irc.chaincode.com/bitcoin-core-dev/2021-10-22#727092) \<laanwj> or patch the script to allow different key for different ranges of commits
> [13:15](https://bitcoin-irc.chaincode.com/bitcoin-core-dev/2021-10-22#727118) \<jonasschnelli> MarcoFalke: I had no plan to remove my keyid,… would that make sense and how would you fix verify commits?
> [13:16](https://bitcoin-irc.chaincode.com/bitcoin-core-dev/2021-10-22#727119) \<jonasschnelli> Ideally, we should set en expiration date next to those keyid

### CODE REVIEW

**Review by laanwj — APPROVED** [review]
Changes LGTM, however when running locally I run into this verification issue:
```
bitcoin$ contrib/verify-commits/verify-commits.py
Using verify-commits data from …

No parent of e658b0e49bee257e197dd8ca37ee3ffa73092d92 was signed with a trusted key!
Parents are:
commit 19e3e654293858141f39eef8fdae0badd224090f
Merge: 9b48b3ac42294410cb56e7da24a261fa69ddb503 915e34112b5a4c2ef391d7e3706603bcd6f62a2a
Author: MarcoFalke <falke.marco@gmail.com>
Date:   Fri Mar 26 17:30:18 2021 +0100
```
This seems to be an old expired key of Marco Falke (60B0B8A402FB386B24A039ACD2EA4850E7528B25). I don't think it's caused by this change.

**Comment by fanquake** [comment]
Concept ACK

**Comment by MarcoFalke** [comment]
Commit 19e3e654293858141f39eef8fdae0badd224090f should be buried far under the trusted root 577bd51a4b8de066466a445192c1c653872657e2, so I don't see how it could be considered even or cause a failure.

**Comment by laanwj** [comment]
> Commit https://github.com/bitcoin/bitcoin/commit/19e3e654293858141f39eef8fdae0badd224090f should be buried far under the trusted root https://github.com/bitcoin/bitcoin/commit/577bd51a4b8de066466a445192c1c653872657e2, so I don't see how it could be considered even or cause a failure.

Apparently I don't know how to use the script, then.

**Comment by laanwj** [comment]
I just retried, it works now:
```sh
$ git fetch upstream pull/25197/head
From github.com:bitcoin/bitcoin
 * branch                                                                              refs/pull/25197/head -> FETCH_HEAD
$ git checkout FETCH_HEAD
Note: switching to 'FETCH_HEAD'.
…
HEAD is now at d4b3dc5b0a726cc4cc7a8467be43126e78f841cf contrib: Remove keys that are no longer used for merging
$ git reset --soft HEAD~1  # get rid of unsigned top-level commit, but keep changes in local tree
$ contrib/verify-commits/verify-commits.py
Using verify-commits data from /store/orion/projects/bitcoin/bitcoin/contrib/verify-commits
There is a valid path from "HEAD" to 577bd51a4b8de066466a445192c1c653872657e2 where all commits are signed!
```

ACK d4b3dc5b0a726cc4cc7a8467be43126e78f841cf

**Pull request merged**
