### PR TITLE
readability improvement

### PR DESCRIPTION
**Pull request by smatthewenglish**

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Changing old release notes makes no sense IMO and stuff like this leads to "pull-request-overview pollution".

**Comment by MarcoFalke** [comment]
Sometimes we change release notes when an issue is discovered shortly after release, but I don't think fixing *0.4.0* release notes helps anyone.

**Comment by laanwj** [comment]
Yes, 0.4.0 is ancient. Let's not mess with historical documents like this...

**Comment by MarcoFalke** [comment]
@s-matthew-english If you are looking for small things to help out with, you can

* search through the [easy to implement](https://github.com/bitcoin/bitcoin/issues?q=is%3Aissue+is%3Aopen+label%3A%22Easy+to+implement%22) issues.
* write tests to improve the coverage (both unit tests and rpc tests are welcome)
* help with review and testing (There are easy ones such as the [gui](https://github.com/bitcoin/bitcoin/pulls?q=is%3Apr+is%3Aopen+label%3AGUI) and [rpc](https://github.com/bitcoin/bitcoin/pulls?q=is%3Apr+is%3Aopen+label%3ARPC%2FREST%2FZMQ))
* join us on irc and let us know what you are interested in.

**Comment by s-matthew-english** [comment]
@jonasschnelli ah, please forgive me I wasn't trying to pollute the pull-request-overview. my idea was that, if I'm trying to understand some else's code I guess I would read through the release history and all the comments first. I won't submit pull-requests about old release notes anymore

@laanwj @MarcoFalke thank you! for sure I'll check those out

do you guys know a good resource on C++ that I could investigate?

**Comment by s-matthew-english** [comment]
:/ I checked out the gui and rpc issues, I feel like I don't understand the code well enough yet to contribute in a good way there.

my idea was to bootstrap my knowledge of the code, and my ability to work with git by reading through the comments and initially just making some small improvements, do you think, if I avoided the old release notes, that it could be something useful? the last thing I would want to do is to make a nuisance of myself

**Comment by laanwj** [comment]
@s-matthew-english 
As you seem documentation-focused I'll give some examples related to that. I'd recommend focusing on user-facing things, not developer-facing things such as code comments (unless they're terribly wrong; a typo in a comment is meh). But anything user-facing is bound to have much more impact.

For example, RPC help messages. The RPC help messages are part of the code, but in principle are just hard-coded text in the cpp files in `src/rpc/*.cpp` and `src/wallet/rpcwallet.cpp`, e.g.:
-  a simple one, `getblockcount` https://github.com/bitcoin/bitcoin/blob/master/src/rpc/blockchain.cpp#L153
-  a more extended one,`getblockheader` https://github.com/bitcoin/bitcoin/blob/master/src/rpc/blockchain.cpp#L634

I'm sure there are plenty of mistakes, both in language, and correctness of types/descriptions there, as well as things that could use clarification. And it would be very useful to improve them as they are a frequently used resource. 

Other documents that are essential are e.g.:

- [Using bitcoin with Tor](https://github.com/bitcoin/bitcoin/blob/master/doc/tor.md)
- [UNIX build guide](https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md)
- [Gitian deterministic building](https://github.com/bitcoin/bitcoin/blob/master/doc/gitian-building.md)

In the GUI code (src/qt) are also plenty of user-facing dialogs and strings.

**Pull request closed without merging**
