### PR TITLE
Add some script tests

### PR DESCRIPTION
**Pull request by richardkiss**
Add some script tests related to BOOL ops and odd values like negative 0.

### CODE REVIEW

**Comment by randolf** [comment]
Why is it necessary to check for negative 0?

**Comment by laanwj** [comment]
utACK, thanks for adding tests!

> Why is it necessary to check for negative 0?

Because the point of these tests is to cover as many as possible inputs, including weird/unexpected encodings of values.

**Comment by richardkiss** [comment]
I thought I'd found some mismatches between bitcoind's consensus mechanims and pycoin's, so I wrote these tests to check. Turns out pycoin was working properly, but I thought I'd submit the tests anyway.

**Comment by randolf** [comment]
@laanwj Okay, that answers my question and it makes sense.  Thank you.

**Review by randolf — APPROVED** [review]

**Pull request merged**
