### PR TITLE
RPC: add weight to mempool entry output

### PR DESCRIPTION
**Pull request by luke-jr**
Rebased and fixed outstanding issues in #11256

Also removed some unnecessary refactoring to simplify review

### CODE REVIEW

**Comment by MeshCollider** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/14649/commits/092defc216c9fe2a6d32bd670a5f5215c143a48c

**Comment by promag** [comment]
utACK 092defc. Could have release note.

**Comment by conscott** [comment]
Tested ACK 092defc216c9fe2a6d32bd670a5f5215c143a48c

**Review by promag — COMMENTED** [review]
@luke-jr the following also get `weight` key in the result:
 - `getrawmempool`, `getmempoolancestors` and `getmempooldescendants` with `verbose=true`
 -  `/rest/mempool/contents.json`.

Do you mind adding tests for those (at least test it's numeric) and add release notes?

**Comment by fanquake** [comment]
Given this had utACKs, @luke-jr would you like to rebase and add some release notes.

**Comment by fanquake** [comment]
I've rebased and added release-notes in #16647.

**Pull request closed without merging**
