### PR TITLE
util: Implement boolean conversion and !operator for uint*

### PR DESCRIPTION
**Pull request by qmma70**
_First time contributor_

1. Implement boolean conversion and `operator!()` for uint160/uint256 to be consistent with https://github.com/bitcoin/bitcoin/blob/master/src/arith_uint256.h#L67

2. Implement boolean conversion operator for `arith_uint256`

3. Add unit tests for (1) and (2)

### CODE REVIEW

**Comment by Empact** [comment]
Prefer removing this as per #13388.

**Comment by qmma70** [comment]
The operators are good to haves IMO. 

But I'll close this one after #13396 is merged.

**Comment by skeees** [comment]
I'm a concept ACK on rationalizing the apis, note that there's code overlap with uint256::IsNull() so consider having one call the other

**Comment by laanwj** [comment]
I'm not sure it makes sense to add more unused methods. Also looks like this makes a lot of changes not directly related to the topic, please try to avoid that.

**Comment by laanwj** [comment]
Closing because #13396 merged

**Pull request closed without merging**
