### PR TITLE
doc/bips: Document BIP 125 support

### PR DESCRIPTION
**Pull request by luke-jr**
(Clean merge into master and 0.12)

### CODE REVIEW

**Comment by MarcoFalke** [comment]
ACK d570a1f

**Comment by petertodd** [comment]
ACK https://github.com/luke-jr/bitcoin/commit/d570a1f41b9eef60db441be0eb26c9f5020e3c6a

**Comment by dcousens** [comment]
ACK @ d570a1f

**Comment by jonasschnelli** [comment]
ACK d570a1f41b9eef60db441be0eb26c9f5020e3c6a

**Comment by fanquake** [comment]
ACK https://github.com/luke-jr/bitcoin/commit/d570a1f41b9eef60db441be0eb26c9f5020e3c6a

**Comment by laanwj** [comment]
Merged into master and 0.12

**Pull request merged**
