### PR TITLE
tests: Possible fix the permission error when the tests open the cookie file

### PR DESCRIPTION
**Pull request by ken2812221**
This PR would wait until the `.cookie` file is readable
Possible fix no. 5 `PermissionError` in #14446

### CODE REVIEW

**Comment by MarcoFalke** [comment]
utACK 0cb4518d355738b2530a66cded2fc4b673ba1c2a

**Comment by laanwj** [comment]
There's so much polling and waiting in the tests; from a determinism point of view I'd prefer to do this waiting *once* after starting a node, this is the only time where one'd expect the cookie to not be there yet.

(If the same happens and it's trying to find the cookie *after shutdown* this is a problem with the test and it shouldn't simply wait 10 seconds. Or if the cookie goes missing while a node is supposed to be running this is a problem with the software that should be detected immediately.)

**Comment by promag** [comment]
Another error https://ci.appveyor.com/project/DrahtBot/bitcoin/builds/20508203.

**Comment by ken2812221** [comment]
@laanwj Now it would also raise ValueError if the cookie file is not readable

**Comment by MarcoFalke** [comment]
utACK d6b3790d1a41030f4ac83556fdbe9f019b9b4e59

**Pull request merged**
