### PR TITLE
tests: Add test for 64-bit Windows PE, modify 32-bit test results

### PR DESCRIPTION
**Pull request by ken2812221**
9a75d29b6f0d6c4834e451b0fae2200786655a35 change the error result from `PIE` to `DYNAMIC_BASE`. And there are no test for 64-bit, so I made one

### CODE REVIEW

**Comment by laanwj** [comment]
travis complains about whitespace
```
This diff appears to have added new lines with trailing whitespace.
The following changes were suspected:
diff --git a/contrib/devtools/test-security-check.py b/contrib/devtools/test-security-check.py
@@ -57,0 +58,14 @@ class TestSecurityChecks(unittest.TestCase):
+        self.assertEqual(call_security_check(cc, source, executable, []),
+        self.assertEqual(call_security_check(cc, source, executable, ['-Wl,--nxcompat']),
+        self.assertEqual(call_security_check(cc, source, executable, ['-Wl,--nxcompat','-Wl,--dynamicbase']),
+        self.assertEqual(call_security_check(cc, source, executable, ['-Wl,--nxcompat','-Wl,--dynamicbase','-Wl,--high-entropy-va']),
^---- failure generated from contrib/devtools/lint-whitespace.sh
```

**Comment by ken2812221** [comment]
@laanwj I just follow the original format of this file, so should I change this?

**Comment by laanwj** [comment]
Looks good to me.
@theuni can you take a look as well just in case?

**Comment by theuni** [comment]
Sorry for missing this one. Post-merge utACK.

**Pull request merged**
