### PR TITLE
[build-aux] Update Boost & check macros to latest serials

### PR DESCRIPTION
**Pull request by fanquake**

### CODE REVIEW

**Comment by jonasschnelli** [comment]
LGTM.
ping @theuni

**Comment by theuni** [comment]
@fanquake: Looks like this drops our libsubdirs boost patch (which I thought made it upstream). Was that intentional?

**Comment by fanquake** [comment]
@theuni no, my mistake. The only patch of yours I can see being merged into Boost base was in [serial 22](http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=commitdiff;h=cba04c6644ef75f6f0eb7ac67db90d2533d80f0c).

This patch, hasn't yet made it upstream
```
    dnl some arches may advertise a cpu type that doesn't line up with their
    dnl prefix's cpu type. For example, uname may report armv7l while libs are
    dnl installed to /usr/lib/arm-linux-gnueabihf. Try getting the compiler's
    dnl value for an extra chance of finding the correct path.
    libsubdirs="lib/`$CXX -dumpmachine 2>/dev/null` $libsubdirs"
```

I've amended the changes.

**Comment by laanwj** [comment]
Is this ready for merge? (e.g. all patches are included now?)

**Comment by paveljanik** [comment]
Fixes #5516.

`configure` output differences here (OS X: master->#7711):

Expected:

```
-checking if compiler needs -Werror to reject unknown flags... yes
-checking whether pthreads work with -pthread... yes
+checking whether gcc is Clang... yes
+checking whether Clang needs flag to prevent "argument unused" warning when linking with -pthread... -Qunused-arguments
```

Unexpected:

```
-checking for __attribute__((visibility))... yes
+checking for __attribute__((visibility))... no
```

ACK https://github.com/bitcoin/bitcoin/pull/7711/commits/cf5c786fc3244b6aedcc4a2f839f5248f95fafa1

**Comment by theuni** [comment]
Mm, I missed this before merge.

@paveljanik to clarify, are you saying that after this change, the visibility attribute isn't found? If so, that'll be quite ugly at link time. I would think it would cause a flood of "visibility doesn't match" warnings.

**Comment by paveljanik** [comment]
No such warnings here...

**Comment by paveljanik** [comment]
config.log here:

```
configure:20859: checking for __attribute__((visibility))
configure:20883: g++ -o conftest -g -O2 -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -Wno-self-assign  -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -isystem /opt/local/include -I/opt/local/include/db48 -DMAC_OSX  -Wl,-headerpad_max_install_names conftest.cpp  -L/opt/local/lib -L/opt/local/lib/db48 >&5
conftest.cpp:30:56: warning: target does not support 'protected' visibility; using 'default' [-Wunsupported-visibility]
                    int foo_pro( void ) __attribute__((visibility("protected")));
                                                       ^
1 warning generated.
configure:20883: $? = 0
configure:20896: result: no
```

**Comment by laanwj** [comment]
Must be due to this change:
```diff
                 [visibility], [
                      int foo_def( void ) __attribute__(($1("default")));
                      int foo_hid( void ) __attribute__(($1("hidden")));
 +                    int foo_int( void ) __attribute__(($1("internal")));
 +                    int foo_pro( void ) __attribute__(($1("protected")));
                  ],
```
Apparently it needs *all kinds of* visibility to be supported for that check.

Still fine on ubuntu 14.04:
```
configure:20274: checking for __attribute__((visibility))
configure:20298: g++ -o conftest -g -O2 -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -Wno-self-assign  -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS  conftest.cpp  >&5
configure:20298: $? = 0
configure:20311: result: yes
```

**Pull request merged**
