### PR TITLE
ci: Enable D_GLIBCXX_DEBUG for multiprocess task

### PR DESCRIPTION
**Pull request by maflcko**
Enable `-D_GLIBCXX_DEBUG` via the depends `DEBUG` flag. Also `--enable-debug` to get debug symbols in traces.

### CODE REVIEW

**Comment by hebasto** [comment]
https://cirrus-ci.com/task/5754102559801344 -- OOM

**Comment by fanquake** [comment]
Note that `DEBUG=1` is also set for depends in the [previous releases job](https://github.com/bitcoin/bitcoin/blob/bb11a988fa52a081e29441209cd19900bc9c2c80/ci/test/00_setup_env_native_qt5.sh#L12). Could add `DEBUG` to that description as part of this PR.

**Comment by MarcoFalke** [comment]
Thanks, will do

**Comment by MarcoFalke** [comment]
Closing because I wasn't aware this is already tested by another task

**Comment by MarcoFalke** [comment]
Reopening because the other one is using gcc and this one is using clang

**Comment by MarcoFalke** [comment]
Ok, addressed all feedback

**Comment by practicalswift** [comment]
Concept ACK

**Review by hebasto — APPROVED** [review]
ACK fa44f5119a0b412f0d46cad02f638727d140b451, I have reviewed the code and it looks OK, I agree it can be merged, and CI is green.

**Review by iadeelzafar — APPROVED** [review]

**Pull request merged**
