### PR TITLE
travis: Full clone for git subtree check

### PR DESCRIPTION
**Pull request by maflcko**
Lazy workaround and fix for #12388

### CODE REVIEW

**Comment by laanwj** [comment]
I disagree with this solution in the long run, but I'm going to cherry-pick this to the 0.16 branch to make travis pass there again.

**Comment by MarcoFalke** [comment]
I think it is a waste of time to micro-optimize travis solely for a questionable speedup. Note that the remote could be the bottleneck as well while counting and compressing the git objects. The runtime that travis reports for this commit/pull is `10.93s` whereas on current master it is `12.95s`.

**Comment by MarcoFalke** [comment]
Anything holding this back?

**Comment by MeshCollider** [comment]
Post merge utACK https://github.com/bitcoin/bitcoin/commit/fa44af5cd2152a21da9ef3e48c073a668bf2df27

**Pull request merged**
