### PR TITLE
util: Use steady clock instead of system clock to measure durations

### PR DESCRIPTION
**Pull request by maflcko**
`GetTimeMillis` has multiple issues:

* It doesn't denote the underlying clock type
* It isn't type-safe
* It is used incorrectly in places that should use a steady clock

Fix all issues here.

### CODE REVIEW

**Comment by dergoegge** [comment]
Concept ACK

**Review by martinus — COMMENTED** [review]
Concept ACK

**Comment by willcl-ark** [comment]
ACK fa83fb3161

This is a nice cleanup to the clocks.

There are a few time values left as other types in the codebase, but it doesn't make sense to change them as they are being used as those types by other components (mainly libevent it seems).

**Comment by RandyMcMillan** [comment]
Concept ACK

**Comment by martinus** [comment]
Code review ACK fa83fb3, also ran all tests. All usages of the steady_clock are just for duration measurements, so the change to a different epoch is ok.

**Review by martinus — APPROVED** [review]
Code review ACK https://github.com/bitcoin/bitcoin/commit/fa83fb31619c19a1a30b4181486601a944941b16, also ran all tests. All usages of the steady_clock are just for duration measurements, so the change to a different epoch is ok.

**Pull request merged**
