### PR TITLE
Send fewer feefilter messages (and avoid the wobbling issue)

### LINKED ISSUE #21635: feefilter messages being sent too often
I have noticed (after adding a debug line) that feefilter messages are being sent more than once to a peer even if the MinRelayFee has not changed:-

> 2021-04-08T15:24:47.454 send feefilter 5959 (actual: 6006) peer=33
> 2021-04-08T15:25:03.770 send feefilter 6554 (actual: 6006) peer=34
> 2021-04-08T15:26:30.933 UpdateTip: new best=0000000000000000000b2b33e937dfaf38000d52ecd2d5d3620838cb37288c6d height=678337 version=0x3fffe000 log2_work=92.795673 tx=632211134 date='2021-04-08T15:26:09Z' progress=1.000000 cache=18.9MiB(140609txo)
> 2021-04-08T15:27:37.803 send feefilter 6554 (actual: 6006) peer=33

I would have thought a feefilter message should only be sent if there has been a change since the last message was sent.

### PR DESCRIPTION
**Pull request by rebroad**
Fixes #21635

### CODE REVIEW

**Comment by MarcoFalke** [comment]
-0. There are at most 6 feefilter expected to be sent per hour. In practice it should be less due to rounding. No need to micro-optimize the bandwidth here.

**Comment by rebroad** [comment]
> -0. There are at most 6 feefilter expected to be sent per hour. In practice it should be less due to rounding. No need to micro-optimize the bandwidth here.

Hi, no, actually the rounding causes it to send them more often as the number "wobbles" above and below the actual. Please see the attached log. The wobbling happens most often when the actual isn't moving much:- 

> 2021-04-30T05:59:05.941 send feefilter WOBBLE 2297 (actual: 2346) peer=110
> 2021-04-30T06:02:07.715 send feefilter WOBBLE 2297 (actual: 2346) peer=56
> 2021-04-30T06:03:33.621 send feefilter WOBBLE 2527 (actual: 2346) peer=110
> 2021-04-30T06:08:49.501 send feefilter WOBBLE 2297 (actual: 2346) peer=98
> 2021-04-30T06:09:21.618 send feefilter WOBBLE 2527 (actual: 2346) peer=76
> 2021-04-30T06:10:31.663 send feefilter WOBBLE 2527 (actual: 2346) peer=88
> 2021-04-30T06:11:43.064 send feefilter WOBBLE 2297 (actual: 2346) peer=88
> 2021-04-30T06:14:01.180 send feefilter WOBBLE 2297 (actual: 2346) peer=81
> 2021-04-30T06:15:41.912 send feefilter WOBBLE 2297 (actual: 2346) peer=110
> 2021-04-30T06:16:39.465 send feefilter WOBBLE 2297 (actual: 2346) peer=76
> 2021-04-30T06:18:14.436 send feefilter WOBBLE 2527 (actual: 2346) peer=87
> 2021-04-30T06:21:56.656 send feefilter WOBBLE 2527 (actual: 2346) peer=81
> 2021-04-30T06:22:31.126 send feefilter 2297 (actual: 2346) peer=114
> 2021-04-30T06:25:48.578 send feefilter WOBBLE 2297 (actual: 2346) peer=87
> 2021-04-30T06:26:08.049 send feefilter WOBBLE 2527 (actual: 2346) peer=88
> 2021-04-30T06:30:05.929 send feefilter WOBBLE 2527 (actual: 2346) peer=78
> 2021-04-30T06:31:18.270 send feefilter WOBBLE 2527 (actual: 2346) peer=98
> 2021-04-30T06:32:56.377 send feefilter WOBBLE 2297 (actual: 2346) peer=78

I'll edit this comment in a moment to refer to the code I'm using, but the WOBBLE lines are essentially the existing logic, and the non-WOBBLE lines are the new logic.

**Comment by rebroad** [comment]
@MarcoFalke another fix would be to change the rounding function so that it only ever goes in one direction (rather than in two directions as it currently does).

**Comment by MarcoFalke** [comment]
The excerpt shows 30 minutes and each connection is sent about 2 feefilters. (3 are expected)

**Comment by rebroad** [comment]
> The excerpt shows 30 minutes and each connection is sent about 2 feefilters. (3 are expected)

I'm not sure what point you're trying to make. My point is that the round function is supposed to provide some privacy, and it's failing to do that, and it's also causing unnecessary traffic to be generated. Surely this is worth fixing for both reasons.

**Comment by MarcoFalke** [comment]
> causing unnecessary traffic

You will need to provide benchmarks to support this claim. A single inv message with just one tx entry is larger than the feefilter message.

**Comment by MarcoFalke** [comment]
Closing for now because for the same reason: https://github.com/bitcoin/bitcoin/issues/21635#issuecomment-830591541

Also all the tests are failing.

In the future it might be good if you ran the tests locally before proposing a change for review.

**Comment by rebroad** [comment]
> > causing unnecessary traffic
> 
> You will need to provide benchmarks to support this claim. A single inv message with just one tx entry is larger than the feefilter message.

this can be derived by logical deduction simply by looking at the debug.log

**Comment by MarcoFalke** [comment]
I understand that logically this reduces the traffic. However, in practice the savings should be less than the rounding errors you encounter while trying to measure.

**Pull request closed without merging**
