### PR TITLE
scripted-diff: Use the C++11 keyword nullptr to denote the pointer literal instead of the macro NULL

### PR DESCRIPTION
**Pull request by practicalswift**
Since C++11 the macro `NULL` may be:
* an integer literal with value zero, or
* a prvalue of type `std::nullptr_t`

By using the C++11 keyword `nullptr` we are guaranteed a prvalue of type `std::nullptr_t`.

For a more thorough discussion, see "A name for the null pointer: nullptr" (Sutter &
Stroustrup), http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2007/n2431.pdf

With this patch applied there are no `NULL` macro usages left in the repo:

```
$ git grep NULL -- "*.cpp" "*.h" | egrep -v '(/univalue/|/secp256k1/|/leveldb/|_NULL|NULLDUMMY|torcontrol.*NULL|NULL cert)' | wc -l
0
```

The road towards `nullptr` (C++11) is split into two PRs:
* `NULL` → `nullptr` is handled in PR #10483 (scripted, this PR)
* `0` → `nullptr` is handled in PR #10645 (manual)

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Concept ACK

**Review by dcousens — APPROVED** [review]
utACK

**Comment by laanwj** [comment]
Concept ACK. I think we can all agree that this needs to be done at some point, though we'll have to discuss when to do this with the least impact. This change probably means every single PR needs to be rebased.

**Comment by practicalswift** [comment]
Rebased!

**Comment by sipa** [comment]
Can you rewrite this as a series of scripted diffs (possibly mixed with a few manual commits to fix things up)? See #10189 #10193 #10502 #10321 for examples.

As for timing, possibly immediately after the feature freeze?

**Comment by practicalswift** [comment]
@sipa Great idea! Now re-implemented as a scripted-diff. Looks good? :-)

**Comment by sipa** [comment]
@practicalswift You can use `sed -i 's/\<NULL\>/nullptr/g'` for the main operation. `\<` and `\>` denote begin and end of word.

**Comment by practicalswift** [comment]
@sipa Good point! Now using `s/\<NULL\>/nullptr/g`. Looks good? :-)

**Comment by practicalswift** [comment]
Merge conflicts resolved!

**Comment by practicalswift** [comment]
What is the correct protocol to follow w.r.t. rebasing a large scripted-diff PR such as this one?

Should I rebase periodically myself to keep it mergeable, or should I wait until I'm asked to rebase prior to the suggested time for merge (@sipa suggested: "possibly immediately after the feature freeze").

**Comment by MarcoFalke** [comment]
@practicalswift It is sufficient to rebase only once. Please refer to https://github.com/bitcoin/bitcoin/issues/9961#issue-212976673 for the preliminary date of feature freeze.

**Comment by practicalswift** [comment]
@MarcoFalke Great! Thanks for clarifying!

**Comment by theuni** [comment]
Concept ACK. It'd be helpful to compare before/after binaries.

**Comment by jtimon** [comment]
utACK
But after revieweing the code, the script seems to be more complicated than it needs to be, wouldn't the following do the same?
```
sed -i 's/NULL/nullptr/g' ./src/*.h ./src/*.cpp ./src/*/*.h ./src/*/*.cpp ./src/*/*/*.h ./src/*/*/*.cpp ;
```

**Comment by practicalswift** [comment]
@jtimon Unfortunately that command is a bit too broad which leads to the following problems:
* It would match dependencies such as `src/leveldb/`, `src/secp256k1/`, `src/univalue/`, etc.
* It would match unrelated constants such as `TX_NULL_DATA`, `SCRIPT_VERIFY_NULLDUMMY`, `SCRIPT_VERIFY_NULLFAIL`, `bitcoinconsensus_SCRIPT_FLAGS_VERIFY_NULLDUMMY`, `SCRIPT_ERR_SIG_NULLDUMMY`, `SCRIPT_ERR_SIG_NULLFAIL`, etc.

**Comment by jtimon** [comment]
What about ?
```
sed -i 's/ NULL/ nullptr/g' ./src/*.h ./src/*.cpp ./src/*/*.h ./src/*/*.cpp ./src/*/*/*.h ./src/*/*/*.cpp ;
sed -i 's/ nullptr/ NULL/g' ./src/leveldb/*.*  ./src/secp256k1/.*.*;
```

Anyway, no big deal, probably not worth it to change it. I looked at the changes and they do what I expect.

**Comment by practicalswift** [comment]
@jtimon Unfortunately that one is too broad – it will replace `NULLDUMMY` with `nullptrDUMMY`, etc. `'s/\<NULL\>/nullptr/g'` is the narrowest replacement I can think of :-)

**Comment by jtimon** [comment]
No worries, what you have seems to work. Needs rebase.

**Comment by practicalswift** [comment]
Rebased! :-)

**Comment by practicalswift** [comment]
Rebased!

**Comment by TheBlueMatt** [comment]
utACK 2f2ac6fc76c966b6174d9df647648d0573d2ac41. I read through the diff but not thoroughly, the script looks good :).

**Comment by practicalswift** [comment]
Rebased! :-)

**Comment by jtimon** [comment]
Fast scroll-down re-review ACK.
Didn't checked the rebase.

**Comment by practicalswift** [comment]
Rebased! :-)

**Comment by promag** [comment]
utACK 2f2ac6f.

Nit, while rebasing, reword to something short, like `scripted-diff: Replace NULL macro with C++11 nullptr keyword`.

**Comment by sipa** [comment]
Let's try to merge this right before branching off 0.15.

**Comment by practicalswift** [comment]
Rebased!

@sipa That's great! When is that expected to happen? I'll keep this PR rebased :-)

**Comment by practicalswift** [comment]
What about merging the related PR #10645 ("Use nullptr (C++11) instead of zero (0) as the null pointer constant ") at the same time? :-)

**Comment by MarcoFalke** [comment]
90d4d89 conflicts with #10882, which is tagged for 0.15.

**Comment by practicalswift** [comment]
@laanwj Excellent! Thanks for merging! :-)

**Pull request merged**
