### PR TITLE
Net: Fix resource leak in ReadBinaryFile(...)

### PR DESCRIPTION
**Pull request by practicalswift**
Potential file descriptor leak introduced in commit 0b6f40d4cabb3bebf551a49a69ce36d4b0375b6a via PR #10408 (submitted 2017-05-16, merged 2017-05-18).

### CODE REVIEW

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/10587/commits/f2fb132cb09efb253df44db09035d4210cc61236

**Comment by theuni** [comment]
utACK f2fb132cb09efb253df44db09035d4210cc61236, but RAII would be nice here.

**Comment by sipa** [comment]
@theuni Agree, but since the existing code is using fopen/fread/fclose, let's keep using that in the bug fix. The rest can happen later.

utACK f2fb132cb09efb253df44db09035d4210cc61236

**Comment by practicalswift** [comment]
Friendly ping @str4d – you might want this fix in zcash too :-)

**Comment by str4d** [comment]
Thanks @practicalswift, nice catch!

**Comment by laanwj** [comment]
> utACK f2fb132, but RAII would be nice here.

Yes it's pretty easy to make a RAII for `FILE*` using `unique_ptr` with a custom deleter, we could even make our `fsbridge::fopen` return this.
Agree with not doing it in this PR though.

**Pull request merged**
