### PR TITLE
Univalue: Pull subtree

### LINKED ISSUE #7102: upgrade univalue
Univalue must be updated before freeze, subtree love needed.

### PR DESCRIPTION
**Pull request by maflcko**
@sipa @gmaxwell is this desired?

Closes #7102

### CODE REVIEW

**Comment by sipa** [comment]
Looks good, but I was waiting for https://github.com/jgarzik/univalue/pull/14 to be merged first.

**Comment by jonasschnelli** [comment]
Agree with @sipa: Let's wait for @laanwj open PR there.

**Comment by laanwj** [comment]
Not sure what is blocking jgarzik/univalue#14.

Need to move this along though for the 0.12 branch. Maybe we could create a univalue fork under bitcoin.

**Comment by jonasschnelli** [comment]
I think a fork of UniValue under the github bitcoin identity would make sense.

**Comment by laanwj** [comment]
OK: https://github.com/bitcoin/univalue

**Comment by MarcoFalke** [comment]
Updated. Make sure you fetch https://github.com/bitcoin/univalue (and not jgarzik) when doing

```
$ contrib/devtools/git-subtree-check.sh src/univalue

**Comment by laanwj** [comment]
```
src/univalue in HEAD was last updated to upstream commit 9218595ed19ccc1a7958c2c7284fd4acb9ce4fdc (tree 5d50d2814919fe88dda5f33df70310c2df080319)
src/univalue in HEAD currently refers to tree 5d50d2814919fe88dda5f33df70310c2df080319
GOOD
```

**Comment by fanquake** [comment]
ACK

**Comment by laanwj** [comment]
Can you re-do this, I've added a commit to  jgarzik/univalue#14 and updated the repository

**Comment by laanwj** [comment]
Thanks, should pass Travis now
```
src/univalue in HEAD was last updated to upstream commit 5839ac3311792f80b9cd5070440c2256e0e69e13 (tree 259c34c09fea315ca8ac9efd61111e6321c315cb)
src/univalue in HEAD currently refers to tree 259c34c09fea315ca8ac9efd61111e6321c315cb
GOOD
```
ACK

**Comment by MarcoFalke** [comment]
@laanwj You have run `subtree-check` on master, not my PR ;)

**Comment by laanwj** [comment]
@MarcoFalke I was running it on master but without your PR merged, worst of both worlds. But I've since updated the post and it should be ok now?

**Comment by MarcoFalke** [comment]
Looks good.

**Comment by sipa** [comment]
Can you also update the list of subtrees in
https://github.com/bitcoin/bitcoin/tree/master/contrib/devtools ?

**Pull request merged**
