### PR TITLE
doc: Update release process with latest changes

### PR DESCRIPTION
**Pull request by maflcko**
Mainly adding the reminder to bump the flatpak

### CODE REVIEW

**Comment by harding** [comment]
Since you're editing this, could you please drop the line about pinging @saivann and myself for problems with Bitcoin.org?  Neither of us have been maintainers on that site for years.  https://github.com/bitcoin/bitcoin/pull/17598/files#diff-de998d58f0c2d133a7876f170453dabcR319

**Comment by MarcoFalke** [comment]
Addressed feedback

**Comment by laanwj** [comment]
ACK fab2f351f2311295c9ed893fe883a08a9104144e

**Review by fanquake — APPROVED** [review]
ACK fab2f351f2311295c9ed893fe883a08a9104144e

**Pull request merged**
