### PR TITLE
[build-aux] Correct AC_PACKAGE_NAME brackets in bitcoin m4 scripts

### LINKED ISSUE #7519: wrong brackets
https://github.com/bitcoin/bitcoin/blob/master/build-aux/m4/bitcoin_qt.m4#L223

AC_MSG_CHECKING(whether to build ]AC_PACKAGE_NAME[ GUI)
AC_MSG_CHECKING(whether to build [AC_PACKAGE_NAME] GUI)

### PR DESCRIPTION
**Pull request by fanquake**
Closes #7519
@luke-jr can you advise if this was done on purpose or not?

### CODE REVIEW

**Comment by laanwj** [comment]
Why close?

**Comment by paveljanik** [comment]
Travis failed on all systems:
```
configure:21110: error: possibly undefined macro: AC_PACKAGE_NAME
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
The command "test -n "$USE_SHELL" && eval '"$USE_SHELL" -c "./autogen.sh"' || ./autogen.sh" exited with 1.
```

I'd be happy if someone helps me to understand it 8)

**Comment by fanquake** [comment]
@laanwj If this is going to be changed I think it needs to be done another way. I'd rather find out if it is correct or not.

**Comment by luke-jr** [comment]
It's intentionally for *de*quoting.

**Comment by laanwj** [comment]
So `]VARIABLE[` is intentional syntax. I's unfortunate that searching for such symbols on google is hard, would love a documentation reference for that.
But it works so @luke-jr is likely right.

**Comment by paveljanik** [comment]
me too 8)

**Pull request closed without merging**
