### PR TITLE
gui: add shortcuts for Options and Command-line options

### PR DESCRIPTION
**Pull request by GChuf**
Adds CTRL shortcuts for Options (CTRL+O) and Command-line options (CTRL+H _- "help"_) in menus.
shortcuts

### CODE REVIEW

**Comment by emilengler** [comment]
Is the options shortcut a cross platform thing?
IIRC macOS uses `CMD+,`

NACK about the Command line Options, I think F1 would fit better

**Comment by GChuf** [comment]
> Is the options shortcut a cross platform thing?
Yes, it is.

**Comment by emilengler** [comment]
@GChuf Take a look at Atom, you open the Settings there with `CTRL-,`

**Comment by jonasschnelli** [comment]
Unsure about that.
At least on macOS, there is already a default shortcut for options.
Would someone really make use of a shortcut for the command line options?

**Comment by GChuf** [comment]
Regarding options, I could make this shortcut available only to non-macOS systems.
And as for command line options, I think someone might use it. I don't think it hurts adding it.

**Pull request closed without merging**
