### PR TITLE
doc: Add post branch-off note about fuzz input pruning

### PR DESCRIPTION
**Pull request by dergoegge**

### CODE REVIEW

**Comment by dergoegge** [comment]
cc @MarcoFalke

**Review by maflcko — APPROVED** [review]
lgtm

**Review by pablomartin4btc — APPROVED** [review]
ACK. 
Btw, there's a typo on [line 29 on that readme](https://github.com/bitcoin-core/qa-assets/blame/main/README.md#L29) file: "corpora", since you are there also on line 32 perhaps should say "running" instead of "run".

**Comment by fanquake** [comment]
> "corpora", 

This isn't a typo. It's a commonly used term when talking about fuzzing.

**Comment by dergoegge** [comment]
@fanquake It is actually a typo, in the readme it is currently spelled "copora" not "corpora"

**Comment by fanquake** [comment]
Right. Confusion over posting the correct spelling and calling it a typo.

**Comment by fanquake** [comment]
Fixed in https://github.com/bitcoin-core/qa-assets/pull/123.

**Pull request merged**
