### PR TITLE
Avoid temporary copies in C++11 ranged-based for loops.

### PR DESCRIPTION
**Pull request by ghost**
The ::value_type of the std::map/std::unordered_map containers is
std::pair<const Key, T>.

Currently a lot of loops drop the const from the iterator which forces
the compiler to create a copy, this should be avoided by using the auto
keyword.

A better explanation can be found in Meyer's Effective Modern C++.

https://books.google.de/books?id=rjhIBQAAQBAJ&lpg=PA41&ots=FmZL15vynY&pg=PA41#v=onepage&q&f=false

### CODE REVIEW

**Comment by sipa** [comment]
All cases you touch are already const, so your rationale doesn't seem to apply.

Regardless I'm personally a fan of the use of auto in this case, but that may be more controversial.

**Comment by laanwj** [comment]
> Currently a lot of loops drop the const from the iterator which forces
the compiler to create a copy, this should be avoided by using the auto
keyword.

I don't understand this rationale for using `auto`. Why doesn't adding `const` to the iterator have the same effect of avoiding copies?

**Comment by ryanofsky** [comment]
> I don't understand this rationale for using auto. Why doesn't adding const to the iterator have the same effect of avoiding copies?

If you take a const reference to a type that requires an implicit conversion it will make a copy. Example where loop items are copied:

```c++
vector<pair<int, int>> v;
...
for (const pair<short, short>& p : v);
```

Using `auto` would avoid the copy. You could also drop `const` to trigger a compiler error if the copies are unintended.

**Comment by dcousens** [comment]
``` cpp
#include <iostream>
#include <vector>

struct Foo {
	Foo () { std::cout << "  Foo()" << std::endl; }
	Foo (const Foo& z) { std::cout << "  Foo(Foo)" << std::endl; }
	Foo (const Foo&& z) { std::cout << "  Foo(Foo&&)" << std::endl; }
};
using FooInt = std::pair<const Foo, int>;

int main () {
	std::cout << "Init" << std::endl;
	std::vector<FooInt> boo;
	boo.push_back({ Foo(), 0 });
	boo.push_back({ Foo(), 1 });
	boo.push_back({ Foo(), 2 });
	const auto bar = boo;

	std::cout << "FooInt : bar" << std::endl;
	for (FooInt x : bar) {}

	std::cout << "const FooInt& : bar" << std::endl;
	for (const FooInt& x : bar) {}

	std::cout << "std::Pair<Foo, int>& : bar" << std::endl;
	for (const std::pair<Foo, int>& x : bar) {}

	std::cout << "std::Pair<const Foo, int>& : bar" << std::endl;
	for (const std::pair<const Foo, int>& x : bar) {}

	std::cout << "auto : bar" << std::endl;
	for (auto x : bar) {}

	std::cout << "auto& : bar" << std::endl;
	for (auto& x : bar) {}

	std::cout << "const auto& : bar" << std::endl;
	for (const auto& x : bar) {}

	return 0;
}
```

``` bash
$ g++ foo.cpp && ./a.out
.. snip ..
FooInt : bar
  Foo(Foo)
  Foo(Foo)
  Foo(Foo)
const FooInt& : bar
std::Pair<Foo, int>& : bar
  Foo(Foo)
  Foo(Foo)
  Foo(Foo)
std::Pair<const Foo, int>& : bar
auto : bar
  Foo(Foo)
  Foo(Foo)
  Foo(Foo)
auto& : bar
const auto& : bar
```

**Comment by MarcoFalke** [comment]
Needs rebase if still relevant

**Comment by jnewbery** [comment]
needs rebase

**Comment by Empact** [comment]
Would be great to avoid these copies, but IMO there is potential documentation / clarity benefit to being explicit about the pair types. How about changing this to just add const to the key types?

**Comment by Empact** [comment]
Also, I see 32 loops over `std::pair`, only one of which has const. Not all of those are necessarily maps, but I'm guessing more of them could be converted.

**Comment by laanwj** [comment]
Going to close this as it seems to be inactive, let me know if you want to pick it up again then I'll reopen.

**Comment by Empact** [comment]
I'll take it.

**Pull request closed without merging**
