### PR TITLE
qt, refactor: Optimize signal-slot connections logic

### PR DESCRIPTION
**Pull request by hebasto**
This PR:
- is a follow up and based on #17937 (update: already merged)
- implements an idea from https://github.com/bitcoin/bitcoin/pull/17937#issuecomment-575991765
- simplifies `WalletFrame` class interface
- as a side effect, removes `bitcoingui` -> `walletframe` -> `bitcoingui` circular dependency
- is an alternative to #17500

### CODE REVIEW

**Review by Binh0103 — APPROVED** [review]

**Comment by jonasschnelli** [comment]
Nice cleanup. Concept ACK.

**Comment by hebasto** [comment]
Rebased.

**Comment by hebasto** [comment]
Rebased after #17937 and #18036 have been merged.

**Comment by hebasto** [comment]
Rebased after #18060 has been merged.

**Comment by hebasto** [comment]
Rebased 809fd3a6e4952671633a5c193fb5fa0f41837b29 -> 7d7cd84351b6c1637ec40f7546c1aaa16bb55199 ([pr17966.04](https://github.com/hebasto/bitcoin/commits/pr17966.04) -> [pr17966.05](https://github.com/hebasto/bitcoin/commits/pr17966.05)) due to the conflict with #16432.

**Comment by hebasto** [comment]
@jonasschnelli Mind reviewing this PR?

**Comment by fanquake** [comment]
There's a Concept ACK, however no subsequent review after ~6 months and this is purely a gui/qt refactor. I'm going to suggest moving this over to https://github.com/bitcoin-core/gui.

**Pull request closed without merging**
