### PR TITLE
Changed getnetworkhps value to double to avoid overflow.

### LINKED ISSUE #7476: Potential overflow of the network's hashrate indicator in the JSON-RPC API
I was calling the `getnetworkhashps` and `getmininginfo` RPCs via some Java code the other day and realized that the hashrate is getting pretty close to overflowing a signed 64-bit integer. Hence, I decided to check how `bitcoind` handles things (with some help from Luke Jr) and it turns out that a signed 64-bit integer (`int64_t`) is used indeed (at least in `mining.cpp` (see [here](https://github.com/bitcoin/bitcoin/blob/master/src/rpc/mining.cpp))) -- potentially elsewhere as well?

As you all know, the max value for a 64-bit signed integer is `2^63-1`, or about `9223372036854775807`. With the sharp increase in hashrate these past few weeks, we seem to be up to about 12.5% of the datatype's full capacity at this point. To illustrate this:

`9 223 372 036 854 775 807 (maximum value of a 64-bit signed integer)`
`1 126 516 160 438 311 092 (current network hashrate -- as of 2016-02-07 12:20:07 UTC)`

According to historical data, the value could wrap in maybe 1 - 1.5 years (or however long it'll take for a 1-order-of-magnitude increase in hashrate).

Luke Jr advised me to create a PR on this in the `#bitcoin-dev` IRC channel the other day. However, as I don't know the codebase that well and am not very well-versed in C++ specifics & caveats, I decided to create this issue instead. 

Maybe someone smarter can take a quick look at this and prove me wrong if that's the case :).

### PR DESCRIPTION
**Pull request by instagibbs**
Fixes https://github.com/bitcoin/bitcoin/issues/7476

### CODE REVIEW

**Comment by laanwj** [comment]
That was easy :)

utACK

**Comment by MarcoFalke** [comment]
Tested ACK  993d089

I don't get why a cast to int was done in the first place.

**Comment by dcousens** [comment]
utACK

**Comment by paveljanik** [comment]
ACK https://github.com/instagibbs/bitcoin/commit/993d089e82fc045d7b0f23e1a5dc934cba0e3306

Before:
```shell
$ btctest getnetworkhashps
1795134992997
$
```
After:
```shell
$ btctest getnetworkhashps
1795134992997.291
$
```

**Comment by dcousens** [comment]
We could still round the value if desired.

**Comment by MarcoFalke** [comment]
> We could still round the value if desired.

Right, but I can't see how this could be desired.

**Comment by laanwj** [comment]
Agree with @MarcoFalke that rounding gives the wrong idea here that we actually know what the precision of this estimate is.

**Comment by laanwj** [comment]
Backported to 0.12 as c3faf78c0e96a8c64a5ff8c37ef6fc4cfb35d125

**Pull request merged**
