### PR TITLE
doc: Add release notes for -printtoconsole and -debuglogfile changes

### PR DESCRIPTION
**Pull request by ghost**
This adds release notes relevant to the changes in #13004 and documented in command line help in #13614.

### CODE REVIEW

**Comment by satwo** [comment]
I attempted to bring this branch up-to-date with Master to attempt to get the Travis CI build to pass, and followed the instructions for rebasing in `CONTRIBUTING.md` to squash my two commits down to one, but something went wrong and now many other files are affected that I never touched. I will  try to get everything going properly but if any maintainer wants to step in and fix it, please feel free. Only the additional few lines in `doc/release-notes.md` are my changes.

**Comment by fanquake** [comment]
@satwo Travis is failing because of the trailing whitespace at the end of the lines you've added. You'll need to remove it.

**Comment by satwo** [comment]
@fanquake Thank you! Had a feeling it was something like that, but wasn't sure how to read the lint error.

**Comment by fanquake** [comment]
utACK 801cb30

**Comment by laanwj** [comment]
thank you—utACK 801cb307b5cc89d09c5aafd0a3c7874848c6a75d

**Pull request merged**
