### PR TITLE
gui: Remove unused RPCConsole::tabFocus

### PR DESCRIPTION
**Pull request by promag**
Added in #14573 but not used, so begone.

### CODE REVIEW

**Comment by emilengler** [comment]
Maybe it's better to comment it out so we can use it if may need it in future.

**Comment by promag** [comment]
IMO better is to kill unused code. It's also easy to bring this back, if needed.

**Comment by practicalswift** [comment]
utACK b078067b9c2aa1d259395198005fab470ea4e39d

**Comment by emilengler** [comment]
It perfectly removes it, utACK

**Comment by promag** [comment]
@practicalswift @emilengler please take a new look at [CONTRIBUTING.md#peer-review](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#peer-review), it was recently updated in #16149.

**Comment by emilengler** [comment]
@promag Didn't knew it, then 
Concept ACK
Approach ACK

**Comment by hebasto** [comment]
ACK b078067b9c2aa1d259395198005fab470ea4e39d
I have not tested the code, but I have reviewed it and it looks OK, I agree it can be merged.

**Comment by laanwj** [comment]
ACK b078067b9c2aa1d259395198005fab470ea4e39d, there's nothing really to test here

> Maybe it's better to comment it out so we can use it if may need it in future (If that's a thing in this project).

I think if we don't expect it to be necessary at some point it's better to remove it.
(I'm generally for removing dead code unless it breaks API expectations)

**Pull request merged**
