### PR TITLE
build: add lto configure option

### PR DESCRIPTION
**Pull request by theuni**
Addresses #10616. Please see the commit messages and note that AR/RANLIB may need to be set manually!

This is testing the waters for LTO. There are a few unknowns:
- A boost LTO issue was addressed here, but others may remain for different libs/versions
- ar/ranlib detection will likely turn out to be annoying
- Not yet tested with Gitian

I propose adding this as-is (maybe after Gitian testing), and seeking feedback. I suspect that there will be quite a few platforms/toolchains where it's broken, but there's only so much we can do about it.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Built successfully on my gitian machine (haven't tested the build yes though): https://bitcoin.jonasschnelli.ch/build/213

**Comment by laanwj** [comment]
Bleh, the boost work-around is really nasty. It breaks my use-case with cloudabi, where fs::path is not actually convertible from/to a string losslessly.

**Comment by MarcoFalke** [comment]
@theuni This can be closed given https://github.com/bitcoin/bitcoin/issues/10616#issuecomment-372027171 ? Otherwise needs rebase

**Comment by laanwj** [comment]
Closing, let me know when it needs to be reopened.

**Pull request closed without merging**
