### PR TITLE
Prefer iterators arrow operator over iterator dereference

### PR DESCRIPTION
**Pull request by bytting**
Prefer iterators arrow operator over iterator dereference to improve readability

### CODE REVIEW

**Review by dcousens — APPROVED** [review]

**Comment by practicalswift** [comment]
Should we extend this to doing it globally? If so, the following might be of help:

```
git grep -E '\(\*[a-zA-Z0-9]+\)\.(first|second)' # 80 occurrences of 
                                                 # which 7 in validation.cpp
```

Ideally such a change should probably be made as an scripted-diff.

**Comment by corebob** [comment]
@practicalswift 
That only works for iterators to pairs, still that seems to be a common structure here.
I'm not quite comfortable with automating this but if someone wants to go for that, that's fine with me.

**Comment by laanwj** [comment]
Although I agree with you with regard to readability, I'm not convinced this is worth the risk to do as a global change. Sorry, closing.

**Comment by bytting** [comment]
@laanwj Fair enough

**Pull request closed without merging**
