### PR TITLE
Move script flag to/from-string logic from tests to script/interpreter

### PR DESCRIPTION
**Pull request by luke-jr**
When we last discussed making scripts debuggable (sometime after #3901), the plan was to instead trace execution rather than single-step through it.

This is a dependency step toward that, and is eventually used for the RPC `verifyscript` to parse its `"flags"` option.

See also #10729

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Needs rebase

**Comment by luke-jr** [comment]
Rebased

**Comment by laanwj** [comment]
I'm okay with moving this out of the tests if it's necessary in another place, however the string stuff doesn't belong with the interpreter consensus code IMO. Better to keep it in a separate compilation unit, like with the CBitcoinAddress split done in #11117.

**Comment by laanwj** [comment]
@luke-jr ping?

**Comment by luke-jr** [comment]
Hmm, so where would you suggest? Bundle it in with RPC-specific stuff?

**Comment by luke-jr** [comment]
Rebased, and moved it to script/script_flags.{h,cpp} for now.

**Comment by luke-jr** [comment]
Closing due to apparent lack of interest/reviewers

**Pull request closed without merging**
