### PR TITLE
[qa] Fix race conditions in p2p-compactblocks.py and sendheaders.py

### PR DESCRIPTION
**Pull request by sdaftuar**
Sorry for the code churn in this test; this is another attempt to resolve the test failure reported in #8842.

In #8854 I added a sync_with_ping() with the idea of making sure that we'd processed all the block announcements from the node before continuing in the test; however that is insufficient for making sure that the node had actually tried sending all the block announcements it's going to eventually send.  My guess is that the test failures are happening in situations where the block announcements from the generate(101) call don't finish arriving until after the sync_with_ping(), throwing off the later tests.

So I replaced the sync_with_ping with an explicit check that the node's tip has been announced, before continuing on with the test.  Hopefully this resolves the lingering issues.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
utACK 6976db2

**Comment by sdaftuar** [comment]
I suspect the failure in sendheaders may have the same underlying cause:a generate() call where the block announcements might be arriving later than expected.  I'll try to fix that up in this PR as well.

**Comment by sdaftuar** [comment]
I believe I've addressed the occasional test failure in sendheaders.py as well now.

**Comment by MarcoFalke** [comment]
utACK b55d941

**Comment by instagibbs** [comment]
utACK b55d9411e7e1aa36ddabba3b942f2e1c736c1bd9

**Comment by btcdrak** [comment]
utACK d6c83b95cff2ff290533593719d6501ecf128f13

**Pull request merged**
