### PR TITLE
scripted-diff: stop using the gArgs wrappers

### PR DESCRIPTION
**Pull request by benma**
Following #9494, where they were introduced to ease the transition.

The first commit removes the uses, the second commit removes the wrappers themselves.

### CODE REVIEW

**Comment by practicalswift** [comment]
utACK 39faab76321bc6bf217ffdc9b380c60b9d99416f

**Comment by sipa** [comment]
utACK 39faab76321bc6bf217ffdc9b380c60b9d99416f

**Comment by fanquake** [comment]
Concept ACK. Needs rebase.

**Comment by jnewbery** [comment]
Tested ACK 39faab76321bc6bf217ffdc9b380c60b9d99416f

**Comment by benma** [comment]
Rebased.

**Comment by TheBlueMatt** [comment]
Wait, is this the direction we want to go in, or the opposite? eg i figured we'd want to slowly move towards storing references to gArgs in things that need them, eg as we move towards classes which contain things (CConnman, CChainState, etc) we'd either pass in the options relevant to those objects (ala CConnman's constructor) or pass them the gArgs to avoid the global.

**Comment by benma** [comment]
@TheBlueMatt what you mention makes sense to me, but it seems unrelated to this PR, which is just about removing the wrappers (which use the same global). This PR is also good prep-work for storing references to gArgs in classes in that sense.

**Comment by TheBlueMatt** [comment]
Hmm, I figured it'd be easier to just sed/gArgs/locallyReferencedArgs/ in files, but I guess it doesnt matter much either way.

**Comment by benma** [comment]
One can easily do this after this PR, whereas before, `gArgs` didn't even appear in all the places you'd expect it to and you'd have to use the same kind of complex regexp to catch them all as in the scripted diff script. I agree it doesn't matter much, but it does make it easier I think.

**Comment by practicalswift** [comment]
Needs rebase :-)

**Comment by benma** [comment]
Rebased 😆

**Comment by benma** [comment]
Rebased.

@sipa I'd be glad if this could be merged soon, as it conflicts with other changes very often.

**Comment by benma** [comment]
How can I retrigger CI?

**Comment by sipa** [comment]
@benma I've restarted Travis.

**Comment by TheBlueMatt** [comment]
Needs rebase.

**Comment by benma** [comment]
@TheBlueMatt thx. Rebased.

**Comment by promag** [comment]
I believe 3b22edd has an unrelated change that should be in bb3d105, otherwise tested ACK 3b22edd.

**Comment by benma** [comment]
@promag thank you. util.h and util.cpp are excluded from the scripted diff due to false positives. Making it work would take an unreasonable effort, so I did those few instances manually.

**Comment by promag** [comment]
@benma what about switching commit order? I know it's not the logical thing to do in terms of commit order, but in terms of what the PR stands for, IMO it's fine.

**Comment by benma** [comment]
@promag, I prefer it if each is compiles and passes tests, and also think it would be more confusing and unneeded work.

**Comment by MarcoFalke** [comment]
@benma is right. Commits should be atomic (https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#contributor-workflow)

**Review by ryanofsky — COMMENTED** [review]
Slightly tested ACK 3b22edd106f51cc25b200e41ffaab10877c50144. Confirmed both commits compile, so I think the atomic commit issue is resolved.

**Comment by MarcoFalke** [comment]
utACK 3b22edd106f51cc25b200e41ffaab10877c50144

**Comment by promag** [comment]
ACK 3b22edd.

**Review by promag — COMMENTED** [review]
ACK 3b22edd.

**Comment by promag** [comment]
@laanwj it would be nice to have this in so #10976 can be rebased.

**Comment by sipa** [comment]
Let's try to merge this right before branching off.

**Comment by MarcoFalke** [comment]
utACK 3b22edd106f51cc25b200e41ffaab10877c50144, but it conflicts with #10882, which is tagged for 0.15.

**Comment by benma** [comment]
I don't mind rebasing once more after #10882 is merged.

**Comment by MarcoFalke** [comment]
Needs rebase.

**Comment by laanwj** [comment]
Rebased and merged via c2704ec

**Comment by jtimon** [comment]
Oh, nice, I was planning to do this but thank you for doing it faster!

**Pull request closed without merging**
