### PR TITLE
[wallet] Kill accounts

### PR DESCRIPTION
**Pull request by jnewbery**
To make space for new words, it's time to eliminate a word that has fallen into disuse: accounts. We make it fade into the night of time.

RIP accounts.

Completes #12952

### CODE REVIEW

**Comment by laanwj** [comment]
Bon débarras!

Concept ACK, looks good in a first skim of commits.

**Comment by jnewbery** [comment]
Rebased.

V0.17 is branched. This is now ready for review/merge.

**Comment by MeshCollider** [comment]
I think the general agreement towards this is clear but Concept ACK regardless. Will try and find time to review this soon

**Comment by jnewbery** [comment]
Perec redacted to remove any potential copyright material from git logs 😢

**Comment by jnewbery** [comment]
rebased

**Comment by jnewbery** [comment]
Thanks @DrahtBot . Rather than continually rebase this large PR, I've split the first three commits into #14023.

Reviewers, please review that first.

**Comment by jnewbery** [comment]
The 'account' RPC has been removed in #14023. This PR removes all dead code left behind by that PR.

**Comment by promag** [comment]
Care to fix https://github.com/bitcoin/bitcoin/pull/14023#discussion_r213136227?

**Comment by laanwj** [comment]
utACK 30538846964e8c7490f94d0b57580e65aaf9c5a9

**Comment by jnewbery** [comment]
Thanks @laanwj & @promag . Typo fixed in https://github.com/bitcoin/bitcoin/pull/13825/commits/85ec8d645f9aace793514ab36d6cc7a5382f3e7c

**Comment by laanwj** [comment]
re-utACK 85ec8d6

**Comment by jonasschnelli** [comment]
utACK 85ec8d645f9aace793514ab36d6cc7a5382f3e7c

**Comment by gmaxwell** [comment]
utACK .. but mostly I just like the PR text.

**Comment by ajtowns** [comment]
utACK 85ec8d645f9aace793514ab36d6cc7a5382f3e7c

Some of the changes for the "GetLabelDestination" commit (53038b47) are actually in the following "Delete unused account functions" commit, causing "make all" to fail. Otherwise looks good.

**Comment by jnewbery** [comment]
4 utACKs. Rather than fix the build break in the intermediate commit, I think it makes sense to just squash everything down to one commit (I only split it up so granularly to aid reviews).

@laanwj - if you agree, I'm happy for you to squash these down when you merge, or I can do it. Let me know.

**Comment by laanwj** [comment]
@jnewbery ok, I'll do that, no problem

**Comment by cryppty** [comment]
Hi, this is a real pity that you have removed the "accounts" functionality. Many platforms have been designed around this as to "move" and "sendfrom" between accounts  Is there a discussion somewhere where one can see the reasoning behind removing this functionality?

**Comment by inzider** [comment]
Why comments on th

> Hi, this is a real pity that you have removed the "accounts" functionality. Many platforms have been designed around this as to "move" and "sendfrom" between accounts Is there a discussion somewhere where one can see the reasoning behind removing this functionality?

I fully agree with you. This is close minded mentality, not looking at all side of the story, only at green users and miners side.

I need this CORE functionality!!!

What should I do now? Downgrade my version ? How odd. 
-deprecated=accounts options seems without effect.

**Comment by sipa** [comment]
@inzider The accounts functionality we had almost certainly did not what you would expect it to do. It never supported moving coins between addresses, for example. You may be interested in the more modern multiwallet feature that supports having multiple truly independent wallets simultaneously.

**Comment by inzider** [comment]
I appreciate the suggestion and this is exactly what I DON'T want.
Im lkooing at one wallet with multiple address as in the core code. 

I'm using a code that is based on bitcoin (multichain) and sendfrom does exactly that! 
Moving fund from one address to the other in the same wallet.

This is useful is MANY situation - I could write a novel on it.   

Refer to : https://stackoverflow.com/questions/21450384/how-can-i-transfer-bitcoins-from-my-address-to-other-bitcoin-addresses

As the core command document say: https://en.bitcoin.it/wiki/Original_Bitcoin_client/API_calls_list

Along the way it almost certainly seems some people did not understand the purpose of it, and just removed it...

Oh well, I just downgraded my version and it works now, how stupid...

**Comment by ryanofsky** [comment]
I don't understand use-case described https://github.com/bitcoin/bitcoin/pull/13825#issuecomment-624990913, since sendfrom didn't control coin selection and had no influence on what addresses (so to speak) would be sent from. It only affected how account balances were computed.

If there's an actual use-case made more difficult by removing accounts, it'd be good to open a feature request to see how it could be addressed. I did describe some steps for replicating account functionality outside of the wallet in https://github.com/bitcoin/bitcoin/issues/12952#issuecomment-552960188

**Pull request closed without merging**
