### PR TITLE
wallet: Add external-signer-support specific error message

### PR DESCRIPTION
**Pull request by hebasto**
On master (5f44c5c428b696af4214b2519cb2bbeb0e4a1027) an attempt to load an external signer wallet using Bitcoin Core compiled without external signer support fails with the following log messages:
```
2022-02-20T19:01:11Z [qt-walletctrl] Using SQLite Version 3.31.1
2022-02-20T19:01:11Z [qt-walletctrl] Using wallet /home/hebasto/.bitcoin/testnet3/wallets/coldcard-0220
2022-02-20T19:01:11Z [qt-walletctrl] init message: Loading wallet…
2022-02-20T19:01:11Z [qt-walletctrl] [coldcard-0220] Error: External signer wallet being loaded without external signer support compiled
2022-02-20T19:01:11Z [qt-walletctrl] [coldcard-0220] Releasing wallet
```

While log messages are good, a message in the GUI window is completely misleading:

Screenshot from 2022-02-20 20-43-46

This PR fixes this issue:

Screenshot from 2022-02-20 21-01-18

### CODE REVIEW

**Review by kristapsk — APPROVED** [review]
ACK 7f3a6a9495fafbf77f221297615fa56dc3ecc64a

**Comment by kristapsk** [comment]
Not related to this PR, but what I noticed - it seems there is no normal way of unloading wallet in this case, bitcoind / bitcoin-qt will refuse to start. Only workaround is to manually edit settings.json and remove it from there.

**Review by brunoerg — APPROVED** [review]
crACK 7f3a6a9495fafbf77f221297615fa56dc3ecc64a

**Comment by achow101** [comment]
ACK 7f3a6a9495fafbf77f221297615fa56dc3ecc64a

**Comment by luke-jr** [comment]
>Not related to this PR, but what I noticed - it seems there is no normal way of unloading wallet in this case, bitcoind / bitcoin-qt will refuse to start. Only workaround is to manually edit settings.json and remove it from there.

See https://github.com/bitcoin-core/gui/pull/236

**Pull request merged**
