### PR TITLE
util: remove unwanted fields from bitcoin-cli -getinfo

### LINKED ISSUE #17314: Re-thinking `bitcoin-cli -getinfo`
Now that `getinfo` is no longer part of the RPC API, and client-side implementation is not subject to API stability, it's possible to start thinking about making it more user friendly.

I've made a start in #17302 by adding some status fields.

Some other potential ideas:

- Remove noise: fields that users are unlikely to want to query often ~~`protocolversion`, `walletversion`, `keypoololdest`~~ (these three were done in #17650)
- Multiwallet: List balance per wallet
- List all proxies, at least if they're different from the IPv4 one
- Alternative, more human-friendly, format besides JSON? Colors, progress bars :smile:?

### PR DESCRIPTION
**Pull request by malevolent**
Removed the following fields from -getinfo: protocolversion, walletversion and keypoololdest.

### CODE REVIEW

**Comment by laanwj** [comment]
Concept ACK

Code changes look good to me. Some git nits:

- Please adapt your commit message to the standard format: a short title, an empty line then the body of the text
- Please set a username and mail address other than "EC2 Default User"

**Comment by practicalswift** [comment]
Concept ACK

@malevolent Welcome as a contributor! :)

**Comment by emilengler** [comment]
Concept ACK

Your tests are failing.
Please update https://github.com/bitcoin/bitcoin/blob/master/test/functional/interface_bitcoin_cli.py.
See line 61-76

**Comment by malevolent** [comment]
@laanwj Yes sir, done and done.
@practicalswift Thank you :) 
@emilengler Thanks, just pushed change to delete tests for removed api calls.

**Comment by fanquake** [comment]
Please [squash your commits](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#squashing-commits).

> Please adapt your commit message to the standard format: a short title, an empty line then the body of the text

You could use a commit title like `util: remove unwanted fields from bitcoin-cli -getinfo`.

**Comment by malevolent** [comment]
Hi @fanquake , thanks for letting me know, I rebased and used better titles for the commit messages. Please let me know if theres anything else needed

**Comment by practicalswift** [comment]
ACK 868a32228688afca262f10d3be9fa6caa9cdea65 -- diff looks correct

**Comment by laanwj** [comment]
the author is still reported as "EC2 Default User"
```
commit 868a32228688afca262f10d3be9fa6caa9cdea65
Author: EC2 Default User <ec2-user@ip-172-31-6-106.us-west-1.compute.internal>
```
i think you need to do `git commit --amend --reset-author ` to fix this, if you want to be credited correctly

**Comment by malevolent** [comment]
@laanwj Thanks I think that fixed it, let me know if there is anything else I need to do

**Comment by laanwj** [comment]
ACK 01c87015597021bf1c0856f7f6be175bdde844b2

**Comment by practicalswift** [comment]
ACK 01c87015597021bf1c0856f7f6be175bdde844b2 -- diff looks correct

**Comment by malevolent** [comment]
@laanwj is there anything I need to do for the release note label that was added? Also, I think I should change it from saying "closes #17314" since there are other parts to that issue, right?

**Comment by fanquake** [comment]
> release note label that was added?

This can be addressed at a later date.

> I think I should change itfrom saying "closes #17314" since there are other parts to that issue, right?

Correct, that issue doesn't need to be closed after this is merged.

**Comment by achow101** [comment]
ACK 01c87015597021bf1c0856f7f6be175bdde844b2

**Comment by laanwj** [comment]
> release note label that was added?

Yea, it's probably better to wait until the release in this case, if there's other bitcoin-cli changes at well they should be grouped and scattered over the place.

**Comment by fanquake** [comment]
@laanwj Could you add any relevant release notes to https://github.com/bitcoin-core/bitcoin-devwiki/wiki/0.20.0-Release-Notes-Draft ?

**Comment by MarcoFalke** [comment]
Done https://github.com/bitcoin-core/bitcoin-devwiki/wiki/0.20.0-Release-Notes-Draft/_compare/b03541ec204bd2c7460b3c383c45f84b21c5b65c...3f531649bb00d9824814ff3a7e9c7282e806844b

**Pull request merged**
