### PR TITLE
scripted-diff: Remove BOOST_FOREACH, Q_FOREACH and PAIRTYPE

### PR DESCRIPTION
**Pull request by jtimon**
Separated from #10193 since the reverse iterator isn't working there, as suggested in https://github.com/bitcoin/bitcoin/pull/10193#issuecomment-293742166 (but without removing #include <boost/foreach.hpp> everywhere except where BOOST_REVERSE_FOREACH is needed).

Seems to compete with #10497

### CODE REVIEW

**Comment by practicalswift** [comment]
utACK 9eafbf2

Excellent work! I ❤️ modern C++

**Comment by jtimon** [comment]
Needed rebase after #10195. Just run the sed scripts again. Review should be as simple as it was, more or less.

**Comment by jtimon** [comment]
Needed rebase again(2)

**Comment by sipa** [comment]
Concept ACK. Nit: you can add a commit that removes the `#include <boost/foreach.hpp>` directives.

**Comment by jtimon** [comment]
> you can add a commit that removes the #include <boost/foreach.hpp> directives.

But not in the whole project, because I'm not able to remove BOOST_REVERSE_FOREACH yet, see #10193 on top of this one.

**Review by ryanofsky — COMMENTED** [review]
utACK 1238f13cf6ccf1177b66df735f360c61ae1dc20b. Seems fine to remove includes in a followup pr as long as some of them are still needed for reverse iteration.

**Comment by theuni** [comment]
nice, utACK 1238f13cf6ccf1177b66df735f360c61ae1dc20b.

**Comment by sipa** [comment]
utACK 1238f13cf6ccf1177b66df735f360c61ae1dc20b

**Pull request merged**
