### PR TITLE
PSBT backports to 0.17

### PR DESCRIPTION
**Pull request by sipa**
This is a backport of #14588, #14377, and #14197's test to 0.17.

### CODE REVIEW

**Comment by sipa** [comment]
Please review, @achow101 and @gwillen. All tests from the original PRs are included, and all commits pass, though some code changes may have been missed or ended up in the wrong commit.

**Comment by gmaxwell** [comment]
Concept ACK

**Comment by gwillen** [comment]
ACK on my changes appearing correctly-included.

**Comment by MarcoFalke** [comment]
nit: Are these cherry-picks? It might help to include the id they were cherry-picked from.

See for example https://github.com/bitcoin-core/bitcoin-maintainer-tools#backport which might do just that (haven't tried it)

**Comment by sipa** [comment]
@MarcoFalke I created it by taking the merged #14588, rebasing it on top of the 0.17 branch, and removing all the commits except the ones from the 3 PRs listed in the description. Some commits needed nontrivial changes to work on top of the 0.17 (which lacks some of the refactors that happened in master). They're not clean cherry-picks.

Is there any marker or tag I need to put on the PR or commits so it gets picked up by the release notes scripts?

**Comment by sipa** [comment]
Added Github-Pull: and Rebased-From: annotations

**Comment by gmaxwell** [comment]
kinda tested ACK.

**Comment by Sjors** [comment]
tACK 7bee414

I reviewed it along side with the originals, which I hadn't seen before, so that's a fresh perspective :-)

**Comment by promag** [comment]
ACK 7bee414, indeed not a clean rebase, at least for me `FillPSBT` was the most hard.

**Pull request merged**
