### PR TITLE
wallet: move BDB specific classes to bdb.{cpp/h}

### PR DESCRIPTION
**Pull request by achow101**
Moves the BDB specific classes from db.{cpp/h} to bdb.{cpp/h}.

To do this, `SplitWalletFilePath` is first made non-static. Then `IsWalletLoaded` functionality is moved to `IsBDBWalletLoaded` which is called by `IsWalletLoaded`. Then the bulk of db.{cpp/h} is moved to a new file bdb.{cpp/h}.

While doing some moveonly stuff, an additional commit moves the `*Cursor` and `Txn*` implementations out of the header file and into the cpp file.

Part of #18971

### CODE REVIEW

**Comment by laanwj** [comment]
Code review ACK 61c16339da4e80b1320a6296df6d96cd7a84bb4e

**Comment by promag** [comment]
Yesterday I was reviewing #18971 and thought about splitting it, and this PR is exactly it.

Code review ACK 61c16339da4e80b1320a6296df6d96cd7a84bb4e.

nit, typo in first commit, if you have to push again for some other reason.

**Review by meshcollider — COMMENTED** [review]
utACK 61c16339da4e80b1320a6296df6d96cd7a84bb4e

**Review by ryanofsky — COMMENTED** [review]
Code review ACK 61c16339da4e80b1320a6296df6d96cd7a84bb4e

**Pull request merged**
