### PR TITLE
Add missing newlines to debug logging

### PR DESCRIPTION
**Pull request by laanwj**
~~Don't we have a linter that should catch these?~~

### CODE REVIEW

**Comment by jonasschnelli** [comment]
utACK 4987c2495f2910434645abe7f4fe424101cb36e3

**Comment by MarcoFalke** [comment]
Suggested fix for the linter:

```diff
diff --git a/contrib/devtools/lint-logs.sh b/contrib/devtools/lint-logs.sh
index 3bb54359a8..35be13ec19 100755
--- a/contrib/devtools/lint-logs.sh
+++ b/contrib/devtools/lint-logs.sh
@@ -13,12 +13,13 @@
 # ignored
 
 
-UNTERMINATED_LOGS=$(git grep "LogPrintf(" -- "*.cpp" | \
+UNTERMINATED_LOGS=$(git grep --extended-regexp "LogPrintf?\(" -- "*.cpp" | \
     grep -v '\\n"' | \
     grep -v "/\* Continued \*/" | \
+    grep -v "LogPrint()" | \
     grep -v "LogPrintf()")
 if [[ ${UNTERMINATED_LOGS} != "" ]]; then
-    echo "All calls to LogPrintf() should be terminated with \\n"
+    echo "All calls to LogPrintf() and LogPrint() should be terminated with \\n"
     echo
     echo "${UNTERMINATED_LOGS}"
     exit 1

**Comment by laanwj** [comment]
@MarcoFalke thanks, will add that and fix the remaining cases.

**Comment by promag** [comment]
utACK 4b75dcf.

**Pull request merged**
