### PR TITLE
bitcoin-tx: Avoid treating integer overflow as OP_0

### PR DESCRIPTION
**Pull request by maflcko**
Seems odd to treat integer overflow as `OP_0`, so fix that.

### CODE REVIEW

**Comment by practicalswift** [comment]
Concept ACK

Nice to see `LocaleIndependentAtoi` be replaced by `ToIntegral` too.

**Review by meshcollider — COMMENTED** [review]
utACK fa0c2f92aa226c51b36220c2b31b029b6188f8aa

**Review by theStack — APPROVED** [review]
Concept and code-review ACK fa0c2f92aa226c51b36220c2b31b029b6188f8aa

**Review by theStack — APPROVED** [review]
re-ACK fa43e7c2d9dc5e2df70acd2019bdd24023c1d333

**Review by shaavan — APPROVED** [review]
ACK fa43e7c2d9dc5e2df70acd2019bdd24023c1d333

This PR’s primary focus is to avoid treating an overflow integer value as output 0.

This is done by using the **ToIntegral** function that returns the integer value of the number if it is in the **int_64** range; otherwise, it produces a **nullopt**. Followed by this, a check is applied to a returned value which checks if it has a valid value. And return an error in case if its not.

This PR also deals with further minors changes, which are:
- Appropriate additions to the comments in **strencodings.h** and **lint-locale-dependence.sh** files.
- Using **C++11** range based indicator in **ParseScript** function.
- Fixing whitespaces in **ParseScript** function.

I agree with the above changes, and I think they are necessary and valuable.

I would like to suggest one addition, though. In case you have to update the PR for some major reason, how about also adding the test for negative **-999….999** (i.e., huge number)

```
  { "exec": "./bitcoin-tx",
    "args": ["-create", "outscript=0:-999999999999999999999999999999"],
    "return_code": 1,
    "error_txt": "error: script parse error: decimal numeric value only allowed in the range -0xFFFFFFFF...0xFFFFFFFF",
    “description”: “Try to parse an output script with a decimal number below the allowed range.”
  },
```

**Review by meshcollider — COMMENTED** [review]
re-utACK fa43e7c2d9dc5e2df70acd2019bdd24023c1d333

**Pull request merged**
