### PR TITLE
build, bench, msvc: Add missing benchmarks

### PR DESCRIPTION
**Pull request by hebasto**
On the master branch, the `bench_bitcoin.vcxproj` MSVC project misses wallet-specific source files.

This PR fixes this issue.

Benchmark run on Windows:
```
> src\bench_bitcoin.exe -filter="CoinSelection|BnBExhaustion|Wallet.*"

|               ns/op |                op/s |    err% |     total | benchmark
|--------------------:|--------------------:|--------:|----------:|:----------
|          398,800.00 |            2,507.52 |    1.5% |      0.01 | `BnBExhaustion`
|          584,450.00 |            1,711.01 |    1.5% |      0.01 | `CoinSelection`
|       86,603,650.00 |               11.55 |    0.4% |      1.91 | `WalletAvailableCoins`
|            7,604.00 |          131,509.73 |    0.9% |      0.01 | `WalletBalanceClean`
|          124,028.57 |            8,062.66 |    2.6% |      0.01 | `WalletBalanceDirty`
|            7,587.12 |          131,802.30 |    1.9% |      0.01 | `WalletBalanceMine`
|               48.58 |       20,583,872.99 |    0.9% |      0.01 | `WalletBalanceWatch`
|        2,371,060.00 |              421.75 |    1.3% |      0.13 | `WalletCreateTxUseOnlyPresetInputs`
|       96,861,760.00 |               10.32 |    0.9% |      5.31 | `WalletCreateTxUsePresetInputsAndCoinSelection`
|              280.71 |        3,562,424.13 |    1.5% |      0.01 | `WalletIsMineDescriptors`
|            1,033.47 |          967,618.32 |    0.3% |      0.01 | `WalletIsMineLegacy`
|              282.36 |        3,541,599.91 |    0.5% |      0.01 | `WalletIsMineMigratedDescriptors`
|      484,547,300.00 |                2.06 |    1.0% |      2.43 | `WalletLoadingDescriptors`
|       29,924,300.00 |               33.42 |    0.4% |      0.15 | `WalletLoadingLegacy`
```

### CODE REVIEW

**Comment by hebasto** [comment]
@achow101 @sipsorcery 

Any ideas how to release a wallet database properly (see the last commit)?

**Comment by sipsorcery** [comment]
@hebasto only guessing but I've always found Windows fairly average at releasing file and socket handles. Maybe that's the cause of the test failure rather than anything code related. 

In my other life I work with SIP (telecoms protocol) with lots of socket handles flying around. If it's only for testing then I generally just add a 5 second wait and try again for handle in use errors.

**Comment by fanquake** [comment]
Is the intention to try and merge this as-is, or are the Windows issues going to be investigated and fixed (can draft if so)?

**Comment by hebasto** [comment]
> Is the intention to try and merge this as-is, or are the Windows issues going to be investigated and fixed (can draft if so)?

The former. The issue is tracked in https://github.com/bitcoin/bitcoin/issues/29816.

**Comment by hebasto** [comment]
> An alternative would be to update the generation script?

Yes. However, in the light of coming migration to CMake, it makes no substantial difference, right?

**Comment by hebasto** [comment]
cc @sipsorcery

**Pull request merged**
