### PR TITLE
scripts: add key for Michael Ford (fanquake) to trusted keys list

### PR DESCRIPTION
**Pull request by fanquake**
Adding my key to the [trusted keys list](https://github.com/bitcoin/bitcoin/blob/master/contrib/verify-commits/trusted-keys) to join the maintainer group. I'll gain merge access and will continue with all triage/repo management work. I'll be focusing primarily on build system development with some guidance from theuni.

Some maintainer related discussion from the Core Dev meetup in Amsterdam is available [here](http://diyhpl.us/wiki/transcripts/bitcoin-core-dev-tech/2019-06-06-maintainers/).

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Does that mean you are officially a maintainer? (Maybe mention that in the description, and which parts you are primarily going to maintain)



ACK 8081927c33299e82498a85ac773c9f162e69ecaf

Only checked that the commit was signed with a key of "fanquake".
For some reason I never signed your key as part of a party, I think.

<details><summary>Show signature and timestamp</summary>

Signature:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK 8081927c33299e82498a85ac773c9f162e69ecaf

Only checked that the commit was signed with a key of "fanquake".
For some reason I never signed your key as part of a party, I think.
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEE+rVPoUahrI9sLGYTzit1aX5ppUgFAlwqrYAACgkQzit1aX5p
pUiRSAv/WhRxCHlWvpE8sgWMsFpE5T/5EK1xqPWECe19s8D5uE2llzYIIeO9wDW9
SF+HRHoGU9L7/fbb6rr6r2SUxXys9yFXsSsjaDnISeT3HKSwK/v3qi6pqAzM523D
ZGUPKcfyz9jFBwlfmKarZbV6bXxn9N9ibIGfiQg3+QMZUgV6RGThJKN3Niq7a0C3
IK7/+b/Nyp6PhH1mYccHZu/DWEz1NfSQ25SRMlHO/61O8dOih82wppydYZByVxAF
o2AfmLaO45yNNPxK9BFlpu4MLMPOZNYkiwbOaVwxb/gO1vf3Pwk23+D0JnWDUZOQ
zjF0m63fcndOsC60J327/XU4LP8862uCsP995EIwfTt6FLkNLPYXHDbketoeMw/Z
1fae1EX+4L70/AYYcGS3zGJUQgdULMv3kdJd17xUTR5CZ72ulVdsFTGds8HKWkOX
SNNFOR3Xk+OHkwEK3LCLs+xUmwmdzuHkbUdRn5JLRlQL4tRvq50RTz7Br5qJnV6+
st9uvYAr
=uYjG
-----END PGP SIGNATURE-----
```

[Timestamp of file with hash `14bcdd110c0f72b7f23748e1c19ae6656e75575292f425f4eb1a09cae6786879  -`](https://opentimestamps.org/info/?004f70656e54696d657374616d7073000050726f6f6600bf89e2e884e89294010814bcdd110c0f72b7f23748e1c19ae6656e75575292f425f4eb1a09cae6786879f010c29eaea3ec22ab8b8e693b5f5140c0e108fff0107df2e187c1f63ac5150a77c83f66eb6808f0109f43a16d9e389202cc9b510b21f39e0e08f120851aad7d455824ae11978b3f39ae81bd4db02cb741186abd5490552e3ac6fc7808f1045cfa1c0af00864edeec0c1ce244e0083dfe30d2ef90c8e292868747470733a2f2f66696e6e65792e63616c656e6461722e657465726e69747977616c6c2e636f6dfff01087e17acb295e4d7ff692aa3d7692310308f1045cfa1c0af008007aac82b96049480083dfe30d2ef90c8e2c2b68747470733a2f2f626f622e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267fff0108ca6dbeebf82d7966b1bc842f4cdfb9408f1045cfa1c0af0089551c7e46a80b5fe0083dfe30d2ef90c8e2e2d68747470733a2f2f616c6963652e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267f0108fbee07387330f7ff9e7ec0c0525d74808f1045cfa1c0af00818dbaaa9be6523bb0083dfe30d2ef90c8e232268747470733a2f2f6274632e63616c656e6461722e636174616c6c6178792e636f6d)

</details>

**Comment by achow101** [comment]
Concept ACK (didn't actually check the key yet)

**Comment by laanwj** [comment]
ACK, this matches the key I have 8081927c33299e82498a85ac773c9f162e69ecaf:
```
pub   rsa4096 2013-04-10 [SCEA]
      E777299FC265DD04793070EB944D35F9AC3DB76A
uid           [ unknown] Michael Ford (bitcoin-otc) <fanquake@gmail.com>
sub   rsa4096 2013-04-10 [SEA]
```

**Comment by meshcollider** [comment]
ACK, this matches the key I have from the CoreDev New York 2018 keysigning party

**Comment by jnewbery** [comment]
Concept ACK. Please update OP to explain why you're doing this (to be a maintainer)

**Comment by fanquake** [comment]
@jnewbery Thanks, done.

**Comment by practicalswift** [comment]
Concept ACK

Welcome as a maintainer @fanquake! 🎉

**Comment by IlyasRidhuan** [comment]
ACK. 8081927c33299e82498a85ac773c9f162e69ecaf matches the key I have.

**Pull request merged**
