### PR TITLE
[0.19] final rc2 backports

### PR DESCRIPTION
**Pull request by maflcko**

### CODE REVIEW

**Comment by fanquake** [comment]
Given the cctools used in the 0.19 branch is somewhat older, our patch from master [doesn't apply](https://travis-ci.org/github/bitcoin/bitcoin/jobs/750850498). I've put together an updated patch that should be the equivalent change here: https://github.com/fanquake/bitcoin/commit/bd943d195903edcb8a4464eeed22871326e42be8.

**Comment by MarcoFalke** [comment]
Thanks. ci macos cross build now passing

**Comment by fanquake** [comment]
Going to close this for now, giving the commit being backported here is being reverted in #20855.

**Comment by MarcoFalke** [comment]
From IRC: `[20:35] <jonasschnelli> 0.19.2rc1 works also (with apples macOS 11 codesign)`, so this isn't needed

**Pull request closed without merging**
