### PR TITLE
doc: clean out release notes post branch-off

### PR DESCRIPTION
**Pull request by fanquake**
Should probably be done, given we've already had a PR add a release note for 23.0 (#22407).

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Remove `# Release notes now being edited on https://github.com/bitcoin-core/bitcoin-devwiki/wiki/22.0-Release-Notes-draft`?

**Comment by fanquake** [comment]
> Remove # Release notes now being edited on https://github.com/bitcoin-core/bitcoin-devwiki/wiki/22.0-Release-Notes-draft?

Done

**Comment by laanwj** [comment]
Do we need to get rid of the fragments too?
```
release-notes-14941.md
release-notes-14982.md
```

**Comment by MarcoFalke** [comment]
ACK 2ce7f95d4a1583bf0090a3fc1f5d1aba9c1d1b06

**Comment by MarcoFalke** [comment]
I couldn't find them:

```
$ git ls-files|grep release-notes-14|wc
      0       0       0

**Comment by fanquake** [comment]
> release-notes-14941.md

I'm not seeing either of those files in the master branch.

**Comment by laanwj** [comment]
Me neither, apparently they were local files only. ACK.

**Pull request merged**
