### PR TITLE
refactor: Rename signal TransactionRemovedFromMempool to better describe behavior

### PR DESCRIPTION
**Pull request by instagibbs**

### CODE REVIEW

**Comment by MarcoFalke** [comment]
why not as a scripted diff?

**Comment by instagibbs** [comment]
Because I had to learn the tool :smirk:

**Comment by fanquake** [comment]
> Because I had to learn the tool 😏

Looks like you didn't do a very good job 😏

```bash
Running script for: bf36bc9369a86198c0f24871dadc168f9db6fa7c

git grep -l 'TransactionRemovedFromMempool' | xargs sed -i 's/TransactionRemovedFromMempool/TransactionRemovedFromMempoolNotConfirmed/g'

diff --git a/src/wallet/wallet.cpp b/src/wallet/wallet.cpp

index 8eec00993..4d67cac72 100644

--- a/src/wallet/wallet.cpp

+++ b/src/wallet/wallet.cpp

@@ -1829,7 +1829,7 @@ bool CWalletTx::SubmitMemoryPoolAndRelay(std::string& err_string, bool relay)

     //

     // Irrespective of the failure reason, un-marking fInMempool

     // out-of-order is incorrect - it should be unmarked when

-    // TransactionRemovedFromMempool fires.

+    // TransactionRemovedFromMempoolNotConfirmed fires.

     bool ret = pwallet->chain().broadcastTransaction(tx, pwallet->m_default_max_tx_fee, relay, err_string);

     fInMempool |= ret;

     return ret;

Failed
```

 Also please add a PR description.

**Comment by instagibbs** [comment]
I'll learn the tool in a new life I guess

**Pull request closed without merging**
