### PR TITLE
doc: Update tor.md for notes on how to preserve v2 urls (with a not recommended note)

### PR DESCRIPTION
**Pull request by nolim1t**
Add the the text from the [release notes](https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-0.21.0.md) to the actual documentation `docs/tor.md` to document how users can preserve their old address.

Just in case users would like for some reason to preserve their existing v2 address with a not recommended text.

### CODE REVIEW

**Comment by jonatack** [comment]
Thanks @nolim1t. Unless this change is backported to 0.21.1, by the time 22.0 (the next release) is out tor v2 will be EOL, so maybe the existing release notes are enough. It may be good to squash your commits down to one when you are finished.

**Review by lehuuhieu7777 — APPROVED** [review]

**Comment by nolim1t** [comment]
> Thanks @nolim1t. Unless this change is backported to 0.21.1, by the time 22.0 (the next release) is out tor v2 will be EOL, so maybe the existing release notes are enough. It may be good to squash your commits down to one when you are finished.

Squashed into one. Yep I recognize that it may be deprecated too, hence not recommended mention

**Comment by laanwj** [comment]
We're on the trailing edge of TorV2 support here, and this is a really hacky workaround. I too think that the mention in the release notes is enough. No strong objection though.

**Review by jarolrod — COMMENTED** [review]
Concept 0 on this, I think there's no need to mention this as it is will be mandatory to migrate to torv3 since support for v2 addresses will be disabled on the network, see [Tor Deprecation Timeline](https://blog.torproject.org/v2-deprecation-timeline)

**Comment by laanwj** [comment]
I'm going to close this, sorry. Everyone is at most ~0 on this, which makes it unlikely that this will be merged. It doesn't seem worth the hassle to rebase .

**Pull request closed without merging**
