### PR TITLE
Fix chainstate serialized_size computation

### PR DESCRIPTION
**Pull request by sipa**
This was introduced in #6650 by a cherry-picked commit of mine.

### CODE REVIEW

**Comment by CodeShark** [comment]
ACK

**Comment by sipa** [comment]
Seems we have tests that test for the incorrect behaviour?

**Comment by dcousens** [comment]
ACK

**Comment by gmaxwell** [comment]
ACK / Tested ACK.  Also ... tests are not very meaningful if an effort isn't put in to verify that they're actually testing something. :(

**Comment by jonasschnelli** [comment]
Tests require an update.
https://github.com/bitcoin/bitcoin/blob/master/qa/rpc-tests/blockchain.py#L46
`bytes_serialized` is no longer 130'000 bytes 
https://travis-ci.org/bitcoin/bitcoin/jobs/86716075#L4329

**Comment by laanwj** [comment]
ACK after test fixed

**Comment by jgarzik** [comment]
ditto @laanwj - ACK after test fixed

**Comment by sipa** [comment]
Test should be fixed, and fix was tested.

**Pull request merged**
