### PR TITLE
Remove bad chain alert partition check

### PR DESCRIPTION
**Pull request by btcdrak**
As per meeting 2016-03-31 https://bitcoincore.org/en/meetings/2016/03/31/#bad-chain-alerts

The partition checker was producing huge number of false-positives and was disabled in 0.12.1 on the understanding it would either be fixed in 0.13 or removed entirely from master if not.

### CODE REVIEW

**Comment by sdaftuar** [comment]
Duplicate of #8241?

**Comment by MarcoFalke** [comment]
You are also removing the tests, so something like  #7568 would require to add them back later.

**Comment by btcdrak** [comment]
Not a duplicate, this is deliberate and should replace #8241: we disabled the alerts for 0.12.1 and agreed the partition alert code would be removed 0.13.0 if it wasnt fixed satisfactorily in #7568.

**Comment by laanwj** [comment]
Yes removing the code entirely is a more final option, though it could be re-added if something better pops up.

Which to choose that depends. If this is just due to lack of review time / too many high-priority issues pre-0.13, which was my guess, it makes sense to postpone the deadline to 0.14 and do #8241 in the meantime. 

But if it is considered a bad, broken idea and no one is motivated to look at this at all, it's better to remove it and do this.

**Comment by petertodd** [comment]
It's not like we're deleting it from git history, and disabled code has a tendency to break further anyway.

Concept ACK

**Pull request merged**
