### PR TITLE
Revert "travis: temporarily disable qt to avoid timeouts"

### PR DESCRIPTION
**Pull request by maflcko**
~~Should be safe to revert now, I assume?~~

~~Edit: Initially this timed out, but it seems this does no longer timeout as of today...~~

~~Good to merge?~~

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Hmm, the 50 min timeout triggered during the rpc tests. I think there are two options:

* Request travis to bump the timeout to 70 min
* Temporarily disable rpc tests

**Comment by MarcoFalke** [comment]
It seems this does no longer timeout as of today...

Good to merge?

**Comment by laanwj** [comment]
@theuni Is this ok to do now?

**Comment by theuni** [comment]
Not yet. It's building quickly now because it's been incrementally cached. The issue will be fresh builds with no cache (#7165 as an example, which will essentially be a complete rebuild).

I think we should work on speeding up tests first. I played around with parallelizing the rpc tests yesterday with reasonable success.

Additionally, https://github.com/travis-ci/travis-build/pull/706#issuecomment-214880848 will buy us a few extra minutes, as we'll be able to switched to the stripped down image that should startup quicker.

@MarcoFalke to see where we stand, you could try merging #7165 in here and seeing how long it takes.

**Comment by laanwj** [comment]
Maybe we can build against the platform qt in the meantime?
The qt tests aren't very worthwhile, but building against qt was a good way to make sure a full compilation still works.

**Comment by MarcoFalke** [comment]
Concept NACK per above discussion but I am leaving this open as an issue to indicate something needs to be done here.

**Pull request closed without merging**
