### PR TITLE
[trivial] fixing multiple typos

### PR DESCRIPTION
**Pull request by calebogden**

### CODE REVIEW

**Comment by paveljanik** [comment]
ACK after squashing into one commit.

**Comment by dcousens** [comment]
trivial ACK @ f85d3d7, please squash

**Comment by fanquake** [comment]
Nack as is. If you are going to correct them please fix them all. All in torcontrol.cpp
```
    connected is the handler that is called when connection is succesfully established.      [position 82:67]	
    LogPrint("tor", "tor: Succesfully connected!\n");      [position 180:31]	
    Callback after succesful connection      [position 383:24]	
    LogPrint("tor", "tor: ADD_ONION succesful\n");      [position 422:41]	
    LogPrint("tor", "tor: Authentication succesful\n");      [position 451:46]	
    LogPrint("tor", "tor: SAFECOOKIE authentication challenge succesful\n");      [position 504:67]	
```

**Comment by jonasschnelli** [comment]
agree with @fanquake: would be nice to fix all of them.
Once fixed, ACK after squashing.

**Comment by calebogden** [comment]
@fanquake @jonasschnelli Ah yeah sorry I thought I grabbed those too, fixed!

**Comment by MarcoFalke** [comment]
utACK 0331aa3

**Comment by dcousens** [comment]
utACK 0331aa3

**Comment by paveljanik** [comment]
trivial ACK https://github.com/bitcoin/bitcoin/commit/0331aa350c04253f3b94604a0152042646fc94bb

**Comment by fanquake** [comment]
ACK 0331aa3

**Pull request merged**
