### PR TITLE
depends: biplist 1.0.3

### PR DESCRIPTION
**Pull request by fanquake**
biplist should now be usable for reproducible builds without any patching.

One change has been incorporated,  the two remaining changes were rejected upstream: https://bitbucket.org/wooster/biplist/pull-requests/9/make-biplist-ordering-deterministic/diff#comment-None

testing on gitian cc @jonasschnelli

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Gitian Build: https://bitcoin.jonasschnelli.ch/build/532

**Comment by laanwj** [comment]
utACK 4ef82f1

**Comment by MarcoFalke** [comment]
> @jonasschnelli  Gitian Build: https://bitcoin.jonasschnelli.ch/build/532

Please note that the osx build failed with

```
curl: (28) Resolving timed out after 10524 milliseconds
```

**Comment by MarcoFalke** [comment]
@jonasschnelli This is still an issue with your osx nightly builds:

https://bitcoin.jonasschnelli.ch/builds/551/build_osx.log

Mind taking a look?

**Pull request merged**
