### PR TITLE
Do not absolutely protect local peers and make eviction more aggressive.

### PR DESCRIPTION
**Pull request by gmaxwell**
With automatic tor HS support in place we should probably not be providing
 absolute protection for local peers, since HS inbound could be used to
 attack pretty easily.  Instead, this counts on the latency metric inside
 AttemptToEvictConnection to privilege actually local peers.

This change also makes eviction generally more aggressive by making it
 willing to evict the unprotected peer in a netgroup, if the new
 connection comes from a netgroup where we have no unprotected peers.

It also makes sure that in the case of tying group size to select the
 group with the newest member, since newest time is the final selection
 criteria.

The third commit protects four peers that most recently sent us a valid
 transaction to our memory pool.  This metric is costly for attackers to
 control since it requires sending acceptable transactions, and an
 attacker which is blocking transactions is inherently disadvantaged for this
 criteria.

### CODE REVIEW

**Comment by pstratem** [comment]
concept ACK

**Comment by pstratem** [comment]
I would split this into two commits:
* removing the protection for localhost and adding the youngest member criteria
* another adding the more aggressive disconnect based on peer groups

**Comment by gmaxwell** [comment]
@pstratem Okay, I split it up.

I wanted to get something in that distinguishes good onion peers from bad;  ultimately I want to add peer POW to this, but thats a non-trivial amount of work.  So right now TXs are at least something.

It would be good to add blocks too, though that block addition pipeline makes it a little hard to avoid crediting people from sending duplicate blocks.

**Comment by petertodd** [comment]
Concept ACK

Will look at code after rebase.

**Comment by laanwj** [comment]
As #7438 was merged into 0.12, this needs to go in before 0.13, otherwise there will be a regression

**Comment by MarcoFalke** [comment]
Needs rebase if still relevant. (c.f. #7453)

**Pull request closed without merging**
