### PR TITLE
[Qt] minor optimisations in peertablemodel

### PR DESCRIPTION
**Pull request by Diapolo**
- remove an unneeded include of net.h in peertablemodel.cpp
- add const after size() in PeerTablePriv
- remove 2x unneeded else in functions
- replace a (int) typecast by (QVariant) to use Qt style

### CODE REVIEW

**Comment by paveljanik** [comment]
Can you please remove { and } in a one-line ifs?
utACK

**Comment by Diapolo** [comment]
@paveljanik @laanwj most of the time prefers { and } even for one-line ifs :).

**Comment by jonasschnelli** [comment]
I agree with @paveljanik: most one line ifs are without brackets and i think this is according to our code style / clang style.

**Comment by Diapolo** [comment]
@paveljanik @jonasschnelli Changed into one-line ifs :).

**Comment by Diapolo** [comment]
@paveljanik @jonasschnelli @laanwj Do I get some ACKs, this should be easy to merge :).

**Comment by paveljanik** [comment]
utACK
I think such changes should go to trivial...

**Comment by jonasschnelli** [comment]
utACK

**Comment by jonasschnelli** [comment]
ACK

**Comment by Diapolo** [comment]
@laanwj Can you please merge this trivial stuff :)?

**Comment by Diapolo** [comment]
@laanwj Ping once more.

**Comment by Diapolo** [comment]
@jonasschnelli IMHO, if we still support the GUI, we need another person wo is willing or able to merge GUI pulls... it's currently frustrating!

**Comment by MarcoFalke** [comment]
>merge GUI pulls

It seems cosmetic-only changes to the source code usually get rejected? (#6511)

Still, utACK from me.

**Pull request merged**
