### PR TITLE
build: produce Windows GUI build with Cirrus CI

### PR DESCRIPTION
**Pull request by wu-emma**
This PR is a build of Bitcoin Core for Windows with Cirrus CI. It creates executable files,
including bitcoin-qt.exe and packs them to NSIS installer .exe file.

It's built using MSVC toolchain with the solution files from build_msvc, so the
commands in the task are different than ones used in CI folder.

Please consider this as a prototype, if making builds from single CI system could
be counted as simpler approach. In such case I would make changes according to feedback and
some refactoring should still be required.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
How does this compare to #21551 ?

**Comment by wu-emma** [comment]
Sorry, I didn't noticed #21551 somehow. The main difference is producing of installer .exe file.

**Comment by laanwj** [comment]
What is your reasoning behind creating a new kind of installer in the integration tests? I don't think this makes sense for us, to to add testing for the windows installer, it'd need to be built in the same way as the gitian distribution one.

**Comment by wu-emma** [comment]
We are using only Cirrus CI for experimental BTC-derived project Bitgesell and at the time didn't saw Marco's PR, so decided to share the code for Bitcoin Core. Wondering why both AppVeyor and CirrusCI are used, like to have greater unification of auto testing and building. By the way, testing of windows install/uninstall looks like a great idea, would think about it.

**Comment by fanquake** [comment]
Doesn't seem to be heaps of motivation here, lets start with #21551. Going to close this for now.

**Pull request closed without merging**
