### PR TITLE
rest.cpp: change HTTP_INTERNAL_SERVER_ERROR to HTTP_BAD_REQUEST

### PR DESCRIPTION
**Pull request by djpnewton**

### CODE REVIEW

**Comment by fanquake** [comment]
The rest.py test is failing.
Travis output:
```
rest.py:
Initializing test directory /tmp/testcuky3r1q/27
start_node: bitcoind started, waiting for RPC to come up
start_node: RPC succesfully started
start_node: bitcoind started, waiting for RPC to come up
start_node: RPC succesfully started
start_node: bitcoind started, waiting for RPC to come up
start_node: RPC succesfully started
Mining blocks...
Assertion failed: 400 != 500
Stopping nodes
Not cleaning up dir /tmp/testcuky3r1q/27
Failed
stderr:
   File "/home/travis/build/bitcoin/bitcoin/qa/rpc-tests/test_framework/test_framework.py", line 150, in main
    self.run_test()
  File "/home/travis/build/bitcoin/bitcoin/build/../qa/rpc-tests/rest.py", line 182, in run_test
    assert_equal(response.status, 500) #must be a 500 because we send a invalid json request
  File "/home/travis/build/bitcoin/bitcoin/qa/rpc-tests/test_framework/util.py", line 504, in assert_equal
    raise AssertionError("%s != %s"%(str(thing1),str(thing2)))
Pass: False, Duration: 8 s

```

**Comment by djpnewton** [comment]
thanks, updated now

**Comment by dcousens** [comment]
concept ACK

**Comment by jonasschnelli** [comment]
Concept ACK.
It's a tiny API change and maybe adding a short passage to the release notes could make sense.

**Comment by dcousens** [comment]
@jonasschnelli especially if people were checking the error codes that came back

**Comment by djpnewton** [comment]
I added a line to the release notes.

..initially it seemed like such a simple change at the time =)

**Comment by laanwj** [comment]
Changing APIs is always difficult (because it's partially a social problem), but the new codes make more sense, thanks for sticking with it. utACK https://github.com/bitcoin/bitcoin/pull/8638/commits/f012a857f5e9b3bdd11a64dd0c16b4c805076594

**Comment by jgarzik** [comment]
ut ACK

**Pull request merged**
