### PR TITLE
[0.16.1] Remaining backports

### PR DESCRIPTION
**Pull request by maflcko**

### CODE REVIEW

**Comment by jnewbery** [comment]
Tested ACK 08334b73be031485a41e2c0647c2df1aa13c6316

**Comment by achow101** [comment]
utACK 08334b73be031485a41e2c0647c2df1aa13c6316

**Comment by sipa** [comment]
utACK 08334b73be031485a41e2c0647c2df1aa13c6316

**Comment by laanwj** [comment]
utACK 08334b73be031485a41e2c0647c2df1aa13c6316

**Pull request merged**
