### PR TITLE
windows: Add testnet link to installer

### PR DESCRIPTION
**Pull request by laanwj**
Implements #8251

testnet

@jonasschnelli I'm not sure what tooling you used in 4c23743, but for some reason icotool, even though I've used the same sizes/bit depths as you, manages to produce a huge icon file:

```
  57964 Feb 18  2015 bitcoin.ico
 295606 Jun 29 13:01 bitcoin_testnet.ico
```

```
$ icotool -l bitcoin.ico > /tmp/bitcoin.lst
bitcoin.ico: clr_important field in bitmap should be zero
bitcoin.ico: clr_important field in bitmap should be zero
bitcoin.ico: clr_important field in bitmap should be zero
$ icotool -l bitcoin_testnet.ico > /tmp/bitcoin_testnet.lst
$ diff -du /tmp/bitcoin.lst /tmp/bitcoin_testnet.lst
[no output]
$ cat /tmp/bitcoin.lst
--icon --index=1 --width=48 --height=48 --bit-depth=4 --palette-size=16
--icon --index=2 --width=32 --height=32 --bit-depth=4 --palette-size=16
--icon --index=3 --width=16 --height=16 --bit-depth=4 --palette-size=16
--icon --index=4 --width=48 --height=48 --bit-depth=8 --palette-size=256
--icon --index=5 --width=32 --height=32 --bit-depth=8 --palette-size=256
--icon --index=6 --width=16 --height=16 --bit-depth=8 --palette-size=256
--icon --index=7 --width=256 --height=256 --bit-depth=32 --palette-size=0
--icon --index=8 --width=48 --height=48 --bit-depth=32 --palette-size=0
--icon --index=9 --width=32 --height=32 --bit-depth=32 --palette-size=0
--icon --index=10 --width=16 --height=16 --bit-depth=32 --palette-size=0
```

Comparing binary, it looks like it's not using PNG compression inside the icon.

It also looks like it's picking a smaller and lower-depth icon than it should.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
utACK.
An optimized version of the testnet icon can be found here: https://github.com/jonasschnelli/bitcoin/commit/6473d7305389f714eabdf30bd9c5ac176b8cd137

I'm using the OSX "Icon Slate" app.

**Comment by laanwj** [comment]
Gah, seems I did something wrong while changing the color:
testnet2

What I did was take the 256x256 image and re-create all the other levels from that. But it looks like the smaller levels have relatively different amounts of whitespace? at least that would explain the differently-sized icon.

**Comment by jonasschnelli** [comment]
@laanwj: hmm..
I just re-created the testnet icon with the same properties like the mainnet icon: https://github.com/jonasschnelli/bitcoin/commit/d188c85e5ced31da39f76ed7aacad582d02cae72

Maybe this one is more in align.

**Comment by laanwj** [comment]
Unfortunately that one has a white block around it, and seems even smaller :(

testnet3

**Comment by laanwj** [comment]
Pushed an icon that has the right properties and size - rotated the hue with 70 degrees for every level of the icon individually.

testnet4

Could use file size optimization though :)

**Comment by jonasschnelli** [comment]
Tested ACK (on Windows 10).
bildschirmfoto 2016-06-30 um 14 52 36

**Comment by sipa** [comment]
Concept ACK, and the screenshots look good.

However, I don't understand how the second .lnk file is associated with the new icon.

**Comment by laanwj** [comment]
> Tested ACK (on Windows 10).

The new icon still needs optimization, would you be willing to do this?

> However, I don't understand how the second .lnk file is associated with the new icon.

It's told to grab icon index 1 from the exe:
```
    CreateShortcut "$SMPROGRAMS\$StartMenuGroup\@PACKAGE_NAME@ (testnet, @WINDOWS_BITS@-bit).lnk" "$INSTDIR\@BITCOIN_GUI_NAME@@EXEEXT@" "-testnet" "$INSTDIR\@BITCOIN_GUI_NAME@@EXEEXT@" 1
```

**Comment by jonasschnelli** [comment]
> The new icon still needs optimization, would you be willing to do this?

Sure. I guess this one should be fine:
https://bitcoin.jonasschnelli.ch/bitcoin_testnet.ico

**Comment by laanwj** [comment]
> Sure. I guess this one should be fine:

Added. Tested ACK, looks good now, and both icons are ~60kB.

**Pull request merged**
