### PR TITLE
test: Move wallet tests to wallet_*.py

### PR DESCRIPTION
**Pull request by maflcko**
The tests only tests the wallet and it doesn't make sense to extend it for other stuff, so clarify that.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Removed it from the list in https://github.com/bitcoin/bitcoin/issues/20078#issuecomment-1106586728

**Comment by MarcoFalke** [comment]
Pused to move two wallet tests to `wallet_*.py`, let me know if I forgot any

**Review by hernanmarino — COMMENTED** [review]
ACK  :+1:

**Review by pablomartin4btc — COMMENTED** [review]
cr ACK.
I see @Sjors's point, I still agree with this change as I'm also following the upgrading of tests to MiniWallet usage and this change conveys that intention.

**Comment by pablomartin4btc** [comment]
Since we are here, perhaps you could move `rpc_psbt.py` to `wallet_psbt.py` as you mentioned [here](https://github.com/bitcoin/bitcoin/issues/20078#issuecomment-1330753523).

**Comment by MarcoFalke** [comment]
Not sure, about half of it is testing the wallet, the other half not. Ideally the parts were split or the non-wallet parts wouldn't depend on a wallet, so I'll leave it for a follow-up  for now.

**Comment by MarcoFalke** [comment]
rebased

**Review by fanquake — APPROVED** [review]
ACK fa7d71acccab4e5b416c9dd1e2080a9652107f84

**Review by hernanmarino — APPROVED** [review]

**Review by pablomartin4btc — APPROVED** [review]
re-ACK https://github.com/bitcoin/bitcoin/commit/fa7d71acccab4e5b416c9dd1e2080a9652107f84

**Pull request merged**
