### PR TITLE
test: Use wait_until to ensure ping goes out

### PR DESCRIPTION
**Pull request by Empact**
Intermittent failure evident here:
https://travis-ci.org/bitcoin/bitcoin/jobs/344021180

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Could we instead get rid of the time.sleep with an arbitrary argument? That is just terrible practice. If it is necessary to wait on some predicate, you might use the wait_until helper function.

**Comment by Empact** [comment]
Sounds good to me, hadn't seen `wait_until`

**Comment by Empact** [comment]
Switched to using `wait_until` here. There are a few other uses of time.sleep for this sort of thing. I'll switch them over in another PR.

**Comment by conscott** [comment]
Tested 0eb84f30d80847b7392ad42b2d916eaf5923a63c ACK.

I also saw this issue last week, thanks for fix.

**Comment by MarcoFalke** [comment]
utACK 0eb84f30d8

**Pull request merged**
