### PR TITLE
Fixed a couple small grammatical errors.

### PR DESCRIPTION
**Pull request by BitsInMyBlood**
1. "If a pull request is not to be considered for merging (yet), please
prefix the ..."

2. If a particular commit references another issue, please add the reference. For
example: `refs #1234` or `fixes #4321`.

### CODE REVIEW

**Comment by fanquake** [comment]
utACK f927ee1

**Comment by promag** [comment]
utACK f927ee1.

Nit, could drop the period from commit message and PR title. There is no need to detail the commit message too (patch is pretty simple).

**Comment by BitsInMyBlood** [comment]
Forgive me, I'm new to contributing and am just trying to help. Any advice
is encouraged and appreciated.

**Comment by practicalswift** [comment]
utACK f927ee1aa871b1bd4c5ab2b218d0ea27ef9fff19. Nice first-time contribution!

**Comment by BitsInMyBlood** [comment]
You have no idea how appreciated your response is...

**Comment by MeshCollider** [comment]
LGTM, ACK https://github.com/bitcoin/bitcoin/commit/f927ee1aa871b1bd4c5ab2b218d0ea27ef9fff19

**Comment by laanwj** [comment]
ACK f927ee1

**Comment by BitsInMyBlood** [comment]
Deleting deprecated branch due to merge

**Pull request merged**
