### PR TITLE
test: whitelist rpc_rawtransaction peers to speed up tests

### PR DESCRIPTION
**Pull request by jonatack**
Speed up the somewhat slow `rpc_rawtransaction.py` test by more than 3x (from 45-55 seconds to 15 seconds on a laptop running 2 x 2.5GHz).

### CODE REVIEW

**Comment by jonatack** [comment]
(First commit from #22437).

**Review by kristapsk — APPROVED** [review]
ACK a3d6ec5bb567481a634638cea7ae37c355119a7b

**Review by theStack — APPROVED** [review]
ACK a3d6ec5bb567481a634638cea7ae37c355119a7b 🐎

**Review by brunoerg — APPROVED** [review]
tACK a3d6ec5bb567481a634638cea7ae37c355119a7b

From 01:12:77 to 00:24:92

**Comment by mjdietzx** [comment]
ACK a3d6ec5bb567481a634638cea7ae37c355119a7b

**Pull request merged**
