### PR TITLE
ci: Rename tasks (previous releases, macOS cross)

### PR DESCRIPTION
**Pull request by maflcko**
The previous releases task no longer uses the qt5 dev package, but the depends package, so fix that in the name.

Also, remove a detail from the macOS cross task name, because anyone can look it up in the source, if they really want to. Otherwise, it may go out of date in the name.

Also, rename the two tasks' config file to reflect the same.

### CODE REVIEW

**Review by fanquake — APPROVED** [review]
ACK fa0c594b33970e12d97e6879ab4ca57045453492

**Review by hebasto — COMMENTED** [review]
Post-merge ACK fa0c594b33970e12d97e6879ab4ca57045453492.

@maflcko 

Thank you for addressing https://github.com/bitcoin/bitcoin/pull/29203#discussion_r1446339387.

**Comment by ryanofsky** [comment]
Mostly just asking for curiousity, since I guess I can rebase, but in some of my PR's I see:

```sh
./ci/test/00_setup_env.sh: line 33: ./ci/test/00_setup_env_native_qt5.sh: No such file or directory
```

https://cirrus-ci.com/task/5895775641665536
https://cirrus-ci.com/task/5238795365253120

And I'm confused about why this happens. Which cirrus is running, is it mixing and matching the cirrus configuration and scripts from different branches?

**Comment by ryanofsky** [comment]
Would it maybe make sense to have a wiki page with a reverse chronological list of known CI failures? I think it would be useful to have a simple place to check if there is a known issue when a CI job is failing, but I'm not sure if it would create a maintenance burden.

**Comment by ryanofsky** [comment]
> a new label can be added, if a dedicated "category" is needed

I think this would be great. Ideally there would just be some link you could go to quickly see recent known CI failures and what the expected error messages look like.

This could avoid the need to debug and search for fragments of error messages when CI tasks are failing. I think a filtered issue list would work just as well as a wiki page (but I might experiment with creating a wiki page anyway since I'm about to go through my own PRs and take some notes on what's failing).

**Pull request merged**
