### PR TITLE
[Qt] remove std namespace polution from code

### PR DESCRIPTION
**Pull request by Diapolo**

### CODE REVIEW

**Comment by paveljanik** [comment]
ACK

**Comment by jonasschnelli** [comment]
Hmm.. is this a complete transition to namespaceless of the whole QT part? If not, what is the reason to only adapt these files?
The PR itself looks good to me but i would also say that this is a "no-code" change and could go in over trivial@theuni.

**Comment by Diapolo** [comment]
This covers the whole Qt part!

**Comment by laanwj** [comment]
Verified that this removes all `using namespace` from the GUI implementation files. Which is not terribly useful, it's mostly important to avoid it in *headers* but anyhow. utACK.

**Pull request merged**
