### PR TITLE
refactor: Split logging utilities from system.h

### PR DESCRIPTION
**Pull request by sedited**
This pull request is part of the `libbitcoinkernel` project https://github.com/bitcoin/bitcoin/issues/24303 https://github.com/bitcoin/bitcoin/projects/18 and more specifically its "Step 2: Decouple most non-consensus code from libbitcoinkernel". These commits were originally authored by empact and are taken from their parent PR #25152.

#### Context

There is an ongoing effort to decouple the `ArgsManager` used for command line parsing user-provided arguments from the libbitcoinkernel library (https://github.com/bitcoin/bitcoin/pull/25290, https://github.com/bitcoin/bitcoin/pull/25487, https://github.com/bitcoin/bitcoin/pull/25527, https://github.com/bitcoin/bitcoin/pull/25862, https://github.com/bitcoin/bitcoin/pull/26177, and https://github.com/bitcoin/bitcoin/pull/27125). The `ArgsManager` is defined in `system.h`.

#### Changes

Next to providing better code organization, this PR removes some reliance of the tree of libbitcoinkernel header includes on `system.h` (and thus the `ArgsManager` definition) by moving some logging functions out of the `system.*` files.

Further commits splitting more functionality out of `system.h` are still in #25152 and will be submitted in separate PRs once this PR has been processed.

### CODE REVIEW

**Comment by fanquake** [comment]
Concept ACK

**Comment by davidgumberg** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/27238/commits/485ea8d400241506a6abe485b7b71b0cacfdc853

**Review by maflcko — APPROVED** [review]
review ACK 4aa0ec6a8617ac77a19e49d8cf081b7a7f6404ae 🐸

<details><summary>Show signature</summary>

Signature:

```
untrusted comment: signature from minisign secret key on empty file; verify via: minisign -Vm "${path_to_any_empty_file}" -P RWTRmVTMeKV5noAMqVlsMugDDCyyTSbA3Re5AkUrhvLVln0tSaFWglOw -x "${path_to_this_whole_four_line_signature_blob}"
RUTRmVTMeKV5npGrKx1nqXCw5zeVHdtdYURB/KlyA/LMFgpNCs+SkW9a8N95d+U4AP1RJMi+krxU1A3Yux4bpwZNLvVBKy0wLgM=
trusted comment: review ACK 4aa0ec6a8617ac77a19e49d8cf081b7a7f6404ae 🐸
Q9UDjbl3uLbiI3hg8GAjCLa+KcpMXFHY4zmCz2T39dQ6BsSrY7132Xgo9wCcDbaRQQsRJs5AfEjE9uCDi9P0AA==
```

</details>

**Comment by TheCharlatan** [comment]
Updated  [4aa0ec6](https://github.com/bitcoin/bitcoin/pull/27238/commits/4aa0ec6a8617ac77a19e49d8cf081b7a7f6404ae) -> aaced5633b81b2f08b993106a527e2a0e1d663c1 ([splitSystemLogging_0](https://github.com/TheCharlatan/bitcoin/tree/splitSystemLogging_0) -> [splitSystemLogging_1](https://github.com/TheCharlatan/bitcoin/tree/splitSystemLogging_1), [compare](https://github.com/TheCharlatan/bitcoin/compare/splitSystemLogging_0..splitSystemLogging_1))  to fix header inclusion order addressing @MarcoFalke's https://github.com/bitcoin/bitcoin/pull/27238#pullrequestreview-1337368491.

**Comment by Empact** [comment]
Thanks @TheCharlatan for picking this up. 👍

**Pull request merged**
