### PR TITLE
[GUI] - Reintroduce menu icons

### PR DESCRIPTION
**Pull request by GChuf**
Reintroduce old icons back to the menu
Add new icons to the menu

### CODE REVIEW

**Comment by GChuf** [comment]
I know we've had lengthy discussions, but I still decided to open a PR after @luke-jr's comments.
I'd also like to mention @emilengler who had the original idea of replacing the "Open URI" icon, which I included here.
The "filesave" icon remains as it was.

The only 2 options that don't have any icons right now are the "Restore" and "Main Window", both of them which don't do anything for me on linux or windows, so I didn't really know what to put there. If they dont do anything, I was thinking about removing them for linux and windows builds.

See the previews below.

file
help
settings
window

**Comment by luke-jr** [comment]
IMO Open/Close Wallet look too much alike. On my text editor, close file has a document (no folder) with an X in the corner - but not sure if that's appropriate for a wallet.

The 'i' for Command-line options was hard to make out. I think it's too much serif for the size?

From the main window (ie, not system-wide menu), Restore/Main Window seem like no-ops. I'm not sure how to best detect that, but it seems outside the scope of this PR. For icon-making purposes: Restore would un-minimise / bring to front, and Main Window would switch to the main window specifically.

Sending/Receiving addresses are too hard to differentiate. Maybe fill in the arrows and make them simpler?

**Comment by emilengler** [comment]
Concept ACK,
like I mentioned it earlier I think menu icons are necessary for accessibility

**Comment by jonasschnelli** [comment]
Ref: #16612 
NACK and sorry for directly closing
This is bikeshed-back-and-forth territory which I'm not going to support.

If you want to improve the UI (which would be highly welcome), I recommend spending time working on something that makes a difference.

> like I mentioned it earlier I think menu icons are necessary for accessibility

I do very much doubt that. One of the platforms with the best accessibility support is macOS and there are no menu icons,.. really nowhere.

**Comment by GChuf** [comment]
All due respect and no ill will intended: since I'm not a programmer, dealing with these issues is not bikeshedding for >me<, and I wouldn't be doing this if I haven't thought this was helpful - I myself still look at the icons and not text (therefore this PR is also kind of a "scratch your own itch" thing). Furthermore, macOS isn't all that popular throughout the world, I believe.

I genuinely just want to help the project in ways that I can. For me, and some others, this _would_ make a difference - please do not think that everyone thinks like you (programmers) do.

Any way, if this stays closed, I'll leave the icons behind.

**Comment by emilengler** [comment]
There are other ways to contribute like translations :)

**Comment by jonasschnelli** [comment]
@GChuf: I see your point and I appreciate your intention to help. #16612 had relatively broad support which makes me believe that this PR will be a waste of time for no good reason. That's why I think cut harsh, save everyone's time, is the right approach.  

> Furthermore, macOS isn't all that popular throughout the world, I believe.

Totally. I just responded to @emilengler statement that icons are *necessary* for accessibility which IMO is wrong.

>  There are other ways to contribute like translations :)

What really would be awesome if someone would take care of good UX. I don't mean changing a bunch of icons... I more mean thinking the whole thing through, starting with a great concept, etc.

**Comment by luke-jr** [comment]
@jonasschnelli It's completely unreasonable for macOS and GNOME users to force macOS/GNOME UI design choices on everyone else. Recuse yourself.

**Comment by emilengler** [comment]
@luke-jr IMO if we use Qt we should stick more with KDE I think if there are any design guidelines

**Comment by luke-jr** [comment]
Sure, although half the point of Qt is to be desktop-neutral (and Qt apparently does so by hiding menu icons on platforms without them).

**Comment by emilengler** [comment]
Yes but KDE apps are a concrete example of Qt apps I think

**Comment by GChuf** [comment]
I'd have to agree with @luke-jr that it's unreasonable for macOS/GNOME users to decide on design for other platforms. It seems as though there are a lot of macOS users here - that might explain the general dislike for the idea of menu icons. I now understand what people were referring to when they said "good design practice" - in other words, it doesnt refer to "good design", but on macOS design ... not quite the same thing, I would argue.
Therefore it seems like the solution would be to leave this decision to windows/linux/... users, and leave macOS without icons.

Regarding luke's review, I agree with what you said.
Regarding emil's comment - I've done extensive work regarding translations in august ... you can check transifex's dashboard.

**Comment by luke-jr** [comment]
[KDE HIG: "Provide icons for all menu items. Don’t re-use the same icon for multiple items."](https://hig.kde.org/components/navigation/menubar.html)

**Comment by luke-jr** [comment]
@GChuf How about using theme-provided icons where practical? https://doc.qt.io/qt-5/qicon.html#fromTheme

**Comment by jonasschnelli** [comment]
> I'd have to agree with @luke-jr that it's unreasonable for macOS/GNOME users to decide on design for other platforms.

No one said that. I only said that it's not true that you need Icon for accessibility and made an example about macOS.

We removed the menu icons in #16612. We had 7 acks for that. Working on bringing them back is extremely likely a waste of time...  up to you if you want to continue on this... but I strongly recommend to not waste precious contributors time.

**Comment by GChuf** [comment]
@luke-jr i'm not sure about theme-provided icons - honestly, this is out of my depth. From what I understand, adding some theme icons would not be practical, as it would require additional code and work.
There'd also be problems with finding a theme that matches the current icons - unless we change every icon. Meanwhile, filling those arrows and replacing "i" for command line options wouldnt be hard at all. Not sure about open/close wallet.

@jonasschnelli I wasn't targeting you specifically. Working on the icons only to see the PR closed is a waste of time, can't argue with that. But merging this would also end the time-waste - as for the other reasons for not having icons, I can't say I agree with any of them.

**Comment by luke-jr** [comment]
> (especially since most(?) ACKs were from people who don't have icons on their menus)

That is my impression. People who don't use features shouldn't be ACKing their removal. It would be like bitcoind-only devs ACKing removal of the entire GUI...

**Comment by GChuf** [comment]
@luke-jr I've updated the sending/receiving address icons, and the "i" for command line options. 
Will post pictures of GUI and update commits later. But how do you think we should proceed?

**Pull request closed without merging**
