### PR TITLE
test: add test for corrupt wallet bdb logs

### PR DESCRIPTION
**Pull request by ryanofsky**
This PR adds a wallet test testing handling of corrupt BDB logs. It restores commit c6a2c265f5d0b424fc8226c2f3426e82856779d0 from #18907 which was dropped because it triggered a memory leak, which is reported as #19034

### CODE REVIEW

**Comment by ryanofsky** [comment]
Opened as draft PR to see if tests will pass now. If they do then #19034 can be closed and this can be reviewed and merged. Otherwise some more debugging will be required.

**Comment by jonasschnelli** [comment]
Approach ACK

**Comment by MarcoFalke** [comment]
@ryanofsky

**Comment by achow101** [comment]
I'm not sure that the issue this is trying to fix is really an issue, especially since we have BDB slated for removal.

**Comment by achow101** [comment]
Closing as this has been open as a draft for more than 2 years with basically no activity. The tests do not pass, nor does it appear that the issue has been fixed or will be fixed. The planned removal of BDB will also obsolete this test.

**Pull request closed without merging**
