### PR TITLE
doc: update docs for `CHECK_ATOMIC` macro

### PR DESCRIPTION
**Pull request by fanquake**
Clarify that supported versions of GCC are not affected, and that Clang
prior to version 15 still requires the explicit `-latomic` linking, when
compiling for 32-bit.

### CODE REVIEW

**Comment by fanquake** [comment]
Although not always, because the 32-bit CentOS build using GCC 11 compiled fine. Will adjust the docs.

**Comment by fanquake** [comment]
Clang prior to version 15, when compiling for 32-bit, is the culprit here (I misread the CI). Have updated the docs.

**Comment by hebasto** [comment]
Not directly related to this PR patch, but...

At some point in the future, the Bitcoin Core project will drop support for i686 platforms. It looks unreasonable to run the modern Bitcoin Core on CPUs without instruction sets for h/w optimizations etc. And the market is full of cheap alternatives.

By what criteria will we make such a decision?

Could this moment be now?

**Comment by fanquake** [comment]
> Could this moment be now?

Feel free to open an issue for broader discussion. Given the overhead of supporting it is low, I don't see a pressing reason to do so. There is also a difference between us officially dropping support, and purposefully breaking the ability to compile for certain targets.

**Review by hebasto — APPROVED** [review]
ACK ebc7063c80135dd6f3e7b9418e8f4bf217bd8db7.

**Comment by fanquake** [comment]
See also the CMake implementation of this check: https://github.com/hebasto/bitcoin/pull/50.

**Pull request merged**
