### PR TITLE
p2p, contrib: add cjdns hardcoded seeds and update the i2p seeds

### PR DESCRIPTION
**Pull request by jonatack**
This update targets the v23 release.  Additional reliable CJDNS seeds, and feedback on the I2P seeds, is welcome.  To verify `src/chainparamsseeds.h` locally, run:
```
contrib/seeds/generate-seeds.py contrib/seeds > src/chainparamsseeds.h
```

### CODE REVIEW

**Comment by laanwj** [comment]
Code review ACK bcc5676f16d86a2d271e0d822d836d9c47ef298b
I've verified that the new I2P node is connectable, and that the `generate-seeds` output matches. Also, the new entries for CJDNS have the correct BIP155 network type (6). I did not try to connect to CJDNS nodes.

**Review by lsilva01 — APPROVED** [review]
tACK bcc5676

I successfully connected to the I2P address added in `nodes_main.txt`.
I also successfully connected to CJDNS node `[fcc7:be49:ccd1:dc91:3125:f0da:457d:8ce]:8333`, but not to `[fc32:17ea:e415:c3bf:9808:149d:b5a2:c9aa]:8333`.

**Comment by jonatack** [comment]
> but not to `[fc32:17ea:e415:c3bf:9808:149d:b5a2:c9aa]:8333`

Thanks! That's me, and you are the second person to report today that I can't be connected to. Hm.

**Comment by jonatack** [comment]
> but not to `[fc32:17ea:e415:c3bf:9808:149d:b5a2:c9aa]:8333`

Thanks @lsilva01! Can you please re-try connecting? I think I've fixed the issue.

**Comment by lsilva01** [comment]
Sure. I am still getting the error  `connect() to [fc32:17ea:e415:c3bf:9808:149d:b5a2:c9aa]:8333 failed after wait: Permission denied (13)`.

**Comment by jonatack** [comment]
Sorry about that -- can you please try once again?

**Comment by jonatack** [comment]
Ok, resolved (thanks @vasild and @lsilva01 for testing), I have inbound CJDNS connections now.

**Comment by lsilva01** [comment]
reACK. I confirm that I have successfully connected to all seeds added in this PR.

**Pull request merged**
