### PR TITLE
qt: Show progress overlay when clicking spinner icon

### PR DESCRIPTION
**Pull request by laanwj**
Bring up the modal progress overlay when the user clicks the spinner icon in the task bar.

I think this is the intuitive thing to do when that icon is clicked.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Thanks for doing this!
I think it would be great if the modal progress overlay would show when the users presses on the sync progress bar in the task-bar.

**Comment by paveljanik** [comment]
It makes sense in IBD, but later when you are in sync with the network, the info there is almost useless and false in fact.

**Comment by laanwj** [comment]
> It makes sense in IBD, but later when you are in sync with the network, the info there is almost useless and false in fact.

Maybe it should only (ever) show during IBD and when catching up?

**Comment by sipa** [comment]
Concept ACK

**Comment by gmaxwell** [comment]
Concept ACK.

Perhaps just make the text at the top of that overlay display conditionally. (And otherwise perhaps display "your node appears to be up to date. The most recent received block is 12345 with timestamp X which you recieved Y minutes ago."

**Comment by fanquake** [comment]
How this currently functions:
giphy

**Comment by laanwj** [comment]
@fanquake Yep. Nice animation!

**Comment by jonasschnelli** [comment]
Tested ACK 042f9fa071fd76ab310cd47b73d0e620a7850660

**Comment by paveljanik** [comment]
This was merged a bit prematurely, I think.

The info present after being in sync with the network is nonsense. Just try it and imagine users reading it...

**Comment by laanwj** [comment]
Feel free to make it better. I wasn't intending to change the message in this pull, at least.

A simpler fix that I realized later is to only show it when the spinner is actually a spinner, and not when it is a "check" icon.

But I think this is ok for now, it's sort-of hidden functionality anyway.

**Comment by paveljanik** [comment]
> A simpler fix that I realized later is to only show it when the spinner is actually a spinner, and not when it is a "check" icon.

This is exactly what is needed. Please PR it. Thank you.
--  
Pavel Janík

**Comment by jonasschnelli** [comment]
Will try to add @paveljanik's/@laanwj's suggestions in #9280.

**Pull request merged**
