### PR TITLE
travis: add --enable-debug macos build

### PR DESCRIPTION
**Pull request by kallewoof**
The added configuration would have found #15233 before it happened. It may be worth to add other machine configs, but so far, only macs have croaked, so not going there yet.

### CODE REVIEW

**Comment by Sjors** [comment]
Are you sure this works? Wouldn't this try to run a macOS cross-compiled binary in a Linux environment? The other macOS machine doesn't run unit tests at all: `RUN_UNIT_TESTS=false`.

Maybe we should try out the native macOS Travis environment? https://docs.travis-ci.com/user/reference/osx/ (

cc @MarcoFalke

**Comment by promag** [comment]
Not sure if the cross-compile binary has the #15227 problem.

I think @Sjors has a good suggestion, more info in https://docs.travis-ci.com/user/multi-os/.

**Comment by MarcoFalke** [comment]
How is this a bug only on macos? I'd prefer to run the tests in bionic with clang (and whatever else macos uses)

**Comment by kallewoof** [comment]
I will do more tests to see if this solves the problem with the patch cherry-picked. I assumed it would, but you're right, maybe not. @MarcoFalke I think it only appeared for mac users.

**Comment by sipa** [comment]
This doesn't work, we can't run cross-compiled OSX binaries in the Linux build environment.

**Pull request closed without merging**
