### PR TITLE
Doc: Fix copypasted comment

### PR DESCRIPTION
**Pull request by paveljanik**
The deserialization stuff was copied from peers.dat...

### CODE REVIEW

**Comment by MarcoFalke** [comment]
I remember some rule that comments should not describe what the code does, but rather *why* the code does (some weird) stuff.

I don't think (de)serialization is weird, so you might as well remove those altogether?

**Comment by paveljanik** [comment]
@MarcoFalke I do not have problem with that. Will wait for other comments.

**Comment by jonasschnelli** [comment]
ACK f26da35142c1d8869cb171d3053aaf2ec3f6cca1.
I'm all in for better comments (can be a different PR).

**Comment by paveljanik** [comment]
Yes, in this case, it documents the contents of the file being read.

**Comment by MarcoFalke** [comment]
Fine, just going to merge this.

**Pull request merged**
