### PR TITLE
Deprecate `main` and `test` `-chain` params

### PR DESCRIPTION
**Pull request by katesalazar**
'Main' and 'test' is old terminology,
with which it seems 'signet' as a name has broken with.

Deprecate `main` and `test` `-chain` params in favor of
`mainnet` and `testnet`, in line with `signet`.

`main` and `test` shouldn't be removed from the source code
_until most users are unaffected by the removal_.

This supersedes #23068.

### CODE REVIEW

**Comment by michaelfolkson** [comment]
Leaning towards Concept NACK as the only upside appears to be making it prettier (I don't think this addresses any particular confusion) and don't think that upside is worth the short term disruption and invasive change.

**Comment by katesalazar** [comment]
> Leaning towards Concept NACK as the only upside appears to be making it prettier (I don't think this addresses any particular confusion) and don't think that upside is worth the short term disruption and invasive change.

Mhnmyea, I wouldna tried this if I knew it would expand this big.

**Comment by michaelfolkson** [comment]
:) I think [good first issues](https://github.com/bitcoin/bitcoin/labels/good%20first%20issue) would be a better starting point until you understand the codebase/project better.

**Comment by katesalazar** [comment]
Reading CI logs, I think at this point these changes spill out to
bitcoin configuration files (in
https://github.com/bitcoin/bitcoin/blame/16ccb3a1/doc/bitcoin-conf.md#L32
it's rejecting \[main\] and \[test\].

I hadn't intended that.

I'm not sure about the choice between shrinking scope or
keep pushing forward. I think it's best to keep pushing forward and
eventually break the PR into smaller pieces if it becomes too big to
be handled comfortably, but some maintainer wisdom is naturally
very welcome.

**Comment by katesalazar** [comment]
> :) I think good first issues would be a better starting point until you understand the codebase/project better.

Your good first issues are a mud of moshpit, CI stuff (only insiders control), OS specific stuff, vague and generic subjects, and stuff for ultra specialized developers. This project's approach to good first issues is quite wrong.

And then there's things like "Use C++17 std::clamp" (23095).

Luckily you are no short on developers.

**Comment by katesalazar** [comment]
test/functional/p2p_dos_header_tree.py failures are not very informative and
test/functional/feature_backwards_compatibility.py seems to require some
configuration efforts, so I expect no more progress here.

**Comment by katesalazar** [comment]
Currently pursuing locally a feeling that 22817 fixes
test/functional/feature_backwards_compatibility.py in
both my host and CI. 🤔

**Comment by Sjors** [comment]
Concept NACK. This will create headaches for years for only cosmetic benefit. The code that processes config files is already rather complicated and full of unpleasant backward compatibility quirks. See e.g. #15934

See also https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#refactoring

> Pull requests that refactor the code should not be made by new contributors. It requires a certain level of experience to know where the code belongs to and to understand the full ramification (including rebase effort of open pull requests).

**Comment by katesalazar** [comment]
Sjors: you are so right you almost convinced me. 😖

**Comment by meshcollider** [comment]
Hi @katesalazar, thank you very much for contributing! As others have said, unfortunately this change is a bit too nuanced to be worth the cosmetic change and has already received NACKs, so I'm going to have to close it sorry.

As michaelfolkson said, please do check out the `good-first-issue` tag for some good starting-point issues that you might like to help with 🙂 Look forward to further contributions in future!

**Pull request closed without merging**
