### PR TITLE
doc: Fix table syntax

### PR DESCRIPTION
**Pull request by cvengler**
Adjustment with whitespaces to other tables in the docs.
See 9b51b158fc42f2d5ad4fe161053e44e667d42fd6

### CODE REVIEW

**Comment by emilengler** [comment]
The travis fail has nothing to do with this PR see recent master logs

**Comment by hebasto** [comment]
I cannot see any visual difference for the rendered docs.

**Comment by emilengler** [comment]
@hebasto There is none, it is just an improvement to keep it coherent with the markdown syntax

**Comment by fanquake** [comment]
Thanks, however this isn't required. We also have other tables in the docs that don't use spacing.

**Pull request closed without merging**
