### PR TITLE
build: Propagate user-defined flags to host packages

### PR DESCRIPTION
**Pull request by hebasto**
On master (4f8b1f8759301d2553183e14f72444a0f1d80725) `{CPP,C,CXX,LD}FLAGS` that are specified in the command line are not propagated to packages:
```
$ make --no-print-directory -C depends print-libevent_cxxflags CXXFLAGS=-some-fancy-flag
libevent_cxxflags=-pipe -O2
```

This PR:
- propagates `{CPP,C,CXX,LD}FLAGS` to host packages:
```
$ make --no-print-directory -C depends print-libevent_cxxflags CXXFLAGS=-some-fancy-flag
libevent_cxxflags= -some-fancy-flag
```
- does not propagate `{CPP,C,CXX,LD}FLAGS` to native packages:
```
$ make --no-print-directory -C depends print-native_b2_cxxflags CXXFLAGS=-some-fancy-flag
native_b2_cxxflags=     
```
- actually addresses the https://github.com/bitcoin/bitcoin/pull/23551#issuecomment-973896518

### CODE REVIEW

**Comment by hebasto** [comment]
#### Guix builds:
```
$ find guix-build-$(git rev-parse --short=12 HEAD)/output/ -type f -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum
3cee4e32aa313571b0f7d9d43d0762d9fbce684c56ef1a7478f92a804781c3cd  guix-build-86ef828e1d0d/output/aarch64-linux-gnu/SHA256SUMS.part
75b63151b2ce0b7a56d6a37277c54f71f23eeb50d1fd79470e25ed2dda43e4fd  guix-build-86ef828e1d0d/output/aarch64-linux-gnu/bitcoin-86ef828e1d0d-aarch64-linux-gnu-debug.tar.gz
ebd38d798f46a4e95e082c92dc39ee96f6fc5022a7f2127cbc537c8c09575c1b  guix-build-86ef828e1d0d/output/aarch64-linux-gnu/bitcoin-86ef828e1d0d-aarch64-linux-gnu.tar.gz
55d783afce727971508987ff515c2cfd0b7c308f6c10c54c26eb914d3f6b2c8a  guix-build-86ef828e1d0d/output/arm-linux-gnueabihf/SHA256SUMS.part
0fe724fa127665f61ed8599adcbbfbdb102a273e9cd2058e6b332f215219f932  guix-build-86ef828e1d0d/output/arm-linux-gnueabihf/bitcoin-86ef828e1d0d-arm-linux-gnueabihf-debug.tar.gz
8bf7a6104f17d6b1c7306f3ad730e58ed20827aa51ff15a711629f439f0b6612  guix-build-86ef828e1d0d/output/arm-linux-gnueabihf/bitcoin-86ef828e1d0d-arm-linux-gnueabihf.tar.gz
b84a027900a7b2583b08e7fd4467b605bb9fc993315e2b06d888bc96d49fd225  guix-build-86ef828e1d0d/output/dist-archive/bitcoin-86ef828e1d0d.tar.gz
9669c19d60aff1733bc16ea7ba1b5990df7eb26f38fdf48d5785a93ebfa5082b  guix-build-86ef828e1d0d/output/powerpc64-linux-gnu/SHA256SUMS.part
9fab7f8f78e0922ce229195928635c6ca59c71ff5b64f2c23b37f56346cf5e02  guix-build-86ef828e1d0d/output/powerpc64-linux-gnu/bitcoin-86ef828e1d0d-powerpc64-linux-gnu-debug.tar.gz
424581198b30f81625522dd9099338e618d31b9134d1a9b97592a8b77e1f84d9  guix-build-86ef828e1d0d/output/powerpc64-linux-gnu/bitcoin-86ef828e1d0d-powerpc64-linux-gnu.tar.gz
849195175e6aaf8c89516ac49049131e2aee23a4b65be95f5efc0fbc7f3ff3c9  guix-build-86ef828e1d0d/output/powerpc64le-linux-gnu/SHA256SUMS.part
aa732e328351d4e2732a1642b7a0242b7a55556587e8587a9dfe9f309d29663f  guix-build-86ef828e1d0d/output/powerpc64le-linux-gnu/bitcoin-86ef828e1d0d-powerpc64le-linux-gnu-debug.tar.gz
4b1da33e17a2acd0cb9fd4ef31ffe8364dce7dd4ffdf3ca7bb2885fa462a53e8  guix-build-86ef828e1d0d/output/powerpc64le-linux-gnu/bitcoin-86ef828e1d0d-powerpc64le-linux-gnu.tar.gz
0610182fd34cec3b431d39dbc3199da466f0035f37937f3d500128974a24a4b1  guix-build-86ef828e1d0d/output/riscv64-linux-gnu/SHA256SUMS.part
b05b10a2653430fd74badec36d424bdcb341d02ab7a02c4f21b86817b28fd829  guix-build-86ef828e1d0d/output/riscv64-linux-gnu/bitcoin-86ef828e1d0d-riscv64-linux-gnu-debug.tar.gz
a078ddb3700dfbfac10adeb9ad68a8d281a9d84bde2cf48630c32b83b419f295  guix-build-86ef828e1d0d/output/riscv64-linux-gnu/bitcoin-86ef828e1d0d-riscv64-linux-gnu.tar.gz
67e8515e685e2334eae6a8dfb79567663ab4a661538764fc647e1ef5f93aefc6  guix-build-86ef828e1d0d/output/x86_64-apple-darwin19/SHA256SUMS.part
cdde8978f8e0bc1d45de9d9c0964c48b9d437dfd135bc4f1979c5b02bba6f5c1  guix-build-86ef828e1d0d/output/x86_64-apple-darwin19/bitcoin-86ef828e1d0d-osx-unsigned.dmg
0bb93adbba81467ac16bee268ead06c82e951803ed50046fa5eb9da48b51c1b3  guix-build-86ef828e1d0d/output/x86_64-apple-darwin19/bitcoin-86ef828e1d0d-osx-unsigned.tar.gz
3c30ee6c8f5970ad9fe78985c3b1f65ed6c47f33af332b9773f5fcbd6ee59724  guix-build-86ef828e1d0d/output/x86_64-apple-darwin19/bitcoin-86ef828e1d0d-osx64.tar.gz
44eaaea30bdfdde0e1c272223f424dc6bbb0b85a3e68cc328f73750cda6d43af  guix-build-86ef828e1d0d/output/x86_64-linux-gnu/SHA256SUMS.part
772dbefbfc99627e1246952ec80ee1192396ba2b8479875ef97d546c25e26b11  guix-build-86ef828e1d0d/output/x86_64-linux-gnu/bitcoin-86ef828e1d0d-x86_64-linux-gnu-debug.tar.gz
a4d997999578bb4acd736061a6ced56bf26c764272a88eb40deeaeb57eeabeb5  guix-build-86ef828e1d0d/output/x86_64-linux-gnu/bitcoin-86ef828e1d0d-x86_64-linux-gnu.tar.gz
d113bdbaee6ba2c29148e11868ee1c7c15dcd0d17b590a4e6b4cd2434edea3f5  guix-build-86ef828e1d0d/output/x86_64-w64-mingw32/SHA256SUMS.part
0b9438327abfe42d0cf4bc2e0362e41592acd6e53bd89749ca57dc3b1850ae73  guix-build-86ef828e1d0d/output/x86_64-w64-mingw32/bitcoin-86ef828e1d0d-win-unsigned.tar.gz
e1aafe35b7b667ed2abf68a03cc1d0b89af1bb3abdfc6019da5c8627331321b4  guix-build-86ef828e1d0d/output/x86_64-w64-mingw32/bitcoin-86ef828e1d0d-win64-debug.zip
5d8d735948a852492d4be6bc2e59c48d17c21f16f946884d120414b2e695191c  guix-build-86ef828e1d0d/output/x86_64-w64-mingw32/bitcoin-86ef828e1d0d-win64-setup-unsigned.exe
753cfc14d66eab282ed4ec9b2bdfae5ac874d2011ac5799bad714008cb70d5ab  guix-build-86ef828e1d0d/output/x86_64-w64-mingw32/bitcoin-86ef828e1d0d-win64.zip
```

**Comment by hebasto** [comment]
#### Guix builds on `x86_64`:
```
$ find guix-build-$(git rev-parse --short=12 HEAD)/output/ -type f -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum
d82c8dc7b5f70e369e4b69c95204c3b5e6b95a9fcfa00deeb3e3d0fcd5597fdc  guix-build-a3a2bd9e8ad3/output/aarch64-linux-gnu/SHA256SUMS.part
22480c8c3263714520df837cee08be3adab64ff2b1fc2b6620f2650a7eaee987  guix-build-a3a2bd9e8ad3/output/aarch64-linux-gnu/bitcoin-a3a2bd9e8ad3-aarch64-linux-gnu-debug.tar.gz
e7e85a417fa050434c48fe716c289762a87eb99759b00c653e77a428aac87b85  guix-build-a3a2bd9e8ad3/output/aarch64-linux-gnu/bitcoin-a3a2bd9e8ad3-aarch64-linux-gnu.tar.gz
eeb6b95194ea6b4b9293e6ca5912606a7b19037b1fb9ee34120eb9b0206a12f4  guix-build-a3a2bd9e8ad3/output/arm-linux-gnueabihf/SHA256SUMS.part
847c5c3b928eb21c55ac152b0ff9679a548d87fd4b6136eb56d22b113b84dcca  guix-build-a3a2bd9e8ad3/output/arm-linux-gnueabihf/bitcoin-a3a2bd9e8ad3-arm-linux-gnueabihf-debug.tar.gz
a723632d1facbf30b988c60affa75331c58ac91ee979ba40c6d86b460223700b  guix-build-a3a2bd9e8ad3/output/arm-linux-gnueabihf/bitcoin-a3a2bd9e8ad3-arm-linux-gnueabihf.tar.gz
7834b6b42c1b2c812e769b84b232b2f305685cec98a45f0b9dda7a2c3d5befac  guix-build-a3a2bd9e8ad3/output/arm64-apple-darwin/SHA256SUMS.part
1fcc075c0f6e9d01e124c3ad29ed075fb99a128bb36c0e2a8b0fb13e2864f390  guix-build-a3a2bd9e8ad3/output/arm64-apple-darwin/bitcoin-a3a2bd9e8ad3-arm64-apple-darwin-unsigned.dmg
6fc753b25f8e924197514b557368b826ca9a74ccfa1b8ab5a17f9f43e7ac3cd1  guix-build-a3a2bd9e8ad3/output/arm64-apple-darwin/bitcoin-a3a2bd9e8ad3-arm64-apple-darwin-unsigned.tar.gz
661655828828b938ade562fec0278537e0cf1b96563e50e7641a6dec0c4b38c0  guix-build-a3a2bd9e8ad3/output/arm64-apple-darwin/bitcoin-a3a2bd9e8ad3-arm64-apple-darwin.tar.gz
98bb4caaccda0fd7c444ad84120e28c426434c9cb6eccd77e7f15b385b638c53  guix-build-a3a2bd9e8ad3/output/dist-archive/bitcoin-a3a2bd9e8ad3.tar.gz
035f72bd931f7becc24471c279ef162a03d16b294a820f229561ca6e55924b5c  guix-build-a3a2bd9e8ad3/output/powerpc64-linux-gnu/SHA256SUMS.part
b679958ebaf9521400f1e93c673634a815d1ca374102f6236ecee8f8b7ba57a0  guix-build-a3a2bd9e8ad3/output/powerpc64-linux-gnu/bitcoin-a3a2bd9e8ad3-powerpc64-linux-gnu-debug.tar.gz
6b436cf5e3d37a0f8e1e096bc8b2b6d1a2f45ee641d979d4130f86d447e62f74  guix-build-a3a2bd9e8ad3/output/powerpc64-linux-gnu/bitcoin-a3a2bd9e8ad3-powerpc64-linux-gnu.tar.gz
32efbd285cbb4fc0dd3256c9e549f989f7dbc3c8faeed252184b40cbd839b515  guix-build-a3a2bd9e8ad3/output/powerpc64le-linux-gnu/SHA256SUMS.part
e280de74727aa641d7bba242e2fc2e701a7a28b0320e4eb26fff1e015fe61f97  guix-build-a3a2bd9e8ad3/output/powerpc64le-linux-gnu/bitcoin-a3a2bd9e8ad3-powerpc64le-linux-gnu-debug.tar.gz
b53e95063a08840454bd556ff7bde0d054919f7dda09dc4a572365da86ebc1f2  guix-build-a3a2bd9e8ad3/output/powerpc64le-linux-gnu/bitcoin-a3a2bd9e8ad3-powerpc64le-linux-gnu.tar.gz
2604cf96d7c9e5ac50a20dc3f9a10f22c7bcc99afd887031138d04190e9eb30b  guix-build-a3a2bd9e8ad3/output/riscv64-linux-gnu/SHA256SUMS.part
af3ff3b898fb07c97e43e74ea8de590d124aa5f069ec75e96930234e3f4c5aea  guix-build-a3a2bd9e8ad3/output/riscv64-linux-gnu/bitcoin-a3a2bd9e8ad3-riscv64-linux-gnu-debug.tar.gz
f37319ea8a5971ff2544f7361e4bc6f7210f1ea0f0e47864df7b54ae286731ee  guix-build-a3a2bd9e8ad3/output/riscv64-linux-gnu/bitcoin-a3a2bd9e8ad3-riscv64-linux-gnu.tar.gz
5b768c737aa1353d32dcc8296163428cd839c28bf6cea09012643a9887bb2867  guix-build-a3a2bd9e8ad3/output/x86_64-apple-darwin/SHA256SUMS.part
ff8a212939855321a6ee9096aff8e244a339a7fbc774acde6f89584d62975f67  guix-build-a3a2bd9e8ad3/output/x86_64-apple-darwin/bitcoin-a3a2bd9e8ad3-x86_64-apple-darwin-unsigned.dmg
8b3b5d5afbb1e16ef91ffeac7b807d6d6f16ed0ab6a37b32f0e809c87bf07950  guix-build-a3a2bd9e8ad3/output/x86_64-apple-darwin/bitcoin-a3a2bd9e8ad3-x86_64-apple-darwin-unsigned.tar.gz
55dd5bd0b6fab282b778a47f312a81b78be3a544a3ddc0c5bc5b414db9ff1dbe  guix-build-a3a2bd9e8ad3/output/x86_64-apple-darwin/bitcoin-a3a2bd9e8ad3-x86_64-apple-darwin.tar.gz
615ad6a3c2c6b98ed729d59f67736fc634e704a2f38043ac37cd791d951d793d  guix-build-a3a2bd9e8ad3/output/x86_64-linux-gnu/SHA256SUMS.part
98bf3b95ed46ecad65ec767221ddc32bfcbeb9eb74f64949af9208dce14e6203  guix-build-a3a2bd9e8ad3/output/x86_64-linux-gnu/bitcoin-a3a2bd9e8ad3-x86_64-linux-gnu-debug.tar.gz
666a82d7ed634ef365b982a3bca51a089a5257c7db3f5d3356edbc6d3e95eb43  guix-build-a3a2bd9e8ad3/output/x86_64-linux-gnu/bitcoin-a3a2bd9e8ad3-x86_64-linux-gnu.tar.gz
a99fee78fb24a3e7c5823cd847280bef0d190d738d733ee2ee7e0d543ea5557b  guix-build-a3a2bd9e8ad3/output/x86_64-w64-mingw32/SHA256SUMS.part
6b41a34df61e6f089ab8274bc16481a08b95dceb2dc818ff343acff181600742  guix-build-a3a2bd9e8ad3/output/x86_64-w64-mingw32/bitcoin-a3a2bd9e8ad3-win64-debug.zip
4b576a7e06f14c03c3c05f7378427267f45a928125823f437463afa6be321a0f  guix-build-a3a2bd9e8ad3/output/x86_64-w64-mingw32/bitcoin-a3a2bd9e8ad3-win64-setup-unsigned.exe
bfdb2a43a8a4f43724d677e24343b55352e67a6082af346fa8bac7bceaa21bd1  guix-build-a3a2bd9e8ad3/output/x86_64-w64-mingw32/bitcoin-a3a2bd9e8ad3-win64-unsigned.tar.gz
e55323da3755032b6a948606a5e484ffe8a6237d99f15c7613ddec79b6eadc56  guix-build-a3a2bd9e8ad3/output/x86_64-w64-mingw32/bitcoin-a3a2bd9e8ad3-win64.zip
```

**Comment by jarolrod** [comment]
GUIX hashes

x86:
```
$ find guix-build-$(git rev-parse --short=12 HEAD)/output/ -type f -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum

d82c8dc7b5f70e369e4b69c95204c3b5e6b95a9fcfa00deeb3e3d0fcd5597fdc  guix-build-a3a2bd9e8ad3/output/aarch64-linux-gnu/SHA256SUMS.part
22480c8c3263714520df837cee08be3adab64ff2b1fc2b6620f2650a7eaee987  guix-build-a3a2bd9e8ad3/output/aarch64-linux-gnu/bitcoin-a3a2bd9e8ad3-aarch64-linux-gnu-debug.tar.gz
e7e85a417fa050434c48fe716c289762a87eb99759b00c653e77a428aac87b85  guix-build-a3a2bd9e8ad3/output/aarch64-linux-gnu/bitcoin-a3a2bd9e8ad3-aarch64-linux-gnu.tar.gz
eeb6b95194ea6b4b9293e6ca5912606a7b19037b1fb9ee34120eb9b0206a12f4  guix-build-a3a2bd9e8ad3/output/arm-linux-gnueabihf/SHA256SUMS.part
847c5c3b928eb21c55ac152b0ff9679a548d87fd4b6136eb56d22b113b84dcca  guix-build-a3a2bd9e8ad3/output/arm-linux-gnueabihf/bitcoin-a3a2bd9e8ad3-arm-linux-gnueabihf-debug.tar.gz
a723632d1facbf30b988c60affa75331c58ac91ee979ba40c6d86b460223700b  guix-build-a3a2bd9e8ad3/output/arm-linux-gnueabihf/bitcoin-a3a2bd9e8ad3-arm-linux-gnueabihf.tar.gz
7834b6b42c1b2c812e769b84b232b2f305685cec98a45f0b9dda7a2c3d5befac  guix-build-a3a2bd9e8ad3/output/arm64-apple-darwin/SHA256SUMS.part
1fcc075c0f6e9d01e124c3ad29ed075fb99a128bb36c0e2a8b0fb13e2864f390  guix-build-a3a2bd9e8ad3/output/arm64-apple-darwin/bitcoin-a3a2bd9e8ad3-arm64-apple-darwin-unsigned.dmg
6fc753b25f8e924197514b557368b826ca9a74ccfa1b8ab5a17f9f43e7ac3cd1  guix-build-a3a2bd9e8ad3/output/arm64-apple-darwin/bitcoin-a3a2bd9e8ad3-arm64-apple-darwin-unsigned.tar.gz
661655828828b938ade562fec0278537e0cf1b96563e50e7641a6dec0c4b38c0  guix-build-a3a2bd9e8ad3/output/arm64-apple-darwin/bitcoin-a3a2bd9e8ad3-arm64-apple-darwin.tar.gz
98bb4caaccda0fd7c444ad84120e28c426434c9cb6eccd77e7f15b385b638c53  guix-build-a3a2bd9e8ad3/output/dist-archive/bitcoin-a3a2bd9e8ad3.tar.gz
035f72bd931f7becc24471c279ef162a03d16b294a820f229561ca6e55924b5c  guix-build-a3a2bd9e8ad3/output/powerpc64-linux-gnu/SHA256SUMS.part
b679958ebaf9521400f1e93c673634a815d1ca374102f6236ecee8f8b7ba57a0  guix-build-a3a2bd9e8ad3/output/powerpc64-linux-gnu/bitcoin-a3a2bd9e8ad3-powerpc64-linux-gnu-debug.tar.gz
6b436cf5e3d37a0f8e1e096bc8b2b6d1a2f45ee641d979d4130f86d447e62f74  guix-build-a3a2bd9e8ad3/output/powerpc64-linux-gnu/bitcoin-a3a2bd9e8ad3-powerpc64-linux-gnu.tar.gz
32efbd285cbb4fc0dd3256c9e549f989f7dbc3c8faeed252184b40cbd839b515  guix-build-a3a2bd9e8ad3/output/powerpc64le-linux-gnu/SHA256SUMS.part
e280de74727aa641d7bba242e2fc2e701a7a28b0320e4eb26fff1e015fe61f97  guix-build-a3a2bd9e8ad3/output/powerpc64le-linux-gnu/bitcoin-a3a2bd9e8ad3-powerpc64le-linux-gnu-debug.tar.gz
b53e95063a08840454bd556ff7bde0d054919f7dda09dc4a572365da86ebc1f2  guix-build-a3a2bd9e8ad3/output/powerpc64le-linux-gnu/bitcoin-a3a2bd9e8ad3-powerpc64le-linux-gnu.tar.gz
2604cf96d7c9e5ac50a20dc3f9a10f22c7bcc99afd887031138d04190e9eb30b  guix-build-a3a2bd9e8ad3/output/riscv64-linux-gnu/SHA256SUMS.part
af3ff3b898fb07c97e43e74ea8de590d124aa5f069ec75e96930234e3f4c5aea  guix-build-a3a2bd9e8ad3/output/riscv64-linux-gnu/bitcoin-a3a2bd9e8ad3-riscv64-linux-gnu-debug.tar.gz
f37319ea8a5971ff2544f7361e4bc6f7210f1ea0f0e47864df7b54ae286731ee  guix-build-a3a2bd9e8ad3/output/riscv64-linux-gnu/bitcoin-a3a2bd9e8ad3-riscv64-linux-gnu.tar.gz
5b768c737aa1353d32dcc8296163428cd839c28bf6cea09012643a9887bb2867  guix-build-a3a2bd9e8ad3/output/x86_64-apple-darwin/SHA256SUMS.part
ff8a212939855321a6ee9096aff8e244a339a7fbc774acde6f89584d62975f67  guix-build-a3a2bd9e8ad3/output/x86_64-apple-darwin/bitcoin-a3a2bd9e8ad3-x86_64-apple-darwin-unsigned.dmg
8b3b5d5afbb1e16ef91ffeac7b807d6d6f16ed0ab6a37b32f0e809c87bf07950  guix-build-a3a2bd9e8ad3/output/x86_64-apple-darwin/bitcoin-a3a2bd9e8ad3-x86_64-apple-darwin-unsigned.tar.gz
55dd5bd0b6fab282b778a47f312a81b78be3a544a3ddc0c5bc5b414db9ff1dbe  guix-build-a3a2bd9e8ad3/output/x86_64-apple-darwin/bitcoin-a3a2bd9e8ad3-x86_64-apple-darwin.tar.gz
615ad6a3c2c6b98ed729d59f67736fc634e704a2f38043ac37cd791d951d793d  guix-build-a3a2bd9e8ad3/output/x86_64-linux-gnu/SHA256SUMS.part
98bf3b95ed46ecad65ec767221ddc32bfcbeb9eb74f64949af9208dce14e6203  guix-build-a3a2bd9e8ad3/output/x86_64-linux-gnu/bitcoin-a3a2bd9e8ad3-x86_64-linux-gnu-debug.tar.gz
666a82d7ed634ef365b982a3bca51a089a5257c7db3f5d3356edbc6d3e95eb43  guix-build-a3a2bd9e8ad3/output/x86_64-linux-gnu/bitcoin-a3a2bd9e8ad3-x86_64-linux-gnu.tar.gz
a99fee78fb24a3e7c5823cd847280bef0d190d738d733ee2ee7e0d543ea5557b  guix-build-a3a2bd9e8ad3/output/x86_64-w64-mingw32/SHA256SUMS.part
6b41a34df61e6f089ab8274bc16481a08b95dceb2dc818ff343acff181600742  guix-build-a3a2bd9e8ad3/output/x86_64-w64-mingw32/bitcoin-a3a2bd9e8ad3-win64-debug.zip
4b576a7e06f14c03c3c05f7378427267f45a928125823f437463afa6be321a0f  guix-build-a3a2bd9e8ad3/output/x86_64-w64-mingw32/bitcoin-a3a2bd9e8ad3-win64-setup-unsigned.exe
bfdb2a43a8a4f43724d677e24343b55352e67a6082af346fa8bac7bceaa21bd1  guix-build-a3a2bd9e8ad3/output/x86_64-w64-mingw32/bitcoin-a3a2bd9e8ad3-win64-unsigned.tar.gz
e55323da3755032b6a948606a5e484ffe8a6237d99f15c7613ddec79b6eadc56  guix-build-a3a2bd9e8ad3/output/x86_64-w64-mingw32/bitcoin-a3a2bd9e8ad3-win64.zip
```

arm64:
```
$ env HOSTS='arm-linux-gnueabihf arm64-apple-darwin powerpc64-linux-gnu powerpc64le-linux-gnu riscv64-linux-gnu x86_64-apple-darwin x86_64-linux-gnu x86_64-w64-mingw32' ./contrib/guix/guix-build
$ find guix-build-$(git rev-parse --short=12 HEAD)/output/ -type f -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum

10506ea14861e92467f46553be1a123a3c8f8fa6b3389bb81404297b11ad7836  guix-build-a3a2bd9e8ad3/output/arm-linux-gnueabihf/SHA256SUMS.part
62eace9518bc7321b7d36a44ef67132d584d01612cafa4b3e1143287600abd03  guix-build-a3a2bd9e8ad3/output/arm-linux-gnueabihf/bitcoin-a3a2bd9e8ad3-arm-linux-gnueabihf-debug.tar.gz
56399bfa02d9ffc00046ba79c03ed42f107da48d86b730e002bfbff0cef6a2a8  guix-build-a3a2bd9e8ad3/output/arm-linux-gnueabihf/bitcoin-a3a2bd9e8ad3-arm-linux-gnueabihf.tar.gz
dc47266a279644b6eee81808f3ab48214a01afed044ff4900209a7d08926c16d  guix-build-a3a2bd9e8ad3/output/arm64-apple-darwin/SHA256SUMS.part
e6f52a1895d1866a96c491b52c39f78a88085711ecd0dc0b09cffb1d94bfc324  guix-build-a3a2bd9e8ad3/output/arm64-apple-darwin/bitcoin-a3a2bd9e8ad3-arm64-apple-darwin-unsigned.dmg
b277eeb68c8ddfddf5a63dc33a37399fab435bf3b383f2e1698ab9b53143542e  guix-build-a3a2bd9e8ad3/output/arm64-apple-darwin/bitcoin-a3a2bd9e8ad3-arm64-apple-darwin-unsigned.tar.gz
b7f6b85505a0ca06591d0f9bf640a9a3d943c40d9a041c403f714943bbe20b97  guix-build-a3a2bd9e8ad3/output/arm64-apple-darwin/bitcoin-a3a2bd9e8ad3-arm64-apple-darwin.tar.gz
98bb4caaccda0fd7c444ad84120e28c426434c9cb6eccd77e7f15b385b638c53  guix-build-a3a2bd9e8ad3/output/dist-archive/bitcoin-a3a2bd9e8ad3.tar.gz
39e8fef31df3285ed1ad9fb234e781cbd053998c3efbeb92e6efc629ead003ee  guix-build-a3a2bd9e8ad3/output/powerpc64-linux-gnu/SHA256SUMS.part
fa0882144d0b956e39d80c8b78f9450ea49126e0016b52d733a806b01a0b623b  guix-build-a3a2bd9e8ad3/output/powerpc64-linux-gnu/bitcoin-a3a2bd9e8ad3-powerpc64-linux-gnu-debug.tar.gz
772ffc2cd49bc164796405c6315ead2d2570e1f46c74849f879c1206e94cb82c  guix-build-a3a2bd9e8ad3/output/powerpc64-linux-gnu/bitcoin-a3a2bd9e8ad3-powerpc64-linux-gnu.tar.gz
fa4756b90bcaf140d45f2d931dc8a1c592e78647d6418c5b2a9092c5093a184b  guix-build-a3a2bd9e8ad3/output/powerpc64le-linux-gnu/SHA256SUMS.part
01df2293c18b35580e24a10da03c258cc018ce01239f1b7c9218722b17cb39d5  guix-build-a3a2bd9e8ad3/output/powerpc64le-linux-gnu/bitcoin-a3a2bd9e8ad3-powerpc64le-linux-gnu-debug.tar.gz
687195360a74746b6f3c70e16f5f2f92e163d93525a21c061b28d5f2d1985fbb  guix-build-a3a2bd9e8ad3/output/powerpc64le-linux-gnu/bitcoin-a3a2bd9e8ad3-powerpc64le-linux-gnu.tar.gz
bbe9a1f7196c75e35762933dd762c0e19b88870ff8510f84247b7202aa53e2db  guix-build-a3a2bd9e8ad3/output/riscv64-linux-gnu/SHA256SUMS.part
f921489a8d7dde342d6e0df4e501b9c907674e421c502612c824ffba634067ff  guix-build-a3a2bd9e8ad3/output/riscv64-linux-gnu/bitcoin-a3a2bd9e8ad3-riscv64-linux-gnu-debug.tar.gz
fcf11e8d3d2494134af98c507071f1adeffd5b62301415b6750ab8ba5323764c  guix-build-a3a2bd9e8ad3/output/riscv64-linux-gnu/bitcoin-a3a2bd9e8ad3-riscv64-linux-gnu.tar.gz
3ff577177734ea4b09c1061e958962fbac99c51437e499f9e982bf36b1295731  guix-build-a3a2bd9e8ad3/output/x86_64-apple-darwin/SHA256SUMS.part
ff8a212939855321a6ee9096aff8e244a339a7fbc774acde6f89584d62975f67  guix-build-a3a2bd9e8ad3/output/x86_64-apple-darwin/bitcoin-a3a2bd9e8ad3-x86_64-apple-darwin-unsigned.dmg
78c72a7540bd5d6dcae45e383e408dd8e9fa247bae580a8d358499a6ce74b400  guix-build-a3a2bd9e8ad3/output/x86_64-apple-darwin/bitcoin-a3a2bd9e8ad3-x86_64-apple-darwin-unsigned.tar.gz
55dd5bd0b6fab282b778a47f312a81b78be3a544a3ddc0c5bc5b414db9ff1dbe  guix-build-a3a2bd9e8ad3/output/x86_64-apple-darwin/bitcoin-a3a2bd9e8ad3-x86_64-apple-darwin.tar.gz
1a28371d202e003c29d5fdfa4ae80cfc70aa6c50df15ad8168b67ce962afb2d6  guix-build-a3a2bd9e8ad3/output/x86_64-linux-gnu/SHA256SUMS.part
f03db78cda94aa58d2fa502fec8e9791195f6e500eef32ce1d78b4c9af8f900e  guix-build-a3a2bd9e8ad3/output/x86_64-linux-gnu/bitcoin-a3a2bd9e8ad3-x86_64-linux-gnu-debug.tar.gz
f652146003e96d46d8bee5be1477b0040f5ccfbf73feecc96f258ab813b550c3  guix-build-a3a2bd9e8ad3/output/x86_64-linux-gnu/bitcoin-a3a2bd9e8ad3-x86_64-linux-gnu.tar.gz
1ae30c8fbd357fa6148e77bea9b9348b5a5bcc1a0c700def7cdea29e8a5b8e71  guix-build-a3a2bd9e8ad3/output/x86_64-w64-mingw32/SHA256SUMS.part
77803fc04e1384b2a52d8285622f4c6903c2b4baac01d245c4f76827999035a1  guix-build-a3a2bd9e8ad3/output/x86_64-w64-mingw32/bitcoin-a3a2bd9e8ad3-win64-debug.zip
4b576a7e06f14c03c3c05f7378427267f45a928125823f437463afa6be321a0f  guix-build-a3a2bd9e8ad3/output/x86_64-w64-mingw32/bitcoin-a3a2bd9e8ad3-win64-setup-unsigned.exe
bfdb2a43a8a4f43724d677e24343b55352e67a6082af346fa8bac7bceaa21bd1  guix-build-a3a2bd9e8ad3/output/x86_64-w64-mingw32/bitcoin-a3a2bd9e8ad3-win64-unsigned.tar.gz
2912e627e6636c81223e6b45b4d11d41473a106d3fa92f4431636cc77ffae31b  guix-build-a3a2bd9e8ad3/output/x86_64-w64-mingw32/bitcoin-a3a2bd9e8ad3-win64.zip
```

**Comment by TheCharlatan** [comment]
Code review ACK a3a2bd9e8ad360a63cc8bdfc365d8bfd25ecc720

**Pull request merged**
