### PR TITLE
[contrib] Support ARM and RISC-V symbol check

### PR DESCRIPTION
**Pull request by ken2812221**
Solve the TODO in the gitian-descripter

### CODE REVIEW

**Comment by laanwj** [comment]
Thanks for adding this!

**Comment by laanwj** [comment]
utACK 8f62ece7c1dddc4f69141d884b7c1863776c4fa7

**Comment by ken2812221** [comment]
#13665 has not ready to merge since it would export a lot of symbols.

**Comment by MarcoFalke** [comment]
Have you run the symbol check after cross compilation? It seems to fail for me:


```
  CXXLD    test/test_bitcoin_fuzzy
  CXXLD    bitcoind
  CXXLD    bitcoin-cli
  CXXLD    bitcoin-tx
  CXXLD    test/test_bitcoin
  AR       qt/libbitcoinqt.a
  OBJCXXLD qt/bitcoin-qt
make[2]: Leaving directory '/home/ubuntu/build/bitcoin/distsrc-arm-linux-gnueabihf/src'
make[1]: Leaving directory '/home/ubuntu/build/bitcoin/distsrc-arm-linux-gnueabihf/src'
Making all in doc/man
make[1]: Entering directory '/home/ubuntu/build/bitcoin/distsrc-arm-linux-gnueabihf/doc/man'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/ubuntu/build/bitcoin/distsrc-arm-linux-gnueabihf/doc/man'
make[1]: Entering directory '/home/ubuntu/build/bitcoin/distsrc-arm-linux-gnueabihf'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/home/ubuntu/build/bitcoin/distsrc-arm-linux-gnueabihf'
+ make -j9 -C src check-security
make: Entering directory '/home/ubuntu/build/bitcoin/distsrc-arm-linux-gnueabihf/src'
Checking binary security...
make: Leaving directory '/home/ubuntu/build/bitcoin/distsrc-arm-linux-gnueabihf/src'
+ make -j9 -C src check-symbols
make: Entering directory '/home/ubuntu/build/bitcoin/distsrc-arm-linux-gnueabihf/src'
Checking glibc back compat...
qt/bitcoin-qt: export of symbol _bss_end__ not allowed
qt/bitcoin-qt: export of symbol __bss_end__ not allowed
qt/bitcoin-qt: export of symbol __bss_start__ not allowed
qt/bitcoin-qt: export of symbol __end__ not allowed
make: *** [check-symbols] Error 1
Makefile:10512: recipe for target 'check-symbols' failed
make: Leaving directory '/home/ubuntu/build/bitcoin/distsrc-arm-linux-gnueabihf/src'

**Comment by ken2812221** [comment]
@MarcoFalke Fixed. Sorry about not testing before I commited. I've tested 85ec33a35dfec2cc3b2e0decb5e184650caecdef (master + 60976f2) that can successfully do gitian build.

**Comment by laanwj** [comment]
Needs rebase after #13665

**Comment by ken2812221** [comment]
Need to skip RISC-V for now, the linker would export so many symbols.

**Comment by laanwj** [comment]
> Need to skip RISC-V for now, the linker would export so many symbols.

FWIW checking the *imports* is much more important than checking the exports, as that's what prevents binary incompatibilities.

**Comment by laanwj** [comment]
utACK c516c3a770e93dcd283dc4a9275cba88221d0e3a

**Comment by luke-jr** [comment]
Hmm, didn't see this sooner. FWIW, I have another alternative to this we can evaluate.

**Comment by laanwj** [comment]
I'm going ahead and merging this, @luke-jr please rebase your stuff on top.

**Pull request merged**
