### PR TITLE
[25.1] Final backports

### PR DESCRIPTION
**Pull request by fanquake**
Further backports for the `25.x` branch. Currently:
* https://github.com/bitcoin/bitcoin/pull/27622
* https://github.com/bitcoin/bitcoin/pull/27834
* https://github.com/bitcoin/bitcoin/pull/28125
* https://github.com/bitcoin/bitcoin/pull/28452
* https://github.com/bitcoin/bitcoin/pull/28542
* https://github.com/bitcoin/bitcoin/pull/28543
* https://github.com/bitcoin/bitcoin/pull/28551
* https://github.com/bitcoin/bitcoin/pull/28571
* https://github.com/bitcoin-core/gui/pull/751

### CODE REVIEW

**Comment by fanquake** [comment]
Added #28542. Slight diff in the tests to account for changes to `send()`.

**Comment by fanquake** [comment]
This will hopefully have 1 or 2 additional changes added (see milestone/labels), but marking as ready for review.

**Review by dergoegge — APPROVED** [review]
ACK a6683945ca38752875e82dddccba075195ec61a6

**Review by willcl-ark — APPROVED** [review]
ACK a6683945ca

Verified the diffs between each patch and its Rebased-From patch

**Comment by hebasto** [comment]
Suggesting to add https://github.com/bitcoin-core/gui/pull/751

**Review by hebasto — COMMENTED** [review]
When backporting https://github.com/bitcoin/bitcoin/pull/28452 locally, I've got the following diff with this PR:
```diff
--- a/src/net.cpp
+++ b/src/net.cpp
@@ -35,6 +35,7 @@
 #include <util/threadinterrupt.h>
 #include <util/trace.h>
 #include <util/translation.h>
+#include <util/vector.h>
 
 #ifdef WIN32
 #include <string.h>
```

**Comment by fanquake** [comment]
> I've got the following diff with this PR:

Yea, because it's not used in that file in this branch.

**Review by hebasto — APPROVED** [review]
ACK f31899d19a0333e87c3690b3d3c2b574abb357fa, I've applied all backports locally and got a zero diff with this PR branch.

**Comment by fanquake** [comment]
This is ready for final review.

**Review by hebasto — APPROVED** [review]
re-ACK 45a5fcb165081f38ef90944dd31c5e3107aa03dc, only #28551 has been backported with since my recent [review](https://github.com/bitcoin/bitcoin/pull/28487#pullrequestreview-1655584132).

**Review by dergoegge — APPROVED** [review]
reACK 45a5fcb165081f38ef90944dd31c5e3107aa03dc

**Review by willcl-ark — APPROVED** [review]
reACK 45a5fcb165081f38ef90944dd31c5e3107aa03dc

<details>
  <summary>build info</summary>
 
| Key         | Value |
|-------------|-------|
| Hostname    | ubuntu |
| Arch        | x86_64 |
| Kernel      | 6.2.0-32-generic |
| System      | Linux |
| CC          | Ubuntu clang version 16.0.6 |
| CXX         | Ubuntu clang version 16.0.6 |
| Configure   | ./configure --with-incompatible-bdb --without-miniupnpc --without-natpmp --disable-bench --without-gui --enable-debug CXX=/usr/lib/ccache/clang++ CC=/usr/lib/ccache/clang --disable-shared --with-pic --enable-benchmark=no --enable-module-recovery --disable-module-ecdh --no-create --no-recursion ./config.status  ./config.status src/config/bitcoin-config.h |
  
</details>

**Pull request merged**
