### PR TITLE
[tests] Remove unused variables and imports

### PR DESCRIPTION
**Pull request by practicalswift**

### CODE REVIEW

**Comment by fanquake** [comment]
I'm surprised there are some many to remove again, given this was only done two months ago (#9508).

**Comment by jonasschnelli** [comment]
utACK d3073c232a7a0ad182cf4d9eb1495c79795669e9

**Comment by jonasschnelli** [comment]
Maybe add commit from #10049 here? Trivial PRs tend to distract and therefore combining should be okay and desirable.

**Comment by jnewbery** [comment]
Tested ACK d3073c232a7a0ad182cf4d9eb1495c79795669e9

@fanquake - there's been a lot of churn in the test directory recently, which is how some of these have crept in.

Longer term, I expect we'll continue to see unused imports until we have a sensible import scheme for the functional tests such as https://github.com/bitcoin/bitcoin/pull/9876#issuecomment-283198485. Static analysis tools can't work out wildcard imports and linters like flake8 throw up many errors when wildcards are used, so I expect no-one is using linters before committing.

**Comment by practicalswift** [comment]
@jonasschnelli Good point! Added the commit from #10049 into this PR :-)

**Comment by fanquake** [comment]
@jnewbery fair enough.

utACK 3897459

**Comment by paveljanik** [comment]
utACK 3897459

**Comment by MarcoFalke** [comment]
utACK 3897459

**Pull request merged**
