### PR TITLE
ci: Combine 32-bit build with CentOS 7 build

### PR DESCRIPTION
**Pull request by theStack**
Combines the CentOS build with the 32-bit (i686) build to avoid Travis bottlenecks, as suggested in #17757 by MarcoFalke. This keeps most of the properties of the 32-bit build (dash as config shell, building QT5 GUI) and just builds it with depends inside the CentOS docker container.

Making the depends in `05_before_script.sh` with unset config shell (`CONFIG_SHELL=`) 

https://github.com/bitcoin/bitcoin/blob/6196e930018181301b5972842ae384ea4288ff34/ci/test/05_before_script.sh#L28

caused problems for building the library libevent (resulting in a Makefile with no shell set (`SHELL=`)), that's why I set it explicitely to `/bin/bash` if we have a CentOS Docker container.

A Travis output of this 32-bit CentOS build can be seen here: https://travis-ci.org/theStack/bitcoin/jobs/634472394 (has been restarted once due to too long build time and appearance of the `CACHE_ERR_MSG`).

For anyone wanting to verify the outputs, I found these instructions useful to reproduce a Travis build locally: https://github.com/erdc/proteus/wiki/Replicating-the-TravisCI-Environment-on-your-Local-Machine (steps 1-3). In this case it's a bit tricky since you run Docker inside Docker -- within the Travis Docker container, the CentOS Docker container is created. To make this possible, the Docker socket has to be exposed to the Travis container via bind-mounting (`docker run -v /var/run/docker.sock:/var/run/docker.sock ...`), as suggested in https://stackoverflow.com/a/33003273.

### CODE REVIEW

**Comment by hebasto** [comment]
One of the [initial goals](https://github.com/bitcoin/bitcoin/issues/17628#issuecomment-559448201) to run CentOS task on Travis was to check the Bitcoin Core compatibility with aged (system) dependencies. Using our built `depends/` eliminates this achievement, no?

**Comment by MarcoFalke** [comment]
32-bit gitian is going to be removed, so we might as well not use depends in here. See #17504

**Comment by theStack** [comment]
> 
> 
> One of the [initial goals](https://github.com/bitcoin/bitcoin/issues/17628#issuecomment-559448201) to run CentOS task on Travis was to check the Bitcoin Core compatibility with aged (system) dependencies. Using our built `depends/` eliminates this achievement, no?

Without building the depends I don't see a way to do a cross-compile from 64 bit to 32 bit, one would need all the needed libraries also for i686, which is unfortunately the case in CentOS 7 -- the following packages are only available for x86_64: libdb4-devel, libdb4-cxx-devel, miniupnpc-devel, zeromq-devel.

**Comment by hebasto** [comment]
For quick reference: http://mirror.centos.org/altarch/7/os/i386/Packages/

**Comment by laanwj** [comment]
Concept ACK

> 32-bit gitian is going to be removed, so we might as well not use depends in here. See #17504

I'm not sure 32-bit gitian binaries and depends 32-bit support should be equated here. Deciding not to ship 32 bit gitian binaries does not necessarily mean making it harder to build on/for 32 bit for those that still want to. I dunno.

**Pull request merged**
