### PR TITLE
Create btcdrak-key.pgp

### PR DESCRIPTION
**Pull request by btcdrak**

### CODE REVIEW

**Comment by fanquake** [comment]
```
Name: BtcDrak
Email: btcdrak@gmail.com
Created: 18 July 2015 00:14
Expires: 17 July 2018 00:14

Key ID: E73A1AF2
Length: 4,096
Algorithm: RSA
Fingerprint: C93F 3219 C7FE 9867 B918  A46F E5D1 38F5 E73A 1AF2
```

ACK after a set of sigs has been merged to the gitian.sigs repo

**Comment by btcdrak** [comment]
please redact the email from the comment quote so spambots dont harass me.

**Comment by btcdrak** [comment]
Signed in https://github.com/bitcoin/gitian.sigs/pull/226

**Comment by petertodd** [comment]
ACK

**Pull request merged**
