### PR TITLE
doc: Update dependencies.md

### PR DESCRIPTION
**Pull request by hebasto**
Updated info about:
- Qt-bundled FreeType library on Android
- Qt-bundled HarfBuzz-NG library
- Qt dependency version (5.9.7 -> 5.9.8, #16413)

### CODE REVIEW

**Review by promag — COMMENTED** [review]
ACK df97e592078a33f6bf535979e05967c563de317b.

**Comment by elichai** [comment]
ACK df97e592078a33f6bf535979e05967c563de317b

**Comment by hebasto** [comment]
@elichai 

> I'm not quite sure I understand the semantics of the table. does it mean it's _only_ bundled in QT-android or _also_ or both? (because `fontconfig` also requires `freetype`, even on linux)

https://github.com/bitcoin/bitcoin/blob/b931f61b9ab098ea4ea8fbe4cbf0b03c566c3f63/depends/packages/qt.mk#L33

https://github.com/bitcoin/bitcoin/blob/b931f61b9ab098ea4ea8fbe4cbf0b03c566c3f63/depends/packages/qt.mk#L131

https://github.com/bitcoin/bitcoin/blob/b931f61b9ab098ea4ea8fbe4cbf0b03c566c3f63/depends/packages/qt.mk#L159

[Qt Third-Party Libraries](https://doc.qt.io/qt-5/configure-options.html#third-party-libraries):
> To set whether Qt should use the _system's_ versions of the libraries or to use the _bundled_ version, pass either `-system` or `-qt` before the name of the library to configure.
> It is also possible to _disable_ support for these libraries by using `-no` instead of `-qt`.

So, only on Android platform the bundled version of `freetype` is used.
Other Linux platforms use system's `freetype`.

**Comment by elichai** [comment]
I know that. what I tried to ask is does this change semantically mean that this is the *only* place where `freetype` is used? if so then that's not right. if it doesn't then it's fine.

in other words. *in qt* `freetype` is only used in android. *outside of qt* it's used in more places in "normal" linux too. 
https://github.com/bitcoin/bitcoin/blob/b931f61b9ab098ea4ea8fbe4cbf0b03c566c3f63/depends/packages/packages.mk#L7
https://github.com/bitcoin/bitcoin/blob/b931f61b9ab098ea4ea8fbe4cbf0b03c566c3f63/depends/packages/fontconfig.mk#L6

**Comment by hebasto** [comment]
> in other words. **in qt** `freetype` is only used in android. **outside of qt** it's used in more places in "normal" linux too.

`freetype` is used **by** Qt:
- Qt's own (bundled) `freetype` on Android
- system's (provided by host Linux OS) `freetype` on Linux (non-Android)

**Comment by hebasto** [comment]
> ... this change semantically mean that this is the **only** place where `freetype` is used?

The column name is "Bundled Qt library" ;)

**Comment by fanquake** [comment]
ACK df97e592078a33f6bf535979e05967c563de317b

**Pull request merged**
