### PR TITLE
test: passing a negative value to `-peertimeout` should throw an error

### PR DESCRIPTION
**Pull request by brunoerg**
This PR adds test coverage for the following init error:
https://github.com/bitcoin/bitcoin/blob/5bc10b39abbcb77638161902ccd1225139bc7cc0/src/init.cpp#L967-L970

### CODE REVIEW

**Review by kristapsk — APPROVED** [review]
utACK 694669e1458ec16a88e6be7c6723144e778fa879

**Comment by kristapsk** [comment]
While looking at this, noticed that it gives the same error message about "cannot be negative" if you try to start with non-integer `-peertimeout`, which seems wrong.

**Comment by 1440000bytes** [comment]
> While looking at this, noticed that it gives the same error message about "cannot be negative" if you try to start with non-integer `-peertimeout`, which seems wrong.

```diff
-return InitError(Untranslated("peertimeout cannot be configured with a negative value."));
+ return InitError(Untranslated("Invalid value for peertimeout: %d", peer_connect_timeout));
 ```
 
 Maybe this could fix it

**Comment by brunoerg** [comment]
> While looking at this, noticed that it gives the same error message about "cannot be negative" if you try to start with non-integer -peertimeout, which seems wrong.

Yea, just noticed it. Same if you pass `0`

**Comment by 1440000bytes** [comment]
> @1440000bytes maybe this way? I can address this change in this PR if other reviewers agree.

I added another error message in https://github.com/bitcoin/bitcoin/pull/25506

**Review by ghost — APPROVED** [review]
ACK https://github.com/bitcoin/bitcoin/pull/25505/commits/694669e1458ec16a88e6be7c6723144e778fa879

**Comment by kristapsk** [comment]
Probably it's good idea to first decide about merging or not merging #25506 and then possibly add additional test case here.

**Comment by brunoerg** [comment]
Why is this closed? @MarcoFalke I intended to rebase it

**Comment by kristapsk** [comment]
It was auto-closed by `github-merge.sh` script, because PR description contained "Fixes" with link to this PR, script didn't understand that it was link to a comment.

**Comment by brunoerg** [comment]
@kristapsk oh sorry, didn't notice it. Anyway, I opened #25511 in order to this one. thanks!

**Pull request closed without merging**
