### PR TITLE
net: Make addr relay mockable, add test

### PR DESCRIPTION
**Pull request by maflcko**
As usual:

* Switch to std::chrono time to be type-safe and mockable
* Add basic test that relies on mocktime to add code coverage

### CODE REVIEW

**Comment by jonatack** [comment]
Concept ACK. The code changes look good, will review the new test.

**Comment by practicalswift** [comment]
Concept ACK

Thanks taking on this unglamourous (in the short-run) but important (in the long-run) work.

**Comment by promag** [comment]
Code review ACK fa5bf23d527a450e72c2bf13d013e5393b664ca3, clean change, just read the new test.

**Comment by naumenkogs** [comment]
Code looks good.
I can't understand what the test is actually testing for?

**Comment by MarcoFalke** [comment]
It is a basic test to check that addr messages can be received (and are then relayed). For more information you can read the lines `self.log.info(...)`

**Comment by MarcoFalke** [comment]
Force pushed because I had to re-arrange the commits. Diff to previous review should be empty.

**Comment by naumenkogs** [comment]
Yeah I tried reading that, just wanted to confirm. So, it actually doesn't test the new behavior (mockability)? Because ``setmocktime`` is called at the very end and nothing is really tested after it.

**Comment by MarcoFalke** [comment]
`assert_debug_log` is a context manager, so the checks in it are executed at the end.

You can check that the test fails by compiling current master, then checking out this branch, then running the functional tests without recompiling.

You can also check that this test fails by removing the call to `setmocktime` in the functional test.

**Comment by naumenkogs** [comment]
utACK fad3f58fd5a9d35d5a6e3467b1b5bcf18081ca41, although I would prefer to comment the last lines of the test. I think it's counter-intuitive of what you are actually trying to demonstrate.

**Comment by MarcoFalke** [comment]
@naumenkogs Happy to do that, could you leave suggestions for in-line comments please, so that I can take them?

**Comment by MarcoFalke** [comment]
Removed last commit after chat with @naumenkogs to keep this pull focussed on one topic. The test in the last commit can be added later, if needed.

**Comment by naumenkogs** [comment]
utACK  fa1da3d

**Comment by MarcoFalke** [comment]
@promag Mind to re-ACK after I dropped one commit?

**Comment by promag** [comment]
ACK fabe56e44b6f683e24e37246a7a8851190947cb3, fa5bf23d527a450e72c2bf13d013e5393b664ca3 was dropped since last review.

**Pull request merged**
