### PR TITLE
Remove Safe mode (achow101)

### PR DESCRIPTION
**Pull request by laanwj**
Rebase of #10563. Safe mode was [disabled by default and deprecated in 0.16](https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-0.16.0.md#safe-mode-disabled-by-default), so probably should be removed for 0.17.

> Rationale:
>
> Safe mode is useless. It only disables some RPC commands when large work forks are detected. Nothing else is affected by safe mode. It seems that very few people would be affected by safe mode. The people who use Core as a wallet are primarily using it through the GUI, which safe mode does not effect. In the GUI, transactions will still be made as normal; only a warning is displayed.
>
> I also don't think that we should be disabling RPC commands or any functionality in general. If we do, it should be done consistently, which safe mode is not. If we want to keep the idea of a safe mode around, I think that the current system needs to go first before a new system can be implemented.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Is there an issue open to remind us of implementing something better? If not, that should probably done before merge.

**Comment by fanquake** [comment]
@MarcoFalke The "something better" is likely to be hashed out in the comments here, an issue can probably be opened after that.

**Comment by laanwj** [comment]
I'm not sure we need "something better" for safe mode. We need something better for fork/isolation detection, which would generate a warning, but I don't think safe mode (as in, automatically disabling RPC calls) needs to be brought back.

**Comment by achow101** [comment]
The rebase looks right, utACK 2ae705d84178fb9faa49f92091206e92379a2c63

**Comment by jtimon** [comment]
utACK 2ae705d84178fb9faa49f92091206e92379a2c63

**Comment by sipa** [comment]
utACK 2ae705d84178fb9faa49f92091206e92379a2c63

**Comment by laanwj** [comment]
> Leftover RPC_FORBIDDEN_BY_SAFE_MODE

I thought about this, but decided to keep it - we wouldn't want to accidentally re-use the number. Could replace it with a comment that the number is reserved, I guess...
 
> Usage of "rpc" in the context of warnings

Ok, will remove that.

**Comment by MarcoFalke** [comment]
Then, it seems adjusting the comment slightly will help for future reference. Otherwise some linter will come around and remove it ;)

**Comment by laanwj** [comment]
> Then, it seems adjusting the comment slightly will help for future reference. Otherwise some linter will come around and remove it ;)

Yes - I think I'll move it to a 'reserved' section.

**Comment by laanwj** [comment]
Added commits:

###     rpc: Move RPC_FORBIDDEN_BY_SAFE_MODE code to reserved section
    
Although this code is no longer ever sent back after removing safe mode, it would be unwise to remove it from the header.
    
For one, it would be bad to accidentally re-use the number.
    
Also some API documentation / bindings are directly generated from the .h file - this is why the "Aliases for backward compatibility" are there. We don't want to break code that relies on this error code existing, even if it's never generated.
    
So keep it around but move it to a reserved section.

### Remove "rpc" category from GetWarnings

No longer used after removing safe mode.
    
This function can likely be simplified more, but I'll leave that for later to make this easy to review.

**Comment by MarcoFalke** [comment]
Thanks. utACK d8e9a2a

**Comment by practicalswift** [comment]
utACK d8e9a2ac74e1071c9a92b9858b7ed3143413ee94

Nice cleanup!

**Review by promag — COMMENTED** [review]
utACK d8e9a2a.

I guess it doesn't make sense to add `assert(code != RPC_FORBIDDEN_BY_SAFE_MODE)` to `JSONRPCError`.

**Comment by practicalswift** [comment]
@promag Why wouldn't that make sense? Explicit is better than implicit :-)

**Comment by laanwj** [comment]
I'm not going to add that assert. In the unlikely case that that happens, returning that error code would be preferable to crashing the whole process with an assert error. It also feels like overdesign to add a consistency check for this.

**Comment by practicalswift** [comment]
@laanwj I see your point w.r.t. possible impact of returning the now obsolete error code. You made me change my mind:

-1 for adding `assert(code != RPC_FORBIDDEN_BY_SAFE_MODE)` to `JSONRPCError`

:-)

**Comment by MarcoFalke** [comment]
Clearly, an assert in rpc code makes no sense... I think this is ready for merge, since we reached our final destination, the bike shed.

**Pull request merged**
