### PR TITLE
log: Avoid treating remote misbehvior as local system error

### PR DESCRIPTION
**Pull request by maflcko**
When logging failures of `CheckBlockHeader` (high-hash), they are always logged as system error. This is problematic for several reasons:

* Submitting a blockheader that fails `CheckBlockHeader` over RPC will result in a debug log line that starts with `ERROR`. Proper behaviour should be to log not anything and instead only return the failure reason to the RPC user. This pull does not fix this issue entirely, but is a good first step in the right direction.

* A misbehaving peer that sends us an invalid block header that fails `CheckBlockHeader` will result in a debug log line that starts with `ERROR`. Proper behavior should be to log the remote peer misbehavior if logging for that category was enabled. This pull fixes this issue for `CheckBlockHeader` and other functions can be adjusted as well if needed in follow-ups. This should be a good first step in the right direction.

### CODE REVIEW

**Comment by jonatack** [comment]
Concept ACK. A quick skim of the code LGTM.

**Comment by practicalswift** [comment]
ACK fac66194e4028206b641fe20743ee495ca970025 -- patch looks correct and misbehaving peers should not be able to cause us to write to disk

**Comment by practicalswift** [comment]
ACK fa3e94a3353dbbed98a15dd538fe87c153b821e9 -- patch looks correct and misbehaving peers should not be able to cause us to write to disk

**Comment by MarcoFalke** [comment]
Please excuse the repeated force pushes. There has been a windows cross compile failure, which should now be fixed.

**Comment by laanwj** [comment]
Looks good to me. Validation errors, definitely for network-received transactions, should not spam the log with errors by default. I thought we had caught all of these by now but apparently not, good catch.
The refactor seems unrelated but looks like a good change to me.
ACK fa492895b572a1196ca8652006b6fc2fa1d16951

**Comment by practicalswift** [comment]
re-ACK fa56eda58e5ec2f2345bbe14c798e83f2abb4728

**Pull request merged**
