### PR TITLE
[QA] add multisig rpc tests

### PR DESCRIPTION
**Pull request by jonasschnelli**
Wrote this during some educational tests. Could also be useful for others trying to get more into multisig.
And tests will always help to improve maintainability.

### CODE REVIEW

**Comment by gavinandresen** [comment]
Tested ACK: more tests is good.

RE: having a 2-of-3 count as spendable: WAAAY back when I implemented P2SH support to the wallet I decided that the safest thing to do would be to only count as spendable outputs for which you had ALL of the keys.

The double-spend / conflicting transaction code is much better now, so I'm not worried any more, and would be in favor of changing to counting any output for which you have enough keys to fully sign count as spendable (assuming we have good regression tests like this one to go along with that change, of course).

**Comment by jgarzik** [comment]
ut ACK

**Comment by jonasschnelli** [comment]
Rebased and adapted `setgenerate()` to `.generate()`.
Hope for a quick merge.

**Comment by paveljanik** [comment]
utACK. Please fix the typo in the commit message (mutlisig).

**Comment by jonasschnelli** [comment]
@paveljanik: fixed. Thanks @paveljanik!

**Pull request merged**
