### PR TITLE
[0.13] Backports

### PR DESCRIPTION
**Pull request by maflcko**
Several test and rpc related backports. (Minor non blocking fixes)

Created with the backport script by @luke-jr

### CODE REVIEW

**Comment by fanquake** [comment]
This should wait for #8882 given that #8854 is included.

**Comment by instagibbs** [comment]
Diff review ACK https://github.com/bitcoin/bitcoin/pull/8866/commits/5e0dd9e07c02422a263cc14a173d4ee21a7c1393  

(only text that is different is the getinfo deprecation non-backport in tests)

**Comment by fanquake** [comment]
Also reviewed the diffs. Only difference is text in https://github.com/bitcoin/bitcoin/pull/8866/commits/794b007896aae7b180bdfc771bb4e1656a3e3329 vs https://github.com/MarcoFalke/bitcoin/commit/fa6e71b27d00766897f3e69775d450924a58a153

ACK https://github.com/bitcoin/bitcoin/pull/8866/commits/5e0dd9e07c02422a263cc14a173d4ee21a7c1393

**Comment by MarcoFalke** [comment]
I think those are all the qa/rpc/doc changes for 0.13.1; This should be ready now.

**Comment by laanwj** [comment]
Yes, this is ready. Can't merge it though while I'm in Milan so feel free to do so.

**Pull request merged**
