### PR TITLE
scripted-diff: Replace deprecated C headers

### PR DESCRIPTION
**Pull request by hebasto**
This PR replaces deprecated C headers with C++ ones for all repo except [subtrees](https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md#subtrees) to not pollute the global namespace as much as possible.

Rationale:
1. ISO/IEC 14882:2011, Annex C, C.3.1:
> For compatibility with the Standard C library, the C++ standard library provides the 18 C headers (D.5), but their use is _deprecated_ in C++.

2. ibid, Annex D, D.5:
> Every C header, each of which has a name of the form `name.h`, behaves as if each name placed in the standard library namespace by the corresponding `cname` header is placed within _the global namespace_ scope.

> [ _Example:_ The header `<cstdlib>` assuredly provides its declarations and definitions within the namespace `std`. It may also provide these names within the global namespace. The header `<stdlib.h>` assuredly provides the same declarations and definitions within the global namespace, much as in the C Standard. It may also provide these names within the namespace `std`. — _end example_ ]

### CODE REVIEW

**Comment by laanwj** [comment]
There's nothing about C/C++ headers in the developer notes. This would have to be added first with a clear rationale first before even considering a global update. 

Personally I've never seen the point of the C++-specific header names, as far as I know they're simply indirections that include the original file. Many, if not most, C++ projects use the C header names. If it's only cosmetic then NACK from me.

**Comment by promag** [comment]
Are there advantages? Otherwise NACK.

**Comment by hebasto** [comment]
@laanwj @promag 
Thank you for reviews. The only advantage of this PR is to keep the global namespace as clean as possible (PR's description has been updated with a rationale).

> ... they're simply indirections that include the original file.

e.g. `cstring` from my system:
```
...
#include <string.h>
...
// Get rid of those macros defined in <string.h> in lieu of real functions.
#undef memchr
#undef memcmp
#undef memcpy
... // total 22 undefs
```

**Comment by promag** [comment]
I think that's a really small advantage, but not too bad considering it's a scripted diff. I think you could simplify the script by using multiple substitutions with only 1 sed?

I'm neutral on this one.

**Comment by MarcoFalke** [comment]
If this would help enforcing the `std::` prefix (see #13227), I'd be concept ACK, but it seems like those changes have no effect and are purely stylistic?

**Comment by practicalswift** [comment]
ACK 03b645bfdbae164bc1f9157b505255eb68af1c02

**Comment by hebasto** [comment]
@MarcoFalke Thank you for your review.
> Also, there have been two similar pull requests in the past:
> - #11261
> - #12184

I supposed that but haven't managed to find these PRs. Thank you for pointing them out. It seems another similar PR will come next year :)

> ... but it seems like those changes have no effect and are purely stylistic?

IMO, using deprecated features is not a kind of stylistic or cosmetic matter.

**Comment by hebasto** [comment]
@laanwj 
> There's nothing about C/C++ headers in the developer notes

Cherry-picked @practicalswift's 2942efa19a73841e6c947df077d9b9622002908b commit:

> Added a note about the preference of `#include <cxxx>` in the developer notes.

**Comment by practicalswift** [comment]
utACK 0e1379a155a7e685ed5e141ad99757597f3599a9

**Comment by MarcoFalke** [comment]
The scripted diff looks very verbose and is not easy to review. Mind to compress it a bit?

**Comment by practicalswift** [comment]
@MarcoFalke @hebasto Suggestion:

```
HEADERS="assert|errno|limits|math|signal|stdarg|stddef|stdint|stdio|stdlib|string"
git grep -lE "^#include <(${HEADERS})\.h>" -- ":(exclude)src/univalue/" ":(exclude)src/leveldb/" ":(exclude)src/secp256k1/" ":(exclude)src/crypto/ctaes/" "*.cpp" "*.h" | \
    xargs sed -i -E "s/#include <(${HEADERS})\.h>/#include <c\1>/g"
```

**Comment by laanwj** [comment]
I still don't really see the point, this is another one of those PRs that change a substantial part of the code (130 files!) without actually changing things from the user perspective.

What also bothers me is that only a part of the C headers has a designated C++ replacement (say, not the BSD sockets or POSIX ones), and you'll need to memorize which ones to write in the new and old style.

**Comment by promag** [comment]
In addition to @laanwj comment, there is nothing to prevent adding back, for instance, `#include <stdio.h>`, which we can easily ignore while reviewing.

**Comment by hebasto** [comment]
@laanwj I'm appreciate your position.
> I still don't really see the point...

The point is the compliance with C++ ISO/IEC 14882:2011 Standard.

> ... this is another one of those PRs that change a substantial part of the code (130 files!) without actually changing things from the user perspective.

Yes, it is. This PR is not about the user perspective.

> What also bothers me is that only a part of the C headers has a designated C++ replacement (say, not the BSD sockets or POSIX ones)...

You're right. Not all headers are covered by C++ ISO/IEC 14882:2011 Standard.

> ... and you'll need to memorize which ones to write in the new and old style.

Is it a job for a kind of linter?

@promag 
> In addition to @laanwj comment, there is nothing to prevent adding back, for instance, `#include <stdio.h>`, which we can easily ignore while reviewing.

Updated developer notes and linter rules can help.

**Comment by laanwj** [comment]
> The point is the compliance with C++ ISO/IEC 14882:2011 Standard.

This is not in itself a goal.
Look, we have *603* open issues. If you're not solving any of them, you're just creating extra work for maintainers.

**Pull request closed without merging**
