### PR TITLE
WIP NOMERGE [bench] gitian builds for OP_IF bench

### PR DESCRIPTION
**Pull request by maflcko**
Get gitian builds for two revisions, with and without #16902

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Tested on ARM:

Current master (with optimizations):

```
VerifyNestedIfScript, 5, 100, 0.25091, 0.000499568, 0.000508809, 0.000500318
```

This pull (without the opt):

```
VerifyNestedIfScript, 5, 100, 0.505166, 0.00100926, 0.0010135, 0.00100959
```

**Comment by MarcoFalke** [comment]
@fjahr , would be nice if you can test this to compare against https://github.com/bitcoin/bitcoin/pull/16902#issuecomment-585751558

**Comment by MarcoFalke** [comment]
@fjahr Alternatively, it would be nice to know what optimization flags you used to compile https://github.com/bitcoin/bitcoin/pull/16902#issuecomment-585751558

**Comment by fjahr** [comment]
> @fjahr Alternatively, it would be nice to know what optimization flags you used to compile [#16902 (comment)](https://github.com/bitcoin/bitcoin/pull/16902#issuecomment-585751558)

Just the defaults of `./configure` but I am also compiling this PR right now and will post results soon.

**Comment by MarcoFalke** [comment]
>  compiling this PR right now

The pr was mostly to get two gitian builds for osx (`bitcoin-0.19.99-osx64.tar.gz`). They are using the release compile flags and a cross compiler.

**Comment by fjahr** [comment]
> The pr was mostly to get two gitian builds for osx (`bitcoin-0.19.99-osx64.tar.gz`). They are using the release compile flags and a cross compiler.

Sorry, misread at first, here are results for `bitcoin-0.19.99-osx64.tar.gz`.

Master:
```
$ bin/bench_bitcoin -filter=VerifyNestedIfScript -evals=50
# Benchmark, evals, iterations, total, min, max, median
VerifyNestedIfScript, 50, 100, 1.88564, 0.000253594, 0.00063017, 0.000371099
VerifyNestedIfScript, 50, 100, 1.89325, 0.000237669, 0.000570061, 0.000369836
VerifyNestedIfScript, 50, 100, 1.94918, 0.000245143, 0.000753701, 0.000398808
```

Master and this PR:
```
$ bin/bench_bitcoin -filter=VerifyNestedIfScript -evals=50
# Benchmark, evals, iterations, total, min, max, median
VerifyNestedIfScript, 50, 100, 1.47942, 0.000233691, 0.000447447, 0.000285911
VerifyNestedIfScript, 50, 100, 1.52134, 0.000252425, 0.000506466, 0.000287488
VerifyNestedIfScript, 50, 100, 1.49092, 0.000252439, 0.000458893, 0.000286676
```

**Comment by MarcoFalke** [comment]
Hmmm :thinking: Now it seems to even slow it down by a bit. (Master should be the faster one)

**Comment by fjahr** [comment]
> Hmmm 🤔 Now it seems to even slow it down by a bit. (Master should be the faster one)

Yeah, I had some direct exchanges with @ajtowns as well after my results on #16902 but we could not figure it out. Let me know if you want me to do more specific testing or investigate my system aside from the information I shared so far.

**Comment by MarcoFalke** [comment]
The hardware you are using and the version of the operating system would help to check if this can be reproduced or if it is only happening on your end.

**Comment by fjahr** [comment]
I think the most relevant info is:
- MacBook Pro (13-inch, 2016)
- Intel(R) Core(TM) i5-6287U CPU @ 3.10GHz
- macOS 10.15.3 (latest stable)

**Comment by MarcoFalke** [comment]
Testing on a mac-mini shows the same result: Slower on master (the optimized version) and faster with the old code:

```
mac-mini:~ marco$ ./master/bitcoin-0.19.99/bin/bench_bitcoin -filter=VerifyNestedIfScript -evals=50 
# Benchmark, evals, iterations, total, min, max, median
VerifyNestedIfScript, 50, 100, 0.884273, 0.000143609, 0.000295676, 0.000151077

mac-mini:~ marco$ ./old/bitcoin-0.19.99/bin/bench_bitcoin -filter=VerifyNestedIfScript -evals=50 
# Benchmark, evals, iterations, total, min, max, median
VerifyNestedIfScript, 50, 100, 0.782465, 0.000150363, 0.000179858, 0.000153508

**Comment by ajtowns** [comment]
> Testing on a mac-mini shows the same result:

Super weird. Maybe try setting `nOpCount = 0;` prior to the `++nOpCount > MAX_OPS_PER_SCRIPT` check in script/interpreter.cpp and check to see what the behaviour is with much larger numbers of OP_IFs or OP_1s in bench/verify_script.cpp? If your script is `{1 IF}*x NOP*y ENDIF*x 1` your runtime should be O(3x+y) in master, but O(3x+y+xy) with the revert, which ought to be noticible at the some point. (You need to change the 1000 OP_1's to OP_NOP's or you'll also violate the `stack.size() + altstack.size() > MAX_STACK_SIZE` test)

**Comment by MarcoFalke** [comment]
With the new bench framwork I get this:

This pull with the last two commits dropped:

```
mac-mini:bitcoin-core marco$ ./src/bench/bench_bitcoin --filter=VerifyNestedIfScript
Warning, results might be unstable:
* NDEBUG not defined, assert() macros are evaluated

Recommendations
* Make sure you compile for Release

|               ns/op |                op/s |    err% |     total | benchmark
|--------------------:|--------------------:|--------:|----------:|:----------
|          154,373.00 |            6,477.82 |    9.4% |      0.00 | :wavy_dash: `VerifyNestedIfScript` (Unstable with ~1.0 iters. Increase `minEpochIterations` to e.g. 10)
mac-mini:bitcoin-core marco$ ./src/bench/bench_bitcoin --filter=VerifyNestedIfScript
Warning, results might be unstable:
* NDEBUG not defined, assert() macros are evaluated

Recommendations
* Make sure you compile for Release

|               ns/op |                op/s |    err% |     total | benchmark
|--------------------:|--------------------:|--------:|----------:|:----------
|          141,380.00 |            7,073.14 |    0.5% |      0.00 | `VerifyNestedIfScript`
mac-mini:bitcoin-core marco$ ./src/bench/bench_bitcoin --filter=VerifyNestedIfScript
Warning, results might be unstable:
* NDEBUG not defined, assert() macros are evaluated

Recommendations
* Make sure you compile for Release

|               ns/op |                op/s |    err% |     total | benchmark
|--------------------:|--------------------:|--------:|----------:|:----------
|          141,859.00 |            7,049.25 |    0.4% |      0.00 | `VerifyNestedIfScript`
```


This pull:
```
mac-mini:bitcoin-core marco$ ./src/bench/bench_bitcoin --filter=VerifyNestedIfScript
Warning, results might be unstable:
* NDEBUG not defined, assert() macros are evaluated

Recommendations
* Make sure you compile for Release

|               ns/op |                op/s |    err% |     total | benchmark
|--------------------:|--------------------:|--------:|----------:|:----------
|          201,531.00 |            4,962.02 |   26.1% |      0.00 | :wavy_dash: `VerifyNestedIfScript` (Unstable with ~1.0 iters. Increase `minEpochIterations` to e.g. 10)
mac-mini:bitcoin-core marco$ ./src/bench/bench_bitcoin --filter=VerifyNestedIfScript
Warning, results might be unstable:
* NDEBUG not defined, assert() macros are evaluated

Recommendations
* Make sure you compile for Release

|               ns/op |                op/s |    err% |     total | benchmark
|--------------------:|--------------------:|--------:|----------:|:----------
|          148,760.00 |            6,722.24 |    0.3% |      0.00 | `VerifyNestedIfScript`
mac-mini:bitcoin-core marco$ ./src/bench/bench_bitcoin --filter=VerifyNestedIfScript
Warning, results might be unstable:
* NDEBUG not defined, assert() macros are evaluated

Recommendations
* Make sure you compile for Release

|               ns/op |                op/s |    err% |     total | benchmark
|--------------------:|--------------------:|--------:|----------:|:----------
|          149,385.00 |            6,694.11 |    0.3% |      0.00 | `VerifyNestedIfScript`

**Comment by MarcoFalke** [comment]
So it does seem to get slightly faster, which might point to a problem with the current bench framework.

**Pull request closed without merging**
