### PR TITLE
doc: Remove Boost build note from build-unix.md

### PR DESCRIPTION
**Pull request by fanquake**
We don't have build instructions for any other dependency, and in any case, this isn't something we should maintain in our docs. If someone wants to know how to build Boost, or any other dependency, they can look at the relevant website / external build documentation.

### CODE REVIEW

**Review by shaavan — COMMENTED** [review]
Concept ACK

It makes sense to remove Boost build notes, as:
1. As mentioned by @fanquake, build notes are not maintained for other libraries.
2. Building Boost yourself is not an immediate necessity to compiling bitcoin.
3. The official documentation of building boost is quite good and easy to follow through, so we don’t need to explain it on our docs.

However, removing Boost build notes intuitively kind of seems off to me. I would like to listen to other reviewers’ opinions before making a final decision.

As for removing unnecessary “optional,” I am ACK on that. Cheers!

**Review by jarolrod — COMMENTED** [review]
ACK ea360d69e5fec8f96630354c4adc9df9dbab8329

- [x] b97185812e6fa21461d1114c7e62a247cfa74ff9
  - ACK because it's not something we need in our build notes
- [x] ea360d69e5fec8f96630354c4adc9df9dbab8329
  - Yep, this is redundant given the table title

**Comment by instagibbs** [comment]
@shaavan no informed opinion myself but I'd flip the question: would you ACK the addition of these docs?

**Comment by MarcoFalke** [comment]
I think our recommended way to use dependencies is system packages or depends. I wasn't aware there is even a doc on how to build boost separately. And I am still not entirely sure why we have the build_bdb script, given that there is depends.

cr ACK

**Comment by MarcoFalke** [comment]
It looks like the note on building boost was added before the depends system.

**Comment by katesalazar** [comment]
So QR is now required, right?

**Comment by fanquake** [comment]
> So QR is now required, right?

No.

**Comment by katesalazar** [comment]
ACK.

**Comment by katesalazar** [comment]
Unless it's a recent thing, there's no need to bootstrap Boost as root.

**Pull request merged**
