### PR TITLE
[tests] Add uacomment tests

### PR DESCRIPTION
**Pull request by mess110**
Checks for setting the value, max length and reserved characters

### CODE REVIEW

**Comment by laanwj** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/11486/commits/c5dfa90aab53832c9ad339360d11d6635a26ba6b, thanks for adding tests!

**Comment by promag** [comment]
Nice. missing one test with multiple `-uacomment` values.

**Comment by mess110** [comment]
@promag by default test nodes have 1 uacomment set which I test here: https://github.com/bitcoin/bitcoin/pull/11486/files#diff-9bf941056cb812e87bf8826dd7a34952R18 and the following test checks for 2 uacomments (default + foo)

I can add another one if more people think it is needed, but for now, I think it is enough.

Thanks for the review

**Comment by promag** [comment]
Ahh yes, restart with extra args.

utACK c5dfa90 then.

**Comment by achow101** [comment]
utACK c5dfa90aab53832c9ad339360d11d6635a26ba6b

**Pull request merged**
