### PR TITLE
gui: Don't access static members from class instances

### PR DESCRIPTION
**Pull request by practicalswift**
Don't access static members from class instances.

Be explicit about the fact that the members we're accessing are static.

### CODE REVIEW

**Comment by practicalswift** [comment]
After posting this PR I see that the Qt documentation has an example with `app.exec();`. Am I mistaken here? :-)

**Comment by Empact** [comment]
I'm not sure this is an improvement...

**Comment by sipa** [comment]
I believe this is generally a good idea.

**Comment by promag** [comment]
Concept ACK.

Are these the only cases?

**Comment by practicalswift** [comment]
@promag Yes AFAIK :-)

**Comment by laanwj** [comment]
> I'm not sure this is an improvement...

Me neither TBH. Let's not make changes just to make changes!

Please illustrate how this avoids bugs, otherwise I don't see the point. Currently it's possible to change the class and the calls will go to exactly the same class.

**Comment by practicalswift** [comment]
Closing due to lack of consensus ACK :-)

**Pull request closed without merging**
