### PR TITLE
tests: RPC bumpfee totalFee deprecation

### PR DESCRIPTION
**Pull request by jonatack**
This is a follow-up to PR #15996 which deprecates the `totalFee` argument in RPC bumpfee.

If that PR is merged, several of the wallet_bumpfee tests will need to be updated to not use `totalFee`.

But first, we need a test for the deprecation itself. The intent of this PR is to add that coverage.

### CODE REVIEW

**Comment by jonatack** [comment]
(The tidy up commits are very much optional).

**Comment by fridokus** [comment]
ACK 96f3be13d96becbd9586c6a4476329964cf625fd
Ran functional tests locally and reviewed the code. No manual tests.

**Comment by fanquake** [comment]
@fridokus Thanks for the review. Given that this PR builds on top of #15996, you might also be interested in testing and `ACK`ing there, especially since the commits from `15996` that are part of this PR are no longer up to date.

**Comment by fridokus** [comment]
Aha. Will do :)

**Comment by jnewbery** [comment]
@jonatack - the commit that adds the test has been added to #15996. Are you happy to close this PR now? (you can either open a PR for the tidy-up commits or just drop them)

**Comment by jonatack** [comment]
@jnewbery Sure. My intent was to update the tests to not use totalFee but can do it in a separate PR and not divert further review time.

**Comment by jonatack** [comment]
(Thank you for the review, @fridokus.)

**Pull request closed without merging**
