### PR TITLE
[qa] Fix block message processing error in sendheaders.py

### PR DESCRIPTION
**Pull request by sdaftuar**
Introduced in #10169 

@jnewbery

### CODE REVIEW

**Comment by MarcoFalke** [comment]
utACK 38bb21bb409d4da4ffe6f81f9b060a75334d6fb6

**Comment by jnewbery** [comment]
good catch!

The `last_message["block"]` variable isn't actually used at all in this test (and `last_block` wasn't used before my refactor which introduced this bug), so we can actually just remove the `on_block()` method override entirely.

**Comment by sdaftuar** [comment]
@jnewbery Done.

**Comment by promag** [comment]
utACK f1bf311.

**Comment by fanquake** [comment]
utACK f1bf311

**Pull request merged**
