### PR TITLE
gui: Drop calls to QCoreApplication::processEvents

### PR DESCRIPTION
**Pull request by promag**
Addresses #16875. For now just remove the calls.

These were introduced in #593 and #12818.

### CODE REVIEW

**Comment by promag** [comment]
Some discussion in https://stackoverflow.com/a/1386160

**Comment by promag** [comment]
Could I have gitian build?

**Comment by fanquake** [comment]
It looks like this has broken some GUI tests [585229862](https://travis-ci.org/bitcoin/bitcoin/jobs/585229862), [585229863](https://travis-ci.org/bitcoin/bitcoin/jobs/585229863), [585229866](https://travis-ci.org/bitcoin/bitcoin/jobs/585229866):
```bash
********* Start testing of WalletTests *********
Config: Using QtTest library 5.9.5, Qt 5.9.5 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 7.4.0)
PASS   : WalletTests::initTestCase()
QDEBUG : WalletTests::walletTests() TransactionTablePriv::refreshWallet
QWARN  : WalletTests::walletTests() This plugin does not support propagateSizeHints()
QDEBUG : WalletTests::walletTests() "NotifyTransactionChanged: 12537cd362d98a08b60e15109d9b328ba3c1b42a0b6abc443c3e8c6c58b23cd3 status= 0"
QDEBUG : WalletTests::walletTests() "NotifyTransactionChanged: 864afb476316659fcf6e4717a4daa6d69c51b06b772ec8b3c6d86061856f133e status= 1"
QDEBUG : WalletTests::walletTests() "NotifyAddressBookChanged: mfWxJ45yp2SFn7UciZyNpvDKrzbhyfKrY8  isMine=0 purpose=send status=0"
QWARN  : WalletTests::walletTests() This plugin does not support propagateSizeHints()
QDEBUG : WalletTests::walletTests() "TransactionTablePriv::updateWallet: 12537cd362d98a08b60e15109d9b328ba3c1b42a0b6abc443c3e8c6c58b23cd3 0"
QDEBUG : WalletTests::walletTests() "    inModel=0 Index=86-86 showTransaction=1 derivedStatus=0"
QDEBUG : WalletTests::walletTests() "TransactionTablePriv::updateWallet: 864afb476316659fcf6e4717a4daa6d69c51b06b772ec8b3c6d86061856f133e 1"
QDEBUG : WalletTests::walletTests() "    inModel=1 Index=27-28 showTransaction=1 derivedStatus=1"
QDEBUG : WalletTests::walletTests() "NotifyTransactionChanged: 52b3ca1ca8d757d595ea5501754c0b46762fc69fc1a668ea8fbda0d380a3d3bb status= 0"
QDEBUG : WalletTests::walletTests() "NotifyTransactionChanged: 154297156e2d1cd324cecb6cce2377c90fd6e59c87a12fbd84590809f44dc1f9 status= 1"
FAIL!  : WalletTests::walletTests() Compared values are not the same
   Actual   (transactionTableModel->rowCount({})): 106
   Expected (107)                                : 107
   Loc: [qt/test/wallettests.cpp(175)]
PASS   : WalletTests::cleanupTestCase()
Totals: 2 passed, 1 failed, 0 skipped, 0 blacklisted, 3780ms
********* Finished testing of WalletTests *********
```

**Comment by laanwj** [comment]
These calls are a work-around for doing too much work (and blocking waiting on locks) in the GUI thread, which we very much are guilty of in bitcoin-qt. The idea is to make sure that the window is updated and events are handled before doing something that might take longer.

Calling the function is redundant, sometimes, but should never be a bug.

Do you know why this segfaults in the first place? It seems to point at a different underlying issue and this just triggers it.

**Comment by promag** [comment]
> The idea is to make sure that the window is updated and events are handled before doing something that might take longer.

Meh, I think we agree it's the fix.

> Do you know why this segfaults in the first place? It seems to point at a different underlying issue and this just triggers it.

I don't but will investigate.

**Comment by Sjors** [comment]
#16966 has the side-effect of removing `processEvents` for bump fee

**Comment by jonasschnelli** [comment]
Closing for now. Feel free to reopen if this still makes sense.

**Pull request closed without merging**
