### PR TITLE
Fixed a grammar issue.

### PR DESCRIPTION
**Pull request by ChandlerScheurkogel**

### CODE REVIEW

**Comment by MeshCollider** [comment]
A little bit picky imo, it's not even wrong in the first place. Probably should be 'the' anyway

**Comment by fanquake** [comment]
trivial ACK 1c6ee8a

**Comment by promag** [comment]
Agree with @MeshCollider, the "fix" isn't worth it.

Either way, remove period from PR title and commit message and add reference to `linearize documentation`?

**Comment by laanwj** [comment]
Yeah, I agree this isn't worth it, also the old sentence seems fine to me.

**Comment by Leviathn** [comment]
Old sentence was perfectly fine.

**Pull request closed without merging**
