### PR TITLE
Verify binaries from bitcoincore.org and bitcoin.org

### PR DESCRIPTION
**Pull request by TheBlueMatt**
In preparation for moving the "official" binary host to bitcoincore.org, use it for verifybinaries (and compare with bitcoin.org).

### CODE REVIEW

**Comment by sipa** [comment]
Does this need such hardcoding for those two specific hosts, as opposed to a `for HOST in bitcoin.org bitcoincore.org` loop?

**Comment by TheBlueMatt** [comment]
I mean that's just as much hard coding since it only downloads the binaries from one of the two (and unless you want to depend on bash for arrays.....).

**Comment by sipa** [comment]
I see a wget from both?

**Comment by TheBlueMatt** [comment]
With a very different error message on both :p

**Comment by sipa** [comment]
That seems a silly complication to justify duplicating the logic. Just say "failed to download file X from host Y".

**Comment by TheBlueMatt** [comment]
Well the first error message correctly highlights that it is most likely the user's fault (bad version string), whereas the second is mostly likely servers acting up. Could go further and attempt to download both in any case, however.

**Comment by TheBlueMatt** [comment]
@sipa I added the array-based version at https://github.com/TheBlueMatt/bitcoin/commit/3a60faacd99dc727a43b53ba38966fb1e9cdee1f its more code, and IMO more complex, but if you still prefer it we can do that?

**Comment by laanwj** [comment]
> I mean that's just as much hard coding since it only downloads the binaries from one of the two (and unless you want to depend on bash for arrays.....).

I can't believe we're having a discussion whether to use arrays in 2017. Shellscript is horrible.

**Comment by TheBlueMatt** [comment]
Heh, well I realized this script is already full of bashism, so I dont really care either way...its more code with the arrays but if we ever plan on adding more mirrors (I dont think so?) then it might be helpful.

**Comment by jtimon** [comment]
Concept ACK

**Comment by laanwj** [comment]
So, okay, can we make a decision here? Arrays or not? Should we throw a coin?

**Comment by TheBlueMatt** [comment]
Coin sounds good. My very weak vote is leave it as-is cause I find it less confusing, but dont care strongly either way.

**Comment by sipa** [comment]
If it is this complicated, I retract my suggestion :)

**Comment by laanwj** [comment]
Just going to merge this, it's outrageous to keep tools/tests pulls like this open if they simply do correctly what they should do. Cleaning up the code can be done later.

**Pull request merged**
