### PR TITLE
contrib: Remove unused import string

### PR DESCRIPTION
**Pull request by maflcko**
Tiny oversight in #11881, that broke travis.

### CODE REVIEW

**Comment by jnewbery** [comment]
utACK 05120ee755f03582c77109eb4f109b68515337f1

**Comment by MeshCollider** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/12821/commits/05120ee755f03582c77109eb4f109b68515337f1

**Comment by ajtowns** [comment]
ACK 05120ee755f03582c77109eb4f109b68515337f1

**Review by randolf — APPROVED** [review]

**Review by ken2812221 — APPROVED** [review]

**Comment by promag** [comment]
utACK 05120ee.

**Comment by conscott** [comment]
ACK 05120ee755f03582c77109eb4f109b68515337f1

**Pull request merged**
