### PR TITLE
[Doc] Fix link for BIP-159 pull request

### PR DESCRIPTION
**Pull request by azuchi**
The link of the pull request for BIP-159 described in bips.md was a different link.

### CODE REVIEW

**Comment by MeshCollider** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/12143/commits/91769d6e288891cbfebcfe7ad71968de58315574, nice spot

**Comment by randolf** [comment]
The wrong link doesn't mention BIP159 in its title (the correct link does), so this change seems to be legitimate.

**Review by jonasschnelli — APPROVED** [review]
ACK 91769d6e288891cbfebcfe7ad71968de58315574

**Comment by jonasschnelli** [comment]
Thanks. My mistake.

**Comment by tonyalester** [comment]
ty

**Pull request merged**
