### PR TITLE
Use compiler byteswap functions if available

### PR DESCRIPTION
**Pull request by DesWurstes**

### CODE REVIEW

**Comment by practicalswift** [comment]
What would be the appropriate benchmark for this change?

**Comment by sipa** [comment]
I believe this won't have any effect. Modern compilers recognize the pattern used in the current code as byteswapping, and will use an appropriate native operation for it if available. I think it's likely the binary output is in fact identical before and after.

That said, it's probably more clear and reliable to use the builtin when available.

**Comment by jgarzik** [comment]
Agree with @sipa 's first paragraph.

Typically the modern compilers _plus system headers_ do a better job, and are better maintained By The People Who Know These Things (gcc/llvm/glibc people).

**Comment by DesWurstes** [comment]
I've experimented: GCC can see that pattern since 4.5 and Clang can see it since 3.0. MSVC still can't recognize `bswap64`.

So, closing it.

**Pull request closed without merging**
