### PR TITLE
Update msvc build to use Qt5.12.10 binaries.

### PR DESCRIPTION
**Pull request by sipsorcery**
bitcoin_qt5 12 10

### CODE REVIEW

**Comment by fanquake** [comment]
Concept ACK - thanks for updating this.

**Comment by hebasto** [comment]
Concept ACK.

**Comment by kiminuo** [comment]
Concept ACK

It works for me:

```powershell
# unzip https://github.com/sipsorcery/qt_win_binary/releases/download/qt51210x64_vs2019_1694/Qt5.12.10_x64_static_vs2019_1694.zip to C:\Qt5.12.10_x64_static_vs2019_1694
cd build_msvc
python msvc-autogen.py  # as a substution for "py -3 msvc-autogen.py"
msbuild /m bitcoin.sln /p:Platform=x64 /p:Configuration=Release /t:build
```

image 🎉

**Review by hebasto — APPROVED** [review]
ACK f02ca7a354b69e3959d513cd36637507cbc33e78, I made a customized AppVeyor build with an artifact: https://ci.appveyor.com/project/hebasto/bitcoin/builds/38786868/artifacts

The resulted build was tested on Windows 10 20H2 (build 19042.928):
Screenshot from 2021-04-20 15-11-35

**Pull request merged**
