### PR TITLE
Performance: Prefer prefix operator for non-primitive types

### PR DESCRIPTION
**Pull request by maflcko**

### CODE REVIEW

**Comment by paveljanik** [comment]
Do you have some numbers? It would be nice to see some benchmarks added first and then comparing ++them with++ 👍

**Comment by dcousens** [comment]
utACK fa18923,  but I really doubt this will be measurable.

**Comment by MarcoFalke** [comment]
This was suggested in https://github.com/bitcoin/bitcoin/pull/7656#discussion-diff-56476755, but apparently for base58 this has 0 effect, the bench binaries are identical. :laughing: 

Some other hunks did not produce identical binaries, so in theory there could be a performance difference. Though, I don't think the performance gain matters in those other places.

**Comment by UdjinM6** [comment]
Not sure about specific cases here but in general performance gain could be quite significant: http://stackoverflow.com/a/9519095
Also it might simply be a good practice to use prefix operators by default and postfix only when needed imo.

**Comment by sipa** [comment]
In practice I expect this to have very little effect for containers with 'simple' iterators (where the iterator essentially consists of a single pointer). This is the case for `std::vector`, `std::list`, `std::set`, `std::map`, `std::multimap` (but not for `std::vector<bool>` or `std::deque`). In this case, technically a copy is made before returning, but the compiler will just discard it.

**Comment by paveljanik** [comment]
Thank you for testing this Marco!

**Comment by laanwj** [comment]
> Some other hunks did not produce identical binaries, so in theory there could be a performance difference. Though, I don't think the performance gain matters in those other places.

Even is changing it retroactively is not deemed worth it, let's try to encourage `++x` iso `x++` usage in new code, that's pretty uncontroversial.

**Comment by sipa** [comment]
> Even is changing it retroactively is not deemed worth it, let's try to encourage ++x iso x++ usage in new code, that's pretty uncontroversial.

Agree. Let's add that to `doc/developer-notes.md`.

**Pull request closed without merging**
