### PR TITLE
net processing: Remove dropmessagestest

### PR DESCRIPTION
**Pull request by jnewbery**
-dropmessagestest is a command line option that causes 1 in n received
messages to be dropped. The Bitcoin P2P protocol is stateful and in
general cannot handle messages being dropped. Dropped
version/verack/ping/pong messages will cause the connection to time out
and be torn down. Other dropped messages may also cause the peer to
believe that the peer has stalled and tear down the connection.

It seems difficult to uncover any actual issues with -dropmessagestest,
and any coverage that could be generated would probably be easier to
trigger with fuzz testing.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
cr ACK 176325a5a47befe32d480b3dc206dd0e64e04b21

**Comment by practicalswift** [comment]
cr ACK 176325a5a47befe32d480b3dc206dd0e64e04b21

Thanks for pruning options.

More generally: Concept ACK on removing obsolete/unused options.

Less is sometimes more when it comes to the number of knobs presented to end-users :)

**Review by amitiuttarwar — APPROVED** [review]
ACK 176325a5a47befe32d480b3dc206dd0e64e04b21 
- agree with the rationale in OP 
- sanity checked that this arg isn't used anywhere 
- did some code archeology because I was curious why this was introduced, looks like it can be traced back to [satoshi code](https://github.com/bitcoin/bitcoin/commit/1a01afab238cbf48331559f4be4b20f9027c53b4#diff-608d8de3fba954c50110b6d7386988f27295de845e9d7174e40095ba5efcf1bbR1722)

**Comment by dhruv** [comment]
cr ACK 176325a

Checked that the only use of `-dropmessagestest` is also removed in this PR. I can't think of any use cases where this is useful as the non-determinism makes it hard to test resulting behavior.

**Pull request merged**
