### PR TITLE
build: set OSX_MIN_VERSION to 10.15

### PR DESCRIPTION
**Pull request by fanquake**
Taken out of #20744, as splitting up some of the build changes was mentioned [here](https://github.com/bitcoin/bitcoin/pull/22937#discussion_r707303172).

This is required to use `std::filesystem` on macOS, as support for it only landed in the libc++.dylib shipped with 10.15. So if we want to move to using `std::filesystem` for `23.0`, this bump is required.

See also: https://developer.apple.com/documentation/xcode-release-notes/xcode-11-release-notes

> Clang now supports the C++17 \<filesystem\> library for iOS 13, macOS 10.15, watchOS 6, and tvOS 13.

macOS 10.15 was released in October 2019. macOS OS's seem to have a life of about 3 years, so it's possible that 10.14 will become officially unsupported by the end of 2021 and prior to the release of 23.0.

Guix builds:
```bash
bash-5.1# find guix-build-$(git rev-parse --short=12 HEAD)/output/ -type f -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum
abc8b749be65f1339dcdf44bd1ed6ade2533b8e3b5030ad1dde0ae0cede78136  guix-build-a43b8e955558/output/dist-archive/bitcoin-a43b8e955558.tar.gz
1edcc301eb4c02f3baa379beb8d4c78e661abc24a293813bc9d900cf7255b790  guix-build-a43b8e955558/output/x86_64-apple-darwin19/SHA256SUMS.part
e9dbb5594a664519da778dde9ed861c3f0f631525672e17a67eeda599f16ff44  guix-build-a43b8e955558/output/x86_64-apple-darwin19/bitcoin-a43b8e955558-osx-unsigned.dmg
11b23a17c630dddc7594c25625eea3de42db50f355733b9ce9ade2d8eba3a8f3  guix-build-a43b8e955558/output/x86_64-apple-darwin19/bitcoin-a43b8e955558-osx-unsigned.tar.gz
257ba64a327927f94d9aa0a68da3a2695cf880b3ed1a0113c5a966dcc426eb5e  guix-build-a43b8e955558/output/x86_64-apple-darwin19/bitcoin-a43b8e955558-osx64.tar.gz
```

### CODE REVIEW

**Comment by hebasto** [comment]
Concept ACK.

Also it will make `make deploy` [bug](https://github.com/bitcoin/bitcoin/pull/20422#issuecomment-919012839) on macOS 10.14.6 outdated :)

**Comment by fanquake** [comment]
> Also it will make the make deploy bug on macOS 10.14.6 outdated :)

I've commented on that PR. Given what you've posted it's not exactly clear that is a bug.

**Comment by hebasto** [comment]
Also in https://github.com/bitcoin/bitcoin/blob/4eea1c535d5b96cc7eef17e5988b040b0df1297d//contrib/guix/README.md#L227 s/`darwin18`/`darwin19`/ ?

**Comment by fanquake** [comment]
> Also in 

Done

**Comment by MarcoFalke** [comment]
There was an odd native windows CI failure, which I re-ran: https://cirrus-ci.com/task/6041484689408000

**Comment by hebasto** [comment]
> There was an odd native windows CI failure, which I re-ran: https://cirrus-ci.com/task/6041484689408000

It's a network failure
```
https://github.com/PowerShell/PowerShell/releases/download/v7.1.0/PowerShell-7.1.0-win-x86.zip: WinHttpReceiveResponse() failed: 12030
```
which happens sometimes.

**Review by hebasto — APPROVED** [review]
ACK a43b8e955558483d8893996cc3a67bc74cbaf358

#### Guix build:
```
$ env HOSTS='x86_64-apple-darwin19' ./contrib/guix/guix-build
$ find guix-build-$(git rev-parse --short=12 HEAD)/output/ -type f -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum
abc8b749be65f1339dcdf44bd1ed6ade2533b8e3b5030ad1dde0ae0cede78136  guix-build-a43b8e955558/output/dist-archive/bitcoin-a43b8e955558.tar.gz
1edcc301eb4c02f3baa379beb8d4c78e661abc24a293813bc9d900cf7255b790  guix-build-a43b8e955558/output/x86_64-apple-darwin19/SHA256SUMS.part
e9dbb5594a664519da778dde9ed861c3f0f631525672e17a67eeda599f16ff44  guix-build-a43b8e955558/output/x86_64-apple-darwin19/bitcoin-a43b8e955558-osx-unsigned.dmg
11b23a17c630dddc7594c25625eea3de42db50f355733b9ce9ade2d8eba3a8f3  guix-build-a43b8e955558/output/x86_64-apple-darwin19/bitcoin-a43b8e955558-osx-unsigned.tar.gz
257ba64a327927f94d9aa0a68da3a2695cf880b3ed1a0113c5a966dcc426eb5e  guix-build-a43b8e955558/output/x86_64-apple-darwin19/bitcoin-a43b8e955558-osx64.tar.gz
```

**Comment by laanwj** [comment]
Welcome to the yearly MacOSX bump :smile: 
I guess that's a fact of life, Apple is kind of harsh with regard to backward/forward compatibility (so many quasi-arbitrary changes every release, no beginning in trying to support all combinations…), and besides, MacOS users don't seem to mind.
Concept ACK.

**Comment by fanquake** [comment]
> Welcome to the yearly MacOSX bump 😄
> I guess that's a fact of life, 

At least this time it's also in aide of a larger project goal, which is the migration to `std::filesystem`.

**Review by jarolrod — COMMENTED** [review]
ACK a43b8e9

I have checked that any instances of `*-darwin18` have been updated to `*-darwin-19`, also CI is green 👍.

In terms of timing, it is likely that macOS 10.14 will be depricated around the time that `23.0` is released. This [table](https://en.wikipedia.org/wiki/MacOS_version_history#Releases) confirms the typical lifetime of around 3 years. Additionally, I've noticed other applications I use start to phase out 10.14 support.

Guix Hashes, mine match all posted hashes
```
find guix-build-$(git rev-parse --short=12 HEAD)/output/ -type f -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum

abc8b749be65f1339dcdf44bd1ed6ade2533b8e3b5030ad1dde0ae0cede78136  guix-build-a43b8e955558/output/dist-archive/bitcoin-a43b8e955558.tar.gz
1edcc301eb4c02f3baa379beb8d4c78e661abc24a293813bc9d900cf7255b790  guix-build-a43b8e955558/output/x86_64-apple-darwin19/SHA256SUMS.part
e9dbb5594a664519da778dde9ed861c3f0f631525672e17a67eeda599f16ff44  guix-build-a43b8e955558/output/x86_64-apple-darwin19/bitcoin-a43b8e955558-osx-unsigned.dmg
11b23a17c630dddc7594c25625eea3de42db50f355733b9ce9ade2d8eba3a8f3  guix-build-a43b8e955558/output/x86_64-apple-darwin19/bitcoin-a43b8e955558-osx-unsigned.tar.gz
257ba64a327927f94d9aa0a68da3a2695cf880b3ed1a0113c5a966dcc426eb5e  guix-build-a43b8e955558/output/x86_64-apple-darwin19/bitcoin-a43b8e955558-osx64.tar.gz
```

**Pull request merged**
