### PR TITLE
scripted-diff: Log parameter interaction not thrice

### PR DESCRIPTION
**Pull request by maflcko**
Seems a bit overkill to log the words "parameter interaction" thrice, when at least once is enough. So do that.

Before:

```
2024-06-28T15:30:57Z [init.cpp:745] [InitParameterInteraction] InitParameterInteraction: parameter interaction: -connect or -maxconnections=0 set -> setting -dnsseed=0
```

After:

```
2024-06-28T15:47:27Z [init.cpp:745] [InitParameterInteraction] parameter interaction: -connect or -maxconnections=0 set -> setting -dnsseed=0

### CODE REVIEW

**Comment by paplorinc** [comment]
ACK fa1bc7c88bb720f02955dbe4e2a174b5a52f3af8

**Review by sedited — APPROVED** [review]
Nice, ACK fa1bc7c88bb720f02955dbe4e2a174b5a52f3af8

**Comment by fjahr** [comment]
utACK fa1bc7c88bb720f02955dbe4e2a174b5a52f3af8

**Review by hodlinator — APPROVED** [review]
utACK fa1bc7c88bb720f02955dbe4e2a174b5a52f3af8

Should have already been made less repetitive when moving them into a dedicated function in 411b05ac9511395923976bfbd0c153ddabf2ebcf.

**Pull request merged**
