### PR TITLE
refactor: Remove unused cacheSigStore from CheckInputsFromMempooAndCache

### PR DESCRIPTION
**Pull request by jnewbery**
CheckInputsFromMempoolAndCache() is only called in one place, and
cacheSigStore is set to true in that call site. Remove the argument
entirely.

Also improve commenting.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
unsigned ACK 0a433fc876d82df1005f175c1254fff62f0f36f8 Comment looks good

**Comment by jamesob** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/17242/commits/0a433fc876d82df1005f175c1254fff62f0f36f8

**Comment by laanwj** [comment]
Yay, one boolean argument less.
ACK 0a433fc876d82df1005f175c1254fff62f0f36f8

**Review by fanquake — APPROVED** [review]
ACK 0a433fc876d82df1005f175c1254fff62f0f36f8. Checked that `CheckInputsFromMempoolAndCache` is only called once, in `MemPoolAccept::ConsensusScriptChecks`, and that `cacheSigStore` is true. 

New comments match `CheckInputs` params.

**Comment by promag** [comment]
ACK 0a433fc876d82df1005f175c1254fff62f0f36f8.

**Pull request merged**
