### PR TITLE
rpc, wallet: Expose wallet id in getwalletinfo RPC output

### PR DESCRIPTION
**Pull request by hebasto**
Based on #20205.

### CODE REVIEW

**Comment by jonatack** [comment]
Seems useful. Can haz test?

**Comment by hebasto** [comment]
Rebased 17a20b94be63550fc021b7c6e0ed3d4dce834cdc -> b7eb69c48d1f0411abc16dc3210d86a3d4039fd7 ([pr20243.01](https://github.com/hebasto/bitcoin/commits/pr20243.01) -> [pr20243.02](https://github.com/hebasto/bitcoin/commits/pr20243.02)).

**Comment by luke-jr** [comment]
@jonatack BDB wallets already have an id

**Comment by jonatack** [comment]
Concept ACK, first skim of the code looks reasonable

**Comment by hebasto** [comment]
Waiting for a #20205, and closing for now.

**Pull request closed without merging**
