### PR TITLE
test: remove explicit descriptors=True for createwallet RPC calls

### LINKED ISSUE #24550: remove explicit `descriptors=true` parameter for createwallet RPCs in functional tests
Since the default wallet type was changed to descriptor wallets in https://github.com/bitcoin/bitcoin/pull/23002, there is no need to explicitly pass the `descriptors=true` parameter to `createwallet` RPCs anymore. All of those instances in functional tests should be identified and simplified by omitting the parameter (there is already a PR doing the same for documentation, see #24519).

#### Useful skills:
- Basic Python3 knowledge

#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

### PR DESCRIPTION
**Pull request by prusnak**
because descriptors wallets are created by default since #23002

Fixes https://github.com/bitcoin/bitcoin/issues/24550

### CODE REVIEW

**Comment by michaelfolkson** [comment]
Concept ACK

Some failures on the CI. Will run the tests locally and attempt to debug tomorrow.

**Comment by achow101** [comment]
NACK

Most of these are tests that require that the wallet must be a descriptor wallet. Removing the explicit parameter makes the type depend on the presence of `--descriptors`. If `--legacy-wallet` were provided, the type of wallet created would incorrectly be legacy. Hence the explicit option must remain.

**Comment by michaelfolkson** [comment]
Thanks for this @achow101. This PR and accompanying and issue should be closed then it sounds like. The below is just for my own understanding.

>  If --legacy-wallet were provided, the type of wallet created would incorrectly be legacy

And when you say "incorrectly be legacy" you mean be legacy-bdb rather than legacy-sqlite? As you say in #20160 you need the explicit parameter to switch between descriptor-sqlite (descriptors=True) and legacy-bdb (descriptors=False).

I'm not sure why there aren't just two explicit parameters: descriptors(True/False for whether it uses descriptors or not) and sqlite (True/False for the database choice) rather than descriptors=False implicitly flipping the database choice from sqlite to bdb.

**Comment by theStack** [comment]
> NACK
> 
> Most of these are tests that require that the wallet must be a descriptor wallet. Removing the explicit parameter makes the type depend on the presence of `--descriptors`. If `--legacy-wallet` were provided, the type of wallet created would incorrectly be legacy. Hence the explicit option must remain.

Right, I completely forgot about that! In the test framework calling `node.createwallet` doesn't immediately invoke the RPC, but passes it through an overload wrapper first:
https://github.com/bitcoin/bitcoin/blob/25d045a9ecc24a2752685d176c28f8f75bb100f6/test/functional/test_framework/test_node.py#L749-L752

So agreed, this PR can be closed. Sorry for creating confusion!

**Comment by prusnak** [comment]
> So agreed, this PR can be closed. Sorry for creating confusion!

Closing 👍

**Pull request closed without merging**
