### PR TITLE
doc: Add to Doxygen documentation guidelines

### PR DESCRIPTION
**Pull request by jonatack**
Completes the up-for-grabs PR #16948.

Changes can be tested here: [doc/developer-notes.md](https://github.com/jonatack/bitcoin/blob/doxygen-developer-notes-improvements/doc/developer-notes.md)

Co-authored-by: Jon Layton <me@jonl.io>

### CODE REVIEW

**Comment by jonatack** [comment]
Recommend reviewing the 2 commits together, as the second commit reverts the formatting changes in the first one.

**Comment by fanquake** [comment]
Why not just edit the original commit directly? There's not really any point having it (with all it's problems), only to revert a bunch of the changes in a follow up.

**Comment by jonatack** [comment]
Agreed; done.

**Comment by laanwj** [comment]
Changes look good to me. Thanks.
ACK c902c4c0c6a26de8cb69a469503bf4a0bd73903c

**Review by fanquake — APPROVED** [review]
ACK c902c4c0c6a26de8cb69a469503bf4a0bd73903c - quick read, checked the new links work.

**Pull request merged**
