### PR TITLE
guix: switch from `guix environment` to `guix shell`

### PR DESCRIPTION
**Pull request by fanquake**
See https://guix.gnu.org/manual/devel/en/html_node/Invoking-guix-environment.html.

> Deprecation warning: The guix environment command is deprecated
in favor of guix shell, which performs similar functions but is more convenient to use. See Invoking guix shell.

> Being deprecated, guix environment is slated for eventual removal,
but the Guix project is committed to keeping it until May 1st, 2023. Please get in touch with us at guix-devel@gnu.org if you would like to discuss it.

See also https://guix.gnu.org/blog/2021/from-guix-environment-to-guix-shell/ for a blog post and additional details.

Guix `shell` was added to Guix ~1 year ago, in this commit, https://git.savannah.gnu.org/cgit/guix.git/commit/?id=80edb7df6586464aa40e84e103f0045452de95db, which isn't part of the 1.3.0 release binaries out of the box, but invoking a `guix pull`, and updating will make it available. i.e:
```bash
bash-5.1# guix --version
guix (GNU Guix) 1.3.0
Copyright (C) 2021 the Guix authors
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

bash-5.1# guix shell
guix: shell: command not found
Try 'guix --help' for more information.

bash-5.1# guix pull
Updating channel 'guix' from Git repository at 'https://git.savannah.gnu.org/git/guix.git'...
Authenticating channel 'guix', commits 9edb3f6 to 7a980bb (6,278 new commits)...
Building from this channel:
  guix      https://git.savannah.gnu.org/git/guix.git	7a980bb
< snip >
building /gnu/store/2wwwsczxcw61m05p4mv0kf0advx4fqsb-inferior-script.scm.drv...
building package cache...
building profile with 1 package...
New in this revision:
  6,866 new packages: a2jmidid, abjad,

bash-5.1# guix help shell
Usage: guix shell [OPTION] PACKAGES... [-- COMMAND...]
Build an environment that includes PACKAGES and execute COMMAND or an
interactive shell in that environment.
```

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Seems a bit early to accommodate for a removed feature that was replaced by something that hasn't ever been released in a release. Do you expect everyone to run the development branch of guix? Everyone running the latest release of guix should be fine without the changes here.

**Comment by fanquake** [comment]
> Do you expect everyone to run the development branch of guix?

No. I don't see running `guix pull` [(`Download and deploy the latest version of Guix.`)](https://guix.gnu.org/manual/en/html_node/Invoking-guix-pull.html) as running a development branch. It's much more equivalent to running `apt/dnf/brew update`; giving you access to updated versions of packages to install, new features in Guix, bug fixes, support for new platforms/hardware etc. Fwiw I'd consider the [`core-updates`](https://git.savannah.gnu.org/cgit/guix.git/log/?h=core-updates) branch to be the "development branch" of Guix.

> Everyone running the latest release of guix should be fine without the changes here.

Sometime prior to May (assuming the command is removed as stated) our scripts will have to change, as we'll need to accomodate builders who keep their Guix updated. Once we make that change, anyone who's not run`guix pull` will no-longer be able to build (master at least), as `guix shell` wont exist in their Guix binary.

This will also effect any other branch still using `guix environment`, and then this change would need to be backported, so it can continue to be Guix built. 

I'm not trying to force anything on Guix builders early, but I also don't see the benefit in leaving this until later, or right up until the point that things might break; especially if currently the only trade-off is accomodating builders who don't want to update their package manager.

**Comment by MarcoFalke** [comment]
Ok, then maybe `guix pull` should be documented as required/expected before starting the build?

**Comment by fanquake** [comment]
>  replaced by something that hasn't ever been released in a release.

In regards to this point, it's not currently clear to me what the schedule is for the next Guix release. The most recent `Release v1.4?` discussions on the `guix-devel` list seem to have died out in June: https://lists.gnu.org/archive/html/guix-devel/2022-06/msg00364.html. 

A `1.4.0` branch does exist, https://git.savannah.gnu.org/cgit/guix.git/log/?h=version-1.4.0, but also hasn't been updated since January this year.

**Comment by jarolrod** [comment]
GUIX hashes

x86:
```

```

arm64:
```
$ find guix-build-$(git rev-parse --short=12 HEAD)/output/ -type f -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum

14af0889d50b276d2552e9e4a286751b29bb835cf2d6c568b0ab3e00d13a997a  guix-build-0bd5162f8e73/output/aarch64-linux-gnu/SHA256SUMS.part
e7971b5e89b4440c865acba54242bb3c21e0fb51597ab57df85d9eec49c41fdb  guix-build-0bd5162f8e73/output/aarch64-linux-gnu/bitcoin-0bd5162f8e73-aarch64-linux-gnu-debug.tar.gz
4c361dddf559ad52bce5b1f93cd612d9951ed41f7bcc2449705ad83c33f8b9b8  guix-build-0bd5162f8e73/output/aarch64-linux-gnu/bitcoin-0bd5162f8e73-aarch64-linux-gnu.tar.gz
08b384613febec9414bd2fef03f98fe2bd45c5d7656017b05a589a765bb8983f  guix-build-0bd5162f8e73/output/arm-linux-gnueabihf/SHA256SUMS.part
c1757a0789663da8e844ac376fb4c66728653076f499054112304efbe6227b62  guix-build-0bd5162f8e73/output/arm-linux-gnueabihf/bitcoin-0bd5162f8e73-arm-linux-gnueabihf-debug.tar.gz
f0c875d9a072ca7b97b10ed71b7f8edc01032cb48aa4db722fae8230f50718fa  guix-build-0bd5162f8e73/output/arm-linux-gnueabihf/bitcoin-0bd5162f8e73-arm-linux-gnueabihf.tar.gz
fa6b69d3cec6f0cf8b7371777cb40581008bdbd8ddb4e9edd7af05a44a9789b6  guix-build-0bd5162f8e73/output/arm64-apple-darwin/SHA256SUMS.part
23129cbaed8b4cd3c9ea6ecb414f0885dc0e244eabee25b4e5848f6f9c7232c9  guix-build-0bd5162f8e73/output/arm64-apple-darwin/bitcoin-0bd5162f8e73-arm64-apple-darwin-unsigned.dmg
6b87a6e98020884ac598e42b98df3c77723f8dd2a829d3261240642c844262f0  guix-build-0bd5162f8e73/output/arm64-apple-darwin/bitcoin-0bd5162f8e73-arm64-apple-darwin-unsigned.tar.gz
12f2e92cc609a45f18b7ddf64a38a66e372b103051651948c1d013f355603174  guix-build-0bd5162f8e73/output/arm64-apple-darwin/bitcoin-0bd5162f8e73-arm64-apple-darwin.tar.gz
1b79b5d406524acfe9d6353c4d4011ee212cbb211b2d11bc1596c575d43299ae  guix-build-0bd5162f8e73/output/dist-archive/bitcoin-0bd5162f8e73.tar.gz
b75eddcee748e1f8ead8b5e2f1b2a2956dcce33faae0292dc157c507e4d238bc  guix-build-0bd5162f8e73/output/powerpc64-linux-gnu/SHA256SUMS.part
f3bcb70031c8634689eff00dc16849aa9ba26171471121fc3cf304a45f5d3c5d  guix-build-0bd5162f8e73/output/powerpc64-linux-gnu/bitcoin-0bd5162f8e73-powerpc64-linux-gnu-debug.tar.gz
dac92ec1e2335cf17efc978b3c4426138ed0c8bf5e8bd8ed2a82525093719907  guix-build-0bd5162f8e73/output/powerpc64-linux-gnu/bitcoin-0bd5162f8e73-powerpc64-linux-gnu.tar.gz
852f951d203e0ea8d8eaf65432cc9301651d25143929a5c00d1a1f06b7b17d9a  guix-build-0bd5162f8e73/output/powerpc64le-linux-gnu/SHA256SUMS.part
d2e71465cbffac7f46a1f7169904d33d157a0aa1c0de632701307431f4f52cd8  guix-build-0bd5162f8e73/output/powerpc64le-linux-gnu/bitcoin-0bd5162f8e73-powerpc64le-linux-gnu-debug.tar.gz
1a048d680a10651a79ca5005fa238bbf669d8ad70313c498e0218d10bd5565fa  guix-build-0bd5162f8e73/output/powerpc64le-linux-gnu/bitcoin-0bd5162f8e73-powerpc64le-linux-gnu.tar.gz
08503a3513a8d56b91b5b2942eb2ab54de09346390e90ba8cd8cb0188fab5939  guix-build-0bd5162f8e73/output/riscv64-linux-gnu/SHA256SUMS.part
279ef5692047c2efacd21f5eca29ca377571ac0c1a23ecdbdcb345a55ec2b09c  guix-build-0bd5162f8e73/output/riscv64-linux-gnu/bitcoin-0bd5162f8e73-riscv64-linux-gnu-debug.tar.gz
d244f82d3de2c7ad85b26c5b6d5dd02b2f15c00632c47b59628d11705efe8c2a  guix-build-0bd5162f8e73/output/riscv64-linux-gnu/bitcoin-0bd5162f8e73-riscv64-linux-gnu.tar.gz
21ea0318d54940f3fed26ded1738b1e91ea8b703243baf7d02decf6cb7159859  guix-build-0bd5162f8e73/output/x86_64-apple-darwin/SHA256SUMS.part
2f621374d7351ecc63b97585a33111fcda1e80644e2dd15c3058e4433d2ab13c  guix-build-0bd5162f8e73/output/x86_64-apple-darwin/bitcoin-0bd5162f8e73-x86_64-apple-darwin-unsigned.dmg
244347af756e595380ed965fa7e63ffe670026600dad820d21436a46e9801129  guix-build-0bd5162f8e73/output/x86_64-apple-darwin/bitcoin-0bd5162f8e73-x86_64-apple-darwin-unsigned.tar.gz
8e26b527cee40a96b7a1bd85529114bedd0524a70f6f5c7c2e8cf56f44cf9d6f  guix-build-0bd5162f8e73/output/x86_64-apple-darwin/bitcoin-0bd5162f8e73-x86_64-apple-darwin.tar.gz
815f8468a6953c01daf7712bf7b8c70515de47a33ab3616945b2c4111e367954  guix-build-0bd5162f8e73/output/x86_64-linux-gnu/SHA256SUMS.part
14967568b389c2f2692ad31c0d1fe538a8cc56a2309073f369e4e5b915f6cd41  guix-build-0bd5162f8e73/output/x86_64-linux-gnu/bitcoin-0bd5162f8e73-x86_64-linux-gnu-debug.tar.gz
0d223150ccefcfed563ca900c01f9730dd5e2f446042518fb8144bb9ec2fa658  guix-build-0bd5162f8e73/output/x86_64-linux-gnu/bitcoin-0bd5162f8e73-x86_64-linux-gnu.tar.gz
b4818c32dd2bce3e525edf02a0396738fdd943490778ff657df90b6261681bd1  guix-build-0bd5162f8e73/output/x86_64-w64-mingw32/SHA256SUMS.part
0bee28242cb9e913ffe0490164dbb39190917885ca8be6595155106fe905cfa5  guix-build-0bd5162f8e73/output/x86_64-w64-mingw32/bitcoin-0bd5162f8e73-win64-debug.zip
33a77389546371adbf4bb73e8a1c2638dc59dccb9b7c1a92feb5839a8c273d5e  guix-build-0bd5162f8e73/output/x86_64-w64-mingw32/bitcoin-0bd5162f8e73-win64-setup-unsigned.exe
abbec5d12d7f8facfb7ca220c1b66d07ffdf8f3470a829c789f875582c029200  guix-build-0bd5162f8e73/output/x86_64-w64-mingw32/bitcoin-0bd5162f8e73-win64-unsigned.tar.gz
40af9455183d68aa83da30fe58e70de937a11127b8d77c4a227176b335887b49  guix-build-0bd5162f8e73/output/x86_64-w64-mingw32/bitcoin-0bd5162f8e73-win64.zip
```

**Comment by hebasto** [comment]
> Guix `shell` was added to Guix ~1 year ago, in this commit, https://git.savannah.gnu.org/cgit/guix.git/commit/?id=80edb7df6586464aa40e84e103f0045452de95db, which isn't part of the 1.3.0 release binaries out of the box, but invoking a `guix pull`

Just a reminder, that `guix pull` failed in certain conditions in the past (just search in https://issues.guix.gnu.org). I don't think we can rely on it.

**Comment by fanquake** [comment]
> Ok, then maybe guix pull should be documented as required/expected before starting the build?

I'll add some additional documentation.

> Just a reminder, that guix pull failed in certain conditions in the past (just search in https://issues.guix.gnu.org/). I don't think we can rely on it.

Can you point to some specific instances of bugs that would effect us, and are still relevant for a recent Guix release? What are the certain conditions?

**Comment by fanquake** [comment]
Looks like there is at least some movement on the Guix `1.4.0` release front. A [commit this morning](https://git.savannah.gnu.org/cgit/guix.git/commit/?id=839950c4a9925bf3d7108cb8533be37b185fb8bd) added: `* NEWS: Update entries for v1.4.0.`.

**Comment by hebasto** [comment]
> > Just a reminder, that guix pull failed in certain conditions in the past (just search in https://issues.guix.gnu.org/). I don't think we can rely on it.
> 
> Can you point to some specific instances of bugs that would effect us, and are still relevant for a recent Guix release? What are the certain conditions?

By "certain conditions" I mean a combination of a local repo head commit and a remote repo head commit. Nothing specific to us. If it happened before, I see no reasons why it can't happen again.

**Comment by MarcoFalke** [comment]
Once there is a 1.4 release, it seems more acceptable to say this is also the minimum required version

**Comment by fanquake** [comment]
> Once there is a 1.4 release, it seems more acceptable to say this is also the minimum required version

Possibly, although that will also depend on how fast distros are too adopt it.

The changes here will still be needed for all maintained branches (or will have to backport a change to say they can't be built with newer Guix), and the `guix pull` instructions will be required for users updating from their current binaries (unless the expectation is for everyone to download and overwrite their existing binaries).

**Comment by hebasto** [comment]
After an offline discussion with @fanquake I concept ACK.

https://github.com/bitcoin/bitcoin/pull/26077#issuecomment-1245595838:
> Ok, then maybe `guix pull` should be documented as required/expected before starting the build?

+1

**Comment by MarcoFalke** [comment]
I don't see why this needs to be rushed. It should be fine to do nothing for almost a year and then backport this to all branches on May 2nd, or when  1.4 has been released, whichever happens earlier

**Comment by fanquake** [comment]
> and then backport this to all branches on May 2nd,

This doesn't make tagged / released versions buildable. They will start failing to build for anyone using a Guix that no-longer has `environment`. I'm not advocating rushing, but I also don't see the point of leaving this until much later / the last minute, and then having things broken that otherwise wouldn't have needed to be. In any case, we don't have to do this last-minute for 24.0.

> or when 1.4 has been released

When released, this binary will, as far as I can tell, still have both commands, so it's release date (if it's much earlier than May) won't really factor into when we change things here.

**Comment by luke-jr** [comment]
Looking at this PR, it seems like it should be trivial to accommodate both commands? Try `guix shell` first, and if that fails, try `guix environment`...

**Comment by TheCharlatan** [comment]
Concept ACK

Guix 1.4.0 was released in December, they still paint May 2023 has a potential deprecation target for `guix environment` in their release blog post: https://guix.gnu.org/en/blog/2022/gnu-guix-1.4.0-released/ .

Guix hashes (built with a 1.4.0 release):

```
14af0889d50b276d2552e9e4a286751b29bb835cf2d6c568b0ab3e00d13a997a  guix-build-0bd5162f8e73/output/aarch64-linux-gnu/SHA256SUMS.part
e7971b5e89b4440c865acba54242bb3c21e0fb51597ab57df85d9eec49c41fdb  guix-build-0bd5162f8e73/output/aarch64-linux-gnu/bitcoin-0bd5162f8e73-aarch64-linux-gnu-debug.tar.gz
4c361dddf559ad52bce5b1f93cd612d9951ed41f7bcc2449705ad83c33f8b9b8  guix-build-0bd5162f8e73/output/aarch64-linux-gnu/bitcoin-0bd5162f8e73-aarch64-linux-gnu.tar.gz
08b384613febec9414bd2fef03f98fe2bd45c5d7656017b05a589a765bb8983f  guix-build-0bd5162f8e73/output/arm-linux-gnueabihf/SHA256SUMS.part
c1757a0789663da8e844ac376fb4c66728653076f499054112304efbe6227b62  guix-build-0bd5162f8e73/output/arm-linux-gnueabihf/bitcoin-0bd5162f8e73-arm-linux-gnueabihf-debug.tar.gz
f0c875d9a072ca7b97b10ed71b7f8edc01032cb48aa4db722fae8230f50718fa  guix-build-0bd5162f8e73/output/arm-linux-gnueabihf/bitcoin-0bd5162f8e73-arm-linux-gnueabihf.tar.gz
fa6b69d3cec6f0cf8b7371777cb40581008bdbd8ddb4e9edd7af05a44a9789b6  guix-build-0bd5162f8e73/output/arm64-apple-darwin/SHA256SUMS.part
23129cbaed8b4cd3c9ea6ecb414f0885dc0e244eabee25b4e5848f6f9c7232c9  guix-build-0bd5162f8e73/output/arm64-apple-darwin/bitcoin-0bd5162f8e73-arm64-apple-darwin-unsigned.dmg
6b87a6e98020884ac598e42b98df3c77723f8dd2a829d3261240642c844262f0  guix-build-0bd5162f8e73/output/arm64-apple-darwin/bitcoin-0bd5162f8e73-arm64-apple-darwin-unsigned.tar.gz
12f2e92cc609a45f18b7ddf64a38a66e372b103051651948c1d013f355603174  guix-build-0bd5162f8e73/output/arm64-apple-darwin/bitcoin-0bd5162f8e73-arm64-apple-darwin.tar.gz
1b79b5d406524acfe9d6353c4d4011ee212cbb211b2d11bc1596c575d43299ae  guix-build-0bd5162f8e73/output/dist-archive/bitcoin-0bd5162f8e73.tar.gz
b75eddcee748e1f8ead8b5e2f1b2a2956dcce33faae0292dc157c507e4d238bc  guix-build-0bd5162f8e73/output/powerpc64-linux-gnu/SHA256SUMS.part
f3bcb70031c8634689eff00dc16849aa9ba26171471121fc3cf304a45f5d3c5d  guix-build-0bd5162f8e73/output/powerpc64-linux-gnu/bitcoin-0bd5162f8e73-powerpc64-linux-gnu-debug.tar.gz
dac92ec1e2335cf17efc978b3c4426138ed0c8bf5e8bd8ed2a82525093719907  guix-build-0bd5162f8e73/output/powerpc64-linux-gnu/bitcoin-0bd5162f8e73-powerpc64-linux-gnu.tar.gz
852f951d203e0ea8d8eaf65432cc9301651d25143929a5c00d1a1f06b7b17d9a  guix-build-0bd5162f8e73/output/powerpc64le-linux-gnu/SHA256SUMS.part
d2e71465cbffac7f46a1f7169904d33d157a0aa1c0de632701307431f4f52cd8  guix-build-0bd5162f8e73/output/powerpc64le-linux-gnu/bitcoin-0bd5162f8e73-powerpc64le-linux-gnu-debug.tar.gz
1a048d680a10651a79ca5005fa238bbf669d8ad70313c498e0218d10bd5565fa  guix-build-0bd5162f8e73/output/powerpc64le-linux-gnu/bitcoin-0bd5162f8e73-powerpc64le-linux-gnu.tar.gz
08503a3513a8d56b91b5b2942eb2ab54de09346390e90ba8cd8cb0188fab5939  guix-build-0bd5162f8e73/output/riscv64-linux-gnu/SHA256SUMS.part
279ef5692047c2efacd21f5eca29ca377571ac0c1a23ecdbdcb345a55ec2b09c  guix-build-0bd5162f8e73/output/riscv64-linux-gnu/bitcoin-0bd5162f8e73-riscv64-linux-gnu-debug.tar.gz
d244f82d3de2c7ad85b26c5b6d5dd02b2f15c00632c47b59628d11705efe8c2a  guix-build-0bd5162f8e73/output/riscv64-linux-gnu/bitcoin-0bd5162f8e73-riscv64-linux-gnu.tar.gz
21ea0318d54940f3fed26ded1738b1e91ea8b703243baf7d02decf6cb7159859  guix-build-0bd5162f8e73/output/x86_64-apple-darwin/SHA256SUMS.part
2f621374d7351ecc63b97585a33111fcda1e80644e2dd15c3058e4433d2ab13c  guix-build-0bd5162f8e73/output/x86_64-apple-darwin/bitcoin-0bd5162f8e73-x86_64-apple-darwin-unsigned.dmg
244347af756e595380ed965fa7e63ffe670026600dad820d21436a46e9801129  guix-build-0bd5162f8e73/output/x86_64-apple-darwin/bitcoin-0bd5162f8e73-x86_64-apple-darwin-unsigned.tar.gz
8e26b527cee40a96b7a1bd85529114bedd0524a70f6f5c7c2e8cf56f44cf9d6f  guix-build-0bd5162f8e73/output/x86_64-apple-darwin/bitcoin-0bd5162f8e73-x86_64-apple-darwin.tar.gz
815f8468a6953c01daf7712bf7b8c70515de47a33ab3616945b2c4111e367954  guix-build-0bd5162f8e73/output/x86_64-linux-gnu/SHA256SUMS.part
14967568b389c2f2692ad31c0d1fe538a8cc56a2309073f369e4e5b915f6cd41  guix-build-0bd5162f8e73/output/x86_64-linux-gnu/bitcoin-0bd5162f8e73-x86_64-linux-gnu-debug.tar.gz
0d223150ccefcfed563ca900c01f9730dd5e2f446042518fb8144bb9ec2fa658  guix-build-0bd5162f8e73/output/x86_64-linux-gnu/bitcoin-0bd5162f8e73-x86_64-linux-gnu.tar.gz
b4818c32dd2bce3e525edf02a0396738fdd943490778ff657df90b6261681bd1  guix-build-0bd5162f8e73/output/x86_64-w64-mingw32/SHA256SUMS.part
0bee28242cb9e913ffe0490164dbb39190917885ca8be6595155106fe905cfa5  guix-build-0bd5162f8e73/output/x86_64-w64-mingw32/bitcoin-0bd5162f8e73-win64-debug.zip
33a77389546371adbf4bb73e8a1c2638dc59dccb9b7c1a92feb5839a8c273d5e  guix-build-0bd5162f8e73/output/x86_64-w64-mingw32/bitcoin-0bd5162f8e73-win64-setup-unsigned.exe
abbec5d12d7f8facfb7ca220c1b66d07ffdf8f3470a829c789f875582c029200  guix-build-0bd5162f8e73/output/x86_64-w64-mingw32/bitcoin-0bd5162f8e73-win64-unsigned.tar.gz
40af9455183d68aa83da30fe58e70de937a11127b8d77c4a227176b335887b49  guix-build-0bd5162f8e73/output/x86_64-w64-mingw32/bitcoin-0bd5162f8e73-win64.zip
```

**Comment by fanquake** [comment]
> lgtm, but you'll have to document the minimum guix version to be 1.4, no?

Yea we'll have to update docs in some capacity. Going to draft for now, until we've bumped the time-machine (27897), and then come back to this.

**Comment by fanquake** [comment]
>  I just tested this locally with guix v1.3 and it works:

I tried the same with 1.2.0:
```bash
fa242307e656:/bitcoin# guix --version
/gnu/store/7sfbiqh21h90bc6zi8br1xh60m6qgdd5-bash-minimal-5.0.16/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
guix (GNU Guix) 1.2.0
Copyright (C) 2020 the Guix authors
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
fa242307e656:/bitcoin# guix time-machine --commit=77386bdbfe6b0c649c05ab37f08051d1ab3e5074 -- shell
/gnu/store/7sfbiqh21h90bc6zi8br1xh60m6qgdd5-bash-minimal-5.0.16/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Updating channel 'guix' from Git repository at 'https://git.savannah.gnu.org/git/guix.git'...
guix shell: warning: no packages specified; creating an empty environment
hint: Consider passing the '--check' option once to make sure your shell does not clobber environment variables.

guix shell: warning: no packages specified; creating an empty environment
substitute: /gnu/store/7sfbiqh21h90bc6zi8br1xh60m6qgdd5-bash-minimal-5.0.16/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
substitute: updating substitutes from 'https://ci.guix.gnu.org'... 100.0%
The following derivations will be built:
  /gnu/store/wkvzmn03nc2p0ym7vpp0hri0fvd6c8vf-profile.drv
  /gnu/store/f0cq09h6rn52zcmvn4khrl8wcan63v2j-module-import-compiled.drv

applying 7 grafts for guile-3.0.9 ...
building /gnu/store/f0cq09h6rn52zcmvn4khrl8wcan63v2j-module-import-compiled.drv...
building profile with 0 packages...
```

**Review by sedited — APPROVED** [review]
ACK 66c4b58e518aff08030b3c879c44af7716110619

Guix builds (x86):
```
b4a8c955fb5df71df94a0c754aec564ebe43e38055c6b41a271466b4573fe53f  guix-build-66c4b58e518a/output/aarch64-linux-gnu/SHA256SUMS.part
0d0a7612863ddd41d26b1d43fff827a2b8d118106a037e82c4111ce37fa7e857  guix-build-66c4b58e518a/output/aarch64-linux-gnu/bitcoin-66c4b58e518a-aarch64-linux-gnu-debug.tar.gz
b251292b681ec36bdb3c331c76afa7389671f9942cd6afadb4e303a803711415  guix-build-66c4b58e518a/output/aarch64-linux-gnu/bitcoin-66c4b58e518a-aarch64-linux-gnu.tar.gz
74b41731eddcb68b157d9a526c94c8e19e58ee676104b44f92bf8ef99e14b258  guix-build-66c4b58e518a/output/arm-linux-gnueabihf/SHA256SUMS.part
4b515a6ff49606cdb1451510699fcff87394ed5c650e9d7db22c783c666010d1  guix-build-66c4b58e518a/output/arm-linux-gnueabihf/bitcoin-66c4b58e518a-arm-linux-gnueabihf-debug.tar.gz
55db0db7df0a9f13c79eaf309c61f44c73fb37d26e4a1cf265eef7881321fec1  guix-build-66c4b58e518a/output/arm-linux-gnueabihf/bitcoin-66c4b58e518a-arm-linux-gnueabihf.tar.gz
eb62791c4acb8a46c3631fa90f346be72f38c1c3ee38346a7a92883aecd8e170  guix-build-66c4b58e518a/output/arm64-apple-darwin/SHA256SUMS.part
b2a89ac099f39155a58ef566cb111b2c38bcbbd9d0d0df226c9661b9fac4fd1f  guix-build-66c4b58e518a/output/arm64-apple-darwin/bitcoin-66c4b58e518a-arm64-apple-darwin-unsigned.tar.gz
642578b1750ba067b93d7ad716d3e5cecdb3be0071cd88984eb68af670247070  guix-build-66c4b58e518a/output/arm64-apple-darwin/bitcoin-66c4b58e518a-arm64-apple-darwin-unsigned.zip
23cedc5f89d7a3514aa1718d74851fa53f21acd89e4c4994b4e4864f92e41366  guix-build-66c4b58e518a/output/arm64-apple-darwin/bitcoin-66c4b58e518a-arm64-apple-darwin.tar.gz
58ccdddb213b92ee2b18fba9960298cfa45c5fb23972eb2f73c4652f89a026ba  guix-build-66c4b58e518a/output/dist-archive/bitcoin-66c4b58e518a.tar.gz
fd31e0439b48bcc896deb1ecf5fabbaede91f47f065da6df360e1eca222323bd  guix-build-66c4b58e518a/output/powerpc64-linux-gnu/SHA256SUMS.part
558ea3ad15d08c4e57af66cdccd6ae5fd02be8878880bb898870d3b13443acdb  guix-build-66c4b58e518a/output/powerpc64-linux-gnu/bitcoin-66c4b58e518a-powerpc64-linux-gnu-debug.tar.gz
112936fb96bf22097a046ef1a2b1ea23e91d2bba9e3b54a819a4a33811efab07  guix-build-66c4b58e518a/output/powerpc64-linux-gnu/bitcoin-66c4b58e518a-powerpc64-linux-gnu.tar.gz
a408de2a12852cfae0b6dd19ee6bbcdeabcc0223ce3554727ce0e0f440d8f2f9  guix-build-66c4b58e518a/output/powerpc64le-linux-gnu/SHA256SUMS.part
389d9654743cd307a875e753dafc3a40aa5d7c94eca1efba33e4d18bf6c66748  guix-build-66c4b58e518a/output/powerpc64le-linux-gnu/bitcoin-66c4b58e518a-powerpc64le-linux-gnu-debug.tar.gz
5fe15013c4e60f6fa4b9679664a8c3296ade2461e5b999ca3f748d25199ce454  guix-build-66c4b58e518a/output/powerpc64le-linux-gnu/bitcoin-66c4b58e518a-powerpc64le-linux-gnu.tar.gz
61b579e1e8174ae85c2b6e1372d4a0f7d728731032795ba50ff8b5fafef0e48b  guix-build-66c4b58e518a/output/riscv64-linux-gnu/SHA256SUMS.part
309378ea24e1c4029608263fb9a6310b8457047083c86d209cb2b39fbceb7cc5  guix-build-66c4b58e518a/output/riscv64-linux-gnu/bitcoin-66c4b58e518a-riscv64-linux-gnu-debug.tar.gz
b8c15e6f32097abc00a26a13af64213de98ffe7cde081f247e0ce2f91b5864bb  guix-build-66c4b58e518a/output/riscv64-linux-gnu/bitcoin-66c4b58e518a-riscv64-linux-gnu.tar.gz
baab1c7ae5a75add97602f77136a9d5a6df4c4e76528561de8fa26f5a284413b  guix-build-66c4b58e518a/output/x86_64-apple-darwin/SHA256SUMS.part
0bcb35054d1b3e40d33a270f86905157ac7507fc15fdfc2d006825791040099d  guix-build-66c4b58e518a/output/x86_64-apple-darwin/bitcoin-66c4b58e518a-x86_64-apple-darwin-unsigned.tar.gz
b308c7715814ee546f2f3b66f42fced1cde38e29979a6551e1be615d3cc42f84  guix-build-66c4b58e518a/output/x86_64-apple-darwin/bitcoin-66c4b58e518a-x86_64-apple-darwin-unsigned.zip
444ac5eeb627391e09dc7ef07b53b359f0a20c795e6bc9af2dae6142da36ed09  guix-build-66c4b58e518a/output/x86_64-apple-darwin/bitcoin-66c4b58e518a-x86_64-apple-darwin.tar.gz
e0604482cad9d85f22ee388e371219643fd862b5a3498575c833adb205c59d52  guix-build-66c4b58e518a/output/x86_64-linux-gnu/SHA256SUMS.part
c6011195f0e2ae34c2f8433145c1595b89a2ad4cecd479472d6776d567607a1a  guix-build-66c4b58e518a/output/x86_64-linux-gnu/bitcoin-66c4b58e518a-x86_64-linux-gnu-debug.tar.gz
4b1a86f447217b5dec9ce957049dbcd96bd5b8470f31d972d1fd483a58f18d32  guix-build-66c4b58e518a/output/x86_64-linux-gnu/bitcoin-66c4b58e518a-x86_64-linux-gnu.tar.gz
96ed252f85c9d7cb98b3020dcab184b8dcac11746dfc11b96101daeabb1f9530  guix-build-66c4b58e518a/output/x86_64-w64-mingw32/SHA256SUMS.part
c57be6253f755ea4d3b08f0348c3d6210dbf3884a52835ed06d0aebea3edee59  guix-build-66c4b58e518a/output/x86_64-w64-mingw32/bitcoin-66c4b58e518a-win64-debug.zip
58173b97084ae070576d447c5ee4673457e197da352a84684b1fbc9fb977349f  guix-build-66c4b58e518a/output/x86_64-w64-mingw32/bitcoin-66c4b58e518a-win64-setup-unsigned.exe
40463c75f29bec4de2e29c0d1ed1b2c8ee1a49111ebfc411799455e44b9d773a  guix-build-66c4b58e518a/output/x86_64-w64-mingw32/bitcoin-66c4b58e518a-win64-unsigned.tar.gz
022ef6e06743afe0c976150e6179ca75104dee1762591cd494b366d66cecca50  guix-build-66c4b58e518a/output/x86_64-w64-mingw32/bitcoin-66c4b58e518a-win64.zip
```

**Pull request merged**
