### PR TITLE
Fix #24049: signed integer overflow in `SeenLocal`

### LINKED ISSUE #24049: net: signed-integer-overflow in LocalServiceInfo
`LocalServiceInfo` is defined as:
https://github.com/bitcoin/bitcoin/blob/16781e1bc9f8ffc721ebea73434e0066957bc959/src/net.h#L228-L231
`nScore` is of type int which is signed and is 4 bytes wide on my machine (clang-12). `nScore` is incremented by `SeenLocal` during the version handshake here:
https://github.com/bitcoin/bitcoin/blob/16781e1bc9f8ffc721ebea73434e0066957bc959/src/net_processing.cpp#L2603-L2606
So I believe this UB is peer-triggerable (I don't think the compiler can detect this), but I don't think it's a big deal unless there's a node out there compiled with UBSAN or ftrapv. It seems like `nScore` can just be changed to int64_t.

### PR DESCRIPTION
**Pull request by ViralTaco**
This commit makes the behavior defined (unsigned integer overflow as if: 
`it->second.nscore = static_cast<int>(static_cast<unsigned> (it->second.nscore) + 1U);`)
See: Issue #24049; Discussion on [stackoverflow](https://stackoverflow.com/q/74102221/9282847).

### CODE REVIEW

**Comment by hebasto** [comment]
@ViralTaco 

Did you see a discussion in #24090? Especially, https://github.com/bitcoin/bitcoin/pull/24090#issuecomment-1046959948 and https://github.com/bitcoin/bitcoin/pull/24090#issuecomment-1064206706?

**Comment by luke-jr** [comment]
Doesn't appear to actually fix the issue though?

**Comment by ViralTaco** [comment]
> Looking at the previous comments, this doesn't seem to be a fix. Let's continue discussion in the issue for now.

It doesn't "seem[sic]" to fix the issue?  
What issue? The code before this patch has undefined behavior.
It can do anything, but it doesn't have to. It could do nothing.

The first sentence in your comment only makes sense in a vacuum. The standard is a thing. I agree with the second part. Let's.

**Comment by MarcoFalke** [comment]
The burden to prepare, explain and motivate a change for reviewers is on the author. You created a one-line patch in 4 commits, ignored previous discussions, ignored two review comments, with no apparent progress in about a month. I closed this for now, because it can't be merged according to the guidelines. At a minimum for this simple one line change, you'll have to create at most one commit, with an explanation, and you'll have to reply to review comments. All of this is explained in https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md

**Pull request closed without merging**
