### PR TITLE
doc: Add tracing.md, documenting eBPF tracing

### PR DESCRIPTION
**Pull request by laanwj**
Add documentation for #19866.

### CODE REVIEW

**Comment by jonatack** [comment]
Wow! Concept ACK.

**Comment by practicalswift** [comment]
Concept ACK

**Review by RiccardoMasutti — APPROVED** [review]
ACK

**Review by 0xB10C — CHANGES_REQUESTED** [review]
Concept ACK for tracing documentation and USDTs in general.

However, NACK on this PR in it's current form. This adds documentation for USDT tracepoints that aren't merged in master. #19866 did only add [build system detection of sys/sdt.h](https://github.com/bitcoin/bitcoin/pull/19866/commits/933ab8a720cb9b3341adec4109cffb6dc5b322a5) and the [tracing framework](https://github.com/bitcoin/bitcoin/pull/19866/commits/22eb7930a6ae021438aa0b8e750170534944f296), but not the mentioned tracepoints. 

The two needed commits adding the documented tracepoints would be 16ed9bc2488a96d895a6e277f284f24f4b9ba8ec and ea608d9adc7f41f929b8f6726774f9f09e26099c from this branch [laanwj:usdt-probes](https://github.com/laanwj/bitcoin/tree/usdt-probes). Did you mean to merge them first?

**Comment by laanwj** [comment]
> The two needed commits adding the documented tracepoints would be 16ed9bc and ea608d9 from this branch laanwj:usdt-probes. Did you mean to merge them first?

No, that's not my work, it's @jb55's. I'm really confused here.

**Comment by jb55** [comment]
"Wladimir J. van der Laan" <notifications@github.com> writes:

>> The two needed commits adding the documented tracepoints would be
>> 16ed9bc and ea608d9 from this branch laanwj:usdt-probes. Did you mean
>> to merge them first?
>
> No, that's not my work, it's @jb55's. I'm really confused here.

We only merged the build support for static traces. You mentioned that
we should get that in first.

I don't think we decided what arguments the static traces should have
yet. In my connect_block example I was only passing the height, but we
probably want to pass a few more things.

Some goals for static traces should be:

  - Somewhat stable API (order of arguments don't change) so people can
    rely on these for scripting

  - Some motivational use case

@0xB10C's connected_block trace looks useful as well.

Cheers,
Will

**Comment by jnewbery** [comment]
I think we should probably get a concept ACK from other contributors on whether we should start adding tracepoints all over the code. I can see the benefit that they're very powerful and add almost no overhead when not used. On the other hand, there's almost an unlimited number of things that could be traced, adding `TRACE()` macros in lots of places could potentially make the source less readable, and it's possible to do a lot of useful tracing with uprobes that don't require any changes to the source.

Do we know what other projects are doing? Is it common to put lots of USDTs into the master branch? Perhaps we should discuss what our approach should be in a core dev meeting.

**Comment by jb55** [comment]
John Newbery <notifications@github.com> writes:
> adding `TRACE()` macros in lots of places could potentially make the
> source less readable, and it's possible to do a lot of useful tracing
> with uprobes that don't require any changes to the source.

agreed, USDTs should accompanied by motivating examples and scripts. No
point adding USDTs that noone uses.

**Comment by 0xB10C** [comment]
picked this up in https://github.com/bitcoin/bitcoin/pull/22006

**Pull request closed without merging**
