### PR TITLE
Globals: Don't call Params() from miner.cpp

### PR DESCRIPTION
**Pull request by jtimon**
After this, miner.o doesn't need to ever call Params() anymore.
This is part of #5970.

If #6907 gets merged as well, we can separate Params() [its two versions] and SelectParams() away from chainparams.o (like @theuni wanted to do), maybe to globals/server.o. Then miner needs to include chainparams.h but not globals/server.h (at least while only Params(), Params(std::string) and SelectParams() are exposed there).

### CODE REVIEW

**Comment by petertodd** [comment]
utACK

**Comment by dcousens** [comment]
utACK

**Comment by sipa** [comment]
utACK

**Comment by gmaxwell** [comment]
ACK.

**Pull request merged**
