### PR TITLE
doc: Assert that assumed-valid blocks are not fully valid in CheckBlockIndex()

### PR DESCRIPTION
**Pull request by maflcko**
It does not make sense for a block to be fully-valid and assumed-valid at the same time.

Check it in `CheckBlockIndex()` and fix the tests that violate this assumption.

### CODE REVIEW

**Comment by delta1** [comment]
concept ACK fa027e08f7be63c201f42d0e06160d2273b4a6dd

**Comment by epiccurious** [comment]
Concept ACK fa027e08f7be63c201f42d0e06160d2273b4a6dd.

**Comment by fjahr** [comment]
Seems reasonable, code review ACK fa027e08f7be63c201f42d0e06160d2273b4a6dd

Not sure why this is marked as a "doc" change though.

**Comment by delta1** [comment]
@fjahr i think drahtbot added that label because the commit starts with “doc:”

**Comment by fjahr** [comment]
> @fjahr i think drahtbot added that label because the commit starts with “doc:”

Yes, my question is why the "doc" is there in the name

**Review by ryanofsky — APPROVED** [review]
Code review ACK fa027e08f7be63c201f42d0e06160d2273b4a6dd. This change makes sense and is an improvement over the status quo. I think it could be considered it a "doc" change since it is just adding an assert, which is a form of documentation, and not changing actual code. Not sure if that is how "doc" has been used other places, though.

This PR is a little redundant with #29370, which drops the BLOCK_ASSUMED_VALID flag entirely, so there is no way it could conflict with BLOCK_VALID_SCRIPTS. But it makes sense to check for conflicting flags as long as both flags exist.

**Pull request closed without merging**
