### PR TITLE
Improve section title in release-notes.md

### PR DESCRIPTION
**Pull request by btcdrak**

### CODE REVIEW

**Comment by jonasschnelli** [comment]
ACK

**Comment by achow101** [comment]
ACK

**Comment by petertodd** [comment]
utACK https://github.com/btcdrak/bitcoin/commit/42b521d8a000087e12e6d5e829ea713ec6c3d8e4

**Comment by fanquake** [comment]
ACK btcdrak@42b521d

**Comment by laanwj** [comment]
(re: strange title change, never mind me, I'm testing unicode support in github-merge.py)

**Pull request merged**
