### PR TITLE
Sanity-check script sizes in bitcoin-tx

### PR DESCRIPTION
**Pull request by TheBlueMatt**

### CODE REVIEW

**Comment by promag** [comment]
utACK a6f33ea.

Should add some test case to `test/util/data/bitcoin-util-test.json`?

**Comment by laanwj** [comment]
concept and utACK a6f33ea77d3a48f06b5c7cfcc20553c9a88d429a, better error clarity is good

**Comment by MarcoFalke** [comment]
utACK a6f33ea

**Comment by luke-jr** [comment]
This should probably be backported...

**Pull request merged**
