### PR TITLE
[Doc] Removing references to Windows 32 bit from README

### PR DESCRIPTION
**Pull request by NicolasDorier**

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Please include a short rationale in the pull description.

**Comment by laanwj** [comment]
Windows 32 bit, for better or worse, is still supported at this time.

**Comment by NicolasDorier** [comment]
oups, I thought that 0.14 dropped windows 32 bit, but it is only XP... sorry closing.

**Comment by laanwj** [comment]
Yes no worries it's common confusion, unfortunately, Windows 10 32-bit is a thing.

**Pull request closed without merging**
