### PR TITLE
[Qt, Trivial] misc small trivial pull-requests

### PR DESCRIPTION
**Pull request by Diapolo**
See individual commit messages for descriptions.
Likely this is for @theuni :).

### CODE REVIEW

**Comment by laanwj** [comment]
It's more efficient if you file these with @theuni's repository on the trivial-next branch directly: https://github.com/theuni/bitcoin

**Comment by theuni** [comment]
Yes, please do that.

I'll go ahead and review/pull these (along with some others that are waiting) tomorrow, but submitting them directly to the trivial tree would be much better.

**Comment by theuni** [comment]
I'm not comfortable pulling these into trivial.

1. The authenticated/secure debate has been hashed out here before and I'm not sure how it ended up.
2. The defaultConfirmTarget mixes a small functional change with a cosmetic one.

**Comment by Diapolo** [comment]
Feel free to just take the one commit that matches your Trivial specs :). I didn't want to start a new debate, but recently I've been using the authenticated term when dealing with payment requests and also took that from pull-request discussions, when discussing with others.

**Comment by laanwj** [comment]
> The authenticated/secure debate has been hashed out here before and I'm not sure how it ended up.

"Authenticated" is more apt. "Insecure" is ambiguous.

**Comment by laanwj** [comment]
Agree @cfields that functional changes, even minor ones, should not end up in the trivial branch. That could be very dangerous, even a small change can result in big bugs.

**Comment by sandakersmann** [comment]
I thought there was consensus for writing bitcoin with a lower case b when we are talking about the currency.

**Comment by Diapolo** [comment]
@sandakersmann You're right and I removed that, my fault, sorry!
@laanwj I removed the code change from that pull, you're right it doesn't belong here.
@theuni Seems the Authenticated/Insecure change is consensus then, right :)?

**Comment by Diapolo** [comment]
Moved to: https://github.com/theuni/bitcoin/pull/7

**Pull request closed without merging**
