### PR TITLE
wallet: Remove redundant wpkh script import

### LINKED ISSUE #16711: `importprivkey` always gives warning about already having script
Using the RPC command `importprivkey` always gives a warning message in the log about already having the script, even if the key is not yet known. Repro when the key is not known yet:
```bash
$ src/bitcoind -regtest -daemon
$ src/bitcoin-cli -regtest importprivkey cPRXsaa4WtDYmyvhT7KjT5hEJvNWndyXphTmHn2J6BYhxLt8cREn
$ tail $HOME/.bitcoin/regtest/debug.log
…
2019-08-24T14:33:58Z [default wallet] Already have script 0014d75ad18779e20b8c6e0d6b28dee92ef4069dd2cb, skipping
```

When the key is already known:
```
2019-08-24T14:41:33Z [default wallet] Already have key with pubkey 0327d77baf35f9aadb9fa84ebb87d2b5a56386164a4a86119e919bd65aec52a150, skipping
2019-08-24T14:41:33Z [default wallet] Already have script 0014d75ad18779e20b8c6e0d6b28dee92ef4069dd2cb, skipping
```

### PR DESCRIPTION
**Pull request by hinesley**
- CWallet::ImportPrivKeys() in previous code block already imports the
wpkh script. The block being removed effectively just printed a false
positive warning. Fixes #16711

### CODE REVIEW

**Comment by bhinesley** [comment]
`feature_fee_estimation.py` passes locally, and doesn't seem related.

**Comment by laanwj** [comment]
Concept ACK

> CWallet::ImportPrivKeys() in previous code block already imports the
wpkh script

Do you know where this happens? That function doesn't seem to do it directly, at least.

**Comment by laanwj** [comment]
Thanks! That's pretty sneaky, I was indeed searching for `AddCScript` or something similar, not something that bypasses everything and adds directly to the map.

Looks good to me then. Code review ACK b6e7aa8c4c0162a3515a4efa93c2898a2c4d24b4

**Comment by bhinesley** [comment]
It _is_ sneaky. The author of these lines obviously didn't see it either. Thanks for the review!

**Comment by meshcollider** [comment]
Concept ACK, the fix makes sense, haven't checked that the behaviour of ImplicitlyLearnRelatedKeyScripts behaves in the same way as ImportScripts though (with respect to writing to the wallet).

I think this is fine. Light utACK b6e7aa8c4c0162a3515a4efa93c2898a2c4d24b4

**Comment by achow101** [comment]
This will prevent the segwit output script from being written to the wallet file. While `ImplicitlyLoadRelatedScripts` allowed for those same scripts to be loaded, if the wallet were to be loaded into an older version of Bitcoin Core (without segwit I think, don't remember when this was added, but probably with segwit), outputs involving such scripts will not be recognized as they won't be loaded into the wallet in any way.

**Comment by bhinesley** [comment]
@achow101 That's a good point, I think you're right.

Here's another idea. The original code, for reference:
https://github.com/bitcoin/bitcoin/blob/f5db3f2128f0b293432a5a36cb0314b501019a06/src/wallet/rpcdump.cpp#L188-L196

If we switch the order of these two blocks, like so:
```
 // Add the wpkh script for this key if possible 
 if (pubkey.IsCompressed()) { 
     pwallet->ImportScripts({GetScriptForDestination(WitnessV0KeyHash(vchAddress))}, 0 /* timestamp */); 
 } 

// Use timestamp of 1 to scan the whole chain 
 if (!pwallet->ImportPrivKeys({{vchAddress, key}}, 1)) { 
     throw JSONRPCError(RPC_WALLET_ERROR, "Error adding key to wallet"); 
 } 
```
the warning referenced in #16711 goes away, because `ImplicitlyLoadRelatedScripts` doesn't show a warning when the key already exists. Yes it's being written to the map twice in quick succession, but that shouldn't be an issue.

**Comment by bhinesley** [comment]
Actually, the above would work, but this highlights a bigger problem. `ImportScripts()` relies on `FillableSigningProvider::HaveKey()` to determine whether to write the script to the wallet or not. However, as @achow101 just noted, a script appearing in the map doesn't mean it's written to the wallet. Thus, `ImplicitlyLoadRelatedScripts` can prevent scripts from being written.

https://github.com/bitcoin/bitcoin/blob/e9ef1b2c2ec229be1974c0c2413af53cc804542e/src/wallet/wallet.cpp#L1778-L1781

So perhaps instead, the conditional statement above could be changed to read from the actual wallet to determine if a key exists.

**Comment by fanquake** [comment]
@achow101 @meshcollider did you want to follow up with approach thoughts here?

**Comment by meshcollider** [comment]
IMO places where the map is edited directly without writing (other than the initial read of the wallet) are going to be dangerous, that behavior should be changed instead of adding more checks that the script is in the wallet. I think we should make it not possible to add to the map without adding to the wallet file.

**Comment by instagibbs** [comment]
Are there any legit reasons to not even try to write to DB?

**Pull request closed without merging**
