### PR TITLE
refactor: Add and use HaveTxsDownloaded() where appropriate

### PR DESCRIPTION
**Pull request by maflcko**
`nChainTx` is an implementation detail that shouldn't be exposed without a wrapper that comes with appropriate documentation.

### CODE REVIEW

**Review by promag — COMMENTED** [review]
Concept ACK

Could also update these?:
https://github.com/bitcoin/bitcoin/blob/c62b15118997030b007f04618cbca02d7abb1332/src/net_processing.cpp#L569
https://github.com/bitcoin/bitcoin/blob/c62b15118997030b007f04618cbca02d7abb1332/src/net_processing.cpp#L1127
https://github.com/bitcoin/bitcoin/blob/c62b15118997030b007f04618cbca02d7abb1332/src/rpc/blockchain.cpp#L1461

**Comment by promag** [comment]
utACK fa4fc88.

**Comment by Empact** [comment]
utACK https://github.com/bitcoin/bitcoin/commit/fa4fc8856b239059421a8e507b3e3e7f4b379a72

**Comment by laanwj** [comment]
utACK fa4fc8856b239059421a8e507b3e3e7f4b379a72

**Pull request merged**
