### PR TITLE
build:  Trim `{native_}libmultiprocess` packages in depends 

### PR DESCRIPTION
**Pull request by hebasto**
We are interested only in:
- a `mpgen` tool from the `native_libmultiprocess` package and
- a static `libmultiprocess.a` library from the `libmultiprocess` package

### CODE REVIEW

**Comment by luke-jr** [comment]
Concept ACK. Can we avoid building them too?

**Comment by hebasto** [comment]
> Concept ACK. Can we avoid building them too?

Actually, this was my initial intention. Looks like some upstream changes are required. I'm working on them.

**Review by ryanofsky — APPROVED** [review]
Code review ACK 330ff30b6825034a6d096ec468fb837244e44fdd. This seems ok, but a little fragile. My inclination would be to keep the build simpler, and not worry about removing unused functions of dependencies, unless the dependencies are pretty big like boost or qt, not small like libmultiprocess, and there is some notable time or space saving.

But the change looks safe, and as Luke points out it could be expanded to save some build steps too. I think the only change that would be strictly required upstream to do this would be to add [COMPONENT](https://cmake.org/cmake/help/latest/command/install.html) arguments to install commands in https://github.com/chaincodelabs/libmultiprocess/blob/master/CMakeLists.txt. New custom install targets or configuration options could be added upstream to make this easier too.

One suggestion is maybe s/Clean up/Trim/ in PR and commit descriptions. It's definitely fair to say this change makes the packages smaller, but I'm not sure it makes them cleaner, since the package definitions are more complicated than before

**Comment by hebasto** [comment]
Updated 330ff30b6825034a6d096ec468fb837244e44fdd -> f059620a9b483fdfeac5d3905ba702363e7972d4 ([pr25941.01](https://github.com/hebasto/bitcoin/commits/pr25941.01) -> [pr25941.02](https://github.com/hebasto/bitcoin/commits/pr25941.02), [diff](https://github.com/hebasto/bitcoin/compare/pr25941.01..pr25941.02)):

- addressed @ryanofsky's [comment](https://github.com/bitcoin/bitcoin/pull/25941#pullrequestreview-1089185975):
> One suggestion is maybe s/Clean up/Trim/ in PR and commit descriptions.

**Comment by hebasto** [comment]
> This seems ok, but a little fragile. My inclination would be to keep the build simpler, and not worry about removing unused functions of dependencies, unless the dependencies are pretty big like boost or qt, not small like libmultiprocess, and there is some notable time or space saving.

It is mostly not about package sizes, rather about the actual content of the host prefix directory when using those packages.

I believe, keeping there only required staff, i.e., a builder-specific tool and a host-specific library, is clearer and less fragile.

**Review by ryanofsky — APPROVED** [review]
Code review ACK f059620a9b483fdfeac5d3905ba702363e7972d4. Only change since last review is updating commit titles

**Comment by ryanofsky** [comment]
re: https://github.com/bitcoin/bitcoin/pull/25941#issuecomment-1231352839

> It is mostly not about package sizes, rather about the actual content of the host prefix directory when using those packages.

I am confused about the motivation for this if it is not reducing build times or package sizes. What is the benefit to the user or developer of manually deleting intermediate files that later build steps automatically ignore anyway? I'm in favor of whitelisting dependencies and only building things that are needed. But the approach of blacklisting dependencies complicates the build and doesn't seem reliable.

> I believe, keeping there only required staff, i.e., a builder-specific tool and a host-specific library, is clearer and less fragile.

This change makes the build more fragile, not less fragile. Any of the paths this is hardcoding could change. Any of the directories this is recursively deleting could contain files that are needed in the future. It's easy to think of ways the build could break in the future by making this change. It's difficult to think of ways this change could ever prevent some breakage.

Which approach is "clearer" is subjective, but an approach that has simpler builder recipes and fewer build steps and fewer hardcoded install paths seems clearer to me.

I guess I don't think the PR in its current form is an improvement, but I don't think the cost is very high, and wouldn't want disagreement over this to hold up other work.

**Comment by hebasto** [comment]
@ryanofsky 
> What is the benefit to the user or developer of manually deleting intermediate files that later build steps automatically ignore anyway?

"automatically ignore" is a build system feature which can be [broken](https://github.com/bitcoin/bitcoin/pull/25046).

> I'm in favor of whitelisting dependencies and only building things that are needed. But the approach of blacklisting dependencies complicates the build and doesn't seem reliable.

Closing this PR as it seems controversial.

**Comment by ryanofsky** [comment]
> "automatically ignore" is a build system feature which can be [broken](https://github.com/bitcoin/bitcoin/pull/25046).

Oh, I completely forgot about that issue. I wish I would have known that issue was motivating this PR, because otherwise I was very confused didn't know how building unneeded files and then adding an extra step to deleting them could be a practical improvement.

I still think that the issue in #25046 was worth knowing about and fixing instead of masking, but I could understand the opposite point of view. If you think this PR is an improvement feel free to reopen. I never opposed it just didn't like the extra build step and didn't understand what was motivating it.

**Pull request closed without merging**
