### PR TITLE
refactor: Make MempoolAcceptResult members const

### PR DESCRIPTION
**Pull request by glozow**
Follow up to #21062. Was going to be a part of #20833 but I'm trying to break it down as much as possible. 

- Make members const (https://github.com/bitcoin/bitcoin/pull/21062#discussion_r573659273)
- List fee units (https://github.com/bitcoin/bitcoin/pull/21062#discussion_r569329362)
- Use default value for `TxValidationState` in the success case (https://github.com/bitcoin/bitcoin/pull/21062#discussion_r573659801).

### CODE REVIEW

**Comment by jnewbery** [comment]
ACK 363df758a9e0b5e0aa5ab401de2de820fc362c19

**Comment by glozow** [comment]
The comments being addressed were from @MarcoFalke and @ariard

**Review by ariard — COMMENTED** [review]
Code Review ACK 363df75

Thanks for addressing the suggestion.

**Comment by practicalswift** [comment]
cr ACK 363df758a9e0b5e0aa5ab401de2de820fc362c19: patch looks correct and `const` is better than non-`const` (where possible :))

**Pull request merged**
