### PR TITLE
unify capitalization of "bitcoin address"

### PR DESCRIPTION
**Pull request by smatthewenglish**
in some places it was "Bitcoin address" in other places it was "bitcoin address".

I've unified them to make them consistent with the idea that (capital "B") Bitcoin refers to the protocol. 

Of course I left it where it was the start of a sentence. Also I ignored everything in `locale` and `release notes`

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Huh, personally, I'd call it "Bitcoin address" with a capital "B", so it is correct the way it was before.

Also, we should make sure that translation strings are not touched unnecessarily. Please note that translators have to go through all of them, even if "nothing"/whitespace/capitals changed.

**Comment by s-matthew-english** [comment]
to me it doesn't matter but it seems it should be consistent. 

I was thinking that Bitcoin was the protocol itself so that if it was talking about one address to receive bitcoins then it would be lowercase. 

but anyway- in that case there are many instances of "bitcoin address" 

should we change those to "Bitcoin address"?

**Comment by Leviathn** [comment]
One deposits bitcoin to a Bitcoin address - S-Matthew, revert this and change the "bitcoin address" if you want to get this through.

**Comment by s-matthew-english** [comment]
ok cool- so now I've changed all instances of "bitcoin address" to "Bitcoin address"

I ignored everything in `release notes` since jonasschnelli said that's not consequential

**Comment by paveljanik** [comment]
trivial ACK https://github.com/bitcoin/bitcoin/pull/9064/commits/38d2054fe1201b8f275ac5729099bab94997f1f3

**Review by murchandamus — APPROVED** [review]
ACK (I've looked over the changed code.)

**Comment by MarcoFalke** [comment]
I tried to look up the "correct" capitalization, but there seem to be some discrepancy and no clear and "correct" way. I think it is fine to use both capitalizations exchangeably.

I understand the need to unify the capitalization, but if that means we possibly need to change all of that back to the other way next year, I'd prefer to not change it at all.

Closing for now. (Heh, maybe wait until there is a wikipedia article [Capitalization of "Bitcoin"](https://en.wikipedia.org/wiki/Capitalization_of_%22Bitcoin%22), just like [Capitalization of "Internet"](https://en.wikipedia.org/wiki/Capitalization_of_%22Internet%22))

**Comment by s-matthew-english** [comment]
yeah, I feel you, but in my idea, like- Wikipedia is fully of a lot of crap- I know- since I put a bunch of it there. This GitHub code is sort of like the canonical reference, isn't it? So for instance- I feel like if the capitalization were firmly established here then others would adopt to the way we make it, and not really the other way around, you know what I mean?

**Comment by MarcoFalke** [comment]
We don't act as a reference for spelling (luckily), but I am not strongly against this change, if it at least makes our spelling consistent.

**Comment by s-matthew-english** [comment]
checkout the footnote on page 2* from Sarah Meiklejohn's `Fistful of Bitcoins` paper. 

    Note that this statement is not strictly true since private exchanges
    of Bitcoin between customers of a single third party exchange, such
    as Mt. Gox, need not (and do not) engage the global Bitcoin protocol
    and are therefore not transparent.

So- this change applies this convention in the same way 

*https://cseweb.ucsd.edu/~smeiklejohn/files/imc13.pdf

**Comment by fanquake** [comment]
Closing this. Doesn't seem to be consensus. Needs a rebase.

**Pull request closed without merging**
