### PR TITLE
[trivial] Move blocksonly parameter interaction to InitParameterInteraction()

### PR DESCRIPTION
**Pull request by maflcko**
Caused by a rebase conflict in #6780.

### CODE REVIEW

**Comment by pstratem** [comment]
This seems to be missing something :)

**Comment by MarcoFalke** [comment]
@pstratem Indeed, this should be squashed into df661476133364956a188f892de97974e69f8d6c. But this is already merged so I guess there is nothing I could do about that.

**Comment by jonasschnelli** [comment]
Oops.
Thanks for fixing!

utACK.

**Comment by paveljanik** [comment]
ACK

**Comment by dcousens** [comment]
ACK

**Pull request merged**
