### PR TITLE
test: Run non-wallet tests only once

### PR DESCRIPTION
**Pull request by maflcko**
I don't see why non-wallet tests should run for two wallet configs, even though they never use a wallet.

### CODE REVIEW

**Comment by ayush933** [comment]
Maybe this would also apply to `rpc_createmultisig.py` if #24587 is merged?

**Comment by MarcoFalke** [comment]
Good point. I think you can just do it right there in that pull request.

**Comment by michaelfolkson** [comment]
Concept ACK

Doesn't make sense for wallet_disable.py to be run twice with both `--legacy-wallet` and `--descriptors` given the wallet is disabled for this test.

The wallet isn't necessarily disabled for feature_coinstatsindex.py? That uses MiniWallet so I'm unsure why that is included in this PR.

**Comment by michaelfolkson** [comment]
> Maybe this would also apply to rpc_createmultisig.py if https://github.com/bitcoin/bitcoin/pull/24587 is merged?

@ayush933: I wouldn't make any changes to your PR yet until this PR is merged. It is possible your PR could be merged first (hard to know at this point). But yeah if this PR is merged first you can edit/update your PR.

**Comment by MarcoFalke** [comment]
Starting with commit https://github.com/bitcoin/bitcoin/commit/e3206c9445f8d8e2bdb36d98af609985e8809908 the test doesn't use *any* Bitcoin Core wallet at all, even if one is compiled. So telling the test to use one or the other doesn't make sense.

**Comment by michaelfolkson** [comment]
> edit: Looking through the [test_runner.py](https://github.com/bitcoin/bitcoin/blob/master/test/functional/test_runner.py) it appears there are a number of non-wallet tests that are being run twice (if the criteria is that it isn't testing the Core wallet rather than the Core wallet is explicitly disabled like in wallet_disable.py)

So I think this PR (or a follow up PR) should ensure *all* the non-wallet tests (files beginning with `wallet_`) should run only once right? There's no particular reason that feature_coinstatsindex.py is included in this PR but say rpc_signrawtransaction.py (or indeed rpc_createmultisig.py) isn't?

I guess individuals could open PRs for each non-wallet test that not only uses MiniWallet but also cleans up the --legacy-wallet and --descriptors double tests.

**Comment by MarcoFalke** [comment]
I have no opinion about tests that are not wallet specific, but happen to use the wallet. Maybe this can be discussed/done in a follow-up?

The goal of this pull request is to run tests that don't use the wallet at all to run only once.

**Comment by achow101** [comment]
ACK fa7a576391ad5d61af937dd62496ded44105c671

**Pull request merged**
