### PR TITLE
fuzz: Add regression test for wallet crash

### PR DESCRIPTION
**Pull request by maflcko**
This adds a regression fuzz test for the bug fixed in commit 24abd8312ec1caa04f9b3bd92cd960e28ca91e17.

Steps to test:

```
git show 0fbaef9676a1dcb84bcf95afd8d994831ab327b6 ./src/policy/feerate.cpp | git apply --reverse
# compile fuzz test ...
FUZZ=wallet_notifications ./src/test/fuzz/fuzz
# wait and observe crash ...

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Example crash: [crash-6cd0f86f18ce0ec5b48beb59c602c8f807fe197a.bin.txt](https://github.com/bitcoin/bitcoin/files/7487551/crash-6cd0f86f18ce0ec5b48beb59c602c8f807fe197a.bin.txt)

**Comment by MarcoFalke** [comment]
Be aware that the crash is currently non-deterministic. I presume because the wallet's keys are non-deterministic (random). It might be a good idea to make the wallet generation deterministic for this fuzz test.

**Comment by MarcoFalke** [comment]
> It might be a good idea to make the wallet generation deterministic for this fuzz test.

Done

**Comment by jamesob** [comment]
Concept ACK - will review soon

**Comment by MarcoFalke** [comment]
Ok, it is still not deterministic :disappointed: . Maybe the coin selection is too random?

**Comment by achow101** [comment]
> Ok, it is still not deterministic disappointed . Maybe the coin selection is too random?

It's probably the **random** selection algorithm.

**Comment by fanquake** [comment]
> Ok, it is still not deterministic 😞 . Maybe the coin selection is too random?

Has this situation improved at all with recent coin selection changes?

**Comment by achow101** [comment]
Closing this as it has not had any activity in a while. If you are interested in continuing work on this, please leave a comment so that it can be reopened.

**Pull request closed without merging**
