### PR TITLE
ci: Run functional tests on mac again

### PR DESCRIPTION
**Pull request by maflcko**

### CODE REVIEW

**Comment by hebasto** [comment]
Concept ACK.

What is changed since #17240?

**Comment by MarcoFalke** [comment]
Idk, they seem to pass, so why not enable them again and give it a shot?

**Comment by MarcoFalke** [comment]
Passed once: https://travis-ci.org/github/bitcoin/bitcoin/jobs/679893016#L3111

Open-Close to re-run ci. See https://github.com/bitcoin/bitcoin/issues/15847#issuecomment-487591130

**Comment by Sjors** [comment]
Concept ACK, I didn't even remember we turned them off.

**Comment by Sjors** [comment]
`wallet_multiwallet.py` failed, presumably randomly. I restarted it.

**Comment by MarcoFalke** [comment]
Please don't restart without saving the log. Otherwise, the issue can not be fixed.

**Review by hebasto — APPROVED** [review]
ACK fac24dea00c54fe1e2dcc7625bb65ada8b97ac0c, verified travis build log.

**Pull request merged**
