### PR TITLE
CAddrMan::Deserialize handle corrupt serializations better.

### PR DESCRIPTION
**Pull request by pstratem**

### CODE REVIEW

**Comment by laanwj** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/7932/commits/fb26bf0ea3822638b10a783f054c280fc053a2b5

**Comment by sipa** [comment]
Does this interact with #7696?

**Comment by pstratem** [comment]
@sipa I believe these are mutually beneficial and not conflicting.

**Comment by sipa** [comment]
utACK fb26bf0ea3822638b10a783f054c280fc053a2b5

**Pull request merged**
