### PR TITLE
build: Remove spurious dollar sign. Fixes #7189.

### LINKED ISSUE #7189: Bitcoin GUI is not built when only qt4 is installed
From IRC:

@phantomcircuit: @jonasschnelli, ./configure doesn't detect qt4 on my debian jessie system 
i had to manually specify --with-gui=qt4

### PR DESCRIPTION
**Pull request by dooglus**
Fixes #7189.

### CODE REVIEW

**Comment by paveljanik** [comment]
ACK

**Comment by paveljanik** [comment]
It is there starting from 2014-01-10...

**Comment by jonasschnelli** [comment]
Nice catch!
utACK.

**Comment by fanquake** [comment]
utACK https://github.com/dooglus/bitcoin/commit/3d19193f14b9400f7c908a61375c330113571a38

**Comment by dooglus** [comment]
Here's the limited testing I did, showing that it uses Qt4 if Qt5 isn't available:

    $ alias show4='sudo mv /usr/lib/x86_64-linux-gnu/pkgconfig/QtCore.pc{.hide,}'
    $ alias hide4='sudo mv /usr/lib/x86_64-linux-gnu/pkgconfig/QtCore.pc{,.hide}'
    $ alias show5='sudo mv /usr/lib/x86_64-linux-gnu/pkgconfig/Qt5Core.pc{.hide,}'
    $ alias hide5='sudo mv /usr/lib/x86_64-linux-gnu/pkgconfig/Qt5Core.pc{,.hide}'

    # before applying the fix

    $ hide4; hide5; ./configure --with-incompatible-bdb 2>&1 | grep 'GUI.*Qt' # no QT4 or QT5
    checking whether to build Bitcoin Core GUI... no (Qt5)

    $ show4; ./configure --with-incompatible-bdb 2>&1 | grep 'GUI.*Qt' # QT4 only
    checking whether to build Bitcoin Core GUI... no (Qt5)

    $ hide4; show5; ./configure --with-incompatible-bdb 2>&1 | grep 'GUI.*Qt' # QT5 only
    checking whether to build Bitcoin Core GUI... yes (Qt5)

    $ show4; ./configure --with-incompatible-bdb 2>&1 | grep 'GUI.*Qt' # QT4 and QT5
    checking whether to build Bitcoin Core GUI... yes (Qt5)


    # apply the fix and re-run autogen.sh:
    $ sed -i -e 's/x[$]qt5/xqt5/' build-aux/m4/bitcoin_qt.m4
    $ ./autogen.sh > /dev/null 2>&1


    # after applying the fix
    $ hide5; hide4; ./configure --with-incompatible-bdb 2>&1 | grep 'GUI.*Qt' # no QT4 or QT5
    checking whether to build Bitcoin Core GUI... no (Qt5)

    $ show4; ./configure --with-incompatible-bdb 2>&1 | grep 'GUI.*Qt' # QT4 only
    checking whether to build Bitcoin Core GUI... yes (Qt4) # we have QT4 and not QT5. 4 is used

    $ hide4; show5; ./configure --with-incompatible-bdb 2>&1 | grep 'GUI.*Qt' # QT5 only
    checking whether to build Bitcoin Core GUI... yes (Qt5)

    $ show4; ./configure --with-incompatible-bdb 2>&1 | grep 'GUI.*Qt' # QT4 and QT5
    checking whether to build Bitcoin Core GUI... yes (Qt5)

**Comment by laanwj** [comment]
utACK 3d19193

**Comment by MarcoFalke** [comment]
Backported as part of #7938. Removing label 'Needs backport'.

**Pull request merged**
