### PR TITLE
LevelDB 1.19

### PR DESCRIPTION
**Pull request by sipa**
This upgrades the src/leveldb subtree to our version with upstream 1.19 merged in.

I've marked it here as [preview] because it depends on https://github.com/bitcoin-core/leveldb/pull/14 being merged.

### CODE REVIEW

**Comment by laanwj** [comment]
Concept ACK

**Comment by paveljanik** [comment]
Configures OK, compiles OK, one warning removed:

```
leveldb/util/bloom.cc:50:26: warning: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
    for (size_t i = 0; i < n; i++) {
                       ~ ^ ~
1 warning generated.
```

ACK

**Comment by sipa** [comment]
Updated to include @laanwj's NewAppendableFile change (see bitcoin-core/leveldb#14). This should be tested on various platforms.

**Comment by laanwj** [comment]
I'm testing this on Windows x86_64. Also going to test on ARM/Linux.

**Comment by sipa** [comment]
@laanwj My understanding is that the NewAppendableFile won't actually be used unless we enable the new options.reuse_logs option.

**Comment by laanwj** [comment]
Ehm yes that seems the case. It is used in only two places and both are guarded by `reuse_logs`. I didn't notice the latter point. 
```
  // EXPERIMENTAL: If true, append to existing MANIFEST and log files
  // when a database is opened.  This can significantly speed up open.
  //
  // Default: currently false, but may become true later.
  bool reuse_logs;
```
Reading the description, speeding up "open" isn't really an important concern for us at the moment.
Well at least we can switch the option on now if we wanted...

**Comment by sipa** [comment]
@laanwj When you run with a huge dbcache, sync a lot at once, and shutdown, the next startup takes a very long time. I believe that reuse_logs may improve upon that.

**Comment by laanwj** [comment]
Going to merge this - gives the new version of leveldb some time to be tested in master before 0.14 is released.

> I believe that reuse_logs may improve upon that.

The option is still experimental in leveldb so enabling it by default is probably not a good idea.

But I guess we could first add it too as an experimental feature enabled by a command-line argument.

**Pull request merged**
