### PR TITLE
Fix bumpfee test after #10449

### PR DESCRIPTION
**Pull request by ryanofsky**
Failure reported by @jtimon https://github.com/bitcoin/bitcoin/pull/10449#issuecomment-305556569

### CODE REVIEW

**Comment by ryanofsky** [comment]
Note travis didn't catch this because there isn't currently a travis configuration with qt, wallet, and tests all enabled.

**Comment by achow101** [comment]
ACK 8906a9a0d299c9d10c1d40fbec9756625f32f048

**Comment by jtimon** [comment]
This fixes the tests, tested ACK pr/10506/head 8906a9a0

**Comment by sipa** [comment]
utACK 8906a9a0d, but verifies it fixes the bug.

**Comment by jonasschnelli** [comment]
Oh! Thanks for reporting and fixing.
I thought Travis run those tests... can we add it?

**Comment by ryanofsky** [comment]
> I thought Travis run those tests... can we add it?

We'll see, attempted in #10508.

**Pull request merged**
