### PR TITLE
Revert "Merge #19606: Backport wtxid relay to v0.20"

### PR DESCRIPTION
**Pull request by maflcko**
The 0.20 branch has bugfixes that should be released. However, a tag can currently not be created because the latest merge introduced a regression and is not a bugfix (https://github.com/bitcoin/bitcoin/pull/20317#issuecomment-723754509, https://github.com/bitcoin/bitcoin/pull/20317#issuecomment-727624755).

Fix that by reverting the last merge. Can be reviewed by re-doing the revert or calling `git diff HEAD HEAD~2 | wc` and observing an empty diff.

### CODE REVIEW

**Comment by jnewbery** [comment]
It seems odd to revert a feature that's already been reviewed and merged. If we think this is unsafe it should also be reverted in the master branch.

**Comment by MarcoFalke** [comment]
#20317 has no ACKs so far, so it can't be merged right now. It is holding back the next minor release which has already quite a few bugfixes waiting to be shipped.

I can't vouch whether the backport is safe or unsafe, but we've never delayed a bugfix release to backport a feature. Also, I think this is the first time ever that a feature was backported to a bugfix release and released before it was released in a major version.

If #20317 gets enough review to make it into the release, fine by me. Otherwise the milestone will simply be adjusted by one minor version. Also, no review will be lost. Observing and ACKing an empty diff can be done by anyone.

**Comment by MarcoFalke** [comment]
(appveyor failure can be ignored, as it is caused by appveyor bumping the compiler version)

**Comment by adamjonas** [comment]
Linking to [relevant notes](https://github.com/bitcoin-core/bitcoin-devwiki/wiki/P2P-IRC-meetings#topic-touch-base-on-wtxid-backport-aj) from this week's p2p IRC meeting on reverting #19606.

**Comment by laanwj** [comment]
Code review ACK fa074d2c7b9c3d34876c428d12672a505d4ce4eb
```bash
$ git fetch upstream pull/20399/head
$ git checkout FETCH_HEAD
$ git diff HEAD HEAD~2 | wc -l
0
```
(this doesn't work with the *merge* of this PR to the branch because there was an intermediate merge of #20166 in between, but that's okay, it still applies cleanly)

**Pull request merged**
