### PR TITLE
test: Declare `nodes` type in test_framework.py.

### PR DESCRIPTION
**Pull request by kiminuo**
### Motivation

When I wanted to understand better https://github.com/bitcoin/bitcoin/pull/19145/files#diff-4bebbd3b112dc222ea7e75ef051838ceffcee63b9e9234a98a4cc7251d34451b test, I noticed that navigation in PyCharm/VS Code did not work for `nodes` variable. I think this is frustrating, especially for newcomers. 

### Summary

* This PR modifies Python 3.5 [type comments](https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html#variables) to Python 3.6+ types and adds a proper type for `nodes` [instance attribute](https://mypy.readthedocs.io/en/stable/class_basics.html#instance-and-class-attributes).
* This PR does not change behavior.
* This PR is intentionally very small, if the concept is accepted, a follow-up PRs can be more ambitious.

### End result

1. Open `test/functional/feature_abortnode.py`
2. Move your caret to: `self.nodes[0].generate[caret here](3)`
3. Use "Go to definition" [F12] should work now.

I have tested this on PyCharm (Windows, Ubuntu) and VS Code (Windows, Ubuntu).

Note: Some `TestNode` methods (e.g. `self.nodes[0].getblock(...)` ) use `__call__` mechanism and navigation does not work for them even with this PR.

### CODE REVIEW

**Review by brunoerg — COMMENTED** [review]
Shouldn't the types be added in all vars (network_thread, rpc_timeout..)?

**Comment by kiminuo** [comment]
> Shouldn't the types be added in all vars (network_thread, rpc_timeout..)?

Yes but as I wrote in the description "This PR is intentionally very small, if the concept is accepted, a follow-up PRs can be more ambitious."

**Comment by laanwj** [comment]
Looks correct to me (and the CI does mypy checks on the test framework).
ACK 5353b0c64d32e44fc411464e080d4b00fae7124e

**Comment by brunoerg** [comment]
> > Shouldn't the types be added in all vars (network_thread, rpc_timeout..)?
> 
> Yes but as I wrote in the description "This PR is intentionally very small, if the concept is accepted, a follow-up PRs can be more ambitious."

No problem. Concept ACK.

**Review by theStack — APPROVED** [review]
I was curious and tried this out with PyCharm 2020.3.3 (Community Edition) and Python 3.9.1 under Win10. Navigation to the implementation of `generate` via Ctrl-Alt-B (I guess the proposed shortcut F12 is avilable in VSCode?) did work both in master and PR branch.

That said, the patch looks correct.

ACK 5353b0c64d32e44fc411464e080d4b00fae7124e

**Pull request merged**
