### PR TITLE
Perform member initialization in initialization lists where possible

### PR DESCRIPTION
**Pull request by practicalswift**
See https://isocpp.org/wiki/faq/ctors#init-lists

### CODE REVIEW

**Comment by sipa** [comment]
utACK 656dbd871ae5f460c6ae4506376b059ed41fb6bc

**Comment by benma** [comment]
utACK 656dbd871ae5f460c6ae4506376b059ed41fb6bc

**Comment by MarcoFalke** [comment]
utACK 656dbd871ae5f460c6ae4506376b059ed41fb6bc

**Comment by paveljanik** [comment]
ACK 656dbd8

**Comment by laanwj** [comment]
I only just get mail that this was assigned to me. Thanks github...

**Pull request merged**
