### PR TITLE
wallet: load flags before everything else

### PR DESCRIPTION
**Pull request by Sjors**
Load and set wallet flags before processing other records. That way we can take them into account while processing those other records. 

Suggested here:
https://github.com/bitcoin/bitcoin/pull/16546#discussion_r572334983

### CODE REVIEW

**Comment by achow101** [comment]
ACK afdfb1d2a235ea3e809f1079358cbd3ec73c4ee4

**Comment by Sjors** [comment]
Appeased linter.

**Comment by laanwj** [comment]
Code review ACK 9305862f71189d47c873d366bf976622447e18af

**Comment by Sjors** [comment]
@instagibbs?

**Comment by gruve-p** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/21127/commits/9305862f71189d47c873d366bf976622447e18af

**Comment by achow101** [comment]
ACK 9305862f71189d47c873d366bf976622447e18af

**Pull request merged**
