### PR TITLE
Trivial: Correct indentation and bracing

### PR DESCRIPTION
**Pull request by matthias-g**
This corrects the indentation after a while loop was removed in c5a8b1b946b1ab0bb82bd4270b2a40f5731abcff

### CODE REVIEW

**Comment by laanwj** [comment]
There are some more sillly uses of indentation/bracing left over in network code, for example: 
https://github.com/bitcoin/bitcoin/blob/master/src/net.cpp#L1295

Agree this needs to be cleaned up at some point, let's try to do it in one pass.

**Comment by fanquake** [comment]
Note that this isn't a move-only change, two sets of brackets are being removed. Add ?w=1 to the URL to see.

**Comment by MarcoFalke** [comment]
Please squash your commits according to https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#squashing-commits

**Comment by fanquake** [comment]
Needs a rebase.

**Comment by laanwj** [comment]
Thanks. utACK 31a14d4

**Pull request merged**
