### PR TITLE
RPC/Mining: Clean out pre-Segwit miner compatibility code

### PR DESCRIPTION
**Pull request by luke-jr**
This is dead code post-Segwit.

### CODE REVIEW

**Comment by promag** [comment]
ACK

**Comment by MarcoFalke** [comment]
Concept ACK on removing unused code

**Comment by jnewbery** [comment]
This is based on a 2018 base commit. Needs to be rebased to pick up all of the new tests/changes since then.

**Comment by jnewbery** [comment]
Code looks safe, but should be rebased on a recent base commit to ensure all new tests/checks run successfully.

Should https://github.com/bitcoin/bips/blob/master/bip-0009.mediawiki#getblocktemplate-changes be updated to say that `maxversion` no longer has meaning?

**Comment by fanquake** [comment]
> but should be rebased on a recent base commit to ensure all new tests/checks run successfully.

Agree. This branch is currently based off (8a9ffec0a257da659ba54c5073bfc820986ae9c1).

> Should https://github.com/bitcoin/bips/blob/master/bip-0009.mediawiki#getblocktemplate-changes be updated to say that maxversion no longer has meaning?

This also still needs a response.

Added "Waiting for author".

**Comment by luke-jr** [comment]
Rebased due to conflicts, but note

>Code looks safe, but should be rebased on a recent base commit to ensure all new tests/checks run successfully.

That's not a reason to rebase. That's a flaw in QA infra. It should be merging to master before running tests/checks.

**Comment by fanquake** [comment]
Concept ACK

> That's not a reason to rebase. That's a flaw in QA infra.

There's a myriad of reasons to keep development branches rebased up and/or up to date.

If I'm a dev wanting to just simply checkout and test this code, i.e `git fetch origin pull/19391/head:19391 && git checkout 19391`, not only should I not have to worry about merging it into master myself, but, having a commit here based on a branch from years ago means it's going to bust up my caches when compiling, have missing tests, lack support for fuzzers & other tooling that's been added in the interim, depends will be outdated, so if I'm building against that I'll be testing against old / potentially broken dependencies. I also shouldn't need to replicate the QA infra locally to test things fairly extensively.

**Comment by MarcoFalke** [comment]
> going to bust up my caches

Personally I rebase/merge every change I test on master (even if it is just a single commit back) to rule out any unintended cache mishaps and at the same time check for silent merge conflict.

If there is no reason to rebase, I think the approach @luke-jr is taking seems fine.

**Comment by glozow** [comment]
Concept ACK

**Comment by MarcoFalke** [comment]
(red CI can be ignored, I think)

**Comment by fanquake** [comment]
Added to the 24.0 milestone.

**Comment by fanquake** [comment]
@luke-jr do you want to rebase this, otherwise I can drop it back off the milestone.

**Comment by luke-jr** [comment]
#25153 should really have been reverted, but rebased anyway.

**Comment by achow101** [comment]
ACK 90a5dfa5098f142ba8b7b2f20eac31f4095ca583

**Pull request merged**
