### PR TITLE
ci: Remove bdb build from msan task

### PR DESCRIPTION
**Pull request by maflcko**
This removes BDB from the CI msan task, because:

* It is a common source for failures, as the script doesn't have fallbacks on network errors
* Most wallet code is also covered via sqlite and any bdb-only wallet code can be checked with valgrind

### CODE REVIEW

**Comment by Sjors** [comment]
Concept ACK

IIUC we do still check BDB functionality in plenty of other tests, so this just loses the memory sanitizer coverage. Since we shoved the legacy (BDB) wallet into a box (`LegacyScriptPubKeyMan`), we probably won't be touching its internals (often). Just have to remember, when we do, to be a bit extra careful.

Are you sure this actually removes BDB from that task? E.g. `BDB_PREFIX` is still used in `BITCOIN_CONFIG`. Maybe explicitly opt-out with `--without-bdb` (also for clarity).

**Comment by MarcoFalke** [comment]
Thanks, fixed. NO_BDB=1 is already set.

**Comment by Sjors** [comment]
> Thanks, fixed. NO_BDB=1 is already set.

That's odd; then what was the point of building it? Only compile time checks for dependency itself?

**Comment by Sjors** [comment]
Oh wait, `NO_BDB` only affects the depends build. Fairly confusing, hence my suggestion to make it explicit with `--without-bdb`.

**Comment by MarcoFalke** [comment]
I think it is better to keep it as is now, because:

* No bdb build is known to pass, so there should be no way to re-enable one without making CI red.
* If there was one that passes, having to modify a single place seems less confusing than having to modify two places at the same time.

**Comment by MarcoFalke** [comment]
Looks like this fixed itself, but we should still consider doing this anyway in the future.

**Comment by fanquake** [comment]
Concept ACK. I had a similar change in an MSAN branch.

**Pull request closed without merging**
