### PR TITLE
refactor: add clang-tidy `modernize-use-starts-ends-with` check

### PR DESCRIPTION
**Pull request by romanz**

### CODE REVIEW

**Review by stickies-v — COMMENTED** [review]
Code LGTM eb43872b84bfc4d09fe38ce0cb74722f6f9842da. Commit message and PR title need updating, this is a `tidy` change now affecting multiple modules, not an `http` change.

**Review by jonatack — COMMENTED** [review]
ACK 22bc9fdca314549bf204d3e3f577d7f014858f42

Maybe name this PR (and the commit, if you need to retouch):

tidy: add clang-tidy `modernize-use-starts-ends-with` check

**Review by stickies-v — APPROVED** [review]
ACK fc7b507e9a595a7bf91f4e0f42b4d842af8b93f3

**Review by hebasto — APPROVED** [review]
ACK fc7b507e9a595a7bf91f4e0f42b4d842af8b93f3, I have reviewed the code and it looks OK.

**Comment by achow101** [comment]
ACK fc7b507e9a595a7bf91f4e0f42b4d842af8b93f3

**Comment by romanz** [comment]
Many thanks!

**Comment by fanquake** [comment]
Seems like newer Clang 19 has improved this check, and throws out more (historical) instances to change. i.e:
```bash
bitcoin/src/torcontrol.cpp:359:27: error: use starts_with instead of compare() == 0 [modernize-use-starts-ends-with,-warnings-as-errors]
  359 |             if (0 == line.compare(0, 20, "net/listeners/socks=")) {
      |                 ~~~~      ^~~~~~~~~~~~~~                       ~
      |                           starts_with(                         )
bitcoin/src/torcontrol.cpp:370:38: error: use starts_with instead of compare() == 0 [modernize-use-starts-ends-with,-warnings-as-errors]
  370 |                     if (0 == portstr.compare(0, 10, "127.0.0.1:")) {
      |                         ~~~~         ^~~~~~~~~~~~~~             ~
      |                                      starts_with(               )
bitcoin/src/core_read.cpp:42:25: error: use starts_with instead of compare() == 0 [modernize-use-starts-ends-with,-warnings-as-errors]
   42 |             if (strName.compare(0, 3, "OP_") == 0) { // strName starts with "OP_"
      |                         ^~~~~~~~~~~~~      ~~~~~~
      |                         starts_with(       )
bitcoin/src/wallet/walletdb.cpp:1016:27: error: use starts_with instead of compare() == 0 [modernize-use-starts-ends-with,-warnings-as-errors]
 1016 |         } else if (strKey.compare(0, 2, "rr") == 0) {
      |                           ^~~~~~~~~~~~~     ~~~~~~
      |                           starts_with(      )
<snip the rest>
```

**Comment by hebasto** [comment]
> Seems like newer Clang 19 has improved this check, and throws out more (historical) instances to change. i.e:
> 
> ```shell
> bitcoin/src/torcontrol.cpp:359:27: error: use starts_with instead of compare() == 0 [modernize-use-starts-ends-with,-warnings-as-errors]
>   359 |             if (0 == line.compare(0, 20, "net/listeners/socks=")) {
>       |                 ~~~~      ^~~~~~~~~~~~~~                       ~
>       |                           starts_with(                         )
> bitcoin/src/torcontrol.cpp:370:38: error: use starts_with instead of compare() == 0 [modernize-use-starts-ends-with,-warnings-as-errors]
>   370 |                     if (0 == portstr.compare(0, 10, "127.0.0.1:")) {
>       |                         ~~~~         ^~~~~~~~~~~~~~             ~
>       |                                      starts_with(               )
> bitcoin/src/core_read.cpp:42:25: error: use starts_with instead of compare() == 0 [modernize-use-starts-ends-with,-warnings-as-errors]
>    42 |             if (strName.compare(0, 3, "OP_") == 0) { // strName starts with "OP_"
>       |                         ^~~~~~~~~~~~~      ~~~~~~
>       |                         starts_with(       )
> bitcoin/src/wallet/walletdb.cpp:1016:27: error: use starts_with instead of compare() == 0 [modernize-use-starts-ends-with,-warnings-as-errors]
>  1016 |         } else if (strKey.compare(0, 2, "rr") == 0) {
>       |                           ^~~~~~~~~~~~~     ~~~~~~
>       |                           starts_with(      )
> <snip the rest>
> ```

Addressed in https://github.com/bitcoin/bitcoin/pull/31306.

**Pull request merged**
