### PR TITLE
[0.13 backport] Attempt reconstruction from all compact block announcements

### PR DESCRIPTION
**Pull request by sdaftuar**
Backport of #9352 to the 0.13 branch.

Because in 0.13 we call MarkBlockAsReceived inside ProcessNewBlock(), this code is slightly different from the version in #9352 -- I put a comment that should explain everything.

### CODE REVIEW

**Comment by gmaxwell** [comment]
utACK. Will test.

**Comment by TheBlueMatt** [comment]
utACK 53b656f3558fe960d9328079ca18eb53418f2652

**Comment by gmaxwell** [comment]
ACK.

**Comment by btcdrak** [comment]
ACK 53b656f

**Pull request merged**
