### PR TITLE
bitcoin-tx input verification (awemany, jnewbery)

### PR DESCRIPTION
**Pull request by jnewbery**
Check number of arguments passed to bitcoin-tx in outaddr and outpubkey.

This PR also updates the bitcoin-tx tests to check bitcoin-tx stderr and verify that expected errors are raised.

Adds test cases for calling bitcoin-tx with wrong number of separators in outaddr and outpubkey.

### CODE REVIEW

**Comment by jnewbery** [comment]
Replaces #10106. @gmaxwell @instagibbs @laanwj @jtimon

**Comment by jnewbery** [comment]
@theuni has suggested that checking the stderr for error text may cause problems due to unicode, eols, etc, and that we'd be better off defining our own exit codes in bitcoin-tx and testing on those. I think it's ok to test for text in stderr for now, but we a future PR should define exit codes and test them in bctest.py.

**Comment by laanwj** [comment]
I don't disagree with @theuni on that in general, however checking for text in error messages is perfectly fine for tests that are supposed to test these errors. Especially for a user-facing tool. We do a similar thing for checking e.g. RPC errors where we check both the code and the message.

**Comment by laanwj** [comment]
utACK 19ecd1e

**Comment by gmaxwell** [comment]
@awemany Fix moved over here, your review/testing would be very welcome!

**Review by gmaxwell — APPROVED** [review]
ACK (did not test test, e.g. by introducing a bug).

**Comment by theuni** [comment]
As mentioned in the comments: for reference, I suggested using exit codes rather than comparing text because (here specifically), Wine piles nonsense about window creation into stderr when running without DISPLAY set. For that reason, we can't test that "stderr == expected", rather we have to test "expected in stderr". That's not great, but it's not a huge deal either.

utACK 19ecd1e2e13514c8a92a2a4337c2568c3d5d13e5

**Pull request merged**
