### PR TITLE
[qt] Use tr() instead of _()

### PR DESCRIPTION
**Pull request by maflcko**
code move between bitcoind an bitcoin-qt is **not** move only. I did it wrong in fa41d4c8c6e3f84a9117c0addf51a87f14321e2a.

### CODE REVIEW

**Comment by laanwj** [comment]
Please do a 'make translate' in qt and commit the `bitcoin_en.ts`

**Comment by jonasschnelli** [comment]
Thanks!
utACK.

**Comment by MarcoFalke** [comment]
Force pushed because `HelpMessageOpt()` only accepts `toStdString()`

**Comment by laanwj** [comment]
utACK

**Comment by jonasschnelli** [comment]
Gave it a testshot with `-lang=fr_FR`. It does not translate. Do we need new strings/translations? The translation is available in `bitcoin_fr.ts`.

See:
bildschirmfoto 2015-12-02 um 19 58 22

**Comment by MarcoFalke** [comment]
>Gave it a testshot with -lang=fr_FR. 

@jonasschnelli Thanks for having a look!

> It does not translate. Do we need new strings/translations?

Yes, uioptions, allowselfsignedrootcertificates, resetguisettings, choosedatadir and splash need fresh translations anyway.

lang, min, rootcertificates are possibly gone from transifex due to the mistake.

I think @laanwj isn't doing a sync for rc1 but for rc2

> The translation is available in bitcoin_fr.ts.

They shouldn't imo. You are not running a clean build?

**Comment by jonasschnelli** [comment]
Tested again and something I don't understand.
I took a (almost) fresh repository and added...
```xml
    <message>
        <source>Start minimized</source>
        <translation>(FR)Start minimized</translation>
    </message>
```
to `bitcoin_fr.ts`.
Compiled again.
```shell
jonasschnelli$ pmake
  GEN      qt/locale/bitcoin_fr.qm
  GEN      qt/qrc_bitcoin_locale.cpp
  CXX      qt/qt_libbitcoinqt_a-qrc_bitcoin_locale.o
  AR       qt/libbitcoinqt.a
  OBJCXXLD qt/bitcoin-qt
  CXXLD    qt/test/test_bitcoin-qt
```
(^ --- looks good)

But it looks like that the changes has no effect:
bildschirmfoto 2015-12-03 um 08 06 47

Changing a different already existing translations works:
bildschirmfoto 2015-12-03 um 08 06 36

What am I doing wrong or why does it not translate the strings added to the french translation file?

**Comment by laanwj** [comment]
Tested ACK. I applied this patch, then added the following in the context `HelpMessageDialog` in `bitcoin_fr.ts`
```
<context>
    <name>HelpMessageDialog</name>
...
    <message>
        <source>Start minimized</source>
        <translation>French translation</translation>
    </message>
</context>
```
Then build and show options:
```
$ make -j10
$ src/qt/bitcoin-qt -lang=fr --help
...
UI Options:
  -min
       French translation
...
```

**Comment by jonasschnelli** [comment]
Thanks!
I mixed up the `<context>`.

**Pull request merged**
