### PR TITLE
[net] add seed.bitcoin.sprovoost.nl to DNS seeds

### PR DESCRIPTION
**Pull request by Sjors**
ACK https://github.com/bitcoin/bitcoin/blob/master/doc/dnsseed-policy.md

I'm willing to keep it up and running at least throughout 2018, unless something bad happens.

Same setup as #11917, but with a dedicated instance.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Tested ACK ab8b18342d9d08d7eab8c64a5b1802150ebb9e95.
* Domain is linked to http://www.uroulette.com (not sure if that is good or bad. :))
* Default SSH port is 22 (though I don't want to criticise your security setup)

Sjors is a relatively new contributor, first issue 2017-09-06 (#11219) PR opened 2017-09-26 (#11219), though, he is pretty active.
He is active on Github since 2008.

**Comment by jonasschnelli** [comment]
Oh ... I think my test was wrong.
I guess it connected to one of the IPs from the seeder response.

```shell
curl -v seed.bitcoin.sprovoost.nl
* Rebuilt URL to: seed.bitcoin.sprovoost.nl/
*   Trying 144.76.99.209...
* TCP_NODELAY set
*   Trying 2001::9d38:953c:2cba:3eb8:8e96:74d5...
* TCP_NODELAY set
* Immediate connect fail for 2001::9d38:953c:2cba:3eb8:8e96:74d5: No route to host
*   Trying 2001:470:8:7b3::17...
* TCP_NODELAY set
* Immediate connect fail for 2001:470:8:7b3::17: No route to host
*   Trying 2001:470:8:7b3::55...
* TCP_NODELAY set
* Immediate connect fail for 2001:470:8:7b3::55: No route to host
*   Trying 2001:470:1d:8a9::...
* TCP_NODELAY set
* Immediate connect fail for 2001:470:1d:8a9::: No route to host
*   Trying 2604:4500::a2:225:90ff:fe5c:f7f0...
* TCP_NODELAY set
* Immediate connect fail for 2604:4500::a2:225:90ff:fe5c:f7f0: No route to host
*   Trying 2001:470:1d:8a9::4...
* TCP_NODELAY set
* Immediate connect fail for 2001:470:1d:8a9::4: No route to host
*   Trying 2002:7169:8b2a::7169:8b2a...
* TCP_NODELAY set
* Immediate connect fail for 2002:7169:8b2a::7169:8b2a: No route to host
*   Trying 2001:470:1f07:124::3...
* TCP_NODELAY set
* Immediate connect fail for 2001:470:1f07:124::3: No route to host
*   Trying 2001:41d0:1004:3274::...
* TCP_NODELAY set
* Immediate connect fail for 2001:41d0:1004:3274::: No route to host
*   Trying 2001:470:1f10:776::2...
* TCP_NODELAY set
* Immediate connect fail for 2001:470:1f10:776::2: No route to host
*   Trying 2001:470:1f14:57a::2...
* TCP_NODELAY set
* Immediate connect fail for 2001:470:1f14:57a::2: No route to host
*   Trying 2001:470:1f15:1b95:2c3e:8a9a:24e1:7084...
* TCP_NODELAY set
* Immediate connect fail for 2001:470:1f15:1b95:2c3e:8a9a:24e1:7084: No route to host
*   Trying 2001:200::8801:5054:ff:fe32:e5be...
* TCP_NODELAY set
* Immediate connect fail for 2001:200::8801:5054:ff:fe32:e5be: No route to host
* Connection failed
* connect to 144.76.99.209 port 80 failed: Connection refused
*   Trying 97.107.131.168...
* TCP_NODELAY set
* Connected to seed.bitcoin.sprovoost.nl (97.107.131.168) port 80 (#0)
> GET / HTTP/1.1
> Host: seed.bitcoin.sprovoost.nl
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 302 Found
< Date: Wed, 20 Dec 2017 19:22:08 GMT
< Server: Apache/2.4.7 (Ubuntu)
< X-Powered-By: PHP/5.5.9-1ubuntu4.22
< Location: http://www.uroulette.com/visit/utvtw
< Content-Length: 0
< Content-Type: text/html
```

**Comment by Sjors** [comment]
`curl` will show you a random website every time you try. Probably because it encounters an A record and just follows the trail, to whatever web server happens to be running on the node machine.

`nmap` gets tripped up in a similar way.

**Comment by akx20000a** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/11962/commits/ab8b18342d9d08d7eab8c64a5b1802150ebb9e95

**Review by ghost — APPROVED** [review]

**Comment by fanquake** [comment]
Needs a rebase.

**Comment by Sjors** [comment]
Rebased

**Comment by laanwj** [comment]
I've checked that the DNS seed returns connectable hosts.

> Criticism of my security setup is certainly

FWIW I was not able to find an open SSH port on port 22, nor any other open low/well-known port. Due to this, nmap was unable to even do OS detection.

**Comment by laanwj** [comment]
Can we please have another ACK here maybe @sipa @gmaxwell

**Comment by sipa** [comment]
ACK

**Comment by cdecker** [comment]
ACK

Tested the quality of the results returned by the seed 3 times. The results show how many of the returned nodes are reachable: 15/22, 20/22, and 21/22. Pretty much average with the other seeds.

**Pull request merged**
