### PR TITLE
rpc: Faster getblock using PureBlock

### PR DESCRIPTION
**Pull request by maflcko**
This adds and uses a new transaction type `PureTransaction`.
The underlying class has no transaction hash compiled in. So
it is safe to use (and faster) wherever it compiles.
    
The existing CMutableTransaction retains the behavior to calculate the
tx hash on demand. Use of CMutableTransaction makes compile-time
complexity analysis impossible.
    
The existing CTransaction retains the behavior to cache the hash on
initialization.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
So I did some measurements: While this is a clear performance win, it seems the performance is dominated by shuffling the data around multiple times:

Before:
`disk -> deserialize -> hash -> serialize -> hex string -> json`

After:
`disk -> deserialize ->      -> serialize -> hex string -> json`

Hashing takes 10%-25% on intel CPUs. Didn't try arm.

master:
Screenshot from 2019-11-20 10-47-50



faaa142412:

Screenshot from 2019-11-20 11-01-35

**Comment by MarcoFalke** [comment]
I guess it would be smarter to see if the rpc serialization flags are matching the ones of the block on disk and then just serve it raw. See #13151

**Comment by laanwj** [comment]
> I guess it would be smarter to see if the rpc serialization flags are matching the ones of the block on disk and then just serve it raw. See #13151

If so, it would definitely be a simpler/smaller change!

**Comment by achow101** [comment]
Closing this as it has not had any activity in a while. If you are interested in continuing work on this, please leave a comment so that it can be reopened.

**Comment by a1love-web** [comment]
> This adds and uses a new transaction type `PureTransaction`. The underlying class has no transaction hash compiled in. So it is safe to use (and faster) wherever it compiles.
> 
> The existing CMutableTransaction retains the behavior to calculate the tx hash on demand. Use of CMutableTransaction makes compile-time complexity analysis impossible.
> 
> The existing CTransaction retains the behavior to cache the hash on initialization.

**Pull request closed without merging**
