### PR TITLE
build: Add -Werror=unused... compile flags

### PR DESCRIPTION
**Pull request by hebasto**
With C++17 `[[maybe_unused]]` attribute it is easy to keep emerged cases in the new code under control.

This PR does not touch `-Wno-unused-parameter` as it requires too much of code churning.

---

Compiler specific notes:
1. clang:
  - `-Wunused-macros` not added because it requires a non-trivial checking in the `configure` script, and it blames only https://github.com/bitcoin/bitcoin/blob/a9d1b40d53ec417eefbe767aa66701ef8e1801d5/src/util/system.cpp#L34
  - `-Wunused-template` not added because some of our templates are buried into macros
  - `-Wused-but-marked-unused` produces tones of warnings in boost tests
2. gcc
  - `-Werror=unused-const-variable` with level 2 seems not suitable for C++ code

### CODE REVIEW

**Comment by practicalswift** [comment]
Concept ACK, but why the removal of `-Werror=unused-variable`? :)

Could you describe some tests cases that could be used to verify that the patch in this PR makes the build fail where we expect it to fail?

**Comment by hebasto** [comment]
Rebased 22dd4fbf5d123976b2b23860188115cbea036cbd -> 424683d349dd9a748b324b74a58e034abd76a33e ([pr21458.01](https://github.com/hebasto/bitcoin/commits/pr21458.01) -> [pr21458.02](https://github.com/hebasto/bitcoin/commits/pr21458.02)).

**Review by fanquake — COMMENTED** [review]
~0. I'm not super convinced about the addition of (post rebase, and without `-Wunused`) two, specific `-Wunused-*` flags. See also #23269 where I've cherry-picked 33a3554cbb30657b9af34802dd610b286aa71a56.

**Comment by fanquake** [comment]
This needs a rebase, and comments addressed, or can probably be closed.

**Pull request closed without merging**
