### PR TITLE
Do not shadow in src/qt

### PR DESCRIPTION
**Pull request by paveljanik**
As requested by @laanwj in #8105, Qt shadowing changes all-in-one.

Maintainers allowed to edit.

### CODE REVIEW

**Comment by laanwj** [comment]
Awesome, will check.

**Comment by paveljanik** [comment]
Please note that many places could be rewritten to use member initializers. And on many places, the diff can be shortened by rewriting initialization process, simplifying `this->` stuff and co. But this was not the goal here...

**Comment by laanwj** [comment]
Right, the goal is easy review and checking, as well as being able to enable those warnings after this.

**Review by laanwj — APPROVED** [review]
Binaries match

```
f1916a25418f7a2dac48f142fb56466e6c2d68197f8f1787b68317c1ec62d281  /tmp/compare/bitcoind.26b370a
dff7a8d163c1543fe4044b1bc2e70af1d4fa3d3bc2b8b9ded0635b312c7d1534  /tmp/compare/bitcoind.26b370a.stripped
f1916a25418f7a2dac48f142fb56466e6c2d68197f8f1787b68317c1ec62d281  /tmp/compare/bitcoind.eec927e
dff7a8d163c1543fe4044b1bc2e70af1d4fa3d3bc2b8b9ded0635b312c7d1534  /tmp/compare/bitcoind.eec927e.stripped
```

**Comment by laanwj** [comment]
Eh, oops I checked the bitcoind binary while this relates to bitcoin-qt, need to recheck.
Ignore the above approval for now (I don't think I can delete it).

**Comment by laanwj** [comment]
My binary comparator finds differences in the following functions:
```
0000000000000000 <BitcoinGUI::BitcoinGUI(PlatformStyle const*, NetworkStyle const*, QWidget*)>:
0000000000000000 <EditAddressDialog::EditAddressDialog(EditAddressDialog::Mode, QWidget*)>:
0000000000000000 <WalletView::setClientModel(ClientModel*)>:
0000000000000000 <WalletView::setClientModel(ClientModel*)>:
0000000000000000 <AskPassphraseDialog::AskPassphraseDialog(AskPassphraseDialog::Mode, QWidget*)>:
0000000000000000 <AddressTableModel::AddressTableModel(CWallet*, WalletModel*)>:
0000000000000000 <WalletView::setWalletModel(WalletModel*)>:
0000000000000000 <SignVerifyMessageDialog::SignVerifyMessageDialog(PlatformStyle const*, QWidget*)>:
0000000000000000 <AddressBookPage::AddressBookPage(PlatformStyle const*, AddressBookPage::Mode, AddressBookPage::Tabs, QWidget*)>:
0000000000000000 <PlatformStyle::PlatformStyle(QString const&, bool, bool, bool)>:
0000000000000000 <SendCoinsEntry::SendCoinsEntry(PlatformStyle const*, QWidget*)>:
0000000000000000 <RPCConsole::RPCConsole(PlatformStyle const*, QWidget*)>:
```
This is pretty much every changed function, but especially constructors. I don't see why, it may have something to do with Qt's moc generating different metadata?

ut/code review ACK though

**Comment by MarcoFalke** [comment]
Would be interesting to know why the binaries don't match for qt. Encountered the same here: https://github.com/bitcoin/bitcoin/pull/8658#issuecomment-246030102

**Comment by paveljanik** [comment]
The difference cause by this PR is probably different from the difference caused by #8658.

In this PR, the change in https://github.com/bitcoin/bitcoin/pull/8793/commits/46b15bb509ac9b4212ed40b12098d1842c878424 illustrates the reason. Technically it does the same, but compiler has two places where to get the value used (member variable initialized from the argument or the argument itself).

**Comment by laanwj** [comment]
@MarcoFalke yes we figured it out on IRC: it has to do with name binding, using the argument versus member variable it was assigned to. For example this seems to make the differences in AddressBookPage::AddressBookPage go away: http://www.hastebin.com/jixoyufuxu.php .

But that's kind of ugly. So in this case I prefer slightly different executables to larger source code patch that makes the code uglier. If it was consensus code it'd be different.

**Comment by laanwj** [comment]
Squashed the squashme commit.

**Pull request merged**
