### PR TITLE
qt: Add missing QPainterPath include

### PR DESCRIPTION
**Pull request by achow101**
This is needed to compile with Qt 5.15.

### CODE REVIEW

**Comment by laanwj** [comment]
Code review ACK 79b0a69e09c1a912122e6431ea3c530cc292c690

**Comment by MarcoFalke** [comment]
Code review ACK 79b0a69

**Comment by promag** [comment]
Code review ACK 79b0a69e09c1a912122e6431ea3c530cc292c690.

nit, could also forward declare in src/qt/trafficgraphwidget.h.

**Comment by vahidjalaliii** [comment]
79b0a69

**Comment by puchu** [comment]
> Code review ACK [79b0a69](https://github.com/bitcoin/bitcoin/commit/79b0a69e09c1a912122e6431ea3c530cc292c690).
> 
> nit, could also forward declare in src/qt/trafficgraphwidget.h.

should be in the h file as it's already used there

**Comment by promag** [comment]
Definition isn't necessary in the header, forward declaration is enough.

**Comment by puchu** [comment]
but what's the benefit, instead of directly including it in the h file?

**Comment by promag** [comment]
It's usually best practice to just include an header when the definition is required to minimize the compiler work.

**Comment by puchu** [comment]
makes sense

**Pull request merged**
