### PR TITLE
Docs: Bump OS X version to 10.13

### PR DESCRIPTION
**Pull request by Varunram**
Core works fine on macOS 10.13

### CODE REVIEW

**Comment by fanquake** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/11793/commits/3bc167bb1a6dc8a09c08d9db92b37021fbc6199e

**Comment by laanwj** [comment]
Sorry to be pedantic, but this is the build guide: does it also build fine on 10.13?

**Comment by Varunram** [comment]
Totally understand, I should've been clearer - It builds and works fine on macOS 10.13.

**Comment by laanwj** [comment]
utACK 543ab40a44d32cccbdc309fe184660f726c034d2

**Pull request merged**
