### PR TITLE
Change Luke Dashjr seed to dashjr-list-of-p2p-nodes.us

### PR DESCRIPTION
**Pull request by luke-jr**
To avoid issues with DNS blacklisting, I've setup a separate domain for my DNS seed.

(This time, without a potentially alarming name)

### CODE REVIEW

**Comment by Sjors** [comment]
Concept ACK, seems like a fine name. Haven't tested yet.

**Comment by kevkevinpal** [comment]
Concept ACK [4f273ab](https://github.com/bitcoin/bitcoin/pull/29691/commits/4f273ab4360c9aa72c2feb78787e1811ab58dc16), name looks good to me

**Comment by petertodd** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/29691/commits/4f273ab4360c9aa72c2feb78787e1811ab58dc16

DNS seems to resolve just fine for me, and returns IP addresses with a fair bit of overlap with the ones my DNS seed has.

**Comment by Sjors** [comment]
@luke-jr can you GPG sign this commit?

Someone, possibly you, should also make a PR to update it here: https://github.com/bitcoin-core/bitcoin-maintainer-tools/blob/main/check-dnsseeds.py (better still if it just parses `src/kernel/chainparams.cpp`).

I ran the above script locally and it's happy.

**Review by mzumsande — COMMENTED** [review]
ACK 4f273ab4360c9aa72c2feb78787e1811ab58dc16

I did a quick check that it returns valid addresses under the new domain.

**Review by fanquake — APPROVED** [review]
ACK 4f273ab4360c9aa72c2feb78787e1811ab58dc16

> Someone, possibly you, should also make a PR to update it here:

I don't see why the person making the PR there matters; it's only copying what is in `kernel/chainparams`. Opened one for recent changes: https://github.com/bitcoin-core/bitcoin-maintainer-tools/pull/160

**Pull request merged**
