### PR TITLE
rpc: Update named args documentation for importprivkey

### PR DESCRIPTION
**Pull request by dusty-wil**
Addresses issue #11462 by updating the documentation for the importprivkey arguments to the correct names, and updates the functional test importprunedfunds.py to use named arguments when calling importprivkey.

### CODE REVIEW

**Comment by promag** [comment]
IMO remove 2nd commit.

**Comment by MarcoFalke** [comment]
why?

**Comment by MarcoFalke** [comment]
@promag It nicely proves that the documentation now matches the named args

**Comment by promag** [comment]
The first commit does what the PR title states. No need to change the test to use named arguments. This is obviously my opinion!

**Comment by promag** [comment]
No, the test does not prove that, to prove that we should assert the documentation string.

Again consider my comment above a nit.

**Comment by promag** [comment]
There must be a test to assert argument order too :) (although that is probably in other tests).

**Comment by dusty-wil** [comment]
@MarcoFalke @promag I can remove the second commit if you'd prefer! Is there a neat way to do that through github or do I need to re-commit with the changes?

**Comment by promag** [comment]
For reference, this was missed in #8811 (9adb4e1).

@dusty-wil to remove the commit you must push again. But do not remove it now, wait for more comments.

**Comment by MarcoFalke** [comment]
I think squashing makes the most sense. See here: https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#squashing-commits

**Comment by dusty-wil** [comment]
@MarcoFalke ok, squashed!

**Comment by laanwj** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/11465/commits/aa57590d7c5eab1df5443e8ac9ed53ad0db46c02

**Comment by fanquake** [comment]
utACK aa57590

**Comment by MarcoFalke** [comment]
utACK aa57590

**Comment by dusty-wil** [comment]
Thanks for the opportunity to contribute!

**Pull request merged**
