### PR TITLE
Switch to NSIS 3.03 to avoid DLL hijacking

### PR DESCRIPTION
**Pull request by h4x3rotab**
Early version of NSIS searches its DLL from the same directory of the executable. If a hacker can place some DLL files in the same directory of the bitcoin installer, the installer will load and run it with admin permission.

Gitian is still in trusty. It shipped with NSIS 2.46, which is vulnerable to this issue. So in this fix, we instead build the latest NSIS by Gitian.

Thanks to @wilsonmeier from Bitcoin Gold team for the fix. Borrowed some code from TOR project.

Details: https://trac.torproject.org/projects/tor/ticket/17895

### CODE REVIEW

**Comment by laanwj** [comment]
Thanks,
The idea was to switch to Ubuntu 18.04 for building to avoid having to do this, as that ships with a newer NSIS package, but if that turns out not to be feasible before the next release this will be helpful!

**Comment by MarcoFalke** [comment]
>  if that turns out not to be feasible before the next release this will be helpful!

Currently our Windows gitian cross builds are broken, so we'd *have* to switch to bionic. (Or revert the qt depends bump)

**Comment by ken2812221** [comment]
This has been fixed in nsis 2.50, and nsis in ubuntu bionic is version 2.51.

**Comment by h4x3rotab** [comment]
> This has been fixed in nsis 2.50, and nsis in ubuntu bionic is version 2.51.
Yeah, bionic could be even better.

**Comment by theuni** [comment]
Holding out on reviewing this until after #13171 is merged or closed.

**Comment by akx20000a** [comment]
Bitcoin Gold developer contributing for Bitcoin Core, nice 👍

**Comment by MarcoFalke** [comment]
Closing per https://github.com/bitcoin/bitcoin/pull/13643#issuecomment-404534659

**Pull request closed without merging**
