### PR TITLE
[travis] Exit early when check-doc.py fails

### PR DESCRIPTION
**Pull request by maflcko**
Discussed on IRC

### CODE REVIEW

**Comment by laanwj** [comment]
Concept ACK.

Can we test this by making a dummy change and see if travis fails, and how it looks now?

**Comment by MarcoFalke** [comment]
dummy change: https://travis-ci.org/bitcoin/bitcoin/builds/106296202

TBH, I don't like the `set -e` workaround, as the travis build will not exit cleanly. It doesn't matter with the current `.travis.yml` but it may in the future and it is not considered best practice.

**Comment by laanwj** [comment]
@theuni any ideas here? We want to terminate the test prematurely if the doc check fails, to avoid wasting resources, is there a nicer way to do this then `set -e` or `exit`?

**Comment by MarcoFalke** [comment]
@laanwj You could "remember" the exit code and branch subsequent statements/lines but this is a somewhat larger diff, I guess.

**Comment by MarcoFalke** [comment]
@laanwj The first commit should be uncontroversial and improve things considerably without making anything worse. Would you mind if I create a new pull for this commit?

**Comment by laanwj** [comment]
As this is a testing/build system related pull, I'd just like @theuni to take a look at it. If he's ok with it we'll just merge.

**Comment by theuni** [comment]
@MarcoFalke I think it'd do what you wanted if you just bumped it up into before_script. Then you wouldn't have to worry about forcing an exit, as before_script errors the build on any non-zero return.

**Comment by theuni** [comment]
other than that, ACK.

**Comment by MarcoFalke** [comment]
Thanks for letting me know. This is indeed working: https://travis-ci.org/bitcoin/bitcoin/jobs/113383026

**Pull request merged**
