### PR TITLE
wallet: Use wallet name instead of pointer on unload/release

### LINKED ISSUE #16668: Lifetime issue in ReleaseWallet(CWallet* wallet)
While checking #16661 I stumbled upon what seems to be a lifetime issue in `ReleaseWallet(CWallet* wallet)` (`wallet.cpp`).

https://github.com/bitcoin/bitcoin/blob/fa6431055abfacea4f72ef11d061c7c755de327a/src/wallet/wallet.cpp#L107-L111

After `delete wallet;` the pointer is invalid and shouldn't be used like in the call `g_unloading_wallet_set.erase(wallet)`.

The code was introduced in #14941 which was merged into `master` on January 15, 2019.

In addition to fixing this specific instance it might be worth thinking about how we can use static analysis to automatically catch this class of issues going forward :-)

### PR DESCRIPTION
**Pull request by promag**
Fixes #16668. Wallet name is unique so it can be used instead of pointer.

### CODE REVIEW

**Comment by practicalswift** [comment]
Concept ACK

Thanks for fixing this.

**Review by ryanofsky — APPROVED** [review]
utACK d9d8984270dbb004ec94f8dbb289be2bc9e4dbc3. Alternately I think it might be possible to use an intptr_t set instead of a string set to get around the undefined behavior described in the issue.

Aside from the undefined behavior, I'm not sure the either the existing code or the new code is safe from race conditions where between `delete wallet` and `g_unloading_wallet_set.erase` another wallet object (possibly the same wallet) is loaded and unloaded, resulting in the `assert` after `g_unloading_wallet_set.insert` triggering, or causing `UnloadWallet` to return too early before a wallet was unloaded. Replacing the `set` with a `map` to refcounts might fix this, though at that point it might be worth moving away from shared_ptr and using another mechanism to delay unloading a wallet while it's being used by RPCs.

**Comment by meshcollider** [comment]
utACK d9d8984270dbb004ec94f8dbb289be2bc9e4dbc3

**Comment by promag** [comment]
> Alternately I think it might be possible to use an intptr_t

@ryanofsky I don't think, see https://stackoverflow.com/a/9492910.

> another wallet object (possibly the same wallet) is loaded and unloaded

I also think that wouldn't be possible:

https://github.com/bitcoin/bitcoin/blob/a7be1cc92be4946c4f042bccd3a1b007657f3241/src/wallet/rpcwallet.cpp#L2757-L2764

> moving away from shared_ptr

What's the problem with shared_ptr?

Anyway we could fail to unload if wallet is busy - meaning that the caller wouldn't block.

**Comment by instagibbs** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/16716/commits/d9d8984270dbb004ec94f8dbb289be2bc9e4dbc3

**Pull request merged**
