### PR TITLE
[0.12.1] Fix doc and output for rpcauth

### PR DESCRIPTION
**Pull request by maflcko**
This is already in `master` (#7617), but still would be good to have in 0.12.1 as well.

(Cleanup of #7044)

### CODE REVIEW

**Comment by jonasschnelli** [comment]
ACK fa48d993aed855dc08c986f80da684cc69a8167d

**Comment by paveljanik** [comment]
Changes are OK. Isn't it better for the log/change tracking to cherry-pick the changes instead?

**Comment by laanwj** [comment]
> Changes are OK. Isn't it better for the log/change tracking to cherry-pick the changes instead?

Yes, I don't think this warrants another pull request. That's more apt when there are non-trivial changes.

**Comment by laanwj** [comment]
See f04f4fd2eed581a5e287d14036d790cf2badcbe6

**Pull request closed without merging**
