### PR TITLE
[arith_uint256] Make it safe to use "self" in operators

### PR DESCRIPTION
**Pull request by kallewoof**
Before this fix (see test commit), `v *= v` would result in `0` because `operator*=` set `*this` (`==b`) to `0` at the start. This patch changes the code to use `a` as temporary for `*this`~~, with drawback that `*this` is set to `a` at the end, an extra `=` operation in other words~~.

### CODE REVIEW

**Comment by practicalswift** [comment]
utACK ac68e6d7176c1b24a69559afd1a66b2d04c67dc6

**Review by khalifa4 — APPROVED** [review]

**Comment by ajtowns** [comment]
Removed code invokes copy-constructor, and `operator=(uint64_t)`; new code invokes default-constructor and `operator=(base_uint)`. So doesn't seem like an extra `=` operation to me?

Shouldn't the fix be committed first, then the tests? Or is having an intermediate commit where the tests fail ok? Looks good to me otherwise though.

**Comment by kallewoof** [comment]
@ajtowns I kinda wanted to demonstrate that it fails up until that point, which is why I put the tests before the fix. And yeah, you're right, I forgot I removed one `operator=` so it should be `+/- 0`. :)

**Comment by ajtowns** [comment]
@kallewoof I like the idea of demonstrating the test fails before the fix, but still not convinced having the test actually fail (which could mess up attempts to use `git bisect` later, eg) is great. How about:

```
-BOOST_AUTO_TEST_CASE( operator_with_self )
+BOOST_AUTO_TEST_CASE( operator_with_self,
+               *boost::unit_test::expected_failures(1) )
 {
     arith_uint256 v = UintToArith256(uint256S("02"));
-    v *= v;
-    BOOST_CHECK(v == UintToArith256(uint256S("04")));
     v /= v;
     BOOST_CHECK(v == UintToArith256(uint256S("01")));
     v += v;
     BOOST_CHECK(v == UintToArith256(uint256S("02")));
+    v *= v;
+    BOOST_CHECK(v == UintToArith256(uint256S("04")));
     v -= v;
     BOOST_CHECK(v == UintToArith256(uint256S("0")));
 }
```

which results in:

```
$ ./test_bitcoin
Running 276 test cases...
test/uint256_tests.cpp(278): error: in "uint256_tests/operator_with_self": check v == UintToArith256(uint256S("04")) has failed

*** No errors detected
```

(rearrangement was necessary to avoid the bug causing `v /= v` to give a division by zero)

ie: commit 1: introduce failing test, but mark it as expected to fail; commit 2: fix bug, and remove expected-to-fail marker? I might be overthinking it, so please take this as a suggestion, not a blocker. ACK ac68e6d7176c1b24a69559afd1a66b2d04c67dc6

**Comment by promag** [comment]
I'm also -0 in having broken commits. How about https://docs.travis-ci.com/user/customizing-the-build/#Skipping-a-build?

**Comment by Empact** [comment]
Yeah I would just squash the test and fix commits together, it's clear enough how they're related.

**Comment by kallewoof** [comment]
The bisect thing makes sense yeah. I swapped the order so the fix comes before the tests.

**Comment by practicalswift** [comment]
utACK b120f7bdbee83c00e46a9ec6d0cd09a816631f45

**Comment by laanwj** [comment]
> with drawback that *this is set to a at the end, an extra = operation in other words.

Could be extra copying be conditional on `a` being equal to self?

I don't think we rely on the performance of this function in any inner loop, but much of a performance hit are we going to take for functionality that isn't used in the code base?

An alternative would be to add an assert to forbid this usage.

**Comment by kallewoof** [comment]
@laanwj Actually, it turns out this is +/- 0, because I remove `*this = 0` at the top, so it shouldn't cause a performance drop at all.

**Comment by laanwj** [comment]
Ok, seems better than preventing it then, utACK https://github.com/bitcoin/bitcoin/commit/b120f7bdbee83c00e46a9ec6d0cd09a816631f45.

**Comment by ken2812221** [comment]
utACK b120f7b

**Pull request merged**
