### PR TITLE
doc: mention bech32m/BIP350 in doc/descriptors.md

### PR DESCRIPTION
**Pull request by sipa**
As it says on the tin.

### CODE REVIEW

**Comment by sipa** [comment]
This may make sense for backport, but is extremely low priority.

**Review by fanquake — APPROVED** [review]
ACK d2a09c83554cec864a27e704cf2a0d513691a567 - can be backported for coherent documentation. Bech32m support was backported into branches back to the 0.19.

**Comment by 0xB10C** [comment]
ACK d2a09c83554cec864a27e704cf2a0d513691a567

**Comment by fanquake** [comment]
Backported to 22.x in #22857.

**Comment by fanquake** [comment]
Backported to 0.21 in #22858.

**Comment by fanquake** [comment]
Backported to 0.20 in #22900.

**Pull request merged**
