### PR TITLE
[Tests] Make combine_logs.py handle multi-line logs

### PR DESCRIPTION
**Pull request by jnewbery**
combine_logs.py currently inserts additional newlines into multi-line
log messages, and doesn't color them properly. Fix both of those.

### CODE REVIEW

**Comment by laanwj** [comment]
I've fixed this once as well in the past but never got to submitting a PR
Thanks!

utACK 995dd89d884bda3fb5ca1885c5887d989cd2cad3

**Comment by laanwj** [comment]
Tried to test, but it doesn't work as expected:

output of `test/functional/feature_rbf.py --nocleanup`
then `test/functional/combine_logs.py /tmp/testpdobtlfa`

before:
```
 node0 
2018-04-25T09:45:43Z 

2018-04-25T09:45:43Z Bitcoin Core version v0.16.99.0-7192b8f (release build)

2018-04-25T09:45:43Z InitParameterInteraction: parameter interaction: -bind set -> setting -listen=1

2018-04-25T09:45:43Z InitParameterInteraction: parameter interaction: -whitelistforcerelay=1 -> setting -whitelistrelay=1

2018-04-25T09:45:43Z Validating signatures for all blocks.

2018-04-25T09:45:43Z Setting nMinimumChainWork=0000000000000000000000000000000000000000000000000000000000000000

2018-04-25T09:45:43Z Using the 'standard' SHA256 implementation

2018-04-25T09:45:43Z Default data directory /home/orion/.bitcoin

2018-04-25T09:45:43Z Using data directory /store/orion/projects/bitcoin/bitcoin/test/cache/node0/regtest

2018-04-25T09:45:43Z Using config file /store/orion/projects/bitcoin/bitcoin/test/cache/node0/bitcoin.conf

2018-04-25T09:45:43Z Using at most 125 automatic connections (1024 file descriptors available)

2018-04-25T09:45:44Z Using 16 MiB out of 32/2 requested for signature cache, able to store 524288 elements

2018-04-25T09:45:44Z Using 16 MiB out of 32/2 requested for script execution cache, able to store 524288 elements

2018-04-25T09:45:44Z Using 6 threads for script verification

2018-04-25T09:45:44Z scheduler thread start

2018-04-25T09:45:44Z HTTP: creating work queue of depth 16
```

after:
```
 node0                                    2018-04-25T09:45:43Z  
                                   2018-04-25T09:45:43Z Bitcoin Core version v0.16.99.0-7192b8f (release build)
                                   2018-04-25T09:45:43Z InitParameterInteraction: parameter interaction: -bind set -> setting -listen=1
                                   2018-04-25T09:45:43Z InitParameterInteraction: parameter interaction: -whitelistforcerelay=1 -> setting -whitelistrelay=1
                                   2018-04-25T09:45:43Z Validating signatures for all blocks.
                                   2018-04-25T09:45:43Z Setting nMinimumChainWork=0000000000000000000000000000000000000000000000000000000000000000
                                   2018-04-25T09:45:43Z Using the 'standard' SHA256 implementation
                                   2018-04-25T09:45:43Z Default data directory /home/orion/.bitcoin
                                   2018-04-25T09:45:43Z Using data directory /store/orion/projects/bitcoin/bitcoin/test/cache/node0/regtest
                                   2018-04-25T09:45:43Z Using config file /store/orion/projects/bitcoin/bitcoin/test/cache/node0/bitcoin.conf
                                   2018-04-25T09:45:43Z Using at most 125 automatic connections (1024 file descriptors available)
                                   2018-04-25T09:45:44Z Using 16 MiB out of 32/2 requested for signature cache, able to store 524288 elements
```

both before and after don't really make sense, or am I doing something wrong?

**Comment by jnewbery** [comment]
@laanwj - your logs aren't using microseconds, although that should be set here:

https://github.com/bitcoin/bitcoin/blob/fea4e9eca58b6ef69b413a5fa8efb5388c405fdd/test/functional/test_framework/test_node.py#L79

I wonder if you're using an ancient cache from before microseconds were being used. Can you delete the /test/cache directory and try again?

I've added an extra commit that handles timestamps without microseconds.

**Comment by laanwj** [comment]
> I've added an extra commit that handles timestamps without microseconds.

huh I also remember doing that before, have a very strong deja-vu here :)

will re-test, thanks!

**Pull request merged**
