### PR TITLE
configure: bitcoin-tx doesn't need libevent, so don't pull it in

### PR DESCRIPTION
**Pull request by luke-jr**

### CODE REVIEW

**Comment by promag** [comment]
Concept ACK.

**Comment by kristapsk** [comment]
utACK 8ac34140d53e0b7a0cabfc045cd1c6dd16824cf9

**Review by jgarzik — APPROVED** [review]
ut ACK

**Comment by ken2812221** [comment]
utACK 8ac34140d53e0b7a0cabfc045cd1c6dd16824cf9

**Pull request merged**
