### PR TITLE
build: Bump Qt to 5.15.5 in depends

### PR DESCRIPTION
**Pull request by hebasto**
Bumping Qt patch version allows to drop the `fix_limits_header.patch`.

Guix builds on `x86_64`:
```
6e403f6442f904a17e00f2c5d539c38a6d736963deaca080aaf7e45911f32cd4  guix-build-fd0e8df67cae/output/aarch64-linux-gnu/SHA256SUMS.part
9faf7c7eba364848ab59f78d68a7ef74fc96c1d4b64c9132c8cdeaa3e90dd11c  guix-build-fd0e8df67cae/output/aarch64-linux-gnu/bitcoin-fd0e8df67cae-aarch64-linux-gnu-debug.tar.gz
5a6a63c1e81f088db952ddd5184f673583cbce122de8a5714ba313064ac4536d  guix-build-fd0e8df67cae/output/aarch64-linux-gnu/bitcoin-fd0e8df67cae-aarch64-linux-gnu.tar.gz
d1f0d94a0996d268a498fce2080a456544ccd60c263eb25c6bb335570ee0e181  guix-build-fd0e8df67cae/output/arm-linux-gnueabihf/SHA256SUMS.part
ec89d624ec30f0117e435ff31fe3431c15eb0ef2c31fc33f7a1c6b71d8af1166  guix-build-fd0e8df67cae/output/arm-linux-gnueabihf/bitcoin-fd0e8df67cae-arm-linux-gnueabihf-debug.tar.gz
71521ee2e382bb3b1e85db0e702cb3d91a6c713f290cb3835f6e6a6ff65de22b  guix-build-fd0e8df67cae/output/arm-linux-gnueabihf/bitcoin-fd0e8df67cae-arm-linux-gnueabihf.tar.gz
e757341c8000cdc74b266217bd1bc3ec2fa4d0a53270cef4fe18182010dde213  guix-build-fd0e8df67cae/output/arm64-apple-darwin/SHA256SUMS.part
a361215f99ef2e10decc2c97ad5aea62e268554101cd34a75a28a0f8cc25bc4d  guix-build-fd0e8df67cae/output/arm64-apple-darwin/bitcoin-fd0e8df67cae-arm64-apple-darwin-unsigned.dmg
81b91ab355544d247c2781bf2e323a70c27780665c3098d8ef01a59d291725f6  guix-build-fd0e8df67cae/output/arm64-apple-darwin/bitcoin-fd0e8df67cae-arm64-apple-darwin-unsigned.tar.gz
0b4e6ae2c66ecf49b2223d8d7fabd00765942ffeb4972fd699e4a9d13f176b6b  guix-build-fd0e8df67cae/output/arm64-apple-darwin/bitcoin-fd0e8df67cae-arm64-apple-darwin.tar.gz
94f4a4a319a896c1ce37980fdac0c6bf9b62e2a8ca46476a10895a4fd8d0403f  guix-build-fd0e8df67cae/output/dist-archive/bitcoin-fd0e8df67cae.tar.gz
cf963b63fabc7e832b9469c9c048b08dcee344cb2044e7930bca53dfdc18c3dd  guix-build-fd0e8df67cae/output/powerpc64-linux-gnu/SHA256SUMS.part
50ac40337bed023900ecf1bd3f557276dba8d97cd613f9342e0f7a72e4c7e6f1  guix-build-fd0e8df67cae/output/powerpc64-linux-gnu/bitcoin-fd0e8df67cae-powerpc64-linux-gnu-debug.tar.gz
6884eba5928b831434ae9a1e5c2945185d1e6f013537aac0a05ae9775ab1df7d  guix-build-fd0e8df67cae/output/powerpc64-linux-gnu/bitcoin-fd0e8df67cae-powerpc64-linux-gnu.tar.gz
ad502cdbf072a3875f4cbf653e9b5593c5f5324edc0e38100234a9778a73cc09  guix-build-fd0e8df67cae/output/powerpc64le-linux-gnu/SHA256SUMS.part
e426a8f45095bc6019612a58f60267f6b084e3c273ec70509a0a8759e90e68d2  guix-build-fd0e8df67cae/output/powerpc64le-linux-gnu/bitcoin-fd0e8df67cae-powerpc64le-linux-gnu-debug.tar.gz
a68ec3ba7e63382dc44f99806badc62e660dd3ae2d9d74d48e7e8378fd5c03f4  guix-build-fd0e8df67cae/output/powerpc64le-linux-gnu/bitcoin-fd0e8df67cae-powerpc64le-linux-gnu.tar.gz
67d0bf587538fb151aa867363ab7724543607adda2b8be7dffbc263959e02f67  guix-build-fd0e8df67cae/output/riscv64-linux-gnu/SHA256SUMS.part
093c874104e8f8c7bd73c362be471aba6d0c25828c22b2a8324056d516849242  guix-build-fd0e8df67cae/output/riscv64-linux-gnu/bitcoin-fd0e8df67cae-riscv64-linux-gnu-debug.tar.gz
82b03ba2283a8667ea3c3fa86a5f64be7c7a4c0423b92bd8f3dfe71a78c3b210  guix-build-fd0e8df67cae/output/riscv64-linux-gnu/bitcoin-fd0e8df67cae-riscv64-linux-gnu.tar.gz
5a30433c33322b9deabe4d6fc655f6dd9e6e73f2ae09b01502ce1a9377e1ce16  guix-build-fd0e8df67cae/output/x86_64-apple-darwin/SHA256SUMS.part
473a3df8d63a112ca3e76620a56f6a5781b74c594451c86c26ccfef63cc2b023  guix-build-fd0e8df67cae/output/x86_64-apple-darwin/bitcoin-fd0e8df67cae-x86_64-apple-darwin-unsigned.dmg
fa0eb43787745d6973ceb880003acf9f5be6e14c5c310bcc359a05cb52dd20a8  guix-build-fd0e8df67cae/output/x86_64-apple-darwin/bitcoin-fd0e8df67cae-x86_64-apple-darwin-unsigned.tar.gz
90ccac950577f15e5dc729e9f94bff39fa0a9f0a96a27eee249df15a604eec44  guix-build-fd0e8df67cae/output/x86_64-apple-darwin/bitcoin-fd0e8df67cae-x86_64-apple-darwin.tar.gz
fffda44e37d74908fcb5974a7c290d4e36d457605824f5d3f79b15e4eae5c1e7  guix-build-fd0e8df67cae/output/x86_64-linux-gnu/SHA256SUMS.part
7d807b88d20a759236013fec99d8b16240dc064a0a5a6eb5d51ba02af467d959  guix-build-fd0e8df67cae/output/x86_64-linux-gnu/bitcoin-fd0e8df67cae-x86_64-linux-gnu-debug.tar.gz
8141de0e3aa4174dea1e1cc3ee6344e857650fdd3180e7a4e8359f84733933fe  guix-build-fd0e8df67cae/output/x86_64-linux-gnu/bitcoin-fd0e8df67cae-x86_64-linux-gnu.tar.gz
653b6c61d4ab5c5dcb8f36aefb518dc14d7fcf9f7d684a521c7705cbda9ff2fe  guix-build-fd0e8df67cae/output/x86_64-w64-mingw32/SHA256SUMS.part
999dc6af5a7262c579be1c9904c1ac2deff0617a48d89d60902de5ba9e3684e6  guix-build-fd0e8df67cae/output/x86_64-w64-mingw32/bitcoin-fd0e8df67cae-win64-debug.zip
03a90e2d6191b6ab84ffb38f845e0565ecf34b5d3b34b7fc36edc99e1feef347  guix-build-fd0e8df67cae/output/x86_64-w64-mingw32/bitcoin-fd0e8df67cae-win64-setup-unsigned.exe
6866e0ba9bd4da9487b679f3216cde3d6d455ca074f22de05552b6faf6a6cfca  guix-build-fd0e8df67cae/output/x86_64-w64-mingw32/bitcoin-fd0e8df67cae-win64-unsigned.tar.gz
208d38d00b4a96fb34b558e221f05d08efa078a0d143a2bb2f63fa201c64f29d  guix-build-fd0e8df67cae/output/x86_64-w64-mingw32/bitcoin-fd0e8df67cae-win64.zip
```

### CODE REVIEW

**Review by shaavan — COMMENTED** [review]
<s>Though this might be an improvement and one that is also needed, I would like to mention one thing regarding it.

Following the instructions in https://github.com/bitcoin-core/gui/blob/master/doc/build-unix.md#linux-distribution-specific-instructions to download the dependencies, a user is able to download `Qt version 5.15.3`.

Bumping up the required version would make installing dependencies non-trivial.</s>

**Edit:** 

> Using packages being built with our own depends system is irrelevant to using packages being managed by user's OS, no?

I misinterpreted the change, and I stand corrected. Thanks, @hebasto, for the correction. I shall post the updated review soon.

**Comment by hebasto** [comment]
Using packages being built with our own depends system is irrelevant to using packages being managed by user's OS, no?

**Comment by jarolrod** [comment]
GUIX hashes

x86:
```

```

arm64:
```
$ env HOSTS='arm-linux-gnueabihf arm64-apple-darwin powerpc64-linux-gnu powerpc64le-linux-gnu riscv64-linux-gnu x86_64-apple-darwin x86_64-linux-gnu x86_64-w64-mingw32' ./contrib/guix/guix-build
$ find guix-build-$(git rev-parse --short=12 HEAD)/output/ -type f -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum

1ad8c7ac4ee8981a81d1d7eb7f78e3fcb2ba0f5be6e44f3c6d5ad69dce59a3cc  guix-build-242def30c49d/output/arm-linux-gnueabihf/SHA256SUMS.part
cc55b97e8032a5228639b6cf0cc803dbb1a9dd4591800942800ef9dd5871e586  guix-build-242def30c49d/output/arm-linux-gnueabihf/bitcoin-242def30c49d-arm-linux-gnueabihf-debug.tar.gz
67ec1a1c557ba6a260d0752c72736e09bc714ae35c1b4d026efbf7a1371a3cdc  guix-build-242def30c49d/output/arm-linux-gnueabihf/bitcoin-242def30c49d-arm-linux-gnueabihf.tar.gz
ccf48421b0aa30a51f4150c7615f72c792a4950af184a6d1cb3948855e1729ca  guix-build-242def30c49d/output/arm64-apple-darwin/SHA256SUMS.part
21ca292217ea22f387738072275b3112ea4028b581e9d208e0d05d4c1c7b16ab  guix-build-242def30c49d/output/arm64-apple-darwin/bitcoin-242def30c49d-arm64-apple-darwin-unsigned.dmg
bc845e1182107ab5b92824a04a8c5db51e155f45c8808739395150304f9492d4  guix-build-242def30c49d/output/arm64-apple-darwin/bitcoin-242def30c49d-arm64-apple-darwin-unsigned.tar.gz
ead7d2ae9a0392bfa6d0209372ac740dccdc05fa71e3e05dd09df4a1d26e1d64  guix-build-242def30c49d/output/arm64-apple-darwin/bitcoin-242def30c49d-arm64-apple-darwin.tar.gz
f35f5276582ffb2529490f2a8a773a55b00d056fcb790cfaf836abe781f4e8bd  guix-build-242def30c49d/output/dist-archive/bitcoin-242def30c49d.tar.gz
98b77b6c97632e46b35c07ae835c64c02beb658393afe365a2b6878d47e8cffd  guix-build-242def30c49d/output/powerpc64-linux-gnu/SHA256SUMS.part
1d6654d51af40b41638027dfe47cf51eb0fed744849ca6f69e37b69d6caad42d  guix-build-242def30c49d/output/powerpc64-linux-gnu/bitcoin-242def30c49d-powerpc64-linux-gnu-debug.tar.gz
24238b38e1510b79145adaecac44a63f6b55eb3744bc4772494d36dc12241e36  guix-build-242def30c49d/output/powerpc64-linux-gnu/bitcoin-242def30c49d-powerpc64-linux-gnu.tar.gz
aac4997b88c6951d011493a7f16e7741fe4c26dc15f1f95efc8ddc84a18f2e5e  guix-build-242def30c49d/output/powerpc64le-linux-gnu/SHA256SUMS.part
049908e2a9d0a63a2065bd9f841a71da803c4edb7333436f6432668e04090b27  guix-build-242def30c49d/output/powerpc64le-linux-gnu/bitcoin-242def30c49d-powerpc64le-linux-gnu-debug.tar.gz
17f8941ce1b32aa72a2ccb6dfef4717e1beaf8c67150ff8acaeb121323cab2d4  guix-build-242def30c49d/output/powerpc64le-linux-gnu/bitcoin-242def30c49d-powerpc64le-linux-gnu.tar.gz
ac282b7cf2127db6f6cb980f72dfd468c607993063f68db9f16d61895378e51d  guix-build-242def30c49d/output/riscv64-linux-gnu/SHA256SUMS.part
de1a2ef45ca971e401996ff844929a9e3b26425c98db9215dd1a8c40f4098f71  guix-build-242def30c49d/output/riscv64-linux-gnu/bitcoin-242def30c49d-riscv64-linux-gnu-debug.tar.gz
a4fbf1771feecda509a42e6633100ebebe43257856dae142d6fb7cc732cf154d  guix-build-242def30c49d/output/riscv64-linux-gnu/bitcoin-242def30c49d-riscv64-linux-gnu.tar.gz
0278d3035acbe2b43efbd548032b99ae39683fac20c4f99cf8303c2917b4cbfe  guix-build-242def30c49d/output/x86_64-apple-darwin/SHA256SUMS.part
e50e43aebda69ac7b76fc35f3cfdea94d0e3cec9bccd0b7c1c07d2249166e568  guix-build-242def30c49d/output/x86_64-apple-darwin/bitcoin-242def30c49d-x86_64-apple-darwin-unsigned.dmg
c8d515fc461fbbc26025d2063c8e711781f6d15aa412f4d122cf70bb2da1baaf  guix-build-242def30c49d/output/x86_64-apple-darwin/bitcoin-242def30c49d-x86_64-apple-darwin-unsigned.tar.gz
8d41cbae1d090a4fad6f66b9411d138cba9f0c34c226225c9a459141cfe152c8  guix-build-242def30c49d/output/x86_64-apple-darwin/bitcoin-242def30c49d-x86_64-apple-darwin.tar.gz
af762f4ac69396e0d2e5f697dd7db8181f987555a42442d3415f7893b7e3ab70  guix-build-242def30c49d/output/x86_64-linux-gnu/SHA256SUMS.part
a49babfc052dd894a2cc0607005e359aceee5c80d068df56fbd1c5a5d1cb8095  guix-build-242def30c49d/output/x86_64-linux-gnu/bitcoin-242def30c49d-x86_64-linux-gnu-debug.tar.gz
a3cba4d334bdf613ed85bbb3fce2ea77aaffe542f6d8bfa80129b1cf7b502b25  guix-build-242def30c49d/output/x86_64-linux-gnu/bitcoin-242def30c49d-x86_64-linux-gnu.tar.gz
b8823a8900cc48b47b9fa1688c4c05bae53727bf6e21c71bc3984c4dda9ea8f1  guix-build-242def30c49d/output/x86_64-w64-mingw32/SHA256SUMS.part
e48d2c58cbbfc5d8e66aaf69bc905d9eb1a4164b02bf331bfb5ea7a1b7cf6ef4  guix-build-242def30c49d/output/x86_64-w64-mingw32/bitcoin-242def30c49d-win64-debug.zip
2526b11670937a458912c3f7c001db4f1d3e9a3426bab60a85a5ea1bde447961  guix-build-242def30c49d/output/x86_64-w64-mingw32/bitcoin-242def30c49d-win64-setup-unsigned.exe
d72e013a6f2edb205c3e5e57dd156177a112b27dd91ef1e51c61d26357ccaaa9  guix-build-242def30c49d/output/x86_64-w64-mingw32/bitcoin-242def30c49d-win64-unsigned.tar.gz
49f2ac58fc03e8eb5f02f4ef9cf2c4ce29c207a82ff882a9bc371cc64feb298a  guix-build-242def30c49d/output/x86_64-w64-mingw32/bitcoin-242def30c49d-win64.zip
```

**Comment by fanquake** [comment]
Are there any bug fixes / anything else interesting for us about this update other than removing a single patch from depends? I can't seem to find an actual changelog, other than https://code.qt.io/cgit/qt/qtbase.git/log/?h=v5.15.5-lts-lgpl.

**Comment by hebasto** [comment]
> Are there any bug fixes / anything else interesting for us about this update other than removing a single patch from depends?

No, there are not.

**Comment by fanquake** [comment]
Want to pull in https://github.com/fanquake/bitcoin/commit/c789bd79d27db14ff937b360da67ad0c42d65cdd ?

**Comment by hebasto** [comment]
@fanquake 
> Want to pull in [fanquake@c789bd7](https://github.com/fanquake/bitcoin/commit/c789bd79d27db14ff937b360da67ad0c42d65cdd) ?

Thanks! I've reviewed your commit, and cherry-picked it.

**Review by fanquake — APPROVED** [review]
ACK fd0e8df67caebcc3ace10133eaac2e75e4dc5d8b

Guix Build (x86_64):
```bash
6e403f6442f904a17e00f2c5d539c38a6d736963deaca080aaf7e45911f32cd4  guix-build-fd0e8df67cae/output/aarch64-linux-gnu/SHA256SUMS.part
9faf7c7eba364848ab59f78d68a7ef74fc96c1d4b64c9132c8cdeaa3e90dd11c  guix-build-fd0e8df67cae/output/aarch64-linux-gnu/bitcoin-fd0e8df67cae-aarch64-linux-gnu-debug.tar.gz
5a6a63c1e81f088db952ddd5184f673583cbce122de8a5714ba313064ac4536d  guix-build-fd0e8df67cae/output/aarch64-linux-gnu/bitcoin-fd0e8df67cae-aarch64-linux-gnu.tar.gz
d1f0d94a0996d268a498fce2080a456544ccd60c263eb25c6bb335570ee0e181  guix-build-fd0e8df67cae/output/arm-linux-gnueabihf/SHA256SUMS.part
ec89d624ec30f0117e435ff31fe3431c15eb0ef2c31fc33f7a1c6b71d8af1166  guix-build-fd0e8df67cae/output/arm-linux-gnueabihf/bitcoin-fd0e8df67cae-arm-linux-gnueabihf-debug.tar.gz
71521ee2e382bb3b1e85db0e702cb3d91a6c713f290cb3835f6e6a6ff65de22b  guix-build-fd0e8df67cae/output/arm-linux-gnueabihf/bitcoin-fd0e8df67cae-arm-linux-gnueabihf.tar.gz
e757341c8000cdc74b266217bd1bc3ec2fa4d0a53270cef4fe18182010dde213  guix-build-fd0e8df67cae/output/arm64-apple-darwin/SHA256SUMS.part
a361215f99ef2e10decc2c97ad5aea62e268554101cd34a75a28a0f8cc25bc4d  guix-build-fd0e8df67cae/output/arm64-apple-darwin/bitcoin-fd0e8df67cae-arm64-apple-darwin-unsigned.dmg
81b91ab355544d247c2781bf2e323a70c27780665c3098d8ef01a59d291725f6  guix-build-fd0e8df67cae/output/arm64-apple-darwin/bitcoin-fd0e8df67cae-arm64-apple-darwin-unsigned.tar.gz
0b4e6ae2c66ecf49b2223d8d7fabd00765942ffeb4972fd699e4a9d13f176b6b  guix-build-fd0e8df67cae/output/arm64-apple-darwin/bitcoin-fd0e8df67cae-arm64-apple-darwin.tar.gz
94f4a4a319a896c1ce37980fdac0c6bf9b62e2a8ca46476a10895a4fd8d0403f  guix-build-fd0e8df67cae/output/dist-archive/bitcoin-fd0e8df67cae.tar.gz
cf963b63fabc7e832b9469c9c048b08dcee344cb2044e7930bca53dfdc18c3dd  guix-build-fd0e8df67cae/output/powerpc64-linux-gnu/SHA256SUMS.part
50ac40337bed023900ecf1bd3f557276dba8d97cd613f9342e0f7a72e4c7e6f1  guix-build-fd0e8df67cae/output/powerpc64-linux-gnu/bitcoin-fd0e8df67cae-powerpc64-linux-gnu-debug.tar.gz
6884eba5928b831434ae9a1e5c2945185d1e6f013537aac0a05ae9775ab1df7d  guix-build-fd0e8df67cae/output/powerpc64-linux-gnu/bitcoin-fd0e8df67cae-powerpc64-linux-gnu.tar.gz
ad502cdbf072a3875f4cbf653e9b5593c5f5324edc0e38100234a9778a73cc09  guix-build-fd0e8df67cae/output/powerpc64le-linux-gnu/SHA256SUMS.part
e426a8f45095bc6019612a58f60267f6b084e3c273ec70509a0a8759e90e68d2  guix-build-fd0e8df67cae/output/powerpc64le-linux-gnu/bitcoin-fd0e8df67cae-powerpc64le-linux-gnu-debug.tar.gz
a68ec3ba7e63382dc44f99806badc62e660dd3ae2d9d74d48e7e8378fd5c03f4  guix-build-fd0e8df67cae/output/powerpc64le-linux-gnu/bitcoin-fd0e8df67cae-powerpc64le-linux-gnu.tar.gz
67d0bf587538fb151aa867363ab7724543607adda2b8be7dffbc263959e02f67  guix-build-fd0e8df67cae/output/riscv64-linux-gnu/SHA256SUMS.part
093c874104e8f8c7bd73c362be471aba6d0c25828c22b2a8324056d516849242  guix-build-fd0e8df67cae/output/riscv64-linux-gnu/bitcoin-fd0e8df67cae-riscv64-linux-gnu-debug.tar.gz
82b03ba2283a8667ea3c3fa86a5f64be7c7a4c0423b92bd8f3dfe71a78c3b210  guix-build-fd0e8df67cae/output/riscv64-linux-gnu/bitcoin-fd0e8df67cae-riscv64-linux-gnu.tar.gz
5a30433c33322b9deabe4d6fc655f6dd9e6e73f2ae09b01502ce1a9377e1ce16  guix-build-fd0e8df67cae/output/x86_64-apple-darwin/SHA256SUMS.part
473a3df8d63a112ca3e76620a56f6a5781b74c594451c86c26ccfef63cc2b023  guix-build-fd0e8df67cae/output/x86_64-apple-darwin/bitcoin-fd0e8df67cae-x86_64-apple-darwin-unsigned.dmg
fa0eb43787745d6973ceb880003acf9f5be6e14c5c310bcc359a05cb52dd20a8  guix-build-fd0e8df67cae/output/x86_64-apple-darwin/bitcoin-fd0e8df67cae-x86_64-apple-darwin-unsigned.tar.gz
90ccac950577f15e5dc729e9f94bff39fa0a9f0a96a27eee249df15a604eec44  guix-build-fd0e8df67cae/output/x86_64-apple-darwin/bitcoin-fd0e8df67cae-x86_64-apple-darwin.tar.gz
fffda44e37d74908fcb5974a7c290d4e36d457605824f5d3f79b15e4eae5c1e7  guix-build-fd0e8df67cae/output/x86_64-linux-gnu/SHA256SUMS.part
7d807b88d20a759236013fec99d8b16240dc064a0a5a6eb5d51ba02af467d959  guix-build-fd0e8df67cae/output/x86_64-linux-gnu/bitcoin-fd0e8df67cae-x86_64-linux-gnu-debug.tar.gz
8141de0e3aa4174dea1e1cc3ee6344e857650fdd3180e7a4e8359f84733933fe  guix-build-fd0e8df67cae/output/x86_64-linux-gnu/bitcoin-fd0e8df67cae-x86_64-linux-gnu.tar.gz
653b6c61d4ab5c5dcb8f36aefb518dc14d7fcf9f7d684a521c7705cbda9ff2fe  guix-build-fd0e8df67cae/output/x86_64-w64-mingw32/SHA256SUMS.part
999dc6af5a7262c579be1c9904c1ac2deff0617a48d89d60902de5ba9e3684e6  guix-build-fd0e8df67cae/output/x86_64-w64-mingw32/bitcoin-fd0e8df67cae-win64-debug.zip
03a90e2d6191b6ab84ffb38f845e0565ecf34b5d3b34b7fc36edc99e1feef347  guix-build-fd0e8df67cae/output/x86_64-w64-mingw32/bitcoin-fd0e8df67cae-win64-setup-unsigned.exe
6866e0ba9bd4da9487b679f3216cde3d6d455ca074f22de05552b6faf6a6cfca  guix-build-fd0e8df67cae/output/x86_64-w64-mingw32/bitcoin-fd0e8df67cae-win64-unsigned.tar.gz
208d38d00b4a96fb34b558e221f05d08efa078a0d143a2bb2f63fa201c64f29d  guix-build-fd0e8df67cae/output/x86_64-w64-mingw32/bitcoin-fd0e8df67cae-win64.zip
```

Guix Build (arm64):
```bash
d1f0d94a0996d268a498fce2080a456544ccd60c263eb25c6bb335570ee0e181  guix-build-fd0e8df67cae/output/arm-linux-gnueabihf/SHA256SUMS.part
ec89d624ec30f0117e435ff31fe3431c15eb0ef2c31fc33f7a1c6b71d8af1166  guix-build-fd0e8df67cae/output/arm-linux-gnueabihf/bitcoin-fd0e8df67cae-arm-linux-gnueabihf-debug.tar.gz
71521ee2e382bb3b1e85db0e702cb3d91a6c713f290cb3835f6e6a6ff65de22b  guix-build-fd0e8df67cae/output/arm-linux-gnueabihf/bitcoin-fd0e8df67cae-arm-linux-gnueabihf.tar.gz
2f5ffcca848a85322c600f007b1b7729bf87f0025a2e39e8fb1f05e0670f66f8  guix-build-fd0e8df67cae/output/arm64-apple-darwin/SHA256SUMS.part
034998a6f4f0d7c2321bf70c63ef7b3c5d7f7442612b70f715b686d7bb0c9da0  guix-build-fd0e8df67cae/output/arm64-apple-darwin/bitcoin-fd0e8df67cae-arm64-apple-darwin-unsigned.dmg
ef3bf5d938e9c9556c910a313436d28b0476de69da7f4a9e0ca17d1d85ddeff2  guix-build-fd0e8df67cae/output/arm64-apple-darwin/bitcoin-fd0e8df67cae-arm64-apple-darwin-unsigned.tar.gz
64512719b4708d5fcd359062e78ef4962dcaab70c4f66066e00631c96d25dd32  guix-build-fd0e8df67cae/output/arm64-apple-darwin/bitcoin-fd0e8df67cae-arm64-apple-darwin.tar.gz
94f4a4a319a896c1ce37980fdac0c6bf9b62e2a8ca46476a10895a4fd8d0403f  guix-build-fd0e8df67cae/output/dist-archive/bitcoin-fd0e8df67cae.tar.gz
cf963b63fabc7e832b9469c9c048b08dcee344cb2044e7930bca53dfdc18c3dd  guix-build-fd0e8df67cae/output/powerpc64-linux-gnu/SHA256SUMS.part
50ac40337bed023900ecf1bd3f557276dba8d97cd613f9342e0f7a72e4c7e6f1  guix-build-fd0e8df67cae/output/powerpc64-linux-gnu/bitcoin-fd0e8df67cae-powerpc64-linux-gnu-debug.tar.gz
6884eba5928b831434ae9a1e5c2945185d1e6f013537aac0a05ae9775ab1df7d  guix-build-fd0e8df67cae/output/powerpc64-linux-gnu/bitcoin-fd0e8df67cae-powerpc64-linux-gnu.tar.gz
ad502cdbf072a3875f4cbf653e9b5593c5f5324edc0e38100234a9778a73cc09  guix-build-fd0e8df67cae/output/powerpc64le-linux-gnu/SHA256SUMS.part
e426a8f45095bc6019612a58f60267f6b084e3c273ec70509a0a8759e90e68d2  guix-build-fd0e8df67cae/output/powerpc64le-linux-gnu/bitcoin-fd0e8df67cae-powerpc64le-linux-gnu-debug.tar.gz
a68ec3ba7e63382dc44f99806badc62e660dd3ae2d9d74d48e7e8378fd5c03f4  guix-build-fd0e8df67cae/output/powerpc64le-linux-gnu/bitcoin-fd0e8df67cae-powerpc64le-linux-gnu.tar.gz
67d0bf587538fb151aa867363ab7724543607adda2b8be7dffbc263959e02f67  guix-build-fd0e8df67cae/output/riscv64-linux-gnu/SHA256SUMS.part
093c874104e8f8c7bd73c362be471aba6d0c25828c22b2a8324056d516849242  guix-build-fd0e8df67cae/output/riscv64-linux-gnu/bitcoin-fd0e8df67cae-riscv64-linux-gnu-debug.tar.gz
82b03ba2283a8667ea3c3fa86a5f64be7c7a4c0423b92bd8f3dfe71a78c3b210  guix-build-fd0e8df67cae/output/riscv64-linux-gnu/bitcoin-fd0e8df67cae-riscv64-linux-gnu.tar.gz
5a30433c33322b9deabe4d6fc655f6dd9e6e73f2ae09b01502ce1a9377e1ce16  guix-build-fd0e8df67cae/output/x86_64-apple-darwin/SHA256SUMS.part
473a3df8d63a112ca3e76620a56f6a5781b74c594451c86c26ccfef63cc2b023  guix-build-fd0e8df67cae/output/x86_64-apple-darwin/bitcoin-fd0e8df67cae-x86_64-apple-darwin-unsigned.dmg
fa0eb43787745d6973ceb880003acf9f5be6e14c5c310bcc359a05cb52dd20a8  guix-build-fd0e8df67cae/output/x86_64-apple-darwin/bitcoin-fd0e8df67cae-x86_64-apple-darwin-unsigned.tar.gz
90ccac950577f15e5dc729e9f94bff39fa0a9f0a96a27eee249df15a604eec44  guix-build-fd0e8df67cae/output/x86_64-apple-darwin/bitcoin-fd0e8df67cae-x86_64-apple-darwin.tar.gz
fffda44e37d74908fcb5974a7c290d4e36d457605824f5d3f79b15e4eae5c1e7  guix-build-fd0e8df67cae/output/x86_64-linux-gnu/SHA256SUMS.part
7d807b88d20a759236013fec99d8b16240dc064a0a5a6eb5d51ba02af467d959  guix-build-fd0e8df67cae/output/x86_64-linux-gnu/bitcoin-fd0e8df67cae-x86_64-linux-gnu-debug.tar.gz
8141de0e3aa4174dea1e1cc3ee6344e857650fdd3180e7a4e8359f84733933fe  guix-build-fd0e8df67cae/output/x86_64-linux-gnu/bitcoin-fd0e8df67cae-x86_64-linux-gnu.tar.gz
653b6c61d4ab5c5dcb8f36aefb518dc14d7fcf9f7d684a521c7705cbda9ff2fe  guix-build-fd0e8df67cae/output/x86_64-w64-mingw32/SHA256SUMS.part
999dc6af5a7262c579be1c9904c1ac2deff0617a48d89d60902de5ba9e3684e6  guix-build-fd0e8df67cae/output/x86_64-w64-mingw32/bitcoin-fd0e8df67cae-win64-debug.zip
03a90e2d6191b6ab84ffb38f845e0565ecf34b5d3b34b7fc36edc99e1feef347  guix-build-fd0e8df67cae/output/x86_64-w64-mingw32/bitcoin-fd0e8df67cae-win64-setup-unsigned.exe
6866e0ba9bd4da9487b679f3216cde3d6d455ca074f22de05552b6faf6a6cfca  guix-build-fd0e8df67cae/output/x86_64-w64-mingw32/bitcoin-fd0e8df67cae-win64-unsigned.tar.gz
208d38d00b4a96fb34b558e221f05d08efa078a0d143a2bb2f63fa201c64f29d  guix-build-fd0e8df67cae/output/x86_64-w64-mingw32/bitcoin-fd0e8df67cae-win64.zip
```

**Review by jarolrod — APPROVED** [review]
ACK fd0e8df67caebcc3ace10133eaac2e75e4dc5d8b

My [hashes](https://github.com/bitcoin/bitcoin/pull/25719#issuecomment-1197089707) match, did some sanity check with the built qt binary on macOS and Ubuntu.

**Pull request merged**
