### PR TITLE
Trivial: Grammar and capitalization

### PR DESCRIPTION
**Pull request by Derek701**

### CODE REVIEW

**Comment by MarcoFalke** [comment]
There was also a related suggestion:

>  "Progress increase per hour" is a bit weird sounding to me, maybe "Sync progress per hour"?

Though, I am not a native speaker, so I can't evaluate any of this.

**Comment by laanwj** [comment]
utACK

**Comment by Derek701** [comment]
Oops. Looks like I made a mistake trying to use GitHub for Windows to sync my fork.

**Comment by MarcoFalke** [comment]
ACK c9ce17b, http://english.stackexchange.com/a/9441

**Comment by MarcoFalke** [comment]
> It would be nice to combine other fix-ups to the overlay into this pull request.

Meh, my other pull is more involved and needs some more work to be ready. I will just merge this trivial pull now to reduce the backlog.

**Pull request merged**
