### PR TITLE
build: Patch Qt to handle minimum macOS version properly

### PR DESCRIPTION
**Pull request by hebasto**
This PR is:
- required to [switch](https://github.com/bitcoin/bitcoin/pull/28622) to macOS 14 SDK (Xcode 15).
- an alternative to https://github.com/bitcoin/bitcoin/pull/28732.

### CODE REVIEW

**Comment by fanquake** [comment]
Can you explain the patch? What is the actual problem, and how does this fix it?
Seems a bit odd to have to patch version detection checks inside Qt, can the correct values not be based in from the outside?

**Comment by hebasto** [comment]
> Can you explain the patch? What is the actual problem, and how does this fix it? Seems a bit odd to have to patch version detection checks inside Qt, can the correct values not be passed in from the outside?

In macOS SDK, the problematic `os/activity.h` header relies on the `OS_LOG_TARGET_HAS_10_12_FEATURES` macro:
```c++
#if OS_LOG_TARGET_HAS_10_12_FEATURES
#ifndef OS_ACTIVITY_OBJECT_API
#define OS_ACTIVITY_OBJECT_API 1
#endif // OS_ACTIVITY_OBJECT_API
#else
#if OS_ACTIVITY_OBJECT_API
#error Please change your minimum OS requirements because OS_ACTIVITY_OBJECT_API is not available
#endif // OS_ACTIVITY_OBJECT_API
#define OS_ACTIVITY_OBJECT_API 0
#endif // OS_LOG_TARGET_HAS_10_12_FEATURES
```

That macro in turn is defined in the `os/trace_base.h` header:
```c++
#if __OS_LOG_OS_FEATURES_AT_LEAST(10_12, 10_0, 10_0, 3_0)
#define OS_LOG_TARGET_HAS_10_12_FEATURES 1
#else
#define OS_LOG_TARGET_HAS_10_12_FEATURES 0
#endif
```

which depends on the `__MAC_OS_X_VERSION_MIN_REQUIRED` macro value.

The patch modifies the only code in the whole Qt codebase where the `__MAC_OS_X_VERSION_MIN_REQUIRED` macro is defined. The other `MAC_OS_X_VERSION_MIN_REQUIRED` macro is adjusted for consistency.

**Comment by fanquake** [comment]
> the problematic os/activity.h header 

What is the problem with the header?

The (availability.h) macros are set via the `-mmacosx-version-min` flag (which we set): 
> For these macros to function properly, a program must specify the OS version range 
> it is targeting.  The min OS version is specified as an option to the compiler:
> -mmacosx-version-min=10.x when building for Mac OS X, 

Why do we need to hardcode them to the values that they should already be being set too?

**Comment by hebasto** [comment]
> > the problematic os/activity.h header
> 
> What is the problem with the header?

The `OS_ACTIVITY_OBJECT_API` is set to `0`, which makes a bunch of code unavailable, which in turn causes compile errors.

> The (availability.h) macros are set via the `-mmacosx-version-min` flag (which we set):
> 
> > For these macros to function properly, a program must specify the OS version range
> > it is targeting.  The min OS version is specified as an option to the compiler:
> > -mmacosx-version-min=10.x when building for Mac OS X,

I know this. But I can't see in the code how the `-mmacosx-version-min` flag affect the `__MAC_OS_X_VERSION_MIN_REQUIRED` macro, which is the one that is evaluated in the `os/activity.h` header.

Also, there is a comment in the `Availability.h` header:
```
    It is also possible to use the *_VERSION_MIN_REQUIRED in source code to make one
    source base that can be compiled to target a range of OS versions.  It is best
    to not use the _MAC_* and __IPHONE_* macros for comparisons, but rather their values.
    That is because you might get compiled on an old OS that does not define a later
    OS version macro, and in the C preprocessor undefined values evaluate to zero
    in expresssions, which could cause the #if expression to evaluate in an unexpected
    way.
    
        #ifdef __MAC_OS_X_VERSION_MIN_REQUIRED
            // code only compiled when targeting Mac OS X and not iPhone
            // note use of 1050 instead of __MAC_10_5
            #if __MAC_OS_X_VERSION_MIN_REQUIRED < 1050
                // code in here might run on pre-Leopard OS
            #else
                // code here can assume Leopard or later
            #endif
        #endif
```

> Why do we need to hardcode them to the values that they should already be being set too?

We don't introduce hardcoded values. We rather are adjusting the current inappropriate values, no?

**Comment by fanquake** [comment]
> We rather are adjusting the current inappropriate values, no?

The default values shouldn't need adjusting in the qt source code, if our version setting works. So this would point to that not being the case?

>  The OS_ACTIVITY_OBJECT_API is set to 0, which makes a bunch of code unavailable, which in turn causes compile errors.

In that case, maybe it would be easier to set something like `-DOS_ACTIVITY_OBJECT_API=1` for the Qt build, and not have to patch any source?

However that would still be confusing, because this build failure only happens when cross-compiling? Native builds (using the latest Xcode) are not broken in this way, and the minimum version handling shouldn't differ between the two?

**Comment by hebasto** [comment]
> In that case, maybe it would be easier to set something like `-DOS_ACTIVITY_OBJECT_API=1` for the Qt build, and not have to patch any source?

I think it will hit
```
#error Please change your minimum OS requirements because OS_ACTIVITY_OBJECT_API is not available
```

> Native builds (using the latest Xcode) are not broken in this way, and the minimum version handling shouldn't differ between the two?

I've verified the native build on macOS 14.1 without depends. Both macros are defined to `140000`, which is the same as `__MAC_14_0`.

**Comment by fanquake** [comment]
Another thing to note, is that the code being patched here, has been deleted entirely upstream: https://github.com/qt/qtbase/commit/329db8b64f17c8ef013c586cea1f1c5b49c4a4b7. 
> macOS: Remove fallback defines for MAC_OS_X_VERSION_MIN_REQUIRED 
> Availability.h from the platform SDK should take care of this these days.

So this points to there still being an underlying issue, and workaround will "break" if/when we start using newer versions of Qt.

**Comment by hebasto** [comment]
> Another thing to note, is that the code being patched here, has been deleted entirely upstream: [qt/qtbase@329db8b](https://github.com/qt/qtbase/commit/329db8b64f17c8ef013c586cea1f1c5b49c4a4b7).
> 
> > macOS: Remove fallback defines for MAC_OS_X_VERSION_MIN_REQUIRED
> > Availability.h from the platform SDK should take care of this these days.
> 
> So this points to there still being an underlying issue...

The fact is that the `__MAC_OS_X_VERSION_MIN_REQUIRED` is [_not_](https://github.com/bitcoin/bitcoin/pull/28775#issuecomment-1792023227) defined. At least, when using the current Clang version in depends.

> ... and workaround will "break" if/when we start using newer versions of Qt.

Agree. We can handle it in its time.

**Comment by fanquake** [comment]
> At least, when using the current Clang version in depends.

Right, but why is it suddenly defined when using a newer compiler? Can you point to where in the LLVM/Clang source code this starts happening in versions 16+? It just irks me that updating to a new compiler "magically" fixes things, without explanation.

I think we will likely take this patch as a temporary workaround, just to unblock C++20, but we should probably add some more context to the patch itself. I also dislike having to add comments about "keeping things in sync", rather than enforcing what needs to be done via actual code.

**Comment by hebasto** [comment]
Closing in favour of https://github.com/bitcoin/bitcoin/pull/28851.

**Pull request closed without merging**
