### PR TITLE
[qa] rpc-tests: Properly use test framework

### PR DESCRIPTION
**Pull request by maflcko**
Some tests are not using the framework and thus are blocking some travis related PRs...

It is best to review this PR commit-by-commit. (Append the `?w=flag` to white-space-only commits)

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Keypool is from #4347.

This fixes:

```
$ qa/pull-tester/rpc-tests.py keypool --coverage
Initializing coverage directory at /tmp/coveragerTt3hc
Running 2nd level testscript keypool.py...
Usage: keypool.py [options]

keypool.py: error: no such option: --coveragedir

**Comment by sipa** [comment]
utACK

**Comment by MarcoFalke** [comment]
@laanwj any reason you didn't do this as part of #4347?

**Comment by laanwj** [comment]
> @laanwj any reason you didn't do this as part of #4347?

Probably didn't know about it yet, or even didn't exist yet when I started working on it. 

utACK anyhow

**Pull request merged**
