### PR TITLE
[doc] Update Debian watch & control

### PR DESCRIPTION
**Pull request by fanquake**
Remove SourceForge from Debian watch, as we no longer have binaries there.

Update Bitcoin description in Debian control to match the description in the main README.md file.

[skip-ci]

### CODE REVIEW

**Comment by gmaxwell** [comment]
ACK.

**Comment by MarcoFalke** [comment]
utACK

**Comment by laanwj** [comment]
utACK
(ping @TheBlueMatt )

**Comment by TheBlueMatt** [comment]
Postumous utACK.

**Pull request merged**
