### PR TITLE
test: Check submitblock return values

### PR DESCRIPTION
**Pull request by maflcko**
Add `assert_equal` in some tests to check the `submitblock` return value

### CODE REVIEW

**Comment by robot-visions** [comment]
ACK fa262712ca0981cb0ee68cd3dd99a214a20dcbf1

Updated tests pass locally for me.

Future follow-ups:
- Does it make sense to document the RPC API strings like `block-validation-failed` somewhere?
- It looks like there are a few other test files that call `submitblock` without checking the return value; should those be updated as well?

**Comment by MarcoFalke** [comment]
> It looks like there are a few other test files that call submitblock without checking the return value; should those be updated as well?

I'd say no. Most of them just send a valid block, so the result is `None`. If the block wasn't valid, the tests would fail for that reason already.

> Does it make sense to document the RPC API strings like block-validation-failed somewhere?

Doesn't the documentation of submitblock tell that those are BIP22 reasons?

**Comment by robot-visions** [comment]
The documentation does say they're BIP22 reasons:

```
Result:
null    (json null) Returns JSON Null when valid, a string according to BIP22 otherwise
```

However, BIP22 doesn't give a full list of possible strings.  For example, it doesn't include `inconclusive`, `block-validation-failed`, `bad-witness-nonce-size`, or `bad-witness-merkle-match`.

My question was whether it's important to document the full list of reasons somewhere.  I don't have a strong opinion about this: mostly I am trying to understand how you think about what documentation is important.

**Comment by MarcoFalke** [comment]
No opinion on whether all detailed reasons should be documented. This seems unrelated to this test change either way?

**Comment by robot-visions** [comment]
Correct, it doesn't block this change at all.

When I said "Future Follow-Ups" I meant it as a way to leave a note for future work in separate PRs.  Sorry I distracted from the main point of this change.

**Pull request merged**
