### PR TITLE
fixing typo in README

### PR DESCRIPTION
**Pull request by smatthewenglish**
in accordance with this thread:

https://github.com/bitcoin/bitcoin/pull/9368#issuecomment-270356107

^ I think that's the main problem with trying to group together these small changes I've been making- when they're all agglomerated together it decreased the likelihood that it will be agreeable to everyone, though I do understand that it creates noise if many small changes are being made- but if I didn't think it improved the quality of the software I wouldn't propose it :/

please forgive me for not getting around to this sooner or being more responsive, been a bit preoccupied lately!

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Trivial ACK e2b7556ccb110d3fe2fbb3e0165fb17ad06d53ea

**Comment by morcos** [comment]
don't care enough to NACK, but I think it's more accurate without the `the`

**Comment by laanwj** [comment]
Meh, this is splitting hairs, but I also slightly prefer without 'the'. There is more software that enables use of this currency, of which Bitcoin Core is one.

**Comment by MarcoFalke** [comment]
Closing for now. Seems too controversial.

**Pull request closed without merging**
