### PR TITLE
[0.11] dbwrapper: Detect obfuscation

### LINKED ISSUE #7258: Assertion `hashPrevBlock == view.GetBestBlock()' failed. Aborted (core dumped)
Looks like 0.12 (I was running 3cd836c1d855b92e7c73ab31979f471c4f8dad68 ) is writing a "corrupt" block chain.

Steps to reproduce:
```
$ mkdir  /tmp/dir2
$ ./bitcoin-qt-3cd836c-dirty -testnet -datadir=/tmp/dir2
$ ./bitcoin-0.11.2/bin/bitcoin-qt -testnet -datadir=/tmp/dir2 -debug -printtoconsole

[...]
init message: Verifying wallet...
CDBEnv::Open: LogDir=/tmp/dir2/testnet3/database ErrorFile=/tmp/dir2/testnet3/db.log
scheduler thread start
Bound to [::]:18333
Bound to 0.0.0.0:18333
Cache configuration:
* Using 2.0MiB for block index database
* Using 32.5MiB for chain state database
* Using 65.5MiB for in-memory UTXO set
init message: Loading block index...
Opening LevelDB in /tmp/dir2/testnet3/blocks/index
Opened LevelDB successfully
Opening LevelDB in /tmp/dir2/testnet3/chainstate
Opened LevelDB successfully
LoadBlockIndexDB: last block file = 0
LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=609, size=552976, heights=0...608, time=2011-02-02...2012-05-25)
Checking all blk files are present...
LoadBlockIndexDB: transaction index disabled
Initializing databases...
  - Load block from disk: 0.06ms [0.00s]
bitcoin-qt: main.cpp:1836: bool ConnectBlock(const CBlock&, CValidationState&, CBlockIndex*, CCoinsViewCache&, bool): Assertion `hashPrevBlock == view.GetBestBlock()' failed.
Aborted (core dumped)

### PR DESCRIPTION
**Pull request by maflcko**
Replaces #6919.
Fixes #7258.
Implements https://github.com/bitcoin/bitcoin/issues/6613#issuecomment-138420036.

### CODE REVIEW

**Comment by pstratem** [comment]
concept ACK fa24941c46fe0663efa081326940099313df292f

**Comment by luke-jr** [comment]
Won't this detect the no-op obfuscation too? That wouldn't be a good idea...

**Comment by pstratem** [comment]
@MarcoFalke luke-jr is right you need to also check for the null obfuscation key

**Comment by MarcoFalke** [comment]
@pstratem Why would someone write a null obfuscation key?

**Comment by pstratem** [comment]
@MarcoFalke it's a quirk of how the obfuscation code works, it's XOR so a null obfuscation key is the same as no obfuscation key

**Comment by sipa** [comment]
Do we ever *write* a null key? (as opposed to treating no key as null)

**Comment by MarcoFalke** [comment]
@pstratem But it  is never **written** to the db. This would be like saying I obfuscate every of my GitHub messages with the null obfuscation key. (It's redundant and not needed)

**Comment by pstratem** [comment]
@MarcoFalke I stand corrected

**Comment by laanwj** [comment]
Concept ACK but doubting if this or #6919 makes more sense. 
Sure, backporting the whole thing involves somewhat more code but it seemed more useful than introducing a little bit less of code to just warn.

**Comment by MarcoFalke** [comment]
@laanwj This can be cherry-picked to 0.10 without conflicts as well. As this issue seems popular ( https://github.com/bitcoin/bitcoin/issues/7258#issuecomment-167353533 ) we need either #7259 (this) or #6919.

Keep in mind you can rebase #6919 simply on a commit which reverts #7259 (this), in case you want to reopen after #7259 (this) got merged. ("'Don't Let Perfect Be The Enemy Of Good'")

**Comment by laanwj** [comment]
Yeah, this is fine for 0.11. It's easier to test that it rejects a database than to test whether it works.

Would be nice to have at least one tested ACK, though.

**Pull request merged**
