### PR TITLE
Update univalue subtree

### PR DESCRIPTION
**Pull request by maflcko**
Only change is a performance improvement. See https://github.com/bitcoin-core/univalue/pull/21#issue-333858474 and https://github.com/bitcoin-core/univalue/pull/15#issue-186748173

### CODE REVIEW

**Comment by MarcoFalke** [comment]
The last update was more than a year ago: https://github.com/bitcoin/bitcoin/pull/14164#issue-213911287

**Comment by laanwj** [comment]
There have also been some changes last year in https://github.com/jgarzik/univalue/commits/master, do we want to include them?

**Comment by jnewbery** [comment]
ACK fa439e88af944082875e1fdb1cd8bb5a74b88b56

**Comment by MarcoFalke** [comment]
> There have also been some changes last year in https://github.com/jgarzik/univalue/commits/master, do we want to include them?

We check the return value of `Univalue::read` everywhere, so I'd rather not add some clumsy `goto`. I'd prefer a nodiscard attribute.

**Comment by jgarzik** [comment]
> > There have also been some changes last year in https://github.com/jgarzik/univalue/commits/master, do we want to include them?
> 
> We check the return value of `Univalue::read` everywhere, so I'd rather not add some clumsy `goto`. I'd prefer a nodiscard attribute.

Can you specify which commit or line of code this refers to?   Bitcoin Core is a major user of univalue, and we want to avoid a situation where Bitcoin's univalue diverges from the Debian/Ubuntu univalue.

**Comment by laanwj** [comment]
> We check the return value of Univalue::read everywhere, so I'd rather not add some clumsy goto. I'd prefer a nodiscard attribute.

Ok. Thanks for the explanation It's useful to document why we're not taking certain changes from upstream.

ACK fa439e88af944082875e1fdb1cd8bb5a74b88b56

**Comment by jgarzik** [comment]
> > We check the return value of Univalue::read everywhere, so I'd rather not add some clumsy goto. I'd prefer a nodiscard attribute.
> 
> Ok. Thanks for the explanation It's useful to document why we're not taking certain changes from upstream.

It would be better for the trees not to diverge.  Will look at removing "clumsy goto" related code, and work to eliminate this code-divergence issue.

**Comment by luke-jr** [comment]
The so-called "clumsy goto" in this case looks like pretty reasonable use of goto...

**Comment by MarcoFalke** [comment]
We don't use `goto ` anywhere else in the code base and this case can be replaced with a one line helper function that clears the Univalue and returns false.

**Comment by laanwj** [comment]
Also, while it has definite uses in C, the use of `goto` is generally unnecessary in modern C++.

**Comment by practicalswift** [comment]
Regardless of `goto` vs not `goto` I really think we should incorporate the changes done upstreams :) They seem to have been done for very good reasons AFAICT.

**Comment by MarcoFalke** [comment]
Speedup for gcc: https://codespeed.bitcoinperf.com/timeline/?exe=3%2C4%2C2%2C1%2C5&base=1%2B23&ben=micro.gcc.RpcMempool&env=1&revs=50&equid=off&quarts=on&extr=on
and: https://codespeed.bitcoinperf.com/timeline/?exe=3%2C4%2C2%2C1%2C5&base=1%2B23&ben=micro.gcc.BlockToJsonVerbose&env=1&revs=50&equid=off&quarts=on&extr=on


No speedup for clang: https://codespeed.bitcoinperf.com/timeline/?exe=3%2C4%2C2%2C1%2C5&base=1%2B23&ben=micro.clang.RpcMempool&env=1&revs=50&equid=off&quarts=on&extr=on
and: https://codespeed.bitcoinperf.com/timeline/?exe=3%2C4%2C2%2C1%2C5&base=1%2B23&ben=micro.clang.BlockToJsonVerbose&env=1&revs=50&equid=off&quarts=on&extr=on

**Pull request merged**
