### PR TITLE
bench: Add block assemble benchmark

### PR DESCRIPTION
**Pull request by maflcko**

### CODE REVIEW

**Comment by sipa** [comment]
Concept ACK

**Comment by practicalswift** [comment]
Very nice!

Concept ACK

**Comment by MarcoFalke** [comment]
Can be tested with e.g.  #13011 applied

```
./src/bench/bench_bitcoin --filter=AssembleBlock

**Comment by TheBlueMatt** [comment]
Might be an interesting benchmark to literally dump mempool (+utxo set subset needed to validate them) from some snapshot in time where we have a nontrivial one into a blob and use that to benchmark against. Either that or in some way more realistic mempool makeup then just 100 homogeneous transactions.

**Comment by promag** [comment]
Concept ACK.

**Review by conscott — COMMENTED** [review]
Tested ACK fa0fc1bc7edc7f1dd419db6776dcf89749cc1a00

**Comment by jamesob** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/13219/commits/fa0fc1bc7edc7f1dd419db6776dcf89749cc1a00

Code looks good. We need more benches like this.

**Comment by laanwj** [comment]
utACK fa0fc1bc7edc7f1dd419db6776dcf89749cc1a00

**Pull request merged**
