### PR TITLE
qt, wallet: Revamp SendConfirmationDialog

### LINKED ISSUE #15667: Transaction confirmation prompt too big - buttons not clickable
_Second try - first issue got deleted suddenly..._

When confirming too big transactions, depending on screen resolution with each output the buttons move lower and lower until they are not visible anymore on the screen.

Additionally randomly after a couple transactions the client starts to repeat its content in the confirmation prompt making even the smalest 1:1 transaction unusable as the buttons are not visible, again. (See screenshot)

I (A) would expect that the buttons are visible no matter how big the transaction content is (for example by making the content scrollable) and (B) don't understand why the content is repeating suddenly.

Using Bitcoin Knots 17 but have been directed by the developers that the issue belongs to bitcoin/bitcoin

bug-NEW

Windows 10
1920x1080
Intel i7

### PR DESCRIPTION
**Pull request by hebasto**
Fix #15667

With this PR:
Screenshot from 2019-04-24 23-47-30
Screenshot from 2019-04-24 23-47-40

### CODE REVIEW

**Review by promag — COMMENTED** [review]
utACK 2ee756f, TIL `detailedText`!

This is enough to fix #15667 and in a follow the detailed text can be improved. For instance, there's no point printing "from wallet" for each recipient I think.

**Comment by jonasschnelli** [comment]
Nice work!
I also wasn't aware of `QMessageBox::setDetailedText()`.
utACK 2ee756f0411c467fc638373ea68d6cb5ced46974

**Comment by jonasschnelli** [comment]
Tested a bit. I think the "show details..." approach should only appear if we have multiple recipients. But I'm open to be convince otherwise.

**Comment by hebasto** [comment]
@promag @jonasschnelli 
Thank you for your reviews.

> I think the "show details..." approach should only appear if we have multiple recipients.

Nice. Done.

**Comment by laanwj** [comment]
code review ACK 78f9b5160fea32f85c6ced16b3b0cccda6d3b181

**Pull request merged**
