### PR TITLE
[Testing] Include fRelay in mininode version messages

### PR DESCRIPTION
**Pull request by jnewbery**
In protocol version 70001, an additional field `fRelay` was added to the version message (see https://github.com/bitcoin/bips/blob/master/bip-0037.mediawiki#extensions-to-existing-messages ).

Mininode does not currently include the `fRelay` field in its version messages, and so is technically sending malformed version messages. This PR fixes mininode's version messages.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
> technically sending malformed version message

Are you sure that the field is required? The BIP implies that the field is optional:

> If *missing* or true, no change in protocol behaviour occurs.

**Comment by jnewbery** [comment]
@MarcoFalke Yes - you're correct. I didn't read the BIP closely enough.

Still, I think mininode should specify the `fRelay` field. Even better: we should have a bloom filter test in qa which explicitly tests the field.

**Comment by laanwj** [comment]
It makes sense for the test framework to support this.
utACK https://github.com/bitcoin/bitcoin/pull/8894/commits/d7bf55c3f3ac4466885c1a99aecdf5ed24b27bcf

**Comment by MarcoFalke** [comment]
> Even better: we should have a bloom filter test in qa which explicitly tests the field.

Sure.

Please also make sure to *deserialize* nRelay and mention it in the repr.

**Comment by jonasschnelli** [comment]
Agree with @MarcoFalke, you should extend the change to the deserialization method.

**Comment by MarcoFalke** [comment]
@jnewbery Are you still working on this?

**Comment by jnewbery** [comment]
@MarcoFalke : deserialization and repr methods updated.

**Comment by MarcoFalke** [comment]
Thanks, utACK e5d682faa3e8bdb7be2ea1d4b9835ee563a351f4

**Pull request merged**
