### PR TITLE
depends: sqlite 3.46.1

### PR DESCRIPTION
**Pull request by fanquake**
Update sqlite in depends from [3.38.5](https://sqlite.org/releaselog/3_38_5.html) to [3.46.1](https://sqlite.org/releaselog/3_46_1.html).

### CODE REVIEW

**Comment by TheCharlatan** [comment]
Guix builds (aarch64)
```
95204b6b16c56371e935059face7a9775a20248823740257a96f302b30a1f766  guix-build-63678f7635b4/output/aarch64-linux-gnu/SHA256SUMS.part
a7e81be279d93a7a20b354f98183ac7247694a3a665d56ee05d24cf249d7f74e  guix-build-63678f7635b4/output/aarch64-linux-gnu/bitcoin-63678f7635b4-aarch64-linux-gnu-debug.tar.gz
613d11f0e216160f050e3e752234d33ba63d7e8c7d27bebabbc4cb292d686624  guix-build-63678f7635b4/output/aarch64-linux-gnu/bitcoin-63678f7635b4-aarch64-linux-gnu.tar.gz
5d1286410dcad7a02dfb604b14e5c8075a9968bc199d9ed2f70ac79200aac1ee  guix-build-63678f7635b4/output/arm-linux-gnueabihf/SHA256SUMS.part
f5d6f559684f24555f7dbb8bf20b45b6e89ac0e6f91bd4432c31d3f99ec2b905  guix-build-63678f7635b4/output/arm-linux-gnueabihf/bitcoin-63678f7635b4-arm-linux-gnueabihf-debug.tar.gz
a3a1a4c3d8fce45a9c9cf11b707fd267f81ea2c4fd9369ec59f2b79c82000c26  guix-build-63678f7635b4/output/arm-linux-gnueabihf/bitcoin-63678f7635b4-arm-linux-gnueabihf.tar.gz
fc4e699b42ade1de1a1567f40199baf9dc70a7612b85c172511706b5ff2e0bf4  guix-build-63678f7635b4/output/arm64-apple-darwin/SHA256SUMS.part
c9a838304ff734d3c8be98e88c25d5d845dc1203c0abccda0520df2a1d714b46  guix-build-63678f7635b4/output/arm64-apple-darwin/bitcoin-63678f7635b4-arm64-apple-darwin-unsigned.tar.gz
fc7ebdc19728be16075aba1a225925e3a825c9e374fc4c81febcf195d5c22383  guix-build-63678f7635b4/output/arm64-apple-darwin/bitcoin-63678f7635b4-arm64-apple-darwin-unsigned.zip
4fe96ae092970faa95bff99d1ed40967ac6b3da7df2d1fd9b74e3dd3876ebd3d  guix-build-63678f7635b4/output/arm64-apple-darwin/bitcoin-63678f7635b4-arm64-apple-darwin.tar.gz
d22b6d25f2853fb1a888d02c1f7170d6c89b475027305df76b861e44224cb9f7  guix-build-63678f7635b4/output/dist-archive/bitcoin-63678f7635b4.tar.gz
1bf233ad67b5cdc57ec38225ee65fb9586c84f8d78a6a40044166108d0a784fe  guix-build-63678f7635b4/output/powerpc64-linux-gnu/SHA256SUMS.part
59eb72b19b74178d9e9d8483e41cbfd63dda65cd28032e735b51e1cbf7f03462  guix-build-63678f7635b4/output/powerpc64-linux-gnu/bitcoin-63678f7635b4-powerpc64-linux-gnu-debug.tar.gz
a5932bd6cbaf78cd0c49f9251095cf722310fc9b97b165c5db7320369e44b155  guix-build-63678f7635b4/output/powerpc64-linux-gnu/bitcoin-63678f7635b4-powerpc64-linux-gnu.tar.gz
0954fd791baaaa5b661b4b06ad463c140eb4221f34f84e5bc64d79ef7f8ec482  guix-build-63678f7635b4/output/riscv64-linux-gnu/SHA256SUMS.part
cedc7dab92c2d6707fc475af09b2c67eb6b42765d41d1dff1d93fbc50a9c4f9b  guix-build-63678f7635b4/output/riscv64-linux-gnu/bitcoin-63678f7635b4-riscv64-linux-gnu-debug.tar.gz
6b8f791a56883c6822dbcafe0fbeb0de27aeba0b8223c337d71576b274890155  guix-build-63678f7635b4/output/riscv64-linux-gnu/bitcoin-63678f7635b4-riscv64-linux-gnu.tar.gz
f7ffa8021fd21e777111a2913c9de68260cd0138c2fe9d9d24f3552c2a482f91  guix-build-63678f7635b4/output/x86_64-apple-darwin/SHA256SUMS.part
68329f07fa6a783d50cdc16ec694492e8e9524a2484ee3a64802e4f75137cd5e  guix-build-63678f7635b4/output/x86_64-apple-darwin/bitcoin-63678f7635b4-x86_64-apple-darwin-unsigned.tar.gz
d8f4b4d779ea1ad3b249c41d007866730cd9ca5499c205dfe4bfdcb58b1405b2  guix-build-63678f7635b4/output/x86_64-apple-darwin/bitcoin-63678f7635b4-x86_64-apple-darwin-unsigned.zip
0581070a429fb9e4169497d447eae7f8ac1d922c8d921a6dfb189b64620648d7  guix-build-63678f7635b4/output/x86_64-apple-darwin/bitcoin-63678f7635b4-x86_64-apple-darwin.tar.gz
3abaa2d83e6c9a2e397a6fe970403d390104329d7206a647d6ed01f814dcfbe8  guix-build-63678f7635b4/output/x86_64-linux-gnu/SHA256SUMS.part
ef2bf489e05a15f6099bae0d14eb36870b09426e31b852e5aa556488db6e238e  guix-build-63678f7635b4/output/x86_64-linux-gnu/bitcoin-63678f7635b4-x86_64-linux-gnu-debug.tar.gz
48157d8a8e78f982c0c23f87b8cb65a6d3d412d297444a58ab12ce9321f52867  guix-build-63678f7635b4/output/x86_64-linux-gnu/bitcoin-63678f7635b4-x86_64-linux-gnu.tar.gz
285bb50336410ad429129a9586e97992367699158227465f130bf7acbdf3b222  guix-build-63678f7635b4/output/x86_64-w64-mingw32/SHA256SUMS.part
8e191c7d4f65d0f8fa7889698b9b4d0acae03473541d437f4271e86964e8315f  guix-build-63678f7635b4/output/x86_64-w64-mingw32/bitcoin-63678f7635b4-win64-debug.zip
d4582802b8cfe1f142164f31ef9f781efea33985817695959d94adc36232a53e  guix-build-63678f7635b4/output/x86_64-w64-mingw32/bitcoin-63678f7635b4-win64-setup-unsigned.exe
a92746da3b9e3178b6fc6cccc1d7e89ab0575eacfce47d9267d0ae198914b98e  guix-build-63678f7635b4/output/x86_64-w64-mingw32/bitcoin-63678f7635b4-win64-unsigned.tar.gz
1381193d48ec1ae16d291b99954935786123dbdabfbb7652de98046a2c1e9557  guix-build-63678f7635b4/output/x86_64-w64-mingw32/bitcoin-63678f7635b4-win64.zip
```

**Comment by fanquake** [comment]
Not super pressing. I've been looking at ways we could build sqlite with CMake, given that will be one of the last Autotools holdouts. Some builders for the amalgamation exist, but are mostly based off/more usable with a more recent version.

**Comment by TheCharlatan** [comment]
Guix build (aarch64):
```
773a4d0dbc05ceb91439802ce3374b252f45d2a4c69c3fa5930d9450d8c1f340  guix-build-def6dd0c597f/output/aarch64-linux-gnu/SHA256SUMS.part
c7719110515db339e6ca87f8255338eb21ed2df2fa89e2ae72a10860a6fff2a5  guix-build-def6dd0c597f/output/aarch64-linux-gnu/bitcoin-def6dd0c597f-aarch64-linux-gnu-debug.tar.gz
83a75cb1242f725f234e16799791890d0aebd2efab1632ac3db300b73ad664a9  guix-build-def6dd0c597f/output/aarch64-linux-gnu/bitcoin-def6dd0c597f-aarch64-linux-gnu.tar.gz
f6d09f3839868dee41570771e96e3b86bba37afb8691e5132b356c232fcd2497  guix-build-def6dd0c597f/output/arm-linux-gnueabihf/SHA256SUMS.part
ed500cc8dc809ff944421f4c5c79f13c219f773b32803ce1c824f1606719e3cf  guix-build-def6dd0c597f/output/arm-linux-gnueabihf/bitcoin-def6dd0c597f-arm-linux-gnueabihf-debug.tar.gz
75cf4d67362c76b76169b07110b5743400967232c7f747f569d4f3fbefd6909d  guix-build-def6dd0c597f/output/arm-linux-gnueabihf/bitcoin-def6dd0c597f-arm-linux-gnueabihf.tar.gz
4786b3ed53a06c7cf0bde9c278d5f786876af6d9b6cf0400ae472fd0f571a6b4  guix-build-def6dd0c597f/output/arm64-apple-darwin/SHA256SUMS.part
6231c69411daf0e7e0a867e9cdc4c41d7ab1f5f389155838024ce4faf1852b83  guix-build-def6dd0c597f/output/arm64-apple-darwin/bitcoin-def6dd0c597f-arm64-apple-darwin-unsigned.tar.gz
224c904181b4da0bef50e2ef123b4ba9d8177f708119213cd44f37416d31bce0  guix-build-def6dd0c597f/output/arm64-apple-darwin/bitcoin-def6dd0c597f-arm64-apple-darwin-unsigned.zip
911c8a9c4712884450ddfaf6160d6c3226dda63999e203e67d05020b6d9f3003  guix-build-def6dd0c597f/output/arm64-apple-darwin/bitcoin-def6dd0c597f-arm64-apple-darwin.tar.gz
bc207b9d8c80697f453301b6dbd70bb24ee034fda876f8dd04b3026be485fe8c  guix-build-def6dd0c597f/output/dist-archive/bitcoin-def6dd0c597f.tar.gz
4f2fa510b7a229a7f209a1003e9f05a9e85382e30dcfe0a667b1f7d77ff118e1  guix-build-def6dd0c597f/output/powerpc64-linux-gnu/SHA256SUMS.part
856a29459ae27b267010b1a68ec26d5d21e320b4497eef86fa71a065b5cd6d75  guix-build-def6dd0c597f/output/powerpc64-linux-gnu/bitcoin-def6dd0c597f-powerpc64-linux-gnu-debug.tar.gz
70ab180dffa6e3fbf7ead6e05bcbcba6ff4130bd157d740e75eb5dd77eabc022  guix-build-def6dd0c597f/output/powerpc64-linux-gnu/bitcoin-def6dd0c597f-powerpc64-linux-gnu.tar.gz
c3c6918c5c2de73fdf2feaa78561bb7b00c6cf2d6f48b7aa2c2ec84874fb6c3c  guix-build-def6dd0c597f/output/riscv64-linux-gnu/SHA256SUMS.part
7b801b695c30cd43b32277103ee952afe918f7355fadbc6389633d4ce1991b6c  guix-build-def6dd0c597f/output/riscv64-linux-gnu/bitcoin-def6dd0c597f-riscv64-linux-gnu-debug.tar.gz
aa6e9c77b85cbd4c3ead474adabb4663c2cb8bdd812cd8bad8990e07c8ead836  guix-build-def6dd0c597f/output/riscv64-linux-gnu/bitcoin-def6dd0c597f-riscv64-linux-gnu.tar.gz
346d8b07286d7949808238be10d55d73cef8ae517ed751e75f53fb160629ad69  guix-build-def6dd0c597f/output/x86_64-apple-darwin/SHA256SUMS.part
428a51ab1b0d4897cf2fc503ae1bd1fb58ef0a3bff37e18a4100d476d99b8806  guix-build-def6dd0c597f/output/x86_64-apple-darwin/bitcoin-def6dd0c597f-x86_64-apple-darwin-unsigned.tar.gz
be01eff9b4a8a56cf98a105738b8a17fe80371ca50be9ae2cc55d6e07ac1c121  guix-build-def6dd0c597f/output/x86_64-apple-darwin/bitcoin-def6dd0c597f-x86_64-apple-darwin-unsigned.zip
045e7af17769598a6a6e8a29e07e299f7efa6fa50900126497fdcc7db5a486f4  guix-build-def6dd0c597f/output/x86_64-apple-darwin/bitcoin-def6dd0c597f-x86_64-apple-darwin.tar.gz
bee7f136954df75e191f5a8c65632a5dee5432c0e442cecc0de7f90975f20a09  guix-build-def6dd0c597f/output/x86_64-linux-gnu/SHA256SUMS.part
56766d6404262f137c7a4628dc77d360e9cb6f2f4bbc20969002af7e64ab4073  guix-build-def6dd0c597f/output/x86_64-linux-gnu/bitcoin-def6dd0c597f-x86_64-linux-gnu-debug.tar.gz
7a6bad795102d44143355475afc4475f651c87073f94fdec628fa59f00768960  guix-build-def6dd0c597f/output/x86_64-linux-gnu/bitcoin-def6dd0c597f-x86_64-linux-gnu.tar.gz
23141a2b47e63c04f6298d7ea90fba4823db48908e7ab33f6057d6ae383539d5  guix-build-def6dd0c597f/output/x86_64-w64-mingw32/SHA256SUMS.part
e9076acf52e99d3aea4dee270604276d373fb935ac283e58832e6fa818536404  guix-build-def6dd0c597f/output/x86_64-w64-mingw32/bitcoin-def6dd0c597f-win64-debug.zip
b50ff230d1aee5eb8576458f0eebb7e60b9886c7640989a253bb26e737a08182  guix-build-def6dd0c597f/output/x86_64-w64-mingw32/bitcoin-def6dd0c597f-win64-setup-unsigned.exe
a78adac3ad827cdd3ebff1320fe6af9340cc20415f5158f77e44b09d4825bc31  guix-build-def6dd0c597f/output/x86_64-w64-mingw32/bitcoin-def6dd0c597f-win64-unsigned.tar.gz
bbd5fed4743b5d92a327bdbbb4d7b9092b38fd51a5df39f06a96b5d4f9323003  guix-build-def6dd0c597f/output/x86_64-w64-mingw32/bitcoin-def6dd0c597f-win64.zip
```

**Review by sedited — APPROVED** [review]
ACK def6dd0c597f2c7b0c55910792e646b8ff93e36c

**Review by theuni — APPROVED** [review]
Not opposed utACK def6dd0c597f2c7b0c55910792e646b8ff93e36c

**Comment by fanquake** [comment]
Looks like as of `3.48.0` (current release is `3.47.0`), SQLite is going to migrate it's build system from Autotools to [autosetup](https://msteveb.github.io/autosetup/): https://sqlite.org/src/timeline?r=autosetup.

**Pull request merged**
