### PR TITLE
build: Bump clang minimum supported version to 13

### PR DESCRIPTION
**Pull request by maflcko**
All supported operating systems ship with clang-13 (or later), so bump the minimum to that and remove now unused workarounds for previous clang bugs.

For reference:
* https://packages.debian.org/bullseye/clang-13
* https://packages.ubuntu.com/jammy/clang (`clang-14`) and https://packages.ubuntu.com/jammy/clang-15
* CentOS-like 8/9 Stream: All Clang versions from 13 to 15
* FreeBSD 12/13: All Clang version from 13 to 16
* OpenSuse Tumbleweed ships with https://software.opensuse.org/package/clang (`clang16`); No idea about OpenSuse Leap

This is for Bitcoin Core 27.0 in 2024 (next year), not the soon upcoming 26.0 next month.

### CODE REVIEW

**Comment by fanquake** [comment]
> This fails on macOS 11.0,

Yea, this'll at least need to wait for the macOS compiler bump, but the next time that happens (soon) it will be from 11 to 16, if not 17.

**Comment by fanquake** [comment]
If you want pull in https://github.com/fanquake/bitcoin/commit/fc8f7ae32dc16526fe2f155422781bfbc7e9f326, should be enough for green macOS cross-compile CI. Tested once locally.

**Comment by fanquake** [comment]
CI should be all green on next rebase.

**Comment by fanquake** [comment]
Concept ACK

**Comment by hebasto** [comment]
> This is for Bitcoin Core 27.0 in 2024

Concept ACK.

**Comment by hebasto** [comment]
Just to clarify, does this mean that we will drop support for Ubuntu 20.04 LTS as a build platform for Bitcoin Core v27.0 in 2024, even though its End of Standard Support is in 2025?

**Comment by fanquake** [comment]
ACK fae379b6b1c9d434821acc348f010d67c4fee927

**Comment by hebasto** [comment]
Post-merge ACK.

**Pull request merged**
