### PR TITLE
Fix a type error that would not compile on OSX.

### PR DESCRIPTION
**Pull request by JeremyRubin**
I was unable to compile on OSX without having the proper type here.

### CODE REVIEW

**Comment by paveljanik** [comment]
@JeremyRubin can you please paste exact error message?

**Comment by JeremyRubin** [comment]
```
httprpc.cpp:234:5: error: no matching function for call to 'RegisterHTTPHandler'
    RegisterHTTPHandler("/", true, HTTPReq_JSONRPC);
    ^~~~~~~~~~~~~~~~~~~
./httpserver.h:41:6: note: candidate function not viable: no known conversion from 'bool (HTTPRequest *, const std::string &)' to 'const HTTPRequestHandler'
      (aka 'const function<void (HTTPRequest *, const std::string &)>') for 3rd argument
void RegisterHTTPHandler(const std::string &prefix, bool exactMatch, const HTTPRequestHandler &handler);
     ^
1 error generated.
make[1]: *** [libbitcoin_server_a-httprpc.o] Error 1
make: *** [all-recursive] Error 1
```

**Comment by paveljanik** [comment]
Interesting. Can't reproduce here, but the change is obviously correct.

ACK https://github.com/bitcoin/bitcoin/pull/8513/commits/8194a6e525514d5cda85ac08273a6ffb6d5b6cac

**Comment by JeremyRubin** [comment]
@paveljanik 

you have:

```
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

on master?

**Comment by paveljanik** [comment]
My clang is:

```
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

**Comment by jonasschnelli** [comment]
Can't reproduce either, but utACK.
```
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
```

**Comment by laanwj** [comment]
This is safe: all functions that are registered with `RegisterHTTPHandler` return a bool.
ACK 8194a6e

**Pull request merged**
