### PR TITLE
fix typo in comment of chain.cpp

### PR DESCRIPTION
**Pull request by kanigsson**

### CODE REVIEW

**Comment by paveljanik** [comment]
trivial ACK https://github.com/bitcoin/bitcoin/pull/11469/commits/f902e40c76d25eb9d32994f4844db6059f0f55ab

Good catch!

**Comment by jonasschnelli** [comment]
Thanks!
ACK f902e40c76d25eb9d32994f4844db6059f0f55ab

**Comment by fanquake** [comment]
ACK https://github.com/bitcoin/bitcoin/commit/f902e40c76d25eb9d32994f4844db6059f0f55ab

**Comment by promag** [comment]
ACK f902e40.

**Comment by laanwj** [comment]
Obvious ACK (where were you during review :) https://github.com/bitcoin/bitcoin/commit/f902e40c76d25eb9d32994f4844db6059f0f55ab

**Pull request merged**
