### PR TITLE
sendmany/bumpfee: Avoid address reuse and partial spends as per walle…

### LINKED ISSUE #17706: `avoid_reuse` support for non-`sendtoaddress` calls
`sendmany`, `bumpfee` and others should ideally contain something like this block:

```
    coin_control.m_avoid_address_reuse = GetAvoidReuseFlag(pwallet, request.params[8]);
    // We also enable partial spend avoidance if reuse avoidance is set.
    coin_control.m_avoid_partial_spends |= coin_control.m_avoid_address_reuse;
```
to avoid leakage

### PR DESCRIPTION
**Pull request by instagibbs**
…t flags

partiall resolves https://github.com/bitcoin/bitcoin/issues/17706

### CODE REVIEW

**Comment by promag** [comment]
Concept ACK. With this change there's 3 times the same code, maybe too soon to factor out to some function.

**Comment by instagibbs** [comment]
@promag we could make CoinControl take a wallet param, and initialize it as per wallet defaults(or something like this)

**Comment by promag** [comment]
Or some setter like `CCoinControl::SetAvoidAddressReuse(bool)` that would update `m_avoid_partial_spends` too.

**Comment by instagibbs** [comment]
turns out it's already handled in coin selection directly, closing.

**Pull request closed without merging**
