### PR TITLE
0.20: Add txids with non-standard inputs to reject filter

### PR DESCRIPTION
**Pull request by sdaftuar**
Backport of #19620 to 0.20.

### CODE REVIEW

**Comment by jnewbery** [comment]
utACK 107cf1515e69ee773ad1bcc1d5b6fffa49b78750

**Comment by instagibbs** [comment]
should this be added to 0.20.2 milestone?

**Comment by instagibbs** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/19680/commits/107cf1515e69ee773ad1bcc1d5b6fffa49b78750

**Comment by fjahr** [comment]
utACK 107cf1515e69ee773ad1bcc1d5b6fffa49b78750

Didn't do full testing but briefly verified that the test fails if the behavior changes are undone.

**Pull request merged**
