### PR TITLE
Drop defunct Windows compat fixes

### PR DESCRIPTION
**Pull request by Empact**
"The AI_ADDRCONFIG flag is defined on the Windows SDK for Windows Vista and later.
The AI_ADDRCONFIG flag is supported on Windows Vista and later."
https://docs.microsoft.com/en-us/windows/desktop/api/ws2tcpip/nf-ws2tcpip-getaddrinfo

However, the version of MinGW we use on Travis is not current and does
not carry the relevant definition, as such I defined it in compat.
https://github.com/wine-mirror/wine/blob/master/include/ws2tcpip.h

Testing confirms that the PROTECTION_LEVEL_UNRESTRICTED and
IPV6_PROTECTION_LEVEL are now supported by the version of windows that
we test against, so can be removed.
https://travis-ci.org/bitcoin/bitcoin/jobs/483255439

### CODE REVIEW

**Comment by laanwj** [comment]
Nice
utACK 8f68b80dd6f30e0a975f44bb5001c033ce381642

**Comment by Empact** [comment]
Looks like I’m missing the necessary require. Will look tonight.

**Comment by Empact** [comment]
@ken2812221 Seems this is working despite the version not being set, thanks to the shim in compat.h, but I suspect we can remove that if we set the `_WIN32_WINNT` version. We should be able to detect that situation when it occurs thanks to the `FAIL_ON_EXTRANEOUS_COMPAT` case I added here.

**Comment by laanwj** [comment]
> I think that this would require to define _WIN32_WINNT=0x0601 (Windows 7)

In that case it might be better to merge this into #14922

**Comment by Empact** [comment]
Sounds good, the relevant changes are in: https://github.com/Empact/bitcoin/commit/d0522ec94ebbaa564f5f6b31236d4df032664411 if @ken2812221 wants to pick them up.

**Pull request closed without merging**
