### PR TITLE
ci: Disable valgrind functionl tests on forked repos to avoid timeouts

### PR DESCRIPTION
**Pull request by maflcko**
Allows people to fork our repo and run the tests again

Also print more cache stats

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Build in my fork: https://travis-ci.org/github/MarcoFalke/bitcoin-core/builds/676180239

**Comment by hebasto** [comment]
[Looks](https://travis-ci.org/github/bitcoin/bitcoin/jobs/676181070) nice:
```
ccache version 3.4.1
cache directory                     /home/travis/build/bitcoin/bitcoin/ci/scratch/.ccache
primary config                      /home/travis/build/bitcoin/bitcoin/ci/scratch/.ccache/ccache.conf
secondary config      (readonly)    /etc/ccache.conf
stats zero time                     Fri Apr 17 13:40:23 2020
cache hit (direct)                   499
cache hit (preprocessed)               0
cache miss                             3
cache hit rate                     99.40 %
called for link                        8
cleanups performed                     0
files in cache                      1063
cache size                          63.6 MB
max cache size                     100.0 MB
4.0K	/home/travis/build/bitcoin/bitcoin/depends/SDKs/
16K	/home/travis/build/bitcoin/bitcoin/depends/builders/
31M	/home/travis/build/bitcoin/bitcoin/depends/built/
24K	/home/travis/build/bitcoin/bitcoin/depends/hosts/
108K	/home/travis/build/bitcoin/bitcoin/depends/packages/
76K	/home/travis/build/bitcoin/bitcoin/depends/patches/
4.0K	/home/travis/build/bitcoin/bitcoin/depends/sdk-sources/
4.0K	/home/travis/build/bitcoin/bitcoin/depends/sources/
255M	/home/travis/build/bitcoin/bitcoin/depends/x86_64-pc-linux-gnu/
214M	/home/travis/build/bitcoin/bitcoin/releases/x86_64-pc-linux-gnu
```

**Comment by MarcoFalke** [comment]
valgrind passed in forked repo: https://travis-ci.org/github/MarcoFalke/bitcoin-core/jobs/676180248#L3100

valgrind run in this repo: https://travis-ci.org/github/bitcoin/bitcoin/jobs/676181073#L3107

**Review by hebasto — APPROVED** [review]
ACK faceeae49ae85fb644996fedb970ad9d0e297ca5, tested on my own repo: https://travis-ci.org/github/hebasto/bitcoin/jobs/676257500

**Comment by TBAALi-ros** [comment]
I'm not TBAALi 邮箱：jiaxx903@tom.com 签名由 网易邮箱大师 定制 On 04/18/2020 00:02, Hennadii Stepanov wrote: @hebasto approved this pull request. ACK faceeae, tested on my own repo: https://travis-ci.org/github/hebasto/bitcoin/jobs/676257500 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Review by jonatack — COMMENTED** [review]
Good idea.

ACK faceeae49

**Pull request merged**
