### PR TITLE
Fix timestamp in fee estimate debug message

### PR DESCRIPTION
**Pull request by morcos**
sorry @gmaxwell

### CODE REVIEW

**Comment by laanwj** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/10422/commits/8d4f401269fe6fb06df7137871b7e2e6368e080e

**Comment by fanquake** [comment]
utACK 8d4f401

**Comment by paveljanik** [comment]
utACK 8d4f401

**Review by ryanofsky — COMMENTED** [review]
utACK 8d4f401269fe6fb06df7137871b7e2e6368e080e

**Comment by TheBlueMatt** [comment]
utACK 8d4f401269fe6fb06df7137871b7e2e6368e080e

**Pull request merged**
