### PR TITLE
0.18: wallet: Fix -maxtxfee check by moving it to CWallet::CreateTransaction

### PR DESCRIPTION
**Pull request by promag**
Backports #16322 and #16257.

### CODE REVIEW

**Comment by Sjors** [comment]
ACK modulo the `wip:` commit messages. Description should mention this also backports #16257.

**Comment by promag** [comment]
Is this 0.18.2 then?

**Comment by fanquake** [comment]
> Is this 0.18.2 then?

Unless there happens to be an rc2, and this is merged in the interim, I think that will likely be the case.

Given that this is backporting to the `0.18` branch, instead of adding the `doc/release-notes-0.18.1-16257.md` file, can you just add the changes directly to `release-notes.md`? You might have to rebase, as the release notes have just been updated for 0.18.1.

**Comment by meshcollider** [comment]
Why is the commit message wip? Is this ready for review?

**Comment by promag** [comment]
Dropped wip prefix.

**Comment by Sjors** [comment]
ACK 7397275b4a7571eb09f2e16539b72b4354049b90

**Comment by fanquake** [comment]
This needs a rebase and the commits need the backport metadata (`Github-Pull:` & `Rebased-From:`) added. See the [backport.py](https://github.com/bitcoin-core/bitcoin-maintainer-tools/blob/master/backport.py) script.

**Comment by promag** [comment]
Ping.

**Comment by Sjors** [comment]
re-ACK d3b3bb8c9fb3a2ff1cd3a8776552c649aaf19dc2

**Comment by MarcoFalke** [comment]
ACK d3b3bb8c9fb3a2ff1cd3a8776552c649aaf19dc2 (did the backport myself, arrived at the same result)

<details><summary>Show signature and timestamp</summary>

Signature:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK d3b3bb8c9fb3a2ff1cd3a8776552c649aaf19dc2 (did the backport myself, arrived at the same result)
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEE+rVPoUahrI9sLGYTzit1aX5ppUgFAlwqrYAACgkQzit1aX5p
pUgocwv/bfvARaya5du9b8Tamq0D+dRpoy6FdepDukCHC8NvuekeIxucmHUz7LhJ
UdDwzVSL8v+VGSJ2G6FtLfEzMVJzYdZDak08yarUxJT5vHnxI91fULAvNbXG/+7l
3silywwBoei32t3v3WV/Lgth6xHIWHVumpyjLCJjvB3gp7amEbcKc9KqlvSTvYfg
EWRrtO2RVt7MRduI99m/b+FMuMBY83lkhMBjyFJpD7cmqGtN3WGxxw/IiY0Xu78y
bMt/ELGHTS3AgelOj4rEZwAiRHW+iCgEzHp0Mzn2OvaI6LzsNL0cU/5MKw+sFJzy
zTGOfWpKj+bXlZtpYwr2F9WDh0GF8Fw9RO/w6pjtulTxGbAeD6jtrz8ko99md8kh
RzzNaJrnlddu3fNPe0wGYDIG04eEJPl4ZLBmjmJ44F2m/A2o+/GOJdvs2kOPgfhL
4/JZb32CxJmFQwbYhd85TE3PBFtGQpUalKu/MS1Tx/TGI16kSdztgqkdkGbFWDsN
2zqsw7x9
=F6GX
-----END PGP SIGNATURE-----
```

[Timestamp of file with hash `95092eee457eb227f864af6a5b5dcb82a1ac2386c8b2dffd2bd4ed4ff7edade7  -`](https://opentimestamps.org/info/?004f70656e54696d657374616d7073000050726f6f6600bf89e2e884e89294010895092eee457eb227f864af6a5b5dcb82a1ac2386c8b2dffd2bd4ed4ff7edade7f01022dff40012fb072cc3b0aa110c1e3e0d08fff0102882f926cc5a2012746815d9310de47308f1045d88c97bf0083a52286fe38a28620083dfe30d2ef90c8e2c2b68747470733a2f2f626f622e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267fff010331be4ba1d5fd41d06958c81039c5eb108f1045d88c97bf008963b308cbb6d2ab10083dfe30d2ef90c8e232268747470733a2f2f6274632e63616c656e6461722e636174616c6c6178792e636f6dfff010ea7929945462d28d625c57b30e354f6808f1045d88c97bf00851d14dae50f680420083dfe30d2ef90c8e2e2d68747470733a2f2f616c6963652e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267f010f388085731416bb2c1a99af6ee4a20f008f1045d88c97cf0089c6460d72cec23bc0083dfe30d2ef90c8e292868747470733a2f2f66696e6e65792e63616c656e6461722e657465726e69747977616c6c2e636f6d)

</details>

**Pull request merged**
