### PR TITLE
[qa] 0.13.2 Backports

### PR DESCRIPTION
**Pull request by maflcko**

### CODE REVIEW

**Comment by MarcoFalke** [comment]
This also includes #9058 and thus, also the cleanup pull #8637.

**Comment by laanwj** [comment]
Commit-list-ACK

**Comment by sdaftuar** [comment]
ACK

**Comment by fanquake** [comment]
ACK, I think #9169 should be included as well?

**Comment by MarcoFalke** [comment]
I tried to focus on test fixes and necessary refactoring only in this pull and left the other backports ( https://github.com/bitcoin/bitcoin/pulls?utf8=%E2%9C%93&q=is%3Apr%20label%3A%22Needs%20backport%22%20 ) for later.

**Comment by laanwj** [comment]
New backports pull: #9264

**Pull request merged**
