### PR TITLE
doc: clarify that BDB is only required for the legacy wallet in build-unix.md

### PR DESCRIPTION
**Pull request by fanquake**

### CODE REVIEW

**Comment by Sjors** [comment]
ACK

**Review by darosior — COMMENTED** [review]
ACK 307215b6c5e4a4689fabb37f246a410767c8a3f4

**Comment by gruve-p** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/24608/commits/307215b6c5e4a4689fabb37f246a410767c8a3f4

**Comment by raywhite714** [comment]
could someone help me I received a file titled satoshi-bitcoin master

**Pull request merged**
