### PR TITLE
Update secp256k1 subtree to latest upstream

### PR DESCRIPTION
**Pull request by sipa**
It's been 1.5 years since our secp256k1 subtree was updated, while the upstream project has undergone a number of incremental improvements (performance, tests, build system fixes), plus gained the groundwork for batch verification.

As we're early in the 0.19 window, this seems like a good time to get these merged.

### CODE REVIEW

**Comment by fanquake** [comment]
This is waiting for https://github.com/bitcoin-core/secp256k1/pull/607 to be merged upstream.

**Comment by gmaxwell** [comment]
It has been, though more review of the changes overall would be welcome.

**Comment by sipa** [comment]
Updated to the latest upstream after merging  bitcoin-core/secp256k1#607.

**Comment by fanquake** [comment]
utACK 99df276 the subtree merge, still need to test the actual changes.

I've written some notes on verifying subtree merges [here](https://github.com/fanquake/core-review/blob/master/subtree-merge.md).

```shell
./contrib/devtools/github-merge.py 15703
[pull/15703/local-merge 12f00cb7a] Merge #15703: Update secp256k1 subtree to latest upstream
 Date: Mon Apr 1 09:09:24 2019 +0800
#15703 Update secp256k1 subtree to latest upstream into master
* 99df276da Update the secp256k1 subtree to the latest upstream version (Pieter Wuille) (pull/15703/head)
* 54245985f Squashed 'src/secp256k1/' changes from 0b70241850..b19c000063 (Pieter Wuille)

Dropping you on a shell so you can try building/testing the merged source.
Run 'git diff HEAD~' to show the changes being merged.
Type 'exit' when done.

git fetch https://github.com/bitcoin-core/secp256k1
warning: no common commits
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 4513 (delta 2), reused 6 (delta 1), pack-reused 4503
Receiving objects: 100% (4513/4513), 1.84 MiB | 335.00 KiB/s, done.
Resolving deltas: 100% (3157/3157), done.
From https://github.com/bitcoin-core/secp256k1
 * branch                HEAD       -> FETCH_HEAD

./test/lint/git-subtree-check.sh src/secp256k1
src/secp256k1 in HEAD currently refers to tree e862ca412860538b4969e6f77c8c005695e5ed28
src/secp256k1 in HEAD was last updated in commit 54245985fb3c89d72e285c4db39d38ed2f5fb0de (tree e862ca412860538b4969e6f77c8c005695e5ed28)
src/secp256k1 in HEAD was last updated to upstream commit b19c000063be11018b4d1a6b0a85871ab9d0bdcf (tree e862ca412860538b4969e6f77c8c005695e5ed28)
GOOD
```

**Comment by laanwj** [comment]
utACK 99df276da

**Comment by BIAgents** [comment]
git diff HEAD~'

**Pull request merged**
