### PR TITLE
[qa] Attach node index to test_node AssertionError and print messages

### PR DESCRIPTION
**Pull request by jamesob**
In the midst of fighting with https://github.com/bitcoin/bitcoin/pull/12873 it became apparent that there're a number of assertions and print statements which are emitted by test nodes but don't identify the node in question. This change makes debugging a bit easier by adding identifying information to non-logger test_node-related error messages.

### CODE REVIEW

**Comment by Empact** [comment]
utACK da93b39

A few style nits (ymmv):
* `_with_node_id` feels like an implementation detail to me. A name like `_node_msg` could be clear without being overly so.
* For `raise_assertion` - I'd either remove the indirection or apply it to all raises on the object, given they all use the node id treatment.

**Comment by jamesob** [comment]
@Empact thanks for the review. I've incorporated your good feedback.

**Comment by skeees** [comment]
concept ACK
might also be useful to print out the ports that each node{k} is on - afaict those aren't printed anywhere - and very useful as each bitcoind log identifies peer by a different index and the only way that i'm aware of to tie these to the python test framework indexing is by port num

**Comment by conscott** [comment]
utACK 80a5e59532925a3445f523a8b3bc29e2e11e8848

**Pull request merged**
