### PR TITLE
refactor: Lift prevector default vals to the member declaration

### PR DESCRIPTION
**Pull request by Empact**
I overlooked this possibility in #14028

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Are there any performance or other implications?

**Comment by Empact** [comment]
Main argument for this is that it is protective against another constructor being added but neglecting to initialize these vars properly.

**Comment by promag** [comment]
utACK d2eee87, change looks good because members are always initialized.

**Comment by 251Labs** [comment]
utACK d2eee87 nice one.

nit: perhaps initialize `_union` and `_size` with an empty initializer list `{}`:
`_size {};` `_union {};`.

**Comment by ken2812221** [comment]
utACK d2eee87928781ab3082d4279aa6f19641a45e801

**Comment by laanwj** [comment]
@sipa can you have a look at this please

**Comment by sipa** [comment]
@MarcoFalke I expect that this will have no effect on performance (the default initializers being invoked instead of delegating to the default constructor should do the exact same thing).

utACK

**Comment by practicalswift** [comment]
utACK d2eee87928781ab3082d4279aa6f19641a45e801

**Comment by practicalswift** [comment]
Current version has four utACK:s -- ready for merge? :-)

**Comment by Empact** [comment]
Five ;)

**Comment by scravy** [comment]
utACK d2eee87928781ab3082d4279aa6f19641a45e801

**Pull request merged**
