### PR TITLE
ui: make send a wizard 

### PR DESCRIPTION
**Pull request by Sjors**
Implements #16954 for the current functionality + #16944 (`gui: create PSBT with watch-only wallet`). This PR splits the send screen into three tabs, like a wizard.

This frees up UI real estate where we can add support for PSBT, hardware wallets and education.

I renamed `SendCoinsDialog` to `SendCompose` and `SendConfirmationDialog` to `SendSign`for clarity, which ended up (trivially) touching lots of `src/qt/locale/bitcoin_##.ts` files. This is contained in two move-only commits.

**Tab 1: Draft**

Schermafbeelding 2019-09-26 om 15 59 16

Same as the current send screen: enter destination, do coin selection, set fee etc. This can be split further in future PRs for a less cluttered experience, e.g. one tab for coin selection (if enabled), one for destination(s) and one for fees. Having a separate tab for fees also provides an entry point for RBF, which currently doesn't let the user pick an amount. 

**Tab 2: Sign**

This asks to unlock the wallet if needed.

Schermafbeelding 2019-09-26 om 16 14 42

Display transaction details like the current popup does. 

Schermafbeelding 2019-09-26 om 15 59 35

Edit jumps back to Draft. Send jumps to Finish, unless something goes wrong.

Bump fee jumps straight to this tab:
sign

For watch-only wallets it displays the same text as #16944.

**Tab 3: Finish**

Schermafbeelding 2019-09-26 om 16 08 21

This is where the actual broadcast takes place, or where the PSBT is copied to the clipboard. In a followup we can add support for saving the PSBT to disk, or for copying a signed transaction hex to clipboard if the user wants to broadcast that elsewhere. 

Bump fee shows both the previous and new transaction index:
sent

The manual "Show" button has the nice side-effect of fixing #16875 / #16876 in two out of three places. 

---

Todo:
- [ ] clean up WalletModelTransaction and CoinControl object passing mess
- [x] restore test

Followups:
* add PSBT export to Sign tab (extract from gwillen's branch https://github.com/gwillen/bitcoin/tree/feature-offline-v2, i.e. redo #16944)
* add Load PSBT menu option, jump to Broadcast tab if complete, otherwise to Sign tab
* list connected hardware wallets in Sign tab (redo #16549 
* split fee selection into its own tab
* allow custom RBF amounts: bump fee should jump to fee selection tab

### CODE REVIEW

**Comment by promag** [comment]
Concept ACK. Not sure if the tab view is the best container for the send wizard. Have you considered back/next buttons?

**Comment by gwillen** [comment]
I went back and for myself on the view style and ultimately did settle on a tab view. Ultimately there's never actually a need to press the Back and Next buttons unless you're doing something wrong (or a trivial demo) -- each step of the process will happen on a different machine.

I like the idea of a "load PSBT" menu item taking you to the right tab. In my implementation, there is an "offline" menu from which you have to select "sign" or "broadcast" to open the dialog to the right tab; then you load from there.

There's a lot of stuff that came up in the process of implementing this which I don't know if you've run into yet. For example, the signing wallet may not be able to put up the usual form of the confirmation display, as shown here, unless it has some trustworthy way to know which output is change, which it doesn't except maybe if you're using descriptors to tell it so.

Jumping back to Draft, much like having back/next buttons, is probably mostly not going to get used in real life, where the signing is happening on a different machine from the drafting. Honestly I think the main reason to have the steps of this flow be one dialog are to help the user have a sense of their place in the process, even though I expect probably they will be mostly used separately and on separate machines.

**Comment by Sjors** [comment]
> the signing wallet may not be able to put up the usual form of the confirmation display, as shown here, unless it has some trustworthy way to know which output is change, which it doesn't except maybe if you're using descriptors to tell it so.

I have a hardware wallet GUI PR #16549 which is built on top of native descriptor wallets #16528.

I'm also thinking of replacing `WalletModelTransction`, which is a QT-only thing, with PSBT. But perhaps that's better for a followup.

Re tab view: I briefly looked at [QWizard](https://doc.qt.io/qt-5/qtwidgets-dialogs-classwizard-example.html) but that doesn't give the user an overview of where they are in the flow. The good news is that [QTabWidget](https://doc.qt.io/qt-5/qtabwidget.html) can easily be swapped with [QStackedWidget](https://doc.qt.io/qt-5/qstackedwidget.html) which can be completely customized, e.g. into something like this:

Schermafbeelding 2019-09-26 om 10 37 33

I'll probably disable the other tabs, so that all "navigation" happens through the buttons at the bottom of the screen.  

> I expect probably they will be mostly used separately and on separate machines

I'm thinking more of the hardware wallet use case. In the simplest configuration of 1 hardware wallet that's physically connected, the Sign tab is a nice place to show it. In case of something like ColdCard or the new BitBox this is where you would save the unsigned PSBT to SD drive.

**Comment by Sjors** [comment]
Added RBF

**Comment by hebasto** [comment]
Concept ACK

**Comment by Sjors** [comment]
`qt/wallettests.cpp` breaks because the `transactionTableModel` doesn't update after the transactions are created. @promag could this be related to https://github.com/bitcoin/bitcoin/pull/16876#issuecomment-532665908?

**Comment by Sjors** [comment]
`NotifyTransactionChanged` in `WalletModel` calls `updateTransaction` using a `Qt::QueuedConnection`. That caused the test to fail.

**Comment by promag** [comment]
@Sjors try like this https://github.com/bitcoin/bitcoin/pull/16876/files#diff-6fcb1829ce66ad65046d6896dbcc910bR73

**Comment by Sjors** [comment]
@promag added.

For some reason the Travis `nowallet` build is failing, but I can't reproduce:
```
D__STDC_FORMAT_MACROS  -fstack-reuse=none -Wstack-protector -fstack-protector-all      -fPIE -pipe -O2  -fvisibility=hidden -c -o qt/qt_libbitcoinqt_a-moc_sendcompose.o `test -f 'qt/moc_sendcompose.cpp' || echo './'`qt/moc_sendcompose.cpp
2790In file included from ./wallet/walletdb.h:12:0,
2791                 from ./wallet/wallet.h:23,
2792                 from ./wallet/coincontrol.h:11,
2793                 from ./qt/sendcompose.h:14,
2794                 from qt/moc_sendcompose.cpp:8:
2795./wallet/db.h:24:10: fatal error: db_cxx.h: No such file or directory
2796 #include <db_cxx.h>
2797          ^~~~~~~~~~
2798compilation terminated.
2799make[2]: *** [qt/qt_libbitcoinqt_a-moc_sendcompose.o] Error 1
```

**Comment by Sjors** [comment]
Travis is happy. TIL that `build_msvc/libbitcoin_qt/libbitcoin_qt.vcxproj` isn't auto generated, so I had to update that as well. Now AppVeyor is happy too.

I'm probably going to add a SendWidget class to share common code between the tabs. I might also replace `unique_ptr` with `shared_ptr` as the current passing the baton approach seems a bit brittle.

**Comment by luke-jr** [comment]
Concept NACK. Sorry, this looks ugly, much worse than the current flow.

(Also, normal users probably shouldn't see txids...)

**Comment by Sjors** [comment]
That's subjective. I think it looks better, because it's less cluttered and gets rid of a popup. Happy to hide the transaction id.

The current sign screen (which is a popup) doesn't have space to list hardware wallets. There's also not much room for PSBT creation and/or signing, other than just magically putting it on a clipboard (see #16944). If you have a better design I'd love to see it.

**Comment by luke-jr** [comment]
> If you have a better design I'd love to see it.

To be clear, I think the current design with popup is better...

**Comment by michaelfolkson** [comment]
> This frees up UI real estate where we can add support for PSBT, hardware wallets and education.

Concept ACK on motivation for this. I don't have a view on its ugliness. For these UI redesigns it seems totally dependent on the regular users of the GUI. Personally I support the goal of the GUI being an educational stepping stone to using the CLI. There will be always be better GUIs for the non technically curious which aren't subject to the constraints of Core.

**Comment by luke-jr** [comment]
My view is almost entirely the opposite: The JSON-RPC server isn't meant for end users, but for software developers to interface with. The GUI is the primary method for end users to use Bitcoin Core, not some mere "stepping stone" to a half-baked JSON-RPC client...

P.S. In addition to being a developer, I am a regular user of the GUI.

**Comment by Sjors** [comment]
I think @michaelfolkson was referring to having independently developed wallet applications that use the RPC (somewhat limited atm) or IPC (#10102). I use the GUI as well.

**Comment by michaelfolkson** [comment]
I'm not entirely sure who this GUI is being designed for. Long time contributors like Sjors, Luke? Complete Bitcoin beginners? Someone like me who is technically curious and would ideally want to transition from any reliance on the GUI? All of us? (fiendishly difficult as you are making design compromises all over the place). 

If it is complete Bitcoin beginners then none of us are the target audience. But this is a meta point and this discussion has probably been rehashed multiple times over the years so I won't clog up this PR with it.

**Comment by Rspigler** [comment]
> Concept NACK. Sorry, this looks ugly, much worse than the current flow
> To be clear, I think the current design with popup is better...

What current design allows you to generate PSBT's from the GUI of offline versions of Bitcoin Core for secure multisig?  AFAIK, https://github.com/bitcoin/bitcoin/pull/16944, https://github.com/bitcoin/bitcoin/issues/16954, and this PR are the only discussions/PRs around this (https://github.com/bitcoin/bitcoin/pull/16546, https://github.com/bitcoin/bitcoin/pull/16549, and https://github.com/bitcoin/bitcoin/pull/16895 for HWWs).

The UI isn't beautiful (neither is the rest of Core), but it's not ugly.  And I don't believe that's the point, especially from reading #17395, that seems to be the consensus.  The point is to be secure, power-user friendly, and mistake-minimizing.

**Comment by michaelfolkson** [comment]
> And I don't believe that's the point, especially from reading #17395, that seems to be the consensus. The point is to be secure, power-user friendly, and mistake-minimizing.

Do you agree with that @luke-jr? Feel free to comment on #17395 if you do/don't.

**Comment by Sjors** [comment]
Closing this in favor of more incremental changes, e.g. #17509.

**Pull request closed without merging**
