### PR TITLE
[net] remove an obscure macro used in CNode::copyStats

### PR DESCRIPTION
**Pull request by Diapolo**
- no code change

### CODE REVIEW

**Comment by laanwj** [comment]
Original code seems fine to me too. No strong opinion for or against this.

**Comment by luke-jr** [comment]
Seems like it'd be cleaner to just add a CNodeStats to CNode.

**Comment by laanwj** [comment]
@luke-jr That indeed sounds like a very clean solution. If indeed every field is copied, I don't see any immediate drawbacks.

**Comment by sipa** [comment]
ACK Luke's idea.

**Comment by laanwj** [comment]
@diapolo Are you going to do this?

**Comment by Diapolo** [comment]
I guess the proposed change could also requires some changes in rpcconsole and peertablemodel? Perhaps another dev takes a look at it, if we want to hurry... otherwise I'm going to look into this after the weekend.

**Comment by Diapolo** [comment]
@sipa @laanwj Please see squashme commit, so I can be sure that is the direction you wanted.

**Comment by jgarzik** [comment]
meh.  Code goes from clean to less clean.

**Comment by Diapolo** [comment]
I was asked to do so, but perhaps I did it the wrong way? We need to wait for @laanwj @luke-jr and @sipa to see their comments.

**Comment by sipa** [comment]
Not what I meant.

I meant removing the CNode values that are also in CNodeStats from CNode, and replacing them with a nodestats field. GetStats would then just return a copy of the nodestats field.

**Comment by Diapolo** [comment]
@sipa Well, ``nodestats`` is just the name of the CNodeStats that you wanted me to add to the CNode class, right? So mine is currently named stats. Only thing that differs is that I guess you wanted me to remove or rework ``CNode::copyStats()`` so that it returns a CNodeStats copy. Is this correct?

**Comment by sipa** [comment]
I meant moving all statistics into it, include nLastSend etc.

**Comment by Diapolo** [comment]
@sipa Right, as I've written I just wanted to be sure my change goes into the right direction (that's why I only included nServices).

**Comment by laanwj** [comment]
As this trivial issue appears to be controversial, I think it's not worth spending more time on. The original code is already clear in intent.

**Pull request closed without merging**
