### PR TITLE
[docs]: include README with binary releases

### PR DESCRIPTION
**Pull request by Varunram**
Intended as a fix for: #8160 
Suggestions welcome for a better file name, I couldn't think of any better ones, so went ahead with this. This file is more like a combination of the main readme at `doc/README` and some dev docs.

### CODE REVIEW

**Comment by laanwj** [comment]
Thanks for your contribution, but this overlaps almost 100% with the existing `README.md` and `doc/README.md` with regard to content.

We should probably remove the content from there to make sure there is no overlap, or just add pointers to there instead.

What I meant in #8160, sorry if I was unclear, is that a README file should be part of the installation. That is still not the case after this, as it is a build system/packaging change.

**Comment by Varunram** [comment]
I agree, this is an overlap as I mentioned at the description. But I don't quite get what you mean by "should be part of the installation" (pardon me if I'm being a little noob-ish). If you could elaborate more, that'd be nice. Thanks!

**Comment by laanwj** [comment]
> But I don't quite get what you mean by "should be part of the installation" (pardon me if I'm being a little noob-ish)

I mean it should be part of the distributions generated by gitian.
They are built by scripts, e.g. https://github.com/bitcoin/bitcoin/blob/master/contrib/gitian-descriptors/gitian-linux.yml

**Comment by fanquake** [comment]
Closing, as this PR doesn't currently fix #8160.

**Pull request closed without merging**
