### PR TITLE
Removed contrib/bitrpc

### PR DESCRIPTION
**Pull request by casey**
It's unclear if people are using this and if it's worth maintaining. The script has some problems, as mentioned in pr #5360.

This "fixes" issue #6500

### CODE REVIEW

**Comment by laanwj** [comment]
ACK

**Comment by laanwj** [comment]
Nit: mention also needs to be removed from `contrib/README.md`

**Comment by casey** [comment]
Removed from contrib/README.md

**Comment by fanquake** [comment]
ACK after squashing

**Comment by casey** [comment]
Squashed!

**Comment by jonasschnelli** [comment]
ACK

**Pull request merged**
