### PR TITLE
MOVEONLY: Consensus: Move most of consensus functions (pre-block)

### PR DESCRIPTION
**Pull request by jtimon**
Dependencies:
- ~~MOVEONLY: Move constants to consensus.h #5696~~
- ~~Separate CValidationState from main #5669~~
- ~~Consensus: Refactor: Separate CheckFinalTx from main::IsFinalTx #6063~~
- ~~Consensus: Decouple ContextualCheckBlockHeader from checkpoints #5975~~
- ~~Separate Consensus::CheckTxInputs and GetSpendHeight in CheckInputs #6061~~

I'm sorry for killing commit ids and creating new PRs so easily around this, but I really needed to explore different ways serializing/parallelizing  this. And my conlusion is that everything gets more readable if we do the moveonly first, it is specially important for libconsensus API proposals and how could they potentially change bitcoin core's storage more readable.
Since Script is already exposed, I think the remaining types to be verified by libconsensus are: Transaction, BlockHeader and Block.

For each one of them we will want to expose a full verification function. Additionally, we may want to expose checks in phases, for example, in the way that is already separated in bitcoin core, mostly to prevent DoS attacks and to put policy checks in between (ie: context-less checks before storage-dependent checks, expensive script validation the last thing, etc). I don't think the intermediary checks will generate a lot of discussion, since if we can reach the full validation version for each of the types with proper C APIs, exposing any subset of the checks will probably be easy. So I will focus on the full validation functions for now and calling them VerifyTx, VerifyHeader and VerifyBlock respectively.

But this is not moving everything necessary for libconsensus. Before it is possible for libconsensus to expose full block verification, it has to be able to verify block headers and transactions independently. 
So we know VerifyBlock comes after VerifyTx and VerifyHeader, but we don't know whether VerifyTx or VerifyHeader will be ready first. Because they depend on discussions about CCoinsViewCache and
CBlockIndex respectively about how to expose its storage, which may require or fit well with structural changes in how bitcoin core stores them, for example, if UTXO commitments are going to be softforked in some way, the API for VerifyTx should be forward compatible with that, which may delay its exposure.

And because we don't want to unnecessarily make libbitcoin bigger unless something more it's going to be exposed, I thought that having two cpp files could be useful, I named them txverify.cpp and blockverify.cpp but it's open to bikesheding. The point is that when one is ready you can add it to libconsensus while leaving the other in the server building module. 

Once they're both ready, a last moveonly commit after this one will be required to expose a C API for full block rule validation, that new code can go in blockverify.cpp

The intention of moving all the function declarations that we know we will need (for example, main::CheckBlock) without moving the actual code to a cpp in the same commit is to minimize the number of include restructuring commits, they can all be done right after this PR.
Alternatively the block declarations can be delayed, but I believe that it's worth it to move all transaction and header declarations in the same commmit since it doesn't take that much to move it all fast (see the non-moveonly commits in this PR, they're quite trivial).

### CODE REVIEW

**Comment by jtimon** [comment]
Closing until #5696 is resolved

**Comment by laanwj** [comment]
Are you sure GetBlockProof is not part of consensus? e.g. it's used in `AddBlockToIndex` to determine the total amount of work on a chain. 
It's the only function left in `pow.h` which is kind of unfortunate.

**Comment by jtimon** [comment]
The highest level function I'm contemplating would be VerifyBlock and that's not necessary for it. It's certainly not necessary for VerifyHeader. That's used to chose the longest chain, so it's seems more part of the index than validation rules. Maybe in the future we can expose that too somehow, but one step at a tine...

**Comment by laanwj** [comment]
But `nChainWork` is used in e.g. `ActivateBestChain(Step)`, which choose the best chain.
@cfields what's your opinion here?

**Comment by sipa** [comment]
Depends on whether we define consensus as (conceptually) a black box that just says whether a particular chain is valid or not, or whether we include the mechanism for determining which of possible valid chains as well.

I don't really have an opinion here, apart from that I think separating these two concerns in the code makes sense - whether we expose that in libconsensus or not.

**Comment by laanwj** [comment]
Ok fair enough. But I do think this destroys the purpose of `pow.cpp`/`pow.h`. The goal was to have the proof-of-work functions in one place. Now *one function* is left in that file...

**Comment by jtimon** [comment]
well yes, my plan was to destroy pow and move the remaining function to chain.o, but zince there's more stuff being created there...

**Comment by faizkhan00** [comment]
Built and ran tests ACK

**Comment by jtimon** [comment]
Rebased

**Comment by jtimon** [comment]
Rebased with one less dependency (2 commits less).

**Comment by jtimon** [comment]
Rebased again. 
Only 2 PR dependencies to go, ping  #5975 and #6061.

**Comment by jtimon** [comment]
Needed rebase

**Comment by jtimon** [comment]
Rebased. All PR dependencies merged or replaced with equivalent commits.
Now this is purely move only.

**Comment by jtimon** [comment]
Squashed the 2 moveonly commits.

**Comment by theuni** [comment]
Confirmed move-only with the exception of
```diff
-    set<COutPoint> vInOutPoints;
+    std::set<COutPoint> vInOutPoints;
```
which is obviously fine.

I didn't bother checking includes and function prototypes though.

**Comment by jtimon** [comment]
Rebased

**Comment by jtimon** [comment]
I'm having second thoughts about txverify.cpp + blockverify.cpp vs policy.cpp.
If we don't care about exposing verifyTx or verifyHeader before verifyBlock is ready, then we can just have policy.cpp and we can move more things at the same time (CheckBlock, ContextualCheckBlock and GetBlockSubsidy, for example).

Do we care about being able to expose VerifyTx without being prepared to also expose VerifyHeader and VerifyBlock?
Do we care about being able to expose VerifyHeader without being prepared to also expose VerifyBlock?

Thoughts?

**Comment by jtimon** [comment]
Closing for now.

**Pull request closed without merging**
