### PR TITLE
Relay first double-spend as alert, notify wallet

### PR DESCRIPTION
**Pull request by dgenr8**
Relay at most one double-spend per unspent output, subject to anti-DoS provisions.

Unconfirmed double-spends carry information that is time-critical to the payee of the first spend, but today, they are silently dropped.

Add a -respendnotify option that can immediately notify a user-supplied command when a double-spend affecting the wallet is received.

Change the GUI wallet to highlight a transaction in red when a transaction that double-spends it has been seen.  When the conflict first occurs, display a warning dialog.

alertshot

This change has been running on mainnet since 2014-05-02.  Relayable double-spends seen by the change are [recorded here](http://respends.thinlink.com) in realtime.

### CODE REVIEW

**Comment by dgenr8** [comment]
Travis check failure is due to this PR fixing a bug which is relied on by test [txn_doublespend.py](https://github.com/bitcoin/bitcoin/blob/master/qa/rpc-tests/txn_doublespend.py#L113).  I'm thinking of updating this PR to remove txn_doublespend.py since the included doublespendrelay.py tests detection plenty, and does not depend on the accounting system.

**Comment by jonasschnelli** [comment]
needs rebase.

**Comment by dgenr8** [comment]
Thanks @jonasschnelli, rebased.  The build check problem will clear up if #5881 is merged.

**Comment by luke-jr** [comment]
Some serious problems with this still: respend checking is performed after IsStandard , so a fraudster need only craft his transactions carefully to defeat this entirely; if the order of this is inverted, you then create a situation where it encourages people who want to send real non-IsStandard transactions to do so as a double spend. I think the only way to resolve this is to remove IsStandard from the policy entirely (and hope enough nodes continue to run with this policy). This is potentially very dangerous.

Furthermore, it appears an attacker can flood the network with double-spends in order to rate limit relaying of some of them. I also see no efforts made to consider the relay costs: since these are double spends, only one or the other will confirm, and thus the fee from the non-confirming one is never paid.

**Comment by dgenr8** [comment]
@luke-jr First to catch up, the "wait for confirmation" part of the alert dialog message was removed.  You're right, it's best to stick to the facts.

You are also correct that this change does not secure unconfirmed spends, and as currently written,  does not help in the construction of a system that does.

What this change claims to do, and does, is to stop delaying the moment when interested parties can discover relayable double-spends.  The wallet portion also serves the important function of notifying the user of *successful* double-spends.

Even people with diametrically opposite views on whether unconfirmed transactions can ever gain more reliability agree that relaying double-spends, when possible, is an improvement.  The reason is that they happened, and that is useful information.

**Comment by dgenr8** [comment]
Rebased.  There is a question of where to put the equivalent-tx-check function.  At the moment there are identical versions in CTransaction and CWalletTx.  See #6365.

**Comment by jgarzik** [comment]
Observations on this pull request:
* Zero ACKs after a year
* Discussion on mailing list, here and IRC indicates concerns remain

Going to close.  That is perhaps mildly controversial given the current core/xt code fork debates, but it seems within bounds of reasonable project management.

We can re-open if ACKs suddenly appear or concerns are alleviated, etc.  The overall motivation is simply janitorial, closing pull requests that aren't moving after a long time.

**Pull request closed without merging**
