### PR TITLE
rpc: remove info about mallocinfo needing glibc 2.10+

### PR DESCRIPTION
**Pull request by fanquake**
We require glibc 2.18+.

### CODE REVIEW

**Comment by shaavan** [comment]
@fanquake 
It would greatly help if you explained why you made the changes the way you created them.
For example, you might have changed from:
```
"mallocinfo is only available when compiled with glibc 2.10+"
```
to
```
"mallocinfo is only available when compiled with glibc 2.18+"
```
So why did you prefer not to mention `glibc` at all?

**Review by jarolrod — COMMENTED** [review]
ACK 9a09d307e9bd81ed218dd560d3eac7565f1f7a2f

@shaavan I think you have a misconception with your comment. mallocinfo does not *need* glibc2.18. We require glibc2.18+ to build Bitcoin Core (since #23511). 

The current comment is more information than is needed. If a user has built Bitcoin Core with < glibc2.10, then they most likely made that choice explicitly. They don't need to be reminded about what situations it would be available, nor is it our job.

**Comment by fanquake** [comment]
> For example, you might have changed from:
> to

That wouldn't be correct. `malloc_info` was added to glibc in [version 2.10](https://man7.org/linux/man-pages/man3/malloc_info.3.html).

> So why did you prefer not to mention glibc at all?

Warning that a certain feature is only available if you're using glibc 2.10+, is redundant if our binaries already require 2.18+.

**Review by shaavan — APPROVED** [review]
Thank you, @jarolrod and @fanquake, for correcting my assessment of this PR.
I understand now that mentioning about gilbc version in this error message is redundant information and needs to be edited out.

ACK 9a09d307e9bd81ed218dd560d3eac7565f1f7a2f

**Pull request merged**
