### PR TITLE
WIN32 Seed Cleanup

### PR DESCRIPTION
**Pull request by ghost**
WIN32 cleanup of RandAddSeedPerfmon.

### CODE REVIEW

**Comment by gmaxwell** [comment]
What is the purpose of this change.  The current behavior is intentional.

**Comment by 21E14** [comment]
@gmaxwell Please, do tell. The change introduced here is self-evident, the current intent is less so.

**Comment by gmaxwell** [comment]
I  misread the diff and thought you were moving the ifdef WIN32 above the randaddseed(), and thought your goal was to remove all non-urandom sources of entropy from the pool. (which would be unfortunate considering the frequent dev/random failures https://lists.freebsd.org/pipermail/freebsd-current/2015-February/054580.html  )

Please provide a commit message in the future.

**Comment by 21E14** [comment]
'WIN32 Seed Cleanup' is the commit message, but certainly not opposed to a more in-depth exposé of your choosing.

**Comment by paveljanik** [comment]
ACK
What about:
Remember the last time of performance data use on Windows only.

**Comment by laanwj** [comment]
If you propose a change to the code, the burden of explaining why it is useful is up to you. Something may look 'self-evident' to you but it may not be to others.

That said, ACK after adding a more explanatory commit message.

**Comment by gmaxwell** [comment]
The message I would have written would be:

"Move nLastPerfmon behind win32 ifdef.
Code to avoid calling Perfmon too often is only needed when perfmon is actually going to get called.
This is not intended to make any functional difference in the addition of entropy to the random pool."

**Comment by 21E14** [comment]
The commit message has now been updated accordingly.

**Comment by gmaxwell** [comment]
utACK.  Thanks!

**Comment by laanwj** [comment]
Thanks, ACK

**Pull request merged**
