### PR TITLE
Prefer using std::numeric_limits to C

### PR DESCRIPTION
**Pull request by philmb3487**
This fixes compilation under DragonFlyBSD.

### CODE REVIEW

**Comment by theuni** [comment]
This is not our code, so we're best off not modifying it is possible. Best options imo are either:
- define ```__STDC_LIMIT_MACROS``` for the leveldb build, which should get ```SIZE_MAX``` defined
- push this change upstream and catch it on the next sync

**Comment by sinetek** [comment]
The inclusion of leveldb made me think it has been modified. I agree it would be better to modify the Makefile, something like -D__STDC_LIMIT_MACROS. ?

**Comment by sinetek** [comment]
That brings us to the same position because the Makefile is part of leveldb.

**Comment by theuni** [comment]
For the hard-coded approach:
```diff
diff --git a/src/Makefile.am b/src/Makefile.am
index 37184b6..aed47db 100644
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -14,7 +14,7 @@ $(LIBLEVELDB): $(LIBMEMENV)
 $(LIBLEVELDB) $(LIBMEMENV):
        @echo "Building LevelDB ..." && $(MAKE) -C $(@D) $(@F) CXX="$(CXX)" \
          CC="$(CC)" PLATFORM=$(TARGET_OS) AR="$(AR)" $(LEVELDB_TARGET_FLAGS) \
-          OPT="$(CXXFLAGS) $(CPPFLAGS)"
+          OPT="$(CXXFLAGS) $(CPPFLAGS) -D__STDC_LIMIT_MACROS"
 endif
 
 BITCOIN_CONFIG_INCLUDES=-I$(builddir)/config
```

**Comment by sinetek** [comment]
Works.

**Comment by laanwj** [comment]
You should still aim to get this merged upstream; apparently it doesn't support DragonFlyBSD at the moment.

**Comment by laanwj** [comment]
utACK in any case - until the issue is resolved upstream

**Comment by sinetek** [comment]
I'll see if I can push upstream too.

**Comment by sinetek** [comment]
There must be a difference in the build systems, as upstream compiles fine.

g++ -I. -I./include -std=c++0x -fno-builtin-memcmp -D_REENTRANT -DOS_DRAGONFLYBSD -DLEVELDB_PLATFORM_POSIX -DLEVELDB_ATOMIC_PRESENT -O2 -DNDEBUG -c helpers/memenv/memenv.cc -o helpers/memenv/memenv.o

**Comment by laanwj** [comment]
Ok that's strange, I wonder why it would be needed here then. Maybe because we override the CFLAGS?

**Comment by laanwj** [comment]
@theuni any idea what could be the issue here? according to @sinetek the upstream leveldb compiles fine, do our overrides create this issue then?

**Comment by theuni** [comment]
I'm not sure what could be causing the difference. We could defined the freebsd/openbsd/dflybsd targets in configure and pass them on to leveldb (which we should do, to fix cross builds), but they should be correctly detected for native builds already.

@sinetek could you please paste the failing compile-line so that we can see the difference? My only guesses are that we somehow define a different target, or our flags make the -std=c++0x change fail so that we build in c++98 mode.

**Comment by laanwj** [comment]
Going to merge this. Normally a build fix for a platform should only affect that platform, but I'm reasonably confident that it won't have adverse effects on other platforms.

**Pull request merged**
