### PR TITLE
lint: Fix spelling errors in comments

### PR DESCRIPTION
**Pull request by fyquah**
Found some spelling errors while running spelling linter  https://github.com/bitcoin/bitcoin/pull/21245 

This PR fixes them.

### CODE REVIEW

**Comment by practicalswift** [comment]
@fyquah

Luckily spelling errors cannot cause CI to fail, so you must have hit another issue in the PR you're referencing :)

With that said: Cnocept AKC on fiixng the speling erorrs! :)

**Comment by hebasto** [comment]
> With that said: Cnocept AKC on fiixng the speling erorrs! :)

:)

**Comment by fyquah** [comment]
> diff --git a/src/core_io.h b/src/core_io.h
> @@ -22,0 +23,7 @@ class CTxUndo;
> +
> ^---- failure generated from test/lint/lint-whitespace.sh
> ```

Turns out I wasn't able to capture this because I was using a custom diff tool with git  🤔

**Review by fanquake — APPROVED** [review]
ACK fbbb2d4fc13971c98c83a51635166ac532e71a32 - I thought we just fixed all of these.

**Pull request merged**
