### PR TITLE
fuzz: Use ConsumeWeakEnum in addrman for service flags

### PR DESCRIPTION
**Pull request by maflcko**
This has minimally better performance. Reported by me in https://github.com/bitcoin/bitcoin/pull/20228#discussion_r598081787

### CODE REVIEW

**Comment by MarcoFalke** [comment]
I am also thinking about renaming this to `ConsumeEnumFlags` to better reflect what it does, but maybe this can be done later or the existing name is fine already?

**Comment by practicalswift** [comment]
Concept ACK on both using `ConsumeWeakEnum` and renaming it `ConsumeEnumFlags`.

Better naming will be helpful for future generations of Bitcoin Core fuzzing enthusiasts, and `ConsumeEnumFlags` sure is a better name :)

**Comment by practicalswift** [comment]
Tested ACK 55554463c15e3c75a64d26209dd3f8396e508cc2

**Review by vasild — APPROVED** [review]
ACK 55554463c15e3c75a64d26209dd3f8396e508cc2

I think the existent name "...weak...()" is good because the function may return a completely arbitrary value that is not in the enum. `ConsumeEnumFlags()` may give the wrong impression that it only returns enumerated values.

**Comment by MarcoFalke** [comment]
Though, "weak" could also be interpreted as "weakly typed enum", meaning a non-C++11 "strongly typed enum". But this interpretation would be wrong because flags can also be implemented with strongly typed enums. Maybe there is a better name that we haven't yet thought of?

**Comment by MarcoFalke** [comment]
On really verbose name could be `ConsumeUnderlyingTypeEnum`?

**Comment by MarcoFalke** [comment]
```
[09:35] <vasild> MarcoFalke: maybe ConsumeEnumOrRandom() better describes it?

**Pull request merged**
