### PR TITLE
rpc: Accept strings in AmountFromValue

### PR DESCRIPTION
**Pull request by laanwj**
Accept strings containing decimal values, in addition to bare values.

note: untested

### CODE REVIEW

**Comment by jgarzik** [comment]
Context?  Zero explanation of "why"

**Comment by laanwj** [comment]
Useful from JSON-RPC implementations where it's not possible to have direct control over the text of numbers (e.g. where numbers are always doubles), and it's still desired to send an exact value.

**Comment by laanwj** [comment]
See also  #3759 for previous discussion - I hadn't thought any more context was necessary here.

**Comment by jgarzik** [comment]
@laanwj Someone looking at the git commit will have no idea about any of that background context...

Commit messages should answer "why?" not just "what?"

**Comment by laanwj** [comment]
Ok, don't feel like this discussion, closing...

**Comment by jonasschnelli** [comment]
Hmm.. i think this is useful.
For the new wallet i did implement something similar (`val.setNumStr(val.get_str());` see -> https://github.com/jonasschnelli/bitcoin/blob/2015/05/corewallet/src/corewallet/corewallet_rpc.cpp#L109).

This would allow users to post JSON content with encoded numbers like `{"value": "0.00000001"}` instead of `"value": {0.00000001}` which some php/python encoders wrap into `1e-8`.

**Comment by laanwj** [comment]
@jonasschnelli Yes, that's exactly the idea.

**Comment by luke-jr** [comment]
As a reminder, the conclusion from #3759 was to use satoshi/integer Numbers, not to stringify...

**Comment by laanwj** [comment]
@luke-jr But that would be a major API change, while this could be used today and does not introduce any 1 satoshi versus 1 BTC magnitude risk.

**Comment by jonasschnelli** [comment]
I think using `int` Satoshis for all values in RPC would make sense. But as @laanwj said, this would be a major API change with many risks. And i also think that people are "thinking" in BTC rather then in Satoshis. Somehow this is a legacy we have to deal with.

Nevertheless this PR would also be a slightly API change. In the current releases (before UniValue) and in the current master, numbers encapsulated in string did made bitcoind throwing an exception.

UniValue internally stores everything as a string, that's why i think this PR makes sense and can be seen as a save solution. The only risk i see is that it could be possible that API users/apps expect that sending a string where a btc value is required will thrown an error.

**Comment by morcos** [comment]
I like this pull as well.  We fixed the JSON parsing in #6379 , but what's to say somebody won't be dealing with a broken JSON composer on their end.  This provides a nice safe alternative.

ACK

**Comment by jgarzik** [comment]
ACK.  Thanks for updating the commit.

**Comment by sipa** [comment]
ACK. We shouldn't forget to mention this in release notes if it gets merged.

**Comment by laanwj** [comment]
Yes, and needs to be exercised at least once in the RPC tests as well.

**Comment by jonasschnelli** [comment]
Tested ACK.
RPC test extension for `wallet.py` : https://github.com/jonasschnelli/bitcoin/commit/39b44374f78891839d1488133e9a2c3a60ad44e7

**Comment by laanwj** [comment]
Cherry-picked @jonasschnelli 's test. Thanks!

**Comment by laanwj** [comment]
Added small mention in release notes.

**Comment by jonasschnelli** [comment]
reACK

**Pull request merged**
