### PR TITLE
[0.18] doc backports

### PR DESCRIPTION
**Pull request by fanquake**
Backports #15684, #15792, #15802,  #15809 to the `0.18` branch.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Could include #15799?

**Comment by fanquake** [comment]
> Could include #15799?

Added.

**Comment by jonatack** [comment]
Possibly wait for https://github.com/bitcoin/bitcoin/pull/15607 if it makes it in :)

**Comment by MarcoFalke** [comment]
@jonatack maintainer processes are only relevant (or sufficient) on the master branch

**Pull request merged**
