### PR TITLE
 [wallet] Round up to the next satoshi on odd fee rates 

### PR DESCRIPTION
**Pull request by maflcko**
This requires  #7660 to work.

You can already review this by just looking at 1923bb1 but I will rebase once #7660 is merged.

I consider the priority low on this, as this only happens with really small fee rates like 1 satoshi per kB, as mentioned in https://github.com/bitcoin/bitcoin/pull/4465#issue-37199263

### CODE REVIEW

**Comment by morcos** [comment]
@MarcoFalke I think this is going the wrong direction with making `CFeeRate` more convoluted.
I think we could get rid of that $&$*! special case for 0, and be fine with the truncated version, or round normally, or ceiling all the time, but not make it optional.

We should also switch the internal representation to satoshis per MB or a double so that we could add a new member function to give greater precision, since mining doesn't use `CFeeRate` anyway and uses the actual fee per byte.

**Comment by laanwj** [comment]
> or a double 

Please don't use floating point for monetary values.

**Comment by jtimon** [comment]
Sorry, I commented in https://github.com/bitcoin/bitcoin/pull/7660#issuecomment-197418499 before seeing this.
I tend to agree with @morcos in that probably ceiling always would be better than an optional value.

**Comment by MarcoFalke** [comment]
Closing per IRC discussion.

**Pull request closed without merging**
