### PR TITLE
Fixing typo in rpcdump.cpp

### PR DESCRIPTION
**Pull request by keystrike**
'effect' should be 'affect'.

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by sipa** [comment]
ACK

**Comment by paveljanik** [comment]
trivial ACK https://github.com/bitcoin/bitcoin/pull/10469/commits/16d94d3d03efff9963b7a3cdb5a77c83a7e3e024

**Comment by practicalswift** [comment]
ACK 16d94d3

@keystrike Nice find! Quality is in the details!

**Comment by jtimon** [comment]
ACK 16d94d3d03efff9963b7a3cdb5a77c83a7e3e024

**Pull request merged**
