### PR TITLE
Avoid callback when -blocknotify is empty

### PR DESCRIPTION
**Pull request by promag**

### CODE REVIEW

**Comment by promag** [comment]
@MarcoFalke

**Comment by MarcoFalke** [comment]
ACK 413e0d1d31ede6a9b539d63ec814b6e8044e35e2

**Comment by practicalswift** [comment]
ACK 413e0d1d31ede6a9b539d63ec814b6e8044e35e2 -- patch looks correct

**Comment by laanwj** [comment]
Code review ACK 413e0d1d31ede6a9b539d63ec814b6e8044e35e2

**Comment by promag** [comment]
Thank you.

**Pull request merged**
