### PR TITLE
Qt: Show transaction size in transaction details window

### LINKED ISSUE #8125: [GUI] Show transction size in transaction window.
The user of-course can already implicitly work out this information from comparing the fee-rate with the actual fee.

I think that it would be useful for people not wanting to do this arithmetic in their head.

### PR DESCRIPTION
**Pull request by hsjoberg**
Fixes #8125

### CODE REVIEW

**Comment by sipa** [comment]
Wouldn't it be more useful to show the transaction weight? That's what
matters for fee estimates etc.

**Comment by luke-jr** [comment]
I suggest size + feerate-based-on-weight.

**Comment by Cocosoft** [comment]
@sipa Valid point, I guess I could add that as well.
I'm not sure how to make this easy to understand for the user though.

**Comment by jonasschnelli** [comment]
I agree with @luke-jr: `size + ferrate-based-on-weight`

**Comment by sipa** [comment]
Which size? We have:
* Base size
* Total size (base + witness)
* Virtual size (base + witness/4)
* Weight (4*base + witness)

My assumption was that after segwit, only vsize would matter. For old
transactions it is identical to total and base size, and for others it
remains proportional to fees with that.

**Comment by jonasschnelli** [comment]
Depends what users will do with the size information. But IMO size should be the "total size" (base + witness). I guess the size has usefulness besides fee calculation.

**Comment by sipa** [comment]
I agree it may be useful, but total size isn't the first a user should see
- it's not relevant for fee calculation, propagation time, priority, or
block space usage.

**Comment by jonasschnelli** [comment]
I agree that the virtual size does make more sense to display. We just need to clearly distinct between size (concrete hard size of a data structure) and virtual size (including other variables and attached to a bigger context).

I'm also not opposed to display multiple size types (at least base, total and virtual).

**Comment by laanwj** [comment]
> Which size? We have:
> * Base size
> * Total size (base + witness)
> * Virtual size (base + witness/4)
> * Weight (4*base + witness)

I think the "easy to implement" tag was a bit deceptive in this case :)

**Comment by Cocosoft** [comment]
@laanwj Indeed, what seemed like an easy fix blew up completely.
I can continue adding other types of sizes if we decide which ones to add.

> anyhow, utACK: Let's call it "Total size" and let people add other sizes later if they want.

Will fix.

**Comment by MarcoFalke** [comment]
Please squash your commits according to https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#squashing-commits

**Comment by laanwj** [comment]
@marcofalke These are two logically separate commits, one adds the function, the other adds the information to the transaction description HTML, I don't think squashing is necessary.

**Comment by fanquake** [comment]
It's pretty self explanatory, but here are some OS X screenshots.
transaction
transaction2

**Comment by MarcoFalke** [comment]
utACK c015634

**Review by paveljanik — COMMENTED** [review]
Please squash.

ACK https://github.com/bitcoin/bitcoin/commit/c015634400f112f8b7f037c82690f1332d7971a3

**Comment by jonasschnelli** [comment]
Tested ACK https://github.com/bitcoin/bitcoin/pull/8672/commits/c015634400f112f8b7f037c82690f1332d7971a3, merge-fixed `size`->`total size`.

**Pull request merged**
