### PR TITLE
Update secp256k1 subtree (including BIP340 support)

### PR DESCRIPTION
**Pull request by sipa**
This updates our src/secp256k1 subtree to the latest libsecp256k1 upstream version.

As it adds BIP340 support (see https://github.com/bitcoin-core/secp256k1/pull/558), this is a prerequisite for #17977. In particular, it contains:
* A few generic library improvements
* Support for x-only public keys as used by BIP340.
* Support for "key pair" objects, making signing more efficient by using a precomputed public key.
* Signing support for BIP340 Schnorr (single-party) signatures.
* Verification support for BIP340 Schnorr signatures.
* Support for verifying tweaked x-only keys, as used by BIP341's Taproot construction.

Things that are not included:
* MuSig, nor any kind of multisignatures, threshold signatures, ... on top.
* Batch verification.
* Support for variable-length messages in BIP340 (which are still being discussed, but won't affect BIP341, or Bitcoin Core).
* A few more generic improvements that are still in the pipeline, including faster modular inversions.

### CODE REVIEW

**Comment by real-or-random** [comment]
We still have https://github.com/bitcoin/bitcoin/issues/19263 open but this should not stop us from updating here.

**Comment by instagibbs** [comment]
Ran the subtree linter locally, manually checking hashes:
```
src/secp256k1 in HEAD currently refers to tree 1b2db0573d7c4f2f90589da7886816d0db73b8c7
src/secp256k1 in HEAD was last updated in commit b9c1a7648131c5deec9704ee9acd00ec1820b9ce (tree 1b2db0573d7c4f2f90589da7886816d0db73b8c7)
src/secp256k1 in HEAD was last updated to upstream commit 8ab24e8dad9d43fc6661842149899e3cc9213b24 (tree 1b2db0573d7c4f2f90589da7886816d0db73b8c7)
GOOD
```
Also as an exercise, ran the same update exercise, code matches:
```
git subtree pull --prefix src/secp256k1 https://github.com/bitcoin-core/secp256k1.git 8ab24e8dad9d43fc6661842149899e3cc9213b24 --squash
```


ACK 894fb33f4c1b24667891f7d2aff9f486177b1173

**Review by benthecarman — APPROVED** [review]
```
$ ./test/lint/git-subtree-check.sh src/secp256k1
src/secp256k1 in HEAD currently refers to tree 1b2db0573d7c4f2f90589da7886816d0db73b8c7
src/secp256k1 in HEAD was last updated in commit b9c1a7648131c5deec9704ee9acd00ec1820b9ce (tree 1b2db0573d7c4f2f90589da7886816d0db73b8c7)
src/secp256k1 in HEAD was last updated to upstream commit 8ab24e8dad9d43fc6661842149899e3cc9213b24 (tree 1b2db0573d7c4f2f90589da7886816d0db73b8c7)
GOOD
```

ACK `894fb33`

**Comment by luke-jr** [comment]
Looks like this bump unconditionally forces Valgrind calls on systems with Valgrind headers. Opened https://github.com/bitcoin-core/secp256k1/pull/813 to address.

**Comment by gmaxwell** [comment]
@luke-jr Nothing about this PR changes behaviour with respect to valgrind (see my comments on the linked issue).

**Comment by fanquake** [comment]
ACK 894fb33f4c1b24667891f7d2aff9f486177b1173. Any Valgrind concerns will be addressed upstream, see discussion in https://github.com/bitcoin-core/secp256k1/pull/813, and if necessary, can be pulled into our tree prior to the 0.21.0 branch off. They are not a blocker for merging this PR in it's current state.

```bash
➜  bitcoin-merge-tree git:(pull/19944/local-merge) git fetch https://github.com/bitcoin-core/secp256k1
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5566 (delta 1), reused 2 (delta 1), pack-reused 5560
Receiving objects: 100% (5566/5566), 2.39 MiB | 1023.00 KiB/s, done.
Resolving deltas: 100% (3887/3887), done.
From https://github.com/bitcoin-core/secp256k1
 * branch                HEAD       -> FETCH_HEAD
➜  bitcoin-merge-tree git:(pull/19944/local-merge) ./test/lint/git-subtree-check.sh src/secp256k1
src/secp256k1 in HEAD currently refers to tree 1b2db0573d7c4f2f90589da7886816d0db73b8c7
src/secp256k1 in HEAD was last updated in commit b9c1a7648131c5deec9704ee9acd00ec1820b9ce (tree 1b2db0573d7c4f2f90589da7886816d0db73b8c7)
src/secp256k1 in HEAD was last updated to upstream commit 8ab24e8dad9d43fc6661842149899e3cc9213b24 (tree 1b2db0573d7c4f2f90589da7886816d0db73b8c7)
GOOD
```

**Pull request merged**
