### PR TITLE
build: remove threadinterrupt from libbitcoinkernel

### PR DESCRIPTION
**Pull request by fanquake**
Extracted from #26292.

### CODE REVIEW

**Review by hebasto — APPROVED** [review]
ACK afbcd227dd0889002eeeec6148538ed2e2c9aadb, tested on Ubuntu 22.04.

FWIW, `./configure --with-experimental-kernel-lib --enable-experimental-util-chainstate && make` still works even with the following diff:

```diff
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -886,7 +886,6 @@ libbitcoinkernel_la_SOURCES = \
   chain.cpp \
   chainparamsbase.cpp \
   chainparams.cpp \
-  clientversion.cpp \
   coins.cpp \
   compressor.cpp \
   consensus/merkle.cpp \
@@ -895,11 +894,9 @@ libbitcoinkernel_la_SOURCES = \
   core_read.cpp \
   dbwrapper.cpp \
   deploymentinfo.cpp \
-  deploymentstatus.cpp \
   flatfile.cpp \
   fs.cpp \
   hash.cpp \
-  kernel/chain.cpp \
   kernel/checks.cpp \
   kernel/coinstats.cpp \
   kernel/context.cpp \
@@ -932,7 +929,6 @@ libbitcoinkernel_la_SOURCES = \
   signet.cpp \
   support/cleanse.cpp \
   support/lockedpool.cpp \
-  sync.cpp \
   txdb.cpp \
   txmempool.cpp \
   uint256.cpp \
```

**Comment by fanquake** [comment]
> still works even with the following diff:
> -  sync.cpp \

That's because you didn't test with `--enable-debug`. Haven't looked at the other suggestions.

**Comment by hebasto** [comment]
> That's because you didn't test with `--enable-debug`.

Correct.

> Haven't looked at the other suggestions.

`./configure --with-experimental-kernel-lib --enable-experimental-util-chainstate --enable-debug && make` still works with the following diff on Ubuntu 22.04:
```diff
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -886,7 +886,6 @@ libbitcoinkernel_la_SOURCES = \
   chain.cpp \
   chainparamsbase.cpp \
   chainparams.cpp \
-  clientversion.cpp \
   coins.cpp \
   compressor.cpp \
   consensus/merkle.cpp \
@@ -895,11 +894,9 @@ libbitcoinkernel_la_SOURCES = \
   core_read.cpp \
   dbwrapper.cpp \
   deploymentinfo.cpp \
-  deploymentstatus.cpp \
   flatfile.cpp \
   fs.cpp \
   hash.cpp \
-  kernel/chain.cpp \
   kernel/checks.cpp \
   kernel/coinstats.cpp \
   kernel/context.cpp \
```

**Comment by theuni** [comment]
Concept ACK.

FWIW, I anticipate threadinterrupt coming back to the kernel eventually as I think we'll want to use it to get rid of `shutdown.cpp`.

I think it's fine to re-add it when it's actually needed though.

**Comment by fanquake** [comment]
> still works with the following diff
> -  deploymentstatus.cpp \

If "works" means compiles, then sure, however this also drops the compile-time deployment status sanity checks from the kernel build.

**Review by ryanofsky — APPROVED** [review]
Code review ACK afbcd227dd0889002eeeec6148538ed2e2c9aadb

**Pull request merged**
