### PR TITLE
Prefer (int)a over int(a)

### PR DESCRIPTION
**Pull request by practicalswift**

### CODE REVIEW

**Comment by paveljanik** [comment]
Let's slow down please and let the review part to catch you... thx

**Comment by luke-jr** [comment]
Where is this deprecated? I prefer the current form... :/

**Comment by sipa** [comment]
I don't like C++ style casts for simple integer types. Sure, C-style casts can be dangerous in general, but for simple types there is no such risk, and result in much less cluttered notation.

<bikeshed>I do prefer `(int)a` over `int(a)`, though.</bikeshed>

**Comment by practicalswift** [comment]
@sipa PR updated accordingly. Looks OK? :-)

**Comment by MarcoFalke** [comment]
Our style guide does not mention what is preferred and it does not seem relevant, so tend to NACK.

**Comment by practicalswift** [comment]
Closing since consensus seems to be that this change is unnecessary :-)

**Pull request closed without merging**
