### PR TITLE
refactor (tidy): Fixes after enable-debug configure

### PR DESCRIPTION
**Pull request by sedited**
This diff can be reproduced by running (tested with clang-14 and clang-15):

```
./autogen.sh && CC=clang CXX=clang++ ./configure --enable-suppress-external-warnings --enable-debug
bear --config src/.bear-tidy-config -- make -j $(nproc)
cd ./src/ && run-clang-tidy -quiet -fix -j $(nproc)
```

### CODE REVIEW

**Comment by fanquake** [comment]
The failure here is #27316.

**Comment by hebasto** [comment]
> Besides, I'm also not sold that this lint is an actual improvement.

I think this PR diff _is_ an improvement.

**Comment by glozow** [comment]
> > Besides, I'm also not sold that this lint is an actual improvement.
> 
> I think this PR diff _is_ an improvement.

Could you explain why it's an improvement? It's unclear to me why const references to iterators would be an improvement, I was under the impression that iters by value were fine.

**Comment by hebasto** [comment]
> I'll undraft this then, even if I still don't understand why `clang-tidy` seems to catch more with debug enabled.

I suspect the `-DBOOST_MULTI_INDEX_ENABLE_SAFE_MODE` definition.

**Review by glozow — COMMENTED** [review]
> Making a constness at the call site obvious for a code reader/reviewer is a very minor improvement, which could be just ignored.

Ok, so it seems we agree there is no code quality benefit. Is the motivation = CI already failing or wanting to add --enable-debug to it?

> The failure here is https://github.com/bitcoin/bitcoin/issues/27316.

I'm having trouble understanding the relationship between this PR and that issue, am I missing something?

**Comment by TheCharlatan** [comment]
> I'm having trouble understanding the relationship between this PR and that issue, am I missing something?

The CI was previously failing on the functional tests due to that issue.

**Comment by fanquake** [comment]
The functional test failure was sporadic, and unrelated to the changes proposed here.

**Comment by TheCharlatan** [comment]
Updated 73afe2c3ac87049887e0633bd25c20f809e8090c -> efa1d5bb477dc2093bc06ffded382fdce6bc7703 ([clangTidyDebug_0](https://github.com/TheCharlatan/bitcoin/commits/clangTidyDebug_0) -> [clangTidyDebug_1](https://github.com/TheCharlatan/bitcoin/commits/clangTidyDebug_1), [compare](https://github.com/TheCharlatan/bitcoin/compare/clangTidyDebug_0..clangTidyDebug_1)).

* Addressed @hebasto 's [suggestion](https://github.com/bitcoin/bitcoin/pull/27353#issuecomment-1494267607) for adding the flag to the CI tidy job.

Rebased efa1d5bb477dc2093bc06ffded382fdce6bc7703 -> 3e76aff9d4709f44d6439cd0cbc2fd6c90cae6ab ([clangTidyDebug_1](https://github.com/TheCharlatan/bitcoin/commits/clangTidyDebug_1) -> [clangTidyDebug_2](https://github.com/TheCharlatan/bitcoin/commits/clangTidyDebug_2), [compare](https://github.com/TheCharlatan/bitcoin/compare/clangTidyDebug_1..clangTidyDebug_2)).

**Comment by fanquake** [comment]
> Maybe just provide CPPFLAGS=-DBOOST_MULTI_INDEX_ENABLE_SAFE_MODE?

Concept ~0 on making our clang-tidy usage dependant on some Boost define.

**Review by hebasto — APPROVED** [review]
ACK 3e76aff9d4709f44d6439cd0cbc2fd6c90cae6ab

> Concept ~0 on making our clang-tidy usage dependant on some Boost define.

What are possible drawbacks here?

In this case the `-DBOOST_MULTI_INDEX_ENABLE_SAFE_MODE` is just a subset of flags being used for debug builds.

**Comment by fanquake** [comment]
> What are possible drawbacks here?

I don't really understand adding it given [your comment above](https://github.com/bitcoin/bitcoin/pull/27353#issuecomment-1494267607):

> I'd avoid it as it will change code paths being parsed now

You suggested avoiding changing the code paths being parsed, and then suggested adding a define that changes the code paths being parsed?

In its current state, this PR is adding a Boost define, because it has a side-effect that basically "tricks" `clang-tidy` into thinking some code is slightly less performant (but only in debug builds) than it actually is, and thus will "lint" this code, and tell us to add more code to keep it quiet.

We could instead probably just add the consts, and leave it at that, without trying to invoke some boost-safe-mode-based side effect to trick a linter, and enforce some code change that in reality, doesn't make any difference to anything.

**Comment by fanquake** [comment]
@TheCharlatan can you update this to drop 3e76aff9d4709f44d6439cd0cbc2fd6c90cae6ab, or I think we could just close this?

**Comment by TheCharlatan** [comment]
I'll drop the commit. Could this be related to https://github.com/bitcoin/bitcoin/issues/27586 and solve some of the performance issues?

**Comment by TheCharlatan** [comment]
Updated 3e76aff9d4709f44d6439cd0cbc2fd6c90cae6ab -> 27d182cef72e086afc4592cdfc565b3fdb52d0b4 ([clangTidyDebug_2](https://github.com/TheCharlatan/bitcoin/commits/clangTidyDebug_2) -> [clangTidyDebug_3](https://github.com/TheCharlatan/bitcoin/commits/clangTidyDebug_3), [compare](https://github.com/TheCharlatan/bitcoin/compare/clangTidyDebug_2..clangTidyDebug_3)).

* Dropped the commit changing the CI.

**Pull request closed without merging**
