### PR TITLE
release: bump gitian descriptors for a new 0.14 package cache

### PR DESCRIPTION
**Pull request by theuni**
We should go ahead and bump master to 0.15 as well, so that it will transition to the release branch when the time comes.

I'll PR that separately.

### CODE REVIEW

**Comment by laanwj** [comment]
utACK 42f5f21

**Comment by theuni** [comment]
Yes. I'll add that along with the bump to 0.15 for master.

**Comment by achow101** [comment]
It's already in the release process doc under the "Update version in sources" section.

**Comment by theuni** [comment]
@achow101 Yep, thanks for checking. We just missed the bump last time around.

**Pull request merged**
