### PR TITLE
scripted-diff: Rename libbitcoin_server.a to libbitcoin_node.a

### PR DESCRIPTION
**Pull request by ryanofsky**
Goal along with namespacing PR #23497 is to make code organization more obvious and have `src/node/` code in `node::` namespace in `libbitcoin_node.a` library

### CODE REVIEW

**Comment by hebasto** [comment]
Concept ACK.

**Comment by MarcoFalke** [comment]
I cancelled this because the script failed. Maybe the bash doesn't resolve the `{}` in sed?

**Comment by ryanofsky** [comment]
> I cancelled this because the script failed. Maybe the bash doesn't resolve the `{}` in sed?

Yes it looks like there is a problem with `{server,node}` expansion throughout the script. I think problem might be that `/bin/sh` doesn't support [brace expansion](https://www.gnu.org/software/bash/manual/html_node/Brace-Expansion.html) so I pushed a version that calls bash. Lint looks like it's passing now. Will see if the actual build change is good and all the builds are working. I requested a GUIX build for this too, but feel free to cancel if this is overkill.

Updated 8ef044b7373d3c57841a0bc6427236d6f9b4192c -> 172096e9dd5b0e04b88ffd6dc1f6d43190070e14 ([`pr/libnode.1`](https://github.com/ryanofsky/bitcoin/commits/pr/libnode.1) -> [`pr/libnode.2`](https://github.com/ryanofsky/bitcoin/commits/pr/libnode.2), [compare](https://github.com/ryanofsky/bitcoin/compare/pr/libnode.1..pr/libnode.2))

**Comment by MarcoFalke** [comment]
cr ACK 172096e9dd5b0e04b88ffd6dc1f6d43190070e14

**Pull request merged**
