### PR TITLE
trivial: Replace CPubKey::operator[] with CPubKey::vch where possible

### PR DESCRIPTION
**Pull request by hmel**
Use variable name instead of calling operator[] through &(*this)[0]

### CODE REVIEW

**Comment by promag** [comment]
Actually it's not dependent of class layout, it uses `operator[]`: https://github.com/bitcoin/bitcoin/blob/c575260f80e94026204f97714ba6bcb26237d818/src/pubkey.h#L113
So I suggest to update the PR and commit.

Having said that, I like your change, but don't know if there is a motivation for the current code. Maybe @sipa has something to say?

**Comment by hmel** [comment]
You're absolutely right. I overlooked operator[], but I still think using variable name directly instead of &(*this)[0] going through operator[] to get the same thing. Maybe I'm missing something else? @sipa

**Comment by sipa** [comment]
Indeed, it is not dependent on class layout (no cast to char pointer is made), but the new code certainly looks better.

**Comment by promag** [comment]
@hmel Please update PR and commit messages.

ACK the change.

**Comment by sipa** [comment]
utACK b0bb82209baceff2ae8ff566c374d1dd7725765e

**Comment by promag** [comment]
Commit message still wrong.

**Comment by hmel** [comment]
Care to make a suggestion for commit message?

**Comment by promag** [comment]
Sure, currently it's `Use variable name instead of relying on class layout`, how about `trivial: Replace CPubKey::operator[] with CPubKey::vch where possible`?

**Comment by 251Labs** [comment]
Nice improvement, utACK 6755569

**Comment by promag** [comment]
utACK 6755569.

**Comment by laanwj** [comment]
Post=merge ACK, nice cleanup

**Pull request merged**
