### PR TITLE
Refactor: Move core files from src root to src/core and improve inclu…

### PR DESCRIPTION
**Pull request by danra**
…de paths

Advantages of moving the files under src into src/core:
- Cleans up the root src
- Allows for clearer management of includes - when an include is listed with no path prepended, there is no longer a dillema whether the included file is from the same folder as the including file, or just from the root src folder. This means:
   - Conflict resolution is cleaner in case a file of the same name exists both in the core folder and in the same folder as the including file - previously, to include the core file one had to either use a relative include path (../) or a brackets-system include. Now the core/ prefix can be used for cleaner disambiguation.
   - Files from the same folder can be included with no prefix with clear semantics, since files with no prefix are no longer maybe from the root src folder.

### CODE REVIEW

**Comment by promag** [comment]
At the moment NACK. There was a similar discussion regarding moving tests into subdirs..

**Comment by achow101** [comment]
NACK. Large refactors like this shouldn't really be done as they will break a lot of unmerged pull requests.

**Comment by laanwj** [comment]
I'd prefer to do this in the longer term - move groups of files to a directory that makes sense for them. Moving everything that is now in the source root to one a subdirectory of `src` has some advantages, but IMO not enough for all the rebasing work this will cause.

**Comment by danra** [comment]
Closing for lack of consensus. Thanks!

**Pull request closed without merging**
