### PR TITLE
[0.16.2] Backports

### PR DESCRIPTION
**Pull request by fanquake**
Backports:
* #12859 Bugfix: Include <memory> for std::unique_ptr
* #13131 Add Windows shutdown handler
* #13451 rpc: expose CBlockIndex::nTx in getblock(header)
* #13507 RPC: Fix parameter count check for importpubkey
* #13544 depends: Update Qt download url

to the 0.16 branch.

### CODE REVIEW

**Comment by instagibbs** [comment]
https://github.com/bitcoin/bitcoin/pull/13451 can be included now

**Comment by fanquake** [comment]
@instagibbs Added, care to check the backport.

**Comment by instagibbs** [comment]
Looks good to me

**Comment by laanwj** [comment]
utACK 9fd3e0001fc20eecbfa823e12f66da4054a072a7

**Pull request merged**
