### PR TITLE
Reduce ambiguity of warning message

### LINKED ISSUE #9079: ambiguous message: "spending bitcoins may not be possible"
There is a warning message that says "spending bitcoins may not be possible" which leaves the user unsure whether spending bitcoins will be possible or not. It would be better if it was clear whether the user can or cannot spend bitcoins and what this is dependent upon.

### PR DESCRIPTION
**Pull request by rebroad**
Fixes #9079

### CODE REVIEW

**Comment by kazcw** [comment]
This helps a lot with the ambiguity, but users who have already seen the message will tend to read just the beginning, so I think it should start with a summary of the situation as the old message (sort of) did. What about phrasing the first sentence more like "Your wallet is not finished synchronizing with the bitcoin network." to lead with status information rather than exposition.

**Comment by MarcoFalke** [comment]
Thanks! Concept ACK.

**Comment by jonasschnelli** [comment]
Thanks!
ACK 26f2cb1c9c739002ea74afbb7b333f794c2d7cfd

**Comment by fanquake** [comment]
ACK 26f2cb1

**Comment by rebroad** [comment]
@kazcw I see your point. I will re-arrange the messages.

**Comment by MarcoFalke** [comment]
utACK 77cbbd9

**Comment by MarcoFalke** [comment]
utACK 77cbbd9

**Comment by rebroad** [comment]
Why is travis complaining?

**Comment by laanwj** [comment]
Unrelated, likely:
```
p2p-segwit.py                  | False  | 74 s
```

**Comment by laanwj** [comment]
utACK 77cbbd9

> This helps a lot with the ambiguity, but users who have already seen the message will tend to read just the beginning

Luckily there will not be many users that have already seen the message, as it's not in any release yet.

**Pull request merged**
