### PR TITLE
[26.x] more backports

### PR DESCRIPTION
**Pull request by glozow**
Backports for 26.x. Includes:
- 453b481 from #28391
  - #29179
- #29200
- #29227 
- #28791
- #29127

### CODE REVIEW

**Review by stickies-v — APPROVED** [review]
ACK 234f32860dd0e450e214c93af09e9dd9df20e9ea

**Comment by achow101** [comment]
perhaps add #28791

**Comment by glozow** [comment]
fixed commit messages.

**Comment by fanquake** [comment]
Lets add #29127, so if we decide to, we can test macOS notarization: https://github.com/bitcoin/bitcoin/issues/15774#issuecomment-1899228781.

**Review by stickies-v — APPROVED** [review]
ACK 11f3a7e6baf145360190635f47b1fb371fb38912

**Pull request merged**
