### PR TITLE
doc: note why we can't use thread_local with glibc back compat

### PR DESCRIPTION
**Pull request by fanquake**
Given that we went through a [gitian build](https://github.com/bitcoin/bitcoin/pull/18681) to remember why this is the case, we might as well make a note of it in configure.ac.

[From #18681](https://github.com/bitcoin/bitcoin/pull/18681#issuecomment-615526634):

Looking at the Linux build log, this has failed with:
```bash
Checking glibc back compat...
bitcoind: symbol __cxa_thread_atexit_impl from unsupported version GLIBC_2.18
bitcoind: failed IMPORTED_SYMBOLS
bitcoin-cli: symbol __cxa_thread_atexit_impl from unsupported version GLIBC_2.18
bitcoin-cli: failed IMPORTED_SYMBOLS
bitcoin-tx: symbol __cxa_thread_atexit_impl from unsupported version GLIBC_2.18
bitcoin-tx: failed IMPORTED_SYMBOLS
bitcoin-wallet: symbol __cxa_thread_atexit_impl from unsupported version GLIBC_2.18
bitcoin-wallet: failed IMPORTED_SYMBOLS
test/test_bitcoin: symbol __cxa_thread_atexit_impl from unsupported version GLIBC_2.18
test/test_bitcoin: failed IMPORTED_SYMBOLS
bench/bench_bitcoin: symbol __cxa_thread_atexit_impl from unsupported version GLIBC_2.18
bench/bench_bitcoin: failed IMPORTED_SYMBOLS
qt/bitcoin-qt: symbol __cxa_thread_atexit_impl from unsupported version GLIBC_2.18
```

`__cxa_thread_atexit_impl` is used for [thread_local variable destruction](https://sourceware.org/glibc/wiki/Destructor%20support%20for%20thread_local%20variables):

> To implement this support, glibc defines __cxa_thread_atexit_impl exclusively for use by libstdc++ (which has the __cxa_thread_atexit to wrap around it), that registers destructors for thread_local variables in a list. Upon thread or process exit, the destructors are called in reverse order in which they were added.

As suggested, this only became available in glibc 2.18. From the [2.18 release notes](https://sourceware.org/legacy-ml/libc-alpha/2013-08/msg00160.html):

> * Add support for calling C++11 thread_local object destructors on thread
  and program exit.  This needs compiler support for offloading C++11
  destructor calls to glibc.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
ACK

**Review by hebasto — APPROVED** [review]
ACK 20a30922fbf6ba14e250ca649239af115dbbe7b0

**Comment by hebasto** [comment]
It is absolutely unrelated, but would you mind adding a typo fix in https://github.com/bitcoin/bitcoin/blob/c4c3f110eb93243fc8f740070240f50b0008f206/configure.ac#L259 s/liner/linker/ ?

**Comment by fanquake** [comment]
> It is absolutely unrelated, but would you mind adding a typo fix in 

Done.

**Review by hebasto — APPROVED** [review]
ACK b155fcda5186c59fc4fb2a9eaaf791d132e0ab30

**Pull request merged**
