### PR TITLE
[qa] py2: Unfiddle strings into bytes explicitly

### PR DESCRIPTION
**Pull request by maflcko**
This will explicitly mark most strings as bytes. (Required for py3)

### CODE REVIEW

**Comment by laanwj** [comment]
Awesome, this is the shittiest part of porting to Python 3.
Concept ACK.

**Comment by laanwj** [comment]
tACK faa41ee

**Comment by mruddy** [comment]
@MarcoFalke 

i noticed a new error when running `make check`:

```
Running test/bitcoin-util-test.py...
Traceback (most recent call last):
  File "./test/bitcoin-util-test.py", line 12, in <module>
    "bitcoin-util-test.json",buildenv)
  File "/home/black/Desktop/bitcoin/src/test/bctest.py", line 52, in bctester
    bctest(testDir, testObj, buildenv.exeext)
  File "/home/black/Desktop/bitcoin/src/test/bctest.py", line 30, in bctest
    outs = proc.communicate(input=inputData)
  File "/usr/lib/python3.4/subprocess.py", line 962, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.4/subprocess.py", line 1601, in _communicate
    self._save_input(input)
  File "/usr/lib/python3.4/subprocess.py", line 1677, in _save_input
    self._input = self._input.encode(self.stdin.encoding)
AttributeError: 'bytes' object has no attribute 'encode'
```

this makes the error go away, but is probably not what you want since it only undoes one of this PR's changes:
```
diff --git a/src/test/bctest.py b/src/test/bctest.py
index fc59152..dbff278 100644
--- a/src/test/bctest.py
+++ b/src/test/bctest.py
@@ -17,7 +17,7 @@ def bctest(testDir, testObj, exeext):
        inputData = None
        if "input" in testObj:
                filename = testDir + "/" + testObj['input']
-               inputData = open(filename, 'rb').read()
+               inputData = open(filename).read()
                stdinCfg = subprocess.PIPE
 
        outputFn = None
```

**Comment by MarcoFalke** [comment]
@mruddy Thanks for reporting, I will take a look...

**Pull request merged**
