### PR TITLE
 Bitcoin bans China

### PR DESCRIPTION
**Pull request by DavidBurkett**
This bans users in China from running the Bitcoin client. On startup, we query https://myexternalip.com/raw to determine our external IP address. We then check it against the list of known IPs in China.

image

Limitations:
* Currently only supports IPv4, but IPv6 support could be added in a similar way.
* Relies on a trusted server to determine our external IP address. In the future, we may want to query additional services (e.g. whatismyip.com) to guard against issues with myexternalip.com.
* Relies on a static list of subnets - We could replace the list with a call to http://www.ipdeny.com/ipblocks/data/countries/cn.zone, but this introduces an additional trusted service. I'm open to suggestions.

### CODE REVIEW

**Comment by coblee** [comment]
You should also drop peers if IP is in China. This will stop relaying blocks mined in China.

Also need unit tests!

**Comment by losh11** [comment]
tested ACK

**Comment by red0bear** [comment]
please let me add black list too :D

**Comment by coinforensics** [comment]
Aside from the obvious leak of the client IP to myexternalip[.]com, I strongly oppose such a PR.

Concept NACK.

**Pull request closed without merging**
