### PR TITLE
test: Fix test failures

### LINKED ISSUE #16488: test: feature_dbcrash listunspent times out
On current master

```
2019-07-29T16:43:20.074000Z TestFramework (INFO): Iteration 31, generating 2500 transactions [15, 3, 0]
2019-07-29T16:45:53.858000Z TestFramework (ERROR): JSONRPC error
Traceback (most recent call last):
  File "/root/workspace/bitcoin-core/test/functional/test_framework/authproxy.py", line 163, in _get_response
    http_response = self.__conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/workspace/bitcoin-core/test/functional/test_framework/test_framework.py", line 193, in main
    self.run_test()
  File "./test/functional/feature_dbcrash.py", line 250, in run_test
    utxo_list = self.nodes[3].listunspent()
  File "/root/workspace/bitcoin-core/test/functional/test_framework/coverage.py", line 47, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "/root/workspace/bitcoin-core/test/functional/test_framework/authproxy.py", line 139, in __call__
    response, status = self._request('POST', self.__url.path, postdata.encode('utf-8'))
  File "/root/workspace/bitcoin-core/test/functional/test_framework/authproxy.py", line 107, in _request
    return self._get_response()
  File "/root/workspace/bitcoin-core/test/functional/test_framework/authproxy.py", line 170, in _get_response
    self.__conn.timeout)})
test_framework.authproxy.JSONRPCException: 'listunspent' RPC took longer than 90.000000 seconds. Consider using larger timeout for calls that take longer to return. (-344)
2019-07-29T16:45:54.033000Z TestFramework (INFO): Stopping nodes
2019-07-29T16:45:54.060000Z TestFramework.node3 (ERROR): Unable to stop node.
Traceback (most recent call last):
  File "/root/workspace/bitcoin-core/test/functional/test_framework/test_node.py", line 264, in stop_node
    self.stop(wait=wait)
  File "/root/workspace/bitcoin-core/test/functional/test_framework/coverage.py", line 47, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "/root/workspace/bitcoin-core/test/functional/test_framework/authproxy.py", line 139, in __call__
    response, status = self._request('POST', self.__url.path, postdata.encode('utf-8'))
  File "/root/workspace/bitcoin-core/test/functional/test_framework/authproxy.py", line 106, in _request
    self.__conn.request(method, path, postdata, headers)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1250, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/lib/python3.6/http/client.py", line 1108, in putrequest
    raise CannotSendRequest(self.__state)
http.client.CannotSendRequest: Request-sent
2019-07-29T16:46:55.268000Z TestFramework.utils (ERROR): wait_until() failed. Predicate: ''''
    def is_node_stopped(self):
        """Checks whether the node has stopped.

        Returns True if the node has stopped. False otherwise.
        This method is responsible for freeing resources (self.process)."""
        if not self.running:
            return True
        return_code = self.process.poll()
        if return_code is None:
            return False

        # process has stopped. Assert that it didn't return an error code.
        assert return_code == 0, self._node_msg(
            "Node returned non-zero exit code (%d) when stopping" % return_code)
        self.running = False
        self.process = None
        self.rpc_connected = False
        self.rpc = None
        self.log.debug("Node stopped")
        return True
'''
Traceback (most recent call last):
  File "./test/functional/feature_dbcrash.py", line 273, in <module>
    ChainstateWriteCrashTest().main()
  File "/root/workspace/bitcoin-core/test/functional/test_framework/test_framework.py", line 218, in main
    self.stop_nodes()
  File "/root/workspace/bitcoin-core/test/functional/test_framework/test_framework.py", line 401, in stop_nodes
    node.wait_until_stopped()
  File "/root/workspace/bitcoin-core/test/functional/test_framework/test_node.py", line 305, in wait_until_stopped
    wait_until(self.is_node_stopped, timeout=timeout)
  File "/root/workspace/bitcoin-core/test/functional/test_framework/util.py", line 225, in wait_until
    raise AssertionError("Predicate {} not true after {} seconds".format(predicate_source, timeout))
AssertionError: Predicate ''''
    def is_node_stopped(self):
        """Checks whether the node has stopped.

        Returns True if the node has stopped. False otherwise.
        This method is responsible for freeing resources (self.process)."""
        if not self.running:
            return True
        return_code = self.process.poll()
        if return_code is None:
            return False

        # process has stopped. Assert that it didn't return an error code.
        assert return_code == 0, self._node_msg(
            "Node returned non-zero exit code (%d) when stopping" % return_code)
        self.running = False
        self.process = None
        self.rpc_connected = False
        self.rpc = None
        self.log.debug("Node stopped")
        return True
''' not true after 60 seconds
[node 3] Cleaning up leftover process

### LINKED ISSUE #16498: feature_dbcrash fails on sendrawtransaction [JSONRPCException: dust (code 64) (-26)]
Current master

```
 node3 2019-07-30T17:10:17.042876Z [httpworker.0] ThreadRPCServer method=listunspent user=__cookie__
 test  2019-07-30T17:10:17.304000Z TestFramework (DEBUG): Node3 utxo count: 88
 test  2019-07-30T17:10:17.305000Z TestFramework (INFO): Iteration 18, generating 2500 transactions [4, 1, 0]
 node3 2019-07-30T17:10:17.308014Z [http] Received a POST request for / from 127.0.0.1:36933
 node3 2019-07-30T17:10:17.308240Z [httpworker.3] ThreadRPCServer method=signrawtransactionwithwallet user=__cookie__
 node3 2019-07-30T17:10:17.316277Z [http] Received a POST request for / from 127.0.0.1:36933
 node3 2019-07-30T17:10:17.316528Z [httpworker.1] ThreadRPCServer method=sendrawtransaction user=__cookie__
 test  2019-07-30T17:10:17.318000Z TestFramework (ERROR): JSONRPC error
                                   Traceback (most recent call last):
                                     File "/root/workspace/bitcoin-core/test/functional/test_framework/test_framework.py", line 193, in main
                                       self.run_test()
                                     File "/root/workspace/bitcoin-core/test/functional/feature_dbcrash.py", line 241, in run_test
                                       self.generate_small_transactions(self.nodes[3], 2500, utxo_list)
                                     File "/root/workspace/bitcoin-core/test/functional/feature_dbcrash.py", line 211, in generate_small_transactions
                                       node.sendrawtransaction(tx_signed_hex)
                                     File "/root/workspace/bitcoin-core/test/functional/test_framework/coverage.py", line 47, in __call__
                                       return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
                                     File "/root/workspace/bitcoin-core/test/functional/test_framework/authproxy.py", line 141, in __call__
                                       raise JSONRPCException(response['error'], status)
                                   test_framework.authproxy.JSONRPCException: dust (code 64) (-26)

### LINKED ISSUE #16518: feature_fee_estimation.py test fails randomly
See log https://bitcoinbuilds.org/index.php?ansilog=44accd13-eea0-4aab-a6a4-f0694f12a68f.log#l7024 (`feature_fee_estimation.py` failed on master).

There is a dust detection exception during `sendrawtransaction` (https://github.com/bitcoin/bitcoin/blob/master/test/functional/feature_fee_estimation.py#L66).

### PR DESCRIPTION
**Pull request by maflcko**
in feature_dbcrash:

* Fixes #16488
* Fixes #16498

in feature_fee_estimation:

* Fixes #16518

### CODE REVIEW

**Comment by MarcoFalke** [comment]
This fixes three known test failures by adjusting incorrectly set test params in `set_test_params`. Shouldn't be too hard to review and would make it easier to hunt the other test failures by eliminating the ones that are already known and fixed.

**Review by fanquake — APPROVED** [review]
ACK fa36aa4922582fadf1aa8cbf89c33feeae80ac44

**Comment by practicalswift** [comment]
@MarcoFalke After this merge -- what known test failures remain?

**Comment by MarcoFalke** [comment]
https://github.com/bitcoin/bitcoin/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3ATests+fail+author%3AMarcoFalke

**Pull request merged**
