### PR TITLE
doc: add detached release notes for #14060

### PR DESCRIPTION
**Pull request by mruddy**
Adding detached release notes for #14060 in order to assist with https://github.com/bitcoin/bitcoin/pull/14688.

### CODE REVIEW

**Comment by laanwj** [comment]
Thanks! ACK https://github.com/bitcoin/bitcoin/pull/14704/commits/86cddf0856dc56fabba250254cd6c0745be69eb7

**Comment by MarcoFalke** [comment]
cc @harding

**Comment by mruddy** [comment]
thanks guys. @harding sounds good to me.

**Comment by fanquake** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/14704/commits/86cddf0856dc56fabba250254cd6c0745be69eb7

**Pull request merged**
