### PR TITLE
kernel: chainparams updates for 26.x

### LINKED ISSUE #28572: Update chainparams pre 26.x branch-off
### Motivation

This should be done before the branch-off, and can be done by anyone, as the steps are  reproducible and reviewable.

### Possible solution

Follow the documentation: https://github.com/bitcoin/bitcoin/blob/master/doc/release-process.md#before-branch-off

### Useful Skills

* Compiling Bitcoin Core from source
* Running the C++ unit tests and the Python functional tests
* ...

### Guidance for new contributors

Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

### PR DESCRIPTION
**Pull request by fanquake**
Update chainparams pre `26.x` branch off.

Note: Remember that some variance is expected in the m_assumed_* sizes.

Closes #28572.

### CODE REVIEW

**Comment by ajtowns** [comment]
ACK 817c7cd020c8e4a7e1787bce2e1a2f1d11e91b5f

Consider merging #25970 first and also doing the steps there, perhaps? Can easily be deferred 'til after branch off and next release though.

**Review by Sjors — APPROVED** [review]
ACK 817c7cd020c8e4a7e1787bce2e1a2f1d11e91b5f

See [release-process.md](https://github.com/bitcoin/bitcoin/blob/master/doc/release-process.md#before-branch-off) for how to verify these numbers.

**Comment by darosior** [comment]
ACK 100b7c9b6713aa32281077b0bed6d8daecdc20be -- only checked assumevalid and minimum chain work, not header sync params.

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK 100b7c9b6713aa32281077b0bed6d8daecdc20be
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEEWQtykmla/6W2csuy4T/BRc0/QwQFAmUev50ACgkQ4T/BRc0/
QwQdJAwAn3XQZUXme0XNbEob00a0VxY+xz+rt2aT3JZM8Jmm9OnDDJb4oZVD85wf
PyhNLj9jWwa2GXoyHLkSkpl27c5uY820x1cte6roAXDCoF/SfhK2nE34UmShAhvF
9avwg+wjDd5WAGcK1bcq6E0+ko27VbfMaETvRl3BueafFBIo9yKACJQMfAhVk9vC
WbJOTGol7xp0GELsGjUjfYz3G3Nr36UCUG4fcBuBJljwH8C72Axw0ozCtvS+cyH6
UDEaTvElgcQGKoz1ippf+hQU/VhuiXSMiOuhdrhujsOHduC3hLPECR8r/w/24P54
WcENv8+d3BeP7VGPIhLIwX2V5jTEdxUSg55igUgP7HvQ/xyzNQQ+5Cgo59T5xhIg
ICVT04k2F9zlqEskfGzuGZ0WbpUL6aKqHCpeLeZPhu6gi/bO8ndJ3IEM7o9jrtZz
Va/tAAI+zH4otEeKz7ooEjDCKWGGY0vjLG8kzycfpD6aHDnKoP42gtP+QnPhBHDQ
BzkXTbUa
=YcGc
-----END PGP SIGNATURE-----
```

**Comment by Sjors** [comment]
ACK 100b7c9b6713aa32281077b0bed6d8daecdc20be

Also ran the `headerssync-params.py` script.

**Comment by ajtowns** [comment]
reACK bd71f03df75d2c17926b6d575ffa886daa334e3a

**Comment by darosior** [comment]
re-ACK bd71f03df75d2c17926b6d575ffa886daa334e3a for assumevalid and minchainwork params.

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK bd71f03df75d2c17926b6d575ffa886daa334e3a
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEEWQtykmla/6W2csuy4T/BRc0/QwQFAmUitIYACgkQ4T/BRc0/
QwQSKwwA2pX153WNmI8Aws8DVmyxEG6UVI7BbFYfklr0k4qnPB5CAeFGrtON1PVu
6yljNp7tD297AsQ/kUBL1Vsw+PFy3Oq7PRDruCQJm4iwRGyI7a6WCHzP3hMqiZB5
LmMtoTzW3XUJuarbAK5bK53MUYnbmKPsYYzpFfVPfDajr+RzJv5I2WOBNWZTJDgV
L+kpcbKhVldp46MGa7XtTVH6mvChqgEaa0wHVCuhXf+l2IOAw+1GamOjTlIcnQy5
CCJUArHhHIJN0QvEdgFsuCoqvSX+3OGO8CA5nXpkWTfS0iUSyCF20b7yINxXb4f6
5PmnSEeyfWUYsH7gP7t7MJ9sYzSYUGYMgAXcYzOgaUsGa4fdfbcPPREN0CrhELVl
XkYU2nAMIX+p3PL4yqWM6gbQgHYdQoSk8G2VJ/v3HJasqpfUWlCcJpf3D5xODg1T
LZDhhz8BjzEfsi8UmPe+E5gx47vdQ9YNciu+Bjmlm/Z5TcElhIQjH3vp6fQWF22y
5pvjxLWI
=YXBD
-----END PGP SIGNATURE-----
```

**Review by Bbjj88h — APPROVED** [review]

**Comment by RonieLabr70031** [comment]
# BIP-44 Derivation Paths
| BTC            | Bitcoin           | GetPublicKey           | bc1q7799s3qgqpuvfyux7u3vgrd2lus66sc0gmeaxj         | SignTx             | Derivation    | Note           |
|-------------------|------------------|------------------------|--------------------|--------------------|---------------|----------------|
| Bitcoin           | secp256k1        | `m/p'/c'/a'`           | `m/p'/c'/a'/h/i`   | `m/p'/c'/a'/h/i`   | BIP-32        | [21](#Bitcoin)  |
| Ethereum          | secp256k1        | `m/44'/60'/0'`         | `m/44'/60'/a'/0/0` | `m/44'/60'/a'/0/0` | BIP-32        | [2](#Ethereum) |
| Cosmos            | secp256k1        | `m/44'/118'/0'`        | `m/44'/118'/a'/0/0`| `m/44'/118'/a'/0/0`| BIP-32        | -              |

Where `p` is the [BIP-44](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki) purpose described further in [1](#Bitcoin).

Where `c` is the Coin's [slip44 id](https://github.com/satoshilabs/slips/blob/master/slip-0044.md).

Where `a` is the Account index, starting from `0`.

Where `h` is `0` / `1` for External / Change respectively (for UTXO coins).

Where `i` is the address index, starting from `0`.

# Notes

1. <a name="Bitcoin"></a> For Bitcoin and its derivatives, `p` is decided based on:

    | p    | BTC         | Bitcoin    |
    |   49 |   p2sh SegWit |   1PZsdkJF7SiVYcE1V8TLGLKJkxQHsbs9pF |
    |   44 | Legacy        | SPENDADDRESS         |
    |   48 | Multisig      | SPENDMULTISIG        |
    |   49 | p2sh SegWit   | SPENDP2SHWITNESS     |
    |   84 | Native SegWit | SPENDWITNESS         |

Other `p` are strongly discouraged with an on-device warning. `c` must be equal
to the coin's [slip44-id](https://github.com/satoshilabs/slips/blob/master/slip-0044.md).

2. <a name="Ethereum"></a> For legacy reasons, Ethereum address derivation
paths are very non-standardized across vendors. Not much we can do about it
unfortunately, since there are lots of wallets out in the wild with funds on
them at those addresses.

## Allowed Values

For SignTx on UTXO coins, `i` must be in the range \[0,]1000000].

**Review by dr8931240-ux — COMMENTED** [review]
Complete

**Pull request merged**
