### PR TITLE
wallet: Create named SQLite wallet files instead of wallet directories

### PR DESCRIPTION
**Pull request by achow101**
Wallet directories were introduced because BDB has issues with shared database environments. Since SQLite does not have database environments it is not necessary to have these directories. So instead, we go back to the original multiwallet plan of having just wallet files named with the desired wallet name. Note that this configuration is technically supported with BDB wallets although new wallets would not be created like this. For SQLite, this is both supported and the way that wallets are created.

Depends on #18788 for tests.

### CODE REVIEW

**Comment by ryanofsky** [comment]
I think wallets should keep being directories. Few reasons:

- Aesthetics, usability, and the road to ambiguity. People are used to file names having extensions, and directory names not having extensions. If you create wallet named "My Wallet" in the GUI, or run `bitcoin-cli createwallet "My Wallet"`, there's nothing unusual about seeing a directory called `"My Wallet"` in `<walletdir>`. If `"My Wallet"` is created as a file not a directory, then you have an unusual looking file with no extension. So then there is a reason to call `bitcoin-cli createwallet` with a name that looks more like a filename: `mywallet.dat`, `mywallet.db` `mywallet.wallet`. And then the GUI starts showing lists of wallets like `mywallet1.wallet` and `mywallet2.wallet` and RPC endpoints looks like `/wallet/mywallet1.wallet` and `/wallet/mywallet2.wallet`. And then to improve ergonomics, somebody writes a PR to strip extensions, so GUI is more user-friendly or so RPC endpoint names are less verbose. And then simple mapping of wallet name == RPC endpoint name == GUI display name is broken, so now there are multiple mappings, ambiguity, more confusion, and everything is more complicated and stupid.

- Backup safety. The claim that "Since SQLite does not have database environments it is not necessary to have these directories" is ambiguous and not accurate as far as I know. The sqlite implementation does not require periodic flushing to consolidate log files, but that doesn't mean that sqlite doesn't create log files. If you create a `<walletname>` wallet, sqlite will create a `<walletname>.wallet-journal` file, so if you have a backup script that is periodically backing up the `<walletdir>/<walletname>` path, it can miss the journal file. If the backup script wants to include the journal file, it needs to know about wallet database layout. It is better if wallet is just a directory, so the backup script can back up the directory without having to care about database layout. If script wants to care about the layout, it can still do that and exclude things, but the simple non-invasive approach will include data instead of excluding it.

- Future extensibility. It's nice if wallets are directories instead of files, so there is a place to add new files associated with the wallet. I have PRs that let wallets run as separate processes. These wallet processes will want to run RPC servers. These RPC servers will need a place to put cookie files. A logical place would be inside the wallet directory. Similarly with future per-wallet debug logs, per-wallet settings files, per-wallet socket endpoints. If you have wallet directory, there is a natural place to put all these things. Users and external tools will be able to locate all data associated with a wallet without having to make assumptions about layout.

**Comment by hebasto** [comment]
I agree with @ryanofsky's reasons, especially with "Future extensibility" and "Backup safety".

As for wallet names that looks like \<filename\>\<dot\>\<extension\>, they could cause user confusion and fund loss because some OSes hide extensions from users.

**Comment by sipa** [comment]
@ryanofsky I considered being able to move to non-directory wallets an advantage of sqlite, but you give good arguments for sticking with directories.

**Comment by achow101** [comment]
@ryanofsky makes a convincing argument. Closing.

**Pull request closed without merging**
