### PR TITLE
[rpc] Mention that HD is enabled if hdmasterkeyid is present

### PR DESCRIPTION
**Pull request by fanquake**
Also adds optional flag.

Replaces #12042

### CODE REVIEW

**Comment by laanwj** [comment]
docchange-only-utACK c6b6385

**Review by jonasschnelli — APPROVED** [review]
ACK c6b6385651d5e78daf9dd27717e47e3a8940694b

**Comment by MarcoFalke** [comment]
Thanks for picking this up.

                  
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

utACK c6b6385651d5e78daf9dd27717e47e3a8940694b
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJab4QHAAoJENLqSFDnUoslqngP/1+6Cpoqirp1NaaYTaTZri4I
4rzH6wQV5dkK0Fkr8CtSc1Fhj9p99sExzX6vBemZZzUMVLhlTP9/Q39tOmAUvN7o
DrUBHfPVGQsGPhTeFJ/nWQb9Vju51PBl2ma5Fpq8nYA9SblfKVrK1qbGYRRFU42w
9sk+6MYBKcjvTUMryR9Go66TV0l3n6OyIA6awrn9UyopBqPLRg6VEdeV1uecdcnP
40XdYvDdlqjCo6HSJGkppjNx5ok+4u9v3nY1k1Xl6w0Jti0DLm+6nPS0DYBNUC97
UerN2FtOXrfA0+nQUtB8ZDjBWPtIHw+WwVrXfD4yt1UKei8Ko7NQv/esP1OtpySS
/9eYDXNBg+HXMLgKNz43Hh2tLP63B4r3cJeKu04WfjItguK5YisdLZF3ErydmLLW
c9UrVyoCulCfwnNr86KUL/m+nIZKO1z5pZ+xs/3BZw6D5/ZUxIsq6CKycZfIe942
fjCSg4UlTu4OB06g/D84S+q3n1QUZG83BNQM8XXZaEqMBDnknz3SMorIlm1r4gIq
DkaUkBHQY099VgO7SHp/q3JhZ2ztPT0w1q1wSsflM91YDfUXOI6JeWOKjKrGiz5+
r0EAsszRhsJnJb56rpdX2JE6rBAS4nrW0N8PFzPj0IdjUfKT/yXE2ki1OYfL7dlh
DcAROue7amNsWL3JCj0k
=vV0d
-----END PGP SIGNATURE-----

**Comment by WalterBoles** [comment]
So does this make it were I can access all the money from my poll request

**Pull request merged**
