### PR TITLE
depends: switch to secure download of all dependencies

### PR DESCRIPTION
**Pull request by Kemu**
Even if we potentially check the integrity of the downloaded file via hash comparison, we should make use of SSL since it is available.

### CODE REVIEW

**Comment by fanquake** [comment]
Concept ACK

If we're going to do this, might as well make the change in all packages. 

Looks like `http:` -> `https:` will work for everything except `miniupnpc`. That package could be changed to use the `https://miniupnp.tuxfamily.org/files/` mirror.

**Comment by practicalswift** [comment]
Concept ACK

Not leaking is better than leaking.

**Comment by kristapsk** [comment]
Concept ACK

There is no downside in using HTTPS.

**Comment by jonasschnelli** [comment]
Tested ACK (manually downloaded `curl -OL https://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz` and verified the sha256 hash).

**Comment by jonatack** [comment]
tACK

```bash
$ curl -OL https://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz

$ sha256sum db-4.8.30.NC.tar.gz
12edc0df75bf9abd7f82f821795bcee50f42cb2e5f76a6a281b85732798364ef  db-4.8.30.NC.tar.gz
```

Same hash as the non-SSL http curl from a couple months ago.

**Comment by jonasschnelli** [comment]
@Kemu 
Are you interested to also cover the other plain http packages in this pull?
```shell
grep -rnw './depends' -e 'http:'
./depends/packages/xtrans.mk:3:$(package)_download_path=http://xorg.freedesktop.org/releases/individual/lib/
./depends/packages/libxcb.mk:3:$(package)_download_path=http://xcb.freedesktop.org/dist
./depends/packages/freetype.mk:3:$(package)_download_path=http://download.savannah.gnu.org/releases/$(package)
./depends/packages/xextproto.mk:3:$(package)_download_path=http://xorg.freedesktop.org/releases/individual/proto
./depends/packages/libX11.mk:3:$(package)_download_path=http://xorg.freedesktop.org/releases/individual/lib/
./depends/packages/native_cctools.mk:8:$(package)_clang_download_path=http://llvm.org/releases/$($(package)_clang_version)
./depends/packages/zlib.mk:3:$(package)_download_path=http://www.zlib.net
./depends/packages/native_cdrkit.mk:3:$(package)_download_path=http://distro.ibiblio.org/fatdog/source/600/c
./depends/packages/xproto.mk:3:$(package)_download_path=http://xorg.freedesktop.org/releases/individual/proto
./depends/packages/xcb_proto.mk:3:$(package)_download_path=http://xcb.freedesktop.org/dist
./depends/packages/miniupnpc.mk:3:$(package)_download_path=http://miniupnp.free.fr/files
./depends/packages/fontconfig.mk:3:$(package)_download_path=http://www.freedesktop.org/software/fontconfig/release/
./depends/packages/libXau.mk:3:$(package)_download_path=http://xorg.freedesktop.org/releases/individual/lib/
./depends/packages/bdb.mk:3:$(package)_download_path=http://download.oracle.com/berkeley-db
./depends/packages/libXext.mk:3:$(package)_download_path=http://xorg.freedesktop.org/releases/individual/lib/
```

**Comment by laanwj** [comment]
utACK, as issues with `apt` have shown, if in doubt it's better to use TLS, it's one extra layer of security.

**Comment by MarcoFalke** [comment]
Please squash your commits according to https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#squashing-commits

**Comment by dongcarl** [comment]
Could you add something to `depends/packages.md` so that future depends packages will be written with this in mind?

**Comment by Kemu** [comment]
> Could you add something to `depends/packages.md` so that future depends packages will be written with this in mind?

good idea.

 ```
   $(package)_download_path:
    Location of the upstream source, without the file-name. Usually http, https
    or ftp. Secure transmission options like https should be preferred if
    available.

```

**Comment by Kemu** [comment]
`make download` seems to run without issues, except for native_cdrkit:

```
Fetching cdrkit-1.1.11.tar.bz2 from https://distro.ibiblio.org/fatdog/source/600/c
...
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

while directly running:
`wget https://distro.ibiblio.org/fatdog/source/600/c/cdrkit-1.1.11.tar.bz2`
or
`curl https://distro.ibiblio.org/fatdog/source/600/c/cdrkit-1.1.11.tar.bz2 --output cdrkit-1.1.11.tar.bz2`
seem to work just fine.

Can anyone confirm this behavior in their environment?

The depends Makefile includes a fallback download path (https://bitcoincore.org/depends-sources), which is probably why the tests are not failing in any case.

**Comment by jonasschnelli** [comment]
Thanks.
utACK d8bc47fde46ca0711fa54a0d70ff5d066c708e50

**Comment by practicalswift** [comment]
Welcome as a contributor @Kemu! :-)

utACK d8bc47fde46ca0711fa54a0d70ff5d066c708e50

**Comment by dongcarl** [comment]
tACK d8bc47fde46ca0711fa54a0d70ff5d066c708e50

**Pull request merged**
