### PR TITLE
DragonFlyBSD thread renaming.

### PR DESCRIPTION
**Pull request by philmb3487**
I'm an idiot and closed the previous PR when I got confused with git, so here we go again.
Previous PR https://github.com/bitcoin/bitcoin/pull/6065.

### CODE REVIEW

**Comment by laanwj** [comment]
utACK

**Comment by luke-jr** [comment]
Is there really no common define for *BSD? :/

utACK

**Comment by laanwj** [comment]
Well when using a common flag there may be a SillyBSD that doesn't have this function. Enumerating them individually, though tedious, is safer.

**Comment by sinetek** [comment]
@luke-jr well there is no point in having a common flag when the interfaces all differ anyway. Here a few BSD's share this function, but that is certainly not the case across the board.

**Pull request merged**
