### PR TITLE
Docs: tweak the OSX build instructions

### PR DESCRIPTION
**Pull request by janstary**
This is a revision of doc/build-osx.md, tested on 10.13.2

* Don't dictate Homebrew, mention also MacPorts and Fink
* Drop a link to a nonexistent section
* Mention `./configre --prefix`,  `--disable-wallet` and  `--without-gui`
* Include `make install`
* Fix the `bitcoin.conf` instructions (the directory doesn't exist yet)

### CODE REVIEW

**Comment by janstary** [comment]
I tested the MacPort `port` instructions to install exactly the dependencies.
Can someone please also check the `brew` version? At least autoconf and zmq seem to be missing,
put perhaps in brew they get pulled in as further dependencies?
Can someone using Fink please cook the appropriate `fink` install line?

**Comment by jonasschnelli** [comment]
Thanks for contributing!
I think we should not mention that Bitcoin Core can be installed via brew. It looks like a recommendation and we really have no control whats in that package.

**Comment by fanquake** [comment]
Homebrew is just used because there are multiple devs using it, and we *know* it works. Will you maintain the port/fink instructions for future releases?

Have you checked/updated the configure.ac checks for port installed dependencies? We were going to remove those checks at one point, so they may be out of date. I’m not sure if anything special is required for fink?

Homebrew is also mentioned in other parts of the documentation, such as for installing testing dependencies. Do we need to add port/fink specific instructions in those places as well?

**Comment by janstary** [comment]
I only use MacPorts and can atest that this is how to install the dependencies.

The port as installed by MacPorts is simply version 0.14.1,
I am in the middle of udating it.

I don't use Homebrew or Fink, but they (and MacPorts) are the prevalent
packege managers for MacOS, so it seems relevant to mention them
s a way to install dependencies (or even Bitcoin Core itself).

**Comment by bekahoxoo** [comment]
I just did a fresh install using brew and everything worked as expected (besides a bunch of warnings of comparisons of numbers of inconsistent types), so can confirm all dependencies are pulled in at some point. Also, this may seem really trivial but could it be added that people may have to turn their adblock off to download the community version of qt? I thought I was on a wild goose chase!

**Comment by MarcoFalke** [comment]
Needs rebase if still relevant

**Comment by fanquake** [comment]
Closing for now. You can re-open when you've rebased, and addressed comments.

**Comment by janstary** [comment]
I will prepare a better PR based on 0.16.0

**Pull request closed without merging**
