### PR TITLE
Fixed link to Xcode 6.1.1

### PR DESCRIPTION
**Pull request by Michagogo**
Previous link was dead.

### CODE REVIEW

**Comment by Michagogo** [comment]
Updated: looks like you actually have to go through the main downloads page in order to get the cookie that you need for the download.

**Comment by fanquake** [comment]
This is a dupe of #6236 ?

**Comment by Michagogo** [comment]
This is a version of #6236 on the 0.11 branch rather than on master.

**Comment by fanquake** [comment]
A second pull request/commit isn't necessary, anything that needs to be backported will be done using your original commit. This should really be sent to the trivial branch either way.

**Comment by theuni** [comment]
Yep, what @fanquake said. #6236 was merged into trivial, so these can both be closed.

**Comment by Michagogo** [comment]
Trivial? Not sure I know what that means in this context. I don't really think it's trivial, though -- it's instructions fundamental to the OS X build that are nonfunctional.

**Comment by laanwj** [comment]
Closing, already merged through #6236 and #6238

**Pull request closed without merging**
