### PR TITLE
Trivial: Fix spelling in zapwallettxes test description

### PR DESCRIPTION
**Pull request by bitspill**

### CODE REVIEW

**Comment by promag** [comment]
ACK 174e88b.

Nit, both pull title and commit message could be more descriptive, like "[qa] Fix spelling in fundrawtransaction test description".

**Comment by bitspill** [comment]
Right, it was just a hasty commit via GitHub web UI, I've adjusted the commit message and pull title.

**Comment by MarcoFalke** [comment]
utACK 77678426000b88834ca0beb4353f20730b0f5510

**Review by randolf — APPROVED** [review]

**Comment by fanquake** [comment]
utACK 7767842

**Pull request merged**
