### PR TITLE
Documentation for the Qt Wallet GUI and Syncing

### PR DESCRIPTION
**Pull request by penguin1333**
Just commented a little bit around the Qt Wallet GUI and Syncing.

It's always nice for new developers to know what everything means :)

### CODE REVIEW

**Comment by laanwj** [comment]
I'm a huge proponent of documentation, but I'd like to suggest that if e.g. variable or method names are self-documenting there is no need to add an explicit comment. For example
```patch
+ // Window title
windowTitle += " " + networkStyle->getTitleAddText();
```
This doesn't provide any information. Adding to a variable named `windowTitle` already implies this. Better would be:
```patch
+ // Add the network name to the window title
windowTitle += " " + networkStyle->getTitleAddText();
```
Comments, and documentation, should be on a higher level of abstractness than the source code.

**Comment by prestotron** [comment]
You're right!

I'll work on it tomorrow :D

**Comment by prestotron** [comment]
@laanwj 

I have fixed the Qt Wallet GUI and added more detailed documentation. I'll get to the Syncing now.

**Comment by prestotron** [comment]
@laanwj 
Everything is now documented so it is not just saying what is already implied :)

I didn't fully document the sync.cpp but the GUI wallet file was. But either was, it is ready for merging :D

**Comment by laanwj** [comment]
Sorry - going to close this. The comments still don't add more information in most cases than is in the code itself, and are sometimes confusing.

**Pull request closed without merging**
