### PR TITLE
gitignore: plist and dat

### PR DESCRIPTION
**Pull request by jamesob**
Ignore anything ending in `.dat` and files generated by clang-check.

### CODE REVIEW

**Comment by fanquake** [comment]
utACK 17be9e0

**Comment by laanwj** [comment]
utACK 17be9e0e3037b60ba7bbf4b9249f2efc5e1ba9b3

some days I wish, that like `cmake`, autoconf would strongly encourage building out-of-tree, so that no so many random build artifacts end up in the git tree—this is always a growing set

**Comment by fanquake** [comment]
Backported in #15818.

**Comment by promag** [comment]
Running `git status` while `make` is running shows untracked files `*.o.tmp`. This one could be added too.

**Pull request merged**
