### PR TITLE
[trivial] Add .DSYM to .gitignore

### PR DESCRIPTION
**Pull request by fanquake**
Add debug symbols to .gitignore

### CODE REVIEW

**Comment by laanwj** [comment]
What OS is this for?

**Comment by btcdrak** [comment]
This is platform specific (OSX) and should be in your [global gitignore](https://help.github.com/articles/ignoring-files/#create-a-global-gitignore).

**Comment by laanwj** [comment]
@btcdrak I think we have more OS-specific stuff in there, .e.g `DS_store` and `*.exe`. I think the criterion should be whether the file is generated while following our supported build process.
If it is, it should be in our `.gitignore`.
If not, and it is part of some IDE or other user specific tool, it belongs in that user's gitignore.

Apart from that, at some point in our we should encourage in our build documentation doing out-of-tree builds so that it is no longer an issue.

**Comment by sipa** [comment]
@laanwj That sounds like a good criterion.

@fanquake Can you comment?

**Comment by theuni** [comment]
ACK @laanwj's comment.

**Comment by fanquake** [comment]
.DSYM are generated when running valgrind on OS X

**Comment by laanwj** [comment]
I'd say valgrind fits squarely into the 'other tools' category, it's not something we ever launch from the build system.

**Pull request closed without merging**
