### PR TITLE
Don't close old debug log file handle prematurely when trying to re-open (on SIGHUP)

### PR DESCRIPTION
**Pull request by practicalswift**
Don't close old debug log file handle prematurely when trying to re-open (on `SIGHUP`).

Context: https://github.com/bitcoin/bitcoin/pull/13148#issuecomment-386288606

Thanks @ajtowns!

### CODE REVIEW

**Comment by luke-jr** [comment]
utACK

**Review by luke-jr — APPROVED** [review]
utACK

**Comment by ajtowns** [comment]
Tested ACK 37efe5b7ea059e56d8f5170c91e3160db286cad4

To test:

```
$ bitcoind -regtest -daemon
$ cd ~/.bitcoin/regtest
$ mv debug.log{,.old}
$ touch debug.log; chmod 400 debug.log
$ killall -HUP bitcoind
$ bitcoin-cli -regtest savemempool
```

Current behaviour of master is that the "Dumped mempool" message (along with any other subsequent log messages), and further that fixing permissions on debug.log and HUP'ing the process isn't sufficient to re-enable logging.

With the patch, logging continues in debug.log.old, and after fixing the permissions HUP'ing the process causes logging to move to the new file.

**Comment by MarcoFalke** [comment]
utACK 37efe5b7ea059e56d8f5170c91e3160db286cad4

**Comment by practicalswift** [comment]
Rebased!

@luke-jr @ajtowns @MarcoFalke Please re-review :-)

**Comment by MarcoFalke** [comment]
re-utACK 75ea00f391b742e435c650aae3e827aad913d552

**Comment by ajtowns** [comment]
re-ACK 75ea00f391b742e435c650aae3e827aad913d552

**Pull request merged**
