### PR TITLE
readme: Omit phrasing; 'new'

### PR DESCRIPTION
**Pull request by wbnns**
Since Bitcoin has been around now for over seven years and has a $10
Billion+ market capitalization, just wanted to submit this PR for review
to remove the mentioning in the opening paragraph of the README that
states that it is "an experimental new digital currency" to instead read
"a digital currency" (in case you all are OK w/ this).

Alternatively, if you all would like to revise further, please let me
know and I will amend my commit, or feel free to close if it should be
left unchanged. Thanks in advance for the review!

### CODE REVIEW

**Comment by paveljanik** [comment]
See #7173 for previous discussion.

**Comment by sipa** [comment]
I'm fine with removing 'new'. See Marco's answer about removing
'experimental'.

**Comment by paveljanik** [comment]
Yup, +1 for removing new 👍

**Comment by wbinns** [comment]
@paveljanik @sipa Ok, thanks for the feedback and apologies for missing the previous discussion. I've updated this PR accordingly to align it with your comments.

**Comment by laanwj** [comment]
Yes, leave experimental, agree on removing new (although both are subjective and relative - bitcoin is still a lot newer than say, the use of debt-backed bank notes).

**Pull request merged**
