### PR TITLE
test: wallet migration, add coverage for tx extra data

### PR DESCRIPTION
**Pull request by furszy**
Quick follow-up to #28610, coming from https://github.com/bitcoin/bitcoin/pull/28610#pullrequestreview-1802823938.

Verifying that the 'replaced_by_txid' and 'replaces_txid' tx data is preserved after migration,
as well as the extra tx comments.

### CODE REVIEW

**Comment by jamesob** [comment]
Nice, ACK https://github.com/bitcoin/bitcoin/pull/29204/commits/016cc807f77a9128d430a0df1edd133521628a33

**Review by pablomartin4btc — COMMENTED** [review]
ACK 016cc807f77a9128d430a0df1edd133521628a33

**Review by BrandonOdiwuor — APPROVED** [review]
lgtm ACK 016cc807f77a9128d430a0df1edd133521628a33

**Comment by achow101** [comment]
ACK 016cc807f77a9128d430a0df1edd133521628a33

**Pull request merged**
