### PR TITLE
doc: correct bitcoinconsensus_version in shared-libraries.md

### PR DESCRIPTION
**Pull request by fanquake**
https://github.com/bitcoin/bitcoin/blob/efbc86733a551f2e1f5c43cd6de4fc730c7cce65/src/script/bitcoinconsensus.h#L36

### CODE REVIEW

**Comment by practicalswift** [comment]
ACK 8ae6d020b83572235f85ee68ce87045f2e97cbc0

**Comment by Empact** [comment]
How about remove it entirely?

**Comment by luke-jr** [comment]
Nah, it's good to know what API version the file is documenting.

Recently wrote a FUSE filesystem, and found it annoying that they had API changes after the library on my system, but there was no way to tell which API each version of the tutorial(s) were written for.

**Comment by promag** [comment]
ACK 8ae6d02.

**Comment by laanwj** [comment]
> Nah, it's good to know what API version the file is documenting.

:+1:

**Pull request merged**
