### PR TITLE
rpc: Correctly name arguments

### PR DESCRIPTION
**Pull request by maflcko**
Consistently use the same name to describe arguments in the documentation and add a test that uses the name.

By splitting it up, the changes are easier to potentially backport and also make review easier when we switch to `RPCHelpMan`.

The tests should pass with or without the changes in `src`.

Partly stolen from #14459 (More RPC help description fixes by ch4ot1c)

### CODE REVIEW

**Comment by MarcoFalke** [comment]
cc @ch4ot1c

**Comment by MeshCollider** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/14720/commits/fa0815c3005c861ba94b96412e7997c25e7f6788

**Comment by practicalswift** [comment]
Concept ACK

Nice cleanup!

**Comment by laanwj** [comment]
Makes sense, though I guess the idea eventually would be to use the just-merged `RPCHelpMan` here?

**Comment by MarcoFalke** [comment]
By splitting it up, the changes are easier to potentially backport and also make review easier when we switch to `RPCHelpMan`.

**Review by ryanofsky — APPROVED** [review]
utACK fa0815c3005c861ba94b96412e7997c25e7f6788

**Pull request merged**
