### PR TITLE
bench: Added base58 encoding/decoding benchmarks

### PR DESCRIPTION
**Pull request by rodentrabies**
One of the subtasks for #7883

### CODE REVIEW

**Comment by dcousens** [comment]
This repository or https://github.com/bitcoin/libbase58?

**Comment by yurizhykin** [comment]
This one: benches for encode/decode functions from src/base58.cpp

**Comment by fanquake** [comment]
Some output from three runs.
```
Base58CheckEncode,262143,3.82133e-06,1.50204e-05,3.92075e-06
Base58Decode,720895,1.46078e-06,1.19209e-05,1.48342e-06
Base58Encode,425983,2.38232e-06,1.3113e-05,2.44177e-06
````

```
Base58CheckEncode,262143,3.86023e-06,1.50204e-05,3.93022e-06
Base58Decode,720895,1.45659e-06,1.09673e-05,1.49511e-06
Base58Encode,425983,2.38605e-06,1.3113e-05,2.45076e-06
```

```
Base58CheckEncode,262143,3.85736e-06,5.96046e-06,3.89876e-06
Base58Decode,720895,1.44076e-06,1.19209e-05,1.48369e-06
Base58Encode,425983,2.38419e-06,1.3113e-05,2.46816e-06
```

**Comment by jonasschnelli** [comment]
Nice!
utACK 5fac1f33fb5afad4cbcb51b7c85ab2cd759846e1

**Comment by laanwj** [comment]
utACK https://github.com/bitcoin/bitcoin/commit/5fac1f33fb5afad4cbcb51b7c85ab2cd759846e1

**Pull request merged**
