### PR TITLE
util: Replace std::filesystem with util/fs.h

### PR DESCRIPTION
**Pull request by maflcko**
Using `std::filesystem` is problematic:

* There is a `fs` namespace wrapper for it. So having two ways to achieve the same is confusing.
* Not using the `fs` wrapper is dangerous and buggy, because it disables known bugs by deleting problematic functions.

Fix all issues by removing use of it and adding a linter to avoid using it again in the future.

### CODE REVIEW

**Comment by hebasto** [comment]
Will it be the first Rust code in our codebase?

**Comment by kristapsk** [comment]
Why to introduce Rust as additional dependency just for the linter code?

**Comment by kristapsk** [comment]
> Because I don't think it is a good use of developer and reviewer time to write not type-safe code, only to later (after review or merge) discover that it crashes with a `TypeError`.

Why not just use C++ then? (I'm not a Rust expert, maybe there are good reasons)

>  I can't recall the last time I've run any linter outside of testing one after writing the code for it.

I try always to remember running linters locally before submitting a new PR (sometimes I fail and forget, need to admit).

**Comment by TheCharlatan** [comment]
I'd love for Rust to be "backdoored" into the project, but I am not sure if adding yet another linting infrastructure is the right way to do this. 

What does this check do that a check with a clang-tidy plugin could not? I have pushed a dirty prototype (likely incomplete) for such a plugin check here: https://github.com/TheCharlatan/bitcoin-tidy-experiments/commit/5c1f1e1289758df4a0407cddcfd1f8b043c53be9. It checks for declarations of std::filesystem::path, and calls to its string method. It also showcases some of the pre-processor checks that it can do. In this case, it checks if `<filesystem>` is included, and whether `std::filesystem` can be found anywhere in the source file text.

The tradeoff is obviously the readability of the code and that there might be some declaration edge cases that are not caught by them. A simple git-grep will always be a decent catch-all, but might miss certain declarations, or be unable to distinguish between comment and code. What do you think?

**Review by luke-jr — CHANGES_REQUESTED** [review]
Standing Concept NACK to Rust while it has security issues (unbootstrappable)

"It's just for CI" - but we shouldn't be relying on CI alone.

**Comment by fanquake** [comment]
ACK fa8d99d8932df08320f1bfb4e8f1d4b4169466fd (first commit)

I have no issues with Rust, or using it in the CI; we already do in other CIs in the Bitcoin Core project. Saying that, I'm not sure if we want to introduce a 4th way to do linting in this repo (yet). One potential alternative, if we go further down the clang-tidy route, is the `<filesystem>` linter here: https://github.com/fanquake/bitcoin/commits/integrate_thecharlatan_filesystem, put together by @TheCharlatan.

**Comment by fanquake** [comment]
> Currently the following is used:

Did you exclude clang-tidy here, or is it part of the list in the quote later in your comment. We already use it for linting, and my plan is to migrate more checks too it. For example, we can replace our python based assert linter (and more) with the equivalent clang-tidy check (LLVM 17 though).

**Comment by luke-jr** [comment]
>Simply claiming this doesn't seem helpful. What is the compile error you encountered? (Ideally with steps to reproduce)

The several issues bootstrapping Rust are well-known and documented elsewhere. Fixing it is not within the scope of this project. It simply shouldn't be relied on until then.

**Comment by fanquake** [comment]
I don't think we are going to get the Rust linter over the line here. Obviously the filesystem commit is correct, and should be merged. Do you want to split that out, and continue the lint discussion, or drop the linter from this PR for now?

**Comment by fanquake** [comment]
> Seems better to keep the discussion in one place for now.

Ok, but the discussion of introducing Rust into the codebase (in whatever form) is clearly contentious, and shouldn't be a blocker for merging obvious bug fixes.

**Comment by fanquake** [comment]
I would just like to remove the

> confusing and potentially dangerous,

code. I don't see how that is predicated on, or needs to wait for a Rust based linter. Happy to ACK the first commit.

**Comment by TheCharlatan** [comment]
Concept ACK

**Review by sedited — APPROVED** [review]
ACK  bbbbdb0cd57d75a06357d2811363d30a498f4499

**Review by fanquake — APPROVED** [review]
ACK bbbbdb0cd57d75a06357d2811363d30a498f4499 🦀

**Comment by luke-jr** [comment]
This remains NACK'd and should not have been merged. Please revert it ASAP.

**Comment by Retropex** [comment]
The integration of Rust into Core, further increases the technical debt. Each person's ability to run tests locally is essential, and relying on CIs to manage Rust code is not a viable solution. In addition, introducing Rust can encourage the addition of other languages, risking fragmenting and further complicating the code base.

**Pull request merged**
