### PR TITLE
Update linearize-hashes.py

### PR DESCRIPTION
**Pull request by OverlordQ**
Fix class case issue.

### CODE REVIEW

**Comment by promag** [comment]
ACK 7fdb92e.

**Comment by MarcoFalke** [comment]
Would be nice if this script was tested in ci or otherwise.

**Comment by laanwj** [comment]
Thanks for fixing this!

For next time, please use a PR title that summarizes the change, "Update linearize-hashes.py" isn't very useful to have in the commit log!

**Comment by MarcoFalke** [comment]
Sorry, my bad. I missed to fix it up before merge.

**Pull request merged**
