### PR TITLE
Use a semaphore or pipe for shutdown notification (skeees, laanwj)

### PR DESCRIPTION
**Pull request by laanwj**
Instead of polling, use a semaphore (on WIN32) or a pipe (on POSIX) for shutdown notification. This avoids the need for a polling loop in bitcoind.

Extends #13186.

This does not change the polilng of `ShutdownRequested()` in the GUI. This is more complicated: on POSIX it would be possible to import the `pipe[0]` handle into the event loop, and call a handler when a character is detected, on Windows the `StartShutdown()` could make a callback that queues a qt signal at the GUI side. But I think that is better left for a later PR.

### CODE REVIEW

**Comment by skeees** [comment]
Oh cool - if you are going to split into platform dependent code - you can post to a pthreads semaphore from a unix signal handler. 
Would also suggest that anyone waiting/reading from the semaphore/pipe immediately post/write back that way you could have multiple threads listening for shutdown as opposed to restricting it to only one as you do currently

**Comment by laanwj** [comment]
>  you can post to a pthreads semaphore from a unix signal handler.

I'm fairly sure none of the pthreads-api is signal safe, at least on all platforms.

> Would also suggest that anyone waiting/reading from the semaphore/pipe immediately post/write back that way you could have multiple threads listening for shutdown as opposed to restricting it to only one as you do currently

We only need to wait for shutdown in one thread, so as I see it that additional complexity is not needed. If it happens to be needed in the future it can be added then.

**Comment by laanwj** [comment]
Added a commit that reverts 793667a  (#11006) to hopefully make travis pass. Likely, this has to be conditional on libevent version to prevent adding a delay on shutdown in another place.

**Comment by ken2812221** [comment]
Maybe that shutdown is too quit, add 50ms delay?

**Comment by laanwj** [comment]
> Maybe that shutdown is too quick, add 50ms delay? It failed on my machine occasionally

Adding a fixed delay is never a valid solution.

**Comment by ken2812221** [comment]
Once `StopHTTPServer` has been called in main thread ,the event loop in http thread exit. But http workqueue thread needs to use the event loop to call `evhttp_send_reply`, this could happen after the http thread event loop exit.

**Comment by laanwj** [comment]
Closing this for now, I don't think it's that important, the current way works fine.

**Pull request closed without merging**
