### PR TITLE
build: Remove libssl from LDADD unless gui

### PR DESCRIPTION
**Pull request by maflcko**
libssl is only used by the gui, so no need to LDADD it to the other tools and binaries

Follow up of the commit which removed rpcssl: 40b556d3742a1f65d67e2d4c760d0b13fe8be5b7

### CODE REVIEW

**Comment by practicalswift** [comment]
utACK fa328ae9133b257e93a85db31df568b792c44bd5

**Comment by laanwj** [comment]
right, bitcoind needs libcrypto not libssl
utACK fa328ae9133b257e93a85db31df568b792c44bd5

**Comment by laanwj** [comment]
BTW—are you sure bitcoin-qt does need libssl, or does it only use it through qt? I know it uses some OpenSSL functionality directly but not from what library.

**Comment by laanwj** [comment]
at the least it could be removed from `src/Makefile.test.include` as well

**Comment by Sjors** [comment]
If you're completely purging it, can `libssl.pc` also be removed from `depends/packages/openssl.mk`?

Succesfully compiled and lightly tested 23ec611 on macOS 10.13.6, including opening a BIP-71 payment request.

**Comment by laanwj** [comment]
> If you're completely purging it, can libssl.pc also be removed from depends/packages/openssl.mk?

I don't think removing it from depends is safe—Qt is still relying on it for `https://` connections, which are necessary for BIP70. It's just we have no *direct* dependency on it anymore.

**Comment by Sjors** [comment]
@laanwj are you sure QT isn't using openssl instead of libssl? I'm generally confused by the distinction, but the QT [docs](http://doc.qt.io/qt-5/ssl.html) mention:

> When building Qt from source, the configuration system checks for the presence of the openssl/opensslv.h header provided by source or developer packages of OpenSSL.

**Comment by ken2812221** [comment]
@Sjors libssl is a part of openssl

**Comment by laanwj** [comment]
> @laanwj are you sure QT isn't using openssl instead of libssl? I'm generally confused by the distinction, but the QT docs mention:

As I understand it, OpenSSL  is a combination of two libraries, "libcrypto" and "libssl", the first handles cryptography and certificate operations and randomness, the second networking. Our project uses only the former, which is why this PR works, however Qt (the library) uses both, as it handles both cryptography and TLS/SSL network conections.

I could be misunderstanding it, though.

**Comment by jnewbery** [comment]
utACK b0e2411144c1204793ed25e598963c7d8eae12f6

**Comment by Sjors** [comment]
@ken2812221 @laanwj you're right, `openssl/opensslv.h` indeed refers to the whole kitchen sink, I misread the README:
schermafbeelding 2018-09-13 om 20 56 38

**Comment by MarcoFalke** [comment]
@laanwj Your branch to remove it altogether seems to fail: https://travis-ci.org/bitcoin/bitcoin/builds/428326156 (Note the included libssl header in the qt tests file: 6e996d3)

**Comment by laanwj** [comment]
@MarcoFalke argh—so it looks like that when Qt is linked statically, as in gitian, it relies on the bitcoin build pulling `-lssl` in. This is no problem when building against qt dynamically, which is why I didn't notice before.

**Comment by MarcoFalke** [comment]
Ah, anyway. I removed the SSL_LIB from test_bitcoin as you suggested (and some other changes as well)

**Review by ken2812221 — APPROVED** [review]
utACK cccc362d62b0ba9475b1ac47d5908f77f7eb5d21

**Comment by MarcoFalke** [comment]
I am going to merge this after the gitian build returns

**Comment by laanwj** [comment]
+1

**Pull request merged**
