### PR TITLE
[0.12] Backport: Torcontrol debug msg

### PR DESCRIPTION
**Pull request by maflcko**

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Is it worth to backport this translation change? At least it would require new translations?

**Comment by MarcoFalke** [comment]
Translations are final for 0.12.0. This should only affect debug.log, which does not translate.

**Comment by jonasschnelli** [comment]
Ah. Right.

ACK.

**Comment by fanquake** [comment]
ACK. Are you planning on adding more commits? If not, please change the PR title.

**Pull request merged**
