### PR TITLE
index: coinstats reorg, fail when block cannot be reversed

### PR DESCRIPTION
**Pull request by furszy**
Found it while reviewing https://github.com/bitcoin/bitcoin/pull/24230#discussion_r1310863359.

During a reorg, continuing execution when a block cannot be reversed leaves the
coinstats index in an inconsistent state.
This was surely overlooked when 'CustomRewind' was implemented.

### CODE REVIEW

**Comment by fanquake** [comment]
cc @ryanofsky @mzumsande

**Review by ryanofsky — APPROVED** [review]
Code review ACK eef595560e9ecf3a0d1db4d8ea7ecc33a49d839f

This seems like it should avoid corrupting the index if ReverseBlock fails, since it avoid writing the best block. It also could prevent assert failures because it avoids subsequent ReverseBlock calls.

It would be good to add [[nodiscard]] to Reverseblock and other functions in indexing code to prevent this problem from happening other places. Grepping a little for functions in src/index/ that write to the database and return bool I see `TxIndex::DB::WriteTxs` and `CopyHeightIndexToHashIndex` and there may be others.

**Review by sedited — APPROVED** [review]
ACK eef595560e9ecf3a0d1db4d8ea7ecc33a49d839f

As said, adding `nodiscard` would be nice.

**Comment by fanquake** [comment]
> It would be good to add [[nodiscard]] to Reverseblock and other functions in indexing code to prevent this problem from happening other places. Grepping a little for functions in src/index/ that write to the database and return bool I see TxIndex::DB::WriteTxs and CopyHeightIndexToHashIndex and there may be others.

> As said, adding nodiscard would be nice.

@furszy do you want to push an additional commit?

**Review by furszy — COMMENTED** [review]
> > It would be good to add [[nodiscard]] to Reverseblock and other functions in indexing code to prevent this problem from happening other places. Grepping a little for functions in src/index/ that write to the database and return bool I see TxIndex::DB::WriteTxs and CopyHeightIndexToHashIndex and there may be others.
> 
> > As said, adding nodiscard would be nice.
> 
> @furszy do you want to push an additional commit?

yep, pushed. A bit late due time zone diff.

Thanks both!

**Review by ryanofsky — APPROVED** [review]
Code review ACK c0bf667912064960df194ea94150976b34f7c267. Only change since last review is new commit adding [[nodiscard]]

**Pull request merged**
