### PR TITLE
cmake: add `USE_SOURCE_PERMISSIONS` to all `configure_file()` usage

### PR DESCRIPTION
**Pull request by fanquake**
`USE_SOURCE_PERMISSIONS` is the default, so this should not change behaviour. However, being explicit makes it clear what we are doing.

Related to #30815.

See https://cmake.org/cmake/help/latest/command/configure_file.html#options.

### CODE REVIEW

**Comment by hebasto** [comment]
Could variations in the source directory permissions actually cause https://github.com/bitcoin/bitcoin/issues/30815?

**Comment by fanquake** [comment]
Guix Build:
```bash
f2e883f15be3d30cc27f1e5ba96ccaa18a9201a242f6dfa7bc65595192249f47  guix-build-1f054eca4e77/output/arm64-apple-darwin/SHA256SUMS.part
53379e0ac143a7c150563ac10973ee7af5dc827e53f96a8b2519cdf1992ece63  guix-build-1f054eca4e77/output/arm64-apple-darwin/bitcoin-1f054eca4e77-arm64-apple-darwin-unsigned.tar.gz
8446ce177d54bac5b185faaecf7a7f34590b512b8ffc690f43d461418196f99c  guix-build-1f054eca4e77/output/arm64-apple-darwin/bitcoin-1f054eca4e77-arm64-apple-darwin-unsigned.zip
8839217f2f97adf2ff5c6b88918bd07019dda003d697feb226d0c0a3bf98804e  guix-build-1f054eca4e77/output/arm64-apple-darwin/bitcoin-1f054eca4e77-arm64-apple-darwin.tar.gz
e77d11cd53af8b37a524ab3b649deb027f530e9ffb9a98ab1f5a276f9f8dcaac  guix-build-1f054eca4e77/output/dist-archive/bitcoin-1f054eca4e77.tar.gz
```

**Comment by TheCharlatan** [comment]
Looks like this is not the solution for the reproducibility issue:
```
972bb22e9c3e5fc8858c8351dae323000604cc05dc1bb2b24a35c558d5c20c5d  guix-build-1f054eca4e77/output/arm64-apple-darwin/SHA256SUMS.part
53379e0ac143a7c150563ac10973ee7af5dc827e53f96a8b2519cdf1992ece63  guix-build-1f054eca4e77/output/arm64-apple-darwin/bitcoin-1f054eca4e77-arm64-apple-darwin-unsigned.tar.gz
34439d69eb914fb4e758af68f7ee543da1305409621ff34df0b95d785ba03ba3  guix-build-1f054eca4e77/output/arm64-apple-darwin/bitcoin-1f054eca4e77-arm64-apple-darwin-unsigned.zip
8839217f2f97adf2ff5c6b88918bd07019dda003d697feb226d0c0a3bf98804e  guix-build-1f054eca4e77/output/arm64-apple-darwin/bitcoin-1f054eca4e77-arm64-apple-darwin.tar.gz
e77d11cd53af8b37a524ab3b649deb027f530e9ffb9a98ab1f5a276f9f8dcaac  guix-build-1f054eca4e77/output/dist-archive/bitcoin-1f054eca4e77.tar.gz
```
Might be a good idea in any case though.

**Review by hebasto — APPROVED** [review]
ACK 1f054eca4e779cfa5f9f6e9278071adf65e5eafe.

> Looks like this is not the solution for the reproducibility issue

The PR description rightfully stated that "this should not change behaviour".

**Review by sedited — APPROVED** [review]
ACK 1f054eca4e779cfa5f9f6e9278071adf65e5eafe

**Comment by hebasto** [comment]
If https://github.com/bitcoin/bitcoin/pull/30838 happens to fix https://github.com/bitcoin/bitcoin/issues/30815, it seems reasonable to switch to `NO_SOURCE_PERMISSIONS` in all cases for consistency.

**Comment by fanquake** [comment]
> If https://github.com/bitcoin/bitcoin/pull/30838 happens to fix https://github.com/bitcoin/bitcoin/issues/30815, it seems reasonable to switch to NO_SOURCE_PERMISSIONS in all cases for consistency.

I'm going to merge this, and we can follow up in #30838, and decide if we to change all call sites, or just those needed for reproducibility. That PR will also need to be updated with an explantion of why this started happening, and the fix (I assume there should be no issue always using CMakes default permissions as opposed to our perms, but that should also be mentioned).

**Pull request merged**
