### PR TITLE
Fix createrawtransaction multi op return - issue #14868

### PR DESCRIPTION
**Pull request by isghe**
fix issue https://github.com/bitcoin/bitcoin/issues/14868

### CODE REVIEW

**Comment by gmaxwell** [comment]
NAK.  Network IsStandard rules prohibit multiple op_returns (https://github.com/bitcoin/bitcoin/blob/master/src/policy/policy.cpp#L135), additional bloat on the blockchain is also not desired. The inputs to this RPC are also an array, so duplicating inputs is also pretty broken.

**Comment by isghe** [comment]
@gmaxwell so maybe we should raise an error? Because actually it's producing a strange thing
```
bitcoin-cli createrawtransaction "[]" "{\"data\":\"ee\", \"data\":\"ff\"}"
0200000000020000000000000000036a01ee0000000000000000036a01ee00000000
```

**Comment by Empact** [comment]
@isghe you can help review by making your PR minimal:
> Patchsets should always be focused. For example, a pull request could add a feature, fix a bug, or refactor code; but not a mixture.
https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#pull-request-philosophy

**Comment by isghe** [comment]
https://github.com/isghe/bitcoin/commits/raise-error-createrawtransaction-multi-OP_RETURN 
just adding on this PR
```c++
    const CTransaction rawTxCopy (rawTx);
    std::string error;
    if (!IsStandardTx (rawTxCopy, error)) {
        throw JSONRPCError(RPC_INVALID_PARAMETER, "Invalid parameter combination: " + error);
    }
```
obtaining:
```
$ ./src/bitcoin-cli createrawtransaction "[]" "[{\"mguLQ6eGCHpnmRrDwAjbPpYAHjxY6GneeQ\":\"0.1\"}, {\"data\":\"ee\"}, {\"muLYgM1L3gCzLs1bPX5cVzx3ax1f4vBcpN\":\"0.2\"},{\"data\":\"ff\"}]" | xargs ./src/bitcoin-cli decoderawtransaction
error code: -8
error message:
Invalid parameter combination: multi-op-return
```

**Comment by Empact** [comment]
5987b7cadd15cd1b524fec430868ee0c174f06da makes sense to me, independent of this issue. Calls for another PR IMO.

**Comment by isghe** [comment]
@Empact my idea, is that `createrawtransaction` should check if a transaction is standard or not, just delegating to `IsStandardTx` function. If not, we are spreading the rules in the source code, and  doesn't sound good. At this point I think it would be better to create a PR removing hard-code rule written in `createrawtransaction`, delegating the all things to `IsStandardTx`. I'll work on it, in the weekend.

**Comment by isghe** [comment]
anyway, `createrawtransaction` could be created as an external tool.

**Comment by Empact** [comment]
@isghe to get this done safely and most easily, I recommend approaching this incrementally, e.g.:
1) fixing the immediate issue
2) applying the `IsStandardTx` check to `createrawtransaction`
3) removing the then-redundant checks

**Comment by promag** [comment]
NACK, this changes nothing.

**Comment by isghe** [comment]
@gmaxwell thanks for the explanation. I think we can close this PR.

**Pull request closed without merging**
