### PR TITLE
wallet: Receive silent payment transactions

### PR DESCRIPTION
**Pull request by achow101**
This PR implements receiving silent payment transactions through the use of a new `ScriptPubKeyMan` type: `SilentPaymentsSPKM`. This is a descriptor wallet only feature, although it does not use descriptors.

This is an optional feature, so the only way to use it is to create a new wallet with `createwallet` with `silent_payments=true`. Such wallets will have a single `SilentPaymentsSPKM` that is used for both receiving and change. Since silent payments only have a single address, repeated calls to `getnewaddress` and `getrawchangeaddress` always return the same address, however the receiving and change addresses are different, see the BIP for how the change is generated.

Since silent payments requires the spent coins in order to extract public keys from them, `TransactionAddedToMempool` is modified to also provide that information. For scanning blocks, the wallet will retrieve that information from the undo data. Additionally, when rescanning, a silent payments wallet must use the slow rescan method.

The labels feature has not been fully implemented yet and is left for a followup.

Based on #28122 and #28201 

Alternative to #28202

### CODE REVIEW

**Comment by luke-jr** [comment]
Approach NACK.

1. It should be possible to use silent payments without a new/different wallet.
2. `getnewaddress` should never return the same thing twice (absent a new option explicitly requesting that behaviour).

**Comment by achow101** [comment]
> It should be possible to use silent payments without a new/different wallet.

Upgrading will be possible to implement after #26728. Note that it is currently difficult to upgrade a descriptor wallet created before Taproot's activation to be able to give out Taproot addresses. #25907 (which depends on #26728) resolves that issue, and I would prefer to have upgrade paths for both new descriptor types and for silent payments that use approximately the same code paths rather than a bespoke solution.

> `getnewaddress` should never return the same thing twice (absent a new option explicitly requesting that behaviour).

It's not clear to me what the interface for this should look like, other than just a completely new RPC? I'm working on implementing the labels part of silent payments so it would not always be the same address, just optionally if the user has chose to apply a label.

**Comment by josibake** [comment]
> It's not clear to me what the interface for this should look like, other than just a completely new RPC? I'm working on implementing the labels part of silent payments so it would not always be the same address, just optionally if the user has chose to apply a label

In an older draft, we did implement a new RPC `getsilentpaymentaddress`, which could also take a label argument. Testers and reviewers seemed to like that approach better. Personally, I prefer using `getnewaddress` and I think passing the output type of "silent-payment" makes it clear enough that this is a static payment code. The reason I like this approach better is it avoids introducing a new RPC that will only be used by a handful of users. Seems annoying to have an RPC that just doesn't work 90% of the time. But I'd be happy with either approach.

**Comment by achow101** [comment]
Discussion at CoreDev concluded that using a descriptor for receiving is probably still useful. Will rework this to do that later (after 26.0 release probably).

**Comment by josibake** [comment]
running on signet, `bitcoin-cli rescanblockchain` with a silent payments wallet causes the node to crash, but `bitcoin-cli rescanblockchain 63482` (chain tip - 100,000 blocks) worked. will investigate more

**Comment by achow101** [comment]
Closing for now as up for grabs as I don't have time to work on this.

With having a silent payments module in libsecp, and also the plan to change this to using a descriptor, a lot of this PR is also no longer relevant.

**Pull request closed without merging**
