### PR TITLE
Add missing mempool lock for CalculateMemPoolAncestors

### PR DESCRIPTION
**Pull request by TheBlueMatt**

### CODE REVIEW

**Comment by instagibbs** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/9578/commits/852f5c1a4500845f7b5f8963fca2e3ef9018482c

**Comment by laanwj** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/9578/commits/852f5c1a4500845f7b5f8963fca2e3ef9018482c

**Comment by morcos** [comment]
Should we add AssertLockHeld in CalculateMemPoolAncestors

**Comment by MarcoFalke** [comment]
utACK b2afa4b41cbc91f0fbc36761dadc013e38ad0e53 (travis failure unrelated)

**Comment by MarcoFalke** [comment]
The tests are missing a `LOCK(mempool.cs)` as well, is what travis is trying to tell us.

**Comment by TheBlueMatt** [comment]
Turns out ATMP didnt lock it either, so I just added the LOCK there.

**Comment by morcos** [comment]
utACK 003cd60

**Comment by TheBlueMatt** [comment]
Needs 0.14 tag.

**Comment by gmaxwell** [comment]
utACK

**Pull request merged**
