### PR TITLE
Avoid integer overflow in CheckDiskSpace

### PR DESCRIPTION
**Pull request by dergoegge**
Starting a fresh node with `-prune=1` causes an integer overflow to happen in `CheckDiskSpace` ([here](https://github.com/bitcoin/bitcoin/blob/f7bdcfc83f5753349018be3b5a663c8923d1a5eb/src/init.cpp#L1633-L1648)) because `nPruneTarget` is to the max `uint64_t` value.
```
 node1 stderr util/system.cpp:138:51: runtime error: unsigned integer overflow: 52428800 + 18446744073709551615 cannot be represented in type 'unsigned long'
    #0 0x564a482b5088 in CheckDiskSpace(fs::path const&, unsigned long) src/./src/util/system.cpp:138:51
    #1 0x564a4728dc59 in AppInitMain(node::NodeContext&, interfaces::BlockAndHeaderTipInfo*) src/./src/init.cpp:1639:14
    #2 0x564a47256e6a in AppInit(node::NodeContext&, int, char**) src/./src/bitcoind.cpp:221:43
    #3 0x564a47256087 in main src/./src/bitcoind.cpp:265:13
    #4 0x7fcb7cbffd8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: 69389d485a9793dbe873f0ea2c93e02efaa9aa3d)
    #5 0x7fcb7cbffe3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e3f) (BuildId: 69389d485a9793dbe873f0ea2c93e02efaa9aa3d)
    #6 0x564a471957f4 in _start (/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/src/bitcoind+0xca07f4) (BuildId: 035cb22302d37317a630900a15a26ecb326d395c)
SUMMARY: UndefinedBehaviorSanitizer: unsigned-integer-overflow util/system.cpp:138:51 in 
```

I think side stepping the overflow for this specific case, is better than adding an exception to the UB suppresions file.

### CODE REVIEW

**Comment by martinus** [comment]
How about setting `nPruneTarget` to something smaller, like `std::numeric_limits<uint64_t>::max() / 2`? That's still large enough

**Comment by vasild** [comment]
Just for reference, like @MarcoFalke pointed above:

```
 node1 stderr util/system.cpp:138:51: runtime error: unsigned integer overflow: 52428800 + 18446744073709551615 cannot be represented in type 'unsigned long'
    #0 0x564a482b5088 in CheckDiskSpace(fs::path const&, unsigned long) src/./src/util/system.cpp:138:51
    #1 0x564a4728dc59 in AppInitMain(node::NodeContext&, interfaces::BlockAndHeaderTipInfo*) src/./src/init.cpp:1639:14
    #2 0x564a47256e6a in AppInit(node::NodeContext&, int, char**) src/./src/bitcoind.cpp:221:43
    #3 0x564a47256087 in main src/./src/bitcoind.cpp:265:13
    #4 0x7fcb7cbffd8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: 69389d485a9793dbe873f0ea2c93e02efaa9aa3d)
    #5 0x7fcb7cbffe3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e3f) (BuildId: 69389d485a9793dbe873f0ea2c93e02efaa9aa3d)
    #6 0x564a471957f4 in _start (/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/src/bitcoind+0xca07f4) (BuildId: 035cb22302d37317a630900a15a26ecb326d395c)
SUMMARY: UndefinedBehaviorSanitizer: unsigned-integer-overflow util/system.cpp:138:51 in 
```

**Comment by dergoegge** [comment]
> Should be trivial to add a test, no?

- I don't want to add a new functional test just for this.
- I tried to add a unit test but all our testing setups don't use the actual init logic.
- Maybe it can be added to one of the existing functional tests that do pruning, but I don't know which one. I tried but it always ends up being a bigger change to the test than I think would be justified for this trivial change.

If you know an easy way to add a test let me know, happy to add it.

**Comment by dergoegge** [comment]
> How about setting nPruneTarget to something smaller, like std::numeric_limits<uint64_t>::max() / 2? That's still large enough

@martinus That wouldn't quite work because `CheckDiskSpace` would return false then, given that `std::numeric_limits<uint64_t>::max() / 2 + 50MB` would likely not be available in free disk space on any system (https://github.com/bitcoin/bitcoin/blob/1884b71b1dc1fe463a2f00e61bcc56e4720cbc69/src/util/system.cpp#LL138). Currently the overflow works out because it just ends up checking that `50MB` are available.

**Review by maflcko — APPROVED** [review]
lgtm

**Review by maflcko — APPROVED** [review]
ACK 05eeba2c5fb312e0e6a730b01eb7d1b422d75dbb 🥝

<details><summary>Show signature</summary>

Signature:

```
untrusted comment: signature from minisign secret key on empty file; verify via: minisign -Vm "${path_to_any_empty_file}" -P RWTRmVTMeKV5noAMqVlsMugDDCyyTSbA3Re5AkUrhvLVln0tSaFWglOw -x "${path_to_this_whole_four_line_signature_blob}"
RUTRmVTMeKV5npGrKx1nqXCw5zeVHdtdYURB/KlyA/LMFgpNCs+SkW9a8N95d+U4AP1RJMi+krxU1A3Yux4bpwZNLvVBKy0wLgM=
trusted comment: ACK 05eeba2c5fb312e0e6a730b01eb7d1b422d75dbb 🥝
ldqnydo8QCYst0rz5DHKllo5bSa1wtQwO0yxrHDUxZFuBdkdTde53ru7wlcgYhRrGK2WIJyKmNEgbQMF7paMCg==
```

</details>

**Review by john-moffett — APPROVED** [review]
ACK 05eeba2c5fb312e0e6a730b01eb7d1b422d75dbb

**Comment by vasild** [comment]
ACK 05eeba2c5fb312e0e6a730b01eb7d1b422d75dbb

**Pull request merged**
