### PR TITLE
Update luke-jr's PGP key

### PR DESCRIPTION
**Pull request by luke-jr**
Same key, extended expiration date

### CODE REVIEW

**Comment by laanwj** [comment]
ACK 0d53a9e72f9694e84344f230317aa2485bc07960
Before:
```
pub  8192R/21F4889F 2012-03-23 Luke Dashjr <luke@dashjr.org>
uid                            Luke Dashjr <luke-jr+git@utopios.org>
uid                            Luke Dashjr <luke-jr@dashjr.org>
sub  8192R/CC42DE42 2012-03-23 [expires: 2016-06-09]
```
After:
```
pub  8192R/21F4889F 2012-03-23 Luke Dashjr <luke@dashjr.org>
uid                            Luke Dashjr <luke-jr+git@utopios.org>
uid                            Luke Dashjr <luke-jr@dashjr.org>
sub  8192R/CC42DE42 2012-03-23 [expires: 2017-06-09]
```

**Comment by fanquake** [comment]
utACK 0d53a9e

**Comment by MarcoFalke** [comment]
As you set an expiration date, wouldn't that encourage people with your key
to fetch an update whenever it timrs out?

If you still think bumping makes sense, I'd prefed to have all keys bumped.
(E.g. I have set my key to expire before every major release)

**Comment by laanwj** [comment]
It's really up to him when he wants to bump his key's expiration date.

**Comment by MarcoFalke** [comment]
Oh, I was referring to bumping (updating) the keys in this repo. If one
person just updates all keys, the review overhead is the smallest.

**Comment by laanwj** [comment]
You can only update the expiration date on your own key.

But I suppose you mean re-retrieving all the keys from the keyserver and pushing them, that could certainly work.

**Comment by MarcoFalke** [comment]
Exactly.

I think writing a script to fetch all gitian-keys shouldn't be too hard.

**Comment by laanwj** [comment]
Agree. Not a blocker for this PR, though.

**Pull request merged**
