### PR TITLE
Use static_assert(…, …) (C++11) instead of assert(…) where appropriate

### PR DESCRIPTION
**Pull request by practicalswift**
Use `static_assert(…, …)` instead of `assert(…)` where appropriate.

### CODE REVIEW

**Comment by practicalswift** [comment]
The build error is unrelated.

**Review by dcousens — APPROVED** [review]

**Comment by laanwj** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/11071/commits/d1e6f91f85ba81394297ba72271226ece7047303

**Comment by promag** [comment]
utACK d1e6f91.

**Comment by paveljanik** [comment]
utACK d1e6f91

**Pull request merged**
