### PR TITLE
[Trivial] fix logging typo in FlushStateToDisk()

### PR DESCRIPTION
**Pull request by jnewbery**
Reverts typo introduced here: https://github.com/bitcoin/bitcoin/pull/5367/files#diff-7ec3c68a81efff79b6ca22ac1f1eabbaR1801

### CODE REVIEW

**Comment by morcos** [comment]
ACK

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/9624/commits/ac9a84679a46250c696301bee2d66e75ddeb1223

**Comment by jtimon** [comment]
ACK ac9a846

**Comment by jonasschnelli** [comment]
ACK ac9a84679a46250c696301bee2d66e75ddeb1223

**Pull request merged**
