### PR TITLE
0.13.2 backports

### PR DESCRIPTION
**Pull request by laanwj**
This backports all the current merged "backport needed" pulls with milestone "0.13.2".

Conflicts:
- #9199 src/main.cpp, function MaybeSetPeerAsAnnouncingHeaderAndIDs: code was formulated differently
   - conflicts with #8085 53347f0cb99e514815e44a56439a4a10012238f8 `net: create generic functor accessors and move vNodes to CConnman`
- #9189 src/main.cpp, function GenerateCoinbaseCommitment: trivial change/remove conflict
   - conflicts with #9125 1662b437b33b7ec5a1723f6ae6187d3bdd06f593 `Make CBlock::vtx a vector of shared_ptr<CTransaction>`
- #9188 src/main.cpp, function ProcessMessage: trivial variable naming
   - conflicts with #8655 4731cab8fbff51a8178c85d572e2482040278616 `Do not shadow variables`

@gmaxwell @sipa can you take a look at the backports of the above pulls and see if the conflicts were resolved in the right way.

### CODE REVIEW

**Comment by laanwj** [comment]
Pulled some further backports that weren't tagged but suggested and backported by @luke-jr.

**Comment by MarcoFalke** [comment]
Maybe  #9251 as well?

**Comment by laanwj** [comment]
> Maybe #9251 as well?

Added.

**Comment by gmaxwell** [comment]
I've reviewed all the backports of my commits here, so ACK on that.

**Comment by laanwj** [comment]
Added #9194. @instagibbs I did the backporting yesterday, so if you changed anything important in the rebase I won't have it picked up here. Please check.

**Comment by instagibbs** [comment]
@laanwj quick check ACK. Only differences I know about are CTransactionRef and dropped no `extern` in front of EncodeHexTX.

**Comment by gmaxwell** [comment]
Tested ACK.

**Comment by rebroad** [comment]
Any reason #9088 is missing?

**Comment by MarcoFalke** [comment]
@rebroad The modal overlay is not in 0.13.2?

**Pull request merged**
