### PR TITLE
fix jonasschnelli's gitian key

### PR DESCRIPTION
**Pull request by jonasschnelli**
There where two keys in the keyfile and it also had a missing "-key" in the filename.
See: http://bitcoinstats.com/irc/bitcoin-dev/logs/2015/02/05#l1423162105

@luke-jr mind verifying if it's now correct?

### CODE REVIEW

**Comment by theuni** [comment]
ACK. I'm not seeing this on any key-servers though.

**Comment by jonasschnelli** [comment]
@theuni now it should be listed on the gpg keyservers:
http://sks.spodhuis.org/pks/lookup?op=index&search=jonas.schnelli

**Comment by luke-jr** [comment]
```
gpg: key 522739F6: public key "Jonas Schnelli <jonas.schnelli@include7.ch>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
```
I can't personally vouch that this is the real @jonasschnelli key, but at least now it's a single key. :)

**Comment by luke-jr** [comment]
Also can confirm this key verifies the gitian sigs under his name.

**Comment by fanquake** [comment]
ACK

**Comment by jonasschnelli** [comment]
Message = "I can prove that my key is related to my github profile."

-----BEGIN PGP MESSAGE-----
Version: GnuPG v1.4.12 (GNU/Linux)

owEBdQKK/ZANAwACASJw4wxSJzn2AaxFYgdtZXNzYWdlVNYBPEkgY2FuIHByb3Zl
IHRoYXQgbXkga2V5IGlzIHJlbGF0ZWQgdG8gbXkgZ2l0aHViIHByb2ZpbGUuiQIc
BAABAgAGBQJU1gE8AAoJECJw4wxSJzn291AP/1tlY/qBZnvJyTurw3bYtAJkuKZX
tzr79DfOBBIJtgZnoDPk43CBQ/AThCyVxZ9gmoKea36QOnfLFBXKZFD//kVzC+vU
0FS6VgWRJxqi/kgWSVIxhRtv+xCvm8EjXnTJvp1fEvm1uUAxaMgUYGja0W6Zos/4
rzikgEcqnAdWpYdvQOKH/05jUc01j34RKJEXjHvtWLuLV8qlZEXdIT5wgeSDsxSg
XZKTb02ajZu4mDbD1LyCxwJpKjA7M4C91PtAB+cYOZ37ouHn73ic8OoLrJr+Kuwn
KhBzFO3nUVCJHnpLo/SpTt97nlCI6JLs5O7j8zC3Y2bY8NOS2bwoDsRZrDRy6zdS
IgCOCMx/1TeiPa5Y7DkjTJPmsy49wD+mFTwL4hEKt0wTNnxUhFIb+owY53Ahwf5Q
g9U16wTE9OQSqE2v6/OYgvZ5jjtN2N5wLkdWF1FAUpxx3TKpO6S2XqlWrXaOumbc
ZrP3ZTv6eBHs92gJppZjCHPlsu78lEY7T3VBR2ejtN9xU8qJfdTl+7u8TXET1HMX
PtessYvg9twza3LnoeFMh/Z9TQkTUGCW87zmlaehi1Sah0ZI5SCeh/qQNX6Ges/p
/8hkM8qyvyr6DRL81ryjqAXLB5++0D5Y2CihCsyDet3pm98sxBQ1schRRljtRXpb
tevdAdgt4vsP2Pg0
=jcuG
-----END PGP MESSAGE-----

**Comment by luke-jr** [comment]
That doesn't actually prove anything (other than what was already proven by you submitting the PR)? I'm not implying you need to do anything more to prove it's yours (although it'd be nice if someone verifies it when they meet you in person).

**Comment by jonasschnelli** [comment]
@luke-jr it just proves again that i'm holding the corresponding priv-key. But right, it was already obvious with the gitian sigs. But not in this repository.
Feel free to fly over to Switzerland and have a coffee with me. :)

**Pull request merged**
