### PR TITLE
[Trivial] Fix typo, wrong information in gettxout help text

### PR DESCRIPTION
**Pull request by paveljanik**
... reported to me by other user.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
utACK 3a9dfe9

**Comment by jmcorgan** [comment]
utACK

**Comment by jonasschnelli** [comment]
ACK

**Comment by Xekyo** [comment]
@paveljanik How about "output index number"? Just "number" is a bit generic.

**Comment by instagibbs** [comment]
If we're changing it I think @Xekyo suggestion is best.

**Comment by paveljanik** [comment]
Sorry, but:

```
$ git grep "The output number" *
rpcrawtransaction.cpp:            "         \"vout\":n        (numeric, required) The output number\n"
rpcrawtransaction.cpp:            "       \"vout\": n,         (numeric) The output number\n"
rpcrawtransaction.cpp:            "         \"vout\":n,                  (numeric, required) The output number\n"
wallet/rpcwallet.cpp:            "         \"vout\": n         (numeric) The output number\n"
$ 
```

**Comment by Xekyo** [comment]
@paveljanik: That may be so, but this number is more specifically the position within the transaction’s outputs. That’s why "index" would be more to the point. :)
If others agree, it could be updated in all the positions that you listed.

**Comment by paveljanik** [comment]
@Xekyo It depends on your view. It can be index into vout array and the number of the vout in vouts. ;-)

I do not plan to change it in this PR.

**Comment by Xekyo** [comment]
I feel that "vout number" is ambiguous: For a minute I thought you were telling me the line referred to "the number of outputs" as in how many there are.

But, since it refers to "an unspent transaction output" here, index would be an improvement because it is the correct technical term, making it easier to grasp and more precise. Anyway, your PR is an improvement to the previous state, so I ACK.

**Pull request merged**
