### PR TITLE
Remove redundant readme info in /doc

### PR DESCRIPTION
**Pull request by merland**
As outlined in #14639, there is some old and redundant info in two READMEs in `/doc`. This PR fixes that. 
Also, changed a download link to point to the download page (instead of the releases page).

### CODE REVIEW

**Comment by merland** [comment]
@MarcoFalke Reason for closing?

**Comment by MarcoFalke** [comment]
The file is required and not redundant (see the build failures of gitian and travis)

**Comment by merland** [comment]
I suspected that,  but I don't get the underlying reason,  why a .txt file
with unintuitive contents is mandatory. It's confusing for the reader.
If impossible to remove, can we keep the file but have only a link in it?

**Comment by MarcoFalke** [comment]
Link to what? See the linked conflicting pull requests for how this is being used.

**Comment by merland** [comment]
Link to the official documentation for running a node, to avoid duplication and confusion.  
However, I guess I'm missing something here. Will read up on gitian builds and the related PRs. Thanks for now.

**Comment by MarcoFalke** [comment]
Oh that makes sense I guess. Include the essential information in the distributed (offline) file and link to an online resource for further information.

**Comment by merland** [comment]
I updated [the branch](https://github.com/merland/bitcoin/tree/issue-14639) according to the discussion above. Hopefully ok for gitian build.  
Would you consider re-opening the PR?  

ping @MarcoFalke

**Comment by MarcoFalke** [comment]
GitHub won't allow to reopen a pull request after the linked branch has been force pushed. Feel free to create a fresh pull request.

**Pull request closed without merging**
