### PR TITLE
Add config option to set max debug log size

### PR DESCRIPTION
**Pull request by tehelsper**
This PR adds a new config option "shrinkdebugfilesize=<n>" which accepts an integer specifying the file size of the debug log in megabytes. This option can be specified alongside "shrinkdebugfile=1" (which is the default) and when shrinking the debug log, it will now shrink it to the size specified.

The default size for debug.log shrinking is still 10 MB.

I was working on a tool to analyze IBD times and my log kept shrinking if I wanted to change settings or needed to reboot for some reason. This was causing lost data and I didn't want to let the log grow forever by setting shrinkdebugfile=0. That way I could leave it on passively and do post-analysis.

### CODE REVIEW

**Comment by laanwj** [comment]
I'm not convinced that this doesn't add unnecessary complexity. In the past we've rejected features that add more fully fledged log management to `bitcoind` because, outside trivial usage, it's better to leave this to some dedicate external system such as `logrotate`.

This adds an extra command line option that adds configuration complexity, and also needs tests.

In your specific case I'd have recommended to disable the log shrinking completely for the duration of the experiment. Then you're 100% sure to not lose data, where heuristically choosing a new number does not.

**Comment by tehelsper** [comment]
I see your point of view and would definitely agree if it was functionality to rotate logs or manage them in some way. I do disagree on this specific change since it only allows a user to configure a value that is hard-coded internally.

Since there is an internally hard-coded limit of 10M, it seems reasonable to allow a user to change it without any additional complexity. I would have found it more understandable if I saw this as a config option. It took some digging to even understand why my log seemed to be shrinking to a seemingly arbitrary number and having an argument in the help text indicating the default and the ability to change it may be helpful.

**Comment by tehelsper** [comment]
I still need to get back and do some cleanup based on the linter and look more into automated testing. Manual testing for my test case has worked well.

**Comment by 1440000bytes** [comment]
> Since there is an internally hard-coded limit of 10M, it seems reasonable to allow a user to change it without any additional complexity. 

Makes sense. Concept ACK.

This pull request is less complex as compared to https://github.com/bitcoin/bitcoin/pull/22350 and others

**Review by luke-jr — COMMENTED** [review]
I would have expected the size to be used as the max debug log size, not the size to shrink to only when it's 10% higher.

Also, commit history is dirty (had a merge from master)

**Comment by laanwj** [comment]
> Since there is an internally hard-coded limit of 10M, it seems reasonable to allow a user to change it without any additional complexity.

Sure, but it's not entirely without maintenance burden. It means the code has to handle different sizes someone might configure. For example, the shrinking itself reads the entire size into memory, to clear the file and write it out again. This strategy works for a small size like 10MB, but if people set it to 1GB or more they may be in for a surprise.

**Comment by tehelsper** [comment]
@laanwj Yeah, I agree a user could shoot themselves in the foot, but is that something that is typically prevented? Adding code to stop users from hurting themselves would add even more maintenance burden. Is there precedent for handing that when setting mempool size, dbcache, etc...?

**Comment by achow101** [comment]
Are you still working on this?

**Comment by tehelsper** [comment]
It sounded a bit contentious. I'll go ahead and close it out.

**Pull request closed without merging**
