### PR TITLE
refactor: Add [[nodiscard]] where ignoring a Result return type is an error

### PR DESCRIPTION
**Pull request by maflcko**
Only add it for those where it is an error to ignore. Also, fix the gcc compile warning https://github.com/bitcoin/bitcoin/pull/25977#issuecomment-1564350880. Also, fix iwyu for touched header files.

### CODE REVIEW

**Comment by TheCharlatan** [comment]
> Only add it for those where it is an error to ignore.

How did you select these?

**Review by sedited — APPROVED** [review]
ACK fa5680b7520c340952239c4e25ebe505d16c7c39

**Review by stickies-v — APPROVED** [review]
ACK fa5680b7520c340952239c4e25ebe505d16c7c39

I looked at all sites where `Result` is either of type `void` or some other descriptive/status type, and could not find any other places where the return value can never be ignored.

**Review by stickies-v — APPROVED** [review]
_(hit send twice - duplicate post)_

**Pull request merged**
