### PR TITLE
Skip stale tip checking if outbound connections are off or if reindexing.

### PR DESCRIPTION
**Pull request by gmaxwell**
I got tired of the pointless stale tip notices in reindex and on nodes with connections disabled.

### CODE REVIEW

**Comment by promag** [comment]
Restarted travis job, looks unrelated.

**Review by maflcko — COMMENTED** [review]
utACK 73b1272521b88f7dde9b8774968943116767cccf (doesn't compile for me, though)

**Comment by gmaxwell** [comment]
@MarcoFalke  how about now? :)

**Comment by practicalswift** [comment]
Concept ACK

Increases signal to noise in our logging

**Comment by MarcoFalke** [comment]
re-utACK 66b3fc543706aad1aaccc403b4ee08f65fa5d17b

**Comment by sdaftuar** [comment]
ACK

**Comment by promag** [comment]
utACK 66b3fc5.

**Comment by ken2812221** [comment]
utACK 66b3fc543706aad1aaccc403b4ee08f65fa5d17b

**Pull request merged**
