### PR TITLE
[WIP][NET] Add NATPMP support.

### LINKED ISSUE #11902: NAT-PMP port forwarding support
After repeated issues with libminiupnpc's security we disabled uPNP by default since release 0.11.1.

However this means that by default there is no port forwarding, resulting in nodes not being reachable for incoming connections by default (unless they use tor), and a reduction in the number of externally reachable nodes compared to total nodes.

NAT-PMP ([RFC 6886](https://tools.ietf.org/html/rfc6886)) is another common automatic port forwarding protocol that would be much less risky than UPnP, because it uses fixed-size UDP packets instead of XML parsing. It would be fairly straightforward to support that without introducing a new dependency.

(NAT-PMP was succeeded by PCP, or [RFC 6887](https://tools.ietf.org/html/rfc6887) which is backwards compatible, probably preferable to support the lowest common denominator)

### PR DESCRIPTION
**Pull request by annanay25**
Adds minimal support for NATPMP (and removes dependency on external UPnP library). Reference implementation in `miniupnp/libnatpmp`.

WIP but aims to fix #11902 .

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
I assume libnatpmp should be subtree'd or we should still use the version linked-against in miniupnpc?

**Comment by sipa** [comment]
This PR just copies 6 files from libnatpmp into the repository. Perhaps this is a sufficiently low amount of code that we want to this (like with tinyformat), but if so, putting them in a subdirectory together may be better.

I haven't checked how much changes were necessary to them, but if it was 0, perhaps we can subtree but still build them directly from our build system (as opposed to building as a library and linking statically).

**Comment by annanay25** [comment]
There are minor changes to the copied files, some including changing the `WIN32` macro, and others according to the coding guidelines like changing `NULL` to `nullptr`, etc.

**Comment by WalterBoles** [comment]
Thanks keep track over the next couple week every thing should fixed and A counted or if not we go find find where it went

**Comment by WalterBoles** [comment]
I think all of you for keeping it with some water

**Comment by laanwj** [comment]
libnatpmp seems to have been virtually unmaintained a while (last commit was Mar 15, 2016), so I think it doesn't matter whether we use 'subtree'. It might be easier to just include the (small) implementation files into our build system and see if we can maintain it ourselves, cutting out parts we don't need.

At least now we don't have to carry the `.java`s.

> putting them in a subdirectory together may be better.

I agree with that - whatever you do, please don't put them in `src/` root.

**Comment by laanwj** [comment]
This is failing the travis build - did you perhaps forget to add `natpmp.h` to the makefile, so that it's not included in make dist?
```
Making check in src
make[1]: Entering directory `/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-w64-mingw32/src'
make[2]: Entering directory `/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-w64-mingw32/src'
  CXX      libbitcoin_server_a-net.o
  CXX      libbitcoin_server_a-noui.o
  CXX      libbitcoin_server_a-pow.o
  CXX      libbitcoin_server_a-rest.o
net.cpp:31:20: fatal error: natpmp.h: No such file or directory
 #include <natpmp.h>
                    ^
compilation terminated.
make[2]: *** [libbitcoin_server_a-net.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-w64-mingw32/src'
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory `/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-w64-mingw32/src'
make: *** [check-recursive] Error 1
```

**Comment by annanay25** [comment]
@laanwj ;

I'm a little confused with the name mangling happening here. The `src/natpmp/*.c` files have `extern "C"` in the function prototypes, which confirms no name mangling (confirmed this with `nm src/natpmp/libbitcoin_server_a-natpmp.o | grep initnatpmp`), but C++ object files are looking for mangled function names?

**Comment by laanwj** [comment]
> but C++ object files are looking for mangled function names?

You need the extern "C" in the header, not in the implementation files.

**Review by luke-jr — CHANGES_REQUESTED** [review]
Libraries should not be copied or subtree'd. There's arguably an excuse for consensus-critical libraries, but NATPMP is not that. Link to the system library if present, and if not, just don't build support for it.

**Comment by annanay25** [comment]
Is this PR still relevant? I'm not sure if I will be able to continue working on it. @practicalswift

**Comment by MishraShivendra** [comment]
Can someone please re-assign #11902 to me? I would like to take this PR forward.

**Pull request closed without merging**
