### PR TITLE
net: refactor: cleanup ThreadSocketHandler

### PR DESCRIPTION
**Pull request by pstratem**
Working towards using poll() on unix like systems.

A number of small changes designed to separate the actual socket handling from the rest of the logic in ThreadSocketHandler.

This is a simpler version of #14147

### CODE REVIEW

**Review by ryanofsky — COMMENTED** [review]
utACK 032488e6e7b4c2d37f3f434d575d25806ddcb0b0. PR description above should contain an actual description of the changes, though, and not just reference #14147. (This PR seems the same as #14147 except it replaces `InactivityChecks` with `InactivityCheck` and moves it below `NotifyNumConnectionsChanged`. I'm actually not sure why #14147 was closed and replaced instead of just updated.)

**Comment by sipa** [comment]
utACK 032488e6e7b4c2d37f3f434d575d25806ddcb0b0. Nice to see logic moved out of those giant blocks of code.

**Comment by MeshCollider** [comment]
utACK https://github.com/bitcoin/bitcoin/commit/032488e6e7b4c2d37f3f434d575d25806ddcb0b0, nice refactor

**Comment by laanwj** [comment]
utACK caa08261d1fa1e699b4e649b644dd4f3520de755

**Comment by MarcoFalke** [comment]
post-merge utACK 032488e6e7b4c2d37f3f434d575d25806ddcb0b0

**Pull request merged**
