### PR TITLE
refactor: refactored platform assignment into get_platform function

### PR DESCRIPTION
**Pull request by iw4p**
Improved code readability and maintainability by moving platform identifiers into a dictionary.

### CODE REVIEW

**Comment by laanwj** [comment]
i understand you're only trying to help, but please don't flood the project with small Python script refactorings. We're severely bottlenecked on review, and tend to have a philosophy to not fix what isn't broken.

**Comment by laanwj** [comment]
Sure, but for example: if you're going to do things like optimization, consider if speed is important in the process at that point (in many cases it's not, that's why the tool is in Python and not C++). If it is important, we'll also need to see benchmarks that the speed is noticibly faster.

If you've been involved for a while and know where the pain points are, this is easier to know. For new contributors I wouldn't really recommend doing refactors at all.

If you're looking for something to work on (which is great!), please check the https://github.com/bitcoin/bitcoin/labels/good%20first%20issue label.

**Comment by iw4p** [comment]
I appreciate your response and explanation. I'll take a quick look into it!

**Comment by fanquake** [comment]
Thanks for the contribution, however we are going to leave this code as-is for now.

**Pull request closed without merging**
