### PR TITLE
contrib: Update laanwj key

### PR DESCRIPTION
**Pull request by laanwj**
I recently added a signing subkey (0x1E4AED62986CD25D), which is used to sign gitian asserts as well as commits.

Old:
```
pub  rsa2048/0x74810B012346C9A6 2011-08-24
uid                             Wladimir J. van der Laan <laanwj@gmail.com>
sub  rsa2048/0xF69705ED890DE427 2011-08-24
```

New:
```
pub  rsa2048/0x74810B012346C9A6 2011-08-24 [expires: 2019-02-14]
uid                             Wladimir J. van der Laan <laanwj@visucore.com>
uid                             Wladimir J. van der Laan <laanwj@gmail.com>
sub  rsa2048/0xF69705ED890DE427 2011-08-24
sub  rsa2048/0x1E4AED62986CD25D 2017-05-17 [expires: 2019-05-17]
sub  rsa2048/0x69B4C4CDC628F8F9 2017-05-17 [expires: 2019-05-17]
```

Not sure this warrants an update in the repository, but as it is more than just updating expiration dates, it might (its still within the reach of `--refresh-keys` though).

### CODE REVIEW

**Comment by jonasschnelli** [comment]
tested ACK
```
# off=16266 ctb=b9 tag=14 hlen=3 plen=269
:public sub key packet:
	version 4, algo 1, created 1495035661, expires 0
	pkey[0]: [2048 bits]
	pkey[1]: [17 bits]
	keyid: 1E4AED62986CD25D
```

Commit is signed with `1E4AED62986CD25D`.
Ideally, you sign this PR's description with your current known key, but since it's a subkey, that doesn't really matter.

Curios why you did chose `2048` bits and not `4098`?
Encrypt II as well as BSI recommendation (as of >2022) are in the 3000+ range...

**Comment by laanwj** [comment]
> Curios why you did chose 2048 bits and not 4098?
> Encrypt II as well as BSI recommendation (as of >2022) are in the 3000+ range...

Wouldn't that just be security theater though, as the master key is 2048 bits?
Could create another subkey but I don't think it will make things any less confusing.

**Comment by jonasschnelli** [comment]
> Wouldn't that just be security theater though, as the master key is 2048 bits?

Oh yes. Your right... haven't looked at the master keys used bits.

**Comment by fanquake** [comment]
ACK 3c85332

**Comment by MarcoFalke** [comment]
utACK 3c85332f2928489964c4a5cff66f7119892e7a17. It is the key I already have: 

```
gpg --import < contrib/gitian-keys/laanwj-key.pgp
gpg: key 2346C9A6: "Wladimir J. van der Laan <laanwj@visucore.com>" not changed
```

Going to merge this, but we should really just add a script to update all keys in that folder.

**Pull request merged**
