### PR TITLE
Fix build on FreeBSD

### PR DESCRIPTION
**Pull request by s3erios**

### CODE REVIEW

**Comment by jgarzik** [comment]
ut ACK

**Comment by paveljanik** [comment]
utACK

**Comment by theuni** [comment]
ut ACK

**Comment by luke-jr** [comment]
Propose for inclusion in 0.11?

**Comment by s3erios** [comment]
Possibly, yes (should I open another pull request?)

**Comment by laanwj** [comment]
Cherry-picked to 0.11 as 8ea6d37aeed67d42428e38dcf3ee0771c8fff1d1

**Pull request merged**
