### PR TITLE
test: fix timeout decrease in feature_assumevalid

### PR DESCRIPTION
**Pull request by brunoerg**
This PR fixes the timeout decrease in assert_blockchain_height function.

### CODE REVIEW

**Comment by practicalswift** [comment]
Oh, nice find! Can't believe that slipped in during code review :)

Warm welcome as a contributor @brunoerg! Hope to see more contributions from you in the future! :)

**Review by theStack — APPROVED** [review]
ACK 0d39b5848a7a341cd2b958336861cdd4098e2616 ⏲️ 
Thanks for fixing and welcome as a new contributor! 🎉

**Comment by practicalswift** [comment]
cr ACK 0d39b5848a7a341cd2b958336861cdd4098e2616: patch looks correct

**Comment by curtcurt871** [comment]
#21084

**Pull request merged**
