### PR TITLE
scripted-diff: Remove trailing whitespaces

### PR DESCRIPTION
**Pull request by promag**
The script test/lint/lint-whitespace.sh should prevent new cases.

This happens in some pulls where the code editor and the author 'git add's them, so this would fix it all.

### CODE REVIEW

**Comment by Sjors** [comment]
Ironically rejected by a linter :-)

**Comment by MarcoFalke** [comment]
ACK, any difference between `[[:space:]][[:space:]]*` and `[[:space:]]+`?

**Comment by promag** [comment]
@MarcoFalke in order to use `+` extended regular expressions must be used. Updated to use them.

**Comment by MarcoFalke** [comment]
Note that the flag for gnu sed is `--regexp-extended`, not `-E`

**Comment by MarcoFalke** [comment]
You'd have to remove the trailing `''` after the `-i` option, no?

**Comment by promag** [comment]
@MarcoFalke done :feelsgood:

**Comment by mess110** [comment]
utACK 12dd101

**Comment by MarcoFalke** [comment]
utACK 12dd1013454a3b4913e8e6bbac251887e7e82ff0

**Comment by fanquake** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/13753/commits/12dd1013454a3b4913e8e6bbac251887e7e82ff0

Have not checked the scripted diff or if this is has removed all the trailing whitespace, but if according to @DrahtBot this doesn't disrupt much else, LJGTM.

**Comment by Empact** [comment]
So glad this is done. Thanks @promag!

**Pull request merged**
