### PR TITLE
test: Run rpc_txoutproof.py even with wallet disabled

### PR DESCRIPTION
**Pull request by maflcko**
Run the consensus test even when the wallet was not compiled. Also:

* Minor bugfix in MiniWallet
* Two new test cases (one cherry-picked from #19847)

### CODE REVIEW

**Comment by jnewbery** [comment]
Concept ACK. Moving all the remaining non-wallet tests to use MiniWallet could be a good first issue for newer contributors.

**Comment by MarcoFalke** [comment]
Force pushed to make travis python linter happy

**Comment by jnewbery** [comment]
utACK faf251d854e3a670533ea3e9087e82c92f3ae533. Thanks Marco!

**Review by kristapsk — APPROVED** [review]
ACK faf251d854e3a670533ea3e9087e82c92f3ae533

**Comment by stackman27** [comment]
@MarcoFalke I realize that this is a merged PR, but I just had some hanging issues/comments regarding implementing `create_lots_of_big_transactions` while restructuring`mempool_limit.py`. My biggest concern is that wouldn't we need to change `send_self_transfer` to accommodate extra appends in the transaction outputs to make it large? or is there something i'm missing out? Any help is really appreciated

**Comment by MarcoFalke** [comment]
`send_self_transfer` only handles a single-in-single-out tx. If multi-in-multi-out txs are needed, it could make sense to add a new method for that.

**Comment by stackman27** [comment]
> `send_self_transfer` only handles a single-in-single-out tx. If multi-in-multi-out txs are needed, it could make sense to add a new method for that.

Alright, I will open a PR soon with respected changes. Thank you :)

**Pull request merged**
