### PR TITLE
rfc: Add -printconfig arg to bitcoind

### PR DESCRIPTION
**Pull request by promag**
This PR adds the `-printconfig` argument to `bitcoind`. Like `-help` and `-version`, after printing to the console it exits.

Examples:
```
bitcoind -printconfig
 datadir:   /Users/joao/Library/Application Support/Bitcoin
 blocksdir: /Users/joao/Library/Application Support/Bitcoin/blocks

# network is handled
bitcoind -printconfig -regtest
 datadir:   /Users/joao/Library/Application Support/Bitcoin
 blocksdir: /Users/joao/Library/Application Support/Bitcoin/regtest/blocks

# support overriding datadir
bitcoind -datadir=/tmp -testnet -printconfig
 datadir:   /tmp
 blocksdir: /tmp/testnet3/blocks
```

### CODE REVIEW

**Comment by promag** [comment]
Suggested in https://github.com/bitcoin/bitcoin/issues/15438#issuecomment-467625869.

If you concept ACK feel free to suggest other more configs to print.

**Comment by darosior** [comment]
I think we could print :
- the path to the pid file
- whether or not txindex is activated
- if we listen through tor
- what we debug (which category, ips, timestamps)

Why print the block dir since you already print datadir ?

**Comment by promag** [comment]
> Why print the block dir since you already print datadir ?

Because depends on the network.

**Comment by Sjors** [comment]
Concept ACK, but to prevent endless bike shedding, it should just print everything except passwords.

**Comment by promag** [comment]
You mean iterate ArgsManager?

**Comment by Sjors** [comment]
Yes, that might be useful to see which options override others. So ideally do this after the parameter interaction stuff. In that case it won't complete if there's a problem, but those problems generally have their own error message which should contain enough information.

**Comment by instagibbs** [comment]
concept ACK, it might be completely redundant, but printing explicitly which file is being used as conf would be useful.

**Comment by laanwj** [comment]
> Yes, that might be useful to see which options override others. So ideally do this after the parameter interaction stuff. In that case it won't complete if there's a problem, but those problems generally have their own error message which should contain enough information.

I tend to agree. If you're going to do this, print everything that can be printed, I guess apart from really sensitive options (purely to prevent shoulder surfing, as any user being able to run this will have by definition access to `bitcoin.conf`).

**Comment by hebasto** [comment]
Concept ACK.

**Comment by promag** [comment]
In order to print everything I have to move the default from `GetArg(..., default_value)` to `AddArg(...)`. Is this acceptable?

**Comment by practicalswift** [comment]
Concept ACK

**Comment by luke-jr** [comment]
@promag IMO we should probably do that anyway.

Perhaps also print it in a format that could be put directly in a bitcoin.conf if so desired?

**Comment by kristapsk** [comment]
Concept ACK

**Comment by promag** [comment]
I'll pick this again once flags are settled.

**Pull request closed without merging**
