### PR TITLE
travis: Skip cache for lint stage

### PR DESCRIPTION
**Pull request by maflcko**
* Disable cache for lint stage according to https://docs.travis-ci.com/user/caching/#Explicitly-disabling-caching
* Skip fetching of keys for non-cron branch pushes.

### CODE REVIEW

**Review by ken2812221 — APPROVED** [review]
utACK fa2d83eb44fdb02177d6c01fd0621d364c5a1dfc

**Comment by sipa** [comment]
What is the difference between `script` and `before_script`, and why is it changed? (just trying to understand the semantics).

**Comment by ken2812221** [comment]
@sipa IIRC once `before_script` fail at any point, the build terminate immediately, but `script` would continue running. Also at travis site `script` would not collapse.

**Comment by sipa** [comment]
@ken2812221 Cool, makes sense.

utACK fa2d83eb44fdb02177d6c01fd0621d364c5a1dfc

**Pull request merged**
