### PR TITLE
Consensus: Introduce static GetScriptFlags (mostly MOVEONLY)

### PR DESCRIPTION
**Pull request by jtimon**
This have been proposed many times with different variations, including #9271 and ancestors, and proposals by @TheBlueMatt ( #10192 ) and @CodeShark (#6747) for example.
I think this is something very easy to review and agree with. Regardless of later steps, let's please take the first step already.

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
I'm not sold on passing in the VersionBitsCache (which is the primary difference between this and the version at #10192) - why should ConnectBlock even be aware that there is a fancy cache making GetScriptFlags faster?

**Comment by jtimon** [comment]
> why should ConnectBlock even be aware that there is a fancy cache making GetScriptFlags faster?

Well, GetScriptFlags is aware of it anyway, so at a minimum, I think not calling IsWitnessEnabled from it is very reasonable.

Regarding the question, ConnectBlock should is aware of the global versionbitscache because it uses it though GetScriptFlags, whether we chose to make that dependency explicit or not.
But I guess this comes down to me liking globals being used explicitly instead of hidden when possible (and lower level functions that don't need to use the globals and can use local parameters instead do that instead of using globals they don't need to depend on).
But from past discussions I think you don't believe there's anything wrong with using globals when you don't need them or anything good with functions declaring all their dependencies explicitly as parameters, so I guess I can't convince you on that.

**Comment by TheBlueMatt** [comment]
Guess its all a personal preference thing - make functions more static and pass globals in from higher up the stack, or put a bit more encapsulation in the lower-level functions and keep the globals only for those functions. I tend to prefer the second, myself, but open to other views.

**Comment by jtimon** [comment]
Thoughts on at least removing the use of IsWitnessEnabled() from your version of the change?
That's just removing an unnecessary wrapper.

**Comment by TheBlueMatt** [comment]
I dont have any strong feelings, but IsWitnessEnabled is a much clearer expression of whats going on, and also keeps duplication of that check to one place, which is nice (especially given all the folks running around doing crazy 148/149/etc implementations).

**Comment by jtimon** [comment]
Whatever, I guess I can do this changes later if I ever get to the point where I can actually use them. Closing.

**Pull request closed without merging**
