### PR TITLE
Consensus: Policy: Move CFeeRate out of consensus module and create CPolicy interface

### PR DESCRIPTION
**Pull request by jtimon**
This moves the CFeeRate and dust code out of libconsensus and the consensus module.
Before that, it prepares an empty CPolicy interface and implementation where the dust methods are moved to. It also encapsulates the global minRelayTxFee behind the CPolicy interface.
Since this may be too disruptive for one PR, I was very careful to separate things in smaller commits.
The first commit, for example, may be useful for @jonasschnelli 's work encapsulating the wallet.

This is also intended to replace @morcos' #7557, #6068 and #5114.

### CODE REVIEW

**Comment by dcousens** [comment]
concept ACK

**Comment by jtimon** [comment]
Rebased(1).
Also, fixed the error that was making ```python ./qa/pull-tester/rpc-tests.py mempool_limit``` fail.

**Comment by jtimon** [comment]
Rebased and fixed one error, but it is still failing.
Still not sure what to do with AmountErrMsg and ParseAmountFromArgs. For the latter to use the former, both need to be put together in either util.o or ui_interface.o.
I pushed an alternative simpler option without creating the policy interface nor removing the global minRelayTxFee in https://github.com/bitcoin/bitcoin/compare/master...jtimon:0.13-consensus-dust-out-minimal.

**Comment by NicolasDorier** [comment]
Concept ACK will review, can you check the failing travis ?

**Comment by jtimon** [comment]
I'm sorry, after sewgit's rebase this did never passed travis (but this time I removed the known past mistakes, so it's weird). That;s why I suggested https://github.com/bitcoin/bitcoin/compare/master...jtimon:0.13-consensus-dust-out-minimal which seems to work (locally).
At the same I promised @btcdrak I wouldn't open parallel mutually exclusive PRs to see which one fails on travis or for people to compare and choose...

The travis error seemed related to CAmount becoming undefined for windows, but on the last push it also failed in another build.
I will keep investigating, but travis is what I meant by "it is still failing".

**Comment by jtimon** [comment]
rebased https://github.com/bitcoin/bitcoin/compare/master...jtimon:0.13-consensus-dust-out-minimal ping @btcdrak

**Comment by jtimon** [comment]
Apart from being failing tests and needing rebase, this is going to conflict with #9243. Replaced with the simpler branch I was suggesting that only moves CFeeRate without creating any policy class or interface:  #9279

**Pull request closed without merging**
