### PR TITLE
[0.12] Backports

### PR DESCRIPTION
**Pull request by maflcko**

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Only critical bugs should be back ported IMO. We are already in rc2 stage.

**Comment by laanwj** [comment]
Agree with @jonasschnelli. On the other hand the risk of this introducing a regression is low.

This is something that could be merged if we need to do a rc3 in the first place and won't label rc2 as final.
Otherwise it could be merged after final for 0.12.1.

**Comment by MarcoFalke** [comment]
Sure, this was my intend. Just wait to see what other backports are required (if any).

**Comment by laanwj** [comment]
Agree with these

**Comment by laanwj** [comment]
Cherry-picked https://github.com/MarcoFalke/bitcoin/commit/a83a371f443b850b3450190ec8b4056b05f830eb (#7384) as 294f4320a246e453a0509c82b4112b2a5203dd81
https://github.com/MarcoFalke/bitcoin/commit/6a048953b7808c0fc7653cb50ee5a9d861c24519
 (#7391) is already part of 0.12 through #7440

**Pull request closed without merging**
