### PR TITLE
Fix segfault crash when shutdown the GUI in disablewallet mode

### LINKED ISSUE #9816: Running with --disablewallet gives a segfault
Run `src/qt/bitcoin-qt --disablewallet=1`. 
Quitting after any amount of time will result in `Segmentation fault: 11`

0.14.0 branch at 861cb0c83db0571c2863f6b6276314e115c266ee , osx 10.12.3, Qt5.8

### PR DESCRIPTION
**Pull request by jonasschnelli**
Should fix #9816.
Was introduced in https://github.com/bitcoin/bitcoin/pull/9190.

### CODE REVIEW

**Comment by ryanofsky** [comment]
Obvious utACK 312c4f10574ccf6dfe0d4ecb3ce928733d3a1e52.

Were you planning to add a test? I haven't looked into qt unit testing, but it is nice when simple bugfixes like this are accompanied by tests to increase meaningful test coverage. (It's easy to imagine similar bugs with --disablewallet being introduced in the future.)

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/commit/312c4f10574ccf6dfe0d4ecb3ce928733d3a1e52

Is #9746 the same?

**Comment by laanwj** [comment]
> Were you planning to add a test? I haven't looked into qt unit testing, but it is nice when simple bugfixes like this are accompanied by tests to increase meaningful test coverage. (It's easy to imagine similar bugs with --disablewallet being introduced in the future.)

There are unit tests for Qt, but currently nothing that can test window setup/teardown or UI interaction.

**Comment by laanwj** [comment]
Backported to 0.14 as 7d75a5a, 0.13 as c6811c1

**Comment by MarcoFalke** [comment]
> @ryanofsky Were you planning to add a test? I haven't looked into qt unit testing, but it is nice when simple bugfixes like this are accompanied by tests to increase meaningful test coverage. (It's easy to imagine similar bugs with --disablewallet being introduced in the future.)

You can run `BITCOIND=bitcoin-qt ./qa/pull-tester/rpc-tests.py` for basic sanity checking of the gui.

**Pull request merged**
