### PR TITLE
test: check that bumpfee RPC fails for txs with descendants in mempool

### PR DESCRIPTION
**Pull request by theStack**
This PR adds missing test coverage for the bumpfee RPC error _"Transaction has descendants in the mempool"_, 

https://github.com/bitcoin/bitcoin/blob/6419bdfeb130b20ccfed229d9ba7eca7f385d036/src/wallet/feebumper.cpp#L29-L32

which is thrown if the bumped tx has descendants in the mempool and is _not_ connected to the bitcoin wallet (for those, the error "Transaction has descendants in the Wallet" is thrown a few lines above). To achieve that, the test framework's MiniWallet is used.

### CODE REVIEW

**Review by brunoerg — APPROVED** [review]
tACK 4ac8c89ad96de9ad61cad756b10c9dee2d9e1405

**Review by promag — COMMENTED** [review]
Code review ACK 4ac8c89ad96de9ad61cad756b10c9dee2d9e1405. Nice stuff!

It looks like these are still untested:
 - `"Transaction has been mined, or is conflicted with a mined transaction"`
 - `"Cannot bump transaction %s which was already bumped by transaction %s"`.

**Review by lsilva01 — APPROVED** [review]
Tested ACK 4ac8c89 cad756b10c9dee2d9e1405 on Ubuntu 20.04.

**Review by stratospher — COMMENTED** [review]
tested ACK 4ac8c89.

**Pull request merged**
