### PR TITLE
validation: Skip VerifyDB checks of level >=3 if dbcache is too small

### LINKED ISSUE #25563: verifychain 4 111000 aborts with assertion "hashPrevBlock == view.GetBestBlock()" failed
Providing a low number of blocks works, however, it just crashed for me with 111000 blocks.

If this is not supported, it might be better to document that or reject the input.

Commit 691a08718beff31d1b821b192609ea3bfdb24d41

Output:

```
bitcoin-qt: validation.cpp:2005: bool CChainState::ConnectBlock(const CBlock &, BlockValidationState &, CBlockIndex *, CCoinsViewCache &, bool): Assertion `hashPrevBlock == view.GetBestBlock()' failed.

### PR DESCRIPTION
**Pull request by mzumsande**
This is the first two commits from #25574, leaving out all changes to `-verifychain` error-handling :

- The Problem of [25563](https://github.com/bitcoin/bitcoin/issues/25563) is that when we skip blocks at level 3 due to an insufficient dbcache (skipping some `DisconnectBlock()` calls), we would still attempt the level 4 checks, attempting to reconnect a block that was never disconnected, leading to an assert in `ConnectBlock()`.
Fix this by not attempting level 4 checks in this case.
- Logging of verification progress is now split over multiple lines. This is more verbose, but now each update has its own timestamp, and other threads logging concurrently will no longer lead to mangled output. 

This can be tested with a small `dbcache` value, for example:
`bitcoind -signet -dbcache=10`
`bitcoin-cli -signet verifychain 4 1000`

Fixes #25563

### CODE REVIEW

**Comment by MarcoFalke** [comment]
This removes a crashing check and turns it into a logprint to explain why it was skipped.

Given that no one reported an issue about this in the past, it seems unlikely to affect anyone. However, in the future the log can be displayed more verbosely, for example as an `InitWarning` in init or as a json-dict-key `{"warnings":[...]}` in the rpc.

review ACK fe683f352480245add0b27fe7efef5fef4c1e8c3 🗄

<details><summary>Show signature</summary>

Signature:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

review ACK fe683f352480245add0b27fe7efef5fef4c1e8c3 🗄
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEE+rVPoUahrI9sLGYTzit1aX5ppUgFAlwqrYAACgkQzit1aX5p
pUgyFQwAhO+FMR6aO4RkWEgkOTsUA11ZyFae6aiDhoo2/4sQ4zW/+ssqZxGZxTkH
UwOc1MPXm1rPGvMhfNsHke9WWi6mfmp9G4MeXdyph9PiOFzoCYUWEaz8eTbba2ay
x+SuLJAlP0JTu6/kVCSp8GmoMTNoR+dt6kuRWO4DSloIK6yBRi+uUjdYFZAIvbsE
JMv9+Te6Yty2HeMNxbn7CBbigLfv+bppbeQKdrKy25EoDHMBVDbANkbipvUbShyw
Rc6pz9N1Uo9afdVazMLwzBvzy7OtADGvrAxP4cgyF6p5GKzDbXSvaxH88p2x4NSF
+3WBM8bHxTqU0YWWeuaKIz2XAc9lU3Ho72pQ1Hod7uDlSNiQck6rSlQALs8Szp/g
BLRBr2I6Qa06sbpyB3/rGdPt+nqcPF4X9CzJCOmuoi4+H44P4+5jDtXx4AY79Inp
jpZixdEFeru/sL/i8tSzoIDPG0A4uUHB1Z87FYJD9mH9gXrPwCiWPBc3lzfw6rLi
Go9R0uBP
=H0N/
-----END PGP SIGNATURE-----
```


</details>

**Review by maflcko — APPROVED** [review]

**Review by john-moffett — APPROVED** [review]
ACK fe683f352480245add0b27fe7efef5fef4c1e8c3 

I'm definitely uncomfortable with:

``` bash
src/bitcoin-cli -signet verifychain 4 10000
true
```

when it didn't fully verify at the requested level. However, I think it's preferable to a `SIGABRT`, especially given that we're already potentially silently failing with level 3, so I won't stand in the way of an improvement. If this needs to be a two-PR process, I'm in favor of that over no action.

To be clear, I prefer #25574 in its current form, despite the RPC behavior change.

**Comment by MarcoFalke** [comment]
> when it didn't fully verify at the requested level. However, I think it's preferable to a SIGABRT, especially given that we're already potentially silently failing with level 3, so I won't stand in the way of an improvement. If this needs to be a two-PR process, I'm in favor of that over no action.

How is logging a warning for the not-enough-memory case different from logging a warning for the not-enough-storage case (pruning)? I think the warning can be displayed more prominently in a follow-up, but I think doing the same for similar cases seems fine.

> To be clear, I prefer https://github.com/bitcoin/bitcoin/pull/25574 in its current form, despite the RPC behavior change.

That pull changes the not-enough-memory case to an error and leaves the not-enough-storage case (pruning) a silent pass with log warning. I have no objection to  merging 25574, but I think it may not be the ideal solution either.

**Comment by john-moffett** [comment]
> How is logging a warning for the not-enough-memory case different from logging a warning for the not-enough-storage case (pruning)?

I agree that they're not different, but my main concern isn't about the warning log. It's about the output from the RPC.

> That pull changes the not-enough-memory case to an error and leaves the not-enough-storage case (pruning) a silent pass with log warning.

True, it's not ideal, because I think that the latter case should also change the RPC behavior to return `false` (by adding another new `VerifyDBResult` value).

**Comment by mzumsande** [comment]
Let's continue this discussion in #25574.

**Pull request merged**
