### PR TITLE
wallet: Catch filesystem_error and raise InitError

### LINKED ISSUE #13754: Windows crashes for -wallet=你好
Invalid characters for a wallet name, e.g. `bitcoin-qt -wallet=你好` used to result in an error like this

schermafbeelding 2018-07-24 om 17 46 37

But now it just crashes:

schermafbeelding 2018-07-24 om 17 43 26

I didn't do a `git bisect`, but it broke somewhere this year :-)

### PR DESCRIPTION
**Pull request by maflcko**
Fixes #13754 by restoring the previous behaviour

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Before:
schermafbeelding 2018-07-24 om 17 43 26

After:

screenshot from 2018-08-04 12-48-17


Using:

`6f7a41d357d5e3fb4614fec0280477f3e71bbda1bb28f32461b1cc2c418c0c4d  bitcoin-0.16.99-win64.zip`
https://transfer.sh/MPEy5/bitcoin-0.16.99-win64.zip

**Comment by laanwj** [comment]
certainly better
utACK fa8527ffeced3f898e8f205483ef0ea7c51a9178

**Comment by laanwj** [comment]
Adding to 0.17.0 milestone as I think this is a regression?

**Comment by MarcoFalke** [comment]
Regression in a sense that it throws a useless error as opposed to something more helpful.

**Comment by MarcoFalke** [comment]
Ideally we'd handle runtime errors more sanely and automatic as opposed to splattered catch clauses all over the place. Imo we should provide a copy-paste able stacktrace on runtime errors and a link to submit an issue with all the debugging information attached.

E.g. https://github.com/bitcoin/bitcoin/issues/new?title=VERSION%20MODULE%20runtime%20error&body=stacktrace%20and%20operating_sytem%20information

**Comment by MarcoFalke** [comment]
@Sjors Mind to take a quick look at the patch, please?

**Comment by Sjors** [comment]
For some reason this build throws an unexpected error for me, even when launching without `-wallet` param (master does start):

schermafbeelding 2018-08-08 om 16 52 06

**Comment by MarcoFalke** [comment]
@Sjors Interesting. I didn't change that part of the code at all. This comes very early in initialization:

https://github.com/bitcoin/bitcoin/blob/df9f71274645a917e2578c52a1c59745bce8112d/src/init.cpp#L1183

Are you sure you compare the "Gitian builds for commit 2b67354 (master)" with "Gitian builds for commit 04cb409 (master and this pull)"?

**Comment by MarcoFalke** [comment]
I just tried again and they work for me with a fresh account:

screenshot from 2018-08-08 16-09-56

**Comment by Sjors** [comment]
@MarcoFalke I downloaded it straight from @DrahtBot and the link you posted. It's weird, but given that my error is created elsewhere in the code, and others don't see it, maybe just ignore?

**Comment by ken2812221** [comment]
Tested ACK fa8527ffeced3f898e8f205483ef0ea7c51a9178

Although the message is a mess if the system setting is not English.

image

**Pull request merged**
