### PR TITLE
Various PEP8 Fixes

### PR DESCRIPTION
**Pull request by super3**
https://www.python.org/dev/peps/pep-0008/

### CODE REVIEW

**Comment by super3** [comment]
About 600+ PEP8 style violations in /contrib alone. Just fixed the comma spacing errors first.

**Comment by laanwj** [comment]
NACK. Don't do this - these kinds of floods of minor whitespace changes break other pulls for no good reason.

**Comment by super3** [comment]
@laanwj All of PEP8 violations I'm covering are in `/contrib`. With the exception of `/contrib/debian` these directories have not been touched for 4+ months. I agree that minor floods of whitespace on active code would cause problems, but that directory is far from active.

**Comment by super3** [comment]
Guess the other question is should Bitcoin code even be PEP8 compliant.

**Comment by jonasschnelli** [comment]
I also tend to NACK this.
Generally IMO clean code makes sense. But, at the moment there are many pull requests and it's hard to keep focus on what is going on.
IMO your PR does not produce a benefit for this project at first place.
Somebody needs to review this. This requires time which is probably better spent at some other PRs.

I think this PR could be something for the trivial branch https://github.com/theuni/bitcoin.
This goes also in the same direction as the clang-everything PR (https://github.com/bitcoin/bitcoin/issues/5377, https://github.com/bitcoin/bitcoin/pull/5387)

**Comment by laanwj** [comment]
Some PEP8 "violations" are worse than others. E.g. using the wrong kind of indentation would be awful.

But adding spaces to almost every line so that ',' is lined up. No, that's not important.
Please don't waste your time on this.

**Pull request closed without merging**
