### PR TITLE
refactor: Remove unused function

### PR DESCRIPTION
**Pull request by maflcko**
Oversight of kallewoof and mine in https://github.com/bitcoin/bitcoin/pull/13541#discussion_r266555476

### CODE REVIEW

**Comment by laanwj** [comment]
This should never have been merged in the first place, I'm happy this concerns an unused function but we should mark consensus-critical files at some point to prevent wallet and RPC PRs from affecting consensus-critical code accidentally.

utACK fa5c511a832632b964617776eb6c3535bb2bd893

**Comment by promag** [comment]
utACK fa5c511.

**Comment by jnewbery** [comment]
utACK fa5c511a832632b964617776eb6c3535bb2bd893

**Comment by kallewoof** [comment]
Post-merge utACK. Terribly sorry about that. I must've screwed up something between branches.

**Pull request merged**
