### PR TITLE
RPC: Consistently use UniValue.pushKV instead of push_back(Pair())

### PR DESCRIPTION
**Pull request by karelbilek**
As I was poking in the code, I didn't like that at some places, pushKV is being used, and at other places, push_back(Pair()) is being used. So I changed the style to pushKV. (It's done automatically by sed, see the git comment on the first commit)

I also realized that the Pair Univalue code is not used anymore with this change anymore, and since there is this comment in the source code for about 2 years

> // Most duplicate other methods, and should be removed

I went ahead and removed it

It's all mostly bikeshed

### CODE REVIEW

**Comment by sipa** [comment]
We have in fact a simple framework for verifiable scripted changes, see for example #10483. Perhaps you can use that for the first commit.

**Comment by jonasschnelli** [comment]
UniValue is added as a git subtree. Please propose changes that affect the UniValue sources upstream (https://github.com/bitcoin-core/univalue).

**Comment by achow101** [comment]
@jonasschnelli This is changing how UniValue is used, not changing UniValue itself.

**Comment by jonasschnelli** [comment]
@achow101: what about that https://github.com/bitcoin/bitcoin/pull/11386/files#diff-49e8bd958c3337da3e89c4a731dc37fd?

**Comment by achow101** [comment]
Oh, missed that.

**Review by dcousens — APPROVED** [review]

**Comment by promag** [comment]
@achow101 will you remove univalue changes and submit a patch there?

**Comment by runn1ng** [comment]
Sorry, busy weekend, I am doing it now

**Comment by jgarzik** [comment]
FWIW, https://github.com/jgarzik/univalue/pull/42

**Comment by runn1ng** [comment]
Here is the PR https://github.com/bitcoin-core/univalue/pull/5

I now need to find out how git subtrees work, I can't figure it out :)

**Comment by runn1ng** [comment]
Btw, this commit - https://github.com/bitcoin/bitcoin/commit/64fb0ac016c7fd01c60c39af60f6431bac57f9ee - seem to change some files in src/univalue, but not in the separate repo

**Comment by promag** [comment]
For now 1st commit is enough. Meanwhile other merged PR's can use `.push_back(Pair(...))` so keep an eye on that.

Concept ACK.

**Comment by runn1ng** [comment]
First commit is not enough.

Without the UniValue KV bool fix, saving bool values through pushKV falls
back to some numeric type (not sure which one now) and is saved wrong in
the json. Some RPCs are using bool values and tests (correctly) fail.

I am waiting for the UniValue PR to be merged, and then I will change this
PR to just be a pull from the UniValue subtree + scripted commit.

**Comment by promag** [comment]
I know and IMO a failing build is better. Anyway, concept ACK.

**Comment by jnewbery** [comment]
I think the subtree update and scripted-diff would need to be atomic to avoid breaking git bisect. Is that correct?

Maybe check with @laanwj or @MarcoFalke if that's possible?

**Comment by promag** [comment]
If #10583 is merged then there are a couple of `push_back` to replace after rebase.

**Comment by MarcoFalke** [comment]
@jnewbery Since the scripted diff can not contain any other changes (like changes to a subtree) I don't think this is possible. However, it is possible to do in one commit when the scripted diff keyword does not appear.

**Comment by runn1ng** [comment]
I don't think I can do it both atomically for bisect *and* as git subtree merge.

I think I can make it atomically if I manually add the changes to the subtree files inside the script, but that will be a bit ugly too.

**Comment by sipa** [comment]
If it's impossible to do at once due to the subtree update being a separate commit, I think it's fine to do it as a separate commit in the same PR.

**Comment by jnewbery** [comment]
To keep git bisect working, we'd need to do two commits in univalue:

1. Pushing boolean value to univalue correctly
2. Remove deprecated std::pair wrappers

and do three commits in this repo:

1. subtree update, pulling commit (1) from univalue
2. do the scripted-diff to change from `push_back(Pair())` to `pushKV()`
3. subtree update, pulling commit (2) from univalue

is *that* possible?

**Comment by runn1ng** [comment]
@jnewbery yeah, that could be possible. Actually, the PR in univalue is already written like that.

**Comment by MarcoFalke** [comment]
It can be done atomically in two commits. See #11420

**Comment by laanwj** [comment]
FWIW #11420 was merged, anything left to do here?

**Comment by jnewbery** [comment]
https://github.com/bitcoin-core/univalue/pull/5 needs to be merged in bitcoin-core/univalue before this can go in.

**Comment by jnewbery** [comment]
This now requires https://github.com/bitcoin-core/univalue/pull/10 and https://github.com/bitcoin-core/univalue/pull/11 to be merged, and then separate subtree bumps for those PRs, with the "Consistently use UniValue.pushKV instead of UniValue.push_back(Pair())" commit between those two subtree bumps.

@karel-3d has said that he doesn't have time to maintain these PRs, so I'll open a PR that handles this once the univalue PRs are merged.

**Comment by jnewbery** [comment]
https://github.com/bitcoin-core/univalue/pull/10 is merged. Waiting for https://github.com/bitcoin-core/univalue/pull/11 before I open a new PR for this.

**Comment by MarcoFalke** [comment]
@jnewbery I think it is cleaner to bump the subtree separately. (Once for bitcoin-core/univalue#10, and then some time in the future, not necessarily now, for bitcoin-core/univalue#11)

**Comment by jnewbery** [comment]
> I think it is cleaner to bump the subtree separately.

Sure, I'm happy to review a PR that does that.

**Pull request closed without merging**
