### PR TITLE
build: Avoid remaking makefiles.

### PR DESCRIPTION
**Pull request by dgoncharov**
The purpose of this commit is to reduce the amount of work make does.
This simplifies make -d output and improves performance (this
performance gain is hardly noticeable).

By default make remakes all makefiles.
This build system does not have rules to remake makefiles.
This commit adds an explicit rule for each makefile.

Each rule serves 2 purposes.
1. Each rule prevents make from searching for an implicit rule.
2. Once found, the rule prevents make from remaking the makefile.
That's why the rule is double colon. Make won't use a double colon rule to
remake a makefile. See
https://www.gnu.org/software/make/manual/make.html#Remaking-Makefiles.

$ # on this branch.
$ make -d print-host |grep expat
Reading makefile 'packages/expat.mk' (search path) (no ~ expansion)...
Makefile 'packages/expat.mk' might loop; not remaking it.
$ git co master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
$ make -d print-host |grep expat |wc
    367    1916   19918
$

Make prints 367 lines per makefile.
With this change make prints 2 lines per makefile.

### CODE REVIEW

**Comment by dongcarl** [comment]
Are there any global flags/env vars for `make` we can set to accomplish this instead?

**Comment by dgoncharov** [comment]
Make tries rebuilding makefiles. Even if the user does not specify a makefile and there is no need for a makefile, then still make tries updating the default makefiles.

-r will affect the lookup. So, when -r is specified make will not search for a builtin rule. But make -r will still try updating the makefile.

A double colon rule is the mechanism which causes make (atleast the current implementation) to skip updating the makefile.

**Comment by dgoncharov** [comment]
Closed in favor of pr #22486.

**Comment by fanquake** [comment]
In future, please try and fixup / recover your branch rather than opening a new PR for the same change.

**Pull request closed without merging**
