### PR TITLE
build: use latest config.{guess,sub} in depends

### PR DESCRIPTION
**Pull request by fanquake**
Been a few years since we last updated these.
Also related to https://github.com/bitcoin/bitcoin/pull/26422#issuecomment-1421178967.

### CODE REVIEW

**Comment by hebasto** [comment]
Concept ACK.

**Comment by fanquake** [comment]
Guix Build:
```bash
fef9152d593aa1cb3243f37b8c069ef863f4e270962e17918cfa83e18c9eac3a  guix-build-4a3f1db4ea5f/output/aarch64-linux-gnu/SHA256SUMS.part
3fa8236cea2ba1a08d0caf677de80f798f2594cb208f10e5dfe0a9a71de7978d  guix-build-4a3f1db4ea5f/output/aarch64-linux-gnu/bitcoin-4a3f1db4ea5f-aarch64-linux-gnu-debug.tar.gz
36409f4fa6acfb577d6e6a43c2fda2d81f1fb6fb4e5d90cbaa65a2dbb26d1c23  guix-build-4a3f1db4ea5f/output/aarch64-linux-gnu/bitcoin-4a3f1db4ea5f-aarch64-linux-gnu.tar.gz
02a62c4cc2ecb63b94c573514a713fdbceebc05c36dfee5907cca2745597496e  guix-build-4a3f1db4ea5f/output/arm-linux-gnueabihf/SHA256SUMS.part
2805e862b6dc81cd7e47ae9a48d2e2bbc7ca5dc85acf8a10405e86ebb907ebf3  guix-build-4a3f1db4ea5f/output/arm-linux-gnueabihf/bitcoin-4a3f1db4ea5f-arm-linux-gnueabihf-debug.tar.gz
95d868d7c68131c61ddf62a2ac847c292c2cbabfe818b2f71f52555ab3a41710  guix-build-4a3f1db4ea5f/output/arm-linux-gnueabihf/bitcoin-4a3f1db4ea5f-arm-linux-gnueabihf.tar.gz
2bd22b4fa7a5f457b3e0978404356619426a7e76728c601486793553a994431e  guix-build-4a3f1db4ea5f/output/arm64-apple-darwin/SHA256SUMS.part
d9707433e920b4ad9bc9986478adb5475db661431554429be79a0a30e4743cfd  guix-build-4a3f1db4ea5f/output/arm64-apple-darwin/bitcoin-4a3f1db4ea5f-arm64-apple-darwin-unsigned.dmg
9dd47dde54b433c0798b098468c27ea299fa4e8ac910ace2abc998a7358124eb  guix-build-4a3f1db4ea5f/output/arm64-apple-darwin/bitcoin-4a3f1db4ea5f-arm64-apple-darwin-unsigned.tar.gz
847c21df8c6b40732cbb951f262c3e8e39777d9e3f9888b14d6f5150e6325051  guix-build-4a3f1db4ea5f/output/arm64-apple-darwin/bitcoin-4a3f1db4ea5f-arm64-apple-darwin.tar.gz
2b6bf0d2de499882c8062fd4b6cec1894fe522c142fb6d8f29933a484fc551f4  guix-build-4a3f1db4ea5f/output/dist-archive/bitcoin-4a3f1db4ea5f.tar.gz
fe5267eccb3bdc06dc5e34374eb8f1fb9af7736e1bc9844305be5cf07ccffeaf  guix-build-4a3f1db4ea5f/output/powerpc64-linux-gnu/SHA256SUMS.part
53791f0e83a69a5c3b08c92aaac5111e2dea95e2537f8ba4b1b4cc6f574086ff  guix-build-4a3f1db4ea5f/output/powerpc64-linux-gnu/bitcoin-4a3f1db4ea5f-powerpc64-linux-gnu-debug.tar.gz
c2fa3be2e77fe3bf5e87c5cfa7a9045e5231190de870afb02e393aa646531513  guix-build-4a3f1db4ea5f/output/powerpc64-linux-gnu/bitcoin-4a3f1db4ea5f-powerpc64-linux-gnu.tar.gz
808bdb703bf44f00011610c8d400a7f7e18fb52690114af628b04dcaff39a960  guix-build-4a3f1db4ea5f/output/powerpc64le-linux-gnu/SHA256SUMS.part
f252b3be66016f3d89d0893e41d0df28d649972e51bb2d31daaff99cd34aece2  guix-build-4a3f1db4ea5f/output/powerpc64le-linux-gnu/bitcoin-4a3f1db4ea5f-powerpc64le-linux-gnu-debug.tar.gz
7c48092f69fea1e49cbbf89a701356f5a3c8172872a4ac6f2d176a39446525b5  guix-build-4a3f1db4ea5f/output/powerpc64le-linux-gnu/bitcoin-4a3f1db4ea5f-powerpc64le-linux-gnu.tar.gz
de4bcefa8e2eec7352e2df405a4a8fe4503e323ce16ea85d71ae7bcc7dadc2e4  guix-build-4a3f1db4ea5f/output/riscv64-linux-gnu/SHA256SUMS.part
4843bd78a00fbb79dc6cadc7b79233d7cc4f3568ffe263b5fc8935abd96b44c5  guix-build-4a3f1db4ea5f/output/riscv64-linux-gnu/bitcoin-4a3f1db4ea5f-riscv64-linux-gnu-debug.tar.gz
4cc7ab51eec6805e330e5d67ac5ba6207576ab71b9fdcf1e19df449e290d0fa8  guix-build-4a3f1db4ea5f/output/riscv64-linux-gnu/bitcoin-4a3f1db4ea5f-riscv64-linux-gnu.tar.gz
bd03f188c71bb2915df76bcba6fb2d6d1e1bdc2f1b6abc5a5e46f630cf45c4f3  guix-build-4a3f1db4ea5f/output/x86_64-apple-darwin/SHA256SUMS.part
d968f4012afe6c4dc12495e0228d5d40e9a1777d3a1a64ee552f09054f5b29bf  guix-build-4a3f1db4ea5f/output/x86_64-apple-darwin/bitcoin-4a3f1db4ea5f-x86_64-apple-darwin-unsigned.dmg
f5b6f3ad52025747ad5bf0b163bb4aa9094d3d7526cefa4740e3e9e26babe9e3  guix-build-4a3f1db4ea5f/output/x86_64-apple-darwin/bitcoin-4a3f1db4ea5f-x86_64-apple-darwin-unsigned.tar.gz
5a7ccda1478013c0bc58b80936425cd1b343197498fe7715f4a43c12fa503308  guix-build-4a3f1db4ea5f/output/x86_64-apple-darwin/bitcoin-4a3f1db4ea5f-x86_64-apple-darwin.tar.gz
ab68ddaa21015912de748a085f9b8cea94693af1fd50b3fe45f6183cc3a90611  guix-build-4a3f1db4ea5f/output/x86_64-linux-gnu/SHA256SUMS.part
d607bedd784333de028e67ad7fd861d97e1a47bfaafdfb6366aa331730156a05  guix-build-4a3f1db4ea5f/output/x86_64-linux-gnu/bitcoin-4a3f1db4ea5f-x86_64-linux-gnu-debug.tar.gz
3281b5f591d20479aaf0b85ee23768b3ce05d3dfe9f76a1f92c2196e221554cf  guix-build-4a3f1db4ea5f/output/x86_64-linux-gnu/bitcoin-4a3f1db4ea5f-x86_64-linux-gnu.tar.gz
6464f4baea19eff6d6b15378a26f1d3671882d0a0aea904bbed7895f97f748bd  guix-build-4a3f1db4ea5f/output/x86_64-w64-mingw32/SHA256SUMS.part
660b82cb904f4a50390fb3706ed283270af0bc0f78400689a7e0ec4c789bfd68  guix-build-4a3f1db4ea5f/output/x86_64-w64-mingw32/bitcoin-4a3f1db4ea5f-win64-debug.zip
90304a2755f5d6dc3de1c4d146e9808d1e631cb111900b823a78316e087b63b5  guix-build-4a3f1db4ea5f/output/x86_64-w64-mingw32/bitcoin-4a3f1db4ea5f-win64-setup-unsigned.exe
cbb1670d23989c6b68d089dd430a0b4f02688e33a6a68b9b1913c6e1ba72deee  guix-build-4a3f1db4ea5f/output/x86_64-w64-mingw32/bitcoin-4a3f1db4ea5f-win64-unsigned.tar.gz
4d3603b523031cc2a6c747537dc6db936d9e82e897f31fe44a4f471878a33444  guix-build-4a3f1db4ea5f/output/x86_64-w64-mingw32/bitcoin-4a3f1db4ea5f-win64.zip
```

**Review by sedited — APPROVED** [review]
ACK 4a3f1db4ea5f90277cf7f57c051a2285e8b42468

I also checked the content from
```
wget 'https://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD' -O config.guess
wget 'https://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD' -O config.sub
```

Guix builds:
```
find guix-build-$(git rev-parse --short=12 HEAD)/output/ -type f -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum
fef9152d593aa1cb3243f37b8c069ef863f4e270962e17918cfa83e18c9eac3a  guix-build-4a3f1db4ea5f/output/aarch64-linux-gnu/SHA256SUMS.part
3fa8236cea2ba1a08d0caf677de80f798f2594cb208f10e5dfe0a9a71de7978d  guix-build-4a3f1db4ea5f/output/aarch64-linux-gnu/bitcoin-4a3f1db4ea5f-aarch64-linux-gnu-debug.tar.gz
36409f4fa6acfb577d6e6a43c2fda2d81f1fb6fb4e5d90cbaa65a2dbb26d1c23  guix-build-4a3f1db4ea5f/output/aarch64-linux-gnu/bitcoin-4a3f1db4ea5f-aarch64-linux-gnu.tar.gz
02a62c4cc2ecb63b94c573514a713fdbceebc05c36dfee5907cca2745597496e  guix-build-4a3f1db4ea5f/output/arm-linux-gnueabihf/SHA256SUMS.part
2805e862b6dc81cd7e47ae9a48d2e2bbc7ca5dc85acf8a10405e86ebb907ebf3  guix-build-4a3f1db4ea5f/output/arm-linux-gnueabihf/bitcoin-4a3f1db4ea5f-arm-linux-gnueabihf-debug.tar.gz
95d868d7c68131c61ddf62a2ac847c292c2cbabfe818b2f71f52555ab3a41710  guix-build-4a3f1db4ea5f/output/arm-linux-gnueabihf/bitcoin-4a3f1db4ea5f-arm-linux-gnueabihf.tar.gz
2bd22b4fa7a5f457b3e0978404356619426a7e76728c601486793553a994431e  guix-build-4a3f1db4ea5f/output/arm64-apple-darwin/SHA256SUMS.part
d9707433e920b4ad9bc9986478adb5475db661431554429be79a0a30e4743cfd  guix-build-4a3f1db4ea5f/output/arm64-apple-darwin/bitcoin-4a3f1db4ea5f-arm64-apple-darwin-unsigned.dmg
9dd47dde54b433c0798b098468c27ea299fa4e8ac910ace2abc998a7358124eb  guix-build-4a3f1db4ea5f/output/arm64-apple-darwin/bitcoin-4a3f1db4ea5f-arm64-apple-darwin-unsigned.tar.gz
847c21df8c6b40732cbb951f262c3e8e39777d9e3f9888b14d6f5150e6325051  guix-build-4a3f1db4ea5f/output/arm64-apple-darwin/bitcoin-4a3f1db4ea5f-arm64-apple-darwin.tar.gz
2b6bf0d2de499882c8062fd4b6cec1894fe522c142fb6d8f29933a484fc551f4  guix-build-4a3f1db4ea5f/output/dist-archive/bitcoin-4a3f1db4ea5f.tar.gz
fe5267eccb3bdc06dc5e34374eb8f1fb9af7736e1bc9844305be5cf07ccffeaf  guix-build-4a3f1db4ea5f/output/powerpc64-linux-gnu/SHA256SUMS.part
53791f0e83a69a5c3b08c92aaac5111e2dea95e2537f8ba4b1b4cc6f574086ff  guix-build-4a3f1db4ea5f/output/powerpc64-linux-gnu/bitcoin-4a3f1db4ea5f-powerpc64-linux-gnu-debug.tar.gz
c2fa3be2e77fe3bf5e87c5cfa7a9045e5231190de870afb02e393aa646531513  guix-build-4a3f1db4ea5f/output/powerpc64-linux-gnu/bitcoin-4a3f1db4ea5f-powerpc64-linux-gnu.tar.gz
808bdb703bf44f00011610c8d400a7f7e18fb52690114af628b04dcaff39a960  guix-build-4a3f1db4ea5f/output/powerpc64le-linux-gnu/SHA256SUMS.part
f252b3be66016f3d89d0893e41d0df28d649972e51bb2d31daaff99cd34aece2  guix-build-4a3f1db4ea5f/output/powerpc64le-linux-gnu/bitcoin-4a3f1db4ea5f-powerpc64le-linux-gnu-debug.tar.gz
7c48092f69fea1e49cbbf89a701356f5a3c8172872a4ac6f2d176a39446525b5  guix-build-4a3f1db4ea5f/output/powerpc64le-linux-gnu/bitcoin-4a3f1db4ea5f-powerpc64le-linux-gnu.tar.gz
de4bcefa8e2eec7352e2df405a4a8fe4503e323ce16ea85d71ae7bcc7dadc2e4  guix-build-4a3f1db4ea5f/output/riscv64-linux-gnu/SHA256SUMS.part
4843bd78a00fbb79dc6cadc7b79233d7cc4f3568ffe263b5fc8935abd96b44c5  guix-build-4a3f1db4ea5f/output/riscv64-linux-gnu/bitcoin-4a3f1db4ea5f-riscv64-linux-gnu-debug.tar.gz
4cc7ab51eec6805e330e5d67ac5ba6207576ab71b9fdcf1e19df449e290d0fa8  guix-build-4a3f1db4ea5f/output/riscv64-linux-gnu/bitcoin-4a3f1db4ea5f-riscv64-linux-gnu.tar.gz
bd03f188c71bb2915df76bcba6fb2d6d1e1bdc2f1b6abc5a5e46f630cf45c4f3  guix-build-4a3f1db4ea5f/output/x86_64-apple-darwin/SHA256SUMS.part
d968f4012afe6c4dc12495e0228d5d40e9a1777d3a1a64ee552f09054f5b29bf  guix-build-4a3f1db4ea5f/output/x86_64-apple-darwin/bitcoin-4a3f1db4ea5f-x86_64-apple-darwin-unsigned.dmg
f5b6f3ad52025747ad5bf0b163bb4aa9094d3d7526cefa4740e3e9e26babe9e3  guix-build-4a3f1db4ea5f/output/x86_64-apple-darwin/bitcoin-4a3f1db4ea5f-x86_64-apple-darwin-unsigned.tar.gz
5a7ccda1478013c0bc58b80936425cd1b343197498fe7715f4a43c12fa503308  guix-build-4a3f1db4ea5f/output/x86_64-apple-darwin/bitcoin-4a3f1db4ea5f-x86_64-apple-darwin.tar.gz
ab68ddaa21015912de748a085f9b8cea94693af1fd50b3fe45f6183cc3a90611  guix-build-4a3f1db4ea5f/output/x86_64-linux-gnu/SHA256SUMS.part
d607bedd784333de028e67ad7fd861d97e1a47bfaafdfb6366aa331730156a05  guix-build-4a3f1db4ea5f/output/x86_64-linux-gnu/bitcoin-4a3f1db4ea5f-x86_64-linux-gnu-debug.tar.gz
3281b5f591d20479aaf0b85ee23768b3ce05d3dfe9f76a1f92c2196e221554cf  guix-build-4a3f1db4ea5f/output/x86_64-linux-gnu/bitcoin-4a3f1db4ea5f-x86_64-linux-gnu.tar.gz
6464f4baea19eff6d6b15378a26f1d3671882d0a0aea904bbed7895f97f748bd  guix-build-4a3f1db4ea5f/output/x86_64-w64-mingw32/SHA256SUMS.part
660b82cb904f4a50390fb3706ed283270af0bc0f78400689a7e0ec4c789bfd68  guix-build-4a3f1db4ea5f/output/x86_64-w64-mingw32/bitcoin-4a3f1db4ea5f-win64-debug.zip
90304a2755f5d6dc3de1c4d146e9808d1e631cb111900b823a78316e087b63b5  guix-build-4a3f1db4ea5f/output/x86_64-w64-mingw32/bitcoin-4a3f1db4ea5f-win64-setup-unsigned.exe
cbb1670d23989c6b68d089dd430a0b4f02688e33a6a68b9b1913c6e1ba72deee  guix-build-4a3f1db4ea5f/output/x86_64-w64-mingw32/bitcoin-4a3f1db4ea5f-win64-unsigned.tar.gz
4d3603b523031cc2a6c747537dc6db936d9e82e897f31fe44a4f471878a33444  guix-build-4a3f1db4ea5f/output/x86_64-w64-mingw32/bitcoin-4a3f1db4ea5f-win64.zip
```

**Comment by hebasto** [comment]
My Guix builds:
```
fef9152d593aa1cb3243f37b8c069ef863f4e270962e17918cfa83e18c9eac3a  guix-build-4a3f1db4ea5f/output/aarch64-linux-gnu/SHA256SUMS.part
3fa8236cea2ba1a08d0caf677de80f798f2594cb208f10e5dfe0a9a71de7978d  guix-build-4a3f1db4ea5f/output/aarch64-linux-gnu/bitcoin-4a3f1db4ea5f-aarch64-linux-gnu-debug.tar.gz
36409f4fa6acfb577d6e6a43c2fda2d81f1fb6fb4e5d90cbaa65a2dbb26d1c23  guix-build-4a3f1db4ea5f/output/aarch64-linux-gnu/bitcoin-4a3f1db4ea5f-aarch64-linux-gnu.tar.gz
02a62c4cc2ecb63b94c573514a713fdbceebc05c36dfee5907cca2745597496e  guix-build-4a3f1db4ea5f/output/arm-linux-gnueabihf/SHA256SUMS.part
2805e862b6dc81cd7e47ae9a48d2e2bbc7ca5dc85acf8a10405e86ebb907ebf3  guix-build-4a3f1db4ea5f/output/arm-linux-gnueabihf/bitcoin-4a3f1db4ea5f-arm-linux-gnueabihf-debug.tar.gz
95d868d7c68131c61ddf62a2ac847c292c2cbabfe818b2f71f52555ab3a41710  guix-build-4a3f1db4ea5f/output/arm-linux-gnueabihf/bitcoin-4a3f1db4ea5f-arm-linux-gnueabihf.tar.gz
2bd22b4fa7a5f457b3e0978404356619426a7e76728c601486793553a994431e  guix-build-4a3f1db4ea5f/output/arm64-apple-darwin/SHA256SUMS.part
d9707433e920b4ad9bc9986478adb5475db661431554429be79a0a30e4743cfd  guix-build-4a3f1db4ea5f/output/arm64-apple-darwin/bitcoin-4a3f1db4ea5f-arm64-apple-darwin-unsigned.dmg
9dd47dde54b433c0798b098468c27ea299fa4e8ac910ace2abc998a7358124eb  guix-build-4a3f1db4ea5f/output/arm64-apple-darwin/bitcoin-4a3f1db4ea5f-arm64-apple-darwin-unsigned.tar.gz
847c21df8c6b40732cbb951f262c3e8e39777d9e3f9888b14d6f5150e6325051  guix-build-4a3f1db4ea5f/output/arm64-apple-darwin/bitcoin-4a3f1db4ea5f-arm64-apple-darwin.tar.gz
2b6bf0d2de499882c8062fd4b6cec1894fe522c142fb6d8f29933a484fc551f4  guix-build-4a3f1db4ea5f/output/dist-archive/bitcoin-4a3f1db4ea5f.tar.gz
fe5267eccb3bdc06dc5e34374eb8f1fb9af7736e1bc9844305be5cf07ccffeaf  guix-build-4a3f1db4ea5f/output/powerpc64-linux-gnu/SHA256SUMS.part
53791f0e83a69a5c3b08c92aaac5111e2dea95e2537f8ba4b1b4cc6f574086ff  guix-build-4a3f1db4ea5f/output/powerpc64-linux-gnu/bitcoin-4a3f1db4ea5f-powerpc64-linux-gnu-debug.tar.gz
c2fa3be2e77fe3bf5e87c5cfa7a9045e5231190de870afb02e393aa646531513  guix-build-4a3f1db4ea5f/output/powerpc64-linux-gnu/bitcoin-4a3f1db4ea5f-powerpc64-linux-gnu.tar.gz
808bdb703bf44f00011610c8d400a7f7e18fb52690114af628b04dcaff39a960  guix-build-4a3f1db4ea5f/output/powerpc64le-linux-gnu/SHA256SUMS.part
f252b3be66016f3d89d0893e41d0df28d649972e51bb2d31daaff99cd34aece2  guix-build-4a3f1db4ea5f/output/powerpc64le-linux-gnu/bitcoin-4a3f1db4ea5f-powerpc64le-linux-gnu-debug.tar.gz
7c48092f69fea1e49cbbf89a701356f5a3c8172872a4ac6f2d176a39446525b5  guix-build-4a3f1db4ea5f/output/powerpc64le-linux-gnu/bitcoin-4a3f1db4ea5f-powerpc64le-linux-gnu.tar.gz
de4bcefa8e2eec7352e2df405a4a8fe4503e323ce16ea85d71ae7bcc7dadc2e4  guix-build-4a3f1db4ea5f/output/riscv64-linux-gnu/SHA256SUMS.part
4843bd78a00fbb79dc6cadc7b79233d7cc4f3568ffe263b5fc8935abd96b44c5  guix-build-4a3f1db4ea5f/output/riscv64-linux-gnu/bitcoin-4a3f1db4ea5f-riscv64-linux-gnu-debug.tar.gz
4cc7ab51eec6805e330e5d67ac5ba6207576ab71b9fdcf1e19df449e290d0fa8  guix-build-4a3f1db4ea5f/output/riscv64-linux-gnu/bitcoin-4a3f1db4ea5f-riscv64-linux-gnu.tar.gz
bd03f188c71bb2915df76bcba6fb2d6d1e1bdc2f1b6abc5a5e46f630cf45c4f3  guix-build-4a3f1db4ea5f/output/x86_64-apple-darwin/SHA256SUMS.part
d968f4012afe6c4dc12495e0228d5d40e9a1777d3a1a64ee552f09054f5b29bf  guix-build-4a3f1db4ea5f/output/x86_64-apple-darwin/bitcoin-4a3f1db4ea5f-x86_64-apple-darwin-unsigned.dmg
f5b6f3ad52025747ad5bf0b163bb4aa9094d3d7526cefa4740e3e9e26babe9e3  guix-build-4a3f1db4ea5f/output/x86_64-apple-darwin/bitcoin-4a3f1db4ea5f-x86_64-apple-darwin-unsigned.tar.gz
5a7ccda1478013c0bc58b80936425cd1b343197498fe7715f4a43c12fa503308  guix-build-4a3f1db4ea5f/output/x86_64-apple-darwin/bitcoin-4a3f1db4ea5f-x86_64-apple-darwin.tar.gz
ab68ddaa21015912de748a085f9b8cea94693af1fd50b3fe45f6183cc3a90611  guix-build-4a3f1db4ea5f/output/x86_64-linux-gnu/SHA256SUMS.part
d607bedd784333de028e67ad7fd861d97e1a47bfaafdfb6366aa331730156a05  guix-build-4a3f1db4ea5f/output/x86_64-linux-gnu/bitcoin-4a3f1db4ea5f-x86_64-linux-gnu-debug.tar.gz
3281b5f591d20479aaf0b85ee23768b3ce05d3dfe9f76a1f92c2196e221554cf  guix-build-4a3f1db4ea5f/output/x86_64-linux-gnu/bitcoin-4a3f1db4ea5f-x86_64-linux-gnu.tar.gz
6464f4baea19eff6d6b15378a26f1d3671882d0a0aea904bbed7895f97f748bd  guix-build-4a3f1db4ea5f/output/x86_64-w64-mingw32/SHA256SUMS.part
660b82cb904f4a50390fb3706ed283270af0bc0f78400689a7e0ec4c789bfd68  guix-build-4a3f1db4ea5f/output/x86_64-w64-mingw32/bitcoin-4a3f1db4ea5f-win64-debug.zip
90304a2755f5d6dc3de1c4d146e9808d1e631cb111900b823a78316e087b63b5  guix-build-4a3f1db4ea5f/output/x86_64-w64-mingw32/bitcoin-4a3f1db4ea5f-win64-setup-unsigned.exe
cbb1670d23989c6b68d089dd430a0b4f02688e33a6a68b9b1913c6e1ba72deee  guix-build-4a3f1db4ea5f/output/x86_64-w64-mingw32/bitcoin-4a3f1db4ea5f-win64-unsigned.tar.gz
4d3603b523031cc2a6c747537dc6db936d9e82e897f31fe44a4f471878a33444  guix-build-4a3f1db4ea5f/output/x86_64-w64-mingw32/bitcoin-4a3f1db4ea5f-win64.zip
```

**Review by hebasto — APPROVED** [review]
ACK 4a3f1db4ea5f90277cf7f57c051a2285e8b42468, I've got zero diff with files from the [upstream](https://git.savannah.gnu.org/gitweb/?p=config.git;a=tree).

**Pull request merged**
