### PR TITLE
consensus: Avoid data race in CBlock class

### PR DESCRIPTION
**Pull request by hebasto**
Ref: #14058, #14072 

CheckBlock can be invoked from multiple threads in parallel. To avoid a data race `std::atomic<bool>` is used.
All comments from #14072 are addressed.

As this PR introduces copy constructors for both `CBlockHeader` and `CBlock` classes, additional refactoring proposed for `CBlock::GetBlockHeader()`.

### CODE REVIEW

**Comment by hebasto** [comment]
@fanquake Done.

**Comment by practicalswift** [comment]
Concept ACK

Thanks for fighting UB (data race is UB) :-)

**Comment by gmaxwell** [comment]
Simply making the check flag atomic doesn't really seem correct to me-- why would we be checking the same block object twice concurrently?  Just making the test atomic prevents the that particular bit of UB but it doesn't mean that there isn't wasted work, or even the potential of a deadlock.

Can someone please summarize how the same block can get checked in parallel and why it makes sense for that to happen? 14058 simply states the test fail with thread sanitizing enabled, but don't explain the sequence of events that lead to the race. I want to make sure that we're not bandaging over a structural flaw that should be fixed with a lock someplace or some other change.

**Comment by promag** [comment]
I agree with @gmaxwell, why make data structure thread safe?

**Comment by promag** [comment]
I think 2nd option is the most reasonable.

**Comment by sipa** [comment]
My preference is avoid adding synchronization primitives to structures that don't need it.

**Comment by gmaxwell** [comment]
It doesn't support multithreaded validation and there are lot of things that prevent that, which is why I was concerned.  Why doesn't the lock on the block index or even cs main prevent concurrency here?

I'd missed that the original case was a unit test.

**Comment by MarcoFalke** [comment]
> Why doesn't the lock on the block index or even cs main prevent concurrency here?

The cs main lock was moved down in this change "Harden against mistakes handling invalid blocks" #9765  by @sdaftuar 

So unless there was a reason to not put it before `CheckBlock`, I suggest to move it up by one line.

**Pull request closed without merging**
