### PR TITLE
[0.15] backport depends: Update Qt download url

### PR DESCRIPTION
**Pull request by fanquake**
GitHub-Pull: #13544
Rebased-From: 2fca656

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Tested ACK 809df9e462 (`make download`)

**Comment by ken2812221** [comment]
utACK 809df9e462760156b1d2c8d5f6c0358f51a87898

**Comment by fanquake** [comment]
The Travis failure here is unrelated, not sure if I've seen it before:
```
Postprocessing native_protobuf...
Caching native_protobuf...
rm: cannot remove ‘/home/travis/build/bitcoin/bitcoin/depends/built/x86_64-unknown-linux-gnu/native_protobuf/native_protobuf-2.6.1-394c73e5a01.tar.gz.hash’: Permission denied
rm: cannot remove ‘/home/travis/build/bitcoin/bitcoin/depends/built/x86_64-unknown-linux-gnu/native_protobuf/native_protobuf-2.6.1-394c73e5a01.tar.gz’: Permission denied
make: *** [/home/travis/build/bitcoin/bitcoin/depends/built/x86_64-unknown-linux-gnu/native_protobuf/native_protobuf-2.6.1-bdb45206fb2.tar.gz] Error 1
make: Leaving directory `/home/travis/build/bitcoin/bitcoin/depends'
```

**Comment by MarcoFalke** [comment]
This failure already exists on the 0.15 branch. It fetches the master cache and that probably has wrong read-write permissions set. (Could be because the docker user != travis user?)

**Pull request merged**
