### PR TITLE
qa: Ignore shellcheck warning SC2236

### PR DESCRIPTION
**Pull request by promag**
With shellcheck 0.6.0 the warning `SC2236 -  Use -n instead of ! -z` is raised. This change adds that warning to the ignored list.

### CODE REVIEW

**Comment by laanwj** [comment]
Thanks. utACK 98584ff548e267a1dc1d5240e560c623c5287424, let's merge if it fixes travis.

BTW, a similar thing was already done before in 908a559f33.

To prevent this from happening over and over again it might make sense to change to a list of checks to *include*, instead of a list of checks to *exclude*.
(not sure this is easy to do or would require manually going over the list)

**Comment by promag** [comment]
@practicalswift ping.

**Comment by practicalswift** [comment]
Concept ACK, but please print the version only when `shellcheck` had something to say:

```
if [[ $? != 0 ]]; then
    echo
    shellcheck --version
fi
```

IMO check should be silent unless a deviation is found.

The tweak @laanwj is suggestion can be done in a follow-up PR.

**Comment by promag** [comment]
@practicalswift what's the problem of showing the version? Then it's easier to compare between green and red builds.

**Comment by practicalswift** [comment]
@promag Travis already prints the shellcheck version by default:

```
shellcheck version
0.6.0
```

But more generally we should try to keep the signal to noise as high as possible.

**Comment by promag** [comment]
> Travis already prints the `shellcheck` version by default under "Build system information":

Oh ty! will remove that.

**Comment by promag** [comment]
Done.

**Comment by practicalswift** [comment]
utACK f652f85d0c88629b4284f69b179362254307fb55

**Pull request merged**
