### PR TITLE
scripted-diff: Replace three dots with ellipsis in the UI strings

### PR DESCRIPTION
**Pull request by hebasto**
This PR is split from #21463.
The change was suggested on [Transifex.com](https://www.transifex.com/bitcoin/bitcoin/), and it does not touch `LogPrint` and `LogPrintf` calls.

The only comment on #21463 [was](https://github.com/bitcoin/bitcoin/pull/21463/commits/9030e4b5a6de54e041c59e98d91adecbebf3611a#r597220100):
> Mind that these messages also end up in the log. In principle the log is already UTF-8 (as are all strings and text in bitcoind). But, just noting, that it might make browsing the log a less pleasant experience on systems with misconfigured locale like some BSDs by default.

### CODE REVIEW

**Comment by kiminuo** [comment]
Concept ACK, it's much nicer!

Went line by line and it looks correct to me.

**Comment by laanwj** [comment]
ACK d66f283ac07edce432b964f7f814631f5a5bc33b
We do want to do an English translation update after this to prevent people from wasting time translating the old messages.

**Comment by kristapsk** [comment]
What are the benefits of this? Just looking nicer (which is discutable too)?

**Comment by kiminuo** [comment]
> What are the benefits of this? Just looking nicer (which is discutable too)?

For many people there will be zero benefit. It depends on audience. Either you care about typography or you don't. 

Anyway, when I open randomly a few applications on my computer, ellipses are used in dialogs and menus often so Bitcoin Core will behave as other applications do which is a good thing I think.

**Comment by hebasto** [comment]
> What are the benefits of this? Just looking nicer (which is discutable too)?

As stated in the pr description, this change was suggested by translators on Transifex.com (you could see open issues there).

I personally did not make any research on this topic. I assume that translators could be more experienced than me on it :)

**Comment by laanwj** [comment]
It just seems to be the way to do it nowadays (in the age of unicode). It's intended as ELLIPSIS, there's a dedicated character for it which is better than using three separate dots. It's definitely a very minor thing though and if it becomes controversial in the least we should close this.

**Pull request merged**
