### PR TITLE
docs: fix typo in translation_process.md

### PR DESCRIPTION
**Pull request by johnlow95**

### CODE REVIEW

**Comment by Empact** [comment]
ACK 081f5b4

**Comment by johnlow95** [comment]
do i need to add that also?

**Comment by johnlow95** [comment]
confuse on ?

**Comment by Empact** [comment]
The `ACK 081f5b4` I added earlier was an explicit approval of that specific change. You can remove it from the title.

**Comment by johnlow95** [comment]
oh, sorry for that

**Comment by johnlow95** [comment]
so now i wait for the PR to be approve and merge?

**Comment by Empact** [comment]
Yeah now other people will review and merge it if they see fit.

**Comment by johnlow95** [comment]
anywhere i can get someone to commit it, I need it for my assignment

**Comment by fanquake** [comment]
trivial ACK 081f5b4

**Comment by practicalswift** [comment]
@johnlow95 Please remove the "of" in commit text and title. The "of" is confusing. Those texts should reflect the change your doing.

utACK 081f5b4e2baed28ffa3bf6ce11e0aec7156038c2 modulo the "of" change

**Pull request merged**
