### PR TITLE
refactor: Cleanup clientversion.cpp

### PR DESCRIPTION
**Pull request by hebasto**
This PR:
- removes unused macros and duplicated code
- renames macros in a way, that makes the code self-descriptive.

### CODE REVIEW

**Comment by hebasto** [comment]
Rebased 3335ab4b857c96999b390f92a9fe62a42d827f82 -> 098d26d0cc00cb1bca005a0cd289f4cae753c67b ([pr18616.01](https://github.com/hebasto/bitcoin/commits/pr18616.01) -> [pr18616.02](https://github.com/hebasto/bitcoin/commits/pr18616.02)) due to the conflict with #18556.

**Comment by hebasto** [comment]
@dongcarl Mind looking into this?

**Comment by MarcoFalke** [comment]
Concept ACK

**Comment by brakmic** [comment]
ACK 098d26d0cc00cb1bca005a0cd289f4cae753c67b

Built, run and tested on macOS Catalina 10.15.4

info_window

**Comment by dongcarl** [comment]
068bcc017c695a450e132f060b936800954637ab
----
Perhaps let's separate the pure-rename changes into another commit from the other changes? (I think the changes to `share/genbuild.sh` are the only pure-rename ones). Also, is the `DO_STRINGIZE` a mistake from before? Why is it not needed anymore?

098d26d0cc00cb1bca005a0cd289f4cae753c67b
----
Not quite sure how this mechanism works here, and wasn't able to find a reference to it in the `git-achive(1)` man page, could you point me in the right direction?

**Comment by hebasto** [comment]
@dongcarl 
> ## [098d26d](https://github.com/bitcoin/bitcoin/commit/098d26d0cc00cb1bca005a0cd289f4cae753c67b)
> 
> Not quite sure how this mechanism works here, and wasn't able to find a reference to it in the `git-achive(1)` man page, could you point me in the right direction?

a) we set the `export-subst` attribute for `src/clientversion.cpp` in the `.gitattributes` file: https://github.com/bitcoin/bitcoin/blob/844d2070a2c0106bb7a54be5cad7d4da4d9cd55e/.gitattributes#L1

From the [git docs](https://www.git-scm.com/docs/gitattributes#_creating_an_archive):
> If the attribute `export-subst` is set for a file then Git will expand several placeholders when adding this file to an archive. The expansion depends on the availability of a commit ID, i.e., if `git archive` has been given a tree instead of a commit or a tag then no replacement will be done. The placeholders are the same as those for the option `--pretty=format:` of `git log`, except that they need to be wrapped like this: `$Format:PLACEHOLDERS$` in the file. E.g. the string `$Format:%H$` will be replaced by the commit hash.

b) `$Format:%n#define GIT_COMMIT_ID "%H"$` has two placeholders:
- `%n`, which is [expanded](https://www.git-scm.com/docs/git-log#Documentation/git-log.txt-emnem) to a newline that makes a new _uncommented_ LOC just after the comment that states the same thing :)
```c++
//! git will put "#define GIT_COMMIT_ID ..." on the next line inside archives.
```
- `%H`, which is [expanded](https://www.git-scm.com/docs/git-log#Documentation/git-log.txt-emHem) to a commit hash

**Comment by hebasto** [comment]
@dongcarl 
> Also, is the `DO_STRINGIZE` a mistake from before? Why is it not needed anymore?

It is still required: https://github.com/bitcoin/bitcoin/blob/844d2070a2c0106bb7a54be5cad7d4da4d9cd55e/src/clientversion.h#L17-L22

**Comment by hebasto** [comment]
Updated 098d26d0cc00cb1bca005a0cd289f4cae753c67b -> d88195c30697b1ea3fd64aea0acf2d35520b1737 ([pr18616.02](https://github.com/hebasto/bitcoin/commits/pr18616.02) -> [pr18616.04](https://github.com/hebasto/bitcoin/commits/pr18616.04), [diff](https://github.com/hebasto/bitcoin/compare/pr18616.02..pr18616.04)):

- the pure-rename changes to `share/genbuild.sh` are separated into their own commit (see @dongcarl's [comment](https://github.com/bitcoin/bitcoin/pull/18616#issuecomment-622541334))

@dongcarl 
Thank you for reviewing. All your comments have been addressed.

**Comment by dongcarl** [comment]
Code Review ACK 09ee167a6dd7b2d4ade828affc95a679acfaf6c6

-----

Nit: personally, something like this in `clientversion.cpp` made it a bit more readable for me without sacrificing the DRY-ness:

```cpp
#ifdef BUILD_GIT_TAG
    #define BUILD_DESC BUILD_GIT_TAG
#else
    #define BUILD_BASE_DESC "v" STRINGIZE(CLIENT_VERSION_MAJOR) "." STRINGIZE(CLIENT_VERSION_MINOR) \
                            "." STRINGIZE(CLIENT_VERSION_REVISION) "." STRINGIZE(CLIENT_VERSION_BUILD)
    #ifdef BUILD_GIT_COMMIT
        #define BUILD_DESC BUILD_BASE_DESC "-" BUILD_GIT_COMMIT
    #elif defined(GIT_COMMIT_ID)
        #define BUILD_DESC BUILD_BASE_DESC "-g" GIT_COMMIT_ID
    #else
        #define BUILD_DESC BUILD_BASE_DESC "-unk"
    #endif
#endif

const std::string CLIENT_BUILD(BUILD_DESC);
```

**Comment by hebasto** [comment]
Updated 09ee167a6dd7b2d4ade828affc95a679acfaf6c6 -> c269e618cf53634d3cf270273ab1b0354dc3c119 ([pr18616.05](https://github.com/hebasto/bitcoin/commits/pr18616.05) -> [pr18616.06](https://github.com/hebasto/bitcoin/commits/pr18616.06), [diff](https://github.com/hebasto/bitcoin/compare/pr18616.05..pr18616.06)):

- addressed @dongcarl's [comment](https://github.com/bitcoin/bitcoin/pull/18616#issuecomment-623556368)

**Comment by dongcarl** [comment]
FYI: I tested a branch with both this and my changes in #18741, builds passed fine!

**Comment by hebasto** [comment]
> FYI: I tested a branch with both this and my changes in #18741, builds passed fine!

Does it mean "re-ACK" from you? :)

**Comment by dongcarl** [comment]
Yup! ACK c269e618cf53634d3cf270273ab1b0354dc3c119

**Pull request merged**
