### PR TITLE
fix typo: propagation relay -> delay

### PR DESCRIPTION
**Pull request by jafaber**

### CODE REVIEW

**Comment by paveljanik** [comment]
trivial ACK https://github.com/bitcoin/bitcoin/pull/8380/commits/f891e34cf962b74ba6f29aaea6b368c412b8376d

**Comment by MarcoFalke** [comment]
If someone wants to pick up this nit: There is a line which should not start with `#`: https://github.com/jafaber/bitcoin/blame/f891e34cf962b74ba6f29aaea6b368c412b8376d/doc/release-notes.md#L173 (renders incorrectly)

**Comment by MarcoFalke** [comment]
ACK f891e34

**Comment by fanquake** [comment]
ACK f891e34

**Pull request merged**
