### PR TITLE
wallet: Avoid deserializing unused records when salvaging

### PR DESCRIPTION
**Pull request by achow101**
When salvaging a wallet, the only things that matter are the private keys. It is not necessary to attempt to deserialize any other records, especially if those records are corrupted too.

This PR adds a `KeyFilterFn` function callback to `ReadKeyValue` that salvage uses to filter for only the records that it wants. Of course doing it this way also lets us do other filters in the future from other places should we so desire.

### CODE REVIEW

**Review by ryanofsky — APPROVED** [review]
Code review ACK 0bbe26a1af2aab2287b18048f80b3f70e63e0044. Looks great! This should make the recovery code more robust. Normally it'd be good to have a test case for the problem this fixes, but Marco already wrote one in #19078, so I think we're covered

**Comment by laanwj** [comment]
> When salvaging a wallet, the only things that matter are the private keys. It is not necessary to attempt to deserialize any other records, especially if those records are corrupted too.

What about scripts, can't they be critical as well to spend utxos?

**Comment by achow101** [comment]
> What about scripts, can't they be critical as well to spend utxos?

There are basically two types of scripts that we store: 1) watchonly imports, and 2) the segwit scripts for our keys. For watchonly imports, I don't really think that these are necessary to keep as presumably there is some place else that has those scripts. For segwit scripts for our keys, those are automatically added to the wallet's in-memory `mapScripts` on loading so we don't need to keep them. IIRC the only reason those scripts were written to disk after keys were removed from the keypool was to allow for downgrading to a non-segwit version.

**Comment by laanwj** [comment]
@achow101 Thanks! Clear to me now.

**Review by laanwj — APPROVED** [review]
Code review ACK 0bbe26a1af2aab2287b18048f80b3f70e63e0044

**Pull request merged**
