### PR TITLE
ensure consistent header comment naming conventions

### PR DESCRIPTION
**Pull request by Diapolo**
- BITCOIN_FOLDER_SUBFOLDER_FILENAME_H
- also correct header groupings in core files

### CODE REVIEW

**Comment by jonasschnelli** [comment]
utACK @theuni trivial branch.
@Diapolo would it not make more sense do open such PR directly at the trivial branch? https://github.com/theuni/bitcoin/pulls

**Comment by fanquake** [comment]
utACK. Yes these pulls should really be going straight to the trivial branch.

**Comment by laanwj** [comment]
Please apply these kind of changes directly against the trivial branch. That's why we have it.

**Comment by Diapolo** [comment]
Moved to: https://github.com/theuni/bitcoin/pull/8

**Pull request closed without merging**
