### PR TITLE
build, doc: Drop no longer required packages from macOS cross-compiling dependencies

### PR DESCRIPTION
**Pull request by hebasto**
The `libcap-dev` and `libbz2-dev` packages are no longer required when cross-compiling for macOS.

### CODE REVIEW

**Comment by hebasto** [comment]
May I ask the "Needs gitian build" label for this PR?

**Comment by fanquake** [comment]
macOS gitian builds @ f7f3829a68df173c54ab11ecfe162b840afb64e8:
```bash
Generating report
17f47954ecca153573606a409b23d60c683b62e8a7220566ff5cf8691a1bd76b  bitcoin-f7f3829a68df-osx-unsigned.dmg
0a3b62ca98659df1af116c8c5e5f9d8ae14d37ce34b2927f95972555d51e2850  bitcoin-f7f3829a68df-osx-unsigned.tar.gz
df97c42428922b123f1aed0731b2132b4cc61a5889f414c19d18f721ed3c41fa  bitcoin-f7f3829a68df-osx64.tar.gz
41181bd31fa5e7f4cab804cccd575222618799d9a518754f9831bafe8d49315e  src/bitcoin-f7f3829a68df.tar.gz
558c5655205bfaf1b24c83f5bdf205f14035d68a1248c739e3eea5eb4e5cdccb  bitcoin-core-osx-22-res.yml
Done.
```

**Review by lindacorbett — APPROVED** [review]

**Comment by jonasschnelli** [comment]
ACK.
Gitian Build: https://bitcoin.jonasschnelli.ch/gitian/build/466

(merged on top of master)
    54c234f96d25ee626009855333d542fe2aad06a61dd43798a58f43748350da22  bitcoin-109fa68f8345-osx-unsigned.dmg
    5c3c43c0215c069333ec89872db04b8458bfe5d911beb0d23a0fb05743f11ad3  bitcoin-109fa68f8345-osx-unsigned.tar.gz
    f58d2e5411b80486919cef8ce1deaea058f33b2cb9d941180e56c235347a8ac5  bitcoin-109fa68f8345-osx64.tar.gz
    e93fd08985a3805fae993f247e02d5cb6c9988d5b11fcf8a553ca6244f6a9cb5  src/bitcoin-109fa68f8345.tar.gz

**Review by fanquake — APPROVED** [review]
ACK f7f3829a68df173c54ab11ecfe162b840afb64e8

**Pull request merged**
