### PR TITLE
[0.13 Backport] IBD using chainwork instead of height and not using header timestamp (#9053)

### PR DESCRIPTION
**Pull request by gmaxwell**
This is a backport of PR #9053 -- we passed on backporting it right after it was merged, but it's been in master for over a month now with no issue.

This resolves some frequent annoying misbehavior on testnet (in theory the problems it solves are also possible on mainnet but aren't likely there without miner funny business).

### CODE REVIEW

**Comment by MarcoFalke** [comment]
`GetTotalBlocksEstimate()` is still used in another place in main.

Style nit: Please use the backport script by @luke-jr, so that there is a reference to the original pull and commit hash? (@luke-jr would you mind to put that script in our repo?)

**Comment by gmaxwell** [comment]
@MarcoFalke  K. I believe I addressed your comments (I just imitated the style by hand.)

**Comment by MarcoFalke** [comment]
utACK 5998a09

**Comment by laanwj** [comment]
> I believe I addressed your comments (I just imitated the style by hand.)

LGTM

**Pull request merged**
