### PR TITLE
Bugfix: RPC: Add address_type named param for createmultisig

### PR DESCRIPTION
**Pull request by luke-jr**

### CODE REVIEW

**Comment by ken2812221** [comment]
the third parameter was added in b9024fdda33e5c7a2e61705822ded034dd4f8e3b. utACK d8bf1071cf819fb4e848bb832af8199f084e0434

**Comment by fanquake** [comment]
utACK d8bf107

Looks like this needs back-porting as well.

**Comment by jnewbery** [comment]
utACK d8bf1071cf819fb4e848bb832af8199f084e0434

**Comment by fanquake** [comment]
Backported in #14835.

**Pull request merged**
