### PR TITLE
Create .conf file with RPC credentials if none exists.

### PR DESCRIPTION
**Pull request by Alex-van-der-Peet**
I've attempted to implement issue #3902 as described in its discussion. Description:

If no username and password are provided through the conf file or command line and no conf file exists, one will be created and preconfigured with the username and password recommended in the original console message. The generated username and password will be set in memory too, so the RPC server is immediately accessible with these details.

If a conf file does exists but does not contain a username and password, the old error will show, as I felt it too forward to start modifying a user's existing conf file without their consent.

First attempt to contribute, please don't bite my head off.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
@Alex-van-der-Peet: your contribution are very welcome! Thanks.

This PR would make things more convenient, but, i have a strong feeling that the `bitcoin.conf` file should stay readonly. I think apps like bitcoin-core (critical security requirements) should not create config files automatically.

**Comment by laanwj** [comment]
@gmaxwell and I had an interesting conversation about this once. The idea would be not to generate a `bitcoin.conf`  - there are good reasons to keep config files read-only - but a special 'cookie' file for authentication. This file is generated with random content when the daemon starts. Read access to this file stored in the data directory controls who can access through RPC. This method would be active by default if no `rpcpassword` and `rpcuser` is specified.

This is similar to Tor's `CookieAuthentication`: see https://www.torproject.org/docs/tor-manual.html.en

**Comment by paveljanik** [comment]
I think that we should only create the file when there is no such file.
We should not change the file if it doesn't contain rpcuser and password at all.

So NACK as it is right now.

**Comment by Alex-van-der-Peet** [comment]
@paveljanik Eh? That is how it is implented though. No file -> create file, file -> do nothing.

Also, I might be having a moment of stupidity, but a read-only config file? How would that work exactly?

I checked the access rights of the created file in Ubuntu, I think they're correct.

**Comment by paveljanik** [comment]
@Alex-van-der-Peet ups, sorry. I have reread again and yes, this is how it is implemented.
utACK

**Comment by luke-jr** [comment]
Commit description also needs to be fixed to actually describe the change being made.

**Comment by sipa** [comment]
@laanwj I like that cookie idea!

**Comment by laanwj** [comment]
I'll have a stab at implementing the cookie authentication.

**Comment by laanwj** [comment]
See #6388

**Comment by sipa** [comment]
I prefer #6388's approach.

**Comment by laanwj** [comment]
Closing in favor of #6388

**Pull request closed without merging**
