### PR TITLE
test: Add test for conflicted wallet tx notifications

### PR DESCRIPTION
**Pull request by ryanofsky**
Add test coverage for conflicted wallet transaction notifications so we can improve current behavior and avoid future regressions

https://github.com/bitcoin/bitcoin/pull/9240 - accidental break
https://github.com/bitcoin/bitcoin/issues/9479 - bug report
https://github.com/bitcoin/bitcoin/pull/9371 - fix
https://github.com/bitcoin/bitcoin/pull/16624 - accidental break
https://github.com/bitcoin/bitcoin/issues/18325 - bug report
https://github.com/bitcoin/bitcoin/pull/18600 - potential fix

### CODE REVIEW

**Review by maflcko — APPROVED** [review]
Nice! ACK

**Review by jonatack — COMMENTED** [review]
ACK 2c1c162cd5f60e649d

**Comment by ryanofsky** [comment]
Thanks for reviews, updated 2c1c162cd5f60e649d9d55f6c99301c4985d5bab -> f963a680515eda66429b3d1537a7baf281ab9283 ([`pr/nonot.2`](https://github.com/ryanofsky/bitcoin/commits/pr/nonot.2) -> [`pr/nonot.3`](https://github.com/ryanofsky/bitcoin/commits/pr/nonot.3), [compare](https://github.com/ryanofsky/bitcoin/compare/pr/nonot.2..pr/nonot.3)) with suggestions

**Comment by laanwj** [comment]
Good to have a test for this, it always used to be somewhat ill-defined functionality, apparently breaking many times (reading that list hurts!).

ACK f963a680515eda66429b3d1537a7baf281ab9283

**Comment by jonatack** [comment]
re-ACK f963a680515eda66429b3d1537a7baf281ab9283

**Comment by MarcoFalke** [comment]
ACK f963a680515eda66429b3d1537a7baf281ab9283

**Pull request merged**
