### PR TITLE
wallet: Avoid calling uiInterface.LoadWallet(...) with cs_wallet held

### PR DESCRIPTION
**Pull request by practicalswift**
Follow-up to #11634.

Context: https://github.com/bitcoin/bitcoin/pull/11634#discussion_r227714968

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Can you explain why this is needed?

**Comment by promag** [comment]
@MarcoFalke before #11634 the lock wasn't held when calling `uiInterface.LoadWallet(walletInstance)`. My suggestion was to revert that behaviour change.

**Comment by MarcoFalke** [comment]
Yeah, I don't see the change in behaviour. Is there any?

**Comment by MarcoFalke** [comment]
Ah ok. Slightly tend to NACK due to our refactoring guidelines.

**Comment by practicalswift** [comment]
@MarcoFalke Makes sense! Closing :-)

**Comment by promag** [comment]
I don't get it why this is refactoring, this should just revert something that was changed for no good reason. Anyway it was just a comment.

**Pull request closed without merging**
