### PR TITLE
(Refactor) QA: wallet_basic: Split wtx expected_fields over multiple lines to minimise merge conflicts

### PR DESCRIPTION
**Pull request by luke-jr**
This list seems to be high risk of, and trivial to reduce merge conflicts for.

### CODE REVIEW

**Review by shaavan — COMMENTED** [review]
I agree that expanding the list in multiple lines avoids the possible risk of merge conflicts.

But this section of code is not very actively edited by contributors. Specifically, this code section has been untouched since it was introduced two years ago. 

**Screenshot of Git Blame:**

Screenshot from 2022-02-09 15-30-32

And at the time of writing this review, @DrahtBot is showing a single merge conflict (with #24198) for this PR.

So, considering the frequency with which this section is edited, would you still think this change deserves a separate PR of its own?

I think it would be better to add this commit along with #24198, as PR is already editing this section.

**Comment by brunoerg** [comment]
@shaavan If more people agree on adding it on #24198, I can do it, no problem. 

I agree it would minimize merge conflicts, but I also don't think new fields are added often.

**Comment by luke-jr** [comment]
There's also #21260 and was #18570 (closed)

**Comment by fanquake** [comment]
Closing for now. Feel free to rebase and reopen.

**Pull request closed without merging**
