### PR TITLE
gui: Also log and print messages or questions like bitcoind

### PR DESCRIPTION
**Pull request by maflcko**
Testing and debugging after shutdown are harder if the node was run through the gui, because errors and warnings would not be logged to the debug.log or written to the stderr (as is the case for bitcoind).

### CODE REVIEW

**Comment by promag** [comment]
utACK fa7e969.

I guess calling `handleMessageBox` and friends is not worth it.

BTW `noui.cpp` is in libbitcoin_server which is shared between bitcoind and bitcoin-qt — initially thought `noui.cpp` wasn't included in bitcoin-qt.

**Comment by jonasschnelli** [comment]
utACK fa7e9694e1ed5406036620d4bf0b72a2aa984578

**Comment by laanwj** [comment]
I'm fairly sure that this used to be the behavior, the noui handlers were *always* registered.

But it regressed when moving away from `boost::signals` in #13961, or earlier, which dropped support for having multiple handlers.

utACK fa7e9694e1ed5406036620d4bf0b72a2aa984578 anyhow.

**Comment by MarcoFalke** [comment]
@laanwj I am pretty sure this has always been the case.

Also, it exists on 0.17:
```
$ ./src/qt/bitcoin-qt -regtest -walletdir=/tmp/aaaab
$
```

master:

```
$ ./src/qt/bitcoin-qt -regtest -walletdir=/tmp/aaaab
Error: Specified -walletdir "/tmp/aaaab" does not exist
$

**Comment by laanwj** [comment]
I think I was confused with InitMessage, both qt and the noui implementation have:
```
static void InitMessage(const std::string &message)
{
    LogPrintf("init message: %s\n", message);
}
```
so they were logged for both the GUI and with bitcoind

the init window also subscribes to this handler, but that's no problem, as multiple handlers for these signals are still supported (in contrast to what I thought)

**Comment by MarcoFalke** [comment]
Indeed, init messages are both handled. Though, not the errors, warnings and questions.

**Pull request merged**
