### PR TITLE
[verify-commits] Allow revoked keys to expire

### PR DESCRIPTION
**Pull request by TheBlueMatt**
This should fix verify-commits on master.

### CODE REVIEW

**Comment by theuni** [comment]
I see how this allows expired keys to pass if revoked keys are allowed, but I'm missing what constrains expired to revoked? Also not sure why we'd want that constraint?

**Comment by TheBlueMatt** [comment]
BITCOIN_VERIFY_COMMITS_ALLOW_REVSIG is set in verify-commits.sh for every commit in contrib/verify-commits/allow-revsig-commits.

**Comment by theuni** [comment]
That's what I was missing, thanks.

What happens when the next unrevoked key expires, though? Wouldn't all commits signed by that key fail to verify?

**Comment by TheBlueMatt** [comment]
If a key is not in-use, it should be revoked, and if it is revoked, its commits should be in allow-revsig-commits. (if its in-use, you can keep bumping the expiration date).

**Comment by theuni** [comment]
Sure, that makes sense. What I'm missing is how to sunset a key (a committer leaves) without having to mark all of its commits. Or is the script smart enough to stop at the first allow-revsig parent?

**Comment by TheBlueMatt** [comment]
No, currently you have to add all of their commits to the file. We could change to a first-revoked-signed-commit model like we do SHA512, but for now the list is short so I figure just leave it.

**Comment by theuni** [comment]
Seems to me we should just have a file for expired (sub)keys, and verify-commit is allowed to return EXPKEYSIG for those. Because they'd be historical anyway.

That kind of change isn't urgent though, so utACK d23be309c2c45f655d5f5405e031833fb4b6bbb4 for the sake of fixing master.

**Comment by laanwj** [comment]
utACK

**Pull request merged**
