### PR TITLE
[doc] Fix typos

### PR DESCRIPTION
**Pull request by infertux**
Just removed some duplicate `the the`.

### CODE REVIEW

**Comment by paveljanik** [comment]
ACK https://github.com/infertux/bitcoin/commit/6e4dfa1480e5cdbe07abe90b88f3aab76dbacff4

**Comment by jmcorgan** [comment]
ACK 6e4dfa1

**Comment by fanquake** [comment]
ACK infertux@6e4dfa1

**Comment by jonasschnelli** [comment]
ACK 6e4dfa1480e5cdbe07abe90b88f3aab76dbacff4

**Pull request merged**
