### PR TITLE
optimization: Preallocate addresses in GetAddr based on nNodes

### PR DESCRIPTION
**Pull request by l0rinc**
The upper bound ensures efficient memory usage based on the input constraints.

before:
```
|               ns/op |                op/s |    err% |     total | benchmark
|--------------------:|--------------------:|--------:|----------:|:----------
|           76,852.79 |           13,011.89 |    0.4% |      1.07 | `AddrManGetAddr`
|           76,598.21 |           13,055.14 |    0.2% |      1.07 | `AddrManGetAddr`
|           76,296.32 |           13,106.79 |    0.1% |      1.07 | `AddrManGetAddr`
```

after:
```
|               ns/op |                op/s |    err% |     total | benchmark
|--------------------:|--------------------:|--------:|----------:|:----------
|           65,966.97 |           15,159.10 |    0.3% |      1.07 | `AddrManGetAddr`
|           66,075.40 |           15,134.23 |    0.2% |      1.06 | `AddrManGetAddr`
|           66,306.34 |           15,081.51 |    0.3% |      1.06 | `AddrManGetAddr`
```

### CODE REVIEW

**Comment by brunoerg** [comment]
Perhaps It would be better to cherry-pick this change into #29578 since that touches it?

**Comment by paplorinc** [comment]
@brunoerg, feel free to do that, I'll close this if you cherry-pick it to the other PR (please provide before/after measurements)

**Review by vasild — APPROVED** [review]
ACK 278a1ee27bc760d3eb00069327d4b8f49950f6b6

Note that this may overshoot and allocate more space than is going to be needed. Less so with https://github.com/bitcoin/bitcoin/pull/29578.

**Comment by paplorinc** [comment]
Thanks for the review @vasild, we've moved it over to the other PR

**Comment by paplorinc** [comment]
Reopening since https://github.com/bitcoin/bitcoin/pull/29578 was closed without merging

**Review by stickies-v — APPROVED** [review]
ACK 66082ca3488e7ad78149e05631dccd09be03c961

I don't think this is a particularly impactful change but it's very small and straightforward to review.

**Review by vasild — APPROVED** [review]
ACK 66082ca3488e7ad78149e05631dccd09be03c961

**Comment by fanquake** [comment]
> I don't think this is a particularly impactful change but it's very small and straightforward to review.

I agree, and I think we are probably overdue for a review of what is in `src/bench`, and cleaning out benchmarks that aren't (very) meaningful. IIRC `clang-tidy` has a check for exactly this kind of change, so I think if any more were going to be made, they could be done using that.

**Comment by fanquake** [comment]
The `clang-tidy` check I was thinking of was https://clang.llvm.org/extra/clang-tidy/checks/performance/inefficient-vector-operation.html.

**Pull request merged**
