### PR TITLE
Net: Remove "Address refresh broadcast" logic.

### PR DESCRIPTION
**Pull request by pstratem**
addrKnown is now a CRollingBloomFilter which forgets about entries every 5000 inserts

### CODE REVIEW

**Comment by jgarzik** [comment]
This seems like it would degrade service on networks like testnet with a low level of addresses / address traffic, where the local address would be broadcast far less frequently (versus current code).

**Comment by pstratem** [comment]
@jgarzik The local address is broadcast to all outbound connected peers on connect.

**Comment by laanwj** [comment]
Agree with @jgarzik. I'm not convinced that this is a good idea, specially rebroadcasting our own address once in a while is useful, I don't think we should rely on the implementation details of the rolling bloom filter to do this as a side-effect.

**Comment by sipa** [comment]
I guess I'll remove this part from #7125 as well then.

**Comment by laanwj** [comment]
@sipa Well unless you think our reasoning is wrong? Is there some privacy compromise here?

**Comment by sipa** [comment]
I guess there are a few ways forward:
- Keep as-is, drop the entire filter every 24 hours + rebroadcast.
- Don't drop the filter, but still rebroadcast your own address periodically in a forceful way (bypassing the filter).
- Don't drop the filter, but still rebroadcast periodically (subject to the filter, which means no rebroadcast if there was not enough noise to hide the data in).
- This PR (no drop, no rebroadcast).

**Comment by pstratem** [comment]
@sipa how about randomly settings bits in the filter to 0 instead of completely clearing it?

**Pull request closed without merging**
