### PR TITLE
depends: Bump Qt version to 5.12.11

### LINKED ISSUE #136: macOS 11 (Big Sur) visual bugs
Nighy build on Big Sur "dark mode":
Screenshot 2020-11-24 at 20 13 04

Self compiled on Big Sur "night mode" with depends:
Screenshot 2020-11-24 at 20 10 38

Two major issues:
* [ ] disabling the night mode color palette or adopt it correctly (probably a QT upstream issue)
* [ ] get rid of the white glitch in the debug-window tab-bar-menu 

Qt upstream issue: https://bugreports.qt.io/browse/QTBUG-85546

### PR DESCRIPTION
**Pull request by hebasto**
Qt 5.12.11:
- [fixes](https://github.com/qt/qtbase/commit/c5d904639dbd690a36306e2b455610029704d821) macOS related [QTBUG-87014](https://bugreports.qt.io/browse/QTBUG-87014), and the `fix_bigsur_drawing.patch` (which is our workaround for QTBUG-87014) could be dropped
- [upgrades](https://github.com/qt/qtbase/commit/00326c9dc1ec6c80679347859c2fe01d4837b061) supported macOS SDK to 11.0, and removes related warnings
- fixes tab widget rendering on macOS Big Sur ([here](https://github.com/qt/qtbase/commit/4d6832d03f31b513ff2e3517197691bedddaccdf) and [here](https://github.com/qt/qtbase/commit/28b015342d000b8487c853153f1d93606d3c2add)):
  - master (5.12.10)
DeepinScreenshot_select-area_20210525122725
DeepinScreenshot_select-area_20210525123634
  - this PR (5.12.11)
Screenshot from 2021-05-25 12-28-02

Closes https://github.com/bitcoin-core/gui/issues/136.

### CODE REVIEW

**Comment by fanquake** [comment]
>  has a fix for QTBUG-87014, 

In what scenarios does this currently affect bitcoin-qt on macOS?

**Comment by hebasto** [comment]
> > has a fix for QTBUG-87014,
> 
> In what scenarios does this currently affect bitcoin-qt on macOS?

Building with depends: https://github.com/bitcoin-core/gui/issues/249

**Comment by fanquake** [comment]
> Building with depends: bitcoin-core/gui#249

Ok. So nothings currently broken, because we're patching it. Besides dropping a patch, is there any other benefit to updating to 5.12.11? The way the PR description is written I assumed they were two separate things.

**Comment by hebasto** [comment]
> > Building with depends: [bitcoin-core/gui#249](https://github.com/bitcoin-core/gui/issues/249)
> 
> Ok. So nothings currently broken, because we're patching it. Besides dropping a patch, is there any other benefit to updating to 5.12.11?

Dropping the patch is the only benefit.

> The way the PR description is written I assumed they were two separate things.

the PR description updated.

**Comment by hebasto** [comment]
@fanquake 
> Besides dropping a patch, is there any other benefit to updating to 5.12.11?

More benefits added to the PR description.

**Comment by MarcoFalke** [comment]
Approach ACK

**Comment by fanquake** [comment]
> More benefits added to the PR description.

Ok. Concept ACK if this is actually fixing something. Even if that something is just tab rendering in the GUI, for a single platform; which is probably about as low priority as it gets. Before, I didn't see the point in updating Qt just to skip applying a single patch.

At least this PR had the side effect of turning up some issues in the CI.

**Review by promag — COMMENTED** [review]
Concept ACK.

**Comment by hebasto** [comment]
Rebased 987625c7ea3a171f9e41cc38a214c203c7d58e51 -> fa416cea84d8f1528fc7ecf9a04654aae75ac3f5 ([pr22054.01](https://github.com/hebasto/bitcoin/commits/pr22054.01) -> [pr22054.02](https://github.com/hebasto/bitcoin/commits/pr22054.02)) due to the merging of #22063.

**Comment by laanwj** [comment]
No opinion on this specific one, but qt depends bumps are getting a bit frequent to my taste. I don't think we need to track every minor version. Maybe it's better to schedule a Qt update at some fixed time in the release cycle only *unless* there is a serious issue that makes it impossible to move forward otherwise.

**Comment by hebasto** [comment]
@laanwj 
> No opinion on this specific one, but qt depends bumps are getting a bit frequent to my taste. I don't think we need to track every minor version. Maybe it's better to schedule a Qt update at some fixed time in the release cycle only _unless_ there is a serious issue that makes it impossible to move forward otherwise.

Agree with you in general.

This minor update have visual bug fixes that touches macOS only. OTOH, the next Qt update will be 5.15.x or 6.x.
Visual bugs could just [upset](https://github.com/bitcoin-core/gui/issues/136) macOS users of Bitcoin Core v22.0 for some months.

**Comment by hebasto** [comment]
#### Guix builds:
```
$ find guix-build-$(git rev-parse --short=12 HEAD)/output/ -type f -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum
3b59d9a42f2e5645865b28fd3d5417a39cc80012b54d2b733646f93f01dcaa31  guix-build-fa416cea84d8/output/aarch64-linux-gnu/bitcoin-fa416cea84d8-aarch64-linux-gnu-debug.tar.gz
7808b42eb14718c52717ebb548b60e4c1a2fd98cffeae33aefde6b1224909e72  guix-build-fa416cea84d8/output/aarch64-linux-gnu/bitcoin-fa416cea84d8-aarch64-linux-gnu.tar.gz
b936ee58999b34c9420567e0a12d90b17860e8cc6168eab73a2eaeff21054be6  guix-build-fa416cea84d8/output/aarch64-linux-gnu/inputs.SHA256SUMS
77c90acb1aeb8f44a83f4a089b73fe53fb1130377a146d5451bed4a3e988be95  guix-build-fa416cea84d8/output/arm-linux-gnueabihf/bitcoin-fa416cea84d8-arm-linux-gnueabihf-debug.tar.gz
e84e24a1d50da81e67ff666442256ec1bc0acea1044667c96142d3beb0055674  guix-build-fa416cea84d8/output/arm-linux-gnueabihf/bitcoin-fa416cea84d8-arm-linux-gnueabihf.tar.gz
b936ee58999b34c9420567e0a12d90b17860e8cc6168eab73a2eaeff21054be6  guix-build-fa416cea84d8/output/arm-linux-gnueabihf/inputs.SHA256SUMS
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  guix-build-fa416cea84d8/output/dist-archive/SKIPATTEST.TAG
6703361a420b6a9f5598bf8ab3fa0240544a790091fd28bd5c6425749a739c87  guix-build-fa416cea84d8/output/dist-archive/bitcoin-fa416cea84d8.tar.gz
e8432275271d4b5313b572156b53961a39e2d448d55594092176e24b7b2ebd3a  guix-build-fa416cea84d8/output/powerpc64-linux-gnu/bitcoin-fa416cea84d8-powerpc64-linux-gnu-debug.tar.gz
12cb420dab9ff62e391b3da40ba337b05d17d2a41e61221052697b5ee3d6907c  guix-build-fa416cea84d8/output/powerpc64-linux-gnu/bitcoin-fa416cea84d8-powerpc64-linux-gnu.tar.gz
b936ee58999b34c9420567e0a12d90b17860e8cc6168eab73a2eaeff21054be6  guix-build-fa416cea84d8/output/powerpc64-linux-gnu/inputs.SHA256SUMS
cbd2b492735021697e23a0b6612176ea9b1d24ad21a84443882d5dace93d909e  guix-build-fa416cea84d8/output/powerpc64le-linux-gnu/bitcoin-fa416cea84d8-powerpc64le-linux-gnu-debug.tar.gz
97a49bb3955baa61dd88b9dfea24018404a73aeba9bca48e4b6a539fc3e5c733  guix-build-fa416cea84d8/output/powerpc64le-linux-gnu/bitcoin-fa416cea84d8-powerpc64le-linux-gnu.tar.gz
b936ee58999b34c9420567e0a12d90b17860e8cc6168eab73a2eaeff21054be6  guix-build-fa416cea84d8/output/powerpc64le-linux-gnu/inputs.SHA256SUMS
7c73fc7dc28e0bc59e9908929c1e32ec41c44b80cf46d8eb3675a2057644f7c6  guix-build-fa416cea84d8/output/riscv64-linux-gnu/bitcoin-fa416cea84d8-riscv64-linux-gnu-debug.tar.gz
fc5cdc1ae5bcf657c6a98beeca0d0871d9b86dddb34a803c59f8c2cf45b3b44e  guix-build-fa416cea84d8/output/riscv64-linux-gnu/bitcoin-fa416cea84d8-riscv64-linux-gnu.tar.gz
b936ee58999b34c9420567e0a12d90b17860e8cc6168eab73a2eaeff21054be6  guix-build-fa416cea84d8/output/riscv64-linux-gnu/inputs.SHA256SUMS
64dcedc5f1dbb22acf956ac4b248c7a72e66a15fecaa9f8dbab335ccb7f401ae  guix-build-fa416cea84d8/output/x86_64-apple-darwin18/bitcoin-fa416cea84d8-osx-unsigned.dmg
f476e17c63be2cec30e86be9b37f6925570c82e1cb05092470b4174b8ca33a7a  guix-build-fa416cea84d8/output/x86_64-apple-darwin18/bitcoin-fa416cea84d8-osx-unsigned.tar.gz
7e20c135840d033ad15426532a23244a6ac09b9625d47b43338624698db6b179  guix-build-fa416cea84d8/output/x86_64-apple-darwin18/bitcoin-fa416cea84d8-osx64.tar.gz
b936ee58999b34c9420567e0a12d90b17860e8cc6168eab73a2eaeff21054be6  guix-build-fa416cea84d8/output/x86_64-apple-darwin18/inputs.SHA256SUMS
c6508f46c99decf5152551d8cc605e1351b967e669edfebfa46b45b2796a7415  guix-build-fa416cea84d8/output/x86_64-linux-gnu/bitcoin-fa416cea84d8-x86_64-linux-gnu-debug.tar.gz
e58e6314a713f4c3c5c4546925a8e42db2211fff2d96ed31184290bed8b9f9a0  guix-build-fa416cea84d8/output/x86_64-linux-gnu/bitcoin-fa416cea84d8-x86_64-linux-gnu.tar.gz
b936ee58999b34c9420567e0a12d90b17860e8cc6168eab73a2eaeff21054be6  guix-build-fa416cea84d8/output/x86_64-linux-gnu/inputs.SHA256SUMS
c02e2fbc94b66178834de6efb9976adb5dd52c7cf9e19fedbe81fdc54e5c7396  guix-build-fa416cea84d8/output/x86_64-w64-mingw32/bitcoin-fa416cea84d8-win-unsigned.tar.gz
c756127af1ed03e40c642a283a80b9f3ce569a8ec1250cda0b5b023ae4276558  guix-build-fa416cea84d8/output/x86_64-w64-mingw32/bitcoin-fa416cea84d8-win64-debug.zip
1d99330da26f1521588ef27a1a7b7a627158f4a85bf137410084468771df8256  guix-build-fa416cea84d8/output/x86_64-w64-mingw32/bitcoin-fa416cea84d8-win64-setup-unsigned.exe
a0cc5f2f731f97b2e2fb27c8e739e8ebb5cea52b659b96d19eaf04c7b6fa6485  guix-build-fa416cea84d8/output/x86_64-w64-mingw32/bitcoin-fa416cea84d8-win64.zip
b936ee58999b34c9420567e0a12d90b17860e8cc6168eab73a2eaeff21054be6  guix-build-fa416cea84d8/output/x86_64-w64-mingw32/inputs.SHA256SUMS
```

**Review by fanquake — APPROVED** [review]
ACK fa416cea84d8f1528fc7ecf9a04654aae75ac3f5 - merging this now to move it out of the way of other Qt related changes.

Guix Builds:
```bash
3b59d9a42f2e5645865b28fd3d5417a39cc80012b54d2b733646f93f01dcaa31  guix-build-fa416cea84d8/output/aarch64-linux-gnu/bitcoin-fa416cea84d8-aarch64-linux-gnu-debug.tar.gz
7808b42eb14718c52717ebb548b60e4c1a2fd98cffeae33aefde6b1224909e72  guix-build-fa416cea84d8/output/aarch64-linux-gnu/bitcoin-fa416cea84d8-aarch64-linux-gnu.tar.gz
b936ee58999b34c9420567e0a12d90b17860e8cc6168eab73a2eaeff21054be6  guix-build-fa416cea84d8/output/aarch64-linux-gnu/inputs.SHA256SUMS
77c90acb1aeb8f44a83f4a089b73fe53fb1130377a146d5451bed4a3e988be95  guix-build-fa416cea84d8/output/arm-linux-gnueabihf/bitcoin-fa416cea84d8-arm-linux-gnueabihf-debug.tar.gz
e84e24a1d50da81e67ff666442256ec1bc0acea1044667c96142d3beb0055674  guix-build-fa416cea84d8/output/arm-linux-gnueabihf/bitcoin-fa416cea84d8-arm-linux-gnueabihf.tar.gz
b936ee58999b34c9420567e0a12d90b17860e8cc6168eab73a2eaeff21054be6  guix-build-fa416cea84d8/output/arm-linux-gnueabihf/inputs.SHA256SUMS
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  guix-build-fa416cea84d8/output/dist-archive/SKIPATTEST.TAG
6703361a420b6a9f5598bf8ab3fa0240544a790091fd28bd5c6425749a739c87  guix-build-fa416cea84d8/output/dist-archive/bitcoin-fa416cea84d8.tar.gz
e8432275271d4b5313b572156b53961a39e2d448d55594092176e24b7b2ebd3a  guix-build-fa416cea84d8/output/powerpc64-linux-gnu/bitcoin-fa416cea84d8-powerpc64-linux-gnu-debug.tar.gz
12cb420dab9ff62e391b3da40ba337b05d17d2a41e61221052697b5ee3d6907c  guix-build-fa416cea84d8/output/powerpc64-linux-gnu/bitcoin-fa416cea84d8-powerpc64-linux-gnu.tar.gz
b936ee58999b34c9420567e0a12d90b17860e8cc6168eab73a2eaeff21054be6  guix-build-fa416cea84d8/output/powerpc64-linux-gnu/inputs.SHA256SUMS
cbd2b492735021697e23a0b6612176ea9b1d24ad21a84443882d5dace93d909e  guix-build-fa416cea84d8/output/powerpc64le-linux-gnu/bitcoin-fa416cea84d8-powerpc64le-linux-gnu-debug.tar.gz
97a49bb3955baa61dd88b9dfea24018404a73aeba9bca48e4b6a539fc3e5c733  guix-build-fa416cea84d8/output/powerpc64le-linux-gnu/bitcoin-fa416cea84d8-powerpc64le-linux-gnu.tar.gz
b936ee58999b34c9420567e0a12d90b17860e8cc6168eab73a2eaeff21054be6  guix-build-fa416cea84d8/output/powerpc64le-linux-gnu/inputs.SHA256SUMS
7c73fc7dc28e0bc59e9908929c1e32ec41c44b80cf46d8eb3675a2057644f7c6  guix-build-fa416cea84d8/output/riscv64-linux-gnu/bitcoin-fa416cea84d8-riscv64-linux-gnu-debug.tar.gz
fc5cdc1ae5bcf657c6a98beeca0d0871d9b86dddb34a803c59f8c2cf45b3b44e  guix-build-fa416cea84d8/output/riscv64-linux-gnu/bitcoin-fa416cea84d8-riscv64-linux-gnu.tar.gz
b936ee58999b34c9420567e0a12d90b17860e8cc6168eab73a2eaeff21054be6  guix-build-fa416cea84d8/output/riscv64-linux-gnu/inputs.SHA256SUMS
64dcedc5f1dbb22acf956ac4b248c7a72e66a15fecaa9f8dbab335ccb7f401ae  guix-build-fa416cea84d8/output/x86_64-apple-darwin18/bitcoin-fa416cea84d8-osx-unsigned.dmg
f476e17c63be2cec30e86be9b37f6925570c82e1cb05092470b4174b8ca33a7a  guix-build-fa416cea84d8/output/x86_64-apple-darwin18/bitcoin-fa416cea84d8-osx-unsigned.tar.gz
7e20c135840d033ad15426532a23244a6ac09b9625d47b43338624698db6b179  guix-build-fa416cea84d8/output/x86_64-apple-darwin18/bitcoin-fa416cea84d8-osx64.tar.gz
b936ee58999b34c9420567e0a12d90b17860e8cc6168eab73a2eaeff21054be6  guix-build-fa416cea84d8/output/x86_64-apple-darwin18/inputs.SHA256SUMS
c6508f46c99decf5152551d8cc605e1351b967e669edfebfa46b45b2796a7415  guix-build-fa416cea84d8/output/x86_64-linux-gnu/bitcoin-fa416cea84d8-x86_64-linux-gnu-debug.tar.gz
e58e6314a713f4c3c5c4546925a8e42db2211fff2d96ed31184290bed8b9f9a0  guix-build-fa416cea84d8/output/x86_64-linux-gnu/bitcoin-fa416cea84d8-x86_64-linux-gnu.tar.gz
b936ee58999b34c9420567e0a12d90b17860e8cc6168eab73a2eaeff21054be6  guix-build-fa416cea84d8/output/x86_64-linux-gnu/inputs.SHA256SUMS
c02e2fbc94b66178834de6efb9976adb5dd52c7cf9e19fedbe81fdc54e5c7396  guix-build-fa416cea84d8/output/x86_64-w64-mingw32/bitcoin-fa416cea84d8-win-unsigned.tar.gz
c756127af1ed03e40c642a283a80b9f3ce569a8ec1250cda0b5b023ae4276558  guix-build-fa416cea84d8/output/x86_64-w64-mingw32/bitcoin-fa416cea84d8-win64-debug.zip
1d99330da26f1521588ef27a1a7b7a627158f4a85bf137410084468771df8256  guix-build-fa416cea84d8/output/x86_64-w64-mingw32/bitcoin-fa416cea84d8-win64-setup-unsigned.exe
a0cc5f2f731f97b2e2fb27c8e739e8ebb5cea52b659b96d19eaf04c7b6fa6485  guix-build-fa416cea84d8/output/x86_64-w64-mingw32/bitcoin-fa416cea84d8-win64.zip
b936ee58999b34c9420567e0a12d90b17860e8cc6168eab73a2eaeff21054be6  guix-build-fa416cea84d8/output/x86_64-w64-mingw32/inputs.SHA256SUMS
```

**Comment by hebasto** [comment]
@sipsorcery 

Is it worth to update https://github.com/sipsorcery/qt_win_binary release and our CI stuff?

**Comment by sipsorcery** [comment]
> Is it worth to update https://github.com/sipsorcery/qt_win_binary release and our CI stuff?

I'll get on it. Can take a little while though so I wouldn't hold up this PR or anything else for it.

**Pull request merged**
