### PR TITLE
contrib: remove no longer used contrib/bitcoin-qt.pro

### PR DESCRIPTION
**Pull request by hebasto**
From [IRC](http://www.erisian.com.au/bitcoin-core-dev/log-2021-04-15.html#l-209):
> \<hebasto> wumpus: I cannot see any way how the `contrib/bitcoin-qt.pro` is used in the  translation process, neither in the main repo nor in https://github.com/bitcoin-core/bitcoin-maintainer-tools. Besides it looks outdated and unmaintained. May I ask you to confirm/deny my assumption?
> \<wumpus> hebasto: it is not used for anything, it exists to be able to edit the qt forms in qt designer nothing more
> \<wumpus> i'm not sure if it is even *necessary* for that, but it is why it is there
> \<hebasto> wumpus: thanks, qt designer does not need *.pro file at all
> \<hebasto> maybe qt creator does
> \<wumpus> feel free to create a PR to remove it, best way to find out if someone wants to keep it, you are right it hasn't been updated in a long time
> \<hebasto> ok
> \<wumpus> fwiw, the only question i get about it ever is why it exists
> \<hebasto> it was in use with `qmake` years ago (what I found digging into the repo history)
> \<wumpus> yes, that was the original reason, but when we switched to automake it was kept around for use w/ qt's GUI tools
> \<hebasto> I've noticed it in https://github.com/bitcoin/bitcoin/blame/master/doc/translation_process.md#L25
> \<wumpus> what it says there is definitely not true anymore

### CODE REVIEW

**Comment by laanwj** [comment]
ACK 5f2be6e71e6130b58ebfbf81aaf48ce90dd9d179

**Comment by hebasto** [comment]
@jarolrod 

As you was the last person who checked [Using Qt Creator as an IDE](https://github.com/bitcoin/bitcoin/blob/master/src/qt/README.md#using-qt-creator-as-an-ide), could your confirm/deny the necessary of the `contrib/bitcoin-qt.pro` for such setup?

**Review by jarolrod — COMMENTED** [review]
ACK on removing the line about bitcoin-qt.pro from doc/translation_process.md.

The bitcoin-qt.pro file is a convenient way to quickly open up the GUI ui files and start editing them. The flow is (Using Qt Creator) `Open Project -> Select pro file -> Edit UI Files`. This can be the recommended flow to suggest to designers who'd like to make UI changes. I think it should stay for this reason, and I can add a note to the Qt readme about it.

The pro file is a bit outdated. To bring the pro file up to speed, we'd need to add the following missing `.ui` files under `FORMS +=`:
- modeloverlay.ui
- psbtoperationsdialog.ui

**Comment by hebasto** [comment]
@jarolrod 
Does Qt Creator allow to open `*.ui` file directly (as Qt Designer does)?

**Comment by hebasto** [comment]
> The pro file is a bit outdated. To bring the pro file up to speed, we'd need to add the following missing `.ui` files under `FORMS +=`:
> 
>     * modeloverlay.ui
> 
>     * psbtoperationsdialog.ui

... and remove `aboutdialog.ui`...

**Comment by jarolrod** [comment]
@hebasto yeah you can open up UI files individually. This pro file opens up all of them for you as well as the resources folder. I think it's more convenient to have all of them open. I don't have a strong opinion on this

It could be that no one uses it (i dont) and it could be wasting time to maintain this.

**Comment by hebasto** [comment]
> ... it could be wasting time to maintain this.

That is my concern.

**Comment by Bosch-0** [comment]
I personally do not use this as a designer. Qt Creator has its uses for working with Qt widgets to understand what can and can't be modified on the design side but outside that it's use as a design tool isn't great 

ACK from me if this files requires resources to maintain

**Comment by jarolrod** [comment]
ACK 5f2be6e71e6130b58ebfbf81aaf48ce90dd9d179

ACK because I don't have a strong opinion, the file is not used very much, and the resulting conversation would be more man-hours than is used to maintain this file.

> Qt Creator has its uses for working with Qt widgets to understand what can and can't be modified on the design side but outside that it's use as a design tool isn't great

There's a difference between designing and implementing a design by changing the UI files. Qt Creator, which packages Qt Designer, is the best tool for performing design work that changes the GUI as it's WYSIWYG. 

we could add the two lines and remove the one line, that's the cost of maintenance for now. Or just remove the file. Again no strong opinion.

**Pull request merged**
