### PR TITLE
depends: zeromq 4.3.5

### PR DESCRIPTION
**Pull request by fanquake**
First new point release of zeromq in two and a half years. Mostly bug fixes; the project also completed a relicense to the "Mozilla Public License".

See https://github.com/zeromq/libzmq/releases/tag/v4.3.5.

### CODE REVIEW

**Comment by hebasto** [comment]
Concept ACK.

**Review by hebasto — APPROVED** [review]
ACK 986d7fed057b995a720787cbbd21e1c41763fb83, I have reviewed the code and it looks OK.

**Comment by hebasto** [comment]
My Guix builds:
```
x86_64
59b037743bf99c3e8bf4932ed61c595847daf3c88167b12e02b62ec0d28459b9  guix-build-986d7fed057b/output/aarch64-linux-gnu/SHA256SUMS.part
b7baef8a064db9da3743e671c8075826c3949c275a83f69d22e659d1e4d47326  guix-build-986d7fed057b/output/aarch64-linux-gnu/bitcoin-986d7fed057b-aarch64-linux-gnu-debug.tar.gz
40c565876bdc15639b69c6bbb61ae7f7be00b3643f232ceea7023d1126ab15fe  guix-build-986d7fed057b/output/aarch64-linux-gnu/bitcoin-986d7fed057b-aarch64-linux-gnu.tar.gz
fd63ef307a72332f279ea6b2c6f43826e6d2af7bef3b8db0eb55e20d2cbfcad7  guix-build-986d7fed057b/output/arm-linux-gnueabihf/SHA256SUMS.part
b58ff1c7adeb5a566b5aeeef005f225c8882d85f27a8195e5d5a8365b37d3cac  guix-build-986d7fed057b/output/arm-linux-gnueabihf/bitcoin-986d7fed057b-arm-linux-gnueabihf-debug.tar.gz
2a431f280bd18e3fc873e70b3b8cd07e27089d2efac8a8083ef3604b64b453a7  guix-build-986d7fed057b/output/arm-linux-gnueabihf/bitcoin-986d7fed057b-arm-linux-gnueabihf.tar.gz
ff7eebe52cf818a9bd97cc07d7f931e37daa5a3091c0b990b10ac1f767f5926e  guix-build-986d7fed057b/output/arm64-apple-darwin/SHA256SUMS.part
3119e3a0b031d6a45311c1532220bacd212716186c7bad263eb8b0076c215899  guix-build-986d7fed057b/output/arm64-apple-darwin/bitcoin-986d7fed057b-arm64-apple-darwin-unsigned.tar.gz
f313f2db12eaa6d5284446f0c2f3af6c529c76574d743d4c033a326baa2095d9  guix-build-986d7fed057b/output/arm64-apple-darwin/bitcoin-986d7fed057b-arm64-apple-darwin-unsigned.zip
79badcb4070b2b950eed2fac47e9745d52e9181d5dc4ae82e83ba567e787505d  guix-build-986d7fed057b/output/arm64-apple-darwin/bitcoin-986d7fed057b-arm64-apple-darwin.tar.gz
6410960d0ddc494a95881672e1721140213d3290b2764dec35ceb419f629c2a6  guix-build-986d7fed057b/output/dist-archive/bitcoin-986d7fed057b.tar.gz
3aabb100d5a49af2fc00fbead3e4ff1166c008c2023eaa32257544c355f8bb99  guix-build-986d7fed057b/output/powerpc64-linux-gnu/SHA256SUMS.part
b45d94a09d5231a68f1300f6043b6ea3effc33fe0a177beb8f72eba73dd50191  guix-build-986d7fed057b/output/powerpc64-linux-gnu/bitcoin-986d7fed057b-powerpc64-linux-gnu-debug.tar.gz
8369f5eaaf639c874a500099f7b29a8ad5c7ca1b6ea2fa3a3d946e4464d943ec  guix-build-986d7fed057b/output/powerpc64-linux-gnu/bitcoin-986d7fed057b-powerpc64-linux-gnu.tar.gz
bd98c22bcb077c64802ac6a4fea8c125de3ad51fa059c6cc615961743764c4de  guix-build-986d7fed057b/output/powerpc64le-linux-gnu/SHA256SUMS.part
c4aa32f17d16b5ff11116887dc047fc198942be84431743b667d5e977b975e4c  guix-build-986d7fed057b/output/powerpc64le-linux-gnu/bitcoin-986d7fed057b-powerpc64le-linux-gnu-debug.tar.gz
6b30377ef2d1996131595134e7b0a2894ca60e17e4e254bec2df8fb3738ac833  guix-build-986d7fed057b/output/powerpc64le-linux-gnu/bitcoin-986d7fed057b-powerpc64le-linux-gnu.tar.gz
478fda56708f839699493a04b70833a59470d388d8227c2627a0c7ef52aee12a  guix-build-986d7fed057b/output/riscv64-linux-gnu/SHA256SUMS.part
b6fe8284ca15f9a14ce5326b30d1542a007c41ea0e4b0a7b1a81bb63f7002e89  guix-build-986d7fed057b/output/riscv64-linux-gnu/bitcoin-986d7fed057b-riscv64-linux-gnu-debug.tar.gz
a11db5ba19c21ac662279595478f7ffe85eb9867d2c56b046c4717e434816d8e  guix-build-986d7fed057b/output/riscv64-linux-gnu/bitcoin-986d7fed057b-riscv64-linux-gnu.tar.gz
698abf77725448f82310d0efd661422f39550d377edc565d6042d00a37bf798b  guix-build-986d7fed057b/output/x86_64-apple-darwin/SHA256SUMS.part
27cef1ea92865247cd0692c42228237903f58f14afc29abf0009ceb27e82e158  guix-build-986d7fed057b/output/x86_64-apple-darwin/bitcoin-986d7fed057b-x86_64-apple-darwin-unsigned.tar.gz
0ddad23cc0562d8346463f8cb6a37faf8bde2b7a8570c2a41e07748e59deb13f  guix-build-986d7fed057b/output/x86_64-apple-darwin/bitcoin-986d7fed057b-x86_64-apple-darwin-unsigned.zip
7bcd078a7eb15e439e931512421622d37cbec4395ba742f04f2594fd23624291  guix-build-986d7fed057b/output/x86_64-apple-darwin/bitcoin-986d7fed057b-x86_64-apple-darwin.tar.gz
5ac508736ecaba1e7ccbc70b2728f798d9f31e30f860af7b39dd6ac18c4de2d6  guix-build-986d7fed057b/output/x86_64-linux-gnu/SHA256SUMS.part
25e7dd48f5b3a00d3318084d572737ec380168889dc455a9f6cdd6b5b39ccfbe  guix-build-986d7fed057b/output/x86_64-linux-gnu/bitcoin-986d7fed057b-x86_64-linux-gnu-debug.tar.gz
ffb68a445586283bc874d77828cabedf0251565e8c9434ade7b62d7f5f52a4c6  guix-build-986d7fed057b/output/x86_64-linux-gnu/bitcoin-986d7fed057b-x86_64-linux-gnu.tar.gz
b7028a690cd2f3534b6506e7c12742a80ab2ea371d2ec329ad82f2eedb457747  guix-build-986d7fed057b/output/x86_64-w64-mingw32/SHA256SUMS.part
aaf07cddfe55e8988b4854463f8dfb3d16e00502ab501f6e8f2a67091b630284  guix-build-986d7fed057b/output/x86_64-w64-mingw32/bitcoin-986d7fed057b-win64-debug.zip
82ac6875462f819ff54e77a209062ca51ac4b07d85b518665b6f405864840519  guix-build-986d7fed057b/output/x86_64-w64-mingw32/bitcoin-986d7fed057b-win64-setup-unsigned.exe
cde6c04506dda70a1f0cdef3a50186ecf82a7d0551f8c266f795f8883ae82307  guix-build-986d7fed057b/output/x86_64-w64-mingw32/bitcoin-986d7fed057b-win64-unsigned.tar.gz
8a904f11110f66d741b3dae1cb6412b7fadc4f29b2d477453540dbd1729001a9  guix-build-986d7fed057b/output/x86_64-w64-mingw32/bitcoin-986d7fed057b-win64.zip
```

**Comment by TheCharlatan** [comment]
Guix builds:
```
aarch64 and x86_64
59b037743bf99c3e8bf4932ed61c595847daf3c88167b12e02b62ec0d28459b9  guix-build-986d7fed057b/output/aarch64-linux-gnu/SHA256SUMS.part
b7baef8a064db9da3743e671c8075826c3949c275a83f69d22e659d1e4d47326  guix-build-986d7fed057b/output/aarch64-linux-gnu/bitcoin-986d7fed057b-aarch64-linux-gnu-debug.tar.gz
40c565876bdc15639b69c6bbb61ae7f7be00b3643f232ceea7023d1126ab15fe  guix-build-986d7fed057b/output/aarch64-linux-gnu/bitcoin-986d7fed057b-aarch64-linux-gnu.tar.gz
fd63ef307a72332f279ea6b2c6f43826e6d2af7bef3b8db0eb55e20d2cbfcad7  guix-build-986d7fed057b/output/arm-linux-gnueabihf/SHA256SUMS.part
b58ff1c7adeb5a566b5aeeef005f225c8882d85f27a8195e5d5a8365b37d3cac  guix-build-986d7fed057b/output/arm-linux-gnueabihf/bitcoin-986d7fed057b-arm-linux-gnueabihf-debug.tar.gz
2a431f280bd18e3fc873e70b3b8cd07e27089d2efac8a8083ef3604b64b453a7  guix-build-986d7fed057b/output/arm-linux-gnueabihf/bitcoin-986d7fed057b-arm-linux-gnueabihf.tar.gz
ff7eebe52cf818a9bd97cc07d7f931e37daa5a3091c0b990b10ac1f767f5926e  guix-build-986d7fed057b/output/arm64-apple-darwin/SHA256SUMS.part
3119e3a0b031d6a45311c1532220bacd212716186c7bad263eb8b0076c215899  guix-build-986d7fed057b/output/arm64-apple-darwin/bitcoin-986d7fed057b-arm64-apple-darwin-unsigned.tar.gz
f313f2db12eaa6d5284446f0c2f3af6c529c76574d743d4c033a326baa2095d9  guix-build-986d7fed057b/output/arm64-apple-darwin/bitcoin-986d7fed057b-arm64-apple-darwin-unsigned.zip
79badcb4070b2b950eed2fac47e9745d52e9181d5dc4ae82e83ba567e787505d  guix-build-986d7fed057b/output/arm64-apple-darwin/bitcoin-986d7fed057b-arm64-apple-darwin.tar.gz
6410960d0ddc494a95881672e1721140213d3290b2764dec35ceb419f629c2a6  guix-build-986d7fed057b/output/dist-archive/bitcoin-986d7fed057b.tar.gz
3aabb100d5a49af2fc00fbead3e4ff1166c008c2023eaa32257544c355f8bb99  guix-build-986d7fed057b/output/powerpc64-linux-gnu/SHA256SUMS.part
b45d94a09d5231a68f1300f6043b6ea3effc33fe0a177beb8f72eba73dd50191  guix-build-986d7fed057b/output/powerpc64-linux-gnu/bitcoin-986d7fed057b-powerpc64-linux-gnu-debug.tar.gz
8369f5eaaf639c874a500099f7b29a8ad5c7ca1b6ea2fa3a3d946e4464d943ec  guix-build-986d7fed057b/output/powerpc64-linux-gnu/bitcoin-986d7fed057b-powerpc64-linux-gnu.tar.gz
bd98c22bcb077c64802ac6a4fea8c125de3ad51fa059c6cc615961743764c4de  guix-build-986d7fed057b/output/powerpc64le-linux-gnu/SHA256SUMS.part
c4aa32f17d16b5ff11116887dc047fc198942be84431743b667d5e977b975e4c  guix-build-986d7fed057b/output/powerpc64le-linux-gnu/bitcoin-986d7fed057b-powerpc64le-linux-gnu-debug.tar.gz
6b30377ef2d1996131595134e7b0a2894ca60e17e4e254bec2df8fb3738ac833  guix-build-986d7fed057b/output/powerpc64le-linux-gnu/bitcoin-986d7fed057b-powerpc64le-linux-gnu.tar.gz
478fda56708f839699493a04b70833a59470d388d8227c2627a0c7ef52aee12a  guix-build-986d7fed057b/output/riscv64-linux-gnu/SHA256SUMS.part
b6fe8284ca15f9a14ce5326b30d1542a007c41ea0e4b0a7b1a81bb63f7002e89  guix-build-986d7fed057b/output/riscv64-linux-gnu/bitcoin-986d7fed057b-riscv64-linux-gnu-debug.tar.gz
a11db5ba19c21ac662279595478f7ffe85eb9867d2c56b046c4717e434816d8e  guix-build-986d7fed057b/output/riscv64-linux-gnu/bitcoin-986d7fed057b-riscv64-linux-gnu.tar.gz
698abf77725448f82310d0efd661422f39550d377edc565d6042d00a37bf798b  guix-build-986d7fed057b/output/x86_64-apple-darwin/SHA256SUMS.part
27cef1ea92865247cd0692c42228237903f58f14afc29abf0009ceb27e82e158  guix-build-986d7fed057b/output/x86_64-apple-darwin/bitcoin-986d7fed057b-x86_64-apple-darwin-unsigned.tar.gz
0ddad23cc0562d8346463f8cb6a37faf8bde2b7a8570c2a41e07748e59deb13f  guix-build-986d7fed057b/output/x86_64-apple-darwin/bitcoin-986d7fed057b-x86_64-apple-darwin-unsigned.zip
7bcd078a7eb15e439e931512421622d37cbec4395ba742f04f2594fd23624291  guix-build-986d7fed057b/output/x86_64-apple-darwin/bitcoin-986d7fed057b-x86_64-apple-darwin.tar.gz
5ac508736ecaba1e7ccbc70b2728f798d9f31e30f860af7b39dd6ac18c4de2d6  guix-build-986d7fed057b/output/x86_64-linux-gnu/SHA256SUMS.part
25e7dd48f5b3a00d3318084d572737ec380168889dc455a9f6cdd6b5b39ccfbe  guix-build-986d7fed057b/output/x86_64-linux-gnu/bitcoin-986d7fed057b-x86_64-linux-gnu-debug.tar.gz
ffb68a445586283bc874d77828cabedf0251565e8c9434ade7b62d7f5f52a4c6  guix-build-986d7fed057b/output/x86_64-linux-gnu/bitcoin-986d7fed057b-x86_64-linux-gnu.tar.gz
b7028a690cd2f3534b6506e7c12742a80ab2ea371d2ec329ad82f2eedb457747  guix-build-986d7fed057b/output/x86_64-w64-mingw32/SHA256SUMS.part
aaf07cddfe55e8988b4854463f8dfb3d16e00502ab501f6e8f2a67091b630284  guix-build-986d7fed057b/output/x86_64-w64-mingw32/bitcoin-986d7fed057b-win64-debug.zip
82ac6875462f819ff54e77a209062ca51ac4b07d85b518665b6f405864840519  guix-build-986d7fed057b/output/x86_64-w64-mingw32/bitcoin-986d7fed057b-win64-setup-unsigned.exe
cde6c04506dda70a1f0cdef3a50186ecf82a7d0551f8c266f795f8883ae82307  guix-build-986d7fed057b/output/x86_64-w64-mingw32/bitcoin-986d7fed057b-win64-unsigned.tar.gz
8a904f11110f66d741b3dae1cb6412b7fadc4f29b2d477453540dbd1729001a9  guix-build-986d7fed057b/output/x86_64-w64-mingw32/bitcoin-986d7fed057b-win64.zip
```

**Review by sedited — APPROVED** [review]
ACK 986d7fed057b995a720787cbbd21e1c41763fb83

Independently verified the sha256sum.
Also checked that the now removed patch is indeed in the [upstream](https://github.com/zeromq/libzmq/commit/6473bf4166215db1f042e10bd1bd9708f8a66347).

**Pull request merged**
