### PR TITLE
[Qt] use Qt foreach where possible

### PR DESCRIPTION
**Pull request by Diapolo**
- also use const references where appropriate

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Codereview utACK.
Next time it would recommend to split of the `const` changes and brackets/line break changes into a different commit.

**Comment by Diapolo** [comment]
@jonasschnelli I just wanted to ensure I'm using the correct style that get's applied after clang-cleanup and changed it in the same commit. I hope this is still okay for this pull :). Thanks for review.

**Comment by laanwj** [comment]
Not opposed, although I'd prefer to go straight to c++11 range-based for if we're going that route anyway - that avoids some diff noise.

**Comment by Diapolo** [comment]
@laanwj Yeah, a move to C++11 would be nice, but until there is consensus about when and how, we could perhaps merge this rather uncontroversial pull.

**Comment by laanwj** [comment]
I really want to reach consensus on C++11. I don't see the need for this intermediate step.

**Comment by laanwj** [comment]
Closing this, please don't submit any pulls that don't fix any issues anymore, we don't have time nor resources to review them.

**Comment by Diapolo** [comment]
@laanwj May I remember you that you were it, who tagged this "improvement". Also it's not my fault that time of the core devs is limited. It's also my free time, I use to create patches for Bitcoin Core and it's not very motivating at all to just hear that same phrase again. You even reviewed this and @jonasschnelli gave an ACK... why is the discussion always longer than just merging it?

**Comment by jonasschnelli** [comment]
I'm with @laanwj on this: let's wait and change it directly to a c++11.

**Comment by luke-jr** [comment]
OTOH, if we're leaning toward not moving to C++11 for years (what it now looks like the outcome may be), might as well merge this...

**Comment by laanwj** [comment]
@diapolo But why? This patch introduces an ever-small amount of risk at no gain at all. Boost's foreach works just as well as Qt's, and at least the code is verified to work that way.

I understand it is your free time too, and I'm sorry for that, but that is no argument to merge everything. Mind that this is a highly critical piece of software. We can't just merge things for the sake of being a lot of work.

> it's not very motivating at all to just hear that same phrase again

I'm only repeating that because you don't pay attention to it. Please try to contribute changes that fix reported issues, not just 'because I think the code is prettier this way'.

**Pull request closed without merging**
