### PR TITLE
CLTV IsSuperMajority() soft-fork, rebased against v0.10.2

### PR DESCRIPTION
**Pull request by petertodd**
Everything required to backport CLTV to v0.10, including the soft-fork itself.

### CODE REVIEW

**Comment by laanwj** [comment]
Somehow I cannot get travis to pass here. Even though "travis: for travis generating an extra build" is on the 0.10 branch, it still creates an extra empty test target.
@theuni any idea?

**Comment by btcdrak** [comment]
@laanwj Travis has been doing this in a lot of places randomly. That extra target is bogus and can be ignored.

**Comment by laanwj** [comment]
@btcdrak Sure, but we managed to correct that on the branch by twiddling with the `.travis.yml` file (which is why it doesn't appear in master pullreqs or the 0.11 one). But somehow it does here. And it's not random, I re-triggered it three times.

**Comment by dexX7** [comment]
Might be resolved by rebasing on top of the updated 0.10.

The last build [81320710](https://travis-ci.org/bitcoin/bitcoin/builds/81320710) also refers to a non-existing commit https://github.com/bitcoin/bitcoin/commit/0dc55a8e8992c610c84adfd364d5c88a187d779a.

**Comment by petertodd** [comment]
Rebased as suggested; tests passing now.

**Comment by dexX7** [comment]
Ah nice.

Looks good to me. I can confirm that the code for 0.10 is the same as for master and 0.11.

The softfork status via `"getblockchaininfo"` is missing in this branch (i.e. 08dbe20f7f8d8dbefb7955d4470b891ac2344ba5 + f59bc924a2af3e4dc0512eeeb5610885781f24fd) though.

**Comment by petertodd** [comment]
@dexX7 That code depends on the consensusParams stuff, which was added in v0.11.0, so I didn't bother rebasing it for v0.10.x - I expect on a small handful of miners to be using v0.10.x anyway.

**Comment by MarcoFalke** [comment]
Needs rebase due to `SCRIPT_VERIFY_LOW_S`

**Comment by petertodd** [comment]
@MarcoFalke Rebased

**Comment by CodeShark** [comment]
Tested. Looks good to me. ACK

**Comment by dcousens** [comment]
ACK

**Comment by btcdrak** [comment]
utACK

**Pull request merged**
