### PR TITLE
[Refactor] RAII of libevent stuff using unique ptrs with deleters

### PR DESCRIPTION
**Pull request by kallewoof**
This PR is the initial part of cleaning up the use of `ev*_new/ev*_free`.

The relevant, owned types are wrapped in `std::unique_ptr`s with associated deleters.

Some cases require manually releasing the pointer, such as when an `evhttp_request` is handed to `evhttp_make_request` (as its ownership is moved at that point), but otherwise things become mostly automagic.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
General concept ACK on a RAII approach (C++ wrapper) for libevent.
I think we should avoid `boost::noncopyable` and instead use C++11's `MyClass& operator=(const MyClass&) = delete;` approach.

**Comment by kallewoof** [comment]
@jonasschnelli Fixed.

**Comment by laanwj** [comment]
ACK on making things RAII. Thanks.

I'm not so sure about wrapping the entire interface, though. I'm not sure about others but I'd prefer something thinner.

For example  `evhttp_set_max_headers_size` -> `setMaxHeadersSize`. This makes it fractionally harder for someone that has learned the libevent APIs to understand the code because the functions are named differently.

**Comment by kallewoof** [comment]
@laanwj It felt sensible to make the underlying `ev*` structs private but maybe my intuition was off on that. I'm not entirely convinced that `evhttp_set_max_headers_size` -> `setMaxHeadersSize` is a problem, but if you think it is, it may be better to un-private'ify the structs. That would remove the need for friends as well.

**Comment by laanwj** [comment]
It's not a *problem* but it's one of the little things that I've learned in years developing in open source. If a project makes use of some library which you already know, it's easier to get into it if it is simply using the "lexicon" of that library instead of wrapping everything in custom-named calls.

You could work around this by making the wrapping functions the same as the evhttp calls, e.g. don't do the camel-case thing. But yes I'd prefer not making the inner objects private - make it behave more like a "smart pointer".

Another (less-LoC) alternative to all of this is to define a std::unique_ptr with our own cleanup hook. I've done a similar thing recently in `paymentserver.cpp`.
```
struct X509StoreDeleter {
      void operator()(X509_STORE* b) {
          X509_STORE_free(b);
      }
};
std::unique_ptr<X509_STORE, X509StoreDeleter> certStore;
```

**Comment by kallewoof** [comment]
There is also a slight issue with the `evhttp_request` which needs to *not* be freed if a call to `evhttp_make_request` has been made. By exposing the internal `evhttp_request`, it's not possible to determine which is the case.

**Comment by kallewoof** [comment]
That (names being same) makes sense. The `unique_ptr` approach looks very nice, but unsure if it can address the above issue adequately.

**Comment by laanwj** [comment]
> There is also a slight issue with the evhttp_request which needs to not be freed if a call to evhttp_make_request has been made. By exposing the internal evhttp_request, it's not possible to determine which is the case.

Couldn't, in that case, the calling code could just `.release()` the pointer? No need to build that intelligence into the pointer object.

**Comment by kallewoof** [comment]
You mean, explicitly tell the wrapper it no longer owns the object whenever you do `evhttp_make_request`? I suppose that is doable. I would have loved to not have to risk developers forgetting to do so though.

**Comment by laanwj** [comment]
True, though hiding behaviour in the wrapper instead of explicit transfer
of ownership could also cause confusion, as there is a certain expectation
from the API.

**Comment by kallewoof** [comment]
Yeah, that makes sense. Thanks for the feedback, will fix!

**Comment by kallewoof** [comment]
@laanwj I decided to go with the unique pointer + deleter approach. It became awfully verbose, so I did some macroing.

**Comment by laanwj** [comment]
Nice!
Concept ACK. I think the use of macros is okay in this case, as indeed they all follow the same pattern.

**Review by dcousens — APPROVED** [review]
concept and light utACK

**Comment by laanwj** [comment]
I tried building this and it fails:
```
$ make
Making all in src
make[1]: Entering directory '/store2/build/bitcoin/bitcoin/src'
make[2]: Entering directory '/store2/build/bitcoin/bitcoin/src'
...
  CXX      test/test_test_bitcoin-raii_event_tests.o
/.../bitcoin/src/test/raii_event_tests.cpp:5:10: fatal error: 'event2/event.h' file not found
#include <event2/event.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
```
Perhaps the include directory for libevent headers is not specified for the tests in the Makefile.am?

**Comment by kallewoof** [comment]
@laanwj Weird. What does `V=1 make` give as output?

**Comment by laanwj** [comment]
Sure:
```
/usr/bin/ccache /opt/clang40/bin/clang++ -std=c++11 -DHAVE_CONFIG_H -I. -I.../bitcoin/src -I../src/config  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I. -I./obj  -pthread -I/usr/include -I.../bitcoin/src/leveldb/include -I.../bitcoin/src/leveldb/helpers/memenv   -I.../bitcoin/src/secp256k1/include -I.../bitcoin/src/univalue/include -I./test/ -DBOOST_TEST_DYN_LINK -Qunused-arguments -ggdb -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -Wstack-protector -fstack-protector-all -fPIE -g -O2 -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -Wno-self-assign -Wno-unused-local-typedef -Wno-deprecated-register -MT test/test_test_bitcoin-raii_event_tests.o -MD -MP -MF test/.deps/test_test_bitcoin-raii_event_tests.Tpo -c -o test/test_test_bitcoin-raii_event_tests.o `test -f 'test/raii_event_tests.cpp' || echo '.../bitcoin/src/'`test/raii_event_tests.cpp
.../bitcoin/src/test/raii_event_tests.cpp:5:10: fatal error: 'event2/event.h' file not found
#include <event2/event.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
```
My configure script looks like:
```
#!/bin/bash
CLANGPATH=/opt/clang40
$1/configure --with-incompatible-bdb \
    --prefix=/tmp/bitcoin \
    CC="${CLANGPATH}/bin/clang " CXX="${CLANGPATH}/bin/clang++" \
    OBJCXX="${CLANGPATH}/bin/clang++" \
    CPPFLAGS="-ggdb" \
    EVENT_CFLAGS="-I/opt/libevent/include" \
    EVENT_LIBS="-L/opt/libevent/lib -levent" \
    EVENT_PTHREADS_CFLAGS="-I/opt/libevent/include" \
    EVENT_PTHREADS_LIBS="-L/opt/libevent/lib -levent_pthreads" \
```

**Comment by kallewoof** [comment]
On my system, I have event2 symlinked inside `/usr/local/include`, which means I don't have to explicitly include it in the g++ call. Adding $(EVENT_CFLAGS) to `test_test_bitcoin_CPPFLAGS` added explicit references so this should fix it on your end.

**Comment by laanwj** [comment]
Yep, that solved it, thanks! utACK 05a55a6

**Review by laanwj — APPROVED** [review]

**Pull request merged**
