### PR TITLE
Add vcpkg custom port files

### PR DESCRIPTION
**Pull request by sipsorcery**
The purpose is to allow control of the vcpkg package versions installed by the appveyor CI job. The main vcpkg port files change regularly and can potentially break the Bitcoin Core build.

- Copies the current vcpkg port files required for Bitcoin Core dependencies.
- Updates the appveyor CI job to use custom port files.

P.S. as discussed in #17976.

### CODE REVIEW

**Comment by sipsorcery** [comment]
I think the linter will need to be turned off for `build_msvc\vcpkg-ports`. Otherwise it will be a never ending task keeping the port files in sync with the main vcpkg repo.

Anyone know if I can and if so where I add a linter exclusion?

**Comment by laanwj** [comment]
Concept ACK, but adding 335 files to the repository is a bit too much, IMO. I'm not sure it is good to add that to the maintenance bottleneck. Should we create a new repo for this?

**Comment by sipsorcery** [comment]
+1 for a separate repo.

**Comment by fanquake** [comment]
> Concept ACK, but adding 335 files to the repository is a bit too much, IMO. I'm not sure it is good to add that to the maintenance bottleneck. Should we create a new repo for this?

+1 for a separate repo. I'd rather remove `build_msvc/` and `appveyor.yml` from this repository then have to add ~300 files just to try and pin some dependencies.

**Comment by sipsorcery** [comment]
> I'd rather remove build_msvc/ and appveyor.yml from this repository then have to add ~300 files just to try and pin some dependencies.

Only the port files need to be put in a separate repo. The existing `build_msvc` directory can stay as is. 

I'll create a repo on my account to demonstrate how it works. It can be switched over to a Bitcoin Core repo afterwards if that's deemed appropriate.

**Pull request closed without merging**
