### PR TITLE
Remove -feefilter option

### PR DESCRIPTION
**Pull request by AdityaNG**
Removed the `-feefilter` option from `src/net_processing.cpp`.  #21545 
To make sure everything works, I ran `make check` and then ran `test_runner.py` with [`p2p_feefilter.py`](https://github.com/bitcoin/bitcoin/blob/master/test/functional/p2p_feefilter.py)

```bash
$ test/functional/test_runner.py p2p_feefilter.py
Temporary test directory at /tmp/test_runner_₿_🏃_20210403_190347
Running Unit Tests for Test Framework Modules
..........
----------------------------------------------------------------------
Ran 10 tests in 0.633s

OK
Remaining jobs: [p2p_feefilter.py]
1/1 - p2p_feefilter.py passed, Duration: 15 s

TEST             | STATUS    | DURATION

p2p_feefilter.py | ✓ Passed  | 15 s

ALL              | ✓ Passed  | 15 s (accumulated) 
Runtime: 15 s
```

Regarding splitting up the `feefilter` logic and moving it to a seperate function for better readability, the `g_filter_rounder.round()` function is not thread safe and is currently inside a `LOCK(cs_main);`  called at the begining of [`PeerManagerImpl::SendMessages(CNode* pto)`](https://github.com/AdityaNG/bitcoin/blob/e08f3193b543017702d000c2263bccbefa981c14/src/net_processing.cpp#L4267). Didn't make any changes for this, how would I proceed for this?

### CODE REVIEW

**Comment by glozow** [comment]
There are a couple other places you'll need to remove `-feefilter` from as well, e.g. init.cpp.

**Comment by ccdle12** [comment]
In terms of extracting the logic into a separate function, one option you can use is an assert to make sure `cs_main` is held before entering the main function logic e.g. `AssertLockHeld(cs_main)` like [used here](https://github.com/bitcoin/bitcoin/blob/master/src/net_processing.cpp#L3932).

**Comment by OxideDevX** [comment]
Thank you. bro.

вт, 6 апр. 2021 г. в 21:26, Christopher Coverdale ***@***.***

**Comment by AdityaNG** [comment]
@ccdle12 understood the usage of `AssertLockHeld(cs_main)`. 
In #21509 @jnewbery and @MarcoFalke talk about 

1. removing the `-feefilter` option ( as @glozow mentioned I have looked through all usages of 'feefilter')
2. factoring out the feefilter logic out into its own function (will do so with `AssertLockHeld(cs_main)` ).

From what I understand about the goal of #21545 , was to remove the feefilter check from the message handler loop in `net_processing.cpp`. Wouldn't removing it from the `init.cpp` be problematic as it would entirely remove the option? Or is removing feefilter completely the goal? I would like some clarity on this.

### Feefilter usage

Looked around and pulled up files with refrences to feefilter and understood the context of the refrence which was a good exercise that got me familiar with the codebase.

1. init.cpp - `argsman.AddArg("-feefilter", ...)`
2. net_processing.cpp
3. net.cpp and net.h
```cpp
if (m_tx_relay != nullptr) {
    stats.minFeeFilter = m_tx_relay->minFeeFilter;
} else {
    stats.minFeeFilter = 0;
}
```
4. protocol.cpp and protocol.h
```cpp
const char *FEEFILTER="feefilter";
...
const static std::string allNetMessageTypes[] = {
    ...
    NetMsgType::FEEFILTER,
};
```
5. validation.h `static const bool DEFAULT_FEEFILTER = true;`
6. version.h `static const int FEEFILTER_VERSION = 70013;`
7. fees.cpp and fees.h `explicit FeeFilterRounder(const CFeeRate& minIncrementalFee);` (the non-thread safe round function)
8. net.cpp
```cpp
RPCResult::Type::NUM, "minfeefilter", "The minimum fee rate for transactions this peer accepts"
...
static RPCHelpMan getpeerinfo() {
    ...
    obj.pushKV("minfeefilter", ValueFromAmount(stats.minFeeFilter));
}
```
9. policy_fee_tests.cpp `FeeFilterRounder fee_rounder{CFeeRate{1000}};`
10. fees.cpp `FeeFilterRounder fee_filter_rounder{minimal_incremental_fee};`
11. process_message.cpp `FUZZ_TARGET_MSG(feefilter);`
12. Multiple python tests in test/functional
    a. p2p_feefilter.py
    b. p2p_ibd_txrelay.py
    c. p2p_leak.py
    d. rpc_net.py
    e. test_runner.py
    f. messages.py
    g. p2p.py

**Comment by jnewbery** [comment]
> is removing feefilter completely the goal

Yes. The `-feefilter` config option is not used anywhere else, so it should be removed from the init code.

> Looked around and pulled up files with refrences to feefilter and understood the context of the refrence which was a good exercise that got me familiar with the codebase...

All of these instances of `minFeeFilter`, `FEEFILTER, `FEEFILTER_VERSION`, etc are separate from the `-feefilter` option, which is used to control whether we'll ever send `feefilter` messages to our peer.

**Comment by jnewbery** [comment]
Please also add rationale to the commit log. Why is it ok to remove -feefilter?

**Comment by MarcoFalke** [comment]
Closing for now due to inactivity. Let me know when you want to work on this again.

**Pull request closed without merging**
