### PR TITLE
script: Make LXC container size suitable for gitian builds

### PR DESCRIPTION
**Pull request by hebasto**
This change prevents "No space left on device" error.

See:
- https://github.com/bitcoin/bitcoin/pull/21036#issuecomment-774771873
- https://github.com/bitcoin/bitcoin/pull/21036#issuecomment-775031315

### CODE REVIEW

**Comment by hebasto** [comment]
cc @laanwj

**Comment by laanwj** [comment]
Is this only relevant to LXC?

**Comment by hebasto** [comment]
> Is this only relevant to LXC? KVM uses sized images too, after all.

Right. Did not test KVM-based builds. Will do.
And this is not relevant to Docker.

**Comment by hebasto** [comment]
@laanwj 
> Is this only relevant to LXC? KVM uses sized images too, after all.

See #21140.

**Comment by jonasschnelli** [comment]
ACK 166266a372fed2b1f73053084a923fab7edc77f4 - I had to add this manually to my nighly build base image

**Pull request merged**
