### PR TITLE
build: tighter Univalue integration, remove `--with-system-univalue`

### PR DESCRIPTION
**Pull request by fanquake**
This PR more tightly integrates building Univalue into our build system. This follows the same approach we use for [LevelDB](https://github.com/bitcoin-core/leveldb/), ([`Makefile.leveldb.include`](https://github.com/bitcoin/bitcoin/blob/master/src/Makefile.leveldb.include)), and [CRC32C](https://github.com/bitcoin-core/crc32c) ([`Makefile.crc32c.include`](https://github.com/bitcoin/bitcoin/blob/master/src/Makefile.crc32c.include)), and will be the same approach we use for [minisketch](https://github.com/sipa/minisketch); see #23114.

This approach yields a number of benefits, including:
* Faster configuration due to one less subconfigure being run during `./configure` i.e 22s with this PR vs 26s
* Faster autoconf i.e 13s with this PR vs 17s
* Improved caching
* No more issues with compiler flags i.e https://github.com/bitcoin/bitcoin/pull/12467
* More direct control means we can build exactly the objects we want

There might be one argument against making this change, which is that builders should have the option to use "proper shared/system libraries". However, I think that falls down for a few reasons. The first being that we already don't support building with a number of system libraries (secp256k1, leveldb, crc32c); some for good reason. Univalue is really the odd one out at the moment. 

Note that the only fork of Core I'm aware of, that actively patches in support for using system libs, also explicitly marks them as ["DANGEROUS"](https://github.com/bitcoinknots/bitcoin/blob/a886811721ce66eb586871706b3f5dd27518ac3e/configure.ac#L1430) and ["NOT SUPPORTED"](https://github.com/bitcoinknots/bitcoin/blob/a886811721ce66eb586871706b3f5dd27518ac3e/configure.ac#L1312). So it would seem they exist more to satisfy a distro requirement, as opposed to something that anyone should, or would actually use in practice.

PRs like #22412 highlight the "issue" with us operating with our own Univalue fork, where we actively fix bugs, and make improvements, when upstream (https://github.com/jgarzik/univalue) may not be taking those improvements, and by all accounts, is not currently actively maintained. Bitcoin Core should not be hamstrung into not being able to fix bugs in a library, and/or have to litter our source with "workarounds", i.e #22412, for bugs we've already fixed, based on the fact that an upstream project is not actively being maintained. Allowing builders to use system libs is really only exacerbating this problem, with little benefit to our project. Bitcoin Core is not quite like your average piece of distro packaged software.

There is the potential for us to give the same treatment to libsecp256k1, however it seems doing that is currently less straightforward.

### CODE REVIEW

**Comment by jnewbery** [comment]
Strong concept ACK!

As well as the technical benefits listed in the PR description, a strong reason to go in this direction is to lower our maintenance and testing burden. Being able to build with a system univalue library really doesn't provide any benefit to users, but results in issues like #22412 which suck up reviewer and maintainer time. Maintaining support for different versions of univalue also expands the matrix of different build/configuration combinations which we really should (but don't) test if we claim support.

**Comment by ryanofsky** [comment]
I know that the forking process already began before this PR, and I think that forking in open source can be very good. But I also think that when you fork, it is better practically and ethically to _rename the fork_. In the case of a library, this doesn't need to involve renaming functions and classes in the library, but the forked library should at least have different library filenames (`libunivalue.a`) and include filenames (in this case just `univalue.h`) so it is not a nightmare if downstream projects have code requiring both libraries as dependencies. Also it would be good to rename the source directory [`src/univalue/`](https://github.com/bitcoin/bitcoin/tree/master/src/univalue) and update the readme documentation [`src/univalue/README.md`](https://github.com/bitcoin/bitcoin/blob/master/src/univalue/README.md) to explicity say the library has been forked, the forks are incompatible, problems and discussions about the fork should be directed at the new issue tracker / mailing list / irc channel / whatever, not at the original project.

The idea is that by renaming a directory and two files, you can make things less ambiguous, confusing, and potentially painful for downstream developers, while also being kinder to the author of the original library and letting the name he chose for his project refer unambiguously to his own project instead of a collection of forks.

As for what name to substitute, for an internal fork it could be nonsense like _xyzlkq_ for all it matters, or something like _unibtc_ to be coherent, or something ike _jsonvalue_ to be descriptive, or something like _univalue--_ to be cheeky, whatever.

Please ignore this suggestion if it's too cumbersome. Just wanted to describe a possible way to make forking less confusing and contentious.

**Comment by Rspigler** [comment]
Concept ACK.  More control over our build is better.

**Comment by practicalswift** [comment]
Concept ACK for the reasons @jnewbery gave in https://github.com/bitcoin/bitcoin/pull/22646#issuecomment-894142812

**Comment by laanwj** [comment]
Concept ACK. 

> Please ignore this suggestion if it's too cumbersome. Just wanted to de scribe a possible way to make forking less confusing and contentious.

Not sure about this. As said in the OP, we have done a similar thing for the `leveldb` and `crc32c` libraries with regard to maintaining our own fork without renaming them. The subsequent repositories have a mention in their github description that they are not the upstream project, this may be enough. To be clear, it is **not** the intent that other projects use our fork of the library. This might be signaled by giving them a new name.

**Comment by MarcoFalke** [comment]
Maybe the GitHub projects could be renamed to `bitcoin-core/${upstream-name}-subtree` to clarify this is a repo only used for bitcoin-core internal subtrees? I agree that renaming the project name itself (in the code) is too much and might even send the wrong impression that this is maintained for someone other than bitcoin-core itself.

**Comment by luke-jr** [comment]
Concept NACK.

UniValue is not comparable to secp256k1 and LevelDB - the latter are used in consensus-critical code, and so it's important to be careful about which bugs get fixed in them. Using the system UniValue isn't and shouldn't not be dangerous nor unsupported.

There is basically no reason to embed a copy of UniValue at all. If upstream support is lacking, we should just release our fork as a proper fork of the library or not require things upstream has decided not to do. The embedded copy should ideally be removed, and only ever build against the system install.

Other disagree with removing the embedded copy, however. Keeping support for both system *and* an embedded copy was a reasonable compromise. If we're not going to support both, however, the direction to go is removing the embedded copy, not dropping support for the correct configuration (system library).

**Comment by MarcoFalke** [comment]
Concept ACK.

Surely, in a world with enough maintenance resources, univalue could be released and integrated as a separate library. As there are evidently neither resources to maintain it as a separate library, nor maintain the integration of an external univalue, this seems like a good move.

**Comment by luke-jr** [comment]
It's literally less effort to maintain it properly.

All the work to integrate it is already done. The bugs recently introduced, have also been fixed aside from gatekeepers blocking the fixes from being merged.

**Comment by laanwj** [comment]
> Maybe the GitHub projects could be renamed to bitcoin-core/${upstream-name}-subtree to clarify this is a repo only used for bitcoin-core internal subtrees?

Sure, sounds good to me.

**Comment by jnewbery** [comment]
https://github.com/bitcoin-core/univalue-subtree/pull/19 is merged. Does this need rebasing?

**Comment by fanquake** [comment]
> bitcoin-core/univalue-subtree#19 is merged. Does this need rebasing?

I've rebased on master and dropped the cherry-picks in favour of a subtree update. I've also fixed up the integration commit so that `make dist` is working properly, and made some other minor changes. Also updated the PR description.

**Comment by MarcoFalke** [comment]
The changes without the last commit will break building with git-bisect? If yes, the changes should probably be squashed into the previous merge commit (`git reset --soft HEAD~ && git commit --amend`).

**Comment by fanquake** [comment]
Pushed a fix for the CI failures. The `fail*.json` sources were missing from the dist tarball, which was causing `unitester` to fail.

> The changes without the last commit will break building with git-bisect?

They shouldn't do. After the subtree pull, the univalue is still buildable using autotools. We atomically swap from building univalue using autotools, to integrating univalue into our build in the last commit.

**Comment by fanquake** [comment]
Similar to what we are doing with the [minisketch integration](https://github.com/bitcoin/bitcoin/pull/23114/files#diff-d4537436596f04e21cc7507f185f355d2f9bff213eca7969382faff5c3336e57R31), pushed a change to skip building the univalue tests if fuzzing is enabled.

**Comment by fanquake** [comment]
At least one issue to fix from a [sanitizer CI](https://github.com/bitcoin/bitcoin/pull/22646/checks?check_run_id=3798223718):
```bash
********* Start testing of URITests *********
Config: Using QtTest library 5.15.2, Qt 5.15.2 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 10.3.0), ubuntu 21.04
PASS   : URITests::initTestCase()
PASS   : URITests::uriTests()
PASS   : URITests::cleanupTestCase()
Totals: 3 passed, 0 failed, 0 skipped, 0 blacklisted, 1ms
********* Finished testing of URITests *********
********* Start testing of RPCNestedTests *********
Config: Using QtTest library 5.15.2, Qt 5.15.2 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 10.3.0), ubuntu 21.04
PASS   : RPCNestedTests::initTestCase()
univalue/lib/univalue_read.cpp:292:13: runtime error: implicit conversion from type 'int' of value -5 (32-bit, signed) to type 'unsigned int' changed the value to 4294967291 (32-bit, unsigned)
    #0 0x55978052c2bf in UniValue::read(char const*, unsigned long) univalue/lib/univalue_read.cpp:292:13
    #1 0x55977fcabbbd in UniValue::read(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ./univalue/include/univalue.h:153:16
    #2 0x5597804a66c6 in ParseNonRFCJSONValue(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) rpc/client.cpp:234:15
    #3 0x5597804a6cc8 in RPCConvertValues(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) rpc/client.cpp:252:30
    #4 0x55977f0920c0 in RPCConsole::RPCParseCommandLine(interfaces::Node*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, WalletModel const*) qt/rpcconsole.cpp:328:47
    #5 0x55977ee8a3dc in RPCConsole::RPCExecuteCommandLine(interfaces::Node&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, WalletModel const*) ./qt/rpcconsole.h:48:16
    #6 0x55977ee8a3dc in RPCNestedTests::rpcNestedTests() qt/test/rpcnestedtests.cpp:62:5
    #7 0x55977ef214f2 in RPCNestedTests::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) qt/test/moc_rpcnestedtests.cpp:72:21
    #8 0x7f83e3593d9a in QMetaMethod::invoke(QObject*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) const (/lib/x86_64-linux-gnu/libQt5Core.so.5+0x2c3d9a)
    #9 0x7f83e3294552  (/lib/x86_64-linux-gnu/libQt5Test.so.5+0x1c552)
    #10 0x7f83e3294ffb  (/lib/x86_64-linux-gnu/libQt5Test.so.5+0x1cffb)
    #11 0x7f83e32955e3  (/lib/x86_64-linux-gnu/libQt5Test.so.5+0x1d5e3)
    #12 0x7f83e3295b33 in QTest::qRun() (/lib/x86_64-linux-gnu/libQt5Test.so.5+0x1db33)
    #13 0x7f83e3295f2f in QTest::qExec(QObject*, int, char**) (/lib/x86_64-linux-gnu/libQt5Test.so.5+0x1df2f)
    #14 0x55977eea9a74 in main qt/test/test_main.cpp:92:9
    #15 0x7f83e1a32564 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28564)
    #16 0x55977edc350d in _start (/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/src/qt/test/test_bitcoin-qt+0x18ba50d)

SUMMARY: UndefinedBehaviorSanitizer: implicit-integer-sign-change univalue/lib/univalue_read.cpp:292:13 in 
FAIL qt/test/test_bitcoin-qt (exit status: 1)
```

**Comment by MarcoFalke** [comment]
You can fix the CI error with this diff:

```diff
diff --git a/src/univalue/lib/univalue_read.cpp b/src/univalue/lib/univalue_read.cpp
index f8a5d4d76f..d68d263858 100644
--- a/src/univalue/lib/univalue_read.cpp
+++ b/src/univalue/lib/univalue_read.cpp
@@ -244,7 +244,7 @@ enum jtokentype getJsonToken(std::string& tokenVal, unsigned int& consumed,
     }
 }
 
-enum expect_bits {
+enum expect_bits : unsigned {
     EXP_OBJ_NAME = (1U << 0),
     EXP_COLON = (1U << 1),
     EXP_ARR_VALUE = (1U << 2),
```

See also https://github.com/bitcoin/bitcoin/pull/22232/files#diff-da9625bc8e6928c0ec3239921e739c32b9d0abdfbca9773c550a3cdd818230b8 which did the same thing for another enum.

**Comment by MarcoFalke** [comment]
Aw sorry, looks like I missed some more:

```diff
diff --git a/src/univalue/lib/univalue_read.cpp b/src/univalue/lib/univalue_read.cpp
index d68d263858..be39bfe57a 100644
--- a/src/univalue/lib/univalue_read.cpp
+++ b/src/univalue/lib/univalue_read.cpp
@@ -227,7 +227,7 @@ enum jtokentype getJsonToken(std::string& tokenVal, unsigned int& consumed,
             }
 
             else {
-                writer.push_back(*raw);
+                writer.push_back(static_cast<unsigned char>(*raw));
                 raw++;
             }
         }
diff --git a/src/univalue/lib/univalue_write.cpp b/src/univalue/lib/univalue_write.cpp
index db039fcb00..3a2c580c7f 100644
--- a/src/univalue/lib/univalue_write.cpp
+++ b/src/univalue/lib/univalue_write.cpp
@@ -13,13 +13,13 @@ static std::string json_escape(const std::string& inS)
     outS.reserve(inS.size() * 2);
 
     for (unsigned int i = 0; i < inS.size(); i++) {
-        unsigned char ch = inS[i];
+        unsigned char ch = static_cast<unsigned char>(inS[i]);
         const char *escStr = escapes[ch];
 
         if (escStr)
             outS += escStr;
         else
-            outS += ch;
+            outS += static_cast<char>(ch);
     }
 
     return outS;

**Comment by MarcoFalke** [comment]
all green now :green_apple: :green_book:

**Review by theuni — APPROVED** [review]
ACK 0f95247246344510c9a51810c14c633abb382e95. Thanks fanquake for keeping this going.

> There is the potential for us to give the same treatment to libsecp256k1, however it seems doing that is currently less straightforward.

After some discussion in #secp256k1, this probably isn't going to happen. It would require us to essentially copy/paste secp256k1's configure since it deals with c as opposed to c++. I proposed wrapping secp256k1 in a .cpp, but that idea was NACK'd quickly by the upstream maintainers. So I think that subconfigure will probably stay as-is.

**Comment by fanquake** [comment]
I'm going to go ahead and merge this. In regards to the comments earlier in this PR, we've done some work to make it more clear that our fork is an internal (for our use only) subtree, by renaming the repository, and I've also opened a PR to adjust the README to mention that our API has diverged from upstream: https://github.com/bitcoin-core/univalue-subtree/pull/30.

> After some discussion in #secp256k1, this probably isn't going to happen.

That is slightly disappointing, but at least now we'll be down to only a single extra configure invocation.

**Comment by jnewbery** [comment]
post-merge ACK 0f95247246344510c9a51810c14c633abb382e95

I've tested the changes and confirmed that the subconfigure isn't run (and that it's slightly faster). I'm not an autotools expert so can only lightly review the diff, but it all looks reasonable to me.

**Comment by hebasto** [comment]
This PR breaks builds with depends for `HOST=x86_64-w64-mingw32 DEBUG=1` due to massive errors like that:
```
/usr/bin/x86_64-w64-mingw32-ld: ./.libs/libunivalue.a(libunivalue_la-univalue.o):univalue.cpp:(.text+0x890): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: ./.libs/libunivalue.a(libunivalue_la-univalue.o):univalue.cpp:(.text+0x8b0): undefined reference to `__imp_pthread_mutex_unlock'
```

during linking `univalue/test/object.exe`, `univalue/test/unitester.exe` and `univalue/test/no_nul.exe`.

**Comment by fanquake** [comment]
> This PR breaks builds with depends for HOST=x86_64-w64-mingw32 DEBUG=1 due to massive errors like that:

This is the same as #19772.

**Comment by hebasto** [comment]
> > This PR breaks builds with depends for HOST=x86_64-w64-mingw32 DEBUG=1 due to massive errors like that:
> 
> This is the same as #19772.

The fix has been suggested on #23612.

**Pull request merged**
