### PR TITLE
doc: Small release notes fixups in the list of pulls

### PR DESCRIPTION
**Pull request by maflcko**
* Remove a pull which I merged, but was later reverted
* Remove a pull that was already merged for 0.13
* Remove myself as author from one pull

### CODE REVIEW

**Comment by sipa** [comment]
utACK

**Comment by fanquake** [comment]
utACK fa230fd

**Comment by paveljanik** [comment]
utACK fa230fd

**Comment by laanwj** [comment]
> Remove a pull that was already merged for 0.13

Ah yes looks like the `Github-Pull:` metadata was missing on the backport there, good catch.

**Pull request merged**
