### PR TITLE
wallet: Translate all initErrors in CreateWalletFromFile

### PR DESCRIPTION
**Pull request by maflcko**
The translations are going to close in three days (#15940), so I am submitting this as a standalone pull request.

Those changes are part of a bugfix #16661, which includes a test. The first change (the refactor) is required, the second commit is not. I am happy to drop it, if needed.

### CODE REVIEW

**Review by hebasto — COMMENTED** [review]
Concept ACK. Will review in details tonight.

**Review by hebasto — APPROVED** [review]
ACK fa61365a1368f9970fa22fb96f89f4ecc08e69f0, I have tested the code on Linux Mint 19.2.

**Comment by laanwj** [comment]
utACK fa61365a1368f9970fa22fb96f89f4ecc08e69f0

**Comment by promag** [comment]
ACK fa61365a1368f9970fa22fb96f89f4ecc08e69f0.

**Pull request merged**
