### PR TITLE
Fix pre-push-hook regexes

### PR DESCRIPTION
**Pull request by TheBlueMatt**
Seems I was very out of it and wrote some backwards regexes. Shouldnt actually matter at all, but might as well fix them.

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
Oh, and gotta whitelist two commits now that Pieter revoked his key.

**Comment by laanwj** [comment]
utACK

**Comment by jgarzik** [comment]
ut ACK

**Comment by TheBlueMatt** [comment]
Added yet another commit which adds Pieter's new PGP key. The commit is signed by one of my keys, and the PGP key will be signed later this evening (though it is already signed by Greg).

**Pull request merged**
