### PR TITLE
Add script tests with actual signatures

### PR DESCRIPTION
**Pull request by sipa**
Change the script_valid/script_invalid rules to use actually valid transactions, and add some simple tests with OP_CHECKSIG, and various verification flags.

### CODE REVIEW

**Comment by shea256** [comment]
@petertodd @sipa Any idea if and when OP_CHECKLOCKTIMEVERIFY is going to be integrated? This would be a godsend for a project I'm working on.

**Comment by petertodd** [comment]
@shea256 Not really the right place for that question, but anyway, BIP66 needs to get adopted first: http://bitcoin.sipa.be/ver-2k.png http://bitcoin.sipa.be/ver-ever.png

All the major pools have upgraded; what's left is <5% pools like slush.

**Comment by shea256** [comment]
OK thank you Peter.

I just looked through all the issues and this was the only one I saw that referenced CLTV. For the future, where should I direct my questions about this?

**Comment by laanwj** [comment]
The development mailing list is the place for discussion of network-wide issues

**Comment by shea256** [comment]
Perfect, thank you. Please excuse my posting here, I will use that for the future.

**Pull request merged**
