### PR TITLE
 fuzz: Create a block template in tx_pool targets 

### PR DESCRIPTION
**Pull request by maflcko**
Relatively simple check to ensure a block can always be created from the mempool

### CODE REVIEW

**Comment by practicalswift** [comment]
Concept ACK

Touches only `src/test/fuzz/`

**Comment by MarcoFalke** [comment]
Looks like ci fails due to:

```
policy/feerate.cpp:26:34: runtime error: signed integer overflow: 1887171891083620 * 5555 cannot be represented in type 'long'
    #0 0x560eb0295c97 in CFeeRate::GetFee(unsigned long) const policy/feerate.cpp:26:34
    #1 0x560eafb6409b in BlockAssembler::addPackageTxs(int&, int&) miner.cpp:378:43
    #2 0x560eafb60c86 in BlockAssembler::CreateNewBlock(CScript const&) miner.cpp:150:5
    #3 0x560eafa21cae in (anonymous namespace)::Finish(FuzzedDataProvider&, (anonymous namespace)::MockedTxPool&, CChainState&) test/fuzz/tx_pool.cpp:89:41
    #4 0x560eafa1e237 in (anonymous namespace)::tx_pool_standard_fuzz_target(Span<unsigned char const>) test/fuzz/tx_pool.cpp:272:5
    
...

SUMMARY: UndefinedBehaviorSanitizer: signed-integer-overflow policy/feerate.cpp:26:34 in

**Comment by MarcoFalke** [comment]
(ci now green)

**Comment by adamjonas** [comment]
Tested fa03232 with DEBUG=1 and observed some nice coverage increases.

My setup is still showing the CI's UB error both in faf3e9d and fa03232, but that just might be due to my own lack of understanding or a compile issue on my part.

**Comment by MarcoFalke** [comment]
squashed the commits. bisecting should now work again.

**Comment by practicalswift** [comment]
Tested ACK fa03d0acd6bd8bb6d3d5227512f042ff537ad993

As expected the coverage achieved by the `tx_pool` fuzzing harness is dramatically improved with this patch applied.

Nice work!

**Pull request merged**
