### PR TITLE
ci: Add Appveyor CI

### LINKED ISSUE #12613: [CI] Adding MSVC build to CI check with Appveyor
Credit to @sipsorcery for his hard work on making bitcoin compile in Visual Studio.

On top of this, he managed to integrate Visual Studio to integration server AppVeyor. (Travis does not support Windows for now as far as I know)

You can see it in action here: https://ci.appveyor.com/project/sipsorcery/bitcoin this is done on top of [this PR](https://github.com/bitcoin/bitcoin/pull/11526).

He shared the following config file for the CI:

```
version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2017
configuration: Release
platform: x64
environment:
  EMAIL: aaron@sipsorcery.com
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  DUMMY1: dummy
cache: C:\Tools\vcpkg\installed
before_build:
- ps: >-
    dir c:\tools\vcpkg

    dir c:\tools\vcpkg\installed


    vcpkg install boost:x64-windows-static

    vcpkg install libevent:x64-windows-static

    vcpkg install openssl:x64-windows-static

    vcpkg install zeromq:x64-windows-static

    vcpkg install berkeleydb:x64-windows-static

    vcpkg install secp256k1:x64-windows-static

    vcpkg install leveldb:x64-windows-static


    git pull origin pull/11526/head
     Invoke-WebRequest -Uri https://gist.githubusercontent.com/sipsorcery/0ce4b529ebd3bda784ad71c5702cae88/raw/6732cef26554fd016a154ed852f5dbac8fbf4199/bitcoin-config.h -OutFile src\config\bitcoin-config.h
build:
  project: build_msvc\bitcoin.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: build_msvc\x64\Release\*.exe
  name: Executables
```

Note that the download of `bitcoin-config.h` will likely go away and be part of the build.

### PR DESCRIPTION
**Pull request by ken2812221**
Introduce Appveyor CI for MSVC. This would require the owner adding appveyor to this repo. Also fix some MSVC incompatible code.

This `appveyor.yml` file is modified from @sipsorcery and @NicolasDorier 's code in #12613.

Appveyor CI result: https://ci.appveyor.com/project/ken2812221/bitcoin/build/1.0.151

### CODE REVIEW

**Comment by practicalswift** [comment]
Concept ACK

More testing is better.

FWIW, it seems like a few tests are missing from `test_bitcoin.vcxproj` – is that intentional?

```
$ for FILE in $(git ls-files -- "*_tests.cpp"); do FILE_BASENAME=$(basename ${FILE}); grep -q ${FILE_BASENAME} build_msvc/test_bitcoin/test_bitcoin.vcxproj || echo "* ${FILE_BASENAME} missing in test_bitcoin.vcxproj"; done
* descriptor_tests.cpp missing in test_bitcoin.vcxproj
* key_io_tests.cpp missing in test_bitcoin.vcxproj
* merkleblock_tests.cpp missing in test_bitcoin.vcxproj
* txvalidation_tests.cpp missing in test_bitcoin.vcxproj
```

**Comment by ken2812221** [comment]
@practicalswift I'm not sure if it is intentional. Maybe @sipsorcery forgot to add them. I'll add those files after the test pass.

**Comment by NicolasDorier** [comment]
btw, msbuild support wildcard replacing all `..\..\src\test\xxxxx_tests.cpp` by one `..\..\src\test\*.cpp` might work.

**Comment by ken2812221** [comment]
@MarcoFalke Yes, note that appveyor does not connect with github team. So the owner need to change his account name on appveyor to "bitcoin" to get "bitcoin" project prefix(https://ci.appveyor.com/account), but that is not necessary.

**Comment by sipsorcery** [comment]
utACK https://github.com/bitcoin/bitcoin/commit/a87072f4b9ce2e4020dd2a1ca4ed7cb227757090

@NicolasDorier's suggestion is a good one and would help avoid files missing in the future (it was human error on my behalf that caused them to be missing in the first place).

``` 
<ItemGroup>
  <ClCompile Include="..\..\src\test\*.cpp" Exclude="..\..\src\test\test_bitcoin_fuzzy.cpp" />
  <ClCompile Include="..\..\src\wallet\test\*.cpp" />
  </ItemGroup>
```

@MarcoFalke if there is a webhook on the bitcoin/bitcoin project under Settings->WebHooks and we can get it that would allow us to initiate the AppVeyor builds automatically whenever there is a commit. At the moment I kick off a build whenever I see a Twitter commit message.

**Comment by practicalswift** [comment]
@sipsorcery Would it be possible to use wildcards in the other project files to make the maintenance of these scripts easier? :-)

**Comment by MarcoFalke** [comment]
It must run on pull requests. Otherwise we can't enable it on the master branch without having to fix each failure post merge.

**Comment by ken2812221** [comment]
@practicalswift That might not happen on other project files because that would cause link error.

@MarcoFalke Yes, it can run on pull request https://ci.appveyor.com/project/ken2812221/bitcoin/build/1.0.150

**Comment by sipsorcery** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/13964/commits/1f6ff04e59fcd1f2315d194f096665d73c8922d2

**Comment by sipsorcery** [comment]
A small note on the AppVeyor build in this PR.

The URL to install the bzip dependency in the AppVeyor version of vcpkg (the Microsoft C++ dependency that makes building bitcoin-core straight forward) is currently broken as per https://github.com/Microsoft/vcpkg/pull/4046.

The consequence is that anyone that forks bitcoin-core and creates their own AppVeyor job will end up with a failing job. At some point AppVeyor will update their vcpkg version and this will be fixed. In the meantime it's possible to workaround the problem by manually updating the vcpkg files using:

```
cd c:\tools\vcpkg
git pull
```

I don't think it's worth adding these commands to the appveyor.yml as it would potentially result in dependency updates that a user may not be expecting.

**Comment by sipsorcery** [comment]
Before doing a PR I'll try and ascertain how/when AppVeyor update vcpkg https://help.appveyor.com/discussions/problems/15817-vcpkg-updates.

**Comment by ken2812221** [comment]
@MarcoFalke Did you have any trouble while setting up Appveyor CI?

**Comment by NicolasDorier** [comment]
Cool they replied on https://help.appveyor.com/discussions/problems/15817-vcpkg-updates

```
install:
- cmd: |
    cd "C:\Tools\vcpkg"
    git pull
    .\bootstrap-vcpkg.bat
    cd %appveyor_build_folder%
```

@MarcoFalke , you will need that for now if you want to include to github. That said they will fix in some weeks.

**Comment by MarcoFalke** [comment]
@laanwj @ken2812221 I have set this up through DrahtBot. Though, it wouldn't run on pull requests, it seems.

**Comment by ken2812221** [comment]
@MarcoFalke Can you take a look at https://github.com/bitcoin/bitcoin/settings/hooks
It should enable pull request
image

**Comment by ras0219-msft** [comment]
@sipsorcery We would definitely recommend what @NicolasDorier suggests -- the best fix here is to  checkout a specific vcpkg git commit in your appveyor.yml:
```
cd C:\Tools\vcpkg
git checkout <some sha, perhaps today's master>
.\bootstrap-vcpkg.bat
cd %appveyor_build_folder%
```
Whenever you want to update your dependencies (say, to fix issues like this), you just need to change the commit id.

**Comment by ken2812221** [comment]
@MarcoFalke Could you enable rolling build for Appveyor?
 https://www.appveyor.com/docs/build-configuration/#rolling-builds

**Comment by MarcoFalke** [comment]
Hmm, that would make it impossible to run multiple pull requests?

**Comment by ken2812221** [comment]
@MarcoFalke  If you push to the same PR, it would cancel the previous one and does not affect other PRs.

**Comment by jonasschnelli** [comment]
Post merge: I'm unsure about the usefulness of this. This requires documentation. I have no clue how to make #14032 pass AppVeyor...
Somehow I have the feeling that this sets an unexpected heavy burden on those not primarily interested in MSVC support.

IMO MSVC compatibility should be maintained by those interested in it.

**Comment by sipsorcery** [comment]
The project files for the msvc build are currently not automatically synchronised with the Makefiles. Whenever a new class file is added or removed the msvc build will break. Until we write a script to keep them in sync I agree with @jonasschnelli in that blocking a PR based on the msvc build is not ideal.

**Comment by practicalswift** [comment]
@sipsorcery Agreed!

Could a way to solve this be to auto-generate the project files (or at least the parts referencing files) to make sure they’re automatically changed when new files are added/removed?

The only input needed for such auto-generation would be `find src/ -type f`? :-)

See previous discussion in https://github.com/bitcoin/bitcoin/pull/11526#issuecomment-338202281 and https://github.com/bitcoin/bitcoin/pull/11526#issuecomment-338210829 about auto-generation.

**Comment by sipsorcery** [comment]
The options I can think of:

1. Leave the Visual Studio project files as is and manually update the project files as class files are added and removed. Over the last 12 months I’d estimate I’ve updated the project files about a dozen times,
2. Investigate switching to a wildcard project file,
3. Switch from Makefile to CMake to allow a wider variety of platform builds from a single configuration.

For my own purposes option 1 is by far the most useful. Having a Visual Studio project configuration that directly reflects the current bitcoin core libraries makes building and debugging straight forward and is the by far the biggest benefit for me. It’s also not a great burden to update the project files when the build breaks but that’s based on only building the master branch.

For options 2 and 3 it would make building on Windows easier but be worse for debugging and comprehending the code.

**Pull request merged**
