### PR TITLE
Scale legacy sigop count in CreateNewBlock

### PR DESCRIPTION
**Pull request by sdaftuar**
This bugfix should be cherry-picked to 0.13 as well.

### CODE REVIEW

**Comment by luke-jr** [comment]
utACK, although I wonder if it would be better to do the scaling in GetLegacySigOpCount

**Comment by sipa** [comment]
utACK. I think this is the easiest fix.

**Comment by MarcoFalke** [comment]
utACK 682aa0f289c550c029733966a2ce3449e4a471df Agree with @sipa

**Comment by laanwj** [comment]
Sorry for the stupid question here: but what bug does this fix?

**Comment by sipa** [comment]
I think this is exactly a no-op. The internal result from CreateNewBlock is incorrectly computed (the sigop value for the coinbase transaction is off by a factor 4), however, this value is ignored by all call sites:
* GBT lets the consumer construct their own coinbase, so does not report anything about the temporary coinbase transaction used inside CreateNewBlock
* The `generate` RPC call uses the constructed block directly, ignoring all metadata about it.

**Comment by sdaftuar** [comment]
@laanwj @sipa You guys are right -- I stumbled across the units error when making the weight/cost change, and assumed it must propagate downstream somehow, but indeed it seems to be ignored.

Still, unless someone is eager to rewrite the gbt code to be both better tested and have no no-op lines, I think we might as well merge this at some point so that we don't have "incorrect" code lying around (that could inadvertently be exposed or copied), but there's no urgency.

**Comment by laanwj** [comment]
> I think we might as well merge this at some point so that we don't have "incorrect" code lying around (that could inadvertently be exposed or copied), but there's no urgency.

Thanks for the explanation @sipa @sdaftuar .

I tend to agree that this is better than leaving it as-is. Though on the other hand, if this is dead code, removing it may be the wisest thing to do. If it's unused even in tests, then for the next change, we'll likely forget to update it again.

**Pull request merged**
