### PR TITLE
DRY config header inclusion

### PR DESCRIPTION
**Pull request by danra**
Create a wrapper header file which includes config/bitcoin-config.h only if it exists (according to a macro). Files can include this wrapper header directly instead of having each including file repeat the check-if-config-exists-and-only-include-if-it-does macros.

p.s. Open to suggestions if anyone has a better filename for the wrapper header.

### CODE REVIEW

**Comment by dougstrong77** [comment]
Is this for my wallet

**Review by dougstrong77 — APPROVED** [review]

**Comment by danra** [comment]
@laanwj Looks like Travis builds fail due to check-doc.py failure on -usehd

**Review by promag — COMMENTED** [review]
How about just
```cpp
#include "bitcoin-config.h"
```
which includes `config/bitcoin-config.h`.

**Comment by danra** [comment]
@promag I think that would be 1) confusing to readers 2) brittle to include paths changes

**Comment by promag** [comment]
> brittle to include paths changes

I believe there is a plan to make all includes relative to `src/` cc @laanwj. 

Another option is to change the generated to, for instance
```
AC_CONFIG_HEADERS([src/config/bitcoin-config-gen.h])
```
And always have `config/bitcoin-config.h` which checks for that.

**Comment by danra** [comment]
> Another option is to change the generated to, for instance
> 
> AC_CONFIG_HEADERS([src/config/bitcoin-config-gen.h])
> And always have config/bitcoin-config.h which checks for that.

That's fine with me if more people agree that's preferable.

Personally I think 
`"#include "config/bitcoin-config-if-exists.h"`
or
`"#include "bitcoin-config-if-exists.h"`
reads nice and explicit, saying what we are actually doing - including the config file, but just in case it exists.

**Comment by MeshCollider** [comment]
Other than refactoring, does this have any benefit? I'm not too keen on this idea tbh

**Comment by danra** [comment]
@MeshCollider In general, refactoring in order to DRY code has benefits.
1) Less overhead to reading and understanding the code. Especially important for security-conscious projects.
2) Less chance of being wrong when writing new code (e.g. see 3aa60b7ff9587637dcb3e646c2448bf75495a1f4)

And more. But I think that's enough.

**Comment by MeshCollider** [comment]
@danra, not exactly sure, its just something about creating an entire new file just for 3 lines to import another file. IMO its clear enough as it is, because its just an if-statement, and anyone who would currently forget the ifdef would probably also forget to use this file, and just include bitcoin-config.h directly. Yes DRY is better, but I think this is taking it a bit far, that's all :)

**Comment by danra** [comment]
@MeshCollider In addition to the considerations I mentioned, it's a macro if, easy to either misspell or get wrong (checking for value instead of just being defined, etc.)
Better contain it to a single file and forget about it.

**Comment by achow101** [comment]
@danra can you do the bulk of this as a scripted diff? That would make review easier and also less likely for you to have accidentally missed an include.

**Comment by danra** [comment]
@achow101 It's fine. I didn't miss anything :P

Seriously, I'm not sure a script would help very much, since there're subtle variations of the original ifdefs as you can see in the diff. So at best the script would show handling of some variations, and the rest of the code would have to be checked anyway for any other variations not covered by the script.

At best, the script would prove no misspellings of the new include, but that would be caught as a compiler error anyway.

**Comment by achow101** [comment]
A scripted diff is easier to review and verify that the changes are correct, especially for such a change like this which is basically a scripted diff.

**Comment by danra** [comment]
DAK why Travis is failing to find "config/bitcoin-config-if-present.h" in the build? Is this some cache issue? It builds fine on my local machine.

**Comment by MarcoFalke** [comment]
@danra I haven't looked by it could be that out of tree builds are failing.

**Comment by danra** [comment]
@MarcoFalke Tested out of tree build on my local machine - works fine. Would appreciate any other pointers as to what else might be causing the travis build to fail.

**Comment by sipa** [comment]
Run `make distcheck`.

**Comment by danra** [comment]
@sipa That reproduces the build error locally. Thanks!

**Review by dcousens — APPROVED** [review]

**Comment by danra** [comment]
@achow101 Added scripted diff.
Rebased

**Comment by danra** [comment]
Does anyone know if `GLOBIGNORE` is supported in the shell on the Travis host which fails the scripted-diff check? It works on my local bash but I can't get it to work here, tried multiple variations.

**Comment by laanwj** [comment]
Closing this for now, I don't think there is agreement to do this, and rebasing it will be a ton of work.

**Pull request closed without merging**
