### PR TITLE
doc: Changes to README to stop future PRs

### PR DESCRIPTION
**Pull request by michaelfolkson**
We continue to receive PRs (e.g. #24429) to remove "experimental" from the README and to add a link to the white paper. To prevent us from receiving these PRs add "(arguably)" in front of experimental and remove any reference to the white paper. 

The intention is to save time of reviewers (and new PR authors). If this does more harm than good feel free to close this PR.

### CODE REVIEW

**Comment by prayank23** [comment]
> add "(arguably)" in front of experimental and 

ACK

Other word can be 'debatable' and both look good according to https://english.stackexchange.com/questions/221305/whats-the-difference-between-arguable-and-debatable#221317

> remove any reference to the white paper

NACK

**Comment by laanwj** [comment]
Bah, prefer not to bother with this. (arguably) experimental sounds really awful to me sentence-wise. I'd prefer just to keep this as is. People will find reason to do silly PRs nevertheless, we'll continue to ignore them.

**Comment by michaelfolkson** [comment]
Ok I tried :) Closing!

**Comment by laanwj** [comment]
If you really want to be edgy you could add "!!! do not open PRs that change the word experimental or reference to the whitepaper in README.md !!!" to the template text people see when opening a PR :)
(no, this is not a serious suggestion)

**Comment by prayank23** [comment]
Personally I don't consider word 'experimental' a big issue because I think even [life is an experiment](https://i.imgur.com/tkO1eRd.jpg). However, lot of users don't believe Bitcoin is still an experiment so adding a word that describes this situation made sense.

Removing last reference to term whitepaper from readme is not required IMO. In fact whitepaper or link can be added back when we have consensus about it in future.

**Comment by katesalazar** [comment]
Close referring COPYING.

https://github.com/bitcoin/bitcoin/blob/a1b532d1a5f02f1ef4c5af52e04072eab9636bb1/COPYING#L16-L22

**Pull request closed without merging**
