### PR TITLE
refactor: include a missing <limits> header in fs.cpp

### PR DESCRIPTION
**Pull request by joankaradimov**
I get this compilation error on versions `0.21.1` and `22.0`:

```
fs.cpp: In member function 'bool fsbridge::FileLock::TryLock()':
fs.cpp:123:89: error: 'numeric_limits' is not a member of 'std'
  123 |     if (!LockFileEx(hFile, LOCKFILE_EXCLUSIVE_LOCK | LOCKFILE_FAIL_IMMEDIATELY, 0, std::numeric_limits<DWORD>::max(), std::numeric_limits<DWORD>::max(), &overlapped)) {
      |                                                                                         ^~~~~~~~~~~~~~
fs.cpp:123:109: error: expected primary-expression before '>' token
  123 |     if (!LockFileEx(hFile, LOCKFILE_EXCLUSIVE_LOCK | LOCKFILE_FAIL_IMMEDIATELY, 0, std::numeric_limits<DWORD>::max(), std::numeric_limits<DWORD>::max(), &overlapped)) {
      |                                                                                                             ^
fs.cpp:123:112: error: '::max' has not been declared; did you mean 'std::max'?
  123 |     if (!LockFileEx(hFile, LOCKFILE_EXCLUSIVE_LOCK | LOCKFILE_FAIL_IMMEDIATELY, 0, std::numeric_limits<DWORD>::max(), std::numeric_limits<DWORD>::max(), &overlapped)) {
      |                                                                                                                ^~~
      |                                                                                                                std::max
In file included from C:/dev/msys64/mingw64/include/c++/11.2.0/bits/char_traits.h:39,
                 from C:/dev/msys64/mingw64/include/c++/11.2.0/string:40,
                 from ./fs.h:9,
                 from fs.cpp:5:
C:/dev/msys64/mingw64/include/c++/11.2.0/bits/stl_algobase.h:300:5: note: 'std::max' declared here
  300 |     max(const _Tp& __a, const _Tp& __b, _Compare __comp)
      |     ^~~
fs.cpp:123:124: error: 'numeric_limits' is not a member of 'std'
  123 |     if (!LockFileEx(hFile, LOCKFILE_EXCLUSIVE_LOCK | LOCKFILE_FAIL_IMMEDIATELY, 0, std::numeric_limits<DWORD>::max(), std::numeric_limits<DWORD>::max(), &overlapped)) {
      |                                                                                                                            ^~~~~~~~~~~~~~
fs.cpp:123:144: error: expected primary-expression before '>' token
  123 |     if (!LockFileEx(hFile, LOCKFILE_EXCLUSIVE_LOCK | LOCKFILE_FAIL_IMMEDIATELY, 0, std::numeric_limits<DWORD>::max(), std::numeric_limits<DWORD>::max(), &overlapped)) {
      |                                                                                                                                                ^
fs.cpp:123:147: error: '::max' has not been declared; did you mean 'std::max'?
  123 |     if (!LockFileEx(hFile, LOCKFILE_EXCLUSIVE_LOCK | LOCKFILE_FAIL_IMMEDIATELY, 0, std::numeric_limits<DWORD>::max(), std::numeric_limits<DWORD>::max(), &overlapped)) {
      |                                                                                                                                                   ^~~
      |                                                                                                                                                   std::max
In file included from C:/dev/msys64/mingw64/include/c++/11.2.0/bits/char_traits.h:39,
                 from C:/dev/msys64/mingw64/include/c++/11.2.0/string:40,
                 from ./fs.h:9,
                 from fs.cpp:5:
C:/dev/msys64/mingw64/include/c++/11.2.0/bits/stl_algobase.h:300:5: note: 'std::max' declared here
  300 |     max(const _Tp& __a, const _Tp& __b, _Compare __comp)
      |     ^~~
```

It appears that `std::numeric_limits<T>::max` is used without the `limits` header being included. Probably on other STL implementations it's included transitively, but not in the one in MinGW. Including it fixes the compilation problem.

Environment:
OS: Windows 10
Compiler: gcc 11.2.0
Qt: 5.15.2 (included in msys2)
Using the latest mingw w64 shipped with msys2.

### CODE REVIEW

**Comment by theuni** [comment]
Only the windows code paths use `std::numeric_limits`. The transitivity is moot elsewhere.

Otherwise I'd agree :)

**Comment by joankaradimov** [comment]
> Please write a more descriptive commit message title. i.e `refactor: add missing <limits> header to fs.cpp`

Updated and force pushed.

**Review by fanquake — APPROVED** [review]
ACK 077a875d94b51e3c87381133657be98989c8643e - Thanks.

**Review by hebasto — APPROVED** [review]
ACK 077a875d94b51e3c87381133657be98989c8643e

FWIW, the `<limits>` header is also missed in multiple other places. This is another reason to consider #15442.

**Comment by fanquake** [comment]
Backported to 0.21 in #25318.

**Pull request merged**
