### PR TITLE
[wallet] Set fLimitFree = true

### PR DESCRIPTION
**Pull request by maflcko**
- Free transactions is no longer a thing.
- It was removed from the GUI in 0.13 and made debug option. #7686
- I don't see a need to be susceptible to fingerprinting.

### CODE REVIEW

**Comment by paveljanik** [comment]
=false?

**Comment by sipa** [comment]
Agree, I prefer 2 commits.

**Comment by MarcoFalke** [comment]
@sipa @paveljanik Done.

**Review by paveljanik — APPROVED** [review]
ACK https://github.com/bitcoin/bitcoin/pull/8287/commits/fa8b02d36d5c75266d3c8ffb91ece761ce90e774

**Pull request merged**
