### PR TITLE
key: clear out secret data in `DecodeExtKey`

### PR DESCRIPTION
**Pull request by theStack**
Same as in `DecodeSecret`, we should also clear out the secret data from the vector resulting from the Base58Check parsing for xprv keys. Note that the if condition is needed in order to avoid UB, see #14242 (commit d855e4cac8303ad4e34ac31cfa7634286589ce99).

### CODE REVIEW

**Review by tdb3 — APPROVED** [review]
cr ACK 559a8dd9c0aafcecf00f9ccd9aabe5720bcebe8c

Good catch

**Review by laanwj — APPROVED** [review]
Code review ACK 559a8dd9c0aafcecf00f9ccd9aabe5720bcebe8c

**Comment by davidgumberg** [comment]
Maybe should do:

```diff
 CExtKey DecodeExtKey(const std::string& str)
 {
     CExtKey key;
-     std::vector<unsigned char> data;

**Comment by laanwj** [comment]
Yes, using secure_allocator is a better option if possible.

**Comment by davidgumberg** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/31166/commits/559a8dd9c0aafcecf00f9ccd9aabe5720bcebe8c

I agree that given how short lived this data is it doesn't seem likely to get paged, but it would still be nice to encapsulate our allocation strategy for secrets.

**Comment by achow101** [comment]
ACK 559a8dd9c0aafcecf00f9ccd9aabe5720bcebe8c

**Pull request merged**
