### PR TITLE
build: switch to upstream libdmg-hfsplus

### PR DESCRIPTION
**Pull request by fanquake**
Pulled the first two commits off #16392, as they are standalone.

Corys PRs (https://github.com/planetbeing/libdmg-hfsplus/pull/7, https://github.com/planetbeing/libdmg-hfsplus/pull/8) have been merged, and the author was active for a little while in 2017/18, so switch back to the upstream [`libdmg-hfsplus`](https://github.com/planetbeing/libdmg-hfsplus) repo. I've added the last of Corys patches into depends.

[Switching back to upstream discussion](https://github.com/bitcoin/bitcoin/pull/16392#discussion_r303610767).

### CODE REVIEW

**Comment by laanwj** [comment]
Concept ACK

**Comment by laanwj** [comment]
Can someone please check the resulting `.dmg` file above, on a Mac?

**Comment by jonasschnelli** [comment]
I checked the dmg from @DrahtBot's gitian build and it looks good.
Though my own gitian build failed:
https://bitcoin.jonasschnelli.ch/build/1251
```
....
+ OSX_VOLNAME=Bitcoin-Core
+ mkdir -p unsigned-app-x86_64-apple-darwin14
+ cp osx_volname unsigned-app-x86_64-apple-darwin14/
+ cp contrib/macdeploy/detached-sig-apply.sh unsigned-app-x86_64-apple-darwin14
+ cp contrib/macdeploy/detached-sig-create.sh unsigned-app-x86_64-apple-darwin14
+ cp /home/ubuntu/build/bitcoin/depends/x86_64-apple-darwin14/native/bin/dmg /home/ubuntu/build/bitcoin/depends/x86_64-apple-darwin14/native/bin/genisoimage unsigned-app-x86_64-apple-darwin14
cp: cannot stat '/home/ubuntu/build/bitcoin/depends/x86_64-apple-darwin14/native/bin/dmg': No such file or directory
Failed run an application inside container
```

**Comment by dongcarl** [comment]
Getting the same error, some clue from my docker container:
```
root@b7b23ed5f2d6:/home/ubuntu/build/bitcoin/depends/x86_64-apple-darwin16/native/bin# ls
bin           x86_64-apple-darwin16-ObjectDump         x86_64-apple-darwin16-indr               x86_64-apple-darwin16-ranlib
clang         x86_64-apple-darwin16-ar                 x86_64-apple-darwin16-inout              x86_64-apple-darwin16-redo_prebinding
clang++       x86_64-apple-darwin16-as                 x86_64-apple-darwin16-install_name_tool  x86_64-apple-darwin16-seg_addr_table
genisoimage   x86_64-apple-darwin16-bitcode_strip      x86_64-apple-darwin16-ld                 x86_64-apple-darwin16-seg_hack
lrelease      x86_64-apple-darwin16-check_dylib        x86_64-apple-darwin16-libtool            x86_64-apple-darwin16-segedit
lupdate       x86_64-apple-darwin16-checksyms          x86_64-apple-darwin16-lipo               x86_64-apple-darwin16-size
moc           x86_64-apple-darwin16-cmpdylib           x86_64-apple-darwin16-machocheck         x86_64-apple-darwin16-strings
qdbuscpp2xml  x86_64-apple-darwin16-codesign_allocate  x86_64-apple-darwin16-nm                 x86_64-apple-darwin16-strip
qdbusxml2cpp  x86_64-apple-darwin16-ctf_insert         x86_64-apple-darwin16-nmedit             x86_64-apple-darwin16-unwinddump
rcc           x86_64-apple-darwin16-dsymutil           x86_64-apple-darwin16-otool
uic           x86_64-apple-darwin16-dyldinfo           x86_64-apple-darwin16-pagestuff
root@b7b23ed5f2d6:/home/ubuntu/build/bitcoin/depends/x86_64-apple-darwin16/native/bin# ls bin
dmg
```
It would seem that `dmg` was installed to `depends/x86_64-apple-darwin16/native/bin/bin` (note the double `bin`)

**Comment by jonasschnelli** [comment]
Oh. I tested the wrong dmg of @DrahtBot's gitian build (tested master). I edited my comment above.

Drath's OSX build did also fail.

**Comment by MarcoFalke** [comment]
Jup, failure was:


```
  AR       qt/libbitcoinqt.a
make[2]: Leaving directory '/home/ubuntu/build/bitcoin/distsrc-x86_64-apple-darwin14/src'
make[1]: Leaving directory '/home/ubuntu/build/bitcoin/distsrc-x86_64-apple-darwin14/src'
Making all in doc/man
make[1]: Entering directory '/home/ubuntu/build/bitcoin/distsrc-x86_64-apple-darwin14/doc/man'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/ubuntu/build/bitcoin/distsrc-x86_64-apple-darwin14/doc/man'
make[1]: Entering directory '/home/ubuntu/build/bitcoin/distsrc-x86_64-apple-darwin14'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/home/ubuntu/build/bitcoin/distsrc-x86_64-apple-darwin14'
/bin/mkdir -p Bitcoin-Qt.app/Contents/MacOS
STRIPPROG="/home/ubuntu/build/bitcoin/depends/x86_64-apple-darwin14/share/../native/bin/x86_64-apple-darwin14-strip" /bin/bash /home/ubuntu/build/bitcoin/distsrc-x86_64-apple-darwin14/build-aux/install-sh -c -s  ./src/qt/bitcoin-qt Bitcoin-Qt.app/Contents/MacOS/Bitcoin-Qt
/bin/mkdir -p Bitcoin-Qt.app/Contents/Resources/Base.lproj
echo '{	CFBundleDisplayName = "Bitcoin Core"; CFBundleName = "Bitcoin Core"; }' > Bitcoin-Qt.app/Contents/Resources/Base.lproj/InfoPlist.strings
INSTALLNAMETOOL=/home/ubuntu/build/bitcoin/depends/x86_64-apple-darwin14/share/../native/bin/x86_64-apple-darwin14-install_name_tool  OTOOL=/home/ubuntu/build/bitcoin/depends/x86_64-apple-darwin14/share/../native/bin/x86_64-apple-darwin14-otool STRIP=/home/ubuntu/build/bitcoin/depends/x86_64-apple-darwin14/share/../native/bin/x86_64-apple-darwin14-strip /usr/bin/python3.6 ./contrib/macdeploy/macdeployqtplus Bitcoin-Qt.app -translations-dir=/home/ubuntu/build/bitcoin/depends/x86_64-apple-darwin14/share/../translations -add-qt-tr da,de,es,hu,ru,uk,zh_CN,zh_TW -verbose 2
Warning: Could not detect Qt's path, skipping plugin deployment!
+ Copying source bundle +
+ Deploying frameworks +
Warning: Could not find any external frameworks to deploy in dist/Bitcoin-Qt.app.
+ Installing qt.conf +
+ Adding Qt translations +
+ Done +
/bin/mkdir -p dist/.background
/usr/bin/tiffcp -c none dpi36.background.tiff dpi72.background.tiff dist/.background/background.tiff
/usr/bin/python3.6 contrib/macdeploy/custom_dsstore.py "dist/.DS_Store" "Bitcoin-Core"
++ cat osx_volname
+ OSX_VOLNAME=Bitcoin-Core
+ mkdir -p unsigned-app-x86_64-apple-darwin14
+ cp osx_volname unsigned-app-x86_64-apple-darwin14/
+ cp contrib/macdeploy/detached-sig-apply.sh unsigned-app-x86_64-apple-darwin14
+ cp contrib/macdeploy/detached-sig-create.sh unsigned-app-x86_64-apple-darwin14
+ cp /home/ubuntu/build/bitcoin/depends/x86_64-apple-darwin14/native/bin/dmg /home/ubuntu/build/bitcoin/depends/x86_64-apple-darwin14/native/bin/genisoimage unsigned-app-x86_64-apple-darwin14
cp: cannot stat '/home/ubuntu/build/bitcoin/depends/x86_64-apple-darwin14/native/bin/dmg': No such file or directory

**Comment by MarcoFalke** [comment]
@fanquake Does this require a new sdk or something?

**Comment by dongcarl** [comment]
@MarcoFalke @jonasschnelli Sorry, I should have posted here as well... I fixed this in https://github.com/fanquake/bitcoin/compare/329af88c548ff4afe6fed7fdbad3d39f62044048...dongcarl:2019-10-fixing-fanquake-osx-bump, specifically https://github.com/fanquake/bitcoin/commit/a24ba3ac94d1ebc42a6471e9fb50177958b36f48

**Comment by fanquake** [comment]
Thanks for the testing. I'd been `make deploy`ing on Debian to test the built DMGs back on macOS, and had missed the [upstream bin changes](https://github.com/planetbeing/libdmg-hfsplus/commit/ddeed55ff514073755988f4cb51e1e2bac6e6ea3). Have rebased, fixed `DCMAKE_INSTALL_PREFIX` and queued a new gitian build.

> Does this require a new sdk or something?

No this doesn't require any changes to our required macOS SDK.

**Review by theuni — APPROVED** [review]
ACK, looks good to me!

**Pull request merged**
