### PR TITLE
rpc, test: remove newline escape sequence from wallet warning fields

### PR DESCRIPTION
**Pull request by jonatack**
This PR extends our test coverage to demonstrate the issue, then removes newline escape sequences printed in the wallet `warning` field in RPCs `createwallet`, `loadwallet`, `unloadwallet`, and `restorewallet`.

before

```
$ ./src/bitcoin-cli -signet createwallet w1 false false "" false false
{
  "name": "w1",
  "warning": "Empty string given as passphrase, wallet will not be encrypted.\nWallet created successfully. The legacy wallet type is being deprecated and support for creating and opening legacy wallets will be removed in the future."
}
```

after

```
$ ./src/bitcoin-cli -signet createwallet w2 false false "" false false
{
  "name": "w2",
  "warning": "Empty string given as passphrase, wallet will not be encrypted. Wallet created successfully. The legacy wallet type is being deprecated and support for creating and opening legacy wallets will be removed in the future."
}
```

Rationale:  Our RPC is returning newline presentation elements embedded in JSON string field responses. These are a client-side concern, not a server-side one.  If it is important for the RPC client to know how many warnings have been returned in order to display them on separate lines, then it may be a good idea after this to gradually replace the `warning` string field with a `warnings` JSON array of strings, as we do in several other RPCs.  I'm happy to do that in a follow-up, as it would be orthogonal to this change: first the `warnings` field would be added and the `warning` field deprecated, then after a release or so the latter could possibly be removed. In the meantime, this is a simple and focused fix.

### CODE REVIEW

**Comment by TheCharlatan** [comment]
Concept ACK

> I believe only createwallet appends additional warning sentences and is affected by the fix.

I think they all do, check the code in `CWallet::Create`. E.g. by setting weird `mintxfee` and `maxapsfee` values:
```
./bitcoin-cli -signet restorewallet "w2" "w2"
{
  "name": "w2",
  "warning": "-mintxfee is set very high! This is the minimum transaction fee you pay on every transaction.\n-maxapsfee is set very high! This is the maximum transaction fee you pay (in addition to the normal fee) to prioritize partial spend avoidance over regular coin selection."
}

```

**Review by sedited — APPROVED** [review]
ACK f0391cd3ea562d526db63996e7694ff4cd44b8b2

Was a bit hesitant about adding the messages to the functional tests, but I think testing the correct concatenation kind of makes sense.

**Comment by pinheadmz** [comment]
Code changes and tests look OK to me but I don't understand the motivation, are newlines a problem in RPC responses?

I found a few other similar mechanisms in other modules, dunno if this change should apply to them as well:

https://github.com/bitcoin/bitcoin/blob/82793f1984911774b111117f2e81d5f3b0bbec68/src/warnings.cpp#L55-L57

https://github.com/bitcoin/bitcoin/blob/82793f1984911774b111117f2e81d5f3b0bbec68/src/validation.cpp#L2565-L2569

**Review by pinheadmz — APPROVED** [review]
ACK f0391cd3ea562d526db63996e7694ff4cd44b8b2

**Comment by ryanofsky** [comment]
-0. Showing \n on the terminal seems like a client side problem not a server side problem, and this server-side change makes it harder for other clients besides bitcoin-cli to display the warnings clearly on separate lines.

IMO, the ideal fix for this would be for `bitcoin-cli` to colorize and pretty-print the json when it detects stdout is a tty.

**Comment by fanquake** [comment]
> Saw those for (maybe, maybe not) another pull; prefer to keep this small and focused.

If they are the same issue, what's the reasoning for leaving them for another PR? Not sure how the PR becomes less focused by fixing more of the same problem.

**Review by vasild — APPROVED** [review]
ACK f0391cd3ea562d526db63996e7694ff4cd44b8b2

The newline is presentation-specific and does not belong to the server output. For example it will not render as expected if displayed in HTML (where newlines are displayed as a single space). Then it should be `<br/>` instead of `\n`, or maybe `\r\n` for MacOS?

I am happy to review more of the same in another PR or a change that returns an array of warnings so that display engines can chose the best separator for them.

**Comment by achow101** [comment]
I agree with @ryanofsky that this is a client side issue which should be fixed in the client and not the server. I also prefer that we remove `warning` and replace it with `warnings` as has been done in several other RPCs.

**Comment by ryanofsky** [comment]
> I'm not sure it makes sense to patch around this by adding code to our CLI to parse newline escape sequences

Yes agree no need for this as we already have a JSON parser. CLI could see simply if check result object has `"warning"` field which is a string, and if it does, write the string to stderr.

This would be really simple, and make warnings more obvious and readable, and be compatible with other bitcoin-cli improvements in the future.

**Pull request closed without merging**
