### PR TITLE
[doc] gitian: Replace precise with trusty

### PR DESCRIPTION
**Pull request by maflcko**

### CODE REVIEW

**Comment by laanwj** [comment]
Trivial ACK, doc changes look good to me, but haven't tested the new sequence verbatim

**Comment by jonasschnelli** [comment]
"ut"ACK fa6399d918fdaa8844c4c767b2012e0b2ca60ee9

**Comment by MarcoFalke** [comment]
We never got complaints that this is still wrong. So I didn´t bother testing  this either.

**Comment by paveljanik** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/7855/commits/fa6399d918fdaa8844c4c767b2012e0b2ca60ee9

**Pull request merged**
