### PR TITLE
[0.20] wallet: Simplify and fix CWallet::SignTransaction

### LINKED ISSUE #19737: signrawtransactionwithwallet fails to sign non-wallet inputs (0.20 only; before/after already fixed)
#17204 introduced a test that uses `signrawtransactionwithwallet` to sign a non-wallet input (providing the necessary solution as a param).

At least 0.20 didn't allow this. Bisect reveals that the behaviour change was in bde7c9fa38775a81d53ac0484fa9c98076a0c7d1 (part of #16528, descriptor wallets).

Is this change intended behaviour, or a bug?

### PR DESCRIPTION
**Pull request by achow101**
Backport `CWallet::SignTransaction` from master which is simpler and not broken.

Previously `CWallet::SignTransaction` would return false for a fully signed transaction. This is a regression and obviously incorrect - a fully signed transaction is always complete. This occurs because `CWallet::SignTransaction` would iterate through each input and skip any further checks if the input was already signed. It would then end up falling through to the `return false` catch-all thus erroneously saying a fully signed transaction is incomplete. The change to attempting to use all `ScriptPubKeyMan`s fixes this problem since the `LegacyScriptPubKeyMan` (the only spkm implemented in 0.20) will verify inputs during its signing attempt and correctly return that it is complete when the inputs verify. Thus a fully signed transaction will be correctly identified as complete, `LegacyScriptPubKeyMan::SignTranaction` will return true, and so `CWallet::Transaction` will return true too.

Note that this is not a backport of any specific commit. Rather it is the end result of the changes we have made to this function in master.

Fixes #19737

### CODE REVIEW

**Comment by doianmai2020** [comment]
To create a branch rule, the branch you specify doesn't have to exist yet in the repository.

**Comment by fjahr** [comment]
utACK 2d48d7dcfb93eeec36dd6f5cbad289b89ec69324

**Comment by MarcoFalke** [comment]
I'd feel more comfortable if all the individual commits were backported instead of a effectively squashed version without reference to the original commits

**Comment by achow101** [comment]
> I'd feel more comfortable if all the individual commits were backported instead of a effectively squashed version without reference to the original commits

There aren't really any individual commits *to* backport. This end result is essentially an accident and a product of the refactors and changes made for descriptor wallets. To backport those commits would be nuts and bring in a bunch of things that aren't needed.

**Comment by MarcoFalke** [comment]
Concept ACK

**Comment by achow101** [comment]
Updated the OP and cherry-picked #20562 for the test for this.

**Comment by MarcoFalke** [comment]
Checked that the test fails without the code changes:

```
./test/functional/rpc_signrawtransaction.py 
2020-12-04T14:55:24.933000Z TestFramework (INFO): Initializing test directory /tmp/bitcoin_func_test_q8rf0stk
2020-12-04T14:55:26.373000Z TestFramework (INFO): Try with a P2PKH script as the witnessScript
2020-12-04T14:55:26.389000Z TestFramework (INFO): Try with a P2PK script as the witnessScript
2020-12-04T14:55:26.741000Z TestFramework (INFO): Test signing a fully signed transaction does nothing
2020-12-04T14:55:26.946000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/home/marco/workspace/btc_bitcoin_core/test/functional/test_framework/test_framework.py", line 112, in main
    self.run_test()
  File "/home/marco/workspace/btc_bitcoin_core/./test/functional/rpc_signrawtransaction.py", line 227, in run_test
    self.test_fully_signed_tx()
  File "/home/marco/workspace/btc_bitcoin_core/./test/functional/rpc_signrawtransaction.py", line 158, in test_fully_signed_tx
    assert_equal(signedtx2["complete"], True)
  File "/home/marco/workspace/btc_bitcoin_core/test/functional/test_framework/util.py", line 46, in assert_equal
    raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
AssertionError: not(False == True)
```

Approach ACK a4b56df42e42ad304571ed82648893484accfa5e 🥔

<details><summary>Show signature and timestamp</summary>

Signature:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Approach ACK a4b56df42e42ad304571ed82648893484accfa5e 🥔
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEE+rVPoUahrI9sLGYTzit1aX5ppUgFAlwqrYAACgkQzit1aX5p
pUho6AwAy4I+vrdOq7pk7ML0Dehz3qSStFH7iRuDJgJ8Y51p1BiD5KyVeT0gh0vj
ZJ3Cidqnw5BF6oDhFRGWCu1SZyy3yiNFBUqR/HhqSprpSenYcm2BXvCHuKl2BjNh
DqDMsER379Joc3vdIqFBDspyQceUS+4gvkqsgn9tct1kz2Fpzw0ZXo5FPKpj+7Pd
hs7lvWb8UUWRcmk7++UBRB2lxSdlIIs/avgZzsdvQxk8sEQ5qLkqp2Z/LBhMuVtt
10DEhmAoX73zfCKYV5zTj+XXMRWVlZzxZoeslxco60CmwuMRZcMTrolvQJP0oduE
YxlL5G5l4dANoSO9jnb068ANALLK7Zzl3Ku/OM4d6ag4Yzt6EU1RkdVLSXZ66hwu
ACyqsAWlioxfCYDpXmDpjoCvobWap4Ot9Tg+1m4AwItzbRaEdVzPlCRmesvqGnUI
i3xuPwTPaFSBDdvzZHjSyuNYCsSwDokiWRNANwgY0e75eY4fYxUs3LJEpcs8QlgJ
arovBtKa
=W9jc
-----END PGP SIGNATURE-----
```

[Timestamp of file with hash `c79fcd31a097ea698807dc5bea3f3e1c7255db211721590c8c645e427a0c180a  -`](https://opentimestamps.org/info/?004f70656e54696d657374616d7073000050726f6f6600bf89e2e884e892940108c79fcd31a097ea698807dc5bea3f3e1c7255db211721590c8c645e427a0c180af010682fe902b021eb53500b514a1f3cf19108fff010866986ee944688adbd017a8619c4b5fa08f1045fca4e74f00892b0207a4ab714990083dfe30d2ef90c8e2e2d68747470733a2f2f616c6963652e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267fff0109a00276a02c526c1b0107a59adfddda108f1045fca4e74f008c487746911c507810083dfe30d2ef90c8e232268747470733a2f2f6274632e63616c656e6461722e636174616c6c6178792e636f6dfff010a524bf2b3dce275b1035f98a06ca430c08f12059fdf20c875269eb7ff5968de8ae78f74704b106a7053f1069ba837f46b35d6608f1045fca4e74f0084303b7e00ddce9950083dfe30d2ef90c8e2c2b68747470733a2f2f626f622e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267f010b6e89b1cea7d4e3c24f4a1016b3e900308f1045fca4e74f008ae49f96696b6cff10083dfe30d2ef90c8e292868747470733a2f2f66696e6e65792e63616c656e6461722e657465726e69747977616c6c2e636f6d)

</details>

**Comment by achow101** [comment]
Updated to backport #20562

**Comment by fjahr** [comment]
Code review ACK 6a326cf66f04948ffe729e5540a69e159a7840ad

Also verified that the test fails without the fix.

**Comment by MarcoFalke** [comment]
re-ACK 6a326cf66f 👓

<details><summary>Show signature and timestamp</summary>

Signature:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

re-ACK 6a326cf66f 👓
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEE+rVPoUahrI9sLGYTzit1aX5ppUgFAlwqrYAACgkQzit1aX5p
pUhTyAwAnFnihLBRb563G4JDJxQh4cCfRgpRXR3ue1ethB9Rz7Nj8LwlM83+pjCT
E2W0YwFdqo+qnQ2IbqJ5KwA5v0HxUow0dG7/f6CY33JP26YTHCfchg2a88WflcB+
PHdffVINZoEUavW4yAc6bQeF6qmlEWLTTbGaeRgZBpKvNWJcLkh1FlvS/7upg3kM
Qiyk4u7/ORYlGzhg5FvYqbVBbaDAZINIwACli1TwdSg0tbgNdojHFFMYdy6b7o6/
TMELRZy0HRfwDJBSwaVg1RuLQQnfOL1qmafXdSkfTR9RKLc2kPofR5hpxGBCHQKR
HS3AQ8vsETMDyoBaWfC1lAcDdhOdk/iFOLJFP2GSY9MHArZdF1uea/nOD7AhmMF5
mCR7/XahkSyviwwVwJidNN2cFaz/k2Yac8/8AAyMMx9wEnkodzifAo7M88pmcEay
bt9Tg7TrHfvXMEFuoF3Ofy4iF+9KNZrKeLbIzW5iviS6YEppWgRlF059/Ffw7vny
INa4mZw9
=uNHT
-----END PGP SIGNATURE-----
```

[Timestamp of file with hash `04a77f1e983fe92e78f64282f06846538107aa60448a3aa30dd8a20609188ffb  -`](https://opentimestamps.org/info/?004f70656e54696d657374616d7073000050726f6f6600bf89e2e884e89294010804a77f1e983fe92e78f64282f06846538107aa60448a3aa30dd8a20609188ffbf010a2267e693007a6c05a6f52f230f1831208fff0104fdc0d823346d15a8a59be487982e68608f1045fcc9f20f00817ad7814fe746f500083dfe30d2ef90c8e2c2b68747470733a2f2f626f622e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267fff0106d4da61ae262021b3ebb734982cc8f0108f1045fcc9f20f00893e405f44b3e755a0083dfe30d2ef90c8e232268747470733a2f2f6274632e63616c656e6461722e636174616c6c6178792e636f6dfff0109591f495953bc00ff812a4725b3c5aa308f1045fcc9f20f00845d6674fc6b7c5830083dfe30d2ef90c8e2e2d68747470733a2f2f616c6963652e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267f010c091785a77baa8dd6be6f5228500673f08f1045fcc9f20f0082a1c2893f8f5e5d30083dfe30d2ef90c8e292868747470733a2f2f66696e6e65792e63616c656e6461722e657465726e69747977616c6c2e636f6d)

</details>

**Pull request merged**
