### PR TITLE
Fix mempool packages

### PR DESCRIPTION
**Pull request by sdaftuar**
This fixes an edge case (introduced by #6654 and reported by @sipa here: https://github.com/bitcoin/bitcoin/pull/6654#issuecomment-142345556) in removing an entry from the mempool during the middle of a reorg, where the entry has an in-block ancestor which has not yet had its descendant state updated for the transaction being removed.

The first commit updates the `mempool_packages.py` rpc-test to include a test that demonstrates the bug; the second commit provides a fix.

### CODE REVIEW

**Comment by morcos** [comment]
ACK

**Comment by btcdrak** [comment]
utACK

**Comment by 0x9F** [comment]
Tested.

**Comment by laanwj** [comment]
utACK

**Pull request merged**
