### PR TITLE
[gitian] Default reference date to commit author date

### PR DESCRIPTION
**Pull request by maflcko**
<strike>Parallel to #7251 as 0.13 is released 2016-07-01?

### CODE REVIEW

**Comment by fanquake** [comment]
I'm not sure we want to start making file changes in anticipation of events 6 months ahead. This also means that any gitian builds of master between this merging and the 2016-07 are from the future? :watch: 

Other than being the 'real' date, what value does changing these add. I'm assuming the dates are already new enough that the binary file views isn't an issue?

**Comment by luke-jr** [comment]
Maybe we can get gitian to pull it from the git commit date?

**Comment by MarcoFalke** [comment]
@fanquake I will add this to `release-process.md`, so @laanwj can do it before every release.

@luke-jr  I'd prefer this option as well...

**Comment by MarcoFalke** [comment]
https://github.com/devrandom/gitian-builder/pull/113

**Comment by jonasschnelli** [comment]
Agree with @luke-jr: can we not load the date from the tag/commit date? Time could set be set to 00:00.

**Comment by MarcoFalke** [comment]
> Time could set be set to 00:00

No need to fiddle with the time. Imo it makes sense to have the exact commit (author) date corresponding to the commit which is shown in the debug window.

**Comment by MarcoFalke** [comment]
@jonasschnelli Would be nice to see if this works on your build box. Make sure to update gitian-builder, first.

**Comment by laanwj** [comment]
> @fanquake I will add this to release-process.md, so @laanwj can do it before every release.

If you do this, please automate it, it's not worth adding another manual step to me.

**Comment by MarcoFalke** [comment]
Needs rebase. Closing for now and making it a new pull.

**Pull request closed without merging**
