### PR TITLE
 Add from_me and bip125-replaceable to listunspent and gettransaction

### LINKED ISSUE #11613: rpc listunspent should expose "is_mine" and "replaceable"
Currently `listunspent` only exposes a `safe` which is coded roughly as `confirmations > 0 || (is_mine && !replaceable)` however a consumer very well might want to distinguish between when it's "mine" and when it's not (as I presently need to).

This ideally would be extended to listunspent, gettransaction and listtransactions. 

(The `listtransactions` already exposes a "trusted" which is basically "is_mine" but also uses the spendZeroConf  configuration, which is imho rather confusing. So my suggestion would be that all apis expose a consistent set of "is_mine", "replaceable" and "confirmations" (which is already always exposed) and RPC consumers can use these primitives to make decisions.

### PR DESCRIPTION
**Pull request by GabrielDav**
This closes #11613 
* Added ```from_me``` to ```listunspent``` and ```gettransaction```. This field indicates whether the source of the transaction was an address on the current node
* Added ```source``` query filter to ```listunspent```. Using this filter a user can list transactions from all sources (all), only from the current node (from_me) or from external sources (external)
* Added ```bip125-replaceable``` to ```listunspent```. This field indicates whether the transactions was marked as bip125-replaceable

### CODE REVIEW

**Comment by RHavar** [comment]
Concept ACK.

Nit: I think `from_me` should be a boolean not a string for `yes`|`no`.  I also think all the filtering stuff is a mess, and there's probably no point adding to it. Especially something like this is so easy to "client side" filter, I don't think there's really much gains by supporting it.  (But don't really care either way, just seems like more code)

**Comment by GabrielDav** [comment]
@RHavar 

> I think from_me should be a boolean not a string for yes|no

Yes, needs to be fixed. Confusion was caused by ```replaceable``` which can have non binary values.

>  I also think all the filtering stuff is a mess, and there's probably no point adding to it

I agree. However, there is no clear solution - either this needs to be marked as obsolete/to remove, or it needs to be updated when adding new output fields. Usually query is added when either:

- Data extraction have additional cost that can be reduced querying beforehand. This is not the case here since the data needed is already extracted before applying query.
- List is ever expanding. Again, this is not the case because list might change size depending on number of wallets and unused inputs. I would not expect this list to be too large to handle in the future.

It would be nice to get additional opinion and potentially create an issue to remove query parameters. But as it stands now the proper way to add new output fields is to add them in query as well to be consistent with intentions of this method.

**Comment by laanwj** [comment]
Needs rebase

**Comment by MarcoFalke** [comment]
Closing for now. Let me know when you want to continue working on this.

**Pull request closed without merging**
