### PR TITLE
net: Correct addrman logging

### PR DESCRIPTION
**Pull request by laanwj**
These were introduced in #9037.

Found by @theuni (https://github.com/bitcoin/bitcoin/pull/9037#pullrequestreview-101704656).

### CODE REVIEW

**Comment by promag** [comment]
utACK b4db76c.

**Comment by fanquake** [comment]
utACK b4db76c

**Comment by sdaftuar** [comment]
utACK b4db76c550c04957bc2721628f77bc24dce52f7f

**Comment by theuni** [comment]
post-merge utACK b4db76c550c04957bc2721628f77bc24dce52f7f

**Pull request merged**
