### PR TITLE
Enable (and check for) 64-bit ASLR on Windows

### PR DESCRIPTION
**Pull request by laanwj**
See #8248 for more information.

### CODE REVIEW

**Comment by laanwj** [comment]
Ugh, looks like the mingw64 ld on Trusty doesn't support this:
```
checking host system type... x86_64-w64-mingw32
...
checking whether the linker accepts -Wl,--high-entropy-va... no
```

```bash
user@trusty:~$ i686-w64-mingw32-ld --version
GNU ld (GNU Binutils) 2.23.52.20130620
Copyright 2013 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```
Minimum version would be binutils 2.25.

**Comment by luke-jr** [comment]
Maybe have configure check if this is supported, so it can be built both ways?

**Comment by laanwj** [comment]
> Maybe have configure check if this is supported, so it can be built both ways?

That's what the check_link_flag already does. It's just the security check that fails after the build.

**Comment by laanwj** [comment]
@theuni @luke-jr What if I change this to make the extra security check non-fatal, issue a warning for now?
This is still useful to have in the future if we ever get to the end of #8653 and the xenial mess cleaned up.
Otherwise I'm going to close it for now.

**Comment by theuni** [comment]
@laanwj ACK on making it non-fatal for now. Optimally with some kind of switch to elevate warnings to errors like -Werror. That way we could set it as a real error in gitian when it should be supported, even though we allow older toolchains to configure with warnings.

I'm still head-down in toolchain stuff, maybe we can have this turned on for 0.14.

**Comment by laanwj** [comment]
I split off the high entropy check and added this to the security-checks for now:
```
NONFATAL = {'HIGH_ENTROPY_VA'} # checks which are non-fatal for now but only generate a warning
```
I didn't find it worth the trouble to add a command-line option. The script can just be updated once we switch build platforms.

**Pull request merged**
