### PR TITLE
MOVEONLY: CWallet transaction code out of wallet.cpp/.h

### PR DESCRIPTION
**Pull request by ryanofsky**
This commit just moves function without making any changes. It can be reviewed with `git log -p -n1 --color-moved=dimmed_zebra`

Motivation for this change is to make `wallet.cpp/h` less monolithic and start to make wallet transaction state tracking comprehensible so bugs in https://github.com/bitcoin-core/bitcoin-devwiki/wiki/Wallet-Transaction-Conflict-Tracking can be fixed safely without introducing new problems.

This moves wallet classes and methods that deal with transactions out of `wallet.cpp/.h` into better organized files:

- `transaction.cpp/.h` - CWalletTx and CMerkleTx class definitions
- `receive.cpp/.h` - functions checking received transactions and computing balances
- `spend.cpp/.h` - functions creating transactions and finding spendable coins

After #20773, when loading is separated from syncing it will also be possible to move more `wallet.cpp/.h` functions to:

- `sync.cpp/.h` - functions handling chain notifications and rescanning

This commit arranges `receive.cpp` and `spend.cpp` functions in dependency order so it's possible to skim `receive.cpp` and get an idea of how computing balances works, and skim `spend.cpp` and get an idea of how transactions are created, without having to jump all over `wallet.cpp` where functions are not in order and there is a lot of unrelated code.

Followup commit "refactor: Detach wallet transaction methods" in https://github.com/bitcoin/bitcoin/pull/21206 follows up this PR and tweaks function names and arguments to reflect new locations. The two commits are split into separate PRs because this commit is more work to maintain and less work to review, while the other commit is less work to maintain and more work to review, so hopefully this commit can be merged earlier.

### CODE REVIEW

**Review by jonatack — COMMENTED** [review]
ACK 2a855bf0927908c7c1100ef763a44e3b82432c8f light verification of move-only and review of headers and makefile, local debug build and unit tests clean, the re-organisation choices of which code to move where look coherent

**Comment by ryanofsky** [comment]
This is from a hacky, stolen script[1], but here are commands that can be used verify the change is move only. It just prints all the lines that were NOT moved (comment lines and #include lines)

```bash
diff_lines=$(git diff HEAD^..HEAD | grep -v '^\(---\|+++\|@@ \)'| grep '^\([><] \)\|[+-]' | sed 's/^+/> /;s/^-/< /')
while IFS= read -r line || [ -n "$line" ]
do
    contents="${line:2}"
    count_removes="$(grep -cFxe "< $contents" <<< "$diff_lines" || true)"
    count_adds="$(grep -cFxe "> $contents" <<< "$diff_lines" || true)"
    test -z "$contents" || test "$count_removes" -eq "$count_adds" || echo "$line"
done <<< "$diff_lines"
```

[1] script stolen from https://github.com/l0b0/diff-ignore-moved-lines/blob/master/diff-ignore-moved-lines.sh

**Comment by ryanofsky** [comment]
Rebased 2a855bf0927908c7c1100ef763a44e3b82432c8f -> 01f4bb26935e431d44503a31006300196e0d1360 ([`pr/txmove.1`](https://github.com/ryanofsky/bitcoin/commits/pr/txmove.1) -> [`pr/txmove.2`](https://github.com/ryanofsky/bitcoin/commits/pr/txmove.2), [compare](https://github.com/ryanofsky/bitcoin/compare/pr/txmove.1-rebase..pr/txmove.2)) due to conflict with #16546

**Comment by ryanofsky** [comment]
Requesting concept ACKs for this PR! 

No are no code changes, only moves, so the review should be trivial. Also, this is easy for me to rebase, so if anyone is concerned about conflicts and wants this delayed until another change is merged, that is no problem. I'm going to try to review PRs on the conflict list https://github.com/bitcoin/bitcoin/pull/21207#issuecomment-780456462, but it'd be good to know if any PRs in particular are a concern!

**Comment by ryanofsky** [comment]
Rebased 74d45298e59dc15dd708c68bac502c12a5d93ab5 -> 7c188f3508cfca4cf4ca8bf3ca3b266b147bb854 ([`pr/txmove.3`](https://github.com/ryanofsky/bitcoin/commits/pr/txmove.3) -> [`pr/txmove.4`](https://github.com/ryanofsky/bitcoin/commits/pr/txmove.4), [compare](https://github.com/ryanofsky/bitcoin/compare/pr/txmove.3-rebase..pr/txmove.4)) due to conflict with #21083

**Comment by fanquake** [comment]
@achow101 @Sjors @instagibbs @Xekyo @meshcollider @S3RK do any of you have a (conceptual) opinion here?

**Comment by ryanofsky** [comment]
Rebased 7c188f3508cfca4cf4ca8bf3ca3b266b147bb854 -> a71a7db9a9eca72a391426acd8555d97980b018d ([`pr/txmove.4`](https://github.com/ryanofsky/bitcoin/commits/pr/txmove.4) -> [`pr/txmove.5`](https://github.com/ryanofsky/bitcoin/commits/pr/txmove.5), [compare](https://github.com/ryanofsky/bitcoin/compare/pr/txmove.4-rebase..pr/txmove.5)) due to conflict with #21467

**Comment by Sjors** [comment]
I'm always happy to see large files split up. Will give it some more thought.

**Comment by instagibbs** [comment]
I like the effort being put in, would have to think more about it before approach acking

**Comment by ryanofsky** [comment]
Note that commit 3e0a7ba411a01160aa411c7aa78f718c2feed056 from #21206 is the spiritual successor to this PR and I'll probably break it off from that PR if this one gets merged.

This PR does obvious high-level moves that can be trivially reviewed, and then that commit does tedious renames to reflect the moved-to locations.

Since I requested approach ACKS, I can summarize what the approach taken here was: Just starting from a big file full of functions, then moving groups of functions that call each other into smaller files. I put a lot of thought and effort into the moves, grouping related functions together while keeping the functions strictly sorted in dependency order within each file, avoiding any circular dependencies between files, and not changing any code at all. Things can move around freely after this, but I think the result is a great starting point for less monolithic and more comprehensible wallet code.

**Comment by S3RK** [comment]
I'm in favour of splitting big files/classes. Will take a closer look and come back with more thoughts

**Comment by S3RK** [comment]
> grouping related functions together while keeping the functions strictly sorted in dependency order within each file, avoiding any circular dependencies between files

This is an instrumental ground work, greatly appreciate the effort.

What I'm missing here is an ideal end state and #21206 doesn't help with this either. A purely procedural style as proposed in  3e0a7ba is fine as an intermediate state, but it's not good enough for the long run.

Let's take `CWallet::GetBalance` as an example for no particular reason. On the first look, it seems like it should stay in `CWallet` class IMHO. And in that case there is no need to move to `receive.cpp`. Of course, there are multiple ways to design this, so I'm curious how do you envision this.

Do you think a class diagram for an ideal final state would be useful here?

**Comment by ryanofsky** [comment]
re: https://github.com/bitcoin/bitcoin/pull/21207#issuecomment-823059685

Thanks for looking into this. 

> What I'm missing here is an ideal end state

The idea is instead of implementing all wallet functionality in one sprawling and disorganized class, CWallet, CWallet is just a collection of keys and transactions, and higher level functionality like spending, receiving, and syncing implemented on top of it separately. This PR and followup commit 3e0a7ba411a01160aa411c7aa78f718c2feed056 [refactor: Detach wallet transaction methods](https://github.com/bitcoin/bitcoin/commit/3e0a7ba411a01160aa411c7aa78f718c2feed056) which is currently part of #21206 achieve that goal, except for the syncing, and #15719 begins to address the syncing.

I'm not someone with strong opinions about object oriented style, but if you are interested in a justification for this approach the "Non-Member Functions Improve Encapsulation" idea https://www.drdobbs.com/cpp/how-non-member-functions-improve-encapsu/184401197, http://www.gotw.ca/gotw/084.htm could be helpful. #21207 and 3e0a7ba411a01160aa411c7aa78f718c2feed056 are just grouping related functions together instead mixing them up, though, so no need to get very lofty about them.

> A purely procedural style as proposed in [3e0a7ba](https://github.com/bitcoin/bitcoin/commit/3e0a7ba411a01160aa411c7aa78f718c2feed056) is fine as an intermediate state, but it's not good enough for the long run.

It doesn't matter to me if wallet spending, receiving, and syncing code is object oriented or procedural. Currently it's procedural code that's thrown into a giant class. The followup commit 3e0a7ba411a01160aa411c7aa78f718c2feed056 makes the procedural form more explicit, but there's nothing substantive about the commit, it's pure renaming.

> Let's take `CWallet::GetBalance` as an example for no particular reason. On the first look, it seems like it should stay in `CWallet` class IMHO. And in that case there is no need to move to `receive.cpp`. Of course, there are multiple ways to design this, so I'm curious how do you envision this.
> 
> Do you think a class diagram for an ideal final state would be useful here?

I don't have any objections to someone rewriting GetBalance code in an object oriented style, but I don't have plans to change GetBalance. I just want to consolidate it in `wallet/receive.cpp` so it's not scattered all over `wallet/wallet.cpp`.

**Comment by Sjors** [comment]
utACK a71a7db9a9eca72a391426acd8555d97980b018d

**Comment by promag** [comment]
Concept ACK, will review and #21206 again.

**Comment by S3RK** [comment]
@ryanofsky Thanks for the pointers and expanded explanation of your reasoning. I'm now convinced this a clear improvement.
Approach ACK, will do code review soon.

**Comment by ryanofsky** [comment]
> Approach ACK, will do code review soon.

Thanks all reviewers, and just a reminder using `--color-moved=dimmed_zebra` mentioned in the description should make this a lot easier to review and the moveonly verify script https://github.com/bitcoin/bitcoin/pull/21207#issuecomment-781538839 could also help as another check.

**Comment by ryanofsky** [comment]
Rebased 4984c4548cd3d6fb0296cad39bcec7ff3be7cd76 -> 264b945fa7f10b418d8acaeebe90c766789720c2 ([`pr/txmove.6`](https://github.com/ryanofsky/bitcoin/commits/pr/txmove.6) -> [`pr/txmove.7`](https://github.com/ryanofsky/bitcoin/commits/pr/txmove.7), [compare](https://github.com/ryanofsky/bitcoin/compare/pr/txmove.6-rebase..pr/txmove.7)) due to conflicts with #21359 and #21910

**Comment by Sjors** [comment]
re-utACK 264b945fa7f10b418d8acaeebe90c766789720c2

**Comment by ryanofsky** [comment]
Rebased 264b945fa7f10b418d8acaeebe90c766789720c2 -> ae93b95a6822be5360544b5c2bb6dacbd8d3b10d ([`pr/txmove.7`](https://github.com/ryanofsky/bitcoin/commits/pr/txmove.7) -> [`pr/txmove.8`](https://github.com/ryanofsky/bitcoin/commits/pr/txmove.8), [compare](https://github.com/ryanofsky/bitcoin/compare/pr/txmove.7-rebase..pr/txmove.8)) due to conflict with #17331

**Comment by practicalswift** [comment]
cr ACK ae93b95a6822be5360544b5c2bb6dacbd8d3b10d: dimmed zebra looks correct

**Review by promag — COMMENTED** [review]
ACK after rebase due to #22042.

**Comment by ryanofsky** [comment]
Rebased ae93b95a6822be5360544b5c2bb6dacbd8d3b10d -> c7bd5842e467c4fc286399379572bbdec6b26a4f ([`pr/txmove.8`](https://github.com/ryanofsky/bitcoin/commits/pr/txmove.8) -> [`pr/txmove.9`](https://github.com/ryanofsky/bitcoin/commits/pr/txmove.9), [compare](https://github.com/ryanofsky/bitcoin/compare/pr/txmove.8-rebase..pr/txmove.9)) due to conflicts with #22042 and #18418

**Review by promag — COMMENTED** [review]
Code review ACK c7bd5842e467c4fc286399379572bbdec6b26a4f, verified move only claim.

This is base for #21206 which IMO is an awesome change. Reviewers might want to check that to get motivation for this one.

**Comment by Sjors** [comment]
re-utACK c7bd5842e467c4fc286399379572bbdec6b26a4f

In case we want more review / concept ACKs: cc @achow101, @instagibbs, @fjahr

**Comment by fjahr** [comment]
utACK c7bd5842e467c4fc286399379572bbdec6b26a4f

I reviewed using `git show --color-moved=dimmed_zebra` and manually confirmed the few instances were git was acting funny with the diffs. Move-only confirmed.

**Review by meshcollider — COMMENTED** [review]
Dimmed-zebra-check and functional test run ACK c7bd5842e467c4fc286399379572bbdec6b26a4f

**Review by doianmai2020 — COMMENTED** [review]
.

**Pull request merged**
