### PR TITLE
fix incorrect file name bitcoin.qrc 

### PR DESCRIPTION
**Pull request by bitcoinsSG**
bitcoin.qrc does not contain any language manifest data as implied in sentence; fixed to point to correct file bitcoin_locale.qr

### CODE REVIEW

**Comment by jonasschnelli** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/8683/commits/df2d2e70cac8d15ecc30bc5c46930fd27c8afac0

**Comment by theuni** [comment]
This was moved long ago in 38e324af8693eb0c3d4bf22df9cbb73667f195ce, but not updated in the docs. Thanks.

ACK df2d2e70cac8d15ecc30bc5c46930fd27c8afac0

**Comment by bitcoinsSG** [comment]
@theuni np

**Comment by fanquake** [comment]
ACK df2d2e7

**Comment by laanwj** [comment]
Eh, yes.
This document is in dire need of an update anyhow: no one adds languages manually, the regexps under "Synchronising translations" is how it's actually done these days. 
But thanks, this was plainly incorrect.

**Pull request merged**
