### PR TITLE
Remove duplicate include

### PR DESCRIPTION
**Pull request by practicalswift**
Remove duplicate include.

Introduced in 5c643241e5d98992c0d5487b65e9c7b6d8005d1a.

### CODE REVIEW

**Comment by practicalswift** [comment]
Friendly ping @jnewbery :-)

**Comment by jnewbery** [comment]
Bah! Yes utACK. Thanks!

**Comment by fanquake** [comment]
utACK c53369c

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/commit/c53369cc24276b64b43636ae0868de9d41ca8b00

**Comment by TheBlueMatt** [comment]
utACK c53369cc24276b64b43636ae0868de9d41ca8b00

**Pull request merged**
