### PR TITLE
[Trivial] bitcoind: alias -h for -help

### LINKED ISSUE #6838: Alias `-h` with `--help`
As suggested in IRC,  I think this would be worthwhile.

### PR DESCRIPTION
**Pull request by dcousens**
Not sure if more than this is required.

Resolves https://github.com/bitcoin/bitcoin/issues/6838

### CODE REVIEW

**Comment by btcdrak** [comment]
utACK

**Comment by MarcoFalke** [comment]
Any reason not to do this for the other bitcoin binaries?

**Comment by paveljanik** [comment]
Is it `-help` (as in the commit) or `--help` (as in the PR title)?

**Comment by dcousens** [comment]
@paveljanik seems it is `-help`, but `--help` also works.

**Comment by laanwj** [comment]
> Any reason not to do this for the other bitcoin binaries?

Yes, if you do this, please do it everywhere where `-help` is accepted.

**Comment by dcousens** [comment]
@laanwj done.

**Comment by MarcoFalke** [comment]
utACK 3cb56f37780854bf26650e0872a556da25897a0a

**Comment by paveljanik** [comment]
tested ACK. Now all `bitcoind`, `bitcoin-cli` and `bitcoin-tx` accept `-h` as an argument.

**Comment by jmcorgan** [comment]
tested ACK

**Comment by laanwj** [comment]
ACK

**Pull request merged**
