### PR TITLE
Trivial: Corrected owner of DNS seeder

### PR DESCRIPTION
**Pull request by ayeowch**

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
utACK

**Comment by sandakersmann** [comment]
ACK

**Comment by theuni** [comment]
ACK for trivial. @ayeowch for the future, it'd be great if you could submit these directly to trivial-next in https://github.com/theuni/bitcoin . The idea is to pile up small changes like this one over there, to avoid burning extra review cycles in the main repo. Every few weeks those changes are then submitted as a group in a single PR for inclusion in master.

**Comment by ayeowch** [comment]
@theuni Thanks for the note. Will do that in the future.

**Comment by laanwj** [comment]
/me gives @fanquake a donkey hat, Not only you got sipa's name wrong, you here got the entire person wrong. Do your homework :)

**Comment by cdecker** [comment]
Ack, how did that happen in the first place? :-)

**Comment by sipa** [comment]
ACK

**Comment by laanwj** [comment]
Merged into the trivial branch, closing

**Pull request closed without merging**
