### PR TITLE
Add removeaddress RPC call (remove watch-only address)

### PR DESCRIPTION
**Pull request by paveljanik**
The current master has the feature to add watch-only addresses (RPC `importaddress`). There is no way to remove watch-only addresses (looks like the unwritten law to not remove/erase anything from the wallet ;-). This PR adds it. The RPC call is named `removeaddress`. It has only one argument, the address/script to be removed.

You can't remove the address you don't watch in the wallet, you can't remove the address with a privkey.

Problems/questions:
1. After the call, your walletdb contains transactions added by previous (optional) rescan of the call `importaddress`. I do not touch them, because you can always run `bitcoind -zapwallettxes=1` to get rid of them.
2. Qt GUI needs a small fix in `TransactionFilterProxy::filterAcceptsRow()`:

```
if(address.isEmpty())
    return false;
```

(or similar...) to not display these transactions after watch-only addresses are removed.
3. Qt GUI needs to auto-refresh the list of Recent transactions (the right tab on the main screen) because after `removeaddress` the list is not updated (watch-only transactions are still shown). Or you can restart GUI...
4. I do not remove the address from addressbook, because it could have been added even before adding it in `importaddress`.

### CODE REVIEW

**Comment by luke-jr** [comment]
What is the use case for this? Since watchonly really only works with complete wallets, I'm not sure it makes sense to remove addresses?

**Comment by paveljanik** [comment]
@luke-jr Imagine you are interested in watching some addresses. You ``importaddress`` them. After some time, you change your interest and want to stop watching some of them...

**Comment by luke-jr** [comment]
@paveljanik importaddress is designed for (and only works sanely for) watching an entire wallet by importing all of its addresses. It shouldn't be mixed in a normal wallet or used with just a single address or subset of a wallet, because that causes erratic results.

**Comment by Diapolo** [comment]
@luke-jr What you say causes problems is the thing I'mn doing, I imported a watch-only address into a "normal use" testing mainnet wallet...

**Comment by luke-jr** [comment]
@Diapolo Then you should be seeing arbitrary "send" transactions which have nothing to do with the address in question.

**Comment by paveljanik** [comment]
@luke-jr well, OK, but this is what we expect :-) We want to watch the added address... Such transactions should be marked as "watched" though.

**Comment by jonasschnelli** [comment]
needs rebase.

**Comment by laanwj** [comment]
Still needs rebase

**Comment by paveljanik** [comment]
Rebased.

**Comment by jgarzik** [comment]
Bug:  Needs to call EnsureWalletIsAvailable()

Otherwise, looks good to me, ut ACK modulo that issue.

**Comment by paveljanik** [comment]
... and LOCK needed IMO

```
LOCK2(cs_main, pwalletMain->cs_wallet);
```

Will rebase/test tomorrow.

**Comment by TheBlueMatt** [comment]
Needs rebase (again). Maybe needs a bit more of an interactive rebase because of the importaddress/importscript stuff related to the fundrawtransaction watch-only modifications. Sorry about that :/

**Comment by laanwj** [comment]
The rebase seems to be trivial.

> Would it not be recommended to have some tests in (a new rpc test script in qa/pull-tester/and maybe a test in rpc_wallet_tests.cpp)?

This does still need tests. Probably best option is to adapt one of the wallet RPC tests to exercise the call.

**Comment by paveljanik** [comment]
I'm sorry but I'm a bit distracted by other project these days :-(

**Comment by laanwj** [comment]
Are you still planning to do this, say, within the next weeks? Or would it be better to close for now until you can pick it up again?

**Comment by paveljanik** [comment]
I think we can close this and reopen later or anyone can pick up the work with your rebase. Closing.

**Pull request closed without merging**
