### PR TITLE
depends: Add missing -D_LIBCPP_DEBUG=1 to debug flags

### PR DESCRIPTION
**Pull request by maflcko**
Commands that can be used for testing:

```
$ cat 1.cpp 
#include <vector>

int main() {
  std::vector<int> foo;
  foo.begin() + 7;
}
```

```
clang++ -stdlib=libc++ -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC -D_LIBCPP_DEBUG=1 -Wall 1.cpp -o exe && ./exe  
g++                    -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC -D_LIBCPP_DEBUG=1 -Wall 1.cpp -o exe && ./exe

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Suggested by @guidovranken in https://github.com/google/oss-fuzz/issues/5713#issuecomment-833034501. Thanks!

**Comment by fanquake** [comment]
Concept ACK. https://libcxx.llvm.org/docs/DesignDocs/DebugMode.html.

**Comment by practicalswift** [comment]
cr ACK fa9249aaccc3ef7a0a91a822e1cb666c4c9716ec: patch looks correct

**Review by fanquake — APPROVED** [review]
ACK fa9249aaccc3ef7a0a91a822e1cb666c4c9716ec - was going to suggest adding this to the macOS CPP flags as well, however it seems doing that is less straight forward. Could be looked at by someone in a followup.

**Pull request merged**
