### PR TITLE
Remove wallet settings from chainparams

### PR DESCRIPTION
**Pull request by maflcko**
Feels a bit odd to have wallet setting in the chainparams, so remove them from there

### CODE REVIEW

**Comment by promag** [comment]
ACK fa4a605a4c611abe9af4c18aab20f4d1d039170f, missed s/2018/2019?

**Review by darosior — APPROVED** [review]
ACK fa4a605a4c611abe9af4c18aab20f4d1d039170f

**Comment by practicalswift** [comment]
utACK fa4a605a4c611abe9af4c18aab20f4d1d039170f

**Comment by MarcoFalke** [comment]
@jonasschnelli @jtimon, any objections on this? Otherwise I will merge.

**Review by meshcollider — COMMENTED** [review]
Seems sane, LGTM fa4a605a4c611abe9af4c18aab20f4d1d039170f

**Comment by jtimon** [comment]
I dislike using IsTestNet for many things, that was my worry when I complained in the PR it was introduced, but on the other hand I like to remove wallet stuff from chainparams.
I'm not really sure how I feel about this.
Will the bech32  and base58 prefixes do the same?

I guess I would like to hear more opinions about this.

**Comment by MarcoFalke** [comment]
>  Will the bech32 and base58 prefixes do the same?

I think they should stay because they are used even when no wallet is compiled, so they can be considered chain params. Though, chain-specific wallet default values, should, if needed, reside in `./src/wallet/chainparams`. Otherwise they will make it harder to move the wallet to a separate repository, since both repos would have to be kept perfectly in sync with regard to the settings.

**Comment by jtimon** [comment]
I understand the desire to decouple from the wallet, but the more I think about this, the less I like it.
Now IsTestNet serves for two quite unrelated things. If it was WalletIsTestnet separated from the other one, perhaps it would be better.
Let's say we want regtest to be more like mainnet with respect to the fallback fee, like it happened with the default for acceptnonstdtxs in https://github.com/bitcoin/bitcoin/pull/15891.
Then we would need to reintroduce m_fallback_fee_enabled or, even worse, introduce an IsRegtest method that ends up being used for all kinds of things.
For decoupling the wallet part of the chainparams, gaving a src/wallet/chainparams sounds like the long term solution. Or perhaps we can simply have the same defaults for mainnet and the test chains for wallet arguments, since testers can set them to whatever they want manually anyway. Perhaps the extra complexity is not worth it in this case.
Either way, I don't see how this helps towards that goal of separating the wallet.

**Comment by MarcoFalke** [comment]
`m_fallback_fee` only exists for testing, if it is deemed that the value should be the same for mainnet, the whole fallback fee logic can be removed instead.

**Comment by jtimon** [comment]
What about doing https://github.com/bitcoin/bitcoin/pull/16524 ?
That's what I think help the most decoupling wallet and chainparams from each other.
I think the same default as for mainnet should be used, which in practice is currently 0 despite what the constant says. I don't understand why have different defaults for different chains when they're just defaults that can be manually set by the user, or in a config file where I think they truly belong. Much less now that we have sections.

**Pull request merged**
