### PR TITLE
p2p: periodically clear m_addr_known

### PR DESCRIPTION
**Pull request by sdaftuar**
We use a rolling bloom filter to track which addresses we've previously sent a peer, but after #7125 we no longer clear it every day before our own announcement.  This looks to me like an oversight which has the effect of reducing the frequency with which we actually self-announce our own address, so this reintroduces resetting that filter.

### CODE REVIEW

**Comment by sipa** [comment]
Concept ACK on resetting on relay.

Your second commit seems to be identical to #19763 (unclear what the status is there, but there was some interesting discussion earlier).

**Comment by sdaftuar** [comment]
@sipa Thanks, I missed that PR.  I'll drop my second commit and let the discussion continue in #19763.

**Comment by naumenkogs** [comment]
I was aware of this issue, but I was never sure whether it's intended or not...
I guess your reasoning makes sense, especially considering stuff happened in #7125.

Even if non-clearing somehow gave us extra security, it was probably a side-effect, because it was never documented.
I also tried to break AddrMan many times, and but that never has anything to do with the freshness of m_addr_known.

At most what an attacker gets here is easier noticing *when* we roll the filter precisely.
But I don't think timing this activity gives any significant advantage to an attacker.

ACK 65273fa0e74f0c11dfbf0645dd962bdc779ea558

**Comment by laanwj** [comment]
Code review ACK 65273fa0e74f0c11dfbf0645dd962bdc779ea558

**Comment by sipa** [comment]
utACK 65273fa0e74f0c11dfbf0645dd962bdc779ea558

**Pull request merged**
