### PR TITLE
[rpc] deriveaddresses: add range to CRPCConvertParam

### PR DESCRIPTION
**Pull request by Sjors**
Missing from #15497

### CODE REVIEW

**Comment by Sjors** [comment]
The linter caught a related mistake in `CRPCCommand`, so I fixed that as well.

**Comment by MarcoFalke** [comment]
ACK 9586157c0f9c12d3cfa55926ccc6c022324fa60a

Before:

```
$ ./src/bitcoin-cli -named deriveaddresses descriptor="wpkh(tprv8ZgxMBicQKsPd7Uf69XL1XwhmjHopUGep8GuEiJDZmbQz6o58LninorQAfcKZWARbtRtfnLcJ5MQ2AtHcQJCCRUcMRvmDUjyEmNUWwx8UbK/1/1/*)#kft60nuy" range=3
error code: -8
error message:
Unknown named parameter range
```

After:

```
$ ./src/bitcoin-cli -named deriveaddresses descriptor="wpkh(tprv8ZgxMBicQKsPd7Uf69XL1XwhmjHopUGep8GuEiJDZmbQz6o58LninorQAfcKZWARbtRtfnLcJ5MQ2AtHcQJCCRUcMRvmDUjyEmNUWwx8UbK/1/1/*)#kft60nuy" range=0
[
  "bcrt1qjqmxmkpmxt80xz4y3746zgt0q3u3ferr34acd5"
]
```

**Comment by fanquake** [comment]
utACK 9586157

**Comment by Sjors** [comment]
```
$ bitcoin-cli -named deriveaddresses descriptor="wpkh(tprv8...bK/1/1/*)#kft60nuy" range=3
```

TIL how to use named params...

**Comment by promag** [comment]
utACK 9586157.

**Comment by laanwj** [comment]
utACK 9586157c0f9c12d3cfa55926ccc6c022324fa60a

**Pull request merged**
