### PR TITLE
ci: Use python 3.7 on Windows Github Actions

### PR DESCRIPTION
**Pull request by maflcko**
This mirrors the appveyor config https://github.com/bitcoin/bitcoin/blob/7da9e3a8171f976a9e01ee55ab9fe79bd1f033d1/.appveyor.yml#L10 and is needed for PEP 540

### CODE REVIEW

**Comment by sipsorcery** [comment]
I have a feeling I checked this already and that the GitHub Actions Windows images uses Python 3.7 by default. 

I dumped the environment variables in one of my runs. I'll track it down and report back.

**Comment by MarcoFalke** [comment]
My testing concluded otherwise, by default 3.6 is used:

```
  python test\functional\test_runner.py --ansi --ci --quiet --combinedlogslen=4000 --failfast --exclude feature_fee_estimation
  shell: C:\windows\system32\cmd.EXE /D /E:ON /V:OFF /S /C "CALL "{0}""
  env:
    PYTHONUTF8: 1
    QT_DOWNLOAD_URL: https://github.com/sipsorcery/qt_win_binary/releases/download/v1.4/Qt5.9.8_x64_static_vs2019.zip
    QT_DOWNLOAD_HASH: f285cbb02bec3b3f3cc2621e3fa7d5edf0d6a66fa30c57859e583acda954ea80
    QT_LOCAL_PATH: C:\Qt5.9.8_x64_static_vs2019
    VCPKG_INSTALL_PATH: $env:VCPKG_INSTALLATION_ROOT/installed
    PLATFORM: x64
--- Logging error ---
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\logging\__init__.py", line 996, in emit
    stream.write(msg)
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u20bf' in position 127: character maps to <undefined>

**Comment by sipsorcery** [comment]
Yes it's 3.6:

`PYTHON_HOME=C:/hostedtoolcache/windows\Python\3.6.8\x64`

Using 3.7 sounds good to me. Don't know if it's present in the image though?

**Comment by MarcoFalke** [comment]
For reference this is the ci run: https://github.com/MarcoFalke/bitcoin-core/commit/fabd5b444ef83b5cd0d63b33bbf6ea4e7557d0eb/checks and I expect it to pass

**Review by sipsorcery — APPROVED** [review]

**Comment by sipsorcery** [comment]
tACK fabd5b444ef83b5cd0d63b33bbf6ea4e7557d0eb.

**Comment by laanwj** [comment]
ACK fabd5b444ef83b5cd0d63b33bbf6ea4e7557d0eb

**Pull request merged**
