### PR TITLE
[WIP] contrib: Remove distribution packaging

### PR DESCRIPTION
**Pull request by laanwj**
This has been moved to a separate repository, https://github.com/bitcoin-core/packaging

TODO need to find a distribution agnostic place, (somewhere under `share`?) for:
- [ ] `assets-attribution` (../contrib/debian/copyright)
- [ ] example configuration file `contrib/debian/examples/bitcoin.conf`

### CODE REVIEW

**Comment by flack** [comment]
Just did a quick search for `contrib/debian`, and it's still referenced and these files:

https://github.com/bitcoin/bitcoin/blob/master/doc/assets-attribution.md
https://github.com/bitcoin/bitcoin/blob/master/doc/init.md
https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md

These should probably be updated here as well. Also, https://github.com/bitcoin/bitcoin/blob/master/Makefile.am contains a reference to `contrib/rpm`, not sure if that's a problem

**Comment by laanwj** [comment]
@flack thanks, yes, those should be updated as well

**Comment by laanwj** [comment]
According to @thebluematt it's out of date half of the time anyway. If it's not kept in sync with releases there's no reason to keep it in the main repository.

> especially since the debian/ dir has things useful in general.

In that case, make sure it's moved somewhere else. 

I agree that we've salvaged generally useful parts from there before (though at least the man-pages had license issues preventing that), but for something that is useful in general, a distribution-packaging specific directory is not the place.

**Comment by MeshCollider** [comment]
Concept ACK

**Comment by practicalswift** [comment]
Concept ACK

**Comment by MarcoFalke** [comment]
Re "assets-attribution":

We are only talking about qt stuff in `./src/qt/res` and `share/pixmaps/`, so I think it is fine to just amend the Readme in those folders to include the copyright notices. (This way we don't have to do it a third time, when the gui is moved out of this repo)

**Comment by MarcoFalke** [comment]
Needs rebase and feedback addressed

**Comment by MarcoFalke** [comment]
See #13809

**Pull request closed without merging**
