### PR TITLE
gitian-keys: add darosior's key

### PR DESCRIPTION
**Pull request by darosior**
As per https://github.com/bitcoin-core/gitian.sigs/issues/1427

### CODE REVIEW

**Comment by laanwj** [comment]
Thanks, I chedked that the key fingerprint `590B7292695AFFA5B672CBB2E13FC145CD3F4304` matches what is used to sign gitian releases.

Same as for #20846: I've been unable to get this key from keyservers, do you have it published somehwere?

**Comment by darosior** [comment]
It should be at hkps://keys.openpgp.org and hkps://keyserver.ubuntu.com:443 (checking the other ones in my gpg.conf now).
I can probably dump it in --armor in the commit message ?

**Comment by MarcoFalke** [comment]
> It should be at hkps://keys.openpgp.org

You'll need to verify your email with them to make it downloadable, I think

**Comment by laanwj** [comment]
> EDIT 2: Added it in the commit message too.

I think putting it in the commit message is a good idea, though, I wouldn't clearsign the exported public key with the key itself. It seems a bit like putting scissors in a package that needs scissors to open 🙂

**Comment by michaelfolkson** [comment]
Is this is a case of the more the better with Gitian keys? Or are we happy with the number of these post merging this?

**Comment by fanquake** [comment]
> Is this is a case of the more the better with Gitian keys? Or are we happy with the number of these post merging this?

This is a case of people who have been regularly performing gitian builds adding their keys to this file. See https://github.com/bitcoin-core/gitian.sigs/issues/1427.

**Comment by darosior** [comment]
Rebased

**Review by fanquake — APPROVED** [review]
ACK d825a3957ee317c74147611a7791193438f0e53c

**Pull request merged**
