### PR TITLE
0.18: Backport "Add -ignorepartialspends to list of ignored wallet options"

### PR DESCRIPTION
**Pull request by maflcko**
First run clang-format on the wallet options list (review with `--word-diff-regex=.`). This is not a backport.

Then backport Github-Pull: #15913

### CODE REVIEW

**Comment by luke-jr** [comment]
What is the reason for not doing a backport of the first commit?

**Comment by Empact** [comment]
@luke-jr could certainly see  applying a script to the file would be easier and more failsafe than rebasing the commit.

**Comment by promag** [comment]
ACK 106471d.

**Comment by laanwj** [comment]
ACK /106471d0d710a957280c36862df222657ace17f5

**Comment by curtcurt380** [comment]
I need help I don't understand nothing going on. I don't  know how to find my wallets, I dont understand what a node is?, I don't understand please help me thank .

**Comment by Empact** [comment]
> I need help I don't understand nothing going on. I don't know how to find my wallets, I dont understand what a node is?, I don't understand please help me thank .

@curtcurt380 this isn't the place for user support. I would suggest looking into [the docs on bitcoin.org](https://bitcoin.org/en/resources#learn), starting with the [FAQ](https://bitcoin.org/en/faq).

If you can't get your bearings there, I'd reach out to one of the [online user communities](https://bitcoin.org/en/community) for help. [r/bitcoin](https://www.reddit.com/r/Bitcoin/) has a lot of helpful people.

**Pull request merged**
