### PR TITLE
build: Add missed definition for `AM_OBJCXXFLAGS`

### PR DESCRIPTION
**Pull request by hebasto**
This PR adds the missed definition for `AM_OBJCXXFLAGS` which has the same value as `AM_CXXFLAGS`.

Otherwise, the compiling flags used by Objective C++ (for `.mm` source files) differ from C++ ones including hardening, debug, warning etc options.

### CODE REVIEW

**Comment by fanquake** [comment]
```bash
   CXX      qt/libbitcoinqt_a-moc_bitcoin.o
qt/macnotificationhandler.mm:27:9: error: 'NSUserNotification' is deprecated: first deprecated in macOS 11.0 - All NSUserNotifications API should be replaced with UserNotifications.frameworks API [-Werror,-Wdeprecated-declarations]
        NSUserNotification* userNotification = [[NSUserNotification alloc] init];
        ^
/Applications/Xcode_15.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUserNotification.h:24:12: note: 'NSUserNotification' has been explicitly marked deprecated here
@interface NSUserNotification : NSObject <NSCopying> {
           ^
qt/macnotificationhandler.mm:27:50: error: 'NSUserNotification' is deprecated: first deprecated in macOS 11.0 - All NSUserNotifications API should be replaced with UserNotifications.frameworks API [-Werror,-Wdeprecated-declarations]
        NSUserNotification* userNotification = [[NSUserNotification alloc] init];
                                                 ^
/Applications/Xcode_15.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUserNotification.h:24:12: note: 'NSUserNotification' has been explicitly marked deprecated here
@interface NSUserNotification : NSObject <NSCopying> {
           ^
qt/macnotificationhandler.mm:30:11: error: 'NSUserNotificationCenter' is deprecated: first deprecated in macOS 11.0 - All NSUserNotifications API should be replaced with UserNotifications.frameworks API [-Werror,-Wdeprecated-declarations]
        [[NSUserNotificationCenter defaultUserNotificationCenter] deliverNotification: userNotification];
          ^
/Applications/Xcode_15.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUserNotification.h:118:12: note: 'NSUserNotificationCenter' has been explicitly marked deprecated here
@interface NSUserNotificationCenter : NSObject {
           ^
3 errors generated.
```

**Comment by theuni** [comment]
This warning seems legitimate. Looks to me like we should modernize this code rather than ignoring it, no?

**Comment by hebasto** [comment]
> This warning seems legitimate. Looks to me like we should modernize this code rather than ignoring it, no?

It is Qt 5 code base. I did not check it out, but I hope Qt 6 dropped using of a deprecated API.

**Comment by theuni** [comment]
> > This warning seems legitimate. Looks to me like we should modernize this code rather than ignoring it, no?
> 
> It is Qt 5 code base. I did not check it out, but I hope Qt 6 dropped using of a deprecated API.

I don't understand what you mean. From what @fanquake pasted above, It's in our `macnotificationhandler.mm`. A quick google says that we should switch to the `UserNotifications.frameworks API` instead. What part of this is qt specific?

Or are there warnings other than those 3?

**Comment by fanquake** [comment]
I just had a look, and anyone compiling on macOS, with Qt 6.6.1, will still see these exact same deprecation warnings. So this isn't solved by Qt 6.

**Review by epiccurious — APPROVED** [review]

**Comment by epiccurious** [comment]
utACK 2fb758da581b5cefcc0232e1b40f13143ad2bdaf

**Comment by theuni** [comment]
@epiccurious What specifically are you ACKing here? Have you read the conversation above?

**Comment by hebasto** [comment]
> This warning seems legitimate. Looks to me like we should modernize this code rather than ignoring it, no?

Last [time](https://github.com/bitcoin-core/gui/issues/112) I tried to replace `NSUserNotificationCenter` with `UNUserNotificationCenter` on macOS 10.15, I got the authorization error "Notifications are not allowed for this application".

Now, the minimum supported macOS is 11.0. So it might be worth trying once more.

> > It is Qt 5 code base. I did not check it out, but I hope Qt 6 dropped using of a deprecated API.
> 
> I don't understand what you mean. From what @fanquake pasted above, It's in our `macnotificationhandler.mm`. A quick google says that we should switch to the `UserNotifications.frameworks API` instead. What part of this is qt specific?

I was waiting when Qt does the same replacement to prove that this is a thing. Alas. See [QTBUG-110998](https://bugreports.qt.io/browse/QTBUG-110998).

**Comment by fanquake** [comment]
I guess mark as draft or something else for now then? This can't be merged as-is, because the comments in the config of files are not correct.

**Comment by hebasto** [comment]
> the comments in the config of files are not correct.

Comments have been adjusted.

**Comment by fanquake** [comment]
NACK -  this currently disables compiler warning output in the CI for an entire release platform, rather than fixing GUI code? Not sure that is the right tradeoff.

**Comment by fanquake** [comment]
Opened an alternative in #29577.

**Comment by hebasto** [comment]
> Opened an alternative in #29577.

Closing in favour of #29577.

**Pull request closed without merging**
