### PR TITLE
util: Make `BResult` error a generic type instead of only `bilingual_str`

### PR DESCRIPTION
**Pull request by w0xlt**
This PR makes `BResult` error a generic type instead of only `bilingual_str` and changes the class name to `StructuredResult` as `BResut` is not related to the purpose of the class.

The motivation is that some methods, like `src/wallet/wallet.h:{RestoreWallet(...),CreateWallet(...),LoadWallet(...)}` have more output parameters than just `bilingual_str& error` such as `DatabaseStatus& status` and `std::vector<bilingual_str>& warnings`.

With a generic template for error, it will be possible to create a struct that has `bilingual_str& error` and `DatabaseStatus& status`, for example, and use it in `StructuredResult`.

Built on top of #25594

### CODE REVIEW

**Comment by ryanofsky** [comment]
The current `BResult` class is definitely very crippled, and needs to be improved to return real error handling information, not just an error reporting string.

Ironically the original implementation #25218 that had `T m_result;` and `std::optional<bilingual_str> m_error` members was not crippled, and was perfectly capable of returning rich error handling information. But after that (against all rationality!) the implementation was changed to use a `std::variant` so no information about the error could be returned other than the reporting string.

This PR (as of 09b796a7c7f62e1d24f7b173825b7dd4409e91b4) adds back the ability to return structured error handling information, but it loses the ability to return standard error reporting information. So it is one step forward, one step backwards, IMO.

I think a better solution is possible that:
- adds back ability to return arbitrary data for error handling (like this PR)
- doesn't drop the standard error reporting format, which I think we can expand and build more utilities around for more complete reporting and less boilerplate (unlike this PR)
- doesn't require changing existing BResult usages (unlike this PR)

I had started writing up a version of this today built on #25308. Will try to post in the next few days and we can compare notes.

**Comment by ryanofsky** [comment]
Would add I don't think iterations on the `BResult` class should hold up either PR #25594 or #25308. I think both PR's are in a good state and would be good to merge when they have enough review.

**Comment by w0xlt** [comment]
@ryanofsky in https://github.com/bitcoin/bitcoin/pull/25601/commits/28c81d7317b248c7a0b6ee1b4cef4b822a5e4286, I added the `class SingeErrorResult` meets all the all the requirements you mentioned:

* adds back ability to return arbitrary data for error handling (it is a class derived from `StructuredResult`).
* doesn't drop the standard error reporting format (`SingeErrorResult() : StructuredResult<T, bilingual_str>(Untranslated("")) {}`).
* doesn't require changing existing BResult usages (except for the name change, this keeps the same `BResult` usage).

**Comment by ryanofsky** [comment]
Thanks! Glad to see this (as of 696f9536556f78698cc82c64515fa8b1e0b01ef5) adding back a standard type for error reporting.

I do think there are still some issues here. The main one is that I don't see a point to the `StructuredResult<S, E>` class. The class doesn't have any functionality, and is just a nonstandard wrapper around a `std::variant<std::monostate, E, S>` field. I can't imagine code that could use `StructuredResult<S, E>` that wouldn't be better off using `std::optional<E>` or `std::variant<S, E1, E2, ...>` avoiding the need to nest multiple error types in single error type, or call nonstandard `HasRes` `GetObj` methods, or deal with impossible null states.

Also think it would be better to standardize on an error reporting class that can return multiple errors and warnings (and optionally format the result as a single error) than a class that can only return one error. Draft PR #25608 is a little rough but starts to go in this direction.

**Comment by w0xlt** [comment]
Closing this in favor of https://github.com/bitcoin/bitcoin/pull/25721.

**Pull request closed without merging**
