### PR TITLE
Add pixmaps for testnet and regtest

### PR DESCRIPTION
**Pull request by eklitzke**
I am trying to build an RPM that ships .desktop files to run bitcoin-qt in testnet and regtest modes, respectively. This requires color shifted pixmaps to get the green/blue logos for testnet and regtest, respectively. These pixmaps are used by GNOME, KDE, and other Linux WMs to provide an actual application launcher icon.

This PR includes the pixmaps I generated, as well as the script I used to create the pixmaps. The script requires the `convert` command provided by GraphicsMagick. I think it makes sense to check these assets in for ease of distribution.

### CODE REVIEW

**Comment by laanwj** [comment]
I think you need to update `makefile.am` so that these are installed?

**Comment by promag** [comment]
Move the script to a different commit?

**Comment by laanwj** [comment]
Ping @eklitzke ^^

**Comment by laanwj** [comment]
Closing this for now - let me know if you start work on this again (there are some unresolved comments) and I'll reopen.

**Comment by ryanofsky** [comment]
Could add [up for grabs](https://github.com/bitcoin/bitcoin/issues?q=label%3A%22Up+for+grabs%22) tag in case someone wants to resume work.

**Pull request closed without merging**
