### PR TITLE
test, bugfix: fix intermittent failure in getrawtransaction_tests

### LINKED ISSUE #23991: rpc_rawtransaction.py issue
https://github.com/bitcoin/bitcoin/pull/22437/files#r779593489

### PR DESCRIPTION
**Pull request by jonatack**
Easiest to review with `colorMoved = dimmed-zebra` and `colorMovedWs = allow-indentation-change`.

Resolves #23991

### CODE REVIEW

**Comment by jonatack** [comment]
@rajarshimaitra I added your commit from #22437 here.

**Comment by MarcoFalke** [comment]
would it be possible to create a separate bugfix pr from the refactor pr to allow easier backporting/cherry-picking

**Comment by jonatack** [comment]
> would it be possible to create a separate bugfix pr from the refactor pr to allow easier backporting/cherry-picking

Sure, done here. Will open the refactor pull afterward.

**Comment by jonatack** [comment]
Thanks @MarcoFalke.

**Comment by jonatack** [comment]
> --ignore-all-space -U8 --color-moved=dimmed-zebra --color-moved-ws=ignore-all-space

Much better, noted, thanks!

**Pull request merged**
