### PR TITLE
Mention that PPA doesn't support Debian

### PR DESCRIPTION
**Pull request by anduck**
Mention that PPA doesn't support Debian and how to fix it for Debian.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
I'm not sure if PPAs are meant to be used in debian and I guess we should not encourage doing so in the docs.

**Comment by TheBlueMatt** [comment]
NACK. This is very bad practice and will likely result in broken deps, at a minimum.

**Comment by Michagogo** [comment]
694615

**Comment by Michagogo** [comment]
Erm, no, that was a TOTP. I meant to say, https://wiki.debian.org/DontBreakDebian

And of course GH mobile doesn't allow comment editing or deleting...

**Comment by anduck** [comment]
Then it should be explicitly stated that the PPA is for Ubuntu only. It is currently very confusing, and the commands also work for both Ubuntu and Debian distros.

**Comment by TheBlueMatt** [comment]
Indeed, feel free to update this to just mention that the PPA does not support Debian.

**Comment by MarcoFalke** [comment]
Squashed the commits.

**Comment by MarcoFalke** [comment]
utACK b55d823

**Comment by btcdrak** [comment]
utACK

**Pull request merged**
