### PR TITLE
bench: Amend mempool_eviction test for witness txs

### PR DESCRIPTION
**Pull request by maflcko**

### CODE REVIEW

**Comment by laanwj** [comment]
Makes sense - utACK fa3bb183adaf086a70fbbe2bb1981f471a3281ce

**Comment by MarcoFalke** [comment]
Just for reference a plot of the benchmark results:

* The first commit (which obviously makes the loop faster by moving stuff out)
* The second commit (which makes slower due to witness)
* tag of version 0.16.0 for reference

mempooleviction

**Comment by MarcoFalke** [comment]
@ryanofsky Any notes here, since you wrote the inital benchmark?

**Review by ryanofsky — COMMENTED** [review]
utACK fa3bb183adaf086a70fbbe2bb1981f471a3281ce. I believe original benchmark was mostly a copy and paste of other test code.

**Pull request merged**
