### PR TITLE
Change bundle identifiers

### PR DESCRIPTION
**Pull request by btcdrak**

### CODE REVIEW

**Comment by laanwj** [comment]
Can these just be changed, or is this bound to the signing key somehow?
Ping @theuni

**Comment by theuni** [comment]
Grr, I looked into all of this at one point, but didn't document. I'll do so again, this time documenting what we can change at-will, and what would break packaging assumptions.

**Comment by jonasschnelli** [comment]
This would break code signing with the current key (the current certificate is tied to the bundle identifier).

**Comment by laanwj** [comment]
Ok, closing for now, can be reopened if the underlying issue is solved (e.g. switched to a different cert)

**Pull request closed without merging**
