### PR TITLE
openssl: avoid config file load/race

### LINKED ISSUE #6436: Core dumped when running with -prune=N option
I couldn't reproduce this again, but I'll post it in case it helps. Feel free to close the issue if not useful.

I just installed v0.11.0 and ran it with the following config:
```
rpcuser=user
rpcpassword=pass

server=1
txindex=1
```
I then wanted to test the new `-prune=N` option, so I ran:
```sh
$ ./bitcoin-qt -testnet -prune=2048
```
I got a UI error saying `-txindex` is incompatible with `-prune`, so I went and deleted the `txindex=1` line from my config. When I ran it again I got:

```sh
$ ./bitcoin-qt -testnet -prune=2048
Auto configuration failed
139732253796224:error:02001002:system library:fopen:No such file or directory:bss_file.c:169:fopen('/home/ubuntu/build/bitcoin/depends/x86_64-unknown-linux-gnu/etc/openssl/openssl.cnf','rb')
139732253796224:error:2006D002:BIO routines:BIO_new_file:system lib:bss_file.c:174:
139732253796224:error:0E078002:configuration file routines:DEF_LOAD:system lib:conf_def.c:199:
bitcoin-qt: /home/ubuntu/build/bitcoin/depends/x86_64-unknown-linux-gnu/include/boost/thread/pthread/recursive_mutex.hpp:110: void boost::recursive_mutex::lock(): Assertion `!pthread_mutex_lock(&m)' failed.
Aborted (core dumped)
```
Here's my debug.log file for today: http://pastebin.com/n90GTrmY (filtered with `cat 2015-07-14-debug.log | grep -v 'UpdateTip'`)
When I ran it again, it worked. I wasn't able to reproduce this behavior again. Any other info I can provide?

### PR DESCRIPTION
**Pull request by theuni**
Should fix #6436. See [here](https://wiki.openssl.org/index.php/Library_Initialization#OPENSSL_config) for more info. Also [the source](https://github.com/openssl/openssl/blob/OpenSSL_1_0_0-stable/crypto/conf/conf_sap.c) is self-explanatory.

Since we don't use any loadable functionality, I don't see how this could hurt. Presumably qt tries to load available modules, but the fallbacks should always work.

One last data point: The depends build is trying to load `/home/ubuntu/build/bitcoin/depends/x86_64-unknown-linux-gnu/etc/openssl/openssl.cnf` which obviously won't be found in the end-user's environment. So this functionality has actually been disabled for a long time anyway.

### CODE REVIEW

**Comment by laanwj** [comment]
utACK, also needs backport to 0.11.

**Comment by jonasschnelli** [comment]
Fixes https://github.com/bitcoin/bitcoin/issues/6436

**Comment by paveljanik** [comment]
ACK

**Comment by jonasschnelli** [comment]
utACK

**Comment by laanwj** [comment]
Backported to 0.11 as 253143860da9983d127251814f0665a5454e5030

**Comment by laanwj** [comment]
Bacported to 0.10 as d4b1d5a8baf18e4c8d62846360c0c1c0c9331d70

**Pull request merged**
