### PR TITLE
doc: move gitian building to external repo

### PR DESCRIPTION
**Pull request by maflcko**
The guide was moved to [the Bitcoin Core documentation repository](https://github.com/bitcoin-core/docs/blob/master/gitian-building.md).

It now includes not only instructions to run on a debian host, but also on
any recent fedora host. 

This is an ongoing effort to reduce the fraction caused by incoming
pull requests to docs (usually fixups, typo fixes, version bumps).

This is especially important for documentation that is independent
of any release cycles and should thus be up-to-date regardless
of a tag on a non-master branch.

Finally, fetching a shallow copy of the source is less heavy,
as many binary png files are moved out of the repo.

### CODE REVIEW

**Comment by promag** [comment]
> Finally, fetching the source code of the current HEAD is less heavy, as many binary png files are moved out of the repo.

You mean downloading an archive?

**Comment by MarcoFalke** [comment]
Jup, or fetching with `--depth` specified, which will fetch a shallow copy.

**Comment by fanquake** [comment]
I'm not completely in favour of this, now the instructions to reproducibly build are no longer available with the code your downloading.

I also don't really agree that these are instructions that are "independent of any release cycles". I've occasionally gone back to a historic branch, knowing that the gitian build instructions in that branch will work with that code. Separating the instructions and keeping them updated to only build the latest version of the code means that'll no longer be the case (maybe that doesn't matter).

Regardless, you'll need to update the link under [Building](https://github.com/bitcoin/bitcoin/blob/master/doc/README.md#building) in the main readme.
You should also remove the partial gitian build instructions [here](https://github.com/bitcoin/bitcoin/tree/master/contrib/gitian-descriptors).

**Comment by MeshCollider** [comment]
@fanquake note that the instructions for gitian building are still in the release-process.md, only the instructions to set up the gitian building VM is moving

**Comment by fanquake** [comment]
Right, I guess I always thought of them as being the same thing. In that case, this PR should be updating some docs somewhere here to point to the new home of the guide, maybe in release-process? Otherwise anyone reading that doc gets no indication there is a whole other setup process involved.

**Comment by laanwj** [comment]
utACK 

I agree that having a documentation repository for "heavy" guides like this is a good idea. This also this means not having to carry the images, and most importantly updates to the images in the future.

> In that case, this PR should be updating some docs somewhere here to point to the new home of the guide, maybe in release-process?

The file itself contains a link to the new location. Possibly this could be extended to places that link the file, which would save a step, though I have no strong opinion about that.

**Pull request merged**
