### PR TITLE
doc: Combine 23.0 release notes

### PR DESCRIPTION
**Pull request by maflcko**
`doc/release-notes-remove-rescan.md` didn't include a `(#pull_nr)`, so fix that and also combine the notes while touching them.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Can be reviewed with `--color-moved=dimmed-zebra --color-moved-ws=ignore-all-space`.

**Review by shaavan — APPROVED** [review]
ACK fad5a185488ff2937071860877df00aae52548f1

**Comment by katesalazar** [comment]
Had only a look without optimizing for moves,
yet it seems simple and without flaw. ACK.

**Review by fanquake — APPROVED** [review]
ACK fad5a185488ff2937071860877df00aae52548f1

**Pull request merged**
