### PR TITLE
Make it clear which functions that are intended to be translation unit local

### PR DESCRIPTION
**Pull request by practicalswift**
Make it clear which functions that are intended to be translation unit local.

Do not share functions that are meant to be translation unit local with other translation units. Use internal linkage for those consistently.

### CODE REVIEW

**Comment by sipa** [comment]
utACK c3f34d06befa352acb343ad08337123d9474535f

All this does is add `static` declarations to functions; if it compiles, it should be correct.

**Comment by laanwj** [comment]
Concept ACK - indeed, not exposing unnecessary symbols is good, it can speed up linking, and also allows the compiler to be smarter with inlining.

Can we somehow verify that you got them all? In C, we'd use `-Wmissing-prototypes` but compilers don't tend to support that for C++.

**Comment by promag** [comment]
utACK c3f34d0.

@laanwj better than that would be a check to detect unnecessary symbols in future PRs?

**Comment by practicalswift** [comment]
This is how I created this PR:

I wrote a dumb three-line `bash` script which generated a candidate list of 463 functions that appeared to be lacking `static` despite appearing being translation unit local.

I manually checked those 463 functions and removed the ones that were false positives. The remaining 226 functions were changed.

**Comment by laanwj** [comment]
@practicalswift good enough for me. Just asking because I wouldn't want PRs like this to be opened every day, there's already so many maintenance PRs.

utACK c3f34d06befa352acb343ad08337123d9474535f

**Comment by MarcoFalke** [comment]
​utACK c3f34d06befa352acb343ad08337123d9474535f

**Comment by Empact** [comment]
utACK  c3f34d0

**Pull request merged**
