### PR TITLE
Fix qt build broken by 5a5e4e9

### PR DESCRIPTION
**Pull request by TheBlueMatt**
#10368 broke qt build.

### CODE REVIEW

**Comment by laanwj** [comment]
utACK https://github.com/bitcoin/bitcoin/commit/5a5e4e9cc19e30186ba0a15a1cf892516d419baf

**Comment by sipa** [comment]
@laanwj It seems you acked the wrong commit.

**Comment by deeplink** [comment]
ACK 9e9e31a

**Comment by laanwj** [comment]
Verified that this fixes the qt build, ACK 9e9e31a

**Pull request merged**
