### PR TITLE
Update to LevelDB 1.20

### PR DESCRIPTION
**Pull request by sipa**
See https://github.com/bitcoin-core/leveldb/pull/1

### CODE REVIEW

**Review by gmaxwell — COMMENTED** [review]
utACK

**Comment by sipa** [comment]
Major improvement: adds the ability to use hardware-accelerated crc32.

**Comment by gmaxwell** [comment]
Travis is bombing with

leveldb/util/env_posix.cc:29:10: fatal error: 'util/env_posix_test_helper.h'

      file not found

#include "util/env_posix_test_helper.h"

**Comment by paveljanik** [comment]
On OS X:
```
Making all in src
  CXXLD    bitcoind
Undefined symbols for architecture x86_64:
  "leveldb::port::AcceleratedCRC32C(unsigned int, char const*, unsigned long)", referenced from:
      leveldb::crc32c::Extend(unsigned int, char const*, unsigned long) in libleveldb.a(leveldb_libleveldb_a-crc32c.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by paveljanik** [comment]
But `util/env_posix_test_helper.h` is there:

https://github.com/bitcoin/bitcoin/pull/10544/commits/94fe30aaec40c6795586d2a0291f053500e40335#diff-c439a67281cf7c414d51630edca309c9

Strange. This Travis issue does not happen locally.

**Comment by paveljanik** [comment]
My issue is this one 8) https://github.com/NuxiNL/cloudabi-ports/issues/32 reported by @laanwj ;-)

**Comment by jonasschnelli** [comment]
Gitian complains:
```
  CXX      leveldb/util/leveldb_libleveldb_a-status.o
  CXX      leveldb/port/leveldb_libleveldb_a-port_posix.o
  CXX      leveldb/helpers/memenv/leveldb_libmemenv_a-memenv.o
  CXX      test/test_test_bitcoin-arith_uint256_tests.o
  AR       libbitcoin_cli.a
leveldb/util/env_posix.cc:29:10: fatal error: 'util/env_posix_test_helper.h' file not found
#include "util/env_posix_test_helper.h"
         ^
1 error generated.
make[2]: *** [leveldb/util/leveldb_libleveldb_a-env_posix.o] Error 1
make[2]: *** Waiting for unfinished jobs....
  CXX      test/test_test_bitcoin-addrman_tests
```

**Comment by laanwj** [comment]
> My issue is this one 8) NuxiNL/cloudabi-ports#32 reported by @laanwj ;-)

There the SSE-accelerated CRC function was referenced, but not linked in.

**Comment by sipa** [comment]
@theuni fixed it, yo

**Comment by paveljanik** [comment]
compiles OK here, only one new warning:
```
leveldb/db/version_set.cc:1039:21: warning: comparison of integers of different signs: 'uint64_t' (aka 'unsigned long long') and 'int' [-Wsign-compare]
      manifest_size >= TargetFileSize(options_)) {
      ~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
```

**Comment by MarcoFalke** [comment]
@sipa I suspect you need to fix the out-of-tree builds by something like

```diff
diff --git a/src/Makefile.leveldb.include b/src/Makefile.leveldb.include
index b61088e..ac38141 100644
--- a/src/Makefile.leveldb.include
+++ b/src/Makefile.leveldb.include
@@ -77,6 +77,7 @@ leveldb_libleveldb_a_SOURCES += leveldb/table/merger.h
 leveldb_libleveldb_a_SOURCES += leveldb/table/format.h
 leveldb_libleveldb_a_SOURCES += leveldb/table/iterator_wrapper.h
 leveldb_libleveldb_a_SOURCES += leveldb/util/crc32c.h
+leveldb_libleveldb_a_SOURCES += leveldb/util/env_posix_test_helper.h
 leveldb_libleveldb_a_SOURCES += leveldb/util/arena.h
 leveldb_libleveldb_a_SOURCES += leveldb/util/random.h
 leveldb_libleveldb_a_SOURCES += leveldb/util/posix_logger.h

**Comment by paveljanik** [comment]
@MarcoFalke Good catch!

**Comment by sipa** [comment]
@MarcoFalke Thanks! I've added a commit with you as author.

**Review by gmaxwell — APPROVED** [review]
ACK

**Comment by laanwj** [comment]
After merging https://github.com/bitcoin-core/leveldb/pull/1
```
src/leveldb in HEAD was last updated to upstream commit 196962ff01c39b4705d8117df5c3f8c205349950 (tree d5a89851da0a8ab07c40966ac137f4e299c80927)
src/leveldb in HEAD currently refers to tree d5a89851da0a8ab07c40966ac137f4e299c80927
GOOD
```

**Review by laanwj — APPROVED** [review]

**Comment by theuni** [comment]
post-merge utACK.

**Pull request merged**
