### PR TITLE
Update sha512.cpp

### PR DESCRIPTION
**Pull request by smatthewenglish**
cleaning up formatting

### CODE REVIEW

**Comment by dcousens** [comment]
utACK, but [Trivial]

**Comment by DavidVorick** [comment]
NACK

the triple slash is a signal for doxygen

**Comment by fanquake** [comment]
NACK

**Comment by jonasschnelli** [comment]
Right. Comments are often in doxygen compatible format.
Please also don't open extremely trivial PRs. This is contra productive because it distracts from the important stuff.

**Pull request closed without merging**
