### PR TITLE
Bump python minimum supported version to 3.10

### PR DESCRIPTION
**Pull request by maflcko**
All supported operating systems ship with python 3.10 (or later), so bumping the minimum should not cause any issues. A bump will allow new code to use new python features.

For reference:
* https://packages.debian.org/bookworm/python3
* https://packages.ubuntu.com/jammy/python3
* FreeBSD 13/14 ships with 3.11
* CentOS-like 8/9 ships with 3.11/3.12 (via `appstream`)
* OpenSuse Tumbleweed ships with all python versions, e.g. https://software.opensuse.org/package/python312-base

This is for Bitcoin Core 29.0 in 2025 (next year), not the soon upcoming 28.0 this fall.

### CODE REVIEW

**Comment by hebasto** [comment]
> All supported operating systems ship with python 3.10 (or later), so bumping the minimum should not cause any issues.

I agree on using newer tools.

> A bump will allow new code to use new python features.

Out of curiosity, which features can you mention specifically?

**Review by AngusP — APPROVED** [review]
ACK fa1b139d17d04cb23bdfb1dd9c2abcdad4bdcd27

A few more:
* Brew provides [3.9.19](https://formulae.brew.sh/formula/python@3.9) thru [3.12.5](https://formulae.brew.sh/formula/python@3.12#default) (with [3.8](https://formulae.brew.sh/formula/python@3.8#default) as a deprecated package)
* Fedora 40 ships [3.12.5](https://packages.fedoraproject.org/pkgs/python3.12/python3/)
* Alpine v3.20 ships [3.12.3](https://pkgs.alpinelinux.org/package/v3.20/main/x86_64/python3)
* Arch ships [3.12.5](https://archlinux.org/packages/core/x86_64/python/)

**Comment by Zero-1729** [comment]
> In theory one could use the Python `match`, which was ported from Rust, IIRC.
> 
> Not sure if anyone wants to do that, or if it is worth it. Happy to close this pull instead and do a bump to 3.11 next year instead, which comes with more useful features.

In that case, it might be worth just waiting to bump to 3.11 instead.

**Review by l0rinc — APPROVED** [review]
> -- Found Python3: /opt/homebrew/Frameworks/Python.framework/Versions/3.12/bin/python3.12 (found suitable version "3.12.5", minimum required is "3.10")

ACK fa1b139d17d04cb23bdfb1dd9c2abcdad4bdcd27

**Review by stickies-v — APPROVED** [review]
ACK fa1b139d17d04cb23bdfb1dd9c2abcdad4bdcd27

> For reference:
> ...
> * https://packages.ubuntu.com/jammy/python3

Note: focal is [supported until April 2025](https://ubuntu.com/about/release-cycle) and ships with [`3.8`](https://packages.ubuntu.com/focal/python3), but since that's already unsupported as per our current `3.9` requirements that doesn't really change anything.

**Comment by achow101** [comment]
ACK fa1b139d17d04cb23bdfb1dd9c2abcdad4bdcd27

**Pull request merged**
