### PR TITLE
ci: Use `ninja` to build in macOS native CI job

### PR DESCRIPTION
**Pull request by hebasto**
This PR addresses [this](https://github.com/bitcoin/bitcoin/pull/30911#issuecomment-2354922939) comment:
> I wonder if one CI task should be using Ninja (and cmake >= 3.27), if it isn't too hard to implement. Otherwise this config will remain untested and errors may sneak in to the master branch, only being detected after merge.

### CODE REVIEW

**Review by theuni — APPROVED** [review]
ACK d01b85bfecbcf16ea16f90e2ade7537bf582269f.

I was going to suggest this as well :)

**Review by jonatack — COMMENTED** [review]
LGTM but am new to CMake builds.

ACK d01b85bfecbcf16ea16f90e2ade7537bf582269f

**Review by jarolrod — APPROVED** [review]
ACK d01b85bfecbcf16ea16f90e2ade7537bf582269f

**Comment by laanwj** [comment]
ACK d01b85bfecbcf16ea16f90e2ade7537bf582269f

Good to test this in the CI, i prefer building using ninja.

**Review by rezaeghbal01 — APPROVED** [review]

**Pull request merged**
