### PR TITLE
Fix include comment in src/interfaces/wallet.h

### PR DESCRIPTION
**Pull request by promag**

### CODE REVIEW

**Comment by practicalswift** [comment]
ACK a962c5440e6ea264c518dd527e4dc24876509c45

**Comment by promag** [comment]
@ryanofsky Sorry if I've overlooked. Now with your suggestion.

**Comment by practicalswift** [comment]
ACK defffb3587ebb1cda5331ac1e229a34472f29ddb

**Comment by ryanofsky** [comment]
utACK defffb3587ebb1cda5331ac1e229a34472f29ddb

**Pull request merged**
