### PR TITLE
Explicitly pass CChainParams& to DisconnectTip()

### PR DESCRIPTION
**Pull request by hmel**
Continue work on #7829 started by @jtimon 
Pass CChainParams& to UpdateTip(), DisconnectTip(), InvalidateBlock() and ConnectBlock(), and remove global Params()  call.

### CODE REVIEW

**Comment by jtimon** [comment]
utACK

**Comment by laanwj** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/7916/commits/d0a6353dec48f365c38de3c76b42f67eda737ed5

**Comment by hmel** [comment]
I have a patch for ConnectBlock() which is also a few lines. Should I push it here as well?

**Comment by jtimon** [comment]
Since ConnectBlock() is trivial enough and the PR is still recent, I would say we're still on time to slightly increase the scope of this PR with an additional commit.
@laanwj thoughts?

**Comment by sipa** [comment]
ACK on adding ConnectBlock()

**Comment by laanwj** [comment]
@jtimon fine with me. As I said in #7876, I prefer bundling changes that are easy to review like this one.

**Comment by jtimon** [comment]
re-utACK (after adding 176869f ).

**Comment by dcousens** [comment]
utACK 176869f

**Pull request merged**
