### PR TITLE
Allow wallet file to be a symlink, as was the case before v0.15.0

### PR DESCRIPTION
**Pull request by mmgen**

### CODE REVIEW

**Comment by jnewbery** [comment]
NACK. Please see discussion here: https://github.com/bitcoin/bitcoin/pull/10885#issuecomment-329715523 for why this unintended behaviour was removed.

In general, PRs without a description are unlikely to get much sympathy/review.

If you need flexibility in where your wallet files are kept, you may wish to help with reviewing #11687

**Comment by ryanofsky** [comment]
I don't think we can do this because of concerns that storing the berkeleydb data file separately from berkeleydb log files (in database/log.*) could lead to data and funds loss. With 0.16 it will be possible to specify a -walletdir=<path> option to bitcoind that can be a symlink. Also #11687, which is not scheduled to be merged before 0.16 is branched will restore the options for individual wallets to be symlinks (to directories).

**Comment by MarcoFalke** [comment]
> With 0.16 it will be possible to specify a -walletdir= option to bitcoind that can be a symlink.

I'd suggest to close this pull

**Comment by mmgen** [comment]
> With 0.16 it will be possible to specify a -walletdir= option to bitcoind that can be a symlink.

Fine, this answers my needs.  I'm fine with closing the PR then.

**Pull request closed without merging**
