### PR TITLE
Fix OSX non-deterministic dmg

### PR DESCRIPTION
**Pull request by theuni**
I believe this is all that's necessary to fix the 0.13rc1 osx determinism issue.

Obviously needs backport to 0.13 branch.

### CODE REVIEW

**Comment by luke-jr** [comment]
Makes sense. utACK

**Comment by MarcoFalke** [comment]
Concept ACK

**Comment by achow101** [comment]
ACK 3b3ce25df6cc84cd1e75a7ec20fc7da8d2ef76e0

Ran the gitian build twice and got the same results

`9fa6b31128eee2cfa535774fe4eebaa384f0471c094ce6ee6aefe9aef93f134b  bitcoin-0.13.99-osx-unsigned.dmg
e2e33efea3d2c86d34391b3be20d032343b359909cdbe55b1153ba109ae5af4f  bitcoin-0.13.99-osx-unsigned.tar.gz
fc5a233b3be260ec7be63f699bbc128240ad190692cd5d4a82cc1352eb3c57df  bitcoin-0.13.99-osx64.tar.gz
0269f915640886ba16c73450ab2dbcdde0304fa79807414c7e0cf4d4ba8f39df  src/bitcoin-0.13.99.tar.gz
ab0a5e271e81fb48cf355f866a105eca12713260e703da35330ae66e03336367  bitcoin-osx-0.13-res.yml`

**Comment by theuni** [comment]
Matched @achow101's results:
```
9fa6b31128eee2cfa535774fe4eebaa384f0471c094ce6ee6aefe9aef93f134b  bitcoin-0.13.99-osx-unsigned.dmg
e2e33efea3d2c86d34391b3be20d032343b359909cdbe55b1153ba109ae5af4f  bitcoin-0.13.99-osx-unsigned.tar.gz
fc5a233b3be260ec7be63f699bbc128240ad190692cd5d4a82cc1352eb3c57df  bitcoin-0.13.99-osx64.tar.gz
0269f915640886ba16c73450ab2dbcdde0304fa79807414c7e0cf4d4ba8f39df  src/bitcoin-0.13.99.tar.gz
1f378788d2965cec1e0d6591f59288cc4344f5b9a328b6186bd41cf1a631bada  bitcoin-osx-0.13-res.yml
```

**Comment by paveljanik** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/8373/commits/3b3ce25df6cc84cd1e75a7ec20fc7da8d2ef76e0

**Comment by laanwj** [comment]
utACK 3b3ce25

**Pull request merged**
