### PR TITLE
refactor: Add thread safety annotation to `BanMan::SweepBanned()`

### PR DESCRIPTION
**Pull request by hebasto**
This PR adds a proper thread safety annotation to `BanMan::SweepBanned()`.

Also a simple refactoring applied.

### CODE REVIEW

**Review by theStack — COMMENTED** [review]
Concept ACK

Looks like a `m_cs_banned` lock acquire needs to add before the the `SweepBanned` call in the `BanMan` constructor to get rid of the failed assertion.

**Comment by ajtowns** [comment]
Moving the code that's in the constructor into a separate function, so that the constructor is just `{ LoadBanlist(); DumpBanlist(); }` causes the compiler to give errors about the missing locks in `LoadBanlist()`.

**Comment by MarcoFalke** [comment]
A constructor shouldn't need to lock a member mutex. Maybe we should fade out `AssertLockHeld` and remove it here?

**Comment by hebasto** [comment]
Reworked: c4d0613bdf3beaf48fd35625cf2dc6018b059dbb -> f317ae181dc03cbe7004b63996dc7cf2c85c84db ([pr25149.01](https://github.com/hebasto/bitcoin/commits/pr25149.01) -> [pr25149.02](https://github.com/hebasto/bitcoin/commits/pr25149.02)).

**Comment by w0xlt** [comment]
Concept ACK

**Comment by hebasto** [comment]
Applied @ajtowns's [suggestion](https://github.com/bitcoin/bitcoin/pull/25149#issuecomment-1128972447) which was supported by @w0xlt with :+1: .

**Comment by ajtowns** [comment]
ACK ab7538832043a6c15e45a178fb6bb6298a00108f

**Review by w0xlt — APPROVED** [review]
ACK https://github.com/bitcoin/bitcoin/pull/25149/commits/ab7538832043a6c15e45a178fb6bb6298a00108f

**Review by theStack — APPROVED** [review]
Code-review ACK ab7538832043a6c15e45a178fb6bb6298a00108f

Happy to see that another `RecursiveMutex` will bite the dust soon.

**Pull request merged**
