### PR TITLE
build: Produce a `.zip` for macOS distribution

### PR DESCRIPTION
**Pull request by hebasto**
It is https://github.com/bitcoin/bitcoin/pull/27099 revived with addressed [comments](https://github.com/bitcoin/bitcoin/pull/27099#issuecomment-1708705686).

From https://github.com/bitcoin/bitcoin/pull/27099#issue-1584429885:
> Reviving the discussion around using a `.zip` for the distributed macOS binaries, as opposed to a `.dmg`.
>
> Given we only had a single report of the "no finder window" issue (#26176), I wonder if that means macOS users were able to figure it out, they gave up/didn't report, or, we just have very few macOS users.
>
> Related to #18128.

That's how it looks on macOS:

image

### CODE REVIEW

**Comment by hebasto** [comment]
cc @Sjors @fanquake @prusnak

**Comment by Sjors** [comment]
ACK b334ef8dbccc02505532a90711a27966fa46a44b

Tested again on Intel macOS by building on the same machine and using the (unsigned) guix build.

```
find guix-build-$(git rev-parse --short=12 HEAD)/output/ -type f -print0 | env-r0 sha256sum
d0294bf567dd0403070ad599c93900fccd54d352396d0cec6778e6c04a7bfe8f  guix-build-b334ef8dbccc/output/arm64-apple-darwin/SHA256SUMS.part
51f6de1530136253f7a6616fadea55e9e5ee3ec6f8d350e9069e5953d2487f20  guix-build-b334ef8dbccc/output/arm64-apple-darwin/bitcoin-b334ef8dbccc-arm64-apple-darwin-unsigned.tar.gz
a20203dfd9624bb445a5c7d1d3e7746feb3910df033c413df8354b2606d2293a  guix-build-b334ef8dbccc/output/arm64-apple-darwin/bitcoin-b334ef8dbccc-arm64-apple-darwin-unsigned.zip
7d771d7279c1c5480315e0570914724738ef684ae599943f21421fd90bb2db52  guix-build-b334ef8dbccc/output/arm64-apple-darwin/bitcoin-b334ef8dbccc-arm64-apple-darwin.tar.gz
59f6e88ba0f28010feecfdc1fd67dd32de35c8eecc7ea4a73164d550f83eba57  guix-build-b334ef8dbccc/output/dist-archive/bitcoin-b334ef8dbccc.tar.gz
c23611d70355b31f70094b26555bce361cfa81f5044a2ab4f14ac1a95aae2cc7  guix-build-b334ef8dbccc/output/x86_64-apple-darwin/SHA256SUMS.part
c315865d94d98ae5830d80bfa5adb14b3eec111762fbd2ae234da9a20fedc999  guix-build-b334ef8dbccc/output/x86_64-apple-darwin/bitcoin-b334ef8dbccc-x86_64-apple-darwin-unsigned.tar.gz
e857d41029a8d20bce3db5bc1e4636dd863cc19b6e454a19b3f97764408539e7  guix-build-b334ef8dbccc/output/x86_64-apple-darwin/bitcoin-b334ef8dbccc-x86_64-apple-darwin-unsigned.zip
36ca3883439d36de7e27ba8edaa3dbead910a28396c1229ff3ce427eeba237f5  guix-build-b334ef8dbccc/output/x86_64-apple-darwin/bitcoin-b334ef8dbccc-x86_64-apple-darwin.tar.gz
```

**Review by stickies-v — COMMENTED** [review]
Approach ACK. Skipping the dmg for a simplified build process makes sense to me, it's an easy enough setup process with the zip too. An additional installation hint on https://bitcoincore.org/en/download/ would probably be helpful.

Tested on M1 Pro with `make deploy`, as well as guix build (done on amd64 bookworm). Both binaries work well, and my shasums match too:

```
% find guix-build-$(git rev-parse --short=12 HEAD)/output/ -type f -print0 | sort -z | xargs -0 sha256sum

7d771d7279c1c5480315e0570914724738ef684ae599943f21421fd90bb2db52  guix-build-b334ef8dbccc/output/arm64-apple-darwin/bitcoin-b334ef8dbccc-arm64-apple-darwin.tar.gz
51f6de1530136253f7a6616fadea55e9e5ee3ec6f8d350e9069e5953d2487f20  guix-build-b334ef8dbccc/output/arm64-apple-darwin/bitcoin-b334ef8dbccc-arm64-apple-darwin-unsigned.tar.gz
a20203dfd9624bb445a5c7d1d3e7746feb3910df033c413df8354b2606d2293a  guix-build-b334ef8dbccc/output/arm64-apple-darwin/bitcoin-b334ef8dbccc-arm64-apple-darwin-unsigned.zip
d0294bf567dd0403070ad599c93900fccd54d352396d0cec6778e6c04a7bfe8f  guix-build-b334ef8dbccc/output/arm64-apple-darwin/SHA256SUMS.part
59f6e88ba0f28010feecfdc1fd67dd32de35c8eecc7ea4a73164d550f83eba57  guix-build-b334ef8dbccc/output/dist-archive/bitcoin-b334ef8dbccc.tar.gz
36ca3883439d36de7e27ba8edaa3dbead910a28396c1229ff3ce427eeba237f5  guix-build-b334ef8dbccc/output/x86_64-apple-darwin/bitcoin-b334ef8dbccc-x86_64-apple-darwin.tar.gz
c315865d94d98ae5830d80bfa5adb14b3eec111762fbd2ae234da9a20fedc999  guix-build-b334ef8dbccc/output/x86_64-apple-darwin/bitcoin-b334ef8dbccc-x86_64-apple-darwin-unsigned.tar.gz
e857d41029a8d20bce3db5bc1e4636dd863cc19b6e454a19b3f97764408539e7  guix-build-b334ef8dbccc/output/x86_64-apple-darwin/bitcoin-b334ef8dbccc-x86_64-apple-darwin-unsigned.zip
c23611d70355b31f70094b26555bce361cfa81f5044a2ab4f14ac1a95aae2cc7  guix-build-b334ef8dbccc/output/x86_64-apple-darwin/SHA256SUMS.part
```

We still have references to [xorriso](https://github.com/hebasto/bitcoin/blob/b334ef8dbccc02505532a90711a27966fa46a44b/ci/test/00_setup_env_mac.sh#L14) and [xorrisofs](https://github.com/hebasto/bitcoin/blob/b334ef8dbccc02505532a90711a27966fa46a44b/configure.ac#L802), are those still necessary?

I'm a bit out of my depth with this build stuff so this is probably as far as my review will go.

**Comment by hebasto** [comment]
Updated b334ef8dbccc02505532a90711a27966fa46a44b -> f52a72af569526f319d9f1480eb473b9570125c3 ([pr28432.01](https://github.com/hebasto/bitcoin/commits/pr28432.01) -> [pr28432.02](https://github.com/hebasto/bitcoin/commits/pr28432.02)):

- addressed @stickies-v's [comment](https://github.com/bitcoin/bitcoin/pull/28432#pullrequestreview-1628728342)
- added the `AC_PATH_PROG` macro for the `zip` program
- mentioned the `zip` package in https://github.com/bitcoin/bitcoin/tree/master/depends#for-macos-cross-compilation
- rebased

**Comment by hebasto** [comment]
My updated Guix builds:
```
x86_64
bbbbce4747a8dcd9581cd734eec6fed14163e830e5ab7d53b6a1057f4414b0cc  guix-build-b5790c35f7e1/output/arm64-apple-darwin/SHA256SUMS.part
add758c8c7c526c68fbe43850af17f284a2a52d267e9b38f328060673dffda77  guix-build-b5790c35f7e1/output/arm64-apple-darwin/bitcoin-b5790c35f7e1-arm64-apple-darwin-unsigned.tar.gz
7f477397fe0e13d4e4b6048488258f46b88c52f32dc510d85e080bb1eec81a7e  guix-build-b5790c35f7e1/output/arm64-apple-darwin/bitcoin-b5790c35f7e1-arm64-apple-darwin-unsigned.zip
dad1cea8b0db52d7e8d08dd02bbe22ba8777c44c40be9b15ebb77f31bb121b7a  guix-build-b5790c35f7e1/output/arm64-apple-darwin/bitcoin-b5790c35f7e1-arm64-apple-darwin.tar.gz
d8a89730ac1398621bcc7d245ca20991dac33c37728668727bc1edbb892c5706  guix-build-b5790c35f7e1/output/dist-archive/bitcoin-b5790c35f7e1.tar.gz
864f0dcb1a795e6958dfe152ef3b172c5f2c7b77a1ff6589e59059f484121506  guix-build-b5790c35f7e1/output/x86_64-apple-darwin/SHA256SUMS.part
3a1f7384e9d132a18650550e3484f5dbd33807030f3a5fad490532797b5e70ed  guix-build-b5790c35f7e1/output/x86_64-apple-darwin/bitcoin-b5790c35f7e1-x86_64-apple-darwin-unsigned.tar.gz
671d4c6df29d1ed36cd2624ef799fe8fa10e7fdcf8e78861dfd40fbefd075e6c  guix-build-b5790c35f7e1/output/x86_64-apple-darwin/bitcoin-b5790c35f7e1-x86_64-apple-darwin-unsigned.zip
ae8fbb32d0c311eb0891b325988e519061051d8c5e754e6ae457f59bf8ac5ed8  guix-build-b5790c35f7e1/output/x86_64-apple-darwin/bitcoin-b5790c35f7e1-x86_64-apple-darwin.tar.gz
```

**Comment by Sjors** [comment]
Getting the same guix hashes as @hebasto.

tACK b5790c35f7e1d48c79b83bded36f3f72c18c9fc1

Only tested that the Guix binary still works.

**Review by jarolrod — APPROVED** [review]
ACK b5790c35f7e1d48c79b83bded36f3f72c18c9fc1

Tested working, tested through `make deploy`. One slight behavior change to note, consecutive expansion of the zip and its binary in the same directory will result in a naming convention for the binary of `Bitcoin Qt [n]`, whereas with the current DMG approach it would be `Bitcoin Core [n]`.

Of course, that's not something we need to optimize for :D

**Review by sedited — COMMENTED** [review]
utACK b5790c35f7e1d48c79b83bded36f3f72c18c9fc1

**Pull request merged**
