### PR TITLE
opportunistic 1p1c followups

### PR DESCRIPTION
**Pull request by glozow**
Followups from #28970:
- https://github.com/bitcoin/bitcoin/pull/28970#discussion_r1568781077
- https://github.com/bitcoin/bitcoin/pull/28970#discussion_r1585554972
- https://github.com/bitcoin/bitcoin/pull/28970#discussion_r1581019326
- https://github.com/bitcoin/bitcoin/pull/28970#discussion_r1581036209
- https://github.com/bitcoin/bitcoin/pull/28970#discussion_r1586258730

### CODE REVIEW

**Review by instagibbs — APPROVED** [review]
ACK 6119f76ef72c1adc55c1a384c20f8ba9e1a01206

**Comment by fanquake** [comment]
Can this also address:
```bash
txorphanage.cpp:281:21: error: loop variable 'child_iter' creates a copy from type '__gnu_debug::_Safe_iterator<std::_Rb_tree_iterator<std::pair<const transaction_identifier<false>, TxOrphanage::OrphanTx>>, std::map<transaction_identifier<false>, TxOrphanage::OrphanTx>> const' [-Werror,-Wrange-loop-construct]
  281 |     for (const auto child_iter : iters) {
      |                     ^
txorphanage.cpp:281:10: note: use reference type '__gnu_debug::_Safe_iterator<std::_Rb_tree_iterator<std::pair<const transaction_identifier<false>, TxOrphanage::OrphanTx>>, std::map<transaction_identifier<false>, TxOrphanage::OrphanTx>> const &' to prevent copying
  281 |     for (const auto child_iter : iters) {
      |          ^~~~~~~~~~~~~~~~~~~~~~~
      |                     &
txorphanage.cpp:313:21: error: loop variable 'child_iter' creates a copy from type '__gnu_debug::_Safe_iterator<std::_Rb_tree_iterator<std::pair<const transaction_identifier<false>, TxOrphanage::OrphanTx>>, std::map<transaction_identifier<false>, TxOrphanage::OrphanTx>> const' [-Werror,-Wrange-loop-construct]
  313 |     for (const auto child_iter : iters) {
      |                     ^
txorphanage.cpp:313:10: note: use reference type '__gnu_debug::_Safe_iterator<std::_Rb_tree_iterator<std::pair<const transaction_identifier<false>, TxOrphanage::OrphanTx>>, std::map<transaction_identifier<false>, TxOrphanage::OrphanTx>> const &' to prevent copying
  313 |     for (const auto child_iter : iters) {
      |          ^~~~~~~~~~~~~~~~~~~~~~~
      |                     &
```

**Comment by glozow** [comment]
> Can this also address:

Added. I made a copy instead of reference because it's a pointer.

**Comment by instagibbs** [comment]
reACK https://github.com/bitcoin/bitcoin/pull/30012/commits/7f6fb73c82fdff2afe5edefcc335ba6707d5627d

just the non-pointer copying added

**Pull request merged**
