### PR TITLE
doc: correct typos

### PR DESCRIPTION
**Pull request by fanquake**
Includes #31253.
Includes https://github.com/bitcoin/bitcoin/pull/31239#pullrequestreview-2425008603.
Fixes remaining lint output.

### CODE REVIEW

**Comment by l0rinc** [comment]
ACK 726cbee9553b25bedfef70cfd5be9f1eeec8a30d

**Review by rkrux — APPROVED** [review]
crACK 726cbee9553b25bedfef70cfd5be9f1eeec8a30d

**Review by tdb3 — APPROVED** [review]
ACK 726cbee9553b25bedfef70cfd5be9f1eeec8a30d

Thanks. This scratches an itch.

Non longer saw the linter errors (present on master) when running `DOCKER_BUILDKIT=1 docker build -t bitcoin-linter --file "./ci/lint_imagefile" ./ && docker run --rm -v $(pwd):/bitcoin -it bitcoin-linter` on the PR branch.

**Review by Abdulkbk — APPROVED** [review]
ACK

**Pull request merged**
