### PR TITLE
rpc:  append rpcauth.py hash in config and show pass

### PR DESCRIPTION
**Pull request by st3b1t**
Small change improves security during the rpcauth directive generation procedure. In this way you can hang the configuration line directly inside the bitcoin.conf file and at the same time show the new password to the user, but without writing it to disk, the new beahvior:

append generated hash in config:

```bash
rpcauth.py user >> bitcoin.conf
```
show only in stderr without write clear password to disk:

```bash
Your password:
xxxxx...
```

### CODE REVIEW

**Review by Aminkavoos — APPROVED** [review]

**Review by brunoerg — COMMENTED** [review]
From CI:
```sh
102/264 - 
rpc_users.py
 failed, Duration: 1 s
stdout:
2023-05-06T19:48:12.787000Z TestFramework (INFO): PRNG seed is: 4992424049312590578
2023-05-06T19:48:12.806000Z TestFramework (INFO): Initializing test directory /tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_₿_🏃_20230506_193750/rpc_users_159
2023-05-06T19:48:13.197000Z TestFramework (ERROR): Unexpected exception caught during testing
Traceback (most recent call last):
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 131, in main
    self.setup()
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 297, in setup
    self.setup_chain()
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/rpc_users.py", line 65, in setup_chain
    self.password = lines[3]
                    ~~~~~^^^
IndexError: list index out of range
```

**Comment by st3b1t** [comment]
> From CI:
> 
> ```shell
> 102/264 - 
> rpc_users.py
>  failed, Duration: 1 s
> stdout:
> 2023-05-06T19:48:12.787000Z TestFramework (INFO): PRNG seed is: 4992424049312590578
> 2023-05-06T19:48:12.806000Z TestFramework (INFO): Initializing test directory /tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_₿_🏃_20230506_193750/rpc_users_159
> 2023-05-06T19:48:13.197000Z TestFramework (ERROR): Unexpected exception caught during testing
> Traceback (most recent call last):
>   File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 131, in main
>     self.setup()
>   File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 297, in setup
>     self.setup_chain()
>   File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/rpc_users.py", line 65, in setup_chain
>     self.password = lines[3]
>                     ~~~~~^^^
> IndexError: list index out of range
> ```

many tanks @brunoerg I found the problem and I am trying unit testing in local and in my branch

**Comment by st3b1t** [comment]
> Please squash your commits according to https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#squashing-commits

done, the resultant commit, only two files:
https://github.com/bitcoin/bitcoin/pull/27588/commits/e1046eca9d637dfd29599d156a57a8a3a7440b23

**Comment by fanquake** [comment]
@st3b1t note that you've left the commit messages from the squashed commits in e1046eca9d637dfd29599d156a57a8a3a7440b23.

**Pull request closed without merging**
