### PR TITLE
build: add support for FreeBSD to depends

### PR DESCRIPTION
**Pull request by fanquake**
Setup to use the system Clang (11.0.1 as of FreeBSD 13.0).

Doesn't build the Qt package; that requires a few additional changes. The current issue is that FreeBSDs `byacc` seems to have an issue parsing something in libxkbcommon. Work in progress branch here: https://github.com/fanquake/bitcoin/tree/depends_support_freebsd_qt. In any case, I don't think building the Qt libs on FreeBSD is a super high priority (I'd also have no way to test the GUI).

### CODE REVIEW

**Comment by MarcoFalke** [comment]
> In any case, I don't think building the Qt libs on FreeBSD is a super high priority (I'd also have no way to test the GUI).

It might be possible to use the system qt with the depends options `NO_QT=1 ALLOW_HOST_PACKAGES=1`

**Review by melissamforbs — APPROVED** [review]

**Review by melissamforbs — APPROVED** [review]

**Comment by fanquake** [comment]
Rebased on master and dropped the base commit.

> It might be possible to use the system qt with the depends options NO_QT=1 ALLOW_HOST_PACKAGES=1

Yes I'd think that is possible. I'm just assuming that the number of users wanting to run (depends built) bitcoin-qt on FreeBSD is not large.

**Comment by laanwj** [comment]
I tested it and get:
```
~/src/bitcoin/depends % gmake NO_QT=1
Invalid configuration `medea': machine `medea-unknown' not recognized
shasum: hosts/.mk: No such file or directory
shasum: hosts/.mk: No such file or directory
shasum: hosts/.mk: No such file or directory
…
```
It looks like the hostname ends up in the machine tuple somehow :smile:

**Comment by laanwj** [comment]
For some reason the environment variable `HOST` contains the hostname on this machine. I'm not sure where it comes from, but it seems FreeBSD behavior? 
The makefile assumes it to be a host tuple.

With the following patch, it gets past it:
```
diff --git a/depends/Makefile b/depends/Makefile
index 003778b37..36f28f1c7 100644
--- a/depends/Makefile
+++ b/depends/Makefile
@@ -45,7 +45,7 @@ MULTIPROCESS ?=
 FALLBACK_DOWNLOAD_PATH ?= https://bitcoincore.org/depends-sources
 
 BUILD = $(shell ./config.guess)
-HOST ?= $(BUILD)
+HOST := $(BUILD)
 PATCHES_PATH = $(BASEDIR)/patches
 BASEDIR = $(CURDIR)
 HASH_LENGTH:=11
```

**Comment by laanwj** [comment]
Oh, we explicitly document the use of `HOST`. OK, this is kind of annoying, I don't really know how to resolve this, we could just add a big FreeBSD warning to always override it.

**Comment by laanwj** [comment]
ACK ae9175f6086aa6c177084365c795e78c580eac1d
We can solve the tcsh specific issue (or document it) somewhere else.

**Pull request merged**
