### PR TITLE
Add net2 debug option

### PR DESCRIPTION
**Pull request by rebroad**
I often want to enable net debugging, but currently it's too noisy for what I want. Move some of the more verbose net debugging messages to "net2", making "net" debugging more likely to be desired without being too verbose (like this description!).

### CODE REVIEW

**Comment by jonasschnelli** [comment]
I think this makes sense. Although it would remove certain log output if people continue to use only `debug=net`. But IMO thats okay.
I personally would prefer something like `debug=netverbose` instead of `net2`.

**Comment by laanwj** [comment]
> I personally would prefer something like debug=netverbose instead of net2.

Agreed

**Comment by paveljanik** [comment]
Concent ACK.
I too prefer `netverbose`.

**Comment by laanwj** [comment]
@rebroad can you please update the name of the debug category, then we can get this merged.

**Comment by morcos** [comment]
`LogPrint("net", "dropmessages DROPPING SEND MESSAGE\n");` at [line 2492](https://github.com/bitcoin/bitcoin/pull/7654/files#diff-9a82240fe7dfe86564178691cc57f2f1R2492) should probably also be moved to the new category.

Also maybe out of scope for this PR but the debug logging around `"received getdata"` seems due for a cleanup.

**Comment by laanwj** [comment]
Ping @rebroad

**Comment by laanwj** [comment]
Closing due to inactivity.

**Pull request closed without merging**
