### PR TITLE
Update btcdrak key with new expiry dates

### PR DESCRIPTION
**Pull request by btcdrak**

### CODE REVIEW

**Comment by MarcoFalke** [comment]
I think my key in the repo expired as well... We might ask people to just refresh the keys from a keyserver.

**Comment by laanwj** [comment]
On the other hand, the key servers are a sewer, people should be careful not to request keys by 32-bit key-id anymore at least. So if we're going to ask people to refresh from there, we should provide the right commands.

**Comment by MarcoFalke** [comment]
```sh
gpg --import bitcoin/contrib/gitian-keys/*.pgp
gpg --refresh-keys
```

I don't think if you import from the repo first, it is not requesting by 32-bit id.

**Comment by laanwj** [comment]
I didn't even know about --refresh-keys. Let's add that to `doc/release-process.md`.

**Comment by laanwj** [comment]
Closing in favor of #8603

**Pull request closed without merging**
