### PR TITLE
scripted-diff: Replace strCommand with msg_type

### PR DESCRIPTION
**Pull request by maflcko**
Receiving a message is not a command, but simply a message of some type

### CODE REVIEW

**Comment by naumenkogs** [comment]
Not sure how we go about refactoring like this, but I do like this change. ACK!

I was thinking maybe we should make a type stronger than a string since we're touching it, but I guess there's not much we can do here.

**Comment by MarcoFalke** [comment]
> Not sure how we go about refactoring like this, but I do like this change. ACK!

For purely stylistic matters, I think the rule is to not change the style unless you touch that line for other reasons. However, in this case, I think it is a problem of code (self) documentation. A command and message type are two completely different things and should not be confused with each other.

> I was thinking maybe we should make a type stronger than a string since we're touching it, but I guess there's not much we can do here.

Indeed, string is the best we can do here. On the wire it is a string and practically you'll always have to do string comparison. Even if it is to convert the string to an enum (#10145).

**Comment by promag** [comment]
ACK, also update src/test/fuzz/process_message.cpp?

**Comment by MarcoFalke** [comment]
Addressed @promag's feedback

**Comment by promag** [comment]
ACK 7777e3624fabe4718675b2be8b088697b7ad4d0d.

**Comment by naumenkogs** [comment]
ACK 7777e36

**Comment by practicalswift** [comment]
ACK 7777e3624fabe4718675b2be8b088697b7ad4d0d -- I've always thought the `strCommand` name is confusing :)

**Review by theStack — APPROVED** [review]
ACK 7777e36
> A command and message type are two completely different things and should not be confused with each other.

Concerning this point, a follow-up PR renaming also `CNetMessage.m_command` would make sense I guess?

**Comment by MarcoFalke** [comment]
> Concerning this point, a follow-up PR renaming also CNetMessage.m_command would make sense I guess?

There is some active work going on in CNetMessage, so it can be done as part of one of those changes that touch that code anyway.

**Comment by theStack** [comment]
Another place where the "command" naming is still used is in the `class CMessageHeader`:
- `char pchCommand[COMMAND_SIZE];`
- `std::string GetCommand() const;`
- .....

**Comment by MarcoFalke** [comment]
Did all of the replacements suggested by @theStack in one scripted diff

**Comment by MarcoFalke** [comment]
The full replacement commit was eeee135a9f517d65075f0f5b66f450e79368fbc4, but I've reverted this to the initial version, which was focussed on just net_processing and was less invasive and has 4 ACKs. Someone else can pick up the full replacement later.

**Comment by MarcoFalke** [comment]
I've also checked that on my system with clang and gcc on `-O2` it produces the same binaries. So I will go ahead and merge this.

**Pull request merged**
