### PR TITLE
build: set minimum supported macOS to 10.12

### PR DESCRIPTION
**Pull request by fanquake**
Extracted from #16392 as this doesn't need to wait for the other build changes.

Reasoning:
* `10.10` has been unsupported since July 2017 (~3 years at `v0.20.0` release)
* `10.11` has been unsupported since July 2018  (~2 years at `v0.20.0` release)
* macOS users are consistent at upgrading to new releases.
* Qt 5.12 LTS only supports [macOS > 10.12](https://doc-snapshots.qt.io/qt5-5.12/supported-platforms.html). As long as we're supporting macOS < 10.12 we would not be able to bump Qt in depends to 5.12 for the `v0.20.0` release.

Once we drop support for 10.12 and start using the 10.15 SDK there are some other follow ups:
* Enabling support for [`thread_local`](https://github.com/bitcoin/bitcoin/blob/master/configure.ac#L901).
* Removing some of the macOS notification code
* Removing macOS [startup item code](https://github.com/bitcoin/bitcoin/blob/master/src/qt/guiutil.cpp#L695).

There was also some related discussion in the `#bitcoin-builds` channel yesterday arvo.

### CODE REVIEW

**Review by maflcko — APPROVED** [review]

**Comment by laanwj** [comment]
ACK 7d7bf2ff4a67c3953b0d660ca88d11313cb4d71d

**Comment by dongcarl** [comment]
So this bumps the supported OSX version, but doesn't bump the SDK? (At least not a major version of the SDK?)

**Comment by fanquake** [comment]
> could we have bumped the supported OSX version without bumping the SDK

That's what this PR is doing. This increases our minimum supported macOS version from `10.10` to `10.12`. Nothing SDK related is changing, the change to start using the `10.14` SDK over the `10.11` SDK is still in #16392.

**Comment by dongcarl** [comment]
post-IRC-grilling-ACK 7d7bf2ff4a67c3953b0d660ca88d11313cb4d71d

**Pull request merged**
