### PR TITLE
Remove whitespace before double colon in errors and logs

### PR DESCRIPTION
**Pull request by paveljanik**
Remove unnecessary whitespaces in errors and log messages as previously discussed. E.g.

```
error("CAlert::CheckSignature() : verify signature failed");
```

The space before the colon (':') is removed.
This branch was created automatically with the following commands:

```
find . -type f -and \( -name \*.cpp -or -name \*.h \) -exec sed -i '' '/.*error(.*\".* : .*\"/ s# : #: #' {} \;
find . -type f -and \( -name \*.cpp -or -name \*.h \) -exec sed -i '' '/.*LogPrint(.*\".* : .*\"/ s# : #: #' {} \;
find . -type f -and \( -name \*.cpp -or -name \*.h \) -exec sed -i '' '/.*LogPrintf(.*\".* : .*\"/ s# : #: #' {} \;
```

on non GNU system (thus '' after -i, no + etc.). Developers are thus able to replicate its changes on their system to make rebase easy.

No manual changes in this branch so far. git diff --check empty.

This have to be handled later or before this PR to completely clean this up automatically (original lines from master):
1. src/qt/coincontroltreewidget.cpp - the above commands add a newline at the end of file. Do not ask me why. sed was run on OS X 10.10.
2. These error messages are in the master already and look ugly and the above commands change them:

```
return error("AcceptToMemoryPool: : CheckTransaction failed");
return state.DoS(100, error("AcceptToMemoryPool: : coinbase as individual tx"),
return error("AcceptToMemoryPool: : nonstandard transaction input");
```
1. To keep things automatable, the following lines are touched as well.

```
LogPrintf("LoadBlockIndexDB(): transaction index %s\n", fTxIndex ? "enabled" : "disabled");
LogPrint("net", "got inv: %s  %s peer=%d\n", inv.ToString(), fAlreadyHave ? "have" : "new", pfrom->id);
LogPrint("net", "getblocks %d to %s limit %d from peer=%d\n", (pindex ? pindex->nHeight : -1), hashStop==uint256(0) ? "end" : hashStop.ToString(), nLimit, pfrom->id);
LogPrintf("AddToWallet %s  %s%s\n", wtxIn.GetHash().ToString(), (fInsertedNew ? "new" : ""), (fUpdated ? "update" : ""));
```

So a few questions/propositions:
1. git checkout -- src/qt/coincontroltreewidget.cpp or keep the added newline?
2. fix these error here manually or separate branch before this?
3. fix these four problematic lines manually in this branch (deleted whitespaces do not make effect anyway) or let them be?

### CODE REVIEW

**Comment by paveljanik** [comment]
Rebased again. Now fully automated with:

```
find . -type f -and \( -name \*.cpp -or -name \*.h \) -exec sed -i '' '/.*error(.*\".* : .*\"/ s# : #: #' {} \;
find . -type f -and \( -name \*.cpp -or -name \*.h \) -exec sed -i '' '/.*LogPrint(.*\".* : .*\"/ s# : #: #' {} \;
find . -type f -and \( -name \*.cpp -or -name \*.h \) -exec sed -i '' '/.*LogPrintf(.*\".* : .*\"/ s# : #: #' {} \;
find . -type f -and \( -name \*.cpp -or -name \*.h \) -exec sed -i '' '/.*qWarning(.*\".* : .*\"/ s# : #: #' {} \;
find . -type f -and \( -name \*.cpp -or -name \*.h \) -exec sed -i '' '/.*qDebug(.*\".* : .*\"/ s# : #: #' {} \;
find . -type f -and \( -name \*.cpp -or -name \*.h \) -exec sed -i '' '/.*failure(.*\".* : .*\"/ s# : #: #g' {} \;
find . -type f -and \( -name \*.cpp -or -name \*.h \) -exec sed -i '' '/.*printf(.*\".* : .*\"/ s# : #: #' {} \;
find . -type f -and \( -name \*.cpp -or -name \*.h \) -exec sed -i '' '/.*assert(.*\".* : .*\"/ s# : #: #' {} \;

# Fix errors:
find . -type f -and \( -name \*.cpp -or -name \*.h \) -exec sed -i '' '/[^ ]": "/ s#": "#" : "#' {} \;
sed -i '' 's#pindex->nHeight: -1#pindex->nHeight : -1#' src/main.cpp
```

**Comment by fanquake** [comment]
Needs rebase

**Comment by Diapolo** [comment]
I'd love to see this merged soon... scripted cleanup rocks IMHO.

**Comment by paveljanik** [comment]
I think this should me merged in after 0.10 is finished (to make it easier to merge stuff from last 0.10 fixes). And as soon as it is, I'll rebase again. @Diapolo this was the reason I scripted it ;-)

**Comment by laanwj** [comment]
This is part of @theuni 's https://github.com/theuni/bitcoin-trivial/commits/trivial-rebase , and will be merged via that route.

**Pull request closed without merging**
