### PR TITLE
Move zmq test skipping logic into individual test case.

### PR DESCRIPTION
**Pull request by jnewbery**
This commit uses the new skip test funcationality added in
232b6665bc3e5b134821dc7584968fb439fd5f44 to skip the zmq tests if the
python zmq module is not available or if bitcoind has been built without
zmq support.

This removes the zmq-specific logic from test_runner.py. In general it's
better if test_runner.py has no knowledge of special cases for
individual tests and is a general purpose test runner.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Concept ACK

**Comment by fanquake** [comment]
Needs a rebase. Will test.

**Comment by jmcorgan** [comment]
utACK

**Comment by jnewbery** [comment]
rebased

**Comment by jnewbery** [comment]
rebased

**Review by jimmysong — APPROVED** [review]
ACK 6803e09e6eeb2dbc820bb1025475a50a4352e30d

Tested with pyzmq not installed (skipped as expected)
Tested with zmq not enabled in binary (skipped as expected)
Tested with zmq and pyzmq enabled (tested as expected)

**Comment by MarcoFalke** [comment]
utACK 6803e09

@jimmysong Thanks for testing.

**Pull request merged**
