### PR TITLE
cirrus: Use SSD cluster for speedup

### PR DESCRIPTION
**Pull request by maflcko**
Haven't tested, but this might be faster: https://twitter.com/fedor/status/1354505744293502980

### CODE REVIEW

**Comment by hebasto** [comment]
No speed up observed?

**Comment by laanwj** [comment]
> No speed up observed?

Strange.

I wonder how much our tests are really bound by I/O speed. I guess it could matter for compilation times. But I wouldn't be surprised if it's mostly CPU bound.

**Comment by MarcoFalke** [comment]
It seems this will result in a slow-down. E.g. https://cirrus-ci.com/task/6631575736549376?command=ci#L5821 vs https://cirrus-ci.com/task/5477946514210816?command=ci#L5513

Looks like it is only using 0.3 CPU even though 2 have been requested?

**Comment by MarcoFalke** [comment]
Let's revisit this some other time

**Comment by MarcoFalke** [comment]
Testing ...

**Review by fanquake — APPROVED** [review]
ACK fa212391ce0bb04669bc5205553a71e653f5ad48 - going to merge this now given there is a speedup, and it's enough to fix the fuzz task the is continually timing out.

**Pull request merged**
