### PR TITLE
test: Catch decimal.InvalidOperation from TestNodeCLI#send_cli

### PR DESCRIPTION
**Pull request by Empact**
`decimal.InvalidOperation` is a special case of a float parsing error, which
presumably should be handled in the same way as a general parsing error,
rather than blow up.

Alternatives include: logging the error, or re-raising with more information.

Example log output:
```
    File "/home/travis/build/bitcoin/bitcoin/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 603, in sync_all
      self.sync_blocks(nodes)
    File "/home/travis/build/bitcoin/bitcoin/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 568, in sync_blocks
      best_hash = [x.getbestblockhash() for x in rpc_connections]
    File "/home/travis/build/bitcoin/bitcoin/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 568, in <listcomp>
      best_hash = [x.getbestblockhash() for x in rpc_connections]
    File "/home/travis/build/bitcoin/bitcoin/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_node.py", line 571, in __call__
      return self.cli.send_cli(self.command, *args, **kwargs)
    File "/home/travis/build/bitcoin/bitcoin/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_node.py", line 639, in send_cli
      return json.loads(cli_stdout, parse_float=decimal.Decimal)
    File "/usr/lib64/python3.6/json/__init__.py", line 367, in loads
      return cls(**kw).decode(s)
    File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
      obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    File "/usr/lib64/python3.6/json/decoder.py", line 355, in raw_decode
      obj, end = self.scan_once(s, idx)
  decimal.InvalidOperation: [<class 'decimal.InvalidOperation'>]
```
See: https://travis-ci.org/github/bitcoin/bitcoin/jobs/713502326

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Too bad the stdout isn't available. I presume it is something like "connection reset"?

ACK

**Comment by laanwj** [comment]
ACK 82fc4017b774aaff8799c2b6e8ba5370d94dbf4d

I don't understand what happened though. If you psas invalid input to a Decimal, you'll normally get this message:
```
>>> decimal.Decimal("sdfsdf3f")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
```
The exception message has a condition "decimal.ConversionSyntax". However in your case, the condition is`decimal.InvalidOperation` itself. Too bad we can't see the input.

**Comment by MarcoFalke** [comment]
Looks like this might happen when the quantization is too precise:

```
>>> decimal.Decimal(3).quantize(decimal.Decimal('0.000000000000000000000000000000000000000000001'), rounding=decimal.ROUND_DOWN)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
decimal.InvalidOperation: [<class 'decimal.InvalidOperation'>]
```

or

```
>>> decimal.Decimal('inf')*0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
decimal.InvalidOperation: [<class 'decimal.InvalidOperation'>]
```

See https://docs.python.org/3.8/library/decimal.html#decimal.InvalidOperation

Though, still no idea how that could happen in our test framework.

**Comment by laanwj** [comment]
It looks like it also happens if some limit is exceeded e.g. `decimal.Decimal("1e9999999999999999999")` (wasn't able to trigger this with just a long number without exponent). This would be possible to trigger though unlikely.

**Pull request merged**
