### PR TITLE
[backport] #14679 importmulti: Don't add internal addresses to address book

### PR DESCRIPTION
**Pull request by fanquake**

### CODE REVIEW

**Comment by jonasschnelli** [comment]
utACK ae1b6756c96f78985e88fa5b0c68ccad90f5e259

**Comment by laanwj** [comment]
utACK ae1b6756c96f78985e88fa5b0c68ccad90f5e259

**Comment by instagibbs** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/14900/commits/ae1b6756c96f78985e88fa5b0c68ccad90f5e259

**Comment by promag** [comment]
Ref #14679.

ACK ae1b675, repeated the rebase and verified the changes.

I wonder if #14410 should be backported?

**Comment by sipa** [comment]
utACK ae1b6756c96f78985e88fa5b0c68ccad90f5e259

**Comment by instagibbs** [comment]
@promag depends on when the point release should be going out.

**Pull request merged**
