### PR TITLE
build: explicitly disable libsecp256k1 openssl based tests

### PR DESCRIPTION
**Pull request by fanquake**
These tests are failing when run against OpenSSL 3, and have been
removed upstream, bitcoin-core/secp256k1#983, so
disabled them for now to avoid `make check` failures.

Note that this will also remove warning output from our build, due to
the use of deprecated OpenSSL API functions. See bitcoin#23048.

### CODE REVIEW

**Comment by fanquake** [comment]
cc @real-or-random @jonasnick

**Comment by fanquake** [comment]
Guix Build:
```bash
bash-5.1# find guix-build-$(git rev-parse --short=12 HEAD)/output/ -type f -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum
618833fd227e172fd904df15751f1a8f5ca04673e3bfc650ea7b5b9882d51dc9  guix-build-2f1c6a4020b0/output/aarch64-linux-gnu/SHA256SUMS.part
66aa0768a7d2505ec51fc4a7b44a8da5dfd2fb533ea516bd70f37203644cfa5a  guix-build-2f1c6a4020b0/output/aarch64-linux-gnu/bitcoin-2f1c6a4020b0-aarch64-linux-gnu-debug.tar.gz
1b86c53fd9ed8a867f6e7caf14ef232c51a17f5e3fb994c36d35a4513be912b8  guix-build-2f1c6a4020b0/output/aarch64-linux-gnu/bitcoin-2f1c6a4020b0-aarch64-linux-gnu.tar.gz
58d0f1d151b99bf7e44dfa0748a6aa1fcb89d89df2bd24a30d8a586bc9ab38e4  guix-build-2f1c6a4020b0/output/arm-linux-gnueabihf/SHA256SUMS.part
13c2913a1a46faefe0bbdc609c6fc703b2f10c39b8d83dfc74c3dc4c5eb1d334  guix-build-2f1c6a4020b0/output/arm-linux-gnueabihf/bitcoin-2f1c6a4020b0-arm-linux-gnueabihf-debug.tar.gz
c906658aa787215fa889595ab1bccde6cd1d3ad16767e0253842470c57a3016c  guix-build-2f1c6a4020b0/output/arm-linux-gnueabihf/bitcoin-2f1c6a4020b0-arm-linux-gnueabihf.tar.gz
deee78f99870e06f510aa464ef0ea6f2e9984c083af4092c947f7dc8d3230f16  guix-build-2f1c6a4020b0/output/dist-archive/bitcoin-2f1c6a4020b0.tar.gz
eefa7baa957301b13bd0cbca102a81c93f98fbdb8ddb2e6356334e0edc1ad7fe  guix-build-2f1c6a4020b0/output/powerpc64-linux-gnu/SHA256SUMS.part
c4ebf784c60be309b66e8aae5cd2135e27073b44999fd0d035101c81c2853c4c  guix-build-2f1c6a4020b0/output/powerpc64-linux-gnu/bitcoin-2f1c6a4020b0-powerpc64-linux-gnu-debug.tar.gz
60942e1991e39bede0aed8b1b6ad0b5f35b769d8ece82e023729cb9c6afeced3  guix-build-2f1c6a4020b0/output/powerpc64-linux-gnu/bitcoin-2f1c6a4020b0-powerpc64-linux-gnu.tar.gz
e0ecc5ca8032b4c51b80b814ca18489e639d96bb7dd4055998c73706b5704508  guix-build-2f1c6a4020b0/output/powerpc64le-linux-gnu/SHA256SUMS.part
0db0a7cac0cb8798566d9a87da5a1670c6d9b6aeea6baefd8167b4bd990882b7  guix-build-2f1c6a4020b0/output/powerpc64le-linux-gnu/bitcoin-2f1c6a4020b0-powerpc64le-linux-gnu-debug.tar.gz
f427f2f82a6c1ec8eea34ff27139c43eae7314de769a554adc9986497c85af1b  guix-build-2f1c6a4020b0/output/powerpc64le-linux-gnu/bitcoin-2f1c6a4020b0-powerpc64le-linux-gnu.tar.gz
edfd2c65bca776708b6fd5883e646643305cd571557fee4b15b49786bef91a52  guix-build-2f1c6a4020b0/output/riscv64-linux-gnu/SHA256SUMS.part
aac59ce3af05337d8a25a555b36c0547a0c6bd2f30e3f9ef198677e7793b0153  guix-build-2f1c6a4020b0/output/riscv64-linux-gnu/bitcoin-2f1c6a4020b0-riscv64-linux-gnu-debug.tar.gz
7f675a459773a852f279cbb9e4191deaa40066654fdd5278a627785ffab8f9e4  guix-build-2f1c6a4020b0/output/riscv64-linux-gnu/bitcoin-2f1c6a4020b0-riscv64-linux-gnu.tar.gz
c71b9081389cd9927c51ed0a071056adc7d4da0fc05552d7d8056efbc7cf50be  guix-build-2f1c6a4020b0/output/x86_64-apple-darwin19/SHA256SUMS.part
79982783e267d09f7d38d9bd00bfefa71147dee6d3c7d3550cfe7b1c4a8bb4db  guix-build-2f1c6a4020b0/output/x86_64-apple-darwin19/bitcoin-2f1c6a4020b0-osx-unsigned.dmg
627c6f2090e4484fefc0e54be979289ff46b803bd4a601d966c4c14118cf0abf  guix-build-2f1c6a4020b0/output/x86_64-apple-darwin19/bitcoin-2f1c6a4020b0-osx-unsigned.tar.gz
1c1115142985b6b42637a3bfb74592310bfd7c68ad2a85753d2f4ca894496dc5  guix-build-2f1c6a4020b0/output/x86_64-apple-darwin19/bitcoin-2f1c6a4020b0-osx64.tar.gz
a291a8e741ad801064c030c48dd5d639d90a82d8ee23a3ea6baa756a7b9e1806  guix-build-2f1c6a4020b0/output/x86_64-linux-gnu/SHA256SUMS.part
2c5efb07524d3dc181d8464106e4000561cb0d8dbd1032226b8d51c6cc3dc9a4  guix-build-2f1c6a4020b0/output/x86_64-linux-gnu/bitcoin-2f1c6a4020b0-x86_64-linux-gnu-debug.tar.gz
6485d7dfd76d77fd1e5753e076a26e34fdb169c5c65625f3cb480b915aaf1680  guix-build-2f1c6a4020b0/output/x86_64-linux-gnu/bitcoin-2f1c6a4020b0-x86_64-linux-gnu.tar.gz
0bf1680d57e1bf8f3a3e0aef80a4f6875edafc0e0fa0d7ad028912b1e6377157  guix-build-2f1c6a4020b0/output/x86_64-w64-mingw32/SHA256SUMS.part
44dd818647b28822744a33035a8f99d790f74e7dd8e86d8a3d5d46a878887ce7  guix-build-2f1c6a4020b0/output/x86_64-w64-mingw32/bitcoin-2f1c6a4020b0-win-unsigned.tar.gz
3a58957bd6c6d9bc7eea6b70d783b1e4a6fda8d87d0ced3ea68c3bb9560382f6  guix-build-2f1c6a4020b0/output/x86_64-w64-mingw32/bitcoin-2f1c6a4020b0-win64-debug.zip
a25bc1abb3b4586cebd107cae1412efe05fb46290960c63accc66e0b56b84acc  guix-build-2f1c6a4020b0/output/x86_64-w64-mingw32/bitcoin-2f1c6a4020b0-win64-setup-unsigned.exe
30df3aaa0ce85e1142cfcded64bb1a92c55cdb634ee7f2e725d338f09518fb36  guix-build-2f1c6a4020b0/output/x86_64-w64-mingw32/bitcoin-2f1c6a4020b0-win64.zip
```

**Comment by fanquake** [comment]
> If you are going to backport a --disable-openssl-tests to 22.x,

> This would also avoid a successive bump in a short time.

It's not clear how soon that bump would be, and it could well be too late for 23.0

**Comment by MarcoFalke** [comment]
Is there anything in the bump that we need, assuming the test issue is fixed with a configure flag? Especially, since you are planning another bump after bitcoin-core/secp256k1#988 (soon?).

**Comment by fanquake** [comment]
Ok. I've changed this to just disable the tests for now, as I would like to get this merged and backported into `22.x`. I'll update #23315 to be a proper backport after this has been merged.

**Comment by fanquake** [comment]
Backported in #23315.

**Pull request merged**
