### PR TITLE
Remove P2SH coinbase flag, no longer interesting

### PR DESCRIPTION
**Pull request by luke-jr**

### CODE REVIEW

**Comment by laanwj** [comment]
utACK. It should be safe to remove now.

**Comment by maaku** [comment]
Tested ACK. That's a needlessly wasted six bytes we can recover from future coinbases.

**Comment by gavinandresen** [comment]
utACK. +1 for getting rid of code....

**Comment by laanwj** [comment]
Backported to 0.11 as c00ae64f775e10f71c108f00ab28e6eb5af94524, to 0.10 as ecc96f5ba9af206d1eb69f41d4d04f4fd014eeb3

**Pull request merged**
