### PR TITLE
refactor: Avoid UniValue copies

### PR DESCRIPTION
**Pull request by maflcko**
UniValue copies have been a source of performance related bugs and regressions, so it would be good to remove the copy constructors.

This is the first change toward the goal. This change uses a `const UniValue&` where possible.

See also:

* https://github.com/bitcoin-core/univalue-subtree/pull/27
* https://github.com/bitcoin/bitcoin/pull/15974

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Review note: `const` will compile, but kill performance when `std::move` or RVO is intended.

**Comment by theStack** [comment]
Concept ACK

**Comment by fanquake** [comment]
cc @martinus

**Comment by MarcoFalke** [comment]
I am actually not sure how to fix *all* copies. Sometimes the std lib will copy if asked to:


```cpp
std::vector<UniValue> a;
std::vector<UniValue> b;
a.insert(a.end(), b.begin(), b.end());

**Comment by laanwj** [comment]
I guess you could add an explicit 'clone' method (like rust) and use that when it's really necessary to make a copy. It will probably make some things much more verbose though.

**Comment by martinus** [comment]
> a.insert(a.end(), b.begin(), b.end());

In that case you can use

```cpp
a.insert(a.end(), std::make_move_iterator(b.begin()), std::make_move_iterator(b.end()));
```

But I there might still be case where copy constructor is necessary, I remember that I had difficulties in my old PR as well

**Comment by fanquake** [comment]
Concept ACK

**Review by fanquake — APPROVED** [review]
ACK bbbbcfdb8e87f3151229ebc8c7b812a420d89b14 - as a first step.

**Comment by MarcoFalke** [comment]
While the changes are correct, I'll try to make them easier to review and more complete. For now, please review actual UniValue-copy bugfixes, like https://github.com/bitcoin/bitcoin/pull/25464

**Comment by hebasto** [comment]
Concept ACK.

**Pull request closed without merging**
