### PR TITLE
Use C++ initializer to initialze map and implement map comparator as const

### PR DESCRIPTION
**Pull request by cg31**
The first change will avoid a cast. And the second makes code more compliant.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Trivial ACK b28f8c0bcfaaa81f83a1d53e0e63f6293ecc3d2f.

**Review by dcousens — APPROVED** [review]
utACK

**Review by ryanofsky — COMMENTED** [review]
utACK b28f8c0bcfaaa81f83a1d53e0e63f6293ecc3d2f

(This PR prompted me to spend the last half hour reading about how this list initialization actually works. I found https://stackoverflow.com/questions/24718555/what-language-rules-permit-c11-to-deduce-that-this-is-an-initializer-list-of-p, which I thought provided a very helpful q&a, in case anyone else was curious.)

**Comment by fanquake** [comment]
utACK b28f8c0
Please squash the merge commit.

**Comment by fanquake** [comment]
@cg31 Looks like you've introduced some unrelated commits.

**Comment by sipa** [comment]
@cg31 You'll need to rebase on master to get rid of the merge commits.

**Comment by MarcoFalke** [comment]
@cg31 To get rid of the merge commit:

```sh
git checkout master
git reset --hard  b28f8c0
git push origin master -f

**Comment by fanquake** [comment]
@benma Thanks for the contribution here, but I'm going to close this in favour of #10545 which covers the whole codebase. If you'd like to review over there it would be appreciated.

**Pull request closed without merging**
