### PR TITLE
0.11

### PR DESCRIPTION
**Pull request by barkinet**
gpg: keyring `/tmp/tmperoj050l/secring.gpg' created
gpg: keyring`/tmp/tmperoj050l/pubring.gpg' created
gpg: requesting key 8842CE5E from hkp server keyserver.ubuntu.com
gpg: /tmp/tmperoj050l/trustdb.gpg: trustdb created
gpg: key 8842CE5E: public key "Launchpad PPA for Bitcoin" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
ubuntu14.04

### CODE REVIEW

**Comment by barkinet** [comment]
gpg: keyring `/tmp/tmperoj050l/secring.gpg' created
gpg: keyring `/tmp/tmperoj050l/pubring.gpg' created
gpg: requesting key 8842CE5E from hkp server keyserver.ubuntu.com
gpg: /tmp/tmperoj050l/trustdb.gpg: trustdb created
gpg: key 8842CE5E: public key "Launchpad PPA for Bitcoin" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK

**Comment by barkinet** [comment]
engineering2015@engineer:~$ git clone https://github.com/barkinet/bitcoin.git
Cloning into 'bitcoin'...
remote: Counting objects: 54403, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 54403 (delta 0), reused 0 (delta 0), pack-reused 54401
Receiving objects: 100% (54403/54403), 48.93 MiB | 485.00 KiB/s, done.
Resolving deltas: 100% (39292/39292), done.
Checking connectivity... done.
engineering2015@engineer:~$ sudo add-apt-repository ppa:bitcoin/bitcoin
[sudo] password for engineering2015: 
 Stable Channel of bitcoin-qt and bitcoind for Ubuntu, and their dependencies
 More info: https://launchpad.net/~bitcoin/+archive/ubuntu/bitcoin
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keyring `/tmp/tmperoj050l/secring.gpg' created
gpg: keyring `/tmp/tmperoj050l/pubring.gpg' created
gpg: requesting key 8842CE5E from hkp server keyserver.ubuntu.com
gpg: /tmp/tmperoj050l/trustdb.gpg: trustdb created
gpg: key 8842CE5E: public key "Launchpad PPA for Bitcoin" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
engineering2015@engineer:~$

**Comment by jgarzik** [comment]
broken PR

**Comment by laanwj** [comment]
@barkinet Stop opening these spurious pull requests. This is the second one in a month: https://github.com/bitcoin/bitcoin/pulls?utf8=%E2%9C%93&q=+is%3Apr+author%3Abarkinet+

Not sure why you're doing this, but the goal of pull requests is to send your own code changes for inclusion, as documented here: https://help.github.com/articles/using-pull-requests/

**Pull request closed without merging**
