### PR TITLE
depends: don't use OpenGL in Qt on macOS

### PR DESCRIPTION
**Pull request by fanquake**
Based on #17663. OpenGL on macOS was also deprecated in 10.14.

This also removes the `/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL` dylib from `bitcoin-qt`.

### CODE REVIEW

**Comment by laanwj** [comment]
ACK 2359a4790d93ffd17b8afc2fea3775dd858ef50d

**Review by hebasto — APPROVED** [review]
ACK 2359a4790d93ffd17b8afc2fea3775dd858ef50d

Ref: [About OpenGL for OS X](https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/OpenGL-MacProgGuide/opengl_intro/opengl_intro.html)

Should `contrib/macdeploy/macdeployqtplus` be changed too?

**Comment by laanwj** [comment]
I don't *think* so, the only OpenGL related code there conditionally adds the OpenGL graphicssystem plugin:
```
            elif pluginPath == "graphicssystems/libqglgraphicssystem.dylib":
                # Deploy the opengl graphicssystem plugin only if QtOpenGL is in use
                if not deploymentInfo.usesFramework("QtOpenGL"):
                    continue
```
We don't use dynamically-loaded Qt plugins in the first place.

**Comment by fanquake** [comment]
> Should contrib/macdeploy/macdeployqtplus be changed too?

@laanwj is correct, nothing in that script needs to be changed.

**Comment by jonasschnelli** [comment]
Nice cleanup.
utACK 2359a4790d93ffd17b8afc2fea3775dd858ef50d

**Pull request merged**
