### PR TITLE
util: Safer MakeByteSpan with ByteSpanCast

### PR DESCRIPTION
**Pull request by maflcko**
The `AsBytes` helpers (or `std::as_bytes` helpers) are architecture
dependent. For example, the below test case diff [0], applied before
this commit will pass on x86_64, but fail on s390x [1].

Fix this by replacing `AsBytes` with a new `ByteSpanCast` in the `MakeByteSpan` helper.
This will turn the test case diff into a compile failure instead of a runtime error.

[0] test case diff:

```diff
diff --git a/src/test/serialize_tests.cpp b/src/test/serialize_tests.cpp
index 09f77d2b61..4e56ffa351 100644
--- a/src/test/serialize_tests.cpp
+++ b/src/test/serialize_tests.cpp
@@ -241,6 +241,15 @@ BOOST_AUTO_TEST_CASE(class_methods)
     ss2 << intval << boolval << stringval << charstrval << txval;
     ss2 >> methodtest3;
     BOOST_CHECK(methodtest3 == methodtest4);
+
+    {
+        DataStream out;
+        std::vector<uint8_t> in_8{0x00, 0x11, 0x22, 0x33};
+        std::vector<uint16_t> in_16{0xaabb, 0xccdd};
+        out.write(MakeByteSpan(in_8));
+        out.write(MakeByteSpan(in_16));
+        BOOST_CHECK_EQUAL(HexStr(out), "00112233bbaaddcc");
+    }
 }

 BOOST_AUTO_TEST_SUITE_END()
```

[1] test case failure on s390x:
`test/serialize_tests.cpp(251): error: in "serialize_tests/class_methods": check HexStr(out) == "00112233bbaaddcc" has failed [00112233aabbccdd != 00112233bbaaddcc]`

### CODE REVIEW

**Comment by ryanofsky** [comment]
> Maybe MakeByteSpan should just be removed?

I don't think I agree. `MakeByteSpan(x)` is just equivalent to `AsBytes(Span{x})` currently, so right now it is pointless. But if we go ahead with this PR and restrict it to only work on character arrays, that will actually make it safer and actually useful.

> it seems pointless trying to offer a safe MakeByteSpan wrapper with only a docstring suggesting to use it.

I don't think it's pointless to have a safe function even though a dangerous alternative exists. If I'm writing or reviewing code that uses a safe implementation of `MakeByteSpan` I can be more confident it is doing the right thing than if I see code using `AsBytes`. Just like if I'm reviewing code that is using `UCharCast` I can be more confident in it than code using an `(unsigned char)` cast.

I think it would be a good thing to discourage use of `AsBytes` and provide some safer alternative where possible. That alternative doesn't have to be `MakeByteSpan`, but if we have a `MakeByteSpan` function now and can document it and make it safer, I think it'd be good to do that.

**Comment by ryanofsky** [comment]
> > If I'm writing or reviewing code that uses a safe implementation of MakeByteSpan I can be more confident it is doing the right thing than if I see code using AsBytes.
> 
> Would you be less confident if there was a clang-tidy plugin doing the check? For example, instead of having two functions that do a similar thing, but it is unclear which one is safer/preferred from just looking at the name, we could have an additional `UnsafeAsBytes` (or similar), where it is clear that using it without looking up what it does is unsafe.

I think that sounds fine, though I'm not sure what the clang plugin adds exactly. If the goal is just to forbid `AsBytes` from being called on non-char arrays, we could change the definition of `AsBytes` to do that (probably using UCharCast internally), and provide an additional `UnsafeAsBytes` escape hatch for the cases where that doesn't work. But maybe a clang plugin could be useful to prevent `std::as_bytes` calls?.

I just think as long as we have a `MakeByteSpan` function and can make it safer, it seems good to do that. Or at least that doing that would be better than getting rid of `MakeByteSpan` and replacing it with calls to `AsBytes` when `AsBytes` is not very safe right now. But if there's something that can we can do to make `AsBytes` safer, I'd agree there be little use for a safer `MakeByteSpan`

**Comment by ryanofsky** [comment]
> FWIW, I don't believe `AsBytes` (or `std::as_bytes`) are ever undefined behavior

Yes that should be true as long as span is pointing to live memory. I should replace "platform specific or undefined" with "implementation specific" in the #27978 change description

**Review by PRADACANDI18 — COMMENTED** [review]
General feed back have I have not given approval just yet on a merge. I have to review some more

**Pull request closed without merging**
