### PR TITLE
qa: Note on test order in test_runner

### PR DESCRIPTION
**Pull request by maflcko**
C.f. #11964

### CODE REVIEW

**Comment by promag** [comment]
utACK fa2333f.

Nit, should new tests be added at the end of the run-time section or should there be an effort to keep them sorted?

**Comment by thijstriemstra** [comment]
I would clarify it a little more, e.g.

```
# Don't add tests below this comment to avoid merge conflicts
# Put them in a location above this comment based on their approximate run-time
```

**Comment by MarcoFalke** [comment]
@promag Adding at the end of run-time sections doesn't help with merge conflict. Sorting by name would. Though, since we plan to rename the tests, I don't want to go in this direction.
@thijstriemstra Reworked wording a bit.

**Comment by jnewbery** [comment]
utACK fadf60e381006aa27689971771e83426fb7c0daa

**Pull request merged**
