### PR TITLE
init, doc: improve -onlynet help and related tor/i2p documentation

### PR DESCRIPTION
**Pull request by jonatack**
including review feedback from https://github.com/bitcoin/bitcoin/pull/22834#discussion_r795253056 and https://github.com/bitcoin/bitcoin/pull/24205#discussion_r818629106 concerning `src/init.cpp`, `doc/tor.md` and `doc/i2p.md`

- s/outgoing/automatic outbound/
- s/Incoming/Inbound and manual/ (are not affected by this option.)
- s/only through network/only to network/
- s/this option. This option/this option. It/
- s/network types/networks/

and pick up a few nits in `doc/p2p-bad-ports.md` from https://github.com/bitcoin/bitcoin/pull/23542#pullrequestreview-881415043.

### CODE REVIEW

**Comment by jonatack** [comment]
(could be tagged for v23.0)

**Comment by jonatack** [comment]
Targets backport for v23.

**Review by w0xlt — APPROVED** [review]
ACK a1db99a

**Review by theStack — APPROVED** [review]
LGTM.

ACK a1db99adea36dbee1ec97ca1851edad12137feea

**Comment by laanwj** [comment]
ACK a1db99adea36dbee1ec97ca1851edad12137feea

**Pull request merged**
