### PR TITLE
Update license year range to 2016

### PR DESCRIPTION
**Pull request by prayagverma**

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Please also fix it in qt.

**Comment by pra85** [comment]
@MarcoFalke Sorry for my lack of information. I am unaware of what qt means 

I was just passing through and saw the copyright year being not updated, therefore I made the pull request for the same.

I went through your previous commit ( 9be08b7fe2b6fc81afd0ff4a ) and have updated my pull request accordingly.

If this isn't what you meant, if you can point me in the direction of what needs to be done, then I would surely do that

**Comment by MarcoFalke** [comment]
Qt is our GUI framework. Please look at edbc9045cb21020d0cc19d226f55ee169e2ffb92

**Comment by pra85** [comment]
@MarcoFalke Thanks for guiding. I have updated the pull request with the changes you suggested

**Comment by laanwj** [comment]
Yes we should get rid of the duplication between clientversion.h and configure.ac some time. Note that this has nothing to do with qt.

**Comment by laanwj** [comment]
utACK

**Comment by MarcoFalke** [comment]
Our qt GUI is the most prominent sink of `COPYRIGHT_YEAR`.

**Comment by MarcoFalke** [comment]
post merge utACK  bd34174

@pra85 Thanks for sticking with this.

**Comment by pra85** [comment]
I am glad that I could be helpful in some way :smile:

**Comment by laanwj** [comment]
> Our qt GUI is the most prominent sink of COPYRIGHT_YEAR.

Yes, but see the `#if defined(HAVE_CONFIG_H)`. COPYRIGHT_YEAR comes from config/bitcoin-config.h.
Effectively, at least for build configurations that we support, the content of clientversion.h will never be used.
The duplication is there as an old crutch to support building without autotools. But there have been so many additions to bitcoin-config.h and platform detection over the last versions that this has become unrealistic anyway.

**Pull request merged**
