### PR TITLE
Use MakeUnique to construct objects owned by unique_ptrs

### PR DESCRIPTION
**Pull request by practicalswift**
Use `MakeUnique` to construct objects owned by `unique_ptr`s.

Rationale:
* `MakeUnique` ensures exception safety in complex expressions.
* `MakeUnique` gives a more concise statement of the construction.

### CODE REVIEW

**Comment by promag** [comment]
Concept ACK. Could mention `std::make_unique` is only available in c++14 so `MakeUnique` is a temporary replacement.

**Comment by practicalswift** [comment]
@promag Good point! Added. Please re-review :-)

**Comment by donaloconnor** [comment]
utACK https://github.com/bitcoin/bitcoin/commit/81f81ec022bce22c916b2964f5e38c318a828d9a :-)

**Comment by ken2812221** [comment]
utACK da15d9d3d9451b5cb3af137305a702174a9202b3

**Comment by practicalswift** [comment]
@donaloconnor Thanks for the review! I'm afraid you didn't review the latest commit. Would you mind reviewing da15d9d3d9451b5cb3af137305a702174a9202b3? :-)

**Comment by promag** [comment]
utACK da15d9d.

**Comment by MarcoFalke** [comment]
Thanks, but this can be changed the next time someone touches the function(s).
No need for a separate patch.

Pull requests without a rationale and clear improvement may be closed
immediately.

Please provide clear motivation for your patch and explain how it improves
Bitcoin Core user experience or Bitcoin Core developer experience
significantly.

* Any test improvements or new tests that improve coverage are always welcome.
* Features are always welcome, but might be rejected early in the review
  process.
* Bug fixes are most welcome when they come with steps to reproduce or an
  explanation of the potential issue as well as reasoning for the way the bug
  was fixed.
* Refactoring changes are only accepted if they are required for a feature or
  bug fix or otherwise improve developer experience significantly. For example,
  most "code style" refactoring changes require a thorough explanation why they
  are useful, what downsides they have and why they *significantly* improve
  developer experience or avoid serious programming bugs. Note that code style
  is often a subjective matter. Unless they are explicitly mentioned to be
  preferred in the [developer notes](/doc/developer-notes.md), stylistic code
  changes are usually rejected.
* All changes should have accompanying unit tests (see `src/test/`) or
  functional tests (see `test/`).  PR authors should note which tests cover
  modified code. If no tests exist for a region of modified code, new tests
  should accompany the change.

Bitcoin Core has a thorough review process and even the most trivial change
needs to pass a lot of eyes and requires non-zero or even substantial time
effort to review. There is a huge lack of active reviewers on the project, so
patches often sit for a long time.

**Comment by MarcoFalke** [comment]
Feel free to submit the test and documentation changes separately, but we don't have the resources right now to review refactoring of core code. Also I think we are not affected by "complex expressions" that require MakeUnique to ensures exception safety.

**Comment by ryanofsky** [comment]
> we don't have the resources right now to review refactoring of core code

Could we have a tag to distinguish PRs that were closed to due lack of resources from PRs that were closed due to more substantive issues (like brokenness or lack of agreement)? It might be useful to track where we are falling behind, and maybe nice to take edge off rejection for people who submit such PRs, sort of https://en.wikipedia.org/wiki/It%27s_not_you,_it%27s_me

**Comment by MarcoFalke** [comment]
@ryanofsky A closed pull request due to lack of *author* resources is tagged with "up for grabs". A closed pull request due to lack of *reviewer* resources is usually left open until it is reviewed or closed due to a merge conflict and then also tagged with "up for grabs".

For refactoring pull requests, I don't see the need to place them "up for grabs", since the same topics come up frequently every couple of months.

**Pull request closed without merging**
