### PR TITLE
docs: Clarifying testing instructions

### PR DESCRIPTION
**Pull request by benthecarman**
This statement confused me on my first time reading through.  Hopefully, this addition will help someone else on their first time.

### CODE REVIEW

**Comment by sipa** [comment]
Is this needed? I never use those options

**Comment by benthecarman** [comment]
> Is this needed? I never use those options

If that's true it might be better to change it to say "Be sure not to disable wallet, utils ..."

**Comment by fanquake** [comment]
If the sentence is confusing I'd rather we just remove it. I don't think we need to add explicit documentation for options that are enabled by default.

**Comment by laanwj** [comment]
Also tend to NACK. The tests are built by default, on purpose. It is a matter of following the build steps for whatever platform, no need to duplicate the command-line here.

**Comment by benthecarman** [comment]
Changed it so it now gives a link to build instructions instead

**Comment by jnewbery** [comment]
"Before tests can be run locally, your system must be built." isn't correct. You need to build bitcoind *for your system* (eg linux, macos, etc), not build your system.

ACK adding a reference to the build instructions.

**Comment by jonasschnelli** [comment]
ACK 127e37e7fcd426c990a6e4c49af9d1c35e76d384

**Comment by fanquake** [comment]
utACK 127e37e

**Comment by jnewbery** [comment]
ACK ef5ebc6d8f11f86ae53f18ef6a20bddbf73ef4e1

**Comment by hebasto** [comment]
utACK ef5ebc6d8f11f86ae53f18ef6a20bddbf73ef4e1

**Pull request merged**
