### PR TITLE
contrib: gh-merge: Include ACKs in merge commit

### PR DESCRIPTION
**Pull request by maflcko**
This includes all up-to-date ACKs in the merge commit for reference

### CODE REVIEW

**Comment by laanwj** [comment]
I think including all review/PR comments in the merge commit is overkill, it already tends to be hard to read the history with `git log -p` because the long, not-for-console formatted text that gets included from the opening post.

**Comment by MarcoFalke** [comment]
With review comments I mean only the ACKs (adjusted title)

**Comment by MarcoFalke** [comment]
Example:
```
commit 67e54064294326b8fba1c420aaa1b8afb084bf25 (HEAD -> pull/15463/local-merge)
Merge: abd914ed34 643eba0aa2
Author: MarcoFalke <falke.marco@gmail.com>
Date:   Fri Mar 22 12:33:22 2019 -0400

    Merge #15463: rpc: Speedup getaddressesbylabel
    
    643eba0aa2 rpc: Speedup getaddressesbylabel (João Barbosa)
    
    Pull request description:
    
      Fixes #15447. Same approach of #14984, this change avoids duplicate key check when building the JSON response in memory.
    
    ACKs for commit 643eba:
      ryanofsky:
        utACK 643eba0aa262ead636d5de18ced31b6f166ec033
      MeshCollider:
        utACK https://github.com/bitcoin/bitcoin/pull/15463/commits/643eba0aa262ead636d5de18ced31b6f166ec033
    
    Tree-SHA512: ee0941130ada600171d36cf69219921ab2fa044402cedc57cdf73bdb23499555c53bc076d65ef117d0a8f5cbc5381a49e40d945766796241936a701678b72ab6

**Comment by laanwj** [comment]
> With review comments I mean only the ACKs (adjusted title)

Oh that does sound good!

**Comment by MarcoFalke** [comment]
see merge commit 68520597ccf8ff3f6e8a7ad6869b06bf2012ae8a for a live example

**Comment by jamesob** [comment]
Nice! utACK https://github.com/bitcoin/bitcoin/pull/15643/commits/fa1c073154c6a39dca878f5c9a37abee8af0fd30

**Comment by jnewbery** [comment]
Concept ACK

**Comment by practicalswift** [comment]
Concept ACK

If I'm reading the code right also NACK:s will be included under the heading "ACKs for commit"?

**Comment by MarcoFalke** [comment]
@practicalswift No, it would only show up if you NACK+the commit id

**Comment by sipa** [comment]
Concept ACK

**Comment by practicalswift** [comment]
@MarcoFalke Thanks for the clarification. I missed the `and head_commit in l` :-)

utACK fa1c073154c6a39dca878f5c9a37abee8af0fd30 (nit: a run with your `yapf` script would make it even more beautiful :-))

**Comment by laanwj** [comment]
utACK fa1c073154c6a39dca878f5c9a37abee8af0fd30

**Pull request merged**
