### PR TITLE
Remove unused variable COINBASE_FLAGS

### PR DESCRIPTION
**Pull request by murchandamus**

### CODE REVIEW

**Comment by MarcoFalke** [comment]
ACK 878af3e144a3681d1cd80cd1ccd77146a02d6f72, should have been removed in d449772cf69c01932fc5d72c46054815d6300b3c 🏭

<details><summary>Show signature and timestamp</summary>

Signature:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK 878af3e144a3681d1cd80cd1ccd77146a02d6f72, should have been removed in d449772cf69c01932fc5d72c46054815d6300b3c 🏭
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEE+rVPoUahrI9sLGYTzit1aX5ppUgFAlwqrYAACgkQzit1aX5p
pUhs/gwAkkA5X1KwxFkoWUsSaoQ3RXM+jXhc/GoclpduSW5/gFcoR6tt60VceVPc
BuOUUIGZIjk/BOU6RweDdUSo6HYhSoU0Co7FXvez6MDF2qAfZjxJuXK2GBtX6y9V
Q25OMsv6Wtx+ltgFe6+VJM7FHKfAP3L3C/XBfwQNhBDa5rDhpdPcBYGk+t0YHJn7
oIpcd0oWyEjJ06DB0UZJHuLIlMXFMNTWq4ohL9zgAFQD4XFtdoHlVCO+/NQDwqq7
62SZIRZjw+EEB1Ai7/SLQyLLxzWFNAtWZf9VIvJinNV+vQwb4FOPPpxNH2hgicSE
RYfpEuz5HkET75gc21IafJu/t+Bl3gx1woqiJxztKGv3WHPhFWtbRYTbkIMrsXEA
r/R0X0SLE+Qnn7oDvm6QgII4wK0uFReXWjL+B4zNExJjrgrgxbcpUqnSYX9Or8tF
qPJ6rAEKIfehRcfWg5IAmLf4rBM4F5OWhzIY9vXYLqJbQ8frYZb9WLuY2hYEO9w1
3gyCCLX6
=3jyh
-----END PGP SIGNATURE-----
```

[Timestamp of file with hash `1a9905c42e19c4dfae5c73093fa64854d87a67ffa53be50f21e8040cb86f9636  -`](https://opentimestamps.org/info/?004f70656e54696d657374616d7073000050726f6f6600bf89e2e884e8929401081a9905c42e19c4dfae5c73093fa64854d87a67ffa53be50f21e8040cb86f9636f0102fa141085f99feab8416f842080e4b6408fff0100b6e45d895786bbb096d8250c593043708f1045dced884f008f67ec7c4a049cfaa0083dfe30d2ef90c8e2c2b68747470733a2f2f626f622e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267fff01045768603eab5c597bab10296af8f713608f1045dced884f0084c4e51b9ec2f34250083dfe30d2ef90c8e232268747470733a2f2f6274632e63616c656e6461722e636174616c6c6178792e636f6dfff010a60b376a0834bd1b56bdfb39ca2607eb08f1045dced885f008abcd566789da4c780083dfe30d2ef90c8e292868747470733a2f2f66696e6e65792e63616c656e6461722e657465726e69747977616c6c2e636f6df010a83eb68c3d86c04f0f3a88b7b523d00508f120f2038e5aac8babe2be5613340ef72307d97e4f6a9c360cd390c5e662aa1d7b9c08f1045dced884f0089fe0877e4bc74c0a0083dfe30d2ef90c8e2e2d68747470733a2f2f616c6963652e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267)

</details>

**Comment by MarcoFalke** [comment]
Oh, looks like it is still used in `miner.cpp`:

```
$ git grep COINBASE_FLA
src/miner.cpp:    txCoinbase.vin[0].scriptSig = (CScript() << nHeight << CScriptNum(nExtraNonce)) + COINBASE_FLAGS;
src/rpc/mining.cpp:    aux.pushKV("flags", HexStr(COINBASE_FLAGS.begin(), COINBASE_FLAGS.end()));
src/validation.h:extern CScript COINBASE_FLAGS;

**Comment by MarcoFalke** [comment]
So it might be better to move it to miner.h,cpp. It is confusing to have this sit in validation.h,cpp

**Comment by Xekyo** [comment]
Ah, my bad. Closing then, as I guess this falls into the refactors section rather than a simple deletion.

**Comment by laanwj** [comment]
But what is the point of it, if it's never assigned a value?

**Comment by jnewbery** [comment]
Concept ACK on removal. `COINBASE_FLAGS` has not been used since BIP 16/17 signalling.

I think @narula is planning to pick this one up.

**Pull request closed without merging**
