### PR TITLE
Set jonasschnellis dns-seeder filter flag

### PR DESCRIPTION
**Pull request by jonasschnelli**
Test can be done with something like:

```
dig x9.seed.bitcoin.jonasschnelli.ch
```

### CODE REVIEW

**Comment by laanwj** [comment]
tACK https://github.com/bitcoin/bitcoin/pull/8573/commits/40a95cfd8f21bedbf35016b920f26c19bfb25c69

**Comment by btcdrak** [comment]
tACK 40a95cf

**Comment by fanquake** [comment]
utACK 40a95cf

**Comment by sipa** [comment]
utACK

**Pull request merged**
