### PR TITLE
MOVEONLY-ish: Move most block header validation function defintions to consensus/blockverify.cpp

### PR DESCRIPTION
**Pull request by jtimon**
Right after #5975 is merged I would open this PR so I think it makes sense to open it already in case both things can be merged at once, and also to simplify #6051 dependecies.

Note that this is no longer depedendent on #5696 nor #5669

### CODE REVIEW

**Comment by jtimon** [comment]
Closing until #5696 is resolved

**Comment by jtimon** [comment]
Reopened as independent from #5696

**Comment by theuni** [comment]
NACK. Why?

#5696 has several ACKs and is likely to be merged very quickly. Those changes have gone through half a dozen iterations, but never been merged because they're constantly moving in and out of PRs. Now you've tacked it on to something else that will need more review, essentially putting the brakes on it again. Worse yet, it fails to build.

Please, just wait for one chunk at a time. This is getting out of hand.

**Comment by jtimon** [comment]
I'm sorry, I just wanted to show that this (and everything necessary to expose VerifyHeader) is independent from #5696, from whether MANDATORY_SCRIPT_VERIFY_FLAGS is consensus, policy, or none of them. And if the includes in #5696 (not so many now that the policy stuff is left out) trigger a rebase (like they have done many times before), this could still not need rebase and have an older commit ID the replacement of https://github.com/jtimon/bitcoin/commit/691161d419fe3d82d7a49b511ef80e2b24332aac.
I also wanted to show additional motivation for  #5975 (or maybe merge both together, it's not that big of a change), for example, to support the argument for merging #5975 before #6055.

About the building error, I don't know why forgetting .h files in the makefile doesn't fail in my computer, but fixed.

Anyway, even if it's independent from #5696, merging one would trigger a trivial rebase on the other, so closing until #5696 and #5975.

**Comment by sipa** [comment]
Try "make distcheck", which builds a source package abd rebuilds from that.
If you don't do that (and this has bitten me as well), you risk that the
build uses files from the repository which are not listed as source files
in the build system.

**Comment by jtimon** [comment]
Thank you @sipa . Oh, I actually forgot to close the PR

**Pull request closed without merging**
