### PR TITLE
contrib/init: (OpenRC) use -daemonwait to wait for startup completion

### PR DESCRIPTION
**Pull request by whitslack**
When other initscripts depend on bitcoind, it's because their daemons want to be able to invoke `bitcoin-cli` or to communicate with bitcoind via RPC. That can't happen until some time after bitcoind has forked into the background when it is started with the `-daemon` option. The `-daemonwait` option was added in 92cf3a22e (#21007) to address exactly this issue, so let's use it.

To avoid blocking startup for arbitrarily long, as users would be annoyed if `agetty`/`display-manager` doesn't start quickly, we now mark the `bitcoind` service initially as inactive at startup and then call back to OpenRC to mark the service as started (and proceed to start any dependent services) after bitcoind forks into the background.

This PR is a replacement for withdrawn PRs #22285 and #22354.

### CODE REVIEW

**Comment by laanwj** [comment]
Concept ACK, this is exactly what daemonwait is for.

**Comment by whitslack** [comment]
Has this PR stalled because no one with commit privilege uses OpenRC?

**Comment by luke-jr** [comment]
Concept ACK, but it feels hacky and I don't know OpenRC well enough to comment on whether this is just normal practice for similar services or not.

(Also, nit, would prefer to keep the command variables?)

**Comment by whitslack** [comment]
> Concept ACK, but it feels hacky and I don't know OpenRC well enough to comment on whether this is just normal practice for similar services or not.

`mark_service_inactive` and `IN_BACKGROUND` *are* hacky, but that's how OpenRC does it. See [OpenVPN](https://github.com/gentoo/gentoo/blob/master/net-vpn/openvpn/files/openvpn-2.1.init) for an example of another service that starts up in the inactive state and [calls back](https://github.com/gentoo/gentoo/blob/dd1ebe44dd72ec2435687095d063644ec94d8b8e/net-vpn/openvpn/files/up.sh#L93-L94) into OpenRC later when the service is fully up and running. OpenVPN performs the callback from a script that the daemon spawns after establishing the VPN tunnel. That's how I originally implemented it for Bitcoin Core too, using the `-startupnotify` option, but I was told to use `-daemonwait` instead, so now the callback happens from a backgrounded subshell after `bitcoind` forks into the background.

> (Also, nit, would prefer to keep the command variables?)

The default `start()` function, which uses those variables, doesn't support marking the service inactive at startup or forking a subshell to the background. I could rewrite my `start()` in terms of those variables if you really like to see the variables, but I think that's more confusing than inlining the values directly in the function.

Do you have any other ideas for how to fix the problem? To remind: the problem is that, using the currently shipped runscript, the `bitcoind` service reaches the `started` state despite not actually being ready to accept RPC requests from dependent services. OpenRC then starts dependent services, which immediately fail because `bitcoind` refuses their RPCs. The most straightforward solution is simply to add `-daemonwait` to the command line, but you (@luke-jr) expressed a concern about that potentially holding up the boot process for an unacceptably long time, so I addressed that concern with the background hack.

Are we just going to concede that the problem is unsolvable?

**Comment by achow101** [comment]
> Are we just going to concede that the problem is unsolvable?

This PR does not seem to have conceptual support.

**Comment by whitslack** [comment]
For posterity: note that Gentoo switched to shipping [its own local version](https://github.com/gentoo/gentoo/blob/380aad5fc649a00ae46644c130fb9a3b8970ee09/net-p2p/bitcoin-core/files/bitcoind.openrc) of the OpenRC runscript for Bitcoin Core last year because this PR had stalled.

**Pull request closed without merging**
