### PR TITLE
build, qt: Make QWindowsVistaStylePlugin available again (regression)

### LINKED ISSUE #303: Remove indented/raised borders elements on Windows
Somewhere between the last GUI update and current master 4cfe6c37d956be58e6228f50833d25b84aafe55a the Windows version of the GUI has these indented / raised border designs applied to them which has resulted in a very visually cluttered GUI. I think this style is only visually bad on Windows as other recent screenshots of master from macOS / Linux don't seem to be effected.  Below is an example from the overview section:

Group 265

It has also made the sections more condensed as I assume each widget has a size constraint and these borders are taking up extra space. It would be much more visually appealing to have this reverted back to the old style (like in the before above).

### LINKED ISSUE #22132: Missing windowsvista style plugin for Windows
Here's a comparison of the Bitcoin Core GUI cross-compiled from linux to Windows between `master` and `0.21`:

| Master     | 0.21         |
| ------------- | ------------- |
| master-cross | 021-cross |

Yep, there's something wrong here. We can gain some insight into what's going on with the style by leveraging the logging of static plugins introduced in 957895c715f86feaa26c806e5fa8ebb77430a926. The `master` branch already includes this commit. I cherry-picked it on top of the `0.21` branch [here](https://github.com/jarolrod/bitcoin/tree/021-static). Now if we take a look at the `debug.log` for each, we'll see the following

*0.21 Branch:*
```
2021-06-02T07:23:59Z Qt 5.9.8 (static), plugin=windows (static)
2021-06-02T07:23:59Z Static plugins:
2021-06-02T07:23:59Z  QWindowsIntegrationPlugin, version 329992
2021-06-02T07:23:59Z Style: windowsvista / QWindowsVistaStyle
```

*Master Branch:*
```
2021-06-02T04:16:06Z Qt 5.12.10 (static), plugin=windows (static)
2021-06-02T04:16:06Z Static plugins:
2021-06-02T04:16:06Z  QWindowsIntegrationPlugin, version 330752
2021-06-02T04:16:06Z Style: windows / QWindowsStyle
```

We notice that the `master` branch's style is set to `windows` while the `0.21` branch is set to `windowsvista` style. Looking at the [Qt Widgets Gallery](https://doc.qt.io/qt-5/gallery.html), you can observe that `windows` style looks like Windows 95 while `windowsvista` is the "sleeker"/"modern" [QStyle](https://doc.qt.io/qt-5/qstyle.html) for the Windows platform.

This is what has changed between `master` and `0.21` and what is causing the GUI to look straight out of the 90's (maybe this is a retro release? 🕺). 

Now, what is causing this change? Well, I'm not completely sure. Otherwise I'd open up a PR. I do have some findings:

#### Different available QStyle Keys between Qt 5.9.8 and Qt 5.12 at runtime:

Looking at the `Qt Widgets` section of the depends Qt configuration output, we can see the following styles are available:

*0.21 Branch:*
```
Qt Widgets:
  GTK+ ................................... no
  Styles ................................. Fusion Windows WindowsXP WindowsVista
```

*Master Branch:*
```
Qt Widgets:
  GTK+ ................................... no
  Styles ................................. Fusion Windows WindowsVista
```

So while it seems that in regards to how Qt is configured, `WindowsVista` style is available in both cases,  If we apply the patch below to see the available [QStyle Keys](https://doc.qt.io/qt-5/qstylefactory.html#keys) at runtime, we don't see `windowsvista` as an available key on `master`: 
```
qInfo() << QStyleFactory::keys().join(",");
```

*0.21 Branch:*
```
2021-06-02T17:43:35Z GUI: "Windows,WindowsXP,WindowsVista,Fusion"
```

*Master Branch:*
```
2021-06-02T17:03:11Z GUI: "Windows,Fusion"
```

This means that we can't use the line below to fix the issue, and so a fix would involve changes to our build system: 
```
QApplication::setStyle("windowsvista");
```

**Windows Vista Style moved to a Plugin in Qt 5.10:**

This is based off what I found while looking for this issue online:

[Source A](https://trac.videolan.org/vlc/ticket/20780)

> I have also ran into this issue with Qt 5.11.1. Qt's Windows Vista style has been moved out to a separate DLL, which is styles\qwindowsvistastyle.dll. If you add this to the package, standard windows will get back their modern look. 

[Source B](https://stackoverflow.com/questions/49587418/qt-application-becomes-windows-old-styled-after-build-on-a-buildbot)

> I found a problem. After Qt5.10.1 the "windowsvista" style becomes a plugin. So in the final deploy file windowsvistastyle.dll schould exists. I add a folder "/styles" with this .dll and a problem is gone.

[Source C](https://github.com/Ruin0x11/tiled/commit/7537fd06187591ec4d2feecbdb1fe8da88ccf5a7)

> Ship style plugins, since native styles were moved into plugins as of Qt 5.10. This includes Windows Vista style on Windows and Adwaita on Linux.

If we figure out what needs to be done on the build side to link to this plugin, then we can use a similar patch as [vlc](http://git.videolan.org/?p=vlc.git;a=blobdiff;f=modules/gui/qt/qt.cpp;h=6fdbda06fa8f8aba4c9d43eef29543b28fdeedea;hp=1128633386a3fa43fe9a59ea5f633557a9596483;hb=0630bfa0436105ae7e24051cc16031c8ce2d77f5;hpb=07c35dcde98e25fba642085ea89080d94a0698d8) to fix this and so the following is a solution:

```
 Q_IMPORT_PLUGIN(QWindowsVistaStylePlugin)
```

### PR DESCRIPTION
**Pull request by hebasto**
This PR is similar to 1be8e0f2388e243d310fe7eeb46149a690de4ddf, and, actually, it is a #21376 follow up.

Required as in Qt 5.12.x style plugins are separated.

Fixes #22132.
Fixes https://github.com/bitcoin-core/gui/issues/303.

**Note for reviewers**. Besides visual changes in the GUI, you could compare the first dozen of lines in the `debug.log` file.

---

#### Guix build:
```
$ HOSTS=x86_64-w64-mingw32 contrib/guix/guix-build
$ find guix-build-$(git rev-parse --short=12 HEAD)/output/ -type f -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  guix-build-ab86ac7739b2/output/dist-archive/SKIPATTEST.TAG
d3f05888c95d6cf6f4a0bac952d4c0bf1e271f49cb7ab92b08080b753957e5e5  guix-build-ab86ac7739b2/output/dist-archive/bitcoin-ab86ac7739b2.tar.gz
113bb86ffd2854e08d3c0c5cd3f9728f2e4fe6c7a1813bc1c4b73eb48ad6597f  guix-build-ab86ac7739b2/output/x86_64-w64-mingw32/bitcoin-ab86ac7739b2-win-unsigned.tar.gz
3fdc99754d6f26d9655a308c8847076d8fd4db8d61f4f18d8ef545894a42c10d  guix-build-ab86ac7739b2/output/x86_64-w64-mingw32/bitcoin-ab86ac7739b2-win64-debug.zip
932bb69e3eb1a617f9e337b83220c9d6a277bec421f4d78e32dffde5643eb00c  guix-build-ab86ac7739b2/output/x86_64-w64-mingw32/bitcoin-ab86ac7739b2-win64-setup-unsigned.exe
852f4c03ad049fcd6bb2ce25b3bcf4e18b90d34f7232660024b341bd7c8dd710  guix-build-ab86ac7739b2/output/x86_64-w64-mingw32/bitcoin-ab86ac7739b2-win64.zip
c6a33a193a6b128e665198dde94758acab3a5ab7fefe0c3c6617eb98ad01693d  guix-build-ab86ac7739b2/output/x86_64-w64-mingw32/inputs.SHA256SUMS
```

### CODE REVIEW

**Review by ghost — APPROVED** [review]
ACK https://github.com/bitcoin/bitcoin/pull/22133/commits/da8309ff29f0796e6649f66f2f0e5b402c6e08af

Difference that is easier to notice: Color of progress bar 🟧(Master) and 🟩(PR)

<details>

<summary>Master Branch</summary>

image

image

</details>

<details>

<summary>PR Branch</summary>

image

image

</details>

**Review by jarolrod — COMMENTED** [review]
~~ACK da8309ff29f0796e6649f66f2f0e5b402c6e08af~~

Tested cross-compile from both Arch Linux and Ubuntu, also tested with `make deploy`. 

**Comparison of Debug Logs:**

Master branch:

```
2021-06-02T04:16:06Z Qt 5.12.11 (static), plugin=windows (static)
2021-06-02T04:16:06Z Static plugins:
2021-06-02T04:16:06Z  QWindowsIntegrationPlugin, version 330752
2021-06-02T04:16:06Z Style: windows / QWindowsStyle
```

PR Branch:

```
2021-06-02T19:48:25Z Qt 5.12.11 (static), plugin=windows (static)
2021-06-02T19:48:25Z Static plugins:
2021-06-02T19:48:25Z  QWindowsIntegrationPlugin, version 330752
2021-06-02T19:48:25Z  QWindowsVistaStylePlugin, version 330752
2021-06-02T19:48:25Z Style: windowsvista / QWindowsVistaStyle
```

**Comparison of GUI Visual Style:**

| Master  | PR          |
| ----------- | ----------- |
| master-cross | bitcoin-22133 |

*< reserved for GUIX hashes >*

**Comment by jarolrod** [comment]
retracting ACK

Will need to update `build_msvc` -> https://ci.appveyor.com/project/DrahtBot/bitcoin/builds/39434710#L31

**Comment by hebasto** [comment]
MSVC build fixed.

**Comment by laanwj** [comment]
Concept and code review ACK ab86ac7739b27f2c45ae72ce4c4ebecf324b3e90

**Comment by hebasto** [comment]
Guix build hashes updated in the OP.

**Review by fanquake — APPROVED** [review]
ACK ab86ac7739b27f2c45ae72ce4c4ebecf324b3e90

```bash
  adding: bitcoin-ab86ac7739b2/bin/test_bitcoin.exe.dbg (deflated 81%)
  adding: bitcoin-ab86ac7739b2/lib/libbitcoinconsensus-0.dll.dbg (deflated 78%)

real	11m35.180s
user	53m25.755s
sys	3m55.505s
bash-5.1# find guix-build-$(git rev-parse --short=12 HEAD)/output/ -type f -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  guix-build-ab86ac7739b2/output/dist-archive/SKIPATTEST.TAG
d3f05888c95d6cf6f4a0bac952d4c0bf1e271f49cb7ab92b08080b753957e5e5  guix-build-ab86ac7739b2/output/dist-archive/bitcoin-ab86ac7739b2.tar.gz
113bb86ffd2854e08d3c0c5cd3f9728f2e4fe6c7a1813bc1c4b73eb48ad6597f  guix-build-ab86ac7739b2/output/x86_64-w64-mingw32/bitcoin-ab86ac7739b2-win-unsigned.tar.gz
3fdc99754d6f26d9655a308c8847076d8fd4db8d61f4f18d8ef545894a42c10d  guix-build-ab86ac7739b2/output/x86_64-w64-mingw32/bitcoin-ab86ac7739b2-win64-debug.zip
932bb69e3eb1a617f9e337b83220c9d6a277bec421f4d78e32dffde5643eb00c  guix-build-ab86ac7739b2/output/x86_64-w64-mingw32/bitcoin-ab86ac7739b2-win64-setup-unsigned.exe
852f4c03ad049fcd6bb2ce25b3bcf4e18b90d34f7232660024b341bd7c8dd710  guix-build-ab86ac7739b2/output/x86_64-w64-mingw32/bitcoin-ab86ac7739b2-win64.zip
c6a33a193a6b128e665198dde94758acab3a5ab7fefe0c3c6617eb98ad01693d  guix-build-ab86ac7739b2/output/x86_64-w64-mingw32/inputs.SHA256SUMS
```

**Pull request merged**
