### PR TITLE
ci: Add clang-tidy task

### LINKED ISSUE #24747: ci: add lint job to run clang-tidy check for named args
After #24661, we should be able to enable [`clang-tidy`](https://clang.llvm.org/extra/clang-tidy/) named argument checking in the CI lint job. The simplest way to invoke this checking, is something like `./autogen.sh && ./configure CC=clang-12 CXX=clang++-12 && make clean && bear make -j9 && ( cd ./src/ && run-clang-tidy-12 -j9 )`, which invokes clang-tidy using our [`.clang-tidy` config](https://github.com/bitcoin/bitcoin/blob/master/src/.clang-tidy).

Dependencies, like `clang-tidy` would need to be installed in the [linting container](https://github.com/bitcoin/bitcoin/blob/master/ci/lint/04_install.sh), and a linting job could be added to https://github.com/bitcoin/bitcoin/tree/master/test/lint.

It is possible to work on this now, by just basing your changes on the #24661 branch.

#### Useful skills:

* Bash
* CI

#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

### PR DESCRIPTION
**Pull request by maflcko**
Fixes #24747

### CODE REVIEW

**Comment by fanquake** [comment]
Concept ACK

**Review by vincenzopalazzo — COMMENTED** [review]
Concept ACK

**Comment by laanwj** [comment]
Concept ACK (given that this doesn't cause false positives or spurious failures)

**Comment by MarcoFalke** [comment]
If this task fails because clang-tidy doesn't work, we'll need to revert 67f654ef612c8dbefb969e6e67c286ea2c2e82d6 as well.

If there are silent merge conflicts, I think we can handle them as they arise. Worst case is we ignore the red status of the task for a few days.

**Comment by MarcoFalke** [comment]
(And before merging this pull, make sure to re-run the tidy task to be sure about silent mere conflicts)

**Review by fanquake — APPROVED** [review]
ACK fab24f8c3540b6f1a128cb9d6812df6678472b8d

> (And before merging this pull, make sure to re-run the tidy task to be sure about silent mere conflicts)

Rebooted in https://cirrus-ci.com/task/5864889825624064.

**Review by vincenzopalazzo — APPROVED** [review]
Code Review ACK https://github.com/bitcoin/bitcoin/pull/24753/commits/fab24f8c3540b6f1a128cb9d6812df6678472b8d

**Comment by jonatack** [comment]
Concept ACK

**Comment by fanquake** [comment]
> Rebooted in https://cirrus-ci.com/task/5864889825624064.

🟢

**Pull request merged**
