### PR TITLE
build: Drop 32-bit build configurations for MSVC

### PR DESCRIPTION
**Pull request by hebasto**
A 32-bit application for Windows in 2021 looks outdated. I'm pretty sure no one is going to run Bitcoin Core v23.0 on 32-bit Windows.

Also see #15939.

### CODE REVIEW

**Comment by hebasto** [comment]
cc @sipsorcery

**Comment by practicalswift** [comment]
Concept ACK

Somewhat related:
* #16096

**Comment by hebasto** [comment]
Updated 8c49dc2b7402d6b6b8cd00c4784abf6e86071c30 -> 57b3c5bda648016747553f49b6107fd6c7d90235 ([pr22908.01](https://github.com/hebasto/bitcoin/commits/pr22908.01) -> [pr22908.02](https://github.com/hebasto/bitcoin/commits/pr22908.02)) on top of the recent changes in CI.

**Comment by laanwj** [comment]
Concept ACK. There is no point in supporting this configuration, I'm sure it's wildly under-tested. 32-bit x86 is a museum architecture by now, and accidentally using a 32-bit build on 64-bit hardware will result in lousy performance.

**Comment by fanquake** [comment]
Concept ACK - haven't / wont test though.

**Review by sipsorcery — APPROVED** [review]
Looks good to me. Nice pickup of the duplicate project GUID.

Update: Will test it out this evening.

**Comment by sipsorcery** [comment]
tACK 57b3c5bda648016747553f49b6107fd6c7d90235.

**Pull request merged**
