### PR TITLE
[doc] clarify blockchain size and pruning

### PR DESCRIPTION
**Pull request by askmike**

### CODE REVIEW

**Comment by paveljanik** [comment]
what about "more than 100 GBs" so it actually brings some information? Please also fix the commit message typo.

**Comment by askmike** [comment]
done both!

**Comment by paveljanik** [comment]
Please squash (https://github.com/bitcoin/bitcoin/blob/afae75fd3dad48b7a5db72732141d421c6864b9b/CONTRIBUTING.md#squashing-commits).

**Comment by askmike** [comment]
Should be squashed now.

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/9995/commits/6be66aed3df2271132d2540f24db6e49e3cf947d

This is very easy to review now, few ACKs please.

**Comment by TheBlueMatt** [comment]
While you're updating this you might as well mention pruning. "Downloads and, by default, stores the entire history".

**Comment by askmike** [comment]
done (removed the "However" to limit the amount of commas) and squashed

**Comment by instagibbs** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/9995/commits/b26ea0a8db88026066d499cc6c8f10d8b873f17b

**Comment by TheBlueMatt** [comment]
ACK

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/9995/commits/b26ea0a8db88026066d499cc6c8f10d8b873f17b

**Comment by laanwj** [comment]
I'm okay with this change, although hopefully this won't result in a PR every month updating the current number. "more than 100 GBs" as written is somewhat future-proof at least.

**Pull request merged**
