### PR TITLE
scripted-diff: Prefer x.empty() over x.size() == 0 and x.length() == 0

### PR DESCRIPTION
**Pull request by practicalswift**
Changes:
* Prefer `x.empty()` over `x.size() == 0` and `x.length() == 0`
* Prefer `!x.empty()` over `bool(x.size())`
* Prefer `!x.empty()` over `x.size() > 0`

Rationale:
* Improve readability.
* Avoid nongeneric code - see ["T.143: Don't write unintentionally nongeneric code"](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#t143-dont-write-unintentionally-nongeneric-code) in the C++ Core Guidelines (Stroustrup & Sutter): *"Emptiness works for more containers than size(), because some containers don't know their size or are conceptually of unbounded size."*

### CODE REVIEW

**Comment by promag** [comment]
Should these
```cpp
if (container.size()) { ... }
if (container.size() > 0) { ... }
```
be
```cpp
if (!container.empty()) { ... }
```
?

**Comment by practicalswift** [comment]
@promag Updated! :-)

**Comment by promag** [comment]
Rename PR to something along "Prefer empty over size or length"?

**Comment by promag** [comment]
@practicalswift Why was this closed?

**Comment by practicalswift** [comment]
@promag Two reasons - I had my doubts if this PR is worth doing (might be a bit too picky and quite heavy to review due to the number of change) and also that the PR failed to gain any concept ACKs from core developers :-)   But thanks for reviewing anyways!

**Comment by promag** [comment]
NP.

**Pull request closed without merging**
