### PR TITLE
[init] better message when no wallet support is compiled in

### PR DESCRIPTION
**Pull request by Diapolo**

### CODE REVIEW

**Comment by sipa** [comment]
ACK

**Comment by laanwj** [comment]
ACK, but seems more like something for @theuni's trivial branch

**Comment by Diapolo** [comment]
I can also open that pull in the trivial-next branch but had the impression it would't make it anymore ;).

**Comment by theuni** [comment]
Merged into trivial via https://github.com/theuni/bitcoin/pull/16

**Pull request closed without merging**
