### PR TITLE
qt: Plug many memory leaks

### PR DESCRIPTION
**Pull request by laanwj**
This plugs all the memory leaks that I could get a full traceback for in bitcoin-qt.

In most cases this means properly using the QObject parent hierarchy, in other cases (no qt object, or where parenting would have ancillary effects) I've used std::unique_ptr. I've introduced no new manual 'deletes' or 'frees'.

Before:
```
SUMMARY: AddressSanitizer: 2660170 byte(s) leaked in 39504 allocation(s).
```

After:
```
SUMMARY: AddressSanitizer: 25089 byte(s) leaked in 696 allocation(s).
```

The leaks that asan finds after this are likely Qt global objects, and some fontconfig related things. I was not able to track them down.

### CODE REVIEW

**Comment by gmaxwell** [comment]
huh. I run valgrind all the time on bitcoind... but I haven't on qt. Good finds! Reviewing...

**Comment by laanwj** [comment]
> huh. I run valgrind all the time on bitcoind... but I haven't on qt. Good finds! Reviewing...

Yes, bitcoind was clean in asan too. Nice accomplishment. The GUI apparently has quite some leaks, some of which we probably can't help. None extremely serious - these are mostly objects allocated only once, although the thread leak is a bit scary for other reasons: there really shouldn't be a RPC executor thread before `AppIinit()` nor after `Shutdown()`. So it's a safety fix too.

@fanquake to answer your IRC question this was with Qt 5.5.1, the system library on Ubuntu 1604.

**Comment by jonasschnelli** [comment]
Tested ACK 4b2c2888868cb49806cd734ea36e7f5b032c3b00.
Looks much better now on OSX but still got some leaks reported (maybe OSX specific, maybe root source lies in Qt).

* `void PaymentServer::LoadRootCAs(X509_STORE* _store);`
* `CDBEnvOpen` via `CWallet::Verify()` and `CWallet::LoadWallet()`

bildschirmfoto 2016-11-21 um 14 52 07

**Comment by laanwj** [comment]
Huh, the leaks in `PaymentServer::LoadRootCAs` should have been solved with commit 4b2c2888868cb49806cd734ea36e7f5b032c3b00 . In any case I'm not claiming to plug all leaks, just most of them.

**Comment by fanquake** [comment]
@jonasschnelli Which version of Qt are you testing with?

I'm currently testing with Qt5.7, on OS X 10.12.1, seeing similar results. Screenshots below.
bitcoin-leaks
Payment Server:
payment server
SplashScreen:
splashscreen

**Comment by sipa** [comment]
Concept ACK

**Comment by paveljanik** [comment]
utACK https://github.com/bitcoin/bitcoin/commit/4b2c2888868cb49806cd734ea36e7f5b032c3b00

There are two more `new QMenu();`:
```
src/qt/coincontroldialog.cpp:    contextMenu = new QMenu();
src/qt/receiverequestdialog.cpp:    contextMenu = new QMenu();
```

**Comment by laanwj** [comment]
@paveljanik Thanks! Verified that those don't get deleted (they likely didn't show up in my overview because I didn't check opening sub-windows apart from the debug window), so changed them too and re-pushed.

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/9190/commits/ed998ea7a0ecf294211b06e9ef82f1548a621a1d

**Pull request merged**
