### PR TITLE
Update petertodd's testnet seed

### PR DESCRIPTION
**Pull request by petertodd**
New seed with servicebit filtering support.

### CODE REVIEW

**Comment by petertodd** [comment]
FYI I have no plans to take down the old testnet seed anytime soon, and the two are running on separate servers to avoid having the new servicebits stuff cause any issues. This seed's service bit whitelist is also setup to return the RBF bit, and there will be an analogous mainnet version of it on seed.btc.petertodd.org shortly.

**Comment by jonasschnelli** [comment]
`dig A x9.seed.tbtc.petertodd.org` results in a list with 23 IPs (I think we have only a handful [even less] of SW nodes).
Took out an random IP (139.59.169.37) and checked the service bits (00000005).

I guess seed.tbtc.petertodd.org runs still the bitcoin-seeder without filter support?

**Comment by petertodd** [comment]
@jonasschnelli Huh, weird, it's *definitely* running the seeder with filter support, no doubt about that. Maybe the seeder has a bug? Or those aren't actually real nodes? The seed was just started for the first time earlier today if that means anything.

**Comment by laanwj** [comment]
Anything left to be done here?

**Comment by petertodd** [comment]
@laanwj Go ahead and merge; the possible issue @jonasschnelli would be only on my end, and any fix for it would require no changes to Bitcoin Core's codebase.

**Pull request merged**
