### PR TITLE
script: Drop KVM support in gitian-build.py

### PR DESCRIPTION
**Pull request by hebasto**
The [`python-vm-builder`](https://packages.ubuntu.com/bionic/python-vm-builder) package, which is required for KVM-based builds, is not available in distros after bionic.

### CODE REVIEW

**Comment by laanwj** [comment]
Concept ACK as discussed in #bitcoin-builds
```
2021-02-10 10:14:27     hebasto `python-vm-builder` package is not available in distros after bionic; should we maintain the `--kvm` option for `gitian-build.py` script?
2021-02-10 10:15:39     hebasto wumpus: luke-jr: ^
2021-02-10 10:16:55     wumpus  i personally always use LXC
2021-02-10 10:17:08     hebasto me too :)
2021-02-10 10:17:10     wumpus  so ok with removing it, unless someone got it to work some other way
2021-02-10 10:17:44     wumpus  i dono't really know why one'd prefer to use KVM, there's no reason to use a low level VM here
2021-02-10 10:19:14     hebasto anyway, it is still possible to make kvm-based gitian builds w/o python helper script, right?
2021-02-10 10:21:43     wumpus  yes
2021-02-10 10:37:49     wumpus  i think removing it is fine
2021-02-10 10:38:11     wumpus  it can still be used for old releases, with the build script on that branch
2021-02-10 10:38:25     wumpus  but not on 22.x which builds with focal
```

**Comment by luke-jr** [comment]
Concept NACK. Ubuntu isn't the only distro out there.

Besides, vmbuilder doesn't even work to *create* bionic either, so it's been irrelevant for a while. It's not very hard to install in KVM manually.

**Comment by laanwj** [comment]
@luke-jr So do you use this script at all, or call gitian-build directly? In the latter case this doesn't affect you.

**Comment by luke-jr** [comment]
At present I have a custom script that is similar, but this isn't about me personally...

>Sure, but Ubuntu is the only distro used for building bitcoin core gitian binaries.

*Within* gitian, yes, but not the only one *outside* gitian.

**Comment by laanwj** [comment]
> Within gitian, yes, but not the only one outside gitian.

This script is only relevant to gitian.

**Comment by hebasto** [comment]
Rebased b4bc7208294d34c1407a4e30a6a0ac45b96dea43 -> ef14d90172e2278b362171763805ac41a6d7779e ([pr21140.01](https://github.com/hebasto/bitcoin/commits/pr21140.01) -> [pr21140.02](https://github.com/hebasto/bitcoin/commits/pr21140.02)) due to the conflict with #21130.

**Comment by luke-jr** [comment]
>This script is only relevant to gitian. It's not called gitian-build.py for nothing.

Yes, and gitian runs fine on non-Ubuntu platforms... The only Ubuntu-specific thing about (our) gitian usage is the OS run *within* the VM gitian manages.

**Comment by laanwj** [comment]
ACK ef14d90172e2278b362171763805ac41a6d7779e

**Comment by laanwj** [comment]
I think it's better to close this. There are clear differences in opinion here and it's unclear how much debating a small cleanup like this even matters with the move to GUIX in progress.

**Comment by fanquake** [comment]
> I think it's better to close this. 

Agree. There's not really any harm to leave this as-is for now.

**Comment by hebasto** [comment]
> I think it's better to close this. There are clear differences in opinion here and it's unclear how much debating a small cleanup like this even matters with the move to GUIX in progress (and this script disappearing completely).

Right.

**Pull request closed without merging**
