### PR TITLE
Bugfix: Correctly calculate priority when inputs are mined after dependent transactions enter the memory pool

### PR DESCRIPTION
**Pull request by luke-jr**
This is needed to restore proper CreateNewBlock functioning for unconfirmed transaction chains.

### CODE REVIEW

**Comment by luke-jr** [comment]
Added RPC tests and fixed an additional bug found with them. This should now be ready for merging to master and 0.12.

**Comment by arowser** [comment]
Can one of the admins verify this patch?

**Comment by sipa** [comment]
Weak concept NACK. I don't think we should be spending effort on maintaining the old priority system (which was completely arbirary anyway).

**Comment by fanquake** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
