### PR TITLE
[rpc] Remove auth cookie on shutdown

### PR DESCRIPTION
**Pull request by practicalswift**
Accidentally removed in 40b556d3742a1f65d67e2d4c760d0b13fe8be5b7

### CODE REVIEW

**Comment by laanwj** [comment]
Thanks,  utACK

**Comment by fanquake** [comment]
utACK 4b87973

**Comment by jonasschnelli** [comment]
Oh.. good catch.
utACK 4b87973c32bcaa5fa7509793e4f0c4f4f981f21b

**Review by gmaxwell — APPROVED** [review]
utACK

**Pull request merged**
