### PR TITLE
qt: 25.0rc2 translations update

### PR DESCRIPTION
**Pull request by hebasto**
This PR follows our [Release Process](https://github.com/bitcoin/bitcoin/blob/master/doc/release-process.md#before-every-release-candidate) and pulls the recent translations from the [Transifex.com](https://www.transifex.com/bitcoin/bitcoin) using the [`bitcoin-maintainer-tools/update-translations.py`](https://github.com/bitcoin-core/bitcoin-maintainer-tools/blob/main/update-translations.py) tool.

Unfortunately, it wasn't done before `v25.0rc1` tagging. Therefore, it is expected to be merged just before the `v25.0rc2` tag (I commit to keep this PR updated on a daily basis).

All developers with non-English native languages are welcome to skim through their language translation files and look for any malicious content, such as "official technical support for a stuck transaction", etc.

### CODE REVIEW

**Comment by hebasto** [comment]
Updated.

**Comment by jarolrod** [comment]
Concept ACK, could use an update?

**Comment by hebasto** [comment]
> could use an update?

Updated.

**Comment by fanquake** [comment]
> is this now pushed to rc3?

An rc2 hasn't been tagged yet; not sure why it would be pushed to rc3.

**Comment by hebasto** [comment]
Updated.

**Review by jarolrod — APPROVED** [review]
ACK 20c076d0567da56637e69a26a8cc4e7d99124ebd

Made sure we're adhering to the translation process and ran the script. I sanity tested loading different translations within the gui to make sure nothing is wildly off.

**Pull request merged**
