### PR TITLE
build: Add CLIENT_VERSION_BUILD to CFBundleGetInfoString

### PR DESCRIPTION
**Pull request by fanquake**
As mentioned in #14697, if you download the `0.17.0.1` dmg, and inspect the `.app` bundle, the version in the GetInfo string reads `0.17.0`, which is confusing given you're expecting `0.17.0.1`:

This PR adds `CLIENT_VERSION_BUILD` to the string, so that the full version number is displayed, i.e:
this pr

### CODE REVIEW

**Comment by laanwj** [comment]
Concept ACK.
Might want to wait until #14612 is merged so that RC level can be included as well.

**Comment by laanwj** [comment]
> Might want to wait until #14612 is merged so that RC level (of appropriate) can be included as well.

#14612 was merged

**Comment by jonasschnelli** [comment]
Tested via gitian build: https://bitcoin.jonasschnelli.ch/build/908

Result:
bildschirmfoto 2018-12-09 um 14 57 55

**Comment by core-code** [comment]
this has been going completely into the wrong direction. the 'CFBundleGetInfoString' has been deprecated fore more than 10 years (!) and needs to be removed completely and not updated.

(if you need some copyright information it should be added to the 'NSHumanReadableCopyright' field)

meanwhile the 'real' version numbers embedded into the app are still broken. if you download version '0.19.0.1' the version strings are still cropped:

CFBundleShortVersionString:
0.19.0
CFBundleVersion:
0.19.0

both are wrong.

**Comment by laanwj** [comment]
So looks like the versions are still cropped. Can anyone verify?

**Comment by Sjors** [comment]
Not sure where to look, these all look fine on Catalina:

Schermafbeelding 2019-11-29 om 09 49 22


Schermafbeelding 2019-11-29 om 09 49 39

Schermafbeelding 2019-11-29 om 09 49 56

**Comment by core-code** [comment]
the screenshots from inside the aren't useful. they can show anything they want and do not necessarily have a connection to the *real* version numbers of the app, i.e. the one the operating system knows about and e.g. uses to determine which is the newest version if multiple versions are installed.

the real version numbers are the CFBundleShortVersionString and especially the CFBundleVersion entries in the Info.plist file.

the screenshot from the Finder proves what i've been saying above. you are including the 'CFBundleGetInfoString' in your plist. this has been deprecated for more than 10 years. so, in the Finder you are just seeing this deprecated string instead of the real version numbers. those are still cropped:
Screenshot 2019-11-29 at 12 06 55

**Comment by laanwj** [comment]
yep https://github.com/bitcoin/bitcoin/blob/master/share/qt/Info.plist.in#L22-L26

**Comment by core-code** [comment]
so, if you change
CFBundleShortVersionString and CFBundleVersion to 
`
<string>@CLIENT_VERSION_MAJOR@.@CLIENT_VERSION_MINOR@.@CLIENT_VERSION_REVISION@.@CLIENT_VERSION_BUILD@</string>
`
and remove *CFBundleGetInfoString* and add *NSHumanReadableCopyright* then things should be good ;)

**Comment by MarcoFalke** [comment]
@core-code Please open a new issue or pull request for this

**Pull request merged**
