### PR TITLE
build: pkg-config related cleanup

### PR DESCRIPTION
**Pull request by hebasto**
This PR:
- does not change behavior
- drops redundant `AC_SUBST` macros

Also checks of PKG_CHECK_MODULES presence are removed because they are redundant due to the following code https://github.com/bitcoin/bitcoin/blob/ab1feadf4e6cd4f5f2c7e74cea1c7baad61458ba/configure.ac#L16-L20

### CODE REVIEW

**Comment by practicalswift** [comment]
Concept ACK: nice cleanup!

**Comment by laanwj** [comment]
> drops redundant AC_SUBST macros

What makes these redundant?

**Comment by hebasto** [comment]
> > drops redundant AC_SUBST macros
> 
> What makes these redundant?

From commit message:
> Variables that are declared with AC_ARG_VAR macro are substituted via
> AC_SUBST macro.
> PKG_CHECK_MODULES macro already has AC_ARG_VAR(${PACKAGE}_CFLAGS) and
> AC_ARG_VAR(${PACKAGE}_LIBS).

**Comment by laanwj** [comment]
Thanks. Yes, clear. But otoh that seems pretty deeply buried. I think one advantage of specifying them explicitly is to have a better idea what gets exported from the `configure.ac` script, what its interface is to the makefiles and config.h file.

**Comment by hebasto** [comment]
@laanwj 
> I think one advantage of specifying them explicitly is to have a better idea what gets exported from the `configure.ac` script, what its interface is to the makefiles and config.h file.

`PKG_CHECK_MODULES` has a pretty self-documenting feature, as its internal `AC_ARG_VAR` include variable description in the variable section of `./configure --help`.

**Comment by hebasto** [comment]
Rebased ae92fb1e103c17302fdbf03b1bbd04c6919c7920 -> 58737de5807445aeb3bc89e8215f85a1df0f398f ([pr20201.01](https://github.com/hebasto/bitcoin/commits/pr20201.01) -> [pr20201.02](https://github.com/hebasto/bitcoin/commits/pr20201.02)) due to the conflict with #20202.

**Comment by hebasto** [comment]
Rebased 58737de5807445aeb3bc89e8215f85a1df0f398f -> ab1feadf4e6cd4f5f2c7e74cea1c7baad61458ba ([pr20201.02](https://github.com/hebasto/bitcoin/commits/pr20201.02) -> [pr20201.03](https://github.com/hebasto/bitcoin/commits/pr20201.03)) due to the conflict with #18077.

**Comment by bitmastercoin** [comment]
Running Kali Linux. 2020.4 and getting the error after attempting `sudo ./autogen.sh` 
with the out put being a long string and eventually. ::
`configure.ac:16: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:255: error: possibly undefined macro: AC_DEFINE
configure.ac:632: error: possibly undefined macro: AC_MSG_WARN
autoreconf: /usr/bin/autoconf failed with exit status: 1
`

**Comment by hebasto** [comment]
@bitmastercoin What happens when you do the same on the master branch?

**Comment by jarolrod** [comment]
@bitmastercoin I was able to successfully build and and run with Kali Linux 2020.4 and 2021.1 on master branch and PR branch. Can you give any update?

**Review by jarolrod — COMMENTED** [review]
Concept ACK, I cannot ACK yet because I want to confirm the reproducibility of the stripped information with the [bitcoin-maintainer-tools/build-for-compare.py](https://github.com/bitcoin-core/bitcoin-maintainer-tools/blob/master/build-for-compare.py) script, but I'm currently running into the following issue:
```
>>> [do_build] Command failed: git apply /home/xyz/Bitcoin/Code/revie/test-reproducibility/bitcoin-maintainer-tools/patches/stripbuildinfo.patch
>>> [do_build] Could not apply patch to strip build info. Probably it needs to be updated
```
I tried running on the PR branch itself, and the PR branch rebased on the current master, but no luck. Obviously, I am not a maintainer, so any help would be appreciated 😊

**Notes:**
I wanted to try to document what is going on here and give my opinion.

- [x] 388135bcf91bcc665417b59980468db270e48d9a
  - Commit 388135bcf91bcc665417b59980468db270e48d9a  states that it is removing a redundant check of `PKG_CHECK_MODULES`. If we look at the  [pkg.m4](https://github.com/pkgconf/pkgconf/blob/master/pkg.m4) source code, and specifically [lines 131-142](https://github.com/pkgconf/pkgconf/blob/cef30268e1a3f79efd607c26abcf556aa314c9c4/pkg.m4#L131-L142), we can see that performing this check within our configure.ac script is in fact redundant. 

- [x] ab1feadf4e6cd4f5f2c7e74cea1c7baad61458ba
  - From my understanding, the [AC_SUBT](https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Setting-Output-Variables.html) macro is meant to provide output variables to automake. The description for this commit explains why performing this work ourselves is redundant; these variables will already be provided to automake thanks to `pkg.m4`. This can be confirmed by looking at [Lines 141 and 142](https://github.com/pkgconf/pkgconf/blob/master/pkg.m4#L141-L142) of the `pkg.m4` source code. As such, it is ok to remove what is being removed in this commit.

**Should we do this?**
I think it is great not to redo unnecessary work when it is *unnecessary*. As such, this PR is a nice simplification.

@laanwj brings up a good point that this is kind of buried, and you need to dig through the source code to confirm this. Luckily the `pkg.m4` source code is not too large, and it's easy to refer to. In this case, I'd say it's not a big deal. But, I will defer to our build experts.

**Comment by fanquake** [comment]
> If we look at the pkg.m4 source code,
> Lines 141 and 142 of the pkg.m4 source code.

Not sure if you're aware, but https://github.com/pkgconf/pkgconf (which you've been linking to here), is not the same piece of software as https://www.freedesktop.org/wiki/Software/pkg-config/, which is what most builders would actually be using.

**Comment by jarolrod** [comment]
@fanquake ah thanks for the clarification. Just trying to learn about our build system by reviewing. I've checked the source code for the pkg-config you've linked and have found the same relevant lines in its `pkg.m4`

**Comment by hebasto** [comment]
@jarolrod 
> ... I want to confirm the reproducibility of the stripped information with the [bitcoin-maintainer-tools/build-for-compare.py](https://github.com/bitcoin-core/bitcoin-maintainer-tools/blob/master/build-for-compare.py) script, but I'm currently running into the following issue:

Try https://github.com/bitcoin-core/bitcoin-maintainer-tools/pull/108.

**Comment by hebasto** [comment]
Comparing the current master (c3545a7396787c1d649f2d12fcb380b714cab6b2) with `pull/20201/merge` using [bitcoin-maintainer-tools/build-for-compare.py](https://github.com/bitcoin-core/bitcoin-maintainer-tools/blob/master/build-for-compare.py) (with https://github.com/bitcoin-core/bitcoin-maintainer-tools/pull/108) returns zero diff.

**Comment by hebasto** [comment]
@jarolrod 
> * Commit [388135b](https://github.com/bitcoin/bitcoin/commit/388135bcf91bcc665417b59980468db270e48d9a)  states that it is removing a redundant check of `PKG_CHECK_MODULES`. If we look at the  [pkg.m4](https://github.com/pkgconf/pkgconf/blob/master/pkg.m4) source code, and specifically [lines 131-142](https://github.com/pkgconf/pkgconf/blob/cef30268e1a3f79efd607c26abcf556aa314c9c4/pkg.m4#L131-L142), we can see that performing this check within our configure.ac script is in fact redundant.

See the update PR description.

**Comment by hebasto** [comment]
> > If we look at the pkg.m4 source code,
> > Lines 141 and 142 of the pkg.m4 source code.
> 
> Not sure if you're aware, but https://github.com/pkgconf/pkgconf (which you've been linking to here), is not the same piece of software as https://www.freedesktop.org/wiki/Software/pkg-config/, which is what most builders would actually be using.

The correct reference is [here](https://gitlab.freedesktop.org/pkg-config/pkg-config/-/blob/master/pkg.m4.in#L141-142):
```
AC_ARG_VAR([$1][_CFLAGS], [C compiler flags for $1, overriding pkg-config])dnl
AC_ARG_VAR([$1][_LIBS], [linker flags for $1, overriding pkg-config])dnl
```

**Comment by hebasto** [comment]
Rebased ab1feadf4e6cd4f5f2c7e74cea1c7baad61458ba -> 17c2cad948855f8f08e798b3e11b2be5e5fffdf1 ([pr20201.03](https://github.com/hebasto/bitcoin/commits/pr20201.03) -> [pr20201.04](https://github.com/hebasto/bitcoin/commits/pr20201.04)) on top of the recent change in the build system (including Guix) and CI.

**Comment by hebasto** [comment]
#### Guix hashes:
```
$ find guix-build-$(git rev-parse --short=12 HEAD)/output/ -type f -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum
3eac41c46efef01623ad8b7511eb5368f57415a45dd1d6a435c257bd41839446  guix-build-17c2cad94885/output/aarch64-linux-gnu/SHA256SUMS.part
f00e74b71820778b361c2eeea7012bc61280d48e72e892bab554304df408fd5e  guix-build-17c2cad94885/output/aarch64-linux-gnu/bitcoin-17c2cad94885-aarch64-linux-gnu-debug.tar.gz
6f9c90a2fdc0b850dfecefdd26d1f8a2c574e53d20ff35e64b02c861f50543fb  guix-build-17c2cad94885/output/aarch64-linux-gnu/bitcoin-17c2cad94885-aarch64-linux-gnu.tar.gz
0d905e68421d77e0cea2d6586271a515a8e4f88fc69de8c0ff0b9dad65a25b6c  guix-build-17c2cad94885/output/arm-linux-gnueabihf/SHA256SUMS.part
cd0f03d2c14a5775dbb945d64aaaa0e9ecc1679f75ba74dcf30213daedcae2ac  guix-build-17c2cad94885/output/arm-linux-gnueabihf/bitcoin-17c2cad94885-arm-linux-gnueabihf-debug.tar.gz
6def410f1881d53ae674ba64bc6d5e8a059b5e4b5816034b6268a248b8eb2a85  guix-build-17c2cad94885/output/arm-linux-gnueabihf/bitcoin-17c2cad94885-arm-linux-gnueabihf.tar.gz
485f20c1e7b4be427c75d580cbeb42a9d8ae5c40c1c16f75190f2be5fc0f1669  guix-build-17c2cad94885/output/dist-archive/bitcoin-17c2cad94885.tar.gz
a9bd07a042d1e74f65fc6c42dbc84672adcb6b520601754395e216b374933116  guix-build-17c2cad94885/output/powerpc64-linux-gnu/SHA256SUMS.part
582f31bd11a872c0b7d9be26b623a5a595a1373e6848f690322b3d3a944f167e  guix-build-17c2cad94885/output/powerpc64-linux-gnu/bitcoin-17c2cad94885-powerpc64-linux-gnu-debug.tar.gz
3bce6480c68e1e5214f5b9c2f306a489b5da469dd8474188b22322af0a53061b  guix-build-17c2cad94885/output/powerpc64-linux-gnu/bitcoin-17c2cad94885-powerpc64-linux-gnu.tar.gz
d55af904cb36592db6305d643e7508252610ce334b455ee3a63454767d7166b9  guix-build-17c2cad94885/output/powerpc64le-linux-gnu/SHA256SUMS.part
f660af2150242f7658d5c642aadd15e2c71a8f5d989cf066558be1866b274123  guix-build-17c2cad94885/output/powerpc64le-linux-gnu/bitcoin-17c2cad94885-powerpc64le-linux-gnu-debug.tar.gz
f9f1a7cdd8f75297340c6da6d38a239c5acc56216fa057a69fe46526b23ac33d  guix-build-17c2cad94885/output/powerpc64le-linux-gnu/bitcoin-17c2cad94885-powerpc64le-linux-gnu.tar.gz
1788779b44122b2e26f2536f2d1b61ae7c22490eda22cbdbc3260a4dd79a655c  guix-build-17c2cad94885/output/riscv64-linux-gnu/SHA256SUMS.part
4ea6204af91392715f6cb398512e64a481b985b107c999af505851b277df4c7e  guix-build-17c2cad94885/output/riscv64-linux-gnu/bitcoin-17c2cad94885-riscv64-linux-gnu-debug.tar.gz
77f22f43b38d97466d7179028714a09f677cec301250ed534cd11998c9a29b1e  guix-build-17c2cad94885/output/riscv64-linux-gnu/bitcoin-17c2cad94885-riscv64-linux-gnu.tar.gz
1ebd0b23b401b309cbfd72d40e32da74ecffe8c77f83c08af74b46d644f59254  guix-build-17c2cad94885/output/x86_64-apple-darwin18/SHA256SUMS.part
918df7b7a9584cbebdca691c2cb6e717e18e41c4a7c6beb85c3680d86a016945  guix-build-17c2cad94885/output/x86_64-apple-darwin18/bitcoin-17c2cad94885-osx-unsigned.dmg
5bbdb688ec9bd3366879c8cfaba24a2348a6535d25b16f11441c4b32af4e169d  guix-build-17c2cad94885/output/x86_64-apple-darwin18/bitcoin-17c2cad94885-osx-unsigned.tar.gz
a8205ff6c618d3bb6c0ac88570b50ba3c845f2bfa1131740bbc435afb3a1d089  guix-build-17c2cad94885/output/x86_64-apple-darwin18/bitcoin-17c2cad94885-osx64.tar.gz
ec78d91ed8a7b927ee9be14743a7f612c1baf62cfcd576c3fc8dfc593e765dd5  guix-build-17c2cad94885/output/x86_64-linux-gnu/SHA256SUMS.part
58100846b217a1954d27ee39c8a33b544a831e983e1cf6e6e73cdc5304e68421  guix-build-17c2cad94885/output/x86_64-linux-gnu/bitcoin-17c2cad94885-x86_64-linux-gnu-debug.tar.gz
6983d9eecf01bbcec1ef59c0c5d63755f97e9d1900951c855ed0071a72efc1d7  guix-build-17c2cad94885/output/x86_64-linux-gnu/bitcoin-17c2cad94885-x86_64-linux-gnu.tar.gz
d442887bf09591a2225903b66477cdbbe56314ed93e2a45a8b44168502cd9b27  guix-build-17c2cad94885/output/x86_64-w64-mingw32/SHA256SUMS.part
035d6caf2ae753f2cb16ec1346239c05849eb2927162073652c73bfb82e4edcf  guix-build-17c2cad94885/output/x86_64-w64-mingw32/bitcoin-17c2cad94885-win-unsigned.tar.gz
02df13c02c0c8f11de912d9d4325540ee62085e1eb511c771b95d661950b281e  guix-build-17c2cad94885/output/x86_64-w64-mingw32/bitcoin-17c2cad94885-win64-debug.zip
469209f47641ab15d5ae691ce7f3793d5d8d0584e01bba574a45de475f01a7e5  guix-build-17c2cad94885/output/x86_64-w64-mingw32/bitcoin-17c2cad94885-win64-setup-unsigned.exe
327a246294ad0deb0c6fc24312ed11ca6396804d3d1856de679bb589946c3f93  guix-build-17c2cad94885/output/x86_64-w64-mingw32/bitcoin-17c2cad94885-win64.zip
```

**Comment by jarolrod** [comment]
GUIX hashes, mine match @hebasto 

```
find guix-build-$(git rev-parse --short=12 HEAD)/output/ -type f -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum

3eac41c46efef01623ad8b7511eb5368f57415a45dd1d6a435c257bd41839446  guix-build-17c2cad94885/output/aarch64-linux-gnu/SHA256SUMS.part
f00e74b71820778b361c2eeea7012bc61280d48e72e892bab554304df408fd5e  guix-build-17c2cad94885/output/aarch64-linux-gnu/bitcoin-17c2cad94885-aarch64-linux-gnu-debug.tar.gz
6f9c90a2fdc0b850dfecefdd26d1f8a2c574e53d20ff35e64b02c861f50543fb  guix-build-17c2cad94885/output/aarch64-linux-gnu/bitcoin-17c2cad94885-aarch64-linux-gnu.tar.gz
0d905e68421d77e0cea2d6586271a515a8e4f88fc69de8c0ff0b9dad65a25b6c  guix-build-17c2cad94885/output/arm-linux-gnueabihf/SHA256SUMS.part
cd0f03d2c14a5775dbb945d64aaaa0e9ecc1679f75ba74dcf30213daedcae2ac  guix-build-17c2cad94885/output/arm-linux-gnueabihf/bitcoin-17c2cad94885-arm-linux-gnueabihf-debug.tar.gz
6def410f1881d53ae674ba64bc6d5e8a059b5e4b5816034b6268a248b8eb2a85  guix-build-17c2cad94885/output/arm-linux-gnueabihf/bitcoin-17c2cad94885-arm-linux-gnueabihf.tar.gz
485f20c1e7b4be427c75d580cbeb42a9d8ae5c40c1c16f75190f2be5fc0f1669  guix-build-17c2cad94885/output/dist-archive/bitcoin-17c2cad94885.tar.gz
a9bd07a042d1e74f65fc6c42dbc84672adcb6b520601754395e216b374933116  guix-build-17c2cad94885/output/powerpc64-linux-gnu/SHA256SUMS.part
582f31bd11a872c0b7d9be26b623a5a595a1373e6848f690322b3d3a944f167e  guix-build-17c2cad94885/output/powerpc64-linux-gnu/bitcoin-17c2cad94885-powerpc64-linux-gnu-debug.tar.gz
3bce6480c68e1e5214f5b9c2f306a489b5da469dd8474188b22322af0a53061b  guix-build-17c2cad94885/output/powerpc64-linux-gnu/bitcoin-17c2cad94885-powerpc64-linux-gnu.tar.gz
d55af904cb36592db6305d643e7508252610ce334b455ee3a63454767d7166b9  guix-build-17c2cad94885/output/powerpc64le-linux-gnu/SHA256SUMS.part
f660af2150242f7658d5c642aadd15e2c71a8f5d989cf066558be1866b274123  guix-build-17c2cad94885/output/powerpc64le-linux-gnu/bitcoin-17c2cad94885-powerpc64le-linux-gnu-debug.tar.gz
f9f1a7cdd8f75297340c6da6d38a239c5acc56216fa057a69fe46526b23ac33d  guix-build-17c2cad94885/output/powerpc64le-linux-gnu/bitcoin-17c2cad94885-powerpc64le-linux-gnu.tar.gz
1788779b44122b2e26f2536f2d1b61ae7c22490eda22cbdbc3260a4dd79a655c  guix-build-17c2cad94885/output/riscv64-linux-gnu/SHA256SUMS.part
4ea6204af91392715f6cb398512e64a481b985b107c999af505851b277df4c7e  guix-build-17c2cad94885/output/riscv64-linux-gnu/bitcoin-17c2cad94885-riscv64-linux-gnu-debug.tar.gz
77f22f43b38d97466d7179028714a09f677cec301250ed534cd11998c9a29b1e  guix-build-17c2cad94885/output/riscv64-linux-gnu/bitcoin-17c2cad94885-riscv64-linux-gnu.tar.gz
1ebd0b23b401b309cbfd72d40e32da74ecffe8c77f83c08af74b46d644f59254  guix-build-17c2cad94885/output/x86_64-apple-darwin18/SHA256SUMS.part
918df7b7a9584cbebdca691c2cb6e717e18e41c4a7c6beb85c3680d86a016945  guix-build-17c2cad94885/output/x86_64-apple-darwin18/bitcoin-17c2cad94885-osx-unsigned.dmg
5bbdb688ec9bd3366879c8cfaba24a2348a6535d25b16f11441c4b32af4e169d  guix-build-17c2cad94885/output/x86_64-apple-darwin18/bitcoin-17c2cad94885-osx-unsigned.tar.gz
a8205ff6c618d3bb6c0ac88570b50ba3c845f2bfa1131740bbc435afb3a1d089  guix-build-17c2cad94885/output/x86_64-apple-darwin18/bitcoin-17c2cad94885-osx64.tar.gz
ec78d91ed8a7b927ee9be14743a7f612c1baf62cfcd576c3fc8dfc593e765dd5  guix-build-17c2cad94885/output/x86_64-linux-gnu/SHA256SUMS.part
58100846b217a1954d27ee39c8a33b544a831e983e1cf6e6e73cdc5304e68421  guix-build-17c2cad94885/output/x86_64-linux-gnu/bitcoin-17c2cad94885-x86_64-linux-gnu-debug.tar.gz
6983d9eecf01bbcec1ef59c0c5d63755f97e9d1900951c855ed0071a72efc1d7  guix-build-17c2cad94885/output/x86_64-linux-gnu/bitcoin-17c2cad94885-x86_64-linux-gnu.tar.gz
d442887bf09591a2225903b66477cdbbe56314ed93e2a45a8b44168502cd9b27  guix-build-17c2cad94885/output/x86_64-w64-mingw32/SHA256SUMS.part
035d6caf2ae753f2cb16ec1346239c05849eb2927162073652c73bfb82e4edcf  guix-build-17c2cad94885/output/x86_64-w64-mingw32/bitcoin-17c2cad94885-win-unsigned.tar.gz
02df13c02c0c8f11de912d9d4325540ee62085e1eb511c771b95d661950b281e  guix-build-17c2cad94885/output/x86_64-w64-mingw32/bitcoin-17c2cad94885-win64-debug.zip
469209f47641ab15d5ae691ce7f3793d5d8d0584e01bba574a45de475f01a7e5  guix-build-17c2cad94885/output/x86_64-w64-mingw32/bitcoin-17c2cad94885-win64-setup-unsigned.exe
327a246294ad0deb0c6fc24312ed11ca6396804d3d1856de679bb589946c3f93  guix-build-17c2cad94885/output/x86_64-w64-mingw32/bitcoin-17c2cad94885-win64.zip
```

**Review by jarolrod — COMMENTED** [review]
ACK 17c2cad948855f8f08e798b3e11b2be5e5fffdf1

As I've outlined [here](https://github.com/bitcoin/bitcoin/pull/20201#pullrequestreview-726967954) and [here](https://github.com/bitcoin/bitcoin/pull/20201#issuecomment-896435332), this change is ok to do.

>  cannot ACK yet because I want to confirm the reproducibility of the stripped information

I have used the [bitcoin-maintainer-tools/build-for-compare.py](https://github.com/bitcoin-core/bitcoin-maintainer-tools/blob/master/build-for-compare.py) script to check for the reproducibility of the stripped information. The two branch heads tested were 17c2cad and c3545a7 and the built executables were `bitcoind` and `bitcoin-qt`. Running `git diff -W --word-diff /tmp/compare/17c2cad /tmp/compare/c3545a7` returns a zero-diff.

shasums of the stripped info:
```
93c4fe1e65dffc43380d638f2fc72d8967bd6813b175d6363cfc46d27fcc5c24  /tmp/compare/bitcoind.17c2cad.stripped
93c4fe1e65dffc43380d638f2fc72d8967bd6813b175d6363cfc46d27fcc5c24  /tmp/compare/bitcoind.c3545a7.stripped
52e8e1375b7ea0e733c9e33eafd07c2f96731f96bebc65b72b2d156ac1faa37f  /tmp/compare/bitcoin-qt.17c2cad.stripped
52e8e1375b7ea0e733c9e33eafd07c2f96731f96bebc65b72b2d156ac1faa37f  /tmp/compare/bitcoin-qt.c3545a7.stripped
```

**Comment by hebasto** [comment]
Rebased 362edc2aebc2de41c55248521e446f0d1cb24498 -> c236f2e22868c7653441660fd50863f5fa36a512 ([pr20201.05](https://github.com/hebasto/bitcoin/commits/pr20201.05) -> [pr20201.06](https://github.com/hebasto/bitcoin/commits/pr20201.06)) due to the conflict with #23593.

**Review by fanquake — APPROVED** [review]
ACK c236f2e22868c7653441660fd50863f5fa36a512 - I see no difference in `config.log`s.

90498121063c9a9b5e15144bf8959044adac3885 is obviously correct.

For c236f2e22868c7653441660fd50863f5fa36a512: The only calls left to `AC_SUBST(*_LIBS)` are for `BOOST_LIBS`, `QT_LIBS`, `MINIUPNPC_LIBS` and `NATPMP_LIBS`, which are required as we either modify these vars ourselves, or the dependency doesn't use pkg-config.

**Pull request merged**
