### PR TITLE
[trivial] correct typos

### PR DESCRIPTION
**Pull request by Varunram**

### CODE REVIEW

**Comment by Empact** [comment]
You can drop the `src/leveldb/port/port_posix.h` change - that file is upstream in https://github.com/google/leveldb, and the typo doesn't exist there in current master.

**Comment by fanquake** [comment]
I've cherry-picked the relevant parts of this into #13781.

**Comment by Varunram** [comment]
Thanks fanquake, #13781 refers to this PR though, I hope it made it into master through some commit! Sorry I couldn't update this myself, was caught up in some things.

**Comment by fanquake** [comment]
@Varunram Sorry, I meant #13255. You should see your commit there.

**Pull request closed without merging**
