### PR TITLE
[RPC] push back getaddednodeinfo dead value

### PR DESCRIPTION
**Pull request by instagibbs**
I believe this is the desired behavior, if this is unneeded we should just delete the else branch.

### CODE REVIEW

**Comment by paveljanik** [comment]
Looks like this was the original goal, yes.

utACK https://github.com/bitcoin/bitcoin/pull/7926/commits/9c0bcb617b7358006842900ad8a9b333b30f5031

**Comment by sipa** [comment]
utACK 9c0bcb6

**Comment by laanwj** [comment]
Yes, I've never used this RPC but this makes sense I think 
utACK https://github.com/bitcoin/bitcoin/pull/7926/commits/9c0bcb617b7358006842900ad8a9b333b30f5031

**Comment by TheBlueMatt** [comment]
utACK 9c0bcb617b7358006842900ad8a9b333b30f5031

**Pull request merged**
