### PR TITLE
Wallet: Replace TxnAbort with assert.

### PR DESCRIPTION
**Pull request by pstratem**
CDB::Close should never be called with an activeTxn in progress.

### CODE REVIEW

**Comment by petertodd** [comment]
utACK

**Comment by laanwj** [comment]
I agree in principle, but assertions on shutdown are extremely annoying. People google the error that pops up.

They tend to mask the actual error that caused the (sudden) shutdown. E.g it will end up in this assertion if the node was aborted suddenly for some other reason, and it didn't manage to close the transaction.

We had a similar assert in `~LockedPageManager()` for a long time - checking that the set of locked pages was empty on shutdown - and most bug report mentioned it in favor of more useful information from debug.log.

As long as all the usages are in function scope this isn't a problem. CDB is not a global object, unlike the CDBEnv. But make sure that this doesn't become a problem.

**Comment by pstratem** [comment]
The only alternative I can think of would be to simply ignore the failure silently, however that could result in permanent data loss....

**Comment by laanwj** [comment]
The way in-between would be to log an error message and continue.

It is less in-your-face than an assertion, but then again, I'd expect when this happens there will already be something wrong and the user will be looking at / uploading debug.log.

**Pull request closed without merging**
