### PR TITLE
gui: Reject dialogs if key escape is pressed

### PR DESCRIPTION
**Pull request by promag**
Currently `EditAddressDialog` and `OptionsDialog` don't close when the escape key is pressed. The `QDataWidgetMapper` instances prevents closing the dialogs because the escape key is used to reset the widgets values. More details and workarounds in https://stackoverflow.com/a/51487847 and http://qtramblings.blogspot.com/2010/10/qdatawidgetmapper-annoyances.html.

The adopted solution is different from the above references. It turns out that `QDataWidgetMapper::setItemDelegate` sets the event filter for all mapped widgets. So in this PR the mapper's delegate are changed to a custom `GUIUtil::ItemDelegate` that offers the signal `keyEscapePressed`, which is connected to the `QDialog::reject` slot.

Note that the installed event filter lets all events pass, so the current behaviour isn't changed, meaning that widgets values are reset in addition to closing the dialog.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Trivial utACK ffa9fa4bce06cc680cf5a7833bcb255454439c80

**Comment by laanwj** [comment]
I'm disappointed at Qt that verbose code like this is needed to make simple ESC functionality work.
Is this the only place where this is needed?

utACK ffa9fa4bce06cc680cf5a7833bcb255454439c80.

**Comment by promag** [comment]
I could add some comments here for future reference.

> Is this the only place where this is needed?

@laanwj I'll check.

**Comment by laanwj** [comment]
> I could add some comments here for future reference.

THank you, good idea.

**Comment by promag** [comment]
@laanwj looks like the options dialog has the same problem. At least on macOS pressing ESC doesn't close it. I'll see what can be done fo fix both cases.

**Comment by promag** [comment]
@jonasschnelli @laanwj udpated OP and pushed an alternative implementation that also fixes options dialog.

**Comment by ken2812221** [comment]
f49253fda works on Windows. ACK 7bf22bf0c21d13557ec46a67413819ebcabc3df0

**Comment by laanwj** [comment]
Your code looks much better this way, by organizing it into the delegate class
utACK 7bf22bf0c21d13557ec46a67413819ebcabc3df0

**Pull request merged**
