### PR TITLE
validation: make CScriptCheck and prevector swap members noexcept

### PR DESCRIPTION
**Pull request by jonatack**
along with those seen elsewhere in the codebase (prevector and checkqueue units/fuzz/bench).

A swap must not fail; when a class has a swap member function, it should be declared noexcept.
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c84-a-swap-function-must-not-fail

### CODE REVIEW

**Comment by laanwj** [comment]
Concept ACK.
Do we have any other swap member functions?

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/bitcoin/bitcoin/pull/25017/commits/01e223ff9d9c3851395ed6e883fca509f2f0f4a4

**Comment by jonatack** [comment]
> Concept ACK. Do we have any other swap member functions?

Added the remaining ones found with `git grep "void swap"`.

**Comment by pk-b2** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/25017/commits/e5485e8e4be7f2ee0671f58c3dcce35c68ba0ee0

**Review by w0xlt — APPROVED** [review]
ACK https://github.com/bitcoin/bitcoin/pull/25017/commits/e5485e8e4be7f2ee0671f58c3dcce35c68ba0ee0

These changes make the code conform to the `C.85: Make swap noexcept` directive.

**Pull request merged**
