### PR TITLE
[QT] debug window "rpcconsole.ui" should have Qt::Window flag

### PR DESCRIPTION
**Pull request by jonasschnelli**
Should solve https://github.com/bitcoin/bitcoin/issues/5908
Needs testing (especially in wallet disabled mode).

### CODE REVIEW

**Comment by laanwj** [comment]
It should not be a dialog, just a window. A dialog implies a modal user interaction flow, whereas the debug window is just an auxiliary window.

**Comment by jonasschnelli** [comment]
@laanwj: QWindow is actually a non QWidget subclass and would require some adaptation to make it work as it is now.

Now i went for the most easy solution: adding a `Qt::Window` flag for the widget. This should be sufficient to make the debug window act as a normal window.

**Comment by laanwj** [comment]
Right. That's fine.

**Comment by jonasschnelli** [comment]
But i'm not sure if this is even required. I can't reproduce #5908.
But adding the `Qt::Window` flag for the console widget should anyway be the right thing.

**Comment by laanwj** [comment]
It should get added automatically when there is no parent widget.
Forcing the flag on will likely give problems when the debug console is embedded in the main window.

**Comment by jonasschnelli** [comment]
I'm closing this until #5908 turns out to be a real issue.

**Comment by laanwj** [comment]
We could add the flag conditionally, I think it can be passed to the constructor. But I agree we should first be sure it's the issue.

**Comment by jonasschnelli** [comment]
Regarding #5908, this is probably a Qt4.x "bug" (or inconsistency). I think the PR could make sense for users/package-maintainer who build/ship bitcoin-qt with Qt4.X. But it first needs testing over a Qt4 build.

**Pull request closed without merging**
