### PR TITLE
test: fix 'unknown named parameter' test in `wallet_basic`

### PR DESCRIPTION
**Pull request by brunoerg**
This PR removes loop when testing an unknown named parameter. They don't have any effect.

### CODE REVIEW

**Comment by kevkevinpal** [comment]
ACK [d9ef627](https://github.com/bitcoin/bitcoin/pull/28288/commits/d9ef627af771987c134e72d8358798e6f376ffdf)

**Review by jonatack — COMMENTED** [review]
ACK, good catch.  These tests were part of #20305, and I suppose the idea was to ensure `totalFee` and `feeRate` kwargs weren't valid. `totalFee` was then deprecated and subsequently removed from the codebase (there is a similar test in `wallet_bumpfee.py`). Testing for `feeRate` might be more interesting than for `key`.

**Review by jonatack — COMMENTED** [review]
ACK 551c4e036dc18e6b4a917d854c9785170898aff7

**Review by theStack — COMMENTED** [review]
Concept ACK

Could keep the loop and test for both invalid parameters (what was seemingly intended), as also done in e.g. `wallet_bumpfee.py`?
https://github.com/bitcoin/bitcoin/blob/9b066da8af77f971046a42118fd65046321bed1b/test/functional/wallet_bumpfee.py#L126-L127
(I think you'd need the dict unpacking operator `**` in this case though, as the parameters before are not positional, see https://stackoverflow.com/questions/47907268/how-do-i-pass-a-string-as-an-argument-name)

Also, IIUC the second loop could be removed completely, there is no value in having the exact same test executed twice for legacy wallets.

**Comment by brunoerg** [comment]
Thanks, @theStack for the review. It seems better to keep the loop, just pushed changing it. Also, I checked that for both legacy and descriptor the first occurance is enough, so there is no need to have both. Removed the second one.

**Review by theStack — APPROVED** [review]
ACK 9ad950031bc487a089ada5aeb9d0bef467b74dd3

**Comment by brunoerg** [comment]
I preferred to remove `totalFee` since it never had any relation to `sendtoaddress`, left only `feeRate`. I kept the removal of the second (and redundant) assert.

**Review by theStack — APPROVED** [review]
re-ACK 452c094449de00f3640e6e0763366e7603375825

(CI fail is in a different functional test and hence unrelated)

**Pull request merged**
