### PR TITLE
Improvement of documentation of command line parameter 'whitelist'

### PR DESCRIPTION
**Pull request by ghost**
I wonder what "netmask" one should give here. E.g. for 24 bit netmask give `whitelist=24` ? What use should that have?
If I guess correctly, what is meant here is a network segment, not a netmask. So, e.g. I expect one can say `whitelist=1.2.3.0/24`

### CODE REVIEW

**Comment by gmaxwell** [comment]
ACK.

**Comment by paveljanik** [comment]
Nica catch, utACK 8a639e1

**Comment by MarcoFalke** [comment]
Please just fix it upstream.
https://github.com/bitcoin/bitcoin/blob/40022fe5f2b576d023fa260eb176bde6d0779330/src/init.cpp#L394

We will take care to populate it downstream.

**Comment by wodry** [comment]
Sorry, I have made a mess. I don't know github so good. No I do not know anymore what to do.... :-/

**Comment by MarcoFalke** [comment]
No worries, you can add commits as you like to fix mistakes, we can take
care of squashing later. (Also, please close one of the two pulls)

**Comment by wodry** [comment]
Closed in favour of https://github.com/bitcoin/bitcoin/pull/9251

**Pull request closed without merging**
