### PR TITLE
[trivial] pull-tester cleanup: Run keypool, Tidy stdout

### PR DESCRIPTION
**Pull request by maflcko**
- Run keypool (takes 6 seconds)
- Print duration of each rpc test
- Structure output (bold, new lines)

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Should look like this:

screenshot from 2015-11-30 15-58-36

**Comment by jonasschnelli** [comment]
Nice!
utACK.

**Comment by laanwj** [comment]
Tested ACK

**Comment by jamesob** [comment]
Cool :)

**Comment by fanquake** [comment]
ACK

**Comment by paveljanik** [comment]
ACK Nice :-))

**Pull request merged**
