### PR TITLE
scripted-diff: Remove redundant license reference (HTTP URL)

### PR DESCRIPTION
**Pull request by practicalswift**
As discussed in "up for grabs" PR #12192:
* Remove redundant license reference (see https://github.com/bitcoin/bitcoin/pull/12192#issuecomment-367986454)

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Just to mention, that our license file is not contained if someone downloads an individual file only.

**Comment by practicalswift** [comment]
@MarcoFalke From a licensing perspective the contained text "MIT software license" should hopefully be sufficiently well-defined in case someone downloads an individual file only, don't you think?

**Comment by practicalswift** [comment]
Rebased. Please review :-)

**Comment by practicalswift** [comment]
Rebased!

**Comment by practicalswift** [comment]
Rebased!

**Comment by practicalswift** [comment]
Rebased! No longer touching copyright year to keep this PR focused.

**Comment by practicalswift** [comment]
Rebased!

**Comment by MarcoFalke** [comment]
I think this needs some Concept ACK first. If no one comments here, either close it or bring it up in one of the meetings as a short topic.

**Review by ryanofsky — COMMENTED** [review]
utACK 176bb1b05fe3eee7deb1a351adb87d1f76f1c3dc. Since the scripted-diff affects a lot of files, though, I think it would be good to anchor the `sed '/PATTERN/d'` commands with `sed '/^PATTERN$/d'` to make sure they are aren't unintentially removing other text or closing comment or quote symbols.

> bring it up in one of the meetings as a short topic.

This is a good suggestion for many of your pr's, practicalswift, if you are free Thursdays at 19:00 UTC (
https://bitcoincore.org/en/meetings/)

**Pull request closed without merging**
