### PR TITLE
[24.x] Additional backports for 24.1

### PR DESCRIPTION
**Pull request by fanquake**
Backports:
* https://github.com/bitcoin/bitcoin/pull/27279 (only f73782a9032a462a71569e9424db9bf9eeababf3)
* https://github.com/bitcoin/bitcoin/pull/27462
* https://github.com/bitcoin/bitcoin/pull/27468
* https://github.com/bitcoin/bitcoin/pull/27473

### CODE REVIEW

**Review by hebasto — APPROVED** [review]
ACK 5c937ae7c323198c76f1743870c68f8576305a6e

**Comment by stickies-v** [comment]
Suggest adding https://github.com/stickies-v/bitcoin/commit/db6cf79694112a4679378fdd1f2bdf69cf6adbea which backports #27468, but without the changes to `rest_mempool` (query parameters in this endpoint were added only after v24 in #26207).

**Comment by fanquake** [comment]
> Suggest adding https://github.com/stickies-v/bitcoin/commit/db6cf79694112a4679378fdd1f2bdf69cf6adbea which backports https://github.com/bitcoin/bitcoin/pull/27468,

Pulled & added metadata. 

> Suggest adding https://github.com/bitcoin/bitcoin/commit/f73782a9032a462a71569e9424db9bf9eeababf3.

Ok.

**Review by stickies-v — APPROVED** [review]
ACK dc711fbd32653b09e196f72942106114a32353f4

Verified that the backports correspond to their original PR, and I can't see any silent merge conflicts. Release notes match the backported changes.

**Review by hebasto — APPROVED** [review]
re-ACK dc711fbd32653b09e196f72942106114a32353f4

**Review by jonatack — COMMENTED** [review]
ACK dc711fbd32653b09e196f72942106114a32353f4

Pull description is missing some of the changes.

**Comment by fanquake** [comment]
This has been merged.

**Pull request closed without merging**
