### PR TITLE
build: fix dmg-mount crashes on OSX 10.11

### PR DESCRIPTION
**Pull request by theuni**
Without this, attempting to mount the -rc1 dmg crashes finder in OSX 10.11.

Needs testing in older versions to ensure that it's backwards-compat.

### CODE REVIEW

**Comment by theuni** [comment]
I'm unsure if this is a local issue or not. It would be great if someone else on OSX 10.11 could test the rc1 .dmg to see if it also crashes for them: https://bitcoincore.org/cfields/bitcoin-0.11.1rc1/bitcoin-0.11.1-osx-unsigned.dmg

To reproduce: just double-click the dmg. For me, Finder crashes and I never see the contents of the image.

**Comment by jonasschnelli** [comment]
Will update a 10.10 VM to 10.11 next week and take a closer look.

**Comment by urlin** [comment]
OSX 10.11. I can't reproduce it.

**Comment by jonasschnelli** [comment]
Works here (0.11.1-rc2).

bildschirmfoto 2015-10-12 um 14 43 29

**Comment by theuni** [comment]
Thanks for testing, looks like this is a local issue. Closing for now.

**Pull request closed without merging**
