### PR TITLE
scripted-diff: update license URLs to https

### PR DESCRIPTION
**Pull request by div72**
This PR changes MIT license URLs to HTTPS. http://www.opensource.org/licenses/mit-license.php already redirects to https://opensource.org/licenses/mit-license.php and it's a bit tedious to update it when porting stuff downstream.

### CODE REVIEW

**Comment by prayank23** [comment]
If others ACK this change, we can even remove dot from the link:

https://opensource.org/licenses/mit-license.php. :x:
https://opensource.org/licenses/mit-license.php :white_check_mark:

**Comment by hebasto** [comment]
> If others ACK this change, we can even remove dot from the link:
> 
> https://opensource.org/licenses/mit-license.php. x
> https://opensource.org/licenses/mit-license.php white_check_mark

This is not a "dot in the link". It's rather a full stop at the end of the sentence.

**Comment by prayank23** [comment]
Not sure if its a sentence or a link even needs to end with anything extra.

Example: 

https://github.com/github/snakebite/blob/6a456e6100b0c1be66cc1f7f9d7f50494f369da3/setup.py#L9

There is nothing extra here after `http://www.apache.org/licenses/LICENSE-2.0`

Anyway its a nit which can be ignored. Don't think anyone uses links from here.

**Comment by laanwj** [comment]
NACK, this is not worth changing 1157(!) files for.

**Comment by div72** [comment]
@laanwj Would modifying the `contrib/devtools/copyright_header.py` to handle it with the next copyright update be acceptable then?

**Comment by laanwj** [comment]
> @laanwj Would modifying the contrib/devtools/copyright_header.py to handle it with the next copyright update be acceptable then?

Not if it changes all files. I guess if a header has to be updated anyway it doesn't hurt to change

but… I honestly don't think changing http to https is important here, the lowest priority possible. I'm not sure there should even be a link, it's not like that site is leading, ideally people would refer to the LICENSE file that is *in the repository*. And everyone knows what the "MIT" license is, anyhow, it could be replaced with "SPDX-License-Identifier: MIT" and it'd be just as clear.

**Comment by div72** [comment]
By that same logic, aren't the copyright headers redundant? They should be the same as the LICENSE file unless specified otherwise.

**Comment by laanwj** [comment]
Opinions differ on that. I think the status quo is to have *some* license marker in every source file because files tend to get copied around on their own sometimes. This is why the SPDX standard was designed. It's more set in stone than either a website reference or local repo reference. But it's newer than bitcoin.

Anyhow, IMO, it's not worth changing this at this point, the incremental benefit to changing this now is zilch. I would suggest letting this go and finding another way to contribute.

**Pull request closed without merging**
