### PR TITLE
test: Use assert_equal over assert for easier debugging

### PR DESCRIPTION
**Pull request by maflcko**
See #23116

### CODE REVIEW

**Review by jonatack — COMMENTED** [review]
Light code review ACK fa8f3ba131d5460275b52c08608ebad8195a420d

**Review by hebasto — APPROVED** [review]
ACK fa8f3ba131d5460275b52c08608ebad8195a420d, I have reviewed the code and it looks OK, I agree it can be merged.

**Review by theStack — APPROVED** [review]
Code-review ACK fa8f3ba131d5460275b52c08608ebad8195a420d

Note that there are dozens of other instances in the functional test code where this substitution should be done:
```
$ cd ./test/functional
$ git grep assert.*== | wc -l
      153
```
(though this number contains obviously also some false-positives)

**Comment by MarcoFalke** [comment]
> (though this number contains obviously also some false-positives)

Could be filed as a good first issue?

**Pull request merged**
