### PR TITLE
travis: Run unit tests --with-sanitizers=thread

### PR DESCRIPTION
**Pull request by maflcko**
See issue #12691

### CODE REVIEW

**Comment by practicalswift** [comment]
Concept ACK

The sanitizers are our friends in the eternal struggle for correctness!

**Comment by MarcoFalke** [comment]
Needs #14083 to pass

**Comment by practicalswift** [comment]
Works as expected:

```
# Benchmark, evals, iterations, total, min, max, median
ThreadSanitizer:DEADLYSIGNAL
==26609==ERROR: ThreadSanitizer: SEGV on unknown address 0x000000000000 (pc 0x56102d97b3ac bp 0x000000000000 sp 0x7f3835779e88 T26614)
==26609==The signal is caused by a WRITE memory access.
==26609==Hint: address points to the zero page.
    #0 __tsan_func_entry :? (bench_bitcoin+0xfdf3ab)
    #1 boost::detail::thread_data<boost::_bi::bind_t<void, boost::_mfi::mf0<void, CScheduler>, boost::_bi::list1<boost::_bi::value<CScheduler*> > > >::run() ??:? (bench_bitcoin+0x109aed1)
    #2 boost::this_thread::interruption_requested() ??:? (libboost_thread.so.1.65.1+0x11bcc)
    #3 start_thread ??:? (libpthread.so.0+0x76da)
    #4 clone ??:? (libc.so.6+0x12188e)
ThreadSanitizer can not provide additional info.
SUMMARY: ThreadSanitizer: SEGV :? in __tsan_func_entry
==26609==ABORTING
```

**Comment by practicalswift** [comment]
Why the close? :-)

**Comment by luke-jr** [comment]
Note: This was superceded by #14764

**Pull request closed without merging**
