### PR TITLE
Save client version to the settings file on shutdown

### PR DESCRIPTION
**Pull request by jonatack**
Following an [IRC conversation today](http://www.erisian.com.au/bitcoin-core-dev/log-2021-02-13.html#l-325), this patch proposes to persist `CLIENT_VERSION` as "lastrunversion" to the `settings.json` file on shutdown.

This allows, for example, to detect if the user upgraded with code like
```cpp
if (CLIENT_VERSION > chain.getRwSetting("lastrunversion").get_int())
```
so as to take various actions.

Reviewers, this patch can be tested manually by opening `<datadir>/signet/settings.json` in your editor, starting and stopping signet, and watching the file be updated. One can also manually edit the setting and verify that the version is updated on shutdown.

```json
{
    "lastrunversion": 219900,
    "wallet": [
        ""
    ]
}
```

### CODE REVIEW

**Comment by michaelfolkson** [comment]
Concept ACK (assuming no downsides)

I think this could be useful for providing better logging around upgrades. Currently logging does not recognize when an upgrade is happening. Something like "First time running new version" "Successful upgrade to version x" etc

**Comment by jonatack** [comment]
Changed fieldname from "version" to "lastrunversion" per IRC suggestion by @luke-jr (thanks!)

**Comment by brunoerg** [comment]
Concept ACK

**Comment by ryanofsky** [comment]
I didn't read the IRC link, but this does not seem like a good idea. If you can't detect a new feature directly and need a flag to indicate when it's been enabled, you should probably set that flag at the time the feature is actually enabled (not shutdown) and choose a flag name and value clearly tied to the feature. This way behavior can be straightforward and reliable, not confusing and based on a flaky heuristic.

(If in addition, the feature is backwards incompatible and you need to prevent bitcoin versions that don't support the feature from loading after it's enabled, implementing the `-require=<feature>` flag suggested https://github.com/bitcoin/bitcoin/pull/15935#issuecomment-663566209 could be a good approach.)

In any case, would encourage opening an issue that clearly describes the problem so a good solution can be found.

**Comment by jonatack** [comment]
Thanks @ryanofsky. I learned more about the `settings.json` file doing this. Opened a patch for the specific case in #21181 instead.

**Review by curtcurt871 — COMMENTED** [review]
21171

**Pull request closed without merging**
