### PR TITLE
build, qt: drop fix_no_printer patch, add CVE fixes

### PR DESCRIPTION
**Pull request by prusnak**
- builds on top of https://github.com/bitcoin/bitcoin/pull/24668, hence the draft state
- contains fix from https://github.com/bitcoin/bitcoin/pull/24684
- adds 2 CVE fixes mentioned in https://github.com/bitcoin/bitcoin/pull/24668

### CODE REVIEW

**Comment by prusnak** [comment]
@MarcoFalke @laanwj If there is a desire I can create a backport PR to 23.x branch with only 8d83d31 included.

**Comment by fanquake** [comment]
NACK. I don't understand why all these Qt patch changes are being split into different PRs. If we are going to go through the motions of bumping Qt, then all the changes should be in #24668.

**Comment by prusnak** [comment]
> NACK.

This PR is a combination of all Qt related PRs. If your goal is to have all changes combined, I can just push the same changeset to https://github.com/bitcoin/bitcoin/pull/24668 and close this PR.

**Comment by fanquake** [comment]
> If our goal is to have all changes combined, I can just push the same changeset to https://github.com/bitcoin/bitcoin/pull/24668 and close this PR.

Yes, lets do that.

**Comment by prusnak** [comment]
> Yes, lets do that.

Done. Closing this PR. Sorry for the noise.

**Pull request closed without merging**
