### PR TITLE
Countermeasures against eclipse attacks

### PR DESCRIPTION
**Pull request by sipa**
This implements countermeasures 1, 2, and 6 from the http://cs-people.bu.edu/heilman/eclipse/ paper.

### CODE REVIEW

**Comment by sipa** [comment]
Someone should test how long it takes to find peers with this, when DNS seeding and the built-in seeds are disabled. I'm not able to test the next ~3 days or so.

**Comment by sipa** [comment]
This is running on bitcoin.sipa.be, with -DDEBUG_ADDRMAN enabled.

**Comment by laanwj** [comment]
Going to test this.

> Someone should test how long it takes to find peers with this, when DNS seeding and the built-in seeds are disabled.

OK, disabling those.

**Comment by jgarzik** [comment]
Typically, (a) less than 11 seconds if you have a fresh addrman, or (b) sometimes hours or longer, if not.

Current code skips DNS seeds & built in, if it manages to connect to some peers within a short amount of time.

**Comment by sipa** [comment]
@jgarzik I mean after this patch. Reason is the bias changes in peer selection. If you have very few tried peers, the new code will likely very actively keep retrying those (as there is a 50% chance to pick a previously tried peer), and there is no bias towards more recently learned addresses anymore. Both probably slow down initial connection, but likely don't have that much impact in a working system.

**Comment by laanwj** [comment]
It instantly found a peer on start:
```
2015-03-24 13:55:51 init message: Loading addresses...
2015-03-24 13:55:51 Loaded 14669 addresses from peers.dat  664ms
...
2015-03-24 13:55:51 receive version message: /Satoshi:0.9.2/: version 70002, blocks=346129, ...
```

**Comment by gavinandresen** [comment]
Ran this with -dnsseed=0 and a peers.dat from a bitcoind that I stopped 23 hours ago:

```
2015-03-24 20:15:18 Loaded 12904 addresses from peers.dat  512ms
   ...
2015-03-24 20:15:30 connect() to 93.143.11.182:8333 failed after select(): Connection refused (61)
2015-03-24 20:16:15 connect() to 85.199.110.252:8333 failed after select(): Connection refused (61)
2015-03-24 20:16:16 receive version message: /Satoshi:0.10.0/: version 70002, blocks=349059, us=...., peer=1
```
... so just under one minute to connect.

**Comment by 21E14** [comment]
utAck. The paper does not specify a countermeasure "6" in Section 7.

We've still got a bit to go (the symptoms being #5886, #5397, #5352, #5299), but great to see the attention on P2P. Let it remind us that P2P is at the (decentralized) core of Bitcoin Core as much as transactions are; arguably more so.

**Comment by sipa** [comment]
21E14: there are further countermeasures listed in the appendix.

**Comment by 21E14** [comment]
It's worth pointing out.

This may also be a good opportunity to tilt the balance of preprocessor directives vs "magic" values, e.g. ADDRMAN_TRIED_BUCKETS_PER_GROUP (2 occurrences) vs 24 * 60 * 60 & 60 * 10.

Interestingly, P2P is not very well reflected in the ongoing libification. As it stands, libbitcoin_server is its closest anchor, but the two are arguably distinct. A large subset of the protocol is arguably entirely P2P (ver, verack, ping, pong, inv, getheaders, ...).

**Comment by fanquake** [comment]
Running with -dnsseed=0
```
2015-03-26 03:21:39 init message: Loading addresses...
2015-03-26 03:21:39 Loaded 12984 addresses from peers.dat  94ms
2015-03-26 03:21:39 DNS seeding disabled
2015-03-26 03:21:40 connect() to 199.167.100.226:8333 failed after select(): Connection refused (61)
2015-03-26 03:21:52 receive version message: /Satoshi:0.9.3/: version 70002, blocks=349268, us=..., peer=1
2015-03-26 03:21:58 receive version message: /Satoshi:0.10.0/: version 70002, blocks=349268, us=..., peer=2
2015-03-26 03:22:05 receive version message: /Satoshi:0.9.2.1/: version 70002, blocks=349268, us=..., peer=3
2015-03-26 03:22:16 receive version message: /Satoshi:0.10.0/: version 70002, blocks=349268, us=..., peer=4
```

Removed peers.dat
```
2015-03-26 03:28:42 init message: Loading addresses...
2015-03-26 03:28:42 Loaded 0 addresses from peers.dat  1ms
2015-03-26 03:28:42 dnsseed thread start
2015-03-26 03:28:44 receive version message: /Satoshi:0.10.0/: version 70002, blocks=349269, us=..., peer=1
2015-03-26 03:28:45 72 addresses found from DNS seeds
2015-03-26 03:28:45 dnsseed thread exit
2015-03-26 03:28:46 receive version message: /Satoshi:0.8.6/: version 70001, blocks=349269, us=..., peer=2
2015-03-26 03:28:47 receive version message: /Satoshi:0.10.0/: version 70002, blocks=349269, us=..., peer=3
2015-03-26 03:28:56 receive version message: /Satoshi:0.9.3/: version 70002, blocks=349269, us=..., peer=4
```

**Comment by sipa** [comment]
I tried a few times with -dnsseed=0 and a copy of bitcoin.sipa.be's peers.dat, and always had an initial connection between 15 and 30 seconds later.

**Comment by laanwj** [comment]
Works for me - tested ACK

**Comment by gmaxwell** [comment]
ACK.

**Comment by jgarzik** [comment]
ut ACK

My only nit:  I wonder if we could replace that '%' with a shift.  Could be, if the powers [of two] are aligned.

**Comment by sipa** [comment]
At -O2, gcc does strength reduction which should turns the modulo
operations into bitmasking.

**Comment by jgarzik** [comment]
@sipa should, agreed.  With our 256 bit C++ implemented integer type, I wonder if that is true?

**Comment by sipa** [comment]
There are no uint256's involved in the modulus operations. Hashing is
performed, then the lower 64 bits are extracted, and then a modulus is
applied.

Besides, uint256 does not even offer arithmetic operations anymore. It's
just an encapsulated 256-size bit vector.

**Comment by laanwj** [comment]
Cherry-picked to 0.10 as aa587d4 0c6f334 214154e 2218d4b cf0218f b788994
Some conflicts encountered with uint256 usage, but was easy to backport.

**Pull request merged**
