### PR TITLE
Update doc/build-unix.md to reflect my experience trying to build on a m...

### PR DESCRIPTION
**Pull request by mwleeds**
...achine with 1 GB.

### CODE REVIEW

**Comment by luke-jr** [comment]
Did you try setting compiler options for low-memory systems? For example:
```
LDFLAGS="-Wl,--no-keep-memory -Wl,--reduce-memory-overheads"
CXXFLAGS="-g0 --param ggc-min-expand=0 --param ggc-min-heapsize=32768"
```

**Comment by luke-jr** [comment]
Also: I compiled bitcoind just fine with normal flags on a 512 MB RAM system with no swap...

**Comment by mleeds95** [comment]
I appended the flags you suggested in the corresponding lines of the Makefile, but still got "virtual memory exhausted: Cannot allocate memory" on a virtual machine running Ubuntu 14.04. Oh well. I'll just send a binary over to it instead. On a different note, when I compiled it on my linux mint desktop I had to install automake in addition to the listed packages, so perhaps that should be added to the list of ubuntu dependencies.

**Comment by luke-jr** [comment]
Virtual memory exhausted means the container system (OpenVZ or LXC most likely) is limiting it - it doesn't mean it ran out of real memory.

If you build from git, you need automake, but not if you use a release.

**Comment by mleeds95** [comment]
Ah ok thanks for the help. And thanks for all your work on bitcoin.

**Pull request closed without merging**
