### PR TITLE
test: Add missing ECC_Stop() in GUI rpcnestedtests.cpp

### LINKED ISSUE #16288: tests: make check currently broken on macOS
```bash
git checkout master && git clean -fxd && ./autogen.sh && ./configure && make check -j8
.....
Running tests: torcontrol_tests from test/torcontrol_tests.cpp
Running tests: transaction_tests from test/transaction_tests.cpp
Running tests: txindex_tests from test/txindex_tests.cpp
../build-aux/test-driver: line 107: 85583 Abort trap: 6           "$@" > $log_file 2>&1
FAIL: qt/test/test_bitcoin-qt

cat src/test-suite.log 
==============================================
   Bitcoin Core 0.18.99: src/test-suite.log
==============================================

# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: qt/test/test_bitcoin-qt
=============================

********* Start testing of AppTests *********
Config: Using QtTest library 5.12.3, Qt 5.12.3 (x86_64-little_endian-lp64 shared (dynamic) release build; by Clang 10.0.1 (clang-1001.0.46.4) (Apple))
PASS   : AppTests::initTestCase()
WARNING: AppTests::appTests() Skipping AppTests on mac build with 'minimal' platform set due to Qt bugs. To run AppTests, invoke with 'test_bitcoin-qt -platform cocoa' on mac, or else use a linux or windows build.
   Loc: [qt/test/apptests.cpp(61)]
PASS   : AppTests::appTests()
PASS   : AppTests::cleanupTestCase()
Totals: 3 passed, 0 failed, 0 skipped, 0 blacklisted, 1ms
********* Finished testing of AppTests *********
********* Start testing of URITests *********
Config: Using QtTest library 5.12.3, Qt 5.12.3 (x86_64-little_endian-lp64 shared (dynamic) release build; by Clang 10.0.1 (clang-1001.0.46.4) (Apple))
PASS   : URITests::initTestCase()
PASS   : URITests::uriTests()
PASS   : URITests::cleanupTestCase()
Totals: 3 passed, 0 failed, 0 skipped, 0 blacklisted, 0ms
********* Finished testing of URITests *********
********* Start testing of RPCNestedTests *********
Config: Using QtTest library 5.12.3, Qt 5.12.3 (x86_64-little_endian-lp64 shared (dynamic) release build; by Clang 10.0.1 (clang-1001.0.46.4) (Apple))
PASS   : RPCNestedTests::initTestCase()
Assertion failed: (secp256k1_context_sign == nullptr), function ECC_Start, file key.cpp, line 349.
FAIL qt/test/test_bitcoin-qt (exit status: 134)
```

Looks like it's been failing since #16252, cc @MarcoFalke.

```bash
git checkout bc948d4cfd6da2effa8c2ae619e11e83207c6fbc && git clean -fxd && ./autogen.sh && ./configure && make check -j8
....
Running tests: db_tests from wallet/test/db_tests.cpp
PASS: qt/test/test_bitcoin-qt
Running tests: psbt_wallet_tests from wallet/test/psbt_wallet_tests.cpp
============================================================================
Testsuite summary for Bitcoin Core 0.18.99
============================================================================
# TOTAL: 1
# PASS:  1
```

### PR DESCRIPTION
**Pull request by jonasschnelli**
Fixes #16288

Was probably missing in #7783

### CODE REVIEW

**Review by fanquake — APPROVED** [review]
ACK f466c4ce846000b2f984b4759f89f3f793fa0100. Tested running `make check` on macOS.

**Comment by MarcoFalke** [comment]
Why is this only happening on macos?

**Comment by jonasschnelli** [comment]
Because on Mac, the `AppTests::appTests()` gets skipped and misses the `ECC_Stop()` which would have cured the issue that `ECC_Start()` gets double initialized through `RPCNestedTests::rpcNestedTests()` -> `TestingSetup test`.

I don't know if we could get rid of `TestingSetup test` in `RPCNestedTests::rpcNestedTests()` though.

**Comment by Sjors** [comment]
ACK f466c4c. Tested by comparing `make check` on master and this PR with macOS 10.14.5. I also tried with and without `--enable-debug` / `--without-gui`.

**Pull request merged**
