### PR TITLE
Remove unnecessary forward class declarations in header files

### PR DESCRIPTION
**Pull request by practicalswift**
Remove unnecessary forward class declarations in header files. These are no longer needed.

### CODE REVIEW

**Comment by sipa** [comment]
utACK d56a058715ae95d7123df0d5771a5cdcb94cccb7. If it compiles without them, they're guaranteed to be unnecessary.

**Review by dcousens — APPROVED** [review]

**Comment by benma** [comment]
Cool. How did you find them? If you found them using a tool, it would be good to mention the command you used in the commit message.

**Comment by fanquake** [comment]
Tested it compiles ACK d56a058

**Comment by paveljanik** [comment]
compilesACK https://github.com/bitcoin/bitcoin/pull/10568/commits/d56a058715ae95d7123df0d5771a5cdcb94cccb7

**Comment by practicalswift** [comment]
Merge conflict resolved!

**Pull request merged**
