### PR TITLE
Update build-openbsd.md

### PR DESCRIPTION
**Pull request by rusticbison**
add openSSL to base dependencies, it is required for secp256k1

### CODE REVIEW

**Comment by fanquake** [comment]
OpenSSL has not been required to build Bitcoin Core since #17265. What error are you seeing?

**Comment by MarcoFalke** [comment]
Maybe the build notes should mention that they are only valid for their own branch/commit and don't document how to compile older branches/commits?

**Comment by rusticbison** [comment]
> Maybe the build notes should mention that they are only valid for their own branch/commit and don't document how to compile older branches/commits?

Yes this would be helpful. There is no way to know this otherwise.

> OpenSSL has not been required to build Bitcoin Core since #17265. What error are you seeing?

Before I installed OpenSSL, the build would fail with this error: 

`gmake[3] Leaving directory '/tmp/bitcoin/src/secp256k1`
`ld: error: undefined symbol: ChaCha20::Keystream(unsigned char*, unsigned long)`
`>>> referenced by random.h.118(./random.h:118)`

**Comment by fanquake** [comment]
> Maybe the build notes should mention that they are only valid for their own branch/commit and don't document how to compile older branches/commits?

I think that should be implied. If you've checked out and want to build 0.19.x, you should be looking at the docs in the 0.19 branch.

> Before I installed OpenSSL, the build would fail with this error:
> gmake[3] Leaving directory '/tmp/bitcoin/src/secp256k1
> ld: error: undefined symbol: ChaCha20::Keystream(unsigned char*, unsigned long)
> >>> referenced by random.h.118(./random.h:118)

I've just built master (5622d8f3156a293e61d0964c33d4b21d8c9fd5e0) and `v0.19.0.1` on OpenBSD 6.6 the `OpenSSL` didn't need to be installed for either (`pkg_info` below). `bitcoind` is linked against `libsodium.so`.

If you are still having issues compiling after cleaning your build directory, and rebuilding, please open an issue with all the relevant information. I'm going to close this, as we aren't adding openssl to the required packages list.
 
```bash
autoconf-2.69p2     automatically configure source code on many Un*x platforms
automake-1.15.1     GNU Standards-compliant Makefile generator
bash-5.0.11         GNU Bourne Again Shell
boost-1.66.0p7      free peer-reviewed portable C++ source libraries
bzip2-1.0.8         block-sorting file compressor, unencumbered
curl-7.66.0         get files from FTP, Gopher, HTTP or HTTPS servers
cvsps-2.1p2         generate patchsets from CVS repositories
dmidecode-3.1       dump DMI/SMBIOS contents in human-readable format
gettext-runtime-0.20.1p0 GNU gettext runtime libraries and programs
git-2.23.0          GIT - Tree History Storage Tool
gmake-4.2.1p4       GNU make
icu4c-64.2p0        International Components for Unicode
intel-firmware-20191115v0 microcode update binaries for Intel CPUs
libevent-2.0.22p1   event notification library
libffi-3.2.1p5      Foreign Function Interface
libiconv-1.16p0     character set conversion library
libidn2-2.0.0p0     implementation of IDNA2008 internationalized domain names
libltdl-2.4.2p1     GNU libtool system independent dlopen wrapper
libpsl-0.20.2p0     public suffix list library
libsodium-1.0.18    library for network communications and cryptography
libtool-2.4.2p0     generic shared library support script
libunistring-0.9.7  manipulate Unicode strings
metaauto-1.0p3      wrapper for gnu auto*
nghttp2-1.39.2      library for HTTP/2
p5-Error-0.17025    error/exception handling in an OO-ish way
pcre2-10.33         perl-compatible regular expression library, version 2
python-3.7.4        interpreted object-oriented programming language
quirks-3.182        exceptions to pkg_add rules
sqlite3-3.29.0      embedded SQL implementation
sudo-1.8.28.1p0     execute a command as another user
vim-8.1.2061-no_x11 vi clone, many additional features
wget-1.20.3p1       retrieve files from the web via HTTP, HTTPS and FTP
xz-5.2.4            LZMA compression and decompression tools
zeromq-4.3.2        open source message queue optimised for performance
```

**Comment by laanwj** [comment]
apart from master no longer needing the OpenSSL API at all anymore, OpenSSL hasn't been required on OpenBSD for a long time, first they used LibreSSL and now sodium, apparently

use of the OpenBSD openssl port is discouraged, it even used to have some comment like 
```patch
-CATEGORIES=    security net
+CATEGORIES=    security net games
```
:smile:

**Pull request closed without merging**
