### PR TITLE
Docs: Remove the ending slashes from RPC URI format.

### LINKED ISSUE #11861: Multi-wallet RPC URI parsing invalid when ending with a slash
Using the newer RPC access point for multi-wallet support as described https://bitcoincore.org/en/releases/0.15.0/#multi-wallet-support will __not__ work if the URI ends with a slash ( `/` ).
In other words, all RPCs for multi-wallet would only work if the URI does not end with a slash.

Expected behavior:
Any RPC command (or by using _curl_ ) __should work__ for URI like `http://username:password@127.0.0.1:8332/wallet/wallet.dat/` regardless of the ending slash.

Actual behavior:
An error will be return `{"result":null,"error":{"code":-18,"message":"Requested wallet does not exist or is not loaded"},"id":"curltext"}` even when the wallet name is valid.
- `http://username:password@127.0.0.1:8332/wallet/wallet.dat` will work.

Reproduction steps:
1. Run `curl --data-binary '{"jsonrpc":"1.1","id":"curltext","method":"listreceivedbyaddress","params":[]}' -H 'content-type:text/plain;' http://username:password@127.0.0.1:8332/wallet/wallet.dat/`

Found in Version: 0.15.1
OS: Windows 10 Pro with Ubuntu WSL _(if this info matters)_

### PR DESCRIPTION
**Pull request by jackycjh**
This resolves #11861 (A confusion caused by incorrect information in the release notes).

More information can be found at #11861.

### CODE REVIEW

**Comment by promag** [comment]
Do we fix release notes?

**Comment by DuncanBetts** [comment]
I would imagine the intent of release notes is to support a release, by providing accurate information about it. So, my opinion would be that we should. Happy to hear arguments against :).

**Comment by laanwj** [comment]
Normally I'm against changing release notes after a release. They have been copied to many places, in mail, other sites. So it's like closing the barn after the horse left. 

But I'm okay with changing this as the examples are really wrong. I'm surprised no one discovered this sooner.

**Comment by ryanofsky** [comment]
> I'm surprised no one discovered this sooner.

Heh, I'm not surprised by this at all. While we were discussing this change (admittedly, I was against it), I asked repeatedly for documentation to be written to accompany it because I thought the usage was complex and confusing.

I think it's best when documentation and code changes are made at the same time. It prevents mistakes, makes code easier to review, and can even lead to better designs because often writing documentation causes you to look at things from a different perspective.

**Pull request merged**
