### PR TITLE
Implement Keccak and SHA3_256

### PR DESCRIPTION
**Pull request by sipa**
Add a simple (and initially unoptimized) Keccak/SHA3 implementation based on https://github.com/mjosaarinen/tiny_sha3/blob/master/sha3.c, as one will be needed for TORv3 support (the conversion from BIP155 encoding to .onion notation uses a SHA3-based checksum). In follow-up commits, a benchmark is added, and the Keccakf function is unrolled for a (for me) 4.9x speedup.

Test vectors are taken from https://csrc.nist.gov/projects/cryptographic-algorithm-validation-program/secure-hashing#sha3vsha3vss.

### CODE REVIEW

**Comment by sipa** [comment]
Ping @vasild.

**Comment by jonatack** [comment]
Nice!

**Comment by fanquake** [comment]
Concept ACK on this approach to adding a Keccak/SHA3 implementation.

**Comment by naumenkogs** [comment]
Concept ACK as a requirement for Torv3.

**Comment by practicalswift** [comment]
Concept ACK

Nice simple implementation: will fuzz it to see if I'm able to reject that it is as robust as it looks :)

**Comment by laanwj** [comment]
This is a nice compact implementation of KeccaK/SHA3.
Code review ACK 2263ab190e625f81d154ce6581f37adcdb31ef8b

**Review by vasild — APPROVED** [review]
ACK 2263ab190

I tested this with https://github.com/bitcoin/bitcoin/pull/19845, changing the code to use this SHA3_256 implementation and it works (produces the same checksum in the TORv3 address):

```cpp
// CHECKSUM = H(".onion checksum" | PUBKEY | VERSION)[:2]

hasher.Write(Span<const uint8_t>{reinterpret_cast<const uint8_t*>(".onion checksum"), 15});
hasher.Write(m_addr);
hasher.Write(Span<const uint8_t>{reinterpret_cast<const uint8_t*>("\x03"), 1});
```

I also tested this implementation against the same vectors as `TestSHA256`, just like in https://github.com/bitcoin/bitcoin/pull/19845 and the results are the same (as the SHA3_256 from that PR, not as the SHA256!).

The last two tests:
```cpp
    TestSHA3_256(std::string(1000000, 'a'),
                 "5c8875ae474a3634ba4fd55ec85bffd661f32aca75c6d699d0cdcb6c115891c1");
    TestSHA3_256(test1, "7d06279100b45d54a479e973aa01ea0cceafb656c45238557813c9c39ceb6403");
```

take 2.8s VS 0.4s for SHA256 (in non optimized build).

Verdict: likely it works correctly and there may be room for performance improvement, but this is not relevant for the TORv3 code.

Ideally this would get merged first and then https://github.com/bitcoin/bitcoin/pull/19845 adapted to use it (and ditch the implementation imported in that PR).

**Comment by sipa** [comment]
@vasild FWIW, you should be able to use `hasher.Write(MakeUCharSpan(".onion checksum"))`.

**Comment by vasild** [comment]
Right, all is good. And SHA3-256 [is supposed to be slower than SHA256](https://crypto.stackexchange.com/questions/68307/what-is-the-difference-between-sha-3-and-sha-256).

**Comment by laanwj** [comment]
> Verdict: likely it works correctly and there may be room for performance improvement, but this is not relevant for the TORv3 code.

As it is not relevant to our use case, I don't think this is worth it. I wouldn't like to see the added complication of assembly implementations and special intrinsics just for computing an address checksum (it would be different if it was for *packet* checksums). Brevity (and of course correctness) of the implementation is the important thing here.

**Review by theStack — COMMENTED** [review]
Concept ACK
It seems that currently the header `<array>` is unnecessarily included both in the implementation and the unit test source files.
// EDIT: ~~Same for `<stdint.h>` and `<stdlib.h>` in `sha3.h`.~~

**Comment by laanwj** [comment]
@theStack Agree about `array`, it doesn't seem to be used at all. Wouldnt' stdint.h be necessary for sized integer types such as `uint32_t`? (yes, it's probably included indirectly somehow, but we like to be explicit about dependencies)

**Comment by theStack** [comment]
> @theStack Agree about `array`, it doesn't seem to be used at all. Wouldnt' stdint.h be necessary for sized integer types such as `uint32_t`? (yes, it's probably included indirectly somehow, but we like to be explicit about dependencies)

 @laanwj: Oh indeed, you are right. For some reason I forgot that sized integer types and `size_t` are not integral part of the language but defined in headers... 🤦‍♂️ so both `<stdint.h>` are `<stdlib.h>` are needed indeed (though one could probably use the C++ counterparts `<cstdint>` and `<cstdlib>` instead, but that'd be more of a general discussion not related only to this PR).

**Comment by sipa** [comment]
I added `<array>` to get access to `std::begin` and `std::end`.

**Comment by laanwj** [comment]
> I forgot that sized integer types and size_t are not integral part of the language but defined in headers... man_facepalming 

Haah. I try to forget that sometimes …

> I added <array> to get access to std::begin and std::end.

Oh, of course!

**Comment by theStack** [comment]
> I added `<array>` to get access to `std::begin` and `std::end`.

Ah, I wasn't aware those are declared in `<array>`. Sorry for the noise.

For reviewing this PR, I thought it would be nice to validate this implementation against a standard one with random input data  (in addition to only the test vectors). I decided for python's `hashlib` which has `sha3_256` available since Version 3.6. Thanks to [pybind11](https://github.com/pybind/pybind11) it's super-easy to create Python bindings for C++ code. With less than 20 LOC binding code, SHA3_256 can be used in Python in a natural way: 
```
import sha3_sipa


def sha3_256_sipa(input):
    return sha3_sipa.SHA3_256().Write(input).Finalize()
```
The whole mini-project with Makefile and the comparison test with random input data is on my branch https://github.com/theStack/bitcoin/tree/test-sha3_256-against-python3-implementation
If anyone wants to try out, the following instructions should work on any recent Ubuntu with Python3.6+:
```
$ sudo apt-get install python3-dev
$ sudo pip3 install pybind11
$ cd sha3_test
$ make
$ ./sha3_test.py
```
Running this already for a few hours, with millions of random inputs (random length up to 1 MB) and as expected, all of them passed. Will as next step code-review the PR tomorrow.

**Comment by elichai** [comment]
I like how compact this is :)

**Comment by sipa** [comment]
Improved the tests and comments a bit.

@theStack Nice, that's pretty neat!

@elichai It was much more compact before unrolling, but I couldn't resist a 4.9x speedup with such a simple change (even though it really doesn't matter here...).

@practicalswift You're of course welcome to do any testing you like, but I don't think fuzzing for *robustness* is all that useful here. The KeccakF function has completely fixed code path and memory accesses, so it either fails for everything or for nothing. The only input-dependent behavior is in `SHA3_256::Write`, but even there the only thing that matters is the length of the inputs, which is well-covered by the included tests. It'd be slightly more useful to test that hashing the same data, chopped up in differently sized chunks, gives the same result.

**Review by vasild — APPROVED** [review]
ACK ab654c7

> It'd be slightly more useful to test that hashing the same data, chopped up in differently sized chunks, gives the same result.

I [tested](https://github.com/bitcoin/bitcoin/pull/19841#pullrequestreview-478717514) that as I ran the new code through the same tests as the existent SHA256 which uses [TestVector](https://github.com/bitcoin/bitcoin/blob/0a8aa62/src/test/crypto_tests.cpp#L27).

**Comment by elichai** [comment]
> @elichai It was much more compact before unrolling, but I couldn't resist a 4.9x speedup with such a simple change (even though it really doesn't matter here...).

haha, you could instead add `#pragma GCC unroll 5/24/25` :P

**Comment by sipa** [comment]
> haha, you could instead add #pragma unroll 5/24/25 :P

I tried that. Numbers I get:

|             ns/byte |              byte/s |    err% |     total | benchmark
|--------------------:|--------------------:|--------:|----------:|:----------
|               28.88 |       34,630,178.09 |    1.0% |      0.33 |  3f01ddb01bfffd49dfa131898d1c674ac5d0ac99 (before unrolling)
|                5.88 |      170,120,654.67 |    0.8% |      0.07 | ab654c7d587b33d62230394663020439f80cee28 (after unrolling)
|                5.60 |      178,667,398.49 |    0.4% |      0.06 | 3f01ddb01bfffd49dfa131898d1c674ac5d0ac99, but with pragmas to unroll everything in one round

So that means it's (on GCC 9.3.0, on x86_64 Linux) possible to get slightly better performance with forced unrolling, but also a lot more fragile (pragmas may work different across compilers and without the pragmas the code is a lot worse).

I prefer keeping the code as-is. It's still very readable (I think), is platform neutral, and has close to ideal performance.

**Comment by elichai** [comment]
> I prefer keeping the code as-is. It's still very readable (I think), is platform neutral, and has close to ideal performance.

Yeah it probably won't work on MSVC :/

**Comment by practicalswift** [comment]
ACK ab654c7d587b33d62230394663020439f80cee28 -- patch looks correct and no sanitizer complaints when doing some basic fuzz testing of the added code (remember: **don't trust: fuzz!**) :)

**Comment by laanwj** [comment]
Thanks @theStack. I have run your cross-verification for a while here as well, no errors came up.

I would prefer to keep the code as-is, with an explicit unroll. Even though a pragma would make the code shorter, it's non standard C++ functionality.

ACK ab654c7d587b33d62230394663020439f80cee28

**Pull request merged**
