### PR TITLE
Update doc/policy/README.md

### PR DESCRIPTION
**Pull request by djschnei21**
Include `-datacarriersize` in the examples because people are extremely confused about this...

### CODE REVIEW

**Review by luke-jr — APPROVED** [review]
utACK, but maybe we should just have a table with them all somewhere instead?

**Comment by glozow** [comment]
Agree with not keeping 2 separate lists. Maybe just say "see node relay options" in `-help`.

**Comment by fanquake** [comment]
Cherry-picked into #29235.

**Review by jonesk7734 — COMMENTED** [review]
Reviewed, and terms agreed to.

**Pull request closed without merging**
