### PR TITLE
rpc: Disallow gettxoutsetinfo queries for a specific block with `use_index=false`

### PR DESCRIPTION
**Pull request by mzumsande**
In the `gettxoutsetinfo` RPC, if we set `use_index` to false but specify `hash_or_height`, we currently hit a nonfatal error, e.g. `gettxoutsetinfo "muhash" "1" "false"` results in:
```
Internal bug detected: "!pindex || pindex->GetBlockHash() == view->GetBestBlock()"
rpc/blockchain.cpp:836 (GetUTXOStats) 
```
The failing check was added in [#24410](https://github.com/bitcoin/bitcoin/pull/24410/commits/664a14ba7ccb40aa82d35a59831acd35db1897a6), but the previous behavior, returning the specified height together with data corresponding to the tip's height, was very confusing too in my opinion.
Fix this by disallowing the interaction  of `use_index=false` and `hash_or_height` and add a RPC help example with `-named` because users might ask themselves how to use the `use_index` flag witout hitting an error.

An alternative way would be to allow the interaction if the specified `hash_or_height` happens to correspond to the tip (which should then also be applied to the `HASH_SERIALIZED` check before). If reviewers would prefer that, please say so.

### CODE REVIEW

**Review by shaavan — COMMENTED** [review]
Concept ACK

- I agree with allowing displaying an RPC error instead of an Internal bug error because:
    1. AFAIK. This will enable the incorrect command to fail faster
    2. This will allow users to understand better the problem's cause and how to solve it.

Now, as for the alternative that you suggested: 

> An alternative way would be to allow the interaction if the specified hash_or_height happens to correspond to the tip...


I want to explain why I think it is better not to switch to the alternative.

1. This will potentially increase the code complexity.
2. Running the command `bitcoin-cli -named `gettxoutsetinfo` hash_type='muhash' use_index='false'` prints the info for the current best block. So technically, the alternative is not needed.
3. Since it is explicitly mentioned in the `gettxoutsetinfo` help message, the `hash_or_height` option is available only with the **coinstatsindex**. So ideally, it shouldn't be allowed to provide hash_or_height value with `use_index=0`.

```
Arguments:
1. hash_type         (string, optional, default="hash_serialized_2") Which UTXO set hash should be calculated. Options: 'hash_serialized_2' (the legacy algorithm), 'muhash', 'none'.
2. hash_or_height    (string or numeric, optional) The block hash or height of the target height (only available with coinstatsindex).
3. use_index         (boolean, optional, default=true) Use coinstatsindex, if available.
```

However, not using the alternative makes the `gettxoutsetinfo` command quite verbose, as there is no way to make `use_index = false` without using the `--named` option.

**Screenshot:**

Screenshot from 2022-06-25 14-59-50


So I would suggest reordering the arguments of this RPC to 
```
1. `hash_type`
2. `use_index`
3. `hash_or_height`
```
Because, first, it would eliminate the need to use `--named` for specific cases, and second, this makes the ordering of argument logically sounder.

And I would also suggest mentioning in the description of `hash_or_height`, that not using this command would print info for the best block.

**Comment by mzumsande** [comment]
Thanks for the review!

> So I would suggest reordering the arguments of this RPC

That would be nice, but it would break compatibility with older versions, which I think should really be avoided unless absolutely necessary. For other RPCs, we sometimes even keep  dysfunctional dummy-arguments around to avoid this. (`prioritisetransaction`)

> And I would also suggest mentioning in the description of hash_or_height, that not using this command would print info for the best block.

I'll do this with my next push!

**Comment by Riahiamirreza** [comment]
Where the `use_index` and `hash_or_height` are given to the program? Are they api args? or should set while running `bitcoind`? I checked the api [docs](https://developer.bitcoin.org/reference/rpc/gettxoutsetinfo.html) but not found something useful.

**Comment by mzumsande** [comment]
> Where the `use_index` and `hash_or_height` are given to the program? Are they api args? or should be set while running `bitcoind`? I checked the api [docs](https://developer.bitcoin.org/reference/rpc/gettxoutsetinfo.html) but not found something useful.

You need to start bitcoind with the coinstatsindex to  reproduce this, e.g. `./bitcoind -signet -coinstatsindex`, and wait until the index is synced. After that, you can query `./bitcoin-cli -signet gettxoutsetinfo "muhash" "1" "false"`, which should give you this internal error on master.

Doing the same locally with -regtest instead of -signet works too, but then you need to mine a couple of blocks yourself (`./bitcoin-cli -regtest -generate 10` before querying `gettxoutsetinfo` ).

**Comment by mzumsande** [comment]
[2e9c043 ](https://github.com/bitcoin/bitcoin/commit/2e9c043cac4a309ff0a1bb3248b0b4f2a7843dd8)to [27c8056](https://github.com/bitcoin/bitcoin/commit/27c8056885b05bd25f540dbf6ede89230d43c7b9):
added explanation for the default of `hash_or_height` parameter (thanks @shaavan)

**Review by shaavan — APPROVED** [review]
ACK 27c8056885b05bd25f540dbf6ede89230d43c7b9

Changes since my last review:
- The help message for the default behavior of the `hash_or_height` argument has been added.

I was able to successfully run the `./bitcoin-cli -signet help gettxoutsetinfo` command, and verify the help message has been displayed correctly.

**Screenshot:**
image

**Comment by fjahr** [comment]
utACK 27c8056885b05bd25f540dbf6ede89230d43c7b9

**Review by fjahr — APPROVED** [review]

**Comment by dongcarl** [comment]
Concept ACK for fixing the internal error that's exposed to RPC

-----

In the longer term, I'd like to see `CreateUTXOSnapshot` use `kernel::ComputeUTXOStats` directly, and `GetUTXOStats` inlined into its only user `gettxoutsetinfo` and a lot of the if else checking can be removed.

**Pull request merged**
