### PR TITLE
doc: Revert translated string change, clarify wallet log messages

### PR DESCRIPTION
**Pull request by PierreRochard**
Fixes https://github.com/bitcoin/bitcoin/pull/12992 post-merge nits from @jnewbery

### CODE REVIEW

**Comment by jnewbery** [comment]
LGTM. Tested ACK c4a884d555e75cf43c695517f3f8344be177e5eb

**Comment by MarcoFalke** [comment]
utACK c4a884d555e75cf43c695517f3f8344be177e5eb

Can confirm that the only changes to translation strings are unrelated to this pull:

```
diff --git a/src/qt/bitcoinstrings.cpp b/src/qt/bitcoinstrings.cpp
index ab7e56a9da..de60b30dfe 100644
--- a/src/qt/bitcoinstrings.cpp
+++ b/src/qt/bitcoinstrings.cpp
@@ -40,6 +40,12 @@ QT_TRANSLATE_NOOP("bitcoin-core", ""
 "Fee estimation failed. Fallbackfee is disabled. Wait a few blocks or enable -"
 "fallbackfee."),
 QT_TRANSLATE_NOOP("bitcoin-core", ""
+"Group outputs by address, selecting all or none, instead of selecting on a "
+"per-output basis. Privacy is improved as an address is only used once "
+"(unless someone sends to it after spending from it), but may result in "
+"slightly higher fees as suboptimal coin selection may result due to the "
+"added limitation (default: %u)"),
+QT_TRANSLATE_NOOP("bitcoin-core", ""
 "Invalid amount for -maxtxfee=<amount>: '%s' (must be at least the minrelay "
 "fee of %s to prevent stuck transactions)"),
 QT_TRANSLATE_NOOP("bitcoin-core", ""
@@ -168,7 +174,7 @@ QT_TRANSLATE_NOOP("bitcoin-core", "Signing transaction failed"),
 QT_TRANSLATE_NOOP("bitcoin-core", "Specified -walletdir \"%s\" does not exist"),
 QT_TRANSLATE_NOOP("bitcoin-core", "Specified -walletdir \"%s\" is a relative path"),
 QT_TRANSLATE_NOOP("bitcoin-core", "Specified -walletdir \"%s\" is not a directory"),
-QT_TRANSLATE_NOOP("bitcoin-core", "Specified blocks directory \"%s\" does not exist.\n"),
+QT_TRANSLATE_NOOP("bitcoin-core", "Specified blocks directory \"%s\" does not exist."),
 QT_TRANSLATE_NOOP("bitcoin-core", "Starting network threads..."),
 QT_TRANSLATE_NOOP("bitcoin-core", "The source code is available from %s."),
 QT_TRANSLATE_NOOP("bitcoin-core", "The transaction amount is too small to pay the fee"),

**Comment by fanquake** [comment]
utACK c4a884d

**Review by kallewoof — COMMENTED** [review]
utACK c4a884d555e75cf43c695517f3f8344be177e5eb

**Pull request merged**
