### PR TITLE
Windows: Avoid launching as admin when NSIS installer ends.

### LINKED ISSUE #7990: Windows installer launches GUI as Admin
When installing the GUI with the Windows installer, there's a checkbox at the end of the process that launches the software. However, when the installer launches a process, it runs at the same Integrity Level (privilege) as the installer. As the installer is, well, installing software, it needs to run at the High (elevated/admin) privilege/Integrity Level, and hence the node/GUI will be launched at that same level. I've confirmed this using [Sysinternals Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx) -- launching Bitcoin Core from the Start menu results in an Integrity Level of Medium, as expected, while closing the installer without deselecting the checkbox results in the process being started at the High level.

A quick search does turn up ways to work around the issue (such as [this plugin](http://nsis.sourceforge.net/ShellExecAsUser_plug-in) in combination with [this trick](http://nsis.sourceforge.net/Run_an_application_shortcut_after_an_install)), but I wonder if we really need that checkbox there at all. I know nothing about NSIS and how easy that is (what a plugin is, what would be involved in using it, or what other ways there are to do the same thing, etc.), but it seems to me that if it's not trivial to fix this we may as well just drop the box altogether.

### PR DESCRIPTION
**Pull request by JeremyRand**
The Bitcoin Core NSIS script runs with elevated privileges.  Unfortunately, this means that it launches Bitcoin Core itself with elevated privileges when the user chooses to launch Bitcoin Core at the end of the installation procedure.  This PR works around the issue by having `explorer.exe` launch Bitcoin Core.  Seems to be a similar approach to what http://nsis.sourceforge.net/ShellExecAsUser_plug-in does, but without a plugin.

I've tested this with Sysinternals Process Explorer on Windows 10 32-bit.  I wouldn't expect any differences in behavior on other Windows releases, but if anyone would like to test on other Windows releases, feel free.

h/t to "UK" at https://mdb-blog.blogspot.se/2013/01/nsis-lunch-program-as-user-from-uac.html?showComment=1410158039989#c2463780017054126736 for the sample code.

Fixes #7990.

### CODE REVIEW

**Review by ken2812221 — APPROVED** [review]
Tested ACK 7d8a8cc

**Comment by fanquake** [comment]
@ken2812221 Could you provide the basic steps you used to test this, so anyone else can recreate on a Windows VM?

**Comment by ken2812221** [comment]
@fanquake I just add `wallet=C:\Windows\xxxx` to my config file.

if bitcoin core has higher privilege, it can successfully create the directory, otherwise it crash

**Comment by laanwj** [comment]
Concept ACK - would like to see some more tested ACKs.

**Comment by jonasschnelli** [comment]
Gitian build is here: https://bitcoin.jonasschnelli.ch/build/573

**Comment by fanquake** [comment]
I've tested this using the method @ken2812221 suggested. Basically create a bitcoin.conf with
```
wallet=C:\Windows\xxxx
```

If you then install 0.16.0, and choose to run at the end of the installation, Core will error on startup, because we can't specify a path as a wallet name.
error

```
2018-04-18 04:48:31 Using 4 threads for script verification
2018-04-18 04:48:31 scheduler thread start
2018-04-18 04:48:31 Using wallet directory C:\Users\User\AppData\Roaming\Bitcoin\wallets
2018-04-18 04:48:31 init message: Verifying wallet(s)...
2018-04-18 04:48:41 Shutdown: In progress...
2018-04-18 04:48:41 scheduler thread interrupt
2018-04-18 04:48:41 Shutdown: done
```

However if you then install the [gitian build](https://bitcoin.jonasschnelli.ch/build/573) provided by @jonasschnelli, and launch Core at the end of the installation we get an Exception. Looking at the debug, looks like we no longer have access to ```C:\Windows\```.
fatal exception


```
2018-04-18T04:40:39Z init message: Verifying wallet(s)...
2018-04-18T04:40:39Z Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)
2018-04-18T04:40:39Z Using wallet wallet.dat
2018-04-18T04:40:39Z 

************************
EXCEPTION: N5boost10filesystem16filesystem_errorE       
boost::filesystem::create_directory: Access is denied: "C:\Windows\xxxx"       
C:\Program Files\Bitcoin\bitcoin-qt.exe in Runaway exception   
```

**Comment by laanwj** [comment]
@fanquake Thanks for testing. To be clear: All in all that seems a positive result? I suppose you used `C:\windows` as a path that bitcoin core is supposed to not have access to?

**Comment by fanquake** [comment]
@laanwj Yes, I think it's a positive result. Core should not have access to write files into ```C:\Windows\```.

**Comment by laanwj** [comment]
Right - it's similar to `/usr/`. I've kind of forgot about windows things somewhat.
Looks good to me, then. Also added "to backport" as sane installer behavior is very important.

**Comment by Michagogo** [comment]
This may not be a good idea: https://mdb-blog.blogspot.com/2013/01/nsis-lunch-program-as-user-from-uac.html?showComment=1388694317801#c939517856791332836

**Comment by JeremyRand** [comment]
@Michagogo I'm not sure whom at Microsoft Ericlaw talked to (he doesn't give any citation), but Microsoft has [recommended](https://blogs.msdn.microsoft.com/oldnewthing/20131118-00/?p=2643) the approach of using `explorer.exe` for this.

**Comment by Michagogo** [comment]
I’m not sure if launching explorer.exe with the program as an argument is
exactly equivalent to what that page describes (calling various functions
directly).

**Comment by JeremyRand** [comment]
@Michagogo the Microsoft page I linked says:

> The solution here is to go back to Explorer and ask Explorer to launch the program for you. Since Explorer is running as the original unelevated user, the program (in this case, the Web browser) will run as Bob.

So while I haven't audited the Microsoft sample code to verify that it does that (Windows C API's aren't my specialty), I think it's reasonable to infer that the Microsoft sample code matches the Microsoft description (which matches what this PR does).

**Comment by Michagogo** [comment]
Windows C APIs aren’t my specialty either, so maybe someone with more
experience could weigh in, but that code definitely doesn’t just run
explorer.exe with an argument. Just by skimming it, it’s clear that it
somehow looks at the environment to get some kind of handle or something on
the running shell and call a function on that. That may, however, be
equivalent - I don’t have enough deep Windows knowledge to say for sure
what the difference is.

**Pull request merged**
