### PR TITLE
 [Qt] allow users to set -onion via GUI

### PR DESCRIPTION
**Pull request by Diapolo**
- also allow users to see, if the default proxy (-proxy) is used for IPv6
  and Onion
- based on #4871 (formerly #2575)

proxy

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Needs rebase or close due inactivity.

**Comment by Diapolo** [comment]
No, this needs review and help with https://github.com/bitcoin/bitcoin/pull/4871, which no one is interessted in :D.

**Comment by jonasschnelli** [comment]
Sorry. Your right. It's on top of #4871

**Comment by Diapolo** [comment]
Rebased to latest #4871 and fixed a small bug that was causing ``-onion`` to be missing in the options dialog, when the GUI setting was overridden.

**Comment by Diapolo** [comment]
Same here, this will be rebased after https://github.com/bitcoin/bitcoin/pull/6272 is merged.

**Comment by Diapolo** [comment]
Rebased and passing travis :).

**Comment by Diapolo** [comment]
@laanwj @jonasschnelli Mind taking a closer look now?

**Comment by Diapolo** [comment]
@jonasschnelli @laanwj This should be ready.

**Comment by jonasschnelli** [comment]
Gave it a short test.

Why can't i unselect/select the IPv4/IPv6/Tor checkboxes (i didn't start reading why in the PRs description because IMO this must be clear within the app). If it's just as a visual prove what networks are supported by the proxy, it should not use read-only checkboxes.

The new height of the settings window does somehow look strange on the other tabs.
Auto-Resizing like this (https://vid.me/F53C) would be a better approach (check: http://stackoverflow.com/questions/11441809/resize-window-using-qpropertyanimation).

IMO the autoresizing would be nice but should not hold this PR back.

**Comment by jonasschnelli** [comment]
bildschirmfoto 2015-07-21 um 21 28 22

**Comment by Diapolo** [comment]
@jonasschnelli I choose the read-only checkbox approach as that seemed easy to do. What elemet do you suggest? As you discovered the state is not changable via the boxes, they just give information.

The resize issue is a different one and as far as I understand the link you gave me, this is just for getting a nice and smooth animation, but I don't even know how to resize a window so that the contents and size are matching and that it looks good ;). IMHO our client suffers from these issue nearly everywhere.

**Comment by jgarzik** [comment]
ut ACK

Is this ready for merging?  Blockers appear to be resolved.

**Comment by jonasschnelli** [comment]
Readonly-Checkboxes as visual indicator for a available option (but while actually supporting no interaction) should be avoided. But i can address this in another upcoming PR after merging.

I would recommend to use the checkbox icon instead (https://github.com/bitcoin/bitcoin/blob/master/src/qt/res/icons/transaction2.png).

**Comment by Diapolo** [comment]
@jonasschnelli I'd love to get this in or you could just add a commit to it. But I'd love to move forward.

**Comment by jonasschnelli** [comment]
Doesn't compile at the moment because of the recent "emit" changes (https://github.com/bitcoin/bitcoin/pull/6433).

**Comment by Diapolo** [comment]
@jonasschnelli fixed the emit problem.

**Comment by jonasschnelli** [comment]
bildschirmfoto 2015-07-24 um 12 43 12

bildschirmfoto 2015-07-24 um 12 55 46


I think this looks better.
Commit: https://github.com/jonasschnelli/bitcoin/commit/3ae243422abfbdaa8c5a56ebdf86d4fedeaa467c

**Comment by laanwj** [comment]
@jonasschhnelli I like what you're trying to do, but I'm not sure it's better:
- The checkbox icon is always black, also in themes that themselves have a black background
- It doesn't fit in with the rest of the UI

**Comment by laanwj** [comment]
Going to merge this as-is for now. You can improve it later.

**Comment by jonasschnelli** [comment]
ACK.

**Pull request merged**
