### PR TITLE
scripts: Add trusted key for Samuel Dobson

### PR DESCRIPTION
**Pull request by laanwj**
Add trusted GPG key so that Samuel Dobson (MeshCollider), who is now wallet maintainer, can merge PRs.

### CODE REVIEW

**Comment by Sjors** [comment]
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

ACK 1ca0502

I signed his PGP key earlier this year.

Afaik he never signed a commit, but he did sign several Gitian
builds with this key.

-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEE7ZvfetalXiMuhFJCV/+b28wwEAkFAlwGiD8ACgkQV/+b28ww
EAnwNxAAuy6sHs6HUNT/TO6yv0tqKWTtBI8OP1yTAqdnM3XtV8UacC2KUi5/L3vq
VxaHZjtBNvlYO+kPXDsA6isOwgFta5qSwkqyF57zH6PmfdplEyWVDOyawYE8E2H5
4yPFDph4LVGIyD5IMys3l/HnZqZqBuQMTR5nu4Z7a/Z+6aaG9wZUpXg6eUXNbFw3
vv0wA2dISqChIXTRx54X4YiGtQ6LuQYRzi1sRiu8BU0jT6aIvwXJ3NcrIiHm5Ol9
yE5QB8Y/PfNEvkMYEBYNc3xAAD4FavApbF+9gm5ohCphc9+6eIR1jGnxenGHoAPY
P9SOwEdskzQfT5AJkprbKeTQAiLTuGr6r864hzBxV50N8bi5aNKUz72wC1rQQk+B
SibAwhepzpCh1wERSaV3eQDKABKsEW68waLKmlomBZXRMZSweMW+Q5T/0MnOatuz
Yob7k4oc04Cz4hKxr7wPsYMkYuMwUauczGzJggrxcL8JJTAr3N56tHv7KT88c9QW
/xhhoZDWzPZMOqSNZjzFcOM+HOP4f51Jv+VBnZiw1MBIb8wfGxSyEgU1ClZud8cT
XRqLOribWVvegfo4FlmYDFVkcSqpAdN+nnK+MaCQ8lJvf8Q2TcgrcwqgsmqLg5rJ
IK16vXIMbQrfIrjp5vioVGHlUNEjDMs2miwAnXWQRFro+ckZUS4=
=Morc
-----END PGP SIGNATURE-----
```

**Comment by laanwj** [comment]
Thanks for checking!
FWIW: we also refer to the key in https://github.com/bitcoin/bitcoin/blob/master/contrib/gitian-keys/keys.txt
He did sign some gitian builds.

**Comment by jonasschnelli** [comment]
ACK 1ca050254145ebbbbf5910bfee2e82a45e465ca1

**Comment by achow101** [comment]
ACK 1ca050254145ebbbbf5910bfee2e82a45e465ca1

**Comment by MarcoFalke** [comment]
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK 1ca050254145ebbbbf5910bfee2e82a45e465ca1
-----BEGIN PGP SIGNATURE-----

iQGcBAEBCgAGBQJcBqxkAAoJEM4rdWl+aaVIbp4L/jylpTOebL3Y1leEV5sID8fM
FcEDppmWQmQ3J0NtYSRXQ8bAgaYXBaRaKX+jhiuiDHNzPp/aTb8uJcndZUTulbIo
KuPdrVo0GwA58NgVVoBsTnHd76/znMLmUuWpWt/G04FhSytZwjMTaa6DSw3Pnpgo
MbHXOlAsbCRlBiLkd8roQLvdOeBlfrm/0+OrH7phQXsfry8UjULh9KRMqrxI3nc7
ztGLw6y0UG3JDWLaNp64qbuClFFSh+dROc/gRy6X7t2yU0kiixQ2Dn1Q4NLtKgxW
t2tI3RH5Iuot8QBM3bQ12pvZHoAxXpcSxDps7R2Yvs34MHMFU42taZFFUBzWa86R
YAIjj4mjweUlWkZdlzHSlMXBx1eFRdx5+ILqoueN6iB/2SYSSmXwIYK4Xir9Z3Vv
aeobImjCiATgoCmIRc5yk/5miBPzaEwgM+hArDunNTR4PDZho/rtqKwQ1V2DjR0A
QSHDyhvpOXLo46NriJFWoUExtwWJh61pb5t1lfBfXw==
=UCYU
-----END PGP SIGNATURE-----

**Comment by practicalswift** [comment]
Good news! 🎉 

The five trusted keys are now:

```
71A3… laanwj
133E… sipa
32EE… jonasschnelli
B8B3… MarcoFalke
CA03… MeshCollider
```

**Comment by MeshCollider** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

ACK 1ca050254145ebbbbf5910bfee2e82a45e465ca1
This is my (Samuel Dobson / MeshCollider)'s key
-----BEGIN PGP SIGNATURE-----

iQIcBAEBAgAGBQJcBtEKAAoJENMAEW4ch1o9S5YQAMIO2NlqsfGxdKUeu92PwkhS
gi0q1hUreynmHtdtL5WuKaHJhn0nxGIAybNa2pqILFO064LbV2zMHk+DOnj1vXFr
xVVIy0XtpTDsl1+/NVMwGJMVFAtjL5XSL+3+4za8vKcrEiw3dNQ5O4KMcJy3r5Ln
JYQMG1b/o+pwHkfKDUx9qY4kD4o+g7TXKreTKpiD+6Xt2cTjxVVNa+oR8aDUcxd5
5ErimZs8/jAwaacAb0YHYtpIY/ZvDU1Pi3zjci5EUfF/X1fFEaTnl66bBsh9nm8i
KzqnwDTsbC3ubG8JBkCvs0QUQphDWkOQ6+zOwDjXWtYaWnDvvy1Yp9ru5IYAmvUJ
yLVSDLARKhfuhDS4UwJj92+ipVR4LCH6Y2oZiZdQAEul2f8RvYKNdlXFLk6q1sa1
plIsXfqIlr7sKuxBxmPeH4UWOgr6ZEs3pMyGM0Fb4SomaCkRQbNnXs5Z8ZD14lCW
Jranjpko/+fB18y/nuUPtaWYzzr06ch71BleDON1rwzflryE7B0Ap0vZombwE2n2
NySalJenO1SizlFb+TCAC8lDHoLjHuORjV7qNYaOkvFw195ClTbS1bsRPlxhBop/
6BuHbF04GdlJCDyEz9gV+7qeZVKN6uybGGmu8DlkpHUX99RmAbcxKSKGCc8rugFm
LpefQ/qx5XcVuRQ46izd
=Qdr0
-----END PGP SIGNATURE-----

**Comment by MarcoFalke** [comment]
@MeshCollider Don't forget to set up the pre-push-hook https://github.com/bitcoin/bitcoin/tree/master/contrib/verify-commits#tooling-for-verification-of-pgp-signed-commits to avoid pushing non-githubmerge.py commits to master (like I did once).

**Pull request merged**
