### PR TITLE
[Qt] header group cleanup

### PR DESCRIPTION
**Pull request by Diapolo**
- seperate core from GUI headers where this was missing
- remove an unneeded new-line

### CODE REVIEW

**Comment by laanwj** [comment]
Does this solve all header group deviations in the qt code? e.g. if we're going to do this, make sure to do it all in one go.

**Comment by Diapolo** [comment]
I have no more changes to add currently for the Qt codebase.

**Comment by fanquake** [comment]
You should probably be sending this to theuni's trival-next branch.

**Comment by Diapolo** [comment]
@theuni Can you pick this up? Seems it won't get merged fast anyway.

**Comment by theuni** [comment]
@Diapolo Got it, thanks for the ping.

**Pull request closed without merging**
