### PR TITLE
doc: Fix typos

### PR DESCRIPTION
**Pull request by omahs**
Fix: typos

### CODE REVIEW

**Comment by jonatack** [comment]
Changes look correct, mind also fixing these two in the same commit?

```
$ test/lint/lint-spelling.py 
src/net_processing.cpp:2717: minumum ==> minimum
src/net_processing.cpp:3904: mimimum ==> minimum
```

**Comment by omahs** [comment]
Just added those 👌  @jonatack

**Comment by jonatack** [comment]
Thanks -- it might be a  good idea [squash your commits](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#squashing-commits), as the diff is trivial.

**Comment by omahs** [comment]
@jonatack Sure!, just did

**Review by aureleoules — APPROVED** [review]
ACK 180eac0f73b7d96861f9626ebb701d9a46585a5b

The commit description is duplicated 3 times though:

> Fix: typos
> Fix: typos
> Fix: typos

**Comment by fanquake** [comment]
This was merged.

**Pull request closed without merging**
