### PR TITLE
Remove unused include in hash.cpp

### PR DESCRIPTION
**Pull request by kallewoof**

### CODE REVIEW

**Comment by sipa** [comment]
Please don't mark this as trivial (it's changing the code being compiled), but otherwise obvious ACK.

**Review by jonasschnelli — APPROVED** [review]
utACK c1e5e27e7a612703f7351f8fc9ce47be669d93ca

**Comment by kallewoof** [comment]
> Please don't mark this as trivial (it's changing the code being compiled), but otherwise obvious ACK.

You could argue that it doesn't, actually, but I'll keep that in mind.

**Comment by laanwj** [comment]
> You could argue that it doesn't, actually, but I'll keep that in mind.

One way to find out for sure: compare executables with https://github.com/bitcoin-core/bitcoin-maintainer-tools/blob/master/build-for-compare.py.
(though I don't think this argument is worth it, utACK anyhow, please update the commit message too)

**Comment by practicalswift** [comment]
ACK c1e5e27e7a612703f7351f8fc9ce47be669d93ca

**Comment by kallewoof** [comment]
Removed "[Trivial]" from commit message.

**Comment by promag** [comment]
utACK 3f09e03.

**Comment by MarcoFalke** [comment]
Tend to NACK here, since a related pull was just merged: #10574 and I fail to see why this change wasn't included there. I'd rather avoid another upcoming wave of commits with little value compared to the review it has to go through.

I am fine if you improve the travis check (#11878) instead.


In case my NACK is invalid, binary diff:
```diff
<   3554a6:	mov    $0x6b,%edx
---
>   3554a6:	mov    $0x6a,%edx
```

utACK 3f09e03e0f2ddbcd7ccaa9d21062be97dab2883a

**Comment by kallewoof** [comment]
@MarcoFalke I don't see why the other merge is related, and I don't think this commit has little value. Removing redundant/unused includes is quite beneficial in many cases. And one-liners are trivial to review.

The duplicate includes PR you pointed to seems slightly unrelated. This isn't a duplicate include, this is an unused include. Nowhere in the `hash.cpp` code does it use anything from `pubkey.h`. It may be possible to use static analysers to detect that sort of thing, but it smells like something that would give false positives occasionally.

**Review by dcousens — APPROVED** [review]

**Comment by MarcoFalke** [comment]
@kallewoof Jup, you are right.

**Pull request merged**
