### PR TITLE
assumeutxo: Add mainnet chainparams for block 830000

### PR DESCRIPTION
**Pull request by fjahr**
This seems to have fallen a bit by the wayside (or I missed the conversation) but I don't see a blocker to not have them. I will share a link to the file shortly txoutsetfile.

### CODE REVIEW

**Comment by fjahr** [comment]
Hm, moving to draft since there seems to be an open question if we want to wait for #26045.

**Comment by fanquake** [comment]
> Hm, moving to draft since there seems to be an open question if we want to wait for https://github.com/bitcoin/bitcoin/pull/26045.

We also want to wait for the rest of the bugfixes. i.e #29519. It's too late for this PR to be going into 27.x.

**Comment by fanquake** [comment]
Just realised this is also a duplicate of #28553. So closing this.

**Review by mzumsande — COMMENTED** [review]
I think the biggest issue the open question about distribution.
Would it be ok to just add an entry to chainparams and let the wider space figure it out (maybe someone out there will put the utxo set dump on a website or start a torrent)? Or should we come up with some kind of distribution mechanism _before_ that?

**Pull request closed without merging**
