### PR TITLE
RFC: depends: add release type to CMake builds

### PR DESCRIPTION
**Pull request by theuni**
RFC because I'm not sure if this is the right thing to do in combination with our CFLAGS/CXXFLAGS/etc env overrides.

I believe it was suggested by laanwj at some point.

### CODE REVIEW

**Comment by theuni** [comment]
Ping @hebasto

**Comment by theuni** [comment]
Right, but a few more things to consider:

An upstream build could be [following the docs](https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html#build-configurations) and doing something like:
```cmake
# Works correctly for both single and multi-config generators
target_compile_definitions(exe1 PRIVATE
  $<$<CONFIG:Debug>:DEBUG_BUILD>
)
```
In this case, we wouldn't currently pick up the extra debug opts.

The other thing to consider that is that we could be using
`CMAKE_<LANG>_FLAGS_<CONFIG>` for these options rather than CFLAGS/CXXFLAGS, potentially overriding the defaults you mentioned above but still being explicit about the build type.

Note that I don't necessarily believe these arguments and don't feel strongly either way, I just wanted to raise the discussion.

**Comment by laanwj** [comment]
i think `-O2 -g` (RelWIthDebInfo) for the release makes sense, it means that the distributed binary will be optimized, but still get (as far as possible) descriptive debug information such as line numbers and symbols in case it's necessary for troubleshooting, getting a traceback, figuring out where some crash address comes from, and so on.

**Comment by fanquake** [comment]
This "seems" like the right thing to do, but I'm also not sure. Could you rebase here, to incorporate other recent CMake changes, and so it's easier to test?

**Comment by fanquake** [comment]
We seem to have gravitated towards using `DCMAKE_BUILD_TYPE=None` + our flags for CMake packages in depends, (except for libevent), so maybe that is the best thing to do here, for now?

**Comment by hebasto** [comment]
> We seem to have gravitated towards using `DCMAKE_BUILD_TYPE=None` + our flags for CMake packages in depends, (except for libevent), so maybe that is the best thing to do here, for now?

I think this approach is quite straightforward and gives us full control on optimization/debug flags.

**Comment by fanquake** [comment]
To be clear, I was not saying to not make this change, but we could set the `None` build type globally in both cases.

**Pull request closed without merging**
