### PR TITLE
build: Drop unneeded macOS framework dependencies

### PR DESCRIPTION
**Pull request by hebasto**
Bitcoin Core codebase does not contain direct dependencies on the `ApplicationServices` and `IOKit` frameworks.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
utACK ec4a46dd9c158e1a0de144e9abb260da941aa702

**Comment by practicalswift** [comment]
cr ACK ec4a46dd9c158e1a0de144e9abb260da941aa702: patch looks correct!

Thanks for removing unused old cruft!

**Review by promag — COMMENTED** [review]
Tested ACK ec4a46dd9c158e1a0de144e9abb260da941aa702 (not depends build).

**Comment by fanquake** [comment]
In future it would be good if PRs like this had slightly more informative PR descriptions and commit messages.

> Bitcoin Core codebase does not contain direct dependencies on the ApplicationServices and IOKit frameworks.

Our C++ code might not contain direct dependencies on these frameworks, but that's not really the point of these checks. We need to test linking against some frameworks, and adding them to `QT_LIBS` if successful, so that when we try and link against `-lqcocoa`, it will work. i.e in #19716 I've actually [added additional framework checks (while removing IOKit)](https://github.com/bitcoin/bitcoin/pull/19716/commits/2cf81481acd59cbe8e32bd52bfb63b80f3c5e302#diff-a8347c206479f65144c2d8ab6188c4d5324597d333facaee47f95215015c3ca0R133-R135), as without them, the `-qcocoa` static plugin check would fail. 

For example, if with that branch, you drop off the link check for `-framework Carbon`, when you configure you'll see:
```bash
checking for static Qt plugins: -lqminimal... yes
checking whether the linker accepts -framework QuartzCore... yes
checking whether the linker accepts -framework IOSurface... yes
checking for static Qt plugins: -lqcocoa... no
configure: WARNING: Could not resolve: -lqcocoa; bitcoin-qt frontend will not be built

# config.log
Undefined symbols for architecture x86_64:
  "_kTISPropertyInputSourceLanguages", referenced from:
      QCocoaInputContext::updateLocale() in libqcocoa.a(qcocoainputcontext.o)
  "_TISCopyInputMethodKeyboardLayoutOverride", referenced from:
      QCocoaKeyMapper::updateKeyboard() in libqcocoa.a(qcocoakeymapper.o)
  "_GetCurrentKeyModifiers", referenced from:
      QCocoaKeyMapper::queryKeyboardModifiers() in libqcocoa.a(qcocoakeymapper.o)
```
as the linker can't resolve the symbols from the Carbon framework. This means that we won't build `bitcoin-qt`.

Also, the commit messages say "uneeded X framework dependency". However the macOS `bitcoin-qt` binaries we release do have a dependency on the IOKit and ApplicationServices frameworks (among many others).

I do agree that some of these checks are a bit arbitrary and there is opportunity to better document this behaviour.

**Pull request merged**
