### PR TITLE
Refactor: Create CCoinsViewEfficient interface for CCoinsViewCache

### PR DESCRIPTION
**Pull request by jtimon**
To move AreInputsStandard() and its consensus homologous to policy.o and consensus.o respectively without making those modules dependent on CCoinsModifier nor CCoinsViewCache, we need an interface that doesn't implement the method `CCoins* AccessCoins(const uint256 &txid)`. This interface doesn't need several other methods from CCoinsViewCache.
You can see some code using this change at #5697

### CODE REVIEW

**Comment by theuni** [comment]
As discussed on IRC. The first commit (making CCoinsView an interface class and creating CCoinsViewDummy to reimplement the current CCoinsView) is confusing, and really doesn't add any functionality. I'd prefer to skip that.

**Comment by jtimon** [comment]
I assume you're talking about HaveInputs(), GetValueIn(), GetPriority() and GetOutputFor()
Do we want those to be virtual?
Abstract classes often have methods implemented that use pure virtual methods that the child classes must implement like in here.
Are we expecting them to be reimplemented by child classes?

**Comment by theuni** [comment]
No, I just meant that the classes with virtual functions need virtual destructors.

**Comment by jtimon** [comment]
Nits resolved.

**Comment by sipa** [comment]
I would prefer moving GetOutputFor, GetPriority, GetValueIn, and HaveInputs to become validation/policy related utiliyu functions in main, avoiding the issue altogether.

**Comment by jtimon** [comment]
haveinputs is used in consensus (see https://github.com/jtimon/bitcoin/commit/0ac0610bf054aadc621201f79432e7559aea2cf2). GetValueIn (which uses GetOutputFor) could be modified to avoid some code duplication within consensus.
GetPriority could probably be moved to policy, I'm just not there yet.
In any case, this change doesn't prevent future changes in that direction.

**Comment by sipa** [comment]
Ok, that can happen independently if it doesn't solve any controversy. I just don't think GetOutputFor, GetPriority, GetValueIn and HaveInputs belong in CCoins (despite me being the one who put them there).

**Comment by sipa** [comment]
untested ACK, but verified b627d9abbe25a11ffca02ef1f3ab312575e5e450 as moveonly.

**Comment by theuni** [comment]
utACK

**Comment by jtimon** [comment]
Updated doing the includes better (not inclding coins.h nor coinscache.h from main.h), after doing that it needed rebase, so I rebased it. The non-includes code remains the same.

**Comment by jtimon** [comment]
mhmm, @theuni for some reason my last push didn't trigger travis, can you look at it?

**Comment by jtimon** [comment]
Needed rebase.

**Comment by jtimon** [comment]
I'm having second thoughts about this, closing for now.

**Pull request closed without merging**
