### PR TITLE
newcomer can think bitcoincore.org is Bitcoin homepage.

### PR DESCRIPTION
**Pull request by vlamer**
i dont i am fooled,maybe this just what i think..
newcomer can think bitcoincore.org is Bitcoin.

### CODE REVIEW

**Comment by jmcorgan** [comment]
NACK

**Comment by cdecker** [comment]
NACK, this is the Bitcoin Core client. bitcoin.org is purposefully client-agnostic.

**Comment by vlamer** [comment]
@cdecker Why do you use the word agnostic? which I think is not a rejection of the earlier,.

**Comment by achow101** [comment]
Actually, I think it would be better if the repo and the organization was renamed to bitcoin-core to continue the decoupling of Bitcoin Core away from being the official Bitcoin in general like what they are trying to do with moving Bitcoin core to bitcoincore.org.

**Comment by laanwj** [comment]
A newcomer will probably end up on bitcoin.org, or one of the other introductory sites. It's unlikely their first experience with bitcoin will be our README.md file.

In any case that file introduces our project, not bitcoin in general.

> Actually, I think it would be better if the repo and the organization was renamed to bitcoin-core to continue the decoupling of Bitcoin Core away from being the official Bitcoin in general like what they are trying to do with moving Bitcoin core to bitcoincore.org.

Yes, I'd like to do Bitcoin Core development under the bitcoin-core organization instead. However, a ton of links would have to be updated, which is the reason such a move hasn't been done yet.

**Comment by luke-jr** [comment]
@vlamer Note bitcoin.org is *also* not Bitcoin's homepage. Bitcoin is a decentralised project; it does not have anything official anywhere.

**Pull request closed without merging**
