### PR TITLE
build: Require C++17 compiler

### PR DESCRIPTION
**Pull request by maflcko**
Developers have been compiling with C++17 for a few months now (fuzz tests and the msvc build have it even enabled by default). According to #16684, the 22.0 release shall be compiled with C++17 enabled.

This only sets the build flag, any other changes need more discussion and can be done later.

### CODE REVIEW

**Comment by jonatack** [comment]
Concept ACK

**Comment by theStack** [comment]
Concept ACK

**Comment by laanwj** [comment]
ACK fae854da2fd8a45862e5169b698bf37a5fc57592 if it passes CI

**Comment by jnewbery** [comment]
Works for me.

utACK fae854da2fd8a45862e5169b698bf37a5fc57592

**Comment by practicalswift** [comment]
ACK fae854da2fd8a45862e5169b698bf37a5fc57592 assuming CI is happily green

**Comment by elichai** [comment]
utACK fac71987281077aed7f79dce99f4eb3e8a91916a

**Review by hebasto — APPROVED** [review]
ACK fac71987281077aed7f79dce99f4eb3e8a91916a, I've locally compiled on ARM 32bit SBC without GUI.

**Comment by MarcoFalke** [comment]
(ci green now)

**Review by fanquake — APPROVED** [review]
ACK fac71987281077aed7f79dce99f4eb3e8a91916a

**Comment by jonasschnelli** [comment]
Bitcoinbuilds is failing since this (ubuntu 18.04, clang-8, native qt/libs)

`SUMMARY: UndefinedBehaviorSanitizer: unsigned-integer-overflow /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/basic_string.tcc:1271:25 in`
https://bitcoinbuilds.org/index.php?ansilog=cde36fc5-66ef-4f85-a6c2-c7efb509bc01.log#l1987

**Comment by MarcoFalke** [comment]
Options:

* Use focal (like our ci configs)
* Use a newer compiler (not tested) g++-8 or clang++-10
* Add a suppression
* Something else?

**Comment by practicalswift** [comment]
I suggest adding a suppression since this isn't in our code.

**Comment by sipa** [comment]
unsigned integer overflow is not UB. It's just enabled because it is a red flag - but in standard libraries I think we can assume this is fine.

**Pull request merged**
