### PR TITLE
banman: Limit resources consumed by misbehaving node deprioitisation

### PR DESCRIPTION
**Pull request by luke-jr**
Potential alternative to #19219 that keeps the current semantics at the cost of more memory usage.

1. Single-address bans are moved to a dedicated std::map to avoid iteration.
2. Misbehaving "ban" entries are limited to 50k using a circular buffer.
3. Bugfix: Manual bans can override misbehaving discouragement, even for a shorter period of time.

I'm not sure if the tradeoffs justify this approach.

Looking for concept ACK/NACK, as well as code review (will probably use this for at least Knots 0.20.0 temporarily).

### CODE REVIEW

**Comment by jonatack** [comment]
Reviewed #19219 today, so with it fresh in mind will have a look at this version now.

**Review by jonatack — COMMENTED** [review]
Concept and light code review ACK with builds/tests ran. Good to see a unit test. This maintains the current interface/semantics with a bit more code complexity, more memory (4 MiB or more vs 0.5 MiB for the rolling bloom filter), but can erase from the set with fairly fast O(log(n)) lookups.

**Comment by TheBlueMatt** [comment]
Concept NACK - #19219 is essentially the current semantics with a node count limit, I don't see any reason to use more memory for a similar thing, and I dont think it makes sense to go back to treating them as an actual ban (though I dont think this does that, either, just noting).

**Comment by luke-jr** [comment]
@TheBlueMatt By "current semantics", in particular I mean being able to list and remove entries, and a reliable 24 hour expiration.

**Comment by luke-jr** [comment]
Also added a fix for a bug in the current code: Now manual bans take priority over misbehaving discouragement, regardless of expiry times.

**Comment by luke-jr** [comment]
#19219 was merged, so this is no longer applicable

**Pull request closed without merging**
