### PR TITLE
qt: Allow horizontal slider in debugwindow peers tab to autosize display

### PR DESCRIPTION
**Pull request by Saibato**
When fiddling around  with new node flags other than the usual. 
  
Not all possible node flag strings i.e. UNKNOWN where 
visible in peers details tab.
Since v18.2 fixed size was set to 300 and sliding is thereby limited. 

A fix on my old linux cruft and small screen was to set  minimumSize width to -1 or 0.
Qt the will then autosize the slider to the max string length.
 
Thereby i had full display of all flags inclusive sliding without to fullscreen the window.  

Not sure if this is even an issue for those who can afford big screens or high res macs?
Feedback welcome.

### CODE REVIEW

**Comment by promag** [comment]
@Saibato mind opening this PR in https://github.com/bitcoin-core/gui, which is where GUI changes should be made.

**Comment by fanquake** [comment]
Moved too: https://github.com/bitcoin-core/gui/pull/6.

**Comment by Saibato** [comment]
> Moved too: [bitcoin-core/gui#6](https://github.com/bitcoin-core/gui/pull/6).

Move Done:
BTW: should i file a tracking issue here, since at some point even a big screen can not display all 
flags at some point with the fixed 300 size?

**Comment by hebasto** [comment]
> > Moved too: [bitcoin-core/gui#6](https://github.com/bitcoin-core/gui/pull/6).
> 
> Move Done:
> BTW: should i file a tracking issue here, since at some point even a big screen can not display all
> flags at some point with the fixed 300 size?

The GUI-related issues also should filed in https://github.com/bitcoin-core/gui

In this particular case, the understandable pr description with screenshots could be sufficient, imo.

**Pull request closed without merging**
