### PR TITLE
Coin Control: Use U+2248 "ALMOST EQUAL TO" rather than a simple tilde

### PR DESCRIPTION
**Pull request by luke-jr**
The tilde appears identical to a negative sign for me:

This changes it to something more obvious:

### CODE REVIEW

**Comment by gmaxwell** [comment]
I like this, in that even if it fails to display correctly you'll just get a box or a missing symbol or and equals sign; and all are much better failure modes than something that looks like a minus sign.

But I am not a GUI wizard.

**Comment by Michagogo** [comment]
Is falling back to = something that might happen? Also, we need to check the various platforms' default fonts (OS X 10.10, OS X <10.10, Win7, Win8, maybe Unity default, possibly others?) to see if this looks right.

**Comment by gmaxwell** [comment]
@Michagogo falling back? I don't think so... being visually indistinguishable to? probably, but thats not so severe a problem as the 'negative' values.

**Comment by jonasschnelli** [comment]
OSX 10.10
Before:
bildschirmfoto 2015-01-13 um 08 57 07

After:
bildschirmfoto 2015-01-13 um 08 56 15

Win7:
bildschirmfoto 2015-01-13 um 09 01 10

Are there any OS without correct default font utf8 support with a mentionable amount of market share?

Tested ACK.

**Comment by jonasschnelli** [comment]
Just another thought:

why not `s/~/aprox.`?

**Comment by Michagogo** [comment]
May want to also find someone on Win8+ and an earlier OS X, since I'm
pretty sure 10.10 changed the system font.

**Comment by laanwj** [comment]
@zander `\u` is c++11 so we can't use it yet. The current formulation makes no assumption about the compiler, and just creates a UTF-8 string in bytes form. The end-result of `\u` in memory would be the same.

As for the client we explicitly force all string converstions to be UTF-8 at the start of the program (which is the default for Qt5 higher):
```
#if QT_VERSION < 0x050000
    // Internal string conversion is all UTF-8
    QTextCodec::setCodecForTr(QTextCodec::codecForName("UTF-8"));
    QTextCodec::setCodecForCStrings(QTextCodec::codecForTr());
#endif
```
That said, QChar(0x2243) looks a bit more readable so I'd prefer that.

**Comment by Diapolo** [comment]
utACK

**Comment by laanwj** [comment]
@diapolo it'd help moving this forward if you test on windows

**Comment by Diapolo** [comment]
@laanwj Done, looks good. Tested ACK! Btw. can you help me with pushing the payment request unit tests?

**Comment by Michagogo** [comment]
Looks like on Windows 7, it does show properly (0.10.0rc3 with this cherry-picked on top):

image

**Comment by theuni** [comment]
Someone mind checking this in some of the more difficult languages? I believe traditional chinese is one that usually ends up causing us trouble with exotic chars like these.

**Comment by Michagogo** [comment]
Broken in zh_CN.
image

**Comment by Michagogo** [comment]
Looks fine in zh_CN on Windows 7:
image

**Comment by theuni** [comment]
@Michagogo thanks for testing.

**Comment by Michagogo** [comment]
Should still be checked on Ubuntu and the various Linux environments, though.

**Comment by jonasschnelli** [comment]
I did test on OSX10.10 and 10.9 (comparable to Win8 and Win7 in case of actuality):
See osx10.10 screenshot above and here also comes the 10.9 screenshot:

bildschirmfoto 2015-01-13 um 21 45 42

**Comment by theuni** [comment]
Verified looks ok in Ubuntu with qt4 and qt5. Kde/kwin.

**Comment by Michagogo** [comment]
@theuni Uh, I thought Ubuntu is Unity?

**Comment by theuni** [comment]
Only by default.

**Comment by jonasschnelli** [comment]
We should also test this on OSX over a gitian build.

**Comment by laanwj** [comment]
@jonasschnelli Right - let's postpone this until the MacOSX unicode issues are fixed.

**Comment by jonasschnelli** [comment]
Prebuilt (gitian) binaries for testing are here: https://bitcoin.jonasschnelli.ch/pulls/5651/

**Comment by jonasschnelli** [comment]
Tested over gitian on OSX and windows.

ACK

**Pull request merged**
