### PR TITLE
util: Add missing headers to util/fees.cpp

### PR DESCRIPTION
**Pull request by hebasto**

### CODE REVIEW

**Comment by hebasto** [comment]
ping @jnewbery

**Comment by laanwj** [comment]
code review ACK b1315241375211563e9ec00391c4ac5310e1146f

**Comment by MarcoFalke** [comment]
ACK b131524

**Comment by jnewbery** [comment]
ACK b1315241375211563e9ec00391c4ac5310e1146f

**Comment by luke-jr** [comment]
Should be backported to 0.19?

**Comment by fanquake** [comment]
> Should be backported to 0.19?

Backported in #17858.

**Pull request merged**
