### PR TITLE
doc: Fix incorrect sendmany RPC doc

### PR DESCRIPTION
**Pull request by maflcko**
This enables the skipped type check for `sendmany` and fixes the resulting error.

Also, there is an unrelated test-only commit.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Rendered diff:

```diff
diff --git a/sendmany b/sendmany
index 45d946d..774b5db 100644
--- a/sendmany
+++ b/sendmany
@@ -1,10 +1,10 @@
-sendmany "" {"address":amount,...} ( minconf "comment" ["address",...] replaceable conf_target "estimate_mode" fee_rate verbose )
+sendmany ( "" ) {"address":amount,...} ( minconf "comment" ["address",...] replaceable conf_target "estimate_mode" fee_rate verbose )
 
 Send multiple times. Amounts are double-precision floating point numbers.
 Requires wallet passphrase to be set with walletpassphrase call if wallet is encrypted.
 
 Arguments:
-1. dummy                     (string, required) Must be set to "" for backwards compatibility.
+1. dummy                     (string, optional, default="\"\"") Must be set to "" for backwards compatibility.
 2. amounts                   (json object, required) The addresses and amounts
      {
        "address": amount,    (numeric or string, required) The bitcoin address is the key, the numeric amount (can be string) in BTC is the value

**Comment by MarcoFalke** [comment]
Reworked approach, changed title and made it more clear that this is a behaviour change. Rendered diff above should still be applicable.

**Comment by MarcoFalke** [comment]
Do I need to rework this again in light of https://github.com/bitcoin/bitcoin/pull/19262 ?

**Comment by MarcoFalke** [comment]
Completely reworked this, since the check has been merged, to only fixup the RPC doc

**Review by fanquake — APPROVED** [review]
ACK fa95f2033a26fb18914c2aa5e5e18650d32e6e4b

**Pull request merged**
