### PR TITLE
wallet, refactor: Include headers instead of function declarations

### PR DESCRIPTION
**Pull request by hebasto**
This PR is a #19077 follow up: https://github.com/bitcoin/bitcoin/pull/19077#discussion_r502882199

### CODE REVIEW

**Comment by practicalswift** [comment]
ACK 1d5ac6062603e8ed494c8edacbdd314377e83627

**Review by theStack — APPROVED** [review]
ACK 1d5ac6062603e8ed494c8edacbdd314377e83627 📄

**Review by mjdietzx — APPROVED** [review]
ACK 1d5ac6062603e8ed494c8edacbdd314377e83627

**Comment by hebasto** [comment]
Rebased 1d5ac6062603e8ed494c8edacbdd314377e83627 -> e32fb745918604798a25abc8a1f154c742320f83 ([pr20206.01](https://github.com/hebasto/bitcoin/commits/pr20206.01) -> [pr20206.02](https://github.com/hebasto/bitcoin/commits/pr20206.02)) due to the conflict with #20156.

**Comment by hebasto** [comment]
Rebased e32fb745918604798a25abc8a1f154c742320f83 -> 9dbdb2729126d06268b22653b948daf98a435e59 ([pr20206.02](https://github.com/hebasto/bitcoin/commits/pr20206.02) -> [pr20206.03](https://github.com/hebasto/bitcoin/commits/pr20206.03)) due to the conflict with #20202.

**Comment by hebasto** [comment]
This change is outdated since #20275 has been merged.

Closing.

**Pull request closed without merging**
