### PR TITLE
qt: askpassphrasedialog: Clear pass fields on accept

### PR DESCRIPTION
**Pull request by ghost**
This is usability improvement in a case if user gets re-asked
passphrase. (e.g. made a typo)

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Looks good. Thanks.
utACK 02ce2a3ca773e2d10ff37ecf50d15c71113f3335

**Comment by Tyler-Hardin** [comment]
I kinda doubt the secure clear is useful. Wouldn't the QString that already contains the password be untouched and just deallocated?

**Comment by Tyler-Hardin** [comment]
Actually, QLineEdit::text isn't a const reference (most Qt properties are not writable), so you can zero the memory yourself. I would recommend directly zeroing the existing QString if you really want attempt to clear it securely.

**Comment by jonasschnelli** [comment]
Cleansing the memory can help. But I think there are various cases where the UI framework leaves uncleaned copies somewhere in the ram.
I think the main use advantage of this PR is: https://github.com/bitcoin/bitcoin/pull/8073/files#diff-defede4762fd62a298bd8a0936cd3ed0R103 (the clear in AskPassphraseDialog::accept()).

**Comment by arowser** [comment]
Can one of the admins verify this patch?

**Pull request merged**
