### PR TITLE
build: Update `qt` package up to 5.15.11

### PR DESCRIPTION
**Pull request by hebasto**
In the light of https://github.com/bitcoin/bitcoin/pull/28622, we probably have to patch Qt. It seems reasonable to update it up to the latest available version before doing that.

### CODE REVIEW

**Comment by fanquake** [comment]
Concept ACK. Lets get this merged, and then figure out what the issue in #28622. That should unblock C++20.

**Comment by hebasto** [comment]
Guix builds:
```
x86_64
f3d6ac10842f48884b36d704cc4303ee001197a5c39f7d65116324ab919f4497  guix-build-8047bb6feaa9/output/aarch64-linux-gnu/SHA256SUMS.part
a651622edbca1c9badf7f4018296639929f9553c257bc2cdb464c240e5ab29d2  guix-build-8047bb6feaa9/output/aarch64-linux-gnu/bitcoin-8047bb6feaa9-aarch64-linux-gnu-debug.tar.gz
6ad8004e3739c51380032a411f43054a7768188033bcd9534ebb165b1755819d  guix-build-8047bb6feaa9/output/aarch64-linux-gnu/bitcoin-8047bb6feaa9-aarch64-linux-gnu.tar.gz
aaecf84b3fabcec61612534b302112950cd5254522397f8967538ebb29405561  guix-build-8047bb6feaa9/output/arm-linux-gnueabihf/SHA256SUMS.part
af1cc0dd1e6196cd49fbf0a4b851551314cfd721efa6fe2e0c348ffb5e7e2023  guix-build-8047bb6feaa9/output/arm-linux-gnueabihf/bitcoin-8047bb6feaa9-arm-linux-gnueabihf-debug.tar.gz
0a887a820c9e13e2cc2b1b61072252d5b48cceb631b3af687111abd7359c7bc4  guix-build-8047bb6feaa9/output/arm-linux-gnueabihf/bitcoin-8047bb6feaa9-arm-linux-gnueabihf.tar.gz
b6943c5b1cf963e78f67a3251855e5d516315f32e1d49a487031352929bffaf0  guix-build-8047bb6feaa9/output/arm64-apple-darwin/SHA256SUMS.part
28913ce170b61922b5be6f77f51d2ce35eb5962017b29351e4bc091a74aefe6f  guix-build-8047bb6feaa9/output/arm64-apple-darwin/bitcoin-8047bb6feaa9-arm64-apple-darwin-unsigned.tar.gz
cb30060d8a1495d66107f43714e47cba9597a2a8d0afe9eae32cf1762311f2b5  guix-build-8047bb6feaa9/output/arm64-apple-darwin/bitcoin-8047bb6feaa9-arm64-apple-darwin-unsigned.zip
810d2c6317b5db2f1be16de9af73ef109b0627ce37a2061ce101799b2263f4d5  guix-build-8047bb6feaa9/output/arm64-apple-darwin/bitcoin-8047bb6feaa9-arm64-apple-darwin.tar.gz
13a5fa14a91d95b66c78c405f7deca14db148f1d6b86a7659da097d1cbcd430c  guix-build-8047bb6feaa9/output/dist-archive/bitcoin-8047bb6feaa9.tar.gz
949b7ac900f946d974dfc1cadede95738f2077e58976fc3bf1375a45ba45d6d8  guix-build-8047bb6feaa9/output/powerpc64-linux-gnu/SHA256SUMS.part
af1f890255e152434f49e7d6973a0c8d95b71f04de3d55737a0c7429d3aa36a9  guix-build-8047bb6feaa9/output/powerpc64-linux-gnu/bitcoin-8047bb6feaa9-powerpc64-linux-gnu-debug.tar.gz
bdddf864f0d9829f749ea9eea2197b58f5ba200dc13a42d5e2b9683cfee7cbb3  guix-build-8047bb6feaa9/output/powerpc64-linux-gnu/bitcoin-8047bb6feaa9-powerpc64-linux-gnu.tar.gz
79cac140ef8745d214a1c8d8601dd6eba9ff54a0aa50a106c09e62d378a2f011  guix-build-8047bb6feaa9/output/powerpc64le-linux-gnu/SHA256SUMS.part
e2051b4a88d9c7a76aa2d9e9ffd721d08bcc9fb279e7f0214622df4c5b2e549a  guix-build-8047bb6feaa9/output/powerpc64le-linux-gnu/bitcoin-8047bb6feaa9-powerpc64le-linux-gnu-debug.tar.gz
9619457edac605460405c03760ee55d48be5e107e9b88ebcdc4bea47749f7642  guix-build-8047bb6feaa9/output/powerpc64le-linux-gnu/bitcoin-8047bb6feaa9-powerpc64le-linux-gnu.tar.gz
7783309320d2298bcbe36e3ff3d594c7fd37ea163bb27c148bdc46f162c1d054  guix-build-8047bb6feaa9/output/riscv64-linux-gnu/SHA256SUMS.part
9b0e9eac57d3bfcd849efb1106fb83ea4b70c0a11de85a861f21c26c51e4c727  guix-build-8047bb6feaa9/output/riscv64-linux-gnu/bitcoin-8047bb6feaa9-riscv64-linux-gnu-debug.tar.gz
b292334262288dca4a0fae6cc142b52be00e0b6ae435f8b2b9b4386400257ffd  guix-build-8047bb6feaa9/output/riscv64-linux-gnu/bitcoin-8047bb6feaa9-riscv64-linux-gnu.tar.gz
dc3a39f638fdb32f5f58534057bfac6fe4e0c1f253bfe1ccec230cf1bddf8bcf  guix-build-8047bb6feaa9/output/x86_64-apple-darwin/SHA256SUMS.part
d46df2d74687a2a46adb73fb7cfb0723208d702bbe186c0381c50b0775cfce59  guix-build-8047bb6feaa9/output/x86_64-apple-darwin/bitcoin-8047bb6feaa9-x86_64-apple-darwin-unsigned.tar.gz
cd271760b5e4745b533b1201746ee7ee5747b3d6a426770ab7e20892c697cc8b  guix-build-8047bb6feaa9/output/x86_64-apple-darwin/bitcoin-8047bb6feaa9-x86_64-apple-darwin-unsigned.zip
133a5d9c6c90756539377c1eb89fce65dd6d07d4d8281799198fdcc9dda7e40e  guix-build-8047bb6feaa9/output/x86_64-apple-darwin/bitcoin-8047bb6feaa9-x86_64-apple-darwin.tar.gz
76d6f8345ed55f64f5145ec683a144903cd777819804e880ec7d0c0cb2b2fec9  guix-build-8047bb6feaa9/output/x86_64-linux-gnu/SHA256SUMS.part
ad3bf94e9b257dc49624512dddd7292f10129d5e9a309afcd330a7c29d134e45  guix-build-8047bb6feaa9/output/x86_64-linux-gnu/bitcoin-8047bb6feaa9-x86_64-linux-gnu-debug.tar.gz
7dd04ace57d9c099195b862342dcfd1b0ca854e0a58906442470826297c9280e  guix-build-8047bb6feaa9/output/x86_64-linux-gnu/bitcoin-8047bb6feaa9-x86_64-linux-gnu.tar.gz
6382292fa6ea24e8bd2ac44464ad2c8fb24cbe1a62b36b530a22c4e488b7f975  guix-build-8047bb6feaa9/output/x86_64-w64-mingw32/SHA256SUMS.part
65998c3269652698dabbcd45f36f03df44fdabea75517ccd7b71ce5e5fdb02e1  guix-build-8047bb6feaa9/output/x86_64-w64-mingw32/bitcoin-8047bb6feaa9-win64-debug.zip
e2106694cb294a0b48f21c3b81a4232b150c9b7c84dd012f02bd23db5462e392  guix-build-8047bb6feaa9/output/x86_64-w64-mingw32/bitcoin-8047bb6feaa9-win64-setup-unsigned.exe
881023240ca29b323ecaefddf6a3d1c6b8e6c9bcb77ab2ff2d2517cb8ca19ab8  guix-build-8047bb6feaa9/output/x86_64-w64-mingw32/bitcoin-8047bb6feaa9-win64-unsigned.tar.gz
094df6af5b660deaf247edf5009feac855c98cb283a5d268cd6b37e2bbf8be60  guix-build-8047bb6feaa9/output/x86_64-w64-mingw32/bitcoin-8047bb6feaa9-win64.zip
```

**Comment by TheCharlatan** [comment]
Guix builds (x86_64 and aarch64):
```
find guix-build-$(git rev-parse --short=12 HEAD)/output/ -type f -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum
f3d6ac10842f48884b36d704cc4303ee001197a5c39f7d65116324ab919f4497  guix-build-8047bb6feaa9/output/aarch64-linux-gnu/SHA256SUMS.part
a651622edbca1c9badf7f4018296639929f9553c257bc2cdb464c240e5ab29d2  guix-build-8047bb6feaa9/output/aarch64-linux-gnu/bitcoin-8047bb6feaa9-aarch64-linux-gnu-debug.tar.gz
6ad8004e3739c51380032a411f43054a7768188033bcd9534ebb165b1755819d  guix-build-8047bb6feaa9/output/aarch64-linux-gnu/bitcoin-8047bb6feaa9-aarch64-linux-gnu.tar.gz
aaecf84b3fabcec61612534b302112950cd5254522397f8967538ebb29405561  guix-build-8047bb6feaa9/output/arm-linux-gnueabihf/SHA256SUMS.part
af1cc0dd1e6196cd49fbf0a4b851551314cfd721efa6fe2e0c348ffb5e7e2023  guix-build-8047bb6feaa9/output/arm-linux-gnueabihf/bitcoin-8047bb6feaa9-arm-linux-gnueabihf-debug.tar.gz
0a887a820c9e13e2cc2b1b61072252d5b48cceb631b3af687111abd7359c7bc4  guix-build-8047bb6feaa9/output/arm-linux-gnueabihf/bitcoin-8047bb6feaa9-arm-linux-gnueabihf.tar.gz
b6943c5b1cf963e78f67a3251855e5d516315f32e1d49a487031352929bffaf0  guix-build-8047bb6feaa9/output/arm64-apple-darwin/SHA256SUMS.part
28913ce170b61922b5be6f77f51d2ce35eb5962017b29351e4bc091a74aefe6f  guix-build-8047bb6feaa9/output/arm64-apple-darwin/bitcoin-8047bb6feaa9-arm64-apple-darwin-unsigned.tar.gz
cb30060d8a1495d66107f43714e47cba9597a2a8d0afe9eae32cf1762311f2b5  guix-build-8047bb6feaa9/output/arm64-apple-darwin/bitcoin-8047bb6feaa9-arm64-apple-darwin-unsigned.zip
810d2c6317b5db2f1be16de9af73ef109b0627ce37a2061ce101799b2263f4d5  guix-build-8047bb6feaa9/output/arm64-apple-darwin/bitcoin-8047bb6feaa9-arm64-apple-darwin.tar.gz
13a5fa14a91d95b66c78c405f7deca14db148f1d6b86a7659da097d1cbcd430c  guix-build-8047bb6feaa9/output/dist-archive/bitcoin-8047bb6feaa9.tar.gz
949b7ac900f946d974dfc1cadede95738f2077e58976fc3bf1375a45ba45d6d8  guix-build-8047bb6feaa9/output/powerpc64-linux-gnu/SHA256SUMS.part
af1f890255e152434f49e7d6973a0c8d95b71f04de3d55737a0c7429d3aa36a9  guix-build-8047bb6feaa9/output/powerpc64-linux-gnu/bitcoin-8047bb6feaa9-powerpc64-linux-gnu-debug.tar.gz
bdddf864f0d9829f749ea9eea2197b58f5ba200dc13a42d5e2b9683cfee7cbb3  guix-build-8047bb6feaa9/output/powerpc64-linux-gnu/bitcoin-8047bb6feaa9-powerpc64-linux-gnu.tar.gz
79cac140ef8745d214a1c8d8601dd6eba9ff54a0aa50a106c09e62d378a2f011  guix-build-8047bb6feaa9/output/powerpc64le-linux-gnu/SHA256SUMS.part
e2051b4a88d9c7a76aa2d9e9ffd721d08bcc9fb279e7f0214622df4c5b2e549a  guix-build-8047bb6feaa9/output/powerpc64le-linux-gnu/bitcoin-8047bb6feaa9-powerpc64le-linux-gnu-debug.tar.gz
9619457edac605460405c03760ee55d48be5e107e9b88ebcdc4bea47749f7642  guix-build-8047bb6feaa9/output/powerpc64le-linux-gnu/bitcoin-8047bb6feaa9-powerpc64le-linux-gnu.tar.gz
7783309320d2298bcbe36e3ff3d594c7fd37ea163bb27c148bdc46f162c1d054  guix-build-8047bb6feaa9/output/riscv64-linux-gnu/SHA256SUMS.part
9b0e9eac57d3bfcd849efb1106fb83ea4b70c0a11de85a861f21c26c51e4c727  guix-build-8047bb6feaa9/output/riscv64-linux-gnu/bitcoin-8047bb6feaa9-riscv64-linux-gnu-debug.tar.gz
b292334262288dca4a0fae6cc142b52be00e0b6ae435f8b2b9b4386400257ffd  guix-build-8047bb6feaa9/output/riscv64-linux-gnu/bitcoin-8047bb6feaa9-riscv64-linux-gnu.tar.gz
dc3a39f638fdb32f5f58534057bfac6fe4e0c1f253bfe1ccec230cf1bddf8bcf  guix-build-8047bb6feaa9/output/x86_64-apple-darwin/SHA256SUMS.part
d46df2d74687a2a46adb73fb7cfb0723208d702bbe186c0381c50b0775cfce59  guix-build-8047bb6feaa9/output/x86_64-apple-darwin/bitcoin-8047bb6feaa9-x86_64-apple-darwin-unsigned.tar.gz
cd271760b5e4745b533b1201746ee7ee5747b3d6a426770ab7e20892c697cc8b  guix-build-8047bb6feaa9/output/x86_64-apple-darwin/bitcoin-8047bb6feaa9-x86_64-apple-darwin-unsigned.zip
133a5d9c6c90756539377c1eb89fce65dd6d07d4d8281799198fdcc9dda7e40e  guix-build-8047bb6feaa9/output/x86_64-apple-darwin/bitcoin-8047bb6feaa9-x86_64-apple-darwin.tar.gz
76d6f8345ed55f64f5145ec683a144903cd777819804e880ec7d0c0cb2b2fec9  guix-build-8047bb6feaa9/output/x86_64-linux-gnu/SHA256SUMS.part
ad3bf94e9b257dc49624512dddd7292f10129d5e9a309afcd330a7c29d134e45  guix-build-8047bb6feaa9/output/x86_64-linux-gnu/bitcoin-8047bb6feaa9-x86_64-linux-gnu-debug.tar.gz
7dd04ace57d9c099195b862342dcfd1b0ca854e0a58906442470826297c9280e  guix-build-8047bb6feaa9/output/x86_64-linux-gnu/bitcoin-8047bb6feaa9-x86_64-linux-gnu.tar.gz
6382292fa6ea24e8bd2ac44464ad2c8fb24cbe1a62b36b530a22c4e488b7f975  guix-build-8047bb6feaa9/output/x86_64-w64-mingw32/SHA256SUMS.part
65998c3269652698dabbcd45f36f03df44fdabea75517ccd7b71ce5e5fdb02e1  guix-build-8047bb6feaa9/output/x86_64-w64-mingw32/bitcoin-8047bb6feaa9-win64-debug.zip
e2106694cb294a0b48f21c3b81a4232b150c9b7c84dd012f02bd23db5462e392  guix-build-8047bb6feaa9/output/x86_64-w64-mingw32/bitcoin-8047bb6feaa9-win64-setup-unsigned.exe
881023240ca29b323ecaefddf6a3d1c6b8e6c9bcb77ab2ff2d2517cb8ca19ab8  guix-build-8047bb6feaa9/output/x86_64-w64-mingw32/bitcoin-8047bb6feaa9-win64-unsigned.tar.gz
094df6af5b660deaf247edf5009feac855c98cb283a5d268cd6b37e2bbf8be60  guix-build-8047bb6feaa9/output/x86_64-w64-mingw32/bitcoin-8047bb6feaa9-win64.zip
```

**Review by sedited — APPROVED** [review]
ACK 8047bb6feaa9ee5d6c1edb7640baaf228450bc6b

**Comment by fanquake** [comment]
Guix Build (x86_64):
```bash
f3d6ac10842f48884b36d704cc4303ee001197a5c39f7d65116324ab919f4497  guix-build-8047bb6feaa9/output/aarch64-linux-gnu/SHA256SUMS.part
a651622edbca1c9badf7f4018296639929f9553c257bc2cdb464c240e5ab29d2  guix-build-8047bb6feaa9/output/aarch64-linux-gnu/bitcoin-8047bb6feaa9-aarch64-linux-gnu-debug.tar.gz
6ad8004e3739c51380032a411f43054a7768188033bcd9534ebb165b1755819d  guix-build-8047bb6feaa9/output/aarch64-linux-gnu/bitcoin-8047bb6feaa9-aarch64-linux-gnu.tar.gz
aaecf84b3fabcec61612534b302112950cd5254522397f8967538ebb29405561  guix-build-8047bb6feaa9/output/arm-linux-gnueabihf/SHA256SUMS.part
af1cc0dd1e6196cd49fbf0a4b851551314cfd721efa6fe2e0c348ffb5e7e2023  guix-build-8047bb6feaa9/output/arm-linux-gnueabihf/bitcoin-8047bb6feaa9-arm-linux-gnueabihf-debug.tar.gz
0a887a820c9e13e2cc2b1b61072252d5b48cceb631b3af687111abd7359c7bc4  guix-build-8047bb6feaa9/output/arm-linux-gnueabihf/bitcoin-8047bb6feaa9-arm-linux-gnueabihf.tar.gz
b6943c5b1cf963e78f67a3251855e5d516315f32e1d49a487031352929bffaf0  guix-build-8047bb6feaa9/output/arm64-apple-darwin/SHA256SUMS.part
28913ce170b61922b5be6f77f51d2ce35eb5962017b29351e4bc091a74aefe6f  guix-build-8047bb6feaa9/output/arm64-apple-darwin/bitcoin-8047bb6feaa9-arm64-apple-darwin-unsigned.tar.gz
cb30060d8a1495d66107f43714e47cba9597a2a8d0afe9eae32cf1762311f2b5  guix-build-8047bb6feaa9/output/arm64-apple-darwin/bitcoin-8047bb6feaa9-arm64-apple-darwin-unsigned.zip
810d2c6317b5db2f1be16de9af73ef109b0627ce37a2061ce101799b2263f4d5  guix-build-8047bb6feaa9/output/arm64-apple-darwin/bitcoin-8047bb6feaa9-arm64-apple-darwin.tar.gz
13a5fa14a91d95b66c78c405f7deca14db148f1d6b86a7659da097d1cbcd430c  guix-build-8047bb6feaa9/output/dist-archive/bitcoin-8047bb6feaa9.tar.gz
949b7ac900f946d974dfc1cadede95738f2077e58976fc3bf1375a45ba45d6d8  guix-build-8047bb6feaa9/output/powerpc64-linux-gnu/SHA256SUMS.part
af1f890255e152434f49e7d6973a0c8d95b71f04de3d55737a0c7429d3aa36a9  guix-build-8047bb6feaa9/output/powerpc64-linux-gnu/bitcoin-8047bb6feaa9-powerpc64-linux-gnu-debug.tar.gz
bdddf864f0d9829f749ea9eea2197b58f5ba200dc13a42d5e2b9683cfee7cbb3  guix-build-8047bb6feaa9/output/powerpc64-linux-gnu/bitcoin-8047bb6feaa9-powerpc64-linux-gnu.tar.gz
79cac140ef8745d214a1c8d8601dd6eba9ff54a0aa50a106c09e62d378a2f011  guix-build-8047bb6feaa9/output/powerpc64le-linux-gnu/SHA256SUMS.part
e2051b4a88d9c7a76aa2d9e9ffd721d08bcc9fb279e7f0214622df4c5b2e549a  guix-build-8047bb6feaa9/output/powerpc64le-linux-gnu/bitcoin-8047bb6feaa9-powerpc64le-linux-gnu-debug.tar.gz
9619457edac605460405c03760ee55d48be5e107e9b88ebcdc4bea47749f7642  guix-build-8047bb6feaa9/output/powerpc64le-linux-gnu/bitcoin-8047bb6feaa9-powerpc64le-linux-gnu.tar.gz
7783309320d2298bcbe36e3ff3d594c7fd37ea163bb27c148bdc46f162c1d054  guix-build-8047bb6feaa9/output/riscv64-linux-gnu/SHA256SUMS.part
9b0e9eac57d3bfcd849efb1106fb83ea4b70c0a11de85a861f21c26c51e4c727  guix-build-8047bb6feaa9/output/riscv64-linux-gnu/bitcoin-8047bb6feaa9-riscv64-linux-gnu-debug.tar.gz
b292334262288dca4a0fae6cc142b52be00e0b6ae435f8b2b9b4386400257ffd  guix-build-8047bb6feaa9/output/riscv64-linux-gnu/bitcoin-8047bb6feaa9-riscv64-linux-gnu.tar.gz
dc3a39f638fdb32f5f58534057bfac6fe4e0c1f253bfe1ccec230cf1bddf8bcf  guix-build-8047bb6feaa9/output/x86_64-apple-darwin/SHA256SUMS.part
d46df2d74687a2a46adb73fb7cfb0723208d702bbe186c0381c50b0775cfce59  guix-build-8047bb6feaa9/output/x86_64-apple-darwin/bitcoin-8047bb6feaa9-x86_64-apple-darwin-unsigned.tar.gz
cd271760b5e4745b533b1201746ee7ee5747b3d6a426770ab7e20892c697cc8b  guix-build-8047bb6feaa9/output/x86_64-apple-darwin/bitcoin-8047bb6feaa9-x86_64-apple-darwin-unsigned.zip
133a5d9c6c90756539377c1eb89fce65dd6d07d4d8281799198fdcc9dda7e40e  guix-build-8047bb6feaa9/output/x86_64-apple-darwin/bitcoin-8047bb6feaa9-x86_64-apple-darwin.tar.gz
76d6f8345ed55f64f5145ec683a144903cd777819804e880ec7d0c0cb2b2fec9  guix-build-8047bb6feaa9/output/x86_64-linux-gnu/SHA256SUMS.part
ad3bf94e9b257dc49624512dddd7292f10129d5e9a309afcd330a7c29d134e45  guix-build-8047bb6feaa9/output/x86_64-linux-gnu/bitcoin-8047bb6feaa9-x86_64-linux-gnu-debug.tar.gz
7dd04ace57d9c099195b862342dcfd1b0ca854e0a58906442470826297c9280e  guix-build-8047bb6feaa9/output/x86_64-linux-gnu/bitcoin-8047bb6feaa9-x86_64-linux-gnu.tar.gz
6382292fa6ea24e8bd2ac44464ad2c8fb24cbe1a62b36b530a22c4e488b7f975  guix-build-8047bb6feaa9/output/x86_64-w64-mingw32/SHA256SUMS.part
65998c3269652698dabbcd45f36f03df44fdabea75517ccd7b71ce5e5fdb02e1  guix-build-8047bb6feaa9/output/x86_64-w64-mingw32/bitcoin-8047bb6feaa9-win64-debug.zip
e2106694cb294a0b48f21c3b81a4232b150c9b7c84dd012f02bd23db5462e392  guix-build-8047bb6feaa9/output/x86_64-w64-mingw32/bitcoin-8047bb6feaa9-win64-setup-unsigned.exe
881023240ca29b323ecaefddf6a3d1c6b8e6c9bcb77ab2ff2d2517cb8ca19ab8  guix-build-8047bb6feaa9/output/x86_64-w64-mingw32/bitcoin-8047bb6feaa9-win64-unsigned.tar.gz
094df6af5b660deaf247edf5009feac855c98cb283a5d268cd6b37e2bbf8be60  guix-build-8047bb6feaa9/output/x86_64-w64-mingw32/bitcoin-8047bb6feaa9-win64.zip
```

**Comment by fanquake** [comment]
Couldn't see any patches that we can drop.

**Pull request merged**
