### PR TITLE
build: 0.19 release updates on master

### PR DESCRIPTION
**Pull request by jonatack**
Post split-off. As per https://github.com/bitcoin/bitcoin/blob/master/doc/release-process.md#before-every-major-release and  issue #16996.

Note: after split-off, the same changes should be made on the new 0.19.0 release branch, with also these additional changes to both files (configure.ac and build_msvc/bitcoin_config.h):

  - set `CLIENT_VERSION_REVISION` to `0`
  - set `CLIENT_VERSION_IS_RELEASE` to `true`

The second commit resets the release notes after branch-off and proposes a few improvements.

### CODE REVIEW

**Comment by laanwj** [comment]
ACK post-splitoff

Can you please empty the release notes (and remove any fragments) as well as in 58efc49b954f145ce39fc1047aca3534b7100a4f.

**Comment by jonatack** [comment]
Thanks -- release notes emptied with a few improvements and PR description updated.

**Comment by laanwj** [comment]
I think it's best to delay the rebase until the actual branch-off, as there might be an arbitrary number of release notes changes inbetween.

**Comment by jonatack** [comment]
Snap! :) rebased.

**Comment by jonatack** [comment]
Snap! Will check back after branch-off for changes and fragments.

**Comment by laanwj** [comment]
ACK 434101875c69d523ee34afee540212129be06458

**Pull request merged**
