### PR TITLE
Use ArgsManager::ALLOW_STRING flag explicitly in simple cases

### PR DESCRIPTION
**Pull request by hebasto**
This PR replaces permissive `ArgsManager::ALLOW_ANY` flag with more restrictive `ArgsManager::ALLOW_STRING` flag for string type configuration options in simple cases.

With this PR:
```
$ src/bitcoind -nodatadir
Error: Error parsing command line arguments: Negating of -datadir is meaningless and therefore forbidden

$ src/bitcoind -noblocksdir
Error: Error parsing command line arguments: Negating of -blocksdir is meaningless and therefore forbidden
```

Special cases, like `-nowallet`, are out of this PR's scope.

NOTE for reviewers. This PR is based on top of #16508 and #16097, so only the last four commits are to be reviewed here.

### CODE REVIEW

**Comment by hebasto** [comment]
ping @MarcoFalke @promag @ryanofsky

**Review by promag — COMMENTED** [review]
Concept ACK.

**Comment by jonasschnelli** [comment]
Concept ACK. Haven't looked at the code though.

**Comment by practicalswift** [comment]
Concept ACK

**Comment by ryanofsky** [comment]
I'd NACK this PR in it's current form, but I think it could be fixed up without too much effort. Currently, commit "Use ArgsManager::ALLOW_STRING flag explicitly" (181f462dd983c0218618c1f64b65eefecb32ca4e) is changing too much behavior at the same time, and the current PR description doesn't begin to describe all the changes, and there are no release notes. Regarding commit 181f462dd983c0218618c1f64b65eefecb32ca4e:

* I think it's good to trigger errors if someone specifies `-noblocksdir` or `-nodatadir` since these directories are mandatory and bitcoin can't function without them. It looks like the commit is doing the right thing by forbidding these options.
* It's probably ok to trigger unconditional errors on `-norpcport` and `-nowalletdir` like this commit is doing, but I think more ideally conservative configurations like `-noserver -norpcport` or `-nowallet -nowalletdir` would continue to work instead of being forbidden now.
* I think options like `-noalertnotify`, `-noassumevalid`, `-noconf`, `-nominimumchainwork`, `-noaddnode`, and others should be continue to allowed since they could be useful for command line overrides and because they have straightforward meanings. It looks like the PR is forbidding these options without a justification. If these flags aren't currently being interpreted correctly, it would seem better to make simple bugfixes here than forbid options which should work.
* The `-noincludeconf` case might be an exception, or there may be other options like it, but it's explicitly handled in config parsing code to disable inclusion, but now the option itself is now forbidden, so this is a bug.

Overall, I think commit 181f462dd983c0218618c1f64b65eefecb32ca4e changes too much and is too restrictive. I think some parts of it could be rolled back to limit scope of this PR and preserve more current behavior, while allowing more targeted improvements to be done in the future. Otherwise, I would just like to see it split up into smaller commits that:

* Change individual options, or small groups of options that are similar to each other.
* Document user-visible changes in release notes, so users can be forewarned about them. You can see instructions at https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md#release-notes for adding a `doc/release-notes-16476.md` file, to document previously accepted options that are now errors and previously misinterpreted options that are now interpreted correctly.

**Comment by hebasto** [comment]
@ryanofsky 
> I think some parts of it could be rolled back to limit scope of this PR and preserve more current behavior, while allowing more targeted improvements to be done in the future.

Done. Only simple cases are in this PR. Other parts have been rolled back.

>  I would just like to see it split up into smaller commits...

Done. A big commit has been split in two smaller ones.

> Document user-visible changes in release notes, so users can be forewarned about them.

Done.

Also some tests have been added.

**Comment by hebasto** [comment]
The PR title and description have been updated.

**Pull request closed without merging**
