### PR TITLE
backport: #11995 Fix Qt build with Xcode 9

### PR DESCRIPTION
**Pull request by fanquake**
GitHub-Pull: #11995
Rebased-From: 2b1f794

### CODE REVIEW

**Comment by jonasschnelli** [comment]
utACK b7d95037f42adb393881cea182814f9a8fc14879.
Looks good, haven't tested though (currently no access to 10.13).

There is some whitespace issue:
https://travis-ci.org/bitcoin/bitcoin/jobs/350402801

**Comment by fanquake** [comment]
Whitespace issue should be resolved.

**Comment by laanwj** [comment]
Gah, still seems there's a whitespace issue.
```
diff --git a/depends/patches/qt/fix-cocoahelpers-macos.patch b/depends/patches/qt/fix-cocoahelpers-macos.patch
@@ -0,0 +1,70 @@
+
+
+
+
+
^---- failure generated from contrib/devtools/lint-whitespace.sh
```

I think we should exclude `.patch` files from the whitespace checks?

**Comment by fanquake** [comment]
Added a backport of https://github.com/bitcoin/bitcoin/pull/12442 so that Travis stops harassing us about patch whitespace on the 0.16 branch.

**Pull request merged**
