### PR TITLE
build: set minimum supported macOS to 10.14

### PR DESCRIPTION
**Pull request by fanquake**
This is a requirement for C++17 support. See my comments [here](https://github.com/bitcoin/bitcoin/issues/16684#issuecomment-643722538):

> You cannot use std::get with std::variant on macOS < 10.14, because Apples libc++ doesn't support the std::bad_variant_access exception. [Relevant comment](https://github.com/bitcoin/bitcoin/pull/19183#discussion_r439794318) in #19183.

> While we could work around this in our own code, using std::get_if, this would still be a problem for 3rd-party dependencies.

> I've been testing Qt 5.15LTS (we'll have to enable C++17 in qt, and may upgrade to a newer version at the same time), and you can't enable -std c++17, while targeting a macOS deployment version < 10.14, configuring will fail. They are making use of std::get with std::variant throughout their cocoa code.

We would have to had to have bumped to at least 10.13 in any case, as Qt 5.15 (#19716) [requires 10.13+](https://doc.qt.io/qt-5/supported-platforms.html).

### CODE REVIEW

**Comment by jonasschnelli** [comment]
macOS 10.14 was released Sept 2018. Do we really want to drop older macOSes? Also some (older) Mac Hardware can't be upgraded to 10.14.

**Comment by MarcoFalke** [comment]
No opinion on this, but it should be possible to use C++17, but postpone std::variant and qt5.15 to a later release?

**Comment by luke-jr** [comment]
macOS 10.13 is still supported and 10.13.6 was released only 6 days ago...

But, we only support the most recent LTS of major Linux distros. I see no reason the macOS equivalent wouldn't be macOS 11 (Big Sur)...

otoh, maybe the policy needs to be different for macOS due to the hardware incompatibility @jonasschnelli mentions...

**Comment by MarcoFalke** [comment]
> But, we only support the most recent LTS of major Linux distros. I see no reason the macOS equivalent wouldn't be macOS 11 (Big Sur)...

You keep repeating that, but I can't find where this is documented or was discussed.

**Comment by hebasto** [comment]
> macOS 10.13 is still supported and 10.13.6 was released only 6 days ago...

Not a release, but a security update, right?

If C++17 and macOS 10.13 cannot coexist peacefully, I Concept ACK on moving to macOS 10.14+

Owners of macOS 10.13 have two choices:
- upgrade macOS (if hw supports it)
- do not upgrade Bitcoin Core

**Comment by luke-jr** [comment]
@MarcoFalke That's been the case for many years. I don't recall when it was first discussed, but it likely came up around C++11 migration.

@hebasto I think there's also an option to install Linux? Also, I don't think anyone has plans to support 0.21 longer than normal...

**Comment by MarcoFalke** [comment]
@luke-jr The previous LTS of Ubuntu (18.04) is fully supported and stays that way. Dropping support for that would also drop support for the most prominent OS that all nodes run on.

**Comment by MarcoFalke** [comment]
> macOS 10.13 High Sierra - End of Life Support Ending November 30, 2020

source: (unverified) https://computing.cs.cmu.edu/news/2019/eol-macos-highsierra

**Comment by sipa** [comment]
If macOS 10.13 will become unsupported this year, I don't think there is much of a problem with requiring 10.14 for 0.22.

**Comment by laanwj** [comment]
Concept ACK. I don't think bumping the minimum MacOS version was ever an issue before. In contrast to Windows and Linux users, Mac users tend to be, in general, really eager for OS updates, and the life of an older version is very short.

**Comment by practicalswift** [comment]
Concept ACK for the reasons given by @laanwj

**Review by hebasto — APPROVED** [review]
ACK a52ecc936a267cae97c2f313743bf75d5af07700, I have reviewed the code and it looks OK, I agree it can be merged.

**Comment by hebasto** [comment]
Just for the record: Homebrew does not provide support for macOS 10.12 and 10.13, e.g.:
- https://formulae.brew.sh/formula/automake
- https://formulae.brew.sh/formula/boost

**Pull request merged**
