### PR TITLE
Change "insane" to "absurd" (referring to high fees) in text strings and identifiers

### PR DESCRIPTION
**Pull request by daira**
Note that this will also require translation changes in Transifex for the key
"A fee higher than %1 is considered an insanely high fee." which is now
"A fee higher than %1 is considered an absurdly high fee."
(see https://github.com/bitcoin/bitcoin/pull/5727#issuecomment-72341948 )

Signed-off-by: Daira Hopwood daira@jacaranda.org

### CODE REVIEW

**Comment by daira** [comment]
See #5727 for previous discussion.

**Comment by laanwj** [comment]
ACK

**Comment by fanquake** [comment]
ACK

**Comment by jonasschnelli** [comment]
ACK

**Comment by luke-jr** [comment]
utACK

**Comment by paveljanik** [comment]
ACK

**Pull request merged**
