### PR TITLE
contrib/bash-completions: use package naming conventions

### PR DESCRIPTION
**Pull request by erikarvstedt**
#### Copy of commit msg

This naming scheme supports auto-detection and on-demand loading of completions.

See
https://github.com/scop/bash-completion/blob/ba109693ee2284f6a82f8f0e1563baf071252df9/README.md#faq,
section "Where should I put it to be sure that interactive bash shells will find it and source it", keyword `foo.bash`.

Previously, distro package maintainers had to rename these files manually.

### CODE REVIEW

**Comment by erikarvstedt** [comment]
cc @prusnak

**Review by prusnak — APPROVED** [review]
utACK

**Comment by fanquake** [comment]
Seems ok, and lines up with the other .fish completions. I see the discussion in https://github.com/fort-nix/nix-bitcoin/pull/647.

I guess downstreams like https://github.com/gentoo/gentoo/blob/af3998740256e5f8f8618ae248edd512fff5f0eb/net-p2p/bitcoin-cli/bitcoin-cli-0.21.0.ebuild#L101C2-L101C2, or https://github.com/archlinuxarm/PKGBUILDs/blob/d645584b373f39c5aa750bd4729ee812ad8fc5c4/extra/bitcoin/PKGBUILD#L96 can be pinged to update their integrations.

cc @willcl-ark

**Comment by willcl-ark** [comment]
ACK 360b917674e63c1e95119040463b3f50976bf331

Agree that this matches the spec and best practice, and also tested that simply copying completions to _/usr/share/bash-completion/completions_ had them work automatically as expected.

I suppose with cmake incoming there's no point in adding a configure flag to install completions with `make install`, but it could be nice to have that option later...

**Comment by fanquake** [comment]
Added a label so we don't forget to mention this in the 26.x release notes.

**Comment by fanquake** [comment]
Release note to be added in #29023.

**Pull request merged**
