### PR TITLE
doc: Use DecodeTxDoc helper

### PR DESCRIPTION
**Pull request by maflcko**

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Rendered diff is move-only:


```diff
diff --git a/getrawtransaction b/getrawtransaction
index e1a266d..ae73e6b 100644
--- a/getrawtransaction
+++ b/getrawtransaction
@@ -23,6 +23,10 @@ Result (if verbose is not set or set to false):
 Result (if verbose is set to true):
 {                                    (json object)
   "in_active_chain" : true|false,    (boolean, optional) Whether specified block is in the active chain or not (only present with explicit "blockhash" argument)
+  "blockhash" : "hex",               (string, optional) the block hash
+  "confirmations" : n,               (numeric, optional) The confirmations
+  "blocktime" : xxx,                 (numeric, optional) The block time expressed in UNIX epoch time
+  "time" : n,                        (numeric, optional) Same as "blocktime"
   "hex" : "hex",                     (string) The serialized, hex-encoded data for 'txid'
   "txid" : "hex",                    (string) The transaction id (same as provided)
   "hash" : "hex",                    (string) The transaction hash (differs from txid for witness transactions)
@@ -61,11 +65,7 @@ Result (if verbose is set to true):
       }
     },
     ...
-  ],
-  "blockhash" : "hex",               (string, optional) the block hash
-  "confirmations" : n,               (numeric, optional) The confirmations
-  "blocktime" : xxx,                 (numeric, optional) The block time expressed in UNIX epoch time
-  "time" : n                         (numeric, optional) Same as "blocktime"
+  ]
 }
 
 Examples:

**Review by fanquake — APPROVED** [review]
ACK fa58427aaea10b48ced069db20a58157a38ce9f9

**Review by shaavan — APPROVED** [review]
ACK fa58427aaea10b48ced069db20a58157a38ce9f9

- This newly introduced helper function, DecodeTxDoc, helps display all the text in the RPC help message for getting a transaction and decoderawtransaction.
- Since almost all the text in both of these functions help message is the same, this function helps remove the redundant lines of code while ensuring consistency in the displayed message for both these RPC commands.
- I compiled the PR successfully, and I was able to verify that the displayed RPC help message is unchanged.

**Screenshot:**
PR

**Comment by shaavan** [comment]
I want to bring a point to notice. While compiling the PR, I got a bunch of repeated (same) warnings, whose screenshot I am adding here.

Issue

Since this doesn't seem relevant to this PR, I am adding it as a separate comment. I am running bitcoin core on Ubuntu 20.04. I am not sure if this is a genuine issue or my system's fault.

**Comment by laanwj** [comment]
Post-merge ACK

**Review by w0xlt — COMMENTED** [review]
Post-merge ACK

**Pull request merged**
