### PR TITLE
travis: Re-enable s390x

### PR DESCRIPTION
**Pull request by maflcko**
According to travis, the issue has been solved. Quote

> I would like to confirm that we have resolved this issue and most of our users are reported that this issue has been resolved on their end as well. Could you please re-check and see if that still exists for you?

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Requested here https://github.com/bitcoin/bitcoin/pull/19509#discussion_r461556730 by @theStack

**Comment by theStack** [comment]
Ah, great news that Travis solved the problem! I think having one big endian instance makes a lot of sense.
ACK https://github.com/bitcoin/bitcoin/pull/19613/commits/fae656144e9ec25a0b610cd5278c1b7c42880097

**Comment by troygiorshev** [comment]
posthumous Concept ACK

**Comment by hebasto** [comment]
Disable it again?

- https://travis-ci.org/github/bitcoin/bitcoin/jobs/715083327
- https://travis-ci.org/github/bitcoin/bitcoin/jobs/715125080
- https://travis-ci.org/github/bitcoin/bitcoin/jobs/715202114

**Pull request merged**
