### PR TITLE
Add armhf/aarch64 gitian builds

### PR DESCRIPTION
**Pull request by theuni**
As discussed in yesterday's IRC meeting.

Please see the individual commit messages for more detailed info and caveats. Also note:
- I haven't tested the resulting bins. I'd prefer to get ACKs from testers on native hardware before merge.
- Not yet tested for determinism, though I have no reason to believe it should cause problems.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Started a gitian build: https://bitcoin.jonasschnelli.ch/pulls/8188/

**Comment by laanwj** [comment]
Going to test this.

**Comment by laanwj** [comment]
It's building libX11 for `arm-unknown-linux-gnueabihf`:
```
/home/ubuntu/cache/common/libX11-1.6.2.tar.bz2: OK
Preprocessing libX11...
Configuring libX11...
configure: WARNING: if you wanted to set the --build type, don't use --host.
    If a cross compiler is detected then cross compile mode will be used
checking build system type... x86_64-unknown-linux-gnu
checking host system type... arm-unknown-linux-gnueabihf
```
As X11 is needed only for the GUI, and this disables Qt, I don't think this is necessary?

**Comment by laanwj** [comment]
Crashed:
```
Extracting qt...
/home/ubuntu/cache/common/qt-everywhere-opensource-src-5.2.1.tar.gz: OK

   The specified system/compiler is not supported:

      /home/ubuntu/build/bitcoin/depends/work/build/arm-linux-gnueabihf/qt/5.2.1-6d332f9982b/qtbase/mkspecs/arm-linux-gnueabihf
```

**Comment by laanwj** [comment]
Sorry, looks like something is going here locally. Probably a descriptor/tree mismatch.

**Comment by sipa** [comment]
Hmm, I don't see how this is avoiding building Qt? (I haven't tried, just looking at the code changes)

**Comment by laanwj** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/8188/commits/9d253620874087d96d64d0c4c771a582d9774657
- Output (commit 9d253620874087d96d64d0c4c771a582d9774657):
```
682f88fc641256963247e7af3f9a4884f283966fcb5c231f722f689d89a2cee6  bitcoin-0.12.99-aarch64-linux-gnu-debug.tar.gz
b9ffbbc180381c0f258ce73b03907a083787fd9ff60858c43d6cf0f44eed5329  bitcoin-0.12.99-aarch64-linux-gnu.tar.gz
b68184aaca65cf3e35f5404933cd76e64e050b964a1a9f5b2ffe4c9e04a9f0c4  bitcoin-0.12.99-arm-linux-gnueabihf-debug.tar.gz
c1e2fce0759ad9b960541ebe46ffcf82e0a68de2c1f38aedc2750044b45c3d72  bitcoin-0.12.99-arm-linux-gnueabihf.tar.gz
859d36d60686b1df9349c200bb28d6fd05dfa718fce80e1d3130ba1a3fade01e  bitcoin-0.12.99-i686-pc-linux-gnu-debug.tar.gz
3b0d20fdac61ba321eba25a8171bf0a6c859fedf3d85f62bae03949898229822  bitcoin-0.12.99-i686-pc-linux-gnu.tar.gz
7ec01ff5322a0efabe3230c612a9110501ec1da4604c2518b82d104928b249a8  bitcoin-0.12.99-x86_64-linux-gnu-debug.tar.gz
ae713f6b25a5e35362d1717bcb6f0721a9683f445c71cd0b403b7729ab6dfa5d  bitcoin-0.12.99-x86_64-linux-gnu.tar.gz
```
- It correctly built Xorg and Qt and other GUI dependencies only for x64, not the ARM archs
- ARM tarballs contain the expected files:
```
bitcoin-0.12.99/
bitcoin-0.12.99/bin/
bitcoin-0.12.99/bin/bitcoin-cli
bitcoin-0.12.99/bin/bitcoind
bitcoin-0.12.99/bin/bitcoin-tx
bitcoin-0.12.99/bin/test_bitcoin
bitcoin-0.12.99/include/
bitcoin-0.12.99/include/bitcoinconsensus.h
bitcoin-0.12.99/lib/
bitcoin-0.12.99/lib/libbitcoinconsensus.so
bitcoin-0.12.99/lib/libbitcoinconsensus.so.0
bitcoin-0.12.99/lib/libbitcoinconsensus.so.0.0.0
```
- 32-bit ARM Debian 8.5 (i.MX6 Quad/DualLite)
  - `test_bitcoin` passes
  - `bitcoind` was able to run it on a node, where it veriefied blocks, connected to peers correctly and stayed up to date with the chain
  - `bitcoind` succesfully shuts down, no crashes
- 64-bit ARM Ubuntu 16.04 (ODROID-C2)
  - `test_bitcoin` passes
  - `bitcoind` was able to create its data files and do a testnet sync up to block ~70000 (will keep this running)
  - `bitcoind` succesfully shuts down, no crashes

**Comment by jonasschnelli** [comment]
Tested ACK 9d253620874087d96d64d0c4c771a582d9774657 (AARCH only).
Gitian built successful.
Got different hashes then @laanwj, but I did a merge build:
```
0614d92 Merge branch 'arm-bins' of https://github.com/theuni/bitcoin
9d25362 build: add armhf/aarch64 gitian builds
980e7eb depends: only build qt on linux for x86_64/x86
67db011 Merge #8177: developer notes: updates for C++11
ac8d041 qt: translations update
fde0ac4 Merge #8133: build: Finish up out-of-tree changes
```

```
    c68ea35758ed49abf31e97a516b705ca2d8002699e5b8c82370f39b7d5dec7ce  bitcoin-0.12.99-aarch64-linux-gnu-debug.tar.gz
    5b14e326dff5ccf118df8ca6efadbc6ba6bf7042dd82b81a3c27274722c414eb  bitcoin-0.12.99-aarch64-linux-gnu.tar.gz
    1101faad27ea7f39e876b4274f8601468bf2c534b8bb4038ca783af4cccdcc0b  bitcoin-0.12.99-arm-linux-gnueabihf-debug.tar.gz
    bab4c0213d2a76e72517bab413eebf421ab7dcf67ff245a0e99f25f8cb81e593  bitcoin-0.12.99-arm-linux-gnueabihf.tar.gz
    454b5ab2a3edaad347d9a6c12cfadc921fc89be79922695cdb3a240d23ce4be1  bitcoin-0.12.99-i686-pc-linux-gnu-debug.tar.gz
    bb74034acd026637531e87199f9b902fdef9420767c6eb96ad0878d2c492d465  bitcoin-0.12.99-i686-pc-linux-gnu.tar.gz
    733f39ad756212d5b321b439a66328e4d005956cf03c4252c5ff383b21583d32  bitcoin-0.12.99-x86_64-linux-gnu-debug.tar.gz
    2145f811a8a5892087948a5f827f791a199da8d0a5e631aff8148ed5c4b163c6  bitcoin-0.12.99-x86_64-linux-gnu.tar.gz
    bdd273ce240272abeff7980895c75bb25456446ac6ec2cdc8f2e36d7f4c3eb7a  src/bitcoin-0.12.99.tar.gz
- in_manifest: |-
    b07e1e71c64e656612820ea76a377730c4e1c79cd29d432051fd99efe29a8f07  bitcoin-linux-0.13-desc.yml
    git:0614d929ddc55be702d910ff3f3f4481db0a6192 bitcoin
```
https://bitcoin.jonasschnelli.ch/pulls/8188/bitcoin-linux-0.13-build.assert

Successfully ran `test_bitcoin` and `bitcoind` on my Pine64 2GB.

```
ubuntu@pine64:~$ cat /proc/cpuinfo 
Processor	: AArch64 Processor rev 4 (aarch64)
processor	: 0
processor	: 1
processor	: 2
processor	: 3
Features	: fp asimd aes pmull sha1 sha2 crc32 
CPU implementer	: 0x41
CPU architecture: AArch64
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4
```

```
ubuntu@pine64:~$ ./test_bitcoin 
Running 204 test cases...

*** No errors detected
```

```
ubuntu@pine64:~$ ./bitcoind --dbcache=300 --datadir=/disk2/fullnode/ --prune=550 --printtoconsole
2016-06-10 15:21:26 
2016-06-10 15:21:26 Bitcoin version v0.12.99.0-0614d92
2016-06-10 15:21:26 InitParameterInteraction: parameter interaction: -whitelistforcerelay=1 -> setting -whitelistrelay=1
---snip
2016-06-10 15:22:57 init message: Verifying blocks...
2016-06-10 15:22:57 Verifying last 288 blocks at level 3
2016-06-10 15:22:57 [0%]...[10%]...[20%]...[30%]...[40%]...[50%]...[60%]...[70%]...[80%]...[90%]...[DONE].
2016-06-10 15:24:19 No coin database inconsistencies in last 42 blocks (43555 transactions)
2016-06-10 15:24:19  block index          171850ms
2016-06-10 15:24:19 init message: Loading wallet...
2016-06-10 15:24:19 nFileVersion = 129900
2016-06-10 15:24:19 Keys: 101 plaintext, 0 encrypted, 101 w/ metadata, 101 total
2016-06-10 15:24:20  wallet                  742ms
2016-06-10 15:24:20 Unsetting NODE_NETWORK on prune mode
2016-06-10 15:24:20 init message: Pruning blockstore...
2016-06-10 15:24:20 mapBlockIndex.size() = 415682
2016-06-10 15:24:20 nBestHeight = 414857
2016-06-10 15:24:20 setKeyPool.size() = 100
2016-06-10 15:24:20 mapWallet.size() = 0
2016-06-10 15:24:20 mapAddressBook.size() = 1
2016-06-10 15:24:20 init message: Loading addresses...
2016-06-10 15:24:20 torcontrol thread start
2016-06-10 15:24:21 Loaded 57944 addresses from peers.dat  1023ms
2016-06-10 15:24:21 init message: Loading banlist...
2016-06-10 15:24:21 dnsseed thread start
2016-06-10 15:24:21 net thread start
2016-06-10 15:24:21 msghand thread start
2016-06-10 15:24:21 opencon thread start
2016-06-10 15:24:21 addcon thread start
2016-06-10 15:24:21 init message: Done loading
```

**Comment by sipa** [comment]
Concept ACK

**Comment by laanwj** [comment]
odroid64 testnet node synced to height 869998 over the weekend. All seems to work fine.

**Pull request merged**
