### PR TITLE
net: add I2P hardcoded seeds

### PR DESCRIPTION
**Pull request by jonatack**
Follow-up to #21560 that updated the fixed seeds infra for BIP155 addresses and then added Tor v3 ones:

- Update contrib/generate-seeds.py to parse I2P addresses

- Add a few I2P nodes to contrib/seeds/nodes_main.txt

- Run generate-seeds.py and add the I2P seeds to chainparamsseeds.h

Reviewers, see contrib/seeds/README.md for more info and feel free to use the following CLI one-liner to check for and propose additional seeds for contrib/seeds/nodes_main.txt. You can also see how many I2P peers your node knows with cli -addrinfo.

```rake
bitcoin-cli getnodeaddresses 0 | jq '.[] | (select(.address | contains(".b32.i2p"))) | .address' | sort
```

I verified the I2P addresses are correctly BIP155-serialized/deserialized by building with all seeds removed from chainparamsseeds.h except those added here, restarting with `-datadir=newdir -dnsseed=0` and running rpc ` getnodeaddresses 0` that initially returns only the new I2P addresses.

### CODE REVIEW

**Comment by jonatack** [comment]
Added port numbers for the seeds to pass the "non-default port" check at `src/net.cpp#L2029` and be connected more quickly.

**Comment by jonatack** [comment]
Am testing running a node with no peers.dat, dnsseed=0, onlynet=i2p, and only these new I2P seeds in chainparamsseeds and it's slowly bootstrapping with only I2P peers so far... 2 to 3 out of the 7 connected.

**Comment by jonatack** [comment]
Tested several times running a node with no peers.dat, dnsseed=0, noonion, onlynet=i2p, and only these new I2P seeds in chainparamsseeds and it connects correctly to the I2P seeds.

```
Bitcoin Core v21.99.0-142e2da4401a-dirty - 70016/Satoshi:21.99.0(@jon)/

<->   type   net  mping   ping send recv  txn  blk  hb age id address                                                           version
out   full   i2p                 35                      0  2 pjs7or2ctvteeo5tu4bwyrtydeuhqhvdprtujn4daxr75jpebjxa.b32.i2p:8333
out   full   i2p                  4                      0  6 72l3ucjkuscrbiiepoehuwqgknyzgo7zuix5ty4puwrkyhtmnsga.b32.i2p:8333
out   full   i2p  12801  12801    1    1    0            1  0 h3r6bkn46qxftwja53pxiykntegfyfjqtnzbm6iv6r5mungmqgmq.b32.i2p:8333 70016/Satoshi:21.99.0/
                     ms     ms  sec  sec  min  min     min

        ipv4    ipv6   onion     i2p   total   block
in         0       0       0       0       0
out        0       0       0       3       3       0
total      0       0       0       3       3

Local addresses
zsxwyo6qcn3chqzwxnseusqgsnuw3maqnztkiypyfxtya4snkoka.b32.i2p     port   8333    score      2
```
```
$ bitcoin-cli -addrinfo
{
  "addresses_known": {
    "ipv4": 0,
    "ipv6": 0,
    "torv2": 0,
    "torv3": 0,
    "i2p": 8,
    "total": 8
  }
}

$ bitcoin-cli getnodeaddresses 0
[
  {
    "time": 1619267336,
    "services": 9,
    "address": "wwbw7nqr3ahkqv62cuqfwgtneekvvpnuc4i4f6yo7tpoqjswvcwa.b32.i2p",
    "port": 8333,
    "network": "i2p"
  },
  {
    "time": 1619331060,
    "services": 9,
    "address": "hnbbyjpxx54623l555sta7pocy3se4sdgmuebi5k6reesz5rjp6q.b32.i2p",
    "port": 8333,
    "network": "i2p"
  },
  {
    "time": 1618857028,
    "services": 9,
    "address": "72l3ucjkuscrbiiepoehuwqgknyzgo7zuix5ty4puwrkyhtmnsga.b32.i2p",
    "port": 8333,
    "network": "i2p"
  },
  {
    "time": 1619232946,
    "services": 9,
    "address": "zsxwyo6qcn3chqzwxnseusqgsnuw3maqnztkiypyfxtya4snkoka.b32.i2p",
    "port": 8333,
    "network": "i2p"
  },
  {
    "time": 1619240850,
    "services": 9,
    "address": "pjs7or2ctvteeo5tu4bwyrtydeuhqhvdprtujn4daxr75jpebjxa.b32.i2p",
    "port": 8333,
    "network": "i2p"
  },
  {
    "time": 1618776457,
    "services": 9,
    "address": "c4gfnttsuwqomiygupdqqqyy5y5emnk5c73hrfvatri67prd7vyq.b32.i2p",
    "port": 8333,
    "network": "i2p"
  },
  {
    "time": 1619959105,
    "services": 1033,
    "address": "h3r6bkn46qxftwja53pxiykntegfyfjqtnzbm6iv6r5mungmqgmq.b32.i2p",
    "port": 8333,
    "network": "i2p"
  },
  {
    "time": 1619108616,
    "services": 9,
    "address": "gehtac45oaghz54ypyopim64mql7oad2bqclla74l6tfeolzmodq.b32.i2p",
    "port": 8333,
    "network": "i2p"
  }
]
```

**Review by vasild — APPROVED** [review]
ACK 142e2da4401aa8c0643f7fc473ffaceafbbf90c3

I verified that the additions to `src/chainparamsseeds.h` are generated from the extended `contrib/seeds/nodes_main.txt`. The I2P peers in my node's list of peers are a subset of the added ones.

The command from the PR description did not work for me because the `getnodeaddresses` RPC does not return a JSON with `network` field. I used this instead:

```sh
bitcoin-cli getnodeaddresses 0 |jq -r '.[] | (select(.address |test("\\.i2p$"; "i"))) | .address' | sort
```

**Comment by Emzy** [comment]
ACK
I'm one of the I2P seeds.

**Comment by jonatack** [comment]
> The command from the PR description did not work for me because the `getnodeaddresses` RPC does not return a JSON with `network` field.

Indeed, it was added only very recently to master in #/21594 (thanks!)

**Comment by jonatack** [comment]
Collecting ways to do this with `jq` :sunglasses: 
```shell
./src/bitcoin-cli getnodeaddresses 0 | jq '.[] | (select(.address | contains(".i2p"))) | .address' | sort
./src/bitcoin-cli getnodeaddresses 0 | jq -r '.[] | (select(.address | test("\\.i2p$"; "i"))) | .address' | sort
./src/bitcoin-cli getnodeaddresses 0 | jq '.[] | (select(.network == "i2p")) | .address' | sort
```

**Comment by jonatack** [comment]
> Collecting ways to do this with `jq` sunglasses

or #21843...

**Comment by vasild** [comment]
> ... select(.address | contains(".i2p")) ...

I have `xppyui2pgfuqegju.onion` :hole:

**Comment by laanwj** [comment]
ACK 142e2da4401aa8c0643f7fc473ffaceafbbf90c3
- Verified that `python3 generate-seeds.py . > ../../src/chainparamsseeds.h` gives the same output
- Checked that all nodes (except one) are connectable

**Comment by jonatack** [comment]
>     * Checked that all nodes (except one) are connectable

Same, am connected to all but one. Pinged the person on IRC and they are checking.

**Comment by jonatack** [comment]
Ok, that node is back online. We're good :rocket:

**Pull request merged**
