### PR TITLE
test: check backup from `migratewallet` can be successfully restored

### PR DESCRIPTION
**Pull request by brunoerg**
`migratewallet` migrates the wallet to a descriptor one. During the process, it generates a backup file of the wallet in case of an incorrect migration. This PR adds test to check if the backup file can be successfully restored.

### CODE REVIEW

**Review by furszy — COMMENTED** [review]
While I'm a concept ACK, I think that the approach isn't the best.

The code is walking through the node's directory, restoring all the backup files without checking if the restored wallet is correct or not.

The main point behind a backup test should be to assert that the restored wallet has the same balance and it watches the same scripts as before. Not only check that the backup file can be opened (the wallet could be empty or missing some information).

Also, test cases should be independent from each other.

Would suggest to test this inside the main `test_basic()` case. Using the `migratewallet()` return information to access the backup path (the command retrieves the backup path). And check that balance and watched scripts are the same prior and post migration.

**Comment by brunoerg** [comment]
Thanks, @furszy. Initially, I was thinking about identifying all backup files into the node's directory, run `migratewallet` with them and check the result. However, I agree it's better to go beyond by checking wallet's balance and other stuff prior and post migration.

Force-pushed changing the approach. I also moved it to `test_basic()`.

**Comment by achow101** [comment]
ACK 769f5b15f207ce6d1067672ea5e195541c97de6b

**Review by jonatack — COMMENTED** [review]
Post-merge ACK.

For the getwalletinfo['balance'] check, RPC getbalances['mine']['trusted'] should work as well.

**Pull request merged**
