### PR TITLE
Fix LogPrint to LogPrintf

### PR DESCRIPTION
**Pull request by thelazier**
Printing Log without category defined should use LogPrintf

### CODE REVIEW

**Comment by evan82** [comment]
utACK

**Comment by pstratem** [comment]
utACK ba6194928a03a474b442744511da4c753441469d

**Comment by laanwj** [comment]
utACK ba61949
Good catch!
This mistake is all too easy to make, unfortunately.

At some point we either need to rename one of those functions, or create an automatic checker for Printf/LogPrintf arguments, or both.

**Comment by gmaxwell** [comment]
I hate that this isn't typesafe, what is this, PHP? :) ... when I saw the ticket open I felt immediately stupid, sure than it must have been me that did this again.  (posthumous utACK).

**Comment by laanwj** [comment]
Eh, why is this merging into 0.12 though?
Isn't this a problem on master?

> I hate that this isn't typesafe, what is this, PHP? :) .

Well it was a step up from C's printf - none of this will allow mangling values or corrupting memory.
It is typesafe, e.g you don't need size specifiers, it doesn't matter if you use `%i` or `%lli` etc.
Worst-case, you get an exception if the number of arguments doesn't match the number of `%`. Or nothing is logged and you rub your head why.
There would be logging methods that are more robust, e.g. C++/Qt style:
```
LogInfo() << "";
LogDebug("rpc") << "Invalid RPC call " << strMethod;
```
(tinyformat even uses this internally, but emulates C printf-isms because that was what was already in the code and this had the least impact)

Then again, there's so much to do already, it's never been urgent.

**Comment by laanwj** [comment]
Forward-ported to master as bf9c70b.
(this is not how we usually work, please base your PR on master next time unless it's a backport)

**Comment by sipa** [comment]
Changing the debug category into an enum would also avoid type ambiguity
(which arises from the fact that the format string and the debug category
are both strings).

**Comment by laanwj** [comment]
> Changing the debug category into an enum would also avoid type ambiguity

That's a neat idea, a problem with that is that it requires centralizing all the debug categories of the program in one place. That would be inimical to modularization.

Another option would be to create a DebugCategory type that is based on string, and only allow passing that as category argument.

```
DebugCategory LOG_RPC("rpc");
...
LogPrintf(LOG_RPC, "Invalid RPC call %s\n", strMethod);
```

**Pull request merged**
