### PR TITLE
build: Fix Boost.Process test for Boost 1.78

### LINKED ISSUE #24413: Homebrew Boost 1.78 breaks external signer configure
Test on macOS 12.2.1 against the master branch. #24397 doesn't fix it.

```
brew info boost
boost: stable 1.78.0 (bottled), HEAD
...
./configure --enable-external-signer
...
checking for boostlib >= 1.64.0 (106400)... yes
checking whether Boost.Process can be used... no
configure: error: External signing is not supported for this Boost version
```

It does work with boost 1.76 (there was no 1.77 release in home-brew):

```
brew install boost@1.76
...
LDFLAGS="-L/usr/local/opt/boost@1.76/lib" CPPFLAGS="-I/usr/local/opt/boost@1.76/include" ./configure --enable-external-signer
...
checking for boostlib >= 1.64.0 (106400)... yes
checking whether Boost.Process can be used... yes
...
Options used to compile and link:
  external signer = yes
```

There's nothing in the release notes about Boost.Process for either [1.77](https://www.boost.org/users/history/version_1_77_0.html) or [1.78](https://www.boost.org/users/history/version_1_78_0.html).

The Homebrew [formula changes](https://github.com/Homebrew/homebrew-core/commits/master/Formula/boost.rb) are nothing but a trivial version and hash bump.

### PR DESCRIPTION
**Pull request by hebasto**
Fixes bitcoin/bitcoin#24413.

An alternative to bitcoin/bitcoin#24414.

### CODE REVIEW

**Comment by Sjors** [comment]
tACK d092dfb1b3f1fadbb22ff5605176979a78b623a2

**Comment by Sjors** [comment]
The MSVC failure seems unrelated:

```
 test  2022-02-22T11:44:36.374000Z TestFramework (ERROR): Assertion failed 
                                   Traceback (most recent call last):
                                     File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\test_framework.py", line 132, in main
                                       self.run_test()
                                     File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\wallet_send.py", line 560, in run_test
                                       assert_fee_amount(testres["fees"]["base"], testres["vsize"], Decimal(0.0001))
                                     File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\util.py", line 46, in assert_fee_amount
                                       raise AssertionError("Fee of %s BTC too high! (Should be %s BTC)" % (str(fee), str(target_fee)))
                                   AssertionError: Fee of 0.00003160 BTC too high! (Should be 0.0000313 BTC)
```

**Review by luke-jr — CHANGES_REQUESTED** [review]
Seems like `-Werror` should simply always use `--enable-suppress-external-warnings`

And never enable `-Werror` for configure checks...

**Comment by hebasto** [comment]
Not able to continue to work on this PR (no access to macOS x86_64), and will be happy if someone grab it.

**Comment by MarcoFalke** [comment]
Looks like this had a tested ACK, so if we want it, it can be merged as-is, unless there are concerns with it.

**Comment by hebasto** [comment]
> Looks like this had a tested ACK, so if we want it, it can be merged as-is, unless there are concerns with it.

It requires rebasing, and @luke-jr's suggestion deserves testing.

**Comment by MarcoFalke** [comment]
Ah sorry, I missed the rebase label.

**Pull request closed without merging**
