### PR TITLE
test: wallet: add coverage for `-spendzeroconfchange` setting

### PR DESCRIPTION
**Pull request by theStack**
This PR adds missing test coverage for the `-spendzeroconfchange` setting (in particular the non-default case `=0`). Note that in contrast to the name, the setting does not only apply to change outputs, but in fact to _all_ unconfirmed outputs that we sent to ourselves, i.e. we can trigger the testing path simply with a single recipient address. The first commit removes the setting from the functional test mempool_limit.py, where it doesn't have any effect, since the test was changed to use MiniWallet in commit dddca3899c4738e512313a85aeb006310e34e31f.

### CODE REVIEW

**Review by brunoerg — COMMENTED** [review]
Concept ACK

**Comment by brunoerg** [comment]
I think we could also test the behavior of `getbalance` with `spendzeroconfchange`.

**Comment by theStack** [comment]
> I think we could also test the behavior of `getbalance` with `spendzeroconfchange`.

Good idea, done. Used `getbalances` rather than `getbalance` to check in which category unconfirmed self-sent coins fall (trusted or untrusted_pending) depending on the `-spendzeroconfchange` setting.

**Review by brunoerg — APPROVED** [review]
crACK 603d29519931e6ab6a58db09b9d3eb9b355fe566

Nice!

**Pull request merged**
