### PR TITLE
Enforcing consistency, 'gitian' to 'Gitian'

### PR DESCRIPTION
**Pull request by smatthewenglish**
There was once instance of 'gitian'. I changed it to 'Gitian' so that it would be consistent with all other instances in the file.

### CODE REVIEW

**Comment by paveljanik** [comment]
trivial ACK https://github.com/bitcoin/bitcoin/pull/9083/commits/66ca6cda4c67a6c279d086223b69f398dc140724

Please collect such fixes and submit them in one PR e.g. once a month or so.

**Comment by s-matthew-english** [comment]
I know what you mean. At the moment I'm trying to understand how the code works so I'm reading through all the comments, if I see something like that then I just quickly fix it and create a pull request so that I don't forget about it.

**Comment by paveljanik** [comment]
And you can as well, collect your fixes in some of your branches (so you do not forget about it) and then PR it at the end of month :-)

**Comment by s-matthew-english** [comment]
yeah, that makes sense. I'll do that. this is the first open source project I've contributed to so- I'm still kind of getting the hang of things. 

What do you think of my PR #9064?

**Comment by fanquake** [comment]
ACK 66ca6cd

**Comment by Leviathn** [comment]
Ack

**Comment by MarcoFalke** [comment]
Agree with @paveljanik. Please try to collect small fixes in separate commits/branches and then submit them in one pull request, rather than a separate commit/pull request for each single word typo-fix.

**Comment by s-matthew-english** [comment]
please forgive me if I was making too many pull requests for those small errors

in fact already I've been accumulating a new one, maybe I'll make it into a pull request at the end of the month or so?

**Comment by MarcoFalke** [comment]
@s-matthew-english Sounds good!

**Comment by MarcoFalke** [comment]
@s-matthew-english If you are looking for other fixes, there are still [some like this](https://github.com/bitcoin/bitcoin/pull/8680/files#r78133809).

**Comment by s-matthew-english** [comment]
@MarcoFalke ah- thank you for pointing that out :) 

Please forgive me is this is daft, but I'm having trouble determining what is exactly the change that needs fixing.

Is it to ensure that calls to the help command output this: `s/waitforblock/waitforblock <blockhash> <timeout>`?

**Comment by paveljanik** [comment]
@s-matthew-english See https://github.com/bitcoin/bitcoin/pull/9144

**Comment by s-matthew-english** [comment]
so then- I guess I can find all those instances by grepping for "request.fHelp" is it so?

**Pull request merged**
