### PR TITLE
refactor: minor whitespace fixups, s/const/constexpr/ and remove template (followup to #19845)

### PR DESCRIPTION
**Pull request by vasild**
Address suggestions:
https://github.com/bitcoin/bitcoin/pull/19845#discussion_r495486760
https://github.com/bitcoin/bitcoin/pull/19845#discussion_r495488051
https://github.com/bitcoin/bitcoin/pull/19845#discussion_r495730125

### CODE REVIEW

**Comment by vasild** [comment]
cc @hebasto

**Comment by hebasto** [comment]
Concept ACK, obviously :) Thanks @vasild  !

Mind also integrating https://github.com/bitcoin/bitcoin/pull/19845#discussion_r495730125 as that change was unneeded?

**Comment by vasild** [comment]
Well, I left it as is because

```cpp
template <typename E>
bool operator()(const E& e) const {
```

is more generic than

```cpp
bool operator()(const std::runtime_error& e) const {
```

both work now but the former would also work if the exception does not inherit `std::runtime_error`.

**Comment by hebasto** [comment]
I don't think the template function is required to make exception handling more generic for the following reasons:
- all custom types in the project inherit from `std::runtime_error`
- if this seems insufficient, the base `std::exception` type could be used

**Comment by ajtowns** [comment]
Please describe the actual changes in the pr title/description?

**Comment by fanquake** [comment]
@vasild could you follow up here with @hebasto and @ajtowns comments, as this is a fairly straight-forward change.

**Comment by vasild** [comment]
Done!

**Review by jonatack — COMMENTED** [review]
ACK b76317461e4664ba2d2d06c528a67d8718aa7c63

For the PR title, maybe `s/style/net, test/` per CONTRIBUTING.md. Feel free to ignore.

**Review by hebasto — APPROVED** [review]
ACK b76317461e4664ba2d2d06c528a67d8718aa7c63, I have reviewed the code and it looks OK, I agree it can be merged.

**Comment by vasild** [comment]
`./test/util/setup_common.h:166:10: note:   no known conversion for argument 1 from ‘const std::ios_base::failure’ to ‘const std::runtime_error&’` :bomb:

**Comment by jonatack** [comment]
Interesting. I compiled and ran the unit tests without warnings.

**Comment by rmtnong** [comment]
เมื่อ วันเสาร์ที่ 31 ตุลาคม ค.ศ. 2020, Hennadii Stepanov <
notifications@github.com> เขียนว่า:

**Comment by jonatack** [comment]
re-ACK 89836a8, built/ran unit tests with gcc debian 10.2.0-15, then broke a few v3 net_tests and checked the error reporting

**Comment by jonatack** [comment]
re-ACK 89836a8 change since previous review is replacing std::runtime_error with std::exception, built/ran unit tests with gcc debian 10.2.0-15, then broke a few v3 net_tests involving `BOOST_CHECK_EXCEPTION`, rebuilt, ran `src/test/test_bitcoin -t net_tests -l all` and checked the error reporting.

Change per `git diff b763174 89836a8` since previous review:
```diff
diff --git a/src/test/util/setup_common.h b/src/test/util/setup_common.h
index 33c2ea0028..1812ce1666 100644
--- a/src/test/util/setup_common.h
+++ b/src/test/util/setup_common.h
@@ -163,7 +163,7 @@ class HasReason
 {
 public:
     explicit HasReason(const std::string& reason) : m_reason(reason) {}
-    bool operator()(const std::runtime_error& e) const
+    bool operator()(const std::exception& e) const
     {
         return std::string(e.what()).find(m_reason) != std::string::npos;
     };
```

**Comment by hebasto** [comment]
re-ACK 89836a82eec63f93bbe6c3bd6a52be26e71ab54d

> `./test/util/setup_common.h:166:10: note: no known conversion for argument 1 from ‘const std::ios_base::failure’ to ‘const std::runtime_error&’` bomb
> 
> https://travis-ci.org/github/bitcoin/bitcoin/jobs/740417628#L2831

CentOS build uses pretty old gcc. Nice that CI caught that issue.

**Comment by rmtnong** [comment]
#outlook a { padding: 0; }
  .ReadMsgBody { width: 100%; }
  .ExternalClass { width: 100%; }
  .ExternalClass * { line-height:100%; }
  body { margin: 0; padding: 0; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; }
  table, td { border-collapse:collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; }
  img { border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none; -ms-interpolation-mode: bicubic; }
  p { display: block; margin: 13px 0; }



  @media only screen and (max-width:480px) {
    @-ms-viewport { width:320px; }
    @viewport { width:320px; }
  }






    
    

        @import url(https://d2yjfm58htokf8.cloudfront.net/static/fonts/averta-v2.css);

    
  
      *, *:before, *:after {
        box-sizing: border-box;
      }
          
      p {
        margin: 0 0 40px 0;
      }
      
      a {
        color: #00b9ff;
      }
      
      a.no-decoration {
        text-decoration: none;
      }
      
      .body-wrapper {
        background: #f2f5f7;
        padding: 16px;
      }
      
      .logo-wrapper {
        margin-bottom: 16px !important;
      }
      
      .content-wrapper {
        margin-bottom: 16px !important;
      }
      
      .footer-wrapper div {
        color: #37517e !important;
      }
      
      .footer-wrapper div a {
        color: #00b9ff !important;
      }
      
      .mt-0 {
        margin-top: 0 !important;
      }
      
      .mt-1 {
        margin-top: 16px !important;
      }
      
      .mt-2 {
        margin-top: 24px !important;
      }
      
      .mb-0 {
        margin-bottom: 0 !important;
      }
      
      .mb-1 {
        margin-bottom: 16px !important;
      }
      
      .mb-2 {
        margin-bottom: 24px !important;
      }
 
      .mr-0 {
        margin-right: 0 !important;
      }
      
      .mr-1 {
        margin-right: 16px !important;
      }
      
      .mr-2 {
        margin-right: 24px !important;
      }
      
      .ml-0 {
        margin-left: 0 !important;
      }
      
      .ml-1 {
        margin-left: 16px !important;
      }
      
      .ml-2 {
        margin-left: 24px !important;
      }
      
      .centered {
        text-align: center
      }
      
      .btn {
        box-sizing: border-box;
        display: inline-block;
        min-height: 36px;
        padding: 12px 24px;
        margin: 0 0 24px;
        font-size: 16px;
        font-weight: 600;
        line-height: 24px;
        text-align: center;
        white-space: nowrap;
        vertical-align: middle;
        cursor: pointer;
        border: 0;
        border-radius: 3px;
        color: #fff !important;
        background-color: #00b9ff;
        text-decoration: none;

        -webkit-transition: all .15s ease-in-out;
        -o-transition: all .15s ease-in-out;
        transition: all .15s ease-in-out;
      }
      
      .btn-full {
        width: 100%;
      }
      
      .btn:hover {
        background-color: #00a4df;
      }
      
      .btn:active {
        background-color: #008ec0;
      }
      
      .blue {
        color: #00b9ff;
      }
      
      @media screen and (min-width: 576px) and (max-width: 768px) {
        .body-wrapper {
          padding: 24px !important;
        }
        .logo-wrapper {
          margin-bottom: 24px !important;
        }
        .content-wrapper {
          margin-bottom: 24px !important;
        }
      }
      
      @media screen and (min-width: 768px) {
        .body-wrapper {
          padding: 24px 48px !important;
        }
        .logo-wrapper {
          margin-bottom: 24px !important;
        }
        .content-wrapper {
          margin-bottom: 48px !important;
        }
      }
      
      .mainCard .hero {
        color: #fff;
        font-size: 26px;
        font-weight: bold;
        margin-bottom: 24px;
      }
      
      .mainCard .hero .highlight {
        color: #00b9ff;
      }
      
      .mainCard p {
        color: #fff;
      }
      
      .title {
        font-size: 22px;
        font-weight: 600;
        color: #2f4366;
      }
      
      .subtitle {
        font-size: 16px;
        font-weight: 600;
        color: #2f4366;
      }
     
      
      
  
  .mainCard {
    background-color: #37517e !important;
  }


  .custom-message{
    background-color: #dbf4fe;
  }

  .custom-message p{
    padding: 24px;
    color: #37517e;
    margin-bottom: 0;
  }

  .custom-message-triangle {
    width: 0;
    height: 0;
    border-style: solid;
    border-width: 21px 20px 0;
    border-color: #dbf4fe transparent transparent;
    margin-left: auto;
    margin-right: auto;
  }

  .initials-circle {
    width: 40px;
    height: 40px;
    background-color: #f2f5f7;
    -moz-border-radius: 20px;
    -webkit-border-radius: 20px;
    border-radius: 20px;
    margin-left: auto;
    margin-right: auto;
    margin-top: 12px;
    margin-bottom: 40px;
    text-align: center;
    line-height: 40px;
  }

  .initials-circle table{
    font-size:16px;
    color:#37517e;
  }

     
  @media only screen and (min-width:480px) {
    .mj-column-per-100 { width:100%!important; }
  }



  
  
      
    
      
    
  
  
	
  
    Nonlaphan invited you to TransferWise.
  
  
    Thanks to Nonlaphan, we'll waive the fees on your first transfer up to 500 GBP. Moving forward, you’ll always get the best exchange rate out there.
  


  
    
      Use your discount
    
  
      Want to change what we get in touch about? Go to your Notification Settings.   We can’t receive replies to this email address. But if you’d like some support, please visit our Help Centre.This email was sent to you by TransferWise. By using our services, you agree to our customer agreements.

© TransferWise 2020. All rights reserved.
      zdtag-nr-contact-form-sent

**Review by theStack — APPROVED** [review]
ACK 89836a82eec63f93bbe6c3bd6a52be26e71ab54d

**Pull request merged**
