### PR TITLE
[rpc] throw JSONRPCError when utxo set can not be read

### LINKED ISSUE #7344: gettxoutsetinfo returns empty dict on Raspberry Pi 2
It takes from 5 (shortest) to almost 40 (longest) minutes for `bitcoin-cli gettxoutsetinfo` to return an *empty* dict. I noticed this first whilst configuring the Statoshi branch of Bitcoin Core, but went back to install Bitcoin Core (git clone -b v0.11.2 https://github.com/bitcoin/bitcoin.git) to find the same results.
```
20:10 pi@raspinode:~/bin/bitcoin.orig $ bitcoin-cli gettxoutsetinfo
{
}
20:12 pi@raspinode:~/bin/bitcoin.orig $ bitcoin-cli getinfo
{
    "version" : 110200,
    "protocolversion" : 70002,
    "blocks" : 393193,
    "timeoffset" : 0,
    "connections" : 12,
    "proxy" : "",
    "difficulty" : 113354299801.47113037,
    "testnet" : false,
    "relayfee" : 0.00005000,
    "errors" : ""
}
20:17 pi@raspinode:~/bin/bitcoin.orig $
```
Raspberry Pi 2 - 1GB memory - 4 core CPU 900MHz - Blockchain on SanDisk Ultra Android microSDXC 128GB up to 80 MB/Sec Class 10

All other RPC calls through bitcoin-cli are answered promptly and correctly.
See also issue on jlopp/statoshi https://github.com/jlopp/statoshi/issues/19#issuecomment-171350739

### PR DESCRIPTION
**Pull request by maflcko**
I think this closes #7344

### CODE REVIEW

**Comment by laanwj** [comment]
utACK

**Review by jonasschnelli — APPROVED** [review]
utACK fa05cfdf256f3bc13b89ea80231e342f4302d204

**Review by paveljanik — APPROVED** [review]
ACK https://github.com/bitcoin/bitcoin/pull/8832/commits/fa05cfdf256f3bc13b89ea80231e342f4302d204

**Review by dcousens — APPROVED** [review]

**Comment by laanwj** [comment]
This was backported in #8832, removing tag

**Pull request merged**
