### PR TITLE
wallet: Remove GetLegacyBalance

### PR DESCRIPTION
**Pull request by maflcko**
`GetLegacyBalance` returns arbitrarily different values than `GetBalance`, sometimes even negative balances

It is only used to throw a warning in some cases, so instead of fixing it, it should be safe to remove it (since the "balance check" is done by the wallet internally).

The first commit is a scripted-diff that does not change the `objdump` of `bitcoind` for me and seems like a nice cleanup to me.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
:egg: `eb98be266003faa9d42434961e9c28a975fc46d41d5ea76f01f1babcadc33c55`

**Comment by luke-jr** [comment]
`GetLegacyBalance` is the only one that returns the *correct* values... The newer stuff is still broken.

**Comment by MarcoFalke** [comment]
A negative balance can clearly not be correct

**Comment by practicalswift** [comment]
@MarcoFalke This PR looks a bit unfinished: the calculated `totalAmount` is never used after this change?

Can you describe the code path that will be taken that makes the `GetLegacyBalance` call technically redundant?

**Comment by luke-jr** [comment]
Negative balances can indeed be correct. Receives are only counted once they reach a certain confirmation level. But sends (including ones that use unconfirmed inputs) are always counted. So if you receive 50 BTC, and send 40 BTC, until the 50 BTC confirms, you have a balance of -40 BTC.

**Comment by MarcoFalke** [comment]
> Can you describe the code path that will be taken that makes the GetLegacyBalance call technically redundant?

It is practically redundant in that it may fail in cases where we'd later create the transaction because we have sufficient balance and it may not fail in cases where we are unable to create a transaction due to insufficient balance.

So the check is at best confusing. Definitely not enough reason to keep that code around in `sendmany`. Especially considering that none of the other RPCs make this check. Compare for example `sendtoaddress`.

**Comment by practicalswift** [comment]
@MarcoFalke 

The PR seems unfinished and should probably be marked WIP.

The `minconf` API argument passed by the user is being ignored after your change:

```
{"minconf", RPCArg::Type::NUM, /* default */ "1", 
 "Only use the balance confirmed at least this many times."},
```

Drop that argument?

Also `totalAmount` is calculated but not used.

TBH these kinds of things should really be detected automatically using compiler warnings or a linter before hitting review. Human review time is scarce.

**Comment by MarcoFalke** [comment]
Going to reopen later, maybe

**Comment by practicalswift** [comment]
@MarcoFalke What was the egg (🥚) + hash you posted initially about? :-)

**Comment by jnewbery** [comment]
Concept ACK

**Pull request closed without merging**
