### PR TITLE
change AC_PACKAGE_BUGREPORT from info@bitcoin.org to github issue tracker

### PR DESCRIPTION
**Pull request by jonasschnelli**
Mentioned by @laanwj:
http://bitcoinstats.com/irc/bitcoin-dev/logs/2015/05/02#l1430543664

I always thought this needs an update.

Details here:
http://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Initializing-configure.html

### CODE REVIEW

**Comment by jonasschnelli** [comment]
This is how it looks after this PR:
bildschirmfoto 2015-05-02 um 10 31 24

**Comment by luke-jr** [comment]
utACK

**Comment by jgarzik** [comment]
ut ACK

**Comment by fanquake** [comment]
ACK

**Comment by laanwj** [comment]
Thank you, yes that's much better
utACK

**Pull request merged**
