### PR TITLE
Upgrade mac_alias to 2.0.7

### PR DESCRIPTION
**Pull request by droark**
The patch Bitcoin Core has been maintaining for mac_alias was pulled by the mac_alias maintainer in commit 4f31cb084c1c6a8626128b0b00842020b6db9037. Delete the patch and remove the patch from the depends system.

Note that this PR won't be complete until a new version of mac_alias containing the patch has been released, and the depends system is updated to reflect the new version.

### CODE REVIEW

**Comment by droark** [comment]
Just for reference, [here's the original PR for the mac_alias patch](https://github.com/al45tair/mac_alias/pull/3).

**Comment by thijstriemstra** [comment]
2.0.7 has been [released](https://github.com/al45tair/mac_alias/pull/3#issuecomment-365291516).

**Comment by droark** [comment]
tACK

Added a commit upgrading mac_alias to 2.0.7 and did `make deploy` on my Macbook Pro. The resultant DMG file allowed me to place Core in /Applications. Core runs fine.

**Comment by jonasschnelli** [comment]
Tested ACK via Gitian Build:
https://bitcoin.jonasschnelli.ch/build/499

**Comment by laanwj** [comment]
Looks good to me, @theuni might want to sign off on this because it's a depends change.

**Comment by fanquake** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/12417/commits/fc1bfcf9fd2c24846a9f9caa42f5370f192c3d40

@droark Could you post a screenshot of the out of place icons for reference?

**Review by theuni — APPROVED** [review]
utACK fc1bfcf9fd2c24846a9f9caa42f5370f192c3d40. Thanks!

**Comment by droark** [comment]
Thanks, everyone!

@fanquake - Here you go.

image

**Comment by theuni** [comment]
@droark You just have hidden files showing. That's normal.

**Comment by droark** [comment]
@theuni - Oh no, I understand the hidden folders. :) I just seemed to recall some issue/PR from awhile back where something similar was discussed, and how the macOS builds put the icons in odd places. I thought it had been resolved? I can't remember where I saw all this, though, and I could be wrong. Better safe than sorry!

**Comment by thijstriemstra** [comment]
@droark what version of macOS are you using?

**Comment by droark** [comment]
@thijstriemstra - 10.13.3.

**Review by fanquake — APPROVED** [review]
utACK fc1bfcf

**Pull request merged**
