### PR TITLE
wallet: rm unused LegacyScriptPubKeyMan& spk_man

### PR DESCRIPTION
**Pull request by jonatack**
Follow-up to #17300 "LegacyScriptPubKeyMan code cleanups" and https://github.com/bitcoin/bitcoin/pull/17300#issuecomment-548747261.

### CODE REVIEW

**Comment by jonatack** [comment]
Not sure if these should be removed or documented.

**Comment by ryanofsky** [comment]
This PR as of 074405ad1ded63d1ba83518f458fde61cfd220f5 isn't really doing the right thing. The rpcdump methods are supposed to trigger "This type of wallet does not support this command" errors when called on descriptor wallets where `CWallet::GetLegacyScriptPubKeyMan` returns null (in the future after 4d0e6f063e34d3869f89d410ccdc4b6255a00150 from #17621).

To clean this up I would rename the rpcdump function `GetLegacyScriptPubKeyMan` to `EnsureLegacyScriptPubKeyMan` and keep calling it even when the returned reference is unused, just deleting the unused rpc_man variables, but not the function calls.

Also, for more cleanup I would move `EnsureLegacyScriptPubKeyMan` to `rpcwallet.h` / `rpcwallet.cpp` and start calling it from the other two rpc methods there that throw "This type of wallet does not support this command" errors.

**Comment by jonatack** [comment]
Thank you @ryanofsky for your feedback. Will do.

**Comment by laanwj** [comment]
> This PR as of 074405a isn't really doing the right thing.

FWIW this is exactly what I warned about in https://github.com/bitcoin/bitcoin/pull/17300#issuecomment-548747261 :smile: 
But yes, might be better to just wait for @ryanofsky's follow up on this.

**Comment by jonatack** [comment]
Heh, I suspected as much. Closing rather than following up, then.

**Pull request closed without merging**
