### PR TITLE
Bugfix: RPC: Check for blank rpcauth on a per-param basis

### PR DESCRIPTION
**Pull request by luke-jr**
Without this, a blank rpcauth will error if there is a non-blank following it, and a non-blank rpcauth will get ignored if the last one is blank

Includes test updates to detect issues

(It might make sense to support `-norpcauth`/`-rpcauth=0` to disable all defined `-rpcauth` options, but that isn't currently supported, so out of scope here)

### CODE REVIEW

**Comment by luke-jr** [comment]
I'm not entirely sure what the expected behaviour here is...

**Comment by luke-jr** [comment]
Not sure what more work there is to be done here. The current behaviour is broken

**Comment by ryanofsky** [comment]
> So unless there is a good reason to support per-param blank auths, and discard the previous behavior, I'd say to not change it.

IIUC the previous behavior just didn't make any sense. I made a similar bugfix






, and this PR removes support for blank `-rpcauth=""` settings so they explicitly cause an error. It would be good if it added a test for this behavior, which I think it does not as of 6b79de4f9aed365adda0a99d6522e83ccb6c593f.













> 
> When proposing a change, the burden to motivate and explain the change is on the pull request author. Simply making a change, then stating that you don't know the expected behavior ([#29141 (comment)](https://github.com/bitcoin/bitcoin/pull/29141#issuecomment-1868353002)), while claiming your fix is a "bugfix" does not seem consequential to me.

**Comment by fanquake** [comment]
See #30401.

**Pull request closed without merging**
