### PR TITLE
qa: Make tmpdir option an absolute path, misc cleanup

### PR DESCRIPTION
**Pull request by maflcko**
This should fix issues with the multiwallet test and its symlinks
when the tmpdir is a relative path.

Rather than fixing os.symlink to work with paths relative to a
directory descriptor, which does not work on Windows, normalize
the path instead.

### CODE REVIEW

**Comment by laanwj** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/11472/commits/fa949d1bd6710358626eb70a47dfa101c0a60da2, storing paths as absolute is always a good precaution to prevent unexpected behavior.

**Comment by promag** [comment]
utACK.

Do the same for `cachedir`?

**Comment by laanwj** [comment]
> Should the same applies to cachedir?

I think that makes sense (not sure it's in scope of this issue though).

**Comment by jnewbery** [comment]
Tested ACK fa949d1bd6710358626eb70a47dfa101c0a60da2.

:+1: for the same treatment to cachedir

**Comment by promag** [comment]
re-utACK fafa003.

**Comment by MeshCollider** [comment]
utACK https://github.com/bitcoin/bitcoin/commit/fafa0039708e15d1067be091b2bfc10195afa480

**Pull request merged**
