### PR TITLE
Remove size and position saving in the about window

### PR DESCRIPTION
**Pull request by ghost**
Something went screwy with the old request after I accidentally cross-synced forks/branches so this is a continuation of https://github.com/bitcoin/bitcoin/pull/5772, albeit with a clearer title. 

The base commit for this PR includes the changes from https://github.com/jonasschnelli/bitcoin/commit/a16b79b16d9f13f13f13960e858d9416694a2ee4 and I have made sure to clarify the title both on the commit and the PR per a suggestion to do so.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
ACK

Next time i first would try to `git push --force` to your exiting PR branch (#5772). When there is a commit mess, just create a new local branch and overwrite the remote one by `git push --force <remote> localbranch:remotebranch` (or similar; not tested). This fixed my issues always.

**Comment by fanquake** [comment]
utACK

**Comment by L-Cranston-Shadow** [comment]
@jonasschnelli I did a hard reset and then a force push, the reset wiped me back to the source master branch and the push made the server side repository think that I removed all of the commits which triggered the issue closing. As far as I can tell, at that point it was game over short of the github admins getting involved as it wouldn't let me open with new commits.

**Comment by L-Cranston-Shadow** [comment]
I tried for a few hours to fix the phantom commits, when I get back online I'll give it another try but in the meantime just ignore them. The two files that were actually changed were utilitydialog.cpp and utilitydialog.h, although one of those included an unrelated change involving the new logo in the about window.

**Comment by jonasschnelli** [comment]
Do you plan to update/fix this?
Otherwise please close this pull. Thanks.

**Comment by L-Cranston-Shadow** [comment]
@jonaschnelli, I will fix it today as soon as I get back to my computer. Sorry for the delay.

**Comment by laanwj** [comment]
> although one of those included an unrelated change involving the new logo in the about window.

I noticed this during review. What is the motivation for this change?

**Comment by laanwj** [comment]
Also, as I asked before, but didn't get an answer: if we remove it from the about box, do we need to keep shape and position saving for the help message window? It doesn't seem necessary to me. I expect that the help message will be something that people occasionally open, not keep open during their session, so just popping it up in a sensible place would be good enough.

**Comment by L-Cranston-Shadow** [comment]
@laanwj, the unrelated change is an artifact of going back to a different version of the file during my multiple attempts to undo the mess that became of this PR as well as the previous one. If it's an issue then I'll go in and try to undo it but since I apparently can't rebase to the current version without utterly breaking the PR, I'll have to do it by hand.

In regards to your question, sorry that you didn't get a reply, I didn't see the question before. My understanding, such as it is, is that this change will only affect the about window, not the help window.

**Comment by laanwj** [comment]
Closing in favor of #5830

**Pull request closed without merging**
