### PR TITLE
lint: Refactor lint checks to reuse exclusion logic; Support running individual lint checks in lint runner

### PR DESCRIPTION
**Pull request by davidgumberg**
Motivated by a [comment](https://github.com/bitcoin/bitcoin/pull/29479#pullrequestreview-1957109397) in #29479, this draft PR refactors the lint runner into multiple modules, and refactors a few of the python linters to reuse common file excluding logic.

The include guards lint now prints all missing include guards before exiting, and all of the rewritten linters now exclude all subtrees, including `crypto/caes`.

The lint runner now supports running individual linters by passing `--lint=LINT_CHECK_TO_RUN` to the lint runner. If using `cargo run` arguments can be passed e.g.:
```sh
cd test/lint/test_runner && cargo run -- --lint=doc --lint=includes
```
 I can see reasons why the benefits of this PR might be outweighed by the downsides so I'm just publishing this as a draft to explore if further rewriting/refactoring of the lint suite in rust is desirable, and if so, what the best approach is.

### CODE REVIEW

**Comment by fjahr** [comment]
I think this needs a conceptual discussion if we want to move all Python code to Rust eventually.

**Comment by unicornsavior42** [comment]
Unicornsavior42

**Comment by unicornsavior42** [comment]
Unicornsavior42

**Comment by dergoegge** [comment]
Concept ACK

**Comment by fjahr** [comment]
> I don't think moving all Python code to Rust makes sense. Simply due to the reason that reviewing such a large change is close to impossible.

The tests are already split up into separate files and can be ported one at a time. We could pull in `rust_bitcoin` to get access to all the low-level stuff they have already written. It is a big project but certainly doable if Rust is considered a big enough upgrade. If it's just a minor improvement I don't think it's worth alienating the developers that don't know Rust from contributing to the linters.

**Comment by fjahr** [comment]
Previously the linters were separated into their own files and could be called separately as well. This is now moving to one big monolytic program, which is not great. The `lint_all` function also doesn't actually run all linters anymore with this change, it only runs the python ones, not the rewritten ones. So I don't think the CI is running these linters at all right now?

> Sure, but I think the functional test framework itself is already 10k lines of code. Having to support two test frameworks that are supposed to behave similar or identical may already be too difficult.

If such a rewrite is not worth it on a big scale we should also not do it on a small scale. The value and effort scale up proportionally with the size of the change. And if we are concerned about resources I think we also should do this here either because a small distraction is a distraction as well.

**Comment by davidgumberg** [comment]
I've substantially revised this PR to address @fjahr's feedback that the rust lint runner monofile was getting too big, and that it doesn't support running individual tests (https://github.com/bitcoin/bitcoin/pull/29744#issuecomment-2022796657) and @maflcko's suggestion to include `test/lint/lint-locale-dependence.py` and `test/lint/lint-python-utf8-encoding.py` (https://github.com/bitcoin/bitcoin/pull/29744#issuecomment-2022606314).

I do not feel confident in regex, and had to do some tricky things to avoid importing the rust regex crate, so I ask any reviewers to give special care to all of the regex segments, especially the regex pattern in `fn get_locale_dependence_regexp()`, I really appreciate your time and feedback!


I feel that whether the added review and complexity burden of the changes here and, broadly, of having  *another* language for everyone to be knowledgeable of outweighs the benefits remains an open question, (I am concept +0) it is possible for further rewriting of the lint suite to be worthwhile without it being the case that moving **all** Python code to Rust should be a good idea.

**Comment by davidgumberg** [comment]
> Are you still working on this?

Yes, I was just waiting to see if there was any other feedback before putting all of the linter code back into a single file. 

I think a lot of the reason for the individual lint checks being placed in separate files previously was so that they could be run individually, but I feel that a single file that contains both the lint checks and the lint runner is a bit clunky.

I would rather leave splitting up `main.rs` to the tastes of a future PR, unless someone has a strong opinion about how the files should be laid out.

**Comment by fjahr** [comment]
Concept NACK

As I have said before, I think there needs to be a discussion about using more Rust just for the sake of using more Rust in the project. The only motivation given so far is that @maflcko said that it could be done. There is no benefit to doing this otherwise apparently and the biggest effect I see is that there will be fewer people able to contribute to that part of the code base. And this change alone will also take up a lot of review effort so it appears to be a clear negative, at least in the short to mid-term.

**Comment by fjahr** [comment]
> Not sure where you get that from

"an alternative might be to rewrite the 3 lint checks to rust" https://github.com/bitcoin/bitcoin/pull/29479#pullrequestreview-1957109397 That is what @davidgumberg has given as the motivation in his description. It does not matter what you have said in other places because I have not been talking about that. I only talked about your comment that the author took as the motivation for this PR.

**Comment by fjahr** [comment]
> That comment says `so that they can use the already existing function` as the motivation. (This is the issue that was attempted to be solved and why the other pull request was created in the first place). 

Right, and that original PR was merged so that part does not apply here anymore, still this PR is still open.

> Re-reading my comment, I don't get the impression that it said "using more Rust just for the sake of using more Rust in the project can be done".

Well, my impression is that the author got that impression and opened this PR because of it.

**Comment by fjahr** [comment]
>  For example, crypto/ctaes is a subtree, but test/lint/lint_ignore_dirs.py does not list it. Also, test/lint/lint-locale-dependence.py and test/lint/lint-python-utf8-encoding.py don't use test/lint/lint_ignore_dirs.py.

Right, these are behavior changes that I did not see as part of the motivation of the original PR, as the title says it was a refactor. So I don't think this is something that was missed, it was just not the goal. It should be made more clear that this is the main motivation of this PR, to improve exclusion of subtrees. It should not be called a refactor in the title as it is now.

**Comment by davidgumberg** [comment]
@maflcko @fjahr Thank you for the feedback, sorry for the confusion on this PR. I've opened https://github.com/bitcoin/bitcoin/pull/29965

**Pull request closed without merging**
