### PR TITLE
wallet: Fix typo in comments; Simplify assert

### PR DESCRIPTION
**Pull request by maflcko**
Follow up to https://github.com/bitcoin/bitcoin/pull/19046#discussion_r443783101 and https://github.com/bitcoin/bitcoin/pull/19046#discussion_r443793690

### CODE REVIEW

**Comment by meshcollider** [comment]
ACK

**Comment by practicalswift** [comment]
ACK facd7dd3d1f9d51e1133974ff69eeb48f5ae282b

Getting rid of tpyos once in a while is good project hygiene :)

**Review by jonatack — COMMENTED** [review]
ACK facd7dd3d1f9d51e1133974ff69eeb48f5ae282b

**Review by hebasto — APPROVED** [review]
ACK facd7dd3d1f9d51e1133974ff69eeb48f5ae282b, spelling verified with `test/lint/lint-spelling.sh`: all remaining warnings are false positive.

**Review by meshcollider — COMMENTED** [review]
Code review & functional test run ACK facd7dd3d1f9d51e1133974ff69eeb48f5ae282b

**Pull request merged**
