### PR TITLE
Remove obsolete NODISCARD ifdef forest. Use [[nodiscard]] (C++17). 

### PR DESCRIPTION
**Pull request by practicalswift**
Remove obsolete `NODISCARD` `ifdef` forest. Use `[[nodiscard]]` (C++17).

### CODE REVIEW

**Comment by fanquake** [comment]
Now that the ifdef forest is removed, is there an advantage to redefining `[[nodiscard]]` as `NODISCARD` rather than just using `[[nodiscard]]` directly where applicable?

**Comment by practicalswift** [comment]
@fanquake No, not at all: I just wanted to keep the diff down. But you have a good point: using `[[nodiscard]]` directly is certainly nicer and more idiomatic, so it is probably worth the one time cost of a few extra lines of diff. Now doing that using a scripted-diff :)

**Review by theStack — APPROVED** [review]
ACK 79bff8e48aca961ec271b0d592aca9278b981e2f
Checked that all instances of NODISCARD were tackled.
It's always nice to see when old cruft is removed 👍

**Review by fanquake — APPROVED** [review]
ACK 79bff8e48aca961ec271b0d592aca9278b981e2f

**Pull request merged**
