### PR TITLE
[26.x] final changes for 26.1

### PR DESCRIPTION
**Pull request by glozow**
Final changes for `v26.1`.

Bins for rc2 have been available for 10 days and I haven't seen any bug reports or new things to add.
Includes #29610 backport for the CI, which has no effect on what goes into the release.
Website PR: https://github.com/bitcoin-core/bitcoincore.org/pull/1009

### CODE REVIEW

**Comment by glozow** [comment]
Added a #29610 backport for the CI

**Review by hebasto — APPROVED** [review]
ACK cc0553d0d666a6ad5cdd3b88ddb06af883b6d7a1.

**Review by fanquake — APPROVED** [review]
ACK cc0553d0d666a6ad5cdd3b88ddb06af883b6d7a1

**Review by stickies-v — APPROVED** [review]
ACK cc0553d0d666a6ad5cdd3b88ddb06af883b6d7a1 (modulo CI passing)

Verified that:
- backports are clean
- release notes and contributors list match actually merged PRs as per `git log v26.0..`
- new manpages match my output

**Comment by Saeed149** [comment]
Hi

**Pull request merged**
