### PR TITLE
Predeclare PrecomputedTransactionData as struct

### PR DESCRIPTION
**Pull request by sipa**

### CODE REVIEW

**Comment by sipa** [comment]
As pointed out by @paveljanik.

**Comment by laanwj** [comment]
Yes, makes sense to have this consistent, utACK https://github.com/bitcoin/bitcoin/pull/8651/commits/4424af5190f11996e7970064b4f6553ba7cd1f9e

**Comment by fanquake** [comment]
utACK 4424af5

**Comment by paveljanik** [comment]
Typo in commit message (sturct). Change itself ACK.

**Comment by btcdrak** [comment]
utACK 442af5

**Comment by theuni** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/8651/commits/4424af5190f11996e7970064b4f6553ba7cd1f9e, fixes current noisy build.

**Comment by gmaxwell** [comment]
ACK.

**Comment by jonasschnelli** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/8651/commits/4424af5190f11996e7970064b4f6553ba7cd1f9e

**Comment by sipa** [comment]
Marking as needs backport, as that will be the case as soon as #8524 is backported.

**Pull request merged**
