### PR TITLE
Reinitialize state in between individual unit tests.

### PR DESCRIPTION
**Pull request by sipa**

### CODE REVIEW

**Comment by sipa** [comment]
Tested with valgrind: zero memory leaks in test_bitcoin.

**Comment by sipa** [comment]
@gavinandresen ping

**Comment by gavinandresen** [comment]
Code review ACK-- very nice!

I'll re-implement the #5835 unit test on top of this after lunch, to test.

**Comment by gavinandresen** [comment]
ACK. Tested by reimplementing unit test of #5835 with a REGTEST-mode 100-block chain.

**Comment by laanwj** [comment]
utACK

**Pull request merged**
