### PR TITLE
ci: Make ci system read-only on the git work tree

### LINKED ISSUE #17372: Improve Running CI Locally
One issue that can come up when running CI locally is that docker links directly to the current working directory. This has two unsavory side effects:

1) When docker writes the files, it writes them as root, preventing local building 
2) It blows away your current build

### PR DESCRIPTION
**Pull request by maflcko**
Running the ci completely in a docker, without leaving any traces on the host system is not possible right now because the ccache and depends dir needs to be propagated back and picked up by the host for caching.

Fixes #17372

### CODE REVIEW

**Comment by JeremyRubin** [comment]
Concept Ack!

**Comment by laanwj** [comment]
I know nothing about docker but Concept ACK, making things that can be made read-only read-only tends to be a good idea both for determinism and to avoid build steps generating clutter in unexpected places.

**Comment by MarcoFalke** [comment]
This should be easy to review. All it does it add some `DOCKER_EXEC`, which means "execute everything that follows in this line in our docker thing". Also, it mounts the source dir readonly into the docker.

**Comment by laanwj** [comment]
@JeremyRubin you brought this up, can you please give a tested ACK?

**Comment by MarcoFalke** [comment]
It was on my list of thing to improve either way. A code review should be sufficient, it is really straightforward.

**Comment by JeremyRubin** [comment]
Testing now...

Looks like you still need to run a make distclean before running? Would there be any reason to not have travis (now that it's RO on host) run make distclean first in case it's a dirty dir?

**Comment by JeremyRubin** [comment]
tested ACK fa7523d3aa75b0266015af59901c2397b52265b5

Ran `make distclean` and `FILE_ENV=ci/test/00_setup_env_amd64_trusty.sh ./ci/test_run_all.sh`

and was able to re-run

`./autogen.sh && ./configure && make` without hitting permissions errors.


Would prefer, as noted, if the distclean could happen in the copied dir.

**Comment by MarcoFalke** [comment]
Thanks for testing. I've merged this and left the suggestion as a follow up, see #17544.

**Pull request merged**
