### PR TITLE
[0.11] Important backports for 0.11.3 (updated to v0.12.0)

### PR DESCRIPTION
**Pull request by luke-jr**
These seem fairly important even for a softfork-deployment 0.11.3.

### CODE REVIEW

**Comment by btcdrak** [comment]
Backport of #6978 and #7092

**Comment by laanwj** [comment]
utACK

**Comment by sipa** [comment]
Why the merge commit?

**Comment by luke-jr** [comment]
Cleaner grouping of the two related commits together.

**Pull request merged**
