### PR TITLE
travis: Check that ~/.bitcoin is never created

### PR DESCRIPTION
**Pull request by maflcko**

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Travis failure:

```
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/test/functional/feature_config_args.py", line 39, in run_test

    self.nodes[0].assert_start_raises_init_error(['-conf=' + conf_file], 'Error reading configuration file: specified data directory "' + new_data_dir + '" does not exist.')

  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_node.py", line 266, in assert_start_raises_init_error

    'Expected message "{}" does not fully match stderr:\n"{}"'.format(expected_msg, stderr))

  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_node.py", line 108, in _raise_assertion_error

    raise AssertionError(self._node_msg(msg))

AssertionError: [node 0] Expected message "Error reading configuration file: specified data directory "/tmp/bitcoin_test_runner_20180717_122100/feature_config_args_1/node0/newdatadir" does not exist." does not fully match stderr:

"************************

EXCEPTION: N5boost10filesystem16filesystem_errorE       

boost::filesystem::create_directory: File exists: "/root/.bitcoin"       

bitcoin in AppInit()

**Comment by MarcoFalke** [comment]
I have no idea how to fix the broken functional test cross platform without removing it.

Closing as "up for grabs".

**Comment by laanwj** [comment]
Let's remove it then. I prefer having this test, TBH.

**Comment by laanwj** [comment]
utACK fabe28a0cdcfa13e0e595a0905e3642a960d3077

**Pull request merged**
