### PR TITLE
Fix mistakenly swapped "previous" and "current" lock orders

### PR DESCRIPTION
**Pull request by hebasto**
In master (8ef15e8a86038225afef2487ca23abc10ca5dffa) the "previous" and "current" lock orders are mistakenly swapped.

This PR:
- fixes printed lock orders
- improves the `sync_tests` unit test
- makes the "detected inconsistent lock order" error message pointing to the lock location rather `tfm::format()` location.

Debugger output example with this PR (with modified code, of course):
```
2020-06-22T15:46:56Z [msghand] POTENTIAL DEADLOCK DETECTED
2020-06-22T15:46:56Z [msghand] Previous lock order was:
2020-06-22T15:46:56Z [msghand]  (2) 'cs_main' in net_processing.cpp:2545 (in thread 'msghand')
2020-06-22T15:46:56Z [msghand]  (1) 'g_cs_orphans' in net_processing.cpp:1400 (in thread 'msghand')
2020-06-22T15:46:56Z [msghand] Current lock order is:
2020-06-22T15:46:56Z [msghand]  (1) 'g_cs_orphans' in net_processing.cpp:2816 (in thread 'msghand')
2020-06-22T15:46:56Z [msghand]  (2) 'cs_main' in net_processing.cpp:2816 (in thread 'msghand')
Assertion failed: detected inconsistent lock order for 'cs_main' in net_processing.cpp:2816 (in thread 'msghand'), details in debug log.
Process 131393 stopped
* thread #15, name = 'b-msghand', stop reason = signal SIGABRT
    frame #0: 0x00007ffff775c18b libc.so.6`__GI_raise(sig=2) at raise.c:51:1
(lldb) bt
* thread #15, name = 'b-msghand', stop reason = signal SIGABRT
  * frame #0: 0x00007ffff775c18b libc.so.6`__GI_raise(sig=2) at raise.c:51:1
    frame #1: 0x00007ffff773b859 libc.so.6`__GI_abort at abort.c:79:7
    frame #2: 0x0000555555e5b196 bitcoind`(anonymous namespace)::potential_deadlock_detected(mismatch=0x00007fff99ff6f30, s1=size=2, s2=size=2, lock_location=0x00007fff99ff7010) at sync.cpp:134:9
    frame #3: 0x0000555555e5a1b1 bitcoind`(anonymous namespace)::push_lock(c=0x0000555556379220, locklocation=0x00007fff99ff7010) at sync.cpp:158:13
    frame #4: 0x0000555555e59e8a bitcoind`EnterCritical(pszName="cs_main", pszFile="net_processing.cpp", nLine=2816, cs=0x0000555556379220, fTry=false) at sync.cpp:177:5
    frame #5: 0x00005555555b0500 bitcoind`UniqueLock<AnnotatedMixin<std::recursive_mutex>, std::unique_lock<std::recursive_mutex> >::Enter(this=0x00007fff99ff8c20, pszName="cs_main", pszFile="net_processing.cpp", nLine=2816) at sync.h:134:9
    frame #6: 0x00005555555b017f bitcoind`UniqueLock<AnnotatedMixin<std::recursive_mutex>, std::unique_lock<std::recursive_mutex> >::UniqueLock(this=0x00007fff99ff8c20, mutexIn=0x0000555556379220, pszName="cs_main", pszFile="net_processing.cpp", nLine=2816, fTry=false) at sync.h:160:13
    frame #7: 0x00005555556aa57e bitcoind`ProcessMessage(pfrom=0x00007fff90001180, msg_type=error: summary string parsing error, vRecv=0x00007fff9c005ac0, nTimeReceived=1592840815980751, chainparams=0x00005555564b7110, chainman=0x0000555556380880, mempool=0x0000555556380ae0, connman=0x000055555657aa20, banman=0x00005555565167b0, interruptMsgProc=0x00005555565cae90) at net_processing.cpp:2816:9
```

### CODE REVIEW

**Comment by laanwj** [comment]
So to be clear: this fixes *reporting* of lock orders, not the lock orders themselves?

**Comment by hebasto** [comment]
@laanwj 
> So to be clear: this fixes _reporting_ of lock orders (with `DEBUG_LOCKORDER`), not the lock orders themselves?

Yes. You are correct.

**Comment by hebasto** [comment]
Updated fdd1d7718596d1dbbb5fddf254151be84ed1c8dd -> 0ecff9dd3418e8c18fa423ba53e9cab1df8be553 ([pr19353.01](https://github.com/hebasto/bitcoin/commits/pr19353.01) -> [pr19353.02](https://github.com/hebasto/bitcoin/commits/pr19353.02), [diff](https://github.com/hebasto/bitcoin/compare/pr19353.01..pr19353.02)):

- addressed @vasild's [comment](https://github.com/bitcoin/bitcoin/pull/19353#issuecomment-649407194):
> Feel free to simplify as follows, there is no need to pass the lock location as an additional argument to `potential_deadlock_detected()` because it is always the last element in the second stack `s2`

**Review by vasild — APPROVED** [review]
ACK 0ecff9dd

**Comment by hebasto** [comment]
@fanquake Mind looking into this PR?

**Comment by laanwj** [comment]
ACK 0ecff9dd3418e8c18fa423ba53e9cab1df8be553

**Pull request merged**
