### PR TITLE
wallet: Add key generation type

### PR DESCRIPTION
**Pull request by luke-jr**
Continuing #5916 by adding backward compatibility with existing wallets

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Hmm... we never have deployed #5916 (I guess you did in your custom distribution?). This would mean 104ab313baeac2f909ce1fb10fe8562327b35e01 would address a feature-compatibility between third party distribution.
Okay for me but results in some ugly migration code.

My preferred solution would be:
  * a) 104ab313baeac2f909ce1fb10fe8562327b35e01 must only be included in your custom distribution (if people swap wallet.dat from your fork to Core they might need to manually migrate first)
  * b) If a) is problematic, keep the 8BIT bitfield and merge #5916 (which should be sufficient IMO).

PR nit: `s/FEATURE_KEYFLAGS_OLD/FEATURE_KEYFLAGS_8BIT/` , `s/VERSION_SUPPORT_FLAGS_OLD/VERSION_SUPPORT_FLAGS_8BIT/`

**Comment by luke-jr** [comment]
I called it "OLD" rather than "8BIT" because there's a bitshift involved.

Any idea what's up with Travis's Mac build? :/

**Comment by laanwj** [comment]
I'd prefer to not include migration code for something that we never deployed.
You can include that in your own distribution, of course.

**Comment by luke-jr** [comment]
Superceded by #8471

**Pull request closed without merging**
