### PR TITLE
qt: Update translation source file

### PR DESCRIPTION
**Pull request by hebasto**
As the part of the v23.0 [release process](https://github.com/bitcoin/bitcoin/issues/22969) this PR updates translation source file, `src/qt/locale/bitcoin_en.xlf`.

The following changes are reflected in this PR:
- small string changes from bitcoin-core/gui#509
- internal technical details from bitcoin/bitcoin#22151

### CODE REVIEW

**Comment by hebasto** [comment]
@laanwj 

I'll be happy to rebase this PR on top of the #24367, if the latter will get merged soon :)

**Comment by laanwj** [comment]
> I'll be happy to rebase this PR on top of the https://github.com/bitcoin/bitcoin/pull/24367, if the latter will get merged soon :)

Yes let's update this one more time.

**Comment by hebasto** [comment]
> > I'll be happy to rebase this PR on top of the #24367, if the latter will get merged soon :)
> 
> Yes let's update this one more time.

Done.

**Comment by laanwj** [comment]
ACK c5158290aff5d5e38d351c4f77340f9b17f44cb4
Checked that `make translate` gives the same output.

**Pull request merged**
