### PR TITLE
wallet: Remove -zapwallettxes

### PR DESCRIPTION
**Pull request by achow101**
It's not clear what use there is to keeping `-zapwallettxes` given that it's intended usage has been superseded by `abandontransaction`. So this removes it outright.

Alternative to #19700

### CODE REVIEW

**Comment by ryanofsky** [comment]
This seems reasonable if `abandontransaction` is a good alternative. I was also wondering if -zapwallettxes is fully working because it loops over m_spk_managers on the dummy wallet without calling SetupLegacyScriptPubKeyMan first

**Comment by achow101** [comment]
> I was also wondering if -zapwallettxes is fully working because it loops over m_spk_managers on the dummy wallet without calling SetupLegacyScriptPubKeyMan first

It looks like that's not even a reachable code path as `WalletBatch::ZapWalletTx` can't return `DBErrors::NEED_REWRITE`.

**Comment by laanwj** [comment]
Concept ACK

Removing all transactions from the wallet a sledge-hammer option. If there is any need for this it should be the wallet maintenance tool. But if its use is fully replaced by `abandontransaction` well, better to get rid of it.

If we do this, please keep the option *as hidden option* and exit with an error explaining to use `abandontransaction` if it is passed. People might find this option documented in old guides and such, it can be somewhat frustrating if options just disappear.

**Comment by laanwj** [comment]
FWIW I asked on [twitter](https://twitter.com/orionwl/status/1291655348181401601) and [mastodon](https://x0f.org/@orionwl/104647207101194527) what people's uses are with this option. Nothing really surprising there. No one is screaming to keep it. @luke-jr mentions something about a RBF override for `abandontranscation` that would be a remaining use case for this option.

**Comment by achow101** [comment]
> @luke-jr mentions something about a RBF override for `abandontranscation` that would be a remaining use case for this option.

To forcibly remove a particular transaction, people can use `removeprunedfunds`. It's intended use is for pruned wallets, but the RPC doesn't check for that and just removes the given transaction regardless. So if `abandontransaction` doesn't work, then `removeprunedfunds` will.

**Comment by meshcollider** [comment]
I agree entirely with @laanwj and prefer this over #19700. I see no point in keeping this in either the wallet tool or the RPC.

**Comment by fanquake** [comment]
Concept ACK

**Comment by fjahr** [comment]
Concept ACK

**Comment by laanwj** [comment]
Let's move forward with this. I think we can just remove this. I received no strong disagreements on my twitter/mastodon posts.

We can always add it back (to the wallet tool) if we receive reports of people missing it.

**Comment by practicalswift** [comment]
Concept ACK

Removing likely broken likely unused options make perfect sense :)

Also: +6 −182 gives a warm fuzzy feeling.

**Comment by laanwj** [comment]
Code review ACK 6738e3457824871c577bcdeb95bac599a3e09428

**Comment by practicalswift** [comment]
ACK 6738e3457824871c577bcdeb95bac599a3e09428 -- patch looks correct

Restarted Travis to get rid of timeout

**Comment by fanquake** [comment]
Looks good, but there's still `DBErrors ZapWalletTx(std::list<CWalletTx>& vWtx);` in [wallet.h](https://github.com/bitcoin/bitcoin/blob/21eda43cdea808335385af5c35f3baa77239749c/src/wallet/wallet.h#L1078) and [walletdb.h](https://github.com/bitcoin/bitcoin/blob/21eda43cdea808335385af5c35f3baa77239749c/src/wallet/walletdb.h#L260).

Can you also add a release note after you've dropped them?

**Comment by achow101** [comment]
> Looks good, but there's still `DBErrors ZapWalletTx(std::list<CWalletTx>& vWtx);` in [wallet.h](https://github.com/bitcoin/bitcoin/blob/21eda43cdea808335385af5c35f3baa77239749c/src/wallet/wallet.h#L1078) and [walletdb.h](https://github.com/bitcoin/bitcoin/blob/21eda43cdea808335385af5c35f3baa77239749c/src/wallet/walletdb.h#L260).
> 
> Can you also add a release note after you've dropped them?

Done and done.

**Review by meshcollider — COMMENTED** [review]
utACK 3340dbadd38f5624642cf0e14dddbe6f83a3863b

**Review by fanquake — APPROVED** [review]
ACK 3340dbadd38f5624642cf0e14dddbe6f83a3863b - remaining manpage references will get cleaned up pre-release.

**Comment by gmaxwell** [comment]
I don't see any problem in removing this.  But the release note asserts that this functionality was added for the purpose of replacing transactions that didn't have RBF.   Rather, the functionality was added to help rescue wallets that had been messed up by malleability attack:  https://github.com/bitcoin/bitcoin/pull/3659#issuecomment-34878999

It's my (non-researched) belief that the malleability motivation is no longer a reason to keep the functionality, because although wallets with non-segwit coins are still malleability-vulnerable, I believe other changes mean that conflicted transactions can just be abandoned.  If there is another rash of malleability attacks, users will have to be advised to use abandon on the unsuccessful mutants rather than be advised to zap as was the case when these attacks were an issue, along with spendzeroconfchange=false (or a narrower version that only avoids vulnerable inputs, if one is ever implemented).

**Comment by achow101** [comment]
> But the release note asserts that this functionality was added for the purpose of replacing transactions that didn't have RBF. Rather, the functionality was added to help rescue wallets that had been messed up by malleability attack

Thanks for pointing that out, I've updated the release notes draft.

**Pull request merged**
