### PR TITLE
Remove unused test files and references

### PR DESCRIPTION
**Pull request by btcdrak**
Refs #7562

### CODE REVIEW

**Comment by laanwj** [comment]
This must have broken `make distdir`. Unsure how did it pass the Travis tests.

**Comment by fanquake** [comment]
@laanwj Yes it looks like `make distdir` has been broken.
```
$ make distdir
if test -d "bitcoin-0.13.99"; then find "bitcoin-0.13.99" -type d ! -perm -200 -exec chmod u+w {} ';' && rm -rf "bitcoin-0.13.99" || { sleep 5 && rm -rf "bitcoin-0.13.99"; }; else :; fi
test -d "bitcoin-0.13.99" || mkdir "bitcoin-0.13.99"
 (cd src && /Applications/Xcode.app/Contents/Developer/usr/bin/make  top_distdir=../bitcoin-0.13.99 distdir=../bitcoin-0.13.99/src \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
Generated bench/data/block413567.raw.h
Generated test/data/tx_valid.json.h
make[1]: *** No rule to make target `test/data/blanktx.hex', needed by `distdir'.  Stop.
make: *** [distdir] Error 1
```
However after merging this I still see:
```
config.status: executing depfiles commands
make[1]: *** No rule to make target `test/data/txcreatesign.hex', needed by `distdir'.  Stop.
make: *** [distdir] Error 1
```
@btcdrak  Could you fixup that reference? Looks like it's now ` txcreatesignv1.hex`?

**Comment by laanwj** [comment]
@theuni Shouldn't Travis pick up problems like this? It always did for me, although now that I think of it that was when forgetting to specify `.h` files.

**Comment by MarcoFalke** [comment]
@laanwj Travis never does the distdir step, I think.

**Comment by laanwj** [comment]
Okay, then I must be confused with gitian. I thought it did that before building. But maybe that's only gitian.

**Comment by DATSEC** [comment]
I got this error

```
make[2]: *** No rule to make target `test/data/blanktx.hex', needed by `distdir'                       .  Stop.
make[2]: Leaving directory `/home/ubuntu/build/bitcoin/src'
make[1]: *** [distdir] Error 1
make[1]: Leaving directory `/home/ubuntu/build/bitcoin'
make: *** [dist] Error 2
```

**Comment by theuni** [comment]
@laanwj IIRC we used to have a distcheck in Travis, but got rid of it a while ago because it was too heavy. Or maybe it was that it used distdir before the out-of-tree build?

I think we could probably add back the lighter ```make distdir``` at the end to catch these things.

**Comment by DATSEC** [comment]
```
+ make dist
make  dist-gzip am__post_remove_distdir='@:'
make[1]: Entering directory `/home/ubuntu/build/bitcoin'
if test -d "bitcoin-0.13.99"; then find "bitcoin-0.13.99" -type d ! -perm -200 -                     exec chmod u+w {} ';' && rm -rf "bitcoin-0.13.99" || { sleep 5 && rm -rf "bitcoi                     n-0.13.99"; }; else :; fi
test -d "bitcoin-0.13.99" || mkdir "bitcoin-0.13.99"
 (cd src && make  top_distdir=../bitcoin-0.13.99 distdir=../bitcoin-0.13.99/src                      \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[2]: Entering directory `/home/ubuntu/build/bitcoin/src'
Generated bench/data/block413567.raw.h
Generated test/data/script_tests.json.h
Generated test/data/base58_keys_valid.json.h
Generated test/data/base58_encode_decode.json.h
Generated test/data/base58_keys_invalid.json.h
Generated test/data/tx_invalid.json.h
Generated test/data/tx_valid.json.h
Generated test/data/sighash.json.h
make[2]: *** No rule to make target `test/data/blanktx.hex', needed by `distdir'                     .  Stop.
make[2]: Leaving directory `/home/ubuntu/build/bitcoin/src'
make[1]: *** [distdir] Error 1
make[1]: Leaving directory `/home/ubuntu/build/bitcoin'
make: *** [dist] Error 2

```

**Comment by btcdrak** [comment]
> Could you fixup that reference? Looks like it's now txcreatesignv1.hex?

@fanquake done.

**Comment by fanquake** [comment]
@btcdrak  Thanks, looks better now:
```
bash-3.2$ make distdir
if test -d "bitcoin-0.13.99"; then find "bitcoin-0.13.99" -type d ! -perm -200 -exec chmod u+w {} ';' && rm -rf "bitcoin-0.13.99" || { sleep 5 && rm -rf "bitcoin-0.13.99"; }; else :; fi
test -d "bitcoin-0.13.99" || mkdir "bitcoin-0.13.99"
 (cd src && /Applications/Xcode.app/Contents/Developer/usr/bin/make  top_distdir=../bitcoin-0.13.99 distdir=../bitcoin-0.13.99/src \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
 (cd secp256k1 && /Applications/Xcode.app/Contents/Developer/usr/bin/make  top_distdir=../../bitcoin-0.13.99 distdir=../../bitcoin-0.13.99/src/secp256k1 \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
:
test -d "../../bitcoin-0.13.99/src/secp256k1" || mkdir "../../bitcoin-0.13.99/src/secp256k1"
test -n ":" \
	|| find "../../bitcoin-0.13.99/src/secp256k1" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec /bin/sh /Users/michael/bitcoin/src/secp256k1/build-aux/install-sh -c -m a+r {} {} \; \
	|| chmod -R a+r "../../bitcoin-0.13.99/src/secp256k1"
 (cd univalue && /Applications/Xcode.app/Contents/Developer/usr/bin/make  top_distdir=../../bitcoin-0.13.99 distdir=../../bitcoin-0.13.99/src/univalue \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
:
test -d "../../bitcoin-0.13.99/src/univalue" || mkdir "../../bitcoin-0.13.99/src/univalue"
test -n ":" \
	|| find "../../bitcoin-0.13.99/src/univalue" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec /bin/sh /Users/michael/bitcoin/src/univalue/build-aux/install-sh -c -m a+r {} {} \; \
	|| chmod -R a+r "../../bitcoin-0.13.99/src/univalue"
 (cd doc/man && /Applications/Xcode.app/Contents/Developer/usr/bin/make  top_distdir=../../bitcoin-0.13.99 distdir=../../bitcoin-0.13.99/doc/man \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
/Applications/Xcode.app/Contents/Developer/usr/bin/make  \
	  top_distdir="bitcoin-0.13.99" distdir="bitcoin-0.13.99" \
	  dist-hook
/usr/local/bin/git archive --format=tar HEAD -- src/clientversion.cpp | ${TAR-tar} -C bitcoin-0.13.99 -xf -
test -n "" \
	|| find "bitcoin-0.13.99" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec /bin/sh /Users/michael/bitcoin/build-aux/install-sh -c -m a+r {} {} \; \
	|| chmod -R a+r "bitcoin-0.13.99"
```
ACK https://github.com/bitcoin/bitcoin/pull/9376/commits/9cb66248dc7e1c782256d1f69ad67f9c63fb61f8

**Comment by laanwj** [comment]
> @laanwj IIRC we used to have a distcheck in Travis, but got rid of it a while ago because it was too heavy. Or maybe it was that it used distdir before the out-of-tree build?

The travis check was the only way most people were even noticing inconsistencies in the Makefile with regard to installed files, this is why pulls like this are popping up all over the place now.

**Comment by droark** [comment]
Posthumous ACK

blanktx.json is still sitting around unused. I believe it can be used for a v1 JSON test that doesn't seem to exist right now. I'll file a PR where I change it to blanktxv1.json and integrate it into the test suite.

**Pull request merged**
