### PR TITLE
init: add missing -blockversion help to debugging help output

### PR DESCRIPTION
**Pull request by Diapolo**

### CODE REVIEW

**Comment by laanwj** [comment]
I'm not sure it makes much sense to document this flag. It's never useful to end users, so it's a waste of translator time.

(At the very least we don't want to add new translation messages until the 0.11 release)

**Comment by laanwj** [comment]
On the other hand this is only shown with `-help-debug`.
Alternatively, we could add the policy that debug option help messages are not translated (no `_()`), then I'm fine with this.

**Comment by Diapolo** [comment]
@laanwj Currently all debug help messages are translated anyway. So to be consistent we could just merge as is or I add another commit, which removes the translation for all ``-help-debug`` strings?

**Comment by laanwj** [comment]
I don't want to remove the existing strings for 0.11, people may have already translated them. At least do not translate this one and add a comment to not add new translation strings for strings that will only be visible to developers.

**Comment by Diapolo** [comment]
@laanwj Sorry, but as I use ``-help-debug`` all time with german translation turned on, I refuse to leave this translation string out, while ALL others are indeed translated, that makes no sense to me.

**Pull request closed without merging**
