### PR TITLE
consensus: move amount.h into consensus

### PR DESCRIPTION
**Pull request by fanquake**
A first step (of a few) towards some source code reorganization, as well as making libbitcoinconsensus slightly more self contained.

Related to #15732.

### CODE REVIEW

**Comment by bitcoin-public-domain** [comment]
So now **BITCOIN_AMOUNT_H** becomes **BITCOIN_CONSENSUS_AMOUNT_H**? 

I think renaming stuff like this or as you call "reorganizing" is very dangerous. I'm totally against such reorganization.

**Comment by laanwj** [comment]
Concept ACK. I think this is organizationally the right thing to do. Nearly everything in `amount.h` is consensus critical:

- type `CAmount`
- constant `MAX_MONEY`
- function `MoneyRange`

Even `COIN`, though it strictly is a presentation detail, is used in `src/validation.cpp` to set the initial subsidy. So changing it would be consensus critical.

**Comment by hebasto** [comment]
Concept ACK.

**Review by hebasto — APPROVED** [review]
ACK 2c1554a10940e471708d0d81bde0d490dc1c73b4.

I see the last two commits as a way to modernize `amount.h`. Here are some additional suggestions:
- use type alias instead of `typedef`
- use separators for integer literals
- s/`nValue`/`value`/ to follow our name convention
- pass `CAmount` as a non-reference parameter: s/`const CAmount&`/`CAmount`/. Also https://github.com/bitcoin/bitcoin/pull/23076#issuecomment-926539987.

**Comment by practicalswift** [comment]
Concept ACK

**Comment by MarcoFalke** [comment]
concept ACK 9d0379cea6c164610d05287ae6dd4e66f35b92b 🏝

<details><summary>Show signature and timestamp</summary>

Signature:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

concept ACK 9d0379cea6c164610d05287ae6dd4e66f35b92b 🏝
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEE+rVPoUahrI9sLGYTzit1aX5ppUgFAlwqrYAACgkQzit1aX5p
pUiIegv/UQSjhE3MlZkZ8Q9eV6M5sxc+xLMthzRmDDxQrktiXjsquDzCTLaKGrlA
26ASYaHNdvfTPn3UMY8IU2ibgI5EwRYgzOR4jWqlr7gBTU4DqQobi/oxxYrZPFTf
25Js5ET2yeIhCfusFwqorUXOI7zH/ehA7Om8re6zvWMyc3zMfDOCcI4+BCNF4Dbq
aOWlS1j8GZaK7RtgUDCkk9z0gwZNTKfgJSDmWc7Lh1dsvawcOFAkF2nAZtwSfyxN
//XU90+V0JMJz8sDkqBskidKi2tPi9j09ijqlo7ISBcA72skMzbBxLByo8nkZqv1
2D1OY/tqP6qDjhSwIb9OVf3/sWqRsMn5mz16yQ/KvhslyG8RY8ye8mYpFV6Xb7N3
mWIiDgI15LcjsoNi1MBB2979OI3oNahxaVV9SjxUq8M8zsBGe2IT8mq4KdUunccf
0pCfiebUvJNg+/4pq+d6a3BA+tdzYP5MDNQ6xminkn0wVytxskD3mkD/Jck83nOu
VVQPRV9w
=KxXo
-----END PGP SIGNATURE-----
```

[Timestamp of file with hash `fc451b85b7714b6efec31b9a07f211a521da7a434e0bfda8e649fdc21e55b2f6  -`](https://opentimestamps.org/info/?004f70656e54696d657374616d7073000050726f6f6600bf89e2e884e892940108fc451b85b7714b6efec31b9a07f211a521da7a434e0bfda8e649fdc21e55b2f6f010192997b086ed84a1416c4ea171010a4b08fff010578dc9570b0d776b65f71db66f8996d708f104615c01b5f008162a06dd21f4cb7e0083dfe30d2ef90c8e292868747470733a2f2f66696e6e65792e63616c656e6461722e657465726e69747977616c6c2e636f6dfff010a6ce733bcadbabc71b0282f3e50e666f08f104615c01b5f0082c2fb63705c642670083dfe30d2ef90c8e2e2d68747470733a2f2f616c6963652e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267fff010bf175f952cc2a792f6ce748766be05c008f104615c01b4f0086da24bf48e2ddb920083dfe30d2ef90c8e232268747470733a2f2f6274632e63616c656e6461722e636174616c6c6178792e636f6df010fb1dd305adbcb773faf31259fdab056008f104615c01b5f0089107b38179e40a5c0083dfe30d2ef90c8e2c2b68747470733a2f2f626f622e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267)

</details>

**Pull request merged**
