### PR TITLE
[qt] Rename formateNiceTimeOffset(qint64) to formatNiceTimeOffset(qint64)

### PR DESCRIPTION
**Pull request by practicalswift**
Rename `formateNiceTimeOffset(qint64)` to `formatNiceTimeOffset(qint64)`.

The **e** in "format**e**" is most likely a typo :-)

### CODE REVIEW

**Comment by MarcoFalke** [comment]
utACK 6cfbfc7

**Comment by paveljanik** [comment]
ACK https://github.com/bitcoin/bitcoin/commit/6cfbfc7654649ad42ead6149b179f54f01ac0596

**Comment by fanquake** [comment]
utACK 6cfbfc7 Could only find those 4 occurrences of formateNiceTimeOffset()

**Comment by practicalswift** [comment]
Removed `[trivial]` from commit title and added `[qt]` as per the clarified guidelines in #9542 :-)

**Pull request merged**
