### PR TITLE
test: Remove unused, undocumented and misleading CScript.__add__

### PR DESCRIPTION
**Pull request by maflcko**
See the corresponding pull #18612

### CODE REVIEW

**Comment by laanwj** [comment]
ACK faff9e4bb431919a4bc7e4dc4a9ca188e2d18113 provided it passes Travis

**Comment by hebasto** [comment]
`feature_fee_estimation.py` failed on [CentOS build](https://travis-ci.org/github/bitcoin/bitcoin/jobs/678150425).

**Comment by practicalswift** [comment]
Concept ACK: removed is better than unused

**Comment by MarcoFalke** [comment]
> feature_fee_estimation.py failed on CentOS build.

Thanks, reported as bug #18737

**Pull request merged**
