### PR TITLE
refactor: Drop unused CBufferedFile::Seek()

### PR DESCRIPTION
**Pull request by hebasto**

### CODE REVIEW

**Comment by practicalswift** [comment]
ACK 7b3851e9473e74043342d414c056c2ef87c2f261 -- deleted code is better than unused untested code:)

**Review by promag — COMMENTED** [review]
Code review ACK 7b3851e9473e74043342d414c056c2ef87c2f261.

@practicalswift agree, see #19391.

**Comment by MarcoFalke** [comment]
ACK 7b3851e9473e74043342d414c056c2ef87c2f261, assuming that removing this should either be correct or result in a compile failure

**Comment by jonasschnelli** [comment]
utACK 7b3851e9473e74043342d414c056c2ef87c2f261

**Pull request merged**
