### PR TITLE
CLTV IsSuperMajority() soft-fork, rebased against v0.11.0

### PR DESCRIPTION
**Pull request by petertodd**
Everything required to backport CLTV to v0.11, including the soft-fork itself.

### CODE REVIEW

**Comment by laanwj** [comment]
It may make sense to backport the "softforks" field in `getblockchaininfo` to 0.11 as well, to give people a way to check how far the fork is along.

**Comment by petertodd** [comment]
@laanwj Done!

Heh, I actually need to add that last commit to #6351, but the getblockchaininfo code was added after it and I'd rather not rebase it if I can avoid it; these two backport patches refer to commits in #6351 by commit ID and I don't want to change that. I'll fix that after #6351 is merged.

**Comment by petertodd** [comment]
Rebased

**Comment by dcousens** [comment]
once-over ACK

**Comment by btcdrak** [comment]
utACK

**Pull request merged**
