### PR TITLE
Fix a bug if the min fee is 0 for FeeFilterRounder

### PR DESCRIPTION
**Pull request by morcos**
Thanks @dcousens and @gmaxwell

### CODE REVIEW

**Comment by gmaxwell** [comment]
ACK.  This appears sensible and also fixes the bug.

**Comment by dcousens** [comment]
ACK 0e78469,  does it need to be put in place at https://github.com/bitcoin/bitcoin/blob/master/src/policy/fees.cpp#L304 also?

**Comment by dcousens** [comment]
Maybe actually, if someone changed `MIN_FEERATE to 0`, it would dead lock again

**Comment by laanwj** [comment]
utACK 0e78469

**Comment by MarcoFalke** [comment]
> if someone changed MIN_FEERATE to 0

I think we can't protect against developers randomly changing internal constants.

utACK 0e78469

**Comment by sipa** [comment]
@dcousens One way to deal with such constraints that some parts of the code have, is by adding a `static_assert(MIN_FEERATE > 0, "Min feerate must be nonzero);` in the place where it is used.

**Comment by dcousens** [comment]
@sipa sounds fine to me,

**Comment by laanwj** [comment]
Yes, static assertions would be the way to go then.

**Comment by morcos** [comment]
I added the static_assert, although I'm not sure it matters since the value used is actually max of MIN_FEERATE and minRelayTxFee which can't be 0.  But it doesn't hurt.

I noticed another "bug" if a minRelayTxFee of 1 satoshi is used in the mempool min fee decay.
Wouldn't mind someone else verifying the fix makes sense though..

**Comment by gmaxwell** [comment]
re-ACK.

**Comment by laanwj** [comment]
utACK f8d43b8

**Pull request merged**
