### PR TITLE
[Wallet] Replace OrderedTxItems(..) with in-memory map

### PR DESCRIPTION
**Pull request by cozz**
I was wondering why adding 18000 transactions to the wallet takes ages.
One of the reasons is CWallet::OrderedTxItems(..).
So maintain the map in-memory instead of generating it all the time.
This pull should not change any functionality.

### CODE REVIEW

**Comment by laanwj** [comment]
@jonasschnelli is working on larger changes to the wallet, and adding a 'netwallet' based on a new database. There doesn't seem to be much point in improving the performance of the legacy wallet, with risk of breaking things. So I'm closing this, sorry.

**Comment by bitcreditscc** [comment]
Any news on this wallet by @jonasschnelli ? I ask because a number of useful ideas seem to have been by-passed in favor of this option.

**Comment by jonasschnelli** [comment]
Still working on the wallet. Currently I'm exploring some hardware wallet stuff. Soon I'm back refactoring the wallet. Very likely I'm going to remove everything node related from my core-wallet fork and support SPV*RPC (qt) wallet connection to a trusted full node. Bundling the two (for deployment) could still be possible.

**Comment by MarcoFalke** [comment]
This seems related to #6851?

**Comment by bitcreditscc** [comment]
hehehe, it'll be a year soon and likely any work you do will take a while longer. Why don't we re-consider the most useful pull requests and maybe merge them? Then later when your version becomes available, we can allow users to have a choice? I see no downside to this and would be willing to put in some hours towards these goals.

**Pull request closed without merging**
