### PR TITLE
test, lint: check bash version before executing codespell

### PR DESCRIPTION
**Pull request by brunoerg**
When executing `lint-spelling.sh` I noticed `mapfile` command wasn't working so it wasn't ignoring the files that should be ignored giving me some false flags. I noticed the problem is the version of bash, `mapfile` was introduced in bash 4 and my machine had the 3 one. So, I added a verification to skip it if the version of bash is less than 4.

### CODE REVIEW

**Comment by w0xlt** [comment]
Concept ACK.

**Comment by jessebarton** [comment]
Concept ACK `a5e5b6d`

Code reviewed. 
Installed bash version 3 and confirmed code functioning as expected.

**Review by jessebarton — APPROVED** [review]

**Comment by fanquake** [comment]
> and my machine had the 3 one

What system / OS was this? Does everything else work? Judging by https://repology.org/project/bash/versions, there is no recently released version of any OS that ships with Bash `3.x`. Even ancient CentOS / Debian / Ubuntu all shipped with `4.x` (which was [released in 2009](https://ftp.gnu.org/gnu/bash/)).

Given that, I'm ~0 on adding more code to warn for this case.

**Comment by brunoerg** [comment]
> What system / OS was this? Does everything else work? Judging by https://repology.org/project/bash/versions, there is no recently released version of any OS that ships with Bash `3.x`. Even ancient CentOS / Debian / Ubuntu all shipped with `4.x` (which was [released in 2009](https://ftp.gnu.org/gnu/bash/)).

@fanquake I use MacOS and most versions (I think) are stuck in 3.x giving its license. So, since mapfile doesn't work in 3.x, the script doesn't "fail", it runs ignoring that certain files should be skipped, giving me some false flags.

**Comment by fanquake** [comment]
> I use MacOS and most versions (I think) are stuck in 3.x giving its license.

macOS swapped it's default shell away from bash > 2 years ago, with the release of `10.15`, which also happens to be the oldest version of macOS our release binaries will run on. I'd suggest installing, and switching to any other modern shell.

**Comment by jessebarton** [comment]
> > and my machine had the 3 one
> 
> What system / OS was this? Does everything else work? Judging by https://repology.org/project/bash/versions, there is no recently released version of any OS that ships with Bash `3.x`. Even ancient CentOS / Debian / Ubuntu all shipped with `4.x` (which was [released in 2009](https://ftp.gnu.org/gnu/bash/)).
> 
> Given that, I'm ~0 on adding more code to warn for this case.

Very good point, I had to download the bash source from the official GNU site to even get a binary I could test with. I agree its probably not worth adding code for this.

**Comment by fanquake** [comment]
Thanks, however I'm going to close this PR. I don't think we should be adding more code to our scripts, to better support Bash 3. I would suggest either swapping to the macOS default shell (zsh), or installing and using a modern Bash, i.e Bash 5.1 via homebrew: https://formulae.brew.sh/formula/bash.

**Comment by fjahr** [comment]
> I would suggest either swapping to the macOS default shell (zsh), or installing and using a modern Bash, i.e Bash 5.1 via homebrew: https://formulae.brew.sh/formula/bash.

I ran into this today and from my understanding it's still annoying, especially if you are starting out on a new macOS system. I am suggesting at least adding some docs on this since it would have saved me some time, see #24750

**Comment by laanwj** [comment]
This kind of issues keep coming up. Can we please port scripts like this to Python…

**Comment by MarcoFalke** [comment]
Started in https://github.com/bitcoin/bitcoin/pull/24762

**Pull request closed without merging**
