### PR TITLE
Changed rpc-tests.sh to rpc-tests.py in README.md

### PR DESCRIPTION
**Pull request by ptschip**

### CODE REVIEW

**Comment by paveljanik** [comment]
Is the UTF BOM at the beginning of the file needed?

**Comment by ptschip** [comment]
i don't know, but i don't see it as related to this pull request...

**Comment by paveljanik** [comment]
You added it in the commit in this PR, so it is related ;-)

**Comment by laanwj** [comment]
heh, UTF-8 should not require BOMs

**Comment by jonasschnelli** [comment]
ACK

**Comment by laanwj** [comment]
Merged as 5f34a25 without BOM

**Comment by paveljanik** [comment]
BOM in the master:
```
bitcoin-master pavel$ hexdump -C README.md | head -1
00000000  ef bb bf 42 69 74 63 6f  69 6e 20 43 6f 72 65 20  |...Bitcoin Core |
bitcoin-master pavel$ 
```

**Comment by laanwj** [comment]
Yes, editorfail, these things are harder to get rid of than viruses.

Never mind, it's bullshit but I guess it doesn't get in the way of anything.

**Comment by MarcoFalke** [comment]
Let's just append it to the next trivial PR.

**Comment by paveljanik** [comment]
No problem for me. The diff looked weird in the GitHub PR 8)

**Pull request closed without merging**
