### PR TITLE
ci: Bump s390x to ubuntu:24.04

### PR DESCRIPTION
**Pull request by maflcko**
Now that most other CI tasks are rolled to 24.04, roll this one as well.
Also, re-enable feature_init.

### CODE REVIEW

**Comment by emc99** [comment]
What's s390x?

**Comment by laanwj** [comment]
> I think they are only missing riscv64, after commit

Great!

> What's s390x?

s390x is some old IBM CPU architecture, we test on it to check if everything works on big-endian machines.

**Review by emc99 — APPROVED** [review]

**Review by fanquake — APPROVED** [review]
ACK fadf7e90dc10e212e59bb294209bab2e73c47800 - finished running after ~5 hours.

**Comment by fanquake** [comment]
Backported to 27.x in #29888.

**Pull request merged**
