### PR TITLE
guix: Misc leftover usability improvements

### PR DESCRIPTION
**Pull request by dongcarl**
There seems to be some corner cases that can be hit when guix scripts unexpectedly fail in the middle of operation, see: https://gnusha.org/bitcoin-builds/2021-05-24.log

- Perform an early disk space check for `guix-build`
- Overwrite existing output directory after a successful build (the existing one might be malformed), and cleanup output directory if the `mv` somehow fails

### CODE REVIEW

**Comment by laanwj** [comment]
>  Perform an early disk space check for guix-build
> Overwrite existing output directory after a successful build 

Thank you!
Untested ACK, will test.

**Comment by fanquake** [comment]
Concept ACK

**Comment by laanwj** [comment]
Tested ACK
Disk space check worked:
```
Performing a Bitcoin Core Guix build for the selected HOSTS requires 44 GiB, however, only 15 GiB is available. Please free up some disk space before performing the build.
```
I also checked that rebuilding for a commit while leaving the `output` directory intact doesn't cause an error anymore.

**Comment by achow101** [comment]
ACK 108a6be92adc1e80839d90b552e72b8142140f6c

**Pull request merged**
