### PR TITLE
[24.x] Revert "build: Use Homebrew's sqlite package if it is available"

### PR DESCRIPTION
**Pull request by maflcko**
Identical commit, taken as-is from https://github.com/bitcoin/bitcoin/pull/25985

### CODE REVIEW

**Comment by dergoegge** [comment]
ACK d216d714aae36e6f1c95f82aef81a0be74dee2f3

**Review by hebasto — APPROVED** [review]
ACK d216d714aae36e6f1c95f82aef81a0be74dee2f3

nit: no usual commit message backport stuff like
```
Github-Pull: ...
Rebased-From: ...
```
?

**Comment by MarcoFalke** [comment]
Yes, it was written before the branch-off, so it can just be merged like any other commit before the branch-off. Just seems extra effort to change the commit id, add metadata, and then ask reviewers to verify the metadata again for no reason?

**Comment by hebasto** [comment]
> Yes, it was written before the branch-off, so it can just be merged like any other commit before the branch-off.

Right.

**Pull request merged**
