### PR TITLE
Sort pending wallet transactions before reaccepting

### PR DESCRIPTION
**Pull request by dexX7**
During startup, when adding pending wallet transactions, which spend outputs of
other pending wallet transactions, back to the memory pool, and when they are
added out of order, it appears as if they are orphans with missing inputs.

Those transactions are then rejected and flagged as "conflicting" (= not in the
memory pool, not in the block chain).

To prevent this, transactions are explicitly sorted.

### CODE REVIEW

**Comment by laanwj** [comment]
I'd say that transactions generated by the wallet itself, which are the ones useful to insert into the mempool, are always in dependency order by nOrderPos, so this makes sense.

**Comment by dexX7** [comment]
@zander: I did not move the lock, but I believe both should work.

I reworded the comment from "chronological order" to "based on initial wallet insertion order". Hope this is more accurate.

**Comment by dexX7** [comment]
Rebased (`src/wallet.cpp -> src/wallet/wallet.cpp`).

Tested with the above linked test a few hundred times, although I can't say in which case `nOrderPos` might actually not reflect dependency order, and the test only shows it works well under those specific test conditions. It can be used to show the current failure though: [sample log output and comparison](https://gist.github.com/dexX7/9f6f33444d8df1de63a5)

**Comment by sipa** [comment]
utACK

**Comment by gavinandresen** [comment]
utACK

**Comment by willstg** [comment]
As a wallet user who has this issue and a lot of BTC in this status what can be done to get them back?

**Comment by dexX7** [comment]
Hey @willstg,

fortunally this is only a local issue, and your BTC are not lost.

Please create a backup of the wallet nevertheless.

Shutdown Bitcoin Core before continuing.

Depending on the OS, the default wallet locations are:

- On Unix systems: `$HOME/.bitcoin/wallet.dat`
- On OS X: `$HOME/Library/Application Support/Bitcoin/wallet.dat`
- On Windows: `%APPDATA%/Bitcoin/wallet.dat`

To clear the conflicted transactions, start `bitcoind` or `bitcoin-qt` with the command-line option `-zapwallettxes`.

Alternatively, `zapwallettxes=1` can be added to the `bitcoin.conf`, but should be removed after the first startup.

`zapwallettxes` clears the wallet transactions, and then scans the blockchain to find and add only those, which are actually in the chain (the non-conflicted ones).

If you had a bunch of unconfirmed transactions, then it could be that not all, but only some, or maybe even none, are going to be confirmed. This depends on whether other nodes received the transactions (and ultimately the miners).

There is also a chance that other nodes received the unconfirmed transactions, but your local client doesn't know anything about them after zapping, so please wait some time, ideally a few blocks, until you resend the transactions, which didn't go through.

**Comment by willstg** [comment]
Thumbs up @dexX7 thanks.

**Pull request merged**
