### PR TITLE
refactor: remove duplicate code from BlockAssembler

### PR DESCRIPTION
**Pull request by jamesob**
Found while reminding myself how transactions are chosen for blocks. Take it or leave it!

### CODE REVIEW

**Comment by laanwj** [comment]
Concept ACK

**Review by theStack — APPROVED** [review]
Concept and code-review ACK 0f40d653218789aa176ca2f844e3222d2ad890a3

**Comment by glozow** [comment]
code review ACK 0f40d653218789aa176ca2f844e3222d2ad890a3

**Comment by MarcoFalke** [comment]
Can anyone explain why this is correct? Why should GetModifiedFee be equal to GetFee??

**Comment by jamesob** [comment]
> Can anyone explain why this is correct? Why should GetModifiedFee be equal to GetFee??

Good point. This is not correct. :)

Probably a comment and/or test should be added.

**Comment by glozow** [comment]
Ah that's true, but it's very weird that they're not the same. Why does `update_for_parent_inclusion` use `GetFee()` and not `GetModifiedFee()` to update `nModFeesWithAncestors`?

**Comment by MarcoFalke** [comment]
modified fee is already applied recursively, so if you apply it repeatedly it would accumulate?

**Comment by MarcoFalke** [comment]
Well, it seems undocumented and either version could make sense I guess?

**Comment by theStack** [comment]
> Can anyone explain why this is correct? Why should GetModifiedFee be equal to GetFee??

Oh snap, I obviously totally overlooked this in my review :/

**Comment by MarcoFalke** [comment]
Indeed, might be good to add a test for this to understand/document what it does in the first place.

**Comment by MarcoFalke** [comment]
Looks like you may be able to re-open this after #24538 is merged?

**Comment by MarcoFalke** [comment]
This can be reopened, now that #https://github.com/bitcoin/bitcoin/pull/24538 is merged.

**Comment by fanquake** [comment]
@jamesob @glozow want to reopen / pick this up?

**Review by glozow — COMMENTED** [review]
ACK 0f40d653218789aa176ca2f844e3222d2ad890a3

**Pull request merged**
