### PR TITLE
Build: add REPO_SLUG to fix errors in forked builds

### PR DESCRIPTION
**Pull request by RandyMcMillan**
This small change enables forks to use the TravisCI tests.

### CODE REVIEW

**Comment by RandyMcMillan** [comment]
@hebasto - I am not sure if eliminating the if condition all together is a possibility.

**Comment by MarcoFalke** [comment]
What kind of errors?

**Comment by RandyMcMillan** [comment]
> What kind of errors?

I believe this is an example.

https://travis-ci.org/RandyMcMillan/bitcoin/jobs/608862338#L17515

It seems the if condition is timing out builds. I could be missing something but this change seems have fixed it.

**Comment by MarcoFalke** [comment]
The error comes from `./ci/test/06_script_a.sh`. Here you are modifying linters, so this can not be the right "fix".

**Comment by MarcoFalke** [comment]
The error is

> Error! Initial build successful, but not enough time remains to run later build stages and tests. Please manually re-run this job by using the travis restart button or asking a bitcoin maintainer to restart. The next run should not time out because the build cache has been saved.

Which means that your repository has a limit of 50 minutes. There is no code change that could fix that. You'd have to ask travis to increase it.

**Comment by RandyMcMillan** [comment]
Thanks - lesson learned - I will stick to the mac side of things!

**Pull request closed without merging**
