### PR TITLE
doc: Fix typo in importdescriptors

### PR DESCRIPTION
**Pull request by KolbyML**

### CODE REVIEW

**Review by ghost — APPROVED** [review]
ACK https://github.com/bitcoin/bitcoin/pull/25276/commits/210cd592cd67e05434c87d6f95e2d8d5b7abc800

**Comment by Zeyu-Li** [comment]
lgtm

**Review by LarryRuane — COMMENTED** [review]
ACK 210cd592cd67e05434c87d6f95e2d8d5b7abc800

**Review by Zeyu-Li — APPROVED** [review]

**Review by brunoerg — APPROVED** [review]
crACK 210cd592cd67e05434c87d6f95e2d8d5b7abc800

**Comment by brunoerg** [comment]
You could fix all typos in this PR. 

See:
```
src/kernel/context.h:15: libary ==> library
src/net.cpp:1106: Desig ==> Design
src/net.cpp:1107: Desig ==> Design
src/net.cpp:1108: Desig ==> Design
src/net.cpp:1109: Desig ==> Design
src/net.cpp:1110: Desig ==> Design
src/net.cpp:1111: Desig ==> Design
src/net.cpp:1112: Desig ==> Design
src/net.cpp:1113: Desig ==> Design
src/net.cpp:1114: Desig ==> Design
src/net.cpp:1115: Desig ==> Design
src/net.cpp:1116: Desig ==> Design
src/net.cpp:1117: Desig ==> Design
src/util/designator.h:16: Desig ==> Design
src/util/designator.h:18: Desig ==> Design
```

**Comment by hebasto** [comment]
> You could fix all typos in this PR.
> 
> See:
> 
> ```
> src/kernel/context.h:15: libary ==> library
> src/net.cpp:1106: Desig ==> Design
> src/net.cpp:1107: Desig ==> Design
> src/net.cpp:1108: Desig ==> Design
> src/net.cpp:1109: Desig ==> Design
> src/net.cpp:1110: Desig ==> Design
> src/net.cpp:1111: Desig ==> Design
> src/net.cpp:1112: Desig ==> Design
> src/net.cpp:1113: Desig ==> Design
> src/net.cpp:1114: Desig ==> Design
> src/net.cpp:1115: Desig ==> Design
> src/net.cpp:1116: Desig ==> Design
> src/net.cpp:1117: Desig ==> Design
> src/util/designator.h:16: Desig ==> Design
> src/util/designator.h:18: Desig ==> Design
> ```

I think `Desig` is a correct macro's name :)

**Comment by brunoerg** [comment]
> I think Desig is a correct macro's name :)

nice, we could add it to `spelling.ignore-words.txt`

**Pull request merged**
