### PR TITLE
[rpc] Allow a txid param in getrawmempool

### PR DESCRIPTION
**Pull request by kallewoof**
See #10300.

### CODE REVIEW

**Comment by jnewbery** [comment]
utACK 0300d5e556cc1556b9cba1ec11ff3eef47bddca5.

Can you add a test to exercise the new functionality? Perhaps add some calls to `getrawmempool` with specified txids to the mempool_reorg test. Around here: https://github.com/bitcoin/bitcoin/blob/e2b99b13131b5d0fd6fae6d55892c2ebb327d438/test/functional/mempool_reorg.py#L88

**Comment by sipa** [comment]
I believe this functionality already exists as `getmempoolentry`.

**Comment by kallewoof** [comment]
@sipa Indeed, I had completely missed that one. I'm surprised there's a whole command for it, personally. (And it doesn't seem to be well known as several people (me, issue author, ..) did not realize it, so it may be an idea to mention it in getrawmempool help.)

**Comment by paveljanik** [comment]
Thinking a bit more about it, `gettransaction` should be generalised to include not only in-wallet transactions, but also in-mempool txs. as we have in-wallet, in-blockchain/non-wallet and in-mempool txs (why entries?). But this is backward incompatible change in the API.

**Comment by sipa** [comment]
@paveljanik We have `getrawtransaction` for that, which can query for mempool transactions (and without `-txindex`, that's pretty much the only thing it is useful for).

I disagree that `gettransaction` should be extended. Despite its name, `gettransaction` actually does not return information about a transaction, but is a wallet RPC that returns information about a ledger entry (i.e., the effects a transaction has on your personal balance).

**Pull request closed without merging**
