### PR TITLE
Bugfix: Check for bench_bitcoin being enabled where needed, and skip UniValue dependency when unused

### PR DESCRIPTION
**Pull request by luke-jr**

### CODE REVIEW

**Comment by laanwj** [comment]
This seems to import all kinds of ancillary changes?

**Comment by luke-jr** [comment]
Yes, it's based on #5618. The cost of continually rebasing things like this without it seems higher than the cost of just merging it...

**Comment by laanwj** [comment]
That's fine but a) You should at least list all the changes that you make in the PR description b) Some of these have been rejected before, sometimes multiple times, such as having a configuration option for every single utility.

**Comment by kirkalx** [comment]
Not relevant to Luke's PR but this sort of thing "xnononononono", looks like it would be easy to screw up. Any good reason for it?

**Comment by luke-jr** [comment]
Lack of a better alternative?

**Comment by laanwj** [comment]
@kirkalx I commented on that too when that was introduced, but apparently that's the portable shell script way of doing things. Blame silly 80's UNIX's inheritance.

**Comment by laanwj** [comment]
I think this is too messy with all the merges factored in, closing.

**Pull request closed without merging**
