### PR TITLE
[devtools] add clang-format.py

### PR DESCRIPTION
**Pull request by maflcko**
This will add a python convenience wrapper for `clang-format`. The python code includes a list with tested versions (`tested_versions`) which can easily be updated in the future.

[ci skip]

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Not sure if possible: a script that only clang-formats changed/added code (would require some clever git operations) would be nice.

**Comment by MarcoFalke** [comment]
@jonasschnelli  Not sure if [this](http://clang.llvm.org/docs/ClangFormat.html#script-for-patch-reformatting) is what you are looking for.

**Comment by paveljanik** [comment]
After looking at the amount of changes `clang-format` generates and actually looking at such changes and looking at our release process (releasing 0.10, 0.11, ...), I think it doesn't make sense to apply the formatting in one shot for all the source files.
It only has sense for formatting new files and (maybe) for very stable files, like `primites/*` etc.

And as written above, I do not think the wrapper (in fact, `-i` and "tested" version check) is needed at all.

**Comment by MarcoFalke** [comment]
> @paveljanik  I think it doesn't make sense to apply the formatting in one shot for all the source files.

I think we all agree on this.

> @paveljanik I do not think the [...] "tested" version check is needed at all.

How would one verify a format PR when different versions produce different output? Also, it may be useful the extend the `clang-format.py` to skip git subtrees et al. (c.f. https://github.com/sipa/bitcoin/commit/a1261296e48967b3236053d3435a3f521898df2f#diff-6ca10bb3f43dbe234b1fce27929ce0d4R10 ).

**Comment by laanwj** [comment]
Code review ACK, although I'm not sure I see when this should be used.

Needs mention in `contrib/devtools/README.md`

**Comment by sipa** [comment]
Earlier reasons to not use clang-format was that its output changed, even
between several "versions" of clang-format-3.5. I wonder whether a solution
could be to include a small snippet of representative unformatted code, and
have the wrapper script check whether it results in the expected output?

**Comment by paveljanik** [comment]
It should definitely be used when committing new files...

**Comment by MarcoFalke** [comment]
@laanwj Done.
@sipa I have tested 3.6.{0,1,2} and they all produce the same output, so I have added them to `tested_versions`. I am thinking about doing the snippet-test after cleaning up .clang-format. So that would be a separate PR, I guess.

**Comment by laanwj** [comment]
>  I wonder whether a solution could be to include a small snippet of representative unformatted code, and have the wrapper script check whether it results in the expected output?

I like this idea a lot.

**Pull request merged**
