### PR TITLE
Refactor: Rename NET_TOR to NET_ONION

### PR DESCRIPTION
**Pull request by ghost**
This is a follow-up to #13532, where @promag already asked if this renaming would make sense.

If network shall be named _Onion_ instead of _Tor_ (like in the option `onlynet`), renaming the network enum NET_TOR to NET_ONION maybe would make sense and be stringent.

Change was produced with the following script:

```
#!/bin/bash

for file in $(grep --exclude-dir='.git' --files-with-matches --binary-files=without-match --recursive NET_TOR bitcoin/)
do
    sed --in-place --expression='s/NET_TOR/NET_ONION/g' $file
done
```

_Tor_ is used at many other places in the code, though.

### CODE REVIEW

**Comment by promag** [comment]
Follow https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md#scripted-diffs for these changes.

**Comment by wodry** [comment]
OK I did update the commit message.

**Comment by fanquake** [comment]
@wodry Have a look at  https://github.com/fanquake/bitcoin/commit/454bec264ef9d104a4062992e98fe8ca1513844c for an example of this scripted diff that doesn't require the for/do loop, grep etc. Ideally, we want to keep the verify scripts as simple and concise as possible.

For anyone wondering about the `-i ""`,  it's required for `sed` on macOS if you want to edit files in-place without passing a backup extension.

**Comment by wodry** [comment]
@fanquake OK i replaced the script code. Do other versions of sed not understand the `s/regexp/replacement/` syntax? I am surprised that one can leave out the first and last `/`

The man page for GNU sed 4.4 on Linux says:
> s/regexp/replacement/
              Attempt  to match regexp against the pattern space.  If successful, replace that portion matched with replacement.

**Comment by fanquake** [comment]
@wodry Apologies, my commit message was meant to include the first and last `/`...

**Comment by wodry** [comment]
Does not work for me:
> bitcoin$ LANG=C sed -i "" 'sNET_TOR/NET_ONIONg' src/init.cpp src/netaddress.cpp src/netaddress.h src/netbase.cpp src/qt/optionsdialog.cpp src/test/netbase_tests.cpp src/torcontrol.cpp
sed: can't read sNET_TOR/NET_ONIONg: No such file or directory

**Comment by fanquake** [comment]
@wodry See my [comment above](https://github.com/bitcoin/bitcoin/pull/13575#issuecomment-401608078).

**Comment by wodry** [comment]
@fanquake please see my edits. Is
`sed -i"" 's/NET_TOR/NET_ONION/g' src/init.cpp src/netaddress.cpp src/netaddress.h src/netbase.cpp src/qt/optionsdialog.cpp src/test/netbase_tests.cpp src/torcontrol.cpp` ok for Mac?

**Comment by wodry** [comment]
What does the Travis error mean. Is something not ok with my commit?
```
The command "if [ "$TRAVIS_EVENT_TYPE" = "pull_request" ]; then test/lint/commit-script-check.sh $TRAVIS_COMMIT_RANGE; fi" exited with 1.
0.12s$ test/lint/git-subtree-check.sh src/crypto/ctaes
src/crypto/ctaes in HEAD currently refers to tree 1b6c31139a71f80245c09597c343936a8e41d021
src/crypto/ctaes in HEAD was last updated in commit 8501bedd7508ac514385806e191aec21ee978891 (tree 1b6c31139a71f80245c09597c343936a8e41d021)
subtree commit 003a4acfc273932ab8c2e276cde3b4f3541012dd unavailable: cannot compare
```
I double checked that my change commit is set up onto a freshly fetched master upstream branch.

**Comment by fanquake** [comment]
@wodry You need to add "scripted-diff:" to the commit title. i.e "scripted-diff: rename NET_TOR to NET_ONION"

See [scripted diffs](https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md#scripted-diffs) in the developer notes.

**Comment by wodry** [comment]
Ah tanks, forgot that, fixed.

**Comment by Empact** [comment]
Could you apply the scripted-diff to all sources? If that works it will be more robust against independent introduction.

**Comment by MarcoFalke** [comment]
git grep -l could be helpful

**Comment by wodry** [comment]
@Empact I agree. My original script that I posted in my first comment does that.

@MarcoFalke `-l` is `--files-with-matches` which I used in my original script that I posted in my first comment.

@fanquake I changed back to my original script but changed `--in-place` to `--in-place''` so it should work on MacOS sed, too.

**Comment by wodry** [comment]
Could someone please advise howto fix the Travis error? I triple checked to follow [scripted diffs developer notes)](https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md#scripted-diffs)

**Comment by ken2812221** [comment]
I would suggest 

    sed -iE 's/NET_TOR/NET_ONION/g' $(git ls-files -- '*.cpp' '*.h')

**Comment by wodry** [comment]
Thanks @ken2812221 for the fix. Isn't it better to grep for occurrence of NET_TOR in all non-binary files to see if NET_TOR is maybe also in non-.cpp/.h files?
If this is not the case, like here, it's fine, and as a benefit one knows that fact.

**Comment by MarcoFalke** [comment]
Please use `git grep` instead of `grep`

**Comment by wodry** [comment]
@MarcoFalke Updated

**Comment by Empact** [comment]
utACK 07c493f

**Comment by ken2812221** [comment]
utACK 07c493f2d1053d6a1c7d0ca1650da7b6f94c8948

**Comment by sipa** [comment]
utACK 07c493f2d1053d6a1c7d0ca1650da7b6f94c8948

**Comment by laanwj** [comment]
utACK 07c493f2d1053d6a1c7d0ca1650da7b6f94c8948

> Tor is used at many other places in the code, though.

The goal should also not be to replace tor with onion. The distinction is:
- `onion` should be used when referring to the representation and connecting to of onion hidden services. 
- `tor` when dealing with tor in general, so when connecting out through the tor proxy, Tor is special (unlike say, I2P) in that it's possible to connect both to internal onion addresses and external addresses through exit nodes.

**Pull request merged**
