### PR TITLE
Update the wallet best block marker when pruning

### PR DESCRIPTION
**Pull request by sipa**
When pruning, make sure that we update the wallet best block before deleting any files.

### CODE REVIEW

**Comment by laanwj** [comment]
utACK

Note: intended to fix #7494.

**Comment by sipa** [comment]
Updated the logic to just always update the wallet best block when the chainstate is flushed. Both are relatively slow operations, so this shouldn't have a strong effect on performance.

There are further problems with the flushing logic, which will require a more invasive change, but those problems can only trigger when a crash during flushing happens.

**Comment by morcos** [comment]
utACK

**Comment by sdaftuar** [comment]
utACK.  Needs backport!

**Comment by sdaftuar** [comment]
Verified that I can trigger the problem reported in #7494 by stopping bitcoind cleanly after the first blocks are pruned (restarting then fails).

Verified further that this pull fixes the issue.

ACK e4eebb604e19f67b0c7a483b1ded1229d75ecdd3

**Comment by laanwj** [comment]
@sdaftuar thanks for testing!

**Comment by laanwj** [comment]
Cherry-picked to 0.12 as 13299630013411b1a9c77d2332f9d2d45eacde0f

**Pull request merged**
