### PR TITLE
[qt] change µBTC to bits

### PR DESCRIPTION
**Pull request by jb55**
Now that we have bip176, change "µBTC" to the more colloquial "bits"

### CODE REVIEW

**Comment by Sjors** [comment]
I would suggest `bits (µBTC)`, `Bits (µBTC)` or `µBTC (bits)`, so more SI oriented folks don't need to Google "bits". Can you add some screenshots to see what this would look like in the UI?

**Comment by Sjors** [comment]
Also paging @jimmysong who opened this can of worms :-)

**Comment by jimmysong** [comment]
I would love if we can switch to bits, but not required. I understand if people don't want to change it.

**Comment by jb55** [comment]
current pic: https://jb55.com/s/2fbb07812e2dd00b.png

> I would suggest `bits (µBTC)`, `Bits (µBTC)` or `µBTC (bits)`, so more SI oriented folks don't need to Google "bits". 

This information is still available in the tooltip via BitcoinUnits::description if needed

> Can you add some screenshots to see what this would look like in the UI?

This isn't a quick fix like this change, and will require some reworking
so that it shows `bits` instead of `bits (µBTC)` everywhere.

**Comment by Sjors** [comment]
@jb55 you can actually drag & drop images onto Github, so they're inline.

There's more places where "bits" would appear, e.g. in the settings and as a dropdown in the send screen. If we go for `bits (µBTC)` that would probably look fine in a dropdown menu, but look terrible on the transactions screen. Whereas `bits` probably looks fine everywhere.

I remember the first time I saw the term "bits" in a wallet (Xapo). I found it very confusing, because I didn't know how many decimals it represents. I'm fine with switching to bits, but shouldn't assume all users are familiar with it. So it requires some education.

The easiest way to achieve a minimum level of education is to have two strings. Use the short version `bits` everywhere expect the dropdown menus. That would add a few lines of code to this PR, but nothing unsurmountable. Let me know if you need any pointers.

**Comment by jb55** [comment]
I've implemented your suggestion in af7f3c1ccafefd92603a5138a136a52f0c249fe9

Here's what it looks like:

dec28-061640

dec28-061628

dec28-061139

dec28-061037

**Comment by Sjors** [comment]
ACK af7f3c1c, but please [squash](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#squashing-commits).

**Comment by jb55** [comment]
Squashed in 275b2eeed4050d8797bf127e5abf171c050e182a

**Comment by Sjors** [comment]
Thanks, reACK 275b2ee.

**Comment by laanwj** [comment]
No opinion on this but at least you should update `doc/bips.md` when you do this.

**Comment by jb55** [comment]
@laanwj done in ebcee1de263ea21acfd79e92dc874de65c9bae9b

**Comment by laanwj** [comment]
Tested ACK ebcee1d

**Comment by jonasschnelli** [comment]
utACK ebcee1de263ea21acfd79e92dc874de65c9bae9b

**Pull request merged**
