### PR TITLE
RPC: Add aliases for priv and pub rpc calls

### PR DESCRIPTION
**Pull request by cvengler**
Hello, this PR adds aliases for all privkey and pubkey rpc calls.<br>
For example:
`importprivatekey` does the same as `importprivkey`
Same with `importpublickey` and `importpubkey`<br>
**Aliases that have been added**
- importprivatekey => importprivkey
- importpublickey => importpubkey
- signmessagewithprivatekey => signmessagewithprivkey

I added the aliases because I did several typos in the past where I've written public and private instead of pub and priv.

However I haven't added the aliases to the help/qt autocompletion because I added them, as stated above, for typos.

Greetings Emil

### CODE REVIEW

**Comment by promag** [comment]
Concept NACK sorry, IMO there's no point in having aliases just because you type the wrong command.

Maybe an alternative is to have the aliases on the client side? Still I don't think it's worth it.

**Comment by emilengler** [comment]
@promag GNU for example also have aliases.
dir is just an alias for ls

**Comment by promag** [comment]
@emilengler I'm aware of aliases, I just think the server doesn't have to deal with that.

**Comment by kristapsk** [comment]
Concept NACK, definitely not the right thing to do at the server side. If typos are the problem that needs to be solved (I doubt even that), can be done at client side. For `bitcoin-cli` typos can be solved better as an autocomplete module for the shell you use.

**Comment by MarcoFalke** [comment]
Closing for now. Seems too controversial. Indeed, we have autocomplete (in the gui) as well as for the shell.

**Pull request closed without merging**
