### PR TITLE
fuzz: Add fuzzer for ConditionStack

### PR DESCRIPTION
**Pull request by maflcko**
This takes the ConditionStack from d0e8f4d5d8ddaccb37f98b7989fb944081e41ab8 and e6e622e5a0e22c2ac1b50b96af818e412d67ac54 and checks that they behave equally with a fuzz test.

### CODE REVIEW

**Comment by practicalswift** [comment]
Concept ACK: thanks for adding fuzzing harnesses. Nice to see the new PR title prefix `fuzz:` :)

**Comment by Empact** [comment]
Concept ACK - I take it you don't mean for this to be merged but rather to prove the point?

**Review by jonatack — COMMENTED** [review]
Concept ACK, tested
```diff
(pr/18127)$ src/test/fuzz/script_condition_stack 
INFO: Seed: 3449044402
INFO: Loaded 1 modules   (510932 inline 8-bit counters): 510932 [0x5642d9dc1678, 0x5642d9e3e24c), 
INFO: Loaded 1 PC tables (510932 PCs): 510932 [0x5642d9e3e250,0x5642da609f90), 
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
INFO: A corpus is not provided, starting from an empty corpus
#2	INITED cov: 177 ft: 178 corp: 1/1b exec/s: 0 rss: 117Mb
#3	NEW    cov: 179 ft: 242 corp: 2/59b exec/s: 0 rss: 117Mb L: 58/58 MS: 1 InsertRepeatedBytes-
#4	NEW    cov: 179 ft: 290 corp: 3/90b exec/s: 0 rss: 117Mb L: 31/58 MS: 1 EraseBytes-
#5	NEW    cov: 179 ft: 291 corp: 4/121b exec/s: 0 rss: 117Mb L: 31/58 MS: 1 ChangeByte-
#6	REDUCE cov: 179 ft: 291 corp: 4/111b exec/s: 0 rss: 117Mb L: 21/58 MS: 1 EraseBytes-
#7	REDUCE cov: 179 ft: 291 corp: 4/99b exec/s: 0 rss: 117Mb L: 19/58 MS: 1 EraseBytes-
	NEW_FUNC[0/10]: 0x5642d6f4b1d0 in std::_Bvector_base<std::allocator<bool> >::_Bvector_impl::_M_end_addr() const /usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_bvector.h:487
	NEW_FUNC[1/10]: 0x5642d6f4b880 in std::vector<bool, std::allocator<bool> >::_M_insert_aux(std::_Bit_iterator, bool) /usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/vector.tcc:843

.../...

#24489	REDUCE cov: 438 ft: 2252 corp: 118/178Kb exec/s: 9 rss: 264Mb L: 2263/4096 MS: 2 InsertRepeatedBytes-EraseBytes-
```

**Comment by practicalswift** [comment]
@MarcoFalke Why the close?

**Pull request closed without merging**
