### PR TITLE
test: Replace 0xC0 constant

### PR DESCRIPTION
**Pull request by roconnor-blockstream**
Instead it should be the named constant `LEAF_VERSION_TAPSCRIPT`.

### CODE REVIEW

**Comment by instagibbs** [comment]
Since we're already here, we could replace the rest of the instances of this variable too?

**Comment by roconnor-blockstream** [comment]
I am not aware of other instances.

**Comment by instagibbs** [comment]
here and `script_lists` a few lines below it https://github.com/bitcoin/bitcoin/blob/master/test/functional/feature_taproot.py#L1548

**Comment by roconnor-blockstream** [comment]
*lol* I'm embarrassed to say, I was only looking at Elements code.

**Comment by instagibbs** [comment]
ACK https://github.com/bitcoin/bitcoin/pull/27143/commits/c3b4b5a142b204ceeca4e9b1ca1e2ff41ddd1308

**Review by theStack — APPROVED** [review]
ACK c3b4b5a142b204ceeca4e9b1ca1e2ff41ddd1308

**Pull request merged**
