### PR TITLE
Disallow uncompressed pubkeys in bitcoin-tx [multisig] output adds

### PR DESCRIPTION
**Pull request by TheBlueMatt**
Does what it says on the tin.

### CODE REVIEW

**Comment by instagibbs** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/11377/commits/53525eecb8a46f04ca844baef9b4a7b5c4d142e9

**Comment by MeshCollider** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/11377/commits/7c8b452f2b1e0693a3026f98c83fc67b2c55793f

Should the capitalization be 'SegWit' though, not 'Segwit'? Or all lowercase instead?

**Comment by TheBlueMatt** [comment]
Changed to "SegWit", didn't realize there was a "correct" capitalization.

**Comment by jonasschnelli** [comment]
Nice catch!
utACK 28d4542a0ac77a30a242d0568e580a5b437f53fa

**Comment by jl2012** [comment]
utACK 28d4542 
need backport?

**Comment by sipa** [comment]
utACK 28d4542a0ac77a30a242d0568e580a5b437f53fa. I didn't know this was supported in bitcoin-tx.

**Review by gmaxwell — APPROVED** [review]
ACK

**Comment by gmaxwell** [comment]
Backport tag please. This should be 0.15.1 milestone.

**Pull request merged**
