### PR TITLE
gitian-keys: add miketwenty1 key

### PR DESCRIPTION
**Pull request by miketwenty1**
in ref to:
bitcoin-core/gitian.sigs#1427

### CODE REVIEW

**Review by RiccardoMasutti — APPROVED** [review]
ACK

**Comment by laanwj** [comment]
Thanks! I've checked that the key id matches.

Please change your commit message to something clearer though, something like
```
gitian-keys: add key for miketwenty1
```
(see #20847, #20860)

**Comment by miketwenty1** [comment]
@laanwj 
Amended the commit message to be the recommended.

**Comment by laanwj** [comment]
Yes, looks good now!

ACK f2d93b229d8a95c0ff6c6cb9253d11cceec9d5d8

**Pull request merged**
