### PR TITLE
[wallet] Remove unused variables

### PR DESCRIPTION
**Pull request by practicalswift**
Remove two unused variables in `src/wallet/db.cpp`.

### CODE REVIEW

**Comment by benma** [comment]
utACK a8c09affcea53f1c65a1cb682d059127c15eae2d

**Review by gmaxwell — APPROVED** [review]
utACK

**Comment by paveljanik** [comment]
ACK a8c09af

**Comment by MarcoFalke** [comment]
utACK a8c09af

**Pull request merged**
