### PR TITLE
rpc: add deriveaddressesfromprivkey command

### PR DESCRIPTION
**Pull request by kallewoof**
This is a simple command for listing out all the address variants given a privkey, a feature which seems obvious but missing (unless I'm not finding the command!).

```Bash
$ ./bitcoin-cli -regtest getnewaddress
bcrt1qss60qxqt3vk6kxm4j6ufwp725f89esvm8lhvf6
$ ./bitcoin-cli -regtest dumpprivkey bcrt1qss60qxqt3vk6kxm4j6ufwp725f89esvm8lhvf6
cPsQTSmMZ8e3AEUWGjS73f5R364yJxH6RxcgnwbHjbKbFPUP2Dtu
$ ./bitcoin-cli -regtest deriveaddressesfromprivkey cPsQTSmMZ8e3AEUWGjS73f5R364yJxH6RxcgnwbHjbKbFPUP2Dtu
{
  "p2pkh": "msZzuZcZUYP8pdLZ3BktxFNZJQNR8ZBQjd",
  "segwit": "bcrt1qss60qxqt3vk6kxm4j6ufwp725f89esvm8lhvf6",
  "p2sh": "2N6EW9Va47woKmpzUmkqhpzemabnJAZudWW"
}
```

### CODE REVIEW

**Comment by sipa** [comment]
I think that `deriveaddresses` with a "combo(privkey)" descriptor will do this.

**Comment by kallewoof** [comment]
Interesting. I'm getting 'missing checksum', though. Syntax?
```
$ ./bitcoin-cli -regtest deriveaddresses "combo(cPsQTSmMZ8e3AEUWGjS73f5R364yJxH6RxcgnwbHjbKbFPUP2Dtu)"
error code: -5
error message:
Missing checksum
```

**Comment by sipa** [comment]
See https://github.com/bitcoin/bitcoin/blob/master/doc/descriptors.md

You can compute the checksum with the `getdescriptorinfo` RPC.

**Comment by kallewoof** [comment]
That worked. Nobody is going to realize that though, so I'm going to propose a change to the describeaddresses RPC that walks through this example.

**Pull request closed without merging**
