### PR TITLE
Update bips.md for 0.18.0

### PR DESCRIPTION
**Pull request by sipa**
Update `doc/bips.md` for changes in 0.17 and 0.18 (BIP 61 deprecated, BIP 70 support optional, BIP 159 connection logic).

### CODE REVIEW

**Comment by MarcoFalke** [comment]
utACK 65d2f5d2de37fd64c9cf8d526bab0072774b7b1d

**Comment by fanquake** [comment]
utACK 65d2f5d

**Comment by promag** [comment]
ACK 65d2f5d, referenced pulls match.

**Comment by fanquake** [comment]
Backported in #15775.

**Pull request merged**
