### PR TITLE
Improve CWallet API  with new GetAccountPubkey function.

### PR DESCRIPTION
**Pull request by pstratem**
Remove one more caller that is passing CWalletDB

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Travis didn't fetch this one. Mind to do a "null-rebase" and force-push?

**Comment by pstratem** [comment]
@MarcoFalke done

**Comment by laanwj** [comment]
Concept ACK

There does seem to be a pattern lately to move more and more code to the CWallet class, and we do need to split that up at some point, but I agree that these implementation details don't belong in the RPC code and that this is better locking-wise.

**Comment by pstratem** [comment]
@laanwj I'm going to be working on improving the wallet in general but that's very difficult to do when there's code all over the place.

This is just the logical first step.

**Comment by MarcoFalke** [comment]
utACK 8eb28b6

**Comment by laanwj** [comment]
Checked move-only, utACK https://github.com/bitcoin/bitcoin/commit/8eb28b61ee32369169bbabbe8e8b14361ebe292d

**Comment by sipa** [comment]
Posthumous move-only utACK 152ab236ea1c1106340196f45918fd84f57a0b63.

For reference, used this command:
```
git diff -w --patience --word-diff=color 152ab236ea1c1106340196f45918fd84f57a0b63~:src/wallet/rpcwallet.cpp 152ab236ea1c1106340196f45918fd84f57a0b63:src/wallet/wallet.cpp
```

**Comment by sipa** [comment]
Posthumous move-only utACK 152ab236ea1c1106340196f45918fd84f57a0b63

For reference:
```
git diff -w --patience --word-diff=color 152ab23~:src/wallet/rpcwallet.cpp 152ab23:src/wallet/wallet.cpp
```

**Pull request merged**
