### PR TITLE
wallet: remove GetScriptPubKeyMan spam

### LINKED ISSUE #21716: GetScriptPubKeyMan spamming the logs with irrelevant message
In the current way in which GetScriptPubKeyMan is used, there are multiple places where it is expected to fail and return empty. When this happens, the function writes to the logs that the searched output type doesn't exist. Since this function is called in multiple places as part of a loop to search the output types which do exist, this logs gets outputted a lot, while it's really quite irrelevant and expected. In the current situation, it can sometimes practically spam the logs with this quite unclear and worrying message, while in fact it is completely expected and (at least mostly) irrelevant...

I would suggest to either remove it or suppress it where it is used in a loop to search for the existing type.
If this makes sense I'd be happy to submit a PR for this.

### PR DESCRIPTION
**Pull request by klementtan**
fixes: #21716
 
**Problem:**
In `AddWalletDescriptor` we iterate through every combination of `internal/external` and `OutputType`. For each combination we call `GetScriptPubKeyMan` and when the combination is invalid we would log a warning `scriptPubKey Manager for output type` and thus causing the spam in the logs.

**My approach**
Since there is only one `ScriptPubKeyMan` that has the same id as `old_spk_man_id`, we would instead iterate through both the map and erase the `ScriptPubKeyMan` once we find it. 

The code that causes the spam: `src/wallet/wallet.cpp`
```cpp
ScriptPubKeyMan* CWallet::GetScriptPubKeyMan(const OutputType& type, bool internal) const
{
    const std::map<OutputType, ScriptPubKeyMan*>& spk_managers = internal ? m_internal_spk_managers : m_external_spk_managers;
    std::map<OutputType, ScriptPubKeyMan*>::const_iterator it = spk_managers.find(type);
    if (it == spk_managers.end()) {
        WalletLogPrintf("%s scriptPubKey Manager for output type %d does not exist\n", internal ? "Internal" : "External", static_cast<int>(type));
        return nullptr;
    }
    return it->second;
}
        auto old_spk_man_id = old_spk_man->GetID();
        for (bool internal : {false, true}) {
            for (OutputType t : OUTPUT_TYPES) {
                auto active_spk_man = GetScriptPubKeyMan(t, internal);
                if (active_spk_man && active_spk_man->GetID() == old_spk_man_id) {
                    if (internal) {
                        m_internal_spk_managers.erase(t);
                    } else {
                        m_external_spk_managers.erase(t);
                    }
                    break;
                }
            }
        }
```

### CODE REVIEW

**Review by Subawit — APPROVED** [review]

**Comment by fanquake** [comment]
@S3RK You might be interested in this.

**Review by 0racl3z — APPROVED** [review]

**Comment by S3RK** [comment]
Updating descriptors by removing SPKmanager from the map and creating a new one has been shown to be problematic — see #19651. I'd suggest to review #19651 as it removes the code it question altogether and it had one ACK already.

**Comment by achow101** [comment]
Agree with @S3RK that we should focus on #19651 which removes this code and replaces it with proper updating that also happens to not call `GetScriptPubKeyMan` a bunch.

**Comment by klementtan** [comment]
Agreed. #19651 is a better solution than this. Will take a look at it.

**Comment by tyson12346** [comment]
....

**Comment by tyson12346** [comment]
Me an noone else

**Pull request closed without merging**
