### PR TITLE
Performance fix for #6312

### PR DESCRIPTION
**Pull request by NicolasDorier**
Build on #6312 commit added is 0559bb24e6e92a2d790c77707e464aa1e17919ca :
- Remove lock time verification in CNB because the mempool is always finality coherent.
- Improve removeForReorg by not calling CheckLockTime on every transaction in the mempool during a reorg.

### CODE REVIEW

**Comment by morcos** [comment]
Any tx that has been in your mempool for longer than 10 blocks will have to be recalculated from scratch during a reorg.  In addition any transaction which entered your mempool more recently than the reorg depth will have to recalculated, so you will always have to recalculate at least the txs that came in since the last blcok.

I think if we are going to try to make reorgs fast, we should do it properly.

**Comment by NicolasDorier** [comment]
We could potentially scan the whole header chain instead of only 10, but I don't think this is a good idea performance wise. I think this is better to only scan 10 and just recalculate locktime if it is more, rather than wasting time scanning to the genesis. I can change that though if you think it is indeed faster to scan to genesis.

>  In addition any transaction which entered your mempool more recently than the reorg depth will have to recalculated, so you will always have to recalculate at least the txs that came in since the last blcok.

I don't understand your point.
Imagine tip = Block A, the tx1 comes in mempool. Then a reorg happens that replace BlockA with BlockB then tx1 will have, as expected, locktime invalidated.
This must be done, and can't be optimized, because the blockTime in LockTime(), MTP or not, will have changed.

If I understand your point : yes, during a reorg, all transaction which came since the last block will be invalidated, and they should be.

**Comment by morcos** [comment]
Yes that is my point.
However with the solution in #7187 it will not be necessary to relook up the inputs to the the tx and recalculate the sequence locks unless any of the inputs to the tx were in that most recent block, which seems likely to be considerably rarer.   
Technically if its a 1 block reorg, the blockTime won't have changed (with MTP) but I'm not suggesting not rechecking that.  I'm just saying you don't have to recalculate the time/height at which the sequence locks are valid which is the expensive part.
With your solution I think you will still be recalculating sequence locks for a significant fraction of the mempool on a reorg which is slow and destroys your utxo cache.

**Comment by NicolasDorier** [comment]
> Technically if its a 1 block reorg, the blockTime won't have changed (with MTP)

The blockTime will have changed. The old tip (BlockA) was part of the median.
When calculating LockTime of a mempool entry, we are assuming the tx will get in next block just after tip, so BlockA or BlockB are part of MTP calculation.

> I'm just saying you don't have to recalculate the time/height at which the sequence locks are valid which is the expensive part.

I need to. After a reorg, the maturity of the inputs may have changed, and so, the minimum time/height (what you call LockPoint) to satisfy as well. Am I missing something ?

**Comment by morcos** [comment]
> The blockTime will have changed. The old tip (BlockA) was part of the median.

Yes sorry, you are right about that, anyway we both agreed it should be checked.

> I need to. After a reorg, the "birthdate" of the inputs may have changed, and so, the minimum time/height (what you call LockPoint) to satisfy as well. Am I missing something ?

Yes you need to in your code.  I'm saying my approach saves that.

**Comment by jtimon** [comment]
I'm having troubles understanding what is wrong with this solution for #7176. It is very nice that it doesn't have to touch the 6-months old consensus code further, and I think that makes it the less risky option for #7176.

**Comment by NicolasDorier** [comment]
I agree, with jtimon. What is wrong with this code is the I recheck more than I need to.
In this code, if there is a 1 block reorg (block A replaced by block B), then all mempool transaction which came after BlockA will need to be rechecked. Morcos solution does not have this problem.

I myself prefer not touching the code that was heavily reviewed though.

**Comment by btcdrak** [comment]
@NicolasDorier this should be closed as the related ticket was also closed and superseded.

**Pull request closed without merging**
