### PR TITLE
Fix listreceivedbyaddress not taking address as a string

### LINKED ISSUE #14173: rpc method listreceivedbyaddress doesn't take address as a string
```
bitcoin-cli listreceivedbyaddress 0 true true 2NABbUr9yeRCp1oUCtVmgJF8HGRCo3ifpTT
```

gives an error: `error: Error parsing JSON:2NABbUr9yeRCp1oUCtVmgJF8HGRCo3ifpTT`

as it's trying to parse the address as json. so you'd have to write:
```
bitcoin-cli listreceivedbyaddress 0 true true '"2NABbUr9yeRCp1oUCtVmgJF8HGRCo3ifpTT"'
```
which is clumsy and inconsistent with other RPC methods as well as the help file

### PR DESCRIPTION
**Pull request by etscrivner**
Fixes #14173. Add the patch in #14173 and include a regression test.

### CODE REVIEW

**Comment by kristapsk** [comment]
ACK ccdcd9eec9825cc95a75816637960511d67305c1

**Comment by MeshCollider** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/14417/commits/ccdcd9eec9825cc95a75816637960511d67305c1

Note that your commit isn't associated with your GitHub account currently, did you use the same email address for both?

**Comment by etscrivner** [comment]
@MeshCollider Thanks! The commit should have the correct email now.

**Comment by MarcoFalke** [comment]
utACK d4d70eda33

**Comment by promag** [comment]
utACK d4d70ed.

**Comment by gmaxwell** [comment]
Backport me?

**Pull request merged**
