### PR TITLE
build: Minimize I/O operations in `GenerateHeaderFrom{Json,Raw}.cmake`

### PR DESCRIPTION
**Pull request by hebasto**
This PR aims to reduce build time by replacing multiple `file(WRITE|APPEND ...)` commands with a single `file(WRITE ...)` command.

Due to differences in implementation (e.g., filesystem design, system calls, caching), a noticeable improvement in build time is observed only on Windows.

Additionally, the code has been refactored to remove the `remainder` local variables.

### CODE REVIEW

**Comment by TheCharlatan** [comment]
I don't really see a difference in performance to be honest.

**Comment by hebasto** [comment]
> I am not measuring a difference in performance in the generation of the headers between master and this PR.

Building on Windows benefits most.

**Comment by hebasto** [comment]
> > I am not measuring a difference in performance in the generation of the headers between master and this PR.
> 
> Building on Windows benefits most.

On my Windows machine, the time to process `data/*.h` headers for the `test_bitcoin` target has been reduced from ~155s to ~105s.

@sipsorcery What do you think?

**Comment by sipsorcery** [comment]
> @sipsorcery What do you think?

The overall build time for me on Win11 msvc reduced by 44s (only one test run each of the master and PR builds).

**master**:
```
PS C:\Dev\github\bitcoin>  Measure-Command { cmake --build build --config Release }
TotalSeconds      : 637.2643505
```

**pr 30842**:
```
PS C:\Dev\github\bitcoin>  Measure-Command { cmake --build build --config Release }
TotalSeconds      : 553.3287435
```

IMHO it's always beneficial to improve CI times so +1 for me.

tACK b07fe666f27e2b2515d2cb5a0339512045e64761

**Review by sedited — APPROVED** [review]
ACK b07fe666f27e2b2515d2cb5a0339512045e64761

**Comment by fanquake** [comment]
> This PR aims to reduce the build time.

Can you update the PR description to clarify that this is only relevant for native windows builds. Can you also add the explanation for why this only makes a difference on Windows.

**Comment by hebasto** [comment]
> > This PR aims to reduce the build time.
> 
> Can you update the PR description to clarify that this is only relevant for native windows builds. Can you also add the explanation for why this only makes a difference on Windows.

I did my best.

**Comment by hebasto** [comment]
> Not sure why, but for me the command took almost an hour:
> 
> 
> 
> 
> 
> ```
> 
> $ ps -p 816447 --format time,rss,cmd
> 
>     TIME   RSS CMD
> 
> 00:51:12 117640 /usr/bin/cmake -DRAW_SOURCE_PATH=_/src/bench/data/block413567.raw -DHEADER_PATH=_/bld-cmake/src/bench/data/block413567.raw.h -DRAW_NAMESPACE=benchmark::data -P _/cmake/script/GenerateHeaderFromRaw.cmake
> 
> ```
> 
> 
> 
> Previously it took only a few seconds.

What's your system?

**Comment by fanquake** [comment]
Opened #30881 to track this, given a second dev has reported performance issues.

**Review by HumayunMhmadi — CHANGES_REQUESTED** [review]
IMG_20240904_132132_468.jpg](https://github.com/user-attachments/assets/bf11748e-d475-4f4d-870c-6691730baba7)

**Pull request merged**
