### PR TITLE
build: update retry to current version

### PR DESCRIPTION
**Pull request by RandyMcMillan**
retry updated
REF: https://github.com/kadwanev/retry/commit/7d2caa94a7e54bd15f54fb7f2395e11b2b829575

While spell checking and linting a few typos showed up.
This commit eliminates those linting alerts.

REF: https://github.com/bitcoin/bitcoin/pull/17207

### CODE REVIEW

**Comment by laanwj** [comment]
Huh, I wasn't aware we were subtree-ing this at all.

**Comment by RandyMcMillan** [comment]
@laanwj - I thought it wasn't sub tree'd so I just dragged and dropped. I will update the subtree and re push the commit.

**Comment by laanwj** [comment]
> maybe it should be?

I'm not sure. It doesn't seem like something that needs to be updated often. But I don't have a strong opinion on it.

@MarcoFalke imported this so will leave it to him.

**Comment by MarcoFalke** [comment]
This is not a subtree, but a plain copy. I don't know what this pull request is trying to achieve with its 22 commits. Unsubscribing. You can ping me when this is a single commit, ready for review that passes travis.

**Comment by RandyMcMillan** [comment]
@MarcoFalke - I am not sure where the inconsistency is coming from.
I did force push some corrections and Travis CI may not have the most current version of the PR. (restart build?)

I will make sure my branches pass before creating PRs in the future. 

**The point is to put /ci/retry under proper version control as a subtree.**

This is related to linting due to spelling errors and white space alerts in TRAVIC CI. 
https://travis-ci.org/bitcoin/bitcoin/jobs/601692713#L363
https://travis-ci.org/bitcoin/bitcoin/jobs/601692713#L346


**Part of the issue is the spelling errors touch so many files.**

https://travis-ci.org/bitcoin/bitcoin/jobs/601692713#L346
etc...

**Is it better to place them under one PR or file by file PRs?**

I am happy to tackle this issue. I just need some guidance on how to do this due to the fact that each PR (if done file by file) will likely **NOT** pass. But if the spelling corrections are placed in one large commit **they aren't very atomic**.

In my build:
https://travis-ci.com/RandyMcMillan/bitcoin/builds/133151187
you can see that it passes.

As this is a subtree (in this fork/PR) the spelling errors have been corrected upstream.
https://github.com/RandyMcMillan/bitcoin/commit/7d2caa94a7e54bd15f54fb7f2395e11b2b829575

I appreciate the feedback.

master branch linting:
Screen Shot 2019-10-23 at 5 33 05 PM

retry branch linting:
Screen Shot 2019-10-23 at 5 38 48 PM

https://travis-ci.com/RandyMcMillan/bitcoin/builds/133151187
[Build Status](https://travis-ci.com/RandyMcMillan/bitcoin)


NOTES:

The folder had to be deleted to create the subtree:
https://github.com/bitcoin/bitcoin/pull/17214/commits/4d3a9a6e902667c5d5d3efae3cf9419330f63716

The folder recreated as a subtree:
https://github.com/bitcoin/bitcoin/pull/17214/commits/71221d4be6b9c41205465f06baa895ee9eadf46c


The HEAD of the ci/retry subtree:
https://github.com/bitcoin/bitcoin/commit/7d2caa94a7e54bd15f54fb7f2395e11b2b829575


Part of the wider goal is to tackle the macOS build as well:
***https://github.com/bitcoin/bitcoin/issues/17178***

NOTE on grep alert on macOS. A path to ggrep will need to be added (for homebrew) I believe.

Thanks for your time.

**Comment by MarcoFalke** [comment]
Again, this is not a subtree or submodule or whatever.

`rm -r ci/retry && mv remote/retry ci/` is all that is needed to update this file.

I don't understand why this is so complicated

**Comment by RandyMcMillan** [comment]
I understood that it wasn't a subtree.

> **The point is to put /ci/retry under proper version control as a subtree.**

**Pull request closed without merging**
