### PR TITLE
Init script for debian/ubuntu

### PR DESCRIPTION
**Pull request by adam083b**
Contribution init script for debian/ubuntu operating systems to cleanly automatically start and stop bitcoind.

### CODE REVIEW

**Comment by luke-jr** [comment]
Last I checked, Debian/Ubuntu use systemd, for which we already have a service file...?

**Comment by echo083** [comment]
Yes indeed there is already a script for systemd but this script is intended to be used on RedHat operating systems and is not compatible with Debian/Ubuntu that's why I created this new one.

**Comment by hebasto** [comment]
> Contribution init script for debian/ubuntu operating systems to cleanly automatically start and stop bitcoind.

> Yes indeed there is already a script for systemd but this script is intended to be used on RedHat operating systems and is not compatible with Debian/Ubuntu that's why I created this new one.

Why "debian/ubuntu" is mentioned in the PR title and in OP?

**Comment by echo083** [comment]
> > Contribution init script for debian/ubuntu operating systems to cleanly automatically start and stop bitcoind.
> 
> > Yes indeed there is already a script for systemd but this script is intended to be used on RedHat operating systems and is not compatible with Debian/Ubuntu that's why I created this new one.
> 
> Why "debian/ubuntu" is mentioned in the PR title and in OP?

What OP means please?

If you are referring to the filename it's because there is already a script named bitcoind.init for RedHat operating systems so I thought it would the most appropriate name to differentiate the scripts, but if you want to give another name to this file it's fine for me. Also it's in the pull request description because it's the best description in my opinion except if you have a more generic name to reference debian/ubuntu operating systems i'd be happy to change that too.

Also keep in mind that I made this script for my personal needs and just wanted to share it, if you are not comfortable with the idea of merging it in the project it's fine for me.

Thanks

**Comment by luke-jr** [comment]
contrib/init/bitcoind.service should work fine on debian/ubuntu...

**Comment by hebasto** [comment]
> What OP means please?

"original post", i.e. pull request description.

**Comment by hebasto** [comment]
> Yes indeed there is already a script for systemd but this script is intended to be used on RedHat operating systems and is not compatible with Debian/Ubuntu that's why I created this new one.

It seems I mis-read your message. You mean that the current `bitcoind.service` in the repo is intended to be used on RedHat operating systems, right? I didn't run it on RedHat, but on Ubuntu it works just fine for me. What errors do you encounter?

**Comment by laanwj** [comment]
Thanks for your contribution. However the systemd service file *should* work on Ubuntu. If it does not at this time for you, it would be good to fix that.

I don't think including an old sysv-style init script is the right solution. Systemd contains some fallbacks to support this but that's at most a temporary situation, I suspect.

**Comment by echo083** [comment]
> Thanks for your contribution. However the systemd service file _should_ work on Ubuntu. If it does not at this time for you, it would be good to fix that.
> 
> I don't think including an old sysv-style init script is the right solution. Systemd contains some fallbacks to support this but that's at most a temporary situation, I suspect.

You can't adapt the existing script to work on any operating system using Systemd, for example the script bitcoind.init uses the file /etc/init.d/functions to get generic initialization functions which is specific to Redhat and doesn't exist on Debian/Ubuntu.
Depending on the operating system you want to support you can replace the existing script by mine, or reject my merge request.

**Comment by hebasto** [comment]
> You can't adapt the existing script to work on any operating system using Systemd, for example the script bitcoind.init uses the file /etc/init.d/functions to get generic initialization functions which is specific to Redhat and doesn't exist on Debian/Ubuntu.
> Depending on the operating system you want to support you can replace the existing script by mine, or reject my merge request.

Not `bitcoind.init`, but [`bitcoind.service`](https://github.com/bitcoin/bitcoin/blob/master/contrib/init/bitcoind.service) works with `systemd` just fine.

**Comment by laanwj** [comment]
Closing this, as it seems to be based on a misunderstanding.

**Pull request closed without merging**
