### PR TITLE
refactor: Fix prevector iterator concept issues

### PR DESCRIPTION
**Pull request by maflcko**
Currently prevector iterators have many issues:

* Forward iterators (and stronger) must be default constructible (https://eel.is/c++draft/forward.iterators#1.2). Otherwise, some functions can not be instantiated, like `std::minmax_element`.
* Various `const` issues with random access iterators. For example, a `const iterator` is different from a `const_iterator`, because the first one holds a mutable reference and must also return it without `const`. Also, `operator+` must be callable regardless of the iterator object's `const`-ness.
* When adding an offset to random access iterators, both `x+n` and `n+x` must be specified, see https://eel.is/c++draft/random.access.iterators#tab:randomaccessiterator

Fix all issues.

Also, upgrade the `std::random_access_iterator_tag` (C++17) to `std::contiguous_iterator_tag` (C++20)

### CODE REVIEW

**Comment by luke-jr** [comment]
Can we split the fixes from the C++20 stuff? The latter shouldn't be backported...

**Review by sedited — APPROVED** [review]
ACK fad74bbbd0ab4425573f182ebde1b31a99e80547

Could the `bitdeque` iterator also get `std::contiguous_iterator_tag`?

**Review by stickies-v — APPROVED** [review]
ACK fad74bbbd0ab4425573f182ebde1b31a99e80547

**Review by willcl-ark — APPROVED** [review]
ACK fad74bbbd0ab4425573f182ebde1b31a99e80547

Nice enhancements to safety, usability and standards.

**Pull request merged**
