### PR TITLE
 test: replace (send_message + sync_with_ping) with send_and_ping

### PR DESCRIPTION
**Pull request by jonatack**
This is a follow-up to faf1d047313e71658fb31f6b94fdd5d37705ab85 yesterday.

### CODE REVIEW

**Review by theStack — COMMENTED** [review]
Concept ACK
Note that in `p2p_filter.py` you could also tackle the sending-and-pinging of `msg_filterclear` in the last subtest. I think there are still many other occurences of this pattern in the functional tests (I saw them in at least 5-6 different tests recently as far as I remember), but as long as a PR approaches at least all per certain files that's ok I guess.

**Review by vasild — APPROVED** [review]
utACK 7e30eb7

**Comment by jonatack** [comment]
@theStack @vasild thank you -- updated with @theStack's suggestion as per `git diff 7e30eb7 5cd2f20`

**Comment by vasild** [comment]
re-utACK 5cd2f204d9028c609b61e523937d85c7aa8f8d12

**Comment by jonatack** [comment]
Thanks again @vasild. Added the remaining ones:  git diff 7e30eb7 6112a20

**Comment by vasild** [comment]
utACK 6112a20

**Review by theStack — CHANGES_REQUESTED** [review]
You almost catched them all now, after `grep`ping and inspecting the functional test I found three remaining occurences:
https://github.com/bitcoin/bitcoin/blob/6bdd515ccf1b0d3ec5990467db87b9f7963b9b51/test/functional/p2p_segwit.py#L128-L129
https://github.com/bitcoin/bitcoin/blob/6bdd515ccf1b0d3ec5990467db87b9f7963b9b51/test/functional/p2p_segwit.py#L140-L141
https://github.com/bitcoin/bitcoin/blob/6bdd515ccf1b0d3ec5990467db87b9f7963b9b51/test/functional/p2p_leak_tx.py#L42-L43

**Comment by jonatack** [comment]
@theStack thanks for verifying! I don't think the first two cases work, and the last one is already added unless I'm confused.

**Comment by theStack** [comment]
@jonatack: Oops, you are right, for some reason I overlooked that the change in `p2p_leak_tx.py` was already part of your commit. I don't see a reason why it wouldn't work for the first two cases.
Given that `node` is an instance of the class `P2PInterface`, the snippet
```
node.send_message(foobar);
node.sync_with_ping();
```
should behave exactly the same as 
```
node.sync_and_ping(foobar);
```
no matter how complex the expression `foobar` is. Or am I missing something here?

**Comment by MarcoFalke** [comment]
Can't this be done with a scripted diff?

```perl
perl -0777 -i -pe 's/\n([a-z A-Z\._]+)\.send_message\(([^\n]+)\)\n\1\.sync_with_ping\(\)\n/\n$1.send_and_ping($2)\n/gs'

**Comment by jonatack** [comment]
Thanks for reviewing. There are cases where it doesn't make sense, or where it breaks the test, to make the change. I think this now covers the correct ones and is ready.

**Comment by MarcoFalke** [comment]
ACK 6112a209828c43930f677c45461339cdf68a56e9 🎞

<details><summary>Show signature and timestamp</summary>

Signature:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK 6112a209828c43930f677c45461339cdf68a56e9 🎞
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEE+rVPoUahrI9sLGYTzit1aX5ppUgFAlwqrYAACgkQzit1aX5p
pUiYjwv9FE2tAKgeRs4uwRH/7SYYLQ/70VCkJzKFQbcZ92s44UF063cXkrff13Ey
l4vyJzOa/Nh88t/+L/2SfRrndkTBZkv6zVixK1FP5RQH/TezHIZK2Odse3Pyu78I
CcyFYQZ0vKCyMqFRIReoSgiWbcKDMMpcFY3NNNtT1WBjIhkd+n/3b+P5BcjFTYj0
m9cZJ9Bw68xNxBVWduwnq/E5YbmXhE8XXpAEAOPHB9XasHfQmV3k39r4txQsBL/6
Vt6REPiv4MwNjby/xEYiqikZhYF1cvla+Rgby56Fe7b0sLDO+c95BJvqOSUL1Vt9
ayi0X1sgN7VFrExHtEBtcnNECs9pedYBzP7kKUgQeENV2hdhwy5PGFOYTRxeor2l
2HOEVbCaff1oYzq/gWNbMH3M9e4c41P347sXqFLYqtIbGWU4QFZApTZ+1D0YfCta
R7NxrDHmmIyQy9ch6po44aJ+PO9T06b//qI1L78i20jcGegQQq2btSlaTqjBujns
D/YSdpwU
=BVs9
-----END PGP SIGNATURE-----
```

[Timestamp of file with hash `bba67858ba7d762e61143110f42d94eddd837c955e06827a1e1de70e2c30db8c  -`](https://opentimestamps.org/info/?004f70656e54696d657374616d7073000050726f6f6600bf89e2e884e892940108bba67858ba7d762e61143110f42d94eddd837c955e06827a1e1de70e2c30db8cf0101827c445cd59073a55287fe8219763b708fff01026e89f314b557cece6d1ff023f4a8fee08f1045e862af3f008b9038999c6bcee870083dfe30d2ef90c8e2c2b68747470733a2f2f626f622e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267fff010393774d3db5ef8897e410adf44129f7d08f1045e862af4f0083949a5330a0675350083dfe30d2ef90c8e292868747470733a2f2f66696e6e65792e63616c656e6461722e657465726e69747977616c6c2e636f6dfff01039c0907b36d4aa2c14907395e8cfd3ac08f1045e862af4f008a9460e02f1149ebd0083dfe30d2ef90c8e232268747470733a2f2f6274632e63616c656e6461722e636174616c6c6178792e636f6df010ef4590a806656b5c46b721b137d6e72808f1045e862af3f008c90235af9ce0b4ad0083dfe30d2ef90c8e2e2d68747470733a2f2f616c6963652e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267)

</details>

**Comment by MarcoFalke** [comment]
btw, I ran with the ones provided by @theStack in https://github.com/bitcoin/bitcoin/pull/18494#pullrequestreview-386418913 and the tests passed

**Comment by jonatack** [comment]
same... I suspect I ran them with `send_with_ping` by mistake

**Pull request merged**
