### PR TITLE
Do not turn OP_1NEGATE in scriptSig into 0x0181 in signing code

### PR DESCRIPTION
**Pull request by sipa**
Reported by arubi on IRC.

### CODE REVIEW

**Comment by laanwj** [comment]
Needs a unit test, I think.

**Comment by MarcoFalke** [comment]
Yeah, a test makes sense for this function, since it is not particularly well covered: https://marcofalke.github.io/btc_cov/total.coverage/src/script/sign.cpp.gcov.html

**Comment by fivepiece** [comment]
ACK on the fix!
Many thanks for looking into it :)

Before :
```
$ bitcoin-cli -regtest signrawtransactionwithwallet \
0200000001FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000044F024F9CFDFFFFFF01F0B9F505000000002321027777777777777777777777777777777777777777777777777777777777777777AC66030000 \
'[{"txid":"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF","vout":0,"scriptPubKey":"A914AE44AB6E9AA0B71F1CD2B453B69340E9BFBAEF6087","redeemScript":"4F9C","amount":1}]'

{                                                                                             VVVV
  "hex": "0200000001ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff00000000050181024f9cfdffffff01f0b9f505000000002321027777777777777777777777777777777777777777777777777777777777777777ac66030000",
  "complete": false,
  "errors": [
    {
      "txid": "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
      "vout": 0,
      "witness": [
      ],
      "scriptSig": "0181024f9c",
      "sequence": 4294967293,
      "error": "Data push larger than necessary"
    }
  ]
}
```

After:
```
$ bitcoin-cli -regtest signrawtransactionwithwallet \
0200000001FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000044F024F9CFDFFFFFF01F0B9F505000000002321027777777777777777777777777777777777777777777777777777777777777777AC66030000 \
'[{"txid":"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF","vout":0,"scriptPubKey":"A914AE44AB6E9AA0B71F1CD2B453B69340E9BFBAEF6087","redeemScript":"4F9C","amount":1}]' \

{                                                                                             VV
  "hex": "0200000001ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff00000000044f024f9cfdffffff01f0b9f505000000002321027777777777777777777777777777777777777777777777777777777777777777ac66030000",
  "complete": true
}
```

**Review by melG81 — APPROVED** [review]

**Comment by laanwj** [comment]
It looks like there is a copy of this function in `src/test/transaction_tests.cpp`: `static CScript PushAll(const std::vector<valtype>& values)` used in `ReplaceRedeemScript`. Does this need update as well?

**Comment by fanquake** [comment]
@sipa Would this be good to get into 0.17.0?

**Comment by MeshCollider** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/13084/commits/5af76250792b3bc7cedfdc8cd036ba4dcdb844c6 but as @laanwj says, looks like transaction_tests.cpp also needs updating

**Comment by meshcollider** [comment]
Closing in favor of #17204

**Pull request closed without merging**
