### PR TITLE
wallet: Fix segfault in CreateWalletFromFile, Pass error to rpc caller

### PR DESCRIPTION
**Pull request by maflcko**
`CreateWalletFromFile` has a bunch of issues:

* `walletFile` refers to freed memory and will thus corrupt the debug.log and/or crash the node if read
* `WalletParameterInteraction` was moved to `CreateWalletFromFile` and `WalletInit::ParameterInteraction` without updating the documentation
* `loadwallet` and `createwallet` will not pass up errors from `CreateWalletFromFile` to the RPC caller

Fix each of those issues in a separate commit.

### CODE REVIEW

**Comment by practicalswift** [comment]
Concept ACK -- very good find!

The problem was introduced in #15491 which was merged in to `master` on March 18.

@MarcoFalke While checking this PR I stumbled upon what seems to be another lifetime issue in `wallet.cpp`:

https://github.com/bitcoin/bitcoin/blob/fa6431055abfacea4f72ef11d061c7c755de327a/src/wallet/wallet.cpp#L107-L111

**Comment by MarcoFalke** [comment]
@practicalswift I think it would be better to open a new issue for the lifetime issue you mention. And either explain why it is a lifetime issue or even better, include a test case that fails on current master.

**Comment by practicalswift** [comment]
> And either explain why it is a lifetime issue or even better, include a test case that fails on current master.

Constructing a test case that fails on current `master` will be tricky since lifetime issues are typically not handled consistently across C++ compiler implementations, but explaining is easy:

After `delete wallet;` the pointer is invalid and shouldn't be used like in the call `g_unloading_wallet_set.erase(wallet)` :-)

https://github.com/bitcoin/bitcoin/blob/fa6431055abfacea4f72ef11d061c7c755de327a/src/wallet/wallet.cpp#L107-L111

**Review by ariard — APPROVED** [review]
ACK 6f51ece, reviewed code and tests pass, maybe segfault fix could be more elaborated on the manual process to trigger crash in its message commit.

**Comment by promag** [comment]
Concept ACK.

**Comment by MarcoFalke** [comment]
Split up the changes into separate commits and added a commit body with an explanation to each. Also, fixed an appveyor issue with `/` vs `\` in paths.

**Comment by MarcoFalke** [comment]
I will fix the GUI issue (`LC_ALL=de_DE.UTF-8 XDG_SESSION_TYPE=x11 BITCOIND=bitcoin-qt ./test/functional/wallet_multiwallet.py` does not pass) in a separate pull request and the daemon issue in #16796. Thanks for the input everyone.

**Pull request closed without merging**
