### PR TITLE
[Trivial, RPC] Fix and cleanup listreceivedbyX documentation

### PR DESCRIPTION
**Pull request by instagibbs**

### CODE REVIEW

**Comment by paveljanik** [comment]
Can you please also fix the commit message? Otherwise it is correct.

**Comment by instagibbs** [comment]
@paveljanik had to google how to, heh. fixed

**Comment by paveljanik** [comment]
@instagibbs Great - learning by doing. Thanks.

ACK

**Comment by MarcoFalke** [comment]
utACK  c372572. "Needs backport" label is missing?

**Comment by MarcoFalke** [comment]
Backported as part of #7938. Removing label 'Needs backport'.

**Pull request merged**
