### PR TITLE
system: skip trying to set the locale on NetBSD

### LINKED ISSUE #17379: Segfault running master on NetBSD
While testing 17270 I noticed that master (bdda137878904e9401a84e308ac74c93c2ef87c1) does not run on NetBSD. I assume this started after #17085 changed the fallback locale from `C` to `C.UTF-8`. There doesn't seem to be a `C.UTF-8` locale on NetBSD.

```bash
src/bitcoind
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
Abort trap (core dumped)
```

`LC_ALL=C src/bitcoind` works, `LC_ALL=en_US.UTF-8 src/bitcoind` does not.

```bash
locale
LANG=""
LC_CTYPE="en_US.UTF-8"
LC_COLLATE="C"
LC_TIME="C"
LC_NUMERIC="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_ALL=""
```

### PR DESCRIPTION
**Pull request by fanquake**
Just treat it the same as the other BSDs.

Fixes #17379.

### CODE REVIEW

**Comment by theStack** [comment]
Concept ACK

**Comment by tryphe** [comment]
Concept ACK

This change matches the intention of the comment above the changed line.

**Comment by laanwj** [comment]
I wonder at some point it wont make more sense to make this override Linux specific, "instead of all UNIXy systems-except-BSDs and MacOS".

**Comment by practicalswift** [comment]
cr ACK fdd71448e78f442ffd93a3a3398a5062eaba9f1b

**Comment by fanquake** [comment]
> This is a valid solution, just not nice to keep extending this list forever, there are so many BSDs.

Going to merge this for now. Agree that we could rework how this is done in future.

**Pull request merged**
