### PR TITLE
tests: shrink feature_taproot transfer of funds tx

### PR DESCRIPTION
**Pull request by ajtowns**
When moving funds from node 1 to node 0 for the pre-activation tests, there can be a large number of inputs, potentially resulting in a tx that is larger than standardness rules allow, or that takes a long time to sign. This just takes the top 500 outputs, which is plenty (~90% of the wallet balance).

### CODE REVIEW

**Review by luke-jr — APPROVED** [review]
tACK e68d3324f7ce821516b7b232cdd74add861ae78e

**Comment by jonatack** [comment]
Concept ACK, testing.

**Comment by jonatack** [comment]
On a sluggish Intel Core i7-6500U CPU @ 2.50GHz × 4

master
real	4m8.402s
user	5m30.459s
sys	0m12.095s

this patch
real	3m39.194s
user	4m52.800s
sys	0m12.868s

**Comment by luke-jr** [comment]
re-tACK ed8745a6f827791aee55764b44682fea8987017d

**Review by jonatack — COMMENTED** [review]
ACK  ed8745a6f827791aee55764b44682fea8987017d

**Comment by ajtowns** [comment]
Rebased further back in history so it's easy to backport to 0.21, and simplified to just pick the 500 unspents with the highest amount, rather than doing many transactions.

**Comment by luke-jr** [comment]
utACK 7ffac12545328cadd92a3caec4f1c6ca7c127493

**Comment by sipa** [comment]
utACK

**Comment by MarcoFalke** [comment]
cr ACK 7ffac12545328cadd92a3caec4f1c6ca7c127493

**Comment by jonatack** [comment]
ACK 7ffac12545328cadd92a3caec4f1c6ca7c127493

**Comment by MarcoFalke** [comment]
backported in #20431

**Pull request merged**
