### PR TITLE
build: don't use deprecated brew package names

### PR DESCRIPTION
**Pull request by fanquake**
Fixes:
```bash
checking for brew... brew
Warning: Use berkeley-db@4 instead of deprecated berkeley-db4
```

on macOS.

### CODE REVIEW

**Comment by hebasto** [comment]
Concept ACK.

Maybe also s/`qt5`/`qt@5`/ a few lines below?

**Comment by katesalazar** [comment]
Concept ACK.

https://github.com/bitcoin/bitcoin/blob/368831371d97a642beb54b5c4eb6eb0fedaa16b4/.cirrus.yml#L287

**Comment by fanquake** [comment]
> Maybe also s/qt5/qt@5/ a few lines below?

Done.

> Concept ACK.
> 
> https://github.com/bitcoin/bitcoin/blob/368831371d97a642beb54b5c4eb6eb0fedaa16b4/.cirrus.yml#L287

Added.

**Review by hebasto — APPROVED** [review]
ACK 4d83038714e4f099529e4372ef04f8f947c3a421, I have reviewed the code and it looks OK, I agree it can be merged.

**Comment by katesalazar** [comment]
Suggest replacing:

    build: don't check for deprecated berkeley-db4 package

    Fixes:
    ```bash
    checking for brew... brew
    Warning: Use berkeley-db@4 instead of deprecated berkeley-db4
    ```

For:

    build: don't check for deprecated berkeley-db4 package

    Fixes:

        checking for brew... brew
        Warning: Use berkeley-db@4 instead of deprecated berkeley-db4

Console output is not source code.

**Comment by mjdietzx** [comment]
Tested ACK 4d83038714e4f099529e4372ef04f8f947c3a421 on macOS Big Sur

**Pull request merged**
