### PR TITLE
[doc] qa: Move README.md and update -help

### PR DESCRIPTION
**Pull request by maflcko**
ci skip
skip ci

### CODE REVIEW

**Comment by fanquake** [comment]
Don't think this needs to be two commits.

**Comment by laanwj** [comment]
Is it better to move this? Looks like everything relates to the things below `qa/rpc-tests`. 

I'd prefer adding a more concise README.md in `qa` that describes the different directories in there.

**Comment by MarcoFalke** [comment]
@laanwj Tried to address your nits

**Comment by laanwj** [comment]
Looks good to me now

**Comment by gmaxwell** [comment]
ACK.

**Pull request merged**
