### PR TITLE
test: Add test for unknown args

### PR DESCRIPTION
**Pull request by maflcko**
Currently uncovered.

Further reading:

* https://marcofalke.github.io/btc_cov/total.coverage/src/util/system.cpp.gcov.html
*  Fail on unknown config file options #15021

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Requested by @hebasto as part of https://github.com/bitcoin/bitcoin/pull/16112#issuecomment-503169330

**Comment by hebasto** [comment]
Approach ACK.
Going to test tonight.

**Comment by promag** [comment]
ACK fa7dd88b71a1c6641bd450fae29a4a31849b1afd, tests looks good to me.

**Comment by hebasto** [comment]
ACK fa7dd88b71a1c6641bd450fae29a4a31849b1afd, I have tested the code.

**Pull request merged**
