### PR TITLE
travis: Remove travis

### LINKED ISSUE #16148: Travis timeouts
Travis generally times out when `./depends` changes or when a commonly included header file is changed. It currently needs human attention to run the job again and continue compiling from the last time the cache was saved.

Solutions to this could be:
* Run a helper script to poll travis failures and rerun them if the failure was due to a timeout.
* Rerun about-to-time-out jobs from within travis
* Switch to another CI solution. We currently have travis, appveyor and (not enabled) Cirrus CI, so we'd have to get rid of at least one of them before adding a new one.

### PR DESCRIPTION
**Pull request by maflcko**
Travis stopped working for no apparent reason and no way to fix, so remove it. Tests are still run on appveyor and developers can run tests locally with `make  check && ./test/functional/test_runner.py`.

Fixes  #16148  (Travis timeouts)

### CODE REVIEW

**Comment by laanwj** [comment]
Drastic.

I'd prefer to have a replacement for Travis first, and not rely on Appveyor only. The drawback of local testing is that it only covers one platform, generally.

On the other hand, if Travis has become useless then this makes sense, I'm sure false positives consume a lot of developer time.

**Comment by practicalswift** [comment]
Concept NACK

Doing this as suggested is a very risky move: we will lose automated testing under ASan, TSan, UBSan and Clang thread-sanitiser analyser.

This should not be rushed.

**Comment by practicalswift** [comment]
Until we have a proper Travis replacement in place: why don't we just pay Travis to get this resolved?

Paid working Travis must be strictly better than this rushed "no Travis" alternative, no?

**Comment by fanquake** [comment]
> why don't we just pay Travis to get this resolved?

We already pay Travis as far as I’m aware.

**Comment by practicalswift** [comment]
> We already pay Travis as far as I’m aware.

No we don't :-)

See https://github.com/bitcoin/bitcoin/issues/16148#issuecomment-499287945.

**Comment by laanwj** [comment]
I don't think it's as easy as "simply pay travis".
There might be other CI hosters more open to paid service for open source projects, but for Travis this has always been difficult.

**Comment by MarcoFalke** [comment]
We used to pay them, but they nudged us about a renewal. And in light of it being useless, I don't see why we should purchase parallel jobs again.


> Hi Marco,

> My name is Sara and I am your new Renewals Representative for Travis-CI. Our record indicates that your subscription for 15 build plan expired on April 4, 2019

> If this is an over-sight, please let me know and I will send you a quote to reactive your subscription. Or if you have decide to not renew your subscription, I would appreciate if you could give me a short feedback on your experience with Travis-CI and the features you would like to see in Travis-CI in future.

> I look forward to hearing from you soon.

> Thank you and have a great day.

**Comment by practicalswift** [comment]
> We used to pay them, but they nudged us about a renewal. And in light of it being useless, I don't see why we should purchase parallel jobs again.

I would like to pay until we have a proper Travis replacement in place. I find it very important that we don't lose automated sanitiser testing for all new code entering the repo.

Where shall I send money and how much? Perhaps it would be easiest to pay it one year in advance to minimise administrative overhead. Feel free to mail me the details.

**Comment by MarcoFalke** [comment]
@practicalswift Travis is not running because the caching is not working. Throwing money at them won't magically fix that.

I have a ticket with them `Travis CI: [8383] - Caching issues on travis infrastructure`. You are welcome to contact support as well or try to fix the caching issue in some way. Though, if we can't fix it there is no point in either keeping travis or paying them.

We absolutely need a working cache to build depends and then build Bitcoin Core based on those depends to mimick our release binaries that are also built with depends. Without a cache, compile times are not manageable.

**Comment by MarcoFalke** [comment]
I am going to purge all caches again and re-run some builds, but honestly I am not expecting anything to change.

**Comment by jonasschnelli** [comment]
Instead of completely removing, would it make sense to reduce Travis to only build against system libraries (remove the depends builds)? Then eventually add the dependency builds through semaphore2 with the restriction of missing public view access to the build log for now.

**Comment by MarcoFalke** [comment]
@jonasschnelli Yeah, that would be an option, but then we'd maintain three ci solutions. Not sure if that scales well.

**Comment by MarcoFalke** [comment]
Deleting all caches and rerunning some builds didn't fix anything. Also, the travis output of the cacher is completely useless:

https://travis-ci.org/bitcoin/bitcoin/jobs/545179929#L152

**Comment by jonasschnelli** [comment]
@MarcoFalke maintaining one additional CI during a time of transition (or uncertainty) is probably okay.

Would implementing our own cacher be an option (tar, upload to a custom filespace)?

**Comment by luke-jr** [comment]
I also tried to solve caching with Travis before our paid service expired, and their support staff were useless.

No reason to keep Travis enabled when it isn't doing anything useful. Sure, it'd be great to have *San tests running automatically, but right now they don't seem to be.

**Comment by practicalswift** [comment]
Is it just me... or is Travis feeling faster than ever before since yesterday? :-)

**Comment by MarcoFalke** [comment]
Ok, closing until we found a replacement.

**Comment by practicalswift** [comment]
@MarcoFalke Can you describe what happened yesterday?

Did we start paying? Did Travis put the correct engineer on the case? Or both? :-)

 I'm trying to understand why it is suddenly super quick and if the current swiftness can be assumed to be permanent or not.

**Comment by MarcoFalke** [comment]
@practicalswift Nothing sped up. It is back to normal.

See the reply here: https://github.com/bitcoin/bitcoin/issues/16148#issuecomment-503289922

**Comment by practicalswift** [comment]
@MarcoFalke Ah, so Travis pushed a fix and everything else remained constant. Does Travis work as we want it to now? I.e. should we see the "Travis situation" as resolved?

I take it we are not paying?

**Comment by MarcoFalke** [comment]
I asked them for a quote for the next year, but they haven't replied yet.

**Pull request closed without merging**
