### PR TITLE
validation, zmq: pass block in UpdatedBlockTip to avoid duplicate read

### PR DESCRIPTION
**Pull request by andrewtoth**
When `CZMQPublishRawBlockNotifier::NotifyBlock` is called it calls `ReadBlockFromDisk` with the passed in block index. However, we will always have already read this block into memory during `ActivateBestChain` and use it to call `BlockConnected`. We can check for the tip block there and pass that into `UpdatedBlockTip` to avoid having the zmq notifier read the block. This also has the benefit of removing the `node/blockstorage.h` dependency entirely from the zmq code, so we can continue working to remove `ReadBlockFromDisk` out of global scope (https://github.com/bitcoin/bitcoin/pull/26316#discussion_r1000954807).

### CODE REVIEW

**Review by aureleoules — APPROVED** [review]
ACK 7b631dc9b1979afc99d9d1a3996492dcb415d3a3 - LGTM

**Review by w0xlt — APPROVED** [review]
crACK https://github.com/bitcoin/bitcoin/pull/26375/commits/7b631dc9b1979afc99d9d1a3996492dcb415d3a3

**Comment by MarcoFalke** [comment]
This will increase the memory use even if not using zmq. I guess it is fine because the queue is limited?

**Comment by andrewtoth** [comment]
> This will increase the memory use even if not using zmq. I guess it is fine because the queue is limited?

That sounds accurate. It seems `LimitValidationInterfaceQueue` in the loop prevents this from blowing up.

**Pull request closed without merging**
