### PR TITLE
ci: Bump `TIDY_LLVM_V`

### PR DESCRIPTION
**Pull request by hebasto**
This PR switches to the latest [IWYU 0.22](https://github.com/include-what-you-use/include-what-you-use/releases/tag/0.22), which is compatible with Clang 18.

### CODE REVIEW

**Comment by fanquake** [comment]
> This PR switches to the latest [IWYU 0.22](https://github.com/include-what-you-use/include-what-you-use/releases/tag/0.22)

Where is this change?

**Comment by hebasto** [comment]
> > This PR switches to the latest [IWYU 0.22](https://github.com/include-what-you-use/include-what-you-use/releases/tag/0.22)
> 
> Where is this change?

The IWYU branch being built is `clang_"${TIDY_LLVM_V}"`: https://github.com/bitcoin/bitcoin/blob/af2cd8e64d90308f71007198c63a51be6a5937dc/ci/test/01_base_install.sh#L70:

**Comment by fanquake** [comment]
CI is failing:
```bash
clang-tidy-18 -p=/ci_container_base/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu -quiet -load=/tidy-build/libbitcoin-tidy.so /ci_container_base/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/src/script/miniscript.cpp
./script/interpreter.h:28:1: error: enum '(unnamed enum at ./script/interpreter.h:28:1)' uses a larger base type ('unsigned int', size: 4 bytes) than necessary for its value set, consider using 'std::uint8_t' (1 byte) as the base type to reduce its size [performance-enum-size,-warnings-as-errors]
   28 | enum
      | ^
./script/interpreter.h:190:12: error: enum 'SigVersion' uses a larger base type ('int', size: 4 bytes) than necessary for its value set, consider using 'std::uint8_t' (1 byte) as the base type to reduce its size [performance-enum-size,-warnings-as-errors]
  190 | enum class SigVersion
      |            ^
./script/interpreter.h:274:12: error: enum 'MissingDataBehavior' uses a larger base type ('int', size: 4 bytes) than necessary for its value set, consider using 'std::uint8_t' (1 byte) as the base type to reduce its size [performance-enum-size,-warnings-as-errors]
  274 | enum class MissingDataBehavior
      |            ^
./script/miniscript.h:194:12: error: enum 'Fragment' uses a larger base type ('int', size: 4 bytes) than necessary for its value set, consider using 'std::uint8_t' (1 byte) as the base type to reduce its size [performance-enum-size,-warnings-as-errors]
  194 | enum class Fragment {
      |            ^
./script/miniscript.h:228:12: error: enum 'Availability' uses a larger base type ('int', size: 4 bytes) than necessary for its value set, consider using 'std::uint8_t' (1 byte) as the base type to reduce its size [performance-enum-size,-warnings-as-errors]
  228 | enum class Availability {
      |            ^
./script/miniscript.h:234:12: error: enum 'MiniscriptContext' uses a larger base type ('int', size: 4 bytes) than necessary for its value set, consider using 'std::uint8_t' (1 byte) as the base type to reduce its size [performance-enum-size,-warnings-as-errors]
  234 | enum class MiniscriptContext {
      |            ^
./script/miniscript.h:1663:12: error: enum 'ParseContext' uses a larger base type ('int', size: 4 bytes) than necessary for its value set, consider using 'std::uint8_t' (1 byte) as the base type to reduce its size [performance-enum-size,-warnings-as-errors]
 1663 | enum class ParseContext {
      |            ^
./script/miniscript.h:2152:12: error: enum 'DecodeContext' uses a larger base type ('int', size: 4 bytes) than necessary for its value set, consider using 'std::uint8_t' (1 byte) as the base type to reduce its size [performance-enum-size,-warnings-as-errors]
 2152 | enum class DecodeContext {
      |            ^
./script/script.h:72:6: error: enum 'opcodetype' uses a larger base type ('unsigned int', size: 4 bytes) than necessary for its value set, consider using 'std::uint8_t' (1 byte) as the base type to reduce its size [performance-enum-size,-warnings-as-errors]
   72 | enum opcodetype
      |      ^
./script/script_error.h:11:14: error: enum 'ScriptError_t' uses a larger base type ('unsigned int', size: 4 bytes) than necessary for its value set, consider using 'std::uint8_t' (1 byte) as the base type to reduce its size [performance-enum-size,-warnings-as-errors]
   11 | typedef enum ScriptError_t
      |              ^
./script/solver.h:22:12: error: enum 'TxoutType' uses a larger base type ('int', size: 4 bytes) than necessary for its value set, consider using 'std::uint8_t' (1 byte) as the base type to reduce its size [performance-enum-size,-warnings-as-errors]
   22 | enum class TxoutType {
```

**Review by fanquake — APPROVED** [review]
ACK 636c9862cfc8b3facc84eb62b51e18877f2022a9

**Pull request merged**
