### PR TITLE
test: Adding functional test for -maxuploadtarget with byte unit 'M'

### PR DESCRIPTION
**Pull request by dougEfresh**
Adding new functional test  for -maxuploadtarget
Same tests as in `test/functional/feature_maxuploadtarget.py` but with  `-maxuploadtarget=800M`

### CODE REVIEW

**Review by brunoerg — COMMENTED** [review]
In `feature_maxuploadtarget.py`, it tests the `maxuploadtarget` with two values 800 and 1. See:
https://github.com/bitcoin/bitcoin/blob/64059b78f59e45cc4200ca76d0af8c6dff8a20d4/test/functional/feature_maxuploadtarget.py#L144

I think the approach you took we would be testing `-maxuploadtarget=1` twice when executing `feature_maxuploadtarget_byteunit.py` and `feature_maxuploadtarget.py`.  Maybe, you can create another variable to it? And then, you can test 1M?

**Comment by dougEfresh** [comment]
> In `feature_maxuploadtarget.py`, it tests the `maxuploadtarget` with two values 800 and 1. See:
> 
Updated to include `1M`

**Review by luke-jr — CHANGES_REQUESTED** [review]
Prefer to keep it in the existing file

**Comment by dougEfresh** [comment]
> Prefer to keep it in the existing file

Agreed.
It was easier for me to open a new PR, closing this one, new PR #23648

**Pull request closed without merging**
