### PR TITLE
test: Fix intermittent failure in feature_segwit

### LINKED ISSUE #24590: qa: Intermittent failure in feature_segwit.py --descriptors
https://api.cirrus-ci.com/v1/task/5763159330914304/logs/ci.log
```
5/238 - feature_segwit.py --descriptors failed, Duration: 11 s

stdout:
2022-03-16T18:38:33.242000Z TestFramework (INFO): Initializing test directory /tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_₿_🏃_20220316_183814/feature_segwit_225
2022-03-16T18:38:39.177000Z TestFramework (INFO): Verify sigops are counted in GBT with pre-BIP141 rules before the fork
2022-03-16T18:38:43.168000Z TestFramework (INFO): Verify witness txs cannot be mined before the fork
2022-03-16T18:38:43.200000Z TestFramework (INFO): Verify unsigned p2sh witness txs without a redeem script are invalid
2022-03-16T18:38:43.630000Z TestFramework (ERROR): JSONRPC error
Traceback (most recent call last):
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 132, in main
    self.run_test()
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/feature_segwit.py", line 210, in run_test
    self.generate(self.nodes[0], 4)  # blocks 428-431
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 639, in generate
    blocks = generator.generate(*args, invalid_call=False, **kwargs)
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_node.py", line 303, in generate
    return self.generatetoaddress(nblocks=nblocks, address=self.get_deterministic_priv_key().address, maxtries=maxtries, **kwargs)
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_node.py", line 311, in generatetoaddress
    return self.__getattr__('generatetoaddress')(*args, **kwargs)
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/coverage.py", line 49, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/authproxy.py", line 144, in __call__
    raise JSONRPCException(response['error'], status)
test_framework.authproxy.JSONRPCException: CreateNewBlock: TestBlockValidity failed: unexpected-witness, ContextualCheckBlock : unexpected witness data found (-1)
2022-03-16T18:38:43.682000Z TestFramework (INFO): Stopping nodes
2022-03-16T18:38:43.856000Z TestFramework (WARNING): Not cleaning up dir /tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_₿_🏃_20220316_183814/feature_segwit_225
2022-03-16T18:38:43.856000Z TestFramework (ERROR): Test failed. Test logging available at /tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_₿_🏃_20220316_183814/feature_segwit_225/test_framework.log
2022-03-16T18:38:43.866000Z TestFramework (ERROR): 
2022-03-16T18:38:43.866000Z TestFramework (ERROR): Hint: Call /tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/combine_logs.py '/tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_₿_🏃_20220316_183814/feature_segwit_225' to consolidate all logs
2022-03-16T18:38:43.866000Z TestFramework (ERROR): 
2022-03-16T18:38:43.866000Z TestFramework (ERROR): If this failure happened unexpectedly or intermittently, please file a bug and provide a link or upload of the combined log.
2022-03-16T18:38:43.867000Z TestFramework (ERROR): https://github.com/bitcoin/bitcoin/issues
2022-03-16T18:38:43.867000Z TestFramework (ERROR): 
```

### PR DESCRIPTION
**Pull request by maflcko**
There are intermittent failures on current master (https://github.com/bitcoin/bitcoin/pull/24421#issuecomment-1067451667) as the witness txs occasionally make it into other node's mempools when they shouldn't.

Fix this by removing the test as suggested earlier in https://github.com/bitcoin/bitcoin/pull/24421#discussion_r822933721.

Fixes https://github.com/bitcoin/bitcoin/issues/24590

### CODE REVIEW

**Comment by aureleoules** [comment]
tACK d6b24e14d2a828ba7328f0cae1d0d7c5f4f6b3bd.
Tested on NixOS 22.05 64 bits.

I was able to reproduce the bug (https://github.com/bitcoin/bitcoin/pull/24421#issuecomment-1067451667) prior to this fix using: `seq 100 | xargs -i -P 20 python test/functional/feature_segwit.py` (100 tests in batches of 20).  
Could not reproduce the bug after this PR using the same command with 1000 tests.

**Comment by jnewbery** [comment]
Code review ACK d6b24e14d2a828ba7328f0cae1d0d7c5f4f6b3bd

Is there a way to introduce random sleeps into the test logic to flush out other racy test bugs?

**Comment by MarcoFalke** [comment]
Sure, it should be possible to inject a random sleep after sendrawtransaction. Though, I am not sure if this is going to give consistent results either. I think the only way would be to do the same for txs that was done for blocks. (Always sync unless opted out).

**Comment by glozow** [comment]
post merge ACK

**Pull request merged**
