### PR TITLE
Update to latest libsecp256k1

### PR DESCRIPTION
**Pull request by sipa**
Includes several code cleanups and improved tests, but also fixes the OpenSSL 1.1 issue.

### CODE REVIEW

**Comment by gmaxwell** [comment]
ACK

**Comment by paveljanik** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/9334/commits/547a53d13507b3348d216d82353e0d6a9d8fa974

**Comment by fanquake** [comment]
utACK 547a53d

**Comment by laanwj** [comment]
utACK 547a53d

**Comment by rebroad** [comment]
What was the OpenSSL issue?

**Pull request merged**
