### PR TITLE
Update headers for v0.19

### PR DESCRIPTION
**Pull request by GChuf**
Updates headers for version 0.19 with the updated "copyright_header.py" script. It now includes `.sh` and `.bash-completion` files as well.

### CODE REVIEW

**Comment by emilengler** [comment]
Concept NACK.
The planned release date is `2020-01-03`.
This means that there might be some code changes in 2020 as well.
I think that this script should executed at the end of every year and SHORTLY before a release.
@laanwj When you do the final commits, could you run this script again?

**Comment by emilengler** [comment]
Also running this script to often is not a good approach. You are changing 287 files which means that if a user is currently working on a file which was changed by you he would need to rebase which wouldn't be the effort worth in my opinion. Sorry.

**Comment by laanwj** [comment]
AFAIK the current way of working is to run this script at the end of a year. It doesn't really have anything to do with the release cycle.

**Comment by emilengler** [comment]
@laanwj 
IIRC @DrahtBot runs opens a PR for this every year.
However in #16789 @MarcoFalke said that this should be done before every new release.
I agree with this because the release is also delivered as a (de-facto) tarball and it should correct there as well.
So I would suggest to add this process to the release process as well

**Comment by laanwj** [comment]
I don't agree. I don't care if the copyright years are a year off.

**Pull request closed without merging**
